### ISSUE TITLE
Test failure: GC\\API\\NoGCRegion\\Callback_Svr\\Callback_Svr.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100052]
**Failed in:** [runtime-coreclr outerloop 20240320.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610284&view=ms.vss-test-web.build-test-results-tab&runId=14900364&resultId=117141&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - GC\\API\\NoGCRegion\\Callback_Svr\\Callback_Svr.cmd
coreclr windows x64 Checked @ Windows.10.Amd64.Open
    - GC\\API\\NoGCRegion\\Callback_Svr\\Callback_Svr.cmd
R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
    - GC\\API\\NoGCRegion\\Callback_Svr\\Callback_Svr.cmd
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - GC\\API\\NoGCRegion\\Callback_Svr\\Callback_Svr.cmd
```

**Error message:**
```
 
Assert failure(PID 8372 [0x000020b4], Thread: 8396 [0x20cc]): promoted_bytes (heap_number) == promoted

CORECLR! SVR::gc_heap::mark_phase + 0x167C (0x00007ffb`2376149c)
CORECLR! SVR::gc_heap::gc1 + 0x240 (0x00007ffb`23753220)
CORECLR! SVR::gc_heap::garbage_collect + 0x99B (0x00007ffb`23752f8b)
CORECLR! SVR::gc_heap::gc_thread_function + 0x504 (0x00007ffb`23754934)
CORECLR! SVR::gc_heap::gc_thread_stub + 0x7E (0x00007ffb`23754dde)
CORECLR! <lambda_07428600c89a72b48ab39053bd192909>::<lambda_invoker_cdecl> + 0x74 (0x00007ffb`2341e204)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ffb`538984d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ffb`53991791)
    File: D:\a\_work\1\s\src\coreclr\gc\gc.cpp:24234
    Image: C:\h\w\AE9A0A3C\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\AE9A0A3C\w\ABCC0989\uploads\Reports\GC.API\NoGCRegion\Callback_Svr\Callback_Svr.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AE9A0A3C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Callback_Svr.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 3/20/2024 9:31:58 PM
Processing C:\cores\corerun.exe.8372.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\cdb.exe -c "$<C:\h\w\AE9A0A3C\t\tmpcyn54r.tmp" -z "C:\cores\corerun.exe.8372.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.8372.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\AE9A0A3C\p\PDB
Symbol search path is: C:\h\w\AE9A0A3C\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Wed Mar 20 21:32:03.000 2024 (UTC + 0:00)
System Uptime: 0 days 1:08:36.763
Process Uptime: 0 days 0:00:04.000
..............................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(20b4.20cc): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
KERNELBASE!RaiseFailFastException+0xae:
00007ffb`507b96ce 803d4d78120000  cmp     byte ptr [KERNELBASE!local_unwind+0x7fe2 (00007ffb`508e0f22)],0 ds:00007ffb`508e0f22=00
0:005> cdb: Reading initial command '$<C:\h\w\AE9A0A3C\t\tmpcyn54r.tmp'
0:005> .load C:\Users\runner\.dotnet\sos\sos.dll
0:005> ~*k

   0  Id: 20b4.20b8 Suspend: 0 Teb: 000000d1`27987000 Unfrozen
Child-SP          RetAddr           Call Site
000000d1`27b7d5f8 00007ffb`50716d1f ntdll!ZwWaitForSingleObject+0x14
000000d1`27b7d600 00007ffb`2377b5a2 KERNELBASE!WaitForSingleObjectEx+0x8f
000000d1`27b7d6a0 00007ffb`23730f09 coreclr!SVR::gc_heap::wait_for_gc_done+0x1b2
000000d1`27b7d700 00007ffb`23776f01 coreclr!SVR::GCHeap::GarbageCollectGeneration+0x359
000000d1`27b7d750 00007ffb`2372fa10 coreclr!SVR::gc_heap::trigger_gc_for_alloc+0x71
(Inline Function) --------`-------- coreclr!SVR::gc_heap::try_allocate_more_space+0xca
(Inline Function) --------`-------- coreclr!SVR::gc_h
```

**Stack trace:**
```
   at GC_API._NoGCRegion_Callback_Svr_Callback_Svr_._NoGCRegion_Callback_Svr_Callback_Svr_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
Dup of https://github.com/dotnet/runtime/issues/100035

@markples @mangod9
