### ISSUE TITLE
Test failure: GC\\LargeMemory\\API\\gc\\gettotalmemory\\gettotalmemory.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100053]
**Failed in:** [runtime-coreclr crossgen2 20240319.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609486&view=ms.vss-test-web.build-test-results-tab&runId=14873546&resultId=112079&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows arm64 Checked @ Windows.11.Arm64.Open
    - GC\\LargeMemory\\API\\gc\\gettotalmemory\\gettotalmemory.cmd
```

**Error message:**
```
 Failed to load: 'C:\h\w\AC5009BF\p\coreclr.dll'. Error: 0x000005aa

Return code:      1
Raw output file:      C:\h\w\AC5009BF\w\9F0C088B\uploads\Reports\GC.LargeMemory\API\gc\gettotalmemory\gettotalmemory.output.txt
Raw output:
BEGIN EXECUTION
gettotalmemory.dll
largeobject.dll
memcheck.dll
        3 file(s) copied.
 7:40:10.95
Response file: C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.dll.rsp
C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\IL-CG2\gettotalmemory.dll
-o:C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AC5009BF\p\System.*.dll
-r:C:\h\w\AC5009BF\p\Microsoft.*.dll
-r:C:\h\w\AC5009BF\p\xunit.*.dll
-r:C:\h\w\AC5009BF\p\mscorlib.dll
-r:C:\h\w\AC5009BF\p\netstandard.dll
" "dotnet" "C:\h\w\AC5009BF\p\crossgen2\crossgen2.dll" @"C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.dll.rsp"   -r:C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.dll
" "dotnet" "C:\h\w\AC5009BF\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.dll --out C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\gettotalmemory.dll.r2rdump --val"
 7:40:14.23
 7:40:14.25
Response file: C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\largeobject.dll.rsp
C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\IL-CG2\largeobject.dll
-o:C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\largeobject.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AC5009BF\p\System.*.dll
-r:C:\h\w\AC5009BF\p\Microsoft.*.dll
-r:C:\h\w\AC5009BF\p\xunit.*.dll
-r:C:\h\w\AC5009BF\p\mscorlib.dll
-r:C:\h\w\AC5009BF\p\netstandard.dll
" "dotnet" "C:\h\w\AC5009BF\p\crossgen2\crossgen2.dll" @"C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\largeobject.dll.rsp"   -r:C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\largeobject.dll
" "dotnet" "C:\h\w\AC5009BF\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\largeobject.dll --out C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\largeobject.dll.r2rdump --val"
 7:40:18.31
 7:40:18.43
Response file: C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\memcheck.dll.rsp
C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\IL-CG2\memcheck.dll
-o:C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\memcheck.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AC5009BF\p\System.*.dll
-r:C:\h\w\AC5009BF\p\Microsoft.*.dll
-r:C:\h\w\AC5009BF\p\xunit.*.dll
-r:C:\h\w\AC5009BF\p\mscorlib.dll
-r:C:\h\w\AC5009BF\p\netstandard.dll
" "dotnet" "C:\h\w\AC5009BF\p\crossgen2\crossgen2.dll" @"C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\memcheck.dll.rsp"   -r:C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\memcheck.dll
" "dotnet" "C:\h\w\AC5009BF\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\memcheck.dll --out C:\h\w\AC5009BF\w\9F0C088B\e\GC\LargeMemory\API\gc\gettotalmemory\memcheck.dll.r2rdump --val"
 7:40:25.82
 "C:\h\w\AC5009BF\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatter
```

**Stack trace:**
```
   at GC_LargeMemory._API_gc_gettotalmemory_gettotalmemory_._API_gc_gettotalmemory_gettotalmemory_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by steveisok** [comment]
@ivdiazsa please determine if this is still an issue

**Comment by ivdiazsa** [comment]
Was not able to reproduce locally and has not showed up in the pipelines in the past month or so.
