### ISSUE TITLE
gcServer + forcerelocs --> JIT/jit64/regress/vsw/373472/test fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#10002]
`JIT/jit64/regress/vsw/373472/test/test.sh` fails with configuration gcServer + forcerelocs
Similarly `JIT/jit64/regress/vsw/373472/test_il/test_il.sh`
```
corerun test.exe
test1 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StrideTest.Test1()
Test1 failed
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StrideTest.Test2()
Test2 failed
Expected: 100
Actual: 1
```

@dotnet/arm64-contrib @Maoni0 @swgillespie @sywhang FYI

**Comment by v-haren** [comment]
failed again in job: [ runtime-coreclr jitstress-isas-x86 20200829.1](https://dev.azure.com/dnceng/public/_build/results?buildId=793813&view=ms.vss-test-web.build-test-results-tab&runId=25096258&resultId=100746&paneView=debug)

CoreCLR Windows_NT x86 Checked jitstress_isas_nohwintrinsic @ Windows.10.Amd64.Open


Error message
~~~
Return code:      1
Raw output file:      C:\h\w\B7920A65\w\AFE709AB\e\JIT\jit64\Reports\JIT.jit64\regress\vsw\373472\test\test.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B7920A65\p\corerun.exe" test.dll 
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StrideTest.Test2()
Test2 failed
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StrideTest.Test3()
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B7920A65\p
> C:\h\w\B7920A65\w\AFE709AB\e\JIT\jit64\regress\vsw\373472\test\test.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\JIT.jit64\JIT.jit64.XUnitWrapper.cs:line 82008
~~~

**Comment by mangod9** [comment]
Hi @v-haren does this failure consistently repro? I believe this is due to low memory machines the test runs on?

**Comment by sdmaclea** [comment]
FWIW the initial report came from a machine with 16GB physical memory.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress 20210218.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1002474&view=ms.vss-test-web.build-test-results-tab&runId=31328740&resultId=100280&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked zapdisable @ Windows.10.Amd64.Open
 -JIT\\jit64\\regress\\vsw\\373472\\test\\test.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\B02D094A\w\A66D08EC\e\JIT\jit64\Reports\JIT.jit64\regress\vsw\373472\test\test.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B02D094A\p\corerun.exe" test.dll 
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test2()
Test2 failed
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test3()
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B02D094A\p
> C:\h\w\B02D094A\w\A66D08EC\e\JIT\jit64\regress\vsw\373472\test\test.cmd
Expected: True
Actual: False

Stack trace
   at JIT_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress 20210313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1038365&view=ms.vss-test-web.build-test-results-tab&runId=32186802&resultId=100453&paneView=debug)

Failed tests:
```
JIT\\jit64\\regress\\vsw\\373472\\test_il\\test_il.cmd
JIT\\jit64\\regress\\vsw\\373472\\test\\test.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\B0C609B2\w\B4DC09FE\e\JIT\jit64\Reports\JIT.jit64\regress\vsw\373472\test_il\test_il.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B0C609B2\p\corerun.exe" test_il.dll 
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test2()
Test2 failed
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test3()
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B0C609B2\p
> C:\h\w\B0C609B2\w\B4DC09FE\e\JIT\jit64\regress\vsw\373472\test_il\test_il.cmd
Expected: True
Actual: False

Stack trace
   at JIT_jit64._regress_vsw_373472_test_il_test_il_._regress_vsw_373472_test_il_test_il_cmd()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress 20210329.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1062826&view=ms.vss-test-web.build-test-results-tab&runId=32743214&resultId=101869&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked zapdisable @ Windows.10.Amd64.Open
 -JIT\\jit64\\regress\\vsw\\373472\\test\\test.cmd
```

**Error message:**
```

Return code: 1
Raw output file: C:\h\w\9D2308F5\w\A1D6088E\e\JIT\jit64\Reports\JIT.jit64\regress\vsw\373472\test\test.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\9D2308F5\p\corerun.exe" test.dll 
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test2()
Test2 failed
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test3()
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\9D2308F5\p
> C:\h\w\9D2308F5\w\A1D6088E\e\JIT\jit64\regress\vsw\373472\test\test.cmd
Expected: True
Actual: False

Stack trace
   at JIT_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd()


```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210425.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1106740&view=ms.vss-test-web.build-test-results-tab&runId=33792476&resultId=100522&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
 -JIT\\jit64\\regress\\vsw\\373472\\test\\test.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\B10E09AA\w\AD8909B9\e\JIT\jit64\Reports\JIT.jit64\regress\vsw\373472\test\test.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B10E09AA\p\corerun.exe" test.dll 
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test3() in test.dll:token 0x6000004+0x2
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B10E09AA\p
> C:\h\w\B10E09AA\w\AD8909B9\e\JIT\jit64\regress\vsw\373472\test\test.cmd
Expected: True
Actual: False

Stack trace
   at JIT_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210502.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1117964&view=ms.vss-test-web.build-test-results-tab&runId=34040540&resultId=100706&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
 -JIT\\jit64\\regress\\vsw\\373472\\test\\test.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\9B2708B2\w\AEF708F1\e\JIT\jit64\Reports\JIT.jit64\regress\vsw\373472\test\test.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\9B2708B2\p\corerun.exe" test.dll 
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
 at StrideTest.Test3() in test.dll:token 0x6000004+0x2
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\9B2708B2\p
> C:\h\w\9B2708B2\w\AEF708F1\e\JIT\jit64\regress\vsw\373472\test\test.cmd
Expected: True
Actual: False

Stack trace
   at JIT_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd()

```
