### ISSUE TITLE
System.Net.Tests.HttpListenerRequestTests fail with SocketException : Connection refused

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#100088]
```
    System.Net.Tests.HttpListenerRequestTests.ContentEncoding_GetProperty_ReturnsExpected(header: "Content-Type:", expected: UTF8EncodingSealed { BodyName = "utf-8", CodePage = 65001, DecoderFallback = DecoderReplacementFallback { DefaultString = "�", MaxCharCount = 1 }, EncoderFallback = EncoderReplacementFallback { DefaultString = "�", MaxCharCount = 1 }, EncodingName = "Unicode (UTF-8)", ··· }) [FAIL]
      System.Net.Sockets.SocketException : Connection refused 127.0.0.1:1293
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3216,0): at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(838,0): at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(922,0): at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=611434
Build error leg or test failing: System.Net.HttpListener.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/100066

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.Net.Tests.HttpListenerRequestTests.ContentEncoding_GetProperty_ReturnsExpected.*FAIL",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci has this has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by wfurt** [comment]
low hit count, moving to future.

**Comment by danmoseley** [comment]
Failure Oct 2025, another Nov 2025, none since then.
