### ISSUE TITLE
IOException when creating a global mutex on macOS

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#100135]
### Description

We have a customer that reported getting the following exception when our code is creating a global named `Mutex` on macOS (see https://github.com/postsharp/Metalama/issues/272):

```
Unhandled exception. System.IO.IOException: The system cannot open the device or file specified. : 'Global\Metalama.Configuration'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
```

The exception happened consistently, but did not reoccur after restarting the machine, so it seems it's caused by some corrupted temporary state.

What could have caused this situation? Could it be a bug in our code, or a bug in the macOS implementation of `Mutex`? What should we do to avoid this problem in the future?

### Reproduction Steps

I do not have a reproduction. The relevant code on our side is [here](https://github.com/postsharp/Metalama.Backstage/blob/5743a3f/Metalama.Backstage/Utilities/MutexHelper.cs#L83), but it boils down to:

```c#
internal static Mutex OpenOrCreateMutex( string mutexName )
{
    // The number of iterations is intentionally very low.
    // We will restart if the following occurs:
    //   1) TryOpenExisting fails, i.e. there is no existing mutex.
    //   2) Creating a new mutex fails, i.e. the mutex was created in the meantime by a process with higher set of rights.
    // The probability of mutex being destroyed when we call TryOpenExisting again is fairly low.

    for ( var i = 0; ; i++ )
    {
        // First try opening the mutex.
        if ( Mutex.TryOpenExisting( mutexName, out var existingMutex ) )
        {
            return existingMutex;
        }
        else
        {
            // Otherwise we will try to create the mutex.
            try
            {
                return new Mutex( false, mutexName );
            }
            catch ( UnauthorizedAccessException )
            {
                if ( i < 3 )
                {
                    // Mutex was probably created in the meantime and is not accessible - we will restart.
                    continue;
                }
                else
                {
                    // There were too many restarts - just rethrow.
                    throw;
                }
            }
        }
    }
}
```

### Expected behavior

Either the exception is not thrown at all, or there is more information on the actual cause of the exception.

### Actual behavior

The exception described above is thrown.

**Comment by filipnavara** [comment]
I'm not sure whether this is actionable without more information. What version of framework was used to run the app? I went all the way back to .NET 6 and the `CreateMutexCore` would not throw `IOException` there AFAICT.

**Comment by svick** [comment]
@filipnavara Unfortunately, I don't have more information, apart from it being .Net 6+.

Though [that exception message is associated with `ERROR_OPEN_FAILED` in the PAL](https://github.com/dotnet/runtime/blob/a2ce8db/src/coreclr/pal/src/misc/errorstrings.cpp#L71), so I'm assuming that the exception is coming from native code.

**Comment by craigbehnke** [comment]
Hi @filipnavara, I'm the guy who opened the original issue. My app's target framework is net7.0 (installed SDKs are 7.0.311 and 7.0.313).

Please let me know what other info you would like.

**Comment by albahari** [comment]
I have experience this, too, on .NET 8.0.6 on macOS. Same stack trace.

**Comment by filipnavara** [comment]
> The exception shows the file 'Global\Metalama.Configuration'. Shouldn't that be Global/Metalama.Configuration on macOS?

No. The `Global\` prefix is a mutex thing, not a file-system thing.
