### ISSUE TITLE
[NAOT][Apple] NativeAOT TrimmingBehaviors smoke tests failing on apple mobile

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#100226]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=615665&view=logs&j=c275b23a-f0ee-5afa-80c6-bf568d89cc8e&t=4f4af029-f205-5b24-50af-8f7c525c1304
Build error leg or test failing: nativeaot.SmokeTests.TrimmingBehaviors

Failing on Mono Apple Mobile:
- ios-arm64
- iossimulator-x64
- tvos-arm64
- tvossimulator-x64

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "nativeaot/SmokeTests/TrimmingBehaviors/TrimmingBehaviors/TrimmingBehaviors.sh [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Stack trace:
```
           at nativeaot_SmokeTests_TrimmingBehaviors._TrimmingBehaviors_TrimmingBehaviors_._TrimmingBehaviors_TrimmingBehaviors_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by matouskozak** [comment]
Test is disabled, removing blocking-ci tag.

**Comment by kotlarmilos** [comment]
Failures are in servicing branches, closing this issue
