### ISSUE TITLE
Test failure: baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100217]
**Failed in:** [runtime-coreclr gcstress-extra 20240323.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615668&view=ms.vss-test-web.build-test-results-tab&runId=15042196&resultId=110778&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```

**Error message:**
```
 Failed: Verify_ServerGC_Env_Enable: exit code = -1073740286
```

**Stack trace:**
```
   at TestConfigTester.RunTests()
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**More failures:**
[runtime-coreclr r2r-extra 20240323.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=615768&view=ms.vss-test-web.build-test-results-tab&runId=15046154&resultId=130126&paneView=debug)
```
R2R-CG2 windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```
[runtime-coreclr gcstress0x3-gcstress0xc 20240324.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616030&view=ms.vss-test-web.build-test-results-tab&runId=15055512&resultId=101423&paneView=debug)

```
coreclr windows x64 Checked gcstress0x3 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```

**Comment by AndyAyersMS** [comment]
This looks like duplicate or consequence of https://github.com/dotnet/runtime/issues/100035

```
Running: "C:\h\w\A699090B\w\A47B0947\e\baseservices\baseservices\TestConfig.dll" Verify_ServerGC_Env_Enable
    set DOTNET_gcServer=1

Assert failure(PID 2860 [0x00000b2c], Thread: 10180 [0x27c4]): promoted_bytes (heap_number) == promoted

CORECLR! SVR::gc_heap::mark_phase + 0x167C (0x00007ffb`ac5f4a0c)
CORECLR! SVR::gc_heap::gc1 + 0x240 (0x00007ffb`ac5e6790)
CORECLR! SVR::gc_heap::garbage_collect + 0x99B (0x00007ffb`ac5e64fb)
CORECLR! SVR::gc_heap::gc_thread_function + 0x504 (0x00007ffb`ac5e7ea4)
CORECLR! SVR::gc_heap::gc_thread_stub + 0x7E (0x00007ffb`ac5e834e)
CORECLR! <lambda_99b27fb778a8c8677119b7591398adfb>::<lambda_invoker_cdecl> + 0x74 (0x00007ffb`ac2af964)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ffb`daa484d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ffb`dd4d1791)
    File: D:\a\_work\1\s\src\coreclr\gc\gc.cpp:24234
    Image: C:\h\w\A699090B\p\corerun.exe

System.Exception: Failed: Verify_ServerGC_Env_Enable: exit code = -1073740286
   at TestConfigTester.RunTests()
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
22:47:35.650 Failed test: baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```

**Comment by AndyAyersMS** [comment]
Interestingly TestConfigTester.csproj has
```
    <!-- This test provides no interesting scenarios for GCStress -->
    <GCStressIncompatible>true</GCStressIncompatible>
```
so I am puzzled why we are running it under gc stress at all. That being said, it shouldn't fail.

**Comment by AndyAyersMS** [comment]
@markples no luck with a local repro yet (runtime built with 14.40.33617/19.40.33617.1). I am going to download the native assets from the CI build and see what compiler version they're actually using.

**Comment by AndyAyersMS** [comment]
Lab bits use a slightly earlier version:
```
Frontend Version: Major = 19, Minor = 40, Build = 33521, QFE = 0
```
so issue may well be fixed in the one I'm using locally.

**Comment by mangod9** [comment]
Closing since we have picked up a new compiler version with a fix.
