### ISSUE TITLE
Synchronous call inside XDocument.LoadAsync

### ISSUE THREAD

**Issue by Yozer** [dotnet/runtime#100239]
### Description

Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.

```
at MyMiddleware.InvokeAsync(HttpContext context) 
at System.Xml.Linq.XDocument.LoadAsync(TextReader textReader, LoadOptions options, CancellationToken cancellationToken)
at System.Xml.Linq.XDocument.LoadAsyncInternal(XmlReader reader, LoadOptions options, CancellationToken cancellationToken)
at System.Xml.Linq.XDeclaration..ctor(XmlReader r)
at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
at System.Xml.XmlTextReaderImpl.ParseElement()
at System.Xml.XmlTextReaderImpl.ParseAttributes()
at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
at System.Xml.XmlTextReaderImpl.ReadData()
at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
at System.IO.StreamReader.ReadSpan(Span`1 buffer)
at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.Read(Span`1 buffer)
at System.IO.Stream.Read(Span`1 buffer)
at System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
```

### Reproduction Steps

I don't have the actual XML request that caused it but I think it's pretty clear for call stack that LoadAsyncInternal creates XDeclaration and the ctor there reads attributes and does it in a non-async way.

### Expected behavior

XDocument.LoadAsync should be fully async

### Actual behavior

Throws Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.

### Regression?

No

### Known Workarounds

Allow syncIO
```
builder.WebHost.ConfigureKestrel((_, options) =>
{
    options.AllowSynchronousIO = true;
});
```

### Configuration

latest aspnet core docker image: 8.0.3-bookworm-slim-amd64
https://github.com/dotnet/dotnet-docker/blob/9ffd75ed9a9a8790e7c7af5c925eefe7e4015bc1/src/aspnet/8.0/bookworm-slim/amd64/Dockerfile

**Comment by Yozer** [comment]
Repro steps, invalid xml, easier to debug:

```csharp
var xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope'\r";

using var ms = new MemoryStream(Encoding.UTF8.GetBytes(xml));
var asyncInput = new CheckSyncAsyncStream(async: true, ms);
var xdoc = await XDocument.LoadAsync(asyncInput, LoadOptions.None, CancellationToken.None);
Console.WriteLine(xdoc.DescendantNodes().Count());
```

Or with valid xml. When reading attribute we exceeded the buffer the read happens in a sync way.
```xml
var xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope";
xml += string.Join("", Enumerable.Repeat("a", 50_000));
xml += "\"></soap:Envelope>";
```
