### ISSUE TITLE
Test failure System.Net.Quic.QuicException : The connection timed out from inactivity.

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100219]
**Failed in:** [runtime-coreclr libraries-pgo 20240324.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=616074&view=ms.vss-test-web.build-test-results-tab&runId=15056638&resultId=152051&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-fullpgo_random_gdv-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.MsQuicTests.CallDifferentWriteMethodsWorks
    - System.Net.Quic.Tests.MsQuicTests.ConnectWithServerCertificateCallback
    - System.Net.Quic.Tests.MsQuicTests.ManagedAVE_MinimalFailingTest
    - System.Net.Quic.Tests.MsQuicTests.OpenStreamAsync_BlocksUntilAvailable_PeerClosesWritingUnidirectional
    - System.Net.Quic.Tests.MsQuicTests.QuicRootedObjectGetReleased
    - System.Net.Quic.Tests.MsQuicTests.Read_ConnectionAbortedByPeer_Throws
    - System.Net.Quic.Tests.QuicConnectionTests.AcceptAsync_NoCapacity_Throws
    - System.Net.Quic.Tests.QuicConnectionTests.AcceptStreamAsync_ConnectionDisposed_Throws
    - System.Net.Quic.Tests.QuicConnectionTests.CloseAsync_WithPendingAcceptAndConnect_PendingAndSubsequentThrowOperationAbortedException
    - System.Net.Quic.Tests.QuicConnectionTests.Connection_AwaitsStream_ConnectionSurvivesGC
    - System.Net.Quic.Tests.QuicConnectionTests.ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException
    - System.Net.Quic.Tests.QuicConnectionTests.Dispose_WithPendingAcceptAndConnect_PendingAndSubsequentThrowOperationAbortedException
    - System.Net.Quic.Tests.QuicConnectionTests.DisposeAfterCloseCanceled
    - System.Net.Quic.Tests.QuicConnectionTests.DisposeAfterCloseTaskStored
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ClientConnects_CancelIgnored
    - System.Net.Quic.Tests.QuicListenerTests.Listener_AlpnNarrowingDown_Success
    - System.Net.Quic.Tests.QuicListenerTests.Listener_AwaitsConnection_ListenerSurvivesGC
    - System.Net.Quic.Tests.QuicListenerTests.Listener_Backlog_Success
    - System.Net.Quic.Tests.QuicListenerTests.Listener_Backlog_Success_IPv6
    - System.Net.Quic.Tests.QuicListenerTests.Listener_BacklogLimitRefusesConnection_ClientThrows
    - System.Net.Quic.Tests.QuicListenerTests.Listener_IPv6Any_Accepts_IPv4
    - System.Net.Quic.Tests.QuicListenerTests.TwoListenersOnSamePort_DisjointAlpn_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Disposed_ThrowsObjectDisposedException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnReadableStream_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnWriteableStreamWithNoData_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_DuringReadAsync_ThrowsIfUnsupported
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadTimeout_Expires_Throws
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteByte_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Timeout_Roundtrips
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_ProperlyOpenedStream_Success
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.Read_WriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
net9.0-linux-Release-arm-fullpgo_random_gdv-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ThrowingCallbackOde_KeepRunning
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ListenerDisposed_Throws
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 526
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 594
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 628
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 434
   at System.Net.Quic.Tests.MsQuicTests.<ManagedAVE_MinimalFailingTest>g__GetStreamIdWithoutStartWorks|34_0() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 1269
   at System.Net.Quic.Tests.MsQuicTests.ManagedAVE_MinimalFailingTest() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 1277
--- End of stack trace from previous location ---
```

**Comment by BruceForstall** [comment]
@ManickaP @liveans Is this related to the other System.Net.Quic test failures we've seen recently?

**Comment by liveans** [comment]
> @ManickaP @liveans Is this related to the other System.Net.Quic test failures we've seen recently?

I don't think so, because almost the whole test suite failed this time, there might be something environmental.

**Comment by ManickaP** [comment]
Disabled in #100514 and covered by #91757, closing.
