### ISSUE TITLE
[mono][interpreter] Occasional failures of GC/Regressions/v2.0-beta2/452950 on OSX arm64 Mono interpreter

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#100398]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=610598
Build error leg or test failing: PayloadGroup0

- occasionally failing (5 times in the last 30 days) on osx-arm64 mono interpreter job on `runtime-extra-platforms`

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "GC/Regressions/v2.0-beta2/452950/452950/452950.sh [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Error log:
```
Starting:    GC.Regressions.XUnitWrapper (parallel test collections = on [8 threads], stop on fail = off)
    GC/Regressions/v2.0-beta2/452950/452950/452950.sh [FAIL]
      
      Return code:      1
      Raw output file:      /tmp/helix/working/A5FD08F0/w/B9860A02/uploads/Reports/GC.Regressions/v2.0-beta2/452950/452950/452950.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/A5FD08F0/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true 452950.dll ''
      112
      Failed
      Expected: 100
      Actual: 1
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /cores since 3/20/2024 3:44:03 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/tmp/helix/working/A5FD08F0/p
      > /private/tmp/helix/working/A5FD08F0/w/B9860A02/e/GC/Regressions/v2.0-beta2/452950/452950/452950.sh
      Stack Trace:
           at GC_Regressions._v2_0_beta2_452950_452950_452950_._v2_0_beta2_452950_452950_452950_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /tmp/helix/working/A5FD08F0/w/B9860A02/uploads/Reports/GC.Regressions/v2.0-beta2/452950/452950/452950.output.txt
        Raw output:
        BEGIN EXECUTION
        /tmp/helix/working/A5FD08F0/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true 452950.dll ''
        112
        Failed
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /cores since 3/20/2024 3:44:03 PM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/tmp/helix/working/A5FD08F0/p
        > /private/tmp/helix/working/A5FD08F0/w/B9860A02/e/GC/Regressions/v2.0-beta2/452950/452950/452950.sh
  Finished:    GC.Regressions.XUnitWrapper
```

cc: @BrzVlad 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=610598
**Error message validated:** `[GC/Regressions/v2.0-beta2/452950/452950/452950.sh [FAIL]`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 3/28/2024 10:12:15 AM UTC

**Comment by BrzVlad** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/99729 that @cshung was taking a look at.

**Comment by matouskozak** [comment]
> This is a duplicate of #99729 that @cshung was taking a look at.

Thank you, wasn't aware of this one. I will close this as a duplicate.
