### ISSUE TITLE
Test failure: JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#100366]
When I run tests locally on win-x64 using `src\tests\run.cmd x64 checked` on a build with the Pri-1 tests I get:

```
      JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro.cmd [FAIL]

        Return code:      1
        Raw output file:      C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Reports\JIT.HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro.output.txt
        Raw output:
        BEGIN EXECUTION

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set DOTNETCLI=C:\gh\runtime\dotnet.cmd

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set SUPERPMI_CACHE_DIRECTORY=c:\spmi

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set __DOTNET_ADD_32BIT=1

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set __DOTNET_PREFERRED_BITNESS=32
         "C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerial
  ization=true"  Sve_ro.dll
        Supported ISAs:
          AdvSimd:   False
          Aes:       False
          ArmBase:   False
          Crc32:     False
          Dp:        False
          Rdm:       False
          Sha1:      False
          Sha256:    False
          Sve:       False

        System.ArgumentException: Invalid value of alignment
           at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float.DataTable..ctor(Single[] inArray1, Single[] outArray, Int32 alignment) in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JI
  T\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\SveLoadVector.float.cs:line 69
           at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float..ctor() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\SveLoadVector.fl
  oat.cs:line 113
           at JIT.HardwareIntrinsics.Arm._Sve.Program.SveLoadVector_float() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\SveLoadVector.float.cs:line 27
           at __GeneratedMainWrapper.Main() in c:\gh\runtime\src\tests\JIT\HardwareIntrinsics\Arm\Sve\XUnitWrapperGenerator\XUnitWrapperGenerator.XUnitWrapperGenerator\SimpleRunner.g.cs:line 7
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
        > C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro.cmd
        Stack Trace:
          c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(2723,0): at JIT_HardwareIntrinsics._Arm_Sve_Sve_ro_Sve_ro_._Arm_Sve_Sve_ro_Sve_ro_cmd(
  )
             at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
             at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        Output:

          Return code:      1
          Raw output file:      C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Reports\JIT.HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro.output.txt
          Raw output:
          BEGIN EXECUTION

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set DOTNETCLI=C:\gh\runtime\dotnet.cmd

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set SUPERPMI_CACHE_DIRECTORY=c:\spmi

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set __DOTNET_ADD_32BIT=1

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro>set __DOTNET_PREFERRED_BITNESS=32
           "C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSeri
  alization=true"  Sve_ro.dll
          Supported ISAs:
            AdvSimd:   False
            Aes:       False
            ArmBase:   False
            Crc32:     False
            Dp:        False
            Rdm:       False
            Sha1:      False
            Sha256:    False
            Sve:       False

          System.ArgumentException: Invalid value of alignment
             at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float.DataTable..ctor(Single[] inArray1, Single[] outArray, Int32 alignment) in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\
  JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\SveLoadVector.float.cs:line 69
             at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float..ctor() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\SveLoadVector.
  float.cs:line 113
             at JIT.HardwareIntrinsics.Arm._Sve.Program.SveLoadVector_float() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\SveLoadVector.float.cs:line 2
  7
             at __GeneratedMainWrapper.Main() in c:\gh\runtime\src\tests\JIT\HardwareIntrinsics\Arm\Sve\XUnitWrapperGenerator\XUnitWrapperGenerator.XUnitWrapperGenerator\SimpleRunner.g.cs:line 7
          Expected: 100
          Actual: 101
          END EXECUTION - FAILED
          FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
          > C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro.cmd
      JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r.cmd [FAIL]

        Return code:      1
        Raw output file:      C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Reports\JIT.HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r.output.txt
        Raw output:
        BEGIN EXECUTION

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set DOTNETCLI=C:\gh\runtime\dotnet.cmd

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set SUPERPMI_CACHE_DIRECTORY=c:\spmi

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set __DOTNET_ADD_32BIT=1

        C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set __DOTNET_PREFERRED_BITNESS=32
         "C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerial
  ization=true"  Sve_r.dll
        Supported ISAs:
          AdvSimd:   False
          Aes:       False
          ArmBase:   False
          Crc32:     False
          Dp:        False
          Rdm:       False
          Sha1:      False
          Sha256:    False
          Sve:       False

        System.ArgumentException: Invalid value of alignment
           at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float.DataTable..ctor(Single[] inArray1, Single[] outArray, Int32 alignment) in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JI
  T\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r\gen\SveLoadVector.float.cs:line 69
           at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float..ctor() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r\gen\SveLoadVector.floa
  t.cs:line 113
           at JIT.HardwareIntrinsics.Arm._Sve.Program.SveLoadVector_float() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r\gen\SveLoadVector.float.cs:line 27
           at __GeneratedMainWrapper.Main() in c:\gh\runtime\src\tests\JIT\HardwareIntrinsics\Arm\Sve\XUnitWrapperGenerator\XUnitWrapperGenerator.XUnitWrapperGenerator\SimpleRunner.g.cs:line 7
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
        > C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r.cmd
        Stack Trace:
          c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(2822,0): at JIT_HardwareIntrinsics._Arm_Sve_Sve_r_Sve_r_._Arm_Sve_Sve_r_Sve_r_cmd()
             at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
             at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        Output:

          Return code:      1
          Raw output file:      C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Reports\JIT.HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r.output.txt
          Raw output:
          BEGIN EXECUTION

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set DOTNETCLI=C:\gh\runtime\dotnet.cmd

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set SUPERPMI_CACHE_DIRECTORY=c:\spmi

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set __DOTNET_ADD_32BIT=1

          C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r>set __DOTNET_PREFERRED_BITNESS=32
           "C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSeri
  alization=true"  Sve_r.dll
          Supported ISAs:
            AdvSimd:   False
            Aes:       False
            ArmBase:   False
            Crc32:     False
            Dp:        False
            Rdm:       False
            Sha1:      False
            Sha256:    False
            Sve:       False

          System.ArgumentException: Invalid value of alignment
             at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float.DataTable..ctor(Single[] inArray1, Single[] outArray, Int32 alignment) in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\
  JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r\gen\SveLoadVector.float.cs:line 69
             at JIT.HardwareIntrinsics.Arm._Sve.LoadUnaryOpTest__SveLoadVector_float..ctor() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r\gen\SveLoadVector.fl
  oat.cs:line 113
             at JIT.HardwareIntrinsics.Arm._Sve.Program.SveLoadVector_float() in c:\gh\runtime\artifacts\tests\coreclr\obj\windows.x64.Checked\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r\gen\SveLoadVector.float.cs:line 27
             at __GeneratedMainWrapper.Main() in c:\gh\runtime\src\tests\JIT\HardwareIntrinsics\Arm\Sve\XUnitWrapperGenerator\XUnitWrapperGenerator.XUnitWrapperGenerator\SimpleRunner.g.cs:line 7
          Expected: 100
          Actual: 101
          END EXECUTION - FAILED
          FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
          > C:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\HardwareIntrinsics\Arm\Sve\Sve_r\Sve_r.cmd
```

@a74nh @dotnet/arm64-contrib

**Comment by kunalspathak** [comment]
I see the problem and that's because the `["LargestVectorSize"] = "8"` instead of "16" [when we added this case](https://github.com/dotnet/runtime/pull/98218/files#diff-3ba328ecb68a67ab7f832fbae8b4d0490ef6230e5888e2b35d18d4163f2d15e2R2890), because `Vector` is mapped to `Vector128` if IIRC. 

I am not even sure why this test is running on x64 though locally. It doesn't run in CI so is there a reason why it is run locally? did we forget to turn off some knobs?
