### ISSUE TITLE
MethodInfo Invoke with [Optional] argument as Type.Missing fails

### ISSUE THREAD

**Issue by jborean93** [dotnet/runtime#100322]
### Description

I'm trying to invoke a method that contains an [OptionalAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.optionalattribute?view=net-8.0) without a default value set using reflection but it fails when using `Type.Missing` with

>  System.ArgumentException: Object of type 'System.Reflection.Missing' cannot be converted to type 'System.Int32'.

### Reproduction Steps

```csharp
using System;
using System.Runtime.InteropServices;

public class Program
{
    public static void Main()
    {
        int value1 = (int)typeof(Program).GetMethod(nameof(TestMethod1))
            .Invoke(null, new[] { Type.Missing });
        Console.WriteLine($"TestMethod1() => {value1}");

        int value2 = (int)typeof(Program).GetMethod(nameof(TestMethod2))
            .Invoke(null, new[] { Type.Missing });
        Console.WriteLine($"TestMethod2() => {value2}");

        int value3 = (int)typeof(Program).GetMethod(nameof(TestMethod3))
            .Invoke(null, new[] { Type.Missing });
        Console.WriteLine($"TestMethod3() => {value3}");
    }

    public static int TestMethod1(int value = 1) => value;
    public static int TestMethod2([Optional, DefaultParameterValue(1)] int value) => value;
    public static int TestMethod3([Optional] int value) => value;
}
```

### Expected behavior

```
TestMethod1() => 1
TestMethod2() => 1
TestMethod3() => 0
```

### Actual behavior

```
TestMethod1() => 1
TestMethod2() => 1
Unhandled exception. System.ArgumentException: Object of type 'System.Reflection.Missing' cannot be converted to type 'System.Int32'.
   at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Program.Main() in /home/user/dev/Example/Program.cs:line 16
```

### Regression?

It does not look like it, the same example fails on .NET Framework 4.8.

### Known Workarounds

The workaround is to pass in `null` (I'm not sure if that works in all scenarios or not).

```csharp
int value3 = (int)typeof(Program).GetMethod(nameof(TestMethod3))
            .Invoke(null, new object[] { null });
```

### Configuration

net8.0
All OS
Tested on x64
I don't believe this is specific to this configuration.

### Other information

This is opened in response to https://github.com/PowerShell/PowerShell/issues/21372. PowerShell is using an ExpressionTree to invoke the method. It uses the [ParameterInfo.DefaultValue](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.defaultvalue?view=net-8.0) for arguments not specified in PowerShell which for `TestMethod3()` is [Missing](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.missing?view=net-8.0).

```powershell
Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

public class MyClass
{
    public static int TestMethod1(int value = 1) => value;
    public static int TestMethod2([Optional, DefaultParameterValue(1)] int value) => value;
    public static int TestMethod3([Optional] int value) => value;
}
'@

[MyClass].GetMethod('TestMethod1').GetParameters() | Select-Object Attributes, DefaultValue

          Attributes DefaultValue
          ---------- ------------
Optional, HasDefault            1

[MyClass].GetMethod('TestMethod2').GetParameters() | Select-Object Attributes, DefaultValue

          Attributes DefaultValue
          ---------- ------------
Optional, HasDefault            1

[MyClass].GetMethod('TestMethod3').GetParameters() | Select-Object Attributes, DefaultValue

Attributes DefaultValue
---------- ------------
  Optional System.Reflection.Missing
```

I've got a patch for PowerShell that uses `Expression.Default(parameters[0].ParameterType);` which solves this issue but it seems like this might be a bug in .NET that should be fixed here. If not it would be great to understand more about why the current behaviour fails and if there are other cases were `ParameterInfo.DefaultType` might also be `System.Reflection.Missing`.

**Comment by steveharter** [comment]
This is by design; see the test [Invoke_OptionalParameterUnassingableFromMissing_WithMissingValue_ThrowsArgumentException.](https://github.com/dotnet/runtime/blob/788f5726850d5bd85141f821f5329cb6e5a80a18/src/libraries/System.Runtime/tests/System.Reflection.Tests/MethodInfoTests.cs#L394-L397) where the parameter type is `string`. The similar test before that has an `object` parameter type and doesn't throw but the incoming value is `Type.Missing` which can be passed as `object`.

Also verified previous versions (v7, v8) are consistent.

**Comment by jborean93** [comment]
Thanks @steveharter for replying, so is the solution here to just provide `null` for these values explicitly? Are you aware of any other scenario where `ParameterInfo.DefaultValue` might also by `System.Reflection.Missing` that could potential cause problems if I change the PowerShell code to provide the default value/null for this argument when calling it?

**Comment by jborean93** [comment]
Oh and the linked issue to that test seems to be unrelated https://github.com/mono/mono/issues/15025 so not sure what the reason behind this behaviour is.
