### ISSUE TITLE
Test failure: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100475]
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20240331.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625354&view=ms.vss-test-web.build-test-results-tab&runId=15328934&resultId=109148&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.ARM64.Open
    - JIT/Methodical/eh/basics/throwinclassconstructor_do/throwinclassconstructor_do.dll
    - JIT/Methodical/eh/basics/throwinclassconstructor_ro/throwinclassconstructor_ro.dll
```

**Error message:**
```
 Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Stack trace:**
```
   at Program.<<Main>$>g__TestExecutor200|0_201(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by kunalspathak** [comment]
I don't see this test failing lately in https://dev.azure.com/dnceng-public/public/_build/results?buildId=633990&view=results, but on the build where it failed, it passed with `DOTNET_LegacyExceptionHandling =1`. @janvorli

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240512.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=672815&view=ms.vss-test-web.build-test-results-tab&runId=16679862&resultId=197247&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2-Windows.10.Amd64.Open
    - System.Text.RegularExpressions.Tests.RegexGroupTests.Groups
```

**Error message:**
```
 System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Stack trace:**
```
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.<VisitArguments>g__visitArguments|234_0(BoundNode node, ImmutableArray`1 arguments, ImmutableArray`1 argumentsNoConversions, ImmutableArray`1 conversions, ImmutableArray`1 results, ImmutableArray`1 refKindsOpt, ImmutableArray`1 parametersOpt, ImmutableArray`1 argsToParamsOpt, BitVector defaultArguments, Boolean expanded, Boolean invokedAsExtensionMethod, MethodSymbol method, Boolean delayCompletionForTargetMember)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitArguments(BoundNode node, ImmutableArray`1 arguments, ImmutableArray`1 refKindsOpt, ImmutableArray`1 parametersOpt, ImmutableArray`1 argsToParamsOpt, BitVector defaultArguments, Boolean expanded, Boolean invokedAsExtensionMethod, MethodSymbol method, Nullable`1 firstArgumentResult)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.<VisitCall>g__reinferMethodAndVisitArguments|215_2(BoundCall node, TypeWithState receiverType, Nullable`1 firstArgumentResult)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node, Boolean expressionIsRead)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitRvalue(BoundExpression node, Boolean isKnownToBeAnLvalue)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitOptionalImplicitConversion(BoundExpression expr, TypeWithAnnotations targetTypeOpt, Boolean useLegacyWarnings, Boolean trackMembers, AssignmentKind assignmentKind)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitLocalDeclaration(BoundLocalDeclaration node)
   at Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatement(BoundStatement statement)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatementsWithLocalFunctions(BoundBlock block)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatement(BoundStatement statement)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitStatementsWithLocalFunctions(BoundBlock block)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node, Boolean expressionIsRead)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2.Analyze(Boolean& badRegion, Optional`1 initialState)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(NullableWalker walker, Symbol symbol, DiagnosticBag diagnostics, Optional`1 initialState, Builder snapshotBuilderOpt, Boolean requiresAnalysis)
   at Microsoft.CodeAnalysis.CSharp.NullableWalker.Analyze(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, Conversions conversions, DiagnosticBag diagnostics, Boolean useConstructorExitWarnings, Boolean useDelegateInvokeParameterTypes, Boolean useDelegateInvokeReturnType, MethodSymbol delegateInvokeMethodOpt, VariableState initialState, MethodSymbol baseOrThisInitializer, Builder analyzedNullabilityMapOpt, Builder snapshotBuilderOpt, ArrayBuilder`1 returnTypesOpt, Boolean getFinalNullableState, VariableState& finalNullableState, Boolean requiresAnalysis)
   at Microsoft.CodeA
```

**Comment by JulieLeeMSFT** [comment]
Pinging again if you had a chance to look into it, @janvorli.

**Comment by janvorli** [comment]
The failure seems to be gone, closing the issue for now.
