### ISSUE TITLE
Test failure: readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100477]
**Failed in:** [runtime-coreclr pgostress 20240329.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624712&view=ms.vss-test-web.build-test-results-tab&runId=15304342&resultId=115357&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked syntheticpgo_blend @ Windows.10.Amd64.Open
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 63594 msecs, exit code -1073740286 = 0xC0000602, expected 0: corerun.exe C:hw91E5082Fpcrossgen2crossgen2.dll @C:hw91E5082FwA57B097Ce
eadytoruncoreroot_determinismcoreroot_determinismseed1CPAOT-ret.outSystem.Private.CoreLib.dll.rsp
!! Assert failure(PID 5628 [0x000015fc], Thread: 1452 [0x05ac]): Assertion failed 'fgPgoConsistentCheck' in 'ILCompiler.LazyGenericsSupport+GraphBuilder+<<-ctor>g__GetGenericParameters|0_3>d:MoveNext():ubyte:this' during 'Importation' (IL size 719; hash 0xa668b1ae; Tier1)
!!     File: D:_work1ssrccoreclrjitlowgraph.cpp:591
!!     Image: C:hw91E5082Fpcorerun.exe

Return code:      1
Raw output file:      C:hw91E5082FwA57B097Cuploadscoreroot_determinismoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hw91E5082Fpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  coreroot_determinism.dll 
================================== Compiling with seed 1 ==================================
Locating output folder C:hw91E5082FwA57B097Ce
eadytoruncoreroot_determinismcoreroot_determinismseed1
Deleting 0 output folders
Successfully deleted 0 output folders in 435 msecs
Using dotnet: C:hw91E5082Fpcorerun.exe
1 / 1 (0%, 0 failed): launching: C:hw91E5082Fpcorerun.exe C:hw91E5082Fpcrossgen2crossgen2.dll @C:hw91E5082FwA57B097Ce
eadytoruncoreroot_determinismcoreroot_determinismseed1CPAOT-ret.outSystem.Private.CoreLib.dll.rsp
Compilation failed. C:hw91E5082Fpcorerun.exe C:hw91E5082FpR2RTestR2RTest.dll compile-directory -cr C:hw91E5082Fp -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -out seed1 failed with exit code 1
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 3/30/2024 7:48:45 AM
Processing C:corescorerun.exe.5628.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hw91E5082F		mpy5tmge.tmp" -z "C:corescorerun.exe.5628.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.5628.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hw91E5082FpPDB
Symbol search path is: C:hw91E5082FpPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Mar 30 07:50:02.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:58:00.346
Process Uptime: 0 days 0:01:02.000
...........................................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(15fc.5ac): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=090ca8f8 ebx=00000000 ecx=00000
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-02-03T07:31:43.508Z | runtime-coreclr pgostress | Checked-syntheticpgo_blend | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"230","AzurePipelinesTestRunId":"13131124","Project":"public","architecture":"arm64","System.StageName":"Build","System.JobName":"__default","BuildId":"552059","System.JobAttempt":"1","Reason":"Schedule","configuration":"Checked-syntheticpgo_blend","System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20240202.1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr pgostress","System.PhaseAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e"} | Schedule
2024-02-03T07:21:19.509Z | runtime-coreclr pgostress | Checked-syntheticpgo_blend | ubuntu.2004.armarch.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"architecture":"arm64","System.JobAttempt":"1","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","System.JobName":"__default","configuration":"Checked-syntheticpgo_blend","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","Project":"public","System.PhaseName":"run_test_p1__linux_arm64_checked","AzurePipelinesTestRunId":"13130950","DefinitionName":"runtime-coreclr pgostress","BuildId":"552059","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","System.StageAttempt":"1","DefinitionId":"230","BuildNumber":"20240202.1","Reason":"Schedule"} | Schedule
2024-02-03T07:20:50.47Z | runtime-coreclr pgostress | Checked-syntheticpgo_blend | ubuntu.2204.amd64.open.rt | x64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"BuildNumber":"20240202.1","configuration":"Checked-syntheticpgo_blend","System.JobName":"__default","DefinitionName":"runtime-coreclr pgostress","System.JobAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","BuildId":"552059","architecture":"x64","DefinitionId":"230","operatingSystem":"Ubuntu.2204.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","System.PhaseAttempt":"1","Project":"public","System.PhaseName":"run_test_p1__linux_x64_checked","AzurePipelinesTestRunId":"13130938","Reason":"Schedule","System.StageAttempt":"1"} | Schedule
2024-01-14T18:40:11.7Z | runtime-coreclr jitstress2-jitstressregs | Checked-jitstress2_jitstressregs8 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr jitstress2-jitstressregs","System.StageName":"Build","System.PhaseName":"run_test_p1__osx_arm64_checked","configuration":"Checked-jitstress2_jitstressregs8","AzurePipelinesTestRunId":"12404836","System.PhaseAttempt":"1","architecture":"arm64","BuildNumber":"20240114.1","System.StageAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"526827","Reason":"Schedule","Project":"public","DefinitionId":"111","System.JobAttempt":"1","System.JobName":"__default"} | Schedule
2024-01-14T18:39:53.95Z | runtime-coreclr jitstress2-jitstressregs | Checked-jitstress2_jitstressregs1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"AzurePipelinesTestRunId":"12404820","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"111","DefinitionName":"runtime-coreclr jitstress2-jitstressregs","BuildNumber":"20240114.1","System.StageName":"Build","System.PhaseAttempt":"1","System.JobName":"__default","System.StageAttempt":"1","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64","BuildId":"526827","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.PhaseName":"run_test_p1__osx_arm64_checked","configuration":"Checked-jitstress2_jitstressregs1"} | Schedule
2024-01-13T18:33:09.036Z | runtime-coreclr jitstress2-jitstressregs | Checked-jitstress2_jitstressregs1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"System.StageName":"Build","System.JobName":"__default","DefinitionId":"111","operatingSystem":"OSX.1200.ARM64.Open","configuration":"Checked-jitstress2_jitstressregs1","System.StageAttempt":"1","BuildId":"526416","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","AzurePipelinesTestRunId":"12392342","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20240113.1","DefinitionName":"runtime-coreclr jitstress2-jitstressregs","Project":"public","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule
2024-01-13T18:33:08.02Z | runtime-coreclr jitstress2-jitstressregs | Checked-jitstress2_jitstressregs8 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","architecture":"arm64","System.PhaseAttempt":"1","Project":"public","DefinitionId":"111","System.JobAttempt":"1","DefinitionName":"runtime-coreclr jitstress2-jitstressregs","System.JobName":"__default","configuration":"Checked-jitstress2_jitstressregs8","BuildId":"526416","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"12392354","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","System.StageName":"Build","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildNumber":"20240113.1"} | Schedule

**Comment by AndyAyersMS** [comment]
I can repro. Digging in.
