### ISSUE TITLE
[browser][MT] Runtime Aborts after executing Main()

### ISSUE THREAD

**Issue by glutio** [dotnet/runtime#100597]
### Description

The multithreading browser runtime crashes in `await runMain()` after executing `Program::Main()`. 

### Reproduction Steps

.csproj
```
<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmEnableThreads>true</WasmEnableThreads>
  </PropertyGroup>
</Project>
```
.js
```
import { dotnet } from './_framework/dotnet.js'
const { runMain } = await dotnet.create();
await runMain();
```
.cs
```
using System;
Console.WriteLine("Hello, Browser!");
```

### Expected behavior

Prints message and does not crash

### Actual behavior

Prints message and crashes

```
worker.onerror		@	dotnet.native.9.0.0-…8.5.kpnkj0mqsi.js:8
error (async)		
(anonymous)		@	dotnet.native.9.0.0-…8.5.kpnkj0mqsi.js:8
loadWasmModuleToWorker	@	dotnet.native.9.0.0-…8.5.kpnkj0mqsi.js:8
e.loadWasmModuleToWorker@	ui-thread.ts:243
Bn			@	ui-thread.ts:359
(anonymous)		@	ui-thread.ts:169
(anonymous)		@	startup.ts:247
```
```
dotnet.native.wasm:1  Uncaught (in promise) RuntimeError: unreachable
    at __trap (dotnet.native.wasm)
    at ___trap (dotnet.native.9.0.0-preview.4.24202.8.804phjyibc.js:7325:45)
    at abort (dotnet.native.9.0.0-preview.4.24202.8.804phjyibc.js:727:3)
    at _abort (dotnet.native.9.0.0-preview.4.24202.8.804phjyibc.js:5423:2)
    at ves_icall_System_Environment_FailFast (dotnet.native.wasm)
    at ves_icall_System_Environment_FailFast_raw (dotnet.native.wasm)
    at do_icall (dotnet.native.wasm)
    at do_icall_wrapper (dotnet.native.wasm)
    at mono_interp_exec_method (dotnet.native.wasm)
    at interp_runtime_invoke (dotnet.native.wasm)
```

### Regression?

Works in .net8

### Configuration

version 9.0.x-preview.x

**Comment by maraf** [comment]
cc @pavelsavara

**Comment by pavelsavara** [comment]
The real error is `Marshalling null return Task to JS is not supported in MT` because the `void Main()` doesn't create any task.
