### ISSUE TITLE
[browser][mt] Running Buffers tests in parallel results in OOM

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#100628]
```
[FAIL][8] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingSpecificLengthsYieldsExpectedLengths(requestedMinimum: 2097152, expectedLength: 2097152)
info: System.OutOfMemoryException : Out of memory
info:    at System.Buffers.ConfigurableArrayPool`1[[System.String, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Rent(Int32 minimumLength)
info:    at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingSpecificLengthsYieldsExpectedLengths(Int32 requestedMinimum, Int32 expectedLength)
info:    at System.Object.InvokeStub_ArrayPoolUnitTests.RentingSpecificLengthsYieldsExpectedLengths(Object , Span`1 )
info:    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Running in parallel disabled. Discovered in https://github.com/dotnet/runtime/pull/98492

_It seems that GC is unable to keep up with the traffic.
I wonder if Mono on x64 has the same problem but survives this because of more available memory ?_

**Comment by pavelsavara** [comment]
I found it still OOM on MT [here](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-101056-merge-c58adb1a8881497398/WasmTestOnBrowser-System.Buffers.Tests/1/console.de698822.log?helixlogtype=result)

I updated the issue to "known build error "
