### ISSUE TITLE
Received an unexpected EOF or 0 bytes from the transport stream

### ISSUE THREAD

**Issue by pisethdanh** [dotnet/runtime#100773]
### Description

When using HttpClient to download the metadata file from graph.microsoft.com, we get intermittent failures with the following stacktrace.

Application is running in an AKS cluster using the sdk:8.0-alpine docker image.

I'm not able to reproduce this issue locally so I cannot get any packet captures.

```
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Semperis.Infrastructure.Services.GraphClient.GetMetadataAsync(CancellationToken cancellationToken) in /src/Semperis.Zebra/Infrastructure/Semperis.Infrastructure/Services/GraphClient.cs:line 41
   at Semperis.Zebra.Backup.BackupV2.RunAsync(CancellationToken cancellationToken) in /src/Semperis.Zebra/Services/Semperis.Zebra.Backup/BackupV2.cs:line 58
   at Semperis.Zebra.Backup.BackupWorker.StartAsync(CancellationToken cancellationToken) in /src/Semperis.Zebra/Services/Semperis.Zebra.Backup/BackupWorker.cs:line 52
```

### Reproduction Steps

use the following docker image:
`mcr.microsoft.com/dotnet/sdk:8.0-alpine`

standard HttpClient SendAsync code:
```csharp
// GraphClient.cs

public async Task<Stream> GetMetadataAsync(CancellationToken cancellationToken = default)
{
    using var request = new HttpRequestMessage(HttpMethod.Get, "$metadata");
    request.AddResilienceContext(nameof(GetMetadataAsync), cancellationToken);

    var response = await _httpClient.SendAsync(request, cancellationToken);
    response.EnsureSuccessStatusCode();

    return await response.Content.ReadAsStreamAsync(cancellationToken);
}
```

setup:
```csharp
services.AddHttpClient<IGraphClient, GraphClient>("graph-client", c =>
{
    c.BaseAddress = new Uri("https://graph.microsoft.com/beta/");
    // known bug; setting this to Infinite is a workaround
    // https://github.com/dotnet/extensions/issues/4770
    c.Timeout = Timeout.InfiniteTimeSpan;
})
.AddHttpMessageHandler<AuthorizationHeaderHandler>()
.AddStandardResilienceHandler();
```

Application is a console application running in an ASK cluster.

### Expected behavior

Downloading file should always succeed.

### Actual behavior

Intermittently fails with the following stacktrace:

```
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Semperis.Infrastructure.Services.GraphClient.GetMetadataAsync(CancellationToken cancellationToken) in /src/Semperis.Zebra/Infrastructure/Semperis.Infrastructure/Services/GraphClient.cs:line 41
   at Semperis.Zebra.Backup.BackupV2.RunAsync(CancellationToken cancellationToken) in /src/Semperis.Zebra/Services/Semperis.Zebra.Backup/BackupV2.cs:line 58
   at Semperis.Zebra.Backup.BackupWorker.StartAsync(CancellationToken cancellationToken) in /src/Semperis.Zebra/Services/Semperis.Zebra.Backup/BackupWorker.cs:line 52
```

### Known Workarounds

The following issues seem similar:

- https://github.com/dotnet/runtime/issues/83455
- https://github.com/dotnet/runtime/issues/98797
- https://github.com/dotnet/runtime/issues/55227

### Configuration

.NET version: .NET 8.0
docker image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
architecture: x64
application is running in AKS

**Comment by nmoATusercube** [comment]
We have a similar issue with a dotnet 6.0 client calling a .NET 8.0 App Service. It was working perfectly with the dotnet 6.0 version of the App Service. The root cause seems on the server side.

>  ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

**Comment by MihaZupan** [comment]
Errors like these indicate that the server (or infra between you and the server) decided to gracefully close the transport connection before sending all of the content. It isn't on its own an indication of anything wrong happening with HttpClient.

Does this happen only for a particular kind of request, or at a consistent time after starting the request (e.g. it always does this after N seconds)? Or is it always seemingly random?
Do retries mitigate the problem?

You could try collecting a packet capture to confirm what the server sent in such cases, but it's unlikely that there is an issue with how HttpClient is parsing such responses.
This sounds more like an intermittent connectivity/service issue.

**Comment by rzikm** [comment]
Alternatively, can you provide a minimal self-contained repro project which we can run locally? I am having hard time reproducing this.

**Comment by henkepa** [comment]
Guys, this really sucks badly. As you probably know enterprises move slowly - I expect many of them still working on the migration to .NET8 and they will hit this issue sooner than later. I can't understand why this is not anticipates as a must-have fix.

**Comment by rzikm** [comment]
In case of #98797 we received EOF while establishing the connection (due to configuration differences explained in the issue).

The callstack in this issue shows that the EOF occured while reading the response content, with a partially received TLS frame in the buffer. As opposed to server closing the connection during handshake, it is very hard to tell why would server intentionally close the connection here.

**Comment by henkepa** [comment]
@rzikm thanks for pointing out the difference -> I'll complain on #98797 then :-)
