### ISSUE TITLE
Test failure: Interop/COM/NativeClients/MiscTypes/MiscTypes.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100739]
**Failed in:** [runtime-coreclr gcstress0x3-gcstress0xc 20240406.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633038&view=ms.vss-test-web.build-test-results-tab&runId=15563988&resultId=120116&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked gcstress0x3 @ Windows.10.Amd64.Open
    - Interop/COM/NativeClients/MiscTypes/MiscTypes.cmd
```

**Error message:**
```
 
Assert failure(PID 15436 [0x00003c4c], Thread: 3932 [0x0f5c]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x11F (0x00007ffa`4e22574f)
CORECLR! Object::Validate + 0xA1 (0x00007ffa`4e2255f1)
CORECLR! WKS::GCHeap::Promote + 0xDA (0x00007ffa`4e71f48a)
CORECLR! GCFrame::GcScanRoots + 0x7F (0x00007ffa`4e136b2f)
CORECLR! ScanStackRoots + 0x2B0 (0x00007ffa`4e3c1820)
CORECLR! GCToEEInterface::GcScanRoots + 0x197 (0x00007ffa`4e3bf017)
CORECLR! WKS::gc_heap::mark_phase + 0x48E (0x00007ffa`4e7422fe)
CORECLR! WKS::gc_heap::gc1 + 0x224 (0x00007ffa`4e737894)
CORECLR! WKS::gc_heap::garbage_collect + 0x8A0 (0x00007ffa`4e737600)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x4E3 (0x00007ffa`4e71d723)
    File: D:_work1ssrccoreclrmobject.cpp:521
    Image: C:hwB05F094DwB35C0972eInteropCOMNativeClientsMiscTypesCOMClientMiscTypes.exe


Return code:      1
Raw output file:      C:hwB05F094DwB35C0972uploadsCOMNativeClientsMiscTypesoutput.txt
Raw output:
BEGIN EXECUTION
Copying 'C:hwB05F094DpCoreShim.dll'...
        1 file(s) copied.
 COMClientMiscTypes MiscTypes.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 4/6/2024 3:08:13 PM
Processing C:coresCOMClientMiscTypes.exe.15436.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwB05F094D		mpvsusbz.tmp" -z "C:coresCOMClientMiscTypes.exe.15436.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:coresCOMClientMiscTypes.exe.15436.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB05F094DpPDB
Symbol search path is: C:hwB05F094DpPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Apr  6 15:08:18.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:37:25.463
Process Uptime: 0 days 0:00:05.000
...................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(3c4c.f5c): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
KERNELBASE!RaiseFailFastException+0xae:
00007ffa`56e196ce 803d4d78120000  cmp     byte ptr [KERNELBASE!local_unwind+0x7fe2 (00007ffa`56f40f22)],0 ds:00007ffa`56f40f22=00
0:000> cdb: Reading initial command '$<C:hwB05F094D		mpvsusbz.tmp'
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: 3c4c.f5c Suspend: 0 Teb: 000000a7`b86b6000 Unfrozen
Child-SP          RetAddr           Call Site
000000a7`b897b320 00007ffa`4e7dd60c KERNELBASE!RaiseFailFastException+0xae
000000a7`b897b8f0 00007ffa`4e7dced5 coreclr!_DbgBreakCheck+0x2ec
000000a7`b897ca60 00007ffa`4e7dd0cf coreclr!_DbgBreakCheckNoThrow+0x55
000000a7`b897cb10 00007ffa`4e22574f coreclr!DbgAssertDialog+0x19f
000000a7`b897cc20 00007ffa`4e2255f1 coreclr!Object::ValidateInner+0x11f
000000a7`b897cd20 00007ffa`4e71f48a coreclr!Object::Validate+0xa1
000000a7`b897cd60 00007ffa`4e136b2f coreclr!WKS::GCHeap::Promote+0xda
000000a7`b897cdb0 00007ffa`4e3c1820 coreclr!GCFrame::GcScanRoots+0x7f
000000a7`b897ce10 00007ffa`4e3bf017 coreclr!ScanStackRoots+0x2b0
0000
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor214|25_215(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by AaronRobinsonMSFT** [comment]
This is very interesting that this is failing. The test was recently added in https://github.com/dotnet/runtime/pull/100377. It is mostly exercising a set of scenarios that we've lacked testing for. I will take a first pass look.

/cc @dotnet/jit-contrib

**Comment by AaronRobinsonMSFT** [comment]
This is a bug in the legacy marshalling code. It was introduced in https://github.com/dotnet/coreclr/pull/26340.
