### ISSUE TITLE
The process cannot access the file 'xxxxx.zip' because it is being used by another process

### ISSUE THREAD

**Issue by gzj132** [dotnet/runtime#100756]
### Description

The process cannot access the file 'xxx.zip' because it is being used by another process. ?System.IO.IOException: The process cannot access the file 'xxx.zip' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)

### Reproduction Steps

using var fileStream = new FileStream(zipFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);

### Expected behavior

My work scenario looks like this:
1. A timed asynchronous service accesses my current service to create an xxx.zip
2. I will tell him that xxx.zip is created and give him the full name of zip
3. The timer asynchronous service fragments the zip with all its names to obtain bytes of the zip
I have errors in steps 1 and 3 respectively
Since the first step is too modified, it is impossible to remove repeated requests, and there are fewer errors, after all, the zip can be created within a fixed time, so I just want to solve the error of the third step, I want multiple different processes to access the zip at the same time, and use FileMode.Open according to the document. FileAccess.Read, FileShare.ReadWrite read the file stream, but an accident still occurred. What should I do?

### Actual behavior

The process cannot access the file 'xxx.zip' because it is being used by another process. ?System.IO.IOException: The process cannot access the file 'xxx.zip' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)

### Configuration

.net 6
linux centos 7

**Comment by stephentoub** [comment]
If the other process opened the file without appropriate sharing permissions, and then didn't close the file before your process tried to open it, you'll get the cited error (it's not just about what you specify for FileShare in the second process but also how the first process opens the file). You'll need to find/fix the issue in the process that has the file open. This error is just coming from the operating system.
