### ISSUE TITLE
[wasm] Methodical_d2 test failure

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#100757]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100718-merge-eb0bf3a1ea06483aa8/Methodical_d2/1/console.fea1d183.log?helixlogtype=result)
```
02:02:03] info: 02:02:03.472 Running test: JIT/Methodical/VT/port/huge_gcref_d/huge_gcref_d.dll
[02:02:03] info: Creating 32-dimension array
[02:02:03] info: 0 1 40 1 80 2 120 1 160 1 200 2 240 1 280 1 320 2 360 1 400 1 440 2 480 1 520 1 560 2 600 1 640 1 680 2 720 1 760 1 800 2 840 1 880 1 920 2 960 1 1000 1 1040 2 1080 1 1120 1 1160 2 1200 1 1240 1 TEST PASSED02:02:03.479 Passed test: JIT/Methodical/VT/port/huge_gcref_d/huge_gcref_d.dll
[02:02:03] info: 02:02:03.481 Running test: JIT/Methodical/refany/indcall_d/indcall_d.dll
[02:02:03] info: 02:02:03.482 Passed test: JIT/Methodical/refany/indcall_d/indcall_d.dll
[02:02:03] info: 02:02:03.483 Running test: JIT/Methodical/xxblk/initblk3_d/initblk3_d.dll
[02:02:03] info: PASSED
[02:02:03] info: 02:02:03.485 Passed test: JIT/Methodical/xxblk/initblk3_d/initblk3_d.dll
[02:02:03] info: 02:02:03.486 Running test: JIT/Methodical/Invoke/fptr/instftn_t_d/instftn_t_d.dll
[02:02:03] info: JitTest_instftn_t_fptr_il.Test
[02:02:03] info: JitTest_instftn_t_fptr_il.Test
[02:02:03] info: 02:02:03.488 Passed test: JIT/Methodical/Invoke/fptr/instftn_t_d/instftn_t_d.dll
[02:02:03] info: 02:02:03.489 Running test: JIT/Methodical/MDArray/basics/jaggedarr_basics_cs_d/jaggedarr_basics_cs_d.dll
[02:02:03] info: MONO_WASM: memory access out of bounds
[02:02:03] info: RuntimeError: memory access out of bounds
[02:02:03] info:     at dlmalloc (wasm://wasm/00b35686:wasm-function[8549]:0x209cb3)
[02:02:03] info:     at dlrealloc (wasm://wasm/00b35686:wasm-function[8551]:0x20b722)
[02:02:03] info:     at monoeg_realloc (wasm://wasm/00b35686:wasm-function[563]:0x40048)
[02:02:03] info:     at interp_create_var_explicit (wasm://wasm/00b35686:wasm-function[345]:0x200a2)
[02:02:03] info:     at interp_create_stack_var (wasm://wasm/00b35686:wasm-function[426]:0x3b152)
[02:02:03] info:     at push_type_explicit (wasm://wasm/00b35686:wasm-function[365]:0x2a106)
[02:02:03] info:     at generate_code (wasm://wasm/00b35686:wasm-function[360]:0x2316a)
[02:02:03] info:     at mono_interp_transform_method (wasm://wasm/00b35686:wasm-function[402]:0x2f061)
[02:02:03] info:     at do_transform_method (wasm://wasm/00b35686:wasm-function[219]:0x1b70b)
[02:02:03] info:     at mono_interp_exec_method (wasm://wasm/00b35686:wasm-function[218]:0x1b481)
[02:02:03] info:     at interp_runtime_invoke (wasm://wasm/00b35686:wasm-function[255]:0x1d07d)
[02:02:03] info:     at mono_jit_runtime_invoke (wasm://wasm/00b35686:wasm-function[3207]:0xecb7c)
[02:02:03] info:     at do_runtime_invoke (wasm://wasm/00b35686:wasm-function[2532]:0xc293c)
[02:02:03] info:     at mono_runtime_invoke_checked (wasm://wasm/00b35686:wasm-function[2531]:0xc28cc)
[02:02:03] info:     at ves_icall_InternalInvoke_raw (wasm://wasm/00b35686:wasm-function[1901]:0x9e81e)
[02:02:03] info:     at do_icall (wasm://wasm/00b35686:wasm-function[295]:0x1edfe)
[02:02:03] info:     at do_icall_wrapper (wasm://wasm/00b35686:wasm-function[227]:0x1c409)
[02:02:03] info:     at mono_interp_exec_method (wasm://wasm/00b35686:wasm-function[218]:0xeaea)
[02:02:03] info:     at interp_runtime_invoke (wasm://wasm/00b35686:wasm-function[255]:0x1d07d)
[02:02:03] info:     at mono_jit_runtime_invoke (wasm://wasm/00b35686:wasm-function[3207]:0xecb7c)
[02:02:03] info:     at do_runtime_invoke (wasm://wasm/00b35686:wasm-function[2532]:0xc293c)
[02:02:03] info:     at mono_runtime_try_invoke (wasm://wasm/00b35686:wasm-function[2538]:0xc316c)
[02:02:03] info:     at mono_runtime_invoke (wasm://wasm/00b35686:wasm-function[2562]:0xc57c0)
[02:02:03] info:     at mono_wasm_invoke_jsexport (wasm://wasm/00b35686:wasm-function[166]:0xace8)
[02:02:03] info:     at Module._mono_wasm_invoke_jsexport [as mono_wasm_invoke_jsexport] (/root/helix/work/workitem/e/_framework/dotnet.native.js:8:121386)
[02:02:03] info:     at bn (/root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:30065)
[02:02:03] info:     at /root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:188610
[02:02:03] info:     at Object.il [as runMain] (/root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:188738)
[02:02:03] info:     at async run (/root/helix/work/workitem/e/test-main.js:350:32)
[02:02:03] info:     at async /root/helix/work/workitem/e/test-main.js:366:1
[02:02:03] info: Process v8 exited with 1
```

Another Log
```
[02:02:03] info: Creating 32-dimension array
[02:02:03] info: 0 1 40 1 80 2 120 1 160 1 200 2 240 1 280 1 320 2 360 1 400 1 440 2 480 1 520 1 560 2 600 1 640 1 680 2 720 1 760 1 800 2 840 1 880 1 920 2 960 1 1000 1 1040 2 1080 1 1120 1 1160 2 1200 1 1240 1 TEST PASSED02:02:03.479 Passed test: JIT/Methodical/VT/port/huge_gcref_d/huge_gcref_d.dll
[02:02:03] info: 02:02:03.481 Running test: JIT/Methodical/refany/indcall_d/indcall_d.dll
[02:02:03] info: 02:02:03.482 Passed test: JIT/Methodical/refany/indcall_d/indcall_d.dll
[02:02:03] info: 02:02:03.483 Running test: JIT/Methodical/xxblk/initblk3_d/initblk3_d.dll
[02:02:03] info: PASSED
[02:02:03] info: 02:02:03.485 Passed test: JIT/Methodical/xxblk/initblk3_d/initblk3_d.dll
[02:02:03] info: 02:02:03.486 Running test: JIT/Methodical/Invoke/fptr/instftn_t_d/instftn_t_d.dll
[02:02:03] info: JitTest_instftn_t_fptr_il.Test
[02:02:03] info: JitTest_instftn_t_fptr_il.Test
[02:02:03] info: 02:02:03.488 Passed test: JIT/Methodical/Invoke/fptr/instftn_t_d/instftn_t_d.dll
[02:02:03] info: 02:02:03.489 Running test: JIT/Methodical/MDArray/basics/jaggedarr_basics_cs_d/jaggedarr_basics_cs_d.dll
[02:02:03] info: MONO_WASM: memory access out of bounds
[02:02:03] info: RuntimeError: memory access out of bounds
[02:02:03] info:     at dlmalloc (wasm://wasm/00b35686:wasm-function[8549]:0x209cb3)
[02:02:03] info:     at dlrealloc (wasm://wasm/00b35686:wasm-function[8551]:0x20b722)
[02:02:03] info:     at monoeg_realloc (wasm://wasm/00b35686:wasm-function[563]:0x40048)
[02:02:03] info:     at interp_create_var_explicit (wasm://wasm/00b35686:wasm-function[345]:0x200a2)
[02:02:03] info:     at interp_create_stack_var (wasm://wasm/00b35686:wasm-function[426]:0x3b152)
[02:02:03] info:     at push_type_explicit (wasm://wasm/00b35686:wasm-function[365]:0x2a106)
[02:02:03] info:     at generate_code (wasm://wasm/00b35686:wasm-function[360]:0x2316a)
[02:02:03] info:     at mono_interp_transform_method (wasm://wasm/00b35686:wasm-function[402]:0x2f061)
[02:02:03] info:     at do_transform_method (wasm://wasm/00b35686:wasm-function[219]:0x1b70b)
[02:02:03] info:     at mono_interp_exec_method (wasm://wasm/00b35686:wasm-function[218]:0x1b481)
[02:02:03] info:     at interp_runtime_invoke (wasm://wasm/00b35686:wasm-function[255]:0x1d07d)
[02:02:03] info:     at mono_jit_runtime_invoke (wasm://wasm/00b35686:wasm-function[3207]:0xecb7c)
[02:02:03] info:     at do_runtime_invoke (wasm://wasm/00b35686:wasm-function[2532]:0xc293c)
[02:02:03] info:     at mono_runtime_invoke_checked (wasm://wasm/00b35686:wasm-function[2531]:0xc28cc)
[02:02:03] info:     at ves_icall_InternalInvoke_raw (wasm://wasm/00b35686:wasm-function[1901]:0x9e81e)
[02:02:03] info:     at do_icall (wasm://wasm/00b35686:wasm-function[295]:0x1edfe)
[02:02:03] info:     at do_icall_wrapper (wasm://wasm/00b35686:wasm-function[227]:0x1c409)
[02:02:03] info:     at mono_interp_exec_method (wasm://wasm/00b35686:wasm-function[218]:0xeaea)
[02:02:03] info:     at interp_runtime_invoke (wasm://wasm/00b35686:wasm-function[255]:0x1d07d)

[02:02:03] info: Process v8 exited with 1
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=633984
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2185",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[634558](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634558)|dotnet/runtime|[Methodical_d2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634558&view=ms.vss-test-web.build-test-results-tab&runId=15611658&resultId=107631)|dotnet/runtime#100520|
|[634470](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634470)|dotnet/runtime|[Methodical_d2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=634470&view=ms.vss-test-web.build-test-results-tab&runId=15607912&resultId=107631)|dotnet/runtime#100610|
|[633984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633984)|dotnet/runtime|[Methodical_d2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633984&view=ms.vss-test-web.build-test-results-tab&runId=15587112&resultId=107631)|dotnet/runtime#99339|
|[633836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633836)|dotnet/runtime|[Methodical_d2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633836&view=ms.vss-test-web.build-test-results-tab&runId=15585034&resultId=107631)|dotnet/runtime#100520|
|[633815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633815)|dotnet/runtime|[Methodical_d2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633815&view=ms.vss-test-web.build-test-results-tab&runId=15583538&resultId=107527)|dotnet/runtime#100726|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|5|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=633984
**Error message validated:** `[Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2185`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/8/2024 11:43:58 AM UTC

**Comment by pavelsavara** [comment]
note this is not multi-threading! (also just V8)

**Comment by pavelsavara** [comment]
There are lot of cases captured in https://github.com/dotnet/runtime/issues/96546 but that has broader filter.

**Comment by pavelsavara** [comment]
Here are some other hints:
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100726-merge-18cf12a229fe40d6bb/Methodical_r2/1/console.3e3e739d.log?helixlogtype=result)
```
[13:49:35] info: [MONO] /__w/1/s/src/mono/mono/utils/monobitset.c:109: assertion 'pos < set->size' failed
```

Another [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100661-merge-8850b35a806c459cb5/Methodical_d2/1/console.d1359f54.log?helixlogtype=result)
```
[04:36:12] info: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/seq-points-data.c:29, condition `size < 4 && "value has more than 28 bits"' not met
```

**Comment by pavelsavara** [comment]
another [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100702-merge-36928e9a114142a78d/Methodical_d2/1/console.7c00e43d.log?helixlogtype=result)
