### ISSUE TITLE
Test failure: Interop/COM/NETClients/MiscTypes/NetClientMiscTypes/NetClientMiscTypes.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#100738]
**Failed in:** [runtime-coreclr gcstress0x3-gcstress0xc 20240406.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=633038&view=ms.vss-test-web.build-test-results-tab&runId=15563992&resultId=165004&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked gcstress0x3 @ Windows.11.Arm64.Open
    - Interop/COM/NETClients/MiscTypes/NetClientMiscTypes/NetClientMiscTypes.cmd
    - Interop/COM/NativeClients/MiscTypes/MiscTypes.cmd
```

**Error message:**
```
 
Assert failure(PID 8140 [0x00001fcc], Thread: 268 [0x010c]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x184 (0x00007ff8`4252a4bc)
CORECLR! Object::Validate + 0xA4 (0x00007ff8`4252a27c)
CORECLR! WKS::GCHeap::Promote + 0xF8 (0x00007ff8`427a0958)
CORECLR! GCFrame::GcScanRoots + 0x80 (0x00007ff8`424bd780)
CORECLR! ScanStackRoots + 0x300 (0x00007ff8`425f9ea0)
CORECLR! GCToEEInterface::GcScanRoots + 0x1A4 (0x00007ff8`425f8b9c)
CORECLR! WKS::gc_heap::mark_phase + 0x46C (0x00007ff8`427c258c)
CORECLR! WKS::gc_heap::gc1 + 0x23C (0x00007ff8`427b85b4)
CORECLR! WKS::gc_heap::garbage_collect + 0x6B8 (0x00007ff8`427b8338)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x520 (0x00007ff8`4279f138)
    File: D:_work1ssrccoreclrmobject.cpp:521
    Image: C:hwAC000903pcorerun.exe


Return code:      1
Raw output file:      C:hwAC000903wB44709ADuploadsCOMNETClientsMiscTypesNetClientMiscTypesoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwAC000903pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  NetClientMiscTypes.dll 
Running ValidationTests ...
-- Primitives <=> VARIANT...
-- BSTR <=> VARIANT...
-- System.Guid <=> VARIANT...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 4/6/2024 3:08:56 PM
Processing C:corescorerun.exe.8140.dmp
Unable to find cdb.exe at C:Program Files (x86)Windows Kits10Debuggersrm64cdb.exe
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwAC000903wB44709ADeInteropInterop../COM/NETClients/MiscTypes/NetClientMiscTypes/NetClientMiscTypes.cmd
```

**Stack trace:**
```
    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor224|25_225(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by AaronRobinsonMSFT** [comment]
Yes.

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/runtime/pull/100787
