### ISSUE TITLE
System.TypeLoadException from static field

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#100950]
### Description

The runtime seems to throw a `System.TypeLoadException` on a struct `S1` with a static field of type `Nullable<S1>`.

### Reproduction Steps

Run the following code:
```csharp
S1.X();

struct S1
{
    private static S1? _s1;
    public static void X() { }
}
```

https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwMoEYB0ANAFASgG4BYAKDIGdhIBjYAAgzIG8z736AHMASwDcAhsACm9AALoAbI3QB+egH0K6EqQ7iAzOKniALPTz56zegF8y50kA==

### Expected behavior

Does not crash

### Actual behavior

Crashes:
```
System.TypeLoadException: Could not load type 'S1' from assembly '_, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Program.<Main>$(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

### Configuration

Windows 10.0.19045.4291 x64
.NET 8.0.4
And Sharplab.io

**Comment by Tornhoof** [comment]
See #79636

**Comment by hamarb123** [comment]
Found this following that trail: https://github.com/dotnet/runtime/issues/6924#issuecomment-1496804660 - I see no other issue for it

**Comment by hamarb123** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/88030

**Comment by hamarb123** [comment]
Actually, that issue, while very similar, is not exactly the same as this one - in the other one the generic parameter is not actually used, whereas for `Nullable<T>` it would be. I'll reopen so someone on runtime team can decide if they should be merged or separate (since I'm not sure if the fix for the other one would fix my one).

**Comment by steveisok** [comment]
Closing as it's a duplicate of https://github.com/dotnet/runtime/issues/104511

**Comment by kg** [comment]
This looks like it's actually different from 104511 somehow. Not sure what's going on yet.

**Comment by hamarb123** [comment]
This was just marked as a duplicate of https://github.com/dotnet/runtime/issues/79636, which is technically true, but that issue was falsely closed as a duplicate of https://github.com/dotnet/runtime/issues/6924 (although that was also technically true at the time I think, but this issue wasn't fixed as a part of the fix for that issue, https://github.com/dotnet/runtime/issues/6924#issuecomment-1496804660). That issue was marked as fixed in .NET 8, but this issue was literally reported on .NET 8 & still reproduces on godbolt running the latest .NET 10 main: https://godbolt.org/z/bcxvEE3xd

<img width="1710" height="388" alt="Image" src="https://github.com/user-attachments/assets/b9bc124b-6749-43fe-85b4-1f5e009e6e08" />

@mangod9 can you please re-open this issue (or the one it's marked as a duplicate of I guess), and to the next person tempted to close it, please double check before it's closed incorrectly for a third time. Thanks.

**Comment by davidwrighton** [comment]
Fixed in .NET 10

**Comment by hamarb123** [comment]
Edit: just saw your PR - sorry for the annoyed message & thanks for fixing it :)
