### ISSUE TITLE
System.Net.Tests.HttpWebRequestTest_Async.GetResponseAsync_ParametersAreNotCachable_CreateNewClient test fails

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#100912]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=717524
Build error leg or test failing: Libraries Test Run checked coreclr linux arm64 Debug

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "GetResponseAsync_ParametersAreNotCachable_CreateNewClient.*FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=717524
**Error message validated:** `[GetResponseAsync_ParametersAreNotCachable_CreateNewClient.*FAIL]`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/3/2024 10:43:30 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[719004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719004)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719004&view=ms.vss-test-web.build-test-results-tab&runId=18019696&resultId=208842)|dotnet/runtime#102680|
|[718697](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718697)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718697&view=ms.vss-test-web.build-test-results-tab&runId=18011186&resultId=218803)|dotnet/runtime#103899|
|[718354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718354)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexMatchTests.Match_StaticMethods_DefaultTimeout_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718354&view=ms.vss-test-web.build-test-results-tab&runId=18003654&resultId=209956)|dotnet/runtime#103902|
|[717524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717524)|dotnet/runtime|[System.Net.Tests.WebRequestTest.SendGetRequest_WithGlobalCachePolicyBypassCache_DoNotAddCacheHeaders](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717524&view=ms.vss-test-web.build-test-results-tab&runId=17972332&resultId=178398)|dotnet/runtime#103738|
|[715984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715984)|dotnet/runtime|[System.Diagnostics.DiagnosticSource.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715984&view=ms.vss-test-web.build-test-results-tab&runId=17923084&resultId=210246)|dotnet/runtime#103706|
|[714212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714212)|dotnet/runtime|[System.Net.Tests.WebRequestTest.SendGetRequest_WithGlobalCachePolicyBypassCache_DoNotAddCacheHeaders](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714212&view=ms.vss-test-web.build-test-results-tab&runId=17867082&resultId=172985)|dotnet/runtime#103738|
|[711142](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711142)|dotnet/runtime|[System.Diagnostics.DiagnosticSource.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711142&view=ms.vss-test-web.build-test-results-tab&runId=17773630&resultId=210088)|dotnet/runtime#103612|
|[709124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709124)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709124&view=ms.vss-test-web.build-test-results-tab&runId=17705274&resultId=167220)|dotnet/runtime#103427|
|[708567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708567)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708567&view=ms.vss-test-web.build-test-results-tab&runId=17689858&resultId=207953)|dotnet/runtime#100041|
|[702919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=702919)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=702919&view=ms.vss-test-web.build-test-results-tab&runId=17509296&resultId=208215)|dotnet/runtime#103241|
|[2470077](https://dev.azure.com/dnceng/internal/_build/results?buildId=2470077)|dotnet-runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng//internal/_build/results?buildId=2470077&view=ms.vss-test-web.build-test-results-tab&runId=53706423&resultId=156202)|[#40222](https://dev.azure.com/dnceng/internal/_git/dotnet-runtime/pullrequest/40222)|
|[701749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701749)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701749&view=ms.vss-test-web.build-test-results-tab&runId=17469724&resultId=205029)|dotnet/runtime#103031|
|[701226](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701226)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701226&view=ms.vss-test-web.build-test-results-tab&runId=17451522&resultId=207912)|dotnet/runtime#103148|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|13|

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240617.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709728&view=ms.vss-test-web.build-test-results-tab&runId=17728380&resultId=163571&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitminopts-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 38

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    924 BrokerInfrastructure, DcomLaunch, Power,    
                                   SystemEventsBroker                          
svchost.exe                    488 RpcEptMapper, RpcSs                         
svchost.exe                    548 LSM                                         
svchost.exe                   1136 TermService                                 
svchost.exe                   1192 lmhosts                                     
svchost.exe                   1232 NcbService                                  
svchost.exe                   1240 TimeBrokerSvc                               
svchost.exe                   1312 CoreMessagingRegistrar                      
svchost.exe                   1372 Schedule                                    
svchost.exe                   1392 ProfSvc                                     
svchost.exe                   1436 nsi                                         
svchost.exe                   1464 vmicheartbeat                               
svchost.exe                   1488 vmickvpexchange                             
svchost.exe                   1496 vmicshutdown                                
svchost.exe                   1532 UserManager                                 
svchost.exe                   1544 netprofm                                    
svchost.exe                   1628 vmictimesync                                
svchost.exe                   1708 UmRdpService                                
svchost.exe                   1772 EventLog                                    
svchost.exe                   1872 DispBrokerDesktopSvc                        
svchost.exe                   1932 EventSystem                                 
svchost.exe                   1952 SysMain                                     
svchost.exe                   1976 Themes                                      
svchost.exe                   2016 CryptSvc                                    
svchost.exe                   2228 SENS                                        
svchost.exe                   2252 LanmanWorkstation                           
svchost.exe                   2268 AppIDSvc                                    
svchost.exe                   2332 AudioEndpointBuilder                        
svchost.exe                   2368 FontCache                                   
svchost.exe                   2408 Dnscache                                    
svchost.exe                   2452 SessionEnv                                  
svchost.exe                   2516 Audiosrv                                    
svchost.exe                   2528 CertPropSvc                                 
svchost.exe                   2584 TextInputManagementService                  
svchost.exe                   2720 Dhcp                                        
svchost.exe                   2728 DusmSvc                                     
svchost.exe                   2744 Wcmsvc                                      
svchost.exe                   2860 ShellHWDetection                            
svchost.exe                   3068 BFE, mpssvc                                 
svchost.exe                   2076 WinHttpAutoProxySvc                         
svchost.exe                   3224 DiagTrack                                   
svchost.exe                   3232 DPS                                         
svchost.exe                   3244 iphlpsvc                                    
svchost.exe                   3332 StateRepository                             
svchost.exe                   3360 LanmanServer                      
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at Microsoft.Extensions.Hosting.WindowsServiceTester.Dispose(Boolean disposing) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 147
   at System.ComponentModel.Component.Dispose() in /_/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/Component.cs:line 73
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs:line 85
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240621.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715271&view=ms.vss-test-web.build-test-results-tab&runId=17897046&resultId=164200&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitminopts-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 36


Image Name                     PID Services

========================= ======== ============================================
svchost.exe                    928 BrokerInfrastructure, DcomLaunch, Power,

SystemEventsBroker

svchost.exe                    524 RpcEptMapper, RpcSs

svchost.exe                    528 LSM

svchost.exe                   1052 TermService

svchost.exe                   1112 lmhosts

svchost.exe                   1152 nsi

svchost.exe                   1160 NcbService

svchost.exe                   1260 TimeBrokerSvc

svchost.exe                   1280 netprofm

svchost.exe                   1296 gpsvc

svchost.exe                   1452 Schedule

svchost.exe                   1500 CoreMessagingRegistrar

svchost.exe                   1512 UmRdpService

svchost.exe                   1564 ProfSvc

svchost.exe                   1708 Dnscache

svchost.exe                   1764 UserManager

svchost.exe                   1776 vmicheartbeat

svchost.exe                   1812 LanmanWorkstation

svchost.exe                   1824 vmickvpexchange

svchost.exe                   1856 CryptSvc

svchost.exe                   1908 vmicshutdown

svchost.exe                   1976 vmictimesync

svchost.exe                   2004 DispBrokerDesktopSvc

svchost.exe                   2084 AppIDSvc

svchost.exe                   2212 EventLog

svchost.exe                   2284 SessionEnv

svchost.exe                   2312 Dhcp

svchost.exe                   2360 EventSystem

svchost.exe                   2372 SysMain

svchost.exe                   2388 Themes

svchost.exe                   2440 CertPropSvc

svchost.exe                   2628 SENS

svchost.exe                   2672 WinHttpAutoProxySvc

svchost.exe                   2684 AudioEndpointBuilder

svchost.exe                   2708 FontCache

svchost.exe                   2816 Audiosrv

svchost.exe                   2904 TextInputManagementService

svchost.exe                   2980 Wcmsvc

svchost.exe                   2988 DusmSvc

svchost.exe                   3052 ShellHWDetection

svchost.exe                   2060 BFE, mpssvc

svchost.exe                   3184 StateRepository

svchost.exe                   3224 DiagTrack

svchost.exe                   3232 iphlpsvc

svchost.exe                   3244 DPS                
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at Microsoft.Extensions.Hosting.WindowsServiceTester.Dispose(Boolean disposing) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 147
   at System.ComponentModel.Component.Dispose() in /_/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/Component.cs:line 73
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs:line 85
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240624.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717664&view=ms.vss-test-web.build-test-results-tab&runId=17978046&resultId=202482&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-disabler2r-Windows.11.Arm64.Open
    - System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 36

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    924 BrokerInfrastructure, DcomLaunch, Power,    
                                   SystemEventsBroker                          
svchost.exe                    496 RpcEptMapper, RpcSs                         
svchost.exe                    868 LSM                                         
svchost.exe                   1064 CryptSvc                                    
svchost.exe                   1072 TermService                                 
svchost.exe                   1132 lmhosts                                     
svchost.exe                   1220 NcbService                                  
svchost.exe                   1268 gpsvc                                       
svchost.exe                   1304 AppIDSvc                                    
svchost.exe                   1348 nsi                                         
svchost.exe                   1420 TimeBrokerSvc                               
svchost.exe                   1428 netprofm                                    
svchost.exe                   1504 Schedule                                    
svchost.exe                   1540 ProfSvc                                     
svchost.exe                   1548 CoreMessagingRegistrar                      
svchost.exe                   1576 UmRdpService                                
svchost.exe                   1652 vmicheartbeat                               
svchost.exe                   1664 vmickvpexchange                             
svchost.exe                   1724 vmicshutdown                                
svchost.exe                   1732 UserManager                                 
svchost.exe                   1792 vmictimesync                                
svchost.exe                   1884 LanmanWorkstation                           
svchost.exe                   1472 DispBrokerDesktopSvc                        
svchost.exe                   2104 SessionEnv                                  
svchost.exe                   2124 Dnscache                                    
svchost.exe                   2140 EventLog                                    
svchost.exe                   2200 CertPropSvc                                 
svchost.exe                   2240 SysMain                                     
svchost.exe                   2260 Themes                                      
svchost.exe                   2284 EventSystem                                 
svchost.exe                   2492 SENS                                        
svchost.exe                   2512 Dhcp                                        
svchost.exe                   2564 AudioEndpointBuilder                        
svchost.exe                   2576 FontCache                                   
svchost.exe                   2688 Audiosrv                                    
svchost.exe                   2744 WinHttpAutoProxySvc                         
svchost.exe                   2796 TextInputManagementService                  
svchost.exe                   2880 DusmSvc                                     
svchost.exe                   2888 Wcmsvc                                      
svchost.exe                   2976 ShellHWDetection                            
svchost.exe                   2628 BFE, mpssvc                                 
svchost.exe                   3152 DiagTrack                                   
svchost.exe                   3160 DPS                                         
svchost.exe                   3172 iphlpsvc                                    
svchost.exe                   3256 LanmanServer                      
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime() in /_/src/libraries/System.Security.Cryptography/tests/X509Certificates/PfxIterationCountTests.X509Certificate2.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by karelz** [comment]
@v-wenyuxu we hid the dumps above as "off-topic", they are not related to this issue, only the error seems similar. Please create a new separate issue and investigate it if you want to get traction on that. Thanks!

**Comment by liveans** [comment]
When I look at the kusto data, what I see is this test is failing when `ALL` RemoteExecutor tests are failing within the test suite. I don't think this is related to `HttpWebRequest` changes we've made starting of this year. I don't have idea about how `RemoteExecutor` actually works.
/cc @rzikm

**Comment by liveans** [comment]
Closing this in favor of #104366
