### ISSUE TITLE
[browser][MT] TimeZoneInfoTests.ChangeLocalTimeZone not thread safe

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#101166]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-101138-merge-c3006911f3b84935a1/WasmTestOnBrowser-System.Runtime.Tests/1/console.5b66ee33.log?helixlogtype=result)
```
[20:36:08] info: [FAIL] System.Tests.TimeZoneInfoTests.ChangeLocalTimeZone(id: "America/Buenos_Aires")
[20:36:08] info: Assert.Equal() Failure: Strings differ
[20:36:08] info:            ↓ (pos 0)
[20:36:08] info: Expected: "-03"
[20:36:08] info: Actual:   "UTC"
[20:36:08] info:            ↑ (pos 0)
[20:36:08] info:    at System.Tests.TimeZoneInfoTests.ChangeLocalTimeZone(String id)
[20:36:08] info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[20:36:08] info:    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=645791
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.TimeZoneInfoTests.ChangeLocalTimeZone",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by mkhamoyan** [comment]
As discussed in https://github.com/dotnet/runtime/pull/103953 we need to add additional test case to observe a single non-UI thread performing the change and examining the slow propagation of this change.
The objective is to understand the underlying mechanism in emscripten and identify the necessary synchronization in mono to prevent issues like "read after write hazards".
This approach will provide clearer insights into the root cause.
