### ISSUE TITLE
[mono][tvos] Failure in System.Memory.Tests.Span.StringSearchValuesTests.SimpleIndexOfAnyValues

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#101367]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=651298&
Build error leg or test failing: System.Memory.Tests

Failing job: `tvos_arm64_release_allsubsets_mono` from `runtime-extra-platforms`

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Exception messages: Expected 1, got 0 for impl='AsciiStringSearchValuesTeddyNonBucketizedN2`2 [CaseSensitive, CaseSensitive]' comparison=Ordinal needle='7b, [ 99, 33 ], [ 33, 37 ]', haystack='[ 0, 33, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 98 ]'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Stack trace (from *net.dot.System.Memory.Tests.log* file):
```
[19:30:07.3407940] 2024-04-21 16:30:07.328 System.Memory.Tests[67087:86388886] 	[FAIL] System.Memory.Tests.Span.StringSearchValuesTests.SimpleIndexOfAnyValues(valuesArray: ["ab", "c!", "!%"])
[19:30:07.3408460] 2024-04-21 16:30:07.328 System.Memory.Tests[67087:86388886] Expected 1, got 0 for impl='AsciiStringSearchValuesTeddyNonBucketizedN2`2 [CaseSensitive, CaseSensitive]' comparison=Ordinal needle='7b, [ 99, 33 ], [ 33, 37 ]', haystack='[ 0, 33, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 98 ]'
[19:30:07.3412040] 2024-04-21 16:30:07.329 System.Memory.Tests[67087:86388886]    at System.Memory.Tests.Span.StringSearchValuesTests.StringSearchValuesTestHelper.AssertionFailed(ReadOnlySpan`1 haystack, String[] needle, SearchValues`1 searchValues, StringComparison comparisonType, Int32 expected, Int32 actual)
[19:30:07.3412440]    at System.Memory.Tests.Span.StringSearchValuesTests.<>c__DisplayClass5_0.<IndexOfAny>g__TestWithDifferentMarkerChars|3(Span`1 haystack, Char marker)
[19:30:07.3414680] 2024-04-21 16:30:07.329 System.Memory.Tests[67087:86388886]    at System.Memory.Tests.Span.StringSearchValuesTests.<>c__DisplayClass5_0.<IndexOfAny>g__TestWithPoisonPages|2(PoisonPagePlacement poisonPlacement, Int32 haystackLength)
[19:30:07.3414970] 2024-04-21 16:30:07.330 System.Memory.Tests[67087:86388886]    at System.Memory.Tests.Span.StringSearchValuesTests.IndexOfAny(StringComparison comparisonType, Int32 expected, String text, String values)
[19:30:07.3415060]    at System.Memory.Tests.Span.StringSearchValuesTests.<SimpleIndexOfAnyValues>g__TestCore|7_3(String[] valuesArray)
[19:30:07.3415130]    at System.Memory.Tests.Span.StringSearchValuesTests.SimpleIndexOfAnyValues(String[] valuesArray)
[19:30:07.3421790] 2024-04-21 16:30:07.330 System.Memory.Tests[67087:86388886]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[19:30:07.3422030]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object , Span`1 , BindingFlags )
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=651298
**Error message validated:** `[Exception messages: Expected 1, got 0 for impl='AsciiStringSearchValuesTeddyNonBucketizedN2`2 [CaseSensitive, CaseSensitive]' comparison=Ordinal needle='7b, [ 99, 33 ], [ 33, 37 ]', haystack='[ 0, 33, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 98 ]'`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 4/22/2024 7:59:23 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by matouskozak** [comment]
The failures are not blocking clean CI because they are happening only occasionally. First failure I could find happened on 9th of January (https://dev.azure.com/dnceng-public/public/_build/results?buildId=519103) and last so far on 28th of April (https://dev.azure.com/dnceng-public/public/_build/results?buildId=658560&view=results).

**Comment by matouskozak** [comment]
No longer failing, closing.
