### ISSUE TITLE
[wasm] AOT null function or function signature mismatch

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#101481]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-2382c6b95790428b91/WasmTestOnChrome-ST-Common.Tests/1/console.1771950c.log?helixlogtype=result)
```
[19:27:59] fail: MONO_WASM: null function or function signature mismatch
RuntimeError: null function or function signature mismatch
    at xunit.assert_Xunit_Sdk_CollectionTracker_CheckIfEnumerablesAreEqual_Xunit_Sdk_CollectionTracker_Xunit_Sdk_CollectionTracker_System_Collections_IEqualityComparer_bool_System_Nullable_1_int_ (xunit.assert_Xunit_Sdk_CollectionTracker_CheckIfEnumerablesAreEqual_Xunit_Sdk_CollectionTracker_Xunit_Sdk_CollectionTracker_System_Collections_IEqualityComparer_bool_System_Nullable_1_int_ (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[40181]:0xc80abc))
    at xunit.assert_Xunit_Sdk_CollectionTracker_AreCollectionsEqual_Xunit_Sdk_CollectionTracker_Xunit_Sdk_CollectionTracker_System_Collections_IEqualityComparer_bool_System_Nullable_1_int_ (xunit.assert_Xunit_Sdk_CollectionTracker_AreCollectionsEqual_Xunit_Sdk_CollectionTracker_Xunit_Sdk_CollectionTracker_System_Collections_IEqualityComparer_bool_System_Nullable_1_int_ (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[40158]:0xc7e1d7))
    at xunit.assert_Xunit_Sdk_AssertEqualityComparer_1_T_REF_Equals_T_REF_Xunit_Sdk_CollectionTracker_T_REF_Xunit_Sdk_CollectionTracker_System_Nullable_1_int_ (xunit.assert_Xunit_Sdk_AssertEqualityComparer_1_T_REF_Equals_T_REF_Xunit_Sdk_CollectionTracker_T_REF_Xunit_Sdk_CollectionTracker_System_Nullable_1_int_ (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[40157]:0xc7d259))
    at aot-instances_aot_wrapper_gsharedvt_out_sig_u1_this_objobjobjobjbii (aot-instances_aot_wrapper_gsharedvt_out_sig_u1_this_objobjobjobjbii (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[48004]:0xed5a66))
    at jit_call_cb (jit_call_cb (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[63559]:0x142fafe))
    at mono_llvm_cpp_catch_exception (mono_llvm_cpp_catch_exception (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[68929]:0x1555340))
    at mono_llvm_catch_exception (mono_llvm_catch_exception (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[68996]:0x1559a39))
    at do_jit_call (do_jit_call (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[63476]:0x142c256))
    at mono_interp_exec_method (mono_interp_exec_method (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[63471]:0x14201c3))
    at interp_entry (interp_entry (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[63550]:0x142f3c1))
    at interp_entry_static_3 (interp_entry_static_3 (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[63596]:0x1430f79))
    at aot-instances_aot_wrapper_gsharedvt_in_sig_void_objobjobj (aot-instances_aot_wrapper_gsharedvt_in_sig_void_objobjobj (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[46383]:0xe38a02))
    at xunit.assert_Xunit_Assert_Equal_T_REF_T_REF_T_REF_System_Collections_Generic_IEqualityComparer_1_T_REF (xunit.assert_Xunit_Assert_Equal_T_REF_T_REF_T_REF_System_Collections_Generic_IEqualityComparer_1_T_REF (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[40024]:0xc6ecf0))
    at aot-instances_Xunit_Assert_Equal_T_BYTE_System_Collections_Generic_IEnumerable_1_T_BYTE_System_Collections_Generic_IEnumerable_1_T_BYTE (aot-instances_Xunit_Assert_Equal_T_BYTE_System_Collections_Generic_IEnumerable_1_T_BYTE_System_Collections_Generic_IEnumerable_1_T_BYTE (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[45415]:0xe07209))
    at Common.Tests_System_Net_Http_Unit_Tests_HPack_HuffmanDecodingTests_HuffmanDecoding_ValidEncoding_Succeeds (Common.Tests_System_Net_Http_Unit_Tests_HPack_HuffmanDecodingTests_HuffmanDecoding_ValidEncoding_Succeeds (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[688]:0x87373))
    at aot-instances_aot_wrapper_gsharedvt_out_sig_void_this_ (aot-instances_aot_wrapper_gsharedvt_out_sig_void_this_ (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[44920]:0xde5feb))
    at aot-instances_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_object_intptr_intptr_intptr (aot-instances_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_object_intptr_intptr_intptr (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[58006]:0x11e1b4e))
    at mono_llvmonly_runtime_invoke (mono_llvmonly_runtime_invoke (http://127.0.0.1:49267/_framework/dotnet.native.wasm:wasm-function[68723]:0x1546371))
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=653707
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "null function or function signature mismatch",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by pavelsavara** [comment]
cc @kg @BrzVlad

**Comment by mkhamoyan** [comment]
This is caused because of my draft PR https://github.com/dotnet/runtime/pull/101476, I'll assign this to me.

**Comment by pavelsavara** [comment]
> This is caused because of my draft PR #101476, I'll assign this to me.

no, this was on my PR https://github.com/dotnet/runtime/pull/100697

**Comment by mkhamoyan** [comment]
> no, this was on my PR #100697

I see, my bad.

**Comment by lewing** [comment]
cc @steveisok

**Comment by pavelsavara** [comment]
Not all of them are AOT now, some of them are MT.

**Comment by lewing** [comment]
Almost all of the ST failures are at `at dotnet.native.wasm.Moq_Moq_ExpressionExtensions_IsMatch_System_Linq_Expressions_Expression_Moq_Match` now

**Comment by pavelsavara** [comment]
I hope the the root cause is https://github.com/dotnet/runtime/issues/106200 and fix https://github.com/dotnet/runtime/pull/106313

**Comment by lewing** [comment]
> I hope the the root cause is #106200 and fix #106313

That was definitely not all of them

**Comment by lewing** [comment]
So far it appears we only have MT failures after the alignment fix?

**Comment by pavelsavara** [comment]
Last 2 are MT [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-4f267d3d0e0d49138c/WasmTestOnChrome-MT-System.IO.FileSystem.Tests/1/console.6e8d8c81.log?helixlogtype=result)
```
[09:00:43] fail: [0x000fbb58--UI- 09:00:43.363] MONO_WASM: null function or function signature mismatch
                 RuntimeError: null function or function signature mismatch
                     at call_with_ctx (http://127.0.0.1:41243/_framework/dotnet.native.wasm:wasm-function[8715]:0x228509)
                     at em_task_queue_execute (http://127.0.0.1:41243/_framework/dotnet.native.wasm:wasm-function[8700]:0x227ea2)
                     at receive_notification (http://127.0.0.1:41243/_framework/dotnet.native.wasm:wasm-function[8706]:0x22808e)
                     at em_task_queue_execute (http://127.0.0.1:41243/_framework/dotnet.native.wasm:wasm-function[8700]:0x227ea2)
                     at _emscripten_check_mailbox (http://127.0.0.1:41243/_framework/dotnet.native.wasm:wasm-function[8844]:0x22feac)
                     at callUserCallback (http://127.0.0.1:41243/_framework/dotnet.native.js:8:98666)
                     at checkMailbox (http://127.0.0.1:41243/_framework/dotnet.native.js:8:99197)
```

**Comment by lewing** [comment]
The issue this was mean to catch is no longer applicable to CI since we aren't running the MT tests
