### ISSUE TITLE
[tvos-arm64] System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest failed

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#101549]
```
[FAIL] System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest   Test name: System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest
[05:47:48.9832830] 2024-04-25 02:47:49.011 System.Runtime.Serialization.Xml.Tests[70846:86554902]    Assembly:  [System.Runtime.Serialization.Xml.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[05:47:48.9833110]    Exception messages: Assert.Contains() Failure: Sub-string not found
[05:47:48.9833190] String:    "<xs:complexType name="ExporterTypesTests."···
[05:47:48.9861560] 2024-04-25 02:47:49.011 System.Runtime.Serialization.Xml.Tests[70846:86554902] Not found: "<xs:complexType name="ExporterTypesTests."···   Exception stack traces:    at System.Runtime.Serialization.Xml.XsdDataContractExporterTests.SchemaUtils.OrderedContains(String expected, String& actual)
[05:47:48.9862230] 2024-04-25 02:47:49.011 System.Runtime.Serialization.Xml.Tests[70846:86554902]    at System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest()
[05:47:48.9862380]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[05:47:48.9862450]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=655074&view=results
Build error leg or test failing: tvos-arm64 Release AllSubsets_Mono

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=655074
**Error message validated:** `[[FAIL] System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 4/25/2024 10:55:05 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
@fan this is too broad a pattern it will match any substring assertion that fails (as evidenced by the matches)

**Comment by lewing** [comment]
I've updated ErrorMessage

**Comment by lewing** [comment]
And it is not matching the actual failure because Build Analysis doesn't run against runtime-extra-platforms

**Comment by matouskozak** [comment]
I haven't seen this failure on rolling-builds on main for the past week.

**Comment by akoeplinger** [comment]
Closing as we haven't seen this in a while.
