### ISSUE TITLE
The archive entry was compressed using an unsupported compression method.

### ISSUE THREAD

**Issue by ssreerama** [dotnet/runtime#101689]
### Description

One of our customers are facing this issue continuously when exporting the package from LINUX operating system and trying to import it to Windows OS machine. But the same package is working fine when they are importing in LINUX machine. 

stacktrace: 
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (The archive entry was compressed using an unsupported compression method.))
 ---> System.AggregateException: One or more errors occurred. (The archive entry was compressed using an unsupported compression method.)
 ---> System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)

### Reproduction Steps

This issue arises when exporting the database using SqlPackage CORE version, Sqlpackage uses the system.IO.Packaging dll for generating the compressed bacpac version files. And only happening when involving in LINUX to Windows importing process. 

### Expected behavior

It should import the bacpac with out any errors, other than the sqlpackage related or unsupported sql objects error. 

### Actual behavior

The archive entry was compressed using an unsupported compression method.

### Known Workarounds

Suggested to use the NET Framework MSI version, but for this customer has to change their machine from LINUX to Windows and they are not accepting this workaround.

**Comment by ssreerama** [comment]
Is there any env variable for compression entry that can be set while compressing the package in LINUX env? It seems the entry that is used for compressing is not available in windows(for decompress).

call Stack at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)

**Comment by carlossanlop** [comment]
Can you please share a minimal repro project that can reproduce the issue as described?

**Comment by carlossanlop** [comment]
Also, please let us know which specific .NET version you're using to generate the package on the first OS and then to unpack it on the second OS.

**Comment by llali** [comment]
here's the stack trace    at System.IO.Compression.Inflater.Inflate(FlushCode flushCode) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 315
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 281
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 125
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 102
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 269
   at System.IO.Compression.DeflateStream.Read(Byte[] buffer, Int32 offset, Int32 count) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 239
   at System.IO.Packaging.ZipWrappingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 70

**Comment by llali** [comment]
I'm not sure if that helps or not but this only happens for the file inside the package that is 4MB

**Comment by ssreerama** [comment]
Adding to Leila's info, We also have a customer's bacpac file that reproduces the error on a particular .BCP file, but the size of the bacpac is 12GB, please let me know if that would help.

**Comment by ericstj** [comment]
If you'd like us to have a look at this we'll need to see a repro.  The information shared here is not enough to investigate.  It looks like you're @ Microsoft - you can reach out to Carlos and myself about this if it's still blocking.

**Comment by ssreerama** [comment]
We have not been able to reproduce the issue on Ubuntu 22.04, and the customer has not encountered it on this platform either. The error is occurring on a CentOS distribution, which we have not yet tested. We have requested the customer to update to the latest version of .NET 8.0, as a recent fix related to compression issues was released. We are currently awaiting the customer’s response on the testing, as they are unable to update immediately due to dependencies with other applications. Thanks

**Comment by rokonec** [comment]
@ssreerama Please let us know if this is still an issue.

**Comment by ssreerama** [comment]
Hey @rokonec , We weren’t able to reproduce the issue, and the customer hasn’t responded after that. I think it’s reasonable to go ahead and close it.
