### ISSUE TITLE
System.ArgumentOutOfRangeException: Count cannot be less than zero. Parameter name: count

### ISSUE THREAD

**Issue by HareeshvareU** [dotnet/runtime#101600]
We have a app hosted in AWS and we get this exception in our database once a while bringing the application down. A simple restart of the services makes it work again. This issue has been flagged in Github at multiple places but there is no resolution or root cause for this . Can someone please help here. 

Stack trace is below:
Exception 
ArgumentOutOfRangeException 
StackTrace 
at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count) at System.IO.StreamWriter.Write(String value) at System.IO.TextWriter.SyncTextWriter.Write(String value) at System.Diagnostics.TextWriterTraceListener.Write(String message) at System.Diagnostics.TraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id) at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message) at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args) at System.Web.Http.Tracing.SystemDiagnosticsTraceWriter.TraceMessage(TraceLevel level, String message) at System.Web.Http.Tracing.SystemDiagnosticsTraceWriter.Trace(HttpRequestMessage request, String category, TraceLevel level, Action`1 traceAction) at System.Web.Http.Tracing.ITraceWriterExtensions.TraceError(ITraceWriter traceWriter, Exception exception, HttpRequestMessage request, String category, String operatorName, String operationName, Action`1 errorTrace) at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()

**Comment by tarekgh** [comment]
This is seems Sysstem.IO issue. Here is a readable stack:

```
at System.String.CopyTo(Int32 sourceIndex, Char[] destination, Int32 destinationIndex, Int32 count) 
at System.IO.StreamWriter.Write(String value) 
at System.IO.TextWriter.SyncTextWriter.Write(String value) 
at System.Diagnostics.TextWriterTraceListener.Write(String message) 
at System.Diagnostics.TraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id) 
at System.Diagnostics.TraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message) 
at System.Diagnostics.TraceInternal.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args) 
at System.Web.Http.Tracing.SystemDiagnosticsTraceWriter.TraceMessage(TraceLevel level, String message) 
at System.Web.Http.Tracing.SystemDiagnosticsTraceWriter.Trace(HttpRequestMessage request, String category, TraceLevel level, Action1 traceAction) 
at System.Web.Http.Tracing.ITraceWriterExtensions.TraceError(ITraceWriter traceWriter, Exception exception, HttpRequestMessage request, String category, String operatorName, String operationName, Action1 errorTrace) 
at System.Web.Http.Tracing.ITraceWriterExtensions.d__24.MoveNext() --- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Web.Http.Owin.HttpMessageHandlerAdapter.d__13.MoveNext()
```

The string that trying to write to the stream is originally created by a call like `string.Create(CultureInfo.InvariantCulture, stackalloc char[256], $"{source} {eventType}: {id} : ")` https://source.dot.net/#System.Diagnostics.TraceSource/System/Diagnostics/TraceListener.cs,384 which I am not sure if this is what causes the problem?

**Comment by stephentoub** [comment]
The original poster cited running on .NET Framework 4.8.

**Comment by tarekgh** [comment]
@stephentoub good point. 

on netfx, the string is created normally using `String.Format(CultureInfo.InvariantCulture, "{0} {1}: {2} : ", source, eventType.ToString(), id.ToString(CultureInfo.InvariantCulture))` https://referencesource.microsoft.com/#System/compmod/system/diagnostics/TraceListener.cs,404. 

The code will throw in the line https://referencesource.microsoft.com/#mscorlib/system/io/streamwriter.cs,437 which has assert statement in the previous line suggesting what the problem could be: `Contract.Assert(n > 0, "StreamWriter::Write(String) isn't making progress!  This is most likely a race condition in user code.");`

**Comment by danmoseley** [comment]
Is there another thread which doesn't go through the wrapper?

**Comment by bilby91** [comment]
We had a very similar incident today.

We created a bunch of indexes and 10 minutes later the application started failing with this exception. We are uncertain if it could be related to the index creation operation but the timing was very suspicious. We are running .NET Framework 4.8 in Azure App Services.

Stack trace looks very similar.
