### ISSUE TITLE
If Stream throws on Write, trying to close the stream throws again on Close

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#101771]
### Description

Stacktrace:

```
System.IO.IOException: The pipe is being closed.
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Cedaron.Common.Kickback.KickbackRunner.Shutdown(Boolean fastShutdown)
```

The problem is where this occurred. The code is in the unwinding `catch(Execption ex) { unwind; throw; }` block (the logical equivalent of a finally block but needs access to the exception); a normal `StreamWriter.Write()` threw the exception already; and on unwind 

### Reproduction Steps

1) Have a process created by system.diagnostics.process with standard input redirected
2) Kill the process from outside (say via task manager)
3) Have code that looks something like this:

```
    int exitcode;
    try {
        p.StandardInput.Write("Hello\r\n");
       p.WaitForExit();  // If you set this test up correctly you won't reach this line
       exitcode = p.ExitCode;
    } catch {
       p.StandardInput.Close();
       p.WaitForExit();            // This line should be reached but isn't.
       exitcode = p.ExitCode;
       p.Dispose();
    }
```

### Expected behavior

Throwing from Stream.Write() clears the buffer so that Stream.Close() doesn't try to write it *again* in unwind.

### Actual behavior

Throwing from Stream.Write() leaves junk in the buffer causing Stream.Close() to throw.

### Regression?

Yes; not sure how many versions ago. I think process.StandardInput.BaseStream wasn't always buffered.

### Known Workarounds

I have an ugly reflection mess to get the safe handle and destroy it. Looking for better.

### Configuration

Windows x64; runtime is 8.0.2 and we ship the runtime with dotnet publish.

**Comment by Jozkee** [comment]
When `p.StandardInput.Write("Hello\r\n")` throws, is the same "pipe is being closed" exception, right?

> Throwing from FileStream.Write() clears the buffer so that Stream.Close() doesn't try to write it again in unwind.

@adamsitnik @stephentoub could there be any negative implications about doing this? It's possible not all exceptions raised in Write want to clear the buffer or perform any clean-up (like calling Close()) so subsequent Close's don't fail.

> Regression?
Yes; not sure how many versions ago. I think process.StandardInput.BaseStream wasn't always buffered.

You sure about that? I see a buffer size in .NET Framework source.
https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Process.cs,2154

**Comment by jhudsoncedaron** [comment]
Whether or not it's always been buffered; in .NET Runtime 2.0 this fault didn't throw the second time. Error paths don't get tested much so the failure went unnoticed for quite awhile. I ended up having to add an extra catch block just to catch this specific exception during unwind.
