### ISSUE TITLE
System.Numerics.Tensors.Net8.Tests does not appear to actually run against .NET 8

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#101846]
As per the title, the `System.Numerics.Tensors.Net8.Tests` do not appear to currently be running against .NET 8 as intended. Instead, they are compiled for .NET 8 and appear to be running on the .NET 9 runtime via the roll forward mechanism.

This can be seen in one of the CI legs for https://github.com/dotnet/runtime/pull/101800 where the `Net8.Tests` project has the following failure:
```
System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.SpanDestinationFunctions_SpecialValues(tensorPrimitivesMethod: SpanDestinationDelegate { Method = Void ReciprocalSqrtEstimate[Single](System.ReadOnlySpan`1[System.Single], System.Span`1[System.Single]), Target = null }, expectedMethod: Func`2 { Method = Single ReciprocalSqrtEstimate(Single), Target = null }, tolerance: 0.01171875) [FAIL]
      Assert.All() Failure: 253 out of 256 items in the collection did not pass.
      [3]:   Item:  4
             Error: Assert.All() Failure: 9 out of 24 items in the collection did not pass.
                    [12]: Item:  -1.40129846E-45
                          Error: Assert.Equal() Failure: Values differ
                                 Expected: NaN
                                 Actual:   -∞
```

The actual test is comparing the result of the `TensorPrimitives.ReciprocalSqrtEstimate` function against the in-box `float.ReciprocalSqrtEstimate` API. On .NET 8, the `float` version will call into `Sse.ReciprocalSqrtScalar` which treats subnormal values as `flush-to-zero` and therefore does `1 / Sqrt(-0.0f)` which returns `-∞`, however the expected value is `NaN` indicated that the `float` version isntead called into `Avx512F.Reciprocal14SqrtScalar` which handles all non-zero negatives as properly negative and thus is doing `1 / Sqrt(nonZeroNegative)` which returns `NaN`. This highlights that it is actually running against .NET 9 and not testing what we think it should be testing.

**Comment by stephentoub** [comment]
> > As per the title, the System.Numerics.Tensors.Net8.Tests do not appear to currently be running against .NET 8 as intended. Instead, they are compiled for .NET 8 and appear to be running on the .NET 9 runtime via the roll forward mechanism.
> 
> Correct. None of the libraries tests in dotnet/runtime run against a previous version of .NETCoreApp: #54639
> 
> We only test the NetCoreAppCurrent and NetFrameworkCurrent/NetFrameworkMinimum TFMs via tests. That's a known gap that we never had resources to close.

Ok, so this project is using the .NET 8 build of SNT (and thus exercising .NET 8 code paths in the assembly) but running on .NET 9?

**Comment by tannergooding** [comment]
That's what it looks like to me.

Hence the issue is that the `System.Numerics.Tensors v8.0` tests expects `ReciprocalSqrtEstimate` to behave one way (doesn't use AVX512) but `System.Private.Corelib v9` does it a different way (does use AVX512). Leading the tests to fail since they can't compare the `TensorPrimitives` results against the scalar (float) results.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240514.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674625&view=ms.vss-test-web.build-test-results-tab&runId=16724110&resultId=175546&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
net9.0-linux-Release-x64-jitstress1_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.151808769
            Actual:   0.25312683
[4]: Item:  5
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.253379166
            Actual:   0.138663024
[5]: Item:  6
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.344092488
            Actual:   -0.0114496415
[6]: Item:  7
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.410494238
            Actual:   -0.248638168
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240515.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676046&view=ms.vss-test-web.build-test-results-tab&runId=16758734&resultId=193023&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-tailcallstress-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-jitminopts-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-jitstress2_tiered-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-jitstress1-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-jitstress2-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-disabler2r-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
net9.0-linux-Release-arm-jitstress1_tiered-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength
    - System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.NameConstraintViolation_InvalidGeneralNames
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: InvalidBasicConstraints
Actual:   NotTimeValid | InvalidBasicConstraints
```

**Stack trace:**
```
   at System.Security.Cryptography.X509Certificates.Tests.DynamicChainTests.BasicConstraints_ExceedMaximumPathLength() in /_/src/libraries/System.Security.Cryptography/tests/X509Certificates/DynamicChainTests.cs:line 251
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by stephentoub** [comment]
@v-wenyuxu, that last failure doesn't appear to be related to this discussion. And while the one prior to that is related, it's not the same thing. Can you please open new issues for each if there's nothing else relevant open now? Thanks.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240516.4](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678186&view=ms.vss-test-web.build-test-results-tab&runId=16810164&resultId=178790&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
net9.0-linux-Release-x64-jitstress1_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.151808769
            Actual:   0.25312683
[4]: Item:  5
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.253379166
            Actual:   0.138663024
[5]: Item:  6
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.344092488
            Actual:   -0.0114496415
[6]: Item:  7
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.410494238
            Actual:   -0.248638168
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240520.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681081&view=ms.vss-test-web.build-test-results-tab&runId=16901002&resultId=188437&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
net9.0-linux-Release-x64-jitstress1_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.151808769
            Actual:   0.25312683
[4]: Item:  5
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.253379166
            Actual:   0.138663024
[5]: Item:  6
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.344092488
            Actual:   -0.0114496415
[6]: Item:  7
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.410494238
            Actual:   -0.248638168
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240521.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682386&view=ms.vss-test-web.build-test-results-tab&runId=16934482&resultId=176226&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
net9.0-linux-Release-x64-jitstress1_tiered-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
net9.0-windows-Release-x64-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.NonGenericSingleTensorPrimitivesTests.CosineSimilarity_AllLengths
    - System.Numerics.Tensors.Tests.SingleGenericTensorPrimitives.CosineSimilarity_AllLengths
```

**Error message:**
```
 Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.151808769
            Actual:   0.25312683
[4]: Item:  5
     Error: Assert.Equal() Failure: Values differ
            Expected: 0.253379166
            Actual:   0.138663024
[5]: Item:  6
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.344092488
            Actual:   -0.0114496415
[6]: Item:  7
     Error: Assert.Equal() Failure: Values differ
            Expected: -0.410494238
            Actual:   -0.248638168
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.CosineSimilarity_AllLengths() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 740
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```
