### ISSUE TITLE
Test failure: Interop/COM/NETClients/IDispatch/NETClientIDispatch/NETClientIDispatch.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#101959]
**Failed in:** [runtime-coreclr gcstress-extra 20240505.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666286&view=ms.vss-test-web.build-test-results-tab&runId=16525492&paneView=debug&resultId=112575)

**Failed tests:**
```
coreclr windows arm64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.11.Arm64.Open
    -Interop/COM/NETClients/IDispatch/NETClientIDispatch/NETClientIDispatch.cmd
```

**Error message:**
```
Assert failure(PID 2360 [0x00000938], Thread: 8484 [0x2124]): Consistency check failed: AV in clr at this callstack:

CORECLR! SafeReleasePreemp + 0x1C (0x00007ffcf8ba978c) CORECLR! RCW::ReleaseAllInterfaces + 0x84 (0x00007ffcf8cb578c)
CORECLR! RCWCleanupList::ReleaseRCWListRaw + 0x170 (0x00007ffcf8cb5a70) CORECLR! RCWCleanupList::CleanupAllWrappers + 0x220 (0x00007ffcf8cb1708)
CORECLR! SyncBlockCache::CleanupSyncBlocks + 0x2C0 (0x00007ffcf8af14c0) CORECLR! Thread::DoExtraWorkForFinalizer + 0xE4 (0x00007ffcf8afb3ec)
CORECLR! FinalizerThread::FinalizerThreadWorker + 0x6B4 (0x00007ffcf8b84534) CORECLR! ManagedThreadBase_DispatchMiddle + 0x9C (0x00007ffcf8afee0c)
CORECLR! ManagedThreadBase_DispatchOuter'::11'::__Body::Run + 0x28 (0x00007ffcf8b00858) CORECLR! ManagedThreadBase_DispatchOuter + 0xB4 (0x00007ffcf8afeeec)
CORECLR! ManagedThreadBase::FinalizerBase + 0x20 (0x00007ffcf8afc158) CORECLR! FinalizerThread::FinalizerThreadStart + 0x18C (0x00007ffcf8b83bdc)
KERNEL32! BaseThreadInitThunk + 0x30 (0x00007ffd53fa2310) NTDLL! RtlUserThreadStart + 0x3C (0x00007ffd5561578c)

.AV on tid=0x2124 (8484), cxr=000000F8378FF280, exr=000000F8378FF610
FAILED: false


CORECLR! CHECK::Trigger + 0x1BC (0x00007ffcf8db38cc) CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x22C (0x00007ffcf8a3147c)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007ffcf8a3104c) CORECLR! CLRVectoredExceptionHandler + 0x188 (0x00007ffcf8a30fd0)
CORECLR! CLRVectoredExceptionHandlerShim + 0x22C (0x00007ffcf8a3176c) NTDLL! RtlTimeToSecondsSince1970 + 0x1A8 (0x00007ffd55636818)
NTDLL! RtlRaiseException + 0x198 (0x00007ffd55622218) NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ffd555b2764)
CORECLR! SafeReleasePreemp + 0x1C (0x00007ffcf8ba978c) CORECLR! RCW::ReleaseAllInterfaces + 0x84 (0x00007ffcf8cb578c)
File: D:_work1ssrccoreclrmexcep.cpp:7131
Image: C:hw9B7808FApcorerun.exe


Return code:      1
Raw output file:      C:hw9B7808FAwACAE096EuploadsCOMNETClientsIDispatchNETClientIDispatchoutput.txt
Raw output:
BEGIN EXECUTION
"C:hw9B7808FApcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  NETClientIDispatch.dll
Calling DoubleNumeric_ReturnByRef ...
Call to DoubleNumeric_ReturnByRef complete
Calling Add_Float_ReturnAndUpdateByRef ...
Call to Add_Float_ReturnAndUpdateByRef complete: 0.1 + 0.2 = 0.3; 0.3 == 0.3
Calling Add_Double_ReturnAndUpdateByRef ...
Call to Add_Double_ReturnAndUpdateByRef complete: 0.1 + 0.2 = 0.30000000000000004; 0.30000000000000004 == 0.30000000000000004
Calling TriggerException with Disp 127...
Calling TriggerException with HResult 127...
Calling TriggerException (PreserveSig) with Int 127...
Calling TriggerException (PreserveSig, ValueType) with Int 127...
IDispatch with structs not supported...
Calling GetEnumerator ...
Calling ExplicitGetEnumerator ...
Calling ReturnToManaged ...
Converting VT_EMPTY to int should be supported.
Converting VT_I2 to int should be supported.
Converting VT_I4 to int should be supported.
Converting VT_R4 to int should be supported.
Converting VT_R8 to int should be supported.
Converting VT_CY to int should be supported.
Converting VT_DATE to int should be supported.
Converting VT_BSTR to int should be supported.
Converting VT_ERROR to int should be supported.
Converting VT_BOOL to int should be supported.
Converting VT_DECIMAL to int should be supported.
Invalid variant type should throw InvalidOleVariantTypeException.
Converting from VT_ERROR with DISP_E_PARAMNOTFOUND should be rejected.
Converting int to VT_MISSING should be rejected.
Converting int to VT_NULL should be rejected.
Converting VT_UNKNOWN to int should fail from VariantChangeTypeEx.
Converting VT_NULL to int should fail from VariantChangeTypeEx.
VARIANT_BOOL should convert to non-numeric string.
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump f
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor221|25_222(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by huoyaoyuan** [comment]
@AaronRobinsonMSFT is this same to #101898 ?

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT is this same to #101898 ?

Yes.
