### ISSUE TITLE
Test failure ilverify\\ILVerificationTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#101900]
**Failed in:** [runtime-coreclr jitstress-random 20240505.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666195&view=ms.vss-test-web.build-test-results-tab&runId=16524308&resultId=100194&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - ilverify\\ILVerificationTests.cmd
    - GC\\API\\GC\\CollectionCountTest\\CollectionCountTest.cmd
    - GC\\API\\GC\\Finalize\\Finalize.cmd
    - GC\\API\\WeakReference\\IsAlive_neg\\IsAlive_neg.cmd
    - GC\\Scenarios\\LeakGen\\leakgenthrd\\leakgenthrd.cmd
    - GC\\Scenarios\\Boxing\\variantlinklist\\variantlinklist.cmd
    - ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd
```

**Error message:**
```
 
Assert failure(PID 7500 [0x00001d4c], Thread: 5624 [0x15f8]): Assertion failed 'firstILBlock->hasProfileWeight()' in 'Internal.TypeSystem.TypeSystemContext+FieldForInstantiatedTypeKey+FieldForInstantiatedTypeKeyHashtable:.ctor():this' during 'Compute block weights' (IL size 7; hash 0x60deda92; MinOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fgprofile.cpp:4544
    Image: C:\h\w\A3C608B7\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A3C608B7\w\BE110A66\uploads\Reports\ilverify\ILVerificationTests.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A3C608B7\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ILVerificationTests.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/5/2024 7:48:43 PM
Processing C:\cores\corerun.exe.7500.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A3C608B7\p
> C:\h\w\A3C608B7\w\BE110A66\e\ilverify\ILVerificationTests.cmd
```

**Stack trace:**
```
   at ilverify._ILVerificationTests_._ILVerificationTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
dup with [#101901](https://github.com/dotnet/runtime/issues/101901)
