### ISSUE TITLE
Test failure GC\\API\\GCHandle\\AddrOfPinnedObject_neg\\AddrOfPinnedObject_neg.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#101901]
**Failed in:** [runtime-coreclr jitstress-random 20240505.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666195&view=ms.vss-test-web.build-test-results-tab&runId=16524308&resultId=100140&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - GC\\API\\GCHandle\\AddrOfPinnedObject_neg\\AddrOfPinnedObject_neg.cmd
```

**Error message:**
```
 
Assert failure(PID 7540 [0x00001d74], Thread: 5096 [0x13e8]): Assertion failed 'firstILBlock->hasProfileWeight()' in 'Test_AddrOfPinnedObject_neg:Main():int' during 'Compute block weights' (IL size 192; hash 0x4ec04431; Tier0-MinOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fgprofile.cpp:4544
    Image: C:\h\w\A3C608B7\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A3C608B7\w\A7BA08D7\uploads\Reports\GC.API\GCHandle\AddrOfPinnedObject_neg\AddrOfPinnedObject_neg.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A3C608B7\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  AddrOfPinnedObject_neg.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/5/2024 7:49:19 PM
Processing C:\cores\corerun.exe.7540.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A3C608B7\p
> C:\h\w\A3C608B7\w\A7BA08D7\e\GC\API\GCHandle\AddrOfPinnedObject_neg\AddrOfPinnedObject_neg.cmd
```

**Stack trace:**
```
   at GC_API._GCHandle_AddrOfPinnedObject_neg_AddrOfPinnedObject_neg_._GCHandle_AddrOfPinnedObject_neg_AddrOfPinnedObject_neg_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by AndyAyersMS** [comment]
Thought I had fixed all these, but evidently not.
