### ISSUE TITLE
Test failure: Loader/classloader/RefFields/Validate/Validate.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#101964]
**Failed in:** [runtime-coreclr r2r-extra 20240505.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666362&view=ms.vss-test-web.build-test-results-tab&runId=16528098&resultId=107172&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
    -Loader/classloader/RefFields/Validate/Validate.cmd
```

**Error message:**
```
Assert failure(PID 4396 [0x0000112c], Thread: 5192 [0x1448]): Assertion failed 'InlineeCompiler->fgFirstBB->bbWeight == 0' in 'Xunit.Assert:Throws[System.__Canon](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666362&view=ms.vss-test-web.build-test-results-tab&runId=16528098&paneView=debug&resultId=107172):System.__Canon' during 'Morph - Inlining' (IL size 32; hash 0x2c2a1269; FullOpts)


File: D:_work1ssrccoreclrjitginline.cpp:1754
Image: C:hwB22409E6pcorerun.exe

Return code:      1
Raw output file:      C:hwB22409E6wA8FC0917uploadsclassloaderRefFieldsValidateoutput.txt
Raw output:
BEGIN EXECUTION
InvalidCSharp.dll
TestLibrary.dll
Validate.dll
3 file(s) copied.
4:31:53.41
Response file: C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateInvalidCSharp.dll.rsp
C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateIL-CG2InvalidCSharp.dll
-o:C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateInvalidCSharp.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwB22409E6pSystem..dll
-r:C:hwB22409E6pMicrosoft..dll
-r:C:hwB22409E6p\xunit..dll
-r:C:hwB22409E6pmscorlib.dll
-r:C:hwB22409E6p
etstandard.dll
" "dotnet" "C:hwB22409E6pcrossgen2crossgen2.dll" @"C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateInvalidCSharp.dll.rsp"   -r:C:hwB22409E6wA8FC0917eLoaderLoaderIL-CG2.dll  -r:C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateIL-CG2*.dll"
Emitting R2R PE file: C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateInvalidCSharp.dll
" "dotnet" "C:hwB22409E6p
2rdump
2rdump.dll" --header --sc --in C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateInvalidCSharp.dll --out C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateInvalidCSharp.dll.r2rdump --val"
4:31:55.25
4:31:55.25
Response file: C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateTestLibrary.dll.rsp
C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateIL-CG2TestLibrary.dll
-o:C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateTestLibrary.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwB22409E6pSystem..dll
-r:C:hwB22409E6pMicrosoft..dll
-r:C:hwB22409E6p\xunit..dll
-r:C:hwB22409E6pmscorlib.dll
-r:C:hwB22409E6p
etstandard.dll
" "dotnet" "C:hwB22409E6pcrossgen2crossgen2.dll" @"C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateTestLibrary.dll.rsp"   -r:C:hwB22409E6wA8FC0917eLoaderLoaderIL-CG2.dll  -r:C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateIL-CG2*.dll"
Emitting R2R PE file: C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateTestLibrary.dll
" "dotnet" "C:hwB22409E6p
2rdump
2rdump.dll" --header --sc --in C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateTestLibrary.dll --out C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateTestLibrary.dll.r2rdump --val"
4:31:57.47
4:31:57.47
Response file: C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateValidate.dll.rsp
C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateIL-CG2Validate.dll
-o:C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateValidate.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwB22409E6pSystem..dll
-r:C:hwB22409E6pMicrosoft..dll
-r:C:hwB22409E6p\xunit..dll
-r:C:hwB22409E6pmscorlib.dll
-r:C:hwB22409E6p
etstandard.dll
" "dotnet" "C:hwB22409E6pcrossgen2crossgen2.dll" @"C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateValidate.dll.rsp"   -r:C:hwB22409E6wA8FC0917eLoaderLoaderIL-CG2.dll  -r:C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateIL-CG2*.dll"
Emitting R2R PE file: C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateValidate.dll
" "dotnet" "C:hwB22409E6p
2rdump
2rdump.dll" --header --sc --in C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateValidate.dll --out C:hwB22409E6wA8FC0917eLoaderclassloaderRefFieldsValidateValidate.dll.r2rdump --val"
4:31:59.41
"C:hwB22409E6pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Vali
```

**Stack trace:**
```
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor185|0_186(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by AndyAyersMS** [comment]
Hopefully fixed by https://github.com/dotnet/runtime/pull/101925.

**Comment by AndyAyersMS** [comment]
I kicked off a new runtime-coreclr r2r-extra pipeline run ... indeed this is fixed.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=668348&view=results
