### ISSUE TITLE
System.Buffers.Tests timeout on wasm MT

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#102040]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=670159
Build error leg or test failing: WasmTestOnChrome-MT-System.Buffers.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/102029

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests", "Tests timed out. Killing driver service pid"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=670159
**Error message validated:** `[System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests Tests timed out. Killing driver service pid`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/9/2024 7:17:48 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment]
last few [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100675-merge-7b9737d2580e434cb9/WasmTestOnFirefox-MT-System.Buffers.Tests/1/console.b7e078e9.log?helixlogtype=result) [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-7918b4b30eb3431ea0/WasmTestOnChrome-MT-System.Buffers.Tests/1/console.73413c74.log?helixlogtype=result) are caused by OOM
```
[17:15:33] info: [FAIL] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentAndReturnManyOfTheSameSize_NoneAreSame(pool: ConfigurableArrayPool`1 { })
[17:15:33] info: System.OutOfMemoryException : Out of memory
[17:15:33] info:    at System.Buffers.ConfigurableArrayPool`1.Bucket[[System.Byte, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Rent()
[17:15:33] info:    at System.Buffers.ConfigurableArrayPool`1[[System.Byte, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Rent(Int32 minimumLength)
[17:15:33] info:    at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentAndReturnManyOfTheSameSize_NoneAreSame(ArrayPool`1 pool) in /_/src/libraries/System.Runtime/tests/System.Buffers.Tests/ArrayPool/UnitTests.cs:line 551
[17:15:33] info:    at System.Object.InvokeStub_ArrayPoolUnitTests.RentAndReturnManyOfTheSameSize_NoneAreSame(Object , Span`1 )
[17:15:33] info:    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by ilonatommy** [comment]
Looks like https://github.com/dotnet/runtime/pull/105246 fixed it

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ilonatommy** [comment]
Sorry, it's `disabled-test`, reopening
