### ISSUE TITLE
[browser][MT] System.Buffers.ArrayPool.Tests - Could not allocate

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#102195]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100141-merge-2bc80070eae34fc693/WasmTestOnChrome-MT-System.Buffers.Tests/1/console.77eace3e.log?helixlogtype=result)
```
[11:40:08] info: Test collection for System.Buffers.ArrayPool.Tests.CollectionTests
[11:40:08] info: [IGNORED] System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure
[11:40:08] info: System.Buffers.ArrayPool.Tests.CollectionTests 0 ms
[11:40:08] fail: [0x012251a0-dpty 11:40:08.951] [MONO] Could not allocate 131072 (1 * 131072) bytes
                 Error
                     at tu (http://127.0.0.1:40487/_framework/dotnet.runtime.js:3:199931)
                     at wasm_trace_logger (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[197]:0x155ad)
                     at eglib_log_adapter (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[697]:0x4e9fc)
                     at monoeg_g_logv_nofree (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[615]:0x4c119)
                     at monoeg_g_log (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[617]:0x4c1dc)
                     at monoeg_g_calloc (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[607]:0x4bf7c)
                     at monoeg_malloc0 (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[608]:0x4bf96)
                     at rehash_table (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[2198]:0xbd6b5)
                     at mono_conc_hashtable_insert (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[2199]:0xbd81d)
                     at mono_metadata_lookup_generic_class (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[2455]:0xd146e)
                     at inflate_generic_type (http://127.0.0.1:40487/_framework/dotnet.native.wasm:wasm-function[1235]:0x7313a)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=674731
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[MONO] Could not allocate",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=674731
**Error message validated:** `[[MONO] Could not allocate`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/14/2024 1:43:54 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment]
cc @kg

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100334-merge-8e2c5d2ead2d4ca980/WasmTestOnFirefox-MT-System.Buffers.Tests/1/console.478c8ec4.log?helixlogtype=result)
```
[13:20:43] info: [STRT] System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure
[13:20:43] info: [IGNORED] System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure
[13:20:43] info: System.Buffers.ArrayPool.Tests.CollectionTests 0 ms

[13:20:43] fail: [0x000fb778--UI- 13:20:43.300] MONO_WASM: Out of memory
                    at System.IO.MemoryStream.set_Capacity(Int32 value)
                    at System.IO.MemoryStream.EnsureCapacity(Int32 value)
                    at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
                    at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
                    at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
                    at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
                    at System.Xml.XmlUtf8RawTextWriterIndent.WriteString(String text)
                    at System.Xml.XmlWellFormedWriter.WriteString(String text)
                    at System.Xml.XmlWriter.WriteAttributeString(String prefix, String localName, String ns, String value)
                    at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e)
                    at System.Xml.Linq.ElementWriter.WriteElement(XElement e)
                    at System.Xml.Linq.XElement.WriteTo(XmlWriter writer)
                    at System.Xml.Linq.XElement.Save(XmlWriter writer)
                    at System.Xml.Linq.XElement.Save(Stream stream, SaveOptions options)
                    at System.Xml.Linq.XElement.Save(Stream stream)
                    at Microsoft.DotNet.XHarness.TestRunners.Xunit.WasmXmlResultWriter.WriteOnSingleLine(XElement assembliesElement)
                    at Microsoft.DotNet.XHarness.TestRunners.Xunit.WasmThreadedTestRunner.WriteResultsToFile(TextWriter writer, XmlResultJargon jargon)
                    at Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationEntryPoint.WriteResults(TestRunner runner, ApplicationOptions options, LogWriter logger, TextWriter writer)
                    at Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationEntryPoint.InternalRunAsync(ApplicationOptions options, TextWriter loggerWriter, TextWriter resultsFile)
                    at Microsoft.DotNet.XHarness.TestRunners.Common.WasmApplicationEntryPointBase.RunAsync()
                    at Microsoft.DotNet.XHarness.TestRunners.Xunit.WasmApplicationEntryPoint.Run()
                    at WasmTestRunner.Main(String[] args)
                 ManagedError@http://127.0.0.1:44247/_framework/dotnet.runtime.js:3:37234
                 an@http://127.0.0.1:44247/_framework/dotnet.runtime.js:3:27033
                 on/<@http://127.0.0.1:44247/_framework/dotnet.runtime.js:3:26589
                 Dl</</<@http://127.0.0.1:44247/_framework/dotnet.runtime.js:3:197717
                 Dl</<@http://127.0.0.1:44247/_framework/dotnet.runtime.js:3:197845
                 callUserCallback@http://127.0.0.1:44247/_framework/dotnet.native.js:8:98666
                 createDotnetRuntime/safeSetTimeout/createDotnetRuntime<@http://127.0.0.1:44247/_framework/dotnet.native.js:8:106269
JavaScript error: http://127.0.0.1:44247/_framework/dotnet.runtime.js, line 3: Error: Out of memory
[13:20:43] info: WASM EXIT 1
```

**Comment by mkhamoyan** [comment]
@pavelsavara, this issue has not been hit for over a month. Should we consider closing it?

**Comment by pavelsavara** [comment]
I disabled the most difficult test in https://github.com/dotnet/runtime/pull/105246 and that probably helped. Closing.
