### ISSUE TITLE
JIT: Assertion failed '(genRegMask(initReg) & intRegState.rsCalleeRegArgMaskLiveIn) == 0' in win-x86

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#102161]
Failing in win-x86 jitstress runs

Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=673226&view=results
Example console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-b9d10774a0ca480a82/Interop/1/console.174f035c.log?helixlogtype=result

This looks related to some of my recent changes.

cc @dotnet/jit-contrib

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr gcstress-extra 20240512.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673163&view=ms.vss-test-web.build-test-results-tab&runId=16687470&resultId=121348&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open
    - Interop/PInvoke/CriticalHandles/StructTest/StructTest/StructTest.cmd
coreclr windows x86 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open
    - Interop/PInvoke/CriticalHandles/StructTest/StructTest/StructTest.cmd
coreclr windows x86 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
    - Interop/PInvoke/CriticalHandles/StructTest/StructTest/StructTest.cmd
```

**Error message:**
```
 
Assert failure(PID 9464 [0x000024f8], Thread: 9044 [0x2354]): Assertion failed '(genRegMask(initReg) & intRegState.rsCalleeRegArgMaskLiveIn) == 0' in '(dynamicClass):IL_STUB_PInvoke(int,byref)' during 'Generate code' (IL size 116; hash 0x99f14004; FullOpts)

    File: D:_work1ssrccoreclrjitcodegencommon.cpp:3987
    Image: C:hw9EE408D5pcorerun.exe


Return code:      1
Raw output file:      C:hw9EE408D5wA81608FAuploadsPInvokeCriticalHandlesStructTestStructTestoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hw9EE408D5pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  StructTest.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 5/12/2024 11:01:28 PM
Processing C:corescorerun.exe.9464.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hw9EE408D5		mpzaks2h.tmp" -z "C:corescorerun.exe.9464.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.9464.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hw9EE408D5pPDB
Symbol search path is: C:hw9EE408D5pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sun May 12 23:01:33.000 2024 (UTC + 0:00)
System Uptime: 0 days 3:15:19.343
Process Uptime: 0 days 0:00:04.000
...................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(24f8.2354): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=029793f8 ebx=00000000 ecx=00000000 edx=00000000 esi=029793a8 edi=029793f8
eip=71d156b1 esp=029796dc ebp=0297a774 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!FailFastOnAssert+0x21:
71d156b1 5e              pop     esi
0:000> cdb: Reading initial command '$<C:hw9EE408D5		mpzaks2h.tmp'
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: 24f8.2354 Suspend: 0 Teb: 026da000 Unfrozen
ChildEBP RetAddr  
029796e8 71d1638d coreclr!FailFastOnAssert+0x21
0297a774 718d9e48 coreclr!_DbgBreakCheck+0x337
*** WARNING: Unable to verify checksum for clrjit.dll
0297a7dc 6fbbce7e coreclr!CEEInfo::doAssert+0x68
0297c804 6fb9bc33 clrjit!assertAbort+0xd8
0297c834 6fb97115 clrjit!CodeGen::genZeroInitFrame+0x7f
0297c8b0 6fb97b2e clrjit!CodeGen::genFnProlog+0x69b
0297c8c8 6fb97a9f clrjit!CodeGen::genGeneratePrologsAndEpilogs+0x6b
0297c8d8 6fb93294 clrjit!CodeGen::genGenerateMachineCode+0x33f
0297c8e4 6fcb9d88 clrjit!CodeGenPhase::DoPhase+0x14
0297c918 6fb976c8 clrjit!Phase::Run+0x38
(Inline) -------- clrjit!DoPhase+0x45
0297c948 6fba66b2 clrjit!CodeGen::genGenerateCode+0x78
0297cbfc 6fba7cbb clrjit!Compiler::compCompile+0xb5d
0297cc64 6fba7029 clrjit!Compiler::compCompileHelper+0x702
(Inline) -------- clrjit!Compiler::compCompile::__l170::__Body::Run+0x15
0297cd50 6fba50f4 clrjit!Compiler::compCompile+0x74c
0297cd70 6fba5135 clrjit!``jitNativeCode'::`8'::__Body::
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor261|25_262(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```
