### ISSUE TITLE
[iOS] Error The Internet connection appears to be offline.

### ISSUE THREAD

**Issue by czuck** [dotnet/runtime#102163]
### Description

This error has been reported but those reports have been closed and this is an issue in 8.0.20 but I can also recreate it with 8.0.14.
When my app is not previously installed on my phone, I consistently get this error when calling HttpClient.SendAsync(_requestMessage_).  Just before this call Connectivity.NetworkAccess is checked and is set to NetworkAccess.Internet.
I will do a full rebuild and debug and repeat that process until the request is successfully returned.  Once it works, it continues to work until I delete the app from the phone, at which point the issue reappears.  It happens with both Debug and Release builds.  I have tested doing a rebuild, if works (for the first time), I delete the app from the phone, re-deploy the same build and test and it does not work.  

```
{System.Net.Http.HttpRequestException: The Internet connection appears to be offline.
 ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x3026e07e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (Local network prohibited), interface: en0[802.11], ipv4, uses wifi, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4B22EF41-B5E1-4278-8A9B-DE62658BEFB6>.<7>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <4B22EF41-B5E1-4278-8A9B-DE62658BEFB6>.<7>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=http://192.168.x.xx/m/d/ApiSettings/GetApiVersionInfo, NSErrorFailingURLKey=http://192.168.x.xx/m/d/ApiSettings/GetApiVersionInfo, _kCFStreamErrorDomainKey=1}
   --- End of inner exception stack trace ---
   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:line 544
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at JMoApp.Utilities.HttpUtilities.<GetResponseAsync>d__6`1[[JMoApp.Models.ApiVersionInfo, JMoApp, Version=2024.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\Code\My App \Utilities\HttpUtilities.cs:line 180}
```

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17.4.1

### Did you find any workaround?

keep rebuilding and debugging.

**Comment by deejcoder** [comment]
I'm getting the same issue when connecting to a range of APIs hosted through IIS within the local network (on my computer and servers within the same network). This issue is quite serious as it will prevent us publishing the iOS version of the app as users will need to connect to local networks.

In my Info.plist file I have the following:
```
<key>NSLocalNetworkUsageDescription</key>
<string>This app may need to connect to local services</string>
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
    <key>NSAllowsLocalNetworking</key>
    <true/>
</dict>
```
The connection should be encrypted with TLS 1.2, ECDHE_RSA with P-384 and AES_256_GCM. These APIs have valid signed certificates. However, this should be ignored arbitrary loads are enabled.

I am able to connect to these APIs on the device in the web browser.
I am able to connect to the same API, when it is not hosted within the same network.
I am able to connect from an old Xamarin solution.
It has only worked a few times out of about a hundred attempts (when debugging for the first time).
It works on Android and WinUI.

When it worked, it showed a popup to grant local network access.

I tried using bonjour services to consistently show the popup to grant local network access, which works, however, the connection still fails for the same reason. On the device, in settings the app has local network access.

This works fine on WinUI3 and Android.

```
Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x303567840 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns, uses wifi, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <1CF48953-E39F-4D4A-A5EE-EE1B31E48825>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <1CF48953-E39F-4D4A-A5EE-EE1B31E48825>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://api.mycompany.com/v3/Auth/Login, NSErrorFailingURLKey=https://api.mycompany.com/v3/Auth/Login, _kCFStreamErrorDomainKey=1}
```
```
   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:line 544
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MauiAppleConnectivityTests.iOS.LoginService.Login() in C:\git\radfords.visualstudio.com\MauiAppleConnectivityTests\MauiAppleConnectivityTests\MauiAppleConnectivityTests.iOS\LoginService.cs:line 102
```

Hopefully this helps a bit.

**Comment by Ni2Be** [comment]
Getting the same error with post
```csharp
            var response = await client.PostAsync(url,
                new StringContent(
                    JsonConvert.SerializeObject(item),
                    Encoding.UTF8, MediaType), cancellationToken);
```
<details>
  <summary>Versions:</summary>
  
  ```yml
 dotnet --info
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.011fccd5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.301\

.NET workloads installed:
 [android]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    34.0.95/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.95\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.1\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    8.0.21/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.21\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.205 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]
  8.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
  ```
</details>

**Comment by nickdavidbhs** [comment]
Does anyone got to solve the issue? I am facing the same issue.

In debug mode the api calls work fine.
But in release after first install is not working, the user has to close the app and reopen it, then it keeps working fine.

Version 8.0.20

**Comment by deejcoder** [comment]
I have managed to reproduce this reliably. I am not sure if this is the same as the original problem.

We have multiple solutions that reference a core nuget package.

When there are multiple solutions installed on a single iOS device, with different versions of this nuget package, then I get the error.

If I uninstall all but one of the solutions, it starts working again.

**Comment by MrZander** [comment]
I am consistently getting this error in debug and release mode.

MAUI Blazor Hybrid App
Dotnet version 8.0.302

Code causing the error:
`await client.GetStringAsync($"https://{internalApiHost}:{internalApiPort}");`
`client is an `HttpClient`

The device is on WiFi, I can access the above URL through Safari without issue.  It is a local server hosted on-prem, same network as the device.

**Comment by MrZander** [comment]
I'm running into this and cannot get past it.
It is only happening once deployed, testing it through TestFlight.

I can build the app in release mode with a developer provisioning profile, and it connects fine, but once I deploy it through the app store, it gives me "The Internet connection appears to be offline."

I am trying to connect to a local resource on the same network, which is using a self-signed TLS certificate (using `ServerCertificateCustomValidationCallback` to validate it manually).  
I can connect to our service fine through Safari, but not my app when deployed.

I've tried adding:
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
```
to Info.plist and using `NSUrlSessionHandler.TrustOverrideForUrl` to manually approve the URL, but neither have helped.

dotnet --version `8.0.302`

If anyone has any insight, it would be greatly appreciated.  This is blocking my ability to publish the app and I am out of debugging ideas.

**Comment by deejcoder** [comment]
> I'm running into this and cannot get past it.
> It is only happening once deployed, testing it through TestFlight.
> 
> I can build the app in release mode with a developer provisioning profile, and it connects fine, but once I deploy it through the app store, it gives me "The Internet connection appears to be offline."
> 
> I am trying to connect to a local resource on the same network, which is using a self-signed TLS certificate (using `ServerCertificateCustomValidationCallback` to validate it manually).  
> I can connect to our service fine through Safari, but not my app when deployed.
> 
> I've tried adding:
> ```
> 	<key>NSAppTransportSecurity</key>
> 	<dict>
> 		<key>NSAllowsLocalNetworking</key>
> 		<true/>
> 	</dict>
> ```
> to Info.plist and using `NSUrlSessionHandler.TrustOverrideForUrl` to manually approve the URL, but neither have helped.
> 
> dotnet --version `8.0.302`
> 
> If anyone has any insight, it would be greatly appreciated.  This is blocking my ability to publish the app and I am out of debugging ideas.

Hi MrXander,

Have you tried removing NSAllowsLocalNetworking and instead adding NSAllowsArbitraryLoads? Doing this, will disable the ATS security restrictions, which is not recommended, however is required if your network service does not meet them. You can read more here: https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads

Even with ATS turned off I believe you will still be prompted to grant permission to access local networks, if all is working as expected.

**Comment by MrZander** [comment]
@deejcoder I get the same error message with `NSAllowsArbitraryLoads`, but I only have one MAUI app installed.

**Comment by MrZander** [comment]
It started working after I rebooted my device.  I have no idea why, one of the most frustrating problems I've ever debugged.

My info.plist has only `NSAllowsLocalNetworking` set to `true`

**Comment by AngeloLazzari** [comment]
Does anyone solved this one? I have still getting this error when debugging in local with a real Ipad. I am using a .NET 9 MAUI app.

**Comment by mattleibow** [comment]
What is the urls you are trying to access? When this error occurs, can you access the url in safari?

**Comment by mjanzetic** [comment]
I've updated my [sample repo](https://github.com/mjanzetic/MauiRestClient/tree/main) to also contain a web service. It can be accessed by '<host ip>:5192/test' and will answer all requests methods with 200 OK.
Accessing it via a browser, e.g. Safari, works as well.
In the sample app it now works, although I'm running it on a different device (iOS 18.2.1) and upgraded the app to .NET 9.

**Comment by yedi97** [comment]
i have this problem since installing firebase message

**Comment by BrzVlad** [comment]
We don't have enough information to go on in order to investigate this issue. The repro project that was provided seems to be working now with latest release. If anybody has a project reproducing this issue, please share it here.
