### ISSUE TITLE
AccessViolationException in HttpClient.SendAsync() on macOS arm64 in .NET 9 preview.4

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#102313]
### Description

I have an application I'm testing against .NET 9 daily builds. With the latest SDK and package versions I'm seeing `System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.` errors in my tests when running on GitHub Actions' macOS arm64 runners.

I have 9 applications I'm doing this with, but I'm only observing this issue with one of them.

### Reproduction Steps

1. Clone https://github.com/martincostello/costellobot/pull/1078/commits/18966b86239e57c468633695a1843894af31eeea
2. Run `build.ps1` on a macOS arm64 machine.

### Expected behavior

The tests all pass.

### Actual behavior

Lots of test failures with a stack trace similar to the below:

```
System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MartinCostello.Costellobot.Infrastructure.IntegrationTests`1.PostWebhookAsync(String event, Object value, String webhookSecret, String delivery) in /_/tests/Costellobot.Tests/Infrastructure/IntegrationTests`1.cs:line 176
   at MartinCostello.Costellobot.Handlers.DeploymentStatusHandlerTests.PostWebhookAsync(DeploymentStatusDriver driver, String action) in /_/tests/Costellobot.Tests/Handlers/DeploymentStatusHandlerTests.cs:line 667
   at MartinCostello.Costellobot.Handlers.DeploymentStatusHandlerTests.Deployment_Is_Approved_For_Trusted_User_And_Dependency_When_Penultimate_Build_Skipped() in /_/tests/Costellobot.Tests/Handlers/DeploymentStatusHandlerTests.cs:line 128
--- End of stack trace from previous location ---
```

That corresponds to this code, but it doesn't appear to have been recently changed:

https://github.com/dotnet/runtime/blob/8f3c687784a33aafe642368c28492244fa2f2c7f/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L520-L556

### Regression?

Yes.

### Known Workarounds

None.

### Configuration

.NET SDK `9.0.100-preview.4.24265.4`

**Comment by antonfirsov** [comment]
@martincostello any chance you can help us by [collecting traces](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/telemetry/events#dotnet-trace)? This could give us some preliminary ideas before someone manages to jump on the issue.

```
dotnet-trace collect --providers System.Net.Http,Private.InternalDiagnostics.System.Net.Http,System.Net.Security,System.Net.Sockets,System.Net.NameResolution,System.Threading.Tasks.TplEventSource:0x80:4 --process-id <PID>
```

**Comment by antonfirsov** [comment]
Could [this](https://github.com/dotnet/runtime/issues/101479#issuecomment-2095641144) be the root cause?

**Comment by martincostello** [comment]
> any chance you can help us by [collecting traces](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/telemetry/events#dotnet-trace)?

Sure, I'll try and do this later today.

> Could https://github.com/dotnet/runtime/issues/101479#issuecomment-2095641144 be the root cause?

I did spot that issue, but it _seemed_ a bit too old to still be an issue in the nightlies?

**Comment by martincostello** [comment]
> ```
> dotnet-trace collect --providers System.Net.Http,Private.InternalDiagnostics.System.Net.Http,System.Net.Security,System.Net.Sockets,System.Net.NameResolution,System.Threading.Tasks.TplEventSource:0x80:4 --process-id <PID>
> ```

Just looked at this - how do I do this exactly when I don't know what the test process' ID will be until after I start the tests?

**Comment by martincostello** [comment]
At the moment my repro is just "run dotnet test" - I don't have anything more specific at the moment.

I could maybe add something to the tests to have the tests start monitor itself (if that works?)

I'm only seeing this on macOS, not Windows or Linux, but only in this one project. I'm not specifically using lib2gitsharp anywhere, and if it is being used, I would assume it's from an SDK or something and would/should be present in my other repos I'm testing nightlies with.

**Comment by martincostello** [comment]
If it helps narrow the search, this has started happening at [some point since the 24th April](https://github.com/martincostello/costellobot/actions/workflows/build.yml?query=branch%3Adotnet-nightly), but all I had to go on was "dotnet test crashes" at that point and I figured it would stabilise at some point. It's only in the last day or so I've noticed it's progressed to not killing the whole process and giving me an exception message and stack trace.

**Comment by martincostello** [comment]
_But_ that probably correlates more with GitHub Actions runners moving from macOS 12 x64 to macOS 14 arm64, so it was probably broken before then and my build was just on a different arch so I didnt see it before...

**Comment by martincostello** [comment]
I don't seem to be able to get hold of a `.netrace` file as now dotnet test is just crashing again. I do have a dump file, but it's ~1.3GB zipped and will contain secrets from my repository that are configured in environment variables.

If you let me know what the right secure process to provide the dump file is, I can provide one tomorrow.

**Comment by martincostello** [comment]
I'm _possibly_ seeing this issue in a different repository using the official preview.4 build as well: [logs](https://github.com/martincostello/dotnet-bumper/actions/runs/9179506490/job/25242278338?pr=292#step:6:45).

In that case, dotnet test is just outright crashing, rather than throwing an `AccessViolationException`.

**Comment by martincostello** [comment]
Yep, definitely an issue with the official .NET 9 preview.4 build: [crash](https://github.com/martincostello/costellobot/actions/runs/9187650118/job/25266197826#step:10:97)

**Comment by martincostello** [comment]
I've also spotted that sometimes instead of crashing, I get this instead:

```console
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at MartinCostello.DotNetBumper.Bumper.RunAsync(IAnsiConsole console, String[] args, Func`2 configureLogging, CancellationToken cancellationToken) in /_/src/DotNetBumper/Bumper.cs:line 98
   at MartinCostello.DotNetBumper.EndToEndTests.Application_Returns_Two_If_Cancelled_By_User() in /_/tests/DotNetBumper.Tests/EndToEndTests.cs:line 425
--- End of stack trace from previous location ---
```

That appears to come from here: [ExecuteMethodConvention.InvokeAsync()](https://github.com/natemcmaster/CommandLineUtils/blob/d463a5c251f58dc6b3ae0bae06c68fcc234dfb4d/src/CommandLineUtils/Conventions/ExecuteMethodConvention.cs#L83)

**Comment by antonfirsov** [comment]
> I've also spotted that sometimes instead of crashing, I get this instead

We don't own McMaster CommandLine utilities. We should focus on the `HttpClient` AV/crash in this issue.

It would be very helpful for us if there were crash dumps or if you could do some experiments that can help deciding whether we can exclude libgit2sharp or other 3rd party components as sources of memory corruption. Ideally there should be a repro that only uses HttpClient.

**Comment by martincostello** [comment]
@antonfirsov I have a crash dump - I just need to know how to securely give it to you: https://github.com/dotnet/runtime/issues/102313#issuecomment-2116222427

**Comment by antonfirsov** [comment]
Sorry, I missed that. Can you send it over email? (anfirszo at companydomain).

**Comment by martincostello** [comment]
@antonfirsov The dump is 1.4GB compressed. Is there a secure file share to upload it to instead?

@danmoseley Can you point me to the appropriate feedback thing that's used for this? I forget where it is.

**Comment by martincostello** [comment]
This _seems_ to have stopped happening as of the `9.0.100-preview.5.24279.9` SDK. I still have the crash dump from the earlier build.

**Comment by antonfirsov** [comment]
> Can you point me to the appropriate feedback thing that's used for this?

There should be a way to privately attach it to tickets opened on https://developercommunity.visualstudio.com.

Alternatively, if there is a way for you to safely share it via a private link to OneDrive or similar, you can send me a link over email, I will let you know after downloading it so you can delete the share.

**Comment by martincostello** [comment]
I tried to use the feedback site, but the webpage OOMs in Chrome when I try and attach the ZIP file 😅

I'm just setting up a throw-away OneDrive share now, and I'll share it with the email address you provided earlier.

**Comment by martincostello** [comment]
@antonfirsov Just emailed you the link.

**Comment by martincostello** [comment]
A colleague of mine, @slang25, managed to capture the output of `sos pstacks` from a crash dump on a MacBook if that's useful:

```text
________________________________________________
 ~~~~ 8a5297
    1 System.Threading.Monitor.Wait(Object, Int32)
    1 System.Threading.ManualResetEventSlim.Wait(Int32, CancellationToken)
    1 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, CancellationToken)
    1 System.Threading.Tasks.Task.InternalWaitCore(Int32, CancellationToken)
    1 System.Threading.Tasks.Task.Wait(Int32, CancellationToken)
    1 System.Threading.Tasks.Task.Wait()
    1 Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary<String,String>)
    1 Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[], UiLanguageOverride)
    1 Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[])
    1 Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[])


________________________________________________
      ~~~~ 8a52aa
         1 System.Threading.WaitHandle.WaitOneNoCheck(Int32, Boolean, Object, WaitHandleWaitSourceMap)
         1 System.Threading.PortableThreadPool+GateThread.GateThreadStart()
      ~~~~ 8a52ab
         1 System.Threading.WaitHandle.WaitAnyMultiple(ReadOnlySpan<SafeWaitHandle>, Int32)
         1 System.Threading.PortableThreadPool+WaitThread.WaitThreadStart()
      ~~~~ 8a52ad
         1 System.Threading.WaitHandle.WaitOneNoCheck(Int32, Boolean, Object, WaitHandleWaitSourceMap)
         1 System.Threading.TimerQueue.TimerThread()
      ~~~~ 8a537c
         1 System.IO.FileSystemWatcher+RunningInstance+StaticWatcherRunLoopManager.WatchForFileSystemEventsThreadStart(ManualResetEventSlim, SafeEventStreamHandle)
      ~~~~ 8a52ae,8a52af
         2 Interop+Sys.WaitForSocketEvents(IntPtr, SocketEvent*, Int32*)
         2 System.Net.Sockets.SocketAsyncEngine.EventLoop()
           ~~~~ 8a5325
              1 System.Threading.Monitor.Wait(Object, Int32)
              1 System.Threading.ManualResetEventSlim.Wait(Int32, CancellationToken)
              1 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, CancellationToken)
              1 System.Threading.Tasks.Task.InternalWaitCore(Int32, CancellationToken)
              1 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)
              1 Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost)
              1 Program.<Main>$(String[])
              1 System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object, Span<Object>, BindingFlags)
           ~~~~ 8a542f
              1 System.Threading.Monitor.Wait(Object, Int32)
              1 System.Threading.ManualResetEventSlim.Wait(Int32, CancellationToken)
              1 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, CancellationToken)
              1 System.Threading.Tasks.Task.InternalWaitCore(Int32, CancellationToken)
              1 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)
              1 Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost)
              1 Program.<Main>$(String[])
         2 System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
         2 Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener.<CreateHost>b__10_0()
           ~~~~ 8a52a8
              1 System.Threading.WaitHandle.WaitOneNoCheck(Int32, Boolean, Object, WaitHandleWaitSourceMap)
              1 Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext, IFrameworkHandle, LoggerHelper, TestPlatformContext, RunSettings, IMessageSinkWithTypes, AssemblyRunInfo)
              1 Xunit.Runner.VisualStudio.VsTestRunner+<>c__DisplayClass18_0.<RunTests>b__4(AssemblyRunInfo)
              1 System.Collections.Generic.List<System.__Canon>.ForEach(Action<__Canon>)
              1 Xunit.Runner.VisualStudio.VsTestRunner.RunTests(IRunContext, IFrameworkHandle, LoggerHelper, TestPlatformContext, RunSettings, Func<List<AssemblyRunInfo>>)
              1 Xunit.Runner.VisualStudio.VsTestRunner.RunTests(IEnumerable<String>, IRunContext, IFrameworkHandle)
              1 Microsoft.VisualStudio.TestPlatform.Common.ExtensionDecorators.SerialTestRunDecorator.RunTests(IEnumerable<String>, IRunContext, IFrameworkHandle)
              1 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension<ITestExecutor,ITestExecutorCapabilities>, Tuple<Uri,String>, RunContext, IFrameworkHandle)
              1 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable<Tuple<Uri,String>>, Int64)
              1 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestsInternal()
              1 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTests()
              1 Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.ExecutionManager.StartTestRun(Dictionary<String,IEnumerable<String>>, String, String, TestExecutionContext, ITestCaseEventsHandler, IInternalTestRunEventsHandler)
              1 Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler+<>c__DisplayClass45_4.<OnMessageReceived>b__3()
              1 Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler+<>c.ctor>b__31_2(Action)
              1 Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue<System.__Canon>.SafeProcessJob(__Canon)
              1 Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue<System.__Canon>.BackgroundJobProcessor(String)
              1 Microsoft.VisualStudio.TestPlatform.Utilities.JobQueue<System.__Canon>.ctor>b__16_0()
           ~~~~ 8a52b4
              1 System.Threading.Monitor.Wait(Object, Int32)
              1 System.Threading.ManualResetEventSlim.Wait(Int32, CancellationToken)
              1 System.Threading.ManualResetEventSlim.Wait()
              1 Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.ProcessRequests(ITestHostManagerFactory)
              1 Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker+<>c__DisplayClass21_0.<StartProcessingAsync>b__0()
           ~~~~ 8a52dc
              1 System.Threading.WaitHandle.WaitOneNoCheck(Int32, Boolean, Object, WaitHandleWaitSourceMap)
              1 Xunit.Sdk.MessageBus.ReporterWorker()
              1 Xunit.Sdk.XunitWorkerThread+<>c.<QueueUserWorkItem>b__5_0(Object)
         3 System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
         3 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task ByRef, Thread)
                ~~~~ 8a52a9
                   1 Interop+Sys.Poll(SafeHandle, PollEvents, Int32, PollEvents ByRef)
                   1 System.Net.Sockets.SocketPal.Poll(SafeSocketHandle, Int32, SelectMode, Boolean ByRef)
                   1 System.Net.Sockets.Socket.Poll(Int32, SelectMode)
                   1 Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient, ICommunicationChannel, Action<Exception>, CancellationToken)
                   1 Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.SocketClient.<OnServerConnected>b__16_0()
                   1 System.Threading.Tasks.Task<System.__Canon>.InnerInvoke()
                   1 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
                   1 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task ByRef, Thread)
                ~~~~ 8a52de
                   1 Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.StopApplication()
                   1 Microsoft.Extensions.Hosting.Internal.Host+<StopAsync>d__16.MoveNext()
                   1 Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken)
                   1 Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<WaitForShutdownAsync>d__5.MoveNext()
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<WaitForShutdownAsync>d__5>.ExecutionContextCallback(Object)
                   1 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<WaitForShutdownAsync>d__5>.MoveNext(Thread)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<WaitForShutdownAsync>d__5>.ExecuteFromThreadPool(Thread)
                ~~~~ 8a52e1
                   1 System.Threading.Thread.Sleep(Int32)
                   1 Program+<>c.<<Main>$>b__0_8()
                   1 System.Threading.CancellationTokenSource.Invoke(Delegate, Object, CancellationTokenSource)
                   1 System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
                   1 System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
                   1 Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.StopApplication()
                   1 Microsoft.Extensions.Hosting.Internal.Host+<TryExecuteBackgroundServiceAsync>d__15.MoveNext()
                   1 System.Runtime.EH.DispatchEx(StackFrameIterator ByRef, ExInfo ByRef)
                   1 System.Runtime.EH.RhThrowEx(Object, ExInfo ByRef)
                   1 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                   1 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
                   1 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)
                   1 Microsoft.Extensions.Hosting.Internal.Host+<TryExecuteBackgroundServiceAsync>d__15.MoveNext()
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<Microsoft.Extensions.Hosting.Internal.Host+<TryExecuteBackgroundServiceAsync>d__15>.ExecutionContextCallback(Object)
                   1 System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<Microsoft.Extensions.Hosting.Internal.Host+<TryExecuteBackgroundServiceAsync>d__15>.MoveNext(Thread)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<Microsoft.Extensions.Hosting.Internal.Host+<TryExecuteBackgroundServiceAsync>d__15>.MoveNext()
                   1 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox, Boolean)
                   1 System.Threading.Tasks.Task.RunContinuations(Object)
                   1 System.Threading.Tasks.Task.TrySetCanceled(CancellationToken, Object)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetException(Exception, Task<VoidTaskResult> ByRef)
                   1 MartinCostello.Costellobot.ClientLogBroadcastService+<ExecuteAsync>d__3.MoveNext()
                   1 System.Runtime.EH.DispatchEx(StackFrameIterator ByRef, ExInfo ByRef)
                   1 System.Runtime.EH.RhThrowEx(Object, ExInfo ByRef)
                   1 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                   1 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task)
                   1 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions)
                   1 System.Runtime.CompilerServices.TaskAwaiter<System.__Canon>.GetResult()
                   1 MartinCostello.Costellobot.ClientLogBroadcastService+<ExecuteAsync>d__3.MoveNext()
                   1 System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>+AsyncStateMachineBox<System.__Canon>.MoveNext(Thread)
                   1 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox, Boolean)
                   1 System.Threading.Tasks.Task.RunContinuations(Object)
                   1 System.Threading.Tasks.Task.TrySetCanceled(CancellationToken, Object)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.SetException(Exception, Task<__Canon> ByRef)
                   1 MartinCostello.Costellobot.ChannelQueue<System.__Canon>+<DequeueAsync>d__7.MoveNext()
                   1 System.Runtime.EH.DispatchEx(StackFrameIterator ByRef, ExInfo ByRef)
                   1 System.Runtime.EH.RhThrowEx(Object, ExInfo ByRef)
                   1 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                   1 System.Threading.Channels.AsyncOperation<System.Boolean>.GetResult(Int16)
                   1 MartinCostello.Costellobot.ChannelQueue<System.__Canon>+<DequeueAsync>d__7.MoveNext()
                   1 System.Threading.ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
                   1 System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>+AsyncStateMachineBox<System.__Canon>.MoveNext(Thread)
              3 System.Threading.ThreadPoolWorkQueue.Dispatch()
           ~~~~ 8a52ac,8a52dd,8a52e2,8a52e3
              4 System.Threading.LowLevelLifoSemaphore.WaitNative(SafeWaitHandle, Int32)
              4 System.Threading.LowLevelLifoSemaphore.WaitForSignal(Int32)
              4 System.Threading.LowLevelLifoSemaphore.Wait(Int32, Boolean)
         7 System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   18 System.Threading.Thread.StartCallback()


==> 19 threads with 2 roots

> clrstack 8a5297
OS Thread Id: 0x8a5297 (0)
        Child SP               IP Call Site
000000016BDB5220 0000000197ef59ec [InlinedCallFrame: 000000016bdb5220]
000000016BDB5220 0000000106f074fc [InlinedCallFrame: 000000016bdb5220]
000000016BDB5200 0000000106F074FC System.Threading.Monitor.Wait(System.Object, Int32) [/_/src/coreclr/System.Private.CoreLib/src/System/Threading/Monitor.CoreCLR.cs @ 157]
000000016BDB52E0 0000000106F1A82C System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/ManualResetEventSlim.cs @ 578]
000000016BDB5370 0000000106F39844 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 3069]
000000016BDB53D0 0000000106F394F4 System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 3004]
000000016BDB5420 0000000106F38EDC System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken) [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 2765]
000000016BDB5440 0000000106F38D40 System.Threading.Tasks.Task.Wait() [/_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 2626]
000000016BDB5450 0000000107C9D624 Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(System.Collections.Generic.IDictionary`2<System.String,System.String>) [/_/src/testhost.x86/DefaultEngineInvoker.cs @ 153]
000000016BDB5530 0000000107C93A60 Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(System.String[], Microsoft.VisualStudio.TestPlatform.Execution.UiLanguageOverride) [/_/src/testhost.x86/Program.cs @ 65]
000000016BDB5560 0000000107C93680 Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(System.String[]) [/_/src/testhost.x86/Program.cs @ 54]
000000016BDB5580 0000000107C918B4 Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(System.String[]) [/_/src/testhost.x86/Program.cs @ 37]
```

**Comment by martincostello** [comment]
I've been able to get the preview 4 versions of both this project and another to not crash by setting `DOTNET_LegacyExceptionHandling=1` after @slang25 give me a tip-off after we were discussing that he's seeing a lot of random instability on his MacBook with .NET 9 preview 4:

- https://github.com/martincostello/costellobot/pull/1077/commits/d0875b0e8815632c1231a98415546de536bbf2ae [passed tests](https://github.com/martincostello/costellobot/actions/runs/9386268469?pr=1077)
- https://github.com/martincostello/dotnet-bumper/pull/89/commits/606b105ad4f22066b5c35810bf60e8e9996dc3a8 [passed tests](https://github.com/martincostello/dotnet-bumper/actions/runs/9386286664?pr=89)

/cc @janvorli

**Comment by janvorli** [comment]
@martincostello could you please share a dump with that crash with me? I am not aware of any instabilities due to the new exception handling in the runtime, so I really want to get to the bottom of this issue. My email is my alias at microsoft.com

**Comment by martincostello** [comment]
@janvorli Just emailed you a link.

**Comment by janvorli** [comment]
@martincostello the dump you have shared with me is somehow broken. I am unable to see the stack trace of the failing thread across a signal handler. Would you be able to capture / share another one?

**Comment by martincostello** [comment]
Sure, I can try - what are the best flags to pass to `dotnet test` to get the most useful dump I can for you?

**Comment by janvorli** [comment]
I don't have any preference for those. However, instead of letting .NET generate the dump, it might be useful to try to get a dump using the macOS dump collection facility. That means
* running `ulimit -c unlimited`
* running the dotnet test with sudo or adding your user to the wheel group or changing the protection of the /cores directory so that the OS can write the dump there

After that, running the dotnet test from the same console should produce dump in the /cores directory.

Sometimes, I had problems with dumps collected by our tools in specific cases, so that's why I am suggesting this.

**Comment by martincostello** [comment]
OK - I'm just working on a way to get my CI (I don't have access to any physical mac hardware myself) to upload crash dumps to somewhere securely without putting them into GitHub Actions artifacts first, then once that's working I'll try the extra steps above.

In the meantime, I just had an instance of the tests not crash, but fail with the following stack trace which I've not seen before:

```
System.ObjectDisposedException : The CancellationTokenSource has been disposed.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MartinCostello.Costellobot.Infrastructure.IntegrationTests`1.PostWebhookAsync(String event, Object value, String webhookSecret, String delivery) in /_/tests/Costellobot.Tests/Infrastructure/IntegrationTests`1.cs:line 176
   at MartinCostello.Costellobot.Handlers.DeploymentStatusHandlerTests.PostWebhookAsync(DeploymentStatusDriver driver, String action) in /_/tests/Costellobot.Tests/Handlers/DeploymentStatusHandlerTests.cs:line 667
   at MartinCostello.Costellobot.Handlers.DeploymentStatusHandlerTests.Deployment_Is_Approved_For_Trusted_User_And_Dependency_When_Penultimate_Build_Skipped() in /_/tests/Costellobot.Tests/Handlers/DeploymentStatusHandlerTests.cs:line 128
--- End of stack trace from previous location ---
```

**Comment by janvorli** [comment]
@martincostello I think the issue in the dumps you have shared with me is the issue is most likely a problem already fixed by #101971, so it should be fixed in preview 5. I guess the failures you are getting in preview 5 are likely something else. 
It would be great if you could share a dump from a crash with the preview 5 runtime too.

**Comment by martincostello** [comment]
@janvorli Sure - I'll try and get one of the preview 5 ones for you tomorrow.

**Comment by martincostello** [comment]
Not observing any crashes this morning - I'll keep any eye out as my automation updates to newer preview.5 builds daily. If I don't observe any further crashes by the time preview.5 officially ships I'll close this issue.

**Comment by martincostello** [comment]
I can't repro this as of the official preview 5, so I'm going to close this on the basis it must have gotten fixed at some point.

**Comment by wfurt** [comment]
great. Thanks for the confirmation @martincostello
