### ISSUE TITLE
Test failure: System.Diagnostics.Tests.CounterSampleCalculatorTests.CounterSampleCalculator_ElapsedTime

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#102429]
**Failed in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20240518.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680155&view=ms.vss-test-web.build-test-results-tab&runId=16867216&resultId=151307&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstress2_jitstressregs0x2000-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.CounterSampleCalculatorTests.CounterSampleCalculator_ElapsedTime
```

**Error message:**
```
 System.AggregateException : One or more errors occurred. (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.) (Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.)
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
---- System.InvalidOperationException : Category 'CounterSampleCalculator_ElapsedTime_Category' does not exist.
```

**Stack trace:**
```
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 54
   at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 73
   at System.Diagnostics.Tests.CounterSampleCalculatorTests.CounterSampleCalculator_ElapsedTime() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/CounterSampleCalculatorTests.cs:line 22
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 828
   at System.Diagnostics.PerformanceCounter.NextSample() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs:line 545
   at System.Diagnostics.PerformanceCounter.NextValue() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs:line 574
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass12_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 75
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 45
----- Inner Stack Trace #2 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 828
   at System.Diagnostics.PerformanceCounter.NextSample() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs:line 545
   at System.Diagnostics.PerformanceCounter.NextValue() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs:line 574
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass12_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 75
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 45
----- Inner Stack Trace #3 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 828
   at System.Diagnostics.PerformanceCounter.NextSample() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs:line 545
   at System.Diagnostics.PerformanceCounter.NextValue() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs:line 574
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass12_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 75
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 45
----- Inner Stack Trace #4 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, 
```

**Comment by ericstj** [comment]
I believe this is the same root case as https://github.com/dotnet/runtime/issues/104572.  Counters are deleted before tests can run.
