### ISSUE TITLE
Blazor Wasm limited to 1 GB of memory

### ISSUE THREAD

**Issue by verdie-g** [dotnet/runtime#102574]
### Description

OutOfMemoryExceptions are thrown after allocating more than ~1 GB in a Blazor Wasm app.

This is a duplicate of https://github.com/dotnet/aspnetcore/issues/55694 that got closed but the issue is not solved.

### Reproduction Steps

1. `dotnet new blazorwasm -n BlazorTest`
2. Add this method to Home.razor
```csharp
protected override void OnInitialized()
{
    const int bufferSize = 64 * 1000;
    const int oneGig = 1_000_000_000;
    List<byte[]> list = [];
    for (int i = 0; i < oneGig / bufferSize; i += 1)
    {
        list.Add(new byte[bufferSize]);
    }
}
```
3. `dotnet run --project BlazorTest`
4. Observe OOM in the console

### Expected behavior

Because wasm uses a 32-bits addressing, I would expect to be able to use 4 GB of memory.

### Actual behavior

OOM is thrown after allocating ~1 GB of memory.
```
System.OutOfMemoryException: Out of memory
   at BlazorTest.Pages.Home.OnInitialized() in /home/gverdier/repos/BlazorTest/Pages/Home.razor:line 17
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

### Configuration

.NET: 8.0.100
OS: Ubuntu x64
Browser: Google Chrome 125

**Comment by verdie-g** [comment]
It seems like it was fixed in .NET 10
