### ISSUE TITLE
Shake128Tests/Shake256Tests throw PNSE on Fedora 40

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#102562]
The Shake*Tests throw PNSE on our Fedora 40 CI.

The OpenSSL package version is: 3.2.1-2.fc40.

Example failure:
```
System.PlatformNotSupportedException: System.PlatformNotSupportedException : Operation is not supported on this platform.
        at Interop.Crypto.EvpDigestSqueeze(SafeEvpMdCtxHandle ctx, Span`1 destination) in /home/tester/runtime/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.EVP.cs:line 108
at System.Security.Cryptography.LiteXof.Read(Span`1 destination) in /home/tester/runtime/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Unix.cs:line 88
at System.Security.Cryptography.Shake128.Read(Span`1 destination) in /home/tester/runtime/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/Shake128.cs:line 218
at System.Security.Cryptography.Tests.Shake128Tests.Traits.Read(Shake128 shake, Span`1 destination) in /home/tester/runtime/src/libraries/System.Security.Cryptography/tests/Shake128Tests.cs:line 24
at System.Security.Cryptography.Tests.ShakeTestDriver`2.Read_MixedGetHashAndReset() in /home/tester/runtime/src/libraries/System.Security.Cryptography/tests/ShakeTestDriver.cs:line 716
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 50
```

cc @vcsjones @omajid

**Comment by vcsjones** [comment]
I can take a look.
