### ISSUE TITLE
Firefox MT typeload exceptions

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#102615]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=685548
Build error leg or test failing: WasmTestOnFirefox-MT-Microsoft.Extensions.FileSystemGlobbing.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/102489

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "fail: System.TypeLoadException: Could not load type of field", "geckodriver	INFO" ]
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by ericstj** [comment]
@lewing  the ordering in your ErrorMessage array matters.  In the log `geckodriver	INFO` occurs before `fail: System.TypeLoadException` so the order in the query needs to swap.

**Comment by lewing** [comment]
similar to https://github.com/dotnet/runtime/issues/102762

**Comment by lewing** [comment]
This hasn't been hit in a couple of weeks, keeping open for now but moving to 10

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-108061-merge-a2d3fe743657432cb0/WasmTestOnFirefox-MT-System.Console.Manual.Tests/1/console.abeb22ad.log?helixlogtype=result)
```
System.TypeLoadException: Could not load type of field 'Mono.Options.OptionSet:ValueOption' (3) due to: 
Could not resolve type with token 0100002f from typeref 
(expected class 'System.Text.RegularExpressions.Regex' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Text.RegularExpressions.Regex member:(null)
```

Do we need memory barrier after we load the assembly from fetch ?

**Comment by pavelsavara** [comment]
I thought lot of those issues are only visible on FF, but here we have Chrome specimen.

[Log](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-483ad509fabf46e88e/WasmTestOnChrome-MT-System.IO.Packaging.Tests/1/console.ebcb0878.log?helixlogtype=result)
```
[09:18:53] fail: [0x000ebcc8--UI- 09:18:53.626] MONO_WASM: Could not set up parent class, due to: Could not load type of field 'Xunit.Xunit2Discoverer:<TestFrameworkAssemblyName>k__BackingField' (7) due to: Could not load file or assembly 'System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:xunit.runner.utility.netcoreapp10.dll type:Xunit2Discoverer member:(null)
                    at Xunit.XunitFrontController.EnsureInitialized()
                    at Xunit.XunitFrontController.get_InnerController()
                    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
                    at Microsoft.DotNet.XHarness.TestRunners.Xunit.XUnitTestRunner.Run(Assembly assembly, String assemblyPath)
```

That means it's our problem, not FF
