### ISSUE TITLE
System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.JSDelay_ContinueWith_Sync test failed

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#103080]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=697787
Build error leg or test failing: WasmTestOnChrome-MT-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/102475

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.JSDelay_ContinueWith_Sync(executor: NewThread)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=697787
**Error message validated:** `[[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.JSDelay_ContinueWith_Sync(executor: NewThread)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/5/2024 4:58:58 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ilonatommy** [comment]
It wasn't hit for a month. We can reopen if it gets hit again.

**Comment by mkhamoyan** [comment]
This was hit yesterday in https://github.com/dotnet/runtime/pull/104393 [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-104393-merge-9a7a025de5ee4b288c/WasmTestOnFirefox-MT-System.Runtime.InteropServices.JavaScript.Tests/1/console.52220704.log?helixlogtype=result)

```
[16:49:23] info: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.JSDelay_ContinueWith_Sync(executor: NewThread)
[16:49:23] info: Assert.True() Failure
[16:49:23] info: Expected: True
[16:49:23] info: Actual:   False
[16:49:23] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.<>c.<JSDelay_ContinueWith_Sync>b__15_1(Task _)
[16:49:23] info:    at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
[16:49:23] info:    at System.Threading.Tasks.Task.<>c.<.cctor>b__292_0(Object obj)
[16:49:23] info:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
[16:49:23] info: --- End of stack trace from previous location ---
[16:49:23] info:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext , ContextCallback , Object )
[16:49:23] info:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
[16:49:23] info: --- End of stack trace from previous location ---
[16:49:23] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.<>c__DisplayClass15_0.<<JSDelay_ContinueWith_Sync>b__0>d.MoveNext()
[16:49:23] info: --- End of stack trace from previous location ---
[16:49:23] info:    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.JSDelay_ContinueWith_Sync(Executor executor)
[16:49:23] info: --- End of stack trace from previous location ---
```
