### ISSUE TITLE
GC test failure on arm64 mono interpreter

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#103124]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=699251&view=results
Build error leg or test failing: `GC/Regressions/v2.0-beta2/452950`
Pull request: https://github.com/dotnet/runtime/pull/102961

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "GC/Regressions/v2.0-beta2/452950/452950/452950.sh [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

## Error log
```
dotnet /tmp/helix/working/B050098D/p/xunit/xunit.console.dll GC/LargeMemory/GC.LargeMemory.XUnitWrapper.dll GC/Features/GC.Features.XUnitWrapper.dll GC/Scenarios/GC.Scenarios.XUnitWrapper.dll GC/API/GC.API.XUnitWrapper.dll GC/Regressions/GC.Regressions.XUnitWrapper.dll GC/Coverage/GC.Coverage.XUnitWrapper.dll GC/Stress/GC.Stress.XUnitWrapper.dll ilasm/PortablePdb/ilasm.PortablePdb.XUnitWrapper.dll ilasm/System/ilasm.System.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml
Microsoft.DotNet.XUnitConsoleRunner v2.6.7.0 (64-bit .NET 9.0.0-preview.4.24266.19)
  Discovering: GC.LargeMemory.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  GC.LargeMemory.XUnitWrapper (found 3 test cases)
  Starting:    GC.LargeMemory.XUnitWrapper (parallel test collections = on [8 threads], stop on fail = off)
  Finished:    GC.LargeMemory.XUnitWrapper
  Discovering: GC.Features.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  GC.Features.XUnitWrapper (found 18 test cases)
  Starting:    GC.Features.XUnitWrapper (parallel test collections = on [8 threads], stop on fail = off)
  Finished:    GC.Features.XUnitWrapper
  Discovering: GC.Scenarios.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  GC.Scenarios.XUnitWrapper (found 22 test cases)
  Starting:    GC.Scenarios.XUnitWrapper (parallel test collections = on [8 threads], stop on fail = off)
  Finished:    GC.Scenarios.XUnitWrapper
  Discovering: GC.API.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  GC.API.XUnitWrapper (found 22 test cases)
  Starting:    GC.API.XUnitWrapper (parallel test collections = on [8 threads], stop on fail = off)
  Finished:    GC.API.XUnitWrapper
  Discovering: GC.Regressions.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  GC.Regressions.XUnitWrapper (found 9 test cases)
  Starting:    GC.Regressions.XUnitWrapper (parallel test collections = on [8 threads], stop on fail = off)
    GC/Regressions/v2.0-beta2/452950/452950/452950.sh [FAIL]
      
      Return code:      1
      Raw output file:      /tmp/helix/working/B050098D/w/B1CE09B6/uploads/Reports/GC.Regressions/v2.0-beta2/452950/452950/452950.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/B050098D/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true 452950.dll ''
      95
      Failed
      Expected: 100
      Actual: 1
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /cores since 6/5/2024 2:45:16 AM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/tmp/helix/working/B050098D/p
      > /private/tmp/helix/working/B050098D/w/B1CE09B6/e/GC/Regressions/v2.0-beta2/452950/452950/452950.sh
      Stack Trace:
           at GC_Regressions._v2_0_beta2_452950_452950_452950_._v2_0_beta2_452950_452950_452950_sh()
        
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /tmp/helix/working/B050098D/w/B1CE09B6/uploads/Reports/GC.Regressions/v2.0-beta2/452950/452950/452950.output.txt
        Raw output:
        BEGIN EXECUTION
        /tmp/helix/working/B050098D/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true 452950.dll ''
        95
        Failed
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /cores since 6/5/2024 2:45:16 AM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/tmp/helix/working/B050098D/p
        > /private/tmp/helix/working/B050098D/w/B1CE09B6/e/GC/Regressions/v2.0-beta2/452950/452950/452950.sh
  Finished:    GC.Regressions.XUnitWrapper
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=699251
**Error message validated:** `[GC/Regressions/v2.0-beta2/452950/452950/452950.sh [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/6/2024 1:58:31 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[699251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699251)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699251&view=ms.vss-test-web.build-test-results-tab&runId=17400270&resultId=115002)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by kotlarmilos** [comment]
This is the range: https://github.com/dotnet/runtime/compare/40ff2ecd86073987c2706b2992648bd21bcf69bf...2a80808f86459a95229c6f9c85ce32b62636fceb. This could also be a transient failure.

**Comment by BrzVlad** [comment]
this is https://github.com/dotnet/runtime/issues/99729. Any idea why it wasn't detected by the other issue ?

**Comment by kotlarmilos** [comment]
Thanks. The extra platforms were not executed on this PR, and I manually reported this issue.
