### ISSUE TITLE
[8.0] "Stream aborted by peer" failure in System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#103264]
Note that "Build retry" is enabled for this failure as it looks like it could be a networking issue. Please disable it if you think it's not worth stressing the system.

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=703197&view=logs&j=52ad279b-b059-569b-870a-4d7b21a81589&t=2ee877e9-a459-5e35-8acf-a38e5009bee3&l=88
Build error leg or test failing: System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [
    "Stream aborted by peer",
    "ServerSendsTrailingHeaders_Success [FAIL]"
  ],
  "BuildRetry": true,
  "ExcludeConsoleLog": false
}
```

PR: https://github.com/dotnet/runtime/pull/103253
Queue: `Libraries Test Run release coreclr linux x64 Release`
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=703197&view=logs&j=52ad279b-b059-569b-870a-4d7b21a81589&t=2ee877e9-a459-5e35-8acf-a38e5009bee3&l=88
Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-staging-5af68ea19de047af81/System.Net.Http.Functional.Tests/3/console.29c365b7.log?helixlogtype=result
Output:
```
    System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success [FAIL]
      System.Net.Quic.QuicException : Stream aborted by peer (268).
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(169,0): at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(565,0): at System.Net.Quic.QuicStream.HandleEventPeerReceiveAborted(_PEER_RECEIVE_ABORTED_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(615,0): at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(646,0): at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(277,0): at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(165,0): at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(120,0): at System.Net.Test.Common.Http3LoopbackStream.SendHeadersFrameAsync(Nullable`1 statusCode, IEnumerable`1 headers, Boolean qpackEncodeStatus)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(261,0): at System.Net.Test.Common.Http3LoopbackStream.SendResponseHeadersAsync(Nullable`1 statusCode, IEnumerable`1 headers)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1639,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerSendsTrailingHeaders_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1640,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerSendsTrailingHeaders_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1640,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerSendsTrailingHeaders_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1663,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success()
        --- End of stack trace from previous location ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_Cancellation [SKIP]
      Condition(s) not met: "IsBrowser"
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_StreamingCancellation [SKIP]
      Condition(s) not met: "IsBrowser"
  Finished:    System.Net.Http.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Http.Functional.Tests  Total: 4534, Errors: 0, Failed: 1, Skipped: 23, Time: 84.294s
/datadisks/disk1/work/B66109BB/w/B9CC0977/e
----- end Tue Jun 11 01:09:00 UTC 2024 ----- exit code 1 ----------------------------------------------------------
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=703197
**Error message validated:** `[Stream aborted by peer ServerSendsTrailingHeaders_Success [FAIL]`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 6/11/2024 3:49:40 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MihaZupan** [comment]
This looks like the same issue as #87552 (we made changes in 9.0 and 8.0 - #91291, #91690).
I'm still seeing about 1 `PassedOnRerun` entry a day for this test, but only on 8.0 runs.
Given it appears to be fine on 9, I think we should just disable it on 8.0. @liveans thoughts?

**Comment by liveans** [comment]
> This looks like the same issue as #87552 (we made changes in 9.0 and 8.0 - #91291, #91690). I'm still seeing about 1 `PassedOnRerun` entry a day for this test, but only on 8.0 runs. Given it appears to be fine on 9, I think we should just disable it on 8.0. @liveans thoughts?

I also think that we can disable this on 8.0, and I think this is not failing on 9.0 due to this work: https://github.com/dotnet/runtime/pull/90253

**Comment by karelz** [comment]
Do we need to keep open issues against tests disabled in 8.0.x? Or can we close the issue now?

**Comment by MihaZupan** [comment]
We won't be fixing it in 8.0 and it's not disabled in 9.0+, no need to track it.
