### ISSUE TITLE
Test failure: Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ServiceCanStopItself

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#103262]
**Failed in:** [runtime-coreclr libraries-pgo 20240609.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701806&view=ms.vss-test-web.build-test-results-tab&runId=17471672&resultId=176621&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-fullpgo_random_gdv-Windows.10.Amd64.Open
    - Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ServiceCanStopItself
```

**Error message:**
```
 System.ServiceProcess.TimeoutException : The operation requested for service 'ServiceCanStopItself' has not been completed within the specified time interval.
```

**Stack trace:**
```
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 994
   at Microsoft.Extensions.Hosting.WindowsServiceTester.WaitForStatus(ServiceControllerStatus desiredStatus) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 54
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ServiceCanStopItself() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs:line 174
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 48
```

**Comment by steveharter** [comment]
Similar to https://github.com/dotnet/runtime/issues/103262
