### ISSUE TITLE
Assertion failed: The class hierarchy should declare the method

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#103268]
This is just an assert guarding some invariant that the reflection stack relies on. The test "works" with a release build of the runtime, but whatever invariant it's guarding obviously doesn't hold.

Ran into this while writing tests for #103220, going to disable newly added tests on this.

```
Process terminated. Assertion failed.
The class hierarchy should declare the method
   at System.Delegate.GetMethodImpl()
   at System.MulticastDelegate.GetMethodImpl()
   at Program.<Main>$(String[] args)
```

Hit for the following program:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using Internal;

foreach (var o in Create_ClosedDelegate_TestData())
    Console.WriteLine(((Delegate)o[0]).Method.ToString());


static IEnumerable<object[]> Create_ClosedDelegate_TestData()
{
    const string TestNamespace = nameof(System);

    IGenericInterfaceForDiagnosticMethodInfoTests<object> og = new GenericClassForDiagnosticMethodInfoTests<object>();

        yield return new object[] {
                (Action)og.NonGenericDefaultMethod,
                nameof(IGenericInterfaceForDiagnosticMethodInfoTests<object>.NonGenericDefaultMethod) ,
                TestNamespace + nameof(IGenericInterfaceForDiagnosticMethodInfoTests<object>) + "`1"
                };

    yield return new object[] {
                (Action)og.GenericDefaultMethod<object>,
                nameof(IGenericInterfaceForDiagnosticMethodInfoTests<object>.GenericDefaultMethod),
                TestNamespace + nameof(IGenericInterfaceForDiagnosticMethodInfoTests<object>) + "`1"
            };
}

interface IGenericInterfaceForDiagnosticMethodInfoTests<T>
{
    void NonGenericMethod();
    void GenericMethod<U>();

    void NonGenericDefaultMethod() { }
    void GenericDefaultMethod<U>() { }
}

class GenericClassForDiagnosticMethodInfoTests<T> : IGenericInterfaceForDiagnosticMethodInfoTests<T>
{
    void IGenericInterfaceForDiagnosticMethodInfoTests<T>.GenericMethod<U>() => throw new NotImplementedException();
    void IGenericInterfaceForDiagnosticMethodInfoTests<T>.NonGenericMethod() => throw new NotImplementedException();
    public void Method1() { }
    public void Method2() { }
}
```

**Comment by ericstj** [comment]
Assertion is here:
https://github.com/dotnet/runtime/blob/17c55f1709da56e0904494a69865ba52ea827c06/src/coreclr/System.Private.CoreLib/src/System/Delegate.CoreCLR.cs#L194-L197

Seems to me like this assertion doesn't handle DIMs.  Should it just be updated to account to allow DIMs @AaronRobinsonMSFT @jkotas?

**Comment by AaronRobinsonMSFT** [comment]
@ericstj Yes, this is a DIM issue. A naive fix would be to update the assert to check if the `targetType` is an interface. I'm not sure we have a better explicit check for a DIM. I can submit a PR if everyone is okay with this.

```csharp
Debug.Assert(
    currentType != null
    || _target.GetType().IsCOMObject
    || targetType.IsInterface, "The class hierarchy should declare the method");
```
