### ISSUE TITLE
SslStreamTlsResumeTests.ClientDisableTlsResume_Succeeds failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#103449]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=707064
Build error leg or test failing: System.Net.Security.Tests.SslStreamTlsResumeTests.ClientDisableTlsResume_Succeeds
Pull request: https://github.com/dotnet/runtime/pull/103309

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "ClientDisableTlsResume_Succeeds",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
❌ System.Net.Security.Tests.SslStreamTlsResumeTests.ClientDisableTlsResume_Succeeds(testClient: True)
Exception Message
TLS session resumed in round $2
Stack Trace
   at System.Net.Security.Tests.SslStreamTlsResumeTests.ClientDisableTlsResume_Succeeds(Boolean testClient) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamAllowTlsResumeTests.cs:line 99
--- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=707064
**Error message validated:** `[ClientDisableTlsResume_Succeeds`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/14/2024 11:26:27 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by stephentoub** [comment]
@rzikm, can we disable this test? It's failing a lot.

**Comment by rzikm** [comment]
The behavior seems to be flaky and seems to depend on timing, the bug has been passed to SChannel team for investigation.

**Comment by rzikm** [comment]
Removing from 9.0.0, as this is not critical for 9.0 and the SChannel team is currently busy with higher priority investigations.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by jkotas** [comment]
This failed again in #113416 windows-Debug-x64-coreclr_release-Windows.Amd64.Server2022.Open:

From https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-113416-merge-2f216bd0c68a49be87/System.Net.Security.Tests/3/console.734dc56a.log?helixlogtype=result:
```
    System.Net.Security.Tests.SslStreamTlsResumeTests.ClientDisableTlsResume_Succeeds(testClient: True) [FAIL]
      TLS session resumed in round $2
      Stack Trace:
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamAllowTlsResumeTests.cs(99,0): at System.Net.Security.Tests.SslStreamTlsResumeTests.ClientDisableTlsResume_Succeeds(Boolean testClient)
        --- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Fixed by https://github.com/dotnet/runtime/pull/113604

**Comment by liveans** [comment]
> Fixed by [#113604](https://github.com/dotnet/runtime/pull/113604)

This test is still disabled
https://github.com/dotnet/runtime/blob/3057101c0479ff67b389d5a578b3e25cc8b8512a/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamAllowTlsResumeTests.cs#L37-L38
