### ISSUE TITLE
Test failure: System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#103457]
**Failed in:** [runtime-coreclr crossgen2 20240612.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706281&view=ms.vss-test-web.build-test-results-tab&runId=17620938&resultId=138539&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.81.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
 Expected: 6/13/2024 8:02:52 AM to be greater than 6/13/2024 8:02:52 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr crossgen2 20240625.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720701&view=ms.vss-test-web.build-test-results-tab&runId=18075160&resultId=139082&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.81.Amd64.Open
    - System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime
```

**Error message:**
```
 Expected: 6/26/2024 8:10:48 AM to be greater than 6/26/2024 8:10:48 AM
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime() in /_/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/GetSetTimes_SafeFileHandle.cs:line 115
--- End of stack trace from previous location ---
```

**Comment by ivdiazsa** [comment]
Been checking the pipelines and this test seems to only be failing in the Windows 8.1 pipelines, which will be decommissioned by the end of the month. I wasn't able to reproduce it locally either. The Windows 10 pipelines that fail are different tests from this one, so it might not be worth it to keep looking into this specific issue.
