### ISSUE TITLE
Test failure: baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#103547]
**Failed in:** [runtime-coreclr gcstress-extra 20240615.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709160&view=ms.vss-test-web.build-test-results-tab&runId=17706880&resultId=108313&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked gcstress0xc_disabler2r_heapverify1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux arm64 Checked gcstress0xc_disabler2r_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux arm64 Checked gcstress0xc_disabler2r @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows arm64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.11.Arm64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows arm64 Checked gcstress0xc_disabler2r @ Windows.11.Arm64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux x64 Checked gcstress0xc_disabler2r_heapverify1 @ Ubuntu.2204.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows arm64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.11.Arm64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux x64 Checked gcstress0xc_disabler2r_jitstress2 @ Ubuntu.2204.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux x64 Checked gcstress0xc_disabler2r @ Ubuntu.2204.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```

**Error message:**
```
 Failed: Verify_ServerGC_Env_Enable: exit code = 134
```

**Stack trace:**
```
   at TestConfigTester.RunTests()
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr gcstress-extra 20240616.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709589&view=ms.vss-test-web.build-test-results-tab&runId=17720442&resultId=101883&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.11.Arm64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux arm64 Checked gcstress0xc_disabler2r_heapverify1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows arm64 Checked gcstress0xc_disabler2r @ Windows.11.Arm64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows arm64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.11.Arm64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux arm64 Checked gcstress0xc_disabler2r @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux arm64 Checked gcstress0xc_disabler2r_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux x64 Checked gcstress0xc_disabler2r_jitstress2 @ Ubuntu.2204.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux x64 Checked gcstress0xc_disabler2r_heapverify1 @ Ubuntu.2204.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr linux x64 Checked gcstress0xc_disabler2r @ Ubuntu.2204.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
coreclr windows x64 Checked gcstress0xc_disabler2r @ Windows.10.Amd64.Open
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```

**Error message:**
```
 Failed: Verify_ServerGC_Env_Enable: exit code = -1073740286
```

**Stack trace:**
```
   at TestConfigTester.RunTests()
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-06-17T07:33:21.772Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | windows.11.arm64.open | arm64 | baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll | Failed | {"System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","BuildId":"709719","BuildNumber":"20240616.1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"c55e12b8-4209-535c-d94d-51b07fc6ab63","AzurePipelinesTestRunId":"17727754","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageName":"Build","System.PhaseName":"run_test_p1_Composite_windows_arm64_checked","configuration":"Checked-gcstress0xc_disabler2r","DefinitionId":"141","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule
2024-06-17T07:33:21.772Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | windows.11.arm64.open | arm64 | baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll | Failed | {"System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","BuildId":"709719","BuildNumber":"20240616.1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"c55e12b8-4209-535c-d94d-51b07fc6ab63","AzurePipelinesTestRunId":"17727754","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageName":"Build","System.PhaseName":"run_test_p1_Composite_windows_arm64_checked","configuration":"Checked-gcstress0xc_disabler2r","DefinitionId":"141","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule
2024-06-17T07:33:21.772Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | windows.11.arm64.open | arm64 | baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll | Failed | {"System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","BuildId":"709719","BuildNumber":"20240616.1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"c55e12b8-4209-535c-d94d-51b07fc6ab63","AzurePipelinesTestRunId":"17727754","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageName":"Build","System.PhaseName":"run_test_p1_Composite_windows_arm64_checked","configuration":"Checked-gcstress0xc_disabler2r","DefinitionId":"141","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule

**Comment by mangod9** [comment]
adding @VSadov to check if this can be reproed.

**Comment by VSadov** [comment]
The testcase launches a separate small program while enabling Server GC and that program hits an assert.

Looks like a GC bug. Possibly just an assert that is too strict. @dotnet/gc

```
22:35:51.533 Running test: baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
Running: "C:\h\w\9FEF08EE\w\B0DA09B1\e\baseservices\baseservices\TestConfig.dll" Verify_ServerGC_Env_Enable
    set DOTNET_gcServer=1

Assert failure(PID 5332 [0x000014d4], Thread: 8404 [0x20d4]): total_soh_stable_size > 0

CORECLR! SVR::gc_heap::dynamic_heap_count_data_t::compute_gen0_budget_per_heap + 0x40 (0x00007ff9`98052cf0)
CORECLR! SVR::gc_heap::update_end_gc_time_per_heap + 0x294 (0x00007ff9`98082b0c)
CORECLR! SVR::gc_heap::gc1 + 0x130C (0x00007ff9`9805e7dc)
CORECLR! SVR::gc_heap::garbage_collect + 0x898 (0x00007ff9`9805d4a0)
CORECLR! SVR::gc_heap::gc_thread_function + 0x498 (0x00007ff9`9805ed98)
CORECLR! SVR::gc_heap::gc_thread_stub + 0x78 (0x00007ff9`9805f268)
CORECLR! <lambda_e7b69842a3dfd51332f5bcb927a9be70>::<lambda_invoker_cdecl> + 0x7C (0x00007ff9`97ee3dbc)
KERNEL32! BaseThreadInitThunk + 0x30 (0x00007ff9`c7952310)
NTDLL! RtlUserThreadStart + 0x3C (0x00007ff9`cad9578c)
    File: D:\a\_work\1\s\src\coreclr\gc\gcpriv.h:4882
    Image: C:\h\w\9FEF08EE\p\corerun.exe

System.Exception: Failed: Verify_ServerGC_Env_Enable: exit code = -1073740286
   at TestConfigTester.RunTests()
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
22:36:03.800 Failed test: baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
22:36:03.918 Running test: baseservices/callconvs/TestCallingConventions/TestCallingConventions.cmd
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20240630.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725487&view=ms.vss-test-web.build-test-results-tab&runId=18220782&resultId=120951&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
```

**Error message:**
```
 Failed: Verify_ServerGC_Env_Enable: exit code = 134
```

**Stack trace:**
```
   at TestConfigTester.RunTests()
   at Program.<<Main>$>g__TestExecutor4|0_5(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-06-17T07:33:21.772Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | windows.11.arm64.open | arm64 | baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll | Failed | {"System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","BuildId":"709719","BuildNumber":"20240616.1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"c55e12b8-4209-535c-d94d-51b07fc6ab63","AzurePipelinesTestRunId":"17727754","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageName":"Build","System.PhaseName":"run_test_p1_Composite_windows_arm64_checked","configuration":"Checked-gcstress0xc_disabler2r","DefinitionId":"141","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule
2024-06-17T07:33:21.772Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | windows.11.arm64.open | arm64 | baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll | Failed | {"System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","BuildId":"709719","BuildNumber":"20240616.1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"c55e12b8-4209-535c-d94d-51b07fc6ab63","AzurePipelinesTestRunId":"17727754","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageName":"Build","System.PhaseName":"run_test_p1_Composite_windows_arm64_checked","configuration":"Checked-gcstress0xc_disabler2r","DefinitionId":"141","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule
2024-06-17T07:33:21.772Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_disabler2r | windows.11.arm64.open | arm64 | baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll | Failed | {"System.StageAttempt":"1","DefinitionName":"runtime-coreclr   crossgen2-composite   gcstress","BuildId":"709719","BuildNumber":"20240616.1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"c55e12b8-4209-535c-d94d-51b07fc6ab63","AzurePipelinesTestRunId":"17727754","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageName":"Build","System.PhaseName":"run_test_p1_Composite_windows_arm64_checked","configuration":"Checked-gcstress0xc_disabler2r","DefinitionId":"141","Reason":"Schedule","System.JobAttempt":"1","architecture":"arm64"} | Schedule

**Comment by cshung** [comment]
The bug is understood.

With `gcstress=c`, the very first GC is triggered before anything is allocated, therefore `get_total_soh_stable_size()` returned `0` and upset the logic at `dynamic_heap_count_data_t::get_total_soh_stable_size()`.

We can't just relax the assert because this will lead to division by `0`.

**Comment by Maoni0** [comment]
we can just give it a temp value like min gen1 size, the result from `compute_total_gen0_budget` will be adjusted to min gen0 budget anyway, ie, in `get_total_soh_stable_size`, add the `if (!total_stable_size)` block.

```cplusplus
size_t gc_heap::get_total_soh_stable_size()
{
    if (current_total_soh_stable_size)
    {
        return current_total_soh_stable_size;
    }
    else
    {
        size_t total_stable_size = 0;
        for (int i = 0; i < gc_heap::n_heaps; i++)
        {
            gc_heap* hp = g_heaps[i];
            total_stable_size += hp->generation_size (max_generation - 1) / 2;
        }

        if (!total_stable_size)
        {
            // Setting a temp value before a GC naturally happens (ie, due to allocation).
            total_stable_size = dd_min_size (g_heaps[0]->dynamic_data_of (max_generation - 1));
        }

        return total_stable_size;
    }
}
```
