### ISSUE TITLE
XDocument.Load fails with certain Unicode characters (U+E039)

### ISSUE THREAD

**Issue by Eilon** [dotnet/runtime#103532]
### Description

Calling `XDocument.Load()` when *any* part of the path has [Unicode character U+E039](https://unicodeplus.com/U+E039) fails with:

```
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'E:\repos\BugRepros\another\re\????????%EE%80%B9?&?? ???? ??? ? ??.xml'.
File name: 'E:\repos\BugRepros\another\re\????????%EE%80%B9?&?? ???? ??? ? ??.xml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Program.<Main>$(String[] args) in E:\repos\BugRepros\another\re\Program.cs:line 3
```

That is, if any part of the effective full filename of the file has that character, you get the error. It appears to be URL-encoding that character and trying to use the *URL-encoded* path to load the file, which of course won't work.

### Reproduction Steps

One line of code is all you need in an otherwise blank C# console app:

```csharp
System.Xml.Linq.XDocument.Load("𫓧龦唉丂荳◎℉㐁&ᠭᠤ སྲིད خەل ꌠ ᥕ᧞.xml");
```

Note: That XML file doesn't have to exist (it won't get loaded anyway due to the bug!), and you can run this from anywhere.

### Expected behavior

The specified XML file should be loaded.

### Actual behavior

The previously mentioned exception is thrown.

### Regression?

Not sure if it's a regression, but some very similar bugs have been reported, and supposedly fixed quite some time ago:

1. https://github.com/dotnet/runtime/issues/23738
1. https://github.com/dotnet/runtime/issues/24403
1. https://github.com/dotnet/runtime/issues/24602
1. https://github.com/dotnet/runtime/issues/25382
1. https://github.com/dotnet/runtime/issues/28212

### Known Workarounds

None

### Other information

```
>dotnet --info

.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.00e64df5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\
```

**Comment by danmoseley** [comment]
Guessing this is about URI rather than FileStream, as -- 
```
File.WriteAllText("c:\\bak\\abc\ue039", "xyz");
using var fs = new FileStream("c:\\bak\\abc\ue039", FileMode.Open) // OK
System.Xml.Linq.XDocument.Load("c:\\bak\\abc\ue039"); // System.IO.FileNotFoundException: 'Could not find file 'c:\bak\abc%EE%80%B9'.'
```

**Comment by danmoseley** [comment]
@MihaZupan is that a known URI thing (or I'm doing it wrong?)

**Comment by MihaZupan** [comment]
Very likely #89538 -- behavior with paths when the Uri contains "Private Use Area" characters

**Comment by danmoseley** [comment]
Yes, it seems that as `System.Xml.Linq.XDocument.Load("file://c:\\bak\\abc\ue039");` works. Do you want to close as dupe?
