### ISSUE TITLE
System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows fails in CI

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#103586]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=710311
Build error leg or test failing: System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
Pull request: https://github.com/dotnet/runtime/pull/103576

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20240623.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717422&view=ms.vss-test-web.build-test-results-tab&runId=17968886&resultId=118323&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-fullpgo_methodprofiling-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
      at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240630.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725277&view=ms.vss-test-web.build-test-results-tab&runId=18212088&resultId=122099&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-jitstress2_tiered-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240708.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=732574&view=ms.vss-test-web.build-test-results-tab&runId=18439392&resultId=131325&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-jitstress2_tiered-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240724.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753165&view=ms.vss-test-web.build-test-results-tab&runId=19084944&resultId=133261&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2_tiered-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240807.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768198&view=ms.vss-test-web.build-test-results-tab&runId=19600986&resultId=115836&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2_tiered-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20240929.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=821627&view=ms.vss-test-web.build-test-results-tab&runId=21328594&resultId=122044&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-fullpgo_methodprofiling-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by JulieLeeMSFT** [comment]
@adityamandaleeka, PTAL. 
CC @AndyAyersMS.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20241010.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=837632&view=ms.vss-test-web.build-test-results-tab&runId=21690164&resultId=133284&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstress1_tiered-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20241020.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=848456&view=ms.vss-test-web.build-test-results-tab&runId=22025032&resultId=129571&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-fullpgo_random_gdv_edge-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20241020.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=848456&view=ms.vss-test-web.build-test-results-tab&runId=22025032&resultId=129571&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-fullpgo_random_gdv_edge-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```

**Comment by carlossanlop** [comment]
Hit this today in 9.0: https://github.com/dotnet/runtime/pull/112628/checks?check_run_id=38523562417

- Queue: Libraries Test Run checked coreclr windows x64 Release
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=974437&view=logs&j=51e4640a-c078-5be6-cc1b-f971e75d762f
- Output:
```
C:\h\w\AB180980\w\B47C0A3C\e>"C:\h\w\AB180980\p\dotnet.exe" exec --runtimeconfig System.IO.Pipelines.Tests.runtimeconfig.json --depsfile System.IO.Pipelines.Tests.deps.json xunit.console.dll System.IO.Pipelines.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.IO.Pipelines.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.Pipelines.Tests (found 408 of 413 test cases)
  Starting:    System.IO.Pipelines.Tests (parallel test collections = on [4 threads], stop on fail = off)
    System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows [FAIL]
      Assert.Throws() Failure: No exception was thrown
      Expected: typeof(System.InvalidOperationException)
      Stack Trace:
        /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs(311,0): at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows()
        --- End of stack trace from previous location ---
  Finished:    System.IO.Pipelines.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.Pipelines.Tests  Total: 572, Errors: 0, Failed: 1, Skipped: 0, Time: 19.769s
```

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20251129.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1215609)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstress1_tiered-Windows.10.Amd64.Open
    - System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows
```

**Error message:**
```
Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.IO.Pipelines.Tests.PipeWriterTests.CompleteWithLargeWriteThrows() in /_/src/libraries/System.IO.Pipelines/tests/PipeWriterTests.cs:line 311
--- End of stack trace from previous location ---
```
