### ISSUE TITLE
DisableBitTests.EnabledThroughFeatureSwitch/DisabledAlwaysInBrowser failures

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#103683]
These tests are failing in our CI which is building with these flags:

```
/p:NoPgoOptimize=true --portablebuild false /p:DotNetBuildFromSource=true /p:DotNetBuildSourceOnly=true /p:DotNetBuildTests=true --runtimeconfiguration Release --librariesConfiguration Debug
```

The test failures are:

```
System.Runtime.Serialization.Formatters.Tests.DisableBitTests.EnabledThroughFeatureSwitch

Microsoft.DotNet.RemoteExecutor.RemoteExecutionException: Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
        Child exception:
Xunit.Sdk.ThrowsAnyException: Assert.ThrowsAny() Failure: No exception was thrown
Expected: typeof(System.NotSupportedException)
at System.Runtime.Serialization.Formatters.Tests.DisableBitTests.<>c.<RunRemoteTest>b__9_1() in /home/tester/runtime/src/libraries/System.Runtime.Serialization.Formatters/tests/DisableBitTests.cs:line 93
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /home/tester/runtime/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
Child process:
System.Runtime.Serialization.Formatters.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.Serialization.Formatters.Tests.DisableBitTests+<>c Void <RunRemoteTest>b__9_1()
```
```
System.Runtime.Serialization.Formatters.Tests.DisableBitTests.DisabledAlwaysInBrowser

Xunit.Sdk.ThrowsException: Assert.Throws() Failure: No exception was thrown\nExpected: typeof(System.PlatformNotSupportedException)
        at System.Runtime.Serialization.Formatters.Tests.DisableBitTests.DisabledAlwaysInBrowser() in /home/tester/runtime/src/libraries/System.Runtime.Serialization.Formatters/tests/DisableBitTests.cs:line 30
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /home/tester/runtime/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

Probably this is triggered by the changes in: https://github.com/dotnet/runtime/pull/103255.

@bartonjs do you have an idea what may be the issue?

cc @omajid

**Comment by adamsitnik** [comment]
@tmds BinaryFormatter was moved to an OOB package (not part of shared SDK) in #103255 

The code that checks whether it's enabled can be found here:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Serialization.Formatters/tests/TestConfiguration.cs
and here:
https://github.com/dotnet/runtime/blob/5c53e8ec9ca1a06a31c45936d3058fd6b1dc5961/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L728-L756

I am afraid that it's going to require some debugging to see what does not work as expected

**Comment by tmds** [comment]
@adamsitnik and @ViktorHofer (because @adamsitnik's status indicates he is unavailable).

I dug into this a bit deeper.

I have a dll that is version 8.1. According to `DetermineBinaryFormatterSupport` it should not support serialization, but according to the way the test fails, it supports serialization.

The test results are different when I run `dotnet test` against the test project. Then there are no test failures. To reproduce the issue I need to run the tests from `build.sh` using `--test` like our CI is doing.

In `xunit.console.runtimeconfig.json` I see `"System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false`. I think https://github.com/dotnet/runtime/blob/7946e6f5c102105346c3ab4b321e7a33802d8bce/src/libraries/System.Runtime.Serialization.Formatters/tests/System.Runtime.Serialization.Formatters.Tests.csproj#L74-L78 is probably meant to prevent that. It may not be working and therefore mess up the test conditions.

**Comment by ViktorHofer** [comment]
> I have a dll that is version 8.1. According to DetermineBinaryFormatterSupport it should not support serialization, but according to the way the test fails, it supports serialization.

The System.Runtime.Serialization.Formatters assembly with an 8.1.0.0 version is the one that supports serialization. The 9.0.0.0 assembly is the PNSE throwing one.

**Comment by ViktorHofer** [comment]
Oh sorry, I got this wrong. You are right, that the inbox implementation is pinned to 8.1.0.0. The OOB one has 9.0.0.0.

https://github.com/dotnet/runtime/blob/2fe4afa81e5986124a1fef91e6f35f8994b92ef7/src/libraries/System.Runtime.Serialization.Formatters/Directory.Build.targets#L5-L12
