### ISSUE TITLE
Test failure: System.Diagnostics.Metrics.Tests.MetricsTests.SerializedEventsTest

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#103882]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240622.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716976&view=ms.vss-test-web.build-test-results-tab&runId=17951422&resultId=146559&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-jitstress_random_1-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Diagnostics.Metrics.Tests.MetricsTests.SerializedEventsTest
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exit code was 134 but it should have been 42
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 242
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-06-22T18:35:18.273Z | runtime-coreclr libraries-jitstress-random | Release | ubuntu.2004.armarch.open | arm | System.Diagnostics.Metrics.Tests.MetricsTests.SerializedEventsTest | Failed | {"System.JobId":"c853aab5-8f1f-5c32-4f55-a2193507092b","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","runtimeFlavor":"coreclr","AzurePipelinesTestRunId":"17951422","System.StageAttempt":"1","DefinitionName":"runtime-coreclr   libraries-jitstress-random","System.JobName":"__default","DefinitionId":"160","architecture":"arm","BuildNumber":"20240622.1","BuildId":"716976","System.JobAttempt":"1","operatingSystem":"(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7","scenario":"jitstress_random_1","System.PhaseName":"build_linux_arm_Release_","System.PhaseAttempt":"1","configuration":"Release","Project":"public","Reason":"Schedule"} | Schedule

</body>

</html>

**Comment by JulieLeeMSFT** [comment]
Duplidate of https://github.com/dotnet/runtime/issues/103875
