### ISSUE TITLE
Test failure: System.IO.Tests.File_Move_Tests.File_Move_SynchronizingObject

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#103940]
**Failed in:** [runtime-coreclr libraries-jitstress 20240624.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717664&view=ms.vss-test-web.build-test-results-tab&runId=17978046&resultId=116267&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-disabler2r-Windows.11.Arm64.Open
    - System.IO.Tests.File_Move_Tests.File_Move_SynchronizingObject
    - System.IO.Tests.File_Changed_Tests.FileSystemWatcher_File_Changed_LastWrite
```

**Error message:**
```
 Renamed event did not occur as expected
```

**Stack trace:**
```
   at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 352
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.File_Move_Tests.File_Move_SynchronizingObject() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Move.cs:line 143
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240625.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719303&view=ms.vss-test-web.build-test-results-tab&runId=18029058&resultId=114584&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitminopts-Windows.11.Arm64.Open
    - System.IO.Tests.File_Changed_Tests.FileSystemWatcher_File_Changed_LastWrite
```

**Error message:**
```
 Changed event did not occur as expected
```

**Stack trace:**
```
   at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 317
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 168
   at System.IO.Tests.File_Changed_Tests.FileSystemWatcher_File_Changed_LastWrite() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Changed.cs:line 20
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240702.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=727164&view=ms.vss-test-web.build-test-results-tab&runId=18262880&resultId=123592&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstress1-Windows.11.Arm64.Open
    - System.IO.Tests.File_Changed_Tests.FileSystemWatcher_File_Changed_LastWrite
    - System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_ModifyAndDelete
    - System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters
```

**Error message:**
```
 Changed event did not occur as expected
```

**Stack trace:**
```
   at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 295
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.File_Changed_Tests.FileSystemWatcher_File_Changed_LastWrite() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Changed.cs:line 20
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by Jozkee** [comment]
See https://github.com/dotnet/runtime/issues/103584#issuecomment-2223174496 and https://github.com/dotnet/runtime/issues/103630#issuecomment-2223183422.
