### ISSUE TITLE
Failed test: JIT/jit64/opt/cse/VolatileTest_op_* for add, or and shr

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#103980]
Test failures in runtime-coreclr gcstress0x3-gcstress0xc pipeline.
- Failed test: JIT/jit64/opt/cse/VolatileTest_op_add/VolatileTest_op_add.cmd
- Failed test: JIT/jit64/opt/cse/VolatileTest_op_or/VolatileTest_op_or.cmd
- Failed test: JIT/jit64/opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd

```
17:17:34.475 Running test: JIT/jit64/opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd
Attempting to collect crash dump: C:\cores\crashdump_5784.dmp
Collected crash dump: C:\cores\crashdump_5784.dmp

cmdLine:C:\h\w\A78A0947\w\A88A090D\e\JIT\jit64\jit64_3\../opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/23/2024 5:17:34 PM, end: 6/23/2024 6:17:34 PM)

Return code:      -100
Raw output file:      C:\h\w\A78A0947\w\A88A090D\uploads\opt\cse\VolatileTest_op_shr\output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A78A0947\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  VolatileTest_op_shr.dll 
this test is designed to hang if jit cse doesnt honor volatile

cmdLine:C:\h\w\A78A0947\w\A88A090D\e\JIT\jit64\jit64_3\../opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/23/2024 5:17:34 PM, end: 6/23/2024 6:17:34 PM)
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> C:\h\w\A78A0947\w\A88A090D\e\JIT\jit64\jit64_3\../opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd
Xunit.Sdk.TrueException: 
cmdLine:C:\h\w\A78A0947\w\A88A090D\e\JIT\jit64\jit64_3\../opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/23/2024 5:17:34 PM, end: 6/23/2024 6:17:34 PM)

Return code:      -100
Raw output file:      C:\h\w\A78A0947\w\A88A090D\uploads\opt\cse\VolatileTest_op_shr\output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A78A0947\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  VolatileTest_op_shr.dll 
this test is designed to hang if jit cse doesnt honor volatile

cmdLine:C:\h\w\A78A0947\w\A88A090D\e\JIT\jit64\jit64_3\../opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/23/2024 5:17:34 PM, end: 6/23/2024 6:17:34 PM)
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> C:\h\w\A78A0947\w\A88A090D\e\JIT\jit64\jit64_3\../opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor139|0_140(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
18:17:44.450 Failed test: JIT/jit64/opt/cse/VolatileTest_op_shr/VolatileTest_op_shr.cmd
```

**Comment by jakobbotsch** [comment]
@JulieLeeMSFT Please attach a link to an example test failure when filing these issues, since we usually need to go get some more information from the relevant console log.

**Comment by jakobbotsch** [comment]
The test seems to be trying to verify that we don't CSE multiple volatile loads of an address. It does so by running a separate background thread that is constantly changing two values, and then verifying that at some point a loop that loads those values sees an inconsistent result in the values, caused by the background thread changing one of them.

The test quite often requires a large number of iteration before it sees the inconsistency it is looking for, so I think I am going to just mark it as GC stress incompatible.
