### ISSUE TITLE
Arm64/Sve: PrefetchBytes16 fails on InvalidInput instead of throwing `ArgumentOutOfRangeException`

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#104006]
`DOTNET_TieredCompilation=0`

```
Process terminated. Assertion failed.
Unhandled exceptions should be processed by the native runtime only
   at System.Runtime.EH.DispatchEx(StackFrameIterator& frameIter, ExInfo& exInfo)
   at System.Runtime.EH.RhThrowEx(Object exceptionObj, ExInfo& exInfo)
   at System.Runtime.Intrinsics.Arm.Sve.PrefetchInt16(Vector`1 mask, Void* address, SvePrefetchType prefetchType)
```

**Comment by kunalspathak** [comment]
@dotnet/arm64-contrib

**Comment by kunalspathak** [comment]
This most likely is from my local changes and not on `main`.
