### ISSUE TITLE
baseservices/threading/commitstackonlyasneeded/DefaultStackCommit/DefaultStackCommit.cmd timed out

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#104058]
Pipeline: [runtime-coreclr gcstress-extra](https://dev.azure.com/dnceng-public/public/_build?definitionId=113&_a=summary) / [20240625.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720410)

Failed tests:
- coreclr windows arm64 Checked gcstress0xc_disabler2r_heapverify1 @ Windows.11.Arm64.Open
- coreclr windows x64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
- Console log:[baseservices/threading/commitstackonlyasneeded/DefaultStackCommit/DefaultStackCommit.cmd](https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-312444bd190446c6b1/threading_group1.2.10/1/console.7eb137f4.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-312444bd190446c6b1/threading_group1.2.10/1/console.7eb137f4.log?helixlogtype=result))

Error message:
```
cmdLine:C:\h\w\B19209B1\w\AB2508F8\e\baseservices\threading\threading_group1\../commitstackonlyasneeded/DefaultStackCommit/DefaultStackCommit.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 6/25/2024 11:54:42 PM, end: 6/26/2024 1:24:44 AM)

Return code:      -100
Raw output file:      C:\h\w\B19209B1\w\AB2508F8\uploads\commitstackonlyasneeded\DefaultStackCommit\output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B19209B1\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  DefaultStackCommit.dll 
Main -- Base: 266e00000, Size: 1536kb
266f65000-266f80000   108kb MEM_COMMIT  active region
266f5f000-266f65000    24kb MEM_COMMIT  guard region
266e00000-266f5f000  1404kb MEM_RESERVE 

ThreadPool -- Base: 267880000, Size: 1536kb
2679ef000-267a00000    68kb MEM_COMMIT  active region
2679e9000-2679ef000    24kb MEM_COMMIT  guard region
267880000-2679e9000  1444kb MEM_RESERVE 

new Thread() -- Base: 267a00000, Size: 1536kb
267b7a000-267b80000    24kb MEM_COMMIT  active region
267b74000-267b7a000    24kb MEM_COMMIT  guard region
267a00000-267b74000  1488kb MEM_RESERVE 

Finalizer -- Base: 267700000, Size: 1536kb
267870000-267880000    64kb MEM_COMMIT  active region
26786a000-267870000    24kb MEM_COMMIT  guard region
267700000-26786a000  1448kb MEM_RESERVE 

Success!

cmdLine:C:\h\w\B19209B1\w\AB2508F8\e\baseservices\threading\threading_group1\../commitstackonlyasneeded/DefaultStackCommit/DefaultStackCommit.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 6/25/2024 11:54:42 PM, end: 6/26/2024 1:24:44 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> C:\h\w\B19209B1\w\AB2508F8\e\baseservices\threading\threading_group1\../commitstackonlyasneeded/DefaultStackCommit/DefaultStackCommit.cmd
```

Stack trace:
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor73|0_74(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by AndyAyersMS** [comment]
Has run successfully the past three weeks, so removing the blocking label. Typically finishes in under 10 seconds.

![image](https://github.com/user-attachments/assets/eecca5f1-8b9a-452e-a1a5-04ce50d427ce)
