### ISSUE TITLE
.NET 9 Arm32 tests are randomly failing from PowerShell hang

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#104106]
There have been random test jobs failing with either one of two issues: a timeout ~or a `HttpRequestException`~. I've only seen this happening in the Noble and Bookworm jobs, not Alpine.

This first popped up with this PR: https://github.com/dotnet/dotnet-docker/pull/5587. But I can't imagine it was the cause. The most recent .NET change prior to that was this: https://github.com/dotnet/dotnet-docker/pull/5584.

I've only seen this in public builds but there haven't been many internal builds yet to determine if it's only limited to public.

[Example timeout build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715249&view=results)

> [!NOTE]
The rest of the information below is not relevant to this particular issue. Keeping it here because the conversation below references it. But this error is not a pervasive error like the timeout issue is.

[Example `HttpRequestException` build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715739&view=results)

`Microsoft.DotNet.Docker.Tests.SdkImageTests.VerifyBlazorWasmScenario`

```
Executing: docker run --name 9.0-app-run-133634530996233443 -d -t -p 8080 9.0-publish_fx_dependent-133634530130912981 dotnet run --urls [http://*:8080](http://%2A:8080/)
 80fef330b2b77c6817b3479302abfbcbcfdf3eff5d94d6ff58798d5ed3ff452a
 Execution Elapsed Time: 00:00:01.4260173
 Executing: docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" 9.0-app-run-133634530996233443
 172.17.0.3
 Execution Elapsed Time: 00:00:00.0211357
 Request to http://172.17.0.3:8080/ failed - retrying: System.Net.Http.HttpRequestException: Connection refused (172.17.0.3:8080)
  ---> System.Net.Sockets.SocketException (111): Connection refused
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
    at System.Threading.ThreadPoolWorkQueue.Dispatch()
    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
 --- End of stack trace from previous location ---
    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
    at Microsoft.DotNet.Docker.Tests.WebScenario.GetHttpResponseFromContainerAsync(String containerName, DockerHelper dockerHelper, ITestOutputHelper outputHelper, Int32 containerPort, String pathAndQuery, Action`1 validateCallback, AuthenticationHeaderValue authorizationHeader) in /repo/dotnet-docker/tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs:line 96
```

**Comment by mthalman** [comment]
I've moved this to the runtime repo to investigate further.

**Comment by jkoritzinsky** [comment]
I believe I actually just fixed this with https://github.com/dotnet/runtime/pull/104126. @mthalman can you test out with a nightly build or do you need to wait until we have a preview with that fix?

**Comment by mthalman** [comment]
I ran some tests: https://github.com/dotnet/dotnet-docker/pull/5643. This succeeded 3 times in a row. Normally that would for sure have run into this issue.

**Comment by mthalman** [comment]
I'm fine with closing it.
