### ISSUE TITLE
[6.0] Failure in DnsGetHostAddresses_PostCancelledToken_Throws: No such host is known

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#104392]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=729080
Build error leg or test failing: `System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws`

## Error Message

```json
{
  "ErrorMessage" : ["DnsGetHostAddresses_PostCancelledToken_Throws [FAIL]", "No such host is known"],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/104353
- Queue: `Libraries Test Run checked coreclr windows x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=729080&view=logs&j=c05a0321-017e-5528-e1bc-b9bf377db5aa&t=08572c74-4d4f-5c01-aaf7-b500751fa1f1&l=60
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-104353-merge-8a0972bd570d4266ac/System.Net.NameResolution.Functional.Tests/1/console.107c2d36.log?helixlogtype=result
- Output:
```
    System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.OperationCanceledException)
      Actual:   typeof(System.Net.Sockets.SocketException): No such host is known.
      ---- System.Net.Sockets.SocketException : No such host is known.
      Stack Trace:
        /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs(220,0): at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs(192,0): at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs(220,0): at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs(192,0): at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
        --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=729080
**Error message validated:** `[DnsGetHostAddresses_PostCancelledToken_Throws [FAIL] No such host is known`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/3/2024 6:10:26 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by wfurt** [comment]
This one looks like infrastructure issue to me.

**Comment by akoeplinger** [comment]
Closing old 6.0 known issue, no recent hits.
