### ISSUE TITLE
[ARM][ARM64] Problems with empty struct passing

### ISSUE THREAD

**Issue by tomeksowi** [dotnet/runtime#104369]
Issue for CI failures on 32- and 64-bit ARM for the new tests introduced in #104237

I identified the issue with empty struct argument on arm32 as a bug in Clang similar to RISC-V, raised [here](https://github.com/llvm/llvm-project/issues/97285#issuecomment-2205742277].

But there are some CI failures which I cannot reproduce running in docker images:
* mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-cross-arm-net9.0
* mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-cross-arm64-net9.0

### OSX ARM 64-bit
This one has symptoms similar to the Clang bug mentioned above -- the empty struct argument was not assigned a register. I checked the [asm from Clang on ARM64 (albeit linux)](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXLnwEEAqgGdMABQAenAAy8AVhNK0mDUMgCkAJgBCZ86UX1kBPAMqN0AYVS0AriwYhTpFwAZPAZMADlvACNMYgl/AAdUeUJHBncvHz9SROSHAWDQiJZo2K5/W0x7VKECJmICdO9fcsw7PIYauoIC8KiYuJta%2BsbM8qHukN7i/rKAShtUT2Jkdg55AmJPewBqbBZ4ggBPbeMAdktTgBFjAGZLdQBBY0eQgm2mKgIYgH1MfaOIK9tnh1KRdv9jpgwUC8FxZs8nucEc8AJzETAEJYMYFcW73RHXR4IoEfL7EX4Q74Cb7rJjIADWEAR2xZwMEwNBbLesOh7Lw/i5wJuvO5ABYRcCAKwSvAANhlpzBewOkJlAA54USkUT1GiMVjgWq8cirhx5rROJLeL5uLxUJxXFYrNt5ItlpgTqYbjxSAQNGb5vSQDcbgA6EMRyNR%2BUWjii63%2B0j2ji8eQgUF%2BjiaeZwWBIND7OgxciUAvxIuxOosABuaoAtMh9IYuGquKCaLQyWmIJFE5EQnVDpwff3mMRDgB5SJaSqZn0FtiCCcMWhDrO8LCRTzAVxiWhp22kLAsAzAcTro94dFVauYA%2BaAIqSqeL7D3ivVqJ2h4SLEQfuLBEw2PAWDfUhb2ISIkkwS4/lPb9DH9eYqH0YB5AANTwTAAHcJ3iRgwP4QQRDEdhJGkQQFGUNQLx0KQmyMJ0LD0H800geZUAOVIDzrCcAC87Qg4g8CwNiIHmCoqicCAXBGXwpCCSYihKXQchSAQ5NUpJ1IYHplJmGxWlnapxk0qRJPaTp6j0vpSkGLozPs6ylNsiQJLdFY3L0S0EwvZN3mIGt6yYbZG1PbYW1DLhQ3UbYIFwQgSE9b1Zl4TNs0DYMwyjHKIxjTh41IG0H2TVN019JDSFzRAUFQQt6DICgIDLCsQCrWVRWALhRTbPg6C7ShewvUdBzAkbxynGd7DAhdGAIZdV0TTdt13Wh9zA494NWB98GvBxb3vXhMCfZAX1WH0P1jB9v1/f8MG2tLhNAw8IKgxRYJPQwENAddkNQjCsNw/CbR9IjhFEcRyLBqjVETHR/AYlAmOsG6xI4riBB4/jBJiYTRPgCSjKk3wZIYNwPCaXRFMKVypDU9pHPp1IbOmOyLJMhyKcycyics8YWZU8zTK5%2BSnImGnWa810lk8uFvI4K0isTfyHgAJQAWQ67ZgGQZAItFKKYrihKiGIZK4TSpDMpDcNcpy%2BXCuKu1ODKjMrfl0xfJKl2Kt%2B%2BYIOSJxRSAA%3D) and it looks fine. However, the stack trace doesn't point which of the calls, native or managed, failed so the problem could also be on the .NET side.
```
BEGIN EXECUTION
/tmp/helix/working/B45209B9/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true EmptyStructs.dll ''
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 0
Actual:   3
at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
at Program.Test_Empty_Sanity()
at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
```

### Linux ARM 32-bit
A crash in PackedEmptyFloatLong.Equals()
```
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/JIT/Directed/Directed_3/../StructABI/EmptyStructs/EmptyStructs.sh: line 441:   171 Bus error               (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/StructABI/EmptyStructs/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true EmptyStructs.dll ''
[createdump] Gathering state for process 171 corerun
[createdump] Crashing thread 00ab signal 7 (0007)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.171.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.171.dmp
[createdump] Written 55050240 bytes (13440 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 75ms
Expected: 100
Actual: 135
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 7/3/2024 1:07:38 PM
Processing /home/helixbot/dotnetbuild/dumps/coredump.171.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.171.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:

Thread Id: 0xab
Child SP               IP Call Site
0xffd6c310 0xf7787614 libc.so.6!
0xffd6c318 0xf77f19c0 libc.so.6!__wait4_time64
0xffd6c380 0xf768583c libcoreclr.so!PROCCreateCrashDump(std::vector<char const*, std::allocator<char const*> >&, char*, int, bool) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2308:22
0xffd6c3c8 0xf768663c libcoreclr.so!PROCCreateCrashDumpIfEnabled at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2526:9
0xffd6c418 0xf763b0de libcoreclr.so!invoke_previous_action(sigaction*, int, siginfo_t*, void*, bool) at /__w/1/s/src/coreclr/pal/src/exception/signal.cpp:422:13
0xffd6c450 0xf763a3e4 libcoreclr.so!sigbus_handler(int, siginfo_t*, void*) at /__w/1/s/src/coreclr/pal/src/exception/signal.cpp:722:1
0xffd6c470 0xf77971b0 libc.so.6!
0xffd6c7e0 0xf7289b74 libcoreclr.so!long long VolatileLoad<long long>(long long const*) at /__w/1/s/src/coreclr/inc/volatile.h:188:13
(inlined by) FieldDesc::GetInstanceField(OBJECTREF, void*) at /__w/1/s/src/coreclr/vm/field.cpp:315:28
0xffd6c830 0xf73bb0da libcoreclr.so!InvokeUtil::GetFieldValue(FieldDesc*, TypeHandle, OBJECTREF*, TypeHandle, bool*) at /__w/1/s/src/coreclr/vm/invokeutil.cpp:0:21
0xffd6c8c8 0xf74131d2 libcoreclr.so!RuntimeFieldHandle::GetValue(ReflectFieldObject*, Object*, ReflectClassBaseObject*, ReflectClassBaseObject*, bool*) at /__w/1/s/src/coreclr/vm/reflectioninvocation.cpp:58:8
0xffd6c9e8 0xeed24ee2 System.Reflection.FieldAccessor.GetValue(System.Object)
0xffd6ca10 0xeeb20296 System.ValueType.Equals(System.Object)
0xffd6ca60 0xedd5644e Xunit.Sdk.AssertEqualityComparer1[[Program+PackedEmptyFloatLong, EmptyStructs]].Equals(PackedEmptyFloatLong, Xunit.Sdk.CollectionTracker, PackedEmptyFloatLong, Xunit.Sdk.CollectionTracker, System.Nullable1<Int32> ByRef)
0xffd6caa8 0xedd56214 Xunit.Sdk.AssertEqualityComparer1[[Program+PackedEmptyFloatLong, EmptyStructs]].Equals(PackedEmptyFloatLong, PackedEmptyFloatLong)  0xffd6cb00 0xedd55ac8 Xunit.Assert.Equal[[Program+PackedEmptyFloatLong, EmptyStructs]](PackedEmptyFloatLong, PackedEmptyFloatLong, System.Collections.Generic.IEqualityComparer1<PackedEmptyFloatLong>)
0xffd6cba0 0xedd557ca 0xedd557ca
0xffd6cc40 0xf5ea11bc __GeneratedMainWrapper.Main()

Thread Id: 0xac
Child SP               IP Call Site
0xf708ebd0 0xf7787614 libc.so.6!
0xf708ebd8 0xf7812f44 libc.so.6!poll
0xf708ebe8 0xf767b940 libcoreclr.so!CorUnix::CPalSynchronizat
```

### Linux ARM 64-bit
This log has the least useful information, console logs just say timeout:
```
13:20:55.641 Running test: JIT/Directed/StructABI/EmptyStructs/EmptyStructs.cmd
Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/coredump.159.dmp.crashreport.json
stdout: -rw------- 1 helixbot2 adm 18100 Jul  3 13:20 /home/helixbot/dotnetbuild/dumps/coredump.159.dmp.crashreport.json

=========================================
Child process took too long. Timed out... Exiting...
App Exit Code: 110
Expected: 100
Actual: 110
END EXECUTION - FAILED
```

Part of #84834

**Comment by JulieLeeMSFT** [comment]
cc @jakobbotsch.

**Comment by jakobbotsch** [comment]
I will move this to .NET 11 since this isn't a regression.
