### ISSUE TITLE
wasm-test-browser Connection refused in 127.0.0.1

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#104349]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728515
Build error leg or test failing: `browser-wasm linux Release WasmBuildTests`

## Error Message

```json
{
  "ErrorMessage" : "[wasm test-browser] Connection refused",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR (unrelated to the failure): https://github.com/dotnet/runtime/pull/102403
- Queue: `browser-wasm linux Release WasmBuildTests`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728515&view=logs&j=1fa93050-f528-55d3-a351-f8bf9ce5adbf&t=a9f1a437-3b59-5900-1137-ec6cae9a530c
- Log file: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-102403-merge-5519bcefeaed444f94/Workloads-NoWebcil-ST-Wasm.Build.Tests.BuildPublishTests/1/console.05156025.log?helixlogtype=result

<details><summary>Output (expand)</summary>

```
[wasm test-browser] [9.0.0-prerelease.24317.3+65d0584b517952962b7a79195b5d7606b52fcbfe] XHarness command issued: wasm test-browser --app=. --output-directory=/root/helix/work/workitem/uploads/xharness-output/logs/j0lhm4ui_bff/Chrome --expected-exit-code=42 -v trace -b Chrome --locale=en-US --web-server-use-cop --browser-path=/root/helix/work/correlation/chrome-linux/chrome --browser-arg=--no-sandbox -- --setenv=XHARNESS_DISABLE_COLORED_OUTPUT=true --setenv=DOTNET_ROOT=/root/helix/work/workitem/e/dotnet-latest --setenv=DOTNET_INSTALL_DIR=/root/helix/work/workitem/e/dotnet-latest --setenv=DOTNET_MULTILEVEL_LOOKUP=0 --setenv=DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 --setenv=EM_WORKAROUND_PYTHON_BUG_34780=1 --setenv=WasmEnableWebCil=false --run build_publish_Release_鿀蜒枛遫䡫煉.dll
[wasm test-browser] [01:21:37] info: Using Chrome from /root/helix/work/correlation/chrome-linux/chrome
[wasm test-browser] [01:21:37] info: Starting chromedriver with args: --no-sandbox --headless --incognito --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --enable-features=NetworkService,NetworkServiceInProcess --allow-insecure-localhost --disable-breakpad --disable-component-extensions-with-background-pages --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-ipc-flooding-protection --force-color-profile=srgb --metrics-recording-only --no-sandbox
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
...
...
...
...
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] ChromeDriver was started successfully.
[wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
[wasm test-browser] [01:21:53] dbug: Opening in browser: http://127.0.0.1:41599/index.html?arg=--setenv%3dXHARNESS_DISABLE_COLORED_OUTPUT%3dtrue&arg=--setenv%3dDOTNET_ROOT%3d%2froot%2fhelix%2fwork%2fworkitem%2fe%2fdotnet-latest&arg=--setenv%3dDOTNET_INSTALL_DIR%3d%2froot%2fhelix%2fwork%2fworkitem%2fe%2fdotnet-latest&arg=--setenv%3dDOTNET_MULTILEVEL_LOOKUP%3d0&arg=--setenv%3dDOTNET_SKIP_FIRST_TIME_EXPERIENCE%3d1&arg=--setenv%3dEM_WORKAROUND_PYTHON_BUG_34780%3d1&arg=--setenv%3dWasmEnableWebCil%3dfalse&arg=--run&arg=build_publish_Release_%e9%bf%80%e8%9c%92%e6%9e%9b%e9%81%ab%e4%a1%ab%e7%85%89.dll&arg=-verbosity&arg=Debug
[wasm test-browser] [01:21:53] fail: [out of order message from the browser]: http://127.0.0.1:41599/runArgs.json - Failed to load resource: the server responded with a status of 404 (Not Found)
[wasm test-browser] [01:21:53] info: Running in: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/126.0.6478.0 Safari/537.36
[wasm test-browser] [01:21:53] info: Running at: http://127.0.0.1:41599/index.html?arg=--setenv%3dXHARNESS_DISABLE_COLORED_OUTPUT%3dtrue&arg=--setenv%3dDOTNET_ROOT%3d%2froot%2fhelix%2fwork%2fworkitem%2fe%2fdotnet-latest&arg=--setenv%3dDOTNET_INSTALL_DIR%3d%2froot%2fhelix%2fwork%2fworkitem%2fe%2fdotnet-latest&arg=--setenv%3dDOTNET_MULTILEVEL_LOOKUP%3d0&arg=--setenv%3dDOTNET_SKIP_FIRST_TIME_EXPERIENCE%3d1&arg=--setenv%3dEM_WORKAROUND_PYTHON_BUG_34780%3d1&arg=--setenv%3dWasmEnableWebCil%3dfalse&arg=--run&arg=build_publish_Release_%e9%bf%80%e8%9c%92%e6%9e%9b%e9%81%ab%e4%a1%ab%e7%85%89.dll&arg=-verbosity&arg=Debug
[wasm test-browser] [01:21:53] info: could not load /runArgs.json: 404. Ignoring
[wasm test-browser] [01:21:53] info: Incoming arguments: --setenv=XHARNESS_DISABLE_COLORED_OUTPUT=true --setenv=DOTNET_ROOT=/root/helix/work/workitem/e/dotnet-latest --setenv=DOTNET_INSTALL_DIR=/root/helix/work/workitem/e/dotnet-latest --setenv=DOTNET_MULTILEVEL_LOOKUP=0 --setenv=DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 --setenv=EM_WORKAROUND_PYTHON_BUG_34780=1 --setenv=WasmEnableWebCil=false --run build_publish_Release_鿀蜒枛遫䡫煉.dll -verbosity Debug
[wasm test-browser] [01:21:53] info: Application arguments: --run build_publish_Release_鿀蜒枛遫䡫煉.dll -verbosity Debug
[wasm test-browser] [01:21:55] info: Initializing dotnet version 9.0.0-ci commit hash 80f20f07bd83fd39b42dccb42ffafcc668f01579
[wasm test-browser] [01:21:55] info: test-main.js exiting build_publish_Release_鿀蜒枛遫䡫煉.dll -verbosity with result 42
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:03:59
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:05:59
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:07:59
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:09:59
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:11:59
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:13:59
-- exception -- System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Diagnostics.Process.WaitForExitAsync(CancellationToken cancellationToken)
   at Wasm.Build.Tests.BuildTestBase.RunProcessAsync(String path, ITestOutputHelper _testOutput, String args, IDictionary`2 envVars, String workingDir, String label, Nullable`1 timeoutMs) in /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs:line 505
    Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, host: Chrome, id: "j0lhm4ui_bff") [FAIL]
      System.AggregateException : One or more errors occurred. (A task was canceled.)
      ---- System.Threading.Tasks.TaskCanceledException : A task was canceled.
      Stack Trace:
           at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.Wait()
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(433,0): at Wasm.Build.Tests.BuildTestBase.RunProcess(String path, ITestOutputHelper _testOutput, String args, IDictionary`2 envVars, String workingDir, String label, Nullable`1 timeoutMs)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(298,0): at Wasm.Build.Tests.BuildTestBase.RunWithXHarness(String testCommand, String testLogPath, String projectName, String bundleDir, ITestOutputHelper _testOutput, IDictionary`2 envVars, Int32 expectedAppExitCode, Int32 xharnessExitCode, String extraXHarnessArgs, String appArgs, String extraXHarnessMonoArgs, Boolean useWasmConsoleOutput)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(219,0): at Wasm.Build.Tests.BuildTestBase.RunAndTestWasmApp(BuildArgs buildArgs, RunHost host, String id, Action`1 test, String buildDir, String bundleDir, Int32 expectedExitCode, String args, Dictionary`2 envVars, String targetFramework, String extraXHarnessMonoArgs, String extraXHarnessArgs, String jsRelativePath, String environmentLocale)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildPublishTests.cs(151,0): at Wasm.Build.Tests.BuildPublishTests.<>c__DisplayClass2_0.<BuildThenPublishWithAOT>g__Run|3(Boolean expectAOT)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildPublishTests.cs(105,0): at Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT(BuildArgs buildArgs, RunHost host, String id)
        
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
           at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
           at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.Wait()
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(433,0): at Wasm.Build.Tests.BuildTestBase.RunProcess(String path, ITestOutputHelper _testOutput, String args, IDictionary`2 envVars, String workingDir, String label, Nullable`1 timeoutMs)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(298,0): at Wasm.Build.Tests.BuildTestBase.RunWithXHarness(String testCommand, String testLogPath, String projectName, String bundleDir, ITestOutputHelper _testOutput, IDictionary`2 envVars, Int32 expectedAppExitCode, Int32 xharnessExitCode, String extraXHarnessArgs, String appArgs, String extraXHarnessMonoArgs, Boolean useWasmConsoleOutput)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(219,0): at Wasm.Build.Tests.BuildTestBase.RunAndTestWasmApp(BuildArgs buildArgs, RunHost host, String id, Action`1 test, String buildDir, String bundleDir, Int32 expectedExitCode, String args, Dictionary`2 envVars, String targetFramework, String extraXHarnessMonoArgs, String extraXHarnessArgs, String jsRelativePath, String environmentLocale)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildPublishTests.cs(151,0): at Wasm.Build.Tests.BuildPublishTests.<>c__DisplayClass2_0.<BuildThenPublishWithAOT>g__Run|3(Boolean expectAOT)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildPublishTests.cs(105,0): at Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT(BuildArgs buildArgs, RunHost host, String id)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at System.Threading.Tasks.Task`1.InnerInvoke()
           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
           at System.Threading.ThreadPoolWorkQueue.Dispatch()
           at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
        --- End of stack trace from previous location ---
        
      Output:
        
        ** -------- build -------- **
        
        Binlog path: /root/helix/work/workitem/uploads/xharness-output/logs/j0lhm4ui_bff/j0lhm4ui_bff-first_build-build.binlog
        [] Executing (Captured Output) - /root/helix/work/workitem/e/dotnet-latest/dotnet build -bl:/root/helix/work/workitem/uploads/xharness-output/logs/j0lhm4ui_bff/j0lhm4ui_bff-first_build-build.binlog -p:Configuration=Release -nr:false   -  in pwd /root/helix/work/workitem/e/wbt artifacts/j0lhm4ui_bff
        	[DOTNET_ROOT] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_INSTALL_DIR] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /root/helix/work/workitem/e/dotnet-latest:/__w/1/s/artifacts/bin/geckodriver/geckodriver:/root/helix/work/correlation/dotnet-latest:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        	[WasmEnableWebCil] = false
        	[NUGET_PACKAGES] = /root/helix/work/workitem/e/wbt artifacts/nuget/j0lhm4ui_bff
        	[ForceNet8Current] = false
        []   Determining projects to restore...
        []   Restored /root/helix/work/workitem/e/wbt artifacts/j0lhm4ui_bff/build_publish_Release_鿀蜒枛遫䡫煉.csproj (in 1.42 sec).
        [] /root/helix/work/workitem/e/dotnet-latest/sdk/9.0.100-preview.7.24323.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(326,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/helix/work/workitem/e/wbt artifacts/j0lhm4ui_bff/build_publish_Release_鿀蜒枛遫䡫煉.csproj]
        []   build_publish_Release_鿀蜒枛遫䡫煉 -> /root/helix/work/workitem/e/wbt artifacts/j0lhm4ui_bff/bin/Release/net9.0/browser-wasm/build_publish_Release_鿀蜒枛遫䡫煉.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/9.0.0-ci'
        []   Generated app bundle at /root/helix/work/workitem/e/wbt artifacts/j0lhm4ui_bff/bin/Release/net9.0/browser-wasm/AppBundle/
        [] 
        [] Build succeeded.
        []     0 Warning(s)
        []     0 Error(s)
        [] 
        [] Time Elapsed 00:00:13.47
        [] 
        [] Workload updates are available. Run `dotnet workload list` for more information.
        Skipping asserting symbols file
        ============== wasm test-browser =============
        
        ---------- Running with wasm test-browser ---------
        Running /root/helix/work/workitem/e/dotnet-latest/dotnet /root/helix/work/correlation/microsoft.dotnet.xharness.cli/9.0.0-prerelease.24317.3/tools/net8.0/any/Microsoft.DotNet.XHarness.CLI.dll wasm test-browser --app=. --output-directory=/root/helix/work/workitem/uploads/xharness-output/logs/j0lhm4ui_bff/Chrome --expected-exit-code=42  -v trace -b Chrome --locale=en-US --web-server-use-cop  --browser-path="/root/helix/work/correlation/chrome-linux/chrome" --browser-arg=--no-sandbox --  "--setenv=XHARNESS_DISABLE_COLORED_OUTPUT=true" "--setenv=DOTNET_ROOT=/root/helix/work/workitem/e/dotnet-latest" "--setenv=DOTNET_INSTALL_DIR=/root/helix/work/workitem/e/dotnet-latest" "--setenv=DOTNET_MULTILEVEL_LOOKUP=0" "--setenv=DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1" "--setenv=EM_WORKAROUND_PYTHON_BUG_34780=1" "--setenv=WasmEnableWebCil=false" --run build_publish_Release_鿀蜒枛遫䡫煉.dll 
        WorkingDirectory: /root/helix/work/workitem/e/wbt artifacts/j0lhm4ui_bff/bin/Release/net9.0/browser-wasm/AppBundle
        Setting environment variables for execution:
        	XHARNESS_DISABLE_COLORED_OUTPUT = true
        	DOTNET_ROOT = /root/helix/work/workitem/e/dotnet-latest
        	DOTNET_INSTALL_DIR = /root/helix/work/workitem/e/dotnet-latest
        	DOTNET_MULTILEVEL_LOOKUP = 0
        	DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 1
        	PATH = /root/helix/work/workitem/e/dotnet-latest:/__w/1/s/artifacts/bin/geckodriver/geckodriver:/root/helix/work/correlation/dotnet-latest:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	EM_WORKAROUND_PYTHON_BUG_34780 = 1
        	WasmEnableWebCil = false
        [wasm test-browser] [9.0.0-prerelease.24317.3+65d0584b517952962b7a79195b5d7606b52fcbfe] XHarness command issued: wasm test-browser --app=. --output-directory=/root/helix/work/workitem/uploads/xharness-output/logs/j0lhm4ui_bff/Chrome --expected-exit-code=42 -v trace -b Chrome --locale=en-US --web-server-use-cop --browser-path=/root/helix/work/correlation/chrome-linux/chrome --browser-arg=--no-sandbox -- --setenv=XHARNESS_DISABLE_COLORED_OUTPUT=true --setenv=DOTNET_ROOT=/root/helix/work/workitem/e/dotnet-latest --setenv=DOTNET_INSTALL_DIR=/root/helix/work/workitem/e/dotnet-latest --setenv=DOTNET_MULTILEVEL_LOOKUP=0 --setenv=DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 --setenv=EM_WORKAROUND_PYTHON_BUG_34780=1 --setenv=WasmEnableWebCil=false --run build_publish_Release_鿀蜒枛遫䡫煉.dll
        [wasm test-browser] [01:21:37] info: Using Chrome from /root/helix/work/correlation/chrome-linux/chrome
        [wasm test-browser] [01:21:37] info: Starting chromedriver with args: --no-sandbox --headless --incognito --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --enable-features=NetworkService,NetworkServiceInProcess --allow-insecure-localhost --disable-breakpad --disable-component-extensions-with-background-pages --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-ipc-flooding-protection --force-color-profile=srgb --metrics-recording-only --no-sandbox
        [wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
        [wasm test-browser] Connection refused [::ffff:127.0.0.1]:40349 (localhost:40349)
```
</details>

**Comment by lewing** [comment]
cc @ilonatommy

**Comment by pavelsavara** [comment]
I think this is just slow helix machine. It usually recovers from it eventually.

**Comment by carlossanlop** [comment]
Should we set BuildRetry to true?

**Comment by pavelsavara** [comment]
> Should we set BuildRetry to true?

Good idea. I wonder if we could somehow detect re-run like that and eventually enable more logging. Does CI set some env variable ?

**Comment by carlossanlop** [comment]
That's a great question for which I don't have an answer. @AlitzelMendez is it possible to detect that a CI run was triggered a second time due to `BuildRetry` being set to `true`?

**Comment by pavelsavara** [comment]
This is kind of "catch all" filter and it was hiding https://github.com/dotnet/runtime/issues/108175 and maybe more.

**Comment by pavelsavara** [comment]
this is misleading filter
