### ISSUE TITLE
[runtime-extra-platforms] tvos arm64 mono net.dot.JIT_Directed application failing with DllNotFoundException: EmptyStructsLib

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#104348]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728775
Build error leg or test failing: `net.dot.JIT_Directed`

## Error Message

```json
{
  "ErrorPattern" : "Detected exit code 101 from *net\\.dot\\.JIT_Directed\\.log",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR (unrelated to failure): https://github.com/dotnet/runtime/pull/102403
- Queue: `tvos-arm64 Release AllSubsets_Mono_RuntimeTests`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728775&view=logs&j=28c2a171-0c43-5d2a-7ef1-2d2cea8331ba&t=3df1997a-11aa-5246-c452-91536bb3018b
- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728775&view=ms.vss-test-web.build-test-results-tab&runId=18318146&resultId=100025&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
- The [helix log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-102403-merge-2210ca523eba4be4be/JIT_Directed/1/console.d10782d3.log?helixlogtype=result) indicates the mlaunch process returned error 101 and the log containing the error is called [net.dot.JIT_Directed.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-102403-merge-2210ca523eba4be4be/JIT_Directed/1/net.dot.JIT_Directed.log?helixlogtype=result).
- Output:
```
[00:15:38.1299010] 2024-07-03 00:15:38.129 mlaunch[38352:1679055] .NET ThreadPool Worker DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot7/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-21779/DVTFoundation/DeveloperStructure/DVTExtendedPlatformInfo.m:79
[00:15:38.1299070] Details:  DVTExtendedPlatformInfo: Synthesized iphoneos Extended Platform Info because no plugin existed to provide it or that plugin was not loaded
[00:15:38.1299120] Object:   <DVTExtendedPlatformInfo>
[00:15:38.1299160] Method:   +extendedPlatformInfoForPlatformIdentifier:error:
[00:15:38.1299200] Thread:   <NSThread: 0x6000004e2740>{number = 9, name = (null)}
[00:15:38.1299330] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[00:15:38.8985620] Xamarin.Hosting: Launched net.dot.JIT_Directed with PID: 35194
[00:15:38.8990820] Launched application 'net.dot.JIT_Directed' on 'DNCENGTVOS-026' with pid 35194
[00:15:39.1148410] 2024-07-02 21:15:39.206 JIT_Directed[35194:73496952] System.DllNotFoundException: EmptyStructsLib
[00:15:39.1148740]    at Program.TestIntEmptySysV()
[00:15:39.1148800]    at __GeneratedMainWrapper.Main()
[00:15:39.1244190] Xamarin.Hosting: Process '35194' exited with exit code 101 or crashing signal .
[00:15:39.1251630] Application 'net.dot.JIT_Directed' terminated (with exit code '101' and/or crashing signal ').
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=728775
**Error message validated:** `[Detected exit code 101 from *net\.dot\.JIT_Directed\.log`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/3/2024 6:07:21 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by matouskozak** [comment]
Test has been disabled (https://github.com/dotnet/runtime/issues/104430)
