### ISSUE TITLE
Unable to resolve type: Microsoft.Extensions.Hosting.IHostApplicationLifetime

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#104372]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-resolve-type:-MicrosoftExtens/10679003)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.9]
I updated my visual studio from 17.9 to 17.10.1. Without changing anything to the dotnet code, the api won't start anymore and gives an exception in the program.cs file on the code rule:

```
var app = builder.Build();
```
Note: we are using Lightinject for depencency injection.

Callstack:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve type: Microsoft.Extensions.Hosting.IHostApplicationLifetime, service name: 
  Source=LightInject
  StackTrace:
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
   at LightInject.ServiceContainer.GetInstance(Type serviceType, Scope scope)
   at LightInject.Scope.GetInstance(Type serviceType)
   at LightInject.Microsoft.DependencyInjection.LightInjectServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.HostBuilder.<>c__DisplayClass35_0.<PopulateServiceCollection>b__2(IServiceProvider _)
   at LightInject.Microsoft.DependencyInjection.DependencyInjectionContainerExtensions.<>c__DisplayClass10_0`1.<CreateTypedFactoryDelegate>b__0(IServiceFactory serviceFactory)
   at LightInject.Microsoft.DependencyInjection.PerRootScopeLifetime.GetInstance(GetInstanceDelegate createInstance, Scope scope, Object[] arguments)
   at LightInject.ServiceContainer.GetInstance(Type serviceType, Scope scope)
   at LightInject.Scope.GetInstance(Type serviceType)
   at LightInject.Microsoft.DependencyInjection.LightInjectServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Projects\Interreg\Eloket\Interreg.Eloket.Web.Api\Program.cs:line 40

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Hosting.Internal.ApplicationLifetime], [Parameter: logger(Microsoft.Extensions.Logging.ILogger`1[Microsoft.Extensions.Hosting.Internal.ApplicationLifetime])], [Requested dependency: ServiceType:Microsoft.Extensions.Logging.ILogger`1[Microsoft.Extensions.Hosting.Internal.ApplicationLifetime], ServiceName:]

Inner Exception 2:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Logging.Logger`1[Microsoft.Extensions.Hosting.Internal.ApplicationLifetime]], [Parameter: factory(Microsoft.Extensions.Logging.ILoggerFactory)], [Requested dependency: ServiceType:Microsoft.Extensions.Logging.ILoggerFactory, ServiceName:]

Inner Exception 3:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Logging.LoggerFactory], [Parameter: providers(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider])], [Requested dependency: ServiceType:System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], ServiceName:]

Inner Exception 4:
InvalidOperationException: Unresolved dependency [Target Type: <>z__ReadOnlySingleElementList`1[Microsoft.Extensions.Logging.ILoggerProvider]], [Parameter: item(Microsoft.Extensions.Logging.ILoggerProvider)], [Requested dependency: ServiceType:Microsoft.Extensions.Logging.ILoggerProvider, ServiceName:]

Inner Exception 5:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider], [Parameter: telemetryConfigurationOptions(Microsoft.Extensions.Options.IOptions`1[Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration])], [Requested dependency: ServiceType:Microsoft.Extensions.Options.IOptions`1[Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration], ServiceName:]

Inner Exception 6:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.DependencyInjection.TelemetryConfigurationOptions], [Parameter: applicationInsightsServiceOptions(Microsoft.Extensions.Options.IOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions])], [Requested dependency: ServiceType:Microsoft.Extensions.Options.IOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions], ServiceName:]

Inner Exception 7:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Options.UnnamedOptionsManager`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions]], [Parameter: factory(Microsoft.Extensions.Options.IOptionsFactory`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions])], [Requested dependency: ServiceType:Microsoft.Extensions.Options.IOptionsFactory`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions], ServiceName:]

Inner Exception 8:
InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Options.OptionsFactory`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions]], [Parameter: postConfigures(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions]])], [Requested dependency: ServiceType:System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions]], ServiceName:]

Inner Exception 9:
InvalidOperationException: Unresolved dependency [Target Type: <>z__ReadOnlySingleElementList`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions]]], [Parameter: item(Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions])], [Requested dependency: ServiceType:Microsoft.Extensions.Options.IPostConfigureOptions`1[Microsoft.ApplicationInsights.AspNetCore.Extensions.ApplicationInsightsServiceOptions], ServiceName:]

```

---
#### Arnaud Boussaer on 6/10/2024, 06:31 AM: 

(private comment, text removed)
#### Feedback Bot on 6/10/2024, 11:12 PM: 

(private comment, text removed)

---
#### Constantine Nevostruev solved on 6/19/2024, 08:37 AM, 0 votes: 

<p>The problem is with <code>z__ReadOnlySingleElementList</code> which is embedded into your assembly at compile time. As far as I understand, it is used for the new style of array initialization like <code>var nums = [5]</code>. Seems you are using automatic type registration to their implemented interfaces which register <code>z__ReadOnlySingleElementList&lt;&gt;</code> to <code>IEnumerable&lt;&gt;</code>. Then the container tries to use <code>z__ReadOnlySingleElementList&lt;&gt;</code> in the cases where it needs to collect all implementations of an interface.</p>
<p>You can, for instance, filter out all the types that implement <code>IEnumerable</code>. Example using Autofac:</p>
<pre><code>containerBuilder
    . RegisterAssemblyOpenGenericTypes(assemblies)
    . Where(<span class="hljs-function"><span class="hljs-params">x</span> =&gt;</span> !x.IsAssignableTo(<span class="hljs-keyword">typeof</span>(IEnumerable)))
    . AsImplementedInterfaces()
    . AsSelf();
</code></pre>

**Comment by steveharter** [comment]
The "Solution" above mentioned:
- `z__ReadOnlySingleElementList` is added by Roslyn now
- That type is being picked up by a call to `RegisterAssemblyOpenGenericTypes()` (from Lightinject \ Autofac)
- Workaround is to filter the types before calling `RegisterAssemblyOpenGenericTypes`

Keeping open for a few days before closing. We don't have a github user name for the author since it was ported.

**Comment by ArnaudB88** [comment]
Hi @steveharter , I am the author of the developercommunity post.

I am using LightInject 6.6.4 as a DI container.
Auto registrations are done with the method `Container.RegisterAssembly(assembly)`

I tried the suggestion to exclude types which implement IEnumerable, but this results in a lot of unregisterd types. The code I tried is:
```
Container.RegisterAssembly(assembly, shouldRegister: (Type serviceType, Type implementingType) =>
{
    return !serviceType.IsAssignableTo(typeof(IEnumerable)) && !implementingType.IsAssignableTo(typeof(IEnumerable));

    //I also tried (with the same result):
    //return serviceType != typeof(IEnumerable) && implementingType != typeof(IEnumerable);
});
```

I created a linked ticket in the repository of lightinject: https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/issues/209
It seems Autofac users also have issues: https://github.com/autofac/Autofac/issues/1408#issuecomment-2117105117

**Comment by ArnaudB88** [comment]
I managed to find registrations which are assignable to the interface `IEnumerable<>`. Below are all the combinations which were registerd with LightInject in my project.

Found with ` r.ServiceType.IsAssignableTo(typeof(IEnumerable<>))`
```
"ServiceType:System.Collections.Generic.IEnumerable`1; ImplementingType:<>z__ReadOnlyArray`1"
"ServiceType:System.Collections.Generic.IEnumerable`1; ImplementingType:<>z__ReadOnlySingleElementList`1"
```

Found with `IsAssignableToGenericInterface` (see https://github.com/autofac/Autofac/issues/1408#issuecomment-2271467996)
```
"ServiceType:System.Collections.Generic.IReadOnlyList`1; ImplementingType:<>z__ReadOnlySingleElementList`1"
"ServiceType:System.Collections.Generic.IReadOnlyList`1; ImplementingType:<>z__ReadOnlyArray`1"
"ServiceType:System.Collections.Generic.IReadOnlyCollection`1; ImplementingType:<>z__ReadOnlySingleElementList`1"
"ServiceType:System.Collections.Generic.IReadOnlyCollection`1; ImplementingType:<>z__ReadOnlyArray`1"
"ServiceType:System.Collections.Generic.IList`1; ImplementingType:<>z__ReadOnlySingleElementList`1"
"ServiceType:System.Collections.Generic.IList`1; ImplementingType:<>z__ReadOnlyArray`1"
"ServiceType:System.Collections.Generic.ICollection`1; ImplementingType:<>z__ReadOnlySingleElementList`1"
"ServiceType:System.Collections.Generic.ICollection`1; ImplementingType:<>z__ReadOnlyArray`1"
"ServiceType:<>z__ReadOnlySingleElementList`1; ImplementingType:<>z__ReadOnlySingleElementList`1"
"ServiceType:<>z__ReadOnlyArray`1; ImplementingType:<>z__ReadOnlyArray`1"
```

Is it possible that those types should be marked as compiler generated (but currently aren't)?
When marked, DI containers will filter those types out of the autoregistration.

**Comment by ArnaudB88** [comment]
Seems like the bug is resolved:
https://github.com/dotnet/roslyn/issues/74676
