### ISSUE TITLE
ILCompiler.Compiler.Tests.SwiftLoweringTests.VerifyLowering failing with preivew 6

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#104765]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=737461
Build error leg or test failing: ILCompiler.Compiler.Tests.SwiftLoweringTests.VerifyLowering
Pull request: https://github.com/dotnet/runtime/pull/104696

## Error Message

```
    Assert.Equal() Failure: Exception thrown during comparison
Expected: {CORINFO_TYPE_LONG: 0, CORINFO_TYPE_DOUBLE: 8, CORINFO_TYPE_LONG: 16, CORINFO_TYPE_SHORT: 24}
Actual:   {CORINFO_TYPE_LONG: 0, CORINFO_TYPE_DOUBLE: 8, CORINFO_TYPE_LONG: 16, CORINFO_TYPE_SHORT: 24}
---- System.NotSupportedException : Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid.

   at ILCompiler.Compiler.Tests.SwiftLoweringTests.VerifyLowering(String typeName, EcmaType type, CORINFO_SWIFT_LOWERING expectedLowering) in /_/src/coreclr/tools/aot/ILCompiler.Compiler.Tests/SwiftLoweringTests.cs:line 106
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

----- Inner Stack Trace -----
at System.ValueType.CanCompareBitsOrUseFastGetHashCode(MethodTable* pMT)
at System.ValueType.Equals(Object obj)
at System.ValueType.Equals(Object obj)
```

```json
{
  "ErrorMessage": "Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=737461
**Error message validated:** `[Calling built-in Equals() or GetHashCode() on type marked as InlineArray is invalid`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/11/2024 10:27:03 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MichalStrehovsky** [comment]
Cc @jkoritzinsky, looks like the test is trying to compare two InlineArrays using the built-in valuetype equality. This just silently didn't work in the past but now it throws.
