### ISSUE TITLE
Misleading error message when trying to deserialize JSON into a collection property without a getter

### ISSUE THREAD

**Issue by ezhevita** [dotnet/runtime#104700]
### Description

When trying to deserialize a JSON string into a class containing a property with a collection type (`Dictionary` or `IEnumerable`) serializer throws an exception which says about a property missing a setter despite it being present.

### Reproduction Steps

```csharp
JsonSerializer.Deserialize<Test>("{\"Data\":[1]}");

public class Test
{
    [JsonRequired]
    public List<int> Data
    {
        set => FirstValue = value[0];
    }
    
    [JsonIgnore]
    public int FirstValue { get; private set; }
}
```

### Expected behavior

Either:
- JSON is deserialized correctly;
- Error message says exactly what the problem is and doesn’t mislead a user

### Actual behavior

The following exception is thrown:
```
System.InvalidOperationException: JsonPropertyInfo 'Data' defined in type 'Test' is marked required but does not specify a setter.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonPropertyRequiredAndNotDeserializable(JsonPropertyInfo jsonPropertyInfo)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at Program.<Main>$(String[] args)
```

### Regression?

No, this behavior is present at least since .NET 7 when required properties were introduced.

### Known Workarounds

Adding a getter to the property, it may return null or just outright throw an exception.

### Configuration

.NET 8.0.6 running on macOS 14.5 ARM64; issue is not specific to the configuration.

### Other information

Similar to (although different scenarios): https://github.com/dotnet/runtime/issues/92330

**Comment by eiriktsarpalis** [comment]
I can reproduce, thanks. One workaround is to specify a getter it seems.

**Comment by julien98Qc** [comment]
Indeed, in `DetermineSerializationCapabilities()`, `CanDeserialize` is set to false when an Enumerable or Dictionary has no getter. In `Configure()`, we trigger the exception based on IsRequired and CanDeserialize. The exception message assumes it is a setter problem, but that is not always the case.

The resolution might be one of the following:
- Add another verification that throws a separate error for this specific case.
- Change the exception message to a more generic one.

**Comment by julien98Qc** [comment]
@eiriktsarpalis Just wanted to let you know that I've made a PR for this issue.

**Comment by julien98Qc** [comment]
The issue is not about a misleading error message anymore but to make it work when required and no getter specified.

See this comment below for more context : https://github.com/dotnet/runtime/pull/104861#pullrequestreview-2204684810

**Comment by ezhevita** [comment]
I've updated the issue title to reflect that the expected solution is making this scenario work.

**Comment by devsko** [comment]
> I don't think this is the correct way to address the problem. A fix should instead try to make the scenario work as expected. If you remove JsonRequired from the repro in #104700 then deserialization works as expected and this should too.

@eiriktsarpalis are you aware that the setter is not called even when `[JsonRequired]` is removed. No exception but still unexpected.

The following
- Throws `InvalidOperationException` with `[JsonRequired]` and  without getter
- Prints '0' without `[JsonRequired]` and without getter
- Prints '1' with getter (even though it is never called)

``` cs
Console.WriteLine(JsonSerializer.Deserialize<Test>("{\"Data\":[1]}")?.FirstValue);

public class Test
{
    //[JsonRequired]
    public List<int> Data
    {
        //get => throw new Exception();
        set => FirstValue = value[0]; // Is NOT called as long as no getter is declared
    }

    [JsonIgnore]
    public int FirstValue { get; private set; }
}
```

**Comment by ShawnWu33** [comment]
Hi I am trying to have a look into this one as got some time in upcoming days.

Upon shallow investigation, in `DetermineSerializationCapabilities()`there is following logics:
```
if ((EffectiveConverter.ConverterStrategy & (ConverterStrategy.Enumerable | ConverterStrategy.Dictionary)) != 0)
            {
                // Properties of collections types that only have setters are not supported.
                if (Get == null && Set != null && !_isUserSpecifiedSetter)
                {
                    CanDeserialize = false;
                }
            }
```
The comment there saying `Properties of collections types that only have setters are not supported.` is added for fixing an stakeoverflow issue #72186.

@eiriktsarpalis could you shed a light on which direction we are going to fix this? Add support for collection type that having only setter?

Btw, `_isUserSpecifiedSetter` is `false` when running the code above. Should it be `true`?

**Comment by ShawnWu33** [comment]
Hi I am trying to looking into this issue as got some time in upcoming few days.

Upon a shallow investigation, the following logic in `DetermineSerializationCapabilities()` is where the `CanDeserilize` being set false. 
```c#
if ((EffectiveConverter.ConverterStrategy & (ConverterStrategy.Enumerable | ConverterStrategy.Dictionary)) != 0)
{
    // Properties of collections types that only have setters are not supported.
    if (Get == null && Set != null && !_isUserSpecifiedSetter)
    {
        CanDeserialize = false;
    }
}
```
The comment `// Properties of collections types that only have setters are not supported.` is introduced in #72186.
@eiriktsarpalis Could you shed a light on which direction you consider the proper fix should be? Do we want to fix what's underlying to let collection type that only have setters be supported?

Btw Should `_isUserSpecifiedSetter` being set as `true` in this case? Its `false` when running above case.

**Comment by vispute-pratik** [comment]
Hi! I'd like to work on this issue. I've reproduced the problem locally and have started investigating the System.Text.Json metadata configuration around JsonPropertyInfo.Configure() and CanDeserialize. I'll submit a PR once I have a fix ready.
