### ISSUE TITLE
Test failure: System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#104769]
**Failed in:** [runtime-coreclr crossgen2 20240710.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=736959&view=ms.vss-test-web.build-test-results-tab&runId=18579510&resultId=132958&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-TestReadyToRun_Release-Ubuntu.2204.Amd64.Open
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-linux-Release-x64-TestReadyToRun_Release-(Centos.8.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8-helix
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-linux-Release-x64-TestReadyToRun_Release-(Debian.11.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-windows-Release-x64-TestReadyToRun_Release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.81.Amd64.Open
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.11.Amd64.Client.Open
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-windows-Release-x64-TestReadyToRun_Release-Windows.Amd64.Server2022.Open
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
net9.0-osx-Release-x64-TestReadyToRun_Release-OSX.1200.Amd64.Open
    - System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints
```

**Error message:**
```
 System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 408
   at System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/MetricsTest.cs:line 47
--- End of stack trace from previous location ---
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-07-11T10:43:30.669Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"DefinitionName":"runtime-extra-platforms","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"build_iossimulator_x64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"18583636","System.JobName":"__default","System.JobAttempt":"1","Project":"public","System.StageAttempt":"1","BuildId":"737098","BuildNumber":"20240711.1","System.JobId":"07effcfd-c63d-5008-e811-03b29530f5cb","architecture":"x64","Reason":"Schedule","DefinitionId":"154","System.StageName":"Build","configuration":"Release","runtimeFlavor":"mono","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.Amd64.Open"} | Schedule
2024-07-11T10:25:42.515Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"DefinitionName":"runtime-extra-platforms","architecture":"x64","System.JobName":"__default","BuildNumber":"20240711.1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","Project":"public","System.StageAttempt":"1","System.PhaseName":"build_maccatalyst_x64_Release_AllSubsets_Mono","System.JobId":"a2a39d6b-70c5-5040-933a-4b8b6e52bf19","runtimeFlavor":"mono","System.JobAttempt":"1","System.StageName":"Build","DefinitionId":"154","configuration":"Release","BuildId":"737098","operatingSystem":"OSX.1200.Amd64.Open","AzurePipelinesTestRunId":"18583256"} | Schedule
2024-07-11T10:23:32.688Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"AzurePipelinesTestRunId":"18583254","System.JobAttempt":"1","System.JobName":"__default","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","BuildNumber":"20240711.1","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","runtimeFlavor":"mono","DefinitionName":"runtime-extra-platforms","System.StageName":"Build","BuildId":"737098","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","DefinitionId":"154","System.PhaseAttempt":"1","architecture":"x64","configuration":"Release","Project":"public"} | Schedule
2024-07-11T10:16:39.252Z | runtime-extra-platforms | Release | osx.1200.arm64.open | arm64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"System.PhaseAttempt":"1","System.StageAttempt":"1","architecture":"arm64","DefinitionName":"runtime-extra-platforms","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","AzurePipelinesTestRunId":"18583174","System.PhaseName":"build_maccatalyst_arm64_Release_AllSubsets_Mono","BuildId":"737098","configuration":"Release","System.StageName":"Build","BuildNumber":"20240711.1","Reason":"Schedule","Project":"public","DefinitionId":"154","System.JobId":"cbf7f906-06a1-5744-2b19-594b1486a781","runtimeFlavor":"mono","System.JobName":"__default","operatingSystem":"OSX.1200.Arm64.Open"} | Schedule
2024-07-11T09:29:53.574Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"System.JobAttempt":"1","Project":"public","System.StageName":"Build","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","configuration":"Release","System.JobName":"__default","architecture":"arm64","BuildId":"737098","BuildNumber":"20240711.1","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","AzurePipelinesTestRunId":"18582134","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"154","runtimeFlavor":"mono"} | Schedule
2024-07-10T22:29:36.888Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"architecture":"x64","System.JobId":"07effcfd-c63d-5008-e811-03b29530f5cb","BuildNumber":"20240710.3","operatingSystem":"OSX.1200.Amd64.Open","Reason":"Schedule","System.JobName":"__default","BuildId":"736600","configuration":"Release","AzurePipelinesTestRunId":"18567518","DefinitionId":"154","System.JobAttempt":"1","System.PhaseAttempt":"1","runtimeFlavor":"mono","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","System.StageName":"Build","System.PhaseName":"build_iossimulator_x64_Release_AllSubsets_Mono","Project":"public","DefinitionName":"runtime-extra-platforms"} | Schedule
2024-07-10T22:26:10.257Z | runtime-extra-platforms | Release | osx.1200.arm64.open | arm64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"System.PhaseName":"build_maccatalyst_arm64_Release_AllSubsets_Mono","Reason":"Schedule","DefinitionName":"runtime-extra-platforms","BuildId":"736600","AzurePipelinesTestRunId":"18567554","runtimeFlavor":"mono","System.JobId":"cbf7f906-06a1-5744-2b19-594b1486a781","Project":"public","System.PhaseAttempt":"1","BuildNumber":"20240710.3","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.StageName":"Build","configuration":"Release","System.JobName":"__default","operatingSystem":"OSX.1200.Arm64.Open","System.StageAttempt":"1","DefinitionId":"154","architecture":"arm64"} | Schedule
2024-07-10T22:22:54.473Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"System.PhaseName":"build_maccatalyst_x64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"18567522","Reason":"Schedule","configuration":"Release","architecture":"x64","System.JobId":"a2a39d6b-70c5-5040-933a-4b8b6e52bf19","DefinitionId":"154","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","operatingSystem":"OSX.1200.Amd64.Open","System.PhaseAttempt":"1","runtimeFlavor":"mono","Project":"public","BuildNumber":"20240710.3","System.JobAttempt":"1","DefinitionName":"runtime-extra-platforms","System.JobName":"__default","BuildId":"736600"} | Schedule
2024-07-10T22:19:04.905Z | runtime-extra-platforms | Release | osx.1200.amd64.open | x64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"operatingSystem":"OSX.1200.Amd64.Open","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"18567410","System.StageName":"Build","BuildId":"736600","System.JobId":"cd385208-11d3-5d70-fa38-1c21a65d17f1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"154","runtimeFlavor":"mono","System.PhaseName":"build_tvossimulator_x64_Release_AllSubsets_Mono","DefinitionName":"runtime-extra-platforms","configuration":"Release","BuildNumber":"20240710.3","Reason":"Schedule","Project":"public","System.StageAttempt":"1","System.JobName":"__default","architecture":"x64","System.JobAttempt":"1"} | Schedule
2024-07-10T21:37:16.904Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.NameResolution.Tests.MetricsTest.DurationHistogram_HasBucketSizeHints | Failed | {"System.StageName":"Build","BuildId":"736600","System.JobName":"__default","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","architecture":"arm64","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","Reason":"Schedule","AzurePipelinesTestRunId":"18566188","DefinitionName":"runtime-extra-platforms","configuration":"Release","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","System.StageAttempt":"1","runtimeFlavor":"mono","System.PhaseAttempt":"1","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Project":"public","BuildNumber":"20240710.3"} | Schedule

**Comment by MichalStrehovsky** [comment]
This was fixed in #104736.
