### ISSUE TITLE
[6.0] Microsoft.Extensions.FileProviders.Physical.Tests failing to access a symlink used by PhysicalFilesWatcher

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#104823]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/public%20Team/_build/results?buildId=737840
Build error leg or test failing: `Libraries Test Run release coreclr windows x64 Debug` - `Microsoft.Extensions.FileProviders.Physical.Tests`

## Error Message

```json
{
  "ErrorMessage" : [
    "System.UnauthorizedAccessException: Access to the path",
    "PhysicalFilesWatcher.cs"
  ],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/104748
- Queue: `Libraries Test Run release coreclr windows x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=737840&view=logs&j=cb131f87-d5af-5ecc-6e5f-6dc86994859c&t=76503e0a-8c41-542c-43da-63a4758a95b0
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-104748-merge-8ea65ffd74cf4a6f89/Microsoft.Extensions.FileProviders.Physical.Tests/1/console.bad6be3c.log?helixlogtype=result
- Output:
```
===========================================================================================================

C:\h\w\BADD098E\w\B26B0998\e>"C:\h\w\BADD098E\p\dotnet.exe" exec --runtimeconfig Microsoft.Extensions.FileProviders.Physical.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.FileProviders.Physical.Tests.deps.json xunit.console.dll Microsoft.Extensions.FileProviders.Physical.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Microsoft.Extensions.FileProviders.Physical.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.FileProviders.Physical.Tests (found 83 of 92 test cases)
  Starting:    Microsoft.Extensions.FileProviders.Physical.Tests (parallel test collections = on, max threads = 2)
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\h\w\BADD098E\t\x3dfgyya.35z\2visikrv.aco' is denied.
   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 585
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 422
   at System.IO.FileSystemInfo.ResolveLinkTarget(Boolean returnFinalTarget) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystemInfo.cs:line 170
   at Microsoft.Extensions.FileProviders.Physical.FileSystemInfoHelper.GetFileLinkTargetLastWriteTimeUtc(FileInfo fileInfo) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Internal/FileSystemInfoHelper.cs:line 56
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 57
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 101
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 476
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 673
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 326
----- end Thu 07/11/2024 19:06:54.62 ----- exit code -532462766 ----------------------------------------------------------
```

**Comment by adamsitnik** [comment]
We have not touched this area in 6.0, so it must be some kind of rare flakiness. I am moving it to future for now.
