### ISSUE TITLE
Dotnet core Oracle 23c SSL connection not working on Linux environment and works on Windows

### ISSUE THREAD

**Issue by dkalidan** [dotnet/runtime#104840]
Our data direct ADO.NET oracle driver is having an issue with SSL connection on Linux platform and the same connection is working on windows environment with Oracle23c server.

Are there any known  limitations with dotnet core on linux environment with SSL/TLS connections.

 
```
Trace :

 InnerException: System.IO.IOExceptionMessage: Unable to read data from the transport connection: Connection reset by peer.
Source: System.Net.Sockets
Stack Trace
at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)

 ```

The same application works on Windows environment with dotnet8 and dotnet6 .

**Comment by wfurt** [comment]
This is likely what the `Connection reset by peer.` exception suggest e.g. networking problem. You should get packet captures and look @dkalidan.
