### ISSUE TITLE
Failed test: baseservices/exceptions/regressions/Dev11/154243/dynamicmethodliveness/dynamicmethodliveness.cmd

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#104924]
Pipeline: [runtime-coreclr gcstress-extra](https://dev.azure.com/dnceng-public/public/_build?definitionId=113&_a=summary)/[20240714.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740628)

Failed test:
coreclr linux arm Checked heapverify1 @ (Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7

Error message:
```
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/baseservices/exceptions/baseservices-exceptions/../regressions/Dev11/154243/dynamicmethodliveness/dynamicmethodliveness.sh: line 441:   181 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/regressions/Dev11/154243/dynamicmethodliveness/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true dynamicmethodliveness.dll ''
TestCase Started
Counter = 0
[createdump] Gathering state for process 181 corerun
[createdump] Crashing thread 00b5 signal 11 (000b)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.181.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.181.dmp
[createdump] Written 70758400 bytes (17275 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 94ms
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 7/14/2024 10:22:14 PM
Processing /home/helixbot/dotnetbuild/dumps/coredump.181.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.181.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0xb5
      Child SP               IP Call Site
 0xf790ab20 0xf7607614 libc.so.6!
 0xf790ab28 0xf76719c0 libc.so.6!__wait4_time64
 0xf790ab90 0xf75056dc libcoreclr.so!PROCCreateCrashDump(std::vector<char const*, std::allocator<char const*> >&, char*, int, bool) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2308:22
 0xf790abd8 0xf75064dc libcoreclr.so!PROCCreateCrashDumpIfEnabled at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2526:9
 0xf790ac28 0xf74baf7e libcoreclr.so!invoke_previous_action(sigaction*, int, siginfo_t*, void*, bool) at /__w/1/s/src/coreclr/pal/src/exception/signal.cpp:422:13
 0xf790ac60 0xf74ba500 libcoreclr.so!sigsegv_handler(int, siginfo_t*, void*) at /__w/1/s/src/coreclr/pal/src/exception/signal.cpp:0:5
 0xf790ac90 0xf76171b0 libc.so.6!
 0xff97c2f0 0xf7363be6 libcoreclr.so!Object::RawGetMethodTable() const at /__w/1/s/src/coreclr/vm/object.h:141:16
 (inlined by) WKS::CObjectHeader::GetMethodTable() const at /__w/1/s/src/coreclr/gc/gc.cpp:4742:44
 (inlined by) WKS::GCHeap::ValidateObjectMember(Object*) at /__w/1/s/src/coreclr/gc/gc.cpp:48081:5
 0xff97c320 0xf716b6dc libcoreclr.so!Object::ValidateInner(int, int, int) at /__w/1/s/src/coreclr/vm/object.cpp:588:13
 0xff97c398 0xf716b0ea libcoreclr.so!GetThreadNULLOk() at /__w/1/s/src/coreclr/vm/threads.inl:37:12
 (inlined by) Thread::IsObjRefValid(OBJECTREF const*) at /__w/1/s/src/coreclr/vm/threads.h:3243:34
 (inlined by) OBJECTREF::operator=(OBJECTREF const&) at /__w/1/s/src/coreclr/vm/object.cpp:1335:5
 0xff97c3b8 0xf70fe67e libcoreclr.so!StackTraceInfo::EnsureKeepAliveArray(REF<PtrArray>*, unsigned int) at /__w/1/s/src/coreclr/vm/vars.hpp:0:7
 0xff97c400 0xf70fec7e libcoreclr.so!StackTraceInfo::AppendElement(OBJECTHANDLE__*, unsigned int, unsigned int, MethodDesc*, CrawlFrame*) at /__w/1/s/src/coreclr/vm/excep.cpp:0:13
 0xff97c4b8 0xf72e7b3c libcoreclr.so!AppendExceptionStackFrame at /__w/1/s/src/coreclr/vm/exceptionhandling.cpp:0:13
 0xff97c530 0xeea01aca 0xeea01aca
 0xff97c5e0 0xeea0156e System.Runtime.EH.RhThrowEx(System.Object, ExInfo ByRef)
 0xff97c5f0 0xf736b96e 0xf736b96e
 0xff97c600 0xf71db93e libcoreclr.so!CallDescrWorker(CallDescrData*) at /__w/1/s/src/coreclr/vm/callhelpers.cpp:0:5
 0xff97ca28 0xf71db80e libcoreclr.so!NativeExceptionHolderBase::~NativeExceptionHolderBase() at /__w/1/s/src/coreclr/pal/inc/pal.h:4237:13
 (inlined by) CallDescrWorkerWithHandler(CallDescrData*, int) at /__w/1/s/src/coreclr/vm/callhelpers.cpp:65:5
 0xff97ca50 0xf71dbb46 libcoreclr.so!DispatchCallSimple(unsigned int*, unsigned int, unsigned int, unsigned int) at /__w/1/s/src/coreclr/vm/callhelpers.cpp:0:9
 0xff97cab0 0xf72e630e libcoreclr.so!DispatchManagedException(OBJECTREF, _CONTEXT*, bool) at /__w/1/s/src/coreclr/vm/exceptionhandling.cpp:0:5
 0xff97d4b8 0xf72e64c4 libcoreclr.so!DispatchManagedException(OBJECTREF, bool) at /__w/1/s/src/coreclr/vm/exceptionhandling.cpp:0:5
 0xff97d680 0xf724958c libcoreclr.so!ThrowNew(OBJECTREF) at /__w/1/s/src/coreclr/vm/jithelpers.cpp:0:5
 0xff97d6c8 0xf724975c libcoreclr.so!IL_Throw(Object*) at /__w/1/s/src/coreclr/vm/jithelpers.cpp:3550:9
 0xff97d7a8 0xee28a9ce My.ThrowException()
 0xff97d7b0 0xecc5e106 DynamicClass.MyMethod()
 0xff97d7b8 0xecc5e094 DynamicClass.MyMethod()
 0xff97d7c0 0xecc5e020 DynamicClass.MyMethod()
 0xff97d7c8 0xecc5df90 DynamicClass.MyMethod()
 0xff97d7d0 0xecc5df1c DynamicClass.MyMethod()
 0xff97d7d8 0xecc5dea8 DynamicClass.MyMethod()
 0xff97d7e0 0xecc5de34 DynamicClass.MyMethod()
 0xff97d7e8 0xecc5ddc0 DynamicClass.MyMethod()
 0xff97d7f0 0xecc5dd4c DynamicClass.MyMethod()
 0xff97d7f8 0xecc5dcd8 DynamicClass.MyMethod()
 0xff97d800 0xecc5dc64 DynamicClass.MyMethod()
 0xff97d808 0xecc5dbf0 DynamicClass.MyMethod()
 0xff97d810 0xecc5db7c DynamicClass.MyMethod()
 0xff97d818 0xecc5db08 DynamicClass.MyMethod()
 0xff97d820 0xecc5da94 DynamicClass.MyMethod()
 0xff97d828 0xecc5da20 DynamicClass.MyMethod()
 0xff97d830 0xecc5d9ac DynamicClass.MyMethod()
 0xff97d838 0xecc5d938 DynamicClass.MyMethod()
 0xff97d840 0xecc5d8c4 DynamicClass.MyMethod()
 0xff97d848 0xecc5d850 DynamicClass.MyMethod()
 0xff97d850 0xecc5d7dc DynamicClass.MyMethod()
 0xff97d858 0xee28a988 0xee28a988
 0xff97d8c0 0xee287e50 My.TestEntryPoint()
 0xff97d8e0 0xee287c38 __GeneratedMainWrapper.Main()
----------------------------------
Thread Id: 0xb6
      Child SP               IP Call Site
 0xf6f0ebd0 0xf7607614 libc.so.6!
 0xf6f0ebd8 0xf7692f44 libc.so.6!poll
 0xf6f0ebe8 0xf74fb7e0 libcoreclr.so!CorUnix::CPalSynchronizationManager::ReadBytesFromProcessPipe(int, unsigned char*, int) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:2238:24
 0xf6f0ec48 0xf74faf9e libcoreclr.so!CorUnix::CPalSynchronizationManager::ReadCmdFromProcessPipe(int, CorUnix::CPalSynchronizationManager::SynchWorkerCmd*, void**, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:2018:13
 0xf6f0ec98 0xf74fa408 libcoreclr.so!CorUnix::CPalSynchronizationManager::WorkerThread(void*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:1723:17
 0xf6f0ed28 0xf7508a72 libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
----------------------------------
Thread Id: 0xb7
      Child SP               IP Call Site
 0xf65feb90 0xf7607614 libc.so.6!
 0xf65feb98 0xf7692f44 libc.so.6!poll
 0xf65feba8 0xf741af4e libcoreclr.so!ipc_retry_syscall(int) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:283:22
 (inlined by) ipc_poll_fds(pollfd*, unsigned int, unsigned int) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:486:11
 (inlined by) ds_ipc_poll(_DiagnosticsIpcPollHandle*, unsigned int, unsigned int, void (*)(char const*, unsigned int)) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:1105:16
 0xf65febd0 0xf7392bc6 libcoreclr.so!ds_ipc_stream_factory_get_next_available_stream(void (*)(char const*, unsigned int)) at /__w/1/s/src/native/eventpipe/ds-ipc.c:0:14
 0xf65fecd0 0xf7396f06 libcoreclr.so!server_thread(void*) at /__w/1/s/src/native/eventpipe/ds-server.c:130:7
 0xf65fed28 0xf7508a72 libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
----------------------------------
Thread Id: 0xb8
      Child SP               IP Call Site
 0xf5bfe918 0xf7607614 libc.so.6!
 0xf5bfe920 0xf768e00a libc.so.6!__open64
 0xf5bfe948 0xf741a8fe libcoreclr.so!TwoWayPipe::WaitForConnection() at /__w/1/s/src/coreclr/debug/debug-pal/unix/twowaypipe.cpp:87:19
 0xf5bfe970 0xf7415aea libcoreclr.so!DbgTransportSession::TransportWorker() at /__w/1/s/src/coreclr/debug/ee/../shared/dbgtransportsession.cpp:1315:17
 0xf5bfed18 0xf74148f4 libcoreclr.so!DbgTransportSession::TransportWorkerStatic(void*) at /__w/1/s/src/coreclr/debug/ee/../shared/dbgtransportsession.cpp:1235:5
 0xf5bfed28 0xf7508a72 libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
----------------------------------
Thread Id: 0xb9
      Child SP               IP Call Site
 0xf51fe9b0 0xf7607614 libc.so.6!
 0xf51fe9b8 0xf764347e libc.so.6!
 0xf51fe9f0 0xf764355c libc.so.6!
 0xf51fea00 0xf764570a libc.so.6!pthread_cond_wait
 0xf51fea80 0xf74f81a8 libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:489:17
 0xf51feae0 0xf74f78b8 libcoreclr.so!CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:0:0
 0xf51feb30 0xf74ff01a libcoreclr.so!CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int, int) at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:0:45
 0xf51fec18 0xf74ff884 libcoreclr.so!WaitForMultipleObjectsEx at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:204:5
 0xf51fec60 0xf7412648 libcoreclr.so!DebuggerRCThread::MainLoop() at /__w/1/s/src/coreclr/debug/ee/rcthread.cpp:927:14
 0xf51fece0 0xf7412464 libcoreclr.so!BaseHolder<Debugger*, FunctionBase<Debugger*, &(Debugger::AcquireDebuggerLock(Debugger*)), &(Debugger::ReleaseDebuggerLock(Debugger*))>, 0u, &(int CompareDefault<Debugger*>(Debugger*, Debugger*))>::Release() at /__w/1/s/src/coreclr/inc/holder.h:285:13
 (inlined by) BaseHolder<Debugger*, FunctionBase<Debugger*, &(Debugger::AcquireDebuggerLock(Debugger*)), &(Debugger::ReleaseDebuggerLock(Debugger*))>, 0u, &(int CompareDefault<Debugger*>(Debugger*, Debugger*))>::~BaseHolder() at /__w/1/s/src/coreclr/inc/holder.h:256:9
 (inlined by) DebuggerRCThread::ThreadProc() at /__w/1/s/src/coreclr/debug/ee/rcthread.cpp:731:1
 0xf51fed18 0xf74120ec libcoreclr.so!DebuggerRCThread::ThreadProcStatic(void*) at /__w/1/s/src/coreclr/debug/ee/rcthread.cpp:1321:5
 0xf51fed28 0xf7508a72 libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
----------------------------------
Thread Id: 0xba
      Child SP               IP Call Site
 0xf19fd658 0xf7607614 libc.so.6!
 0xf19fd660 0xf764347e libc.so.6!
 0xf19fd698 0xf764355c libc.so.6!
 0xf19fd6a8 0xf764597c libc.so.6!__pthread_cond_timedwait64
 0xf19fd730 0xf74f81bc libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:489:17
 0xf19fd790 0xf74f78b8 libcoreclr.so!CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:0:0
 0xf19fd7e0 0xf74ff01a libcoreclr.so!CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int, int) at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:0:45
 0xf19fd8c8 0xf74ff648 libcoreclr.so!WaitForSingleObjectEx at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:141:5
 0xf19fd908 0xf72bb1e4 libcoreclr.so!NativeExceptionHolderBase::~NativeExceptionHolderBase() at /__w/1/s/src/coreclr/pal/inc/pal.h:4237:13
 (inlined by) CLREventWaitHelper(void*, unsigned int, int) at /__w/1/s/src/coreclr/vm/synch.cpp:399:5
 (inlined by) CLREventBase::WaitEx(unsigned int, WaitMode, PendingSync*) at /__w/1/s/src/coreclr/vm/synch.cpp:466:20
 0xf19fd968 0xf722198c libcoreclr.so!FinalizerThread::WaitForFinalizerEvent(CLREvent*) at /__w/1/s/src/coreclr/vm/finalizerthread.cpp:189:5
 0xf19fd9a8 0xf7221d62 libcoreclr.so!GCHeapUtilities::GetGCHeap() at /__w/1/s/src/coreclr/vm/gcheaputilities.h:74:9
 (inlined by) FinalizerThread::FinalizerThreadWorker(void*) at /__w/1/s/src/coreclr/vm/finalizerthread.cpp:321:36
 0xf19fdc10 0xf71a913a libcoreclr.so!ManagedThreadBase_DispatchMiddle(ManagedThreadCallState*) at /__w/1/s/src/coreclr/vm/threads.cpp:0:5
 (inlined by) ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_0::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const::'lambda'(Param*)::operator()(Param*) const at /__w/1/s/src/coreclr/vm/threads.cpp:7317:13
 (inlined by) ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_0::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const at /__w/1/s/src/coreclr/vm/threads.cpp:7319:9
 (inlined by) ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) at /__w/1/s/src/coreclr/vm/threads.cpp:7343:5
 0xf19fdcd0 0xf71a958e libcoreclr.so!ManagedThreadBase_NoADTransition(void (*)(void*), UnhandledExceptionLocation) at /__w/1/s/src/coreclr/vm/threads.cpp:0:5
 (inlined by) ManagedThreadBase::FinalizerBase(void (*)(void*)) at /__w/1/s/src/coreclr/vm/threads.cpp:7406:5
 0xf19fdce8 0xf7222316 libcoreclr.so!FinalizerThread::FinalizerThreadStart(void*) at /__w/1/s/src/coreclr/vm/finalizerthread.cpp:462:22
 0xf19fdd28 0xf7508a72 libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
----------------------------------
Thread Id: 0xbd
      Child SP               IP Call Site
 0xed4bbd80 0xf7607614 libc.so.6!
 0xed4bbd88 0xf768e2e0 libc.so.6!read

Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/baseservices/exceptions/baseservices-exceptions/../regressions/Dev11/154243/dynamicmethodliveness/dynamicmethodliveness.sh
Xunit.Sdk.TrueException: waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/baseservices/exceptions/baseservices-exceptions/../regressions/Dev11/154243/dynamicmethodliveness/dynamicmethodliveness.sh: line 441:   181 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

```

Stack trace:
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor95|0_96(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL.

**Comment by kunalspathak** [comment]
Is there any reason why this is tagged as codegen bug? I don't see any Jit flags needed to repro this, and looking at the stack, I don't see any jitted code involved.

**Comment by janvorli** [comment]
This a dup of #104878 that I have fixed yesterday. So I am closing this issue.
