### ISSUE TITLE
System.Net.Quic.Tests.MsQuicTests.WriteTests failed with "System.Net.Quic.QuicException : The connection timed out from inactivity."

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#105177]
E.g.
```
    System.Net.Quic.Tests.MsQuicTests.WriteTests(writes: [[1000004, 1], [1, 15003], [1000004, 1000004], [15003, 15003], [1, 502]]) [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(630,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(732,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(767,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(561,0): at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(1029,0): at System.Net.Quic.Tests.MsQuicTests.<>c__DisplayClass23_0.<<WriteTests>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(295,0): at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(291,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(322,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(322,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(285,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(1012,0): at System.Net.Quic.Tests.MsQuicTests.WriteTests(Int32[][] writes)
        --- End of stack trace from previous location ---
```

Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-105169-merge-e8c1f9b799044b5882/System.Net.Quic.Functional.Tests/1/console.64747ae3.log?helixlogtype=result

Looks like we had a known failure #91757 before, but it was closed yesterday with #105109, cc @liveans. Note that the failure I saw here is on osx-x64, not arm32.

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=748550
Build error leg or test failing: System.Net.Quic.Tests.MsQuicTests.WriteTests
Pull request: https://github.com/dotnet/runtime/pull/105169

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Net.Quic.QuicException ?: The connection timed out from inactivity",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by liveans** [comment]
Related to #103482

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20250420.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1021374&view=ms.vss-test-web.build-test-results-tab&runId=27358572&resultId=171299&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-syntheticpgo_blend-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Timeout_Roundtrips
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteByte_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnWriteableStreamWithNoData_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadTimeout_Expires_Throws
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnReadableStream_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Disposed_ThrowsObjectDisposedException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_DuringReadAsync_ThrowsIfUnsupported
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ServerReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAsync_LocalAbort_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAbortedWithoutWriting_ReadThrows
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWriteCompletionAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 773
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 808
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 581
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass12_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 84
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 585
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 80
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync()
   at System.IO.Tests.ConnectedStreamConformanceTests.Timeout_Roundtrips() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2578
--- End of stack trace from previous location ---
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250422.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1022537&view=ms.vss-test-web.build-test-results-tab&runId=27394010&resultId=186412&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-disabler2r-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnReadableStream_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Disposed_ThrowsObjectDisposedException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_DuringReadAsync_ThrowsIfUnsupported
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ServerReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAsync_LocalAbort_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAbortedWithoutWriting_ReadThrows
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWriteCompletionAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 178
   at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 642
   at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 665
   at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 694
--- End of stack trace from previous location ---
   at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 251
   at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 323
   at System.IO.Tests.ConnectedStreamConformanceTests.<>c__DisplayClass43_1.<<ConcurrentBidirectionalReadsWrites_Success>b__3>d.MoveNext() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2502
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 579
   at System.IO.Tests.ConnectedStreamConformanceTests.<>c__DisplayClass43_0.<<ConcurrentBidirectionalReadsWrites_Success>b__0>d.MoveNext() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2497
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 585
   at System.IO.Tests.ConnectedStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2512
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
This issue is to track OSX failures, yours are on arm32.

**Comment by AndyAyersMS** [comment]
I am seeing an instance of this in #114974, not sure why build analysis didn't latch on.

**Comment by ManickaP** [comment]
It passed on re-run based on the 2 console logs from here https://dev.azure.com/dnceng-public/public/_build/results?buildId=1024684&view=ms.vss-test-web.build-test-results-tab&runId=27461692&resultId=205458&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

I don't know why AzDO is still showing the test as failed, it shouldn't, the second run was clear:
```
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 429, Errors: 0, Failed: 0, Skipped: 1, Time: 137.101s
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250426.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1027298&view=ms.vss-test-web.build-test-results-tab&runId=27550690&resultId=179534&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 773
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 808
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 553
   at System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 506
   at System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 523
   at System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 523
--- End of stack trace from previous location ---
```
