### ISSUE TITLE
Test failure: profiler\\assembly\\ALCTest\\ALCTest.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105225]
**Failed in:** [runtime-coreclr gcstress-extra 20240721.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749452&view=ms.vss-test-web.build-test-results-tab&runId=18964592&resultId=100359&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.11.Arm64.Open
    - profiler\\assembly\\ALCTest\\ALCTest.cmd
```

**Error message:**
```
 Unhandled exception. System.ArgumentException: Path "
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code -532462766.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.ALCTest.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AAC80946\w\AFD109FF\uploads\Reports\profiler.assembly\ALCTest\ALCTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AAC80946\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ALCTest.dll 
Profiler path: C:\h\w\AAC80946\w\AFD109FF\e\profiler\assembly\ALCTest\Profiler.dll
Profilee STDOUT: Profiler.dll!DllGetClassObject
Profilee STDOUT: Profiler.dll!Profiler::Initialize
Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code -532462766.
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 7/21/2024 11:14:54 PM
Processing C:\cores\corerun.exe.1292.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Processing C:\cores\corerun.exe.4060.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AAC80946\p
> C:\h\w\AAC80946\w\AFD109FF\e\profiler\assembly\ALCTest\ALCTest.cmd
```

**Stack trace:**
```
   at profiler_assembly._ALCTest_ALCTest_._ALCTest_ALCTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by mdh1418** [comment]
The test failure looks unrelated to the test being ran, and Jakob noted the linked revert pr fixes the issue.
