### ISSUE TITLE
`JIT/Performance/CodeQuality/Bytemark/Bytemark` failed with `Assert failure: al->alloc_list_tail() == 0`

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#105201]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=749347
Build error leg or test failing: JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.cmd
Pull request: https://github.com/dotnet/runtime/pull/105196

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "al->alloc_list_tail() == 0",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=749347
**Error message validated:** `[al->alloc_list_tail() == 0`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/21/2024 4:32:13 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by mangod9** [comment]
Closing since this hasnt reproed in a few weeks.

**Comment by jakobbotsch** [comment]
Failed again in https://dev.azure.com/dnceng-public/public/_build/results?buildId=788045&view=ms.vss-test-web.build-test-results-tab&runId=20250350&resultId=116754&paneView=debug

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240827.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=790814&view=ms.vss-test-web.build-test-results-tab&runId=20330520&resultId=123122&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked tailcallstress @ OSX.1200.ARM64.Open
    - JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.cmd
```

**Error message:**
```
 
Assert failure(PID 19124 [0x00004ab4], Thread: 1429884 [0x15d17c]): al->alloc_list_tail() == 0
    File: /Users/runner/work/1/s/src/coreclr/gc/gc.cpp:15956
    Image: /private/tmp/helix/working/B7F90A39/p/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/private/tmp/helix/working/B7F90A39/w/AD6C0972/e/JIT/Performance/JIT.performance/../CodeQuality/Bytemark/Bytemark/Bytemark.sh: line 453: 19124 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/B7F90A39/w/AD6C0972/uploads/CodeQuality/Bytemark/Bytemark/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B7F90A39/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true Bytemark.dll ''
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 2209.94186  Index: 56.67535
NUMERIC SORT(rectangle):  Iterations/sec: 1287.13523  Index: 33.00939
STRING SORT:  Iterations/sec: 27520.34177  Index: 12296.84619
BITFIELD:  Iterations/sec: 476784185.07108  Index: 81.78532
FP EMULATION(struct):  Iterations/sec: 198.24854  Index: 95.12886
FP EMULATION(class):  Iterations/sec: 195.65436  Index: 93.88405
FOURIER:  Iterations/sec: 398137.02624  Index: 452.79994
ASSIGNMENT(jagged):  Iterations/sec: 64.87394  Index: 246.85669
ASSIGNMENT(rectangle):  Iterations/sec: 52.86123  Index: 201.14625
IDEA:  Iterations/sec: 10666.95361  Index: 163.14817
HUFFMAN:  Iterations/sec: 6345.85266  Index: 175.97062
NEURAL NET(jagged):  Iterations/sec: 71.06452  Index: 114.15988
NEURAL NET(rectangle):  Iterations/sec: 55.22170  Index: 88.70956
LU DECOMPOSITION:[createdump] Gathering state for process 19124 
[createdump] Crashing thread 15d17c signal 6 (0006)
[createdump] Writing crash report to file /cores/coredump.19124.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.19124.dmp
[createdump] Written 455016616 bytes (27772 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 1207ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 8/27/2024 10:35:27 PM
Processing /cores/coredump.19124.dmp.crashreport.json
Printing stacktrace from '/cores/coredump.19124.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/B7F90A39/w/AD6C0972/e/JIT/Performance/JIT.performance'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 496
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at System.Diagnostics.Process.Start() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1284
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/B7F90A39/w/AD6C0972/e/JIT/
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor99|0_100(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jeffschwMSFT** [comment]
removing 'blocking-clea-ci' since it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by mangod9** [comment]
old issue which hasn't reproed in a while.
