### ISSUE TITLE
QuicStream has racy ManualResetValueTaskSourceCore usage

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#105263]
### Description

Somehow the `QuicStream._sendTcs` is getting into an invalid state when there is an active write and shutdown is occurring.

Below are the logs from a Kestrel test where we hit the classic concurrent ValueTask usage stack:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetStatus(Int16 token)
    at System.Net.Http.Http3RequestStream.FlushSendBufferAsync(Boolean endStream, CancellationToken cancellationToken)
```
<details>
<summary>logs</summary>

```
2024-07-07T01:43:41.5496226Z   Standard Output Messages:
2024-07-07T01:43:41.5496784Z  | [0.000s] TestLifetime Information: Starting test POST_ServerAbort_ClientReceivesAbort-Http3 at 2024-07-07T01:43:39
2024-07-07T01:43:41.5497170Z  | [0.003s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2024-07-07T01:43:41.5497389Z  | [0.029s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: QUIC listener starting with configured endpoint 127.0.0.1:0.
2024-07-07T01:43:41.5497647Z  | [0.032s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:43054
2024-07-07T01:43:41.5498015Z  | [0.032s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
2024-07-07T01:43:41.5498369Z  | [0.033s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2024-07-07T01:43:41.5498566Z  | [0.033s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2024-07-07T01:43:41.5498835Z  | [0.033s] Microsoft.Hosting.Lifetime Information: Content root path: /root/helix/work/workitem/e/
2024-07-07T01:43:41.5499283Z  | [0.033s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2024-07-07T01:43:41.5499655Z  | [0.064s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HN4U4OSPUDLV" accepted.
2024-07-07T01:43:41.5499910Z  | [0.064s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN4U4OSPUDLV" accepted.
2024-07-07T01:43:41.5500737Z  | [0.064s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN4U4OSPUDLV" started.
2024-07-07T01:43:41.5501659Z  | [0.065s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000003" type Unidirectional connected.
2024-07-07T01:43:41.5502653Z  | [0.068s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000002" type Unidirectional accepted.
2024-07-07T01:43:41.5503391Z  | [0.068s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HN4U4OSPUDLV" received SETTINGS frame for stream ID 2 with length 5.
2024-07-07T01:43:41.5504532Z  | [0.073s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Client sending request headers
2024-07-07T01:43:41.5505328Z  | [0.075s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000000" type Bidirectional accepted.
2024-07-07T01:43:41.5506205Z  | [0.075s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HN4U4OSPUDLV" received HEADERS frame for stream ID 0 with length 22.
2024-07-07T01:43:41.5507012Z  | [0.075s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/3 POST https://127.0.0.1:43054/ - - -
2024-07-07T01:43:41.5507854Z  | [0.075s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Trace id "0HN4U4OSPUDLV:00000000": HTTP/3 stream error "H3_INTERNAL_ERROR". An abort is being sent to the stream.
2024-07-07T01:43:41.5508599Z  | Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
2024-07-07T01:43:41.5509298Z  | [0.076s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000000" aborted by application with error code 258 because: "The connection was aborted by the application.".
2024-07-07T01:43:41.5509969Z  | [0.076s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000000" shutting down writes because: "The connection was aborted by the application.".
2024-07-07T01:43:41.5510938Z  | [0.081s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HN4U4OSPUDLV" aborted by peer with error code 256.
2024-07-07T01:43:41.5511649Z  | System.Net.Quic.QuicException: Connection aborted by peer (256).
2024-07-07T01:43:41.5512348Z  |    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByPeer(_SHUTDOWN_INITIATED_BY_PEER_e__Struct& data)
2024-07-07T01:43:41.5513117Z  |    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
2024-07-07T01:43:41.5513926Z  |    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
2024-07-07T01:43:41.5514532Z  | --- End of stack trace from previous location ---
2024-07-07T01:43:41.5515269Z  |    at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
2024-07-07T01:43:41.5516116Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 97
2024-07-07T01:43:41.5516879Z  | [0.082s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000003" write aborted by peer with error code 256.
2024-07-07T01:43:41.5517683Z  | [0.082s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000003" shutting down writes because: "Connection aborted by peer (256).".
2024-07-07T01:43:41.5518466Z  | [0.082s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN4U4OSPUDLV:00000002" read aborted by peer with error code 256.
2024-07-07T01:43:41.5519311Z  | [0.083s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HN4U4OSPUDLV" request processing ended abnormally.
2024-07-07T01:43:41.5520035Z  | Microsoft.AspNetCore.Connections.ConnectionResetException: Connection aborted by peer (256).
2024-07-07T01:43:41.5520739Z  |  ---> System.Net.Quic.QuicException: Connection aborted by peer (256).
2024-07-07T01:43:41.5521391Z  |    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByPeer(_SHUTDOWN_INITIATED_BY_PEER_e__Struct& data)
2024-07-07T01:43:41.5522177Z  |    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
2024-07-07T01:43:41.5522780Z  |    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
2024-07-07T01:43:41.5523535Z  | --- End of stack trace from previous location ---
2024-07-07T01:43:41.5524269Z  |    at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
2024-07-07T01:43:41.5525105Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 97
2024-07-07T01:43:41.5525758Z  |    --- End of inner exception stack trace ---
2024-07-07T01:43:41.5526495Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 145
2024-07-07T01:43:41.5527900Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-07-07T01:43:41.5528632Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs:line 356
2024-07-07T01:43:41.5529560Z  | [0.084s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HN4U4OSPUDLV" aborted by application with error code 256 because: "The client closed the connection.".
2024-07-07T01:43:41.5530294Z  | [0.086s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: QUIC listener aborted.
2024-07-07T01:43:41.5531306Z  | System.ObjectDisposedException: Cannot access a disposed object.
2024-07-07T01:43:41.5532070Z  | Object name: 'System.Net.Quic.QuicListener'.
2024-07-07T01:43:41.5533211Z  |    at System.Net.Quic.QuicListener.DisposeAsync()
2024-07-07T01:43:41.5534197Z  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-07-07T01:43:41.5535272Z  |    at System.Net.Quic.QuicListener.DisposeAsync()
2024-07-07T01:43:41.5536080Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.DisposeAsync() in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 211
2024-07-07T01:43:41.5536938Z  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-07-07T01:43:41.5537682Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.DisposeAsync()
2024-07-07T01:43:41.5538384Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.UnbindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 200
2024-07-07T01:43:41.5540004Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.GenericMultiplexedConnectionListener.UnbindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 233
2024-07-07T01:43:41.5541343Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.ActiveTransport.UnbindAsync(CancellationToken cancellationToken)
2024-07-07T01:43:41.5542080Z  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-07-07T01:43:41.5542879Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.StopTransportsAsync(List`1 transportsToStop, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 131
2024-07-07T01:43:41.5544521Z  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-07-07T01:43:41.5545386Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StopAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 259
2024-07-07T01:43:41.5546335Z  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-07-07T01:43:41.5547077Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StopAsync(CancellationToken cancellationToken)
2024-07-07T01:43:41.5547980Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.Dispose() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 283
2024-07-07T01:43:41.5548919Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
2024-07-07T01:43:41.5549719Z  |    at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
2024-07-07T01:43:41.5550326Z  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-07-07T01:43:41.5551064Z  |    at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
2024-07-07T01:43:41.5551789Z  |    at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
2024-07-07T01:43:41.5552719Z  |    at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerAbort_ClientReceivesAbort(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 568
2024-07-07T01:43:41.5553507Z  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
2024-07-07T01:43:41.5554494Z  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-07-07T01:43:41.5555239Z  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
2024-07-07T01:43:41.5556211Z  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
2024-07-07T01:43:41.5556869Z  |    at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__0() in /_/src/xunit.execution/Sdk/AsyncTestSyncContext.cs:line 58
2024-07-07T01:43:41.5557527Z  |    at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in /_/src/common/XunitWorkerThread.cs:line 37
2024-07-07T01:43:41.5558259Z  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-07-07T01:43:41.5559195Z  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2024-07-07T01:43:41.5560028Z  | --- End of stack trace from previous location ---
2024-07-07T01:43:41.5560850Z  |    at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)
2024-07-07T01:43:41.5561713Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.AcceptAsync(IFeatureCollection features, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 157
2024-07-07T01:43:41.5563184Z  | [0.087s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to close gracefully during server shutdown.
2024-07-07T01:43:41.5564251Z  | [1.088s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to abort during server shutdown.
2024-07-07T01:43:41.5565165Z  | [1.097s] Interop.FunctionalTests.Http3.Http3RequestTests Error: Test threw an exception.
2024-07-07T01:43:41.5566104Z  | System.InvalidOperationException: Operation is not valid due to the current state of the object.
2024-07-07T01:43:41.5566763Z  |    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetStatus(Int16 token)
2024-07-07T01:43:41.5567577Z  |    at System.Net.Http.Http3RequestStream.FlushSendBufferAsync(Boolean endStream, CancellationToken cancellationToken)
2024-07-07T01:43:41.5568278Z  |    at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 117
2024-07-07T01:43:41.5569048Z  |    at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerAbort_ClientReceivesAbort(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 568
2024-07-07T01:43:41.5569715Z  |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2024-07-07T01:43:41.5570481Z  | --- End of stack trace from previous location ---
2024-07-07T01:43:41.5571129Z  |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2024-07-07T01:43:41.5571796Z  |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2024-07-07T01:43:41.5572617Z  | [1.098s] TestLifetime Information: Finished test POST_ServerAbort_ClientReceivesAbort-Http3 in 1.0973761s
```

</details>

### Reproduction Steps

No minimal steps at this time. Maximum steps would be to run the Kestrel test POST_ServerAbort_ClientReceivesAbort repeatedly.

### Expected behavior

No InvalidOperationException from ManualResetValueTaskSourceCore

### Actual behavior

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetStatus(Int16 token)
    at System.Net.Http.Http3RequestStream.FlushSendBufferAsync(Boolean endStream, CancellationToken cancellationToken)
```

**Comment by ManickaP** [comment]
I've been trying to reproduce it for a while with no success (with a loop, with stress-ng stressing the machine CPU, with strategically placed yields and delays, ...). Based on Kusto queries, this has been intermittently happening for a while as well (as long as Kusto remembers, query `AzureDevOpsTests | where TestName has "POST_ServerAbort_ClientReceivesAbort"`). It hasn't happened since 12.7. I'll punt it into 10.0 and I'll observe it.

**Comment by ManickaP** [comment]
Based on Kusto data, this doesn't happen on .NET 9.0 nor main, only on .NET 8. As we don't have any customer reports that would warrant deeper investigation (to even find which change fixed it) and potential backport, I'll close this issue as resolved.
