### ISSUE TITLE
[wasm] XHarness SocketException: Transport endpoint is not connected

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#105370]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=752655
Build error leg or test failing: `browser-wasm windows Release LibraryTests_Smoke_AOT`

## Error Message

```json
{
  "ErrorMessage" : "Transport endpoint is not connected",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/105352
- Queue: `browser-wasm windows Release LibraryTests_Smoke_AOT`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=752655&view=logs&j=d4114222-2640-5505-c7da-33ed88276119&t=bcb04d4d-862f-5ea3-9327-2e64cfa5d6de
- Log file: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105352-merge-27ea34114b60472f9d/WasmTestOnFirefox-ST-System.Xml.Linq.Events.Tests/1/console.cb610c54.log?helixlogtype=result
- Output:
```
console.error: (new AbortError("IndexedDB: main/search-config-overrides-v2 getLastModified() IndexedDB:  execute() A request was aborted, for example through a call to IDBTransaction.abort.", "resource://services-settings/IDBHelpers.sys.mjs", 16))
[22:45:33] crit: System.Net.Sockets.SocketException (107): Transport endpoint is not connected
                    at System.Net.Sockets.Socket.get_RemoteEndPoint()
                    at System.Net.Http.HttpConnectionPool.<ConnectAsync>g__GetRemoteEndPoint|51_0(Stream stream)
                    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
                    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
                    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
                    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
                    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
                    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Dispose(Boolean disposing)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Dispose()
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 108
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger)
                    at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 145
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by maraf** [comment]
Looks like some firefox specific thing. No idea, maybe something like maintance? Does firefox driver have some configuration that we could set? 
(Looking for the addons seems unoptimal as well).
