### ISSUE TITLE
AspNetCore  app fail to start on rocky linux 9.4 with selinux with SocketException (13): Permission denied

### ISSUE THREAD

**Issue by Neurozone** [dotnet/runtime#105320]
### Description

When running an aspnet application on rocky linux 9.4 as non-root I have permission denied issue for socket
Also selinux is in enforcing mode

app is here: https://github.com/Kareadita/Kavita

### Reproduction Steps

cat /etc/systemd/system/kavita.service
[Unit]
Description=Kavita Server
After=network.target suricata.service

[Service]
User=kavita
Group=kavita
Type=simple
WorkingDirectory=/data/Kavita
ExecStart=/data/Kavita/Kavita
TimeoutStopSec=20
KillMode=process
#Restart=on-failure
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

[Install]
WantedBy=multi-user.target

systemctl start kavita

fail

### Expected behavior

application start

### Actual behavior

application fail

### Known Workarounds

running dotnet app as root work, but it's a security issue

### Configuration

.NET 8
rocky linux 9.4 x86_64
sellinux enabled 
port is 5000 by default

cat /data/Kavita/config/appsettings.json
{
  "TokenKey": "****",
  "Port": 5000,
  "IpAddresses": "",
  "BaseUrl": "/",
  "Cache": 50,
  "AllowIFraming": false
}

### Other information
`
Kavita[440433]: [Kavita] [2024-07-23 14:11:20.273 +02:00  1] [Information] API.Program Starting with base url as /
Kavita[440433]: [Kavita] [2024-07-23 14:11:20.335 +02:00  1] [Error] Microsoft.Extensions.Hosting.Internal.Host Hosting failed to start
Kavita[440433]: System.Net.Sockets.SocketException (13): Permission denied
Kavita[440433]:   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
Kavita[440433]:   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
Kavita[440433]: --- End of stack trace from previous location ---
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)

Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)

Kavita[440433]: [Kavita] [2024-07-23 14:11:20.351 +02:00  1] [Fatal]  Host terminated unexpectedly

Kavita[440433]: System.Net.Sockets.SocketException (13): Permission denied

Kavita[440433]:   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)

Kavita[440433]:   at System.Net.Sockets.Socket.Bind(EndPoint localEP)

Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)

Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
Kavita[440433]: --- End of stack trace from previous location ---
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Kavita[440433]:   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Kavita[440433]:   at API.Program.Main(String[] args) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Program.cs:line 149
systemd[1]: kavita.service: Deactivated successfully.
systemd[1]: kavita.service: Consumed 3.502s CPU time.
`

**Comment by Neurozone** [comment]
Found the solution, it was a hidden selinux rule:

`Jul 24 13:49:53 setroubleshoot[71999]: SELinux is preventing /data/Kavita/Kavita from name_bind access on the tcp_socket port 5000. For complete SELinux messages run: sealert -l 12fee786-2741-47f5-91ca-90d301101db1
Jul 24 13:49:54 setroubleshoot[71999]: SELinux is preventing /data/Kavita/Kavita from name_bind access on the tcp_socket port 5000.
*****  Plugin catchall_boolean (89.3 confidence) suggests   ******************
If you want to allow httpd to access openstack ports
Then you must tell SELinux about this by enabling the 'httpd_use_openstack' boolean.
You can read 'httpd_selinux' man page for more details.
setsebool -P httpd_use_openstack 1
*****  Plugin catchall (11.6 confidence) suggests   **************************
If you believe that Kavita should be allowed name_bind access on the port 5000 tcp_socket by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
allow this access for now by executing:
 ausearch -c 'Kavita' --raw | audit2allow -M my-Kavita
 semodule -X 300 -i my-Kavita.pp#
`

needed to add 
allow httpd_t commplex_main_port_t:tcp_socket name_bind;

as selinux rule
