### ISSUE TITLE
[Apple] New Environment.CpuUsage tests failing on Apple mobile

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#105322]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=750924
Build error leg or test failing: `System.Tests.EnvironmentTests.TestCpuUsage`, `System.Diagnostics.Metrics.Tests.RuntimeMetricsTests.CpuTime`
Affected CI: `tvos_arm64_release_allsubsets_mono`, `[ios/tvos]simulator_x64_release_allsubsets_mono` (`runtime-extra-platforms`
Range of commits: https://github.com/dotnet/runtime/compare/f304e99c...b252fa50

Stack trace example:
```
[18:23:54] dbug: 2024-07-22 18:23:54.787192-0400 System.Runtime.Extensions.Tests[42406:561226] 	[FAIL] System.Tests.EnvironmentTests.TestCpuUsage
[18:23:54] dbug: Assert.Equal() Failure: Values differ
[18:23:54] dbug: Expected: 00:00:00
[18:23:54] dbug: Actual:   00:00:28.3581230
[18:23:54] dbug: at System.Tests.EnvironmentTests.TestCpuUsage()
[18:23:54] dbug: 2024-07-22 18:23:54.787476-0400 System.Runtime.Extensions.Tests[42406:561226]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[18:23:54] dbug: at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.EnvironmentTests.TestCpuUsage",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=750924
**Error message validated:** `[[FAIL] System.Tests.EnvironmentTests.TestCpuUsage`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/23/2024 3:32:24 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[758343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758343)|dotnet/runtime|[System.Runtime.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=758343&view=ms.vss-test-web.build-test-results-tab&runId=19243430&resultId=206492)||
|[757260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757260)|dotnet/runtime|[System.Runtime.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757260&view=ms.vss-test-web.build-test-results-tab&runId=19207358&resultId=206486)||
|[755747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747)|dotnet/runtime|[System.Runtime.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747&view=ms.vss-test-web.build-test-results-tab&runId=19161316&resultId=206482)||
|[751577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751577)|dotnet/runtime|[System.Runtime.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751577&view=ms.vss-test-web.build-test-results-tab&runId=19035918&resultId=206490)||
|[750924](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750924)|dotnet/runtime|[System.Runtime.Extensions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=750924&view=ms.vss-test-web.build-test-results-tab&runId=19016074&resultId=206499)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|5|

**Comment by matouskozak** [comment]
Likely introduced by the new tests from https://github.com/dotnet/runtime/pull/105152 @tarekgh. I see there is an assumption that on iOS and TvOS the times should be zero. Is this something we should reconsider in the test design and try to enable the "regular" path for these platforms?

**Comment by matouskozak** [comment]
The failures are still present on the CI https://dev.azure.com/dnceng-public/public/_build/results?buildId=763399&view=logs&j=acac6bf3-3edd-5022-4e45-3362a02520b1&t=1de8bf71-8fe5-5d5c-4360-8c2eb159d012. This time only on `tvos_arm64_release_allsubsets_mono` pipeline (actual tvOS device, not simulator) @tarekgh 

```
[18:41:26.5988610] 2024-08-01 15:41:26.621 System.Runtime.Extensions.Tests[26622:107344504] 	[FAIL] System.Tests.EnvironmentTests.TestCpuUsage
[18:41:26.5988980] Assert.NotEqual() Failure: Values are equal
[18:41:26.5989060] Expected: Not 00:00:00
[18:41:26.5989120] Actual:       00:00:00
[18:41:26.5989170]    at System.Tests.EnvironmentTests.TestCpuUsage()
```
