### ISSUE TITLE
Ctor_Dispose_HandleClosedIfOwnsHandle failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#105379]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=752819
Build error leg or test failing: System.Net.Sockets.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/105344

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["Ctor_Dispose_HandleClosedIfOwnsHandle", "Values differ"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
Windows.Nano.1809.Amd64.Open

    System.Net.Sockets.Tests.CreateSocket.Ctor_Dispose_HandleClosedIfOwnsHandle(ownsHandle: True) [FAIL]
      Assert.Equal() Failure: Values differ
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/CreateSocketTests.cs(709,0): at System.Net.Sockets.Tests.CreateSocket.Ctor_Dispose_HandleClosedIfOwnsHandle(Boolean ownsHandle)
           at InvokeStub_CreateSocket.Ctor_Dispose_HandleClosedIfOwnsHandle(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Process terminated. Assertion failed.
ReleaseHandle failed. handle:8684
   at System.Net.Sockets.SafeSocketHandle.CloseHandle(Boolean abortive, Boolean canceledOperations) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs:line 134
   at System.Net.Sockets.SafeSocketHandle.ReleaseHandle() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs:line 86
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 266
   at System.Runtime.InteropServices.SafeHandle.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 108
   at System.Net.Sockets.Socket.Dispose(Boolean disposing) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3259
   at System.Net.Sockets.Socket.Finalize() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3381
   at System.GC.RunFinalizers() in /_/src/coreclr/System.Private.CoreLib/src/System/GC.CoreCLR.cs:line 320
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=752819
**Error message validated:** `[Ctor_Dispose_HandleClosedIfOwnsHandle Values differ`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/24/2024 3:50:08 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[752819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752819)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=752819&view=ms.vss-test-web.build-test-results-tab&runId=19074394&resultId=222002)|dotnet/runtime#105344|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by jkotas** [comment]
This is bad test. The test is trying to close a random handle and expected it to fail. It won't work if some other thread opened a handle that happens to have the same value.
