### ISSUE TITLE
Test failure: Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105377]
**Failed in:** [runtime-coreclr libraries-jitstress 20240723.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=751494&view=ms.vss-test-web.build-test-results-tab&runId=19032338&resultId=175113&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstress1-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 35

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    912 BrokerInfrastructure, DcomLaunch, Power,    
                                   SystemEventsBroker                          
svchost.exe                    480 RpcEptMapper, RpcSs                         
svchost.exe                    644 LSM                                         
svchost.exe                   1048 CryptSvc                                    
svchost.exe                   1064 TermService                                 
svchost.exe                   1140 lmhosts                                     
svchost.exe                   1168 NcbService                                  
svchost.exe                   1264 nsi                                         
svchost.exe                   1276 TimeBrokerSvc                               
svchost.exe                   1340 AppIDSvc                                    
svchost.exe                   1376 gpsvc                                       
svchost.exe                   1396 netprofm                                    
svchost.exe                   1472 vmicheartbeat                               
svchost.exe                   1492 vmickvpexchange                             
svchost.exe                   1540 vmicshutdown                                
svchost.exe                   1560 Schedule                                    
svchost.exe                   1624 vmictimesync                                
svchost.exe                   1664 CoreMessagingRegistrar                      
svchost.exe                   1688 UmRdpService                                
svchost.exe                   1796 ProfSvc                                     
svchost.exe                   2004 Dnscache                                    
svchost.exe                   2024 EventLog                                    
svchost.exe                   1128 LanmanWorkstation                           
svchost.exe                   1764 UserManager                                 
svchost.exe                   1864 SysMain                                     
svchost.exe                   2056 EventSystem                                 
svchost.exe                   2068 Themes                                      
svchost.exe                   2220 SENS                                        
svchost.exe                   2264 SessionEnv                                  
svchost.exe                   2376 AudioEndpointBuilder                        
svchost.exe                   2384 CertPropSvc                                 
svchost.exe                   2424 FontCache                                   
svchost.exe                   2436 DispBrokerDesktopSvc                        
svchost.exe                   2496 Dhcp                                        
svchost.exe                   2612 Audiosrv                                    
svchost.exe                   2700 WinHttpAutoProxySvc                         
svchost.exe                   2740 TextInputManagementService                  
svchost.exe                   2828 Wcmsvc                                      
svchost.exe                   2840 DusmSvc                                     
svchost.exe                   2892 ShellHWDetection                            
svchost.exe                   2136 BFE, mpssvc                                 
svchost.exe                   3128 DiagTrack                                   
svchost.exe                   3136 iphlpsvc                                    
svchost.exe                   3148 DPS                                         
svchost.exe                   3240 LanmanServer                      
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.Extensions.Hosting.WindowsServiceTester.Dispose(Boolean disposing) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 147
   at System.ComponentModel.Component.Dispose() in /_/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/Component.cs:line 73
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs:line 85
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by buyaa-n** [comment]
> Stack trace:

From the `Stack trace` the `ExceptionOnStartIsPropagatedis` test is actually finished successfully: 
`at Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStartIsPropagated() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs:line 85`
https://github.com/dotnet/runtime/blob/d3eeb0ea697fe9f3e6ff362cd944fe3883a451f3/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceLifetimeTests.cs#L84-L85
It is somehow failed on `RemoteInvokeHandle.Dispose(bool)` and [threw](https://source.dot.net/#Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs,225):
`at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225`
Don't know what team owns it, it could be just network failure, whatever it is not runtime issue, so closing
