### ISSUE TITLE
ProcessThreadTests.TestStartTimeProperty failure in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#105526]
```
    System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty [FAIL]
      Assert.Single() Failure: The collection did not contain any matching items
      Expected:   (predicate expression)
      Collection: [System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, System.Diagnostics.ProcessThread, ···]
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessThreadTests.cs(156,0): at System.Diagnostics.Tests.ProcessThreadTests.<>c__DisplayClass4_2.<TestStartTimeProperty>b__0()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2396,0): at System.Threading.Tasks.Task.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2384,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__292_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(179,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(203,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2342,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessThreadTests.cs(149,0): at System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty()
        --- End of stack trace from previous location ---
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=755830
Build error leg or test failing: System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty
Pull request: https://github.com/dotnet/runtime/pull/105519

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Diagnostics.Tests.ProcessThreadTests.TestStartTimeProperty [FAIL]","The collection did not contain any matching items"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by Jozkee** [comment]
https://github.com/dotnet/runtime/pull/104972 was an attempt to fix it but looks like ProcessInfo.Threads is not being Refresh()'d properly.

**Comment by adamsitnik** [comment]
I wonder why it fails only on Mono?

**Comment by danmoseley** [comment]
**Analysis**

The test's second half starts a `LongRunning` task (dedicated OS thread), then immediately does `p.Refresh()` followed by `Assert.Single(p.Threads, t => t.Id == newThreadId)`. On Linux, `p.Threads` enumerates `/proc/self/task/` — there's a known small window after thread creation where the new thread's `/proc` entry isn't visible yet.

PR #104972 (which fixed #103448) improved correctness by matching the exact thread ID instead of picking the newest-by-StartTime, but this made the test stricter: the `/proc` visibility race now causes a hard `Assert.Single` failure instead of silently matching a wrong thread.

The Mono-only pattern is consistent with Mono's thread startup having different timing that widens this window.

**Suggested fix**

Replace the single-shot `Assert.Single` with a retry loop that re-calls `Refresh()`, giving `/proc` time to reflect the new thread:

```csharp
await Task.Factory.StartNew(() =>
{
    int newThreadId = GetCurrentThreadId();

    ProcessThread newThread = null;
    for (int i = 0; i < 10 && newThread is null; i++)
    {
        if (i > 0) Thread.Sleep(100);
        p.Refresh();
        newThread = p.Threads.Cast<ProcessThread>()
            .FirstOrDefault(t => t.Id == newThreadId);
    }

    Assert.NotNull(newThread);
    Assert.InRange(newThread.StartTime.ToUniversalTime(),
        curTime - allowedWindow,
        DateTime.Now.ToUniversalTime() + allowedWindow);
}, CancellationToken.None, TaskCreationOptions.LongRunning,
   TaskScheduler.Default);
```

This is low-risk — it preserves the exact-ID matching from #104972 while tolerating the `/proc` propagation delay. If the root cause is something deeper (e.g., Mono returning incorrect thread IDs), the retry would still fail and surface that.

Happy to put up a PR for this.

**Comment by mrek-msft** [comment]
Failed again on release branch in PR https://github.com/dotnet/runtime/pull/131852

**Comment by adamsitnik** [comment]
> Failed again on release branch in PR [#131852](https://github.com/dotnet/runtime/pull/131852)

The fix got merged into main and was part of 11 Preview 4. We can backport it to release branches (8, 9 and 10?) if you believe it's worth it.

**Comment by mrek-msft** [comment]
Kusto has 8 failures on release branches since April. It is approx. 2 per month in average.
