### ISSUE TITLE
[mono] Vector shuffle failures in Mono LLVM scenario

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#105537]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747
Build error leg or test failing: `Microsoft.Bcl.Memory.Tests`, `System.Runtime.Intrinsics.Tests `, `System.Security.Cryptography.Tests`
Affected CI: `tvos_arm64_release_allsubsets_mono` (`runtime-extra-platforms`). Note: x64 LLVM coverage is not working currently due to https://github.com/dotnet/runtime/issues/105319
Range of commits: https://github.com/dotnet/runtime/compare/d73e625c...7134e1e6

Full logs: 
[net.dot.System.Security.Cryptography.Tests.log](https://github.com/user-attachments/files/16386575/net.dot.System.Security.Cryptography.Tests.log)
[net.dot.System.Runtime.Intrinsics.Tests.log](https://github.com/user-attachments/files/16386576/net.dot.System.Runtime.Intrinsics.Tests.log)
[net.dot.Microsoft.Bcl.Memory.Tests.log](https://github.com/user-attachments/files/16386577/net.dot.Microsoft.Bcl.Memory.Tests.log)

Stack trace example for `System.Runtime.Intrinsics.Tests`:
```
[17:54:10.7789630] 2024-07-25 14:54:10.805 System.Runtime.Intrinsics.Tests[3591:104610303] 1) 	[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest
[17:54:10.7789730] 2024-07-25 14:54:10.806 System.Runtime.Intrinsics.Tests[3591:104610303]    Assembly:  [System.Runtime.Intrinsics.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[17:54:10.7789800]    Exception messages: Assert.Equal() Failure: Values differ
[17:54:10.7789860] Expected: 8
[17:54:10.7789940] 2024-07-25 14:54:10.806 System.Runtime.Intrinsics.Tests[3591:104610303] Actual:   0   Exception stack traces:    at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest()
[17:54:10.7790010]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:54:10.7790120]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[17:54:10.7790190] 2024-07-25 14:54:10.806 System.Runtime.Intrinsics.Tests[3591:104610303]    Execution time: 0.0073298
[17:54:10.7790280] 2024-07-25 14:54:10.806 System.Runtime.Intrinsics.Tests[3591:104610303] 2) 	[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SingleCreateFromArrayTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SingleCreateFromArrayTest
[17:54:10.7806070] 2024-07-25 14:54:10.808 System.Runtime.Intrinsics.Tests[3591:104610303]    Assembly:  [System.Runtime.Intrinsics.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[17:54:10.7806290]    Exception messages: Assert.Equal() Failure: Values differ
[17:54:10.7806370] Expected: <0, 0>
[17:54:10.7826440] 2024-07-25 14:54:10.809 System.Runtime.Intrinsics.Tests[3591:104610303] Actual:   <1, 2>   Exception stack traces:    at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SingleCreateFromArrayTest()
[17:54:10.7826640]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:54:10.7826730]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[17:54:10.7826790]    Execution time: 0.0058828
[17:54:10.7827190] 2024-07-25 14:54:10.810 System.Runtime.Intrinsics.Tests[3591:104610303] 3) 	[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64UInt32ShuffleOneInputWithDirectVectorTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64UInt32ShuffleOneInputWithDirectVectorTest
[17:54:10.7827320] 2024-07-25 14:54:10.810 System.Runtime.Intrinsics.Tests[3591:104610303]    Assembly:  [System.Runtime.Intrinsics.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[17:54:10.7827390]    Exception messages: Assert.Equal() Failure: Values differ
[17:54:10.7827440] Expected: 2
[17:54:10.7827520] 2024-07-25 14:54:10.810 System.Runtime.Intrinsics.Tests[3591:104610303] Actual:   0   Exception stack traces:    at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64UInt32ShuffleOneInputWithDirectVectorTest()
[17:54:10.7827590]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:54:10.7827650]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[17:54:10.7828010] 2024-07-25 14:54:10.810 System.Runtime.Intrinsics.Tests[3591:104610303]    Execution time: 0.0033379
[17:54:10.7828650] 2024-07-25 14:54:10.810 System.Runtime.Intrinsics.Tests[3591:104610303] 4) 	[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64Int16ShuffleOneInputTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64Int16ShuffleOneInputTest
[17:54:10.7828830] 2024-07-25 14:54:10.810 System.Runtime.Intrinsics.Tests[3591:104610303]    Assembly:  [System.Runtime.Intrinsics.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[17:54:10.7828900]    Exception messages: Assert.Equal() Failure: Values differ
[17:54:10.7828950] Expected: 4
[17:54:10.7838870] 2024-07-25 14:54:10.811 System.Runtime.Intrinsics.Tests[3591:104610303] Actual:   0   Exception stack traces:    at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64Int16ShuffleOneInputTest()
[17:54:10.7839030]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:54:10.7839100]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[17:54:10.7839150]    Execution time: 0.0020901
[17:54:10.7854900] 2024-07-25 14:54:10.813 System.Runtime.Intrinsics.Tests[3591:104610303] 5) 	[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64ByteShuffleOneInputWithZeroIndicesTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64ByteShuffleOneInputWithZeroIndicesTest
[17:54:10.7855200] 2024-07-25 14:54:10.813 System.Runtime.Intrinsics.Tests[3591:104610303]    Assembly:  [System.Runtime.Intrinsics.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[17:54:10.7855260]    Exception messages: Assert.Equal() Failure: Values differ
[17:54:10.7855300] Expected: 1
[17:54:10.7868500] 2024-07-25 14:54:10.814 System.Runtime.Intrinsics.Tests[3591:104610303] Actual:   0   Exception stack traces:    at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64ByteShuffleOneInputWithZeroIndicesTest()
[17:54:10.7868640]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:54:10.7868700]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[17:54:10.7868980] 2024-07-25 14:54:10.814 System.Runtime.Intrinsics.Tests[3591:104610303]    Execution time: 0.0036366
[17:54:10.7869600] 2024-07-25 14:54:10.814 System.Runtime.Intrinsics.Tests[3591:104610303] 6) 	[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithZeroIndicesTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithZeroIndicesTest
[17:54:10.7870160] 2024-07-25 14:54:10.814 System.Runtime.Intrinsics.Tests[3591:104610303]    Assembly:  [System.Runtime.Intrinsics.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[17:54:10.7870310]    Exception messages: Assert.Equal() Failure: Values differ
[17:54:10.7870370] Expected: 1
[17:54:10.7870440] 2024-07-25 14:54:10.815 System.Runtime.Intrinsics.Tests[3591:104610303] Actual:   0   Exception stack traces:    at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithZeroIndicesTest()
[17:54:10.7870520]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:54:10.7870580]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[17:54:10.7870810] 2024-07-25 14:54:10.815 System.Runtime.Intrinsics.Tests[3591:104610303]    Execution time: 0.0019761
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=755747
**Error message validated:** `[[FAIL] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest   Test name: System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SByteShuffleOneInputWithDirectVectorTest`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/26/2024 4:35:54 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by matouskozak** [comment]
Possibly caused by https://github.com/dotnet/runtime/pull/105299 @tannergooding @fanyang-mono

**Comment by tannergooding** [comment]
Taking a look, this is interesting because each new path is actually supposed to be explicitly filtering on `vector_size == 16`

**Comment by tannergooding** [comment]
Found the issue, there was a path that was incorrectly creating a constant for `vector_size == 8`.
