### ISSUE TITLE
Test failure: baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105608]
**Failed in:** [runtime-coreclr r2r-extra 20240727.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757985&view=ms.vss-test-web.build-test-results-tab&runId=19230564&resultId=120388&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitstressregs1 @ OSX.1200.ARM64.Open
    - baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.cmd
```

**Error message:**
```
 /private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/baseservices-exceptions/../unittests/CollidedUnwind/CollidedUnwind.sh: line 315: -r:/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/IL-CG2/*.dll: No such file or directory
/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/baseservices-exceptions/../unittests/CollidedUnwind/CollidedUnwind.sh: line 254:  5763 Segmentation fault: 11  (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/B6C0099A/w/B68609CD/uploads/unittests/CollidedUnwind/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/IL-CG2/CollidedUnwind.dll
20:30:01
Response file: /private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.dll.rsp
/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/IL-CG2/CollidedUnwind.dll
-o:/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.dll
-r:/tmp/helix/working/B6C0099A/p/System.*.dll
-r:/tmp/helix/working/B6C0099A/p/Microsoft.*.dll
-r:/tmp/helix/working/B6C0099A/p/xunit.*.dll
-r:/tmp/helix/working/B6C0099A/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B6C0099A/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.dll.rsp  
[createdump] Gathering state for process 5763 
[createdump] Crashing thread 5a1f2b signal 11 (000b)
[createdump] Writing crash report to file /cores/coredump.5763.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.5763.dmp
[createdump] Written 482673160 bytes (29460 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 1082ms
Running R2RDump:  dotnet /tmp/helix/working/B6C0099A/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.dll --out /private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 467
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 449
20:30:11
Crossgen2 failed with exitcode: 139
in ReleaseLock
Test failed. Trying to see if dump file was created in /cores since 7/27/2024 8:30:01 PM
Processing /cores/coredump.5763.dmp.crashreport.json
Printing stacktrace from '/cores/coredump.5763.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/B6C0099A/w/B68609CD/e/baseservices/exceptions/baseservices-exceptions'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 498
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at Co
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor142|0_143(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-07-28T03:17:26.588Z | runtime-coreclr r2r-extra | Checked-jitstressregs1 | osx.1200.arm64.open | arm64 | baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.cmd | Failed | {"Reason":"Schedule","System.PhaseAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20240727.1","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","System.JobAttempt":"1","configuration":"Checked-jitstressregs1","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","DefinitionId":"114","System.StageAttempt":"1","architecture":"arm64","DefinitionName":"runtime-coreclr   r2r-extra","System.JobName":"__default","BuildId":"757985","Project":"public","AzurePipelinesTestRunId":"19230564","System.StageName":"Build"} | Schedule
2024-07-21T22:16:28.524Z | runtime-coreclr gcstress-extra | Checked-gcstress0xc_jitstress1 | osx.1200.arm64.open | arm64 | baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"18964484","BuildId":"749452","BuildNumber":"20240721.1","DefinitionId":"113","Reason":"Schedule","System.StageAttempt":"1","Project":"public","System.StageName":"Build","architecture":"arm64","System.JobAttempt":"1","configuration":"Checked-gcstress0xc_jitstress1","System.PhaseName":"run_test_p1__osx_arm64_checked","System.PhaseAttempt":"1","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr   gcstress-extra","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e"} | Schedule
2024-06-23T19:21:10.299Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | baseservices/exceptions/unittests/CollidedUnwind/CollidedUnwind.cmd | Failed | {"AzurePipelinesTestRunId":"17969654","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-jitstress_random_1","Project":"public","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageAttempt":"1","System.StageName":"Build","System.JobName":"__default","System.PhaseAttempt":"1","DefinitionName":"runtime-coreclr   jitstress-random","BuildId":"717429","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"159","architecture":"arm64","Reason":"Schedule","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildNumber":"20240623.1"} | Schedule

**Comment by mangod9** [comment]
Old issue which hasn't reproed recently.
