### ISSUE TITLE
Access violation in CEEInfo::getCallInfo

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#105710]
### Description

When running with our profiler attached, we discovered that powershell sometimes crashes from an access violation with the following callstack:

```
coreclr!MethodTable::GetFlag
coreclr!MethodTable::IsArray
coreclr!TypeHandle::IsArray
coreclr!TypeHandle::IsSharedByGenericInstantiations
coreclr!CEEInfo::getCallInfo
clrjit!Compiler::eeGetCallInfo
clrjit!Compiler::impImportBlockCode
clrjit!Compiler::impImportBlock
clrjit!Compiler::impImport
clrjit!Compiler::fgImport
clrjit!Phase::Run
clrjit!DoPhase
clrjit!Compiler::compCompile
clrjit!Compiler::compCompileHelper
clrjit!Compiler::compCompile
clrjit!jitNativeCode
clrjit!CILJit::compileMethod
coreclr!invokeCompileMethodHelper
coreclr!invokeCompileMethod
coreclr!UnsafeJitFunction
coreclr!MethodDesc::JitCompileCodeLocked
coreclr!MethodDesc::JitCompileCodeLockedEventWrapper
coreclr!MethodDesc::JitCompileCode
coreclr!MethodDesc::PrepareILBasedCode
coreclr!MethodDesc::PrepareCode
coreclr!CodeVersionManager::PublishVersionableCodeIfNecessary
coreclr!MethodDesc::DoPrestub
coreclr!PreStubWorker
coreclr!ThePreStub
System_Net_Http!System.Net.Http.HttpClientHandler.SendAsync
```

There's a chance that our profiler might be emitting invalid metadata or IL code (the crash happens in a rejitted method) but I would need a bit of help to figure out. Either way, I feel like this should result in a `BadImageFormatException` rather an access violation.

Luckily I have a crash dump and a TTD trace so I should be able to get to the bottom of it. However I'm unfamiliar with the JIT code so I would need a bit of help.

In `getCallInfo`, the execution gets [to this bit](https://github.com/dotnet/runtime/blob/ee3b1f0d5ba90f0cdbf04a59c0624fc87fb2cc8b/src/coreclr/vm/jitinterface.cpp#L5118): 

```
        if (!exactType.IsTypeDesc() && !pTargetMD->IsArray())
        {
            // Because of .NET's notion of base calls, exactType may point to a sub-class
            // of the actual class that defines pTargetMD.  If the JIT decides to inline, it is
            // important that they 'match', so we fix exactType here.
            exactType = pTargetMD->GetExactDeclaringType(exactType.AsMethodTable());
            _ASSERTE(!exactType.IsNull());
        }

        pResult->contextHandle = MAKE_CLASSCONTEXT(exactType.AsPtr());
        if (exactType.IsSharedByGenericInstantiations())
        {
            pResult->exactContextNeedsRuntimeLookup = TRUE;
        }
```

`pTargetMD->GetExactDeclaringType(exactType.AsMethodTable())` returns NULL, so `exactType.IsSharedByGenericInstantiations()` then causes the access violation. 
Before that, `exactType` comes from `TypeHandle exactType = TypeHandle(pResolvedToken->hClass);`.

My first question is related to `pResolvedToken`. In Windbg, calling `!dumpmt` on the value of `pResolvedToken->hClass` returns the expected MT. However, calling `!dumpmd` on `pResolvedToken->hMethod` fails (`00007FFB8FE32B38 is not a MethodDesc`). Am I right to assume that `hMethod` should be a MethodDesc as expected by SOS? Knowing would help me understand where things start to get wrong.

### Reproduction Steps

- Download the Datadog tracer: https://github.com/DataDog/dd-trace-dotnet/releases/download/v2.56.0/windows-tracer-home.zip
- Unzip it and run `dd-dotnet.cmd run -- pwsh -NoLogo -NoProfile -Command "iisreset"`

### Expected behavior

The iisreset command is executed.

### Actual behavior

Powershell crashes: 

```
C:\Users\kevin.gosse>dd-dotnet run -- pwsh -NoLogo -NoProfile -Command "iisreset"
Fatal error. Internal CLR error. (0x80131506)
   at System.Net.Http.SocketsHttpHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClientHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<<SendAsync>g__Core|83_0>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](<<SendAsync>g__Core|83_0>d ByRef)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationTokenSource, Boolean, System.Threading.CancellationTokenSource, System.Threading.CancellationToken)
   at System.Net.Http.HttpClient.SendAsync(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationToken)
   at Datadog.Trace.Agent.Transports.HttpClientRequest+<PostAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Datadog.Trace.Agent.Transports.HttpClientRequest+<PostAsync>d__10, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<PostAsync>d__10 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Datadog.Trace.Agent.Transports.HttpClientRequest+<PostAsync>d__10, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<PostAsync>d__10 ByRef)
   at Datadog.Trace.Agent.Transports.HttpClientRequest.PostAsync(System.ArraySegment`1<Byte>, System.String, System.String)
   at Datadog.Trace.Agent.Transports.HttpClientRequest.PostAsync(System.ArraySegment`1<Byte>, System.String)
   at Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport+<PushTelemetry>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport+<PushTelemetry>d__9, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<PushTelemetry>d__9 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Datadog.Trace.Telemetry.TelemetryPushResult, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].Start[[Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport+<PushTelemetry>d__9, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<PushTelemetry>d__9 ByRef)
   at Datadog.Trace.Telemetry.Transports.JsonTelemetryTransport.PushTelemetry(Datadog.Trace.Telemetry.TelemetryData)
   at Datadog.Trace.Telemetry.TelemetryTransportManager+<TryPushTelemetry>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Datadog.Trace.Telemetry.TelemetryTransportManager+<TryPushTelemetry>d__9, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<TryPushTelemetry>d__9 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Datadog.Trace.Telemetry.TelemetryTransportManager+<TryPushTelemetry>d__9, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<TryPushTelemetry>d__9 ByRef)
   at Datadog.Trace.Telemetry.TelemetryTransportManager.TryPushTelemetry(Datadog.Trace.Telemetry.TelemetryData)
   at Datadog.Trace.Telemetry.TelemetryController+<PushTelemetry>d__36.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Datadog.Trace.Telemetry.TelemetryController+<PushTelemetry>d__36, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<PushTelemetry>d__36 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Datadog.Trace.Telemetry.TelemetryController+<PushTelemetry>d__36, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]](<PushTelemetry>d__36 ByRef)
   at Datadog.Trace.Telemetry.TelemetryController.PushTelemetry(Boolean, Boolean)
   at Datadog.Trace.Telemetry.TelemetryController+<PushTelemetryLoopAsync>d__35.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Datadog.Trace.Telemetry.TelemetryController+<PushTelemetryLoopAsync>d__35, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Datadog.Trace.Telemetry.TelemetryController+<PushTelemetryLoopAsync>d__35, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Datadog.Trace.Telemetry.TelemetryController+<PushTelemetryLoopAsync>d__35, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Datadog.Trace.Telemetry.TelemetryController+Scheduler+<WaitForNextInterval>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Datadog.Trace.Telemetry.TelemetryController+Scheduler+<WaitForNextInterval>d__26, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Datadog.Trace.Telemetry.TelemetryController+Scheduler+<WaitForNextInterval>d__26, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Datadog.Trace.Telemetry.TelemetryController+Scheduler+<WaitForNextInterval>d__26, Datadog.Trace, Version=3.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.__Canon)
   at System.Threading.Tasks.TaskFactory+CompleteOnInvokePromise`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Invoke(System.Threading.Tasks.Task)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by jkotas** [comment]
> Am I right to assume that hMethod should be a MethodDesc as expected by SOS?

Yes.

**Comment by kevingosse** [comment]
Thanks. I found an issue with our instrumentation (we were not synchronizing some code that created metadata token) and that fixed the crash.
