### ISSUE TITLE
System.Net.Quic.Functional.Tests.CertificateCallbackThrowPropagates failed

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#105778]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=761886
Build error leg or test failing: Build / linux-arm64 Debug Mono_MiniJIT_LibrariesTests / Send to Helix
Pull request: https://github.com/dotnet/runtime/pull/105766

```
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on [2 threads], stop on fail = off)
MsQuic supported and using 'libmsquic.so 2.3.6.508949 (93878039a7fba95b83f1887b21c92f88325cfa31)'.
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
    System.Net.Quic.Tests.MsQuicTests.QuicRootedConnectionGetsReleased_ConnectFails [SKIP]
      Condition(s) not met: "IsNotMonoRuntime"
    System.Net.Quic.Tests.MsQuicTests.QuicRootedObjectGetReleased [SKIP]
      Condition(s) not met: "IsNotMonoRuntime"
    System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates [FAIL]
      Assert.Throws() Failure: Exception type was not an exact match
      Expected: typeof(System.Security.Authentication.AuthenticationException)
      Actual:   typeof(System.Net.Quic.QuicException)
      ---- System.Net.Quic.QuicException : Connection handshake was canceled due to the configured timeout of 00:00:10 seconds elapsing.
      -------- System.OperationCanceledException : The operation was canceled.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(387,0): at System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates()
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(394,0): at System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs(276,0): at System.Net.Quic.QuicListener.StartConnectionHandshake(QuicConnection connection, SslClientHelloInfo clientHello)
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs(292,0): at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Quic.QuicListener.<StartConnectionHandshake>d__16, System.Net.Quic, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecutionContextCallback(Object s)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(264,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs(376,0): at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Quic.QuicListener.<StartConnectionHandshake>d__16, System.Net.Quic, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs(347,0): at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Quic.QuicListener.<StartConnectionHandshake>d__16, System.Net.Quic, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecuteFromThreadPool(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs(1096,0): at System.Threading.ThreadPoolWorkQueue.Dispatch()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs(128,0): at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
        /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs(218,0): at System.Threading.Thread.StartCallback()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs(190,0): at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(387,0): at System.Net.Quic.Tests.MsQuicTests.<>c__DisplayClass10_0.<<CertificateCallbackThrowPropagates>b__2>d.MoveNext()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(119,0): at System.Net.Quic.ValueTaskSource.TryComplete(Exception exception)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(166,0): at System.Net.Quic.ValueTaskSource.TrySetException(Exception exception)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(70,0): at System.Net.Quic.ValueTaskSource.<>c.<TryInitialize>b__10_0(Object obj, CancellationToken cancellationToken)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs(998,0): at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs(1216,0): at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs(813,0): at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs(699,0): at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs(35,0): at System.Threading.CancellationTokenSource.TimerCallback(Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs(723,0): at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs(686,0): at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs(334,0): at System.Threading.TimerQueue.FireNextTimers()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/TimerQueue.Portable.cs(140,0): at System.Threading.TimerQueue.System.Threading.IThreadPoolWorkItem.Execute()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs(1096,0): at System.Threading.ThreadPoolWorkQueue.Dispatch()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs(128,0): at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
        /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs(218,0): at System.Threading.Thread.StartCallback()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs(245,0): at System.Net.Quic.QuicListener.StartConnectionHandshake(QuicConnection connection, SslClientHelloInfo clientHello)
      Output:
        System.Net.Quic.QuicException: User configured callback failed.
         ---> System.ArithmeticException: foobar
           at System.Net.Quic.Tests.MsQuicTests.<>c__DisplayClass10_0.<CertificateCallbackThrowPropagates>b__1(Object sender, X509Certificate cert, X509Chain chain, SslPolicyErrors errors) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 380
           at System.Net.Quic.QuicConnection.SslConnectionOptions.ValidateCertificate(X509Certificate2 certificate, Span`1 certData, Span`1 chainData) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.SslConnectionOptions.cs:line 228
           --- End of inner exception stack trace ---
           at System.Net.Quic.QuicConnection.SslConnectionOptions.ValidateCertificate(X509Certificate2 certificate, Span`1 certData, Span`1 chainData) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.SslConnectionOptions.cs:line 255
           at System.Net.Quic.QuicConnection.SslConnectionOptions.StartAsyncCertificateValidation(IntPtr certificatePtr, IntPtr chainPtr) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.SslConnectionOptions.cs:line 135
           at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 176
           at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 428
           at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 84
           at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 99
           at System.Net.Quic.Tests.MsQuicTests.<>c__DisplayClass10_0.<<CertificateCallbackThrowPropagates>b__3>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 385
        --- End of stack trace from previous location ---
           at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in /_/src/Microsoft.DotNet.XUnitAssert/src/Record.cs:line 105
MsQuic Counters:
    CONN_CREATED 1606
    CONN_HANDSHAKE_FAIL 26
    CONN_APP_REJECT 8
    CONN_LOAD_REJECT N/A
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Net.Quic.QuicException : Connection handshake was canceled due to the configured timeout of 00:00:10 seconds elapsing.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=761886
**Error message validated:** `[System.Net.Quic.QuicException : Connection handshake was canceled due to the configured timeout of 00:00:10 seconds elapsing.`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 7/31/2024 8:43:05 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[762172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762172)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762172&view=ms.vss-test-web.build-test-results-tab&runId=19366406&resultId=211355)|dotnet/runtime#105672|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240731.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=761255&view=ms.vss-test-web.build-test-results-tab&runId=19335490&resultId=211643&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2-Ubuntu.2204.Amd64.Open
    - System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates
net9.0-linux-Release-x64-disabler2r-Ubuntu.2204.Amd64.Open
    - System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates
```

**Error message:**
```
 Assert.Throws() Failure: Exception type was not an exact match
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.Net.Quic.QuicException)
---- System.Net.Quic.QuicException : Connection handshake was canceled due to the configured timeout of 00:00:10 seconds elapsing.
-------- System.OperationCanceledException : The operation was canceled.
```

**Stack trace:**
```
   at System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 387
   at System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 369
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.QuicListener.StartConnectionHandshake(QuicConnection connection, SslClientHelloInfo clientHello) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs:line 276
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 290
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 264
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 354
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1096
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 128
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs:line 190
   at System.Net.Quic.Tests.MsQuicTests.<>c__DisplayClass10_0.<<CertificateCallbackThrowPropagates>b__2>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 387
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.ValueTaskSource.TryComplete(Exception exception) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 119
   at System.Net.Quic.ValueTaskSource.<>c.<TryInitialize>b__10_0(Object obj, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 70
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 998
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 813
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 699
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 686
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 334
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1096
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 128
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskS
```
