### ISSUE TITLE
[iOS/tvOS] BigInteger tests running out-of-memory 

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#105753]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=757260&view=ms.vss-test-web.build-test-results-tab&runId=19205408&resultId=107014&paneView=debug
Build error leg or test failing: `System.Tests.DecimalTests+BigInteger[Add/Div/Mul].Test`
Affected CI: `ios_arm64_release_allsubsets_mono`, `ios_arm64_release_allsubsets_mono`
The issues doesn't seem to be 100% reproducible and is failing occasionally on the CI

The first failure on rolling build CI happenned on 24th of July 10:00 (CEST) https://dev.azure.com/dnceng-public/public/_build/results?buildId=753200&view=results corresponding to https://github.com/dotnet/runtime/commit/703df3b3d7ef6c92ffdf3e9221d82539a9dd5fce

Stack trace example:
```
[17:51:30.6376040] 2024-07-26 17:51:30.636 System.Runtime.Tests[40033:121905450] 	[FAIL] System.Tests.DecimalTests+BigIntegerAdd.Test
[17:51:30.6376740] System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
[17:51:30.6377030]    at System.GC.AllocateArray[UInt32](Int32 length, Boolean pinned)
[17:51:30.6378010] 2024-07-26 17:51:30.636 System.Runtime.Tests[40033:121905450]    at System.GC.AllocateUninitializedArray[UInt32](Int32 length, Boolean pinned)
[17:51:30.6378340]    at System.Buffers.SharedArrayPool`1[[System.UInt32, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Rent(Int32 minimumLength)
[17:51:30.6380530] 2024-07-26 17:51:30.636 System.Runtime.Tests[40033:121905450]    at System.Numerics.BigInteger.Multiply(ReadOnlySpan`1 left, Int32 leftSign, ReadOnlySpan`1 right, Int32 rightSign)
[17:51:30.6380990]    at System.Numerics.BigInteger.op_Multiply(BigInteger left, BigInteger right)
[17:51:30.6381220]    at System.Tests.DecimalTests.BigDecimal.Add(BigDecimal value, Boolean& overflow)
[17:51:30.6381330] 2024-07-26 17:51:30.636 System.Runtime.Tests[40033:121905450]    at System.Tests.DecimalTests.BigIntegerAdd.Test()
[17:51:30.6381450]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[17:51:30.6381530]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

```
[16:51:43.0371740] 2024-07-29 13:51:43.082 System.Runtime.Tests[36143:107068255] 	[FAIL] System.Tests.DecimalTests+BigIntegerMul.Test
[16:51:43.0372230] Assert.Equal() Failure: -6773724285713928637.9 * 0.000000000000001533938174
[16:51:43.0372340] Expected: 0.0000000000000000000000000
[16:51:43.0372420] Actual:   -10390.474262007477981186633195
[16:51:43.0372510] 2024-07-29 13:51:43.082 System.Runtime.Tests[36143:107068255]    at System.Tests.DecimalTests.BigIntegerMul.Test()
[16:51:43.0372600]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[16:51:43.0372690]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[16:51:43.0390030] 2024-07-29 13:51:43.084 System.Runtime.Tests[36143:107068255] System.Tests.DecimalTests+BigIntegerMul 0.096197 ms
[16:51:43.0391760] 2024-07-29 13:51:43.085 System.Runtime.Tests[36143:107068255] 
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage":,
  "ErrorPattern": "(System\\.OutOfMemoryException : Insufficient memory to continue the execution of the program\\.)|(Assert\\.Equal\\(\\) Failure: -23057707503038771933 \\* -1)|(Assert\\.Equal\\(\\) Failure: -6773724285713928637\\.9 \\* 0\\.000000000000001533938174)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[757260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757260)|dotnet/runtime|[System.Tests.DecimalTests+BigIntegerAdd.Test](https://dev.azure.com/dnceng-public/public/_build/results?buildId=757260&view=ms.vss-test-web.build-test-results-tab&runId=19205408&resultId=107014)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=763399
**Error message validated:** `[(System\.OutOfMemoryException : Insufficient memory to continue the execution of the program\.)|(Assert\.Equal\(\) Failure: -23057707503038771933 \* -1)|(Assert\.Equal\(\) Failure: -6773724285713928637\.9 \* 0\.000000000000001533938174)`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 8/7/2024 5:25:59 PM UTC

**Comment by matouskozak** [comment]
No longer failing on rolling-builds.

**Comment by matouskozak** [comment]
Still occasionally failing, e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=763399&view=results

**Comment by matouskozak** [comment]
![image](https://github.com/user-attachments/assets/77b895e4-e674-48f4-9451-54dfda59af1e)

**Comment by vitek-karas** [comment]
@matouskozak Could you please create a separate issue for the functional failures - the title of this one talks just about OOM conditions which are probably much less of a problem. Computing wrong results is more serious problem.

**Comment by matouskozak** [comment]
Likely fixed by https://github.com/dotnet/runtime/pull/106313
