### ISSUE TITLE
NullReferenceException in System.Net.HttpConnection.get_LocalEndPoint

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#105865]
### Description

We spotted the following failure in our CI:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.HttpConnection.get_LocalEndPoint()
   at System.Net.HttpListenerRequest.FinishInitialization()
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

This looks a lot like https://github.com/dotnet/runtime/issues/91014, which was fixed in the 9.0 branch (https://github.com/dotnet/runtime/pull/91234).
There were talks about backporting the fix to 8.0 but I see no evidence that it has been done. Are there still plans to do so?

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by wfurt** [comment]
there is currently no plan for backport. I'm not sure this would meet servicing bar and 9.0 is just around the corner e.g. may be out sooner than any servicing. 
Any more thoughts on this @karelz ?
