### ISSUE TITLE
Test failure: System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105925]
**Failed in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20240803.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=764865&view=ms.vss-test-web.build-test-results-tab&runId=19459552&resultId=110123&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress2_jitstressregs0x1000-Windows.10.Amd64.Open
    - System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly
```

**Error message:**
```
 System.ComponentModel.Win32Exception : The process cannot access the file because it is being used by another process.
```

**Stack trace:**
```
   at System.Diagnostics.PerformanceCounterLib.RegisterFiles(String arg0, Boolean unregister) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1233
   at System.Diagnostics.PerformanceCounterCategory.Delete(String categoryName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 392
   at System.Diagnostics.Tests.Helpers.DeleteCategory(String categoryName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 56
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by ericstj** [comment]
https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-4276504538c24eecae/System.Diagnostics.PerformanceCounter.Tests/1/console.a3510fec.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-4276504538c24eecae/System.Diagnostics.PerformanceCounter.Tests/1/console.a3510fec.log?helixlogtype=result)

```
C:\h\w\A4DA094B\w\AB5E093F\e>"C:\h\w\A4DA094B\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.PerformanceCounter.Tests.runtimeconfig.json --depsfile System.Diagnostics.PerformanceCounter.Tests.deps.json xunit.console.dll System.Diagnostics.PerformanceCounter.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.PerformanceCounter.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.PerformanceCounter.Tests (found 90 of 92 test cases)
  Starting:    System.Diagnostics.PerformanceCounter.Tests (parallel test collections = on [4 threads], stop on fail = off)
    System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_IncrementBy_IncrementByReadOnly [FAIL]
      System.ComponentModel.Win32Exception : The process cannot access the file because it is being used by another process.
      Stack Trace:
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs(1233,0): at System.Diagnostics.PerformanceCounterLib.RegisterFiles(String arg0, Boolean unregister)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs(392,0): at System.Diagnostics.PerformanceCounterCategory.Delete(String categoryName)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs(56,0): at System.Diagnostics.Tests.Helpers.DeleteCategory(String categoryName)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Info: Successfully installed performance counters in C:\h\w\A4DA094B\t\a1lrvxog.qbf\provider.man    System.Diagnostics.Tests.PerformanceDataTests.PerformanceCounter_PerformanceData [SKIP]
      Condition(s) not met: "IsRunnableEnvironment"

Info: Successfully uninstalled the performance counters from the counter definition XML file C:\h\w\A4DA094B\t\a1lrvxog.qbf\provider.man.  Finished:    System.Diagnostics.PerformanceCounter.Tests
=== TEST EXECUTION SUMMARY ===
```


Another one similar to https://github.com/dotnet/runtime/issues/104572.   Seems to me like we might have cross-talk between tests.  I wonder if we should disable parallelization in these tests?

**Comment by mikelle-rogers** [comment]
@ericstj, I noticed this test failure was put into future with no comments indicating the reason behind the milestone move, nor if the test was disabled. Would you please provide some clarity around that?

**Comment by ericstj** [comment]
Seems to be test interference or AV scanner interference.  The tests previously applied `DisableTestParallelization` in https://github.com/dotnet/runtime/commit/e4ee447368a510ff0d1d1c28b8ceba6d02b3d3fd but that doesn't seem to have fixed it.

We could introduce retries around all the calls to PerformanceCategory.Create and Delete from the tests in PerformanceCounterCategoryTests.  We already have a [delete helper that retries](https://github.com/dotnet/runtime/blob/f1f11679a4336d43e5dd8cded83c50abde8eb167/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs#L51), we can add the same for CreateCategory and ensure we call it instead of PerformanceCounterCategory directly.
