### ISSUE TITLE
[browser][MT] Could not load file or assembly System.Runtime.InteropServices

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#106067]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=759000

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105308-merge-9efc49cae32045169f/WasmTestOnFirefox-MT-Microsoft.Win32.Primitives.Tests/1/console.ca67413b.log?helixlogtype=result)
```
[14:30:37] fail: [0x000fbae8--UI- 14:30:37.974] MONO_WASM: Could not load type of field 'System.Console:s_sigIntRegistration' (9) due to: Could not load file or assembly 'System.Runtime.InteropServices, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
                    at WasmTestRunner.RunAsync()
                    at Microsoft.DotNet.XHarness.TestRunners.Xunit.WasmApplicationEntryPoint.Run()
                    at WasmTestRunner.Main(String[] args)
                 ManagedError@http://127.0.0.1:40679/_framework/dotnet.runtime.js:3:37234
                 an@http://127.0.0.1:40679/_framework/dotnet.runtime.js:3:27033
                 on/<@http://127.0.0.1:40679/_framework/dotnet.runtime.js:3:26589
                 Dl</</<@http://127.0.0.1:40679/_framework/dotnet.runtime.js:3:198011
                 Dl</<@http://127.0.0.1:40679/_framework/dotnet.runtime.js:3:198139
                 callUserCallback@http://127.0.0.1:40679/_framework/dotnet.native.js:8:98666
                 createDotnetRuntime/safeSetTimeout/createDotnetRuntime<@http://127.0.0.1:40679/_framework/dotnet.native.js:8:106269
```

```json
{
  "ErrorMessage": ["MONO_WASM","Could not load file or assembly","System.Runtime.InteropServices"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=759000
**Error message validated:** `[MONO_WASM Could not load file or assembly System.Runtime.InteropServices`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/7/2024 10:16:05 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[875425](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875425)|dotnet/runtime|[WasmTestOnFirefox-MT-Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875425&view=ms.vss-test-web.build-test-results-tab&runId=22864172&resultId=190633)|dotnet/runtime#109537|
|[873985](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873985)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Globalization.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873985&view=ms.vss-test-web.build-test-results-tab&runId=22833766&resultId=190121)|dotnet/runtime#109994|
|[873041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873041)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Formats.Cbor.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873041&view=ms.vss-test-web.build-test-results-tab&runId=22769880&resultId=190472)|dotnet/runtime#109232|
|[865986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865986)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865986&view=ms.vss-test-web.build-test-results-tab&runId=22533956&resultId=100291)|dotnet/runtime#109684|
|[865724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865724)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Dynamic.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=865724&view=ms.vss-test-web.build-test-results-tab&runId=22526902&resultId=183495)||
|[859273](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859273)|dotnet/runtime|[WasmTestOnFirefox-MT-System.Formats.Cbor.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859273&view=ms.vss-test-web.build-test-results-tab&runId=22348362&resultId=187435)||
|[859264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859264)|dotnet/runtime|[WasmTestOnChrome-MT-System.IO.Pipelines.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=859264&view=ms.vss-test-web.build-test-results-tab&runId=22348330&resultId=191044)|dotnet/runtime#108469|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|7|

**Comment by pavelsavara** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/102615
