### ISSUE TITLE
Runtime crashing under WSL2 on Volterra

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#106081]
I have Ubuntu 24.04 installed on my arm64 volterra under WSL2. I was trying to reproduce #105670.

I'm seeing crashes with both runfo-downloaded and locally built runtimes, eg from runfo bits
```
/home/andya/bugs/r105670/./correlation-payload/dotnet exec --runtimeconfig LibraryImportGenerator.Unit.Tests.runtimeconfig.json --depsfile LibraryImportGenerator.Unit.Tests.deps.json xunit.console.dll LibraryImportGenerator.Unit.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================
~/bugs/r105670/workitems/LibraryImportGenerator.Unit.Tests ~/bugs/r105670/workitems/LibraryImportGenerator.Unit.Tests
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Text.RegularExpressions.Regex..ctor(System.String, System.Globalization.CultureInfo)
   at Xunit.DependencyContextAssemblyCache..cctor()
   at Xunit.DependencyContextAssemblyCache.GetFallbackRuntime(System.String)
   at Xunit.DependencyContextAssemblyCache.<.ctor>b__17_0()
```
Will update once I've done a bit more debugging.

Crash happens at this load, looks like a TLS access:
```asm

/_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs @ 28:
0000f3d16c7cc1f4 40d03bd5             mrs     x0, TPIDR_EL0
0000f3d16c7cc1f8 01639bd2             mov     x1, #0xdb18
0000f3d16c7cc1fc 211dadf2             movk    x1, #0x68e9, lsl #16
0000f3d16c7cc200 016861b8             ldr     w1, [x0, x1]
```

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib FYI... who aside from Kunal is most familiar with the TLS access sequences?

**Comment by AndyAyersMS** [comment]
Possibly related to https://github.com/dotnet/runtime/pull/106052 ?

**Comment by davidwrighton** [comment]
@AndyAyersMS Yeah, that looks related. there's no way that the appropriate offset from the `TPIDR_EL0` register is 0x68e9db18

**Comment by davidwrighton** [comment]
@AndyAyersMS  I've just merged #106052, could you check to see if this fixes the issue?

**Comment by AndyAyersMS** [comment]
Yes, will do so.

**Comment by AndyAyersMS** [comment]
Yep, it's fixed. Thanks!

```
Launching dotnet exec --runtimeconfig LibraryImportGenerator.Unit.Tests.runtimeconfig.json --depsfile LibraryImportGenerator.Unit.Tests.deps.json xunit.console.dll LibraryImportGenerator.Unit.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  -maxthreads 2 in /home/andya/repos/runtime0/artifacts/bin/LibraryImportGenerator.Unit.Tests/Release/net9.0
  Discovering: LibraryImportGenerator.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  LibraryImportGenerator.Unit.Tests (found 185 of 189 test cases)
  Starting:    LibraryImportGenerator.Unit.Tests (parallel test collections = on [2 threads], stop on fail = off)
    LibraryImportGenerator.UnitTests.Compiles.ValidateSnippetsWithMarshalType [SKIP]
      No current scenarios to test.
  Finished:    LibraryImportGenerator.Unit.Tests
=== TEST EXECUTION SUMMARY ===
   LibraryImportGenerator.Unit.Tests  Total: 700, Errors: 0, Failed: 0, Skipped: 1, Time: 80.714s
```
