### ISSUE TITLE
Test failure:System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106002]
**Failed in:** [runtime-coreclr libraries-jitstress 20240805.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765641&view=ms.vss-test-web.build-test-results-tab&runId=19501764&resultId=202417&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-disabler2r-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
```

**Error message:**
```
 System.Net.Quic.QuicException : Stream aborted by peer (123456).
```

**Stack trace:**
```
   at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 177
   at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 663
   at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 694
--- End of stack trace from previous location ---
   at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 251
   at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass4_0.<<MultipleReadsAndWrites>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 105
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass4_0.<<MultipleReadsAndWrites>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 105
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__0>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 295
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 291
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 321
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 321
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 285
   at System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 90
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
We get some passedonrerun on this but no failures in Kusto now.
