### ISSUE TITLE
[browser] Unsupported long branch opcode

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#106028]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=767339
Build error leg or test failing: 

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["MONO_WASM" ,"Unsupported long branch opcode"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=767339
**Error message validated:** `[MONO_WASM Unsupported long branch opcode`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 8/6/2024 4:57:09 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[2510515](https://dev.azure.com/dnceng/internal/_build/results?buildId=2510515)|dotnet-runtime|[release.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2510515&view=ms.vss-test-web.build-test-results-tab&runId=53983821&resultId=100059)||
|[768349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768349)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768349&view=ms.vss-test-web.build-test-results-tab&runId=19605204&resultId=100001)|dotnet/runtime#99596|
|[768211](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768211)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=768211&view=ms.vss-test-web.build-test-results-tab&runId=19601258&resultId=100001)|dotnet/runtime#106062|
|[2510332](https://dev.azure.com/dnceng/internal/_build/results?buildId=2510332)|dotnet-runtime|[wasm.x64.micro.net9.0.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2510332&view=ms.vss-test-web.build-test-results-tab&runId=53982927&resultId=100059)||
|[2509870](https://dev.azure.com/dnceng/internal/_build/results?buildId=2509870)|dotnet-runtime|[wasmaot.x64.micro.net9.0.Partition8.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2509870&view=ms.vss-test-web.build-test-results-tab&runId=53980839&resultId=100057)||
|[767917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767917)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767917&view=ms.vss-test-web.build-test-results-tab&runId=19589196&resultId=100001)|dotnet/runtime#105841|
|[767877](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767877)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767877&view=ms.vss-test-web.build-test-results-tab&runId=19587680&resultId=100001)|dotnet/runtime#106048|
|[767716](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767716)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767716&view=ms.vss-test-web.build-test-results-tab&runId=19579606&resultId=109439)|dotnet/runtime#106040|
|[767709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767709)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767709&view=ms.vss-test-web.build-test-results-tab&runId=19578852&resultId=100001)||
|[767427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767427)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767427&view=ms.vss-test-web.build-test-results-tab&runId=19566382&resultId=100001)|dotnet/runtime#106026|
|[767356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767356)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767356&view=ms.vss-test-web.build-test-results-tab&runId=19563160&resultId=100001)|dotnet/runtime#105841|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|11|11|

**Comment by pavelsavara** [comment]
heh, the filter can't find it because it's not failing the test

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105709-merge-7dadedcb6cfe493ba5/WasmTestOnChrome-ST-Microsoft.Extensions.Configuration.Functional.Tests/1/console.e74fb728.log?helixlogtype=result)

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105709-merge-7dadedcb6cfe493ba5/WasmTestOnChrome-ST-System.Net.Http.Functional.Tests/1/console.235cd936.log?helixlogtype=result)

```
[15:38:15] fail: MONO_WASM: SequenceEqual:106 code generation failed: Error: Unsupported long branch opcode: bgt.un.i4 Error: Unsupported long branch opcode: bgt.un.i4
    at di (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:113026)
    at fi (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:114113)
    at http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164049
    at Object.generator (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164836)
    at Na.emitImportsAndFunctions (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:74056)
    at http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164902
    at Cc (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:165972)
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[212]:0x1a746
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[283]:0x1e5e7
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[319]:0x1f78d
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[191]:0xce35
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[794]:0x49026
    at e.<computed> (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:179764)
    at Yo (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:55968)
    at callUserCallback (http://127.0.0.1:49168/_framework/dotnet.native.js:8:107146)
    at http://127.0.0.1:49168/_framework/dotnet.native.js:8:107414
[15:38:15] info: MONO_WASM: // SequenceEqual:106 generated, blob follows //
[15:38:15] info: MONO_WASM: 0	00 61 73 6d 01 00 00 00 01 5c
[15:38:15] info: MONO_WASM: 10	0f 60 01 7f 00 60 04 7f 7f 7f
[15:38:15] info: MONO_WASM: 20	7f 01 7f 60 03 7f 7f 7f 01 7f
[15:38:15] info: MONO_WASM: 30	60 02 7f 7f 00 60 03 7f 7f 7f
[15:38:15] info: MONO_WASM: 40	00 60 01 7f 01 7f 60 02 7f 7f
[15:38:15] info: MONO_WASM: 50	01 7f 60 01 7c 01 7c 60 02 7c
[15:38:15] info: MONO_WASM: 60	7c 01 7c 60 01 7d 01 7d 60 02
[15:38:15] info: MONO_WASM: 70	7d 7d 01 7d 60 03 7d 7d 7d 01
[15:38:15] info: MONO_WASM: 80	7d 60 03 7c 7c 7c 01 7c 60 04
[15:38:15] info: MONO_WASM: 90	7f 7f 7f 7f 00 60 03 7c 7c 7f
[15:38:15] info: MONO_WASM: 100	01 7f
[15:38:15] info: MONO_WASM: // end blob //
[15:38:15] fail: MONO_WASM: Equals:1c0 code generation failed: Error: Unsupported long branch opcode: bgt.un.i4 Error: Unsupported long branch opcode: bgt.un.i4
    at di (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:113026)
    at fi (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:114113)
    at http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164049
    at Object.generator (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164836)
    at Na.emitImportsAndFunctions (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:74056)
    at http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164902
    at Cc (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:165972)
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[212]:0x1a746
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[283]:0x1e5e7
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[319]:0x1f78d
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[191]:0xce35
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[794]:0x49026
    at e.<computed> (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:179764)
    at Yo (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:55968)
    at callUserCallback (http://127.0.0.1:49168/_framework/dotnet.native.js:8:107146)
    at http://127.0.0.1:49168/_framework/dotnet.native.js:8:107414
[15:38:15] info: MONO_WASM: // Equals:1c0 generated, blob follows //
[15:38:15] info: MONO_WASM: 0	00 61 73 6d 01 00 00 00 01 5c
[15:38:15] info: MONO_WASM: 10	0f 60 01 7f 00 60 04 7f 7f 7f
[15:38:15] info: MONO_WASM: 20	7f 01 7f 60 03 7f 7f 7f 01 7f
[15:38:15] info: MONO_WASM: 30	60 02 7f 7f 00 60 03 7f 7f 7f
[15:38:15] info: MONO_WASM: 40	00 60 01 7f 01 7f 60 02 7f 7f
[15:38:15] info: MONO_WASM: 50	01 7f 60 01 7c 01 7c 60 02 7c
[15:38:15] info: MONO_WASM: 60	7c 01 7c 60 01 7d 01 7d 60 02
[15:38:15] info: MONO_WASM: 70	7d 7d 01 7d 60 03 7d 7d 7d 01
[15:38:15] info: MONO_WASM: 80	7d 60 03 7c 7c 7c 01 7c 60 04
[15:38:15] info: MONO_WASM: 90	7f 7f 7f 7f 00 60 03 7c 7c 7f
[15:38:15] info: MONO_WASM: 100	01 7f
[15:38:15] info: MONO_WASM: // end blob //
[15:38:15] fail: MONO_WASM: MoveNext:0 code generation failed: Error: Unsupported long branch opcode: bge.un.i4 Error: Unsupported long branch opcode: bge.un.i4
    at di (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:113026)
    at fi (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:114113)
    at http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164049
    at Object.generator (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164836)
    at Na.emitImportsAndFunctions (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:74056)
    at http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:164902
    at Cc (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:165972)
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[212]:0x1a746
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[283]:0x1e5e7
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[319]:0x1f78d
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[191]:0xce35
    at http://127.0.0.1:49168/_framework/dotnet.native.wasm:wasm-function[794]:0x49026
    at e.<computed> (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:179764)
    at Yo (http://127.0.0.1:49168/_framework/dotnet.runtime.js:3:55968)
    at callUserCallback (http://127.0.0.1:49168/_framework/dotnet.native.js:8:107146)
    at http://127.0.0.1:49168/_framework/dotnet.native.js:8:107414
[15:38:15] info: MONO_WASM: Disabling jiterpreter after 2 failures
[15:38:15] info: MONO_WASM: // MoveNext:0 generated, blob follows //
[15:38:15] info: MONO_WASM: 0	00 61 73 6d 01 00 00 00 01 5c
[15:38:15] info: MONO_WASM: 10	0f 60 01 7f 00 60 04 7f 7f 7f
[15:38:15] info: MONO_WASM: 20	7f 01 7f 60 03 7f 7f 7f 01 7f
[15:38:15] info: MONO_WASM: 30	60 02 7f 7f 00 60 03 7f 7f 7f
[15:38:15] info: MONO_WASM: 40	00 60 01 7f 01 7f 60 02 7f 7f
[15:38:15] info: MONO_WASM: 50	01 7f 60 01 7c 01 7c 60 02 7c
[15:38:15] info: MONO_WASM: 60	7c 01 7c 60 01 7d 01 7d 60 02
[15:38:15] info: MONO_WASM: 70	7d 7d 01 7d 60 03 7d 7d 7d 01
[15:38:15] info: MONO_WASM: 80	7d 60 03 7c 7c 7c 01 7c 60 04
[15:38:15] info: MONO_WASM: 90	7f 7f 7f 7f 00 60 03 7c 7c 7f
[15:38:15] info: MONO_WASM: 100	01 7f
[15:38:15] info: MONO_WASM: // end blob //
```
