### ISSUE TITLE
[Wasm][Test Failure] ConsolePublishAndRun(config: "Release", aot: True, relinking: False)

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#106162]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=769868
Build error leg or test failing: Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun
Pull request: https://github.com/dotnet/runtime/pull/105841

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Not found: \"args[0] = x\"",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by carlossanlop** [comment]
Updated the error message to capture more hits. Also linked a new build as the original one is already gone.

Example:

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-108765-merge-422f1af29bad4418b8/NoWebcil-ST-Wasm.Build.Tests.WasmTemplateTests/1/console.5f4b0de8.log?helixlogtype=result
```
[Release_was00fgf_osm] [MONO] AOT: FOUND method (wrapper managed-to-native) Interop/Runtime:BindAssemblyExports (intptr) [0x21fd - 0x21fe 0x41030]
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Release", aot: True, relinking: False) [FAIL]
      Assert.Contains() Failure: Sub-string not found
      String:    "[Release_was00fgf_osm] ]9;4;3;\\[?25l["���
      Not found: "AOT: image 'Release_was00fgf_osm' found"
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(383,0): at Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(String config, Boolean aot, Boolean relinking)
           at InvokeStub_WasmTemplateTests.ConsolePublishAndRun(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\dotnet-latest\dotnet.exe new wasmconsole  -  in pwd C:\helix\work\workitem\e\wbt artifacts\Release_was00fgf_osm
        [] The template "WebAssembly Console App" was created successfully.
        [] 
        
```

**Comment by pavelsavara** [comment]
WBT with this name doesn't exist anymore
