### ISSUE TITLE
Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#106135]
```
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
    Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs(296,0): at Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled()
        --- End of stack trace from previous location ---
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=769401
Build error leg or test failing: Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled
Pull request: https://github.com/dotnet/runtime/pull/106004

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20250119.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=922375&view=ms.vss-test-web.build-test-results-tab&runId=24397956&resultId=115312&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-fullpgo_random_gdv_edge-Windows.10.Amd64.Open
    - Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled
```

**Error message:**
```
 Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at Microsoft.Extensions.Hosting.Internal.HostTests.StartCanBeCancelled() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs:line 296
--- End of stack trace from previous location ---
```

**Comment by jkotas** [comment]
This is hit multiple times per week currently.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as this has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
