### ISSUE TITLE
[Test Failure] EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#106268]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=768382
Build error leg or test failing: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": ["System.Net.Http.Functional.Tests.TelemetryTest.ValidateEventCounters", "Assert.Contains() Failure: Filter not matched in collection"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Example failure

```
System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop(uriTail: "/test/path?q1=a&q2=b", disableRedaction: True) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:

        Child exception:
          Xunit.Sdk.ContainsException: Assert.Contains() Failure: Filter not matched in collection
        Collection: [0, 0, 0, 0, 0, ···]
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs(666,0): at System.Net.Http.Functional.Tests.TelemetryTest.ValidateEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 versionMajor, Boolean requestLeftQueue)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs(479,0): at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop>b__7_0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs(65,0): at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)

        Child process:
          System.Net.Http.Functional.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop>b__7_0(System.String, System.String, System.String)

        Child arguments:
          1.1, /test/path?q1=a&q2=b, /test/path?q1=a&q2=b
```

**Comment by rzikm** [comment]
The check fails at

**Comment by MihaZupan** [comment]
@noahfalk

#105548 introduces a new race condition where the first increment reported by an `IncrementingPollingCounter` can be inaccurate.
Because we're now calling `UpdateMetric` from the background timer thread instead as part of the `EventSource` initialization, any changes to the counter value made between the `EventSource` creation and the timer thread first running will be dropped.

Consider the following repro project that always prints a `1` on .NET 8, but not on 9.
The setup is similar to how we use EventSources in the BCL.

<details>
<summary>Simplified repro project</summary>

```c#
using System.Diagnostics.Tracing;

using var listener = new Listener();

var log = MyEventSource.Log;

// If you add some delay, you will see the increment=1 on .NET 9 as well
// Thread.Sleep(1000);

log.SomeInterestingValue++;

Console.ReadKey();

class MyEventSource : EventSource
{
    public static MyEventSource Log { get; } = new();

    private IncrementingPollingCounter? _couter;

    public int SomeInterestingValue;

    private MyEventSource() : base(nameof(MyEventSource)) { }

    protected override void OnEventCommand(EventCommandEventArgs command)
    {
        if (command.Command == EventCommand.Enable)
        {
            _couter ??= new IncrementingPollingCounter("counter", this, () => SomeInterestingValue);
        }
    }
}

class Listener : EventListener
{
    protected override void OnEventSourceCreated(EventSource eventSource)
    {
        if (eventSource.Name != nameof(MyEventSource)) return;

        EnableEvents(eventSource, EventLevel.Informational, EventKeywords.None,
            new Dictionary<string, string?> { { "EventCounterIntervalSec", 0.5f.ToString() } });
    }

    protected override void OnEventWritten(EventWrittenEventArgs eventData)
    {
        if (eventData.EventSource.Name != nameof(MyEventSource)) return;

        var counters = (IDictionary<string, object>)eventData.Payload![0]!;

        Console.WriteLine($"Increment: {counters["Increment"]}");
    }
}
```

</details>

I'm assuming this wasn't intentional?

**Comment by noahfalk** [comment]
> I'm assuming this wasn't intentional?

While it wasn't an explicit goal to break such a test, it was intentional to make that callback asynchronous. All calls to EventListener.OnEventSourceCreated() are holding a lock and invoking an IncrementingEventCounter callback function while holding that lock can lead to a deadlock (the issue that https://github.com/dotnet/runtime/pull/105548 was fixing).

More discussion about the tests for those counters here: https://github.com/dotnet/aspnetcore/issues/57259
