### ISSUE TITLE
Enum decorated with [JsonStringEnumMemberName] fails to deserialize

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#106406]
### Description

I saw `[JsonStringEnumMemberName]` in the API diff for .NET 9 preview 7 and thought I'd try it out as I have a [custom converter](https://github.com/martincostello/alexa-london-travel/blob/ab79dda176afe6662923f07720cf3ffcbbc15718/src/LondonTravel.Skill/Models/CustomStringEnumConverter%601.cs) to deal with `SCREAMING_SNAKE_CASE` at the moment in an application, so it should simplify things.

On updating the code however, one of my tests fails due to deserialization failing.

I can't see an obvious reason why - the test case contains the value [`"USER_INITIATED"`](https://github.com/martincostello/alexa-london-travel/blob/8ab652f95781b63b25ee289ed26d55f92776e81b/test/LondonTravel.Skill.Tests/Samples/SessionEndedRequest.json#L24), which matches [the code](https://github.com/martincostello/alexa-london-travel/blob/8ab652f95781b63b25ee289ed26d55f92776e81b/src/LondonTravel.Skill/Models/Reason.cs#L10-L11).

### Reproduction Steps

1. Clone https://github.com/martincostello/alexa-london-travel/commit/8ab652f95781b63b25ee289ed26d55f92776e81b
2. Run `build.ps1` in the root of the repository.

### Expected behavior

The tests pass and enum values are correctly (de)serialized.

### Actual behavior

An exception is thrown by the [Can_Deserialize_Request](https://github.com/martincostello/alexa-london-travel/blob/8ab652f95781b63b25ee289ed26d55f92776e81b/test/LondonTravel.Skill.Tests/SerializationTests.cs#L15) test:

```text
  LondonTravel.Skill.Tests test failed with 1 error(s) and 1 warning(s) (11.7s)
    C:\Coding\martincostello\alexa-london-travel\test\LondonTravel.Skill.Tests\SerializationTests.cs(25): error TESTERROR:
      Can_Deserialize_Request(name: "SessionEndedRequest", expectedType: typeof(MartinCostello.LondonTravel.Skill.Models.SessionEndedRequest)) (84ms): Error Message: Amazon.Lambda.Serialization.SystemTextJson.JsonSerializerException : Error converting the Lambda event JSON payload to type MartinCostello.LondonTravel.Skill.Models.SkillRequest: The JSON value could not be converted to MartinCostello.LondonTravel.
      Skill.Models.Reason. Path: $.request.reason | LineNumber: 23 | BytePositionInLine: 30.
      ---- System.Text.Json.JsonException : The JSON value could not be converted to MartinCostello.LondonTravel.Skill.Models.Reason. Path: $.request.reason | LineNumber: 23 | BytePositionInLine: 30.
      Stack Trace:
         at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
         at MartinCostello.LondonTravel.Skill.SerializationTests.Can_Deserialize_Request(String name, Type expectedType) in C:\Coding\martincostello\alexa-london-travel\test\LondonTravel.Skill.Tests\SerializationTests.cs:line 25
         at InvokeStub_SerializationTests.Can_Deserialize_Request(Object, Span`1)
         at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      ----- Inner Stack Trace -----
         at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
         at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.OnTryReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Object& value)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo)
         at Amazon.Lambda.Serialization.SystemTextJson.SourceGeneratorLambdaJsonSerializer`1.InternalDeserialize[T](Byte[] utf8Json)
         at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
```

### Regression?

No - new functionality.

### Known Workarounds

None.

### Configuration

- .NET SDK `9.0.100-preview.7.24407.12`
- System.Text.Json `9.0.0-preview.7.24405.7`

**Comment by eiriktsarpalis** [comment]
Thanks. Any chance you could distill this to a minimal repro? 🙏

**Comment by martincostello** [comment]
I'll give it a whirl tomorrow. This was a very end-of-day I'll just give this a quick try...oh no kinda thing.

**Comment by Ilchert** [comment]
Hello @martincostello according to the example https://github.com/dotnet/runtime/issues/74385 you need to add `JsonConverter(typeof(JsonStringEnumConverter))` attribute to your enum.

**Comment by martincostello** [comment]
@Ilchert Thanks, that was it.

I'd incorrectly assumed I didn't need it anymore and completely removed my converter attribute, rather than just change it to not use my custom converter.

**Comment by eiriktsarpalis** [comment]
Would it make sense to infer the string-based converter based on the presence of the new attribute? I'm not sure what the right approach should be here.
