### ISSUE TITLE
JIT: Debug/Release diff for `AdvSimd.ShiftRightLogicalNarrowingLower`

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#106546]
Hit by Antigen:
```csharp
// Found by Antigen
// Reduced from 22.52 KB to 1.95 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    public struct S1
    {
    }
    public struct S2
    {
        public byte byte_1;
    }
    static Vector64<float> s_v64_float_25 = Vector64.Create(1f);
    static Vector128<long> s_v128_long_33 = Vector128<long>.AllBitsSet;
    static S1 s_s1_51 = new S1();
    static S2 s_s2_52 = new S2();
    byte byte_54 = 82;
    Vector64<byte> v64_byte_68 = Vector64.CreateScalar((byte)82);
    Vector64<int> v64_int_72 = Vector64.Create(1, 1);
    Vector64<double> v64_double_77 = Vector64.CreateScalar((double)82);
    S2 s2_103 = new S2();
    static int s_loopInvariant = 8;
    private static List<string> toPrint = new List<string>();
    public S2 Method3(S2 p_s2_147, Vector64<byte> p_v64_byte_148, S1 p_s1_149, ref S1 p_s1_150, double p_double_151, float p_float_152, ref byte p_byte_153)
    {
        unchecked
        {
            int __loopvar0 = s_loopInvariant;
            while (true)
            {
                if (__loopvar0 == s_loopInvariant + 9)
                    break;
                __loopvar0 += 3;
                Vector64.Shuffle(s_v64_float_25 += Vector64.AsSingle(v64_double_77), AdvSimd.ShiftRightLogicalNarrowingLower(s_v128_long_33, s2_103.byte_1) & (v64_int_72 - v64_int_72)* 15*4);
            }
            return s_s2_52;
        }
    }
    public void Method0()
    {
        unchecked
        {
            s_s2_52 = Method3(s2_103, v64_byte_68 -= v64_byte_68, s_s1_51, ref s_s1_51, 15-4, Vector64.Dot(Vector64<float>.AllBitsSet & s_v64_float_25, s_v64_float_25), ref byte_54);
            return;
        }
    }
    public static void Main(string[] args)
    {
        Console.WriteLine(Antigen());
    }
    public static int Antigen()
    {
        new TestClass().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

export DOTNET_TieredPGO_InstrumentedTierAlwaysOptimized=1
export DOTNET_JitRandomOnStackReplacement=15
export DOTNET_HeapVerify=1
export DOTNET_TC_OnStackReplacement=1
export DOTNET_TC_PartialCompilation=1
export DOTNET_TC_QuickJitForLoops=1
export DOTNET_TieredCompilation=0
export DOTNET_TieredPGO=1
export DOTNET_EnableSSE2=0
export DOTNET_JitThrowOnAssertionFailure=1
export DOTNET_LegacyExceptionHandling=1

Release:
856641990

Debug:
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Runtime.Intrinsics.Arm.AdvSimd.ShiftRightLogicalNarrowingLower(Vector128`1 value, Byte count)
   at TestClass.Method3(S2 p_s2_147, Vector64`1 p_v64_byte_148, S1 p_s1_149, S1& p_s1_150, Double p_double_151, Single p_float_152, Byte& p_byte_153) in /Users/kunalpathak/git/repro/Program.cs:line 42
   at TestClass.Method0() in /Users/kunalpathak/git/repro/Program.cs:line 51
   at TestClass.Antigen() in /Users/kunalpathak/git/repro/Program.cs:line 61
   at TestClass.Main(String[] args) in /Users/kunalpathak/git/repro/Program.cs:line 57
*/
```

cc @dotnet/jit-contrib

**Comment by amanasifkhalid** [comment]
In this example, we're calling `AdvSimd.ShiftRightLogicalNarrowingLower(x, 0)`, and like `AdvSimd.ShiftRightLogical`, the underlying intrinsic that directly encodes the immediate doesn't support shift values of 0, so we throw in Debug. In Release, we const-fold the intrinsic, hence the behavioral diff. Like we did for `ShiftRightLogical`, we should emit a fallback intrinsic in Debug to handle out-of-bounds immediates.

Antigen also hit similar Debug/Release diffs for `AdvSimd.ShiftRightLogicalRounded`, `AdvSimd.ShiftRightLogicalNarrowingLower`, etc. so I might as well cover all the `ShiftLeft`/`ShiftRight` intrinsics while I'm at it.

**Comment by amanasifkhalid** [comment]
I spoke too soon on this one. For all the `AdvSimd.Shift*` intrinsics that can be const-folded, we already have fallback intrinsics implemented for when the immediate is out-of-range. `ShiftRightLogicalNarrowingLower` isn't being folded away. Instead, we seem to be incorrectly CSEing its parent tree away. Here's what the tree looks like before any CSEing:
```
N023 ( 32, 35)              [000049] --CXG+-----                         *  HWINTRINSIC simd8  float Shuffle <l:$312, c:$311>
N001 (  1,  1)              [000024] -----+-----                         +--*  LCL_VAR   simd8  V10 tmp1         u:2 (last use) <l:$440, c:$441>
N022 ( 30, 33) CSE #06 (use)[000048] --CXG+-----                         \--*  HWINTRINSIC simd8  int And <l:$30d, c:$310>
N008 ( 12, 19)              [000034] --CXG+-----                            +--*  HWINTRINSIC simd8  int ShiftRightLogicalNarrowingLower <l:$307, c:$306>
N003 (  6, 14)              [000029] n---G+-----                            |  +--*  IND       simd16 <l:$480, c:$4c0>
N002 (  3, 12) CSE #04 (use)[000028] H----+-----                            |  |  \--*  CNS_INT(h) long   0x2b60020e6b8 static Fseq[s_v128_long_33] $1c5
N007 (  5,  4)              [000033] ---XG+-----                            |  \--*  IND       ubyte  <l:$541, c:$542>
N006 (  3,  4)              [000056] -----+-N---                            |     \--*  ADD       byref  $381
N004 (  1,  1)              [000030] -----+-----                            |        +--*  LCL_VAR   ref    V00 this         u:1 $80
N005 (  1,  2)              [000055] -----+-----                            |        \--*  CNS_INT   long   40 Fseq[s2_103] $341
N021 ( 17, 13) CSE #06 (use)[000047] ---XG+-----                            \--*  HWINTRINSIC simd8  int MultiplyByScalar <l:$30d, c:$30f>
N019 ( 13, 10) CSE #06 (use)[000044] ---XG+-----                               +--*  HWINTRINSIC simd8  int MultiplyByScalar <l:$30d, c:$30e>
N017 (  9,  7) CSE #06 (def)[000041] ---XG+-----                               |  +--*  HWINTRINSIC simd8  int Subtract <l:$30d, c:$30c>
N012 (  4,  3) CSE #05 (def)[000037] ---XG+-----                               |  |  +--*  IND       simd8  <l:$309, c:$30a>
N011 (  3,  4)              [000058] -----+-N---                               |  |  |  \--*  ADD       byref  $382
N009 (  1,  1)              [000035] -----+-----                               |  |  |     +--*  LCL_VAR   ref    V00 this         u:1 $80
N010 (  1,  2)              [000057] -----+-----                               |  |  |     \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N016 (  4,  3) CSE #05 (use)[000040] ---XG+-----                               |  |  \--*  IND       simd8  <l:$309, c:$30b>
N015 (  3,  4)              [000060] -----+-N---                               |  |     \--*  ADD       byref  $382
N013 (  1,  1)              [000038] -----+-----                               |  |        +--*  LCL_VAR   ref    V00 this         u:1 $80
N014 (  1,  2)              [000059] -----+-----                               |  |        \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N018 (  3,  2)              [000043] -----+-----                               |  \--*  CNS_VEC   simd8 <0x0000000f, 0x0000000f> $581
N020 (  3,  2)              [000046] -----+-----                               \--*  CNS_VEC   simd8 <0x00000004, 0x00000004> $582
```

We start by CSEing the `Subtract` intrinsic. Here's what the first replacement looks like (one of the `MultiplyByScalar` intrinsics is gone):
```
N024 ( 29, 33)              [000049] -ACXG+-----                         *  HWINTRINSIC simd8  float Shuffle <l:$312, c:$311>
N001 (  1,  1)              [000024] -----+-----                         +--*  LCL_VAR   simd8  V10 tmp1         u:2 (last use) <l:$440, c:$441>
N023 ( 27, 31) CSE #06 (use)[000048] -ACXG+-----                         \--*  HWINTRINSIC simd8  int And <l:$30d, c:$310>
N008 ( 12, 19)              [000034] --CXG+-----                            +--*  HWINTRINSIC simd8  int ShiftRightLogicalNarrowingLower <l:$307, c:$306>
N003 (  6, 14)              [000029] n---G+-----                            |  +--*  IND       simd16 <l:$480, c:$4c0>
N002 (  3, 12) CSE #04 (use)[000028] H----+-----                            |  |  \--*  CNS_INT(h) long   0x2b60020e6b8 static Fseq[s_v128_long_33] $1c5
N007 (  5,  4)              [000033] ---XG+-----                            |  \--*  IND       ubyte  <l:$541, c:$542>
N006 (  3,  4)              [000056] -----+-N---                            |     \--*  ADD       byref  $381
N004 (  1,  1)              [000030] -----+-----                            |        +--*  LCL_VAR   ref    V00 this         u:1 $80
N005 (  1,  2)              [000055] -----+-----                            |        \--*  CNS_INT   long   40 Fseq[s2_103] $341
N022 ( 14, 11) CSE #06 (use)[000047] -A-XG+-----                            \--*  HWINTRINSIC simd8  int MultiplyByScalar <l:$30d, c:$30f>
N020 ( 10,  8)              [000075] -A-XG------                               +--*  COMMA     simd8  <l:$580, c:$444>
N018 (  9,  7) CSE #06 (def)[000071] DA-XG------                               |  +--*  STORE_LCL_VAR simd8  V13 cse0         d:1 $VN.Void
N017 (  9,  7)              [000041] ---XG+-----                               |  |  \--*  HWINTRINSIC simd8  int Subtract <l:$30d, c:$30c>
N012 (  4,  3) CSE #05 (def)[000037] ---XG+-----                               |  |     +--*  IND       simd8  <l:$309, c:$30a>
N011 (  3,  4)              [000058] -----+-N---                               |  |     |  \--*  ADD       byref  $382
N009 (  1,  1)              [000035] -----+-----                               |  |     |     +--*  LCL_VAR   ref    V00 this         u:1 $80
N010 (  1,  2)              [000057] -----+-----                               |  |     |     \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N016 (  4,  3) CSE #05 (use)[000040] ---XG+-----                               |  |     \--*  IND       simd8  <l:$309, c:$30b>
N015 (  3,  4)              [000060] -----+-N---                               |  |        \--*  ADD       byref  $382
N013 (  1,  1)              [000038] -----+-----                               |  |           +--*  LCL_VAR   ref    V00 this         u:1 $80
N014 (  1,  2)              [000059] -----+-----                               |  |           \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N019 (  1,  1)              [000074] -----------                               |  \--*  LCL_VAR   simd8  V13 cse0         u:1 <l:$580, c:$444>
N021 (  3,  2)              [000046] -----+-----                               \--*  CNS_VEC   simd8 <0x00000004, 0x00000004> $582
```

Then the other `MultiplyByScalar` is gone:
```
N022 ( 25, 30)              [000049] -ACXG+-----                         *  HWINTRINSIC simd8  float Shuffle <l:$312, c:$311>
N001 (  1,  1)              [000024] -----+-----                         +--*  LCL_VAR   simd8  V10 tmp1         u:2 (last use) <l:$440, c:$441>
N021 ( 23, 28) CSE #06 (use)[000048] -ACXG+-----                         \--*  HWINTRINSIC simd8  int And <l:$30d, c:$310>
N008 ( 12, 19)              [000034] --CXG+-----                            +--*  HWINTRINSIC simd8  int ShiftRightLogicalNarrowingLower <l:$307, c:$306>
N003 (  6, 14)              [000029] n---G+-----                            |  +--*  IND       simd16 <l:$480, c:$4c0>
N002 (  3, 12) CSE #04 (use)[000028] H----+-----                            |  |  \--*  CNS_INT(h) long   0x2b60020e6b8 static Fseq[s_v128_long_33] $1c5
N007 (  5,  4)              [000033] ---XG+-----                            |  \--*  IND       ubyte  <l:$541, c:$542>
N006 (  3,  4)              [000056] -----+-N---                            |     \--*  ADD       byref  $381
N004 (  1,  1)              [000030] -----+-----                            |        +--*  LCL_VAR   ref    V00 this         u:1 $80
N005 (  1,  2)              [000055] -----+-----                            |        \--*  CNS_INT   long   40 Fseq[s2_103] $341
N020 ( 10,  8)              [000077] -A-XG------                            \--*  COMMA     simd8  <l:$580, c:$444>
N018 (  9,  7) CSE #06 (def)[000071] DA-XG------                               +--*  STORE_LCL_VAR simd8  V13 cse0         d:1 $VN.Void
N017 (  9,  7)              [000041] ---XG+-----                               |  \--*  HWINTRINSIC simd8  int Subtract <l:$30d, c:$30c>
N012 (  4,  3) CSE #05 (def)[000037] ---XG+-----                               |     +--*  IND       simd8  <l:$309, c:$30a>
N011 (  3,  4)              [000058] -----+-N---                               |     |  \--*  ADD       byref  $382
N009 (  1,  1)              [000035] -----+-----                               |     |     +--*  LCL_VAR   ref    V00 this         u:1 $80
N010 (  1,  2)              [000057] -----+-----                               |     |     \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N016 (  4,  3) CSE #05 (use)[000040] ---XG+-----                               |     \--*  IND       simd8  <l:$309, c:$30b>
N015 (  3,  4)              [000060] -----+-N---                               |        \--*  ADD       byref  $382
N013 (  1,  1)              [000038] -----+-----                               |           +--*  LCL_VAR   ref    V00 this         u:1 $80
N014 (  1,  2)              [000059] -----+-----                               |           \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N019 (  1,  1)              [000076] -----------                               \--*  LCL_VAR   simd8  V13 cse0         u:1 <l:$580, c:$444>
```

And then the whole `And` subtree is gone:
```
N014 ( 12, 10)              [000049] -ACXG+-----                         *  HWINTRINSIC simd8  float Shuffle <l:$312, c:$311>
N001 (  1,  1)              [000024] -----+-----                         +--*  LCL_VAR   simd8  V10 tmp1         u:2 (last use) <l:$440, c:$441>
N013 ( 10,  8)              [000079] -A-XG------                         \--*  COMMA     simd8  <l:$580, c:$444>
N011 (  9,  7) CSE #06 (def)[000071] DA-XG------                            +--*  STORE_LCL_VAR simd8  V13 cse0         d:1 $VN.Void
N010 (  9,  7)              [000041] ---XG+-----                            |  \--*  HWINTRINSIC simd8  int Subtract <l:$30d, c:$30c>
N005 (  4,  3) CSE #05 (def)[000037] ---XG+-----                            |     +--*  IND       simd8  <l:$309, c:$30a>
N004 (  3,  4)              [000058] -----+-N---                            |     |  \--*  ADD       byref  $382
N002 (  1,  1)              [000035] -----+-----                            |     |     +--*  LCL_VAR   ref    V00 this         u:1 $80
N003 (  1,  2)              [000057] -----+-----                            |     |     \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N009 (  4,  3) CSE #05 (use)[000040] ---XG+-----                            |     \--*  IND       simd8  <l:$309, c:$30b>
N008 (  3,  4)              [000060] -----+-N---                            |        \--*  ADD       byref  $382
N006 (  1,  1)              [000038] -----+-----                            |           +--*  LCL_VAR   ref    V00 this         u:1 $80
N007 (  1,  2)              [000059] -----+-----                            |           \--*  CNS_INT   long   24 Fseq[v64_int_72] $342
N012 (  1,  1)              [000078] -----------                            \--*  LCL_VAR   simd8  V13 cse0         u:1 <l:$580, c:$444>
```

@AndyAyersMS I'm guessing this is an issue with the CSE propagation logic. Do you have any recommendations for where to look? Thanks!

**Comment by AndyAyersMS** [comment]
Looking at the above it seems like something is off with value numbering. Quite different looking trees are ending up with the same numbers, eg

```
N017 (  9,  7) CSE #06 (def)[000041] ---XG+-----                               |  +--*  HWINTRINSIC simd8  int Subtract <l:$30d, c:$30c>
N023 ( 27, 31) CSE #06 (use)[000048] -ACXG+-----                         \--*  HWINTRINSIC simd8  int And <l:$30d, c:$310>
``` 
CSE uses these to form its candidate sets, so if they are wrong, CSE will do wrong things.

**Comment by amanasifkhalid** [comment]
@AndyAyersMS thanks for pointing this out. As far as I can tell, the value numbers seem ok. Here's a simplified snippet of the source code in question:
```csharp
AdvSimd.ShiftRightLogicalNarrowingLower(s_v128_long_33, s2_103.byte_1) & (v64_int_72 - v64_int_72)
```

When we number the subtraction, we give it a zero VN since we recognize the args are the same. Then when we number the bitwise-AND, we notice the second arg has a zero VN, and thus give the AND a zero VN, too. I'm guessing that we need to account for the fact that `ShiftRightLogicalNarrowingLower` can throw an exception during numbering (I see in `Compiler::fgValueNumberArrIndexAddr` that we account for NREs for load/store intrinsics, for example). Looking at the VN info for this intrinsic, I only see exception info for the NRE we can hit from dereferencing the `this` pointer:
```
N008 [000034]   HWINTRINSIC => <l:$307 {norm=$442 {HWI_AdvSimd_ShiftRightLogicalNarrowingLower($480, $540, $403)}, exc=$400 {NullPtrExc($80)}}, c:$306 {norm=$443 {HWI_AdvSimd_ShiftRightLogicalNarrowingLower($4c0, $141, $403)}, exc=$400 {NullPtrExc($80)}}>
```

**Comment by AndyAyersMS** [comment]
That exception in the $307/$306 pair should propagate up to the `And` and give it a different value number than $30d/$310.

It looks like the code in `fgValueNumberHWIntrinsic` tries to do this..? Do we end up going through there for the `And` node?

**Comment by amanasifkhalid** [comment]
Are you referring to [this bit](https://github.com/dotnet/runtime/blob/ed68a645403b90fd64ad35d464e36c3320f288b6/src/coreclr/jit/valuenum.cpp#L13057)? If so, yes, we do go through there for the `And` node. I might be misunderstanding this, but I think the exception set for `ShiftRightLogicalNarrowingLower` should include the `ArgumentOutOfRangeException` it can throw. Right now, the exception sets for `And`'s children are identical. For example, here's the VN info for the `Subtract` node:
```
N017 [000041]   HWINTRINSIC => <l:$30d {norm=$580 {Simd8Cns[0x00000000, 0x00000000]}, exc=$400 {NullPtrExc($80)}}, c:$30c {norm=$444 {HWI_AdvSimd_Subtract($103, $104, $403)}, exc=$400 {NullPtrExc($80)}}>
```

**Comment by tannergooding** [comment]
ShiftRightLogicalNarrowingLower shouldn’t throw, it should rather be treated as just NarrowingLower for 0.

On Arm64 typically one of the shifts (left or right) but not both have allow 0 and the other is supposed to be handled as the one that allows 0. Same as was done for the regular SIMD shifts

**Comment by AndyAyersMS** [comment]
So we need to fix the debug codegen?

**Comment by amanasifkhalid** [comment]
> So we need to fix the debug codegen?

I think so; sorry to loop you in on the Release codegen.

> ShiftRightLogicalNarrowingLower shouldn’t throw, it should rather be treated as just NarrowingLower for 0.

Implementing a fallback path during importation should work, right? To handle out-of-range and/or non-constant immediates, we could wrap a `ShiftLogical` intrinsic with `gtNewSimdNarrowNode` -- is this what you're suggesting? I imagine we'd want similar fallback paths for all the remaining `Shift` APIs that encode the immediate into the instruction.

**Comment by tannergooding** [comment]
> So we need to fix the debug codegen?

Right. Well, actually I think there's two semi-related things here.

In general we try to emit platform specific intrinsics 1-to-1 with a precise corresponding instruction. However, some intrinsics require a "constant" due to the encoding of their instruction. In many cases, such an instruction has an alternative encoding (often of a different name) that allows a non-constant value to be used instead and so we prefer automatically emitting that alternative instruction in said cases.

For shift in particular, `Arm64` is a bit different in that when the pair exists (such as `ShiftLeftLogical` and `ShiftRightLogical`) its typical that `left` allows you to encode `[0, sizeof(T) * 8 - 1]` while `right` allows you to encode `[1, sizeof(T) * 8]` so in the case that you have `ShiftRightLogical(x, 0)` you need to instead emit `ShiftLeftLogical(x, 0)` (or no-op if optimizations are being done).

For `ShiftRightLogicalNarrowingLower` there is no left shift equivalent and no encoding that allows a non-constant. That leaves us with a few choices:
* We emulate the functionality via a cheap alternative sequence when the input is non-constant. In this case the operation is just `ShiftRightLogical` + `ExtractNarrowingLower`
  * This happens already in some other cases as it allows us to avoid emitting a call to an up to 256 case jump table
* We mark the intrinsic as potentially side effecting because if it is rewritten back to a call in rationalization, such as if the parameter never became constant or was constant but out of bounds then it will throw
  * We'd notably need or want to mark it non side effecting if the input became an in range constant, so the right optimizations still happen
* We update `addRangeCheckIfNeeded` to always insert the range check if the constant is out of bounds or unknown
  * It is only inserted in the `mustExpand` case today

Looking through the Arm64 intrinsics, there looks to be a non-trivial number of these that may still be "incorrect". So while the first bullet is probably the best long term option, the second or third option is probably the best option for .NET 9 to avoid churn and risk this late in the cycle.
* There are 763 instances of `ConstantExpected` in https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/AdvSimd.PlatformNotSupported.cs, and every one of them has potential to hit this issue depending on what the lower/upper constant bounds are expected to be. A lot of those are just overloads of the same method group, so we can reasonably divide that by around 10 to get around 80 IntrinsicIds that may need this handling, and I don't think we want to go through every single case before RC2.

I expect the third (update `addRangeCheckIfNeeded`) is the least risky. It may regress codegen in some cases, but it will help ensure we don't miss marking any individual intrinsic IDs and the JIT should be able to fold the range check in most cases where the value does become an in range constant.
* I think we want to change `if (mustExpand && ...)` to instead be something like `if (!immOp->IsCnsIntOrI() && ...)`
* I also think we'd want to have the `CheckHWIntrinsicImmRange` callsites change from `else if (!opts.OptimizationEnabled())` to `else if (!opts.OptimizationEnabled() || immOp->IsCnsIntOrI())` to ensure that out of bound constants are preserved as calls or otherwise insert a constant throw so the rest of the code can be tracked as "dead", although that's expected to be almost non-existent for real world code

---------------------------

Does that make sense and sound like a reasonable fix for this for .NET 9 (just ensure consistency between Debug/Release and match the .NET 8 behavior)? We can then track auditing and handling these to not throw where possible in .NET 10 instead, as a "better" fix

**Comment by amanasifkhalid** [comment]
@tannergooding thanks for taking a look at this; I think that's a reasonable solution for now, especially since Roslyn warns for non-const immediates already. I've created #106761 to track fallback intrinsic implementation work for .NET 10. For .NET 9, are you ok with the slight inconsistency in behavior between the `Shift` APIs that already have fallbacks, and everything else? Those won't throw for out-of-range immediates, while everything else will with your proposed solution.
