### ISSUE TITLE
Httpwebrequest Cause program crash in runtime 8.0.5,Windows Server 2012 R2 Datacenter

### ISSUE THREAD

**Issue by Jackcu** [dotnet/runtime#106522]
### Description

10 concurrent requests, occurring every few hours, using a proxy server

```
Application: dotnet.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Interop+ZLib.Inflate(ZStream*, FlushCode)
   at System.IO.Compression.Inflater.Inflate(FlushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte*, Int32, FlushCode, Int32 ByRef)
   at System.IO.Compression.Inflater.InflateVerified(Byte*, Int32)
   at System.IO.Compression.DeflateStream+<<ReadAsyncMemory>g__Core|51_0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Compression.DeflateStream+<<ReadAsyncMemory>g__Core|51_0>d, System.IO.Compression, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<Int32>, Int32)
   at System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<ReadAsyncCore>d__6.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Net.Http.HttpConnection+ChunkedEncodingReadStream+<ReadAsyncCore>d__6, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Net.Http.HttpConnection+<ReadAsync>d__87.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SignalCompletion()
   at System.Net.Security.SslStream+<ReadAsyncInternal>d__163`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__161`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Http.HttpConnection+RawConnectionStream+<ReadAsync>d__6.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Net.Http.HttpConnection+<ReadAsync>d__87.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SignalCompletion()
   at System.Net.Sockets.SocketAsyncEventArgs+<>c.<.cctor>b__173_0(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2[[System.Threading.PortableThreadPool+IOCompletionPoller+Event, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Threading.PortableThreadPool+IOCompletionPoller+Callback, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

```

### Reproduction Steps

It is difficult to repeat the problem, because the BCL level direct test program crashed

I registered the AppDomain. CurrentDomain. UnhandledException, TaskScheduler. UnobservedTaskException (e.S etObserved ()) But the program still crashed

### Expected behavior

I set up the request. AutomaticDecompression = DecompressionMethods. GZip | DecompressionMethods. Deflate. 
It should be able to decode correctly without crashing, or at least throw an exception that the caller can catch

### Actual behavior

```
错误应用程序名称: dotnet.exe，版本: 8.0.524.21615，时间戳: 0x661f004a
错误模块名称: coreclr.dll，版本: 8.0.524.21615，时间戳: 0x661ef96e
异常代码: 0xc0000005
错误偏移量: 0x00000000001cca96
错误进程 ID: 0x55c8
错误应用程序启动时间: 0x01daed3ed8c22787
错误应用程序路径: C:Files.exe
错误模块路径: C:Files.NETCore.App.0.5.dll
报告 ID: c7e35f56-5a49-11ef-80e3-7845c4f8ea77
错误程序包全名: 
错误程序包相对应用程序 ID: 
```

### Configuration

x64 windows 2012 r2 datacenter

**Comment by huoyaoyuan** [comment]
The access violation happens in native zlib, which is not catchable in managed code.

.NET 9 is going to replace zlib with zlib-ng. The issue may disappear if it's indeed a bug in zlib. Can you try 9.0 Preview 7 and see if it still reproduces?

**Comment by Jackcu** [comment]
> The access violation happens in native zlib, which is not catchable in managed code.
> 
> .NET 9 is going to replace zlib with zlib-ng. The issue may disappear if it's indeed a bug in zlib. Can you try 9.0 Preview 7 and see if it still reproduces?

I upgraded the runtime to 8.0.8 and no such issues have occurred
