### ISSUE TITLE
[Test Failure] NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds on Alpine

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#106634]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=779054
Build error leg or test failing: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": ["NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds [Fail]", "Resource temporarily unavailable (revoked.badssl.com:443)"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds [FAIL]
      System.Net.Http.HttpRequestException : Resource temporarily unavailable (revoked.badssl.com:443)
      ---- System.Net.Sockets.SocketException : Resource temporarily unavailable
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(715,0): at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(584,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http1.cs(297,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http1.cs(266,0): at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
           at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(491,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(530,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs(235,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1386,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1302,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(118,0): at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(692,0): at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

**Comment by rzikm** [comment]
I was able to track down the issue to the difference in handling DNS errors between glibc vs musl-libc distributions.

The DNS server used to resolve names in CI (and also e.g. Azure VMs) returns ServFail response for AAAA query for `revoked.badssl.com`. However, the A entry is returned without problems.

glibc-based distributions will return the IP address from the A entry and everything works.
musl-libc-based distros will fail the `getaddrinfo` call with `Try again` error even if IPv4 address is available.

**Comment by rzikm** [comment]
The reason for server failing to serve AAAA record for `revoked.badssl.com` is a mystery to me, but since both the website and the DNS server is outside our immediate scope of influence, I think we should disable the test on Alpine for now. Alternative workaround is enforcing public DNS server such as "8.8.8.8".

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci due to not failing for 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by rzikm** [comment]
Shraring some info discovered internally:

The authoritative DNS servers for revoked.badssl.com are returning an SOA for badssl.com when queried for type AAAA. This is technically not valid, as the server is only authoritative for revoked.badssl.com. They should not be returning an SOA record with owner name outside their authority. This is such a common domain configuration error that other implementations permit it. But currently Azure DNS does not.

```
azureuser@linuxtesteastus:~$ dig @ns-cloud1.googledomains.com. aaaa revoked.badssl.com.
; <<>> DiG 9.18.28-0ubuntu0.22.04.1-Ubuntu <<>> @ns-cloud1.googledomains.com. aaaa revoked.badssl.com.
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53809
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
; COOKIE: b4f3ff8ae1b479e00159933674e39de7fb1e4349017e7979e6a68ca04d (good)
;; QUESTION SECTION:
revoked.badssl.com.            IN      AAAA
;; AUTHORITY SECTION:
badssl.com.             300     IN      SOA     ns-cloud1.googledomains.com. dns-admin.google.com. 0 21600 3600 1209600 300
```

issue on badssl repo: https://github.com/chromium/badssl.com/issues/535

As this is outside of our scope of influence, we can't promise to "fix" this in .NET 10 and we should keep the test disabled for the time being.
