### ISSUE TITLE
application load .net com component crash

### ISSUE THREAD

**Issue by fuxuejun** [dotnet/runtime#106676]
CoreCLR Version: 9.0.24.40507
.NET Version: 9.0.0-preview.7.24405.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'Internal.Runtime.InteropServices.ComponentActivator' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.CultureAwareComparer' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Globalization.CompareInfo' threw an exception.
 ---> System.DivideByZeroException: Attempted to divide by zero.
   at System.Buffers.SearchValues.TryGetSingleRange[T](ReadOnlySpan`1 values, T& minInclusive, T& maxInclusive)
   at System.Buffers.SearchValues.Create(ReadOnlySpan`1 values)
   at System.Globalization.CompareInfo..cctor()

   --- End of inner exception stack trace ---
   at System.CultureAwareComparer..cctor()

   --- End of inner exception stack trace ---
   at Internal.Runtime.InteropServices.ComponentActivator..cctor()

   --- End of inner exception stack trace ---
   at Internal.Runtime.InteropServices.ComponentActivator.GetFunctionPointer(IntPtr typeNameNative, IntPtr methodNameNative, IntPtr delegateTypeNative, IntPtr loadContext, IntPtr reserved, IntPtr functionHandle)

**Comment by tarekgh** [comment]
@fuxuejun could you please provide instructions or a small sample of how to reproduce the issue?
