### ISSUE TITLE
Test failure: System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106849]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240822.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=785250&view=ms.vss-test-web.build-test-results-tab&runId=20167938&resultId=102768&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-jitstress_random_2-Windows.10.Amd64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20241130.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=882807&view=ms.vss-test-web.build-test-results-tab&runId=23080410&resultId=103470&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-jitosr_stress_random-Windows.10.Amd64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250113.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=915376&view=ms.vss-test-web.build-test-results-tab&runId=24176138&resultId=113288&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-arm64-jitstress_random_2-Windows.11.Arm64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250201.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=937193&view=ms.vss-test-web.build-test-results-tab&runId=24847880&resultId=103286&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress_random_1-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250208.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=945482&view=ms.vss-test-web.build-test-results-tab&runId=25102024&resultId=105360&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress_random_1-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250222.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=959891&view=ms.vss-test-web.build-test-results-tab&runId=25554498&resultId=103545&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-jitstress_random_2-Windows.10.Amd64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250322.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=989990&view=ms.vss-test-web.build-test-results-tab&runId=26420526&resultId=104974&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-jitstress_random_2-Windows.10.Amd64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250329.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=998314&view=ms.vss-test-web.build-test-results-tab&runId=26641020&resultId=118853&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm64-jitstress_random_2-(Ubuntu.2404.Arm64.Open)Ubuntu.2204.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-24.04-helix-arm64v8
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250628.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1081064&view=ms.vss-test-web.build-test-results-tab&runId=29388968&resultId=103407&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-arm64-jitstress_random_2-Windows.11.Arm64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
 Cancellation in Main thread
```

**Stack trace:**
```
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250816.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1124589)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress_random_1-(Debian.13.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-13-helix-arm32v7
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20250927.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1159924)

**Failed tests:**
```
net10.0-windows-Release-x64-jitstress_random_1-Windows.10.Amd64.Open
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by JulieLeeMSFT** [comment]
cc @jakobbotsch if this failure is related to Async2.

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20251101.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1190989)

**Failed tests:**
```
net10.0-linux-Release-arm64-jitstress_random_1-(AzureLinux.3.0.ArmArch.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-helix-arm64v8
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20251206.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1222797)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress_random_1-(Debian.13.Arm32.Open)AzureLinux.3.Arm64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-13-helix-arm32v7
    - System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync
```

**Error message:**
```
Cancellation in Main thread
```

**Stack trace:**
```
   at System.ComponentModel.EventBasedAsync.Tests.BackgroundWorkerTests.TestCancelAsync() in /_/src/libraries/System.ComponentModel.EventBasedAsync/tests/BackgroundWorkerTests.cs:line 126
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by jakobbotsch** [comment]
Don't see recent occurrences.
