### ISSUE TITLE
Test failure: Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106848]
**Failed in:** [runtime-coreclr jitstress 20240821.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=784551&view=ms.vss-test-web.build-test-results-tab&runId=20141776&resultId=118470&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hw9EFD08A6wB0D509D5uploadsIJWCopyConstructorMarshalerCopyConstructorMarshaleroutput.txt
Raw output:
BEGIN EXECUTION
 "C:hw9EFD08A6pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CopyConstructorMarshaler.dll 
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 3
Actual:   4
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at CopyConstructorMarshaler.CopyConstructorMarshaler.TestEntryPoint()
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   101
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 8/22/2024 5:59:05 AM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hw9EFD08A6wB0D509D5eInteropInterop../IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor244|25_245(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress-isas-x86 20240824.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787572&view=ms.vss-test-web.build-test-results-tab&runId=20232236&resultId=118472&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress_isas_2_x86_noavx @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress_isas_1_x86_noavx @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress_isas_2_x86_nosse41 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress_isas_2_x86_nosse @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress_isas_1_x86_nohwintrinsic @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwAC870A08wBC3A0A06uploadsIJWCopyConstructorMarshalerCopyConstructorMarshaleroutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwAC870A08pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CopyConstructorMarshaler.dll 
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 3
Actual:   4
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at CopyConstructorMarshaler.CopyConstructorMarshaler.TestEntryPoint()
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   101
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 8/24/2024 10:12:03 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwAC870A08wBC3A0A06eInteropInterop../IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor244|25_245(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240825.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787939&view=ms.vss-test-web.build-test-results-tab&runId=20245102&resultId=115126&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwBB190A1BwA40608D0uploadsIJWCopyConstructorMarshalerCopyConstructorMarshaleroutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwBB190A1Bpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CopyConstructorMarshaler.dll 
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 3
Actual:   4
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at CopyConstructorMarshaler.CopyConstructorMarshaler.TestEntryPoint()
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   101
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 8/26/2024 5:57:38 AM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwBB190A1BwA40608D0eInteropInterop../IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor244|25_245(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240826.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=789410&view=ms.vss-test-web.build-test-results-tab&runId=20288656&resultId=115264&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
    - Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwBE340A38wAE5F09A5uploadsIJWCopyConstructorMarshalerCopyConstructorMarshaleroutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwBE340A38pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CopyConstructorMarshaler.dll 
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 3
Actual:   4
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at CopyConstructorMarshaler.CopyConstructorMarshaler.TestEntryPoint()
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   101
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 8/27/2024 7:55:23 AM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwBE340A38wAE5F09A5eInteropInterop../IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/CopyConstructorMarshaler.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor244|25_245(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```
