### ISSUE TITLE
Test failure: System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ThrowingCallbackOde_KeepRunning

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106944]
**Failed in:** [runtime-coreclr libraries-pgo 20240823.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786253&view=ms.vss-test-web.build-test-results-tab&runId=20193942&resultId=171046&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-jitrlcse-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ThrowingCallbackOde_KeepRunning
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: CallbackError
Actual:   ConnectionIdle
```

**Stack trace:**
```
    at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 68
   at System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ThrowingCallbackOde_KeepRunning() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicListenerTests.cs:line 128
   at System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ThrowingCallbackOde_KeepRunning() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicListenerTests.cs:line 135
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
The five issues: #106945, #106944, #106943, #106942 and #106941 all seem to be environmental. They all happen at the same time on 23.8., they are all Arm32 libraries-pgo run. I'm closing them until we see repeated failures.
