### ISSUE TITLE
net8.0: Using unmanaged function pointer in a generic class throws "System.BadImageFormatException: Bad element type in SizeOf"

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#106997]
Compile and run the following for net8.0 (Using .NET 9 works as expected):

```console
$ dotnet new console -f net8.0
```

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;


namespace HelloWorld
{
    public static class InteropUtil
    {
        [UnmanagedCallersOnly]
        private static void Bar(int x) => Console.WriteLine ($"Bar {x}");
        
        public unsafe static /*extern*/ IntPtr getNativeFunctionPointer() => (IntPtr)(void*)(delegate* unmanaged<int,void>)&InteropUtil.Bar;
    }

    unsafe public class NativeInvoker<T>
    {
        [MethodImpl(MethodImplOptions.NoInlining)]
        T Foo(T x) => x;

        public void RunIt(IntPtr fptr, T arg)
        {
            T x = Foo(arg);
            var func = (delegate* unmanaged<T, void>)fptr;
            func(x);
        }
    }
    internal class Program
    {
        private static void Main(string[] args)
        {
            var invoker = new NativeInvoker<int>();
            invoker.RunIt(InteropUtil.getNativeFunctionPointer(), 42);
        }
    }
}
```

Expected output:

```
Bar 42
```

Actual output:

```
Unhandled exception. System.BadImageFormatException: Bad element type in SizeOf.
   at HelloWorld.NativeInvoker`1.RunIt(IntPtr fptr, T arg)
   at HelloWorld.Program.Main(String[] args) in /tmp/neight/Program.cs:line 32
```

**Comment by lambdageek** [comment]
Found while trying to decide whether to backport https://github.com/dotnet/runtime/pull/106837 to net8.0 for Mono

**Comment by hez2010** [comment]
This is expected as support for generic function pointers only exists on .NET 9+, see #97079
