### ISSUE TITLE
Test failure: baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106949]
**Failed in:** [runtime-coreclr outerloop 20240825.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787850&view=ms.vss-test-web.build-test-results-tab&runId=20240272&resultId=107553&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked no_tiered_compilation @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
```

**Error message:**
```
 
Assert failure(PID 212 [0x000000d4], Thread: 212 [0x00d4]): Consistency check failed: Crst Level violation: Can't take level 6 lock CrstUnresolvedClassLock because you already holding level 0 lock CrstNativeImageEagerFixups
FAILED: false
    File: /__w/1/s/src/coreclr/vm/crst.cpp:765
    Image: /root/helix/work/correlation/crossgen2/crossgen2

[createdump] The app model does not support crash report generation
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
/root/helix/work/workitem/e/baseservices/baseservices/../TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh: line 211:   212 Aborted                 (core dumped) "$CORE_ROOT/crossgen2/crossgen2" --out r2r/BasicTestWithMcj.dll BasicTestWithMcj.dll -r $CORE_ROOT/*.dll
BEGIN: coreclr_initialize failed - Error: 0x80070057
END: coreclr_initialize failed - Error: 0x80070057

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/TieredCompilation/BasicTestWithMcj/output.txt
Raw output:
BEGIN EXECUTION
[createdump] Target process is alive
./RunBasicTestWithMcj.sh --runCustomTest /root/helix/work/workitem/e/baseservices/TieredCompilation/BasicTestWithMcj/ BasicTestWithMcj.dll ''
Collect profile without R2R, use profile without R2R
Collect profile with R2R, use profile with R2R
Exe path: /root/helix/work/correlation/corerun
Properties:
    TRUSTED_PLATFORM_ASSEMBLIES = /root/helix/work/correlation/System.ServiceModel.Web.dll:/root/helix/work/correlation/System.Composition.Hosting.dll:/root/helix/work/correlation/System.Net.dll:/root/helix/work/correlation/System.ServiceProcess.ServiceController.dll:/root/helix/work/correlation/Microsoft.CodeAnalysis.dll:/root/helix/work/correlation/System.Net.WebSockets.dll:/root/helix/work/correlation/System.Threading.Tasks.dll:/root/helix/work/correlation/System.Net.Primitives.dll:/root/helix/work/correlation/System.DirectoryServices.dll:/root/helix/work/correlation/Microsoft.Diagnostics.Tracing.TraceEvent.dll:/root/helix/work/correlation/Microsoft.Extensions.Options.ConfigurationExtensions.dll:/root/helix/work/correlation/xunit.execution.dotnet.dll:/root/helix/work/correlation/System.Net.Sockets.dll:/root/helix/work/correlation/Microsoft.Extensions.Hosting.Systemd.dll:/root/helix/work/correlation/System.Runtime.Serialization.Json.dll:/root/helix/work/correlation/System.Threading.Channels.dll:/root/helix/work/correlation/System.Diagnostics.DiagnosticSource.dll:/root/helix/work/correlation/Microsoft.Extensions.Configuration.Xml.dll:/root/helix/work/correlation/xunit.runner.utility.netcoreapp10.dll:/root/helix/work/correlation/System.ComponentModel.DataAnnotations.dll:/root/helix/work/correlation/System.Security.Cryptography.Cng.dll:/root/helix/work/correlation/System.Security.AccessControl.dll:/root/helix/work/correlation/System.Formats.Cbor.dll:/root/helix/work/correlation/System.Buffers.dll:/root/helix/work/correlation/System.Runtime.CompilerServices.Unsafe.dll:/root/helix/work/correlation/System.IO.Pipes.dll:/root/helix/work/correlation/System.ServiceProcess.dll:/root/helix/work/correlation/System.Runtime.Extensions.dll:/root/helix/work/correlation/System.Threading.Thread.dll:/root/helix/work/correlation/System.Dynamic.Runtime.dll:/root/helix/work/correlation/WindowsBase.dll:/root/helix/work/correlation/Microsoft.Extensions.Logging.EventSource.dll:/root/helix/work/correlation/Microsoft.Extensions.FileProviders.Physical.dll:/root/helix/work/correlation/System.ComponentModel.Composition.Registration.dll:/root/helix/work/correlation/System.IO.FileSystem.Primitives.dll:/root/helix/work/correlation/System.Collections.dll:/root/helix/work/correlation/System.Security.Principal.Windows.dll:/root/helix/work/correlation/xunit.console.dll:/root/helix/work/correlation/Microsoft.Extensions.FileProviders.Composite.dll:/root/helix/work/correlation/System.Runtime.Serialization.Primitives.dll:/root/helix/work/correlation/System.Configuration.ConfigurationManager.dll:/root/helix/
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor23|0_24(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jkotas** [comment]
Introduced by #80154?

cc @am11 @jakobbotsch

**Comment by am11** [comment]
@jkotas https://github.com/dotnet/runtime/pull/106965#issuecomment-2312793610, this is failing in main as well:
<img width="1710" alt="Screenshot 2024-08-27 at 17 56 07" src="https://github.com/user-attachments/assets/1d636a2e-2a3b-489e-9320-fc4234d3d0b6">
https://dev.azure.com/dnceng-public/public/_build?definitionId=134&_a=summary

so this was unrelated to https://github.com/dotnet/runtime/pull/80154 change.

**Comment by am11** [comment]
Can't say for sure when it started to happen because old logs are deleted on helix side, but by the number of failures on those jobs, it seems like it's  between 1<sup>st</sup> and 2<sup>nd</sup> of august: https://github.com/dotnet/runtime/compare/e3684bce...30b34e6d, i.e. e3684bce had fewer failures and next run on the next day against 30b34e6d had many.

**Comment by jkotas** [comment]
This was introduced by https://github.com/dotnet/runtime/pull/105671

We may need to add a new lock dependency to https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/CrstTypes.def

cc @AaronRobinsonMSFT
