### ISSUE TITLE
Test failure: System.Net.Quic.Tests.QuicConnectionTests.AcceptStreamAsync_ConnectionDisposed_Throws

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106942]
**Failed in:** [runtime-coreclr libraries-pgo 20240823.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786253&view=ms.vss-test-web.build-test-results-tab&runId=20193942&resultId=171043&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-jitrlcse-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicConnectionTests.AcceptStreamAsync_ConnectionDisposed_Throws
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ListenerDisposed_Throws
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_InvalidConnectionOptions_Throws
```

**Error message:**
```
 Assert.Throws() Failure: Exception type was not an exact match
Expected: typeof(System.ObjectDisposedException)
Actual:   typeof(System.Net.Quic.QuicException)
---- System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.Tests.QuicConnectionTests.AcceptStreamAsync_ConnectionDisposed_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 727
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 761
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 796
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 581
   at System.Net.Quic.Tests.QuicConnectionTests.<>c__DisplayClass22_0.<<AcceptStreamAsync_ConnectionDisposed_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 727
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
The five issues: #106945, #106944, #106943, #106942 and #106941 all seem to be environmental. They all happen at the same time on 23.8., they are all Arm32 libraries-pgo run. I'm closing them until we see repeated failures.
