### ISSUE TITLE
Test failure: System.Net.Quic.Tests.QuicConnectionTests.ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106941]
**Failed in:** [runtime-coreclr libraries-pgo 20240823.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=786253&view=ms.vss-test-web.build-test-results-tab&runId=20193942&resultId=171040&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-jitrlcse-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicConnectionTests.ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException
```

**Error message:**
```
 Assert.False() Failure
Expected: False
Actual:   True
```

**Stack trace:**
```
   at System.Net.Quic.Tests.QuicConnectionTests.<>c__DisplayClass15_0.<<ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 549
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__0>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 295
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 291
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 321
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 321
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 285
   at System.Net.Quic.Tests.QuicConnectionTests.ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 536
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
The five issues: #106945, #106944, #106943, #106942 and #106941 all seem to be environmental. They all happen at the same time on 23.8., they are all Arm32 libraries-pgo run. I'm closing them until we see repeated failures.
