### ISSUE TITLE
iOS-sim PhysicalFileProviderTests.TokenForEmptyFilter test failure

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#107246]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=794325
Build error leg or test failing: Microsoft.Extensions.FileProviders.Physical.Tests
Affected CI: `iossimulator_x64_release_allsubsets_mono` (`runtime-extra-platforms`)
Range of commits: https://github.com/dotnet/runtime/compare/c87cbf63...ac663e44

Failure log:
```
[15:37:09] dbug: 2024-08-30 15:37:09.282611-0700 Microsoft.Extensions.FileProviders.Physical.Tests[20660:5667193] 	[FAIL] Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter
[15:37:09] dbug: Assert.False() Failure
[15:37:09] dbug: Expected: False
[15:37:09] dbug: Actual:   True
[15:37:09] dbug: at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter()
[15:37:09] dbug: 2024-08-30 15:37:09.282865-0700 Microsoft.Extensions.FileProviders.Physical.Tests[20660:5667193]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[15:37:09] dbug: at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=794325
**Error message validated:** `[[FAIL] Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenForEmptyFilter`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/2/2024 7:17:48 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[794325](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794325)|dotnet/runtime|[Microsoft.Extensions.FileProviders.Physical.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794325&view=ms.vss-test-web.build-test-results-tab&runId=20442928&resultId=206693)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by matouskozak** [comment]
@adamsitnik do you know if the `PhysicalFileProviderTests.TokenForEmptyFilter` test could be affected by https://github.com/dotnet/runtime/pull/107195?

**Comment by matouskozak** [comment]
No longer failing, closing for now.
