### ISSUE TITLE
Test failure: System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107239]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240831.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=794887&view=ms.vss-test-web.build-test-results-tab&runId=20460438&resultId=167326&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstress_random_2-Windows.11.Arm64.Open
    - System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync
```

**Error message:**
```
 System.InvalidOperationException : The current TransactionScope is already complete.
```

**Stack trace:**
```
   at System.Transactions.Transaction.get_Current() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Transaction.cs:line 169
   at System.Transactions.Tests.AsyncTransactionScopeTests.AssertTransactionNull() in /_/src/libraries/System.Transactions.Local/tests/AsyncTransactionScopeTests.cs:line 1674
   at System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTAsyncTSNestedAsync() in /_/src/libraries/System.Transactions.Local/tests/AsyncTransactionScopeTests.cs:line 1158
--- End of stack trace from previous location ---
```

**Comment by SamMonoRT** [comment]
Assigning to myself for tracking, moving to 10.0.0 milestone, don't see any relevant changes in this area.

@v-wenyuxu  - Is this a deterministic failure?
