### ISSUE TITLE
Proposer #if #else statement does not work with attributes

### ISSUE THREAD

**Issue by sirinath** [dotnet/runtime#107262]
### Description

I should be able to write:

```csharp
#if DEBUG
[AAttribute("")]
#else
[AnotherAttribute("")]
#endif
class XXX ....
```

But I have to write

```csharp
#if DEBUG
[AAttribute("")]
#endif
#if !DEBUG
[AnotherAttribute("")]
#endif
class XXX ....
```

### Reproduction Steps

Write something along the lines of:

```csharp
#if DEBUG
[AAttribute("")]
#else
[AnotherAttribute("")]
#endif
class XXX ....
```

### Expected behavior

This should be valid

### Actual behavior

The `#else` is not recognised.

### Known Workarounds

```csharp
#if DEBUG
[AAttribute("")]
#endif
#if !DEBUG
[AnotherAttribute("")]
#endif
class XXX ....
```

### Configuration

.Net 6
Win 11
x64

**Comment by KeterSCP** [comment]
What exactly is not working for you?

Here is a working example on [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWAChGA3AQygAJWMMoBLYDgwwAzhwC8HDAE8ADjAgAzABQBZaQGEANqxEiAlADoA4jAwacIjBAC2AQR79BwkcsWstImPoDcjRorQMKxgABYcymyc3LwCQjAcfHhcjnEu+owA3owcuRwUNACcyjFO8b6MAL7+DADEfIocACIAogBCAKrGjADaAPLAIhBaZjAAuoy1MJ4wvQDKMPwefABerMAjE3UweIQNjNQc6tq6IllVQA)

You can change Debug configuration to Release and observe that applied attribute changes depending on the configuration.

**Comment by sirinath** [comment]
This was a issue in Microsoft Visual Studio Enterprise 2022 Version 17.11.2. It did not recognise the `#else` part. 

I tried I changing it back:

```csharp
#if DEBUG
[Robot(TimeZone = TimeZones.UTC, AccessRights = AccessRights.None, AddIndicators = true)]
#else
[Robot(TimeZone = TimeZones.UTC, AccessRights = AccessRights.FullAccess, AddIndicators = true)]
#endif
public class Trail2 : Robot {
```

from

```csharp
#if DEBUG
[Robot(TimeZone = TimeZones.UTC, AccessRights = AccessRights.None, AddIndicators = true)]
#endif
#if !DEBUG
[Robot(TimeZone = TimeZones.UTC, AccessRights = AccessRights.FullAccess, AddIndicators = true)]
#endif
public class Trail2 : Robot {
```

But this error has since disappeared.

**Comment by CyrusNajmabadi** [comment]
I cannot repro this issue on any version of visual studio (including 17.11.2).  Can you provide a link to a repro where your are saying this?

**Comment by sirinath** [comment]
This is a private repo. 

This uses the cTrader API.

**Comment by jeffschwMSFT** [comment]
If this is related to Visual Studio, please file an issue here: https://developercommunity.visualstudio.com/home

**Comment by CyrusNajmabadi** [comment]
> This is a private repo. 
> 
> This uses the cTrader API.

Even if it's a private report, can you at least provide a repro where this happens?  I cannot repro this at all in the last few versions of VS

**Comment by sirinath** [comment]
This does not happen frequently. But when it does I seam to get errors like this before or after:

```
StreamJsonRpc.RemoteInvocationException: Object reference not set to an instance of an object.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__154`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
RPC server exception:
System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.CodeAnalysis.ImmutableArrayExtensions.WhereAsArrayImpl[T,TArg](ImmutableArray`1 array, Func`2 predicateWithoutArg, Func`3 predicateWithArg, TArg arg)
      at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, SyntaxToken token, SolutionServices services, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.GetSemanticInfoAtPositionAsync(SemanticModel semanticModel, Int32 position, SolutionServices services, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSymbolAtPositionAsync(SemanticModel semanticModel, Int32 position, SolutionServices services, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsInCurrentProcessAsync(Document document, Int32 position, IImmutableSet`1 documentsToSearch, HighlightingOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsAsync(Document document, Int32 position, IImmutableSet`1 documentsToSearch, HighlightingOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
```

**Comment by CyrusNajmabadi** [comment]
That was fixed with https://github.com/dotnet/roslyn/pull/71595/files

**Comment by sirinath** [comment]
Is this available in:

```
Microsoft Visual Studio Enterprise 2022 (2) (64-bit) - Current
Version 17.11.2
```
