### ISSUE TITLE
PipeReaderStream throws when the read buffer is smaller than the examined length

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#107213]
### Description

`PipeReaderStream`'s `HandleReadResult` implementation calls `AdvanceTo` with the `examined` argument set to the same value as `consumed`.
https://github.com/dotnet/runtime/blob/ac663e44b907618c631edd614231b73677843952/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReaderStream.cs#L142
If the user previously advanced the pipe's `examined` beyond what is read via the stream, the read will throw.

### Reproduction Steps

```c#
using System.Buffers;
using System.IO.Pipelines;

var pipe = new Pipe();

pipe.Writer.Write("abc"u8);
await pipe.Writer.FlushAsync();

pipe.Reader.TryRead(out var result);
pipe.Reader.AdvanceTo(result.Buffer.Start, result.Buffer.Slice(result.Buffer.Start, 2).End);

_ = pipe.Reader.AsStream().ReadByte();
```

### Expected behavior

`ReadByte` returns 'a', advances the pipe's consumed by 1, leaving examined at 2.

### Actual behavior

Throws
```
System.InvalidOperationException: The examined position cannot be less than the previously examined position.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_InvalidExaminedPosition()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.PipeReaderStream.HandleReadResult(ReadResult result, Span`1 buffer)
   at System.IO.Pipelines.PipeReaderStream.HandleReadResult(ReadResult result, Span`1 buffer)
   at System.IO.Pipelines.PipeReaderStream.ReadInternal(Span`1 buffer)
   at System.IO.Pipelines.PipeReaderStream.ReadByte()
```

### Regression?

Not as far as I can tell.

### Known Workarounds

Assuming that the `examined - start` delta is smaller than 4 KB, you can wrap the pipe like so
```c#
reader = PipeReader.Create(reader.AsStream());
```
before doing any reads via the `AsStream()`.

If it's above 4 KB, you can increase the buffer size option on `PipeReader.Create`.

### Other information

ASP.NET Core's `DuplexPipeStream` implementation has the same issue
https://github.com/dotnet/aspnetcore/blob/d630c295110bb4af6b49298671024a545c1642bf/src/Shared/ServerInfrastructure/DuplexPipeStream.cs#L148

**Comment by MihaZupan** [comment]
For a realistic case where you can hit this, consider a Kestrel app where you want to examine the TLS ClientHello before passing it to `SslStream`.
```c#
using System.Net;
using Microsoft.AspNetCore.Connections;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseKestrel(options =>
{
    options.Listen(IPAddress.Any, 5001, listenOptions =>
    {
        listenOptions.Use(async (ConnectionContext connectionContext, Func<Task> next) =>
        {
            var input = connectionContext.Transport.Input;
            var result = await input.ReadAsync();
            var buffer = result.Buffer;
            var examined = buffer.Slice(buffer.Start, 1).End;
            input.AdvanceTo(buffer.Start, examined);

            await next();
        });

        listenOptions.UseHttps();
    });
});

var app = builder.Build();
app.Run();
```
The above scenario no longer works as of .NET 8 because `SslStream` now injects zero-byte reads. cc: @wfurt
