### ISSUE TITLE
PKCS7 CMS Decryption failed when using certificates with Elliptic Curve keys.

### ISSUE THREAD

**Issue by azure-hu** [dotnet/runtime#107363]
### Description

When recipient has certificate with Elliptic Curve keys, PKCS7 CMS message encrypted by a Java program fails to decrypt on .NET side. Encryption algorithm was AES-128-CBC, but as I saw, an ephemeral EC keypair was generated, and key wrap also happened.
OpenSSL can decrypt the data, but I haven't found any method to decrypt the encrypted key, and use it for content decryption. 
Do .NET still missing some implementation, maybe EnvelopedCms class cannot identify key encryption and decrypt it, or my code has issues? 

### Reproduction Steps

Please found the example code on this URL: https://gist.github.com/azure-hu/bb25db4d7e658e254770c4e0d646796c

### Expected behavior

Encrypted key unwrapped internally, then used to decrypt the CMS content.

### Actual behavior

Exception occurs when calling EnvelopedCms Decryt() function:
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'Invalid data.'
		at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore)
		at System.Security.Cryptography.Pkcs.EnvelopedCms.Decrypt(X509Certificate2Collection extraStore)

### Configuration

Which version of .NET is the code running on? - .NET Framework 4+, .NET 5, .NET6, even .NET 8
What OS and version, and what distro if applicable? - tested on Windows only
What is the architecture (x64, x86, ARM, ARM64)? - x64
Do you know whether it is specific to that configuration? - Not tested, but if OpenSSL works, might be on OS using classes with OpenSSL implementation instead of CNG works also.
If you're using Blazor, which web browser(s) do you see this issue in? - Not a Blazor project.

**Comment by bartonjs** [comment]
If you're getting WindowsCryptographicException, that suggests that our implementation decided to use the Windows implementation, and presumably what it's saying is that Windows never hooked up ECDH for KeyAgreement in CMS.

Turns out, we haven't done it in the Managed implementation, either.  We probably should.

**Comment by Crypt32** [comment]
I would like to upvote this issue/request. We are stumbled with ECDH recipients in EnvelopedCms with the same problem too. Right now, we are forced to drop entire .NET EnvelopedCms because it is useless and write our own implementation, including RFC 3394 key wrapping logic and the rest parts of enveloped CMS.
