### ISSUE TITLE
System.Text.Json analyzers should warn about using reflection when reflection is disabled

### ISSUE THREAD

**Issue by sweemer** [dotnet/runtime#107440]
### Description

Setting the `JsonSerializerIsReflectionEnabledByDefault` property to `false` currently results in a runtime exception when reflection-based json serialized is encountered. As discussed in https://github.com/dotnet/roslyn-analyzers/issues/7283, it would be nice if the analyzers for `System.Text.Json` could provide a compile-time warning for code that uses reflection when reflection is disabled through the property.

### Reproduction Steps

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

```csharp
using System.Text.Json;
JsonSerializer.Serialize(42);
```

### Expected behavior

Compiler warning or error for using reflection-based json serialization when `JsonSerializerIsReflectionEnabledByDefault` is set to `false`.

### Actual behavior

No warning or error at compile-time. The following exception is thrown at runtime:

```
Unhandled exception. System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Program.<Main>$(String[] args) in /home/sweemer/JsonTest/Program.cs:line 2
```

### Configuration

```
$ dotnet --info
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.401/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  8.0.401 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by nomi-san** [comment]
You can use `PublishAot` to trigger the analyzer. For publishing without AOT, just add a condition.

```xml
  <PropertyGroup Condition="not publishing...">
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <PublishAot>true</PublishAot>
  </PropertyGroup
```

**Comment by sweemer** [comment]
@nomi-san The problem is that `PublishAot` and `IsAotCompatible` enable a lot of other analyzers too, which some applications might not be ready for, especially applications that depend on third-party packages that are not AOT compatible. So I still say it's valuable for `JsonSerializerIsReflectionEnabledByDefault` to have its own standalone analyzer.

**Comment by nomi-san** [comment]
@sweemer  I agree. Remember to always pass `JsonTypeInfo` or `JsonContext.Default` to any serializer methods.

**Comment by jeffhandley** [comment]
Assigned to @eiriktsarpalis for triage. Eirik, do you think this would be feasible without false positives?

**Comment by eiriktsarpalis** [comment]
My concern is that it would be creating duplicate warnings for the 99% of projects that disable this feature flag because they're enabling trimming or Native AOT. Why disable reflection if neither is being used?

**Comment by sweemer** [comment]
Hi @eiriktsarpalis as mentioned [here](https://github.com/dotnet/runtime/issues/107440#issuecomment-2611217774) and [here](https://github.com/dotnet/roslyn-analyzers/issues/7283#issuecomment-2332834149), I found it desirable in my app to enforce a ban on reflection as a first step towards trimming. It's much better than no enforcement when trimming is not possible due to incompatible package references.

It was actually your [blog post](https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-8/#disabling-reflection-defaults) where I first found out about this property, and I immediately thought it would be a good way to enforce some of the benefits of AOT and trimming before the rest of my application was ready, which indeed it has been. (Very informational post by the way, thanks for writing it!)

As far as duplicate warnings are concerned, perhaps there is a way to only show one warning when trimming or AOT is also enabled?

**Comment by eiriktsarpalis** [comment]
> Hi [@eiriktsarpalis](https://github.com/eiriktsarpalis) as mentioned [here](https://github.com/dotnet/runtime/issues/107440#issuecomment-2611217774) and [here](https://github.com/dotnet/roslyn-analyzers/issues/7283#issuecomment-2332834149), I found it desirable in my app to enforce a ban on reflection as a first step towards trimming.

My recommendation would be to enable the AOT analyzer. System.Text.Json isn't the only component that exposes APIs using unsupported reflection, the entire .NET library ecosystem exposes APIs annotated using attributes understood by the linker and the related analyzers. I don't think exposing an ad-hoc analyzer for one API is going to help much here.
