### ISSUE TITLE
[8.0] Test assert failure in Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#107413]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=796437
Build error leg or test failing: Microsoft.Extensions.Configuration.Binder.Tests

## Error Message

```json
{
  "ErrorMessage" : "ConfigurationBinderTests.cs(769,0)",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- Found in an unrelated PR https://github.com/dotnet/runtime/pull/107161
- Queue: `Build Libraries Test Run checked coreclr windows x64 Release`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=796437&view=logs&j=51e4640a-c078-5be6-cc1b-f971e75d762f&t=a795459e-9f5a-52e6-9047-d38ac6fe5fb4&l=56
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-107161-merge-7fa52758a6084b85a1/Microsoft.Extensions.Configuration.Binder.Tests/1/console.1e5e9a94.log?helixlogtype=result
- Output:
```
    Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: other stuff
      Actual:   stuff
                 (pos 0)
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/Common/ConfigurationBinderTests.cs(769,0): at Microsoft.Extensions.Configuration.Binder.Tests.ConfigurationBinderTests.BindCanReadStaticProperty()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=796437
**Error message validated:** `[ConfigurationBinderTests.cs(769,0)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/5/2024 5:37:09 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by tarekgh** [comment]
Closing this as it has been more than a month the test not failed.

**Comment by PranavSenthilnathan** [comment]
Reopening because this repro'd in 8.0 PR (#120832): https://dev.azure.com/dnceng-public/public/_build/results?buildId=1182748&view=ms.vss-test-web.build-test-results-tab&runId=32728196&resultId=101541&paneView=debug
