### ISSUE TITLE
[9.0] PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds test crash

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#107412]
@dotnet/interop-contrib 

## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=798645
Build error leg or test failing: `System.Runtime.InteropServices.Tests`

## Error Message

```json
{
  "ErrorMessage" : "[InlinedCallFrame] (System.Tests.PosixSignalRegistrationTests.AllocConsole)",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/107397
- Queue: `Libraries Test Run checked coreclr windows x64 Release`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=798645&view=logs&j=1fb92a8d-ebcf-5b2f-a0cf-5c423627f3d7&t=fb9c4aa3-2ac2-52e1-0eb5-e37bec33b04f&l=69
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-107397-merge-c365e67502de4c589a/System.Runtime.InteropServices.Tests/1/console.3897a480.log?helixlogtype=result
- Output:
```
  System.Tests.PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
      Memory load: 12
      
      Image Name                     PID Services                                    
      ========================= ======== ============================================
      svchost.exe                    768 BrokerInfrastructure, DcomLaunch, LSM,      
                                         PlugPlay, Power, SystemEventsBroker         
      svchost.exe                    828 RpcEptMapper, RpcSs                         
      svchost.exe                    952 TermService                                 
      svchost.exe                    964 Appinfo, CertPropSvc, DsmSvc, gpsvc,        
                                         iphlpsvc, ProfSvc, sacsvr, Schedule, SENS,  
                                         SessionEnv, ShellHWDetection, Themes,       
                                         UserManager, Winmgmt, wlidsvc, WpnService,  
                                         wuauserv                                    
      svchost.exe                   1020 NcbService, PcaSvc, TrkWks, UmRdpService,   
                                         vmickvpexchange, vmicshutdown               
      svchost.exe                    388 Dhcp, EventLog, lmhosts, NgcCtnrSvc,        
                                         TimeBrokerSvc, vmictimesync                 
      svchost.exe                   1028 vmicheartbeat                               
      svchost.exe                   1184 CDPSvc, EventSystem, FontCache, netprofm,   
                                         nsi, RemoteRegistry, W32Time,               
                                         WinHttpAutoProxySvc                         
      svchost.exe                   1212 BFE, CoreMessagingRegistrar, DPS, MpsSvc,   
                                         pla                                         
      svchost.exe                   1520 CryptSvc, Dnscache, LanmanWorkstation,      
                                         NlaSvc, WinRM                               
      svchost.exe                   1572 Wcmsvc                                      
      svchost.exe                     80 AppHostSvc                                  
      svchost.exe                   2052 StateRepository, tiledatamodelsvc           
      svchost.exe                   2132 DiagTrack                                   
      svchost.exe                   2156 LanmanServer                                
      svchost.exe                   2172 W3SVC, WAS                                  
      svchost.exe                   3172 CDPUserSvc_482ba, OneSyncSvc_482ba          
      svchost.exe                   3548 AppReadiness                                
      svchost.exe                   5276 MapsBroker                                  
      Timed out at 9/5/2024 4:22:32 PM after 60000ms waiting for remote process.
      Wrote mini dump to: C:\h\w\AC9F09E5\w\A8BD0964\uploads\4040.mwebtg0s.5rk.dmp
      	Process ID: 4040
      	Handle: 984
      	Name: dotnet
      	MainModule: C:\h\w\AC9F09E5\p\dotnet.exe
      	StartTime: 9/5/2024 4:21:32 PM
      	TotalProcessorTime: 00:00:02.0625000
      	Threads:
      		Thread #1 (OS 0xEBC)   [MTA]
      			[InlinedCallFrame] (System.Tests.PosixSignalRegistrationTests.AllocConsole)
      			[InlinedCallFrame] (System.Tests.PosixSignalRegistrationTests.AllocConsole)
      			ILStubClass.IL_STUB_PInvoke()
      			System.Tests.PosixSignalRegistrationTests+<>c.<ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds>b__13_0()
      			[HelperMethodFrame_PROTECTOBJ] (System.RuntimeMethodHandle.InvokeMethod)
      			System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
      			System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
      			System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
      			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
      		Thread #2 (OS 0x14B4) [Finalizer] [Background] 
      			[DebuggerU2MCatchHandlerFrame]
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(225,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/PosixSignalRegistrationTests.Windows.cs(35,0): at System.Tests.PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=798645
**Error message validated:** `[[InlinedCallFrame] (System.Tests.PosixSignalRegistrationTests.AllocConsole)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/5/2024 5:14:24 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[798645](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798645)|dotnet/runtime|[System.Tests.PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798645&view=ms.vss-test-web.build-test-results-tab&runId=20589272&resultId=167139)|dotnet/runtime#107397|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by agocke** [comment]
Closing, as this hasn't reproed.
