### ISSUE TITLE
Test failure: GC/Scenarios/muldimjagary/muldimjagary/muldimjagary.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107528]
**Failed in:** [runtime-coreclr gcstress-extra 20240908.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=801338&view=ms.vss-test-web.build-test-results-tab&runId=20673054&resultId=115612&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked heapverify1 @ (Ubuntu.2004.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8
    - GC/Scenarios/muldimjagary/muldimjagary/muldimjagary.cmd
```

**Error message:**
```
 apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffffaadbf520)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/GC/Scenarios/GC-scenarios1/../muldimjagary/muldimjagary/muldimjagary.sh: line 440:   393 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/muldimjagary/muldimjagary/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true muldimjagary.dll ''
Test should return with ExitCode 100 ...
[createdump] Gathering state for process 393 corerun
[createdump] Crashing thread 0190 signal 5 (0005)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.393.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.393.dmp
[createdump] Written 169508864 bytes (41384 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 280ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 9/8/2024 10:28:52 PM
Processing /home/helixbot/dotnetbuild/dumps/coredump.393.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.393.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0x189
      Child SP               IP Call Site
 0xffffff00c350 0xffffaafe2040 libc.so.6!
 0xffffff00c350 0xffffaabb831c libcoreclr.so!WKS::gc_heap::adjust_limit_clr(unsigned char*, unsigned long, unsigned long, alloc_context*, unsigned int, WKS::heap_segment*, int, int) at ??:0:0
 0xffffff00c400 0xffffaabba8f4 libcoreclr.so!WKS::gc_heap::a_fit_segment_end_p(int, WKS::heap_segment*, unsigned long, alloc_context*, unsigned int, int, int*) at ??:0:0
 0xffffff00c4a0 0xffffaabbb8d4 libcoreclr.so!WKS::gc_heap::soh_try_fit(int, unsigned long, alloc_context*, unsigned int, int, int*, int*) at ??:0:0
 0xffffff00c590 0xffffaabbbdc4 libcoreclr.so!WKS::gc_heap::allocate_soh(int, unsigned long, alloc_context*, unsigned int, int) at ??:0:0
 0xffffff00c610 0xffffaabf0c8c libcoreclr.so!WKS::gc_heap::allocate_more_space(alloc_context*, unsigned long, unsigned int, int) at ??:0:0
 (inlined by) WKS::gc_heap::allocate(unsigned long, alloc_context*, unsigned int) at ??:19630:19
 (inlined by) WKS::GCHeap::Alloc(gc_alloc_context*, unsigned long, unsigned int) at ??:49915:34
 0xffffff00c660 0xffffaaa2fa34 libcoreclr.so!Alloc(unsigned long, GC_ALLOC_FLAGS) at ??:0:0
 0xffffff00c6c0 0xffffaaa2f78c libcoreclr.so!AllocateSzArray(MethodTable*, int, GC_ALLOC_FLAGS) at ??:0:0
 0xffffff00c750 0xffffaaa4f8a8 libcoreclr.so!JIT_NewArr1(CORINFO_CLASS_STRUCT_*, long) at ??:0:0
 0xffffff00c970 0xffff6bfb5c08 muldimjagary.dll!DefaultNamespace.MulDimJagAry.SetThreeDimJagAry(System.Object[][][], Int32, Int32)
 0xffffff00c9f0 0xffff6bfb246c muldimjagary.dll!DefaultNamespace.MulDimJagAry.TestEntryPoint()
 0xffffff00ca70 0xffff6bfb207c muldimjagary.dll!__GeneratedMainWrapper.Main()
----------------------------------
Thread Id: 0x18a
      Child SP               IP Call Site
 0xffff6a5596a0 0xffffab024098 libc.so.6!__poll
 0xffff6a559700 0xffffaae0dc5c libcoreclr.so!CorUnix::CPalSynchronizationManager::ReadBytesFromProcessPipe(int, unsigned char*, int) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:2240:17
 0xffff6a5597a0 0xffffaae0d364 libcoreclr.so!CorUnix::CPalSynchronizationManager::ReadCmdFromProcessPipe(int, CorUnix::CPalSynchronizationManager::SynchWorkerCmd*, void**, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:2016:16
 0xffff6a559810 0xffffaae0c6b0 libcoreclr.so!CorUnix::CPal
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor38|0_39(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by mrsharm** [comment]
Closing since this hasn't repro'd - please reopen if it does again.
