### ISSUE TITLE
[mono] Windows x64 Mono job BinaryFormatterTests exception

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#107553]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=800429
Build error leg or test failing: `System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs`
Affected CI: `windows-x64 Release AllSubsets_Mono`
Range of commits: https://github.com/dotnet/runtime/compare/b10f5c9d...1c4755da

Stack trace: 
```
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs [FAIL]
      System.TypeInitializationException : The type initializer for 'System.Drawing.DrawingCom' threw an exception.
      ---- System.PlatformNotSupportedException : Operation is not supported on this platform.
      Stack Trace:
           at System.Drawing.Bitmap..ctor(Stream stream, Boolean useIcm)
           at System.Drawing.Bitmap..ctor(Stream stream)
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs(1357,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(39,0): at System.Linq.Enumerable.<ToArray>g__EnumerableToArray|314_0[Object[]](IEnumerable`1 source)
        /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(26,0): at System.Linq.Enumerable.ToArray[Object[]](IEnumerable`1 source)
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs(79,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects_MemberData()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
           at System.Drawing.DrawingCom.InitializeComInterfaceEntry()
           at System.Drawing.DrawingCom..cctor()
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=800429
**Error message validated:** `[System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/9/2024 3:32:12 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[896707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707)|dotnet/runtime|[System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707&view=ms.vss-test-web.build-test-results-tab&runId=23520306&resultId=194190)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by matouskozak** [comment]
I think this could be related to https://github.com/dotnet/runtime/pull/107408. Could you take a look @adamsitnik, please?
