### ISSUE TITLE
Test failure: managed/Compilation/Compilation/Compilation.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107527]
**Failed in:** [runtime-coreclr jitstress-random 20240908.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=801287&view=ms.vss-test-web.build-test-results-tab&runId=20672008&resultId=109074&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress_random_1 @ Windows.10.Amd64.Open
    - managed/Compilation/Compilation/Compilation.cmd
```

**Error message:**
```
 
Assert failure(PID 5788 [0x0000169c], Thread: 5524 [0x1594]): Assertion failed 'markedLastLoop && markedCurrLoop' in 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this' during 'Generate code' (IL size 877; hash 0xba50a687; FullOpts)

    File: D:_work1ssrccoreclrjitemit.cpp:6067
    Image: C:hwB8160A1Epcorerun.exe


Return code:      1
Raw output file:      C:hwB8160A1EwAFF409B8uploadsCompilationCompilationoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB8160A1Epcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Compilation.dll 
Starting the test
Using reference to: C:hwB8160A1EpSystem.Private.CoreLib.dll
Test compiled
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 9/8/2024 7:49:13 PM
Processing C:corescorerun.exe.5788.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwB8160A1E		mpgayc4n.tmp" -z "C:corescorerun.exe.5788.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.5788.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB8160A1EpPDB
Symbol search path is: C:hwB8160A1EpPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sun Sep  8 19:49:51.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:02:36.595
Process Uptime: 0 days 0:00:37.000
..................................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(169c.1594): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=0da098c8 ebx=00000000 ecx=00000000 edx=00000000 esi=0da09878 edi=0da098c8
eip=72926066 esp=0da09ba8 ebp=0da0ac34 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!FailFastOnAssert+0x21:
72926066 5e              pop     esi
0:005> cdb: Reading initial command '$<C:hwB8160A1E		mpgayc4n.tmp'
0:005> .load C:Users
unner.dotnetsossos.dll
0:005> ~*k

   0  Id: 169c.1680 Suspend: 0 Teb: 02d24000 Unfrozen
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
02bbdb6c 725c5c5f ntdll!NtWaitForMultipleObjects+0xc
02bbdbf0 725c618d coreclr!Thread::DoAppropriateAptStateWait+0xc7
02bbdd4c 725cc5bc coreclr!Thread::DoAppropriateWaitWorker+0x3e6
02bbdda0 725c5d16 coreclr!`Thread::DoAppropriateWait'::`9'::__Body::Run+0x5a
02bbde04 727a0b0e coreclr!Thread::DoAppropriateWait+0x95
02bbdeb4 727a08f4 coreclr!CLREventBase::WaitEx+0x216
02bbdec8 725d050a coreclr!CLREventBase::Wait+0x17
02bbdee8 725c2f06 coreclr!Thread::Wait+0x3c
02bbdf00 725c0f50 coreclr!Thread::Block+0x3a
02bbe030 725c0ce0 coreclr!SyncBlock::Wait+0x232
02bbe0a4 729e57eb coreclr!ObjHeader::Wait+0xba
*** WARNING: Unable to verify checksum for System.Private.CoreLib.dll
(Inline) -------- coreclr!Object::Wait+0x
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by EgorBo** [comment]
Loop alignment assert

**Comment by EgorBo** [comment]
Closing as a dup of https://github.com/dotnet/runtime/issues/107518
