### ISSUE TITLE
Failing test cases System.IO.FileSystem

### ISSUE THREAD

**Issue by saitama951** [dotnet/runtime#107636]
I have been recently seeing test case failures relating to System.IO.FileSystem on s390x.
```
[xUnit.net 00:00:10.87]     System.IO.Tests.File_ReadWriteAllBytesAsync.WriteToReadOnlyFileAsync [FAIL]
  Failed System.IO.Tests.File_ReadWriteAllBytesAsync.WriteToReadOnlyFileAsync [3 ms]
  Error Message:
   Assert.Equal() Failure: Collections differ
                          ↓ (pos 4)
Expected: [···, 120, 116, 116, 101, 120, ···]
Actual:   [···, 120, 116]
  Stack Trace:
     at System.IO.Tests.File_ReadWriteAllBytesAsync.WriteToReadOnlyFileAsync() in /home/sanjam/runtime/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/ReadWriteAllBytesAsync.cs:line 128
```

```
[xUnit.net 00:00:10.18]     System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile [FAIL]
  Failed System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile [1 s]
  Error Message:
   Assert.Equal() Failure: Collections differ
                          ↓ (pos 4)
Expected: [···, 120, 116, 116, 101, 120, ···]
Actual:   [···, 120, 116]
  Stack Trace:
     at System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile() in /home/sanjam/runtime/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/ReadWriteAllBytes.cs:line 117
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /home/sanjam/runtime/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs:line 22
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /home/sanjam/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
   ```
   Although this also fails when running as a extracted test case on x64  (with net9-preview7) 
   The failures were introduced here #103308 
   
   cc: @giritrivedi @omajid @stephentoub @akoeplinger

**Comment by saitama951** [comment]
The problem seems to here 
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/ReadWriteAllBytes.cs#L116
and 
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/ReadWriteAllBytesAsync.cs#L128
I believe according to the documentation `WriteAllBytes` overwrites the data in the file

shouldn't the assert should be `"text"u8` instead of  `"texttext"u8`

**Comment by adamsitnik** [comment]
> I believe according to the documentation WriteAllBytes overwrites the data in the file

It sounds reasonable. 

@jozkee @stephentoub Could you PTAL? (I am busy with some last minute bug fixes in NRBF)
