### ISSUE TITLE
Certificate pinning is not working in MAUI Android application

### ISSUE THREAD

**Issue by Joshna-Lingala** [dotnet/runtime#107642]
### Description

We are receiving below exception for MAUI Android application, but it is working fine in iOS. This is working fine in lower environments like Staging (Windows 2019) and UAT (Windows 2019) but this issue is occurring only in Production server (Windows 2022).

**Exception :**
```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.Receive(Span`1 buffer, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SyncReadWriteAdapter.ReadAsync(Stream stream, Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<EnsureFullTlsFrameAsync>d__157`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Runtime.CompilerServices.IAsyncStateMachine, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__159`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Runtime.CompilerServices.IAsyncStateMachine, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request)
```
### Steps to Reproduce

1. Clone application from the below repository.
2. Run the application.
3. Click on button.
4. Above shared exception occurs. 

### Link to public reproduction project repository

https://github.com/Joshna-Lingala/CertPinningIssue

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Joshna-Lingala** [comment]
@wfurt Could you please let us know any update on this?

**Comment by wfurt** [comment]
I'm not Android person. @simonrozsival  is the right guy to look at this. 
But looking at the exception it seems like something with the peer.
```Connection reset by peer```
Geting packet capture would be good start IMHO.

**Comment by simonrozsival** [comment]
@Joshna-Lingala Can you also please share information about the Android device(s) you're using for testing? Also do I understand it correctly that the same code works correctly in your staging environment, but it doesn't work with the production environment (when the right certificate for the right server is used)?

This scenario should be fully supported, so I'm surprised this isn't working consistently. I wasn't able to find the relevant communication data in the attached package capture, but I was able to reproduce it locally (Android emulator API 33):

![image](https://github.com/user-attachments/assets/0ab67a30-1e8d-4416-b8d7-f385d70d65a6)

From what I can tell, the client never sends the client certificate. I can see that the certificate is correctly loaded and the Android key store should be configured correctly. For some reason, the java SSLEngine doesn't send the certificate to the server. 

@wfurt is there something that stands out in my packet capture?

[simonrozsival-issue-107642-packetcapture.pcapng.zip](https://github.com/user-attachments/files/17044133/simonrozsival-issue-107642-packetcapture.pcapng.zip)

**Comment by Joshna-Lingala** [comment]
@simonrozsival we are using Samsung Mobile device for testing the application.

However, after a research found that issue was resolved when we have disabled TLS1.3 on Windows 2022 IIS server. If we enable TLS1.3 issue is occurring. Could you please look into this issue further so that this issue will not occur in further future.

**Comment by simonrozsival** [comment]
This is very interesting. I'm glad you found a workaround. Right now, I'm not sure if this is a limitation of .NET or of the underlying Android APIs. I need to do more digging to get to the bottom of this.

**Comment by simonrozsival** [comment]
@Joshna-Lingala I tried running your test app against your server again and I'm not seeing any `Certificate Request` coming from the server and no `Certificate` being sent from the client to the server and I'm still getting a 200 response from the server. Is client authentication currently disabled?

**Comment by wfurt** [comment]
note that TLS 1.3 uses different mechanism for post-handshake authentication,. Do you see claim for support in client hello @simonrozsival? And part of the TLS 1.3 handshake is encrypted so you may not see the request either ... if that happens during handshake.

**Comment by simonrozsival** [comment]
@wfurt I'm not sure what I'm looking for in the Client hello - is that the `key_share` extension? You can find the whole packet capture here if you're interested: https://github.com/dotnet/runtime/issues/107642#issuecomment-2358379532

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/1e095050-2f04-48c9-8b20-ecd91d9b6e87">
<img width="668" alt="image" src="https://github.com/user-attachments/assets/4f67acf9-beec-4950-b8b5-7dc3fceb704a">

**Comment by wfurt** [comment]
I'm not 100% sure if that is relevant. But the server can ask for client certificate during handshake or it can do it later ... for example if you access particular URL.  With TLS 1.2 you would `CertificateRequets` message (or EncryptedHandshake message) but for TLS 1.3 that part is already encrypted so it is difficult to see what is exactly goin on just from the packet capture.  So best way may be to analyze 1.2 working case first and assuming the server setting is the same apply that learning to TLS 1.3. 

To answer your question, you would be looking for this:

![image](https://github.com/user-attachments/assets/639a31e3-503f-4ae9-93db-bde81124e94d)

The empty extension indicates client willingness to provide certificate later if needed. Without it, the server would not even try to ask. 

For OpenSSL it is set explicitly here:

https://github.com/dotnet/runtime/blob/45343ce62358df7db57fcff8738c24d868046a0c/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L434-L441

You _could_ possibly set it unconditionally IMHO if such option exists on Android. The conditional is just optimization to avoid extra work in case we know we won't have any certificate. 

Note that this depends on the server so you may not see it when you set local repro. 
I briefly looked at the repro and it seems to have only client. Do you get repro yourself @simonrozsival ?
