### ISSUE TITLE
JsonSerializer.Deserialize throws not expected ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by sancheolz** [dotnet/runtime#107729]
### Description

Issue has been found by fuzzing with AFL++ and SharpFuzz package. The [documentation ](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.deserialize?view=net-8.0#system-text-json-jsonserializer-deserialize-1(system-io-stream-system-text-json-serialization-metadata-jsontypeinfo((-0))))says that the expected exceptions are ArgumentNullException, JSONException and NotSupportedException, but it throws not expected ArgumentOutOfRangeException in some input cases.

### Reproduction Steps

Run this fuzzing target with attached input.
````csharp
﻿using System;
using System.Collections.Generic;
using System.Text.Json;
using SharpFuzz;

namespace JsonSerializerFuzzer;

public class Item
{
    public byte A { get; set; }
    public int B { get; set; }
    public double C { get; set; }
    public DateTime D { get; set; }
    public string? E { get; set; }
    public short[]? F { get; set; }
    public Item? G { get; set; }
    public Dictionary<string, int>? H { get; set; }
}

public class Program
{
    public static void Main()
    {
        Fuzzer.OutOfProcess.Run(span =>
        {
            try
            {
                JsonSerializer.Deserialize<Item>(span);
            }
            catch (JsonException)
            {
            }
            catch (NotSupportedException)
            {
            }
        });
    }
}
````

For example you can replace `span` value with this string
`{"A":123,"B":1024,"C":3.6415,"D":"2010-10-\\"6":1123,"-15TR\"7":123,"08;":néll,"H":{"10":10,"1{:A":1223,"\"7":102<"B5T08;BR\\:A":1223,"\"7":1024,"R\"7":123,"08;BR\\:A"`

[crashes.zip](https://github.com/user-attachments/files/16975693/crashes.zip)

### Expected behavior

Throw [JsonException](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonexception?view=net-8.0)

### Actual behavior

Throws ArgumentOutOfRangeException.

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Text.Json.JsonHelpers.TryParseDateTimeOffset(ReadOnlySpan`1 source, DateTimeParseData& parseData)
   at System.Text.Json.JsonHelpers.TryParseAsISO(ReadOnlySpan`1 source, DateTime& value)
   at System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime(ReadOnlySpan`1 source, DateTime& value)
   at System.Text.Json.Utf8JsonReader.TryGetDateTimeCore(DateTime& value)
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
   at System.Text.Json.Utf8JsonReader.GetDateTime()
   at System.Text.Json.Serialization.Converters.DateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAll[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadAllUsingOptions[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream utf8Json, JsonSerializerOptions options)
   at JsonSerializerFuzzer.Program.<>c.<Main>b__0_0(Stream span) in /home/fuzzer/runtime-sdl-dotnet-lib-fuzz/System.Text.Json.JsonSerializer/Program.cs:line 28
   at SharpFuzz.Fuzzer.RunWithoutAflFuzz(Action`1 action, Stream stream)
   at SharpFuzz.Fuzzer.OutOfProcess.Run(Action`1 action)
   at JsonSerializerFuzzer.Program.Main() in /home/fuzzer/runtime-sdl-dotnet-lib-fuzz/System.Text.Json.JsonSerializer/Program.cs:line 24
``` 

### Configuration

.NET v6.0.32 at e77011b31a3e5c47d931248a64b47f9b2d47853d

**Comment by eiriktsarpalis** [comment]
Did you try fuzzing against .NET 8 or .NET 9? I can't reproduce the crash with these versions. I believe what you're seeing is essentially a duplicate of a bug that got fixed in https://github.com/dotnet/runtime/pull/63534

**Comment by elgonzo** [comment]
> .NET v6.0.32

That's mightily old. .NET 6 will go out of support in about two months. I don't expect anyone in the team to put much import on this, unless you can confirm whether the issue still occurs with the still current .NET 8 or the 9.x preview versions?

**Comment by sancheolz** [comment]
Thank you. I've tried to pass these input strings to the .NET 8 test and the test passed. I have not tried full fuzzing this target with .NET 8. I don't think that full fuzzing against .NET 8 will give similar crashes, since they have almost the same path.
