### ISSUE TITLE
terminate called after throwing an instance of 'PAL_SEHException'

### ISSUE THREAD

**Issue by JackJiang1234** [dotnet/runtime#107785]
Hey buddy, we have an ASP.NET Core app deployed in a Kubernetes Docker environment. Lately, it’s been crashing occasionally, and the error message is as stated in the title, but there's no stack trace. We're using .NET Core version net6. Do you know any way to catch the specific error details?

**Comment by colejohnson66** [comment]
Does the issue still occur on .NET 8 or .NET 9?

**Comment by jkotas** [comment]
`PAL_SEHException` should be always caught by the runtime code, it should never escape unhandled. If you see it escaping unhandled, it means there is a bug in the runtime. To get more detail, you would need to get a crash dump and inspect it under native debugger (lldb).

We have fixed a few bugs that can cause `PAL_SEHException` to escape. I agree with @colejohnson66 that upgrading to newer version is a good idea. .NET 6 has only two months of life left, so you will need to upgrade soon anyway to stay on a supported version.

**Comment by JackJiang1234** [comment]
Thanks for getting back to me. We're using CoreCLR. We referred to https://learn.microsoft.com/zh-cn/dotnet/core/diagnostics/collect-dumps-crash to set up crash dumps. I'll keep you posted with any further updates.

**Comment by JackJiang1234** [comment]
i got the crash dump,  but i can't find any crash info.   
![1727148554369](https://github.com/user-attachments/assets/facb4021-9a6e-4c51-aabe-cf753e97a1ab)
![1727148615707](https://github.com/user-attachments/assets/d8a4d705-b24d-47c0-ae9a-174a11f01ba5)
do you have any suggest?  thank you

**Comment by jkotas** [comment]
This is low-level runtime crash. `dotnet-dump` won't be able to diagnose it. `dotnet-dump` works for managed crashes only.

Could you please open the crash dump in lldb debugger and get the stacktrace?

**Comment by JackJiang1234** [comment]
thanks for response ,  i will try the lldb deubgger.

**Comment by ShivamBhardwaj93** [comment]
hello, I also got this error, here are the specifics, I am on ubuntu 22 and i'm trying to code in python with pythonnet to use methods of a .netcore library ( my company's) this is the core dump I got
` root@enguser:~# coredumpctl debug 532802
           PID: 532802 (python)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Mon 2025-08-25 23:19:24 PDT (26s ago)
  Command Line: /root/v/venv/bin/python /root/v/testcases/protectapp/dotnetcore/shivam/1.py
    Executable: /usr/bin/python3.10
 Control Group: /user.slice/user-0.slice/session-41.scope
          Unit: session-41.scope
         Slice: user-0.slice
       Session: 41
     Owner UID: 0 (root)
       Boot ID: 571b11f7c3c2481084e76792c30030b7
    Machine ID: 0e72eff8b1e341e482ce5619164498fc
      Hostname: enguser
       Storage: /var/lib/systemd/coredump/core.python.0.571b11f7c3c2481084e76792c30030b7.532802.1756189164000000.zst (present)
     Disk Size: 13.8M
       Message: Process 532802 (python) of user 0 dumped core.
                
                Found module /root/v/venv/lib/python3.10/site-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so with build-id: 26ed60072bff621a3d04b423912b94ffa3f8ac14
                Found module linux-vdso.so.1 with build-id: 8f6d5e26d7303ac48c3036ff1bc8c52dcca0ad65
                Found module libicui18n.so.70 with build-id: ff2dbcdd92cbe5a63d20291e295d8fed9f87d35b
                Found module libicudata.so.70 with build-id: b1c2496dd0543023c7a19c961bb7f3abc818f465
                Found module libicuuc.so.70 with build-id: bef3ff1d70aadd68aab07d858a759360c8b919ae
                Found module libSystem.Native.so with build-id: 698316f6f9fbc20f0886441ba56e3f7f59792c89
                Found module libclrjit.so with build-id: 16500672b654cfb87912fc386d118efa313227ca
                Found module librt.so.1 with build-id: cb5b17a9bdf060b73ecac80f77fb2c535ef84612
                Found module libcoreclr.so with build-id: e1722451f96072c770b6ead831a68576f3387e96
                Found module libhostpolicy.so with build-id: efdb9bb2b5ab2384c3dbaefcb12900e778c2859f
                Found module libgcc_s.so.1 with build-id: 3ae8ad2eded3e51695b509273c67832869daf90b
                Found module libstdc++.so.6 with build-id: e72c155b714bc42a767ec9c0dd94589110e5b42f
                Found module libdl.so.2 with build-id: c71c8c73dd8b7323bd6190420f0ebc4301e93186
                Found module libhostfxr.so with build-id: 073b2ecca0da32538390aa40d51436f38dc67ac2
                Found module libpthread.so.0 with build-id: 81f46d553e2f7c999e43c3eede73a822bc8d5d93
                Found module _opcode.cpython-310-x86_64-linux-gnu.so with build-id: bd9c71a0c269c3bb70b5d4c35667277e4ffb7767
                Found module liblzma.so.5 with build-id: b85da6c48eb60a646615392559483b93617ef265
                Found module _lzma.cpython-310-x86_64-linux-gnu.so with build-id: 27d63d8a76633403f36e74050b121a29d1774715
                Found module libbz2.so.1.0 with build-id: e56b62c27bcc7ace8f9be36b255bd7b31bfde405
                Found module _bz2.cpython-310-x86_64-linux-gnu.so with build-id: b725712d936960611982c5268a558462c0266f64
                Found module _json.cpython-310-x86_64-linux-gnu.so with build-id: df02232316250800cd082493393d33af869c21b1
                Found module termios.cpython-310-x86_64-linux-gnu.so with build-id: ba493002dc09c1d0b5dcf882b0c4574050c1134c
                Found module ld-linux-x86-64.so.2 with build-id: 9cb53985768bb99f138f48655f7b8bf7e420d13d
                Found module libc.so.6 with build-id: d5197096f709801829b118af1b7cf6631efa2dcd
                Found module libz.so.1 with build-id: 30840b79ac329ecbf1dec0bb60180eed256d319f
                Found module libexpat.so.1 with build-id: 0b6c4077faed982d2a40f9b30908095113fadc52
                Found module libm.so.6 with build-id: a3ad9bb40b4907e509e4404cb972645c19675ca3
                Found module python3.10 with build-id: b2fd9010dc75aa747aee5296c31a07d210d124ad
                Stack trace of thread 532802:
                #0  0x00007f1f7dfff9fc __pthread_kill_implementation (libc.so.6 + 0x969fc)
                #1  0x00007f1f7dfab476 __GI_raise (libc.so.6 + 0x42476)
                #2  0x00007f1f7df91885 __GI_abort (libc.so.6 + 0x28885)
                #3  0x00007f1f7cfb3b9e n/a (libstdc++.so.6 + 0xa2b9e)
                #4  0x00007f1f7cfbf20c n/a (libstdc++.so.6 + 0xae20c)
                #5  0x00007f1f7cfbf277 _ZSt9terminatev (libstdc++.so.6 + 0xae277)
                #6  0x00007f1f7cfbf52b __cxa_rethrow (libstdc++.so.6 + 0xae52b)
                #7  0x00007f1f78f8105b n/a (libclrjit.so + 0xf405b)
                #8  0x00007f1f78f78224 n/a (libclrjit.so + 0xeb224)
                #9  0x00007f1efe61578a n/a (n/a + 0x0)
                #10 0x00007f1efe616727 n/a (n/a + 0x0)
                #11 0x00007f1efe615ff5 n/a (n/a + 0x0)
                #12 0x00007f1f7c9eab2b n/a (libcoreclr.so + 0x23db2b)
                #13 0x00007f1f7c9ead33 n/a (libcoreclr.so + 0x23dd33)
                #14 0x00007f1f7c9eb8d7 n/a (libcoreclr.so + 0x23e8d7)
                #15 0x00007f1f7ca272da n/a (libcoreclr.so + 0x27a2da)
                #16 0x00007f1f7ca26bbb n/a (libcoreclr.so + 0x279bbb)
                #17 0x00007f1f7ca2631f n/a (libcoreclr.so + 0x27931f)
                #18 0x00007f1f7ca25d2d n/a (libcoreclr.so + 0x278d2d)
                #19 0x00007f1f7c9968f8 n/a (libcoreclr.so + 0x1e98f8)
                #20 0x00007f1f7ca2a346 n/a (libcoreclr.so + 0x27d346)
                #21 0x00007f1f7ca29ea4 n/a (libcoreclr.so + 0x27cea4)
                #22 0x00007f1f7cc4ab50 n/a (libcoreclr.so + 0x49db50)
                #23 0x00007f1efe61a28b n/a (n/a + 0x0)
                #24 0x00007f1f7cc49c37 n/a (libcoreclr.so + 0x49cc37)
                #25 0x00007f1f7ca83646 n/a (libcoreclr.so + 0x2d6646)
                #26 0x00007f1f7cb34f62 n/a (libcoreclr.so + 0x387f62)
                #27 0x00007f1efda9753c n/a (n/a + 0x0)
                #28 0x00007f1efe5ec4c5 n/a (n/a + 0x0)
                #29 0x00007f1efe5ea5b8 n/a (n/a + 0x0)
                #30 0x00007f1efe617b3f n/a (n/a + 0x0)
                #31 0x00007f1efe5ea049 n/a (n/a + 0x0)
                #32 0x000055e8f954af4b PyObject_Call (python3.10 + 0x198f4b)
                #33 0x00007f1efe5e693b n/a (n/a + 0x0)
                #34 0x00007f1efe616b0d n/a (n/a + 0x0)
                #35 0x00007f1efe616a71 n/a (n/a + 0x0)
                #36 0x00007f1efe6043af n/a (n/a + 0x0)
                #37 0x00007f1efe5ea049 n/a (n/a + 0x0)
                #38 0x000055e8f953342b _PyObject_MakeTpCall (python3.10 + 0x18142b)
                #39 0x000055e8f952caf7 _PyEval_EvalFrameDefault (python3.10 + 0x17aaf7)
                #40 0x000055e8f953d1bc _PyFunction_Vectorcall (python3.10 + 0x18b1bc)
                #41 0x000055e8f9527820 _PyEval_EvalFrameDefault (python3.10 + 0x175820)
                #42 0x000055e8f960c566 n/a (python3.10 + 0x25a566)
                #43 0x000055e8f960c436 PyEval_EvalCode (python3.10 + 0x25a436)
                #44 0x000055e8f9632ed8 n/a (python3.10 + 0x280ed8)
                #45 0x000055e8f962d6df n/a (python3.10 + 0x27b6df)
                #46 0x000055e8f9632c75 n/a (python3.10 + 0x280c75)
                #47 0x000055e8f9632258 _PyRun_SimpleFileObject (python3.10 + 0x280258)
                #48 0x000055e8f9631f37 _PyRun_AnyFileObject (python3.10 + 0x27ff37)
                #49 0x000055e8f96263ae Py_RunMain (python3.10 + 0x2743ae)
                #50 0x000055e8f960047d Py_BytesMain (python3.10 + 0x24e47d)
                #51 0x00007f1f7df92d90 __libc_start_call_main (libc.so.6 + 0x29d90)
                #52 0x00007f1f7df92e40 __libc_start_main_impl (libc.so.6 + 0x29e40)
                #53 0x000055e8f9600375 _start (python3.10 + 0x24e375)
                
                Stack trace of thread 532804:
                #0  0x00007f1f7e081bcf __GI___poll (libc.so.6 + 0x118bcf)
                #1  0x00007f1f7ccb09fc n/a (libcoreclr.so + 0x5039fc)
                #2  0x00007f1f7cd6857b n/a (libcoreclr.so + 0x5bb57b)
                #3  0x00007f1f7cd66026 n/a (libcoreclr.so + 0x5b9026)
                #4  0x00007f1f7cdbfe9e n/a (libcoreclr.so + 0x612e9e)
                #5  0x00007f1f7dffdac3 start_thread (libc.so.6 + 0x94ac3)
                #6  0x00007f1f7e08f850 __clone3 (libc.so.6 + 0x126850)
                
                Stack trace of thread 532828:
                #0  0x00007f1f7dffa117 __futex_abstimed_wait_common64 (libc.so.6 + 0x91117)
                #1  0x00007f1f7dffce9b __pthread_cond_wait_common (libc.so.6 + 0x93e9b)
                #2  0x00007f1f7cdb4735 n/a (libcoreclr.so + 0x607735)
                #3  0x00007f1f7cdb439f n/a (libcoreclr.so + 0x60739f)
                #4  0x00007f1f7cdb96b9 n/a (libcoreclr.so + 0x60c6b9)
                #5  0x00007f1f7ca55f3a n/a (libcoreclr.so + 0x2a8f3a)
                #6  0x00007f1f7ca55def n/a (libcoreclr.so + 0x2a8def)
                #7  0x00007f1f7ca52855 n/a (libcoreclr.so + 0x2a5855)
                #8  0x00007f1f7ca52e2d n/a (libcoreclr.so + 0x2a5e2d)
                #9  0x00007f1f7ca55d00 n/a (libcoreclr.so + 0x2a8d00)
                #10 0x00007f1f7cdbfe9e n/a (libcoreclr.so + 0x612e9e)
                #11 0x00007f1f7dffdac3 start_thread (libc.so.6 + 0x94ac3)
                #12 0x00007f1f7e08f850 __clone3 (libc.so.6 + 0x126850)
                
                Stack trace of thread 532806:
                #0  0x00007f1f7dffa117 __futex_abstimed_wait_common64 (libc.so.6 + 0x91117)
                #1  0x00007f1f7dffca41 __pthread_cond_wait_common (libc.so.6 + 0x93a41)
                #2  0x00007f1f7cdb4792 n/a (libcoreclr.so + 0x607792)
                #3  0x00007f1f7cdb439f n/a (libcoreclr.so + 0x60739f)
                #4  0x00007f1f7cdb8f95 n/a (libcoreclr.so + 0x60bf95)
                #5  0x00007f1f7cdb9243 n/a (libcoreclr.so + 0x60c243)
                #6  0x00007f1f7cca900d n/a (libcoreclr.so + 0x4fc00d)
                #7  0x00007f1f7cca8e88 n/a (libcoreclr.so + 0x4fbe88)
                #8  0x00007f1f7cca8b85 n/a (libcoreclr.so + 0x4fbb85)
                #9  0x00007f1f7cdbfe9e n/a (libcoreclr.so + 0x612e9e)
                #10 0x00007f1f7dffdac3 start_thread (libc.so.6 + 0x94ac3)
                #11 0x00007f1f7e08f850 __clone3 (libc.so.6 + 0x126850)
                
                Stack trace of thread 532803:
                #0  0x00007f1f7e081bcf __GI___poll (libc.so.6 + 0x118bcf)
                #1  0x00007f1f7cdb6e51 n/a (libcoreclr.so + 0x609e51)
                #2  0x00007f1f7cdb64a3 n/a (libcoreclr.so + 0x6094a3)
                #3  0x00007f1f7cdbfe9e n/a (libcoreclr.so + 0x612e9e)
                #4  0x00007f1f7dffdac3 start_thread (libc.so.6 + 0x94ac3)
                #5  0x00007f1f7e08f850 __clone3 (libc.so.6 + 0x126850)
                
                Stack trace of thread 532805:
                #0  0x00007f1f7e07d5b4 __libc_open64 (libc.so.6 + 0x1145b4)
                #1  0x00007f1f7ccb140f n/a (libcoreclr.so + 0x50440f)
                #2  0x00007f1f7ccab757 n/a (libcoreclr.so + 0x4fe757)
                #3  0x00007f1f7ccaa8e5 n/a (libcoreclr.so + 0x4fd8e5)
                #4  0x00007f1f7cdbfe9e n/a (libcoreclr.so + 0x612e9e)
                #5  0x00007f1f7dffdac3 start_thread (libc.so.6 + 0x94ac3)
                #6  0x00007f1f7e08f850 __clone3 (libc.so.6 + 0x126850)
                
                Stack trace of thread 532807:
                #0  0x00007f1f7dffa117 __futex_abstimed_wait_common64 (libc.so.6 + 0x91117)
                #1  0x00007f1f7dffce9b __pthread_cond_wait_common (libc.so.6 + 0x93e9b)
                #2  0x00007f1f7cdb4735 n/a (libcoreclr.so + 0x607735)
                #3  0x00007f1f7cdb439f n/a (libcoreclr.so + 0x60739f)
                #4  0x00007f1f7cdb8f95 n/a (libcoreclr.so + 0x60bf95)
                #5  0x00007f1f7cdb9169 n/a (libcoreclr.so + 0x60c169)
                #6  0x00007f1f7cb55bbe n/a (libcoreclr.so + 0x3a8bbe)
                #7  0x00007f1f7cac0e6f n/a (libcoreclr.so + 0x313e6f)
                #8  0x00007f1f7cac106f n/a (libcoreclr.so + 0x31406f)
                #9  0x00007f1f7ca52855 n/a (libcoreclr.so + 0x2a5855)
                #10 0x00007f1f7ca52e7d n/a (libcoreclr.so + 0x2a5e7d)
                #11 0x00007f1f7cac12c8 n/a (libcoreclr.so + 0x3142c8)
                #12 0x00007f1f7cdbfe9e n/a (libcoreclr.so + 0x612e9e)
                #13 0x00007f1f7dffdac3 start_thread (libc.so.6 + 0x94ac3)
                #14 0x00007f1f7e08f850 __clone3 (libc.so.6 + 0x126850)

GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.10...
(No debugging symbols found in /usr/bin/python3.10)

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing
[New LWP 532802]
[New LWP 532804]
[New LWP 532828]
[New LWP 532806]
[New LWP 532803]
[New LWP 532805]
[New LWP 532807]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/root/v/venv/bin/python /root/v/testc'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139773234020352) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1f7df68000 (LWP 532802))]
(gdb) thread apply all bt

Thread 7 (Thread 0x7f1f7a67b640 (LWP 532807)):
#0  __futex_abstimed_wait_common64 (private=24, cancel=true, abstime=0x7f1f7a67a690, op=137, expected=0, futex_word=0x55e8fa855024) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=24, abstime=0x7f1f7a67a690, clockid=-91933440, expected=0, futex_word=0x55e8fa855024) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55e8fa855024, expected=expected@entry=0, clockid=clockid@entry=1, abstime=abstime@entry=0x7f1f7a67a690, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f1f7dffce9b in __pthread_cond_wait_common (abstime=0x7f1f7a67a690, clockid=1, mutex=0x55e8fa854fd0, cond=0x55e8fa854ff8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_timedwait64 (cond=0x55e8fa854ff8, mutex=0x55e8fa854fd0, abstime=0x7f1f7a67a690) at ./nptl/pthread_cond_wait.c:652
#5  0x00007f1f7cdb4735 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#6  0x00007f1f7cdb439f in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#7  0x00007f1f7cdb8f95 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#8  0x00007f1f7cdb9169 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#9  0x00007f1f7cb55bbe in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#10 0x00007f1f7cac0e6f in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#11 0x00007f1f7cac106f in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#12 0x00007f1f7ca52855 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#13 0x00007f1f7ca52e7d in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#14 0x00007f1f7cac12c8 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#15 0x00007f1f7cdbfe9e in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#16 0x00007f1f7dffdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#17 0x00007f1f7e08f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7f1f7b78f640 (LWP 532805)):
#0  0x00007f1f7e07d5b4 in __libc_open64 (file=0x55e8fa771c74 "/tmp/clr-debug-pipe-532802-6544070-in", oflag=0) at ../sysdeps/unix/sysv/linux/open64.c:41
#1  0x00007f1f7ccb140f in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#2  0x00007f1f7ccab757 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#3  0x00007f1f7ccaa8e5 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#4  0x00007f1f7cdbfe9e in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#5  0x00007f1f7dffdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007f1f7e08f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7f1f7c7a7640 (LWP 532803)):
#0  0x00007f1f7e081bcf in __GI___poll (fds=0x7f1f7c7a6cf8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f1f7cdb6e51 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#2  0x00007f1f7cdb64a3 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#3  0x00007f1f7cdbfe9e in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#4  0x00007f1f7dffdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007f1f7e08f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7f1f7af8a640 (LWP 532806)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55e8fa825b40) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x55e8fa825b40) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55e8fa825b40, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f1f7dffca41 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55e8fa825af0, cond=0x55e8fa825b18) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55e8fa825b18, mutex=0x55e8fa825af0) at ./nptl/pthread_cond_wait.c:627
#5  0x00007f1f7cdb4792 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#6  0x00007f1f7cdb439f in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#7  0x00007f1f7cdb8f95 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#8  0x00007f1f7cdb9243 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#9  0x00007f1f7cca900d in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#10 0x00007f1f7cca8e88 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#11 0x00007f1f7cca8b85 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#12 0x00007f1f7cdbfe9e in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00007f1f7dffdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#14 0x00007f1f7e08f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7f1f78a7c640 (LWP 532828)):
#0  __futex_abstimed_wait_common64 (private=-91729136, cancel=true, abstime=0x7f1f78a7bac0, op=137, expected=0, futex_word=0x55e8fa886304) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=-91729136, abstime=0x7f1f78a7bac0, clockid=0, expected=0, futex_word=0x55e8fa886304) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55e8fa886304, expected=expected@entry=0, clockid=clockid@entry=1, abstime=abstime@entry=0x7f1f78a7bac0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f1f7dffce9b in __pthread_cond_wait_common (abstime=0x7f1f78a7bac0, clockid=1, mutex=0x55e8fa8862b0, cond=0x55e8fa8862d8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_timedwait64 (cond=0x55e8fa8862d8, mutex=0x55e8fa8862b0, abstime=0x7f1f78a7bac0) at ./nptl/pthread_cond_wait.c:652
#5  0x00007f1f7cdb4735 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#6  0x00007f1f7cdb439f in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#7  0x00007f1f7cdb96b9 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#8  0x00007f1f7ca55f3a in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#9  0x00007f1f7ca55def in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#10 0x00007f1f7ca52855 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#11 0x00007f1f7ca52e2d in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#12 0x00007f1f7ca55d00 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#13 0x00007f1f7cdbfe9e in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#14 0x00007f1f7dffdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#15 0x00007f1f7e08f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7f1f7bfa6640 (LWP 532804)):
#0  0x00007f1f7e081bcf in __GI___poll (fds=0x7f1ef0000f00, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f1f7ccb09fc in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#2  0x00007f1f7cd6857b in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#3  0x00007f1f7cd66026 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#4  0x00007f1f7cdbfe9e in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#5  0x00007f1f7dffdac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007f1f7e08f850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f1f7df68000 (LWP 532802)):
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139773234020352) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139773234020352) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139773234020352, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f1f7dfab476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f1f7df91885 in __GI_abort () at ./stdlib/abort.c:100
#5  0x00007f1f7cfb3b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f1f7cfbf20c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f1f7cfbf277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f1f7cfbf52b in __cxa_rethrow () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f1f78f8105b in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libclrjit.so
#10 0x00007f1f78f78224 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libclrjit.so
#11 0x00007f1efe61578a in ?? ()
#12 0x0000000003e68c43 in ?? ()
#13 0x00007f1f7ce1b238 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.19/libcoreclr.so
#14 0x00007ffc63351d00 in ?? ()
#15 0x0000000000000000 in ?? ()
(gdb) exit`
