### ISSUE TITLE
Test failure: JIT/Stress/ABI/tailcalls_do/tailcalls_do.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107727]
**Failed in:** [runtime-coreclr outerloop 20240911.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=804759&view=ms.vss-test-web.build-test-results-tab&runId=20794468&resultId=123349&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.11.Arm64.Open
    - JIT/Stress/ABI/tailcalls_do/tailcalls_do.cmd
```

**Error message:**
```
 
cmdLine:C:hwAB970948wB37B097FeJITJIT_do../Stress/ABI/tailcalls_do/tailcalls_do.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 9/11/2024 10:39:55 AM, end: 9/11/2024 11:09:55 AM)

Return code:      -100
Raw output file:      C:hwAB970948wB37B097FuploadsStressABI	ailcalls_dooutput.txt
Raw output:
BEGIN EXECUTION
tailcalls_do.dll
        1 file(s) copied.
10:39:55.95
Response file: C:hwAB970948wB37B097FeJITStressABI	ailcalls_do	ailcalls_do.dll.rsp
C:hwAB970948wB37B097FeJITStressABI	ailcalls_doIL-CG2	ailcalls_do.dll
-o:C:hwAB970948wB37B097FeJITStressABI	ailcalls_do	ailcalls_do.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwAB970948pSystem.*.dll
-r:C:hwAB970948pMicrosoft.*.dll
-r:C:hwAB970948p\xunit.*.dll
-r:C:hwAB970948pmscorlib.dll
-r:C:hwAB970948p
etstandard.dll
" "C:hwAB970948pcrossgen2crossgen2.exe" @"C:hwAB970948wB37B097FeJITStressABI	ailcalls_do	ailcalls_do.dll.rsp"   -r:C:hwAB970948wB37B097FeJITJIT_doIL-CG2*.dll  -r:C:hwAB970948wB37B097FeJITStressABI	ailcalls_doIL-CG2*.dll"
Emitting R2R PE file: C:hwAB970948wB37B097FeJITStressABI	ailcalls_do	ailcalls_do.dll
" "dotnet" "C:hwAB970948p
2rdump
2rdump.dll" --header --sc --in C:hwAB970948wB37B097FeJITStressABI	ailcalls_do	ailcalls_do.dll --out C:hwAB970948wB37B097FeJITStressABI	ailcalls_do	ailcalls_do.dll.r2rdump --val"
10:39:57.85
 "C:hwAB970948pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  tailcalls_do.dll --tailcalls --num-calls 1000 --no-ctrlc-summary 
Stressing tailcalls
OSVersion: Microsoft Windows NT 10.0.22621.0
OSArchitecture: Arm64
ProcessArchitecture: Arm64
Selecting win64 ABI
50 callers done (49 successful tailcalls tested)
100 callers done (100 successful tailcalls tested)
150 callers done (148 successful tailcalls tested)
200 callers done (197 successful tailcalls tested)
250 callers done (249 successful tailcalls tested)
300 callers done (297 successful tailcalls tested)
350 callers done (350 successful tailcalls tested)
400 callers done (399 successful tailcalls tested)
450 callers done (450 successful tailcalls tested)
500 callers done (500 successful tailcalls tested)
550 callers done (546 successful tailcalls tested)
600 callers done (597 successful tailcalls tested)
650 callers done (650 successful tailcalls tested)
700 callers done (699 successful tailcalls tested)
750 callers done (750 successful tailcalls tested)
800 callers done (799 successful tailcalls tested)
850 callers done (849 successful tailcalls tested)
900 callers done (898 successful tailcalls tested)
950 callers done (947 successful tailcalls tested)
1000 callers done (999 successful tailcalls tested)
999 tailcalls tested
  Done with 0 mismatches

cmdLine:C:hwAB970948wB37B097FeJITJIT_do../Stress/ABI/tailcalls_do/tailcalls_do.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 9/11/2024 10:39:55 AM, end: 9/11/2024 11:09:55 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> C:hwAB970948wB37B097FeJITJIT_do../Stress/ABI/tailcalls_do/tailcalls_do.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor3|0_4(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by amanasifkhalid** [comment]
I suspect this was just a sporadic infra issue. I'll watch the [newer runs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=806578&view=results) to see if it repros.

**Comment by amanasifkhalid** [comment]
This didn't fail in subsequent runs ([example](https://dev.azure.com/dnceng-public/public/_build/results?buildId=807416&view=ms.vss-test-web.build-test-results-tab), [example](https://dev.azure.com/dnceng-public/public/_build/results?buildId=807178&view=results)), so I think this was just an infra issue.
