### ISSUE TITLE
[Android][crypto] Android 7 crashes in `AsymmetricDSASignature`

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#107867]
When running `System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricDSASignature` tests on Android 7 emulators, we get the following crash:

```
08-27 18:39:54.155  2753  2771 I DOTNET  : 1) 	[FAIL] System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricDSASignature   Test name: System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricDSASignature
08-27 18:39:54.155  2753  2771 I DOTNET  :    Assembly:  [System.Security.Cryptography.Xml.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
08-27 18:39:54.155  2753  2771 I DOTNET  :    Exception messages: System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.   Exception stack traces:    at System.Security.Cryptography.DSAImplementation.DSAAndroid.SignHash(ReadOnlySpan`1 hash, Span`1 destination, Int32 signatureLength, SafeDsaHandle key)
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Security.Cryptography.DSAImplementation.DSAAndroid.CreateSignature(Byte[] rgbHash)
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Security.Cryptography.DSASignatureFormatter.CreateSignature(Byte[] rgbHash)
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Security.Cryptography.AsymmetricSignatureFormatter.CreateSignature(HashAlgorithm hash)
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Security.Cryptography.Xml.SignedXml.ComputeSignature() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 435
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricDSASignature() in /_/src/libraries/System.Security.Cryptography.Xml/tests/SignedXmlTest.cs:line 316
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
08-27 18:39:54.155  2753  2771 I DOTNET  :    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
08-27 18:39:54.155  2753  2771 I DOTNET  :    Execution time: 2.2244818
```

The exception is thrown by https://github.com/dotnet/runtime/blob/4101144c8dde177addfb93ac46425fd1a8604f7a/src/libraries/Common/src/System/Security/Cryptography/DSAAndroid.cs#L301-L304

and the probable cause:
```
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  java.security.InvalidKeyException: valueN must be 224 or 256 for valueL = 2048
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  	at com.android.org.bouncycastle.jcajce.provider.asymmetric.dsa.DSASigner.checkKey(DSASigner.java:203)
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  	at com.android.org.bouncycastle.jcajce.provider.asymmetric.dsa.DSASigner.engineInitSign(DSASigner.java:116)
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  	at java.security.Signature$Delegate.init(Signature.java:1208)
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  	at java.security.Signature$Delegate.chooseProvider(Signature.java:1167)
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  	at java.security.Signature$Delegate.engineInitSign(Signature.java:1232)
2024-08-28 19:49:31.026  5166-5187  System.err              net...curity.Cryptography.Xml.Tests  W  	at java.security.Signature.initSign(Signature.java:607)
```

Discovered in https://github.com/dotnet/runtime/pull/106951
fyi: @bartonjs @vcsjones

**Comment by vcsjones** [comment]
@bartonjs @matouskozak I took a look at this and this is a bug in Android 7 / API 24.

This was an issue in BouncyCastle https://github.com/bcgit/bc-java/commit/706c05786e28eb47aee71391d724e3b1d0a8811. When it generated DSA parameters for FIPS 186-4 it did so incorrectly. This was fixed in 2016, around the same time as Android 7 was already out.

Google pulled in the fix here https://android.googlesource.com/platform/external/bouncycastle/+/4caba4cfca3316673ae4e330e8a47932bed8a53a

This bug is fixed in Android 8 / API 26.

We _can_ work around it, but the fix is non-trivial.

Given that this issue only exists in API 24, an extremely old version of Android, and that this is for DSA, a deprecated signature algorithm, I don't really know if this is worth fixing by bringing in more complexity.

_Kevin, what is the bug and the fix?_

Older BouncyCastle, when using `KeyPairGenerator.initialize(keyBits)` when using a key-size > 1024 would do so, but it would generate DSA parameters where Q is 160-bits. This is not a good combination, Q should be 256-bit for a 2048-bit key. This API basically accepts a key size and generates one for you. However, DSA key generation is more complex than that - there are also parameters to generate, like Q. The size of these parameters can be recommended or inferred from the key size. For DSA 1024, a Q of 160-bits was used. For DSA 2048, Q has a floor of 224, but the key generator on Android 7 is creating a 2048-bit key with a Q of 160-bits.

The BouncyCastle commit fixes the generator to use appropriate parameters for a 2048-bit key (Q is 256 in this case).

The fix is to change our key pair generator for DSA to use `DSAParametersGenerator.init` which lets us control the parameter sizes of DSA and explicitly tell it we want a key L of n-bits, and a Q of n-bits, etc. This fix is only necessary for Android 7. Android 7 does support FIPS 186-4 signatures - the default key generator just created invalid parameters until Android 8 unless you take total control over the parameters when generating.

**Comment by vcsjones** [comment]
After talking about this with @bartonjs, we decided to not pursue a fix.

1. DSA is a legacy algorithm that no one should be using in 2026.
2. The issue is only present on Android 7. Android 8+ work as expected (API Level 26)
3. While Android 7 is "supported" by .NET, it is the very oldest version of Android that we still support.
4. It only happens with DSA that uses FIPS 186-3 style keys, where are even more uncommon.
5. It only impacts key generation. (Though the unit test is for signing, the problem is that DSA generated a bad key that signing later rejects).
6. No customer has raised an issue.
