### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProcessTests.TestGetProcessById

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107821]
**Failed in:** [runtime-coreclr libraries-jitstress 20240913.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=807347&view=ms.vss-test-web.build-test-results-tab&runId=20871924&resultId=138148&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.TestGetProcessById
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: ".NET Long Runni"
Actual:   "dotnet"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.TestGetProcessById() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1177
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20240917.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=810440&view=ms.vss-test-web.build-test-results-tab&runId=20976164&resultId=142066&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.TestGetProcessById
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: ".NET Long Runni"
Actual:   "dotnet"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.TestGetProcessById() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1177
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by adamsitnik** [comment]
I am going to close it in favor of #110643 which uses the new pattern matching that is recognized by Build Analysis
