### ISSUE TITLE
Test failure: System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInTOut<Single>

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#107893]
Pipeline: runtime-coreclr libraries-jitstressregs
Job: net9.0-windows-Release-arm64-jitstressregs0x1000-Windows.11.Arm64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=808889&view=ms.vss-test-web.build-test-results-tab&runId=20923354&paneView=debug&resultId=184029

This failed in JitStress, but I've seen similar failures in many different pipeline runs.

This run configuration:
```
DOTNET_JitStressRegs=0x1000
DOTNET_TieredCompilation=0
```

```
----- start Sun 09/15/2024 10:36:11.05 ===============  To repro directly: =====================================================
pushd C:\h\w\BE660A73\w\A7B3095B\e\
"C:\h\w\BE660A73\p\dotnet.exe" exec --runtimeconfig System.Numerics.Tensors.Tests.runtimeconfig.json --depsfile System.Numerics.Tensors.Tests.deps.json xunit.console.dll System.Numerics.Tensors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\BE660A73\w\A7B3095B\e>"C:\h\w\BE660A73\p\dotnet.exe" exec --runtimeconfig System.Numerics.Tensors.Tests.runtimeconfig.json --depsfile System.Numerics.Tensors.Tests.deps.json xunit.console.dll System.Numerics.Tensors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Numerics.Tensors.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Tensors.Tests (found 2438 of 4311 test cases)
  Starting:    System.Numerics.Tensors.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Numerics.Tensors.Tests.TensorSpanTests.TensorExtensionsSpanInTOut<Single>(tensorPrimitivesOperation: TensorPrimitivesSpanInTOut`1 { Method = Single Max(System.ReadOnlySpan`1[System.Single]), Target = null }, tensorOperation: TensorSpanInTOut`1 { Method = Single Max[Single](System.Numerics.Tensors.ReadOnlyTensorSpan`1[System.Single] ByRef), Target = null }) [FAIL]
      Assert.All() Failure: 1 out of 12 items in the collection did not pass.
      [11]: Item:  [1, 2, 3, 4, 5, ���]
            Error: Index was outside the bounds of the array.
      Stack Trace:
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(174,0): at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  Finished:    System.Numerics.Tensors.Tests
=== TEST EXECUTION SUMMARY ===
   System.Numerics.Tensors.Tests  Total: 4473, Errors: 0, Failed: 1, Skipped: 0, Time: 158.431s
```

@tannergooding

**Comment by BruceForstall** [comment]
More failures:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=808988&view=ms.vss-test-web.build-test-results-tab&runId=20927946&resultId=204728&paneView=debug

https://dev.azure.com/dnceng-public/public/_build/results?buildId=808988&view=ms.vss-test-web.build-test-results-tab&runId=20927948&resultId=204539&paneView=debug

**Comment by jeffhandley** [comment]
No recent reports and much of the internal implementation has been changed since this was logged. Closing.
