### ISSUE TITLE
.NET Framework DLL can't use at .NET 9 when VB.NET My.Resources Used BinaryFormatter

### ISSUE THREAD

**Issue by VB-Man** [dotnet/runtime#107967]
### Description

Due to the discontinuation of BinaryFormatter, when an image is registered as a resource in a .NET Framework project, an exception will occur when retrieving the Bitmap in My.Resources.XXXX in VB.

NET Framework DLL from a third party can no longer be used with .NET 9.
Is there a workaround?

### Reproduction Steps

No, sir.

### Expected behavior

We want to avoid a situation where third party .NET Fraework DLLs can no longer be used with .NET9. We are not referring to a specific product.

### Actual behavior

---------------------------
Microsoft.VisualBasic.Core
---------------------------
System.PlatformNotSupportedException

BinaryFormatter serialization and deserialization have been removed. See https://aka.ms/binaryformatter for more information.

   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)

   at System.Resources.ResourceReader.<>c__DisplayClass7_0`1.<CreateUntypedDelegate>b__0(Object obj, Stream stream)

   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)

   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)

   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)

   at System.Resources.ResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)

   at System.Resources.RuntimeResourceSet.ReadValue(ResourceReader reader, Int32 dataPos, Boolean isString, ResourceLocator& locator)

   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)

   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)

   at XXX.My.Resources.Resources.get_XXXXX() in C:\XXXXX\XXX\XXX\My Project\Resources.Designer.vb:line 78

**Comment by colejohnson66** [comment]
As the exception mentions, `BinaryFormatter` is removed. The URL provided says the same thing:

![image](https://github.com/user-attachments/assets/e79f086b-7071-42a7-bdde-82725ec9ab07)

If you want to use `BinaryFormatter` in .NET 9, you need to install the compatibility package: https://learn.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-migration-guide/compatibility-package

**Comment by VB-Man** [comment]
Thank you very much.
