### ISSUE TITLE
Test failure: System.Net.Quic.Tests.QuicStreamTests.TestStreams

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107969]
**Failed in:** [runtime-coreclr libraries-jitstress 20240917.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=810440&view=ms.vss-test-web.build-test-results-tab&runId=20975938&resultId=172426&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ServerReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAsync_LocalAbort_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAbortedWithoutWriting_ReadThrows
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWriteCompletionAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 761
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 796
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 553
   at System.Net.Quic.Tests.QuicStreamTests.CreateAndTestBidirectionalStream(QuicConnection c1, QuicConnection c2) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 286
   at System.Net.Quic.Tests.QuicStreamTests.TestStreams() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 276
   at System.Net.Quic.Tests.QuicStreamTests.TestStreams() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 280
   at System.Net.Quic.Tests.QuicStreamTests.TestStreams() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 280
   at System.Net.Quic.Tests.QuicStreamTests.TestStreams() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 280
--- End of stack trace from previous location ---
```

**Comment by liveans** [comment]
We started to see this kind of failures lately on Debian Arm32. I'll take a look at this when I have time, but I believe this is not an actual product issue, since the failure is happening on Arm32 + JitStress.

/cc @ManickaP

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250302.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967110&view=ms.vss-test-web.build-test-results-tab&runId=25771452&resultId=167896&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-disabler2r-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.MsQuicTests.OpenStreamAsync_BlocksUntilAvailable_PeerClosesWritingUnidirectional
    - System.Net.Quic.Tests.MsQuicTests.Read_ConnectionAbortedByUser_Throws
    - System.Net.Quic.Tests.MsQuicTests.CallDifferentWriteMethodsWorks
    - System.Net.Quic.Tests.MsQuicTests.DisposingConnection_OK
    - System.Net.Quic.Tests.MsQuicTests.Read_ConnectionAbortedByPeer_Throws
    - System.Net.Quic.Tests.MsQuicTests.QuicRootedObjectGetReleased
    - System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates
    - System.Net.Quic.Tests.QuicConnectionTests.GetStreamCapacity_SumInvariant
    - System.Net.Quic.Tests.QuicConnectionTests.Connection_AwaitsStream_ConnectionSurvivesGC
    - System.Net.Quic.Tests.QuicConnectionTests.GetStreamCapacity_OpenCloseStream_CountsCorrectly
    - System.Net.Quic.Tests.QuicConnectionTests.AcceptStreamAsync_ConnectionDisposed_Throws
    - System.Net.Quic.Tests.QuicListenerTests.TwoListenersOnSamePort_DisjointAlpn_Success
    - System.Net.Quic.Tests.QuicListenerTests.Listener_AwaitsConnection_ListenerSurvivesGC
    - System.Net.Quic.Tests.QuicListenerTests.Listener_Backlog_Success
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ClientConnects_CancelIgnored
    - System.Net.Quic.Tests.QuicListenerTests.Listener_BacklogLimitRefusesConnection_ClientThrows
    - System.Net.Quic.Tests.QuicListenerTests.Listener_AlpnNarrowingDown_Success
    - System.Net.Quic.Tests.QuicListenerTests.Listener_IPv6Any_Accepts_IPv4
    - System.Net.Quic.Tests.QuicListenerTests.Listener_Backlog_Success_IPv6
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 773
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 808
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 553
   at System.Net.Quic.Tests.MsQuicTests.OpenStreamAsync_BlocksUntilAvailable_PeerClosesWritingUnidirectional() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 867
--- End of stack trace from previous location ---
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250330.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=998489&view=ms.vss-test-web.build-test-results-tab&runId=26648728&resultId=190256&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 773
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 808
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 581
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass12_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 84
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 585
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 80
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 137
   at System.IO.Tests.ConnectedStreamConformanceTests.ArgumentValidation_ThrowsExpectedException() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1678
--- End of stack trace from previous location ---
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250426.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1027298&view=ms.vss-test-web.build-test-results-tab&runId=27550690&resultId=179534&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 773
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 808
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 553
   at System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 506
   at System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 523
   at System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 523
--- End of stack trace from previous location ---
```
