### ISSUE TITLE
[9.0][osx] Access to path denied, bad file descriptor IOException in System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#107933]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=810754
Build error leg or test failing: `System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow`

## Error Message

```json
{
  "ErrorMessage" : [
    "System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow [FAIL]",
    "Access to the path is denied",
    "Bad file descriptor"
  ],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: Unrelated deps flow PR: https://github.com/dotnet/runtime/pull/107915
- Queue: `Libraries Test Run checked coreclr osx x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=810754&view=logs&j=69b60b53-a417-56e9-d4e0-3a40344d5e67&t=5193bee0-1c28-53bc-a56d-6d396c4c4a0d&s=6884a131-87da-5381-61f3-d7acc3b91d76
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-107915-merge-13e7f2ccfab34c04b5/System.Diagnostics.Process.Tests/1/console.9a36f95f.log?helixlogtype=result
- Output:
```
   System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow [FAIL]
      System.UnauthorizedAccessException : Access to the path is denied.
      ---- System.IO.IOException : Bad file descriptor
      Stack Trace:
        /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs(468,0): at System.IO.Pipes.PipeStream.CheckPipeCall(Int32 result)
        /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs(235,0): at System.IO.Pipes.PipeStream.ValidateHandleIsPipe(SafePipeHandle safePipeHandle)
        /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeClientStream.cs(67,0): at System.IO.Pipes.AnonymousPipeClientStream.Init(PipeDirection direction, SafePipeHandle safePipeHandle)
        /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeClientStream.cs(60,0): at System.IO.Pipes.AnonymousPipeClientStream..ctor(PipeDirection direction, SafePipeHandle safePipeHandle)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(849,0): at System.Diagnostics.Process.OpenStream(Int32 fd, PipeDirection direction)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(476,0): at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1284,0): at System.Diagnostics.Process.Start()
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(1601,0): at System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(48,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250202.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=937922&view=ms.vss-test-web.build-test-results-tab&runId=24879392&resultId=154122&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress1_tiered-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow
```

**Error message:**
```
 System.UnauthorizedAccessException : Access to the path is denied.
---- System.IO.IOException : Bad file descriptor
```

**Stack trace:**
```
   at System.IO.Pipes.PipeStream.ValidateHandleIsPipe(SafePipeHandle safePipeHandle) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 235
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 476
   at System.Diagnostics.Process.Start() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1284
   at System.Diagnostics.Tests.ProcessTests.Start_RedirectStandardOutput_StartAgain_DoesntThrow() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1601
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs:line 1159
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 48
----- Inner Stack Trace -----

```
