### ISSUE TITLE
DSAOpenSsl doest suuport in SslStreamCertificateContext

### ISSUE THREAD

**Issue by SwimUp** [dotnet/runtime#107977]
### Description

Hello. I'm trying using TLS/SSL connection via FluentFTP, he is using SslStreamCertificateContext, with pfx certificate on Linux, Ubuntu.
NET 8.0

But i get error "The server mode SSL must use a certificate with the associated private key."
```
 The server mode SSL must use a certificate with the associated  private key.
   at System.Net.Security.SslStreamCertificateContext..ctor(X509Certificate2 target, ReadOnlyColle ction`1 intermediates, SslCertificateTrust trust)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certific ate2Collection additionalCertificates, Boolean offline, SslCertificateTrust trust, Boolean noOcspF etch)
   at System.Net.Security.SslStream.AcquireClientCredentials(Byte[]& thumbPrint, Boolean newCreden tialsRequested)
   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer, ProtocolToken& toke n)
   at System.Net.Security.SslStream.ProcessTlsFrame(Int32 frameSize, ProtocolToken& message)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byt e[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientA uthenticationOptions)
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targetHost, X509CertificateCollection cl ientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect(Boolean reConnect)
   at FluentFTP.FtpClient.Connect()


```

After some investigation i realized SslStreamCertificateContext doest support DSAOpenSsl

Loading pfx and debuggings:
```
var certificate = new X509Certificate2(Settings.Settings["require"]["certPath"], Settings.Settings["require"]["password"]);

Console.WriteLine($"certificate HasPrivateKey: {certificate.HasPrivateKey}");
Console.WriteLine($"certificate PrivateKey: {certificate.PrivateKey}");
Console.WriteLine($"certificate GetRSAPrivateKey: {certificate.GetRSAPrivateKey()}");
Console.WriteLine($"certificate GetDSAPrivateKey: {certificate.GetDSAPrivateKey()}");
Console.WriteLine($"certificate GetECDsaPrivateKey: {certificate.GetECDsaPrivateKey()}");

certificate HasPrivateKey: True
certificate PrivateKey: System.Security.Cryptography.DSAOpenSsl
certificate GetRSAPrivateKey:
certificate GetDSAPrivateKey: System.Security.Cryptography.DSAOpenSsl
certificate GetECDsaPrivateKey:
```

### Reproduction Steps

```
I'm using FluentFTP 

FtpConfig ftpConfig = new FtpConfig()
{
    EncryptionMode = FtpEncryptionMode.Auto,
    DataConnectionType = FtpDataConnectionType.PASV,
    ReadTimeout = (int)TimeSpan.FromMinutes(30).TotalMilliseconds,
    ConnectTimeout = (int)TimeSpan.FromMinutes(30).TotalMilliseconds,
    LogToConsole = true,
    ValidateAnyCertificate = true,
    SslProtocols = System.Security.Authentication.SslProtocols.Tls12,
};

//Certficate with DSA
 var certificate = new X509Certificate2(cert, pass);

ftpConfig.ClientCertificates.Add(certificate);

FtpClient ftpClient = new FtpClient(host, username, password, port, ftpConfig);

ftpClient.Connect();
```

### Expected behavior

SslStreamCertificateContext working with DSAOpenSsl private key

### Actual behavior

SslStreamCertificateContext thrown error with DSAOpenSsl private key

**Comment by vcsjones** [comment]
In general, you are correct, `SslStreamCertificateContext` does not support DSA. It tries RSA and ECDSA here, and if neither work, reports no private key.

https://github.com/dotnet/runtime/blob/69851f204995553f8540b55355b7598c830427c7/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.Linux.cs#L78-L88


In general though, is there a reason you need to use DSA? DSA is a very old, deprecated algorithm, where ECDSA or RSA are preferred.

**Comment by SwimUp** [comment]
> In general, you are correct, `SslStreamCertificateContext` does not support DSA on Linux. It tries RSA and ECDSA here, and if neither work, reports no private key.
> 
> https://github.com/dotnet/runtime/blob/69851f204995553f8540b55355b7598c830427c7/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.Linux.cs#L78-L88
> 
> In general though, is there a reason you need to use DSA? DSA is a very old, deprecated algorithm, where ECDSA or RSA are preferred.

Thanks for answer! I think you are right and I should request a reissue of the certificate.
