### ISSUE TITLE
[Fuzzing] AssemblyNameInfoFuzzer: CultureNotFoundException: Culture is not supported

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#107949]
```
System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
aaaA is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Reflection.AssemblyName.set_CultureName(String value)
   at System.Reflection.Metadata.AssemblyNameInfo.ToAssemblyName()
   at DotnetFuzzing.Fuzzers.AssemblyNameInfoFuzzer.Test(Span`1 span) in D:\a\_work\1\s\src\libraries\Fuzzing\DotnetFuzzing\Fuzzers\AssemblyNameInfoFuzzer.cs:line 44
   at DotnetFuzzing.Fuzzers.AssemblyNameInfoFuzzer.FuzzTarget(ReadOnlySpan`1 bytes) in D:\a\_work\1\s\src\libraries\Fuzzing\DotnetFuzzing\Fuzzers\AssemblyNameInfoFuzzer.cs:line 27
   at DotnetFuzzing.Program.<>c__DisplayClass1_0.b__0(ReadOnlySpan`1 bytes) in D:\a\_work\1\s\src\libraries\Fuzzing\DotnetFuzzing\Program.cs:line 91
   at SharpFuzz.Fuzzer.LibFuzzer.Run(ReadOnlySpanAction action, Boolean ignoreExceptions)
```

Input: `sibP,culture=aaaA`

cc: @adamsitnik @buyaa-n

**Comment by adamsitnik** [comment]
We just need to make sure this scenario is recognized properly (all unexpected exceptions are treated as bugs)

**Comment by ericstj** [comment]
I see, so you need to add a catch here to indicate you expect a CultureNotFoundException:
https://github.com/dotnet/runtime/blob/d6094d218c74e0cc496a7bceeda016a3b34b1967/src/libraries/Fuzzing/DotnetFuzzing/Fuzzers/AssemblyNameInfoFuzzer.cs#L60
