### ISSUE TITLE
[9.0] Strings differ assert in System.Text.Tests.EncodingExtensionsTests.Convert_Decoder_ReadOnlySpan_IBufferWriter

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#108005]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=811970
Build error leg or test failing: osx-x64 Debug Mono_MiniJIT_LibrariesTests

## Error Message

```json
{
  "ErrorMessage" : [
    "System.Text.Tests.EncodingExtensionsTests.Convert_Decoder_ReadOnlySpan_IBufferWriter [FAIL]",
    "Strings differ"
  ],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- Unrelated 9.0 PR: https://github.com/dotnet/runtime/pull/107983
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=811970&view=logs&j=07e4961f-4232-5b4a-5e6a-31092474840f
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-107983-merge-e9603399f33e432fa5/System.Memory.Tests/1/console.85730821.log?helixlogtype=result
- Output:
```
===========================================================================================================
/private/tmp/helix/working/A7850979/w/AA9A0959/e /private/tmp/helix/working/A7850979/w/AA9A0959/e
  Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Memory.Tests (found 2795 of 2827 test cases)
  Starting:    System.Memory.Tests (parallel test collections = on [12 threads], stop on fail = off)
    System.Text.Tests.EncodingExtensionsTests.Convert_Decoder_ReadOnlySpan_IBufferWriter [FAIL]
      Assert.Equal() Failure: Strings differ
                                        ↓ (pos 449122)
      Expected: ···"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"···
      Actual:   ···"xxxxxxxxxxxxxxxxxxxxzxxxxxxxxxxxxxxxxxxxx"···
                                        ↑ (pos 449122)
      Stack Trace:
        /_/src/libraries/System.Memory/tests/EncodingExtensions/EncodingExtensionsTests.cs(98,0): at System.Text.Tests.EncodingExtensionsTests.Convert_Decoder_ReadOnlySpan_IBufferWriter()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
    System.Memory.Tests.Span.StringSearchValuesTests.TestIndexOfAny_RandomInputs_Nls [SKIP]
      Condition(s) not met: "CanTestNls"
  Finished:    System.Memory.Tests
=== TEST EXECUTION SUMMARY ===
   System.Memory.Tests  Total: 51533, Errors: 0, Failed: 1, Skipped: 1, Time: 39.461s
/private/tmp/helix/working/A7850979/w/AA9A0959/e
----- end Wed Sep 18 09:43:02 EDT 2024 ----- exit code 1 ----------------------------------------------------------
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=811970
**Error message validated:** `[System.Text.Tests.EncodingExtensionsTests.Convert_Decoder_ReadOnlySpan_IBufferWriter [FAIL] Strings differ`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/19/2024 1:52:19 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by PranavSenthilnathan** [comment]
Nothing looks obviously wrong in the code that would cause this error. Hit count is 0, so closing for now.
