### ISSUE TITLE
Access Violation in CastHelpers.IsInstanceOfInterface

### ISSUE THREAD

**Issue by peterchase** [dotnet/runtime#108052]
### Description

Our .Net application experiences an intermittent fatal AccessViolationException. It is a plain managed code .Net application and hence cannot directly cause such an exception.

The crash seems to occur in a TPL Task scheduler that we have implemented. This is still ordinary managed code, however.

### Reproduction Steps

Unfortunately we have not been able to identify a small reproduction case.

### Expected behavior

No Access Violation

### Actual behavior

Application: REDACTED
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
at System.Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface(Void*, System.Object)
at System.Threading.Tasks.Task.RunContinuations(System.Object)
at System.Threading.Tasks.Task.FinishSlow(Boolean)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at REDACTED

Faulting application name: REDACTED, time stamp: 0x66960000
Faulting module name: coreclr.dll, version: 8.0.824.36612, time stamp: 0x6696b815
Exception code: 0xc0000005
Fault offset: 0x00000000001c2090
Faulting process id: 0x23b8
Faulting application start time: 0x01db03174ba027e7
Faulting application path: REDACTED
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.8\coreclr.dll
Report Id: cab987fc-5e3c-4a59-aa25-75c80d0fb0ed
Faulting package full name:
Faulting package-relative application ID:

### Regression?

Also occurring with 8.0.7. Unsure about earlier versions.

### Configuration

.Net 8.0.8 (also seen in 8.0.7)
.Net SDK 8.0.401 

Seen on:
Windows 11, version 10.0
Windows Server 2022, version 10.0
Windows Server 2019, version 10.0

**Comment by mangod9** [comment]
Not much we can investigate without a repro or dumps. Is this still an issue on latest servicing releases?

**Comment by thrytsak** [comment]
We hit this same crash signature repeatedly in production and have now captured **two full crash dumps** of it. The dumps contain credentials/payloads from our environment and stay internal, but the analysis below explains the mechanism, and we're happy to run additional commands against the dumps and post the outputs.

## Environment

- .NET 8.0.29 and 8.0.30 (`mcr.microsoft.com/dotnet/aspnet:8.0.30`, Debian 12), linux-x64, Kubernetes
- Workstation concurrent GC, `processorCount = 1` (cgroup cpu limit 400m), heap hard limit 750 MB, managed heap only ~20–60 MB
- **No third-party native libraries** (verified from `/proc/self/maps`: only glibc/ICU/OpenSSL/hostfxr), no unsafe code, no profilers/APM
- 6 crashes with a frame-identical stack over ~4 weeks in one environment; always seconds after a request burst, during near-idle connection teardown. The identical image runs crash-free in environments with different traffic patterns.

## Crash stack (identical every time)

```
Fatal error. System.AccessViolationException
   at System.Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface(Void*, System.Object)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.ConnectionManager.RemoveConnection(Int64)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportConnectionManager.RemoveConnection(Int64)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1+<ExecuteAsync>d__8.MoveNext()
   ... (continuation cascade from SocketConnection.DisposeAsync / DoReceive)
```

## Dump analysis

Faulting frame:

```
System.Threading.Tasks.Task.RunContinuations(System.Object)
    this               = 0x00007efd3188a028
    continuationObject = 0x00007efe33cca688
```

`this` does **not** point at a Task. It points into the middle of a pristine, freshly allocated
HTML-DOM object graph (AngleSharp, via HtmlSanitizer — our middleware parses request bodies, so
these are the dominant gen0 allocations of the last request, which completed ~5s before the crash):

```
> dumpobj 0x7efd3188a028
Name: System.Collections.Generic.List`1[[AngleSharp.Dom.Node]]   Size: 32
```

`this + 0x20` (Task.m_continuationObject slot) = `0x7efd3188a048` — which is the **MethodTable slot
of the neighbouring `NamedNodeMap` object** (still referenced by `HtmlBodyElement._attributes`).
Completing the stale "Task" did its `Interlocked.Exchange` there:

- at `0x7efd3188a048` now: `0x7efd2bc30d00` → a bare 24-byte `System.Object` in gen2 — i.e.
  `Task.s_taskCompletionSentinel`, stamped over the NamedNodeMap's MT by `FinishContinuations`
- the exchanged-out **old** value, passed to `RunContinuations` as the "continuation", is
  `0x7efe33cca688` = the **MethodTable of `AngleSharp.Dom.NamedNodeMap`**
- `IsInstanceOfInterface` then dereferences that MT pointer's first qword
  (`0x0000002001000000` = MT flags + BaseSize 0x20) as if it were a MethodTable → AV

`verifyheap` over 688,436 objects reports **exactly 2 errors, both at this seam**, and both are
collateral of the crash write itself:

```
7efd31889f50  InvalidObjectReference  bad member at offset 40: 7efd3188a048  (HtmlBodyElement._attributes)
7efd3188a048  InvalidMethodTable      invalid method table 7efd2bc30d00      (sentinel over the MT slot)
```

```
> listnearobj 0x7efd3188a048
Before: 7efd3188a028  32  List<AngleSharp.Dom.Node>
Current: 7efd3188a048  Unknown (invalid MT 7efd2bc30d00)
Next:   7efd3188a068  32  List<AngleSharp.Dom.Attr>
```

## Interpretation

A Task on the Kestrel connection-teardown path was **collected (or relocated without this root
being updated) while still reachable**, its gen0 memory was reused by ordinary allocations, and the
teardown then completed the stale reference on top of the new objects. With no unsafe or native
code in the process, this looks like a GC liveness/relocation issue — possibly sensitive to
`processorCount = 1` and to the burst→idle timing (the 30s window before the crash included gen2 +
gen1 + several gen0 collections).

The diagnostics in the earlier reports here never got past the symptom because the corruption is
planted milliseconds before the crash — logs can't see it; only the dump can.
