### ISSUE TITLE
try again to match Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#108107]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=814594
Build error leg or test failing: Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations
Pull request: https://github.com/dotnet/runtime/pull/108094

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by lewing** [comment]
![image](https://github.com/user-attachments/assets/71a34ead-6722-4629-aa69-2ff19b7c8000)

**Comment by lewing** [comment]
this should match the same failures as https://github.com/dotnet/runtime/issues/108107 and https://github.com/dotnet/runtime/issues/108107 and https://github.com/dotnet/runtime/issues/108074

**Comment by lewing** [comment]
some of the hits #107639 #108033

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-108165-merge-3ec91e6d4051475080/Workloads-ST-Wasm.Build.Tests.WasmTemplateTests/1/console.1d81a857.log?skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2024-09-24T08%3A33%3A36Z&ske=2024-09-24T09%3A33%3A36Z&sks=b&skv=2024-05-04&sv=2024-05-04&st=2024-09-24T08%3A33%3A36Z&se=2024-09-24T09%3A33%3A36Z&sr=c&sp=r&sig=5Dclau%2F0ZWqcMONP3qoWifI8W3haKizPq0zcvCcdDHc%3D)
```
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "") [FAIL]
      System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "http://localhost:5052/", waiting until "load"
============================================================
      Stack Trace:
        /_/src/Playwright/Transport/Connection.cs(164,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args)
        /_/src/Playwright/Transport/Connection.cs(475,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
        /_/src/Playwright/Core/Frame.cs(539,0): at Microsoft.Playwright.Core.Frame.GotoAsync(String url, FrameGotoOptions options)
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(188,0): at Wasm.Build.Tests.BrowserRunner.RunAsync(IBrowserContext context, String browserUrl, Boolean headless, Action`2 onConsoleMessage, Action`1 onError, Func`2 modifyBrowserUrl, Boolean resetExitedState)
        /_/src/mono/wasm/Wasm.Build.Tests/BrowserRunner.cs(157,0): at Wasm.Build.Tests.BrowserRunner.RunAsync(ToolCommand cmd, String args, Boolean headless, Action`2 onConsoleMessage, Action`1 onServerMessage, Action`1 onError, Func`2 modifyBrowserUrl)
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(333,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(335,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/mono/wasm/Wasm.Build.Tests/Templates/WasmTemplateTests.cs(301,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
```

**Comment by pavelsavara** [comment]
I guess this is good to be closed now ?
