### ISSUE TITLE
Works in debug and exception in release mode with Sql Server SMO in IOS & Android

### ISSUE THREAD

**Issue by last-Programmer** [dotnet/runtime#108160]
### Description

I am using Sql Server SMO nuget package with .net MAUI and when i use Microsoft.SqlServer.Management.Smo.Table.Script to script a table it throws up exception  like this

Script failed for Table 'dbo.Test'. 
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl()
   at Microsoft.SqlServer.Management.Smo.TableViewTableTypeBase.Script()
   at MakeProg.Wrapper.Sql.Table.GetScript(String table, String schema, String database)
TypeInitialization_Type, Microsoft.SqlServer.Management.Smo.TypeConverters
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImplWorker(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
Arg_TargetInvocationException
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(Type objectType, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance, Boolean verifyIsRegisteredType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type, Object instance)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.SmoManagementUtil.GetTypeConverter(Type t)
   at Microsoft.SqlServer.Management.Smo.TypeConverters..cctor()
EnumInvalidValue
   at System.ComponentModel.EnumConverter..ctor(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.LocalizableEnumConverter..ctor(Type type)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

### Steps to Reproduce

Create a new .net maui app and install Sql Server SMO nuget package and connect to sql server and try to script a table using Microsoft.SqlServer.Management.Smo.Table.Script and run in android or IOS simulator in relase mode and you can see that it threws up exception. This was not happening in .net 8. i upgraded my project to .net9 and .net 9 maui rc and this started happening.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.90 SR9

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

No As Such

### Relevant log output

```shell
Script failed for Table 'dbo.Test'. 
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl()
   at Microsoft.SqlServer.Management.Smo.TableViewTableTypeBase.Script()
   at MakeProg.Wrapper.Sql.Table.GetScript(String table, String schema, String database)
TypeInitialization_Type, Microsoft.SqlServer.Management.Smo.TypeConverters
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImplWorker(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
Arg_TargetInvocationException
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(Type objectType, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance, Boolean verifyIsRegisteredType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type, Object instance)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.SmoManagementUtil.GetTypeConverter(Type t)
   at Microsoft.SqlServer.Management.Smo.TypeConverters..cctor()
EnumInvalidValue
   at System.ComponentModel.EnumConverter..ctor(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.LocalizableEnumConverter..ctor(Type type)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by ericstj** [comment]
I'm guessing Type information is missing for the target type here.  @LakshanF seems you [added](https://github.com/dotnet/runtime/commit/afbebfe01026d9fc719f85a28d6e15da09150adc) this exception: 
https://github.com/dotnet/runtime/blob/b5833d2cd22f474485f74696609f6a6c3617cd15/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/EnumConverter.cs#L26-L29

The Sql type is here: https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Sdk/Sfc/LocalizableTypeConverter.cs#L1636

Here are the various types it's trying to register:
https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/ConnectionInfo/ConnectionEnums.cs#L348-L352
https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Smo/ScriptingOptions.cs#L149-L152

cc @shueybubbles

**Comment by ericstj** [comment]
You might be able to workaround this by rooting the type information for:
- `Microsoft.SqlServer.Management.Smo.SqlServerVersion`

I think that's the enum that's causing the failure here.

**Comment by last-Programmer** [comment]
@ericstj Thank you for you time to take a look into this. I am novice here in linking related stuff. What shoud i do in code to root that type infomration. i really dont know what is rooting.

**Comment by last-Programmer** [comment]
@ericstj I tried rooting the assembly itself by adding this to csproj

```
    <ItemGroup>
        <TrimmerRootAssembly  Include="Microsoft.SqlServer.Smo" RootMode="library"/>
    </ItemGroup>
```

and it does not help. it throws up the same exception in ios & android in release mode.

**Comment by last-Programmer** [comment]
> Where the two workarounds are:
> 
> * `<TrimmerRootAssembly Include="Microsoft.SqlServer.Smo" />`
> * `<PublishTrimmed>false</PublishTrimmed>`

I tried both work arounds with release config and it does not work. in IOS using UseIntrepreter solves the problem in release mode. in android the problem reamains even after the workaround. But with .net 8 i did not had this problem when running the app in release config in ios and android simulator/device.

**Comment by LakshanF** [comment]
> I'm guessing Type information is missing for the target type here. @LakshanF seems you [added](https://github.com/dotnet/runtime/commit/afbebfe01026d9fc719f85a28d6e15da09150adc) this exception:
> 
> https://github.com/dotnet/runtime/blob/b5833d2cd22f474485f74696609f6a6c3617cd15/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/EnumConverter.cs#L26-L29
> 
> The Sql type is here: https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Sdk/Sfc/LocalizableTypeConverter.cs#L1636
> 
> Here are the various types it's trying to register: https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/ConnectionInfo/ConnectionEnums.cs#L348-L352 https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Smo/ScriptingOptions.cs#L149-L152
> 
> cc @shueybubbles

The types trying to register listed above all seem `enum` types and shouldn't cause the exception in the [EnumConverter](https://github.com/dotnet/runtime/blob/3c0dc6368dc140910a4f7fbb9abb5a39b3e16b76/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/EnumConverter.cs#L26).

https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Smo/ScriptingOptions.cs#L125
https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/ConnectionInfo/ConnectionEnums.cs#L77
https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/ConnectionInfo/ConnectionEnums.cs#L59

Is it possible to find a `non-enum` type that is getting passed to be registered from the repro?

**Comment by ericstj** [comment]
@LakshanF and I looked at this and we think we spotted the bug:
https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Sdk/Sfc/LocalizableTypeConverter.cs#L1636-L1637
```c#
        public LocalizableEnumConverter(System.Type type)
            : base(type.GetType())
```

That's passing down `System.Type.GetType()` rather than just `type`.  That's why the `IsEnum` check is failing.  Not sure why this is only hitting in release (perhaps the library or application has a different codepath in release vs debug) but that seems to be a bug in `Microsoft.SqlServer.Smo`.  It looks to me like it got away with this bug because it captures it's own copy of `type` effectively on construction in it's dictionary https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/Sdk/Sfc/LocalizableTypeConverter.cs#L1588.

The same bug appears to be in the following derived EnumConverter as well.
https://github.com/microsoft/sqlmanagementobjects/blob/f185f0170573aa1c8ae9fb59eaa4ad602e9de95f/src/Microsoft/SqlServer/Management/ConnectionInfo/LocalizableTypeConverter.cs#L648-L649

I filed https://github.com/dotnet/runtime/issues/108200 to track adding an analyzer to catch this mistake.

I've marked https://github.com/dotnet/runtime/pull/100347 as breaking to document this change.   @last-Programmer I'm not seeing a good workaround here.

@shueybubbles can you help me transfer this issue to https://github.com/microsoft/sqlmanagementobjects?

**Comment by ericstj** [comment]
Resolving this as fixed, since SqlManagementObjects took the fix and we'll update the breaking change docs to highlight this.

**Comment by last-Programmer** [comment]
@ericstj thank you very much for the fix. waiting to test it n my maui application.

**Comment by last-Programmer** [comment]
I tried building from the source and not it works ok in ios/android release config.
