### ISSUE TITLE
Test failure: JIT/superpmi/superpmicollect/superpmicollect.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#108123]
**Failed in:** [runtime-coreclr jitstress-random 20240922.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815228&view=ms.vss-test-web.build-test-results-tab&runId=21131596&resultId=123342&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - JIT/superpmi/superpmicollect/superpmicollect.cmd
```

**Error message:**
```
 
cmdLine:C:hwB78D0A37wA79108A9eJITJIT_others../superpmi/superpmicollect/superpmicollect.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 9/22/2024 7:59:20 PM, end: 9/22/2024 8:29:20 PM)

Return code:      -100
Raw output file:      C:hwB78D0A37wA79108A9uploadssuperpmisuperpmicollectoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB78D0A37pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  superpmicollect.dll 
SuperPMI collection and playback - BEGIN
Setting environment variables:
    SuperPMIShimLogPath=C:hwB78D0A37	1atlbklh.gchSPMI
    SuperPMIShimPath=C:hwB78D0A37pclrjit.dll
    DOTNET_JitName=superpmi-shim-collector.dll
Running: C:Windowssystem32cmd.exe /c C:hwB78D0A37wA79108A9eJITsuperpmisuperpmicollectBytemarkBytemark.cmd
BEGIN EXECUTION
 "C:hwB78D0A37pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Bytemark.dll 
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 2139.62655  Index: 54.87207
NUMERIC SORT(rectangle):  Iterations/sec: 680.16086  Index: 17.44315
STRING SORT:  Iterations/sec: 8645.70758  Index: 3863.14012
BITFIELD:  Iterations/sec: 446875301.34208  Index: 76.65489
FP EMULATION(struct):  Iterations/sec: 148.09782  Index: 71.06422
FP EMULATION(class):  Iterations/sec: 163.20000  Index: 78.31094
FOURIER:  Iterations/sec: 16566.35276  Index: 18.84086
ASSIGNMENT(jagged):  Iterations/sec: 35.26411  Index: 134.18612
ASSIGNMENT(rectangle):  Iterations/sec: 28.05493  Index: 106.75391
IDEA:  Iterations/sec: 3174.75669  Index: 48.55704
HUFFMAN:  Iterations/sec: 3360.23951  Index: 93.17951
NEURAL NET(jagged):  Iterations/sec: 22.85512  Index: 36.71505
NEURAL NET(rectangle):  Iterations/sec: 11.32852  Index: 18.19843
LU DECOMPOSITION:  Iterations/sec: 1870.70964  Index: 96.91239
===========OVERALL============
INTEGER INDEX: 100.22116
FLOATING-POINT INDEX: 33.23453
 (90 MHz Dell Pentium = 1.00)
==============================
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Running: C:Windowssystem32cmd.exe /c C:hwB78D0A37wA79108A9eJITsuperpmisuperpmicollectCscBenchCscBench.cmd
BEGIN EXECUTION
 "C:hwB78D0A37pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CscBench.dll 
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Running: C:Windowssystem32cmd.exe /c C:hwB78D0A37wA79108A9eJITsuperpmisuperpmicollect\xprecise1_cs_do\xprecise1_cs_do.cmd
BEGIN EXECUTION
 "C:hwB78D0A37pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  xprecise1_cs_do.dll 
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Running: C:hwB78D0A37pmcs.exe -merge C:hwB78D0A37	1atlbklh.gchSPMIase.mch C:hwB78D0A37	1atlbklh.gchSPMI*.mc -recursive -dedup -thin
Merging files matching 'C:hwB78D0A37	1atlbklh.gchSPMI*.mc' into 'C:hwB78D0A37	1atlbklh.gchSPMIase.mch'
Appending file 'C:hwB78D0A37	1atlbklh.gchSPMI C__h_w_B78D0A37_p_corerun_exe __-p_ System_Reflection_Metadata_MetadataUpdater_IsSupported_false _-p_ System_Runtime_Serialization_EnableUnsafeBinaryFormatterSeria745C9DE8.mc'
Loaded 179, Saved 175
Appending file 'C:hwB78D0A37	1atlbklh.gchSPMI C__h_w_B78D0A37_p_corerun_exe __-p_ System_Reflection_Metadata_MetadataUpdater_IsSupported_false _-p_ System_Runtime_Serialization_EnableUnsafeBinaryFormatterSeriaB7CAEC7D.mc'
Loaded 1000 at 5305 per second
Loaded 2000 at 4847 per second
Loaded 3000 at 4589 per second
Loaded 4000 at
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor11|0_12(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-06-23T05:27:24.098Z | runtime-coreclr jitstress | Checked-jitstress2 | windows.11.arm64.open | arm64 | JIT/superpmi/superpmicollect/superpmicollect.cmd | Failed | {"System.JobId":"63f2a02a-7891-5505-e9da-45b13105e16b","Project":"public","BuildId":"717159","configuration":"Checked-jitstress2","AzurePipelinesTestRunId":"17958280","System.StageName":"Build","DefinitionName":"runtime-coreclr   jitstress","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Windows.11.Arm64.Open","System.StageAttempt":"1","architecture":"arm64","Reason":"Schedule","System.PhaseAttempt":"1","System.JobName":"__default","BuildNumber":"20240622.1","DefinitionId":"109","System.JobAttempt":"1","System.PhaseName":"run_test_p1__windows_arm64_checked"} | Schedule

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240922.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815348&view=ms.vss-test-web.build-test-results-tab&runId=21136684&resultId=121972&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
    - JIT/superpmi/superpmicollect/superpmicollect.cmd
```

**Error message:**
```
 
cmdLine:C:hwADC40958wB9740A16eJITJIT_others../superpmi/superpmicollect/superpmicollect.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 9/23/2024 6:02:53 AM, end: 9/23/2024 6:32:53 AM)

Return code:      -100
Raw output file:      C:hwADC40958wB9740A16uploadssuperpmisuperpmicollectoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwADC40958pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  superpmicollect.dll 
SuperPMI collection and playback - BEGIN
Setting environment variables:
    SuperPMIShimLogPath=C:hwADC40958	yv1ifr52.4jnSPMI
    SuperPMIShimPath=C:hwADC40958pclrjit.dll
    DOTNET_JitName=superpmi-shim-collector.dll
Running: C:Windowssystem32cmd.exe /c C:hwADC40958wB9740A16eJITsuperpmisuperpmicollectBytemarkBytemark.cmd
BEGIN EXECUTION
 "C:hwADC40958pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Bytemark.dll 
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 990.97264  Index: 25.41412
NUMERIC SORT(rectangle):  Iterations/sec: 861.67568  Index: 22.09821
STRING SORT:  Iterations/sec: 8696.18580  Index: 3885.69517
BITFIELD:  Iterations/sec: 372227095.58199  Index: 63.85008
FP EMULATION(struct):  Iterations/sec: 197.60000  Index: 94.81766
FP EMULATION(class):  Iterations/sec: 224.20000  Index: 107.58157
FOURIER:  Iterations/sec: 16208.44623  Index: 18.43381
ASSIGNMENT(jagged):  Iterations/sec: 39.68031  Index: 150.99054
ASSIGNMENT(rectangle):  Iterations/sec: 26.42802  Index: 100.56325
IDEA:  Iterations/sec: 2363.35570  Index: 36.14689
HUFFMAN:  Iterations/sec: 2960.09466  Index: 82.08349
NEURAL NET(jagged):  Iterations/sec: 22.43333  Index: 36.03748
NEURAL NET(rectangle):  Iterations/sec: 6.63006  Index: 10.65069
LU DECOMPOSITION:  Iterations/sec: 711.36617  Index: 36.85243
===========OVERALL============
INTEGER INDEX: 95.64021
FLOATING-POINT INDEX: 22.59714
 (90 MHz Dell Pentium = 1.00)
==============================
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Running: C:Windowssystem32cmd.exe /c C:hwADC40958wB9740A16eJITsuperpmisuperpmicollectCscBenchCscBench.cmd
BEGIN EXECUTION
 "C:hwADC40958pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CscBench.dll 
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Running: C:Windowssystem32cmd.exe /c C:hwADC40958wB9740A16eJITsuperpmisuperpmicollect\xprecise1_cs_do\xprecise1_cs_do.cmd
BEGIN EXECUTION
 "C:hwADC40958pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  xprecise1_cs_do.dll 
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
Running: C:hwADC40958pmcs.exe -merge C:hwADC40958	yv1ifr52.4jnSPMIase.mch C:hwADC40958	yv1ifr52.4jnSPMI*.mc -recursive -dedup -thin
Merging files matching 'C:hwADC40958	yv1ifr52.4jnSPMI*.mc' into 'C:hwADC40958	yv1ifr52.4jnSPMIase.mch'
Appending file 'C:hwADC40958	yv1ifr52.4jnSPMI C__h_w_ADC40958_p_corerun_exe __-p_ System_Reflection_Metadata_MetadataUpdater_IsSupported_false _-p_ System_Runtime_Serialization_EnableUnsafeBinaryFormatterSeria13DE60A8.mc'
Loaded 1000 at 8104 per second
Loaded 2000 at 9559 per second
Loaded 3000 at 9793 per second
Loaded 4000 at 7725 per second
Loaded 5000 at 8808 per second
Loaded 6000 at 9391 per second
Loaded 7000 at 8928 per second
Loaded 8000 at 8449 per second
Loaded 9000 at 9907 per second
Loaded 10000 at 9683 per second
Loaded 11000 at 9579 per second
Loaded 1200
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor11|0_12(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by BruceForstall** [comment]
This succeeded after fixing a recent regression: https://dev.azure.com/dnceng-public/public/_build/results?buildId=816469&view=results
