### ISSUE TITLE
Test failure: Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process. Memory load: 12

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#108210]
Pipeline: runtime-coreclr libraries-jitstress
Job: net9.0-windows-Release-x86-jitstress2_tiered-Windows.10.Amd64.Open
Test: System.Tests.PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds

```
    System.Tests.PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
      Memory load: 12
      
      Image Name                     PID Services                                    
      ========================= ======== ============================================
      svchost.exe                    764 BrokerInfrastructure, DcomLaunch, LSM,      
                                         PlugPlay, Power, SystemEventsBroker         
      svchost.exe                    824 RpcEptMapper, RpcSs                         
      svchost.exe                    932 TermService                                 
      svchost.exe                    944 Appinfo, CertPropSvc, DsmSvc, gpsvc,        
                                         iphlpsvc, ProfSvc, sacsvr, Schedule, SENS,  
                                         SessionEnv, ShellHWDetection, Themes,       
                                         UserManager, Winmgmt, wlidsvc, WpnService,  
                                         wuauserv                                    
      svchost.exe                    992 Dhcp, EventLog, lmhosts, NgcCtnrSvc,        
                                         TimeBrokerSvc, vmictimesync                 
      svchost.exe                    320 NcbService, PcaSvc, TrkWks, UmRdpService,   
                                         vmickvpexchange, vmicshutdown               
      svchost.exe                    532 CDPSvc, EventSystem, FontCache, netprofm,   
                                         nsi, RemoteRegistry, W32Time,               
                                         WinHttpAutoProxySvc                         
      svchost.exe                   1084 CryptSvc, Dnscache, LanmanWorkstation,      
                                         NlaSvc, WinRM                               
      svchost.exe                   1132 vmicheartbeat                               
      svchost.exe                   1344 BFE, CoreMessagingRegistrar, DPS, MpsSvc,   
                                         pla                                         
      svchost.exe                   1592 Wcmsvc                                      
      svchost.exe                   2020 W3SVC, WAS                                  
      svchost.exe                   2028 DiagTrack                                   
      svchost.exe                   2044 StateRepository, tiledatamodelsvc           
      svchost.exe                   1336 AppHostSvc                                  
      svchost.exe                   2156 LanmanServer                                
      svchost.exe                   3308 CDPUserSvc_47c64, OneSyncSvc_47c64          
      svchost.exe                   3736 AppReadiness                                
      svchost.exe                   3796 AppXSvc, ClipSVC                            
      Timed out at 9/24/2024 5:26:10 PM after 60000ms waiting for remote process.
      Wrote mini dump to: C:\h\w\BEFC0A33\w\A6F80974\uploads\5112.xvfhk42o.y5p.dmp
      	Process ID: 5112
      	Handle: 1136
      	Name: dotnet
      	MainModule: C:\h\w\BEFC0A33\p\dotnet.exe
      	StartTime: 9/24/2024 5:25:09 PM
      	TotalProcessorTime: 00:00:02.8281250
      	Threads:
      		Thread #1 (OS 0x71C)   [MTA]
      			[InlinedCallFrame]
      			ILStubClass.IL_STUB_PInvoke()
      			[InlinedCallFrame]
      			System.Tests.PosixSignalRegistrationTests+<>c.<ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds>b__13_0()
      			[HelperMethodFrame_PROTECTOBJ] (System.RuntimeMethodHandle.InvokeMethod)
      			System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(System.Object, IntPtr*)
      			System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
      			System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
      			System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
      			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
      		Thread #2 (OS 0x17A0) [Finalizer] [Background] 
      			[DebuggerU2MCatchHandlerFrame]
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(225,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/PosixSignalRegistrationTests.Windows.cs(35,0): at System.Tests.PosixSignalRegistrationTests.ExternalConsoleManipulation_RegistrationRemoved_UnregisterSucceeds()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs(36,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=817147&view=ms.vss-test-web.build-test-results-tab&runId=21195830&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=153443

**Comment by BruceForstall** [comment]
Guessed at an area

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250206.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=943943&view=ms.vss-test-web.build-test-results-tab&runId=25062430&resultId=150330&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-arm64-jitstress1_tiered-Windows.11.Arm64.Open
    - System.Collections.Concurrent.Tests.EtwTests.TestEtw
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 35

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    964 BrokerInfrastructure, DcomLaunch, Power,    
                                   SystemEventsBroker                          
svchost.exe                    592 RpcEptMapper, RpcSs                         
svchost.exe                    860 LSM                                         
svchost.exe                   1192 TermService                                 
svchost.exe                   1200 CryptSvc                                    
svchost.exe                   1232 lmhosts                                     
svchost.exe                   1284 CoreMessagingRegistrar                      
svchost.exe                   1304 TimeBrokerSvc                               
svchost.exe                   1444 AppIDSvc                                    
svchost.exe                   1452 NcbService                                  
svchost.exe                   1544 Schedule                                    
svchost.exe                   1564 DispBrokerDesktopSvc                        
svchost.exe                   1584 ProfSvc                                     
svchost.exe                   1692 UmRdpService                                
svchost.exe                   1728 UserManager                                 
svchost.exe                   1764 nsi                                         
svchost.exe                   1916 netprofm                                    
svchost.exe                   1964 LanmanWorkstation                           
svchost.exe                   1980 vmicheartbeat                               
svchost.exe                   1988 vmickvpexchange                             
svchost.exe                   2004 vmicshutdown                                
svchost.exe                   2024 vmictimesync                                
svchost.exe                   2124 EventLog                                    
svchost.exe                   2216 SessionEnv                                  
svchost.exe                   2316 Dnscache                                    
svchost.exe                   2360 EventSystem                                 
svchost.exe                   2372 Themes                                      
svchost.exe                   2380 SysMain                                     
svchost.exe                   2400 CertPropSvc                                 
svchost.exe                   2584 Dhcp                                        
svchost.exe                   2620 SENS                                        
svchost.exe                   2716 AudioEndpointBuilder                        
svchost.exe                   2728 FontCache                                   
svchost.exe                   2800 WinHttpAutoProxySvc                         
svchost.exe                   2844 Audiosrv                                    
svchost.exe                   2912 TextInputManagementService                  
svchost.exe                   3012 DusmSvc                                     
svchost.exe                   3020 Wcmsvc                                      
svchost.exe                   1164 RmSvc                                       
svchost.exe                   2520 ShellHWDetection                            
svchost.exe                   3236 BFE, mpssvc                                 
svchost.exe                   3376 DPS                                         
svchost.exe                   3384 iphlpsvc                                    
svchost.exe                   3396 LanmanServer                                
svchost.exe                   3404 DiagTrack                         
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 55
   at System.Collections.Concurrent.Tests.EtwTests.TestEtw() in /_/src/libraries/System.Collections.Concurrent/tests/EtwTests.cs:line 17
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs:line 1159
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstressregs 20250413.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1014770&view=ms.vss-test-web.build-test-results-tab&runId=27147844&resultId=133885&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstressregs2-Windows.10.Amd64.Open
    - Microsoft.Win32.SystemEventsTests.ShutdownTest.ShutdownSuccessDespiteThreadBlock
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 17

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    772 BrokerInfrastructure, DcomLaunch, LSM,      
                                   PlugPlay, Power, SystemEventsBroker         
svchost.exe                    832 RpcEptMapper, RpcSs                         
svchost.exe                    932 TermService                                 
svchost.exe                    948 Appinfo, CertPropSvc, DsmSvc, gpsvc,        
                                   iphlpsvc, lfsvc, ProfSvc, sacsvr, Schedule, 
                                   SENS, SessionEnv, ShellHWDetection, Themes, 
                                   UserManager, Winmgmt, wisvc, WpnService,    
                                   wuauserv                                    
svchost.exe                    992 NcbService, PcaSvc, TrkWks, UALSVC,         
                                   UmRdpService, vmickvpexchange,              
                                   vmicshutdown, WdiSystemHost, WPDBusEnum     
svchost.exe                   1000 Dhcp, EventLog, lmhosts, NgcCtnrSvc,        
                                   TimeBrokerSvc, vmictimesync                 
svchost.exe                   1064 vmicheartbeat                               
svchost.exe                   1232 BFE, CoreMessagingRegistrar, DPS, MpsSvc,   
                                   pla                                         
svchost.exe                   1240 CDPSvc, EventSystem, FontCache, netprofm,   
                                   nsi, RemoteRegistry, W32Time,               
                                   WinHttpAutoProxySvc                         
svchost.exe                   1380 Wcmsvc                                      
svchost.exe                   1388 CryptSvc, Dnscache, LanmanWorkstation,      
                                   NlaSvc, WinRM                               
svchost.exe                   2060 AppHostSvc                                  
svchost.exe                   2084 DiagTrack                                   
svchost.exe                   2120 W3SVC, WAS                                  
svchost.exe                   2204 StateRepository, tiledatamodelsvc           
svchost.exe                   2236 LanmanServer                                
svchost.exe                   3736 CDPUserSvc_4c7b8, OneSyncSvc_4c7b8          
svchost.exe                   3228 AppReadiness                                
svchost.exe                    700 WerSvc                                      
svchost.exe                    368 AppIDSvc                                    
Timed out at 4/13/2025 10:17:03 AM after 60000ms waiting for remote process.
Wrote mini dump to: C:\h\w\B9DE09D4\w\BFCA0A00\uploads\5292.4va3j0og.txj.dmp
	Process ID: 5292
	Handle: 1124
	Name: dotnet
	MainModule: C:\h\w\B9DE09D4\p\dotnet.exe
	StartTime: 4/13/2025 10:16:03 AM
	TotalProcessorTime: 00:01:00.5468750
	Threads:
		Thread #1 (OS 0x390)   [MTA]
			[InlinedCallFrame] (Interop+User32.SendMessageW)
			Microsoft.Win32.SystemEventsTests.ShutdownTest.<ShutdownSuccessDespiteThreadBlock>b__1_0()
			[InlinedCallFrame]
			System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(System.Object, IntPtr*)
			System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
			System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
			[InlinedCallFrame]
		Thread #2 (OS 0x166C) [Finalizer] [Background] 
			[DebuggerU2MCatchHandlerFrame]
		Thread #3 (OS 0xA34)  [Background] [MTA]
			
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.Win32.SystemEventsTests.ShutdownTest.ShutdownSuccessDespiteThreadBlock() in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/ShutdownTest.cs:line 37
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250414.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1015937&view=ms.vss-test-web.build-test-results-tab&runId=27177690&resultId=160278&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x64-tailcallstress-Windows.10.Amd64.Open
    - Microsoft.Win32.SystemEventsTests.ShutdownTest.ShutdownSuccessDespiteThreadBlock
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
Memory load: 16

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    776 BrokerInfrastructure, DcomLaunch, LSM,      
                                   PlugPlay, Power, SystemEventsBroker         
svchost.exe                    840 RpcEptMapper, RpcSs                         
svchost.exe                    948 Appinfo, CertPropSvc, DsmSvc, gpsvc,        
                                   iphlpsvc, lfsvc, ProfSvc, sacsvr, Schedule, 
                                   SENS, SessionEnv, ShellHWDetection, Themes, 
                                   UserManager, Winmgmt, WpnService, wuauserv  
svchost.exe                    964 TermService                                 
svchost.exe                    320 Dhcp, EventLog, lmhosts, NgcCtnrSvc,        
                                   TimeBrokerSvc, vmictimesync                 
svchost.exe                    480 NcbService, PcaSvc, TrkWks, UALSVC,         
                                   UmRdpService, vmickvpexchange,              
                                   vmicshutdown, WdiSystemHost, WPDBusEnum     
svchost.exe                    792 CDPSvc, EventSystem, FontCache, netprofm,   
                                   nsi, RemoteRegistry, W32Time,               
                                   WinHttpAutoProxySvc                         
svchost.exe                    912 vmicheartbeat                               
svchost.exe                   1228 CryptSvc, Dnscache, LanmanWorkstation,      
                                   NlaSvc, WinRM                               
svchost.exe                   1408 BFE, CoreMessagingRegistrar, DPS, MpsSvc,   
                                   pla                                         
svchost.exe                   1436 Wcmsvc                                      
svchost.exe                   2036 W3SVC, WAS                                  
svchost.exe                   1292 StateRepository, tiledatamodelsvc           
svchost.exe                   1336 DiagTrack                                   
svchost.exe                   1340 AppHostSvc                                  
svchost.exe                   2140 LanmanServer                                
svchost.exe                   3180 CDPUserSvc_4ea88, OneSyncSvc_4ea88          
svchost.exe                   3756 AppReadiness                                
Timed out at 4/14/2025 8:06:23 PM after 60000ms waiting for remote process.
Wrote mini dump to: C:\h\w\B4820A0A\w\AB7C09A3\uploads\5372.kf5oig2p.btg.dmp
	Process ID: 5372
	Handle: 1052
	Name: dotnet
	MainModule: C:\h\w\B4820A0A\p\dotnet.exe
	StartTime: 4/14/2025 8:05:23 PM
	TotalProcessorTime: 00:01:00.3125000
	Threads:
		Thread #1 (OS 0xCAC)   [MTA]
			[InlinedCallFrame] (Interop+User32.SendMessageW)
			[InlinedCallFrame] (Interop+User32.SendMessageW)
			Microsoft.Win32.SystemEventsTests.ShutdownTest.<ShutdownSuccessDespiteThreadBlock>b__1_0()
			[InlinedCallFrame]
			[InlinedCallFrame]
			System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(System.Object, IntPtr*)
			System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
			System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
		Thread #2 (OS 0xFF4) [Finalizer] [Background] 
			[DebuggerU2MCatchHandlerFrame]
		Thread #3 (OS 0x810)  [Background] [MTA]
			Microsoft.Win32.SystemEventsTests.ShutdownTest+<>c.<ShutdownSuccessDespiteThreadBlock>b__1_1(System.Object, Microsoft.Win32.UserPreferenceChangedEventArgs)
			[InlinedCallFrame]
			[InlinedCa
```

**Stack trace:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 225
   at Microsoft.Win32.SystemEventsTests.ShutdownTest.ShutdownSuccessDespiteThreadBlock() in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/ShutdownTest.cs:line 37
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by agocke** [comment]
I believe "remote execution exception" is basically the infra saying that the test failed. Looking at each of the tests, they seem unrelated. We should investigate the specific test failures rather than this error message.

**Comment by AndyAyersMS** [comment]
I have this same failure in my PR ([console log](https://[helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-114754-merge-5385328b7b494afa9d/System.Text.Json.Tests/1/console.82e7fa32.log?skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-04-17T21%3A57%3A57Z&ske=2025-04-17T22%3A57%3A57Z&sks=b&skv=2024-11-04&sv=2024-11-04&st=2025-04-17T21%3A57%3A57Z&se=2025-04-17T22%3A57%3A57Z&sr=c&sp=r&sig=R8DqqnRXYZVKlJYOuP9HEJMWCGwDKjYF9k3RiOXyZg4%3D](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-114754-merge-5385328b7b494afa9d/System.Text.Json.Tests/1/console.82e7fa32.log?skoid=8eda00af-b5ec-4be9-b69b-0919a2338892&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2025-04-17T21%3A57%3A57Z&ske=2025-04-17T22%3A57%3A57Z&sks=b&skv=2024-11-04&sv=2024-11-04&st=2025-04-17T21%3A57%3A57Z&se=2025-04-17T22%3A57%3A57Z&sr=c&sp=r&sig=R8DqqnRXYZVKlJYOuP9HEJMWCGwDKjYF9k3RiOXyZg4%3D))), here's the only thread in the child process that is not waiting:
```
00 000000a4`56579078 00007ffa`b66fb9f4     ntdll!NtCreateSection+0x14
01 000000a4`56579080 00007ffa`b66fa99d     ntdll!LdrpMapDllNtFileName+0x194
02 000000a4`56579170 00007ffa`b66fa3b4     ntdll!LdrpMapDllFullPath+0xf5
03 000000a4`56579300 00007ffa`b66ff0a0     ntdll!LdrpProcessWork+0x144
04 000000a4`56579360 00007ffa`b66fed20     ntdll!LdrpLoadDllInternal+0x210
05 000000a4`565793f0 00007ffa`b670a650     ntdll!LdrpLoadDll+0x100
06 000000a4`565795c0 00007ffa`b3f02446     ntdll!LdrLoadDll+0x170
07 000000a4`565796b0 00007ffa`79606873     KERNELBASE!LoadLibraryExW+0xe6
08 000000a4`56579720 00007ffa`79606735     coreclr!LoadLibraryExWrapper+0xd7 [D:\a\_work\1\s\src\coreclr\utilcode\longfilepathwrappers.cpp @ 273] 
09 (Inline Function) --------`--------     coreclr!CLRLoadLibraryExWorker+0x2a [D:\a\_work\1\s\src\coreclr\vm\util.cpp @ 977] 
0a (Inline Function) --------`--------     coreclr!CLRLoadLibraryEx+0x2a [D:\a\_work\1\s\src\coreclr\vm\util.cpp @ 995] 
0b 000000a4`565799d0 00007ffa`79606621     coreclr!LoadedImageLayout::LoadedImageLayout+0xa5 [D:\a\_work\1\s\src\coreclr\vm\peimagelayout.cpp @ 544] 
0c 000000a4`56579a10 00007ffa`79606599     coreclr!PEImageLayout::Load+0x5d [D:\a\_work\1\s\src\coreclr\vm\peimagelayout.cpp @ 136] 
0d 000000a4`56579a50 00007ffa`7960654d     coreclr!PEImage::CreateLoadedLayout+0x21 [D:\a\_work\1\s\src\coreclr\vm\peimage.cpp @ 673] 
0e 000000a4`56579a80 00007ffa`796197a4     coreclr!PEImage::GetOrCreateLayoutInternal+0x69 [D:\a\_work\1\s\src\coreclr\vm\peimage.cpp @ 645] 
0f 000000a4`56579ab0 00007ffa`796162de     coreclr!PEImage::GetOrCreateLayout+0xd0 [D:\a\_work\1\s\src\coreclr\vm\peimage.cpp @ 586] 
10 000000a4`56579b10 00007ffa`795da41f     coreclr!BinderAcquireImport+0x82 [D:\a\_work\1\s\src\coreclr\vm\coreassemblyspec.cpp @ 125] 
```
There are 8 critsecs in the process, none are held.

Doesn't seem like this process could be frozen here but it seemingly was.
