### ISSUE TITLE
Test failure: GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#108308]
**Failed in:** [runtime-coreclr r2r 20240925.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=818700&view=ms.vss-test-web.build-test-results-tab&runId=21245898&resultId=119325&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm64 Checked no_tiered_compilation @ (Ubuntu.2004.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8
    - GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.cmd
```

**Error message:**
```
 /root/helix/work/workitem/e/GC/Scenarios/GC-scenarios1/../DoublinkList/dlbigleakthd/dlbigleakthd.sh: line 323: -r:/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/*.dll: No such file or directory
DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /root/helix/work/correlation/crossgen2/createdump
DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /root/helix/work/correlation/crossgen2/createdump

Assert failure(PID 806 [0x00000326], Thread: 813 [0x032d]): committed_by_oh[oh] == compute_committed_bytes_per_heap (oh, committed_bookkeeping)
    File: /__w/1/s/src/coreclr/gc/gc.cpp:47978
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff94650600)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff94650600)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/GC/Scenarios/GC-scenarios1/../DoublinkList/dlbigleakthd/dlbigleakthd.sh: line 440:   806 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/DoublinkList/dlbigleakthd/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/dlbigleakthd.dll
07:27:56
Response file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll.rsp
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/dlbigleakthd.dll
-o:/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll.rsp  
Emitting R2R PE file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll --out /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll.r2rdump --val
07:27:56
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/DoubLinkList.dll
07:27:56
Response file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll.rsp
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/DoubLinkList.dll
-o:/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll.rsp  
Emitting R2R PE file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll --out /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll.r2rdump --val
07:27:57
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true dlbigleakthd.dll ''
Test should return with ExitCode 100 ...
[createdump] Gatherin
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor16|0_17(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/104178

cc @cshung

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr r2r 20240927.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=821098&view=ms.vss-test-web.build-test-results-tab&runId=21312892&resultId=111430&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm64 Checked @ (Ubuntu.2004.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8
    - GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.cmd
```

**Error message:**
```
 /root/helix/work/workitem/e/GC/Scenarios/GC-scenarios1/../DoublinkList/dlbigleakthd/dlbigleakthd.sh: line 323: -r:/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/*.dll: No such file or directory
DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /root/helix/work/correlation/crossgen2/createdump
DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /root/helix/work/correlation/crossgen2/createdump

Assert failure(PID 850 [0x00000352], Thread: 850 [0x0352]): committed_by_oh[oh] == compute_committed_bytes_per_heap (oh, committed_bookkeeping)
    File: /__w/1/s/src/coreclr/gc/gc.cpp:47978
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff9d5aeb80)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff9d5aeb80)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/GC/Scenarios/GC-scenarios1/../DoublinkList/dlbigleakthd/dlbigleakthd.sh: line 440:   850 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/DoublinkList/dlbigleakthd/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/dlbigleakthd.dll
07:10:13
Response file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll.rsp
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/dlbigleakthd.dll
-o:/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll.rsp  
Emitting R2R PE file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll --out /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.dll.r2rdump --val
07:10:13
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/DoubLinkList.dll
07:10:13
Response file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll.rsp
/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/IL-CG2/DoubLinkList.dll
-o:/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll.rsp  
Emitting R2R PE file: /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll --out /root/helix/work/workitem/e/GC/Scenarios/DoublinkList/dlbigleakthd/DoubLinkList.dll.r2rdump --val
07:10:13
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true dlbigleakthd.dll ''
Test should return with ExitCode 100 ...
[createdump] Gatherin
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor16|0_17(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by mangod9** [comment]
Closing as dupe of https://github.com/dotnet/runtime/issues/104178
