### ISSUE TITLE
[area-Tools-ILLink]: Failed on .NET MAUI CI for macOS build: Fatal error in IL Linker

### ISSUE THREAD

**Issue by Eilon** [dotnet/runtime#108617]
### Description

AzDO build log: https://dev.azure.com/xamarin/public/_build/results?buildId=125088&view=logs&j=71979588-66ac-5e95-831a-69c8cd9b2cd2&t=acd19e4c-afbd-5efc-2769-76bfa657ccbb&l=24110

Here are some details from the log:

```
   Maui.Controls.Sample -> /Users/builder/azdo/_work/2/s/artifacts/bin/Maui.Controls.Sample/Release/net9.0-maccatalyst/maccatalyst-x64/Maui.Controls.Sample.dll
   Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
   Optimizing assemblies for size. This process might take a while.
 ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink [/Users/builder/azdo/_work/2/s/src/Controls/samples/Controls.Sample/Maui.Controls.Sample.csproj::TargetFramework=net9.0-maccatalyst]
   Fatal error in IL Linker
   Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
      at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
      at Mono.Linker.Dataflow.TrimAnalysisMethodCallPattern.Merge(ValueSetLattice`1 lattice, TrimAnalysisMethodCallPattern other)
      at Mono.Linker.Dataflow.TrimAnalysisPatternStore.Add(TrimAnalysisMethodCallPattern pattern)
      at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams)
      at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack, Dictionary`2 locals, InterproceduralState& interproceduralState, Int32 curBasicBlock)
      at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodIL methodIL, InterproceduralState& interproceduralState)
      at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.Scan(MethodIL methodIL, InterproceduralState& interproceduralState)
      at Mono.Linker.Dataflow.MethodBodyScanner.InterproceduralScan(MethodIL startingMethodIL)
      at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.InterproceduralScan(MethodIL methodIL)
      at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodIL methodIL, Boolean requiresReflectionMethodBodyScanner, MessageOrigin origin)
      at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body, MessageOrigin origin)
      at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
      at Mono.Linker.Steps.MarkStep.ProcessQueue()
      at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
      at Mono.Linker.Steps.MarkStep.Process()
      at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
      at Mono.Linker.Pipeline.Process(LinkContext context)
      at Mono.Linker.Driver.Run(ILogger customLogger)
      at Mono.Linker.Driver.Main(String[] args)
 /Users/builder/.nuget/packages/microsoft.net.illink.tasks/9.0.0-rtm.24501.6/build/Microsoft.NET.ILLink.targets(96,5): error NETSDK1144: Optimizing assemblies for size failed. [/Users/builder/azdo/_work/2/s/src/Controls/samples/Controls.Sample/Maui.Controls.Sample.csproj::TargetFramework=net9.0-maccatalyst]
   Maui.Controls.Sample -> /Users/builder/azdo/_work/2/s/artifacts/bin/Maui.Controls.Sample/Release/net9.0/Maui.Controls.Sample.dll
```

### Reproduction Steps

Not sure about exact repro. This is happening on a CI build on AzDO.

### Expected behavior

No error.

### Actual behavior

Error.

**Comment by kornect** [comment]
Getting the same error running on Azure pipelines and locally, I have absolutely no idea what to look for.

```
0>ILLink: Error IL1012 : IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink
Fatal error in IL Linker
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mono.Linker.Dataflow.TrimAnalysisMethodCallPattern.Merge(ValueSetLattice`1 lattice, TrimAnalysisMethodCallPattern other)
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack, Dictionary`2 locals, InterproceduralState& interproceduralState, Int32 curBasicBlock)
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodIL methodIL, InterproceduralState& interproceduralState)
   at Mono.Linker.Dataflow.MethodBodyScanner.InterproceduralScan(MethodIL startingMethodIL)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.InterproceduralScan(MethodIL methodIL)
   at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodIL methodIL, Boolean requiresReflectionMethodBodyScanner, MessageOrigin origin)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
0>Microsoft.NET.ILLink.targets(96,5): Error NETSDK1144 : Optimizing assemblies for size failed.
```

**Comment by valentingrigorean** [comment]
Getting the same error...

```
>ILLink: Error IL1012 : IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink
Fatal error in IL Linker
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Mono.Linker.Dataflow.TrimAnalysisMethodCallPattern.Merge(ValueSetLattice`1 lattice, TrimAnalysisMethodCallPattern other)
   at Mono.Linker.Dataflow.TrimAnalysisPatternStore.Add(TrimAnalysisMethodCallPattern pattern)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams)
   at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack, Dictionary`2 locals, InterproceduralState& interproceduralState, Int32 curBasicBlock)
   at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodIL methodIL, InterproceduralState& interproceduralState)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.Scan(MethodIL methodIL, InterproceduralState& interproceduralState)
   at Mono.Linker.Dataflow.MethodBodyScanner.InterproceduralScan(MethodIL startingMethodIL)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.InterproceduralScan(MethodIL methodIL)
   at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodIL methodIL, Boolean requiresReflectionMethodBodyScanner, MessageOrigin origin)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body, MessageOrigin origin)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
Build continuing because "ContinueOnError" on the task "ILLink" is set to "ErrorAndContinue".
Target ILLink:
```

csproj
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-ios</TargetFramework>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\gps\Hjelp113.Gps.iOS\Hjelp113.Gps.iOS.csproj"/>
        <ProjectReference Include="..\..\gps\Hjelp113.Gps\Hjelp113.Gps.csproj"/>
        <ProjectReference Include="..\..\snla\Snla.iOS.Extended\Snla.iOS.Extended.csproj"/>
        <ProjectReference Include="..\Hjelp113.Core\Hjelp113.Core.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AdamE.Firebase.iOS.Analytics" Version="11.10.0" />
        <PackageReference Include="AdamE.Firebase.iOS.Crashlytics" Version="11.10.0" />
        <PackageReference Include="AdamE.Firebase.iOS.Installations" Version="11.10.0" />
        <PackageReference Include="MBProgressHUDiOS" Version="1.2.0" />
        <PackageReference Include="Microsoft.Maui.Essentials" Version="$(MauiVersion)"/>
        <PackageReference Include="BTProgressHUD" Version="2.2.0" />
        <PackageReference Include="MPowerKit.Lottie.MaciOS" Version="4.5.1" />
        <PackageReference Include="ReactiveUI.Fody" Version="19.5.41"/>
    </ItemGroup>
    <ItemGroup>
        <BundleResource Include="GoogleService-Info.plist" Condition="Exists('GoogleService-Info.plist')"/>
    </ItemGroup>
</Project>
```
Work for simulator debug/release can't build it on actual device debug/release
[msbuild.binlog](https://drive.google.com/file/d/1X2t-6Lm-pIdtlAda9k0LSEG_CM8xEzq6/view?usp=sharing)

**Comment by sbomer** [comment]
We'll need a repro to figure out what's going wrong here. @valentingrigorean any chance you would be able to share one?

**Comment by valentingrigorean** [comment]
@sbomer Hey! I’ve upgraded to a newer MAUI version, and the issue no longer reproduces on my end. It seemed to occur only in my specific project setup, and I wasn’t able to isolate a minimal reproducible example.
