### ISSUE TITLE
Test failure: baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#108698]
**Failed in:** [runtime-coreclr outerloop 20241008.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=833799&view=ms.vss-test-web.build-test-results-tab&runId=21650126&resultId=102950&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked no_tiered_compilation @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
```

**Error message:**
```
 
Assert failure(PID 212 [0x000000d4], Thread: 212 [0x00d4]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x4c, unman: 0x48, Name: System.Diagnostics.StackFrameHelper
FAILED: size == expectedsize
    File: /__w/1/s/src/coreclr/vm/binder.cpp:647
    Image: /root/helix/work/correlation/crossgen2/crossgen2

[createdump] The app model does not support crash report generation
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
/root/helix/work/workitem/e/baseservices/baseservices/../TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh: line 211:   212 Aborted                 (core dumped) "$CORE_ROOT/crossgen2/crossgen2" --out r2r/BasicTestWithMcj.dll BasicTestWithMcj.dll -r $CORE_ROOT/*.dll
BEGIN: coreclr_initialize failed - Error: 0x80070057
END: coreclr_initialize failed - Error: 0x80070057

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/TieredCompilation/BasicTestWithMcj/output.txt
Raw output:
BEGIN EXECUTION
[createdump] Target process is alive
./RunBasicTestWithMcj.sh --runCustomTest /root/helix/work/workitem/e/baseservices/TieredCompilation/BasicTestWithMcj/ BasicTestWithMcj.dll ''
Collect profile without R2R, use profile without R2R
Collect profile with R2R, use profile with R2R
Exe path: /root/helix/work/correlation/corerun
Properties:
    TRUSTED_PLATFORM_ASSEMBLIES = /root/helix/work/correlation/System.Linq.dll:/root/helix/work/correlation/System.Security.Cryptography.Cose.dll:/root/helix/work/correlation/System.Security.SecureString.dll:/root/helix/work/correlation/System.ComponentModel.dll:/root/helix/work/correlation/System.Management.dll:/root/helix/work/correlation/System.Runtime.InteropServices.dll:/root/helix/work/correlation/System.Diagnostics.TextWriterTraceListener.dll:/root/helix/work/correlation/Newtonsoft.Json.Bson.dll:/root/helix/work/correlation/System.Linq.Queryable.dll:/root/helix/work/correlation/System.CodeDom.dll:/root/helix/work/correlation/System.Xml.XmlDocument.dll:/root/helix/work/correlation/Microsoft.Diagnostics.Tools.RuntimeClient.dll:/root/helix/work/correlation/System.Security.Cryptography.Algorithms.dll:/root/helix/work/correlation/System.Reflection.Emit.Lightweight.dll:/root/helix/work/correlation/System.Collections.Concurrent.dll:/root/helix/work/correlation/Newtonsoft.Json.dll:/root/helix/work/correlation/System.Runtime.Intrinsics.dll:/root/helix/work/correlation/System.Numerics.Vectors.dll:/root/helix/work/correlation/System.Reflection.Extensions.dll:/root/helix/work/correlation/System.Globalization.Calendars.dll:/root/helix/work/correlation/System.Reflection.Metadata.dll:/root/helix/work/correlation/System.Security.Permissions.dll:/root/helix/work/correlation/System.Runtime.Serialization.Primitives.dll:/root/helix/work/correlation/System.Net.Primitives.dll:/root/helix/work/correlation/System.Private.DataContractSerialization.dll:/root/helix/work/correlation/System.Net.Sockets.dll:/root/helix/work/correlation/System.Composition.Hosting.dll:/root/helix/work/correlation/System.Reflection.TypeExtensions.dll:/root/helix/work/correlation/Microsoft.Extensions.DependencyModel.dll:/root/helix/work/correlation/System.IO.Pipes.dll:/root/helix/work/correlation/Microsoft.Extensions.Diagnostics.dll:/root/helix/work/correlation/System.Transactions.Local.dll:/root/helix/work/correlation/System.Net.Requests.dll:/root/helix/work/correlation/System.Diagnostics.TraceSource.dll:/root/helix/work/correlation/System.Formats.Asn1.dll:/root/helix/work/correlation/System.Security.Cryptography.dll:/root/helix/work/correlation/System.Diagnostics.Process.dll:/root/helix/work/correlation/Microsoft.Extensions.Logging.Console.dll:/root/helix/work/correlation/System.Xml.Serialization.dll:/root/helix/work/correlation/System.Composition.TypedParts.dll:/root/helix/work/correlation/System.Runtime.Extensions.dll:/root/helix/work/correlation/System.Formats.Nrbf.dll:/root/helix/work/correlation/Micros
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor23|0_24(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20241009.4](https://dev.azure.com/dnceng-public/public/_build/results?buildId=836052&view=ms.vss-test-web.build-test-results-tab&runId=21675330&resultId=103776&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
coreclr linux arm Checked no_tiered_compilation @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
```

**Error message:**
```
 
Assert failure(PID 240 [0x000000f0], Thread: 240 [0x00f0]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x4c, unman: 0x48, Name: System.Diagnostics.StackFrameHelper
FAILED: size == expectedsize
    File: /__w/1/s/src/coreclr/vm/binder.cpp:647
    Image: /root/helix/work/correlation/crossgen2/crossgen2

[createdump] The app model does not support crash report generation
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
/root/helix/work/workitem/e/baseservices/baseservices/../TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh: line 211:   240 Aborted                 (core dumped) "$CORE_ROOT/crossgen2/crossgen2" --out r2r/BasicTestWithMcj.dll BasicTestWithMcj.dll -r $CORE_ROOT/*.dll
BEGIN: coreclr_initialize failed - Error: 0x80070057
END: coreclr_initialize failed - Error: 0x80070057

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/TieredCompilation/BasicTestWithMcj/output.txt
Raw output:
BEGIN EXECUTION
[createdump] Target process is alive
./RunBasicTestWithMcj.sh --runCustomTest /root/helix/work/workitem/e/baseservices/TieredCompilation/BasicTestWithMcj/ BasicTestWithMcj.dll ''
Collect profile without R2R, use profile without R2R
Collect profile with R2R, use profile with R2R
Exe path: /root/helix/work/correlation/corerun
Properties:
    TRUSTED_PLATFORM_ASSEMBLIES = /root/helix/work/correlation/Microsoft.Extensions.FileProviders.Composite.dll:/root/helix/work/correlation/System.Diagnostics.EventLog.dll:/root/helix/work/correlation/System.ComponentModel.EventBasedAsync.dll:/root/helix/work/correlation/System.Composition.Runtime.dll:/root/helix/work/correlation/System.Xml.XmlSerializer.dll:/root/helix/work/correlation/System.Runtime.Caching.dll:/root/helix/work/correlation/xunit.runner.reporters.netcoreapp10.dll:/root/helix/work/correlation/System.Formats.Nrbf.dll:/root/helix/work/correlation/ILCompiler.Reflection.ReadyToRun.dll:/root/helix/work/correlation/System.Reflection.TypeExtensions.dll:/root/helix/work/correlation/System.Runtime.CompilerServices.VisualC.dll:/root/helix/work/correlation/System.DirectoryServices.dll:/root/helix/work/correlation/System.Runtime.Serialization.Primitives.dll:/root/helix/work/correlation/Microsoft.Extensions.Logging.Console.dll:/root/helix/work/correlation/xunit.core.dll:/root/helix/work/correlation/System.Linq.dll:/root/helix/work/correlation/System.Data.OleDb.dll:/root/helix/work/correlation/System.Xml.XDocument.dll:/root/helix/work/correlation/System.Net.Primitives.dll:/root/helix/work/correlation/System.Threading.RateLimiting.dll:/root/helix/work/correlation/System.Net.Sockets.dll:/root/helix/work/correlation/System.Dynamic.Runtime.dll:/root/helix/work/correlation/System.Threading.Tasks.Parallel.dll:/root/helix/work/correlation/System.Threading.Tasks.Dataflow.dll:/root/helix/work/correlation/Microsoft.Extensions.Options.ConfigurationExtensions.dll:/root/helix/work/correlation/System.IO.Pipelines.dll:/root/helix/work/correlation/System.Security.Cryptography.Cose.dll:/root/helix/work/correlation/System.Drawing.dll:/root/helix/work/correlation/CommandLine.dll:/root/helix/work/correlation/System.Drawing.Primitives.dll:/root/helix/work/correlation/System.IO.FileSystem.Primitives.dll:/root/helix/work/correlation/System.Reflection.MetadataLoadContext.dll:/root/helix/work/correlation/System.Globalization.dll:/root/helix/work/correlation/Microsoft.Extensions.Logging.EventSource.dll:/root/helix/work/correlation/System.Text.Encoding.CodePages.dll:/root/helix/work/correlation/Microsoft.Extensions.Configuration.CommandLine.dll:/root/helix/work/correlation/Microsoft.Extensions.FileProviders.Abstractions.dll:/root/helix/work/correlation/System.Speech.dll:/root/helix/work/correlation/System.Resources.Reader.dll:/root/helix/work/correlation/Microsoft.CSharp.dll:/root/helix/work/correlation/Microsoft.Extensions.Hosting.WindowsServices.dll:/root/helix/work/correlation/System.N
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor23|0_24(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20241013.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841199&view=ms.vss-test-web.build-test-results-tab&runId=21810376&resultId=105897&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked no_tiered_compilation @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.cmd
```

**Error message:**
```
 
Assert failure(PID 211 [0x000000d3], Thread: 211 [0x00d3]): Consistency check failed: Managed object size does not match unmanaged object size
man: 0x4c, unman: 0x48, Name: System.Diagnostics.StackFrameHelper
FAILED: size == expectedsize
    File: /__w/1/s/src/coreclr/vm/binder.cpp:647
    Image: /root/helix/work/correlation/crossgen2/crossgen2

[createdump] The app model does not support crash report generation
[createdump] Failure took 2ms
waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
/root/helix/work/workitem/e/baseservices/baseservices/../TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh: line 211:   211 Aborted                 (core dumped) "$CORE_ROOT/crossgen2/crossgen2" --out r2r/BasicTestWithMcj.dll BasicTestWithMcj.dll -r $CORE_ROOT/*.dll
BEGIN: coreclr_initialize failed - Error: 0x80070057
END: coreclr_initialize failed - Error: 0x80070057

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/TieredCompilation/BasicTestWithMcj/output.txt
Raw output:
BEGIN EXECUTION
[createdump] Target process is alive
./RunBasicTestWithMcj.sh --runCustomTest /root/helix/work/workitem/e/baseservices/TieredCompilation/BasicTestWithMcj/ BasicTestWithMcj.dll ''
Collect profile without R2R, use profile without R2R
Collect profile with R2R, use profile with R2R
Exe path: /root/helix/work/correlation/corerun
Properties:
    TRUSTED_PLATFORM_ASSEMBLIES = /root/helix/work/correlation/Microsoft.Extensions.Logging.Console.dll:/root/helix/work/correlation/System.Console.dll:/root/helix/work/correlation/Microsoft.Extensions.Hosting.dll:/root/helix/work/correlation/Microsoft.Bcl.AsyncInterfaces.dll:/root/helix/work/correlation/System.Security.Cryptography.X509Certificates.dll:/root/helix/work/correlation/System.Formats.Cbor.dll:/root/helix/work/correlation/System.Runtime.dll:/root/helix/work/correlation/System.Net.dll:/root/helix/work/correlation/System.Net.Ping.dll:/root/helix/work/correlation/System.Threading.Overlapped.dll:/root/helix/work/correlation/mscorlib.dll:/root/helix/work/correlation/System.Management.dll:/root/helix/work/correlation/System.Dynamic.Runtime.dll:/root/helix/work/correlation/System.IO.UnmanagedMemoryStream.dll:/root/helix/work/correlation/Newtonsoft.Json.Bson.dll:/root/helix/work/correlation/System.Formats.Tar.dll:/root/helix/work/correlation/FSharp.Core.dll:/root/helix/work/correlation/System.Reflection.Emit.dll:/root/helix/work/correlation/System.Private.Xml.Linq.dll:/root/helix/work/correlation/System.ObjectModel.dll:/root/helix/work/correlation/Microsoft.Win32.Registry.AccessControl.dll:/root/helix/work/correlation/System.Data.DataSetExtensions.dll:/root/helix/work/correlation/xunit.console.dll:/root/helix/work/correlation/Microsoft.Diagnostics.FastSerialization.dll:/root/helix/work/correlation/Microsoft.Extensions.Hosting.WindowsServices.dll:/root/helix/work/correlation/System.Security.Cryptography.ProtectedData.dll:/root/helix/work/correlation/System.Resources.Writer.dll:/root/helix/work/correlation/CommandLine.dll:/root/helix/work/correlation/System.Formats.Nrbf.dll:/root/helix/work/correlation/Microsoft.Extensions.Options.ConfigurationExtensions.dll:/root/helix/work/correlation/System.Data.Odbc.dll:/root/helix/work/correlation/System.Composition.Convention.dll:/root/helix/work/correlation/Microsoft.Extensions.Diagnostics.Abstractions.dll:/root/helix/work/correlation/System.Reflection.Emit.ILGeneration.dll:/root/helix/work/correlation/System.IO.Compression.dll:/root/helix/work/correlation/System.Composition.TypedParts.dll:/root/helix/work/correlation/System.Net.WebSockets.Client.dll:/root/helix/work/correlation/System.Net.NetworkInformation.dll:/root/helix/work/correlation/System.Threading.Thread.dll:/root/helix/work/correlation/Microsoft.Extensions.Options.dll:/root/helix/work/correlation/System.Security.Cryptography.Encoding.dll:/root/helix/work/correlation/Microsoft.Extensions.Logging.Configuration.dll:/root/helix/work/correlation/System.ValueTuple.dll:
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor23|0_24(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
