### ISSUE TITLE
Libraries test fails with "Method has zero rva" error

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#108641]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=830089
Build error leg or test failing: System.Tests.EnvironmentTests.CurrentDirectory_SetToValidOtherDirectory
Pull request: https://github.com/dotnet/runtime/pull/108032

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.BadImageFormatException : Method has zero rva",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
From [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-108032-merge-61ef30b425874d4d94/System.Net.Sockets.Tests/1/console.0c53ee85.log?helixlogtype=result):
```log
System.Tests.EnvironmentTests.CurrentDirectory_SetToValidOtherDirectory [FAIL]
      System.BadImageFormatException : Method has zero rva
      Stack Trace:
        /_/src/libraries/Common/src/System/Runtime/Serialization/SerializationGuard.cs(20,0): at System.Runtime.Serialization.SerializationGuard.ThrowIfDeserializationInProgress(String switchSuffix, Int32& cachedValue)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1282,0): at System.Diagnostics.Process.Start()
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1352,0): at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs(470,0): at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs(118,0): at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options)
        /_/src/libraries/System.Runtime/tests/System.Runtime.Extensions.Tests/System/EnvironmentTests.cs(42,0): at System.Tests.EnvironmentTests.CurrentDirectory_SetToValidOtherDirectory()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=830089
**Error message validated:** `[System.BadImageFormatException : Method has zero rva`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 10/8/2024 2:44:13 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment]
No repro in last two months

**Comment by jkotas** [comment]
Hit again in https://github.com/dotnet/runtime/pull/111137

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by steveisok** [comment]
Doesn't appear to have been hit in a while. Reopen if you find otherwise.
