### ISSUE TITLE
`XmlSerializer` deserialize xml with  parameterless struct constructors which implement  `IXmlSerializable` will throw an exception

### ISSUE THREAD

**Issue by MauNguyenVan** [dotnet/runtime#108660]
### Description

`XmlSerializer` deserialize xml with  parameterless struct constructors which implement  `IXmlSerializable` will throw an exception

 - The Exception:
System.InvalidOperationException: 'There is an error in XML document (0, 0).'
Inner Exception
InvalidProgramException: Common Language Runtime detected an invalid program.

Note that. `XmlSerializer.Serialize()` is working well, but `XmlSerializer.Deserialize()` is not

![image](https://github.com/user-attachments/assets/73a1fe12-9a7b-4672-a80b-5ec75799efb7)

### Reproduction Steps

Try it at [Sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6ADQFsAbAbj0JPIEkB5B/Y0y2sgZQDGACwCmVAIacmPajQGiwASwk0lALwnAlAeyicA9AeBgAnniMBvPEVtE5/RSrXrFRAB61Hy1RrcBeIihRAHd7LydfVzAACmBTAAdRHQAzGP4TCEFgAAUtCSpFYEUaUQBnMoBKSs4bOwzIbLzgAqKS8rKiMsym/MKwYrBSiqJA4LCGrNy+tqGOmJq8OtsmABVRd2AAdWVBomLNnaU9sdCiBqUoAHMjwYXOOw8InxdFBRe/OI3t3cUYLp60xa/UGwyqDzspGInhoF2uo3231ub1WOjhV3uRCMMPRICIAB4APwwogAN0UZV0UH8ACJyAQaURRFBBDo4JcrrSIMAUgBaTAANhphIAfPjzoDmq0Bu0RiKiJgCQYJY0gdLQR0iCLlswAJwxHEmDmLXA6tbfABKogkcDcB2AVptASCZ3RjttsUNymuJsepIkYCIYFEgmDWlEbAARgArEPABHpSUzGVzCqVHGRV5gMgAEXKmc+9vdihqWOVAFEwGAdIGxMGQDTVnXREQlJ0JFAmVWa63OxQALIAGSIcB0ggghSg8ZiBH+BEqZBpFgMAF9l4ItCIiDFy+5BKIEto9Ez3JVl9ZcEZHkZK9Xa4pRA2mw/W+3O4o7737EOR2OJ8zp1nIh50XZdrwMFgoH9NQ4FIAB2Xd90PKk8QAYR0KgqGPQcOyuCAJCuFsLWgbRChHURimyUQ4CIDte2gpQaISasrjAAoyDAyFMH1DYyH7DoCNEE0jDXU0xNQABmAFVRVKYpRBWVOjxFgHALTRI1KMt9jELpWi7T8QmOYQgxDGsaO6VU8AvR5SAFXt43HKsAJYHMIRWKTLnjAA1VQIBbSwiEI4A6CIZilH9YougokLRJsqTJl6YFZjBBYdWsx47B8mg/IRRzgynFzEEQNyiFEs0pIcERxAkQkiAAcQooQxEkVLcEedKMpIOCgggGh6B1Mq2shKTUAAFiId05BiORi0DMMPTPIbbA6jKspywJ5red1y1KSdgHQqcAIAQTKSDgHuAaliWkgRvG5EprkZFAxCX4wEW9qdUeF7jjeZE1tEGJ/t9OxRJXIA==)  

```cs
using System;
using System.Xml;
using System.IO;
using System.Xml.Schema;
using System.Xml.Serialization;
try
{
    XmlSerializer xmlSerializer = new XmlSerializer(typeof(StructPatamerterless));

    StructPatamerterless structPatamerterless = new StructPatamerterless();

    using TextWriter textWriter = new StringWriter();
    xmlSerializer.Serialize(textWriter, structPatamerterless);
    string xmlString = textWriter.ToString(); //xmlString: <?xml version="1.0" encoding="utf-16"?>< StructPatamerterless > 1 </ StructPatamerterless >

    using TextReader textReader = new StringReader(xmlString);
    var recreateObject = (StructPatamerterless)xmlSerializer.Deserialize(textReader); // Error here:"There is an error in XML document (0, 0)."
}
catch (Exception ex)
{
    //Error here:"There is an error in XML document (0, 0)."
    //InvalidProgramException: Common Language Runtime detected an invalid program.
    Console.WriteLine(ex.Message);
}


public struct StructPatamerterless : IXmlSerializable // the same error with record struct
{
    static int currentID;
    public int Value { get; private set; }
    public StructPatamerterless()
    {
        Value = currentID++;
    }

    public XmlSchema? GetSchema()
    {
        return null;
    }

    public void ReadXml(XmlReader reader)
    {
        Value = reader.ReadElementContentAsInt();
    }

    public void WriteXml(XmlWriter writer)
    {
        writer.WriteValue(Value);
    }
}
```

### Expected behavior

The Xml content to deserialise correctly into a POCO class, without exception, in the same way as would happen if there wasn't a parameterless constructor defined.

### Actual behavior

System.InvalidOperationException
  HResult=0x80131509
  Message=There is an error in XML document (0, 0).
  Source=System.Private.Xml
  StackTrace:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at ConsoleApp.Classes.XmlSerializerWithStructParameterless.TestWith_StructPatamerterless_IXmlSerializable() in E:\Development\Console\ConsoleApp\src\ConsoleApp\Classes\XmlSerializerWithStructParameterless.cs:line 27

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidProgramException: Common Language Runtime detected an invalid program.

### Known Workarounds

.Net 8.0,
Windows 10 Pro -22H2  64 bit
VisualStudio 2022  Enterprise Version 17.11.4

### Configuration

run on Console app

**Comment by KeterSCP** [comment]
This is duplicate of https://github.com/dotnet/runtime/issues/99613

**Comment by StephenMolloy** [comment]
> This is duplicate of [#99613](https://github.com/dotnet/runtime/issues/99613)
