### ISSUE TITLE
Cannot publish android project with ReadyToRun

### ISSUE THREAD

**Issue by MaxwellDAssistek** [dotnet/runtime#109004]
### Description

When I attempt to publish an Android project (with or without MAUI) using ReadyToRun, I get an exception while building.

### Reproduction Steps

1. Create a new Android app project.
2. Add the following to the csproj file:
```
    <RunAOTCompilation>false</RunAOTCompilation>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
```
3. Run the following command: `dotnet publish -f net8.0-android -c Release -p:RuntimeIdentifier=android-arm64`

### Expected behavior

Publish should complete successfully.

### Actual behavior

```
MSBuild version 17.9.8+b34f75857 for .NET
  Determining projects to restore...
  Restored <snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj (in 279 ms).
  AndroidApp1 -> <snip>\AndroidApp1\AndroidApp1\bin\Release\net8.0-android\android-arm64\  AndroidApp1.dll
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error : Error: Object reference not set to an instance of an object. [<snip>\AndroidApp1\AndroidApp 1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.ProcessLinkerXmlBase.ProcessXml(Boolean) + 0xd9 [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1, NodeFactory, IEnumerable`1, ILProvider, DevirtualizationManager, IEnumerable`1, Logger, InstructionSetSupport) + 0x143 [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.ReadyToRunCodegenCompilation..ctor(DependencyAnalyzerBase`1, NodeFactory, IEnumerable`1, ILProvider, Logger, DevirtualizationManager, IEnumerable`1, String, InstructionSetSupport, Boolean, Boolean, Boolean, Boolean, Func`2, String, Boolean, String, Int32, Boolean, Int32, ProfileDataManager, ReadyToRunMethodLayoutAlgorithm, ReadyToRunFileLayoutAlgorithm, Int32, Boolean) + 0x1b5 [<snip>\AndroidApp1\AndroidApp1\AndroidApp 
1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() + 0x6ac [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.Program.RunSingleCompilation(Dictionary`2, InstructionSetSupport, String, Dictionary`2, HashSet`1, ReadyToRunCompilerContext, Logger) + 0x1d23 [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.Program.Run() + 0x11c6 [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj] 
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error :     at ILCompiler.Crossgen2RootCommand.<>c__DisplayClass205_0.<.ctor>b__0(ParseResult result) + 0x3e9 [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(358,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [<snip>\AndroidApp1\AndroidApp1\AndroidApp1.csproj]
```

### Configuration

.NET version 8.0.204
Windows 10

**Comment by filipnavara** [comment]
.NET on Android uses the MonoVM runtime. R2R is only available with CoreCLR runtime and it's thus NOT available on Android.

However, MonoVM does support [ahead of time compilation and profiled AOT](https://devblogs.microsoft.com/dotnet/performance-improvements-in-dotnet-maui/#profiled-aot).

**Comment by MaxwellDAssistek** [comment]
@filipnavara I am looking to dynamically load some plugins during runtime, which prevents using AOT, so I was attempting to use Ready To Run to optimize the first-load performance of these plugins.

**Comment by filipnavara** [comment]
> [@filipnavara](https://github.com/filipnavara) I am looking to dynamically load some plugins during runtime, which prevents using AOT, so I was attempting to use Ready To Run to optimize the first-load performance of these plugins.

MonoVM AOT is technically closer to how CoreCLR ReadyToRun works. It still allows dynamic code. It's NOT the same as NativeAOT that has the restrictions you are mentioning.

**Comment by MaxwellDAssistek** [comment]
> MonoVM AOT is technically closer to how CoreCLR ReadyToRun works. It still allows dynamic code. It's NOT the same as NativeAOT that has the restrictions you are mentioning.

I can't seem to find any clear instructions on how I can apply Mono AOT without Trimming being enforced.

**Comment by vitek-karas** [comment]
@simonrozsival / @jonathanpeppers is it even possible to run the mono AOT compiler without the trimmer, I don't think that would work.

That said it should be possible to "root" everything. Maybe something like TimeMode=copy if it still works.

**Comment by jonathanpeppers** [comment]
Mono's AOT compiler runs alongside the trimmer currently, so I don't know how you can use it without trimming.

See: https://github.com/dotnet/android/issues/10063

There isn't a good reason to want this combination:
* Release mode
* No trimming
* Mono's AOT

You would end up with the largest .NET Android app possible with this combination!

What I suspect the actual problem is:
* You ran into some kind of trimming issue.
* You disabled trimming completely, and that fixed it.

I would go back to enabling trimming and see if there is a problematic library causing it. You may be better off simply doing (for `MyProblemAssembly.dll`:
```
<ItemGroup>
  <TrimmerRootAssembly Include="MyProblemAssembly" RootMode="All" />
</ItemGroup>
```

You will end up with a much more reasonably sized app this way.

**Comment by vitek-karas** [comment]
The plugin scenario and trimming don't play nice together, so this will be difficult to resolve either way.

That said the default Mono AOT behavior on Android should be to only AOT the startup path in the framework. So even if the assemblies themselves are not trimmed, the AOT size cost should be more or less the same. This obviously doesn't apply if the settings are enabling full AOT, that would have really big size impact without trimming.

**Comment by jonathanpeppers** [comment]
Oh, I missed the "plugin" comment. It would be helpful if the app knew the list of plugins at build time, but maybe that isn't possible.

**Comment by MaxwellDAssistek** [comment]
That's correct. The plugin architecture that we require prevents us from knowing the full list of plugins at build time. We would like to just have each module be as optimized as possible ahead of time. On desktop ReadyToRun is a great help with this.

**Comment by vitek-karas** [comment]
There are two parts to this:
- Disable trimming so that plugins have a chance to work. This will be probably tricky to do since mobile in general assumes trimming. Using things like `TrimmerRootAssembly` is definitely a way to try. 
- AOT. The default AOT for Android is to AOT only the startup path in the framework, that approach should work regardless of trimming. If you want to enable full AOT, that will probably be tricky to get to work, because that again assumes trimming.

@jonathanpeppers maybe you know more about the details of this.

**Comment by MaxwellDAssistek** [comment]
@vitek-karas 
I would like to avoid full AOT here. I believe the much bigger immediate benefit will be from non-full AOT, which is being able to supply pre-jitted assemblies side by side with the normal bytecode ones. https://www.mono-project.com/docs/advanced/aot/

App file size is not a significant concern for us.

**Comment by vitek-karas** [comment]
The default for Android is to AOT startup paths, that should work out of the box and AFAIK should not be affected by the trimming changes. I don't think we have another AOT options between this default setup and the full AOT - Jonathan might know if there's some way it can be achieved, but it's likely not going to be simple.

**Comment by jonathanpeppers** [comment]
How are the plugins provided inside the app? Are they downloaded from the web and then loaded with `System.Reflection.Assembly`?

For AOT to work with the plugins, it has to load a native library. I think it only looks in the default locations for `.so` with the pattern of `libaot-*.dll.so`. These would either be inside the app (extractNativeLibs=false), or extracted at app install time.

I'm not sure you'll easily download and load these `.so` files dynamically at runtime.

**Comment by MaxwellDAssistek** [comment]
Correct. They are downloaded and loaded into a custom AssemblyLoadContext and potentially later unloaded.

**Comment by grendello** [comment]
Technically, .so files could be generated at build time and downloaded during application build time (although there might be restrictions to the system loader as far as allowed locations are concerned). However, this is not allowed by the [Google Play Store rules](https://support.google.com/googleplay/android-developer/answer/9888379?hl=en):

```
An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. 
Likewise, an app may not download executable code (such as dex, JAR, .so files) from a source other than Google Play. This restriction 
does not apply to code that runs in a virtual machine or an interpreter where either provides indirect access to Android APIs 
(such as JavaScript in a webview or browser).
```

The language there is a bit ambiguous, but I think that even DLL plugin files with wouldn't be allowed if downloaded from the web. 

However, they say that such dynamically downloaded code is disallowed from sources **other** than Google Play Store. It means that, in theory, you could create a [feature APK](https://developer.android.com/guide/playcore/feature-delivery) and request them dynamically from the Play Store. Once such a feature package is installed, you would probably access the DLL files as resources (e.g. with resource manager) and load them from memory, while the .so files would follow the standard patterns without any additional work required.

**Comment by MaxwellDAssistek** [comment]
What's nice about android is that there are distribution channels outside of google play, i.e. MDM variations.

Although the feature APK approach is also interesting for those requiring google play.
@grendello

**Comment by MaxwellDAssistek** [comment]
So I was able to make some progress with a few workarounds:

First of all, I was able to eliminate the original exception by adding this to my csproj:

    <ItemGroup>
        <PublishReadyToRunExclude Include="System.Private.CoreLib.dll" />
    </ItemGroup>

The next error that I am seeing is this one:

```
 C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\36.0.0-rc.1.285\tools\Xamarin.Android.Common.targets(1466,3): error XALNS7015:
      System.NotSupportedException: Writing mixed-mode assemblies is not supported
         at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
         at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
         at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
         at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
         at Xamarin.Android.Tasks.SaveChangedAssemblyStep.ProcessAssembly(AssemblyDefinition assembly, StepContext context)
         at Xamarin.Android.Tasks.AssemblyPipeline.Run(AssemblyDefinition assembly, StepContext context)
         at Xamarin.Android.Tasks.AssemblyModifierPipeline.RunPipeline(AssemblyPipeline pipeline, ITaskItem source, ITaskItem destination)
         at Xamarin.Android.Tasks.AssemblyModifierPipeline.RunTask()
         at Microsoft.Android.Build.Tasks.AndroidTask.Execute()
```

Unfortunately Mono.Cecil seems to not be able to touch R2R assemblies... There is [an alternative](https://github.com/0xd4d/dnlib) that claims to be able to but I didn't pursue this further...

I was able to work around this issue by expanding the exclude list to include all android libraries:

        <PublishReadyToRunExclude Include="SQLitePCLRaw.batteries_v2.dll" />
        <PublishReadyToRunExclude Include="SQLitePCLRaw.lib.e_sqlcipher.android.dll" />
        <PublishReadyToRunExclude Include="Xamarin.AndroidX.Core.dll" />
        <PublishReadyToRunExclude Include="Xamarin.Google.Crypto.Tink.Android.dll" />

Then I got this error:

```
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\36.0.0-rc.1.285\targets\Microsoft.Android.Sdk.AssemblyResolution.targets(198,5): error MSB4096: The item "obj\Release\net10.0-android\android-arm64\MYPROJECT.pdb" in item list "ResolvedSymbols" does not define a value for metadata "DestinationSubPath".  In order to use this metadata, either qualify it by specifying %(ResolvedSymbols.DestinationSubPath), or ensure that all items in this list define a value for this metadata.
```

Looking at Structured Log Viewer, I see that the one pdb file is not added with the right attributes:

<img width="850" height="495" alt="Image" src="https://github.com/user-attachments/assets/e214d317-6418-473a-8ba3-50fe8d77778f" />

Now, if I add the project dll itself to the exclude list, I do get a completed build, but it doesn't actually utilize ReadyToRun.

---

Now if I let go building the base application with ReadyToRun and focus on my plugin library project, I have to add a custom target to force it to actually build ReadyToRun DLLs when publishing: (In addition to excluding `System.Private.CoreLib.dll` as before)

    <Target Name="FixBuildR2R" BeforeTargets="CopyFilesToPublishDirectory;_ComputeResolvedFilesToPublishTypes;_CopyResolvedFilesToPublishPreserveNewest;_CopyResolvedFilesToPublishAlways;_HandleFileConflictsForPublish" DependsOnTargets="ComputeFilesToPublish" />

This does result in the assemblies to be published with ReadyToRun (confirmed in dotPeek), however when I dynamically load these assemblies in a normally compiled base application, I still don't any indication of ReadyToRun being utilized. I think I am hitting issue #103435 which might just mean that ReadyToRun is totally broken in .NET for this plugin based approach.

**Comment by vitek-karas** [comment]
I think there's a bit of confusion (admittedly we don't make this easy :-)):
- ReadToRun is an AOT technology used by CoreCLR, mono doesn't know anything about it. Unfortunately the SDK doesn't have guards to detect the mismatch and will (with some tweaks) do it regardless. R2R writes the AOT image into the managed assembly in such a way that mono will simply ignore it.
- Mono AOT is different from R2R, it produces .so files next to the assemblies (sort of) and in turn is not recognized by CoreCLR

I don't know if it's possible (or reasonable) to use mono AOT for this scenario - maybe @grendello would know how to trigger mono AOT on a single assembly (and make it work at runtime).

With .NET 10 RC1 you could try CoreCLR as well - it's in a preview for Android, where the usual R2R should work. Just set `<UseMonoRuntime>false</UseMonoRuntime>`. We would be interested if it works for you - even in this plugin scenario which is a bit special.

**Comment by MaxwellDAssistek** [comment]
Ahh, I guess i forgot to write up where i got to on the Mono aot approach. My bad.

I just executed mono-aot-cross manually against all my plugin assemblies, which did produce .so files. However, when actually trying to dynamically load those assemblies, i see no indication that the aot libraries are actually used. There is no change in performance and nothing related to aot in mono logs.

Looking at the source code, I think that the issue is that the aot runtime is not initialized unless the main executable is AOTed.

https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/mini-runtime.c#L4793

**Comment by MaxwellDAssistek** [comment]
@vitek-karas Its very exciting to see CoreCLR coming to android to help ease a lot of the mono limitations perhaps. However, I just tested it on the latest RC but my app just immediately crashes on startup with a segfault in `libSystem.Security.Cryptography.Native.Android.so` so looks like its still too raw. I'll try to narrow things down and make a separate issue about that.

**Comment by jonathanpeppers** [comment]
There are a few fixes related to `libSystem.Security.Cryptography.Native.Android.so` that haven't shipped yet:
* https://github.com/dotnet/android/commits/fca76a3963c5006049f3311bc3a57b2675448350?author=grendello

**Comment by MaxwellDAssistek** [comment]
> With .NET 10 RC1 you could try CoreCLR as well - it's in a preview for Android, where the usual R2R should work. Just set `<UseMonoRuntime>false</UseMonoRuntime>`. We would be interested if it works for you - even in this plugin scenario which is a bit special.

So I was able to work around the initial crashing (separate issue created), but I'm not really seeing much difference in performance between a R2R plugin and a simple one. Is there any way of concretely verifying if R2R data has been loaded for a specific assembly or if it is falling back to JIT?

Also, I am unable to use `PublishReadyToRun` on the whole application since I'm getting the `Writing mixed-mode assemblies is not supported` error on another DLL that I tried to exclude but it didn't help..

<img width="1332" height="354" alt="Image" src="https://github.com/user-attachments/assets/1d521574-3529-4b29-b020-f729ae12c1ec" />

**Comment by vitek-karas** [comment]
The failure in PublishReadToRun is weird. It's a shame we don't write out the name of the assembly it's failing on. "Mixed-mode" assemblies typically refers to C++/CLI assemblies, but those should not really work anywhere but windows, so I'm surprised they're in a mobile app.

Also - if you built for Release configuration, R2R should be enabled by default with CoreCLR. So I would expect the behavior to be the same with or without `PublishReadyToRun` specified.

**Comment by MaxwellDAssistek** [comment]
> The failure in PublishReadToRun is weird. It's a shame we don't write out the name of the assembly it's failing on. "Mixed-mode" assemblies typically refers to C++/CLI assemblies, but those should not really work anywhere but windows, so I'm surprised they're in a mobile app.

@vitek-karas Looking at the Messages section, here is the DLL it crashes on, which makes sense:

<img width="923" height="322" alt="Image" src="https://github.com/user-attachments/assets/6632bbc3-2932-459a-b83a-03ed02280082" />

**Comment by vitek-karas** [comment]
@jonathanpeppers - It's interesting that this fails only with PublishReadyToRun - I would expect we rewrite the assembly regardless of AOT solution...

**Comment by Maxwell175** [comment]
@vitek-karas The issue is simply that Mono.Cecil does not support R2R assemblies. So any assembly that need to be patched with Android Metadata stuff needs to not be R2R while it's being patched. Maybe the solution is simply to ensure that R2R generation happens after the patching.

**Comment by jonathanpeppers** [comment]
There is a refactoring of the Android build that is needed for the new runtimes. There are Android MSBuild tasks that need to properly run before ReadyToRun (and ILC in NativeAOT's case).

The example above https://github.com/dotnet/runtime/issues/109004#issuecomment-3289287540 is using a Debug (non-trimmed build)? Did you intend to use ReadyToRun there?

**Comment by MaxwellDAssistek** [comment]
> The example above [#109004 (comment)](https://github.com/dotnet/runtime/issues/109004#issuecomment-3289287540) is using a Debug (non-trimmed build)? Did you intend to use ReadyToRun there?

All my builds are with trimming disabled. For that specific test I was using a custom build configuration intended to function as "Release" hence why I attempted to use PublishReadyToRun. I noticed that in that case it is forcing me to choose a specific runtime identifier, which is, of course, not right for an Android app. However, I have since tried it using the default Release configuration (with trimming disabled), which doesn't force a specific runtime identifier (good), but it still gives me that Mono.Cecil error.
