### ISSUE TITLE
Program hangs on dotnet9 rc2

### ISSUE THREAD

**Issue by ares128** [dotnet/runtime#109172]
### Description

My program got stuck on dotnet 9 rc2 randomly, about once a day. Even Ctrl-C can not terminate the program on this situation.
but It is running ok for months on dotnet 8.

Here is dotnet version
dotnet --version
9.0.100-rc.2.24474.11

linux version(uname -a)
Linux ip-172-31-19-202 6.8.0-1017-aws #18~22.04.1-Ubuntu SMP Thu Oct  3 20:15:06 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
It is aws c7g.8xlarge.

Here is coredump backtrace.
(gdb) bt
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0,
    futex_word=0xb527a50a0d2c) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0,
    futex_word=0xb527a50a0d2c) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0xb527a50a0d2c,
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0,
    private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x0000f7c18c8cc8fc in __pthread_cond_wait_common (abstime=0x0, clockid=0,
    mutex=0xb527a50a0cd0, cond=0xb527a50a0d00) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0xb527a50a0d00, mutex=0xb527a50a0cd0)
    at ./nptl/pthread_cond_wait.c:627
#5  0x0000f7c18c62f988 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#6  0x0000f7c18c62f6dc in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#7  0x0000f7c18c633e74 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#8  0x0000f7c18c2dd548 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#9  0x0000f7c18c2d8258 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#10 0x0000f7c18c2de488 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#11 0x0000f7c18c2d6810 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#12 0x0000f7c18c5bf548 in ?? ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/9.0.0-rc.2.24473.5/libcoreclr.so
#13 0x0000f7c184301b2c in ?? ()
#14 0x84d00a98ffffff68 in ?? ()

attachment is core dump by gcore.
https://1drv.ms/u/c/6cfa9557e62383f8/EQ_vrxnyNJVCrRXYguj-FMQB3Qn4HkX42v0t2FDb-Akibg

### Reproduction Steps

None

### Expected behavior

None

### Actual behavior

hangs

**Comment by ares128** [comment]
The core file is about 114M, where can i drop it?

**Comment by mangod9** [comment]
Is there a simple repro you can provide for the issue? You can upload a dump by filing an issue here: https://developercommunity.visualstudio.com/dotnet/report.

**Comment by ares128** [comment]
Core dump Share with OneDrive
https://1drv.ms/u/c/6cfa9557e62383f8/EQ_vrxnyNJVCrRXYguj-FMQB3Qn4HkX42v0t2FDb-Akibg

**Comment by mangod9** [comment]
Thanks for sharing the dump. This issue should be fixed with https://github.com/dotnet/runtime/pull/108774 which is in the RTM build. 

@Maoni0 FYI.

**Comment by ares128** [comment]
@mangod9 Not fully addressed with RTM build, but less often.
Probably same issue as #110350.
Trying to save a coredump to share.

**Comment by mangod9** [comment]
Yeah there was another issue which we uncovered in RTM which is fixed by https://github.com/dotnet/runtime/pull/110174. You can also try the workaround to disable BGC and check if that helps.

**Comment by mangod9** [comment]
Thanks for confirming.
