### ISSUE TITLE
Test failure: JIT/Directed/StructABI/EmptyStructs/EmptyStructs.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#109269]
**Failed in:** [runtime-coreclr jitstress-random 20241027.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=854288&view=ms.vss-test-web.build-test-results-tab&runId=22190982&resultId=102847&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked jitstress_random_1 @ (Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - JIT/Directed/StructABI/EmptyStructs/EmptyStructs.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/StructABI/EmptyStructs/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true EmptyStructs.dll ''
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: {Double0:2.6845792983795817E+216}
Actual:   {Double0:1.61803}
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 174
   at Program.ShufflingThunk_PackedEmptyUintEmptyFloat_PackedEmptyDouble(Int32 a1_to_a0, Int32 a2_to_a1, Int32 a3_to_a2, Int32 a4_to_a3, Int32 a5_to_a4, Int32 a6_to_a5, Int32 a7_to_a6, Single fa0, Single fa1, PackedEmptyUintEmptyFloat stack0_stack1_to_a7_fa2, Single fa2_to_fa3, Single fa3_to_fa4, Single fa4_to_fa5, Int32 stack2_to_stack0, Single fa5_to_fa6, Single fa6_to_fa7, PackedEmptyDouble fa7_to_stack1_stack2)
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 10/27/2024 7:31:20 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/JIT/Directed/Directed_3/../StructABI/EmptyStructs/EmptyStructs.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor238|0_239(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch, PTAL.

**Comment by jakobbotsch** [comment]
Repros with
```
DOTNET_TieredCompilation=0
DOTNET_JitStress=12a
DOTNET_JitStressModeNamesAllow=STRESS_RANDOM_INLINE
DOTNET_JitStressRange=2a2bf82b
```

**Comment by jakobbotsch** [comment]
The stress mode is probably a bit of a red herring as it points to the test entry point. The problem in fact seems to be inside `ShufflingThunk_PackedEmptyUintEmptyFloat_PackedEmptyDouble`, where we end up with the following codegen:

```asm
000732      movw    r0, 0x266c
000736      movt    r0, 0x6cdf
00073A      movw    r3, 0xe373
00073E      movt    r3, 0x3ff9
000742      vmov.i2d d4, r0, r3
000746      addw    r0, sp, 37  // [V19 tmp2+0x01]
00074A      vmov.d2i r2, r3, d4
00074E      str     r2, [r0]
000750      str     r2, [r0+0x04]           // this should be "str r3, [r0+0x04]"
000752      movs    r0, 0
000754      strb    r0, [sp+0x24]       // [V19 tmp2]
000758      movw    r0, 0xffc8
00075C      movt    r0, 0xedc8
000760      movw    r3, 0xa499
000764      movt    r3, 0xf78a
000768      blx     r3          // CORINFO_HELP_NEWSFAST
00076A      mov     r4, r0
00076C      mov     r0, r4
00076E      movs    r1, 0
000770      movw    r3, 0x4210
000774      movt    r3, 0xf6d1
000778      ldr     r3, [r3]
00077A      blx     r3          // Xunit.Sdk.AssertEqualityComparer`1[Program+PackedEmptyDouble]:.ctor(System.Collections.IEqualityComparer):this
00077C      str     r4, [sp+0x08]       // [V17 OutArgs+0x08]
00077E      ldr     r0, [sp+0x24]       // [V19 tmp2]
000780      ldr     r1, [sp+0x28]       // [V19 tmp2+0x04]
000782      ldr     r2, [sp+0x2C]       // [V19 tmp2+0x08]
000784      ldr     r3, [sp+0x9C]       // [V16 arg16]
000786      ldr     lr, [sp+0xA0]       // [V16 arg16+0x04]
00078A      ldr     r12, [sp+0xA4]      // [V16 arg16+0x08]
00078E      str     lr, [sp]    // [V17 OutArgs]
000792      str     r12, [sp+0x04]      // [V17 OutArgs+0x04]
000796      movw    lr, 0x41f8
00079A      movt    lr, 0xf6d1
00079E      ldr     lr, [lr]
0007A2      blx     lr          // Xunit.Assert:Equal[Program+PackedEmptyDouble](Program+PackedEmptyDouble,Program+PackedEmptyDouble,System.Collections.Generic.IEqualityComparer`1[Program+PackedEmptyDouble])
                                                ;; size=168 bbWeight=1 PerfScore 54.00
```
where I have annotated the bad codegen.
