### ISSUE TITLE
[.NET 8] Android crash at `mono_gc_wbarrier_generic_store_internal`

### ISSUE THREAD

**Issue by akravch** [dotnet/runtime#109461]
### Android application type

.NET Android (net7.0-android, net8.0-android, etc.)

### Affected platform version

.NET 8.0.101, Android workload 34.0.52, Android NDK 26.1.10909125

### Description

Here is one of the top crashes that we are getting from production users:

```
SIGSEGV /SEGV_MAPERR

libmonosgen-2.0.so mono_gc_wbarrier_generic_store_internal
libmonosgen-2.0.so mono_gc_wbarrier_generic_store_internal
libmonosgen-2.0.so mono_gc_wbarrier_generic_store_internal
libc.so            0xf0358e24 + 986660
```

Seeing this crash for different Android versions from 6 to 14.

We were able to collect a few partial ADB logs, so I'm attaching them to the issue ([logs.zip](https://github.com/xamarin/xamarin-android/files/14085729/logs.zip)). In every log I can see a line like that:

```
TrafficStats: tagSocket(260) with statsTag=0xffffffff, statsUid=-1
```

Also sometimes there are connection related exceptions:

```
Exception caught while cancelling connection: Java.IO.IOException: Canceled
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
   at Java.Net.HttpURLConnectionInvoker.Connect()
   at Xamarin.Android.Net.AndroidMessageHandler.<>c__DisplayClass133_0.<ConnectAsync>b__0()
  --- End of managed Java.IO.IOException stack trace ---
java.io.IOException: Canceled
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:183)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
```

So it looks like network may be related somehow, although it can as well just be a coincidence since our app uses network pretty much always.

### Steps to Reproduce

No repro, only crash reports from production.

### Relevant log output

```shell
ABI: 'arm64'
Cmdline: <package-name>
pid: 6343, tid: 6400, name: SGen worker  >>> <package-name> <<<
uid: 10283
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000007349069d2c
    x0  0000000000000020  x1  000000714c299138  x2  0000007348fc0010  x3  0000000000000000
    x4  00000071ffdb0f08  x5  0000000000000004  x6  00000000ffffffff  x7  7f7f7f7f7f7f7f7f
    x8  000000714c298000  x9  0000007349040088  x10 000000000000a729  x11 0000000000000001
    x12 0000000000000000  x13 0000000040000000  x14 00000000403b8007  x15 0000000000000001
    x16 0000007223f663c8  x17 000000734a156a40  x18 000000721b0a8000  x19 0000007153c58818
    x20 0000007223f81f90  x21 000000714c299138  x22 0000007153c58620  x23 ffffffffffffffff
    x24 0000007223f81f40  x25 0000007223f81000  x26 0000007223f81000  x27 0000000000001f40
    x28 00000000000000c0  x29 00000072a25d9a70
    lr  0000007223f3b924  sp  00000072a25d9a20  pc  0000007223f3b94c  pst 0000000080001000
6 total frames
backtrace:
      #00 pc 00000000002db94c  /data/app/~~kvrjv-DLrngHaZ5pTroGYQ==/<package-name>-vyjdzyibhfKFdL8EZ9rfcg==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (offset 0x69f7000) (BuildId: 4ff0195244ee97a6b2da5b8881773c3c424a9739)
      dotnet/android#1 pc 00000000002dd92c  /data/app/~~kvrjv-DLrngHaZ5pTroGYQ==/<package-name>-vyjdzyibhfKFdL8EZ9rfcg==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (offset 0x69f7000) (BuildId: 4ff0195244ee97a6b2da5b8881773c3c424a9739)
      dotnet/android#2 pc 00000000002fbe58  /data/app/~~kvrjv-DLrngHaZ5pTroGYQ==/<package-name>-vyjdzyibhfKFdL8EZ9rfcg==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (offset 0x69f7000) (BuildId: 4ff0195244ee97a6b2da5b8881773c3c424a9739)
      dotnet/android#3 pc 00000000002faee4  /data/app/~~kvrjv-DLrngHaZ5pTroGYQ==/<package-name>-vyjdzyibhfKFdL8EZ9rfcg==/split_config.arm64_v8a.apk!libmonosgen-2.0.so (offset 0x69f7000) (BuildId: 4ff0195244ee97a6b2da5b8881773c3c424a9739)
      dotnet/android#4 pc 000000000010ba80  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: a87e89fc2c0a5753053f536add4d7ae1)
      dotnet/android#5 pc 000000000009f690  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a87e89fc2c0a5753053f536add4d7ae1)
```

**Comment by steveisok** [comment]
@BrzVlad can you please take a look at this and let me know your thoughts?

**Comment by filipnavara** [comment]
I have just been debugging a similar issue. There was a nearly identical stack trace with `mono_debugger_agent_unhandled_exception` as the one above. It turned out that the whole stack trace is incorrect and not symbolicated with the debug symbols. You can download the symbols using the `dotnet-symbol` tool and hopefully apply them in your crash reporting tool to get a correct stack trace.

It's likely that it will reveal an assert that is actually failing. In the case I investigated it was this one:
https://github.com/dotnet/runtime/blob/04538da4fc4dca4a5f1184708fe95a16dd947d17/src/mono/mono/metadata/sgen-tarjan-bridge.c#L1144

**Comment by BrzVlad** [comment]
The stacktraces above are not correct so there is not any information to go from. If you are indeed impacted by random GC related crashes you could try the workarounds from the issue linked by Filip and you could also try disabling concurrent GC: `<AndroidEnableSGenConcurrent>false</AndroidEnableSGenConcurrent>`, to see if it has any effect.

**Comment by BrzVlad** [comment]
Closing this as we've had multiple GC fixes ever since and there is no activity on this issue.
