### ISSUE TITLE
Test failure: baseservices/exceptions/unittests/TryCatchInFinally/TryCatchInFinally.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#109574]
**Failed in:** [runtime-coreclr jitstress 20241104.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=860819&view=ms.vss-test-web.build-test-results-tab&runId=22390900&resultId=110238&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked jitstress1 @ (Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - baseservices/exceptions/unittests/TryCatchInFinally/TryCatchInFinally.cmd
```

**Error message:**
```
 
Assert failure(PID 961 [0x000003c1], Thread: 961 [0x03c1]): Assertion failed 'found && "BBJ_EHFINALLYRET predecessor of block that doesn't follow a BBJ_CALLFINALLY!"' in 'TryCatchInFinallyTest:Run():int:this' during 'Optimize layout' (IL size 161; hash 0x2cbab2a8; FullOpts)

    File: /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:2875
    Image: /root/helix/work/correlation/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/baseservices/exceptions/baseservices-exceptions/../unittests/TryCatchInFinally/TryCatchInFinally.sh: line 463:   961 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/unittests/TryCatchInFinally/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true TryCatchInFinally.dll ''
[createdump] Gathering state for process 961 corerun
[createdump] Crashing thread 03c1 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.961.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.961.dmp
[createdump] Written 53108736 bytes (12966 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 70ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 11/5/2024 5:45:03 AM
Processing /home/helixbot/dotnetbuild/dumps/coredump.961.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.961.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0x3c1
      Child SP               IP Call Site
 0xffd9bbb0 0xf78c7654 libc.so.6!
 0xffd9bbb8 0xf7931a00 libc.so.6!__wait4_time64
 0xffd9bc20 0xf77c1d8e libcoreclr.so!PROCCreateCrashDump(std::vector<char const*, std::allocator<char const*> >&, char*, int, bool) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2308:22
 0xffd9bc68 0xf77c2b90 libcoreclr.so!PROCCreateCrashDumpIfEnabled at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2526:9
 0xffd9bcb8 0xf77c0278 libcoreclr.so!PROCAbort at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2559:5
 (inlined by) RaiseFailFastException at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:1276:14
 0xffd9bcd0 0xf7695080 libcoreclr.so!_DbgBreakCheckNoThrow(char const*, int, char const*, int) at /__w/1/s/src/coreclr/utilcode/debug.cpp:300:0
 0xffd9bcd8 0xf7694f06 libcoreclr.so!SBuffer::~SBuffer() at /__w/1/s/src/coreclr/inc/sbuffer.inl:206:9
 (inlined by) _DbgBreakCheck at /__w/1/s/src/coreclr/utilcode/debug.cpp:293:1
 0xffd9cd58 0xf74087e0 libcoreclr.so!CEEInfo::doAssert(char const*, int, char const*) at /__w/1/s/src/coreclr/vm/jitinterface.cpp:0:0
 0xffd9cda0 0xedf849ee libclrjit.so!assertAbort at /__w/1/s/src/coreclr/jit/error.cpp:286:9
 0xffd9edf0 0xedf941a2 libclrjit.so!BBPredsChecker::CheckEHFinallyRet(BasicBlock*, BasicBlock*) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:0:5
 0xffd9ee38 0xedf93e20 libclrjit.so!BBPredsChecker::CheckJump(BasicBlock*, BasicBlock*) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:2785:13
 0xffd9ee68 0xedf93a42 libclrjit.so!BBPredsChecker::CheckBBPreds(BasicBlock*, unsigned int) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:2677:9
 0xffd9eea0 0xedf94822 libclrjit.so!Compiler::fgDebugCheckBBlist(bool, bool) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:3066:44
 0xffd9ef00 0xee0d9a24 libclrjit.so!Phase::PostPhase(PhaseStatus) at /__w/1/s/src/coreclr/jit/phase.cpp:192:9
 0xffd9ef28 0xee0d9890 libclrjit.so!Phase::Run() at /__w/1/s/src/coreclr/jit/phase.cpp:0:5
 0xffd9ef68 0xedf6992c libclrjit.so!CompilerPhaseWithStatus:
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor158|0_159(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by amanasifkhalid** [comment]
This is failing across platforms. I suspect 3-opt isn't being careful about keeping call-finally pairs together when picking partition points. Will take a look.

**Comment by amanasifkhalid** [comment]
For the asserting method, before running 3-opt, we have a call-finally pair on the hot/cold block boundary like so:
```
BB28 [0007]  1       BB27                  1      2 [???..???)-> BB30(1)                 (callf )                     i LIR IBC internal
BB29 [0008]  1       BB46                  0      0 [???..???)-> BB47(1)                 (callfr)                     i LIR IBC rare internal xentry
```

Since `BB28` is the last hot block, 3-opt will try partitioning after it, which can split up the call-finally pair. The simplest solution is to ensure the entire call-finally pair is included in the hot section if only the first half is hot. This ensures the pair will move together as 3-opt reorders blocks.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20241105.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=862209&view=ms.vss-test-web.build-test-results-tab&runId=22432748&resultId=111924&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked jitstress2 @ (Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - baseservices/exceptions/unittests/TryCatchInFinally/TryCatchInFinally.cmd
```

**Error message:**
```
 
Assert failure(PID 960 [0x000003c0], Thread: 960 [0x03c0]): Assertion failed 'found && "BBJ_EHFINALLYRET predecessor of block that doesn't follow a BBJ_CALLFINALLY!"' in 'TryCatchInFinallyTest:Run():int:this' during 'Optimize layout' (IL size 161; hash 0x2cbab2a8; FullOpts)

    File: /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:2875
    Image: /root/helix/work/correlation/corerun

waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/baseservices/exceptions/baseservices-exceptions/../unittests/TryCatchInFinally/TryCatchInFinally.sh: line 463:   960 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/unittests/TryCatchInFinally/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true TryCatchInFinally.dll ''
[createdump] Gathering state for process 960 corerun
[createdump] Crashing thread 03c0 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.960.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.960.dmp
[createdump] Written 53063680 bytes (12955 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 74ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 11/6/2024 5:35:25 AM
Processing /home/helixbot/dotnetbuild/dumps/coredump.960.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.960.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0x3c0
      Child SP               IP Call Site
 0xff9436d8 0xf7587654 libc.so.6!
 0xff9436e0 0xf75f1a00 libc.so.6!__wait4_time64
 0xff943748 0xf7481216 libcoreclr.so!PROCCreateCrashDump(std::vector<char const*, std::allocator<char const*> >&, char*, int, bool) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2308:22
 0xff943790 0xf7482018 libcoreclr.so!PROCCreateCrashDumpIfEnabled at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2526:9
 0xff9437e0 0xf747f700 libcoreclr.so!PROCAbort at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2559:5
 (inlined by) RaiseFailFastException at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:1276:14
 0xff9437f8 0xf7354480 libcoreclr.so!_DbgBreakCheckNoThrow(char const*, int, char const*, int) at /__w/1/s/src/coreclr/utilcode/debug.cpp:300:0
 0xff943800 0xf7354306 libcoreclr.so!SBuffer::~SBuffer() at /__w/1/s/src/coreclr/inc/sbuffer.inl:206:9
 (inlined by) _DbgBreakCheck at /__w/1/s/src/coreclr/utilcode/debug.cpp:293:1
 0xff944880 0xf70c85a0 libcoreclr.so!CEEInfo::doAssert(char const*, int, char const*) at /__w/1/s/src/coreclr/vm/jitinterface.cpp:0:0
 0xff9448c8 0xedc449ee libclrjit.so!assertAbort at /__w/1/s/src/coreclr/jit/error.cpp:286:9
 0xff946918 0xedc541a2 libclrjit.so!BBPredsChecker::CheckEHFinallyRet(BasicBlock*, BasicBlock*) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:0:5
 0xff946960 0xedc53e20 libclrjit.so!BBPredsChecker::CheckJump(BasicBlock*, BasicBlock*) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:2785:13
 0xff946990 0xedc53a42 libclrjit.so!BBPredsChecker::CheckBBPreds(BasicBlock*, unsigned int) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:2677:9
 0xff9469c8 0xedc54822 libclrjit.so!Compiler::fgDebugCheckBBlist(bool, bool) at /__w/1/s/src/coreclr/jit/fgdiagnostic.cpp:3066:44
 0xff946a28 0xedd99a2c libclrjit.so!Phase::PostPhase(PhaseStatus) at /__w/1/s/src/coreclr/jit/phase.cpp:192:9
 0xff946a50 0xedd99898 libclrjit.so!Phase::Run() at /__w/1/s/src/coreclr/jit/phase.cpp:0:5
 0xff946a90 0xedc2992c libclrjit.so!CompilerPhaseWithStatus:
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor158|0_159(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
