### ISSUE TITLE
IndexOutOfRangeException when using one-shot AES decrypt with empty array

### ISSUE THREAD

**Issue by tipa** [dotnet/runtime#109658]
### Description

Calling `DecryptCbc` on the `AesAlgorithm` with an empty array (but a correctly sized initialization vector) throws an `IndexOutOfRangeException`.

### Reproduction Steps

```
var iv = Enumerable.Range(0, 16).Select(i => (byte)i).ToArray();
var resutlt = Aes.Create().DecryptCbc(Array.Empty<byte>(), iv);
```

### Expected behavior

I would have expected something like `System.Security.Cryptography.CryptographicException: The input data is not a complete block.` or an empty array, which is what the "non-oneshot" decryption returns:

```
var ms = new MemoryStream();
using var algorithm = Aes.Create();
algorithm.IV = iv.ToArray();
using (var encryptor = algorithm.CreateDecryptor())
{
    using var cs = new CryptoStream(ms, encryptor, CryptoStreamMode.Write, true);
    cs.Write(data.ToArray(), 0, data.Length);
}
return ms.ToArray();
```

### Actual behavior

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Security.Cryptography.SymmetricPadding.GetPaddingLength(ReadOnlySpan`1 block, PaddingMode paddingMode, Int32 blockSize)
   at System.Security.Cryptography.UniversalCryptoOneShot.OneShotDecrypt(ILiteSymmetricCipher cipher, PaddingMode paddingMode, ReadOnlySpan`1 input, Span`1 output, Int32& bytesWritten)
   at System.Security.Cryptography.AesImplementation.TryDecryptCbcCore(ReadOnlySpan`1 ciphertext, ReadOnlySpan`1 iv, Span`1 destination, PaddingMode paddingMode, Int32& bytesWritten)
   at System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(ReadOnlySpan`1 ciphertext, ReadOnlySpan`1 iv, PaddingMode paddingMode)
   at System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(Byte[] ciphertext, Byte[] iv, PaddingMode paddingMode)
```

### Known Workarounds

I can manually check for the input array length

### Configuration

.NET 9 RC2

**Comment by vcsjones** [comment]
Thanks for the report! This will be fixed in .NET 10.
