### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#109630]
**Failed in:** [runtime-coreclr libraries-jitstress 20241106.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=863290&view=ms.vss-test-web.build-test-results-tab&runId=22462276&resultId=131519&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 48
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20241122.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877421&view=ms.vss-test-web.build-test-results-tab&runId=22895180&paneView=debug&resultId=133389)

**Failed tests:**
```
net10.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
Assert.Equal() Failure: Strings differ
↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 48
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20241125.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879319&view=ms.vss-test-web.build-test-results-tab&runId=22966130&resultId=134749&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-x64-tailcallstress-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20241228.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=903660&view=ms.vss-test-web.build-test-results-tab&runId=23756192&resultId=135288&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-x64-jitstress_random_1-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by jeffhandley** [comment]
Assigned to @adamsitnik for triage

**Comment by adamsitnik** [comment]
Triage: it seems that reading a process name on Linux makes some of our tests flaky (#109630, #110643, #111460). 

@jkotas has suggested in https://github.com/dotnet/runtime/issues/111460#issuecomment-2608999432 that we maybe reading it too soon. I am going to try to add a simple retry mechanism to see if it helps.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250302.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=967110&view=ms.vss-test-web.build-test-results-tab&runId=25771504&resultId=151743&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-x64-jitminopts-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20250303.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=968343&view=ms.vss-test-web.build-test-results-tab&runId=25805580&resultId=142796&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-x64-jitstress2_tiered-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 48
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20250420.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1021374&view=ms.vss-test-web.build-test-results-tab&runId=27358584&resultId=172459&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-x64-fullpgo_random_gdv_edge-Ubuntu.2204.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList
```

**Error message:**
```
 Assert.Equal() Failure: Strings differ
           ↓ (pos 0)
Expected: "sleep"
Actual:   ".NET Long Runni"
           ↑ (pos 0)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.ProcessStart_OnLinux_UsesSpecifiedProgramUsingArgumentList() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 377
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 126
```
