### ISSUE TITLE
First class span's break EFC

### ISSUE THREAD

**Issue by Suchiman** [dotnet/runtime#109757]
### Description

When enabling `LangVersion` `preview`, that enables first class span's which then prefers `MemoryExtensions.Contains` over `Enumerable.Contains` which then breaks EFC. It seems that EFC internally calls `Expression.Compile` with `preferInterpretation` set to `true` which then eventually crashes.

### Reproduction Steps

```csharp
public class MyDbContext : DbContext
{
    public DbSet<MyTable> MyTable { get; set; }
}

public class MyTable
{
    public int Id { get; set; }
    public string Name { get; set; }
}

string[] filters = ["Test"];

var dbContext = new MyDbContext();
dbContext.MyTable.Where(x => filters.Contains(x.Name)).ToList();
```

### Expected behavior

First class span's should not negatively affect EFC queries

### Actual behavior

```
TypeLoadException: GenericArguments[1], 'System.Span`1[System.String]', on 'System.Linq.Expressions.Interpreter.FuncCallInstruction`2[T0,TRet]' violates the constraint of type parameter 'TRet'.
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Linq.Expressions.Interpreter.CallInstruction.GetHelperType(MethodInfo info, Type[] arrTypes)
   at System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(MethodInfo info, ParameterInfo[] pis)
   at System.Linq.Expressions.Interpreter.CallInstruction.Create(MethodInfo info, ParameterInfo[] parameters)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression(Expression object, MethodInfo method, IArgumentProvider arguments)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileTop(LambdaExpression node)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionTreeFuncletizer.<Evaluate>g__EvaluateCore|70_0(Expression expression, String& parameterName, Boolean& isContextAccessor) in Microsoft.EntityFrameworkCore.Query.Internal\ExpressionTreeFuncletizer.cs:line 1755
```

### Regression?

Yes, only when enabling `<LangVersion>preview</LangVersion>`

### Known Workarounds

set `<LangVersion>preview</LangVersion>` to anything but preview

### Configuration

.NET 9.0.0
EFC 9.0.0

**Comment by jkotas** [comment]
cc @jjonescz

**Comment by ChrisJollyAU** [comment]
@Suchiman Which version of VS are you on? 17.13 Preview 1?

I've just come across this when building the tests on efcore (same problem with MemoryExtesions.* vs IEnumerable.*) To me it only happened on 17.13 preview 1 AND `LangVersion` is `preview`. Using 17.12 even with LangVersion on `preview` it was fine to build

**Comment by Suchiman** [comment]
> [@Suchiman](https://github.com/Suchiman) Which version of VS are you on? 17.13 Preview 1?

yes

**Comment by ilGianfri** [comment]
I've attached a simple repro application [ConsoleApp2.zip](https://github.com/user-attachments/files/17784692/ConsoleApp2.zip)

On Visual Studio 17.12 it works, in 17.13p1 I get this issue with both .NET 8 and .NET 9 if LangVersion is set to preview

**Comment by ChrisJollyAU** [comment]
Any relation to https://github.com/dotnet/runtime/issues/96160 ?

**Comment by jjonescz** [comment]
This was discussed [at LDM](https://github.com/dotnet/csharplang/blob/b9456cd15242f657e548c6afaf949fc0fbaaac0a/meetings/2024/LDM-2024-12-04.md#conversions-in-expression-trees) with no change in the C# language planned. LINQ-to-DB should be probably updated to recognize `MemoryExtensions.Contains` (and perhaps other similar methods) or users will need to update the calls (e.g., calling `Enumerable.Contains` explicitly, or casting the array to `IEnumerable<T>`).

**Comment by GerardSmit** [comment]
Does this mean libraries need to fix this issue?

In that case it would mean .NET 9 (or lower) can never use the new C# LangVersion together with EF Core when First class span's get released? 
You will either need to lower the C# LangVersion or upgrade .NET.

I know using newer C# LangVersions in older .NET versions isn't official supported, but I do this together with PolySharp a lot.

When I upgraded my .NET SDK locally, I got hit by this issue; since I had `<LangVersion>preview</LangVersion>` in my project during the .NET 7 to .NET 8 transition, I forgot I had the preview version still configured 😄.

**Comment by jjonescz** [comment]
> In that case it would mean .NET 9 (or lower) can never use the new C# LangVersion together with EF Core when First class span's get released?

You can use .NET 9, just make sure you call `Enumerable` methods (e.g., by calling them in their non-expanded static forms) instead of `MemoryExtensions` ones. As you said, older .NETs are not supported with newer LangVersions, so workarounds like that are expected.

**Comment by roji** [comment]
Just to second @jkotas's comment, our problem in EF is not recognizing MemoryExtensions.Contains and similar (though that in itself is also a breaking change) - it's the reliance on the LINQ interpreter in various scenarios, but the interpreter doesn't support this. More generally, there's a gap that's starting to widen between C# itself and its metaprogramming (and related) features: the interpreter can no longer handle any construct, and LINQ expression trees themselves only represent a small subset of C# (and getting smaller). This will become more and more problematic, unless a decision is made to start updating these components to bring them more in line with the latest C# developments.

**Comment by jjonescz** [comment]
> It can be fixed in System.Linq.Expressions by adding support for byref-like types to the Interpreter, but that is in conflict with the [effectively archived status](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Linq.Expressions#systemlinqexpressions-library) of System.Linq.Expressions.

That doc says "We will consider changes that address significant bugs or regressions". This seems like a significant regression.

> our problem in EF is [...] the reliance on the LINQ interpreter in various scenarios, but the interpreter doesn't support this.

So... does EF need to implement its own interpreter to avoid relying on an archived component?

**Comment by ChrisJollyAU** [comment]
@jjonescz There's already 2 issues previously related to byref-like types and Span types in expression trees (#96160 and #27499). Both have basically said the same as @jkotas - that `System.Linq.Expressions` is effectively archived.

With the new first class span support being introduced, it's clear that there would be an increasing likelihood of more expression trees encountering the byref-like types. With this in mind, I feel the impact of that bug has changed enough to at the very least needing to be re-evaluated (and possibly implemented)

**Comment by GerardSmit** [comment]
A hacky workaround is to make an ExpressionVisitor that converts all the `MemoryExtensions.Contains` to `Enumerable.Contains`.

[SharpLab link](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwBYBuYsyvAOgBlYBHekiqtz5gFEAHgAdkAUwDOUqAHsYU7oz4AlCQDMANhIDGCeTG4M8pANoBdchqhaEE5FPIBecmYBEAFWkJ3F7iLi0rIKADxYAKyhALIAnp4QwDpw5MBycloAfJnWtvbILuTCLjk2dg5SzADCCgjQigAUwswAchBgEgCUxkQA9L3kNWAdMAjkcqhjCAAWEuQwEsJjWrBzCHLkurO6ANbkM3OLuhKiBgrEZfmFAMqiEDCecoIwqB3IiToAalCy68jVCgAbg4EA1Lg5usQGFE4gkkhIUmkMqV0LpCuD/kNRLYJA0ghoHABJUYOIJ1M4wED7NBdbhIrTkSRSVB2dGohoLADu5FhHzmAG9yG0OoUvD53OQAL6QojEJkshDMAAir1EDRlDAAzJQcDz4nziPziOQTZRtVQKMKBeQAOYSBC0chSe2OyXEN2yoiwfIwCAM3DkW73R7PV4OPnfX5yApUwJMkIwSNQP6G42m8RQQEQexMABsjIkEAAJgotLFA3cHk8Xm8Iz9k9HyMSpHUYMdClz1T1TeQM1mc1R85Ji6Xy9F7dM5EXiRoNjVRvUpEGYIUELFRBI5BoGuOwNHYiJ7IpDFJOswAOL28czKcNNM9k3ued1WBSdxwe8PgBCsCLsBtABiWgQDalQAAqoEkUBohg5A/jAf4wIBwGgcw1zktBH5EA+povFoWhYThJpmGuG5bg06jFgA8jAZbLqEmRntEEA7BIl4LMg0GeOuuLcRuzDMax7EONB16TkWYEQO8HT5A0pCdJ0KR8RIAksWxEgcaJE5TpJ0n2g4cmdBYhFEXhWifp0ACE3bppx/ZzIOBYjrRY7adOMCzoMtSLqGtbwquPHkb54bwmel4IGJt6fj2T7ea+77Raa8GIchIHgZBKwwXBv7/kBaVoRhugmThZnFQ+JGBduVCagxTFqcJnG6MpDTKapQkaSJuiRRJUntPpyCGYp5CtYJ6maV1bm6X1snycZiUmmZFnWVC2G2XI9j6BIRbjMCyCcUWcxxsEhjkEmEVuVUfpaDuF1XUdMgnTAU5dJ+RqrThUAaOQHLPQJbnMISUgNVpN7bQAZGD80Pk9B1/aDF72sDE2g0qmiwMmhjqi4rjPouy7kBDUM9jDKndQjCBIwAgsgNphqMUhYz8bhZgUpESFYhPvURC2/dTtMjAgUhmKQVhM91l34fdCbkIKZNWlS7hyKIAD6hJgKImXJhKkqbHdYjxidnPcz2uh60ED0KMwfN04LwsWMwynY/sPFtRI1PvPEPHqp0UNvcbppYAA7OQUuGNUV13lz/smrjr7Be88Ku0j3UNGzilE0RoeW/Ou2gqbkv68dlvWwLQsiykbPkdVtVJx1jXNWn6dR9HJNWzTNtC3gFgZyaMrcx6UNB6kEDOswZ3ixHJN96aA9c1g5p4PmnheTAuehJ4mQteQizmwmnTkJysySMN5CxoXFsrs4OQtZ0zatscY/1qCO8GwoMoekAA=)

<details>
  <summary>Code</summary>
  
  The ExpressionVisitor:
  
  ```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

internal class SpanToEnumerableVisitor : ExpressionVisitor
{
    private static readonly SpanToEnumerableVisitor Instance = new();

    private static readonly MethodInfo ContainsSpan = typeof(MemoryExtensions).GetMethod(
        "Contains",
        BindingFlags.Public | BindingFlags.Static,
        null,
        [typeof(ReadOnlySpan<>).MakeGenericType(Type.MakeGenericMethodParameter(0)), Type.MakeGenericMethodParameter(0)],
        null
    )!;

    private static readonly MethodInfo ContainsEnumerable = typeof(Enumerable).GetMethod(
        "Contains",
        BindingFlags.Public | BindingFlags.Static,
        null,
        [typeof(IEnumerable<>).MakeGenericType(Type.MakeGenericMethodParameter(0)), Type.MakeGenericMethodParameter(0)],
        null
    )!;

    protected override Expression VisitMethodCall(MethodCallExpression node)
    {
        if (node.Method.IsGenericMethod &&
            node.Method.GetGenericMethodDefinition() == ContainsSpan &&
            node.Method.GetGenericArguments() is [var type] &&
            node.Arguments[0] is MethodCallExpression { Method.Name: "op_Implicit" } callExpression &&
            callExpression.Arguments[0].Type == type.MakeArrayType())
        {
            return Expression.Call(
                ContainsEnumerable.MakeGenericMethod(type),
                Expression.Convert(callExpression.Arguments[0], typeof(IEnumerable<>).MakeGenericType(type)),
                node.Arguments[1]
            );
        }

        return base.VisitMethodCall(node);
    }

    public static T Convert<T>(T expression) where T : Expression => (T)Instance.Visit(expression);
}
  ```

  Example:
```cs
string[] filters = ["Test"];
Expression<Func<MyTable, bool>> filter = x => filters.Contains(x.Name);

// Comment out the next line to check the exception
filter = SpanToEnumerableVisitor.Convert(filter);

Func<MyTable, bool> func = filter.Compile(preferInterpretation: true);
bool result = func(new MyTable { Name = "Test" });

Console.WriteLine(result);
```
  
</details>

**Comment by jkotas** [comment]
> @jjonescz There's already 2 issues previously related to byref-like types and Span types in expression trees 

+ https://github.com/dotnet/runtime/issues/110592 that was just filled

**Comment by roji** [comment]
> A hacky workaround is to make an ExpressionVisitor that converts all the MemoryExtensions.Contains to Enumerable.Contains.

Yep, that's likely the workaround we'd do in EF for this.

**Comment by ChrisJollyAU** [comment]
While `.Contains` is the method giving the current problem, you would probably have to look at doing it for all methods from `MemoryExtensions`

**Comment by roji** [comment]
@ChrisJollyAU indeed.

**Comment by ChrisJollyAU** [comment]
@jjonescz @jkotas Was also thinking on this.

EFC calls the `.Compile` with `preferInterpretation` being true.

With the function being as follows
```
public new TDelegate Compile(bool preferInterpretation)
{
    if (CanInterpret && preferInterpretation)
    {
        return (TDelegate)(object)new Interpreter.LightCompiler().CompileTop(this).CreateDelegate();
    }

    return Compile();
}
```

Clearly the `CanInterpret` variable is also true, even when the expression has the byref-like types/Span in it. Giving that the interpret fails it clearly can't interpret. That's a potential bug/mismatch there.

Even if the byref-like types wasn't added to the interpreter (if the verdict from the other mentioned issues is still valid now), I would say this part would be applicable - to make sure that the `CanConvert` is false if you have those types in the expression.

@roji This should satisfy you with regards to performance - those normal expressions will just be interpreted as normal, and then drop into the full compiler (which does work) for the restricted types

**Comment by jjonescz** [comment]
> This needs a breaking change notice to be filled.

Filed https://github.com/dotnet/docs/issues/43952.

> Even if the byref-like types wasn't added to the interpreter

It seems this would also require adding support for ref structs in reflection since the interpreter is using reflection under the hood.

> Clearly the `CanInterpret` variable is also true, even when the expression has the byref-like types/Span in it. Giving that the interpret fails it clearly can't interpret. That's a potential bug/mismatch there.

This sounds like a potentially good solution to me - avoid interpretation if the expression tree contains spans. But is it possible to do compilation everywhere or is it necessary to fall back to interpretation in some cases (e.g., on some platforms)?

**Comment by jkotas** [comment]
> This sounds like a potentially good solution to me - avoid interpretation if the expression tree contains spans. But is it possible to do compilation everywhere or is it necessary to fall back to interpretation in some cases (e.g., on some platforms)?

This does not work for native AOT that [EF Core has been busy adding support for](https://github.com/dotnet/efcore/issues?q=is%3Aissue%20state%3Aopen%20label%3Aarea-aot%20).

**Comment by jkotas** [comment]
> It seems this would also require adding support for ref structs in reflection since the interpreter is using reflection under the hood.

Yes, adding support for ref structs in reflection has been on [the reflection backlog](https://github.com/dotnet/runtime/issues/10057) for a while. So far we did not have a good motivating scenario to justify investing into it.

**Comment by roji** [comment]
@ChrisJollyAU and others, I think the EF strategy for dealing with this will be to perform early detect and replacing of expression nodes that cannot be interpreted, basically transforming the new tree back to the way it was - before the LINQ interpreter is ever invoked. In other words, we'd have a static, hard-coded table in EF's funcletizer (the very first visitor that processes the incoming the tree), and would simply rewrite the tree. So from a pure EF perspective, we'll likely be able to deal with this without any need to either disable interpretation, or something like CanInterpret.

Do you see any trouble with that approach @ChrisJollyAU?

Regardless, this will affect other users of the LINQ interpreter. I'm not sure CanInterpret would be very useful to them, and I'm generally not in love with "magically" switching between interpretation and compilation based on something that the user has no knowledge or control over (i.e. there's a performance cliff the moment you introduce a Contains, or possibly other discrepancies). I'd at least want to discuss this with other users of the interpreter first...

> I think it's just performance reasons that EFC uses the interpreter. The expressions are evaluated only once so was faster with the interpreter than with the compilation and its overheads. @roji Any other reasons for using the interpreter?

Yep, that was the reason, nothing else.

**Comment by PeteMWilson** [comment]
It seems ironic to me that the LDM decision for this is that breaking old code that uses EF is okay when the common refrain when discussing adding new operators (e.g. ??) to `Expression` is that it breaks using EF in newer code that isn't written yet.

**Comment by CypherPotato** [comment]
In .NET 10, `Contains` changed from being `Enumerable.Contains` to being `MemoryExtensions.Contains` by default, which is breaking all EF Linq queries that use Contains in the code. I have a huge codebase and it's causing conflicts in several places. Is there a workaround for this for now? A workaround that doesn't require casting every .Contains in my codebase

```csharp
var totalPendencies = db.Pendencies.Count(p => (p.RequestingUserId == authUser.Id || p.RespondingUserId == authUser.Id || Pendency.GetDepartmentsForUser(authUser).Contains(p.TargetDepartment)) && p.Status == PendencyStatus.Open);
```

```
At /v2/index
Exception thrown at Thu, 13 Nov 2025 10:19:16 GMT
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. See the inner exception for more information. To show additional information call 'DbContextOptionsBuilder.EnableSensitiveDataLogging'.
 ---> System.ArgumentException: GenericArguments[1], 'System.ReadOnlySpan`1[BeYouSmile.Model.PendencyDepartment]', on 'System.Linq.Expressions.Interpreter.FuncCallInstruction`2[T0,TRet]' violates the constraint of type 'TRet'.
 ---> System.TypeLoadException: GenericArguments[1], 'System.ReadOnlySpan`1[BeYouSmile.Model.PendencyDepartment]', on 'System.Linq.Expressions.Interpreter.FuncCallInstruction`2[T0,TRet]' violates the constraint of type parameter 'TRet'.
   at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] typeArguments)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] typeArguments)
   at System.Linq.Expressions.Interpreter.CallInstruction.GetHelperType(MethodInfo info, Type[] arrTypes)
   at System.Linq.Expressions.Interpreter.CallInstruction.SlowCreate(MethodInfo info, ParameterInfo[] pis)
   at System.Linq.Expressions.Interpreter.CallInstruction.Create(MethodInfo info, ParameterInfo[] parameters)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression(Expression object, MethodInfo method, IArgumentProvider arguments)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileTop(LambdaExpression node)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.Internal.ExpressionTreeFuncletizer.<Evaluate>g__EvaluateCore|75_0(Expression expression, String& parameterName, Boolean& isContextAccessor)
   --- End of inner exception stack trace ---
```

**Comment by viceroypenguin** [comment]
> For everyone encountering this issue after upgrading the target framework to `net10.0` but not upgrading their EF to 10 - Upgrade your EF to 9.0.11 and it will stop breaking

https://github.com/dotnet/efcore/issues/35100#issuecomment-3522080449

**Comment by CypherPotato** [comment]
> > For everyone encountering this issue after upgrading the target framework to `net10.0` but not upgrading their EF to 10 - Upgrade your EF to 9.0.11 and it will stop breaking
> 
> [dotnet/efcore#35100 (comment)](https://github.com/dotnet/efcore/issues/35100#issuecomment-3522080449)

Didn't worked for me.

```
System.InvalidOperationException: An exception was thrown while attempting to evaluate a LINQ query parameter expression. See the inner exception for more information. To show additional information call 'DbContextOptionsBuilder.EnableSensitiveDataLogging'.
 ---> System.ArgumentException: GenericArguments[1], 'System.ReadOnlySpan`1[BeYouSmile.Model.AppointmentStatus]', on 'System.Linq.Expressions.Interpreter.FuncCallInstruction`2[T0,TRet]' violates the constraint of type 'TRet'.
 ---> System.TypeLoadException: GenericArguments[1], 'System.ReadOnlySpan`1[BeYouSmile.Model.AppointmentStatus]', on 'System.Linq.Expressions.Interpreter.FuncCallInstruction`2[T0,TRet]' violates the constraint of type parameter 'TRet'.
```

Package references:
```xml
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
<PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="2.0.7" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Json.Newtonsoft" Version="9.0.0" />
```

Maybe is the Pomelo lib the culprit?

**Comment by ChrisJollyAU** [comment]
@CypherPotato Have you tried setting LangVersion to 13 yet?

**Comment by CypherPotato** [comment]
> [@CypherPotato](https://github.com/CypherPotato) Have you tried setting LangVersion to 13 yet?

Nope, but after doing that, it **solved the issue** for now.

```xml
<TargetFramework>net10.0</TargetFramework>
<LangVersion>13</LangVersion>
```

Thank you for the tip. I don't think it is a proper fix, but a workaround for now.

**Comment by ChrisJollyAU** [comment]
> Thank you for the tip. I don't think it is a proper fix, but a workaround for now.

Its about the best at the moment. It works because first class spans were introduced in c# 14. So setting it to 13 is before that. The only downside is you can't use any new c# 14 (and future version) features

**Comment by jjonescz** [comment]
If the error is caused by using a ReadOnlySpan during evaluation of the expression (which seems to be the case from the exception trace), a workaround can be defining your own `Contains` extension method which C# will bind to instead of `MemoryExtensions.Contains`, for example, (assuming your receiver is an `T[]`):

```cs
static class Extensions
{
    public static bool Contains(this T[] array, T item) => Enumerable.Contains(array, item);
}
```

And you can continue using C# 14 with this.

**Comment by CypherPotato** [comment]
> If the error is caused by using a ReadOnlySpan during evaluation of the expression (which seems to be the case from the exception trace), a workaround can be defining your own `Contains` extension method which C# will bind to instead of `MemoryExtensions.Contains`, for example, (assuming your receiver is an `T[]`):
> 
> static class Extensions
> {
>     public static bool Contains(this T[] array, T item) => Enumerable.Contains(array, item);
> }
> And you can continue using C# 14 with this.

Tried this, but doens't work on EF. It claims that cannot translate the user-defined Contains method.

**Comment by jjonescz** [comment]
> Tried this, but doens't work on EF. It claims that cannot translate the user-defined Contains method.

But EF Core was updated to be able to handle `MemoryExtensions.Contains` afaik. You've mentioned that you are using another library, so likely that one is the culprit.

We would need a minimal reproducible example to investigate further I think.

**Comment by CypherPotato** [comment]
> > Tried this, but doens't work on EF. It claims that cannot translate the user-defined Contains method.
> 
> But EF Core was updated to be able to handle `MemoryExtensions.Contains` afaik. You've mentioned that you are using another library, so likely that one is the culprit.
> 
> We would need a minimal reproducible example to investigate further I think.

[There you go.](https://github.com/CypherPotato/Issue109757Repro)

**Comment by jjonescz** [comment]
Thanks. You are using EFCore v9, that does not seem to have the fix; if you update to v10, there is no crash.

**Comment by ChrisJollyAU** [comment]
@jjonescz Actually it was ported back to v9 and v8 https://github.com/dotnet/efcore/pull/35719 and https://github.com/dotnet/efcore/pull/35720

I was having a look and whats happened is there is a specific case that gets overlooked.

Normally efcore only can manage a `Contains` when there is no EqualityComparer. But for some reason `.Contains(bp.State)` in your code gets to using the `MemoryExtensions.Contains` overload that does take an EqualityComparer even though you didnt specify one. The value in this case is `null` That is why it is jumping over that and doesnt switch it back to the `Enumerable.Contains`

**Comment by jjonescz** [comment]
^ @roji

(still, using EFCore v10 works, so I guess just the backports are incomplete?)

**Comment by ChrisJollyAU** [comment]
@jjonescz @roji 

See https://github.com/dotnet/efcore/issues/35547 and its resulting PR https://github.com/dotnet/efcore/pull/36057

The changes of that weren't backported

**Comment by CypherPotato** [comment]
> Thanks. You are using EFCore v9, that does not seem to have the fix; if you update to v10, there is no crash.

I'm using Pomelo MySQL, which doens't runs on EFCore v10, so I will just sit down here and wait for Pomelo update their lib to v10.

**Comment by gurustron** [comment]
> I'm using Pomelo MySQL, which doens't runs on EFCore v10, so I will just sit down here and wait for Pomelo update their lib to v10.

@CypherPotato 

Please see https://stackoverflow.com/a/79820634/2501279

1. Have you tried downgrading language version as suggested before? I.e.:
    ```
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>13</LangVersion>
    </PropertyGroup>
    ```
2. Also you can try explicitly using `Enumerable.Contains`:

    ```c#
    dbContext.MyTable.Where(x => Enumerable.Contains(filters, x.Name)).ToList();
    ````
3. Finally you can try using another type for the variable:

    ```c#
    IReadOnlyCollection<string> filters = ["Test"];

    var dbContext = new MyDbContext();
    dbContext.MyTable.Where(x => filters.Contains(x.Name)).ToList();
    ```

**Comment by roji** [comment]
@ChrisJollyAU thanks for looking into this, and @CypherPotato thanks for reporting. I've opened https://github.com/dotnet/efcore/issues/37176 to backport the fix to EF 8 and 9, and will try to do this ASAP for the upcoming patch releases. In the meantime, you can either upgrade to EF 10 (which already has the fix) or stay on C# 13 as suggested above.

As I don't think there's anything actionable remaining with this issue, I'll go ahead and close it. But feel free to continue posting and we can reopen if needed.
