### ISSUE TITLE
One time mass coreclr asan failure in HTTP stress tests

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#109824]
All 3 jobs failed during coreclr startup in the following run, detecting various asan failures:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=867571

HTTP/3 failed in the client, while for 1.1/2.0 the failures happenned in the Kestrel process.

Copying the HTTP/3 stack traces as an example:

<details>

```
=================================================================
==9==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x61a000067280
    #0 0x7ffba59d36a8 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
    #1 0x7ffba4002da0 in FreeTHREAD(CorUnix::CPalThread*) /repo/src/coreclr/pal/src/thread/thread.cpp:231
    #2 0x7ffba4002da0 in CorUnix::CPalThread::ReleaseThreadReference() /repo/src/coreclr/pal/src/thread/thread.cpp:2172
    #3 0x7ffba4002da0 in ThreadCleanupRoutine(CorUnix::CPalThread*, CorUnix::IPalObject*, bool, bool) /repo/src/coreclr/pal/src/thread/thread.cpp:2459
    #4 0x7ffba3fe91c3 in CorUnix::CPalObjectBase::ReleaseReference(CorUnix::CPalThread*) /repo/src/coreclr/pal/src/objmgr/palobjbase.cpp:307
    #5 0x7ffba3fdf5c2 in CorUnix::CSimpleHandleManager::FreeHandle(CorUnix::CPalThread*, void*) /repo/src/coreclr/pal/src/handlemgr/handlemgr.cpp:245
    #6 0x7ffba3fdf12d in CorUnix::InternalCloseHandle(CorUnix::CPalThread*, void*) /repo/src/coreclr/pal/src/handlemgr/handleapi.cpp:305
    #7 0x7ffba3fdf12d in CloseHandle /repo/src/coreclr/pal/src/handlemgr/handleapi.cpp:280
    #8 0x7ffba3c63e0a in Thread::DecExternalCount(int) /repo/src/coreclr/vm/threads.cpp:2261
=================================================================
==9==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x61a000067280
    #0 0x7ffba59d36a8 in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52
    #1 0x7ffba4002da0 in FreeTHREAD(CorUnix::CPalThread*) /repo/src/coreclr/pal/src/thread/thread.cpp:231
    #2 0x7ffba4002da0 in CorUnix::CPalThread::ReleaseThreadReference() /repo/src/coreclr/pal/src/thread/thread.cpp:2172
    #3 0x7ffba4002da0 in ThreadCleanupRoutine(CorUnix::CPalThread*, CorUnix::IPalObject*, bool, bool) /repo/src/coreclr/pal/src/thread/thread.cpp:2459
    #4 0x7ffba3fe91c3 in CorUnix::CPalObjectBase::ReleaseReference(CorUnix::CPalThread*) /repo/src/coreclr/pal/src/objmgr/palobjbase.cpp:307
    #5 0x7ffba3fdf5c2 in CorUnix::CSimpleHandleManager::FreeHandle(CorUnix::CPalThread*, void*) /repo/src/coreclr/pal/src/handlemgr/handlemgr.cpp:245
    #6 0x7ffba3fdf12d in CorUnix::InternalCloseHandle(CorUnix::CPalThread*, void*) /repo/src/coreclr/pal/src/handlemgr/handleapi.cpp:305
    #7 0x7ffba3fdf12d in CloseHandle /repo/src/coreclr/pal/src/handlemgr/handleapi.cpp:280
    #8 0x7ffba3c63e0a in Thread::DecExternalCount(int) /repo/src/coreclr/vm/threads.cpp:2261
    #9 0x7ffba3c64d24 in Thread::CleanupDetachedThreads() /repo/src/coreclr/vm/threads.cpp:2626
    #10 0x7ffba3c691fb in Thread::DoExtraWorkForFinalizer() /repo/src/coreclr/vm/threads.cpp:6964
    #11 0x7ffba3cd7487 in FinalizerThread::FinalizerThreadWorker(void*) /repo/src/coreclr/vm/finalizerthread.cpp:353
    #12 0x7ffba3c6945c in ManagedThreadBase_DispatchInner(ManagedThreadCallState*) /repo/src/coreclr/vm/threads.cpp:7032
    #13 0x7ffba3c6945c in ManagedThreadBase_DispatchMiddle(ManagedThreadCallState*) /repo/src/coreclr/vm/threads.cpp:7076
    #14 0x7ffba3c6945c in ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_0::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const::{lambda(Param*)#1}::operator()(Param*) const /repo/src/coreclr/vm/threads.cpp:7234
    #15 0x7ffba3c6945c in ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_0::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const /repo/src/coreclr/vm/threads.cpp:7236
    #16 0x7ffba3c6945c in ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) /repo/src/coreclr/vm/threads.cpp:7260
    #17 0x7ffba3c6945c in ManagedThreadBase_Dispatch(void (*)(void*), void*, UnhandledExceptionLocation) /repo/src/coreclr/vm/threads.cpp:7277
    #18 0x7ffba3cd7597 in FinalizerThread::FinalizerThreadStart(void*) /repo/src/coreclr/vm/finalizerthread.cpp:398
    #19 0x7ffba4003bbd in CorUnix::CPalThread::ThreadEntry(void*) /repo/src/coreclr/pal/src/thread/thread.cpp:1658
    #20 0x7ffba54a31c3  (/lib/x86_64-linux-gnu/libc.so.6+0x891c3)
    #21 0x7ffba5522abf in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x108abf)

0x61a000067280 is located 0 bytes inside of 1328-byte region [0x61a000067280,0x61a0000677b0)
allocated by thread T9 here:
    #0 0x7ffba59d5780 in operator new(unsigned long, std::nothrow_t const&) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:101
    #1 0x7ffba4002f0a in AllocTHREAD() /repo/src/coreclr/pal/src/thread/thread.cpp:206
    #2 0x7ffba4003475 in CorUnix::InternalCreateThread(CorUnix::CPalThread*, _SECURITY_ATTRIBUTES*, unsigned int, unsigned int (*)(void*), void*, unsigned int, CorUnix::PalThreadType, unsigned long*, void**) /repo/src/coreclr/pal/src/thread/thread.cpp:575
    #3 0x7ffba4003706 in PAL_CreateThread64 /repo/src/coreclr/pal/src/thread/thread.cpp:482
    #4 0x7ffba3c6417f in Thread::CreateNewOSThread(unsigned long, unsigned int (*)(void*), void*) /repo/src/coreclr/vm/threads.cpp:2109
    #5 0x7ffba3c640c1 in Thread::CreateNewThread(unsigned long, unsigned int (*)(void*), void*, char16_t const*) /repo/src/coreclr/vm/threads.cpp:1934
    #6 0x7ffba3cb0c37 in ThreadNative_Start /repo/src/coreclr/vm/comsynchronizable.cpp:252
    #7 0x7ffb24c349ab  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x2249ab)
    #8 0x7ffb24c518c3  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x2418c3)
    #9 0x7ffb24c4db5d  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x23db5d)
    #10 0x7ffb24c5531c  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x24531c)
    #11 0x7ffb24c5bf2a  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x24bf2a)
    #12 0x7ffb24c58119  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x248119)
    #13 0x7ffb250063f9  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x5f63f9)
    #14 0x7ffb26048b2c  (/memfd:doublemapper (deleted)+0x789b2c)
    #15 0x7ffb26048606  (/memfd:doublemapper (deleted)+0x789606)
    #16 0x7ffb260480d7  (/memfd:doublemapper (deleted)+0x7890d7)
    #17 0x7ffb26046ca1  (/memfd:doublemapper (deleted)+0x787ca1)
    #18 0x7ffb2604693f  (/memfd:doublemapper (deleted)+0x78793f)
    #19 0x7ffb2604689b  (/memfd:doublemapper (deleted)+0x78789b)
    #20 0x7ffb26046833  (/memfd:doublemapper (deleted)+0x787833)
    #21 0x7ffb26043930  (/memfd:doublemapper (deleted)+0x784930)
    #22 0x7ffb260432e1  (/memfd:doublemapper (deleted)+0x7842e1)
    #23 0x7ffb260431cf  (/memfd:doublemapper (deleted)+0x7841cf)
    #24 0x7ffb2604316a  (/memfd:doublemapper (deleted)+0x78416a)
    #25 0x7ffb26041297  (/memfd:doublemapper (deleted)+0x782297)
    #26 0x7ffb2604055d  (/memfd:doublemapper (deleted)+0x78155d)
    #27 0x7ffb259f1b3f  (/memfd:doublemapper (deleted)+0x1a2b3f)
    #28 0x7ffb259f1a1f  (/memfd:doublemapper (deleted)+0x1a2a1f)
    #29 0x7ffb259f19b6  (/memfd:doublemapper (deleted)+0x1a29b6)

Thread T5 created by T0 here:
    #0 0x7ffba5965726 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7ffba4003602 in CorUnix::InternalCreateThread(CorUnix::CPalThread*, _SECURITY_ATTRIBUTES*, unsigned int, unsigned int (*)(void*), void*, unsigned int, CorUnix::PalThreadType, unsigned long*, void**) /repo/src/coreclr/pal/src/thread/thread.cpp:692
    #2 0x7ffba4003706 in PAL_CreateThread64 /repo/src/coreclr/pal/src/thread/thread.cpp:482
    #3 0x7ffba3c6417f in Thread::CreateNewOSThread(unsigned long, unsigned int (*)(void*), void*) /repo/src/coreclr/vm/threads.cpp:2109
    #4 0x7ffba3c640c1 in Thread::CreateNewThread(unsigned long, unsigned int (*)(void*), void*, char16_t const*) /repo/src/coreclr/vm/threads.cpp:1934
    #5 0x7ffba3cd7715 in FinalizerThread::FinalizerThreadCreate() /repo/src/coreclr/vm/finalizerthread.cpp:462
    #6 0x7ffba3fa7f4f in EEStartupHelper() /repo/src/coreclr/vm/ceemain.cpp:928
    #7 0x7ffba3fa76a1 in EEStartup()::$_0::operator()(void*) const /repo/src/coreclr/vm/ceemain.cpp:1087
    #8 0x7ffba3fa76a1 in EEStartup() /repo/src/coreclr/vm/ceemain.cpp:1089
    #9 0x7ffba3fa7565 in EnsureEEStarted() /repo/src/coreclr/vm/ceemain.cpp:303
    #10 0x7ffba3bac6bb in CorHost2::Start() /repo/src/coreclr/vm/corhost.cpp:100
    #11 0x7ffba3b6fbd8 in coreclr_initialize /repo/src/coreclr/dlls/mscoree/exports.cpp:310
    #12 0x7ffba4c45fb0 in coreclr_t::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, coreclr_property_bag_t const&, std::unique_ptr<coreclr_t, std::default_delete<coreclr_t> >&) /repo/src/native/corehost/hostpolicy/coreclr.cpp:72
    #13 0x7ffba4c618af in (anonymous namespace)::create_coreclr() /repo/src/native/corehost/hostpolicy/hostpolicy.cpp:75
    #14 0x7ffba4c612c3 in corehost_main /repo/src/native/corehost/hostpolicy/hostpolicy.cpp:422
    #15 0x7ffba502e24c  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/host/fxr/10.0.0/libhostfxr.so+0x2024c)
    #16 0x7ffba502d2a7  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/host/fxr/10.0.0/libhostfxr.so+0x1f2a7)
    #17 0x7ffba5027251 in hostfxr_main_startupinfo (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/host/fxr/10.0.0/libhostfxr.so+0x19251)
    #18 0x564f5e807782  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/dotnet+0x7782)
    #19 0x564f5e807a5e  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/dotnet+0x7a5e)
    #20 0x7ffba5441249  (/lib/x86_64-linux-gnu/libc.so.6+0x27249)

Thread T9 created by T0 here:
    #0 0x7ffba5965726 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7ffba4003602 in CorUnix::InternalCreateThread(CorUnix::CPalThread*, _SECURITY_ATTRIBUTES*, unsigned int, unsigned int (*)(void*), void*, unsigned int, CorUnix::PalThreadType, unsigned long*, void**) /repo/src/coreclr/pal/src/thread/thread.cpp:692
    #2 0x7ffba4003706 in PAL_CreateThread64 /repo/src/coreclr/pal/src/thread/thread.cpp:482
    #3 0x7ffba3c6417f in Thread::CreateNewOSThread(unsigned long, unsigned int (*)(void*), void*) /repo/src/coreclr/vm/threads.cpp:2109
    #4 0x7ffba3c640c1 in Thread::CreateNewThread(unsigned long, unsigned int (*)(void*), void*, char16_t const*) /repo/src/coreclr/vm/threads.cpp:1934
    #5 0x7ffba3cb0c37 in ThreadNative_Start /repo/src/coreclr/vm/comsynchronizable.cpp:252
    #6 0x7ffb24c349ab  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x2249ab)
    #7 0x7ffb24c518c3  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x2418c3)
    #8 0x7ffb24c4db5d  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/System.Private.CoreLib.dll+0x23db5d)
    #9 0x7ffb259efee2  (/memfd:doublemapper (deleted)+0x1a0ee2)
    #10 0x7ffb259ef7bb  (/memfd:doublemapper (deleted)+0x1a07bb)
    #11 0x7ffb259ef75d  (/memfd:doublemapper (deleted)+0x1a075d)
    #12 0x7ffb259eed29  (/memfd:doublemapper (deleted)+0x19fd29)
    #13 0x7ffb259eeb2a  (/memfd:doublemapper (deleted)+0x19fb2a)
    #14 0x7ffb259eea7b  (/memfd:doublemapper (deleted)+0x19fa7b)
    #15 0x7ffb259eea2b  (/memfd:doublemapper (deleted)+0x19fa2b)
    #16 0x7ffb259ee62b  (/memfd:doublemapper (deleted)+0x19f62b)
    #17 0x7ffb259ed9ff  (/memfd:doublemapper (deleted)+0x19e9ff)
    #18 0x7ffb259ec401  (/memfd:doublemapper (deleted)+0x19d401)
    #19 0x7ffb259ec152  (/memfd:doublemapper (deleted)+0x19d152)
    #20 0x7ffb259ec0af  (/memfd:doublemapper (deleted)+0x19d0af)
    #21 0x7ffb259ec046  (/memfd:doublemapper (deleted)+0x19d046)
    #22 0x7ffb259ea41f  (/memfd:doublemapper (deleted)+0x19b41f)
    #23 0x7ffb259ea123  (/memfd:doublemapper (deleted)+0x19b123)
    #24 0x7ffb259ea06f  (/memfd:doublemapper (deleted)+0x19b06f)
    #25 0x7ffb259ea002  (/memfd:doublemapper (deleted)+0x19b002)
    #26 0x7ffb259e9e92  (/memfd:doublemapper (deleted)+0x19ae92)
    #27 0x7ffb259e9d63  (/memfd:doublemapper (deleted)+0x19ad63)
    #28 0x7ffb259e377c  (/memfd:doublemapper (deleted)+0x19477c)
    #29 0x7ffb259e3323  (/memfd:doublemapper (deleted)+0x194323)
    #30 0x7ffb259e3041  (/memfd:doublemapper (deleted)+0x194041)
    #31 0x7ffb259e0fd7  (/memfd:doublemapper (deleted)+0x191fd7)
    #32 0x7ffb259e2f2f  (/memfd:doublemapper (deleted)+0x193f2f)
    #33 0x7ffb259e0fd7  (/memfd:doublemapper (deleted)+0x191fd7)
    #34 0x7ffb259e2001  (/memfd:doublemapper (deleted)+0x193001)
    #35 0x7ffb259e134a  (/memfd:doublemapper (deleted)+0x19234a)
    #36 0x7ffb259e11b1  (/memfd:doublemapper (deleted)+0x1921b1)
    #37 0x7ffb259e111f  (/memfd:doublemapper (deleted)+0x19211f)
    #38 0x7ffb259e10b8  (/memfd:doublemapper (deleted)+0x1920b8)
    #39 0x7ffb259e0fd7  (/memfd:doublemapper (deleted)+0x191fd7)
    #40 0x7ffb259d25a4  (/memfd:doublemapper (deleted)+0x1835a4)
    #41 0x7ffb259d2403  (/memfd:doublemapper (deleted)+0x183403)
    #42 0x7ffb259d2347  (/memfd:doublemapper (deleted)+0x183347)
    #43 0x7ffb259d1d23  (/memfd:doublemapper (deleted)+0x182d23)
    #44 0x7ffb259d1bab  (/memfd:doublemapper (deleted)+0x182bab)
    #45 0x7ffb259d1b0f  (/memfd:doublemapper (deleted)+0x182b0f)
    #46 0x7ffb259d1ab9  (/memfd:doublemapper (deleted)+0x182ab9)
    #47 0x7ffb259cd8a3  (/memfd:doublemapper (deleted)+0x17e8a3)
    #48 0x7ffb259cd117  (/memfd:doublemapper (deleted)+0x17e117)
    #49 0x7ffb259cd099  (/memfd:doublemapper (deleted)+0x17e099)
    #50 0x7ffb259cd041  (/memfd:doublemapper (deleted)+0x17e041)
    #51 0x7ffb259cc7b3  (/memfd:doublemapper (deleted)+0x17d7b3)
    #52 0x7ffb259ca5cb  (/memfd:doublemapper (deleted)+0x17b5cb)
    #53 0x7ffb259ca3b2  (/memfd:doublemapper (deleted)+0x17b3b2)
    #54 0x7ffb259ca31b  (/memfd:doublemapper (deleted)+0x17b31b)
    #55 0x7ffb259ca2cc  (/memfd:doublemapper (deleted)+0x17b2cc)
    #56 0x7ffb259c3304  (/memfd:doublemapper (deleted)+0x174304)
    #57 0x7ffb259c3183  (/memfd:doublemapper (deleted)+0x174183)
    #58 0x7ffb259c30fb  (/memfd:doublemapper (deleted)+0x1740fb)
    #59 0x7ffb259c30b8  (/memfd:doublemapper (deleted)+0x1740b8)
    #60 0x7ffb259c2fd3  (/memfd:doublemapper (deleted)+0x173fd3)
    #61 0x7ffb259afdf2  (/memfd:doublemapper (deleted)+0x160df2)
    #62 0x7ffb259ae987  (/memfd:doublemapper (deleted)+0x15f987)
    #63 0x7ffb259ae8fb  (/memfd:doublemapper (deleted)+0x15f8fb)
    #64 0x7ffb259ae874  (/memfd:doublemapper (deleted)+0x15f874)
    #65 0x7ffb25981b00  (/memfd:doublemapper (deleted)+0x132b00)
    #66 0x7ffb259819d3  (/memfd:doublemapper (deleted)+0x1329d3)
    #67 0x7ffb2598194b  (/memfd:doublemapper (deleted)+0x13294b)
    #68 0x7ffb25981908  (/memfd:doublemapper (deleted)+0x132908)
    #69 0x7ffb2598187d  (/memfd:doublemapper (deleted)+0x13287d)
    #70 0x7ffba3e53dc3  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/shared/Microsoft.NETCore.App/10.0.0/libcoreclr.so+0x4b5dc3)
    #71 0x7ffba3c9b60b in CallDescrWorkerWithHandler(CallDescrData*, int) /repo/src/coreclr/vm/callhelpers.cpp:63
    #72 0x7ffba3c9b60b in MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) /repo/src/coreclr/vm/callhelpers.cpp:585
    #73 0x7ffba3b82b64 in MethodDescCallSite::Call_RetArgSlot(unsigned long const*) /repo/src/coreclr/vm/callhelpers.h:465
    #74 0x7ffba3b82b64 in RunMainInternal(Param*) /repo/src/coreclr/vm/assembly.cpp:1223
    #75 0x7ffba3b82b64 in RunMain(MethodDesc*, short, int*, PtrArray**)::$_0::operator()(Param*) const::{lambda(Param*)#1}::operator()(Param*) const /repo/src/coreclr/vm/assembly.cpp:1291
    #76 0x7ffba3b82b64 in RunMain(MethodDesc*, short, int*, PtrArray**)::$_0::operator()(Param*) const /repo/src/coreclr/vm/assembly.cpp:1293
    #77 0x7ffba3b82b64 in RunMain(MethodDesc*, short, int*, PtrArray**) /repo/src/coreclr/vm/assembly.cpp:1293
    #78 0x7ffba3b82fbb in Assembly::ExecuteMainMethod(PtrArray**, int) /repo/src/coreclr/vm/assembly.cpp:1419
    #79 0x7ffba3bacab3 in CorHost2::ExecuteAssembly(unsigned int, char16_t const*, int, char16_t const**, unsigned int*) /repo/src/coreclr/vm/corhost.cpp:349
    #80 0x7ffba3b6ee1f in coreclr_execute_assembly /repo/src/coreclr/dlls/mscoree/exports.cpp:494
    #81 0x7ffba4c5ff07 in run_app_for_context(hostpolicy_context_t const&, int, char const**) /repo/src/native/corehost/hostpolicy/hostpolicy.cpp:250
    #82 0x7ffba4c6025f in run_app(int, char const**) /repo/src/native/corehost/hostpolicy/hostpolicy.cpp:285
    #83 0x7ffba4c612d5 in corehost_main /repo/src/native/corehost/hostpolicy/hostpolicy.cpp:426
    #84 0x7ffba502e24c  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/host/fxr/10.0.0/libhostfxr.so+0x2024c)
    #85 0x7ffba502d2a7  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/host/fxr/10.0.0/libhostfxr.so+0x1f2a7)
    #86 0x7ffba5027251 in hostfxr_main_startupinfo (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/host/fxr/10.0.0/libhostfxr.so+0x19251)
    #87 0x564f5e807782  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/dotnet+0x7782)
    #88 0x564f5e807a5e  (/live-runtime-artifacts/testhost/net10.0-linux-Release-x64/dotnet+0x7a5e)
    #89 0x7ffba5441249  (/lib/x86_64-linux-gnu/libc.so.6+0x27249)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:52 in __interceptor_free
==9==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==9==ABORTING
HttpStress failed, copying artifacts for investigation
```

</details>

Given it's a one-off failure so far (and in that case it happenned consistently in independent runs which can be a sign of some kind of CI anomaly) I'm not sure it's worth to worry about, opening the issue just in case.

Unfortunately, the published dumps [seem to be empty](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867571&view=artifacts&pathAsName=false&type=publishedArtifacts); @rzikm any idea why?

**Comment by rzikm** [comment]
I believe this was fixed by https://github.com/dotnet/runtime/pull/109753, as it does not happen anymore

**Comment by jkoritzinsky** [comment]
Yes it was fixed by my PR.
