### ISSUE TITLE
System.DirectoryServices.AccountManagement Version 9.0: UserPrincipal.GetAuthorizationGroups() throws  System.UriFormatException: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by uwer62** [dotnet/runtime#109858]
### Description

After updating from 8.0.1 to 9.0.0 the call above throws the following exception:
 System.UriFormatException: Invalid URI: The hostname could not be parsed.

### Reproduction Steps
```
var ctx = new PrincipalContext(ContextType.Domain);
var usersearcher = new PrincipalSearcher(new UserPrincipal(ctx));
var users = usersearcher.FindAll().Cast<UserPrincipal>();
var user = users.FirstOrDefault(e => e.SamAccountName == "valid user name");
var groupList = user?.GetAuthorizationGroups().ToList(); <== throws in 9.0.0
```

### Expected behavior

This call should return the groups as the older versions

### Actual behavior

Throws unexpected exception

### Regression?

Yes. worked in 8.0.1

### Known Workarounds

downgrade to 8.0.1

### Configuration

.NET 8.0 and .NET 9.0 on Windows 11

**Comment by jasasa** [comment]
I have the same issue with GetGroups(). Works in 8.0, not in 9.0. 
If I include the name of the domain in the PrincipalContext-call, it works:
`var ctx = new PrincipalContext(ContextType.Domain, "domainname"); `

**Comment by ericstj** [comment]
No repro for me with the given code sample I get the same results from both package versions.  Could you please share the full details of the exception and callstack?  Could you confirm what runtime are you using - .NET 8.0 or .NET 9.0? Thanks.

**Comment by uwer62** [comment]
I have created a new console application (.NET 9.0) and added the code I mentioned to Program.cs.
Here is the full code:
```
// See https://aka.ms/new-console-template for more information
using System.DirectoryServices.AccountManagement;

Console.WriteLine("Hello, World!");
var ctx = new PrincipalContext(ContextType.Domain);
var usersearcher = new PrincipalSearcher(new UserPrincipal(ctx));
var users = usersearcher.FindAll().Cast<UserPrincipal>();
var user = users.FirstOrDefault(e => e.SamAccountName == "Here I used a valid user name in our domain");
var groupList = user?.GetAuthorizationGroups().ToList();
Console.WriteLine(groupList.Count.ToString());

```
Then I added System.DirectoryServices.AccountManagetment 9.0.0 and ran the code
The exception is thrown in the following line:
`var user = users.FirstOrDefault(e => e.SamAccountName == "Here I used a valid user name in our domain");`

HResult: -2146233033 
Message: Invalid URI: The hostname could not be parsed.
Source: System.Private.Uri
Stack Trace:
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.DirectoryServices.AccountManagement.ADStoreCtx.LoadDomainInfo()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.get_DnsDomainName()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOfAZ(Principal p)
   at System.DirectoryServices.AccountManagement.UserPrincipal.GetAuthorizationGroupsHelper()
   at System.DirectoryServices.AccountManagement.UserPrincipal.GetAuthorizationGroups()
   at Program.<Main>$(String[] args) in C:\Users\ur\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 9

**Comment by uwer62** [comment]
I can confirm @jasasa's comment that the problem goes away if I add the name of our domain to the following line:
` var ctx = new PrincipalContext(ContextType.Domain, "our domain name");`

**Comment by steveharter** [comment]
Appears to be introduced by https://github.com/dotnet/runtime/pull/89787/files#diff-36ef1673850535f3dd5645a5b990a17652b2eaff381d3abaed74fc29278665afR2421

**Comment by steveharter** [comment]
@kumarravik78c is it possible you can provide a fix for this? Thanks

**Comment by steveharter** [comment]
The simplest fix is to call `Uri.CheckSchemeName()` before using the Uri constructor. I can prep a PR.

**Comment by steveharter** [comment]
> If I include the name of the domain in the PrincipalContext-call, it works:
var ctx = new PrincipalContext(ContextType.Domain, "domainname"); 

@jasasa @uwer62 do you have examples of what was throwing?

I verified that this throws:
```LDAP://CN=John Doe,CN=Users```
while this does not:
```LDAP://myserver.local:12345/CN=John Doe, CN=Users```

**Comment by uwer62** [comment]
@steveharter Currently I only have the example and stack trace I had posted above. Are you looking for something specific?

**Comment by steveharter** [comment]
The next v10 build will have this fix; we should get validation from the community before porting to v9. cc @uwer62 @jasasa

**Comment by uwer62** [comment]
@steveharter Sorry for the question, but how could we test this?

**Comment by steveharter** [comment]
Re-opening for v9

**Comment by steveharter** [comment]
> @steveharter Sorry for the question, but how could we test this?

If it is possible for you to run v10 code + say a command prompt test then install the nightly SDK+runtime build from https://github.com/dotnet/sdk/blob/main/documentation/package-table.md and in your VS project set up a nuget feed to `https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet10/nuget/v3/index.json`. The nuget feed is necessary since the `System.Directory.Services.AccountManagement` package is OOB. You may also need a newer version of Visual Studio (I'm using 17.13.0 Preview 1.0).

If that is not possible, the dogfooding instructions may be useful: https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md.

Also, I did manually verify the nightly drop of build 10.0.0-alpha.1.24577.3 of the `System.Directory.Services.AccountManagement` package in contains the fix (in `System.Directory.Services.AccountManagement.dll` for windows).

**Comment by vc-74** [comment]
Same issue here and I confirm using the `PrincipalContext` constructor overload with an explicit domain name fixes it.

**Comment by michaelmairegger** [comment]
As @uwer62 says, specifying the domain name works. Here I provide a more complete example in order to not hard-code the domain name:

    var currentUserPrincipal = UserPrincipal.Current;

    var ctx = new PrincipalContext(ContextType.Domain, currentUserPrincipal.Context.ConnectedServer);
    var userPrincipal = UserPrincipal.FindByIdentity(ctx, currentUserPrincipal.Sid.Value);
    var groups = userPrincipal.GetGroups();
    // or
    var authorizationGroups = userPrincipal.GetAuthorizationGroups();

**Comment by uwer62** [comment]
I can confirm that @StefanBertels workaround solves the problem for version 9.0.1 of the Nuget (the one I tested with).

**Comment by the-black-wolf** [comment]
Just to add to the context, there is an issue in running this code now on Domain Controllers too. 

The workaround using `new PrincipalContext(ContextType.Domain);` and `new PrincipalContext(ContextType.Domain, currentUserPrincipal.Context.ConnectedServer)` do not work, the code refuses to connect to itself on Domain Controller via directory services, 

however when the context is obtained via `new PrincipalContext(ContextType.Machine)` it loads the domain context. 

I feel this should be somehow normalized and made transparent, context should be loaded either way on DC.

**Comment by the-black-wolf** [comment]
Just to add to the context, there is an issue in running this code now on Domain Controllers too.

The workaround using new `PrincipalContext(ContextType.Domain);` and `new PrincipalContext(ContextType.Domain, currentUserPrincipal.Context.ConnectedServer)` and even using helperContext woraround do not work, the code always says the `Invalid URI....`

It only works when the context is obtained via `new PrincipalContext(ContextType.Machine)` and it loads the domain machine's context, which is empty essentially as DC uses domain context for its operations, so this is useless. 

There does not appear to be a way to obtain a PrincipalContext on the domain controller now (this did work before). 

I feel this should be somehow normalized and made transparent and operative in the course of fixing this bug, context should be loaded on DC the same as on any other domain machine, the application should not have to deal with this specially.

**Comment by filipnavara** [comment]
@steveharter Is there anything left to be done? The fix landed both on .NET 10 and .NET 9 service release.

**Comment by ericstj** [comment]
@uwer62 @maxima120 - the fix to this issue shipped in https://github.com/dotnet/runtime/pull/110224 package version 9.0.2.  Could you let us know if that resolves the issue?

**Comment by maxima120** [comment]
it works in v 9.0.2 .. 5 thank you for fixing it !
