### ISSUE TITLE
Hardware intrinsic throw ArgumentOutOfRangeException with IMM parameter name

### ISSUE THREAD

**Issue by fiigii** [dotnet/runtime#10982]
Now, some hardware intrinsic can throw `ArgumentOutOfRangeException` from the IMM arguments.
```csharp
 Avx.Compare(Avx.SetZeroVector256<float>(), Avx.SetZeroVector256<float>(), (FloatComparisonMode)100);
```
```
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Runtime.Intrinsics.X86.Avx.Compare(Vector256`1 left, Vector256`1 right, FloatComparisonMode mode)
   at SseTest.Program.Main(String[] args) in D:\workspace\tests\testIntrinsic\Program.cs:line 14
```

We may need to bring the IMM parameter name in the exception object.

Logged from the conversation https://github.com/dotnet/coreclr/pull/19392#discussion_r213050260

@tannergooding @CarolEidt 

category:implementation
theme:hardware-intrinsics
skill-level:beginner
cost:small

**Comment by VMikulasek** [comment]
This issue seems outdated, the parameter name is already in exception object everywhere in [intrinsics subdirectory](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics). The repo got restructured since this issue was created, but the `Avx2.cs` file referenced by the [referenced issue comment](https://github.com/dotnet/coreclr/pull/19392#discussion_r213050260) now lives at [this path](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Avx2.cs).

**Comment by VMikulasek** [comment]
@tannergooding sorry for the ping. Unless I'm missing something, it should be safe to close this issue.

**Comment by tannergooding** [comment]
This hasn't been resolved as the managed source and JIT implementation differ. However, it also isn't really a "core need" to have the `ParamName` property populated and we've had it implemented this way since v1.0.

I'm going to go ahead and close this as by-design, at least until some real world need crops up that shows why this is necessary for these edge case scenarios.
