### ISSUE TITLE
WASM AOT fails with regex in .NET 9

### ISSUE THREAD

**Issue by voroninp** [dotnet/runtime#109862]
### Description

I am playing with Blazor and discovered that for some reason publishing application as WASM AOT breaks it one way or another.

Here is [the repo](https://github.com/voroninp/DutchVerbs)

If I use regular (not source generated regex with `NonBacktracing` option, application fails at startup.

Here is an example of the log I see in browser console. (including debug logs from Mono):
[voroninp.github.io-1731573811462.log](https://github.com/user-attachments/files/17775046/voroninp.github.io-1731573811462.log)

If I remove `NonBacktracking` application start without any issue.

When I [switch to source generated regex](https://github.com/voroninp/DutchVerbs/blob/6475c0a15e15173f6a8184f108e22c86a4235bc7/DutchVerbs.Spa/Infrastructure/Application.cs#L115), I have another error:
```
ManagedError: AggregateException_ctor_DefaultMessage (NoMetadataForType, System.Object, DutchVerbs.Spa.Infrastructure.SourceGenerationContext Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
    at sn (dotnet.runtime.o8gq1i8bk6.js:3:26894)
    at Kt.resolve_or_reject (dotnet.runtime.o8gq1i8bk6.js:3:26449)
    at dotnet.runtime.o8gq1i8bk6.js:3:172526
    at dotnet.runtime.o8gq1i8bk6.js:3:172590
    at fr (dotnet.runtime.o8gq1i8bk6.js:3:35046)
    at Fc (dotnet.runtime.o8gq1i8bk6.js:3:172173)
    at dotnet.native.sn79jhuo16.wasm:0x360233
    at dotnet.native.sn79jhuo16.wasm:0x36c10f
    at dotnet.native.sn79jhuo16.wasm:0x64a937
    at dotnet.native.sn79jhuo16.wasm:0x91fccc
``` 

P.S. I was asked to create a new issue by @vitek-karas [here](#99030)

### Reproduction Steps

Visit [this url](https://voroninp.github.io/DutchVerbs/) to see the error, or play with the repository https://github.com/voroninp/DutchVerbs

### Expected behavior

It should not fail.

### Actual behavior

It fails.

### Regression?

I did not have the problem with .NET 8

**Comment by pavelsavara** [comment]
I think that the interesting part of the log is 
```
dotnet.runtime.o8gq1i8bk6.js:3 [MONO] AOT NOT FOUND: (wrapper other) object:gsharedvt_out_sig (intptr,System.Text.RegularExpressions.Symbolic.SymbolicRegexBuilder`1/NodeCacheKey<object>&,intptr).
dotnet.runtime.o8gq1i8bk6.js:3 [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2667, condition `<disabled>' not met
```

which is pointing to 
https://github.com/dotnet/runtime/blob/234e2f7ec5dd315014f31574719900c0715f9477/src/mono/mono/mini/interp/interp.c#L2665-L2667

**Comment by voroninp** [comment]
So, gentlemen? How is it going with this issue?
