### ISSUE TITLE
LdapSessionOptions.VerifyServerCertificate Callback Does Not Work in Linux

### ISSUE THREAD

**Issue by BavadhariniE** [dotnet/runtime#109952]
### Description

While using the `System.DirectoryServices.Protocols` library in .NET Core on Linux, attempting to set the `LdapSessionOptions.VerifyServerCertificate` callback results in an exception.

#### Exception Details:

Error in LdapSearch: "System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable. at System.DirectoryServices.Protocols.ErrorChecking.CheckAndSetLdapError(Int32 error) at System.DirectoryServices.Protocols.LdapSessionOptions.set_VerifyServerCertificate(VerifyServerCertificateCallback value)

### Reproduction Steps

1. Use the following code snippet on a Linux environment:

```csharp
using System;
using System.DirectoryServices.Protocols;

var ldapConnection = new LdapConnection("ldaps://your-ldap-server:636")
{
    SessionOptions =
    {
        SecureSocketLayer = true,
        VerifyServerCertificate = (conn, cert) => true // Ignore SSL validation
    }
};

ldapConnection.Bind();

2. Replace "ldaps://your-ldap-server:636" with your actual LDAP server and port.

3. Run the code.

4. Observe the exception.

### Expected behavior

The `VerifyServerCertificate` callback should allow bypassing SSL validation on Linux, as it does on Windows.


### Actual behavior

The callback throws an exception on Linux with the message: `System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable`.

Error in LdapSearch: "System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable. at System.DirectoryServices.Protocols.ErrorChecking.CheckAndSetLdapError(Int32 error) at System.DirectoryServices.Protocols.LdapSessionOptions.set_VerifyServerCertificate(VerifyServerCertificateCallback value)



### Regression?

The same code works without errors on Windows. However, it fails on Linux. This inconsistency prevents cross-platform development for applications using the System.DirectoryServices.Protocols library for LDAP.

Support the LdapSessionOptions.VerifyServerCertificate callback functionality on Linux, enabling developers to handle SSL certificate validation dynamically across platforms.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

**Comment by BavadhariniE** [comment]
#60972 is about 389 port. I want to use 636 port so LdapSessionOptions.VerifyServerCertificate this callback function is necessary.

**Comment by BavadhariniE** [comment]
@steveharter Please reopen the ticket. I want a solution for port 636.
