### ISSUE TITLE
Test failure: System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#109942]
**Failed in:** [runtime-coreclr libraries-jitstress 20241117.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871869&view=ms.vss-test-web.build-test-results-tab&runId=22731574&resultId=111188&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstress1-Windows.10.Amd64.Open
    - System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters
```

**Error message:**
```
 System.ComponentModel.Win32Exception : The process cannot access the file because it is being used by another process.
```

**Stack trace:**
```
   at System.Diagnostics.PerformanceCounterLib.RegisterFiles(String arg0, Boolean unregister) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1232
   at System.Diagnostics.PerformanceCounterLib.UnregisterCategory(String categoryName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1237
   at System.Diagnostics.PerformanceCounterCategory.Delete(String categoryName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 392
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 235
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by ericstj** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/105925
