### ISSUE TITLE
ios-arm64 helix queue: Failed to list devices

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#110008]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=874462&view=logs&jobId=1a7f2d0f-403f-5f1a-afbb-20466d7ac54e
Build error leg or test failing: Build / ios-arm64 Release AllSubsets_NativeAOT
Pull request: https://github.com/dotnet/runtime/pull/109232

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Exception: Failed to list devices",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=874462
**Error message validated:** `[System.Exception: Failed to list devices`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 11/20/2024 11:09:50 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[875124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875124)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875124&view=ms.vss-test-web.build-test-results-tab&runId=22833822&resultId=100007)|dotnet/runtime#104488|
|[875051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875051)|dotnet/runtime|[iOS.Device.LibraryMode.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=875051&view=ms.vss-test-web.build-test-results-tab&runId=22832560&resultId=109471)|dotnet/runtime#110023|
|[874703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874703)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874703&view=ms.vss-test-web.build-test-results-tab&runId=22818672&resultId=100007)|dotnet/runtime#110010|
|[874592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874592)|dotnet/runtime|[iOS.Device.Aot.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874592&view=ms.vss-test-web.build-test-results-tab&runId=22816262&resultId=109471)|dotnet/runtime#109638|
|[874640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874640)|dotnet/runtime|[iOS.Device.ExportManagedSymbols.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874640&view=ms.vss-test-web.build-test-results-tab&runId=22817284&resultId=100005)|dotnet/runtime#109540|
|[874462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874462)|dotnet/runtime|[iOS.Device.LibraryMode.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=874462&view=ms.vss-test-web.build-test-results-tab&runId=22812132&resultId=100005)|dotnet/runtime#109232|
|[873775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873775)|dotnet/runtime|[iOS.Device.Aot.Test.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=873775&view=ms.vss-test-web.build-test-results-tab&runId=22795102&resultId=100005)|dotnet/runtime#109977|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|7|7|

**Comment by vitek-karas** [comment]
@matouskozak could you please take a look - if this is an XHarness issue, or possibly hardware related.

**Comment by akoeplinger** [comment]
We hit this before (https://github.com/dotnet/runtime/issues/84394) and very likely specific to certain devices, Build Analysis should give us a list soon.

**Comment by matouskozak** [comment]
Issue looks mitigated, latest runs are passing:
![Image](https://github.com/user-attachments/assets/c1e91980-8029-4302-bb40-9bbd91161dd4)

**Comment by kotlarmilos** [comment]
Could you provide the error log? I wasn’t able to retrieve it from the links above.

This type of failure should not be caused by XHarness but by an underlying issue. All branches are using the latest Apple mobile queues, and it is correct to use the latest XHarness, since we don’t want to backport recent changes to older branches. Let's fix .NET 8 servicing branch.

**Comment by akoeplinger** [comment]
The stats in the known issue report seem to be outdated i.e. from 2024, looks like it didn't get updated since then.

I think we should close this issue and open a new one if we still see it and work on getting https://github.com/dotnet/runtime/pull/124165 and https://github.com/dotnet/runtime/pull/124544 merged in the meantime.

**Comment by matouskozak** [comment]
> Could you provide the error log? I wasn’t able to retrieve it from the links above.

For example: https://helixr1107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-staging-3b7fdcf1178b40e4b0/IcuAppLocal.Tests/1/console.865662a2.log?helixlogtype=result

```
[20:56:19] info: Preparing run for tvos-device
[20:56:19] info: Looking for available tvos-device devices..
[20:56:19] dbug: Looking for available tvos-device devices. Storing logs into list-tvos-device-20260217_205619.log
[20:56:22] crit: System.Exception: Failed to list devices.
                    at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.HardwareDeviceLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData, Boolean includeWirelessDevices, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs:line 104
                    at Microsoft.DotNet.XHarness.Apple.DeviceFinder.FindDevice(TestTargetOs target, String deviceName, ILog log, Boolean includeWirelessDevices, Boolean pairedDevicesOnly, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs:line 74
                    at Microsoft.DotNet.XHarness.Apple.BaseOrchestrator.OrchestrateOperationInternal(TestTargetOs target, String deviceName, Boolean includeWirelessDevices, Boolean resetSimulator, Boolean enableLldb, GetAppBundleInfoFunc getAppBundle, ExecuteMacCatalystAppFunc executeMacCatalystApp, ExecuteAppFunc executeApp, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs:line 215
                    at Microsoft.DotNet.XHarness.Apple.BaseOrchestrator.OrchestrateOperation(TestTargetOs target, String deviceName, Boolean includeWirelessDevices, Boolean resetSimulator, Boolean enableLldb, GetAppBundleInfoFunc getAppBundle, ExecuteMacCatalystAppFunc executeMacCatalystApp, ExecuteAppFunc executeApp, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs:line 96
                    at Microsoft.DotNet.XHarness.Apple.TestOrchestrator.OrchestrateTest(GetAppBundleInfoFunc getAppBundlePath, TestTargetOs target, String deviceName, TimeSpan timeout, TimeSpan launchTimeout, CommunicationChannel communicationChannel, XmlResultJargon xmlResultJargon, IEnumerable`1 singleMethodFilters, IEnumerable`1 classMethodFilters, Boolean includeWirelessDevices, Boolean resetSimulator, Boolean enableLldb, Boolean signalAppEnd, IReadOnlyCollection`1 environmentalVariables, IEnumerable`1 passthroughArguments, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs:line 189
                    at Microsoft.DotNet.XHarness.CLI.Commands.Apple.AppleAppCommand`1.Invoke(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs:line 68
                    at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 145
XHarness exit code: 71 (GENERAL_FAILURE)
```
