### ISSUE TITLE
Test failure: Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Collections

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110139]
**Failed in:** [runtime-coreclr libraries-pgo 20241124.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877940&view=ms.vss-test-web.build-test-results-tab&runId=22917242&resultId=111392&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-jitosr_stress_random-Windows.10.Amd64.Open
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Collections
net10.0-windows-Release-x86-jitosr_stress-Windows.10.Amd64.Open
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Collections
net10.0-windows-Release-x86-jitoldlayout-Windows.10.Amd64.Open
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Collections
```

**Error message:**
```
 System.Collections.Generic.KeyNotFoundException : The given key 'SourceGenerationSpec' was not present in the dictionary.
```

**Stack trace:**
```
   at System.Collections.ThrowHelper.ThrowKeyNotFoundException[TKey](TKey key) in /_/src/libraries/System.Collections.Immutable/src/System/Collections/ThrowHelper.cs:line 34
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key) in /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableDictionary_2.cs:line 251
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.ConfigBindingGenTestDriver.RunGeneratorAndUpdateCompilation(String source) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigBindingGenTestDriver.cs:line 62
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.RunGeneratorAndUpdateCompilation(String source, LanguageVersion langVersion, IEnumerable`1 assemblyReferences) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Helpers.cs:line 186
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, ExtensionClassType extType, ExpectedDiagnostics expectedDiags) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Helpers.cs:line 147
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Collections() in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Baselines.cs:line 941
--- End of stack trace from previous location ---
```

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/110129 (and doesn't repro in https://github.com/dotnet/runtime/pull/110142)
