### ISSUE TITLE
Test failure: Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110138]
**Failed in:** [runtime-coreclr libraries-pgo 20241124.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877940&view=ms.vss-test-web.build-test-results-tab&runId=22917242&resultId=110983&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-jitosr_stress_random-Windows.10.Amd64.Open
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
net10.0-windows-Release-x86-jitosr_stress-Windows.10.Amd64.Open
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
net10.0-windows-Release-x86-jitoldlayout-Windows.10.Amd64.Open
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
```

**Error message:**
```
 Assert.Empty() Failure: Collection was not empty
Collection: [warning CS8785: Generator 'LoggerMessageGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.']
```

**Stack trace:**
```
   at Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode) in /_/src/libraries/Microsoft.Extensions.Logging.Abstractions/tests/Microsoft.Extensions.Logging.Generators.Tests/LoggerMessageGeneratorEmitterTests.cs:line 265
   at Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success() in /_/src/libraries/Microsoft.Extensions.Logging.Abstractions/tests/Microsoft.Extensions.Logging.Generators.Tests/LoggerMessageGeneratorEmitterTests.cs:line 147
--- End of stack trace from previous location ---
```

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/110129 (and doesn't repro in https://github.com/dotnet/runtime/pull/110142)
