### ISSUE TITLE
Source generator tests failing with NullReferenceException in TaskReplicator

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#110127]
```
  Starting:    ComInterfaceGenerator.Unit.Tests (parallel test collections = on [2 threads], stop on fail = off)
    ComInterfaceGenerator.Unit.Tests.ComClassGeneratorOutputShape.SingleComClass [FAIL]
      System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/TaskReplicator.cs(158,0): at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
        /_/src/libraries/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs(982,0): at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=877993
Build error leg or test failing: ComInterfaceGenerator.Unit.Tests.AddGeneratedComClassTests.TypeThatImplementsGeneratedComInterfaceType_ReportsDiagnostic
Pull request: https://github.com/dotnet/runtime/pull/110123

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "NullReferenceException", "System.Threading.Tasks.TaskReplicator" ],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=877993
**Error message validated:** `[NullReferenceException System.Threading.Tasks.TaskReplicator`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 11/25/2024 5:47:56 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[878074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878074)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexGeneratorParserTests.Valid_ClassWithGenericConstraints](https://dev.azure.com/dnceng-public/public/_build/results?buildId=878074&view=ms.vss-test-web.build-test-results-tab&runId=22921584&resultId=208383)|dotnet/runtime#109996|
|[877993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877993)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexGeneratorParserTests.Valid_ClassWithGenericConstraints](https://dev.azure.com/dnceng-public/public/_build/results?buildId=877993&view=ms.vss-test-web.build-test-results-tab&runId=22920728&resultId=210089)|dotnet/runtime#110123|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|2|2|

**Comment by jkotas** [comment]
@EgorBo Looks like this was introduced by #110076 . I am trying to revert it in https://github.com/dotnet/runtime/pull/110129
