### ISSUE TITLE
Authentication validation failed with error - InvalidToken exception on .net

### ISSUE THREAD

**Issue by danghyan** [dotnet/runtime#110184]
### Description

Hello. My team has partially encountered an InvalidToken error during POST requests to the server. This error appears sequentially for different developers, and once it occurs, it doesn’t go away. Currently, half of the team has no issues, while the other half consistently encounters this error during POST requests.

The client typically makes two requests. The first one, a handshake response, returns 401, and the second request receives a 200 response. The server processes the request correctly and returns the appropriate response. However, the client throws an InvalidToken error. I checked the headers through Fiddler, and they seem fine.

If the Kerberos authentication header is explicitly specified for the HTTP client, everything starts working correctly. In this case, the client skips the first handshake (401 request, which makes sense) and sends the request with the Kerberos header directly. Again, I checked the headers through Fiddler, and they are identical to those used in unsuccessful operations. The first 7700 characters of the header are entirely identical.

Decompiled code didn’t provide any useful information either. I understand this is a common issue, so are there any suggestions or advice?

All the threads found here and on other resources did not provide a clear answer to the issue. In our case, the server is managed by our team, so we might be able to dig a bit deeper into solving the problem.

### Reproduction Steps

It won't be possible to reproduce it explicitly.

### Expected behavior

Currect 200 response

### Actual behavior

System.Net.Http.HttpRequestException: Authentication validation failed with error - InvalidToken.
    at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

### Known Workarounds

Cusom kerberos header for HttpClient

### Configuration

.Net 7, .Net 8
Client - Windows 10
Server - K8S

**Comment by danghyan** [comment]
@filipnavara You were extremely helpful and provided a lot of advice in a similar thread where the server was not managed by the developers and was written in Java. Perhaps you could offer some guidance here as well, please?

**Comment by filipnavara** [comment]
@danghyan I can analyze Fiddler/Proxyman/Charles traces with the `Authorization` / `WWW-Authentication` headers included. Feel free to share them with me on my email (link on my profile) and I will post the results back here.

**Comment by ogguevara07** [comment]
Correct my spelling and then translate it into English. Review how you declared the `[Authorize]`. At one point, I had issues with the front-end returning a 401 error on some occasions. I identified that the problem was how I had configured my JWT and how the back-end was processing it. What I did was change `[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]` to `[Authorize]`.

**Comment by filipnavara** [comment]
Just a summary of the private conversation from email.

I briefly checked the tokens. The server responds with 200 OK and WWW-Authentication header. The value of the header seems to be syntactically correct according to RFC 4178 (https://datatracker.ietf.org/doc/html/rfc4178) specification of NegTokenResp and contains the following values:
- negState: accept-completed
- supportedMech: 1.2.840.48018.1.2.2 (technically incorrect Kerberos V5 OID sent by Windows, matches the request OID though, so likely ok; https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-spng/f663e38f-f4c8-4ed8-9bfe-51772e667116#Appendix_A_Target_9)
- responseToken: <the Kerberos response token>

There's no MIC (Message Integrity Check) in the response. That seems to be valid in this case according to the specification:
> Otherwise, if the accepted mechanism is the most preferred mechanism of both the initiator and the acceptor, then the MIC token exchange, as described later in this section, is OPTIONAL. 

The value of `responseToken` seems to be a Kerberos 5 `KRB_AP_REP` packet. Whether the token is actually valid response I am not sure. Just in case, this is the decoded ASN.1 structure:

```
OCTET_STRING @0+156 (encapsulates): (156 byte)|<...>
  Application_0 @3+153 (constructed): (3 elem)
    OBJECT_IDENTIFIER @6+9: 1.2.840.113554.1.2.2
    INTEGER @17+0: 0
    Application_15 @19+137 (constructed): (1 elem)
      SEQUENCE @22+134 (constructed): (3 elem)
        [0] @25+3 (constructed): (1 elem)
          INTEGER @27+1: 5
        [1] @30+3 (constructed): (1 elem)
          INTEGER @32+1: 15
        [2] @35+122 (constructed): (1 elem)
          SEQUENCE @37+120 (constructed): (2 elem)
            [0] @39+3 (constructed): (1 elem)
              INTEGER @41+1: 18
            [2] @44+113 (constructed): (1 elem)
              OCTET_STRING @46+111: (111 byte)|<...>
```

/cc @SteveSyfuhs in case he has tips on getting more info from the Windows auth stack.

**Comment by SteveSyfuhs** [comment]
Structure looks about right:

```asn1
AP-REP          ::= [APPLICATION 15] SEQUENCE {
        pvno            [0] INTEGER (5), --> 5
        msg-type        [1] INTEGER (15), --> 15
        enc-part        [2] EncryptedData -- EncAPRepPart ----->
}

EncryptedData   ::= SEQUENCE {
        etype   [0] Int32, --> 18 (AES)
        kvno    [1] UInt32 OPTIONAL, --> NULL
        cipher  [2] OCTET STRING --> 111 bytes
}
```

It's unlikely a structural issue and more likely the client and server not agreeing on the session key. I'm not sure how the client gets to `InvalidToken` but I'd guess it's translated from `SEC_E_INVALID_TOKEN`. Looking at the code there's a handful of places where this is set:

ISC:
 - Missing output token buffer
 - Missing input token buffer && missing mechlist buffer
 - Internal state machine failure -- unlikely

Which none of these come from session key disagreement.

Might try enabling logging on the client and see if the provides anything more specific: https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/enable-kerberos-event-logging. Otherwise we might need to dig into the internal tracing and see what its complaining about.

**Comment by danghyan** [comment]
I’ve discovered something that might be useful.

The source code for the location where the error occurs is here - https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs

If the Kerberos authentication header is set manually, the check passes at line 89 without validating the token. It simply checks the status. The authContext.GetOutgoingBlob(challengeData, out statusCode) method is not even called.

However, if the header is not set manually, the first request is made at line 89, where we get a NeedContinue response and proceed further. At line 209, we then receive an InvalidToken error.

In both cases, the tokens are sent and generated correctly. The difference lies in how the token is verified.

It’s also unclear why it works fine for half of my colleagues. It could be related to a Windows update or some corrupted system package, such as sspicli.dll, which is used to calculate the InvalidToken error code.

**Comment by danghyan** [comment]
@SteveSyfuhs Thank you very much for your response. Below are the errors from the event logs.


Errors occurring during the initial anonymous request:
1) 0x44 KDC_ERR_WRONG_REALM
2) 0x19 KDC_ERR_PREAUTH_REQUIRED

Warning after the last call:
3) The machine-default permission settings do not grant Local Activation permission for the COM Server application with CLSID Microsoft.Windows.ShellExperienceHost_10.0.19041.5072_neutral_neutral_cw5n1h2txyewy SID. This security permission can be modified using the Component Services administrative tool.

**Comment by danghyan** [comment]
We found where the issue arises:
After checking the decompiled code of System.Net.Http with a colleague, the problem is that the server does not return the WWW-Authenticate header for him. At line 201 (as referenced above), his code hits the break and returns the response. However, in my case, the server also responds with a 200 status, but includes the WWW-Authenticate header. As a result, my code does not hit the break and instead proceeds to evaluate the challengeData, which is subsequently considered invalid.

**Comment by rzikm** [comment]
Unfortunately not many, best next step seems to be looking into Kerberos event logs, see comment from @SteveSyfuhs 

> Might try enabling logging on the client and see if the provides anything more specific: https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/enable-kerberos-event-logging. Otherwise we might need to dig into the internal tracing and see what its complaining about.

tagging @wfurt in case he has more ideas.

**Comment by danghyan** [comment]
Hello,

Apologies for the delay in responding.

From my side:
We spent a lot of time studying the issue and found that the token logic works approximately as follows:

The client generates a token and sends it to the server.
The server validates the token, and if the token is valid, it performs the operation.
Before responding, the server generates a new token (I assume by enriching the incoming token with additional information), which it returns with the response.
The client validates the token received from the server and processes the response. (In our case, it results in InvalidToken.)
It seems like our chain breaks at step 3, but it's unclear what exactly is missing. The issue occurs on .NET 7 and 8.

Here is the server-side code:
https://github.com/dotnet/aspnetcore/blob/main/src/Security/Authentication/Negotiate/src/NegotiateHandler.cs line 137.
I tried following this trail but couldn't find the NegotiateAuthenticationPal class further down the chain.

Reply @SteveSyfuhs :
Event Viewer -> System -> Error:
A Kerberos error message was received:
on logon session username
Client Time:
Server Time: 14:40:39.0000 12/28/2024 Z
Error Code: 0x19 KDC_ERR_PREAUTH_REQUIRED
Extended Error:
Client Realm:
Client Name:
Server Realm: domain
Server Name: krbtgt/domain
Target Name: krbtgt/domain@domain
Error Text:
File: onecore\ds\security\protocols\kerberos\client2\logonapi.cxx
Line: e35
Error Data is in record data.

**Comment by rzikm** [comment]
@danghyan could you try the suggestion from my previous comment? https://github.com/dotnet/runtime/issues/110184#issuecomment-2514278470
