### ISSUE TITLE
Test failure: Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110299]
**Failed in:** [runtime-coreclr r2r-extra 20241130.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=882955&view=ms.vss-test-web.build-test-results-tab&runId=23085024&resultId=111036&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitstress1 @ OSX.1200.ARM64.Open
    - Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.cmd
```

**Error message:**
```
 DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /private/tmp/helix/working/A6200902/p/crossgen2/createdump
/private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/Interop/../StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.sh: line 258: 50281 Segmentation fault: 11  (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/A6200902/w/BCE609FC/uploads/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/IL-CG2/ReversePInvokeTest.dll
19:59:07
Response file: /private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.dll.rsp
/private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/IL-CG2/ReversePInvokeTest.dll
-o:/private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.dll
--targetarch:arm64
--targetos:osx
--verify-type-and-field-layout
--method-layout:random
-r:/tmp/helix/working/A6200902/p/System.*.dll
-r:/tmp/helix/working/A6200902/p/Microsoft.*.dll
-r:/tmp/helix/working/A6200902/p/xunit.*.dll
-r:/tmp/helix/working/A6200902/p/mscorlib.dll
-r:/tmp/helix/working/A6200902/p/netstandard.dll
Running CrossGen2:  /tmp/helix/working/A6200902/p/crossgen2/crossgen2 @/private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.dll.rsp   -r:/private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/IL-CG2/*.dll
Running R2RDump:  dotnet /tmp/helix/working/A6200902/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.dll --out /private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 467
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 449
19:59:16
Crossgen2 failed with exitcode: 139
in ReleaseLock
Test failed. Trying to see if dump file was created in /cores since 11/30/2024 7:59:07 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/A6200902/w/BCE609FC/e/Interop/Interop/../StructMarshalling/ReversePInvoke/MarshalSeqStruct/ReversePInvoke/ReversePInvokeTest/ReversePInvokeTest.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor274|25_275(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr r2r-extra 20250614.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1068428&view=ms.vss-test-web.build-test-results-tab&runId=28908714&resultId=121797&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitminopts @ OSX.13.Arm64.Open
    - Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.cmd
```

**Error message:**
```
 DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /private/tmp/helix/working/B42D0A27/p/crossgen2/createdump
/private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/Interop/../StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.sh: line 258: 48560 Segmentation fault: 11  $__Command

Return code:      1
Raw output file:      /tmp/helix/working/B42D0A27/w/9D0408D2/uploads/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/IL-CG2/MarshalStructAsLayoutSeq.dll
23:26:50
Response file: /private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.dll.rsp
/private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/IL-CG2/MarshalStructAsLayoutSeq.dll
-o:/private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.dll
--targetarch:arm64
--targetos:osx
--verify-type-and-field-layout
--method-layout:random
-r:/tmp/helix/working/B42D0A27/p/System.*.dll
-r:/tmp/helix/working/B42D0A27/p/Microsoft.*.dll
-r:/tmp/helix/working/B42D0A27/p/xunit.*.dll
-r:/tmp/helix/working/B42D0A27/p/mscorlib.dll
-r:/tmp/helix/working/B42D0A27/p/netstandard.dll
Running CrossGen2:  /tmp/helix/working/B42D0A27/p/crossgen2/crossgen2 @/private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.dll.rsp   -r:/private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/IL-CG2/*.dll
Running R2RDump:  dotnet /tmp/helix/working/B42D0A27/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.dll --out /private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 508
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader..ctor(IAssemblyResolver assemblyResolver, String filename) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 422
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 449
23:26:50
Crossgen2 failed with exitcode: 139
in ReleaseLock
Test failed. Trying to see if dump file was created in /cores since 6/14/2025 11:26:50 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/B42D0A27/w/9D0408D2/e/Interop/Interop/../StructMarshalling/PInvoke/MarshalStructAsLayoutSeq/MarshalStructAsLayoutSeq.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/arcade/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor269|25_270(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```
