### ISSUE TITLE
Test failure: JIT/Stress/ABI/tailcalls_do/tailcalls_do.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110210]
**Failed in:** [runtime-coreclr outerloop 20241126.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=879387&view=ms.vss-test-web.build-test-results-tab&runId=22970278&resultId=123364&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm64 Checked no_tiered_compilation @ (Alpine.317.Arm64.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm64v8
    - JIT/Stress/ABI/tailcalls_do/tailcalls_do.cmd
```

**Error message:**
```
 DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /root/helix/work/correlation/crossgen2/createdump

cmdLine:/root/helix/work/workitem/e/JIT/JIT_do/../Stress/ABI/tailcalls_do/tailcalls_do.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 11/26/2024 10:56:30 AM, end: 11/26/2024 11:26:30 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Stress/ABI/tailcalls_do/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/Stress/ABI/tailcalls_do/IL-CG2/tailcalls_do.dll
10:56:30
Response file: /root/helix/work/workitem/e/JIT/Stress/ABI/tailcalls_do/tailcalls_do.dll.rsp
/root/helix/work/workitem/e/JIT/Stress/ABI/tailcalls_do/IL-CG2/tailcalls_do.dll
-o:/root/helix/work/workitem/e/JIT/Stress/ABI/tailcalls_do/tailcalls_do.dll
--targetarch:arm64
--targetos:linux
--verify-type-and-field-layout
--method-layout:random
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
-r:/root/helix/work/correlation/netstandard.dll
Running CrossGen2:  /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/JIT/Stress/ABI/tailcalls_do/tailcalls_do.dll.rsp   -r:/root/helix/work/workitem/e/JIT/Stress/ABI/tailcalls_do/IL-CG2/*.dll

cmdLine:/root/helix/work/workitem/e/JIT/JIT_do/../Stress/ABI/tailcalls_do/tailcalls_do.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 11/26/2024 10:56:30 AM, end: 11/26/2024 11:26:30 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/JIT/JIT_do/../Stress/ABI/tailcalls_do/tailcalls_do.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor3|0_4(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by mangod9** [comment]
Closing old issues not reproing anymore
