### ISSUE TITLE
Exception on LDAP/AD connection with .NET 8 on MacOs and Docker with StartTransportLayerSecurity

### ISSUE THREAD

**Issue by markusTraber** [dotnet/runtime#110391]
### Description

On `MacOs Sonoma 14.5 (23F79)` and `Docker Debian mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim` I cannot connect to our Active Directory with `System.DirectoryServices.Protocols 8.0.0`. I get an exception when calling `StartTransportLayerSecurity(null)`. It works as soon, as I use version `7.0.1` instead of `8.0.0`.

#### MacOs

1. `MacOs Sonoma 14.5 (23F79)`
2. AD Server with Start TLS on port 389
3. Reference `System.DirectoryServices.Protocols` package in version 8.0.0 in your project
4. Execute code
```
LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier(host, port);
LdapConnection cn = new LdapConnection(ldi);
cn.Credential = new NetworkCredential(userDn, plainPassword);
cn.AuthType = AuthType.Basic;
cn.SessionOptions.ProtocolVersion = 3;
cn.SessionOptions.StartTransportLayerSecurity(null);
cn.Bind();
```

#### Docker

1. AD Server with Start TLS on port 389
2. Reference `System.DirectoryServices.Protocols` package in version 8.0.0 in your project
3. Implement code in project
```
LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier(host, port);
LdapConnection cn = new LdapConnection(ldi);
cn.Credential = new NetworkCredential(userDn, plainPassword);
cn.AuthType = AuthType.Basic;
cn.SessionOptions.ProtocolVersion = 3;
cn.SessionOptions.StartTransportLayerSecurity(null);
cn.Bind();
```
4. Build a docker image:
```
FROM --platform=$BUILDPLATFORM  mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS build
ARG TARGETARCH
WORKDIR /build

# Copy project files and restore
COPY *.sln ./
COPY Directory.Packages.props ./
COPY src/ExampleApp.Web.Host/*.csproj ./src/ExampleApp.Web.Host/
# ... more csproj files
RUN dotnet restore

COPY --link . ./

WORKDIR /build/src/ExampleApp.Web.Host/
RUN dotnet publish -c Release -o /publish /p:Version=$(date +"%Y.%m.%d") --no-restore


#
# Runtime stage
#
FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim
EXPOSE 10001
WORKDIR /app
COPY --link --from=build /publish .

# install new libldap
RUN apt update \
  && apt install --upgrade -y libldap-2.5-0 \
  && ln -s /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2 \
  && ln -s /usr/lib/x86_64-linux-gnu/libldap.so.2 /usr/lib/libldap-2.5.so.0 \
  && apt install nano vim -y \
  && apt clean \
  && rm -rf /var/lib/apt/lists/

# ad/ldap library link issue - https://github.com/dotnet/runtime/discussions/98990
# RUN apt update \
#  && ln -s /usr/lib/x86_64-linux-gnu/libldap-2.5.so.0 /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2 \
#  && ln -s /usr/lib/x86_64-linux-gnu/libldap.so.2 /usr/lib/libldap-2.5.so.0 \

# copy entrypoint script and make executable
COPY ./docker/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# create directory for ldap cert -> will be mounted as volume and checked by entrypoint.sh
RUN mkdir /usr/share/ca-certificates/extra
RUN cp /etc/ca-certificates.conf /etc/ca-certificates.conf.backup

CMD ["/usr/local/bin/entrypoint.sh"]
```
5. Run image and execute ldap connection code. I have tried 3 variations:
    5.1 Installing libldap-2.5-0
    5.2 Installing libldap-2.5-0 and creating symbolic links (commented in dockerfile)
    5.2 Without installing and linking

### Expected behavior

I can connect to AD and no exception is thrown when "StartTransportLayerSecurity" method is called.

#### MacOS

Exception is thrown when calling "StartTransportLayerSecurity" method:

```
Exception has occurred: CLR/System.DirectoryServices.Protocols.LdapException
Exception thrown: 'System.DirectoryServices.Protocols.LdapException' in System.DirectoryServices.Protocols.dll: 'The LDAP server is unavailable.'
   at System.DirectoryServices.Protocols.LdapSessionOptions.StartTransportLayerSecurity(DirectoryControlCollection controls)
   at ExampleApp.Authentication.Ldap.LdapConnectionFactory.CreateBoundConnection(String userDn, String plainPassword) in src/ExampleApp.Ldap/Authentication/Ldap/LdapConnectionFactory.cs:line 102
```

![Image](https://github.com/user-attachments/assets/cf0030ca-c020-4fb2-874c-389c54de72a8)

#### Docker

When installing libldap 2.5 and linking it or not (5.1 and 5.2), I get basically the same error as on MacOs:

```
System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.    at System.DirectoryServices.Protocols.LdapSessionOptions.StartTransportLayerSecurity(DirectoryControlCollection controls)
   at ExampleApp.Authentication.Ldap.LdapConnectionFactory.CreateBoundConnection(String userDn, String plainPassword) in /build/src/ExampleApp.Ldap/Authentication/Ldap/LdapConnectionFactory.cs:line 102
```

without installing I get the following:

```
System.TypeInitializationException: The type initializer for 'Ldap' threw an exception.    at Interop.Ldap.ldap_initialize(IntPtr& ld, String uri)
   at System.DirectoryServices.Protocols.ConnectionHandle..ctor()
   at System.DirectoryServices.Protocols.LdapConnection.InternalInitConnectionHandle()
   at System.DirectoryServices.Protocols.LdapConnection.Init()
   at System.DirectoryServices.Protocols.LdapConnection..ctor(LdapDirectoryIdentifier identifier, NetworkCredential credential, AuthType authType)
   at System.DirectoryServices.Protocols.LdapConnection..ctor(LdapDirectoryIdentifier identifier)
   at ExampleApp.Authentication.Ldap.LdapConnectionFactory.CreateBoundConnection(String userDn, String plainPassword) in /build/src/ExampleApp.Ldap/Authentication/Ldap/LdapConnectionFactory.cs:line 85
```

### Regression?

Works with `System.DirectoryServices.Protocols 7.0.1`

### Known Workarounds

Using v 7.0.1

### Configuration

- `MacOs Sonoma 14.5 (23F79)` on arm64 with .Net v8.0.403
- `Docker Debian mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim`, running as x64 on MacOs arm64 Host
- `System.DirectoryServices.Protocols 8.0.0`

### Other information

- Similar issue: https://github.com/dotnet/runtime/issues/96988
- Discussion about docker image and problems with libldap (but not using aspnet image).: https://github.com/dotnet/runtime/discussions/98990

**Comment by steveharter** [comment]
This looks like a duplicate of https://github.com/dotnet/runtime/issues/108448 due to the hard-coded version of LDAP. We have 2.4 and 2.6 but the above issue description has 2.5.

You could try installing 2.6, or create a symlink to forward one of the known versions to 2.6.

**Comment by steveharter** [comment]
This looks similar to https://github.com/dotnet/runtime/issues/108448, but the current implementation should pick up `libldap-2.4.so.2`, `libldap-2.5.so.0` and `libldap-2.6.so.0` and it look like you've tried `2.5-0` and variants.

**Comment by steveharter** [comment]
>  It works as soon, as I use version 7.0.1 instead of 8.0.0.

There was a [change in v8 ](https://github.com/dotnet/runtime/pull/88851)that started to probe for 2.4, 2.5 and 2.6. 

Previously in v7 it only looked for 2.4 (`libldap-2.4.so.2`), and I see you used symlinks to forward 2.5 to 2.4 which was necessary.

For the v8 case is it possible that these symlinks are pointing to an incorrect or missing entry? The symlinks shouldn't be necessary for v8 as 2.5 is now probed for.

**Comment by steveharter** [comment]
I suggest also looking at https://github.com/dotnet/runtime/issues/69456

**Comment by markusTraber** [comment]
Thank you. I will look into this and get back to you here.

**Comment by markusTraber** [comment]
Hi, I looked into the links, unfortunately I am not able to resolve this.

There was a wrong symlink `ln -s /usr/lib/x86_64-linux-gnu/libldap.so.2 /usr/lib/libldap-2.5.so.0`, which I now removed from the Dockerfile in the bug report. But it did not matter, since I also tried without symlinking before. 

I would assume, that v8 correctly finds and loads the libldap library without symlinking. I think this is what the different error messages suggest (not installed / installed).

I also tried with runtime identifiers (as suggested [here](https://github.com/dotnet/runtime/issues/69456#issuecomment-1590574655)) and therefore updated the dockerfile to include runtime identifiers (also updated the dockerfile in the bug report):

```
RUN dotnet restore -r linux-x64 -p:TargetFramework=net8.0

COPY --link . ./

WORKDIR /build/src/ExampleApp.Web.Host/
RUN dotnet publish -c Release -r linux-x64 -o /publish /p:Version=$(date +"%Y.%m.%d") --no-restore
``

I still get the same error, (installing libldap-2.5-0, without symlinking) as before:

```
System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.    at System.DirectoryServices.Protocols.LdapSessionOptions.StartTransportLayerSecurity(DirectoryControlCollection controls)
   at ExampleApp.Authentication.Ldap.LdapConnectionFactory.CreateBoundConnection(String userDn, String plainPassword) in /build/src/ExampleApp.Ldap/Authentication/Ldap/LdapConnectionFactory.cs:line 102
```

[The workaround](https://github.com/dotnet/runtime/issues/69456#issuecomment-1592867432), using AssemblyLoadContext, is basically very similar to what you are doing in .net v8 already. Because of this and my assumption, that in my case the probing already works correctly, I did not try this.

Thank you

**Comment by adamjasinski** [comment]
An update for .NET 10 and Linux (Ubuntu 24.04):

The behavior observed by the OP (`LdapException` with `The LDAP server is unavailable` message) also occurs in .NET 10.
My workaround for .NET 8 was to provide a symlink to `libldap2.4.so.2`, as .NET 8 was looking for that specific version. That symlink is no longer required, as System.DirectoryServices in .NET 10 look for `libldap.so.2` instead. 
However, the code that calls `StartTransportLayerSecurity(null)` (the same code as the OP posted) throws `LdapException` in .NET 10 on Linux.

I was able to determine the following:
A call to `StartTransportLayerSecurity` seems to assume that there's an open connection to the LDAP server already. 
(And opening a plain, anonymous connection to LDAP suffices for the purpose of sending a StartTLS request)

```csharp
// NB - we need to open the connection first
cn.AuthType = AuthType.Anonymous;
cn.Bind();
// Send a StartTLS request to upgrade the connection to TLS (by default on port 389)
cn.SessionOptions.StartTransportLayerSecurity(null);

// Now we can re-bind the connection with our actual credentials.
LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier(host, port);
LdapConnection cn = new LdapConnection(ldi);
cn.Credential = new NetworkCredential(userDn, plainPassword);
cn.AuthType = AuthType.Basic;
cn.SessionOptions.ProtocolVersion = 3;
cn.Bind();
```

(Note: An alternative approach would be to use LDAPS (SSL from the start) via `cn.SessionOptions.SecureSocketLayer = true`, but in this example I wanted to use StartTLS to upgrade a plain connection on port 389)

I wasn't able to pinpoint  whether the change of behaviour between frameworks stems from a difference of the C# implementation of [LdapSessionOptions](https://github.com/dotnet/runtime/blob/454c7cd73dcd088bd66377b5cbe2db4cff9c7056/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapSessionOptions.cs#L605), or from differences in behaviour of different versions of Linux `libldap.ldap_start_tls`. But a workaround is to open an anonymous connection first.

If this is indeed a pre-requisite of `StartTransportLayerSecurity` method and not a platform-specific behaviour, it would be nice to have this requirement (a connection has to exist already) added to the documentation of `LdapSessionOptions.StartTransportLayerSecurity` method, as the exception ("The LDAP server is unavailable") doesn't really indicate the root cause of the issue.
