### ISSUE TITLE
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters Failed

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#110454]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=887390
Build error leg or test failing: System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters
Pull request: https://github.com/dotnet/runtime/pull/110378

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as this issue has not been hit in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-jitstressregs 20250601.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1056081&view=ms.vss-test-web.build-test-results-tab&runId=28465124&resultId=112886&paneView=debug)

**Failed tests:**
```
net10.0-windows-Release-x86-jitstressregs1-Windows.10.Amd64.Open
    - System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static
```

**Error message:**
```
 Expected: 0 to be greater than 0 PerformanceCounterCategory.GetInstanceNames() returned 0.
```

**Stack trace:**
```
   at System.AssertExtensions.GreaterThan[T](T actual, T greaterThan, String userMessage) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 335
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 273
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by ericstj** [comment]
```
System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.



Stack trace
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/Win32.cs:line 308
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 263
   at System.Security.AccessControl.NativeObjectSecurity.Persist(SafeHandle handle, AccessControlSections includeSections, Object exceptionContext) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 368
   at System.Security.AccessControl.NativeObjectSecurity.Persist(SafeHandle handle, AccessControlSections includeSections) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 361
   at System.Security.AccessControl.MutexSecurity.Persist(SafeWaitHandle handle) in /_/src/libraries/System.Threading.AccessControl/src/System/Security/AccessControl/MutexSecurity.cs:line 178
   at System.Threading.ThreadingAclExtensions.SetAccessControl(Mutex mutex, MutexSecurity mutexSecurity) in /_/src/libraries/System.Threading.AccessControl/src/System/Threading/ThreadingAclExtensions.cs:line 35
   at System.Diagnostics.NetFrameworkUtils.EnterMutexWithoutGlobal(String mutexName, Mutex& mutex) in /_/src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs:line 32
   at System.Diagnostics.NetFrameworkUtils.EnterMutex(String name, Mutex& mutex) in /_/src/libraries/Common/src/System/Diagnostics/NetFrameworkUtils.cs:line 20
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 222
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, String counterName, String counterHelp) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 192
   at System.Diagnostics.Tests.Helpers.CreateCategory(String categoryName, String counterName, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 33
   at System.Diagnostics.Tests.Helpers.CreateCategory(String categoryName, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CategoryType_MultiInstance() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 85
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 126
```

Introduced with https://github.com/dotnet/runtime/commit/81f1f5ef694b62d801291fb70d86dd5ed9074448.  Perhaps this thread isn't the one to create the mutex and cannot modify the ACL?
