### ISSUE TITLE
System.Uri.ToString() throws despite Uri.TryCreate succeeding

### ISSUE THREAD

**Issue by zotanmew** [dotnet/runtime#110480]
### Description

`Uri.ToString` throws `ArgumentOutOfRangeException` for some inputs that pass `Uri.TryCreate`. Same behavior for `.Host`, `.AbsoluteUri`, etc:
![Image](https://github.com/user-attachments/assets/4b9fbe0f-40c3-429a-9cc6-b68cf0d435c0)

### Reproduction Steps

```csharp
if (Uri.TryCreate("\t/�", UriKind.Absolute, out var uri)) {
    Console.WriteLine(uri.ToString()); // throws ArgumentOutOfRangeException
}
```

### Expected behavior

Either for `Uri.TryCreate` to fail, or for uri.ToString() to succeed

### Actual behavior

```
System.ArgumentOutOfRangeException: length ('-8') must be a non-negative value. (Parameter 'length')
Actual value was -8.
   at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
   at System.ArgumentOutOfRangeException.ThrowIfNegative[T](T value, String paramName)
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Uri.CreateHostStringHelper(String str, Int32 idx, Int32 end, Flags& flags, String& scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.ToString()
```

### Regression?

.NET Core 3.1: uri.ToString() → `file://%EF%BF%BD/%25EF%25BF%25BD`
Any later .NET version (from .NET 5 onwards): `ArgumentOutOfRangeException` at `ToString()`

### Configuration

.NET 9.0.0, macOS 15.1.1 arm64

**Comment by zotanmew** [comment]
This was found during a fuzzing pass on a parser I wrote, the original input the fuzzer used was `\t\t\t\t\t\t\t\t/s�:<G$[hcom`

**Comment by kescherCode** [comment]
.NET Framework 4.x refuses to create the Uri to begin with.

**Comment by MihaZupan** [comment]
Thanks for the report.
Implicit file path support, the gift that keeps on giving.

After `EnsureUriInfo` we're looking at:
```
_string "\t/�"

_info.Offset
    End: 3
    Fragment: 0
    Host: 1
    Path: 1
    PortValue: 0
    Query: 0
    Scheme: 1
    User: 1
```
and after `ParseRemaining`:
```
_string "/%EF%BF%BD"

_info.Offset
    End: 10
    Fragment: 10
    Host: 1
    Path: 0
    PortValue: 0
    Query: 10
    Scheme: 1
    User: 1
```
Note that we've updated `Path = 0` as we've realized there's no host, but we never fix up the `Host = 1` offset.
https://github.com/dotnet/runtime/blob/e7e568be723d1ec37b374eeb59ca9e1d2fb11892/src/libraries/System.Private.Uri/src/System/Uri.cs#L3285-L3304

And once we reach the host helper, we're calling it with `idx = 1, end = 0`:
https://github.com/dotnet/runtime/blob/e7e568be723d1ec37b374eeb59ca9e1d2fb11892/src/libraries/System.Private.Uri/src/System/Uri.cs#L2437

If you don't have leading whitespace in the input, `Host` remains 0, and you only "allocate" an empty substring for the host.
