### ISSUE TITLE
Strange OutOfMemory exceptions on Linux ppc64le

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#110487]
Hi there,

This issue probably connected with #86069. The virtual machine on POWER9 works properly on my tests, BUT I got a ton of same errors on QEMU x64 with Fedora 41 ppc64le + .NET 9.0 ppc64le. Please see https://github.com/JetBrains/format-ripper/actions/runs/12204385970/job/34049372306

// cc @alhad-deshpande 

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Collections.Hashtable.rehash(Int32 newsize)
   at System.Collections.Hashtable.expand()
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.set_Item(Object key, Object value)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes(Type type)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes()
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetAttributes(Type type)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetAttributes()
   at System.ComponentModel.TypeDescriptor.GetAttributes(Type componentType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes()
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetAttributes(Type type)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetAttributes()
   at System.ComponentModel.TypeDescriptor.GetAttributes(Type componentType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance, Boolean verifyIsRegisteredType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type, Object instance)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.CanTypeDescriptorConvertString(Type type, TypeConverter& typeConverter)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CanConvertToString(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.Serialization.DefaultTestPlatformContractResolver.CreateContract(Type objectType) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/Serialization/DefaultTestPlatformContractResolver.cs:line 22
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]].GetOrAdd(Type key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2[[System.Type, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed]].Get(Type key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContract(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal(JsonWriter jsonWriter, Object value, Type rootType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Converters.KeyValuePairConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.Serialize[VersionedMessageForSerialization](JsonSerializer serializer, VersionedMessageForSerialization data) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs:line 433
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.JsonDataSerializer.SerializePayload(String messageType, Object payload, Int32 version) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/JsonDataSerializer.cs:line 391
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestHandler.SendTestRunStatistics(TestRunChangedEventArgs testRunChangedArgs) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/EventHandlers/TestRequestHandler.cs:line 196
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.EventHandlers.TestRunEventsHandler.HandleTestRunStatsChange(TestRunChangedEventArgs testRunChangedArgs) in /_/src/Microsoft.TestPlatform.CommunicationUtilities/EventHandlers/TestRunEventsHandler.cs:line 38
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.OnCacheHit(TestRunStatistics testRunStats, ICollection`1 results, ICollection`1 inProgressTestCases) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/BaseRunTests.cs:line 666
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.TestRunCache.SendResults() in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/TestRunCache.cs:line 339
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.TestRunCache.CheckForCacheHit() in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/TestRunCache.cs:line 320
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.TestRunCache.OnTestStarted(TestCase testCase) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Execution/TestRunCache.cs:line 192
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Adapter.TestExecutionRecorder.RecordStart(TestCase testCase) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Adapter/TestExecutionRecorder.cs:line 72
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.TestStarted(INUnitTestEventStartTest testNode) in C:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 141
   at NUnit.VisualStudio.TestAdapter.NUnitEventListener.OnTestEvent(String report) in C:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEventListener.cs:line 81
```

**Comment by ww898** [comment]
Some additional stack trace:
```
Exception NUnit.Engine.NUnitEngineException,    Exception thrown executing tests in /work/JetBrains.HabitatDetector/tests/bin/Release/net9.0/JetBrains.HabitatDetector.Tests.dll
An exception occurred in the driver while running tests.
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnitEngine.NUnitEngineAdapter.Run(ITestEventListener listener, TestFilter filter) in C:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\NUnitEngineAdapter.cs:line 102
   at NUnit.VisualStudio.TestAdapter.Execution.Run(TestFilter filter, DiscoveryConverter discovery, NUnit3TestExecutor nUnit3TestExecutor) in C:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\Execution.cs:line 45
   at NUnit.VisualStudio.TestAdapter.VsTestExecution.Run(TestFilter filter, DiscoveryConverter discovery, NUnit3TestExecutor nUnit3TestExecutor) in C:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\Execution.cs:line 136
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyPath, IGrouping`2 testCases, TestFilter filter, String assemblyName) in C:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnit3TestExecutor.cs:line 303
InnerException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Number.Grisu3.BiggestPowerTen(UInt32 number, Int32 numberBits, Int32& exponentPlusOne)
   at System.Number.Grisu3.TryDigitGenCounted(DiyFp& w, Int32 requestedDigits, Span`1 buffer, Int32& length, Int32& kappa)
   at System.Number.Grisu3.TryRunCounted(DiyFp& w, Int32 requestedDigits, Span`1 buffer, Int32& length, Int32& decimalExponent)
   at System.Number.Grisu3.TryRun[Double](Double value, Int32 requestedDigits, NumberBuffer& number)
   at System.Number.FormatFloat[Double,Char](ValueListBuilder`1& vlb, Double value, ReadOnlySpan`1 format, NumberFormatInfo info)
   at System.Number.FormatFloat[Double](Double value, String format, NumberFormatInfo info)
   at System.Double.ToString(String format, IFormatProvider provider)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.AddToXml(TNode parentNode, Boolean recursive)
   at NUnit.Framework.Internal.TestResult.ToXml(Boolean recursive)
   at NUnit.Framework.Api.FrameworkController.RunTests(Action`1 callback, String filter)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(MethodInfo method, Object[] args)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.ExecuteMethod(String methodName, Type[] ptypes, Object[] args)
   at NUnit.Engine.Drivers.NUnitNetStandardDriver.Run(ITestEventListener listener, String filter)
   at NUnit.Engine.Runners.DirectTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
```

**Comment by janvorli** [comment]
@ww898 I wonder if qemu has problem with the fact that .NET reserves a lot of virtual memory address space for GC heap. That memory is not committed, just reserved, but maybe the way qemu handles it is causing the OOM.
You could try to set the GC heap hard limit to say 512MB (see https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-hard-limit) and see of that helps. Other way could be to use `ulimit -v ` to set the limit for the max virtual memory.

**Comment by alhad-deshpande** [comment]
@ww898 
I have tested with ulimit -v and export DOTNET_GCHeapHardLimit=524288. But both the options are not working. I think this looks like a QEMU Power specific issue and not a dotnet related issue as it works fine on Power hardware.

**Comment by janvorli** [comment]
@alhad-deshpande please note that the DOTNET_GCHeapHardLimit value is in hexadecimal even if you don't add 0x prefix to it. And it is in bytes. See https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-hard-limit
So your setting set the limit to approximately 5MB, which is not a usable value.

**Comment by alhad-deshpande** [comment]
@janvorli 
I missed that its hexadecimal value. Thanks about that.

**Tried by setting below values but still it fails.**

export DOTNET_GCHeapHardLimit=0x20000000 (512 MB)
export DOTNET_GCHeapHardLimit=0x40000000 (1 GB)
export DOTNET_GCHeapHardLimit=0x100000000 (4 GB)

**Comment by ww898** [comment]
Hi @janvorli, I got the same result with different values of `DOTNET_GCHeapHardLimit` and `ulimit -v` - the issue is still present.
