### ISSUE TITLE
iOS test failure on System.Tests.HalfTests.ExplicitConversion_FromSingle

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#110402]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=886168
Build error leg or test failing: System.Tests.HalfTests.ExplicitConversion_FromSingle
Pull request: https://github.com/dotnet/runtime/pull/110372

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.HalfTests.ExplicitConversion_FromSingle",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

wasm-console.log
```
[FAIL] System.Tests.HalfTests.ExplicitConversion_FromSingle(f: NaN, expected: NaN)
Assert.Equal() Failure: Values differ
Expected:   NaN
Actual:     NaN
   at System.AssertExtensions.Equal(Half expected, Half actual)
   at System.Tests.HalfTests.ExplicitConversion_FromSingle(Single f, Half expected)
   at System.Object.InvokeStub_HalfTests.ExplicitConversion_FromSingle(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[STRT] System.Tests.HalfTests.ExplicitConversion_FromSingle(f: NaN, expected: NaN)
[FAIL] System.Tests.HalfTests.ExplicitConversion_FromSingle(f: NaN, expected: NaN)
Assert.Equal() Failure: Values differ
Expected:   NaN
Actual:     NaN
   at System.AssertExtensions.Equal(Half expected, Half actual)
   at System.Tests.HalfTests.ExplicitConversion_FromSingle(Single f, Half expected)
   at System.Object.InvokeStub_HalfTests.ExplicitConversion_FromSingle(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=886168
**Error message validated:** `[[FAIL] System.Tests.HalfTests.ExplicitConversion_FromSingle`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 12/4/2024 4:57:25 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by steveharter** [comment]
Looks like a dup of https://github.com/dotnet/runtime/issues/103347 but for some reason the pattern matching didn't work.

**Comment by steveharter** [comment]
Closing as duplicate
