### ISSUE TITLE
Test failure: System.Reflection.Tests.InvokeInterpretedTests.VerifyInvokeIsUsingInterpreter_Method

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110511]
**Failed in:** [runtime-coreclr libraries-jitstress 20241207.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889277&view=ms.vss-test-web.build-test-results-tab&runId=23281310&resultId=130071&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress1_tiered-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Reflection.Tests.InvokeInterpretedTests.VerifyInvokeIsUsingInterpreter_Method
```

**Error message:**
```
 Assert.Contains() Failure: Sub-string not found
String:    "System.Exception: Here\n   at System.Refle"···
Not found: "InterpretedInvoke_Method"
```

**Stack trace:**
```
   at System.Reflection.Tests.InvokeInterpretedTests.VerifyInvokeIsUsingInterpreter_Method() in /_/src/libraries/Common/tests/System/Reflection/InvokeInterpretedTests.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs:line 1094
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT Looks like a regression from FCall -> QCall conversion
