### ISSUE TITLE
Converting from GB18030 encoded bytes to chars throws Exception

### ISSUE THREAD

**Issue by uBpringlIoNaRys** [dotnet/runtime#110521]
### Description

Converting from GB18030 encoded data to string throws an exception in net9.

### Reproduction Steps

This code throws the exception on net9 but not on net8.
```C#
using System.Text;

Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

var encoding = Encoding.GetEncoding("GB18030");

ReadOnlySpan<byte> encodedBytes = [0x95, 0x32, 0xB7, 0x37];

// This call throws, encoding GetString or GetChars as well.
var actual = encoding.GetCharCount(encodedBytes);

Console.WriteLine($"CharCount: {actual}");

var bytes = encoding.GetBytes("𠈓");
Console.WriteLine($"EncodedBytes of character match encodedBytes span: {bytes.AsSpan().SequenceEqual(encodedBytes)}");

```

### Expected behavior

The conversion from bytes to chars does not throw an exception.

### Actual behavior

```
Unhandled exception. System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Chinese Simplified (GB18030)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
   at System.Text.EncodingNLS.ThrowCharsOverflow()
   at System.Text.EncodingNLS.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.EncodingCharBuffer.AddChar(Char ch1, Char ch2, Int32 numBytes)
   at System.Text.GB18030Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.GB18030Encoding.GetCharCount(Byte* bytes, Int32 count, DecoderNLS baseDecoder)
   at System.Text.Encoding.GetCharCount(ReadOnlySpan`1 bytes)
   at Program.<Main>$(String[] args) in C:\git\Receiver\SYC_Appliance\Test\GB18030DecodeFailure\Program.cs:line 12
   
```

### Regression?

Yes

### Known Workarounds

none

### Configuration

.net 9
Windows
x64

### Other information

There was a change (https://github.com/dotnet/runtime/commit/861164ce20ffb8288365be76f8db95399973175d) that modified the if statement in `EncodingCharBuffer.AddChar`. Maybe the logic for uninitialized chars and "counting" has changed.

**Comment by uBpringlIoNaRys** [comment]
Our product supports receiving GB18030 encoded text in DICOM data. 

This error prohibits us migrating to net9. 

Is this breaking change something that would be fixed or is this encoding not supported anymore?

**Comment by am11** [comment]
Works with .NET 8 https://dotnetfiddle.net/BUQChY
Fails with .NET 9 https://dotnetfiddle.net/3N5Syf

**Comment by ericstj** [comment]
@tarekgh can you please have a look?

**Comment by tarekgh** [comment]
This is a regression from the change https://github.com/dotnet/runtime/pull/97950. I'll work on fixing it. 

CC @jkotas

**Comment by tarekgh** [comment]
This is now fixed by the PR https://github.com/dotnet/runtime/pull/111367. The fix will be released in the next 9.0 servicing release.
