### ISSUE TITLE
[mono][tvos] DataSet Xml serialization tests failing on tvos lanes

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#110771]
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707
Affected pipeline: `runtime-extra-platforms`
Job name: `tvos-arm64 Release AllSubsets_Mono`
Build error leg or test failing: `System.Data.Common.Tests`

## Crash details

```
[FAIL] System.Data.Tests.DataSetTest.DeserializeModifiedDataSet
[16:49:48.6707670] System.InvalidOperationException : There was an error generating the XML document.
[16:49:48.6726660] 2024-12-16 21:49:48.709 System.Data.Common.Tests[47911:134275559] ---- System.NotSupportedException : DataSet implementation of IXmlSerializable is not trim compatible and has been disabled in the app configuration.
[16:49:48.6727080]    at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
[16:49:48.6727580] 2024-12-16 21:49:48.710 System.Data.Common.Tests[47911:134275559]    at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o)
[16:49:48.6727850]    at System.Data.Tests.DataSetTest.DeserializeModifiedDataSet()
[16:49:48.6727960]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[16:49:48.6728360] 2024-12-16 21:49:48.710 System.Data.Common.Tests[47911:134275559]    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[16:49:48.6728680] ----- Inner Stack Trace -----
[16:49:48.6728810]    at System.Data.DataSet.System.Xml.Serialization.IXmlSerializable.WriteXml(XmlWriter writer)
[16:49:48.6729520] 2024-12-16 21:49:48.710 System.Data.Common.Tests[47911:134275559]    at System.Xml.Serialization.XmlSerializationWriter.WriteSerializable(IXmlSerializable serializable, String name, String ns, Boolean isNullable, Boolean wrapped)
[16:49:48.6729820]    at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement(Object o, ElementAccessor element, Boolean writeAccessor)
[16:49:48.6731190] 2024-12-16 21:49:48.710 System.Data.Common.Tests[47911:134275559]    at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElements(Object o, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, Boolean writeAccessors, Boolean isNullable)
[16:49:48.6732140] 2024-12-16 21:49:48.710 System.Data.Common.Tests[47911:134275559]    at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteMember(Object o, Object choiceSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc memberTypeDesc, Boolean writeAccessors)
[16:49:48.6732380]    at System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTypeElement(Object o, XmlTypeMapping xmlMapping)
[16:49:48.6732480] 2024-12-16 21:49:48.710 System.Data.Common.Tests[47911:134275559]    at System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteObject(Object o)
[16:49:48.6732590]    at System.Xml.Serialization.XmlSerializer.SerializeUsingReflection(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
[16:49:48.6732710] 2024-12-16 21:49:48.711 System.Data.Common.Tests[47911:134275559]    at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
[16:49:48.6791230] 2024-12-16 21:49:48.716 System.Data.Common.Tests[47911:134275559]
```

[ConsoleLog](https://helixr1107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2fede6af229d474fb6/System.Data.Common.Tests/1/console.babd1eb7.log?helixlogtype=result)
[CrashLog](https://helixr1107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2fede6af229d474fb6/System.Data.Common.Tests/1/net.dot.System.Data.Common.Tests.log?helixlogtype=result)

## Root cause

This seems to be introduced with https://github.com/dotnet/runtime/pull/110477 more specifically: https://github.com/dotnet/runtime/pull/110477/commits/a14993897e256b29c6b468106b03114061111940

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": ["Failed: [1-9]+[0-9]*", "net.dot.System.Data.Common.Tests"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707
**Error message validated:** `[Failed: [1-9]\d*.*(net\.dot\.System\.Data\.Common\.Tests)+`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 12/17/2024 9:01:33 AM UTC

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707
**Error message validated:** `[(Failed: )+[1-9]\d*.*(net\.dot\.System\.Data\.Common\.Tests)+`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 12/17/2024 9:27:50 AM UTC

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707
**Error message validated:** `[Failed: [1-9]\d*.*net\.dot\.System\.Data\.Common\.Tests`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 12/17/2024 9:34:35 AM UTC

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707
**Error message validated:** `[Failed: [1-9]+[0-9]* net.dot.System.Data.Common.Tests`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 12/17/2024 9:43:23 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[896707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707)|dotnet/runtime|[System.Data.Common.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=896707&view=ms.vss-test-web.build-test-results-tab&runId=23520386&resultId=186820)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by akoeplinger** [comment]
Hmm this shouldn't have happened because these tests are marked with `ConditionalFact` that uses the same feature switch as the NotSupportedException:
https://github.com/dotnet/runtime/blob/9482c1ed378dfde2f540b99cb99685396b3bd4c2/src/libraries/System.Data.Common/tests/System/Data/DataTableTest5.cs#L787

Can you check whether the AppConfig gets generated correctly?

**Comment by akoeplinger** [comment]
I wonder if we need to add the msbuild property to:
https://github.com/dotnet/runtime/blob/69d80765741a92af937f91c9c944a6b7ec56297b/eng/testing/tests.mobile.targets#L43-L48

but I'm not 100% sure why we get this mismatch between the feature switch used inside of the BCL and the test code...

**Comment by ivanpovazan** [comment]
I also noticed trimming tests have this configuration:
https://github.com/dotnet/runtime/blob/e78ee77456c94b83c83e485bb1a16a1d3d3a2573/src/libraries/System.Data.Common/tests/TrimmingTests/System.Data.Common.TrimmingTests.proj#L7-L9

**Comment by ivanpovazan** [comment]
I think the problem is related to how we split trimming+AOT builds between Helix and build machines where we have the following:

1. On build machines we only build and **don't** have `PublishTrimmed=true`. Therefore `RuntimeHostConfiguration` gets configured by only what is specified in test project files. This means that we will have only a few features configured that end up in `RuntimeHostConfiguration` and in `runtimeconfig.json`. For example `System.Data.Common.Tests.runtimeconfig.json` contains:
```json
  {
    "runtimeOptions": {
      "tfm": "net10.0",
      "includedFrameworks": [
        {
          "name": "Microsoft.NETCore.App",
          "version": "10.0.0"
        }
      ],
      "configProperties": {
        "System.Reflection.Metadata.MetadataUpdater.IsSupported": false,
        "System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported": false,
        "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": true
      }
    }
  }
```
2. We transfer both `RuntimeHostConfiguration` (via `_AppleUsedRuntimeHostConfigurationOption`)  and `runtimeconfig.json` to Helix through our "AOT on Helix" logic
3. On Helix we perform trimming and AOT compilation and we have `PublishTrimmed=true`. Therefore, Microsoft.NET.ILLink.targets set defaults for feature switches, along with https://github.com/dotnet/runtime/blob/8a25506957ae24effa9f57c7e4d5571f9e6bc9be/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets#L60 We overwrite only the feature switch values we collected during build via `_AppleUsedRuntimeHostConfigurationOption`: https://github.com/dotnet/runtime/blob/6d6f2bd36c7d5e134177383958b02522b770bd04/src/mono/msbuild/apple/data/ProxyProjectForAOTOnHelix.proj#L102-L104
and run the linker. Since we didn't specify a value for `_DataSetXmlSerializationSupport` during build, trimmer uses the default and wires `XmlSerializationIsSupported ` to `false` and removes deadcode.
4. During runtime, PlatformDetection determines which tests need to be included by reading `XmlSerializationIsSupported` from `AppContext`, but since `runtimeconfig.json` does not set it, the value will be resolved as `true` and we will run the tests which don't have XmlSerialization support - causing tests to crash

**Comment by akoeplinger** [comment]
Yeah that sounds like a reasonable explanation and is also pretty scary :)
It's why I mentioned when we talked with @kotlarmilos that I don't like this setup.

I wonder if we could only do the AOT+app build on Helix and do the publish+trim on AzDO, that one should be fast enough.

**Comment by kotlarmilos** [comment]
> I wonder if we could only do the AOT+app build on Helix and do the publish+trim on AzDO, that one should be fast enough.

Do you mean publish+trim on build machine?

**Comment by akoeplinger** [comment]
yes, publish+trim. afaik the bottleneck was on AOTing the assemblies.
