### ISSUE TITLE
[area-Tools-ILLink]: ILLinker is failing when building a mac-catalyst app

### ISSUE THREAD

**Issue by pictos** [dotnet/runtime#110714]
### Description

During the release build of the sample app of CommunityToolkit.Maui, for maccatalyst, the build breaks with a IL1012 error, and doesn't provide any helpful log message.

### Reproduction Steps

1. Checkout this repo https://github.com/CommunityToolkit/Maui/tree/feature/sl-dotnet-nine
2. checkout at the `feature/sl-dotnet-nine` branch
3. (IF you want you can remove other TFM and just build for macCatalyst)
4. build the sample app on terminal `dotnet build --no-incremental /bl -c Release`
5. see the error.

### Expected behavior

The project builds.

### Actual behavior

The build breaks.

### Other information

[msbuild.binlog.zip](https://github.com/user-attachments/files/18137857/msbuild.binlog.zip)

**Comment by vitek-karas** [comment]
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Mono.Linker.Dataflow.TrimAnalysisMethodCallPattern.Merge(ValueSetLattice`1 lattice, TrimAnalysisMethodCallPattern other)
   at Mono.Linker.Dataflow.TrimAnalysisPatternStore.Add(TrimAnalysisMethodCallPattern pattern)
   at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams)
```

I have a repro package for mac - ping me when you get to this.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/runtime/issues/110753 contains the explanation of this failure.

@ivanpovazan is there a way to change an option to stop using managed registrar, that might be a viable workaround.

**Comment by ivanpovazan** [comment]
Yes, here are the .NET 9 release notes explaining the change and the way to opt-out from using managed-static registrar: https://github.com/xamarin/xamarin-macios/wiki/.NET-9-release-notes#type-registrar-managed-static-as-the-new-default

**Comment by agocke** [comment]
Closing as by-design in the linker
