### ISSUE TITLE
[apple] Failure in System.Globalization.Tests.StringNormalizationTests.Normalize tests

### ISSUE THREAD

**Issue by BrzVlad** [dotnet/runtime#110720]
This happens in test suites: `System.Globalization.Extensions.iOS.Tests` and `System.Globalization.Extensions.Tests`
It impacts all apple lanes. Other configs not affected. Fails on `maccatalyst_x64`, `maccatalyst_arm64`, `iossimulator_x64`, `ios-arm64`.

Sample failure:
```
[FAIL] System.Globalization.Tests.StringNormalizationTests.Normalize(value: "ÄÇ", normalizationForm: FormC, expected: "ÄÇ")
[04:39:50.5756830] Assert.Equal() Failure: Values differ
[04:39:50.5756940] Expected: 2
[04:39:50.5757040] Actual:   0
[04:39:50.5757150] 2024-12-15 01:39:50.661 System.Globalization.Extensions.iOS.Tests[94400:124587059]    at System.Globalization.Tests.StringNormalizationTests.Normalize(String value, NormalizationForm normalizationForm, String expected)
[04:39:50.5757500]    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[04:39:50.5757630] 2024-12-15 01:39:50.661 System.Globalization.Extensions.iOS.Tests[94400:124587059]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[04:39:50.5822700] 2024-12-15 01:39:50.668 System.Globalization.Extensions.iOS.Tests[94400:124587059] 
```

Regressed recently. Most likely caused by https://github.com/dotnet/runtime/commit/a5af0ab77caa5ed7a6844fc5f4f459e5edfe23d3

**Comment by BrzVlad** [comment]
@tarekgh Any idea what is going on and how the fix should look like ?

**Comment by tarekgh** [comment]
@BrzVlad could you please disable the failing test against an active issue till we investigate?  

CC @matouskozak if he can help till, I am back?

**Comment by tarekgh** [comment]
I think I understand what the problem is. 

The following line expect returning the right length:
https://github.com/dotnet/runtime/blob/3aa1ec5bb1f50f0a1bed9cfcac8734f742bcf24b/src/libraries/System.Private.CoreLib/src/System/Globalization/Normalization.Icu.cs#L181

while the iOS implementation doesn't allow empty buffers while it should do. 
https://github.com/dotnet/runtime/blob/3aa1ec5bb1f50f0a1bed9cfcac8734f742bcf24b/src/native/libs/System.Globalization.Native/pal_normalization.m#L73

@BrzVlad I'll try to fix this at first chance. I would appreciate it if you could disable the test against active issue till, I fix it. Sorry for the inconvenience,

**Comment by tarekgh** [comment]
I opened the PR https://github.com/dotnet/runtime/pull/110723. I didn't test it because I don't have the environment setup, but I believe it will fix the issue.

**Comment by BrzVlad** [comment]
@tarekgh Doesn't seem like the PR is fixing the tests. Will disable the test until you have more time to investigate. https://github.com/dotnet/runtime/pull/110725.

cc @ivanpovazan
