### ISSUE TITLE
Test failure: JIT/Stress/ABI/stubs_do/stubs_do.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110763]
**Failed in:** [runtime-coreclr crossgen2 20241215.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=895911&view=ms.vss-test-web.build-test-results-tab&runId=23495208&resultId=115599&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - JIT/Stress/ABI/stubs_do/stubs_do.cmd
```

**Error message:**
```
 
cmdLine:C:hwBA6009F7wA14008EFeJITJIT_do../Stress/ABI/stubs_do/stubs_do.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 12/16/2024 7:19:09 AM, end: 12/16/2024 7:49:09 AM)

Return code:      -100
Raw output file:      C:hwBA6009F7wA14008EFuploadsStressABIstubs_dooutput.txt
Raw output:
BEGIN EXECUTION
stubs_do.dll
        1 file(s) copied.
 7:19:09.33
Response file: C:hwBA6009F7wA14008EFeJITStressABIstubs_dostubs_do.dll.rsp
C:hwBA6009F7wA14008EFeJITStressABIstubs_doIL-CG2stubs_do.dll
-o:C:hwBA6009F7wA14008EFeJITStressABIstubs_dostubs_do.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hwBA6009F7pSystem.*.dll
-r:C:hwBA6009F7pMicrosoft.*.dll
-r:C:hwBA6009F7p\xunit.*.dll
-r:C:hwBA6009F7pmscorlib.dll
-r:C:hwBA6009F7p
etstandard.dll
"Running CrossGen2:  "C:hwBA6009F7pcrossgen2crossgen2.exe" @"C:hwBA6009F7wA14008EFeJITStressABIstubs_dostubs_do.dll.rsp"   -r:C:hwBA6009F7wA14008EFeJITJIT_doIL-CG2*.dll  -r:C:hwBA6009F7wA14008EFeJITStressABIstubs_doIL-CG2*.dll"
Emitting R2R PE file: C:hwBA6009F7wA14008EFeJITStressABIstubs_dostubs_do.dll
"Running R2RDump:  "dotnet" "C:hwBA6009F7p
2rdump
2rdump.dll" --header --sc --in C:hwBA6009F7wA14008EFeJITStressABIstubs_dostubs_do.dll --out C:hwBA6009F7wA14008EFeJITStressABIstubs_dostubs_do.dll.r2rdump --val"
 7:19:10.04
 "C:hwBA6009F7pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  stubs_do.dll --instantiatingstubs --unboxingstubs --sharedgenericunboxingstubs --num-calls 100 --max-params 5 --no-ctrlc-summary 
Stressing instantiatingstubs
Stressing unboxingstubs
Stressing sharedgenericunboxingstubs
OSVersion: Microsoft Windows NT 10.0.14393.0
OSArchitecture: X64
ProcessArchitecture: X64
Selecting win64 ABI
50 callers done
100 callers done
  Done with 0 mismatches

cmdLine:C:hwBA6009F7wA14008EFeJITJIT_do../Stress/ABI/stubs_do/stubs_do.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 12/16/2024 7:19:09 AM, end: 12/16/2024 7:49:09 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> C:hwBA6009F7wA14008EFeJITJIT_do../Stress/ABI/stubs_do/stubs_do.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor2|0_3(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by mangod9** [comment]
Closing an old issue.
