### ISSUE TITLE
Test failure: System.Net.Quic.Tests.MsQuicTests.ManagedAVE_MinimalFailingTest

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110896]
**Failed in:** [runtime-coreclr libraries-jitstress 20241220.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=901266&view=ms.vss-test-web.build-test-results-tab&runId=23656466&resultId=169603&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.MsQuicTests.ManagedAVE_MinimalFailingTest
    - System.Net.Quic.Tests.MsQuicTests.OpenStreamAsync_BlocksUntilAvailable_PeerClosesWritingUnidirectional
    - System.Net.Quic.Tests.MsQuicTests.Read_ConnectionAbortedByUser_Throws
    - System.Net.Quic.Tests.MsQuicTests.CallDifferentWriteMethodsWorks
    - System.Net.Quic.Tests.MsQuicTests.DisposingConnection_OK
    - System.Net.Quic.Tests.MsQuicTests.Read_ConnectionAbortedByPeer_Throws
    - System.Net.Quic.Tests.MsQuicTests.QuicRootedObjectGetReleased
    - System.Net.Quic.Tests.MsQuicTests.ConnectWithServerCertificateCallback
    - System.Net.Quic.Tests.QuicConnectionTests.Connection_AwaitsStream_ConnectionSurvivesGC
    - System.Net.Quic.Tests.QuicConnectionTests.GetStreamCapacity_OpenCloseStream_CountsCorrectly
    - System.Net.Quic.Tests.QuicConnectionTests.AcceptStreamAsync_ConnectionDisposed_Throws
    - System.Net.Quic.Tests.QuicListenerTests.TwoListenersOnSamePort_DisjointAlpn_Success
    - System.Net.Quic.Tests.QuicListenerTests.Listener_AwaitsConnection_ListenerSurvivesGC
    - System.Net.Quic.Tests.QuicListenerTests.Listener_Backlog_Success
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ClientConnects_CancelIgnored
    - System.Net.Quic.Tests.QuicListenerTests.Listener_BacklogLimitRefusesConnection_ClientThrows
    - System.Net.Quic.Tests.QuicListenerTests.Listener_AlpnNarrowingDown_Success
    - System.Net.Quic.Tests.QuicListenerTests.Listener_IPv6Any_Accepts_IPv4
    - System.Net.Quic.Tests.QuicListenerTests.Listener_Backlog_Success_IPv6
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Timeout_Roundtrips
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnReadableStream_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 659
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 761
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 796
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 553
   at System.Net.Quic.Tests.MsQuicTests.<ManagedAVE_MinimalFailingTest>g__GetStreamIdWithoutStartWorks|31_0() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 1204
   at System.Net.Quic.Tests.MsQuicTests.ManagedAVE_MinimalFailingTest() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 1212
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Same as #110898. 
Based on kusto data seems like a fluke, all the QUIC tests failed on timeout on 21.12. and 27.12. Closing, we can revisit if it starts showing up on our CI board.
