### ISSUE TITLE
Test failure: System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#110898]
**Failed in:** [runtime-coreclr libraries-jitstress 20241220.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=901266&view=ms.vss-test-web.build-test-results-tab&runId=23656466&resultId=169628&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-no_tiered_compilation-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ThrowingCallbackOde_KeepRunning
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: CallbackError
Actual:   ConnectionIdle
```

**Stack trace:**
```
   at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 68
   at System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 383
   at System.Net.Quic.Tests.MsQuicTests.CertificateCallbackThrowPropagates() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 392
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Based on kusto data seems like a fluke, all the QUIC tests failed on timeout on 21.12. and 27.12. Closing, we can revisit if it starts showing up on our CI board.
