### ISSUE TITLE
HttpClient may leak UnobservedTaskException in CheckUsabilityOnScavenge

### ISSUE THREAD

**Issue by salvois** [dotnet/runtime#110951]
### Description

We have a .NET 9 console application (namely, a Windows Service running on Microsoft.Extensions.Hosting.BackgroundService, hosted by Windows Server 2019 on x86-64) making multiple HTTP requests (GETs or POSTs) using a singleton instance of HttpClient created during service startup using `new HttpClient { Timeout = TimeSpan.FromMinutes(10) };`

All otherwise unhandled application exceptions are handled by a top level catch that does any logging and deadlettering required for our processing. We also register a handler to `TaskScheduler.UnobservedTaskException` to log any exception that may leak, usually from our code forgetting an await.

In several cases, under heavy load, our handler for UnobservedTaskException's received exceptions from what appear to be the internals of HttpClient itself, such as in the following stack trace, apparently related to #61256:

```
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
— End of inner exception stack trace —
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|39_0()
```

We also experienced #104324 when the application ran on .NET 8, and upgraded to .NET 9 hoping to solve the issue, but we are still receiving the exception about `CheckUsabilityOnScavenge` nonetheless.

### Reproduction Steps

Unfortunately we have not been able to reproduce the problem deterministically. It seems related to our system being under heavy load.

### Expected behavior

We expect no unobserved exceptions, even less exceptions from internal implementation.

### Actual behavior

An UnobservedTaskException is caught by the handler registered to `TaskScheduler.UnobservedTaskException`, which is very scary to us because in our mind "unobserved task excetion == possible data loss" 😄 (due to the deadletter mechanism being bypassed).
If I understand the implementation correctly (which I don't fully, I must confess), that should not be the case in our scenario, though, because the exception seems to be thrown when the HTTP connection is about to be dropped anyway, and our application should proceed normally. Please advise whether this is the case.

### Regression?

We don't have memory of this issue nor #104324 prior to switching to .NET 8 (the application used .NET 6, .NET 5, .NET Core 2 and .NET Framework 4.6.2 before).

### Other information

Based on a quick review of the source of `CheckUsabilityOnScavenge` in [HttpConnection](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs), I think a solution similar to PR #104335 may do the job. I can try to create a pull request based on it.

**Comment by salvois** [comment]
Should it matter, I noticed our application also starts a SignalR client created as follows, to a web app hosted by IIS with Windows authentication enabled:

```
_hubConnection = new HubConnectionBuilder()
    .WithUrl("https://example.com/app/notificationHub", options => options.UseDefaultCredentials = true)
    .WithAutomaticReconnect(new RandomRetryPolicy())
    .Build();

public class RandomRetryPolicy : IRetryPolicy
{
    public TimeSpan? NextRetryDelay(RetryContext retryContext) => TimeSpan.FromSeconds(Random.Shared.Next(1, 5));
}
```

Maybe our unobserved exception comes from an HttpClient created by the SignalR client library (if it works like this). We have a log about a re-enstablished SignalR connection on the same machine 40 seconds after the offending UnobservedTaskException.

**Comment by MihaZupan** [comment]
That fact it's SignalR shouldn't matter, but `with Windows authentication enabled` could.

Auth is a thing that happens after the `PrepareForReuse` call. We'll call into here
https://github.com/dotnet/runtime/blob/6045e29bbefa63b58ccd5502f057ae452f3c83af/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L76-L78
, but doing the actual send is the first thing we do, so that should be fine as well.

That method also does some manual connection management ([this bit](https://github.com/dotnet/runtime/blob/6045e29bbefa63b58ccd5502f057ae452f3c83af/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L98-L108)), but that also looks fine at first glance.

**Comment by antonfirsov** [comment]
I suspect that there is a condition where we don't hit [the catch block in `ReadAheadWithZeroByteReadAsync()`](https://github.com/dotnet/runtime/blob/2d1588d3a03f32064f71deb1ec32ed6590dae89c/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L270-L275) and also don't observe exceptions from the failing `_readAheadTask` later.

Stress tests are unlikely to catch this, since connections are not spending enough time in idle state there to be scavenged.

**Comment by meriffa** [comment]
@salvois 

Hi Salvatore,

Is this issue still open on your side? I was wandering if it is possible to get a memory dump at the time of the `IOException` generation.

Let me know if you want to take this offline.

Thanks,

Marian.

**Comment by salvois** [comment]
Hello @meriffa ,
unfortunately (or fortunately!) the issue is pretty random and very rare. I can't ever recall last time it occurred, as we only observed it just a few times, so getting a memory dump is not really feasible for me.
Speaking of memory, that triggers an idea to me: what if the machine was in a low memory condition? We have also been experiencing low memory issues. Could an out of memory exception explain what we observed?
Thanks,
   Salvo

**Comment by meriffa** [comment]
@salvois 

Salvo,

The fact that this is issue rare and very erratic was the main reason I reached out to you. This is a very interesting scenario for me to try to troubleshoot.

In the next couple of weeks I will try to put together a sample that mimics your issue in a test environment and I will try to find a non-obtrusive way to capture one or more memory (core) dumps at the time when the `IOException` is thrown and the `TaskScheduler.UnobservedTaskException` handler is called. I'll try this on Linux, even though you are using Windows service.

The idea is if there is a core dump taken very close to the condition that causes the exception, we might be able to tell what exactly is causing this error and even be able to devise a scenario to reproduce this consistently. E.g. we can see what are the active / pending HttpClient connections, where they are coming from and for how long they are running.

On a side note - I doubt the system memory utilization (low memory) has any impact on this issue. This would assume that HttpClient uses GC information (allocation budget, memory pressure) to adjust the connection scavenging logic. I very much doubt this is the case.

Let me know if you are interested in my test findings later on.

Thanks,

Marian.

**Comment by salvois** [comment]
Hi @meriffa , sorry for the shamefully late reply.
Thanks for looking into it! 

Just to clarify my thinking about the memory issue: I was not assuming that how HttpClient works is affected by memory information in any way, rather than an OutOfMemoryException might be responsible for the erratic behavior we observed.

From what I got from the source, and thanks to @MihaZupan explanations, the code is pretty much safe from exceptions, that is, anything between the point the offending task is created and where it's observed can not normally throw exceptions, or they are handled where needed. However OOM exceptions could be thrown unexpectedly by any innocent looking code, hence my speculation. Not that I'm very confident about it though.

Of course I'm very interested in your findings, even if it was just for personal culture.
Best,
   Salvo

**Comment by meriffa** [comment]
@salvois

Salvo,

I managed to spend some time on the original issue (`UnobservedTaskException`) this week. Although you last mentioned OOM and that means there might be multiple issues.

My initial thoughts were:

1. Capture a core dump when the hidden `HttpClient` exception occurs.
2. Check the active tasks & state machines from the core dump.
3. Check the `HttpClient`, `HttpConnection`, `HttpRequestMessage`, and `HttpResponseMessage` instances from the core dump.

The idea is to see what the application state is in terms of `HttpClient` connections and requests when the `CheckUsabilityOnScavenge` -> `System.IO.IOException` exception appears. It is possible that there is some random remote service slowness that results in a spike in the number of active connections under heavy load. Or it might be something else, but one can get some idea of what is happening at this time.

Unfortunately, I could not find a suitable solution regarding p.1. I added a core dump capture (using Diagnostics Port) inside the `TaskScheduler.UnobservedTaskException` event handler, but this event is called from the finalizer thread following a GC collection. This means that by the time this event fires, the application state is very different, and even some relevant object instances might be GC collected.
In theory, another approach is to attach a custom Profiler and monitor for `System.IO.IOException` allocations and trigger a core dump when such an instance contains `System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>` in its stack trace. The main issue with this approach is what the performance impact of the profiler on the application is going to be.

Regarding p.2 & p.3 I have simple scripts / tools to extract this information.

I am not planning to do any further analysis of this issue (unless I get a good idea of how to capture a core dump when the exception happens).

Thanks,

Marian.

**Comment by MihaZupan** [comment]
I suppose an OOM could explain this, but then I'd be suspicious of why you were only seeing this specific one.
E.g. in networking we use a [`LogExceptions` helper](https://grep.app/search?f.repo=dotnet%2Fruntime&q=LogExceptions%28) in a bunch of places, and that could throw while trying to hook up the continuation that's supposed to observe the exception.

**Comment by karelz** [comment]
Triage: While it is interesting for us, there is no repro from anyone, so we need to wait for another customer report.
Moving to Future.
