### ISSUE TITLE
Unobserved ObjectDisposedException when reading HTTPS stream

### ISSUE THREAD

**Issue by salvois** [dotnet/runtime#110998]
### Description

We have a self-contained .NET 9 console application (namely, a Windows Service running on Microsoft.Extensions.Hosting.BackgroundService, hosted by Windows Server 2019 on x86-64) making multiple HTTP requests (GETs or POSTs) using a singleton instance of HttpClient created during service startup using `new HttpClient { Timeout = TimeSpan.FromMinutes(10) };`

All otherwise unhandled application exceptions are handled by a top level catch that does any logging and deadlettering required for our processing. We also register a handler to `TaskScheduler.UnobservedTaskException` to log any exception that may leak, usually from our code forgetting an await.

In several cases, under heavy load, our handler for UnobservedTaskException's received exceptions from what appear to be the internals of HttpClient itself, due to the inner stream of an SslStream having being disposed, such as in the following stack trace:

```
System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
```

### Reproduction Steps

Unfortunately we have not been able to reproduce the problem deterministically. It seems related to our system being under heavy load.

### Expected behavior

We expect no unobserved exceptions, even less exceptions from internal implementation.

### Actual behavior

An UnobservedTaskException is caught by the handler registered to TaskScheduler.UnobservedTaskException, causing our application to escape its usual error handling, leading to possible data loss.

### Regression?

From our logs this happened both on .NET 8 and on .NET 9, and never before 2024-11-29 (before October the application used .NET 6).

**Comment by MihaZupan** [comment]
The unobserved task exception is likely a duplicate of #80116 (see `RawConnectionStream.ReadAsync` in the stack trace).

The `Cannot access a disposed object.` is a duplicate of https://github.com/dotnet/runtime/issues/31254#issuecomment-2183191583.

Both should be harmless (aside from being annoying).

**Comment by salvois** [comment]
Oh, sorry for the duplicate! Many thanks for your feedback
