### ISSUE TITLE
Crash when CustomControl Property use StaticResource

### ISSUE THREAD

**Issue by albilaga** [dotnet/runtime#111096]
### Description

I have some CustomControl like this 
```cs
public class CustomButton : ContentView
{
	//other code
	private ButtonConfiguration? _containedButtonConfiguration;
	public ButtonConfiguration? ButtonConfig
	{
		get => _containedButtonConfiguration;
		set
		{
			_containedButtonConfiguration = value;
			Draw();
		}
	}

	public CustomButton()
	{
		HorizontalOptions = VerticalOptions = LayoutOptions.Start;
	}
}
```

and `ButtonConfiguration` is something like this
```cs
[AcceptEmptyServiceProvider]
public abstract class ButtonConfiguration : IMarkupExtension<ButtonConfiguration>
{
	public abstract ButtonConfiguration BasedOn { set; }

	public abstract View ComposeView();
	public ButtonConfiguration ProvideValue(IServiceProvider serviceProvider)
	{
		return this;
	}

	object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
	{
		return ProvideValue(serviceProvider);
	}

	public abstract void ApplyGestureHandler(View parentView, GestureRecognizer customGestureRecognizer);
}
```

and some ButtonConfiguration is like this
```cs
public class IconButtonConfiguration : ButtonConfiguration
{
	public Color? Color { get; set; }
	public string? IconGlyph { get; set; } = string.Empty;
	public double IconSize { get; set; } = 14;
}
```
and when I set style in `App.xaml`
```xml
<ResourceDictionary>
            <system:Double x:Key="LargeIconButtonFontSize">24</system:Double>
            <config:IconButtonConfiguration
                x:Key="DefaultIconButtonConfig"
                IconSize="{StaticResource LargeIconButtonFontSize}"
                SpacingEnabled="True"
                Color="Black" />
        </ResourceDictionary>
```
this will cause crash when in Release (both on Android and iOS). Debug working fine. But if I set like this
```xml
<ResourceDictionary>
            <system:Double x:Key="LargeIconButtonFontSize">24</system:Double>
            <config:IconButtonConfiguration
                x:Key="DefaultIconButtonConfig"
                IconSize="18"
                SpacingEnabled="True"
                Color="Black" />
        </ResourceDictionary>
```
it is working fine in Release. Not really sure what is the cause of this

### Steps to Reproduce

1. Clone https://github.com/albilaga/mauitest
2. Run android or iOS project in Release. This will crash

### Link to public reproduction project repository

https://github.com/albilaga/mauitest

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS, Android

### Affected platform versions

iOS and Android

### Did you find any workaround?

Hard code the value instead of using StaticResource but this mean then when refactoring need to be careful

### Relevant log output

https://github.com/dotnet/runtime/issues/111096

**Comment by vitek-karas** [comment]
@BrzVlad for possible ideas how to diagnose this further.

**Comment by albilaga** [comment]
@vitek-karas I don't think this is only affecting iOS as Android also have same issue

**Comment by albilaga** [comment]
Stacktace for Android
```
FATAL EXCEPTION: main
Process: com.companyname.mauitest, PID: 13490
android.runtime.JavaProxyThrowable: [System.InvalidProgramException]: Invalid IL code in mauitest.App:InitializeComponent (): IL_006c: stloc.s   6
at mauitest.App..ctor + 0x6(Unknown Source)
at Unknown.Unknown(Unknown Source)
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor + 0x0(Unknown Source)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs + 0x24(Unknown Source)
at System.Reflection.RuntimeConstructorInfo.Invoke + 0x50(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor + 0x45(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain + 0x3f(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache + 0x61(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite + 0x4f(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve + 0x26(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor + 0x55(Unknown Source)
at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider+ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd + 0x48(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService + 0xd(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService + 0xd(Unknown Source)
at Microsoft.Maui.MauiContext+WrappedServiceProvider.GetService + 0x2c(Unknown Source)
at Microsoft.Maui.MauiContext+WrappedServiceProvider.GetService + 0x2c(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService + 0x28(Unknown Source)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService + 0xb(Unknown Source)
at Microsoft.Maui.MauiApplication.OnCreate + 0x4a(Unknown Source)
at Android.App.Application.n_OnCreate + 0x8(Unknown Source)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V + 0x5(Unknown Source)
at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:27)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
