### ISSUE TITLE
Some adjustment rules are ambiguous in TimeZoneInfo.GetSystemTimeZones on unix

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#11421]
Run the following code snippet on macOS:
```csharp
foreach (var tmz in TimeZoneInfo.GetSystemTimeZones())
    var tmzClone = TimeZoneInfo.FromSerializedString(tmz.ToSerializedString ());
```
**Expected:**
no exceptions (just like on Windows).

**Actual:**
```
Unhandled Exception: System.Runtime.Serialization.SerializationException: An error occurred while deserializing the object.  The serialized data is corrupt. ---> System.InvalidTimeZoneException: The elements of the AdjustmentRule array must be in chronological order and must not overlap.
   at System.TimeZoneInfo.ValidateTimeZoneInfo(String id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, Boolean& adjustmentRulesSupportDst)
   at System.TimeZoneInfo..ctor(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime)
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
```

The problem is - some (well, almost all of them) adjustment rules are overlapped, run this to find out which ones:
```csharp
foreach (var tmz in TimeZoneInfo.GetSystemTimeZones())
{
    var rules = tmz.GetAdjustmentRules();
    var prev = rules.First();
    foreach (var current in rules.Skip(1))
    {
        if (current.DateStart <= prev.DateEnd)	
            Console.WriteLine($"ERR: {tmz.Id}, CurrentStart={current.DateStart}, PrevEnd={prev.DateEnd}");
        prev = current;
    }
}
```
so the first snippet crashes here: https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/shared/System/TimeZoneInfo.cs#L1974-L1978

Possible fixes:
1) Change `<=` to `<`
2) Add a minute/second/tick to all "StartDate"

**Comment by joperezr** [comment]
Given @tarekgh's suggestion above and the lack of activity here I'll go ahead and close this one for now. If the suggestion doesn't work or you disagree feel free to reopen.

**Comment by tarekgh** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/19794 anyway.
