### ISSUE TITLE
[Linux/arm64] System.Net.Http.Functional.Tests failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#11627]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/59/consoleFull

Including VM assert:
```
Assert failure(PID 33063 [0x00008127], Thread: 37956 [0x9444]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
```

Partial log:
```
04:29:37 >>>>> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Net.Http.Functional.Tests
04:29:37 
04:29:37 Running tests in /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Net.Http.Functional.Tests/netcoreapp-Linux-Release-arm64
04:29:37 timeout --kill-after=30s 20m ./RunTests.sh /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64
04:29:37 
04:29:37 ./RunTests.sh: line 110: ulimit: core file size: cannot modify limit: Operation not permitted
04:29:37 ----- start 04:28:33 =============== To repro directly: =====================================================
04:29:37 pushd .
04:29:37 #!/usr/bin/env bash export COMPlus_TieredCompilation=0
04:29:37 chmod +x /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Net.Http.Functional.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
04:29:37 popd
04:29:37 ===========================================================================================================
04:29:37 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Net.Http.Functional.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Net.Http.Functional.Tests/netcoreapp-Linux-Release-arm64
04:29:37 xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27204.0)
04:29:37 [37m  Discovering: System.Net.Http.Functional.Tests (method display = ClassAndMethod, method display options = None)
04:29:37 [m[37m  Discovered:  System.Net.Http.Functional.Tests (found 629 of 920 test cases)
04:29:37 [m[37m  Starting:    System.Net.Http.Functional.Tests (parallel test collections = on, max threads = 46)
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.MakeAndFaultManyRequests [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.MakeAndFaultManyRequests [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.UnreadResponseMessage_Collectible [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.SingleClient_ManyGets_Async [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.CreateAndDestroyManyClients [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.ManyClients_ManyPosts_Async [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.ManyClients_ManyGets [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.SingleClient_ManyGets_Sync [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.ManyClients_ManyPosts_Async [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.SingleClient_ManyGets_Sync [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.UnreadResponseMessage_Collectible [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.ManyClients_ManyGets [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.SingleClient_ManyGets_Async [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.CreateAndDestroyManyClients [SKIP]
04:29:37 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestClientCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestClientCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestClientCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestClientCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestCertificates"
04:29:37 [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
04:29:37 [m[37m      Condition(s) not met: "CanTestCertificates"
04:29:37 [mCLR: Managed code called FailFast, saying "[This assert catches satellite assembly build/deployment problems - report this message to your build lab & loc engineer]
04:29:37 GetSatelliteAssembly failed for culture en-US and version 4.1.1.0 of assembly System.Net.Security with error code 0x80131509
04:29:37 Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Net.Security.resources, Version=4.1.1.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509 (COR_E_INVALIDOPERATION))
04:29:37 File name: 'System.Net.Security.resources, Version=4.1.1.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
04:29:37    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
04:29:37    at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
04:29:37 
04:29:37 
04:29:37 
04:29:37    at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
04:29:37    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
04:29:37    at System.Resources.ResourceManager.GetString(String name)
04:29:37    at System.SR.GetResourceString(String resourceKey, String defaultString) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/Common/src/System/SR.cs:line 29
04:29:37    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 250
04:29:37    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 158
04:29:37    at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 841
04:29:37    at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 729
04:29:37    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 749
04:29:37    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 965
04:29:37    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 1111
04:29:37    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/FixedSizeReader.cs:line 72
04:29:37    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
04:29:37    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
04:29:37    at System.Threading.ThreadPoolGlobals.<>c.<.cctor>b__6_0(Object state)
04:29:37    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1040
04:29:37    at System.Threading.ThreadPoolWorkQueue.Dispatch()
04:29:37    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()"
04:29:37 Assertion Failed
04:29:37 [This assert catches satellite assembly build/deployment problems - report this message to your build lab & loc engineer]
04:29:37 GetSatelliteAssembly failed for culture en-US and version 4.1.1.0 of assembly System.Net.Security with error code 0x80131509
04:29:37 Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Net.Security.resources, Version=4.1.1.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'. An operation is not legal in the current state. (Exception from HRESULT: 0x80131509 (COR_E_INVALIDOPERATION))
04:29:37 File name: 'System.Net.Security.resources, Version=4.1.1.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a'
04:29:37    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
04:29:37    at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
04:29:37 
04:29:37 
04:29:37 
04:29:37    at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
04:29:37    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
04:29:37    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
04:29:37    at System.Resources.ResourceManager.GetString(String name)
04:29:37    at System.SR.GetResourceString(String resourceKey, String defaultString) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/Common/src/System/SR.cs:line 29
04:29:37    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 250
04:29:37    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 158
04:29:37    at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 841
04:29:37    at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 729
04:29:37    at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 749
04:29:37    at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 965
04:29:37    at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/Security/SslState.cs:line 1111
04:29:37    at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Security/src/System/Net/FixedSizeReader.cs:line 72
04:29:37    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
04:29:37    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
04:29:37    at System.Threading.ThreadPoolGlobals.<>c.<.cctor>b__6_0(Object state)
04:29:37    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1040
04:29:37    at System.Threading.ThreadPoolWorkQueue.Dispatch()
04:29:37    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
04:29:37 
04:29:37 
Assert failure(PID 33063 [0x00008127], Thread: 37956 [0x9444]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
04:29:37     File: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/src/vm/excep.cpp Line: 165
04:29:37     Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 
04:29:37 
04:29:37 
Assert failure(PID 33063 [0x00008127], Thread: 37956 [0x9444]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
04:29:37     File: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/src/vm/excep.cpp Line: 165
04:29:37     Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 
04:29:37 
04:29:37 Assert failure(PID 33063 [0x00008127], Thread: 37389 [0x920d]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
04:29:37     File: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/src/vm/excep.cpp Line: 165
04:29:37     Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 
04:29:37 
04:29:37 Assert failure(PID 33063 [0x00008127], Thread: 37389 [0x920d]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
04:29:37     File: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/src/vm/excep.cpp Line: 165
04:29:37     Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 
04:29:37 
04:29:37 Assert failure(PID 33063 [0x00008127], Thread: 38054 [0x94a6]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
04:29:37     File: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/src/vm/excep.cpp Line: 165
04:29:37     Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 
04:29:37 
04:29:37 Assert failure(PID 33063 [0x00008127], Thread: 38054 [0x94a6]): g_fEEShutDown >= ShutDown_Finalize2 || !"This should not be called unless we are in the last phase of shutdown!"
04:29:37     File: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/src/vm/excep.cpp Line: 165
04:29:37     Image: /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
04:29:37 
04:29:37 ./RunTests.sh: line 127: 33063 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.dll System.Net.Http.Functional.Tests.dll -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
04:29:37 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Net.Http.Functional.Tests/netcoreapp-Linux-Release-arm64
04:29:37 ----- end 04:29:15 ----- exit code 134 ----------------------------------------------------------
04:29:37 exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

**Comment by BruceForstall** [comment]
This is obsolete
