### ISSUE TITLE
`System.Diagnostics.Tests.EventLogConfigurationTests.SetProperties_SaveChanges_NotAdmin_Throws` throws wrong exception type

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#1167]
When run from unelevated prompt, the test runs but fails with the wrong type of exception thrown:
```cs
System.Diagnostics.Tests.EventLogConfigurationTests.SetProperties_SaveChanges_NotAdmin_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   typeof(System.Diagnostics.Eventing.Reader.EventLogException): Unknown error (0x7ffc)
      ---- System.Diagnostics.Eventing.Reader.EventLogException : Unknown error (0x7ffc)
      Stack Trace:
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\EventLogException.cs(47,0): at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\NativeWrapper.cs(197,0): at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtSaveChannelConfig(EventLogHandle channelConfig, Int32 flags)
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\EventLogConfiguration.cs(259,0): at System.Diagnostics.Eventing.Reader.EventLogConfiguration.SaveChanges()
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\tests\System\Diagnostics\Reader\EventLogConfigurationTests.cs(118,0): at System.Diagnostics.Tests.EventLogConfigurationTests.<>c__DisplayClass1_0.<SetProperties_SaveChanges_NotAdmin_Throws>b__0()
        ----- Inner Stack Trace -----
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\EventLogException.cs(47,0): at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\NativeWrapper.cs(197,0): at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtSaveChannelConfig(EventLogHandle channelConfig, Int32 flags)
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\EventLogConfiguration.cs(259,0): at System.Diagnostics.Eventing.Reader.EventLogConfiguration.SaveChanges()
        C:\Users\gotos\source\repos\runtime\src\libraries\System.Diagnostics.EventLog\tests\System\Diagnostics\Reader\EventLogConfigurationTests.cs(118,0): at System.Diagnostics.Tests.EventLogConfigurationTests.<>c__DisplayClass1_0.<SetProperties_SaveChanges_NotAdmin_Throws>b__0()
```

Ran on Windows 10 Pro Insiders build (19536), Korean (ko-KR).

**Comment by danmosemsft** [comment]
This may be a Windows bug. It means that `EvtSaveChannelConfig` failed, but `GetLastError()` did not return ERROR_ACCESS_DENIED. I cannot decode `0x7ffc`.

The test does assume you have an event log named "Application" (even in ko-KR) but if that wasn't the case I expect other tests would fail.

Perhaps the simplest thing here would be to disable the test except on en-US.

**Comment by Gnbrkm41** [comment]
Huh, after changing the system/user locale to en-US, I'm getting a slightly different result:
```
 System.Diagnostics.Tests.EventLogConfigurationTests.SetProperties_SaveChanges_NotAdmin_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   typeof(System.Diagnostics.Eventing.Reader.EventLogException): Unknown error (0x7ffa)
      ---- System.Diagnostics.Eventing.Reader.EventLogException : Unknown error (0x7ffa)
```

**Comment by Gnbrkm41** [comment]
Which `Application` event log is it, exactly? The one under `Windows Logs` have been renamed to "Application" once I've changed the locale, but the one under `Applications and Services Logs` is still named "응용 프로그램" ("Application" in Korean).

**Comment by Gnbrkm41** [comment]
Changed back to ko-KR, and getting a different code again:
```
Assert.Throws() Failure
      Expected: typeof(System.UnauthorizedAccessException)
      Actual:   typeof(System.Diagnostics.Eventing.Reader.EventLogException): Unknown error (0x7ff8)
      ---- System.Diagnostics.Eventing.Reader.EventLogException : Unknown error (0x7ff8)
```

**Comment by Gnbrkm41** [comment]
Updated to 19541 and now `0x7ff9`. 🙄

I suspect it's a bug in Windows. I've been hitting #1631 which also is a problem with `wevtapi`.

**Comment by tommcdon** [comment]
@sywhang is this ours?

**Comment by sywhang** [comment]
@tommcdon We don't own this part of the System.Diagnostics namespace. I think it's someone from @danmosemsft's team who owns this. I would be happy to help out investigating this if nobody owns it.

**Comment by danmosemsft** [comment]
Right, per https://github.com/dotnet/runtime/blob/master/docs/area-owners.md @anipik owns this. However, as it doesn't seem to be having widespread impact it might be a while before we can look at it. The ideal would be to boil it down to a pinvoke-only (or native) repro that (I assume) we could send to Windows.

**Comment by Gnbrkm41** [comment]
I could run the tests again to see if this issue is still there on latest insider builds.

**Comment by Gnbrkm41** [comment]
It does still fail (W10 Pro Insider Preview, Build 19624). If I have some time I can write some native code to demonstrate the issue.

**Comment by Gnbrkm41** [comment]
Native repro:
```cpp
#include <iostream>
#include <Windows.h>
#include <winevt.h>
#include <assert.h>

int main()
{
    DWORD err;
    EVT_HANDLE configHandle = EvtOpenChannelConfig(NULL, L"Application", 0);
    if (configHandle == NULL)
    {
        std::cout << "Failed to open channel config: " << std::hex << (err = GetLastError());
        return err;
    }

    EVT_VARIANT variant;

    // C#: eventLogConfiguration.IsEnabled = false;
    variant.Type = EvtVarTypeBoolean;
    variant.BooleanVal = false;
    if (!EvtSetChannelConfigProperty(configHandle, EvtChannelConfigEnabled, 0, &variant)) return GetLastError();

    if (EvtSaveChannelConfig(configHandle, 0))
    {
        std::cout << "EvtSaveChannelConfig did not fail (is the program elevated?)";
        return -1;
    }
    err = GetLastError();
    std::cout << "EvtSaveChannelConfig Failed (Expected), and GetLastError returned 0x"  << err;
}
```

**Comment by Anipik** [comment]
i can provide this repro to the windows team and can carry on the conversation

**Comment by Robo210** [comment]
Please install the latest cumulative update (July 2020 or later) and let us know if the issue persists.

**Comment by danmosemsft** [comment]
Thanks @Robo210 . @Gnbrkm41 can you confirm, and we can close thi?

**Comment by danmosemsft** [comment]
In fact, I'm going to optimistically close and do continue the conversation if it's not fixed.

**Comment by Gnbrkm41** [comment]
Can confirm this no longer fails on 20170. Thanks! ❤️

**Comment by Anipik** [comment]
Thanks @Robo210 for resolving this.
