### ISSUE TITLE
[x64] Test failed: System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#11917]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_minopts/835/

**Failed tests:**
System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal

**Log:**
```
      System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal(testData: [FormatDecimal [-0, scale=0],default to '0')]) [FAIL]
  [m[31;1m[m[37m      Assert.Equal() Failure
  [m[37m                ↓ (pos 0)
  [m[37m      Expected: 0
  [m[37m      Actual:   -0
  [m[37m                ↑ (pos 0)
  [m[30;1m      Stack Trace:
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_minopts/_/fx/src/System.Memory/tests/ParsersAndFormatters/Formatter/ValidateFormatter.cs(84,0): at System.Buffers.Text.Tests.FormatterTests.ValidateFormatterHelper[T](FormatterTestData`1 testData)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_minopts/_/fx/src/System.Memory/tests/ParsersAndFormatters/Formatter/ValidateFormatter.cs(22,0): at System.Buffers.Text.Tests.FormatterTests.ValidateFormatter[T](FormatterTestData`1 testData)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_minopts/_/fx/src/System.Memory/tests/ParsersAndFormatters/Formatter/FormatterTests.cs(79,0): at System.Buffers.Text.Tests.FormatterTests.TestFormatterDecimal(FormatterTestData`1 testData)
```

**Comment by jashook** [comment]
Stale
