### ISSUE TITLE
[arm64][Ubuntu][jitstress2] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#11995]
There are unstable failures of this test with:

```
m[31;1m System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds [FAIL]
00:40:05  [m  [37m   Assert.Equal() Failure
00:40:05   [m  [37m   Expected: OK
00:40:05   [m  [37m   Actual:   Unauthorized
00:40:05   [m  [30;1m   Stack Trace:
00:40:05   [m  [37m     /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_prtest/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Proxy.cs(277,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test.<>c__DisplayClass8_0.<<ProxyAuth_Digest_Succeeds>b__0>d.MoveNext()
00:40:05   [m  [37m     --- End of stack trace from previous location where exception was thrown ---
00:40:05   [m  [37m     /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_prtest/_/fx/src/Common/tests/System/Net/Http/LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
00:40:05   [m  [37m     /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_prtest/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Proxy.cs(256,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds()
00:40:05   [m  [37m     --- End of stack trace from previous location where exception was thrown ---
```

**Comment by sandreenko** [comment]
The exclusion list was deleted so now this issue is not mentioned anywhere, also many things have changed since the test was open so the issue is outdated and can be closed.
