### ISSUE TITLE
fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#1211]
Hit in https://github.com/dotnet/runtime/pull/1178, runtime-libraries (Libraries Build Linux x64 Debug) leg, RedHat.7.Amd64.Open test job, multiple tests: System.Security.Cryptography.OpenSsl.Tests and System.Net.Http.Functional.Tests.

**Comment by jkotas** [comment]
Failure log for `System.Security.Cryptography.OpenSsl.Tests`:
https://helix.dot.net/api/2019-06-17/jobs/6d34e4ec-a194-4a1f-a5d6-f9957266612d/workitems/System.Security.Cryptography.OpenSsl.Tests/console

```
  Discovering: System.Security.Cryptography.OpenSsl.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.OpenSsl.Tests (found 599 of 602 test cases)
  Starting:    System.Security.Cryptography.OpenSsl.Tests (parallel test collections = on, max threads = 2)
fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
./RunTests.sh: line 161:  2341 Aborted                 (core dumped)
```

**Comment by jkotas** [comment]
Failure log for `System.Net.Http.Functional.Tests` test failures
https://helix.dot.net/api/2019-06-17/jobs/6d34e4ec-a194-4a1f-a5d6-f9957266612d/workitems/System.Net.Http.Functional.Tests/console

``` 
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateOnlySentWhenValid_Success(certIndex: 1, serverExpectsClientCertificate: True) [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (The SSL connection could not be established, see inner exception.)) (One or more errors occurred. (Authentication failed, see inner exception.))
      ---- System.AggregateException : One or more errors occurred. (The SSL connection could not be established, see inner exception.)
      -------- System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
      ------------ System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---------------- Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
      -------------------- Interop+Crypto+OpenSslCryptographicException : error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error
      ---- System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.)
      -------- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ------------ Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
      ---------------- Interop+Crypto+OpenSslCryptographicException : error:1408807B:SSL routines:ssl3_get_cert_verify:bad signature
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs(103,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass6_0.<<Manual_CertificateOnlySentWhenValid_Success>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.ClientCertificates.cs(98,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateOnlySentWhenValid_Success(Int32 certIndex, Boolean serverExpectsClientCertificate)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(162,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(650,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(665,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(331,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(523,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(553,0): at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(156,0): at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(378,0): at System.Net.Security.SslStream.ForceAuthenticationAsync(Boolean receiveFirst, Byte[] buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(146,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(316,0): at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs(117,0): at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
        ----- Inner Stack Trace -----
        
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(378,0): at System.Net.Security.SslStream.ForceAuthenticationAsync(Boolean receiveFirst, Byte[] buffer, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(100,0): at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(125,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs(316,0): at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs(117,0): at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
        ----- Inner Stack Trace -----
        
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n ", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n ", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n\t", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n\t", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n    ", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n    ", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "\r\n ", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "\r\n ", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "\r\n\t", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "\r\n\t", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "\r\n    ", dribble: False) [SKIP]
      Folding is not supported on HTTP/2.
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\r\n", fold: "\r\n    ", dribble: True) [SKIP]
      Folding is not supported on HTTP/2.
fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
```

**Comment by wfurt** [comment]
This seems like external issue: https://bugzilla.redhat.com/show_bug.cgi?id=1752254
I don't know if this is actionable unless this was caused by infrastructure changes: 

cc: @bartonjs @tmds @safern

**Comment by bartonjs** [comment]
RedHat has closed out their bugs on this, and the issue shows little-to-no activity for a long time.  Calling it closed until proven otherwise.
