### ISSUE TITLE
[x86] Test Failure: Exit code was -1073740791 but it should have been 42

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#12145]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/755/

**Failed tests:**
System.Tests.EnvironmentTests.CurrentDirectory_SetToValidOtherDirectory
System.Tests.AppDomainTests.GetData_SetData
System.Net.Http.Tests.HttpSystemProxyTest.HttpProxy_InvalidSystemProxy_Null(rawProxyString: \" ; \")

**Log:**
```
System.Tests.EnvironmentTests.CurrentDirectory_SetToValidOtherDirectory [FAIL]
        Exit code was -1073740791 but it should have been 42
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\src\CoreFx.Private.TestUtilities\src\System\Diagnostics\RemoteExecutorTestBase.cs(383,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing)
          D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\src\System.Runtime.Extensions\tests\System\EnvironmentTests.cs(42,0): at System.Tests.EnvironmentTests.CurrentDirectory_SetToValidOtherDirectory()
```

**Comment by mangod9** [comment]
Old issue, closing out.
