### ISSUE TITLE
.NET Core 3.1 : Unable to load DLL

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#1215]
I built entire projects successfully from "https://github.com/dotnet/corefx/tree/release/3.1", I changed System.Data.Odbc to Informix.Net.Core appropriately. The newly built assembly, Informix.Net.Core.dll references iclit09b.dll (which has ODBC implementation for Informix), very simple program which tries to connect with Informix database receives "unable to load iclit09b.dll" (more details below) at runtime, iclit09b.dll is included in the PATH variable of the command prompt and also in the "Environment". Exact same program works without any issue in the same environment when I use .NET Core 2.2.

Did something change in .NET Core 3.1 in terms of loading "non .NET dependent DLL/so called legacy DLLs"?

D:\shesh\DOTNET-Core-Informix-code\VS2019_projects\MyApp>dotnet D:\shesh\DOTNET-Core-Informix-code\VS2019_projects\MyApp\bin\Debug\netcoreapp3.1\MyApp.dll

**Unhandled exception. System.DllNotFoundException: Unable to load DLL 'iclit09b.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)**

   at Interop.Odbc.SQLAllocHandle(SQL_HANDLE HandleType, IntPtr InputHandle, IntPtr& OutputHandle)
   at Informix.Net.Core.OdbcHandle..ctor(SQL_HANDLE handleType, OdbcHandle parentHandle) in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Informix\Net\Core\OdbcHandle.cs:line 37
   at Informix.Net.Core.OdbcEnvironmentHandle..ctor() in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Informix\Net\Core\OdbcEnvironmentHandle.cs:line 12
   at Informix.Net.Core.OdbcEnvironment.GetGlobalEnvironmentHandle() in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Informix\Net\Core\OdbcEnvironment.cs:line 26
   at Informix.Net.Core.IfxConnectionOpen..ctor(IfxConnection outerConnection, IfxConnectionString connectionOptions) in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Informix\Net\Core\OdbcConnectionOpen.cs:line 17
   at Informix.Net.Core.IfxConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject) in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Informix\Net\Core\OdbcConnectionFactory.cs:line 32
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in D:\shesh\corefx-release-3.1\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 374
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions) in D:\shesh\corefx-release-3.1\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 96
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Common\System\Data\ProviderBase\DbConnectionFactory.cs:line 130
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in D:\shesh\corefx-release-3.1\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 325
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in D:\shesh\corefx-release-3.1\src\Common\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 37
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory) in D:\shesh\corefx-release-3.1\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 295
   at Informix.Net.Core.IfxConnection.Open() in D:\shesh\corefx-release-3.1\src\Informix.Net.Core\src\Informix\Net\Core\OdbcConnection.cs:line 1739
   at FirstODBCSamp.Class1.Main(String[] args) in D:\shesh\DOTNET-Core-Informix-code\VS2019_projects\MyApp\Program1.cs:line 28

D:\shesh\DOTNET-Core-Informix-code\VS2019_projects\MyApp>

**Comment by deokershesh** [comment]
I tried to change following in versioning.targets, removed "artifacts" folder and rebuilt, but still it didn't help!!, basically added, System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior

Any clue/help will be highly appreciated.

From:
-----
     <AssemblyInfoLines Condition="'$(IncludeDllSafeSearchPathAttribute)'=='true'"
        Include="[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute(System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory | System.Runtime.InteropServices.DllImportSearchPath.System32)]" />
    </ItemGroup>

To:
----
     <AssemblyInfoLines Condition="'$(IncludeDllSafeSearchPathAttribute)'=='true'"
        Include="[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute(System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory | System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior | System.Runtime.InteropServices.DllImportSearchPath.System32)]" />
    </ItemGroup>

**Comment by jkotas** [comment]
> added System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior

`DllImportSearchPath.LegacyBehavior` value is 0, so ORing it in won't have any affect. `DllImportSearchPath.LegacyBehavior` is meant to be used without any other values.

> Did something change in .NET Core 3.1 in terms of loading "non .NET dependent DLL/so called legacy DLLs"?

Nothing that I am aware of changed in the runtime itself.

The best way to troubleshoot unmanaged library load failures like this on Windows are [loader snaps](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/show-loader-snaps). https://blogs.msdn.microsoft.com/junfeng/2006/11/20/debugging-loadlibrary-failures/ has a step-by-step example for how to do this.

**Comment by deokershesh** [comment]
@jkotas, I also tried following in versioning.targets, which works in .NET Core 2.2 but it reports below error in .NET Core 3.1, that's the reason I tried "|" (OR) style syntax!

versioning.target
------------------
      <AssemblyInfoLines Condition="'$(IncludeDllSafeSearchPathAttribute)'=='true'"
        Include="[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute( System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior )]" />
    
      <AssemblyInfoLines Condition="'$(IncludeDllSafeSearchPathAttribute)'=='true'"
        Include="[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute(System.Runtime.InteropServices.DllImportSearchPath.AssemblyDirectory | System.Runtime.InteropServices.DllImportSearchPath.System32)]" />
    </ItemGroup>


Error:
-----
D:\shesh\corefx-release-3.1\artifacts\obj\ref\System.Numerics.Tensors\netstandard-Debug\_AssemblyInfo.cs(5,12): error CS0579: **Duplicate 'System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute'** attribute [D:\shesh\corefx-release-3.1\src\System.Numerics.Tensors\ref\System.Numerics.Tensors.csproj]

**Comment by jkotas** [comment]
So set `IncludeDllSafeSearchPathAttribute` to false in your project, and then you can include DefaultDllImportSearchPathsAttribute in any shape you would like.

**Comment by deokershesh** [comment]
@jkotas, Could you please explain little more on, what you meant by "set to false"? If I set it to "false", how will it get into above(previous post) "IF" condition and get the "System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior" set?

**Comment by jkotas** [comment]
I mean that you can add this:

```
<PropertyGroup>
    <IncludeDllSafeSearchPathAttribute>false</IncludeDllSafeSearchPathAttribute>
</PropertyGroup>
```

to your .csproj file. Then you can add a local .cs with any DllImportSearchPath attribute you like to your project. 

The CoreFX assemblies use DllImportSearchPath to restrict places where DllImport looks for unmanaged binaries. This is done for security defense in depth.

From what you are describing, these restrictions break your project. The obvious fix is to relax these restrictions. You will lose the security defense in depth, but you will get something that actually works.

**Comment by deokershesh** [comment]
Thanks jkotas, I tried following and this works!! Do you see anything wrong with below? Well, I commented few params for now! and only enabled "LegacyBehavior".

      <AssemblyInfoLines Condition="'$(IncludeDllSafeSearchPathAttribute)'=='true'"
        Include="[assembly: System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute(System.Runtime.InteropServices.DllImportSearchPath.LegacyBehavior)]" />
      
    </ItemGroup>

**Comment by jkotas** [comment]
As I have said, you are losing the security defense in depth. If you would like to better, you may want to figure out which specific bits in DefaultDllImportSearchPathsAttribute you need.

**Comment by jeffschwMSFT** [comment]
Closing this issue as it looks like it was resolved.  Let me know otherwise.
