### ISSUE TITLE
[arm] Test failed: ConfigurationErrorsException in arm_cross_checked_windows_nt_corefx

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#12478]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_minopts_tst/56/

**Failed tests:**
MonoTests.System.Configuration.ConfigurationManagerTest.exePath_UserLevelPerRoamingAndLocal

**Log:**
```
MonoTests.System.Configuration.ConfigurationManagerTest.exePath_UserLevelPerRoamingAndLocal [FAIL]
      System.Configuration.ConfigurationErrorsException : An error occurred loading a configuration file: The process cannot access the file 'C:\Users\HelixAdmin\AppData\Local\Microsoft_Corporation\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\2.5.1.0\user.config' because it is being used by another process. (C:\Users\HelixAdmin\AppData\Local\Microsoft_Corporation\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\2.5.1.0\user.config)
      ---- System.IO.IOException : The process cannot access the file 'C:\Users\HelixAdmin\AppData\Local\Microsoft_Corporation\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\2.5.1.0\user.config' because it is being used by another process.
      Stack Trace:
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationSchemaErrors.cs(72,0): at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs(3655,0): at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs(253,0): at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\Configuration.cs(76,0): at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigurationHost.cs(487,0): at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationManager.cs(221,0): at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationManager.cs(188,0): at System.Configuration.ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel userLevel)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\tests\Mono\ConfigurationManagerTest.cs(164,0): at MonoTests.System.Configuration.ConfigurationManagerTest.exePath_UserLevelPerRoamingAndLocal()
        ----- Inner Stack Trace -----
           at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
           at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\Internal\InternalConfigHost.cs(228,0): at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForRead(String streamName)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\Internal\InternalConfigHost.cs(60,0): at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForRead(String streamName)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigurationHost.cs(282,0): at System.Configuration.ClientConfigurationHost.OpenStreamForRead(String streamName)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\UpdateConfigHost.cs(80,0): at System.Configuration.UpdateConfigHost.OpenStreamForRead(String streamName)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\Internal\DelegatingConfigHost.cs(86,0): at System.Configuration.Internal.DelegatingConfigHost.OpenStreamForRead(String streamName)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\ImplicitMachineConfigHost.cs(64,0): at System.Configuration.ImplicitMachineConfigHost.OpenStreamForRead(String streamName)
        D:\j\workspace\arm_cross_che---bb9c275d\_\fx\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs(552,0): at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
```

**Comment by jashook** [comment]
This has not reproed in 1+ year, closing
