### ISSUE TITLE
CoreFX test failure: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#12564]
Looks like a timeout

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/840/consoleFull

```
22:45:50      System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent [FAIL]
22:45:50         System.TimeoutException : Task timed out after 00:00:30
22:45:50         Stack Trace:
22:45:50              at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
22:45:50           D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cookies.cs(153,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent()
22:45:50           --- End of stack trace from previous location where exception was thrown ---
```

**Comment by BruceForstall** [comment]
This is obsolete
