### ISSUE TITLE
[arm64] Test failed: System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricRSASignature

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#12610]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress2_tst/34/

**Failed tests:**
System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricRSASignature

**Log:**
```
System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricRSASignature [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        D:\j\workspace\arm64_cross_c---3be10518\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(1116,0): at System.Security.Cryptography.Xml.SignedXml.IsKeyTheCorrectAlgorithm(AsymmetricAlgorithm key, Type expectedType)
        D:\j\workspace\arm64_cross_c---3be10518\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(1020,0): at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
        D:\j\workspace\arm64_cross_c---3be10518\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(304,0): at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
        D:\j\workspace\arm64_cross_c---3be10518\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(272,0): at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
        D:\j\workspace\arm64_cross_c---3be10518\_\fx\src\System.Security.Cryptography.Xml\tests\SignedXmlTest.cs(208,0): at System.Security.Cryptography.Xml.Tests.SignedXmlTest.AsymmetricRSASignature()
```

**Comment by bartonjs** [comment]
This failure hasn't occurred within 90 days, closing.
