### ISSUE TITLE
Potential error in the csproj of System.Xml.RW.XmlReader.ReadContentAs.Tests

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#1267]
https://github.com/dotnet/runtime/blob/3b9abae5aae537258611b5750dc7e2963cfc73ed/src/libraries/System.Private.Xml/tests/XmlReader/ReadContentAs/System.Xml.RW.XmlReader.ReadContentAs.Tests.csproj#L3

This was causing those errors in VS:
```cs
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "FindBestConfigurations" task failed unexpectedly.
System.ArgumentException: No value was provided for property 'TargetGroup' and no default value exists
   at Microsoft.DotNet.Build.Tasks.Configuration.ConfigurationFactory.ParseConfiguration(String configurationString, Boolean permitUnknownValues, Configuration baseConfiguration) in /_/src/Microsoft.DotNet.Build.Tasks.Configuration/src/Configuration/ConfigurationFactory.cs:line 211
   at Microsoft.DotNet.Build.Tasks.Configuration.FindBestConfigurations.Execute() in /_/src/Microsoft.DotNet.Build.Tasks.Configuration/src/FindBestConfigurations.cs:line 38
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	System.Xml.RW.XmlReader.ReadContentAs.Tests	C:\Users\gotos\.nuget\packages\microsoft.dotnet.build.tasks.configuration\5.0.0-beta.19617.1\build\Microsoft.DotNet.Build.Tasks.Configuration.targets	194	
Error	NETSDK1013	The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	System.Xml.RW.XmlReader.ReadContentAs.Tests	C:\Users\gotos\source\repos\runtime\.dotnet\sdk\5.0.100-alpha1-015772\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	93	
```

also it was constantly trying to edit the .sln file:
```diff
diff --git a/src/libraries/System.Private.Xml/System.Private.Xml.sln b/src/libraries/System.Private.Xml/System.Private.Xml.sln
index cdfd60e8f4d..a6498d976a5 100644
--- a/src/libraries/System.Private.Xml/System.Private.Xml.sln
+++ b/src/libraries/System.Private.Xml/System.Private.Xml.sln
@@ -1,6 +1,6 @@
 Microsoft Visual Studio Solution File, Format Version 12.00
-# Visual Studio 15
-VisualStudioVersion = 15.0.27213.1
+# Visual Studio Version 16
+VisualStudioVersion = 16.0.29521.150
 MinimumVisualStudioVersion = 10.0.40219.1
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "System.Xml.Misc.Tests", "tests\Misc\System.Xml.Misc.Tests.csproj", "{A30BBA60-647C-4565-A42F-BE60B2CA2E8E}"
        ProjectSection(ProjectDependencies) = postProject
@@ -206,10 +206,10 @@ Global
                {6C6F323D-054E-4723-9DEA-1C5E1E45DF88}.Debug|Any CPU.Build.0 = netcoreapp5.0-Debug|Any CPU
                {6C6F323D-054E-4723-9DEA-1C5E1E45DF88}.Release|Any CPU.ActiveCfg = netcoreapp5.0-Release|Any CPU
                {6C6F323D-054E-4723-9DEA-1C5E1E45DF88}.Release|Any CPU.Build.0 = netcoreapp5.0-Release|Any CPU
-               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Debug|Any CPU.ActiveCfg = netcoreapp5.0-Debug|Any CPU
-               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Debug|Any CPU.Build.0 = netcoreapp5.0-Debug|Any CPU
-               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Release|Any CPU.ActiveCfg = netcoreapp5.0-Release|Any CPU
-               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Release|Any CPU.Build.0 = netcoreapp5.0-Release|Any CPU
+               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Debug|Any CPU.ActiveCfg = -Debug|Any CPU
+               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Debug|Any CPU.Build.0 = -Debug|Any CPU
+               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Release|Any CPU.ActiveCfg = -Release|Any CPU
+               {DA6A9B7F-F311-49A4-8BBE-42EF3152C37B}.Release|Any CPU.Build.0 = -Release|Any CPU
                {507DB29F-74F5-4B34-A240-ABE7BD168DF6}.Debug|Any CPU.ActiveCfg = netcoreapp5.0-Debug|Any CPU
                {507DB29F-74F5-4B34-A240-ABE7BD168DF6}.Debug|Any CPU.Build.0 = netcoreapp5.0-Debug|Any CPU
                {507DB29F-74F5-4B34-A240-ABE7BD168DF6}.Release|Any CPU.ActiveCfg = netcoreapp5.0-Release|Any CPU

```

It appears that `TargetFrameworkVNext` isn't really defined (nor used anywhere)? all the other projects seem use `NetCoreAppCurrent` instead.

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/runtime/commit/3b9abae5aae537258611b5750dc7e2963cfc73ed
> TargetFrameworkVNext -> netcoreappCurrent

So probably was meant to be changed, but missed out for some reason 🙂
