### ISSUE TITLE
Assertion failure "Header buffer is not allocated." in System.Net.Security.SslStream.DetectFraming in Fedora

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#1291]
netcoreapp5.0-Linux-Debug-x64-(Fedora.29.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-
```
      Condition(s) not met: "IsRootCertificateInstalled"
Process terminated. Assertion failed.
Header buffer is not allocated.
SslStream#65520770.DetectFraming
   at System.Net.NetEventSource.Fail(Object thisOrContextObject, Object message, String memberName) in /_/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs:line 287
   at System.Net.Security.SslStream.DetectFraming(Byte[] bytes, Int32 length) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1234
   at System.Net.Security.SslStream.ReceiveBlobAsync(SslReadAsync adapter, Byte[] buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 509
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 329
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 785
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3242
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 399
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncValueTaskMethodBuilderT.cs:line 66
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|207_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1048
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 329
   at System.Threading.ThreadPoolGlobals.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs:line 42
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1052
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 872
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 776
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 407
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 122
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 490
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 888
   at System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation op) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1295
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 332
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs:line 673
./RunTests.sh: line 161:    57 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Net.Security.Tests.runtimeconfig.json --depsfile System.Net.Security.Tests.deps.json xunit.console.dll System.Net.Security.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests $RSP_FILE
/root/helix/work/workitem
----- end Fri Jan 3 23:25:34 UTC 2020 ----- exit code 134 ----------------------------------------------------------
```

https://dev.azure.com/dnceng/public/_build/results?buildId=471549&view=logs&j=1136f1e1-214d-5201-e246-afde0074522e&t=c7dce115-ca80-5f46-8523-cdb0118adc23&l=77
https://helix.dot.net/api/2019-06-17/jobs/43660ba8-1e76-4148-9d5c-65a9c5c0fd51/workitems/System.Net.Security.Tests/console

@mjanecke do we expect a dumpfile in this case?

**Comment by mjanecke** [comment]
@danmosemsft based off the exit code, I would expect a dump file to exist for this job, but I'm not seeing anything in the test results when I filter on "Failure Report". I'll open up an issue in FR to investigate why the dump file isn't appearing for this run.

**Comment by danmosemsft** [comment]
@wfurt (or whoever wishes to look) there was in fact a dump file, I just looked in the wrong "Attachments":

![image](https://user-images.githubusercontent.com/6385855/71859971-c1f4bb80-30a5-11ea-9c22-b3353f20f284.png)

HTH

**Comment by wfurt** [comment]
I will look at it.

**Comment by wfurt** [comment]
```
(lldb) dumpobj 0x00007f0095dab558
Name:        System.Net.Security.SslStream
MethodTable: 00007f00bc8e6428
EEClass:     00007f00bc8f0840
Size:        224(0xe0) bytes
File:        /root/helix/work/correlation/shared/Microsoft.NETCore.App/5.0.0/System.Net.Security.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007f00bc8c1718  4001371        8 ...eam+ReadWriteTask  0 instance 0000000000000000 _activeReadWriteTask
00007f00bc014590  4001372       10 ...ing.SemaphoreSlim  0 instance 0000000000000000 _asyncActiveSemaphore
00007f00bbff8f18  4001370     1168     System.IO.Stream  0   static 00007f0094082710 Null
00007f00bbff8f18  4000214       18     System.IO.Stream  0 instance 00007f0095dab4c8 _innerStream
00007f00bbf160d0  4000215       20       System.Boolean  1 instance                0 _leaveStreamOpen
00007f00bc8eefb8  4000184       28 ....X509Certificate2  0 instance 0000000000000000 _remoteCertificate
00007f00bbf160d0  4000185       21       System.Boolean  1 instance                0 _remoteCertificateExposed
00007f00bc90dbe0  4000186       30 ...alidationCallback  0 instance 00007f0095dab518 _userCertificateValidationCallback
00007f00bc90f0e8  4000187       38 ...SelectionCallback  0 instance 0000000000000000 _userCertificateSelectionCallback
00007f00bca268a8  4000188       40 ...SelectionCallback  0 instance 0000000000000000 _userServerCertificateSelectionCallback
00007f00bc90f280  4000189       48 ...alidationCallback  0 instance 00007f0095dab638 _certValidationDelegate
00007f00bc90f418  400018a       50 ...SelectionCallback  0 instance 0000000000000000 _certSelectionDelegate
00007f00bc5c3cb8  400018b       24         System.Int32  1 instance                0 _encryptionPolicy
00007f00bbff8f18  400018c       58     System.IO.Stream  0 instance 00007f0095dab4c8 _innerStream
00007f00bca2d330  400018d       60 ...ity.SecureChannel  0 instance 00007f0095dab9c0 _context
00007f00bc7d99c8  400018e       68 ...ptionDispatchInfo  0 instance 00007f0094151368 _exception
00007f00bbf160d0  400018f       22       System.Boolean  1 instance                0 _shutdown
00007f00bbf160d0  4000190       23       System.Boolean  1 instance                0 _handshakeCompleted
00007f00bbf74948  4000191       70        System.Byte[]  0 instance 0000000000000000 _internalBuffer
00007f00bbf1a0f0  4000192       98         System.Int32  1 instance                0 _internalOffset
00007f00bbf1a0f0  4000193       9c         System.Int32  1 instance                7 _internalBufferCount
00007f00bbf1a0f0  4000194       a0         System.Int32  1 instance                0 _decryptedBytesOffset
00007f00bbf1a0f0  4000195       a4         System.Int32  1 instance                0 _decryptedBytesCount
00007f00bbf1a0f0  4000196       a8         System.Int32  1 instance                0 _nestedWrite
00007f00bbf1a0f0  4000197       ac         System.Int32  1 instance                1 _nestedRead
00007f00bca26788  4000199       78 ...enticationOptions  0 instance 00007f0095dab900 _sslAuthenticationOptions
00007f00bbf1a0f0  400019a       b0         System.Int32  1 instance                0 _nestedAuth
00007f00bc8e60c8  400019b       c8 ...SecurityStatusPal  1 instance 00007f0095dab620 _securityStatus
00007f00bc8e6150  400019c       c4          System.Byte  1 instance                0 _CachedSession
00007f00bc8e62a0  400019d       b4         System.Int32  1 instance                0 _framing
00007f00bbf74948  400019e       80        System.Byte[]  0 instance 0000000000000000 _queuedReadData
00007f00bbf1a0f0  400019f       b8         System.Int32  1 instance                0 _queuedReadCount
00007f00bbf1a0f0  40001a0       bc         System.Int32  1 instance                0 _lockWriteState
00007f00bbd8ca50  40001a1       88        System.Object  0 instance 0000000000000000 _queuedWriteStateRequest
00007f00bbf1a0f0  40001a2       c0         System.Int32  1 instance                0 _lockReadState
00007f00bbd8ca50  40001a3       90        System.Object  0 instance 0000000000000000 _queuedReadStateRequest
00007f00bc7d99c8  4000183       d0 ...ptionDispatchInfo  0   static 00007f0094151368 s_disposedSentinel
00007f00bbf1a0f0  4000198       dc         System.Int32  1   static              123 s_uniqueNameInteger
```

_exception has value of s_disposedSentinel and _internalBuffer is null. It seems like stream was closed/disposed during read. I think I know what to do.

**Comment by danmosemsft** [comment]
Yay for dump files from tests!

**Comment by wfurt** [comment]
there are some hoops to jump through. @mikem8361 updated sos FAQ so finding correct bits is probably biggest hassle at the moment.

**Comment by stephentoub** [comment]
Failed again here:
https://github.com/dotnet/runtime/pull/1973/checks?check_run_id=403682834

**Comment by wfurt** [comment]
It should be fixed by the linked PR.

**Comment by jkotas** [comment]
Failed again in #2151
