### ISSUE TITLE
Test failed: Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#13040]
**Job:**
https://mc.dot.net/#/user/coreclr-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2F/20190707.1/workItem/Interop/analysis/xunit/Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_~2F_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

**Failed tests:**
Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

**Log:**
```
Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\c5b8c1d5-cf58-411c-8a90-0c0b458e15c6\\Work\\6299d9a7-4f5b-4278-8a59-3562fbfc5d8c\\Exec\\Interop\\COM\\Reports\\Interop.COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\c5b8c1d5-cf58-411c-8a90-0c0b458e15c6\\Payload\\corerun.exe\" NETClientPrimitives.exe 
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Marshal strings as BStr
Marshal LCID
Verify expected exception from HRESULT
Verify preserved function signature
Testing COM object lifetime control methods.
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Marshal strings as BStr
Marshal LCID
Verify expected exception from HRESULT
Verify preserved function signature
Test Failure: TestLibrary.AssertTestException: Assert.IsFalse: 
   at TestLibrary.Assert.HandleFail(String assertionName, String message) in F:\\workspace.3\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Assertion.cs:line 735
   at TestLibrary.Assert.IsFalse(Boolean condition, String message) in F:\\workspace.3\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Assertion.cs:line 322
   at NetClient.Program.Main(String[] doNotUse) in F:\\workspace.3\\_work\\1\\s\\tests\\src\\Interop\\COM\\NETClients\\Primitives\\Program.cs:line 29
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\c5b8c1d5-cf58-411c-8a90-0c0b458e15c6\\Payload
> C:\\dotnetbuild\\work\\c5b8c1d5-cf58-411c-8a90-0c0b458e15c6\\Work\\6299d9a7-4f5b-4278-8a59-3562fbfc5d8c\\Exec\\Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
Expected: True
Actual:   False
```

**Comment by AaronRobinsonMSFT** [comment]
Closing based on last comment.
