### ISSUE TITLE
Block signals when using libunwind

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#13142]
Hi!

Here is the problem I was talking about a week ago: RaiseException() uses your bundled libunwind, which has mutex to protect struct dwarf_rs_cache in find_reg_state(). AFAIK libunwind has reentrancy protection, but it's under CONFIG_BLOCK_SIGNALS flag, which is turn off in coreclr. Thus, without this flag, I get the following deadlock:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
__lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135     ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
dotnet/coreclr#1  0x00007f4c98537023 in __GI___pthread_mutex_lock (mutex=0x7f4c97298378 <local_addr_space+88>)
    at ../nptl/pthread_mutex_lock.c:78
dotnet/coreclr#2  0x00007f4c96f7a938 in _ULx86_64_dwarf_step ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#3  0x00007f4c96f74cb1 in _ULx86_64_step ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#4  0x00007f4c96f37613 in PAL_VirtualUnwind ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#5  0x00007f4c96ce5c3b in LazyMachState::unwindLazyState(LazyMachState*, MachState*, unsigned int, int, HostCallPreference) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#6  0x00007f4c96b71556 in HelperMethodFrame::InsureInit(bool, MachState*, HostCallPreference) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#7  0x00007f4c96b714b2 in HelperMethodFrame::GetFunction() ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#8  0x00007f4c96bc7b16 in StackFrameIterator::ProcessCurrentFrame() ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#9  0x00007f4c96bc8fa4 in StackFrameIterator::NextRaw() ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#10 0x00007f4c96bc8688 in StackFrameIterator::Filter() ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#11 0x00007f4c96bc742b in StackFrameIterator::Init(Thread*, Frame*, REGDISPLAY*, unsigned int) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#12 0x00007f4c96bc716f in Thread::StackWalkFramesEx(REGDISPLAY*, StackWalkAction (*)(CrawlFrame*, void*), void*, unsigned int, Frame*) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#13 0x00007f4c96bc759c in Thread::StackWalkFrames(StackWalkAction (*)(CrawlFrame*, void*), void*, unsigned int, Frame*) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#14 0x00007f4c96c7d93e in ProfToEEInterfaceImpl::DoStackSnapshotHelper(Thread*, _PROFILER_STACK_WALK_DATA*, unsigned int, _CONTEXT*) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#15 0x00007f4c96c7d809 in ProfToEEInterfaceImpl::DoStackSnapshot(unsigned long, int (*)(unsigned long, unsigned long, unsigned long, unsigned int, unsigned char*, void*), unsigned int, void*, unsigned char*, unsigned int) ()
   from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
...
dotnet/runtime#3859 0x00007f4c8ea27516 in do_sample (signum=27, info=0x7fff7b46d3b0, ucontext=0x7fff7b46d280)
    at ???:???
dotnet/coreclr#27 <signal handler called>
dotnet/runtime#3860 __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
dotnet/runtime#3861 0x00007f4c98537098 in __GI___pthread_mutex_lock (mutex=0x7f4c98b78990 <_rtld_global+2352>) at ../nptl/pthread_mutex_lock.c:113
dotnet/runtime#3862 0x00007f4c97962deb in __GI___dl_iterate_phdr (callback=0x7f4c96f7c790 <_ULx86_64_dwarf_callback>, data=0x7fff7b46d978) at dl-iteratephdr.c:40
dotnet/runtime#3863 0x00007f4c96f7cdce in _ULx86_64_dwarf_find_proc_info () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#32 0x00007f4c96f7ab02 in _ULx86_64_dwarf_step () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/runtime#3864 0x00007f4c96f74cb1 in _ULx86_64_step () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so dotnet/runtime#3865 0x00007f4c96f37613 in PAL_VirtualUnwind () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#35 0x00007f4c96f37a38 in RaiseException () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so dotnet/coreclr#36 0x00007f4c96b62d93 in RaiseTheExceptionInternalOnly(Object*, int, int) () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/runtime#3866 0x00007f4c96c5a0e0 in IL_Throw(Object*) () from /home/user/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.1.11/runtimes/linux-x64/native/libcoreclr.so
dotnet/coreclr#38 0x00007f4c1db1516a in ?? ()
dotnet/runtime#3867 0x00007fff7b46e770 in ?? ()
dotnet/runtime#3868 0x000000630000029a in ?? ()
dotnet/coreclr#41 0x0000000000000000 in ?? ()
```

cc @davmason @janvorli

**Comment by janvorli** [comment]
Invoking any code in the runtime or any non-async safe function from an async signal handler without knowing that the interrupted code was running in a safe place should never be done as it can lead to deadlocks or crashes. Basically, unless the interrupted thread was running in managed code or in one of the few GC barrier helpers, calling into anything in the runtime is dangerous.
So making libunwind reentrant would not help to fix the problem in general.
