### ISSUE TITLE
Test Failed: System.Collections.Immutable.Tests failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#13258]
**Job:**
https://helix.dot.net/api/2019-06-17/jobs/70d33134-0f7a-4948-9911-ed455503951c/workitems/System.Collections.Immutable.Tests/console

**Failed tests:**
System.Collections.Immutable.Tests.ImmutableListBuilderTest.BinarySearch
System.Collections.Immutable.Tests.ImmutableListTest.BinarySearchPartialSortedList
System.Collections.Immutable.Tests.ImmutableListTest.BinarySearch

**Log:**
```
System.Collections.Immutable.Tests.ImmutableListBuilderTest.BinarySearch [FAIL]
      Assert.Equal() Failure
      Expected: -403996873
      Actual:   -26
      Stack Trace:
        /_/src/System.Collections.Immutable/tests/ImmutableListTestBase.cs(411,0): at System.Collections.Immutable.Tests.ImmutableListTestBase.BinarySearch()
    System.Collections.Immutable.Tests.ImmutableListTest.BinarySearchPartialSortedList [FAIL]
      Assert.Equal() Failure
      Expected: -413545449
      Actual:   -1
      Stack Trace:
        /_/src/System.Collections.Immutable/tests/ImmutableListTestBase.cs(445,0): at System.Collections.Immutable.Tests.ImmutableListTestBase.BinarySearchPartialSortedListHelper(ImmutableArray`1 inputData, Int32 sortedIndex, Int32 sortedLength)
        /_/src/System.Collections.Immutable/tests/ImmutableListTestBase.cs(427,0): at System.Collections.Immutable.Tests.ImmutableListTestBase.BinarySearchPartialSortedList()
    System.Collections.Immutable.Tests.ImmutableListTest.BinarySearch [FAIL]
      Assert.Equal() Failure
      Expected: -414151913
      Actual:   -1
      Stack Trace:
        /_/src/System.Collections.Immutable/tests/ImmutableListTestBase.cs(409,0): at System.Collections.Immutable.Tests.ImmutableListTestBase.BinarySearch()
  Finished:    System.Collections.Immutable.Tests
```

**Comment by danmosemsft** [comment]
There have been zero failures of these tests in official builds since the new repo was created. The tests are not disabled. I guess it was fixed by fix to issue linked above.

https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAEXOQQrCMBCF4X2hdxiy0k2DB%2bhKEHSpXiBNRjqaZCQzQSoe3rYuXP88vnfiQdrmA68RC8KFa%2fEIfQ%2fGk33WIZK3gTWj2lKzUkJb8CZ2RBfEJieKxSz7O1OGB%2bXQU85Y4IqiZ5QaVYAznHg4hr%2fzK6tzcBTNv1ynJ%2b5A1BWVF%2bkI5jLNSOr2HCN6Jc7SHVOq6oaI3cLIOpeakiv0RvA8P91s26ZtvulMKMneAAAA&web=0
```
Jobs
| where Source == "ci/public/dotnet/runtime/refs/heads/master"
| join kind=inner TestResults on JobId
| where Result == "Fail"
| where Type1 startswith "System.Collections.Immutable.Tests"
| summarize count()
```

  |  
-- | --
  | count_
  | 0
