### ISSUE TITLE
Unable to load shared library 'System.Security.Cryptography.Native.OpenSsl' or one of its dependencies

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#1329]
Many tests in https://github.com/dotnet/runtime/pull/1324 failed on OSX Debug with:

```    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - DVPT128.rsp - 60 (128/56/192/32/0)) [FAIL]
      System.TypeInitializationException : The type initializer for 'Crypto' threw an exception.
      ---- System.TypeInitializationException : The type initializer for 'CryptoInitializer' threw an exception.
      -------- System.DllNotFoundException : Unable to load shared library 'System.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSystem.Security.Cryptography.Native.OpenSsl, 1): image not found
      Stack Trace:
           at Interop.Crypto.EvpAes128Ccm()
        /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/AesCcm.Unix.cs(122,0): at System.Security.Cryptography.AesCcm.GetCipher(Int32 keySizeInBits)
        /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/AesCcm.Unix.cs(28,0): at System.Security.Cryptography.AesCcm.EncryptInternal(ReadOnlySpan`1 nonce, ReadOnlySpan`1 plaintext, Span`1 ciphertext, Span`1 tag, ReadOnlySpan`1 associatedData)
        /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/AesCcm.cs(43,0): at System.Security.Cryptography.AesCcm.Encrypt(ReadOnlySpan`1 nonce, ReadOnlySpan`1 plaintext, Span`1 ciphertext, Span`1 tag, ReadOnlySpan`1 associatedData)
        /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/AesCcm.cs(32,0): at System.Security.Cryptography.AesCcm.Encrypt(Byte[] nonce, Byte[] plaintext, Byte[] ciphertext, Byte[] tag, Byte[] associatedData)
        /_/src/libraries/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(371,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Initialization.cs(40,0): at Interop.CryptoInitializer.Initialize()
        /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Initialization.cs(19,0): at Interop.Crypto..cctor()
        ----- Inner Stack Trace -----
           at Interop.CryptoInitializer.EnsureOpenSslInitialized()
        /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Initialization.cs(27,0): at Interop.CryptoInitializer..cctor()
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - DVPT192.rsp - 60 (192/56/192/32/0)) [FAIL]
```

**Comment by jkotas** [comment]
The log for "Install Build Dependencies" step says that the opensll was already installed and up-to-date:

```
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/runners/2.163.1/work/_temp/f731bd89-2535-4396-99d7-caf6815c9466.sh
Warning: openssl@1.1 1.1.1d is already installed and up-to-date
To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.mojave.bottle.1.tar.gz
```

**Comment by wfurt** [comment]
seems like dup of #1129. I think we still build against 1.0 but it is no longer available for fresh install.

**Comment by danmosemsft** [comment]
dupe
