### ISSUE TITLE
Test failed:System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#13407]
**Job:**
coreclr-corefx-jitstress [20190910.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=349115)

**Details:**
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-coreclr-refs-heads-master-7685d1b2c5eb49f495/System.Drawing.Common.Tests/console.283dda31.log?sv=2018-03-28&sr=c&sig=GMP6BggHmL4BfoaxTTlab%2BoKEF4kw3MjUQbpwKj2uyc%3D&se=2019-09-21T07%3A34%3A20Z&sp=rl

**OS & Arch:**
Windows x86

**Mode:**
set COMPlus_TieredCompilation=0
set COMPlus_TailcallStress=1

**Log:**
```
System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111776
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(788,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111776
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(788,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111776
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(788,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111776
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(788,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111776
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(788,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111776
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(788,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold | Italic | Strikeout, gdiCharSet: 255, gdiVerticalFont: True, expectedNamePrefix: "@", expectedWeight: 700) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111692
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(751,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111692
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(751,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   182111692
      Stack Trace:
        /_/src/System.Drawing.Common/tests/FontTests.cs(751,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
  Finished:    System.Drawing.Common.Tests
=== TEST EXECUTION SUMMARY ===
   System.Drawing.Common.Tests  Total: 4636, Errors: 0, Failed: 9, Skipped: 2, Time: 82.164s
----- end Wed 09/11/2019  8:02:35.87 ----- exit code 1 ----------------------------------------------------------
```

category:testing
theme:tail-call
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment]
Doesn't repro currently. Hopefully we get libraries JIT stress tests in AzDO soon.
