### ISSUE TITLE
System.Net.HttpListener.Tests failure in CoreFX

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#13479]
**Job:**
[coreclr-corefx-jitstress2-jitstressregs: #20190924.1](https://dnceng.visualstudio.com/public/_build/results?buildId=364155)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/5e5765f9-a036-4e33-8a3d-43ba8278921f/workitems/System.Net.HttpListener.Tests/console

**OS & Arch:**
Windows x86

**Mode:**
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=1

**Note:**
This failure **repro** on our windows x86 machine.

**Log:**
```
C:\dotnetbuild\work\5e5765f9-a036-4e33-8a3d-43ba8278921f\Work\1dba70ff-0179-46b0-9d11-2f5426d8de38\Exec>"C:\dotnetbuild\work\5e5765f9-a036-4e33-8a3d-43ba8278921f\Payload\dotnet.exe" exec --runtimeconfig System.Net.HttpListener.Tests.runtimeconfig.json xunit.console.dll System.Net.HttpListener.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\5e5765f9-a036-4e33-8a3d-43ba8278921f\Payload\CoreFX.issues.rsp 
  Discovering: System.Net.HttpListener.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.HttpListener.Tests (found 217 of 298 test cases)
  Starting:    System.Net.HttpListener.Tests (parallel test collections = on, max threads = 2)
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   10485760
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(332,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(224,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutAfterStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(213,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutNoStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(273,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutNoStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(283,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutAfterStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(189,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutNoStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   10485760
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(298,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(234,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutNoStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   10485760
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(308,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(241,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutAfterStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(262,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutAfterStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerUnixTests.DrainEntityBody_Roundtrips [SKIP]
      Condition(s) not met: "IsManagedImplementation"
    System.Net.Tests.HttpListenerTimeoutManagerUnixTests.UnsupportedProperties_Throw [SKIP]
      Condition(s) not met: "IsManagedImplementation"
    System.Net.Tests.HttpListenerTimeoutManagerUnixTests.IdleConnection_Roundtrips [SKIP]
      Condition(s) not met: "IsManagedImplementation"
    System.Net.Tests.HttpListenerTimeoutManagerUnixTests.Properties_DefaultValues [SKIP]
      Condition(s) not met: "IsManagedImplementation"
  Finished:    System.Net.HttpListener.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.HttpListener.Tests  Total: 549, Errors: 0, Failed: 12, Skipped: 4, Time: 63.171s
----- end Tue 09/24/2019  8:46:28.65 ----- exit code 1 ----------------------------------------------------------
```

**Comment by karelz** [comment]
Networking stress, esp. outerloop are known to be flaky. It is something we are trying to address for last few years, but the flakiness keeps coming back :(.
I recommend to exclude networking stress from JitStress runs until the functional tests are more stable.
