### ISSUE TITLE
Test failed: baseservices/threading/monitor/enter/monitorenter/monitorenter.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#13613]
**Job:**
[coreclr-gcstress0x3-gcstress0xc #20191020.1 Run Test Pri1 Linux x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=394950)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/6a648879-0b35-4e2d-b166-8f80500e43ce/workitems/baseservices.threading/console

**OS & Arch:**
linux x64

**Mode:**
COMPlus_TieredCompilation=0
COMPlus_DbgEnableMiniDump=1
COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
COMPlus_GCStress=0x3

**Note:**
This failure **doesn't repro** on our linux x64 machine.

**Log:**
```
baseservices/threading/monitor/enter/monitorenter/monitorenter.sh [FAIL]
      
      Return code:      1
      Raw output file:      /home/helixbot/work/6a648879-0b35-4e2d-b166-8f80500e43ce/Work/123a70b3-3805-4250-a9e5-bb695725a0bd/Exec/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/6a648879-0b35-4e2d-b166-8f80500e43ce/Payload/corerun monitorenter.dll ''
      null object tests
      tookLock == true tests
      timeout < -1
      timeout > int.Max
      --- no contention ---
      Positive tests, no SyncBlk
      Positive tests, with HashCode
      Positive tests, with SyncBlk
      --- a little contention ---
      Positive tests, no SyncBlk
      Positive tests, with HashCode
      Positive tests, with SyncBlk
      --- lots of contention ---
      Positive tests, no SyncBlk
      Positive tests, with HashCode
      Positive tests, with SyncBlk
      *** High thread ID tests ***
      Assertion failed
      --- no contention ---
      Positive tests, no SyncBlk
      Positive tests, with HashCode
      Positive tests, with SyncBlk
      --- a little contention ---
      Positive tests, no SyncBlk
      Positive tests, with HashCode
      Positive tests, with SyncBlk
      --- lots of contention ---
      Positive tests, no SyncBlk
      Positive tests, with HashCode
      Positive tests, with SyncBlk
      Failed!
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
```

**Comment by v-haren** [comment]
failed again in job: [ runtime-coreclr gcstress-extra 20200829.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=793873&view=ms.vss-test-web.build-test-results-tab&runId=25099986&paneView=debug&resultId=107282)

CoreCLR Windows_NT x86 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open


Error message
~~~
Return code:      1
Raw output file:      C:\h\w\95D508AB\w\96F50911\e\baseservices\threading\Reports\baseservices.threading\monitor\enter\monitorenter\monitorenter.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\95D508AB\p\corerun.exe" monitorenter.dll 
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode

Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode

Positive tests, with SyncBlk
--- lots of contention ---

Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\95D508AB\p
> C:\h\w\95D508AB\w\96F50911\e\baseservices\threading\monitor\enter\monitorenter\monitorenter.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs:line 22353
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr gcstress0x3-gcstress0xc 20201206.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=909981&view=ms.vss-test-web.build-test-results-tab&runId=29002606&resultId=105297&paneView=debug)

failed test: baseservices/threading/monitor/enter/monitorenter/monitorenter.sh

CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440


Error message
~~~
Return code:      1
Raw output file:      /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun monitorenter.dll ''
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs:line 24549
~~~

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210131.1](https://dev.azure.com/dnceng/public/_build/results?buildId=973189&view=ms.vss-test-web.build-test-results-tab&runId=30560880&paneView=debug&resultId=106056)

Failed tests:
```
CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
    - baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
```

Error message:
```
Return code:      1
Raw output file:      /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun monitorenter.dll ''
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/baseservices/threading/monitor/enter/monitorenter/monitorenter.sh

stack trace:
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_sh()
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210228.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1015821&view=ms.vss-test-web.build-test-results-tab&runId=31629670&resultId=107391&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0x3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 
-baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
```

**Error message:**
```
Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun monitorenter.dll ''
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
Expected: True
Actual: False

Stack trace
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_sh()

```

**Comment by BruceForstall** [comment]
This continues to periodically fail in the CI. I've removed the milestone and re-added `untriaged` so it can be re-triaged for 6.0 product cycle.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr r2r-extra 20210404.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1072272&view=ms.vss-test-web.build-test-results-tab&runId=32937838&resultId=107782&paneView=debug)

Failed test:
```
R2R Linux arm Checked gcstress0xf @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 -baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
```

**Error message:**
```
Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation. All rights reserved.

Native image monitorenter.dll generated successfully.

in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun monitorenter.dll ''
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
in ReleaseLock
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
Expected: True
Actual: False

Stack trace
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_sh()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210523.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1152136&view=ms.vss-test-web.build-test-results-tab&runId=34832984&resultId=108321&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0x3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

- baseservices/threading/monitor/enter/monitorenter/monitorenter.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun monitorenter.dll ''
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_sh()
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr r2r-extra 20210605.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1173433&view=ms.vss-test-web.build-test-results-tab&runId=35346524&resultId=110655&paneView=debug)

Failed test:
```
R2R Linux arm Checked gcstress0xf @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- baseservices/threading/monitor/enter/monitorenter/monitorenter.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/baseservices/threading/Reports/baseservices.threading/monitor/enter/monitorenter/monitorenter.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image monitorenter.dll generated successfully.

in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun monitorenter.dll ''
null object tests
tookLock == true tests
timeout < -1
timeout > int.Max
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
*** High thread ID tests ***
Assertion failed
--- no contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- a little contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
--- lots of contention ---
Positive tests, no SyncBlk
Positive tests, with HashCode
Positive tests, with SyncBlk
Failed!
in ReleaseLock
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/baseservices/threading/monitor/enter/monitorenter/monitorenter.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._monitor_enter_monitorenter_monitorenter_._monitor_enter_monitorenter_monitorenter_sh()
```
