### ISSUE TITLE
Test failure:System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#13634]
**Job:**
coreclr-corefx-jitstress : [20191022.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=398269)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/505d09f1-5311-4557-bd86-ef485c3510a8/workitems/System.Runtime.Loader.Tests/console

**OS & Arch:**
Windows x64

**Mode:**
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=2

**Note:**
This failure **repro** on our windows x64 machine.

**Log:**
```
C:\dotnetbuild\work\505d09f1-5311-4557-bd86-ef485c3510a8\Work\ba55b9bf-af6e-44ae-a0ab-4aa5a8ce419c\Exec>"C:\dotnetbuild\work\505d09f1-5311-4557-bd86-ef485c3510a8\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.Loader.Tests.runtimeconfig.json xunit.console.dll System.Runtime.Loader.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\505d09f1-5311-4557-bd86-ef485c3510a8\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.Loader.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Loader.Tests (found 65 test cases)
  Starting:    System.Runtime.Loader.Tests (parallel test collections = on, max threads = 2)
    System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/System.Runtime.Loader/tests/ContextualReflection.cs(659,0): at System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeTestCase(Func`1 func, Assembly nullExpected, Assembly defaultExpected, Assembly isolatedExpected)
        /_/src/System.Runtime.Loader/tests/ContextualReflection.cs(808,0): at System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated()
  Finished:    System.Runtime.Loader.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Loader.Tests  Total: 134, Errors: 0, Failed: 1, Skipped: 0, Time: 8.818s
----- end Wed 10/23/2019  7:38:00.94 ----- exit code 1 ----------------------------------------------------------
```

category:correctness
theme:tail-call
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Doesn't reproduce currently
