### ISSUE TITLE
Test Infrastructure Failure: Access to the path ... is denied

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#13650]
Hit in https://github.com/dotnet/coreclr/pull/27451/ on Run Test Pri0 Linux_musl x64 release:

```
+ /root/helix/work/correlation/corerun /root/helix/work/correlation/xunit.console.dll Exceptions/Finalization/Exceptions.Finalization.XUnitWrapper.dll Exceptions/ForeignThread/Exceptions.ForeignThread.XUnitWrapper.dll GC/Regressions/GC.Regressions.XUnitWrapper.dll GC/LargeMemory/GC.LargeMemory.XUnitWrapper.dll GC/Stress/GC.Stress.XUnitWrapper.dll GC/Features/GC.Features.XUnitWrapper.dll GC/Coverage/GC.Coverage.XUnitWrapper.dll GC/Scenarios/GC.Scenarios.XUnitWrapper.dll GC/API/GC.API.XUnitWrapper.dll Regressions/common/Regressions.common.XUnitWrapper.dll Regressions/coreclr/Regressions.coreclr.XUnitWrapper.dll readytorun/crossgen2/readytorun.crossgen2.XUnitWrapper.dll readytorun/tests/readytorun.tests.XUnitWrapper.dll readytorun/DynamicMethodGCStress/readytorun.DynamicMethodGCStress.XUnitWrapper.dll baseservices/TieredCompilation/baseservices.TieredCompilation.XUnitWrapper.dll baseservices/varargs/baseservices.varargs.XUnitWrapper.dll baseservices/compilerservices/baseservices.compilerservices.XUnitWrapper.dll reflection/DefaultInterfaceMethods/reflection.DefaultInterfaceMethods.XUnitWrapper.dll reflection/StaticInterfaceMembers/reflection.StaticInterfaceMembers.XUnitWrapper.dll reflection/SetValue/reflection.SetValue.XUnitWrapper.dll reflection/Modifiers/reflection.Modifiers.XUnitWrapper.dll CoreMangLib/system/CoreMangLib.system.XUnitWrapper.dll tracing/eventsource/tracing.eventsource.XUnitWrapper.dll tracing/tracevalidation/tracing.tracevalidation.XUnitWrapper.dll tracing/eventcounter/tracing.eventcounter.XUnitWrapper.dll tracing/eventactivityidcontrol/tracing.eventactivityidcontrol.XUnitWrapper.dll tracing/eventpipe/tracing.eventpipe.XUnitWrapper.dll tracing/tracecontrol/tracing.tracecontrol.XUnitWrapper.dll tracing/eventlistener/tracing.eventlistener.XUnitWrapper.dll Loader/AssemblyDependencyResolver/Loader.AssemblyDependencyResolver.XUnitWrapper.dll Loader/regressions/Loader.regressions.XUnitWrapper.dll Loader/ContextualReflection/Loader.ContextualReflection.XUnitWrapper.dll Loader/AssemblyLoadContext30Extensions/Loader.AssemblyLoadContext30Extensions.XUnitWrapper.dll ilasm/System/ilasm.System.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET Core 5.0.0-ci.19525.1)
  Discovering: Exceptions.Finalization.XUnitWrapper
  Discovered:  Exceptions.Finalization.XUnitWrapper
  Starting:    Exceptions.Finalization.XUnitWrapper
    Exceptions/Finalization/Finalizer/Finalizer.sh [FAIL]
      Test Infrastructure Failure: Access to the path '/root/helix/work/workitem/Exceptions/Finalization/Reports/Exceptions.Finalization/Finalizer/' is denied.
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/2/s/bin/tests/Linux.x64.Release/TestWrappers/Exceptions.Finalization/Exceptions.Finalization.XUnitWrapper.cs(142,0): at Exceptions_Finalization._Finalizer_Finalizer_._Finalizer_Finalizer_sh()
  Finished:    Exceptions.Finalization.XUnitWrapper
  Discovering: Exceptions.ForeignThread.XUnitWrapper
  Discovered:  Exceptions.ForeignThread.XUnitWrapper
  Starting:    Exceptions.ForeignThread.XUnitWrapper
    Exceptions/ForeignThread/ForeignThreadExceptions/ForeignThreadExceptions.sh [FAIL]
      Test Infrastructure Failure: Access to the path '/root/helix/work/workitem/Exceptions/ForeignThread/Reports/Exceptions.ForeignThread/ForeignThreadExceptions/' is denied.
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/2/s/bin/tests/Linux.x64.Release/TestWrappers/Exceptions.ForeignThread/Exceptions.ForeignThread.XUnitWrapper.cs(142,0): at Exceptions_ForeignThread._ForeignThreadExceptions_ForeignThreadExceptions_._ForeignThreadExceptions_ForeignThreadExceptions_sh()
```

The same  "Test Infrastructure Failure: Access to the path ..." is repeated hundreds of times for different paths

**Comment by jashook** [comment]
This has been running without issues for several months now. Closing
