### ISSUE TITLE
Test failed: Interop\BestFitMapping\BestFitMapping\BestFitMapping.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#13718]
**Job:**
[coreclr-gcstress-extra #20191102.1](https://dev.azure.com/dnceng/public/_build/results?buildId=413324)

**Detail:**
windows x64:
https://helix.dot.net/api/2019-06-17/jobs/43878d92-c298-4791-ac50-bb5922f9acda/workitems/Interop/console
windows x86:
https://helix.dot.net/api/2019-06-17/jobs/2e54b859-b523-4dfb-a261-b11f9f429f66/workitems/Interop/console

**OS & Arch:**
windows x64/x86

**Mode:**
COMPlus_TieredCompilation=0
COMPlus_GCStress=0xC
COMPlus_JitStress=2
COMPlus_ReadyToRun=0
COMPlus_ZapDisable=1

**Note:**
I try to repro this failure, but get the following output:
```
BEGIN EXECUTION
 "C:\Users\vbibu\Tests_Windows_NT_x64_checked\Tests\Core_Root\corerun.exe" BestFitMapping.dll
Beginning scenario: Cdecl,LPStr,In
ERROR!!!-e01: TestMethod_CLPStr_In:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_In(String str)
   at BestFitMapping.TestMethod_CLPStr_In() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 288
Beginning scenario: Cdecl,LPStr,Out
ERROR!!!-e02: TestMethod_CLPStr_Out:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_Out(StringBuilder str)
   at BestFitMapping.TestMethod_CLPStr_Out() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 319
Beginning scenario: Cdecl,LPStr,InOut
ERROR!!!-e03: TestMethod_CLPStr_InOut:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_InOut(StringBuilder str)
   at BestFitMapping.TestMethod_CLPStr_InOut() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 350
Beginning scenario: Cdecl,LPStr,InRef
ERROR!!!-e04: TestMethod_CLPStr_InRef:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_InByRef(StringBuilder& str)
   at BestFitMapping.TestMethod_CLPStr_InRef() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 380
Beginning scenario: Cdecl,LPStr,OutRef
ERROR!!!-e05: TestMethod_CLPStr_OutRef:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_OutByRef(StringBuilder& str)
   at BestFitMapping.TestMethod_CLPStr_OutRef() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 410
Beginning scenario: Cdecl,LPStr,InOutRef
ERROR!!!-e06: TestMethod_CLPStr_InOutRef:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_InOutByRef(StringBuilder& str)
   at BestFitMapping.TestMethod_CLPStr_InOutRef() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 442
Beginning scenario: Cdecl,LPStr,DelegatePInvoke
ERROR!!!-e07: TestMethod_CLPStr_DelegatePInvoke:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.CLPStr_DelegatePInvoke()
   at BestFitMapping.TestMethod_CLPStr_DelegatePInvoke() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 472
Beginning scenario: StdCall,LPStr,In
ERROR!!!-e08: TestMethod_SLPStr_In:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_In(String str)
   at BestFitMapping.TestMethod_SLPStr_In() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 506
Beginning scenario: StdCall,LPStr,Out
ERROR!!!-e09: TestMethod_SLPStr_Out:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_Out(StringBuilder str)
   at BestFitMapping.TestMethod_SLPStr_Out() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 536
Beginning scenario: StdCall,LPStr,InOut
ERROR!!!-e10: TestMethod_SLPStr_InOut:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_InOut(StringBuilder str)
   at BestFitMapping.TestMethod_SLPStr_InOut() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 566
Beginning scenario: StdCall,LPStr,InRef
ERROR!!!-e11: TestMethod_SLPStr_InRef:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_InByRef(StringBuilder& str)
   at BestFitMapping.TestMethod_SLPStr_InRef() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 598
Beginning scenario: StdCall,LPStr,OutRef
ERROR!!!-e12: TestMethod_SLPStr_OutRef:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_OutByRef(StringBuilder& str)
   at BestFitMapping.TestMethod_SLPStr_OutRef() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 630
Beginning scenario: StdCall,LPStr,InOutRef
ERROR!!!-e13: TestMethod_SLPStr_InOutRef:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_InOutByRef(StringBuilder& str)
   at BestFitMapping.TestMethod_SLPStr_InOutRef() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 663
Beginning scenario: StdCall,LPStr,DelegatePInvoke
ERROR!!!-e14: TestMethod_SLPStr_DelegatePInvoke:Unexpected Exception Occured:System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.SLPStr_DelegatePInvoke()
   at BestFitMapping.TestMethod_SLPStr_DelegatePInvoke() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 692
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'BestFitMappingNative' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BestFitMapping.DoCCallBack_LPSTR_In(CCallBackIn callback)
   at BestFitMapping.Main() in F:\workspace\_work\1\s\tests\src\Interop\BestFitMapping\BestFitMapping.cs:line 913
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
```
**Log:**
```
Interop\BestFitMapping\BestFitMapping\BestFitMapping.cmd [FAIL]
      
      Assert failure(PID 2032 [0x000007f0], Thread: 1336 [0x0538]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! WKS::gc_heap::mark_object_simple + 0x2A3 (0x00007fff`e7067253)
      CORECLR! WKS::GCHeap::Promote + 0x12B (0x00007fff`e704b05b)
      CORECLR! GcEnumObject + 0x72 (0x00007fff`e6f56c82)
      CORECLR! GcInfoDecoder::ReportSlotToGC + 0xCD (0x00007fff`e701e175)
      CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0xCA1 (0x00007fff`e701d399)
      CORECLR! EECodeManager::EnumGcRefs + 0x39B (0x00007fff`e6c89c6b)
      CORECLR! GcStackCrawlCallBack + 0x2CD (0x00007fff`e6f5711d)
      CORECLR! Thread::MakeStackwalkerCallback + 0x52 (0x00007fff`e69bfe02)
      CORECLR! Thread::StackWalkFramesEx + 0x17A (0x00007fff`e69c1e4e)
      CORECLR! Thread::StackWalkFrames + 0x184 (0x00007fff`e69c1c34)
      CORECLR! ScanStackRoots + 0x280 (0x00007fff`e70d4914)
      CORECLR! GCToEEInterface::GcScanRoots + 0x1DA (0x00007fff`e70d353e)
      CORECLR! WKS::gc_heap::mark_phase + 0x22D (0x00007fff`e7067605)
      CORECLR! WKS::gc_heap::gc1 + 0x28B (0x00007fff`e705f12f)
      CORECLR! WKS::gc_heap::garbage_collect + 0x63A (0x00007fff`e705edf2)
      CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x28A (0x00007fff`e7049bda)
      CORECLR! WKS::GCHeap::GarbageCollect + 0x102 (0x00007fff`e7049902)
      CORECLR! WKS::GCHeap::StressHeap + 0x621 (0x00007fff`e704c5c1)
      CORECLR! DoGcStress + 0x340 (0x00007fff`e6e7a7f4)
      -----
      .AV on tid=0x538 (1336), cxr=0000006E0177A7C0, exr=0000006E0177ACB0
      FAILED: false
      
      CORECLR! CHECK::Trigger + 0x2C5 (0x00007fff`e688c76d)
      CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x364 (0x00007fff`e6a184d4)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x69 (0x00007fff`e6a17f55)
      CORECLR! CLRVectoredExceptionHandler + 0x1C6 (0x00007fff`e6a17ece)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x00007fff`e6a1872a)
      NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ff8`153a5e90)
      NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ff8`1537fa1b)
      NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ff8`153e96fa)
      CORECLR! WKS::gc_heap::mark_object_simple + 0x2A3 (0x00007fff`e7067253)
      CORECLR! WKS::GCHeap::Promote + 0x12B (0x00007fff`e704b05b)
          File: F:\workspace\_work\1\s\src\vm\excep.cpp Line: 7537
          Image: C:\dotnetbuild\work\43878d92-c298-4791-ac50-bb5922f9acda\Payload\CoreRun.exe
      
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\43878d92-c298-4791-ac50-bb5922f9acda\Work\04d8de67-1e27-4947-a068-e70cd33cf54a\Exec\Interop\BestFitMapping\Reports\Interop.BestFitMapping\BestFitMapping\BestFitMapping.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\dotnetbuild\work\43878d92-c298-4791-ac50-bb5922f9acda\Payload\corerun.exe" BestFitMapping.dll 
      Beginning scenario: Cdecl,LPStr,In
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
```

category:testing
theme:gc-stress
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
Passes locally, also passing in CI. Will close.
