### ISSUE TITLE
Loader\binding\tracing\BinderTracingTest\BinderTracingTest.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#13803]
**Job:**
[coreclr-runincontext #20191117.1 Run Test Pri1 RunInContext Windows_NT x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=430234)

**Detail:**
win x64
https://helix.dot.net/api/2019-06-17/jobs/728f730a-d057-4beb-a504-9a4d29fba3c7/workitems/PayloadGroup0/console

**OS & Arch:**
windows x64
windows x86
linux x64

**Mode:**
win x64
RunInUnloadableContext=1 
COMPlus_TieredCompilation=0

**Note:**
I can't repro this failure on my windows x64 machine

**Log:**
```
Loader\binding\tracing\BinderTracingTest\BinderTracingTest.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\728f730a-d057-4beb-a504-9a4d29fba3c7\Work\8cd0ac24-a914-47de-ab92-ff7eed6e46f9\Exec\Loader\binding\Reports\Loader.binding\tracing\BinderTracingTest\BinderTracingTest.output.txt
      Raw output:
      BEGIN EXECUTION
      call C:\dotnetbuild\work\728f730a-d057-4beb-a504-9a4d29fba3c7\Payload\runincontext.cmd C:\dotnetbuild\work\728f730a-d057-4beb-a504-9a4d29fba3c7\Work\8cd0ac24-a914-47de-ab92-ff7eed6e46f9\Exec\Loader\binding\tracing\BinderTracingTest\ BinderTracingTest.dll 
      Running AppDomainAssemblyResolve_LoadAssembly...
      Running AppDomainAssemblyResolve_NameMismatch...
      Running AppDomainAssemblyResolve_MultipleHandlers...
      Launching process for AssemblyLoadFromResolveHandler_LoadDependency...
      Running AssemblyLoadFromResolveHandler_LoadDependency...
      
      Launching process for AssemblyLoadFromResolveHandler_MissingDependency...
      Running AssemblyLoadFromResolveHandler_MissingDependency...
      Test AssemblyLoadFromResolveHandler_MissingDependency failed: TestLibrary.AssertTestException: Assert.AreEqual: Expected: [True]. Actual: [False]. Unexpected value for IsTrackedLoad on event
         at TestLibrary.Assert.HandleFail(String assertionName, String message) in F:\workspace\_work\1\s\tests\src\Common\CoreCLRTestLibrary\Assertion.cs:line 735
         at TestLibrary.Assert.AreEqual[T](T expected, T actual, String message) in F:\workspace\_work\1\s\tests\src\Common\CoreCLRTestLibrary\Assertion.cs:line 414
         at BinderTracingTests.BinderTracingTest.ValidateLoadFromHandlerInvocation(LoadFromHandlerInvocation expected, LoadFromHandlerInvocation actual) in F:\workspace\_work\1\s\tests\src\Loader\binding\tracing\BinderTracingTest.cs:line 533
         at BinderTracingTests.BinderTracingTest.ValidateBindOperation(BindOperation expected, BindOperation actual) in F:\workspace\_work\1\s\tests\src\Loader\binding\tracing\BinderTracingTest.cs:line 486
         at BinderTracingTests.BinderTracingTest.ValidateSingleBind(BinderEventListener listener, String assemblyName, BindOperation expected) in F:\workspace\_work\1\s\tests\src\Loader\binding\tracing\BinderTracingTest.cs:line 475
         at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method) in F:\workspace\_work\1\s\tests\src\Loader\binding\tracing\BinderTracingTest.cs:line 430
      
      RunInContext FAIL! Exiting due to unhandled exception in the test: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
      File name: 'System.ComponentModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
       ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
         at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
         at TestAssemblyLoadContext.Load(AssemblyName name) in /_/src/tools/runincontext/runincontext.cs:line 179
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
         at System.ComponentModel.Component.Dispose(Boolean disposing)
         at System.ComponentModel.Component.Finalize()
      Expected: 100
      Actual: 213
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
```

**Comment by elinor-fung** [comment]
The binder tracing tests are marked `UnloadabilityIncompatible` now and query of test results from the past month don't show this failure.
