### ISSUE TITLE
C# .NET Core ReadAsStringAsync() throws System.OperationCanceledException

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/runtime#1439]
Im using C#'s `HttpClient.GetAsync()` method to make an API request from an endpoint URL, the API returns a JSON string and then I retrieve the result using `HttpContent.ReadAsStringAsync()` method. It works successfully. But when I hit `CTRL+C` on the `dotnet run` running process, unexpectedly it throws an `Unhandled exception. System.OperationCanceledException: The operation was canceled.`, is there any way to get rid of this?

My fully controller method:

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _httpClient.GetAsync("projects/7/issues?scope=all&per_page=100&page=1");
        if (result.IsSuccessStatusCode)
        {
            var content = await result.Content.ReadAsStringAsync();
            Issue[] issues = JsonSerializer.Deserialize<Issue[]>(content);
            return Json(issues);
        }
    
        return NoContent();
    }

Exception:

    Unhandled exception. System.OperationCanceledException: The operation was canceled.
       at System.Threading.CancellationToken.ThrowOperationCanceledException()
       at System.Threading.CancellationToken.ThrowIfCancellationRequested()
       at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
       at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

**Comment by scalablecory** [comment]
From your stack trace, it seems like ASP.NET's `Run()` is throwing the exception, not `HttpClient.ReadAsString()`.

If I'm understanding, your goal is that when user hits ctrl+c you do *not* want ASP.NET to close the app? @Pilchie

**Comment by justinushermawan** [comment]
@scalablecory Yes, it throws, so I need to surround `CreateHostBuilder(args).Build().Run();` with try-catch block, but it seems not the right solution. 

My goal is to make the app exiting gracefully, even when user hits CTRL+C without throwing an exception.

**Comment by Pilchie** [comment]
@anurse any ideas here?

**Comment by anurse** [comment]
(Now that we're in the same org and it's much easier to transfer issues, I'll move this to ASP.NET because it's definitely an ASP.NET question! 🎉)

This is the expected behavior if you aren't cancelling async operations during shutdown. When Ctrl-C is triggered, we call `Host.StopAsync` to trigger shutdown but we give it a `CancellationToken` that will expire in 5 seconds (configurable, see below). The `StopAsync` call is waiting for outstanding request operations to finish, and if you aren't cancelling the HttpClient request, it's causing you to overrun this timeout.

Try passing the [`HttpContext.RequestAborted`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-3.1) cancellation token into your calls to `GetAsync` and `ReadAsStringAsync` (and, in general, into any async APIs that take a `CancellationToken` that you call during the course of a request). That token will be signalled when either: the request is cancelled by the client (i.e. the TCP connection is dropped) **or** the server is being shut down.

Note that it's likely `HttpClient` will throw `OperationCancelledException` if the token is cancelled during an async operation. This is just part of the contract for most (if not all) async methods that take a CancellationToken. Including the ASP.NET Core APIs like `RunAsync`!

If you still aren't meeting the 5 second timeout even when cancelling the requests, I'd suggest ensuring you don't have any other uncancelled async operations floating around. If absolutely necessary, you can extend the shutdown timeout using [`HostOptions.ShutdownTimeout`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostoptions.shutdowntimeout?view=dotnet-plat-ext-3.1). You can configure this with this code snippet in `ConfigureServices`:

```csharp
services.Configure<HostOptions>(options => options.ShutdownTimeout = /* ... */);
```
