### ISSUE TITLE
TCP Fast Open implementation?

### ISSUE THREAD

**Issue by icylogic** [dotnet/runtime#1476]
## Proposal: TCP Fast Open

TCP Fast Open is an extension for TCP to speed up the handshaking process in successive TCP connections. This feature has been available for OSX and Linux for years and was implemented on Windows by Anniversary Update. Users could check by `netsh`
```
>netsh int tcp show global
Querying active state...

TCP Global Parameters
----------------------------------------------
...
TCP Fast Open                       : enabled
```
but dotnet has not implemented this for System.Net yet.

### Rational and Usage

This new API is important and powerful because when it is used with TLS False Start, we are down to 1-RTT from original 3-RTT for a successive TCP+TLS (HTTPS) connection, and furthermore, 0-RTT could be achieved by combining TFO and TLS 1.3.

And it's easy to use: programmers only need to add a few lines to set an socket option and provide a buffer filled with data to send. Here's the usage:

``` C#
var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
var e = new SocketAsyncEventArgs();
s.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.FastOpen, true);
e.SetBuffer(buffer, offset, length); 
s.ConnectAsync(e);
```

Note that  `buffer[offset]` ~ `buffer[offset+length-1]` might be (partially) sent together with SYN. It's up to the OS how to send.

A typical usage is the TLS handshake. In successive connections, the client could send a SYN with TLS Client Hello.

Please check the "Original Proposal" for details.

### Proposed API

``` C#
namespace System.Net.Sockets
{
    // Defines socket option names for the <see cref='System.Net.Sockets.Socket'/> class.
    public enum SocketOptionName
    {
        // ...

        #region SocketOptionLevel.Tcp
        // ...
        FastOpen = 15
        #endregion

    }
}
```

This enum value is 15 for Windows according to `ws2ipdef.h`.

### Problems & Extra works

- Implementation
  In fact, adding just one line like the code above in [SocketOptionName.cs](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Sockets/src/System/Net/Sockets/SocketOptionName.cs) would work for Windows.
  However, it might not work for Unix. Since dotnet simply pass the socket option to native API on Windows while the Unix Pal would check the value. For more information about the difference please check the relevant issue dotnet/corefx#14237 . To make this work for Unix we may need to modify [this part](https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_networking.cpp#L2103-L2113)

- Compatibility
  According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738596(v=vs.85).aspx), this option is available since Windows 10, 1607. Maybe we should generate a warning if this option is set on the older Windows platform

- Other System.Net API
  For API using sockets in its code such as WebClient or HttpClient, it could take advantage of this feature, especially for "https://" scheme.

#### TCP Fast Open on Windows
Windows has introduced TCP Fast Open in the Anniversary Update serveral months ago. ([Announcing: New Transport Advancements in the Anniversary Update for Windows 10 and Windows Server 2016](https://blogs.technet.microsoft.com/networking/2016/07/18/announcing-new-transport-advancements-in-the-anniversary-update-for-windows-10-and-windows-server-2016/))
> TFO is one full Round Trip Time (RTT) faster than the standard TCP setup which requires a three way-handshake. This leads to latency savings and is very relevant to short web transfers over the Internet where the average latency is on the order of 40 msec.

#### Native API for TCP Fast Open 
This feature could be turned on using native Windows Socket 2 API: [IPPROTO_TCP Socket Options](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738596(v=vs.85).aspx). But it has not been implemented in dotnet ([SocketOptionName.cs](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Sockets/src/System/Net/Sockets/SocketOptionName.cs)). 

#### dotnet API relating to TCP Fast Open
According to the Native API Documentation, in addition to passing a new enum value to  the method `setSocketOption` which then calls the native `setsockopt`, we need to set up the buffer including the data to send during the initial connection:
>Note that to make use of fast opens, you should use ConnectEx to make the initial connection, and specify data in that function's lpSendBuffer parameter to be transferred during the handshake process. Some of the data in lpSendBuffer will be transferred under the Fast Open protocol.

The native method `ConnectEx` is called by  [`DoOperationConnect`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L235) which is called by [`socket.ConnectAsync`](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs#L235) on Windows. And the buffer could be set as a property of SocketAsyncEventArgs.

```C#
//TFO is defined as 15 in ws2ipdef.h
socket.SetSocketOption(SocketOptionLevel.Tcp, (SocketOptionName)15, true);  
e.SetBuffer(buffer, start, length);  //e is a SocketAsyncEventArgs
socket.ConnectAsync(e);
```

#### dotnet implementation
The most straightforward way to implement this feature is to add a new value to the SocketOptionName enum. But it enables this feature only on Windows. In this issue https://github.com/dotnet/corefx/issues/14237, it seems that members are interested in introducing a new cross-platform API for TCP options.
>It would be nice if the Public API contained all of the possible socket options across Windows, Linux, and Darwin.

PS. TCP Fast Open is natively supported on Linux and OSX. Here's how to use it on Linux: [TCP Fast Open: expediting web services](https://lwn.net/Articles/508865/)

More about TCP Fast Open:
- [RFC7413](https://tools.ietf.org/html/rfc7413)
- [Windows blog: Building a faster and more secure web with TCP Fast Open, TLS False Start, and TLS 1.3](https://blogs.windows.com/msedgedev/2016/06/15/building-a-faster-and-more-secure-web-with-tcp-fast-open-tls-false-start-and-tls-1-3/#0ODjLsVbVq2W3FyD.97)

**Comment by chrisaut** [comment]
FYI SetRawSocketOption has been merged: https://github.com/dotnet/runtime/pull/33261

**Comment by scalablecory** [comment]
The API as proposed seems reasonable to me. We will also need to update our Linux PAL to use `sendto` when the user supplies a buffer.

**Comment by scalablecory** [comment]
We should investigate usage in SocketsHttpHandler, at least TLS negotiation should get a boost. Need to find out how to plumb through SslStream.

**Comment by scalablecory** [comment]
Triage: I will look at OSX APIs to ensure it is something we can implement portably, then mark as ready for review.

**Comment by terrajobst** [comment]
* We need to decide wether we throw or whether we do a softwar fallback, but naming looks fine:

```C#
namespace System.Net.Sockets
{
    public enum SocketOptionName
    {
        FastOpen = 15
    }
}
```

**Comment by deeprobin** [comment]
@terrajobst 

I think a software fallback would be useful.
As far as I know TCP_FASTOPEN is supported under Linux only from kernel version 3.6 on the client side and 3.7 on the server side. We should perhaps evaluate how to deal with features that do not work in older kernel versions elsewhere as a basis for decision making.

How this behaves under Windows I do not know just now.

**Comment by sakno** [comment]
`SetRawSocketOption` is not enough: https://lwn.net/Articles/508865/

It seems like the socket at the client side must be configured properly. `sendto` requires to set `MSG_FASTOPEN`  flag when using with TFO. Thus, `SocketFlags` enum must be modified as well.

**Comment by deeprobin** [comment]
> `SetRawSocketOption` is not enough. It seems like the socket at the client side must be configured properly. `sendto` requires to set `MSG_FASTOPEN` flag when using with TFO. Thus, `SocketFlags` enum must be modified as well.

@sakno

I think that's a good point. This API needs a new review. Possibly with the following additional API:

```cs
public partial enum SocketFlags {
    FastOpen = 0x20000000, // or TcpFastOpenMessage?
}
```

### libc Constant Reference: 
|constant|value|
|-|-|
|`TCP_FASTOPEN`|23|
|`MSG_FASTOPEN`|0x20000000|

---

We should also note that under Linux this may need to be explicitly enabled in `/proc/sys/net/ipv4/tcp_fastopen`.
I do not know how we should proceed then in case it would not be enabled (due disabled in config / unsupported kernel version). Throw InvalidOperationException/NotSupportedException or just ignore it and not use TCP Fast Open?

```sh
# Disabled
echo "0"> /proc/sys/net/ipv4/tcp_fastopen 

# Client-only
echo "1"> /proc/sys/net/ipv4/tcp_fastopen 

# Server-only
echo "2"> /proc/sys/net/ipv4/tcp_fastopen 

# full support
echo "3"> /proc/sys/net/ipv4/tcp_fastopen 
```

**Comment by deeprobin** [comment]
pinging @karelz

**Comment by antonfirsov** [comment]
@deeprobin is anything wrong with the usage proposed by the OP? The underlying Unix PAL (platform abstraction layer) could use a `sendto` syscall instead of `connect` in a transparent manner when `TcpFastOpen` is set and there is a buffer available on `SocketAsyncEventArgs`.

Using `SendTo` / `ReceiveFrom` API-s directly comes with a big performance penalty today, I wouldn't recommend it (see #30797).

**Comment by ScotMac** [comment]
So, what was the conclusion for this?

The SetSocketOption value pass-thru appears to work for turning on TFO. However, for the send/buffer, it appears that a new SocketFlag on the send was proposed, but not finalized?

**Comment by antonfirsov** [comment]
`MSG_FASTOPEN` is not cross-platform, so I would prefer looking for alternatives to the SocketFlag. For example, we could set `MSG_FASTOPEN` transparently, or use `TCP_FASTOPEN_CONNECT` (needs Linux 4.11+).

Someone needs to go and prototype this feature, ideally including it's usage by higher layers of the stack as https://github.com/dotnet/runtime/issues/1476#issuecomment-628733712 recommends.

**Comment by ScotMac** [comment]
OK, so the MSG_FASTOPEN *also* works for the sendto? But only on certain platforms?  Can you provide the details please?

**Comment by ScotMac** [comment]
Can someone point me to how to use .NET to turn on TFO and send TFO data? Preferably in a platform independent manner. Is there some other issue that handles this?

**Comment by ScotMac** [comment]
> @deeprobin is anything wrong with the usage proposed by the OP? The underlying Unix PAL (platform abstraction layer) could use a `sendto` syscall instead of `connect` in a transparent manner when `TcpFastOpen` is set and there is a buffer available on `SocketAsyncEventArgs`.
> 
> Using the managed `SendTo` / `ReceiveFrom` API-s directly comes with a big performance penalty today (see #30797), I wouldn't recommend it.

This seems to be a problem. ie, I don't believe you did the implementation the OP asked for, and the pass-thru implementation appears to have a big performance problem. Please look into doing the original proposal, where you handle the C native calls for sendto vs connect underneath the covers.

**Comment by ScotMac** [comment]
OK, this is what i am doing, as a pass-thru to the C native API for SendTo (SetSockOpt does NOT appear to be needed):

m_client.Client.SendTo(Encoding.ASCII.GetBytes(m_conOption.ConnectData), 0, m_conOption.ConnectData.Length, 
            (System.Net.Sockets.SocketFlags) 0x20000000, new IPEndPoint(addr, m_portNo));

Is this the right approach?

**Comment by ScotMac** [comment]
It appears that the "pass-thru" for the SendTo() is not support (like it IS for the SetSockOpt(). When i try it, I get the following error:

 SE : System.Net.Sockets.SocketException (95): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at OracleInternal.Network.TcpTransportAdapter.ConnectIterate()

**Comment by ScotMac** [comment]
And from this issue:

https://github.com/dotnet/runtime/issues/28706

It appears that Send/SendTo are  validating the flags, so no PASS-THRU flag is going to work.

**Comment by antonfirsov** [comment]
While in #99490 we are planning to introduce this feature so customers can use it on their own risk, we must issue an important warning about its reliability:
 
A non trivial percentage of middleboxes (routers, firewalls, proxies) in the open web will drop SYN packets containing TFO cookies. According to [this article](
https://candrews.integralblue.com/2019/03/the-sad-story-of-tcp-fast-open), the ratio was 5% in 2019. This could lead to software bugs and failures that are very difficult to diagnose.
 
We consulted with the Windows networking team, and they confirmed that this concern is valid. It has prevented them from utilizing the feature as an enabled-by-default optimization in higher-level Windows components.
 
In practice, TFO is only reliable in controlled networking environments. This means that if an organization wants to optimize their solutions with TFO, they need full control over each firewall, router, and proxy on the network path between the client and the server. They need the rights and expertise to configure these middleboxes and they need to be committed to maintain the configuration. In my understanding this essentially excludes most cloud scenarios.
 
Also note that on Windows there is an aggressive TFO fallback mechanism that completely disables TFO globally until next restart when it detects problems with it. In my experiments I was never able to see a TFO cookie on a Windows system without first disabling this mechanism using `netsh int tcp set global fastopenfallback=disabled`. I assume there is a strong reason for the presence of this mechanism, and there is a risk that disabling it for one software may break other software on the same machine.

**Comment by antonfirsov** [comment]
@ScotMac considering the problems described above, how do you still find TFO useful for your scenario?

**Comment by karelz** [comment]
@ScotMac ping?

**Comment by wfurt** [comment]
Note that the linked  https://github.com/dotnet/runtime/pull/99490 brings back the idea  @icylogic originally mentioned 
```c#
var s = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
var e = new SocketAsyncEventArgs();
s.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.FastOpen, true);
e.SetBuffer(buffer, offset, length); 
s.ConnectAsync(e);
```

This fragment will now work across all platforms. On top of it, it adds the approved  `FastOpen` enum. When used in combination AND when TFO is actually enabled at OS level AND the TCP stack has proper cookies, part (or all of the provided) data will go it together with initial SYN. Otherwise it would just go out when TCP is established. 

We don't plan to add more API at the moment but once can write simple extension. Perhaps something like 
```c#
internal static void Connect(this Socket socket, EndPoint ep, Memory<byte> buffer, int timeout)
{
    var re = new ManualResetEventSlim();
    var saea = new SocketAsyncEventArgs();
    saea.SetBuffer(buffer);
    saea.RemoteEndPoint = ep;
    saea.Completed += (_, __) => re.Set();
    if (!socket.ConnectAsync(saea))
    {
        re.Wait(timeout);
    }
}
```

**Comment by ScotMac** [comment]
We are discussing it internally. Thanks for the ping.

**Comment by ScotMac** [comment]
Based on the fact that we will have a good number of people using this within the cloud (not the public internet), we believe that 5% will not apply to us. And for a good number of those customers, the client will be on Linux.

So, yes, please continue w/ the implementation.

**Comment by ScotMac** [comment]
@wfurt Hi, did your implementation make it into .NET 9 Preview 5? Is the new enum, specified here (SocketOptionName.FastOpen) implemented for your solution?

**Comment by wfurt** [comment]
no, it was submitted after the cutoff. It should be part of preview 6 - around Jul 9 . If you want to proceed on testing you can grab daily build: https://github.com/dotnet/sdk/blob/main/documentation/package-table.md
