### ISSUE TITLE
[Win7] Test failure: System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests / ClientCertificates_ValidCertificate_ServerReceivesCertificateAndConnectAsyncSucceeds

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/runtime#1491]
## Type of failure

```
Assert.NotNull() Failure
at System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.<>c__DisplayClass8_0.<<ClientCertificates_ValidCertificate_ServerReceivesCertificateAndConnectAsyncSucceeds>b__3>d.MoveNext() in E:\A\_work\63\s\corefx\src\System.Net.WebSockets.Client\tests\ClientWebSocketOptionsTests.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in E:\A\_work\63\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 117
at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in E:\A\_work\63\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in E:\A\_work\63\s\corefx\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
at System.Net.WebSockets.Client.Tests.ClientWebSocketOptionsTests.ClientCertificates_ValidCertificate_ServerReceivesCertificateAndConnectAsyncSucceeds() in E:\A\_work\63\s\corefx\src\System.Net.WebSockets.Client\tests\ClientWebSocketOptionsTests.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
```

## History of failure

Day | Build | Details
-- | -- | --
3/7 | 20180307.03 | 2x
3/7 | 20180307.04 | 2x
3/7 | 20180307.06 | 2x
3/8 | 20180308.01 | 2x
3/8 | 20180308.02 | 2x
3/8 | 20180308.06 | 2x
3/8 | 20180308.09 | 2x
3/10 | 20180310.01 | 2x
3/10 | 20180310.02 | 2x
3/11 | 20180311.01 | 2x
3/11 | 20180311.02 | 2x
3/12 | 20180312.01 | 2x
3/12 | 20180312.02 | 2x
3/13 | 20180313.01 | 2x
3/13 | 20180313.03 | 2x
3/14 | 20180314.01 | 2x

**Comment by wfurt** [comment]
Win7 is out of support. closing.
