### ISSUE TITLE
An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#1500]
Run the following repro

```c#
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Headers;

class X {

	private HttpClient _httpClient;

	void Foo ()
	{
		_httpClient = new HttpClient ();
		_httpClient.DefaultRequestHeaders.UserAgent.Add (new ProductInfoHeaderValue ("name", "version"));
		_httpClient.DefaultRequestHeaders.UserAgent.Add (new ProductInfoHeaderValue ("(comment)"));
	}

	private async Task DoIt () => await Task.Run (DoThat);

	private async Task DoThat ()
	{
		//
		// This does not always throw exception but should, someone is modifying default headers while other requests are in flight
		//
		_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue ("ping", "pong");

		await _httpClient.GetAsync ("http://neverssl.com");
	}

	public static void Main ()
	{
		while (true) {
			var x = new X ();
			x.Foo ();
			Task.WhenAll (x.DoIt (), x.DoIt ()).Wait ();
		}
	}
}
```

It occasionally hits a race when setting up the request in such case it terminates with the following exception
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor) ---> System.ArgumentException: An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Net.Http.Headers.HttpHeaders.GetOrCreateHeaderInfo(HeaderDescriptor descriptor, Boolean parseRawValues)
   at System.Net.Http.Headers.HttpHeaders.SetParsedValue(HeaderDescriptor descriptor, Object value)
   at System.Net.Http.Headers.HttpRequestHeaders.set_Authorization(AuthenticationHeaderValue value)
   at X.DoThat() in Program.cs:line 23
   at X.DoIt() in Program.cs:line 16
```

The code is racy but I think we should do a better job by making the failure more obvious

**Comment by aik-jahoda** [comment]
Added remark into the documentation.
