### ISSUE TITLE
null value is handled incorrectly for PropertyChangedEventHandler

### ISSUE THREAD

**Issue by Kill4kan** [dotnet/runtime#1527]
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/System.Private.CoreLib/src/System/StubHelpers.cs#L599

This code throws an exception in UWP when the INotifyPropertyChanged.PropertyChanged event is raised with a null parameter as follows:

PropertyChanged(this, new PropertyChangedEventArgs(null));

The callstack is:
at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)
at System.StubHelpers.EventArgsMarshaler.CreateNativePCEventArgsInstance(String name)
at System.Runtime.InteropServices.WindowsRuntime.PropertyChangedEventArgsMarshaler.ConvertToNative(PropertyChangedEventArgs managedArgs)
at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)

According to .NET [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=netframework-4.8), this parameter is valid:

_The PropertyChanged event can indicate all properties on the object have changed by using either null or String.Empty as the property name in the PropertyChangedEventArgs._

**Comment by ericstj** [comment]
@jkoritzinsky I believe this code was deleted from dotnet/runtime recently.  We should make sure we don't have the same bug in C#-winrt.

**Comment by jkoritzinsky** [comment]
C#/WinRT does not have the same bug. It returns null instead as it should.
