### ISSUE TITLE
Add async dispose support to ZipArchive

### ISSUE THREAD

**Issue by MarcusWichelmann** [dotnet/runtime#1560]
In my application I am creating a ZipArchive that writes directly to the ASP.Net Core body stream, like that:

```C#
using var zipArchive = new ZipArchive(Response.Body, ZipArchiveMode.Create, true);
```

Asynchronously writing file contents to that archive works fine, but as soon as the writing is finished and the `ZipArchive` gets disposed, the `ZipArchive` tries to synchronously write some more data to the stream. This results in an exception, because Kestrel, by default, doesn't allow synchronous writes anymore:

```C#
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.PositionPreservingWriteOnlyStreamWrapper.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryWriter.Write(UInt32 value)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at System.IO.Compression.ZipArchive.Dispose()
```

Enabling async disposal for this class and then doing the necessary writes asynchronously would probably resolve this issue.

**Comment by madelson** [comment]
This would be beneficial for us as well!

**Comment by anranruye** [comment]
Is there any progress?

**Comment by anranruye** [comment]
A workaround for this scenario is to use `Response.BodyWriter.AsStream()` instead.

**Comment by carlossanlop** [comment]
The discussion in this issue has been very helpful. I think we should implement all ZipFile and ZipArchive async APIs at the same time. For that reason, I'll close this issue in favor of the oldest and most generic issue (https://github.com/dotnet/runtime/issues/1541), and will add a comment there to make sure to come back here to look at the comments here.
