### ISSUE TITLE
SignalR issues due to lack of ISerializable and TimeZoneInfo support

### ISSUE THREAD

**Issue by tgundhus** [dotnet/runtime#1565]
#### Original issue: 
aspnet/AspNetCore/issues/14422

Serialization of TimeZoneInfo.Local fails and results in an incorrect json when sending over SignalR.

The Client uses version 3.0.
The Server is built on .NET core 2.2. 

Client code:
`HubConnection.SendAsync("Initialize", DateTime.UtcNow, TimeZoneInfo.Local);`

Server code:
`[public async Task Initialize(DateTime clientTimeInUTC, TimeZoneInfo clientTimeZone) { .. }]`

### Expected  behavior
How the TimeZoneInfo should be parsed, and is parsed if I use NewtonSoft serializer directly.
```
{
  "id": "W. Europe Standard Time",
  "displayName": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "standardName": "W. Europe Standard Time",
  "daylightName": "W. Europe Daylight Time",
  "baseUtcOffset": {
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
  },
  "supportsDaylightSavingTime": true
}
```

### Actual behavior
How it is sent via SignalR.  You can see an extra curly bracket on line 1 in the JSON. These are ONLY added if I sent through signalR. If I serialize TimeZoneInfo using NewtonSoft in either the server or the client, this works perfect and gives the json listed above. 
```
{{
  "id": "W. Europe Standard Time",
  "displayName": "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "standardName": "W. Europe Standard Time",
  "daylightName": "W. Europe Daylight Time",
  "baseUtcOffset": {
    "ticks": 36000000000,
    "days": 0,
    "hours": 1,
    "milliseconds": 0,
    "minutes": 0,
    "seconds": 0,
    "totalDays": 0.041666666666666664,
    "totalHours": 1,
    "totalMilliseconds": 3600000,
    "totalMinutes": 60,
    "totalSeconds": 3600
  },
  "supportsDaylightSavingTime": true
}}
```

#### Exception
Exception message: _System.Runtime.Serialization.SerializationException: Member 'Id' was not found._
```
2019-09-25 10:41:37 Failed to invoke hub method '"Initialize"'.
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.Runtime.Serialization.SerializationException: Member 'Id' was not found.
   at System.Runtime.Serialization.SerializationInfo.GetElement(String name, Type& foundType)
   at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
   at System.TimeZoneInfo..ctor(SerializationInfo info, StreamingContext context)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
```

#### Workaround
We've current added NewtonSoftJson to our HubConnection builder `.AddNewtonsoftJsonProtocol()` which solved the issue and everything is now working as before the update. 
[MSDN: switch to Newtonsoftjson](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#switch-to-newtonsoftjson)

**Comment by ahsonkhan** [comment]
Next steps: We should validate our serializer behavior - and throw NSE for TimeZoneInfo for both serialize and deserialize (to make the intent clear). Currently serializing the "wrong" output, silently, is incorrect.

If we need proper support for TimeZoneInfo, let's file a separate issue and special case that.

**Comment by eiriktsarpalis** [comment]
Bumping this. Is adding support for `ISerializable` really on the cards for STJ? It would require supporting unchecked polymorphic serialization and as such it's unlikely it would meet the bar from a security perspective.
