### ISSUE TITLE
non-UTF8 encoded JSON docs to throw NotSupportedException

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#1572]
I am in the process of adding `System.Text.Json` parser to JSONTestSuite: https://github.com/am11/JSONTestSuite/tree/feature/dotnet-system-text-json/parsers/test_dotnet_system_text_json.

Currently, the following four tests are failing:

1. [i_string_UTF-16LE_with_BOM.json](https://github.com/nst/JSONTestSuite/tree/e3d9a17/test_parsing/i_string_UTF-16LE_with_BOM.json)
    * > System.Text.Json.JsonReaderException: '0xFF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
2. [i_string_utf16BE_no_BOM.json](https://github.com/nst/JSONTestSuite/tree/e3d9a17/test_parsing/i_string_utf16BE_no_BOM.json)
    * > System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
3. [i_string_utf16LE_no_BOM.json](https://github.com/nst/JSONTestSuite/tree/e3d9a17/test_parsing/i_string_utf16LE_no_BOM.json)
    * > System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 1.
4. [i_structure_500_nested_arrays.json](https://github.com/nst/JSONTestSuite/tree/e3d9a17/test_parsing/i_structure_500_nested_arrays.json)
    * > System.Text.Json.JsonReaderException: The maximum configured depth of 64 has been exceeded. Cannot read next JSON array. LineNumber: 0 | BytePositionInLine: 64.
    * AFAICT, this limit is not adjustable by API consumer.

Should `NotSupportedException` be thrown in case of 1, 2 and 3 with message indicating that non-UTF8 encodings are unsupported?

I found two places, where similar white-listing / checking for encoding is employed:

1. https://github.com/dotnet/corefx/blob/f4344b0d3b45fc7c8f41e5c909ddcb2752bea0fa/src/System.Private.DataContractSerialization/src/System/Xml/EncodingStreamWrapper.cs#L22
2. https://github.com/dotnet/corefx/blob/f4344b0d3b45fc7c8f41e5c909ddcb2752bea0fa/src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JsonEncodingStreamWrapper.cs#L57-L63

**Comment by ahsonkhan** [comment]
Given we are planning to add a transcoding stream (https://github.com/dotnet/runtime/issues/30260), there is less need for supporting non-UTF-8 encoded streams in the serializer directly. The primary benefit of doing it natively would be performance. Moving to future.

**Comment by Yomodo** [comment]
Exactly the exception I get with those code. Too bad.

```
var gitDesc = new GitVersionDescriptor {Version = "main"};

         foreach (var item in items.OrderBy(j => j.Path))
         {
            var fileName = Path.GetFileName(item.Path);

            using var stream = _gitClient.GetItemContentAsync(repo.Id, $"/{TemplatesRoot}/{fileName}", versionDescriptor: gitDesc);
            
            using var task5 = JsonDocument.ParseAsync(await stream, TenantToolCore.JsonDocumentOptions);
            using var document = await task5;

            yield return document.RootElement.Clone();
         }



System.Text.Json.JsonReaderException: '0xFF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
```
