### ISSUE TITLE
InvalidCastException when deserialising invalid List/IEnumerable from JSON

### ISSUE THREAD

**Issue by GREsau** [dotnet/runtime#1575]
```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace DotNetTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var json = @"{ ""MyList"": ""not a list!"" }";
            try
            {
                JsonSerializer.Deserialize<ModelWithList>(json);
                Console.WriteLine($"Deserialization of '{json}' to ModelWithList succeeded!");
            }
            catch (Exception e)
            {
                Console.Write($"Deserialization of '{json}' to ModelWithList failed: ");
                Console.WriteLine(e);
            }
        }
    }

    class ModelWithList
    {
        public List<string> MyList { get; set; }
    }
}
```

I would expect this to result in a JsonException, but it actually results in an InvalidCastException:
```
Deserialization of '{ "MyList": "not a list!" }' to ModelWithList failed: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Collections.Generic.IEnumerable`1[System.String]'.
   at System.Text.Json.JsonPropertyInfoCommon`4.SetValueAsObject(Object obj, Object value)
   at System.Text.Json.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at DotNetTest.Program.Main(String[] args) in C:\work\DotNetTest\Program.cs:line 14
```

**Comment by layomia** [comment]
This is fixed in 3.1.

**Comment by ahsonkhan** [comment]
@GREsau, presumably you were running on .NET Core 3.0 OR referencing an older version of the System.Text.Json package (4.6.0).

Were you able to upgrade to .NET Core 3.1 OR System.Text.Json package (4.7.0) and resolve this issue?

**Comment by GREsau** [comment]
Yep, all good in 3.1!
