### ISSUE TITLE
Test: System.Net.Sockets.Tests.SendReceiveEap.SendToRecvFrom_Datagram_UDP(loopbackAddress: ::1) failed in CI

### ISSUE THREAD

**Issue by KristinXie1** [dotnet/runtime#1712]
Failed test: System.Net.Sockets.Tests.SendReceiveEap.SendToRecvFrom_Datagram_UDP(loopbackAddress: ::1)
Configuration: OuterLoop_CentOS7.1_debug ([build#123](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug/123/testReport/))

Message:
~~~
System.Net.Sockets.Tests.SendReceiveEap.SendToRecvFrom_Datagram_UDP(loopbackAddress: ::1) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(148,0): at System.Net.Sockets.Tests.SendReceive.<SendToRecvFrom_Datagram_UDP>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug/123/consoleText

**Comment by antonfirsov** [comment]
This is a major blocker for implementing #938, since we need a robust way to test UDP, if we want to cover those changes.

**Comment by antonfirsov** [comment]
This failure is likely not about port stealing or any other direct interference with other tests.

The test tends to fail when CPU load is high. I can reproduce the failure by running the Theory's cases in parallel with a single other test case that calculates PI.
