### ISSUE TITLE
CloseOutputAsync_Cancel_Success - failure in Assert.Equal

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#1725]
Platform: Linux arm release
Pipeline: runtime-libraries outerloop-linux
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=482388&view=logs&j=214ce225-49cc-5240-836e-21c9eea7fd5c&t=b7252a1f-0482-5ee0-8d5b-0c274fc0e2e0

Proximate diagnostic info:

<pre>
  Starting:    System.Net.WebSockets.Client.Tests (parallel test collections = on, max threads = 4)
    System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx) [FAIL]
      Assert.Equal() Failure
      Expected: Aborted
      Actual:   Open
      Stack Trace:
        /_/src/libraries/System.Net.WebSockets.Client/tests/ClientWebSocketTestBase.cs(76,0): at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server)
        /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs(97,0): at System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(Uri server)
        --- End of stack trace from previous location ---
      Output:
        GetConnectedWebSocket: ConnectAsync starting.
        GetConnectedWebSocket: ConnectAsync done.
  Finished:    System.Net.WebSockets.Client.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.WebSockets.Client.Tests  Total: 100, Errors: 0, Failed: 1, Skipped: 0, Time: 11.162s
</pre>

One thing I find weird is the "Expected = Aborted, Actual = Open" - that's not what I'd expect in the presence of transient network failures.

**Comment by AriNuer** [comment]
Same test `System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)` has failed.

**Job:**
[runtime-libraries outerloop:#20200304.1](https://dev.azure.com/dnceng/public/_build/results?buildId=546039&view=results)

**Error message:**
```
Assert.Equal() Failure
Expected: Aborted
Actual: Open
```
**Stack trace:**
```
 at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/ClientWebSocketTestBase.cs:line 76
   at System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 97
--- End of stack trace from previous location ---
```

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=546039&view=ms.vss-test-web.build-test-results-tab&runId=17270276&resultId=102009&paneView=debug

**Comment by AriNuer** [comment]
Test `System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success` failed again:
**Job:**
[runtime-libraries outerloop20200317.2](https://dev.azure.com/dnceng/public/_build/results?buildId=561936&view=results)
**Error message:**
```
Assert.Equal() Failure
Expected: Aborted
Actual: Open
```
**Stack trace:**
```
   at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/ClientWebSocketTestBase.cs:line 76
   at System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 97
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=561936&view=ms.vss-test-web.build-test-results-tab&runId=17683058&resultId=102217&paneView=debug

**Comment by BruceForstall** [comment]
@wfurt

**Comment by AriNuer** [comment]
Test `System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success` failed again:
[runtime-libraries outerloop:20200330.1](https://dev.azure.com/dnceng/public/_build/results?buildId=579439&view=results)
**Error message:**
```
Assert.Equal() Failure
Expected: Aborted
Actual: Open
```
**Stack trace:**
```
at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/ClientWebSocketTestBase.cs:line 76
   at System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 97
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=579439&view=ms.vss-test-web.build-test-results-tab&runId=18211894&resultId=100835&paneView=debug

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200413.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=598251&view=ms.vss-test-web.build-test-results-tab&runId=18843458&resultId=100406&paneView=debug)


Error message
~~~
Assert.Equal() Failure
Expected: Aborted
Actual: Open


Stack trace
   at System.Net.WebSockets.Client.Tests.ClientWebSocketTestBase.TestCancellation(Func`2 action, Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/ClientWebSocketTestBase.cs:line 76
   at System.Net.WebSockets.Client.Tests.CancelTest.CloseOutputAsync_Cancel_Success(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 97
--- End of stack trace from previous location ---
~~~
