### ISSUE TITLE
System.Diagnostics.Process.Enable raising events sometimes throws

### ISSUE THREAD

**Issue by MattKotsenas** [dotnet/runtime#1785]
I'm filing this issue as part of follow up from PR #1278. Setting `EnableRaisingEvents` to true on Systems.Diagnostics.Process after the process has already exited throws an `InvalidOperationException` in some cases, but not in others.

More specifically, it throws if the process is a "copy", which is created via methods like `Process.GetProcessById()` and `Process.GetProcessesByName()`.

Here's a repro case that shows both behaviors:

```csharp
using System;
using System.Diagnostics;
using System.Threading;

class Program
{
    static void Main(string[] args)
    {
        var timeout = TimeSpan.FromSeconds(5);

        var p = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "cmd.exe",
                Arguments = $"/c timeout /t {timeout.TotalSeconds} /nobreak",
                UseShellExecute = false,
            }
        };

        Console.WriteLine("Staring main process...");
        p.Start();
        Console.WriteLine($"PID = {p.Id}");

        Console.WriteLine("Creating 'copy' of process by PID");
        var copy = Process.GetProcessById(p.Id);

        Console.WriteLine("Waiting for main process to exit...");
        Thread.Sleep(timeout * 2);

        Console.WriteLine("Enabling events on main process");
        p.EnableRaisingEvents = true;

        Console.WriteLine("Enabling events on 'copy'");
        copy.EnableRaisingEvents = true;

        Console.WriteLine("Done!");
    }
}
```

```
Staring main process...
PID = 37344
Creating 'copy' of process by PID
Waiting for main process to exit...

Waiting for 0 seconds, press CTRL+C to quit ...
Enabling events on main process
Enabling events on 'copy'
Unhandled exception. System.InvalidOperationException: Cannot process request because the process (37344) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.EnsureWatchingForExit()
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   at Program.Main(String[] args) in C:\Users\mattkot\Desktop\temp\ConsoleApp1\Program.cs:line 35
```

When getting a process by Id or name, the Process object defers getting a handle to the process. Then `EnableRaisingEvents` eventually calls `GetProcessHandle` with `throwIfExited: true`.

I'm opening this to determine what the correct behavior should be. It feels odd to me that the Process object should behave differently depending on how it was constructed _plus_ whether or not a handle has been opened yet.

**Comment by nohwnd** [comment]
@MattKotsenas Thanks for pointing out that this only works on a "copy". I was trying to repro an issue and it did not repro when I started the process directly. 👍
