### ISSUE TITLE
ConnectAsync_NotWebSocketServer_ThrowsWebSocketExceptionWithMessage failing

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#1895]
The test `ConnectAsync_NotWebSocketServer_ThrowsWebSocketExceptionWithMessage` is failing and blocking the libraries linux outerloop jobs. 

Failure stack:

```
    System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_NotWebSocketServer_ThrowsWebSocketExceptionWithMessage(server: ws://2a026e6b-eb9b-43f4-afcf-a1a94b87027e/, exceptionMessage: "Unable to connect to the remote server", errorCode: Faulted) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Net.WebSockets.WebSocketException)
      Actual:   typeof(System.Threading.Tasks.TaskCanceledException): The operation was canceled.
      ---- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(117,0): at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs(650,0): at System.Net.Sockets.SocketAsyncEventArgs.FinishConnectByNameAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(339,0): at System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception e)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(402,0): at System.Net.Sockets.MultipleConnectAsync.CallAsyncFail(Object ignored)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(361,0): at System.Net.Sockets.MultipleConnectAsync.<Cancel>b__20_0(Object s)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2380,0): at System.Threading.Tasks.Task.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2359,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(300,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2333,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2258,0): at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2243,0): at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs(659,0): at System.Threading.ThreadPoolWorkQueue.Dispatch()
        /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs(29,0): at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(55,0): at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(661,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(665,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(331,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(523,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs(171,0): at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
        /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs(152,0): at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(117,0): at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs(650,0): at System.Net.Sockets.SocketAsyncEventArgs.FinishConnectByNameAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(339,0): at System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception e)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(402,0): at System.Net.Sockets.MultipleConnectAsync.CallAsyncFail(Object ignored)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(361,0): at System.Net.Sockets.MultipleConnectAsync.<Cancel>b__20_0(Object s)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2380,0): at System.Threading.Tasks.Task.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2359,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(300,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2333,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2258,0): at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2243,0): at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs(659,0): at System.Threading.ThreadPoolWorkQueue.Dispatch()
        /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs(29,0): at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(55,0): at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(661,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(665,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(331,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(523,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs(171,0): at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
        /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs(152,0): at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
  Finished:    System.Net.WebSockets.Client.Tests
```

This test has been failing for 2+ days. 

Example Builds: 
- https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/Builds/487498
- https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/Builds/485926

**Comment by jaredpar** [comment]
Note this failure seems to come only in the following queues:
- netcoreapp5.0-Linux-Release-arm-(Debian.9.Arm32.Open)Ubuntu.1804.ArmArch.Open
- netcoreapp5.0-Linux-Release-arm64-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open

**Comment by karelz** [comment]
The test was disabled on all platforms in PR #1896 ...
