### ISSUE TITLE
linux System.ArgumentException: Parameter is not valid.    at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)

### ISSUE THREAD

**Issue by fjod** [dotnet/runtime#1920]
Hello .net team!
I have small app on .net core 3.1, part of it downloads images from web and stores in DB. It works nice on windows. On linux (debian 10) it works fine with some images and throws images on other. I tested this code on windows to donwload thousands of images, so there is something wrong with linux one.

here is code to get images:
```

var retWOrks = CrawlerBitmap.DownloadImage(
                "http://avatars.mds.yandex.net/get-autoru-vos/2106286/3fbfed61bff31136bcda59010e092218/1200x900n");
            
            var ret =CrawlerBitmap.DownloadImage(            
                "http://auto.ru/_crpd/26BRt9D25/f3cdbc3cR/DBGiNNzAMe1C9L3wp-XU-dmc05ME9LCtU9FZci7PTFEJgDKpjvDebkFTQ38vrMoRDm7KPdrwAzdq2iWUU55CKQRc8wTMgHWcFu2o2Zqs0ayEvKvKdeTMiEcQPf6yB1QxSJjG2ccZm59ouoZyWlhb2Muaj3S3OJO_Jpf0UV5amnncWUYsTEi4ASJgbPAHiUhV1Snnb6R1IK2jzP1OmqvUlZQAyokDfbsD8BZKUqZ4hwArKhekj4CHD1oPUJGyykaxyB2E");
            
           Console.WriteLine($@"{ret.Height}");
            Console.WriteLine($@"{retWOrks.Height}");
            Console.WriteLine("Hello world");
            

```

and here is code for DownloadImage:
```

public static class CrawlerBitmap
    {
        private static System.Net.WebClient _webClient;
        public static Image DownloadImage(string fromUrl)
        {
            if (_webClient == null)
            {
                _webClient = new System.Net.WebClient();
            }
            Image ret = null;
            Random rand1 = new Random();
            
            Console.WriteLine($"Started at {DateTime.Now}");
            using (var stream = _webClient.OpenRead(fromUrl))
            {
                ret = Image.FromStream(stream);
            }
            Console.WriteLine($"Exiting at {DateTime.Now}");
            Thread.Sleep(TimeSpan.FromSeconds(rand1.Next(5, 15)));
            return ret;
        }
}
```

Output:
```

fjod@fjordbox:~/crawler/publish$ /usr/bin/dotnet /home/fjod/crawler/publish/CuteDOS.dll
Started at 1/19/2020 4:08:08 AM
Exiting at 1/19/2020 4:08:08 AM
Started at 1/19/2020 4:08:17 AM
Unhandled exception. System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromStream(Stream stream)
   at Domain.ImageComparison.CrawlerBitmap.DownloadImage(String fromUrl) in /builds/fjod/crawler/Domain/ImageComparison/CrawlerBitmap.cs:line 25
```

line 25 is 

` ret = Image.FromStream(stream);`

**Comment by fjod** [comment]
looks like something wrong with cookies, not .net issue

**Comment by fjod** [comment]
I continued investigation of this issue. Now I have two Ubuntu 18.04, one is on my laptop, another is vps. Program above works on laptop with output:

```
/snap/rider/38/lib/ReSharperHost/runtime.sh /snap/rider/38/lib/ReSharperHost/JetBrains.Debugger.Worker.exe --mode=client --frontend-port=38247 --plugins=
Started at 2/3/2020 9:24:56 AM
Exiting at 2/3/2020 9:24:57 AM
Started at 2/3/2020 9:25:05 AM
Exiting at 2/3/2020 9:25:06 AM
900
900
Hello world

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00400000-00871000 r-xp 00000000 07:15 2300                               /snap/rider/38/lib/ReSharperHost/linux-x64/mono/bin/mono-sgen
00a71000-00a7f000 rw-p 00471000 07:15 2300                               /snap/rider/38/lib/ReSharperHost/linux-x64/mono/bin/mono-sgen
00a7f000-00a9a000 rw-p 00000000 00:00 0 
02a44000-02c00000 rw-p 00000000 00:00 0                                  [heap]
40d41000-41321000 rwxp 00000000 00:00 0 
41e5c000-41e6c000 rwxp 00000000 00:00 0 
7fb9f8000000-7fb9f8021000 rw-p 00000000 00:00 0 
7fb9f8021000-7fb9fc000000 ---p 00000000 00:00 0 
7fba00000000-7fba00725000 rw-p 00000000 00:00 0 
7fba00725000-7fba04000000 ---p 00000000 00:00 0 
7fba04000000-7fba04021000 rw-p 00000000 00:00 0 
7fba04021000-7fba08000000 ---p 00000000 00:00 0 
7fba08000000-7fba08144000 rw-p 00000000 00:00 0 
7fba08144000-7fba0c000000 ---p 00000000 00:00 0 
7fba0cb00000-7fba0cc00000 rw-p 00000000 00:00 0 
7fba0cd00000-7fba0ce00000 rw-p 00000000 00:00 0 
7fba0cefb000-7fba0d20b000 rw-p 00000000 00:00 0 
7fba0d60b000-7fba0d70c000 rw-p 00000000 00:00 0 
7fba0d800000-7fba0d880000 rw-p 00000000 00:00 0 
7fba0d883000-7fba0da0b000 rw-p 00000000 00:00 0 
7fba0db0c000-7fba0db0d000 ---p 00000000 00:00 0 
7fba0db0d000-7fba0e30d000 rw-p 00000000 00:00 0 
7fba0e30d000-7fba0e30e000 ---p 00000000 00:00 0 
7fba0e30e000-7fba0eb0e000 rw-p 00000000 00:00 0 
7fba0eb0e000-7fba0edae000 r-xp 00000000 103:02 12584051                  /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.1/libmscordaccore.so

=================================================================
        Native stacktrace:
=================================================================
        0x4ba122 - /snap/rider/38/lib/ReSharperHost/linux-x64/mono/bin/mono-sgen : (null)
        0x4ba421 - /snap/rider/38/lib/ReSharperHost/linux-x64/mono/bin/mono-sgen : (null)
        0x467a49 - /snap/rider/38/lib/ReSharperHost/linux-x64/mono/bin/mono-sgen : (null)
        0x42ef82 - /snap/rider/38/lib/ReSharperHost/linux-x64/mono/bin/mono-sgen : (null)
        0x7fba72701890 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
        0x7fba5054a400 - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
* Assertion at mono-threads.c:638, condition `info' not met

Process finished with exit code 0.
```


Program on VPS fails with same message.

```
Started at 02/03/2020 06:24:05
Exiting at 02/03/2020 06:24:05
Started at 02/03/2020 06:24:10
Unhandled exception. System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromStream(Stream stream)
   at Domain.ImageComparison.CrawlerBitmap.DownloadImage(String fromUrl) in /builds/fjod/crawler/Domain/ImageComparison/CrawlerBitmap.cs:line 25
   at CuteDOS.Program.Main(String[] args) in /builds/fjod/crawler/DOS/CuteDOS/Program.cs:line 24
Aborted (core dumped)

```

**Comment by fjod** [comment]
definitely cookies problem. sorry guys ¯\_(ツ)_/¯
