### ISSUE TITLE
Win32Exception from `Process` class when running `dotnet test` on Windows ARM arch

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#2082]
On a machine with Windows IoT Core 1809 and .NET Core 3.1.101 installed:
1. Unzip [complexapp.zip](https://github.com/dotnet/runtime/files/4103678/complexapp.zip)
1. Run `dotnet build`
```
U:\complexapp>dotnet build -c release

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.101

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 15.87 sec for U:\complexapp\complexapp\complexapp.csproj.
  Restore completed in 15.81 sec for U:\complexapp\libbar\libbar.csproj.
  Restore completed in 15.81 sec for U:\complexapp\libfoo\libfoo.csproj.
  Restore completed in 1.31 min for U:\complexapp\tests\tests.csproj.
  libbar -> U:\complexapp\libbar\bin\Release\netstandard2.0\libbar.dll
  libfoo -> U:\complexapp\libfoo\bin\Release\netstandard2.0\libfoo.dll
  complexapp -> U:\complexapp\complexapp\bin\Release\netcoreapp3.1\complexapp.dll
  tests -> U:\complexapp\tests\bin\Release\netcoreapp3.1\tests.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:06.14
```

3. Run `dotnet test`
```
U:\complexapp>dotnet test --logger:trx
Test run for U:\complexapp\tests\bin\Debug\netcoreapp3.1\tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (This function is not supported on this system.)
 ---> System.ComponentModel.Win32Exception (120): This function is not supported on this system.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String ar   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String ar   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.<>c__DisplayClass36_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
Test run in progress.Results File: U:\complexapp\tests\TestResults\administrator_ddvsohumw038_2020-01-23_06_02_31.trx   

Test Run Aborted.
```

The above steps produce the following exception: `System.ComponentModel.Win32Exception (120): This function is not supported on this system.`

A different exception, but similar callstack, will occur if you execute this from within a Docker container with the Dockerfile contained in the zip file: `System.ComponentModel.Win32Exception (298): Too many posts were made to a semaphore.`
```
Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (Too many posts were made to a semaphore.)
 ---> System.ComponentModel.Win32Exception (298): Too many posts were made to a semaphore.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.<>c__DisplayClass36_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
```

**Comment by wfurt** [comment]
cc: @janvorli

**Comment by danmosemsft** [comment]
Apparently coming from CreateProcess

@mthalman is this important for 5.0 do you think?

**Comment by mthalman** [comment]
> Apparently coming from CreateProcess
> 
> @mthalman Matt Thalman FTE is this important for 5.0 do you think?

@richlander - Do you have an opinion on this?

**Comment by adamsitnik** [comment]
@richlander ping

**Comment by danmosemsft** [comment]
@mthalman given https://github.com/dotnet/dotnet-docker/issues/1840 I am going to close this. Please reopen if there is evidence it occurs in supported scenarios.
