### ISSUE TITLE
Linux certificate detection with HttpClient

### ISSUE THREAD

**Issue by ealsur** [dotnet/runtime#2122]
I have a client application (netcoreapp3.0, console) running on Linux (tested in Ubuntu and also Docker Linux with image `mcr.microsoft.com/dotnet/core/sdk:3.1`) and a service running on Windows.

The service running on Windows exposes connection points and uses a Self-Signed certificate which exists in CurrentUser/Personal and a respective CA in CurrentUser/Trusted Root CA.

The Certificate has a Subject Alternative Name for localhost and the Windows machine network IP.

Based on many other Issues, what I did was:

1. Export the PFX from the service machine
2. Take that PFX and, programmatically using `X509Store` save that certificate as part of the app initialization like so:

```
    using (var store = new X509Store(StoreName.My, StoreLocation.CurrentUser, OpenFlags.ReadWrite))
    {
        var cert = new X509Certificate2("mycert.pfx", "the-key", X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.Exportable | X509KeyStorageFlags.PersistKeySet);
        store.Add(cert);
    }

   /* code for the app /*
```

And I can verify that the cert is there if I open the store and read the existing Certs.

But on runtime, I see this exception:

    Error: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
     ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
       at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
       at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)         at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)     at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)      at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
       at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)         at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)     at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)      at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Net.Security.SslStream.ThrowIfExceptional()
       at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
       at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
       at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
       at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
       at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
       at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
       at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)           at Microsoft.Azure.Cosmos.DocumentClient.HttpRequestMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

The NET Core application uses HttpClient to try and connect to the exposed endpoint. Running the app on another Windows after installing the PFX works as expected.

## Things I tried

1. Multiple and different combinations of `X509KeyStorageFlags`
2. Storing it in `StoreName.CertificateAuthority` also
3. Manually converting it to a PEM file, putting it on the `/etc/ssl/certs` and running `update-ca-certificates`
4. I know that I could modify the `HttpClient` to ignore invalid certificates but I'm trying to avoid that by injecting it somewhere that can be detected.

I'm sure I must be missing something that is particular for Linux, but I would expect HttpClient to search for certificates in the `X509Store`? Am I missing something?

**Comment by wfurt** [comment]
Do you have expected EKU in your certificate? Look for example at https://github.com/dotnet/aspnetcore/issues/7246
For Linux, you can try to connect with `openssl s_client`. .Net does not maintain separate trust so if OpenSSL will trust it, we .Net should trust it as well.

**Comment by ealsur** [comment]
Will test it! Thanks! I take any pointer or lead, I am basically trying any alternative that will pick up the cert and make it work without changing the HttpClient code.

**Comment by ealsur** [comment]
I checked and my cert does not have the Key Usage, which I guess is the issue, will investigate further

![image](https://user-images.githubusercontent.com/1633401/73081982-769c2480-3e7d-11ea-94a4-4f769ef55b81.png)

**Comment by ealsur** [comment]
Got it to work!

The key here was to Clone the PFX that I had, but add the `-KeyUsage CertSign, DigitalSignature, KeyEncipherment`

![image](https://user-images.githubusercontent.com/1633401/73199155-2c1ee000-40e9-11ea-9c8c-4208a14bf760.png)

The resulting certificated had the Key Usages.

I then created the CRT in Linux with:

`openssl pkcs12 -in MyPFX.pfx -clcerts -nokeys -out MyCert.crt`

Then copied the cert to `/usr/local/share/ca-certificates/` and ran `update-ca-certificates` and the dotnet core app in Linux could connect 😄

**Comment by wfurt** [comment]
good to know you got it workign. OpenSSL is just more picky about attributes so certificate working on Windows may not work on Linux. (That is also true for new macOS)
