### ISSUE TITLE
Http2_PendingSend_SendsReset test failing in CI

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#2131]
https://helix.dot.net/api/2019-06-17/jobs/cd21187c-48d5-439a-bcd6-7b022dfe2148/workitems/System.Net.Http.Functional.Tests/console
```
   System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PendingSend_SendsReset(waitForData: False) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(1678,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass59_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(83,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(111,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(71,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs(186,0): at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(1643,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset(Boolean waitForData)
```

I saw 22 failures in the last 30 days in Kusto. This test is marked as OuterLoop because it is using Task.Delay. But there is no real reason to be unreliable since it us using LoopbackServer.

**Comment by AriNuer** [comment]
same test failed 'System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PendingSend_SendsReset' has failed here runtime-libraries outerloop#20200301.1 

Details:
https://dev.azure.com/dnceng/public/_build/results?buildId=542108&view=ms.vss-test-web.build-test-results-tab&runId=17175548&resultId=102753&paneView=debug

```
Error message
Assert.Equal() Failure
Expected: 0
Actual: 1

Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass59_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1677
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 191
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset(Boolean waitForData) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1642
--- End of stack trace from previous location ---
```

**Comment by AriNuer** [comment]
Test `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PendingSend_SendsReset(waitForData: False)` failed again here [runtime-libraries outerloop:20200318.1](https://dev.azure.com/dnceng/public/_build/results?buildId=563484&view=results)
```
Error message:
Assert.Equal() Failure
Expected: 0
Actual: 1

Stack trace:
at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass59_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1677
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Int32 timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 191
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset(Boolean waitForData) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1642
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=563484&view=ms.vss-test-web.build-test-results-tab&runId=17734980&resultId=103182&paneView=debug

**Comment by AriNuer** [comment]
Test `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PendingSend_SendsReset` failed again here [runtime-libraries outerloop:20200330.1](https://dev.azure.com/dnceng/public/_build/results?buildId=579439&view=results)
**Error message:**
```
Assert.Equal() Failure
Expected: 0
Actual: 1
```
**Stack trace:**
```
 at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass59_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1677
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Http2Options http2Options, Int32 timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 196
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset(Boolean waitForData) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1642
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=579439&view=ms.vss-test-web.build-test-results-tab&runId=18211948&resultId=102663&paneView=debug

**Comment by v-haren** [comment]
also failed in job: [runtime-libraries outerloop 20200420.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=608143&view=ms.vss-test-web.build-test-results-tab&runId=19101870&resultId=102717&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PendingSend_SendsReset(waitForData: False)


Error message
~~~
Assert.Equal() Failure
Expected: 0
Actual: 1


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass59_0.<<Http2_PendingSend_SendsReset>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1677
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 71
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Http2Options http2Options, Int32 timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 196
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PendingSend_SendsReset(Boolean waitForData) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1642
--- End of stack trace from previous location ---
~~~
