### ISSUE TITLE
Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException test fails on macOS

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#21590]
```
System.Net.Tests.HttpResponseStreamTests.Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException(ignoreWriteExceptions: False) [FAIL]
10:29:33         Assert.Throws() Failure
10:29:33         Expected: typeof(System.Net.HttpListenerException)
10:29:33         Actual:   (No exception was thrown)
10:29:33         Stack Trace:
10:29:33            /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.HttpListener/tests/HttpResponseStreamTests.cs(453,0): at System.Net.Tests.HttpResponseStreamTests.<Write_HeadersToClosedConnectionSynchronously_ThrowsHttpListenerException>d__21.MoveNext()
10:29:33            --- End of stack trace from previous location where exception was thrown ---
10:29:33               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:29:33               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:29:33            --- End of stack trace from previous location where exception was thrown ---
10:29:33               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:29:33               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10:29:33            --- End of stack trace from previous location where exception was thrown ---
10:29:33               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
10:29:33               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by wfurt** [comment]
I tried it on macOS and I it seems to work now. But it is inheritently unreliable and disabled on Windows as well. I think it works on Linux only by good luck. 

The test closes client side and depends on "abortive" behavior. When the Close in WaitForSocketShutdown() is finished, there is no guarantee that the server actually processed the RST and that the socket in closed state. 
I tried to replace it with Shutdown() and see if I can detect server closely but that does not happen since the test is still holding the OutputStream. We would probably need some reflection and inner state knowledge to know the close was actually processed by the server. 

We _could_ add some arbitraty delay but that still seems problematic. 
Since I do not see path forward I'm suggesting to delete the test and close this issue. 
We could alternatively make it Linux specific and remove the ActivreIssues.

please cast your vote @stephentoub @geoffkizer 

I think  #21940 is on the same boat using exactly same strategy. I just don't see value keeping those old issues open.

**Comment by geoffkizer** [comment]
I vote delete

**Comment by stephentoub** [comment]
Sounds fine
