### ISSUE TITLE
Assertion failed 'localVarInterval->assignedReg->isCalleeSave'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#2181]
On Linux/arm64, JitStress=1 or JitStress=2, JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh fails with:

```
Assert failure(PID 14794 [0x000039ca], Thread: 14794 [0x39ca]): Assertion failed 'localVarInterval->assignedReg->isCalleeSave' in 'JIT.HardwareIntrinsics.General.VectorAs__AsDouble:RunGenericScenario():this' (IL size 345)

    File: /home/bruce/gh/runtime/src/coreclr/src/jit/lsra.cpp Line: 7109
    Image: /home/brucefo/build/runtime/artifacts/tests/coreclr/Linux.arm64.Checked/Tests/Core_Root/corerun
```

with:
```
export COMPlus_TieredCompilation=0
export COMPlus_JitStress=1
```

Example in CI:
https://dev.azure.com/dnceng/public/_build/results?buildId=496122&view=results

**Comment by BruceForstall** [comment]
cc @CarolEidt @tannergooding @echesakovMSFT

**Comment by tannergooding** [comment]
I was going to say this one is probably related to https://github.com/dotnet/runtime/pull/1280, but it looks like its been failing for a bit longer than that...

**Comment by BruceForstall** [comment]
Stack:
```
#2  0x0000007fb3a6ebd8 in assertAbort (why=0x7fb3df9b57 "localVarInterval->assignedReg->isCalleeSave", file=0x7fb3df7a98 "/home/bruce/gh/runtime/src/coreclr/src/jit/lsra.cpp", line=7109)
    at /home/bruce/gh/runtime/src/coreclr/src/jit/error.cpp:293
#3  0x0000007fb3b8ac08 in LinearScan::resolveRegisters (this=0x555583ffb8) at /home/bruce/gh/runtime/src/coreclr/src/jit/lsra.cpp:7109
#4  0x0000007fb3b870f4 in LinearScan::doLinearScan (this=0x555583ffb8) at /home/bruce/gh/runtime/src/coreclr/src/jit/lsra.cpp:1242
#5  0x0000007fb3a45920 in Compiler::compCompile (this=0x555566c1b8, methodCodePtr=0x7fffffbc88, methodCodeSize=0x7fffffc1c4, compileFlags=0x7fffffbca0)
    at /home/bruce/gh/runtime/src/coreclr/src/jit/compiler.cpp:4599
```

```
(gdb) p *localVarInterval
$1 = {<Referenceable> = {firstRefPosition = 0x5555847538, recentRefPosition = 0x555565ce98, lastRefPosition = 0x555565ddd0, isActive = true}, registerPreferences = 8589934592, relatedInterval = 0x0,
  assignedReg = 0x55558408c8, registerType = TYP_SIMD16, isLocalVar = true, isSplit = false, isSpilled = false, isInternal = false, isStructField = false, isPromotedStruct = false,
  hasConflictingDefUse = false, hasInterferingUses = false, isSpecialPutArg = false, preferCalleeSave = false, isConstant = false, isUpperVector = false, isPartiallySpilled = false, physReg = REG_V1,
  intervalIndex = 1, varNum = 1}
(gdb) p *(localVarInterval->assignedReg)
$2 = {<Referenceable> = {firstRefPosition = 0x5555844160, recentRefPosition = 0x555565c6a8, lastRefPosition = 0x555565e6e0, isActive = true}, assignedInterval = 0x5555842cd0, previousInterval = 0x0,
  regNum = REG_V1, isCalleeSave = false, registerType = TYP_FLOAT, isBusyUntilNextKill = false}
```
