### ISSUE TITLE
Assertion failed 'type == lvaTable[lnum].lvType || (lvaIsImplicitByRefLocal(lnum) && fgGlobalMorph && (lvaTable[lnum].lvType == TYP_BYREF))

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#2182]
On Linux/arm64, JitStress=1 or JitStress=2, these:

```
JIT/HardwareIntrinsics/X86/Sse2/Sse2_ro/Sse2_ro.sh
JIT/HardwareIntrinsics/X86/Avx2/Avx2_ro/Avx2_ro.sh
JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_ro/AdvSimd_ro.sh
JIT/HardwareIntrinsics/X86/Sse41/Sse41_ro/Sse41_ro.sh
JIT/HardwareIntrinsics/X86/Sse41_Overloaded/Sse41_Overloaded_ro/Sse41_Overloaded_ro.sh
JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/Avx2_ro.sh
JIT/HardwareIntrinsics/Arm/Aes/Aes_ro/Aes_ro.sh
JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_ro/AdvSimd.Arm64_ro.sh
JIT/HardwareIntrinsics/X86/Ssse3/Ssse3_ro/Ssse3_ro.sh
JIT/HardwareIntrinsics/X86/Sse2.X64/Sse2.X64_ro/Sse2.X64_ro.sh
JIT/HardwareIntrinsics/X86/Sse41.X64/Sse41.X64_ro/Sse41.X64_ro.sh
```

fail with:

```
Assert failure(PID 14783 [0x000039bf], Thread: 14783 [0x39bf]): Assertion failed 'type == lvaTable[lnum].lvType || (lvaIsImplicitByRefLocal(lnum) && fgGlobalMorph && (lvaTable[lnum].lvType == TYP_BYREF))
' in 'JIT.HardwareIntrinsics.X86.Program:ExtractInt64129()' (IL size 147)

    File: /home/bruce/gh/runtime/src/coreclr/src/jit/gentree.cpp Line: 6143
    Image: /home/brucefo/build/runtime/artifacts/tests/coreclr/Linux.arm64.Checked/Tests/Core_Root/corerun
```

with:
```
export COMPlus_TieredCompilation=0
export COMPlus_JitStress=1
```

Example in CI:
https://dev.azure.com/dnceng/public/_build/results?buildId=496122&view=results

**Comment by BruceForstall** [comment]
cc @CarolEidt @tannergooding @echesakovMSFT

**Comment by BruceForstall** [comment]
Looking at JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_ro/AdvSimd.Arm64_ro.sh:

`STRESS_CLONE_EXPR` is active.

stack at assert:
```
#2  0x0000007fb3a6ebd8 in assertAbort (why=0x7fb3dd2862 "type == lvaTable[lnum].lvType || (lvaIsImplicitByRefLocal(lnum) && fgGlobalMorph && (lvaTable[lnum].lvType == TYP_BYREF))",
    file=0x7fb3dd1e4d "/home/bruce/gh/runtime/src/coreclr/src/jit/gentree.cpp", line=6143) at /home/bruce/gh/runtime/src/coreclr/src/jit/error.cpp:293
#3  0x0000007fb3ac548c in Compiler::gtNewLclvNode (this=0x5555873ce8, lnum=215, type=TYP_SIMD16, ILoffs=16) at /home/bruce/gh/runtime/src/coreclr/src/jit/gentree.cpp:6142
#4  0x0000007fb3ac7da4 in Compiler::gtCloneExpr (this=0x5555873ce8, tree=0x5555978be8, addFlags=0, varNum=4294967295, varVal=0, deepVarNum=4294967295, deepVarVal=0)
    at /home/bruce/gh/runtime/src/coreclr/src/jit/gentree.cpp:7145
#5  0x0000007fb3ac8e10 in Compiler::gtCloneExpr (this=0x5555873ce8, tree=0x5555978cd8, addFlags=0, varNum=4294967295, varVal=0, deepVarNum=4294967295, deepVarVal=0)
    at /home/bruce/gh/runtime/src/coreclr/src/jit/gentree.cpp:7432
#6  0x0000007fb3a1c02c in Compiler::gtCloneExpr (this=0x5555873ce8, tree=0x5555978cd8, addFlags=0, varNum=4294967295, varVal=0) at /home/bruce/gh/runtime/src/coreclr/src/jit/compiler.h:2646
#7  0x0000007fb3bc9e4c in Compiler::fgMorphStmts (this=0x5555873ce8, block=0x55558757b0, lnot=0x7fffffadf7, loadw=0x7fffffadf6) at /home/bruce/gh/runtime/src/coreclr/src/jit/morph.cpp:15465
```

During import we have:
```
               [002042] I-C-G-------              *  CALL      struct TestStruct.Create (exactContextHnd=0x0000007F3E801BC1)

    [ 1]  15 (0x00f) stloc.0
lvaGrabTemp returning 215 (V215 tmp214) (a long lifetime temp) called for Inline stloc first use temp.


               [002046] -AC---------              *  ASG       simd16 (copy)
               [002044] D-----------              +--*  LCL_VAR   simd16<TestStruct> V215 tmp214
               [002043] --C---------              \--*  RET_EXPR  simd16(inl return from call [002042])
```

After inlining we have:
```
STMT00453 (IL 0x083...  ???)
               [002046] -AC---------              *  ASG       simd16 (copy)
               [002044] D-----------              +--*  LCL_VAR   simd16<TestStruct> V215 tmp214
               [002042] --C-G-------              \--*  CALL      simd16 TestStruct.Create

***** BB14
STMT00454 (IL 0x083...  ???)
               [002053] -A----------              *  ASG       simd16 (copy)
               [002051] D-----------              +--*  LCL_VAR   simd16<System.Runtime.Intrinsics.Vector128`1[Double]> V216 tmp215
               [002050] ------------              \--*  HWINTRINSIC simd16 double Abs
               [002049] ------------                 \--*  FIELD     simd16 _fld1
               [002048] ------------                    \--*  ADDR      byref
               [002047] ------------                       \--*  LCL_VAR   struct<TestStruct, 16> V215 tmp214
```

Note that V215 looks to be used with two different types:
```
[002044] D-----------              +--*  LCL_VAR   simd16<TestStruct> V215 tmp214
```
and
```
[002047] ------------                       \--*  LCL_VAR   struct<TestStruct, 16> V215 tmp214
```

Q: is that correct?

The assert happens because we try to clone `[002044]` which is type `simd16` but the local variable is `TYP_STRUCT`.

Is this an acceptable situation that the assert should allow?

**Comment by CarolEidt** [comment]
I'll have to look at the test case, but it may be fallout from the fact that an HVA (even with a single SIMD field) is passed & returned as SIMD16. This would then be kind of like the cases where we pass a register-sized struct "as if" it is a scalar type - but in this case the "scalar" is a SIMD16.
