### ISSUE TITLE
User defined table value type in Ado.net cause issue after upgrading to .net 3.1

### ISSUE THREAD

**Issue by Mrpankaj666** [dotnet/runtime#2207]
In .net core 2.2 its working fine but once I upgrade the project to .net core 3.1 its start failing only for user defined data type in ado
Error: Object must implement IConvertible
please assist on this

**Comment by jkotas** [comment]
Could you please share the stacktrace of the "Object must implement IConvertible" exception?

**Comment by Mrpankaj666** [comment]
`   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at projectd__20.MoveNext() in C:\path\StagingRecords.cs:line 295`

@jkotas here it is stack trace and inner exception is
{"Object must implement IConvertible."}

**Comment by Mrpankaj666** [comment]
@jkotas and the same issue with "FromSqlraw" method as well in Ef Core
but previously it was working with "fromsql" method

**Comment by Mrpankaj666** [comment]
@jkotas 
here is the same error has been discussed which is most probably fixed in .net standard 2.0 for dapper
https://github.com/dotnet/corefx/issues/19708#issue-228274758

**Comment by Mrpankaj666** [comment]
Closing this issue as it was namespace issue
https://github.com/dotnet/SqlClient/issues/323
