### ISSUE TITLE
GCExtendedTests.GetTotalAllocatedBytes failed on Mono on Ubuntu in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#2280]
https://dev.azure.com/dnceng/public/_build/results?buildId=494262&view=ms.vss-test-web.build-test-results-tab&runId=15733104&resultId=166198&paneView=debug
```
    System.Tests.GCExtendedTests.GetTotalAllocatedBytes [FAIL]
      System.Exception : Expected more memory to be allocated. previous = 3806405736, precise = 3789497944, difference = 16907792
      Stack Trace:
           at System.Tests.GCExtendedTests.<GetTotalAllocatedBytes>g__CallGetTotalAllocatedBytesAndCheck|23_0(Int64 previous, Int64& differenceBetweenPreciseAndImprecise)
           at System.Tests.GCExtendedTests.<GetTotalAllocatedBytes>g__CallGetTotalAllocatedBytes|23_1(Int64 previous, <>c__DisplayClass23_0& )
           at System.Tests.GCExtendedTests.GetTotalAllocatedBytes()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
cc: @akoeplinger

**Comment by akoeplinger** [comment]
@BrzVlad can you please take a look at whether this test makes sense on Mono's sgen? https://github.com/dotnet/runtime/blob/2645da670164c4a2e3acd662ff23888f217d135f/src/libraries/System.Runtime/tests/System/GCTests.cs#L847

**Comment by BrzVlad** [comment]
We added this API just recently. It's not clear why it fails this way, it should work. @naricc can you take a look ?

**Comment by naricc** [comment]
Yes, I am looking into it. First thought; is this just failing because mono and the dotnet-core runtime use diffirent object layouts and thus allocate different amounts of memory? The difference is like .4 %

**Comment by BrzVlad** [comment]
This has nothing to do with coreclr. According to the failure, this counter is not monotonic on mono.

**Comment by naricc** [comment]
Ah, I see.... We only ever add to the counter, so maybe it is a synchronization error where two threads are clobbering the value. Except the test itself looks single threaded?

Any way, looking into it.

**Comment by BrzVlad** [comment]
Also the test expects the precise value to be lower than the imprecise value, for whatever reason. I'm not sure we guarantee this, or if we do, we do it by accident. Maybe also double check there if we can have same behavior.

**Comment by naricc** [comment]
So I am a bit confused due to the repo move and all; how do I actually run this test locally?

**Comment by akoeplinger** [comment]
You can follow https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/mono/testing.md and then run the tests in src/libraries/System.Runtime/tests

**Comment by danmosemsft** [comment]
Failed again in CI
https://github.com/dotnet/runtime/pull/32288/checks?check_run_id=468133057
```
{ "HelixJobId": "a721cc95-8b86-4783-9b93-3331666ea4d1", "HelixWorkItemName": "System.Runtime.Tests" }


Error message
System.Exception : Expected more memory to be allocated. previous = 2928940008, precise = 2910475664, difference = 18464344


Stack trace
   at System.Tests.GCExtendedTests.<GetTotalAllocatedBytes>g__CallGetTotalAllocatedBytesAndCheck|23_0(Int64 previous, Int64& differenceBetweenPreciseAndImprecise) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 875
   at System.Tests.GCExtendedTests.<GetTotalAllocatedBytes>g__CallGetTotalAllocatedBytes|23_1(Int64 previous, <>c__DisplayClass23_0& ) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 880
   at System.Tests.GCExtendedTests.GetTotalAllocatedBytes() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 891
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
```

**Comment by jkotas** [comment]
Hit in https://github.com/dotnet/runtime/pull/33028 on netcoreapp5.0-Linux-Debug-arm64-Mono_release. If you are not actively working on this, disable the test on Mono against this issue to keep the CI clean.

**Comment by Jozkee** [comment]
Another hit here: https://github.com/dotnet/runtime/pull/32909/checks?check_run_id=473576884

**Comment by naricc** [comment]
I will disable the test this afternoon, if I can't figure it out immediately.

**Comment by naricc** [comment]
Resolve by this change: https://github.com/dotnet/runtime/pull/42388
