### ISSUE TITLE
Test flakiness: HostActivation.NativeHosting.Comhost.ActivateClass

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#2320]
It looks like the output is truncated--a crash?

https://dev.azure.com/dnceng/internal/_build/results?buildId=396505&view=ms.vss-test-web.build-test-results-tab&runId=12373480&resultId=101463&paneView=debug

win-x64 Debug, `master`

```
Expected command to pass but it did not.\"
File Name: F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\nativeHosting\\0\\nativehost.exe
Arguments: comhost synchronous 10 F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.comhost.dll {438968CE-5950-4FBC-90B0-E64691350DF5}
Exit Code: -1073741819
StdOut:
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 1 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 2 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 3 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 4 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 5 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 6 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 7 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 8 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 9 of 10
New instance of Server created
Activation of {438968CE-5950-4FBC-90B0-E64691350DF5} succeeded. 10 of 10

StdErr:
Tracing enabled @ Tue Oct 22 22:12:57 2019 GMT
Using environment variable DOTNET_ROOT=[F:\\workspace\\_work\\1\\s\\artifacts\\obj\\win-x64.Debug\\sharedFrameworkPublish] as runtime location.
Reading fx resolver directory=[F:\\workspace\\_work\\1\\s\\artifacts\\obj\\win-x64.Debug\\sharedFrameworkPublish\\host\\fxr]
Considering fxr version=[5.0.0-alpha1.19522.10]...
Detected latest fxr version=[F:\\workspace\\_work\\1\\s\\artifacts\\obj\\win-x64.Debug\\sharedFrameworkPublish\\host\\fxr\\5.0.0-alpha1.19522.10]...
Resolved fxr [F:\\workspace\\_work\\1\\s\\artifacts\\obj\\win-x64.Debug\\sharedFrameworkPublish\\host\\fxr\\5.0.0-alpha1.19522.10\\hostfxr.dll]...
Loaded library from F:\\workspace\\_work\\1\\s\\artifacts\\obj\\win-x64.Debug\\sharedFrameworkPublish\\host\\fxr\\5.0.0-alpha1.19522.10\\hostfxr.dll
Tracing enabled @ Tue Oct 22 22:12:57 2019 GMT
--- Invoked hostfxr_initialize_for_runtime_config [commit hash: c1f5f8106b800c35d1b112cff11e3c79bac0170a]
Specified runtimeconfig.json from [F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.runtimeconfig.json]
Runtime config is cfg=F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.runtimeconfig.json dev=F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.runtimeconfig.dev.json
Attempting to read runtime config: F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.runtimeconfig.json
Attempting to read dev runtime config: F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.runtimeconfig.dev.json
Runtime config [F:\\workspace\\_work\\1\\s\\artifacts\\tests\\Debug\\ha\\0\\ComLibrary\\bin\\ComLibrary.runtimeconfig.json] is valid=[1]
--- The specified framework 'Microsoft.NETCore.App', version '5.0.0-alpha1.19522.10', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '5.0.0-alpha1.19522.10'.
--- Resolving FX directory, name 'Microsoft.NETCore.App' version '5.0.0-alpha1.19522.10'
Searching FX directory in [F:\\workspace\\_work\\1\\s\\artifacts\\obj\\win-x64.Debug\\sharedFrameworkPublish]
Attempting FX roll forward starting from version='[5.0.0-alpha1.19522.10]', apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, prefer_release=0
'Roll forward' enabl
```

```
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in /_/src/test/TestUtils/Assertions/CommandResultAssertions.cs:line 31
at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.Comhost.ActivateClass(Int32 count, Boolean synchronous) in /_/src/test/HostActivation.Tests/NativeHosting/Comhost.cs:line 44
```

Seen initially in PR validation for https://github.com/dotnet/core-setup/pull/8641, but the above is an exact repro from an official build.

It's interesting that the truncation is the same for both: `'Roll forward' enabl` is the last line.

@vitek-karas @elinor-fung

**Comment by jkotas** [comment]
Hit in https://github.com/dotnet/runtime/pull/31705
