### ISSUE TITLE
[mono] System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_InvalidFlags_ThrowsArgumentException fails

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#2337]
0. Make sure that you have the [libgdiplus ]( https://docs.microsoft.com/dotnet/core/install/dependencies?pivots=os-macos&tabs=netcore31#libgdiplus) dependency installed.
1. `./build.sh /p:RuntimeFlavor=mono`
2.  `cd src/libraries/System.Drawing.Common/tests`
3. `dotnet msbuild /t:BuildAndTest /p:RuntimeFlavor=mono`

Actual:
```
      System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_InvalidFlags_ThrowsArgumentException(flag: -1) [FAIL]
        System.ArgumentException : Arg_ObjObjEx
        Stack Trace:
             at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
             at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
          --- End of stack trace from previous location ---
      System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_InvalidFlags_ThrowsArgumentException(flag: Count) [FAIL]
        System.ArgumentException : Arg_ObjObjEx
        Stack Trace:
             at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
             at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
      System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_InvalidFlags_ThrowsArgumentException(flag: Any) [FAIL]
          --- End of stack trace from previous location ---
      System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_InvalidFlags_ThrowsArgumentException(flag: 7) [FAIL]
        System.ArgumentException : Arg_ObjObjEx
        Stack Trace:
             at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
             at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
          --- End of stack trace from previous location ---
        System.ArgumentException : Arg_ObjObjEx
        Stack Trace:
             at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.ConvertValues(Binder binder, Object[] args, ParameterInfo[] pinfo, CultureInfo culture, BindingFlags invokeAttr)
             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
             at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
          --- End of stack trace from previous location ---

```

Expected:
`System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_InvalidFlags_ThrowsArgumentException` test passes

OS: MacOS 
master (5fca04171171f118bca0f93aa9741f205b8cdc29)

**Comment by JeremyKuhne** [comment]
System.Drawing.Common has moved to WinForms and no longer supports platforms other than Windows.
