### ISSUE TITLE
FreeBSD: System.Drawing.Printing tests are failing

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#23786]
=== TEST EXECUTION SUMMARY ===
   System.Drawing.Common.Tests  Total: 1731, Errors: 0, Failed: 31, Skipped: 1327, Time: 1.415s
~/git/corefx/bin/tests/System.Drawing.Common.Tests/netcoreapp-FreeBSD-Debug-x64
 
     ---- System.TypeInitializationException : The type initializer for 'System.Drawing.Printing.LibcupsNative' threw an exception.
      -------- System.DllNotFoundException : Unable to load DLL 'libdl': The specified module or one of its dependencies could not be found.
       (Exception from HRESULT: 0x8007007E)
      Stack Trace:
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs(88,0): at System.Drawing.Printing.PrintingServices.get_DefaultPrinter()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.Unix.cs(70,0): at System.Drawing.Printing.PrinterSettings..ctor()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/tests/Printing/PrinterSettingsTests.cs(224,0): at System.Drawing.Printing.Tests.PrinterSettingsTests.MaximumPage_SetValue_ReturnsExpected(Int32 maximumPage)
         ----- Inner Stack Trace -----
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs(44,0): at System.Drawing.Printing.LibcupsNative.cupsGetDefault()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs(107,0): at System.Drawing.Printing.PrintingServices.CheckCupsInstalled()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/PrintingServices.Unix.cs(64,0): at System.Drawing.Printing.PrintingServices..cctor()
         ----- Inner Stack Trace -----
            at Interop.Libdl.dlopen(String fileName, Int32 flag)
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs(17,0): at System.Drawing.Printing.LibcupsNative.LoadLibcups()
         /home/furt/git/wfurt2-corefx/src/System.Drawing.Common/src/System/Drawing/Printing/LibcupsNative.cs(12,0): at System.Drawing.Printing.LibcupsNative..cctor()

This is because FreeBSD has dlopen in libc instead of libdl. 
This may be simple as updating src/Common/src/Interop/Unix/Interop.Libraries.cs
libcups.so seems to exit but no testing has been done.

This is part of https://github.com/dotnet/corefx/issues/1626

**Comment by wfurt** [comment]
seems no longer applicable.
