### ISSUE TITLE
IconCodecTest.Bitmap16Pixels failed on netfx in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#24267]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/5682/consoleText
```
MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap16Pixels [FAIL]
        System.ArgumentException : Parameter is not valid.
        Stack Trace:
             at System.Drawing.Bitmap..ctor(String filename)
             at MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap16Pixels()
```

**Comment by safern** [comment]
It seems like this hasn't failed in 120 days per my Kusto query.
