### ISSUE TITLE
When a DispatchProxy nested class is not public it throws TypeLoadException: Access is denied

### ISSUE THREAD

**Issue by Mutuduxf** [dotnet/runtime#25595]
The repo is [here](https://github.com/Mutuduxf/DispatchProxyDemo)
```
System.TypeLoadException: Access is denied: 'DynamicProxy+InvokeProxy`1[IService]'.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at System.Reflection.DispatchProxyGenerator.ProxyBuilder.CreateType()
   at System.Reflection.DispatchProxyGenerator.GenerateProxyType(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxyGenerator.GetProxyType(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType)
   at System.Reflection.DispatchProxy.Create[T,TProxy]()
   at DispatchProxyDemo.DynamicProxy.Proxy[T]() in C:\Users\aeond\Desktop\GitHub\DispatchProxyDemo\DispatchProxyDemo\DynamicProxy.cs:line 9
   at DispatchProxyDemo.Program.Main(String[] args) in C:\Users\aeond\Desktop\GitHub\DispatchProxyDemo\DispatchProxyDemo\Program.cs:line 11
```

[EDIT] Format exception + add exception line by @karelz

**Comment by GrabYourPitchforks** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/30917, which is a more generalized work item tracking whether we need `DispatchProxy` to behave better with internal base classes or internal interfaces.
