### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest / ProxyAuth_Digest_Succeeds

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#25705]
https://github.com/dotnet/corefx/pull/28643#issuecomment-377766657
```
Windows.10.Amd64.Open-x86-Release

ProxyAuth_Digest_Succeeds
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest

Unhandled Exception of Type System.TimeoutException
Message :
System.TimeoutException : WhenAllOrAnyFailed timed out after 60000
Stack Trace :
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 53
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass114_0.<<ProxyAuth_Digest_Succeeds>b__0>d.MoveNext() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 3014
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in D:\j\workspace\windows-TGrou---f8ac6754\src\Common\tests\System\Net\Http\LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.ProxyAuth_Digest_Succeeds() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 3000
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by karelz** [comment]
No failures during 2/23-5/11 (incl. PRs). Closing.
