### ISSUE TITLE
 The dynamic type created is thrown Fileloadexception when using the GetCustomAttributes method

### ISSUE THREAD

**Issue by joshfree** [dotnet/runtime#26912]
Original issue https://github.com/dotnet/core/issues/1481

**_@faib920 commented on Apr 26_**
I Use TypeBuilder create a testclass, and use SetCustomAttributes to add custom attribute, then I use the method of GetCustomAttributes, throw FileLoadFileException.

FileLoadException:
Could not load file or assembly '_testclass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Operation is not supported. (Exception from HRESULT: 0x80131515)

inner Exception
System.NotSupportedException
Resolving to a collectible assembly is not supported.

StackTrace:
```
at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
```

**_@evo01 commented 14 days ago_**
I did some more testing around this issue and the temporary work around seems to be to not use named arguments.  If you leave the named arguments off, and use the following property instead, you can custom attributes in a dynamic type.

```
[Custom1("Howdy", new []{ EnumTesting_BasicEnum_Int16 .One})] 
public class ClassTesting_ClassWithBlankAttribute
{
}
```

`var attributes = dynamicType.CustomAttributes.ToList(); // WORKS`
			
`Assert.AreEqual(1, attributes.Count); // WORKS`

This does not work:

```
[Custom1("Howdy", new []{ EnumTesting_BasicEnum_Int16 .One}, MyField1 = new[] { EnumTesting_BasicEnum_Int16.One }, MyField2 = typeof(Custom1Attribute), MyProperty1 =1)]
public class ClassTesting_ClassWithBlankAttribute
{
}
```

**Comment by steveharter** [comment]
I was unable to repro this on .NET 5.0 or .NET 4.7.2.

@faib920 can you provide a repro please?

Attempted repro:
```cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;

namespace ConsoleApp26
{
    [AttributeUsage(AttributeTargets.All, AllowMultiple = false)]
    public class IntPropertyAttribute : Attribute
    {
        public int Value;
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Type returnType = typeof(int);
            Type[] ctorParamTypes = new Type[] { typeof(int) };

            FieldInfo fieldInfo = typeof(IntPropertyAttribute).GetField("Value");

            int expectedValue = 10;
            object[] propertyValues = new object[] { expectedValue };
            FieldInfo[] fieldInfos = new FieldInfo[] { fieldInfo };
            CustomAttributeBuilder customAttrBuilder = new CustomAttributeBuilder(
                typeof(IntPropertyAttribute).GetConstructor(new Type[] { }), new object[] { },
                fieldInfos, propertyValues);

            TypeBuilder type = Helpers.DynamicType(TypeAttributes.Class | TypeAttributes.Public);

            PropertyBuilder property = type.DefineProperty("TestProperty", PropertyAttributes.HasDefault, returnType, null);
            property.SetCustomAttribute(customAttrBuilder);

            MethodAttributes getMethodAttributes = MethodAttributes.Public | MethodAttributes.SpecialName | MethodAttributes.HideBySig;
            MethodBuilder method = type.DefineMethod("TestMethod", getMethodAttributes, returnType, new Type[0]);

            ILGenerator methodILGenerator = method.GetILGenerator();
            methodILGenerator.Emit(OpCodes.Ldarg_0);
            methodILGenerator.Emit(OpCodes.Ret);

            property.SetGetMethod(method);

            BindingFlags bindingFlags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Static;
            Type createdType = type.CreateTypeInfo().AsType();
            PropertyInfo createdProperty = createdType.GetProperty("TestProperty", bindingFlags);
            object[] attributes = createdProperty.GetCustomAttributes(false).ToArray();

            Debug.Assert(1 == attributes.Length);
            Debug.Assert(attributes[0] is IntPropertyAttribute);
            Debug.Assert(expectedValue == (attributes[0] as IntPropertyAttribute).Value);
        }

        public static class Helpers
        {
            public const BindingFlags AllFlags = BindingFlags.Static | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;

            public static AssemblyBuilder DynamicAssembly(string name = "TestAssembly", AssemblyBuilderAccess access = AssemblyBuilderAccess.Run)
            {
                AssemblyName assemblyName = new AssemblyName(name);
                return AssemblyBuilder.DefineDynamicAssembly(assemblyName, access);
            }

            public static ModuleBuilder DynamicModule(string assemblyName = "TestAssembly", string moduleName = "TestModule")
            {
                return DynamicAssembly(assemblyName).DefineDynamicModule(moduleName);
            }

            public static TypeBuilder DynamicType(TypeAttributes attributes, string assemblyName = "TestAssembly", string moduleName = "TestModule", string typeName = "TestType")
            {
                return DynamicModule(assemblyName, moduleName).DefineType(typeName, attributes);
            }

            public static EnumBuilder DynamicEnum(TypeAttributes visibility, Type underlyingType, string enumName = "TestEnum", string assemblyName = "TestAssembly", string moduleName = "TestModule")
            {
                return DynamicModule(assemblyName, moduleName).DefineEnum(enumName, visibility, underlyingType);
            }
        }
    }
}
```

**Comment by steveharter** [comment]
Closing; unable to repro.

Please re-open if we can a repro or additional information on how to repro.
