### ISSUE TITLE
[arm32/Windows] System.Console.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28138]
Running the arm32 tests on windows for System.Console.Tests produced the following results: passed 126/127 tests.

The test that failed was ReadAndWrite.OutputEncodingPreamble and it failed with the following IOException:
```
System.IO.IOException : The parameter is incorrect.
   at System.ConsolePal.SetConsoleOutputEncoding(Encoding enc) in F:\git\corefx\src\System.Console\src\System\ConsolePal.Windows.cs:line 120
   at System.Console.set_OutputEncoding(Encoding value) in F:\git\corefx\src\System.Console\src\System\Console.cs:line 68
   at ReadAndWrite.OutputEncodingPreamble() in F:\git\corefx\src\System.Console\tests\ReadAndWrite.cs:line 281
```

**Comment by carlossanlop** [comment]
Similar to https://github.com/dotnet/runtime/issues/25466
That test used to fail in windows.10.amd64.iot-x64. This test failed in arm32, but looking at the history, is not failing anymore.
Closing. Feel free to reopen if it starts failing again.

**Comment by joperezr** [comment]
Are we running the test though? Lets double check the test is running in arm32 runs and its passing there.
