### ISSUE TITLE
[arm32/Windows] System.Resources.ResourceManager.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28137]
Running the arm32 tests on windows for System.Resources.ResourceManager.Tests produced the following results: passed 94/96 tests.

Both failures had the same message:
```
System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.\r\n---- System.DllNotFoundException : Unable to load DLL 'gdiplus.dll': The specified module could not be found.
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromFile(String filename, IntPtr& bitmap) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.cs:line 1781
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs:line 41
   at System.Drawing.Bitmap..ctor(String filename) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Bitmap.cs:line 24
   at System.Resources.Tests.ResourceManagerTests.EnglishImageResourceData()+MoveNext() in F:\git\corefx\src\System.Resources.ResourceManager\tests\ResourceManagerTests.cs:line 266
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in F:\git\corefx\src\System.Linq\src\System\Linq\Select.cs:line 135
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate() in F:\git\corefx\src\Common\src\System\Runtime\InteropServices\FunctionWrapper.cs:line 37
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output) in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\GdiplusNative.Windows.cs:line 241
   at System.Drawing.SafeNativeMethods.Gdip..cctor() in F:\git\corefx\src\System.Drawing.Common\src\System\Drawing\Gdiplus.cs:line 85
```

If somebody can provide instructions on how to install Gdip on WIndows IoT Core I'm happy to install the dependency and re run the tests.

**Comment by jkotas** [comment]
Windows Arm32 is no longer supported.
