### ISSUE TITLE
[arm32/Windows] System.Data.SqlClient.Tests failures on arm32 windows 

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28148]
Running the arm32 tests on windows for System.Data.SqlClient.Tests produced the following results: passed 142/180 tests.

Most of the 38 failed tests fail with the following exception:
```
Assert.Throws() Failure\r\nExpected: typeof(System.Data.SqlClient.SqlException)\r\nActual:   typeof(System.TypeInitializationException): The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.\r\n---- System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.\r\n-------- System.TypeInitializationException : The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception.\r\n------------ System.DllNotFoundException : Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.TdsParser..ctor(Boolean MARS, Boolean fAsynchronous) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParser.cs:line 56
   at System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 1331
   at System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 1225
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1622
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1130
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs:line 384
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnectionFactory.cs:line 135
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 96
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 140
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 325
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs:line 1050
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs:line 151
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs:line 325
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 37
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 1190
   at System.Data.SqlClient.SqlConnection.Open() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 757
   at System.Data.SqlClient.Tests.SqlErrorCollectionTest.CreateCollection() in F:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\SqlErrorCollectionTest.cs:line 143
   at System.Data.SqlClient.Tests.SqlErrorCollectionTest.GetEnumerator_Success() in F:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\SqlErrorCollectionTest.cs:line 106
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions) in F:\git\corefx\src\Common\src\System\Data\ProviderBase\DbConnectionClosed.cs:line 37
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry) in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 1190
   at System.Data.SqlClient.SqlConnection.Open() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs:line 757
   at System.Data.SqlClient.Tests.ExceptionTest.<>c__DisplayClass9_0.<NamedPipeTest>b__0() in F:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs:line 98
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Data.SqlClient.TdsParserStateObjectFactory.get_EncryptionOptions() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserStateObjectFactory.Windows.cs:line 28
   at System.Data.SqlClient.TdsParser..cctor() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParser.cs:line 69
----- Inner Stack Trace -----
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize() in F:\git\corefx\src\System.Data.SqlClient\src\Interop\SNINativeMethodWrapper.Windows.cs:line 288
   at System.Data.SqlClient.SNILoadHandle..ctor() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserSafeHandles.cs:line 35
   at System.Data.SqlClient.SNILoadHandle..cctor() in F:\git\corefx\src\System.Data.SqlClient\src\System\Data\SqlClient\TdsParserSafeHandles.cs:line 19
```

[testResults.zip](https://github.com/dotnet/corefx/files/2669833/testResults.zip)

**Comment by jkotas** [comment]
Tracked by https://github.com/dotnet/SqlClient/issues/117
