### ISSUE TITLE
[arm32/Windows] System.IO.MemoryMappedFiles.Tests failures on arm32 windows

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#28166]
Running the arm32 tests on windows for System.IO.MemoryMappedFiles.Tests produced the following results: passed 599/839 tests.

Most of the 240 test failures have the same error:
```
System.IO.IOException : Cannot create a file when that file already exists.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity) in F:\git\corefx\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedFile.Windows.cs:line 45
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability) in F:\git\corefx\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedFile.cs:line 309
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity) in F:\git\corefx\src\System.IO.MemoryMappedFiles\src\System\IO\MemoryMappedFiles\MemoryMappedFile.cs:line 262
   at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_OpenExisting.OpenCreatedNew(String mapName, MemoryMappedFileRights desiredAccessRights, HandleInheritability inheritability) in F:\git\corefx\src\System.IO.MemoryMappedFiles\tests\MemoryMappedFile.OpenExisting.Tests.cs:line 82
```

[testResults.zip](https://github.com/dotnet/corefx/files/2673266/testResults.zip)

**Comment by QueueAmI** [comment]
I'm having the same problem in some C# code that I've written. I make a call to OpenExisting to see if the file already exists. I catch the FileNotFoundException and attempt a CreateNew. I tried switching CreateNew to CreateOrOpen and I get the same error. This occurs randomly, not every instance. I'm thinking it's some sort of race condition on some internal resource that hasn't quite released yet.

**Comment by jkotas** [comment]
Windows Arm32 is no longer supported.
