### ISSUE TITLE
FormatDescription EventLog test frequently failing

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#28403]
This test continues to fail frequently in CI, e.g.
https://mc.dot.net/#/user/Dotnet-GitSync-Bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/9d279bc3edfc20ee52b91d07b457e2954d08070a/workItem/System.Diagnostics.EventLog.Tests/analysis/xunit/System.Diagnostics.Tests.EventLogRecordTests~2FFormatDescription(log:%20%5C%22Application%5C%22)
```
Unhandled Exception of Type System.Diagnostics.Eventing.Reader.EventLogNotFoundException
Message :
System.Diagnostics.Eventing.Reader.EventLogNotFoundException : El sistema no puede encontrar el archivo especificado.
Stack Trace :
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\EventLogException.cs:line 24
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName, EventLogSession session, CultureInfo targetCultureInfo, String logFilePath) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\ProviderMetadata.cs:line 73
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName, EventLogSession session, CultureInfo targetCultureInfo) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\ProviderMetadata.cs:line 53
   at System.Diagnostics.Eventing.Reader.ProviderMetadataCachedInformation.GetProviderMetadata(ProviderMetadataId key) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\ProviderMetadataCachedInformation.cs:line 144
   at System.Diagnostics.Eventing.Reader.ProviderMetadataCachedInformation.GetFormatDescription(String ProviderName, EventLogHandle eventHandle, String[] values) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\ProviderMetadataCachedInformation.cs:line 203
   at System.Diagnostics.Eventing.Reader.EventLogRecord.FormatDescription(IEnumerable`1 values) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\src\System\Diagnostics\Reader\EventLogRecord.cs:line 306
   at System.Diagnostics.Tests.EventLogRecordTests.FormatDescription(String log) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.Diagnostics.EventLog\tests\System\Diagnostics\Reader\EventLogRecordTests.cs:line 47
```
cc: @danmosemsft, @maryamariyan

**Comment by Anipik** [comment]
@maryamariyan can you take a look at this https://github.com/dotnet/runtime/issues/28403

**Comment by maryamariyan** [comment]
Looking..

**Comment by danmosemsft** [comment]
This was 18 months ago - I believe we added retries in many of these tests since then. If that's the cas,e maybe next action is to switch it on, with the retries, and see how it goes.

**Comment by tommcdon** [comment]
@Anipik any objections if we move this to the .NET 6 milestone?
