### ISSUE TITLE
EndPrint_SetValue_ReturnsExpected failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#28454]
```
Unhandled Exception of Type System.Drawing.Printing.InvalidPrinterException
Message :
System.Drawing.Printing.InvalidPrinterException : No printers are installed.
Stack Trace :
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 881
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 872
   at System.Drawing.Printing.PageSettings.get_ExtraBytes() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 384
   at System.Drawing.Printing.PageSettings.CopyToHdevmode(IntPtr hdevmode) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PageSettings.Windows.cs:line 368
   at System.Drawing.Printing.PrinterSettings.GetHdevmode(PageSettings pageSettings) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrinterSettings.Windows.cs:line 955
   at System.Drawing.Printing.PrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 275
   at System.Drawing.Printing.Tests.PrintDocumentTests.TestPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e) in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 274
   at System.Drawing.Printing.PrintController.Print(PrintDocument document) in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintController.Windows.cs:line 116
   at System.Drawing.Printing.PrintDocument.Print() in D:\a\1\s\src\System.Drawing.Common\src\System\Drawing\Printing\PrintDocument.Windows.cs:line 270
   at System.Drawing.Printing.Tests.PrintDocumentTests.EndPrint_SetValue_ReturnsExpected() in D:\a\1\s\src\System.Drawing.Common\tests\Printing\PrintDocumentTests.cs:line 187
```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F34660~2Fmerge/test~2Ffunctional~2Fcli~2F/20190118.1/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Printing.Tests.PrintDocumentTests~2FEndPrint_SetValue_ReturnsExpected

**Comment by safern** [comment]
Dupe of: https://github.com/dotnet/runtime/issues/26428
