### ISSUE TITLE
Test Failure: System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#29383]
Test **System.Diagnostics.Tests.ProcessTests/LongProcessNamesAreSupported** has failed.

Message :
```
Assert.Contains() Failure
Not found: (filter expression)
In value:  Process[] [System.Diagnostics.Process (sh), System.Diagnostics.Process (sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet)]
```
Stack Trace :
```
at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /__w/1/s/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 1883
```

Details:
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190425.7/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FLongProcessNamesAreSupported

**Comment by Anipik** [comment]
Failed again here https://dev.azure.com/dnceng/public/_build/results?buildId=982443&view=logs&j=b9b7de4d-2126-5581-6453-1576f9aaac5f&t=db048d48-40e8-5399-9b14-d587763f33ff

log https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-f42ca9b897964959b9/System.Diagnostics.Process.Tests/console.006564c7.log?sv=2019-07-07&se=2021-02-27T14%3A16%3A51Z&sr=c&sp=rl&sig=NdWxmCLpMC65XXifBPdBuJjlZWau5zODq1eSLz3DZNQ%3D

```
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 246 of 304 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 2)
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Linux
Linux
Linux
Linux
None of the following programs were installed on this machine: xdg-open,gnome-open,kfmclient.
    System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"
    System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported [FAIL]
      Assert.Contains() Failure
      Not found: (filter expression)
      In value:  Process[] [System.Diagnostics.Process (helix_docker_work.sh), System.Diagnostics.Process (execute.sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet), System.Diagnostics.Process (123456789012345)]
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(2067,0): at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported()
  Finished:    System.Diagnostics.Process.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.Process.Tests  Total: 307, Errors: 0, Failed: 1, Skipped: 2, Time: 10.385s
/root/helix/work/workitem
```

**Comment by ericstj** [comment]
Failed again in https://github.com/dotnet/runtime/pull/89196
```
    System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported [FAIL]
      Assert.Contains() Failure
      Not found: (filter expression)
      In value:  Process[] [System.Diagnostics.Process (helix_docker_work.sh), System.Diagnostics.Process (execute.sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet), System.Diagnostics.Process (123456789012345)]
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(2298,0): at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
Failed again in [runtime-coreclr libraries-jitstress](https://dev.azure.com/dnceng-public/public/_build?definitionId=138&_a=summary)/[20241211.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893308)
- net10.0-linux-Release-arm-jitstress1_tiered-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7


```
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 262 of 324 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Linux
Linux
Linux
Linux
    System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix [SKIP]
      Condition(s) not met: "IsPrivilegedProcess"
None of the following programs were installed on this machine: xdg-open,gnome-open,kfmclient.
    System.Diagnostics.Tests.ProcessTests.TestPriorityClassUnix [SKIP]
      Condition(s) not met: "IsPrivilegedProcess"
    System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"
    System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported [FAIL]
      Assert.Contains() Failure: Filter not matched in collection
      Collection: [System.Diagnostics.Process (helix_docker_work.sh), System.Diagnostics.Process (execute.sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet), System.Diagnostics.Process (123456789012345)]
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(2300,0): at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported()
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress 20241211.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=893308&view=ms.vss-test-web.build-test-results-tab&runId=23413850&resultId=143255&paneView=debug)

**Failed tests:**
```
net10.0-linux-Release-arm-jitstress1_tiered-(Debian.12.Arm32.Open)Ubuntu.2204.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported
```

**Error message:**
```
 Assert.Contains() Failure: Filter not matched in collection
Collection: [System.Diagnostics.Process (helix_docker_work.sh), System.Diagnostics.Process (execute.sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet), System.Diagnostics.Process (123456789012345)]
```

**Stack trace:**
```
   at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 2300
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs:line 1128
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 48
```
