### ISSUE TITLE
LocalFileSettingsProviderTests.GetPropertyValues_NotStoredProperty_ValueEqualsNull failing sporadically in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#29429]
```
System.ConfigurationTests.LocalFileSettingsProviderTests.GetPropertyValues_NotStoredProperty_ValueEqualsNull


Error message
System.Configuration.ConfigurationErrorsException : An error occurred loading a configuration file: The process cannot access the file 'C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config' because it is being used by another process. (C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config)\r\n---- System.IO.IOException : The process cannot access the file 'C:\\Users\\runner\\AppData\\Local\\Microsoft_Corporation\\xunit.console_StrongName_vmuqnj1rm2vzmtjlxpznjgrpuvgx0hav\\2.5.1.0\\user.config' because it is being used by another process.

Stack trace
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationSchemaErrors.cs:line 76
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3659
   at System.Configuration.BaseConfigurationRecord.RefreshFactoryRecord(String configKey) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 747
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3378
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3421
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3421
   at System.Configuration.BaseConfigurationRecord.HlClearResultRecursive(String configKey, Boolean forceEvaluatation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 3421
   at System.Configuration.Internal.InternalConfigRoot.ClearResult(BaseConfigurationRecord configRecord, String configKey, Boolean forceEvaluation) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\Internal\InternalConfigRoot.cs:line 288
   at System.Configuration.BaseConfigurationRecord.RefreshSection(String configKey) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\BaseConfigurationRecord.cs:line 268
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientConfigurationSystem.cs:line 61
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ConfigurationManager.cs:line 173
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\ClientSettingsStore.cs:line 96
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties) in D:\a\1\s\src\System.Configuration.ConfigurationManager\src\System\Configuration\LocalFileSettingsProvider.cs:line 91
   at System.ConfigurationTests.LocalFileSettingsProviderTests.GetPropertyValues_NotStoredProperty_ValueEqualsNull() in D:\a\1\s\src\System.Configuration.ConfigurationManager\tests\System\Configuration\LocalFileSettingsProviderTests.cs:line 27
----- Inner Stack Trace -----
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\IO\FileStream.Windows.cs:line 1643
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\IO\FileStream.Win32.cs:line 45
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in F:\workspace\_work\1\s\src\System.Private.CoreLib\shared\System\IO\FileStream.cs:line 238
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) in F:\workspace\_wor
```
cc: @JeremyKuhne

**Comment by danmosemsft** [comment]
Moving to future, a long disabled test without clear customer impact
