### ISSUE TITLE
XDocument.SaveAsync has a blocking call

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#29464]
`XDocument.SaveAsync` has a blocking call. In ASP.NET Core 3 this is not allowed (by default).

````
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException:  ---> System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true.

at Microsoft.AspNetCore.TestHost.ResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.Flush()
   at System.Xml.XmlWellFormedWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlAsyncCheckWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   at System.Xml.Linq.XDocument.SaveAsync(Stream stream, SaveOptions options, CancellationToken cancellationToken)
   at MyCode(Stream stream, XDocument document, CancellationToken cancellationToken)
````

I think `SaveAsync` should call `FlushAsync` before calling `Dispose` (or maybe `XmlWriter` should implement `IAsyncDisposable`).

```c#
        public async Task SaveAsync(Stream stream, SaveOptions options, CancellationToken cancellationToken)
        {
            XmlWriterSettings ws = GetXmlWriterSettings(options);

            ws.Async = true;

            if (_declaration != null && !string.IsNullOrEmpty(_declaration.Encoding))
            {
                try
                {
                    ws.Encoding = Encoding.GetEncoding(_declaration.Encoding);
                }
                catch (ArgumentException)
                {
                }
            }

            using (XmlWriter w = XmlWriter.Create(stream, ws))
            {
                await WriteToAsync(w, cancellationToken).ConfigureAwait(false);

                // I think we should add FlushAsync here
                await w.FlushAsync().ConfigureAwait(false);
            }
        }
```

**Comment by davidfowl** [comment]
👏
