### ISSUE TITLE
Http2_DataSentBeforeServerPreface_ProtocolError - failed

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#29462]
Test: `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_DataSentBeforeServerPreface_ProtocolError`

https://dev.azure.com/dnceng/public/_build/results?buildId=180254&view=ms.vss-test-web.build-test-results-tab&runId=4352366&resultId=324794&paneView=debug

```
netcoreapp-OSX-Debug-x64-OSX.1012.Amd64.Open

System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_DataSentBeforeServerPreface_ProtocolError

Assert.Contains() Failure\nNot found: PROTOCOL_ERROR\nIn value: System.Net.Http.HttpRequestException: Exception of type 'System.Net.Http.HttpRequestException' was thrown.\n at System.Net.Http.Http2Connection.AddStream(HttpRequestMessage request) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1411\n at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 975\n at System.Threading.Tasks.ValueTask`1.get_Result() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/ValueTask.cs:line 759\n at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1356\n at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 525\n at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33\n at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 496\n at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\\projects\\xunit\\src\\xunit.assert\\Asserts\\Record.cs:line 82

   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.AssertProtocolErrorAsync(Task task, ProtocolErrors errorCode) in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 35
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_DataSentBeforeServerPreface_ProtocolError() in /Users/vsts/agent/2.150.3/work/1/s/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
```

cc @stephentoub @davidsh

**Comment by karelz** [comment]
@wfurt are you still working on it? Or can @aik-jahoda take a look?

**Comment by wfurt** [comment]
he can certainly look :) I had some ideas but I'm focusing on ssl right now.

**Comment by Anipik** [comment]
failed again in https://github.com/dotnet/corefx/pull/42920

**Comment by karelz** [comment]
No failures during 2/23-5/11 (incl. PRs). Closing.
