### ISSUE TITLE
SSL Handshaking on the same stream multiple times without reading/writing does not work correctly on Linux

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#29595]
To repro, run following test on Linux:

Found by running following perf test: https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/corefx/System.Net.Security/SslStreamTests.cs#L56

```csharp
using (var listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
{
    client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
    client.Connect(listener.LocalEndPoint);
    server = listener.Accept();
    _client = new NetworkStream(client, ownsSocket: true);
    _server = new NetworkStream(server, ownsSocket: true);
    for (int i = 0; i < 100; i++)
    {
        using (var sslClient = new SslStream(_client, leaveInnerStreamOpen: true, delegate { return true; }))
        using (var sslServer = new SslStream(_server, leaveInnerStreamOpen: true, delegate { return true; }))
        {
            await Task.WhenAll(
                sslClient.AuthenticateAsClientAsync("localhost", null, SslProtocols.None, checkCertificateRevocation: false),
                sslServer.AuthenticateAsServerAsync(_cert, clientCertificateRequired: false, SslProtocols.None, checkCertificateRevocation: false));
        }
    }
}
```

Output:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
---> Interop+Crypto+OpenSslCryptographicException: error:140940F4:SSL routines:ssl3_read_bytes:unexpected message
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount) in /home/krwq/src/corefx/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 278
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 124
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 710
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 557
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 528
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 697
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 600
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 557
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 528
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 398
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 312
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 234
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 213
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_1(String arg1, X509CertificateCollection arg2, SslProtocols arg3, AsyncCallback callback, Object state) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 392
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) in /__w/1/s/src/System.Private.CoreLib/shared/System/Threading/Tasks/FutureFactory.cs:line 1151
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation) in /home/krwq/src/corefx/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 393
   at System.Net.Security.Tests.SslStreamTests.HandshakeAsync() in /home/krwq/src/performance/src/benchmarks/micro/corefx/System.Net.Security/SslStreamTests.cs:line 60
   at BenchmarkDotNet.Autogenerated.Runnable_0.<.ctor>b__3_3() in /home/krwq/src/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp3.0/818cc993-56d1-468a-8969-9ef0f8cdcd98/818cc993-56d1-468a-8969-9ef0f8cdcd98.notcs:line 192
   at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in /home/krwq/src/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp3.0/818cc993-56d1-468a-8969-9ef0f8cdcd98/818cc993-56d1-468a-8969-9ef0f8cdcd98.notcs:line 754
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineStage.RunIteration(IterationMode mode, IterationStage stage, Int32 index, Int64 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EnginePilotStage.RunSpecific()
   at BenchmarkDotNet.Engines.Engine.Run()
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in /home/krwq/src/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp3.0/818cc993-56d1-468a-8969-9ef0f8cdcd98/818cc993-56d1-468a-8969-9ef0f8cdcd98.notcs:line 175
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /__w/1/s/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 466
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in /home/krwq/src/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp3.0/818cc993-56d1-468a-8969-9ef0f8cdcd98/818cc993-56d1-468a-8969-9ef0f8cdcd98.notcs:line 52
```

Adding single read/write in the loop workarounds the issue

cc: @stephentoub

**Comment by wfurt** [comment]
As far as I can tell, this is specific to TLS1.3 not necessarily to OpenSSL version. When I fixed SslVersion to TLS12, it works fine even with OpenSSL 1.1.1.

TLS1.3 main focus on cutting down messages and cutting down latency for the handshake. 


![image](https://user-images.githubusercontent.com/14356188/73975905-15903a00-48dc-11ea-9ce5-9d6483ba13b1.png)

In this case, part of the handshake will piggyback on the first data written _after_ AuthenticateAs*() finished. We could try to flush but I think that would defeat purpose of the TLS13 handshake.

**Comment by wfurt** [comment]
Triage: low priority, no external report. most likely part of TLS13 behavior.

**Comment by wfurt** [comment]
I don't think there is problem with SslStream. We can re-open (or create new issue) if this becomes issue.
