### ISSUE TITLE
Test failure: System.Net.NetworkInformation.Tests.PingTest/SendPingWithIPAddressAndTimeout 

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#29803]
Test `System.Net.NetworkInformation.Tests.PingTest/SendPingWithIPAddressAndTimeout ` has failed.

Message :
```
System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.
---- System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.
```

Stack Trace :
```
 at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options) in /_/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 237
   at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout, Byte[] buffer) in /_/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 202
   at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout) in /_/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 192
   at System.Net.NetworkInformation.Tests.PingTest.<>c__DisplayClass10_0.<SendPingWithIPAddressAndTimeout>b__0(Ping ping) in /_/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 205
   at System.Net.NetworkInformation.Tests.PingTest.SendPing(Func`2 sendPing, Action`1 pingResultValidator) in /_/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 769
   at System.Net.NetworkInformation.Tests.PingTest.SendBatchPing(Func`2 sendPing, Action`1 pingResultValidator) in /_/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 750
   at System.Net.NetworkInformation.Tests.PingTest.SendPingWithIPAddressAndTimeout() in /_/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 210
----- Inner Stack Trace -----
   at System.Net.NetworkInformation.Ping.SendWithPingUtility(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in /_/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 297
   at System.Net.NetworkInformation.Ping.SendPingCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in /_/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs:line 26
   at System.Net.NetworkInformation.Ping.Send(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options) in /_/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs:line 233
```

Build : -2[0190605.78](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190605.78)(Master)

Failing configurations:

- OSX.1012.Amd64.Open-x64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190605.78/workItem/System.Net.Ping.Functional.Tests/analysis/xunit/System.Net.NetworkInformation.Tests.PingTest~2FSendPingWithIPAddressAndTimeout

**Comment by wfurt** [comment]
this did not failed in last 3 months. closing. If this fails again we should open new issue IMHO.
