### ISSUE TITLE
System.Net.Http.Functional.Tests failing with "Process terminated. Assertion failed." in SetParentHandle

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#30006]
From https://github.com/dotnet/corefx/pull/38469

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38469~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.21/workItem/System.Net.Http.Functional.Tests/wilogs

Windows.81.Amd64.Open-x64:Debug
 System.Net.Http.Functional.Tests

```text
C:\dotnetbuild\work\5965e5fe-719d-4ba9-a256-d3d60b6a7a70\Work\ed3631b2-b397-4473-8088-590754b65a5a\Exec>"C:\dotnetbuild\work\5965e5fe-719d-4ba9-a256-d3d60b6a7a70\Payload\dotnet.exe" xunit.console.dll System.Net.Http.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.Http.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.Functional.Tests (found 761 of 1097 test cases)
  Starting:    System.Net.Http.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
      Condition(s) not met: "CanTestClientCertificates"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "CanTestClientCertificates"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
      Condition(s) not met: "IsSelectedSitesTestEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
      Condition(s) not met: "IsSelectedSitesTestEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
      Condition(s) not met: "IsSelectedSitesTestEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
      Condition(s) not met: "IsSelectedSitesTestEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http2.UnreadResponseMessage_Collectible [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http2.ManyClients_ManyGets [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http2.SingleClient_ManyGets_Async [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http2.MakeAndFaultManyRequests [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http2.SingleClient_ManyGets_Sync [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http11.UnreadResponseMessage_Collectible [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http11.MakeAndFaultManyRequests [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http11.ManyClients_ManyPosts_Async [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http11.SingleClient_ManyGets_Async [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http11.SingleClient_ManyGets_Sync [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_Http11.ManyClients_ManyGets [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "CanTestClientCertificates"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
      Condition(s) not met: "CanTestClientCertificates"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.MakeAndFaultManyRequests [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.CreateAndDestroyManyClients [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.ManyClients_ManyGets [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.SingleClient_ManyGets_Sync [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.UnreadResponseMessage_Collectible [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress_NoVersion.SingleClient_ManyGets_Async [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.Credentials_DomainJoinedServerUsesKerberos_UseIpAddressAndHostHeader_Success [SKIP]
      Condition(s) not met: "IsDomainJoinedServerAvailable"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.Credentials_ServerUsesWindowsAuthentication_Success [SKIP]
      Condition(s) not met: "IsWindowsServerAvailable"
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.Credentials_DomainJoinedServerUsesKerberos_Success [SKIP]
      Condition(s) not met: "IsDomainJoinedServerAvailable"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Authentication_Test.Credentials_ServerUsesWindowsAuthentication_Success [SKIP]
      Condition(s) not met: "IsWindowsServerAvailable"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.Ctor_ExpectedDefaultPropertyValues_UapPlatform [SKIP]
      Condition(s) not met: "IsUap"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Authentication_Test.Credentials_DomainJoinedServerUsesKerberos_Success [SKIP]
      Condition(s) not met: "IsDomainJoinedServerAvailable"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Authentication_Test.Credentials_DomainJoinedServerUsesKerberos_UseIpAddressAndHostHeader_Success [SKIP]
      Condition(s) not met: "IsDomainJoinedServerAvailable"
Process terminated. Assertion failed.
   at Interop.WinHttp.SafeWinHttpHandle.SetParentHandle(SafeWinHttpHandle parentHandle) in /_/src/Common/src/Interop/Windows/WinHttp/Interop.SafeWinHttpHandle.cs:line 35
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 813
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/AsyncMethodBuilder.cs:line 1019
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<>c.<SendAsync>b__101_0(Object s) in /_/src/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 560
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 289
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Task.cs:line 2389
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 663
----- end Mon 06/24/2019 17:30:26.88 ----- exit code -2146232797 ----------------------------------------------------------
 Mon 06/24/2019-17:30:26.91
 Mon 06/24/2019-17:30:26.97
Got args https://dev.azure.com/dnceng/ public 5865096 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBSZWFkQW5kUHVibGlzaFRlc3Q6OWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkIFJlYWRBbmRVcGRhdGVCdWlsZEJ5VXJpOjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZC9kb3RuZXQvY29yZWZ4LzE5NjpCdWlsZC9CdWlsZC8yMzY0MzkiLCJhdWkiOiJiYjI5YmM5ZC1iZTIzLTRiNmEtYjBjMC1iMzczNTk4MzdiZWIiLCJzaWQiOiJkMmIwMTg3Ni0wZjc0LTRhMjMtYjc4Yi1iMmUzNjc5ZTRkMWUiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286YjU1ZGU0ZWQtNGI1YS00MjE1LWE4ZTQtMGEwYTVmNzFlN2Q4IiwibmJmIjoxNTYxMzk0MTA3LCJleHAiOjE1NjE0MDQzMDd9.Oi-dWTU2rVYMoB119ZAQFBKleHR_SbbPZ2J66UcOqQoqWdmV41_kJunEgG-Ao0mRPVU-quxXurdwgtBN_bzDCCvhxWOpIg07qijI04O1_lIDEUGISFvcjPVFyuzQmfAahxR6AIIR5iBDS9Z-vzOxKEv2V5jMmvpn8NWvVPc2SH-6bHIDrdAKNXfh8hYZ86G_kntCGb67EIDmOMxp39Fn-ux6S896xsHVYQRALQoGEJ9Ef9G9zuPphzkoTKhFsfnEHpMxCk3Wiy4OiEyXmiK9Pk_I4E3uLRter-3GV_seZ2lMSoaGSdQc5dsLfPVUq3Ea0ZMtrtzWVzlErH1gT0QH3Q
Main thread starting workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
Beginning reading of test results.
Uploading results in batches of size 1000
Searching 'C:\dotnetbuild\work\5965e5fe-719d-4ba9-a256-d3d60b6a7a70\Work\ed3631b2-b397-4473-8088-590754b65a5a\Exec\..' for log files
Found log 'C:\dotnetbuild\work\5965e5fe-719d-4ba9-a256-d3d60b6a7a70\Work\ed3631b2-b397-4473-8088-590754b65a5a\Exec\..\console.f216fa0c.log'
Uri 'https://helixexternalresults.blob.core.windows.net/dotnet-corefx-refs-pull-38469-merge-5965e5fe719d4ba9a2/System.Net.Http.Functional.Tests/console.f216fa0c.log?sv=2017-07-29&sr=c&sig=aQOkH8idk7iXCUKDlu5pl%2FduGfTgQ2gVifobNDu%2FLZ8%3D&se=2019-07-04T17%3A08%3A09Z&sp=rl'
Generated log list: <ul><li><a href='https://helixexternalresults.blob.core.windows.net/dotnet-corefx-refs-pull-38469-merge-5965e5fe719d4ba9a2/System.Net.Http.Functional.Tests/console.f216fa0c.log?sv=2017-07-29&sr=c&sig=aQOkH8idk7iXCUKDlu5pl%2FduGfTgQ2gVifobNDu%2FLZ8%3D&se=2019-07-04T17%3A08%3A09Z&sp=rl' target='_blank'>console.f216fa0c.log</a></li></ul>
Searching 'C:\dotnetbuild\work\5965e5fe-719d-4ba9-a256-d3d60b6a7a70\Work\ed3631b2-b397-4473-8088-590754b65a5a\Exec' for test results files
No results file found in any of the following formats: xunit, junit, trx
Main thread finished queueing batches
Worker 0: uploaded 1 results
Main thread exiting
 Mon 06/24/2019-17:30:28.02
2019-06-24 17:30:28,540: ERROR: xunit-reporter(69): main: Unable to report xunit results: no test results xml file found.
```

cc @stephentoub, @wfurt, @krwq

**Comment by davidsh** [comment]
In PR #397 we removed WinHttpHandler from System.Net.Http.dll. We no longer run "PlatformHandler" tests in System.Net.Http library.

While we do have separate tests for WinHttpHandler specifically, I don't think those tests will surface this intermittent error.

Since this won't repro anymore due to #397, I am going to close this issue. If 'SetParentHandle' errors surface again via WinHttpHandler tests, we can open a new issue and reference this issue.
