### ISSUE TITLE
Failing unit test locally on mac: BitmapTests.GetFrameCount_NewBitmap_ReturnsZero

### ISSUE THREAD

**Issue by hughbe** [dotnet/runtime#30043]
```
        System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
        Stack Trace:
          /Users/hugh/Documents/GitHub/corefx/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(259,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
          /Users/hugh/Documents/GitHub/corefx/src/System.Drawing.Common/src/System/Drawing/Image.cs(271,0): at System.Drawing.Image.GetFrameCount(FrameDimension dimension)
          /Users/hugh/Documents/GitHub/corefx/src/System.Drawing.Common/tests/BitmapTests.cs(555,0): at System.Drawing.Tests.BitmapTests.GetFrameCount_NewBitmap_ReturnsZero()
```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
