### ISSUE TITLE
System.Collections.Immutable.Tests.ImmutableSortedDictionaryTest.EqualsTest failed on Mono OSX

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#3009]
netcoreapp5.0-OSX-Debug-x64-Mono_release-OSX.1013.Amd64.Open

https://dev.azure.com/dnceng/public/_build/results?buildId=502018&view=ms.vss-test-web.build-test-results-tab&runId=15943916&paneView=debug
```

Error message
Assert.True() Failure\nExpected: True\nActual: False


Stack trace
   at System.Collections.Immutable.Tests.ImmutableDictionaryTestBase.EqualsTest()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by danmosemsft** [comment]
Unfortunately this test has 15 different asserts and we have no line number. This is not actionable. Reopen if we get more information.

**Comment by danmosemsft** [comment]
We should also fix whatever the line number issue is. Presumably not deploying the pdb in the test directory.

**Comment by jkotas** [comment]
This failed again in https://github.com/dotnet/runtime/pull/31700 with slightly different stacktrace:
```
  Starting:    System.Collections.Immutable.Tests (parallel test collections = on, max threads = 4)
    System.Collections.Immutable.Tests.ImmutableHashSetTest.EmptyTest [FAIL]
      Assert.Same() Failure
      Expected: ImmutableHashSet<Int32> []
      Actual:   ImmutableHashSet<Int32> []
      Stack Trace:
           at System.Collections.Immutable.Tests.ImmutableHashSetTest.EmptyTestHelper[Int32](IImmutableSet`1 emptySet, Int32 value, IEqualityComparer`1 comparer)
           at System.Collections.Immutable.Tests.ImmutableHashSetTest.EmptyTest()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by akoeplinger** [comment]
> We should also fix whatever the line number issue is. Presumably not deploying the pdb in the test directory.

Mono historically didn't read the .pdb by default, we're changing that for netcore: https://github.com/dotnet/runtime/issues/31662

**Comment by stephentoub** [comment]
I believe the cause of this is https://github.com/dotnet/runtime/issues/31988.
