### ISSUE TITLE
Test failed: System.Resources.Extensions.Tests.PreserializedResourceWriterTests

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#30184]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190707.1/workItem/System.Resources.Extensions.Tests/analysis/xunit/System.Resources.Extensions.Tests.PreserializedResourceWriterTests~2FStreamResources

**Failed tests:**
System.Resources.Extensions.Tests.PreserializedResourceWriterTests

**Log:**
```
System.ArgumentException : Parameter is not valid.
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at System.Drawing.Icon.ToBitmap()
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.ResourceValueEquals(Object expected, Object actual) in /_/src/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 525
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources() in /_/src/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 460
```

**Comment by v-haren** [comment]
failed in job: [runtime-coreclr libraries-jitstressregs 20200816.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=773164&view=ms.vss-test-web.build-test-results-tab&runId=24156390&resultId=141196&paneView=debug)

failed test: System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources


Error message
~~~
System.ArgumentException : Parameter is not valid.


Stack trace
   at System.Drawing.Image.get_RawFormat() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Image.cs:line 281
   at System.Drawing.Graphics.IgnoreMetafileErrors(Image image, Int32& errorStatus) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs:line 2451
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs:line 1655
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 104
   at System.Drawing.Icon.ToBitmap() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:line 642
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.ResourceValueEquals(Object expected, Object actual) in /_/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 505
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources() in /_/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 434
~~~

**Comment by ericstj** [comment]
@safern typically for this sort of thing you can force a repro by modifying the product code to introduce a GC.Collect and WaitForPendingFinalizers right before the call that is throwing.

Agree that this doesn't meet the bar for 5.0.0 at this point, but it's something we could easily fix in 6.0.0

**Comment by safern** [comment]
Thanks, @ericstj -- I modified the milestone.

**Comment by VincentBu** [comment]
Failed in job : [runtime-coreclr libraries-jitstress2-jitstressregs 20210109.1](https://dev.azure.com/dnceng/public/_build/results?buildId=943780&view=ms.vss-test-web.build-test-results-tab&runId=29787718&resultId=119254&paneView=debug)

Failed test : System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources

**Error message:**
```
System.ArgumentException : Parameter is not valid.


Stack trace
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 106
   at System.Drawing.Icon.ToBitmap() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:line 645
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.ResourceValueEquals(Object expected, Object actual) in /_/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 501
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources() in /_/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 434
```
