### ISSUE TITLE
A few loopback server tests are timing out in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#30733]
https://dnceng.visualstudio.com/public/_build/results?buildId=332377&view=ms.vss-test-web.build-test-results-tab&runId=9749356&resultId=100001&paneView=attachments

Configuration: netcoreapp-Windows_NT-Release-arm64-Windows.10.Arm64.Open

```   System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly(chunkedTransfer: False, mode: Token) [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs(45,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly(Boolean chunkedTransfer, CancellationMode mode)
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Finalization_Http2_Test.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Finalization.cs(34,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Finalization_Test.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer()
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(timeoutPropertyName: "PooledConnectionLifetime") [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(207,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(1606,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(String timeoutPropertyName)
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http2.GetAsync_AddMultipleCookieHeaders_CookiesSent [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cookies.cs(150,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent()
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http2.SendAsync_WithZeroLengthHeaderName_Throws [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Headers.cs(272,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_WithZeroLengthHeaderName_Throws()
        --- End of stack trace from previous location where exception was thrown ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.PostAsync_ManyDifferentRequestHeaders_SentCorrectly [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(42,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/Common/tests/System/Net/Http/Http2LoopbackServer.cs(215,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(789,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_ManyDifferentRequestHeaders_SentCorrectly()
        --- End of stack trace from previous location where exception was thrown ---
```

@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by karelz** [comment]
I was able to hit `GetAsync_AddMultipleCookieHeaders_CookiesSent` timeout 1x in 534 runs on latest Win10 VM.
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\git\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 83
    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\git\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 111
    at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass4_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in C:\git\runtime\src\libraries\Common\tests\System\Net\Http\GenericLoopbackServer.cs:line 32
    --- End of stack trace from previous location ---
    at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in C:\git\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 38
    at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options) in C:\git\runtime\src\libraries\Common\tests\System\Net\Http\Http2LoopbackServer.cs:line 236
    at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in C:\git\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 38
    at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent() in C:\git\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.Cookies.cs:line 153
    --- End of stack trace from previous location ---
```

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20201125.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=899602&view=ms.vss-test-web.build-test-results-tab&runId=28737930&resultId=104379&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_PingKeepAlive(keepAlivePingDelay: 00:00:01, keepAlivePingPolicy: Always, expectRequestFail: False)

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open


Error message
~~~
System.Threading.Tasks.TaskCanceledException : A task was canceled.


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Http2Options http2Options, Int32 timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 172
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2_PingKeepAlive(TimeSpan keepAlivePingDelay, HttpKeepAlivePingPolicy keepAlivePingPolicy, Boolean expectRequestFail) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1672
--- End of stack trace from previous location ---
~~~

**Comment by ManickaP** [comment]
This issue is too wide, bunch of tests timing out. If some them still fail we'll see them popping out in our regular CI report.
