### ISSUE TITLE
GetAsync_ExpectContinueTrue_NoContent_StillSendsHeader failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#30976]
https://dnceng.visualstudio.com/public/_build/results?buildId=366818&view=ms.vss-test-web.build-test-results-tab&runId=11098392&resultId=100001&paneView=attachments

Configuration: `netcoreapp-Windows_NT-Release-arm64-Windows.10.Arm64.Open`

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_ExpectContinueTrue_NoContent_StillSendsHeader [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(44,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs(1939,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ExpectContinueTrue_NoContent_StillSendsHeader()
        --- End of stack trace from previous location where exception was thrown ---
```

@geoffkizer, @wfurt, @davidsh, @scalablecory, @eiriktsarpalis, @karelz

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200423.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=613418&view=ms.vss-test-web.build-test-results-tab&runId=19252660&resultId=103326&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxConnectionsPerServer_Test.SmallConnectionLifetimeWithMaxConnections_PendingRequestUsesDifferentConnection(lifetimeMilliseconds: 1)


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 42
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxConnectionsPerServer_Test.<>c__DisplayClass1_1.<<SmallConnectionLifetimeWithMaxConnections_PendingRequestUsesDifferentConnection>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 213
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 134
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxConnectionsPerServer_Test.<>c__DisplayClass1_0.<<SmallConnectionLifetimeWithMaxConnections_PendingRequestUsesDifferentConnection>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 195
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 69
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxConnectionsPerServer_Test.SmallConnectionLifetimeWithMaxConnections_PendingRequestUsesDifferentConnection(Int32 lifetimeMilliseconds) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 190
--- End of stack trace from previous location ---
~~~

**Comment by MihaZupan** [comment]
Last comment is for a different failure: #42724

**Comment by karelz** [comment]
No failures during 2/23-5/11 (incl. PRs). Closing.
