### ISSUE TITLE
System.Composition: CompositionContext.TryGetExport throws CompositionFailedException

### ISSUE THREAD

**Issue by davidmilligan** [dotnet/runtime#31010]
The `CompositionContext.TryGetExport` method can throw a `CompositionFailedException`. This violates the common convention/expectation that `TryXXX` methods don't throw, instead they just return false. 

I would expect that calling `GetExport` would throw an exception in this situation but I would expect that `TryGetExport` would simply return `false`.

Stack Trace:
```
An exception of type 'System.Composition.Hosting.CompositionFailedException' occurred in System.Composition.Hosting.dll but was not handled in user code: 'The component (unknown) cannot be created outside the Scoped sharing boundary.'
   at System.Composition.Hosting.Core.LifetimeContext.FindContextWithin(String sharingBoundary)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract contract, Object& export)
   at System.Composition.CompositionContext.TryGetExport(Type exportType, String contractName, Object& export)
   at System.Composition.CompositionContext.TryGetExport(Type exportType, Object& export)
```

**Comment by ericstj** [comment]
Even Try Methods can throw.  The distinction is usually if the exception is caused by a design time error or a runtime error.  Typically these methods still throw for design time errors (eg: you called the method wrong, provided incorrect parameters that aren't runtime data, or setup the method wrong).  It's important to still throw in these cases so you don't hide a deisgn-time error.

Would you classify this case as a design time error?  I couldn't tell from the OP since it omitted repro steps.

**Comment by davidmilligan** [comment]
No, this is not a design time error. I’ve already provided plenty of justification as to why in my comments above, as this question was already asked in this thread. There’s also repro steps in an above comment.
