### ISSUE TITLE
System.Diagnostics.Tests.EventLogEntryEventWrittenTest.EntryWrittenEventRaised failing with AggregateException on Windows.10.Amd64.Client19H1.ES.Open

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#31207]
From https://github.com/dotnet/corefx/pull/41877

corefx-ci (Windows Build x64_Debug)
netcoreapp-Windows_NT-Debug-x64-Windows.10.Amd64.Client19H1.ES.Open

https://helix.dot.net/api/2019-06-17/jobs/3f109ae1-49d6-468a-9031-887de595b0af/workitems/System.Diagnostics.EventLog.Tests/console

```text
    System.Diagnostics.Tests.EventLogConfigurationTests.SetProperties_SaveChanges_NotAdmin_Throws [SKIP]
      Condition(s) not met: "NotElevatedAndSupportsEventLogs"
    System.Diagnostics.Tests.EventLogEntryEventWrittenTest.EntryWrittenEventRaised [FAIL]
      System.AggregateException : One or more errors occurred. (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.) (Uno de los dispositivos conectados al sistema no funciona.)
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      ---- System.ComponentModel.Win32Exception : Uno de los dispositivos conectados al sistema no funciona.
      Stack Trace:
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(47,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(30,0): at System.Diagnostics.Tests.Helpers.Retry[T](Func`1 func)
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.Retry(Action func)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.RaisingEvent(String log, String methodName, Boolean waitOnEvent)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(58,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.EntryWrittenEventRaised()
        ----- Inner Stack Trace dotnet/corefx#1 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#2 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#3 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#4 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#5 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#6 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#7 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#8 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#9 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
        ----- Inner Stack Trace dotnet/corefx#10 (System.ComponentModel.Win32Exception) -----
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(477,0): at System.Diagnostics.EventLogInternal.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(226,0): at System.Diagnostics.EventLog.Clear()
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(396,0): at System.Diagnostics.EventLog.Delete(String logName, String machineName)
        /_/src/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(360,0): at System.Diagnostics.EventLog.Delete(String logName)
        /_/src/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs(51,0): at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(23,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass6_0.<Retry>b__0()
        /_/src/System.Diagnostics.EventLog/tests/Helpers.cs(32,0): at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0`1.<Retry>b__0()
        /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs(37,0): at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc)
  Finished:    System.Diagnostics.EventLog.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.EventLog.Tests  Total: 140, Errors: 0, Failed: 1, Skipped: 1, Time: 77,730s
```

cc @Anipik, @wtgodbe

**Comment by ViktorHofer** [comment]
Failed again: https://dnceng.visualstudio.com/public/_build/results?buildId=517242&view=ms.vss-test-web.build-test-results-tab&runId=16366334&paneView=debug&resultId=180702

```
netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

System.AggregateException : One or more errors occurred. (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.) (A device attached to the system is not functioning.)\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning.
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 45
   at System.Diagnostics.Tests.Helpers.Retry[T](Func`1 func) in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 41
   at System.Diagnostics.Tests.Helpers.Retry(Action func) in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.RaisingEvent(String log, String methodName, Boolean waitOnEvent) in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs:line 51
   at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.EntryWrittenEventRaised() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs:line 58
----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear() in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 476
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 370
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 361
   at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs:line 51
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 44
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #2 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear() in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 476
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 370
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 361
   at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogTests/EventLogEntryWrittenTest.cs:line 51
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 44
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #3 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear() in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 476
   at System.Diagnostics.EventLog.Delete(String logName, String machineName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 370
   at System.Diagnostics.EventLog.Delete(String logName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 361
   at System.Diagnostics.Tests.EventLogEntryEventWrittenTest.<>c__DisplayClass3_0.<RaisingEvent>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/
```

**Comment by ViktorHofer** [comment]
cc @danmosemsft @stephentoub seems like we are still hitting these random EventLog API issues. Unsure what we should do with these tests besides disabling them all.

**Comment by danmosemsft** [comment]
Disable them on whatever configurations they fail on and open issue. CI needs to be green.

**Comment by janvorli** [comment]
Failed again on my PR yesterday. https://helix.dot.net/api/2019-06-17/jobs/e89d240a-d384-4503-8a80-3715fc2e5721/workitems/System.Diagnostics.EventLog.Tests/files/console.90301c4e.log
