### ISSUE TITLE
System.Drawing.Font.ToLogFont(lOGFONT) fails on Linux - breaks SSRS ReportViewer

### ISSUE THREAD

**Issue by ststeiger** [dotnet/runtime#31302]
System.Drawing.Font.ToLogFont(lOGFONT); fails on Linux. 
This breaks Microsoft ReportViewer

Error information: 
```
[Font: Name=Noto Sans, Size=400, Units=3, GdiCharSet=1, GdiVerticalFont=False]

System.ArgumentException: 
Object contains non-primitive or non-blittable data.

Inner Exception = NULL, stacktrace> 
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type)
   at System.Drawing.Font.ToLogFont(Object logFont, Graphics graphics)
   at System.Drawing.Font.ToLogFont(Object logFont)
   
TargetSite: IntPtr InternalAlloc(System.Object, System.Runtime.InteropServices.GCHandleType)
exceptionMethod: IntPtr InternalAlloc(System.Object, System.Runtime.InteropServices.GCHandleType)

```

Error reproduction example: (it works on Windows, but fails on Linux)
```

namespace AspNetCore.ReportingServices.Fix4Linux
{


    internal class FontAbstraction
    {


        internal static AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel.CharSet
            GetFontExcelCharset(System.Drawing.Font font)
        {
            try
            {
                // https://stackoverflow.com/questions/4674744/how-to-programatically-get-the-character-encoding-a-font-supports
                // https://stackoverflow.com/questions/34663570/what-is-the-win32-api-logfont-lfcharset-value-for-the-unicode-character-set
                // There is no lfCharset value defined for Unicode. 
                // That would defeat the purpose of specifying a charset in the first place. 
                // Use whichever charset the font actually implements. 

                // It looks like most of its barcode glyphs are available in most charsets 
                // (some charsets have a few less glyphs).

                // So try setting the lfCharset to 0(ANSI_CHARSET) or 1(DEFAULT_CHARSET) 
                // if you must set a charset at all.

                AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel.LOGFONT lOGFONT = new AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel.LOGFONT();
                font.ToLogFont(lOGFONT);

                var cs = (AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel.CharSet)lOGFONT.lfCharSet;
                return cs;
            }
            catch (System.Exception)
            {
                System.Console.WriteLine(ex.Message);
                System.Console.WriteLine(font);
            }

            return AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel.CharSet.DEFAULT_CHARSET;
        }

    }


}

```

here's Excel logfont

```
namespace AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel
{
	[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential, CharSet = System.Runtime.InteropServices.CharSet.Auto)]
	internal class LOGFONT
	{
		public int lfHeight;

		public int lfWidth;

		public int lfEscapement;

		public int lfOrientation;

		public int lfWeight;

		public byte lfItalic;

		public byte lfUnderline;

		public byte lfStrikeOut;

		public byte lfCharSet;

		public byte lfOutPrecision;

		public byte lfClipPrecision;

		public byte lfQuality;

		public byte lfPitchAndFamily;

		[System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.ByValTStr, SizeConst = 32)]
		public string lfFaceName;
	}
}

```

and  charset 

```
namespace AspNetCore.ReportingServices.Rendering.ExcelRenderer.Excel
{
	internal enum CharSet : byte
	{
		ANSI_CHARSET = 0,
		DEFAULT_CHARSET = 1,
		SYMBOL_CHARSET = 2,
		MAC_CHARSET = 77,
		SHIFTJIS_CHARSET = 0x80,
		HANGEUL_CHARSET = 129,
		HANGUL_CHARSET = 129,
		JOHAB_CHARSET = 130,
		GB2312_CHARSET = 134,
		CHINESEBIG5_CHARSET = 136,
		GREEK_CHARSET = 161,
		TURKISH_CHARSET = 162,
		VIETNAMESE_CHARSET = 163,
		HEBREW_CHARSET = 177,
		ARABIC_CHARSET = 178,
		BALTIC_CHARSET = 186,
		RUSSIAN_CHARSET = 204,
		THAI_CHARSET = 222,
		EASTEUROPE_CHARSET = 238,
		OEM_CHARSET = byte.MaxValue
	}
}

```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
