### ISSUE TITLE
IsDaylightSavingTime_CasablancaMultiYearDaylightSavings fails on rhel.8

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#31331]
We have an internal CI server that does daily builds of corefx on rhel.8.
Since 24 sept, System.Runtime.Tests is failing on IsDaylightSavingTime_CasablancaMultiYearDaylightSavings.

I haven't looked further into this yet.

```
  pushd /home/tester/corefx/artifacts/bin/System.Runtime.Tests/netcoreapp-Unix-Debug
  /home/tester/corefx/artifacts/bin/testhost/netcoreapp-Linux-Debug-x64/dotnet exec --runtimeconfig System.Runtime.Tests.runtimeconfig.json xunit.console.dll System.Runtime.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
  popd
  ===========================================================================================================
  ~/corefx/artifacts/bin/System.Runtime.Tests/netcoreapp-Unix-Debug ~/corefx/src/System.Runtime/tests
  [37m  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  [m[37m  Discovered:  System.Runtime.Tests (found 5372 of 5419 test cases)
  [m[37m  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 4)
  [m[33;1m    System.Tests.DateTimeOffsetTests.ToLocalTime_MaxValue [SKIP]
  [m[37m      Condition(s) not met: "IsMaxValuePositiveLocalOffset"
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1940-02-25T00:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1940-11-20T00:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1940-12-31T23:59:59.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1941-01-01T00:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1945-02-24T12:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1945-11-17T01:00:00.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
      System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: "1945-11-17T22:59:59.0000000Z", expectedDST: True, expectedOffsetString: "1:00:00") [FAIL]
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 2/25/1940 12:00:00 AM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 11/20/1940 12:00:00 AM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 12/31/1940 11:59:59 PM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 1/1/1941 12:00:00 AM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 2/24/1945 12:00:00 PM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 11/17/1945 1:00:00 AM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[31;1m[m[37m      Test with the zone Africa/Casablanca and date 11/17/1945 10:59:59 PM failed
  [m[37m      Expected: True
  [m[37m      Actual:   False
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(2361,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
  [m[37m        /home/tester/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1743,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
  [m[33;1m    System.Tests.DateTimeOffsetTests.ToLocalTime_MinValue [SKIP]
  [m[37m      Condition(s) not met: "IsMinValueNegativeLocalOffset"
  [m[33;1m    System.Tests.DateTimeOffsetTests.ToLocalTime_Ambiguous [SKIP]
  [m[37m      Condition(s) not met: "IsPacificTime"
  [m[33;1m    System.Tests.ArgIteratorTests.ArgIterator_GetNextArgType [SKIP]
  [m[37m      Condition(s) not met: "IsArgIteratorSupported"
  [m[33;1m    System.Tests.ArgIteratorTests.ArgIterator_GetRemainingCount_GetNextArg [SKIP]
  [m[37m      Condition(s) not met: "IsArgIteratorSupported"
  [m[37m  Finished:    System.Runtime.Tests
  [m[37m=== TEST EXECUTION SUMMARY ===
  [m[37m   System.Runtime.Tests  Total: 34299, Errors: 0, Failed: 7, Skipped: 5, Time: 13.603s
```

cc @omajid @RheaAyase

**Comment by eerhardt** [comment]
This issue is still open because the fix hasn't been ported to 2.1. We ported it to 3.1 in January.

However, I haven't heard any reports of issues on 2.1. Should we close this bug until we feel there is a need to port the fix to 2.1? Or do we think we should move forward with a 2.1 port?

**Comment by danmosemsft** [comment]
At this point the bar to port to 2.1 is really high and we would not do it without evidence of signficant customer impact.

**Comment by eerhardt** [comment]
Sounds good to me. Closing for now. We can re-open once we see customer reports of this issue.
