### ISSUE TITLE
Many tests failed due to System.ArgumentException : Absolute path information is required

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#31340]
**Job:**
[corefx-ci #20191029.52](https://dnceng.visualstudio.com/public/_build/results?buildId=406908)

**Part of error message:**
```
Assert.Throws() Failure\r\nExpected: typeof(System.IO.FileNotFoundException)\r\nActual: typeof(System.ArgumentException): Absolute path information is required. (Parameter 'path')\r\n---- System.ArgumentException : Absolute path information is required. (Parameter 'path')
```

**Part of stack trace:**
```
   at System.Reflection.Assembly.LoadFile(String path) in /_/src/System.Private.CoreLib/shared/System/Reflection/Assembly.cs:line 220
   at System.Reflection.Tests.AssemblyTests.<>c__DisplayClass37_0.<LoadFile_NoSuchPath_ThrowsFileNotFoundException>b__0() in /_/src/System.Reflection/tests/AssemblyTests.cs:line 324
----- Inner Stack Trace -----
   at System.Reflection.Assembly.LoadFile(String path) in /_/src/System.Private.CoreLib/shared/System/Reflection/Assembly.cs:line 220
   at System.Reflection.Tests.AssemblyTests.<>c__DisplayClass37_0.<LoadFile_NoSuchPath_ThrowsFileNotFoundException>b__0() in /_/src/System.Reflection/tests/AssemblyTests.cs:line 324
```

**Comment by joperezr** [comment]
I'm closing this for now as I don't see it failing any longer on CI. Feel free to reopen otherwise.
