### ISSUE TITLE
Unrecognized configuration section system.data

### ISSUE THREAD

**Issue by cincuranet** [dotnet/runtime#31492]
When the app.config file contains `<system.data>` section, processing that file fails, because there's no handler for it.

I.e. this is what happens when EF6 (on netcoreapp3.0) tries to open it.

```text
Error : EntityFramework.Firebird.Tests.QueryTests.QueryTest1
System.TypeInitializationException : The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception.
  ----> System.Configuration.ConfigurationErrorsException : Configuration system failed to initialize
  ----> System.Configuration.ConfigurationErrorsException : Unrecognized configuration section system.data. (***.dll.config line 6)
   at System.Data.Entity.Internal.AppConfig.get_DefaultInstance()
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForAssembly(Assembly assemblyHint, Type contextTypeHint)
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForContext(Type contextType)
   at System.Data.Entity.Database.SetInitializer[TContext](IDatabaseInitializer`1 strategy)
   at EntityFramework.Firebird.Tests.EntityFrameworkTestsBase.GetDbContext[TContext]() in ***:line 46
   at EntityFramework.Firebird.Tests.QueryTests.QueryTest1() in ***:line 47
--ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_ConnectionStrings()
   at System.Data.Entity.Internal.AppConfig..ctor()
   at System.Data.Entity.Internal.AppConfig..cctor()
--ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
```

I understand the app.config is in general not used in .NET Core and the options there might not have an effect, but my expectation is, that it could be loaded at least.

**Comment by ericstj** [comment]
The built-in machine.config only has support for a small subset of the configuration types (largely limited to those which are supported on .NETCore).

On .NETFramework the system.data section would be satsified by this entry in machine.config:
```
        <section name="system.data" type="System.Data.Common.DbProviderFactoriesConfigurationHandler, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
```

Now you could define this section and provide a type to store the information your config file uses, but this information will not be *read* by any component in .NETCore, so you are better off just omitting it, along with any other config-section that would be used to configure .NET types.  System.Configuration.ConfigurationManager is largely only provided for compatibility and framework types no longer read the values set in `.config` files for their settings.

**Comment by ericstj** [comment]
See also https://github.com/dotnet/runtime/issues/33523
