### ISSUE TITLE
ODBC Arithmetic overflow error Accessing AS400 DB2 (Update, Delete, Insert)

### ISSUE THREAD

**Issue by BockTim91** [dotnet/runtime#31533]
We are trying to hit our AS400 running a DB2 instance. When we run a OdbcCommand.ExecuteNonQuery() for select, everything works no issue. However, when executing a simple update, or delete command, we encounter the below error. Our current workaround is to just squish all arithmetic errors out of our execute command, which is unacceptable.

```
Arithmetic operation resulted in an overflow.
   at System.Data.Odbc.OdbcDataReader.FirstResult()
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteNonQuery()
```

We are using VS 2017 with netcore 2.2

**Comment by tb-mtg** [comment]
I too am having this problem.  

I created a simple test project and with basic insert, update & delete OdbcCommands.  They only work, but only if the following is set:

`<PlatformTarget>x86</PlatformTarget>.`

The problem is our real application platform target is x64.

**Comment by danmosemsft** [comment]
@saurabh500

**Comment by saurabh500** [comment]
I think this one suffers from the lack of an WIN32 build for System.Data.Odbc, which has surfaced in System.Data.OleDb also. I will look into it.

**Comment by tb-mtg** [comment]
Turns out I had an out of date IBM Client Access ODBC driver 13.0.1.0.

I downloaded and installed the latest AS400 Client Access service pack si68573 from IBM and I think it may have fixed the problem.

The IBM i Access ODBC drivers versions are now:
* 13.0.21.0 for 32 bit (C:\Windows\SysWOW64\cwbodbc.dll)
* 13.64.21.0 for 64 bit (C:\Windows\System32\cwbodbc.dll)

**Comment by ajcvickers** [comment]
@saurabh500 Do you believe that there is still work to be done here?

**Comment by misha-p** [comment]
Experiencing the same issue with Vertica DB. When ODBC client is in 64 bit (.NET 5) and rows affected > Int32.MaxValue, overflow exception is thrown. I believe @Clockwork-Muse is exactly right in his analysis of the root cause https://github.com/dotnet/runtime/issues/31533#issuecomment-557211264

Unfortunately recent optimization done in .NET 6 preview branch - https://github.com/dotnet/runtime/commit/3d200308e1c9eb8daabd0498d7a2ee02635452b1 - will not solve the issue: `checked((int)l)` is removed, but ToInt32() called on IntPtr will throw OverflowException still.

We are building 32 bit target for now, just to overcome that issue. I guess getting some negative int for rows affected instead of the real count (> int.MaxValue) would be better then an overflow exception.

**Comment by PoojaSingh15** [comment]
@BockTim91, could you please share how are you connecting to as400?
I am using .net5 and IBM.data.DB2.core package to connect to my iSeries database. had no luck so far.

**Comment by BockTim91** [comment]
@PoojaSingh15 We are using System.Data.ODBC (.net core 3.1 currently) and using basic ODBC connections straight to our AS400 connecting to it through windows ODBC Data Sources. The ODBC data source is using iSeries Access ODBC Driver to connect.

**Comment by franciskhoury** [comment]
Hello, I am encountering this problem in .NET5.  The ArithmeticException is being raised on INSERT and DELETE statements (even if affecting 0 rows).  However, the MERGE statement is not raising an exception, and is returning the correct row count.

**Comment by danmoseley** [comment]
@saurabh500 per @ajcvickers  is there more work here?

**Comment by franciskhoury** [comment]
I am not able to reliably reproduce the issue.  I'm running in debug mode in VS2019 / IISExpress.  The issue happened sparsely, then it was happening consistently when I posted; now it seems to have stopped.  It feels like some transient factor on the db2 side is affecting things, but I don't have an idea of what it could be.

**Comment by danmoseley** [comment]
@franciskhoury if you repro under a debugger (VS should download sources and symbols) can you confirm the diagnosis above? And that the driver is returning an erroneous number of rows?

Although (I’m not familiar with this area) if our code simply does not support a number of rows that it ought to work with, perhaps that needs a fix as well.
