### ISSUE TITLE
.NET CORE 2.2: SSL Error : System.IO.IOException: The write operation failed In Linux Container

### ISSUE THREAD

**Issue by akw123** [dotnet/runtime#31537]
Hi guys,

Needed help here from the community.

We have been trying to get this work on Linux Container for quite sometime, but to no avail solution.

We are calling an API that uses SSL Client Auth. The code runs perfectly on our local container, but when deployed to docker swarm, it failed with this error:

```
System.IO.IOException: The write operation failed, see inner exception.
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Error while searching for Customers, Error - The operation was canceled.
```

Code:
```c#
                X509Certificate2 x509 = new X509Certificate2(_configuration["ClientCertPathPFX"], _configuration["CertPassword"]);
                HttpClientHandler handler = new HttpClientHandler()
                {
                    ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
                    {                 
                        return errors == SslPolicyErrors.None;                        
                    },
                };

                handler.ClientCertificates.Add(x509);
                handler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12 |
                                        System.Security.Authentication.SslProtocols.Tls11 |
                                        System.Security.Authentication.SslProtocols.Tls;
                var httpClient = new HttpClient(handler);
                var request = new HttpRequestMessage(new HttpMethod("POST"), "API ENDPOINT");
                var requestJson = JsonConvert.SerializeObject(sfdcRequestCustomer);
                request.Headers.TryAddWithoutValidation("accept", "application/json");
                request.Content = new StringContent(requestJson, Encoding.UTF8, "application/json");
                
                var responseRequest = await httpClient.SendAsync(request);
```

**Comment by karelz** [comment]
Triage: These kind of errors may be "normal" - closed connections while write/read are in progress. We need logs to drill down into it.
2.2 is out of support, so please try it on 3.1

Given that there are no answers to above questions https://github.com/dotnet/runtime/issues/31537#issuecomment-557626912 it is not actionable. Closing.
Feel free to reopen when there is more info for us to act on. Thanks.
