### ISSUE TITLE
[mono] Test failed on Helix: System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs__CornerCase_HasElementTypes

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#31648]
`System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs__CornerCase_HasElementTypes` fails on Helix. It will be skipped with `ActiveIssue` in https://github.com/dotnet/runtime/pull/2087

```    System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs__CornerCase_HasElementTypes [FAIL]
      Assert.All() Failure: 10 out of 10 items in the collection did not pass.
      [9]: Item: System.Double*
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [8]: Item: System.Int32*
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [7]: Item: System.Double&
           Xunit.Sdk.AllException: Assert.All() Failure: 9 out of 10 items in the collection did not pass.
           [9]: Item: System.Double*
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [8]: Item: System.Int32*
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [5]: Item: System.Double[,]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [4]: Item: System.Int32[,]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [3]: Item: System.Double[*]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [2]: Item: System.Int32[*]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [1]: Item: System.Double[]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [0]: Item: System.Int32[]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [6]: Item: System.Int32&
           Xunit.Sdk.AllException: Assert.All() Failure: 9 out of 10 items in the collection did not pass.
           [9]: Item: System.Double*
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [8]: Item: System.Int32*
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [5]: Item: System.Double[,]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [4]: Item: System.Int32[,]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [3]: Item: System.Double[*]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [2]: Item: System.Int32[*]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [1]: Item: System.Double[]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [0]: Item: System.Int32[]
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [5]: Item: System.Double[,]
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [4]: Item: System.Int32[,]
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [3]: Item: System.Double[*]
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [2]: Item: System.Int32[*]
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [1]: Item: System.Double[]
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      [0]: Item: System.Int32[]
           Xunit.Sdk.AllException: Assert.All() Failure: 2 out of 10 items in the collection did not pass.
           [7]: Item: System.Double&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
           [6]: Item: System.Int32&
                Xunit.Sdk.TrueException: Assert.True() Failure
                Expected: True
                Actual:   False
                   at Xunit.Assert.True(Nullable`1 condition, String userMessage)
                   at Xunit.Assert.True(Boolean condition)
                   at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_1.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__1(Type t2)
                   at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
              at System.Reflection.Tests.MemberInfoTests.<>c__DisplayClass31_0.<HasSameMetadataDefinitionAs__CornerCase_HasElementTypes>b__0(Type t1)
              at Xunit.Assert.All[Type](IEnumerable`1 collection, Action`1 action)
      Stack Trace:
           at System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs__CornerCase_HasElementTypes()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by danmosemsft** [comment]
Mono runtime issue.
