### ISSUE TITLE
[mono] Test failed on Helix: System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#31649]
`System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath` fails on Helix. It will be skipped with ActiveIssue in #2087.

```
System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 0) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_fhspupwv.kh4/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_649ae850
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 5) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_ezgcvxxh.ng3/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_74e9dbc3
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 50) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_c02d054y.sjs/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_05123eda
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(seek: 100) [FAIL]
      Assert.Contains() Failure
      Not found: /tmp/AssemblyTests_4egqppii.day/LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath_358_3c0ef32a
      In value:  Invalid Image
      Stack Trace:
           at System.AssertExtensions.ThrowsContains[BadImageFormatException](Action action, String expectedMessageContent)
           at System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath(Int32 seek)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by CoffeeFlux** [comment]
See https://github.com/dotnet/runtime/issues/31650#issuecomment-583570898, failures seem to be for the same reason.
