### ISSUE TITLE
[mono] Test failed: System.Tests.GCTests.LatencyRoundtrips*

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#31657]
`System.Tests.GCTests.LatencyRoundtrips` fails on Helix. It will be skipped with ActiveIssue in #2087.

```
    System.Tests.GCTests.LatencyRoundtrips(value: Interactive) [FAIL]
      System.PlatformNotSupportedException : Operation is not supported on this platform.
      Stack Trace:
           at System.Runtime.GCSettings.set_LatencyMode(GCLatencyMode value)
           at System.Tests.GCTests.LatencyRoundtrips(GCLatencyMode value)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Upd.**  
`System.Tests.GCTests.LatencyRoundtrips` and `System.Tests.GCTests.LatencyRoundtrips_LowLatency` also fail on Window 10 due to PNSE:
```
System.Tests.GCTests.LatencyRoundtrips_LowLatency(value: LowLatency) [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\GCSettings.cs(51,0): at System.Runtime.GCSettings.set_LatencyMode(GCLatencyMode value)
    D:\dev\projects\runtime\src\libraries\System.Runtime\tests\System\GCTests.cs(411,0): at System.Tests.GCTests.LatencyRoundtrips(GCLatencyMode value)
    D:\dev\projects\runtime\src\libraries\System.Runtime\tests\System\GCTests.cs(425,0): at System.Tests.GCTests.LatencyRoundtrips_LowLatency(GCLatencyMode value)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
Perhaps, `GCSettings.SetGCLatencyMode` is not implemented.

**Comment by BrzVlad** [comment]
This requires quite a bit of work. We also don't yet support the `TryStartNoGCRegion` api. Currently, such configurations are available only statically via `MONO_GC_PARAMS` env variable. Moving the milestone

**Comment by SamMonoRT** [comment]
Not implementing this in near future until we have an actual user scenario. @BrzVlad @naricc - please confirm and close this issue.

**Comment by naricc** [comment]
I don't know of any user scenario.
