### ISSUE TITLE
[mono] Test failed on Helix: System.Tests.ExitCodeTests.SigTermExitCode

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#31656]
`System.Tests.ExitCodeTests.SigTermExitCode` fails on Helix. It will be skipped with ActiveIssue in #2087.

```
    System.Tests.ExitCodeTests.SigTermExitCode(exitCodeOnSigterm: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   143
      Stack Trace:
           at System.Tests.ExitCodeTests.SigTermExitCode(Nullable`1 exitCodeOnSigterm)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Tests.ExitCodeTests.SigTermExitCode(exitCodeOnSigterm: 42) [FAIL]
      Assert.Equal() Failure
      Expected: 42
      Actual:   143
      Stack Trace:
           at System.Tests.ExitCodeTests.SigTermExitCode(Nullable`1 exitCodeOnSigterm)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by danmosemsft** [comment]
`Environment.ExitCode` is set, then SIGTERM signal is sent. On CoreCLR, the app exits with the specified exit code; on Mono, it returns with 128+SIGTERM. 

I guess it should follow CoreCLR behavior since the docs don't specify that ExitCode won't be respected in these circumstances.

this behavior is defined in the Mono runtime -mono_environment_exitcode_set etc.
