### ISSUE TITLE
Intermittent Internal CLR error 0x80131506 in dotnet pack

### ISSUE THREAD

**Issue by muntyan** [dotnet/runtime#31720]
We intermittently (like once a month, with tens of builds a day) get the following during `dotnet pack` invocation. There is no simple repro (nor a repro at all really, other than "wait for it to happen"), and it's not possible to share the project which hits it. Is there something we could try to help diagnose this?

D:\nerv\hapysql>c:\hyper-cache\devtoolset\dotnet-sdk\3.0.100\dotnet.exe --version
3.1.101

Description: Fatal error. Internal CLR error. (0x80131506)
[07:07:53][Step 3/10]    at System.Array.InternalCreate(Void*, Int32, Int32*, Int32*)
[07:07:53][Step 3/10]    at System.Array.CreateInstance(System.Type, Int32)
[07:07:53][Step 3/10]    at System.Reflection.CustomAttribute.CreateAttributeArrayHelper(System.RuntimeType, Int32)
[07:07:53][Step 3/10]    at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType)
[07:07:53][Step 3/10]    at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeMethodInfo, System.RuntimeType, Boolean)
[07:07:53][Step 3/10]    at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(System.Type, Boolean)
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(System.Reflection.MemberInfo, System.Type, System.Diagnostics.Tracing.EventManifestOptions)
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(System.Type, System.String, System.Diagnostics.Tracing.EventSource, System.Diagnostics.Tracing.EventManifestOptions)
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized()
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource.DoCommand(System.Diagnostics.Tracing.EventCommandEventArgs)
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource.Initialize(System.Guid, System.String, System.String[])
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
[07:07:53][Step 3/10]    at System.Diagnostics.Tracing.EventSource..ctor()
[07:07:53][Step 3/10]    at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.CoreEventSource..cctor()
[07:07:53][Step 3/10]    at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter+<Send>d__19.MoveNext()
[07:07:53][Step 3/10]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.ApplicationInsights.Channel.InMemoryTransmitter+<Send>d__19, Microsoft.ApplicationInsights, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Send>d__19 ByRef)
[07:07:53][Step 3/10]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.ApplicationInsights.Channel.InMemoryTransmitter+<Send>d__19, Microsoft.ApplicationInsights, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<Send>d__19 ByRef)
[07:07:53][Step 3/10]    at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Send(System.Collections.Generic.IEnumerable`1<Microsoft.ApplicationInsights.Channel.ITelemetry>)
[07:07:53][Step 3/10]    at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.DequeueAndSend()
[07:07:53][Step 3/10]    at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()
[07:07:53][Step 3/10]    at System.Threading.Tasks.Task.InnerInvoke()
[07:07:53][Step 3/10]    at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
[07:07:53][Step 3/10]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
[07:07:53][Step 3/10]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
[07:07:53][Step 3/10]    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
[07:07:53][Step 3/10]    at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
[07:07:53][Step 3/10]    at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
[07:07:53][Step 3/10]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
[07:07:53][Step 3/10]    at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by jkotas** [comment]
This is crashing in the runtime. The best way to diagnose this is to enable full crash dump generation for dotnet.exe using instruction here:

https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Once you get the crash dump for the failure, open it in windbg (https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) to see where in the runtime it is crashing exactly.

You can email me (my email is in my github profile) if you are not comfortable sharing the details on github.

**Comment by muntyan** [comment]
I'm afraid enabling dumps is not an option here because of Reasons, so I guess this issue has to be closed. Perhaps I'll get a dump one day...
