### ISSUE TITLE
[mono] AppContext.BaseDirectory is empty in some cases

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#31800]
When I run runtest.py (see `make run-tests-coreclr-all`) with Mono Runtime bits inside the Core_Root it crashes with
```
    Unhandled Exception:
    System.TypeInitializationException: The type initializer for 'Internal.Microsoft.Extensions.DependencyModel.CompilationLibrary' threw an exception.
     ---> System.TypeInitializationException: The type initializer for 'Internal.Microsoft.DotNet.PlatformAbstractions.ApplicationEnvironment' threw an exception.
     ---> System.ArgumentException: The path is empty. (Parameter 'path')
       at System.IO.Path.GetFullPath(String path)
       at Internal.Microsoft.DotNet.PlatformAbstractions.ApplicationEnvironment.GetApplicationBasePath()
       at Internal.Microsoft.DotNet.PlatformAbstractions.ApplicationEnvironment..cctor()
       --- End of inner exception stack trace ---
       at Internal.Microsoft.Extensions.DependencyModel.Resolution.AppBaseCompilationAssemblyResolver..ctor(IFileSystem fileSystem)
       at Internal.Microsoft.Extensions.DependencyModel.Resolution.AppBaseCompilationAssemblyResolver..ctor()
       at Internal.Microsoft.Extensions.DependencyModel.CompilationLibrary..cctor()
```

It looks like [GetBaseDirectoryCore](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/AppContext.cs#L26) returns empty string on first usage (and then a correct string after).

cc @CoffeeFlux

**Comment by EgorBo** [comment]
Workaround in https://github.com/dotnet/runtime/pull/31739/files#diff-de0eb416fb154da3c76ecf6c8f5105fb

**Comment by CoffeeFlux** [comment]
In some cases, the domain's `entry_assembly` appears to be null, including during the first call to `GetEntryAssembly()`.

**Comment by CoffeeFlux** [comment]
The problem appears to be that the assembly preload hook is triggered early, before `prepare_thread_to_exec_main` is run. On netcore, the preload hook includes a call to managed to locate the BaseDirectory, and the icall returns null because `prepare_thread_to_exec_main` is where the `entry_assembly` is actually set.
