### ISSUE TITLE
ExecutionEngineException due to race between thread creation and shutdown

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#31842]
From https://github.com/dotnet/runtime/pull/31756 on `Libraries Test Run release mono Linux x64 Debug` CI leg.

Specifically: netcoreapp5.0-Linux-Debug-x64-Mono_release-Debian.9.Amd64.Open

https://helix.dot.net/api/2019-06-17/jobs/b8f6a868-71db-4bc3-9142-3adb3b512af6/workitems/System.Net.Http.Functional.Tests/console
```text
  Discovering: System.Net.Http.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.Functional.Tests (found 0 of 853 test cases)
=== TEST EXECUTION SUMMARY ===
   System.Net.Http.Functional.Tests.dll  Total: 0

Unhandled Exception:
System.ExecutionEngineException: Couldn't create thread. Runtime is shutting down.
   at System.Threading.Thread.Start()
   at System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread()
   at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker()
   at System.Threading.PortableThreadPool.RequestWorker()
   at System.Threading.ThreadPool.RequestWorkerThread()
   at System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[ERROR] FATAL UNHANDLED EXCEPTION: System.ExecutionEngineException: Couldn't create thread. Runtime is shutting down.
   at System.Threading.Thread.Start()
   at System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread()
   at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker()
   at System.Threading.PortableThreadPool.RequestWorker()
   at System.Threading.ThreadPool.RequestWorkerThread()
   at System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
~/work/B1C609A0/w/9DFE0880/e
----- end Thu Feb 6 03:23:51 UTC 2020 ----- exit code 1 ----------------------------------------------------------
Looking around for any Linux dump...
... found no dump in /home/helixbot/work/B1C609A0/w/9DFE0880/e
+ export _commandExitCode=1
```
https://dev.azure.com/dnceng/public/_build/results?buildId=509474&view=ms.vss-test-web.build-test-results-tab&runId=16167872&paneView=debug&resultId=168275

**Comment by karelz** [comment]
@marek-safar any idea what could be done here?

**Comment by marek-safar** [comment]
Interesting! This looks like shutdown issue, @lambdageek could you take care of that.

I guess as a workaround you could exclude the test suite as it has 0 tests.

**Comment by lambdageek** [comment]
Not sure what's the best way to go here.   The stack trace in this specific issue shows the threadpool starting a new worker.  The threadpool already catches some exceptions - wecould just throw `ThreadStartException` instead of `ExecutionEngineException` for example. https://github.com/dotnet/runtime/blob/79e5e2750c653b93cc1b8b07fbaef289b67e7708/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs#L240-L254
But that wouldn't really solve other shutdown races.

Another option is to just suspend the current thread (not the about-to-be-created thread, but the one that is requesting the thread creation) since we're about to be killed anyway.  That feels like the correct solution.
