### ISSUE TITLE
[mono] Test failed: System.Runtime.Tests.ProfileOptimizationTest.ProfileOptimization_CheckFileExists

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#31853]
`System.Runtime.Tests.ProfileOptimizationTest.ProfileOptimization_CheckFileExists` fails on mono. This test is disabled in CoreFX.issues.rsp file, but it will be moved into its respective xUnit test with ActiveIssue in #2087.

```
System.Runtime.Tests.ProfileOptimizationTest.ProfileOptimization_CheckFileExists [FAIL]
    'ProfileOptimization_CheckFileExists_17_9fc17555' does not exist
        Expected: True
        Actual:   False
        Stack Trace:
             at System.Runtime.Tests.ProfileOptimizationTest.ProfileOptimization_CheckFileExists()
             at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by dakersnar** [comment]
@lambdageek Are you planning on fixing this for 7.0? If now, can you triage this out to Future? Thanks.

**Comment by tannergooding** [comment]
Still disabled and this looks like a genuine feature gap rather than flakiness.

The test is still guarded by `[ActiveIssue("https://github.com/dotnet/runtime/issues/31853", TestRuntimes.Mono)]` in `ProfileOptimization.cs`, and the root cause is that Mono doesn't implement profile optimization (multicore JIT). The `AssemblyLoadContext` methods backing `ProfileOptimization.SetProfileRoot`/`StartProfile` are empty no-ops on Mono:

```csharp
// src/mono/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.Mono.cs
public void SetProfileOptimizationRoot(string directoryPath) { }
public void StartProfileOptimization(string? profile) { }
```

Where-as CoreCLR P/Invokes into `MultiCoreJIT_InternalSetProfileRoot`/`MultiCoreJIT_InternalStartProfile`, which actually write the profile file. Since Mono does nothing, the profile file is never created, so `CheckProfileFileExists` fails after its 5s grace wait -- exactly what the `ActiveIssue` guards against.

So this can''t pass on Mono until multicore JIT profile writing is implemented there (or the test is made conditional on the feature being supported). Retargeting from `area-System.Runtime` to `area-Codegen-JIT-mono` since the gap is in JIT behavior, not the managed API.

> [!NOTE]
> This analysis was generated by GitHub Copilot.
