### ISSUE TITLE
[mono] Test failed: System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest_ChangedInDotNetCore

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#32020]
`System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest_ChangedInDotNetCore` still fails on mono. It was disabled twice - the first time using `SkipOnTargetFramework` attribute (removed in https://github.com/dotnet/runtime/pull/31920) and the second time in the rsp file. I will move this test into its respective xUnit test with an active issue in #2087.

```
System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest_ChangedInDotNetCore [FAIL]
    Assert.Equal() Failure
    Expected: 1
    Actual:   0
    Stack Trace:
        /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(181,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.VerifyMinThreads(Int32 expectedMinw, Int32 expectedMinc)
        /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(163,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.SetMinMaxThreadsTest_ChangedInDotNetCore()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by danmosemsft** [comment]
Is this because Mono is using "portable thread pool" ?
