### ISSUE TITLE
[mono] Flaky tests: System.ComponentModel.Composition.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#32030]
I have no repro for this test locally, but it fails on `runtime (Libraries Test Run release mono OSX x64 Debug)` lane in https://github.com/dotnet/runtime/pull/2087.

```
      System.NotSupportedException : Interface 'System.ComponentModel.Composition.ITrans_StronglyTypedStructure' is not a valid MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain members that are not properties.
      ---- System.TypeLoadException : Could not load type '_proxy_System.ComponentModel.Composition.ITrans_StronglyTypedStructure_193e0f9f-5ac0-45e4-859f-299ce861709f' from assembly ''.
      Stack Trace:
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs(45,0): at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[ITrans_StronglyTypedStructure](IDictionary`2 metadata)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModelServices.cs(24,0): at System.ComponentModel.Composition.AttributedModelServices.GetMetadataView[ITrans_StronglyTypedStructure](IDictionary`2 metadata)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ExportServices.cs(98,0): at System.ComponentModel.Composition.ExportServices.CreateStronglyTypedLazyOfTM[BasicTestComponent,ITrans_StronglyTypedStructure](Export export)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(769,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportCore[BasicTestComponent,ITrans_StronglyTypedStructure](String contractName)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(214,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExport[BasicTestComponent,ITrans_StronglyTypedStructure](String contractName)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(163,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExport[BasicTestComponent,ITrans_StronglyTypedStructure]()
        /_/src/libraries/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/ExportableAttributeTests.cs(67,0): at System.ComponentModel.Composition.MetadataAttributeTests.StronglyTypedStructureTestWithTransparentViews()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(2292,0): at System.RuntimeType.GetMethodsByName(String name, BindingFlags bindingAttr, MemberListType listType, RuntimeType reflectedType)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(592,0): at System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Int32 genericParamCount, Boolean allowPrefixLookup)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(813,0): at System.RuntimeType.GetMethodImpl(String name, Int32 genericParamCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(806,0): at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
        /_/src/libraries/System.Private.CoreLib/src/System/Type.cs(166,0): at System.Type.GetMethod(String name, BindingFlags bindingAttr)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewGenerator.cs(122,0): at System.ComponentModel.Composition.MetadataViewGenerator.GetMetadataViewFactory(Type viewType)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs(41,0): at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[ITrans_StronglyTypedStructure](IDictionary`2 metadata)
```

Runfo Tracking Issue: [tests.integration.recompositiontests.recomposition_integrationtest](https://runfo.azurewebsites.net/tracking/issue/117)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[942084](https://dev.azure.com/dnceng/public/_build/results?buildId=942084)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46691](https://github.com/dotnet/runtime/pull/46691)|net6.0-Linux-Debug-x64-Mono_release-Ubuntu.1604.Amd64.Open|
|[942062](https://dev.azure.com/dnceng/public/_build/results?buildId=942062)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46711](https://github.com/dotnet/runtime/pull/46711)|net6.0-Linux-Debug-x64-mono_interpreter_release-Debian.9.Amd64.Open|
|[941924](https://dev.azure.com/dnceng/public/_build/results?buildId=941924)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46702](https://github.com/dotnet/runtime/pull/46702)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7|
|[941873](https://dev.azure.com/dnceng/public/_build/results?buildId=941873)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46693](https://github.com/dotnet/runtime/pull/46693)|net6.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|
|[941614](https://dev.azure.com/dnceng/public/_build/results?buildId=941614)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46687](https://github.com/dotnet/runtime/pull/46687)|net6.0-Linux-Debug-arm64-Mono_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-bfcd90a-20200127194925|
|[941559](https://dev.azure.com/dnceng/public/_build/results?buildId=941559)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46680](https://github.com/dotnet/runtime/pull/46680)|net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|
|[941559](https://dev.azure.com/dnceng/public/_build/results?buildId=941559)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46680](https://github.com/dotnet/runtime/pull/46680)|net6.0-Linux-Debug-x64-Mono_release-Ubuntu.1804.Amd64.Open|
|[941555](https://dev.azure.com/dnceng/public/_build/results?buildId=941555)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46647](https://github.com/dotnet/runtime/pull/46647)|net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|
|[941523](https://dev.azure.com/dnceng/public/_build/results?buildId=941523)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46157](https://github.com/dotnet/runtime/pull/46157)|net6.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|8|8|8|

**Comment by danmosemsft** [comment]
#32295

**Comment by eerhardt** [comment]
I hit this again on two different legs of my PR here:

https://dev.azure.com/dnceng/public/_build/results?buildId=941614&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=22b0078b-0469-5ba6-8725-2121fdbae049&l=71

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46687-merge-eaad8ef0e0164fb1a5/System.ComponentModel.Composition.Tests/console.5b5b0056.log?sv=2019-07-07&se=2021-01-27T18%3A42%3A33Z&sr=c&sp=rl&sig=0hGXpKBmBk%2BxtlgMoG%2BMNxv66tG8kK5dYUViM4G34jA%3D

```
===========================================================================================================
/private/tmp/helix/working/C0BC09C3/w/9AB30851/e /private/tmp/helix/working/C0BC09C3/w/9AB30851/e
  Discovering: System.ComponentModel.Composition.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.Composition.Tests (found 1423 of 1588 test cases)
  Starting:    System.ComponentModel.Composition.Tests (parallel test collections = on, max threads = 12)
/Users/runner/work/1/s/src/mono/mono/eglib/ghashtable.c:334: assertion 'hash != NULL' failed

/Users/runner/work/1/s/src/mono/mono/eglib/ghashtable.c:238: assertion 'hash != NULL' failed

    Tests.Integration.ExportFactoryTests.ExportFactoryStandardImports_ShouldWorkProperly [FAIL]
      System.NotSupportedException : Interface 'Tests.Integration.ExportFactoryTests+IIdTypeMetadata' is not a valid MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain members that are not properties.
      ---- System.TypeLoadException : Could not load type '_proxy_Tests.Integration.ExportFactoryTests+IIdTypeMetadata_fd7e9c79-c5a5-4130-bc52-0e379f05ff35' from assembly ''.
      Stack Trace:
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs(44,0): at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IIdTypeMetadata](IDictionary`2 metadata)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModelServices.cs(23,0): at System.ComponentModel.Composition.AttributedModelServices.GetMetadataView[IIdTypeMetadata](IDictionary`2 metadata)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ExportfactoryCreator.cs(70,0): at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.CreateStronglyTypedExportFactoryOfTM[IId,IIdTypeMetadata](Export export)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ExportfactoryCreator.cs(44,0): at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass4_0.<CreateStronglyTypedExportFactoryFactory>b__0(Export e)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs(95,0): at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs(88,0): at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToSingleImportType(Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs(44,0): at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs(242,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs(204,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.PartManager.cs(79,0): at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(477,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(345,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(436,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(171,0): at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServices.cs(550,0): at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CatalogExportProvider.cs(542,0): at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CatalogExportProvider.CatalogExport.cs(59,0): at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Primitives/Export.cs(204,0): at System.ComponentModel.Composition.Primitives.Export.get_Value()
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ExportServices.cs(140,0): at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[ExportFactoryImporter](Export export)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(732,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[ExportFactoryImporter](String contractName, ImportCardinality cardinality)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(528,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[ExportFactoryImporter](String contractName)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ExportProvider.GetExportOverrides.cs(478,0): at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValue[ExportFactoryImporter]()
        /_/src/libraries/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/ExportFactoryTests.cs(133,0): at Tests.Integration.ExportFactoryTests.ExportFactoryStandardImports_ShouldWorkProperly()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(1858,0): at System.RuntimeType.GetMethodsByName(String name, BindingFlags bindingAttr, MemberListType listType, RuntimeType reflectedType)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(564,0): at System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Int32 genericParamCount, Boolean allowPrefixLookup)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(794,0): at System.RuntimeType.GetMethodImpl(String name, Int32 genericParamCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(786,0): at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
        /_/src/libraries/System.Private.CoreLib/src/System/Type.cs(242,0): at System.Type.GetMethod(String name, BindingFlags bindingAttr)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewGenerator.cs(121,0): at System.ComponentModel.Composition.MetadataViewGenerator.GetMetadataViewFactory(Type viewType)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs(40,0): at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IIdTypeMetadata](IDictionary`2 metadata)
  Finished:    System.ComponentModel.Composition.Tests
=== TEST EXECUTION SUMMARY ===
   System.ComponentModel.Composition.Tests  Total: 1423, Errors: 0, Failed: 1, Skipped: 0, Time: 0.911s
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46687-merge-880c3358457c412b96/System.ComponentModel.Composition.Tests/console.01731f34.log?sv=2019-07-07&se=2021-01-27T19%3A27%3A50Z&sr=c&sp=rl&sig=QOPUaD8l%2BNhnCgQav%2B4lQACpAbUDq0ulvXzK%2F38x%2BBc%3D

```
===========================================================================================================
/root/helix/work/workitem /root/helix/work/workitem
  Discovering: System.ComponentModel.Composition.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.Composition.Tests (found 1423 of 1588 test cases)
  Starting:    System.ComponentModel.Composition.Tests (parallel test collections = on, max threads = 6)
/__w/1/s/src/mono/mono/eglib/ghashtable.c:334: assertion 'hash != NULL' failed

/__w/1/s/src/mono/mono/eglib/ghashtable.c:238: assertion 'hash != NULL' failed

    Tests.Integration.RecompositionTests.Recomposition_IntegrationTest [FAIL]
      System.NotSupportedException : Interface 'Tests.Integration.RecompositionTests+IRelationshipView' is not a valid MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain members that are not properties.
      ---- System.TypeLoadException : Could not load type '_proxy_Tests.Integration.RecompositionTests+IRelationshipView_830d7dc0-89c8-42b4-8d3f-686962821a7f' from assembly ''.
      Stack Trace:
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs(44,0): at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IRelationshipView](IDictionary`2 metadata)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModelServices.cs(23,0): at System.ComponentModel.Composition.AttributedModelServices.GetMetadataView[IRelationshipView](IDictionary`2 metadata)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ExportServices.cs(97,0): at System.ComponentModel.Composition.ExportServices.CreateStronglyTypedLazyOfTM[String,IRelationshipView](Export export)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs(95,0): at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs(63,0): at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToCollectionImportType(Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs(40,0): at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs(242,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs(204,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.PartManager.cs(79,0): at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(477,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(357,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(436,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(171,0): at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ComposablePartExportProvider.cs(314,0): at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.<>c__DisplayClass19_0.<Compose>b__0()
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServices.cs(577,0): at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ComposablePartExportProvider.cs(313,0): at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionContainer.cs(396,0): at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
        /_/src/libraries/System.ComponentModel.Composition/tests/System/Integration/RecompositionTests.cs(297,0): at Tests.Integration.RecompositionTests.Recomposition_IntegrationTest()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(1858,0): at System.RuntimeType.GetMethodsByName(String name, BindingFlags bindingAttr, MemberListType listType, RuntimeType reflectedType)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(564,0): at System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Int32 genericParamCount, Boolean allowPrefixLookup)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(794,0): at System.RuntimeType.GetMethodImpl(String name, Int32 genericParamCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs(786,0): at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
        /_/src/libraries/System.Private.CoreLib/src/System/Type.cs(242,0): at System.Type.GetMethod(String name, BindingFlags bindingAttr)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewGenerator.cs(121,0): at System.ComponentModel.Composition.MetadataViewGenerator.GetMetadataViewFactory(Type viewType)
        /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs(40,0): at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IRelationshipView](IDictionary`2 metadata)
  Finished:    System.ComponentModel.Composition.Tests
=== TEST EXECUTION SUMMARY ===
   System.ComponentModel.Composition.Tests  Total: 1423, Errors: 0, Failed: 1, Skipped: 0, Time: 2.189s
```

**Comment by safern** [comment]
Accidentally closed it from runfo.

**Comment by danmosemsft** [comment]
I hit it just now too.

**Comment by danmosemsft** [comment]
Either I’m looking at the wrong test or this issue should not have the disabled test label on it

**Comment by safern** [comment]
> Either I’m looking at the wrong test or this issue should not have the disabled test label on it

Maybe your build checked out before the PR to disable it was merged? https://github.com/dotnet/runtime/pull/46699

**Comment by danmosemsft** [comment]
That's it. I was confused because this issue got a disabled test label months ago. I guess now it's true :)

**Comment by safern** [comment]
Test is disabled, moving to Future.
