### ISSUE TITLE
System.Diagnostics.Tests.EventLogSourceCreationTests.CheckSourceExistenceAndDeletion failing on net472

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32241]
System.Diagnostics.Tests.EventLogSourceCreationTests.CheckSourceExistenceAndDeletion

Configuration: `net472-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`

```
System.AggregateException : One or more errors occurred.\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning\r\n---- System.ComponentModel.Win32Exception : A device attached to the system is not functioning
  at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 45
   at System.Diagnostics.Tests.Helpers.Retry[T](Func`1 func) in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 46
   at System.Diagnostics.Tests.EventLogSourceCreationTests.CheckSourceExistenceAndDeletion() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogTests/EventLogSourceCreationTests.cs:line 25
----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear()
   at System.Diagnostics.EventLog.Delete(String logName, String machineName)
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 43
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #2 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear()
   at System.Diagnostics.EventLog.Delete(String logName, String machineName)
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 43
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #3 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear()
   at System.Diagnostics.EventLog.Delete(String logName, String machineName)
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 43
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #4 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear()
   at System.Diagnostics.EventLog.Delete(String logName, String machineName)
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 43
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #5 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear()
   at System.Diagnostics.EventLog.Delete(String logName, String machineName)
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass7_0.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 34
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass8_0`1.<Retry>b__0() in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 43
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/libraries/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #6 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.EventLogInternal.Clear()
   at S
```

cc @danmosemsft @stephentoub

**Comment by ViktorHofer** [comment]
Failing on netcoreapp5.0 as well: https://dnceng.visualstudio.com/public/_build/results?buildId=523860&view=ms.vss-test-web.build-test-results-tab&runId=16588824&resultId=178919&paneView=debug

**Comment by ViktorHofer** [comment]
Closing as we decided to turn these tests off during CI: https://github.com/dotnet/runtime/pull/32501
