### ISSUE TITLE
System.Threading.Tasks.Tests.ValueTaskTests.Generic_Awaiter_ContinuesOnCapturedContext failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32246]
https://dnceng.visualstudio.com/public/_build/results?buildId=517446&view=ms.vss-test-web.build-test-results-tab&runId=16371898&paneView=debug

Configuration: `netcoreapp5.0-Linux-Release-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open`

```
Assert.True() Failure\nExpected: True\nActual: False
   at System.Threading.Tasks.Tests.ValueTaskTests.<>c__DisplayClass46_0.<Generic_Awaiter_ContinuesOnCapturedContext>b__0() in /_/src/libraries/System.Threading.Tasks.Extensions/tests/ValueTaskTests.cs:line 818
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2370
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2356
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 289
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 314
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2320
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Tests.ValueTaskTests.Generic_Awaiter_ContinuesOnCapturedContext(CtorMode mode, Boolean sync) in /_/src/libraries/System.Threading.Tasks.Extensions/tests/ValueTaskTests.cs:line 805
--- End of stack trace from previous location ---
```

cc @tarekgh @stephentoub

**Comment by stephentoub** [comment]
The assert failure is a 10 second timeout, presumably also because of the checked run:
https://github.com/dotnet/runtime/blob/fddce702c2ff94c6ca05e401cfb0eb1944083767/src/libraries/System.Threading.Tasks.Extensions/tests/ValueTaskTests.cs#L818

**Comment by ViktorHofer** [comment]
Would you mind sending a PR to skip the test on Checked if testing on the other configurations is sufficient in this case?
