### ISSUE TITLE
AppContext switch test with RemoteExecutor failing in mono

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#32316]
AppContext switch test with RemoteExecutor failing on CI legs Linux-mono, Mac-mono. 
More info: https://github.com/dotnet/runtime/pull/32149#issuecomment-586294701
Failure log:
```
Child exception:
  System.IO.InvalidDataException: A local file header is corrupt.
   at System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable(Boolean needToUncompress, Boolean needToLoadIntoMemory) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs:line 595
   at System.IO.Compression.ZipArchiveEntry.OpenInReadMode(Boolean checkOpenable) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs:line 667
   at System.IO.Compression.ZipArchiveEntry.Open() in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs:line 294
   at System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles.<>c.<ZipArchiveEntry_AppContext_Switch_SuppresHeaderValidation>b__6_0(String suppressString) in /_/src/libraries/System.IO.Compression/tests/ZipArchive/zip_InvalidParametersAndStrangeFiles.cs:line 151
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339

Child process:
  System.IO.Compression.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.IO.Compression.Tests.zip_InvalidParametersAndStrangeFiles+<>c Void <ZipArchiveEntry_AppContext_Switch_SuppresHeaderValidation>b__6_0(System.String)

Child arguments:
  True
```

**Comment by ericstj** [comment]
Could be related to when mono is running the static constructor which reads appcontext.  Test isn't guaranteeing that the switch is set before running code which might touch that static constructor.

**Comment by danmosemsft** [comment]
@buyaa-n -- I cannot find any test disabled for this issue, nor a test by this name, nor indeed any compression test disabled for Mono.

**Comment by buyaa-n** [comment]
Yes, we are not using AppContext switch anymore and the test has removed,
