### ISSUE TITLE
System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 fails on netcoreapp5.0-OSX-Debug-x64-Mono_release-OSX.1013.Amd64.Open

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#32378]
From https://github.com/dotnet/runtime/pull/32364 on `Libraries Test Run release mono OSX x64 Debug`

https://helix.dot.net/api/2019-06-17/jobs/59718cf0-1d40-40b2-b716-663c48ea7d8f/workitems/System.Drawing.Common.Tests/console

https://dev.azure.com/dnceng/public/_build/results?buildId=522989&view=ms.vss-test-web.build-test-results-tab&runId=16564108&paneView=debug&resultId=111012

```text
Error message
Assert.True() Failure\nExpected: True\nActual: False


Stack trace
   at System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6() in /_/src/libraries/System.Drawing.Common/tests/GdiplusTests.cs:line 17
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
```

**Comment by ViktorHofer** [comment]
Closing, machines were updated.
