### ISSUE TITLE
[mono] Test failed: System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#32433]
I tried to enable it in #2087 and it failed on CI. I haven't got a local failure on macos.

```
      Assert.NotNull() Failure
      Stack Trace:
        /_/src/libraries/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs(105,0): at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by CoffeeFlux** [comment]
Failure appears to be the result of us not properly calling the managed events. Somehow this regressed with the migration to dotnet/runtime...

My guess would be that this is the reason all the various ALC tests started failing, but I haven't checked anything but this test so far.

Sample program:

```
using System;
using System.Runtime.Loader;
using System.Reflection;
using System.IO;

namespace HelloWorld
{
    public class SecondaryLoadContext : AssemblyLoadContext
    {
        protected override Assembly Load(AssemblyName assemblyName)
        {
            return null;
        }
    }

    class Program
    {
        private const string TestAssemblyName = "System.Runtime.Loader.Noop.Assembly";

        private static Assembly ResolveAssembly(AssemblyLoadContext sender, AssemblyName assembly)
        {
            string resolvedAssemblyPath = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), assembly.Name + "_test.dll");
            Console.WriteLine("HELLO WORLD");

            return sender.LoadFromAssemblyPath(resolvedAssemblyPath);
        }

        static void Main(string[] args)
        {
            // This will attempt to load an assembly, by path, in the Default Load context via the Resolving event
            var assemblyName = new AssemblyName(TestAssemblyName);

            // By default, the assembly should not be found in DefaultContext at all
            //Assembly.Load(assemblyName);

            // Create a secondary load context and wireup its resolving event
            SecondaryLoadContext slc = new SecondaryLoadContext();
            slc.Resolving += ResolveAssembly;

            // Attempt to load the assembly in secondary load context
            var slcLoadedAssembly = slc.LoadFromAssemblyName(assemblyName);

            // We should have successfully loaded the assembly in secondary load context.
            Console.WriteLine(slcLoadedAssembly != null);
        }
    }
}
```

**Comment by CoffeeFlux** [comment]
Caused by this change: https://github.com/dotnet/runtime/commit/7c6ec46a637017971d3eaa210fd2b6e4d4a6b737#diff-53c474033a1751601becf0eb958fcb5dL287-R287
