### ISSUE TITLE
VS Test Explorer not running tests

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#32544]
Even when a solution is opened with `build.cmd -vs System.Net.Http`, the tests cannot be run from Test Explorer. They are visible, I can click on run, but nothing is actually executed.
The output window shows this error:
```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      3.1.1 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
```

<details>

```
[19.02.2020 5:50:25.039 odp.] ---------- Discovery started ----------
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      3.1.1 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x86&rid=win10-x86
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
[19.02.2020 5:50:25.682 odp.] ========== Discovery aborted: 0 tests found (0:00:00,6427201) ==========
[19.02.2020 5:50:25.933 odp.] ---------- Run started ----------
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      3.1.1 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x86&rid=win10-x86
. Please check the diagnostic logs for more information.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      3.1.1 at [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x86&rid=win10-x86
. Please check the diagnostic logs for more information.
[19.02.2020 5:50:26.242 odp.] ========== Run aborted: 0 tests run (0:00:00,0743818) ==========
```

</details>

**Comment by ViktorHofer** [comment]
Switch the Architecture to x64 in the VS Test Explorer Settings. VS Test Explorer tries to run with dotnet x86.

**Comment by ManickaP** [comment]
I'd say that this is more of doc issue than. I've found this page https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing-vs.md. But it seems that it got wrongly moved during the whole consolidation process:
1. docs/installer/building/Running-Tests-In-VisualStudio-IDE.md → docs/workflow/testing/Running-Tests-In-VisualStudio-IDE.md in https://github.com/dotnet/runtime/pull/251/
2. docs/workflow/testing/Running-Tests-In-VisualStudio-IDE.md → docs/workflow/testing/libraries/testing-vs.md in https://github.com/dotnet/runtime/pull/1159

So I think this document rather belongs to `installer` folder and I could either add this `-vs` info into https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md or create a new doc like the one for the installer. WDYT? I can do it once we agree.

**Comment by ViktorHofer** [comment]
FWIW I believe that VS Test Explorer will stop defaulting to x86 in a future update and just pick the machine architecture.

> So I think this document rather belongs to installer folder and I could either add this -vs info into https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md

Yes that sounds like a good plan. We should move the vs switch information into there and remove the other wrongly moved document "testing-vs.md".

Thanks a lot for helping
