### ISSUE TITLE
"Mono LLVM Product Build Linux x64 debug" CI leg failed during building with System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#32638]
From https://github.com/dotnet/runtime/pull/32636 `Mono LLVM Product Build Linux x64 debug` failing during the `Build product` phase.

https://dev.azure.com/dnceng/public/_build/results?buildId=530946&view=results

See https://dev.azure.com/dnceng/public/_build/results?buildId=530946&view=logs&j=a9d8e986-d894-500e-79d4-4a88b1039057&t=4835cc46-49c6-5213-813e-e1366a383450

```text
2020-02-21T03:29:21.5347113Z   Tools restore was successful.
2020-02-21T03:29:24.7336828Z   Restore completed in 3.18 sec for /__w/2/s/.packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20117.3/tools/Tools.proj.
2020-02-21T03:29:25.2704009Z   Restore completed in 12.65 ms for /__w/2/s/src/mono/netcore/System.Private.CoreLib/System.Private.CoreLib.csproj.
2020-02-21T03:29:26.1001157Z   Restore completed in 12.7 ms for /__w/2/s/src/mono/netcore/nuget/packages.builds.
2020-02-21T03:29:26.1004125Z   Restore completed in 14.42 ms for /__w/2/s/src/mono/netcore/nuget/Microsoft.NETCore.Runtime.Mono/Microsoft.NETCore.Runtime.Mono.builds.
2020-02-21T03:29:26.1094057Z /__w/2/s/src/mono/llvm/llvm-init.proj : error : System.AggregateException: One or more errors occurred. (Could not find a part of the path '/tmp/NuGetScratch/fd783170d75748c3b946cf9ec08a3513/420c592af0494c71ac503a54fb38362c.proj.nuget.dgspec.json'.)
2020-02-21T03:29:26.1096996Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/NuGetScratch/fd783170d75748c3b946cf9ec08a3513/420c592af0494c71ac503a54fb38362c.proj.nuget.dgspec.json'.
2020-02-21T03:29:26.1101129Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2020-02-21T03:29:26.1102891Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2020-02-21T03:29:26.1104928Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2020-02-21T03:29:26.1107069Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at System.IO.FileStream..ctor(String path, FileMode mode)
2020-02-21T03:29:26.1108884Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.ProjectModel.DependencyGraphSpec.Save(String path)
2020-02-21T03:29:26.1111033Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.NoOpRestoreUtilities.PersistDGSpecFile(DependencyGraphSpec spec, String dgPath, ILogger log)
2020-02-21T03:29:26.1114054Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreCommand.EvaluateCacheFile()
2020-02-21T03:29:26.1116005Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
2020-02-21T03:29:26.1118032Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2020-02-21T03:29:26.1119896Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
2020-02-21T03:29:26.1121296Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable`1 restoreRequests, RestoreArgs restoreContext)
2020-02-21T03:29:26.1122162Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    --- End of inner exception stack trace ---
2020-02-21T03:29:26.1127582Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2020-02-21T03:29:26.1129520Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
2020-02-21T03:29:26.1251943Z ##[error]src/mono/llvm/llvm-init.proj(0,0): error : System.AggregateException: One or more errors occurred. (Could not find a part of the path '/tmp/NuGetScratch/fd783170d75748c3b946cf9ec08a3513/420c592af0494c71ac503a54fb38362c.proj.nuget.dgspec.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/NuGetScratch/fd783170d75748c3b946cf9ec08a3513/420c592af0494c71ac503a54fb38362c.proj.nuget.dgspec.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at NuGet.ProjectModel.DependencyGraphSpec.Save(String path)
   at NuGet.Commands.NoOpRestoreUtilities.PersistDGSpecFile(DependencyGraphSpec spec, String dgPath, ILogger log)
   at NuGet.Commands.RestoreCommand.EvaluateCacheFile()
   at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
   at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
   at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
   at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable`1 restoreRequests, RestoreArgs restoreContext)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
2020-02-21T03:29:26.1267402Z /__w/2/s/src/mono/llvm/llvm-init.proj : error MSB4236: The SDK 'Microsoft.Build.NoTargets' specified could not be found.
2020-02-21T03:29:26.1271033Z ##[error]src/mono/llvm/llvm-init.proj(0,0): error MSB4236: The SDK 'Microsoft.Build.NoTargets' specified could not be found.
2020-02-21T03:29:26.1271804Z 
2020-02-21T03:29:26.1272225Z Build FAILED.
2020-02-21T03:29:26.1272465Z 
2020-02-21T03:29:26.1273595Z /__w/2/s/src/mono/llvm/llvm-init.proj : error : System.AggregateException: One or more errors occurred. (Could not find a part of the path '/tmp/NuGetScratch/fd783170d75748c3b946cf9ec08a3513/420c592af0494c71ac503a54fb38362c.proj.nuget.dgspec.json'.)
2020-02-21T03:29:26.1274839Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/NuGetScratch/fd783170d75748c3b946cf9ec08a3513/420c592af0494c71ac503a54fb38362c.proj.nuget.dgspec.json'.
2020-02-21T03:29:26.1276040Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
2020-02-21T03:29:26.1276998Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
2020-02-21T03:29:26.1277958Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2020-02-21T03:29:26.1278758Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at System.IO.FileStream..ctor(String path, FileMode mode)
2020-02-21T03:29:26.1279734Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.ProjectModel.DependencyGraphSpec.Save(String path)
2020-02-21T03:29:26.1281313Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.NoOpRestoreUtilities.PersistDGSpecFile(DependencyGraphSpec spec, String dgPath, ILogger log)
2020-02-21T03:29:26.1283278Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreCommand.EvaluateCacheFile()
2020-02-21T03:29:26.1284620Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
2020-02-21T03:29:26.1285649Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
2020-02-21T03:29:26.1286513Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
2020-02-21T03:29:26.1287643Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable`1 restoreRequests, RestoreArgs restoreContext)
2020-02-21T03:29:26.1288755Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    --- End of inner exception stack trace ---
2020-02-21T03:29:26.1289685Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2020-02-21T03:29:26.1291302Z /__w/2/s/src/mono/llvm/llvm-init.proj : error :    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
2020-02-21T03:29:26.1292190Z /__w/2/s/src/mono/llvm/llvm-init.proj : error MSB4236: The SDK 'Microsoft.Build.NoTargets' specified could not be found.
2020-02-21T03:29:26.1292624Z     0 Warning(s)
2020-02-21T03:29:26.1292944Z     2 Error(s)
2020-02-21T03:29:26.1293253Z 
2020-02-21T03:29:26.1293518Z Time Elapsed 00:00:28.69
2020-02-21T03:29:26.1784477Z ##[error](NETCORE_ENGINEERING_TELEMETRY=Build) Build failed (exit code '1').
2020-02-21T03:29:26.1861019Z ##[error]Bash exited with code '1'.
2020-02-21T03:29:26.2305654Z ##[section]Finishing: Build product
```

cc @dotnet/dnceng, @ViktorHofer

**Comment by akoeplinger** [comment]
Also happened in https://github.com/dotnet/runtime/pull/32644.

**Comment by riarenas** [comment]
https://github.com/NuGet/Home/issues/9199

**Comment by danmosemsft** [comment]
Nuget issue above
