### ISSUE TITLE
Cannot find file System.Security.Cryptography.Csp in .NET Core WPF app

### ISSUE THREAD

**Issue by Rinacm** [dotnet/runtime#32650]
Exception message below:
```
System.IO.FileNotFoundException: 
File name: 'System.Security.Cryptography.Csp, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Pixeval.Objects.Cipher.Md5Hex(String input)
   at Pixeval.Persisting.Authentication.Authenticate(String name, String pwd)
   at Pixeval.Persisting.Identity.RefreshIfRequired()
   at Pixeval.UI.SignIn.SignIn_OnInitialized(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Pixeval.App.Main()
```

System Information: Window10 1909 x64 , os version 18363.657, the app is published as self-contained&single file, based on .NET Core 3.0, this issue happened on some of computers and some will not

**Comment by bartonjs** [comment]
Ideally you wouldn't be using any types from the CSP package.  (e.g. for MD5, use `MD5.Create()`, not `new MD5CryptoServiceProvider()`).

But also ideally things should just work.  @ericstj / @safern, any ideas?

**Comment by ericstj** [comment]
> published as self-contained&single file

That means it should have CSP inside it.

I can't imagine what would make this machine-specific if the app is self-contained.

Could be issue with CSP being loaded in the single-file case.  @swaroop-sridhar @jeffschwMSFT can you suggest some host/loader logging that would help @Rinacm debug on the failing machine?

**Comment by swaroop-sridhar** [comment]
@bartonjs does the failure only happen when published single file? What happens when the app is published self-contained, but not single file? 

Can you please check the following: 
1) Publish the app as a self-contained app, and verify that `System.Security.Cryptography.Csp.dll` exists in the publish folder.

2) Publish the app as a self-contained app, single-file app, and run it. Inspect the contents of `%temp%\.net\<app-name>\<hash>\` directory  and check whether `System.Security.Cryptography.Csp.dll` is extracted there.

Thanks.
