### ISSUE TITLE
Test failure in JIT\Intrinsics\TypeIntrinsics_ro\TypeIntrinsics_ro.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32725]
Job: 
[runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16936268&resultId=101892&paneView=debug)

releated tests:
JIT\\Intrinsics\\TypeIntrinsics_ro\\TypeIntrinsics_ro.cmd
JIT\\Intrinsics\\TypeIntrinsics_r\\TypeIntrinsics_r.cmd

Error message:
`
Error: Operation is not valid due to the current state of the object.\r\nSystem.InvalidOperationException: Operation is not valid due to the current state of the object.\r\n at Internal.TypeSystem.LayoutInt.get_AsInt() in F:\workspace\_work\1\s\src\coreclr\src\tools\Common\TypeSystem\Common\LayoutInt.cs:line 50\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.TypeHandle.GetSize() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 71\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.TransitionBlock.ComputeReturnValueTreatment(CorElementType type, TypeHandle thRetType, Boolean isVarArgMethod, Boolean& usesRetBuffer, UInt32& fpReturnSize) in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\TransitionBlock.cs:line 327\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.ComputeReturnFlags() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 1681\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.HasRetBuffArg() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 590\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetNextOffset() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 744\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.ForceSigWalk() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 1404\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.SizeOfArgStack() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 541\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.SizeOfFrameArgumentArray() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\ArgIterator.cs:line 554\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapBuilder.GetCallRefMap(MethodDesc method, Boolean isUnboxingStub) in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\GCRefMapBuilder.cs:line 99\r\n at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapNode.GetData(NodeFactory factory, Boolean relocsOnly) in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\GCRefMapNode.cs:line 97\r\n at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\CodeGen\ReadyToRunObjectWriter.cs:line 157\r\n at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObject(String objectFilePath, EcmaModule componentModule, IEnumerable`1 nodes, NodeFactory factory, Boolean generateMapFile) in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\CodeGen\ReadyToRunObjectWriter.cs:line 293\r\n at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\ILCompiler.ReadyToRun\Compiler\ReadyToRunCodegenCompilation.cs:line 240\r\n at ILCompiler.Program.Run() in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\crossgen2\Program.cs:line 375\r\n at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) in F:\workspace\_work\1\s\src\coreclr\src\tools\crossgen2\crossgen2\Program.cs:line 471\r\n\r\nReturn code: 1\r\
`

**Comment by v-haren** [comment]
also failed in test: 
JIT\\Stress\\ABI\\pinvokes_d\\pinvokes_d.cmd
JIT\\Stress\\ABI\\tailcalls_do\\tailcalls_do.cmd
JIT\\Stress\\ABI\\tailcalls_d\\tailcalls_d.cmd
JIT\\Stress\\ABI\\pinvokes_do\\pinvokes_do.cmd
JIT\\Stress\\ABI\\stubs_do\\stubs_do.cmd

**Comment by karelz** [comment]
@v-haren please only 1 area label per issue - see [why](https://github.com/dotnet/runtime/blob/master/docs/project/issue-guide.md#motivation-for-triage-rules).

**Comment by AriNuer** [comment]
Tests failed in same error here: [runtime-coreclr crossgen2 #20200303.1](https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=results)

**Failed tests:**
```
JIT/Stress/ABI/tailcalls_do/tailcalls_do.sh
JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh
JIT/Stress/ABI/stubs_do/stubs_do.sh
JIT/Stress/ABI/tailcalls_d/tailcalls_d.sh
JIT/Intrinsics/TypeIntrinsics_r/TypeIntrinsics_r.sh
JIT/Intrinsics/TypeIntrinsics_ro/TypeIntrinsics_ro.sh
JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh
```

**Error message**
`
Error: Operation is not valid due to the current state of the object.\nSystem.InvalidOperationException: Operation is not valid due to the current state of the object.\n at Internal.TypeSystem.LayoutInt.get_AsInt() in /__w/10/s/src/coreclr/src/tools/Common/TypeSystem/Common/LayoutInt.cs:line 50\n at Internal.JitInterface.SystemVStructClassificator.GetSystemVAmd64PassStructInRegisterDescriptor(TypeDesc typeDesc, SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR& structPassInRegDescPtr) in /__w/10/s/src/coreclr/src/tools/Common/JitInterface/SystemVStructClassificator.cs:line 99\n at ILCompiler.DependencyAnalysis.ReadyToRun.TransitionBlock.ComputeReturnValueTreatment(CorElementType type, TypeHandle thRetType, Boolean isVarArgMethod, Boolean& usesRetBuffer, UInt32& fpReturnSize) in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/TransitionBlock.cs:line 272\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.ComputeReturnFlags() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 1681\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.HasRetBuffArg() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 590\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetNextOffset() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 744\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.ForceSigWalk() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 1404\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.SizeOfArgStack() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 541\n at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.SizeOfFrameArgumentArray() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 554\n at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapBuilder.GetCallRefMap(MethodDesc method, Boolean isUnboxingStub) in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapBuilder.cs:line 99\n at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapNode.GetData(NodeFactory factory, Boolean relocsOnly) in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs:line 97\n at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 157\n at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObject(String objectFilePath, EcmaModule componentModule, IEnumerable1 nodes, NodeFactory factory, Boolean generateMapFile) in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 293\n at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in /__w/10/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 240\n at ILCompiler.Program.Run() in /__w/10/s/src/coreclr/src/tools/crossgen2/crossgen2/Program.cs:line 375\n at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) in /__w/10/s/src/coreclr/src/tools/crossgen2/crossgen2/Program.cs:line 471\nManaged assembly not found: No such file or directory\n\nReturn code: 1\nRaw output file: /home/helixbot/work/ACBB0982/w/A9670920/e/JIT/Stress/Reports/JIT.Stress/ABI/tailcalls_do/tailcalls_do.output.txt\nRaw output:\nBEGIN EXECUTION\nin takeLock\nWarning: No files matching /home/helixbot/work/ACBB0982/w/A9670920/e/JIT/Stress/ABI/tailcalls_do/*.dll\nInfo: Method[tailcalls_d
`

**Stack trace**
`
 at JIT_Stress._ABI_tailcalls_do_tailcalls_do_._ABI_tailcalls_do_tailcalls_do_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.Stress/JIT.Stress.XUnitWrapper.cs:line 528
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=ms.vss-test-web.build-test-results-tab&runId=17263490&resultId=100008&paneView=debug

**Comment by AriNuer** [comment]
Tests filed with same error here:[runtime-coreclr crossgen2 outerloop 20200314.1](https://dev.azure.com/dnceng/public/_build/results?buildId=560028&view=results)
**Failed tests:**
```
JIT/Intrinsics/TypeIntrinsics_r/TypeIntrinsics_r.sh
JIT/Stress/ABI/stubs_do/stubs_do.sh
JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh
JIT/Stress/ABI/tailcalls_do/tailcalls_do.sh
JIT/Stress/ABI/tailcalls_d/tailcalls_d.sh
JIT/Intrinsics/TypeIntrinsics_ro/TypeIntrinsics_ro.sh
JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh
```
**Error message:**
```
Error: Operation is not valid due to the current state of the object.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
at Internal.TypeSystem.LayoutInt.get_AsInt() in //src/coreclr/src/tools/Common/TypeSystem/Common/LayoutInt.cs:line 50
at Internal.JitInterface.SystemVStructClassificator.GetSystemVAmd64PassStructInRegisterDescriptor(TypeDesc typeDesc, SYSTEMV_AMD64_CORINFO_STRUCT_REG_PASSING_DESCRIPTOR& structPassInRegDescPtr) in //src/coreclr/src/tools/Common/JitInterface/SystemVStructClassificator.cs:line 99
at ILCompiler.DependencyAnalysis.ReadyToRun.TransitionBlock.ComputeReturnValueTreatment(CorElementType type, TypeHandle thRetType, Boolean isVarArgMethod, Boolean& usesRetBuffer, UInt32& fpReturnSize) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/TransitionBlock.cs:line 272
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.ComputeReturnFlags() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 1681
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.HasRetBuffArg() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 590
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetNextOffset() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 744
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.ForceSigWalk() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 1404
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.SizeOfArgStack() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 541
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.SizeOfFrameArgumentArray() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 554 
at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapBuilder.GetCallRefMap(MethodDesc method, Boolean isUnboxingStub) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapBuilder.cs:line 99
at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapNode.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/GCRefMapNode.cs:line 97
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 157
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObject(String objectFilePath, EcmaModule componentModule, IEnumerable1 nodes, NodeFactory factory, Boolean generateMapFile) in /_/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 293
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in /_/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 240
at ILCompiler.Program.Run() in /_/src/coreclr/src/tools/crossgen2/crossgen2/Program.cs:line 375
at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) in /_/src/coreclr/src/tools/crossgen2/crossgen2/Program.cs:line 471
Managed assembly not found: No such file or directory

Return code: 1
Raw output file: /home/helixbot/work/A83308D4/w/A7B30906/e/JIT/Intrinsics/Reports/JIT.Intrinsics/TypeIntrinsics_r/TypeIntrinsics_r.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/A83308D4/w/A7B30906/e/JIT/Intrinsics/TypeIntrinsics_r/*.dll
Info: Method[TypeIntrinsics_r]Program+<>c.<Main>b__1_5()was not compiled becausehttps://github.com/dotnet/runtime/is
```
**Stack trace:**
`
at JIT_Intrinsics._TypeIntrinsics_r_TypeIntrinsics_r_._TypeIntrinsics_r_TypeIntrinsics_r_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.Intrinsics/JIT.Intrinsics.XUnitWrapper.cs:line 2177
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=560028&view=ms.vss-test-web.build-test-results-tab&runId=17641474&resultId=105746&paneView=debug

**Comment by davidwrighton** [comment]
I'll take this. I've found a number of casting related issues.
