### ISSUE TITLE
Test failure in tracing/tracevalidation/tracelogging/tracelogging/tracelogging.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32728]
Job: 
[runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16935746&paneView=debug&resultId=101919)

Error message:
`
Error: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard\nInternal.TypeSystem.TypeSystemException+FileNotFoundException: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard\n at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID id, String fileName) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 36\n at ILCompiler.CompilerTypeSystemContext.GetModuleForSimpleName(String simpleName, Boolean throwIfNotFound) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 122\n at ILCompiler.CompilerTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 106\n at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 503\n at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 123\n at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 569\n at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 351\n at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 459\n at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 115\n at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 569\n at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 351\n at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 327\n at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType() in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 165\n at Internal.TypeSystem.Ecma.EcmaType.get_BaseType() in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 180\n at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 201\n at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask) in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 135\n at Internal.TypeSystem.TypeDesc.get_IsEnum() in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 209\n at Internal.TypeSystem.TypeDesc.get_UnderlyingType() in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 446\n at ILCompiler.DependencyAnalysis.ReadyToRun.TypeHandle.GetCorElementType() in /Users/runner/runners/2.165.0/work/1/s/src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 132\n a
`

**Comment by v-haren** [comment]
also failed in [tracing\\tracevalidation\\tracelogging\\tracelogging\\tracelogging.cmd](https://dev.azure.com/dnceng/public/_build/results?buildId=536417&view=ms.vss-test-web.build-test-results-tab&runId=17025340&resultId=102723&paneView=debug)

**Comment by AriNuer** [comment]
Test `tracing/tracevalidation/tracelogging/tracelogging/tracelogging.sh` failed again.
**Job:**
[runtime-coreclr crossgen2 outerloop:20200304.1](https://dev.azure.com/dnceng/public/_build/results?buildId=547414&view=results)

**Error message:**
```
Error: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard\nInternal.TypeSystem.TypeSystemException+FileNotFoundException: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard 
at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID id, String fileName) in //src/coreclr/src/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 36
at ILCompiler.CompilerTypeSystemContext.GetModuleForSimpleName(String simpleName, Boolean throwIfNotFound) in //src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 122
at ILCompiler.CompilerTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound) in //src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 106
at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 503
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 123 
at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/src/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 569
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle) in /_/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 351\
at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle) in /_/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 459
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in /_/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 115
at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) in //src/coreclr/src/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 569
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 351
at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 327
at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType() in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 165
at Internal.TypeSystem.Ecma.EcmaType.get_BaseType() in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 180
at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 201
at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask) in //src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 135
at Internal.TypeSystem.TypeDesc.get_IsEnum() in //src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 209
at Internal.TypeSystem.TypeDesc.get_UnderlyingType() in //src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 446
at ILCompiler.DependencyAnalysis.ReadyToRun.TypeHandle.GetCorElementType() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 132
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIteratorData.GetArgumentType(Int32 argNum, TypeHandle& thArgType) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 411
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetArgumentType(Int32 argNum, TypeHandle& thArgType, Boolean& forceByRefReturn) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 487
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetNextOffset() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator
```
**Stack trace:**
`
at tracing_tracevalidation._tracelogging_tracelogging_tracelogging_._tracelogging_tracelogging_tracelogging_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/tracing.tracevalidation/tracing.tracevalidation.XUnitWrapper.cs:line 334
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=547414&view=ms.vss-test-web.build-test-results-tab&runId=17309172&resultId=107118&paneView=debug

**Comment by AriNuer** [comment]
Test `tracing/tracevalidation/tracelogging/tracelogging/tracelogging.sh` failed again.
**Job:**
[runtime-coreclr crossgen2:20200315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=560509&view=results)
**Error message:**
```
Error: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard\nInternal.TypeSystem.TypeSystemException+FileNotFoundException: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard
at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID id, String fileName) in //src/coreclr/src/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 36
at ILCompiler.CompilerTypeSystemContext.GetModuleForSimpleName(String simpleName, Boolean throwIfNotFound) in //src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 122
at ILCompiler.CompilerTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound) in //src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 106
at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 503
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 123
at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/src/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 569
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle) in /_/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 351
at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle) in /_/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 459
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in /_/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 115
at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) in //src/coreclr/src/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 569
at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 351
at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 327
at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType() in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 165
at Internal.TypeSystem.Ecma.EcmaType.get_BaseType() in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 180
at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask) in //src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 201
at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask) in //src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 135
at Internal.TypeSystem.TypeDesc.get_IsEnum() in //src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 209
at Internal.TypeSystem.TypeDesc.get_UnderlyingType() in //src/coreclr/src/tools/Common/TypeSystem/Common/TypeDesc.cs:line 446
at ILCompiler.DependencyAnalysis.ReadyToRun.TypeHandle.GetCorElementType() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 132
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIteratorData.GetArgumentType(Int32 argNum, TypeHandle& thArgType) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 411
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetArgumentType(Int32 argNum, TypeHandle& thArgType, Boolean& forceByRefReturn) in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator.cs:line 487
at ILCompiler.DependencyAnalysis.ReadyToRun.ArgIterator.GetNextOffset() in //src/coreclr/src/tools/crossgen2/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ArgIterator
```
**Stack trace:**
`
at tracing_tracevalidation._tracelogging_tracelogging_tracelogging_._tracelogging_tracelogging_tracelogging_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/tracing.tracevalidation/tracing.tracevalidation.XUnitWrapper.cs:line 334
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=560509&view=ms.vss-test-web.build-test-results-tab&runId=17650590&resultId=101347&paneView=debug
