### ISSUE TITLE
Test failure in JIT/superpmi/superpmicollect/superpmicollect.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32730]
failed in job: [runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16935752&paneView=debug&resultId=102063)

Error message:
`
Fatal error. Failed to load alternative JIT compiler\n at System.SpanHelpers.IndexOf(Char ByRef, Char, Int32)\n at System.String.Ctor(Char*)\n at System.AppContext.Setup(Char**, Char**, Int32)\n/home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh: line 193: 6805 Aborted __Command=$_DebuggerFullPath "$CORE_ROOT/crossgen2/crossgen2" -r:$CORE_ROOT/System..dll -r:$CORE_ROOT/Microsoft..dll -r:$CORE_ROOT/mscorlib.dll -r:$PWD/.dll --targetarch=x64 -O --inputbubble $ExtraCrossGen2Args -o:Bytemark.dll Bytemark.org\nManaged assembly not found: No such file or directory\nManaged assembly not found: No such file or directory\nERROR: no .mc files generated\n\nReturn code: 1\nRaw output file: /home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/Reports/JIT.superpmi/superpmicollect/superpmicollect.output.txt\nRaw output:\nBEGIN EXECUTION\nin takeLock\nWarning: No files matching /home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/.dll\nEmitting R2R PE file: /home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/superpmicollect.dll\n\nin ReleaseLock\n/home/helixbot/work/BB7009DF/p/corerun superpmicollect.dll ''\nSuperPMI collection and playback - BEGIN\nSetting environment variables:\n SuperPMIShimLogPath=/tmp/u2wu3ud0.aeySPMI\n SuperPMIShimPath=/home/helixbot/work/BB7009DF/p/libclrjit.so\n COMPlus_AltJit=*\n COMPlus_AltJitName=libsuperpmi-shim-collector.so\nRunning: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"\nRunning: /bin/chmod +x "/home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"\nRunning: /usr/bin/env bash /home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh\nBEGIN EXECUTION\nin takeLock\nWriting minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.6805.dmp\nWritten 47734784 bytes (11654 pages) to core file\n\nin ReleaseLock\n/home/helixbot/work/BB7009DF/p/corerun Bytemark.dll ''\nExpected: 100\nActual: 255\nEND EXECUTION - FAILED\nRunning: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh"\nRunning: /bin/chmod +x "/home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh"\nRunning: /usr/bin/env bash /home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh\nBEGIN EXECUTION\n/home/helixbot/work/BB7009DF/p/corerun 10w5d_cs_do.dll ''\nExpected: 100\nActual: 255\nEND EXECUTION - FAILED\nSuperPMI collection and playback - FAILED\nExpected: 100\nActual: 101\nEND EXECUTION - FAILED\nTest Harness Exitcode is : 1\nTo run the test:\n> set CORE_ROOT=/home/helixbot/work/BB7009DF/p\n> /home/helixbot/work/BB7009DF/w/A7A60982/e/JIT/superpmi/superpmicollect/superpmicollect.sh\nExpected: True\nActual: False
`

**Comment by AriNuer** [comment]
Same test `JIT/superpmi/superpmicollect/superpmicollect.sh` failed with different error.
**Job:**
[runtime-coreclr crossgen2 outerloop:20200304.1](https://dev.azure.com/dnceng/public/_build/results?buildId=547414&view=results)

**Error message:**
```
Managed assembly not found: No such file or directory
ERROR: replay of final file is not error free

Return code: 1
Raw output file: /home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/Reports/JIT.superpmi/superpmicollect/superpmicollect.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/.dll
Emitting R2R PE file: /home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/superpmicollect.dll

in ReleaseLock
/home/helixbot/work/B6220979/p/corerun superpmicollect.dll ''
SuperPMI collection and playback - BEGIN
Setting environment variables:
SuperPMIShimLogPath=/tmp/and353c3.fytSPMI
SuperPMIShimPath=/home/helixbot/work/B6220979/p/libclrjit.so
COMPlus_AltJit=
COMPlus_AltJitName=libsuperpmi-shim-collector.so
Running: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /bin/chmod +x "/home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /usr/bin/env bash /home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
BEGIN EXECUTION
/home/helixbot/work/B6220979/p/corerun Bytemark.dll ''
Expected: 100
Actual: 255
END EXECUTION - FAILED
Running: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh"
Running: /bin/chmod +x "/home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh"
Running: /usr/bin/env bash /home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh
BEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/B6220979/w/A58108C7/e/JIT/superpmi/superpmicollect/10w5d_cs_do/*.dll\nInfo: Method [10w5d_cs_do]testout1..cctor() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_1_1() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_1_2() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_1_5() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_1_6() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_2_1() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_2_5() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_2_4() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_1_6_4() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_3_1_1() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_3_1_2() was not compiled because https://github.com/dotnet/runtime/issues/32663: CORINFO_FIELD_STATIC_ADDRESS requires runtime JIT
Info: Method [10w5d_cs_do]testout1.Func_0_1_3_1_3() was not compiled because `h
```

**Stack trace:**
`
  at JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.superpmi/JIT.superpmi.XUnitWrapper.cs:line 334
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=547414&view=ms.vss-test-web.build-test-results-tab&runId=17309172&resultId=103602&paneView=debug

**Comment by AriNuer** [comment]
Same test `JIT/superpmi/superpmicollect/superpmicollect.sh` failed in [runtime-coreclr crossgen2:20200316.2](https://dev.azure.com/dnceng/public/_build/results?buildId=561824&view=results)
**Error message:**
```
ERROR: replay of final file is not error free

Return code: 1
Raw output file: /home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/Reports/JIT.superpmi/superpmicollect/superpmicollect.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/.dll
Emitting R2R PE file: /home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/superpmicollect.dll
in ReleaseLock
/home/helixbot/work/AF220996/p/corerun superpmicollect.dll ''
SuperPMI collection and playback - BEGIN
Setting environment variables:
SuperPMIShimLogPath=/tmp/h2moyzzx.ejzSPMI
SuperPMIShimPath=/home/helixbot/work/AF220996/p/libclrjit.so
COMPlus_AltJit= 
COMPlus_AltJitName=libsuperpmi-shim-collector.so
Running: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /bin/chmod +x "/home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /usr/bin/env bash /home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh\nBEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/Bytemark/*.dll
Warning: Method [Bytemark]ByteMark.BenchLUDecomp() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchNeural() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchNeuralJagged() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchIDEAEncryption() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchAssignRectangular() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchAssignJagged() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchFourier() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchEmFloatClass() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchEmFloat() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchBitOps() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchStringSort() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchNumericSortRectangular() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Warning: Method [Bytemark]ByteMark.BenchNumericSortJagged() was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: xunit.performance.core
Emitting R2R PE file: /home/helixbot/work/AF220996/w/AE1909A3/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.dll
in ReleaseLock
/home/helixbot/work/AF220996/p/corerun Bytemark.dll ''
BBBBBB YYY Y TTTTTTT EEEEEEE
BBB B YYY Y TTT EEE
BBB B YYY Y TTT EEE
BBBBBB YYY Y TTT EEEEEEE
BBB B YYY TTT EEE
BBB B YYY TTT EEE
BBBBBB YYY TTT EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged): Iterations/sec: 880.02494 Index: 22.56879
NUMERIC SORT(rectangle): Iterations/sec:
```
**Stack trace:**
`
at JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.superpmi/JIT.superpmi.XUnitWrapper.cs:line 334
`
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=561824&view=ms.vss-test-web.build-test-results-tab&runId=17680390&resultId=102250&paneView=debug

**Comment by BruceForstall** [comment]
@nattress weren't you going to disable all these crossgen2 failing tests?

**Comment by davidwrighton** [comment]
These tests are now disabled for crossgen2, but we may wish to look into them in the future. Moving to 6.0

**Comment by trylek** [comment]
@BruceForstall - could you please suggest the way forward here in light of your recent changes?

**Comment by BruceForstall** [comment]
The superpmicollect unit test doesn't know how to do crossgen2 collections. We need to teach it how to do that, like superpmi.py was taught how to do that.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress 20210519.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1145874&view=ms.vss-test-web.build-test-results-tab&runId=34698498&resultId=107633&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked jitstress2 @ OSX.1100.ARM64.Open

- JIT/superpmi/superpmicollect/superpmicollect.sh

```
**Error message:**
```
ERROR: No files found to merge.
ERROR: replay of final file is not error free

Return code:      1
Raw output file:      /private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/Reports/JIT.superpmi/superpmicollect/superpmicollect.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/AC1C091F/p/corerun superpmicollect.dll ''
SuperPMI collection and playback - BEGIN
Setting environment variables:
SuperPMIShimLogPath=/var/folders/0c/jfl1dmyj2zbfrprsb2zsrfj40000gs/T/2mq4xily.tguSPMI
SuperPMIShimPath=/tmp/helix/working/AC1C091F/p/libclrjit.dylib
COMPlus_JitName=libsuperpmi-shim-collector.dylib
Running: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /bin/chmod +x "/private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /usr/bin/env bash /private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
BEGIN EXECUTION
/tmp/helix/working/AC1C091F/p/corerun Bytemark.dll ''
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 1772.61436  Index: 45.45981
NUMERIC SORT(rectangle):  Iterations/sec: 804.77223  Index: 20.63889
STRING SORT:  Iterations/sec: 7857.15831  Index: 3510.79460
BITFIELD:  Iterations/sec: 385573971.63280  Index: 66.13955
FP EMULATION(struct):  Iterations/sec: 179.97822  Index: 86.36191
FP EMULATION(class):  Iterations/sec: 108.86480  Index: 52.23839
FOURIER:  Iterations/sec: 135612.98027  Index: 154.23220
ASSIGNMENT(jagged):  Iterations/sec: 49.03859  Index: 186.60041
ASSIGNMENT(rectangle):  Iterations/sec: 47.60961  Index: 181.16289
IDEA:  Iterations/sec: 4275.48913  Index: 65.39245
HUFFMAN:  Iterations/sec: 2829.60623  Index: 78.46504
NEURAL NET(jagged):  Iterations/sec: 48.54372  Index: 77.98188
NEURAL NET(rectangle):  Iterations/sec: 38.19785  Index: 61.36200
LU DECOMPOSITION:  Iterations/sec: 3000.95401  Index: 155.46487
===========OVERALL============
INTEGER INDEX: 105.47944
FLOATING-POINT INDEX: 103.49637
(90 MHz Dell Pentium = 1.00)
Expected: 100
Actual: 100
END EXECUTION - PASSED
Running: /usr/bin/perl -pi -e 's/\r\n|\n|\r/\n/g' "/private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh"
Running: /bin/chmod +x "/private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh"
Running: /usr/bin/env bash /private/tmp/helix/working/AC1C091F/w/9A5C08EA/e/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh
BEGIN EXECUTION
/tmp/helix/working/AC1C091F/p/corerun 10w5d_cs_do.dll ''
Func_0_6_5_6_3: != true
Func_0_6_5_4_6: <= true
Func_0_6_5_4_5: > true
Func_0_6_5_4_3: == false
Func_0_6_4_6_2: != true
Func_0_6_4_5_4: < true
Func_0_6_4_5_1: < true
Func_0_6_4_4: <= true
Func_0_6_3_6_5: == false
Func_0_6_3_4_4: <= true
Func_0_6_3_4_3: < true
Func_0_6_3_3: < true
Func_0_6_3_2_3: >= true
Func_0_6_3_1_5: < true
Func_0_6_3_1: <= false
Func_0_6_3: != true
Func_0_6_2_5: != true
Func_0_6_2_1: > false
Func_0_6_1_6_4: < false
Func_0_6_1_6_3: > false
Func_0_6_1_5_4: > true
Func_0_6_1_3: == false
Func_0_5_6_6_6: <= true
Func_0_5_6_6_1: > true
Func_0_5_6_4_6: <= false
Func_0_5_6_4_2: >= false
Func_0_5_6_3_6: < false
Func_0_5_6_3_1: == false
Func_0_5_6_3: <= true
Func_0_5_6_2_1: >= false
Func_0_5_6_1_3: > true
Func_0_5_6_1: <= false
Func_0_5_5_6: != true
Func_0_5_5_5_6: != true
Func_0_5_5_5_4: == false
Func_0_5_5_5_2: == false
Func_0_5_5_4_5: < true
Func_0_5_5_4: > true
Func_0_5_5_3_4: != true
Func_0_5_5_3_2: <= true
Func_0_5_5_3_1: > true
Func_0_5_5_1: < false
Func_0_5_4_5: >= false
Func_0_5_4_1_3: <= false
Func_0_5_4_1_2: == false
Func_0_5_4: != tr


Stack trace
   at JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_sh()
```

**Comment by BruceForstall** [comment]
This new failure looks like something different, maybe macOS/arm64 specific?

**Comment by BruceForstall** [comment]
I opened a separate issue for the macOS/arm64 issue: https://github.com/dotnet/runtime/issues/53321

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr jitstress 20211117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1475284&view=ms.vss-test-web.build-test-results-tab&runId=42280206&resultId=106694&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked jitstress1_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh

```
**Error message:**
```
Assert failure(PID 3254 [0x00000cb6], Thread: 3254 [0x0cb6]): Assertion failed 'encoding_found' in 'EMFloatClass:MultiplyInternalFPF(InternalFPF,InternalFPF,InternalFPF)' during 'Emit code' (IL size 592)

File: /__w/1/s/src/coreclr/jit/emitarm64.cpp Line: 2203
Image: /root/helix/work/correlation/corerun
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9fe7e42c)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9fe7e42c)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9fe734a4)
/root/helix/work/workitem/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh: line 384:  3254 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.superpmi/superpmicollect/Bytemark/Bytemark.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Bytemark.dll ''
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 804.12866  Index: 20.62238
NUMERIC SORT(rectangle):  Iterations/sec: 118.67640  Index: 3.04353
STRING SORT:  Iterations/sec: 638.64102  Index: 285.36239
BITFIELD:  Iterations/sec: 84031759.81267  Index: 14.41441
FP EMULATION(struct):  Iterations/sec: 73.98469  Index: 35.50129
FP EMULATION(class):Gathering state for process 3254 corerun
Crashing thread 00000cb6 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3254.dmp
Written 77119488 bytes (18828 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
Expected: True
Actual:   False


Stack trace
   at JIT_superpmi._superpmicollect_Bytemark_Bytemark_._superpmicollect_Bytemark_Bytemark_sh()
```

**Comment by BruceForstall** [comment]
The latest is a dup of https://github.com/dotnet/runtime/issues/61824

**Comment by BruceForstall** [comment]
I'm going to close this to prevent piling on of different/unrelated failures. Please open a NEW issue for any new superpmicollect test failures.
