### ISSUE TITLE
ArgumentException on Mono: Type passed in must be derived from System.Attribute or System.Attribute itself

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#32744]
```
System.ComponentModel.Composition.Registration.Tests.ExportBuilderUnitTests.ExportInheritedInterfaceWithImplements1 [FAIL]
        System.ArgumentException : Type passed in must be derived from System.Attribute or System.Attribute itself. System.ComponentModel.Composition.IAttributedImport
        Stack Trace:
          /Users/alexander/dev/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs(543,0): at System.Reflection.CustomAttribute.IsDefined(ICustomAttributeProvider obj, Type attributeType, Boolean inherit)
          /Users/alexander/dev/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeFieldInfo.cs(182,0): at System.Reflection.RuntimeFieldInfo.IsDefined(Type attributeType, Boolean inherit)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/Microsoft/Internal/AttributeServices.cs(39,0): at Microsoft.Internal.AttributeServices.IsAttributeDefined[IAttributedImport](ICustomAttributeProvider attributeProvider, Boolean inherit)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(507,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsImport(ICustomAttributeProvider attributeProvider)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(489,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetDeclaredOnlyImportMembers(Type type)+MoveNext()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(458,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetImportMembers(Type type)+MoveNext()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(431,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetImportDefinitions()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(262,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.DiscoverExportsAndImports()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModel/AttributedPartCreationInfo.cs(73,0): at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetImports()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePartDefinition.cs(94,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ImportDefinitions()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs(136,0): at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.get_ImportDefinitions()
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(345,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(437,0): at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs(209,0): at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImportsOnce(ComposablePart part)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionContainer.cs(557,0): at System.ComponentModel.Composition.Hosting.CompositionContainer.SatisfyImportsOnce(ComposablePart part)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModelServices.cs(184,0): at System.ComponentModel.Composition.AttributedModelServices.SatisfyImportsOnce(ICompositionService compositionService, Object attributedPart)
          /Users/alexander/dev/runtime/src/libraries/System.ComponentModel.Composition.Registration/tests/System/ComponentModel/Composition/Registration/ExportBuilderUnitTests.cs(110,0): at System.ComponentModel.Composition.Registration.Tests.ExportBuilderUnitTests.ExportInheritedInterfaceWithImplements1()
```

**Comment by marek-safar** [comment]
@lambdageek / @CoffeeFlux I recall seeing fixing in this space. Could you check if this issue does still exist?

**Comment by CoffeeFlux** [comment]
Yeah, I should have fixed all the issues of this class. If no one else gets a chance, I'll check the test to re-enable it next sprint.

**Comment by akoeplinger** [comment]
I tried and they seem to be passing, opened https://github.com/dotnet/runtime/pull/38658 to reenable.
