### ISSUE TITLE
NamedPipeClientStream Connect can use uninitialized _normalizedPipePath

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#32760]
When adding nullable annotations for System.Net.Sockets (#32675), it was discovered that there is a scenario when using `NamedPipeClientStream` can use a null string:

When calling `NamedPipeClientStream.Connect` on Unix, it will try using the `_normalizedPipePath` string:

https://github.com/dotnet/runtime/blob/032e8dbd0ca5aee045a41ff78e3c0244d3ec3b51/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeClientStream.Unix.cs#L21-L31

However, if the `NamedPipeClientStream` object was created with the constructor that takes an existing `SafePipeHandle` and `isConnected: false`, then `_normalizedPipePath` will be `null`.

https://github.com/dotnet/runtime/blob/032e8dbd0ca5aee045a41ff78e3c0244d3ec3b51/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeClientStream.cs#L101-L103

Doing some searching, I'm honestly not certain how this scenario (existing `SafePipeHandle` and `isConnected: false`) can ever work successfully. It will need a `path` to be able to connect to, which it wasn't given. So at best we may be able to throw a better exception than the `ArgumentNullException` we get:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path)
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at System.IO.Pipes.NamedPipeClientStream.Connect()
```

/cc @stephentoub

**Comment by carlossanlop** [comment]
I also noticed we do not have any `NamedPipeClientStream` unit tests verifying `isConnected=false`.

I wonder if it's possible to retrieve the path of a named pipe from only a `SafePipeHandle`. If this is not possible, then I think the exception should be thrown directly in the constructor if `isConnected=false`.
