### ISSUE TITLE
Timeout_TooShort_AllPendingOperationsCanceled - failure

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32818]
Test: `System.Net.Http.Functional.Tests.HttpClientTest.Timeout_TooShort_AllPendingOperationsCanceled`

https://dev.azure.com/dnceng/public/_build/results?buildId=536066&view=ms.vss-test-web.build-test-results-tab&runId=17015970&paneView=debug

Configuration: `netcoreapp5.0-Windows_NT-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504`

```
Assert.All() Failure: 3 out of 3 items in the collection did not pass.
[2]: Item: System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[System.Net.Http.HttpResponseMessage,System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__76]
 Xunit.Sdk.NotNullException: Assert.NotNull() Failure
 at Xunit.Assert.NotNull(Object object) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\NullAsserts.cs:line 20
 at System.Net.Http.Functional.Tests.HttpClientTest.<>c.<Timeout_TooShort_AllPendingOperationsCanceled>b__36_2(Task1 task) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 615
 at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36
[1]: Item: System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[System.Net.Http.HttpResponseMessage,System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__76]
 Xunit.Sdk.NotNullException: Assert.NotNull() Failure
 at Xunit.Assert.NotNull(Object object) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\NullAsserts.cs:line 20
 at System.Net.Http.Functional.Tests.HttpClientTest.<>c.<Timeout_TooShort_AllPendingOperationsCanceled>b__36_2(Task1 task) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 615
 at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
[0]: Item: System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[System.Net.Http.HttpResponseMessage,System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__76]
 Xunit.Sdk.NotNullException: Assert.NotNull() Failure
 at Xunit.Assert.NotNull(Object object) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\NullAsserts.cs:line 20
 at System.Net.Http.Functional.Tests.HttpClientTest.<>c.<Timeout_TooShort_AllPendingOperationsCanceled>b__36_2(Task1 task) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 615
 at Xunit.Assert.All[T](IEnumerable1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
   at System.Net.Http.Functional.Tests.HttpClientTest.Timeout_TooShort_AllPendingOperationsCanceled(HttpCompletionOption completionOption) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 612
```

**Comment by ViktorHofer** [comment]
cc @dotnet/ncl

**Comment by karelz** [comment]
@ViktorHofer do you know why the error text is reported with ugly `\r\n` instead of new line? I have seen it before ... this is rather annoying on bug reports :( ... is there some place we could/should improve this? Thanks!

**Comment by ViktorHofer** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=588820&view=ms.vss-test-web.build-test-results-tab&runId=18553864&resultId=135687&paneView=debug

Configuration: `netcoreapp5.0-Windows_NT-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504`

```
Assert.All() Failure: 2 out of 3 items in the collection did not pass.\r\n[2]: Item: System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[System.Net.Http.HttpResponseMessage,System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__76]\r\n Xunit.Sdk.NotNullException: Assert.NotNull() Failure\r\n at Xunit.Assert.NotNull(Object object) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\NullAsserts.cs:line 20\r\n at System.Net.Http.Functional.Tests.HttpClientTest.<>c.<Timeout_TooShort_AllPendingOperationsCanceled>b__36_2(Task1 task) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 615\r\n at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36\r\n[1]: Item: System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[System.Net.Http.HttpResponseMessage,System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__76]\r\n Xunit.Sdk.NotNullException: Assert.NotNull() Failure\r\n at Xunit.Assert.NotNull(Object object) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\NullAsserts.cs:line 20\r\n at System.Net.Http.Functional.Tests.HttpClientTest.<>c.<Timeout_TooShort_AllPendingOperationsCanceled>b__36_2(Task1 task) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 615\r\n at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
```

> @ViktorHofer do you know why the error text is reported with ugly \r\n instead of new line? 

Don't know :(

**Comment by Jozkee** [comment]
This test failed again on https://github.com/dotnet/runtime/pull/40601, should this be reopen?

Libraries Test Run release coreclr Windows_NT x64 Debug
https://dev.azure.com/dnceng/public/_build/results?buildId=821288&view=logs&j=694d544e-ff71-5faf-b01a-5137c04e57c6

Helix log: https://helix.dot.net/api/2019-06-17/jobs/a8518142-4a8f-4a4b-83d2-28f0834cd224/workitems/System.Net.Http.Functional.Tests/console
