### ISSUE TITLE
Odd build failure

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#32950]
Only happens on one machine – I can build this same commit on other machines just fine. It repros fairly reliably…

This is based off of 9a47b6b9d75b18e913055759286578850aad958d

```
 System.Net.Http.WinHttpHandler -> E:\repos\runtime1\artifacts\bin\System.Net.Http.WinHttpHandler\netstandard2.0-Windows_NT-Release\System.Net.Http.WinHttpHandler.dll
  Fatal error. Internal CLR error. (0x80131506)
     at Mono.Cecil.Cil.CodeReader.ReadCode()
     at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
     at Mono.Cecil.Cil.CodeReader.ReadMethodBody(Mono.Cecil.MethodDefinition)
     at Mono.Cecil.MetadataReader.ReadMethodBody(Mono.Cecil.MethodDefinition)
     at Mono.Cecil.MethodDefinition+<>c.<get_Body>b__41_0(Mono.Cecil.MethodDefinition, Mono.Cecil.MetadataReader)
     at Mono.Cecil.ModuleDefinition.Read[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.__Canon, System.Func`3<System.__Canon,Mono.Cecil.MetadataReader,System.__Canon>)
     at Mono.Cecil.MethodDefinition.get_Body()
     at Mono.Linker.Steps.ClearInitLocalsStep.ProcessAssembly(Mono.Cecil.AssemblyDefinition)
     at Mono.Linker.Steps.BaseStep.Process(Mono.Linker.LinkContext)
     at Mono.Linker.Pipeline.ProcessStep(Mono.Linker.LinkContext, Mono.Linker.Steps.IStep)
     at Mono.Linker.Pipeline.Process(Mono.Linker.LinkContext)
     at Mono.Linker.Driver.Run(Mono.Linker.ILogger)
     at Mono.Linker.Driver.Execute(System.String[], Mono.Linker.ILogger)
     at Mono.Linker.Driver.Main(System.String[])

Event log shows

Faulting application name: dotnet.exe, version: 5.0.20.11201, time stamp: 0x5e43c374
Faulting module name: coreclr.dll, version: 5.0.20.11201, time stamp: 0x5e43b7e0
Exception code: 0xc0000005
Fault offset: 0x002cd024
Faulting process id: 0xb48c
Faulting application start time: 0x01d5ed120fdd81a7
Faulting application path: E:\repos\runtime1\.dotnet\dotnet.exe
Faulting module path: E:\repos\runtime1\.dotnet\shared\Microsoft.NETCore.App\5.0.0-alpha.1.20112.1\coreclr.dll
```
The build also will usually hang -- other link tasks seem to get stuck in endless GC loops.

cc @BruceForstall

**Comment by ViktorHofer** [comment]
@andy-ms I'm closing this of age. If this still happens on your machine please reopen the issue and we will take a closer look. Thanks
