### ISSUE TITLE
Test failed: System.IO.Tests.File_Create_Tests.FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#32955]
**Job:**
[runtime-libraries outerloop 20200227.1](https://dev.azure.com/dnceng/public/_build/results?buildId=538834&view=results)

**Error message:**
`
Assert.False() Failure\nExpected: False\nActual: True
`

**Comment by danmosemsft** [comment]
@VincentBu thanks for opening test issues. Could you please include the full output, including callstack if any? In this case, it's
```
 at System.IO.Tests.File_Create_Tests.<FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent>b__1_0() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs:line 61
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 243
   at System.IO.Tests.File_Create_Tests.FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs:line 34
```

Let me know if you can't find it in the UI.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200425.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=617229&view=ms.vss-test-web.build-test-results-tab&runId=19341720&resultId=103092&paneView=debug)

failed test: System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther


Error message
~~~
Assert.False() Failure
Expected: False
Actual: True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 317
~~~

**Comment by josalem** [comment]
Similar failure here: https://dev.azure.com/dnceng/public/_build/results?buildId=632273&view=logs&j=499826eb-b71f-5fb9-e963-df1d0bd97bcc&t=592f02e1-36e2-5ce1-c6c7-5351786e61b6

failed test: `System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther`

Output:
```
  Discovering: System.IO.FileSystem.Watcher.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Watcher.Tests (found 19 of 183 test cases)
  Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 4)
    System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs(317,0): at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther()
  Finished:    System.IO.FileSystem.Watcher.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Watcher.Tests  Total: 35, Errors: 0, Failed: 1, Skipped: 0, Time: 61.506s
```

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200531.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=665610&view=ms.vss-test-web.build-test-results-tab&runId=20630020&resultId=102888&paneView=debug)


Error message
~~~
Assert.False() Failure
Expected: False
Actual: True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 317
~~~

**Comment by ManickaP** [comment]
Another hit: https://dev.azure.com/dnceng/public/_build/results?buildId=713669&view=ms.vss-test-web.build-test-results-tab&runId=22123896&resultId=102359&paneView=debug

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200708.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=720727&view=ms.vss-test-web.build-test-results-tab&runId=22323580&resultId=102968&paneView=debug)

failed test: System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther


Error message
~~~
Assert.False() Failure
Expected: False
Actual: True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 317
~~~

**Comment by v-haren** [comment]
also failed in job: [runtime-libraries outerloop 20200803.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=754804&view=ms.vss-test-web.build-test-results-tab&runId=23423598&resultId=102971&paneView=debug)

failed test: System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther


Error message
~~~
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200827.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=789975&view=ms.vss-test-web.build-test-results-tab&runId=24928342&paneView=debug&resultId=103377)

failed test: 
System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther

Configurations:
net5.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open


Error message
~~~
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20200914.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=813913&view=ms.vss-test-web.build-test-results-tab&runId=25905762&resultId=103219&paneView=debug)

failed test:  System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther

net5.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open


Error message
~~~
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
~~~

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20201013.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=850450&view=ms.vss-test-web.build-test-results-tab&runId=27103032&paneView=debug&resultId=102959)

failed test: System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open


Error message
~~~
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
~~~

**Comment by VincentBu** [comment]
Failed again in run [runtime-libraries-coreclr outerloop 20210124.2](https://dev.azure.com/dnceng/public/_build/results?buildId=963738&view=ms.vss-test-web.build-test-results-tab&runId=30351548&paneView=debug&resultId=103210)

Failed tests:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
        - System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther
```

Error message:
```
Assert.False() Failure
Expected: False
Actual:   True

stack trace:
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210131.2](https://dev.azure.com/dnceng/public/_build/results?buildId=973165&view=ms.vss-test-web.build-test-results-tab&runId=30559662&paneView=debug&resultId=102978)

Failed tests:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
    - System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther
```

Error message:
```
Assert.False() Failure
Expected: False
Actual:   True

stack trace:
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210225.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1011360&view=ms.vss-test-web.build-test-results-tab&runId=31516792&resultId=102986&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
 
-System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther
```

**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210322.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1050368&view=ms.vss-test-web.build-test-results-tab&runId=32460114&resultId=102760&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
 -System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther
```

**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210505.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1122979&view=ms.vss-test-web.build-test-results-tab&runId=34169220&resultId=103003&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
 -System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther
```

**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by danmoseley** [comment]
This has happened 9 times this year


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= datetime(2021-1-1 0:00:00)
| where Method == "FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent"
| where Result == "Fail"
| project Method, Message, QueueAlias, Queued
```

|Method|Message|QueueAlias|Queued|
|---|---|---|---|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-03-18 01:04:36.6840000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-03-23 12:06:55.8180000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-03-24 11:48:29.2680000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-03-26 11:42:08.8170000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-04-08 12:02:34.4700000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1013.amd64.open|2021-04-09 11:45:01.4610000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-04-10 11:54:23.0580000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-04-17 11:49:57.8770000|
|FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent|Assert.False() Failure\nExpected: False\nActual:   True|osx.1014.amd64.open|2021-05-04 11:55:58.9260000|

**Comment by danmoseley** [comment]
For FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent, the rarer one, I think the line number is off. It has to be here:
https://github.com/dotnet/runtime/blob/e7b743cae325d4720fceaf7f84f68aaaf7bb7dbe/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs#L63
Here we are subscribing to events for a file , creating the file, and apparently the event handler is getting called more than once.

For FileSystemWatcher_File_Delet_NotAffectEachOther it is here
https://github.com/dotnet/runtime/blob/e7b743cae325d4720fceaf7f84f68aaaf7bb7dbe/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs#L316-L315
We delete a file, wait for several delete watchers to all signal, create it again, set watcher 1 to stop watching, delete it, and we see watcher 1 fire nevertheless within ~250ms.
One possibility here is that like the first case, we're getting two events (this time for the delete) and the second event is arriving in a race with disabling the watcher.

**Comment by danmoseley** [comment]
In the second case, it is assuming that events are deterministically not received after `EnableRaisingEvents = false` is set on a watcher. However, this is not synchronous: it just sets a CancellationToken. (Why isn't this failing on Linux?)

In the first case, we are flipping EnableRaisingEvents back and forth, and I am guessing that this may lead to a situation where we effectively have two identical watchers.

**Comment by danmoseley** [comment]
It's not obvious how to fix this - I think it's reasonable to say that we do not guarantee that events won't arrive for a little longer after you disable raising events - and in practice for whatever reason this shows up only on Mac.

so FileSystemWatcher_File_Delet_NotAffectEachOther should be disabled for Mac, or refactor the disable raising events out.

The FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent needs a little more analysis.

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210517.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1141570&view=ms.vss-test-web.build-test-results-tab&runId=34604854&resultId=102203&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1013.Amd64.Open

- System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther

```
**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210609.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1178661&view=ms.vss-test-web.build-test-results-tab&runId=35472950&resultId=102782&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

- System.IO.Tests.File_Create_Tests.FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent

```
**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.File_Create_Tests.<FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent>b__1_0() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs:line 61
   at System.IO.Tests.FileSystemWatcherTest.ExecuteWithRetry(Action action, Int32 maxAttempts) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 241
   at System.IO.Tests.File_Create_Tests.FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.File.Create.cs:line 34
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20210819.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1304025&view=ms.vss-test-web.build-test-results-tab&runId=38410732&resultId=102757&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

- System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther

```

**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20220123.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1567490&view=ms.vss-test-web.build-test-results-tab&runId=44074222&paneView=debug&resultId=102941)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

- System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther

```
**Error message:**
```
Assert.False() Failure
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 316
```
