### ISSUE TITLE
dotnet new mvc Access to the path is denied.

### ISSUE THREAD

**Issue by shaokuan** [dotnet/runtime#33008]
The following error message appears after I enter the command dotnet new mvc
How do I handle it?
thanks.
my dotnet core version 3.1
os linux ubuntu Ubuntu 16.04.6 LTS on raspberry pi

```
pi@bpi-iot-ros-ai:/usr/share/coremvc$ dotnet new mvc
Template "ASP.NET Core Web App (Model-View-Controller)" could not be created.
Error while processing file /content/StarterWeb-CSharp/appsettings.Development.json
System.UnauthorizedAccessException: Access to the path '/usr/share/coremvc/appsettings.Development.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors, IReadOnlyList`1 locOperations)
```

**Comment by svick** [comment]
This looks like you don't have the rights to create files in the directory `/usr/share/coremvc`. Can you try running the command in a directory where you have the rights, like a subdirectory of your home directory?

**Comment by shaokuan** [comment]
thanks..wheh i use chmod 777 to setting permission of folder,new mvc is working...
