### ISSUE TITLE
Assert failure currentProcessCpuCount == g_processAffinitySet.Count()

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#33031]
https://helix.dot.net/api/2019-06-17/jobs/5c24c550-4c42-459f-bbfd-21e69cbf8a27/workitems/System.Diagnostics.Process.Tests/console

`Libraries Test Run checked coreclr Linux x64 Debug `
```
Assert failure(PID 15210 [0x00003b6a], Thread: 15210 [0x3b6a]): currentProcessCpuCount == g_processAffinitySet.Count()
File: /__w/1/s/src/coreclr/src/vm/gcenv.os.cpp Line: 123
Image: /home/helixbot/work/AB3D09A7/p/dotnet

System.Diagnostics.Tests.ProcessTests.TestProcessorAffinity [FAIL]
  System.InvalidOperationException : Cannot process request because the process (15210) has exited.
  Stack Trace:
	System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(343,0): at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
	System.Diagnostics.Process/src/System/Diagnostics/Process.cs(932,0): at System.Diagnostics.Process.EnsureState(State state)
	System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs(191,0): at System.Diagnostics.Process.set_ProcessorAffinityCore(IntPtr value)
	System.Diagnostics.Process/src/System/Diagnostics/Process.cs(532,0): at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value)
	System.Diagnostics.Process/tests/ProcessTests.cs(861,0): at System.Diagnostics.Tests.ProcessTests.TestProcessorAffinity()
System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
  Condition(s) not met: "IsStressModeEnabled"
Finished:    System.Diagnostics.Process.Tests
```

Seen in https://github.com/dotnet/runtime/pull/32538

**Comment by AndyAyersMS** [comment]
Also seen in #33004

https://helix.dot.net/api/2019-06-17/jobs/39ad1508-af24-45b6-a333-b29865d72b21/workitems/System.Diagnostics.Process.Tests/console

Older reports of this or something similar looking: #12510, #13215.

**Comment by jkotas** [comment]
The other failures so far were on arm. It is interesting that we have hit it on x64 as well.

**Comment by jkotas** [comment]
Resolving as dup of #12510

**Comment by benaadams** [comment]
Might be race with process exit? `Cannot process request because the process (15210) has exited.`
