### ISSUE TITLE
System.IO.FileNotFoundException: Could not find file 

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/runtime#33105]
Hello, 

i have migrated my projet from .NET framework to .NET Core, and when i build my project in RedHat,
I had this error
System.IO.FileNotFoundException: Could not find file '/home\VSMP_Setting.xml'.
i used this code below to get file
``````````
private static string Xml_Settings_Path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.FullName + @"\VSMP_Setting.xml";
````````
I have changed Parent.Parent.Parent, but i still have same error

Cordially

**Comment by stephentoub** [comment]
Your code is using `\` as a directory separator. It isn't on Unix. Use `/` or Path.Combine.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
private static string Xml_Settings_Path = Combien.Path(Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName,"VSMP_Setting.xml");

Return same error

**Comment by stephentoub** [comment]
> Return same error

You will need to debug it.  The exception is valid, saying it can't find the specified path.  You'll need to look at what the actual path is that you're specifying, and determine why it can't find that file.  Maybe the path is wrong.  Maybe the permissions on that path prevent you from accessing it.  Etc.

(I'm also not sure what `Combien.Path` is as a method.)

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @stephentoub ,

Still have same problem, i have changed path, i haved used Combine metod but always get error in redhat, System.IO.FileNotFoundException: Could not find file '/home\VSMP_Setting.xml'.
File name: '/home\VSMP_Setting.xml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) in /_/src/System.Private.CoreLib/shared/Interop/Unix/Interop.IOErrors.cs:line 24
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) in /_/src/System.Private.CoreLib/shared/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs:line 39
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) in /_/src/System.Private.CoreLib/shared/System/IO/FileStream.Unix.cs:line 61
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in /_/src/System.Private.CoreLib/shared/System/IO/FileStream.cs:line 237
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) in /_/src/System.Private.CoreLib/shared/System/IO/FileStream.cs:line 179
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy) in /_/src/System.Private.Xml/src/System/Xml/XmlDownloadManager.cs:line 27
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) in /_/src/System.Private.Xml/src/System/Xml/XmlUrlResolver.cs:line 66
   at System.Xml.XmlTextReaderImpl.OpenUrl() in /_/src/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs:line 3087
   at System.Xml.XmlTextReaderImpl.Read() in /_/src/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs:line 1206
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace) in /_/src/System.Private.Xml/src/System/Xml/Dom/XmlLoader.cs:line 50
   at System.Xml.XmlDocument.Load(XmlReader reader) in /_/src/System.Private.Xml/src/System/Xml/Dom/XmlDocument.cs:line 1336
   at System.Xml.XmlDocument.Load(String filename) in /_/src/System.Private.Xml/src/System/Xml/Dom/XmlDocument.cs:line 1288

**Comment by stephentoub** [comment]
There's no way you're using the code `@"/VSMP_Settings_File.xml"` and getting an exception that says `/home\VSMP_Setting.xml` :wink:.  Something is wrong either in what you've shared or in what you tried to execute.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Exactly i can't understand when i run projet in RedHat, i get error /home\VSMP_Setting.xml

**Comment by HASSEN-MEDDEB-ATOS** [comment]
![image](https://user-images.githubusercontent.com/58071802/75894904-31ccbb80-5e35-11ea-8f78-a347947dc4ef.png)

**Comment by stephentoub** [comment]
If your code says "/VSMP_Settings_File.xml", and you're getting an error about "\VSMP_Setting.xml", then the answer is likely simple: you're not executing the code you think you're executing.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
![image](https://user-images.githubusercontent.com/58071802/75895765-65f4ac00-5e36-11ea-8e67-157569fe7863.png)
![image](https://user-images.githubusercontent.com/58071802/75895895-89b7f200-5e36-11ea-918b-56e8f828b0af.png)

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Hello @stephentoub,

I did like this 
```````

    public static class OperatingSystem
    {
        public static bool IsWindows() =>
            RuntimeInformation.IsOSPlatform(OSPlatform.Windows);

        public static bool IsMacOS() =>
            RuntimeInformation.IsOSPlatform(OSPlatform.OSX);

        public static bool IsLinux() =>
            RuntimeInformation.IsOSPlatform(OSPlatform.Linux);
    }
}
````````````
````````````
  private static string Xml_Settings_PathWin = Path.Combine(rootPath, "C:\\Git\\VSMP_Data_Integration\\vsmp_data_integration\\VSMP_Setting.xml");`

            private static string Xml_Settings_PathLin = Path.Combine(rootPath, "/home/a772854/VSMP_Data_Integration/vsmp_data_integration/VSMP_Setting.xml");
if (OperatingSystem.IsLinux())
                {
                    LogHelper.Writer("root of file " + Xml_Settings_PathLin);
                    VSMP_Settings = new XmlDocument();
                    VSMP_Settings.Load(Xml_Settings_PathLin);
                }
                else
                {
                    LogHelper.Writer("root of file " + Xml_Settings_PathWin);
                    VSMP_Settings = new XmlDocument();
                    VSMP_Settings.Load(Xml_Settings_PathWin);

                }
``````````
i get some error :/
![image](https://user-images.githubusercontent.com/58071802/75982219-592f9100-5ee6-11ea-9fa3-6de8581981be.png)

if i run project in Windows i have no errors, can you investigate please.

Best regards

**Comment by stephentoub** [comment]
The code you posted above has `LogHelper.Writer("root of file " + Xml_Settings_PathLin);` in the Linux path.  When you run this on Linux, do you see that logged?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
the logged, it apperas in windows but not in linux :/

**Comment by stephentoub** [comment]
> the logged, it apperas in windows but not in linux :/

Right, which gets back to my previous comment: you're not running the code you think you're running.  You'll need to address that; there's nothing wrong with the implementation of these APIs for us to investigate because you're not actually running code using these APIs.  Thanks.

**Comment by HASSEN-MEDDEB-ATOS** [comment]
But, i run the right project ? i have followed the doc
![image](https://user-images.githubusercontent.com/58071802/75984062-048e1500-5eea-11ea-8d29-2ffbcfc95f95.png)

**Comment by MHamzaYousuf** [comment]
> Thanks for your answee @stephentoub
> private static string Xml_Settings_Path = Combine.Path(Directory.GetParent(Directory.GetCurrentDirectory()).Parent.FullName,"VSMP_Setting.xml");
> 
> Return same error

tested works on both 2.0 and 3.0 https://www.c-sharpcorner.com/article/upload-download-files-in-asp-net-core-2-0
