### ISSUE TITLE
BeginGetHostAddresses returns unexpected results when using systemd-resolved

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#33145]
I bump to this while running HTTP functional tests on local machine but we do see similar failures frequently in CI.

```
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.SendAsync_RequestVersion20_ResponseVersion20 [SKIP]
      Condition(s) not met: "IsWindows10Version1607OrGreater"
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.GetAsync_NonTraditionalChunkSizes_Accepted [SKIP]
      Chunking is not supported on HTTP/2 and later.
      System.Net.Http.HttpRequestException : Name or service not known
      ---- System.Net.Sockets.SocketException : Name or service not known
      Stack Trace:
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(75,0): at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1068,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1108,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(442,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(719,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTestBase.cs(104,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.VersionCheckerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(542,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)
        /mnt/github/wfurt-runtime2/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs(1623,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(RemoteServer remoteServer, HttpContent content, Byte[] expectedData)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(122,0): at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs(644,0): at System.Net.Sockets.SocketAsyncEventArgs.FinishConnectByNameAsyncFailure(Exception exception, Int32 bytesTransferred, SocketFlags flags)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(338,0): at System.Net.Sockets.MultipleConnectAsync.AsyncFail(Exception e)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(304,0): at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(145,0): at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync)
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs(84,0): at System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result)
        /mnt/github/wfurt-runtime2/src/libraries/Common/src/System/Threading/Tasks/TaskToApm.cs(107,0): at System.Threading.Tasks.TaskToApm.TaskAsyncResult.InvokeCallback()
        /mnt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(172,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        /mnt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs(692,0): at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
        /mnt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(3248,0): at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
        /mnt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(1975,0): at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
        /mnt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2327,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        /mnt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs(659,0): at System.Threading.ThreadPoolWorkQueue.Dispatch()
        --- End of stack trace from previous location ---
        /mnt/github/wfurt-runtime2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(56,0): at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.SendAsync_RequestVersion20_ResponseVersion20 [SKIP]
      Condition(s) not met: "IsWindows10Version1607OrGreater"
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http2.SendAsync_101SwitchingProtocolsResponse_Success [SKIP]
      Upgrade is not supported on HTTP/2 and later
  Finished:    System.Net.Http.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Http.Functional.Tests  Total: 2174, Errors: 0, Failed: 3, Skipped: 55, Time: 48.103s
```

While running the test, I did packet capture for DNS traffic as well as I instrumented `SystemNative_GetHostEntryForName` in PAL to log more details on failures of `getaddrinfo`. 

I did not see any sign of failure in packet capture but is it is curious that if an invalid name like guid or `notahostname.invalid.corp.microsoft.com`  fail, errno is set to`ESRCH`but if a valid name like `corefx-net-http2.azurewebsites.net` fail, the result is set to `EAI_NONAME` and errno is set to `EINVAL`.

In  the man page for `getaddrinfo`, errno is mentioned only with `EAI_SYSTEM` result but the observer result is quite consistent. I could not reproduce this when running tests with `-parallel none`. It could be just good luck since test runs as so much slower but it could be also a hint. (I plan to do more runs to be sure) 

Since I have reasonable local repro I tried to triage this closer. I was somewhat surprised to see only AAAA queries for  `waws-prod-bay-047.cloudapp.net` during the runs. It turned out that `corefx-net-http2.azurewebsites.net` is CNAME for 'waws-prod-bay-047.cloudapp.ne' and for IPv4 it resolves to an address but it does not for IPv6.

I also did more digging through glibc resolver code and I did more stracing on test runs. 
It seems like it would use nscd caching transparently when available (not my  case) but I also noticed communication to `/run/dbus/system_bus_socket` and `systemd-resolved` running. 
That eventually led to `hosts:          files resolve [!UNAVAIL=return] dns` entry in `/etc/nsswitch.conf`

When I change that back to good old `files dns`, I could run 100+ iterations without failures when it was failing much more frequently before. 

That opens question if `getaddrinfo` truly threads safe as .NET assumes on Linux systems using systemd e.g. RH, Centos & Ubuntu. With systemd in the picture, all requests and responses need to be marshaled back and forth via a single UDS socket. 

cc: @tmds 

I'll keep looking into this as this is one of the reasons for frequent CI test failures.

**Comment by tmds** [comment]
@wfurt interesting issue, and findings.

> I did not see any sign of failure in packet capture but is it is curious that if an invalid name like guid or notahostname.invalid.corp.microsoft.com fail, errno is set to ESRCH

What is the return value of `getaddrinfo` in this case?
It would be interesting to figure out what process `ESRCH` is referring to.

> That opens question if getaddrinfo truly threads safe as .NET assumes on Linux systems using systemd e.g. RH, Centos & Ubuntu.

It should be thread-safe... except for bugs.

Let me know if/when you want an extra pair of eyes.

**Comment by wfurt** [comment]
I was finally able to capture the failing case @tmds. 
```

[pid 22528]      0.000147 recvmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\17\0\0\0\1\0\0\0E\0\0\0\6\1s\0\n\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24 <0.000005>
[pid 22528]      0.000097 recvmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.1984402\0\0\0\0\0\0\5\1u\0\1\0\0\0\10\1g\0\1s\0\0\7\1s\0\24\0\0\0org.freedesktop.DBus\0\0\0\0\n\0\0\0:1.1984402\0", iov_len=79}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 79 <0.000005>
[pid 22528]      0.000107 sendmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\2\0018\0\0\0\2\0\0\0\242\0\0\0\1\1o\0\31\0\0\0/org/freedesktop/resolve1\0\0\0\0\0\0\0\3\1s\0\17\0\0\0ResolveHostname\0\2\1s\0 \0\0\0org.freedesk"..., iov_len=184}, {iov_base="\0\0\0\0\"\0\0\0corefx-net-http2.azurewebsites.net\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=56}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 240 <0.000009>
[pid 22528]      0.000114 recvmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\17\0\0\0\2\0\0\0\225\0\0\0\1\1o\0\25\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24 <0.000004>
[pid 22528]      0.000097 recvmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="/org/freedesktop/DBus\0\0\0\2\1s\0\24\0\0\0org.freedesktop.DBus\0\0\0\0\3\1s\0\f\0\0\0NameAcquired\0\0\0\0\6\1s\0\n\0\0\0:1.1984402\0\0"..., iov_len=159}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 159 <0.000004>
[pid 22528]      0.000103 recvmsg(379, {msg_namelen=0}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000004>
[pid 22528]      0.000076 recvmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\3\1\0018\0\0\0\376D\0\0k\0\0\0\5\1u\0\2\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24 <0.000005>
[pid 22528]      0.000106 recvmsg(379, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\6\1s\0\n\0\0\0:1.1984402\0\0\0\0\0\0\4\1s\0&\0\0\0org.freedesktop.DBus.Error.InvalidArgs\0\0\10\1g\0\1s\0\0\7\1s\0\n\0\0\0:1.1979977\0\0"..., iov_len=160}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 160 <0.000008>

```

I did not see any evidence that there would be a multithreading issue - at least not on side of the test, It seems like each thread opens its own socket. 

It seems like the error is coming from inside of the DBUS message - see the last part. It both cases, the behavior seems to match `org.freedesktop.DBus.Error.InvalidArgs` -> `EINVAL` and `org.freedesktop.DBus.Error.Timeout` ->` ETIMEDOUT`.

Again, in this case, resolution fails with `EAI_NONAME` instead of `EAI_SYSTEM`

**Comment by wfurt** [comment]
here is dump from dbus-monitor

```

method return time=1583473218.311068 sender=org.freedesktop.DBus -> destination=:1.1988046 serial=1 reply_serial=1
   string ":1.1988046"
signal time=1583473218.311077 sender=org.freedesktop.DBus -> destination=(null destination) serial=3975805 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.1988046"
   string ""
   string ":1.1988046"
signal time=1583473218.311087 sender=org.freedesktop.DBus -> destination=:1.1988046 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.1988046"

method call time=1583473218.311197 sender=:1.1988046 -> destination=org.freedesktop.resolve1 serial=2 path=/org/freedesktop/resolve1; interface=org.freedesktop.resolve1.Manager; member=ResolveHostname
   int32 0
   string "corefx-net-http2.azurewebsites.net"
   int32 0
   uint64 0

method call time=1583473218.311357 sender=:1.1979977 -> destination=org.freedesktop.DBus serial=32180 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.1988046'"
method return time=1583473218.311373 sender=org.freedesktop.DBus -> destination=:1.1979977 serial=16094 reply_serial=32180

method call time=1583473218.311387 sender=:1.1979977 -> destination=org.freedesktop.DBus serial=32181 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string ":1.1988046"
method return time=1583473218.311394 sender=org.freedesktop.DBus -> destination=:1.1979977 serial=16095 reply_serial=32181
   string ":1.1988046"
error time=1583473218.340026 sender=:1.1979977 -> destination=:1.1988046 error_name=org.freedesktop.DBus.Error.InvalidArgs reply_serial=2
   string "Lookup failed due to system error: Invalid argument"

```

**Comment by tmds** [comment]
> It seems like the error is coming from inside of the DBUS message - see the last part. It both cases, the behavior seems to match org.freedesktop.DBus.Error.InvalidArgs -> EINVAL and org.freedesktop.DBus.Error.Timeout -> ETIMEDOUT.
Again, in this case, resolution fails with EAI_NONAME instead of EAI_SYSTEM

This is the bug we're seeing for systemd resolver, right?
Will you create an issue for this (in systemd github project, or Red Hat bugzilla)?
I can look into it if you want.

**Comment by tmds** [comment]
@wfurt shall I look into this further?

**Comment by wfurt** [comment]
yes, that would be great @tmds. At least see if you can reproduce the symptoms. I do run all tests including outerloop in a loop and the "Name or service not known" happens once in a while. Since systemd is caching the responses, this should really not have external dependencies. 

I also opened two separate issues for systemd, both linked above.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200416.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=603555&view=ms.vss-test-web.build-test-results-tab&runId=19005818&paneView=debug&resultId=102200)


Error message
~~~
System.Net.Http.HttpRequestException : Name or service not known
---- System.Net.Sockets.SocketException : Name or service not known


Stack trace
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 81
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1120
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 627
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 720
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.VersionCheckerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTestBase.cs:line 124
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 596
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 304
   at System.Net.Http.Functional.Tests.ResponseStreamTest.GetStreamAsync_ReadToEnd_Success(RemoteServer remoteServer, Int32 readMode) in /_/src/libraries/Common/tests/System/Net/Http/ResponseStreamTest.cs:line 43
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectEventArgs.OnCompleted(SocketAsyncEventArgs _) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 125
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean sync, Exception e) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 304
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(IAsyncResult result, Boolean sync) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 143
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(IAsyncResult result) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/MultipleConnectAsync.cs:line 84
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 691
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3248
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1975
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2327
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs:line 659
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 81
~~~

**Comment by tmds** [comment]
This issue should be fixed by https://github.com/systemd/systemd/commit/fd8a30170342cfe245ea6acac392c2b224f0ae1b, which is in systemd v247+.

**Comment by wfurt** [comment]
I'm wondering if it is time to close this @tmds. 
@rzikm can probably confirm if mysterious name resolution failures are gone.

**Comment by wfurt** [comment]
seems to be fixed by underlying OS.
