### ISSUE TITLE
4 TimeZone tests failing on Windows 10 2004

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#33149]
```
System.Tests.TimeZoneInfoTests.ConvertTime_SameTimeZones [FAIL]
        System.InvalidTimeZoneException : The time zone ID 'E. South America Standard Time' was found on the local computer, but the registry information was corrupt.
        Stack Trace:
          C:\git\runtime4\src\libraries\System.Private.CoreLib\src\System\TimeZoneInfo.Win32.cs(353,0): at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
          C:\git\runtime4\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs(2288,0): at System.Tests.TimeZoneInfoTests.VerifyConvert(DateTimeOffset inputTime, String destinationTimeZoneId, DateTimeOffset expectedTime)
          C:\git\runtime4\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs(330,0): at System.Tests.TimeZoneInfoTests.ConvertTime_SameTimeZones()
      System.Tests.TimeZoneInfoTests.GetSystemTimeZones [FAIL]
        Assert.Contains() Failure
        Not found: (filter expression)
        In value:  ReadOnlyCollection<TimeZoneInfo> [(UTC-12:00) International Date Line West, (UTC-11:00) Coordinated Universal Time-11, (UTC-10:00) Aleutian Islands, (UTC-10:00) Hawaii, (UTC-09:30) Marquesas Islands, ...]
        Stack Trace:
          C:\git\runtime4\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs(1817,0): at System.Tests.TimeZoneInfoTests.GetSystemTimeZones()
      System.Tests.TimeZoneInfoTests.ConvertTime_Brasilia [FAIL]
        System.TimeZoneNotFoundException : The time zone ID 'E. South America Standard Time' was not found on the local computer.
        Stack Trace:
          C:\git\runtime4\src\libraries\System.Private.CoreLib\src\System\TimeZoneInfo.Win32.cs(361,0): at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
          C:\git\runtime4\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs(2288,0): at System.Tests.TimeZoneInfoTests.VerifyConvert(DateTimeOffset inputTime, String destinationTimeZoneId, DateTimeOffset expectedTime)
          C:\git\runtime4\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs(876,0): at System.Tests.TimeZoneInfoTests.ConvertTime_Brasilia()
      System.Tests.TimeZoneInfoTests.CaseInsensitiveLookup [FAIL]
        System.TimeZoneNotFoundException : The time zone ID 'E. South America Standard Time' was not found on the local computer.
        Stack Trace:
          C:\git\runtime4\src\libraries\System.Private.CoreLib\src\System\TimeZoneInfo.Win32.cs(361,0): at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
          C:\git\runtime4\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs(142,0): at System.Tests.TimeZoneInfoTests.CaseInsensitiveLookup()
```

OS build: 19574.1000

cc @tarekgh @bartonjs @joperezr

**Comment by tarekgh** [comment]
I'll take a look

**Comment by tarekgh** [comment]
I looked at the issue and I am seeing this is a problem in Windows data for the zone `E. South America Standard Time`. I am contacting the Windows team to fix that.

**Comment by joperezr** [comment]
Thanks for looking into it Tarek!

**Comment by tarekgh** [comment]
@ViktorHofer I got build 2004 and I am not seeing the problem there. Could you please tell more how you got your build and what is the exact complete version there? I mean the version and the build number.

**Comment by ViktorHofer** [comment]
I have since already upgraded my machine. I just looked in the initial post in which I mentioned the Fast ring version: `OS build: 19574.1000`.

**Comment by tarekgh** [comment]
Please upgrade to `OS build: 19577.1000.` 

I am closing this issue but feel free to reopen if you still see the problem with the upgraded version.
