### ISSUE TITLE
[mono][tests] System.Net.Tests.ServicePointManagerTest.FindServicePoint_Collectible

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#33231]
When running under the **interpreter**, the test fails with:

```
Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Net.Tests.ServicePointManagerTest.<>c.<FindServicePoint_Collectible>b__15_0() in /_/src/libraries/System.Net.ServicePoint/tests/ServicePointManagerTest.cs:line 300
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339

Child process:
  System.Net.ServicePoint.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Tests.ServicePointManagerTest+<>c Void <FindServicePoint_Collectible>b__15_0()
```

**Comment by danmosemsft** [comment]
Possibly related to the GC it expects to happen?
```
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();

                Assert.Equal(initial, GetExpect100Continue(address));
```
@steveisok what OS was this?
