### ISSUE TITLE
Lambda Type Incorrectly Inferred When Written As Expression (But Works As A Statement)

### ISSUE THREAD

**Issue by iUnknwn** [dotnet/runtime#33412]
The same logical lambda is generating different code depending on if it's written as a statement or an expression. 

Here is the code as an expression lambda.
```
Task rt = Task.Run(() => RestoreDatabase(name, owners, jobGuid));
```
If I mouse over the code, the call is interpreted as `Task.Run<dynamic>(Func<dynamic>)`

However, when written as a statement lambda, there is a different response:
```
Task restoreTask = Task.Run(() =>
            {
                RestoreDatabase(name, owners, jobGuid);
            });
```
This code shows up as Task.Run(Action);

The signature of the called function is `private void RestoreDatabase(string name, List<string> owners, Guid id)`, so I'd expect it to be an Action.

The issue affects more than intellisense. If the call is written as a expression, the Task fails to execute, and generates an exception:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'
   at CallSite.Target(Closure , CallSite , ServerMethods , Object , Object , Guid)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at DbRestorer_ServerApp.ServerMethods.<>c__DisplayClass6_0.<BeginRestoreDatabase>b__0() in
C:\\GitProjects\\DatabaseRestorer\\DbRestorer-ServerApp\\ServerMethods.cs:line 151
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

However, when written as a statement, the code executes as expected. 

The code is targeting ASP.NET Core (3.1).

**Comment by iUnknwn** [comment]
I don't see anything for core language features/compiler problems, so I'm guessing this should be Area-Meta (@joperezr )? 

Please feel free to move that is incorrect.
