### ISSUE TITLE
Test failure:tracing\\eventpipe\\eventsvalidation\\GCFinalizers\\GCFinalizers.cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#33464]
**Job:**
[runtime-coreclr crossgen2 outerloop:20200309.1](https://dev.azure.com/dnceng/public/_build/results?buildId=553593&view=results)

**Error message:**
```
Assert failure(PID 4372 [0x00001114], Thread: 4380 [0x111c]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! memcmp + 0x12 (0x00007ff83ebd4c82)\r\nCORECLR! Thread::VirtualUnwindCallFrame + 0x404 (0x00007ff83e39ca28)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1D6 (0x00007ff83e691526)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x6D (0x00007ff83e396e99)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ff83e39b6a8)
CORECLR! StackFrameIterator::Init + 0x213 (0x00007ff83e3994cf)
CORECLR! Thread::StackWalkFramesEx + 0x155 (0x00007ff83e39c2b5)
CORECLR! Thread::HandledJITCase + 0x23F (0x00007ff83e4346ab)
CORECLR! ThreadSuspend::SuspendRuntime + 0x444 (0x00007ff83e43a01c)
CORECLR! ThreadSuspend::SuspendEE + 0x2D7 (0x00007ff83e4398fb)
CORECLR! SampleProfiler::ThreadProc + 0x272 (0x00007ff83e999f22)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ff86abd84d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ff86d3ce8b1)
-----
.AV on tid=0x111c (4380), cxr=000000A6081FCC80, exr=000000A6081FD170
FAILED: false

CORECLR! CHECK::Trigger + 0x2CC (0x00007ff83e28c644)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x364 (0x00007ff83e3f6fe0)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x69 (0x00007ff83e3f6a61)
CORECLR! CLRVectoredExceptionHandler + 0x1C6 (0x00007ff83e3f69da)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x00007ff83e3f723a)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ff86d3c5ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ff86d39fa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ff86d40964a)
CORECLR! memcmp + 0x12 (0x00007ff83ebd4c82)
CORECLR! Thread::VirtualUnwindCallFrame + 0x404 (0x00007ff83e39ca28)
File: F:\\workspace\\_work\\1\\s\\src\\coreclr\\src\\vm\\excep.cpp Line: 7558
Image: C:\\h\\w\\A8950971\\p\\CoreRun.exe


Return code: 1\r\nRaw output file: C:\\h\\w\\A8950971\\w\\B4620A12\\e\\tracing\\eventpipe\\Reports\\tracing.eventpipe\\eventsvalidation\\GCFinalizers\\GCFinalizers.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
\" \"C:\\h\\w\\A8950971\\p\\CoreRun.exe\" \"C:\\h\\w\\A8950971\\p\\crossgen2\\crossgen2.dll\" C:\\h\\w\\A8950971\\w\\B4620A12\\e\\tracing\\eventpipe\\eventsvalidation\\GCFinalizers\\GCFinalizers.org -o:C:\\h\\w\\A8950971\\w\\B4620A12\\e\\tracing\\eventpipe\\eventsvalidation\\GCFinalizers\\GCFinalizers.dll --targetarch:x64 -O --inputbubble -r:\"C:\\h\\w\\A8950971\\p\\System.*.dll\" -r:\"C:\\h\\w\\A8950971\\p\\Microsoft.*.dll\" -r:\"C:\\h\\w\\A8950971\\p\\mscorlib.dll\" -r:C:\\h\\w\\A8950971\\w\\B4620A12\\e\\tracing\\eventpipe\\eventsvalidation\\GCFinalizers\\*.dll\"\r\nWarning: Method[GCFinalizers]Tracing.Tests.GCFinalizers.ProviderValidation+<>c.<.cctor>b__5_1(EventPipeEventSource)` was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard
Emitting R2R PE file: C:\h\w\A8950971\w\B4620A12\e\tracing\eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.dll
"C:\h\w\A8950971\p\corerun.exe" GCFinalizers.dll 
0.0s: ==TEST STARTING==
0.7s: Started sending sentinel events...
0.8s: Connecting to EventPipe...
1.5s: Connected to EventPipe with sessionID '0x1d5b1fab620'
1.5s: Creating EventPipeEventSource...
1.8s: EventPipeEventSource created
1.9s: Dynamic.All callback registered
1.9s: Running optional trace validator
2.1s: Finished running optional trace validator
2.1s: Starting stream processing...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A8950971\p
> C:\h\w\A8950971\w\B4620A12\e\tracing\eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.cmd
Expected: True
Actual: False
```

**Stack trace:**
`
at tracing_eventpipe._eventsvalidation_GCFinalizers_GCFinalizers_._eventsvalidation_GCFinalizers_GCFinalizers_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\tracing.eventpipe\tracing.eventpipe.XUnitWrapper.cs:line 431
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=553593&view=ms.vss-test-web.build-test-results-tab&runId=17470514&resultId=107271&paneView=debug

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr crossgen2 outerloop 20200411.1](https://dev.azure.com/dnceng/public/_build/results?buildId=597748&view=ms.vss-test-web.build-test-results-tab&runId=18829224&resultId=107324&paneView=debug)

failed test: tracing\\eventpipe\\eventsvalidation\\GCFinalizers\\GCFinalizers.cmd


Error message
~~~
Assert failure(PID 624 [0x00000270], Thread: 2712 [0x0a98]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! memcmp + 0x12 (0x00007ffe2d1c7632)
CORECLR! Thread::VirtualUnwindCallFrame + 0x311 (0x00007ffe2cabf3b1)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1B3 (0x00007ffe2cd42427)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x6D (0x00007ffe2caba429)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ffe2cabe56c)
CORECLR! StackFrameIterator::Init + 0x229 (0x00007ffe2cabc731)
CORECLR! Thread::StackWalkFramesEx + 0x11E (0x00007ffe2cabedaa)
CORECLR! Thread::HandledJITCase + 0x219 (0x00007ffe2cb187b5)
CORECLR! ThreadSuspend::SuspendRuntime + 0x46B (0x00007ffe2cb1de33)
CORECLR! ThreadSuspend::SuspendEE + 0x2A3 (0x00007ffe2cb1d657)
CORECLR! SampleProfiler::ThreadProc + 0x1EB (0x00007ffe2cfbb14b)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ffe5a0a84d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ffe5a96e8b1)
-----
.AV on tid=0xa98 (2712), cxr=000000ADD2C7D400, exr=000000ADD2C7D8F0
FAILED: false
CORECLR! CHECK::Trigger + 0x2CC (0x00007ffe2c9a6ad8)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x26F (0x00007ffe2ca1e87b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x86 (0x00007ffe2ca1e3fa)
CORECLR! CLRVectoredExceptionHandler + 0x1BF (0x00007ffe2ca1e353)
CORECLR! CLRVectoredExceptionHandlerShim + 0x189 (0x00007ffe2ca1ead9)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffe5a965ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffe5a93fa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffe5a9a964a)
CORECLR! memcmp + 0x12 (0x00007ffe2d1c7632)
CORECLR! Thread::VirtualUnwindCallFrame + 0x311 (0x00007ffe`2cabf3b1)
File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7558
Image: C:\h\w\B34B09C9\p\CoreRun.exe
Return code: 1
Raw output file: C:\h\w\B34B09C9\w\B79509F4\e\tracing\eventpipe\Reports\tracing.eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" "C:\h\w\B34B09C9\p\CoreRun.exe" "C:\h\w\B34B09C9\p\crossgen2\crossgen2.dll" C:\h\w\B34B09C9\w\B79509F4\e\tracing\eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.org -o:C:\h\w\B34B09C9\w\B79509F4\e\tracing\eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\B34B09C9\p\System..dll" -r:"C:\h\w\B34B09C9\p\Microsoft..dll" -r:"C:\h\w\B34B09C9\p\netstandard.dll" -r:"C:\h\w\B34B09C9\p\mscorlib.dll" -r:C:\h\w\B34B09C9\w\B79509F4\e\tracing\eventpipe\eventsvalidation\GCFinalizers\*.dll"
Emitting R2R PE file: C:\h\w\B34B09C9\w\B79509F4\e\tracing\eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.dll
"C:\h\w\B34B09C9\p\corerun.exe" GCFinalizers.dll
0.0s: ==TEST STARTING==
0.3s: Started sending sentinel events...
0.3s: Connecting to EventPipe...
0.3s: Connected to EventPipe with sessionID '0x1e121d61340'
0.3s: Creating EventPipeEventSource...
0.6s: EventPipeEventSource created
0.7s: Dynamic.All callback registered
0.7s: Running optional trace validator
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B34B09C9\p
> C:\h\w\B34B09C9\w\B79509F4\e\tracing\eventpipe\eventsvalidation\GCFinalizers\GCFinalizers.cmd
Expected: True
Actual: False


Stack trace
   at tracing_eventpipe._eventsvalidation_GCFinalizers_GCFinalizers_._eventsvalidation_GCFinalizers_GCFinalizers_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\tracing.eventpipe\tracing.eventpipe.XUnitWrapper.cs:line 431
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr gcstress-extra 20200419.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=607614&view=ms.vss-test-web.build-test-results-tab&runId=19092032&resultId=101941&paneView=debug)

failed test: Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest83\\Generated83\\Generated83.cmd


Error message
~~~
Assert failure(PID 5736 [0x00001668], Thread: 4320 [0x10e0]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::adjust_limit_clr + 0x3D9 (0x00007ff86f354ef9)
CORECLR! WKS::gc_heap::a_fit_segment_end_p + 0x25C (0x00007ff86f354548)
CORECLR! WKS::gc_heap::soh_try_fit + 0x384 (0x00007ff86f378444)
CORECLR! WKS::gc_heap::allocate_soh + 0x2E8 (0x00007ff86f356914)
CORECLR! WKS::gc_heap::try_allocate_more_space + 0x26E (0x00007ff86f379bda)
CORECLR! WKS::gc_heap::allocate_more_space + 0x31 (0x00007ff86f356605)
CORECLR! WKS::GCHeap::StressHeap + 0x2D0 (0x00007ff86f3534b0)
CORECLR! DoGcStress + 0x362 (0x00007ff86f0a9e86)
CORECLR! Thread::RedirectedHandledJITCase + 0x1F6 (0x00007ff86eddb78a)
CORECLR! RedirectedHandledJITCaseForGCStress_Stub + 0x26 (0x00007ff86f0659f6)
<no module>! <no symbol> + 0x0 (0x00007ff80f93753b)
<no module>! <no symbol> + 0x0 (0x000001870000ca30)
<no module>! <no symbol> + 0x0 (0x000001870000ca30)
<no module>! <no symbol> + 0x0 (0x0000001c9897d1b8)
<no module>! <no symbol> + 0x0 (0x0000001c9897d1b8)
-----
.AV on tid=0x10e0 (4320), cxr=0000001C9897C240, exr=0000001C9897C730
FAILED: false

CORECLR! CHECK::Trigger + 0x2CC (0x00007ff86ec66a98)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x26F (0x00007ff86ecde81b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x86 (0x00007ff86ecde39a)
CORECLR! CLRVectoredExceptionHandler + 0x1BF (0x00007ff86ecde2f3)
CORECLR! CLRVectoredExceptionHandlerShim + 0x189 (0x00007ff86ecdea79)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ff89cf45ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ff89cf1fa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ff89cf8964a)
CORECLR! WKS::gc_heap::adjust_limit_clr + 0x3D9 (0x00007ff86f354ef9)
CORECLR! WKS::gc_heap::a_fit_segment_end_p + 0x25C (0x00007ff86f354548)
 File: F:\\workspace\\_work\\1\\s\\src\\coreclr\\src\\vm\\excep.cpp Line: 7556
 Image: C:\\h\\w\\B82B097E\\p\\CoreRun.exe


Return code: 1
Raw output file: C:\\h\\w\\B82B097E\\w\\B0110972\\e\\Loader\\classloader\\Reports\\Loader.classloader\\TypeGeneratorTests\\TypeGeneratorTest83\\Generated83\\Generated83.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\h\\w\\B82B097E\\p\\corerun.exe\" Generated83.dll 
========================== Method Calling Test ==========================
valuetype MyStruct1331<class BaseClass0> on type MyStruct133
 -> EXPECTED: MyStruct133::Method7.1154<System.Object>()
 -> GOT: MyStruct133::Method7.1154<System.Object>()
valuetype MyStruct1331<class BaseClass0> on type MyStruct133
 -> EXPECTED: MyStruct133::Method4.1156()
 -> GOT: MyStruct133::Method4.1156()
valuetype MyStruct1331<class BaseClass0> on type MyStruct133
 -> EXPECTED: MyStruct133::Method5.1158()
 -> GOT: MyStruct133::Method5.1158()
valuetype MyStruct1331<class BaseClass0> on type MyStruct133
 -> EXPECTED: MyStruct133::Method6.1159<System.Object>()
 -> GOT: MyStruct133::Method6.1159<System.Object>()
class IBase22<class BaseClass1,class BaseClass1> on type valuetype MyStruct1331<class BaseClass0>
 -> EXPECTED: MyStruct133::Method7.MI.1155<System.Object>()
 -> GOT: MyStruct133::Method7.MI.1155<System.Object>()
class IBase11<class BaseClass0> on type valuetype MyStruct1331<class BaseClass0>
 -> EXPECTED: MyStruct133::Method4.MI.1157()
 -> GOT: MyStruct133::Method4.MI.1157()
class IBase11<class BaseClass0> on type valuetype MyStruct1331<class BaseClass0>
 -> EXPECTED: MyStruct133::Method5.1158()
 -> GOT: MyStruct133::Method5.1158()
class IBase11<class BaseClass0> on type valuetype MyStruct1331<class BaseClass0>
 -> EXPECTED: MyStruct133::Method6.MI.1160<System.Object>()
 -> GOT: MyStruct133::Method6.MI.1160<System.Object>()
class IBase22<class B


Stack trace
   at Loader_classloader._TypeGeneratorTests_TypeGeneratorTest83_Generated83_Generated83_._TypeGeneratorTests_TypeGeneratorTest83_Generated83_Generated83_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Loader.classloader\Loader.classloader.XUnitWrapper.cs:line 27397
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr gcstress-extra 20200426.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=618406&view=ms.vss-test-web.build-test-results-tab&runId=19372128&resultId=106685&paneView=debug)

failed test: Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest1157\\Generated1157\\Generated1157.cmd


Error message
~~~
Assert failure(PID 7344 [0x00001cb0], Thread: 9032 [0x2348]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::adjust_limit_clr + 0x3DB (0x00007ff82026d7c7)
CORECLR! WKS::gc_heap::a_fit_segment_end_p + 0x25C (0x00007ff82026ce18)
CORECLR! WKS::gc_heap::soh_try_fit + 0x278 (0x00007ff820291048)
CORECLR! WKS::gc_heap::allocate_soh + 0x2DC (0x00007ff82026f1fc)
CORECLR! WKS::gc_heap::try_allocate_more_space + 0x30A (0x00007ff82029296e)
CORECLR! WKS::gc_heap::allocate_more_space + 0x31 (0x00007ff82026eef9)
CORECLR! WKS::GCHeap::StressHeap + 0x2D0 (0x00007ff82026bd70)
CORECLR! DoGcStress + 0x362 (0x00007ff81ff668a6)
CORECLR! Thread::RedirectedHandledJITCase + 0x1F6 (0x00007ff81fcaf0aa)
CORECLR! RedirectedHandledJITCaseForGCStress_Stub + 0x26 (0x00007ff81fef9036)
<no module>! <no symbol> + 0x0 (0x00007ff7c086c71b)
<no module>! <no symbol> + 0x0 (0x000001d123be14b8)
<no module>! <no symbol> + 0x0 (0x000001d123be14b8)
<no module>! <no symbol> + 0x0 (0x000000a81677ce38)
<no module>! <no symbol> + 0x0 (0x000000a81677ce38)
-----
.AV on tid=0x2348 (9032), cxr=000000A81677B800, exr=000000A81677BCF0
FAILED: false

CORECLR! CHECK::Trigger + 0x2C9 (0x00007ff81fb47c6d)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2B2 (0x00007ff81fba178e)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x97 (0x00007ff81fba124f)
CORECLR! CLRVectoredExceptionHandler + 0x215 (0x00007ff81fba1195)
CORECLR! CLRVectoredExceptionHandlerShim + 0x1A0 (0x00007ff81fba1a00)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ff84f195ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ff84f16fa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ff84f1d964a)
CORECLR! WKS::gc_heap::adjust_limit_clr + 0x3DB (0x00007ff82026d7c7)
CORECLR! WKS::gc_heap::a_fit_segment_end_p + 0x25C (0x00007ff82026ce18)
 File: F:\\workspace\\_work\\1\\s\\src\\coreclr\\src\\vm\\excep.cpp Line: 7702
 Image: C:\\h\\w\\A8F20947\\p\\CoreRun.exe


Return code: 1
Raw output file: C:\\h\\w\\A8F20947\\w\\ADBB0976\\e\\Loader\\classloader\\Reports\\Loader.classloader\\TypeGeneratorTests\\TypeGeneratorTest1157\\Generated1157\\Generated1157.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\h\\w\\A8F20947\\p\\corerun.exe\" Generated1157.dll 
========================== Method Calling Test ==========================
class G1_C122<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G1_C12::ClassMethod1347.4870<System.Object>()
 -> GOT: G1_C12::ClassMethod1347.4870<System.Object>()
class G1_C122<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G2_C637::ClassMethod1346.MI.10875<System.Object>()
 -> GOT: G2_C637::ClassMethod1346.MI.10875<System.Object>()
class G1_C122<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G1_C12::Method6.4867<System.Object>()
 -> GOT: G1_C12::Method6.4867<System.Object>()
class G1_C122<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G1_C12::Method5.4866()
 -> GOT: G1_C12::Method5.4866()
class G1_C122<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G1_C12::Method4.4865()
 -> GOT: G1_C12::Method4.4865()
class G1_C122<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G2_C637::Method7.10874<System.Object>()
 -> GOT: G2_C637::Method7.10874<System.Object>()
class IBase22<class BaseClass0,class BaseClass0> on type class G3_C16291<class BaseClass0>
 -> EXPECTED: G2_C637::Method7.10874<System.Object>()
 -> GOT: G2_C637::Method7.10874<System.Object>()
class IBase11<class BaseClass0> on type class G3_C1629`1<class Bas


Stack trace
   at Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1157_Generated1157_Generated1157_._TypeGeneratorTests_TypeGeneratorTest1157_Generated1157_Generated1157_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Loader.classloader\Loader.classloader.XUnitWrapper.cs:line 131575
~~~

**Comment by BruceForstall** [comment]
There's some confusion here because not all of these are crossgen2. The last one is "CoreCLR Windows_NT x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open"

**Comment by mangod9** [comment]
Yeah I checked and this test passes with the original crossgen2 configuration. I am going to close this particular issue. @AriNuer please open a different one if this fails again for the jitstress configuration.
