### ISSUE TITLE
[mono][windows] Test failed: System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#33549]
1. `build.cmd -subsetcategory coreclr-mono-libraries -c Release -runtimeconfiguration Release /p:RuntimeFlavor=mono`
2. `cd src\libraries\System.Drawing.Common\tests`
3. `dotnet build /t:Test /p:RuntimeFlavor=mono /p:Configuration=Release`
```
System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(id: 2147483647, len: 2147483647, type: 32767, value: [0]) [FAIL]
System.MissingMethodException : No parameterless constructor defined for type 'System.Drawing.Imaging.PropertyItemInternal'.
Stack Trace:
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1987,0): at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1961,0): at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1842,0): at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(95,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(313,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(563,0): at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\src\System\Drawing\PropertyItemInternal.cs(74,0): at System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(IntPtr propdata, Int32 count)
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\src\System\Drawing\Image.Windows.cs(468,0): at System.Drawing.Image.get_PropertyItems()
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\tests\Imaging\PropertyItemTests.cs(50,0): at System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(Int32 id, Int32 len, Int16 type, Byte[] value)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Drawing.Drawing2D.Tests.ColorBlendTests.Ctor_LargeCount_ThrowsOutOfMemoryException [SKIP]
Condition(s) not met: "IsNotIntMaxValueArrayIndexSupported"
System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(id: -2147483648, len: -2147483648, type: -32768, value: [1, 1]) [FAIL]
System.MissingMethodException : No parameterless constructor defined for type 'System.Drawing.Imaging.PropertyItemInternal'.
Stack Trace:
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1987,0): at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1961,0): at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1842,0): at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(95,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(313,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(563,0): at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\src\System\Drawing\PropertyItemInternal.cs(74,0): at System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(IntPtr propdata, Int32 count)
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\src\System\Drawing\Image.Windows.cs(468,0): at System.Drawing.Image.get_PropertyItems()
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\tests\Imaging\PropertyItemTests.cs(50,0): at System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(Int32 id, Int32 len, Int16 type, Byte[] value)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(id: 0, len: 0, type: 0, value: []) [FAIL]
System.MissingMethodException : No parameterless constructor defined for type 'System.Drawing.Imaging.PropertyItemInternal'.
Stack Trace:
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1987,0): at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1961,0): at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1842,0): at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(95,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(313,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
    D:\dev\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(563,0): at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\src\System\Drawing\PropertyItemInternal.cs(74,0): at System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(IntPtr propdata, Int32 count)
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\src\System\Drawing\Image.Windows.cs(468,0): at System.Drawing.Image.get_PropertyItems()
    D:\dev\projects\runtime\src\libraries\System.Drawing.Common\tests\Imaging\PropertyItemTests.cs(50,0): at System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(Int32 id, Int32 len, Int16 type, Byte[] value)
    D:\dev\projects\runtime\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
----- end Fri 03/13/2020 12:25:04.14 ----- exit code -1073740791 ----------------------------------------------------------
```
OS: Win10 1909 (18363.657)

**Comment by danmosemsft** [comment]
-1073740791 STATUS_STACK_BUFFER_OVERRUN
