### ISSUE TITLE
Test failure ThreadTests.InterruptInFinallyBlockTest_SkipOnDesktopFramework

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#33568]
Test failure in https://github.com/dotnet/runtime/pull/33400
OSX Debug
System.Threading.Thread.Tests
```
-<test time="30.1078158" name="System.Threading.Threads.Tests.ThreadTests.InterruptInFinallyBlockTest_SkipOnDesktopFramework" result="Fail" method="InterruptInFinallyBlockTest_SkipOnDesktopFramework" type="System.Threading.Threads.Tests.ThreadTests">
-<failure exception-type="System.AggregateException">
-<message>
-<![CDATA[System.AggregateException : One or more errors occurred. (Assert.Throws() Failure\nExpected: typeof(System.Threading.ThreadInterruptedException)\nActual:   typeof(Xunit.Sdk.TrueException): Assert.True() Failure\nExpected: True\nActual:   False)\n---- Assert.Throws() Failure\nExpected: typeof(System.Threading.ThreadInterruptedException)\nActual:   typeof(Xunit.Sdk.TrueException): Assert.True() Failure\nExpected: True\nActual:   False\n-------- Assert.True() Failure\nExpected: True\nActual:   False]]>
</message>
-<stack-trace>
-<![CDATA[   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1() in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 52
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2() in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 57
   at System.Threading.Threads.Tests.ThreadTests.InterruptInFinallyBlockTest_SkipOnDesktopFramework() in /_/src/libraries/System.Threading.Thread/tests/ThreadTests.cs:line 966
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
----- Inner Stack Trace -----
   at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 154
   at System.Threading.Threads.Tests.ThreadTests.<>c__DisplayClass33_0.<InterruptInFinallyBlockTest_SkipOnDesktopFramework>b__1() in /_/src/libraries/System.Threading.Thread/tests/ThreadTests.cs:line 960
----- Inner Stack Trace -----
   at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 154
   at System.Threading.Threads.Tests.ThreadTests.<>c__DisplayClass33_0.<InterruptInFinallyBlockTest_SkipOnDesktopFramework>b__1() in /_/src/libraries/System.Threading.Thread/tests/ThreadTests.cs:line 960]]>
</stack-trace>
</failure>
</test>
```

**Comment by jaredpar** [comment]
Closing as this has not shown up in some time now
