### ISSUE TITLE
Test failure:System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.SendAsync_ConcurentSendReceive_Ok(shouldWaitForRequestBody: True, responseCode: OK)

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#33661]
**Job:**
[runtime-libraries outerloop:20200316.2](https://dev.azure.com/dnceng/public/_build/results?buildId=560648&view=results)
**Error message:**
```
System.IO.IOException : Got RST
```
**Stack ttrace:**
```
  at System.Net.Test.Common.Http2LoopbackConnection.ReadBodyAsync() in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 474
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.SendAsync_ConcurentSendReceive_Ok(Boolean shouldWaitForRequestBody, HttpStatusCode responseCode) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 2715
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=560648&view=ms.vss-test-web.build-test-results-tab&runId=17652986&resultId=102974&paneView=debug

**Comment by AriNuer** [comment]
Test `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.SendAsync_ConcurentSendReceive_Ok` failed again here [runtime-libraries outerloop:20200402.2](https://dev.azure.com/dnceng/public/_build/results?buildId=585200&view=results)
**Error message:**
```
System.IO.IOException : Got RST
```
**Stack trace:**
```
   at System.Net.Test.Common.Http2LoopbackConnection.ReadBodyAsync() in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 483
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.SendAsync_ConcurentSendReceive_Ok(Boolean shouldWaitForRequestBody, HttpStatusCode responseCode) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 2716
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=585200&view=ms.vss-test-web.build-test-results-tab&runId=18448380&resultId=102978&paneView=debug
