### ISSUE TITLE
CI builds failing with restore error

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#33837]
Looks like all our official builds are failing with the following restore exception:

```
installer.tasks -> F:\workspace\_work\1\s\artifacts\bin\installer.tasks\Debug\net46\installer.tasks.dll
installer.tasks -> F:\workspace\_work\1\s\artifacts\bin\installer.tasks\Debug\netstandard2.0\installer.tasks.dll
Determining projects to restore...
Microsoft.DotNet.ToolPackage.ResolverCacheInconsistentException: more than one row for coverlet.console-1.7.0-net5.0-any-coverlet
   at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.TryGetMatchingRestoredCommand(RestoredCommandIdentifier restoredCommandIdentifier, CacheRow[] cacheTable, RestoredCommand& restoredCommandList)
   at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.TryLoad(RestoredCommandIdentifier restoredCommandIdentifier, RestoredCommand& restoredCommand)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.PackageHasBeenRestored(ToolManifestPackage package, String targetFramework)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by safern** [comment]
cc: @ViktorHofer

**Comment by wli3** [comment]
Try override `DOTNET_CLI_HOME` 
to a temp location everytime.

https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Layout/redist/targets/OverlaySdkOnLKG.targets#L39

**Comment by wli3** [comment]
could mitigate it for now

**Comment by ViktorHofer** [comment]
A mitigation is already in process: https://github.com/dotnet/runtime/pull/33871. Let's discuss the right fix in the sdk issue.

**Comment by janvorli** [comment]
@ViktorHofer, @wli3, @safern I keep hitting this issue locally on my Linux box with Ubuntu 16.04. Latest master cleaned with `git clean -xdf`. DOTNET_CLI_HOME workaround works, but is someone working on a real fix?

**Comment by jaredpar** [comment]
@janvorli 

Have you tried nuking your NuGet package cache? Essentially run the following:

``` sh
dotnet nuget locals all --clear
```

It's possible an old package is cached that is impacting this restore. If that doesn't fix it though we should probably open a new issue to track this as it's unlikely to be related to this specific instance.

**Comment by janvorli** [comment]
@jaredpar that didn't help, the issue persists.

**Comment by jaredpar** [comment]
@janvorli can you open a new issue with the error that you're seeing locally? The error in this issue is specific to our official build so my assumption would be that there is a subtle difference here in what you're seeing. 

Also could you attach / share out the binary log for restore (add `-binaryLog` to the `build.cmd/sh` invocation). That should help narrow down what is going on.
