### ISSUE TITLE
CI failing with   Microsoft.DotNet.ToolPackage.ResolverCacheInconsistentException: more than one row for coverlet.console-1.7.0-net5.0-any-coverlet

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#33876]
https://dev.azure.com/dnceng/public/_build/results?buildId=567177

```
##[section]Starting: Build managed product components and packages
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
F:\workspace\_work\1\s\build.cmd -subsetCategory coreclr -subset corelib-nativecorelib-tools-packages  -arch x86 -c release  -ci
========================== Starting Command Output ===========================
##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "F:\workspace\_work\_temp\807b2795-821e-4a29-af16-ae20c592b5ea.cmd""
Clearing NuGet HTTP cache: C:\Users\vsagent\AppData\Local\NuGet\v3-cache
Local resources cleared.
F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.3.20168.11\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:F:\workspace\_work\1\s\artifacts\log\Release\Build.binlog /clp:Summary /logger:F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20168.2\tools\netcoreapp2.1\Microsoft.DotNet.Arcade.Sdk.dll /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:Configuration=Release /p:RepoRoot=F:\workspace\_work\1\s /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=False /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=False /p:Publish=False /p:ArchGroup=x86 /p:TargetArchitecture=x86 /p:subsetCategory=coreclr /p:subset=corelib-nativecorelib-tools-packages /warnaserror F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20168.2\tools\Build.proj
  Determining projects to restore...
  Restore completed in 28.89 sec for F:\workspace\_work\1\s\tools-local\tasks\installer.tasks\installer.tasks.csproj.
  installer.tasks -> F:\workspace\_work\1\s\artifacts\bin\installer.tasks\Debug\net46\installer.tasks.dll
  installer.tasks -> F:\workspace\_work\1\s\artifacts\bin\installer.tasks\Debug\netstandard2.0\installer.tasks.dll
  Determining projects to restore...
  Microsoft.DotNet.ToolPackage.ResolverCacheInconsistentException: more than one row for coverlet.console-1.7.0-net5.0-any-coverlet
     at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.TryGetMatchingRestoredCommand(RestoredCommandIdentifier restoredCommandIdentifier, CacheRow[] cacheTable, RestoredCommand& restoredCommandList)
     at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.TryLoad(RestoredCommandIdentifier restoredCommandIdentifier, RestoredCommand& restoredCommand)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.PackageHasBeenRestored(ToolManifestPackage package, String targetFramework)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
     at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
     at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
     at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
     at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
     at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
     at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
     at Microsoft.DotNet.Cli.Program.Main(String[] args)
F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20168.2\tools\Tools.proj(43,5): error MSB3073: The command ""F:\workspace\_work\1\s\.dotnet\dotnet.exe" tool restore" exited with code 1.
##[error].packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20168.2\tools\Tools.proj(43,5): error MSB3073: The command ""F:\workspace\_work\1\s\.dotnet\dotnet.exe" tool restore" exited with code 1.

Build FAILED.
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/33837
