### ISSUE TITLE
Microsoft.Extensions.DependencyInjection test failure on mono

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#33894]
This issue tracks DI test failing on Mono:
```
Microsoft.Extensions.DependencyInjection.Tests.ServiceProviderCompilationTest.CompilesInLimitedStackSpace
```

**Comment by ericstj** [comment]
Here's one of the failures:
https://helix.dot.net/api/2019-06-17/jobs/80e913aa-a462-4f20-be32-a4a2e16fc14c/workitems/Microsoft.Extensions.DependencyInjection.Tests/console

This test looks to create very deep type hierarchies then calls composes them via the DI system.  This would be very sensitive to the size used for each stackframe.  I'm guessing that mono is consuming more space per frame than coreclr was.

**Comment by ericstj** [comment]
Talked to @pakrym and he mentioned this test is tuned to barely pass on CoreCLR, so it probably needs tuning for mono (or mono can try to match coreclr here).

**Comment by maryamariyan** [comment]
Meanwhile port and enabling DI.External tests on PR https://github.com/dotnet/runtime/pull/37103 noticed some test failures on mono stacktrace like below:

```
System.InvalidOperationException : Sequence contains no matching element
      Stack Trace:
        /_/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs(28,0): at System.Linq.ThrowHelper.ThrowNoMatchException()
        /_/src/libraries/System.Linq/src/System/Linq/Single.cs(83,0): at System.Linq.Enumerable.Single[Type](IEnumerable`1 source, Func`2 predicate)
           at LamarCompiler.GeneratedType.FindType(Type[] generated)
           at LamarCompiler.GeneratedAssembly.CompileAll(IServiceVariableSource services)
           at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
           at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
           at Lamar.IoC.Instances.ConstructorInstance.ToResolver(Scope topScope)
           at Lamar.ServiceGraph.FindResolver(Type serviceType)
           at Lamar.IoC.Scope.TryGetInstance(Type serviceType)
           at Lamar.IoC.Scope.GetService(Type serviceType)
```
