### ISSUE TITLE
[Linux] Fail to build CoreFX v3.1.2

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#33921]
Hi,

It just hang there without response for more than 24 hours when `./build.sh` CoreFX [v3.1.2](https://github.com/dotnet/corefx/tree/v3.1.2) after thown such errors:

* System.OutOfMemoryException

```
MSBUILD : error MSB4166: /tmp/MSBuild_pid-30991_cafd8a5663e741649c48c3b9ef8a2da6.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 30991:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 2020-3-20 5:06:29 PM
MSBUILD : error MSB4166: System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
MSBUILD : error MSB4166:  ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
MSBUILD : error MSB4166:    at System.Threading.Thread.StartInternal()
MSBUILD : error MSB4166:    at System.Threading.Thread.Start()
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.InjectThread()
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.RequestThread()
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.RequestBuilder.DedicatedThreadsTaskScheduler.QueueTask(Task task)
MSBUILD : error MSB4166:    at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
MSBUILD : error MSB4166:    at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
MSBUILD : error MSB4166:    --- End of inner exception stack trace ---
MSBUILD : error MSB4166:    at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
MSBUILD : error MSB4166:    at System.Threading.Tasks.Task`1.StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
MSBUILD : error MSB4166:    at System.Threading.Tasks.TaskFactory.StartNew[TResult](Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.RequestBuilder.StartBuilderThread()
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.RequestBuilder.BuildRequest(NodeLoggingContext loggingContext, BuildRequestEntry entry)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BuildRequestEngine.ActivateBuildRequest(BuildRequestEntry entry)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass39_0.<SubmitBuildRequest>b__0()
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BuildRequestEngine.<>c__DisplayClass67_0.<QueueAction>b__0()
MSBUILD : error MSB4166: ===================
```

* ApiCompat failed

```
/home/zhaixiang/.nuget/packages/microsoft.dotnet.apicompat/1.0.0-beta.19577.5/build/Microsoft.DotNet.ApiCompat.targets(96,5): error : ApiCompat failed for '/home/zhaixiang/corefx-3.1.2/artifacts/bin/System.Security.SecureString/netcoreapp-Debug/System.Security.SecureString.dll' [/home/zhaixiang/corefx-3.1.2/src/System.Security.SecureString/src/System.Security.SecureString.csproj]
```

* Timeout

```
/home/zhaixiang/.nuget/packages/microsoft.dotnet.apicompat/1.0.0-beta.19577.5/build/Microsoft.DotNet.ApiCompat.targets(143,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/home/zhaixiang/corefx-3.1.2/src/System.Dynamic.Runtime/src/System.Dynamic.Runtime.csproj]
libust[12037/12037] : error : pthread_create global: Resource temporarily unavailable (in lttng_ust_init() at lttng-ust-comm.c:1409) [/home/zhaixiang/corefx-3.1.2/src/System.ObjectModel/src/System.ObjectModel.csproj]
libust[12037/12037] : error : pthread_create local: Resource temporarily unavailable (in lttng_ust_init() at lttng-ust-comm.c:1419) [/home/zhaixiang/corefx-3.1.2/src/System.ObjectModel/src/System.ObjectModel.csproj]
libust[11626/11626] : error : Timed out waiting for lttng-sessiond (in lttng_ust_init() at lttng-ust-comm.c:1444) [/home/zhaixiang/corefx-3.1.2/src/Microsoft.Bcl.HashCode/src/Microsoft.Bcl.HashCode.csproj]
```

Please give me some hint!

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
PING!

> It just hang there without response for more than 24 hours when ./build.sh CoreFX v3.1.2 ...

We will migrate corefx-mips64-dev to [v3.1.2](https://github.com/dotnet/corefx/tree/v3.1.2) and integrate it (same as coreclr-mips64-dev) into CI.  But here comes such issue when trying that for X86-64.

\cc @jkotas

**Comment by am11** [comment]
> libust[12037/12037] : error : pthread_create global: Resource temporarily unavailable (in lttng_ust_init() at lttng-ust-comm.c:1409) [/home/zhaixiang/corefx-3.1.2/src/System.ObjectModel/src/System.ObjectModel.csproj]

Is it happening on Ubuntu/Debian or which distro and version? It could be due to https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1624043, which points to https://unix.stackexchange.com/a/255603/373195 that may give some pointers.

nit: in this repository, [normally](https://github.com/dotnet/runtime/labels?q=arch-) `[Linux/x86]` is considered as x86-32, while `[Linux/x64]` is what this issue is about.

**Comment by jkotas** [comment]
Also, how much memory does the machine has? `OutOfMemoryException` suggests that you may need more memory; or if it is not an option - run the build with lower level of parallelism.

**Comment by xiangzhai** [comment]
Hi @am11 

Thanks for your kind response!

> Is it happening on Ubuntu/Debian or which distro and version?

It is CentOS Linux 3.10.0-957.21.3.el7.x86_64.  And I will try Ubuntu/Debian.

> nit: in this repository, normally [Linux/x86] is considered as x86-32, while [Linux/x64] is what this issue is about.

Thanks!

Hi @jkotas 

> how much memory does the machine has?

```
 total        used        free      shared  buff/cache   available
Mem:       65667212    18032396      322680      387864    47312136    45049576
Swap:      32964604     2227296    30737308
```

> or if it is not an option - run the build with lower level of parallelism

```
processor       : 55
model name      : Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
```

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
> > Is it happening on Ubuntu/Debian or which distro and version?
> 
> It is CentOS Linux 3.10.0-957.21.3.el7.x86_64. And I will try Ubuntu/Debian.

Succeed to build CoreFX v3.1.2 on Ubuntu 18.04.4 LTS 5.3.0-42-generic x86_64:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:31:42.97
```

Cheers,
Leslie Zhai

**Comment by xiangzhai** [comment]
\cc @theaoqi
