### ISSUE TITLE
Assert failure(PID 519 [0x00000207], Thread: 519 [0x0207]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#33944]
**Job:**
[runtime-coreclr gcstress0x3-gcstress0xc:20200322.1](https://dev.azure.com/dnceng/public/_build/results?buildId=569093&view=results)
**Failed tests:**
```
Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
Loader/classloader/generics/Layout/General/Base01d_seq_ser/Base01d_seq_ser.sh
Loader/classloader/generics/Layout/General/Base01b_seq/Base01b_seq.sh
Loader/classloader/generics/Layout/General/Base01c_seq_ser/Base01c_seq_ser.sh
```
**Error message:**
```
Assert failure(PID 519 [0x00000207], Thread: 519 [0x0207]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
File: /__w/1/s/src/coreclr/src/vm/object.cpp Line: 557
Image: /root/helix/work/correlation/corerun\n\n/root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh: line 275: 519 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun Base01b_seq_ser.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.519.dmp
Written 49348608 bytes (12048 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
Expected: True
Actual: False
```
**Stack trace:**
```
at Loader_classloader._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs:line 10713
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=569093&view=ms.vss-test-web.build-test-results-tab&runId=17862376&resultId=100706&paneView=debug

**Comment by AriNuer** [comment]
Same tests failed with `Assert failure(PID 1056 [0x00000420], Thread: 1056 [0x0420]): SanityCheck()`
**Job:**
[runtime-coreclr gcstress0x3-gcstress0xc:20200322.1](https://dev.azure.com/dnceng/public/_build/results?buildId=569093&view=results)
**Failed tests:**
```
Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
Loader/classloader/generics/Layout/General/Base01d_seq_ser/Base01d_seq_ser.sh
Loader/classloader/generics/Layout/General/Base01b_seq/Base01b_seq.sh
Loader/classloader/generics/Layout/General/Base01c_seq_ser/Base01c_seq_ser.sh
```
**Error message:**
```
Assert failure(PID 1056 [0x00000420], Thread: 1056 [0x0420]): SanityCheck()
File: /__w/1/s/src/coreclr/src/vm/methodtable.cpp Line: 9822
Image: /root/helix/work/correlation/corerun
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7eec2e08)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7eec2e08)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7eeb7a80)
/root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh: line 275: 1056 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.output.txt\nRaw output:
BEGIN EXECUTION\n/root/helix/work/correlation/corerun Base01b_seq_ser.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1056.dmp
Written 52273152 bytes (12762 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/classloader/generics/Layout/General/Base01b_seq_ser/Base01b_seq_ser.sh
Expected: True
Actual: False
```
**Stack trace:**
```
at Loader_classloader._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_._generics_Layout_General_Base01b_seq_ser_Base01b_seq_ser_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs:line 10713
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=569093&view=ms.vss-test-web.build-test-results-tab&runId=17862392&resultId=101012&paneView=debug

**Comment by janvorli** [comment]
This is a dup of #33366, even though the assert is slightly different, I am pretty sure the issue is the same.
