### ISSUE TITLE
[Mono] Test failures in linux CI because libgdiplus can't be loaded

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34008]
The following tests are disabled in mono's CoreFX.issues_linux.rsp, and start failing in linux CI (more specifically on RedHat) after enabling:
```
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.RoundtripManyObjectsInOneStream
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip
System.Resources.Tests.ResourceManagerTests.GetObject_Images
System.Resources.Tests.ResourceManagerTests.GetObject_Images_ResourceSet
System.Resources.Tests.ResourceManagerTests.GetResourceSet_Images
System.Resources.Extensions.Tests.PreserializedResourceWriterTests.BinaryFormattedResources
System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources
System.Resources.Extensions.Tests.PreserializedResourceWriterTests.BinaryFormattedResourcesWithoutTypeName
```
The example of stack trace:
```
System.Resources.Extensions.Tests.PreserializedResourceWriterTests.BinaryFormattedResources [FAIL]
    System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
    ---- System.DllNotFoundException : libgdiplus assembly:<unknown assembly> type:<unknown type> member:(null)
    Stack Trace:
    /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs(41,0): at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
    /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs(24,0): at System.Drawing.Bitmap..ctor(String filename)
    /_/src/libraries/System.Resources.Extensions/tests/TestData.cs(71,0): at System.Resources.Extensions.Tests.TestData.get_BinaryFormattedDrawing()
    /_/src/libraries/System.Resources.Extensions/tests/TestData.cs(48,0): at System.Resources.Extensions.Tests.TestData.get_BinaryFormatted()
    /_/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs(269,0): at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.BinaryFormattedResources()
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    ----- Inner Stack Trace -----
    /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(34,0): at System.Drawing.SafeNativeMethods.Gdip..cctor()
```

Those tests will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/33953

**Comment by danmosemsft** [comment]
@MaximLipnin libgdiplus is on these machines, presumably - and it's some issue with the Mono runtime? 

Presumably we will need to disable these tests for eg Android where I guess there is no libgdiplus but this sounds separate.

**Comment by MaximLipnin** [comment]
@danmosemsft Original comment for the disabled tests was `fail on Helix on RedHat systems because libgdiplus can't be loaded`. Perhaps, it's related to some runtime issue, for now I've just created the tracking issue with what I got from CI. As for Android, maybe @steveisok has something in the backlog.

**Comment by akoeplinger** [comment]
Yeah this should be specifically an issue on RedHat, other System.Drawing tests on e.g. Ubuntu work fine on Mono.

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
