### ISSUE TITLE
[Mono] Several tests fail in AssemblyLoadContext.InternalLoadFromPath

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34030]
The following tests are disabled in Mono's CoreFX.issues_linux.rsp file, and they fail after being enabled (at least on Ubuntu 18.04):
- System.Tests.ActivatorTests.TestingCreateInstanceFromObjectHandleFullSignature
- System.Tests.ActivatorTests.TestingCreateInstanceFromObjectHandle
- System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandleFullSignature
- System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandle

The example of failure:
```
System.Tests.ActivatorTests.TestingCreateInstanceFromObjectHandle(physicalFileName: "TestLoadAssembly.dll", assemblyFile: "testloadassembly.dll", type: "publicclassnodefaultconstructorsample", returnedFullNameType: "PublicClassNoDefaultConstructorSample", exceptionType: typeof(System.TypeLoadException)) [FAIL]
Assert.Throws() Failure
Expected: typeof(System.TypeLoadException)
Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly '/home/maxim/Desktop/runtime/artifacts/bin/System.Runtime.Tests/netcoreapp5.0-Unix-Release/testloadassembly.dll' or one of its dependencies.
---- System.IO.FileNotFoundException : Could not load file or assembly '/home/maxim/Desktop/runtime/artifacts/bin/System.Runtime.Tests/netcoreapp5.0-Unix-Release/testloadassembly.dll' or one of its dependencies.
Stack Trace:
    /home/maxim/Desktop/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.Mono.cs(37,0): at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs(309,0): at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs(335,0): at System.Reflection.Assembly.LoadFrom(String assemblyFile)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Activator.cs(51,0): at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Activator.cs(44,0): at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
    /home/maxim/Desktop/runtime/src/libraries/System.Runtime/tests/System/ActivatorTests.cs(630,0): at System.Tests.ActivatorTests.<>c__DisplayClass63_0.<TestingCreateInstanceFromObjectHandle>b__0()
    ----- Inner Stack Trace -----
    /home/maxim/Desktop/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.Mono.cs(37,0): at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs(309,0): at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs(335,0): at System.Reflection.Assembly.LoadFrom(String assemblyFile)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Activator.cs(51,0): at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    /home/maxim/Desktop/runtime/src/libraries/System.Private.CoreLib/src/System/Activator.cs(44,0): at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
    /home/maxim/Desktop/runtime/src/libraries/System.Runtime/tests/System/ActivatorTests.cs(630,0): at System.Tests.ActivatorTests.<>c__DisplayClass63_0.<TestingCreateInstanceFromObjectHandle>b__0()
```

These tests will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/33953

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/blob/5c2ee148ab63dc8b6a751cd6535a4e3d58f441ef/src/mono/mono/metadata/appdomain.c#L2705

**Comment by danmosemsft** [comment]
similar to https://github.com/dotnet/runtime/issues/34492

I'm assuming we follow CoreCLR

**Comment by CoffeeFlux** [comment]
This is also blocking `AppDomainTests.AssemblyResolve_FirstChanceException`.

**Comment by safern** [comment]
This also fails on Browser.
