### ISSUE TITLE
System.InvalidOperationException: StandardIn has not been redirected

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#34097]
I got the following exception from time to time in my application whereas the standard input is  redirected.

````
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in System.Diagnostics.Process.dll but was not handled in user code: 'StandardIn has not been redirected.'
   at System.Diagnostics.Process.get_StandardInput()
   at repro_process.Program.ExecuteProcessAsync(ProcessStartInfo psi) in /home/meziantou/repro-process/Program.cs:line 72
   at repro_process.Program.<>c.<Main>b__0_0(Int32 i) in /home/meziantou/repro-process/Program.cs:line 27
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
````

I tried to make a small repro of the code I have in production. Note that it doesn't always throw the exception. You may need to run the code 10 times to get the exception.

A similar exception sometimes occurs on `process.BeginErrorReadLine()` or `process.BeginOutputReadLine()` with a similar message indicating the the standard output/error is not redirected.

````c#
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace repro_process
{
    class Program
    {
        static void Main()
        {
            // In the actual code, multiple unit tests (xUnit) run in parallel so I tried to reproduce this behavior by using Parallel.For
            Parallel.For(0, 10000, i =>
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "git",
                    ArgumentList =
                    {
                        "config",
                        "--global",
                        "test.a",
                        "abc" + i,
                    },
                    RedirectStandardError = true,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                };
                ExecuteProcessAsync(psi).Wait(); // In the actual code, there is no wait/Result, only await
                Console.WriteLine(i);
            });
        }

        private static Task<bool> ExecuteProcessAsync(ProcessStartInfo psi)
        {
            var process = new System.Diagnostics.Process
            {
                StartInfo = psi,
                EnableRaisingEvents = true,
            };

            var tcs = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
            process.Exited += (sender, e) =>
            {
                try
                {
                    process.WaitForExit();
                    process.Dispose();
                    tcs.TrySetResult(true);
                }
                catch (Exception ex)
                {
                    tcs.SetException(ex);
                }
            };

            process.Start();

            if (psi.RedirectStandardOutput)
            {
                process.OutputDataReceived += (s, e) => { Console.WriteLine(e.Data); };
                process.BeginOutputReadLine();
            }

            if (psi.RedirectStandardError)
            {
                process.ErrorDataReceived += (s, e) => { Console.WriteLine(e.Data); };
                process.BeginErrorReadLine();
            }

            if (psi.RedirectStandardInput)
            {
                process.StandardInput.Close();
            }

            return tcs.Task;
        }
    }
}
````

**Environment:**
- .NET Core 3.1.3 but I also get the exception on 3.1.0 and 3.1.2

````
$> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

$> uname -a
Linux DESKTOP-TV4IPEK 4.4.0-19041-Microsoft #1-Microsoft Fri Dec 06 14:06:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux

$> lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
Stepping:            3
CPU MHz:             3301.000
CPU max MHz:         3301.0000
BogoMIPS:            6602.00
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap clflushopt ibrs ibpb stibp ssbd
````

Edit: I've just got the issue on Windows too (.NET Core 3.1.2).

**Comment by stephentoub** [comment]
Your `process.Exited` event handler is calling `process.Dispose`.  That can race with your subsequent call to `process.StandardInput.Close()`.  If the process exits and the process.Dispose is invoked before you access process.StandardInput, it'll throw.

**Comment by meziantou** [comment]
You are right! That's explain why it occurs very rarely. I've seen the new method `WaitForExitAsync` in the repository. I'll take inspiration from it to fix my code :)

**Comment by pakrym** [comment]
Wonder if it's worth throwing an `ObjectDisposedException` instead to make this situation more discoverable.

**Comment by stephentoub** [comment]
> Wonder if it's worth throwing an ObjectDisposedException instead to make this situation more discoverable.

Seems reasonable to consider.
cc: @adamsitnik @eiriktsarpalis
