### ISSUE TITLE
Test failure: access violation in CscBench.cmd, Compilation.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#34214]
Windows arm32 with:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=1
```

From attempt to re-enable "runtime-coreclr jitstress" testing:
https://dev.azure.com/dnceng/public/_build/results?buildId=574937&view=results

```
    JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd [FAIL]
      Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
         at System.Delegate.DelegateConstruct(System.Object, IntPtr)
         at System.Collections.Generic.ArraySortHelper`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(System.Span`1<CustomAttributeRow>, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
         at System.Array.Sort[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](CustomAttributeRow[], Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
         at System.Collections.Generic.List`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
         at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows()
         at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[], Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder)
         at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.PdbWriter, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Int32, System.Func`2<Microsoft.Cci.MetadataSizes,Int32>, Int32 ByRef, Int32 ByRef, Int32 ByRef, Microsoft.Cci.MetadataSizes ByRef)
         at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.Cci.MetadataWriter, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter)
         at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, System.Func`1<System.Object>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken)
         at CscBench.CompileBench()
         at CscBench.Bench()
         at CscBench.Main()
      
      Return code:      1
      Raw output file:      D:\h\w\B77C09AB\w\B1840A0E\e\JIT\Performance\Reports\JIT.Performance\CodeQuality\Roslyn\CscBench\CscBench.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\B77C09AB\p\corerun.exe" CscBench.dll 
      Expected: 100
      Actual: -1073741819
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\B77C09AB\p
      > D:\h\w\B77C09AB\w\B1840A0E\e\JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\JIT.Performance\JIT.Performance.XUnitWrapper.cs(7221,0): at JIT_Performance._CodeQuality_Roslyn_CscBench_CscBench_._CodeQuality_Roslyn_CscBench_CscBench_cmd()
      Output:
        Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
           at System.Delegate.DelegateConstruct(System.Object, IntPtr)
           at System.Collections.Generic.ArraySortHelper`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(System.Span`1<CustomAttributeRow>, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
           at System.Array.Sort[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](CustomAttributeRow[], Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
           at System.Collections.Generic.List`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
           at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows()
           at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[], Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder)
           at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.PdbWriter, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Int32, System.Func`2<Microsoft.Cci.MetadataSizes,Int32>, Int32 ByRef, Int32 ByRef, Int32 ByRef, Microsoft.Cci.MetadataSizes ByRef)
           at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.Cci.MetadataWriter, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter)
           at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, System.Func`1<System.Object>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken)
           at CscBench.CompileBench()
           at CscBench.Bench()
           at CscBench.Main()
        
        Return code:      1
        Raw output file:      D:\h\w\B77C09AB\w\B1840A0E\e\JIT\Performance\Reports\JIT.Performance\CodeQuality\Roslyn\CscBench\CscBench.output.txt
        Raw output:
        BEGIN EXECUTION
         "D:\h\w\B77C09AB\p\corerun.exe" CscBench.dll 
        Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\h\w\B77C09AB\p
        > D:\h\w\B77C09AB\w\B1840A0E\e\JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
```

It would be useful to understand why this doesn't fail in the Linux arm test run (e.g., is it run? is Windows different somehow?).

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Compilation.cmd fails with the same stack trace:
```
    managed\Compilation\Compilation\Compilation.cmd [FAIL]
      Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
         at System.Delegate.DelegateConstruct(System.Object, IntPtr)
         at System.Collections.Generic.ArraySortHelper`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(System.Span`1<CustomAttributeRow>, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
         at System.Array.Sort[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](CustomAttributeRow[], Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
         at System.Collections.Generic.List`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
         at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows()
         at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[], Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder)
         at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.PdbWriter, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Int32, System.Func`2<Microsoft.Cci.MetadataSizes,Int32>, Int32 ByRef, Int32 ByRef, Int32 ByRef, Microsoft.Cci.MetadataSizes ByRef)
         at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.Cci.MetadataWriter, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter)
         at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, System.Func`1<System.Object>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
         at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken)
         at Program.Main(System.String[])
      
      Return code:      1
      Raw output file:      D:\h\w\B77C09AB\w\A6AD09FE\e\managed\Compilation\Reports\managed.Compilation\Compilation\Compilation.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\B77C09AB\p\corerun.exe" Compilation.dll 
      Starting the test
      Using reference to: D:\h\w\B77C09AB\p\System.Private.CoreLib.dll
      Test compiled
      Expected: 100
      Actual: -1073741819
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\B77C09AB\p
      > D:\h\w\B77C09AB\w\A6AD09FE\e\managed\Compilation\Compilation\Compilation.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\managed.Compilation\managed.Compilation.XUnitWrapper.cs(140,0): at managed_Compilation._Compilation_Compilation_._Compilation_Compilation_cmd()
      Output:
        Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
           at System.Delegate.DelegateConstruct(System.Object, IntPtr)
           at System.Collections.Generic.ArraySortHelper`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(System.Span`1<CustomAttributeRow>, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
           at System.Array.Sort[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](CustomAttributeRow[], Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
           at System.Collections.Generic.List`1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(Int32, Int32, System.Collections.Generic.IComparer`1<CustomAttributeRow>)
           at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows()
           at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[], Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder)
           at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.PdbWriter, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Int32, System.Func`2<Microsoft.Cci.MetadataSizes,Int32>, Int32 ByRef, Int32 ByRef, Int32 ByRef, Microsoft.Cci.MetadataSizes ByRef)
           at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.Cci.MetadataWriter, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter)
           at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, System.Func`1<System.Object>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
           at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken)
           at Program.Main(System.String[])
        
        Return code:      1
        Raw output file:      D:\h\w\B77C09AB\w\A6AD09FE\e\managed\Compilation\Reports\managed.Compilation\Compilation\Compilation.output.txt
        Raw output:
        BEGIN EXECUTION
         "D:\h\w\B77C09AB\p\corerun.exe" Compilation.dll 
        Starting the test
        Using reference to: D:\h\w\B77C09AB\p\System.Private.CoreLib.dll
        Test compiled
        Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\h\w\B77C09AB\p
        > D:\h\w\B77C09AB\w\A6AD09FE\e\managed\Compilation\Compilation\Compilation.cmd
```

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr jitstress 20200424.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=616927&view=ms.vss-test-web.build-test-results-tab&runId=19337110&resultId=109010&paneView=debug)

failed test: 
JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
managed\\Compilation\\Compilation\\Compilation.cmd


Error message
~~~
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
 at System.Delegate.DelegateConstruct(System.Object, IntPtr)
 at System.Collections.Generic.ArraySortHelper1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(System.Span1<CustomAttributeRow>, System.Collections.Generic.IComparer1<CustomAttributeRow>)
 at System.Array.Sort[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](CustomAttributeRow[], Int32, Int32, System.Collections.Generic.IComparer1<CustomAttributeRow>)
 at System.Collections.Generic.List1[[Microsoft.Cci.MetadataWriter+CustomAttributeRow, Microsoft.CodeAnalysis, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Sort(Int32, Int32, System.Collections.Generic.IComparer1<CustomAttributeRow>)
 at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows()
 at Microsoft.Cci.MetadataWriter.PopulateTables(Int32[], Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder)
 at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.PdbWriter, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Microsoft.Cci.BlobBuilder, Int32, System.Func2<Microsoft.Cci.MetadataSizes,Int32>, Int32 ByRef, Int32 ByRef, Int32 ByRef, Microsoft.Cci.MetadataSizes ByRef)
 at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.Cci.MetadataWriter, System.Func1<System.IO.Stream>, System.Func1<System.IO.Stream>, Microsoft.Cci.PdbWriter)
 at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func1<System.IO.Stream>, System.Func1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, System.Threading.CancellationToken)
 at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, System.Func1<System.Object>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, System.Threading.CancellationToken)
 at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Collections.Generic.IEnumerable1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func1<System.Collections.Immutable.ImmutableArray1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
 at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Func1<System.Collections.Immutable.ImmutableArray1<Microsoft.CodeAnalysis.Diagnostic>>, System.Threading.CancellationToken)
 at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.Threading.CancellationToken)
 at CscBench.CompileBench()
 at CscBench.Bench()
 at CscBench.Main()

Return code: 1
Raw output file: D:\h\w\A9D20982\w\AF5D0967\e\JIT\Performance\Reports\JIT.Performance\CodeQuality\Roslyn\CscBench\CscBench.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A9D20982\p\corerun.exe" CscBench.dll 
Expected: 100
Actual: -1073741819
END EXECUTION


Stack trace
   at JIT_Performance._CodeQuality_Roslyn_CscBench_CscBench_._CodeQuality_Roslyn_CscBench_CscBench_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\JIT.Performance\JIT.Performance.XUnitWrapper.cs:line 7221
~~~

**Comment by AndyAyersMS** [comment]
@BruceForstall does this still repro?

**Comment by BruceForstall** [comment]
I haven't tried recently, but, also, we've stopped running Windows arm32 testing in CI. So, this is lower priority. However, if it fails on Windows arm32 then presumably there could be an issue on Linux arm32, so I don't want to push it out yet.

**Comment by BruceForstall** [comment]
No longer repros. Closing.
