### ISSUE TITLE
Files enumeration throw an exception on Linux but succeed on Windows

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/runtime#34264]
When calling `Directory.EnumerateFiles` on Windows when the directory does not exist, the enumerator returns 0 items. 
On Linux, an exception is raised: 
```
   System.IO.DirectoryNotFoundException : Could not find a part of the path '/home/runner/.config/.myFolder'.
  Stack Trace:
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
```

A snippet for repo:
```C#
string root = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
string directory = Path.Combine(root, ".myFolder");
foreach (var filename in Directory.EnumerateFiles(directory, "*.token", SearchOption.TopDirectoryOnly))
{
   Console.WriteLine(filename);
}
```

A workaround is to wrap the code with `Directory.Exists`.

EDIT: Edited by @stephentoub to remove the File.Delete call, just in case someone tries this and ends up deleting something.

**Comment by stephentoub** [comment]
> When calling Directory.EnumerateFiles on Windows when the directory does not exist, the enumerator returns 0 items.

What version are you using?  When I test it, I get a DirectoryNotFoundException, on Windows, with both .NET Core 3.1 and .NET 5:
```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\stoub\AppData\Roaming\.myFolder'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at Program.Main() in C:\Users\stoub\source\repos\ConsoleApp164\ConsoleApp164\Program.cs:line 10
```

**Comment by stephentoub** [comment]
There's also a test for a non-existent path, validating it throws a DirectoryNotFoundException:
https://github.com/dotnet/runtime/blob/8772dd31552d110aa217463c064f06b81c2a0e7d/src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str.cs#L53

**Comment by danmosemsft** [comment]
Could it be in your Windows case @ycrumeyrolle the directory does exist but is hidden? Can you try it on another folder? Or run `attrib` in the folder above and see whether it shows?

This issue is unrelated, but made me think of that; https://github.com/dotnet/runtime/issues/33475

**Comment by ycrumeyrolle** [comment]
My bad... 
On my local machine the directory was existing, but the CI servers are clean workspaces. 
The issue was a disabled test on Linux... And this test is supposed to create the folder then to remove it, but the removal was still not implemented. 
So the Windows environment had a directory that should be deleted, and the Linux environment was not running the same tests. Fixed on my side, and always throwing the same exception on Linux & Windows.
