### ISSUE TITLE
[Mono] Tests fail on windows due to Type.GetTypeFromCLSID not implemented

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34328]
The tests below are disabled in Mono's `CoreFX.issues_windows.rsp` file. After enabling they still fail. I'll move them into respective xunit tests as `ActiveIssue`. 
- System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs_CornerCase_CLSIDConstructor
- System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs_Negative_Null
- System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs_Negative_NonRuntimeType
- System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath
- System.Tests.TypeTests.* (invoke Type.GetTypeFromCLSID in TypeTests cctor)

```
System.Tests.TypeTests.IsVariableBoundArray_FalseForByRefSZArrayType [FAIL]
System.TypeInitializationException : The type initializer for 'System.Tests.TypeTests' threw an exception.
---- System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(858,0): at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
    ----- Inner Stack Trace -----
    _\src\libraries\System.Runtime\tests\System\Type\TypeTests.cs(60,0): at System.Tests.TypeTests..cctor()
```

**Comment by danmosemsft** [comment]
@MaximLipnin could you perhaps attach the testResults.xml? The stack above only applies to one of the tests. The xml file would show the assert or exception causing the others to fail.

**Comment by danmosemsft** [comment]
* `System.Tests.TypeTests.* (invoke Type.GetTypeFromCLSID in TypeTests cctor)` is because Type.GetTypeFromCLSID is not supported on Mono. It just needs disabling against something like "PlatformDetection.SupportsComInterop"
* Same for System.Reflection.Tests.MemberInfoTests.HasSameMetadataDefinitionAs_CornerCase_CLSIDConstructor
* All the other MemberInfoTests directly or indirectly use this API. For some This line needs changing so they can pass:
```
        private static IEnumerable<Type> NegativeTypeDataRaw
        {
            get
            {
...
                if (PlatformDetection.IsWindows)
                    yield return Type.GetTypeFromCLSID(new Guid("DCA66D18-E253-4695-9E08-35B54420AFA2"));
```

System.Reflection.Tests.AssemblyTests.LoadFile_ValidPEBadIL_ThrowsBadImageFormatExceptionWithPath is probably simply because Mono does not include the path in the BadImageFormatException. That's a small bug fix for the Mono runtime.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by MichalStrehovsky** [comment]
I'm fixing the annotations in #87907, but I'm not removing the ActiveIssue - the exclusion on TypeTests disables a lot of tests and from my past experience there will be something else that is failing and I don't want to spend time/waste CI on.
