### ISSUE TITLE
[Mono] Exceptions not being thrown for certain misuses of threading primitives

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34366]
The following tests are disabled in Mono's CoreFX.issues_windows.rsp file and still fail locally after enabling:
- System.Threading.Tests.WaitHandleTests.SignalAndWait
- System.Threading.Tests.WaitHandleTests.WaitAll_SameNames
- System.Threading.Tests.WaitHandleTests.WaitAny_MaxHandles_STA

The related output
```
System.Threading.Tests.WaitHandleTests.SignalAndWait(toSignal: Mutex { Handle = 1644, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, toWaitOn: AutoResetEvent { Handle = 1688, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, callSignalAndWait: Func`3 { Method = Boolean <SignalAndWait_MemberData>b__24_0(System.Threading.WaitHandle, System.Threading.WaitHandle), Target = <>c { } }, skipInfiniteWaitTests: True) [FAIL]
Assert.Throws() Failure
Expected: typeof(System.ApplicationException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(362,0): at System.Threading.Tests.WaitHandleTests.SignalAndWait(WaitHandle toSignal, AutoResetEvent toWaitOn, Func`3 callSignalAndWait, Boolean skipInfiniteWaitTests)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Assert.Throws() Failure
System.Threading.Tests.WaitHandleTests.SignalAndWait(toSignal: Mutex { Handle = 1644, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, toWaitOn: AutoResetEvent { Handle = 1688, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, callSignalAndWait: Func`3 { Method = Boolean <SignalAndWait_MemberData>b__24_1(System.Threading.WaitHandle, System.Threading.WaitHandle), Target = <>c { } }, skipInfiniteWaitTests: False) [FAIL]
Expected: typeof(System.ApplicationException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(362,0): at System.Threading.Tests.WaitHandleTests.SignalAndWait(WaitHandle toSignal, AutoResetEvent toWaitOn, Func`3 callSignalAndWait, Boolean skipInfiniteWaitTests)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Threading.Tests.WaitHandleTests.SignalAndWait(toSignal: Mutex { Handle = 1644, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, toWaitOn: AutoResetEvent { Handle = 1688, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, callSignalAndWait: Func`3 { Method = Boolean <SignalAndWait_MemberData>b__24_2(System.Threading.WaitHandle, System.Threading.WaitHandle), Target = <>c { } }, skipInfiniteWaitTests: False) [FAIL]
Assert.Throws() Failure
Expected: typeof(System.ApplicationException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(362,0): at System.Threading.Tests.WaitHandleTests.SignalAndWait(WaitHandle toSignal, AutoResetEvent toWaitOn, Func`3 callSignalAndWait, Boolean skipInfiniteWaitTests)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Threading.Tests.WaitHandleTests.SignalAndWait(toSignal: Semaphore { Handle = 1708, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, toWaitOn: AutoResetEvent { Handle = 1688, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, callSignalAndWait: Func`3 { Method = Boolean <SignalAndWait_MemberData>b__24_0(System.Threading.WaitHandle, System.Threading.WaitHandle), Target = <>c { } }, skipInfiniteWaitTests: True) [FAIL]
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(368,0): at System.Threading.Tests.WaitHandleTests.SignalAndWait(WaitHandle toSignal, AutoResetEvent toWaitOn, Func`3 callSignalAndWait, Boolean skipInfiniteWaitTests)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Threading.Tests.WaitHandleTests.SignalAndWait(toSignal: Semaphore { Handle = 1708, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, toWaitOn: AutoResetEvent { Handle = 1688, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, callSignalAndWait: Func`3 { Method = Boolean <SignalAndWait_MemberData>b__24_1(System.Threading.WaitHandle, System.Threading.WaitHandle), Target = <>c { } }, skipInfiniteWaitTests: False) [FAIL]
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(368,0): at System.Threading.Tests.WaitHandleTests.SignalAndWait(WaitHandle toSignal, AutoResetEvent toWaitOn, Func`3 callSignalAndWait, Boolean skipInfiniteWaitTests)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Threading.Tests.WaitHandleTests.SignalAndWait(toSignal: Semaphore { Handle = 1708, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, toWaitOn: AutoResetEvent { Handle = 1688, SafeWaitHandle = SafeWaitHandle { IsClosed = False, IsInvalid = False } }, callSignalAndWait: Func`3 { Method = Boolean <SignalAndWait_MemberData>b__24_2(System.Threading.WaitHandle, System.Threading.WaitHandle), Target = <>c { } }, skipInfiniteWaitTests: False) [FAIL]
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(368,0): at System.Threading.Tests.WaitHandleTests.SignalAndWait(WaitHandle toSignal, AutoResetEvent toWaitOn, Func`3 callSignalAndWait, Boolean skipInfiniteWaitTests)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
=======================
System.Threading.Tests.WaitHandleTests.WaitAll_SameNames [FAIL]
Assert.Throws() Failure
Expected: typeof(System.ArgumentException)
Actual:   (No exception was thrown)
Stack Trace:
    _\src\libraries\Common\tests\CoreFx.Private.TestUtilities\System\AssertExtensions.cs(121,0): at System.AssertExtensions.Throws[ArgumentException](String expectedParamName, Func`1 testCode)
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(169,0): at System.Threading.Tests.WaitHandleTests.WaitAll_SameNames()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)          
=======================
System.Threading.Tests.WaitHandleTests.WaitAny_MaxHandles_STA [FAIL]
System.InvalidOperationException : Failed to set the specified COM apartment state.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs(234,0): at System.Threading.Thread.SetApartmentState(ApartmentState state)
    _\src\libraries\System.Runtime\tests\System\Threading\WaitHandleTests.cs(106,0): at System.Threading.Tests.WaitHandleTests.WaitAny_MaxHandles_STA()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
They will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by ericstj** [comment]
Most appear to be a mix of missing this behavior on Mono:
https://github.com/dotnet/runtime/blob/ab6e225d0c3e3b8d2c085ab68f8a6511a64dc562/src/libraries/System.Runtime/tests/System/Threading/WaitHandleTests.cs#L353

Last one is #34360

Lets let this issue track the behavior of WaitHandles on mono.  Needs to be updated to match exception behavior or net core.

**Comment by ericstj** [comment]
So this should track:
Signaling an already signaled Mutex should throw an ApplicationException.
Signaling an already signaled Semaphore should throw InvalidOperationException.
WaitAll on array with named Mutex containing more than one Mutex with same name should throw ArgumentException.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0
