### ISSUE TITLE
CoreCLR tests on Mono runtime : crash running Interop/COM/Reflection/Reflection/Reflection.sh

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#34371]
Crash seen when running the following CoreCLR test on the mono runtime from the dotnet\runtime repo. 
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/ Interop/COM/Reflection/Reflection/Reflection.sh”

Crash report : 

 =================================================================
          External Debugger Dump:
          =================================================================
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/COM/Reflection/Reflection/Reflection.sh: line 275: 77251 Abort trap: 6           $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/COM/Reports/Interop.COM/Reflection/Reflection/Reflection.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun Reflection.dll ''
          Scenario: ReflectionLoad
          ArrayTesting
          ColorTesting
          ConsumeNETServerTesting
          DispatchTesting
          ErrorMarshalTesting
          LicenseTesting
          MockLicenseProvider
          NumericTesting
          StringTesting
          INumericTesting
          IArrayTesting
          IStringTesting
          HResult
          IErrorMarshalTesting
          IDispatchTesting_Exception
          HFA_4
          IDispatchTesting
          IEventTesting
          TestingEvents
          IAggregationTesting
          IColorTesting
          ILicenseTesting
          IConsumeNETServer
          Guids
          IEnumVARIANT
          ContextMenu
          MockLicense
          Scenario: TypeIsComObject
          ComImport Class's IsCOMObject should return true
          TypeIsComObject Failed
          Scenario: ActivateCOMType
          cant resolve internal call to "NETServer.ContextMenu::.ctor" (tested without signature also)
          
          Your mono runtime and class libraries are out of sync.
          The out of sync library is: /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/COM/Reflection/Reflection/NETServer.dll
          
          When you update one from git you need to update, compile and install
          the other too.
          Do not report this as a bug unless you're sure you have updated correctly:
          you probably have a broken mono install.
          If you see other errors or faults after this message they are probably related
          and you need to fix your mono install first.
          * Assertion: should not be reached at /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/mono/metadata/marshal.c:3513
          
          
          =================================================================
          Native Crash Reporting
          =================================================================
          Got a abrt while executing native code. This usually indicates
          a fatal error in the mono runtime or one of the native libraries 
          used by your application.
          =================================================================
          
          =================================================================
          Native stacktrace:
          =================================================================
          0x10a2914b2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_dump_native_crash_info
          0x10a233105 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_handle_native_crash
          0x10a290abf - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : sigabrt_signal_handler
          0x7fff728f342d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
          0x0 - Unknown
          0x7fff727c8a1c - /usr/lib/system/libsystem_c.dylib : abort
          0x10a44e117 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_assert_abort
          0x10a42e117 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_log_write_logfile
          0x10a44e5a5 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_g_logv_nofree
          0x10a44e72f - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_assertion_message
          0x10a44e787 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_assertion_message_unreachable
          0x10a344364 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_marshal_get_native_wrapper
          0x10a1923d3 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_with_opt
          0x10a196993 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_runtime_invoke
          0x10a36c2c8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_invoke_checked
          0x10a373e46 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_try_invoke_array
          0x10a31eed4 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : ves_icall_InternalInvoke
          0x10a32aba4 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : ves_icall_InternalInvoke_raw
          0x10bfc41b9 - Unknown
          0x10bfc1bf3 - Unknown
          
          =================================================================
          Telemetry Dumper:
          =================================================================
          Pkilling 0x123145443520512x from 0x4513787328x
          Entering thread summarizer pause from 0x4513787328x
          Finished thread summarizer pause from 0x4513787328x.
          
          Waiting for dumping threads to resume
          
          =================================================================
          Basic Fault Address Reporting
          =================================================================
          Memory around native instruction pointer (0x7fff728417fa):0x7fff728417ea  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
          0x7fff728417fa  73 08 48 89 c7 e9 85 a2 ff ff c3 90 90 90 b8 53  s.H............S
          0x7fff7284180a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 6d a2  ...I....s.H...m.
          0x7fff7284181a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....
          
          =================================================================
          Managed Stacktrace:
          =================================================================
            at <unknown> <0xffffffff>
            at System.Reflection.RuntimeConstructorInfo:InternalInvoke <0x000b8>
            at System.Reflection.RuntimeConstructorInfo:InternalInvoke <0x0008a>
            at System.RuntimeType:CreateInstanceMono <0x00202>
            at System.RuntimeType:CreateInstanceSlow <0x00082>
            at System.RuntimeType:CreateInstanceDefaultCtor <0x00082>
            at System.Activator:CreateInstance <0x000ba>
            at System.Activator:CreateInstance <0x00052>
            at System.Activator:CreateInstance <0x00042>
            at Reflection:ActivateCOMType <0x0009a>
            at Reflection:Main <0x000ba>
            at <Module>:runtime_invoke_int <0x000a5>
          =================================================================
          Expected: 100
          Actual: 134
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/COM/Reflection/Reflection/Reflection.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.COM/Interop.COM.XUnitWrapper.cs(140,0): at Interop_COM._Reflection_Reflection_Reflection_._Reflection_Reflection_Reflection_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by CoffeeFlux** [comment]
Part of the problem here seems to be that we're running COM tests with `DISABLE_COM` defined. The assertion is in `mono_marshal_get_native_wrapper`:
```
	if (MONO_CLASS_IS_IMPORT (method->klass)) {
		/* The COM code is not AOT compatible, it calls mono_custom_attrs_get_attr_checked () */
		if (aot)
			return method;
#ifndef DISABLE_COM
		return mono_cominterop_get_native_wrapper (method);
#else
		g_assert_not_reached ();
#endif
	}
```

Which is called from `compile_special`:
```
		MonoMethod *nm = mono_marshal_get_native_wrapper (method, TRUE, mono_aot_only);
```

The line in the test causing the crash:
```
            var contextMenu = (NETServer.ContextMenu)Activator.CreateInstance(typeof(NETServer.ContextMenu));

```
where NETServer.ContextMenu is:
```
    [ComImport]
    [Guid("09799AFB-AD67-11d1-ABCD-00C04FC30936")]
    public class ContextMenu
    {
    }
```

I'm not sure what the expected behavior is when calling a COM method despite building with `DISABLE_COM`, but I think this might be a codegen issue and we shouldn't be trying to call into the marshalling code at all? We probably should also not be running the COM tests with COM disabled.

**Comment by SamMonoRT** [comment]
@alexischr - sending this your way. Based on your investigations and comments from CoffeeFlux above, if you think this is an actual codegen issue, please assign it back to me.

**Comment by SamMonoRT** [comment]
moving to 7.0
