### ISSUE TITLE
CoreCLR tests on Mono runtime : crash running Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#34374]
Crash seen when running the following CoreCLR test on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh”

Crash report :

=================================================================
          External Debugger Dump:
          =================================================================
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh: line 282: 77280 Abort trap: 6           $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/Reports/Interop.ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun ICustomMarshaler.dll ''
          Discovering...
          Running 25 of 25 tests...
          * Assertion at /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/mono/metadata/marshal-ilgen.c:93, condition `method' not met, function:get_method_nofail, Could not lookup method GetCustomMarshalerInstance in Marshal
          
          
          =================================================================
          Native Crash Reporting
          =================================================================
          Got a abrt while executing native code. This usually indicates
          a fatal error in the mono runtime or one of the native libraries 
          used by your application.
          =================================================================
          
          =================================================================
          Native stacktrace:
          =================================================================
          0x107fca4b2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_dump_native_crash_info
          0x107f6c105 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_handle_native_crash
          0x107fc9abf - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : sigabrt_signal_handler
          0x7fff728f342d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
          0x0 - Unknown
          0x7fff727c8a1c - /usr/lib/system/libsystem_c.dylib : abort
          0x108187117 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_assert_abort
          0x108167117 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_log_write_logfile
          0x1081875a5 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_g_logv_nofree
          0x10818772f - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monoeg_assertion_message
          0x108106340 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_mb_emit_auto_layout_exception
          0x1080fcd98 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : emit_marshal_custom_ilgen
          0x10807c77b - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_emit_marshal
          0x108101a96 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : emit_native_wrapper_ilgen
          0x10807d85c - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_marshal_get_native_wrapper
          0x107eee0f8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_method_to_ir
          0x107ec56b9 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mini_method_compile
          0x107ec7bbc - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_inner
          0x107ecb9f2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_with_opt
          0x107f6f675 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_delegate_trampoline
          0x10834c013 - Unknown
          0x10bd89088 - Unknown
          0x10bd88fb3 - Unknown
          0x107ecff9e - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_runtime_invoke
          0x1080a52c8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_invoke_checked
          0x1080acc4e - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_try_invoke_array
          0x108057ed4 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : ves_icall_InternalInvoke
          0x108063ba4 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : ves_icall_InternalInvoke_raw
          0x10bbf29e9 - Unknown
          0x10bbf24f9 - Unknown
          0x10bd8819b - Unknown
          0x10bd88073 - Unknown
          0x10bd8796b - Unknown
          0x10bd877f3 - Unknown
          0x10bd86fb3 - Unknown
          0x10bd86e4b - Unknown
          0x10bd85e63 - Unknown
          0x10bd85d33 - Unknown
          0x10bd830ab - Unknown
          0x10bd82f73 - Unknown
          0x10bd827d3 - Unknown
          0x10bd8262b - Unknown
          0x10bd81591 - Unknown
          0x10bd81233 - Unknown
          0x10bd8109b - Unknown
          0x10bd8085b - Unknown
          0x10bd80733 - Unknown
          0x10bd7f2db - Unknown
          0x10bd7f1a3 - Unknown
          0x10bd7d4bb - Unknown
          0x10bd7cfb3 - Unknown
          0x10bd7ce83 - Unknown
          0x10bd7c4ce - Unknown
          0x10bd7bc6b - Unknown
          0x10bd7bb33 - Unknown
          0x10bd7ac7b - Unknown
          0x10bd7ab53 - Unknown
          0x10bd6a1c1 - Unknown
          0x10bd694db - Unknown
          0x10bd69393 - Unknown
          0x10bd652e3 - Unknown
          0x10bd651b3 - Unknown
          0x10bd64205 - Unknown
          0x10bd63b3b - Unknown
          0x10bd63a03 - Unknown
          0x10bcfe423 - Unknown
          0x10bcfe0f3 - Unknown
          0x10bcfd198 - Unknown
          0x10bb5a2c3 - Unknown
          0x10bcfca63 - Unknown
          0x10bcf58c3 - Unknown
          0x10bb5aac6 - Unknown
          0x10bb5a2c3 - Unknown
          0x10bb59e6b - Unknown
          
          =================================================================
          Telemetry Dumper:
          =================================================================
          Pkilling 0x123145466441728x from 0x123145474879488x
          Pkilling 0x123145485426688x from 0x123145474879488x
          Pkilling 0x123145464332288x from 0x123145474879488x
          Pkilling 0x123145483317248x from 0x123145474879488x
          Pkilling 0x123145481207808x from 0x123145474879488x
          Pkilling 0x123145479098368x from 0x123145474879488x
          Pkilling 0x123145476988928x from 0x123145474879488x
          Pkilling 0x123145495973888x from 0x123145474879488x
          Pkilling 0x123145493864448x from 0x123145474879488x
          Pkilling 0x123145472770048x from 0x123145474879488x
          Pkilling 0x123145491755008x from 0x123145474879488x
          Pkilling 0x123145470660608x from 0x123145474879488x
          Pkilling 0x123145489645568x from 0x123145474879488x
          Pkilling 0x123145468551168x from 0x123145474879488x
          Pkilling 0x123145487536128x from 0x123145474879488x
          Pkilling 0x4521860544x from 0x123145474879488x
          Entering thread summarizer pause from 0x123145474879488x
          Finished thread summarizer pause from 0x123145474879488x.
          
          Waiting for dumping threads to resume
          
          =================================================================
          Basic Fault Address Reporting
          =================================================================
          Memory around native instruction pointer (0x7fff728417fa):0x7fff728417ea  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
          0x7fff728417fa  73 08 48 89 c7 e9 85 a2 ff ff c3 90 90 90 b8 53  s.H............S
          0x7fff7284180a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 6d a2  ...I....s.H...m.
          0x7fff7284181a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....
          
          =================================================================
          Managed Stacktrace:
          =================================================================
            at <unknown> <0xffffffff>
            at Xunit.Assert:RecordException <0x00057>
            at Xunit.Assert:Throws <0x00062>
            at System.Runtime.InteropServices.Tests.ICustomMarshalerTests:Parameter_GetInstanceMethodReturnsVoid_ThrowsApplicationException <0x00122>
            at System.Object:runtime_invoke_void__this__ <0x000b0>
            at <unknown> <0xffffffff>
            at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000b8>
            at System.Reflection.RuntimeMethodInfo:Invoke <0x0016a>
            at System.Reflection.MethodBase:Invoke <0x00058>
            at Xunit.Sdk.TestInvoker`1:CallTestMethod <0x0005a>
            at <<InvokeTestMethodAsync>b__1>d:MoveNext <0x0040a>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0010a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00042>
            at <>c__DisplayClass48_1:<InvokeTestMethodAsync>b__1 <0x000de>
            at <AggregateAsync>d__4:MoveNext <0x000f5>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0010a>
            at Xunit.Sdk.ExecutionTimer:AggregateAsync <0x000e2>
            at <>c__DisplayClass48_1:<InvokeTestMethodAsync>b__0 <0x0018a>
            at <RunAsync>d__9:MoveNext <0x000a0>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00102>
            at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000da>
            at <InvokeTestMethodAsync>d__48:MoveNext <0x003ba>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00112>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestInvoker`1:InvokeTestMethodAsync <0x0010e>
            at Xunit.Sdk.XunitTestInvoker:InvokeTestMethodAsync <0x0013a>
            at <<RunAsync>b__47_0>d:MoveNext <0x00779>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0011a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestInvoker`1:<RunAsync>b__47_0 <0x000e6>
            at <RunAsync>d__10`1:MoveNext <0x000cb>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00102>
            at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000fa>
            at Xunit.Sdk.TestInvoker`1:RunAsync <0x0012a>
            at Xunit.Sdk.XunitTestRunner:InvokeTestMethodAsync <0x0010a>
            at <InvokeTestAsync>d__4:MoveNext <0x00210>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00112>
            at Xunit.Sdk.XunitTestRunner:InvokeTestAsync <0x000ea>
            at <>c__DisplayClass43_0:<RunAsync>b__0 <0x00043>
            at <RunAsync>d__10`1:MoveNext <0x000ab>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0010a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.ExceptionAggregator:RunAsync <0x0015e>
            at <RunAsync>d__43:MoveNext <0x005b2>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0011a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestRunner`1:RunAsync <0x0010e>
            at Xunit.Sdk.XunitTestCaseRunner:RunTestAsync <0x000f2>
            at <RunAsync>d__19:MoveNext <0x003ca>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00112>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestCaseRunner`1:RunAsync <0x0010e>
            at Xunit.Sdk.XunitTestCase:RunAsync <0x000f2>
            at Xunit.Sdk.XunitTestMethodRunner:RunTestCaseAsync <0x000bd>
            at <RunTestCasesAsync>d__32:MoveNext <0x001ea>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0011a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestMethodRunner`1:RunTestCasesAsync <0x0010e>
            at <RunAsync>d__31:MoveNext <0x001f8>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0010a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestMethodRunner`1:RunAsync <0x00106>
            at Xunit.Sdk.XunitTestClassRunner:RunTestMethodAsync <0x0012a>
            at <RunTestMethodsAsync>d__38:MoveNext <0x00b00>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0012a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestClassRunner`1:RunTestMethodsAsync <0x0011e>
            at <RunAsync>d__37:MoveNext <0x00405>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00112>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestClassRunner`1:RunAsync <0x0010e>
            at Xunit.Sdk.XunitTestCollectionRunner:RunTestClassAsync <0x00132>
            at <RunTestClassesAsync>d__28:MoveNext <0x004e4>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0011a>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestCollectionRunner`1:RunTestClassesAsync <0x0010e>
            at <RunAsync>d__27:MoveNext <0x00402>
            at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00112>
            at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
            at Xunit.Sdk.TestCollectionRunner`1:RunAsync <0x0010e>
            at Xunit.Sdk.XunitTestAssemblyRunner:RunTestCollectionAsync <0x0010a>
            at <>c__DisplayClass14_2:<RunTestCollectionsAsync>b__2 <0x00067>
            at System.Threading.Tasks.Task`1:InnerInvoke <0x00097>
            at <>c:<.cctor>b__274_0 <0x00036>
            at System.Threading.ExecutionContext:RunInternal <0x00118>
            at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00312>
            at System.Threading.Tasks.Task:ExecuteEntry <0x000f2>
            at <>c:<.cctor>b__8_0 <0x0006a>
            at Xunit.Sdk.MaxConcurrencySyncContext:RunOnSyncContext <0x0006e>
            at <>c__DisplayClass11_0:<WorkerThreadProc>b__0 <0x0005a>
            at System.Threading.ExecutionContext:RunInternal <0x00118>
            at System.Threading.ExecutionContext:Run <0x00072>
            at System.Object:lambda_method2 <0x0008a>
            at Xunit.Sdk.ExecutionContextHelper:Run <0x00081>
            at Xunit.Sdk.MaxConcurrencySyncContext:WorkerThreadProc <0x00262>
            at <>c:<QueueUserWorkItem>b__5_0 <0x00076>
            at System.Threading.Tasks.Task:InnerInvoke <0x000b5>
            at <>c:<.cctor>b__274_0 <0x00036>
            at System.Threading.ExecutionContext:RunInternal <0x00118>
            at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00312>
            at System.Threading.Tasks.Task:ExecuteEntryUnsafe <0x000ba>
            at <>c:<.cctor>b__10_0 <0x0006a>
            at System.Threading.Thread:StartCallback <0x0012c>
            at System.Object:runtime_invoke_void__this__ <0x000b0>
          =================================================================
          Expected: 100
          Actual: 134
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.ICustomMarshaler/Interop.ICustomMarshaler.XUnitWrapper.cs(334,0): at Interop_ICustomMarshaler._Primitives_ICustomMaraler_ICustomMaraler_._Primitives_ICustomMarshaler_ICustomMarshaler_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by SamMonoRT** [comment]
Same as https://github.com/dotnet/runtime/issues/34372 .This can be closed as a duplicate.

**Comment by SamMonoRT** [comment]
@naricc - note while updating the issues.target file, this is a dupe of 34372. Please close this issue once you update that file with the right issue#. Thanks

**Comment by alexischr** [comment]
With this PR, the failure for this test is now a SEGV in `System.SpanHelpers:IndexOf`:

```
/Users/alexischr/runtime/.dotnet/dotnet msbuild /t:RunCoreClrTest /p:CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/Interop/ICustomMarshaler/Primitives/ICustomMarshaler/ICustomMarshaler.sh" /p:CoreClrTestConfig=Debug /p:LibrariesTestConfig=Release /p:Configuration=Release ../mono.proj
Microsoft (R) Build Engine version 16.7.0-preview-20225-01+a123b6db0 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Copying Mono Runtime artifacts from '/Users/alexischr/runtime/artifacts/bin/mono/OSX.x64.Release/' to '/Users/alexischr/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root'.'
  BEGIN EXECUTION
  /Users/alexischr/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun ICustomMarshaler.dll ''
  Discovering...
  Running 25 of 25 tests...

  =================================================================
  	Native Crash Reporting
  =================================================================
  Got a segv while executing native code. This usually indicates
  a fatal error in the mono runtime or one of the native libraries
  used by your application.
  =================================================================

  =================================================================
  	Native stacktrace:
  =================================================================
  	0x109738c46 - /Users/alexischr/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_dump_native_crash_info
  	0x1096dac95 - /Users/alexischr/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_handle_native_crash
  	0x1098f37f7 - /Users/alexischr/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : altstack_handle_and_restore.cold.1
  	0x1097336be - /Users/alexischr/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : altstack_handle_and_restore
  	0x10b969bdd - Unknown
  	0x10b969a4b - Unknown

  =================================================================
  	Telemetry Dumper:
  =================================================================
  Pkilling 0x123145397870592x from 0x123145412636672x
  Pkilling 0x123145416855552x from 0x123145412636672x
  Pkilling 0x123145414746112x from 0x123145412636672x
  Pkilling 0x123145410527232x from 0x123145412636672x
  Pkilling 0x123145429512192x from 0x123145412636672x
  Pkilling 0x123145408417792x from 0x123145412636672x
  Pkilling 0x4514577856x from 0x123145412636672x
  Pkilling 0x123145427402752x from 0x123145412636672x
  Pkilling 0x123145406308352x from 0x123145412636672x
  Pkilling 0x123145425293312x from 0x123145412636672x
  Pkilling 0x123145404198912x from 0x123145412636672x
  Pkilling 0x123145423183872x from 0x123145412636672x
  Pkilling 0x123145402089472x from 0x123145412636672x
  Pkilling 0x123145421074432x from 0x123145412636672x
  Pkilling 0x123145399980032x from 0x123145412636672x
  Pkilling 0x123145418964992x from 0x123145412636672x
  Could not exec mono-hang-watchdog, expected on path '/Users/alexischr/runtime/artifacts/obj/mono/OSX.x64.Release/out/etc/../bin/mono-hang-watchdog' (errno 2)
  Entering thread summarizer pause from 0x123145412636672x
  Finished thread summarizer pause from 0x123145412636672x.
  Failed to create breadcrumb file (null)/crash_hash_0xc74268dd7

  Waiting for dumping threads to resume

  =================================================================
  	External Debugger Dump:
  =================================================================

  =================================================================
  	Basic Fault Address Reporting
  =================================================================
  Memory around native instruction pointer (0x10b969bdd):0x10b969bcd  00 00 00 41 ff d3 49 83 ef 08 49 8b c5 48 03 c3  ...A..I...I..H..
  0x10b969bdd  0f b6 00 44 3b e0 0f 84 39 03 00 00 48 8d 4b 01  ...D;...9...H.K.
  0x10b969bed  49 8b c5 48 03 c1 0f b6 00 44 3b e0 0f 84 2b 03  I..H.....D;...+.
  0x10b969bfd  00 00 48 8d 4b 02 49 8b c5 48 03 c1 0f b6 00 44  ..H.K.I..H.....D

  =================================================================
  	Managed Stacktrace:
  =================================================================
  	  at System.SpanHelpers:IndexOf <0x0011d>
  	  at System.Runtime.InteropServices.Marshal:ZeroFreeCoTaskMemUTF8 <0x0006a>
  	  at System.Runtime.InteropServices.Marshal:ZeroFreeCoTaskMemAnsi <0x00042>
  	  at ClassForwardingCustomMarshaler:CleanUpNativeData <0x00052>
  	  at System.Runtime.InteropServices.Tests.ICustomMarshalerTests:MarshalerOnClassTypeMethod <0x00220>
  	  at System.Runtime.InteropServices.Tests.ICustomMarshalerTests:Parameter_CustomMarshalerProvidedOnClassType_ForwardsCorrectly <0x000ea>
```

**Comment by alexischr** [comment]
@CoffeeFlux You think this is this related to this? https://github.com/dotnet/runtime/pull/35804

**Comment by CoffeeFlux** [comment]
That looks like it might be the same UTF8 crash I was seeing in the StringMarshalling/UTF8 test, yeah. The crash I got was failing in a malloc call, but in both cases it broke the external debugger dumps (since presumably it's caused by some kind of memory corruption).
