### ISSUE TITLE
[Mono] Test failed on windows: System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34396]
`System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT` is disabled in Mono's CoreFX.issues_windows.rsp file. After enabling it still fails locally with the following output:
```
System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT(assemblyName: "Windows, Version=255.255.255.255, Culture=neutral,"..., type: "Windows.Foundation.Collections.StringMap", ignoreCase: False, bindingAttr: Instance | Public | NonPublic, binder: DefaultBinder { }, args: [], culture: , activationAttributes: null, returnedFullNameType: "Windows.Foundation.Collections.StringMap") [FAIL]
System.IO.FileLoadException : The assembly name is invalid.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\AssemblyName.Mono.cs(28,0): at System.Reflection.AssemblyName..ctor(String assemblyName)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(118,0): at System.Activator.CreateInstanceInternal(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(60,0): at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    _\src\libraries\System.Runtime\tests\System\ActivatorTests.cs(784,0): at System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignatureWinRT(String assemblyName, String type, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, String returnedFullNameType)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
The test will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by danmosemsft** [comment]
Maybe change `public static bool IsWinRTSupported => IsWindows && IsNotWindows7;` to `public static bool IsWinRTSupported => IsWindows && IsNotWindows7 && IsNotMono;` and then disable test with that.

**Comment by jkoritzinsky** [comment]
This test will be deleted in #36715 as part of removal of built-in WinRT support in .NET 5.
