### ISSUE TITLE
[Mono] Tests failed on windows: System.Diagnostics.Tests.CounterSampleTests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34409]
`System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSampleCounterSample` and `System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSampleCounterSample` fail in windows CI with following output:
```
System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSampleCounterSample [FAIL]
    System.DllNotFoundException : perfcounter.dll assembly:<unknown assembly> type:<unknown type> member:(null)
    Stack Trace:
    /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/CounterSampleCalculator.cs(97,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
    /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/CounterSample.cs(156,0): at System.Diagnostics.CounterSample.Calculate(CounterSample counterSample, CounterSample nextCounterSample)
    /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/CounterSampleTests.cs(57,0): at System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSampleCounterSample()
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSample [FAIL]
    System.DllNotFoundException : perfcounter.dll assembly:<unknown assembly> type:<unknown type> member:(null)
    Stack Trace:
    /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/CounterSampleCalculator.cs(97,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
    /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/CounterSampleCalculator.cs(56,0): at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample newSample)
    /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/CounterSample.cs(148,0): at System.Diagnostics.CounterSample.Calculate(CounterSample counterSample)
    /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/CounterSampleTests.cs(48,0): at System.Diagnostics.Tests.CounterSampleTests.CounterSample_Calculate_CalculateCounterSample()
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
They will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by danmoseley** [comment]
we no longer use perfcounter.dll. #45142
