### ISSUE TITLE
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds - www.ssllabs.com

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#34434]
**Job:**
[runtime-libraries outerloop:20200401.2](https://dev.azure.com/dnceng/public/_build/results?buildId=583325&view=results)
**Error message:**
```
System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
---- System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure.
```
**Stack trace:**
```
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 179
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1110
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1123
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 456
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 720
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 574
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 35
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(SslProtocols sslProtocols, String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 177
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 410
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 311
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 179
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=583325&view=ms.vss-test-web.build-test-results-tab&runId=18380102&resultId=102798&paneView=debug

**Comment by Rodrigo-Andrade** [comment]
I am testing the net5.0 preview 2 , and the awssdk fails to make requests with httpclient with the same error of the issue.
No problems on windows, but fails with mcr.microsoft.com/dotnet/core/aspnet:5.0.0-preview.2 docker image on linux.

**Comment by Rodrigo-Andrade** [comment]
looks like no https calls work on httpclient on linux on netcore5 preview.2

**Comment by stephentoub** [comment]
> looks like no https calls work on httpclient on linux on netcore5 preview.2

Can you share a repro?  It should work fine.  The error in this issue suggests there was a temporary problem with the certificate being used by the server with which this test was communicating.

**Comment by Rodrigo-Andrade** [comment]
it was talking to the aws s3 endpoint, ill check it soon.

**Comment by Rodrigo-Andrade** [comment]
```csharp
private static async Task Main()
{
    using var http = new HttpClient();
    using var response = await http.GetAsync("https://google.com");
    Console.WriteLine(response);
    Console.WriteLine();
    Console.WriteLine(await response.Content.ReadAsStringAsync());
}
```

Explodes with 

`System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)`

**Comment by Rodrigo-Andrade** [comment]
this is on AWS running docker on 64bit Amazon Linux 2018.03 v2.14.2, on windows (also on aws) works fine.

**Comment by wfurt** [comment]
Your problem is probably different than test failure @Rodrigo-Andrade. It would be better to open separate issue for AWS. I tested aspnet:5.0.0-preview.2  on my machine and it seems to work fine. 

Can you tun following code:
```c#
using System;
using System.Net.Http;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;


namespace certchain
{
    class Program
    {
        static async Task Main(string[] args)
        {
            X509Store store1 = new X509Store (StoreName.Root, StoreLocation.LocalMachine);
            store1.Open(OpenFlags.ReadOnly);
            foreach (X509Certificate cert in store1.Certificates)
            {
                Console.WriteLine(cert.Subject);
            }

            HttpClientHandler handler = new HttpClientHandler();

            using (HttpClient httpClient = new HttpClient(handler))
            {
                handler.ServerCertificateCustomValidationCallback = (request, cert, chain, errors) =>
                {
                    Console.WriteLine($"SslPolicyErrors: {errors}");

                    if (chain == null)
                    {
                        Console.WriteLine("No chain...");
                    }
                    else
                    {
                        foreach (X509ChainElement element in chain.ChainElements)
                        {
                            Console.WriteLine();
                            Console.WriteLine(element.Certificate.Subject);
                            Console.WriteLine(element.ChainElementStatus.Length);
                            foreach (X509ChainStatus status in element.ChainElementStatus)
                            {
                                Console.WriteLine($"Status:  {status.Status}: {status.StatusInformation}");
                            }
                        }
                    }

                    return true;
                };
                Console.WriteLine("----------------------");

                using var response = await httpClient.GetAsync("https://google.com/");
                Console.WriteLine(response);

            }
        }
    }
}
```

**Comment by karelz** [comment]
Hiding the comments above as "unrelated", let's move the AWS problem into separate issue if needed. Thanks!

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200416.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=603555&view=ms.vss-test-web.build-test-results-tab&runId=19005818&resultId=102338&paneView=debug)

failed test: 
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success


Error message
~~~
System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
---- System.IO.IOException : Received an unexpected EOF or 0 bytes from the transport stream.


Stack trace
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 179
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1120
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1133
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 456
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 720
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 565
   at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_HaveCredsAndUseAuthenticatedCustomProxyAndPostToSecureServer_Success() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs:line 121
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 362
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 282
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 179
~~~

**Comment by Rodrigo-Andrade** [comment]
i know its not related, but since i posted here, just letting you know that preview.3 fixed whatever it was.

**Comment by ManickaP** [comment]
The failure are due to dependency on an external server (ssllabs.com), they will pop out from time to time, that's also the reason why the test is outerloop and not innerloop.
We could/should improve our testing environment to remove external dependencies, but that's another can of worms.
