### ISSUE TITLE
[mono] Tests failed on windows: System.DirectoryServices

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34442]
The following tests are disabled in Mono's CoreFX.issues_windows.rsp file, and they still fail locally after enabling:
- System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.Ctor_ContextType
- System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.ValidateCredentials_Invoke_ReturnsExpected
- System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest.Ctor_MachineContext_NoException
- System.DirectoryServices.ActiveDirectory.Tests.ForestTests.GetForest_NonNullNameAndNotRootedDomain_ThrowsActiveDirectoryObjectNotFoundException
- System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.GetDomainController_InvalidIPV6
- System.DirectoryServices.Tests.DirectoryEntryTests.DeleteTree_NoObject_ThrowsCOMException

The output:
```
System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.Ctor_ContextType [FAIL]
System.InvalidOperationException : Failed to set the specified COM apartment state.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs(234,0): at System.Threading.Thread.SetApartmentState(ApartmentState state)
    _\src\libraries\System.DirectoryServices\src\System\DirectoryServices\DirectoryEntry.cs(539,0): at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
    _\src\libraries\System.DirectoryServices\src\System\DirectoryServices\DirectoryEntry.cs(511,0): at System.DirectoryServices.DirectoryEntry.Bind()
    _\src\libraries\System.DirectoryServices\src\System\DirectoryServices\DirectoryEntry.cs(953,0): at System.DirectoryServices.DirectoryEntry.RefreshCache()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(659,0): at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(569,0): at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(487,0): at System.DirectoryServices.AccountManagement.PrincipalContext.get_ConnectedServer()
    _\src\libraries\System.DirectoryServices.AccountManagement\tests\PrincipalContextTests.cs(22,0): at System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.Ctor_ContextType()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.InvalidOperationException : Failed to set the specified COM apartment state.
System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.ValidateCredentials_Invoke_ReturnsExpected(userName: null, password: null, expected: True) [FAIL]
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs(234,0): at System.Threading.Thread.SetApartmentState(ApartmentState state)
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(102,0): at System.DirectoryServices.AccountManagement.CredentialValidator.BindSam(String target, String userName, String password)
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(306,0): at System.DirectoryServices.AccountManagement.CredentialValidator.Validate(String userName, String password)
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(519,0): at System.DirectoryServices.AccountManagement.PrincipalContext.ValidateCredentials(String userName, String password)
    _\src\libraries\System.DirectoryServices.AccountManagement\tests\PrincipalContextTests.cs(297,0): at System.DirectoryServices.AccountManagement.Tests.PrincipalContextTests.ValidateCredentials_Invoke_ReturnsExpected(String userName, String password, Boolean expected)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest.Ctor_MachineContext_NoException [FAIL]
System.InvalidOperationException : Failed to set the specified COM apartment state.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs(234,0): at System.Threading.Thread.SetApartmentState(ApartmentState state)
    _\src\libraries\System.DirectoryServices\src\System\DirectoryServices\DirectoryEntry.cs(539,0): at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
    _\src\libraries\System.DirectoryServices\src\System\DirectoryServices\DirectoryEntry.cs(511,0): at System.DirectoryServices.DirectoryEntry.Bind()
    _\src\libraries\System.DirectoryServices\src\System\DirectoryServices\DirectoryEntry.cs(953,0): at System.DirectoryServices.DirectoryEntry.RefreshCache()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(659,0): at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(569,0): at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Context.cs(1243,0): at System.DirectoryServices.AccountManagement.PrincipalContext.ContextForType(Type t)
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Principal.cs(812,0): at System.DirectoryServices.AccountManagement.Principal.GetStoreCtxToUse()
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Principal.cs(129,0): at System.DirectoryServices.AccountManagement.Principal.set_SamAccountName(String value)
    _\src\libraries\System.DirectoryServices.AccountManagement\src\System\DirectoryServices\AccountManagement\Computer.cs(35,0): at System.DirectoryServices.AccountManagement.ComputerPrincipal..ctor(PrincipalContext context, String samAccountName, String password, Boolean enabled)
    _\src\libraries\System.DirectoryServices.AccountManagement\tests\ComputerPrincipalTest.cs(52,0): at System.DirectoryServices.AccountManagement.Tests.ComputerPrincipalTest.Ctor_MachineContext_NoException()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
These tests will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/issues/34360
