### ISSUE TITLE
[mono] Test failed on windows: WindowAndCursorProps.Title_Set_Windows

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34454]
The `WindowAndCursorProps` tests are disabled in Mono's CoreFX.issues_windows.rsp file. After enabling only `WindowAndCursorProps.Title_Set_Windows` fails locally with the following output:
```
  Unhandled Exception:
  System.IO.DirectoryNotFoundException: Could not find a part of the path.
     at System.ConsolePal.get_Title() in _\src\libraries\System.Console\src\System\ConsolePal.Windows.cs:line 621
     at System.Console.get_Title() in _\src\libraries\System.Console\src\System\Console.cs:line 287
     at WindowAndCursorProps.<>c.<Title_Set_Windows>b__24_0(String lengthOfTitleString) in _\src\libraries\System.Console\tests\WindowAndCursorProps.cs:line 253
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 360
  --- End of stack trace from previous location ---
     at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 95
  [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Could not find a part of the path.
     at System.ConsolePal.get_Title() in _\src\libraries\System.Console\src\System\ConsolePal.Windows.cs:line 621
     at System.Console.get_Title() in _\src\libraries\System.Console\src\System\Console.cs:line 287
     at WindowAndCursorProps.<>c.<Title_Set_Windows>b__24_0(String lengthOfTitleString) in _\src\libraries\System.Console\tests\WindowAndCursorProps.cs:line 253
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs:line 360
  --- End of stack trace from previous location ---
     at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 95
      WindowAndCursorProps.Title_Set_Windows(lengthOfTitle: 0) [FAIL]
        Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
        Stack Trace:
          Child exception:
            System.IO.DirectoryNotFoundException: Could not find a part of the path.
          _\src\libraries\System.Console\src\System\ConsolePal.Windows.cs(621,0): at System.ConsolePal.get_Title()
          _\src\libraries\System.Console\src\System\Console.cs(287,0): at System.Console.get_Title()
          _\src\libraries\System.Console\tests\WindowAndCursorProps.cs(253,0): at WindowAndCursorProps.<>c.<Title_Set_Windows>b__24_0(String lengthOfTitleString)
          _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          Child process:
            System.Console.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 WindowAndCursorProps+<>c Void <Title_Set_Windows>b__24_0(System.String)
          Child arguments:
            0
```
The test will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592

**Comment by danmosemsft** [comment]
GetConsoleTitleW is failing with ERROR_PATH_NOT_FOUND. Would need a debugger to figure out why. Either a wierd Windows bug or a wierd interop bug in Mono runtime? We do properly `SetLastError = true` on this call.
