### ISSUE TITLE
[mono] Test failed on windows: System.IO.Ports.Tests.GetPortNames.OpenEveryPortName

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34490]
It's disabled in Mono's CoreFX.issues_windows.rsp file and fails in CI after enabling.

```   
 System.IO.Ports.Tests.GetPortNames.OpenEveryPortName [FAIL]
      System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
        /_/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.Windows.cs(696,0): at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
        /_/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialPort.cs(599,0): at System.IO.Ports.SerialPort.Open()
        /_/src/libraries/System.IO.Ports/tests/SerialPort/GetPortNames.cs(32,0): at System.IO.Ports.Tests.GetPortNames.OpenEveryPortName()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
The test will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592

**Comment by marek-safar** [comment]
Blocked by #34582

**Comment by danmosemsft** [comment]
Tracking all by #34582
