### ISSUE TITLE
[mono] Test failed on windows: System.Reflection.Tests.AssemblyNameTests.GetAssemblyName_LockedFile

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34492]
`System.Reflection.Tests.AssemblyNameTests.GetAssemblyName_LockedFile` is disabled in Mono's CoreFX.issues_windows.rsp file and after enabling it still fails locally with the following output:

```
System.Reflection.Tests.AssemblyNameTests.GetAssemblyName_LockedFile [FAIL]
Assert.Throws() Failure
Expected: typeof(System.IO.FileLoadException)
Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly '_\AppData\Local\Temp\tmpA90A.tmp' or one of its dependencies.
---- System.IO.FileNotFoundException : Could not load file or assembly '_\AppData\Local\Temp\tmpA90A.tmp' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\AssemblyName.Mono.cs(129,0): at System.Reflection.AssemblyName.GetFileInformationCore(String assemblyFile)
    _\src\libraries\System.Private.CoreLib\src\System\Reflection\AssemblyName.cs(148,0): at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
    _\src\libraries\System.Reflection\tests\AssemblyNameTests.cs(255,0): at System.Reflection.Tests.AssemblyNameTests.<>c__DisplayClass23_0.<GetAssemblyName_LockedFile>b__0()
    ----- Inner Stack Trace -----
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\AssemblyName.Mono.cs(129,0): at System.Reflection.AssemblyName.GetFileInformationCore(String assemblyFile)
    _\src\libraries\System.Private.CoreLib\src\System\Reflection\AssemblyName.cs(148,0): at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
    _\src\libraries\System.Reflection\tests\AssemblyNameTests.cs(255,0): at System.Reflection.Tests.AssemblyNameTests.<>c__DisplayClass23_0.<GetAssemblyName_LockedFile>b__0()
```
This test will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by ericstj** [comment]
This looks like an exception difference in mono runtime when attempting to read AssemblyName from a locked file.

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/blob/5c2ee148ab63dc8b6a751cd6535a4e3d58f441ef/src/mono/mono/metadata/icall.c#L6073
