### ISSUE TITLE
[mono] Tests failed on windows: MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34497]
`MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest` tests are disabled in Mono's CoreFX.issues_windows.rsp file and after enabling some of them fail locally:
- MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.Constructor_MissingFiles_Handler
- MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.Constructor_Duplicates
- MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.UniqueId

The output:
```
MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.Constructor_Duplicates [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs(74,0): at System.IO.FileSystemWatcher.StartRaisingEvents()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(639,0): at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(154,0): at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\FileChangeNotificationSystem.cs(118,0): at System.Runtime.Caching.FileChangeNotificationSystem.System.Runtime.Caching.Hosting.IFileChangeNotificationSystem.StartMonitoring(String filePath, OnChangedCallback onChangedCallback, Object& state, DateTimeOffset& lastWriteTime, Int64& fileSize)
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\HostFileChangeMonitor.cs(64,0): at System.Runtime.Caching.HostFileChangeMonitor.InitDisposableMembers()
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\HostFileChangeMonitor.cs(166,0): at System.Runtime.Caching.HostFileChangeMonitor..ctor(IList`1 filePaths)
    _\src\libraries\System.Runtime.Caching\tests\System.Runtime.Caching\HostFileChangeMonitorTest.cs(146,0): at MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.Constructor_Duplicates()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.UniqueId [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs(74,0): at System.IO.FileSystemWatcher.StartRaisingEvents()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(639,0): at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(154,0): at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\FileChangeNotificationSystem.cs(118,0): at System.Runtime.Caching.FileChangeNotificationSystem.System.Runtime.Caching.Hosting.IFileChangeNotificationSystem.StartMonitoring(String filePath, OnChangedCallback onChangedCallback, Object& state, DateTimeOffset& lastWriteTime, Int64& fileSize)
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\HostFileChangeMonitor.cs(64,0): at System.Runtime.Caching.HostFileChangeMonitor.InitDisposableMembers()
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\HostFileChangeMonitor.cs(166,0): at System.Runtime.Caching.HostFileChangeMonitor..ctor(IList`1 filePaths)
    _\src\libraries\System.Runtime.Caching\tests\System.Runtime.Caching\HostFileChangeMonitorTest.cs(211,0): at MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.UniqueId()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.Constructor_MissingFiles_Handler [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs(74,0): at System.IO.FileSystemWatcher.StartRaisingEvents()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(639,0): at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(154,0): at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\FileChangeNotificationSystem.cs(118,0): at System.Runtime.Caching.FileChangeNotificationSystem.System.Runtime.Caching.Hosting.IFileChangeNotificationSystem.StartMonitoring(String filePath, OnChangedCallback onChangedCallback, Object& state, DateTimeOffset& lastWriteTime, Int64& fileSize)
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\HostFileChangeMonitor.cs(41,0): at System.Runtime.Caching.HostFileChangeMonitor.InitDisposableMembers()
    _\src\libraries\System.Runtime.Caching\src\System\Runtime\Caching\HostFileChangeMonitor.cs(166,0): at System.Runtime.Caching.HostFileChangeMonitor..ctor(IList`1 filePaths)
    _\src\libraries\System.Runtime.Caching\tests\System.Runtime.Caching\HostFileChangeMonitorTest.cs(116,0): at MonoTests.System.Runtime.Caching.HostFileChangeMonitorTest.Constructor_MissingFiles_Handler()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

This test will be marked with `ActiveIssue` in #32592.

**Comment by ericstj** [comment]
ThreadPoolBoundHandle, see https://github.com/dotnet/runtime/issues/34582

**Comment by danmosemsft** [comment]
Let's just track it all with #34582 and if/when fixing that, they can enable tests from linked issues like this.
