### ISSUE TITLE
[mono] Tests failed on windows: System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStream/FileStreamUnix

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34493]
`System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStream` and `System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStreamUnix` are disabled in Mono's CoreFX.issues_windows.rsp file and after enabling they still fail locally with the following output:
```
System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStream [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.Windows.cs(92,0): at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
    _\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs(253,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    _\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs(183,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
    _\src\libraries\System.Reflection.Metadata\tests\Utilities\AbstractMemoryBlockTests.cs(152,0): at System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStream()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStreamUnix [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.Windows.cs(92,0): at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
    _\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs(253,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    _\src\libraries\System.Private.CoreLib\src\System\IO\FileStream.cs(183,0): at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
    _\src\libraries\System.Reflection.Metadata\tests\Utilities\AbstractMemoryBlockTests.cs(152,0): at System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStream()
    _\src\libraries\System.Reflection.Metadata\tests\Utilities\AbstractMemoryBlockTests.cs(128,0): at System.Reflection.Internal.Tests.AbstractMemoryBlockTests.FileStreamUnix()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

These tests will be marked with `ActiveIssue` in #32592.

**Comment by carlossanlop** [comment]
@MaximLipnin can you please point me to the right instructions to run this unit test in mono, so I can try to repro the issue?

**Comment by MaximLipnin** [comment]
@carlossanlop There are some [instructions](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/mono/testing.md), but actually I do the following steps:
1. in the root folder run `build.cmd -subsetcategory mono-libraries -c Release -runtimeconfiguration Release /p:RuntimeFlavor=mono` 
2. after build completes, run `cd src\libraries\System.Reflection.Metadata\tests`
3. run `dotnet build /t:Test /p:RuntimeFlavor=mono /p:Configuration=Release`

**Comment by ericstj** [comment]
ThreadPoolBoundHandle, see #34582

**Comment by danmosemsft** [comment]
Let's just track it all with #34582 and if/when fixing that, they can enable tests from linked issues like this.
