### ISSUE TITLE
[mono] Tests failed on windows: ThreadPoolBoundHandleTests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34502]
`ThreadPoolBoundHandleTests` tests are disabled in Mono's CoreFX.issues_windows.rsp file and after enabling they still fail locally with the following output (only one for short):
```
ThreadPoolBoundHandleTests.AllocateNativeOverlapped_ReturnedNativeOverlapped_AllFieldsZero [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.Threading.Overlapped\tests\ThreadPoolBoundHandle_Helpers.cs(32,0): at ThreadPoolBoundHandleTests.CreateThreadPoolBoundHandle(SafeHandle handle, String memberName, Int32 lineNumber)
    _\src\libraries\System.Threading.Overlapped\tests\ThreadPoolBoundHandle_Helpers.cs(26,0): at ThreadPoolBoundHandleTests.CreateThreadPoolBoundHandle(String memberName, Int32 lineNumber)
    _\src\libraries\System.Threading.Overlapped\tests\ThreadPoolBoundHandle_AllocateNativeOverlappedTests.cs(143,0): at ThreadPoolBoundHandleTests.AllocateNativeOverlapped_ReturnedNativeOverlapped_AllFieldsZero()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(360,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

The related partial test class will be marked with `ActiveIssue` in #32592.

**Comment by ericstj** [comment]
See https://github.com/dotnet/runtime/issues/34582

**Comment by danmosemsft** [comment]
Let's just track it all with #34582 and if/when fixing that, they can enable tests from linked issues like this.
