### ISSUE TITLE
Test failed System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_ServerNoEncryption_NoConnect

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#34545]
leg: Libraries Test Run release coreclr Windows_NT x86 Release
src: https://helix.dot.net/api/2019-06-17/jobs/9377837f-bbd7-4b24-9d71-0b02f14314b1/workitems/System.Net.Security.Tests/console

```sh    System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_ServerNoEncryption_NoConnect [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Security.Authentication.AuthenticationException)
      Actual:   typeof(System.IO.IOException):  Received an unexpected EOF or 0 bytes from the transport stream.
      ---- System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(789,0): at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(338,0): at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(282,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs(160,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncSslHelper(EncryptionPolicy encryptionPolicy, SslProtocols clientSslProtocols, SslProtocols serverSslProtocols)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(789,0): at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(338,0): at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(282,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(38,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs(160,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncSslHelper(EncryptionPolicy encryptionPolicy, SslProtocols clientSslProtocols, SslProtocols serverSslProtocols)
  Finished:    System.Net.Security.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Security.Tests  Total: 4388, Errors: 0, Failed: 1, Skipped: 20, Time: 23,162s
----- end 03/04/2020  3:30:23,27 ----- exit code 1 ----------------------------------------------------------
```

**Comment by alnikola** [comment]
Triage:
We suspect it's a test code bug, but need to confirm this.

**Comment by alnikola** [comment]
Failed 2 times with a different error on June 13th.

```
Assert.Throws() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.ObjectDisposedException): Safe handle has been closed. Object name: 'SafeHandle'.
---- System.ObjectDisposedException : Safe handle has been closed. Object name: 'SafeHandle'.
```

**Comment by v-haren** [comment]
failed again in job: [ runtime-coreclr libraries-jitstress 20201209.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=915424&view=ms.vss-test-web.build-test-results-tab&runId=29125342&resultId=136236&paneView=debug)

failed test: System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Tls)

net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.10.Arm64v8.Open


Error message
~~~
System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.


Stack trace
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|181_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 936
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 454
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 356
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 396
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(SslProtocols protocol) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 43
--- End of stack trace from previous location ---
~~~

**Comment by wfurt** [comment]
did not fail on last 90 days. closing for now.
