### ISSUE TITLE
JsonSerializer intermittently writes invalid JSON for dictionaries in .NET 5 preview 2

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#34564]
I've updated a number of internal applications running .NET Core 3.1.3 to .NET 5 preview 2 (SDK version `5.0.100-preview.2.20176.6`) and have a number of previously passing tests where JSON is returned from an ASP.NET Core API using System.Text.Json that are now failing to have their contents successfully deserialized by either System.Text.Json or Newtonsoft.Json.

Exceptions similar to the following are thrown by code trying to read the JSON returned by the API:

```
System.Text.Json.JsonReaderException : '}' is an invalid start of a value. LineNumber: 503 | BytePositionInLine: 6.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(Stream utf8Json, JsonDocumentOptions options)
```

```
System.Text.Json.JsonException : ':' is invalid after a value. Expected either ',', '}', or ']'. Path: $._pagination.links.first | LineNumber: 499 | BytePositionInLine: 19.
---- System.Text.Json.JsonReaderException : ':' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 499 | BytePositionInLine: 19.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.DictionaryDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
```

I've yet to be able to create a reliable isolated repro (but I will try further to do so), but there appear to be some common themes to the failing tests in these two different applications, though some may be coincidences:
  1. The written JSON is malformed inside an object which is the value of a dictionary.
  1. A single failing test run by itself passes, suggesting that something goes wrong over time rather than always being broken.
  1. Tests that fail appear to be one or more of a set of xunit theories running mostly the same code with slightly different inputs or expected outputs, suggesting some sort of shared state being corrupted.
  1. Which tests fail varies between test runs.
  1. The invalid JSON is approximately 450-520 lines into the returned JSON response.

Below is a simplified invalid JSON string returned by the API showing the malformed part of the response within the wider context of the overall response:

```json
{
  "consumerId": "456",
  "tenant": "uk",
  "orders": [
    {
      "id": "abc"
    },
    {
      "id": "def"
    }
  ],
  "_links": {
    "self": {
      "href": "",
      "templated": false
    }
  },
  "_pagination": {
    "total": null,
    "count": 2,
    "token": "",
    "links": {
      "self": {
        "href": "",
        "templated": false
      },
      "first": {
        "href": "",
        "templated": false
      },
      "prev": {
        "href": "",
        "templated": false,
        "prev": 
      },
      "next": {
        "href": "",
        "templated": false
      }
    }
  },
  "timestamp": "2017-06-05T17:20:00\u002B00:00"
}
```

The invalid part is here, where a dangling `"prev": ` is written before the end of the object before the penultimate object in the dictionary is written:

```json
      "prev": {
        "href": "",
        "templated": false,
        "prev": 
      }
```

The relevant parts of the serialized object model for this part of the JSON are:

```csharp
public class Link
{
    [JsonPropertyName("href")]
    public string Url { get; set; }

    [JsonPropertyName("templated")]
    public bool IsTemplated { get; set; }
}

public class PaginationInfo
{
    public PaginationInfo()
    {
        Links = new Dictionary<string, Link>(StringComparer.Ordinal);
    }

    [JsonPropertyName("total")]
    public long? Total { get; set; }

    [JsonPropertyName("count")]
    public long Count { get; set; }

    [JsonPropertyName("token")]
    public string Token { get; set; }

    [JsonPropertyName("links")]
    public IDictionary<string, Link> Links { get; set; }
}

public class Order
{
    [JsonPropertyName("id")]
    public string Id { get; set; }
}

public class OrderHistory
{
    public OrderHistory()
    {
        Links = new Dictionary<string, Link>(StringComparer.Ordinal);
        Orders = Array.Empty<Order>();
    }

    [JsonPropertyName("consumerId")]
    public string ConsumerId { get; set; }

    [JsonPropertyName("tenant")]
    public string Tenant { get; set; }

    [JsonPropertyName("orders")]
    public ICollection<Order> Orders { get; set; }

    [JsonPropertyName("_links")]
    public IDictionary<string, Link> Links { get; set; }

    [JsonPropertyName("_pagination")]
    public PaginationInfo Pagination { get; set; }

    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; set; }
}
```

Looking at GitHub's suggested similar issues and looking at the source history, it's possible this issue is related to #32523.

**Comment by layomia** [comment]
Might be related to any issues uncovered when fixing https://github.com/dotnet/runtime/issues/32145.

Please let us know when you have a repro.

**Comment by layomia** [comment]
I was able to repro this while working on https://github.com/dotnet/runtime/issues/32145. Fix in https://github.com/dotnet/runtime/pull/35046.

**Comment by martincostello** [comment]
Great, thanks @layomia - sorry I wasn't able to get you a repro.

**Comment by layomia** [comment]
> Great, thanks @layomia - sorry I wasn't able to get you a repro.

No prob at all. Thanks for filing this.
