### ISSUE TITLE
[mono] Test failed on windows: System.Tests.StringTests.NormalizationTest

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34577]
`System.Tests.StringTests.NormalizationTest` is disabled in Mono's CoreFX.issues_windows.rsp file and after enabling it still fails locally with the following output:
```
System.Tests.StringTests.NormalizationTest [FAIL]
System.InvalidOperationException : Unknown error "127".
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Globalization\Normalization.Windows.cs(54,0): at System.Globalization.Normalization.IsNormalized(String strInput, NormalizationForm normalizationForm)
    _\src\libraries\System.Private.CoreLib\src\System\String.cs(723,0): at System.String.IsNormalized(NormalizationForm normalizationForm)
    _\src\libraries\System.Private.CoreLib\src\System\String.cs(709,0): at System.String.IsNormalized()
    _\src\libraries\Common\tests\Tests\System\StringTests.cs(7228,0): at System.Tests.StringTests.NormalizationTest()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

This test will be marked with `ActiveIssue` in #32592.

**Comment by danmosemsft** [comment]
127 - ERROR_PROC_NOT_FOUND
is this failing?
```
[DllImport("Normaliz.dll", CharSet = CharSet.Unicode, SetLastError = true)]
internal static extern bool IsNormalizedString(int normForm, string source, int length);
```
