### ISSUE TITLE
[mono] Tests failed on windows: System.IO.CreateSafeFileHandleTests 

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34578]
`System.IO.CreateSafeFileHandleTests` tests are disabled in Mono's CoreFX.issues_windows.rsp file and after enabling they still fail locally with the following output:
```
System.IO.CreateSafeFileHandleTests.FromStorageFolder_EncryptedThrowsNotSupported [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass14_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFile_BadOptionsThrowsOutOfRange [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass3_0:file' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.NullStorageFolder_ThrowsArgumentNull [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass7_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.NullStorageFolder_ThrowsArgumentNull2 [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass8_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFolder_BadAccessThrowsOutOfRange [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass10_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass1_0:file' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
System.IO.CreateSafeFileHandleTests.FromStorageFile_BadAccessThrowsOutOfRange [FAIL]
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFile_BadSharingThrowsOutOfRange [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass2_0:file' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFolder_BadOptionsThrowsOutOfRange [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass12_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFolder_BadModeThrowsOutOfRange [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass9_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFile_NoInterfaceReturnsNull [FAIL]
System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFile_EncryptedThrowsNotSupported [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass5_0:file' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFolder_InheritableThrowsNotSupported [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass13_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFile_InheritableThrowsNotSupported [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass4_0:file' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.FromStorageFolder_BadSharingThrowsOutOfRange [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass11_0:folder' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.IO.CreateSafeFileHandleTests.NullStorageFile_ThrowsArgumentNull [FAIL]
System.TypeLoadException : Could not load type of field 'System.IO.CreateSafeFileHandleTests+<>c__DisplayClass0_0:file' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

These tests will be marked with `ActiveIssue` in #32592.

Upd. `System.IO.AsWinRTStreamTests` tests also fail with `Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

**Comment by danmosemsft** [comment]
They are already conditioned by `[ConditionalClass(typeof(PlatformDetection), nameof(PlatformDetection.IsWinUISupported))]`. Need to update these so they return false on Mono:
```
   37          public static bool IsWinRTSupported => IsWindows && IsNotWindows7;
   38:         public static bool IsWinUISupported => IsWinRTSupported && IsNotWindows8x && IsNotWindowsNanoServer && IsNotWindowsServerCore && IsNotWindowsIoTCore;
```
