### ISSUE TITLE
TestWithRelativePaths installer test fails on CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#34590]
https://dev.azure.com/dnceng/public/_build/results?buildId=590125&view=ms.vss-test-web.build-test-results-tab&runId=18599454&paneView=debug

Configuration: `Installer-Linux_x64-Debug`

```
System.ComponentModel.Win32Exception : Text file busy

  at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/test/TestUtils/Command.cs:line 200
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute(Boolean fExpectedToFail) in /_/src/installer/test/TestUtils/Command.cs:line 240
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute() in /_/src/installer/test/TestUtils/Command.cs:line 172
   at Microsoft.NET.HostModel.Tests.BundleAndRun.RunTheApp(String path) in /_/src/installer/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleAndRun.cs:line 26
   at Microsoft.NET.HostModel.Tests.BundleAndRun.BundleRun(TestProjectFixture fixture, String publishPath, String singleFileDir) in /_/src/installer/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleAndRun.cs:line 49
   at Microsoft.NET.HostModel.Tests.BundleAndRun.TestWithRelativePaths() in /_/src/installer/test/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleAndRun.cs:line 77
```

**Comment by ViktorHofer** [comment]
This should have been fixed (can't find the commit right now)
