### ISSUE TITLE
[mono] Test failed on windows: System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34592]
`System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected` fails locally with the following output:
```
System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(id: 2147483647, len: 2147483647, type: 32767, value: [0]) [FAIL]
System.MissingMethodException : No parameterless constructor defined for type 'System.Drawing.Imaging.PropertyItemInternal'.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1954,0): at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1925,0): at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1803,0): at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(95,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(319,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
    _\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(563,0): at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
    _\src\libraries\System.Drawing.Common\src\System\Drawing\PropertyItemInternal.cs(74,0): at System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(IntPtr propdata, Int32 count)
    _\src\libraries\System.Drawing.Common\src\System\Drawing\Image.Windows.cs(468,0): at System.Drawing.Image.get_PropertyItems()
    _\src\libraries\System.Drawing.Common\tests\Imaging\PropertyItemTests.cs(51,0): at System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(Int32 id, Int32 len, Int16 type, Byte[] value)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(id: -2147483648, len: -2147483648, type: -32768, value: [1, 1]) [FAIL]
System.MissingMethodException : No parameterless constructor defined for type 'System.Drawing.Imaging.PropertyItemInternal'.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1954,0): at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1925,0): at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1803,0): at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(95,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(319,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
    _\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(563,0): at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
    _\src\libraries\System.Drawing.Common\src\System\Drawing\PropertyItemInternal.cs(74,0): at System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(IntPtr propdata, Int32 count)
    _\src\libraries\System.Drawing.Common\src\System\Drawing\Image.Windows.cs(468,0): at System.Drawing.Image.get_PropertyItems()
    _\src\libraries\System.Drawing.Common\tests\Imaging\PropertyItemTests.cs(51,0): at System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(Int32 id, Int32 len, Int16 type, Byte[] value)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(id: 0, len: 0, type: 0, value: []) [FAIL]
System.MissingMethodException : No parameterless constructor defined for type 'System.Drawing.Imaging.PropertyItemInternal'.
Stack Trace:
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1954,0): at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1925,0): at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
    _\src\mono\netcore\System.Private.CoreLib\src\System\RuntimeType.Mono.cs(1803,0): at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(95,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(319,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
    _\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs(563,0): at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
    _\src\libraries\System.Drawing.Common\src\System\Drawing\PropertyItemInternal.cs(74,0): at System.Drawing.Imaging.PropertyItemInternal.ConvertFromMemory(IntPtr propdata, Int32 count)
    _\src\libraries\System.Drawing.Common\src\System\Drawing\Image.Windows.cs(468,0): at System.Drawing.Image.get_PropertyItems()
    _\src\libraries\System.Drawing.Common\tests\Imaging\PropertyItemTests.cs(51,0): at System.Drawing.Imaging.Tests.PropertyItemTests.Properties_SetValues_ReturnsExpected(Int32 id, Int32 len, Int16 type, Byte[] value)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

This test will be marked with `ActiveIssue` in #32592.

**Comment by ericstj** [comment]
Interesting, looks like a bug in Mono's PtrToStructure
https://github.com/dotnet/runtime/blob/f5ecd6bc936cb9502d5faf8e156d00cf526c9b76/src/libraries/System.Drawing.Common/src/System/Drawing/PropertyItemInternal.cs#L74-L75

This should work since the calling code has access to the constructor
https://github.com/dotnet/runtime/blob/f5ecd6bc936cb9502d5faf8e156d00cf526c9b76/src/libraries/System.Drawing.Common/src/System/Drawing/PropertyItemInternal.cs#L18

However Mono's implementation attempts to call a public constructor:
```
    _\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs(87,0): at System.Activator.CreateInstance(Type type, Boolean nonPublic)
    _\src\libraries\System.Private.CoreLib\src\System\Activator.cs(41,0): at System.Activator.CreateInstance(Type type)
    _\src\mono\netcore\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.Mono.cs(319,0): at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType) 
```

**Comment by hughbe** [comment]
We may be able to fix this by converting `PropertyItemInternal` into a `struct`
