### ISSUE TITLE
[mono] Tests failed on windows: System.Runtime.InteropServices.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34748]
A lot of `System.Runtime.InteropServices.Tests` tests fail on windows.

The example of CI output :
```
System.Runtime.InteropServices.Tests.ReleaseComObjectTests.ReleaseComObject_NonComObject_ThrowsArgumentException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.PlatformNotSupportedException): COM Interop is not supported on this platform.
    ---- System.PlatformNotSupportedException : COM Interop is not supported on this platform.
    Stack Trace:
    /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NoCom.cs(201,0): at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
    /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ReleaseComObjectTests.cs(29,0): at System.Runtime.InteropServices.Tests.ReleaseComObjectTests.<>c.<ReleaseComObject_NonComObject_ThrowsArgumentException>b__2_0()
    ----- Inner Stack Trace -----
    /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NoCom.cs(201,0): at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
    /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ReleaseComObjectTests.cs(29,0): at System.Runtime.InteropServices.Tests.ReleaseComObjectTests.<>c.<ReleaseComObject_NonComObject_ThrowsArgumentException>b__2_0()
System.Runtime.InteropServices.Tests.ReleaseComObjectTests.ReleaseComObject_NullObject_ThrowsNullReferenceException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.NullReferenceException)
    Actual:   typeof(System.PlatformNotSupportedException): COM Interop is not supported on this platform.
    ---- System.PlatformNotSupportedException : COM Interop is not supported on this platform.
    Stack Trace:
    /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NoCom.cs(201,0): at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
    /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ReleaseComObjectTests.cs(22,0): at System.Runtime.InteropServices.Tests.ReleaseComObjectTests.<>c.<ReleaseComObject_NullObject_ThrowsNullReferenceException>b__1_0()
    ----- Inner Stack Trace -----
    /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NoCom.cs(201,0): at System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)
    /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/ReleaseComObjectTests.cs(22,0): at System.Runtime.InteropServices.Tests.ReleaseComObjectTests.<>c.<ReleaseComObject_NullObject_ThrowsNullReferenceException>b__1_0()
cant resolve internal call to "System.Runtime.InteropServices.Tests.Common.ComImportObject::.ctor" (tested without signature also)

Your mono runtime and class libraries are out of sync.
The out of sync library is: C:\h\w\9EB608BF\w\AA6F0948\e\System.Runtime.InteropServices.Tests.dll

When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
* Assertion: should not be reached at F:\workspace\_work\1\s\src\mono\mono\metadata\marshal.c:3513

System.Runtime.InteropServices.Tests.FinalReleaseComObjectTests.FinalReleaseComObject_NullObject_ThrowsArgumentNullException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentNullException)
    Actual:   typeof(System.PlatformNotSupportedException): COM Interop is not supported on this platform.
    ---- System.PlatformNotSupportedException : COM Interop is not supported on this platform.
    Stack Trace:
    /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NoCom.cs(61,0): at System.Runtime.InteropServices.Marshal.FinalReleaseComObject(Object o)
cant resolve internal call to "System.Runtime.InteropServices.Tests.Common.ComImportObject::.ctor" (tested without signature also)
    /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/FinalReleaseComObjectTests.cs(22,0): at System.Runtime.InteropServices.Tests.FinalReleaseComObjectTests.<>c.<FinalReleaseComObject_NullObject_ThrowsArgumentNullException>b__1_0()
    ----- Inner Stack Trace -----

Your mono runtime and class libraries are out of sync.
The out of sync library is: C:\h\w\9EB608BF\w\AA6F0948\e\System.Runtime.InteropServices.Tests.dll

When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
* Assertion: should not be reached at F:\workspace\_work\1\s\src\mono\mono\metadata\marshal.c:3513

    /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.NoCom.cs(61,0): at System.Runtime.InteropServices.Marshal.FinalReleaseComObject(Object o)
    /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/Marshal/FinalReleaseComObjectTests.cs(22,0): at System.Runtime.InteropServices.Tests.FinalReleaseComObjectTests.<>c.<FinalReleaseComObject_NullObject_ThrowsArgumentNullException>b__1_0()
```
The failing tests will be mark with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by danmosemsft** [comment]
@MaximLipnin is COM Interop is not supported on this platform expected - doesn't Mono support COM interop?

**Comment by MaximLipnin** [comment]
@danmosemsft Thanks for taking a look. I'm not sure about Mono's support in this case. What I can do in such cases is to track down possible reason, but because the number of disabled tests/classes/namespaces that I need to check within [my work for removing rsp files](https://github.com/dotnet/runtime/pull/32592) is quite big, it can take long time to investigate. So I just file a tracking issue which someone with broader knowledge can take a look at and decide what to do.

cc/ @steveisok @marek-safar

**Comment by SamMonoRT** [comment]
Moving to 7.0.0
