### ISSUE TITLE
[mono] Tests failed on windows: System.Runtime.InteropServices.WindowsRuntime.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34749]
`System.Runtime.InteropServices.WindowsRuntime.Tests` tests fail on windows mostly with `System.PlatformNotSupportedException : Operation is not supported on this platform.`

The following tests classes/methods will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592:
- System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeMarshalTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.InterfaceImplementedInVersionAttributeTests.Ctor_DefaultInterface

The example of the output with the stack traces:
```
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.Ctor_NonDelegateType_ThrowsInvalidOperationException [FAIL]
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.PlatformNotSupportedException): Operation is not supported on this platform.
---- System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(22,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c.<Ctor_NonDelegateType_ThrowsInvalidOperationException>b__1_0()
    ----- Inner Stack Trace -----
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(22,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c.<Ctor_NonDelegateType_ThrowsInvalidOperationException>b__1_0()
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetDelegate_GetReturnsExpected [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(171,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetDelegate_GetReturnsExpected()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_Null_ReturnsZeroToken [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(68,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_Null_ReturnsZeroToken()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_SingleInvocationList_AddsSingleDelegateToInvocationList [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(29,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_SingleInvocationList_AddsSingleDelegateToInvocationList()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Assert.Throws() Failure
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NonDelegateType_ThrowsInvalidOperationException [FAIL]
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.PlatformNotSupportedException): Operation is not supported on this platform.
---- System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(154,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c__DisplayClass12_0.<GetOrCreateEventRegistrationTokenTable_NonDelegateType_ThrowsInvalidOperationException>b__0()
    ----- Inner Stack Trace -----
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(154,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.<>c__DisplayClass12_0.<GetOrCreateEventRegistrationTokenTable_NonDelegateType_ThrowsInvalidOperationException>b__0()
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_NullDelegate_Nop [FAIL]
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(130,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_NullDelegate_Nop()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Token_RemovesFromTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(80,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Token_RemovesFromTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_MultipleTimes_RemovesSingleDelegateFromTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(115,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_MultipleTimes_RemovesSingleDelegateFromTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Delegate_RemovesFromTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(97,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.RemoveEventHandler_Delegate_RemovesFromTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NullTable_ReturnsNewTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(138,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NullTable_ReturnsNewTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleTimes_AddsEachDelegateToInvocationList [FAIL]
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(54,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleTimes_AddsEachDelegateToInvocationList()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleInvocationList_AddsAllDelegateToInvocationLists [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(43,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.AddEventHandler_MultipleInvocationList_AddsAllDelegateToInvocationLists()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NonNullTable_ReturnsEventTable [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(145,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.GetOrCreateEventRegistrationTokenTable_NonNullTable_ReturnsEventTable()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetNull_GetReturnsNull [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(160,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.InvocationList_SetNull_GetReturnsNull()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.Ctor_Default [FAIL]
System.PlatformNotSupportedException : Operation is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Runtime.InteropServices.WindowsRuntime\tests\System\Runtime\InteropServices\WindowsRuntime\EventRegistrationTokenTableTests.cs(15,0): at System.Runtime.InteropServices.WindowsRuntime.Tests.EventRegistrationTokenTableTests.Ctor_Default()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by danmosemsft** [comment]
@MaximLipnin could you please add sample callstacks in issues like this where there's an exception message? That would show where this exception is coming from.

Perhaps `        public static bool IsWinRTSupported => IsWindows && IsNotWindows7;` should also exclude Mono; but interestingly, this attribute is actually applied on very few tests. So it would be too to know what is throwing here.

**Comment by MaximLipnin** [comment]
@danmosemsft I've updated the PR description with the example of the output.

**Comment by jkoritzinsky** [comment]
These tests will be deleted as part of #36715
