### ISSUE TITLE
[mono] Tests failed on windows: System.Runtime.WindowsRuntime.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34768]
There are test failures in `System.Runtime.WindowsRuntime.Tests` on windows.

```
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [], offset: 0, length: 0, capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 2, length: 0, capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 2, length: 0, capacity: 1) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 0, length: 3, capacity: 3) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 1, length: 2, capacity: 2) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NegativeLength_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NegativeOffset_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NegativeCapacity_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 0, length: 1, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 1, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 1, length: 2, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 2147483647, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 3) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 2147483647) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 2, capacity: 1) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests.AsBuffer_NullBuffer_ThrowsArgumentNullException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentNullException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NegativeCapacity_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NegativeLength_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [], offset: 0, length: 0, capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 0, length: 3, capacity: 3) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [1, 2, 3, 4, 5, ...], offset: 2, length: 1, capacity: 4) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Buffer_ReturnsExpected(source: [1, 2, 3], offset: 1, length: 2, capacity: 2) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 0, length: 1, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [], offset: 1, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 1, length: 2, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 2147483647, length: 0, capacity: 0) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 3) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 0, capacity: 2147483647) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_InvalidOffsetLengthCapacity_ThrowsArgumentException(data: [0, 0], offset: 0, length: 2, capacity: 1) [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Length_SetGreaterThanCapacity_ThrowsArgumentException [FAIL]
    System.TypeLoadException : Could not load type of field 'System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests+<>c__DisplayClass8_0:buffer' (0) due to: Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Capacity_ReturnsExpected(capacity: 0) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_Capacity_ReturnsExpected(capacity: 1) [FAIL]
    System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NegativeOffset_ThrowsArgumentOutOfRangeException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentOutOfRangeException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
    
System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests.Create_NullData_ThrowsArgumentNullException [FAIL]
    Assert.Throws() Failure
    Expected: typeof(System.ArgumentNullException)
    Actual:   typeof(System.IO.FileNotFoundException): Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    ---- System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
    Stack Trace:
    
    ----- Inner Stack Trace -----
```
The following test classes will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592:
- System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferExtensionsTests
- System.Runtime.InteropServices.WindowsRuntime.Tests.WindowsRuntimeBufferTests

**Comment by danmosemsft** [comment]
Should WinRT on Mono be a scenario we support (@jkotas?)

**Comment by jkoritzinsky** [comment]
These tests will be deleted as part of #36715 as we're removing built-in WinRT support in .NET 5.
