### ISSUE TITLE
JWT Bearer Tokens Fail with IDX20803 in 3.1.x on macOS 10.15.4

### ISSUE THREAD

**Issue by mharrisn** [dotnet/runtime#34785]
# Issue Title

I recently upgraded a .Net 2.1 Web API Project to 3.1 and API now throws an error every time I attempt to make a call with an Authorization header when debugging on my mac OS development machine. The code executes fine when debugging or deployed to Windows. 

# General

While inspecting the debug console there is a fairly common pattern.  This issue did not exist using .Net Core 2.x on Mac OS. It appears to not be an issue when run on Windows. When the API request is initiated, these exceptions are thrown:

```
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
```

There is a delay, then another set of exceptions. This appears to happens after approximately a minute - which I believe is the HTTP timeout value:
```
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in Microsoft.IdentityModel.Protocols.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.IdentityModel.Protocols.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
```

Finally, an error is reported:
```
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://{DOMAIN}/openid-configuration'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://{DOMAIN}/openid-configuration'.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Error: Exception occurred while processing message.
```

##Code Sample of JWT Implementation
```csharp
// Add Authentication Services
services
.AddAuthentication(options =>
{
      options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
      options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
      options.Authority = {{MY_AUTHORITY}}
      options.Audience = {{MY_AUDIENCE}};
})
```

**Comment by scalablecory** [comment]
```
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

This indicates your cancellation token is triggering or the request is timing out due to the server not responding. The default for `HttpClient.Timeout` is 100 seconds; you might increase it or even set it to `Timeout.InfiniteTimeSpan` if appropriate.

**Comment by Pilchie** [comment]
Microsoft.Identity is not actually ASP.NET actually.  It's a separate team.

**Comment by am11** [comment]
See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1303, upgrading [Microsoft.IdentityModel.Protocols.OpenIdConnect](https://www.nuget.org/packages/Microsoft.IdentityModel.Protocols.OpenIdConnect/) to latest version (6.x) fixed that issue.

**Comment by mharrisn** [comment]
@am11 Thank you very much for your response. Upgrading packages has resolved the issue for me. I discovered that just installing the dependencies of Microsoft.IdentityModel.Protocols.OpenIdConnect was sufficient to resolve the issue. Here are the additions to my .csproj.  This was definitely a reproducible issue for me for macOS. Are these new packages going to bundled with the 5.x release -or a subsequent maintenance 3.x update?

```xml
<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.5.0" />
<PackageReference Include="Microsoft.IdentityModel.Logging" Version="6.5.0" />
<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.5.0" />
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.5.0" />
```
