### ISSUE TITLE
System.ArgumentNullException in JsonSerializer.SerializeAsync when serializing ImmutableArray<T>

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#34876]
````c#
#nullable enable
using System.Collections.Immutable;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;

namespace ConsoleApp13
{
    class Program
    {
        static async Task Main()
        {
            await Save(Configuration.Default);

        }
        public static async Task Save(Configuration configuration)
        {
            using var stream = File.OpenWrite(Path.GetTempFileName());
            stream.SetLength(0);
            await JsonSerializer.SerializeAsync(stream, configuration).ConfigureAwait(false);
        }
    }

    public class Configuration
    {
        public ImmutableArray<string>? Folders { get; set; }

        public static Configuration Default => new Configuration
        {
            Folders = ImmutableArray<string>.Empty,
        };
    }
}

````

````
Unhandled exception. System.ArgumentNullException: Value cannot be null.
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Text.Json.JsonClassInfo.HasConstructorThatTakesGenericIEnumerable(Type type, JsonSerializerOptions options)   at System.Text.Json.JsonPropertyInfo.DetermineSerializationCapabilities()
   at System.Text.Json.JsonPropertyInfo.GetPolicies()
   at System.Text.Json.JsonPropertyInfoCommon`4.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type elementType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at ConsoleApp13.Program.Save(Configuration configuration) in C:\Users\meziantou\source\repos\ConsoleApp13\ConsoleApp13\Program.cs:line 20
   at ConsoleApp13.Program.Main() in C:\Users\meziantou\source\repos\ConsoleApp13\ConsoleApp13\Program.cs:line 13
   at ConsoleApp13.Program.<Main>()
````

````
C:\Users\meziantou>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
````

**Comment by layomia** [comment]
This is a very specific bug with (de)serializing nullable `ImmutableArray`, both at root level and as a property. Other nullable immutable collections work okay.

I couldn't repro this for master/5.0, likely due to serializer refactoring and various bug fixes. I'll close this issue as this won't meet the bar for a servicing fix in 3.1.

The workaround here is to not make the property nullable, or try a [preview of .NET 5](https://dotnet.microsoft.com/download/dotnet-core/5.0?utm_source=dotnet-website&utm_medium=banner&utm_campaign=preview5-banner) (or just [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/5.0.0-preview.2.20160.6)).
