### ISSUE TITLE
Test failure: Loader/AssemblyDependencyResolver/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34881]
failed in job: [runtime-coreclr outerloop 20200412.3](https://dev.azure.com/dnceng/public/_build/results?buildId=598005&view=ms.vss-test-web.build-test-results-tab&runId=18835524&resultId=107112&paneView=debug)

Error message
~~~
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 't')
at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
at TestLibrary.HostPolicyMock.MockValues_corehost_set_error_writer.get_LastSetErrorWriter() in /__w/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/HostPolicyMock.cs:line 132
at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.<>c__DisplayClass4_0.<TestComponentLoadFailure>b__0(String componentAssemblyPath) in /__w/1/s/src/coreclr/tests/src/Loader/AssemblyDependencyResolver/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.cs:line 55
/root/helix/work/workitem/Loader/AssemblyDependencyResolver/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.sh: line 275: 3758 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/Loader/AssemblyDependencyResolver/Reports/Loader.AssemblyDependencyResolver/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image AssemblyDependencyResolverTests.dll generated successfully.
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun AssemblyDependencyResolverTests.dll ''
TestComponentLoadFailure Start
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3758.dmp
Written 26902528 bytes (6568 pages) to core file
in ReleaseLock
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/AssemblyDependencyResolver/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests/AssemblyDependencyResolverTests.sh
Expected: True
Actual: False


Stack trace
   at Loader_AssemblyDependencyResolver._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/Loader.AssemblyDependencyResolver/Loader.AssemblyDependencyResolver.XUnitWrapper.cs:line 140
~~~

**Comment by jkotas** [comment]
The test depends on internal implementation details that got changed by https://github.com/dotnet/runtime/pull/34813

**Comment by jkotas** [comment]
@EgorBo Could you please take a look? This test is failing in all CoreCLR jobs.

**Comment by jaredpar** [comment]
How was #34813 green given that it broke CI after merge? Did it conflict with a different green PR post merge?

**Comment by jkotas** [comment]
It did not run CoreCLR tests. I do not understand why.

The CoreCLR tests should run for any changes under src/libraries/System.Private.CoreLib : https://github.com/dotnet/runtime/blob/master/eng/pipelines/coreclr/ci.yml#L9
