### ISSUE TITLE
test failure: Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedIsRoughlyEquivalentToInterval

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34888]
failed in job: [runtime-libraries outerloop 20200412.1](https://dev.azure.com/dnceng/public/_build/results?buildId=597835&view=ms.vss-test-web.build-test-results-tab&runId=18830130&paneView=debug&resultId=102059)

Error message
~~~
Timer should fire less than -10% before and less than 50% after expected interval 500, actual: 1849, difference: 269.8%
Expected: True
Actual: False


Stack trace
   at Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedIsRoughlyEquivalentToInterval(Int32 interval) in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/SystemEvents.CreateTimer.cs:line 165
~~~

**Comment by danmosemsft** [comment]
This kind of test is inherently flaky (at least at the upper end).

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200520.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=653190&view=ms.vss-test-web.build-test-results-tab&runId=20277522&resultId=102529&paneView=debug)

failed test: Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedIsRoughlyEquivalentToInterval(interval: 500)


Error message
~~~
Timer should fire less than -10% before and less than 50% after expected interval 500, actual: 872, difference: 74.4%
Expected: True
Actual: False


Stack trace
   at Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedIsRoughlyEquivalentToInterval(Int32 interval) in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/SystemEvents.CreateTimer.cs:line 165
~~~

**Comment by danmosemsft** [comment]
Sometimes the test machine is just overloaded. Until we have the ability to try again on another machine there's not much we can do. @maryamariyan since you own this area -- how about we change this from -10% to 50% to something like -10% to 500%. It's not ideal but at least we would be testing that it didn't fire any sooner than expected. And that it actually fired at all.

**Comment by ericstj** [comment]
Test is inherently flaky which is why it is in outerloop.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200810.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=763270&view=ms.vss-test-web.build-test-results-tab&runId=23713554&resultId=103049&paneView=debug)

failed test: Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedIsRoughlyEquivalentToInterval(interval: 500)


Error message
~~~
Timer should fire less than -10% before and less than 50% after expected interval 500, actual: 2345, difference: 369%
Expected: True
Actual:   False


Stack trace
   at Microsoft.Win32.SystemEventsTests.CreateTimerTests.TimerElapsedIsRoughlyEquivalentToInterval(Int32 interval) in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/SystemEvents.CreateTimer.cs:line 164
~~~

**Comment by maryamariyan** [comment]
I'll change the interval then
