### ISSUE TITLE
Local build on Ubuntu 16.04 fails with restore error

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#34994]
I am hitting the following error when trying to build runtime locally:
```sh
./build.sh -subset Clr -binaryLog
```
```
  Determining projects to restore...
  Microsoft.DotNet.ToolPackage.ResolverCacheInconsistentException: more than one row for coverlet.console-1.7.0-net5.0-any-coverlet
     at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.TryGetMatchingRestoredCommand(RestoredCommandIdentifier restoredCommandIdentifier, CacheRow[] cacheTable, RestoredCommand& restoredCommandList)
     at Microsoft.DotNet.ToolPackage.LocalToolsResolverCache.TryLoad(RestoredCommandIdentifier restoredCommandIdentifier, RestoredCommand& restoredCommand)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.PackageHasBeenRestored(ToolManifestPackage package, String targetFramework)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass11_0.<Execute>b__0(ToolManifestPackage package)
     at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
     at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
     at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
     at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
     at Microsoft.DotNet.Tools.Tool.ToolCommand.Run(String[] args)
     at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
     at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
This seems to be exactly the same issue as #33837 that was happening in the CI and that was supposed to be fixed.

**Comment by janvorli** [comment]
cc: @jaredpar

Here are the binlogs:
https://1drv.ms/u/s!AkLV4wRkyHYhyR6j0hS1eaS5JXZr?e=EM7FEB

**Comment by jaredpar** [comment]
@janvorli can you try running the following command? 

> /home/janvorli/git/runtime2/.dotnet/dotnet nuget list source

Suspect that you have a source there which is complicating things. This is the output from my machine where I can restore successfully:

```
P:\runtime> .\dotnet.cmd nuget list source
P:\runtime\.dotnet
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  dotnet-tools [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  3.  dotnet-eng [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json
  4.  dotnet5 [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  5.  dotnet5-transport [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json
```

**Comment by janvorli** [comment]
This is what the command dumped:
```
/home/janvorli/git/runtime2/.dotnet/dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
```

**Comment by jaredpar** [comment]
@janvorli did you run that from within the `git/runtime2` directory? There should be more sources than that else you wouldn't get very far 

That really shouldn't impact things though. Given your starting state is a cleared NuGet cache and you ran `git clean -dxf .` the only source that could produce the extra package I can think of is extra feeds. There don't appear to be any on your machine though.

@ViktorHofer @safern for ideas on where this duplicate package could be coming from.

**Comment by janvorli** [comment]
No, I didn't. I am sorry I have not realized it makes a difference. Here is the output when ran from that directory:
```
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  dotnet-tools [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
  3.  dotnet-eng [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json
  4.  dotnet5 [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  5.  dotnet5-transport [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json

```

**Comment by ViktorHofer** [comment]
That issue is https://github.com/dotnet/sdk/issues/10938#issuecomment-601997145. I'll open one in Arcade to track setting `DOTNET_CLI_HOME`.

**Comment by jaredpar** [comment]
That issue in SDK is closed though. Is the change just not merged into dotnet/runtime yet?

**Comment by ViktorHofer** [comment]
There was no follow-up change, it was just closed. My guess is because it wasn't actionable in dotnet/sdk. cc @wli3

**Comment by jashook** [comment]
@ViktorHofer is there any follow up here?

**Comment by ViktorHofer** [comment]
Yes, opened https://github.com/dotnet/arcade/issues/5402.

**Comment by janvorli** [comment]
I believe this was fixed already.
