### ISSUE TITLE
Unable to catch exception from native callback due to internal CLR error

### ISSUE THREAD

**Issue by Perksey** [dotnet/runtime#35014]
During startup of our in-development project, one of our testers reported an error preventing them from starting up the application. The error in question involves a first-chance exception thrown by a callback which is called by native code, which should be caught by `[REDACTED].Engine.StartupUtilities.Startup.TestIndividualGLVersion` and, failing that, `[REDACTED].Program.Main`'s call to `ActualMain` so no matter what this exception should be caught.

```
./[REDACTED]
[08:03:40 INFO]: [/0] [REDACTED] - Copyright (C) Ultz Limited
[08:03:40 INFO]: [/0] Started at 4/15/2020 8:03:40 PM.
[08:03:40 INFO]: [/0] Creating graphics device using backend OpenGL...
[08:03:40 DEBUG]: [/0] Checking OpenGL version 4.6...
Unhandled exception. Silk.NET.GLFW.GlfwException: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
   at Silk.NET.GLFW.Glfw.<>c.<.cctor>b__133_0(ErrorCode errorCode, String description)
   at Silk.NET.Windowing.Desktop.GlfwWindow.Initialize()
   at [REDACTED].Engine.StartupUtilities.Startup.TestIndividualGLVersion(Boolean gles, Int32 major, Int32 minor)
Fatal error. Internal CLR error. (0x80131506)
   at Silk.NET.GLFW.X436A9D31.Glfw.CreateWindow(Int32, Int32, System.String, Silk.NET.GLFW.Monitor*, Silk.NET.GLFW.WindowHandle*)
   at Silk.NET.Windowing.Desktop.GlfwWindow.Initialize()
   at [REDACTED].Engine.StartupUtilities.Startup.TestIndividualGLVersion(Boolean, Int32, Int32)
   at [REDACTED].Engine.StartupUtilities.Startup.TestMaxVersion(Boolean)
   at [REDACTED].Engine.StartupUtilities.Startup.GetMaxGLVersion(Boolean)
   at [REDACTED].Engine.StartupUtilities.Startup.SetSDLGLContextAttributes(Ultz.[REDACTED].Graphics.Engine.GraphicsDeviceOptions, Ultz.[REDACTED].Graphics.Engine.GraphicsBackend, Silk.NET.Windowing.Common.WindowOptions ByRef)
   at [REDACTED].Engine.StartupUtilities.Startup.CreateWindowAndGraphicsDevice([REDACTED].Engine.StartupUtilities.WindowCreateInfo, Ultz.[REDACTED].Graphics.Engine.GraphicsDeviceOptions, Ultz.[REDACTED].Graphics.Engine.GraphicsBackend, Silk.NET.Windowing.Common.IWindow ByRef, Ultz.[REDACTED].Graphics.Engine.GraphicsDevice ByRef)
   at [REDACTED].Program.ActualMain()
   at [REDACTED].Program.Main(System.String[])
Aborted
```

There's the log I received from the tester. Notice the `Fatal error. Internal CLR error. (0x80131506)` - something fishy is going on here.

Information regarding this project is sensitive in nature so if there's any further information you need please do not hesistate to contact me at dylan (at) ultz.co.uk

- Deployment: `linux-x64` self-contained deployment
- Built using `5.0.100-preview.1.20155.7` for target framework `netcoreapp3.0`
- Can be reproduced by doing `dotnet [REDACTED].dll` within the self-contained deployment on a machine that has `3.1.100`, but I'm not sure if that makes a difference or not,.
- The machine that is attemting to run it is using a Debian-based distribution of Linux
- `Silk.NET.GLFW.X436A9D31.Glfw.CreateWindow` uses indirect calls to call the native API, which then calls the `Silk.NET.GLFW.Glfw.<>c.<.cctor>b__133_0` callback using a pointer to the pinned delegate.

The actual exception itself isn't the cause for concern, the real problem is why it's not being caught.

**Comment by Perksey** [comment]
Found the cause:
https://docs.microsoft.com/en-us/dotnet/standard/native-interop/exceptions-interoperability
https://github.com/dotnet/runtime/issues/7342

**Comment by Perksey** [comment]
I would appreciate this issue being permenantly deleted if at all possible, due to the confidential nature of the project.

**Comment by stephentoub** [comment]
I'll delete it per your request.
