### ISSUE TITLE
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest failure on Mono

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#35111]
```
    System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1) [FAIL]
      System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.Windows.cs(75,0): at System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(Boolean trySkipCompletionPortOnSuccess)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs(459,0): at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandleSlow()
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs(450,0): at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandle()
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/BaseOverlappedAsyncResult.Windows.cs(50,0): at System.Net.Sockets.BaseOverlappedAsyncResult.SetUnmanagedStructures(Object objectsToPin)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Windows.cs(1033,0): at System.Net.Sockets.SocketPal.ConnectAsync(Socket socket, SafeSocketHandle handle, Byte[] socketAddress, Int32 socketAddressLen, ConnectOverlappedAsyncResult asyncResult)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(4867,0): at System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2235,0): at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2214,0): at System.Net.Sockets.Socket.BeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(123,0): at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketTaskExtensions.cs(19,0): at System.Net.Sockets.SocketTaskExtensions.ConnectAsync(Socket socket, EndPoint remoteEP)
        /_/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs(90,0): at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(IPAddress address)
```

**Comment by jkotas** [comment]
Introduced by https://github.com/dotnet/runtime/pull/35078

**Comment by stephentoub** [comment]
Re-opening to track disabled test

**Comment by jkotas** [comment]
The test is disabled against #34690

**Comment by stephentoub** [comment]
Ah, ok.
