### ISSUE TITLE
System.IO.FileInfo.MoveTo() failing, System.IO.File.Move() working

### ISSUE THREAD

**Issue by snblackout** [dotnet/runtime#35122]
Greetings.  I've encountered and issue with the `FileInfo.MoveTo()` function with ARM on Raspberry Pi 4 but was able to do a workaround.  See below.

```
dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/sbin/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/sbin/dotnet/shared/Microsoft.NETCore.App]
```

OS: Raspbian Buster
Hardware: Raspberry Pi 4

I was working on a download file from server routine.

Pseudo code:

Get list of files need downloading
Download each file individually using a temp filename
Upon finish of download, use `FileInfo.MoveTo()` to move to new final filename

Issue:

Using `FileInfo.MoveTo()` would be called but no exception is thrown.  Checking `FileInfo.Exists` would fail as file was not moved/renamed properly and temp file remained.

Workaround:

Using `File.Move(string, string)` successfully moved/renamed the downloaded file from the temp filename to the final filename.

**Comment by carlossanlop** [comment]
@wli3 @dsplaisted can you help with this issue?

**Comment by dsplaisted** [comment]
@carlossanlop What makes you think this is an SDK issue?  It looks to me like some sort of problem with `FileInfo.MoveTo`, although there doesn't seem to be enough information to really understand the problem.

**Comment by snblackout** [comment]
@dsplaisted I could provide more information if you'd like.  Basically whenever I would call the FileInfo.MoveTo it wouldn't throw an exception and the file would not be moved.  Any checks to that file existing with the new path would fail.  The old path remained and checks on that path were valid.

**Comment by danmosemsft** [comment]
FileInfo.cs
```c#
        public void MoveTo(string destFileName)
        {
            MoveTo(destFileName, false);
        }

        // Moves a given file to a new location and potentially a new file name.
        // Optionally overwrites existing file.
        // This method does work across volumes.
        public void MoveTo(string destFileName, bool overwrite)
        {
...
            string fullDestFileName = Path.GetFullPath(destFileName);

            // These checks are in place to ensure Unix error throwing happens the same way
            // as it does on Windows.These checks can be removed if a solution to
            // https://github.com/dotnet/runtime/issues/14885 is found that doesn't require
            // validity checks before making an API call.
            if (!new DirectoryInfo(Path.GetDirectoryName(FullName)!).Exists)
                throw new DirectoryNotFoundException(SR.Format(SR.IO_PathNotFound_Path, FullName));

            if (!Exists)
                throw new FileNotFoundException(SR.Format(SR.IO_FileNotFound_FileName, FullName), FullName);

            FileSystem.MoveFile(FullPath, fullDestFileName, overwrite);
```

File.cs
```c#
        public static void Move(string sourceFileName, string destFileName)
        {
            Move(sourceFileName, destFileName, false);
        }

        public static void Move(string sourceFileName, string destFileName, bool overwrite)
        {
...
            string fullSourceFileName = Path.GetFullPath(sourceFileName);
            string fullDestFileName = Path.GetFullPath(destFileName);

            if (!FileSystem.FileExists(fullSourceFileName))
            {
                throw new FileNotFoundException(SR.Format(SR.IO_FileNotFound_FileName, fullSourceFileName), fullSourceFileName);
            }

            FileSystem.MoveFile(fullSourceFileName, fullDestFileName, overwrite);
        }
```
Pretty similar. Could you share code snippets @snblackout for how you created and used the FileInfo?

**Comment by davidwengier** [comment]
Just ran into this issue on my M1 MacBook Pro, and it actually breaks the new Razor editor. Working around that in https://github.com/dotnet/razor-tooling/pull/6705 is easy enough, but still. I put up.a small repro at https://github.com/davidwengier/FileMoveTest

Output from running that is as follows:
```
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/davidwengier/Code/FileMoveTest/output.txt.tmp'.
File name: '/Users/davidwengier/Code/FileMoveTest/output.txt.tmp'
   at System.IO.FileInfo.MoveTo(String destFileName, Boolean overwrite)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at Program.<Main>$(String[] args) in /Users/davidwengier/Code/FileMoveTest/Program.cs:line 25
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/davidwengier/Code/FileMoveTest/output.txt.tmp'.
File name: '/Users/davidwengier/Code/FileMoveTest/output.txt.tmp'
   at System.IO.FileInfo.MoveTo(String destFileName, Boolean overwrite)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at Program.<Main>$(String[] args) in /Users/davidwengier/Code/FileMoveTest/Program.cs:line 32
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/davidwengier/Code/FileMoveTest/output.txt.tmp'.
File name: '/Users/davidwengier/Code/FileMoveTest/output.txt.tmp'
   at System.IO.FileInfo.MoveTo(String destFileName, Boolean overwrite)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at Program.<Main>$(String[] args) in /Users/davidwengier/Code/FileMoveTest/Program.cs:line 32
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run fixed
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run fixed
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run fixed
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run fixed
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
% dotnet run fixed
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest 
%
```

Essentially, every second run that uses `MoveTo` fails, but no failures when using `Move`. I would expect both versions of the code to perform exactly the same.

My dotnet info, for completeness:

```
davidwengier@Davids-Work-M1-MacBook-Pro ~/Code/FileMoveTest - (main)
% dotnet --info      
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by davidwengier** [comment]
FYI @jeffhandley in case it changes priority, that the issue is on Apple Silicon and not just Pis :)

**Comment by tfenise** [comment]
https://github.com/dotnet/runtime/blob/058bed796c153ecb1f1a02f443f8d13b70ab81b9/src/libraries/System.Private.CoreLib/src/System/IO/FileInfo.cs#L152-L153

I guess `FileInfo.Exists` is cached, so it thinks the source file does not exist. It seems rather a different problem than what this issue originally was about.

**Comment by davidwengier** [comment]
You might be right, I didn't dig in too much, but the code in the Razor tooling repo has been in place and running on Windows without issue. Only on macOS did the problem occur, so even if it's just a caching issue, seems like it should be consistent on every platform.

**Comment by davidwengier** [comment]
Oh, does it? hmm okay that's surprising, I guess I'm wrong. Interesting, thanks.

**Comment by davidwengier** [comment]
Okay, just woke up and tested, and you're right @tfenise this is nothing to do with the original issue. I will hide all of our comments and slink back to my cave. I guess something in VS/VS for Mac must explain why this was working in Windows for us.

**Comment by danmoseley** [comment]
Seems not enough to do anything here.
