### ISSUE TITLE
System.Text.Json serializing default ImmutableArray<T> causes exceptions

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#35160]
Could `ImmutableArray<T>` be specialized to have `IsDefault` checked? 

We get default `ImmutableArray<T>` values in our models in the first place because null/absense of key causes STJ to leave the default value in place.

```
System.InvalidOperationException: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.IEnumerable.GetEnumerator()
   at System.Text.Json.JsonSerializer.HandleEnumerable(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
```

**Comment by layomia** [comment]
What would the JSON representation be for a `default` collection, `ImmutableArray<T>` or otherwise? I don't think `null` is reasonable because an instance of a value type can't be `null`. An empty JSON array or object (`[]` or `{}`) isn't appropriate either as such default instances are not in fact empty collections.

I think the `InvalidOperationException` thrown here is correct. FWIW, other .NET JSON serializers have the same behavior - https://dotnetfiddle.net/vgHG0a.

A workaround for 5.0, if you want a `null` representation is to make the type nullable, i.e. use `ImmutableArray<T>?`. This won't work for 3.1 due to https://github.com/dotnet/runtime/issues/34876.
