### ISSUE TITLE
CSC crashes with exception ArgumentOutOfRangeException when run with the "COMPlus_JitAggressiveInlining=1" environment variable.

### ISSUE THREAD

**Issue by LadislavLang** [dotnet/runtime#35217]
**Version Used**: 
All csc.exe since first release of Visual Studio 2019, tested with yesterday latest sources (master repository)

**Steps to Reproduce**:
I was able reproduce it only on one computer, but it happens every time.

1. Create empty file "Program.cs"
2. run: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\csc.exe" Program.cs

**Actual Behavior**:
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: length
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
at Microsoft.CodeAnalysis.AssemblyMetadata.GetOrCreateData()
at Microsoft.CodeAnalysis.CommonReferenceManager2.GetMetadata(PortableExecutableReference peReference, CommonMessageProvider messageProvider, Location location, DiagnosticBag diagnostics) at Microsoft.CodeAnalysis.CommonReferenceManager2.ResolveMetadataReferences(TCompilation compilation, Dictionary2 assemblyReferencesBySimpleName, ImmutableArray1& references, IDictionary2& boundReferenceDirectiveMap, ImmutableArray1& boundReferenceDirectives, ImmutableArray1& assemblies, ImmutableArray1& modules, DiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetBoundReferenceManager()
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray1 analyzers, ImmutableArray1 additionalTextFiles, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.b__0(TextWriter tw)
at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)

**My research details and hint for solution**:
I compiled csc.exe from code (master repository), exception was thrown only in Release/x64/net472 build (another configurations are not affected) from class/method CryptoBlobParser/IsValidPulicKey (first call) with argument "00000000000000000400000000000000"

Problem was resolved, when I marked IsValidPublicKey method as NoInlining or when I used build with x86 platform

BTW:  csc.exe (x64) is c. ten times slower than x86 (at least on my computer)

**Comment by danmosemsft** [comment]
Does it repro with .NET Core? If not, then it would go to [developer community.](https://developercommunity.visualstudio.com/spaces/61/index.html)

**Comment by LadislavLang** [comment]
Only Release/x64/net framework, .NET Core is not affected.

**Comment by danmosemsft** [comment]
@LadislavLang in that case the place to report is the link above. Unless the impact is widespread, however, it is unlikely to result in servicing.NET Framework.

**Comment by BruceForstall** [comment]
Given that it doesn't affect .NET Core, I'm going to close this. As @danmosemsft writes, we are unlikely to fix this in .NET Framework unless it occurs in a non-stress mode.

cc @AndyAyersMS
