### ISSUE TITLE
Test failure: System.Net.WebSockets.Client.Tests.ConnectTest.EchoBinaryMessage_Success

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35228]
failed in job: [runtime-libraries outerloop 20200420.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=608143&view=ms.vss-test-web.build-test-results-tab&runId=19101702&resultId=102409&paneView=debug)

Error message
~~~
State immediately after ConnectAsync incorrect: Closed
Expected: True
Actual: False


Stack trace
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<>c__DisplayClass4_0.<<GetConnectedWebSocket>b__0>d.MoveNext() in /_/src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs:line 87
--- End of stack trace from previous location ---
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.Retry[T](ITestOutputHelper output, Func`1 func)
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.TestEcho(Uri server, WebSocketMessageType type, Int32 timeOutMilliseconds, ITestOutputHelper output) in /_/src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs:line 30
   at System.Net.WebSockets.Client.Tests.ConnectTest.EchoBinaryMessage_Success(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/ConnectTest.cs:line 43
--- End of stack trace from previous location ---
~~~

**Comment by karelz** [comment]
No failures during 2/23-5/10 (incl. PRs). Closing.
