### ISSUE TITLE
Issue when combining ReferenceHandling.Preserve and DeserializeAsync

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#35278]
Originally reported on https://github.com/dotnet/runtime/issues/30820#issuecomment-613272109.

Code to reproduce the issue:
```cs
public static async Task ReadMoreDataOnMetadataValueAsync()
{
    // 1..7
    string json = "{\"$id\":";

    // 8..17 - Problem happpens when we step in this portion of the JSON payload.
    json += "\"90123456\"";

    // 18..32
    json += ",\"foo\":\"value\"}";

    var stream = new MemoryStream(Encoding.UTF8.GetBytes(json));

    var opts = new JsonSerializerOptions
    {
        DefaultBufferSize = 16,
        ReferenceHandling = ReferenceHandling.Preserve
    };

    var foo = await JsonSerializer.DeserializeAsync<Foo>(stream, opts);
}
```

Error:
```
System.Text.Json.JsonException : The '$id' and '$ref' metadata properties must be JSON strings. Current token type is 'PropertyName'. Path: $.$id | LineNumber: 0 | BytePositionInLine: 24.
        Stack Trace:
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\ThrowHelper.Serialization.cs(92,0): at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\ThrowHelper.Serialization.cs(449,0): at System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValueWasNotString(JsonTokenType tokenType)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleMetadata.cs(124,0): at System.Text.Json.JsonSerializer.ResolveMetadata(JsonConverter converter, Utf8JsonReader& reader, ReadStack& state)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\Converters\Object\ObjectDefaultConverter.cs(81,0): at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\JsonConverterOfT.cs(182,0): at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\JsonConverterOfT.ReadCore.cs(61,0): at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs(26,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Stream.cs(236,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
          C:\repos\runtime\src\libraries\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Stream.cs(168,0): at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
          C:\repos\runtime\src\libraries\System.Text.Json\tests\Serialization\ReferenceHandlingTests.cs(60,0): at System.Text.Json.Serialization.Tests.ReferenceHandlingTests.ReadMoreDataOnMetadataValueAsync()
```

The reason why this happens is that when we step into the token `"90123456"` we exceed the deserializer's buffer size (16), so we have to unwind the call stack in order to read more data from the stream. When we step back into the code that should read the string token (`"90123456"`), we call `reader.Read` again and hence the reader moves to the next token which is a property (`"foo"`). That should not happen when stepping back where we left since we didn't complete processing the previous token in the first place. 

One possible solution could be to avoid calling `reader.Read` again when we step back into the `HendleMetadata` method after more data is loaded into the deserializer buffer.

**Comment by layomia** [comment]
@Jozkee I noticed this when working on https://github.com/dotnet/runtime/pull/35046. PTAL - that PR might fix this.

**Comment by KerosenoDev** [comment]
Is this in preview 3.20216.6?

**Comment by Jozkee** [comment]
@KerosenoDev No, I think this will be available until preview5; for now you can replace your current package using the preview5 package available on the daily feed gallery, same instructions as https://github.com/dotnet/runtime/issues/30820#issuecomment-578957043, but pick version `5.0.0-preview.5.20230.3` or later instead.

**Comment by ericstj** [comment]
This is too late for Preview4, please grab the latest build as @jozkee suggests.
