### ISSUE TITLE
Unexpected TaskCanceledException when HttpClient.SendAsync fails possibly due to connection issue

### ISSUE THREAD

**Issue by appel1** [dotnet/runtime#35340]
.NET Core 3.1

Is it intentional that HttpClient.SendAsync throws TaskCanceledException when the connection is aborted? It doesn't work very well together with DataFlow that silently swallows TaskCanceledException. 

Is this behavior documented anywhere so we can rely on the fact that a TaskCanceledException with an inner IOException means that we had some kind of connection failure and is not a cancelation at all? 

```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at HttpClientWebConnectorRequestor.SendRequestAsync(Uri requestUri, String sessionId, XNode postXml, String acceptedContentType, SendRequestOptions options, Nullable`1 lastModified, HashSet`1 acceptedCertificateThumbnails, CancellationToken cancellationToken) in HttpClientWebConnectorRequestor.cs:line 76
```

**Comment by davidsh** [comment]
@alnikola

**Comment by wfurt** [comment]
You can get cancel exception on timeout @appel1. It is possible timeout hit when waiting in FillAsyns. You can play with Timeout value on HttpClientHandler as well as do packet capture.

**Comment by thriolsson** [comment]
Seems to me like you would like TaskCanceledException to be reserved for the case when a task is canceled using a CancellationToken. This would be my expectation.

**Comment by appel1** [comment]
@wfurt That's very unexpected considering the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=netcore-3.1) states that SendAsync throws a HttpRequestException for timeouts.

**Comment by wfurt** [comment]
Do you have repro @appel1 ? You can read more about this here https://github.com/dotnet/runtime/issues/21965 and it clearly looks like a duplicate. 
You can also give it try with 5.0 preview builds.

**Comment by wfurt** [comment]
I'm wondering @karelz  if we could update the docs since we clearly have versions with different behavior. Perhaps simply remove references to timeout.

**Comment by appel1** [comment]
@wfurt Yes, it looks like the same as that issue. And depending on where you are in SendAsync you get different inner exceptions or none in the TaskCanceledException. 

Don't agree that using TaskCanceledException in the case of a timeout is a good idea. Very unintuitive and breaks things like DataFlow that doesn't expect you to misuse TaskCanceledException in this manner.

**Comment by wfurt** [comment]
give it try with 5.0. It is unlikely 3.x will change at this point.

**Comment by appel1** [comment]
Looks like 5.0 still throws a TaskCancelledException for timeouts, but a little nicer since the mandatory try-catch can now inspect the inner exception to find out that it was a timeout. 

Hopefully this can be highlighted very clearly in the docs since it causes a mess if you are not careful together with DataFlow. 

https://github.com/dotnet/runtime/blob/b4439ca1fd994c8ec2592fb9614a841853ae08fb/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L600-L604

**Comment by karelz** [comment]
Triage:
- Addressed in 5.0 in #21965
- We need to fix the docs -- address specific versions (.NET Core different versions vs. .NET Framework) ... Note: there is only 1 page for all versions
    - Take into account that `HttpRequestException` may have been used in past versions (.NET Framework)

**Comment by alnikola** [comment]
Created a PR in docs repo dotnet/dotnet-api-docs#4340

**Comment by alnikola** [comment]
Documentation PR dotnet/dotnet-api-docs#4340 is merged.
