### ISSUE TITLE
MemoryMappedViewAccessorTests.AllowFinalization test failure [Mono]  

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#35452]
```
  Starting:    System.IO.MemoryMappedFiles.Tests (parallel test collections = on, max threads = 2)
    System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.AllowFinalization [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/System.IO.MemoryMappedFiles/tests/MemoryMappedViewAccessor.Tests.cs(498,0): at System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.AllowFinalization()
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by jkotas** [comment]
Hit in #35435 https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35435-merge-8a6b2f1055a54e0793/System.IO.MemoryMappedFiles.Tests/console.f8b2754d.log?sv=2019-02-02&se=2020-05-05T08%3A06%3A06Z&sr=c&sp=rl&sig=h3yVPUIPqg7unJuXxPIHC8lvpHbtghYE8rsU9BeKTUs%3D
