### ISSUE TITLE
Test failure: AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Passed_For_Single_File_App

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35503]
failed in job: [runtime 20200426.70 ](https://dev.azure.com/dnceng/public/_build/results?buildId=618699&view=ms.vss-test-web.build-test-results-tab&runId=19377170&resultId=100006&paneView=debug)

Error message
~~~
Expected command to pass but it did not."
File Name: /root/runtime/artifacts/tests/Release/ahb/1/BundleProbeTester/bundle/BundleProbeTester
Arguments: SingleFile
Exit Code: 253
StdOut:
Unexpected file hostpolicy.dll found in bundle.

StdErr:

"


Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in /_/src/installer/test/TestUtils/Assertions/CommandResultAssertions.cs:line 31
   at AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Passed_For_Single_File_App() in /_/src/installer/test/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleProbe.cs:line 46
~~~

**Comment by swaroop-sridhar** [comment]
This is a dup of #35755
