### ISSUE TITLE
Test failure:profiler\\rejit\\rejit\\rejit.cmd (crossgen2 pipeline)

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#35639]
Test profiler\\rejit\\rejit\\rejit.cmd has failed.
Job:
[runtime-coreclr crossgen2 20200428.3](https://dev.azure.com/dnceng/public/_build/results?buildId=622737&view=results)
```
Assert failure(PID 2244 [0x000008c4], Thread: 3488 [0x0da0]): inliners

CORECLR! PersistentInlineTrackingMapR2R2::GetInliners + 0xEB (0x00007ff8b00d251b)
CORECLR! Module::GetNativeOrReadyToRunInliners + 0x45 (0x00007ff8afd0b9dd)
CORECLR! NativeImageInliningIterator::Reset + 0x180 (0x00007ff8b00be394)
CORECLR! ReJitManager::UpdateNativeInlinerActiveILVersions + 0x271 (0x00007ff8b00bfa89)
CORECLR! ReJitManager::UpdateActiveILVersions + 0x247 (0x00007ff8b00bf0b3)
CORECLR! ReJitManager::RequestReJIT + 0x16 (0x00007ff8b00be0fa)
CORECLR! ProfToEEInterfaceImpl::RequestReJITWithInliners + 0x516 (0x00007ff8aff992a6)
PROFILER! <no symbol> + 0x0 (0x00007ff8ad4b72a3)
PROFILER! <no symbol> + 0x0 (0x00007ff8ad4b7e87)
CORECLR! EEToProfInterfaceImpl::JITCachedFunctionSearchFinished + 0x398 (0x00007ff8afbd0760)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\inlinetracking.cpp Line: 632
    Image: C:\h\w\A91A0984\p\CoreRun.exe

Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\common\ProfilerTestRunner.cs:line 135
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\common\ProfilerTestRunner.cs:line 89
   at Profiler.Tests.RejitWithInlining.Main(String[] args) in F:\workspace\_work\1\s\src\coreclr\tests\src\profiler\rejit\rejit.cs:line 100

Return code:      1
Raw output file:      C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\Reports\profiler.rejit\rejit\rejit.output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
Response file: C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\\rejit.dll.rsp
--inputbubble
C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\IL\rejit.dll
-r:C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\IL\.dll
-o:C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\\rejit.dll
--targetarch:x64
-O
-r:C:\h\w\A91A0984\p\System..dll
-r:C:\h\w\A91A0984\p\Microsoft.*.dll
-r:C:\h\w\A91A0984\p\mscorlib.dll
-r:C:\h\w\A91A0984\p\netstandard.dll
" "C:\h\w\A91A0984\p\CoreRun.exe" "C:\h\w\A91A0984\p\crossgen2\crossgen2.dll" @"C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\\rejit.dll.rsp" "
Warning: Method [rejit]Profiler.Tests.RejitWithInlining.Main(string[]) was not compiled because: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: profiler_common
Emitting R2R PE file: C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\rejit.dll
 "C:\h\w\A91A0984\p\corerun.exe" rejit.dll 
Profiler path: C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\Profiler.dll
Disabling tiered compilation.
Profiler path: C:\h\w\A91A0984\w\A65F0933\e\profiler\rejit\rejit\Profiler.dll
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
INFO ReJITProfiler::Initialize - Initialize started
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=StelemRef Inlinee=As<System.__Canon> Inlinee module name=C:\h\w\A91A0984\p\System.Private.CoreLib.dll
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=StelemRef Inlinee=GetMethodTable Inlinee module name=C:\h\w\A91A0984\p\System.Private.CoreLib.dll
INFO ReJITProfiler::AddInlining - Inlining
```

Details:
https://dev.azure.com/dnceng/public/_build/results?buildId=622737&view=ms.vss-test-web.build-test-results-tab&runId=19479104&resultId=100006&paneView=debug

**Comment by nattress** [comment]
Possibly related to https://github.com/dotnet/runtime/issues/35472. This test has never passed on crossgen2 compiler though.

**Comment by nattress** [comment]
https://github.com/dotnet/runtime/issues/35472 only fails jitstress runs when `COMPlus_JITMinOpts=1`, which is not set in crossgen2 runs.
