### ISSUE TITLE
The current TransactionScope is already complete error after converting to .net core 3.1

### ISSUE THREAD

**Issue by dresdor** [dotnet/runtime#35720]
After an update to 3.1, we've been receiving error messages that state:

System.InvalidOperationException: The current TransactionScope is already complete.

The only real change we've made to this process is to move from the 2.x way of doing using statements with brackets to the 3.x way of using statements without brackets (as is recommended). 

Current Way:

    // As multiple copies of this service can be running at once, we should lock the table while we flag the messages to be worked on
    using var transactionScope = new TransactionScope(TransactionScopeOption.Required,
                  new TransactionOptions()
    { IsolationLevel = IsolationLevel.ReadCommitted });
    messagesToProcess = context.InboundMessageQueueRecords.Where(x => x.State == QueueMessageState.New)
              .OrderBy(x => x.Added)
              .Take(NUMBER_OF_MESSAGES_TO_PROCESS).ToList();
    // Flag them as in progress
    messagesToProcess.ForEach(x => x.State = QueueMessageState.InProgress);
    context.SaveChanges();
    transactionScope.Complete();

Old Way:

     // As multiple copies of this service can be running at once, we should lock the table while we flag the messages to be worked on
    using (var transactionScope = new TransactionScope(TransactionScopeOption.Required,
                  new TransactionOptions()
                    { IsolationLevel = IsolationLevel.ReadCommitted }))
    {
        messagesToProcess = context.InboundMessageQueueRecords.Where(x => x.State == QueueMessageState.New)
                .OrderBy(x => x.Added)
                .Take(NUMBER_OF_MESSAGES_TO_PROCESS).ToList();
        // Flag them as in progress
        messagesToProcess.ForEach(x => x.State = QueueMessageState.InProgress);
        context.SaveChanges();
        transactionScope.Complete();
    }

**Comment by dresdor** [comment]
should be labelled with area-System.Transactions but cannot figure out how to label it.

**Comment by stephentoub** [comment]
Can you share a repro?

**Comment by dresdor** [comment]
I have zipped a repo and made it available [here](https://drive.google.com/open?id=1DgFLhVeyzgqacPmsfT2URKCpr1vX00aQ).   I managed to screw up my github desktop client and could not easily push a repo into github.  I can put it there later, but it's going to take a little bit.

The MessagQueueHandler class is the one with the transaction issue.

**Comment by karlra** [comment]
You are calling context.SaveChanges on line 123, after calling TransactionScope.Complete. The TransactionScope.Complete does not commit the transaction as one would expect, this happens only after it is disposed which is on line 132. Without knowing anything about how EF works I would assume this is the problem, and the code examples you posted aren't equivalent.

**Comment by dresdor** [comment]
@karlra Save changes on 132 is part of the ef core update process.  I only need the transaction scope for the initial updating and flagging of messages, as that is the only part of the process that needs to be partially blocking/locking.  The error is being called when TransactionScope.Comlete() is called, so the erroring code never reaches line 132

**Comment by HongGit** [comment]
@dresdor does the old way work after switching to 3.1?  

Nothing has changed in System.Transactions in 3.1.

**Comment by dresdor** [comment]
Yes, the old way works just fine using brackets instead of whatever 3.1 uses to decide its using scope.

My guess is "something" in the way that method is set up is triggering the interpretation of the using statement to go wonky (technical terms, I know).

**Comment by dshamim** [comment]
I have the same issue where the following throws intermittent Exceptions:

```
                using var scope = new TransactionScope();
                var relatedImages = _mapper.Map<IEnumerable<string>>(filteredImageList);
                await UpdateImages(appraisalId, relatedImages, RecordType.Appraisal);
                await UpdateImages(sourceId, relatedImages, RecordType.Sourcing);
                scope.Complete();
```

Getting the following intermittently 

Dealer.Sourcing.Common.Exceptions.DatabaseException: Exception occured on Get Images
 ---> System.InvalidOperationException: The current TransactionScope is already complete.
   at System.Transactions.Transaction.get_Current()
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419
   at Dealer.Sourcing.Common.Repositories.AppraisalRepository.GetImages(Guid recordId) in C:\Projects\Carsales\Dealer.Sourcing\Dealer.Sourcing.Common\Repositories\AppraisalRepository.cs:line 124
   --- End of inner exception stack trace ---

**Comment by ygoldenberg-paradigm** [comment]
By leaving out the brackets, the scope of the using statement is extended to the end of the current block, which includes the call to `context.SaveChanges()` on line 123, as mentioned by @karlra. When the brackets are used, it constrains the using statement to the code within the brackets.
You can get the same results with the new recommended way of writing the using statement if you add an extra set of brackets to constrain the scope of the using statement, like this:
``` c#
                    {
                        using var transactionScope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions() { IsolationLevel = IsolationLevel.ReadCommitted });
                        messagesToProcess = context.InboundMessageQueueRecords.Where(x => x.State == QueueMessageState.New).OrderBy(x => x.Added).Take(NUMBER_OF_MESSAGES_TO_PROCESS).ToList();
                        // Flag them as in progress
                        messagesToProcess.ForEach(x => x.State = QueueMessageState.InProgress);
                        context.SaveChanges();
                        transactionScope.Complete();
                    }
```
