### ISSUE TITLE
ArgIteratorTests.ArgIterator_Throws_PlatformNotSupportedException test fails on Windows ARM

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#35754]
```
System.Tests.ArgIteratorTests.ArgIterator_Throws_PlatformNotSupportedException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.ArgumentException): Handle is not initialized.
      ---- System.ArgumentException : Handle is not initialized.
      Stack Trace:
           at System.ArgIterator..ctor(IntPtr arglist)
        /_/src/coreclr/src/System.Private.CoreLib/src/System/ArgIterator.cs(35,0): at System.ArgIterator..ctor(RuntimeArgumentHandle arglist)
        /_/src/libraries/System.Runtime/tests/System/ArgIteratorTests.cs(93,0): at System.Tests.ArgIteratorTests.<>c.<ArgIterator_Throws_PlatformNotSupportedException>b__6_0()
        ----- Inner Stack Trace -----
           at System.ArgIterator..ctor(IntPtr arglist)
        /_/src/coreclr/src/System.Private.CoreLib/src/System/ArgIterator.cs(35,0): at System.ArgIterator..ctor(RuntimeArgumentHandle arglist)
        /_/src/libraries/System.Runtime/tests/System/ArgIteratorTests.cs(93,0): at System.Tests.ArgIteratorTests.<>c.<ArgIterator_Throws_PlatformNotSupportedException>b__6_0()
```

Var args is supposed to throw not supported exception in Windows ARM.

For more info, see: https://github.com/dotnet/runtime/pull/35690#issuecomment-622597724

cc: @jkotas @jashook

**Comment by safern** [comment]
Disabling the test in: https://github.com/dotnet/runtime/pull/35690
