### ISSUE TITLE
DependencyInjectionEventSourceTests.EmitsDynamicMethodBuiltEvent test failure on Windows in CI

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#35753]
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#626777](https://dev.azure.com/dnceng/public/_build/results?buildId=626777)|Rolling|1|
|[#626849](https://dev.azure.com/dnceng/public/_build/results?buildId=626849)|#35712|1|
|[#626950](https://dev.azure.com/dnceng/public/_build/results?buildId=626950)|Rolling|1|
### Configurations
- netcoreapp5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open
- netcoreapp5.0-Windows_NT-Release-x64-Mono_release-Windows.10.Amd64.Server19H1.Open
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#626777](https://dev.azure.com/dnceng/public/_build/results?buildId=626777)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/6e37991f-9aa2-4a67-9dd3-cb3bf4243692/workitems/Microsoft.Extensions.DependencyInjection.Tests/files/console.c054715e.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/6e37991f-9aa2-4a67-9dd3-cb3bf4243692/workitems/Microsoft.Extensions.DependencyInjection.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-50-preview46e37991f9aa24a679d/Microsoft.Extensions.DependencyInjection.Tests/a4bb3d3e-9be2-4ce9-9006-456816cc38f9.log?sv=2019-02-02&se=2020-05-11T18%3A15%3A55Z&sr=c&sp=rl&sig=9V1xYWazICZ6CYS1mvhEfJ8tuNHOt%2FNMgbVs%2BOasPEU%3D)|
|[#626849](https://dev.azure.com/dnceng/public/_build/results?buildId=626849)|#35712|[console.log](https://helix.dot.net/api/2019-06-17/jobs/e03bbe9b-1e74-4de2-9e07-ae9f4867c35e/workitems/Microsoft.Extensions.DependencyInjection.Tests/files/console.83c7b96e.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/e03bbe9b-1e74-4de2-9e07-ae9f4867c35e/workitems/Microsoft.Extensions.DependencyInjection.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-35712-merge-e03bbe9b1e744de29e/Microsoft.Extensions.DependencyInjection.Tests/1255f0c6-0bf0-4445-a070-0b292cf07e2f.log?sv=2019-02-02&se=2020-05-11T19%3A42%3A07Z&sr=c&sp=rl&sig=%2BAuIuU2VIo0eDTu4unzCju1lWTYUTW83dYwa1pf9wkQ%3D)|
|[#626950](https://dev.azure.com/dnceng/public/_build/results?buildId=626950)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/a23a41ad-f70c-4f9c-b9d3-051b314baa0e/workitems/Microsoft.Extensions.DependencyInjection.Tests/files/console.21d8220f.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/a23a41ad-f70c-4f9c-b9d3-051b314baa0e/workitems/Microsoft.Extensions.DependencyInjection.Tests/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-helixqueuesupdate-a23a41adf70c4f9cb9/Microsoft.Extensions.DependencyInjection.Tests/fd04e531-bef8-4205-a39f-e3621e3c615e.log?sv=2019-02-02&se=2020-05-11T21%3A22%3A37Z&sr=c&sp=rl&sig=kvDn%2B6Bvzb9QgTT%2BsV4gwiqCk44fGAhmVjt%2BWFjtHR8%3D)|

```
 Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSourceTests.EmitsDynamicMethodBuiltEvent [FAIL]
      System.InvalidOperationException : Sequence contains more than one matching element
      Stack Trace:
        /_/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs(22,0): at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
        /_/src/libraries/System.Linq/src/System/Linq/Single.cs(74,0): at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
        /_/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DependencyInjectionEventSourceTests.cs(206,0): at Microsoft.Extensions.DependencyInjection.DependencyInjectionEventSourceTests.EmitsDynamicMethodBuiltEvent()
```

Will disable the test in the meantime.

**Comment by safern** [comment]
Disabling the test in https://github.com/dotnet/runtime/pull/35690
