### ISSUE TITLE
CI test Failure in Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.ComponentActivation.CallDelegate

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#3584]
`Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.ComponentActivation.CallDelegate(validPath: True, validType: True, validMethod: True)`
on
`Installer-Windows_NT_x86-Debug`
https://dev.azure.com/dnceng/public/_build/results?buildId=501284&view=ms.vss-test-web.build-test-results-tab&runId=15922422&paneView=debug
```
Expected command to pass but it did not."
File Name: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\nativeHosting\0\nativehost.exe
Arguments: load_assembly_and_get_function_pointer F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\host\fxr\5.0.0-ci\hostfxr.dll F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.json F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.dll \"Component.Component, ComponentWithNoDependencies\" ComponentEntryPoint1
Exit Code: -1073741819
StdOut:
Called ComponentEntryPoint1(0xdeadbeef, 42) - component call count: 1
[CONFIG] hostfxr_initialize_for_runtime_config succeeded: 0
[CONFIG] hostfxr_get_runtime_delegate succeeded: 0
[CONFIG] calling load_assembly_and_get_function_pointer(\"F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.dll\", \"Component.Component, ComponentWithNoDependencies\", \"ComponentEntryPoint1\", \"nullptr, nullptr, &componentEntryPointDelegate)
[CONFIG] load_assembly_and_get_function_pointer succeeded: 0
[CONFIG] ComponentEntryPoint1 delegate result: 0x1


StdErr:
Tracing enabled @ Thu Jan 30 00:40:55 2020 GMT
--- Invoked hostfxr_initialize_for_runtime_config [commit hash: a6c5f5ea50fbbe41fdb434d49ff44e21611e48ce]
Checking if CoreCLR path exists=[F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\host\fxr\5.0.0-ci\coreclr.dll]
Specified runtimeconfig.json from [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.json]
Runtime config is cfg=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.json dev=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.dev.json
Attempting to read runtime config: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.json
Attempting to read dev runtime config: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.dev.json
Runtime config [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.json] is valid=[1]
--- The specified framework 'Microsoft.NETCore.App', version '5.0.0-ci', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '5.0.0-ci'.
--- Resolving FX directory, name 'Microsoft.NETCore.App' version '5.0.0-ci'
DOTNET_MULTILEVEL_LOOKUP is set to 0
Multilevel lookup is false
Searching FX directory in [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish]
Attempting FX roll forward starting from version='[5.0.0-ci]', apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, prefer_release=0
'Roll forward' enabled with version_compatibility_range [minor]. Looking for the lowest release/pre-release greater than or equal version to [5.0.0-ci]
Found version [5.0.0-ci]
Framework reference resolved to version '5.0.0-ci'.
Changing Selected FX version from [] to [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci]
Chose FX version [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci]
Runtime config is cfg=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.runtimeconfig.json dev=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.runtimeconfig.dev.json
Attempting to read runtime config: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.runtimeconfig.json
Attempting to read dev runtime config: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.runtimeconfig.dev.json
Runtime config [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.runtimeconfig.json] is valid=[1]
--- Summary of all frameworks:
 framework:'Microsoft.NETCore.App', lowest requested version='5.0.0-ci', found version='5.0.0-ci', effective reference version='5.0.0-ci' apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, folder=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci
Libhost loading occurring for a framework-dependent component per config file [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\0\ComponentWithNoDependencies\bin\ComponentWithNoDependencies.runtimeconfig.json]
--- Resolving hostpolicy.dll version from deps json [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.deps.json]
Resolved version 5.0.0-ci from dependency manifest file [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\Microsoft.NETCore.App.deps.json]
Did not find hostpolicy.dll in directory C:\Program Files (x86)\coreservicing\pkgs\runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy\5.0.0-ci\runtimes\win-x86\native
The expected hostpolicy.dll directory is [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci]
Loaded library from F:\workspace\_work\1\s\artifacts\tests\Debug\ha\sharedFrameworkPublish\shared\Microsoft.NETCore.App\5.0.0-ci\hostpolicy.dll
Tracing enabled @ Thu Jan 30 00:40:55 2020 GMT
Reading from host interface version: [0x16041101:120] to initialize policy version: [0x16041101:120]
--- Invoked hostpolicy [commit hash: a6c5f5ea50fbbe41fdb434d49ff44e21611e48ce] [runtime.win-x86.Microsoft.NETCore.DotNetHostPolicy,5.0.0-ci,runtimes/win-x86/native][x86] corehost_initialize = {
}
// etc//
--- Invoked hostfxr_close [commit hash: a6c5f5ea50fbbe41fdb434d49ff44e21611e48ce]

"


Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in /_/src/installer/test/TestUtils/Assertions/CommandResultAssertions.cs:line 31
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.ComponentActivation.CallDelegate(Boolean validPath, Boolean validType, Boolean validMethod) in /_/src/installer/test/HostActivation.Tests/NativeHosting/ComponentActivation.cs:line 49
```

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/pull/2373

**Comment by elinor-fung** [comment]
Same root issue as #2320
