### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35886]
failed in job: [runtime-libraries outerloop 20200505.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=631532&view=ms.vss-test-web.build-test-results-tab&runId=19694176&resultId=103124&paneView=debug)

Error message
~~~
System.Net.Sockets.SocketException : Bad value for ai_flags


Stack trace
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1138
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1123
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 220
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 320
   at System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync(Boolean connectByName) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs:line 435
--- End of stack trace from previous location ---
~~~

**Comment by stephentoub** [comment]
The `Bad value for ai_flags` is misleading.  This is the message that's getting returned for the generic SocketError.SocketError enum value: https://github.com/dotnet/runtime/issues/35955.
