### ISSUE TITLE
Test failure: Expected a value greater or equal to 0 because Trying to filter StdErr after 'corehost_resolve_component_dependencies = {', but such string can't be found in the StdErr.

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35948]
failed in job: [runtime 20200506.84 ](https://dev.azure.com/dnceng/public/_build/results?buildId=633940&view=ms.vss-test-web.build-test-results-tab&runId=19746274&resultId=100672&paneView=debug)

failed test: 
MostSpecificRidNativeLibrarySelected
RidSpecificAssembly
RidSpecificNativeLibrary
MostSpecificRidAssemblySelectedPerTypeMultipleAssets
AppWithSameAssemblyAsFramework
ComponentWithResourcesShouldReportResourceSearchPaths
MostSpecificRidAssemblySelectedPerType
ComponentWithDependenciesAndDependencyRemoved
ComponentWithSameDependencyWithDifferentExtensionShouldFail
ComponentWithDependencies
ComponentWithDependenciesAndNoDeps
ComponentWithNoDependenciesAndNoDeps
InvalidMainComponentAssemblyPathFails
AdditionalDepsDontAffectComponentDependencyResolution

Error message
~~~
Expected a value greater or equal to 0 because Trying to filter StdErr after 'corehost_resolve_component_dependencies = {', but such string can't be found in the StdErr.
Tracing enabled @ Wed May 6 23:26:09 2020 UTC
--- Invoked hostfxr_initialize_for_dotnet_command_line [commit hash: f4a67dfe8528126ef4330eb433a433f7b8713759]
, but found -1.


Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Numeric.NumericAssertions`1.BeGreaterOrEqualTo(T expected, String because, Object[] becauseArgs)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultExtensions.StdErrAfter(CommandResult commandResult, String pattern) in /_/src/installer/test/TestUtils/Assertions/CommandResultExtensions.cs:line 21
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.DependencyResolution.ComponentDependencyResolutionBase.ComponentSharedTestStateBase.RunComponentResolutionTest(String componentPath, TestApp hostApp, String hostFxrFolder, Action`1 commandCustomizer) in /_/src/installer/test/HostActivation.Tests/DependencyResolution/ComponentDependencyResolutionBase.cs:line 67
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.DependencyResolution.ComponentDependencyResolutionBase.ComponentSharedTestStateBase.RunComponentResolutionTest(TestApp component, Action`1 commandCustomizer) in /_/src/installer/test/HostActivation.Tests/DependencyResolution/ComponentDependencyResolutionBase.cs:line 48
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.DependencyResolution.PortableComponentOnFrameworkDependentAppRidAssetResolution.RunTest(Action`1 assetsCustomizer, String rid, String includedAssemblyPaths, String excludedAssemblyPaths, String includedNativeLibraryPaths, String excludedNativeLibraryPaths, Action`1 appCustomizer) in /_/src/installer/test/HostActivation.Tests/DependencyResolution/RidAssetResolution.cs:line 205
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.DependencyResolution.RidAssetResolutionBase.MostSpecificRidNativeLibrarySelected(String rid, String expectedPath) in /_/src/installer/test/HostActivation.Tests/DependencyResolution/RidAssetResolution.cs:line 74
~~~

**Comment by vitek-karas** [comment]
I think this is also Linux-musl which we've had a known issue with around the time of the failure. It has been fixed since. Please reopen if this happens again.
