### ISSUE TITLE
Test failure: System.InvalidProgramException: Non-blittable parameter types are invalid for UnmanagedCallersOnly methods.

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35944]
failed in job: [runtime-coreclr jitstress 20200505.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=632801&view=ms.vss-test-web.build-test-results-tab&runId=19723198&resultId=109005&paneView=debug)

failed tests:
JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh
JIT/SIMD/Vector3Interop_ro/Vector3Interop_ro.sh
JIT\\SIMD\\Vector3Interop_ro\\Vector3Interop_ro.cmd
JIT\\SIMD\\Vector3Interop_r\\Vector3Interop_r.cmd

Error message
~~~
Unhandled exception. System.InvalidProgramException: Non-blittable parameter types are invalid for UnmanagedCallersOnly methods.
 at RPInvokeTest.nativeCall_RPInvoke_Vector3Ret(CallBackDelegate_RPInvoke_Vector3Ret callBack)
 at RPInvokeTest.test()
 at Test.Main()
/private/tmp/helix/working/A0920915/w/99AF08EB/e/JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh: line 316: 43308 Abort trap: 6 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/A0920915/w/99AF08EB/e/JIT/SIMD/Reports/JIT.SIMD/Vector3Interop_r/Vector3Interop_r.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A0920915/p/corerun Vector3Interop_r.dll ''
nativeCall_PInvoke_CheckVector3Size: sizeof(Vector3) == 12
nativeCall_PInvoke_Vector3Arg:
 iVal 123
 sumOfEles(1.000000, 2.000000, 3.000000) = 6.000000
 str abcdefg
 sumOfEles(10.000000, 11.000000, 12.000000) = 33.000000
nativeCall_PInvoke_Vector3Arg_Unix:
 v3f32_xmm0: 1.000000 2.000000 3.000000
 f32_xmm2 - f32_xmm7: 100.000000 101.000000 102.000000 103.000000 104.000000 105.000000
 f32_mem0: 106.000000
 v3f32_mem1: 10.000000 20.000000 30.000000
 f32_mem2-3: 107.000000 108.000000
 sum = 1002.000000
nativeCall_PInvoke_Vector3Arg_Unix2:
 v3f32_xmm0: 1.000000 2.000000 3.000000
 f32_xmm2 - f32_xmm7: 100.000000 101.000000 102.000000 103.000000 104.000000 105.000000
 f32_mem0: 106.000000
 v3f32_mem1: 4.000000 5.000000 6.000000
 f32_mem2-3: 107.000000 108.000000
 v3f32_mem4: 7.000000 8.000000 9.000000
 f32_mem5: 109.000000
 sum = 1090.000000
nativeCall_PInvoke_Vector3Ret:
 Return value: (1.000000, 2.000000, 3.000000)
 Sum of return scalar values = 6.000000
nativeCall_PInvoke_Vector3Array
 arrEle[0]: 1.000000 2.000000 3.000000
 arrEle[1]: 5.000000 6.000000 7.000000
 Sum = 24.000000
nativeCall_PInvoke_Vector3InStruct
 First struct memeber: (1.000000 2.000000 3.000000) -> (2.000000 3.000000 4.000000)
 Second struct member: (5.000000 6.000000 7.000000) -> (6.000000 7.000000 8.000000)
 Sum of all return scalar values = 30.000000
nativeCall_PInvoke_Vector3InComplexStruct
 Arg ival: 99
 Arg Vector3 v1: (1.000000 2.000000 3.000000)
 Arg Vector3 v2: (5.000000 6.000000 7.000000)
 Arg Vector3 v3: (10.000000 20.000000 30.000000)
 Arg string arg: arg_string
 Return ival: 100
 Return Vector3 v1: (2.000000 3.000000 4.000000)
 Return Vector3 v2: (6.000000 7.000000 8.000000)
 Return Vector3 v3: (11.000000 21.000000 31.000000)
 Return string arg: ret_string
 Sum of all return float scalar values = 93.000000
 Managed ival: 100
 Managed Vector3 v1: (2 3 4)
 Managed Vector3 v2: (6 7 8)
 Managed Vector3 v3: (11 21 31)
 Managed string arg: ret_string
 Managed Sum = 735
All PInvoke testcases passed
callBack_RPInvoke_Vector3Arg:
 iVal 123
 Sum0,1,2 = 14, 1400, 140
 str abcdefg
callBack_RPInvoke_Vector3Arg_Unix:
 1, 2, 3
 10, 20, 30
 Sum0,1,2,3 = 14, 1400, 140, 936
callBack_RPInvoke_Vector3Arg_Unix2:
 1, 2, 3
 4, 5, 6
 7, 8, 9
 Sum0,1,2,3,4,5 = 14, 77, 194, 32, 122, 1045
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/A0920915/p
> /private/tmp/helix/working/A0920915/w/99AF08EB/e/JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh
Expected: True
Actual: False


Stack trace
   at JIT_SIMD._Vector3Interop_r_Vector3Interop_r_._Vector3Interop_r_Vector3Interop_r_sh() in /Users/runner/runners/2.166.4/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/JIT.SIMD/JIT.SIMD.XUnitWrapper.cs:line 4893
~~~

**Comment by BruceForstall** [comment]
@AaronRobinsonMSFT @tannergooding @echesakovMSFT @CarolEidt

**Comment by tannergooding** [comment]
I believe @AaronRobinsonMSFT already fixed this with https://github.com/dotnet/runtime/pull/35926
