### ISSUE TITLE
Test failure: Expected command to pass but it did not

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35950]
failed in job: [runtime 20200506.84 ](https://dev.azure.com/dnceng/public/_build/results?buildId=633940&view=ms.vss-test-web.build-test-results-tab&runId=19746274&resultId=100672&paneView=debug)

failed test:
CompatibilityCheck_Properties
RunApp
RunApp_GetDelegate
MultiThreadedComponentDependencyResolutionWhichSucceeeds

Error message
~~~
Expected command to pass but it did not."
File Name: /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/nativehost
Arguments: host_context mixed none /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/mockRuntime/host/fxr/5.0.0-ci/libhostfxr.so /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/app/App_MultiProperty.dll /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/propertyCompat.runtimeconfig.json
Exit Code: 139
StdOut:

StdErr:
Tracing enabled @ Wed May 6 23:27:25 2020 UTC
--- Invoked hostfxr_initialize_for_dotnet_command_line [commit hash: f4a67dfe8528126ef4330eb433a433f7b8713759]

"



Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in /_/src/installer/test/TestUtils/Assertions/CommandResultAssertions.cs:line 33
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.HostContext.CompatibilityCheck_Properties(String scenario, Boolean hasMultipleProperties, PropertyTestData[] properties) in /_/src/installer/test/HostActivation.Tests/NativeHosting/HostContext.cs:line 516
~~~

**Comment by vitek-karas** [comment]
@VSadov this might be caused by the host build changes (since the rolling build points to that commit)

**Comment by swaroop-sridhar** [comment]
This is surprising, because Linux-MUSL-Release-x64 is a part of the PR job now.

**Comment by vitek-karas** [comment]
Note that this was filed 14 days ago - so maybe we fixed it since.

**Comment by VSadov** [comment]
My guess it has been fixed.

**Comment by vitek-karas** [comment]
Please reopen if we see this again - we think this has been fixed since.
