### ISSUE TITLE
Installer Build and Test coreclr Linux_musl_x64 Release failing in CI

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#35967]
This job has about 100% failure now with lots of tests failing.

```
CompatibilityCheck_Frameworks 39
RunApp 29
AppWithSameAssemblyAsFramework 25
CompatibilityCheck_Properties 22
MostSpecificRidAssemblySelected 9
MostSpecificRidAssemblySelectedPerType 9
MostSpecificRidNativeLibrarySelected 9
RidSpecificAssembly 9
RidSpecificNativeLibrary 9
RunApp_GetDelegate 7
MostSpecificRidAssemblySelectedPerTypeMultipleAssets 6
AdditionalDepsDontAffectComponentDependencyResolution 1
ComponentWithCorruptedDepsJsonShouldFail 1
ComponentWithDependencies 1
ComponentWithDependenciesAndDependencyRemoved 1
ComponentWithDependenciesAndNoDeps 1
ComponentWithDependenciesAndNoDepsAndDependencyRemoved 1
ComponentWithNoDependencies 1
ComponentWithNoDependenciesAndNoDeps 1
ComponentWithResourcesShouldReportResourceSearchPaths 1
ComponentWithSameDependencyNativeImageShouldFail 1
ComponentWithSameDependencyWithDifferentExtensionShouldFail 1
InvalidMainComponentAssemblyPathFails 1
Microsoft.Extensions.Caching.Memory.Tests Work Item 1
MultiThreadedComponentDependencyResolutionWhichSucceeeds 1
MultiThreadedComponentDependencyResolutionWhithFailures 1
RunApp_UnhandledException 1
```

**Comment by safern** [comment]
This is investigated as part of: https://github.com/dotnet/runtime/issues/35755

**Comment by safern** [comment]
Different issues but related, so good to keep this one with blocking ci as the other test was disabled. Just wanted to link them together

**Comment by swaroop-sridhar** [comment]
I looked at the other failures that happen only with the singlefilehost change. 
This problem is completely different from  #35755 (nothing to do with interop).

The problem here is that some tests failed with segmentation fault when calling dladdr();

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fc6cfb in dladdr () from /lib/ld-musl-x86_64.so.1
```
Looking at 
       ```
Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.ApplicationExecution.RunApp<br clear="all" /><pre>
```


```
/home/runtime/artifacts/tests/Release/ha/nativeHosting/0/nativehost 
Arguments: run_app /home/runtime/artifacts/tests/Release/ha/sharedFrameworkPublish/host/fxr/5.0.0-dev/libhostfxr.so /home/runtime/artifacts/tests/Release/ha/0/PortableApp/bin/PortableApp.dll
Exit Code: 139

Breaking on dladdr() https://github.com/esmil/musl/blob/master/src/ldso/dynlink.c#L1502, we see 

Breakpoint 1, 0x00007ffff7fc6bf7 in dladdr () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7fc6bf7 in dladdr () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7da53ad in pal::get_own_module_path (recv=0x7fffffffe758) at /home/runtime/src/installer/corehost/cli/hostmisc/pal.unix.cpp:784
#2  0x00007ffff7dac470 in (anonymous namespace)::populate_startup_info (parameters=<optimized out>, startup_info=...) at /home/runtime/src/installer/corehost/cli/fxr/hostfxr.cpp:441
#3  0x00007ffff7dac127 in hostfxr_initialize_for_dotnet_command_line (argc=1, argv=0x7fffffffec30, parameters=0x0, host_context_handle=0x7fffffffe898) at /home/runtime/src/installer/corehost/cli/fxr/hostfxr.cpp:495
#4  0x0000555555559c3b in host_context_test::app(host_context_test::check_properties, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const**, std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&) ()
#5  0x0000555555560ae7 in main () 
```

So, the MUSL library is trying to resolve dladdr (pal::get_own_module_path).
From objdump --syms we see that pal::get_own_module_path is not an exported symbol – still not a reason to segfault.

I think one of the symbol-export changes in the PR doesn’t go well with Alpine. 
It could be useful to apply the changes selectively to determine the root cause that triggers this failure. @Vladimir Sadov can you please investigate it?  Thanks.
