### ISSUE TITLE
Exception thrown if IConfigurationProvider.GetReloadToken() returns null

### ISSUE THREAD

**Issue by oleneveu** [dotnet/runtime#35996]
### Description

The summary for `IConfigurationProvider.GetReloadToken()` states:
`Returns a change token if this provider supports change tracking, null otherwise.`
However, if an implementation actually returns 'null', an exception is thrown from `ConfigurationRoot` constructor.

### Steps to reproduce the behavior:
1. Write your own `IConfigurationProvider` implementation
2. Make sure that the `GetReloadToken()` method returns `null`
3. When calling the `IConfigurationBuilder.Build()` method, a `System.NullReferenceException` exception is thrown

### Additional context
Here is the stack trace from my code:
```
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at DeviceServerTransfer.Program.CreateWebHostBuilder(String[] args) in C:\Dev\DotNet\Server\DeviceServerTransfer\DeviceServerTransfer\Program.cs:line 34
   at DeviceServerTransfer.Program.Main(String[] args) in C:\Dev\DotNet\Server\DeviceServerTransfer\DeviceServerTransfer\Program.cs:line 29
```

**Comment by ericstj** [comment]
@maryamariyan this looks like a pretty straight forward bugfix.  Might be a nice one to knock off as a background task.

**Comment by maryamariyan** [comment]
Closing as dupe of https://github.com/dotnet/runtime/issues/36393
