### ISSUE TITLE
Building chained configuration throws InvalidOperationException

### ISSUE THREAD

**Issue by shaynevanasperen** [dotnet/runtime#36042]
### Describe the bug
Heavy parallelism of `ConfigurationProvider.OnReload()` combined with building new configuration utilising `ChainedConfigurationSource`, results in exceptions being thrown from `ChangeToken.OnChange` with message `Somebody else set the _disposable field`.

### To Reproduce
1. Using version '**3.1.2**' of package '**Microsoft.Extensions.Configuration**'
2. Run this code:

```cs
private class DummyConfigurationProvider : ConfigurationProvider
{
	public void TriggerReload() => OnReload();
}

[Fact]
public void ChainedConfigurationSupportsHeavyParallelism()
{
	var dummyProvider = new DummyConfigurationProvider();
	var providers = new IConfigurationProvider[] { dummyProvider };

	using var configuration = new ConfigurationRoot(providers);

	const int loopCount = 100000;
	var result = Parallel.For(1, loopCount + 1, x =>
	{
		dummyProvider.TriggerReload();
		// ReSharper disable once AccessToDisposedClosure
		new ConfigurationBuilder()
			.AddConfiguration(configuration)
			.AddInMemoryCollection(new Dictionary<string, string>
			{
				{ "foo", "bar" }
			})
			.Build();
	});
	result.IsCompleted.Should().BeTrue();
}
```

3. Run this test repeatedly in a test runner to see that it fails within a few seconds
4. See error:
```

System.AggregateException : One or more errors occurred. (Somebody else set the _disposable field)
---- System.InvalidOperationException : Somebody else set the _disposable field
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at JustEat.Extensions.Configuration.Tests.Layered.ConfigurationExtensionsTests.ChainedConfigurationSupportsHeavyParallelism() in C:\...\ConfigurationExtensionsTests.cs:line 130
----- Inner Stack Trace -----
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1.SetDisposable(IDisposable disposable)
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1.RegisterChangeTokenCallback(IChangeToken token)
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at JustEat.Extensions.Configuration.Tests.Layered.ConfigurationExtensionsTests.<>c__DisplayClass7_0.<ChainedConfigurationSupportsHeavyParallelism>b__0(Int32 x) in C:\...\ConfigurationExtensionsTests.cs:line 134
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()


```

### Expected behavior
No exceptions should be thrown.

### Additional context
Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Alamaster99** [comment]
Any updated on this issue? We are using version 5.0.0 of the Microsoft.Extensions.Configuration library and we have run into almost exactly same issue. InvalidOperationException: Somebody else set the _disposable field when using per tenant configuration.
