### ISSUE TITLE
System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected fails on Linux ARM64

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#36087]
```
System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(format: "tetie", values: [-1, 0, 1, 2, 3], expected: [10, 1, 0, 1, 1, ...]) [FAIL]
      Exception of type 'Xunit.Sdk.AssertActualExpectedException' was thrown.
      Expected: 10, 1, 0, 1, 1, 2, 10, 1, 3
      Actual:   255, 255, 255, 255, 1, 0, 1, 1, 2, 10, 1, 3
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(368,0): at System.AssertExtensions.Equal[T](T[] expected, T[] actual)
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(49,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(String format, Object[] values, Byte[] expected)
    System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(format: "{tetie}", values: [-1, 0, 1, 2, 3], expected: [48, 9, 10, 1, 0, ...]) [FAIL]
      Exception of type 'Xunit.Sdk.AssertActualExpectedException' was thrown.
      Expected: 48, 9, 10, 1, 0, 1, 1, 2, 10, 1, 3
      Actual:   48, 12, 255, 255, 255, 255, 1, 0, 1, 1, 2, 10, 1, 3
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(368,0): at System.AssertExtensions.Equal[T](T[] expected, T[] actual)
        /_/src/libraries/System.DirectoryServices.Protocols/tests/BerConverterTests.cs(49,0): at System.DirectoryServices.Protocols.Tests.BerConverterTests.Encode_Objects_ReturnsExpected(String format, Object[] values, Byte[] expected)
```

Failed on rolling build:
- Linux_arm64
- Alpine.38_arm64

https://dev.azure.com/dnceng/public/_build/results?buildId=635948&view=ms.vss-test-web.build-test-results-tab

This failed from a manual build I queued and these tests where just added in: 
https://github.com/dotnet/runtime/pull/35380

cc: @joperezr @dotnet/runtime-infrastructure

**Comment by joperezr** [comment]
I'll take care of this tomorrow.
