### ISSUE TITLE
Test failure: System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36207]
failed in job: [runtime-libraries outerloop 20200510.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=638660&view=ms.vss-test-web.build-test-results-tab&runId=19854516&resultId=104375&paneView=debug)

Error message
~~~
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
Expected: 6
Actual: 0) (The operation requested for service 'fecf19e2-5eec-47fc-a4a1-e6ae5c129a3c' has not been completed within the specified time interval.)
---- Assert.Equal() Failure
Expected: 6
Actual: 0
---- System.ServiceProcess.TimeoutException : The operation requested for service 'fecf19e2-5eec-47fc-a4a1-e6ae5c129a3c' has not been completed within the specified time interval.


Stack trace

----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 96
----- Inner Stack Trace #2 (System.ServiceProcess.TimeoutException) -----
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 903
   at System.ServiceProcess.Tests.TestServiceInstaller.StopService() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs:line 162
   at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs:line 133
   at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/TestServiceProvider.cs:line 146
   at System.ServiceProcess.Tests.ServiceBaseTests.Dispose() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 218
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200524.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=658368&view=ms.vss-test-web.build-test-results-tab&runId=20429704&resultId=104171&paneView=debug)

failed test: System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop


Error message
~~~
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
Expected: 6
Actual: 0) (The operation requested for service '8467ad82-4566-4e38-80f0-252079c3fe84' has not been completed within the specified time interval.)
---- Assert.Equal() Failure
Expected: 6
Actual: 0
---- System.ServiceProcess.TimeoutException : The operation requested for service '8467ad82-4566-4e38-80f0-252079c3fe84' has not been completed within the specified time interval.


Stack trace

----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 96
----- Inner Stack Trace #2 (System.ServiceProcess.TimeoutException) -----
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 903
   at System.ServiceProcess.Tests.TestServiceInstaller.StopService() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs:line 162
   at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs:line 133
   at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/TestServiceProvider.cs:line 146
   at System.ServiceProcess.Tests.ServiceBaseTests.Dispose() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 218
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
~~~

**Comment by ManickaP** [comment]
Hit in #37441

**Comment by ericstj** [comment]
Dup of https://github.com/dotnet/runtime/issues/38945
