### ISSUE TITLE
Certificate present on a mounted volume but the error Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file 

### ISSUE THREAD

**Issue by hakeemoriola** [dotnet/runtime#36333]
<img width="570" alt="Screenshot 2020-05-13 at 11 22 43" src="https://user-images.githubusercontent.com/9089648/81801441-59629300-950c-11ea-9ca1-586503e77893.png">
<img width="685" alt="Screenshot 2020-05-13 at 11 22 15" src="https://user-images.githubusercontent.com/9089648/81801446-5c5d8380-950c-11ea-9deb-ad8f8ce1c23e.png">
<img width="1440" alt="Screenshot 2020-05-13 at 11 20 36" src="https://user-images.githubusercontent.com/9089648/81801455-61223780-950c-11ea-8e30-37566ea56015.png">

I wrote a code to list the content of the mounted directory, I can see the file but when I try to load the certificate it still gave this
crit: Microsoft.AspNetCore.Server.Kestrel[0]
infusync.identity_1  |       Unable to start Kestrel.
infusync.identity_1  | Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
infusync.identity_1  |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
infusync.identity_1  |    at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
infusync.identity_1  |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
infusync.identity_1  |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
infusync.identity_1  |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
infusync.identity_1  |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert(ConfigurationReader configReader)
infusync.identity_1  |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
infusync.identity_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
infusync.identity_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
infusync.identity_1  | Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
infusync.identity_1  |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)

**Comment by hakeemoriola** [comment]
.Net core 3.1, Docker Container, docker-compose  
<img width="732" alt="Screenshot 2020-05-13 at 12 04 26" src="https://user-images.githubusercontent.com/9089648/81804964-f1af4680-9511-11ea-8bd5-542d903ebc12.png">
<img width="659" alt="Screenshot 2020-05-13 at 12 03 59" src="https://user-images.githubusercontent.com/9089648/81804977-f83dbe00-9511-11ea-936c-301c7d858c63.png">

**Comment by hakeemoriola** [comment]
I fixed the issue by 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
setting the Path to reflect the mounted volume path.
