### ISSUE TITLE
InvalidKeySize_DoesNotInvalidateKey failing in 3.1 release

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#36381]
stacktrace
```  
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000001)
at Internal.Cryptography.CngCommon.TrySignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, Span`1 signature, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32& bytesWritten) in /_/src/Common/src/Internal/Cryptography/CngCommon.SignVerify.cs:line 48
   at System.Security.Cryptography.RSACng.TrySignHash(ReadOnlySpan`1 hash, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten) in /_/src/Common/src/System/Security/Cryptography/RSACng.SignVerify.cs:line 126
   at System.Security.Cryptography.RSA.TrySignData(ReadOnlySpan`1 data, Span`1 destination, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding, Int32& bytesWritten) in /_/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs:line 202
   at System.Security.Cryptography.Rsa.Tests.SignVerify_Span.<>c__DisplayClass0_0.<SignData>b__0(Byte[] dest) in /_/src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.netcoreapp.cs:line 10
   at System.Security.Cryptography.Rsa.Tests.SignVerify_Span.TryWithOutputArray(Func`2 func) in /_/src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.netcoreapp.cs:line 26
   at System.Security.Cryptography.Rsa.Tests.SignVerify_Span.SignData(RSA rsa, Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.netcoreapp.cs:line 10
   at System.Security.Cryptography.Rsa.Tests.SignVerify.InvalidKeySize_DoesNotInvalidateKey() in /_/src/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.cs:line 112
```

Failure PR https://github.com/dotnet/corefx/pull/42920

cc @bartonjs

**Comment by bartonjs** [comment]
Closing as duplicate of #29683 (Windows reports STATUS_UNSUCCESSFUL on NCryptSignHash)
