### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_ResponseStreamTest.GetAsync_UseResponseHeadersReadAndCallLoadIntoBuffer_Success

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36433]
failed in job: [runtime-libraries outerloop 20200513.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=642743&view=ms.vss-test-web.build-test-results-tab&runId=19960502&resultId=102453&paneView=debug)

Error message
~~~
Assert.Equal() Failure
Expected: Byte[] [98, 40, 160, 45, 17, ...]
Actual: Byte[] [212, 29, 140, 217, 143, ...]


Stack trace
   at System.Net.Http.Functional.Tests.TestHelper.VerifyResponseBody(String responseContent, Byte[] expectedMD5Hash, Boolean chunkedUpload, String requestBody) in /_/src/libraries/Common/tests/System/Net/Http/TestHelper.cs:line 65
   at System.Net.Http.Functional.Tests.ResponseStreamTest.GetAsync_UseResponseHeadersReadAndCallLoadIntoBuffer_Success(RemoteServer remoteServer) in /_/src/libraries/Common/tests/System/Net/Http/ResponseStreamTest.cs:line 140
--- End of stack trace from previous location ---
~~~

**Comment by karelz** [comment]
No failures during 2/23-5/10 (incl. PRs). Closing.
