### ISSUE TITLE
Test failed: System.Diagnostics.StackTrace.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#36585]
I'm trying to enable libraries testing using checked coreclr and JIT stress modes. This test fails when disabling TieredCompilation (meaning we're actually optimizing)

```
C:\h\w\B04C09BA\w\ADCA097A\e>set COMPlus_TieredCompilation=0 

C:\h\w\B04C09BA\w\ADCA097A\e>set COMPlus 
COMPlus_TieredCompilation=0

C:\h\w\B04C09BA\w\ADCA097A\e>call RunTests.cmd --runtime-path C:\h\w\B04C09BA\p 
----- start Fri 05/15/2020  6:21:40.95 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B04C09BA\w\ADCA097A\e\
"C:\h\w\B04C09BA\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.StackTrace.Tests.runtimeconfig.json --depsfile System.Diagnostics.StackTrace.Tests.deps.json xunit.console.dll System.Diagnostics.StackTrace.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\B04C09BA\w\ADCA097A\e>"C:\h\w\B04C09BA\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.StackTrace.Tests.runtimeconfig.json --depsfile System.Diagnostics.StackTrace.Tests.deps.json xunit.console.dll System.Diagnostics.StackTrace.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.StackTrace.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.StackTrace.Tests (found 51 test cases)
  Starting:    System.Diagnostics.StackTrace.Tests (parallel test collections = on, max threads = 2)
    System.Diagnostics.Tests.StackTraceTests.ToString_Invoke_ReturnsExpected(stackTrace:    at System.Diagnostics.Tests.StackTraceTests.ToString_TestData()+MoveNext()\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()\r\n   at Xunit.Sdk.TestCaseRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestCaseRunner`1.RunAsync()\r\n   at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)\r\n   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()\r\n   at Xunit.Sdk.TestMethodRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestMethodRunner`1.RunAsync()\r\n   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()\r\n   at Xunit.Sdk.TestClassRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestClassRunner`1.RunAsync()\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunAsync()\r\n   at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   at System.Threading.Tasks.Task.ExecuteEntry()\r\n   at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s)\r\n   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()\r\n   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)\r\n   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)\r\n   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart(Object obj)\r\n, expectedToString: "System.Diagnostics.Tests.StackTraceTests.ClassWith"...) [FAIL]
      Assert.Contains() Failure
      Not found: System.Diagnostics.Tests.StackTraceTests.ClassWithConstructor..ctor()
      In value:     at System.Diagnostics.Tests.StackTraceTests.ToString_TestData()+MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()
         at Xunit.Sdk.TestCaseRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestCaseRunner`1.RunAsync()
         at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)
         at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
         at Xunit.Sdk.TestMethodRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestMethodRunner`1.RunAsync()
         at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
         at Xunit.Sdk.TestClassRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestClassRunner`1.RunAsync()
         at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
         at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
         at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         at System.Threading.Tasks.Task.ExecuteEntry()
         at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s)
         at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
         at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
         at System.Threading.Tasks.Task.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
         at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
         at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.ThreadHelper.ThreadStart(Object obj)
      
      Stack Trace:
        /_/src/libraries/System.Diagnostics.StackTrace/tests/StackTraceTests.cs(288,0): at System.Diagnostics.Tests.StackTraceTests.ToString_Invoke_ReturnsExpected(StackTrace stackTrace, String expectedToString)
    System.Diagnostics.Tests.StackTraceTests.ToString_Invoke_ReturnsExpected(stackTrace:    at System.Diagnostics.Tests.StackTraceTests.ToString_TestData()+MoveNext()\r\n   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()\r\n   at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()\r\n   at Xunit.Sdk.TestCaseRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestCaseRunner`1.RunAsync()\r\n   at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)\r\n   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()\r\n   at Xunit.Sdk.TestMethodRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestMethodRunner`1.RunAsync()\r\n   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()\r\n   at Xunit.Sdk.TestClassRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestClassRunner`1.RunAsync()\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunAsync()\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Xunit.Sdk.TestCollectionRunner`1.RunAsync()\r\n   at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2()\r\n   at System.Threading.Tasks.Task`1.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   at System.Threading.Tasks.Task.ExecuteEntry()\r\n   at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s)\r\n   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()\r\n   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)\r\n   at System.Threading.Tasks.Task.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)\r\n   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)\r\n   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.ThreadHelper.ThreadStart(Object obj)\r\n, expectedToString: "System.Diagnostics.Tests.StackTraceTests.InvokeIgn"...) [FAIL]
      Assert.Contains() Failure
      Not found: System.Diagnostics.Tests.StackTraceTests.InvokeIgnoredMethod()
      In value:     at System.Diagnostics.Tests.StackTraceTests.ToString_TestData()+MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync()
         at Xunit.Sdk.TestCaseRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestCaseRunner`1.RunAsync()
         at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)
         at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
         at Xunit.Sdk.TestMethodRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestMethodRunner`1.RunAsync()
         at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
         at Xunit.Sdk.TestClassRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestClassRunner`1.RunAsync()
         at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
         at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
         at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClass14_2.<RunTestCollectionsAsync>b__2()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         at System.Threading.Tasks.Task.ExecuteEntry()
         at System.Threading.Tasks.SynchronizationContextTaskScheduler.<>c.<.cctor>b__8_0(Object s)
         at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
         at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
         at System.Threading.Tasks.Task.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__276_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
         at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
         at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.ThreadHelper.ThreadStart(Object obj)
      
      Stack Trace:
        /_/src/libraries/System.Diagnostics.StackTrace/tests/StackTraceTests.cs(288,0): at System.Diagnostics.Tests.StackTraceTests.ToString_Invoke_ReturnsExpected(StackTrace stackTrace, String expectedToString)
  Finished:    System.Diagnostics.StackTrace.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.StackTrace.Tests  Total: 119, Errors: 0, Failed: 2, Skipped: 0, Time: 5.242s
----- end Fri 05/15/2020  6:21:53.91 ----- exit code 1 ----------------------------------------------------------
```

Is this a case where the test is expecting a certain set of inlining (or no inlining) that is invalid?

@stephentoub ?

**Comment by danmosemsft** [comment]
It's marked no inlining:
```c#
        private class ClassWithConstructor
        {
            public StackFrame StackFrame { get; }

            [MethodImpl(MethodImplOptions.NoInlining)]
            public ClassWithConstructor() => StackFrame = new StackFrame();
        }
```

**Comment by stephentoub** [comment]
That one is, but I don't think that's the right one. This one is missing it:
https://github.com/dotnet/runtime/blob/61733e21bbe965977827205639bf4b835b522494/src/libraries/System.Diagnostics.StackTrace/tests/StackTraceTests.cs#L338

**Comment by stephentoub** [comment]
This raises an interesting question. In release builds, are most of our tests (the tests themselves) running unoptimized because they're generally only executed once and thus they won't be promoted from tier 0?

**Comment by BruceForstall** [comment]
@stephentoub That's my belief, which is worrisome (I've expressed this worry before; don't remember to whom). cc @AndyAyersMS 

I'm planning to add back JIT stress mode testing over libraries (including simply no-tiering mode) with https://github.com/dotnet/runtime/pull/36486, but it's worth considering whether a more regular mode, e.g., libraries PR or CI, should do this as well.
