### ISSUE TITLE
CompareInfoIndexOfTests.IndexOf_String fails on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36625]
This test fails on every arch with:

```
Assert.Equal() Failure
Expected: 7
Actual:   1
```

StackTrace:

```
at System.Globalization.Tests.CompareInfoIndexOfTests.IndexOf_String(CompareInfo compareInfo, String source, String value, Int32 startIndex, Int32 count, CompareOptions options, Int32 expected) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.IndexOf.cs:line 185
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/steve/dev/net5/droid-runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359
```

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/36631
https://github.com/dotnet/runtime/issues/36630
https://github.com/dotnet/runtime/issues/36629
https://github.com/dotnet/runtime/issues/36628
https://github.com/dotnet/runtime/issues/36627
https://github.com/dotnet/runtime/issues/36626
https://github.com/dotnet/runtime/issues/36624

**Comment by safern** [comment]
Closing in favor of: https://github.com/dotnet/runtime/issues/36672
