### ISSUE TITLE
TextInfoMiscTests.TestToLower fails on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36629]
This test fails on android with:

```
Assert.Equal() Failure         
                  ↓ (pos 1)
Expected: hı\\n\\0hi\\t!\n
Actual:   hi\\n\\0hi\\t!\n           
              ↑ (pos 1)
```

StackTrace:
```
at System.Globalization.Tests.TextInfoMiscTests.TestToLower(String name, String str, String expected) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:line 250
   at System.Globalization.Tests.TextInfoMiscTests.ToLower(String name, String str, String expected) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:line 261
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/steve/dev/net5/droid-runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359
```

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/36631
https://github.com/dotnet/runtime/issues/36630
https://github.com/dotnet/runtime/issues/36628
https://github.com/dotnet/runtime/issues/36627
https://github.com/dotnet/runtime/issues/36626
https://github.com/dotnet/runtime/issues/36625
https://github.com/dotnet/runtime/issues/36624

**Comment by safern** [comment]
Closing in favor of: https://github.com/dotnet/runtime/issues/36672
