### ISSUE TITLE
CompareInfoTests.SortKeyTest fails on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36624]
The test fails for every arch with:

```
Assert.Equal() Failure
Expected: 0
Actual:   -1
```

StackTrace:

```
at System.Globalization.Tests.CompareInfoTests.SortKeyTest(CompareInfo compareInfo, String string1, String string2, CompareOptions options, Int32 expectedSign) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.cs:line 370
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/steve/dev/net5/droid-runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359
```

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/36631
https://github.com/dotnet/runtime/issues/36630
https://github.com/dotnet/runtime/issues/36629
https://github.com/dotnet/runtime/issues/36628
https://github.com/dotnet/runtime/issues/36627
https://github.com/dotnet/runtime/issues/36626
https://github.com/dotnet/runtime/issues/36625

**Comment by safern** [comment]
Closing in favor of: https://github.com/dotnet/runtime/issues/36672
