### ISSUE TITLE
TextInfoMiscTests.ToUpper fails on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36630]
This test fails on every arch with:

```
Assert.Equal() Failure                 
↓ (pos 5)
Expected: HI\\n\\0Hİ\\t!
Actual:   HI\\n\\0HI\\t!\n                 
↑ (pos 5)
```

StackTrace:
```
at System.Globalization.Tests.TextInfoMiscTests.TestToUpper(String name, String str, String expected) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:line 373
   at System.Globalization.Tests.TextInfoMiscTests.ToUpper(String name, String str, String expected) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs:line 384
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/steve/dev/net5/droid-runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359
```

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/36631
https://github.com/dotnet/runtime/issues/36629
https://github.com/dotnet/runtime/issues/36628
https://github.com/dotnet/runtime/issues/36627
https://github.com/dotnet/runtime/issues/36626
https://github.com/dotnet/runtime/issues/36625
https://github.com/dotnet/runtime/issues/36624

**Comment by safern** [comment]
Closing in favor of: https://github.com/dotnet/runtime/issues/36672
