### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36639]
failed in job: [runtime-libraries outerloop 20200517.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=648895&view=ms.vss-test-web.build-test-results-tab&runId=20137590&resultId=104243&paneView=debug)

Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 42
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 549
--- End of stack trace from previous location ---
~~~

**Comment by alnikola** [comment]
Duplicate #36689
