### ISSUE TITLE
[mono] Linker fails to process System.Runtime.Tests

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#36691]
```
./dotnet.sh build -c Release src/libraries/System.Runtime/tests \
/p:TargetArchitecture=arm64 /p:TargetOS=Android 
```
Fails with:
```
Microsoft (R) Build Engine version 16.7.0-preview-20229-03+2cee6d020 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  TestUtilities.Unicode -> /Users/egorbo/prj/runtime/artifacts/bin/TestUtilities.Unicode/net5.0-Release/TestUtilities.Unicode.dll
  TestUtilities -> /Users/egorbo/prj/runtime/artifacts/bin/TestUtilities/net5.0-Release/TestUtilities.dll
  TestLoadAssembly -> /Users/egorbo/prj/runtime/artifacts/bin/TestLoadAssembly/netstandard2.0-Release/TestLoadAssembly.dll
  System.Reflection.TestModule -> /Users/egorbo/prj/runtime/artifacts/bin/System.Reflection.TestModule/netstandard2.0-Release/System.Reflection.TestModule.dll
  TestCollectibleAssembly -> /Users/egorbo/prj/runtime/artifacts/bin/TestCollectibleAssembly/netstandard2.0-Release/TestCollectibleAssembly.dll
  System.TestStructs -> /Users/egorbo/prj/runtime/artifacts/bin/System.TestStructs/netstandard2.0-Release/System.TestStructs.dll
  System.Runtime.Tests -> /Users/egorbo/prj/runtime/artifacts/bin/System.Runtime.Tests/net5.0-Unix-Release/android-arm64/System.Runtime.Tests.dll
  Fatal error in IL Linker
  Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
     at Mono.Cecil.TypeSpecification.set_Scope(IMetadataScope value)
     at Mono.Linker.Steps.SweepStep.UpdateTypeScope(TypeReference type, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttributeArgument attributeArgument, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttributeArgument attributeArgument, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttributeArgument attributeArgument, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttribute attribute)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(ICustomAttributeProvider customAttributeProvider)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes[T](Collection`1 providers)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(TypeDefinition typeDefinition)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.ProcessAssemblyAction(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```
Other libraries (tried a few) work

In order to enable linker I added `<PublishTrimmed>true` here: https://github.com/dotnet/runtime/blob/master/eng/testing/tests.props#L30

**Comment by EgorBo** [comment]
cc @marek-safar

**Comment by stephentoub** [comment]
Should this issue be moved to mono/linker?

**Comment by marek-safar** [comment]
yes, it could

**Comment by EgorBo** [comment]
Moved to https://github.com/mono/linker/issues/1205
