### ISSUE TITLE
[dev/arcade-migration] Fix flaky ResolvePackageAssets error

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#3677]
https://dev.azure.com/dnceng/internal/_build/results?buildId=255796&view=logs

```
##[error].dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 514
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 454
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 295
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 287
   at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 35
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Binlog task tree:

```
ResolvePackageAssets
    Assembly = /Users/vsts/agent/2.153.2/work/1/s/.dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/../tools/netcoreapp2.0/Microsoft.NET.Build.Tasks.dll
    Parameters
        ProjectAssetsFile = /Users/vsts/agent/2.153.2/work/1/s/artifacts/obj/netcoreapp/project.assets.json
        ProjectAssetsCacheFile = /Users/vsts/agent/2.153.2/work/1/s/artifacts/obj/netcoreapp/Release/netcoreapp3.0/osx-x64/netcoreapp.assets.cache
        ProjectPath = /Users/vsts/agent/2.153.2/work/1/s/src/pkg/projects/netcoreapp/src/netcoreapp.depproj
        ProjectLanguage = unused
        EmitAssetsLogMessages = True
        TargetFrameworkMoniker = .NETCoreApp,Version=v3.0
        RuntimeIdentifier = osx-x64
        MarkPackageReferencesAsExternallyResolved = True
        DotNetAppHostExecutableNameWithoutExtension = apphost
    Errors
        /Users/vsts/agent/2.153.2/work/1/s/.dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 514
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 454
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 295
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs:line 287
   at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 35
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/vsts/agent/2.153.2/work/1/s/src/pkg/projects/netcoreapp/src/netcoreapp.depproj]
```

I'd guess this is somehow because it's being called multiple times in parallel, trying to use the same cache file. These projects reference the same cache file (unfortunately no timestamps I can find):

```
Project Name=Project "netcoreapp.depproj" (Build;Test target(s))
```

```
Project Name=Project "Microsoft.NETCore.App.Runtime.pkgproj" (Build;Test target(s))
  Project Name=Project "Microsoft.NETCore.App.Runtime.pkgproj" (InnerBuildRidSpecificPackage target(s))
    Project Name=Project "netcoreapp.depproj" (GetFilesToPackage target(s))
```

```
Project Name=Project "Microsoft.NETCore.App.pkgproj" (Build;Test target(s))
  Project Name=Project "Microsoft.NETCore.App.pkgproj" (InnerBuildRidSpecificPackage target(s))
    Project Name=Project "netcoreapp.depproj" (GetFilesToPackage target(s))
```

Maybe it would be enough to fix up the global properties to make the `GetFilesToPackage` ones only build once? The Runtime package project has BaseId and IdPrefix set globally, which shouldn't be necessary there.

**Comment by dagood** [comment]
Closing. Things have changed since this issue: the Installer (Core-Setup) part works better with up-front restore, relying on the ordinary `RuntimeIdentifiers` flow rather than running once per RID. (We still do run the same project more than once to pack up a few RID-specific packages, but it's more contained to that specific operation.)
