### ISSUE TITLE
Process ProTotalProcessorTime throws InvalidOperationException exception on macOS

### ISSUE THREAD

**Issue by DmitryKhryukin** [dotnet/runtime#36777]
### Description

I'm trying to get information about current running processes. And I'm getting InvalidOperationException exception accessing TotalProcessorTime Process property. 
Please see the configuration and the error message below. 

Here is my example code (I've created a test console app [here](https://github.com/DmitryKhryukin/TotalProcessorTimeOsxProblem))

```
        static void Main(string[] args)
        {
            var processes = Process.GetProcesses();

            try
            {
                var timeInformationToBeUsed = processes.Select(x => x.TotalProcessorTime).ToList();
            }
            catch (InvalidOperationException e)
            {
                Console.WriteLine($"Message: {e.Message}");
                Console.WriteLine($"StackTrace: {e.StackTrace}");
            }

            Console.ReadKey();
        }
```

### Configuration

SDK: 3.1.101
Framework: .NETCoreApp v3.1 (I've tried v2.1 too - the same result)
OS: macOS Catalina Version 10.15.4

Not sure if it's possible to reproduce it on other configurations.

### Regression?

I've tried .NETCoreApp v2.1 too - the same result

### Other information

> Message: Failed to set or retrieve rusage information. See the error code for OS-specific error information.

> StackTrace:   
> at Interop.libproc.proc_pid_rusage(Int32 pid)
> at System.Diagnostics.Process.get_TotalProcessorTime()
> at TotalProcessorTimeOsxProblem.Program.<>c.<Main>b__0_0(Process x) in /Projects/TotalProcessorTimeOsxProblem/TotalProcessorTimeOsxProblem/Program.cs:line 15
> at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
> at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
> at TotalProcessorTimeOsxProblem.Program.Main(String[] args) in /Projects/TotalProcessorTimeOsxProblem/TotalProcessorTimeOsxProblem/Program.cs:line 15

So the exception is happening in [Process.OSX.cs ](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs)

```
        public TimeSpan TotalProcessorTime
        {
            get
            {
                EnsureState(State.HaveNonExitedId);
                Interop.libproc.rusage_info_v3 info = Interop.libproc.proc_pid_rusage(_processId);
                return new TimeSpan(Convert.ToInt64((info.ri_system_time + info.ri_user_time) / NanosecondsTo100NanosecondsFactor));
            }
        }
```

**Comment by DmitryKhryukin** [comment]
same problem with UserProcessorTime and PrivilegedProcessorTime

`Interop.libproc.rusage_info_v3 info = Interop.libproc.proc_pid_rusage(_processId);`

**Comment by danmosemsft** [comment]
I don't know the cause of your problem, but I think we'd welcome a PR to include the error code in the exception at least - the message suggests to look at it but doesn't include it!
```c#
            // Get the PIDs rusage info
            int result = proc_pid_rusage(pid, RUSAGE_INFO_V3, &info);
            if (result < 0)
            {
                throw new InvalidOperationException(SR.RUsageFailure);
            }

            return info;
```

**Comment by danmosemsft** [comment]
Ideally it could append the actual message from the system corresponding to the code. That might be done with `Interop.Sys.StrError(result)`

**Comment by DmitryKhryukin** [comment]
on Windows it throws another exception: 
System.ComponentModel.Win32Exception

```
Message: Access is denied.
StackTrace:    at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessTimes()
   at System.Diagnostics.Process.get_TotalProcessorTime()
   at TotalProcessorTimeOsxProblem.Program.<>c.<Main>b__0_0(Process x) in C:\Users\xxx\Documents\TotalProcessorTimeOsxProblem-master\TotalProcessorTimeOsxProblem-master\TotalProcessorTimeOsxProblem\Program.cs:line 15
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at TotalProcessorTimeOsxProblem.Program.Main(String[] args) in C:\Users\xxx\Documents\TotalProcessorTimeOsxProblem-master\TotalProcessorTimeOsxProblem-master\TotalProcessorTimeOsxProblem\Program.cs:line 15
```

so looks like it might be some system processes which are not accessible

**Comment by danmosemsft** [comment]
likely a different cause : need that Mac error code

**Comment by DmitryKhryukin** [comment]
I've updated my [test project ](https://github.com/DmitryKhryukin/TotalProcessorTimeOsxProblem/blob/master/TotalProcessorTimeOsxProblem/Program.cs)a bit to get more info about the processes which I can't get an access to. 

All of them have empty ProcessName. So I guess it might mean all of them are some system processes.

**Comment by danmosemsft** [comment]
@DmitryKhryukin any interest in offering a PR to add such code?

**Comment by DmitryKhryukin** [comment]
@danmosemsft yep, I'll have a look soon. cheers

**Comment by adamsitnik** [comment]
@DmitryKhryukin have you made any progress on this? please let me know if you need some help

**Comment by 2BitSalute** [comment]
> I've updated my [test project ](https://github.com/DmitryKhryukin/TotalProcessorTimeOsxProblem/blob/master/TotalProcessorTimeOsxProblem/Program.cs)a bit to get more info about the processes which I can't get an access to.
> 
> All of them have empty ProcessName. So I guess it might mean all of them are some system processes.

That is what I see, also.

My own project started off as this SignalR ASP.NET Core tutorial, by the way:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?WT.mc_id=dotnet-35129-website&view=aspnetcore-6.0&tabs=visual-studio-code
