### ISSUE TITLE
ASN1 corrupted data or ASN1_ITEM_EX_D2I:nested asn1 error

### ISSUE THREAD

**Issue by kartheekp-ms** [dotnet/runtime#36786]
## Description

In [NuGet.Client](https://github.com/NuGet/NuGet.Client/tree/dev-feature-xplatVerification), repo we have noticed that same Linux test has failed with different exceptions in 2 CI builds. We need your help to understand the expected behavior going forward in `.NET 5` so that we can handle accordingly.

`SDK Version: 5.0.100-preview.6.20270.13` has raised following exception

```shell
---- System.Security.Cryptography.CryptographicException : ASN1 corrupted data.
Stack trace
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName)
   at NuGet.Commands.CertificateProvider.LoadCertificateFromFileAsync(CertificateSourceOptions options) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs:line 141
   at NuGet.Commands.CertificateProvider.GetCertificatesAsync(CertificateSourceOptions options) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs:line 53
   at NuGet.Commands.SignCommandRunner.GetCertificateAsync(SignArgs signArgs) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/SignCommandRunner.cs:line 169
   at NuGet.Commands.SignCommandRunner.ExecuteCommandAsync(SignArgs signArgs) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/SignCommandRunner.cs:line 28
```
`SDK Version: 5.0.100-preview.6.20270.7` has raised following exception

```shell
typeof(Interop+Crypto+OpenSslCryptographicException): error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error

---- Interop+Crypto+OpenSslCryptographicException : error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error

Stack trace
   at Internal.Cryptography.Pal.CertificatePal.FromBio(SafeBioHandle bio, SafePasswordHandle password)
   at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at NuGet.Commands.CertificateProvider.LoadCertificateFromFileAsync(CertificateSourceOptions options) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs:line 141
   at NuGet.Commands.CertificateProvider.GetCertificatesAsync(CertificateSourceOptions options) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs:line 53
   at NuGet.Commands.SignCommandRunner.GetCertificateAsync(SignArgs signArgs) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/SignCommandRunner.cs:line 169
   at NuGet.Commands.SignCommandRunner.ExecuteCommandAsync(SignArgs signArgs) in /home/vsts/work/1/s/src/NuGet.Core/NuGet.Commands/SignCommand/SignCommandRunner.cs:line 28
```

**Comment by bartonjs** [comment]
Both of those exceptions are `CryptographicException`s, which is all the API guarantees. You should not depend on the specific message or specific subclass of the exception.

**Comment by kartheekp-ms** [comment]
@bartonjs - thanks for the update. I agree, but as per current implementation [NU3001](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3001) error has 3 scenarios `(invalid password, file not found,  and invalid certificate)` and we use `exception.HRResult` to decide which scenario to specify in the error message https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs#L59-L89

please let me know if the below information is helpful to see if there is any remote possibility of a bug in the sdk.

I have tried 3 builds where tests are executed on `SDK Version: 5.0.100-preview.6.20270.13` and here are the results

- code matching with `dev-feature-xplatVerification origin branch` where  `error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error`  is caught then test case **failed** with `ASN1 corrupted data` error. 
- modified code to catch `ASN1 corrupted data` error then test case **failed** with `error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error` 
- modified code catch both `ASN1 corrupted data` error and `error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1` error. test case **passed**

I see a difference in call stack when these errors are thrown.
- When `ASN1 corrupted data` error is thrown the top frame in the call stack is `at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)`
- When `error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1` error is thrown the top frame in the call stack is `Internal.Cryptography.Pal.CertificatePal.FromBio(SafeBioHandle bio, SafePasswordHandle password)`

**Comment by bartonjs** [comment]
We don't guarantee the HResult values of most of our exceptions, depending on them is going to be fragile.

> please let me know if the below information is helpful to see if there is any remote possibility of a bug in the sdk.

`Internal.Cryptography.Pal.CertificatePal.FromBio(SafeBioHandle bio, SafePasswordHandle password)` was removed in https://github.com/dotnet/runtime/commit/af6ab5f364871cb3f5d301d5f9c6b786bccb8a89#diff-ee6b858d55abf269c2efdb147cd62f15L81. (Which was done before any .NET 5 previews, so it's odd that you're seeing it in any .NET 5 previews... it suggests that somehow your tests are falling back to 3.1 when you expect they're on 5).  So you're just seeing an aspect of us guaranteeing the type of the exception, but not the HResult or the Message.

**Comment by kartheekp-ms** [comment]
@bartonjs - Thanks again. We have created a tracking issue (linked above) to fix maintainability issue due to dependency on `Exception.HRResult` property.
