### ISSUE TITLE
Need better error message when it fails to create a Mutex due to no-write permission to the '/tmp' folder on macOS or Linux

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#36823]
We consistently get issue reports in [PSReadLine](https://github.com/PowerShell/PSReadLine) about an `IOException` when creating a Mutex object on macOS:

```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_1525368525'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
I worked with a user on that issue and it turned out it was because the `/tmp` folder (mapped to `/private/tmp`) on the user's mac shows 755 for the permissions, namely no write permission for a non-root user. The user thought the permission change could be caused by `Homebrew`, and Mutex creation works fine after changing the permission to 777, see https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511

The error message is not helpful to get to the root of the problem. Given it's a permission issue, it could be great if the error message could indicate the permission issue.

**Comment by kouvel** [comment]
Consolidating into https://github.com/dotnet/runtime/issues/89090
