### ISSUE TITLE
System.IO.IsolatedStorage.HelperTests.GetDataDirectory fails on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#36836]
This is the only one in the suite that fails with:

```
System.IO.IOException : Read-only file system
at System.IO.FileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at System.Environment.GetFolderPathCore(SpecialFolder folder, SpecialFolderOption option) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs:line 51
   at System.Environment.GetFolderPath(SpecialFolder folder, SpecialFolderOption option) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.Private.CoreLib/src/System/Environment.cs:line 118
   at System.IO.IsolatedStorage.Helper.GetDataDirectory(IsolatedStorageScope scope) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs:line 26
   at System.IO.IsolatedStorage.Tests.HelperTests.GetDataDirectory(IsolatedStorageScope scope) in /Users/steve/dev/net5/droid-runtime/src/libraries/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/HelperTests.cs:line 48
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/steve/dev/net5/droid-runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]
```

**Comment by adamsitnik** [comment]
@steveisok @marek-safar should we move it to 7.0?

**Comment by mkhamoyan** [comment]
Tried on Android x64, x86 and arm64 for all of them test passed. I guess we can close it @steveisok ?
