### ISSUE TITLE
System.Net.NetworkInformation.Functional.Tests fail on iOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36890]
### System.Net.NetworkInformation.Functional.Tests

System.Net.NetworkInformation.Functional.Tests.dll   Failed: 6
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1)
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: ::1)
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: 127.0.0.1)
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: ::1)
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetIsNetworkAvailable_Success

```
System.Net.NetworkInformation.Functional.Tests.dll   Failed: 6

Test collection for System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1)
    Assert.True() Failure\nExpected: True\nActual:   False
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: ::1)
    Assert.True() Failure\nExpected: True\nActual:   False
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors
    System.Net.NetworkInformation.NetworkInformationException : An error was encountered while querying information from the operating system.
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: 127.0.0.1)
    Assert.True() Failure\nExpected: True\nActual:   False
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: ::1)
    Assert.True() Failure\nExpected: True\nActual:   False

Test collection for System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetIsNetworkAvailable_Success
    Assert.True() Failure\nExpected: True\nActual:   False

**Comment by wfurt** [comment]
At least some seems to be build problem.

```
      <test name="System.Net.Http.Json.Functional.Tests.HttpContentJsonExtensionsTests.TestValidMediaTypes(mediaType: \&quot;application/json\&quot;)" type="System.Net.Http.Json.Functional.Tests.HttpContentJsonExtensionsTests" method="TestValidMediaTypes" time="0.0555735" result="Fail">
        <failure exception-type="System.DllNotFoundException">
          <message><![CDATA[System.DllNotFoundException : System.Security.Cryptography.Native.OpenSsl assembly:<unknown assembly> type:<unknown type> member:(null)]]></message>
          <stack-trace><![CDATA[   at System.PlatformDetection.GetOpenSslVersion() in /Users/mdhwang/runtime/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Unix.cs:line 118
   at System.PlatformDetection.get_OpenSslVersion() in /Users/mdhwang/runtime/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Unix.cs:line 53
   at System.PlatformDetection.get_SupportsAlpn() in /Users/mdhwang/runtime/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs:line 112
   at System.Net.Test.Common.GenericLoopbackOptions..ctor() in /Users/mdhwang/runtime/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 87
   at System.Net.Test.Common.LoopbackServer.Options..ctor() in /Users/mdhwang/runtime/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 393
   at System.Net.Test.Common.LoopbackServer..ctor(Options options) in /Users/mdhwang/runtime/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 25
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/mdhwang/runtime/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 65
   at System.Net.Http.Json.Functional.Tests.HttpContentJsonExtensionsTests.TestValidMediaTypes(String mediaType) in /Users/mdhwang/runtime/src/libraries/System.Net.Http.Json/tests/FunctionalTests/HttpContentJsonExtensionsTests.cs:line 241
--- End of stack trace from previous location ---]]></stack-trace>
        </failure>
      </test>
```

Do you know what OS iOS claims to be @mdh1418 ? We should perhaps update the OS detection helpers.

**Comment by wfurt** [comment]
```      <test name="System.Net.NetworkInformation.Tests.StatisticsParsingTests.Udpv6GlobalStatisticsParsing" type="System.Net.NetworkInformation.Tests.StatisticsParsingTests" method="Udpv6GlobalStatisticsParsing" time="0.0119938" result="Fail">
        <failure exception-type="System.IO.DirectoryNotFoundException">
          <message><![CDATA[System.IO.DirectoryNotFoundException : Could not find a part of the path '/Users/mdhwang/Library/Developer/CoreSimulator/Devices/AB8A2904-AD12-4CCD-9072-445DC2401264/data/Containers/Bundle/Application/52E908FC-77EF-4EBB-8B73-EC927C0172CC/System.Net.NetworkInformation.Functional.Tests.app/NetworkFiles/snmp6'.]]></message>
          <stack-trace><![CDATA[   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) in /Users/mdhwang/runtime/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 23
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter) in /Users/mdhwang/runtime/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 30
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) in /Users/mdhwang/runtime/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs:line 56
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options) in /Users/mdhwang/runtime/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs:line 61
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in /Users/mdhwang/runtime/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs:line 241
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) in /Users/mdhwang/runtime/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs:line 216
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) in /Users/mdhwang/runtime/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs:line 201
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks) in /Users/mdhwang/runtime/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs:line 196
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.Tests.FileUtil.NormalizeLineEndings(String source, String normalizedDest) in /Users/mdhwang/runtime/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/FileUtil.cs:line 17
   at System.Net.NetworkInformation.Tests.StatisticsParsingTests.Udpv6GlobalStatisticsParsing() in /Users/mdhwang/runtime/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/StatisticsParsingTests.cs:line 129
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
```

This suggest that either we did not copy the supporting file to the device or GetTestFilePath() from TestUtilities returns wrong location. I don't know if there is some good way to triage it @mandel-macaque  but that does not look like networking issue.

**Comment by wfurt** [comment]
All the failing mail tests are unicode. Most likely related to https://github.com/dotnet/runtime/issues/33654 and https://github.com/dotnet/runtime/issues/33652.

**Comment by mdh1418** [comment]
Updated based on 98ac23212e6

**Comment by filipnavara** [comment]
The header file `netinet/ip_var.h` is missing in iOS SDK. This in turn causes `HAVE_NETINET_IP_VAR_H` not to be defined and the `SystemNative_GetIPv4GlobalStatistics` method becomes no-op. I believe the functionality exists on iOS and that someone already filed a bug report about the missing header files.
