### ISSUE TITLE
System.Text tests fail on iOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36900]
### System.Text.RegularExpressions.Tests
- [ ] System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 2)
- [ ] System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 256)
- [ ] System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: None)
- [ ] System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: IgnoreCase | Compiled | CultureInvariant)
- [ ] System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: Compiled)
- [ ] System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: IgnoreCase | CultureInvariant)
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;en-US\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;az-Latn-AZ\&quot;, pattern: \&quot;ı\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;tr-TR\&quot;, pattern: \&quot;ı\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: null, pattern: \&quot;[B-D\\\\u0130]+\&quot;, input: \&quot;aAeEĩıh BCDbcDİip\&quot;, options: IgnoreCase, expectedGroups: [\&quot;BCDbcDİi\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: null, pattern: \&quot;[\\\\u013B\\\\u013D\\\\u013F]+\&quot;, input: \&quot;ĺĻĽĿļľŀŁ\&quot;, options: IgnoreCase, expectedGroups: [\&quot;ĻĽĿļľŀ\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;tr-TR\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;i\&quot;, options: IgnoreCase, expectedGroups: [\&quot;i\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: null, pattern: \&quot;[\\\\u0100\\\\u0102\\\\u0104]+\&quot;, input: \&quot;ÿ ĀĂĄāăąĆ\&quot;, options: IgnoreCase, expectedGroups: [\&quot;ĀĂĄāăą\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;az-Latn-AZ\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;i\&quot;, options: IgnoreCase, expectedGroups: [\&quot;i\&quot;])
- [ ] System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;en-US\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;i\&quot;, options: IgnoreCase, expectedGroups: [\&quot;i\&quot;])
```
      <test name="System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 2)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture" time="0.0085721" result="Fail">
        <failure exception-type="Xunit.Sdk.AllException">
          <message><![CDATA[Assert.All() Failure: 2 out of 2 items in the collection did not pass.\n[1]: Item: Iıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 53\n        at Xunit.Assert.False(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 19\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 91\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36\n[0]: Item: Iıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 53\n        at Xunit.Assert.False(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 19\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 91\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(Int32 length) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 91
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(length: 256)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture" time="0.0353621" result="Fail">
        <failure exception-type="Xunit.Sdk.AllException">
          <message><![CDATA[Assert.All() Failure: 2 out of 2 items in the collection did not pass.\n[1]: Item: IıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 53\n        at Xunit.Assert.False(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 19\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 91\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36\n[0]: Item: IıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİiIıİi\n     Xunit.Sdk.FalseException: Assert.False() Failure\n     Expected: False\n     Actual:   True\n        at Xunit.Assert.False(Nullable`1 condition, String userMessage) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 53\n        at Xunit.Assert.False(Boolean condition) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\BooleanAsserts.cs:line 19\n        at System.Text.RegularExpressions.Tests.RegexCultureTests.<>c__DisplayClass2_0.<TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture>b__1(Regex rex) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 91\n        at Xunit.Assert.All[Regex](IEnumerable`1 collection, Action`1 action) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 36]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture(Int32 length) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 91
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: None)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="CharactersComparedOneByOne_Invariant" time="0.0009224" result="Fail">
        <failure exception-type="Xunit.Sdk.StartsWithException">
          <message><![CDATA[Assert.StartsWith() Failure:\nExpected: Ö‍\nActual:   Ö]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(RegexOptions options) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 49
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: IgnoreCase | Compiled | CultureInvariant)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="CharactersComparedOneByOne_Invariant" time="0.0000962" result="Fail">
        <failure exception-type="Xunit.Sdk.StartsWithException">
          <message><![CDATA[Assert.StartsWith() Failure:\nExpected: Ö‍\nActual:   Ö]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(RegexOptions options) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 49
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: Compiled)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="CharactersComparedOneByOne_Invariant" time="0.0000888" result="Fail">
        <failure exception-type="Xunit.Sdk.StartsWithException">
          <message><![CDATA[Assert.StartsWith() Failure:\nExpected: Ö‍\nActual:   Ö]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(RegexOptions options) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 49
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(options: IgnoreCase | CultureInvariant)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="CharactersComparedOneByOne_Invariant" time="0.0000864" result="Fail">
        <failure exception-type="Xunit.Sdk.StartsWithException">
          <message><![CDATA[Assert.StartsWith() Failure:\nExpected: Ö‍\nActual:   Ö]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.CharactersComparedOneByOne_Invariant(RegexOptions options) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 49
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;en-US\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0002562" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 889
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;az-Latn-AZ\&quot;, pattern: \&quot;ı\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.000138" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 889
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;tr-TR\&quot;, pattern: \&quot;ı\&quot;, input: \&quot;I\&quot;, options: IgnoreCase, expectedGroups: [\&quot;I\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0001232" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 889
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: null, pattern: \&quot;[B-D\\\\u0130]+\&quot;, input: \&quot;aAeEĩıh BCDbcDİip\&quot;, options: IgnoreCase, expectedGroups: [\&quot;BCDbcDİi\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0028631" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n                 ↓ (pos 7)\nExpected: BCDbcDİi\nActual:   BCDbcDİ\n                 ↑ (pos 7)]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 892
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: null, pattern: \&quot;[\\\\u013B\\\\u013D\\\\u013F]+\&quot;, input: \&quot;ĺĻĽĿļľŀŁ\&quot;, options: IgnoreCase, expectedGroups: [\&quot;ĻĽĿļľŀ\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0001308" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n             ↓ (pos 3)\nExpected: ĻĽĿļľŀ\nActual:   ĻĽĿ\n             ↑ (pos 3)]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 892
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;tr-TR\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;i\&quot;, options: IgnoreCase, expectedGroups: [\&quot;i\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0001205" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 889
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: null, pattern: \&quot;[\\\\u0100\\\\u0102\\\\u0104]+\&quot;, input: \&quot;ÿ ĀĂĄāăąĆ\&quot;, options: IgnoreCase, expectedGroups: [\&quot;ĀĂĄāăą\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.000125" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n             ↓ (pos 3)\nExpected: ĀĂĄāăą\nActual:   ĀĂĄ\n             ↑ (pos 3)]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 892
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;az-Latn-AZ\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;i\&quot;, options: IgnoreCase, expectedGroups: [\&quot;i\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0001222" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 889
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
      <test name="System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(cultureName: \&quot;en-US\&quot;, pattern: \&quot;İ\&quot;, input: \&quot;i\&quot;, options: IgnoreCase, expectedGroups: [\&quot;i\&quot;])" type="System.Text.RegularExpressions.Tests.RegexGroupTests" method="Groups" time="0.0001217" result="Fail">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Assert.True() Failure\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexGroupTests.<Groups>g__Groups|6_0(String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 889
   at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups) in /Users/mdhwang/runtime/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs:line 881
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
        </failure>
      </test>
```

**Comment by danmosemsft** [comment]
A globalization API will almost surely be the cause, not Regex.

**Comment by tarekgh** [comment]
@steveisok 

> Closing in favor of #36900

did you mean https://github.com/dotnet/runtime/issues/36848

**Comment by steveisok** [comment]
:-) yes.
