### ISSUE TITLE
Test failure: Interop\\COM\\ComWrappers\\WeakReference\\WeakReferenceTest\\WeakReferenceTest.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36970]
failed in job: [ runtime-coreclr gcstress-extra 20200524.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=658559&view=ms.vss-test-web.build-test-results-tab&runId=20438422&resultId=110055&paneView=debug)

Error message
~~~
Fatal error. 0xC0000005
 at ComWrappersTests.WeakReferencableWrapper.Finalize()

Return code: 1
Raw output file: C:\h\w\C2780A86\w\A75A091A\e\Interop\COM\Reports\Interop.COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\C2780A86\p\corerun.exe" WeakReferenceTest.dll 
Running ValidateNativeWeakReference...
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\C2780A86\p
> C:\h\w\C2780A86\w\A75A091A\e\Interop\COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.cmd
Expected: True
Actual: False


Stack trace
   at Interop_COM._ComWrappers_WeakReference_WeakReferenceTest_WeakReferenceTest_._ComWrappers_WeakReference_WeakReferenceTest_WeakReferenceTest_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 528
~~~

**Comment by BruceForstall** [comment]
Failure mode: `CoreCLR Windows_NT x86 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open`
