### ISSUE TITLE
Race condition in concurrent method invocation with the dynamic type

### ISSUE THREAD

**Issue by asmichi** [dotnet/runtime#36983]
### Description

Concurrent method invocation with the dynamic type from one call site intermittently causes ``System.Runtime.CompilerServices.CallSite`1.MoveRule(Int32 i)`` to throw `IndexOutOfRangeException`.  

Please check the repro project: [RaceInDynamicInvocation.zip](https://github.com/dotnet/runtime/files/4677782/RaceInDynamicInvocation.zip).
 Please invoke `build.cmd` and `run.cmd` (which continuously executes the program).

This reproduces roughly 1/20 on my environment. Please note that this issue only occurs early in the program life time.

(Example) Concurrently invoking `DynamicInvoker.Invoke` below.
```cs
public static class DynamicInvoker
{
    public static void Invoke(object o) => InvokeImpl((dynamic)o);

    private static void InvokeImpl(int x) { }
    private static void InvokeImpl(long x) { }
}
```

### Configuration

- .NET Core SDK 5.0.100-preview.4.20258.7 (x64)
- .NET Core SDK 3.1.300 (x64)
- Windows 10 Pro 1909 Build 18363.836 (x64)
- AMD Ryzen 2700X

### Regression?

Probably not. I saw this issue several times on .NET Framework 4.7.2.

### Other information

Stack Trace:

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Runtime.CompilerServices.CallSite`1.MoveRule(Int32 i)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at RaceInDynamicInvocation.DynamicInvoker.Invoke(Object o) in C:\home\playground\RaceInDynamicInvocation\RaceInDynamicInvocation\Program.cs:line 58
   at RaceInDynamicInvocation.Program.ThreadFunc(Object obj) in C:\home\playground\RaceInDynamicInvocation\RaceInDynamicInvocation\Program.cs:line 51
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

I am not really sure but my hypothesis is as follows:

- Concurrent invocation of [CallSite.AddRule](https://github.com/dotnet/runtime/blob/47ec733ba79b196e4e09d0c89bad245155002353/src/libraries/System.Linq.Expressions/src/System/Runtime/CompilerServices/CallSite.cs#L239) could shrink its `Rules` array. 
  For example:
    - Suppose `Rules` has `T[1]` (1 element).
    - Thread 1 enters `AddRule` and fetches `T[1]` from `Rules` into `rules`.
    - Thread 2 and thread 3 fully executes `AddRule` and extends `Rules`. `Rules` now has `T[3]`.
    - Thread 1 finally executes `Rules = temp`. `Rules` now has `T[2]` (shrunk!).
- `CallSite.MoveRule` could reference this shrunk array, resulting in an `IndexOutOfRangeException`.
    - `i` passed from [UpdateAndExecuteN](https://github.com/dotnet/runtime/blob/v5.0.0-preview.4.20251.6/src/libraries/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs#L50) could be for the extended array (`T[3]` in the above example).
    - On the other hand, when `CallSite.MoveRule` is called, `Rules` array could already be shrunk (`T[2]` in the above example).

**Comment by asmichi** [comment]
Just realized that you need to use the ReadyToRun version of System.Linq.Expressions.dll to reproduce this. When you use the non-ReadyToRun version, this issue rarely reproduces. (This issue only occurs early in the program life time as I mentioned, so early-stage performance matters.)

----

To my understanding, the reasoning behind the lack of locks is that this is just a cache after all. Messing up with the cache will only cause increased cache misses or longer lookup time. This perf loss is fine if you get more perf gain by omitting locks.

IMHO we could just introduce a manual bounds check to `CallSite.MoveRule`. This will incur no perf loss (at least in the tier-1-JITed code) because `CallSite.MoveRule` already has a JIT-generated bounds check to generate `IndexOutOfRangeException`. In fact the code will be shorter because it will no longer need to generate `IndexOutOfRangeException`.

Proposed code:
```C#
internal void MoveRule(int i)
{
    if (i <= 1)
    {
        return;
    }

    T[] rules = Rules!;
    if (unchecked((uint)i >= (uint)rules.Length))
    {
        return;
    }

    T rule = rules[i];

    rules[i] = rules[i - 1];
    rules[i - 1] = rules[i - 2];
    rules[i - 2] = rule;
}
```

Alternatively we could change the assignment in `CallSite.AddRule` to `Interlocked.CompareExchange(ref Rules, temp, rules)` so that the `Rules` array will not be shrunk. I do not think this "fix" will be justified without a real issue caused by this, considering the code is mature.
