### ISSUE TITLE
System.Buffers tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37067]
### System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests:
- [ ] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent
- [ ] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ReturnBufferFiresDiagnosticEvent
- [ ] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentBufferFiresRentedDiagnosticEvent
- [ ] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingNonExistentBufferFiresAllocatedDiagnosticEvent
- [ ] System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingManyBuffersFiresExpectedDiagnosticEvents
```
<test name="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent" type="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests" method="RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent" time="0.230129" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim) in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs:line 45
		at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent() in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs:line 451
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ReturnBufferFiresDiagnosticEvent" type="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests" method="ReturnBufferFiresDiagnosticEvent" time="0.000637" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim) in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs:line 45
		at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ReturnBufferFiresDiagnosticEvent() in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs:line 424
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentBufferFiresRentedDiagnosticEvent" type="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests" method="RentBufferFiresRentedDiagnosticEvent" time="0.000581" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim) in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs:line 45
		at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentBufferFiresRentedDiagnosticEvent() in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs:line 404
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingNonExistentBufferFiresAllocatedDiagnosticEvent" type="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests" method="RentingNonExistentBufferFiresAllocatedDiagnosticEvent" time="0.00078" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim) in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs:line 45
		at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingNonExistentBufferFiresAllocatedDiagnosticEvent() in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs:line 441
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingManyBuffersFiresExpectedDiagnosticEvents" type="System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests" method="RentingManyBuffersFiresExpectedDiagnosticEvents" time="0.000585" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim) in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs:line 45
		at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingManyBuffersFiresExpectedDiagnosticEvents() in /Users/mdhwang/runtime/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs:line 461
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```

**Comment by tannergooding** [comment]
CC. @GrabYourPitchforks @pgovind
Also CC. @stephentoub as you did some work to reduce RemoteInvokes in https://github.com/dotnet/corefx/pull/41741

This looks like the tests just need some kind of "SkipOnAndroid" attribute

**Comment by stephentoub** [comment]
See the discussions here:
https://github.com/dotnet/arcade/pull/5401#discussion_r419525567
https://github.com/dotnet/arcade/pull/5401#issuecomment-623577466
cc: @safern

**Comment by safern** [comment]
@tannergooding this is a known issue, we have some tracking issues for this to be fixed without having to annotate the tests: https://github.com/dotnet/xharness/issues/205

Also, the ios/tvOS/Android test failures issues that have been open, please ignored as those will be triaged/fixed in a separate wave. At the moment we're just opening issues to understand where we are and to be able to track what we need to fix/disable in order to enable these legs in CI.

**Comment by steveisok** [comment]
The ones that are just RemoteExecutor based can be closed.  We know they'll be skipped once the xharness changes land.
