### ISSUE TITLE
System.Collections tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37069]
### System.Collections.Concurrent.Tests:
- [ ] System.Collections.Concurrent.Tests.EtwTests.TestEtw
```
<test name="System.Collections.Concurrent.Tests.EtwTests.TestEtw" type="System.Collections.Concurrent.Tests.EtwTests" method="TestEtw" time="0.127357" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.Collections.Concurrent.Tests.EtwTests.TestEtw() in /Users/mdhwang/runtime/src/libraries/System.Collections.Concurrent/tests/EtwTests.cs:line 18
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```
___
### System.Collections.Immutable.Tests:
- [ ] System.Collections.Immutable.Tests.ImmutableArrayTest.IStructuralEquatableGetHashCode
```
<test name="System.Collections.Immutable.Tests.ImmutableArrayTest.IStructuralEquatableGetHashCode" type="System.Collections.Immutable.Tests.ImmutableArrayTest" method="IStructuralEquatableGetHashCode" time="0" result="Fail">
  <failure exception-type="System.InvalidOperationException">
    <message><![CDATA[System.InvalidOperationException : No data found for System.Collections.Immutable.Tests.ImmutableArrayTest.IStructuralEquatableGetHashCode]]></message>
    <stack-trace><![CDATA[]]></stack-trace>
  </failure>
</test>
```
___
### System.Collections.NonGeneric.Tests:
- [ ] System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Ctor_CultureInfo_GetHashCodeCompare_TurkishI
- [ ] System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Default_Compare_TurkishI
- [ ] System.Collections.Tests.CaseInsensitiveComparerTests.Ctor_CultureInfo_Compare_TurkishI
```
<test name="System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Ctor_CultureInfo_GetHashCodeCompare_TurkishI" type="System.Collections.Tests.CaseInsensitiveHashCodeProviderTests" method="Ctor_CultureInfo_GetHashCodeCompare_TurkishI" time="0.032986" result="Fail">
  <failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: False\nActual:   True]]></message>
    <stack-trace><![CDATA[   at System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Ctor_CultureInfo_GetHashCodeCompare_TurkishI() in /Users/mdhwang/runtime/src/libraries/System.Collections.NonGeneric/tests/CaseInsensitiveHashCodeProviderTests.cs:line 140
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Default_Compare_TurkishI" type="System.Collections.Tests.CaseInsensitiveHashCodeProviderTests" method="Default_Compare_TurkishI" time="0.002206" result="Fail">
  <failure exception-type="Xunit.Sdk.FalseException">
    <message><![CDATA[Assert.False() Failure\nExpected: False\nActual:   True]]></message>
    <stack-trace><![CDATA[   at System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Default_Compare_TurkishI() in /Users/mdhwang/runtime/src/libraries/System.Collections.NonGeneric/tests/CaseInsensitiveHashCodeProviderTests.cs:line 181
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.Collections.Tests.CaseInsensitiveComparerTests.Ctor_CultureInfo_Compare_TurkishI" type="System.Collections.Tests.CaseInsensitiveComparerTests" method="Ctor_CultureInfo_Compare_TurkishI" time="0.001527" result="Fail">
  <failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 1\nActual:   0]]></message>
    <stack-trace><![CDATA[   at System.Collections.Tests.CaseInsensitiveComparerTests.Ctor_CultureInfo_Compare_TurkishI() in /Users/mdhwang/runtime/src/libraries/System.Collections.NonGeneric/tests/CaseInsensitiveComparerTests.cs:line 105
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```

**Comment by mdh1418** [comment]
https://github.com/dotnet/runtime/issues/56407 may be related with respect to Turkish culture failing.

**Comment by danmoseley** [comment]
It's the same issue. The special casing behavior of Turkish I. This isn't new so even if these devices have old ICU it ought to work. @tarekgh  have you seen this fail?

**Comment by tarekgh** [comment]
It looks to me on Android there is one of the following cultures have Turkish I behavior. 

```
    "cs-CZ","da-DK","de-DE","el-GR","en-US",
    "es-ES","fi-FI","fr-FR","hu-HU","it-IT",
    "ja-JP","ko-KR","nb-NO","nl-NL","pl-PL",
    "pt-BR","pt-PT","ru-RU","sv-SE",
    "zh-CN","zh-HK","zh-TW"
```

I suggested if we can manually check that on the failed device or at least update the test to print the culture name that is failed.

**Comment by danmoseley** [comment]
@mdh1418 can you update the assert of one of these tests to dump the culture name eg
https://github.com/danmoseley/runtime/blob/b432e9892e8cf10d30891f207dbccb4b3de2c3df/src/libraries/System.Collections.NonGeneric/tests/CaseInsensitiveHashCodeProviderTests.cs#L93

**Comment by mdh1418** [comment]
@danmoseley @tarekgh 
```
Test collection for System.Collections.Tests.CaseInsensitiveHashCodeProviderTests
08-06 13:30:04.389  8740  8766 D DOTNET  : assembly_preload_hook: xunit.assert  /data/user/0/net.dot.System.Collections.NonGeneric.Tests/files
MitchellHwang: cs-CZ
2113348816 == 2113348816
MitchellHwang: da-DK
2113348816 == 2113348816
MitchellHwang: de-DE
2113348816 == 2113348816
MitchellHwang: el-GR
2113348816 == 2113348816
MitchellHwang: en-US
2113348816 == 2113348816
MitchellHwang: es-ES
2113348816 == 2113348816
MitchellHwang: fi-FI
2113348816 == 2113348816
MitchellHwang: fr-FR
2113348816 == 2113348816
MitchellHwang: hu-HU
2113348816 == 2113348816
MitchellHwang: it-IT
2113348816 == 2113348816
MitchellHwang: ja-JP
2113348816 == 2113348816
MitchellHwang: ko-KR
2113348816 == 2113348816
MitchellHwang: nb-NO
2113348816 == 2113348816
MitchellHwang: nl-NL
2113348816 == 2113348816
MitchellHwang: pl-PL
2113348816 == 2113348816
MitchellHwang: pt-BR
2113348816 == 2113348816
MitchellHwang: pt-PT
2113348816 == 2113348816
MitchellHwang: ru-RU
2113348816 == 2113348816
MitchellHwang: sv-SE
2113348816 == 2113348816
MitchellHwang: tr-TR
2113348816 == 2113348816
   Test name: System.Collections.Tests.CaseInsensitiveHashCodeProviderTests.Ctor_CultureInfo_GetHashCodeCompare_TurkishI
   Exception messages: Assert.Equal() Failure
Expected: False
Actual:   True
```
So it looks like `provider.GetHashCode("file")` and `provider.GetHashCode("FILE")` are incorrectly the same for tr-TR.

**Comment by tarekgh** [comment]
In this case the issue would be related to the ICU used in Android or Mono could be doing something different than coreclr. 

https://source.dot.net/#System.Private.CoreLib/CompareInfo.Icu.cs,739

**Comment by danmoseley** [comment]
@mdh1418 what version of libicu is on this device? 

I'm not sure where it is or the file name, but eg on Ubuntu I have
```
dan@LAPTOP-P6UJDVTA:/lib$ find . -name "libicudata.so" | ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.3) 2.31
```

I wonder whether it's particular to this Android version/distribution that it hasn't come up before. Windows has had this behavior for nearly 20 years so I would be surprised if it was only recently fixed in ICU/CLDR.

**Comment by danmoseley** [comment]
Either way, it's very unlikely that we can do anything about it. The only question in my mind is whether this is true for all Android flavors, and whether we're testing on one that should be updated.

**Comment by tarekgh** [comment]
I believe Android has customized version of ICU, so the version wouldn't help much here. We need to confirm if this is issue with the ICU version installed on Android or there is something different between Mono and coreclr in such code path. 

@danmoseley just FYI, on Ubuntu, you can get the ICU version by running the command `uconv -V`

**Comment by steveisok** [comment]
The ICU version is set to the API level.  This [table](https://developer.android.com/guide/topics/resources/internationalization#versioning-nougat) shows the breakdown.  It's unknown how much they customize, but there clearly are subtle differences between desktop, Android, and what we provide in iOS.  Also, there theoretically could be differences between devices / carriers as I believe they have full control over what Android they ship.

**Comment by danmoseley** [comment]
This appears to suggest that the behavior was supported starting in v28, but your table shows that as the lowest version. 
https://www.unicode.org/cldr/cldr-aux/charts/28/delta/transform-tr-Lower.html
