### ISSUE TITLE
System.CodeDom tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37068]
### System.CodeDom.Compiler.Tests.ExecutorTests:
- [ ] System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_OutputIncludesCurrentDirectory
- [ ] System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_NullNames_OutputCaptured
- [ ] System.CodeDom.Compiler.Tests.ExecutorTests.ExecWait_OutputCaptured
- [ ] System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_SpecifiedNames_OutputCaptured
- [ ] System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_CurrentDirectorySpecified_OutputIncludesSpecifiedDirectory
```
<test name="System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_OutputIncludesCurrentDirectory" type="System.CodeDom.Compiler.Tests.ExecutorTests" method="ExecWaitWithCapture_OutputIncludesCurrentDirectory" time="0.135099" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_OutputIncludesCurrentDirectory() in /Users/mdhwang/runtime/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/ExecutorTests.cs:line 117
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_NullNames_OutputCaptured" type="System.CodeDom.Compiler.Tests.ExecutorTests" method="ExecWaitWithCapture_NullNames_OutputCaptured" time="0.002159" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_NullNames_OutputCaptured() in /Users/mdhwang/runtime/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/ExecutorTests.cs:line 55
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.CodeDom.Compiler.Tests.ExecutorTests.ExecWait_OutputCaptured" type="System.CodeDom.Compiler.Tests.ExecutorTests" method="ExecWait_OutputCaptured" time="0.000885" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.CodeDom.Compiler.Tests.ExecutorTests.ExecWait_OutputCaptured() in /Users/mdhwang/runtime/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/ExecutorTests.cs:line 40
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_SpecifiedNames_OutputCaptured" type="System.CodeDom.Compiler.Tests.ExecutorTests" method="ExecWaitWithCapture_SpecifiedNames_OutputCaptured" time="0.00085" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_SpecifiedNames_OutputCaptured() in /Users/mdhwang/runtime/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/ExecutorTests.cs:line 80
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_CurrentDirectorySpecified_OutputIncludesSpecifiedDirectory" type="System.CodeDom.Compiler.Tests.ExecutorTests" method="ExecWaitWithCapture_CurrentDirectorySpecified_OutputIncludesSpecifiedDirectory" time="0.000917" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.CodeDom.Compiler.Tests.ExecutorTests.ExecWaitWithCapture_CurrentDirectorySpecified_OutputIncludesSpecifiedDirectory() in /Users/mdhwang/runtime/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/ExecutorTests.cs:line 100
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```

**Comment by mdh1418** [comment]
All of these are RemoteExecutor errors
