### ISSUE TITLE
System.IO tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37077]
### System.IO.MemoryMapped.Tests:
- [ ] System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared
```
<test name="System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared" type="System.IO.MemoryMappedFiles.Tests.CrossProcessTests" method="DataShared" time="0.112365" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 115
		at System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared() in /Users/mdhwang/runtime/src/libraries/System.IO.MemoryMappedFiles/tests/MemoryMappedFile.CrossProcess.cs:line 30
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```
___
### System.IO.Pipes.Tests:

These are all RemoteExecutor related
- [ ] System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof
- [ ] System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong
- [ ] System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ClientClosesPipe_ServerReceivesEof
- [ ] System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.PingPong_Sync
- [ ] System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.PingPong_Async
- [ ] System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.InheritHandles_AvailableInChildProcess
```
<test name="System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof" type="System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess" method="ServerClosesPipe_ClientReceivesEof" time="0.114943" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 115
		at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof() in /Users/mdhwang/runtime/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs:line 56
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong" type="System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess" method="PingPong" time="0.001424" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`2 method, String arg1, String arg2, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 128
		at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong() in /Users/mdhwang/runtime/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs:line 21
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ClientClosesPipe_ServerReceivesEof" type="System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess" method="ClientClosesPipe_ServerReceivesEof" time="0.000762" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 115
		at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ClientClosesPipe_ServerReceivesEof() in /Users/mdhwang/runtime/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs:line 83
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.PingPong_Sync" type="System.IO.Pipes.Tests.NamedPipeTest_CrossProcess" method="PingPong_Sync" time="0.001895" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`2 method, String arg1, String arg2, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 128
		at System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.PingPong_Sync() in /Users/mdhwang/runtime/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CrossProcess.cs:line 59
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.PingPong_Async" type="System.IO.Pipes.Tests.NamedPipeTest_CrossProcess" method="PingPong_Async" time="0.002523" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`2 method, String arg1, String arg2, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 128
		at System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.PingPong_Async() in /Users/mdhwang/runtime/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CrossProcess.cs:line 85
--- End of stack trace from previous location ---]]></stack-trace>
  </failure>
</test>
<test name="System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.InheritHandles_AvailableInChildProcess" type="System.IO.Pipes.Tests.NamedPipeTest_CrossProcess" method="InheritHandles_AvailableInChildProcess" time="0.113343" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 115
		at System.IO.Pipes.Tests.NamedPipeTest_CrossProcess.InheritHandles_AvailableInChildProcess() in /Users/mdhwang/runtime/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CrossProcess.cs:line 26
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```

**Comment by mdh1418** [comment]
Dupe of #36836 and #36845, and the rest.are RemoteExecutor errors
