### ISSUE TITLE
System.ComponentModel tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37070]
### System.ComponentModel.EventBasedAsync.Tests:
- [ ] System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationNotCompleted_CompletesOperation
- [ ] System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationCompleted_DoesNotCallOperationCompleted
```
<test name="System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationNotCompleted_CompletesOperation" type="System.ComponentModel.Tests.AsyncOperationFinalizerTests" method="Finalizer_OperationNotCompleted_CompletesOperation" time="0.134105" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationNotCompleted_CompletesOperation() in /Users/mdhwang/runtime/src/libraries/System.ComponentModel.EventBasedAsync/tests/AsyncOperationFinalizerTests.cs:line 41
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
<test name="System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationCompleted_DoesNotCallOperationCompleted" type="System.ComponentModel.Tests.AsyncOperationFinalizerTests" method="Finalizer_OperationCompleted_DoesNotCallOperationCompleted" time="0.000616" result="Fail">
  <failure exception-type="Microsoft.DotNet.XUnitExtensions.SkipTestException">
    <message><![CDATA[Microsoft.DotNet.XUnitExtensions.SkipTestException : RemoteExecutor is not supported on this platform.]]></message>
    <stack-trace><![CDATA[   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 398
		at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action method, RemoteInvokeOptions options) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 102
		at System.ComponentModel.Tests.AsyncOperationFinalizerTests.Finalizer_OperationCompleted_DoesNotCallOperationCompleted() in /Users/mdhwang/runtime/src/libraries/System.ComponentModel.EventBasedAsync/tests/AsyncOperationFinalizerTests.cs:line 17
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```

**Comment by mdh1418** [comment]
These errors are RemoteExecutor related
