### ISSUE TITLE
Test failure: tracing\\eventpipe\\reverse\\reverse\\reverse.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#37228]
failed in job: [ runtime-coreclr outerloop 20200531.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=665887&view=ms.vss-test-web.build-test-results-tab&runId=20637786&resultId=109297&paneView=debug)

Error message
~~~
Unhandled exception. System.InvalidOperationException: No process is associated with this object.
 at System.Diagnostics.Process.EnsureState(State state) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 914
 at System.Diagnostics.Process.EnsureState(State state) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 926
 at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs:line 802
 at System.Diagnostics.Process.GetProcessTimes() in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs:line 705
 at System.Diagnostics.Process.get_StartTime() in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 200
 at Tracing.Tests.ReverseValidation.ReverseValidation.<>c__DisplayClass2_0.<RunSubprocess>b__0(Object s, DataReceivedEventArgs e) in F:\workspace\work\1\s\src\coreclr\tests\src\tracing\eventpipe\reverse\reverse.cs:line 67
 at System.Diagnostics.Process.OutputReadNotifyUser(String data) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1575
 at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 236
--- End of stack trace from previous location ---
 at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 248
 at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading.ThreadPoolWaitCallback.PerformWaitCallback()
Unhandled exception. System.ComponentModel.Win32Exception (6): The handle is invalid.
 at System.Diagnostics.Process.GetProcessTimes() in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs:line 717
 at System.Diagnostics.Process.get_StartTime() in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 200
 at Tracing.Tests.ReverseValidation.ReverseValidation.<>c__DisplayClass2_0.<RunSubprocess>b__0(Object s, DataReceivedEventArgs e) in F:\workspace\work\1\s\src\coreclr\tests\src\tracing\eventpipe\reverse\reverse.cs:line 67
 at System.Diagnostics.Process.OutputReadNotifyUser(String data) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1575
 at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 236
--- End of stack trace from previous location ---
 at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi) in //src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 248
 at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
 at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Return code: 1
Raw output file: D:\h\w\AAFA093A\w\C18C0A33\e\tracing\eventpipe\Reports\tracing.eventpipe\reverse\reverse\reverse.output.txt
Raw output:
BEGIN EXECUTION
 1 file(s) copied.
" "D:\h\w\AAFA093A\p\crossgen.exe" /Platform_Assemblies_Paths D:\h\w\AAFA093A\p;D:\h\w\AAFA093A\w\C18C0A33\e\tracing\eventpipe\reverse\reverse /in D:\h\w\AAFA093A\w\C18C0A33\e\tracing\eventpipe\reverse\reverse\reverse.org /out D:\h\w\AAFA093A\w\C18C0A33\e\tracing\eventpipe\reverse\reverse\\reverse.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 5.0.0-c


Stack trace
   at tracing_eventpipe._reverse_reverse_reverse_._reverse_reverse_reverse_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\tracing.eventpipe\tracing.eventpipe.XUnitWrapper.cs:line 722
~~~

**Comment by tommcdon** [comment]
@josalem

**Comment by josalem** [comment]
Ah, I think I know what's happening here.  One sec, and I'll have a fix.
