### ISSUE TITLE
[System.Text.Json] Deserialize ArraySegment<byte> throw null ref

### ISSUE THREAD

**Issue by wuzhuoqing** [dotnet/runtime#37268]
dotnet core 3.1 
Serialize work but Deserialize will throw null ref. Work around by adding a custom converter for ArraySegment<byte>. This could be by design, however the null ref exception makes trouble shotting harder.

Newtonsoft Json will not throw but with ends up with default instance of ArraySegment<byte>.
```
        class TestDataRequestClass
        {
            public ArraySegment<byte> UserId { get; set; }
            public TestDataRequestClass()
            {
            }
        }

        [TestMethod()]
        public void DataReqeustArraySegmentByteJsonTest()
        {
            var testDataRequest = new TestDataRequestClass()
            {
                UserId = new ArraySegment<byte>(new byte[] { 1 }),
            };
            var testJsonRequest = JsonSerializer.Serialize(testDataRequest);

            var testRequestBack = JsonSerializer.Deserialize<TestDataRequestClass>(testJsonRequest);
            Assert.IsTrue(testRequestBack != null);
        }
```

```
   at System.Text.Json.JsonPropertyInfoCommon`4.SetValueAsObject(Object obj, Object value) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs:line 92
   at System.Text.Json.ReadStackFrame.CreateEnumerableValue(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.HandleStartArray(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

**Comment by layomia** [comment]
The serializer no longer fails with `NullReferenceException` in 5.0 for this scenario. Instead, `NotSupportedException` is thrown, as read-only collections are not supported for deserialization:

```
System.Text.Json.Serialization.Tests.InvalidTypeTests_Writer.ArraySegmentTest [FAIL]
        System.NotSupportedException : The collection type 'System.ArraySegment`1[System.Byte]' is abstract, an interface, or is read only, and could not be instantiated and populated. Path: $.ArraySegment | LineNumber: 0 | BytePositionInLine: 17.
```

A workaround is to write a custom converter and create an `ArraySegment<T>` instance with the appropriate constructor.
