### ISSUE TITLE
IdnMapping.GetAscii throws for some inputs in GlobalizationMode.Invariant

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#37349]
```C#
Unhandled exception. System.ArgumentException: Left to right characters may not be mixed with right to left characters in IDN labels. (Parameter 'unicode')
   at System.Globalization.IdnMapping.PunycodeEncode(String unicode)
   at System.Globalization.IdnMapping.GetAsciiInvariant(String unicode, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count)
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index)
   at System.Globalization.IdnMapping.GetAscii(String unicode)
```
This works fine with both NLS and ICU.  But when GlobalizationMode.Invariant is enabled (uncomment the relevant line above), it throws an exception:
```
System.ArgumentException: Left to right characters may not be mixed with right to left characters in IDN labels. (Parameter 'unicode')
   at System.Globalization.IdnMapping.PunycodeEncode(String unicode) in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\Globalization\IdnMapping.cs:line 364
   at System.Globalization.IdnMapping.GetAscii(String unicode, Int32 index, Int32 count) in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\Globalization\IdnMapping.cs:line 88
```

**Comment by stephentoub** [comment]
My point is saying "We don't promise any correct IDN behavior when enabling GlobalizationMode.Invariant" means we also don't promise any correct behavior for anything higher in the stack, whether it be SslStream or HttpClient or anything else that uses it.

**Comment by tarekgh** [comment]
@stephentoub I understand your point. I was just commenting on what would be the choice between throwing and not throwing on the level of the IDN layer. 

For the higher stack with the Invariant mode, we can have the choice to change the Invariant mode behavior when the system already has NLS/ICU. This will be the case always on Windows and MacOS and only be broken on Linux images not having ICU installed. the concern with that is we are not fully solving the problem and we are losing the consistency promise when enabling Invariant. Note, I am talking about the IDN only and not the whole globalization.

**Comment by stephentoub** [comment]
> I understand your point.

👍

**Comment by tarekgh** [comment]
I am moving this to 6.0 release as this is not a new behavior for invariant mode. we can revisit later to enhance Invariant mode if needed.

**Comment by ilonatommy** [comment]
Update:
The sample in description works already (returns `xn--e28h` in Invariant). 
The exception is thrown e.g. for `àא ` that should be coded as `xn--0ca24w` according to unicode13.

Beyond throwing, there are cases where we return incorrect result and these are e.g. from Unicode13 tests:
```
0à.א; 0à.א; [B1]; xn--0-sfa.xn--4db; ; ;  # 0à.א  (returns: xn--0a-6tb.xn--4db)
0À.א; 0à.א; [B1]; xn--0-sfa.xn--4db; ; ;  # 0à.א  (returns: xn--0a-6tb.xn--4db)
0À.א; 0à.א; [B1]; xn--0-sfa.xn--4db; ; ;  # 0à.א  (returns: xn--0-yda.xn--4db)
```
all of the above, instead of returning אà.א, throw when `toUnicode` is done on `source`,;

**Comment by tarekgh** [comment]
@ilonatommy we cannot have a perfect IDN behavior in Invariant mode without having some way to support the normalization. Look at my comment https://github.com/dotnet/runtime/issues/37349#issuecomment-638348089.
