### ISSUE TITLE
Test failure: System.Text.Json.Serialization.Tests.EnumConverterTests.VeryLargeAmountOfEnumsToSerialize

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#37471]
failed in job: [runtime-libraries outerloop 20200604.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=671384&view=ms.vss-test-web.build-test-results-tab&runId=20798184&resultId=104437&paneView=debug)

failed tests:
System.Text.Json.Serialization.Tests.EnumConverterTests.VeryLargeAmountOfEnumsToSerialize

System.Text.Json.Tests.Utf8JsonReaderTests.TestPartialJsonReaderSlicesMultiSegment(compactData: True, type: FullSchema1, jsonString: \"{\\\"age\\\":30,\\\"first\\\":\\\"John\\\",\\\"last\\\":\\\"Smith\\\",\"...)

Error message
~~~
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Threading.Tasks.Task`1.StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 328
   at System.Threading.Tasks.Task.Run[TResult](Func`1 function) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 5145
   at System.Text.Json.Serialization.Tests.EnumConverterTests.VeryLargeAmountOfEnumsToSerialize() in /_/src/libraries/System.Text.Json/tests/Serialization/EnumConverterTests.cs:line 253
~~~

**Comment by danmosemsft** [comment]
@v-haren can you please include the configuration in test failure issues? It is on the link above, in this case it is `net5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open`

**Comment by ManickaP** [comment]
Hit in my PR #37441 as well:
https://dev.azure.com/dnceng/public/_build/results?buildId=672063&view=ms.vss-test-web.build-test-results-tab&runId=20821412&paneView=debug&resultId=104439
