### ISSUE TITLE
profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.sh crashed on OSX x64

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#37533]
This test failed with:

```
profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.sh [FAIL]
      Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
         at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /Users/runner/runners/2.169.1/work/1/s/src/coreclr/tests/src/profiler/common/ProfilerTestRunner.cs:line 137
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /Users/runner/runners/2.169.1/work/1/s/src/coreclr/tests/src/profiler/common/ProfilerTestRunner.cs:line 91
         at Profiler.Tests.Program.Main(String[] args) in /Users/runner/runners/2.169.1/work/1/s/src/coreclr/tests/src/profiler/unittest/getappdomainstaticaddress.cs:line 26
      task_for_pid(59803) FAILED 5 (os/kern) failure
      /private/tmp/helix/working/B24C0971/w/AE8609DB/e/profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.sh: line 317: 59803 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /private/tmp/helix/working/B24C0971/w/AE8609DB/e/profiler/unittest/Reports/profiler.unittest/getappdomainstaticaddress/getappdomainstaticaddress.output.txt
      Raw output:
```

Core Dumps:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-37525-merge-48e0ca0d9cc441a6a4/profiler.unittest/core.59803?sv=2019-02-02&se=2020-06-25T23%3A38%3A22Z&sr=c&sp=rl&sig=eKeG1IQaffFbwcHF0WEm1aOTsvKl8P%2F7PJ%2FvOqi7IJI%3D
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-37525-merge-48e0ca0d9cc441a6a4/profiler.unittest/core.59805?sv=2019-02-02&se=2020-06-25T23%3A38%3A22Z&sr=c&sp=rl&sig=eKeG1IQaffFbwcHF0WEm1aOTsvKl8P%2F7PJ%2FvOqi7IJI%3D

Happened in: https://github.com/dotnet/runtime/pull/37525

cc: @jashook

**Comment by danmosemsft** [comment]
@tommcdon this is your area I guess?

**Comment by tommcdon** [comment]
@davmason this looks like an ICorProfiler test

**Comment by davmason** [comment]
It is a profiler test, I am unable to repro though and it's been almost a month. I think it's a one off failure so closing, if it happens again I can investigate more.
