### ISSUE TITLE
Test failure: System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#37540]
`runtime-libraries outerloop` failed on: #37515, #37487

[Pipeline build](https://dev.azure.com/dnceng/public/_build/results?buildId=673981&view=ms.vss-test-web.build-test-results-tab&runId=20898180&resultId=104333&paneView=debug)

Failed configurations:
- `net5.0-Windows_NT-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open`
- `net5.0-Windows_NT-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open`
- `net5.0-Windows_NT-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open`

Error message
```
System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop [FAIL]
  Assert.Equal() Failure
  Expected: 6
  Actual:   0
  Stack Trace:
    /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs(96,0): at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop()

OR

System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop [FAIL]
  System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
  Expected: 6
  Actual:   0) (The operation requested for service '27daeee4-966a-4f33-81b8-dce85a14f3f3' has not been completed within the specified time interval.)
  ---- Assert.Equal() Failure
  Expected: 6
  Actual:   0
  ---- System.ServiceProcess.TimeoutException : The operation requested for service '27daeee4-966a-4f33-81b8-dce85a14f3f3' has not been completed within the specified time interval.
  Stack Trace:
    
    ----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
    /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs(96,0): at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop()
    ----- Inner Stack Trace #2 (System.ServiceProcess.TimeoutException) -----
    /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs(903,0): at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
    /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs(154,0): at System.ServiceProcess.Tests.TestServiceInstaller.StopService()
    /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs(119,0): at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService()
    /_/src/libraries/System.ServiceProcess.ServiceController/tests/TestServiceProvider.cs(135,0): at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices()
    /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs(218,0): at System.ServiceProcess.Tests.ServiceBaseTests.Dispose()
    C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)
```

**Comment by ManickaP** [comment]
Another hit: https://dev.azure.com/dnceng/public/_build/results?buildId=713669&view=ms.vss-test-web.build-test-results-tab&runId=22124978&resultId=104429&paneView=debug

**Comment by ericstj** [comment]
Dup of https://github.com/dotnet/runtime/issues/38945
