### ISSUE TITLE
[browser][wasm] System.NotSupportedException: Cannot start threads on this runtime.

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#37601]
.NET5 version of Timer relies on threading to be available on WASM platform

```
uncaught exception: System.AggregateException: One or more errors occurred. (Cannot start threads on this runtime.)
 ---> System.NotSupportedException: Cannot start threads on this runtime.
   at System.Threading.Thread.Start()
   at System.Threading.TimerQueue.InitializeScheduledTimerManager_Locked()
   at System.Threading.TimerQueue.SetTimer(UInt32 actualDuration)
   at System.Threading.TimerQueue.EnsureTimerFiresBy(UInt32 requestedDuration)
   at System.Threading.TimerQueue.UpdateTimer(TimerQueueTimer timer, UInt32 dueTime, UInt32 period)
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.CancellationTokenSource.CancelAfter(Int32 millisecondsDelay)
   at System.Threading.CancellationTokenSource.CancelAfter(TimeSpan delay)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Test.HttpClientRequestAsync2(String url)
   --- End of inner exception stack trace ---

​```

**Comment by marek-safar** [comment]
This is .NET5 tracking issue only

**Comment by marek-safar** [comment]
Should be fixed in master
