### ISSUE TITLE
System.IO.IOException : The configured user limit (1024) on the number of inotify instances has been reached.

### ISSUE THREAD

**Issue by shaulbehr** [dotnet/runtime#37610]
### Describe the bug
I have created a branch of my project to upgrade to .NET Core 2.2, including upgrading Microsoft.Extensions.Configuration.Json to 2.2.0.
This branch is now failing CI builds with the error:
```
System.IO.IOException : The configured user limit (1024) on the number of inotify instances has been reached.
```

### To Reproduce
1. Using version 2.2.0 of package 'Microsoft.Extensions.Configuration.Json'
2. Run a huge battery of unit tests, with a large number (128+) of TestFixtures.

### Expected behavior
Tests should execute successfully.

### Additional context
I cannot state positively that this library is causing the problem, but from the research I've done online (e.g. [here](https://stackoverflow.com/q/45875981/7850)) it appears that this error is associated with the `.AddJsonFile()` extension, when `reloadOnChange` is set to `true`. I'm setting it to `false`, but I have a sneaking suspicion that a bug got introduced that makes it track the file even if `reloadOnChange` is set to `false`.

**Comment by ericstj** [comment]
@caroe2014 since the issue you are facing seems distinct from the original issue (battery of unit tests) can you please open a new issue with repro steps and ideally a repro project?  You can open that issue in dotnet/runtime.

**Comment by caroe2014** [comment]
This is the issue the customer is facing. As far I can see, it is the same issue:

System.IO.IOException: The configured user limit (1024) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
2020-06-04T17:47:23.437166246Z    at System.IO.FileSystemWatcher.StartRaisingEvents()
2020-06-04T17:47:23.437170046Z    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
2020-06-04T17:47:23.437173746Z    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
2020-06-04T17:47:23.437177546Z    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
2020-06-04T17:47:23.437181346Z    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
2020-06-04T17:47:23.437184846Z    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
2020-06-04T17:47:23.437188446Z    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
2020-06-04T17:47:23.437191946Z    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()

**Comment by ericstj** [comment]
Please open a new issue describing what the customer app is doing. Ideally with an isolated repro. As I mentioned it’s normal for this error to occur if too many FileSystemWatchers are created without disposing them so the exception / stack you’ve shared isn’t sufficient to diagnose the issue.
