### ISSUE TITLE
[5.0.100-preview.6.20308.7] WalletWasabi app Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime exception at launch

### ISSUE THREAD

**Issue by DotNetAppCompatFeiWang** [dotnet/runtime#37638]
Application Name: WalletWasabi
OS: Windows 10 RS5
CPU: X64
.NET Build Number: 5.0.100-preview.6.20308.7
App Source on GitHub link:  https://github.com/zkSNACKs/WalletWasabi

Verify Scenarios:
1). **Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.6.20308.7: Fail**
2). **Windows 10 RS5 X64 + .NET Core SDK build 5.0.100-preview.5.20279.10: Pass**

**Findings :
We think this could be known issue but we couldn't find announcement.
https://github.com/dotnet/windowsdesktop/pull/847**

Exception Log :
```
020-06-09 08:39:48 CRITICAL    Program (49)    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reactive.ReflectionUtils.GetEventMethods[TSender,TEventArgs](Type targetType, Object target, String eventName, MethodInfo& addMethod, MethodInfo& removeMethod, Type& delegateType, Boolean& isWinRT)
   at System.Reactive.Linq.QueryLanguage.FromEventPattern_[TSender,TEventArgs,TResult](Type targetType, Object target, String eventName, Func`3 getResult, IScheduler scheduler) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Events.cs:line 263
   at System.Reactive.Linq.QueryLanguage.FromEventPattern_[TEventArgs](Object target, String eventName, IScheduler scheduler) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Events.cs:line 172
   at System.Reactive.Linq.QueryLanguage.FromEventPattern[TEventArgs](Object target, String eventName) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Events.cs:line 160
   at System.Reactive.Linq.Observable.FromEventPattern[TEventArgs](Object target, String eventName) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable.Events.cs:line 648
   at WalletWasabi.Gui.Controls.WalletExplorer.WalletExplorerViewModel..ctor() in C:\Users\Appcompat\WalletWasabi\WalletWasabi.Gui\Controls\WalletExplorer\WalletExplorerViewModel.cs:line 44
   at lambda_method158(Closure , LifetimeContext , CompositionOperation )
   at System.Composition.Hosting.Core.LifetimeContext.GetOrCreate(Int32 sharingId, CompositionOperation operation, CompositeActivator creator)
   at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext c, CompositionOperation o)
   at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext outermostLifetimeContext, CompositeActivator compositionRootActivator)
   at System.Composition.Hosting.Providers.Lazy.LazyExportDescriptorProvider.<>c__DisplayClass2_2`1.<GetLazyDefinitions>b__4()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AvalonStudio.Shell.ShellViewModel.Initialise(IFactory layoutFactory)
   at AvalonStudio.Shell.Shell.<>c__DisplayClass1_0`1.<StartShellApp>b__0(TAppBuilder _)
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at AvalonStudio.Shell.Shell.StartShellApp[TAppBuilder](TAppBuilder builder, String appName, ShellAppMainDelegate main, String[] args, IFactory layoutFactory)
   at WalletWasabi.Gui.Program.Main(String[] args) in C:\Users\Appcompat\WalletWasabi\WalletWasabi.Gui\Program.cs:line 45
```
Related DevDiv bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1138476

cc @dotnet-actwx-bot

**Comment by danmosemsft** [comment]
@DotNetAppCompatFeiWang I've added triple-ticks above to make the callstack more readable.

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
This is by design. See https://github.com/dotnet/runtime/issues/37672
