### ISSUE TITLE
System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union_NotPipelined times out

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#37698]
[Console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-34948-merge-64bc0d676ac448cd8d/System.Linq.Parallel.Tests/console.ff3e4ec5.log?sv=2019-02-02&se=2020-06-29T20%3A09%3A29Z&sr=c&sp=rl&sig=hmisp8GuEfH9ozxFGIscF8SRrXDoLvpT2gBKr59GGOM%3D) reports: `System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:28:06`. According to Kusto, it seems to be hapenning only on `ubuntu.1804.armarch.open`.

Console.log:
<details>

```
/root/helix/work/workitem /root/helix/work/workitem
  Discovering: System.Linq.Parallel.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Linq.Parallel.Tests (found 588 of 1190 test cases)
  Starting:    System.Linq.Parallel.Tests (parallel test collections = on, max threads = 4)
    System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Concat(source: Partitioner|AsOrdered, operation: Concat-Right:ParallelEnumerable.Range|AsOrdered) [FAIL]
      Assert.Equal() Failure
      Expected: 9
      Actual:   14
      Stack Trace:
        /_/src/libraries/System.Linq.Parallel/tests/Combinatorial/ParallelQueryCombinationTests.cs(151,0): at System.Linq.Parallel.Tests.ParallelQueryCombinationTests.<Concat>g__Concat|119_0(Operation left, Operation right, <>c__DisplayClass119_0& )
        /_/src/libraries/System.Linq.Parallel/tests/Combinatorial/ParallelQueryCombinationTests.cs(157,0): at System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Concat(Labeled`1 source, Labeled`1 operation)
    System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Concat(source: Partitioner|AsOrdered, operation: Concat-Left:ParallelEnumerable.Range|AsOrdered) [FAIL]
      Assert.Equal() Failure
      Expected: 9
      Actual:   10
      Stack Trace:
        /_/src/libraries/System.Linq.Parallel/tests/Combinatorial/ParallelQueryCombinationTests.cs(151,0): at System.Linq.Parallel.Tests.ParallelQueryCombinationTests.<Concat>g__Concat|119_0(Operation left, Operation right, <>c__DisplayClass119_0& )
        /_/src/libraries/System.Linq.Parallel/tests/Combinatorial/ParallelQueryCombinationTests.cs(157,0): at System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Concat(Labeled`1 source, Labeled`1 operation)
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:02:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:04:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:06:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:08:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:10:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:12:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:14:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:16:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:18:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:20:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:22:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:24:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:26:06
   System.Linq.Parallel.Tests: [Long Running Test] 'System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Union', Elapsed: 00:28:06

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 1800 seconds and was killed
```

</details>

Kusto query:
<details>

```
Jobs
| join kind=leftouter WorkItems on JobId
| where FriendlyName == "System.Linq.Parallel.Tests" and Type contains "outerloop" and Status == "Timeout" and Source hassuffix "/master"
| order by Queued desc 
```

</details>

**Comment by stephentoub** [comment]
> According to Kusto, it seems to be hapanning only on ubuntu.1804.armarch.open

Given the parallel nature of the tests, I'm guessing the key piece there is `arm`.
