### ISSUE TITLE
FileNotFoundException w/ ku-TR.UTF-8

### ISSUE THREAD

**Issue by HJLeee** [dotnet/runtime#37778]
### Description
Locale change to/from ku-TR.UTF-8 creates `FileNotFoundException` for TPA when .NET application has ability to detect and update the locale according to the system locale changes.

```
I/DOTNET_LAUNCHER(23387): Unhandled exception.
I/DOTNET_LAUNCHER(23387): System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
I/DOTNET_LAUNCHER(23387):
I/DOTNET_LAUNCHER(23387): File name: 'System.Collections, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
I/DOTNET_LAUNCHER(23387):    at ElmSharp.Window..ctor(Window parent, String name, WindowType type)
I/DOTNET_LAUNCHER(23387):    at Xamarin.Forms.Platform.Tizen.FormsApplication.OnPreCreate()
I/DOTNET_LAUNCHER(23387):    at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
I/DOTNET_LAUNCHER(23387):    at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
I/DOTNET_LAUNCHER(23387):    at Tizen.Applications.CoreApplication.Run(String[] args)
I/DOTNET_LAUNCHER(23387):    at Tizen.Applications.CoreUIApplication.Run(String[] args)
I/DOTNET_LAUNCHER(23387):    at Alarm.Program.Main(String[] args)
I/DOTNET_LAUNCHER(23387):
I/DOTNET_LAUNCHER(23387):
I/DOTNET_LAUNCHER(23387): onSigabrt called
```

It's because in some languages like Turkish, `i` is not converted into `I`  for `toupper()` call.
https://blog.codinghorror.com/whats-wrong-with-turkey/

Checking for all possible locale in a Tizen device, 16 cases are found.
```
Culture: az lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: az upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: az-Cyrl lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: az-Cyrl upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: az-Cyrl-AZ lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: az-Cyrl-AZ upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: az-Latn lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: az-Latn upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: az-Latn-AZ lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: az-Latn-AZ upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: tr lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: tr upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: tr-CY lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: tr-CY upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Culture: tr-TR lower: abcdefghijklmnopqrstuvwxyzabcdefghıjklmnopqrstuvwxyz0123456789.
Culture: tr-TR upper: ABCDEFGH?JKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.
Diff: 16
```

The related code is here.
https://github.com/dotnet/runtime/blob/bbd945ee0e57eb64d27f571e3f6259d692f44798/src/coreclr/src/binder/inc/applicationcontext.hpp#L37-L49
https://github.com/dotnet/runtime/blob/77a383275f1f5dc062a113102856718fe6e8b2ab/src/coreclr/src/inc/utilcode.h#L2931-L2940
The hash function for TPA lookup uses `towupper()` which is not recommanded to use for unicode characters.
https://www.man7.org/linux/man-pages/man3/towupper.3.html#NOTES

Could it be fixed to use `HashString()` for TPA lookup or is there a reason for using case insensitive hash function?

**Comment by vitek-karas** [comment]
This is very likely the same issue as https://github.com/dotnet/runtime/issues/37910 which has some more details on possible fixes.

**Comment by HJLeee** [comment]
Yes it is the same one. Let me participate in #37910. Thank you.
