### ISSUE TITLE
[mono] Type.GetType with generic argument list does not trigger correct exception

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#37871]
I believe the CoreCLR behavior is correct here, given it seems much more useful.

We should probably also update the documentation: [Type.AssemblyQualifiedName](https://docs.microsoft.com/en-us/dotnet/api/system.type.assemblyqualifiedname?view=netcore-3.1) mentions generic argument lists but [Specifying fully qualified type names](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names) does not.

Repro:
```
using System;

namespace HelloWorld
{
    class GenericClass<T> { }
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Type.GetType("HelloWorld.GenericClass`1[[Bogus, BogusAssembly]]", true));
        }
    }
}
```

Output under CoreCLR:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'BogusAssembly, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'BogusAssembly, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at HelloWorld.Program.Main(String[] args) in /Users/ryan/git/runtime/src/mono/netcore/sample/HelloWorld/Program.cs:line 10
```

Output under Mono:
```
Unhandled Exception:
System.TypeLoadException: Could not load type 'HelloWorld.GenericClass`1' from assembly 'HelloWorld, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.RuntimeTypeHandle.GetTypeByName(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, Boolean loadTypeFromPartialName) in /Users/ryan/git/runtime/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeTypeHandle.cs:line 318
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) in /Users/ryan/git/runtime/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 162
   at System.Type.GetType(String typeName, Boolean throwOnError) in /Users/ryan/git/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Type.Mono.cs:line 43
   at HelloWorld.Program.Main(String[] args) in /Users/ryan/git/runtime/src/mono/netcore/sample/HelloWorld/Program.cs:line 10
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'HelloWorld.GenericClass`1' from assembly 'HelloWorld, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.RuntimeTypeHandle.GetTypeByName(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, Boolean loadTypeFromPartialName) in /Users/ryan/git/runtime/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeTypeHandle.cs:line 318
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) in /Users/ryan/git/runtime/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 162
   at System.Type.GetType(String typeName, Boolean throwOnError) in /Users/ryan/git/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Type.Mono.cs:line 43
   at HelloWorld.Program.Main(String[] args) in /Users/ryan/git/runtime/src/mono/netcore/sample/HelloWorld/Program.cs:line 10
```

**Comment by lambdageek** [comment]
This is difficult, probably.  We end up in `mono_class_init_internal` somewhere, probably, and there's no good place to throw an exception in there, so all we can do is mark the type that we're currently creating (a generic instantiation of `HelloWorld.GenericClass<T>`) as failed.

**Comment by lambdageek** [comment]
This would have to be part of a bigger project to propagate a `MonoError` (corresponding to a loader FNFE) out of a `mono_class_init_internal` call.
