### ISSUE TITLE
System.Drawing.Common.Tests fails on iOS, tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#38031]
### System.Drawing.Tests.IconTests
- [ ] Unix_OverflowException_CorruptIcon
```
      <test name="System.Drawing.Tests.IconTests.Unix_OverflowException_CorruptIcon" type="System.Drawing.Tests.IconTests" method="Unix_OverflowException_CorruptIcon" time="0.0079884" result="Fail">
        <failure exception-type="Xunit.Sdk.ThrowsException">
          <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.OverflowException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/Users/mdhwang/Library/Developer/CoreSimulator/Devices/AB8A2904-AD12-4CCD-9072-445DC2401264/data/Containers/Bundle/Application/53FE9AB4-5A03-4E18-9E58-1D2E27F6F43E/System.Drawing.Common.Tests.app/bitmaps/overflowicon.ico'.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/Users/mdhwang/Library/Developer/CoreSimulator/Devices/AB8A2904-AD12-4CCD-9072-445DC2401264/data/Containers/Bundle/Application/53FE9AB4-5A03-4E18-9E58-1D2E27F6F43E/System.Drawing.Common.Tests.app/bitmaps/overflowicon.ico'.]]></message>
          <stack-trace><![CDATA[   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at System.Drawing.Icon..ctor(String fileName)
   at System.Drawing.Tests.IconTests.<>c.<Unix_OverflowException_CorruptIcon>b__1_0()
----- Inner Stack Trace -----
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at System.Drawing.Icon..ctor(String fileName)
   at System.Drawing.Tests.IconTests.<>c.<Unix_OverflowException_CorruptIcon>b__1_0()]]></stack-trace>
        </failure>
      </test>
```

**Comment by filipnavara** [comment]
Caused by #52104.
