### ISSUE TITLE
[WASM]: Task.Yield results in runtime exception

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#38098]
```C#
System.PlatformNotSupportedException: Cannot start threads on this runtime.
at System.Threading.Thread.Start()
at System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread()
at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker()
at System.Threading.PortableThreadPool.RequestWorker()
at System.Threading.ThreadPool.RequestWorkerThread()
at System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested()
at System.Threading.ThreadPoolWorkQueue.Enqueue(Object callback, Boolean forceGlobal)
at System.Threading.ThreadPool.QueueUserWorkItem(WaitCallback callBack, Object state)
at System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AwaitUnsafeOnCompleted[YieldAwaiter](YieldAwaiter& awaiter, IAsyncStateMachineBox box)
```
Runtime version: 5.0.0-preview.7.20317.2+fa7c99d6b2538591edf609b8d3a5f321f9ee7850

**Comment by pranavkm** [comment]
One more of these on a different code path:

```
System.PlatformNotSupportedException: Cannot start threads on this runtime.
at System.Threading.Thread.Start()
at System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread()
at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker()
at System.Threading.PortableThreadPool.RequestWorker()
at System.Threading.ThreadPool.RequestWorkerThread()
at System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested()
at System.Threading.ThreadPoolWorkQueue.Enqueue(Object callback, Boolean forceGlobal)
at System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal(Object callBack, Boolean preferLocal)
at System.Threading.TimerQueue.FireNextTimers()
at System.Threading.TimerQueue.Run()
at System.Threading.TimerQueue.TimeoutCallback()
```

**Comment by pranavkm** [comment]
`Task.Run`:

```
System.PlatformNotSupportedException: Cannot start threads on this runtime.
   at System.Threading.Thread.Start()
   at System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread()
   at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker()
   at System.Threading.PortableThreadPool.RequestWorker()
   at System.Threading.ThreadPool.RequestWorkerThread()
   at System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested()
   at System.Threading.ThreadPoolWorkQueue.Enqueue(Object callback, Boolean forceGlobal)
   at System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal(Object callBack, Boolean preferLocal)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.Task, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.Task, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].StartNew(Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.Task.Run(Func`1 function, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Run(Func`1 function)
```

**Comment by pranavkm** [comment]
Something I just noticed, is there a reason generic type names are assembly qualified? I don't see this in .NET Core.

**Comment by pranavkm** [comment]
TCS.SetResult
```
 ---> System.PlatformNotSupportedException: Cannot start threads on this runtime.
at System.Threading.Thread.Start()
at System.Threading.PortableThreadPool.WorkerThread.TryCreateWorkerThread()
at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker()
at System.Threading.PortableThreadPool.RequestWorker()
at System.Threading.ThreadPool.RequestWorkerThread()
at System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested()
at System.Threading.ThreadPoolWorkQueue.Enqueue(Object callback, Boolean forceGlobal)
at System.Threading.ThreadPool.QueueUserWorkItem(WaitCallback callBack, Object state)
at System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
at System.Threading.Tasks.Task.FinishContinuations()
at System.Threading.Tasks.Task`1[[Wasm.Authentication.Client.OidcAccount, Wasm.Authentication.Client, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TrySetResult(OidcAccount result)
at System.Threading.Tasks.TaskCompletionSource`1[[Wasm.Authentication.Client.OidcAccount, Wasm.Authentication.Client, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TrySetResult(OidcAccount result)
at System.Threading.Tasks.TaskCompletionSource`1[[Wasm.Authentication.Client.OidcAccount, Wasm.Authentication.Client, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].SetResult(OidcAccount result)
```

**Comment by pranavkm** [comment]
FYI, I marked this issue as blocking. In particular, `TaskCompletionSource.SetResult` shows up very frequently in Blazor's code paths. It would be great to fix the other APIs but that one in particular would be a blocker for a preview7 release.

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/38029 should fix this.  Waiting for testing to confirm.
