### ISSUE TITLE
BinderTracingTest.ResolutionFlow.cmd failing with EventSourceException

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#38121]
Similar to https://github.com/dotnet/runtime/issues/37132, but throws exception in ETW listener.

```
   Loader\binding\tracing\BinderTracingTest.ResolutionFlow\BinderTracingTest.ResolutionFlow.cmd [FAIL]
      
      
      
      
      
      Return code:      1
      Raw output file:      D:\h\w\B7CF0A15\w\B70009E0\e\Loader\binding\Reports\Loader.binding\tracing\BinderTracingTest.ResolutionFlow\BinderTracingTest.ResolutionFlow.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\B7CF0A15\p\corerun.exe" BinderTracingTest.ResolutionFlow.dll 
      [2:12:17 PM] Launching process for AppDomainAssemblyResolveEvent_Exception...
      [2:12:17 PM] Running AppDomainAssemblyResolveEvent_Exception...
      
      [2:12:18 PM] Launching process for LoadFromAssemblyPath_FoundInAppPath...
      [2:12:18 PM] Running LoadFromAssemblyPath_FoundInAppPath...
      
      [2:12:19 PM] Launching process for LoadFromAssemblyPath_FoundInLoadContext_DifferentMvid...
      [2:12:19 PM] Running LoadFromAssemblyPath_FoundInLoadContext_DifferentMvid...
      
      [2:12:20 PM] Launching process for LoadFromAssemblyPath_FoundInAppPath_IncompatibleVersion...
      [2:12:20 PM] Running LoadFromAssemblyPath_FoundInAppPath_IncompatibleVersion...
      
      [2:12:21 PM] Running AssemblyLoadContextResolving_ReturnNull...
      Test AssemblyLoadContextResolving_ReturnNull failed: System.AggregateException: One or more errors occurred. (An error occurred when writing to a listener.)
       ---> System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
       ---> TestLibrary.AssertTestException: Assert.Fail: KnownPathProbed (ActivityId: 00000000-0000-0000-0000-000000000000) should have a matching AssemblyBindStart
      Parsed event: D:\h\w\B7CF0A15\p\system.componentmodel.dll - Source=ApplicationAssemblies, Result=0
      Received events:
      
      
         at TestLibrary.Assert.HandleFail(String assertionName, String message) in /Users/runner/runners/2.170.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 735
         at TestLibrary.Assert.Fail(String message, Object[] args) in /Users/runner/runners/2.170.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 722
         at BinderTracingTests.BinderEventListener.OnEventWritten(EventWrittenEventArgs data) in /Users/runner/runners/2.170.1/work/1/s/src/coreclr/tests/src/Loader/binding/tracing/BinderEventListener.cs:line 319
         at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
         --- End of inner exception stack trace ---
         at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
         at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, UInt32* osThreadId, DateTime* timeStamp, Guid* activityID, Guid* childActivityID, Object[] args)
         at System.Diagnostics.Tracing.EventPipeEventDispatcher.DispatchEventsToEventListeners()
         at System.Threading.Tasks.Task.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
         at System.Threading.Tasks.Task.Wait()
         at System.Diagnostics.Tracing.EventPipeEventDispatcher.StopDispatchTask()
         at System.Diagnostics.Tracing.EventPipeEventDispatcher.CommitDispatchConfiguration()
         at System.Diagnostics.Tracing.EventPipeEventDispatcher.RemoveEventListener(EventListener listener)
         at System.Diagnostics.Tracing.EventListener.RemoveReferencesToListenerInEventSources(EventListener listenerToRemove)
         at System.Diagnostics.Tracing.EventListener.Dispose()
         at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method) in /Users/runner/runners/2.170.1/work/1/s/src/coreclr/tests/src/Loader/binding/tracing/BinderTracingTest.cs:line 161
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\B7CF0A15\p
      > D:\h\w\B7CF0A15\w\B70009E0\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\BinderTracingTest.ResolutionFlow.cmd
      Expected: True
      Actual:   False
```

This was also on Windows arm:
https://helix.dot.net/api/2019-06-17/jobs/8a4f9abf-406e-4cb3-8705-b478fbced97c/workitems/PayloadGroup0/console

**Comment by safern** [comment]
Failed again:

https://helix.dot.net/api/2019-06-17/jobs/aaa5da96-04eb-420c-97e0-b473ba11ec63/workitems/PayloadGroup0/console

**Comment by safern** [comment]
cc: @elinor-fung @vitek-karas

**Comment by tommcdon** [comment]
@elinor-fung @vitek-karas please let us know if any assistance is needed
cc @sywhang @josalem
