### ISSUE TITLE
[WASM] Environment.UserName raises "not supported" exception

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#38164]
**Update:** UserName now fails with `System.IO.IOException : Not supported`

~~This is causing `System.Runtime.Extensions.Tests` to crash.~~

~~Crashes with:~~
<details>
```
at 205708 (dotnet.js:1858:32)
    at _emscripten_asm_const_iii (dotnet.js:1863:27)
    at wasm_logger (<anonymous>:wasm-function[7791]:0x1f3d0d)
    at eglib_log_adapter (<anonymous>:wasm-function[6303]:0x1abc50)
    at monoeg_g_logstr (<anonymous>:wasm-function[7225]:0x1ced8d)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[7223]:0x1cecb4)
    at monoeg_g_logv (<anonymous>:wasm-function[7222]:0x1cec11)
    at monoeg_g_log (<anonymous>:wasm-function[7226]:0x1ceded)
    at getpwuid_r (<anonymous>:wasm-function[1131]:0x6e9e5)
    at SystemNative_GetPwUidR (<anonymous>:wasm-function[7726]:0x1effbc)
```
</details>

~~I guess this API should throw PNSE in WASM?~~

Will disable the tests against this issue in the meantime. 

cc: @steveisok @lewing @marek-safar @akoeplinger

**Comment by akoeplinger** [comment]
Looks like on Xamarin iOS/Android we returned a dummy "somebody" string from Environment.UserName.

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/pull/38256 fixed the crash but we're still reporting `System.IO.IOException : Not supported` from the property so we still need to fix that.

**Comment by safern** [comment]
Also, the test should be re-enabled or skipped without ActiveIssue before we close the issue. 

https://github.com/dotnet/runtime/blob/4aef3cc24e6394a6656de866236ea5bc800543dc/src/libraries/System.Runtime.Extensions/tests/System/Environment.UserName.cs#L9
