### ISSUE TITLE
Test failure: Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#38205]
failed in job: [runtime-libraries outerloop 20200621.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=697688&view=ms.vss-test-web.build-test-results-tab&runId=21622464&resultId=103147&paneView=debug)

failed tests:
System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceActivityLogging_InvalidBaggage
System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.AggregateException: One or more errors occurred. (Assert.False() Failure
Expected: False
Actual:   True)
 ---> Xunit.Sdk.FalseException: Assert.False() Failure
Expected: False
Actual:   True
   at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c__DisplayClass14_0.<SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader>b__1(KeyValuePair`2 kvp) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 576
   at System.Net.Http.Functional.Tests.FakeDiagnosticListenerObserver.FakeDiagnosticSourceWriteObserver.OnNext(KeyValuePair`2 value) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/FakeDiagnosticSourceListenerObserver.cs:line 31
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value) in /_/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs:line 262
   at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args) in /_/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceActivity.cs:line 51
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs:line 129
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 533
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 471
   at System.Threading.Tasks.Task`1.get_Result() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 440
   at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c.<SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader>b__14_0(String useVersionString) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 587

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.DiagnosticsTest+<>c Void <SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader>b__14_0(System.String)

Child arguments:
  1.1
~~~

**Comment by stephentoub** [comment]
@tarekgh, might this outerloop failure be related to some of your Activity changes?

**Comment by tarekgh** [comment]
@stephentoub I am not seeing any direct relation between this failure and my changes. this looks more an HTTP issue. 

cc @noahfalk

**Comment by ManickaP** [comment]
First occurrence seems to be from this build: https://dev.azure.com/dnceng/public/_build/results?buildId=695914&view=results, i.e. Friday 19.6. It happened between [this](https://github.com/dotnet/runtime/commit/8dd3619c4fcb0cf0be05f545eb74992708b7f279) and [this](https://github.com/dotnet/runtime/commit/9a323d72d9ffbcbaf978425fa90f742270d631b6) commits. According to System.Net.Http history, it doesn't seem like it comes from there, there's been 2 changes only: [#38065](https://github.com/dotnet/runtime/commit/29e0165eac74b78bd49d326f0be0345a00774f35) and [#35011](https://github.com/dotnet/runtime/commit/3ace198426582bd154569798942591b31ad1425f).

**Comment by ManickaP** [comment]
Two places where it fails:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs#L511
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs#L576

**Comment by stephentoub** [comment]
@tarekgh, this is due to your change https://github.com/dotnet/runtime/commit/c5edc006987847b15741576cbcfddd42e6f87768.

**Comment by tarekgh** [comment]
Thanks, @stephentoub. I'll try to look more later on how these are connected.

**Comment by tarekgh** [comment]
I discovered that the HTTP request will set the fields `transparent` and `tracestate` to the header if the Activity Id Format is W3C which we make default now. that is why the test is failing. I'll submit the test fix soon.
