### ISSUE TITLE
Improve error handling in Android test runner

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#38213]
During the android test run, sometimes the instrumentation task will crash due to some kind of unhandled android exception.  We should improve the error handling within `MonoRunner.java` to handle errors gracefully.

An example of an unhandled exception that will see:

```
6-17 09:07:45.660  3485  3506 I DOTNET  : Tests run: 1194 Passed: 1191 Inconclusive: 0 Failed: 3 Ignored: 0
06-17 09:07:45.667  3485  3506 I DOTNET  : ----- Done -----
06-17 09:07:45.683  3485  3503 D DOTNET  : Exit code: 0.
06-17 09:07:45.685  1791  2286 I ActivityManager: Force stopping net.dot.System.Numerics.Vectors.Tests appid=10104 user=0: finished inst
06-17 09:07:45.686  1791  2286 I ActivityManager: Killing 3485:net.dot.System.Numerics.Vectors.Tests/u0a104 (adj 0): stop net.dot.System.Numerics.Vectors.Tests
06-17 09:07:45.698  1791  3514 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
06-17 09:07:45.698  1791  3514 W Binder  : java.lang.Throwable
06-17 09:07:45.698  1791  3514 W Binder  :     at android.os.BinderProxy.transact(BinderProxy.java:480)
06-17 09:07:45.698  1791  3514 W Binder  :     at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
06-17 09:07:45.698  1791  3514 W Binder  :     at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
06-17 09:07:45.705  1791  1815 E memtrack: Couldn't load memtrack module
06-17 09:07:45.705  1791  1815 W android.os.Debug: failed to get memory consumption info: -1
06-17 09:07:45.724  1533  1533 I Zygote  : Process 3485 exited due to signal 9 (Killed)
06-17 09:07:45.728  3474  3474 D AndroidRuntime: Shutting down VM
06-17 09:07:45.732  1791  1818 I libprocessgroup: Successfully killed process cgroup uid 10104 pid 3485 in 44ms
06-17 09:07:45.757  1791  3514 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{net.dot.System.Numerics.Vectors.Tests/net.dot.MonoRunner} results=Bundle[mParcelledData.dataSize=296]
```

**Comment by steveisok** [comment]
@MattGal Looking at this again.... I have a hard suspicion that the emulator is running out of memory when this happens.  How much ram are the emulators configured with?

/cc @directhex @akoeplinger

**Comment by MattGal** [comment]
Hi @steveisok :

- Machines they're running on currently are D2_v3, which has 8 GB of RAM.   This will change to a similar AMD EPYC chipset SKU some time in the near future but RAM should not change.

- Configuration script is here: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=%2Fartifacts%2Flinux-ubuntu-android-emulator%2Flinux-ubuntu-android-emulator.sh and I see no settings for RAM usage; if you have suggestions for stuff to add it's an easy PR

**Comment by steveisok** [comment]
I created the same emulators local.  Both have `hw.ramSize=96M`.

**Comment by ViktorHofer** [comment]
Closing as potential memory issues have been mitigated.
