### ISSUE TITLE
dotnet run --no-build does not work when the `platform` environment variable is set

### ISSUE THREAD

**Issue by vincentkam** [dotnet/runtime#38274]
### Description
If the environment variable `platform` is set in Powershell, `dotnet run --no-build` errors out with the following message like so:

```
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> dotnet run --no-restore --no-build
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
A minimal repro can be created like so:
```
PS C:\Users\Vincent\scratch> dotnet new console -n "dotnet-platform-env-var-test"
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on dotnet-platform-env-var-test\dotnet-platform-env-var-test.csproj...
  Determining projects to restore...
  Restored C:\Users\Vincent\scratch\dotnet-platform-env-var-test\dotnet-platform-env-var-test.csproj (in 89 ms).

Restore succeeded.

PS C:\Users\Vincent\scratch> cd .\dotnet-platform-env-var-test\
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> $env:platform=""
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> dotnet run
Hello World!
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> $env:platform="foo"
PS C:\Users\Vincent\scratch\dotnet-platform-env-var-test> dotnet run --no-build
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

The work around of course, is to simply unset the environment variable. However, it would be nice to be able to specify the platform without needing to set/unset an environment variable. For example, `dotnet build` sort of supports this via: 
`dotnet build /p:Platform="Any CPU"`
By passing the argument above, `dotnet build` ignores the `platform` environment variable when building.

### Configuration
I've seen this behavior using the following `dotnet` versions:
`5.0.100-preview.3.20216.6` 
`3.1.201` 

The same behavior occurs on Windows 10 and Windows Server 2016.

**Comment by jeffschwMSFT** [comment]
@marcpopMSFT is this a CLI issue?

**Comment by marcpopMSFT** [comment]
Issue moved to [dotnet/sdk #12159](https://github.com/dotnet/sdk/issues/12159) via [**ZenHub**](https://www.zenhub.com/)
