### ISSUE TITLE
CG2/Composite: BinderTracingTest.ResolutionFlow.cmd - FileLoadException in LoadFromAssemblyPath_FoundInAppPath

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#38290]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=699843&view=ms.vss-test-web.build-test-results-tab&runId=21699982&resultId=102428&paneView=attachments

Platform:

Windows x64, arm64 (all architectures currently supported by Crossgen2)

Diagnostics:

<pre>
[7:04:02 AM] Launching process for LoadFromAssemblyPath_FoundInAppPath...
[7:04:03 AM] Running LoadFromAssemblyPath_FoundInAppPath...
Test LoadFromAssemblyPath_FoundInAppPath failed: System.IO.FileLoadException: Could not load file or assembly 'AssemblyToLoad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at BinderTracingTests.BinderTracingTest.LoadFromAssemblyPath_FoundInAppPath() in /Users/runner/runners/2.170.1/work/1/s/src/coreclr/tests/src/Loader/binding/tracing/BinderTracingTest.ResolutionFlow.cs:line 587
   at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method) in /Users/runner/runners/2.170.1/work/1/s/src/coreclr/tests/src/Loader/binding/tracing/BinderTracingTest.cs:line 159
</pre>

**Comment by mangod9** [comment]
Moving to 6 since this is a corner case.
