### ISSUE TITLE
CG2/Composite: baseservices\TieredCompilation\BasicTest_QuickJitOff_R2r\BasicTest_QuickJitOff_R2r.cmd fails to compile

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#38291]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=699843&view=ms.vss-test-web.build-test-results-tab&runId=21699982&resultId=102305&paneView=attachments

Platform: all

Diagnostics:

<pre>
Error: Module with same simple name already exists C:\h\w\BE120A59\w\A05F08BC\e\baseservices\TieredCompilation\BasicTest_QuickJitOff_R2r\IL\BasicTest_QuickJitOff_R2r.ni.dll
System.IO.FileNotFoundException: Module with same simple name already exists C:\h\w\BE120A59\w\A05F08BC\e\baseservices\TieredCompilation\BasicTest_QuickJitOff_R2r\IL\BasicTest_QuickJitOff_R2r.ni.dll
   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding) in /_/src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 220
   at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding) in /_/src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 146
   at ILCompiler.CompilerTypeSystemContext.GetModuleFromPath(String filePath) in /_/src/coreclr/src/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 129
   at ILCompiler.Program.Run() in /_/src/coreclr/src/tools/aot/crossgen2/Program.cs:line 315
   at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) in /_/src/coreclr/src/tools/aot/crossgen2/Program.cs:line 648
</pre>

**Comment by trylek** [comment]
Hits 5 tests total:

<pre>
baseservices\TieredCompilation\BasicTest_QuickJitOff_R2r\BasicTest_QuickJitOff_R2r.cmd
baseservices\TieredCompilation\BasicTest_DefaultMode_R2r\BasicTest_DefaultMode_R2r.cmd
baseservices\TieredCompilation\BasicTest_QuickJitForLoopsOn_R2r\BasicTest_QuickJitForLoopsOn_R2r.cmd
baseservices\TieredCompilation\BasicTest_QuickJitForLoopsOff_R2r\BasicTest_QuickJitForLoopsOff_R2r.cmd
baseservices\TieredCompilation\BasicTest_QuickJitOn_R2r\BasicTest_QuickJitOn_R2r.cmd
</pre>

**Comment by davidwrighton** [comment]
These tests all explicitly run the crossgen compiler, and are incompatible with our current technique for crossgen2 testing. We'll need to revisit them in .NET 6, when we remove crossgen, but for now we can just punt the bug to 6.0.

**Comment by mangod9** [comment]
closing since crossgen is removed.
