### ISSUE TITLE
Microsoft.Extensions.Logging.Tests fail on WASM with an assertion in mono_exception_new_by_name_domain

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#38337]
Some tests in Microsoft.Extensions.Logging.Tests fail with an assertion:

```
Microsoft.Extensions.Logging.Test.ConsoleLoggerTest.ConsoleLoggerOptions_IncludeScopes_IsReadFromLoggingConfiguration

        Stacktrace:
        Error
            at 194359 (dotnet.js:1858:32)
            at _emscripten_asm_const_iii (dotnet.js:1863:27)
            at wasm_logger (<anonymous>:wasm-function[7792]:0x1ef32e)
            at eglib_log_adapter (<anonymous>:wasm-function[6304]:0x1a71bf)
            at monoeg_g_logstr (<anonymous>:wasm-function[7226]:0x1ca2fc)
            at monoeg_g_logv_nofree (<anonymous>:wasm-function[7224]:0x1ca223)
            at monoeg_assertion_message (<anonymous>:wasm-function[7228]:0x1ca3af)
            at mono_exception_new_by_name_domain (<anonymous>:wasm-function[2195]:0xb3b8f)
            at mono_exception_new_by_name (<anonymous>:wasm-function[2205]:0xb4790)
            at mono_exception_new_by_name_msg (<anonymous>:wasm-function[2204]:0xb450f)

        WASM-ERR: * Assertion at /Users/alexander/dev/runtime/src/mono/mono/metadata/exception.c:109, condition `is_ok (error)' not met, function:mono_exception_new_by_name_domain, (null) assembly:System.Private.CoreLib.dll type:PlatformNotSupportedException member:(null)
        WASM-ERR:
        ABORT: undefined
        Stacktrace:
        Error
            at Object.onAbort (runtime.js:160:13)
            at abort (dotnet.js:1643:22)
            at _abort (dotnet.js:6101:7)
            at wasm_logger (<anonymous>:wasm-function[7792]:0x1ef350)
            at eglib_log_adapter (<anonymous>:wasm-function[6304]:0x1a71bf)
            at monoeg_g_logstr (<anonymous>:wasm-function[7226]:0x1ca2fc)
            at monoeg_g_logv_nofree (<anonymous>:wasm-function[7224]:0x1ca223)
            at monoeg_assertion_message (<anonymous>:wasm-function[7228]:0x1ca3af)
            at mono_exception_new_by_name_domain (<anonymous>:wasm-function[2195]:0xb3b8f)
            at mono_exception_new_by_name (<anonymous>:wasm-function[2205]:0xb4790)
```

The problematic tests were disabled so to reproduce it you need to remove https://github.com/dotnet/runtime/blob/cd4c4c99ba438866584e5265fc9c248dd40bbeb1/src/libraries/Microsoft.Extensions.Logging/tests/Common/LoggerFactoryTest.cs#L202

**Comment by lambdageek** [comment]
I think this is due to 
https://github.com/dotnet/runtime/blob/54d9241a344a6722e188d209b9f72a621207ca99/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/DynamicServiceProviderEngine.cs#L25

The dynamic service provider engine is created by 

https://github.com/dotnet/runtime/blob/54d9241a344a6722e188d209b9f72a621207ca99/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs#L37-L49

It's possible that we can pass some options too the logger factory to create a different kind of service provider engine that might work on wasm.  Not sure

https://github.com/dotnet/runtime/blob/54d9241a344a6722e188d209b9f72a621207ca99/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs#L94-L101

**Comment by lambdageek** [comment]
Longer stack trace:

```
  dbug: test[0]
        WASM-ERR: * Assertion at /Users/alklig/work/dotnet-runtime/hask-wasm/src/mono/mono/metadata/exception.c:109, condition `is_ok (error)' not met, function:mono_exception_new_by_name_domain, (null) assembly:System.Private.CoreLib.dll type:ArgumentException member:(null)
  dbug: test[0]
        WASM-ERR:
  dbug: test[0]
        ABORT: undefined
  dbug: test[0]
        Stacktrace:
  dbug: test[0]
  dbug: test[0]
        Error
  dbug: test[0]
            at Object.onAbort (runtime.js:160:13)
  dbug: test[0]
            at abort (dotnet.js:1643:22)
  dbug: test[0]
            at _abort (dotnet.js:6101:7)
  dbug: test[0]
            at wasm_logger (<anonymous>:wasm-function[8190]:0x207e5c)
  dbug: test[0]
            at eglib_log_adapter (<anonymous>:wasm-function[6345]:0x1adec1)
  dbug: test[0]
            at monoeg_g_logstr (<anonymous>:wasm-function[7267]:0x1d0ffe)
  dbug: test[0]
            at monoeg_g_logv_nofree (<anonymous>:wasm-function[7265]:0x1d0f25)
  dbug: test[0]
            at monoeg_assertion_message (<anonymous>:wasm-function[7269]:0x1d10b1)
  dbug: test[0]
            at mono_exception_new_by_name_domain (<anonymous>:wasm-function[2216]:0xb50b4)
  dbug: test[0]
            at mono_exception_new_by_name (<anonymous>:wasm-function[2226]:0xb5cb5)
  dbug: test[0]
            at mono_exception_new_by_name_msg (<anonymous>:wasm-function[2225]:0xb5a34)
  dbug: test[0]
            at mono_error_prepare_exception (<anonymous>:wasm-function[6278]:0x1aafed)
  dbug: test[0]
            at mono_error_convert_to_exception (<anonymous>:wasm-function[6285]:0x1ab5c7)
  dbug: test[0]
            at mono_error_convert_to_exception_handle (<anonymous>:wasm-function[2261]:0xb7789)
  dbug: test[0]
            at mono_error_set_pending_exception_slow (<anonymous>:wasm-function[2260]:0xb768c)
  dbug: test[0]
            at mono_error_set_pending_exception.6 (<anonymous>:wasm-function[3767]:0x1153a4)
  dbug: test[0]
            at mono_monitor_ensure_owned (<anonymous>:wasm-function[3777]:0x115d80)
  dbug: test[0]
            at mono_monitor_exit_internal (<anonymous>:wasm-function[3776]:0x115c6b)
  dbug: test[0]
            at mono_monitor_exit_icall (<anonymous>:wasm-function[3787]:0x116073)
  dbug: test[0]
            at mono_monitor_exit_icall_raw (<anonymous>:wasm-function[2959]:0xe45cf)
  dbug: test[0]
            at do_icall (<anonymous>:wasm-function[230]:0x1f496)
  dbug: test[0]
            at do_icall_wrapper (<anonymous>:wasm-function[190]:0x1d3f1)
  dbug: test[0]
            at interp_exec_method (<anonymous>:wasm-function[142]:0x75ef)
  dbug: test[0]
            at interp_run_finally (<anonymous>:wasm-function[151]:0x1b36c)
  dbug: test[0]
            at mono_handle_exception_internal (<anonymous>:wasm-function[615]:0x50b6c)
  dbug: test[0]
            at mono_handle_exception (<anonymous>:wasm-function[584]:0x4d20b)
  dbug: test[0]
            at interp_throw (<anonymous>:wasm-function[187]:0x1d25e)
  dbug: test[0]
            at interp_exec_method (<anonymous>:wasm-function[142]:0x7647)
  dbug: test[0]
            at interp_runtime_invoke (<anonymous>:wasm-function[140]:0x5876)
  dbug: test[0]
            at mono_jit_runtime_invoke (<anonymous>:wasm-function[909]:0x61f6c)
  dbug: test[0]
            at do_runtime_invoke (<anonymous>:wasm-function[4031]:0x128058)
  dbug: test[0]
            at mono_runtime_invoke_checked (<anonymous>:wasm-function[4029]:0x127f11)
  dbug: test[0]
            at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4160]:0x130cfe)
  dbug: test[0]
            at mono_runtime_invoke_array_checked (<anonymous>:wasm-function[4163]:0x131452)
  dbug: test[0]
            at ves_icall_InternalInvoke (<anonymous>:wasm-function[2564]:0xca9c4)
  dbug: test[0]
            at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[2840]:0xde069)
  dbug: test[0]
            at do_icall (<anonymous>:wasm-function[230]:0x1f670)
  dbug: test[0]
            at do_icall_wrapper (<anonymous>:wasm-function[190]:0x1d3f1)
  dbug: test[0]
            at interp_exec_method (<anonymous>:wasm-function[142]:0x75ef)
  dbug: test[0]
            at interp_runtime_invoke (<anonymous>:wasm-function[140]:0x5876)
  dbug: test[0]
            at mono_jit_runtime_invoke (<anonymous>:wasm-function[909]:0x61f6c)
  dbug: test[0]
            at do_runtime_invoke (<anonymous>:wasm-function[4031]:0x128058)
  dbug: test[0]
            at mono_runtime_try_invoke (<anonymous>:wasm-function[4046]:0x128cf3)
  dbug: test[0]
            at mono_runtime_invoke (<anonymous>:wasm-function[4103]:0x12d0bd)
  dbug: test[0]
            at mono_wasm_invoke_method (<anonymous>:wasm-function[8186]:0x207c3e)
  dbug: test[0]
            at dotnet.js:1711:22
  dbug: test[0]
            at ccall (dotnet.js:751:18)
  dbug: test[0]
            at dotnet.js:763:12
  dbug: test[0]
            at Object.init (runtime.js:366:15)
  dbug: test[0]
            at runtime.js:245:9
  dbug: test[0]
            at dotnet.js:7240:9
```

**Comment by lambdageek** [comment]
Some printf debugging shows that indeed we don't own the lockword on some monitor:
```
small id 64, lock word owner was 0
```

The initial part of the managed stack looks like this by the time we try to do the monitor exit:
```
L: Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver:VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite,Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope,Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver:VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite,Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2<Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, object>:VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite,Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver:Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine/<>c__DisplayClass1_0:<RealizeService>b__1 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine/<>c__DisplayClass1_0:<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine:GetService (System.Type,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine:GetService (System.Type)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceProvider:GetService (System.Type)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions:GetRequiredService (System.IServiceProvider,System.Type)
  dbug: test[0]
        L: Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions:GetRequiredService<Microsoft.Extensions.Logging.ILoggerProvider> (System.IServiceProvider)
  dbug: test[0]
        L: Microsoft.Extensions.Logging.Test.ConsoleLoggerTest:ConsoleLoggerOptions_DisableColors_IsReadFromLoggingConfiguration ()
  dbug: test[0]
        L: System.Reflection.RuntimeMethodInfo:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
```

**Comment by lambdageek** [comment]
Current theory is that we call `Monitor.Exit` too many times, somehow.  Because all the `Enter` calls definitely own the monitor object.

**Comment by vargaz** [comment]
Testcase:
```
using System;
using System.Reflection;

public class Test
{
    public static void foo4 () {
        throw new Exception ();
    }

    public static void Main (String[] args) {
        try {
            foo3 ();
        } catch (Exception) {
        }
        Console.WriteLine (count);
    }

    static int count;

    public static void foo3 () {
        try {
            typeof (Test).GetMethod ("foo4").Invoke (null, BindingFlags.DoNotWrapExceptions, null, null, null);
        } finally {
            count ++;
        }
    }
}
```

This will print '2' under wasm, which means the finally clause is executed twice.

**Comment by vargaz** [comment]
It doesn't fail under the desktop interpreter, only on wasm.

**Comment by vargaz** [comment]
This happens because of differences in EH implementation on wasm. wasm hits this codepath:

#if defined (MONO_CROSS_COMPILE) || defined (HOST_WASM)
#define INTERP_PUSH_LMF_WITH_CTX_BODY(ext, exit_label) \
	(ext).kind = MONO_LMFEXT_INTERP_EXIT;

So after this call in interp_runtime_invoke ():

	interp_exec_method (&frame, context, NULL);

This codepath is hit only on wasm:
	if (context->has_resume_state) {
         }

That if block doesn't seem to do the right thing, which caused the problem.

**Comment by vargaz** [comment]
This will probably fail with a PNSE now.

**Comment by vargaz** [comment]
Should be fixed.
