### ISSUE TITLE
System.Runtime.Serialization.Formatters.Binary.Converter threw and exception

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#38443]
When running tests for WebAssembly, some test suites (System.Threading.Channels.Tests and System.Collections and possibly more) encounter this failure from `System.Runtime.Serialization.Formatters.Binary.Converter`. 
```
<test name="System.Threading.Channels.Tests.ChannelClosedExceptionTests.Serialization_Roundtrip" type="System.Threading.Channels.Tests.ChannelClosedExceptionTests" method="Serialization_Roundtrip" time="0.0124249" result="Fail">
  <failure exception-type="System.TypeInitializationException">
    <message><![CDATA[System.TypeInitializationException : The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.\n---- System.IO.FileNotFoundException : ]]></message>
    <stack-trace><![CDATA[   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      ----- Inner Stack Trace -----
      at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
      at System.Reflection.Assembly.Load(String assemblyString)
      at System.Runtime.Serialization.Formatters.Binary.Converter..cctor()]]></stack-trace>
  </failure>
</test>
```

**Comment by mdh1418** [comment]
This falls under #37648
