### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientTest.Send_CancelledRequestContent_Throws

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#38497]
failed in job: [runtime-libraries outerloop 20200627.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=707650&view=ms.vss-test-web.build-test-results-tab&runId=21923082&resultId=104253&paneView=debug)

Error message
~~~
Assert.IsNotType() Failure
Expected: typeof(System.TimeoutException)
Actual: typeof(System.TimeoutException)


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass46_0.<<Send_CancelledRequestContent_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 850
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 84
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 69
   at System.Net.Http.Functional.Tests.HttpClientTest.Send_CancelledRequestContent_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 831
--- End of stack trace from previous location ---
~~~

**Comment by ManickaP** [comment]
Addressed in https://github.com/dotnet/runtime/pull/38453
