### ISSUE TITLE
Many installer tests are failing because of Directory.Build.props file is missing

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#38530]
failed in job: [runtime 20200628.29 ](https://dev.azure.com/dnceng/public/_build/results?buildId=708726&view=ms.vss-test-web.build-test-results-tab&runId=21951024&resultId=100000&paneView=debug)

failed tests:
Bundle_can_be_renamed_while_running
Bundled_Localized_App_Run_Succeeds
Can_Run_App_With_StatiHost
Can_Run_SingleFile_App_With_StatiHost

Error message
~~~
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net5.0 /p:NetCoreAppCurrent=net5.0 -o /root/runtime/artifacts/tests/Release/ahb/0/AppWithWait/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=5.0.0-ci
Standard Output:
Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/root/runtime/.dotnet/sdk/5.0.100-preview.6.20310.4/MSBuild.dll -maxcpucount -property:RuntimeIdentifier=linux-x64 -property:TargetFramework=net5.0 -property:PublishDir=/root/runtime/artifacts/tests/Release/ahb/0/AppWithWait/publish /p:NetCoreAppCurrent=net5.0 /p:TestTargetRid=linux-x64 /p:MNAVersion=5.0.0-ci -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithWait.csproj
/root/runtime/.dotnet/sdk/5.0.100-preview.6.20310.4/Current/Microsoft.Common.props(32,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/ahb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/ahb/0/AppWithWait/AppWithWait.csproj]

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net5.0 /p:NetCoreAppCurrent=net5.0 -o /root/runtime/artifacts/tests/Release/ahb/0/AppWithWait/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=5.0.0-ci
Standard Output:
Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/root/runtime/.dotnet/sdk/5.0.100-preview.6.20310.4/MSBuild.dll -maxcpucount -property:RuntimeIdentifier=linux-x64 -property:TargetFramework=net5.0 -property:PublishDir=/root/runtime/artifacts/tests/Release/ahb/0/AppWithWait/publish /p:NetCoreAppCurrent=net5.0 /p:TestTargetRid=linux-x64 /p:MNAVersion=5.0.0-ci -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithWait.csproj
/root/runtime/.dotnet/sdk/5.0.100-preview.6.20310.4/Current/Microsoft.Common.props(32,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/ahb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/ahb/0/AppWithWait/AppWithWait.csproj]


---- The following constructor parameters did not have matching fixture data: SharedTestState fixture


Stack trace

----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 47
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, String selfContained, String outputDirectory, Boolean singleFile, Boolean restore) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 312
   at AppHost.Bundle.Tests.BundleRename.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleRename.cs:line 75
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
~~~

**Comment by BruceForstall** [comment]
From `Installer-coreclr-Linux_x64-Release`

**Comment by dagood** [comment]
Looks like host tests, maybe only single-file host tests? @jeffschwMSFT @vitek-karas @swaroop-sridhar

**Comment by swaroop-sridhar** [comment]
Looks like building the test fixture failed. It's strange, but there's nothing specific to single-file tests.
Somehow `root/runtime/artifacts/tests/Release/ahb/Directory.Build.props` is missing, so all remaining `Apphost.Bundle.Tests` failed.

**Comment by eerhardt** [comment]
The following tests failed on my PR https://github.com/dotnet/runtime/pull/45808 in the `Installer Build and Test coreclr Linux_x64 Release` leg:

https://dev.azure.com/dnceng/public/_build/results?buildId=916702&view=logs&j=488ba465-33f8-5af3-b422-ec6526547df5&t=6c6997ae-4d39-5a90-21e3-089719c051c1&l=531

* `AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Not_Passed_For_Non_Single_File_App`
* `AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Passed_For_Single_File_App`

```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: 

/root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/ahb/olrhhrso.jb2/BundleProbeTester/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci

Standard Output:
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/root/runtime/.dotnet/sdk/5.0.100/MSBuild.dll -maxcpucount -property:RuntimeIdentifier=linux-x64 -property:TargetFramework=net6.0 -property:PublishDir=/root/runtime/artifacts/tests/Release/ahb/olrhhrso.jb2/BundleProbeTester/publish /p:NetCoreAppCurrent=net6.0 /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci -target:Publish -verbosity:m /bl:PublishProject.binlog ./BundleProbeTester.csproj
/root/runtime/.dotnet/sdk/5.0.100/Current/Microsoft.Common.props(32,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/ahb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/ahb/olrhhrso.jb2/BundleProbeTester/BundleProbeTester.csproj]

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/ahb/olrhhrso.jb2/BundleProbeTester/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci
Standard Output:
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/root/runtime/.dotnet/sdk/5.0.100/MSBuild.dll -maxcpucount -property:RuntimeIdentifier=linux-x64 -property:TargetFramework=net6.0 -property:PublishDir=/root/runtime/artifacts/tests/Release/ahb/olrhhrso.jb2/BundleProbeTester/publish /p:NetCoreAppCurrent=net6.0 /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci -target:Publish -verbosity:m /bl:PublishProject.binlog ./BundleProbeTester.csproj
/root/runtime/.dotnet/sdk/5.0.100/Current/Microsoft.Common.props(32,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/ahb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/ahb/olrhhrso.jb2/BundleProbeTester/BundleProbeTester.csproj]


---- The following constructor parameters did not have matching fixture data: SharedTestState fixture
```

```
----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 317
   at AppHost.Bundle.Tests.BundleTestBase.SharedTestStateBase.PreparePublishedSelfContainedTestProject(String projectName, String[] extraArgs) in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleTestBase.cs:line 65
   at AppHost.Bundle.Tests.BundleProbe.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleProbe.cs:line 59
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by ViktorHofer** [comment]
10+ tests failed in https://dev.azure.com/dnceng/public/_build/results?buildId=1316373&view=ms.vss-test-web.build-test-results-tab&runId=38724840&resultId=100355&paneView=debug (rolling build) and there are numerous other reports that this is affecting both PR and rolling build runs.

@agocke this is showing up on our reliability dashboard every week and hence impacts our ability to improve our reliability numbers. Can someone please take a look asap?

cc @jeffschwMSFT

**Comment by ViktorHofer** [comment]
Tests that fail because of the underlying infrastructure issue:
- Bundle_Is_Extracted
- Can_Run_App_With_StatiHost
- Can_Run_SingleFile_App_With_StatiHost
- Microsoft.NET.HostModel.Tests.BundlerConsistencyTests.TestWithIdenticalBundlesShouldBeBinaryEqualPasses
- Microsoft.NET.HostModel.Tests.BundlerConsistencyTests.TestWithUniqueBundlesShouldHaveUniqueBundleIdsPasses
- TestAssemblyAlignment
- TestBundlingNativeBinaries
- TestBundlingSymbols
- TestBaseNameComputation
- TestWithDuplicateEntriesFails
- TestWithEmptySpecFails
- TestWithAdditionalContentAfterBundleMetadata
- TestWithAbsolutePaths
- TestFilesAlwaysBundled
- TestFilesNeverBundled
- TestFileSizes
- TestWithCaseSensitiveDuplicateEntriesPasses
- TestWithoutSpecifyingHostFails
- TestWithRelativePaths
- TestWithRelativePathsDirSeparator
- TestWithExactDuplicateEntriesPasses
- TestWithMultipleDuplicateEntriesFails

A few affected rolling builds that I found from the last two days:
- https://dev.azure.com/dnceng/public/_build/results?buildId=1316919&view=ms.vss-test-web.build-test-results-tab
- https://dev.azure.com/dnceng/public/_build/results?buildId=1316373&view=ms.vss-test-web.build-test-results-tab

The underlying infrastructure issue shouldn't be too hard to identify. I would start with uploading binlogs of the generated installer projects and inspecting the relevant infrastructure code (those are just a few lines).

**Comment by agocke** [comment]
Sure, I've been investigating the "text file is busy" problem, but if this one is more severe I can switch focus.

**Comment by VincentBu** [comment]
Failed again in: [runtime 20210901.70](https://dev.azure.com/dnceng/public/_build/results?buildId=1335098&view=ms.vss-test-web.build-test-results-tab&runId=39151446&resultId=100001&paneView=debug)

Failed test:
```
Installer-coreclr-Linux_musl_x64-Release

- AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Not_Passed_For_Non_Single_File_App
- AppHost.Bundle.Tests.BundleProbe.Bundle_Probe_Passed_For_Single_File_App
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Framework_dependent_App_Run_Succeeds(options: BundleAllContent)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Framework_dependent_App_Run_Succeeds(options: BundleNativeBinaries)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Framework_dependent_App_Run_Succeeds(options: None)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_App_Run_Succeeds(options: BundleAllContent)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_App_Run_Succeeds(options: BundleNativeBinaries)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_App_Run_Succeeds(options: None)
- Bundled_Framework_dependent_Targeting50_App_Run_Succeeds
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_NoCompression_App_Run_Succeeds(options: BundleAllContent)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_NoCompression_App_Run_Succeeds(options: BundleNativeBinaries)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_NoCompression_App_Run_Succeeds(options: None)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_With_Empty_File_Succeeds(options: BundleAllContent)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_With_Empty_File_Succeeds(options: BundleNativeBinaries)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_With_Empty_File_Succeeds(options: None)
- SingleFile_Apps_Are_Serviced
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_Targeting50_App_Run_Succeeds(options: BundleAllContent)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_Targeting50_App_Run_Succeeds(options: BundleNativeBinaries)
- AppHost.Bundle.Tests.BundledAppWithSubDirs.Bundled_Self_Contained_Targeting50_App_Run_Succeeds(options: None)
- Bundled_Self_Contained_Targeting50_WithCompression_Throws

```
**Error message:**
```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-musl-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 --self-contained false -o /root/runtime/artifacts/tests/Release/ahb/zcmhrkar.rbg/AppWithSubDirs/publish /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=7.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 17.0.0-preview-21427-02+414393fc1 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-rc.1.21430.12/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-musl-x64 -property:MNAVersion=7.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/ahb/zcmhrkar.rbg/AppWithSubDirs/publish -property:SelfContained=False -property:_CommandLineDefinedSelfContained=true -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-musl-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-rc.1.21430.12/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/ahb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/ahb/zcmhrkar.rbg/AppWithSubDirs/AppWithSubDirs.csproj]\n\n) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)\n---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-musl-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 --self-contained false -o /root/runtime/artifacts/tests/Release/ahb/zcmhrkar.rbg/AppWithSubDirs/publish /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=7.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 17.0.0-preview-21427-02+414393fc1 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-rc.1.21430.12/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-musl-x64 -property:MNAVersion=7.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/ahb/zcmhrkar.rbg/AppWithSubDirs/publish -property:SelfContained=False -property:_CommandLineDefinedSelfContained=true -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-musl-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-rc.1.21430.12/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/ahb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/ahb/zcmhrkar.rbg/AppWithSubDirs/AppWithSubDirs.csproj]\n\n\n---- The following constructor parameters did not have matching fixture data: SharedTestState fixture


Stack trace

----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 317
   at AppHost.Bundle.Tests.BundledAppWithSubDirs.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundledAppWithSubDirs.cs:line 165
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by agocke** [comment]
Should be fixed by https://github.com/dotnet/runtime/pull/59276
