### ISSUE TITLE
SSL connection problems on MacOS X: StartSendAuthResetSignal throws Internal error 

### ISSUE THREAD

**Issue by coolboy190** [dotnet/runtime#38679]
Getting an Internal error on making `k8s.Kubernetes.ListNamespacedServiceWithHttpMessagesAsync` call using the [Kubernetes C# SDK](https://github.com/kubernetes-client/csharp) on MacOS X. The same call works on Windows and another Mac running the same OS version. I'm unable to figure out the root cause because the error message is not descriptive enough.

The app is targeting netcoreapp3.1 framework using KubernetesClient 2.0.25 version.
OS details: Mac OS X (10.15.5) Build version 19F101
OpenSSL version: LibreSSL 2.8.3
Dotnet version: SDK 3.1.301

The above mentioned call throws HttpRequestException with the following inner exception:
 
```
{"ClassName":"System.Security.Authentication.AuthenticationException","Message":"Authentication failed, see inner exception.","Data":null,"InnerException":
{"StackTrace":null,"Message":"Internal error","Data":{},"InnerException":null,"HelpLink":null,"Source":null,"HResult":-9810},"HelpURL":null,"StackTraceString":" at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Security.SslStream.ThrowIfExceptional()
at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233087,"Source":"System.Private.CoreLib","WatsonBuckets":null}
```

----------------------------------------

**Comment by wfurt** [comment]
Do you use client side certificates? Catalina has some changes regarding security partitions. You can also check logs from securityd, there may be some hints.

**Comment by coolboy190** [comment]
@wfurt Thanks for the suggestion, I checked the securityd logs and I do see the following exceptions for my application:

(Security) [com.apple.securityd:security_exception] UNIX error exception: 17
(Security) [com.apple.securityd:security_exception] MacOS error: -25294

But I am not too familiar with these errors. It looks like there is something wrong with the keychain, I can try resetting it to see if it fixes the problem.

**Comment by wfurt** [comment]
I'm not sure the -25294 (errSecNoSuchKeychain) is relevant. I see them often. You can also check your working system and compare. The cases when I saw internal error were related to accessing private keys. And OS gives us `Internal error` so there is not much we can put to the exception. You can try to run `security unlock-keychain` from the same session where you running your app. If you using keys for authentication, you should check access in `Keychain Access` app.

**Comment by coolboy190** [comment]
@wfurt Looks like resetting the default keychain fixed the issue. Thanks a lot for the help!

**Comment by wfurt** [comment]
Good to know. I wish the error codes from OS are more decriptiove so it is more obvious what is wrong.
