### ISSUE TITLE
Test failure: Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#38697]
failed in job: [runtime-coreclr outerloop 20200701.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=713613&view=ms.vss-test-web.build-test-results-tab&runId=22128558&resultId=101117&paneView=debug)

Error message
~~~
Return code: 1
Raw output file: C:\h\w\A6BE0948\w\ACF5090A\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A6BE0948\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Running NegativeTest_NonStaticMethod...
Running NegativeTest_ViaDelegate...
Running NegativeTest_NonBlittable...
Running NegativeTest_NonInstantiatedGenericArguments...
Running NegativeTest_InstantiatedGenericArguments...
Running NegativeTest_FromInstantiatedGenericClass...
Running TestUnmanagedCallersOnlyViaUnmanagedCalli...
Running TestPInvokeMarkedWithUnmanagedCallersOnly...
Test Failure: TestLibrary.AssertTestException: Assert.Fail: Expected 'System.NotSupportedException' to be thrown, however 'System.InvalidProgramException' was thrown. 
 at TestLibrary.Assert.HandleFail(String assertionName, String message) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 735
 at TestLibrary.Assert.Fail(String message, Object[] args) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 722
 at TestLibrary.Assert.Throws[T](Action action, String message, AssertThrowsOptions options) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/Assertion.cs:line 191
 at Program.TestPInvokeMarkedWithUnmanagedCallersOnly() in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:line 762
 at Program.Main(String[] args) in /Users/runner/runners/2.171.1/work/1/s/src/coreclr/tests/src/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest.cs:line 57
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6BE0948\p
> C:\h\w\A6BE0948\w\ACF5090A\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False


Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Interop.UnmanagedCallersOnly\Interop.UnmanagedCallersOnly.XUnitWrapper.cs:line 140
~~~

**Comment by BruceForstall** [comment]
`CoreCLR Windows_NT x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open`

**Comment by BruceForstall** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
The issue here was introduced in https://github.com/dotnet/runtime/pull/38493.

https://github.com/dotnet/runtime/blob/9df02475e09859a8d24852011cf3515f7a665670/src/coreclr/src/vm/dllimport.cpp#L3058-L3064

We now indicate that any P/Invoke marked with `UnmanagedCallersOnly` required marshalling which breaks the test because we throw `InvalidProgramException` instead of `NotSupportedException` which would be throw later on. I will need to think about the best way to reconcile this discrepancy. Functionally the runtime is stable, the test isn't getting the expected exception.
