### ISSUE TITLE
WindowsCryptographicException trying to read certificate from file

### ISSUE THREAD

**Issue by varunkumarmnnit** [dotnet/runtime#38717]
Dear All,
I am running below code to get keys from the  certificate 
```c#
 public static RSA GetRsaPrivateKey(TextReader reader)
        {
            var rsaParameters = ((AsymmetricCipherKeyPair)new PemReader(reader).ReadObject()).Private.RsaParameters();

            // https://github.com/dotnet/corefx/issues/19888
            // .net core SslStream is not working with ephemeral keys on windows
            var rsa = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                ? new RSACryptoServiceProvider(new CspParameters { KeyContainerName = Guid.NewGuid().ToString("N") })
                : RSA.Create();
            rsa.ImportParameters(rsaParameters);
            return rsa;
        }
```
But the code is throwing below exception 
```
Exception while creating certificate provider, retrying 1/3	Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Bad Data
   at Internal.NativeCrypto.CapiHelper.ToKeyBlob(RSAParameters rsaParameters)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at Qlik.ServiceUtils.Security.Cryptography.RsaHelper.GetRsaPrivateKey(TextReader reader)
   at Qlik.ServiceUtils.Security.Certificates.FileCertificateProvider.SetPrivateKey(Stream privateKeyStream)
```

The challenge is the issue is not reporudcible everytime  but once it comes it keeps on coming .I have tested this on windows 2012 and 2016 both .It doesnot always come like 1 out of 10 times but once the error comes it never goes .Can u tell what could be the reason behind this.

**Comment by danmosemsft** [comment]
@varunguptacode I edited your comment to add triple-back-tick like this ``` on lines above and below the code to make it easier to read.

**Comment by bartonjs** [comment]
RSAParameters has a very specific structural requirement that BouncyCastle doesn't always adhere to.

For public keys:
* Modulus: Required (BC gets this right)
* Exponent: Required (BC gets this right)
* Everything else null

For private keys:
* Modulus: Required (BC gets this right)
* Exponent: Required (BC gets this right)
* D: D.Length must be equal to Modulus.Length (insert 0s at low indexes as needed)
* P: P.Length == (Modulus.Length + 1) / 2
* Q: Q.Length == P.Length
* DP: DP.Length == P.Length
* DQ: DQ.Length == P.Length
* InverseQ: InverseQ.Length == P.Length

BouncyCastle doesn't add the "left zeros" required to make the arrays have the correct size.

**Comment by bartonjs** [comment]
Since there has been no activity in almost 2 years, I assume the question was satisfactorily answered.
