### ISSUE TITLE
[browser][wasm] Handle null task exception message

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#38803]
Executing the following:

```
			Task testTask = null;
			await testTask;
```

Will print the following.

```
dotnet.js:8653 Uncaught (in promise) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Test.Client.Main(JSObject output)
   --- End of inner exception stack trace ---
```

Other times it prints something like the following with a `tp callback threw a System.NullReferenceException`
```
dotnet.js:2356 
dotnet.js:2356 Unhandled Exception:
dotnet.js:2356 System.NullReferenceException: Object reference not set to an instance of an object.
dotnet.js:2356    at Test.Client.CloseWebSocket(String closeReason)
dotnet.js:2356    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
dotnet.js:2356    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
dotnet.js:2356    at System.Threading.ThreadPoolWorkQueue.Dispatch()
dotnet.js:2356    at System.Threading.ThreadPool.Callback()
dotnet.js:2344 tp callback threw a System.NullReferenceException
```

Code lines:

https://github.com/dotnet/runtime/blob/master/src/mono/mono/mini/mini-wasm.c#L606-L615

```
	if (!is_ok (error)) {
		printf ("tp callback failed due to %s\n", mono_error_get_message (error));
		mono_error_cleanup (error);
	}

	if (exc) {
		char *type_name = mono_type_get_full_name (mono_object_class (exc));
		printf ("tp callback threw a %s\n", type_name);
		g_free (type_name);
	}
```

**Comment by kg** [comment]
I've been trying to reproduce this and can't. There must be more to it, like a set of conditions that lead to it happening. Does it need to be running in a browser environment in particular, or in node? Does the await need to happen in an event handler or a threadpool task?

**Comment by kjpou1** [comment]
The issue may be a little misleading.  The issue is basically documenting that the `message` being displayed is a little weird and probably should be changed from `tp` to `thread pool`.  

The system handles the case correctly though.
