### ISSUE TITLE
Test failure: System.Drawing.Common.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#38889]
Windows x86 and arm64 with:
```
COMPlus_TailcallStress=1
COMPlus_TieredCompilation=0
```

Doesn't fail on Windows x64.

x86:
```
C:\h\w\ADD60980\w\AB530912\e>set COMPlus 
COMPlus_TailcallStress=1
COMPlus_TieredCompilation=0

C:\h\w\ADD60980\w\AB530912\e>call RunTests.cmd --runtime-path C:\h\w\ADD60980\p 
----- start Tue 07/07/2020  9:13:41.98 ===============  To repro directly: ===================================================== 
pushd C:\h\w\ADD60980\w\AB530912\e\
"C:\h\w\ADD60980\p\dotnet.exe" exec --runtimeconfig System.Drawing.Common.Tests.runtimeconfig.json --depsfile System.Drawing.Common.Tests.deps.json xunit.console.dll System.Drawing.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\ADD60980\w\AB530912\e>"C:\h\w\ADD60980\p\dotnet.exe" exec --runtimeconfig System.Drawing.Common.Tests.runtimeconfig.json --depsfile System.Drawing.Common.Tests.deps.json xunit.console.dll System.Drawing.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Drawing.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Drawing.Common.Tests (found 1934 of 1969 test cases)
  Starting:    System.Drawing.Common.Tests (parallel test collections = on, max threads = 2)
    System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 [SKIP]
      Condition(s) not met: "IsOSX"
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(832,0): at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold | Italic | Strikeout, gdiCharSet: 255, gdiVerticalFont: True, expectedNamePrefix: "@", expectedWeight: 700) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues: -1) [SKIP]
      backwards compatibility on 32 bit platforms may not throw
    System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues: -2147483648) [SKIP]
      backwards compatibility on 32 bit platforms may not throw
  Finished:    System.Drawing.Common.Tests
=== TEST EXECUTION SUMMARY ===
   System.Drawing.Common.Tests  Total: 4675, Errors: 0, Failed: 9, Skipped: 3, Time: 72.518s
----- end Tue 07/07/2020  9:15:21.31 ----- exit code 1 ----------------------------------------------------------
```

https://dev.azure.com/dnceng/public/_build/results?buildId=718587&view=ms.vss-test-web.build-test-results-tab&runId=22273786&resultId=178432&paneView=debug

category:correctness
theme:tail-call
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment]
Windows arm64 also fails with:
```
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold | Italic | Strikeout, gdiCharSet: 255, gdiVerticalFont: True, expectedNamePrefix: "@", expectedWeight: 700) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   64026284
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   64026284
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: "", expectedWeight: 400) [FAIL]
      Assert.Equal() Failure
      Expected: -13
      Actual:   64026284
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(795,0): at System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(FontStyle fontStyle, Byte gdiCharSet, Boolean gdiVerticalFont, String expectedNamePrefix, Int32 expectedWeight)
```

**Comment by erozenfeld** [comment]
The bad tail call is here:

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/Font.cs#L274-L303

We are passing a pointer to a local (`new IntPtr(&nativeLogFont)`) to the call to `Marshal.PtrToStructure`. So it's a tailcallstress issue.
