### ISSUE TITLE
NET Core 3.1 - Scaffold - Could not load file or assembly System.Runtime, Version=4.2.2.0

### ISSUE THREAD

**Issue by dainam91** [dotnet/runtime#38915]
while scaffolding
Scaffold-DbContext "Server=NAV2012\SQLTEST;Database=DADLHR;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
Build started...
Build succeeded.
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable1 schemas, IEnumerable1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable1 schemaFilters, IEnumerable1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.b__0()
at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)

Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ajcvickers** [comment]
Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by singhabhi17** [comment]
![image](https://user-images.githubusercontent.com/71499140/93593153-2ad05980-f9d1-11ea-83f2-11c69d39d75f.png)
[ClassLibrary.zip](https://github.com/dotnet/runtime/files/5245218/ClassLibrary.zip)
![image](https://user-images.githubusercontent.com/71499140/93593281-73881280-f9d1-11ea-9869-34b0d9660c5f.png)

**Comment by djimenezlegend** [comment]
Same issue!

**Comment by tarekgh** [comment]
3.1 is not supported anymore. Please try the newer versions and let's know if you are still facing the same problem. Thanks!
