### ISSUE TITLE
Several tests fail with GC assertion on WASM 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#38942]
net5.0-Browser-Release-wasm-Mono_Release-Ubuntu.2004.Amd64.Open
System.Linq.Parallel.Tests Work Item

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-38877-merge-dc0fdd16a75a4fd2be/System.Linq.Parallel.Tests/console.529dd1cd.log?sv=2019-02-02&se=2020-07-27T17%3A50%3A03Z&sr=c&sp=rl&sig=WuL0qqBC%2Bkn97%2FFkScim4rIdWeJ2XoNz9uB7XpnYhZA%3D

https://dev.azure.com/dnceng/public/_build/results?buildId=719350&view=ms.vss-test-web.build-test-results-tab&runId=22286446&resultId=124553&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
[18:53:02] dbug: test[0]
      [PASS] System.Linq.Parallel.Tests.UnionTests.Union(left: ParallelEnumerable.Range-Ordered, leftCount: 1, right: List-Ordered, rightCount: 16)
[18:53:02] dbug: test[0]
      Stacktrace: 
[18:53:02] dbug: test[0]
[18:53:02] dbug: test[0]
      Error
[18:53:02] dbug: test[0]
          at 187455 (dotnet.js:1:17946)
[18:53:02] dbug: test[0]
          at _emscripten_asm_const_iii (dotnet.js:1:18131)
[18:53:02] dbug: test[0]
          at wasm_logger (<anonymous>:wasm-function[2836]:0x84106)
[18:53:02] dbug: test[0]
          at eglib_log_adapter (<anonymous>:wasm-function[5372]:0xe5fb2)
[18:53:02] dbug: test[0]
          at monoeg_g_logstr (<anonymous>:wasm-function[4003]:0xa691d)
[18:53:02] dbug: test[0]
          at monoeg_g_logv_nofree (<anonymous>:wasm-function[1960]:0x53c61)
[18:53:02] dbug: test[0]
          at monoeg_assertion_message (<anonymous>:wasm-function[369]:0xb769)
[18:53:02] dbug: test[0]
          at mono_assertion_message_unreachable (<anonymous>:wasm-function[126]:0x3407)
[18:53:02] dbug: test[0]
          at simple_nursery_serial_scan_object (<anonymous>:wasm-function[1799]:0x4d754)
[18:53:02] dbug: test[0]
          at simple_nursery_serial_drain_gray_stack (<anonymous>:wasm-function[3674]:0x98bed)
[18:53:02] dbug: test[0]
          at sgen_drain_gray_stack (<anonymous>:wasm-function[625]:0x130ae)
[18:53:02] dbug: test[0]
          at finish_gray_stack (<anonymous>:wasm-function[2589]:0x7a7e2)
[18:53:02] dbug: test[0]
          at collect_nursery (<anonymous>:wasm-function[1718]:0x476d7)
[18:53:02] dbug: test[0]
          at sgen_perform_collection_inner (<anonymous>:wasm-function[1815]:0x4dd34)
[18:53:02] dbug: test[0]
          at sgen_perform_collection (<anonymous>:wasm-function[692]:0x14f27)
[18:53:02] dbug: test[0]
          at sgen_ensure_free_space (<anonymous>:wasm-function[903]:0x1b3ae)
[18:53:02] dbug: test[0]
          at sgen_alloc_obj_nolock (<anonymous>:wasm-function[1061]:0x21c77)
[18:53:02] dbug: test[0]
          at mono_gc_alloc_vector (<anonymous>:wasm-function[1516]:0x3fd20)
[18:53:02] dbug: test[0]
          at mono_array_new_specific_internal (<anonymous>:wasm-function[2409]:0x658b0)
[18:53:02] dbug: test[0]
          at mono_array_new_specific_checked (<anonymous>:wasm-function[983]:0x1e982)
[18:53:02] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[1224]:0x3023b)
[18:53:02] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[4964]:0xcdcac)
[18:53:02] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[4467]:0xb7b8f)
[18:53:02] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[1703]:0x46c3f)
[18:53:02] dbug: test[0]
          at mono_runtime_invoke_checked (<anonymous>:wasm-function[346]:0xabed)
[18:53:02] dbug: test[0]
          at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4225]:0xacec3)
[18:53:02] dbug: test[0]
          at ves_icall_InternalInvoke (<anonymous>:wasm-function[3526]:0x94141)
[18:53:02] dbug: test[0]
          at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3525]:0x93c0a)
[18:53:02] dbug: test[0]
          at do_icall (<anonymous>:wasm-function[5391]:0xe7041)
[18:53:02] dbug: test[0]
          at do_icall_wrapper (<anonymous>:wasm-function[1704]:0x46cf6)
[18:53:02] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[1224]:0x29962)
[18:53:02] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[4964]:0xcdcac)
[18:53:02] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[4467]:0xb7b8f)
[18:53:02] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[1703]:0x46c3f)
[18:53:02] dbug: test[0]
          at mono_runtime_try_invoke (<anonymous>:wasm-function[425]:0xd591)
[18:53:02] dbug: test[0]
          at mono_runtime_invoke (<anonymous>:wasm-function[4230]:0xad228)
[18:53:02] dbug: test[0]
          at mono_wasm_invoke_method (<anonymous>:wasm-function[4036]:0xa75fd)
[18:53:02] dbug: test[0]
          at Module._mono_wasm_invoke_method (dotnet.js:1:187283)
[18:53:02] dbug: test[0]
          at Object.init (runtime.js:366:15)
[18:53:02] dbug: test[0]
          at runtime.js:245:9
[18:53:02] dbug: test[0]
          at dotnet.js:1:128739
[18:53:02] dbug: test[0]
      WASM-ERR: * Assertion: should not be reached at /__w/1/s/src/mono/mono/sgen/sgen-scan-object.h:91
[18:53:02] dbug: test[0]
      WASM-ERR: 
[18:53:02] dbug: test[0]
      ABORT: undefined
[18:53:02] dbug: test[0]
      Stacktrace: 
[18:53:02] dbug: test[0]
[18:53:02] dbug: test[0]
      Error
[18:53:02] dbug: test[0]
          at Object.onAbort (runtime.js:160:13)
[18:53:02] dbug: test[0]
          at abort (dotnet.js:1:14661)
[18:53:02] dbug: test[0]
          at _abort (dotnet.js:1:103998)
[18:53:02] dbug: test[0]
          at wasm_logger (<anonymous>:wasm-function[2836]:0x8412b)
[18:53:02] dbug: test[0]
          at eglib_log_adapter (<anonymous>:wasm-function[5372]:0xe5fb2)
[18:53:02] dbug: test[0]
          at monoeg_g_logstr (<anonymous>:wasm-function[4003]:0xa691d)
[18:53:02] dbug: test[0]
          at monoeg_g_logv_nofree (<anonymous>:wasm-function[1960]:0x53c61)
[18:53:02] dbug: test[0]
          at monoeg_assertion_message (<anonymous>:wasm-function[369]:0xb769)
[18:53:02] dbug: test[0]
          at mono_assertion_message_unreachable (<anonymous>:wasm-function[126]:0x3407)
[18:53:02] dbug: test[0]
          at simple_nursery_serial_scan_object (<anonymous>:wasm-function[1799]:0x4d754)
[18:53:02] dbug: test[0]
          at simple_nursery_serial_drain_gray_stack (<anonymous>:wasm-function[3674]:0x98bed)
[18:53:02] dbug: test[0]
          at sgen_drain_gray_stack (<anonymous>:wasm-function[625]:0x130ae)
[18:53:02] dbug: test[0]
          at finish_gray_stack (<anonymous>:wasm-function[2589]:0x7a7e2)
[18:53:02] dbug: test[0]
          at collect_nursery (<anonymous>:wasm-function[1718]:0x476d7)
[18:53:02] dbug: test[0]
          at sgen_perform_collection_inner (<anonymous>:wasm-function[1815]:0x4dd34)
[18:53:02] dbug: test[0]
          at sgen_perform_collection (<anonymous>:wasm-function[692]:0x14f27)
[18:53:02] dbug: test[0]
          at sgen_ensure_free_space (<anonymous>:wasm-function[903]:0x1b3ae)
[18:53:02] dbug: test[0]
          at sgen_alloc_obj_nolock (<anonymous>:wasm-function[1061]:0x21c77)
[18:53:02] dbug: test[0]
          at mono_gc_alloc_vector (<anonymous>:wasm-function[1516]:0x3fd20)
[18:53:02] dbug: test[0]
          at mono_array_new_specific_internal (<anonymous>:wasm-function[2409]:0x658b0)
[18:53:02] dbug: test[0]
          at mono_array_new_specific_checked (<anonymous>:wasm-function[983]:0x1e982)
[18:53:02] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[1224]:0x3023b)
[18:53:02] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[4964]:0xcdcac)
[18:53:02] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[4467]:0xb7b8f)
[18:53:02] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[1703]:0x46c3f)
[18:53:02] dbug: test[0]
          at mono_runtime_invoke_checked (<anonymous>:wasm-function[346]:0xabed)
[18:53:02] dbug: test[0]
          at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4225]:0xacec3)
[18:53:02] dbug: test[0]
          at ves_icall_InternalInvoke (<anonymous>:wasm-function[3526]:0x94141)
[18:53:02] dbug: test[0]
          at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3525]:0x93c0a)
[18:53:02] dbug: test[0]
          at do_icall (<anonymous>:wasm-function[5391]:0xe7041)
[18:53:02] dbug: test[0]
          at do_icall_wrapper (<anonymous>:wasm-function[1704]:0x46cf6)
[18:53:02] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[1224]:0x29962)
[18:53:02] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[4964]:0xcdcac)
[18:53:02] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[4467]:0xb7b8f)
[18:53:02] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[1703]:0x46c3f)
[18:53:02] dbug: test[0]
          at mono_runtime_try_invoke (<anonymous>:wasm-function[425]:0xd591)
[18:53:02] dbug: test[0]
          at mono_runtime_invoke (<anonymous>:wasm-function[4230]:0xad228)
[18:53:02] dbug: test[0]
          at mono_wasm_invoke_method (<anonymous>:wasm-function[4036]:0xa75fd)
[18:53:02] dbug: test[0]
          at Module._mono_wasm_invoke_method (dotnet.js:1:187283)
[18:53:02] dbug: test[0]
          at Object.init (runtime.js:366:15)
[18:53:02] dbug: test[0]
          at runtime.js:245:9
[18:53:02] dbug: test[0]
          at dotnet.js:1:128739
[18:53:02] info: test[0]
      18:53:02.4516756 Process exited with 1
XHarness exit code: 1001
XHarness artifacts: ./xharness-output
```

**Comment by akoeplinger** [comment]
This seems to be fixed by https://github.com/dotnet/runtime/pull/39856.
