### ISSUE TITLE
CancelKeyPressTests.HandlerInvokedForSigQuit test failing on OSX in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#38998]
https://github.com/dotnet/runtime/pull/38334 un-ActiveIssue'd the test yesterday.
cc: @tmds

```
/private/tmp/helix/working/A13908BE/w/B17A0936/e /private/tmp/helix/working/A13908BE/w/B17A0936/e
  Discovering: System.Console.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Console.Tests (found 102 of 135 test cases)
  Starting:    System.Console.Tests (parallel test collections = on, max threads = 4)
    CancelKeyPressTests.HandlerInvokedForSigQuit [FAIL]
      Half-way through waiting for remote process.
      Timed out at 7/9/2020 6:03:58 AM after 60000ms waiting for remote process.
      	Process ID: 16003
      	Handle: 844
      	Name: dotnet
      	MainModule: /private/tmp/helix/working/A13908BE/p/dotnet
      	StartTime: 7/9/2020 6:02:58 AM
      	TotalProcessorTime: 00:00:06.7481305
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(225,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(58,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs(89,0): at CancelKeyPressTests.HandlerInvokedForSignal(Int32 signalOuter)
        /_/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs(37,0): at CancelKeyPressTests.HandlerInvokedForSigQuit()
```

**Comment by stephentoub** [comment]
cc: @adamsitnik

**Comment by adamsitnik** [comment]
The test has been disabled in https://github.com/dotnet/runtime/pull/39003, I am moving it to 6.0

**Comment by tmds** [comment]
This is now only failing on OSX. Maybe https://github.com/dotnet/runtime/pull/38334 `IsSignalIgnored` implementation is not ok for OSX?

**Comment by adamsitnik** [comment]
FWIW I've tried to reproduce it on my mac book and I've failed ;)
