### ISSUE TITLE
System.Runtime.Extension Test fails on WASM

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#38995]
When running tests for `System.Runtime.Extensions` on wasm, several tests fail.
____
- [ ] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort

```
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "turky ı", expectedString: "TURKY I", cultureName: "tr-TR", options: IgnoreCase, result: True)
Assert.Equal() Failure
Expected: 1177289279
Actual:   -1522784022
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "turky i", expectedString: "TURKY İ", cultureName: "tr-TR", options: IgnoreCase, result: True)
Assert.Equal() Failure
Expected: -1522784022
Actual:   -1018577898
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   2066064758
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab+cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   -1732148097
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab%cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   376413271
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab&cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   838450990
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   1513400474
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   1513400474
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "a-bcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: 217779608
Actual:   1513400474
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd*", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: 984489987
Actual:   1513400474
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptionsStringSort(actualString: "abcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: -1984055434
Actual:   1513400474
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
------
- [ ]  System.Tests.StringComparerTests.CreateFromCultureAndOptions

```
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "turky ı", expectedString: "TURKY I", cultureName: "tr-TR", options: IgnoreCase, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "turky i", expectedString: "TURKY İ", cultureName: "tr-TR", options: IgnoreCase, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab+cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab%cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab&cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "a-bcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd*", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Tests.StringComparerTests.CreateFromCultureAndOptions(actualString: "abcd", expectedString: "ab$cd", cultureName: "en-US", options: IgnoreSymbols, result: True)
Assert.Equal() Failure
Expected: True
Actual:   False
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by safern** [comment]
I can't find any test disabled against this issue and we already enabled this test assembly. Closing

cc: @steveisok @akoeplinger

**Comment by akoeplinger** [comment]
Yeah the tests were moved to be `[ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsNotInvariantGlobalization))]`
