### ISSUE TITLE
Microsoft.Extensions.Hosting: improve timeout message

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#39085]
### Description

The timeout message doesn't point out that a timeout happens. It's confusing to new users.

### Configuration

Microsoft.Extensions.Hosting 5.0.0-preview.6

### Sample Code

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Playground
{
    class Program
    {
        static Task Main(string[] args)
        {
            return Host.CreateDefaultBuilder()
                .ConfigureServices(services => services
                    .AddHostedService<TimeoutService>()
                    .Configure<HostOptions>(o => o.ShutdownTimeout = TimeSpan.FromSeconds(1)))
                .RunConsoleAsync();
        }
    }

    class TimeoutService : IHostedService
    {
        public Task StartAsync(CancellationToken cancellationToken) => Task.CompletedTask;
        public Task StopAsync(CancellationToken cancellationToken) => Task.Delay(2000);
    }
}

```

### Actual Message
```
Unhandled exception. System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Playground.Program.<Main>(String[] args)
```

### Expected Message
**Must**: Point out that it's a shutdown timeout.
**Should**: Include configured timeout time in message.

**Comment by huoyaoyuan** [comment]
Confirmed the behavior in 5.0.0:
No `OperationCanceledException` thrown. If the implementation decides not to check the cancellation token, it can run to complete as usual.
