### ISSUE TITLE
[Mono] Test failure: System.Diagnostics.Process.Tests, SafeHandle double-close?

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#39109]
Failed in:
- Libraries Test Run release mono OSX x64 Debug

- https://dev.azure.com/dnceng/public/_build/results?buildId=725076&view=logs&jobId=c6f8dc49-92a1-5760-c098-ba97b8142bfb&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=22b0078b-0469-5ba6-8725-2121fdbae049
- https://helix.dot.net/api/2019-06-17/jobs/0646804f-7cfc-455a-b6b0-d1c1628db70a/workitems/System.Diagnostics.Process.Tests/console

```
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 221 of 291 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 4)
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Darwin
    System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"
    System.Diagnostics.Tests.ProcessTests.CanBeFinalized [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_CopiesShareExitAsyncInformation', Elapsed: 00:02:09
   System.Diagnostics.Process.Tests: [Long Running Test] 'System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_CopiesShareExitAsyncInformation', Elapsed: 00:04:09

Unhandled Exception:
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 243
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 164
   at Microsoft.Win32.SafeHandles.SafeProcessHandle.ReleaseHandle() in /_/src/libraries/System.Diagnostics.Process/src/Microsoft/Win32/SafeHandles/SafeProcessHandle.Unix.cs:line 45
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 240
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 96
   at System.Runtime.InteropServices.SafeHandle.Finalize() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 72
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 243
   at System.Runtime.InteropServices.SafeHandle.DangerousRelease() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 164
   at Microsoft.Win32.SafeHandles.SafeProcessHandle.ReleaseHandle() in /_/src/libraries/System.Diagnostics.Process/src/Microsoft/Win32/SafeHandles/SafeProcessHandle.Unix.cs:line 45
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 240
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 96
   at System.Runtime.InteropServices.SafeHandle.Finalize() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 72
```

**Comment by mangod9** [comment]
Is this related to the portal TP, or are those changes now exposing some timing issue causing the failure?

**Comment by kouvel** [comment]
Looks like it could be my change, I got a better stack trace in one of the other runs, will take a look

**Comment by kouvel** [comment]
Think I found the issue, couldn't repro locally but trying the CI again. It's a timing issue that existed before but due to other unrelated changes, would be fatal after my changes.

**Comment by kouvel** [comment]
Also I believe it's a new test that I ported from CoreRT that exposed the issue, it may have failed without the changes as well

**Comment by kouvel** [comment]
If my understanding is correct it would have failed before too, but in a slightly different way and with different timing requirements

**Comment by kouvel** [comment]
Upon further review the issue I found above could cause issues before my changes but should not be a problem after my changes, probably something else is wrong.

**Comment by kouvel** [comment]
Got a repro with some timing changes and fixed the issue, it was a new issue in my changes
