### ISSUE TITLE
Test failure: Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39175]
failed in job: [runtime-coreclr gcstress0x3-gcstress0xc 20200712.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=726396&view=ms.vss-test-web.build-test-results-tab&runId=22494802&resultId=109142&paneView=debug)

Error message
~~~
Return code:      1
Raw output file:      C:\h\w\BB02093C\w\9E280924\e\Interop\COM\Reports\Interop.COM\NETClients\Primitives\NETClientPrimitives\NETClientPrimitives.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\BB02093C\p\corerun.exe" NETClientPrimitives.dll 
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling

Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr
Marshal strings as BStr
Marshal LCID
Verify expected exception from HRESULT
Verify preserved function signature
Testing COM object lifetime control methods.
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Marshal strings as LPWStr

Marshal strings as BStr
Marshal LCID

Verify expected exception from HRESULT

Verify preserved function signature
Test Failure: TestLibrary.AssertTestException: Assert.IsFalse: 

   at TestLibrary.Assert.HandleFail(String assertionName, String message) in /Users/runner/work/1/s/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 734
   at NetClient.Program.Main(String[] doNotUse) in /Users/runner/work/1/s/src/tests/Interop/COM/NETClients/Primitives/Program.cs:line 28
Expected: 100

Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\BB02093C\p
> C:\h\w\BB02093C\w\9E280924\e\Interop\COM\NETClients\Primitives\NETClientPrimitives\NETClientPrimitives.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 1789
~~~

**Comment by AaronRobinsonMSFT** [comment]
Run is CoreCLR Windows_NT arm64 Checked gcstress0xc @ Windows.10.Arm64.Open

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Do you remember the history of adding the life time checks? 07c9eaf39c5d4fcb5fbf87e701cf20d94d05277f. I seem to recall asking you to add this testing, but don't remember what the original issue was.

Failure is at: https://github.com/dotnet/runtime/blob/2d9dbbb538322a7cc05397f5e2e15d445c7d3ff0/src/tests/Interop/COM/NETClients/Primitives/Program.cs#L28

**Comment by jkoritzinsky** [comment]
I think the reason we added the checks was because we had no testing for those functions and it was easiest to add testing for it in the existing test.

**Comment by jkoritzinsky** [comment]
This test has not failed since this run on July 12th, so I'm going to close this issue for now.
