### ISSUE TITLE
GetFunctionPointerForDelegateTests tests fail with Specified cast is not valid on Browser

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#39187]
When running System.Runtime.InteropServices library tests on Browser wasm, two functions fail with `Specified cast is not valid`:

- GetFunctionPointerForDelegate_MarshalledDelegateNonGeneric_ReturnsExpected
- GetFunctionPointerForDelegate_MarshalledDelegateGeneric_ReturnsExpected

### Note
When the tests are not ordered, the suite sometimes fails with the two tests above
```
[FAIL] System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledDelegateNonGeneric_ReturnsExpected
System.InvalidCastException : Specified cast is not valid.
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledDelegateGeneric_ReturnsExpected
System.InvalidCastException : Specified cast is not valid.
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
And other times, it fails with the six tests from `GetDelegateForFunctionPointerTests.cs`
```
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_NonGeneric_ReturnsExpected(t: typeof(System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate))
Assert.IsType() Failure
Expected: System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate
Actual: System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests+NonGenericDelegate
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_NonGeneric_ReturnsExpected(t: typeof(System.MulticastDelegate))
Assert.IsType() Failure
Expected: System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate
Actual: System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests+NonGenericDelegate
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_NonGeneric_ReturnsExpected(t: typeof(System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+OtherNonGenericDelegate))
Assert.IsType() Failure
Expected: System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate
Actual: System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests+NonGenericDelegate
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_GenericInvalidType_ReturnsExpected
Assert.IsType() Failure
Expected: System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate
Actual: System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests+NonGenericDelegate
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_CollectibleType_ReturnsExpected
Assert.IsType() Failure
Expected: System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate
Actual: System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests+NonGenericDelegate
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_Generic_ReturnsExpected
System.InvalidCastException : Specified cast is not valid.
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
```

**Comment by vargaz** [comment]
These now fail with:
System.PlatformNotSupportedException : No native to managed transitions on this platform.
They cannot be supported without the pinvoke generator.

**Comment by lewing** [comment]
@vargaz this sounds like net6?

**Comment by vargaz** [comment]
Probably.

**Comment by pavelsavara** [comment]
I will remove the [ActiveIssue] from `System.Net.Http.Functional.Tests` in my PR because it works there.

**Comment by pavelsavara** [comment]
This was probably fixed already. The remaining [ActiveIssue] are in `src\libraries\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\GetFunctionPointerForDelegateTests.cs` but that is in assembly which is not targeting Browser right now. 

@mdh1418 how did you made them run on browser before ?

**Comment by vargaz** [comment]
This PR:
https://github.com/dotnet/runtime/pull/56883
will fix the error handling, so it will now fail with a more reasonable error message.

**Comment by SamMonoRT** [comment]
@lewing - is this a must for 6.0 ?

**Comment by SamMonoRT** [comment]
Moving to 7.0

**Comment by ilonatommy** [comment]
@vargaz, are we able to solve it in 7.0?

**Comment by lewing** [comment]
@ilonatommy can you check if these tests still fail?

**Comment by ilonatommy** [comment]
The error message changed to:
```
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_CantCast_ThrowsInvalidCastException
   System.PlatformNotSupportedException : No native to managed transition for method 'void System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests:Method (string)', missing [UnmanagedCallersOnly] attribute.
  at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(Delegate d)
  at System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_CantCast_ThrowsInvalidCastException()
  at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
  at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
When we use the hint and add the decorator:
```
        [UnmanagedCallersOnly]
        private static void Method(string s) { }
```
`GetFunctionPointerForDelegateTests.cs(124,36): error CS8894: Cannot use 'string' as a parameter type on a method attributed with 'UnmanagedCallersOnly'`

I am not sure how to fix this.

Tests failing with this message:
```
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_CantCast_ThrowsInvalidCastException
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_GenericInvalidType_ReturnsExpected
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_NonGeneric_ReturnsExpected(t: typeof(System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+NonGenericDelegate))
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_NonGeneric_ReturnsExpected(t: typeof(System.MulticastDelegate))
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_NonGeneric_ReturnsExpected(t: typeof(System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests+OtherNonGenericDelegate))
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_Generic_ReturnsExpected
[FAIL] System.Runtime.InteropServices.Tests.GetDelegateForFunctionPointerTests.GetDelegateForFunctionPointer_CollectibleType_ReturnsExpected
[FAIL] System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledDelegateGeneric_ReturnsExpected
[FAIL] System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_NormalDelegateGeneric_ReturnsExpected
[FAIL] System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledDelegateNonGeneric_ReturnsExpected
[FAIL] System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_NormalDelegateNonGeneric_ReturnsExpected
```

**Comment by lewing** [comment]
@vargaz is this something we expect to work?

**Comment by lewing** [comment]
cc @kg @BrzVlad
