### ISSUE TITLE
CreateAppHost task fails with very long path

### ISSUE THREAD

**Issue by mfkl** [dotnet/runtime#39211]
### Description

repro:
- `git clone https://github.com/mfkl/dotnet-longpath-test repro`
- `cd repro`
```
dotnet build .\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing.csproj
```

Fails with 
```
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. 
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: Microsoft.NET.HostModel.HResultException: 8007007A 
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error()
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.ResourceUpdater.Update() 
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnWin32Error(Action func) 
.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) 
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() 
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() 
C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() C:\Program Files\dotnet\sdk\3.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Building a classlibrary instead of a console app works as expected with this long path (because this task isn't run I guess).

With recent Windows 10 versions, if the "enable win32 long paths" registry key is set, I believe this should be building as expected.

What should the new path limit be in that case? Should the code check for the long path support in the registry first?

~~Relevant unit test~~: https://github.com/dotnet/runtime/blob/d44d63811a5437082178e8573f70c6b337e7f794/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUpdateTests.cs#L79

~~Code that throws~~: https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs#L44

~~The unit test were added in https://github.com/dotnet/runtime/commit/3af73799fe3f47d04153ee134664d971eb8946a9~~

Edit:

Actual stacktrace:

```
   Microsoft.NET.HostModel.HResultException : 80070003
  Stack Trace:
     at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error() in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\ResourceUpdater.cs:line 428
   at Microsoft.NET.HostModel.ResourceUpdater..ctor(String peFile) in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\ResourceUpdater.cs:line 217
   at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__UpdateResources|1() in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\AppHost\HostWriter.cs:line 83
   at Microsoft.NET.HostModel.RetryUtil.RetryOnWin32Error(Action func) in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\AppHost\RetryUtil.cs:line 87
   at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResourcesFrom) in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\AppHost\HostWriter.cs:line 127
   at Microsoft.NET.HostModel.Tests.AppHostUpdateTests.ItFailsToEmbedTooLongAppBinaryPath2222() in dotnet-runtime\src\installer\tests\Microsoft.NET.HostModel.Tests\Microsoft.NET.HostModel.AppHost.Tests\AppHostUpdateTests.cs:line 85
```

In the case that the `appHostDestinationFilePath` and `assemblyToCopyResourcesFrom` are very long, win32 calls such as `LoadLibraryEx` and `BeginUpdateResource` fail.

There are some [long path helpers](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/IO/PathInternal.Windows.cs) but they are not available from this namespace.

### Configuration

* Which version of .NET is the code running on?
3.1 but any dotnet core works to repro.

* What OS and version, and what distro if applicable?
Win10 2004.

* What is the architecture (x64, x86, ARM, ARM64)?
x64.

* Do you know whether it is specific to that configuration?
Unlikely to be.

### Regression?

Historic reason, I believe.

**Comment by mfkl** [comment]
Attempt here https://github.com/mfkl/runtime/tree/longpath-fix

Managed to workaround one of the calls to win32 that fails, but not the next one, which is `LoadLibraryEx`

new stacktrace:

```
 Error Message:
   Microsoft.NET.HostModel.HResultException : 80070002
  Stack Trace:
     at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error() in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\ResourceUpdater.cs:line 428
   at Microsoft.NET.HostModel.ResourceUpdater.AddResourcesFromPEImage(String peFile) in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\ResourceUpdater.cs:line 243
   at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__UpdateResources|1() in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\AppHost\HostWriter.cs:line 87
   at Microsoft.NET.HostModel.RetryUtil.RetryOnWin32Error(Action func) in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\AppHost\RetryUtil.cs:line 87
   at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResourcesFrom) in dotnet-runtime\src\installer\managed\Microsoft.NET.HostModel\AppHost\HostWriter.cs:line 131
   at Microsoft.NET.HostModel.Tests.AppHostUpdateTests.ItSucceedsToBuildLongDestinationPath() in dotnet-runtime\src\installer\tests\Microsoft.NET.HostModel.Tests\Microsoft.NET.HostModel.AppHost.Tests\AppHostUpdateTests.cs:line 110
```

Ended up on this page https://docs.microsoft.com/en-us/archive/blogs/bclteam/long-paths-in-net-part-1-of-3-kim-hamilton which states

> For example, LoadLibrary, which maps a module into the address of the calling process, fails if the file name is longer than MAX_PATH. So this means MoveFile will let you move a DLL to a location such that its path is longer than 260 characters, but when you try to load the DLL, it would fail. There are similar examples throughout the Windows APIs; some workarounds exist, but they are on a case-by-case basis.

I'm not sure moving the needed items in a shorter path is a viable/clean option. Any idea how to go about this?

**Comment by ericwj** [comment]
```PowerShell
PS mfkl\repro> cmd /c mklink /j longpath .\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\
Junction created for longpath <<===>> .\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\
PS mfkl\repro> dotnet build .\longpath\
Microsoft (R) Build Engine version 16.7.0-preview-20258-02+26f6d1d87 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\Eric\Source\GitHub\mfkl\repro\longpath\thisisaveryveryverylongpathanditkeepsgoing.csproj (in 131 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  thisisaveryveryverylongpathanditkeepsgoing -> C:\Users\Eric\Source\GitHub\mfkl\repro\longpath\bin\Debug\netcoreapp3.1\thisisaveryveryverylongpathanditkeepsgoing.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.22
PS mfkl\repro>
```

**Comment by mfkl** [comment]
Sure, a symlink or just cd to the dir that contains the csproj will workaround the problem.

But building a library project from a long path works as expected, unlike an exe app (linked above), so there is a discrepancy here. 

Is this something that should be fixed? Or just documented as "known issue, won't fix"?

**Comment by ericwj** [comment]
I guess apart from the API's themselves, many Windows components, hence Windows as a whole is not quite done being fully long path capable, let alone .NET or any app running on it. There is a reason you have to hack the registry to enable implicit long paths.

The following shows that you actually cannot CD into the directory and run `dotnet build`.
```PowerShell
PS> PS mfkl\repro> cd .\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\
PS mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing> dotnet build

ResourceUnavailable: Program 'dotnet.exe' failed to run: The directory name is invalid.At line:1 char:1
+ dotnet build
+ ~~~~~~~~~~~~.
```
Slightly confusing I think. `dotnet.exe` did not get started at all if I'm correct. `$LASTEXITCODE` is `0`.

OK so lets skip `pwsh` and run it in the `cmd`:
```
$P$G>cd mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing

$P$G mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing>dotnet build
The current directory is invalid.


$P$G mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing>cd "\\?\%CD%"
'\\?\C:\...\mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing'
CMD does not support UNC paths as current directories.
```

Haven't tried running `dotnet build` through `Process.Start` with this working directory or one that has the `\\?\` prefix, but that would probably be the only way to get `dotnet` to start there.

Can't even do this and this time MSBuild is at fault:
```PowerShell
mfkl\repro> dotnet build "\\?\$PWD\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing"
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored \\?\C:\...\mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing.csproj (in 141 ms).
C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\Current\Microsoft.Common.props(62,3): error MSB4019: The imported project "\\?\C:\...\mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\obj\thisisaveryveryverylongpathanditkeepsgoing.csproj.*.props" was not found. Confirm that the expression in the Import declaration "\\%3f\C:\...\mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\obj\thisisaveryveryverylongpathanditkeepsgoing.csproj.*.props" is correct, and that the file exists on disk. [\\?\C:\...\mfkl\repro\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing.csproj]

Build FAILED.
(...)
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.95
```
Note the `\\%3f\C:\...\mfkl\repro` which breaks this path.

**Comment by mfkl** [comment]
This works
```
dotnet build .\longpath\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing.csproj
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\..\longpath\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing.csproj (in 254 ms).
  thisisaveryveryverylongpathanditkeepsgoing -> C:\..\longpath\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\thisisaveryveryverylongpathanditkeepsgoing\bin\Debug\netstandard2.0\thisisaveryveryverylongpathanditkeepsgoing.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)
```

But only with
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by ericwj** [comment]
Yes, I perfectly see your point. I just point out there's more to it than just .NET. Will just have to see what the experts say and the priority this gets.
