### ISSUE TITLE
System.Net.Tests.HttpWebRequestTest_Async.Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException fails in CI

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#39279]
https://dev.azure.com/dnceng/public/_build/results?buildId=728239&view=ms.vss-test-web.build-test-results-tab&runId=22544614&resultId=159662&paneView=debug

net5.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open
System.Net.Tests.HttpWebRequestTest_Async.Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException

```
    System.Net.Tests.HttpWebRequestTest_Async.Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Net.WebException)
      Actual:   typeof(System.IO.IOException): The operation is not allowed on non-connected sockets.
      ---- System.IO.IOException : The operation is not allowed on non-connected sockets.
      Stack Trace:
        /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1025,0): at System.Net.HttpWebRequest.GetResponse()
        /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs(522,0): at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass38_0.<Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException>b__1()
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1025,0): at System.Net.HttpWebRequest.GetResponse()
        /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs(522,0): at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass38_0.<Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException>b__1()
```

**Comment by stephentoub** [comment]
cc: @ManickaP, @wfurt

**Comment by wfurt** [comment]
This seems same failure as #39259
```
Assert.Throws() Failure
Expected: typeof(System.Net.WebException)
Actual:   typeof(System.IO.IOException): The operation is not allowed on non-connected sockets.
---- System.IO.IOException : The operation is not allowed on non-connected sockets.


Stack trace
   at System.Net.HttpWebRequest.GetResponse() in /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1025
   at System.Media.SoundPlayer.LoadSync() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 265
   at System.Media.SoundPlayer.LoadAndPlay(Int32 flags) in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 228
   at System.Media.SoundPlayer.Play() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 326
   at System.Media.Test.SoundPlayerTests.<>c__DisplayClass9_0.<Play_InvalidFile_ShortTimeout_ThrowsWebException>b__0() in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 157

```

**Comment by ManickaP** [comment]
Yep, the same problem, different tests. I'll look into it.

**Comment by am11** [comment]
Noticed the same error with `SDK Version: 5.0.100-preview.8.20362.3` in a helloworld app on FreeBSD, using linux x64 binary (in Linux® emulation mode): https://api.cirrus-ci.com/v1/task/6736777027256320/logs/emulate%20dotnet.log  |  [ci job](https://cirrus-ci.com/task/6736777027256320)
