### ISSUE TITLE
GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream start failing in CI

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#39310]
This looks like recent regression. ~ 10 failures 7/14 - official builds as well as unrelated PRs

https://helix.dot.net/api/2019-06-17/jobs/e8072506-027f-4644-8142-63789cf82ad6/workitems/System.Net.Http.Functional.Tests/console

```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream(mode: DisposeHttpClient, copyToAsync: True) [FAIL]
      System.IO.IOException : The request was aborted.
      ---- System.ObjectDisposedException : Cannot access a disposed object.
      Object name: 'SslStream'.
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1829,0): at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(825,0): at System.Net.Http.Http2Connection.PerformWriteAsync[T](Int32 writeBytes, T state, Func`3 writeAction, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1374,0): at System.Net.Http.Http2Connection.SendWindowUpdateAsync(Int32 streamId, Int32 amount)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs(900,0): at System.Net.Http.Http2Connection.Http2Stream.ExtendWindow(Int32 amount)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs(1049,0): at System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(HttpResponseMessage responseMessage, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs(310,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass5_0.<<GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(37,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs(242,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs(271,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelPendingRequests_DoesntCancelReadAsyncOnResponseStream(CancellationMode mode, Boolean copyToAsync)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs(857,0): at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|139_0(ExceptionDispatchInfo e)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs(847,0): at System.Net.Security.SslStream.ThrowIfExceptional()
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs(838,0): at System.Net.Security.SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(258,0): at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
```

we have seen some of this in the past but not it start failing a lot. Perhaps related to recent HTTP changes.
cc: @geoffkizer

**Comment by geoffkizer** [comment]
I'll take a look.

**Comment by geoffkizer** [comment]
Yeah, this seems to be caused by my change. When we are aborted, we are now throwing the abort exception synchronously in PerformWriteAsync rather than asynchronously. So although we try to eat the exception here in ExtendWindow, it's not actually eating it because it's synchronous.
