### ISSUE TITLE
System.SpanTests.SpanTests.BinaryPrimitives_StaticWithSpanArgument fails with a runtime assertion on WASM

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#39311]
In System.Memory.Tests:

```
[0x1: 70.29512 4] ENTER:i System.SpanTests.SpanTests:BinaryPrimitives_StaticWithSpanArgument ()()
Stacktrace:

Error
    at 201711 (dotnet.js:1:18045)
    at _emscripten_asm_const_iii (dotnet.js:1:18230)
    at wasm_logger (<anonymous>:wasm-function[2885]:0x8b7ea)
    at eglib_log_adapter (<anonymous>:wasm-function[5439]:0xebfd5)
    at monoeg_g_logstr (<anonymous>:wasm-function[4056]:0xae177)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[1986]:0x57acb)
    at monoeg_assertion_message (<anonymous>:wasm-function[375]:0xbcf7)
    at mono_assertion_message (<anonymous>:wasm-function[187]:0x4e5b)
    at mono_assertion_message_disabled (<anonymous>:wasm-function[112]:0x2fba)
    at mono_handle_exception_internal (<anonymous>:wasm-function[2277]:0x62945)
    at mono_handle_exception (<anonymous>:wasm-function[2278]:0x62a05)
    at interp_throw (<anonymous>:wasm-function[130]:0x378f)
    at interp_exec_method (<anonymous>:wasm-function[1244]:0x2b48c)
    at interp_runtime_invoke (<anonymous>:wasm-function[5026]:0xd53cc)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4524]:0xbf243)
    at do_runtime_invoke (<anonymous>:wasm-function[1722]:0x498ea)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[337]:0xab5e)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4281]:0xb4809)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[3580]:0x9b948)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3579]:0x9b411)
    at do_icall (<anonymous>:wasm-function[5458]:0xed06e)
    at do_icall_wrapper (<anonymous>:wasm-function[1723]:0x499a1)
    at interp_exec_method (<anonymous>:wasm-function[1244]:0x2b452)
    at interp_runtime_invoke (<anonymous>:wasm-function[5026]:0xd53cc)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4524]:0xbf243)
    at do_runtime_invoke (<anonymous>:wasm-function[1722]:0x498ea)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[434]:0xe4ed)
    at mono_runtime_invoke (<anonymous>:wasm-function[4286]:0xb4b6e)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[4089]:0xaee5c)
    at Module._mono_wasm_invoke_method (dotnet.js:1:185998)
    at Object.init (runtime.js:354:15)
    at runtime.js:233:9
    at dotnet.js:1:126531
WASM-ERR: * Assertion at /Users/alexander/dev/runtime/src/mono/mono/mini/mini-exceptions.c:2673, condition `<disabled>' not met
WASM-ERR:
ABORT: undefined
Stacktrace:

Error
    at Object.onAbort (runtime.js:160:13)
    at abort (dotnet.js:1:14661)
    at _abort (dotnet.js:1:103699)
    at wasm_logger (<anonymous>:wasm-function[2885]:0x8b80e)
    at eglib_log_adapter (<anonymous>:wasm-function[5439]:0xebfd5)
    at monoeg_g_logstr (<anonymous>:wasm-function[4056]:0xae177)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[1986]:0x57acb)
    at monoeg_assertion_message (<anonymous>:wasm-function[375]:0xbcf7)
    at mono_assertion_message (<anonymous>:wasm-function[187]:0x4e5b)
    at mono_assertion_message_disabled (<anonymous>:wasm-function[112]:0x2fba)
    at mono_handle_exception_internal (<anonymous>:wasm-function[2277]:0x62945)
    at mono_handle_exception (<anonymous>:wasm-function[2278]:0x62a05)
    at interp_throw (<anonymous>:wasm-function[130]:0x378f)
    at interp_exec_method (<anonymous>:wasm-function[1244]:0x2b48c)
    at interp_runtime_invoke (<anonymous>:wasm-function[5026]:0xd53cc)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4524]:0xbf243)
    at do_runtime_invoke (<anonymous>:wasm-function[1722]:0x498ea)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[337]:0xab5e)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4281]:0xb4809)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[3580]:0x9b948)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3579]:0x9b411)
    at do_icall (<anonymous>:wasm-function[5458]:0xed06e)
    at do_icall_wrapper (<anonymous>:wasm-function[1723]:0x499a1)
    at interp_exec_method (<anonymous>:wasm-function[1244]:0x2b452)
    at interp_runtime_invoke (<anonymous>:wasm-function[5026]:0xd53cc)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4524]:0xbf243)
    at do_runtime_invoke (<anonymous>:wasm-function[1722]:0x498ea)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[434]:0xe4ed)
    at mono_runtime_invoke (<anonymous>:wasm-function[4286]:0xb4b6e)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[4089]:0xaee5c)
    at Module._mono_wasm_invoke_method (dotnet.js:1:185998)
    at Object.init (runtime.js:354:15)
    at runtime.js:233:9
    at dotnet.js:1:126531
```

**Comment by vargaz** [comment]
I can't repro this with master.

**Comment by lewing** [comment]
me either, opened #40235
