### ISSUE TITLE
WASM: System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestNullRefReturnOfPointer crashes

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#39380]
```
    at 201119 (dotnet.js:1:18045)
    at _emscripten_asm_const_iii (dotnet.js:1:18230)
    at wasm_logger (<anonymous>:wasm-function[2877]:0x8b367)
    at eglib_log_adapter (<anonymous>:wasm-function[5428]:0xeb9e0)
    at monoeg_g_logstr (<anonymous>:wasm-function[4046]:0xadc1f)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[1980]:0x5794e)
    at monoeg_assertion_message (<anonymous>:wasm-function[373]:0xbc39)
    at mono_assertion_message (<anonymous>:wasm-function[186]:0x4dbf)
    at mono_assertion_message_disabled (<anonymous>:wasm-function[111]:0x2f24)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4271]:0xb4448)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[3572]:0x9b4c3)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3571]:0x9af8c)
    at do_icall (<anonymous>:wasm-function[5447]:0xeca78)
    at do_icall_wrapper (<anonymous>:wasm-function[1716]:0x49818)
    at interp_exec_method (<anonymous>:wasm-function[1240]:0x2b268)
    at interp_runtime_invoke (<anonymous>:wasm-function[5017]:0xd4ec2)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4514]:0xbecdd)
    at do_runtime_invoke (<anonymous>:wasm-function[1715]:0x49761)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[335]:0xab04)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4271]:0xb42ad)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[3572]:0x9b4c3)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3571]:0x9af8c)
    at do_icall (<anonymous>:wasm-function[5447]:0xeca78)
    at do_icall_wrapper (<anonymous>:wasm-function[1716]:0x49818)
    at interp_exec_method (<anonymous>:wasm-function[1240]:0x2b268)
    at interp_runtime_invoke (<anonymous>:wasm-function[5017]:0xd4ec2)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4514]:0xbecdd)
    at do_runtime_invoke (<anonymous>:wasm-function[1715]:0x49761)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[430]:0xe260)
    at mono_runtime_invoke (<anonymous>:wasm-function[4276]:0xb4612)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[4079]:0xae904)
    at Module._mono_wasm_invoke_method (dotnet.js:1:185511)
    at Object.init (runtime.js:354:15)
    at runtime.js:233:9
    at dotnet.js:1:126061
WASM-ERR: * Assertion at /Users/santifdezm/repos/runtime/src/mono/mono/metadata/object.c:5740, condition `<disabled>' not met
WASM-ERR: 
ABORT: undefined
Stacktrace: 
Error
    at Object.onAbort (runtime.js:160:13)
    at abort (dotnet.js:1:14661)
    at _abort (dotnet.js:1:103229)
    at wasm_logger (<anonymous>:wasm-function[2877]:0x8b38b)
    at eglib_log_adapter (<anonymous>:wasm-function[5428]:0xeb9e0)
    at monoeg_g_logstr (<anonymous>:wasm-function[4046]:0xadc1f)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[1980]:0x5794e)
    at monoeg_assertion_message (<anonymous>:wasm-function[373]:0xbc39)
    at mono_assertion_message (<anonymous>:wasm-function[186]:0x4dbf)
    at mono_assertion_message_disabled (<anonymous>:wasm-function[111]:0x2f24)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4271]:0xb4448)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[3572]:0x9b4c3)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3571]:0x9af8c)
    at do_icall (<anonymous>:wasm-function[5447]:0xeca78)
    at do_icall_wrapper (<anonymous>:wasm-function[1716]:0x49818)
    at interp_exec_method (<anonymous>:wasm-function[1240]:0x2b268)
    at interp_runtime_invoke (<anonymous>:wasm-function[5017]:0xd4ec2)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4514]:0xbecdd)
    at do_runtime_invoke (<anonymous>:wasm-function[1715]:0x49761)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[335]:0xab04)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[4271]:0xb42ad)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[3572]:0x9b4c3)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[3571]:0x9af8c)
    at do_icall (<anonymous>:wasm-function[5447]:0xeca78)
    at do_icall_wrapper (<anonymous>:wasm-function[1716]:0x49818)
    at interp_exec_method (<anonymous>:wasm-function[1240]:0x2b268)
    at interp_runtime_invoke (<anonymous>:wasm-function[5017]:0xd4ec2)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4514]:0xbecdd)
    at do_runtime_invoke (<anonymous>:wasm-function[1715]:0x49761)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[430]:0xe260)
    at mono_runtime_invoke (<anonymous>:wasm-function[4276]:0xb4612)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[4079]:0xae904)
    at Module._mono_wasm_invoke_method (dotnet.js:1:185511)
    at Object.init (runtime.js:354:15)
    at runtime.js:233:9
    at dotnet.js:1:126061
```

It is hitting this assert: https://github.com/dotnet/runtime/blob/4e1ada2aa1419634f3728ce9c09458654db3f411/src/mono/mono/metadata/object.c#L5740

```cs
TestClassIntPointer tc = new TestClassIntPointer(null);

PropertyInfo p = typeof(TestClassIntPointer).GetProperty(nameof(TestClassIntPointer.NullRefReturningProp));
Assert.NotNull(p);
Assert.Throws<NullReferenceException>(() => p.GetValue(tc));

private sealed unsafe class TestClassIntPointer
{
    private int* _value;

    public TestClassIntPointer(int* value) { _value = value; }
    public ref int* RefReturningProp => ref _value;
    public ref int* NullRefReturningProp => ref *(int**)null;
}
```

It is crashing when doing `p.GetValue(tc)` instead of throwing a `NullReferenceException`

cc: @akoeplinger @marek-safar @steveisok

**Comment by marek-safar** [comment]
@vargaz could you please look into this?
