### ISSUE TITLE
IOException when viewing XpsDocument with DocumentViewer

### ISSUE THREAD

**Issue by MarioZ** [dotnet/runtime#39430]
I'm getting an `IOException` and "_Entries cannot be opened multiple times in Update mode._" message when providing `XpsDocument` to `DocumentViewer` control.

The issue occurs only in .NET Core, it doesn't occur in the .NET Framework.

I'm generating the `XpsDocument` in-memory and displaying it with `DocumentViewer`, but this issue can also be reproduced by creating the `XpsDocument ` from the XPS file, [see this repro project](https://github.com/MarioZ/Issue-XpsDocument-IOException).

After loading the XPS file, you need to do some actions/movements on the `DocumentViewer` control and eventually, the exception will occur. For instance, you can zoom in and out, hover inside and outside, click inside and outside the control, etc.
I didn't determine exactly what action causes the issue, sometimes it is on mouse movement, sometimes it is on mouse click...

Anyway, what I did notice is that the issue doesn't occur when file access is `Read`, not `ReadWrite`.
Also, the issue doesn't occur when the XPS content doesn't contain any image.

```
System.IO.IOException
  HResult=0x80131620
  Message=Entries cannot be opened multiple times in Update mode.
  Source=System.IO.Compression
  StackTrace:
   at System.IO.Compression.ZipArchiveEntry.OpenInUpdateMode()
   at System.IO.Compression.ZipArchiveEntry.Open()
   at System.IO.Packaging.ZipStreamManager.Open(ZipArchiveEntry zipArchiveEntry, FileMode streamFileMode, FileAccess streamFileAccess)
   at System.IO.Packaging.ZipPackagePart.GetStreamCore(FileMode streamFileMode, FileAccess streamFileAccess)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource)
   at System.Windows.Documents.FixedElement.GetImage()
   at System.Windows.Documents.FixedElement.GetObject()
   at System.Windows.Documents.FlowPosition.GetAdjacentElement(LogicalDirection dir)
   at System.Windows.Documents.FixedTextPointer.System.Windows.Documents.ITextPointer.GetAdjacentElement(LogicalDirection direction)
   at System.Windows.Documents.DocumentSequenceTextPointer.xGapAwareGetEmbeddedElement(DocumentSequenceTextPointer thisTp, LogicalDirection direction)
   at System.Windows.Documents.DocumentSequenceTextPointer.GetAdjacentElement(DocumentSequenceTextPointer thisTp, LogicalDirection direction)
   at System.Windows.Documents.DocumentSequenceTextPointer.System.Windows.Documents.ITextPointer.GetAdjacentElement(LogicalDirection direction)
   at System.Windows.Documents.TextEditorMouse.GetUIElementWhenMouseOver(TextEditor This, Point mouseMovePoint)
   at System.Windows.Documents.TextEditorMouse.UpdateCursor(TextEditor This, Point mouseMovePoint)
   at System.Windows.Documents.TextEditorMouse.OnMouseMoveWithoutFocus(TextEditor This, MouseEventArgs e)
   at System.Windows.Documents.TextEditorMouse.OnMouseMove(Object sender, MouseEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.MouseDevice.Synchronize()
   at System.Windows.Input.MouseDevice.OnHitTestInvalidatedAsync(Object sender, EventArgs e)
   at System.Windows.Input.InputManager.HitTestInvalidatedAsyncCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at WpfApp1.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]
```

**Comment by MarioZ** [comment]
I don't have write-permissions, but I think the "area-System.IO.Compression" should be used, just like in #24962 and #27397.

**Comment by am11** [comment]
Related issue: https://github.com/dotnet/wpf/issues/3206.

**Comment by Chapre** [comment]
Any solution to this? having the really same nnoying issue

**Comment by MarioZ** [comment]
@Chapre how exactly are you creating your `XpsDocument`?

In my case, I was able to obtain an XPS stream which enabled me to do this file access change in memory:

```cs
MemoryStream xpsStream = ...

var package = Package.Open(xpsStream, FileMode.Open, FileAccess.Read);
var uri = new Uri($"memorystream://{Guid.NewGuid():N}.xps");
PackageStore.AddPackage(uri, package);

this.xps = new XpsDocument(package, CompressionOption.NotCompressed, uri.AbsoluteUri);
this.viewer.Document = this.xps.GetFixedDocumentSequence();
```

**Comment by NickKhilko** [comment]
@MarioZ i got the same exception, but when i tried to write the xps document with pagination.
And i saw your question on closed issue that looks more like mine.
My solution was divide read and write file access

```c#
....
//saving flow document as xps
using (var xpsDocument = new XpsDocument(__TempFileName, **FileAccess.Read**)) //was  **FileAccess.ReadWrite**
{
FixedDocumentSequence fixedDocSeq = xpsDocument.GetFixedDocumentSequence();
var documentPaginator documentPaginator = fixedDocSeq.DocumentPaginator;
...
using (var newDoc = new XpsDocument(fileName, **FileAccess.Write**))
{
...
XpsDocumentWriter writer = PrintQueue.CreateXpsDocumentWriter(__PrintQueue);
....
writer.Write(documentPaginator);
xpsDocument.Close();   
}
}

> ...
 ```
 Something like this in .net 5.0
 
 Sorry for formatting, my first comment ever

**Comment by PeterPandefu** [comment]
I have the same problem,please fix it soon

**Comment by PeterPandefu** [comment]
What's more, I can't print,Using XpsDocument with DocumentViewer

**Comment by danmoseley** [comment]
Would you be interested in debugging into it @PeterPandefu ?

**Comment by PeterPandefu** [comment]
> Would you be interested in debugging into it @PeterPandefu ?

what should I do?

**Comment by PeterPandefu** [comment]
> Would you be interested in debugging into it @PeterPandefu ?

Is such that.
I have the same problem as him@MarioZ. I using XpsDocument with DocumentViewer and FlowDocument in WPF, 
LoadXps like this:
```c#
using (MemoryStream ms = new MemoryStream())
    {
        using (Package package = Package.Open(ms, FileMode.Create, FileAccess.ReadWrite))
        {
            Uri DocumentUri = new Uri("pack://InMemoryDocument.xps");
            PackageStore.RemovePackage(DocumentUri);
            PackageStore.AddPackage(DocumentUri, package);
            using (XpsDocument xpsDocument = new XpsDocument(package, CompressionOption.Fast, DocumentUri.AbsoluteUri))
            {
                XpsDocumentWriter writer = XpsDocument.CreateXpsDocumentWriter(xpsDocument);
                //m_doc is FlowDocument;
                writer.Write(((IDocumentPaginatorSource)m_doc).DocumentPaginator);
                docViewer.Document = xpsDocument.GetFixedDocumentSequence();
                xpsDocument.Close();
            }
        }
    }
}
catch (Exception ex)
{
    throw; 
}
```

If My FlowDocument Contain Image ,This error will appear,otherwise no
And The issue occurs only in .NET Core, it doesn't occur in the .NET Framework.
I don't konw my description is detailed?
I wish you can help me.Thanks!

**Comment by karelz** [comment]
Triage: Looks like this needed debugging, which didn't happen in last 5 years. There does not seem to be actionable repro. Closing.
Let us know if we missed some key points, we will be happy to reconsider.

**Comment by MarioZ** [comment]
@karelz Of course the repo project is removed, it's been so many years. Nevertheless, it can be easily recreated, and all the information to do so is available here.
Perhaps the issue is now resolved?

Anyway, I think it's silly the way you guys handle the issues, so basically ignore it for a couple of years, then just close it with some silly excuse/explanation. And the cherry on top is the status with which it's closed, "Closed as not planned"...

**Comment by karelz** [comment]
My originally response got somehow lost :/, so trying again ...

> Nevertheless, it can be easily recreated, and all the information to do so is available here.

I do not see any simple way how to get to a simple repro (ideally without WPF). Given that the posts mention specifically WPF and given the call stack in original post, I think it is high chance the problem is in WPF, not in Compression. WPF wants SeekableStream, which under the hood opens the archive in Update mode, which obviously you cannot do more than once.
Naively, I'd say that caller needs to make sure the SeekableStream is not created twice for the same archive. Perhaps due to some race condition?

Sadly, we are not skilled in debugging WPF to help here. Someone needs to get it under debugger and find out what is going on and which component (WPF or Compression) is at fault.
If someone provides more actionable information, pointing at Compression, we'll be happy to reconsider and potentially reopen the issue ... it might make it actionable for us.

> I think it's silly the way you guys handle the issues, so basically ignore it for a couple of years, then just close it with some silly excuse/explanation.

I understand it can be frustrating to see an issue without update for years - sadly we do not have infinite resources and with the volume of PRs and issues we are handling, things sometimes slip through. This one did. Sorry for that.
In ideal world, the above assessment from me would have been made 5 years ago and the issue would be closed for all that time. Still I'd say it's "better late than never".

> And the cherry on top is the status with which it's closed, "Closed as not planned"...

The status represents our assessment - we do not plan to work on it. The cost of actionable repro for this issue is high, and the chance it is not relevant to Compression / BCL is significant. The number of affected customers is low-ish (6 upvotes in 5 years).
Sadly, we just don't have the time to invest into these kind of problems. We focus on issues which have either higher business impact (more customers impacted), or are straightforward (clear simple repros, which lead to straightforward fixes). That's where we can deliver best value for .NET developers, our customers.

In the past, we considered automated closing of issues without any progress in some time period (6-12 months if I remember correctly). I am personally not a fan of such solution, because the closures are bulk edits, which is more dismissive than when a person writes something and really looks at the issue and considers it. However, it would have solved in this case the problem of the issue becoming stale without progress and response.
I personally prefer regular backlog grooming/retriage (ideally 1y cadence) ... which is exactly what we do now for Compression area when it came into our scope of ownership recently.

I hope the above helps to explain the background here.
If we are wrong in some of the statements, feel free to raise it. Nobody's perfect, we are all just trying to do our best.

**Comment by MarioZ** [comment]
@karelz I also believe that the issue is probably specific to WPF (or `DocumentViewer` control), so perhaps a better option than just closing it with "Closed as not planned" is to suggest where the issue should be reported instead.

**Comment by karelz** [comment]
@MarioZ I do not think the issue is ready in current form to be filed against WPF yet. Somebody needs to do a bit more digging before it is actionable for WPF team.
That said, you can find WPF in dotnet/wpf repo.
