### ISSUE TITLE
SocketsHttpHandlerTest_Http2.GoAwayFrame_NewRequest_NewConnection test failure on Windows

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#39475]
https://helix.dot.net/api/2019-06-17/jobs/802052ef-d341-4c6b-94fe-54771d721591/workitems/System.Net.Http.Functional.Tests/console

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.GoAwayFrame_NewRequest_NewConnection [FAIL]
      System.Net.Sockets.SocketException : Se ha forzado la interrupcion de una conexion existente por el host remoto.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(4844,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3545,0): at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
        /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs(271,0): at System.Net.Test.Common.Http2LoopbackConnection.ShutdownSend()
        /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs(280,0): at System.Net.Test.Common.Http2LoopbackConnection.WaitForConnectionShutdownAsync(Boolean ignoreUnexpectedFrames)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(643,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.GoAwayFrame_NewRequest_NewConnection()
        --- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=733906&view=results

cc: @dotnet/ncl

**Comment by wfurt** [comment]
~12 failures in last few days - mix of CI & PRs.

**Comment by jaredpar** [comment]
No failures in last 14 days. closing.
