### ISSUE TITLE
Test failure: System.Tests.TimeZoneInfoTests.BinaryFormatter_RoundTrips

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39499]
failed in job: [runtime 20200716.146 ](https://dev.azure.com/dnceng/public/_build/results?buildId=734524&view=ms.vss-test-web.build-test-results-tab&runId=22732908&resultId=137481&paneView=debug)

Error message
~~~
System.PlatformNotSupportedException : BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.


Stack trace
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at System.Tests.TimeZoneInfoTests.BinaryFormatter_RoundTrips(TimeZoneInfo timeZone)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
~~~

**Comment by GrabYourPitchforks** [comment]
I think this was fixed by https://github.com/dotnet/runtime/pull/39487?
