### ISSUE TITLE
Crossgen2 fails with TableIndexOutOfRangeException

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#39493]
Try to compile the repro listed in https://github.com/dotnet/runtime/issues/13339 using crossgen2. It fails with the following stack:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'tableIndex')
   at System.Reflection.Throw.TableIndexOutOfRange()
   at System.Reflection.Metadata.Ecma335.MetadataTokens.Handle(TableIndex tableIndex, Int32 rowNumber)
   at ILCompiler.DependencyAnalysis.ReadyToRun.CopiedMetadataBlobNode.WriteFieldRvas(NodeFactory factory, ObjectDataBuilder& builder, BlobReader& reader) in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\CopiedMetadataBlobNode.cs:line 85
   at ILCompiler.DependencyAnalysis.ReadyToRun.CopiedMetadataBlobNode.GetData(NodeFactory factory, Boolean relocsOnly) in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\CopiedMetadataBlobNode.cs:line 134
   at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory) in C:\git\fork\runtime\src\coreclr\src\tools\Common\Compiler\DependencyAnalysis\ObjectNode.cs:line 60
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.DependencyAnalysisFramework\DependencyAnalyzer.cs:line 180
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.DependencyAnalysisFramework\DependencyAnalyzer.cs:line 247
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.DependencyAnalysisFramework\DependencyAnalyzer.cs:line 298
   at ILCompiler.ReadyToRunCodegenCompilation.RewriteComponentFile(String inputFile, String outputFile, String ownerExecutableName) in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.ReadyToRun\Compiler\ReadyToRunCodegenCompilation.cs:line 355
   at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in C:\git\fork\runtime\src\coreclr\src\tools\aot\ILCompiler.ReadyToRun\Compiler\ReadyToRunCodegenCompilation.cs:line 319
   at ILCompiler.Program.Run() in C:\git\fork\runtime\src\coreclr\src\tools\aot\crossgen2\Program.cs:line 545
   at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) in C:\git\fork\runtime\src\coreclr\src\tools\aot\crossgen2\Program.cs:line 655
```

**Comment by MichalStrehovsky** [comment]
I see RewriteComponentFile in the stack - this is a WPF application and therefore Managed C++. The input is probably sneaking past the checks @trylek added in #38113.

**Comment by mangod9** [comment]
Thanks @MichalStrehovsky for taking a look. Will assign to @trylek so we can handle this case.
