### ISSUE TITLE
wasm release/5.0-preview8 test failure: System.Runtime.InteropServices.Tests.dll System.NullReferenceException

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/runtime#39520]
There is a failure on release/5.0-preview8 in System.Tests.BitConverterArray.ConvertFromUInt

[testResults.xml](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-50-preview87d439295e58f4c8eb8/System.Runtime.Extensions.Tests/testResults.xml?sv=2019-02-02&se=2020-08-06T08%3A33%3A31Z&sr=c&sp=rl&sig=a7Uz2FecLJAwQSJbnnybfEnk65agWoaP7w%2F2UmYzyio%3D)

`System.NullReferenceException : Object reference not set to an instance of an object.`

```
   at System.Reflection.CustomAttributeTypedArgument.CanonicalizeValue(Object value)
   at System.Reflection.CustomAttributeTypedArgument..ctor(Type argumentType, Object value)
   at System.Reflection.CustomAttributeData.ResolveArguments()
   at System.Reflection.CustomAttributeData.get_ConstructorArguments()
   at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
```

https://helix.dot.net/api/2019-06-17/jobs/7d439295-e58f-4c8e-b815-613b73e50347/workitems/System.Runtime.Extensions.Tests/

https://dnceng.visualstudio.com/public/_build/results?buildId=734993&view=results

cc @Anipik

**Comment by Anipik** [comment]
Its a copy of this https://github.com/dotnet/runtime/issues/39473

**Comment by danmosemsft** [comment]
duplicate. that one is also preview 8
