### ISSUE TITLE
Getting Socket Exception, high response time and Http 500 when performance testing using JMeter

### ISSUE THREAD

**Issue by vahida** [dotnet/runtime#39546]
Hi, 
We are currently running performance testing using JMeter (results attached) by sending concurrent requests to our API.
Getting high response time and HTTP 500 and netstat result showing lots of Time_Wait. After 2 minute ramp up we start seeing degradation in response times and timeouts on requests that exceed the 100s default timeout (these show up as HTTP 500 Errors)

JMeter at peak - 50 concurrent threads hammering at 5 TPS 
Downstream API takes 1.5 sec (average), 2.01 sec (90th percentile)
Downstream API  is able to achieve 4.9 TPS

- Used ASP .NET Core v3.1.0, hosted on Windows Server 2016 8 Core, IIS In-Process Hosting Model
- Used named HttpClient and typed client registered in DI and IHttpClientFactory to inject it through constructor. 
- There is no async blocker in the code path and only one HTTP GET call to an external API deployed in different machine and same domain.
- Didn't change any of HttpClient handler settings. Everything is by default.
- Don't dispose HttpClient instance created by HttpClientFactory !
- Excluded load balancer in the middle and tried to hit external API directly. (Just in case if wondering there is something in the middle)

We also built a bare bones api in order to exclude our custom middlewares, handlers including logging. However, still getting the same result. Here is the[ source code](https://github.com/vahida/Issue-24041) - This is not the original nor prod ready code and only to show two different ways of firing http calls.

Please let me know if we need to update any configuration setting at application or OS level.
Appreciate your help.
Thanks.

Stack trace:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ....FetchClientByNumber(Int32 memberNumber) in D:\TFS\....
   at ....MembersController.GetMemberByMemberNumber(GetMemberByMemberNumberRequest memberNumberRequest) in D:\TFS\....
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

![PT_01](https://user-images.githubusercontent.com/6835254/87737242-c1d83400-c81d-11ea-982d-01897bdb0cfa.JPG)
![PT_02](https://user-images.githubusercontent.com/6835254/87737248-c6045180-c81d-11ea-9f1d-9e80562ba734.JPG)

**Comment by scalablecory** [comment]
@vahida this exception indicates you are either elapsing `HttpClient.Timeout` (which defaults to 100 seconds) or are triggering a cancellation token.

Try setting `HttpClient.Timeout` to `Timeout.InfiniteTimeSpan` here as an easy way to confirm.

**Comment by vahida** [comment]
H @scalablecory , Thanks for the reply. Please find attached the result after applying your suggestion.
![Capture](https://user-images.githubusercontent.com/6835254/88139615-69e16900-cc33-11ea-84b8-a02b01e73804.JPG)
![Capture1](https://user-images.githubusercontent.com/6835254/88139627-6d74f000-cc33-11ea-9591-9df43a3eb7d2.JPG)

**Comment by vahida** [comment]
The problem was session lock contention with - 3rd party - down stream API (ASP .NET Web API 2). It is solved by disabling the session state in IIS.  Basically not a ASP .NET Core/Http Client coding or hosting problem.

**Comment by karelz** [comment]
Great, closing as resolved then.
