### ISSUE TITLE
Test failure: System.Net.Tests.HttpWebRequestTest_Sync.GetResponseAsync_ParametersAreNotCachable_CreateNewClient

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39619]
failed in job: [runtime-coreclr libraries-jitstress2-jitstressregs 20200718.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=736792&view=ms.vss-test-web.build-test-results-tab&runId=22820312&resultId=156897&paneView=debug)

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse() in /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1025
   at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass129_0.<GetResponseAsync_ParametersAreNotCachable_CreateNewClient>b__1() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1661
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 497
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2356
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 241
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 266
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2320
--- End of stack trace from previous location ---
   at System.Net.Tests.HttpWebRequestTest.VerifyResponse(String expectedResponse, Task`1 responseTask) in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1911
   at System.Net.Tests.HttpWebRequestTest.<>c.<<GetResponseAsync_ParametersAreNotCachable_CreateNewClient>b__129_0>d.MoveNext() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1667
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.Requests.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Tests.HttpWebRequestTest+<>c System.Threading.Tasks.Task <GetResponseAsync_ParametersAreNotCachable_CreateNewClient>b__129_0(System.String, System.String, System.String)

Child arguments:
  False, {"AutomaticDecompression":1,"AllowAutoRedirect":false,"MaximumAutomaticRedirections":2,"MaximumResponseHeadersLength":100,"PreAuthenticate":true,"Timeout":10000,"SslProtocols":3072,"CheckCertificateRevocationList":false,"NewCredentials":false,"NewProxy":false,"NewServerCertificateValidationCallback":true,"NewClientCertificates":false,"NewCookieContainer":false}, False
~~~

**Comment by BruceForstall** [comment]
This failure is occuring in a variety of different test runs, including:

`runtime-coreclr libraries-jitstress`:

`net5.0-Windows_NT-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open`
`net5.0-Windows_NT-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open`
https://dev.azure.com/dnceng/public/_build/results?buildId=737443&view=ms.vss-test-web.build-test-results-tab&runId=22837402&paneView=debug

`runtime-coreclr libraries-jitstress2-jitstressregs`:

`net5.0-Windows_NT-Release-x86-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open`
`net5.0-Windows_NT-Release-x86-CoreCLR_checked-jitstress2_jitstressregs4-Windows.10.Amd64.Open`
https://dev.azure.com/dnceng/public/_build/results?buildId=736792&view=ms.vss-test-web.build-test-results-tab&runId=22820306&paneView=debug

**Comment by ManickaP** [comment]
Triage: I need to investigate, it's likely due to change from async to sync in `HttpWebRequest.GetResponse`

**Comment by ManickaP** [comment]
So this failure has been happening before the change, it's also happening not just for sync, but for async as well and it just looks like slow infra and low timeouts.
I've ran the offending test locally in a loop for a few hours and no occurrence.
Adjusting the timeouts little bit in a PR and we'll see. But highly unlikely this is production code bug.
