### ISSUE TITLE
Could not load assembly on published project

### ISSUE THREAD

**Issue by heggi** [dotnet/runtime#39762]
### Description

Project builded, but can not run with error: 
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at XRadAuth.Program.Main() in /home/xxx/rpmbuild/BUILD/xrad/XRadAuth/Program.cs:line 16
```

If I downgrade SDK to 3.1.201 and leave runtime at 3.1.6 - works fine.

From .deps.json file:
```
     "Microsoft.Extensions.Logging.Abstractions/3.1.6": {
        "runtime": {
          "lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll": {
            "assemblyVersion": "3.1.6.0",
            "fileVersion": "3.100.620.31605"
          }
        }
      },
```

Project file:
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.6" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.6" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.6" />
        <PackageReference Include="NLog" Version="4.7.2" />
        <PackageReference Include="NLog.Extensions.Logging" Version="1.6.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.6" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.6" />
        <PackageReference Include="NetEscapades.Configuration.Yaml" Version="2.0.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.4" />
    </ItemGroup>

</Project>
```

### Configuration

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  3.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by heggi** [comment]
dotnet publish place Microsoft.Extensions.Logging.Abstractions.dll version 2.1.1,  but must be 3.1.6.
Manual replace dll with correct version do app running fine again.

**Comment by heggi** [comment]
Problem was with publishing two app in one directory (one project with two executable files)
One of projects (cli tool) has dependency Grpc.Net.Client, what has dep Microsoft.Extensions.Logging.Abstractions 2.1.1 and nothing any.
Sequential launch for each project `dotnet publish` replaced lib 3.1.6 with 2.1.1 (cli tool build lastest)
Previous versions of SDK don't replace libs with old versions.

Problem solved with add `<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.6" />` to cli.csproj
