### ISSUE TITLE
Test failure: profiler/eventpipe/eventpipe/eventpipe.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39932]
CoreCLR Linux arm64 Checked gcstress0x3

https://dev.azure.com/dnceng/public/_build/results?buildId=746110&view=ms.vss-test-web.build-test-results-tab&runId=23125998&paneView=debug

with:
```
export COMPlus_TieredCompilation=0
export COMPlus_GCStress=0x3
```

```
+ dotnet /root/helix/work/correlation/xunit.console.dll profiler/eventpipe/profiler.eventpipe.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=profiler.eventpipe
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 5.0.0-preview.8.20361.2)
  Discovering: profiler.eventpipe.XUnitWrapper
  Discovered:  profiler.eventpipe.XUnitWrapper
  Starting:    profiler.eventpipe.XUnitWrapper
    profiler/eventpipe/eventpipe/eventpipe.sh [FAIL]
      Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
         at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 136
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 90
         at EventPipeTests.EventPipe.Main(String[] args) in /Users/runner/work/1/s/src/tests/profiler/eventpipe/eventpipe.cs:line 31
      apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa4b2b270)
      /root/helix/work/workitem/profiler/eventpipe/eventpipe/eventpipe.sh: line 333:   150 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
```

Related? https://github.com/dotnet/runtime/issues/39669

@davmason

**Comment by BruceForstall** [comment]
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=746876&view=ms.vss-test-web.build-test-results-tab&runId=23150822&resultId=100010&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr jitstress 20200728.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=749233&view=ms.vss-test-web.build-test-results-tab&runId=23231242&resultId=100001&paneView=debug)

failed test: profiler/eventpipe/eventpipe/eventpipe.sh


Error message
~~~
libc++abi.dylib: terminating with uncaught exception of type PAL_SEHException
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 136
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 90
   at EventPipeTests.EventPipe.Main(String[] args) in /Users/runner/work/1/s/src/tests/profiler/eventpipe/eventpipe.cs:line 31
task_for_pid(9627) FAILED 5 (os/kern) failure
/private/tmp/helix/working/BB0A09E0/w/A6E90927/e/profiler/eventpipe/eventpipe/eventpipe.sh: line 340:  9627 Abort trap: 6           $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/BB0A09E0/w/A6E90927/e/profiler/eventpipe/Reports/profiler.eventpipe/eventpipe/eventpipe.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/BB0A09E0/p/corerun eventpipe.dll ''
Profiler path: /private/tmp/helix/working/BB0A09E0/w/A6E90927/e/profiler/eventpipe/eventpipe/libProfiler.dylib
Profiler path: /private/tmp/helix/working/BB0A09E0/w/A6E90927/e/profiler/eventpipe/eventpipe/libProfiler.dylib
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
This method being jitted should trigger events firing...
TriggerMethod found! Sending event...

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Writing minidump with heap to file /cores/coredump.9627.dmp
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/BB0A09E0/p
> /private/tmp/helix/working/BB0A09E0/w/A6E90927/e/profiler/eventpipe/eventpipe/eventpipe.sh
Expected: True
Actual:   False


Stack trace
   at profiler_eventpipe._eventpipe_eventpipe_._eventpipe_eventpipe_sh() in /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/profiler.eventpipe/profiler.eventpipe.XUnitWrapper.cs:line 140
~~~

**Comment by tommcdon** [comment]
This looks like a duplicate to #36195
