### ISSUE TITLE
[wasm] RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#40042]
From here: https://helix.dot.net/api/2019-06-17/jobs/319ba90b-af16-4898-852f-53242c8e9656/workitems/System.Threading.Tasks.Tests/console

```
[19:28:51] dbug: test[0]
      JS exception: RuntimeError: memory access out of bounds
      
[19:28:51] dbug: test[0]
      RuntimeError: memory access out of bounds
      
[19:28:51] dbug: test[0]
          at get_virtual_method_fast (<anonymous>:wasm-function[10393]:0x18629f)
      
[19:28:51] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[2153]:0x44a5d)
      
[19:28:51] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[7870]:0x12e944)
      
[19:28:51] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[7352]:0x1183f7)
      
[19:28:51] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x78f79)
      
[19:28:51] dbug: test[0]
          at mono_runtime_invoke_checked (<anonymous>:wasm-function[526]:0x1003e)
      
[19:28:51] dbug: test[0]
          at mono_runtime_try_invoke_array (<anonymous>:wasm-function[7119]:0x10deca)
      
[19:28:51] dbug: test[0]
          at ves_icall_InternalInvoke (<anonymous>:wasm-function[6245]:0xed397)
      
[19:28:51] dbug: test[0]
          at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[6244]:0xece5b)
      
[19:28:51] dbug: test[0]
          at do_icall (<anonymous>:wasm-function[10631]:0x1953bb)
      
[19:28:51] dbug: test[0]
          at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79030)
      
[19:28:51] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[2153]:0x448a6)
      
[19:28:51] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[7870]:0x12e944)
      
[19:28:51] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[7352]:0x1183f7)
      
[19:28:51] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x78f79)
      
[19:28:51] dbug: test[0]
          at mono_runtime_try_invoke (<anonymous>:wasm-function[667]:0x13db6)
      
[19:28:51] dbug: test[0]
          at mono_runtime_invoke (<anonymous>:wasm-function[7123]:0x10e215)
      
[19:28:51] dbug: test[0]
          at mono_wasm_invoke_method (<anonymous>:wasm-function[6929]:0x108693)
      
[19:28:51] dbug: test[0]
          at Module._mono_wasm_invoke_method (dotnet.js:1:191717)
      
[19:28:51] dbug: test[0]
          at Object.init (runtime.js:308:15)
      
[19:28:51] dbug: test[0]
          at Object.config.loaded_cb (runtime.js:175:8)
      
[19:28:51] dbug: test[0]
          at Object._finalize_startup (dotnet.js:1:128651)
      
[19:28:51] dbug: test[0]
          at onPendingRequestComplete (dotnet.js:1:129659)
      
[19:28:51] dbug: test[0]
          at processFetchResponseBuffer (dotnet.js:1:129979)
```

**Comment by SamMonoRT** [comment]
cc @BrzVlad @vargaz

**Comment by BrzVlad** [comment]
From the looks of the stacktrace, this might be a GC related failure. I would like to see this happen again in a more recent build, after zoltan's fix.

**Comment by SamMonoRT** [comment]
@MaximLipnin - does this still happen on a recent build ?

**Comment by MaximLipnin** [comment]
@SamMonoRT I've seen this error once in CI and I don't have a local repro for it.

**Comment by SamMonoRT** [comment]
We'll close this as no additional failures since Zoltan's change was merged.
