### ISSUE TITLE
CI failure in System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.SendAsync_Expect100Continue_RequestBodyFails_ThrowsContentException

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#40057]
helix.dot.net/api/2019-06-17/jobs/6b514377-c659-427c-892c-d5b30caa1fe9/workitems/System.Net.Http.WinHttpHandler.Functional.Tests/console

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/pull/40052

**Comment by wfurt** [comment]
cc: @ManickaP 

```
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.SendAsync_Expect100Continue_RequestBodyFails_ThrowsContentException [FAIL]
      System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(439,0): at System.Net.Sockets.Socket.GetException(SocketError error, Boolean wrapExceptionsInIOExceptions)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(405,0): at System.Net.Sockets.Socket.CompleteAccept(Socket s, TaskSocketAsyncEventArgs`1 saea)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(41,0): at System.Net.Sockets.Socket.<>c.<AcceptAsync>b__284_0(Object s, SocketAsyncEventArgs e)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs(204,0): at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs(643,0): at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs(1271,0): at System.Net.Sockets.SocketAsyncEventArgs.HandleCompletionPortCallbackError(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs(1233,0): at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__177_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
        /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/ClrThreadPoolBoundHandleOverlapped.cs(48,0): at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
        /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs(62,0): at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(93,0): at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(134,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs(2146,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass79_0.<<SendAsync_Expect100Continue_RequestBodyFails_ThrowsContentException>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(96,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(124,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(35,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(37,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs(2133,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.SendAsync_Expect100Continue_RequestBodyFails_ThrowsContentException()
        --- End of stack trace from previous location ---
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Authentication_Test.Credentials_DomainJoinedServerUsesKerberos_UseIpAddressAndHostHeader_Success [SKIP]

```

**Comment by karelz** [comment]
@ManickaP do you know more about this failure? How often does it happen? Is it a recent regression?

**Comment by ManickaP** [comment]
It's fresh from my recent merge, probably test issue, looking at it right now.
