### ISSUE TITLE
[wasm] The unboxing error during the System.Runtime.InteropServices.JavaScript.Tests run 

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#40132]
The raw log from CI: https://helix.dot.net/api/2019-06-17/jobs/672399eb-f936-4a2a-9364-a171d3cc0adb/workitems/System.Runtime.InteropServices.JavaScript.Tests/console

```
[09:05:55] dbug: test[0]
      JS exception: Error: no idea on how to unbox value types
      
[09:05:55] dbug: test[0]
      Error: no idea on how to unbox value types
      
[09:05:55] dbug: test[0]
          at Object.unbox_mono_obj (dotnet.js:1:145228)
      
[09:05:55] dbug: test[0]
          at Object.call_method (dotnet.js:1:157645)
      
[09:05:55] dbug: test[0]
          at Object.is_nested_array (dotnet.js:1:144373)
      
[09:05:55] dbug: test[0]
          at Object.mono_array_to_js_array (dotnet.js:1:144624)
      
[09:05:55] dbug: test[0]
          at Object.mono_wasm_parse_args (dotnet.js:1:163407)
      
[09:05:55] dbug: test[0]
          at _mono_wasm_invoke_js_with_args (dotnet.js:1:170134)
      
[09:05:55] dbug: test[0]
          at do_icall (<anonymous>:wasm-function[10575]:0x193fe4)
      
[09:05:55] dbug: test[0]
          at do_icall_wrapper (<anonymous>:wasm-function[3293]:0x78c7e)
      
[09:05:55] dbug: test[0]
          at interp_exec_method (<anonymous>:wasm-function[2144]:0x4467b)
      
[09:05:55] dbug: test[0]
          at interp_runtime_invoke (<anonymous>:wasm-function[7843]:0x12dfc1)
      
[09:05:55] dbug: test[0]
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[7326]:0x117aee)
      
[09:05:55] dbug: test[0]
          at do_runtime_invoke (<anonymous>:wasm-function[3292]:0x78bc7)
      
[09:05:55] dbug: test[0]
          at mono_runtime_try_invoke (<anonymous>:wasm-function[666]:0x13d31)
      
[09:05:55] dbug: test[0]
          at mono_runtime_invoke (<anonymous>:wasm-function[7097]:0x10d8f4)
      
[09:05:55] dbug: test[0]
          at mono_wasm_invoke_method (<anonymous>:wasm-function[6904]:0x107db9)
      
[09:05:55] dbug: test[0]
          at Module._mono_wasm_invoke_method (dotnet.js:1:191101)
      
[09:05:55] dbug: test[0]
          at Object.init (runtime.js:308:15)
      
[09:05:55] dbug: test[0]
          at Object.config.loaded_cb (runtime.js:175:8)
      
[09:05:55] dbug: test[0]
          at Object._finalize_startup (dotnet.js:1:128074)
      
[09:05:55] dbug: test[0]
          at onPendingRequestComplete (dotnet.js:1:129082)
      
[09:05:55] dbug: test[0]
          at processFetchResponseBuffer (dotnet.js:1:129402)
```

**Comment by MaximLipnin** [comment]
It has been seen recently: https://github.com/dotnet/runtime/pull/39069#issuecomment-663498769

**Comment by lewing** [comment]
cc @pranavkm

**Comment by lewing** [comment]
The error here is that thinks the value is a value type but not a primitive but it doesn't seem to happen all the time.

**Comment by vargaz** [comment]
Seems to be caused by this code in mono_array_to_js_array ():
```
				var ele = this.mono_array_get (mono_array, i);
				if (this.is_nested_array(ele))
					res.push(this.mono_array_to_js_array(ele));
				else
					res.push (this.unbox_mono_obj (ele));
```
So unbox_mono_obj gets passed an objref, but it calls into managed code while the objref is not tracked.

**Comment by marek-safar** [comment]
@kg can this be closed?

**Comment by kg** [comment]
That function has been fixed, but I don't know if the test still fails on CI.

**Comment by MaximLipnin** [comment]
There haven't been any other reports for this issue recently, so it seems to be fixed.
