### ISSUE TITLE
Build for System.Runtime fails within VS 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#40159]
Cleaned and synced to today
```
build.cmd clr+libs -rc release
build.cmd -subset libs.tests -rc release
build.cmd -subset libs.tests -framework net48 -rc release
build -vs System.Runtime
```
Build in VS and it fails with 
```
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.GetVersion(ITaskItem referencePath)
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfo(ITaskItem referencePath)
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfos(IEnumerable`1 referencePaths)
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath)
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
7>C:\git\runtime\.dotnet\sdk\5.0.100-preview.8.20362.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
7>Done building project "System.Runtime.Tests.csproj" -- FAILED.
```
I have a design time binlog available.

Reproes with both VS 16.8.0   and 16.6.5.

From the binlog we know it's when VS is trying to build with TF=Unix.

@ericstj any thoughts? @ViktorHofer and @safern are puzzled.

**Comment by Anipik** [comment]
The issue here is that we have just buid net5.0-windows from the root and trying to build the tests for net5.0-unix as well from the vs.
When we build from the vs, it doesn't build all the project references and expects that these are already built.
Doing a build on tests 
```
1>------ Build started: Project: System.Runtime (ref\System.Runtime), Configuration: Debug Any CPU ------
2>------ Build started: Project: TestUtilities, Configuration: Debug Any CPU ------
3>------ Build started: Project: TestUtilities.Unicode, Configuration: Debug Any CPU ------
1>System.Runtime -> C:\git\runtime\artifacts\bin\System.Runtime\ref\net5.0-Debug\System.Runtime.dll
4>------ Build started: Project: System.Runtime (src\System.Runtime), Configuration: Debug Any CPU ------
2>TestUtilities -> C:\git\runtime\artifacts\bin\TestUtilities\net461-Debug\TestUtilities.dll
3>TestUtilities.Unicode -> C:\git\runtime\artifacts\bin\TestUtilities.Unicode\net5.0-Debug\TestUtilities.Unicode.dll
4>System.Runtime -> C:\git\runtime\artifacts\bin\System.Runtime\net5.0-Debug\System.Runtime.dll
5>------ Build started: Project: TestCollectibleAssembly, Configuration: Debug Any CPU ------
6>------ Build started: Project: TestLoadAssembly, Configuration: Debug Any CPU ------
6>TestLoadAssembly -> C:\git\runtime\artifacts\bin\TestLoadAssembly\netstandard2.0-Debug\TestLoadAssembly.dll
5>TestCollectibleAssembly -> C:\git\runtime\artifacts\bin\TestCollectibleAssembly\netstandard2.0-Debug\TestCollectibleAssembly.dll
2>TestUtilities -> C:\git\runtime\artifacts\bin\TestUtilities\net5.0-Debug\TestUtilities.dll
7>------ Build started: Project: System.Runtime.Tests, Configuration: Debug Any CPU ------
8>------ Build started: Project: System.Runtime.Nls.Tests, Configuration: Debug Any CPU ------
8>System.Runtime.Nls.Tests -> C:\git\runtime\artifacts\bin\System.Runtime.Nls.Tests\net5.0-Windows_NT-Debug\System.Runtime.Nls.Tests.dll
7>System.Runtime.Tests -> C:\git\runtime\artifacts\bin\System.Runtime.Tests\net5.0-Browser-Debug\System.Runtime.Tests.dll
7>System.Runtime.Tests -> C:\git\runtime\artifacts\bin\System.Runtime.Tests\net5.0-Unix-Debug\System.Runtime.Tests.dll
7>System.Runtime.Tests -> C:\git\runtime\artifacts\bin\System.Runtime.Tests\net5.0-Windows_NT-Debug\System.Runtime.Tests.dll
========== Build: 8 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
```

Adding all the project dependencies solve the problem. project dependencies to the sln. 
I dont think this meets the bar   5.0 rc1. @danmosemsft  @ericstj any thoughts ?

**Comment by Anipik** [comment]
We generally require all the project references, but we can make this workflow with just adding system.security.principal.windows

**Comment by ericstj** [comment]
We should also file a bug on the SDK, since they shouldn't NRE when seeing a simple-name reference here: https://github.com/dotnet/sdk/blob/a5f5bb5183517cb301050288b25c9c727e52e8a6/src/Tasks/Microsoft.NET.Build.Tasks/ReferenceInfo.cs#L150

@Anipik / @ViktorHofer why would this test even be *referencing* a `net5.0-unix` configuration.  Even the `unix` build of the test should be using reference assemblies, not implementation.

What I would expect is for RAR to see: C:\git\runtime\artifacts\bin\ref\net5.0\System.Security.Principal.Windows.dll, not C:\git\runtime\artifacts\bin\System.Security.Principal.Windows\net5.0-Unix-Debug\System.Security.Principal.Windows.dll.  In that case RAR should see an assembly and be able to set `FusionName` metadata correctly.

**Comment by ViktorHofer** [comment]
> What I would expect is for RAR to see: C:\git\runtime\artifacts\bin\ref\net5.0\System.Security.Principal.Windows.dll, not C:\git\runtime\artifacts\bin\System.Security.Principal.Windows\net5.0-Unix-Debug\System.Security.Principal.Windows.dll. In that case RAR should see an assembly and be able to set FusionName metadata correctly.

Am I missing a binlog here? What I see from the output above is:

```
8>                                ReferenceAssembly=C:\git\runtime\artifacts\bin\ref\net5.0\System.Security.Principal.Windows.dll
```

which looks correct.

**Comment by ViktorHofer** [comment]
> @Anipik / @ViktorHofer why would this test even be referencing a net5.0-unix configuration. Even the unix build of the test should be using reference assemblies, not implementation.

A test project P2Ps both the implementation and the reference project as we mimic the RefOut behavior.

**Comment by ericstj** [comment]
Dan shared it offline but it was missing a lot of logging for me when I opened it.  I shared the theory of the source of the NRE above and Dan identified the assembly with short FusionName.  @Anipik shared a theory why this would be, which makes sense.  Typically FusionName metadata is set by RAR though, which is why I said it wouldn’t make sense for RAR to be analyzing the Unix impl — it should look at the ref which should exist and have a strong name.

I think next steps are to look at a full binlog to see what’s happening to produce the short FusionName metadata.  I wouldn’t leave this at resolution of adding the src project to the sln — that shouldn’t be necessary.

**Comment by ViktorHofer** [comment]
I took a lot and with https://github.com/dotnet/runtime/pull/44703 there are still issues. System.Runtime itself now builds fine but System.Runtime.Tests fails as it depends on S.S.AccessControl, S.T.AccessControl and transitively on S.W.Extensions. Those three libraries multi-target with identical target frameworks: `netstandard2.0` and `netstandard2.0-windows` or in the case of S.W.Extensions: `netcoreapp3.0` and `netcoreapp3.0-windows` and because of https://github.com/dotnet/runtime/issues/32205, restore fails inside VS.

This isn't just System.Runtime, but any solution that has a transitive dependency on a library that multi-targets by identical tfms, older than `net5.0`. Until https://github.com/NuGet/Home/issues/5154 is supported by NuGet, it's unclear to me what a mitigation could look like.

**Comment by GrabYourPitchforks** [comment]
After installing latest VS nightly (Version 16.9.0 Preview 2.0 \[30722.44.main\]), this is now starting to fail __from the command line__ as well as within VS.

```txt
C:\runtime\> .\build.cmd -s clr -c Checked ; .\build.cmd -s libs.pretest+libs+libs.tests -rc Checked -test
--- snip ---
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object. [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.GetVersion(ITaskItem referencePath) [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfo(ITaskItem referencePath) [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfos(IEnumerable`1 referencePaths) [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
C:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(195,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\runtime\src\libraries\System.Net.WebProxy\ref\System.Net.WebProxy.csproj]
```

**Comment by Tratcher** [comment]
I'm hitting this null ref again on main. I've followed the normal libraries build instructions from https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md
and then tried to load `build.cmd -vs System.Net.Quic` in VS 2019 16.11 Preview 2 and VS 2022 Preview 3.

I've rebooted, cleaned, and rebuilt the repo but am still hitting this. Any other workarounds?
