### ISSUE TITLE
Test failure: slowpatheltleave

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#40277]
failed in job: [runtime-coreclr jitstress 20200729.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=750921&view=ms.vss-test-web.build-test-results-tab&runId=23285924&resultId=100588&paneView=debug)

failed tests: 
profiler/elt/slowpatheltleave/slowpatheltleave.sh
profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd

Error message
```
Assert failure(PID 169 [0x000000a9], Thread: 169 [0x00a9]): hfaFieldSize == 8
    File: /__w/1/s/src/coreclr/src/vm/arm64/profiler.cpp Line: 265
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9a23ba30)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9a23ba30)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9a230470)
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 138
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 92
   at SlowPathELTTests.SlowPathELTLeave.Main(String[] args) in /Users/runner/work/1/s/src/tests/profiler/elt/slowpatheltleave.cs:line 29
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f78bbe470)
/root/helix/work/workitem/profiler/elt/slowpatheltleave/slowpatheltleave.sh: line 347:   153 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/profiler/elt/Reports/profiler.elt/slowpatheltleave/slowpatheltleave.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun slowpatheltleave.dll ''
Profiler path: /root/helix/work/workitem/profiler/elt/slowpatheltleave/libProfiler.so
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Testing leave hooks
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.169.dmp
Process 169 corerun
Written 63209472 bytes (15432 pages) to core file
Dump successfully written

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.153.dmp
Process 153 corerun
Written 115212288 bytes (28128 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/profiler/elt/slowpatheltleave/slowpatheltleave.sh
Expected: True
Actual:   False


Stack trace
   at profiler_elt._slowpatheltleave_slowpatheltleave_._slowpatheltleave_slowpatheltleave_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/profiler.elt/profiler.elt.XUnitWrapper.cs:line 237
```

Lots of failures for arm64 in various jobs:

https://dev.azure.com/dnceng/public/_build/results?buildId=754335&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=754519&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=754564&view=ms.vss-test-web.build-test-results-tab

@davmason @AndyAyersMS

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
This is an assert in the profiler support code for arm64. On arm64, hfa size can also be 16.
```
(lldb) frame select 8
frame #8: 0x0000ffff9ab1c60c libcoreclr.so`ProfileArgIterator::GetReturnBufferAddr(this=<unavailable>) at profiler.cpp:265:21
(lldb) frame variable
(ProfileArgIterator *) this = <variable not available>

(PROFILE_PLATFORM_SPECIFIC_DATA *) pData = <variable not available>

(UINT) fpReturnSize = <variable not available>

(TypeHandle) thReturnValueType = {
   = {
    m_asTAddr = 281471244565816
    m_asPtr = 0x0000ffff218bfd38
    m_asMT = 0x0000ffff218bfd38
    m_asTypeDesc = 0x0000ffff218bfd38
    m_asParamTypeDesc = 0x0000ffff218bfd38
    m_asTypeVarTypeDesc = 0x0000ffff218bfd38
    m_asFnPtrTypeDesc = 0x0000ffff218bfd38
  }
}
(UINT) hfaFieldSize = 16
(UINT) totalSize = <variable not available>

(BYTE *) dest = 0x0000ffffe2d8e1f0 "`k^ܪ\xaa"
(UINT) floatRegIdx = 0
```

**Comment by AndyAyersMS** [comment]
Fix seems simple enough, will put up a PR.
