### ISSUE TITLE
ClientOptions_ServerOptions_NotMutatedDuringAuthentication - failed "TimeoutException : VirtualNetwork: Timeout reading the next frame."

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#404]
Test: `System.Net.Security.Tests.SslClientAuthenticationOptionsTest.ClientOptions_ServerOptions_NotMutatedDuringAuthentication`

> System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
```
   at System.Net.Test.Common.VirtualNetwork.ReadFrameCoreAsync(Boolean server, Boolean sync, CancellationToken cancellationToken) in /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetwork.cs:line 66
   at System.Net.Test.Common.VirtualNetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/Common/tests/System/Net/VirtualNetwork/VirtualNetworkStream.cs:line 92
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|141_0(ExceptionDispatchInfo e)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__66_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs:line 513
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Net.Security.Tests.SslClientAuthenticationOptionsTest.ClientOptions_ServerOptions_NotMutatedDuringAuthentication() in /_/src/System.Net.Security/tests/FunctionalTests/SslAuthenticationOptionsTest.cs:line 82
--- End of stack trace from previous location ---
```

Seen in https://dev.azure.com/dnceng/public/_build/results?buildId=443044&view=ms.vss-test-web.build-test-results-tab&runId=14122480&resultId=147670&paneView=debug

**Comment by wfurt** [comment]
Aside from jitstress, this only failed twice on PRs(#402 and #242) at the end of November and never in an official run. All recorded failures are on `windows.10.amd64.open` queue and I'm wondering if this is caused by some infrastructure issues and runaway test nodes.

**Comment by karelz** [comment]
No hit during 2020/12/1-4/1 period, closing.
