### ISSUE TITLE
Test failure: System.Net.NameResolution.Tests.TelemetryTest.EventSource_ResolveInvalidHostName_LogsStartFailureStop

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#40514]
failed in job: [runtime-libraries outerloop 20200806.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=759536&view=ms.vss-test-web.build-test-results-tab&runId=23588116&resultId=102064&paneView=debug)

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveInvalidHostName_LogsStartFailureStop>b__2_0>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 90
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.NameResolution.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ResolveInvalidHostName_LogsStartFailureStop>b__2_0()
~~~

**Comment by karelz** [comment]
@MihaZupan is it from recently added test? If not, is it common test failure?

**Comment by MihaZupan** [comment]
It was added 1 month ago in #38409. I made a small change in #40665 that should give us more info when the test does fail.

As far as I can tell it is on average failing once a week on master.

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstress 20200817.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=773746&view=ms.vss-test-web.build-test-results-tab&runId=24175342&resultId=131662&paneView=debug)

failed test: System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs:line 1174
   at System.Text.Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.Internal.cs:line 1264
   at System.Text.UTF8Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder) in /_/src/libraries/System.Private.CoreLib/src/System/Text/UTF8Encoding.cs:line 647
   at System.Text.Encoding.GetCharsWithFallback(Byte* pOriginalBytes, Int32 originalByteCount, Char* pOriginalChars, Int32 originalCharCount, Int32 bytesConsumedSoFar, Int32 charsWrittenSoFar) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.Internal.cs:line 1083
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount) in /_/src/libraries/System.Private.CoreLib/src/System/Text/UTF8Encoding.cs:line 553
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding) in /_/src/libraries/System.Private.CoreLib/src/System/String.cs:line 540
   at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs:line 936
   at System.String.CreateStringForSByteConstructor(Byte* pb, Int32 numBytes) in /_/src/libraries/System.Private.CoreLib/src/System/String.cs:line 233
   at System.String.Ctor(SByte* value) in /_/src/libraries/System.Private.CoreLib/src/System/String.cs:line 187
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs:line 37
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs:line 319
   at System.Net.NetworkInformation.UnixIPGlobalProperties.get_HostName() in /_/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/UnixIPGlobalProperties.cs:line 15
   at System.Net.Mail.Tests.SmtpClientTest.GetClientDomain() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 490
   at System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 294
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs:line 319
   at System.Net.Mail.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_1() in /_/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs:line 37
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallback(Action`1 handler, Action body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 101
   at System.Net.Mail.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0() in /_/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs:line 34

Child process:
  System.Net.Mail.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Mail.Tests.LoggingTest+<>c Void <EventSource_EventsRaisedAsExpected>b__1_0()
~~~

**Comment by MihaZupan** [comment]
That is a different test

**Comment by karelz** [comment]
No failure between 2/23-5/7 (incl. PRs). Closing.
