### ISSUE TITLE
Tests failing with DirectoryNotFoundException on Browser Wasm

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#40536]
```
[FAIL] System.IO.Tests.DirectoryInfo_Delete_bool.RecursiveDeleteWithTrailingSlash
System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/DirectoryInfo_Delete_bool_ed2kbfm3.l5m/RecursiveDeleteWithTrailingSlash_250_9fbdd5c1/'.
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.DirectoryInfo.Delete(Boolean recursive)
   at System.IO.Tests.DirectoryInfo_Delete_bool.Delete(String path, Boolean recursive)
   at System.IO.Tests.Directory_Delete_str_bool.RecursiveDeleteWithTrailingSlash()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

[FAIL] System.IO.Tests.Directory_Delete_str_bool.RecursiveDeleteWithTrailingSlash
System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/Directory_Delete_str_bool_40onlxhb.ah0/RecursiveDeleteWithTrailingSlash_250_3b71fcdb/'.
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at System.IO.Tests.Directory_Delete_str_bool.Delete(String path, Boolean recursive)
   at System.IO.Tests.Directory_Delete_str_bool.RecursiveDeleteWithTrailingSlash()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

[FAIL] System.IO.Tests.Directory_Move.TrailingDirectorySeparators
System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/Directory_Move_bmas3gpw.g5o/TrailingDirectorySeparators_179_7b1943d1/'.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at System.IO.Tests.Directory_Move.TrailingDirectorySeparators()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

[FAIL] System.IO.Tests.DirectoryInfo_MoveTo.TrailingDirectorySeparators
System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/DirectoryInfo_MoveTo_zuselqkm.vma/TrailingDirectorySeparators_179_8892bb55/'.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at System.IO.Tests.Directory_Move.TrailingDirectorySeparators()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

[FAIL] System.IO.Tests.DirectoryInfo_MoveTo.DirectoryPathUpdatesOnMove
System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/DirectoryInfo_MoveTo_mslmzhiz.nex/DirectoryPathUpdatesOnMove_30_2f3fa791/'.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at System.IO.Tests.DirectoryInfo_MoveTo.Move(DirectoryInfo sourceDir, String destDir)
   at System.IO.Tests.DirectoryInfo_MoveTo.DirectoryPathUpdatesOnMove()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
------
**Update**: Looking for support from Emscripten side https://github.com/emscripten-core/emscripten/issues/11897

**Comment by steveisok** [comment]
I think this might be an issue with emscripten.  @mdh1418 Can you create a simple example that creates a file and tries to move it w/ and w/o a slash on the end?  If it errors similarly, then I think we can close this issue.

**Comment by mdh1418** [comment]
Looks like it does error if there's a trailing slash. For `RecursiveDeleteWithTrailingSlash` and `TrailingDirectorySeparators`, by removing `Path.DirectorySeparatorChar`, the tests pass. However for `DirectoryPathUpdatesOnMove`, there's a note that `//NOTE: MoveTo adds a trailing separator character to the FullName of a DirectoryInfo`
