### ISSUE TITLE
System.IO.Filesystem.ErrorHandlingTests tests failing on Browser wasm

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#40531]
```
[FAIL] System.IO.Tests.ErrorHandlingTests.VariableLengthFileNames_AllCreatableFilesAreEnumerable
Assert.Equal() Failure
Expected: OrderedEnumerable<String, String> ["a", "aa", "aaa", "aaaa", "aaaaa", ...]
Actual:   OrderedEnumerable<String, String> ["a", "aa", "aaa", "aaaa", "aaaaa", ...]
at System.IO.Tests.ErrorHandlingTests.VariableLengthFileNames_AllCreatableFilesAreEnumerable()

[FAIL] System.IO.Tests.ErrorHandlingTests.VariableLengthDirectoryNames_AllCreatableDirectoriesAreEnumerable
Assert.Equal() Failure
Expected: OrderedEnumerable<String, String> ["a", "aa", "aaa", "aaaa", "aaaaa", ...]
Actual:   OrderedEnumerable<String, String> ["a", "aa", "aaa", "aaaa", "aaaaa", ...]
at System.IO.Tests.ErrorHandlingTests.VariableLengthDirectoryNames_AllCreatableDirectoriesAreEnumerable()
```

**Comment by carlossanlop** [comment]
@mdh1418 what's the milestone for this issue?

**Comment by mdh1418** [comment]
@carlossanlop this issue is due to emscripten not properly throwing an exception when filenames longer than 255 characters are truncated. Temporarily there is a modification to the test until the exception is thrown on Emscripten's side. I haven't gotten around to reproing in a c program for emscripten yet, but I will open an issue there and get to it later.
