### ISSUE TITLE
Regex.Replace fails with aggressive linking

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#40582]
```C#
var regex = new Regex(@"\w+");
regex.Replace("a b c 1 2 3", "b");
```

```
Unhandled exception. System.TypeLoadException: Type 'System.Text.RegularExpressions.GroupCollection' from assembly 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' tried to override method 'System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String,System.Text.RegularExpressions.Group>>.GetEnumerator' but does not implement or inherit that method.
   at System.Text.RegularExpressions.Match.Reset(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart)
   at System.Text.RegularExpressions.RegexRunner.InitializeForGo()
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback)
   at System.Text.RegularExpressions.RegexReplacement.Replace(Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\davifowl\source\repos\WebApplication60\ConsoleApp1\Program.cs:line 13
```

**Comment by stephentoub** [comment]
cc: @MichalStrehovsky, @marek-safar

**Comment by MichalStrehovsky** [comment]
Nice linker bug. Moving to https://github.com/mono/linker/issues/1421.
