### ISSUE TITLE
Outerloop ConnectTimeout_TimesOutSSLAuth_Throws intermitently fails

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#40798]
With the highest probability due to slow infra.
Occurrences:
|Finished|Method|Message|QueueName|Branch|Duration|
|--------|------|-------|---------|------|--------|
|2020-08-13T19:30:14.549Z|ConnectTimeout_TimesOutSSLAuth_Throws|Assert.InRange() Failure\r\nRange:  (500 - 60000)\r\nActual: 71658|ubuntu.1604.amd64.open|refs/pull/40788/merge|75.1964957|
|2020-08-11T20:32:53.517Z|ConnectTimeout_TimesOutSSLAuth_Throws|Assert.InRange() Failure\r\nRange:  (500 - 60000)\r\nActual: 62208|ubuntu.1604.amd64.open|refs/pull/40666/merge|66.2265728|
|2020-08-08T08:28:04.74Z|ConnectTimeout_TimesOutSSLAuth_Throws|Assert.InRange() Failure\r\nRange:  (500 - 60000)\r\nActual: 72752|osx.1014.amd64.open|refs/pull/40338/merge|75.8671052|

[Kusto](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA21OS0vDQBC++yuGXqqQQtqTlwitUkjxgSbgsWyzQ3ebZkZmZimCP95NlXrxNN/wPVtUe0NNR1O4+oIDR4I+kq8iEQq8s/S14aDAdHlq/590w7uzKt/aZ/4UUBDWkaIG9HBXgXeGFge8XpSLclbezsr5DTjy8IQW2ENVweSec1hnbZZxsu149SVZ0zwuk4VtG4RPOjm7fmaPrunaxeM0d7L4vGT3+VfrUbtx7YfwIedeiOK3tICl7NOAZFpAY67rW3EdjrSq22fwmjDhsxsyXImjLhTwkMRZZPoG1VHlvD0BAAA=)

**Comment by wfurt** [comment]
it happend to me on my local Windows system.
```
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws [1m 9s]                                                                                                
Error Message:
                                                                                                                                                                                                                        Assert.InRange() Failure
Range:  (500 - 60000)      
Actual: 65434                                                                                                                                                                                                                           
```

**Comment by wfurt** [comment]
|Finished |	QueueAlias|
|--|---|
2020-09-08  | alpine.312.amd64.open
2020-09-08	| windows.10.amd64.server19h1.open
2020-09-08  | windows.10.amd64.server19h1.open
2020-09-07 	| windows.10.amd64.server19h1.open
2020-09-05 	| fedora.30.amd64.open
2020-09-03 	| windows.nano.1809.amd64.open
2020-09-02 	| sles.12.amd64.open
2020-09-01 	| windows.10.amd64.serverrs5.open

seems to be failing cross the queues.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201126.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=901043&view=ms.vss-test-web.build-test-results-tab&runId=28783496&resultId=104443&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Assert.InRange() Failure
Range:  (500 - 60000)
Actual: 65514


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 88
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201224.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=931213&view=ms.vss-test-web.build-test-results-tab&runId=29498838&resultId=104200&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
Assert.InRange() Failure
Range:  (500 - 60000)
Actual: 61007


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 88
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
~~~

**Comment by VincentBu** [comment]
Failed in job [runtime-libraries-coreclr outerloop 20210111.2](https://dev.azure.com/dnceng/public/_build/results?buildId=944638&view=ms.vss-test-web.build-test-results-tab&runId=29808938&resultId=104186&paneView=debug)

Failed test : `System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws`

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

**Error message:**
```

Error message
Assert.InRange() Failure
Range:  (500 - 60000)
Actual: 62802


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 88
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in run : [runtime-libraries-coreclr outerloop 20210127.3](https://dev.azure.com/dnceng/public/_build/results?buildId=967786&view=ms.vss-test-web.build-test-results-tab&runId=30432726&resultId=104486&paneView=debug)

Failed test : `System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws`

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

**Error message:**
```
Assert.InRange() Failure
Range:  (500 - 60000)
Actual: 73032


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 89
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210323.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1052244&view=ms.vss-test-web.build-test-results-tab&runId=32498756&resultId=104313&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
 -System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws
```

**Error message:**
```
Assert.InRange() Failure
Range:  (500 - 60000)
Actual: 70987


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 89
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Failures: 2/23-4/23 (main/master branch only)

When | OS | Exception
-- | -- | --
2021-03-01T11:54:10.482Z | ubuntu.1604.amd64.open.rt | Assert.InRange() Failure\r\nRange:  (500 - 60000)\r\nActual: 61715
2021-03-08T12:27:27.677Z | windows.10.amd64.server20h1.open.rt | Assert.InRange() Failure\r\nRange:    (500 - 60000)\r\nActual: 74199
2021-03-13T12:10:32.416Z | windows.10.amd64.server20h1.open.rt | Assert.InRange() Failure\r\nRange:    (500 - 60000)\r\nActual: 63034
2021-03-20T11:53:53.804Z | windows.10.amd64.server20h1.open.rt | Assert.InRange() Failure\r\nRange:    (500 - 60000)\r\nActual: 63570
2021-03-23T12:06:43.362Z | windows.10.amd64.server20h1.open.rt | Assert.InRange() Failure\r\nRange:    (500 - 60000)\r\nActual: 70987
2021-03-27T11:53:37.879Z | windows.10.amd64.server20h1.open.rt | Assert.InRange() Failure\r\nRange:    (500 - 60000)\r\nActual: 84522
2021-03-28T12:06:11.029Z | ubuntu.1604.amd64.open.rt | Assert.InRange() Failure\r\nRange:    (500 - 60000)\r\nActual: 62182

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210530.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1163266&view=ms.vss-test-web.build-test-results-tab&runId=35077660&resultId=104413&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

- System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws

```
**Error message:**
```
Assert.InRange() Failure
Range:  (500 - 85000)
Actual: 86671


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 89
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
This doesn't fail anymore, all the failures are from 6.0 branch, so it's highly likely already fixed.
