### ISSUE TITLE
Windows authentication in HttpClient not working over https in .NET 5

### ISSUE THREAD

**Issue by igor-tk** [dotnet/runtime#40834]
# Windows authentication in HttpClient not working over https in .NET 5

Windows authentication (NTLM or Kerberos) in HttpClient doesn't work over https in .NET 5 although in .NET Core 3.1 it does.
Was first created [here](https://github.com/dotnet/core/issues/5042), but it looks like it was the wrong repository.

Software versions:
Windows 10 Pro x64
IIS Express 10
.NET - dotnet-sdk-5.0.100-preview.7.20366.6-win-x64

Simple table that describes what works and what doesn't:
```
Url                                 |  Has auth (NTLM/Kerberos)   | Https  |  Works?
----------------------------------------------------------------------------------------------
http://localhost:44388/api/values   |                          No |    No   |     Yes  
http://localhost:44388/api/values   |                         Yes |    No   |     Yes  
https://localhost:44388/api/values  |                          No |   Yes   |     Yes  
https://localhost:44388/api/values  |                         Yes |   Yes   |      No  
```

# Sample code and error

```
var httpClientHandler = new HttpClientHandler
            {
                Credentials = CredentialCache.DefaultNetworkCredentials
            };
var httpClient = new HttpClient(httpClientHandler, true);     
var url = "https://localhost:44388/api/values";
var res = httpClient.GetAsync(url).Result;
```

Error:
System.ComponentModel.Win32Exception "The token supplied to the function is invalid"} 

   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.<SendWithNtAuthAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__66.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.AuthenticationHelper.<SendWithAuthAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__76.MoveNext()

For server app I created simple "Hello world" application from Visual Studio 2019 - Web Application (.NET Framework 4.8) with Windows authentication and https.

If I use production web server (apache in my case), I get the same error.

**Comment by wfurt** [comment]
I think this is dup of  #39011 and #35678. Follow instructions in the second issues and verify the fix with daily build or wait for next preview. If you still see problem, reopen this with more details.
