### ISSUE TITLE
System.IO.Tests.File_Copy tests failing on Browser wasm

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#40867]
Triggered by https://github.com/dotnet/runtime/pull/40753.

First:
```
      [FAIL] System.IO.Tests.File_Copy_str_str_b.CopyFileWithData(data: [], readOnly: False)
      Assert.InRange() Failure
      Range:  (08/14/2020 23:38:44 - 08/14/2020 23:38:46)
      Actual: 08/14/2020 22:38:45
         at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
Second (this is a new test just added on https://github.com/dotnet/runtime/pull/40753):
```
      [FAIL] System.IO.Tests.File_Copy_Single.EnsureThrowWhenCopyToNonSharedFile
      Assert.Throws() Failure
      Expected: typeof(System.IO.IOException)
      Actual:   (No exception was thrown)
         at System.IO.Tests.File_Copy_Single.EnsureThrowWhenCopyToNonSharedFile()
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by mdh1418** [comment]
It looks like `EnsureThrowWhenCopyToNonSharedFile` does not throw an error because `flock` is not yet implemented on emscripten https://github.com/emscripten-core/emscripten/issues/11797.
