### ISSUE TITLE
wasm test failure: System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#40886]
Filed on mono/wasm (`net5.0-Browser-Release-wasm-Mono_Release-Ubuntu.1804.Amd64.Open`)  in #40841:
https://dev.azure.com/dnceng/public/_build/results?buildId=772623&view=ms.vss-test-web.build-test-results-tab&runId=24126412&paneView=debug

With `PlatformNotSupportedException: Cannot wait on monitors on this runtime.`

Currently I'm rerunning the tests, but since FileSystem and System.Private.Corelib doesn't have a dependency on System.Net.Primitives, I don't think it can be related to my PR.

**Comment by danmosemsft** [comment]
Assert.Throws() Failure\nExpected: typeof(System.IO.IOException)\nActual:   typeof(System.PlatformNotSupportedException): Cannot wait on monitors on this runtime.\n---- System.PlatformNotSupportedException : Cannot wait on monitors on this runtime.


```
Stack trace
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Tests.FileStream_SafeFileHandle.<>c__DisplayClass5_0.<ThrowWhenHandlePositionIsChanged>b__1()
----- Inner Stack Trace -----
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Tests.FileStream_SafeFileHandle.<>c__DisplayClass5_0.<ThrowWhenHandlePositionIsChanged>b__1()
```
