### ISSUE TITLE
Test failure Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#40881]
Libraries Test Run release coreclr Linux x64 Debug
https://dev.azure.com/dnceng/public/_build/results?buildId=771997&view=logs&j=71afe768-e493-597c-228c-037834193aeb&t=3e74a8b7-5e62-58f8-6a85-9e36ef39d1c1

Helix log: https://helix.dot.net/api/2019-06-17/jobs/0684a59a-ffc9-4199-9295-900298e7dfc2/workitems/System.Net.Requests.Tests/console

```
    System.Net.Tests.HttpWebRequestTest_Sync.Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Net.WebException)
      Actual:   typeof(System.ObjectDisposedException): Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.
      ---- System.ObjectDisposedException : Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.
      Stack Trace:
        /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1025,0): at System.Net.HttpWebRequest.GetResponse()
        /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs(522,0): at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass38_0.<Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException>b__1()
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs(1025,0): at System.Net.HttpWebRequest.GetResponse()
        /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs(522,0): at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass38_0.<Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException>b__1()
```

**Comment by Jozkee** [comment]
@ManickaP This test failed again but with a different assertion failure, should this be re-opened?

Libraries Test Run release coreclr Windows_NT x86 Debug
https://dev.azure.com/dnceng/public/_build/results?buildId=779814&view=logs&j=f9ca12c5-777d-584c-1073-5ce8aeff54d2&t=4ff4ac34-be1d-522f-226d-77967f1046de

Helix log: https://helix.dot.net/api/2019-06-17/jobs/f417e0db-63cc-4f31-a551-76381223e1e9/workitems/System.Net.Requests.Tests/console

```
      Assert.InRange() Failure
      Range:  (1 - 15000)
      Actual: 0
      Stack Trace:
        /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs(525,0): at System.Net.Tests.HttpWebRequestTest.<>c.<Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException>b__38_0(LoopbackServer server, Uri url)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(77,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass12_0.<CreateServerAsync>b__0(LoopbackServer server)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(71,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs(516,0): at System.Net.Tests.HttpWebRequestTest.Timeout_SetTenMillisecondsOnLoopback_ThrowsWebException()
```

**Comment by ManickaP** [comment]
@Jozkee no, this is something different, could you please file a new issue?
