### ISSUE TITLE
CI: System.ArgumentException : The supplied System.Net.Internals.SocketAddress is an invalid size for the System.Net.IPEndPoint end point.

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#40913]
Libraries Test Run release coreclr OSX x64 Debug failed
```
/private/tmp/helix/working/C0070A33/w/AA2A094E/e /private/tmp/helix/working/C0070A33/w/AA2A094E/e
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 816 of 1231 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 4)
    System.Net.Sockets.Tests.DualModeAccept.AcceptV4BoundToAnyV6_Success [FAIL]
      System.ArgumentException : The supplied System.Net.Internals.SocketAddress is an invalid size for the System.Net.IPEndPoint end point. (Parameter 'socketAddress')
      Stack Trace:
        /_/src/libraries/Common/src/System/Net/Internals/IPEndPointExtensions.cs(36,0): at System.Net.Sockets.IPEndPointExtensions.Create(EndPoint thisObj, SocketAddress socketAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1116,0): at System.Net.Sockets.Socket.Accept()
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(765,0): at System.Net.Sockets.Tests.DualModeAccept.Accept_Helper(IPAddress listenOn, IPAddress connectTo)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(755,0): at System.Net.Sockets.Tests.DualModeAccept.AcceptV4BoundToAnyV6_Success()
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
  Finished:    System.Net.Sockets.Tests
```
https://helix.dot.net/api/2019-06-17/jobs/cbdca4c0-455d-445a-b4be-f66a996ae91b/workitems/System.Net.Sockets.Tests/console

Seen in https://github.com/dotnet/runtime/pull/40877

https://dev.azure.com/dnceng/public/_build/results?buildId=773532&view=logs&jobId=4724cd84-0a26-56bc-9b1d-ca1983f340b0&j=4724cd84-0a26-56bc-9b1d-ca1983f340b0&t=522fb2d8-007e-5c8a-7842-66e99f004601

**Comment by karelz** [comment]
Triage: Single occurrence in last 3-6 months.
We should assess if it is a regression in 5.0 - we changed the code around it. The failure is suspicious.
If we don't have anything useful, ok to punt it to 6.0.

**Comment by wfurt** [comment]
The relevant code is:
```c#
          if (family == AddressFamily.InterNetwork || family == AddressFamily.InterNetworkV6)
            {
                if (socketAddress.Size < 8)
                {
                    throw new ArgumentException(SR.Format(SR.net_InvalidSocketAddressSize, socketAddress.GetType().FullName, thisObj.GetType().FullName), nameof(socketAddress));
                }

                return socketAddress.GetIPEndPoint();
            }
```

**Comment by karelz** [comment]
Triage: @MihaZupan can you please look at test history? Thanks!

**Comment by karelz** [comment]
No failure between 2/23-5/10 (incl. PRs). Closing.
