### ISSUE TITLE
Test failure: System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41010]
failed in job: [runtime-coreclr libraries-jitstress 20200817.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=773746&view=ms.vss-test-web.build-test-results-tab&runId=24175342&resultId=131662&paneView=debug)

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs:line 1174
   at System.Text.Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.Internal.cs:line 1264
   at System.Text.UTF8Encoding.GetCharsWithFallback(ReadOnlySpan`1 bytes, Int32 originalBytesLength, Span`1 chars, Int32 originalCharsLength, DecoderNLS decoder) in /_/src/libraries/System.Private.CoreLib/src/System/Text/UTF8Encoding.cs:line 647
   at System.Text.Encoding.GetCharsWithFallback(Byte* pOriginalBytes, Int32 originalByteCount, Char* pOriginalChars, Int32 originalCharCount, Int32 bytesConsumedSoFar, Int32 charsWrittenSoFar) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.Internal.cs:line 1083
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount) in /_/src/libraries/System.Private.CoreLib/src/System/Text/UTF8Encoding.cs:line 553
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding) in /_/src/libraries/System.Private.CoreLib/src/System/String.cs:line 540
   at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount) in /_/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs:line 936
   at System.String.CreateStringForSByteConstructor(Byte* pb, Int32 numBytes) in /_/src/libraries/System.Private.CoreLib/src/System/String.cs:line 233
   at System.String.Ctor(SByte* value) in /_/src/libraries/System.Private.CoreLib/src/System/String.cs:line 187
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs:line 37
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs:line 319
   at System.Net.NetworkInformation.UnixIPGlobalProperties.get_HostName() in /_/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/UnixIPGlobalProperties.cs:line 15
   at System.Net.Mail.Tests.SmtpClientTest.GetClientDomain() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 490
   at System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 294
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeHelpers.CoreCLR.cs:line 319
   at System.Net.Mail.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_1() in /_/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs:line 37
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallback(Action`1 handler, Action body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 101
   at System.Net.Mail.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0() in /_/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs:line 34

Child process:
  System.Net.Mail.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Mail.Tests.LoggingTest+<>c Void <EventSource_EventsRaisedAsExpected>b__1_0()
~~~

**Comment by karelz** [comment]
It is a bit weird that host name string marshalling fails ... @BruceForstall any idea why it would fail during JitStress?
@GrabYourPitchforks would you expect this exception for a valid string? Is it possible we got garbage from marshalling?

cc @antonfirsov @wfurt

**Comment by BruceForstall** [comment]
This was `net5.0-Linux-Release-arm-CoreCLR_checked-tailcallstress`. We've had problems with tailcallstress in the past... it's possible it's a bug in that stress mode. However, those problems should all have been fixed by https://github.com/dotnet/runtime/pull/40698, before this test ran.

I've often assumed that problems in System.Net tests that fail in JitStress modes are simply failing there because we run SO MANY JitStress variations, so a "random" failure is much more likely to occur in a JitStress mode than in a "normal" mode.

If you can reliably repro with:
```
COMPlus_TieredCompilation=0
COMPlus_TailcallStress=1
```

but not with only:
```
COMPlus_TieredCompilation=0
```

then it is likely a JIT bug.

**Comment by karelz** [comment]
No failure during 3/12-5/11 (incl. PRs). Closing.
