### ISSUE TITLE
The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.

### ISSUE THREAD

**Issue by ToMyAF** [dotnet/runtime#41024]
![image](https://user-images.githubusercontent.com/36257915/90585264-05500480-e207-11ea-8925-5f3549569409.png)
I don't do certificate validation, but it always prompts for this exception

**Comment by wfurt** [comment]
What version of .NET are you on and what OS @ToMyAF? 
Since you seems to be on curl path, also `curl --version`
You may need to do packet captures with Wireshark or tcpdump.

Note that SslProtocols.None is 0 so adding it via or does not do anything. 
It is also default for HttpClient so if you want to use it, do not set any specific versions.

**Comment by ToMyAF** [comment]
![image](https://user-images.githubusercontent.com/36257915/90839695-b501af80-e38a-11ea-83bc-2e1519123d47.png)
I changed my code.This is exception
---------------------------------------------------------------------
System.AggregateException: One or more errors occurred. (An error occurred while sending the request.)
---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.Net.Http.CurlException: SSL connect error
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference1 easyWrapper, CURLcode messageResult) --- End of inner exception stack trace --- at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at ERP.Facade.JhCCBQrPayCore.Interface.DefaultHttpCoreClient.DoPost[T](T netParam) at ERP.Facade.JhCCBQrPayCore.Interface.DefaultClient.Excute[T](CCBRequest1 req)
at ERP.Facade.JhCCBQrPayCore.Facade.CCBQrPay(Hashtable ht)InnnerException:System.AggregateException: One or more errors occurred. (An error occurred while sending the request.)
---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.Net.Http.CurlException: SSL connect error
at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference1 easyWrapper, CURLcode messageResult) --- End of inner exception stack trace --- at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

**Comment by ToMyAF** [comment]
centos   application run in docker.
-------------------------------------------------------------------------
NET Core 3.0
-------------------------------------------------------------------------
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
-------------------------------------------------------------------------

**Comment by wfurt** [comment]
3.0 is out of support. You should try either with 3.1 or possibly with 5.0 preview. 
I'm not sure if 3.1 will give any different results, but there are some fixes there. 
It is also curious as 3.x should not use curl unless you ask for it. Is there any reason for that?

Lastly, as I was thinking about it more, you can also try `curl -v <URL>'.
If that does not succeed, .NET will not either. That would help with triage. 

If neither step above gives hints, you will probably need to get packet capture or provide unable repro. 
(not the the capture can be done on host outside of the container as you normally don't have sufficient privilege)

**Comment by ToMyAF** [comment]
Thanks. the configuration of docker is the problem.

This is Solution：
`RUN sed -i "s|DEFAULT@SECLEVEL=2|DEFAULT@SECLEVEL=1|g" /etc/ssl/openssl.cnf`

![image](https://user-images.githubusercontent.com/36257915/90870962-ed29e200-e3cc-11ea-85cb-4d42e875d6ad.png)
