### ISSUE TITLE
[5.0.100-preview.7.20366.6] Single File Publish issue on MultiRPC app

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#41091]
Application Name: MultiRPC (.net 3.0 app)

OS: Windows 10 RS5

CPU: X64
.NET Build Number: 5.0.100-preview.7.20366.6

**App Location:** 
"\\appcompatsrv\appcompat\DotNetCore\AppSource\SingleFileDefault\MultiRPC.exe"

**App Source :**
\\appcompatsrv\appcompat\DotNetCore\20190902SearchApps\AppSource\MultiRPC

**Repro steps:**
Single File exe was created by
dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true 
using 5.0.100-preview.7.20366.6 SDK

1)Copy \\appcompatsrv\appcompat\DotNetCore\AppSource\SingleFileDefault\MultiRPC.exe" to local machine
2) Run the exe

**Expected Result:**
App Should launch

**Actual Result:**
App did not launch

**Findings :**
When we start the app exe, it is looking for Lang folder, inside the current directory where exe resides, however Lang folder is created in %TEMP% directory. It also creates Assets Folder, that is also in %TEMP% but it doesn't create Lang Folder. We don't know if it should get the necessary files from %TEMP% or it is supposed to create Assest and Lang folder in the current directory. 

**Exception:**
Application: MultiRPC.exe
CoreCLR Version: 4.700.20.6603
.NET Core Version: 3.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Appcompat\Documents\TestApps\Lang'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.EnumerateFiles(String path)
   at MultiRPC.App.GetLangFiles()
   at MultiRPC.App.App_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at MultiRPC.App.Main() 

cc @dotnet-actwx-bot

**Comment by swaroop-sridhar** [comment]
> When we start the app exe, it is looking for Lang folder, inside the current directory where exe resides, however Lang folder is created in %TEMP% directory. It also creates Assets Folder, that is also in %TEMP% but it doesn't create Lang Folder. We don't know if it should get the necessary files from %TEMP% or it is supposed to create Assest and Lang folder in the current directory.

Thanks @jiangzeng01 for the detailed notes. 

I think this failure is "by design" for `.net core 3.x` single files. 
Here, all files in the publish directory (including sub-directories) are embedded in the single-file bundle, and extracted out to the extraction directory (within %TEMP%) at run-time. If an app needs certain directories beside the `app.exe`, it should [exclude them from the bundle](https://github.com/dotnet/designs/blob/master/accepted/2020/single-file/design_3_0.md#build-system-interface) or access them from within the extraction directory (relative to `AppContext.BaseDirectory`). I recommend the former method: 
```xml
  <ItemGroup>
    <Content Include="Lang\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
```

In `.net 5`, this problem won't happen when using the default settings for single-file publish. Since content files are not bundled into the single-file app by default, the `Lang` directory will be published beside the `app.exe`, as expected by the app.
However, if the app is published targeting `.net5` using the `netcoreapp3.x` compatibility flag `IncludeAllContentInSingleFile`, then content is bundled into the app, and the project will need the above exclusion.

**Comment by swaroop-sridhar** [comment]
I think we can close this issue, since the failure is understood. If any action is recommended, please reopen it. Thanks.
