### ISSUE TITLE
[wasm-browser] Tests failing due to HTTP timeout

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#41160]
Some test suites time out during startup on Helix.

```
[14:10:40] dbug: test-browser[0]
      Arguments: --run,WasmTestRunner.dll,System.Collections.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
      
[14:13:05] crit: test-browser[0]
      System.AggregateException: One or more errors occurred. (The HTTP request to the remote WebDriver server for URL http://localhost:35065/session/67731f99d192ad05384a3fbce170472d/se/log timed out after 60 seconds.)
       ---> OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:35065/session/67731f99d192ad05384a3fbce170472d/se/log timed out after 60 seconds.
       ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
       ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
       ---> System.Net.Sockets.SocketException (125): Operation canceled
         --- End of inner exception stack trace ---
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
         at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
         --- End of inner exception stack trace ---
         at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
         at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
         at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
         at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
         at OpenQA.Selenium.Remote.RemoteLogs.GetLog(String logKind)
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.PumpLogMessages(IWebDriver driver) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 137
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunLogMessagesPump(IWebDriver driver, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 122
         --- End of inner exception stack trace ---
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunTestsWithWebDriver(IWebDriver driver) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 76
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 51
         at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 119
XHarness exit code: 1001
```

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Collections.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Linq.Expressions.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Linq.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Memory.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Private.Uri.Functional.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Runtime.Numerics.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Runtime.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Text.Encoding.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Text.Encodings.Web.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Text.Json.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.RW.CharCheckingReader.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.RW.NameTable.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.RW.XmlConvert.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.RW.XmlWriterApi.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.Xsl.XslCompiledTransformApi.Tests/console

https://helix.dot.net/api/2019-06-17/jobs/ca5a7a0a-81f9-4293-8570-e1481e234e7e/workitems/System.Xml.Xsl.XslTransformApi.Tests/console

**Comment by pavelsavara** [comment]
@directhex how can I tell if this is still existing issue ?

**Comment by radical** [comment]
This was fixed in https://github.com/dotnet/xharness/pull/309, and hasn't been seen since.
