### ISSUE TITLE
Directory.Delete fails with IOException on Linux with very deep tree

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#41195]
Using `6.0.100-alpha.1.20421.6` on Alpine WSL, a very deep folder tree cannot be deleted with `Directory.Delete(path, recurse:true)`. It fails with DirectoryNotFoundException:

```
danmose3:~/git/performance# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
danmose3:~/git/performance# tree -if /tmp/id5dkyzj.bgu/ | tail -3
/tmp/id5dkyzj.bgu/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a

999 directories, 0 files
danmose3:~/git/performance# cat ../../1/Program.cs
﻿using System;
using System.IO;

namespace _1
{
    class Program
    {
        static void Main(string[] args)
        {
            var path = @"/tmp/id5dkyzj.bgu/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a/a";
            Console.WriteLine($"Length is {path.Length}");
            Console.WriteLine(Directory.Exists(path));
            Directory.Delete("/tmp/id5dkx7j.bgu", true);
            Console.WriteLine(Directory.Exists(path));
        }
    }
}
danmose3:~/git/performance# tools/dotnet/x64/dotnet run --project  ../../1
Length is 2015
True
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/id5dkx7j.bgu'.
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at _1.Program.Main(String[] args) in /root/1/Program.cs:line 13
danmose3:~/git/performance#
```
If I increase the open files limit, it works:
```
danmose3:~/git/performance# ulimit -a
core file size (blocks)         (-c) 0
data seg size (kb)              (-d) unlimited
scheduling priority             (-e) 0
file size (blocks)              (-f) unlimited
pending signals                 (-i) 204978
max locked memory (kb)          (-l) 64
max memory size (kb)            (-m) unlimited
open files                      (-n) 1024
POSIX message queues (bytes)    (-q) 819200
real-time priority              (-r) 0
stack size (kb)                 (-s) 8192
cpu time (seconds)              (-t) unlimited
max user processes              (-u) 204978
virtual memory (kb)             (-v) unlimited
file locks                      (-x) unlimited
danmose3:~/git/performance# ulimit -n 4096
danmose3:~/git/performance# tools/dotnet/x64/dotnet run --project  ../../1
Length is 2015
True
False
```
Directory.Delete on Unix is implemented to enter the directory, if it finds a directory it recurses, else if it finds files it deletes them, else it deletes the directory it's in and returns. 

strace shows each of these directory `open(..)`'s as we go deeper into the tree. Finally it fails with `EMFILE (No file descriptors available)`. It ignores that, and then starts its `rmdir(..)` sequence, walking back up the tree. Because we failed to get to the bottom of the tree, each of these fails with `ENOTEMPTY` and when recursino completes it throws `System.IO.IOException: Directory not empty` because indeed it's not empty.
```
2173  madvise(0x7fd40ea2a000, 65536, MADV_DODUMP) = 0
2173  open("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = 1023
2173  fcntl(1023, F_SETFD, FD_CLOEXEC)  = 0
2173  getdents64(1023, /* 3 entries */, 2048) = 72
2173  lstat("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a/a", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2173  geteuid()                         = 0
2173  lstat("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a/a", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2173  geteuid()                         = 0
2173  open("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a/a", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 EMFILE (No file descriptors available)
2173  futex(0x7fd4a6691604, FUTEX_WAKE_PRIVATE, 1) = 1
2182  <... futex resumed>)              = 0
2182  futex(0x7fd4a6691604, FUTEX_WAIT_PRIVATE, 2, {tv_sec=0, tv_nsec=99999800} <unfinished ...>
2173  mprotect(0x7fd42e6ee000, 4096, PROT_READ|PROT_WRITE) = 0
2173  madvise(0x7fd42e6ee000, 4096, MADV_DODUMP) = 0
2173  mprotect(0x7fd42e6ee000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
2173  brk(0x5567ee37e000)               = 0x5567ee37e000
2173  brk(0x5567ee38c000)               = 0x5567ee38c000
2173  brk(0x5567ee39a000)               = 0x5567ee39a000
2173  brk(0x5567ee3a2000)               = 0x5567ee3a2000
2173  brk(0x5567ee3ac000)               = 0x5567ee3ac000
2173  brk(0x5567ee3cd000)               = 0x5567ee3cd000
2173  brk(0x5567ee3ee000)               = 0x5567ee3ee000
2173  madvise(0x5567ee3bd000, 196608, MADV_DONTNEED) = 0
2173  rmdir("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a/a") = -1 ENOTEMPTY (Directory not empty)
2173  lstat("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a/..", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2173  geteuid()                         = 0
2173  lstat("/tmp/id5dkyzj.bgu//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs..//..bunch of dirs../../bunch of dirs/../a/a/a/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
2173  geteuid()                         = 0
2173  getdents64(1023, /* 0 entries */, 2048) = 0
```
This repro occurs in the performance tests, which create 1000 directories deep:
https://github.com/dotnet/performance/blob/8f00082e5f1ab8b86a98bf3bfc9c307a171912a3/src/benchmarks/micro/libraries/System.IO.FileSystem/Perf.Directory.cs#L62
(which seems to be unintentional as the comment says it's aiming for a 1024 char path)

The failure here is on Alpine but note the ulimit was 1024, which is the same as my Ubuntu, so I"m not sure why it's working on the perf runs.

Can we avoid holding each directory open as we traverse into the tree?

**Comment by JeremyKuhne** [comment]
> any alternative approach occur to you?

Tracking without introducing other issues might be difficult. Perhaps it might be possible to see when we hit this case and fall back to an algorithm that closes and reopens the directory before and after recursing?

The scenario is pretty contrived so I'm a little concerned about trying too hard here. I think you'd realistically expect extreme upper bounds of a few hundred nested directories. I'd prefer to leave it alone and increase the ulimit for the perf test runs if possible or cut the recursion depth down a bit to allow for other active handles.

**Comment by danmosemsft** [comment]
> The scenario is pretty contrived so I'm a little concerned about trying too hard here. I think you'd realistically expect extreme upper bounds of a few hundred nested directories. I'd prefer to leave it alone and increase the ulimit for the perf test runs if possible or cut the recursion depth down a bit to allow for other active handles.

Yes having through about it I think we should just remove the 1000 directory case from the perf tests and just see whether we get customer feedback in future. There's a workaround they can use, if they hit it. I'd rather not rethink this code meantime, given it's functional and stable otherwise.

**Comment by danmosemsft** [comment]
@carlossanlop you're the area owner, do you want to leave open, or close?

**Comment by GSPP** [comment]
Isn't it a bug that the `EMFILE (No file descriptors available)` error is being ignored?

**Comment by danmosemsft** [comment]
@GSPP you’re suggesting that the API should throw when it discovers it can only do a partial job?

**Comment by GSPP** [comment]
@danmosemsft It was my understanding that in this scenario an unrecoverable error occurred and the code continued like `ON ERROR RESUME NEXT`. That does not seem appropriate. But then, I'm not really qualified to make that determination.

**Comment by danmosemsft** [comment]
You're right I think. Thank you for pointing this out.

**Comment by iSazonov** [comment]
In #48148 I am trying to add backward counter to track a recursion depth but with forward counter we could have an explicit condition to switch to alternative algorithm (more slow with close and reopen directories).

**Comment by danmoseley** [comment]
Happened to return to this. I'm actually not sure there is a problem of ignoring the error, since as I mentioned, the exception is always thrown, it just unwinds the recursion first.

I could imagine someone extending the implementation to handle deeper trees (or simply be more frugal with fd's) but that would need a bit of thought, since there is a reason they are being held right now - things get complicated if trying to walk a tree that's changing.

@iSazonov do you have data that this impacts real scenarios?

**Comment by iSazonov** [comment]
> @iSazonov do you have data that this impacts real scenarios?

I don't remember that there was such issue in PowerShell repo. On the other hand, such restrictions are always depressing when they unexpectedly arise.

It might be worth comparing this behavior with bash and other popular frameworks like Java. If users have complaints, they will most likely compare with them.

**Comment by danmoseley** [comment]
As nobody has reported hitting this in a real workload I will close this. We can reopen if a news emerges.
