### ISSUE TITLE
SslStreamCertificateContext.Create fails if there's no private key

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#41246]
### Description

In .NET 5, Kestrel uses `SslStreamCertificateContext.Create` at startup to resolve intermediate certificates at startup instead of during the connection establishment but it seems like there's some incompatibility in some certificates. In particular, certs without a private key now fail immediately https://github.com/dotnet/runtime/blob/da90d08d81aa730a26ffa31d2396654c1b86b03d/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.cs#L15-L18.

If a similar certificate is passed into the `SslServerAuthenticationOptions` using the `ServerCertificate` property it will run this logic to https://github.com/dotnet/runtime/blob/00d4741b496336b399f5e5920113e26143b55f38/src/libraries/System.Net.Security/src/System/Net/Security/SslAuthenticationOptions.cs#L59-L80

We should restore this logic as part of `SslStreamCertificateContext.Create`. 

### Configuration

An internal customer hit this when upgrading to 5.0. 

### Regression?

While it's not a regression in the BCL API (it's a new API), it's a regression because this API is being used in Kestrel as a replacement for the older behavior.

cc @bartonjs @wfurt @karelz

**Comment by karelz** [comment]
Addressed upstack in PR https://github.com/dotnet/aspnetcore/pull/25344 ... unless we hear more customers hitting it, we do not plan to add the API in BCL.

**Comment by ivanpaulovich** [comment]
Hey @karelz,

I got into this issue when upgrading an application from 3.1 to .NET 5. One detail is that the exception only happens when running on UNIX.

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at WebApplication1.Controllers.WeatherForecastController.Get(SkatteetatenService skatteetatenService) in C:\Users\pauloiv\Downloads\CertificateAuthentication\CertificateAuthentication\WebApplication1\Controllers\WeatherForecastController.cs:line 61
   at lambda_method5(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by wfurt** [comment]
is it possible to post repro @ivanpaulovich ? (or at least certificate chain you use) It should not fail with ' Index was out of range.' 

The implementations are different because each stack has different needs. On Windows whole chain needs to be somewhere in cert store for Schannel to work.

**Comment by ivanpaulovich** [comment]
Hey @wfurt,

In Windows I can see the certification path:

![image](https://user-images.githubusercontent.com/7133698/99938643-8d92f800-2d68-11eb-9281-de06e250f030.png)

I am still investigating if I can recreate the certificate manually so I can share here.
