### ISSUE TITLE
RijndaelManaged decrypt sometimes fails on the same cipher

### ISSUE THREAD

**Issue by Zetanova** [dotnet/runtime#41353]
# Issue Title

My encrypt/decrypt with RijndaelManaged UnitTest In the CI/DI pipline failes sometimes.
with "Padding is invalid and cannot be removed." 

# General

I tried to increase the test-iteration of encrypt/decrypt to reproduce the error on my developement machine
and they runs where all successful.

But still sometimes in the gitlab CI/DI system "Padding is invalid and cannot be removed." Exception is throwing.
**Rerunning the unittest** a second time can be successful.
Coping the cipher text from the failed  unittest on the CI/DI run to the development machine (win10, dotnet 3.1.7)
to test for only decryption does not fail.

Using docker image sha256:9ab567a295025939668c4b7bdd7ebd345e13a50dbedd88ae44f33be364352ffa for mcr.microsoft.com/dotnet/core/sdk:3.1

## Unit Tests
```c#
        [Fact]
        public void crypt_big_data()
        {
            PNetEncrypt.AddSecret("test", "testpass123testpass123testpass123");

            var data = new byte[2630];

            for(int i = 0; i < 100; i++)
            {
                //PNetEncrypt.RandomBytes(data);


                var cipher = Array.Empty<byte>();

                try
                {
                    cipher = PNetEncrypt.Encrypt(data, "test");

                    var r = PNetEncrypt.Decrypt(cipher, "test");

                    Assert.True(data.SequenceEqual(r));
                } 
                catch(CryptographicException)
                {
                    //catch padding exception
                    _output.WriteLine("CryptographicException with data: {0}\ncipher: {1}", 
                        Convert.ToBase64String(data), Convert.ToBase64String(cipher));
                    throw;
                }
            }
            
        }

        [Fact]
        public void decrypt_failed_cipher()
        {
            PNetEncrypt.AddSecret("test", "testpass123testpass123testpass123");

            string cipherBase64 = "Y3X5AcQYb9jMUmXTzt49TUfSl9cB/RvaZBePFz1o9Dq858Ld55YpkaloBAbQetQij+pzyhglCHCeIiKjMPG20ludFkQ3bJBFq4dk068BWRWv9JI+anvGowGIP6oPiNMueqmczQ/r3aj/safj0uO0uMEqRSGht25ssLgTUv0mnoGSLsMtCOz4t66JDZaq2IK8TYZ92HX1WPjR/QeCIvA1i77qWey/ZTU1MxqcoUheyF3CSq8Wtq63lbLv8bjFHOQ9V3oOkEPcSSYFfsybQebEnPMZEooDyzrX8fcULLKTAg0ipoWSrzp2qFWvqYU2tw0j00Y4HfYnY76+O+UNI+z27ioTE+NhCpJE1PTGNDIX3uEMZc/dEd2gR+tx0UWbA7nyDTPZXv2YVYD7SDRfTIpIONcCx1AxX7k2kJoT83oSbLtk8TgEwuKH8x62TZd8vA+2xDHiZhTJYe5e263OHNtCne19EwTs37rdC+hlSy2KnqzBzye+4ndNbaaYn17hXuUs1MBHZJK0MEaF/1ODvKUe4B5oJm2EFTvxQk9yWVRcycb3DoltkAW88Ergp9LDWXbwm1uLS/q/fSXSue+eXGkL6uJPd/gvrzmKV/r/TfhEccVk/o//9yiFmNQcbI98Un0SdbI7za4I8XeljF8wysn5C5Hm8UDmx+wKY1HJ6PYsRLEKXzbcH4voAsdOGKK1XiG1ocP2Ku5RUQ2iBIVBgpqUYBNUjiY+9Ys6HvTaMw9e+VGVpuQXodlzn08MX5e1aC9tFDE1mtBlMvbpQO6Gb2dZPtv9+6w7c2389fiH3yX5FnUTkMneRx+46xSqy9YfZ5wautEF6LLsNqTQseBJucJvWZbFxiOfvyV7u8Ofp8Gx9ePl1b9M4qb20w+t9tL15lxq1AlIyV8kHbZ07c5WeTzHGZNAt32gcwIWvjLsIJ90mWVnQhSBE2PAFwZq09dN/h7aaXE0r30a7SCYhUTqu/Es5c2dJsLin9V1FPvmGOJffd+Va1pXbLoT4U2n/uUX9X3TMSRQF7K1S06BJShnES7F0eicq5c1VLQ0YkhQh5QxsUBpYERDJu6F2IHAKKy5LCUOO0XzkhrPQ8rYPsbE/Zu/VjTqOr+PQ3jIMz+d5vWLHzEmlYAANKYSkUJMhFaZdiBMM2sRYnoJY1bVNOK/zeRnGKy1ebo12LkJp1ZaZaOCEVv99ZTkTgiExZHoUPYmttF4pcTnWQoS56H956wOmAurlAlHX+Ay9f9Jgn8ceOL6g+WdvyhyY5hx9KtL0j3tkYzQbPO4PXPd2es1iunNGr3ERTA9czRpCCfplfhV8fTSh3hNpk2hfhdlNibKI2PBGvPT3c6CVDdssI538HfS4NoZbDmWmwiWapHkrU4vLnXRLwo4B74dTJvH4wgpUo1T1kLOEG5YuyNuvPuTH3XmRYo7UtTykZcZvQzNFQ9oQSgcqeynb2ZOC9bkn4NUnLMZ8iRJuefUoQtQcommtxJjG0FIB6l3XhdlJJqWgfsINp06Hergow4TkZ3EpsAq+xXxetmFl9WlkWYyNAblTvDsv9ufjnlrF5RKRtrsGmowKE+Zy1bFHFPhOzsg63/3mFgIi1WlzU06rPiBBsZRVQ6bGpPhpsVT7Puxq6gG8vfBjO2U3phSC5IPRZ2aN/m7tzDgqD8SnsYVk7iMGP1V2lkeVvlOfEm+M19wdHvpGhDfsKy1n3yivVfrLZeIGKgL59xFgyf4gONhLEbxBgzETAiI+rynIDI9UhOip1SOs4J+EUAh1NupiigTRX89AR4GDYtbFTbhl77WSQyzqR6JKTiKboOsuEbQJUnqMs+0zRLbfZm0UxuV3TYmsvbxHyZLclud9t31J3++yVdJncx1t095M9hirj8zVVEN3gDBCtnqZMwyYO2ufY8L4YpejX+xnpcjA9fsHGYPKFJDSf0mg1r1QeSz0cW/U5iR99zbVTNiLDDttcVQG/VsczIzTyPbBdoi5tD6uUIucgMmDDUmwX4tyQXE2DL2rcTXFsD4Nw1WftkQJHiklQ24q9+X2ynV6YJIZqMjC/1HKYmQ9athqN75xNW/2a9Mcf8BqpHRfdz6IJXJCFD5OREuSgY/N/WXuS16Pu2AbX7LEqu2Hfno58ksqyF4Mmp9N0IBHLT44iWYD/GApAwihubynV5AcZ6zoZk/YyS8/MVboRidkefxxN3WHl8Zfo4FUiFM6tc1o9UIlMB7LJBShbZoSn1Of55Typ3HEA0/BDyy70A7X3BB/ELtgLUsciae94QUG5Z1lgpi+qVWhyavxqVGiz7Pt5+cuH/yF265DSLdQlMwUhBE+HlBJqQj0g06xYB7HQk+FIq+7gYud8DoTPAy5FyrF96DWbSC1PxLhPjpeIR8cHFJdnQ9jVJTwRy70GzJYoYYLxd7ao7q2Ysffq21s4mq+ZiOiE4KO+wYWHjBnMjxw6ztLGKpN7uxVGx0aHKLX5kcTxr4PAk/yjR45IVuhCacRAfgnczrRC3vSB/vwG/Tn/XiyazcJaPJFmmBHnzYc5lpw5/djZ9DmzJvcSqbnm1yzIc7OBJH9E0dpHpHMlc8rQ6eQFBS4zL7+dXZmC0QaeXddUV837kkcYQJ9HhzAFbGqpRsepr3ayh7hZeB35n92N3MPjcAkQFTIjCHWC/YVhir4qUB3EddNx7tSqtiEWFyeEEAVazceKDnMSYiFqn/dwYOX96StarRWVN4AHPYLy2vJx/89ivxZHZlLbcM319XZmR5qkUF77+FBS0OqGO8IbAgtwq3ZeWluWG0sVDFxeSdazEhwHZJyX8Eeg+JJQtOu5B2TD4miz4VtlO8pr/r9mQcQi5S5nyfbZkwWqKi4ivvNBeu5azVCFTqCxx+Xjx63iv+HueqW+lzg3dBD2daYRwWzAqGZjl/KxAkCM9tiiCaV31qepCAFplMjSs7ql7GzABIn8hWg5NaTrab6Ce1oXzG/5oz8EJQCiQUNE7+WSQoNROjYHIbilq1SPYgChd6aYoNN/VkJfvZTCmOKdX5CH5jyA8xr0vHRlDZn0IjzN/n08Ur+1Ht6TskFnwOmjBV+eFverBPKiSCkDCX7uWf0kIEcaJOYqmlNfCovKH1GaKRwVMuJmaIY65qNtIG9DjYZMZ5kNLCpnGrqVSDzLVA31wlI6cXQeNsoO+VqKT7BkIDUU4FYRGXydeA6Fh5v8KJQGWIbhR5kvOF902dPCTkN0Cw/7LzvNEb9atqLiRglvGLfUJa+HWzzDNLo7DIhNr14HLSX+ZU/EW7XX2x28OCM1ytu/j3zSfTopdMoLMOHSAWjo7KGkLOATFSmev1cXwaEPStt5zMx7hv7iwfIbFJWZaqpzRbGELKlMxoUYWt1LywU7c6UlKJ4sPwaBqSHInyBUcMemHV52l+0NUl8fYLFDSVANgNHGHwaMDVLALN6WtJdZ97oTMmXMgfUQS73ywPX0OVHJaV/biCCG4LOSFYr9gwM+4JPbOAwYOVw7/Zh0E1N7+Tni5VeXNTCd3SMzEKgUp4fGEu0gbj9YtoOX/k2Yo=";

            var cipher = Convert.FromBase64String(cipherBase64);
            var expected = new byte[2630];

            var data = Decrypt(cipher, "testpass123testpass123testpass123");

            Assert.True(expected.SequenceEqual(data));

            //copy of PNetEncrypt.Decrypt
            static byte[] Decrypt(byte[] cipherBytes, string secret)
            {
                if (cipherBytes?.Length == 0)
                    return Array.Empty<byte>();

                var data = cipherBytes.AsSpan();

                if (data.Length <= 8)
                    throw new FormatException("cipher text invalid");

                var salt = data.Slice(0, 8).ToArray();
                var bytes = data.Slice(8).ToArray();

                var pdb = new Rfc2898DeriveBytes(secret, salt);

                var symmetricKey = new RijndaelManaged
                {
                    Mode = CipherMode.CBC,
                    Key = pdb.GetBytes(32),
                    IV = pdb.GetBytes(16),
                    Padding = PaddingMode.PKCS7
                };

                var decryptor = symmetricKey.CreateDecryptor();

                var dms = new MemoryStream(bytes.Length);
                MemoryStream memoryStream = new MemoryStream(bytes);
                using (var cryptoStream = new CryptoStream(memoryStream, decryptor, CryptoStreamMode.Read))
                    cryptoStream.CopyTo(dms);

                return dms.ToArray();
            }
        }
```

## Output
```
[xUnit.net 00:00:02.12]     PNet.UnitTests.PNetEncryptTests.crypt_big_data [FAIL]
  X PNet.UnitTests.PNetEncryptTests.crypt_big_data [146ms]
  Error Message:
   System.Security.Cryptography.CryptographicException : Padding is invalid and cannot be removed.
  Stack Trace:
     at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at PNet.Security.PNetEncrypt.Decrypt(Byte[] cipherBytes, String password, Byte[] salt) in /builds/Zetanova/PNet/src/PNet/Security/PNetEncrypt.cs:line 74
   at PNet.Security.PNetEncrypt.Decrypt(Byte[] cipherBytes, String ns) in /builds/Zetanova/PNet/src/PNet/Security/PNetEncrypt.cs:line 108
   at PNet.UnitTests.PNetEncryptTests.crypt_big_data() in /builds/Zetanova/PNet/src/PNet.UnitTests/PNetEncryptTests.cs:line 39
  Standard Output Messages:
 CryptographicException with data: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
 cipher: Y3X5AcQYb9jMUmXTzt49TUfSl9cB/RvaZBePFz1o9Dq858Ld55YpkaloBAbQetQij+pzyhglCHCeIiKjMPG20ludFkQ3bJBFq4dk068BWRWv9JI+anvGowGIP6oPiNMueqmczQ/r3aj/safj0uO0uMEqRSGht25ssLgTUv0mnoGSLsMtCOz4t66JDZaq2IK8TYZ92HX1WPjR/QeCIvA1i77qWey/ZTU1MxqcoUheyF3CSq8Wtq63lbLv8bjFHOQ9V3oOkEPcSSYFfsybQebEnPMZEooDyzrX8fcULLKTAg0ipoWSrzp2qFWvqYU2tw0j00Y4HfYnY76+O+UNI+z27ioTE+NhCpJE1PTGNDIX3uEMZc/dEd2gR+tx0UWbA7nyDTPZXv2YVYD7SDRfTIpIONcCx1AxX7k2kJoT83oSbLtk8TgEwuKH8x62TZd8vA+2xDHiZhTJYe5e263OHNtCne19EwTs37rdC+hlSy2KnqzBzye+4ndNbaaYn17hXuUs1MBHZJK0MEaF/1ODvKUe4B5oJm2EFTvxQk9yWVRcycb3DoltkAW88Ergp9LDWXbwm1uLS/q/fSXSue+eXGkL6uJPd/gvrzmKV/r/TfhEccVk/o//9yiFmNQcbI98Un0SdbI7za4I8XeljF8wysn5C5Hm8UDmx+wKY1HJ6PYsRLEKXzbcH4voAsdOGKK1XiG1ocP2Ku5RUQ2iBIVBgpqUYBNUjiY+9Ys6HvTaMw9e+VGVpuQXodlzn08MX5e1aC9tFDE1mtBlMvbpQO6Gb2dZPtv9+6w7c2389fiH3yX5FnUTkMneRx+46xSqy9YfZ5wautEF6LLsNqTQseBJucJvWZbFxiOfvyV7u8Ofp8Gx9ePl1b9M4qb20w+t9tL15lxq1AlIyV8kHbZ07c5WeTzHGZNAt32gcwIWvjLsIJ90mWVnQhSBE2PAFwZq09dN/h7aaXE0r30a7SCYhUTqu/Es5c2dJsLin9V1FPvmGOJffd+Va1pXbLoT4U2n/uUX9X3TMSRQF7K1S06BJShnES7F0eicq5c1VLQ0YkhQh5QxsUBpYERDJu6F2IHAKKy5LCUOO0XzkhrPQ8rYPsbE/Zu/VjTqOr+PQ3jIMz+d5vWLHzEmlYAANKYSkUJMhFaZdiBMM2sRYnoJY1bVNOK/zeRnGKy1ebo12LkJp1ZaZaOCEVv99ZTkTgiExZHoUPYmttF4pcTnWQoS56H956wOmAurlAlHX+Ay9f9Jgn8ceOL6g+WdvyhyY5hx9KtL0j3tkYzQbPO4PXPd2es1iunNGr3ERTA9czRpCCfplfhV8fTSh3hNpk2hfhdlNibKI2PBGvPT3c6CVDdssI538HfS4NoZbDmWmwiWapHkrU4vLnXRLwo4B74dTJvH4wgpUo1T1kLOEG5YuyNuvPuTH3XmRYo7UtTykZcZvQzNFQ9oQSgcqeynb2ZOC9bkn4NUnLMZ8iRJuefUoQtQcommtxJjG0FIB6l3XhdlJJqWgfsINp06Hergow4TkZ3EpsAq+xXxetmFl9WlkWYyNAblTvDsv9ufjnlrF5RKRtrsGmowKE+Zy1bFHFPhOzsg63/3mFgIi1WlzU06rPiBBsZRVQ6bGpPhpsVT7Puxq6gG8vfBjO2U3phSC5IPRZ2aN/m7tzDgqD8SnsYVk7iMGP1V2lkeVvlOfEm+M19wdHvpGhDfsKy1n3yivVfrLZeIGKgL59xFgyf4gONhLEbxBgzETAiI+rynIDI9UhOip1SOs4J+EUAh1NupiigTRX89AR4GDYtbFTbhl77WSQyzqR6JKTiKboOsuEbQJUnqMs+0zRLbfZm0UxuV3TYmsvbxHyZLclud9t31J3++yVdJncx1t095M9hirj8zVVEN3gDBCtnqZMwyYO2ufY8L4YpejX+xnpcjA9fsHGYPKFJDSf0mg1r1QeSz0cW/U5iR99zbVTNiLDDttcVQG/VsczIzTyPbBdoi5tD6uUIucgMmDDUmwX4tyQXE2DL2rcTXFsD4Nw1WftkQJHiklQ24q9+X2ynV6YJIZqMjC/1HKYmQ9athqN75xNW/2a9Mcf8BqpHRfdz6IJXJCFD5OREuSgY/N/WXuS16Pu2AbX7LEqu2Hfno58ksqyF4Mmp9N0IBHLT44iWYD/GApAwihubynV5AcZ6zoZk/YyS8/MVboRidkefxxN3WHl8Zfo4FUiFM6tc1o9UIlMB7LJBShbZoSn1Of55Typ3HEA0/BDyy70A7X3BB/ELtgLUsciae94QUG5Z1lgpi+qVWhyavxqVGiz7Pt5+cuH/yF265DSLdQlMwUhBE+HlBJqQj0g06xYB7HQk+FIq+7gYud8DoTPAy5FyrF96DWbSC1PxLhPjpeIR8cHFJdnQ9jVJTwRy70GzJYoYYLxd7ao7q2Ysffq21s4mq+ZiOiE4KO+wYWHjBnMjxw6ztLGKpN7uxVGx0aHKLX5kcTxr4PAk/yjR45IVuhCacRAfgnczrRC3vSB/vwG/Tn/XiyazcJaPJFmmBHnzYc5lpw5/djZ9DmzJvcSqbnm1yzIc7OBJH9E0dpHpHMlc8rQ6eQFBS4zL7+dXZmC0QaeXddUV837kkcYQJ9HhzAFbGqpRsepr3ayh7hZeB35n92N3MPjcAkQFTIjCHWC/YVhir4qUB3EddNx7tSqtiEWFyeEEAVazceKDnMSYiFqn/dwYOX96StarRWVN4AHPYLy2vJx/89ivxZHZlLbcM319XZmR5qkUF77+FBS0OqGO8IbAgtwq3ZeWluWG0sVDFxeSdazEhwHZJyX8Eeg+JJQtOu5B2TD4miz4VtlO8pr/r9mQcQi5S5nyfbZkwWqKi4ivvNBeu5azVCFTqCxx+Xjx63iv+HueqW+lzg3dBD2daYRwWzAqGZjl/KxAkCM9tiiCaV31qepCAFplMjSs7ql7GzABIn8hWg5NaTrab6Ce1oXzG/5oz8EJQCiQUNE7+WSQoNROjYHIbilq1SPYgChd6aYoNN/VkJfvZTCmOKdX5CH5jyA8xr0vHRlDZn0IjzN/n08Ur+1Ht6TskFnwOmjBV+eFverBPKiSCkDCX7uWf0kIEcaJOYqmlNfCovKH1GaKRwVMuJmaIY65qNtIG9DjYZMZ5kNLCpnGrqVSDzLVA31wlI6cXQeNsoO+VqKT7BkIDUU4FYRGXydeA6Fh5v8KJQGWIbhR5kvOF902dPCTkN0Cw/7LzvNEb9atqLiRglvGLfUJa+HWzzDNLo7DIhNr14HLSX+ZU/EW7XX2x28OCM1ytu/j3zSfTopdMoLMOHSAWjo7KGkLOATFSmev1cXwaEPStt5zMx7hv7iwfIbFJWZaqpzRbGELKlMxoUYWt1LywU7c6UlKJ4sPwaBqSHInyBUcMemHV52l+0NUl8fYLFDSVANgNHGHwaMDVLALN6WtJdZ97oTMmXMgfUQS73ywPX0OVHJaV/biCCG4LOSFYr9gwM+4JPbOAwYOVw7/Zh0E1N7+Tni5VeXNTCd3SMzEKgUp4fGEu0gbj9YtoOX/k2Yo=
```

**Comment by danmosemsft** [comment]
@Zetanova could you try .NET 5.0 latest preview to see whether it has different behavior?

**Comment by GrabYourPitchforks** [comment]
Does the actual implementation of your decrypt method differ from what's listed here? For example, in the above code, you're instantiating a new `RijndaelManaged` instance on every call to `Decrypt`. In the actual implementation is this `RijndaelManaged` instance a shared static singleton instead of a fresh instance on each call? Double-check your `Encrypt` method as well to ensure it's not reusing an instance between calls.

**Comment by Zetanova** [comment]
@GrabYourPitchforks `PNetEncrypt.Decrypt` is a static method without side effects and the one method in the unit test is only a copy of it.  The exception does only occur in gitlab-runner inside the dotnet/sdk container. 

I happens every 2-3 test run with a loop of 100. A retry in der CI/DI will most of the time be successful.

I will try to trigger in local with docker+WSL2

**Comment by Zetanova** [comment]
Same behavior with 
docker over WSL2 
image: mcr.microsoft.com/dotnet/core/sdk@sha256:4805a0ec2e1acae2be9554679acca0ec368aaf50cabdd028c0aa3cb8ff34a751
dotnet 3.1.401

Test run with:
```
dotnet test ${SOLUTION_NAME} --no-build -c Release --logger:"trx"
```

I will try to make make a test project for it later in few hours.

**Comment by Zetanova** [comment]
I made new a test project and/but it is working fine.
https://github.com/Zetanova/RijndaelManagedBugTest

After i made the same Dockerfile with my origin project 
with the single project and UnitTest project and run all tests
The error appeared again.

Then i run only the single `crypt_big_data` test multiple times 
and all were successful.

My suspicion is that xunit is executing unit tests in parallel
and something is using the ArrayPool Buffer after  it was returned back.

**Comment by vcsjones** [comment]
Thanks for the GitHub repo. I tried running it several times and everything passed.

![image](https://user-images.githubusercontent.com/361677/91356031-ffd15c00-e7bc-11ea-9b78-7b8e145db8e5.png)

Is it possible that you have an old docker image of 3.1 pulled? Just to double check, can you change your `FROM` in your docker image to `FROM mcr.microsoft.com/dotnet/core/sdk:3.1.401` (Or make sure the latest 3.1 is pulled otherwise).

Just as another data point, can you try with `FROM mcr.microsoft.com/dotnet/core/sdk:5.0` to see if the failure is 3.1 specific for you, or if it is still reproducing in the latest code?

**Comment by GrabYourPitchforks** [comment]
> My suspicion is that xunit is executing unit tests in parallel and something is using the ArrayPool Buffer after it was returned back.

I'd recommend removing your use of `ArrayPool` and rerunning the tests. We try to avoid use of the shared array pool within our own crypto libraries, opting either to use fresh arrays every time or to use an internal non-shared array pool marked exclusively for crypto use.

**Comment by Zetanova** [comment]
I made a commit to my demo project
but still i cant reproduce the behavior.

It is basically a copy of the code and project properties. 
But still the source projects already fails with only the 4 units test running.
But my demo-project never fails. 

... very strange.

**Comment by Zetanova** [comment]
**No issue with RijndaelManaged**

I found the mistake, it was me.

xUnit executes the tests in parallel,
the Password-UnitTests generated random passwords 
and overwrote the static shared secret-dictionary
All used the key `test`

The error-message from RijndaelManaged with `Padding is invalid and cannot be removed.`
is just indicate that it's just the wrong key-material.
