### ISSUE TITLE
System.Net.Sockets.SocketException：Resource temporarily unavailable

### ISSUE THREAD

**Issue by ToMyAF** [dotnet/runtime#41387]
![image](https://user-images.githubusercontent.com/36257915/91291271-6196c380-e7c7-11ea-9247-205c9fc8557a.png)

This is err detail.
--------------------------------------------------------
Resource temporarily unavailableSystem.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)System.Net.Http.HttpRequestException: Resource temporarily unavailable
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ERP.Facade.PayCenter.Facade.PostAsyncJson(String url, String json)

**Comment by karelz** [comment]
@ToMyAF it looks like the connection cannot be established from some reason. Are you able to reproduce it?
Are you able to write a small HelloWorld app that reproduces the problem with your specific endpoint?
Are you able to reach the endpoint from a browser?

BTW: Reading code from pictures is difficult, cannot be copy-pasted and is not accessible -- please post code in [markdown](https://guides.github.com/features/mastering-markdown/) in future if you can. Thanks!

**Comment by wfurt** [comment]
What OS? I'm wondering if this can come from transient DNS lookup failure. EAGAIN should normally be handled by the Socket layer.
