### ISSUE TITLE
Linq.Queryable.FirstOrDefault doesn't work when using TrimMode=link

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#41392]
Repro: 
[consoleapp-99c9d68.zip](https://github.com/mono/linker/files/5126317/consoleapp-99c9d68.zip)

Run `make linked` to run with `TrimMode=link`, and `make notlinked` to run the same command, except without setting `TrimMode`.

```shell
$ make linked
** Executing linked app
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
❌ failed: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.EnumerableRewriter.FindEnumerableMethod(String name, ReadOnlyCollection`1 args, Type[] typeArgs)
   at System.Linq.EnumerableRewriter.VisitMethodCall(MethodCallExpression m)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.EnumerableRewriter.VisitMethodCall(MethodCallExpression m)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[TElement](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at App.Main() in /Users/rolf/test/dotnet/consoleapp/Program.cs:line 19

$ make notlinked
** Executing notlinked app
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
✅ succeeded: hello hello
```

```shell
$ dotnet --version
5.0.100-rc.1.20426.3
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73
```

CC @marek-safar

**Comment by eerhardt** [comment]
This was fixed in 5.0 by https://github.com/dotnet/runtime/pull/42603.
