### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#41402]
Failed in #39313 

https://dev.azure.com/dnceng/public/_build/results?buildId=788156&view=logs&j=a2c324d3-d1dd-5b5e-9bd2-d56324c8f9e8&t=7a9ad864-1ecc-5f5a-4be6-1a6eb30653af&s=b15d9194-8f26-5328-b47f-5968c76b37e7

Configuration:
`net5.0-OSX-Debug-x64-CoreCLR_release-OSX.1014.Amd64.Open`

And also failed in other places (46 times starting from 2020-08-01 [Link to query](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA21PTUvDUBC8+yuWXqqQQtqTlwi2tpCC4kfFY9m8XZttkvfKvg1a8Mf7UqVePO0sM7Mzu+Fozxz71iJcfME+iIdGPBXiPSu8BW1K4y5C8OelpP+k61CdVGmWlPiPmpVhJV5izQQ3BRAam3R8Octn+SS/nuTTK0BPcM9WB4KigNFr5AW2bYWu2c6RFqwm7+KSc7v8PLAzpsfQijsuVYPG0cn/88DgH69Q2nFKD0qpU3X8K0Ac3dD7oGGf7pyJ7Dc+g1vd9R17ixm8WCqwUXQ80DHiLoGnnnt+wC7BuaJ3dQZ3vaJJ8N+Z+rQNRwEAAA==))

Stacktrace:
<details>

```
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: "https://self-signed.badssl.com/", expectedErrors: RemoteCertificateChainErrors) [FAIL]
      System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
      ---- Assert.Equal() Failure
      Expected: RemoteCertificateChainErrors
      Actual:   RemoteCertificateNameMismatch | RemoteCertificateChainErrors
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(140,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1282,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1327,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(536,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(869,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(565,0): at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs(334,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors_Helper(String url, String useHttp2String, SslPolicyErrors expectedErrors)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs(357,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(String url, SslPolicyErrors expectedErrors)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs(330,0): at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.<>c__DisplayClass18_1.<UseCallback_BadCertificate_ExpectedPolicyErrors_Helper>b__0(HttpRequestMessage request, X509Certificate2 cert, X509Chain chain, SslPolicyErrors errors)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(98,0): at System.Net.Http.ConnectHelper.<>c__DisplayClass3_0.<EstablishSslConnectionAsync>b__0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(989,0): at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(612,0): at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(411,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(116,0): at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
```

</details>

**Comment by wfurt** [comment]
looks like dup of #41381

**Comment by CarnaViire** [comment]
@wfurt I was looking for an existing issue before but GitHub search didn't show me that one :( Closing this as duplicate then

**Comment by karelz** [comment]
Duplicate of #41381
