### ISSUE TITLE
.NET 5.0 (Preview 8) breaks sending message in Microsoft.Azure.ServiceBus (4.1.3)

### ISSUE THREAD

**Issue by frankbuckley** [dotnet/runtime#41475]
### Description

Sending a message using Microsoft Azure ServiceBus fails when running under .NET 5.0 (Preview 8) - at least on Windows 10.0.19041 and macOS.

An InvalidOperationException ("Operation is not valid due to the current state of the object.") is thrown from `[Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync](https://github.com/Azure/azure-sdk-for-net/blob/6655f73bdb422c1c3b9c36973c04de0660870186/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/MessageSender.cs#L538)`, but seems to originate in Microsoft.Azure.Amqp.dll

### Regression?

Yes - works fine running on .NET Core 3.1.

#### Repro

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
	    <OutputType>Exe</OutputType>
	    <TargetFramework>net5.0</TargetFramework>
	  </PropertyGroup>

	  <ItemGroup>
	    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="4.1.3" />
	  </ItemGroup>

	</Project>

    class Program
    {
        public static async Task Main(string[] args)
        {
            var queueClient = new QueueClient(
                "Endpoint=sb://********.servicebus.windows.net/;SharedAccessKeyName=testing-send;SharedAccessKey=********",
                "********");

            var message = new Message(Encoding.UTF8.GetBytes("Test message."));

            await queueClient.SendAsync(message);
        }
    }

#### Stack trace:

	at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__58.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
	at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__45.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	at ServiceBusTestNet5.Program.<Main>d__0.MoveNext() in C:\dev\frankbuckley\ServiceBusTestNet5\ServiceBusTestNet5\Program.cs:line 17

#### dotnet --info (Windows)

	.NET SDK (reflecting any global.json):
	 Version:   5.0.100-preview.8.20417.9
	 Commit:    fc62663a35

	Runtime Environment:
	 OS Name:     Windows
	 OS Version:  10.0.19041
	 OS Platform: Windows
	 RID:         win10-x64
	 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

	Host (useful for support):
	  Version: 5.0.0-preview.8.20407.11
	  Commit:  bf456654f9

	.NET SDKs installed:
	  3.1.401 [C:\Program Files\dotnet\sdk]
	  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

	.NET runtimes installed:
	  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
	  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
	  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
	  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
	  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

#### dotnet --info (Mac OS)

    .NET SDK (reflecting any global.json):
    Version:   5.0.100-preview.8.20417.9
    Commit:    fc62663a35

    Runtime Environment:
    OS Name:     Mac OS X
    OS Version:  10.15
    OS Platform: Darwin
    RID:         osx.10.15-x64
    Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.8.20417.9/

    Host (useful for support):
    Version: 5.0.0-preview.8.20407.11
    Commit:  bf456654f9

    .NET SDKs installed:
    3.0.101 [/usr/local/share/dotnet/sdk]
    3.1.101 [/usr/local/share/dotnet/sdk]
    3.1.102 [/usr/local/share/dotnet/sdk]
    3.1.200 [/usr/local/share/dotnet/sdk]
    3.1.201 [/usr/local/share/dotnet/sdk]
    3.1.202 [/usr/local/share/dotnet/sdk]
    3.1.300 [/usr/local/share/dotnet/sdk]
    3.1.301 [/usr/local/share/dotnet/sdk]
    3.1.302 [/usr/local/share/dotnet/sdk]
    3.1.401 [/usr/local/share/dotnet/sdk]
    5.0.100-preview.8.20417.9 [/usr/local/share/dotnet/sdk]

    .NET runtimes installed:
    Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by frankbuckley** [comment]
https://github.com/Azure/azure-amqp/issues/165
