### ISSUE TITLE
SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent outerloop fail

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#41531]
Multiple occurrences in #41022
https://dev.azure.com/dnceng/public/_build/results?buildId=792342&view=results

For this test input:
`System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })`

[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-41022-merge-ae16a59be3f343b98c/System.Net.Http.Functional.Tests/console.4784ed97.log?sv=2019-02-02&se=2020-09-17T18%3A07%3A03Z&sr=c&sp=rl&sig=u4BNTdAHJdi7ChJlhxiZLBv1XSTD7tM1itdJ%2BPMDJD0%3D)

Error:
```
System.TimeoutException : Task timed out after 00:01:00
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
```

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries outerloop 20200903.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=800064&view=ms.vss-test-web.build-test-results-tab&runId=25329212&resultId=104043&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })

net5.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1604.Amd64.Open


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 226
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20200909.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=806988&view=ms.vss-test-web.build-test-results-tab&runId=25591316&paneView=debug&resultId=104324)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })

net5.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26912000&resultId=103089&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })

net6.0-Linux-Release-x64-CoreCLR_release-Centos.7.Amd64.Open


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00

Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201104.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=875322&view=ms.vss-test-web.build-test-results-tab&runId=28002666&resultId=103775&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })

net6.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1604.Amd64.Open


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 226
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201126.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=901043&view=ms.vss-test-web.build-test-results-tab&runId=28783496&resultId=104272&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 226
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20201207.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=910472&view=ms.vss-test-web.build-test-results-tab&runId=29012290&resultId=104450&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Asynchrony_Test.ExecutionContext_HttpConnectionLifetimeDoesntKeepContextAlive

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 43
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Asynchrony_Test.<>c__DisplayClass2_0.<<ExecutionContext_HttpConnectionLifetimeDoesntKeepContextAlive>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 69
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 89
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Asynchrony_Test.ExecutionContext_HttpConnectionLifetimeDoesntKeepContextAlive() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 54
--- End of stack trace from previous location ---
~~~

**Comment by danmosemsft** [comment]
Failed on `net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64`

https://dev.azure.com/dnceng/public/_build/results?buildId=931328&view=ms.vss-test-web.build-test-results-tab&runId=29502370&paneView=debug

```
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
```

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20210106.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=939900&view=ms.vss-test-web.build-test-results-tab&runId=29701620&resultId=103414&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.PostAsync_Cancel_CancellationTokenPassedToContent(content: StreamContent { Headers = [] }, cancellationTokenSource: CancellationTokenSource { IsCancellationRequested = False, Token = System.Threading.CancellationToken })

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
System.TimeoutException : Task timed out after 00:01:00


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 226
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.PostAsync_Cancel_CancellationTokenPassedToContent(HttpContent content, CancellationTokenSource cancellationTokenSource) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs:line 547
--- End of stack trace from previous location ---
~~~

**Comment by aik-jahoda** [comment]
Disabling the test for now until it is investigated

**Comment by karelz** [comment]
Summary of known facts and history:
- We do not know frequency of failures
- The test was/is failing in 5.0 (see e.g. 5.0.x servicing PR #46745)
- First report: 2020/8/28
- Test disabled: 2021/1/8 in PR #46752
