### ISSUE TITLE
Timeout: OuterLoop SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#41606]
### Test Case
`System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False)`

### Failed on
`net5.0-Linux-Debug-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open`
https://dev.azure.com/dnceng/public/_build/results?buildId=794770&view=ms.vss-test-web.build-test-results-tab&runId=25143524&resultId=104050&paneView=debug

### With
`System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms`

### Stack trace
<details>

```
at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>g__MakeAndValidateRequest|7_0(HttpClient client, LoopbackServer server, Uri url, X509Certificate2 cert) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 140
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass7_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__1>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 174
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 71
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(Int32 numberOfRequests, Boolean reuseClient) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 151
--- End of stack trace from previous location ---
```
</details>

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20200909.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=806988&view=ms.vss-test-web.build-test-results-tab&runId=25591316&paneView=debug&resultId=104192)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False)

net5.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

Error message
~~~
System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>g__MakeAndValidateRequest|7_0(HttpClient client, LoopbackServer server, Uri url, X509Certificate2 cert) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 140
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass7_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__1>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 174
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 71
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(Int32 numberOfRequests, Boolean reuseClient) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 151
--- End of stack trace from previous location ---
~~~

**Comment by ManickaP** [comment]
Triage: probably a test issue, duration of this test has been all over the place (from ms to 100s).

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26912000&resultId=103089&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False)

net6.0-Linux-Release-x64-CoreCLR_release-Centos.7.Amd64.Open

Error message
~~~
System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms

Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>g__MakeAndValidateRequest|7_0(HttpClient client, LoopbackServer server, Uri url, X509Certificate2 cert) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 140
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass7_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__1>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 174
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(Int32 numberOfRequests, Boolean reuseClient) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 151
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201224.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=931213&view=ms.vss-test-web.build-test-results-tab&runId=29498838&resultId=104355&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False)

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>g__MakeAndValidateRequest|7_0(HttpClient client, LoopbackServer server, Uri url, X509Certificate2 cert) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 140
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass7_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__1>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 174
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(Int32 numberOfRequests, Boolean reuseClient) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 151
--- End of stack trace from previous location ---
~~~

**Comment by VincentBu** [comment]
Failed again in run [runtime-libraries-coreclr outerloop 20210209.3](https://dev.azure.com/dnceng/public/_build/results?buildId=984912&view=ms.vss-test-web.build-test-results-tab&runId=30853778&resultId=103881&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1604.Amd64.Open
  -System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(numberOfRequests: 6, reuseClient: False)
```

**Error message:**
```
System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<Manual_CertificateSentMatchesCertificateReceived_Success>g__MakeAndValidateRequest|7_0(HttpClient client, LoopbackServer server, Uri url, X509Certificate2 cert) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 140
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.<>c__DisplayClass7_0.<<Manual_CertificateSentMatchesCertificateReceived_Success>b__1>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 174
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Net.Http.Functional.Tests.HttpClientHandler_ClientCertificates_Test.Manual_CertificateSentMatchesCertificateReceived_Success(Int32 numberOfRequests, Boolean reuseClient) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ClientCertificates.cs:line 151
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Failures: 2/23-4/23

When | OS | Exception
-- | -- | --
2021-03-02T12:23:15.559Z | ubuntu.1604.amd64.open.rt | System.TimeoutException :   WhenAllOrAnyFailed timed out after 60000ms
2021-03-06T12:24:16.241Z | windows.10.amd64.server20h1.open.rt | System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms
2021-03-28T12:06:11.029Z | ubuntu.1604.amd64.open.rt | System.TimeoutException : The operation has timed out.
2021-04-06T11:53:15.309Z | ubuntu.1604.amd64.open.rt | System.TimeoutException : The operation has timed out.

**Comment by karelz** [comment]
No failure in main/master branch in last 2 months: 2/23-4/23.

**Comment by karelz** [comment]
PR failures 3/12-5/11:
- 22 failures on PRs:
    - #48398
    - #49988
    - #50226
    - #50699 - 3x
    - #48758 - 5x
    - #50763
    - #50226
    - #50788
    - #50985
    - #51212 - 3x
    - #51205 - 2x
    - #52054
    - #52178

**Comment by ManickaP** [comment]
Doesn't fail anymore.
