### ISSUE TITLE
System.DirectoryServices.Protocols - FastConcurrentBind does not work on linux

### ISSUE THREAD

**Issue by null-d3v** [dotnet/runtime#41617]
### Description
`LdapSessionOptions.FastConcurrentBind()` does not work on linux.

Valid or invalid credentials will result in the following:
```
System.DirectoryServices.Protocols.LdapException: The LDAP server returned an unknown error.
    at System.DirectoryServices.Protocols.ErrorChecking.CheckAndSetLdapError(Int32 error)
    at System.DirectoryServices.Protocols.LdapSessionOptions.FastConcurrentBind()
```

Sample:
```
var connection = new LdapConnection(
    new LdapDirectoryIdentifier(
        LdapOptions.Server),
    credential,
    AuthType.Negotiate);

connection.SessionOptions.ProtocolVersion = 3;

userConnection.SessionOptions
    .FastConcurrentBind();
```

### Configuration
* .NET 5.0.0-preview.820414.8
* aspnet:5.0-alpine docker image
* x86_64
* libldap 2.4
* Windows Server 2019 DC

### Regression
The exact code is functional when executing from the docker container's Windows host.

**Comment by ericstj** [comment]
I believe this is known to not work:
https://github.com/dotnet/runtime/blob/c0b87c70e42c98b03c3148a3a84eb6898ae3eb1c/src/libraries/Common/src/Interop/Interop.Ldap.cs#L85

The option doesn't appear to be known by libldap.  I think the right place to file this request would be https://github.com/openldap/openldap/.

@joperezr do you agree?
