### ISSUE TITLE
OneCert_MismatchedKey test failing on release 5.0 branch

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#41727]
```
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.X509Certificates.Tests (found 575 of 624 test cases)
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 2)
    System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_Collection.OneCert_MismatchedKey [FAIL]
      Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000001)
      Stack Trace:
        /_/src/libraries/Common/src/Internal/Cryptography/CngCommon.SignVerify.cs(41,0): at Internal.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
        /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.SignVerify.cs(82,0): at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs(175,0): at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs(153,0): at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxFormatTests.cs(944,0): at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests.CheckKeyConsistencyFails(X509Certificate2 cert)
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxFormatTests_Collection.cs(66,0): at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_Collection.ReadPfx(Byte[] pfxBytes, String correctPassword, X509Certificate2 expectedCert, X509Certificate2[] expectedOrder, Action`1 otherWork, X509KeyStorageFlags flags)
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxFormatTests_Collection.cs(17,0): at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_Collection.ReadPfx(Byte[] pfxBytes, String correctPassword, X509Certificate2 expectedCert, Action`1 otherWork)
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/PfxFormatTests.cs(235,0): at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests.OneCert_MismatchedKey()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.X509Certificates.Tests  Total: 1048, Errors: 0, Failed: 1, Skipped: 0, Time: 22.003s
```

cc @ericstj @ViktorHofer @safern

**Comment by vcsjones** [comment]
I think this is another example of #29683.

**Comment by bartonjs** [comment]
Duplicate of #29683.
