### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_UnsuccessfulRequest_LogsStartFailedStop(testMethod: \"GetByteArrayAsync\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41723]
failed in job: [ runtime-libraries outerloop 20200901.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=796476&view=ms.vss-test-web.build-test-results-tab&runId=25203554&resultId=103453&paneView=debug)

net5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   0
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 452
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_UnsuccessfulRequest_LogsStartFailedStop>b__4_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 249
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_UnsuccessfulRequest_LogsStartFailedStop>b__4_0(System.String, System.String)

Child arguments:
  1.1, GetByteArrayAsync
~~~

**Comment by ManickaP** [comment]
cc @MihaZupan

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries outerloop 20200903.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=800064&view=ms.vss-test-web.build-test-results-tab&runId=25329596&paneView=debug&resultId=102811)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SuccessfulRequest_LogsStartStop(testMethod: \"Send\")

net5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   1
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 467
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulRequest_LogsStartStop>b__3_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 149
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulRequest_LogsStartStop>b__3_0(System.String, System.String)

Child arguments:
  1.1, Send
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20200910.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=809083&view=ms.vss-test-web.build-test-results-tab&runId=25705280&resultId=103207&paneView=debug)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue

net5.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   107.6774
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 486
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 590
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  2.0
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20200916.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=817342&view=ms.vss-test-web.build-test-results-tab&runId=26020616&paneView=debug&resultId=102066)

failed test: System.Net.NameResolution.Tests.TelemetryTest.EventSource_ResolveValidHostName_LogsStartStop

net5.0-Windows_NT-Release-x64-CoreCLR_release-Windows.81.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 6
Actual:   5
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveValidHostName_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 57
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.NameResolution.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ResolveValidHostName_LogsStartStop>b__1_0()
~~~

**Comment by ManickaP** [comment]
@MihaZupan will this get fixed with your current PR?

**Comment by ManickaP** [comment]
Triage: seems like test bug, might be fixed by ongoing telemetry fixes.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20200929.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=835093&view=ms.vss-test-web.build-test-results-tab&runId=26615296&resultId=104355&paneView=debug)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_UnsuccessfulRequest_LogsStartFailedStop(testMethod: \"GetStreamAsync\")

net5.0-Windows_NT-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0]
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 462
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_UnsuccessfulRequest_LogsStartFailedStop>b__4_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 249
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_UnsuccessfulRequest_LogsStartFailedStop>b__4_0(System.String, System.String)

Child arguments:
  1.1, GetStreamAsync
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201105.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=876448&view=ms.vss-test-web.build-test-results-tab&runId=28043338&resultId=104412&paneView=debug)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_SuccessfulRequest_LogsStartStop(testMethod: \"InvokerSendAsync\")

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   1
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 514
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulRequest_LogsStartStop>b__3_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 192
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulRequest_LogsStartStop>b__3_0(System.String, System.String)

Child arguments:
  2.0, InvokerSendAsync
~~~

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20201214.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=920179&view=ms.vss-test-web.build-test-results-tab&runId=29240438&resultId=103029&paneView=debug)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   154.1219
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 537
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  2.0
~~~
