### ISSUE TITLE
Test failure: BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41954]
failed in job: [runtime-coreclr libraries-jitstress 20200907.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=804291&view=ms.vss-test-web.build-test-results-tab&runId=25474098&resultId=155710&paneView=debug)

net5.0-Windows_NT-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at BasicEventSourceTests.TestsManifestGeneration.<Test_EventSource_EtwManifestGenerationRollover>b__6_0() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 97

Child process:
  System.Diagnostics.Tracing.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 BasicEventSourceTests.TestsManifestGeneration Void <Test_EventSource_EtwManifestGenerationRollover>b__6_0()
~~~

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by tommcdon** [comment]
@josalem  @sywhang

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstress 20200915.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=815445&view=ms.vss-test-web.build-test-results-tab&runId=25958882&resultId=155986&paneView=debug)

failed test: BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration

net5.0-Windows_NT-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at BasicEventSourceTests.TestsManifestGeneration.<Test_EventSource_EtwManifestGeneration>b__5_0() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 58

Child process:
  System.Diagnostics.Tracing.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 BasicEventSourceTests.TestsManifestGeneration Void <Test_EventSource_EtwManifestGeneration>b__5_0()
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr libraries-jitstress 20201029.1](https://dev.azure.com/dnceng/public/_build/results?buildId=869879&view=ms.vss-test-web.build-test-results-tab&runId=27835522&paneView=debug&resultId=114794)

failed test: BasicEventSourceTests.TestNotSupported.TestBasicOperations_IsSupported_False

net6.0-Windows_NT-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EmptyException: Assert.Empty() Failure
Collection: [EventSource(Microsoft-Windows-DotNETRuntime, 5e5bb766-bbfc-5662-0548-1d44fad9bb56), EventSource(System.Runtime, 49592c0f-5a05-516d-aa4b-a64e02026c89), EventSource(System.Diagnostics.Eventing.FrameworkEventSource, 8e9f5090-2d75-4d03-8a81-e5afbf85daf1), EventSource(Microsoft-Windows-DotNETRuntime, e13c0d23-ccbc-4e12-931b-d9cc2eee27e4), EventSource(EventSourceTest, 69e2aa3e-083b-5014-cad4-3e511a0b94cf)]
   at BasicEventSourceTests.TestNotSupported.<>c.<TestBasicOperations_IsSupported_False>b__0_0() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestNotSupported.cs:line 35

Child process:
  System.Diagnostics.Tracing.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 BasicEventSourceTests.TestNotSupported+<>c Void <TestBasicOperations_IsSupported_False>b__0_0()

~~~

**Comment by tarekgh** [comment]
Looks happening here too https://dev.azure.com/dnceng/public/_build/results?buildId=889393&view=logs&j=d5c01a48-52b8-51d9-fe3a-6804ba4b63f8&t=215202f9-e149-511e-645c-558c2532aa74&l=93

**Comment by VincentBu** [comment]
Failed again in job [runtime-coreclr libraries-jitstress 20210111.1](https://dev.azure.com/dnceng/public/_build/results?buildId=946066&view=ms.vss-test-web.build-test-results-tab&runId=29842406&resultId=161392&paneView=debug)

Failed test : `BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover`

net6.0-windows-Release-x86-CoreCLR_checked-jitminopts-Windows.10.Amd64.Open

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at BasicEventSourceTests.TestsManifestGeneration.<Test_EventSource_EtwManifestGenerationRollover>b__6_0() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 109

Child process:
  System.Diagnostics.Tracing.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 BasicEventSourceTests.TestsManifestGeneration Void <Test_EventSource_EtwManifestGenerationRollover>b__6_0()
```
