### ISSUE TITLE
Exception when interacting between ECDiffieHellman implementations

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#42081]
The following code seems seems reasonable, compiles, but produces an exception:

```c#
using ECDiffieHellman ecdh = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
using ECDiffieHellmanCng ecdhCng = new ECDiffieHellmanCng(ECCurve.NamedCurves.nistP256);
ecdhCng.DeriveKeyFromHash(ecdh.PublicKey, HashAlgorithmName.SHA256);
```

And using CNG package:

```xml
<PackageReference Include="System.Security.Cryptography.Cng" Version="5.0.0-preview.8.20407.11" />
```

```
Error Message:
System.InvalidCastException : Unable to cast object of type 'ECDiffieHellmanCng' to type 'System.Security.Cryptography.ECDiffieHellmanCng'.
Stack Trace:
    at System.Security.Cryptography.ECDiffieHellmanCng.DeriveSecretAgreementHandle(ECDiffieHellmanPublicKey otherPartyPublicKey) in D:\code\personal\runtime\src\libraries\System.Security.Cryptography.Cng\src\System\Security\Cryptography\ECDiffieHellmanCng.Derive.cs:line 114
at System.Security.Cryptography.ECDiffieHellmanCng.DeriveKeyFromHash(ECDiffieHellmanPublicKey otherPartyPublicKey, HashAlgorithmName hashAlgorithm, Byte[] secretPrepend, Byte[] secretAppend) in D:\code\personal\runtime\src\libraries\Common\src\System\Security\Cryptography\ECDiffieHellmanCng.cs:line 85
at System.Security.Cryptography.ECDiffieHellman.DeriveKeyFromHash(ECDiffieHellmanPublicKey otherPartyPublicKey, HashAlgorithmName hashAlgorithm) in D:\code\personal\runtime\src\libraries\System.Security.Cryptography.Algorithms\src\System\Security\Cryptography\ECDiffieHellman.cs:line 59
```

This appears to happen regardless of the package version or the runtime version, so I don't believe this is a regression from .NET Core.

This _does_ work in .NET Framework.

**Comment by vcsjones** [comment]
Found this while implementing #413.

**Comment by bartonjs** [comment]
Hm, the OpenSsl-specific implementation does an as-cast and if that fails does an export/import to build one it understands.  We probably don't have that in the Cng one because it was copied from the one in .NET Framework, which was (apparently) written assuming there was no other implementation.

> This does work in .NET Framework.

Probably because `ECDiffieHellman.Create` is `new ECDiffieHellmanCng()` on .NET Framework :smile:.

**Comment by vcsjones** [comment]
> does an as-cast and if that fails does an export/import to build one it understands.

CNG seems like it does that here, too:

https://github.com/dotnet/runtime/blob/f81701a1e1917c8f470e3a0e37de3809a941da86/src/libraries/System.Security.Cryptography.Cng/src/System/Security/Cryptography/ECDiffieHellmanCng.Derive.cs#L104

Where it throws is here, a few lines below:

https://github.com/dotnet/runtime/blob/f81701a1e1917c8f470e3a0e37de3809a941da86/src/libraries/System.Security.Cryptography.Cng/src/System/Security/Cryptography/ECDiffieHellmanCng.Derive.cs#L114

The exception indicates that is failing to convert a ECDiffieHellmanCng to ECDiffieHellmanCng which is... weird. This seems like a bad interaction between ECDiffieHellmanCng in System.Security.Cryptography.Cng and the other in System.Security.Cryptography.Algorithms. Probably. Maybe. I think.
