### ISSUE TITLE
Can_Run_App_With_StatiHost installer test failure in CI

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#42101]
In my PR, the test has failed with the following stack trace:
```
at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/tests/TestUtils/Command.cs:line 199
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute(Boolean fExpectedToFail) in /_/src/installer/tests/TestUtils/Command.cs:line 239
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute() in /_/src/installer/tests/TestUtils/Command.cs:line 171
   at AppHost.Bundle.Tests.StaticHost.Can_Run_App_With_StatiHost() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/StaticHost.cs:line 47
```

It looks similar to #35068

**Comment by janvorli** [comment]
Here is a link:
https://dev.azure.com/dnceng/public/_build/results?buildId=810089&view=ms.vss-test-web.build-test-results-tab&runId=25747512&resultId=100006&paneView=debug

**Comment by danmosemsft** [comment]
I have what may be the same issue, with an extra clue - @vitek-karas does this help?
```
System.ComponentModel.Win32Exception : Text file busy


Stack trace
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/tests/TestUtils/Command.cs:line 199
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute(Boolean fExpectedToFail) in /_/src/installer/tests/TestUtils/Command.cs:line 239
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute() in /_/src/installer/tests/TestUtils/Command.cs:line 171
   at AppHost.Bundle.Tests.StaticHost.Can_Run_App_With_StatiHost() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/StaticHost.cs:line 27
```

This is in 5.0 branch
https://dev.azure.com/dnceng/public/_build/results?buildId=852073&view=ms.vss-test-web.build-test-results-tab&runId=27196228&paneView=debug&resultId=100011

**Comment by danmosemsft** [comment]
@jaredpar if this is rare, but did break a CI job, is it appropriate to set 'blocking-clean-ci' or is that just for more common issues? Also, how to notify runfo about it so that it autolinks when it happens again?

**Comment by danmosemsft** [comment]
Also note this was Installer-coreclr-Linux_musl_x64-Release

**Comment by danmosemsft** [comment]
This message [apparently](https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix#:~:text=The%20Text%20file%20busy%20error%20in%20specific%20is,is%20the%20text%20segment%20for%20a%20running%20program.) means that we are trying to execute an executable while it is being modified - apparently in its text section.

**Comment by jaredpar** [comment]
This is failing about once a day right now so blocking clean CI is appropriate here.

**Comment by danmosemsft** [comment]
OK, that's a good rule of thumb..

**Comment by am11** [comment]
Happened again in #43804.

I think #44657, #https://github.com/dotnet/runtime/issues/43917 and https://github.com/dotnet/runtime/issues/42101 are stemming from same underlying problem.

**Comment by danmosemsft** [comment]
@agocke could someone maybe take a look?

**Comment by v-haren** [comment]
failed again in job: [runtime 20201217.40 ](https://dev.azure.com/dnceng/public/_build/results?buildId=925704&view=ms.vss-test-web.build-test-results-tab&runId=29363256&resultId=100014&paneView=debug)

failed test: Can_Run_App_With_StatiHost

Installer-coreclr-Linux_x64-Release


Error message
~~~
System.ComponentModel.Win32Exception : Text file busy


Stack trace
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/tests/TestUtils/Command.cs:line 199
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute(Boolean fExpectedToFail) in /_/src/installer/tests/TestUtils/Command.cs:line 239
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute() in /_/src/installer/tests/TestUtils/Command.cs:line 171
   at AppHost.Bundle.Tests.StaticHost.Can_Run_App_With_StatiHost() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/StaticHost.cs:line 27
~~~

**Comment by hoyosjs** [comment]
Removing blocking tag due to low incidence

cc: @agocke

**Comment by VincentBu** [comment]
Failed again in [runtime 20210601.76](https://dev.azure.com/dnceng/public/_build/results?buildId=1166244&view=ms.vss-test-web.build-test-results-tab&runId=35159130&resultId=100016&paneView=debug)

Failed test:
```
Installer-coreclr-Linux_musl_x64-Release

- Can_Run_App_With_StatiHost

```
**Error message:**
```
System.ComponentModel.Win32Exception : Text file busy


Stack trace
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Build.Framework.Command.Start() in /_/src/installer/tests/TestUtils/Command.cs:line 199
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute(Boolean fExpectedToFail) in /_/src/installer/tests/TestUtils/Command.cs:line 239
   at Microsoft.DotNet.Cli.Build.Framework.Command.Execute() in /_/src/installer/tests/TestUtils/Command.cs:line 171
   at AppHost.Bundle.Tests.StaticHost.Can_Run_App_With_StatiHost() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/StaticHost.cs:line 27
```

**Comment by danmoseley** [comment]
Happening every 3rd day for this test, but IIRC there were other tests with this issue.
