### ISSUE TITLE
System.Data.SqlClient 4.8.2 throws TransactionAbortedException (the connection has been broken)

### ISSUE THREAD

**Issue by MichaelLogutov** [dotnet/runtime#42132]
### Description

After updating System.Data.SqlClient version from old 4.6.1 to latest 4.8.2 we started to see period errors like this:
```
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.InvalidOperationException: The requested operation cannot be completed because the connection has been broken.

   --- End of inner exception stack trace ---
   at System.Transactions.TransactionStateAborted.EndCommit(InternalTransaction tx)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   ...
```

Those exceptions happening in pure ADO.NET code with TransactionScope created with ReadCommitted isolation level, TransactionScopeOption.Required, 1 minute timeout and TransactionScopeAsyncFlowOption.Enabled.

After rolling back to System.Data.SqlClient 4.8.1 those exceptions dissapeared but we saw another new type of exceptions we've never seen before from cassandra driver:

```
System.Net.Sockets.SocketException: Transport endpoint is not connected
   at Cassandra.Connections.HostConnectionPool.GetExistingConnections()
   at Cassandra.Connections.HostConnectionPool.BorrowExistingConnection()
   at async Cassandra.Connections.HostConnectionPool.GetConnectionFromHostAsync(?)
```

Downgrading back to 4.6.1 seems to fixed all issues.

### Configuration

It happened on aspnet core 3.1 web applications and console netcore 3.1 applications with latest 3.1 images both running in container on Linux.

### Regression?

It works on System.Data.SqlClient 4.6.1

### Other information

This issue happening on heavy load application and only on production. I can't reproduce this issue locally.
I wish I could find source for System.Data.SqlClient library to see the diff for 4.8.2 version.

**Comment by Wraith2** [comment]
The System version the library has been frozen and moved out of this repository in favour of Microsoft.Data.SqlClient https://github.com/dotnet/SqlClient which can be versioned separately. It contains fixes and improvements beyond those present in the framework provided versions. If possible give it a try and see if the behaviour you're seeing has already been resolved.

**Comment by MichaelLogutov** [comment]
Does it requires rewriting all namespaces Microsoft.*? Because we can't afford such rework in our libraries and all microservices.

**Comment by Wraith2** [comment]
It does. You should probably consider introducing abstractions in your codebase to avoid such things causing agility limitations.

**Comment by MichaelLogutov** [comment]
Well, it's not that simple when you have large code base and product 20 developers. 

Can I see the source code or at least changelog of what been changed in 4.8.2?

**Comment by devsko** [comment]
Maybe these help
[https://github.com/microsoft/dotnet/tree/master/releases](https://github.com/microsoft/dotnet/tree/master/releases)
[https://referencesource.microsoft.com/#System.Data](https://referencesource.microsoft.com/#System.Data)

**Comment by MichaelLogutov** [comment]
Thanks. I can see the source now but I can't seems to see the changes in 4.8.2
https://github.com/microsoft/dotnet/tree/master/releases do not seems to have release notes for individual nuget packages like System.Data.SqlClient. Or I'm missing something?

**Comment by Wraith2** [comment]
It's part of the framework so it doesn't get it's own update schedule. You probably want to review all the pull requests which targeted files in that project.

**Comment by MichaelLogutov** [comment]
I couldn't find the source code in github for System.Data.SqlClient. I saw only System.Data.Common

**Comment by devsko** [comment]
AFAIK **System**.Data.SqlClient is not open sourced but source open at [https://referencesource.microsoft.com/#System.Data](https://referencesource.microsoft.com/#System.Data) as mentioned above.

**Comment by Wraith2** [comment]
> AFAIK System.Data.SqlClient is not open sourced but source open at

It absolutely was and was part of this repository. It was removed in favour of the Microsoft version as I said earlier. To see the code you'll have to look into the history prior to it's removal.

**Comment by devsko** [comment]
@Wraith2 Just curious. It was the same code for core / desktop? Where lives the **System**.Data.SqlClient desktop code now?

**Comment by Wraith2** [comment]
The desktop version was distinct from the core version. This repo only contained the core version. 
The code is still here but not current which I why I say you'll need to look through the repo history to look at it. You can look back at any file that has ever existed by reviewing the git history but because it isn't currently being build and shipped it's not visible in the current master.

The code was forked into Microsoft.Data.SqlClient which also contains the desktop version. The Microsoft version supercedes the System version and is versioned independently so it can be updated without a framework update. It contains performance improvements new features and bug fixes that may not be ported back to core or desktop verisons.

**Comment by devsko** [comment]
Thanks.
I totally misunderstood this issue. After reading 4.6.1 and 4.8.2 I thought it is all about .NET Framework - but it isn't. Sorry for the confusion.

**Comment by cheenamalhotra** [comment]
Tagging @saurabh500 @corivera for System.Data.SqlClient (.Net Framework)

**Comment by cheenamalhotra** [comment]
@MichaelLogutov 

Could you please confirm if this issue occurs for SqlClient from .Net Framework or when referencing in a .Net Core Project? As it seems to me your application is ASP.NET Core but there are discussions for desktop version of SqlClient.. Just want to clarify to identify driver ownership.

**Comment by cheenamalhotra** [comment]
One seemingly related change that went in S.D.S. 4.8.2 (for .Net Core) is https://github.com/dotnet/corefx/pull/42937 which fixes a high security issue of data corruption.

Could you also elaborate more about Cassandra driver's role in your application and how 4.8.1 version causes failures?

Is it possible to run some tests without Cassandra driver in picture to really focus on SqlClient behaviour for the failing use case?

**Comment by MichaelLogutov** [comment]
> @MichaelLogutov
> 
> Could you please confirm if this issue occurs for SqlClient from .Net Framework or when referencing in a .Net Core Project? As it seems to me your application is ASP.NET Core but there are discussions for desktop version of SqlClient.. Just want to clarify to identify driver ownership.

The issue is on NETCore app running in Linux container.

**Comment by MichaelLogutov** [comment]
> For applications involving .Net Core, one seemingly related change that went in S.D.S. 4.8.2 (for .Net Core) is [dotnet/corefx#42937](https://github.com/dotnet/corefx/pull/42937) which fixes a high security issue of data corruption.
> 
> Could you also elaborate more about Cassandra driver's role in your application and how 4.8.1 version causes failures?
Well, Cassandra driver exception is from some background thread and seems does not impact application at all. Maybe it's just some kind of warning from the driver background processing. Since cassandra exception does not impacts my app I don't really have issue with that. It's just I thought it's strange - I only saw those kind exceptions after upgrading System.Data.SqlClient nuget package which also gets "he connection has been broken" exceptions when working with mssql. So I thought that this could somehow be related to some global app IO pooling issues caused by updated package.

> 
> Is it possible to run some tests without Cassandra driver in picture to really focus on SqlClient behaviour for the failing use case?

We can't remove Cassandra since it's also the part of our production microservice data storage unfortunately.

**Comment by cheenamalhotra** [comment]
Hi @MichaelLogutov 

From the stack trace it seems like your application is performing "Commit" on an "Aborted/Ended" transaction.
As the only change of behavior from the recent PR I linked above is to kill the physical connection to the database instead of sending it back to the pool when "Transaction Ended" event is captured by the driver. So I believe there's another thread/service that triggers Transaction Ended event whereas a different thread is trying to commit this transaction.

You can try to confirm this theory by checking `Transaction.TransactionInformation.Status" if it's "Active" before performing commit. Doing so should prevent the app from performing unwanted operations and hence the exceptions.

If there's a different use-case in your case, please provide details with a sample code if possible.

**Comment by MichaelLogutov** [comment]
Hi @cheenamalhotra 

I'll test out your suggestion.

Meanwhile I've looked into the PR and if I understood correctly you now throw a promoteException only if transaction status is aborted. So if transaction is not in aborted state and some exception occur there is a way to still get connection "doomed" and return from method without exception - is this intended?

**Comment by cheenamalhotra** [comment]
> Meanwhile I've looked into the PR and if I understood correctly you now throw a promoteException only if transaction status is aborted. 

The condition checks for
`if (promoteException != null && Transaction.TransactionInformation.Status != TransactionStatus.Aborted)`

([View Change](https://github.com/dotnet/corefx/pull/42937/files?diff=split&w=1#diff-f037ede26066530f183662d7bec3cf1cR217))
We throw exception only if transaction status is NOT aborted or is an active transaction.
