### ISSUE TITLE
DependencyInjection doesn't support value type services

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#42160]
### Description

We have this test, which is currently disabled and fails when enabled:

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Tests/ServiceProviderContainerTests.cs#L211-L225

We should enable this test and fix the product to make it pass.

**Comment by maryamariyan** [comment]
For future reference here is the stacktrace:

```
      Microsoft.Extensions.DependencyInjection.Tests.ServiceProviderExpressionsContainerTests.WorksWithStructServices [FAIL]
        System.ArgumentException : Expression of type 'Microsoft.Extensions.DependencyInjection.Fakes.StructFakeService' cannot be used for assignment to type 'System.Object'
        Stack Trace:
             at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(233,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.BuildScopedExpression(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(97,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.BuildExpression(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(88,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.BuildNoCache(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(61,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.<.ctor>b__17_0(ServiceCacheKey key, ServiceCallSite cs)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(79,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.<>c__DisplayClass18_0.<Build>b__0(ServiceCacheKey key)
             at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(79,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.Build(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(209,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.VisitScopeCache(ServiceCallSite callSite, Object context)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\CallSiteVisitor.cs(30,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(189,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.VisitConstructor(ConstructorCallSite callSite, Object context)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\CallSiteVisitor.cs(49,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(231,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.BuildScopedExpression(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(97,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.BuildExpression(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(88,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.BuildNoCache(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(61,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.<.ctor>b__17_0(ServiceCacheKey key, ServiceCallSite cs)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(79,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.<>c__DisplayClass18_0.<Build>b__0(ServiceCacheKey key)
             at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionResolverBuilder.cs(79,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.Build(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\Expressions\ExpressionsServiceProviderEngine.cs(19,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionsServiceProviderEngine.RealizeService(ServiceCallSite callSite)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\ServiceProviderEngine.cs(112,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
             at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\ServiceProviderEngine.cs(89,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\ServiceProviderEngine.cs(66,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceProvider.cs(58,0): at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection.Abstractions\src\ServiceProviderServiceExtensions.cs(28,0): at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\tests\DI.Tests\ServiceProviderContainerTests.cs(721,0): at Microsoft.Extensions.DependencyInjection.Tests.ServiceProviderContainerTests.WorksWithStructServices()
    Finished:    Microsoft.Extensions.DependencyInjection.Tests
```

and

```

  Assert failure(PID 52328 [0x0000cc68], Thread: 54228 [0xd3d4]): Assertion failed 'genActualType(lclTyp) == genActualType(op1->gtType) || (genActualType(lclTyp) == TYP_I_IMPL && op1->IsLocalAddrExpr() != nullptr) || (genActualType(lclTyp) == TYP_I_IMPL && (op1->gtType == TYP_BYREF || op1->gtType == TYP_REF)) || (genActualType(op1->gtType) == TYP_I_IMPL && lclTyp == TYP_BYREF) || (varTypeIsFloating(lclTyp) && varTypeIsFloating(op1->TypeGet())) || ((genActualType(lclTyp) == TYP_BYREF) && genActualType(op1->TypeGet()) == TYP_REF) : Possibly bad IL with CEE_stloc.3 at offset 0062h (op1=struct op2=NULL stkDepth=0)' in 'DynamicClass:ResolveService(ILEmitResolverBuilderRuntimeContext,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope):System.Object' during 'Importation' (IL size 127)

      File: C:\CodeHub\runtime\src\coreclr\jit\importer.cpp Line: 11857
      Image: C:\CodeHub\runtime\artifacts\bin\testhost\net6.0-windows-Debug-x64\dotnet.exe
...
      Microsoft.Extensions.DependencyInjection.Tests.ServiceProviderILEmitContainerTests.WorksWithStructServices [FAIL]
        System.InvalidProgramException : Common Language Runtime detected an invalid program.
        Stack Trace:
             at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\ServiceProviderEngine.cs(92,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceLookup\ServiceProviderEngine.cs(66,0): at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\src\ServiceProvider.cs(58,0): at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection.Abstractions\src\ServiceProviderServiceExtensions.cs(28,0): at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
          C:\CodeHub\runtime\src\libraries\Microsoft.Extensions.DependencyInjection\tests\DI.Tests\ServiceProviderContainerTests.cs(721,0): at Microsoft.Extensions.DependencyInjection.Tests.ServiceProviderContainerTests.WorksWithStructServices()
    Finished:    Microsoft.Extensions.DependencyInjection.Tests
  === TEST EXECUTION SUMMARY ===
     Microsoft.Extensions.DependencyInjection.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.323s
```

**Comment by allantargino** [comment]
Thanks @maryamariyan, the stack trace definitely helped :)
