### ISSUE TITLE
UnmanagedCallersOnlyTest failing in AllSubsets_Mono_RuntimeTests 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#42172]
Introduced by https://github.com/dotnet/runtime/pull/42146#issuecomment-691600937

```
Running TestUnmanagedCallersOnlyValid...
Test Failure: System.PlatformNotSupportedException: No native to managed transitions on this platform.
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at Program.TestUnmanagedCallersOnlyValid()
   at Program.Main(String[] args)
```

cc @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
I made a rushed decision here and introduced this issue. The 'fix' is to disable the tests for WASM as support doesn't exist to call back into managed from native code on WASM at present.

**Comment by v-haren** [comment]
failed again in job: [runtime 20200913.23 ](https://dev.azure.com/dnceng/public/_build/results?buildId=813420&view=ms.vss-test-web.build-test-results-tab&runId=25883982&resultId=100002&paneView=debug)

failed test: Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/UnmanagedCallersOnlyTest.sh

Mono Browser wasm Release @ Ubuntu.1804.Amd64.Open


Error message
~~~
Return code:      1
Raw output file:      /home/helixbot/work/ABC40918/w/B8260A3F/e/Interop/UnmanagedCallersOnly/Reports/Interop.UnmanagedCallersOnly/UnmanagedCallersOnlyTest/UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AppDir: /home/helixbot/work/ABC40918/w/B8260A3F/e/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/WasmApp/
  TestBinDir: /home/helixbot/work/ABC40918/w/B8260A3F/e/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest
  ArtifactsBinDir: 
Arguments: --run,UnmanagedCallersOnlyTest.dll,UnmanagedCallersOnlyTest
console.debug: MONO_WASM: Initializing mono runtime
console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
Initializing.....
Running TestUnmanagedCallersOnlyValid...
Test Failure: System.PlatformNotSupportedException: No native to managed transitions on this platform.
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at Program.TestUnmanagedCallersOnlyValid()
   at Program.Main(String[] args)

Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/ABC40918/p
> /home/helixbot/work/ABC40918/w/B8260A3F/e/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/UnmanagedCallersOnlyTest.sh
Expected: True
Actual:   False


Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_sh() in /__w/1/s/artifacts/tests/coreclr/Browser.wasm.Release/TestWrappers/Interop.UnmanagedCallersOnly/Interop.UnmanagedCallersOnly.XUnitWrapper.cs:line 140
~~~
