### ISSUE TITLE
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException using AES cfb mode

### ISSUE THREAD

**Issue by jianmingyong** [dotnet/runtime#42214]
### Description

My client that is running my program seems to have issues with the brand new AES CFB feature that is only available in the daily preview builds. It seems like it is unable to initialize or set the feedback size of AES CFB mode and caused the application to crash.

### Configuration

Tested on:
.NET Target Runtime: .NET 5.0
.NET Core SDK: 5.0.100-rc.2.20462.9 (Daily builds)

OS: Windows 7 (x86) - Crash
OS: Windows 10 (x64) - Okay
OS: Ubuntu 20.04 (x64) - Okay

### Other information

Tiny snippet of how the Aes method is consumed. Assume that all other variable exist in the class.
```
var aes = Aes.Create();
aes.Mode = CipherMode.CFB;
aes.BlockSize = 128;
aes.Padding = PaddingMode.None;
aes.KeySize = ClassConnectorSetting.MAJOR_UPDATE_1_SECURITY_CERTIFICATE_SIZE;
aes.Key = aesIvCertificate;

_aesEncryptor = aes.CreateEncryptor(aesIvCertificate, aesSaltCertificate);
_aesDecryptor = aes.CreateDecryptor(aesIvCertificate, aesSaltCertificate);
```

StackTrace:
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unknown error (0xc10000bb)
   at Internal.NativeCrypto.Cng.SetFeedbackSize(SafeAlgorithmHandle hAlg, Int32 dwFeedbackSize)
   at Internal.Cryptography.AesBCryptModes.<>c__DisplayClass5_0.<OpenAesAlgorithm>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Internal.Cryptography.AesBCryptModes.GetSharedHandle(CipherMode cipherMode, Int32 feedback)
   at Internal.Cryptography.AesImplementation.CreateTransformCore(CipherMode cipherMode, PaddingMode paddingMode, Byte[] key, Byte[] iv, Int32 blockSize, Int32 paddingSize, Int32 feedbackSize, Boolean encrypting)
   at Internal.Cryptography.AesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
   at Internal.Cryptography.AesImplementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
   at TheDialgaTeam.Xiropht.Xirorig.Network.XirorigToSeedNetwork..ctor(XirorigConfiguration xirorigConfiguration, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at TheDialgaTeam.Xiropht.Xirorig.Program.Main(String[] args)
```

**Comment by vcsjones** [comment]
My understanding of CFB on Windows is that it isn't supported in CNG until Windows 8. There was some discussion on that here: https://github.com/dotnet/runtime/pull/38211#issuecomment-672047161.

It probably makes sense to improve the exception for this though.

**Comment by vcsjones** [comment]
@bartonjs 

I did a little more digging on this; I think Windows 7 does support CFB. You just can't change the feedback size to anything other than 1.

`BCRYPT_CHAIN_MODE_CFB` appears in the Windows 7 SDK headers; however `BCRYPT_MESSAGE_BLOCK_LENGTH` to change the feedback size doesn't appear until Windows 8.

**Comment by bartonjs** [comment]
Interesting.  I merely noticed a lack of the BCRYPT_MESSAGE_BLOCK_LENGTH support and assumed they were the same thing.

I guess we could add an "if != 1" to the property set (and tests will tell us if it's a bad idea to depend on it being initialized to 1, or 8, depending on if that one was bytes or bits).  Dunno if it'd make the cut for 5.0 at this point (@danmosemsft / @jeffhandley improving Win7 partial support for a new feature in 5.0 based on RC feedback).

**Comment by vcsjones** [comment]
Okay, I'll open a PR regardless. It looks like CFB8 works for DES, AES, etc on Windows 7 when I re-enabled the tests.

**Comment by danmosemsft** [comment]
It would not make the 5.0 cut unless there was something like a major customer blocked from adoption by this - it sounds like we aren't aware of one.

We should be running tests on Win 7 -- was this just a case where we didn't have a test? Just wondering whether ther'es an issue with that CI leg.

**Comment by vcsjones** [comment]
> was this just a case where we didn't have a test?

The functionality and tests were written under the assumption that CFB did not work in Windows 7 at all. With some changes to the functionality, partial Windows 7 support is possible.

I don't believe there is an issue with the CI leg since I was [recently reminded it works][1].

[1]: https://github.com/dotnet/runtime/pull/42180#issuecomment-692057618

**Comment by vcsjones** [comment]
For AES and 3DES CFB8, Windows 7 support has been added but it will not arrive until .NET 6.

For other modes of CFB on Windows 7, such as AES CFB128, this is not supported because we are limited by what CNG on Windows can provide us. However the exception that is raised on Windows 7 has been changed to clarify this is an unsupported configuration, instead of a `CryptographicException` being thrown with an NTSTATUS.

Give that, I think this issue can be closed.
