### ISSUE TITLE
Array.Copy exception on Windows.10.Arm64 with ToList()

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#42342]
### Description

We saw an exception in one of our tests in ASP.NET Core that seems to be a runtime issue. A exception is being thrown in [this test](https://github.com/dotnet/aspnetcore/blob/cfe158cbed7483e8ab931e4cf47d578ba6c7170d/src/Middleware/Diagnostics.EntityFrameworkCore/test/FunctionalTests/DatabaseErrorPageMiddlewareTest.cs#L462) when calling ToList(), with the following callstack:

```
System.ArgumentException : Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')

Stack trace
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.Tests.DatabaseErrorPageMiddlewareTest.Pass_thru_when_exception_in_logic() in /_/src/Middleware/Diagnostics.EntityFrameworkCore/test/FunctionalTests/DatabaseErrorPageMiddlewareTest.cs:line 462
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=816781&view=ms.vss-test-web.build-test-results-tab&runId=25994920&paneView=debug&resultId=107437

**Comment by stephentoub** [comment]
Is it possible your `List<T>` is concurrently being added to while ToList is being called?  That could manifest in such a condition (and is improper use).

**Comment by jkotalik** [comment]
Yeah I think you are right. I'll close this and attempt to fix the test.
