### ISSUE TITLE
Crossgen2 fails with System.BadImageFormatException: Read out of bounds.

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#42429]
### Description

Compiling the following code with crossgen2 code fails. From the repro of this issue: https://github.com/dotnet/runtime/issues/7291

```csharp
using System;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace Bench
{
    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<Bench>();
        }
    }

    public class Bench
    {
        private const int iterations = 10000000;
        private List<int> A = new List<int>(iterations);
        private List<int> B = new List<int>(iterations);

        public Bench()
        {
            var rand = new Random();
            for (int i = 0; i < iterations; i++)
            {
                A.Add(rand.Next(10000));
                B.Add(rand.Next(10000));
            }
        }

        [Benchmark]
        public IList<int> RunInterface() => MultVectorsI(A, B);

        [Benchmark]
        public List<int> RunNoInterface() => MultVectors(A, B);

        public List<int> MultVectors(List<int> a, List<int> b)
        {
            int length = a.Count;
            var c = new List<int>(length);
            for (int i = 0; i < length; i++)
            {
                double valA = a[i];
                double valB = b[i];
                c.Add((int)Math.Sqrt(valA * valA + valB * valB));
            }

            return c;
        }

        public IList<int> MultVectorsI(IList<int> a, IList<int> b)
        {
            int length = a.Count;
            var c = new List<int>(length);
            for (int i = 0; i < length; i++)
            {
                double valA = a[i];
                double valB = b[i];
                c.Add((int)Math.Sqrt(valA * valA + valB * valB));
            }

            return c;
        }
    }
}
```

### Configuration

Compile using CLI:
```dotnet publish ConsoleApp1.csproj /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true --self-contained -r win-x64 -c Release```

### Regression?

No

**Comment by mangod9** [comment]
It fails with the following exception:

```
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error : Error: Read out of bounds. [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error : System.BadImageFormatException: Read out of bounds. [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at System.Reflection.Throw.OutOfBounds() [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at System.Reflection.Metadata.TypeDefinition.get_BaseType() [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType() [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at Internal.TypeSystem.Ecma.EcmaType.get_BaseType() [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at Internal.TypeSystem.TypeDesc.get_IsValueType() [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.IBC.IBCProfileParser.LoadTypeFromIBCZapSig(IBCModule ibcModule, EcmaModule ecmaModule, CorElementType typ, BlobReader& sig) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.IBC.IBCProfileParser.GetSigTypeFromIBCZapSig(IBCModule ibcModule, EcmaModule ecmaModule, BlobReader sig) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.IBC.IBCProfileParser.GetSigTypeFromIBCZapSig(IBCModule ibcModule, EcmaModule ecmaModule, BlobReader sig) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.IBC.IBCProfileParser.GetSigMethodInstantiationFromIBCMethodSpec(IBCModule ibcModule, BlobReader sig) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.IBC.IBCProfileParser.ParseIBCDataFromModule(EcmaModule ecmaModule) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.ProfileDataManager..ctor(Logger logger, IEnumerable`1 possibleReferenceModules, IEnumerable`1 inputModules, IEnumerable`1 versionBubbleModules, ModuleDesc nonLocalGenericsHome, IReadOnlyList`1 mibcFiles, CompilerTypeSystemContext context, ReadyToRunCompilationModuleGroupBase compilationGroup) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.Program.Run() [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
C:\Program Files\dotnet\sdk\5.0.100-rc.2.20461.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(394,5): error :    at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) [C:\Users\magodse\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
```

cc @dotnet/crossgen-contrib

**Comment by gbalykov** [comment]
We observe the same behaviour on armel, during compilation of system libs, runtime 5.0 855e2961ba70d3ed8b094d230aaf655adac2b76e.

For example, if `System.Reflection.Metadata.dll` is compiled to R2R image, then next libs fail to be compiled:
```
System.AppContext.dll
System.Private.CoreLib.dll
System.Net.Sockets.dll
System.Runtime.Loader.dll
System.Reflection.Emit.Lightweight.dll
System.Net.WebClient.dll
System.Resources.Writer.dll
System.Net.WebSockets.dll
System.dll
System.IO.MemoryMappedFiles.dll
System.Drawing.Primitives.dll
System.Numerics.dll
System.Collections.Specialized.dll
System.Private.Uri.dll
System.Data.dll
System.Net.Primitives.dll
System.Xml.XmlSerializer.dll
System.Security.Cryptography.Algorithms.dll
System.IO.FileSystem.AccessControl.dll
System.Console.dll
System.Globalization.Extensions.dll
System.Text.RegularExpressions.dll
System.Private.Xml.dll
System.Resources.Reader.dll
System.Security.Cryptography.Encoding.dll
System.Diagnostics.DiagnosticSource.dll
System.Xml.ReaderWriter.dll
System.Globalization.Calendars.dll
System.Threading.Tasks.Parallel.dll
System.ComponentModel.Annotations.dll
System.IO.FileSystem.dll
System.Core.dll
System.Linq.Queryable.dll
System.Security.Principal.dll
System.Security.Cryptography.Cng.dll
System.Data.DataSetExtensions.dll
System.Net.WebProxy.dll
System.Diagnostics.Tracing.dll
System.Runtime.Serialization.Json.dll
System.Net.Http.Json.dll
System.IO.IsolatedStorage.dll
ILCompiler.DependencyAnalysisFramework.dll
System.CommandLine.dll
ILCompiler.TypeSystem.ReadyToRun.dll
Microsoft.DiaSymReader.dll
crossgen2.dll
ILCompiler.ReadyToRun.dll
System.IO.FileSystem.Watcher.dll
System.Runtime.Numerics.dll
System.ComponentModel.TypeConverter.dll
System.Net.HttpListener.dll
System.Runtime.CompilerServices.Unsafe.dll
System.ComponentModel.EventBasedAsync.dll
System.Threading.dll
System.Text.Encoding.Extensions.dll
System.IO.Compression.FileSystem.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Runtime.InteropServices.dll
System.Threading.Tasks.Dataflow.dll
System.Net.Ping.dll
System.ComponentModel.Primitives.dll
System.Net.Requests.dll
System.Formats.Asn1.dll
System.Xml.Serialization.dll
System.Runtime.Serialization.Primitives.dll
System.Xml.XDocument.dll
```

Output for System.Private.CoreLib.dll:
```
Error: Read out of bounds.
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetName(TypeDefinitionHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.GetType(String nameSpace, String name, Boolean throwIfNotFound) in /home/runtime/src/coreclr/src/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 288
   at Internal.TypeSystem.MetadataTypeSystemContext.SetSystemModule(ModuleDesc systemModule) in /home/runtime/src/coreclr/src/tools/Common/TypeSystem/Common/MetadataTypeSystemContext.cs:line 73
   at ILCompiler.Program.Run() in /home/runtime/src/coreclr/src/tools/aot/crossgen2/Program.cs:line 411
   at ILCompiler.Program.InnerMain(CommandLineOptions buildOptions) in /home/runtime/src/coreclr/src/tools/aot/crossgen2/Program.cs:line 684
```

Crossgen2 cmd:
```sh
./corerun `pwd`/crossgen2/crossgen2.dll -r:`pwd`/* -r:`pwd`/crossgen2/* -O -o:`pwd`/System.AppContext.ni.dll `pwd`/System.AppContext.dll
```

Command above succeeds if there is no System.Reflection.Metadata.dll.

Does crossgen2 have any limitations at this moment, i.e. is this expected?

cc @alpencolt

**Comment by davidwrighton** [comment]
The issue with out of bounds ibc data tokens has been fixed for some time. The armel failure is unrelated.
