### ISSUE TITLE
Test failure: System.Drawing.Tests.BitmapTests.LockBits_Invoke_Success(bitmap: Bitmap { Flags = 0, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 0, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, rectangle: {X=0,Y=0,Width=100,Height=100}, lockMode: WriteOnly, pixelFormat: Format24bppRgb, expectedStride: 300, expectedReserved: 65538)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42518]
failed in job: [runtime-coreclr libraries-jitstress2-jitstressregs 20200919.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=822235&view=ms.vss-test-web.build-test-results-tab&runId=26173284&resultId=118931&paneView=debug)

net5.0-Linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

Error message
~~~
System.ArgumentException : Parameter is not valid.


Stack trace
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs:line 96
   at System.Drawing.Bitmap.UnlockBits(BitmapData bitmapdata) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 259
   at System.Drawing.Tests.BitmapTests.Do_LockBits_Invoke_Success(Bitmap bitmap, Rectangle rectangle, ImageLockMode lockMode, PixelFormat pixelFormat, Int32 expectedStride, Int32 expectedReserved) in /_/src/libraries/System.Drawing.Common/tests/BitmapTests.cs:line 1226
   at System.Drawing.Tests.BitmapTests.LockBits_Invoke_Success(Bitmap bitmap, Rectangle rectangle, ImageLockMode lockMode, PixelFormat pixelFormat, Int32 expectedStride, Int32 expectedReserved) in /_/src/libraries/System.Drawing.Common/tests/BitmapTests.cs:line 1190
~~~

**Comment by safern** [comment]
Seems related to : https://github.com/dotnet/runtime/issues/30184

**Comment by VincentBu** [comment]
Failed again in  [runtime-coreclr libraries-jitstress2-jitstressregs 20210605.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1172838&view=ms.vss-test-web.build-test-results-tab&runId=35332854&resultId=127727&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.Drawing.Tests.BitmapTests.LockBits_Invoke_Success(bitmap: Bitmap { Flags = 2, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 2, HorizontalResolution = 0, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, rectangle: {X=0,Y=0,Width=2,Height=2}, lockMode: ReadWrite, pixelFormat: Format32bppArgb, expectedStride: 8, expectedReserved: 3)

```
**Error message:**
```
System.ArgumentException : Parameter is not valid.


Stack trace
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs:line 96
   at System.Drawing.Bitmap.UnlockBits(BitmapData bitmapdata) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 285
   at System.Drawing.Tests.BitmapTests.Do_LockBits_Invoke_Success(Bitmap bitmap, Rectangle rectangle, ImageLockMode lockMode, PixelFormat pixelFormat, Int32 expectedStride, Int32 expectedReserved) in /_/src/libraries/System.Drawing.Common/tests/BitmapTests.cs:line 1225
   at System.Drawing.Tests.BitmapTests.LockBits_Invoke_Success(Bitmap bitmap, Rectangle rectangle, ImageLockMode lockMode, PixelFormat pixelFormat, Int32 expectedStride, Int32 expectedReserved) in /_/src/libraries/System.Drawing.Common/tests/BitmapTests.cs:line 1189
```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
