### ISSUE TITLE
Test failure: Interop\\COM\\ComWrappers\\API\\ComWrappersTests\\ComWrappersTests.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42513]
failed in job: [runtime-coreclr gcstress-extra 20200920.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=822874&view=ms.vss-test-web.build-test-results-tab&runId=26195706&resultId=104814&paneView=debug)

CoreCLR Windows_NT arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Arm64v8.Open

Error message
~~~
Return code:      1
Raw output file:      D:\h\w\9F9108D1\w\A9B8096D\e\Interop\COM\Reports\Interop.COM\ComWrappers\API\ComWrappersTests\ComWrappersTests.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\9F9108D1\p\corerun.exe" ComWrappersTests.dll 
Running ValidateComInterfaceCreation...
Running ValidateFallbackQueryInterface...
Running ValidateCreateObjectCachingScenario...
Running ValidateWrappersInstanceIsolation...
Running ValidatePrecreatedExternalWrapper...
Running ValidateIUnknownImpls...
Running ValidateBadComWrapperImpl...
Running ValidateRuntimeTrackerScenario...
Test Failure: TestLibrary.AssertTestException: Assert.IsTrue: 
   at TestLibrary.Assert.HandleFail(String assertionName, String message) in /__w/1/s/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 734
   at TestLibrary.Assert.IsTrue(Boolean condition, String message) in /__w/1/s/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 301
   at ComWrappersTests.Program.ValidateRuntimeTrackerScenario() in /__w/1/s/src/tests/Interop/COM/ComWrappers/API/Program.cs:line 376
   at ComWrappersTests.Program.Main(String[] doNotUse) in /__w/1/s/src/tests/Interop/COM/ComWrappers/API/Program.cs:line 411
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\9F9108D1\p
> D:\h\w\9F9108D1\w\A9B8096D\e\Interop\COM\ComWrappers\API\ComWrappersTests\ComWrappersTests.cmd
Expected: True

Actual:   False


Stack trace
   at Interop_COM._ComWrappers_API_ComWrappersTests_ComWrappersTests_._ComWrappers_API_ComWrappersTests_ComWrappersTests_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 237
~~~

**Comment by jeffschwMSFT** [comment]
@AaronRobinsonMSFT can you take a look?

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr gcstress-extra 20201122.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=895976&view=ms.vss-test-web.build-test-results-tab&runId=28633226&resultId=105070&paneView=debug)

failed test: Interop\\COM\\ComWrappers\\API\\ComWrappersTests\\ComWrappersTests.cmd

CoreCLR windows arm64 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Arm64v8.Open


Error message
~~~
Return code:      1
Raw output file:      D:\h\w\A122089F\w\C3BC0A6B\e\Interop\COM\Reports\Interop.COM\ComWrappers\API\ComWrappersTests\ComWrappersTests.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A122089F\p\corerun.exe" ComWrappersTests.dll 
Running ValidateComInterfaceCreation...
Running ValidateFallbackQueryInterface...
Running ValidateCreateObjectCachingScenario...
Running ValidateWrappersInstanceIsolation...
Running ValidatePrecreatedExternalWrapper...
Running ValidateIUnknownImpls...
Running ValidateBadComWrapperImpl...
Running ValidateRuntimeTrackerScenario...
Test Failure: TestLibrary.AssertTestException: Assert.IsTrue: 
   at TestLibrary.Assert.HandleFail(String assertionName, String message) in /__w/1/s/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 734
   at TestLibrary.Assert.IsTrue(Boolean condition, String message) in /__w/1/s/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 301
   at ComWrappersTests.Program.ValidateRuntimeTrackerScenario() in /__w/1/s/src/tests/Interop/COM/ComWrappers/API/Program.cs:line 376
   at ComWrappersTests.Program.Main(String[] doNotUse) in /__w/1/s/src/tests/Interop/COM/ComWrappers/API/Program.cs:line 411
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\A122089F\p
> D:\h\w\A122089F\w\C3BC0A6B\e\Interop\COM\ComWrappers\API\ComWrappersTests\ComWrappersTests.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._ComWrappers_API_ComWrappersTests_ComWrappersTests_._ComWrappers_API_ComWrappersTests_ComWrappersTests_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.arm64.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 260
~~~
