### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: The operation was canceled.

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/runtime#42524]
Hello,

I have migrated my projet from .NET Framework to .NET Core 3.1, i have two proxies, the first one for connection
 to dynamics CRM and the second for connection to WebApi,

the first time i connect to CRM using proxy like code below

```c#
public static CdsServiceClient InitCRMConnection()
        {
            try
            {

                System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls13;

                var _proxyurl = VSMP_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_Settings//ProxyUrl").InnerText;
                var _proxyport = Convert.ToInt32(PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_Settings//ProxyPort").InnerText);
                var _proxylogin = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_Settings//ProxyLogin").InnerText;
                var _proxypass = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_Settings//ProxyPass").InnerText;
                var _proxyswitch = Convert.ToBoolean(PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_Settings//ProxySwitch").InnerText);

                //proxy bypass connection settings

                if (_proxyswitch)
                {
                    var proxy = new WebProxy(_proxyurl, _proxyport);
                    HttpClient.DefaultProxy.Credentials = new NetworkCredential(_proxylogin, _proxypass);
                    HttpClient.DefaultProxy = proxy;
                }
                string connectionstring = ConfigurationManager.ConnectionStrings["connectionPROJECTSecretkeyPROJECT"].ConnectionString;
                sp = new CdsServiceClient(connectionstring);
            }

            catch (Exception ex)
            {
                LogHelper.Writer("Erreur lors de la connexion au crm, Message de l'erreur : " + Environment.NewLine + ex.ToString());
            }

            return sp;
        }
```
the first time the proxy is taken into account because I get no connection errors but when I start to call the webapi with another proxy

```c#
protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {

                _proxyurl = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_SettingsWSPROD//ProxyUrl").InnerText;
                _proxyport = Convert.ToInt32(PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_SettingsWSPROD//ProxyPort").InnerText);
                _proxyswitch = Convert.ToBoolean(PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Proxy_SettingsWSPROD//ProxySwitch").InnerText);

                 if (_proxyswitch)
                {
                    var proxy = new WebProxy(_proxyurl, _proxyport);
                    HttpClient.DefaultProxy.Credentials = CredentialCache.DefaultCredentials;
                    HttpClient.DefaultProxy = proxy;
                }

                HttpResponseMessage response = null;

                _applicationId = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Contracts_Settings//HmacID").InnerText;
                _secretKey = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Contracts_Settings//HmacSecret").InnerText;

                var _secretKeyUTF8 = UTF8Encoding.UTF8.GetBytes(_secretKey);
                string nonce = Guid.NewGuid().ToString("N");

                var gbCulture = new CultureInfo("en-GB");
                // Get current UTC time.   
                var utcDate = DateTime.UtcNow;

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss", gbCulture) + " GMT";


                //string Date = "date:" + UpperCaseUrlEncode(str);
                string Date = "date: " + utcFormattedDate;
                //Date = "date:Thu%2C+21+Apr+2016+13%3A32%3A18+UTC";
                using (HMACSHA1 hmac = new HMACSHA1(_secretKeyUTF8))
                {
                    byte[] Datebytes = Encoding.UTF8.GetBytes(Date);
                    byte[] hashedValue = hmac.ComputeHash(Datebytes);
                    string Signature = Convert.ToBase64String(hashedValue);
                    string Url_Encoded_Signature = UpperCaseUrlEncode(Signature);

                    request.Headers.Add("Authorization", string.Format("Signature keyId=\"{0}\",algorithm=\"{1}\",signature=\"{2}\"", _applicationId, "hmac-sha1", Url_Encoded_Signature));
                    var field = typeof(System.Net.Http.Headers.HttpRequestHeaders)
                                .GetField("invalidHeaders", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)
                              ?? typeof(System.Net.Http.Headers.HttpRequestHeaders)
                                .GetField("s_invalidHeaders", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                    if (field != null)
                    {
                        var invalidFields = (HashSet<string>)field.GetValue(null);
                        invalidFields.Remove("Content-Type");
                    }
                    request.Headers.Add("Date", utcFormattedDate);
                    request.Headers.TryAddWithoutValidation("Content-Type", "application/json;charset=UTF-8");


                }

                bool success = false;

                do
                {
                    response = await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
                    success = response.IsSuccessStatusCode;
                }
                while (!success);

                return response;

            }
```
Here i get error, 

```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 81
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 662
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 675
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 345
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 554
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnel(HttpRequestHeaders headers, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 704
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 662
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 675
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 345
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 554
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Future.cs:line 491
   at System.Threading.Tasks.Task`1.get_Result() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/Future.cs:line 461
```

Note that if I put the environment variables, it works perfectly
export http_proxy .............
export https_proxy ................

i runed my application in RedHat 7.1

Cordially

@karelz  @stephentoub

**Comment by karelz** [comment]
Does it mean, that using first proxy always works and using second proxy never does?
Are you able to verify this in simple HelloWorld app which uses only second proxy?
Or does it fail only if you first use the first proxy, then the second in the same app?

**Comment by HASSEN-MEDDEB-ATOS** [comment]
Does it mean, that using first proxy always works and using second proxy never does? Yes That's what I mean
Are you able to verify this in simple HelloWorld app which uses only second proxy? Yes i did et it work.
Or does it fail only if you first use the first proxy, then the second in the same app? Yes i use two proxies in the same app in the first time i connect to Dynamics with the first proxy, it work. and next i call WEBAPI and it fail, i get error 
System.Threading.Tasks.TaskCanceledException: The operation was canceled.

**Comment by karelz** [comment]
@HASSEN-MEDDEB-ATOS looking into this more -- it would be best to use separate HttpClient instances for each proxy and configure the proxy per HttpClient (before its first usage) via [SocketsHttpHandler.Proxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.proxy?view=net-5.0).
Changes to `DefaultProxy` are not observed by existing and used SocketsHttpHandler instances.

It think that should solve your problem here. Let me know if it does not.
