### ISSUE TITLE
Resolve Remaining Android Device Test Failures

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#42548]
The run in https://github.com/dotnet/runtime/pull/42209 was pretty successful with only 2 failures.  For now, I'll list them in one issue as they seem manageable.  

#### System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests.PropertiesOfValidDrive

```
Assert.True() Failure
Expected: True
Actual:   False

at System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests.PropertiesOfValidDrive() in /_/src/libraries/System.IO.FileSystem.DriveInfo/tests/DriveInfo.Unix.Tests.cs:line 83
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

#### Microsoft.Extensions.Configuration.Xml.Tests

This may be a problem waiting for a device.  Filed an issue at https://github.com/dotnet/xharness/issues/308

```
[11:26:36] info: test[0]
      Waiting for device to be available (max 5 minutes)
[11:26:36] dbug: test[0]
      Executing command: 'C:\h\w\AE270924\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.20457.1\runtimes\any\native\adb\windows\adb.exe -s 023AYV0V1W wait-for-device'
[11:31:37] fail: test[0]
      Waiting for command timed out: execution may be compromised.
[11:31:37] crit: test[0]
      Failure to run test package: Process must exit before requested information can be determined.
System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at Microsoft.DotNet.XHarness.Android.Execution.AdbProcessManager.Run(String adbExePath, String arguments, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs:line 88
   at Microsoft.DotNet.XHarness.Android.AdbRunner.RunAdbCommand(String command, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 441
   at Microsoft.DotNet.XHarness.Android.AdbRunner.WaitForDevice() in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 121
   at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 102
XHarness exit code: 1001
```

**Comment by steveisok** [comment]
@MattGal The second failure looks more like a device acquisition timeout.  If that's the case, I'll separate it into another issue.  

Can you please take a look?

**Comment by MattGal** [comment]
> @MattGal The second failure looks more like a device acquisition timeout. If that's the case, I'll separate it into another issue.
> 
> Can you please take a look?

Agree, looks like a bug in `AdbProcessManager.Run` though the timeout may still be the memory concern.  Can you open an issue in dotnet/xharness with that error?

**Comment by steveisok** [comment]
Filed https://github.com/dotnet/xharness/issues/308

**Comment by steveisok** [comment]
@akoeplinger My guess at the first failure is something to do w/ `/` access on devices.  

See https://github.com/dotnet/runtime/blob/2483700909f03107c4219def40e48671fa250e5c/src/libraries/System.IO.FileSystem.DriveInfo/tests/DriveInfo.Unix.Tests.cs#L62-L87

**Comment by ViktorHofer** [comment]
```
[00:30:14] info: Attempting to remove apk 'net.dot.System.ComponentModel.Composition.Registration.Tests': 
[00:30:14] dbug: Executing command: '/home/helixbot/work/A7BE0957/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20559.2/runtimes/any/native/adb/linux/adb -s emulator-5554 uninstall net.dot.System.ComponentModel.Composition.Registration.Tests'
[00:35:14] fail: Waiting for command timed out: execution may be compromised.
[00:35:14] fail: Error: Exit code: -2
                 Standard Output:
```

Happened again in log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44835-merge-4889b661f47049acae/System.ComponentModel.Composition.Registration.Tests/console.9f4040e2.log?sv=2019-07-07&se=2020-12-08T00%3A00%3A42Z&sr=c&sp=rl&sig=uE1hNYz6bBbmeZvqAVBDgN5s8IoKq7y0AMTD6IXqQBM%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=889822&view=ms.vss-test-web.build-test-results-tab&runId=28459974&resultId=157521&paneView=attachments

**Comment by MaximLipnin** [comment]
The issue with `System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests.PropertiesOfValidDrive` is addressed in https://github.com/dotnet/runtime/pull/56462.
According to dotnet/xharness#308, the issue with `Microsoft.Extensions.Configuration.Xml.Tests` seems to be addressed as well.
We can close this issue.
