### ISSUE TITLE
Test failure: GC\\Features\\HeapExpansion\\pluggaps\\pluggaps.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42569]
failed in job: [runtime-coreclr r2r-extra 20200920.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=822955&view=ms.vss-test-web.build-test-results-tab&runId=26197320&resultId=109949&paneView=debug)

R2R Windows_NT arm64 Checked forcerelocs @ Windows.10.Arm64v8.Open

Error message
~~~
Fatal error. 0xE0004743
   at System.GC.Collect()
   at Test.Main()

Return code:      1
Raw output file:      D:\h\w\C0F60A6E\w\B1400982\e\GC\Features\Reports\GC.Features\HeapExpansion\pluggaps\pluggaps.output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
" "D:\h\w\C0F60A6E\p\crossgen.exe"  /Platform_Assemblies_Paths D:\h\w\C0F60A6E\p;D:\h\w\C0F60A6E\w\B1400982\e\GC\Features\HeapExpansion\pluggaps /in D:\h\w\C0F60A6E\w\B1400982\e\GC\Features\HeapExpansion\pluggaps\pluggaps.org /out D:\h\w\C0F60A6E\w\B1400982\e\GC\Features\HeapExpansion\pluggaps\\pluggaps.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image D:\h\w\C0F60A6E\w\B1400982\e\GC\Features\HeapExpansion\pluggaps\\pluggaps.dll generated successfully.
 "D:\h\w\C0F60A6E\p\corerun.exe" pluggaps.dll 
Beginning phase 1
phase 1 complete
Expected: 100
Actual: -536852669
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\C0F60A6E\p
> D:\h\w\C0F60A6E\w\B1400982\e\GC\Features\HeapExpansion\pluggaps\pluggaps.cmd
Expected: True
Actual:   False


Stack trace
   at GC_Features._HeapExpansion_pluggaps_pluggaps_._HeapExpansion_pluggaps_pluggaps_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\GC.Features\GC.Features.XUnitWrapper.cs:line 1498
~~~

**Comment by mangod9** [comment]
Closing since this was an intermittent failure.
