### ISSUE TITLE
Test failure: System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests.TestKeyTransEncryptedKey_RoundTrip

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42568]
failed in job: [runtime 20200921.82 ](https://dev.azure.com/dnceng/public/_build/results?buildId=824589&view=ms.vss-test-web.build-test-results-tab&runId=26256006&resultId=166770&paneView=debug)

net5.0-OSX-Release-x64-Mono_release-OSX.1014.Amd64.Open

Error message
~~~
Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (com.apple.security.transforms.error error -67718 - CDSA error (A module was not loaded.).)


Stack trace
   at Interop.AppleCrypto.TryExecuteTransform(ReadOnlySpan`1 source, Span`1 destination, Int32& bytesWritten, SecKeyTransform transform) in /_/src/libraries/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.SecKeyRef.cs:line 179
   at Interop.AppleCrypto.TryRsaEncrypt(SafeSecKeyRefHandle publicKey, ReadOnlySpan`1 source, Span`1 destination, RSAEncryptionPadding padding, Int32& bytesWritten) in /_/src/libraries/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.RSA.cs:line 196
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.TryEncrypt(ReadOnlySpan`1 data, Span`1 destination, RSAEncryptionPadding padding, Int32& bytesWritten) in /_/src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:line 320
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.Encrypt(Byte[] data, RSAEncryptionPadding padding) in /_/src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:line 282
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.MakeKtri(Byte[] cek, CmsRecipient recipient, Boolean& v0Recipient) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.KeyTrans.cs:line 173
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes, Byte[] encryptedContent, Byte[] cek, Byte[] parameterBytes) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs:line 112
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs:line 36
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipientCollection recipients) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 109
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipient recipient) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 92
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests.EncodeKeyTransl(SubjectIdentifierType type) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/KeyTransRecipientInfoTests.cs:line 204
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests.TestKeyTransEncryptedKey_RoundTrip() in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/KeyTransRecipientInfoTests.cs:line 179
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 384
~~~

**Comment by vcsjones** [comment]
I can't see how this could happen unless the Mac in question was in a very weird state, perhaps in the middle of logging out or shutting down? We don't explicitly load or unload CSSM modules anywhere.

As far as I can tell, this error only happens in macOS when requesting a CSSM module that is unloaded. https://opensource.apple.com/source/Security/Security-54/cdsa/cssm/manager.cpp.auto.html

**Comment by bartonjs** [comment]
There are no instances of this (or similar) failures in our rolling test history, seems to have been a transient OS or machine issue.
