### ISSUE TITLE
Experiencing NotSupportedException when using HttpClient SendAsync

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#42615]
### Description

In load tests we sometimes experience the following NotSupportedException when calling HttpClient.SendAsync:

```
System.NotSupportedException: The stream does not support concurrent IO read or write operations.
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.Http.StreamToStreamCopy.TryStartWriteSync(Int32 bytesRead)
   at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OurClass.<PerformRequestAsync>d__7.MoveNext() in C:\Build\d6a438e92f31b729\OurProject\OurClass.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
[snip]
```

We're calling the SendAsync method in a pretty default way:

```
var task = _httpClient.SendAsync(
              new HttpRequestMessage(HttpMethod.Post, GetAbsoluteUrl(relativeUrl)) { Content = content },
              HttpCompletionOption.ResponseHeadersRead)
```

When we await the returned task we sometimes run into the NotSupportedException. This looks like a bug in the HttpClient stream handling implementation.

### Configuration

* .NET Framework 4.7.2 (within a Docker container using the base image dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019)
* OS: Windows Server Core LTSC 2019
* x64

### Other information

This looks kinda related: https://stackoverflow.com/questions/37690550/system-net-httpclient-throws-uploading-files-the-stream-does-not-support-concur 

Best regards,
D.R.

**Comment by ManickaP** [comment]
Is this .NET Framework issue? Does is happen on .NET Core as well?
If it's only on .NET Framework, please file the issue in Developer Community: https://developercommunity.visualstudio.com/spaces/61/index.html

Just be aware that bar is very high for .NET Framework bug fixes and it might not clear it.

**Comment by drauch** [comment]
=> https://developercommunity.visualstudio.com/content/problem/1195371/experiencing-notsupportedexception-when-using-http.html

**Comment by ManickaP** [comment]
Thank you, closing this. If you encounter the problem on .NET Core, feel free to reopen.
