### ISSUE TITLE
Test failure: System.Net.Security.Tests.TelemetryTest.EventSource_SuccessfulHandshake_LogsStartStop

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42613]
failed in job: [runtime-libraries-coreclr outerloop 20200922.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=825084&view=ms.vss-test-web.build-test-results-tab&runId=26282208&paneView=debug&resultId=102213)

net5.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0, 0, 0]
   at System.Net.Security.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 144
   at System.Net.Security.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulHandshake_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 59
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Security.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulHandshake_LogsStartStop>b__1_0()
~~~

**Comment by ManickaP** [comment]
cc: @MihaZupan

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201019.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=858234&view=ms.vss-test-web.build-test-results-tab&runId=27486140&resultId=102031&paneView=debug)

failed test: System.Net.Security.Tests.TelemetryTest.EventSource_SuccessfulHandshake_LogsStartStop

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0]
   at System.Net.Security.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 144
   at System.Net.Security.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulHandshake_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 59
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Security.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulHandshake_LogsStartStop>b__1_0()
~~~

**Comment by v-haren** [comment]
failed again in job: [ runtime-libraries-coreclr outerloop 20201206.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=909967&view=ms.vss-test-web.build-test-results-tab&runId=29001804&resultId=102256&paneView=debug)

failed test: System.Net.Security.Tests.TelemetryTest.EventSource_SuccessfulHandshake_LogsStartStop

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0, 0, 0]
   at System.Net.Security.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 144
   at System.Net.Security.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulHandshake_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 59
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Security.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulHandshake_LogsStartStop>b__1_0()
~~~

**Comment by VincentBu** [comment]
Failed again in job [runtime-libraries-coreclr outerloop 20210117.2](https://dev.azure.com/dnceng/public/_build/results?buildId=954714&view=ms.vss-test-web.build-test-results-tab&runId=30122616&paneView=debug&resultId=102258)

Failed tests:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
        - System.Net.Security.Tests.TelemetryTest.EventSource_SuccessfulHandshake_LogsStartStop
```

Error message:
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


stack trace:
Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0, 0, 0, 0]
   at System.Net.Security.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 144
   at System.Net.Security.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulHandshake_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 59
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Security.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulHandshake_LogsStartStop>b__1_0()
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210331.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1065359&view=ms.vss-test-web.build-test-results-tab&runId=32792208&resultId=102172&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
 -System.Net.Security.Tests.TelemetryTest.EventSource_SuccessfulHandshake_LogsStartStop
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0, 0, 0]
   at System.Net.Security.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 144
   at System.Net.Security.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulHandshake_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 59
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Security.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulHandshake_LogsStartStop>b__1_0()
```

**Comment by karelz** [comment]
Failures during 2/23-5/10 (incl. PRs):

Date | Build / PR | OS
-- | -- | --
3/31 | Official run | OSX.1014.Amd64.Open
4/13 | Official run | OSX.1015.Amd64.Open
4/17 | Official run | OSX.1015.Amd64.Open
4/21 | Official run | OSX.1015.Amd64.Open
4/26 | Official run | Windows.81.Amd64.Open
5/1 | Official run | OSX.1014.Amd64.Open
5/3 | Official run | OSX.1015.Amd64.Open

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210603.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1168913&view=ms.vss-test-web.build-test-results-tab&runId=35223908&resultId=102190&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

- System.Net.Security.Tests.TelemetryTest.EventSource_SuccessfulHandshake_LogsStartStop

```
**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  Double[] [0, 0, 0, 0]
   at System.Net.Security.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 144
   at System.Net.Security.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulHandshake_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs:line 59
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Security.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulHandshake_LogsStartStop>b__1_0()
```

**Comment by karelz** [comment]
@MihaZupan could it be something similar to the recently fixed Telemetry tests?

**Comment by MihaZupan** [comment]
I will take a look

**Comment by MihaZupan** [comment]
Yes, there is the same kind of race condition in these tests as in the ones we fixed in sockets/http in the past. I will put up a PR

**Comment by aik-jahoda** [comment]
@MihaZupan  I was able to reproduce this issue in helix test loop on latest main

**Comment by MihaZupan** [comment]
What kind of issue did you observe (failure / timeout / hang)?

**Comment by aik-jahoda** [comment]
It is Assert: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/results-4d505ac13aae4f81aa/Hello%20World/1/console.a89413d1.log?sv=2019-07-07&se=2021-08-26T08%3A38%3A04Z&sr=c&sp=rl&sig=ezfG%2Bs2at0HpojnrCB3zBVEo6a25FED5EwqLpKMOdn8%3D

**Comment by MihaZupan** [comment]
Ah I see, this is a test bug. If the handshake completes quickly, we would never see a non-zero "current". I'll look at fixing it now.
