### ISSUE TITLE
Test failure: PostAsyncDuplex_DisposeResponseBodyBeforeEnd_ResetsStreamAndThrowsOnRequestStreamWriteAndResponseStreamRead

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#42722]
```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.PostAsyncDuplex_DisposeResponseBodyBeforeEnd_ResetsStreamAndThrowsOnRequestStreamWriteAndResponseStreamRead [FAIL]
      System.Threading.Tasks.TaskCanceledException : A task was canceled.
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1466,0): at System.Net.Http.Http2Connection.SendStreamDataAsync(Int32 streamId, ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs(1255,0): at System.Net.Http.Http2Connection.Http2Stream.SendDataAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(2333,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.SendAndReceiveRequestDataAsync(Memory`1 data, Stream requestStream, Http2LoopbackConnection connection, Int32 streamId)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(2736,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.PostAsyncDuplex_DisposeResponseBodyBeforeEnd_ResetsStreamAndThrowsOnRequestStreamWriteAndResponseStreamRead()
        --- End of stack trace from previous location ---
```

Seems to have failed 8 times since September 8th on different machines/platforms.

**Comment by karelz** [comment]
No failure in main/master branch in last 2 months: 2/23-4/23, closing
