### ISSUE TITLE
SslStream: Provide better error message for authentication exception

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#42740]
This came as part of feedback in an ASP.NET Core issue: https://github.com/dotnet/aspnetcore/issues/15105. Users had a expired cert, but the exception you get is a generic "The remote certificate is invalid according to the validation procedure.".

The ask is to provide more specific error messages:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
```

**Comment by stephentoub** [comment]
It looks like this came from .NET Core 2.2.  @wfurt, is this one of the errors you already improved for .NET 5?

**Comment by vcsjones** [comment]
I just tried in RC1, it looks better:

```
Unhandled exception. System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
```

**Comment by wfurt** [comment]
yes, this exception will now have enum details.

**Comment by stephentoub** [comment]
While I'd have preferred that the public enum value `NotTimeValid` read a bit better :smile:, that ship has long-since sailed, and searching for that value finds the docs and a reasonable description: 
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainstatusflags?view=netcore-3.1
"Specifies that the X509 chain is not valid due to an invalid time value, such as a value that indicates an expired certificate."

Seems like this issue has been addressed then.

Thanks!

**Comment by pranavkm** [comment]
Good to know. Thanks!
