### ISSUE TITLE
Test failure: Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42802]
failed in job: [runtime-coreclr gcstress-extra 20200927.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=833311&view=ms.vss-test-web.build-test-results-tab&runId=26563210&resultId=103056&paneView=debug)

CoreCLR Linux x64 Checked gcstress0xc_zapdisable_jitstress2 @ Ubuntu.1804.Amd64.Open

Error message
~~~
Assert failure(PID 2643 [0x00000a53], Thread: 2653 [0x0a5d]): refCollectionObject != NULL
    File: /__w/1/s/src/coreclr/src/vm/gcenv.ee.common.cpp Line: 190
    Image: /home/helixbot/work/A0510861/p/corerun

/home/helixbot/work/A0510861/w/A2640914/e/Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh: line 363:  2643 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /home/helixbot/work/A0510861/w/A2640914/e/Interop/ICustomMarshaler/Reports/Interop.ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/A0510861/p/corerun MultipleALCs.dll ''
Gathering state for process 2643 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.2643.dmp
Written 57786368 bytes (14108 pages) to core file
Dump successfully written
Expected: 100
Actual: 134

END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/A0510861/p
> /home/helixbot/work/A0510861/w/A2640914/e/Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh
Expected: True
Actual:   False


Stack trace
   at Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.x64.Checked/TestWrappers/Interop.ICustomMarshaler/Interop.ICustomMarshaler.XUnitWrapper.cs:line 140
~~~

**Comment by jeffschwMSFT** [comment]
@AaronRobinsonMSFT can you help triage this issue?  Thanks

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Can you take a quick look to see if you can reproduce this issue? Nothing here on the interop side of the house has changed.

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr gcstress-extra 20210207.1](https://dev.azure.com/dnceng/public/_build/results?buildId=982567&view=ms.vss-test-web.build-test-results-tab&runId=30792410&resultId=101286&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked gcstress0xc_zapdisable_jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

  -Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh
```

**Error message:**
```
Assert failure(PID 927 [0x0000039f], Thread: 942 [0x03ae]): refCollectionObject != NULL
 File: /__w/1/s/src/coreclr/vm/gcenv.ee.common.cpp Line: 190
 Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh: line 395: 927 Aborted (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/Interop/ICustomMarshaler/Reports/Interop.ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun MultipleALCs.dll ''
Gathering state for process 927 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.927.dmp
Written 53735424 bytes (13119 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh
Expected: True
Actual: False

Stack trace
   at Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_sh()

```

**Comment by AaronRobinsonMSFT** [comment]
Closing as a dup of #47696
