### ISSUE TITLE
CG2 runtime failure in several tests - Could not execute the method because either the method itself or the containing type is not fully instantiated

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#42850]
Example run:

https://dev.azure.com/dnceng/public/_build/results?buildId=834885

Platform: all

Diagnostic information:

<pre>
      Unhandled exception. System.InvalidOperationException: Could not execute the method because either the method itself or the containing type is not fully instantiated.
         at System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference[T](T[] array)
         at Interop.Sys.ReadLink(String path, Byte[] buffer, Int32 bufferSize)
         at Interop.Sys.ReadLink(String path)
         at System.TimeZoneInfo.FindTimeZoneIdUsingReadLink(String tzFilePath)
         at System.TimeZoneInfo.TryLoadTzFile(String tzFilePath, Byte[]& rawData, String& id)
         at System.TimeZoneInfo.TryGetLocalTzFile(Byte[]& rawData, String& id)
         at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile()
         at System.TimeZoneInfo.GetLocalTimeZone(CachedData cachedData)
         at System.TimeZoneInfo.CachedData.CreateLocal()
         at System.TimeZoneInfo.CachedData.get_Local()
         at System.TimeZoneInfo.get_Local()
         at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc(DateTime time, Boolean& isAmbiguousLocalDst)
         at System.DateTime.get_Now()
         at SciMark2.Stopwatch.seconds()
         at SciMark2.kernel.measureFFT(Int32 N, Double mintime, Random R)
         at SciMark2.CommandLine.Main(String[] args)
</pre>

/cc: @dotnet/crossgen-contrib

**Comment by mangod9** [comment]
@jkotas as an FYI, since the function pointer change was merged a few days ago, but I believe the cg2 CI job was run as part of that change and it didnt show many failures, so this is something recent.

**Comment by trylek** [comment]
FWIW my PR fixing the Composite flag for framework compilation using r2rtest now also fails in CG2 composite run complaining that "it cannot verify layout for Object". I'm not sure whether it can be related somehow but apparently something around CG2 / runtime got recently broken.

https://dev.azure.com/dnceng/public/_build/results?buildId=834563

**Comment by trylek** [comment]
Fixed in https://github.com/dotnet/runtime/pull/43054.
