### ISSUE TITLE
[wasm][tests][browser] Ssl test incorrectly failing with `DllNotFoundException`, instead of a PNSE

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#42864]
```xml
<test name="System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds" type="System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_SslProtocols_Test" method="GetAsync_AllowedSSLVersion_Succeeds" time="0" result="Fail">
        <failure exception-type="System.DllNotFoundException">
          <message><![CDATA[System.DllNotFoundException : libSystem.Security.Cryptography.Native.OpenSsl]]></message>
          <stack-trace><![CDATA[   at System.PlatformDetection.OpenSslGetTlsSupport(SslProtocols protocol)
   at System.PlatformDetection.GetTls10Support()
   at System.Lazy`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
   at System.Lazy`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
   at System.PlatformDetection.get_SupportsTls10()
   at System.Net.Test.Common.SslProtocolSupport.get_SupportedSslProtocols()
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds_MemberData()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object[], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()]]></stack-trace>
        </failure>
      </test>
```

**Comment by lewing** [comment]
This is expected to fail we are looking into the type of exception.

**Comment by lewing** [comment]
This just a platform detection failure on a test that doesn't need to be run.  Closing.
