### ISSUE TITLE
[wasm][tests][browser] Investigate: HttpConnectionKey test failing

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#42865]
```xml
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Https\&quot;, host: \&quot;localhost\&quot;, port: 80, sslHostName: \&quot;localhost-ssl\&quot;, proxyUri: http://localhost/, identity: \&quot;domain1/userA\&quot;, expected: False)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.002665" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Http\&quot;, host: \&quot;localhost1\&quot;, port: 80, sslHostName: \&quot;localhost-ssl\&quot;, proxyUri: http://localhost/, identity: \&quot;domain1/userA\&quot;, expected: False)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.00032" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Http\&quot;, host: \&quot;localhost\&quot;, port: 81, sslHostName: \&quot;localhost-ssl\&quot;, proxyUri: http://localhost/, identity: \&quot;domain1/userA\&quot;, expected: False)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.00034" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Http\&quot;, host: \&quot;localhost\&quot;, port: 80, sslHostName: \&quot;localhost-ssl1\&quot;, proxyUri: http://localhost/, identity: \&quot;domain1/userA\&quot;, expected: False)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.000285" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Http\&quot;, host: \&quot;localhost\&quot;, port: 80, sslHostName: \&quot;localhost-ssl\&quot;, proxyUri: http://localhost1/, identity: \&quot;domain1/userA\&quot;, expected: False)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.00027" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Http\&quot;, host: \&quot;localhost\&quot;, port: 80, sslHostName: \&quot;localhost-ssl\&quot;, proxyUri: http://localhost/, identity: \&quot;domain1/userB\&quot;, expected: False)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.00035" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(kindString: \&quot;Http\&quot;, host: \&quot;localhost\&quot;, port: 80, sslHostName: \&quot;localhost-ssl\&quot;, proxyUri: http://localhost/, identity: \&quot;domain1/userA\&quot;, expected: True)" type="System.Net.Http.Functional.Tests.HttpConnectionKeyTest" method="Equals_DifferentParameters_ReturnsTrueIfAllEqual" time="0.0002999" result="Fail">
        <failure exception-type="System.InvalidOperationException">
          <message><![CDATA[System.InvalidOperationException : Sequence contains no elements]]></message>
          <stack-trace><![CDATA[   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[Type](IEnumerable`1 source)
   at System.Net.Http.Functional.Tests.HttpConnectionKeyTest.Equals_DifferentParameters_ReturnsTrueIfAllEqual(String kindString, String host, Int32 port, String sslHostName, Uri proxyUri, String identity, Boolean expected)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
```

**Comment by radical** [comment]
This is failing because *internal* types `System.Net.Http.HttpConnectionKind`, and `System.Net.Http.HttpConnectionPoolManager` are not included for the browser.

**Comment by lewing** [comment]
We should just skip the tests on browser then.
