### ISSUE TITLE
[wasm][tests][browser] Test with System.Net.Http.HttpMessageHandler.Send fails

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#42862]
Test failing with `The synchronous method is not supported by 'System.Net.Http.BrowserHttpHandler'. If you're using a custom 'HttpMessageHandler' and wish to use synchronous HTTP methods, you must override its 'Send' virtual method`.
```xml
<test name="System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandlerTest.SendAsync_TransferEncodingSetButNoRequestContent_Throws" type="System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandlerTest" method="SendAsync_TransferEncodingSetButNoRequestContent_Throws" time="0.01258" result="Fail">
        <failure exception-type="Xunit.Sdk.ThrowsException">
          <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.Net.Http.HttpRequestException)\nActual:   typeof(System.NotSupportedException): The synchronous method is not supported by 'System.Net.Http.BrowserHttpHandler'. If you're using a custom 'HttpMessageHandler' and wish to use synchronous HTTP methods, you must override its 'Send' virtual method.\n---- System.NotSupportedException : The synchronous method is not supported by 'System.Net.Http.BrowserHttpHandler'. If you're using a custom 'HttpMessageHandler' and wish to use synchronous HTTP methods, you must override its 'Send' virtual method.]]></message>
          <stack-trace><![CDATA[   at System.Net.Http.HttpMessageHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.Functional.Tests.VersionHttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<>n__1(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.Functional.Tests.HttpClientExtensions.<>c__DisplayClass0_0.<SendAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpMessageHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.Functional.Tests.VersionHttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<>n__1(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.Functional.Tests.HttpClientExtensions.<>c__DisplayClass0_0.<SendAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---]]></stack-trace>
        </failure>
      </test>
```

**Comment by lewing** [comment]
We expect this to throw an exception, this is tracking the type of the exception.

**Comment by karelz** [comment]
@mkArtakMSFT @lewing can you please triage it against 5.0? (set milestone)

**Comment by lewing** [comment]
@karelz if the question here is if Send throws on browser should it throw PlatformNotSupportedException or System.Net.Http.HttpRequestException?  I assume PNSE but I wanted to verify.

**Comment by lewing** [comment]
It would be best if we could expose that BrowserHttpHandler can't support sync Send to the platform analyzer but I don't see any way to do that.
