### ISSUE TITLE
Improve error message for unhandled exception in managed callback on Unix

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#42873]
### Description

Run repro from https://github.com/dotnet/runtime/issues/42842#issue-711147004

Actual behavior: 
The exception error contains "Internal CLR error" text that makes it look like something went wrong in CLR itself.
```
Unhandled exception. System.Exception: Callback failed
   at ConsoleApp.Program.Callback() in /mnt/c/repro/Program.cs:line 15
   at ConsoleApp.Program.DoWithCallback(IntPtr callbackPointer)
   at ConsoleApp.Program.Main(String[] args) in /mnt/c/repro/Program.cs:line 24
Fatal error. Internal CLR error. (0x80131506)
   at ConsoleApp.Program.DoWithCallback(IntPtr)
   at ConsoleApp.Program.DoWithCallback(IntPtr)
   at ConsoleApp.Program.Main(System.String[])
```

Expected behavior:
The exception does not contain "Internal CLR error" text.
```
Unhandled exception. System.Exception: Callback failed
   at ConsoleApp.Program.Callback() in /mnt/c/repro/Program.cs:line 15
   at ConsoleApp.Program.DoWithCallback(IntPtr callbackPointer)
   at ConsoleApp.Program.Main(String[] args) in /mnt/c/repro/Program.cs:line 24
```

**Comment by jkoritzinsky** [comment]
I just tested the repro locally against main and the "Internal CLR error" text no longer appears.
