### ISSUE TITLE
Test failure: System.Tests.GCExtendedTests.GetTotalAllocatedBytes

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42883]
failed in job: [runtime 20200929.92 ](https://dev.azure.com/dnceng/public/_build/results?buildId=836354&view=ms.vss-test-web.build-test-results-tab&runId=26646618&resultId=160190&paneView=debug)

net5.0-Linux-Release-x64-mono_interpreter_release-Debian.9.Amd64.Open

Error message
~~~
System.Exception : Expected more memory to be allocated. previous = 3148251576, precise = 3144001808, difference = 4249768


Stack trace
   at System.Tests.GCExtendedTests.<GetTotalAllocatedBytes>g__CallGetTotalAllocatedBytesAndCheck|25_0(Int64 previous, Int64& differenceBetweenPreciseAndImprecise) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 894
   at System.Tests.GCExtendedTests.<GetTotalAllocatedBytes>g__CallGetTotalAllocatedBytes|25_1(Int64 previous, <>c__DisplayClass25_0& ) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 904
   at System.Tests.GCExtendedTests.GetTotalAllocatedBytes() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 915
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 385
~~~

**Comment by naricc** [comment]
I recently re-enabled this after resolving a different issue, but now it is failing in another way. Here is a PR that will disable it when merged; will re-enable once I investigate and resolve: https://github.com/dotnet/runtime/pull/42921

**Comment by directhex** [comment]
Another failure: https://dev.azure.com/dnceng/public/_build/results?buildId=836476&view=results
