### ISSUE TITLE
Microsoft.NET.Sdk.WindowsDesktop crashes

### ISSUE THREAD

**Issue by BentleyJamesSlater** [dotnet/runtime#42979]
Hi , 

Having trouble constructing a Typeface object on windows nanoserver, maybe its a bug, or maybe i'm missing something?

Can be repeated using docker image: mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1909

In C# Just contruct a new System.Windows.Media.Typeface object, using a Microsoft.NET.Sdk.WindowsDesktop project

Typeface font = new Typeface("Arial");

It produces many nested exceptions:
```
The type initializer for 'System.Windows.Media.FontFamily' threw an exception.
   at System.Windows.Media.Typeface..ctor(String typefaceName)
   at ConsoleApp1.Program.Main(String[] args) in C:\Temp\SmileyFaceWpfLibrary\SmileyFaceWpfLibrary\ConsoleApp1\Program.cs:line 18
---- 
The type initializer for 'MS.Internal.FontCache.DWriteFactory' threw an exception.
   at MS.Internal.FontCache.DWriteFactory.get_SystemFontCollection()
   at System.Windows.Media.FontFamily..cctor()
----
The type initializer for '<Module>' threw an exception.
   at MS.Internal.FontCache.DWriteFactory..cctor()
----
The C++ module failed to load during appdomain initialization.
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
----
dwrite.dll
   at MS.Internal.NativeWPFDLLLoader.LoadDwrite()
   at CModuleInitialize.{ctor}(CModuleInitialize* , IntPtr cleaningUpFunc)
   at ?A0x8cc91adf.CreateCModuleInitialize()
   at ?A0x8cc91adf.??__E?A0x8cc91adf@cmiStartupRunner@@YMXXZ()
   at <CrtImplementationDetails>.LanguageSupport.InitializePerAppDomain(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
----
The specified module could not be found.
```

**Comment by danmosemsft** [comment]
I do not believe Windows Nano Server has support for DWrite. @SamBent ?

**Comment by danmosemsft** [comment]
@fabiant3 can you please transfer to WPF? I do not have rights to do so.

**Comment by danmosemsft** [comment]
@BentleyJamesSlater curious about your scenario here. Given Nano Server is headless, why are you instantiating fonts? I am not sure how much or any of WPF will work, but I am not on the WPF team and they should answer that.

**Comment by BentleyJamesSlater** [comment]
> @BentleyJamesSlater curious about your scenario here. Given Nano Server is headless, why are you instantiating fonts? I am not sure how much or any of WPF will work, but I am not on the WPF team and they should answer that.

Im trying to produce some graphical pdf reports. Our existing code base runs as a rest api on windows servers, which we are attempting to containerise. Im not sure its going to work out as we use wpf to produce a xps document, which is then converted into pdf. XPS support isnt looking good.

**Comment by danmosemsft** [comment]
I see. I wonder what alternatives there might be to generate PDF.

**Comment by jeffschwMSFT** [comment]
I manually ported this to https://github.com/dotnet/wpf/issues/3609
