### ISSUE TITLE
Mono.Linker.LinkerFatalErrorException: "Error processing method" at GetValueNodeFromGenericArgument

### ISSUE THREAD

**Issue by SergeySeleznyov** [dotnet/runtime#43222]
Hello,

Can't publish Blazor WebAssembly application with some specific code.

### Steps To Reproduce

0. Install .NET 5 RC1

1. Create some project:

``` 
dotnet new blazorwasm
```

2. Add some new *.cs file with following C# code:

```c#
using System.Text.Json;

namespace SomeNamespace
{
    public static class StaticClass
    {
        public static void GenericMethod<T>()
        {
            T[] value = null;
            JsonSerializer.Serialize(value);
        }
    }
}
```

3. Try to publish

```
dotnet publish
```

### Exception

```
Class.cs(8,9): error IL1005: SomeNamespace.StaticClass.GenericMethod<T>(): Error processing method 'SomeNamespace.StaticClass.GenericMethod<T>
()' in assembly 'TrimmingIssue.dll' [C:\projectsBlazor\Net5Publish\TrimmingIssue\TrimmingIssue.csproj]
  Mono.Linker.LinkerFatalErrorException: C:\projectsBlazor\Net5Publish\TrimmingIssue\Class.cs(8,9): error IL1005: SomeNamespace.StaticClass.GenericMethod<T>(): Error processing method 'S
omeNamespace.StaticClass.GenericMethod<T>()' in assembly 'TrimmingIssue.dll'
   ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.GetValueNodeFromGenericArgument(TypeReference genericArgument)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ProcessGenericArgumentDataFlow(GenericParameter genericParameter, TypeReference genericArgument, IMemberDefinition source)
     at Mono.Linker.Steps.MarkStep.MarkGenericArgumentConstructors(IGenericInstance instance, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.GetOriginalMethod(MethodReference method, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction, MethodDefinition method, Boolean& requiresReflectionMethodBodyScanner)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
```

### Further technical details

* .NET 5 RC1 is installed
* Project targets .NET 5
* Turning the trimming off for whole the app helps:  (dotnet publish -p:PublishTrimmed=False)
* Preservation for the assembly - does not help (\<linker> \<assembly fullname="..." preserve="all" /> \</linker>)

Please, feel free to ask for the details.
Thank you in advance for you help.

**Comment by mkArtakMSFT** [comment]
@eerhardt  FYI

**Comment by eerhardt** [comment]
@marek-safar @vitek-karas - I think this belongs in the mono/linker repo, but I don't have permissions to transfer it.

This may be related to https://github.com/mono/linker/issues/1500 - it is the same exception, but a different set of repro steps.

**Comment by eerhardt** [comment]
FYI - this also repros on a recent RC2 build:

```
❯ F:\dotnet\dotnet.exe --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20475.3
 Commit:    eef7d08fa2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\dotnet\sdk\5.0.100-rc.2.20475.3\

Host (useful for support):
  Version: 5.0.0-rc.2.20474.8
  Commit:  e9ac240eaa

.NET SDKs installed:
  5.0.100-rc.2.20475.3 [F:\dotnet\sdk]
```

**Comment by vitek-karas** [comment]
I can confirm that this a real bug in the linker. Since I didn't find a way to move the issue I filed a copy in https://github.com/mono/linker/issues/1559.

There's no simple workaround for the bug, but there are several ways to get the desired results. In this specific case a good way how to do the same and avoid the bug would be:
```C#
        public static void GenericMethod<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.PublicFields)] T>()
        {
            T[] value = null;
            JsonSerializer.Serialize(value, typeof(T[]));
        }
```

This will generate a trim analysis warning in the linker (Which is by default suppressed, but it can be suppressed in this method specifically as the method will work correctly).

It uses the `Serialize(object, Type)` overload. Linker still doesn't do the right thing with the `typeof(T[])`, but it doesn't crash in that case (it just generates the warning mentioned above).

Adding the annotation on the generic parameter of the method effectively propagates the requirements one frame above and so the end-to-end behavior will be the same as if the bug is fixed.
With this the behavior of `GenericMethod<MyType>` will be the same as calling `JsonSerializer.Serialize<MyType[]>(value)` directly.

**Comment by marek-safar** [comment]
Moved to mono/linker#1559
