### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Http2_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43293]
failed in job: [runtime-libraries-coreclr outerloop 20201011.1](https://dev.azure.com/dnceng/public/_build/results?buildId=848350&view=ms.vss-test-web.build-test-results-tab&runId=27028936&resultId=102943&paneView=debug)

failed tests:
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Http2_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

net6.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

Error message
~~~
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : The read operation failed, see inner exception.
-------- System.Net.Http.WinHttpException : Error -2147467260 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Operation aborted'.

Stack trace
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 203
   at System.Net.Http.Functional.Tests.HttpClientHandler_Decompression_Test.GetAsync_SetAutomaticDecompression_ContentDecompressed(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:line 216
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs:line 126
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 199
----- Inner Stack Trace -----
~~~

**Comment by ManickaP** [comment]
This is only WinHttpHandler. Probably related to https://github.com/dotnet/runtime/pull/42717
