### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43292]
failed in job: [runtime-libraries-coreclr outerloop 20201011.1](https://dev.azure.com/dnceng/public/_build/results?buildId=848350&view=ms.vss-test-web.build-test-results-tab&runId=27028932&resultId=102195&paneView=debug)

net6.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

Error message
~~~
System.IO.InvalidDataException : The archive entry was compressed using an unsupported compression method.

Stack trace
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 301
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 267
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 122
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 92
   at System.IO.Compression.DeflateStream.CopyToStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 995
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs:line 150
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync() in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 931
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 199
   at System.Net.Http.Functional.Tests.HttpClientHandler_Decompression_Test.GetAsync_SetAutomaticDecompression_ContentDecompressed(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:line 216
--- End of stack trace from previous location ---
~~~

**Comment by ManickaP** [comment]
This is only WinHttpHandler. Probably related to #42717
Similar to #43293
