### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_ResponseStreamTest.GetAsync_UseResponseHeadersReadAndCopyToMemoryStream_Success(remoteServer: (BaseUri: https://corefx-net-http2.azurewebsites.net/, HttpVersion: 2.0))

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43388]
failed in job: [runtime-libraries-coreclr outerloop 20201013.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=850450&view=ms.vss-test-web.build-test-results-tab&runId=27103034&paneView=debug&resultId=103122)

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open

Error message
~~~
System.Net.Http.HttpRequestException : Operation timed out (corefx-net-http2.azurewebsites.net:443)
---- System.Net.Sockets.SocketException : Operation timed out


Stack trace
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 57
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1283
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 604
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 859
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, Int64 timeoutTime, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 547
   at System.Net.Http.Functional.Tests.ResponseStreamTest.GetAsync_UseResponseHeadersReadAndCopyToMemoryStream_Success(RemoteServer remoteServer) in /_/src/libraries/Common/tests/System/Net/Http/ResponseStreamTest.cs:line 152
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 917
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 902
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|282_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 119
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1300
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 57
~~~

**Comment by karelz** [comment]
Triage: Azure hosted endpoint -- we need to find out if it is one off or regular? @CarnaViire can you please look at history? (once per week is our current threshold)

**Comment by CarnaViire** [comment]
The test has only failed once in the last 36 days -- on 13-10-2020. Seems like a one off. Closing.
