### ISSUE TITLE
Asp.Net 5.0 RC1 Blazor - Assemblies loaded via AssemblyLoadContext.Default.LoadFromStream corrupt over time

### ISSUE THREAD

**Issue by allderidge** [dotnet/runtime#43402]
## Description
In Asp.Net 5.0 RC1 WASM Blazor when an assembly is loaded via AssemblyLoadContext.Default.LoadFromStream it appears to corrupt over time resulting in various issues in reflection and directly accessing methods.

One form of Assembly corruption is reproduced in https://github.com/allderidge/BlazorBugReport_AssemblyCorruption . Additional stack traces have been included from the project where this issue was found.

The following steps caused the original issue:

- The application loads assemblies from its server via AssemblyLoadContext.Default.LoadFromStream
- DataContractSerialization involving the loaded assemblies is performed
- The application continues to initialise
- Various issues are triggered. Different issues are found by changing code that 'exercises' types found in the loaded assemblies either by construction, reflection or deserialisation.
- All code that generates the issue can be made to succeed dependent on ordering.

### Example Stack 1
```
Uncaught (in promise) Error: System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
   is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at System.Reflection.AssemblyName.FillName(MonoAssemblyName* native, String codeBase, Boolean addVersion, Boolean addPublickey, Boolean defaultToken)
   at System.Reflection.AssemblyName.Create(IntPtr monoAssembly, String codeBase)
   at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
   at System.Reflection.Assembly.GetName()
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.AssemblyKey..ctor(Assembly assembly)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.<>c__DisplayClass12_0.<GetRequiredLoadedAssembly>b__0(Assembly a)
   at System.Linq.Enumerable.TryGetLast[Assembly](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.LastOrDefault[Assembly](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.GetRequiredLoadedAssembly(AssemblyKey assemblyKey)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ScanAssemblyForCallableMethods(AssemblyKey assemblyKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.JSInterop.Infrastructure.DotNetDispatcher.AssemblyKey, Microsoft.JSInterop, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Collections.Generic.IReadOnlyDictionary`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`2[[System.Reflection.MethodInfo, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Type[], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(AssemblyKey key, Func`2 valueFactory)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.GetCachedMethodInfo(AssemblyKey assemblyKey, String methodIdentifier)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1)
    at Object.invokeJSFromDotNet (blazor.webassembly.js:1)
    at Object.w [as invokeJSFromDotNet] (blazor.webassembly.js:1)
    at _mono_wasm_invoke_js_blazor (dotnet.5.0.0-rc.1.20451.14.js:1)
    at do_icall (<anonymous>:wasm-function[10583]:0x1944fd)
    at do_icall_wrapper (<anonymous>:wasm-function[3296]:0x79894)
    at interp_exec_method (<anonymous>:wasm-function[2147]:0x4442c)
    at interp_runtime_invoke (<anonymous>:wasm-function[7851]:0x12e8ab)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7334]:0x11
```

The same exception is found in other code that calls Assembly.GetName().

### Example Stack 2
```
System.BadImageFormatException: Invalid method header local vars signature token 0x  d4400f
	 File name: '_____ name removed ________'
	    at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
	    at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
	    at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
	    at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
	    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
	    at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
	    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
	    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName)
	    at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
```

### Example 4
```
System.BadImageFormatException: Method has zero rva
    at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
    at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
    at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
    at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
    at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
    at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
    at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName)
    at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)```
```
### Example 5
```
System.TypeLoadException: Could not resolve type with token 01000024 from typeref (expected class '__removed__' in assembly '__removed__, Version=1.0.0.0, Culture=neutral, PublicKeyToken=__removed__')
```

### Further technical details
- ASP.NET Core version: `5.0.0-rc.1.20451.17`
- Include the output of `dotnet --info`

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-011223 [C:\Program Files\dotnet\sdk]
  3.1.103 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19216-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27615-11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27613-28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
`Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 3.0`

### Regression?
The previous code base on Blazor 3.1 didn't have these issues although it used Assassin.Load instead.

**Comment by lewing** [comment]
This looks like preview8 not rc1?  Can you reproduce the issue with rc2?

**Comment by allderidge** [comment]
Sorry, I had the wrong terminal window to get the dotnet --info, I've updated it to have the correct machines output. The packages installed in the project are all 5.0.0-rc.1.20451.17. I'll give RC2 a go tomorrow.

**Comment by allderidge** [comment]
The same issue exists with RC2.

The version information is now:

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

and the package versions are set to 5.0.0-rc.2.20475.17

**Comment by allderidge** [comment]
After some more investigation it appears that the main trigger for the stack traces given is using a DataContractSerializer.

The code in the repo https://github.com/allderidge/BlazorBugReport_AssemblyCorruption shows how deserialisation alters the name of the Assembly.

I think the DataContractSerializer code in this are is being changed as part of a fix for #42824 although I would expect a loaded Assembly name to be immutable suggesting that code in DataContractSerializer is triggering the issue. In addition, other stack traces appear to show the actual IDL being altered.

**Comment by lambdageek** [comment]
We think the problem is that the runtime is keeping a pointer to `arrAssembly` (https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.cs#L364) after the call to `InternalLoad` returns without pinning the array.  So it gets collected by the GC and the runtime ends up pointing at junk.  The call to `mono_image_open_from_data_internal` in `mono_alc_load_raw_bytes` is passing `FALSE` for `need_copy` so it ends up storing a pointer to the array data.

**Comment by CoffeeFlux** [comment]
https://github.com/dotnet/runtime/pull/43536 came out of this investigation, and I'm attempting a fix with the issue Aleksey discussed above. This isn't something that easily reduces to a test case, and instead I need to get a custom Blazor build with the runtime fix and verify it manually. If successful, I'll open the PR and backport.

**Comment by allderidge** [comment]
@CoffeeFlux I've just upgraded the example to the release of dotnet core 5.0 and the issue can still be reproduced. Looking at the PR's there should have been a fix that went out with the release: [#43593](https://github.com/dotnet/runtime/pull/43593).

The upgraded example is at [github.com/allderidge/BlazorBugReport_AssemblyCorruption/tree/dotnet5.0](https://github.com/allderidge/BlazorBugReport_AssemblyCorruption/tree/dotnet5.0 )

**Comment by CoffeeFlux** [comment]
Huh, that's very strange. We ended up creating a more minimal example for that issue and validated this fix worked for both it and your sample, so I'm not sure what's going on. Will look at it Monday, sorry for the trouble.

**Comment by CoffeeFlux** [comment]
I can reproduce this with your example on .NET 5.

This repo was the minimal example we found your test reduced to, and is indeed still fixed in .NET 5, so there appear to be multiple issues here: https://github.com/lambdageek/repro-gh-43402

I'm surprised because I remember manually testing your case with a patched dotnet and having it work. I wonder if I tested with #43536 as well and we should have backported that too... I'll try that locally, and if it still fails dig in to see what else changed.

**Comment by JohnathanValentine** [comment]
I am having a similar problem. I am doing WebAPI on .net5 (upgraded from netcoreapp3.1 where it was working splendidly). 
When I run swagger in visual studio (F5 debug) and login with my bearer token then execute my request everything works fine. When I deploy out to my docker container running the "mcr.microsoft.com/dotnet/aspnet:5.0.0-alpine3.12-amd64" and my running docker container dotnet info:

/app # dotnet --info

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
/app # 

My containerized api/swagger error message:

System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'culture')
1033 (0x0409) is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(Int32 culture)
   at System.Globalization.CompareInfo.GetCompareInfo(Int32 culture)
   at System.Data.ProviderBase.FieldNameLookup.GetCompareInfo()
   at System.Data.ProviderBase.BasicFieldNameLookup.LinearIndexOf(String fieldName, CompareOptions compareOptions)
   at System.Data.ProviderBase.BasicFieldNameLookup.IndexOf(String fieldName)
   at System.Data.ProviderBase.BasicFieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at CorpApps.Models.Data.LoginLogRepository.CreateFrom(SqlDataReader e) in /src/Assemblies/CorpApps.Models.Data/LoginLogRepository.cs:line 100
   at CorpApps.Models.Data.LoginLogRepository.GetLatestActiveByUser(Int32 userId) in /src/Assemblies/CorpApps.Models.Data/LoginLogRepository.cs:line 83
   at CorpApps.Models.Facades.AuthorizationFacade.AuditLogout(Int32 userId, DateTime logoutDate) in /src/Assemblies/CorpApps.Models/Facades/AuthorizationFacade.cs:line 78
   at CorpApps.Models.Facades.AuthorizationFacade.AuditLogout(Int32 userId) in /src/Assemblies/CorpApps.Models/Facades/AuthorizationFacade.cs:line 56
   at CorpApps.Models.Facades.AuthorizationFacade.AuditLogin(LoginLog log) in /src/Assemblies/CorpApps.Models/Facades/AuthorizationFacade.cs:line 40
   at CorpApps.Web.Svc.AuthorizationHandler.HandleRequirementAsync(AuthorizationHandlerContext context, AuthorizationPolicy requirement) in /src/Executables/CorpApps.Web.Svc/AuthorizationPoilicy.cs:line 128
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthorizeAsync(AuthorizationPolicy policy, AuthenticateResult authenticationResult, HttpContext context, Object resource)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer (token removed for brevity)
Host: localhost:8082
Referer: http://localhost:8082/swagger/index.html
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty

I understand it is not the same but perhaps my error will help narrow down the issue.

**Comment by CoffeeFlux** [comment]
It seems like the bug was properly fixed in the build tree, but the dotnet.wasm shipping with the .NET 5 release is out of date. It has the old version of the icall:
```
       (call $mono_image_open_from_data_internal
       (local.get $0)
       (local.get $1)
       (local.get $2)
       (i32.const 0)
       (i32.const 0)
       (i32.const 0)
       (i32.const 0)
       (i32.const 0)
```

Following to discover the cause of the packaging problem.

**Comment by lewing** [comment]
The fix for this didn't make it into 5.0.0 but is in release/5.0 and should be part of the next 5.0.x servicing release.

However the 5.0.2xx installer is pointing at 5.0.0 runtimes after https://github.com/dotnet/installer/pull/9185  so it is difficult to verify
cc @mmitche

**Comment by mmitche** [comment]
> The fix for this didn't make it into 5.0.0 but is in release/5.0 and should be part of the next 5.0.x servicing release.
> 
> However the 5.0.2xx installer is pointing at a 5.0.0 sdk and runtime after [dotnet/installer#9185](https://github.com/dotnet/installer/pull/9185) so it is difficult to verify
> cc @mmitche

The 5.0.2xx installer is shipping a 5.0.0 runtime because it's in preview, not the 5.0.1 runtime.

/cc @marcpopMSFT

**Comment by lambdageek** [comment]
Verified that the 5.0.1 runtime from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=5.0.101-servicing.20601.5&package=Microsoft.NETCore.App.Runtime.browser-wasm&version=5.0.1&protocolType=NuGet from the upcoming servicing release does not have the LoadFromStream corruption.  


Also checked that in 5.0.1, `dotnet.wasm`, the function`$mono_alc_load_raw_bytes` has the expected

``` 
(call $mono_image_open_from_data_internal
       (local.get $0)
       (local.get $1)
       (local.get $2)
       (i32.const 1) ;; TRUE
       (i32.const 0)
       (i32.const 0)
       (i32.const 0)
       (i32.const 0) 
```

**Comment by marcpopMSFT** [comment]
To confirm what Matt says above, the SDK previews don't always ship on the same schedule as the servicing releases of the runtime.  To avoid trying to keep them in sync with different schedules, we typically don't update the runtime included in preview SDKs until the GA release of that SDK. The exception is when both the SDK and runtime are in preview (ie 6.0.1xx previews will include matching 6.0 previews).

**Comment by CoffeeFlux** [comment]
I think we can close this issue given that it's fixed for 5.0.1.

However, I'm still curious how we didn't end up standardizing the runtime version across all components we ship that consume it before release. That seems like a procedural problem—having inconsistent runtime versions in the release seems like it could lead to all sorts of unintended problems, even beyond issues like this one.

**Comment by SamMonoRT** [comment]
December 5.0.1 servicing release shipped today. We can close this issue.  Please re-open if this still reproes with 5.0.1

**Comment by allderidge** [comment]
I've retested on 5.0.1 and my issue in the original application is fixed thanks.

**Comment by lewing** [comment]
If anyone else is validating 5.0.1 please make sure to remove 6.x first due to https://github.com/dotnet/installer/pull/9208
