### ISSUE TITLE
Test SslStream_StreamToStream_Authentication_IncorrectServerName_Fail failed in CI

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#43412]
Seen on PR: https://github.com/dotnet/runtime/pull/43379/checks?check_run_id=1255364179
Direct link to results: https://helix.dot.net/api/2019-06-17/jobs/e36bdcf1-3066-4c9e-9b92-05f309f27595/workitems/System.Net.Security.Tests/console

Failure is blocking clean CI on that PR.

```txt
    System.Net.Security.Tests.SslStreamStreamToStreamTest_SyncParameters.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : Error desconocido al procesar el certificado.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(393,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(98,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : Error desconocido al procesar el certificado.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(393,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(98,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
```

**Comment by stephentoub** [comment]
@wfurt, this is the same error I saw locally (only saw it once) after sync'ing https://github.com/dotnet/runtime/commit/51f6b8bd3a2a38c432b1cd1f7c465c256f5f699c.

**Comment by wfurt** [comment]
ok. I'm trying to reproduce.

**Comment by wfurt** [comment]
Got repro on 20H2 19042.572. It works fine one my other Windows machine. Looking into it right now.

**Comment by stephentoub** [comment]
Closing as the offending PR was reverted.  If this re-appears with new runs as of now, please re-open.
