### ISSUE TITLE
Test failure: System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43437]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=853733&view=ms.vss-test-web.build-test-results-tab&runId=27266556&resultId=167135&paneView=debug

failed tests:
System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail
System.Net.Security.Tests.SslStreamStreamToStreamTest_MemoryAsync.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail
System.Net.Security.Tests.SslStreamStreamToStreamTest_SyncSslOptions.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail

Error message
~~~
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- System.ComponentModel.Win32Exception : An unknown error occurred while processing the certificate.

Stack trace
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 393
   at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs:line 98
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
~~~

**Comment by stephentoub** [comment]
Dup of #43412
