### ISSUE TITLE
CG2 Outerloop Test Failure: TypeGeneratorTests throwing System.BadImageFormatException

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#43466]
Example run:
https://dev.azure.com/dnceng/public/_build/results?buildId=853947&view=ms.vss-test-web.build-test-results-tab&runId=27279090&resultId=102633&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Tests failing:
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest612\\Generated612\\Generated612.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest613\\Generated613\\Generated613.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest614\\Generated614\\Generated614.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest681\\Generated681\\Generated681.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest682\\Generated682\\Generated682.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest683\\Generated683\\Generated683.cmd

Platform:
Win10 (x64, arm64)

Item log:
<pre>
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B (COR_E_BADIMAGEFORMAT))
         at Framework.M.G2_C221.T.T[T0,T1,W](W inst, String exp)
         at Framework.ConstrainedCallsTest()
         at Framework.Main()
      
      Return code:      1
      Raw output file:      C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\Generated682.output.txt
      Raw output:
      BEGIN EXECUTION
      Generated682.dll
      TestFramework.dll
              2 file(s) copied.
      Response file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\\composite-r2r.dll.rsp
      C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\IL\*.dll
      -o:C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\\composite-r2r.dll
      --targetarch:x64
      --verify-type-and-field-layout
      -O
      -r:C:\h\w\B90C0986\p\System.*.dll
      -r:C:\h\w\B90C0986\p\Microsoft.*.dll
      -r:C:\h\w\B90C0986\p\mscorlib.dll
      -r:C:\h\w\B90C0986\p\netstandard.dll
      " "dotnet" "C:\h\w\B90C0986\p\crossgen2\crossgen2.dll" @"C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\\composite-r2r.dll.rsp"   --composite"
      Emitting R2R PE file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\composite-r2r.dll
      Emitting R2R PE file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\Generated682.dll
      Emitting R2R PE file: C:\h\w\B90C0986\w\BD420A43\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest682\Generated682\TestFramework.dll
       "C:\h\w\B90C0986\p\corerun.exe" Generated682.dll 
      ========================== Method Calling Test ==========================
[Snip...]
</pre>

**Comment by nattress** [comment]
Prior attempt at fixing and discussion: https://github.com/dotnet/runtime/pull/38366
