### ISSUE TITLE
ILVerify crashes when sees FunctionPointerType

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#43502]
Running ilverify tool on SPC crashes with following exception

```
Verifying [System.Private.CoreLib]System.Globalization.CalendarData.EnumCalendarInfo
Error: System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.FunctionPointerType' to type 'Internal.TypeSystem.Ecma.EcmaType'.
   at ILVerify.AccessVerificationHelpers.CanAccess(TypeDesc currentClass, TypeDesc targetClass)
   at ILVerify.AccessVerificationHelpers.CanAccessMethodSignature(TypeDesc currentType, MethodDesc targetMethod)
   at Internal.IL.ILImporter.ImportCall(ILOpcode opcode, Int32 token)
   at Internal.IL.ILImporter.ImportBasicBlock(BasicBlock basicBlock)
   at Internal.IL.ILImporter.ImportBasicBlocks()
   at ILVerify.Verifier.VerifyMethod(EcmaModule module, MethodIL methodIL, MethodDefinitionHandle methodHandle)
   at ILVerify.Verifier.VerifyMethods(EcmaModule module, IEnumerable`1 methodHandles)+MoveNext()
   at ILVerify.Verifier.Verify(PEReader peReader, MethodDefinitionHandle methodHandle)+MoveNext()
   at ILVerify.Program.VerifyMethods(PEReader peReader, EcmaModule module, String path, Int32& numErrors, Int32& verifiedMethodCounter, Int32& methodCounter)
   at ILVerify.Program.VerifyAssembly(PEReader peReader, EcmaModule module, String path)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
```

**Comment by PZegar** [comment]
Hi, any chance to get assigned to the issue? I can see its up-for-grabs but I'm new here and I can't find clear description as for how to get the existing issue assigned to me.

**Comment by jkotas** [comment]
@PZegar I have assigned this issue to you. Thank you!

**Comment by PZegar** [comment]
Hi @marek-safar would you mind specifying the command line arguments you've called the ILverify with to get this exception? I expect _-r:%WINDIR%\Microsoft.NET\Framework\v4.0.30319\*.dll_ but which dll exactly have you been verifying?

**Comment by marek-safar** [comment]
>  I assume it was something like:

@PZegar yep, that's correct

**Comment by JulieLeeMSFT** [comment]
Moving to future since ILVerify is preview feature.

@PZegar, are you still interested in working on this issue?
