### ISSUE TITLE
OutOfMemoryException when sending payload to helix machine

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#43513]
Ran into the following issue when working on https://github.com/dotnet/runtime/pull/42683

```
##[error].packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20506.7/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(47,5): error : (NETCORE_ENGINEERING_TELEMETRY=Helix) OutOfMemoryException: Array dimensions exceeded supported range.   
 at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader()
   at System.IO.Compression.ZipArchive.WriteFile()
   at System.IO.Compression.ZipArchive.Dispose(Boolean disposing)
   at Microsoft.DotNet.Helix.Client.DirectoryPayload.DoUploadAsync(IBlobContainer payloadContainer, Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs:line 67
   at Microsoft.DotNet.Helix.Client.Helpers.MutexExec[T](Func`1 f, String mutexName) in /_/src/Microsoft.DotNet.Helix/JobSender/Helpers.cs:line 49
   at Microsoft.DotNet.Helix.Client.DirectoryPayload.UploadAsync(IBlobContainer payloadContainer, Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs:line 32
   at Microsoft.DotNet.Helix.Client.JobDefinition.<>c__DisplayClass74_0.<<SendAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 160
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 159
   at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 220
   at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 51
```

**Comment by akoeplinger** [comment]
We figured out that because we're trying to send the whole Core_Root folder (https://github.com/dotnet/runtime/blob/722b8a660e7e0c59419196be102784244883ff08/src/tests/Common/helixpublishwitharcade.proj#L294) which contains all the intermediate Android project build artifacts we were trying to .zip about ~9GB of files, instead of just the .apks.

**Comment by fanyang-mono** [comment]
This issue has been resolved.
