### ISSUE TITLE
System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43548]
Consistently failing test in this PR, my changes are unrelated to that test: https://github.com/dotnet/runtime/pull/43134

```
    System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : Error desconocido al procesar el certificado.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(393,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(98,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        
    System.Net.Security.Tests.SslStreamStreamToStreamTest_MemoryAsync.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : Error desconocido al procesar el certificado.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(393,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(98,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_IncorrectServerName_Fail()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
```

Translation of the exception message:
> Error desconocido al procesar el certificado.
> Unknown error when processing the certificate.

Here you can find the failing legs: https://dev.azure.com/dnceng/public/_build/results?buildId=853192&view=logs&j=a5b2e583-5664-59cd-4302-08f0f52b6a51&t=af414fd7-fec7-5b4b-b481-ec604ebbdc07

Example of output: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43134-merge-7b10ec0bc98b476eb2/System.Net.Security.Tests/console.5da1523b.log?sv=2019-07-07&se=2020-11-04T16%3A01%3A23Z&sr=c&sp=rl&sig=Esmwm%2BvAnmVOpm9pShj22o2RfhF7IsQ%2FQ2MxxOiZ1iw%3D

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/43412.
