### ISSUE TITLE
Test failure: System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: \"\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43574]
failed in job: [ runtime-libraries-coreclr outerloop 20201018.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=857769&view=ms.vss-test-web.build-test-results-tab&runId=27454150&resultId=102052&paneView=debug)

net6.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

Error message
~~~
System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.


Stack trace
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 917
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 883
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 959
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 454
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 356
   at System.Net.Security.Tests.CertificateValidationRemoteServer.EndToEndHelper(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 105
   at System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 84
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
~~~

**Comment by wfurt** [comment]
no failures in last 90 days. This is likely network or infrastructure issue.
