### ISSUE TITLE
ThreadPoolCanPickUpOneOrMoreWorkItemsWhenThreadIsAvailable test failure on Android

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#43754]
```
Assert.True() Failure\nExpected: True\nActual:   False

Stack trace
   at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 153
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolCanPickUpOneOrMoreWorkItemsWhenThreadIsAvailable() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 608
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by jkotas** [comment]
Failed in https://github.com/dotnet/runtime/pull/43744

**Comment by akoeplinger** [comment]
The test was disabled in master with https://github.com/dotnet/runtime/pull/43755 so removing `blocking-clean-ci`.

**Comment by mdh1418** [comment]
Though System.Threading.ThreadPool.Tests crashes on CI in https://github.com/dotnet/runtime/pull/50095,
This test passes on a local run on Android x64.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0
