### ISSUE TITLE
Test failure: System.Drawing.Tests.IconTests.Save_OutputStream_Success(fileName: \"96x96_one_entry_8bit.ico\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43817]
failed in job: [runtime-coreclr libraries-jitstressregs 20201025.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=865277&view=ms.vss-test-web.build-test-results-tab&runId=27709676&resultId=123805&paneView=debug)

net6.0-Linux-Release-arm-CoreCLR_checked-jitstressregs8-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

Error message
~~~
System.ArgumentException : Parameter is not valid.


Stack trace
   at System.Drawing.Image.get_RawFormat() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Image.cs:line 283
   at System.Drawing.Graphics.IgnoreMetafileErrors(Image image, Int32& errorStatus) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs:line 2451
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs:line 1655
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 106
   at System.Drawing.Icon.ToBitmap() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:line 645
   at System.Drawing.Tests.IconTests.SaveAndCompare(Icon icon, Boolean alpha) in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 788
   at System.Drawing.Tests.IconTests.Save_OutputStream_Success(String fileName) in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 464
~~~

**Comment by safern** [comment]
Seems related to: https://github.com/dotnet/runtime/issues/30184
