### ISSUE TITLE
System.Text.Tests.EncodingTest failure, index out of bounds: Browser wasm Release AllSubsets_Mono

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43874]
Possible this is a VM issue, but I've put it in the area of the test suite for now.

Run: https://dev.azure.com/dnceng/public/_build/results?buildId=866154&view=logs&jobId=c693b1a1-52cc-5241-304f-e4b4c2d5f73e&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=09a92b4c-3493-52a9-1172-0680b62c9e30
Failure: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43830-merge-cf1be1de3b70483c8f/System.Text.Encoding.CodePages.Tests/console.8dda7c04.log?sv=2019-07-07&se=2020-11-15T19%3A00%3A14Z&sr=c&sp=rl&sig=QTtwlfO%2BYfoSOrKbIbOjzDQtIg%2Bym04ckJemNquHEEo%3D

```
[19:09:09] info: Arguments: --run,WasmTestRunner.dll,System.Text.Encoding.CodePages.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[19:09:10] info: console.debug: MONO_WASM: Initializing mono runtime
[19:09:10] info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[19:09:10] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[19:09:10] info: Initializing.....
[19:09:10] info: Discovering: System.Text.Encoding.CodePages.Tests.dll (method display = ClassAndMethod, method display options = None)
[19:09:10] info: Discovered:  System.Text.Encoding.CodePages.Tests.dll (found 9 of 9 test cases)
[19:09:10] info: Starting:    System.Text.Encoding.CodePages.Tests.dll
[19:09:11] fail: [FAIL] System.Text.Tests.EncodingTest.TestCodepageEncoding(codePage: 51932, webName: "euc-jp", queryString: "cseucpkdfmtjapanese")
[19:09:11] info: System.IndexOutOfRangeException : The specified index is out of bounds of the specified array.
[19:09:11] info:    at System.Array.GetValue(Int32 index)
[19:09:11] info:    at System.SZArrayEnumerator.get_Current()
[19:09:11] info:    at System.Text.Tests.EncodingTest.TestCodepageEncoding(Int32 codePage, String webName, String queryString)
[19:09:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[19:09:12] info: Finished:    System.Text.Encoding.CodePages.Tests.dll
[19:09:12] info: 
[19:09:12] info: === TEST EXECUTION SUMMARY ===
[19:09:12] info: Total: 1111, Errors: 0, Failed: 1, Skipped: 3, Time: 2.433778s
[19:09:12] info: 
[19:09:13] info: 19:09:13.0592360 Process exited with 1
```

**Comment by BrzVlad** [comment]
Is this flaky or not ? What's the failing frequency ?

**Comment by steveisok** [comment]
114 individual failures on OSX track back to this PR https://github.com/dotnet/runtime/pull/43360 and occurred between 14-10 and 16-10.  

There is only one other instance of this failure and that's what Ryan linked.

**Comment by CoffeeFlux** [comment]
Interesting. We can probably remove the blocking clean ci label if it's that rare, though if this is an interpreter bug it's possible this could manifest in a variety of test suites infrequently. I'll keep an eye out for it.

**Comment by lewing** [comment]
Has this happened again?

**Comment by steveisok** [comment]
Does not look like it.

**Comment by lewing** [comment]
Let's close it and reopen if it shows up again.
