### ISSUE TITLE
APK deletion/installation failure: Android arm64 Release AllSubsets_Mono

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43873]
No idea what's going on here. Hit in https://github.com/dotnet/runtime/pull/43830

Run: https://dev.azure.com/dnceng/public/_build/results?buildId=866154&view=logs&jobId=c693b1a1-52cc-5241-304f-e4b4c2d5f73e&j=c693b1a1-52cc-5241-304f-e4b4c2d5f73e&t=a77d25d8-4b4f-56e7-c08d-3b2f312eb992
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43830-merge-7da23700df3f4c9f92/Microsoft.Extensions.FileProviders.Physical.Tests/console.9fd71ad1.log?sv=2019-07-07&se=2020-11-15T19%3A21%3A11Z&sr=c&sp=rl&sig=iOy%2FuUYCfr0m7vtjUpCrJaq1nsgpjx4DBdSciSmBFeA%3D

```
[12:21:31] info: Attempting to remove apk 'net.dot.Microsoft.Extensions.FileProviders.Physical.Tests': 
[12:21:31] dbug: Executing command: 'C:\h\w\AEE309D3\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.20519.2\runtimes\any\native\adb\windows\adb.exe -s 014AY1RQVS uninstall net.dot.Microsoft.Extensions.FileProviders.Physical.Tests'
[12:21:32] info: APK 'net.dot.Microsoft.Extensions.FileProviders.Physical.Tests' not on device.
[12:21:32] info: Attempting to install C:\h\w\AEE309D3\w\A3100949\e\Microsoft.Extensions.FileProviders.Physical.Tests.apk: 
[12:21:32] dbug: Executing command: 'C:\h\w\AEE309D3\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.20519.2\runtimes\any\native\adb\windows\adb.exe -s 014AY1RQVS install "C:\h\w\AEE309D3\w\A3100949\e\Microsoft.Extensions.FileProviders.Physical.Tests.apk"'
[12:26:33] fail: Waiting for command timed out: execution may be compromised.
[12:26:33] crit: Failure to run test package: Process must exit before requested information can be determined.
                 System.InvalidOperationException: Process must exit before requested information can be determined.
                    at System.Diagnostics.Process.EnsureState(State state)
                    at System.Diagnostics.Process.get_ExitCode()
                    at Microsoft.DotNet.XHarness.Android.Execution.AdbProcessManager.Run(String adbExePath, String arguments, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs:line 88
                    at Microsoft.DotNet.XHarness.Android.AdbRunner.RunAdbCommand(String command, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 441
                    at Microsoft.DotNet.XHarness.Android.AdbRunner.RunAdbCommand(String command) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 432
                    at Microsoft.DotNet.XHarness.Android.AdbRunner.InstallApk(String apkPath) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 159
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 109
XHarness exit code: 1001
```

**Comment by MattGal** [comment]
Yeah I've seen this a few times, it handles timeout in apk install badly.  I can make it up the timeout and not check the exit code of the timed out process but I wonder if the APK in question actually had issues.

**Comment by safern** [comment]
Happened again in: https://dev.azure.com/dnceng/public/_build/results?buildId=882081&view=ms.vss-test-web.build-test-results-tab&runId=28226186&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=157562

**Comment by ViktorHofer** [comment]
Closing as there aren't any recent hits (at least not known to me).
