### ISSUE TITLE
[Regression] [Product bug] Test failure: System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed(useDnsEndPoint: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43931]
failed in job: [runtime-libraries-coreclr outerloop 20201027.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=867094&view=ms.vss-test-web.build-test-results-tab&runId=27760024&resultId=103500&paneView=debug)

net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Net.Sockets.Tests.TelemetryTest.VerifyStartStopEvents(ConcurrentQueue`1 events, Boolean connect, Int32 expectedCount) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 396
   at System.Net.Sockets.Tests.TelemetryTest.VerifyConnectFailureEvents(ConcurrentQueue`1 events) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 324
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 203
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0(System.String, System.String)

Child arguments:
  Apm, True
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201028.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=868604&view=ms.vss-test-web.build-test-results-tab&runId=27801276&resultId=103353&paneView=debug)

failed test: System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(connectMethod: \"Task\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Net.Sockets.Tests.TelemetryTest.VerifyStartStopEvents(ConcurrentQueue`1 events, Boolean connect, Int32 expectedCount) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 396
   at System.Net.Sockets.Tests.TelemetryTest.VerifyConnectFailureEvents(ConcurrentQueue`1 events) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 324
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_ConnectAsyncCanceled_LogsConnectFailed>b__12_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 316
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectAsyncCanceled_LogsConnectFailed>b__12_0(System.String, System.String)

Child arguments:
  Task, True
~~~

**Comment by karelz** [comment]
Triage: Likely a regression - started to fail more often after change in the area recently.

**Comment by MihaZupan** [comment]
[Kusto query I mentioned](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA62RUWvCMBDH3/0UR19UqE0tIip0sDEEB5NNC3uOzdHGtklJLhuFffildvgwhuxhEHK55O7/+5PL0NIBravJwugTzloqqKQSqVQKDbxpU+0IGwtaXZOd+K30SZ8uVT7uhH//KNEgbKWStkQBdykITkiywUkSJ/EsXs/iOcSbuF/TEXAlIOtahDSF4NhZD4r2SNFR5xWSjTLvtN9rbJBM16fB0DX47/vGWy7r8XCrNE0eDFd5CblWxKWyECyS+WoVTIEx+NaFqyK8HKAkau2GsUJS6U5RrhsmNCkkZpzqvbPW1TW7yNzELJPlT4wlkOrdB1lwkv6n/gzzYrdhi/U/whZrP73W6DPmBNcBhvDozEUqhGekUos+WssLDOFIPK8yw3N/vjeFa1CRDeHVocM9b3AewmD7C91hhn5vAgAA).

Initial failures on #43661

**Comment by stephentoub** [comment]
@MihaZupan, I've been unsuccessful in reproing this locally on either Windows or Ubuntu.  Were you able to repro it?

**Comment by wfurt** [comment]
I see only 9 (2 debug, 9 release) failures in last 10 day. Only one failure with Task, 7 failures with APM.

Aside from the one above I see two other variants:
```
Child exception:
  Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Exception)
Actual:   (No exception was thrown)
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass10_0.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 185
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 109
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 179
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0(System.String, System.String)

Child arguments:
  Sync, False

```
and 
```

Child exception:
  System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 385
   at System.Net.Dns.GetHostAddressesCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 369
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 556
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 506
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2359
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 275
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 300
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2321
--- End of stack trace from previous location ---
   at System.Net.Sockets.Tests.TelemetryTest.GetRemoteEndPointAsync(String useDnsEndPointString, Int32 port) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 70
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 173
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0(System.String, System.String)

Child arguments:
  Sync, False
```

**Comment by stephentoub** [comment]
Thanks. Yeah, I just ran 8000 iterations on both Windows and Linux over the course of a few hours and couldn't get it to happen.  Obviously it can, of course, or it wouldn't be happening sporadically in CI.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201122.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=895835&view=ms.vss-test-web.build-test-results-tab&runId=28629402&resultId=103291&paneView=debug)

failed test: System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed(connectMethod: \"Apm\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Net.Sockets.Tests.TelemetryTest.VerifyStartStopEvents(ConcurrentQueue`1 events, Boolean connect, Int32 expectedCount) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 396
   at System.Net.Sockets.Tests.TelemetryTest.VerifyConnectFailureEvents(ConcurrentQueue`1 events) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 324
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 203
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0(System.String, System.String)

Child arguments:
  Apm, True
~~~

**Comment by ManickaP** [comment]
It's still happening [kusto for the last 10 days](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA21QwU7DMAy98xVWTyBNHXxAOQBDGoJJ0Eocpyzx2qxtXDkJUImPx00mxIFLHD+/Zz+7QR/e0McheLj4hs8OGaGZJ4SqgqKefcCx3GEoa9I9Bl82IljeAUcMPC9pAcoZeMHQkUmyzQe6UFNkjfusuyfnUIdHZYfIuH+m1v+B0OQW2UhqscCFGDqRddBbZyordIZ34n4rnjyQ+0225h/mEx0SSWKq59XuWDndpRGMR7/uUBm/HpXsydnEa8SIBm5BtXR5c22uREtspONhPhcFmZhO4h42XxqnYMmt5ADeqxZXUAel+4aVlv9DZJXLWXqOOzUuxHQiUSrdWZfAHw9BzfqQAQAA) has 14 occurrences, including from yesterday (3.12.).

@MihaZupan could you give it another look please?

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201207.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=910472&view=ms.vss-test-web.build-test-results-tab&runId=29012618&resultId=103337&paneView=debug)

failed test: System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(connectMethod: \"Task\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Net.Sockets.Tests.TelemetryTest.VerifyStartStopEvents(ConcurrentQueue`1 events, Boolean connect, Int32 expectedCount) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 396
   at System.Net.Sockets.Tests.TelemetryTest.VerifyConnectFailureEvents(ConcurrentQueue`1 events) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 324
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_ConnectAsyncCanceled_LogsConnectFailed>b__12_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 316
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectAsyncCanceled_LogsConnectFailed>b__12_0(System.String, System.String)

Child arguments:
  Task, True
~~~

**Comment by MihaZupan** [comment]
Linking #43931 as caused by the same underlying issue.

**Comment by MihaZupan** [comment]
Note that this issue is tracking test failures for:
- `EventSource_SocketConnectFailure_LogsConnectFailed`
- `EventSource_ConnectAsyncCanceled_LogsConnectFailed`

**Comment by ManickaP** [comment]
@MihaZupan if there's another test reported under this issue feel free to extract it to its own issue and delete the comment. I've been doing that quite a bit lately.
Especially if we might disable the test.

**Comment by MihaZupan** [comment]
Test disabled by #46031.

**Comment by mateoatr** [comment]
The test failed again in [runtime-libraries-coreclr outerloop 20210707.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1223761&view=ms.vss-test-web.build-test-results-tab).

**Comment by antonfirsov** [comment]
Also failed in #56102:
https://dev.azure.com/dnceng/public/_build/results?buildId=1251070&view=ms.vss-test-web.build-test-results-tab

Only the Sync case seems to fail now.

**Comment by karelz** [comment]
Test failures 5/22-7/22 (incl. PRs):

Day | Run | OS
-- | -- | --
7/7 | Official run | 5x failed -- Debian.9.Arm32.Open, Centos.8.Amd64.Open, Ubuntu.1804.Amd64.Open, Windows.10.Amd64.Server19H1.Open, Windows.7.Amd64.Open
7/8 | Official run | 2x failed -- Alpine.312.Amd64.Open, Ubuntu.1804.ArmArch.Open
7/21 | PR #56102 | 3x failed -- RedHat.7.Amd64.Open, Fedora.32.Amd64.Open, Ubuntu.1604.Amd64.Open

@MihaZupan any ideas why there are these spikes in runs? Does the test depend on external server? Or is it sign that DNS was not working or something like that?

**Comment by MihaZupan** [comment]
This test tries connecting to `microsoft.com:12345`, expecting that to fail and throw. If `microsoft.com` actually started accepting connections on that port, we would start seeing this test failing across all argument variants.

The failure here is that `socket.Connect(EndPoint)` did not throw (while all other async variants apparently did).
@antonfirsov do you know of any recent-ish Socket changes that would affect sync connects?
