### ISSUE TITLE
Test failure: System.Buffers.Tests.ArrayBufferWriterTests_Byte.GetMemory_ExceedMaximumBufferSize

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43932]
failed in job: [ runtime-libraries-coreclr outerloop 20201027.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=867094&view=ms.vss-test-web.build-test-results-tab&runId=27760178&resultId=104647&paneView=debug)

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Array.Resize[T](T[]& array, Int32 newSize) in /_/src/libraries/System.Private.CoreLib/src/System/Array.cs:line 68
   at System.Buffers.ArrayBufferWriter`1.CheckAndResizeBuffer(Int32 sizeHint) in /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs:line 199
   at System.Buffers.ArrayBufferWriter`1.GetMemory(Int32 sizeHint) in /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs:line 133
   at System.Buffers.Tests.ArrayBufferWriterTests_Byte.GetMemory_ExceedMaximumBufferSize() in /_/src/libraries/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.Byte.cs:line 109
~~~

**Comment by danmosemsft** [comment]
@steveharter you changed the code and test recently - could it be the cause? 035b729d829368c2790d825bd02db14f0c0fd2ea

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201206.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=909967&view=ms.vss-test-web.build-test-results-tab&runId=29001806&resultId=104669&paneView=debug)

failed test: System.Buffers.Tests.ArrayBufferWriterTests_Byte.GetMemory_ExceedMaximumBufferSize

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504


Error message
~~~
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Array.Resize[T](T[]& array, Int32 newSize) in /_/src/libraries/System.Private.CoreLib/src/System/Array.cs:line 68
   at System.Buffers.ArrayBufferWriter`1.CheckAndResizeBuffer(Int32 sizeHint) in /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs:line 199
   at System.Buffers.ArrayBufferWriter`1.GetMemory(Int32 sizeHint) in /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs:line 133
   at System.Buffers.Tests.ArrayBufferWriterTests_Byte.GetMemory_ExceedMaximumBufferSize() in /_/src/libraries/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.Byte.cs:line 109
~~~

**Comment by steveharter** [comment]
The test assumes it can allocate ~4GB which apparently isn't always true.

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20210106.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=939900&view=ms.vss-test-web.build-test-results-tab&runId=29701614&resultId=104679&paneView=debug)

failed test: System.Buffers.Tests.ArrayBufferWriterTests_Byte.GetMemory_ExceedMaximumBufferSize

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open


Error message
~~~
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Array.Resize[T](T[]& array, Int32 newSize) in /_/src/libraries/System.Private.CoreLib/src/System/Array.cs:line 68
   at System.Buffers.ArrayBufferWriter`1.CheckAndResizeBuffer(Int32 sizeHint) in /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs:line 199
   at System.Buffers.ArrayBufferWriter`1.GetMemory(Int32 sizeHint) in /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs:line 133
   at System.Buffers.Tests.ArrayBufferWriterTests_Byte.GetMemory_ExceedMaximumBufferSize() in /_/src/libraries/System.Memory/tests/ArrayBufferWriter/ArrayBufferWriterTests.Byte.cs:line 109
~~~
