### ISSUE TITLE
[wasm-browser] unknown error: Chrome failed to start: exited abnormally. (chrome not reachable)

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#43955]
https://dev.azure.com/dnceng/public/_build/results?buildId=868621&view=logs&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=09a92b4c-3493-52a9-1172-0680b62c9e30

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43803-merge-48e510544eab4b8981/Microsoft.Extensions.DependencyModel.Tests/console.b31c959b.log?sv=2019-07-07&se=2020-11-17T12%3A40%3A20Z&sr=c&sp=rl&sig=hsagbbZGP1WmiA61t%2FZKutJ9xJt7ffIS82QRvSzuJbU%3D

```
Starting ChromeDriver 84.0.4147.0 (ff714bcb10c3356b1b1b2819148507a34fa4b1f8-refs/heads/master@{#768968}) on port 45939
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[12:41:07] crit: OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
                   (chrome not reachable)
                   (The process started from chrome location /home/helixbot/work/9FCD08EB/p/chrome-linux/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
                    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.GetChromeDriver() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 90
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 53
                    at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 120
XHarness exit code: 1001
XHarness artifacts: ./xharness-output
```

**Comment by directhex** [comment]
Tagging @radical

**Comment by lewing** [comment]
This happens from time to time when selenium is trying to start a chrome instance, it isn't clear when or why. 
 http://chromedriver.chromium.org/help/chrome-doesn-t-start suggests trying `--no-sandbox` as an option, that is probably worth trying.

**Comment by lewing** [comment]
To be clear I don't think this is a permissions problem at all, it looks like some sort of race at startup I'm grasping at the nearest straw while we look into it more.

**Comment by steveisok** [comment]
According to the Kusto magician, this has happened 21 times in the last month.  17 out of 21 times on PR's and 4 on master.

**Comment by akoeplinger** [comment]
This doesn't sound a lot fortunately, the total number of runs must be in the hundreds right?

**Comment by steveisok** [comment]
357 total runs.

**Comment by steveisok** [comment]
I messed up on the first count.  980 total runs.

**Comment by akoeplinger** [comment]
We made a fix in xharness (https://github.com/dotnet/xharness/pull/343) and haven't seen this issue since. Closing.
