### ISSUE TITLE
Issue while connection through proxy to Web socket on linux arm

### ISSUE THREAD

**Issue by Yuvaraja06** [dotnet/runtime#43988]
# Issue Title
While using Proxy for connecting to Web Socket. Its working fine on Windows but on linux there is exception.

# General
 **environment variable: libSystem.Net.Security.Native: cannot open shared object file: No such file or directory**

Unable to connect to the remote server
---> System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
---> System.ComponentModel.Win32Exception (0x80090020): Unable to load shared library 'System.Net.Security.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.Net.Security.Native: cannot open shared object file: No such file or directory
at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

**Comment by wfurt** [comment]
could be dup of #43656?  The messages are somewhat confusing @Yuvaraja06. You did not leave any information about what OS do you use or what version .NET. 

If you use shared .NET installation you can try to find libSystem.Net.Security.Native.so and run `ldd libSystem.Net.Security.Native.so`

**Comment by wfurt** [comment]
do you have any update @Yuvaraja06? It would be best to share repro with steps.

**Comment by karelz** [comment]
Triage: Not enough information to make it actionable without repro. Closing.
If you have a repro, we can reopen -- please let us know in such case. Thanks!
