### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Task\", useDnsEndPoint: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44015]
failed in job: [runtime-libraries-coreclr outerloop 20201028.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=868604&view=ms.vss-test-web.build-test-results-tab&runId=27801280&resultId=103476&paneView=debug)

failed tests:
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Task\", useDnsEndPoint: True)
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Apm\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1604.Amd64.Open
net6.0-Linux-Release-x64-CoreCLR_release-(Debian.10.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-bfcd90a-20200121150006

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.TimeoutException: Timed out waiting for ConnectStop
   at System.Net.Sockets.Tests.TelemetryTest.WaitForEventAsync(ConcurrentQueue`1 events, String name) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 412
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass9_0.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 151
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 109
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 142
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Task, True
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201105.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=876448&view=ms.vss-test-web.build-test-results-tab&runId=28043660&resultId=103877&paneView=debug)

failed tests:
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Eap\", useDnsEndPoint: True)
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Task\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.TimeoutException: Timed out waiting for ConnectStop
   at System.Net.Sockets.Tests.TelemetryTest.WaitForEventAsync(ConcurrentQueue`1 events, String name) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 412
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass9_0.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 151
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 109
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 142
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Eap, True
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201125.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=899602&view=ms.vss-test-web.build-test-results-tab&runId=28738060&resultId=103620&paneView=debug)

failed test: System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Task\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.TimeoutException: Timed out waiting for ConnectStop
   at System.Net.Sockets.Tests.TelemetryTest.WaitForEventAsync(ConcurrentQueue`1 events, String name) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 412
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass9_0.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 151
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 109
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 142
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Task, True
~~~

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201203.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=907184&view=ms.vss-test-web.build-test-results-tab&runId=28934448&resultId=103153&paneView=debug)

failed tests:
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed(connectMethod: \"Sync\", useDnsEndPoint: True)
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed(connectMethod: \"Sync\", useDnsEndPoint: False)
System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed(connectMethod: \"Apm\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open
net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7


Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Net.Sockets.Tests.TelemetryTest.VerifyStartStopEvents(ConcurrentQueue`1 events, Boolean connect, Int32 expectedCount) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 396
   at System.Net.Sockets.Tests.TelemetryTest.VerifyConnectFailureEvents(ConcurrentQueue`1 events) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 324
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 203
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0(System.String, System.String)

Child arguments:
  Apm, True
~~~

**Comment by MihaZupan** [comment]
Seems to have been fixed by #45170.

**Comment by antonfirsov** [comment]
This happened again in #48704, although I can't see any other occurrences in Kusto, so not reopening yet.

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210411.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1082333&view=ms.vss-test-web.build-test-results-tab&runId=33190830&resultId=100652&paneView=debug)

Failed test:
```
net6.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open
 -System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Sync\", useDnsEndPoint: True)
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Enumerable.WhereEnumerableIterator`1.Select[TResult](Func`2 selector) in /_/src/libraries/System.Linq/src/System/Linq/Where.cs:line 135
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector) in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 16
   at System.Net.Sockets.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 connectCount, Boolean connectOnly, Boolean shouldHaveTransferedBytes, Boolean shouldHaveDatagrams) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 456
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 161
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Sync, True
```
