### ISSUE TITLE
System.Buffers.ArrayPool.Tests.CollectionTests.PollingEventFires failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44037]
Lots of PRs have been failing today with this:
```
  Discovering: System.Buffers.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Buffers.Tests (found 42 of 43 test cases)
  Starting:    System.Buffers.Tests (parallel test collections = on, max threads = 2)
    System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"
    System.Buffers.ArrayPool.Tests.CollectionTests.PollingEventFires(trim: True) [FAIL]
      Half-way through waiting for remote process.
      Timed out at 10/29/2020 5:03:11 PM after 60000ms waiting for remote process.
      	Process ID: 44
      	Handle: 832
      	Name: dotnet
      	MainModule: /root/helix/work/correlation/dotnet
      	StartTime: 10/29/2020 5:02:10 PM
      	TotalProcessorTime: 00:00:00.1300000
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs(57,0): at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action`1 method, Boolean trim, Int32 timeout)
        /_/src/libraries/System.Buffers/tests/ArrayPool/CollectionTests.cs(151,0): at System.Buffers.ArrayPool.Tests.CollectionTests.PollingEventFires(Boolean trim)
```
e.g.
https://dev.azure.com/dnceng/public/_build/results?buildId=870197&view=ms.vss-test-web.build-test-results-tab&runId=27843160&resultId=183117&paneView=attachments

**Comment by stephentoub** [comment]
This has been failing a ton.  I'm disabling the test.  It only started failing very recently and needs to be investigated.
