### ISSUE TITLE
Test failure: System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ReturnBufferFiresDiagnosticEvent

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44060]
failed in job: [runtime-coreclr libraries-jitstress 20201029.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=869879&view=ms.vss-test-web.build-test-results-tab&runId=27835038&paneView=debug&resultId=161678)

net6.0-Linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.1804.Amd64.Open

Error message
~~~
Half-way through waiting for remote process.
Timed out at 10/29/2020 8:17:50 AM after 60000ms waiting for remote process.
\tProcess ID: 8424
\tHandle: 960
\tName: dotnet
\tMainModule: /home/helixbot/work/A4C408F6/p/dotnet
\tStartTime: 10/29/2020 8:16:49 AM
\tTotalProcessorTime: 00:00:00.1500000



Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action action, Boolean trim) in /_/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs:line 44
   at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ReturnBufferFiresDiagnosticEvent() in /_/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs:line 424
~~~

**Comment by stephentoub** [comment]
Again:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44571-merge-6d375b075a5d4f7ebd/System.Buffers.Tests/console.d033ce74.log?sv=2019-07-07&se=2020-12-02T11%3A39%3A20Z&sr=c&sp=rl&sig=740A875BdOQnd9zU%2BTiupgR6QU%2FL1rQjuQ2bHKifjUA%3D

**Comment by v-haren** [comment]
failed again in job: [runtime-libraries-coreclr outerloop 20201203.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=907184&view=ms.vss-test-web.build-test-results-tab&runId=28934436&resultId=103411&paneView=debug)

failed test: System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(connectMethod: \"Eap\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open

Error message
~~~
Half-way through waiting for remote process.
Timed out at 12/3/2020 12:38:24 PM after 60000ms waiting for remote process.
\tProcess ID: 28858
\tHandle: 1736
\tName: dotnet
\tMainModule: /home/helixbot/work/B9CE09F3/p/dotnet
\tStartTime: 12/3/2020 12:37:24 PM
\tTotalProcessorTime: 00:00:00.2900000


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(String connectMethod, Boolean useDnsEndPoint) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 266
~~~

**Comment by danmoseley** [comment]
Again, macOS 10.13
```
Console log: 'System.Buffers.Tests' from job 061cc071-f6af-425b-a328-88414fcccbe5 workitem 0e2e11c6-f88d-493c-9fae-a99deee70c3d (osx.1013.amd64.open) executed on machine dci-mac-build-003.local
+ ./RunTests.sh --runtime-path /tmp/helix/working/AA2B099C/p
----- start Fri Sep 17 12:20:46 PDT 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/AA2B099C/p/dotnet exec --runtimeconfig System.Buffers.Tests.runtimeconfig.json --depsfile System.Buffers.Tests.deps.json xunit.console.dll System.Buffers.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/AA2B099C/w/B67B0A45/e /private/tmp/helix/working/AA2B099C/w/B67B0A45/e
  Discovering: System.Buffers.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Buffers.Tests (found 42 of 46 test cases)
  Starting:    System.Buffers.Tests (parallel test collections = on, max threads = 4)
    System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"
    System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent [FAIL]
      Half-way through waiting for remote process.
      Timed out at 9/17/2021 12:27:51 PM after 60000ms waiting for remote process.
      	Process ID: 99041
      	Handle: 876
      	Name: dotnet
      	MainModule: /private/tmp/helix/working/AA2B099C/p/dotnet
      	StartTime: 9/17/2021 12:26:45 PM
      	TotalProcessorTime: 00:00:25.1393801
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs(45,0): at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Action method, Int32 timeout)
        /_/src/libraries/System.Buffers/tests/ArrayPool/UnitTests.cs(495,0): at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.RentingBufferOverConfiguredMaximumSizeFiresDiagnosticEvent()
   System.Buffers.Tests: [Long Running Test] 'System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ConfigurablePool_AllocatedArraysAreCleared_DateTime', Elapsed: 00:02:01
   System.Buffers.Tests: [Long Running Test] 'System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.ConfigurablePool_AllocatedArraysAreCleared_string', Elapsed: 00:02:05
/tmp/helix/working/AA2B099C/p/scripts/6a1a09b15a3f48f3ac008f16727551d0/execute.sh: line 4: 98977 Killed: 9               ./RunTests.sh --runtime-path "$HELIX_CORRELATION_PAYLOAD"
['System.Buffers.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```
https://github.com/dotnet/runtime/pull/59274
