### ISSUE TITLE
Test failure: JIT\\Methodical\\nonvirtualcall\\generics_r\\generics_r.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44138]
failed in job: [ runtime-coreclr gcstress0x3-gcstress0xc 20201101.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=872566&view=ms.vss-test-web.build-test-results-tab&runId=27919836&resultId=106753&paneView=debug)

failed tests:
JIT\\Methodical\\nonvirtualcall\\generics_r\\generics_r.cmd
Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest1245\\Generated1245\\Generated1245.cmd
JIT\\CodeGenBringUpTests\\LocallocCnstB1_PSP_d\\LocallocCnstB1_PSP_d.cmd
reflection\\ldtoken\\ldtokenmember\\ldtokenmember.cmd
JIT\\CodeGenBringUpTests\\RecursiveTailCall_r\\RecursiveTailCall_r.cmd

CoreCLR Windows_NT x86 Checked gcstress0xc @ Windows.10.Amd64.Open

Error message
~~~
Assert failure(PID 3616 [0x00000e20], Thread: 3844 [0x0f04]): Consistency check failed: Crst Level violation: Can't take level 9 lock CrstCodeVersioning because you already holding level 0 lock CrstLeafLock
FAILED: false

CORECLR! CHECK::Trigger + 0x310 (0x6e9711b0)
CORECLR! CrstBase::IsSafeToTake + 0x30A (0x6e4c6e4a)
CORECLR! CrstBase::Enter + 0x152 (0x6e4c6860)
CORECLR! CrstBase::AcquireLock + 0xD (0x6e4058a2)
CORECLR! CodeVersionManager::LockHolder::LockHolder + 0x25 (0x6e449ea9)
CORECLR! EECodeInfo::GetNativeCodeVersion + 0xC7 (0x6e5501fc)
CORECLR! EECodeInfo::GetSavedMethodCode + 0x8C (0x6e5506df)
CORECLR! UnwindStackFrame + 0xD3 (0x6e505393)
CORECLR! StackFrameIterator::NextRaw + 0x5BD (0x6e5ee9c7)
CORECLR! StackFrameIterator::Next + 0x46 (0x6e5ee3c6)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\crst.cpp Line: 765
    Image: C:\h\w\A1860954\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\A1860954\w\B722099C\e\JIT\Methodical\Reports\JIT.Methodical\nonvirtualcall\generics_r\generics_r.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A1860954\p\corerun.exe" generics_r.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A1860954\p
> C:\h\w\A1860954\w\B722099C\e\JIT\Methodical\nonvirtualcall\generics_r\generics_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._nonvirtualcall_generics_r_generics_r_._nonvirtualcall_generics_r_generics_r_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs:line 184407
~~~

**Comment by v-haren** [comment]
failed again in job: [ runtime-coreclr gcstress-extra 20201122.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=895976&view=ms.vss-test-web.build-test-results-tab&runId=28633798&resultId=104428&paneView=debug)

failed test: JIT\\CodeGenBringUpTests\\Gt1_ro\\Gt1_ro.cmd

CoreCLR windows x86 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open


Error message
~~~
Assert failure(PID 1952 [0x000007a0], Thread: 916 [0x0394]): Consistency check failed: Crst Level violation: Can't take level 9 lock CrstCodeVersioning because you already holding level 0 lock CrstLeafLock
FAILED: false

CORECLR! CHECK::Trigger + 0x310 (0x705e8b91)
CORECLR! CrstBase::IsSafeToTake + 0x304 (0x7014470e)
CORECLR! CrstBase::Enter + 0x152 (0x7014412a)
CORECLR! CrstBase::AcquireLock + 0xD (0x7007e817)
CORECLR! CodeVersionManager::LockHolder::LockHolder + 0x25 (0x700c772b)
CORECLR! EECodeInfo::GetNativeCodeVersion + 0xC7 (0x701cdb5c)
CORECLR! EECodeInfo::GetSavedMethodCode + 0x8C (0x701ce03f)
CORECLR! UnwindStackFrame + 0xD3 (0x70182933)
CORECLR! StackFrameIterator::NextRaw + 0x5BD (0x7026c2f9)
CORECLR! StackFrameIterator::Next + 0x46 (0x7026bcf8)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\crst.cpp Line: 765
    Image: C:\h\w\B42709A0\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\B42709A0\w\A67B094A\e\JIT\CodeGenBringUpTests\Reports\JIT.CodeGenBringUpTests\Gt1_ro\Gt1_ro.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B42709A0\p\corerun.exe" Gt1_ro.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B42709A0\p
> C:\h\w\B42709A0\w\A67B094A\e\JIT\CodeGenBringUpTests\Gt1_ro\Gt1_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_CodeGenBringUpTests._Gt1_ro_Gt1_ro_._Gt1_ro_Gt1_ro_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\JIT.CodeGenBringUpTests\JIT.CodeGenBringUpTests.XUnitWrapper.cs:line 35463
~~~

**Comment by AaronRobinsonMSFT** [comment]
Ran `Gt1_ro.cmd` and `generics_r.cmd` tests 10,000 times with no failures from either. Closing as not repro.
