### ISSUE TITLE
 GetSelfSigned13ServerCertificate() failed with CryptographicException in test run

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#44177]
This seems to be rare Windows failure but the outcome may deserve some investigation. Some of the tests switched somewhat recently to generating certificate and keys on the fly instead of relying on checked-in copy (as that has issues as well)

The failure I saw looks like
```
   System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3_Mock.SendAsync_RequestHeaderInResponse_Success(name: "Accept-Encoding", value: "identity,gzip") [FAIL]
      Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The parameter is incorrect.
      Stack Trace:
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(162,0): at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(87,0): at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.Import.cs(20,0): at Internal.Cryptography.Pal.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(63,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan`1 data)
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate.cs(52,0): at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] data)
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2.cs(51,0): at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
        C:\Users\test\github\wfurt-runtime\src\libraries\Common\tests\System\Net\Configuration.Certificates.cs(94,0): at System.Net.Test.Common.Configuration.Certificates.GetSelfSigned13ServerCertificate()
        C:\Users\test\github\wfurt-runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackServer.cs(27,0): at System.Net.Test.Common.Http3LoopbackServer..ctor(QuicImplementationProvider quicImplementationProvider, GenericLoopbackOptions options)
        C:\Users\test\github\wfurt-runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackServer.cs(81,0): at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServer(GenericLoopbackOptions options)
        C:\Users\test\github\wfurt-runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackServer.cs(86,0): at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options)
        C:\Users\test\github\wfurt-runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs(37,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        C:\Users\test\github\wfurt-runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Headers.cs(317,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_RequestHeaderInResponse_Success(String name, String value)
        --- End of stack trace from previous location ---

```

even if the failure is in HTTP test, I'll make it as Security issue for now as I don't see any obvious reason why this is failing. If I remember correctly, there was something similar on Linux if the crypto parameters comes out weak for whatever reason - but I'm not 100% sure. 

cc: @bartonjs @scalablecory

**Comment by bartonjs** [comment]
Weird, Windows rejected the PFX that it wrote.  I don't think I've ever heard of that happening.

Does the failure happen often enough that you can capture the exported bytes?  It'd require splitting up line 94 a bit:

```C#
byte[] pfx = innerCert.Export(X509ContentType.Pfx);

try
{
    cert = new X509Certificate2(pfx);
}
catch (CryptographicException)
{
    Console.WriteLine($"Bad PFX: {Convert.ToBase64String(pfx)}");
    throw;
}
```

If it's rare, then that same thing, but in a way that xUnit logs capture it.

**Comment by wfurt** [comment]
It is rare. I'll try to capture the data as you suggested. 
The code looks like:
```c#
                    using (ECDsa dsa = ECDsa.Create())
                    {
                        var certReq = new CertificateRequest("CN=testservereku.contoso.com", dsa, HashAlgorithmName.SHA256);
                        certReq.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, false));
                        certReq.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension(new OidCollection { new Oid("1.3.6.1.5.5.7.3.1") }, false));
                        certReq.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature, false));

                        X509Certificate2 innerCert = certReq.CreateSelfSigned(DateTimeOffset.UtcNow.AddMonths(-1), DateTimeOffset.UtcNow.AddMonths(1));

                        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                        {
                            using (innerCert)
                            {
                                cert = new X509Certificate2(innerCert.Export(X509ContentType.Pfx));
                            }
                        }
                        else
                        {
                            cert = innerCert;
                        }
                    }
```
so I assumed the innerCert is created by managed code? (or is that only on Unix?)

**Comment by bartonjs** [comment]
I don't see any failures similar to this in Kusto (only 4 failures have Internal.Cryptography.Pal.CertificatePal.FilterPFXStore in the stacktrace, and they're from a PR that tried to use a Win10 feature on Win8).  Seems like it may have been an OS issue (since I can't recall any product changes that might have had impact).
