### ISSUE TITLE
System.IO.Compression.GzipStreamUnitTests.Write_DataReadFromDesiredOffset(mode: AsyncAPM) failed with NullReferenceException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44189]
Configuration: `net6.0-OSX-Debug-x64-CoreCLR_release-OSX.1015.Amd64.Open`

https://dev.azure.com/dnceng/public/_build/results?buildId=873709&view=ms.vss-test-web.build-test-results-tab&runId=27957978&paneView=debug

```
System.NullReferenceException : Object reference not set to an instance of an object.
at System.IO.Compression.GZipStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/GZipStream.cs:line 142
   at System.IO.Stream.Close() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 154
   at System.IO.Tests.StreamPair.Dispose() in /_/src/libraries/Common/tests/Tests/System/IO/StreamConformanceTests.cs:line 1841
   at System.IO.Tests.ConnectedStreamConformanceTests.Write_DataReadFromDesiredOffset(ReadWriteMode mode) in /_/src/libraries/Common/tests/Tests/System/IO/StreamConformanceTests.cs:line 890
--- End of stack trace from previous location ---
```

**Comment by stephentoub** [comment]
Already fixed

**Comment by ViktorHofer** [comment]
Dupe of https://github.com/dotnet/runtime/issues/44173
