### ISSUE TITLE
PerformanceCounter tests failing in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44208]
Inconsistently but frequently, PRs in CI have been failing tests from the System.Diagnostics.Tests.PerformanceCounterTests suite.  When one test fails, a ton fail.  They all look along the lines of this:
```
Error message
System.InvalidCastException : Unable to cast object of type 'System.String' to type 'System.String[]'.

Stack trace
   at System.Diagnostics.SharedPerformanceCounter.GetCategoryData() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/SharedPerformanceCounter.cs:line 700
   at System.Diagnostics.SharedPerformanceCounter..ctor(String catName, String counterName, String instanceName, PerformanceCounterInstanceLifetime lifetime) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/SharedPerformanceCounter.cs:line 96
   at System.Diagnostics.SharedPerformanceCounter..ctor(String catName, String counterName, String instanceName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/SharedPerformanceCounter.cs:line 88
   at System.Diagnostics.SharedPerformanceCounter.RemoveAllInstances(String categoryName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/SharedPerformanceCounter.cs:line 1389
   at System.Diagnostics.PerformanceCounterCategory.Delete(String categoryName) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 395
   at System.Diagnostics.Tests.Helpers.DeleteCategory(String name) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 46
   at System.Diagnostics.Tests.Helpers.CreateCategory(String name, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 22
   at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs:line 293
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_Decrement() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs:line 186
```
e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=874236&view=ms.vss-test-web.build-test-results-tab&runId=27965576&resultId=121120&paneView=debug

**Comment by danmosemsft** [comment]
Apparently "Counter Names" may be String or Multistring, and the code expects the latter.

My guess is that here

https://github.com/dotnet/runtime/blob/c87e75e8ef260ccc6e979f9df1cc012536ee036f/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/SharedPerformanceCounter.cs#L700-L703

It simply needs to use `GetValueKind` to figure whether to cast to string or string[] and then proceed.

**Comment by danmosemsft** [comment]
@Anipik owns S.D.PerformanceCounter.

**Comment by stephentoub** [comment]
@steveisok hit the new assert:
```
Process terminated. Assertion failed.
Expected string[], got 'System.String[]' with kind 'String'for category 'averagecounter64samplecategory'
   at System.Diagnostics.Tests.CounterCreationDataCollectionTests.PerformanceCounterCategory_CreateCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/CounterCreationDataCollectionTests.cs:line 124
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44046-merge-146881d67d7c4c7ba9/System.Diagnostics.PerformanceCounter.Tests/console.210349c5.log?sv=2019-07-07&se=2020-11-25T20%3A35%3A23Z&sr=c&sp=rl&sig=gYGgvImTcGJ99mVVeSk%2Bg%2BucMp92%2F6xeEerbQTpkqv8%3D

https://github.com/dotnet/runtime/issues/44332

**Comment by stephentoub** [comment]
This assert output is really weird.  The assert I added is:
```C#
Debug.Assert(counterNamesObject is string[], $"Expected string[], got '{counterNamesObject}' with kind '{categoryKey.GetValueKind("Counter Names")}'for category '{_categoryName}'");
```
So the above shows it failing an `is string[]` check, but then its ToString is reporting that it's a `System.String[]`.

@jkotas, does this ring any bells?  Could this be related to casting changes?

**Comment by danmosemsft** [comment]
Well, that's our test
https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Diagnostics.PerformanceCounter/tests/CounterCreationDataCollectionTests.cs#L99
But it's just going through our API's.

**Comment by danmosemsft** [comment]
Oops, of course it's written by our test 😄

**Comment by steveisok** [comment]
I tried finding this kind of issue first.  I searched for "PerformanceCounters" and found 3 unrelated issues :-)

**Comment by jkotas** [comment]
> @jkotas, does this ring any bells? Could this be related to casting changes?

Yes, I think this looks like race condition in the lock-free hashtable used by casting.

@VSadov Could you please take a look?

**Comment by VSadov** [comment]
Will take a look. Thanks!

**Comment by VSadov** [comment]
@stephentoub - did this start recently or was like this for months?

**Comment by stephentoub** [comment]
To my knowledge,  recently.

**Comment by VSadov** [comment]
Exception message should generally be correct about types. 
`string[]` --> `string[]` would be an identity conversion. It should not use cache, unless something bad happened with the type system (i.e. two distinct string types)

I think it is more likely that we are getting a string with `System.String[]` content somehow.

The new assert in #44333 is a good idea - should help to verify this.

**Comment by VSadov** [comment]
Any new failures? Is there a way to check?

**Comment by stephentoub** [comment]
I haven't seen any more but I'm also not at my computer to run a query right now. (I'm also wondering if this could possibly have been another effect of https://github.com/dotnet/runtime/issues/44250?)

**Comment by stephentoub** [comment]
According to Kusto, this failed ~300 times on 11/2, ~100 times on 11/3, and then hasn't failed since.

**Comment by jkotas** [comment]
Likely another effect of #44250
