### ISSUE TITLE
StartInfo_NotepadWithContent* tests are failing in CI

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#44239]
We have 348 failures in last 30 days. This is predominately on `server20h1`  queue:

```
Assert.StartsWith() Failure:\r\nExpected: StartInfo_NotepadWithContent_withArgumentList_1156_a34ea3f3\r\nActual:   
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1179
```

there are few other failures where this fails on various Windows 8-10 with 
```
System.InvalidOperationException : Failed to set the specified COM apartment state.
   at System.Threading.Thread.SetApartmentState(ApartmentState state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs:line 238
   at System.Diagnostics.Process.ShellExecuteHelper.ShellExecuteOnSTAThread() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs:line 169
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs:line 79
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs:line 24
   at System.Diagnostics.Process.Start() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1234
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1302
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1169
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 385
```

**Comment by danmosemsft** [comment]
Those are different problems. In the first one, it's somehow not getting the window title (race?)

**Comment by danmosemsft** [comment]
@wfurt any sign of this diagnostic in the output (assuming there are failures on debug bits)
https://github.com/dotnet/runtime/blob/c87e75e8ef260ccc6e979f9df1cc012536ee036f/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L200
https://github.com/dotnet/runtime/blob/c87e75e8ef260ccc6e979f9df1cc012536ee036f/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L219

**Comment by wfurt** [comment]
not really, but I can look at more failures. I was wondering if the new queue even have Notepad :)

**Comment by danmosemsft** [comment]
Apparently it does as they got a Process object.

**Comment by danmosemsft** [comment]
The apartment state issue on non-Server Core occurred 10 times in 10/3-10/8 and not once previously or subsequently looking back 6 months. So I believe it was something elsewhere that is now fixed.

https://github.com/dotnet/runtime/pull/44972 will fix both for Server Core.

**Comment by danmosemsft** [comment]
Closing as I don't think we will take more action here.
