### ISSUE TITLE
Wasm Benchmark Runs Failing with Target Framework Error

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#44273]
Automated benchmark runs are failing with an Target Framework Error, this seems to be related to changing TFM net6.0. The issue might actually be in BDN, but I am putting it here for now.

```
executed on a0008R2
chmod: cannot access '/home/helixbot/work/C4F60A27/w/BF1F09BB/e/*.sh': No such file or directory
+ export MSBUILDDEBUGCOMM=1
+ export MSBUILDDEBUGPATH=/home/helixbot/work/C4F60A27/w/BF1F09BB/uploads
+ npm install --prefix /home/helixbot/work/C4F60A27/w/BF1F09BB/u jsvu -g
/home/helixbot/work/C4F60A27/w/BF1F09BB/u/bin/jsvu -> /home/helixbot/work/C4F60A27/w/BF1F09BB/u/lib/node_modules/jsvu/cli.js
+ jsvu@1.11.4
added 177 packages from 72 contributors in 13.948s
+ /home/helixbot/work/C4F60A27/w/BF1F09BB/u/bin/jsvu --os=linux64 --engines=v8
ðŸ“¦ jsvu v1.11.4 â€” the JavaScript engine Version Updater ðŸ“¦
âœ” Read OS from config: linux64
âœ” Read engines from config: v8
â¯ Finding the latest V8 versionâ€¦
[1A[Kâœ” Found latest V8 version: v8.8.230.
âœ– V8 v8.8.230 is already installed.
+ chmod +x /home/helixbot/work/C4F60A27/p/performance/tools/machine-setup.sh
+ . /home/helixbot/work/C4F60A27/p/performance/tools/machine-setup.sh
+ export PERFLAB_INLAB=1
+ export PERFLAB_REPO=dotnet/runtime
+ export PERFLAB_BRANCH=refs/pull/44224/merge
+ export PERFLAB_PERFHASH=8d9b216a63d05ff548283c9f2f137e1b5699a50d
+ export PERFLAB_HASH=170633e43d276e779706716c6b0c3c37e3974de4
+ export PERFLAB_QUEUE=Ubuntu.1804.Amd64.Open
+ export PERFLAB_BUILDNUM=20201104.6
+ export PERFLAB_BUILDARCH=x64
+ export PERFLAB_LOCALE=en-US
+ export PERFLAB_BUILDTIMESTAMP=2020-11-04T17:34:34Z
+ export PERFLAB_CONFIGS=CompilationMode=wasm;RunKind=micro
+ export DOTNET_VERSION=6.0.100-alpha.1.20553.6
+ export PERFLAB_TARGET_FRAMEWORKS=net6.0
+ export DOTNET_CLI_TELEMETRY_OPTOUT=1
+ export DOTNET_MULTILEVEL_LOOKUP=0
+ export UseSharedCompilation=false
+ export DOTNET_ROOT=/home/helixbot/work/C4F60A27/p/dotnet
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/helixbot/work/C4F60A27/p/dotnet
+ python3 /home/helixbot/work/C4F60A27/p/performance/scripts/benchmarks_ci.py --csproj /home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj --incremental no --architecture x64 -f net6.0 --dotnet-versions 6.0.100-alpha.1.20553.6 --cli-source-info args --cli-branch refs/pull/44224/merge --cli-commit-sha 170633e43d276e779706716c6b0c3c37e3974de4 --cli-repository https://github.com/dotnet/runtime --cli-source-timestamp 2020-11-04T17:34:34Z --wasm --bdn-artifacts /home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts --bdn-arguments=--anyCategories Libraries Runtime --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart --stopOnFirstError true --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmMainJS /home/helixbot/work/C4F60A27/p/dotnet-wasm/runtime-test.js --wasmEngine /home/helixbot/.jsvu/v8 --customRuntimePack /home/helixbot/work/C4F60A27/p/dotnet-wasm  --partition-count 30 --partition-index 10
[2020/11/04 19:05:22][INFO] ----------------------------------------------
[2020/11/04 19:05:22][INFO] Initializing logger 2020-11-04 19:05:22.222598
[2020/11/04 19:05:22][INFO] ----------------------------------------------
[2020/11/04 19:05:22][INFO] Installing tools.
[2020/11/04 19:05:22][INFO] ----------------------
[2020/11/04 19:05:22][INFO] Downloading DotNet Cli
[2020/11/04 19:05:22][INFO] ----------------------
[2020/11/04 19:05:22][INFO] DotNet Install Path: '/home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64'
[2020/11/04 19:05:22][INFO] Downloading https://dot.net/v1/dotnet-install.sh
[2020/11/04 19:05:22][INFO] $ pushd "/home/helixbot/work/C4F60A27/p/performance"
[2020/11/04 19:05:22][INFO] $ /home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64/dotnet-install.sh -InstallDir /home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64 -Architecture x64 -Version 6.0.100-alpha.1.20553.6
[2020/11/04 19:05:22][INFO] dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
[2020/11/04 19:05:22][INFO] dotnet-install: .NET Core SDK version 6.0.100-alpha.1.20553.6 is already installed.
[2020/11/04 19:05:22][INFO] dotnet-install: Adding to current process PATH: `/home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64`. Note: This change will be visible only when sourcing script.
[2020/11/04 19:05:22][INFO] dotnet-install: Installation finished successfully.
[2020/11/04 19:05:22][INFO] $ popd
[2020/11/04 19:05:22][INFO] $ dotnet --info
[2020/11/04 19:05:22][INFO] .NET SDK (reflecting any global.json):
[2020/11/04 19:05:22][INFO]  Version:   6.0.100-alpha.1.20553.6
[2020/11/04 19:05:22][INFO]  Commit:    5d175aba74
[2020/11/04 19:05:22][INFO] 
[2020/11/04 19:05:22][INFO] Runtime Environment:
[2020/11/04 19:05:22][INFO]  OS Name:     ubuntu
[2020/11/04 19:05:22][INFO]  OS Version:  18.04
[2020/11/04 19:05:22][INFO]  OS Platform: Linux
[2020/11/04 19:05:22][INFO]  RID:         ubuntu.18.04-x64
[2020/11/04 19:05:22][INFO]  Base Path:   /home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64/sdk/6.0.100-alpha.1.20553.6/
[2020/11/04 19:05:22][INFO] 
[2020/11/04 19:05:22][INFO] Host (useful for support):
[2020/11/04 19:05:22][INFO]   Version: 6.0.0-alpha.1.20513.9
[2020/11/04 19:05:22][INFO]   Commit:  eea2256e56
[2020/11/04 19:05:22][INFO] 
[2020/11/04 19:05:22][INFO] .NET SDKs installed:
[2020/11/04 19:05:22][INFO]   6.0.100-alpha.1.20553.6 [/home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64/sdk]
[2020/11/04 19:05:22][INFO] 
[2020/11/04 19:05:22][INFO] .NET runtimes installed:
[2020/11/04 19:05:22][INFO]   Microsoft.AspNetCore.App 6.0.0-alpha.1.20513.8 [/home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64/shared/Microsoft.AspNetCore.App]
[2020/11/04 19:05:22][INFO]   Microsoft.NETCore.App 6.0.0-alpha.1.20513.9 [/home/helixbot/work/C4F60A27/p/performance/tools/dotnet/x64/shared/Microsoft.NETCore.App]
[2020/11/04 19:05:22][INFO] 
[2020/11/04 19:05:22][INFO] To install additional .NET runtimes or SDKs:
[2020/11/04 19:05:22][INFO]   https://aka.ms/dotnet-download
[2020/11/04 19:05:22][INFO] ---------------------------------------
[2020/11/04 19:05:22][INFO] Removing packages, bin and obj folders.
[2020/11/04 19:05:22][INFO] ---------------------------------------
[2020/11/04 19:05:22][INFO] -------------------------------
[2020/11/04 19:05:22][INFO] Restoring .NET micro benchmarks
[2020/11/04 19:05:22][INFO] -------------------------------
[2020/11/04 19:05:22][INFO] $ pushd "/home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro"
[2020/11/04 19:05:22][INFO] $ dotnet restore /home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj --packages /home/helixbot/work/C4F60A27/p/performance/artifacts/packages
[2020/11/04 19:05:23][INFO]   Determining projects to restore...
[2020/11/04 19:05:48][INFO]   Restored /home/helixbot/work/C4F60A27/p/performance/src/tools/Reporting/Reporting/Reporting.csproj (in 24.64 sec).
[2020/11/04 19:06:02][INFO]   Restored /home/helixbot/work/C4F60A27/p/performance/src/harness/BenchmarkDotNet.Extensions/BenchmarkDotNet.Extensions.csproj (in 39.44 sec).
[2020/11/04 19:06:14][INFO]   Restored /home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj (in 26.42 sec).
[2020/11/04 19:06:14][INFO] $ popd
[2020/11/04 19:06:14][INFO] -------------------------------------------
[2020/11/04 19:06:14][INFO] Building .NET micro benchmarks for 'net6.0'
[2020/11/04 19:06:14][INFO] -------------------------------------------
[2020/11/04 19:06:14][INFO] $ pushd "/home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro"
[2020/11/04 19:06:14][INFO] $ dotnet build /home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net6.0 --no-restore /p:NuGetPackageRoot=/home/helixbot/work/C4F60A27/p/performance/artifacts/packages
[2020/11/04 19:06:14][INFO] Microsoft (R) Build Engine version 16.9.0-preview-20513-07+c10f34c4e for .NET
[2020/11/04 19:06:14][INFO] Copyright (C) Microsoft Corporation. All rights reserved.
[2020/11/04 19:06:14][INFO] 
[2020/11/04 19:06:18][INFO]   Reporting -> /home/helixbot/work/C4F60A27/p/performance/artifacts/bin/Reporting/Release/netstandard2.0/Reporting.dll
[2020/11/04 19:06:19][INFO]   BenchmarkDotNet.Extensions -> /home/helixbot/work/C4F60A27/p/performance/artifacts/bin/BenchmarkDotNet.Extensions/Release/netstandard2.0/BenchmarkDotNet.Extensions.dll
[2020/11/04 19:06:26][INFO]   MicroBenchmarks -> /home/helixbot/work/C4F60A27/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/MicroBenchmarks.dll
[2020/11/04 19:06:26][INFO] 
[2020/11/04 19:06:26][INFO] Build succeeded.
[2020/11/04 19:06:26][INFO]     0 Warning(s)
[2020/11/04 19:06:26][INFO]     0 Error(s)
[2020/11/04 19:06:26][INFO] 
[2020/11/04 19:06:26][INFO] Time Elapsed 00:00:11.67
[2020/11/04 19:06:26][INFO] $ popd
[2020/11/04 19:06:26][INFO] ------------------------------------------
[2020/11/04 19:06:26][INFO] Running .NET micro benchmarks for 'net6.0'
[2020/11/04 19:06:26][INFO] ------------------------------------------
[2020/11/04 19:06:26][INFO] --------------------------------------------------
[2020/11/04 19:06:26][INFO] Dumping COMPlus environment:
[2020/11/04 19:06:26][INFO] --------------------------------------------------
[2020/11/04 19:06:26][INFO] $ pushd "/home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro"
[2020/11/04 19:06:26][INFO] $ dotnet run --project /home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net6.0 --no-restore --no-build -- --anyCategories Libraries Runtime --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart --stopOnFirstError true --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmMainJS /home/helixbot/work/C4F60A27/p/dotnet-wasm/runtime-test.js --wasmEngine /home/helixbot/.jsvu/v8 --customRuntimePack /home/helixbot/work/C4F60A27/p/dotnet-wasm "" --partition-count 30 --partition-index 10 --artifacts /home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/C4F60A27/p/performance/artifacts/packages --runtimes wasm
[2020/11/04 19:06:27][INFO] // Validating benchmarks:
[2020/11/04 19:06:29][INFO] // ***** BenchmarkRunner: Start   *****
[2020/11/04 19:06:29][INFO] // ***** Found 99 benchmark(s) in total *****
[2020/11/04 19:06:29][INFO] // ***** Building 1 exe(s) in Parallel: Start   *****
[2020/11/04 19:06:29][INFO] // start dotnet restore --packages "/home/helixbot/work/C4F60A27/p/performance/artifacts/packages" /p:DebugType=portable /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in /home/helixbot/work/C4F60A27/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/7dc65042-a827-4596-a8a6-21c1c4a0a595
[2020/11/04 19:06:42][INFO] // command took 12.37s and exited with 1
[2020/11/04 19:06:42][INFO] // ***** Done, took 00:00:12 (12.65 sec)   *****
[2020/11/04 19:06:42][INFO] // Found 1 benchmarks:
[2020/11/04 19:06:42][INFO] //   ByteMark.BenchEmFloatClass: Job-AXZLTY(PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0)
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // Build Error: The project which defines benchmarks does not target 'net5.0'.
[2020/11/04 19:06:42][INFO] You need to add 'net5.0' to <TargetFrameworks> in your project file ('MicroBenchmarks').
[2020/11/04 19:06:42][INFO] Example: <TargetFrameworks>net6.0;net5.0</TargetFrameworks>
[2020/11/04 19:06:42][INFO] // ***** BenchmarkRunner: Finish  *****
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // * Export *
[2020/11/04 19:06:42][INFO]   home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts/results/ByteMark-report.csv
[2020/11/04 19:06:42][INFO]   home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts/results/ByteMark-report-github.md
[2020/11/04 19:06:42][INFO]   home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts/results/ByteMark-report.html
[2020/11/04 19:06:42][INFO]   home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts/results/ByteMark-report-full.json
[2020/11/04 19:06:42][INFO]   home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts/results/ByteMark-perf-lab-report.json
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // * Detailed results *
[2020/11/04 19:06:42][INFO] ByteMark.BenchEmFloatClass: Job-AXZLTY(PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0)
[2020/11/04 19:06:42][INFO] Runtime = ; GC =
[2020/11/04 19:06:42][INFO] There are not any results runs
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // * Summary *
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] BenchmarkDotNet=v0.12.1.1448-nightly, OS=ubuntu 18.04
[2020/11/04 19:06:42][INFO] AMD EPYC 7452, 1 CPU, 2 logical cores and 1 physical core
[2020/11/04 19:06:42][INFO] .NET SDK=6.0.100-alpha.1.20553.6
[2020/11/04 19:06:42][INFO]   [Host] : .NET 6.0.0 (6.0.20.51309), X64 RyuJIT
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=Wasm  Arguments=/p:DebugType=portable
[2020/11/04 19:06:42][INFO] Toolchain=Wasm  InvocationCount=1  IterationCount=1
[2020/11/04 19:06:42][INFO] IterationTime=250.0000 ms  MaxIterationCount=20  MinIterationCount=15
[2020/11/04 19:06:42][INFO] RunStrategy=ColdStart  UnrollFactor=1  WarmupCount=0
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] |            Method | Mean | Error | Median | Min | Max |
[2020/11/04 19:06:42][INFO] |------------------ |-----:|------:|-------:|----:|----:|
[2020/11/04 19:06:42][INFO] | BenchEmFloatClass |   NA |    NA |     NA |  NA |  NA |
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] Benchmarks with issues:
[2020/11/04 19:06:42][INFO]   ByteMark.BenchEmFloatClass: Job-AXZLTY(PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0)
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // * Legends *
[2020/11/04 19:06:42][INFO]   Mean   : Arithmetic mean of all measurements
[2020/11/04 19:06:42][INFO]   Error  : Half of 99.9% confidence interval
[2020/11/04 19:06:42][INFO]   Median : Value separating the higher half of all measurements (50th percentile)
[2020/11/04 19:06:42][INFO]   Min    : Minimum
[2020/11/04 19:06:42][INFO]   Max    : Maximum
[2020/11/04 19:06:42][INFO]   1 ns   : 1 Nanosecond (0.000000001 sec)
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // * Diagnostic Output - MemoryDiagnoser *
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] // ***** BenchmarkRunner: End *****
[2020/11/04 19:06:42][INFO] // ** Remained 98 benchmark(s) to run **
[2020/11/04 19:06:42][INFO] Run time: 00:00:00 (0.21 sec), executed benchmarks: 0
[2020/11/04 19:06:42][INFO] 
[2020/11/04 19:06:42][INFO] Global total time: 00:00:12 (12.86 sec), executed benchmarks: 0
[2020/11/04 19:06:42][INFO] // * Artifacts cleanup *
[2020/11/04 19:06:42][INFO] $ popd
[2020/11/04 19:06:42][ERROR] Process exited with status 1
Traceback (most recent call last):
  File "/home/helixbot/work/C4F60A27/p/performance/scripts/benchmarks_ci.py", line 247, in <module>
    __main(sys.argv[1:])
  File "/home/helixbot/work/C4F60A27/p/performance/scripts/benchmarks_ci.py", line 230, in __main
    args
  File "/home/helixbot/work/C4F60A27/p/performance/scripts/micro_benchmarks.py", line 310, in run
    *run_args
  File "/home/helixbot/work/C4F60A27/p/performance/scripts/dotnet.py", line 450, in run
    self.working_directory)
  File "/home/helixbot/work/C4F60A27/p/performance/scripts/performance/common.py", line 200, in run
    returncode, quoted_cmdline)
subprocess.CalledProcessError: Command '$ dotnet run --project /home/helixbot/work/C4F60A27/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net6.0 --no-restore --no-build -- --anyCategories Libraries Runtime --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart --stopOnFirstError true --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmMainJS /home/helixbot/work/C4F60A27/p/dotnet-wasm/runtime-test.js --wasmEngine /home/helixbot/.jsvu/v8 --customRuntimePack /home/helixbot/work/C4F60A27/p/dotnet-wasm "" --partition-count 30 --partition-index 10 --artifacts /home/helixbot/work/C4F60A27/p/artifacts/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/C4F60A27/p/performance/artifacts/packages --runtimes wasm' returned non-zero exit status 1.
+ export _commandExitCode=1
+ /bin/sh /home/helixbot/work/C4F60A27/p/reporter/run.sh https://dev.azure.com/dnceng/ public 28012324 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvNzgzOkJ1aWxkL0J1aWxkLzg3NTY0MSIsImF1aSI6ImVjMzVmYTBmLWUxYjAtNGEwOC05ODMwLTEyMjg2NTk5ZTYzMyIsInNpZCI6IjMyYzMzNTJiLWQwMDctNGNiMS04MmM1LTY3N2Q0ZTk4NThjYiIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7ODc1NjQxIiwib3JjaGlkIjoiZmY1MDdkZjgtZDdiNS00ZDFjLWEzYjItZGE0MWFiNzY3ZjM0LmpvYjMuam9iMSIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzpiNTVkZTRlZC00YjVhLTQyMTUtYThlNC0wYTBhNWY3MWU3ZDgiLCJuYmYiOjE2MDQ1MTM2MjUsImV4cCI6MTYwNDUzNDAyNX0.BQtnHavIFW8PceKhfcgdbuA4AWyW-ggZ3wCqNDqOWiutTbcU33kPiLt3c8clDPlCEDQZ3P_4vANemQvsjNxQZaCqzy22BF0xANEhtQaGU3rjgskOhmqkWqTv7VAdcuc6vWHkhS_bMQj5oMeQyhRsvFq6h__QqK_sIYdyF6YBgHaJxpPxIpW6GV1FYws_Wudg9tMRJcgxSoheu7RSkthNimLMpWAxOEg4PQzjz3iyX0_vO5d2O28ogS7U4iLpznrThLOpMYgvv_O9nxt5aBiwInPbwKqen19MjzNJ-XNvk183F_DOUpD-5tM5aVoV_siLvHJn2lZMYLYzf6V2R7NOmw
+ whoami
+ [ helixbot = root ]
+ exec sudo -E /home/helixbot/work/C4F60A27/p/reporter/run.sh https://dev.azure.com/dnceng/ public 28012324 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvNzgzOkJ1aWxkL0J1aWxkLzg3NTY0MSIsImF1aSI6ImVjMzVmYTBmLWUxYjAtNGEwOC05ODMwLTEyMjg2NTk5ZTYzMyIsInNpZCI6IjMyYzMzNTJiLWQwMDctNGNiMS04MmM1LTY3N2Q0ZTk4NThjYiIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7ODc1NjQxIiwib3JjaGlkIjoiZmY1MDdkZjgtZDdiNS00ZDFjLWEzYjItZGE0MWFiNzY3ZjM0LmpvYjMuam9iMSIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzpiNTVkZTRlZC00YjVhLTQyMTUtYThlNC0wYTBhNWY3MWU3ZDgiLCJuYmYiOjE2MDQ1MTM2MjUsImV4cCI6MTYwNDUzNDAyNX0.BQtnHavIFW8PceKhfcgdbuA4AWyW-ggZ3wCqNDqOWiutTbcU33kPiLt3c8clDPlCEDQZ3P_4vANemQvsjNxQZaCqzy22BF0xANEhtQaGU3rjgskOhmqkWqTv7VAdcuc6vWHkhS_bMQj5oMeQyhRsvFq6h__QqK_sIYdyF6YBgHaJxpPxIpW6GV1FYws_Wudg9tMRJcgxSoheu7RSkthNimLMpWAxOEg4PQzjz3iyX0_vO5d2O28ogS7U4iLpznrThLOpMYgvv_O9nxt5aBiwInPbwKqen19MjzNJ-XNvk183F_DOUpD-5tM5aVoV_siLvHJn2lZMYLYzf6V2R7NOmw
+ whoami
+ [ root = root ]
+ dirname -- /home/helixbot/work/C4F60A27/p/reporter/run.sh
+ CDPATH= cd -- /home/helixbot/work/C4F60A27/p/reporter
+ pwd
+ script_path=/home/helixbot/work/C4F60A27/p/reporter
+ ENV_PATH=/home/helixbot/.azdo-env
+ TMP_ENV_PATH=/home/helixbot/.azdo-env-tmp
+ date -u +%FT%TZ
2020-11-04T19:06:42Z
+ [ ! -f /home/helixbot/.azdo-env/bin/python ]
+ _OLD_PYTHONPATH=/usr/bin/python3:/etc/helix/scripts
+ export PYTHONPATH=
+ /home/helixbot/.azdo-env/bin/python -c import azure.devops
+ echo azure-devops module already available
azure-devops module already available
+ /home/helixbot/.azdo-env/bin/python -c import future
+ echo future module already available
future module already available
+ date -u +%FT%TZ
2020-11-04T19:06:42Z
+ /home/helixbot/.azdo-env/bin/python -B /home/helixbot/work/C4F60A27/p/reporter/run.py https://dev.azure.com/dnceng/ public 28012324 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvNzgzOkJ1aWxkL0J1aWxkLzg3NTY0MSIsImF1aSI6ImVjMzVmYTBmLWUxYjAtNGEwOC05ODMwLTEyMjg2NTk5ZTYzMyIsInNpZCI6IjMyYzMzNTJiLWQwMDctNGNiMS04MmM1LTY3N2Q0ZTk4NThjYiIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7ODc1NjQxIiwib3JjaGlkIjoiZmY1MDdkZjgtZDdiNS00ZDFjLWEzYjItZGE0MWFiNzY3ZjM0LmpvYjMuam9iMSIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzpiNTVkZTRlZC00YjVhLTQyMTUtYThlNC0wYTBhNWY3MWU3ZDgiLCJuYmYiOjE2MDQ1MTM2MjUsImV4cCI6MTYwNDUzNDAyNX0.BQtnHavIFW8PceKhfcgdbuA4AWyW-ggZ3wCqNDqOWiutTbcU33kPiLt3c8clDPlCEDQZ3P_4vANemQvsjNxQZaCqzy22BF0xANEhtQaGU3rjgskOhmqkWqTv7VAdcuc6vWHkhS_bMQj5oMeQyhRsvFq6h__QqK_sIYdyF6YBgHaJxpPxIpW6GV1FYws_Wudg9tMRJcgxSoheu7RSkthNimLMpWAxOEg4PQzjz3iyX0_vO5d2O28ogS7U4iLpznrThLOpMYgvv_O9nxt5aBiwInPbwKqen19MjzNJ-XNvk183F_DOUpD-5tM5aVoV_siLvHJn2lZMYLYzf6V2R7NOmw
2020-11-04 19:06:42,875: INFO: 140235722450752: run(82): main: Main thread starting 10 workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
2020-11-04 19:06:42,877: INFO: 140235722450752: run(89): main: Beginning reading of test results.
2020-11-04 19:06:42,877: INFO: 140235722450752: run(98): main: Uploading results in batches of size 1000
2020-11-04 19:06:42,877: INFO: 140235722450752: run(103): main: Main thread finished queueing batches
2020-11-04 19:06:42,877: INFO: 140235722450752: run(107): main: Main thread exiting
Searching '/home/helixbot/work/C4F60A27/w/BF1F09BB/e/..' for log files
Found log '/home/helixbot/work/C4F60A27/w/BF1F09BB/e/../console.caca0c7d.log'
Uri 'https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44224-merge-65feea2abdcd4d43ab/release.Partition10/console.caca0c7d.log?sv=2019-07-07&se=2020-11-24T18%3A29%3A08Z&sr=c&sp=rl&sig=wD%2FbUShCJMYPAG6ZBSpp4Dd25ZDjot78OEPupU%2FiKOQ%3D'
Generated log list: console.caca0c7d.log:
  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44224-merge-65feea2abdcd4d43ab/release.Partition10/console.caca0c7d.log?sv=2019-07-07&se=2020-11-24T18%3A29%3A08Z&sr=c&sp=rl&sig=wD%2FbUShCJMYPAG6ZBSpp4Dd25ZDjot78OEPupU%2FiKOQ%3D

Searching '/home/helixbot/work/C4F60A27/w/BF1F09BB/e' for test results files
Searching '/home/helixbot/work/C4F60A27/w/BF1F09BB/uploads' for test results files
No results file found in any of the following formats: xunit, junit, trx
+ date -u +%FT%TZ
2020-11-04T19:06:42Z
+ export PYTHONPATH=/usr/bin/python3:/etc/helix/scripts
+ exit 1
```

**Comment by naricc** [comment]
So I determined this issue actually belongs in Benchmark Dotnet. I'm going to close this and open an issue there.

**Comment by CoffeeFlux** [comment]
You should be able to transfer this one instead, though it doesn't matter too much.

**Comment by naricc** [comment]
@CoffeeFlux I tried that, but it seems I don't have the appropriate permissions to transfer things to dotnet/benchmarkdotnet. Odd that I can create issues there but not transfer them though.

Any way, here is the BDN issue: https://github.com/dotnet/BenchmarkDotNet/issues/1591
