### ISSUE TITLE
System.Diagnostics.PerformanceCounter.Tests Failing 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#44332]
Seeing this kind of failure across multiple builds.  Can't tell if it's widespread yet.

```
Expected string[], got 'System.String[]' with kind 'String'for category 'averagecounter64samplecategory'
   at System.Diagnostics.Tests.CounterCreationDataCollectionTests.PerformanceCounterCategory_CreateCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/CounterCreationDataCollectionTests.cs:line 124
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 390
...
```

https://dev.azure.com/dnceng/public/_build/results?buildId=876982&view=results

Helix log from one build: 

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44046-merge-146881d67d7c4c7ba9/System.Diagnostics.PerformanceCounter.Tests/console.210349c5.log?sv=2019-07-07&se=2020-11-25T20%3A35%3A23Z&sr=c&sp=rl&sig=gYGgvImTcGJ99mVVeSk%2Bg%2BucMp92%2F6xeEerbQTpkqv8%3D

**Comment by stephentoub** [comment]
Thanks, @steveisok.  This is https://github.com/dotnet/runtime/issues/44208; I just added an assert to help diagnose the failure, which is why it's showing up as an assert here rather than the exception shown there.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/44208; copied the assert details to there.
