### ISSUE TITLE
Directory enumaration throws I/O exception after umounting

### ISSUE THREAD

**Issue by ecls-ecls** [dotnet/runtime#44436]
OS: raspbian (latest)
Arch: ARM

I'm having trouble when calling this function:

var directories = Directory.GetDirectories(absolutePath);

At this point of the code, 'absolutePath' is guaranteed to exist, but what I'm doing differently is that this directory is mounted with "bind" option:

mount -o bind /some/dir/source /some/other/dir/destiny

This happens after I umount it, the folder still exists, but it contains nothing.

It is not a racing condition, waited some seconds after umounting it.

Maybe related with File System cache?

Stack trace:

Unhandled exception. System.IO.IOException: Input/output error
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetDirectories(String path)

It is trying to find next entry, but maybe kernel API is responding that it does not exists.

**Comment by ecls-ecls** [comment]
Can't reproduce it anymore.
