### ISSUE TITLE
Isolated Storage gives CodeBase is not supported on assemblies loaded from a single-file bundle.

### ISSUE THREAD

**Issue by hougaard** [dotnet/runtime#44511]
Console application converted from 3.1 to 5.0 and published to a single .EXE, throw this error when calling System.IO.IsolatedStorage.IsolatedStorageFile.GetStore

System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at System.IO.IsolatedStorage.Helper.GetDefaultIdentityAndHash(Object& identity, String& hash, Char separator)
   at System.IO.IsolatedStorage.IsolatedStorage.InitStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)
   at System.IO.IsolatedStorage.IsolatedStorageFile..ctor(IsolatedStorageScope scope)
   at System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType)
   at BCCL.Program.RegisterBCCL(Options opt)
   at BCCL.Program.<>c__DisplayClass2_0.<Main>b__1(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at BCCL.Program.Main(String[] args)

Visual Studio updated to 16.8.

Code with issue:
using (IsolatedStorageFile isoStore = IsolatedStorageFile.GetStore(IsolatedStorageScope.User | IsolatedStorageScope.Domain | IsolatedStorageScope.Assembly, null, null))
{
}

Everything worked perfectly in 3.1.

**Comment by am11** [comment]
This issue was discussed in #42265. I'd double check if the `dotnet.exe` version used to build/publish the app is 5.0.100 (and not a 5.0 preview or release candidate). It is supposed to not throw that exception with 5.0 RTM build.

The difference between 3.x and 5.0 single file bundle is that in the latter, not all files in bundle are extracted to disk and framework assemblies are loaded directly from the bundle using memory map. However, we can fallback to 3.x behavior in project targeting `net5.0`, by setting `<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>` property in csproj file: https://github.com/dotnet/designs/blob/d455a60/accepted/2020/single-file/design.md#optional-settings.

**Comment by hougaard** [comment]
my dotnet.exe is 5.0.100
![image](https://user-images.githubusercontent.com/3357237/98838614-5f70f800-23f9-11eb-94b1-02a178991764.png)

This is with the IncludeAllContentForSelfExtract because I do need a single file.

**Comment by agocke** [comment]
I just tried this myself and couldn't repro it. Code:

```C#
using System;
using System.IO.IsolatedStorage;

namespace net5
{
    public class net5
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("testing IsolatedStorageFile");
            using (IsolatedStorageFile isoStore = IsolatedStorageFile.GetStore(IsolatedStorageScope.User | IsolatedStorageScope.Domain | IsolatedStorageScope.Assembly, null, null))
            {
            }
            Console.ReadLine();
        }
    }
}
```

Command line:

`dotnet publish -r win-x64 -p:PublishSingleFile=true -f net5.0 -p:IncludeAllContentForSelfExtract=true`

**Comment by hougaard** [comment]
Thanks for checking @agocke - I'll try to retarget to 5.0 again and see if there's something else going on...

**Comment by vitek-karas** [comment]
If you still see the problematic behavior on .NET 5 feel free to reopen this issue, but right now it seems to be a solve problem.

**Comment by jez9999** [comment]
@vitek-karas I think this should be reopened as I'm getting this issue when building an ASP.NET Core web application with MVC Razor, in latest Visual Studio 2019 (16.8.4), generating a single-file for use with linux-x64.  My dotnet.exe version is:

```
C:\Program Files\dotnet>dotnet.exe /?
.NET SDK (5.0.102)
```

The error on Linux when the executable is run is:

```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
         at System.Reflection.RuntimeAssembly.get_CodeBase()
         at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   [...]
   at BLSHBot.Web.WebStartup.<>c.<configure>b__10_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at BLSHBot.Web.WebStartup.configure(IApplicationBuilder app, ILogger`1 logger)
   at BLSHBot.Web.WebStartup.Configure(IApplicationBuilder app, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BLSHBot.Web.Program.Main(String[] args)
```

**Comment by vitek-karas** [comment]
@jez9999 - the fact that `Assembly.CodeBase` throws an exception in single-file deployments is by design. Assemblies bundled into the single-file don't exist as files on disk, so there's no possible path the property can return.

The issue you mention is with the code trying to use that property - in this case it seems to be `DependencyContextLoader`. Can you please file a new issue against that component?

**Comment by jez9999** [comment]
@vitek-karas Should that be filed in `dotnet/runtime` or somewhere else?

**Comment by vitek-karas** [comment]
I think it belongs to `dotnet/runtime` (now - I think it recently moved from somewhere else).

**Comment by jez9999** [comment]
Filed #47527
