### ISSUE TITLE
ThrowAsyncIOInProgress invoked from time to time

### ISSUE THREAD

**Issue by xiaomi7732** [dotnet/runtime#44623]
### Description
Calling into the following method (single threaded) throws exception from time to time. Please help understanding why:
```csharp
        public Task SerializeAsync(IEnumerable<SampleActivity> samples, string destinationFilePath)
        {
            using StreamWriter file = File.CreateText(destinationFilePath);
            return file.WriteAsync(JsonConvert.SerializeObject(samples));
        }
```

Call stack:
```shell
2020-11-11 17:18:12.819 -08:00 [VRB] System.InvalidOperationException: The stream is currently in use by a previous operation on the stream.
   at System.IO.StreamWriter.ThrowAsyncIOInProgress()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Project.Client.SampleActivitySerializer.SerializeAsync(IEnumerable`1 samples, String destinationFilePath) in D:\Repos\Project\src\SampleActivitySerializer.cs:line 14
   at Project.Client.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e) in D:\Repos\Project\src\Provider.cs:line 251
```

### Configuration
.NET Core 3.1;
OS: x64, Windows / x64 Ubuntu 16.04 LTS
* Do you know whether it is specific to that configuration?
Not as I know.

**Comment by stephentoub** [comment]
The code you wrote is basically:
```C#
StreamWriter file = File.CreateText(destinationFilePath);
Task t = file.WriteAsync(JsonConvert.SerializeObject(samples));
file.Dispose();
return t;
```
In other words, you're Dispose'ing of the file while the async operation is still in flight.

I think you likely wanted this instead:
```C#
        public async Task SerializeAsync(IEnumerable<SampleActivity> samples, string destinationFilePath)
        {
            using StreamWriter file = File.CreateText(destinationFilePath);
            return await file.WriteAsync(JsonConvert.SerializeObject(samples));
        }
```

**Comment by stephentoub** [comment]
Closing as answered.  Please feel free to re-open if there's still an issue to be discussed. Thanks.

**Comment by xiaomi7732** [comment]
Thanks @stephentoub for the pointer. I thought the state machine would be the same between those 2, they aren't.

This is notes just for myself:
The state machine, on the caller, for the original code looks like this: no dispose() involved because it is called inside  SerializeAsync(), and as pointed out, at that moment, the task, aka WriteAsyncTask, is not fully completed yet:

```csharp
	private sealed class <Caller>d__1 : IAsyncStateMachine
	{
		public int <>1__state;

		public AsyncTaskMethodBuilder <>t__builder;

		public Program <>4__this;

		private string <fileName>5__1;

		private SampleActivitySerializer <target>5__2;

		private ConfiguredTaskAwaitable.ConfiguredTaskAwaiter <>u__1;

		private void MoveNext()
		{
			int num = <>1__state;
			try
			{
				ConfiguredTaskAwaitable.ConfiguredTaskAwaiter awaiter;
				if (num != 0)
				{
					<fileName>5__1 = null;
					<target>5__2 = new SampleActivitySerializer();
					awaiter = <target>5__2.SerializeAsync(GenSample(), <fileName>5__1).ConfigureAwait(false).GetAwaiter();
					if (!awaiter.IsCompleted)
					{
						num = (<>1__state = 0);
						<>u__1 = awaiter;
						<Caller>d__1 stateMachine = this;
						<>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref stateMachine);
						return;
					}
				}
				else
				{
					awaiter = <>u__1;
					<>u__1 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
					num = (<>1__state = -1);
				}
				awaiter.GetResult();
			}
			catch (Exception exception)
			{
				<>1__state = -2;
				<fileName>5__1 = null;
				<target>5__2 = null;
				<>t__builder.SetException(exception);
				return;
			}
			<>1__state = -2;
			<fileName>5__1 = null;
			<target>5__2 = null;
			<>t__builder.SetResult();
		}
		void IAsyncStateMachine.MoveNext()
		{
			//ILSpy generated this explicit interface implementation from .override directive in MoveNext
			this.MoveNext();
		}

		[DebuggerHidden]
		private void SetStateMachine(IAsyncStateMachine stateMachine)
		{
		}

		void IAsyncStateMachine.SetStateMachine(IAsyncStateMachine stateMachine)
		{
			//ILSpy generated this explicit interface implementation from .override directive in SetStateMachine
			this.SetStateMachine(stateMachine);
		}
	}
```

Write it the other way, the dispose is called on 'final' statement, after all the operation is done, right before returning.

```csharp
[CompilerGenerated]
private sealed class <SerializeAsync2>d__1 : IAsyncStateMachine
{
	public int <>1__state;

	public AsyncTaskMethodBuilder <>t__builder;

	public IEnumerable<SampleActivity> samples;

	public string destinationFilePath;

	public SampleActivitySerializer <>4__this;

	private StreamWriter <file>5__1;

	private TaskAwaiter <>u__1;

	private void MoveNext()
	{
		int num = <>1__state;
		try
		{
			if (num != 0)
			{
				<file>5__1 = File.CreateText(destinationFilePath);
			}
			try
			{
				TaskAwaiter awaiter;
				if (num != 0)
				{
					awaiter = <file>5__1.WriteAsync(JsonConvert.SerializeObject(samples)).GetAwaiter();
					if (!awaiter.IsCompleted)
					{
						num = (<>1__state = 0);
						<>u__1 = awaiter;
						<SerializeAsync2>d__1 stateMachine = this;
						<>t__builder.AwaitUnsafeOnCompleted(ref awaiter, ref stateMachine);
						return;
					}
				}
				else
				{
					awaiter = <>u__1;
					<>u__1 = default(TaskAwaiter);
					num = (<>1__state = -1);
				}
				awaiter.GetResult();
			}
			finally
			{
				if (num < 0 && <file>5__1 != null)
				{
					((IDisposable)<file>5__1).Dispose();
				}
			}
		}
		catch (Exception exception)
		{
			<>1__state = -2;
			<file>5__1 = null;
			<>t__builder.SetException(exception);
			return;
		}
		<>1__state = -2;
		<file>5__1 = null;
		<>t__builder.SetResult();
	}

	void IAsyncStateMachine.MoveNext()
	{
		//ILSpy generated this explicit interface implementation from .override directive in MoveNext
		this.MoveNext();
	}

	[DebuggerHidden]
	private void SetStateMachine(IAsyncStateMachine stateMachine)
	{
	}

	void IAsyncStateMachine.SetStateMachine(IAsyncStateMachine stateMachine)
	{
		//ILSpy generated this explicit interface implementation from .override directive in SetStateMachine
		this.SetStateMachine(stateMachine);
	}
}
```
