### ISSUE TITLE
MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic failure on Linux

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#44780]
```
  Discovering: System.Threading.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tests (found 211 of 237 test cases)
  Starting:    System.Threading.Tests (parallel test collections = on, max threads = 2)
    System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: "") [FAIL]
      System.AggregateException : File contents: 10 (One or more errors occurred. (Assert.True() Failure
      Expected: True
      Actual:   False))
      ---- System.AggregateException : One or more errors occurred. (Assert.True() Failure
      Expected: True
      Actual:   False)
      -------- Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Threading/tests/MutexTests.cs(448,0): at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix)
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(49,0): at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1()
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(56,0): at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2()
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(107,0): at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test)
        /_/src/libraries/System.Threading/tests/MutexTests.cs(410,0): at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix)
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(153,0): at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh)
        /_/src/libraries/System.Threading/tests/MutexTests.cs(456,0): at System.Threading.Tests.MutexTests.IncrementValueInFileNTimes(Mutex mutex, String fileName, Int32 n)
        /_/src/libraries/System.Threading/tests/MutexTests.cs(440,0): at System.Threading.Tests.MutexTests.<>c__DisplayClass15_0.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__0()
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(35,0): at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__0()
  Finished:    System.Threading.Tests
```

**Comment by jkotas** [comment]
Hit by https://github.com/dotnet/runtime/pull/44465

**Comment by jkotas** [comment]
Related to #28449

**Comment by janvorli** [comment]
cc @kouvel

**Comment by VincentBu** [comment]
Failed again in [runtime 20210221.13](https://dev.azure.com/dnceng/public/_build/results?buildId=1005145&view=ms.vss-test-web.build-test-results-tab&runId=31382922&resultId=183328&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open
 -System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: \"\")
```

**Error message:**
```
System.AggregateException : File contents: 10 (One or more errors occurred. (Remote process failed with an unhandled exception.))
---- System.AggregateException : One or more errors occurred. (Remote process failed with an unhandled exception.)
-------- Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace
   at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 448
----- Inner Stack Trace -----
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1() in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 49
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2() in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 57
   at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 108
   at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 410
----- Inner Stack Trace -----

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Threading.Tests.MutexTests.IncrementValueInFileNTimes(Mutex mutex, String fileName, Int32 n) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 456
   at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1(String m, String f) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 423

Child process:
  System.Threading.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tests.MutexTests+<>c Void <CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1(System.String, System.String)

Child arguments:
  a5882fdd176b4bfd9f674e263c0c359b, /tmp/MutexTests_5dgbrwem.vkq/CrossProcess_NamedMutex_ProtectedFileAccessAtomic_407_78dcee6c
```

**Comment by VincentBu** [comment]
Failed again in [runtime 20210304.9](https://dev.azure.com/dnceng/public/_build/results?buildId=1022598&view=ms.vss-test-web.build-test-results-tab&runId=31808594&resultId=183718&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open
 -System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: \"\")
```

**Error message:**
```
System.AggregateException : File contents: 10 (One or more errors occurred. (Remote process failed with an unhandled exception.))
---- System.AggregateException : One or more errors occurred. (Remote process failed with an unhandled exception.)
-------- Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Stack trace
   at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 448
----- Inner Stack Trace -----
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1() in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 49
   at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2() in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 57
   at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 108
   at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 410
----- Inner Stack Trace -----

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Threading.Tests.MutexTests.IncrementValueInFileNTimes(Mutex mutex, String fileName, Int32 n) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 456
   at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1(String m, String f) in /_/src/libraries/System.Threading/tests/MutexTests.cs:line 423

Child process:
  System.Threading.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tests.MutexTests+<>c Void <CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__15_1(System.String, System.String)

Child arguments:
  bd907f9508b24b0c9a758577ca8fc3d4, /tmp/MutexTests_a1s4bviv.cx5/CrossProcess_NamedMutex_ProtectedFileAccessAtomic_407_d395ce4e

```

**Comment by mangod9** [comment]
Closing for now, since it hasnt reproed in the recent past.
