### ISSUE TITLE
Wasm Browser work items failing with OpenQA.Selenium.WebDriverException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44862]
```
[00:03:37] crit: OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:37245/
                    at OpenQA.Selenium.DriverService.Start()
                    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
                    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.GetChromeDriver(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 110
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 53
                    at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 120
XHarness exit code: 71
```

Console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44835-merge-bb0f134359584f1080/System.Text.Encoding.CodePages.Tests/console.1329b837.log?sv=2019-07-07&se=2020-12-07T23%3A45%3A59Z&sr=c&sp=rl&sig=un3ihnU48W%2BrW%2FnAWOvHl%2Fd9djtH7rUx13LlD1Kipe0%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=889822&view=ms.vss-test-web.build-test-results-tab&runId=28458820&resultId=144669&paneView=attachments

cc @steveisok @akoeplinger

**Comment by steveisok** [comment]
@radical Not sure what to make of this

**Comment by steveisok** [comment]
Another build with the same failure:

https://dev.azure.com/dnceng/public/_build/results?buildId=890219&view=ms.vss-test-web.build-test-results-tab&runId=28469708&resultId=100001&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by radical** [comment]
> Another build with the same failure:
> 
> https://dev.azure.com/dnceng/public/_build/results?buildId=890219&view=ms.vss-test-web.build-test-results-tab&runId=28469708&resultId=100001&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Lots of failed tests there. They seem to be failing with mono assertions, eg:
```
[03:44:57] info: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[03:44:57] info: * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:4698, condition `<disabled>' not met
[03:44:57] info: * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:4698, condition `<disabled>' not met
[03:44:57] info: Unhandled exception in _finalize_startup
[03:44:57] fail: [out of order message from the browser]: http://127.0.0.1:35439/index.html?arg=--run&arg=WasmTestRunner.dll&arg=System.Xml.Xsl.XslTransformApi.Tests.dll&arg=-notrait&arg=category%3dIgnoreForCI&arg=-notrait&arg=category%3dOuterLoop&arg=-notrait&arg=category%3dfailing 0:0 Uncaught ExitStatus: Program terminated with exit(0)
```
[System.Xml.Xsl.XslTransform.Api.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44751-merge-1f92635e3a544347a7/System.Xml.Xsl.XslTransformApi.Tests/console.2abb86da.log?sv=2019-07-07&se=2020-12-08T02%3A39%3A28Z&sr=c&sp=rl&sig=pNeK3nEpdlnHKfnYuEMaI3qt0BPSyHHpRNJtjZx8M7s%3D)

I didn't look at *all* of them, fyi.

**Comment by radical** [comment]
> @radical Not sure what to make of this

This might be because of a race. I'll investigate.

**Comment by steveisok** [comment]
> > Another build with the same failure:
> > https://dev.azure.com/dnceng/public/_build/results?buildId=890219&view=ms.vss-test-web.build-test-results-tab&runId=28469708&resultId=100001&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
> 
> Lots of failed tests there. They seem to be failing with mono assertions, eg:
> 
> ```
> [03:44:57] info: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
> [03:44:57] info: * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:4698, condition `<disabled>' not met
> [03:44:57] info: * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:4698, condition `<disabled>' not met
> [03:44:57] info: Unhandled exception in _finalize_startup
> [03:44:57] fail: [out of order message from the browser]: http://127.0.0.1:35439/index.html?arg=--run&arg=WasmTestRunner.dll&arg=System.Xml.Xsl.XslTransformApi.Tests.dll&arg=-notrait&arg=category%3dIgnoreForCI&arg=-notrait&arg=category%3dOuterLoop&arg=-notrait&arg=category%3dfailing 0:0 Uncaught ExitStatus: Program terminated with exit(0)
> ```
> 
> [System.Xml.Xsl.XslTransform.Api.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44751-merge-1f92635e3a544347a7/System.Xml.Xsl.XslTransformApi.Tests/console.2abb86da.log?sv=2019-07-07&se=2020-12-08T02%3A39%3A28Z&sr=c&sp=rl&sig=pNeK3nEpdlnHKfnYuEMaI3qt0BPSyHHpRNJtjZx8M7s%3D)
> 
> I didn't look at _all_ of them, fyi.

This one is a false positive.  It's on a PR that Mitch is fixing.  The original listed in this issue is legit, I think.

**Comment by lewing** [comment]
Just to make sure I'm reading the exception correctly here, the driver service is just trying to start chrome driver and failing?  This is before any of our code is running?

**Comment by radical** [comment]
Yeah, this is one of the first things the xharness command does:

```
                    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.GetChromeDriver(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 110
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 53
                    at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 120
XHarness exit code: 71
```

It is failing to launch for some reason. Maybe we can retry if we see `Cannot start the driver service`?

**Comment by radical** [comment]
Opened https://github.com/dotnet/xharness/pull/370 .

**Comment by radical** [comment]
@steveisok Has this been seen on any other run? How do we check whether the "fix" helped or not?

**Comment by radical** [comment]
This can be closed now.

**Comment by ViktorHofer** [comment]
Still happening: https://dev.azure.com/dnceng/public/_build/results?buildId=1306968&view=ms.vss-test-web.build-test-results-tab&runId=38480032&resultId=173052&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Saw this in at least one other build this week as well.

```
Connection refused [::ffff:127.0.0.1]:43191 (localhost:43191)
Connection refused [::ffff:127.0.0.1]:43191 (localhost:43191)
Connection refused [::ffff:127.0.0.1]:43191 (localhost:43191)
Starting ChromeDriver 84.0.4147.0 (ff714bcb10c3356b1b1b2819148507a34fa4b1f8-refs/heads/master@{#768968}) on port 43191
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Connection refused [::ffff:127.0.0.1]:43191 (localhost:43191)
[10:27:16] crit: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
                  ---> OpenQA.Selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
                    at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
                    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
                    --- End of inner exception stack trace ---
                    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
                    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
                    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.GetChromiumDriver[TDriverOptions,TDriver,TDriverService](String driverName, Func`2 getDriverService, ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 230
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.GetChromeDriver(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 134
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 54
                    at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 142
```

**Comment by krwq** [comment]
Are we using latest xharness on the failing runs? @premun's fix should've fixed this. Perhaps we haven't yet used the latest version on the recent run and it is now fixed?

**Comment by premun** [comment]
I don't think I was fixing this issue. @radical?

**Comment by radical** [comment]
> Are we using latest xharness on the failing runs? @premun's fix should've fixed this. Perhaps we haven't yet used the latest version on the recent run and it is now fixed?

which fix?

**Comment by jakobbotsch** [comment]
I couldn't find a recent failure of this, so will close for now. Let's reopen if we see a new failure.
