### ISSUE TITLE
Failure running APICompat when building on ARM

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#45086]
This appears to be a bug in CCI when running on ARM:
```
  Unhandled exception. System.DataMisalignedException: A datatype misalignment was detected in a load or store instruction.
     at Microsoft.Cci.UtilityDataStructures.MemoryReader.ReadDouble()
     at Microsoft.Cci.MetadataReader.AttributeDecoder.GetPrimitiveValue(ITypeReference type)
     at Microsoft.Cci.MetadataReader.AttributeDecoder.ReadSerializedValue(ITypeReference type)
     at Microsoft.Cci.MetadataReader.CustomAttributeDecoder..ctor(PEFileToObjectModel peFileToObjectModel, MemoryReader signatureMemoryReader, UInt32 customAttributeRowId, IMethodReference attributeConstructor)
     at Microsoft.Cci.MetadataReader.PEFileToObjectModel.GetCustomAttributeAtRow(MetadataObject owningObject, UInt32 token, UInt32 customAttributeRowId)
     at Microsoft.Cci.MetadataReader.ObjectModelImplementation.MetadataObject.GetAttributes()
     at Microsoft.Cci.MetadataReader.ObjectModelImplementation.MetadataObject.get_Attributes()
     at Microsoft.Cci.Differs.Rules.AttributeDifference.Diff(IDifferences differences, ITypeDefinitionMember impl, ITypeDefinitionMember contract) in /_/src/Microsoft.DotNet.ApiCompat/src/Rules/Compat/AttributeDifference.cs:line 75
     at Microsoft.Cci.Differs.DifferenceRule.Diff(IDifferences differences, MemberMapping mapping) in /_/src/Microsoft.Cci.Extensions/Differs/DifferenceRule.cs:line 41
     at Microsoft.Cci.Differs.DifferenceRule.Diff[T](IDifferences differences, ElementMapping`1 mapping) in /_/src/Microsoft.Cci.Extensions/Differs/DifferenceRule.cs:line 18
     at Microsoft.Cci.Differs.ElementDiffer`1.Diff() in /_/src/Microsoft.Cci.Extensions/Differs/ElementDiffer.cs:line 75
     at Microsoft.Cci.Differs.ElementDiffer`1.GetMappingDifference() in /_/src/Microsoft.Cci.Extensions/Differs/ElementDiffer.cs:line 64
     at Microsoft.Cci.Differs.ElementDiffer`1.EnsureDiff() in /_/src/Microsoft.Cci.Extensions/Differs/ElementDiffer.cs:line 54
     at Microsoft.Cci.Differs.ElementDiffer`1.get_DifferenceType() in /_/src/Microsoft.Cci.Extensions/Differs/ElementDiffer.cs:line 35
     at Microsoft.Cci.Mappings.ElementMapping`1.get_Difference() in /_/src/Microsoft.Cci.Extensions/Mappings/ElementMapping.cs:line 101
     at Microsoft.Cci.Filters.MappingDifferenceFilter.Include(MemberMapping member) in /_/src/Microsoft.Cci.Extensions/Filters/MappingDifferenceFilter.cs:line 67
     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
     at Microsoft.Cci.Filters.MappingDifferenceFilter.Include(TypeMapping type) in /_/src/Microsoft.Cci.Extensions/Filters/MappingDifferenceFilter.cs:line 52
     at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
     at Microsoft.Cci.Filters.MappingDifferenceFilter.Include(NamespaceMapping ns) in /_/src/Microsoft.Cci.Extensions/Filters/MappingDifferenceFilter.cs:line 35
     at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
     at Microsoft.Cci.Traversers.MappingsTypeMemberTraverser.Visit(IEnumerable`1 namespaces) in /_/src/Microsoft.Cci.Extensions/Traversers/MappingsTypeMemberTraverser.cs:line 66
     at Microsoft.Cci.Traversers.MappingsTypeMemberTraverser.Visit(AssemblyMapping assembly) in /_/src/Microsoft.Cci.Extensions/Traversers/MappingsTypeMemberTraverser.cs:line 58
     at Microsoft.Cci.Traversers.DifferenceTraverser.Visit(AssemblyMapping mapping) in /_/src/Microsoft.Cci.Extensions/Traversers/DifferenceTraverser.cs:line 43
     at Microsoft.Cci.Writers.DifferenceWriter.Visit(AssemblyMapping mapping) in /_/src/Microsoft.DotNet.ApiCompat/src/DifferenceWriter.cs:line 71
     at Microsoft.Cci.Traversers.MappingsTypeMemberTraverser.Visit(IEnumerable`1 assemblies) in /_/src/Microsoft.Cci.Extensions/Traversers/MappingsTypeMemberTraverser.cs:line 48
     at Microsoft.Cci.Traversers.MappingsTypeMemberTraverser.Visit(AssemblySetMapping assemblySet) in /_/src/Microsoft.Cci.Extensions/Traversers/MappingsTypeMemberTraverser.cs:line 34
     at Microsoft.Cci.Traversers.DifferenceTraverser.Visit(AssemblySetMapping mapping) in /_/src/Microsoft.Cci.Extensions/Traversers/DifferenceTraverser.cs:line 37
     at Microsoft.Cci.Traversers.DifferenceTraverser.Visit(IEnumerable`1 oldAssemblies, IEnumerable`1 newAssemblies) in /_/src/Microsoft.Cci.Extensions/Traversers/DifferenceTraverser.cs:line 31
     at Microsoft.Cci.Writers.DifferenceWriter.Write(String oldAssembliesName, IEnumerable`1 oldAssemblies, String newAssembliesName, IEnumerable`1 newAssemblies) in /_/src/Microsoft.DotNet.ApiCompat/src/DifferenceWriter.cs:line 36
     at Microsoft.DotNet.ApiCompat.ApiCompatRunner.<>c__DisplayClass5_0.<CreateApp>b__0() in /_/src/Microsoft.DotNet.ApiCompat/src/ApiCompatRunner.cs:line 160
     at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
     at Microsoft.DotNet.ApiCompat.ApiCompatRunner.Run(String[] args) in /_/src/Microsoft.DotNet.ApiCompat/src/ApiCompatRunner.cs:line 41
     at Microsoft.DotNet.ApiCompat.Program.Main(String[] args) in /_/src/Microsoft.DotNet.ApiCompat/src/Program.cs:line 10
  Aborted
```
@wfurt I remember you hit something similar in the past, did you do anything to workaround or fix it?

**Comment by wfurt** [comment]
no, I did not. There are several versions if CCI floating around and some of them have it fixed.

**Comment by ericstj** [comment]
I see, found the issue here: https://github.com/microsoft/cci/issues/64
