### ISSUE TITLE
Test failure: ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45097]
failed in job: [runtime-coreclr libraries-jitstress2-jitstressregs 20201121.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=895422&view=ms.vss-test-web.build-test-results-tab&runId=28614764&resultId=143212&paneView=debug)

net6.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs8-Windows.10.Amd64.Open

Error message
~~~
Assert.InRange() Failure
Range:  (0 - 30000)
Actual: 30016


Stack trace
   at System.Threading.Tests.ThreadTestHelpers.WaitForConditionWithCustomDelay(Func`1 condition, Action delay) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 147
   at System.Threading.Tests.ThreadTestHelpers.WaitForCondition(Func`1 condition) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 117
   at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest() in /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs:line 16
~~~

**Comment by mangod9** [comment]
Closing this since hasnt repro-ed in a while.
