### ISSUE TITLE
GetServiceOrCreateInstance attempts to call wrong constructor when no types registered in D.I.

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/runtime#45119]
Original issue: https://github.com/dotnet/efcore/issues/23306
/cc @bricelam @davidfowl 

Using these types:

```C#
public class FailureContext : DbContext
{
    public FailureContext(ILogger<FailureContext> logger)
    {
        Console.WriteLine($"With logger {logger}");
    }

    public FailureContext()
    {
        Console.WriteLine("Parameterless");
    }
}
```

This works for both `GetService<FailureContext>` and `ActivatorUtilities.GetServiceOrCreateInstance<FailureContext>` when both these types are in D.I.:

```C#
        var serviceProvider1 = new ServiceCollection()
            .AddSingleton<ILogger<FailureContext>, MyLogger>()
            .AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context1 = serviceProvider1.GetService<FailureContext>();

        var serviceProvider2 = new ServiceCollection()
            .AddSingleton<ILogger<FailureContext>, MyLogger>()
            .AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context2 = ActivatorUtilities.GetServiceOrCreateInstance<FailureContext>(serviceProvider2);
```
Output:
```
With logger MyLogger
With logger MyLogger
```

It also works if only DbContext is registered in D.I.:
```C#
        var serviceProvider1 = new ServiceCollection()
            //.AddSingleton<ILogger<FailureContext>, MyLogger>()
            .AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context1 = serviceProvider1.GetService<FailureContext>();

        var serviceProvider2 = new ServiceCollection()
            //.AddSingleton<ILogger<FailureContext>, MyLogger>()
            .AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context2 = ActivatorUtilities.GetServiceOrCreateInstance<FailureContext>(serviceProvider2);
```
In this case the output shows that the parameterless constructor is used:
```
Parameterless
Parameterless
```

It also works if `FailureContext` is not registered in D.I., but the logger is:

```C#
        var serviceProvider1 = new ServiceCollection()
            .AddSingleton<ILogger<FailureContext>, MyLogger>()
            //.AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context1 = serviceProvider1.GetService<FailureContext>();

        var serviceProvider2 = new ServiceCollection()
            .AddSingleton<ILogger<FailureContext>, MyLogger>()
            //.AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context2 = ActivatorUtilities.GetServiceOrCreateInstance<FailureContext>(serviceProvider2);
```
In this case `GetService` returns null, but `GetServiceOrCreateInstance` still chooses the correct constructor.
```
With logger MyLogger
```
When this fails is when neither the logger or the logger are registered in D..I:
```C#
        var serviceProvider1 = new ServiceCollection()
            //.AddSingleton<ILogger<FailureContext>, MyLogger>()
            //.AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context1 = serviceProvider1.GetService<FailureContext>();

        var serviceProvider2 = new ServiceCollection()
            //.AddSingleton<ILogger<FailureContext>, MyLogger>()
            //.AddSingleton<FailureContext>()
            .BuildServiceProvider();

        var context2 = ActivatorUtilities.GetServiceOrCreateInstance<FailureContext>(serviceProvider2);
```
```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[FailureContext]' while attempting to activate 'FailureContext'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Program.Main(String[] args) in /home/ajcvickers/AllTogetherNow/FiveOh/Program.cs:line 155
```

In this case, `GetServiceOrCreateInstance` should choose the parameterless constructor since there is no other constructor that can work, but it it instead fails by attempting to call a constructor for which the parameter cannot be resolved.

**Comment by maryamariyan** [comment]
Related to https://github.com/dotnet/runtime/issues/46132
