### ISSUE TITLE
CI failure in System.Diagnostics.PerformanceCounter.Tests

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#45182]
https://dev.azure.com/dnceng/public/_build/results?buildId=899010&view=logs&jobId=85312bf4-08bc-52d1-d0fc-b5f2255cc3aa&j=85312bf4-08bc-52d1-d0fc-b5f2255cc3aa&t=361fd1e3-c164-5be7-cbf1-ec0d6b8f4a50

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45176-merge-15d08531259d4dbcb2/System.Diagnostics.PerformanceCounter.Tests/console.2e9c85c3.log?sv=2019-07-07&se=2020-12-15T01%3A51%3A43Z&sr=c&sp=rl&sig=s3mU9DL%2F0P1Be%2FRGE8g2z1AXG5Mru0B2J%2Fjf0Nx63vs%3D

```
C:\h\w\A5860980\w\AD3E098E\e>call RunTests.cmd --runtime-path C:\h\w\A5860980\p --runtime-path C:\h\w\A5860980\p 
----- start Wed 11/25/2020  1:52:40.32 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A5860980\w\AD3E098E\e\
"C:\h\w\A5860980\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.PerformanceCounter.Tests.runtimeconfig.json --depsfile System.Diagnostics.PerformanceCounter.Tests.deps.json xunit.console.dll System.Diagnostics.PerformanceCounter.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A5860980\w\AD3E098E\e>"C:\h\w\A5860980\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.PerformanceCounter.Tests.runtimeconfig.json --depsfile System.Diagnostics.PerformanceCounter.Tests.deps.json xunit.console.dll System.Diagnostics.PerformanceCounter.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.PerformanceCounter.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.PerformanceCounter.Tests (found 89 of 91 test cases)
  Starting:    System.Diagnostics.PerformanceCounter.Tests (parallel test collections = on, max threads = 2)
    System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInitEndInit_ProcessorCounter [FAIL]
      System.InvalidOperationException : Category does not exist.
      Stack Trace:
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs(373,0): at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs(479,0): at System.Diagnostics.PerformanceCounter.InitializeImpl()
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs(453,0): at System.Diagnostics.PerformanceCounter.Initialize()
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounter.cs(78,0): at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, String machineName)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs(173,0): at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInitEndInit_ProcessorCounter()

Info: Successfully installed performance counters in C:\h\w\A5860980\t\hnqj03yb.4rm\provider.man    System.Diagnostics.Tests.PerformanceDataTests.PerformanceCounter_PerformanceData [SKIP]
      Condition(s) not met: "IsRunnableEnvironnement"

Info: Successfully uninstalled the performance counters from the counter definition XML file C:\h\w\A5860980\t\hnqj03yb.4rm\provider.man.  Finished:    System.Diagnostics.PerformanceCounter.Tests
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.PerformanceCounter.Tests  Total: 92, Errors: 0, Failed: 1, Skipped: 1, Time: 17.544s
```

**Comment by tommcdon** [comment]
@krwq triaged for .net 6.  feel free to resolve as appropriate
