### ISSUE TITLE
Received chunk header length could not be parsed

### ISSUE THREAD

**Issue by markzielinski** [dotnet/runtime#45218]
### Description

When sending a request to an API with HttpClient to receive streaming data an exception is thrown with the message "Received chunk header length could not be parsed."   I have confirmed that the remote side is setting Transfer-Encoding: Chunked to keep the connection open, however the API streams the data over this open connection without sending a chunk header prior to sending the data.   From what I can gather this is apparently a common practice when streaming data over HTTP and while it may not strictly adhere to the RFC this used to work in earlier versions of .NET.

Exception has occurred: CLR/System.IO.IOException
Exception thrown: 'System.IO.IOException' in System.Net.Http.dll: 'Received chunk header length could not be parsed: '7B-22-74-79-70-65-22-3A-22-74-72-61-64-65-22-2C-22-73-79-6D-62-6F-6C-22-3A-22-53-50-59-22-2C-22-65-78-63-68-22-3A-22-50-22-2C-22-70-72-69-63-65-22-3A-22-33-35-35-2E-33-33-22-2C-22-73-69-7A-65-22-3A-22-30-22-2C-22-63-76-6F-6C-22-3A-22-37-30-34-31-31-38-39-30-22-2C-22-64-61-74-65-22-3A-22-31-36-30-35-39-32-30-34-30-30-30-30-30-22-2C-22-6C-61-73-74-22-3A-22-33-35-35-2E-33-33-22-7D'.'
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(Int32 maxBytesToRead, CancellationTokenRegistration cancellationRegistration)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunksFromConnectionBuffer(Span`1 buffer, CancellationTokenRegistration cancellationRegistration)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.get_EndOfStream()

**Comment by wfurt** [comment]
What previous versions did you try @markzielinski ? Is there public server showing this behavior? This seems like clear RFC violation but you suggesting to treat it as `Connection: close`, right? e.g. give the content ASIS until end of the TCP?

**Comment by stephentoub** [comment]
I just tried this on .NET Framework 4.8:
```C#
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        using (Socket listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
        {
            listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listener.Listen(1);
            var ep = (IPEndPoint)listener.LocalEndPoint;
            string url = $"http://{ep.Address}:{ep.Port}";

            using (var c = new HttpClient())
            {
                Task<string> t = c.GetStringAsync(url);

                using (Socket server = listener.Accept())
                using (StreamReader reader = new StreamReader(new NetworkStream(server, ownsSocket: false)))
                {
                    while (!string.IsNullOrEmpty(reader.ReadLine())) ;

                    server.Send(Encoding.UTF8.GetBytes("HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n"));

                    //server.Send(Encoding.UTF8.GetBytes("hello"));
                    server.Send(Encoding.UTF8.GetBytes("5\r\nhello\r\n0\r\n\r\n"));
                }

                Console.WriteLine(await t);
            }
        }
    }
}
```
With a proper chunk, it succeeds as you'd expect, printing out:
```
hello
```
and with the improper chunk that just includes the data, no header or footer, it fails with:
```
Unhandled Exception: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.StartRead()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\Users\stoub\source\repos\ConsoleApp6\ConsoleApp6\Program.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.<Main>()
```
I tried WinHttpHandler as well, and it similarly fails:
```
Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12152 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server returned an invalid or unrecognized response'.
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__109.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\Users\stoub\source\repos\ConsoleApp6\ConsoleApp6\Program.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.<Main>()
```

Is my repro not an accurate representation of the scenario, and if not, can you tweak it to make it be so we can better understand?

Thanks.

**Comment by markzielinski** [comment]
I took another look at this and there must be some other issue that is causing that exception.   I replicated the request with Curl and I can see the server is properly sending the chunk size as seen below which I didn't think it was at first:

HTTP/1.1 200 OK
Date: Wed, 25 Nov 2020 19:45:57 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive

9d
{"type":"quote","symbol":"SPY","bid":362.19,"bidsz":5,"bidexch":"Z","biddate":"1606333557000","ask":362.2,"asksz":3,"askexch":"Z","askdate":"1606333557000"}

9e
{"type":"quote","symbol":"SPY","bid":362.2,"bidsz":11,"bidexch":"Z","biddate":"1606333557000","ask":362.22,"asksz":6,"askexch":"Z","askdate":"1606333557000"}

9e
{"type":"quote","symbol":"SPY","bid":362.2,"bidsz":11,"bidexch":"Z","biddate":"1606333557000","ask":362.22,"asksz":5,"askexch":"Z","askdate":"1606333557000"}

**Comment by stephentoub** [comment]
Thanks. Can you share a repro?  Is there some server we can try with?  Or could you share the raw bytes the server is sending back?  Etc.

**Comment by wfurt** [comment]
there were some cases that the sites can produce different responces based on request headers (like accept-encoding, etc.) If you testing with curl as baseline, you can run it with -v and make sure your dotnet app sends same header set.

**Comment by markzielinski** [comment]
Well I carried out a bunch of tests and I'm not able to reproduce this issue anymore.  I encountered this problem a couple of days ago and saved the stack trace but didn't open a report on it until today, so this must have been a problem that I have since fixed on my side.  Sorry for the false alarm!  I will open up a new issue if I see this problem again and can reliably reproduce it.

**Comment by stephentoub** [comment]
Ok. Thanks, @markzielinski.
