### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.GetAsync_LargeRequestHeader_HeadersAndValuesSent

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#45257]
failed again in job: [runtime-libraries-coreclr outerloop 20201125.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=899602&view=ms.vss-test-web.build-test-results-tab&runId=28738060&resultId=104072&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.GetAsync_LargeRequestHeader_HeadersAndValuesSent(remoteServer: (BaseUri: https://corefx-net-http2.azurewebsites.net/, HttpVersion: 2.0), uri: https://corefx-net-http2.azurewebsites.net/Echo.ashx)

net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7

Error message
~~~
System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---- System.TimeoutException : The operation was canceled.
-------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.


Stack trace
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 583
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_LargeRequestHeader_HeadersAndValuesSent(RemoteServer remoteServer, Uri uri) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:line 736
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 57
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1283
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 709
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 859
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.VersionCheckerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTestBase.cs:line 124
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
~~~

_Originally posted by @v-haren in https://github.com/dotnet/runtime/issues/45205#issuecomment-734031194_

**Comment by ManickaP** [comment]
Moved from: https://github.com/dotnet/runtime/issues/45205#issuecomment-734031194

**Comment by karelz** [comment]
Only semi-related failures (1 machine hiccup) in last 2 months (2/23-4/23) (main/master branch only)

When | OS | Exception
-- | -- | --
2021-03-18T12:35:44.064Z | ubuntu.1804.amd64.open.rt | System.Net.Http.HttpRequestException :   Resource temporarily unavailable   (corefx-net-http2.azurewebsites.net:443)\n----   System.Net.Sockets.SocketException : Resource temporarily unavailable
2021-03-18T12:35:44.064Z | ubuntu.1804.amd64.open.rt | System.Net.Http.HttpRequestException : Resource temporarily unavailable   (corefx-net-http2.azurewebsites.net:443)\n----   System.Net.Sockets.SocketException : Resource temporarily unavailable
2021-03-18T12:35:44.064Z | ubuntu.1804.amd64.open.rt | System.Net.Http.HttpRequestException : Resource temporarily unavailable   (corefx-net-http11.azurewebsites.net:443)\n----   System.Net.Sockets.SocketException : Resource temporarily unavailable
2021-03-18T12:35:44.064Z | ubuntu.1804.amd64.open.rt | System.Net.Http.HttpRequestException : Resource temporarily unavailable   (corefx-net-http11.azurewebsites.net:443)\n----   System.Net.Sockets.SocketException : Resource temporarily unavailable
2021-03-18T12:35:44.064Z | ubuntu.1804.amd64.open.rt | System.Net.Http.HttpRequestException : Resource temporarily unavailable   (corefx-net-http11.azurewebsites.net:80)\n----   System.Net.Sockets.SocketException : Resource temporarily unavailable
2021-03-18T12:35:44.064Z | ubuntu.1804.amd64.open.rt | System.Net.Http.HttpRequestException : Resource temporarily unavailable   (corefx-net-http11.azurewebsites.net:80)\n----   System.Net.Sockets.SocketException : Resource temporarily unavailable

**Comment by karelz** [comment]
Duplicate of #45269
