### ISSUE TITLE
Null ref in System.Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#45317]
Looks to most be on 32 bit Windows

Seen in https://github.com/dotnet/runtime/pull/45303 and https://github.com/dotnet/runtime/pull/45305 and https://github.com/dotnet/runtime/pull/45292

runtime (Libraries Test Run release coreclr windows x86 Release) 
```
System.Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue

Error message
System.ArgumentNullException : Value cannot be null. (Parameter 'type')

Stack trace
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/IntrospectionExtensions.cs:line 11
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 186
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Where.cs:line 391
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer) in /_/src/libraries/System.Linq/src/System/Linq/Contains.cs:line 23
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value) in /_/src/libraries/System.Linq/src/System/Linq/Contains.cs:line 11
   at System.Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue() in /_/src/libraries/System.Text.Encodings.Web/tests/UnicodeHelpersTests.cs:line 107
```
Also
 https://github.com/dotnet/runtime/pull/45310; again on `(Libraries Test Run release coreclr windows x86 Release)` 

`Fatal error. 0xC0000005` https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45310-merge-f380f19a901d423e93/System.Text.Encodings.Web.Tests/console.31ef414e.log?sv=2019-07-07&se=2020-12-19T16%3A41%3A38Z&sr=c&sp=rl&sig=J6tmdBZJgh2VxjCYoed1fJlnVURu6wUExNd29SkhlgU%3D

```
C:\h\w\A748094D\w\9B3408E2\e>"C:\h\w\A748094D\p\dotnet.exe" exec --runtimeconfig System.Text.Encodings.Web.Tests.runtimeconfig.json --depsfile System.Text.Encodings.Web.Tests.deps.json xunit.console.dll System.Text.Encodings.Web.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.Encodings.Web.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Encodings.Web.Tests (found 181 test cases)
  Starting:    System.Text.Encodings.Web.Tests (parallel test collections = on, max threads = 2)
Fatal error. 0xC0000005
   at System.Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface(Void*, System.Object)
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)
   at Xunit.Sdk.AssertEqualityComparer`1+<>c[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<IsSet>b__10_0(System.Type)
   at System.Linq.Enumerable+SelectArrayIterator`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable.Contains[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at System.Linq.Enumerable.Contains[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon)
   at Xunit.Sdk.AssertEqualityComparer`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].IsSet(System.Reflection.TypeInfo)
   at Xunit.Sdk.AssertEqualityComparer`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CheckIfSetsAreEqual(System.__Canon, System.__Canon, System.Reflection.TypeInfo)
   at Xunit.Sdk.AssertEqualityComparer`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Equals(System.__Canon, System.__Canon)
   at Xunit.Assert.Equal[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.__Canon, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Xunit.Assert.Equal[[System.Byte, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<Byte>, System.Collections.Generic.IEnumerable`1<Byte>)
   at System.Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue()
...
```

**Comment by tarekgh** [comment]
CC @GrabYourPitchforks

**Comment by benaadams** [comment]
For the second more detailed trace, this looks problematic?
```
Fatal error. 0xC0000005
   at System.Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface(Void*, System.Object)
```

**Comment by benaadams** [comment]
Failure lines prior/related to `IsInstanceOfInterface`

https://github.com/dotnet/runtime/blob/c1b5ac004773ae5b103acaad8fdb1e194321aff5/src/libraries/System.Private.CoreLib/src/System/Reflection/IntrospectionExtensions.cs#L13-L14

**Comment by GrabYourPitchforks** [comment]
Steve theorized in the other thread that this might be a crossgen issue. Waiting for that investigation to pan out.

**Comment by benaadams** [comment]
The Xunit Linq usage [triggering it](https://github.com/xunit/assert.xunit/blob/7e0022ae9661014e16bd42cc5ac343a743e1ee72/Sdk/AssertEqualityComparer.cs#L330-L337) is `IsSet`
```csharp
bool IsSet(TypeInfo typeInfo)
{
	return typeInfo.ImplementedInterfaces
		.Select(i => i.GetTypeInfo())
		.Where(ti => ti.IsGenericType)
		.Select(ti => ti.GetGenericTypeDefinition())
		.Contains(typeof(ISet<>).GetGenericTypeDefinition());
}
```
Which then does match the longer `Fatal error. 0xC0000005` stack trace (sanitized) /cc @stephentoub 
```
    at Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface(Void*, Object)
    at Reflection.IntrospectionExtensions.GetTypeInfo(Type)
--> at Xunit.Sdk.AssertEqualityComparer`1+<>c[__Canon].<IsSet>b__10_0(Type)
    at Linq.Enumerable+SelectArrayIterator`2[__Canon,__Canon].MoveNext()
    at Linq.Enumerable+WhereSelectEnumerableIterator`2[__Canon,__Canon].MoveNext()
    at Linq.Enumerable.Contains[__Canon](IEnumerable`1<__Canon>, __Canon, IEqualityComparer`1<__Canon>)
    at Linq.Enumerable.Contains[__Canon](IEnumerable`1<__Canon>, __Canon)
    at Xunit.Sdk.AssertEqualityComparer`1[__Canon].IsSet(Reflection.TypeInfo)
    at Xunit.Sdk.AssertEqualityComparer`1[__Canon].CheckIfSetsAreEqual(__Canon, __Canon, Reflection.TypeInfo)
    at Xunit.Sdk.AssertEqualityComparer`1[__Canon].Equals(__Canon, __Canon)
    at Xunit.Assert.Equal[__Canon](__Canon, __Canon, IEqualityComparer`1<__Canon>)
    at Xunit.Assert.Equal[Byte](IEnumerable`1<Byte>, IEnumerable`1<Byte>)
    at Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue()    
```

**Comment by stephentoub** [comment]
> The Xunit Linq usage triggering it is IsSet

Thanks for tracking that down.

**Comment by stephentoub** [comment]
> Steve theorized in the other thread that this might be a crossgen issue. Waiting for that investigation to pan out.

Looking at Kusto data, this test has failed 50 times, with the earliest failure being at 2020-11-27T15:34:50.565Z, which is very close to the time the crossgen change was merged.

**Comment by stephentoub** [comment]
We can try running its tests again, but #45320 reverts #44618 and passed the leg that's failing elsewhere.

**Comment by benaadams** [comment]
Guessing some of these failures are related too; though different callsites and stacks

* https://github.com/dotnet/runtime/issues/45329 windows.x86.Checked `at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes` `Value cannot be null` 
* https://github.com/dotnet/runtime/issues/45330 windows.x86.Checked `MethodTable::Validate` `Assert failure SanityCheck()`
* https://github.com/dotnet/runtime/issues/45333 windows.x86.Checked `BasicClassFactory.GetValidatedInterfaceType` `System.NullReferenceException`
* https://github.com/dotnet/runtime/issues/45335 windows.x86.Checked `Object::ValidateInner` `corrupted OBJECTREF`
* https://github.com/dotnet/runtime/issues/45336 windows x86 Checked System.InvalidOperationException: Type 'IDynamicInterfaceCastableTests.ITestImpl' returned by IDynamicInterfaceCastable does not implement the requested interface 'IDynamicInterfaceCastableTests.ITest'
* https://github.com/dotnet/runtime/issues/45337 windows x86 Checked `<GetMessageTypes>b__4_0(System.Type)` `Fatal error. 0xC0000005`

**Comment by danmosemsft** [comment]
Maybe this worrying one also? I guess we will see
```
System.FormatException : The string 'nit\xunit\src\xunit.executio' was not recognized as a valid DateTime. There is an unknown word starting at index '0'.


Stack trace
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles) in /_/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeParse.cs:line 2424
   at System.DateTime.Parse(String s) in /_/src/libraries/System.Private.CoreLib/src/System/DateTime.cs:line 1143
   at System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.ValidateSystemInfo(XmlDocument document, String eventId, TraceEventType eventType, DateTime date, TraceEventCache eventCache) in /_/src/libraries/System.Diagnostics.TextWriterTraceListener/tests/XmlWriterTraceListenerTests.cs:line 497
   at System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_NullDataParams() in /_/src/libraries/System.Diagnostics.TextWriterTraceListener/tests/XmlWriterTraceListenerTests.cs:line 304
```

**Comment by v-haren** [comment]
failed again in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902287&view=ms.vss-test-web.build-test-results-tab&runId=28812876&resultId=160987&paneView=debug

failed test: System.Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue

net6.0-windows-Release-x86-CoreCLR_checked-jitminopts-Windows.10.Amd64.Open


Error message
~~~
System.ArgumentNullException : Value cannot be null. (Parameter 'type')

Stack trace
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/IntrospectionExtensions.cs:line 11
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 186
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Where.cs:line 391
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer) in /_/src/libraries/System.Linq/src/System/Linq/Contains.cs:line 23
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value) in /_/src/libraries/System.Linq/src/System/Linq/Contains.cs:line 11
   at System.Text.Encodings.Web.Tests.UnicodeHelpersTests.GetUtf8RepresentationForScalarValue() in /_/src/libraries/System.Text.Encodings.Web/tests/UnicodeHelpersTests.cs:line 107
~~~

**Comment by GrabYourPitchforks** [comment]
Fixed by https://github.com/dotnet/runtime/pull/45320
