### ISSUE TITLE
Test failure: JIT\\Performance\\CodeQuality\\Serialization\\Serialize\\Serialize.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45329]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902349&view=ms.vss-test-web.build-test-results-tab&runId=28814280&resultId=102650&paneView=debug

failed tests:
JIT\\Performance\\CodeQuality\\Serialization\\Serialize\\Serialize.cmd
JIT\\Performance\\CodeQuality\\Serialization\\Deserialize\\Deserialize.cmd

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

Error message
~~~
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'attributeProvider')
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes(Object attributeProvider, Type attributeType, Boolean inherit)
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes[T](Object attributeProvider, Boolean inherit)
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttribute[T](Object attributeProvider, Boolean inherit)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute[T](Type type)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute[T](Object provider)
   at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) in //src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1143
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreatePrimitiveContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) in //src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1143
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Serialization.JsonBenchmarks.SerializeJsonNetBinaryBenchInner(Object o, MemoryStream ms)
   at Serialization.JsonBenchmarks.SerializeJsonNetBinaryBench()
   at Serialization.JsonBenchmarks.SerializeObject()
   at Serialization.JsonBenchmarks.Main()

Return code:      1
Raw output file:      C:\h\w\AE8D094B\w\AD200960\e\JIT\Performance\Reports\JIT.Performance\CodeQuality\Serialization\Serialize\Serialize.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AE8D094B\p\corerun.exe" Serialize.dll 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AE8D094B\p
> C:\h\w\AE8D094B\w\AD200960\e\JIT\Performance\CodeQuality\Serialization\Serialize\Serialize.cmd
Expected: True
Actual:   False

Stack trace
   at JIT_Performance._CodeQuality_Serialization_Serialize_Serialize_._CodeQuality_Serialization_Serialize_Serialize_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\JIT.Performance\JIT.Performance.XUnitWrapper.cs:line 8285
~~~

**Comment by layomia** [comment]
Appears related to https://github.com/dotnet/runtime/issues/45317 and fixed by https://github.com/dotnet/runtime/pull/45320.
