### ISSUE TITLE
Test failure: Interop\\COM\\Activator\\Activator\\Activator.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45333]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902349&view=ms.vss-test-web.build-test-results-tab&runId=28814280&resultId=108922&paneView=debug

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

Error message
~~~
Return code:      1
Raw output file:      C:\h\w\AE8D094B\w\9F74090D\e\Interop\COM\Reports\Interop.COM\Activator\Activator\Activator.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AE8D094B\p\corerun.exe" Activator.dll 
Running InvalidInterfaceRequest...
Running ClassNotRegistered...
Running NonrootedAssemblyPath...
Running ValidateAssemblyIsolation...
Running ValidateUserDefinedRegistrationCallbacks...
Validating ValidRegistrationTypeCallbacks...
Test Failure: System.NullReferenceException: Object reference not set to an instance of an object.
   at Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.GetValidatedInterfaceType(Type classType, Guid& riid, Object outer)
   at Internal.Runtime.InteropServices.ComActivator.BasicClassFactory.CreateInstance(Object pUnkOuter, Guid& riid, IntPtr& ppvObject)
   at Activator.Program.ValidateUserDefinedRegistrationCallbacks() in /__w/1/s/src/tests/Interop/COM/Activator/Program.cs:line 186
   at Activator.Program.Main(String[] doNotUse) in /__w/1/s/src/tests/Interop/COM/Activator/Program.cs:line 266
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AE8D094B\p
> C:\h\w\AE8D094B\w\9F74090D\e\Interop\COM\Activator\Activator\Activator.cmd
Expected: True
Actual:   False

Stack trace
   at Interop_COM._Activator_Activator_Activator_._Activator_Activator_Activator_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 153
~~~

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/runtime/pull/45320
