### ISSUE TITLE
Test failure: Interop\\IDynamicInterfaceCastable\\IDynamicInterfaceCastable\\IDynamicInterfaceCastable.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45336]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902349&view=ms.vss-test-web.build-test-results-tab&runId=28814280&resultId=108933&paneView=debug

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

Error message
~~~
Return code:      1
Raw output file:      C:\h\w\AE8D094B\w\9F74090D\e\Interop\IDynamicInterfaceCastable\Reports\Interop.IDynamicInterfaceCastable\IDynamicInterfaceCastable\IDynamicInterfaceCastable.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AE8D094B\p\corerun.exe" IDynamicInterfaceCastable.dll 
Running ValidateBasicInterface
 -- Validate cast
 -- Validate method call
 -- Validate method call which calls methods using 'this'
Test Failure: System.InvalidOperationException: Type 'IDynamicInterfaceCastableTests.ITestImpl' returned by IDynamicInterfaceCastable does not implement the requested interface 'IDynamicInterfaceCastableTests.ITest'.
   at IDynamicInterfaceCastableTests.ITest.CallImplemented(ImplementationToCall toCall)
   at IDynamicInterfaceCastableTests.Program.ValidateBasicInterface() in /__w/1/s/src/tests/Interop/IDynamicInterfaceCastable/Program.cs:line 299
   at IDynamicInterfaceCastableTests.Program.Main() in /__w/1/s/src/tests/Interop/IDynamicInterfaceCastable/Program.cs:line 477
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AE8D094B\p
> C:\h\w\AE8D094B\w\9F74090D\e\Interop\IDynamicInterfaceCastable\IDynamicInterfaceCastable\IDynamicInterfaceCastable.cmd
Expected: True
Actual:   False

Stack trace
   at Interop_IDynamicInterfaceCastable._IDynamicInterfaceCastable_IDynamicInterfaceCastable_._IDynamicInterfaceCastable_IDynamicInterfaceCastable_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\Interop.IDynamicInterfaceCastable\Interop.IDynamicInterfaceCastable.XUnitWrapper.cs:line 153
~~~

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/runtime/pull/45320
