### ISSUE TITLE
Test failure: Interop\\ICustomMarshaler\\Primitives\\ICustomMarshaler_TargetWindows\\ICustomMarshaler_TargetWindows.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45337]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902349&view=ms.vss-test-web.build-test-results-tab&runId=28814282&resultId=100171&paneView=debug

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open

Error message
~~~
Fatal error. 0xC0000005
   at Xunit.OptimizedRemoteMessageSink+<>c.<GetMessageTypes>b__4_0(System.Type)
   at System.Linq.Enumerable+SelectArrayIterator2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
 at System.Collections.Generic.HashSet1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].UnionWith(System.Collections.Generic.IEnumerable1<System.__Canon>)
 at System.Collections.Generic.HashSet1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.Collections.Generic.IEnumerable1<System.__Canon>, System.Collections.Generic.IEqualityComparer1<System.__Canon>)
   at Xunit.OptimizedRemoteMessageSink.GetMessageTypes(Xunit.Abstractions.IMessageSinkMessage)
   at Xunit.OptimizedRemoteMessageSink.OnMessage(Xunit.Abstractions.IMessageSinkMessage)
   at Xunit.Sdk.MessageBus.DispatchMessages()
   at Xunit.Sdk.MessageBus.ReporterWorker()
   at Xunit.Sdk.XunitWorkerThread+<>c.<QueueUserWorkItem>b__5_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__278_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

Return code:      1
Raw output file:      C:\h\w\B2420974\w\BF090A08\e\Interop\ICustomMarshaler\Reports\Interop.ICustomMarshaler\Primitives\ICustomMarshaler_TargetWindows\ICustomMarshaler_TargetWindows.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B2420974\p\corerun.exe" ICustomMarshaler_TargetWindows.dll 
Discovering...
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B2420974\p
> C:\h\w\B2420974\w\BF090A08\e\Interop\ICustomMarshaler\Primitives\ICustomMarshaler_TargetWindows\ICustomMarshaler_TargetWindows.cmd
Expected: True
Actual:   False

Stack trace
   at Interop_ICustomMarshaler._Primitives_ICustomMarshaler_TargetWindows_ICustomMarshaler_TargetWindows_._Primitives_ICustomMarshaler_TargetWindows_ICustomMarshaler_TargetWindows_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\Interop.ICustomMarshaler\Interop.ICustomMarshaler.XUnitWrapper.cs:line 367
~~~

**Comment by AaronRobinsonMSFT** [comment]
Fixed with https://github.com/dotnet/runtime/pull/45320
