### ISSUE TITLE
[wasm][tests] System.ServiceModel.Syndication.Tests.Atom10FeedFormatterTests.Write_EmptyFeed_SerializesExpected

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#45435]
Failing test seen on PR builds (https://dev.azure.com/dnceng/public/_build/results?buildId=898196&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c):

```
[17:01:51] fail: [FAIL] System.ServiceModel.Syndication.Tests.Atom10FeedFormatterTests.Write_EmptyFeed_SerializesExpected
[17:01:51] info: Assert.True() Failure
[17:01:51] info: Expected: True
[17:01:51] info: Actual:   False
[17:01:51] info:    at System.ServiceModel.Syndication.Tests.Atom10FeedFormatterTests.Write_EmptyFeed_SerializesExpected()
[17:01:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:01:55] info: e(reader: null, version: null)
[17:01:55] info: ation.Tests.AtomPub10ServiceDocumentFormatterTests.Ctor_GenericDefault
```

**Comment by radical** [comment]
I couldn't reproduce this locally. And I didn't find another instance of this. Closing.
