### ISSUE TITLE
[browser][websockets][tests] Tests for CloseDescription Max Length are failing

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#45531]
There seems to be a max length verification for the websocket close description that browser is not checking for.

The tests are expecting an exception but the browser websocket implementation does not throw an exception.

```
 fail: [FAIL] System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CloseDescriptionIsMaxLengthPlusOne_ThrowsArgumentException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
  info: Assert.Throws() Failure
  info: Expected: typeof(System.ArgumentException)
  info: Actual:   (No exception was thrown)
  info:    at System.AssertExtensions.Throws[ArgumentException](String expectedParamName, Action action)
  info:    at System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CloseDescriptionIsMaxLengthPlusOne_ThrowsArgumentException(Uri server)
  info: --- End of stack trace from previous location ---

```

See https://github.com/dotnet/runtime/pull/45470 for tests

**Comment by kjpou1** [comment]
The validation is there but the exception is not be propagated to the unit test https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/BrowserWebSockets/BrowserWebSocket.cs#L460
