### ISSUE TITLE
DataContractSerializer is not trimming safe

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#45559]
Following code works today with linker enabled for SDK **and** user code but breaks with netcore libraries

```c#
public class Test
{
	// [Test]
	public static string SerializeSearchRequestWithDictionary ()
	{
		var req = new SearchRequest () {
			Query = "query",

			Users = new List<string> () {
				"user_a", "user_b"
			},

			Filters = new List<string> () {
				"filter_a", "filter_b"
			},

			Parameters = new Dictionary<string, string> () {
				{ "param_key_b", "param_value_a" },
				{ "param_key_a", "param_value_b" },
			}
		};

		using (MemoryStream memoryStream = new MemoryStream ()) {
			var dataContractSerializer = new DataContractSerializer (typeof (SearchRequest));
			dataContractSerializer.WriteObject (memoryStream, req);
			string serializedDataContract = Encoding.UTF8.GetString (memoryStream.ToArray (), 0, (int) memoryStream.Length);
		}
	}
}

[DataContract]
public class SearchRequest
{
	[DataMember]
	public string Query { get; set; }
	[DataMember]
	public List<string> Users { get; set; }
	[DataMember]
	public List<string> Filters { get; set; }
	[DataMember]
	public Dictionary<string, string> Parameters { get; set; }
}
```

Exception is thrown at runtime

```
System.Runtime.Serialization.InvalidDataContractException: NoGetMethodForProperty, LinkTestLib.SearchRequest, Query
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message)
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers()
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type)
   at System.Runtime.Serialization.ClassDataContract..ctor(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(Type type)
   at System.Runtime.Serialization.DataContractSerializer.get_RootContract()
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteStartObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
   at Test.SerializeSearchRequestWithDictionary()
```

@eerhardt @vitek-karas

**Comment by eerhardt** [comment]
> works today with linker enabled for SDK and user code

Do we know how/why it works today? No code is referencing the `SearchRequest.Query` property, so how is the linker working today on it? Why isn't the property getting trimmed when not using the netcore libraries?

**Comment by marek-safar** [comment]
> Do we know how/why it works today?

There are different [custom linker steps](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveRuntimeSerialization.cs) which are trying to guess what should be kept based on some heuristic.

**Comment by eerhardt** [comment]
I don't believe this is going to be possible without more features from the ILLinker. We could make the exact scenario above work with the current `[DynamicallyAccessedMembers]` attribute. But as soon as `SearchRequest` has a property to another class, it will break again.

This issue is blocked by getting a serialization story in the ILLinker (https://github.com/mono/linker/issues/1087), or implementing a source generator for DCS (#43545).

cc @MichalStrehovsky  @mconnew

**Comment by MichalStrehovsky** [comment]
If I'm reading the code in MonoDroid.Tuner right, the heuristic basically relies on the DataContract/DataMember attributes to decide what to keep. Those attributes are not mandatory - you can drop them and the DCS will do the same thing for this class. But I assume MonoDroid.Tuner is going to break it the same as NetCore linker.

We'll need to decide how we want to treat "regression in a unit test" vs "regression in a scenario". This is a regression in a unit test, but I would assume the _scenario_ (DCS) doesn't work either way.

**Comment by marek-safar** [comment]
> This is a regression in a unit test, but I would assume the scenario (DCS) doesn't work either way.

Original customer issue is here https://bugzilla.xamarin.com/show_bug.cgi?id=36250

**Comment by MichalStrehovsky** [comment]
> Original customer issue is here https://bugzilla.xamarin.com/show_bug.cgi?id=36250

Thanks!

```
System.MissingMethodException

Constructor on type 'System.Runtime.Serialization.CollectionDataContract+GenericDictionaryEnumerator`2[[System.String, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.
```

The customer actually hit a different issue and this kind of looks like one of those in the bucket of: "can't solve this without introducing `DynamicallyAccessedMemberKinds.DataContractSerializer` and specializing the DCS rules in the linker" - they hit this without aggressive treeshaking of user code. The unit test happens to pass with aggressive treeshaking of user code because of how the fix was made but it wasn't the original bug report.

**Comment by jeffschwMSFT** [comment]
@StephenMolloy if this is not serialization, do you have a recommendation?

**Comment by eerhardt** [comment]
Given https://github.com/dotnet/linker/issues/1087 is closed as "not planned", and the plan on making `Full` trimming the default (https://github.com/dotnet/sdk/pull/26246) I believe this issue should be Closed. The API above is marked as `RequiresUnreferencedCode`, which means the app developer will get a trim warning that the code won't work with trimming.

**Comment by MichalStrehovsky** [comment]
> Given [dotnet/linker#1087](https://github.com/dotnet/linker/issues/1087) is closed as "not planned", and the plan on making `Full` trimming the default ([dotnet/sdk#26246](https://github.com/dotnet/sdk/pull/26246)) I believe this issue should be Closed. The API above is marked as `RequiresUnreferencedCode`, which means the app developer will get a trim warning that the code won't work with trimming.

This was actually fixed by grandfathering the MonoDroid behavior under a switch that Xamarin opts into. It doesn't make DCS trimming safe, but usable if you follow the very specific golden path that historically worked in Xamarin: https://github.com/dotnet/linker/blob/main/docs/serialization.md

https://github.com/dotnet/linker/issues/1087 would not solve the general DCS serialization patterns either.
