### ISSUE TITLE
WinRT bug: System.InvalidOperationException:“Attempt to update previously set global instance.”

### ISSUE THREAD

**Issue by taooceros** [dotnet/runtime#45632]
### Description

When calling the new PackageManager(), this error throw. 

### Configuration
Using .Net 5 with TargetFramework net5.0-windows10.0.19041.0.
The windows OS version is 20H2 x64.

### Regression?

Not sure, but .net core 3.1 with the Windows.SDK.Contract works well.

#### StackTrace

```
   at System.Runtime.InteropServices.ComWrappers.RegisterForTrackerSupport(ComWrappers instance)
   at WinRT.ComWrappersSupport.get_ComWrappers()
   at WinRT.ComWrappersSupport.TryRegisterObjectForInterface(Object obj, IntPtr thisPtr)
   at WinRT.ComWrappersSupport.RegisterObjectForInterface(Object obj, IntPtr thisPtr)
   at Windows.Management.Deployment.PackageManager..ctor()
   at Flow.Launcher.Plugin.Program.Programs.UWP.CurrentUserPackages() in D:\Document\Dotnet\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Program\Programs\UWP.cs:line 200
   at Flow.Launcher.Plugin.Program.Programs.UWP.All() in D:\Document\Dotnet\Flow.Launcher\Plugins\Flow.Launcher.Plugin.Program\Programs\UWP.cs:line 156
```

#### Similar bug
https://github.com/microsoft/CsWinRT/issues/394

**Comment by AaronRobinsonMSFT** [comment]
WinRT support is now entirely provided by the C#/WinRT tool chain. The above issue appears to be an problem with usage of the generated API by C#/WinRT. The recommendation is to post issues for WinRT at https://github.com/microsoft/CsWinRT.

See https://github.com/dotnet/runtime/issues/37672

**Comment by taooceros** [comment]
> WinRT support is now entirely provided by the C#/WinRT tool chain. The above issue appears to be an problem with usage of the generated API by C#/WinRT. The recommendation is to post issues for WinRT at https://github.com/microsoft/CsWinRT.
> 
> See https://github.com/dotnet/runtime/issues/37672

Thank you for pointing that out. I will port it to that.
