### ISSUE TITLE
Test failure: Microsoft.Extensions.DependencyInjection.Specification.UnityDependencyInjectionSpecificationTests.ResolvesDifferentInstancesForServiceWhenResolvingEnumerable(serviceType: typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeService), implementation: typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.FakeService), resolve: typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeService), lifetime: Scoped)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45668]
failed in job: [ runtime-coreclr libraries-jitstress 20201205.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=909912&view=ms.vss-test-web.build-test-results-tab&runId=28999044&resultId=125557&paneView=debug)

net6.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.10.Arm64v8.Open

Error message
~~~
System.InvalidOperationException : No service for type 'Microsoft.Extensions.DependencyInjection.IServiceScopeFactory' has been registered.


Stack trace
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs:line 58
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider) in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs:line 73
   at Microsoft.Extensions.DependencyInjection.Specification.DependencyInjectionSpecificationTests.ResolvesDifferentInstancesForServiceWhenResolvingEnumerable(Type serviceType, Type implementation, Type resolve, ServiceLifetime lifetime) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.Specification.Tests/DependencyInjectionSpecificationTests.cs:line 858
~~~

**Comment by maryamariyan** [comment]
Closing as it seems not to have failed since.
