### ISSUE TITLE
Windows PKCS12 import throws "keyset does not exist" with duplicate certs and keys

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#45715]
The following PKCS12 document has two certificates, identical, and two keys, identical, none with a LocalKeyId. It will throw a `CryptographicException` when using a non-ephemeral key set.

<pre>
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist
   at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
   at Internal.Cryptography.Pal.CertificatePal.<>c.<GetRSAPrivateKey>b__67_0(CspParameters csp)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
</pre>

```c#

string contents = @"
MIIQeQIBAzCCEDUGCSqGSIb3DQEHAaCCECYEghAiMIIQHjCCCl8GCSqGSIb3DQEHBqCCClAwggpM
AgEAMIIKRQYJKoZIhvcNAQcBMCQGCiqGSIb3DQEMAQMwFgQQx/veV5kE6ZFqBI/bI/Yc5AICB9CA
ggoQd3vZLJIZc14j53bmYOoie7ZeMrJ3ZKjaCQHFatbsGj2Vi98MLoEao9VkkP+GkLS6HxfwlPcP
lCXRHf9rUIfiCRjFe32PG+X+Q8DfmtREWzvRyLePkj+ylywiJpUoQjmw9rD6OBpPd9Sep9o8sTrd
bGVUE4y2pSFtpQQmvcqYo1H4FPqmdmNW8XhB9ZC7106xzBb8Bk588JGLV/gLe1N+Lfj0ix82TAhf
K/ZN9jBl/PzYhezhPl3Ev1m00uYHigAVbnAdZ3wmVbAx1YF1vj22X0C5ea89ZRVL6Dd3LWdoMK2/
kfPm/Bso7bmRwJ5GC8FyV4zECSM8vmrQeJiieItjVmsUN+1hkzLAJ4A5vyuODrJ+R+AOGnFHz3JU
RLK4nvRELGgtXuq9jkim1UreDvhRTJamiQna5HnbfZSYolhxEgVKpxpLOF1srMJewsWX3qsRGb9j
KHcQn6v9UBD1e9ycQBNCRjSpL0O5AvCWd0wjG1BCbkK1/lXkpgXXUs2Wwc1Jf/DFA3bBG5CH//MM
IjDo5fNcUaSSge70HBHCup5z2wTDhxGI3e3eoO+ly9mzSYyEJTJhpXMr16DZDldfoOhQaQ784+dV
sj+KDrTOGJMgWyj9ezs5GMPHMNsPDdRdCWXfa2rDD7K3A3k/xPSzmyqVuoLy7KU0844YkqJAYGhw
yFgx1yccIbEaZgeIcEHwHPL2Wm9b2FSjbtjAUp/1FT887eI3090iY0fnTGr8s1Gn5G5nC9CvHl1L
2+7lBQypNTMWk+FKHngFIt+yVvhenxo+6GUmxj2EAca8Uf00zK3orJn0daBoGOp7cV6BvTT+MMdN
TrsMBbQKnWs7T1oEglanHvnYTdo9Vdk1pL24KbKx6OMa8t0gmnlHeVoMQ8g0mfHdY5Wl6zyta1AF
GmWGLYgPzKRZweyxmyPOWpkXsKw6r4jKbvo/hOHLAH2C0q59irZEce/VvdihfNhCOnVUz2xdFHF1
yMWKvsikTTD11ZK6pAdyIf1EyvSb4cKScknf6afA1w5jpVZl/EAbHTk7tfgGxg6Ygwb5pJASiAVY
1VAu7tSDEOA9psejKmZaNaCsr8uEEiYchr5+wWGttwT1Fq2SX8Bk2bmpaZkeUnxbiNDj89W4MmVZ
8K7dj6OMUEAAPDzvJOcLsEZ+EIKiTrwZLlK2fVqFBKjzxUnndszlGoUJfXGSBPLB9lkXVdQvDH/X
Dj2FWwbrfXYN5xGkFN0As8RWx1KqgvT/20ic2/WZpXS6x+VTQB9sQl4mGdZzuUVF/xZYChdc4lIw
/Hevs+cbzXQwznXuyShiq7x/hJwoz3+2GgMkfcVRD22BtDYn5gNf0s9qO/dw6erD6sZ4sLLaYxqW
NCIUk6I++md9BPXBLdt1ZdIf1ZoHBM0XEVC9Jv+daXRNeCrzrZclznEvcwdJsG8TqZSMUc0tEzFW
on5DJzXShcFwFCdwRql39XSARU+Qg0UbQ4an+8UmAuDNesk1ZoWLABRN+76BuU04k4aiE1Vaa8gO
lbxQXaS3WR3/gb46lrc6XTGVKSnR4RwsDheFFuHLiNRTjKFa6gOHrsJH8h7AJwFnd7sjHlUoj2UH
wZvbbbNDCtdcVZCX70pBpp+hgPH8CqoN1Yzukd/rByIH2lHbnhKTSbe8CK7EM4CxoGwfMvKXbysq
4yAh7PNoH2Dz5KlYOIl0zQGUVfr1ihr6RsBEI6v3tkVXo77Z57brk1IcVljR+dS8J9DCX1+uyTSn
0F2qpr+p/X2cJwho8VaMYsK8aF52hm8gdFNLbuyHYWmi0aijOcNeDgaxT0v+eWh2LvNOVQlNXx2w
7kSf5lljfslwKViGCbeI2m5g1yqqvO+65+1+Th7IkV1Z/jbmqwnz6YNWY83jNbdO937iGiuMB6Ml
kk4obesMu/Vc8BYNXW66sOBPghKUbVUciGsOJBa0X2U9XYXCNrmf+55vyOD3c1yjUcwVYEOOde5P
+bxuUR013vgsaqK0YUZdOC/8wYbiRXMluCRIrtWFTPfWk4JaAgmRRmoWHfSHxejM3sIZJQgAqEv6
wjD+4dgVeX+rnZyqIpVVh6spfY4x/0meu/B/arITFZHz/idFRzwxQgA3NX7nP75D5gEeCKMpXNgr
uZ+jxSJdUCTLttlakYDRfccCU3S6dvm24Z+2sOsEjQtsJqyJTY/jcAs9ZSKErS4fvk3Bi9BPEPBc
x9JR3UWvIvlLe3dzb3s2or0PoS5ZNo+CUZRjWVLjSfkit0BJfwRl5HYuO5Xi0zA7p3v3ZLQR87i6
z9YbyQyxWcRYJN5Js42OUBQQTZEEvpKSBO0Qq4EXkA/eWZs5rwZwjGAB3p+S/XRmd0RLmCfCB4RQ
Y+Rw66/hZ0+IDn1ss6sCamzAkj8S83s4mMlPO2T8gfGmtyTbjCz9tP93Qga7MxgcyZ5PvjYTXl/K
wHiWQNJm4AuJWPPJhLd1ctQIBXaJVWFJRKydVFSMBUXxJhgLKhTQlGLPIhuaRfFpINAm1qTFRChR
tM3+OPGikupkoub9/f0oPHFOo6L5D+AUBU718HivYfXf4e2QqgDrr3nSCWHy5srEDBpNxsFVNEOI
vZt8ioOCXOs8g4Z9le5Ot6xN1Nyt5f2on9HSV/LDsmDld0vGRX9wWXXKARvGyulcHRG1mi0uEsE5
HBBILNwq+/yuWlTb2x2SH7LycdFlxK7LtzEoQ5HZcD5qjRHv8yoUWNrmlbH4yKCFTxofMgWnDqvy
xnNSisUyk8q18WiSF48NW9Bd9+x/2JroydFA15rH6ug1IWNoxfsNLCEJX8oxmrXIK2bRo3eCSX+4
Sr3KK3CURk7KMiY/ljysQPkhluApvUNiKn5AbARye8SGad/POtmjt6RfGRT8VWUBixcmgqgEmEId
FilQXXMDkcVgmNwHg44Z398KnRj8xZY62GKmvt5QY2cghc6aN6kUAwb33oEG5dV1AB6wtWjG1ff9
dz+GUvkzYklCtr+tGUwbvGxiYKuetzdzRqlsbj+ekBb2vHWiFovVFDmAN0KI2lUV8MUOmXf8339E
82f+UDaFNYgfrgUj0wARb49LTG8JtXG41pQEJPzrsEXJNCI6d4NZrUqaDzBlpqGBMi3bzf3ThgNw
7Af07MchzKRzRE9rlVYJ7+Vt85scjR4bHP1+rqaQt8e0JX1lpEUHsVb0eEMLhsmpn1jo0q7AlZXH
y6erVjxLh0XDWogiQPxFfVyZTOxuutA+iI8SIsVMa54QUWWIBYxIJxwvJc7ujCYiJ0zZE1btgjDv
Oqv9T5b1ThbG4sDgpXGoA+0eukOvVwzIm/VhpCT4lxaaoG/lpeycyyWm+8WvVNRvZnx0meuEpk5A
6rbsx394emCHS3Awdj+0GFAPzLu18YdLbL1k7CmJH/ZsA5L1yOIwbMUezYQaJpXglvGYbQ0F0+qP
aqzkO3osQHacNrttfocwggW3BgkqhkiG9w0BBwGgggWoBIIFpDCCBaAwggLMBgsqhkiG9w0BDAoB
A6CCArswggK3BgoqhkiG9w0BCRYBoIICpwSCAqMwggKfMIIBh6ADAgECAgkAy6xshn5HCY0wDQYJ
KoZIhvcNAQELBQAwDzENMAsGA1UEAxMEYmxhaDAeFw0yMDEyMDcyMTI2MTBaFw0yMDEyMDcyMTI2
MTBaMA8xDTALBgNVBAMTBGJsYWgwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvu3r7
TLsHu5Xn4LxW8m4quFWQjbKqxxHKq50OB+Tr35VF6IFNpwEcBOSjrqCWVyFx6DgovyHrRrfljSeD
fgZCg0IbFMwvAtfEDv0fawsCq5GNwS5a1DjVRdP03WQEbyVnZ4VeeoyveCQOvcJY63vCDbDPNT0M
HKDv/Rh6OUjzpW5OJfutigE1a/sOJVwrV/WXQ9RpvuIKd9rHqwD/Q5IogsT1uXOhfUqDlCrKakoc
XDQTpKwnIgadErTFHz63GygiIgB2bL8ptFkVB3lNxhS4mLOjauGgF/t3wV5h+loLJ4rT3dyC+uj6
qWthZb4DdMh+ANS9LfSm0oW8dl8KLgXtAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAHjgBczAGr8m
rfP9lzcPcxRy/iQJR/tECQDBku8Q/nMvWIM49j50cPh5SGv+x6Z4xpJisshSSN1/v0LcuoOkJJLr
ifkTpLoV2kkmwzluTff6nm8E1IArgXyHEm2QXAwakV1LuYxU43BrQzS/FIb7b768N/Cs1MtcTznq
7ej+PtQKGBvHBw2jLH02w1nx4Qafrw44dtDoJe/8nyL1VuStaDVpH+IP/RmwsC3nDGsTM/MdHT7X
crSFJmSi66HRBufZBpcuDcOpktsUs/pMYmFD/nwWdKAcjIFW/FtmqnvE/nwA/VGw9mNEws3ZUZwJ
Ea0eTk+G5hlPbrLzBo2GDJxK8BowggLMBgsqhkiG9w0BDAoBA6CCArswggK3BgoqhkiG9w0BCRYB
oIICpwSCAqMwggKfMIIBh6ADAgECAgkAy6xshn5HCY0wDQYJKoZIhvcNAQELBQAwDzENMAsGA1UE
AxMEYmxhaDAeFw0yMDEyMDcyMTI2MTBaFw0yMDEyMDcyMTI2MTBaMA8xDTALBgNVBAMTBGJsYWgw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvu3r7TLsHu5Xn4LxW8m4quFWQjbKqxxHK
q50OB+Tr35VF6IFNpwEcBOSjrqCWVyFx6DgovyHrRrfljSeDfgZCg0IbFMwvAtfEDv0fawsCq5GN
wS5a1DjVRdP03WQEbyVnZ4VeeoyveCQOvcJY63vCDbDPNT0MHKDv/Rh6OUjzpW5OJfutigE1a/sO
JVwrV/WXQ9RpvuIKd9rHqwD/Q5IogsT1uXOhfUqDlCrKakocXDQTpKwnIgadErTFHz63GygiIgB2
bL8ptFkVB3lNxhS4mLOjauGgF/t3wV5h+loLJ4rT3dyC+uj6qWthZb4DdMh+ANS9LfSm0oW8dl8K
LgXtAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAHjgBczAGr8mrfP9lzcPcxRy/iQJR/tECQDBku8Q
/nMvWIM49j50cPh5SGv+x6Z4xpJisshSSN1/v0LcuoOkJJLrifkTpLoV2kkmwzluTff6nm8E1IAr
gXyHEm2QXAwakV1LuYxU43BrQzS/FIb7b768N/Cs1MtcTznq7ej+PtQKGBvHBw2jLH02w1nx4Qaf
rw44dtDoJe/8nyL1VuStaDVpH+IP/RmwsC3nDGsTM/MdHT7XcrSFJmSi66HRBufZBpcuDcOpktsU
s/pMYmFD/nwWdKAcjIFW/FtmqnvE/nwA/VGw9mNEws3ZUZwJEa0eTk+G5hlPbrLzBo2GDJxK8Bow
OzAfMAcGBSsOAwIaBBS+yvdvf+9G86iP5iH8mphOqNeaRQQU5zwhk8f5Ud9sLIsagnRGGTUJ7z0C
AgfQ";

using X509Certificate2 cert = new X509Certificate2(Convert.FromBase64String(contents), "YabbaDabbaDoo");
_ = cert.GetRSAPrivateKey();
```

Environment:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-alpha.1.20603.2
 Commit:    f2294767a5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by vcsjones** [comment]
Apologies for the bunch of PKCS12 issues, trying to make sure I don't lose track of things.

**Comment by vcsjones** [comment]
Rather, it is not the import that fails, but calling `GetRSAPrivateKey` on the imported certificate.

**Comment by bartonjs** [comment]
Technically we could solve this by ensuring that each key that we're erasing as part of single-cert import doesn't have the same key identifier as the one we're about to produce.  But then we'd need to do something tricky in collection import to try to make the two distinct certificates understand that they have mutual ownership of the key file.

My guess is that we don't really want to do anything here, but maybe this interacts with #48789 in interesting ways.

**Comment by ancaantochi** [comment]
Hi @bartonjs 
I have a similar issue ("Keyset does not exist") when creating X509Certificate2 from pfx and then trying to use the certificate with SSL. The pfx has just a certificate and a private key and this issue only reproduces when I run the application in a docker container (mcr.microsoft.com/dotnet/runtime:3.1.18-nanoserver-1809 as base image). I noticed that it only happens when the container starts and if I retry to create a new certificate after ~200ms it works.
