### ISSUE TITLE
Test failure: Loader\\binding\\tracing\\BinderTracingTest.Basic\\BinderTracingTest.Basic.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45736]
failed in job: [ runtime-coreclr r2r-extra 20201206.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=910264&view=ms.vss-test-web.build-test-results-tab&runId=29007324&resultId=110501&paneView=debug)

R2R windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open

Error message
~~~
Return code:      1
Raw output file:      C:\h\w\971B08A7\w\AFF40960\e\Loader\binding\Reports\Loader.binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
" "C:\h\w\971B08A7\p\crossgen.exe"  /Platform_Assemblies_Paths C:\h\w\971B08A7\p;C:\h\w\971B08A7\w\AFF40960\e\Loader\binding\tracing\BinderTracingTest.Basic /in C:\h\w\971B08A7\w\AFF40960\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.org /out C:\h\w\971B08A7\w\AFF40960\e\Loader\binding\tracing\BinderTracingTest.Basic\\BinderTracingTest.Basic.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image C:\h\w\971B08A7\w\AFF40960\e\Loader\binding\tracing\BinderTracingTest.Basic\\BinderTracingTest.Basic.dll generated successfully.
 "C:\h\w\971B08A7\p\corerun.exe" BinderTracingTest.Basic.dll 
[5:16:32 AM] Running LoadFile...
[5:16:33 AM] Running LoadBytes...
[5:16:33 AM] Running LoadFromStream...
[5:16:33 AM] Running LoadFromAssemblyPath...
[5:16:33 AM] Launching process for LoadFromAssemblyName...
[5:16:34 AM] Running LoadFromAssemblyName...

[5:16:36 AM] Launching process for LoadFrom...
[5:16:36 AM] Running LoadFrom...

[5:16:37 AM] Launching process for PlatformAssembly...
[5:16:38 AM] Running PlatformAssembly...

[5:16:39 AM] Launching process for PlatformAssembly_Cached...
[5:16:40 AM] Running PlatformAssembly_Cached...

[5:16:41 AM] Launching process for Reflection...
[5:16:42 AM] Running Reflection...

[5:16:43 AM] Launching process for Reflection_Cached...
[5:16:44 AM] Running Reflection_Cached...

[5:16:45 AM] Launching process for Reflection_CustomALC...
[5:16:46 AM] Running Reflection_CustomALC...

[5:16:47 AM] Launching process for ContextualReflection_DefaultToCustomALC...
[5:16:48 AM] Running ContextualReflection_DefaultToCustomALC...

[5:16:49 AM] Launching process for ContextualReflection_CustomToDefaultALC...
[5:16:50 AM] Running ContextualReflection_CustomToDefaultALC...

[5:16:51 AM] Launching process for JITLoad...
[5:16:52 AM] Running JITLoad...

[5:16:53 AM] Launching process for JITLoad_CustomALC...
[5:16:54 AM] Running JITLoad_CustomALC...

[5:16:55 AM] Running AssemblyInAppPath...
Test AssemblyInAppPath failed: System.AggregateException: One or more errors occurred. (An error occurred when writing to a listener.)
 ---> System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument) in //src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs:line 12
   at System.Linq.Enumerable.Any[TSource](IEnumerable1 source, Func2 predicate) in //src/libraries/System.Linq/src/System/Linq/AnyAll.cs:line 51
   at BinderTracingTests.BinderEventListener.IsLoadToTrack(String name) in /__w/1/s/src/tests/Loader/binding/tracing/BinderEventListener.cs:line 356
   at BinderTracingTests.BinderEventListener.OnEventWritten(EventWrittenEventArgs data) in /__w/1/s/src/tests/Loader/binding/tracing/BinderEventListener.cs:line 229
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
   --- End of inner exception stack trace ---
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, UInt32* osThreadId, DateTime* timeStamp, Guid* activityID, Guid* childActivityID, Object[] args)
   at System.Dia


Stack trace
   at Loader_binding._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x64.Checked\TestWrappers\Loader.binding\Loader.binding.XUnitWrapper.cs:line 902
~~~

**Comment by hoyosjs** [comment]
We expect all the necessary fixes happened this morning. If this happens again, please re-open.

cc: @sywhang
