### ISSUE TITLE
Test failiure in WebSockets.Client: ArraySegmentSendReceiveTest.SendReceive_VaryingLengthBuffers_Success

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#45773]
### Test case

`System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)`

### Failed on

`net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64`
https://dev.azure.com/dnceng/public/_build/results?buildId=912243&view=ms.vss-test-web.build-test-results-tab

### Error message
`System.Threading.Tasks.TaskCanceledException : The operation was canceled.`

### Stack trace

<details>

```
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1322
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1237
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1330
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 526
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 849
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options) in /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs:line 144
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<>c__DisplayClass4_0.<<GetConnectedWebSocket>b__0>d.MoveNext() in /_/src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs:line 92
--- End of stack trace from previous location ---
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.Retry[T](ITestOutputHelper output, Func`1 func) in /_/src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs:line 108
   at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/SendReceiveTest.cs:line 325
--- End of stack trace from previous location ---
```

<details>

**Comment by karelz** [comment]
No failure between 2/23-5/7 (incl. PRs). Closing.
