### ISSUE TITLE
Test failure: SyncHttpHandler_HttpClientHandlerTest.PostAsync_CallMethod_NullContent

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#45774]
### Test case
`System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandlerTest.PostAsync_CallMethod_NullContent(remoteServer: (BaseUri: http://corefx-net-http11.azurewebsites.net/, HttpVersion: 1.1))(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)`

### Failed on
`net6.0-OSX-Debug-x64-CoreCLR_release-OSX.1015.Amd64.Open`

### Error message
```
System.Net.Http.HttpRequestException : Operation timed out (corefx-net-http11.azurewebsites.net:80)\n---- System.Net.Sockets.SocketException : Operation timed out
```
### Stack trace

<details>

```
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1322
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1237
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1330
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 526
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 849
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 512
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_NullContent(RemoteServer remoteServer) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:line 1949
--- End of stack trace from previous location ---
```
</details>

**Comment by karelz** [comment]
Triage: Looks like external server hiccup. Closing.
