### ISSUE TITLE
failing test: System.Diagnostics.Tests.EventLogSessionTests.ClearLog_LogExists_Success

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#45847]
This is failing on https://github.com/dotnet/runtime/pull/44462 . AFAICS, this isn't related to the PR itself.

```
    System.Diagnostics.Tests.EventLogSessionTests.ClearLog_LogExists_Success [FAIL]
      System.ComponentModel.Win32Exception : Access is denied.
      Stack Trace:
        /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(1402,0): at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
        /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs(1321,0): at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
        /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(1005,0): at System.Diagnostics.EventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData)
        /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs(957,0): at System.Diagnostics.EventLog.WriteEntry(String message)
        /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogSessionTests.cs(96,0): at System.Diagnostics.Tests.EventLogSessionTests.ClearLog_LogExists_Success()
```

https://dnceng.visualstudio.com/public/_build/results?buildId=914224&view=results

console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44462-merge-734e2f430499445e95/System.Diagnostics.EventLog.Tests/console.06c5d2c5.log?sv=2019-07-07&se=2020-12-29T15%3A50%3A32Z&sr=c&sp=rl&sig=k0xDLe8I7mqj58UPi%2FkiYCO2BMwqidG6u7ZklftTgO4%3D

**Comment by tommcdon** [comment]
@krwq

**Comment by VincentBu** [comment]
Failed in run [runtime 20210120.64](https://dev.azure.com/dnceng/public/_build/results?buildId=959032&view=ms.vss-test-web.build-test-results-tab&runId=30229932&resultId=121244&paneView=debug)

Failed test : `System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages`

net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

**Error message:**
```
System.ComponentModel.Win32Exception : Access is denied.


Stack trace
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1396
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1315
   at System.Diagnostics.EventLog.WriteEntry(String source, String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 1016
   at System.Diagnostics.EventLog.WriteEntry(String source, String message) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 979
   at System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogMessagesTests.cs:line 70
```

**Comment by danmosemsft** [comment]
Same configuration, just now: net6.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open
```

Error message
System.ComponentModel.Win32Exception : Access is denied.


Stack trace
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1396
   at System.Diagnostics.EventLogInternal.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs:line 1315
   at System.Diagnostics.EventLog.WriteEntry(String source, String message, EventLogEntryType type, Int32 eventID, Int16 category, Byte[] rawData) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 1016
   at System.Diagnostics.EventLog.WriteEntry(String source, String message) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLog.cs:line 979
   at System.Diagnostics.Tests.EventLogMessagesTests.CanReadAndWriteMessages() in /_/src/libraries/System.Diagnostics.EventLog/tests/EventLogMessagesTests.cs:line 70
```

**Comment by danmosemsft** [comment]
It's always Windows 7
https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2QT0vDQBDF74V%2bhyGXVlhjq%2bBBiFCrhYoVrYUeRGS7OybbP7NhZ6Mt%2bOHdTVqp4CnJy2%2fmvTczZD9Frtaeod36hqU1BCtDOjNE6GBu3WrsccNg6fdjrP9l7%2b2ixsJzrCPwVaBDGBkyXKCG6wzIfnVPLy57%2bqTdkqRhtisRsgySlx2HxemtkTlZ9kZxOgvROL37RPIPNp8gs8yRazVpt87O4vwEfWF1vWEoaYpSD0jPnfF44JPGqOkYwc5ImnWnUffQcYKh3ZSWgufEalync0MX53dbhaU3odoVDJQKQ2AYNJJBnSaxKeDWY1i4ZEtZKR3je3ztPjlbovMG%2bSRie2po6cPklZNxZxbBVB1LAgZOFaGE8pXDBpBHioCnQjI%2byk2IXnu%2bHuL%2f%2fkjeomHp7DLMwI2TpApR31vsrybgucKqhvvicArxN9zfJEe%2bArhasHeG8u6Ll2o1c1IFtSeg3%2buFsu3WDxUeMW5bAgAA&web=0

TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where Finished >= now(-360d)
and Type == "System.Diagnostics.Tests.EventLogMessagesTests"
//and Method == "CanReadAndWriteMessages"
and Result == 'Fail'
and Message == "System.ComponentModel.Win32Exception : Access is denied."
|  extend json=parse_json(Properties)
| extend Configuration=json.configuration, Architecture=json.architecture, PhaseName = json["System.PhaseName"]
| project Branch, Type, Method, QueueName1, Message, Configuration, Architecture, PhaseName, substring(StackTrace, 0, 100)

Branch | Type | Method | QueueName1 | Message | Configuration | Architecture | PhaseName | Column1
-- | -- | -- | -- | -- | -- | -- | -- | --
refs/pull/47311/merge | System.Diagnostics.Tests.EventLogMessagesTests | CanReadAndWriteMessages | windows.7.amd64.open.rt | System.ComponentModel.Win32Exception : Access is denied. | Debug | x86 | libraries_test_run_release_coreclr_windows_x86_Debug | at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventL
refs/heads/master | System.Diagnostics.Tests.EventLogMessagesTests | CanReadAndWriteMessages | windows.7.amd64.open.rt | System.ComponentModel.Win32Exception : Access is denied. | Release | x86 | libraries_test_run_release_coreclr_windows_x86_Release | at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventL
refs/pull/47208/merge | System.Diagnostics.Tests.EventLogMessagesTests | CanReadAndWriteMessages | windows.7.amd64.open.rt | System.ComponentModel.Win32Exception : Access is denied. | Debug | x86 | libraries_test_run_release_coreclr_windows_x86_Debug | at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventL
refs/pull/40887/merge | System.Diagnostics.Tests.EventLogMessagesTests | CanReadAndWriteMessages | windows.7.amd64.open.rt | System.ComponentModel.Win32Exception : Access is denied. | Debug | x86 | libraries_test_run_release_coreclr_windows_x86_Debug | at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventL
refs/pull/46747/merge | System.Diagnostics.Tests.EventLogMessagesTests | CanReadAndWriteMessages | windows.7.amd64.open.rt | System.ComponentModel.Win32Exception : Access is denied. | Debug | x86 | libraries_test_run_release_coreclr_windows_x86_Debug | at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventL

**Comment by danmosemsft** [comment]
This particular line turns out to be missing the usual retry...
