### ISSUE TITLE
[browser][globalization][tests] RegionInfoPropertyTests.DisplayName failures

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#45951]
```
[03:50:22] fail: [FAIL] System.Globalization.Tests.RegionInfoPropertyTests.DisplayName(name: "en-US", expected: "United States")
[03:50:22] info: Assert.Equal() Failure
[03:50:22] info:            â†“ (pos 1)
[03:50:22] info: Expected: United States
[03:50:22] info: Actual:   US
[03:50:22] info:            â†‘ (pos 1)
[03:50:22] info:    at System.Globalization.Tests.RegionInfoPropertyTests.DisplayName(String name, String expected)
[03:50:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

```

Found when executing the [outerloop tests](https://github.com/dotnet/runtime/pull/45949)
```
[OuterLoop("May fail on machines with multiple language packs installed")] // see https://github.com/dotnet/runtime/issues/30132
```

See PR: https://github.com/dotnet/runtime/pull/45949

**Comment by SamMonoRT** [comment]
@radical - is this still an issue we need to fix in .NET6?

**Comment by ilonatommy** [comment]
Neither on runfo nor locally (3 lang packs installed) I cannot see it failing anymore. Planning to remove the comment and close.

**Comment by lewing** [comment]
This is related to what icu subsets are included
