### ISSUE TITLE
[Regression] [Product bug] Test failure: System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(useDnsEndPoint: True)

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#46030]
Same underlying issue as #43931, just a different method.

Example failure:
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   2
   at System.Net.Sockets.Tests.TelemetryTest.VerifyStartStopEvents(ConcurrentQueue`1 events, Boolean connect, Int32 expectedCount) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 396
   at System.Net.Sockets.Tests.TelemetryTest.VerifyConnectFailureEvents(ConcurrentQueue`1 events) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 324
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_ConnectAsyncCanceled_LogsConnectFailed>b__12_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 316
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectAsyncCanceled_LogsConnectFailed>b__12_0(System.String, System.String)

Child arguments:
  Task, True
```

**Comment by MihaZupan** [comment]
Test disabled by #46031.
