### ISSUE TITLE
dotnet-trace needs to work better with apps that has the EventSourceSupport feature switched off

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#46047]
### Description

When an out of proc tracing tool like dotnet-trace is used to collect a trace from an application that has been built with the feature EventSourceSupport turned off, it crashes the application. Also the generated trace file (nettraace.trace) is corrupted.

Repro steps
 - Build a runtime that allows EventSource feature to be turned off. Currently requires, [EventPipe and NativeRuntimeEventSource types](https://github.com/dotnet/runtime/blob/881178effd6fe67565839c809c8c8de0f6d2c554/src/coreclr/src/System.Private.CoreLib/src/ILLink/ILLinkTrim.xml#L9-L11) not to be rooted in corelib.
 - Create a HelloWorld app with the EventSource feature turned off `<EventSourceSupport>false</EventSourceSupport>`
 - Ensure that the app runs for a short time (ex. use Thread.Sleep) so as to mimic dotnet-trace collect
 - publish a trimmed app with libraries linked `<TrimMode>link</TrimMode>` and `<PublishTrimmed>true</PublishTrimmed>`
 - Use dotnet-trace to collect events from this app `(dotnet-trace collect -- <App>.exe)'

### Expected Behavior 
dotnet-trace exits with a message indicating that EventSource is turned off

### Current Behavior

`dotnet-trace collect -- test2.exe
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile

Process        : D:\work\Core\Test\Dec_6\test2\bin\Debug\net5.0\win-x64\publish\test2.exe
Output File    : D:\work\Core\Test\Dec_6\test2\bin\Debug\net5.0\win-x64\publish\trace.nettrace

[00:00:00:01]   Recording trace 0.00     (B)
Press <Enter> or <Ctrl+C> to exit...

Trace completed.`

Reading the generated trace file, nettrace.trace, shows the following stack trace

***** Consider using /ContinueOnError to ignore the bad part of the trace.  *****
Error: Exception EventPipe conversion: System.Exception: Read past end of stream.
   at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
   at FastSerialization.MemoryStreamReader.ReadByte()
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CopyRawEvents(TraceEventDispatcher rawEvents, IStreamWriter writer)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.<>c__DisplayClass120_0.<FastSerialization.IFastSerializable.ToStream>b__0()
   at FastSerialization.DeferedRegion.Write(Serializer serializer, Action toStream)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FastSerialization.IFastSerializable.ToStream(Serializer serializer)
   at FastSerialization.Serializer.WriteObjectData(IFastSerializable obj, Tags beginTag)
   at FastSerialization.Serializer.WriteObjectRef(IFastSerializable obj, Boolean defered)
   at FastSerialization.Serializer..ctor(IStreamWriter writer, IFastSerializable entryObject)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeEventSources(TraceEventDispatcher source, String etlxFilePath, TraceLogOptions options)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeDataFile(String filePath, String etlxFilePath, TraceLogOptions options)
   at PerfView.EventPipePerfViewData.GetTraceLog(TextWriter log, Action`3 onLostEvents

**Comment by josalem** [comment]
> Expected Behavior
dotnet-trace exits with a message indicating that EventSource is turned off

I'm not sure this is something we'll be able to observe external to the application without runtime changes.  More likely I would expect dotnet-trace to receive 0 events and have an empty trace file.  `EventSource` being turned off isn't equivalent to `EventPipe`/`DiagnosticServer` being turned off.

We could add a special event that gets sent in the event we find `EventSource` types to be null at session creation time.  That would give `dotnet-trace` and other readers the ability to know when `EventSource` is turned off/linked out.

**Comment by LakshanF** [comment]
From a team discussion related to #43657

**Comment by mikelle-rogers** [comment]
Attempting to repro this was not successful. I messaged @LakshanF, who could not repro it either. We are closing this issue.
