### ISSUE TITLE
Test Failure System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#46073]
failed again in job: [ runtime-libraries-coreclr outerloop 20201214.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=920179&view=ms.vss-test-web.build-test-results-tab&runId=29240438&resultId=103029&paneView=debug)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   154.1219
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 537
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  2.0
~~~

_Originally posted by @v-haren in https://github.com/dotnet/runtime/issues/41723#issuecomment-745015888_

**Comment by VincentBu** [comment]
Failed again in run [runtime-libraries-coreclr outerloop 20210209.3](https://dev.azure.com/dnceng/public/_build/results?buildId=984912&view=ms.vss-test-web.build-test-results-tab&runId=30853552&resultId=103215&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open
 -System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   103.9025
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 537
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  2.0
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210324.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1054073&view=ms.vss-test-web.build-test-results-tab&runId=32543192&resultId=100408&paneView=debug)

Failed test:
```
net6.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open
 -System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   174.9862
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 537
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  2.0
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210415.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1090156&view=ms.vss-test-web.build-test-results-tab&runId=33415882&resultId=104070&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20200512010618-efb9f14
 -System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 00000012-0000-0000-0000-0000589d9d59
Actual:   00000013-0000-0000-0000-0000279d9d59
   at System.Net.Http.Functional.Tests.TelemetryTest.ValidateSameActivityIds(ValueTuple`2[] a, ValueTuple`2[] b) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 504
   at System.Net.Http.Functional.Tests.TelemetryTest.ValidateStartFailedStopEvents(ConcurrentQueue`1 events, Boolean shouldHaveFailures, Int32 count) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 414
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__11_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 646
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__11_0(System.String)

Child arguments:
  2.0
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210428.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1111562&view=ms.vss-test-web.build-test-results-tab&runId=33890408&resultId=104153&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20200512010618-efb9f14
 -System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 00000012-0000-0000-0000-0000a49d9d59
Actual:   00000013-0000-0000-0000-0000db9d9d59
   at System.Net.Http.Functional.Tests.TelemetryTest.ValidateSameActivityIds(ValueTuple`2[] a, ValueTuple`2[] b) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 504
   at System.Net.Http.Functional.Tests.TelemetryTest.ValidateStartFailedStopEvents(ConcurrentQueue`1 events, Boolean shouldHaveFailures, Int32 count) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 414
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__11_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 646
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__11_0(System.String)

Child arguments:
  1.1
```

**Comment by karelz** [comment]
This issue is still happening after PR #50226 (merged on 4/6), but only in PRs (during 3/11-4/6 the failures were in official builds only).
Note that a new test failure started after the PR was merged: #52530

Failures: 4/7-5/10

Date | Build / PR | HTTP | OS
-- | -- | -- | --
4/8 | PR #48758 | Http11 | OSX.1015.Amd64.Open
4/13 | PR #48758 | Http20 | OSX.1014.Amd64.Open
4/16 | PR #51205 | Http11 | Ubuntu.1804.Amd64.Open
4/18 | PR #51213 | Http11 | OSX.1014.Amd64.Open
4/18 | PR #51212 | Http11 | OSX.1100.ARM64.Open
4/18 | PR #51454 | Http11 | OSX.1100.ARM64.Open
5/3 | PR #52178 | Http11 | OSX.1014.Amd64.Open
5/7 | PR #52178 | Http20 | OSX.1014.Amd64.Open
5/7 | PR #52178 | Http20 | OSX.1014.Amd64.Open
5/7 | PR #52178 | Http11 | OSX.1014.Amd64.Open
5/7 | PR #52178 | Http20 | OSX.1014.Amd64.Open

@MihaZupan should we reopen it or open a new issue, or do you think the PRs caused the failures?

**Comment by antonfirsov** [comment]
Hit in #51094

**Comment by MihaZupan** [comment]
This specific issue is only appearing on OSX (non OSX failures are on release/preview branches that do not have changes from #50226).

We can disable the test on OSX, though I don't see a reason as to why it would be failing in this manner.
