### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SuccessfulRequest_LogsStartStop

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#46075]
failed again in job: [runtime-libraries outerloop 20200903.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=800064&view=ms.vss-test-web.build-test-results-tab&runId=25329596&paneView=debug&resultId=102811)

failed test: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SuccessfulRequest_LogsStartStop(testMethod: \"Send\")

net5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   1
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 467
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulRequest_LogsStartStop>b__3_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 149
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulRequest_LogsStartStop>b__3_0(System.String, System.String)

Child arguments:
  1.1, Send
~~~

_Originally posted by @v-haren in https://github.com/dotnet/runtime/issues/41723#issuecomment-686946261_

**Comment by karelz** [comment]
Triage: @MihaZupan you might want to take a look at this one if it is similar to the larger problems in the area ...

**Comment by VincentBu** [comment]
Failed again in run [runtime-libraries-coreclr outerloop 20210217.1](https://dev.azure.com/dnceng/public/_build/results?buildId=998306&view=ms.vss-test-web.build-test-results-tab&runId=31237660&resultId=103175&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

 -System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SuccessfulRequest_LogsStartStop(testMethod: \"Send\")
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   1
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 514
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_SuccessfulRequest_LogsStartStop>b__3_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 192
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SuccessfulRequest_LogsStartStop>b__3_0(System.String, System.String)

Child arguments:
  1.1, Send
```

**Comment by VincentBu** [comment]
Similar test failed with same exception in [runtime-libraries-coreclr outerloop 20210318.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1045261&view=ms.vss-test-web.build-test-results-tab&runId=32341998&resultId=104472&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
 -System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   159.5255
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 525
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  1.1
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210328.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1060285&view=ms.vss-test-web.build-test-results-tab&runId=32683030&resultId=104479&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
 -System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   299.6055
   at System.Net.Http.Functional.Tests.TelemetryTest.VerifyEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 requestsLeftQueueVersion) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 525
   at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 641
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue>b__10_0(System.String)

Child arguments:
  1.1
```
