### ISSUE TITLE
Test Failure: System.Net.NameResolution.Tests.TelemetryTest.EventSource_ResolveValidHostName_LogsStartStop

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#46074]
failed again in job: [runtime-libraries-coreclr outerloop 20200916.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=817342&view=ms.vss-test-web.build-test-results-tab&runId=26020616&paneView=debug&resultId=102066)

failed test: System.Net.NameResolution.Tests.TelemetryTest.EventSource_ResolveValidHostName_LogsStartStop

net5.0-Windows_NT-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 6
Actual:   5
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveValidHostName_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 57
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.NameResolution.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ResolveValidHostName_LogsStartStop>b__1_0()
~~~

_Originally posted by @v-haren in https://github.com/dotnet/runtime/issues/41723#issuecomment-693794345_

**Comment by karelz** [comment]
Only 1 similar failure between 2/23-5/7 on PR (none in official runs):

OS: Windows.81.Amd64.Open

```
Child exception:
  System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 220
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 192
--- End of stack trace from previous location ---
   at System.Net.Dns.<GetAddrInfoWithTelemetryAsync>g__CompleteAsync|34_0[T](Task task, String hostName, ValueStopwatch stopwatch) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 621
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveValidHostName_LogsStartStop>b__1_1>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 40
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 118
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveValidHostName_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 38
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.NameResolution.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ResolveValidHostName_LogsStartStop>b__1_0()
```

Closing.
