### ISSUE TITLE
Test failure: Loader/binding/tracing/BinderTracingTest.Basic/BinderTracingTest.Basic.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46110]
failed in job: [runtime-coreclr outerloop 20201215.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=922305&view=ms.vss-test-web.build-test-results-tab&runId=29291530&resultId=110377&paneView=debug)

CoreCLR OSX x64 Checked no_tiered_compilation @ OSX.1013.Amd64.Open

Error message
~~~
Return code:      1
Raw output file:      /private/tmp/helix/working/A887096B/w/AA6708F7/e/Loader/binding/Reports/Loader.binding/tracing/BinderTracingTest.Basic/BinderTracingTest.Basic.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A887096B/p/corerun BinderTracingTest.Basic.dll ''
[3:45:17 PM] Running LoadFile...
[3:45:19 PM] Running LoadBytes...
[3:45:19 PM] Running LoadFromStream...
[3:45:19 PM] Running LoadFromAssemblyPath...
[3:45:19 PM] Launching process for LoadFromAssemblyName...
[3:45:20 PM] Running LoadFromAssemblyName...

[3:45:23 PM] Launching process for LoadFrom...
[3:45:23 PM] Running LoadFrom...

[3:45:25 PM] Launching process for PlatformAssembly...
[3:45:25 PM] Running PlatformAssembly...

[3:45:27 PM] Launching process for PlatformAssembly_Cached...
[3:45:28 PM] Running PlatformAssembly_Cached...

[3:45:29 PM] Launching process for Reflection...
[3:45:30 PM] Running Reflection...

[3:45:31 PM] Launching process for Reflection_Cached...
[3:45:32 PM] Running Reflection_Cached...

[3:45:34 PM] Launching process for Reflection_CustomALC...
[3:45:34 PM] Running Reflection_CustomALC...

[3:45:36 PM] Launching process for ContextualReflection_DefaultToCustomALC...
[3:45:36 PM] Running ContextualReflection_DefaultToCustomALC...

[3:45:38 PM] Launching process for ContextualReflection_CustomToDefaultALC...
[3:45:39 PM] Running ContextualReflection_CustomToDefaultALC...

[3:45:40 PM] Launching process for JITLoad...
[3:45:40 PM] Running JITLoad...

[3:45:42 PM] Launching process for JITLoad_CustomALC...
[3:45:43 PM] Running JITLoad_CustomALC...

[3:45:44 PM] Running AssemblyInAppPath...
[3:45:44 PM] Running NonExistentAssembly...
[3:45:45 PM] Launching process for SatelliteAssembly_AppPath...
[3:45:45 PM] Running SatelliteAssembly_AppPath...

[3:45:47 PM] Running SatelliteAssembly_CultureSubdirectory...
[3:45:47 PM] Launching process for SatelliteAssembly_CultureSubdirectory_DefaultALC...
[3:45:48 PM] Running SatelliteAssembly_CultureSubdirectory_DefaultALC...

[3:45:49 PM] Running SatelliteAssembly_CultureSubdirectory_Lowercase...
Test SatelliteAssembly_CultureSubdirectory_Lowercase failed: System.IO.IOException: Source and destination path must be different.
   at System.IO.Directory.Move(String sourceDirName, String destDirName) in /_/src/libraries/System.IO.FileSystem/src/System/IO/Directory.cs:line 277
   at BinderTracingTests.BinderTracingTest.SatelliteAssembly_CultureSubdirectory_Lowercase() in /__w/1/s/src/tests/Loader/binding/tracing/BinderTracingTest.DefaultProbing.cs:line 258
   at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method) in /__w/1/s/src/tests/Loader/binding/tracing/BinderTracingTest.cs:line 171
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/A887096B/p
> /private/tmp/helix/working/A887096B/w/AA6708F7/e/Loader/binding/tracing/BinderTracingTest.Basic/BinderTracingTest.Basic.sh
Expected: True
Actual:   False


Stack trace
   at Loader_binding._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_sh() in /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/Loader.binding/Loader.binding.XUnitWrapper.cs:line 902
~~~

**Comment by agocke** [comment]
This looks like it was an isolated failure -- probably an environment issue.
