### ISSUE TITLE
crossgen2: getHFAType fails on arm64 and passes on x64 targetting arm64

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#46126]
https://github.com/dotnet/runtime/blob/78efb9250245617ff8532371ae4b8375a741f5ea/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L2540  fails on arm64 and passes on x64 targetting arm64.

To repro get this change:
https://github.com/sandreenko/runtime/commit/880a563af8171609257c80045538d98401aa8877

```
readytorun\crossgen2\crossgen2smoke
```

and run crossgen2 test on x64 -> passes, on x64 targeting arm64 -> passes, on arm64 -> fails with:
```
Z:\PayloadGroup0>dotnet "Z:\CoreRoot\crossgen2\crossgen2.dll" @"Z:\PayloadGroup0\readytorun\crossgen2\crossgen2smoke\\composite-r2r.dll.rsp"   --composite"
To repro, add following arguments to the command line:
--singlemethodtypename "HelperGenericILCode`1[[System.__Canon]],helperildll" --singlemethodname LdTokenArrayMethods --singlemethodindex 1
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[helperildll]HelperGenericILCode`1<System.__Canon>.LdTokenArrayMethods(RuntimeMethodHandle&,RuntimeMethodHandle&,RuntimeMethodHandle&,RuntimeMethodHandle&,RuntimeMethodHandle&)'
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 216
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 391
   at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__26_0(DependencyNodeCore`1 dependency) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 499
   at ILCompiler.ReadyToRunCodegenCompilation.ComputeDependencyNodeDependencies(List`1 obj) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 525
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 302
   at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 302
   at ILCompiler.Program.Run(String[] args) in /_/src/coreclr/tools/aot/crossgen2/Program.cs:line 590
   at ILCompiler.Program.Main(String[] args) in /_/src/coreclr/tools/aot/crossgen2/Program.cs:line 739
```

for the minimal repro use the following rsp file(with your passes):
```
Y:\PayloadGroup0\readytorun\crossgen2\crossgen2smoke\IL-CG2\*.dll
-o:Y:\PayloadGroup0\readytorun\crossgen2\crossgen2smoke\\composite-r2r.dll
--targetarch:arm64
--verify-type-and-field-layout
-O
-r:Y:\CoreRoot\System.*.dll
-r:Y:\CoreRoot\Microsoft.*.dll
-r:Y:\CoreRoot\mscorlib.dll
-r:Y:\CoreRoot\netstandard.dll
--parallelism 
1
--singlemethodtypename 
HelperGenericILCode`1[[System.__Canon]],helperildll
--singlemethodname
LdTokenArrayMethods
--singlemethodindex
1
```

Remove a workaround for https://github.com/dotnet/runtime/pull/46034 when it is fixed.

**Comment by sandreenko** [comment]
PTAL @mangod9 @jkotas

**Comment by sandreenko** [comment]
@mangod9 no, it does not

**Comment by mangod9** [comment]
Thanks, assigning to @AntonLapounov who will look at it in Jan.

**Comment by mangod9** [comment]
assume this is still something that needs investigation?

**Comment by AntonLapounov** [comment]
We discussed that offline.  The current behavior may be considered "by design".  There was another question why compiling for ARM64 on x64 and ARM64 machines demonstrated different behavior (no assert vs. assert).  I can check whether it is still the case.  I think we can safely move it to future release.

**Comment by ivdiazsa** [comment]
This issue is apparently still happening. I'm currently investigating.

**Comment by ivdiazsa** [comment]
Ok so I'm seeing an interesting and more pattern-like behavior now. This is now failing with a slightly different error message, but in a more uniform way. If we target x64 using an x64 host, it all goes fine. However, targeting arm64 always fails, regardless of whether the host is x64 or arm64. This is the error message I'm seeing:

```
Unhandled exception.Unhandled exception. Unhandled exception.Unhandled exception.   ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CoreLib]System.Array.CreateInstance(Type,int64[])'
 ---> System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.DefType'.
   at Internal.JitInterface.CorInfoImpl.getHFAType(CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 3030
   at Internal.JitInterface.CorInfoImpl._getHFAType(IntPtr thisHandle, IntPtr* ppException, CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 1691
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 380
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 736
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 841
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 775
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 753ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CoreLib]System.Array.CreateInstance(Type,int32[])'
 ---> System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.DefType'.
   at Internal.JitInterface.CorInfoImpl.getHFAType(CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 3030
   at Internal.JitInterface.CorInfoImpl._getHFAType(IntPtr thisHandle, IntPtr* ppException, CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 1691
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 380
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 736
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 841
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 775
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 753ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CoreLib]System.Array.GetValue(int32[])'
 ---> System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.DefType'.
   at Internal.JitInterface.CorInfoImpl.getHFAType(CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 3030
   at Internal.JitInterface.CorInfoImpl._getHFAType(IntPtr thisHandle, IntPtr* ppException, CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 1691
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 380
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 736
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 841
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 775
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 753ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.CoreLib]System.Array.CreateInstance(Type,int32[],int32[])'
 ---> System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.ArrayType' to type 'Internal.TypeSystem.DefType'.
   at Internal.JitInterface.CorInfoImpl.getHFAType(CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 3030
   at Internal.JitInterface.CorInfoImpl._getHFAType(IntPtr thisHandle, IntPtr* ppException, CORINFO_CLASS_STRUCT_* hClass) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 1691
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 380
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 736
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 841
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 775
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /media/ivdiazsa/DataDrive/Development/dotnet_runtime-x64-and-arm64/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 753
```

Does this mean we should treat it by design as Anton previously mentioned, or does this mean we now got a more severe bug in our hands? I'd like to hear your thoughts on how we should treat it @trylek @mangod9

**Comment by jkotas** [comment]
The [comment on `getHFAType` JIT/EE interface method](https://github.com/dotnet/runtime/blob/10222f94e5d89b19959117dd9e5b8576ef63f878/src/coreclr/inc/corinfo.h#L2889-L2892) says: Returns type of HFA for valuetype

The crossgen implementation of this method assumes that this method can be only called on valuetypes. https://github.com/sandreenko/runtime/commit/880a563af8171609257c80045538d98401aa8877 violates the assumption and that's why you are seeing the crash.

We can either:
- Change the method contract to make it callable on any type: Adjust the comment, adjust the crossgen implementation (return false), apply the proposed change in the JIT.
or
- Keep the method contract as is (ie treat the current behavior as "by design"). It would be nice to add assert to vm/jitinterface.cpp to ensure that this method is only called for valuetypes, so that we are not seeing these problems in crossgen and AOT only.

**Comment by ivdiazsa** [comment]
> The [comment on `getHFAType` JIT/EE interface method](https://github.com/dotnet/runtime/blob/10222f94e5d89b19959117dd9e5b8576ef63f878/src/coreclr/inc/corinfo.h#L2889-L2892) says: Returns type of HFA for valuetype
> 
> The crossgen implementation of this method assumes that this method can be only called on valuetypes. [sandreenko@880a563](https://github.com/sandreenko/runtime/commit/880a563af8171609257c80045538d98401aa8877) violates the assumption and that's why you are seeing the crash.
> 
> We can either:
> 
> * Change the method contract to make it callable on any type: Adjust the comment, adjust the crossgen implementation (return false), apply the proposed change in the JIT.
>   or
> * Keep the method contract as is (ie treat the current behavior as "by design"). It would be nice to add assert to vm/jitinterface.cpp to ensure that this method is only called for valuetypes, so that we are not seeing these problems in crossgen and AOT only.

Thanks for the detailed explanation Jan. After discussing with Tomas, we think your second suggestion is the more reasonable way to solve this problem. I just wanted to ask something that is not clear to me. By adding an assert, then this means we will always crash with the given repro, regardless of architecture correct?

**Comment by sandreenko** [comment]
The assert and change in Jit to call it only on value types sound reasonable. 
Probably many methods in jit call it right now without a value type check, like https://github.com/dotnet/runtime/blob/652433bfe9858f7f4d6f6ffcf0c994cb9b91e482/src/coreclr/jit/codegencommon.cpp#L6482 and expect that `GetHfaType(NO_CLASS_HANDLE)` returns `TYP_UNDEF` but the fix should not be complex.

**Comment by trylek** [comment]
I guess it should suffice to fix the JIT wrapper <code>GetHfaType</code> to avoid actually calling the JIT interface unless the type is a valuetype, there are various sorts of upfront checks there already.

**Comment by jkotas** [comment]
> I guess it should suffice to fix the JIT wrapper GetHfaType to avoid actually calling the JIT interface unless the type is a valuetype

If you need to do another call on JIT/EE inteface to check whether it is a value type, it is more efficient to allow passing any types into the JIT/EE interface getHFAType API.

**Comment by trylek** [comment]
Hmm, I thought this information was readily available to JIT without making another interface call, if not, you're certainly right, we don't want to add another interface call for this purpose.

**Comment by sandreenko** [comment]
> Hmm, I thought this information was readily available to JIT without making another interface call, if not, you're certainly right, we don't want to add another interface call for this purpose.

'isValueType' is saved in LclVars and GenTrees that call 'getHFAType' method so it is cheap to fix. Maybe it would ever be a speed-up not to call it when JIT-EE already knows the result.

cc @jakobbotsch

**Comment by jakobbotsch** [comment]
From a quick pass over the callers I think it will suffice to add a `varTypeIsStruct(argSigType)` guard here:
https://github.com/dotnet/runtime/blob/3fded0bb77c852b10d712bd629ced740499a3aa6/src/coreclr/jit/morph.cpp#L2235

All other callers I saw seem to be from paths that already know we are dealing with a value type.

**Comment by AndyAyersMS** [comment]
This no longer reproduces with the current Crossgen2 and JIT. The `crossgen2smoke` inputs now compile successfully as a composite ARM64 ReadyToRun image from an x64 host.

The unguarded `GetHfaType(argSigClass)` call identified in the final discussion was removed by #112665. Current ARM and ARM64 ABI classifiers only query HFA information for struct types.

Closing as fixed by the subsequent ABI classification cleanup.
