### ISSUE TITLE
[Mono][WASM][Test] JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh failures

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#46174]
The test is failing with:
```
      callBack_RPInvoke_Vector3Arg_Unix:
          1, 2, 3
          10, 30, 107
          Sum0,1,2,3 = 14, 12449, 391, -2.0972324E+29
      RPInvoke Vector3Arg_Unix test failed
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
```
on `Mono Browser wasm Release @ Ubuntu.1804.Amd64.Open` and `Mono Linux arm64 Release`, see an example:
https://dev.azure.com/dnceng/public/_build/results?buildId=923829&view=ms.vss-test-web.build-test-results-tab&runId=29324602&paneView=debug

in the past the test was disabled so we did not see it.

**Comment by sandreenko** [comment]
Hi, @maryamariyan, could you please check if msftbot subscribed the arena owners for this issue? 
The message looks like it did not: `Tagging subscribers to this area: empty`

**Comment by maryamariyan** [comment]
> Tagging subscribers to this area: empty

@danmosemsft is the msftbot missing area `area-Codegen-JIT-mono`?

**Comment by sandreenko** [comment]
PTAL @vargaz

**Comment by lewing** [comment]
the wasm failure is a test issue not a jit issue

```
        Arguments: --run,Vector3Interop_ro.dll
        console.debug: MONO_WASM: Initializing mono runtime
        console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
        console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
        Initializing.....
        WASM-ERR: 
        WASM-ERR: Unhandled Exception:
        WASM-ERR: System.DllNotFoundException: Vector3TestNative
        WASM-ERR:    at PInvokeTest.test()
        WASM-ERR:    at Test.Main()
        JS exception: Error: System.DllNotFoundException: Vector3TestNative
           at PInvokeTest.test()
           at Test.Main()
        Error: System.DllNotFoundException: Vector3TestNative
           at PInvokeTest.test()
           at Test.Main()
            at Object._convert_exception_for_method_call (dotnet.js:1:191022)
            at Object._handle_exception_for_call (dotnet.js:1:192991)
            at Object._handle_exception_and_produce_result_for_call (dotnet.js:1:193312)
            at Object._call_method_with_converted_args (dotnet.js:1:194388)
            at Object.call_method (dotnet.js:1:192781)
            at Object.call_assembly_entry_point (dotnet.js:1:200902)
            at Object.init (runtime.js:368:28)
            at Object.config.loaded_cb (runtime.js:234:8)
            at Object._finalize_startup (dotnet.js:1:148671)
            at onPendingRequestComplete (dotnet.js:1:149870)
        Expected: 100
```

**Comment by danmosemsft** [comment]
Someone left leaving no subscribers to these areas

area-Codegen-JIT-mono | @SamMonoRT | @vargaz |  
-- | -- | -- | --
area-CodeGen-LLVM-mono | @SamMonoRT | @imhameed |  
area-Codegen-meta-mono | @SamMonoRT | @vargaz

I'll remove the empty notificatoins.

**Comment by SamMonoRT** [comment]
@danmosemsft - interesting, thanks for removing the empty notifications. Did you add us back to the above three areas ?

**Comment by danmosemsft** [comment]
@SamMonoRSano the notifications are opt in. Shall I add just you or all the guys I listed here?

**Comment by SamMonoRT** [comment]
yes, please add us as below. :
area-Codegen-JIT-Mono :: SamMonoRT, vargaz
area-CodeGen-LLVM-Mono :: SamMonoRT, vargaz, imhameed
area-CodeGen-meta-Mono :: Sammonort, vargaz, coffeeflux, lambdageek

**Comment by danmosemsft** [comment]
done

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr jitstress 20201217.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=926040&view=ms.vss-test-web.build-test-results-tab&runId=29373118&resultId=109601&paneView=debug)

failed test: JIT\\SIMD\\Vector3Interop_r\\Vector3Interop_r.cmd

CoreCLR windows arm64 Checked zapdisable @ Windows.10.Arm64v8.Open

Error message
~~~
Return code:      1
Raw output file:      D:\h\w\9FEC085C\w\A2F00878\e\JIT\SIMD\Reports\JIT.SIMD\Vector3Interop_r\Vector3Interop_r.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\9FEC085C\p\corerun.exe" Vector3Interop_r.dll 
nativeCall_PInvoke_CheckVector3Size: sizeof(Vector3) == 12
nativeCall_PInvoke_Vector3Arg:
    iVal 123
    sumOfEles(1.000000, 2.000000, 3.000000) = 6.000000
    str  abcdefg
    sumOfEles(10.000000, 11.000000, 12.000000) = 33.000000
nativeCall_PInvoke_Vector3Arg_Unix:
    v3f32_xmm0: 1.000000 2.000000 3.000000
    f32_xmm2 - f32_xmm7: 100.000000 101.000000 102.000000 103.000000 104.000000 105.000000
    f32_mem0: 106.000000
    v3f32_mem1: 10.000000 20.000000 30.000000
    f32_mem2-3: 107.000000 108.000000
    sum = 1002.000000
nativeCall_PInvoke_Vector3Arg_Unix2:
    v3f32_xmm0: 1.000000 2.000000 3.000000
    f32_xmm2 - f32_xmm7: 100.000000 101.000000 102.000000 103.000000 104.000000 105.000000
    f32_mem0: 106.000000
    v3f32_mem1: 4.000000 5.000000 6.000000
    f32_mem2-3: 107.000000 108.000000
    v3f32_mem4: 7.000000 8.000000 9.000000
    f32_mem5: 109.000000
    sum = 1090.000000
nativeCall_PInvoke_Vector3Ret:
    Return value: (1.000000, 2.000000, 3.000000)
    Sum of return scalar values = 6.000000
nativeCall_PInvoke_Vector3Array
    arrEle[0]: 1.000000 2.000000 3.000000
    arrEle[1]: 5.000000 6.000000 7.000000
    Sum = 24.000000
nativeCall_PInvoke_Vector3InStruct
    First struct memeber: (1.000000 2.000000 3.000000) -> (2.000000 3.000000 4.000000)
    Second struct member: (5.000000 6.000000 7.000000) -> (6.000000 7.000000 8.000000)
    Sum of all return scalar values = 30.000000
nativeCall_PInvoke_Vector3InComplexStruct
    Arg ival: 99
    Arg Vector3 v1: (1.000000 2.000000 3.000000)
    Arg Vector3 v2: (5.000000 6.000000 7.000000)
    Arg Vector3 v3: (10.000000 20.000000 30.000000)
    Arg string arg: arg_string
    Return ival: 100
    Return Vector3 v1: (2.000000 3.000000 4.000000)
    Return Vector3 v2: (6.000000 7.000000 8.000000)
    Return Vector3 v3: (11.000000 21.000000 31.000000)
    Return string arg: ret_string
    Sum of all return float scalar values = 93.000000
    Managed ival: 100
    Managed Vector3 v1: (2 3 4)
    Managed Vector3 v2: (6 7 8)
    Managed Vector3 v3: (11 21 31)
    Managed string arg: ret_string
    Managed Sum = 735
All PInvoke testcases passed
callBack_RPInvoke_Vector3Arg:
    iVal 123
    Sum0,1,2 = 14, 1400, 140
    str abcdefg
callBack_RPInvoke_Vector3Arg_Unix:
    1, 2, 3
    10, 20, 30
    Sum0,1,2,3 = 14, NaN, NaN, 936
RPInvoke Vector3Arg_Unix test failed
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\9FEC085C\p
> D:\h\w\9FEC085C\w\A2F00878\e\JIT\SIMD\Vector3Interop_r\Vector3Interop_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._Vector3Interop_r_Vector3Interop_r_._Vector3Interop_r_Vector3Interop_r_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.arm64.Checked\TestWrappers\JIT.SIMD\JIT.SIMD.XUnitWrapper.cs:line 5503
~~~

**Comment by SamMonoRT** [comment]
@fanyang-mono @vargaz please take a look

**Comment by fanyang-mono** [comment]
The comment from @v-haren on Dec 20, 2020 was related to coreclr rather than Mono Wasm. That failure has another tracing issue https://github.com/dotnet/runtime/issues/46347

In terms of why this test is failing on WASM, according to what Larry said earlier, it is a test issue.

**Comment by SamMonoRT** [comment]
Moving to future milestone. @fanyang-mono please confirm if the test is already excluded.

**Comment by fanyang-mono** [comment]
> Moving to future milestone. @fanyang-mono please confirm if the test is already excluded.

Yes, the test has already been excluded.

**Comment by jeffschwMSFT** [comment]
I see that this issue has bounced a few labels, I added back codegen-aot-mono, but feel free to find the right label.
