### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46208]
failed in job: [runtime-libraries-coreclr outerloop 20201217.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=924882&view=ms.vss-test-web.build-test-results-tab&runId=29343938&resultId=102792&paneView=debug)

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.


Stack trace
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/Win32.cs:line 314
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 263
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, AccessControlSections includeSections, Object exceptionContext) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 353
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, AccessControlSections includeSections) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 343
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath) in /_/src/libraries/System.IO.FileSystem.AccessControl/src/System/Security/AccessControl/FileSystemSecurity.cs:line 124
   at System.IO.FileSystemAclExtensions.SetAccessControl(FileInfo fileInfo, FileSecurity fileSecurity) in /_/src/libraries/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.cs:line 78
   at System.Diagnostics.Tests.ProcessStartInfoTests.SetAccessControl(String userName, String filePath, AccessControlType accessControlType) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 523
   at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 502
~~~

**Comment by adamsitnik** [comment]
Based on what I can see in Kusto my previous PR (#46213) has not solved the problem and this test test has failed 140 times since 25th of December. I am going to reopen it and send a proper fix
