### ISSUE TITLE
R2RDump fails for System.IO.FileSystem

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#46210]
### Description

Running R2RDump on System.IO.FileSystem which has been compiled with crossgen2 causes the following exception:

```
CoreRun.exe R2RDump\R2RDump.dll -d -i System.IO.FileSystem.dll

Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ILCompiler.Reflection.ReadyToRun.Amd64.UnwindInfo.ParseUnwindCode(Int32& i) in C:\git\runtime\src\coreclr\src\tools\aot\ILCompiler.Reflection.ReadyToRun\Amd64\UnwindInfo.cs:line 244
   at ILCompiler.Reflection.ReadyToRun.Amd64.UnwindInfo..ctor(Byte[] image, Int32 offset) in C:\git\runtime\src\coreclr\src\tools\aot\ILCompiler.Reflection.ReadyToRun\Amd64\UnwindInfo.cs:line 139
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunMethod.ParseRuntimeFunctions() in C:\git\runtime\src\coreclr\src\tools\aot\ILCompiler.Reflection.ReadyToRun\ReadyToRunMethod.cs:line 480
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunMethod.EnsureRuntimeFunctions() in C:\git\runtime\src\coreclr\src\tools\aot\ILCompiler.Reflection.ReadyToRun\ReadyToRunMethod.cs:line 267
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunMethod.get_RuntimeFunctions() in C:\git\runtime\src\coreclr\src\tools\aot\ILCompiler.Reflection.ReadyToRun\ReadyToRunMethod.cs:line 257
   at R2RDump.Extensions.WriteTo(ReadyToRunMethod theThis, TextWriter writer, DumpOptions options) in C:\git\runtime\src\coreclr\src\tools\r2rdump\Extensions.cs:line 147
   at R2RDump.TextDumper.DumpMethod(ReadyToRunMethod method) in C:\git\runtime\src\coreclr\src\tools\r2rdump\TextDumper.cs:line 154
   at R2RDump.TextDumper.DumpAllMethods() in C:\git\runtime\src\coreclr\src\tools\r2rdump\TextDumper.cs:line 142
   at R2RDump.R2RDump.Dump(ReadyToRunReader r2r) in C:\git\runtime\src\coreclr\src\tools\r2rdump\R2RDump.cs:line 400
   at R2RDump.R2RDump.Run() in C:\git\runtime\src\coreclr\src\tools\r2rdump\R2RDump.cs:line 569
```

### Configuration

Compile System.IO.FileSystem.dll with crossgen2
Use R2RDump to disassemble compiled version of System.IO.FileSystem.dll

### Regression?
No

**Comment by mangod9** [comment]
cc @dotnet/crossgen-contrib
