### ISSUE TITLE
Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global'

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#46239]
[runtime-coreclr outerloop #20201218.4](https://dev.azure.com/dnceng/public/_build/results?buildId=926781)

```
    JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh [FAIL]
      
      Assert failure(PID 941 [0x000003ad], Thread: 941 [0x03ad]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
      
          File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh: line 365:   941 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun expl_obj_1_d.dll ''
      Gathering state for process 941 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.941.dmp
      Written 50401280 bytes (12305 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(101482,0): at JIT_Methodical._explicit_coverage_expl_obj_1_d_expl_obj_1_d_._explicit_coverage_expl_obj_1_d_expl_obj_1_d_sh()
      Output:
        
        Assert failure(PID 941 [0x000003ad], Thread: 941 [0x03ad]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
        
            File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
            Image: /root/helix/work/correlation/corerun
        
        /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh: line 365:   941 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun expl_obj_1_d.dll ''
        Gathering state for process 941 corerun
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.941.dmp
        Written 50401280 bytes (12305 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_d/expl_obj_1_d.sh
    JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh [FAIL]
      
      Assert failure(PID 1491 [0x000005d3], Thread: 1491 [0x05d3]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
      
          File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh: line 365:  1491 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun expl_obj_1_r.dll ''
      Gathering state for process 1491 corerun
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1491.dmp
      Written 50298880 bytes (12280 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(101589,0): at JIT_Methodical._explicit_coverage_expl_obj_1_r_expl_obj_1_r_._explicit_coverage_expl_obj_1_r_expl_obj_1_r_sh()
      Output:
        
        Assert failure(PID 1491 [0x000005d3], Thread: 1491 [0x05d3]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)
        
            File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 4143
            Image: /root/helix/work/correlation/corerun
        
        /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh: line 365:  1491 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun expl_obj_1_r.dll ''
        Gathering state for process 1491 corerun
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1491.dmp
        Written 50298880 bytes (12280 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/JIT/Methodical/explicit/coverage/expl_obj_1_r/expl_obj_1_r.sh

```

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib

**Comment by echesakovMSFT** [comment]
Since it doesn't assert in the previous run [runtime-coreclr outerloop #20201218.3](https://dev.azure.com/dnceng/public/_build/results?buildId=926540&view=results) and there is only change related to the JIT:
```
echesako@echesako-dtl1 F:\echesako\git\runtime
$ git log --pretty=oneline 4bc323242d43dda85d490c0630c4637ffc092469..3a276d5ecb25bb4541d15be50cfd4911e1d58cfe src\coreclr\jit
3a276d5ecb25bb4541d15be50cfd4911e1d58cfe Fix arm64 apple hfa<float>. (#46034)
``` 
I assume it's #46034
@sandreenko PTAL

**Comment by sandreenko** [comment]
Thanks for reporting this. I will take a look.

**Comment by v-haren** [comment]
failed again in job: [runtime-coreclr outerloop 20201220.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=928104&view=ms.vss-test-web.build-test-results-tab&runId=29422278&resultId=100359&paneView=debug)

failed tests: 
JIT\\Methodical\\explicit\\coverage\\expl_obj_1_r\\expl_obj_1_r.cmd
JIT\\Methodical\\explicit\\coverage\\expl_obj_1_d\\expl_obj_1_d.cmd

CoreCLR windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

Error message
~~~
Assert failure(PID 13960 [0x00003688], Thread: 2480 [0x09b0]): Assertion failed 'outgoingArgSpaceSize == preallocatedArgCount * REGSIZE_BYTES' in 'TestApp:Main():int' during 'Morph - Global' (IL size 3136)

    File: F:\workspace\_work\1\s\src\coreclr\jit\morph.cpp Line: 4143
    Image: D:\h\w\9DB3091D\p\CoreRun.exe


Return code:      1
Raw output file:      D:\h\w\9DB3091D\w\AB9E099C\e\JIT\Methodical\Reports\JIT.Methodical\explicit\coverage\expl_obj_1_r\expl_obj_1_r.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\9DB3091D\p\corerun.exe" expl_obj_1_r.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\9DB3091D\p
> D:\h\w\9DB3091D\w\AB9E099C\e\JIT\Methodical\explicit\coverage\expl_obj_1_r\expl_obj_1_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._explicit_coverage_expl_obj_1_r_expl_obj_1_r_._explicit_coverage_expl_obj_1_r_expl_obj_1_r_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.arm.Checked\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs:line 108223
~~~
