### ISSUE TITLE
Executable produced with SingleFile & IncludeNativeLibrariesForSelfExtract may trigger Windows Defender

### ISSUE THREAD

**Issue by maxpiva** [dotnet/runtime#46312]
### Description

The console executable is created using SingleFile, SelfContained & IncludeNativeLibrariesForSelfExtract.

It uses the OpenCVSharp NuGet and native OpenCV DLL.
When OpenCVSharp is trying to load the native OpenCV DLL from the **temporary directory** it fails, and also original caller program is removed by Windows Defender.

#### WIndows Defender Response:

Threat quarantined -> SEVERE

**Detected:** Behavior:Win32/DefenseEvasion.UM!ml
**Status:** Quarantined

### Configuration

NET 5.0.200-preview.20601.7
Windows 10
x64

### Other information

Exception when it happens:
```
System.IO.FileLoadException:
File name: 'OpenCvSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6adad1e807fea099'
   at Sushi.Net.Library.LibIO.CVMatrix.MatchTemplate(CVMatrix pattern, Boolean type)
   at Sushi.Net.Library.Audio.AudioStream.FindSubStream(SubStream pattern, Single window_center, Single window_size, Boolean type)
   at Sushi.Net.Library.Events.Shifter.CalculateShifts(AudioStream src_stream, AudioStream dst_stream, List`1 groups_list, Single normal_window, Single max_window, Single rewind_trash, Single allowed_error)
```
This not always happens. It happens at random. 

The native library lookup mechanism in .net core seems to trigger Windows Defender, maybe the solution is to downgrade the Windows Defender detected behaviour make in it less aggressive or whitelist this lookup process. 
Of course, this is only a supposition.:upside_down_face:

**Area:**

area-Single-File

**Comment by vitek-karas** [comment]
Can you please clarify:
* If the main executable is tagged by Windows Defender then I assume it won't run at all, right?
* So the failure above happens only if the executable itself is not tagged. In that case, does Windows Defender report something - like tagging the native library it's trying to load?
* The failure above is about failing to load a managed dll - not the native dll (unless it's a C++/CLI dll, in which case it's getting weird).

The runtime should use AMSI APIs to report the dll being loaded to Windows Defender (or any other AV installed): https://github.com/dotnet/runtime/blob/113810178607cee16c5073aa7cf4d5f7414f2c4c/src/coreclr/vm/amsi.cpp#L73

**Comment by maxpiva** [comment]
> Can you please clarify:
> 
> * If the main executable is tagged by Windows Defender then I assume it won't run at all, right?

It starts running, and run several times without a problem, but at random, when the native library needs to be loaded is when the wreck happens. In this case OpenCV. I notice that IncludeNativeLibrariesForSelfExtract publish decompress the related DLLs into the Temp/.net/(name of the exe)/temp directory. And, actually, I'm inclined to think that the File.Not.Found is from the main exe itself disappearing and not the external library disappearing. But the lookup/load process seems to be the trigger.


> * So the failure above happens only if the executable itself is not tagged. In that case, does Windows Defender report something - like tagging the native library it's trying to load?

No, it tags the main executable, and move it to quarantine. I'm almost certain it does not tag the native library

> * The failure above is about failing to load a managed dll - not the native dll (unless it's a C++/CLI dll, in which case it's getting weird).

No, it's the looking for the native one, that triggers windows defender, all the managed dll are already linked and trimmed with single file into the main exe.

 Directory of C:\Users\mpiva\AppData\Local\Temp\.net\sushi.net\4k1sh13g.evj

12/25/2020  11:37 PM    <DIR>          .
12/25/2020  11:37 PM    <DIR>          ..
12/25/2020  11:37 PM           747,912 clrcompression.dll
12/25/2020  11:37 PM         1,324,424 clrjit.dll
12/25/2020  11:37 PM         5,157,256 coreclr.dll
12/25/2020  11:37 PM         1,047,928 mscordaccore.dll
**12/25/2020  11:37 PM        19,436,544 OpenCvSharpExtern.dll**
               5 File(s)     27,714,064 bytes
               2 Dir(s)  79,605,387,264 bytes free

> 
> The runtime should use AMSI APIs to report the dll being loaded to Windows Defender (or any other AV installed):
> 
> https://github.com/dotnet/runtime/blob/113810178607cee16c5073aa7cf4d5f7414f2c4c/src/coreclr/vm/amsi.cpp#L73


Code and binaries in:
[https://github.com/maxpiva/Sushi.Net](https://github.com/maxpiva/Sushi.Net)

**Comment by agocke** [comment]
Unfortunately we don't have a lot of control over how the Windows antivirus processes our files. We'll keep this issue in case we find some pattern that can mitigate the problem, but otherwise this is likely up to Windows to change.
