### ISSUE TITLE
System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported

### ISSUE THREAD

**Issue by 89z** [dotnet/runtime#46399]
If I have this program, it works as expected:

~~~cs
using C = System.Console;
using J = System.Text.Json.JsonSerializer;

class Program {
   static void Main() {
      string[] a = { "one", "two" };
      C.WriteLine(J.Serialize(a));
   }
}
~~~

However if I add a dimension to the array:

~~~
using C = System.Console;
using J = System.Text.Json.JsonSerializer;

class Program {
   static void Main() {
      string[,] a = { { "one", "two" }, { "three", "four" } };
      C.WriteLine(J.Serialize(a));
   }
}
~~~

It completely fails:

~~~
Unhandled exception. System.NotSupportedException: The type 'System.String[,]'
   is not supported.
at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type
   propertyType)
at System.Text.Json.Serialization.Converters.IEnumerableConverterFactory.CreateConverter(Type
   typeToConvert, JsonSerializerOptions options)
at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type
   typeToConvert, JsonSerializerOptions options)
at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type
   parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType,
   MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
at System.Text.Json.WriteStack.Initialize(Type type, JsonSerializerOptions
   options, Boolean supportContinuation)
at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer,
   TValue& value, Type inputType, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type
   inputType, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value,
   JsonSerializerOptions options)
~~~

**Comment by huoyaoyuan** [comment]
This is by design. System.Text.Json doesn't support multi-dimensional arrays (`T[,]`). It only supports jagged arrays `T[][]`.

**Comment by 89z** [comment]
Hm yeah, this seems to work as expected:

~~~cs
using C = System.Console;
using J = System.Text.Json.JsonSerializer;

class Program {
   static void Main() {
      // example 1
      int[][] a1 = {
         new[]{10, 11},
         new[]{12, 13}
      };
      // example 2
      var a2 = new[]{
         new[]{10, 11},
         new[]{12, 13}
      };
      // print
      C.WriteLine(J.Serialize(a1) + J.Serialize(a2));
   }
}
~~~

I think the error message could definitely be better.

**Comment by layomia** [comment]
I'm certain this has come up before; I couldn't find a duplicate issue so I'll use this one. Newtonsoft.Json supports multi-dimensional arrays. We can consider it also. We can take a PR including more info in the exception message, maybe a URI to an official docs page pointing out unsupported types. cc @tdykstra.

```cs
using System;
using Newtonsoft.Json;

namespace quickcheck
{
    class Program
    {
        static void Main(string[] args)
        {
            string[,] a = { { "one", "two" }, { "three", "four" } };
            string json = JsonConvert.SerializeObject(a);
            a = JsonConvert.DeserializeObject<string[,]>(json);
            Console.WriteLine(JsonConvert.SerializeObject(a));
        }
    }
}
```

**Comment by TheMaximum** [comment]
I've made an attempt to implement a converter for multidimensional arrays.
I don't know if my attempt is PR worthy - I haven't made any before.

Would anyone be interested to take a look and give me some advice as to if/how to proceed?

https://github.com/dotnet/runtime/compare/master...TheMaximum:feature-46399-jsonserializer-multidimensionalarrays?expand=1

**Comment by DDolG** [comment]
Hello. Can you please tell me if this question is open or closed?

**Comment by eiriktsarpalis** [comment]
@DDolG multi-dimensional are currently not supported. We keep this issue open in the backlog but it's not very high in our priority. As a workaround, you might consider authoring a custom converter that supports multi-dimensional arrays.

**Comment by eiriktsarpalis** [comment]
FWIW this needs source gen support as well, so APIs in JsonMetadataServices are also needed.
