### ISSUE TITLE
Test failure: System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(useExistingWatchers: True)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46421]
failed in job: [runtime-libraries-coreclr outerloop 20201227.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=932227&view=ms.vss-test-web.build-test-results-tab&runId=29520092&resultId=102975&paneView=debug)

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

Error message
~~~
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 190
~~~

**Comment by VincentBu** [comment]
Failed again in job [runtime-libraries-coreclr outerloop 20210112.4](https://dev.azure.com/dnceng/public/_build/results?buildId=946213&view=ms.vss-test-web.build-test-results-tab&runId=29846442&resultId=102978&paneView=debug)

Failed test : 
`System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(useExistingWatchers: True)`

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Create_ForceLoopRestart(Boolean useExistingWatchers) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.MultipleWatchers.cs:line 190
```

**Comment by carlossanlop** [comment]
Triage:
We checked the test result history in Kusto and this failure seems to happen mostly in PR jobs. In the last 30 days, it only affected master 2 times.
Next step is to look at the callstack and try to understand why it happens mostly in PRs.
