### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(uri: \"http://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46439]
failed in job: [runtime-libraries-coreclr outerloop 20201228.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=932693&view=ms.vss-test-web.build-test-results-tab&runId=29531028&resultId=104441&paneView=debug)

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

Error message
~~~
System.Net.Http.HttpRequestException : Response status code does not indicate success: 504 (Gateway Time-out).


Stack trace
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 170
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 182
   at System.Net.Http.Functional.Tests.HttpClientHandler_Decompression_Test.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:line 220
--- End of stack trace from previous location ---
~~~

**Comment by karelz** [comment]
No failure between 2/23-5/10 (incl. PRs). Closing.

**Comment by antonfirsov** [comment]
This started to happen again around 6/30, we keep hitting it since then. @karelz should we reopen it?

**Comment by karelz** [comment]
It is tracked in #58018
