### ISSUE TITLE
possible bug?  "..Eventing.Reader.EventLogSession threw an exception"

### ISSUE THREAD

**Issue by mySYSMON** [dotnet/runtime#46508]
Basic EventLogReader example has exception.
TargetFramework: net5.0

Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Diagnostics.Eventing.Reader.EventLogSession' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.

```
// This code is a stripped down version of the example found here.
// https://github.com/dotnet/runtime/issues/34568

// BE SURE TO RUN AS ADMINISTRATOR

using System.Diagnostics.Eventing.Reader;
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string log =  "Security"; //"Application";
            var reader = new EventLogReader(log, PathType.LogName);
        }
    }
}

/*
PS C:\tmp\ConsoleApp1\bin\x64\Debug\net5.0> .\ConsoleApp1.exe

Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Diagnostics.Eventing.Reader.EventLogSession' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.Eventing.Reader.EventLogPermissionHolder.GetEventLogPermission()
   at System.Diagnostics.Eventing.Reader.EventLogSession..ctor()
   at System.Diagnostics.Eventing.Reader.EventLogSession..cctor()
   --- End of inner exception stack trace ---
   at System.Diagnostics.Eventing.Reader.EventLogSession.get_GlobalSession()
   at System.Diagnostics.Eventing.Reader.EventLogQuery..ctor(String path, PathType pathType, String query)
   at System.Diagnostics.Eventing.Reader.EventLogQuery..ctor(String path, PathType pathType)
   at System.Diagnostics.Eventing.Reader.EventLogReader..ctor(String path, PathType pathType)
   at ConsoleApp1.Program.Main(String[] args) in C:\tmp\ConsoleApp1\Program.cs:line 9

*/
```
**Project Config**
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>ConsoleApp1</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vanara.Compatibility.EventLog" Version="1.0.2" />
  </ItemGroup>
</Project>
```

**Comment by mySYSMON** [comment]
Note I tried to create this earlier this afternoon, but didn't currently show up due to github flagging my other (new) github account.
https://github.com/dotnet/runtime/issues/46507

**Comment by mySYSMON** [comment]
Note I tried to create this earlier this afternoon, but didn't currently show up due to github flagging my other (new) github account.
46507
