### ISSUE TITLE
String.Concat throws OutOfMemoryException

### ISSUE THREAD

**Issue by lucapivato** [dotnet/runtime#46556]
Is there a memory limit to the mono wasm?
I'm testing with the latest .NET 5 and Blazor client side, which seems to be mono, and a loop like this:

        for (int i = 0; i < 1300; i++)
        {
            s += new string('A', 1000);
        }

throw this:

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Out of memory
System.OutOfMemoryException: Out of memory
   at System.String.Concat(String str0, String str1)
   at BlazorApp1.Pages.Counter.IncrementCount() in C:\Users\Luca\Source\Repos\BlazorApp2\BlazorApp1\Pages\Counter.razor:line 19
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)

It should use just about 2.6MB.

**Comment by lucapivato** [comment]
My bad. Wrong loop, will test again.

**Comment by lucapivato** [comment]
OK, tested a bit better. The mono wasm runtime in blazor client side with .NET 5 crashes in a simple loop concatenating a string 31,175 times. Works ate 31,174. Being a crash with the garbage collection it may impact just about anything running in the mono wasm, but I couldn't spend more time.

Crash

        for (int i = 0; i < 31175; i++)
        {
            s = s + "A";
        }

Works

        for (int i = 0; i < 31174; i++)
        {
            s = s + "A";
        }

![image](https://user-images.githubusercontent.com/37640802/103701028-53c22d80-4f73-11eb-8640-08877ccaf13c.png)

**Comment by danmosemsft** [comment]
@lewing not sure what area label to apply to this one.

**Comment by lewing** [comment]
For net5.0 Blazor runs the gc in a degraded mode where is it isn't able to collect in a loop like this.  https://github.com/dotnet/aspnetcore/pull/29098 will reenable this on demand gc mode for net6.0

**Comment by SamMonoRT** [comment]
@lewing @BrzVlad  - is this still an issue with GC now enabled ?

**Comment by BrzVlad** [comment]
this should be fixed now
