### ISSUE TITLE
[browser][tests] Potential memory leak of cached Completion Task

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#46566]
Test [TestNullTarget_CompletionNoCaching](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Threading.Tasks.Dataflow/tests/Dataflow/DataflowBlockExtensionTests.cs#L119-L132) failing with the following: 

```
fail: [FAIL] System.Threading.Tasks.Dataflow.Tests.DataflowBlockExtensionsTests.TestNullTarget_CompletionNoCaching
  info: Assert.False() Failure
  info: Expected: False
  info: Actual:   True
  info:    at System.Threading.Tasks.Dataflow.Tests.DataflowBlockExtensionsTests.TestNullTarget_CompletionNoCaching()
  info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Comments inside test: 
```
            // Make sure that the Completion task returned by a NullTarget
            // is not cached across all NullTargets.  Since it'll never complete,
```

**Comment by akoeplinger** [comment]
This actually fails on Desktop Mono as well occasionally, it looks more due to not having a precise GC.
