### ISSUE TITLE
SslStreamCertificateContext.Create can fail with ArgumentOutOfRangeException if root CA is missing

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#46654]
This is fork from https://github.com/dotnet/aspnetcore/issues/28584

simplified repro
```c#
           var ctx = SslStreamCertificateContext.Create(cert, additionalCertificates: null);
```
will throw  
```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at repro.Program.Main(String[] args) in /tmp/repro/Program.cs:line 46
```

**Comment by wfurt** [comment]
fixed by #46904
