### ISSUE TITLE
wasm AOT library test failure - System.Runtime.Serialization.InvalidDataContractException NoSetMethodForProperty

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46757]
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.Runtime.Serialization.Json.ReflectionOnly.Tests.csproj` fails with 
```
System.Runtime.Serialization.InvalidDataContractException : NoSetMethodForProperty

System.NotImplementedException : Arg_NotImplementedException
```
[SRSJR_fail.txt](https://github.com/dotnet/runtime/files/5788828/SRSJR_fail.txt)

Repro:
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Runtime.Serialization.Json/tests/ReflectionOnly/System.Runtime.Serialization.Json.ReflectionOnly.Tests.csproj`

**Comment by layomia** [comment]
cc @eerhardt since the description mentions linking.

**Comment by radical** [comment]
I get lot of test failures with just `EnableAggressiveTrimming`, and no AOT compilation. eg:

```
  fail: [FAIL] DataContractJsonSerializerTests.DCJS_VerifyDictionaryFormat
  info: System.Runtime.Serialization.InvalidDataContractException : NoSetMethodForProperty, System.Runtime.Serialization.KeyValue`2[System.String,System.String], Key
  info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
  info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message)
  info:    at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers()
  info:    at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type, XmlDictionaryString ns, String[] memberNames)
  info:    at System.Runtime.Serialization.ClassDataContract..ctor(Type type, XmlDictionaryString ns, String[] memberNames)
  info:    at System.Runtime.Serialization.ClassDataContract.CreateClassDataContractForKeyValue(Type type, XmlDictionaryString ns, String[] memberNames)
  info:    at System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.get_ItemContract()
  info:    at System.Runtime.Serialization.CollectionDataContract.InitCollectionDataContract(DataContract sharedTypeContract)
  info:    at System.Runtime.Serialization.CollectionDataContract..ctor(Type type, CollectionKind kind, Type itemType, MethodInfo getEnumeratorMethod, MethodInfo addMethod, ConstructorInfo constructor, Boolean isConstructorCheckRequired)
  info:    at System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(Type type, Boolean tryCreate, DataContract& dataContract, Type& itemType, Boolean constructorRequired)
  info:    at System.Runtime.Serialization.CollectionDataContract.TryCreate(Type type, DataContract& dataContract)
  info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
  info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
  info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
  info:    at System.Runtime.Serialization.DataContract.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
  info:    at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
  info:    at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type)
  info:    at System.Runtime.Serialization.DataContract.GetDataContract(Type type)
  info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.get_RootContract()
  info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
  info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
  info:    at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
  info:    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
  info:    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph)
  info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
  info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
  info:    at System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject(Stream stream, Object graph)
  info:    at DataContractJsonSerializerTests.SerializeAndDeserialize[Dictionary`2](Dictionary`2 value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
  info:    at DataContractJsonSerializerTests.DCJS_VerifyDictionaryFormat()
  info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

I think those need to be cleared before trying this with AOT.

**Comment by eerhardt** [comment]
@joperezr - can you investigate this along with #52083?

**Comment by joperezr** [comment]
Closing this as it appears to be fixed now. We are removing the last .rd.xml file on this PR https://github.com/dotnet/runtime/pull/57013 and it seems that after those changes both the EAT and the EAT_AOT test legs are all passing.
