### ISSUE TITLE
Test failure : SampleSynthesisTests.SpeechRecognizerTests.SpeechRecognizer

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#46800]
Job : [runtime-libraries-coreclr outerloop 20210110.2](https://dev.azure.com/dnceng/public/_build/results?buildId=944231&view=ms.vss-test-web.build-test-results-tab&runId=29799024&resultId=101487&paneView=debug)

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

**Error message:**
```
System.PlatformNotSupportedException : Speech Recognition is not available on this system. SAPI and Speech Recognition engines cannot be found.
```

**Stack trace:**
```
   at System.Speech.Internal.SapiInterop.SapiRecognizer..ctor(RecognizerType type) in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 32
   at SampleSynthesisTests.SpeechRecognizerTests.SpeechRecognizer() in /_/src/libraries/System.Speech/tests/SpeechRecognizerTests.cs:line 35
```

**Comment by BruceForstall** [comment]
@danmosemsft can you triage?
