### ISSUE TITLE
OpenSSL shared library issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by njlr** [dotnet/runtime#46946]
When I do `dotnet run`, the process crashes due to a broken library:

```
$ dotnet run
Unhandled exception. System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSystem.Security.Cryptography.Native.OpenSsl: cannot open shared object file: No such file or directory
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.EvpPkeyDestroy(IntPtr pkey)
   at System.Security.Cryptography.SafeEvpPKeyHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean disposeOrFinalizeOperation)
   at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```

My project targets `netcoreapp3.1`.

My Ubuntu version:

```bash
$ lsb_release -a 
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

My `dotnet` version:

```bash
$ dotnet --info                
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

My OpenSSL version:

```bash
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by danmosemsft** [comment]
Is `liblibSystem` above just a typo, or the actual message?

**Comment by njlr** [comment]
> Is `liblibSystem` above just a typo, or the actual message?

I copy-pasted all of the messages from the terminal, so should be real

**Comment by njlr** [comment]
I should also mention that this dual `5.0` / `3.1` setup is quite common because F# tooling (e.g. Ionide) has moved to `5.0` but AWS and other services are still on the last LTS version `3.1`.

**Comment by danmosemsft** [comment]
> I copy-pasted all of the messages from the terminal, so should be real

Looks like it's just because when we can't find the specified name, we try [variations](https://github.com/dotnet/runtime/issues/43313#issuecomment-754976207), and the error ends up using the last failed one.
