### ISSUE TITLE
X509Certificate2 in wcf client cannot be deserialize

### ISSUE THREAD

**Issue by borgez** [dotnet/runtime#46947]
```
System.Runtime.Serialization.InvalidDataContractException: There was an error while trying to deserialize parameter http://tempuri.org/:GetDocumentsResult.  Please see InnerException for more details.
 ---> System.Runtime.Serialization.InvalidDataContractException: Type 'System.Security.Cryptography.X509Certificates.X509Certificate2' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(Int32 id, RuntimeTypeHandle typeHandle)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadSignatureFileInfoFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadArrayOfSignatureFileInfoFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadSignedFileInfoDataContractFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadAttachmentDataContractFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadDocumentDataContractFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadArrayOfDocumentDataContractFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadDocumentsFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
```

**Comment by scalablecory** [comment]
@GrabYourPitchforks is x509cert2 serializable in the first place?

**Comment by StephenMolloy** [comment]
X509Certificate2 was marked as `[Serializable]` in .Net 4.8, but the attribute has been removed in .Net core. This prevents customers from serializing this class in .Net Core.

**Comment by GrabYourPitchforks** [comment]
.NET Core / .NET 5+ limits the set of inbox types which are marked as `[Serializable]`. The list of serializable types is now essentially limited to primitives, Exception-derived types, and a small handful of others to support critical resource scenarios. This is by-design. See https://docs.microsoft.com/dotnet/standard/serialization/binary-serialization#serializable-types for more information.

I would recommend one of two actions:

1. Change the object model being serialized such that it's not serializing the `X509Certificate2` instance directly. Instead, serialize the certificate's data (e.g., via `X509Certificate2.RawData`), then on the receiving side call `new X509Certificate2(byte[])` to rehydrate the certificate. __-- or --__

2. If you absolutely cannot change your object model, configure the serializer to use a serialization surrogate for `X509Certificate2`. That causes the serializer not to look for a `[Serializable]` implementation on the `X509Certificate2` type, but instead to call into your custom method which can serialize or deserialize these instances. Your custom surrogate would need to fall back to the certificate's raw data as described in (1) above.

@StephenMolloy Can you point to any good resources for configuring a serialization surrogate selector on `XmlReader` or `DataContractSerializer` / WCF?

**Comment by StephenMolloy** [comment]
I'm not aware of any great resources for configuring surrogates in .Net Core/5+. The mechanism for providing surrogates changed from the old .Net Framework to .Net Core and all the samples and blog posts I could find walk through the old way. For .Net Core/5+, we just have the bare-bones msdn API pages.  [DataContractSerializerExtensions.SetSerializationSurrogateProvider()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datacontractserializerextensions.setserializationsurrogateprovider?view=net-5.0#System_Runtime_Serialization_DataContractSerializerExtensions_SetSerializationSurrogateProvider_System_Runtime_Serialization_DataContractSerializer_System_Runtime_Serialization_ISerializationSurrogateProvider_) and [ISerializationSurrogateProvider ](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializationsurrogateprovider?view=net-5.0) The gist is you write a provider to handle all your surrogate work and then attach that to the DCS using the SetSerializationSurrogateProvider extension method.
