### ISSUE TITLE
Test failed: baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47097]
Job: [runtime-coreclr jitstress2-jitstressregs 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954780&view=ms.vss-test-web.build-test-results-tab)

Failed tests:
```
CoreCLR OSX x64 Checked jitstress2_jitstressregs0x10 @ OSX.1013.Amd64.Open
        - baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
```

Error message:
```
Process terminated. Parallel crash in main thread
   at System.Environment.FailFast(System.String)
   at ParallelCrash.Main(System.String[])
{0x3816c7-0x10fcdad40} ASSERT [DEBUG  ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
MachO coredumps are not supported. To enable ELF coredumps on MacOS, set the COMPlus_DbgEnableElfDumpOnMacOS environment variable to 1.
/private/tmp/helix/working/B05809F7/w/A684091E/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh: line 388: 11369 Trace/BPT trap: 5       (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/B05809F7/w/A684091E/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B05809F7/p/corerun ParallelCrash.dll ''
Expected: 134
Actual: 133
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B05809F7/p
> /private/tmp/helix/working/B05809F7/w/A684091E/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

stack trace:
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr outerloop 20210130.4](https://dev.azure.com/dnceng/public/_build/results?buildId=972972&view=ms.vss-test-web.build-test-results-tab&runId=30556198&paneView=debug&resultId=109538)

Failed tests:
```
R2R OSX x64 Checked @ OSX.1013.Amd64.Open
        - baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
```

Error message:
```
Process terminated. {0x1e87b4-0x1017e0a30} ASSERT [DEBUG  ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
Parallel crash in main thread
/private/tmp/helix/working/B28D09D0/w/AF7B0A01/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh: line 388: 77572 Trace/BPT trap: 5       $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/B28D09D0/w/AF7B0A01/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image ParallelCrash.dll generated successfully.

in ReleaseLock
in takeLock
/tmp/helix/working/B28D09D0/p/corerun ParallelCrash.dll ''
in ReleaseLock
Expected: 134
Actual: 133
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B28D09D0/p
> /private/tmp/helix/working/B28D09D0/w/AF7B0A01/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

stack trace:
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr jitstress-isas-x86 20210206.1](https://dev.azure.com/dnceng/public/_build/results?buildId=981920&view=ms.vss-test-web.build-test-results-tab&runId=30777528&resultId=109625&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked jitstress_isas_x86_nosse41 @ OSX.1013.Amd64.Open

  -baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
```

**Error message:**
```
Process terminated. Parallel crash in thread 8!

{0x21c4a6-0x109e5d520} ASSERT [DEBUG ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
 at System.Environment.FailFast(System.String)
 at ParallelCrash.CrashInParallel()
 at System.Threading.Thread.StartCallback()
/private/tmp/helix/working/A74E08D9/w/A4740937/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh: line 388: 504 Trace/BPT trap: 5 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/A74E08D9/w/A4740937/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A74E08D9/p/corerun ParallelCrash.dll ''
Expected: 134
Actual: 133
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/A74E08D9/p
> /private/tmp/helix/working/A74E08D9/w/A4740937/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual: False

Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()

```

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr jitstress2-jitstressregs 20210213.1](https://dev.azure.com/dnceng/public/_build/results?buildId=993930&view=ms.vss-test-web.build-test-results-tab&runId=31138846&resultId=109657&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked jitstress2_jitstressregs8 @ OSX.1013.Amd64.Open
 -baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
```

**Error message:**
```
Process terminated. Parallel crash in thread 10!

{0x2afaf3-0x10b60d050} ASSERT [DEBUG ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
 at System.Environment.FailFast(System.String)/private/tmp/helix/working/B59509C2/w/A901096D/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh: line 388: 15632 Trace/BPT trap: 5 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/B59509C2/w/A901096D/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B59509C2/p/corerun ParallelCrash.dll ''
Expected: 134
Actual: 133
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B59509C2/p
> /private/tmp/helix/working/B59509C2/w/A901096D/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual: False

Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()

```

**Comment by JulieLeeMSFT** [comment]
@sandreenko PTAL. It is failing on OSX.

**Comment by BruceForstall** [comment]
This is the same issue as https://github.com/dotnet/runtime/issues/47096
