### ISSUE TITLE
Assertion failed 'paddingToAdd == paddingNeeded'

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47094]
Job : [runtime-coreclr jitstressregs 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954707&view=results)

Failed test : 
```
CoreCLR windows x64 Checked jitstressregs2 @ Windows.10.Amd64.Open
        - JIT\\HardwareIntrinsics\\General\\Vector256_1\\Vector256_1_ro\\Vector256_1_ro.cmd
        - JIT\\HardwareIntrinsics\\General\\Vector128_1\\Vector128_1_ro\\Vector128_1_ro.cmd
```
Part of error message:
```
Assert failure(PID 548 [0x00000224], Thread: 972 [0x03cc]): Assertion failed 'paddingToAdd == paddingNeeded' in 'JIT.HardwareIntrinsics.General.VectorGetAndWithLowerAndUpper__GetAndWithLowerAndUpperInt16:ValidateWithResult(System.Int16[],System.Int16[],System.String):this' during 'Emit code' (IL size 291)

    File: F:\workspace\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 9417
    Image: C:\h\w\AB90094A\p\CoreRun.exe


Return code:      1

 ...  ...

Beginning scenario: RunBasicScenario
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AB90094A\p
> C:\h\w\AB90094A\w\AA5E0942\e\JIT\HardwareIntrinsics\General\Vector128_1\Vector128_1_ro\Vector128_1_ro.cmd

stack trace:
at JIT_HardwareIntrinsics._General_Vector256_1_Vector256_1_ro_Vector256_1_ro_._General_Vector256_1_Vector256_1_ro_Vector256_1_ro_cmd()
```

**Comment by danmosemsft** [comment]
```
C:\h\w\A4CC08D0\w\AFD5092E\e>"C:\h\w\A4CC08D0\p\dotnet.exe" exec --runtimeconfig System.Collections.Tests.runtimeconfig.json --depsfile System.Collections.Tests.deps.json xunit.console.dll System.Collections.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Collections.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Tests (found 5129 of 6996 test cases)
  Starting:    System.Collections.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 4600 [0x000011f8], Thread: 5480 [0x1568]): Assertion failed 'paddingToAdd == paddingNeeded' in 'System.Collections.Tests.LinkedList_Generic_Tests`1[Int32][System.Int32]:AddFirst_T_Tests():this' during 'Emit code' (IL size 758)

    File: F:\workspace\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 9417
    Image: C:\h\w\A4CC08D0\p\dotnet.exe

----- end Sun 01/17/2021  8:02:11.25 ----- exit code -1073740286 ----------------------------------------------------------
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-a7ab659486744286af/System.Collections.Tests/console.8126f33e.log?sv=2019-07-07&se=2021-02-06T07%3A44%3A02Z&sr=c&sp=rl&sig=%2B3OjyHflp76my8yr6R5LOnyMZhn8z1g97ZEJjIiyqxE%3D

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr jitstressregs 20210124.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963701&view=ms.vss-test-web.build-test-results-tab&runId=30351646&resultId=105206&paneView=attachments)

Failed tests:
```
CoreCLR windows x64 Checked jitstressregs2 @ Windows.10.Amd64.Open
       - JIT\\HardwareIntrinsics\\General\\Vector128_1\\Vector128_1_ro\\Vector128_1_ro.cmd
       - JIT\\HardwareIntrinsics\\General\\Vector256_1\\Vector256_1_ro\\Vector256_1_ro.cmd
```

Part of error message:
```
Assert failure(PID 5484 [0x0000156c], Thread: 5308 [0x14bc]): Assertion failed 'paddingToAdd == paddingNeeded' in 'JIT.HardwareIntrinsics.General.VectorGetAndWithLowerAndUpper__GetAndWithLowerAndUpperInt16:ValidateWithResult(System.Int16[],System.Int16[],System.String):this' during 'Emit code' (IL size 291)

    File: F:\workspace\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 9417
    Image: C:\h\w\B0CB09D6\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\B0CB09D6\w\AB300931\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\General\Vector256_1\Vector256_1_ro\Vector256_1_ro.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B0CB09D6\p\corerun.exe" Vector256_1_ro.dll 
Beginning test case Zero.Byte at 1/24/2021 12:41:47 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario

Ending test case at 1/24/2021 12:41:47 PM
Beginning test case Zero.Double at 1/24/2021 12:41:47 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

... ...

Beginning scenario: RunBasicScenario
Beginning scenario: RunReflectionScenario

Ending test case at 1/24/2021 12:41:52 PM
Beginning test case GetAndWithLowerAndUpper.Int16 at 1/24/2021 12:41:52 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B0CB09D6\p
> C:\h\w\B0CB09D6\w\AB300931\e\JIT\HardwareIntrinsics\General\Vector256_1\Vector256_1_ro\Vector256_1_ro.cmd

stack trace:
   at JIT_HardwareIntrinsics._General_Vector256_1_Vector256_1_ro_Vector256_1_ro_._General_Vector256_1_Vector256_1_ro_Vector256_1_ro_cmd()
``

**Comment by mateoatr** [comment]
It seems that we are hitting this assertion again on win x86 [runtime-coreclr jitstressregs 20210629.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1212545&view=results)

**Comment by kunalspathak** [comment]
I do see these failures in https://dev.azure.com/dnceng/public/_build/results?buildId=1215016&view=ms.vss-test-web.build-test-results-tab&runId=36268938&resultId=110293&paneView=debug . May be it got introduced recently. I will keep an eye.
