### ISSUE TITLE
Test failed: baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47096]
Job : [runtime-coreclr jitstressregs 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954707&view=results)

Failed test : 
```
CoreCLR OSX x64 Checked jitstressregs0x1000 @ OSX.1013.Amd64.Open
        - baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```
Error message:
```
Process terminated. Parallel crash in thread 6!

{0x1bc56e-0x10e475d40} ASSERT [DEBUG  ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
   at System.Environment.FailFast(System.String)
   at ParallelCrash.CrashInParallel()
   at System.Threading.Thread.StartCallback()
../ParallelCrash/ParallelCrash.sh: line 388: 47592 Trace/BPT trap: 5       $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/B90009AF/w/B8D909CB/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/B90009AF/w/B8D909CB/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/tmp/helix/working/B90009AF/p/corerun ParallelCrash.dll '2'
Expected: 134
Actual: 133
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B90009AF/p
> /private/tmp/helix/working/B90009AF/w/B8D909CB/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

stack trace:
at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress-isas-x86 20210123.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963523&view=ms.vss-test-web.build-test-results-tab&runId=30347842&resultId=110361&paneView=debug)

Failed tests:
```
CoreCLR OSX x64 Checked jitstress_isas_x86_nopclmulqdq @ OSX.1013.Amd64.Open
        - baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```

Error message:
```
Process terminated. Parallel crash in thread 2!

   at System.Environment.FailFast(System.String)
   at ParallelCrash.CrashInParallel()
   at System.Threading.Thread.StartCallback()
{0x2561a7-0x109a095b0} ASSERT [DEBUG  ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
../ParallelCrash/ParallelCrash.sh: line 388: 48391 Trace/BPT trap: 5       (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/A60C08B9/w/AE65094C/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/A60C08B9/w/AE65094C/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/tmp/helix/working/A60C08B9/p/corerun ParallelCrash.dll '2'
Expected: 134
Actual: 133
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/A60C08B9/p
> /private/tmp/helix/working/A60C08B9/w/AE65094C/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

stack trace:
   at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr outerloop 20210204.1](https://dev.azure.com/dnceng/public/_build/results?buildId=978862&view=ms.vss-test-web.build-test-results-tab&runId=30714354&resultId=109183&paneView=debug)

Failed test:
```
R2R OSX x64 Checked @ OSX.1013.Amd64.Open
     -baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```



**Error message:**
```
Process terminated. Parallel crash in thread 7!

{0xbd8af-0x10dcba770} ASSERT [DEBUG ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
 at System.Environment.FailFast(System.String)
../ParallelCrash/ParallelCrash.sh: line 388: 80281 Trace/BPT trap: 5 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/B68C0958/w/B2640952/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/B68C0958/w/B2640952/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
in takeLock
/tmp/helix/working/B68C0958/p/corerun ParallelCrash.dll '2'
in ReleaseLock
Expected: 134
Actual: 133
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B68C0958/p
> /private/tmp/helix/working/B68C0958/w/B2640952/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
Expected: True
Actual: False

Stack trace
   at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()

```

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr jitstress 20210216.2](https://dev.azure.com/dnceng/public/_build/results?buildId=997975&view=ms.vss-test-web.build-test-results-tab&runId=31232472&resultId=109662&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked jitstress1_tiered @ OSX.1013.Amd64.Open
 -baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```

**Error message:**
```
Process terminated. Parallel crash in thread 6!

{0x43b3fe-0x10b560570} ASSERT [DEBUG ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
 at System.Environment.FailFast(System.String)
 at ParallelCrash.CrashInParallel()
 at System.Threading.Thread.StartCallback()
../ParallelCrash/ParallelCrash.sh: line 388: 57822 Trace/BPT trap: 5 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /private/tmp/helix/working/9687085E/w/AE4009B4/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/9687085E/w/AE4009B4/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/tmp/helix/working/9687085E/p/corerun ParallelCrash.dll '2'
Expected: 134
Actual: 133
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/9687085E/p
> /private/tmp/helix/working/9687085E/w/AE4009B4/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
Expected: True
Actual: False

Stack trace
   at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()
```

**Comment by JulieLeeMSFT** [comment]
@Sergey for the failure on OSX.

**Comment by BruceForstall** [comment]
This doesn't require jitstress: it can be repro'ed with a basic run.

The problem is a failure in `OutputDebugStringW`: the call to `WideCharToMultiByte` fails:
```
/Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
```

This appears to only happen when the FailFast happens in the worker threads, not in the main thread (of this test). It can sometimes repro in the `ParallelCrash` case, which can FailFast in the worker threads, but I haven't seen it fail in `ParallelCrashMainThread`. In the `ParallelCrashWorkerThreads` case, it mostly fails in the first 50 runs, when run in a loop.

Since this appears to be a PAL problem (maybe only on Mac?), I'm changing the area to PAL from codegen.

@trylek @janvorli

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstressregs 20210227.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1015245&view=ms.vss-test-web.build-test-results-tab&runId=31617474&resultId=109670&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked jitstressregs4 @ OSX.1013.Amd64.Open
 
-baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```

**Error message:**
```
Process terminated. Parallel crash in thread 10!

{0x1aee7a-0x1063c1110} ASSERT [DEBUG ] at /Users/runner/work/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
 at System.Environment.FailFast(System.String)
 at ParallelCrash.CrashInParallel()
 at System.Threading.Thread.StartCallback()
../ParallelCrash/ParallelCrash.sh: line 388: 36311 Trace/BPT trap: 5 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
MachO coredumps are not supported. To enable ELF coredumps on MacOS, set the COMPlus_DbgEnableElfDumpOnMacOS environment variable to 1.

Return code: 1
Raw output file: /private/tmp/helix/working/B48709E5/w/BAAC09CC/e/baseservices/exceptions/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/B48709E5/w/BAAC09CC/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/tmp/helix/working/B48709E5/p/corerun ParallelCrash.dll '2'
Expected: 134
Actual: 133
END EXECUTION - FAILED
Expected: 0
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B48709E5/p
> /private/tmp/helix/working/B48709E5/w/BAAC09CC/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
Expected: True
Actual: False

Stack trace
   at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()

```

**Comment by BruceForstall** [comment]
@mangod9 please triage

**Comment by mangod9** [comment]
Does this fail only with jitstress? We will take a look.

**Comment by BruceForstall** [comment]
> Does this fail only with jitstress?

no (I mentioned that above)

**Comment by mangod9** [comment]
Ok sorry missed that. Unless this is urgent it will have to wait till JanV is back.

**Comment by VincentBu** [comment]
Test `baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh` failed in [runtime-coreclr r2r-extra 20210502.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1118182&view=ms.vss-test-web.build-test-results-tab&runId=34044782&resultId=110345&paneView=debug)

**Error message:**
```
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exists
mkdir: cannot create directory ‘lock’: File exis

Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()

```

**Comment by janvorli** [comment]
I have investigated the issue. The problem is that `SystemNative::GenericFailFast` uses a global buffer for messages shorter than certain size. The failing test has many threads intentionally failing with FailFast at once, so the message in the buffer gets overwritten by possibly multiple threads at once. The `OutputDebugString` that's called from PAL to output the error message calls `WideCharToMultiByte` on the buffer twice - once with -1 as the target length to get the necessary target size and then second time to perform the conversion. In the problematic case, the first one sees a shorter message and the second sees a longer one. 
For example, the message is `Parallel crash in thread 5!` and then it is overwritten in place by `Parallel crash in thread 10!`. So we allocate a buffer for the target of the conversion based on the first invocation and the 2nd invocation of the `WideCharToMultiByte` doesn't get large enough buffer for the longer string.
