### ISSUE TITLE
Test failed: JIT\\Directed\\cmov\\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47101]
Job: [runtime-coreclr r2r-extra 20210116.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954601&view=ms.vss-test-web.build-test-results-tab&runId=30120948&paneView=attachments&resultId=107642)

Failed tests:
```
R2R windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
R2R Linux x64 Checked jitstress2_tiered @ Ubuntu.1804.Amd64.Open
R2R windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
R2R windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
R2R windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
R2R Linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open
R2R windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open
R2R Linux x64 Checked jitstress1 @ Ubuntu.1804.Amd64.Open
R2R windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open
R2R windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
R2R windows x64 Checked jitstress2 @ Windows.10.Amd64.Open
R2R Linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open
R2R Linux arm64 Checked jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
R2R Linux arm64 Checked jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
R2R Linux arm64 Checked jitstress2_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
R2R Linux arm64 Checked jitstress1_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
R2R Linux arm64 Checked jitstress2_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
R2R windows arm64 Checked jitstress1_tiered @ Windows.10.Arm64v8.Open
R2R windows arm64 Checked jitstress1 @ Windows.10.Arm64v8.Open
R2R Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
R2R Linux arm Checked jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
R2R Linux arm Checked jitstress1_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
R2R Linux arm Checked jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
R2R windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open
        - JIT\\Directed\\cmov\\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.cmd
```

Error message:
```
Return code:      1
Raw output file:      C:\h\w\B95209CD\w\B6530A21\e\JIT\Directed\Reports\JIT.Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
" "C:\h\w\B95209CD\p\crossgen.exe"  /Platform_Assemblies_Paths C:\h\w\B95209CD\p;C:\h\w\B95209CD\w\B6530A21\e\JIT\Directed\cmov\Float_And_Op_cs_ro /in C:\h\w\B95209CD\w\B6530A21\e\JIT\Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.org /out C:\h\w\B95209CD\w\B6530A21\e\JIT\Directed\cmov\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image C:\h\w\B95209CD\w\B6530A21\e\JIT\Directed\cmov\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.dll generated successfully.
 "C:\h\w\B95209CD\p\corerun.exe" Float_And_Op_cs_ro.dll 
FAILED
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B95209CD\p
> C:\h\w\B95209CD\w\B6530A21\e\JIT\Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.cmd

stack trace:
   at JIT_Directed._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_cmd()
```

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib all-platform failure in R2R run of Float_And_Op_cs_ro

**Comment by VincentBu** [comment]
Failed again in run (almost every job) [runtime-coreclr r2r-extra 20210123.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963625&view=ms.vss-test-web.build-test-results-tab&runId=30349622&resultId=107828&paneView=debug)

Part of failed tests:
```
R2R windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
       - JIT\\Directed\\cmov\\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.cmd
```

Error message:
```
Return code:      1
Raw output file:      C:\h\w\C3A80A52\w\B58A09D4\e\JIT\Directed\Reports\JIT.Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.output.txt
Raw output:
BEGIN EXECUTION
        1 file(s) copied.
" "C:\h\w\C3A80A52\p\crossgen.exe"  /Platform_Assemblies_Paths C:\h\w\C3A80A52\p;C:\h\w\C3A80A52\w\B58A09D4\e\JIT\Directed\cmov\Float_And_Op_cs_ro /in C:\h\w\C3A80A52\w\B58A09D4\e\JIT\Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.org /out C:\h\w\C3A80A52\w\B58A09D4\e\JIT\Directed\cmov\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image C:\h\w\C3A80A52\w\B58A09D4\e\JIT\Directed\cmov\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.dll generated successfully.
 "C:\h\w\C3A80A52\p\corerun.exe" Float_And_Op_cs_ro.dll 
FAILED
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\C3A80A52\p
> C:\h\w\C3A80A52\w\B58A09D4\e\JIT\Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.cmd

stack trace:
   at JIT_Directed._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_cmd()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr r2r-extra 20210130.1](https://dev.azure.com/dnceng/public/_build/results?buildId=973100&view=ms.vss-test-web.build-test-results-tab&runId=30558630&resultId=108221&paneView=debug)

Failed tests:
```
R2R Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
    - JIT/Directed/cmov/Float_And_Op_cs_ro/Float_And_Op_cs_ro.sh
```

Error message:
```
Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/Directed/Reports/JIT.Directed/cmov/Float_And_Op_cs_ro/Float_And_Op_cs_ro.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image Float_And_Op_cs_ro.dll generated successfully.

in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun Float_And_Op_cs_ro.dll ''
FAILED
in ReleaseLock
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Directed/cmov/Float_And_Op_cs_ro/Float_And_Op_cs_ro.sh

stack trace:
   at JIT_Directed._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_sh()
```

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr r2r-extra 20210214.1](https://dev.azure.com/dnceng/public/_build/results?buildId=994631&view=ms.vss-test-web.build-test-results-tab&runId=31155302&resultId=108123&paneView=debug)

Failed test:
```
R2R windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
 -JIT\\Directed\\cmov\\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\A6B808F1\w\A220095F\e\JIT\Directed\Reports\JIT.Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.output.txt
Raw output:
BEGIN EXECUTION
 1 file(s) copied.
" "C:\h\w\A6B808F1\p\crossgen.exe" /Platform_Assemblies_Paths C:\h\w\A6B808F1\p;C:\h\w\A6B808F1\w\A220095F\e\JIT\Directed\cmov\Float_And_Op_cs_ro /in C:\h\w\A6B808F1\w\A220095F\e\JIT\Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.org /out C:\h\w\A6B808F1\w\A220095F\e\JIT\Directed\cmov\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation. All rights reserved.

Native image C:\h\w\A6B808F1\w\A220095F\e\JIT\Directed\cmov\Float_And_Op_cs_ro\\Float_And_Op_cs_ro.dll generated successfully.
 "C:\h\w\A6B808F1\p\corerun.exe" Float_And_Op_cs_ro.dll 
FAILED
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A6B808F1\p
> C:\h\w\A6B808F1\w\A220095F\e\JIT\Directed\cmov\Float_And_Op_cs_ro\Float_And_Op_cs_ro.cmd
Expected: True
Actual: False

Stack trace
   at JIT_Directed._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_._cmov_Float_And_Op_cs_ro_Float_And_Op_cs_ro_cmd()

```

**Comment by JulieLeeMSFT** [comment]
@kunalspathak This test repeatedly fails. PTAL.

**Comment by kunalspathak** [comment]
> @kunalspathak This test repeatedly fails. PTAL.

Yes, I have started looking into it this morning. I was able to repro it on my local machine.

**Comment by kunalspathak** [comment]
I spent some time debugging this  and the problematic code generated is for https://github.com/dotnet/runtime/blob/51d8e98159adbd60943a6449a221ee003f427608/src/tests/JIT/Directed/cmov/Float_And_Op.cs#L13742 

Here, `t1_i.mfb_false = false`. We create the tree to be:

```cmd
if (B46) {
   B48  ;  3.1F
} else {
   B47  ; ab[index - 1] 
}
```

After block renumbering, it turns to

```cmd
if (B35) {
   B31  ; 3.1F
} else {
   B36  ; ab[index - 1] 
}
```

However, during assertion propagation, we conclude that `B35` is always true and we unconditionally jump to `B31`.

```
 in BB35 as useless:

BB35 becomes empty

Conditional folded at BB35
BB35 becomes a BBJ_ALWAYS to BB31
```

Here is the dump file.
[float-ngen-dump.txt](https://github.com/dotnet/runtime/files/6008867/float-ngen-dump.txt)

I will investigate further tomorrow.

**Comment by kunalspathak** [comment]
So it looks like jmp threading in https://github.com/dotnet/runtime/pull/46257 has something to do. When I turn it off, things are generated correctly.
