### ISSUE TITLE
Test failed: System.Net.NameResolution.Tests.GetHostEntryTest.DnsGetHostEntry_LocalHost_AddressFamilySpecific

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47103]
Job: [runtime-libraries-coreclr outerloop 20210117.2](https://dev.azure.com/dnceng/public/_build/results?buildId=954714&view=ms.vss-test-web.build-test-results-tab&runId=30122550&paneView=debug&resultId=102125)

Failed tests:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759
        - System.Net.NameResolution.Tests.GetHostEntryTest.DnsGetHostEntry_LocalHost_AddressFamilySpecific(useAsync: True, host: \"localhost\", addressFamily: InterNetwork)
        - System.Net.NameResolution.Tests.GetHostAddressesTest.DnsGetHostAddresses_LocalHost_AddressFamilySpecific(useAsync: True, host: \"localhost\", addressFamily: InterNetwork)


```

Error message:
```
Assert.All() Failure: 1 out of 2 items in the collection did not pass.\n[0]: Item: ::1\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: InterNetwork\n     Actual:   InterNetworkV6\n        at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40\n at Xunit.Assert.Equal[T](T expected, T actual) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 24\n at System.Net.NameResolution.Tests.GetHostEntryTest.<>c__DisplayClass15_0.<DnsGetHostEntry_LocalHost_AddressFamilySpecific>b__0(IPAddress address) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 242\n at Xunit.Assert.All[T](IEnumerable1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36

stack trace:
   at System.Net.NameResolution.Tests.GetHostEntryTest.DnsGetHostEntry_LocalHost_AddressFamilySpecific(Boolean useAsync, String host, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 242
--- End of stack trace from previous location ---
```

**Comment by wfurt** [comment]
I'm wondering if the resolver can return different address family beyond hint

cc: :  @gfoidl @scalablecory

**Comment by gfoidl** [comment]
I believe to hunted the 🐛 down. Need to verify that's the cause, then a PR will come.

**Comment by gfoidl** [comment]
https://github.com/dotnet/runtime/pull/47171 should (hopefully) fix the problem.
