### ISSUE TITLE
iOS: Attempting to JIT compile method '(wrapper dynamic-method) void object:WriteArrayOfintToXml (System.Runtime.Serialization.XmlWriterDelegator,object,System.Runtime.Serialization.XmlObjectSerializerWriteContext,System.Runtime.Serialization.CollectionDataContract)' while running in aot-only mode.

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#47114]
### Description

The following code throws an exception at runtime when running on an iOS device:

```csharp
var ds = new DataContractSerializer (typeof (IEnumerable<int>));
using (var xw = XmlWriter.Create (System.IO.Stream.Null))
	ds.WriteObject (xw, new int [] { 1, 2, 3 });
```

Exception:

```csharp
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) void object:WriteArrayOfintToXml (System.Runtime.Serialization.XmlWriterDelegator,object,System.Runtime.Serialization.XmlObjectSerializerWriteContext,System.Runtime.Serialization.CollectionDataContract)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
    at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
    at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
    at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
    at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
    at System.Runtime.Serialization.CodeGenerator.EndMethod()
    at System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter(CollectionDataContract collectionContract)
    at System.Runtime.Serialization.XmlFormatWriterGenerator.GenerateCollectionWriter(CollectionDataContract collectionContract)
    at System.Runtime.Serialization.CollectionDataContract.CreateXmlFormatWriterDelegate()
    at System.Runtime.Serialization.CollectionDataContract.get_XmlFormatWriterDelegate()
    at System.Runtime.Serialization.CollectionDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)
    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
    at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph)
    at System.Runtime.Serialization.DataContractSerializer.WriteObject(XmlWriter writer, Object graph)
    at MySingleView.AppDelegate.FinishedLaunching(UIApplication app, NSDictionary options) in /Users/rolf/work/maccore/onedotnet/xamarin-macios/tests/dotnet/MySingleView/AppDelegate.cs:line 45
```

Repro:

```shell
git clone https://github.com/rolfbjarne/xamarin-macios
cd xamarin-macios
git checkout dotnet-attempting-to-jit-compile-method-WriteArrayOfintToXml
./configure --enable-dotnet
make reset
make all -j8
make install -j8
make singleview -C tests/dotnet
```

[Complete output](https://gist.github.com/rolfbjarne/ecf64299d14ff91fc1223f29ec6d09f2)

### Configuration

.NET 6.0.100-alpha.1.21060.3

Binlog: 
[MySingleView.binlog.zip](https://github.com/dotnet/runtime/files/5829997/MySingleView.binlog.zip)

### Regression?

No (new feature)

**Comment by steveisok** [comment]
@vargaz should this work?

**Comment by vargaz** [comment]
Not likely, dynamic methods will only work with the interpreter.

**Comment by rolfbjarne** [comment]
> @vargaz should this work?

The test case is C# code that works in current versions of Xamarin.iOS, so one possibility is that it's the BCL that has changed.

**Comment by steveisok** [comment]
I suspect we may want to hit this code path instead

https://github.com/dotnet/runtime/blob/39e8a6e0b0a53e621cd997b53122663a4ae114f0/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlFormatWriterGenerator.cs#L109-L112

Which may mean setting this to be ReflectionOnly for iOS https://github.com/dotnet/runtime/blob/39e8a6e0b0a53e621cd997b53122663a4ae114f0/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializer.cs#L37

@danmoseley who would be the best person to help us confirm this is the right approach?  For iOS devices, we basically can't generate any IL on the fly.

**Comment by MaximLipnin** [comment]
It's reproducible against the simulator when executing
```
1. ./build.sh -os iOSSimulator -arch x64 -c Release -s mono+libs
2. ./dotnet.sh build /t:Test /p:TargetOS=iOSSimulator /p:TargetArchitecture=x64 /p:Configuration=Release /p:RunAOTCompilation=true  /p:EnableAggressiveTrimming=true src/tests/FunctionalTests/iOS/Simulator/AOT/iOS.Simulator.Aot.Test.csproj
```
and using the code from the issue description as a functional test

**Comment by MaximLipnin** [comment]
The issue should be fixed now by https://github.com/dotnet/runtime/pull/55503, so closing it.
