### ISSUE TITLE
[browser] System.Composition.AttributeModel.Tests work item failing with OperationCanceledException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#47116]
```
ChromeDriver was started successfully.
[04:15:03] crit: System.OperationCanceledException: The operation was canceled.
                    at System.Net.HttpWebRequest.GetResponse()
                    at OpenQA.Selenium.DriverService.get_IsInitialized()
                    at OpenQA.Selenium.DriverService.WaitForServiceInitialization()
                    at OpenQA.Selenium.DriverService.Start()
                    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
                    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
                    at OpenQA.Selenium.Chromium.ChromiumDriver..ctor(ChromiumDriverService service, ChromiumOptions options, TimeSpan commandTimeout)
                    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.GetChromeDriver(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 165
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 59
                    at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 120
XHarness exit code: 71
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47100-merge-0bc7cf5303d046d1ac/System.Composition.AttributeModel.Tests/console.93cf64b1.log?sv=2019-07-07&se=2021-02-07T04%3A10%3A08Z&sr=c&sp=rl&sig=DQo6v2%2B7ur46QxSB%2BbZJVy0C0ICY%2ByrlaWP8xoEB1EI%3D

https://dev.azure.com/dnceng/public/_build/results?buildId=954947&view=ms.vss-test-web.build-test-results-tab&runId=30127400&resultId=142602&paneView=attachments

cc @akoeplinger

**Comment by ViktorHofer** [comment]
Closing as probably a one-off.
