### ISSUE TITLE
x64 aot: Image is too small

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#47154]
### Description

Crossgen2 fails during compiling of system dll on x64 with message:
```
Error: Image is too small.
System.BadImageFormatException: Image is too small.
   at System.Reflection.Throw.ImageTooSmall() in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/Throw.cs:line 236
   at System.Reflection.PortableExecutable.SectionHeader..ctor(PEBinaryReader& reader) in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/SectionHeader.cs:line 101
   at System.Reflection.PortableExecutable.PEHeaders.ReadSectionHeaders(PEBinaryReader& reader) in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEHeaders.cs:line 305
...
```
Build with:
```bash
$./build.sh -subset clr+libs -configuration release
```
Launch:
```
$ /home/tmustafin/dotnet/x64_runtime//corerun /home/tmustafin/dotnet/x64_runtime//crossgen2/crossgen2.dll '-r:/home/tmustafin/dotnet/x64_runtime//*' '-r:/home/tmustafin/dotnet/x64_runtime//crossgen2/*' -o:/home/tmustafin/dotnet/x64_runtime/crossgen2/crossgen2.ni.dll /home/tmustafin/dotnet/x64_runtime/crossgen2/crossgen2.dll
```
<details><summary>Full log for crossgen2/crossgen2.dll</summary>

```
Error: Image is too small.
System.BadImageFormatException: Image is too small.
   at System.Reflection.Throw.ImageTooSmall() in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/Throw.cs:line 236
   at System.Reflection.PortableExecutable.SectionHeader..ctor(PEBinaryReader& reader) in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/SectionHeader.cs:line 101
   at System.Reflection.PortableExecutable.PEHeaders.ReadSectionHeaders(PEBinaryReader& reader) in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEHeaders.cs:line 305
   at System.Reflection.PortableExecutable.PEHeaders..ctor(Stream peStream, Int32 size, Boolean isLoadedImage) in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEHeaders.cs:line 82
   at System.Reflection.PortableExecutable.PEReader.InitializePEHeaders() in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs:line 324
   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory() in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs:line 552
   at Internal.TypeSystem.Ecma.PortablePdbSymbolReader.TryOpenEmbedded(PEReader peReader, MetadataStringDecoder stringDecoder)
   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding)
   at ILCompiler.CompilerTypeSystemContext.GetModuleForSimpleName(String simpleName, Boolean throwIfNotFound)
   at ILCompiler.CompilerTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound)
   at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
   at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
   at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
   at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key)
   at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle)
   at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle handle)
   at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType()
   at Internal.TypeSystem.Ecma.EcmaType.get_BaseType()
   at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.TypeDesc.get_IsIntrinsic()
   at ILCompiler.InstructionSetSupport.GetHardwareIntrinsicId(TargetArchitecture architecture, TypeDesc potentialTypeDesc)
   at ILCompiler.HardwareIntrinsicHelpers.IsHardwareIntrinsic(MethodDesc method)
   at Internal.JitInterface.CorInfoImpl.ShouldSkipCompilation(MethodDesc methodNeedingCode)
   at ILCompiler.ReadyToRunRootProvider.RootMethods(TypeDesc type, String reason, IRootingServiceProvider rootProvider)
   at ILCompiler.ReadyToRunRootProvider.AddCompilationRoots(IRootingServiceProvider rootProvider)
   at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 compilationRoots, ILProvider ilProvider, DevirtualizationManager devirtualizationManager, IEnumerable`1 modulesBeingInstrumented, Logger logger, InstructionSetSupport instructionSetSupport)
```
</details>

State on 54953538be9e7e20eccc90b271edfd01210cf6a8.
Build and run on x64 Ubuntu 18.04.

[List of failed dlls](https://github.com/dotnet/runtime/files/5835511/Image_is_too_small.txt).

cc @jkotas @alpencolt @gbalykov

**Comment by jkotas** [comment]
cc @dotnet/crossgen-contrib 

@trylek Do we see this failure in crossgen2 test runs?

**Comment by MichalStrehovsky** [comment]
Is this actually opening PE files? The command line above has `'-r:/home/tmustafin/dotnet/x64_runtime//*'` which would syphon garbage files as input. The "List of failed dlls." list has files with `.out` extension. Are those .NET assemblies?

**Comment by gbalykov** [comment]
Could you, please, clarify the correct approach for crossgen2 usage regarding `-r` option. If we leave it as `-r:$DIR/`, then non-pe files will be processed. Should we use `-r:$DIR/*.dll` then? What will happen if there are both ni.dll and dll (which both are processed under *.dll) for some lib? Will this be processed correctly? Or do we need to specify full path to each lib like `-r:$DIR/SPC.dll`, etc?

**Comment by MichalStrehovsky** [comment]
The support for wildcards (`*`) is mostly a convenience for developer inner loop. Unless the input directory is 100% under control, it's recommended to specify individual file names instead, especially from scripts.

Specifying `*.dll` is the next best thing since at least it will avoid seeing multiple files for the same "simple name" (the file name without extension).

The .dll/.ni.dll files will probably not cause problems since the crossgen2 binder does not support ni.dll (the "magic" thing about "X.ni.dll" files is that they can be treated as assemblies for "X" (without the ni) in CoreCLR - crossgen2 will only look at X.dll/X.exe - X.ni.dll is treated as an assembly with a different name in crossgen2 ("X.ni" instead of "X").

**Comment by gbalykov** [comment]
@MichalStrehovsky thanks for clarification!

**Comment by t-mustafin** [comment]
> Is this actually opening PE files? The command line above has `'-r:/home/tmustafin/dotnet/x64_runtime//*'` which would syphon garbage files as input. The "List of failed dlls." list has files with `.out` extension. Are those .NET assemblies?

No, `.out` files contains a text output from corresponding crossgen2 launch.
Thanks for response, use `-r:$DIR/*.dll` fixes that issue.

**Comment by trylek** [comment]
For @jkotas' question - no, I have never seen this before. For now I presume that the closure here is that this particular problem was caused by issues with Crossgen2 command line syntax, not its functionality.
