### ISSUE TITLE
NonDisposedSocket_SafeHandlesCollected test failed on OSX

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#47190]
The NonDisposedSocket_SafeHandlesCollected test failed on leg `runtime (Libraries Test Run release coreclr OSX x64 Debug)` in my PR https://github.com/dotnet/runtime/pull/47017.

See the following logs

https://dev.azure.com/dnceng/public/_build/results?buildId=956499&view=logs&j=4724cd84-0a26-56bc-9b1d-ca1983f340b0&t=bd2814f3-22fe-5d50-acb1-9c92a93a7f5f&l=79

https://helix.dot.net/api/2019-06-17/jobs/f6042aeb-919a-4f53-a79e-ce250a9df0b2/workitems/System.Net.Sockets.Tests/console

```
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 921 of 1338 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 4)
    System.Net.Sockets.Tests.DisposedSocket.NonDisposedSocket_SafeHandlesCollected(clientAsync: False) [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Socket is already connected 127.0.0.1:51579
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3523,0): at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(873,0): at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DisposedSocketTests.cs(800,0): at System.Net.Sockets.Tests.DisposedSocket.CreateHandlesAsync(Boolean clientAsync)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DisposedSocketTests.cs(755,0): at System.Net.Sockets.Tests.DisposedSocket.NonDisposedSocket_SafeHandlesCollected(Boolean clientAsync)
        --- End of stack trace from previous location ---
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
  Finished:    System.Net.Sockets.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 1316, Errors: 0, Failed: 1, Skipped: 1, Time: 8.496s
```

**Comment by hoyosjs** [comment]
So far this is the only instance. Will continue to monitor.

**Comment by karelz** [comment]
Addressed by #50279 -- no failures after 3/26, while there were 30 failures between 3/23-3/26.

Note: One exceptional failure on PR #50191 on 3/29, likely with older source code.
