### ISSUE TITLE
Internal CLR error in PEWriter.WritePEToStream

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/runtime#47250]
Build log: https://dev.azure.com/dnceng/public/_build/results?buildId=958976&view=logs&j=7817cc08-46f6-529a-b675-9c2d2b016c0b&t=8c177619-984e-58de-5e95-103fbf6e1f0a

Artifacts: (includes dump file) https://dev.azure.com/dnceng/public/_build/results?buildId=958976&view=artifacts&pathAsName=false&type=publishedArtifacts

Also attaching the run logs here but not the dump file due to size.
[runtests.log](https://github.com/dotnet/roslyn/files/5845670/runtests.log)
[xUnitFailure-Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4.log](https://github.com/dotnet/roslyn/files/5845671/xUnitFailure-Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4.log)

This occurred in the Test_Windows_CoreClr_Release job. Wondering if we should file this on dotnet/runtime or if we need to first change some configs and keep running CI to try and repro the failure with the diagnostic info they need. @jkotas could you please advise?

```log
Command: test "Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll" --filter "Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.UnsafeTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.UsingStatementTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.WinMdDelegateTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.WinMdDelegateTests+VerifyType|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenInParametersTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenReadOnlyStructTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenRefLocalTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenRefReadOnlyReturnTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGenStackAllocInitializerTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DesktopStrongNameProviderTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CodeGenScriptTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests+TestPEBuilder|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CompilationEmitTests+TestResourceSectionBuilder|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.CovariantReturnTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.DeterministicTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.DeterministicTests+WriteOnlyStream|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EmitCustomModifiers|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EndToEndTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.EntryPointTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.InAttributeModifierTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.OptionalArgumentsTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.Perf|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.ResourceTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Emit.UnmanagedTypeModifierTests|Microsoft.CodeAnalysis.CSharp.UnitTests.EmitErrorTests|Microsoft.CodeAnalysis.CSharp.UnitTests.EmitMetadata|Microsoft.CodeAnalysis.CSharp.UnitTests.InternalsVisibleToAndStrongNameTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.CheckSumTest|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.CSharpDeterministicBuildCompilationTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.CSharpPDBTestBase|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBAsyncTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBConstantTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBDynamicLocalsTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBEmbeddedSourceTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBIteratorTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLambdaTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBSourceLinkTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBTupleTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBUsingTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBWinMdExpTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PortablePdbTests|Microsoft.CodeAnalysis.CSharp.UnitTests.PrivateProtected|Microsoft.CodeAnalysis.CSharp.UnitTests.ReadOnlyStruct|Microsoft.CodeAnalysis.CSharp.UnitTests.RefReturnTests" --framework net5.0 --logger "xunit;LogFilePath=F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4_net5.0_x86_test_results.xml"
xUnit output log: F:\workspace\_work\1\s\artifacts\log\Release\xUnitFailure-Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.4.log
The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)
   at System.IO.MemoryStream.set_Capacity(Int32)
   at System.IO.MemoryStream.EnsureCapacity(Int32)
   at System.IO.MemoryStream.Write(Byte[], Int32, Int32)
   at System.Reflection.Metadata.BlobBuilder.WriteContentTo(System.IO.Stream)
   at Microsoft.Cci.PeWriter.WritePeToStream(Microsoft.CodeAnalysis.Emit.EmitContext, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, Boolean, System.Nullable`1<System.Security.Cryptography.RSAParameters>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CommonMessageProvider, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, System.Func`1<System.IO.Stream>, Microsoft.Cci.PdbWriter, System.String, Boolean, Boolean, Boolean, Boolean, System.Nullable`1<System.Security.Cryptography.RSAParameters>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder, EmitStreamProvider, EmitStreamProvider, EmitStreamProvider, System.Func`2<Microsoft.DiaSymReader.ISymWriterMetadataProvider,Microsoft.DiaSymReader.SymUnmanagedWriter>, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.Emit.EmitOptions, System.Nullable`1<System.Security.Cryptography.RSAParameters>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.CodeGen.CompilationTestData, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.EmitWithPdb(System.IO.MemoryStream, System.IO.MemoryStream, Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis.IMethodSymbol, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Boolean)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.<VerifyPdbImpl>g__Verify|13_0(Boolean, Boolean, <>c__DisplayClass13_0 ByRef)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.VerifyPdbImpl(Microsoft.CodeAnalysis.Compilation, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.IMethodSymbol, System.String, System.String, Microsoft.CodeAnalysis.Emit.DebugInformationFormat, Microsoft.CodeAnalysis.Test.Utilities.PdbValidationOptions, Int32, System.String, Boolean)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.VerifyPdb(Microsoft.CodeAnalysis.Compilation, System.String, System.String, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.Emit.DebugInformationFormat, Microsoft.CodeAnalysis.Test.Utilities.PdbValidationOptions, Int32, System.String)
   at Microsoft.CodeAnalysis.Test.Utilities.PdbValidation.VerifyPdb(Microsoft.CodeAnalysis.Compilation, System.String, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, Microsoft.CodeAnalysis.IMethodSymbol, Microsoft.CodeAnalysis.Emit.DebugInformationFormat, Microsoft.CodeAnalysis.Test.Utilities.PdbValidationOptions, Int32, System.String)
   at Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLambdaTests.Queries1()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CallTestMethod(System.Object)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<InvokeTestMethodAsync>b__1>d<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<InvokeTestMethodAsync>b__1()
   at Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExecutionTimer+<AggregateAsync>d__4, xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<AggregateAsync>d__4 ByRef)
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(System.Func`1<System.Threading.Tasks.Task>)
   at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExceptionAggregator+<RunAsync>d__9, xunit.core, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__9 ByRef)
   at Xunit.Sdk.ExceptionAggregator.RunAsync(System.Func`1<System.Threading.Tasks.Task>)
   at Xunit.Sdk.TestInvoker`1+<InvokeTestMethodAsync>d__48[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<InvokeTestMethodAsync>d__48[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<InvokeTestMethodAsync>d__48<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InvokeTestMethodAsync(System.Object)
   at Xunit.Sdk.TestInvoker`1+<<RunAsync>b__47_0>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<<RunAsync>b__47_0>d[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.execution.dotnet, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<<RunAsync>b__47_0>d<System.__Canon> ByRef)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<RunAsync>b__47_0()
   at Xunit.Sdk.ExceptionAggregator+<RunAsync>d__10`1[[System.Decimal, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.ExceptionAggregator+<RunAsync>d__10`1[[System.Decimal, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], xunit.core, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]](<RunAsync>d__10`1<System.Decimal> ByRef)
   at Xunit.Sdk.ExceptionAggregator.RunAsync[[System.Decimal, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.Threading.Tasks.Task`1<System.Decimal>>)
   at Xunit.
Test Run Aborted.
```

**Comment by jkotas** [comment]
> This is x86, I wonder if it's related to the same stackwalk issue I was looking

@hoyosjs This is 64-bit x64. It means that it is not the 32-bit x86-specific stackwalk issue you are looking at.

> Possibly another symptom of #45557

Likely, it is not possible to tell for sure.

The fix for #45557 shipped in 5.0.2, but this dump shows that Roslyn is still running on 5.0.0. It is not a good use of time to drill into Roslyn GC crashes on 5.0.0 since they are likely dups of #45557. 

@jaredpar @RikkiGibson Could you please get Roslyn updated to 5.0.2? 

If you are still seeing GC crashes once you are on 5.0.2+, we need to repeat https://github.com/dotnet/runtime/issues/45557#issuecomment-738547930 to root-cause them.

**Comment by hoyosjs** [comment]
> @hoyosjs Juan Sebastian Hoyos Ayala FTE This is 64-bit x64. It means that it is not the 32-bit x86-specific stackwalk issue you are looking at.

The test run specifies --platform x86. Is it still an x64 process?

**Comment by jkotas** [comment]
> The test run specifies --platform x86. Is it still an x64 process?

Yes, the crash dump is x64 without any doubts. I guess that the `--platform x86` switch may apply to a different process.

**Comment by jaredpar** [comment]
> @jaredpar @RikkiGibson Could you please get Roslyn updated to 5.0.2?

Yes we can move forward to that now that it's released.
