### ISSUE TITLE
Assertion failed in `Regressions\\coreclr\\GitHub_45929\\test45929\\test45929.cmd`: m_alignpad == 0

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47394]
Run :  [runtime-coreclr jitstress2-jitstressregs 20210124.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963844&view=ms.vss-test-web.build-test-results-tab&runId=30353888&resultId=110590&paneView=debug)

Failed tests:
```
CoreCLR windows arm64 Checked jitstress2_jitstressregs2 @ Windows.10.Arm64v8.Open
        - Regressions\\coreclr\\GitHub_45929\\test45929\\test45929.cmd
```

Error message:
```
Assert failure(PID 12740 [0x000031c4], Thread: 5104 [0x13f0]): m_alignpad == 0

CORECLR! ObjHeader::IllegalAlignPad + 0x48 (0x00007ff8`dac3d730)
CORECLR! ObjHeader::Validate + 0x30 (0x00007ff8`dac3e548)
CORECLR! Object::ValidateInner + 0x55C (0x00007ff8`dac0dfb4)
CORECLR! Object::Validate + 0xC0 (0x00007ff8`dac0da30)
CORECLR! Thread::LastThrownObject + 0xF8 (0x00007ff8`daba8238)
CORECLR! Thread::SafeSetThrowables + 0xC4 (0x00007ff8`dac4981c)
CORECLR! ExceptionTracker::GetOrCreateTracker + 0x864 (0x00007ff8`dadcbe64)
CORECLR! ProcessCLRException + 0x364 (0x00007ff8`dadd14c4)
NTDLL! chkstk + 0x1CC (0x00007ff9`099a387c)
NTDLL! LdrControlFlowGuardEnforced + 0x994 (0x00007ff9`099ccfc4)
    File: F:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp Line: 2952
    Image: D:\h\w\A4130922\p\CoreRun.exe


Return code:      1
Raw output file:      D:\h\w\A4130922\w\A18B08F3\e\Regressions\coreclr\Reports\Regressions.coreclr\GitHub_45929\test45929\test45929.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A4130922\p\corerun.exe" test45929.dll 
The test started.
Progress:
1/24/2021 11:03:34 AM : 001.0%
1/24/2021 11:03:35 AM : 002.0%
1/24/2021 11:03:37 AM : 003.0%
1/24/2021 11:03:38 AM : 004.0%
1/24/2021 11:03:40 AM : 005.0%
1/24/2021 11:03:41 AM : 006.0%
1/24/2021 11:03:42 AM : 007.0%
1/24/2021 11:03:44 AM : 008.0%
1/24/2021 11:03:45 AM : 009.0%
1/24/2021 11:03:47 AM : 010.0%
1/24/2021 11:03:48 AM : 011.0%
1/24/2021 11:03:50 AM : 012.0%
1/24/2021 11:03:51 AM : 013.0%
1/24/2021 11:03:52 AM : 014.0%
1/24/2021 11:03:54 AM : 015.0%
1/24/2021 11:03:55 AM : 016.0%
1/24/2021 11:03:57 AM : 017.0%
1/24/2021 11:03:58 AM : 018.0%
1/24/2021 11:04:00 AM : 019.0%
1/24/2021 11:04:01 AM : 020.0%
1/24/2021 11:04:03 AM : 021.0%
1/24/2021 11:04:04 AM : 022.0%
1/24/2021 11:04:05 AM : 023.0%
1/24/2021 11:04:07 AM : 024.0%
1/24/2021 11:04:08 AM : 025.0%
1/24/2021 11:04:10 AM : 026.0%
1/24/2021 11:04:11 AM : 027.0%
1/24/2021 11:04:13 AM : 028.0%
1/24/2021 11:04:14 AM : 029.0%
1/24/2021 11:04:15 AM : 030.0%
1/24/2021 11:04:17 AM : 031.0%
1/24/2021 11:04:18 AM : 032.0%
1/24/2021 11:04:20 AM : 033.0%
1/24/2021 11:04:21 AM : 034.0%
1/24/2021 11:04:23 AM : 035.0%
1/24/2021 11:04:24 AM : 036.0%
1/24/2021 11:04:25 AM : 037.0%
1/24/2021 11:04:27 AM : 038.0%
1/24/2021 11:04:28 AM : 039.0%
1/24/2021 11:04:30 AM : 040.0%
1/24/2021 11:04:31 AM : 041.0%
1/24/2021 11:04:33 AM : 042.0%
1/24/2021 11:04:34 AM : 043.0%
1/24/2021 11:04:36 AM : 044.0%
1/24/2021 11:04:37 AM : 045.0%
1/24/2021 11:04:38 AM : 046.0%
1/24/2021 11:04:40 AM : 047.0%
1/24/2021 11:04:41 AM : 048.0%
1/24/2021 11:04:43 AM : 049.0%
1/24/2021 11:04:44 AM : 050.0%
1/24/2021 11:04:46 AM : 051.0%
1/24/2021 11:04:47 AM : 052.0%
1/24/2021 11:04:49 AM : 053.0%
1/24/2021 11:04:50 AM : 054.0%
1/24/2021 11:04:51 AM : 055.0%
1/24/2021 11:04:53 AM : 056.0%
1/24/2021 11:04:54 AM : 057.0%
1/24/2021 11:04:56 AM : 058.0%
1/24/2021 11:04:57 AM : 059.0%
1/24/2021 11:04:59 AM : 060.0%
1/24/2021 11:05:00 AM : 061.0%
1/24/2021 11:05:02 AM : 062.0%
1/24/2021 11:05:03 AM : 063.0%
1/24/2021 11:05:04 AM : 064.0%
1/24/2021 11:05:06 AM : 065.0%
1/24/2021 11:05:07 AM : 066.0%
1/24/2021 11:05:09 AM : 067.0%
1/24/2021 11:05:10 AM : 068.0%
1/24/2021 11:05:12 AM : 069.0%
1/24/2021 11:05:13 AM : 070.0%
1/24/2021 11:05:15 AM : 071.0%
1/24/2021 11:05:16 AM : 072.0%
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\A4130922\p
> D:\h\w\A4130922\w\A18B08F3\e\Regressions\coreclr\GitHub_45929\test45929\test45929.cmd

stack trace:
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_cmd()
```

**Comment by janvorli** [comment]
I'll try to repro it on my local arm64 Linux device. I've been investigating another intermittent failure in this test, so I have everything set up.

**Comment by janvorli** [comment]
Ah, I haven't noticed that this is actually Windows ARM64. I don't currently have my Windows ARM64 device in a working state.

**Comment by BruceForstall** [comment]
@janvorli Contact me offline and I can get you access to a win-arm64 box.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress-extra 20210130.1](https://dev.azure.com/dnceng/public/_build/results?buildId=973021&view=ms.vss-test-web.build-test-results-tab&runId=30557350&paneView=debug&resultId=108534)

Failed tests:
```
CoreCLR windows arm64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Arm64v8.Open
    - Regressions\\coreclr\\GitHub_45929\\test45929\\test45929.cmd
```

Error message:
```
Assert failure(PID 2588 [0x00000a1c], Thread: 11300 [0x2c24]): m_alignpad == 0

CORECLR! ObjHeader::IllegalAlignPad + 0x48 (0x00007fff`2f02ece0)
CORECLR! ObjHeader::Validate + 0x30 (0x00007fff`2f02faf8)
CORECLR! Object::ValidateInner + 0x55C (0x00007fff`2effe424)
CORECLR! OBJECTREF::OBJECTREF + 0xC0 (0x00007fff`2eff9840)
CORECLR! StackTraceInfo::SaveStackTrace + 0xBD0 (0x00007fff`2ef9c5c0)
CORECLR! ExceptionTracker::ProcessManagedCallFrame + 0x744 (0x00007fff`2f1c0474)
CORECLR! ExceptionTracker::ProcessOSExceptionNotification + 0x3C4 (0x00007fff`2f1c1e14)
CORECLR! ProcessCLRException + 0x600 (0x00007fff`2f1c34b0)
NTDLL! chkstk + 0x1CC (0x00007fff`5e90387c)
NTDLL! LdrControlFlowGuardEnforced + 0x994 (0x00007fff`5e92cfc4)
    File: F:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp Line: 2952
    Image: D:\h\w\AE9609A4\p\CoreRun.exe

Return code:      1
Raw output file:      D:\h\w\AE9609A4\w\BBF90A26\e\Regressions\coreclr\Reports\Regressions.coreclr\GitHub_45929\test45929\test45929.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\AE9609A4\p\corerun.exe" test45929.dll 
The test started.
Progress:
1/30/2021 3:19:09 PM : 002.0%
1/30/2021 3:19:05 PM : 001.7%
1/30/2021 3:19:11 PM : 003.0%
1/30/2021 3:19:13 PM : 004.0%
1/30/2021 3:19:14 PM : 005.0%
1/30/2021 3:19:16 PM : 006.0%
1/30/2021 3:19:18 PM : 007.0%
1/30/2021 3:19:20 PM : 008.0%
1/30/2021 3:19:21 PM : 009.0%
1/30/2021 3:19:23 PM : 010.0%
1/30/2021 3:19:25 PM : 011.0%
1/30/2021 3:19:27 PM : 012.0%
1/30/2021 3:19:28 PM : 013.0%
1/30/2021 3:19:30 PM : 014.0%
1/30/2021 3:19:32 PM : 015.0%
1/30/2021 3:19:33 PM : 016.0%
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\AE9609A4\p
> D:\h\w\AE9609A4\w\BBF90A26\e\Regressions\coreclr\GitHub_45929\test45929\test45929.cmd

stack trace:
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_cmd()
```

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr gcstress0x3-gcstress0xc 20210207.1](https://dev.azure.com/dnceng/public/_build/results?buildId=982411&view=ms.vss-test-web.build-test-results-tab&runId=30789164&resultId=110594&paneView=debug)

Failed test:
```
CoreCLR windows arm64 Checked gcstress0x3 @ Windows.10.Arm64v8.Open

  -Regressions\\coreclr\\GitHub_45929\\test45929\\test45929.cmd
```

**Error message:**
```
Assert failure(PID 6260 [0x00001874], Thread: 11648 [0x2d80]): m_alignpad == 0

CORECLR! ObjHeader::IllegalAlignPad + 0x48 (0x00007ffa46a6faf0)
CORECLR! ObjHeader::Validate + 0x30 (0x00007ffa46a70908)
CORECLR! Object::ValidateInner + 0x55C (0x00007ffa46a3e76c)
CORECLR! OBJECTREF::operator-> + 0xBC (0x00007ffa46a3a7d4)
CORECLR! ExceptionTracker::ProcessManagedCallFrame + 0x15C0 (0x00007ffa46c024b0)
CORECLR! ExceptionTracker::ProcessOSExceptionNotification + 0x3C4 (0x00007ffa46c02fd4)
CORECLR! ProcessCLRException + 0x600 (0x00007ffa46c04670)
NTDLL! chkstk + 0x1CC (0x00007ffa76a2387c)
NTDLL! LdrControlFlowGuardEnforced + 0x994 (0x00007ffa76a4cfc4)
NTDLL! RtlRaiseException + 0xC0 (0x00007ffa76a8a9b0)
 File: D:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp Line: 2952
 Image: D:\h\w\A75B0991\p\CoreRun.exe


Return code: 1
Raw output file: D:\h\w\A75B0991\w\A305091F\e\Regressions\coreclr\Reports\Regressions.coreclr\GitHub_45929\test45929\test45929.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A75B0991\p\corerun.exe" test45929.dll 
The test started.
Progress:
2/7/2021 7:10:14 AM : 001.0%
2/7/2021 7:10:16 AM : 002.0%
2/7/2021 7:10:19 AM : 003.0%
2/7/2021 7:10:21 AM : 004.0%
2/7/2021 7:10:24 AM : 005.0%
2/7/2021 7:10:27 AM : 006.0%
2/7/2021 7:10:29 AM : 007.0%
2/7/2021 7:10:31 AM : 008.0%
2/7/2021 7:10:34 AM : 009.0%
2/7/2021 7:10:36 AM : 010.0%
2/7/2021 7:10:39 AM : 011.0%
2/7/2021 7:10:41 AM : 012.0%
2/7/2021 7:10:43 AM : 013.0%
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\A75B0991\p
> D:\h\w\A75B0991\w\A305091F\e\Regressions\coreclr\GitHub_45929\test45929\test45929.cmd
Expected: True
Actual: False

Stack trace
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_cmd()

```

**Comment by VincentBu** [comment]
Failed again in run [runtime-coreclr gcstress0x3-gcstress0xc 20210214.1](https://dev.azure.com/dnceng/public/_build/results?buildId=994348&view=ms.vss-test-web.build-test-results-tab&runId=31147718&resultId=110044&paneView=debug)

Failed test:
```
CoreCLR windows arm64 Checked gcstress0x3 @ Windows.10.Arm64v8.Open
 -Regressions\\coreclr\\GitHub_45929\\test45929\\test45929.cmd
```

**Error message:**
```
Assert failure(PID 10380 [0x0000288c], Thread: 7516 [0x1d5c]): m_alignpad == 0

CORECLR! ObjHeader::IllegalAlignPad + 0x48 (0x00007ffa1abafeb0)
CORECLR! ObjHeader::Validate + 0x30 (0x00007ffa1abb0cc8)
CORECLR! Object::ValidateInner + 0x55C (0x00007ffa1ab7eb1c)
CORECLR! OBJECTREF::OBJECTREF + 0xC0 (0x00007ffa1ab79f38)
CORECLR! ExceptionTracker::ProcessManagedCallFrame + 0x159C (0x00007ffa1ad42d7c)
CORECLR! ExceptionTracker::ProcessOSExceptionNotification + 0x3C4 (0x00007ffa1ad438c4)
CORECLR! ProcessCLRException + 0x600 (0x00007ffa1ad44f60)
NTDLL! chkstk + 0x1CC (0x00007ffa4b2a387c)
NTDLL! LdrControlFlowGuardEnforced + 0x994 (0x00007ffa4b2ccfc4)
NTDLL! RtlRaiseException + 0xC0 (0x00007ffa4b30a9b0)
 File: D:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp Line: 2952
 Image: D:\h\w\B2970973\p\CoreRun.exe


Return code: 1
Raw output file: D:\h\w\B2970973\w\B74A0984\e\Regressions\coreclr\Reports\Regressions.coreclr\GitHub_45929\test45929\test45929.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\B2970973\p\corerun.exe" test45929.dll 
The test started.
Progress:
2/14/2021 7:13:01 AM : 001.0%
2/14/2021 7:13:04 AM : 002.0%
2/14/2021 7:13:06 AM : 003.0%
2/14/2021 7:13:08 AM : 004.0%
2/14/2021 7:13:11 AM : 005.0%
2/14/2021 7:13:13 AM : 006.0%
2/14/2021 7:13:15 AM : 007.0%
2/14/2021 7:13:17 AM : 008.0%
2/14/2021 7:13:19 AM : 009.0%
2/14/2021 7:13:21 AM : 010.0%
2/14/2021 7:13:22 AM : 011.0%
2/14/2021 7:13:24 AM : 012.0%
2/14/2021 7:13:26 AM : 013.0%
2/14/2021 7:13:27 AM : 014.0%
2/14/2021 7:13:29 AM : 015.0%
2/14/2021 7:13:31 AM : 016.0%
2/14/2021 7:13:33 AM : 017.0%
2/14/2021 7:13:34 AM : 018.0%
2/14/2021 7:13:36 AM : 019.0%
2/14/2021 7:13:38 AM : 020.0%
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\B2970973\p
> D:\h\w\B2970973\w\B74A0984\e\Regressions\coreclr\GitHub_45929\test45929\test45929.cmd
Expected: True
Actual: False

Stack trace
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_cmd()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210307.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1026446&view=ms.vss-test-web.build-test-results-tab&runId=31891538&resultId=109843&paneView=debug)

Failed test:
```
CoreCLR windows arm64 Checked gcstress0x3 @ Windows.10.Arm64v8.Open
 -Regressions\\coreclr\\GitHub_45929\\test45929\\test45929.cmd
```

**Error message:**
```
Assert failure(PID 17320 [0x000043a8], Thread: 3168 [0x0c60]): m_alignpad == 0

CORECLR! ObjHeader::IllegalAlignPad + 0x48 (0x00007ffbd36600a0)
CORECLR! ObjHeader::Validate + 0x30 (0x00007ffbd3660eb8)
CORECLR! Object::ValidateInner + 0x55C (0x00007ffbd362ed0c)
CORECLR! OBJECTREF::operator-> + 0xBC (0x00007ffbd362ad74)
CORECLR! ExceptionTracker::CanAllocateMemory + 0x28 (0x00007ffbd37ec4b0)
CORECLR! ExceptionTracker::GetOrCreateTracker + 0x86C (0x00007ffbd37ef68c)
CORECLR! ProcessCLRException + 0x364 (0x00007ffbd37f4ce4)
NTDLL! chkstk + 0x1CC (0x00007ffc0302387c)
NTDLL! LdrControlFlowGuardEnforced + 0x994 (0x00007ffc0304cfc4)
NTDLL! RtlRaiseException + 0xC0 (0x00007ffc0308a9b0)
 File: D:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp Line: 2952
 Image: D:\h\w\93810861\p\CoreRun.exe


Return code: 1
Raw output file: D:\h\w\93810861\w\AB490948\e\Regressions\coreclr\Reports\Regressions.coreclr\GitHub_45929\test45929\test45929.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\93810861\p\corerun.exe" test45929.dll 
The test started.
Progress:
3/7/2021 7:57:35 AM : 001.0%
3/7/2021 7:57:37 AM : 002.0%
3/7/2021 7:57:39 AM : 003.0%
3/7/2021 7:57:42 AM : 004.0%
3/7/2021 7:57:44 AM : 005.0%
3/7/2021 7:57:45 AM : 006.0%
3/7/2021 7:57:47 AM : 007.0%
3/7/2021 7:57:49 AM : 008.0%
3/7/2021 7:57:51 AM : 009.0%
3/7/2021 7:57:53 AM : 010.0%
3/7/2021 7:57:55 AM : 011.0%
3/7/2021 7:57:57 AM : 012.0%
3/7/2021 7:57:59 AM : 013.0%
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\93810861\p
> D:\h\w\93810861\w\AB490948\e\Regressions\coreclr\GitHub_45929\test45929\test45929.cmd
Expected: True
Actual: False

Stack trace
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_cmd()

```

**Comment by mangod9** [comment]
Closing since this hasnt reproed in a few months.
