### ISSUE TITLE
Test failed: System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47398]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20210123.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963179&view=ms.vss-test-web.build-test-results-tab&runId=30338700&paneView=debug&resultId=146447)

Failed tests:
```
net6.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs0x1000-Windows.10.Amd64.Open
        - System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey
```

Error message:
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal consistency check failed.

stack trace:
   at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters) in /_/src/libraries/System.Security.Cryptography.Cng/src/System/Security/Cryptography/CngKey.Create.cs:line 34
   at Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(Int32 keySize, CngAlgorithm algorithm) in /_/src/libraries/System.Security.Cryptography.Cng/src/Internal/Cryptography/CngAlgorithmCore.cs:line 52
   at System.Security.Cryptography.DSACng.get_Key() in /_/src/libraries/System.Security.Cryptography.Cng/src/System/Security/Cryptography/DSACng.Key.cs:line 24
   at System.Security.Cryptography.DSACng.ExportKeyBlob(Boolean includePrivateParameters) in /_/src/libraries/System.Security.Cryptography.Cng/src/System/Security/Cryptography/DSACng.ImportExport.cs:line 11
   at System.Security.Cryptography.DSACng.ExportParameters(Boolean includePrivateParameters) in /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.ImportExport.cs:line 325
   at System.Security.Cryptography.Dsa.Tests.DSAImportExport.ExportAutoKey() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSAImportExport.cs:line 26
```

**Comment by VincentBu** [comment]
Failed in [runtime 20210621.104](https://dev.azure.com/dnceng/public/_build/results?buildId=1198136&view=ms.vss-test-web.build-test-results-tab&runId=35915858&resultId=143722&paneView=debug)
Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open

- System.Security.Cryptography.Xml.Tests.DSAKeyValueTest.GetXml_SameDsa

```
**Error message:**
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal consistency check failed.


Stack trace
   at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize) in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CngKeyLite.cs:line 408
   at System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle() in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/DSACng.cs:line 48
   at System.Security.Cryptography.DSAImplementation.DSACng.ExportKeyBlob(Boolean includePrivateParameters) in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/DSACng.cs:line 62
   at System.Security.Cryptography.DSAImplementation.DSACng.ExportParameters(Boolean includePrivateParameters) in /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.ImportExport.cs:line 324
   at System.Security.Cryptography.Xml.DSAKeyValue.GetXml(XmlDocument xmlDocument) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/DSAKeyValue.cs:line 82
   at System.Security.Cryptography.Xml.DSAKeyValue.GetXml() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/DSAKeyValue.cs:line 59
   at System.Security.Cryptography.Xml.Tests.DSAKeyValueTest.GetXml_SameDsa() in /_/src/libraries/System.Security.Cryptography.Xml/tests/DSAKeyValueTest.cs:line 89
```

**Comment by bartonjs** [comment]
This has only failed once since April 1st, and it's really an OS issue.  Closing as unactionable.
