### ISSUE TITLE
R2RDump fails with 'Read out of bounds' exception

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#47412]
### Description

R2RDump fails with  'Read out of bounds'  exception:
```
$ ./corerun ./R2RDump/R2RDump.dll  -r System.Private.CoreLib.dll -r System.Linq.dll --in ./crossgen2/crossgen2.ni.dll
Filename: /home/tmustafin/dotnet/x64_runtime/crossgen2/crossgen2.ni.dll
OS: Linux
Machine: Amd64
ImageBase: 0x00400000

======================== R2R Methods ========================

Error: System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds() in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/Throw.cs:line 194
   at System.Reflection.Metadata.Ecma335.MethodTableReader.GetRva(MethodDefinitionHandle handle) in /home/tmustafin/dotnet/runtime/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Internal/Tables.cs:line 456
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunMethod..ctor(ReadyToRunReader readyToRunReader, IAssemblyMetadata componentReader, EntityHandle methodHandle, Int32 entryPointId, String owningType, String constrainedType, String[] instanceArgs, Nullable`1 fixupOffset)
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.ParseInstanceMethodEntrypoints(Boolean[] isEntryPoint)
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.EnsureMethods()
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.get_Methods()
   at R2RDump.TextDumper.DumpAllMethods()
   at R2RDump.R2RDump.Dump(ReadyToRunReader r2r)
   at R2RDump.R2RDump.Run()
```
R2RDump fails for next system ni.dll files with that exception:
```
System.Security.Cryptography.Encoding.ni.dll
System.Net.WebSockets.ni.dll
System.Diagnostics.DiagnosticSource.ni.dll
System.Private.Uri.ni.dll
crossgen2/crossgen2.ni.dll
System.Collections.Specialized.ni.dll
System.Diagnostics.TextWriterTraceListener.ni.dll
R2RDump/System.CommandLine.ni.dll
System.Text.RegularExpressions.ni.dll
System.Memory.ni.dll
System.Security.Cryptography.X509Certificates.ni.dll
System.Web.HttpUtility.ni.dll
```

### Configuration

* runtime state 54953538be9e7e20eccc90b271edfd01210cf6a8.
* Ubuntu/arm64 and tizen/armel.

cc @jkotas @alpencolt

**Comment by jkotas** [comment]
cc @dotnet/crossgen-contrib

**Comment by davidwrighton** [comment]
I wasn't able to reproduce this as I don't have access to the scripts you use to produce .ni images. If you are still seeing this issue, please re-open the bug, and provide a link to a location where the binaries you attempting to examine are.
