### ISSUE TITLE
[HTTP/3] SETTINGS frame incorrectly being sent on request stream

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#47442]
I have a gRPC test that fails with HTTP/3. The test is sending a large request message and Kestrel appears to receive a `SETTINGS` frame on a request stream. This violates the HTTP/3 spec:

https://tools.ietf.org/html/draft-ietf-quic-http-33#section-7.2.4

>    SETTINGS frames MUST NOT be sent on any stream other than the control
>    stream.  If an endpoint receives a SETTINGS frame on a different
>    stream, the endpoint MUST respond with a connection error of type
>    H3_FRAME_UNEXPECTED.

Kestrel is erroring, although I don't think it is throwing the right error currently. That's a different issue to fix, and is in reaction to this client bug.

Test logs:

```
0.005s GrpcTestContext - Information: Starting IssueTests.SendLargeRequest_SuccessResponse
0.043s Grpc.Net.Client.Internal.GrpcCall - Debug: Starting gRPC call. Method type: 'Unary', URI: 'https://localhost:50010/issue.IssueService/GetLibrary'.
0.158s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic - Debug: Connection id "0HM61GF4HTBJT" accepted.
0.180s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM61GF4HTBJT" accepted.
0.182s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM61GF4HTBJT" started.
0.210s Grpc.Net.Client.Internal.GrpcCall - Debug: Sending message.
0.228s Grpc.Net.Client.Internal.GrpcCall - Trace: Serialized 'Issue.GetLibraryRequest' to 23473 byte message.
0.237s Grpc.Net.Client.Internal.GrpcCall - Trace: Message sent.
0.254s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GF4HTBJT:2" received Settings frame for stream ID 2 with length 5.
0.254s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GF4HTBJT:0" received Headers frame for stream ID 0 with length 238.
0.270s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GF4HTBJT:0" received Data frame for stream ID 0 with length 7094.
0.271s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GF4HTBJT:0" received 49 frame for stream ID 0 with length 51.
0.271s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GF4HTBJT:0" received Settings frame for stream ID 0 with length 49.
0.272s SERVER Microsoft.AspNetCore.Server.Kestrel - Warning: Stream threw an unexpected exception.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3ConnectionException: HTTP_FRAME_UNEXPECTED
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Stream.ProcessHttp3Stream[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Stream.ProcessRequestAsync[TContext](IHttpApplication`1 application)
0.275s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request starting HTTP/3 POST https://localhost:50010/issue.IssueService/GetLibrary application/grpc -
0.318s SERVER Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware - Debug: Request matched endpoint 'gRPC - /issue.IssueService/GetLibrary'
0.323s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executing endpoint 'gRPC - /issue.IssueService/GetLibrary'
0.345s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
0.345s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM61GF4HTBJT:0", Request id "0HM61GF4HTBJT:0": started reading request body.
5.199s GrpcTestContext - Information: Finishing IssueTests.SendLargeRequest_SuccessResponse
```

Important part:

```
0.271s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GF4HTBJT:0" received Settings frame for stream ID 0 with length 49.
0.272s SERVER Microsoft.AspNetCore.Server.Kestrel - Warning: Stream threw an unexpected exception.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3ConnectionException: HTTP_FRAME_UNEXPECTED
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Stream.ProcessHttp3Stream[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload)
```

Stream ID 0 is a request stream and should never get a SETTINGS frame.

Code: https://github.com/grpc/grpc-dotnet
Class: Grpc.AspNetCore.FunctionalTests.Web.Client.IssueTests (Grpc, Http3WithTls)
Test: SendLargeRequest_SuccessResponse

**Comment by JamesNK** [comment]
Hmmm, this is also strange:
```
0.492s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM61GUTNGL9S:0" received 49 frame for stream ID 0 with length 51.
```

**Comment by karelz** [comment]
Triage: Most likely bug in our code as we are explicit where we send the SETTINGS frame.

**Comment by karelz** [comment]
Triage: @JamesNK have you seen it recently?

**Comment by JamesNK** [comment]
The test passes now. Will reopen if it becomes a problem again.
