### ISSUE TITLE
PerformanceCounter.NextValue() throws exceptions

### ISSUE THREAD

**Issue by hanabi1224** [dotnet/runtime#47471]
Code to reproduce the error:
```csharp
var p = Process.GetCurrentProcess();
var ramCounter = new PerformanceCounter("Process", "Working Set - Private", p.ProcessName);
var ram = ramCounter.NextValue();// .NextSample();
Console.WriteLine("RAM: " + ram / (1024 * 1024) + "MB");
```
Exception I got on win10+net5/netcoreapp3.1 (works fine on the same win10+netframework4.8):
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'FormatFromRawValue' in DLL 'perfcounter.dll'.
   at Interop.PerfCounter.FormatFromRawValue(UInt32 dwCounterType, UInt32 dwFormat, Int64& pTimeBase, PDH_RAW_COUNTER& pRawValue1, PDH_RAW_COUNTER& pRawValue2, PDH_FMT_COUNTERVALUE& pFmtValue)
   at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
   at System.Diagnostics.CounterSample.Calculate(CounterSample counterSample, CounterSample nextCounterSample)
   at System.Diagnostics.PerformanceCounter.NextValue()
```

### Configuration

```
win10 19042
```
```
2.1.520 [C:\Program Files\dotnet\sdk]
2.1.812 [C:\Program Files\dotnet\sdk]
3.1.111 [C:\Program Files\dotnet\sdk]
3.1.403 [C:\Program Files\dotnet\sdk]
3.1.405 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
```
```xml
<ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="5.0.0" />
</ItemGroup>
```

**Comment by jkotas** [comment]
cc @ericstj

**Comment by ericstj** [comment]
This should be fixed in servicing (to be released in Feb) and .NET 6.0.  We stopped relying on `perfcounter.dll` for this export.

You can try the latest build by referencing 
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=System.Diagnostics.PerformanceCounter&protocolType=NuGet&version=6.0.0-preview.2.21076.3

I'm still a little surprised you're seeing this error.  Can you tell me more about the target machine?  Is it ARM64?  Is it missing .NETFramework?

**Comment by hanabi1224** [comment]
@ericstj   It's a laptop with x64 cpu + win10, regarding .netframework, I have netfx 4.8 installed.
```
Processor	Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz, 2904 Mhz, 2 Core(s), 4 Logical Processor(s)
Version	10.0.19042 Build 19042
```

**Comment by ericstj** [comment]
That's interesting.  I have the same configuration and it works for me.  Try changing the code to this (or use a debugger to find the path of the loaded perfcounter.dll):
```C#
try
{
    var p = Process.GetCurrentProcess();
    var ramCounter = new PerformanceCounter("Process", "Working Set - Private", p.ProcessName);
    var ram = ramCounter.NextValue();// .NextSample();
    Console.WriteLine("RAM: " + ram / (1024 * 1024) + "MB");
                
}
catch (EntryPointNotFoundException epnfe)
{
    Console.WriteLine(epnfe);
    var proc = Process.GetCurrentProcess();
    foreach (ProcessModule module in proc.Modules.Cast<ProcessModule>().Where(m => m.ModuleName.Equals("perfcounter.dll", StringComparison.OrdinalIgnoreCase)))
    {
        Console.WriteLine(module.FileName);
    }
}
```

 Then from a developer command prompt, run `dumpbin /exports pathto\perfcounter.dll`,  (for me this was `dumpbin /exports "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\PerfCounter.dll"`) and share what you see.

**Comment by hanabi1224** [comment]
@ericstj Here you go
```
System.EntryPointNotFoundException: Unable to find an entry point named 'FormatFromRawValue' in DLL 'perfcounter.dll'.
   at Interop.PerfCounter.FormatFromRawValue(UInt32 dwCounterType, UInt32 dwFormat, Int64& pTimeBase, PDH_RAW_COUNTER& pRawValue1, PDH_RAW_COUNTER& pRawValue2, PDH_FMT_COUNTERVALUE& pFmtValue)
   at System.Diagnostics.CounterSampleCalculator.ComputeCounterValue(CounterSample oldSample, CounterSample newSample)
   at System.Diagnostics.CounterSample.Calculate(CounterSample counterSample, CounterSample nextCounterSample)
   at System.Diagnostics.PerformanceCounter.NextValue()
   at PerfCounter.Program.Main(String[] args) in C:\repos\PerfCounter\Program.cs:line 16
C:\repos\PerfCounter\bin\Debug\netcoreapp3.1\PerfCounter.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\perfcounter.dll

C:\repos\PerfCounter\bin\Debug\netcoreapp3.1\PerfCounter.exe (process 25120) exited with code 0.
```
```
Microsoft (R) COFF/PE Dumper Version 14.28.29336.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\repos\PerfCounter\bin\Debug\netcoreapp3.1\PerfCounter.dll

File Type: EXECUTABLE IMAGE

  Summary

        2000 .reloc
        2000 .rsrc
        2000 .text
```
```
Dump of file C:\Windows\Microsoft.NET\Framework64\v4.0.30319\perfcounter.dll

File Type: DLL

  Section contains the following exports for PerfCounter.dll

    00000000 characteristics
    5DDA4063 time date stamp Sun Nov 24 16:33:39 2019
        0.00 version
           1 ordinal base
           4 number of functions
           4 number of names

    ordinal hint RVA      name

          2    0 00005FF0 ClosePerformanceData
          3    1 00005E30 CollectPerformanceData
          4    2 00006070 FormatFromRawValue
          1    3 00005CE0 OpenPerformanceData

  Summary

        3000 .data
        2000 .pdata
       18000 .rdata
        1000 .reloc
        1000 .rsrc
       22000 .text
```

**Comment by hanabi1224** [comment]
@ericstj Ah I just realize that it's because my program produces assembly with name 'PerfCounter', when I rename it to 'PerfCounter2' it works.
