### ISSUE TITLE
DependencyContextLoader tries to use Assembly.CodeBase - error in .NET 5

### ISSUE THREAD

**Issue by jez9999** [dotnet/runtime#47527]
Related to issue #44511 - when I build an ASP.NET Core web application with MVC Razor, in latest Visual Studio 2019 (16.8.4), generating a single-file for use with `linux-x64`, targeting .NET 5 (my `dotnet.exe` version is `.NET SDK (5.0.102)`), I get an error when I try to run this file on Linux Debian:

```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
         at System.Reflection.RuntimeAssembly.get_CodeBase()
         at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   [...]
   at BLSHBot.Web.WebStartup.<>c.<configure>b__10_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at BLSHBot.Web.WebStartup.configure(IApplicationBuilder app, ILogger`1 logger)
   at BLSHBot.Web.WebStartup.Configure(IApplicationBuilder app, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BLSHBot.Web.Program.Main(String[] args)
```

The problem here seems to be `DependencyContextLoader` trying to access `Assembly.CodeBase`, which is not supported in a single-file bundle.

**Comment by eerhardt** [comment]
The offending code:

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/Microsoft.Extensions.DependencyModel/src/DependencyContextLoader.cs#L128-L162

@agocke @LakshanF @tlakollo @mateoatr - is there an API that allows a library to check whether CodeBase is going to throw or not? Or is the "fix" simply to try-catch around the usage?

**Comment by jkotas** [comment]
Check for empty `Assembly.Location`. If the `Assembly.Location` is empty, do not bother to find anything next to the assembly on disk.
