### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#47556]
### Description

```
Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
   at System.Net.Dns.<>c.b__27_2(Object s)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at ConsoleApp1.Program.Main(String[] args) in D:\src\ConsoleApp1\Program.cs:line 30
   at ConsoleApp1.Program.<Main>(String[] args)

```

### Configuration

```

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

### Other information

```c#
using System;
using System.Diagnostics;
using System.Net;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var hosts = new string[]
            {
                "www.baidu.com",
                "www.qq.com"
            };
            var random = new Random();

            while (true)
            {
                var index = random.Next(0, 2);
                var stopWatch = Stopwatch.StartNew();
                var ipAddresses = await Dns.GetHostAddressesAsync(hosts[index]);
                stopWatch.Stop();

                if (stopWatch.ElapsedMilliseconds > 50)
                {
                    foreach (var item in ipAddresses)
                    {
                        Console.WriteLine($"Host:{hosts[index]},Address Dns:{item},Duration:{stopWatch.ElapsedMilliseconds}ms");
                    }
                }

                await Task.Delay(1000);
            }
        }
    }
}


```

**Comment by danmosemsft** [comment]
EAGAIN ? or GetAddrInfoErrorFlags_EAI_AGAIN ? Both are 1.

**Comment by Varorbc** [comment]
Sorry, I have no idea about network programming under Linux, so I don’t undstand what are you talking about. please give me some suggestion.thank you

**Comment by danmosemsft** [comment]
@Varorbc sorry, neither do I -- that was a note for the System.Net folks, who will no doubt look at this a bit later.

Meantime -- can you share more info
* how often does this happen? I see you already have a loop -- how often does it fail for you?
* does it occur on other machines for you, either Debian or something else?

**Comment by wfurt** [comment]
This can be sign of transient issues with your DNS server. Depending on your OS setting, you may or may not got through DNS cache. You can try to do packet captures with Wireshark and investigate OS setting and log. 
For comparison you can try to write similar test with shell and nslookup (or similar) to see if you get similar results.

**Comment by Varorbc** [comment]
@danmosemsft 

![image](https://user-images.githubusercontent.com/5714438/106080279-b614e500-6151-11eb-98a8-98c80da32560.png)

not occur on Debian arm64

**Comment by Varorbc** [comment]
@wfurt thank you
