### ISSUE TITLE
Tests failed on WASM run with NullReferenceException in System.Runtime.InteropServices.JavaScript.Runtime.<>c__DisplayClass27_0.<SetupJSContinuation>g__Complete|0()

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#47562]
Not sure whether this is the WASM infrastructure, or something else?

net6.0-Browser-Release-wasm-Mono_Release-wasmtestonbrowser-Ubuntu.1804.Amd64.Open
 System.IO.Tests in job 4ff990ac-4209-44ee-905e-a8cab14a1ab9
```
Finished:    System.IO.Tests.dll

=== TEST EXECUTION SUMMARY ===
Total: 826, Errors: 0, Failed: 0, Skipped: 26, Time: 3.520365s

WASM-ERR:
WASM-ERR: Unhandled Exception:
WASM-ERR: System.NullReferenceException: Object reference not set to an instance of an object.
WASM-ERR:    at System.Runtime.InteropServices.JavaScript.Runtime.<>c__DisplayClass27_0.<SetupJSContinuation>g__Complete|0()
WASM-ERR:    at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state)
WASM-ERR:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
WASM-ERR: --- End of stack trace from previous location ---
WASM-ERR:    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
WASM-ERR:    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
WASM-ERR: --- End of stack trace from previous location ---
WASM-ERR:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
WASM-ERR:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
WASM-ERR:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
WASM-ERR:    at System.Threading.ThreadPool.Callback()
ThreadPool Callback threw an unhandled exception of type System.NullReferenceException

```
https://dev.azure.com/dnceng/public/_build/results?buildId=969030&view=ms.vss-test-web.build-test-results-tab&runId=30460098&paneView=debug&resultId=155085

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/pull/47511
