### ISSUE TITLE
System.Net.Http.HttpRequestException: An error occurred while sending the request.

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#47612]
#### randomly fails, sometimes they do all work correctly.

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Essensoft.AspNetCore.Payment.WeChatPay.V2.Extensions.HttpClientExtensions.PostAsync[T](HttpClient client, IWeChatPayRequest`1 request, IDictionary`2 textParams)
   at Essensoft.AspNetCore.Payment.WeChatPay.V2.WeChatPayClient.ExecuteAsync[T](IWeChatPayRequest`1 request, WeChatPayOptions options)
   at lambda_method72(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

```

### Configuration

```

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by stephentoub** [comment]
The error "The response ended prematurely" means the server to which you were making an HTTP request closed the connection without having sent back a compete response.

**Comment by Varorbc** [comment]
@stephentoub but I did not actively close the connection

**Comment by stephentoub** [comment]
>  I did not actively close the connection

Not you, I'm saying you're using HttpClient to make a request, and the server you're making a request to is closing the connection.

**Comment by Varorbc** [comment]
This problem did not occur before I upgraded to .net5.Just like #31528

**Comment by stephentoub** [comment]
> Just like #31528

As with that issue, there's nothing actionable here without a minimal repro we can run to test with; can you share one?  All signs from the information you provided point to this being external to HttpClient.

**Comment by Varorbc** [comment]
https://github.com/essensoft/payment/blob/dev/samples/WebApplicationSample/Controllers/WeChatPayController.cs#L74

**Comment by stephentoub** [comment]
Do you have a standalone repro that directly uses HttpClient?

**Comment by Varorbc** [comment]
sorry,i don't have

**Comment by wfurt** [comment]
You can try to do packet captures with Wireshark or tcpdump. That should give direct clue for HTTP. If this is HTTPS may still give you some hims if there is premature closure. Since this is POST, do you know if 100Continue is in play? (and any redirects and/or authentication) I'm wondering if the server can send error response and close the connection while the requyest body is still being sent.

**Comment by Varorbc** [comment]
@wfurt The other party's server problem?

![image](https://user-images.githubusercontent.com/5714438/106418748-fd70dd80-6491-11eb-9628-1f3471990e04.png)

**Comment by wfurt** [comment]
There is Alert in packet 1652. You can look what its in there. But it is the server closing TCP in  1654 followed by close in 1655. If the request body is still being send, it would fail with the exception you posted. 

Do you set [HttpCompletionOption](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-5.0#System_Net_Http_HttpClient_SendAsync_System_Net_Http_HttpRequestMessage_System_Net_Http_HttpCompletionOption_System_Threading_CancellationToken_) or do you leave it default? If you use ResponseHeadersRead you may see server sending back some error or explanation.

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/106537169-c56ea680-6534-11eb-9d4a-7c4ac6ce995b.png)
![image](https://user-images.githubusercontent.com/5714438/106537245-e9ca8300-6534-11eb-9b48-d38843018e2d.png)

I have not set HttpCompletionOption
https://github.com/essensoft/payment/blob/dev/src/Essensoft.AspNetCore.Payment.WeChatPay/V2/Extensions/HttpClientExtensions.cs#L10

**Comment by Varorbc** [comment]
![image](https://user-images.githubusercontent.com/5714438/106540056-1cc34580-653a-11eb-80b7-e422b083fdfd.png)

I found a lot of warning packets, but no exception was thrown at those points in time

**Comment by wfurt** [comment]
We will not be able to peek easily inside the encrypted alerts. Since this seems like general instability of the server and network, you may try to wrap it in some retry mechanism. At this point, I don't see anything suggesting bug with the HttpClient. It is relaying information back to you and you will need to handle it in your app.

**Comment by karelz** [comment]
Closing for now as it is not actionable without isolated repro. If you get more information / small repro to ensure this is not a specific environment problem, feel free to reopen. Thanks!
