### ISSUE TITLE
'LinkerFatalErrorException' thrown when building PowerShell with Assembly-level trimming

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#47693]
I know PowerShell may not be the target audence of the App Trimming feature in .NET 5 given that it depends on reflection so much, but I gave it a try out of curiosity and saw a `LinkerFatalErrorException` thrown during the build, so I just report it here:

```
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft.WSMan.Runtime -> C:\arena\repos\PowerShell\src\Microsoft.WSMan.Runtime\bin\Release\net5.0\Microsoft.WSMan.Runtime.dll
  Microsoft.PowerShell.CoreCLR.Eventing -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.CoreCLR.Eventing\bin\Release\net5.0\Microsoft.PowerShell.CoreCLR.Eventing.dll
  System.Management.Automation -> C:\arena\repos\PowerShell\src\System.Management.Automation\bin\Release\net5.0\System.Management.Automation.dll
  Microsoft.PowerShell.Security -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.Security\bin\Release\net5.0\Microsoft.PowerShell.Security.dll
  Microsoft.PowerShell.Commands.Diagnostics -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.Commands.Diagnostics\bin\Release\net5.0\Microsoft.PowerShell.Commands.Diagnostics.dll
  Microsoft.Management.Infrastructure.CimCmdlets -> C:\arena\repos\PowerShell\src\Microsoft.Management.Infrastructure.CimCmdlets\bin\Release\net5.0\Microsoft.Management.Infrastructure.CimCmdlets.dll
  Microsoft.PowerShell.ConsoleHost -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.ConsoleHost\bin\Release\net5.0\Microsoft.PowerShell.ConsoleHost.dll
  Microsoft.PowerShell.Commands.Utility -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.Commands.Utility\bin\Release\net5.0\Microsoft.PowerShell.Commands.Utility.dll
  Microsoft.WSMan.Management -> C:\arena\repos\PowerShell\src\Microsoft.WSMan.Management\bin\Release\net5.0\Microsoft.WSMan.Management.dll
  Microsoft.PowerShell.Commands.Management -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.Commands.Management\bin\Release\net5.0\Microsoft.PowerShell.Commands.Management.dll
  Microsoft.PowerShell.SDK -> C:\arena\repos\PowerShell\src\Microsoft.PowerShell.SDK\bin\Release\net5.0\Microsoft.PowerShell.SDK.dll
  powershell-win-core -> C:\arena\repos\PowerShell\src\powershell-win-core\bin\Release\net5.0\win7-x64\pwsh.dll
ILLink : error IL1011: Failed to write 'obj\Release\net5.0\win7-x64\linked\System.Management.Automation.dll [C:\arena\repos\PowerShell\src\powershell-win-core\powershell-win-core.csproj]
  Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net5.0\win7-x64\linked\System.Management.Automation.dll
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Cecil.Pdb.ISymUnmanagedWriter2.CloseMethod()
     at Mono.Cecil.Pdb.SymWriter.CloseMethod()
     at Mono.Cecil.Pdb.NativePdbWriter.Write(MethodDebugInformation info)
     at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
     at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
     at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddNestedTypes(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddTypes()
     at Mono.Cecil.MetadataBuilder.BuildTypes()
     at Mono.Cecil.MetadataBuilder.BuildModule()
     at Mono.Cecil.MetadataBuilder.BuildMetadata()
     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
     at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [C:\arena\repos\PowerShell\src\powershell-win-core\powershell-win-core.csproj]
```

**Comment by danmosemsft** [comment]
@vitek-karas could you please transfer to the linker repo? I don't have powers.

**Comment by danmosemsft** [comment]
@daxian-dbw what did you do to trigger this -- what flags/repro?
