### ISSUE TITLE
PLINQ: throwing empty AggregateException leads to ObjectDisposedException

### ISSUE THREAD

**Issue by Gladskih** [dotnet/runtime#47710]
### Description
Being faced this unexpected behavior I found corresponding [thread on stackoverflow.com from 2013](https://stackoverflow.com/a/19392562/2336304)
[Reproducing on .Net 5: https://dotnetfiddle.net/zT8Djq](https://dotnetfiddle.net/zT8Djq)
```
using System;
using System.Linq;
try
{
	new int[10].AsParallel().Select<int, int>(i => throw new AggregateException()).ForAll(Console.WriteLine);
}
catch (AggregateException)
{
	Console.WriteLine("Expected");
}
catch (ObjectDisposedException)
{
	Console.WriteLine("Bug");
}
```
The code prints "Bug" when "Expected" expected.

The problem is caused by QueryTaskGroupState.QueryEnd() implementation.

**Comment by eiriktsarpalis** [comment]
I can reproduce the issue in .NET 5. This seems to be a bug in the `ParallelEnumerable.ForAll` implementation when the source enumerable specifically throws `AggregateException`:
```csharp
static void Main()
{
    Repro<Exception>(); // works as expected
    Repro<DivideByZeroException>(); // works as expected
    Repro<AggregateException>(); // throws ObjectDisposedException

    static void Repro<TException>() where TException : Exception, new()
    {
        try
        {
            Enumerable.Range(0, 1).AsParallel().Select(i => (i > 0) ? i : throw new TException()).ForAll(_ => { });
        }
        catch (AggregateException)
        {
            Console.WriteLine($"Repro with {typeof(TException).Name} works as expected.");
        }
    }
}
```
The above fails with the exception:
```
Unhandled exception. System.ObjectDisposedException: The query enumerator has been disposed.
Object name: 'enumerator'.
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
```
