### ISSUE TITLE
[wasm] plain Task marshaling failing

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#47780]
The bindings are failing when mashing a non generic task

Reproduce with the wasm console sample and a

```

using System;
using System.Threading.Tasks;

public class Test
{
    public static async Task Main(string[] args)
    {
        await Task.Delay(1);
        Console.WriteLine("Hello World!");
        for (int i = 0; i < args.Length; i++) {
            Console.WriteLine($"args[{i}] = {args[i]}");
        }
        return;
    }
}
```

Error is
```
Error: no idea on how to unbox value types
    at Object._unbox_mono_obj_rooted_with_known_nonprimitive_type (dotnet.js:1:175395)
    at Object._unbox_mono_obj_rooted (dotnet.js:1:176729)
    at Object._mono_array_to_js_array_rooted (dotnet.js:1:173432)
    at Object.mono_array_to_js_array (dotnet.js:1:172973)
    at Object.mono_wasm_parse_args (dotnet.js:1:205340)
    at _mono_wasm_invoke_js_with_args (dotnet.js:1:211789)
    at <anonymous>:wasm-function[10855]:0x1a848d
    at <anonymous>:wasm-function[3406]:0x7df7e
    at <anonymous>:wasm-function[2240]:0x488b7
    at <anonymous>:wasm-function[8112]:0x1423cf
```

**Comment by kg** [comment]
What args did you pass when running it?

**Comment by lewing** [comment]
just did a `make build run` in `src/mono/netcore/sample/wasm/console`

**Comment by lewing** [comment]
```
public class Test
{
    public static Task Main(string[] args)
    {
        Console.WriteLine("Hello World!");
        for (int i = 0; i < args.Length; i++) {
            Console.WriteLine($"args[{i}] = {args[i]}");
        }
        return Task.Delay(1);
    }
}
```
Works so it looks like we're doing something wrong around AsyncTaskMethodBuilder

**Comment by kjpou1** [comment]
It does not look like it ever gets to that part of the code.

the `async Task` is not of `Task` type but `System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Threading.Tasks.VoidTaskResult,Test+<Main>d__0]`

and the return is `System.Threading.Tasks.VoidTaskResult`
