### ISSUE TITLE
Out of range exception/crash during http certificate validation on Linux

### ISSUE THREAD

**Issue by vpopescu** [dotnet/runtime#47791]
### Description

When running on linux, I receive an exception during https connect ( see full exception at the bottom).

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```

### Configuration

5.0.102 SDK on both windows and linux.
Linux is WSL2 (Ubuntu distro), however it also fails the same way when running in a docker container with alpine, in azure AKS.

### Regression?

I don't know, but works on windows.

### Other information

I traced the crash down to this area of code in SslStreamCertificateContext.cs (which is part of System.Net.Security). During execution, count = 2, and chain.ChainElementsCount.Count = 2,  but the assignment inside the for loop attempts to read i+1 on second iteration, which is out of range. 

```
      // Count can be zero for a self-signed certificate, or a cert issued directly from a root.
                if (count > 0 && chain.ChainElements.Count > 1)
                {
                    intermediates = new X509Certificate2[count];
                    for (int i = 0; i < count; i++)
                    {
                        intermediates[i] = chain.ChainElements[i + 1].Certificate;
                    }
                }

```

That doesn't explain why I don't see it on windows (maybe It doesn't get here), but I think this is bad code anyway?

Full exception:

```
   at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
   at System.Net.Security.SslStreamCertificateContext.Create(X509Certificate2 target, X509Certificate2Collection additionalCertificates, Boolean offline)
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at  WssWarrClient.<>c__DisplayClass11_0.<<Get>b__0>d.MoveNext() in C:\source\...\WssClient.cs:line 125
--- End of stack trace from previous location ---
   at Polly.Caching.AsyncCacheEngine.ImplementationAsync[TResult](IAsyncCacheProvider`1 cacheProvider, ITtlStrategy`1 ttlStrategy, Func`2 cacheKeyStrategy, Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, Action`2 onCacheGet, Action`2 onCacheMiss, Action`2 onCachePut, Action`3 onCacheGetError, Action`3 onCachePutError)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)   
 ...
```

**Comment by stephentoub** [comment]
This looks like https://github.com/dotnet/runtime/issues/46654, which was fixed in https://github.com/dotnet/runtime/pull/46904 for the .NET 5.0.3 release.

**Comment by vpopescu** [comment]
Thanks. I don't know why my search didn't pick that up. Are there any workarounds until 5.0.3 comes out?

**Comment by stephentoub** [comment]
> Are there any workarounds until 5.0.3 comes out?

@wfurt?

**Comment by wfurt** [comment]
You can install root CA to the system.

**Comment by vpopescu** [comment]
Thank you, that worked. Sorry for the dupe. Will close.

**Comment by karelz** [comment]
Duplicate of #46654
