### ISSUE TITLE
[Tests] Accessing an already closed handle in System.IO.FileSystem.Watcher.Tests

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#47806]
```
/private/tmp/helix/working/BBD309BB/w/B0AD0982/e /private/tmp/helix/working/BBD309BB/w/B0AD0982/e
  Discovering: System.IO.FileSystem.Watcher.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Watcher.Tests (found 149 of 183 test cases)
  Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 6)
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 148
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) in /_/src/coreclr/System.Private.CoreLib/src/System/StubHelpers.cs:line 1247
   at Interop.EventStream.FSEventStreamUnscheduleFromRunLoop(SafeEventStreamHandle streamRef, IntPtr runLoop, SafeCreateHandle runLoopMode)
   at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.UnscheduleFromRunLoop(SafeEventStreamHandle eventStream) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 221
   at System.IO.FileSystemWatcher.RunningInstance.CleanupEventStream() in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 277
   at System.IO.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr streamRef, IntPtr clientCallBackInfo, IntPtr numEvents, Byte** eventPaths, FSEventStreamEventFlags* eventFlags, UInt64* eventIds) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 353
./RunTests.sh: line 162: 64867 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.FileSystem.Watcher.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Watcher.Tests.deps.json xunit.console.dll System.IO.FileSystem.Watcher.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/BBD309BB/w/B0AD0982/e
----- end Mon Feb 1 22:08:37 EST 2021 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
ulimit -c value: unlimited
```

log https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-73bfe3c9deb84eec88/System.IO.FileSystem.Watcher.Tests/console.00f80181.log?sv=2019-07-07&se=2021-02-22T03%3A07%3A50Z&sr=c&sp=rl&sig=j8bREhoOa%2FpJ6oiX%2BMrHUW7k0JL%2FhFo31NPBd94g37Y%3D

build https://dev.azure.com/dnceng/public/_build/results?buildId=975008&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b&t=caea1d4b-c90c-5be1-e57d-c4635079c333&l=87

**Comment by BrennanConroy** [comment]
Same issue as https://github.com/dotnet/runtime/issues/30056

**Comment by Anipik** [comment]
@adamsitnik is there any update on this one ?

**Comment by ViktorHofer** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/30056
