### ISSUE TITLE
Failing assert in ILogB benchmark

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#47856]
I've merged one big PR of mine to the performance repo and some CI legs went red after that. I thought it was my fault, but according to the [logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-performance-refs-heads-master-b0e291e414a14b52b3/Partition0/console.94d3d474.log?sv=2019-07-07&se=2021-02-24T12%3A04%3A47Z&sr=c&sp=rl&sig=IWpBGVp7VJ0YkF6VTB3etbJSGxm7l5EWkCWhKYaJowk%3D) the windows CI leg for .NET 6 failed because of the following condition:

https://github.com/dotnet/performance/blob/4e14ecc54759224121b807c70e46fb1d9ee0e7d6/src/benchmarks/micro/runtime/Math/Functions/Double/ILogB.cs#L31

```log
[2021/02/04 12:35:55][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2021/02/04 12:35:55][INFO]  ---> System.Exception: Expected Result                 2499; Actual Result                    0
[2021/02/04 12:35:55][INFO]    at System.MathBenchmarks.Double.ILogBTest() in C:\h\w\A401087B\p\src\benchmarks\micro\runtime\Math\Functions\Double\ILogB.cs:line 33
[2021/02/04 12:35:55][INFO]    at System.MathBenchmarks.Double.ILogB() in C:\h\w\A401087B\p\src\benchmarks\micro\runtime\Math\Functions\Double\ILogB.cs:line 18
[2021/02/04 12:35:55][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_354.WorkloadActionUnroll(Int64 invokeCount) in C:\h\w\A401087B\p\artifacts\bin\MicroBenchmarks\Release\net6.0\aba3fe28-ae33-452f-9d08-31981993ac55\aba3fe28-ae33-452f-9d08-31981993ac55.notcs:line 210808
```

I was able to reproduce it on my PC:

```cmd
git clone https://github.com/dotnet/performance.git repro
py .\repro\scripts\benchmarks_ci.py -f net6.0 --filter System.MathBenchmarks.Double.ILogB
```

@tannergooding is this expected?

**Comment by adamsitnik** [comment]
@briansull @tannergooding PTAL

**Comment by tannergooding** [comment]
Individual cases of `ILogB` are constant folding and returning the correct result, any kind of `for` loop breaks things however.

The simplest repro I've gotten is:
```csharp
int result = 0;
double value = 2.0;

for (int iteration = 0; iteration < 1; iteration++)
{
    result += Math.ILogB(value);
}

Console.WriteLine(result);
```

Manually `value` causes it to no longer repro

**Comment by tannergooding** [comment]
A [JitDump.txt](https://github.com/dotnet/runtime/files/5927559/JitDump.txt)

**Comment by tannergooding** [comment]
The codegen ends up being:
```
IN0006: 000000 sub      rsp, 40

G_M29659_IG02:        ; offs=000004H, size=0012H, bbWeight=4    PerfScore 11.00, gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref

IN0001: 000004 mov      ecx, 2
IN0002: 000009 call     System.Math:ILogB(double):int
IN0003: 00000E mov      ecx, eax
IN0004: 000010 call     System.Console:WriteLine(int)
IN0005: 000015 nop      

G_M29659_IG03:        ; offs=000016H, size=0005H, bbWeight=4    PerfScore 5.00, epilog, nogc, extend

IN0007: 000016 add      rsp, 40
IN0008: 00001A ret    
```

which is incorrect since it's treating a double as `int`...

It looks like there is an incorrect cast being inserted:
```
Importing BB02 (PC=016) of 'ConsoleApp14.Program:Main(System.String[])'
    [ 0]  16 (0x010) ldloc.0
    [ 1]  17 (0x011) ldloc.1
    [ 2]  18 (0x012) call 0A00000B
In Compiler::impImportCall: opcode is call, kind=0, callRetType is int, structSize is 0
Named Intrinsic System.Math.ILogB: Recognized

    [ 2]  23 (0x017) add
    [ 1]  24 (0x018) stloc.0

STMT00004 (IL 0x010...  ???)
               [000019] -AC---------              *  ASG       int   
               [000018] D------N----              +--*  LCL_VAR   int    V01 loc0         
               [000017] --C---------              \--*  ADD       int   
               [000013] ------------                 +--*  LCL_VAR   int    V01 loc0         
               [000016] --C---------                 \--*  INTRINSIC int    ilogb
               [000015] ------------                    \--*  CAST      int <- double
               [000014] ------------                       \--*  LCL_VAR   double V02 loc1         
```

which is being done here if the operand and source type don't match: https://github.com/dotnet/runtime/blob/master/src/coreclr/jit/importer.cpp#L4625-L4628.

It isn't clear why this was done or if its necessary. Is it possibly trying to account for `float->double`?

**Comment by AndyAyersMS** [comment]
Seems like maybe we never had a math intrinsic that had this kind of signature before.

cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@JulieLeeMSFT can we find an owner for this?

**Comment by tannergooding** [comment]
@AndyAyersMS, I can get up a fix (it was my PR that surfaced the issue anyways).

The simplest thing looks to be basically:
```csharp
                if ((op1->TypeGet() != callType) && varTypeIsFloating(callType))
                {
                    op1 = gtNewCastNode(callType, op1, false, callType);
                }
```

It just isn't clear if we could actually remove the cast nodes entirely as an alternative.

**Comment by kunalspathak** [comment]
I will try to incorporate @tannergooding 's suggestion (unless he is already working on it).

**Comment by kunalspathak** [comment]
Looks like Tanner is already working on it. Reassigning them.

**Comment by tannergooding** [comment]
I'm just finishing testing locally, I should have a PR up in a few minutes.

**Comment by tannergooding** [comment]
Fix is up: https://github.com/dotnet/runtime/pull/47923
