### ISSUE TITLE
Unit tests are failing for .NET Core v.2.1.24 built on Amazon Linux 2

### ISSUE THREAD

**Issue by klementi** [dotnet/runtime#47941]
### Description

Unit tests are failing for .NET Core v.2.1.24 built on Amazon Linux 2
https://github.com/dotnet/corefx/releases/tag/v2.1.24

Steps to repro
1. Create Amazon Linux 2 container from https://hub.docker.com/ using *docker pull amazonlinux:2.0.20210126.0*
2. Clone repository inside the container, build, run unit tests
3. See folowing unit test failing

```
Starting:    System.IO.Tests
   System.IO.Pipelines.Tests.PipeWriterTests.WriteAsyncWithACompletedReaderNoops [FAIL]
   Assert.Equal() Failure
      Expected: 0
      Actual:   1


Starting:    System.Runtime.Tests
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1940-02-25T00:00:00.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 2/25/40 12:00:00 AM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1940-11-20T00:00:00.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 11/20/40 12:00:00 AM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1940-12-31T23:59:59.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 12/31/40 11:59:59 PM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1941-01-01T00:00:00.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 1/1/41 12:00:00 AM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1945-02-24T12:00:00.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 2/24/45 12:00:00 PM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1945-11-17T01:00:00.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 11/17/45 1:00:00 AM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)
   System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(dateTimeString: \"1945-11-17T22:59:59.0000000Z\", expectedDST: True, expectedOffsetString: \"1:00:00\") [FAIL]
      Test with the zone Africa/Casablanca and date 11/17/45 10:59:59 PM failed
      Expected: True
      Actual:   False
      Stack Trace:
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1996,0): at System.Tests.TimeZoneInfoTests.VerifyDST(TimeZoneInfo tz, DateTime dt, Boolean expectedDST)
         /build/corefx/src/System.Runtime/tests/System/TimeZoneInfoTests.cs(1735,0): at System.Tests.TimeZoneInfoTests.IsDaylightSavingTime_CasablancaMultiYearDaylightSavings(String dateTimeString, Boolean expectedDST, String expectedOffsetString)

```

### Configuration

.NET Core v.2.1.24
https://github.com/dotnet/corefx/releases/tag/v2.1.24

Operating System: Amazon Linux 2, https://aws.amazon.com/amazon-linux-2/
Kernel: Linux 4.14.214-160.339.amzn2.x86_64
Architecture: x86-64
Public AMI ID: ami-0e999cbd62129e3b1 (Amazon Linux 2 AMI 2.0.20210126.0 x86_64 HVM gp2)

### Regression?

Yes, all unit tests pass on the same OS for .NET Core v.2.1.22

Changes that probably affected regression

https://github.com/dotnet/corefx/pull/42982/files

### Other information

TimeZoneInfoTests issues are already known
https://github.com/dotnet/runtime/issues/31331

**Comment by danmosemsft** [comment]
@BrennanConroy does this relate to the linked servicing fix you made?

**Comment by BrennanConroy** [comment]
Yep, the test might need to always assert 1. I don't have a working VS2017 installation currently, I'll look into getting one.

**Comment by hunanniu** [comment]
Any update on this issue?

**Comment by danmoseley** [comment]
@klementi @hunanniu how is this impacting you? Are you impacted by a bug this test is flagging, or by the test run not being clean?
Also, are these the only failures for you?

**Comment by klementi** [comment]
@danmoseley 

we would happily exclude that test as it only affect our build pipeline (unit test phase), we would like to hear your opinion on that

on a separate note we have one more issue, this time with core 2.1.15 build
when we build corefx, it fails with

[Container] 2021/02/12 19:04:24 Running command LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/ src/pal/tests/palsuite/runpaltests.sh /build/$CORECLR_REPO_NAME/bin/obj/Linux.x64.Release

The following test(s) failed:

c_runtime/iswxdigit/test1/paltest_iswxdigit_test1. Exit code: 127

PAL Test Results:

  Passed: 773
  Failed: 1

Do you want us to open separate issue for that?

**Comment by danmoseley** [comment]
@tarekgh may have an explanation for the timezone issue above. If it's benign - I think we would recommend that you ignore it.

Yes, a separate issue for the build failure would be good. Thanks

**Comment by tarekgh** [comment]
This looks to me the timezone data on that container somehow not updated or different than what we get in other Linux containers. 

@klementi if it is handy, would you share the zone data file for `Africa/Casablanca` from this Amazon Linux container? I can try to set it up later and get it if it is not handy.

**Comment by am11** [comment]
> c_runtime/iswxdigit/test1/paltest_iswxdigit_test1. Exit code: 127

This test can be safely ignored. It was deleted in https://github.com/dotnet/coreclr/pull/24608 (to fix https://github.com/dotnet/runtime/issues/12702); as, unlike other C APIs in PAL, we do not have our own implementation of `iswxdigit` (we use the one from C standard library header `<wctype.h>`).

**Comment by klementi** [comment]
@danmoseley can we also disable System.IO.Pipelines.Tests.PipeWriterTests.WriteAsyncWithACompletedReaderNoops unit test temporarily?

**Comment by danmoseley** [comment]
@klementi do you mean, disable the tests locally? of course that is up to you. Or, do you mean, you'd like to submit a change to our repo to disable it for Amazon Linux? Or are you asking whether it matters that it is failing -- @BrennanConroy would have to answer that.

**Comment by klementi** [comment]
Yes, our plan is to disable this test locally, but we would like to understand the implications

**Comment by tarekgh** [comment]
I have looked at why the time zone tests failed. I dumped the data from the file `/usr/share/zoneinfo/Africa/Casablanca` and I am seeing the following:

```
00 08 4C 4D 54 00 2B 30 31 00 2B 30 30 00 00 00 00 00 00 00 00 00 00 00 0A 3C 2B 30 30 3E 30 3C 2B 30 31 3E 2C 30 2F 30 2C 4A 33 36 35 2F 32 35 0A

�LMT�+01�+00�����������
<+00>0<+01>,0/0,J365/25
```

This data indicate it is using Julian day format which we don't currently support. For more info, look at comment 
https://github.com/dotnet/runtime/blob/e5ae9882e76b601aa345230b4a3586e3225b4ff2/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.cs#L1205

By the way, Amazon Linux is based on `centos rhel fedora` which they decide to generate the time zone file formats differently than other Linux distros. 

CC @eerhardt

**Comment by BrennanConroy** [comment]
Pipelines test fixed in https://github.com/dotnet/corefx/pull/43042

I believe the other issues have tracking issues so closing.
