### ISSUE TITLE
Test failed : System.Data.Tests.AppDomainsAndFormatInfo.Bug55978

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47968]
Run: [runtime 20210206.8](https://dev.azure.com/dnceng/public/_build/results?buildId=981759&view=ms.vss-test-web.build-test-results-tab&runId=30771648&resultId=114463&paneView=debug)

Failed test: 
```
net6.0-Browser-Release-wasm-Mono_Release-wasmtestonbrowser-Ubuntu.1804.Amd64.Open

  -System.Data.Tests.AppDomainsAndFormatInfo.Bug55978
```

**Error message:**
```
Assert.Equal() Failure
Expected: 2
Actual:   3


Stack trace
   at System.Data.Tests.AppDomainsAndFormatInfo.Bug55978()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by eerhardt** [comment]
Also failed on browser-wasm in https://github.com/dotnet/runtime/pull/48181/, so I don't believe this is x64 specific.

https://helix.dot.net/api/2019-06-17/jobs/05ea776a-fb59-4058-8691-82b19e0ca827/workitems/System.Data.Common.Tests/console

```
[17:03:32] info: Arguments: --run,WasmTestRunner.dll,System.Data.Common.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[17:03:33] info: console.debug: MONO_WASM: Initializing mono runtime
[17:03:33] info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[17:03:33] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[17:03:33] info: Initializing.....
[17:03:33] info: Discovering: System.Data.Common.Tests.dll (method display = ClassAndMethod, method display options = None)
[17:03:34] info: Discovered:  System.Data.Common.Tests.dll (found 1787 of 1813 test cases)
[17:03:34] info: Starting:    System.Data.Common.Tests.dll
[17:03:37] fail: [FAIL] System.Data.Tests.AppDomainsAndFormatInfo.Bug55978
[17:03:37] info: Assert.Equal() Failure
[17:03:37] info: Expected: 2
[17:03:37] info: Actual:   3
[17:03:37] info:    at System.Data.Tests.AppDomainsAndFormatInfo.Bug55978()
[17:03:37] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:04:01] info: Finished:    System.Data.Common.Tests.dll
[17:04:01] info: 
[17:04:01] info: === TEST EXECUTION SUMMARY ===
[17:04:01] info: Total: 11692, Errors: 0, Failed: 1, Skipped: 10, Time: 26.736458s
```

**Comment by GrabYourPitchforks** [comment]
Also failed in https://github.com/dotnet/runtime/pull/50951/checks?check_run_id=2300492544.

**Comment by VincentBu** [comment]
Failed again in [runtime 20210425.28](https://dev.azure.com/dnceng/public/_build/results?buildId=1106929&view=ms.vss-test-web.build-test-results-tab&runId=33794782&resultId=121168&paneView=debug)

Failed test:
```
net6.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open
 -System.Data.Tests.AppDomainsAndFormatInfo.Bug55978
```

**Error message:**
```
Assert.Equal() Failure
Expected: 2
Actual:   3


Stack trace
   at System.Data.Tests.AppDomainsAndFormatInfo.Bug55978()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by ajcvickers** [comment]
@eerhardt What's the appropriate action here? I don't believe we have touched this code in a long time, so it seems likely that if this has recently started failing, then this is due to some wider change.

**Comment by eerhardt** [comment]
As far as I can tell, this is only failing on wasm, even though the label has `arch-x64`. I think that label is a mistake because the first instance of this failing says:

```
net6.0-Browser-Release-wasm-Mono_Release-wasmtestonbrowser-Ubuntu.1804.Amd64.Open
```

I think it was running browser-wasm on an x64 machine. This is a wasm bug. Fixing the labels.

**Comment by radical** [comment]
Failed again - https://dev.azure.com/dnceng/public/_build/results?buildId=1274300&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4 on https://github.com/dotnet/runtime/pull/56802/checks?check_run_id=3236115645

@lewing do you think this needs to be looked at for 6.0? It has happened only [thrice in the last month](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+result%3Afailed+name%3A%22system.data.tests.appdomainsandformatinfo.bug55978%22). But since it's happening only on wasm, and is sporadic, I wonder if it might be hiding some weird bug.

**Comment by vargaz** [comment]
The test has something to do with dates/times, so it's possible that it only fails at certain dates/times like at midnight etc.

**Comment by lewing** [comment]
@radical we could try improving test assertions so that it was clear how it is failing

**Comment by radical** [comment]
Opened a PR that will dump some info when the test fails - https://github.com/dotnet/runtime/pull/56838
