### ISSUE TITLE
[mono] Add support for IgnoresAccessChecksToAttribute 

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#47989]
The issue is specific to mono.

Most likely same issue exists for InternalsVisibleTo but this was not tested.

See System.Reflection.DispatchProxy tests disabled with this issue number. All tests are using TestType_PrivateProxy. Tests look similar to this:

```csharp
public class TestType_PrivateProxy
{
    public static T Proxy<T>() => DispatchProxy.Create<T, InvokeProxy<T>>();

    private class InvokeProxy<T> : DispatchProxy
    {
        protected override object Invoke(MethodInfo targetMethod, object[] args) => null;
    }
}

// Testcase (pass any interface as generic argument):
TestType_PrivateProxy.Proxy<TestType_InternalInterfaceService>()
```

the dispatch proxy adds IgnoresAccessChecksToAttribute to the assembly so that it can use that private type but gets:

```
[22:32:12] fail: [FAIL] DispatchProxyTests.DispatchProxyTests.Create_Using_PrivateProxy
[22:32:12] info: System.MethodAccessException : Method `TestType_PrivateProxy+InvokeProxy`1[TestType_IHelloService]..ctor()' is inaccessible from method `generatedProxy_2..ctor(System.Reflection.MethodInfo[])'
[22:32:12] info:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
[22:32:12] info:    at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[22:32:12] info:    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[22:32:12] info:    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
[22:32:12] info:    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
[22:32:12] info:    at System.Activator.CreateInstance(Type type, Object[] args)
[22:32:12] info:    at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type baseType, Type interfaceType)
[22:32:12] info:    at System.Reflection.DispatchProxy.Create[TestType_IHelloService,InvokeProxy`1]()
[22:32:12] info:    at TestType_PrivateProxy.Proxy[TestType_IHelloService]()
[22:32:12] info:    at DispatchProxyTests.DispatchProxyTests.Create_Using_PrivateProxy()
[22:32:12] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

note: [Tests are currently in PR](https://github.com/dotnet/runtime/pull/47903)

**Comment by lambdageek** [comment]
> Most likely same issue exists for InternalsVisibleTo but this was not tested.

Not sure this is true.  Mono has support for `InternalsVisibleTo`.

@krwq is there some conceptual case that you have in mind?

**Comment by krwq** [comment]
@lambdageek I assume you mean in general for this issue: DispatchProxy and Ref.Emit in general is what needs IgnoresAccessChecksToAttribute the most. Without it you can't really use any private types.

**Comment by lambdageek** [comment]
> @lambdageek I assume you mean in general for this issue: DispatchProxy and Ref.Emit in general is what needs IgnoresAccessChecksToAttribute the most. Without it you can't really use any private types.

Sorry, I phrased my question poorly.  I know we don't have `IgnoresAccessChecksTo` - so we will definitely need to add support for it. I meant is there a use of `InternalsVisibleTo` that you suspect doesn't work? Mono has had `InternalsVisibleTo` for a really long time, but maybe there's some corner case that doesn't work.

**Comment by krwq** [comment]
@lambdageek, no, nothing specific. I solely based this on a guess - I've been involved in a similar issue in coreclr and they were implemented using similar code paths
