### ISSUE TITLE
Single/Double/Half/Decimal need more test cases for parsing 

### ISSUE THREAD

**Issue by pgovind** [dotnet/runtime#48119]
Follow up for https://github.com/dotnet/runtime/pull/47666/files#r569703812

Tests need to be added for at least:
1) Simple floating point number starting with a `.`. For ex: `.234`
2) Simple floating point number with a `.` as it's last digit. 
3) Floating point number with a `.` at single/double/half/decimal.MaxDigitCount
4) Floating point number with a `.` after single/double/half/decimal.MaxDigitCount

**Comment by ayousuf23** [comment]
Hey,
I haven't contributed before, but I would like to start. Do you think this is something up my alley? If so, where should I add the tests?

**Comment by danmoseley** [comment]
Welcome to the repo, @ayousuf23 ! @pgovind can point you to the right places.

**Comment by ayousuf23** [comment]
@danmoseley Thanks! Please take a look at my website https://ayousuf23.github.io

**Comment by pgovind** [comment]
> Do you think this is something up my alley? If so, where should I add the tests?

Hello @ayousuf23 ! Welcome!

Test cases for `Single` can be added to `SingleTests.cs`. `Double` in `DoubleTests.cs`, Half in `HalfTests.cs` and `Decimal` in `DecimalTests.cs`. All of these files are in `src\libraries\System.Runtime\tests\System\`. I recommend adding the test cases under the `Parse_Valid_TestData` method in each file. Since this is your first time starting with the repo, looking at the ["Workflow Instructions"](https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md) will be useful and will help you ensure that the new tests pass! 

Let me know if you get stuck or need help!

**Comment by ayousuf23** [comment]
Alright! Thanks for the help! @pgovind can you assign this issue to me?

**Comment by ayousuf23** [comment]
I am getting this error:
`
System.Tests.DoubleTests.Parse_Span_Valid(value: "-123456789012345678.", offset: 0, count: 20, style: AllowThousands | Float, provider: null, expected: -1.2345678901234566E+17) [FAIL]
        Assert.Equal() Failure
        Expected: -1.2345678901234566E+17
        Actual:   -1.2345678901234568E+17
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Runtime\tests\System\DoubleTests.cs(615,0): at System.Tests.DoubleTests.Parse_Span_Valid(String value, Int32 offset, Int32 count, NumberStyles style, IFormatProvider provider, Double expected)
      System.Tests.DoubleTests.Parse(value: "-123456789012345678.", style: AllowThousands | Float, provider: null, expected: -1.2345678901234566E+17) [FAIL]
        Assert.Equal() Failure
        Expected: -1.2345678901234566E+17
        Actual:   -1.2345678901234568E+17
`
from this line:
`yield return new object[] { "-123456789012345678.", defaultStyle, null, -1.2345678901234567E17 };`

**Comment by ayousuf23** [comment]
@pgovind I got an assert failure error when trying to test a double with . at the 19 digit place. It appears the double parsed from the string is different than the double I expected (the difference is in the 17th digit).

**Comment by pgovind** [comment]
> System.Tests.DoubleTests.Parse_Span_Valid(value: "-123456789012345678.", offset: 0, count: 20, style: AllowThousands | Float, provider: null, expected: -1.2345678901234566E+17) [FAIL] Assert.Equal() Failure Expected: -1.2345678901234566E+17 Actual: -1.2345678901234568E+17

I believe `1.2345678901234568E17` is the correct value here so it looks like the `Expected` value should be modified in the unit test?

**Comment by pgovind** [comment]
For reference, here is the maxDigitCount for `double/float/single/half`.

``` csharp
     internal const int DecimalNumberBufferLength = 29 + 1;  // 29 for the longest input + 1 for rounding
        internal const int DoubleNumberBufferLength = 767 + 1;  // 767 for the longest input + 1 for rounding: 4.9406564584124654E-324
        internal const int SingleNumberBufferLength = 112 + 1;  // 112 for the longest input + 1 for rounding: 1.40129846E-45
        internal const int HalfNumberBufferLength = 20; // 19 for the longest input + 1 for rounding (+1 for the null terminator)
```

What you want to test is something like:

``` csharp
string input = "6" + new string("0", 766) +"."; // I may be off by 1 here, you'd have to double check
var parsedDouble = Double.Parse(input); //aim here is that the last digit that is parsed [here](https://source.dot.net/#System.Private.CoreLib/Number.Parsing.cs,336) should be a `.`
```

Once you get the tests up for double, the other types should be easy to wire up!

**Comment by ayousuf23** [comment]
Sorry for not commenting in some time. I was very busy due to exams. 
Anyways, I wrote the tests and they all pass except for decimal. The error I am getting is that the expected decimal is different than the actual one.

Here is the relevant code:
```
string inputForDecimalWithDotAtMaxDigit = "6" + new string('1', 27) + ".";
            yield return new object[] { inputForDecimalWithDotAtMaxDigit, defaultStyle, null, Double.Parse(inputForDecimalWithDotAtMaxDigit) };
            string inputForDecimalWithDotAfterMaxDigits = "1" + inputForDecimalWithDotAtMaxDigit;
            yield return new object[] { inputForDecimalWithDotAfterMaxDigits, defaultStyle, null, Double.Parse(inputForDecimalWithDotAfterMaxDigits) };
```
Here are the errors:
```
System.Tests.DecimalTests.Parse(value: "6111111111111111111111111111.", style: Number, provider: null, expected: 6111111111111110000000000000) [FAIL]
        Assert.Equal() Failure
        Expected: 6111111111111110000000000000
        Actual:   6111111111111111111111111111
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Runtime\tests\System\DecimalTests.cs(830,0): at System.Tests.DecimalTests.Parse(String value, NumberStyles style, IFormatProvider provider, Decimal expected)
      System.Tests.DecimalTests.Parse(value: "16111111111111111111111111111.", style: Number, provider: null, expected: 16111111111111100000000000000) [FAIL]
        Assert.Equal() Failure
        Expected: 16111111111111100000000000000
        Actual:   16111111111111111111111111111
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Runtime\tests\System\DecimalTests.cs(830,0): at System.Tests.DecimalTests.Parse(String value, NumberStyles style, IFormatProvider provider, Decimal expected)
      System.Tests.DecimalTests.Parse_Span_Valid(value: "6111111111111111111111111111.", offset: 0, count: 29, style: Number, provider: null, expected: 6111111111111110000000000000) [FAIL]
        Assert.Equal() Failure
        Expected: 6111111111111110000000000000
        Actual:   6111111111111111111111111111
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Runtime\tests\System\DecimalTests.cs(2292,0): at System.Tests.DecimalTests.Parse_Span_Valid(String value, Int32 offset, Int32 count, NumberStyles style, IFormatProvider provider, Decimal expected)
      System.Tests.DecimalTests.Parse_Span_Valid(value: "16111111111111111111111111111.", offset: 0, count: 30, style: Number, provider: null, expected: 16111111111111100000000000000) [FAIL]
        Assert.Equal() Failure
        Expected: 16111111111111100000000000000
        Actual:   16111111111111111111111111111
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Runtime\tests\System\DecimalTests.cs(2292,0): at System.Tests.DecimalTests.Parse_Span_Valid(String value, Int32 offset, Int32 count, NumberStyles style, IFormatProvider provider, Decimal expected)
```

**Comment by ayousuf23** [comment]
@pgovind Please see the comment above. Thanks!

**Comment by ayousuf23** [comment]
@pgovind Sorry for not commenting in some time. I was very busy due to exams. I encountered an issue after writing all the tests. All the tests pass except for two tests for the half type.
Here is the relevant code:
```
  string inputForHalfWithDotAtMaxDigit = "6" + new string('1', 18) + ".";
            yield return new object[] { inputForHalfWithDotAtMaxDigit, defaultStyle, null, Half.Parse(inputForHalfWithDotAtMaxDigit) };
            string inputForHalfWithDotAfterMaxDigits = "1" + inputForHalfWithDotAtMaxDigit;
            yield return new object[] { inputForHalfWithDotAfterMaxDigits, defaultStyle, null, Half.Parse(inputForHalfWithDotAfterMaxDigits) };
```

Here are the errors:
```
System.Tests.HalfTests.Parse_Span_Valid [FAIL]
        System.Reflection.AmbiguousMatchException : Ambiguous match found.
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Private.CoreLib\src\System\DefaultBinder.cs(608,0): at System.DefaultBinder.SelectMethod(BindingFlags bindingAttr, MethodBase[] match, Type[] types, ParameterModifier[] modifiers)
          C:\Users\abdullah\Documents\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(2759,0): at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
          C:\Users\abdullah\Documents\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(2715,0): at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\RuntimeReflectionExtensions.cs(74,0): at System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(Type type, String name, Type[] parameters)
      System.Tests.HalfTests.Parse [FAIL]
        System.Reflection.AmbiguousMatchException : Ambiguous match found.
        Stack Trace:
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Private.CoreLib\src\System\DefaultBinder.cs(608,0): at System.DefaultBinder.SelectMethod(BindingFlags bindingAttr, MethodBase[] match, Type[] types, ParameterModifier[] modifiers)
          C:\Users\abdullah\Documents\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(2759,0): at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
          C:\Users\abdullah\Documents\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(2715,0): at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
          C:\Users\abdullah\Documents\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\RuntimeReflectionExtensions.cs(74,0): at System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(Type type, String name, Type[] parameters)
```

**Comment by ayousuf23** [comment]
@pgovind Please see my previous message.

**Comment by pgovind** [comment]
Hey @ayousuf23! It looks like Reflection is throwing an error because it is not able to uniquely identify a method that you are trying to call. Can you push your changes/(open a PR) so I can see what your code looks like?

**Comment by ayousuf23** [comment]
@pgovind I submitted a PR regarding this issue. Please check it out and let me know what to fix.

**Comment by ayousuf23** [comment]
@pgovind Please take a look at my PR.

**Comment by ayousuf23** [comment]
@pgovind Sorry for disturbing. Can you please take a look at my PR?

**Comment by pgovind** [comment]
> Sorry for disturbing. Can you please take a look at my PR?

No need to apologize! I missed that PR because I wasn't tagged on it, so I never got a notification from GitHub. Left a comment on the PR

**Comment by ayousuf23** [comment]
I will try to fix this and submit a new PR today.

**Comment by ayousuf23** [comment]
@pgovind For testing parsing a floating point number with a `.` at or after `single/double/half/decimal.MaxDigitCount`, the number would to be parsed would be greater than `half/float/double/decimal.MaxValue`. For example, testing `"6" + new string('0', 110) + "."` would not work since 6E110 is greater than `float.MaxValue`. 

Is this correct?

**Comment by pgovind** [comment]
> Is this correct?

Indeed yes. I haven't checked this yet, but I think you'll hit an OverflowException? There must be other tests in the same file that test this behavior. Might be worth looking at to see how they test such cases

**Comment by ayousuf23** [comment]
@pgovind I updated the PR (#52994). Please take a look at it.
