### ISSUE TITLE
TimeSpanFormat crashing with "Fatal error. Internal CLR error. (0x80131506)"

### ISSUE THREAD

**Issue by deiruch** [dotnet/runtime#48284]
### Description

When running the following .NET 5.0 Core Console Application in Visual Studio with Debugger attached (F5), this program produces an internal CLR error approx. every fifth time it is started:

```cs
using System;

Console.WriteLine($"{TimeSpan.Zero:h\\:mm\\:ss\\.f,10}");
```

Expected outcome (happens most of the time): `System.FormatException: Input string was not in a correct format.`
Actual outcome (happens sometimes): Program crashes with this stack trace
```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.String.Ctor(System.ReadOnlySpan`1<Char>)
   at System.Span`1[[System.Char, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToString()
   at System.Globalization.TimeSpanFormat.FormatCustomized(System.TimeSpan, System.ReadOnlySpan`1<Char>, System.Globalization.DateTimeFormatInfo, System.Text.StringBuilder)
   at System.Globalization.TimeSpanFormat.TryFormat(System.TimeSpan, System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
   at System.TimeSpan.TryFormat(System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
   at System.Text.ValueStringBuilder.AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.String.FormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.String.Format(System.String, System.Object)
   at <Program>$.<Main>$(System.String[])
```

### Configuration

Environment.OSVersion: `Microsoft Windows NT 10.0.19042.0`
Environment.Version: `5.0.3`
CPU: x64 (AnyCPU)

Happens in Debug and Release mode

### Regression?

Don't know.

### Other information

I cannot reproduce the problem on the console. It repros only in Visual Studio, with debugger attached.

**Comment by GrabYourPitchforks** [comment]
Are you F10 stepping over this line, F11 stepping into this line, or something else? My best guess is that the debugger is trying to show a data structure in the locals window but that the data structure hasn't yet been initialized.

**Comment by deiruch** [comment]
This happens without stepping. F5 is all it takes.

**Comment by EgorBo** [comment]
@deiruch What is your `CultureInfo.CurrentCulture`? Also, could you please specify the VS version.

**Comment by deiruch** [comment]
InvariantCulture shows the same effect:
```cs
using System;
using System.Globalization;

CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
Console.WriteLine($"{TimeSpan.Zero:h\\:mm\\:ss\\.f,10}");
```

Visual Studio 16.8.5

**Comment by EgorBo** [comment]
> InvariantCulture shows the same effect:
> 
> ```cs
> using System;
> using System.Globalization;
> 
> CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
> Console.WriteLine($"{TimeSpan.Zero:h\\:mm\\:ss\\.f,10}");
> ```
> 
> Visual Studio 16.8.5

Do you place a breakpoint or just hit F5 and eventually the crash occurs? 
I have exactly the same setup and see no crashes so far.

**Comment by deiruch** [comment]
I just hit F5, without any breakpoints.

**Comment by danmoseley** [comment]
Routing to diagnostics as it only happens under debugger.

**Comment by hoyosjs** [comment]
@deiruch Quick thing that could help narrow this quite a bit. 

- What version of the runtime are you using?
- What version of the VS debugger are you using?

**Comment by deiruch** [comment]
> @deiruch Quick thing that could help narrow this quite a bit. What version of the VS debugger are you using?

Where do I find the version?

**Comment by hoyosjs** [comment]
@deiruch I was able to repro the issue. Using JMC is the only way I've found to repro. 

Looks like the unhandled exception hijack happened, then we were trying to notify the debugger of the second change exception and we started draining funcevals. One of them was to do a ToString on a `System.Span<Char>`, I can't seem to find what the debugger is evaluating (not sure if it's something in the exception, not sure if it's the string literal for the parameter of the string format. I can't find the reference to the string of byref param. One interesting thing is looking at the that the `FuncEvalHijackWorker`, we are working in preemptive mode, rather than in coop that we are expecting. This might be the reason I can't find the local.

```
000000A0189BB270 00007FFBCE64CF25 coreclr!EEPolicy::HandleFatalError + 185 at E:\repos\runtime\src\coreclr\src\vm\eepolicy.cpp:765
000000A0189BB880 00007FFBCE5D4FAC coreclr!CLRVectoredExceptionHandlerPhase2 + 721708 at E:\repos\runtime\src\coreclr\src\vm\excep.cpp:7231
000000A0189BB8E0 00007FFBCE524C6F coreclr!CLRVectoredExceptionHandler + 139 at E:\repos\runtime\src\coreclr\src\vm\excep.cpp:7198
000000A0189BB940 00007FFBCE524BAA coreclr!CLRVectoredExceptionHandlerShim + 234 at E:\repos\runtime\src\coreclr\src\vm\excep.cpp:7937
000000A0189BB990 00007FFC56EE85CC ntdll!RtlpCallVectoredHandlers + 264 at minkernel\ntdll\vectxcpt.c:204
000000A0189BBA30 00007FFC56EBB576 ntdll!RtlDispatchException + 102 at minkernel\ntos\rtl\amd64\exdsptch.c:357
000000A0189BBC40 00007FFC56F104AE ntdll!KiUserExceptionDispatch + 46 at minkernel\ntos\rtl\amd64\trampoln.asm:751
000000A0189BC3C8 00007FFBCE53C5F0 coreclr!memcpy + 384 at d:\A01\_work\19\s\src\vctools\crt\vcruntime\src\string\amd64\memcpy.asm:300
000000A0189BC3D0 00007FFBC997BA4B System_Private_CoreLib!System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr) + 91 at /_/src/libraries/System.Private.CoreLib/src/System/Buffer.cs:509
000000A0189BC400                  [InlinedCallFrame: 000000a0189bc400] 
000000A0189BC400                  [InlinedCallFrame: 000000a0189bc400] 
000000A0189BC3D0 00007ffbc997ba36 System.Private.CoreLib.dll!System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr) + 70
000000A0189BC4C0 00007ffbc997b972 System.Private.CoreLib.dll!System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr) + 306
000000A0189BC4F0 00007ffbc999fa03 System.Private.CoreLib.dll!System.String.Ctor(System.ReadOnlySpan`1) + 67
000000A0189BC530 00007ffbc9c38cd9 System.Private.CoreLib.dll!System.Span`1[[System.Char, System.Private.CoreLib]].ToString() + 41
000000A0189BC570 00007FFBCE539333 coreclr!CallDescrWorkerInternal + 131 at E:\repos\runtime\src\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm:100
000000A0189BC5B0 00007FFBCE41D9FA coreclr!MethodDescCallSite::CallTargetWorker + 978 at E:\repos\runtime\src\coreclr\src\vm\callhelpers.cpp:552
000000A0189BC740 00007FFBCE773678 coreclr!FuncEvalWrapper + 52 at E:\repos\runtime\src\coreclr\src\debug\ee\funceval.cpp:3073
000000A0189BC7A0 00007FFBCE772EA0 coreclr!DoNormalFuncEval + 1164 at E:\repos\runtime\src\coreclr\src\debug\ee\funceval.cpp:3448
000000A0189BCAD0 00007FFBCE773B88 coreclr!GCProtectArgsAndDoNormalFuncEval + 796 at E:\repos\runtime\src\coreclr\src\debug\ee\funceval.cpp:3587
000000A0189BCBB0                  [ProtectValueClassFrame: 000000a0189bcbb0] 
000000A0189BCCA0 00007FFBCE773486 coreclr!FuncEvalHijackRealWorker + 1062 at E:\repos\runtime\src\coreclr\src\debug\ee\funceval.cpp:3805
000000A0189BCDE0 00007FFBCE775755 coreclr!FuncEvalHijackWorker + 389 at E:\repos\runtime\src\coreclr\src\debug\ee\funceval.cpp:3928
000000A0189BCE28                  [FuncEvalFrame: 000000a0189bce28] 
000000A0189BCED0 00007FFBCE76968F coreclr!Debugger::ProcessAnyPendingEvals + 127 at E:\repos\runtime\src\coreclr\src\debug\ee\debugger.cpp:7934
000000A0189BCF10 00007FFBCE76B2D0 coreclr!Debugger::SendException + 496 at E:\repos\runtime\src\coreclr\src\debug\ee\debugger.cpp:7876
000000A0189BCFA0 00007FFBCE765DB3 coreclr!Debugger::LastChanceManagedException + 691 at E:\repos\runtime\src\coreclr\src\debug\ee\debugger.cpp:8774
000000A0189BD0D0 00007FFBCE604DE5 coreclr!NotifyDebuggerLastChance + 109 at E:\repos\runtime\src\coreclr\src\vm\excep.cpp:3604
000000A0189BD190 00007FFBCE6088A6 coreclr!WatsonLastChance + 758 at E:\repos\runtime\src\coreclr\src\vm\excep.cpp:3995
000000A0189BD210 00007FFBCE603DBC coreclr!InternalUnhandledExceptionFilter_Worker + 844 at E:\repos\runtime\src\coreclr\src\vm\excep.cpp:4836
000000A0189BD330 00007FFBCE76FC5B coreclr!Debugger::UnhandledHijackWorker + 607 at E:\repos\runtime\src\coreclr\src\debug\ee\debugger.cpp:13658
000000A0189BD910 00007FFBCE771505 coreclr!ExceptionHijackWorker + 197 at E:\repos\runtime\src\coreclr\src\debug\ee\debugger.cpp:13428
000000A0189BD940 00007FFBCE53A9C0 coreclr!ExceptionHijack + 48 at E:\repos\runtime\src\coreclr\src\debug\ee\amd64\dbghelpers.asm:89
000000A0189BD968 000000A0189BD980 
000000A0189BD970 000000A0189BDE70 
000000A0189BD978 0000000000000001 
000000A0189BE378                  [HelperMethodFrame: 000000a0189be378] 
000000A0189BE470 00007ffbc9a81e11 System.Private.CoreLib.dll!System.Globalization.TimeSpanFormat.FormatCustomized(System.TimeSpan, System.ReadOnlySpan`1, System.Globalization.DateTimeFormatInfo, System.Text.StringBuilder) + 1697
```
We are performing a func eval on `System.Span`1.ToString()` which is not yet Jitted.
