### ISSUE TITLE
`JsonSerializer.Deserialize<JsonElement>` fails for some values (e.g. bool, string)

### ISSUE THREAD

**Issue by dharmaturtle** [dotnet/runtime#48282]
From page 13 of [the JSON spec](https://tools.ietf.org/html/rfc8259):

>   Here are three small JSON texts containing only values:
   "Hello world!"
   42
   true

I believe these values should be valid `System.Text.Json.JsonElement`s, but the following fails:

```csharp
JsonSerializer.Deserialize<JsonElement>("hello world!");
```

Stacktrace:

> System.Text.Json.JsonReaderException: 'h' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)

Ref: https://github.com/dotnet/runtime/issues/1573

#### Configuration

* Dotnet SDK v5.0.103
* Windows 10 x64

**Comment by mburbea** [comment]
The issue is you have an invalid json value. To get it to deserialize the text you need to change it to the following::
```cs
JsonSerializer.Deserialize<JsonElement>("\"hello world!\"");
```
With double quotes, otherwise it's not valid json.

**Comment by dharmaturtle** [comment]
Well I feel silly. Thank you @mburbea :)
