### ISSUE TITLE
SIGSEGV at coreclr tracing 

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#48368]
### Description
Coreclr got a SIGSEGV during tracing crossgen2 via `dotnet-trace.dll`:
```
~/dotnet/x64_release_runtime$ ./corerun ../diagnostics/artifacts/bin/DotnetTrace.UnitTests/Release/net5.0/dotnet-trace.dll  collect -- ./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll  ./crossgen2/crossgen2.dll --out ./crossgen2/crossgen2.ni.dll
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: ./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll ./crossgen2/crossgen2.dll --out ./crossgen2/crossgen2.ni.dll 
Process        : /home/tmustafin/dotnet/x64_release_runtime/corerun
Output File    : /home/tmustafin/dotnet/x64_release_runtime/trace.nettrace

[00:00:00:00]   Recording trace 151.50   (KB)
Press <Enter> or <Ctrl+C> to exit...

Trace completed.
Process exited with code '139'.
```

Also it fails to trace via enabling environment variables:
```
~/dotnet/x64_release_runtime$ COMPlus_EnableEventPipe=1 COMPlus_EventPipeConfig="" COMPlus_EventPipeOutputPath=`pwd`/trace.nettrace COMPlus_EventPipeRundown=0 ./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll  ./crossgen2/crossgen2.dll --out ./crossgen2/crossgen2.ni.dll
Segmentation fault (core dumped)
```

### Configuration

It reproduces both on x64 ubuntu 18.04 and armel tizen 6.0.0. 
Runtime state 83143a4a882590101a5b986e333390c94df1bd1f.
Diagnostics state d7663b388b16f8f64c08f9700ba09fa230c57235.

### Regression?

That SIGSEGV behaviour starts at ba3681375cb978c5539815bc6b319b49899025e1.

### Other information

Gdb with `set follow-fork-mode child` on `dotnet-trace.dll` option crashes:
```
[New Thread 0x7fff4c9f5700 (LWP 14435)]
No profile or providers specified, defaulting to trace profile 'cpu-sampling'

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

[New Thread 0x7fff3ffff700 (LWP 14436)]
Launching: ./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll ./crossgen2/crossgen2.dll --out ./crossgen2/crossgen2.ni.dll 
[New process 14437]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/build/gdb-kAlH5B/gdb-8.1/gdb/nat/x86-linux-dregs.c:146: internal-error: void x86_linux_update_debug_registers(lwp_info*): Assertion `lwp_is_stopped (lwp)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
```

Gdb on environment variables option says ThreadPool thread jumps into strange address `0xffffffffffff0002`:
```
Thread 13 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff3ea9b700 (LWP 14580)]
0xffffffffffff0002 in ?? ()
(gdb) bt
#0  0xffffffffffff0002 in ?? ()
#1  0x00007fff7cd47473 in ?? ()
#2  0x0000000000000000 in ?? ()
(gdb)
```

@jkotas @sywhang @alpencolt @gbalykov

**Comment by sywhang** [comment]
Thanks for reporting this - https://github.com/dotnet/runtime/issues/48368 should fix this.

**Comment by t-mustafin** [comment]
Thanks for fast fix, it works for me.
