### ISSUE TITLE
S.S.C.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore failing locally

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#48406]
The test `BuildChainCustomTrustStore` is failing locally for me, all theories.

```
Failed System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(chainBuildsSuccessfully: True, chainFlags: NoError, testArguments: TrustedIntermediateTrustedRoot) [< 1 ms]
  Error Message:
   System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
  Stack Trace:
     at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index) in /code/personal/dotnet/runtime/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509ChainElementCollection.cs:line 46
   at System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(Boolean chainBuildsSuccessfully, X509ChainStatusFlags chainFlags, BuildChainCustomTrustStoreTestArguments testArguments) in /code/personal/dotnet/runtime/src/libraries/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 290
```

```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /code/personal/dotnet/runtime/.dotnet/sdk/5.0.100/
```

```
apt-cache policy ca-certificates      
ca-certificates:
  Installed: 20210119~20.04.1
  Candidate: 20210119~20.04.1
```

Most recently seen at 9195df699fe25d2e752c2bc350c16dc199f02f7a.

--------

I suspect this is occurring because the certificate under test is part of VeriSign whose roots are in-flux in various Linux distributions.

**Comment by vcsjones** [comment]
@bartonjs I think this can be closed again.

**Comment by bartonjs** [comment]
> I think this was re-opened for backporting, but seems to have happened [already].

Weird.

> I think this can be closed again.

Sounds good :smile:.
