### ISSUE TITLE
crossgen2 fails after generating ILCompiler.ReadyToRun.ni.dll on armel with --inputbubble

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#48466]
### Description

On armel crossgen2 produces a wrong ni files for `ILCompiler.ReadyToRun.dll` and `ILCompiler.TypeSystem.ReadyToRun.dll`. It leads to any following compilations crash:
```
[tm1 2.0.0]# ./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll  ./crossgen2/ILCompiler.ReadyToRun.dll --out ./crossgen2/ILCompiler.ReadyToRun.ni.dll --inputbubble
Emitting R2R PE file: ./crossgen2/ILCompiler.ReadyToRun.ni.dll
[tm1 2.0.0]# ./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll  /root/hello/hello.dll --out /root/hello/hello.ni.dll 
Error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILCompiler.CompilerTypeSystemContext.OpenPEFile(String filePath, MemoryMappedViewAccessor& mappedViewAccessor) in /home/runtime/src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 165
   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding) in /home/runtime/src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 192
   at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding) in /home/runtime/src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.cs:line 145
   at ILCompiler.Program.Run(String[] args) in /home/runtime/src/coreclr/tools/aot/crossgen2/Program.cs:line 369
   at ILCompiler.Program.Main(String[] args) in /home/runtime/src/coreclr/tools/aot/crossgen2/Program.cs:line 785
```

### Configuration

Runtime state: bc544bd171674762d8ba8694f55df15465d6e3b0 Release build
Os: tizen 6.0.0
Architecture: armel

cc @jkotas @davidwrighton @alpencolt @gbalykov

**Comment by t-mustafin** [comment]
Assert in debug mode:
```
./corerun ./crossgen2/crossgen2.dll -r:./*.dll -r:./crossgen2/*.dll  ./crossgen2/ILCompiler.TypeSystem.ReadyToRun.dll --out ./crossgen2/ILCompiler.TypeSystem.ReadyToRun.ni.__dll --inputbubble --compilebubblegenerics

Assert failure(PID 23883 [0x00005d4b], Thread: 24492 [0x5fac]): decoderNew.ReadToken() == decoderExisting.ReadToken()
    File: /home/runtime/src/coreclr/vm/frames.cpp Line: 2084
    Image: /opt/usr/dotnet/shared/Microsoft.NETCore.App/2.0.0/corerun

Aborted (core dumped)
```

**Comment by janvorli** [comment]
cc: @dotnet/crossgen-contrib

**Comment by mangod9** [comment]
assume this can be moved to .net 7 as well similar to #55663 ?

**Comment by davidwrighton** [comment]
Yes. While its reasonable to give advice to the team working on armel, we aren't in a position to debug armel bugs, and while we would likely take a fix if identified by a third party, we don't need to track these issues as part of our upcoming ship milestones.

**Comment by davidwrighton** [comment]
I assume this is no longer an issue for those using armel.
