### ISSUE TITLE
Test failure : tracing\\eventpipe\\eventsvalidation\\ThreadPool\\ThreadPool.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#48543]
Run: [runtime-coreclr outerloop 20210219.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1003170&view=ms.vss-test-web.build-test-results-tab&runId=31347124&resultId=110636&paneView=debug)

Failed test:
```
R2R windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
 -tracing\\eventpipe\\eventsvalidation\\ThreadPool\\ThreadPool.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\B98009DE\w\A656088B\e\tracing\eventpipe\Reports\tracing.eventpipe\eventsvalidation\ThreadPool\ThreadPool.output.txt
Raw output:
BEGIN EXECUTION
 1 file(s) copied.
" "C:\h\w\B98009DE\p\crossgen.exe" /Platform_Assemblies_Paths C:\h\w\B98009DE\p;C:\h\w\B98009DE\w\A656088B\e\tracing\eventpipe\eventsvalidation\ThreadPool /in C:\h\w\B98009DE\w\A656088B\e\tracing\eventpipe\eventsvalidation\ThreadPool\ThreadPool.org /out C:\h\w\B98009DE\w\A656088B\e\tracing\eventpipe\eventsvalidation\ThreadPool\\ThreadPool.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation. All rights reserved.

Native image C:\h\w\B98009DE\w\A656088B\e\tracing\eventpipe\eventsvalidation\ThreadPool\\ThreadPool.dll generated successfully.
 "C:\h\w\B98009DE\p\corerun.exe" ThreadPool.dll 
 0.0s: ==TEST STARTING==
 0.5s: Started sending sentinel events...
 0.5s: Connecting to EventPipe...
 1.0s: Connected to EventPipe with sessionID '0x2aa4b6dbd80'
 1.0s: Creating EventPipeEventSource...
 1.1s: EventPipeEventSource created
 1.2s: Dynamic.All callback registered
 1.2s: Running optional trace validator
 1.3s: Finished running optional trace validator
 1.3s: Starting stream processing...
 2.1s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
 2.1s: Saw sentinel event
 2.1s: Saw new provider 'Microsoft-DotNETCore-SampleProfiler'
 2.1s: Stopped sending sentinel events
 2.2s: Starting event generating action...
 2.2s: Stopping event generating action
 2.3s: Sending StopTracing command...
 2.7s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
 2.8s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
 2.8s: Finished StopTracing command
 2.8s: Stopping stream processing
 2.8s: Dropped 0 events
 2.8s: Reader task finished
 2.8s: Validating optional callback...
 2.8s: Event counts validation
 2.8s: ==TEST FINISHED: FAILED!==
Expected: 100
Actual: -1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B98009DE\p
> C:\h\w\B98009DE\w\A656088B\e\tracing\eventpipe\eventsvalidation\ThreadPool\ThreadPool.cmd
Expected: True
Actual: False

Stack trace
   at tracing_eventpipe._eventsvalidation_ThreadPool_ThreadPool_._eventsvalidation_ThreadPool_ThreadPool_cmd()

```

**Comment by VincentBu** [comment]
Failed in run [runtime-coreclr jitstress-isas-arm 20210220.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1004632&view=ms.vss-test-web.build-test-results-tab&runId=31374282&resultId=111019&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 -tracing/eventpipe/eventsvalidation/ThreadPool/ThreadPool.sh
```

**Error message:**
```
Return code: 1
Raw output file: /root/helix/work/workitem/tracing/eventpipe/Reports/tracing.eventpipe/eventsvalidation/ThreadPool/ThreadPool.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ThreadPool.dll ''
 0.0s: ==TEST STARTING==
 2.5s: Started sending sentinel events...
 2.6s: Connecting to EventPipe...
 3.7s: Connected to EventPipe with sessionID '0x7f10009390'
 3.7s: Creating EventPipeEventSource...
 4.0s: EventPipeEventSource created
 4.1s: Dynamic.All callback registered
 4.1s: Running optional trace validator
 5.1s: Finished running optional trace validator
 5.1s: Starting stream processing...
 5.6s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
 5.6s: Saw new provider 'Microsoft-DotNETCore-SampleProfiler'
 5.7s: Saw sentinel event
 5.7s: Stopped sending sentinel events
 5.7s: Starting event generating action...
 5.7s: Stopping event generating action
 5.8s: Sending StopTracing command...
 6.0s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
 6.1s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
 6.1s: Stopping stream processing
 6.1s: Dropped 0 events
 6.1s: Finished StopTracing command
 6.1s: Reader task finished
 6.1s: Validating optional callback...
 6.1s: Event counts validation
 6.1s: ==TEST FINISHED: FAILED!==
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/tracing/eventpipe/eventsvalidation/ThreadPool/ThreadPool.sh
Expected: True
Actual: False

Stack trace
   at tracing_eventpipe._eventsvalidation_ThreadPool_ThreadPool_._eventsvalidation_ThreadPool_ThreadPool_sh()

```
