### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.TcpClientTest.ConnectAsync_DnsEndPoint_Success(mode: 4)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#48546]
Run: [runtime-libraries-coreclr outerloop 20210219.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1002777&view=ms.vss-test-web.build-test-results-tab&runId=31332926&resultId=103029&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200601195603-e06dc59
 -System.Net.Sockets.Tests.TcpClientTest.ConnectAsync_DnsEndPoint_Success(mode: 4)
```

**Error message:**
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Resource temporarily unavailable


Stack trace
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 419
   at System.Net.Dns.GetHostAddressesCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 388
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 583
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 513
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 303
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2363
--- End of stack trace from previous location ---
   at System.Net.Sockets.Tests.TcpClientTest.ConnectAsync_DnsEndPoint_Success(Int32 mode) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs:line 157
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Triage: We think this is environmental - DNS not available, closing.
