### ISSUE TITLE
The .NET 5 return Platform Not Supported if you try to use .NET 5 as a Windows Service application.

### ISSUE THREAD

**Issue by MycroBeat** [dotnet/runtime#48620]
Hello. Recently, i wanted to upgrade my websites from .net core 3.1 to .net 5, but i notice the visual studio return an warning (CA1416) on the host.RunAsService().

### Describe the bug
The .NET 5 return Platform Not Supported if you try to use .NET 5 as a Windows Service application. Even if the `OperatingSystem.IsWindows` return true, the application return errors when i try to start on services.msc.
This does not happen in .net core 3.1.

### To Reproduce
Windows Services via `IHostBuilder`
1. Create a normal .net 5 project.
2. Add this refences to allow Windows Services: 

- Microsoft.AspNetCore.Hosting.WindowsServices
- Microsoft.AspNetCore
- Microsoft.Extensions.Hosting.WindowsServices

3. On `Host.CreateDefaultBuilder` add .UseWindowsService()

4. Main Program looks like this
```
public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .UseWindowsService()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
        }
```

5. Create service on cmd via `sc create`

Windows Services via `IWebHostBuilder`

The process is identical up to point 2, inclusive.

3. Use this code via WebHost to create Windows Service Run.
```
public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().RunAsService();
       }
public static IWebHostBuilder CreateWebHostBuilder(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, config) =>
                {
                })
                .UseStartup<Startup>();
        }
```

4. Create service on cmd via `sc create`

The application will return `Exception Info: System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.`

### Further technical details
Visual Studio 16.8.5
```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.111 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by eerhardt** [comment]
@MycroBeat - this is working fine for me locally. Do you have a repro project and exact steps to run to reproduce?

One thing to note is that if you are copying the application around, you need to ensure you copy the `runtimes` folder with the application. `System.ServiceProcess.ServiceController.dll` is a bit special in that there is a Windows-specific build, which works. And a "default" build which throws PNSE. You want to ensure you are loading and running the Windows-specific version of the assembly that gets placed here:

![image](https://user-images.githubusercontent.com/8291187/108881749-43b8e880-75c9-11eb-897d-d2e763dadb3b.png)

You can try debugging your application by putting `System.Diagnostics.Debugger.Launch();` as the first line in `Main`, and then starting the app under Windows Services. This will prompt you to attach a debugger. Then you can continue the app, and look in the "Modules" window of Visual Studio to see which path/version of that assembly is getting loaded.

**Comment by MycroBeat** [comment]
The repo is a normal .NET 5 Template, without any modification. I just create template on Visual Studio, then I took the steps exactly as I said in my original post. Then i publish the application with the following configuration:

Target location: `bin\Release\net5.0\publish\`
Delete existing files: `False`
Configuration: `Relase`
Target Framework: `net5.0`
Target runtime: `Portable`

Now I found where the error is, although it is a strange error.

- If i publish with Target Runtime selected on `Portable` and i have ` .UseWindowsService()` or `RunAsService()`, the publish create a `runtimes` folder and throw the error if i'm using Windows Service method.
- If i publish with Target selected on `Win-x64`, the `runtimes` folder is not created and the application run normally.

**Comment by eerhardt** [comment]
Publishing `Portable` works for me as well:

![image](https://user-images.githubusercontent.com/8291187/108889585-2ccac400-75d2-11eb-982e-2482d5f48afe.png)

Can you .zip up your publish folder and post it on this issue? That might help me spot the issue. It may be a `.deps.json` issue.

**Comment by MycroBeat** [comment]
Yes. Very weird.. Now I published first as `Portable` and then i republish (i don't know if visual studio delete all .dll files) with `Win-x64` and after i published using `Win-x64` over „Portable„ throw the error again.

[Link](https://wetransfer.com/downloads/a9923bc7702e0a36cbe1e9c1fa9d7e6420210223184454/b3cf0f10b725f9b84f5d011397e476de20210223184516/eb2d15)

**Comment by eerhardt** [comment]
Thanks for the .zip of your publish directory. It definitely makes it easier to understand what is happening.

Using your instructions, I now understand the difference and am able to reproduce the problem myself.

Using .csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="5.0.0" />
  </ItemGroup>
</Project>
```

and Program.cs:

```C#
using System;
using System.ServiceProcess;

namespace Repro48620
{
    class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine(new Service());
        }

        class Service : ServiceBase
        {
        }
    }
}
```

1. "Folder" Publish with the default settings:

![image](https://user-images.githubusercontent.com/8291187/109028217-32ceac80-7687-11eb-8df2-0afb397223fc.png)

2. Now change "Target runtime" to `win-x64`, leave 'Framework-dependent` the same, and publish again

![image](https://user-images.githubusercontent.com/8291187/109028306-47ab4000-7687-11eb-99e4-10cb3df6f328.png)

3. Run the published app, and you get:

```
Unhandled exception. System.PlatformNotSupportedException: ServiceController enables manipulating and accessing Windows services and it is not applicable for other operating systems.
   at System.ServiceProcess.ServiceBase..ctor()
   at Repro48620.Program.Service..ctor()
   at Repro48620.Program.Main(String[] args) in C:\Users\eerhardt\source\repos\Repro48620\Repro48620\Program.cs:line 10
```

Notice that if you delete the `bin` and `obj` folders and just publish directly for `win-x64`, and run the published app, it works just fine. So for now, my suggestion is to ensure your publish directory is cleaned before publishing. That will help you avoid the problem.

The issue is that the first "portable" `Publish` is laying down the PSNE version of `System.ServiceProcess.ServiceController.dll` directly in the `publish` directory, which is correct because this is a "portable" app. The windows-specific version is going into `runtimes\win\lib\netstandard2.0`, where it is getting picked up correctly at runtime.

However, the 2nd `framework-dependent / win-x64` publish is not overwriting the PSNE version of the file. But it should be, because this is no longer a "portable" publish. It is windows specific. So the windows specific assembly should be going directly to the `publish` folder, and not into a `runtimes\...` folder. I'm not exactly sure why publish isn't working correctly.

Since this is a "publish" bug, and not a runtime bug, I'm moving it to `dotnet/sdk`.

cc @dsplaisted
