### ISSUE TITLE
CreateDefaultBuilder_SecretsDoesReload test failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#48696]
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48684-merge-1dda5503a115420687/Microsoft.Extensions.Hosting.Unit.Tests/console.b5b90d65.log?sv=2019-07-07&se=2021-03-16T05%3A35%3A14Z&sr=c&sp=rl&sig=ytXzgYX%2F6x0X9rBYl8sm%2B1JpNoEfEPjQFQhlMtH69tU%3D
```
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 99 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 2)
[40m[32minfo[39m[22m[49m: Microsoft.Extensions.Hosting.Tests.HostTests[0]
      Request starting
    Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload [FAIL]
      Assert.Equal() Failure
                                    â†“ (pos 20)
      Expected: Hello ASP.NET Core: f577b280d3814d6c935970a1aadbb8e6
      Actual:   Hello ASP.NET Core: 407a83ef08c04e1ca1e07690cb30dc0a
                                    â†‘ (pos 20)
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs(264,0): at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload()
        --- End of stack trace from previous location ---
  Finished:    Microsoft.Extensions.Hosting.Unit.Tests
```

**Comment by eerhardt** [comment]
Looking at the test log, it looks like that test took 1 minute to run:

![image](https://user-images.githubusercontent.com/8291187/109018522-d0bd7980-767d-11eb-9f9e-b719c47b393b.png)

Looking at the test, it looks like it is waiting for 1 minute:

https://github.com/dotnet/runtime/blob/5a3d44e40b69619193c8cd6b0742858febd20ff5/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs#L211-L218

So this leads me to believe that the change callback was never invoked, which is why we are getting stale data in the config.

**Comment by stephentoub** [comment]
Failed again here:
https://dev.azure.com/dnceng/public/_build/results?buildId=1061100&view=ms.vss-test-web.build-test-results-tab&runId=32699320&paneView=attachments&resultId=181769
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50357-merge-ede7a005545e42cf8b/Microsoft.Extensions.Hosting.Unit.Tests/console.39af16ec.log?sv=2019-07-07&se=2021-04-18T11%3A42%3A53Z&sr=c&sp=rl&sig=k%2BL7uF4zgHywaVYUegb2Pi%2F%2F7AIejrTog53v%2FftznF0%3D
```
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 100 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 2)
    Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload [FAIL]
      Assert.Equal() Failure
                                    â†“ (pos 20)
      Expected: Hello ASP.NET Core: 1466b2f4da5249bdaef71d3aeee50e47
      Actual:   Hello ASP.NET Core: 8ab58f24c0c34494a4a4969709dc8a26
                                    â†‘ (pos 20)
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs(264,0): at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload()
        --- End of stack trace from previous location ---
[40m[32minfo[39m[22m[49m: Microsoft.Extensions.Hosting.Tests.HostTests[0]
      Request starting
  Finished:    Microsoft.Extensions.Hosting.Unit.Tests
```

**Comment by maryamariyan** [comment]
The test was added in https://github.com/dotnet/runtime/pull/43807

**Comment by maryamariyan** [comment]
Removed blocking-clean-ci as the ActiveIssue attribute is now added to the test. 

Keeping issue open to track re-enabling it properly

**Comment by ViktorHofer** [comment]
Happened again in https://dev.azure.com/dnceng/public/_build/results?buildId=1109669&view=ms.vss-test-web.build-test-results-tab&runId=33849264&resultId=182792&paneView=debug

```
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 108 of 109 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 2)
    Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload [FAIL]
      Assert.Equal() Failure
                                    â†“ (pos 20)
      Expected: Hello ASP.NET Core: fd88495f2f6f4395a50b8a8bb9002821
      Actual:   Hello ASP.NET Core: 96d471cc9668492aa1d5528c5d782693
                                    â†‘ (pos 20)
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs(315,0): at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload()
        --- End of stack trace from previous location ---
[40m[32minfo[39m[22m[49m: Microsoft.Extensions.Hosting.Tests.HostTests[0]
      Request starting
  Finished:    Microsoft.Extensions.Hosting.Unit.Tests
```

Configuration: `net6.0-Linux-Debug-x64-CoreCLR_release-Ubuntu.1604.Amd64.Open`

**Comment by ViktorHofer** [comment]
cc @IEvangelist

**Comment by bartonjs** [comment]
And again.  https://dev.azure.com/dnceng/public/_build/results?buildId=1179018&view=ms.vss-test-web.build-test-results-tab&runId=35916356&resultId=117977&paneView=debug

```
/datadisks/disk1/work/C7C50B48/w/B068098D/e /datadisks/disk1/work/C7C50B48/w/B068098D/e
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 109 of 110 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 2)
    Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload [FAIL]
      Assert.Equal() Failure
                                    â†“ (pos 20)
      Expected: Hello ASP.NET Core: d05cbd4bd6cf4e89b5e5a16267814a60
      Actual:   Hello ASP.NET Core: 5d71a4fa37c348828f14c431f252b45e
                                    â†‘ (pos 20)
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs(316,0): at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload()
        --- End of stack trace from previous location ---
[40m[32minfo[39m[22m[49m: Microsoft.Extensions.Hosting.Tests.HostTests[0]
      Request starting
  Finished:    Microsoft.Extensions.Hosting.Unit.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Extensions.Hosting.Unit.Tests  Total: 115, Errors: 0, Failed: 1, Skipped: 0, Time: 3.639s
```

**Comment by eerhardt** [comment]
Closing as this hasn't failed in over a year. Please re-open if this happens again.
