### ISSUE TITLE
Logging with EventLog in a HostedService running on different thread throws AggregateException during Host shutdown

### ISSUE THREAD

**Issue by Prologh** [dotnet/runtime#48756]
### Description

I'm writing a .NET Core Worker for consuming messages from Kafka. I've met an `AggregateException` while trying to log information when cancellation is requested by host shutdown. The behavior is the same when I just press `CTRL` + `C` in console. Since the original Kafka consuming method blocks the thread, I'm running the consuming loop in a new one. 

Not adding EventLog seems to be fixing the issue. I don't event need EventLog, it comes with logging by default.

What's weird to me though, is that logging done outside the `catch` blocks works just fine. See the finally block that is executed right after catching the first `OperationCanceledException` and there surprisingly no problems with logging occur.

I've based my hosted service on an example from Confluent, which I believe is fine:
https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/Web/RequestTimeConsumer.cs

I think this SO question might be related:
https://stackoverflow.com/questions/57296564/an-error-occurred-while-writing-to-loggers-from-system-diagnostics-eventlogint

### Configuration

* Which version of .NET is the code running on?
* .NET Core 3.1

### Regression?

I don't think so. I've seen the same happening in an app running on .NET Core 3.1 and .NET 5. No difference.

### Other information

Stack trace:

```
System.AggregateException: An error occurred while writing to logger(s). (Cannot access a disposed object.
      Object name: 'EventLogInternal'.)
       ---> System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'EventLogInternal'.
         at System.Diagnostics.EventLogInternal.OpenForWrite(String currentMachineName)
         at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
         at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
         at System.Diagnostics.EventLog.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
         at System.Diagnostics.EventLog.WriteEvent(EventInstance instance, Object[] values)
         at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
         at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
         at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
         --- End of inner exception stack trace ---
         at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
         at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
         at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
         at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)
         at Microsoft.Extensions.Logging.LoggerExtensions.LogWarning(ILogger logger, String message, Object[] args)
         at ConsumerHostedService.StartConsumerLoop(CancellationToken cancellationToken) in C:\Users\Piotr\Documents\Visual Studio 2019\Projects\ConsoleApp1\ConsoleApp1\Program.cs:line 62
```

Project file:

```XML
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
  </ItemGroup>

</Project>
```

Full snippet below, host will shut down automatically after few seconds, triggering the exception. Comment out `AddEventLog()` to see the difference.

```C#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System;
using System.Threading;
using System.Threading.Tasks;


public class Program
{
    public static async Task Main(string[] args)
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(3));
        await CreateHostBuilder(args).Build().RunAsync(cts.Token);
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.ClearProviders();
                logging.AddDebug();
                logging.AddConsole();
                logging.AddEventLog(); // <== Causing Disposed exceptions.
            })
            .ConfigureServices((hostContext, services) =>
            {
                services.AddHostedService<ConsumerHostedService>();
            });
}

public class ConsumerHostedService : BackgroundService
{
    public ConsumerHostedService(ILogger<ConsumerHostedService> logger)
    {
        Logger = logger;
    }

    private ILogger Logger { get; }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        new Thread(() => StartConsumerLoop(stoppingToken)).Start();

        return Task.CompletedTask;
    }

    private void StartConsumerLoop(CancellationToken cancellationToken)
    {
        try
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                try
                {
                    var value = Consume(TimeSpan.FromSeconds(1), cancellationToken);

                    Logger.LogInformation("Message successfully consumed. Value: {0}", value);
                }
                catch (OperationCanceledException)
                {
                    Logger.LogWarning("Consuming cancelled.");
                }
                finally
                {
                    Logger.LogInformation("Finally for consuming works anyway.");
                }
            }
        }
        catch (Exception ex)
        {
            Logger.LogError(ex, "Exception caught!");

            throw;
        }
        finally
        {
            Logger.LogInformation("Finally outside the loop works also.");
        }
    }

    private string Consume(TimeSpan delay, CancellationToken cancellationToken)
    {
        Task.Delay(delay, cancellationToken).GetAwaiter().GetResult();

        return "FOO";
    }
}
```

**Comment by pedrobsaila** [comment]
Hi @Prologh 

So here is how the example works :
* you start a new thread asynchronously without blocking/awaiting it
* You hit `return Task.CompletedTask;`
* The Background service has now ended because of the last step
* We kick the dispose Method of Host
* We dispose of the service container including the Event log logger
* 3 seconds elapses
* the cancellation token is cancelled and OperationCanceledException is thrown inside the new thread
* We try to `Logger.LogWarning("Consuming cancelled.");` but the event log logger inside service container is already disposed
* You got the exception

So your example works, you need to replace `new Thread(() => ).Start()` by `StartConsumerLoop(stoppingToken)`. I believe the issue is in the example, not the runtime. Hope my response is clear and useful

**Comment by Prologh** [comment]
Hi, 
Thanks for digging up this issue. I gave it a spin and yes it does not throw when starting the consumer loop without new thread. But one thing that still makes me wonder is why in original code example this finally block:

```C#
finally
{
    Logger.LogInformation("Finally outside the loop works also.");
}
```

still manages to log the message correctly, event though the service container is already disposed and the host is shutting down? It happens after the exception, but still logs the message. Shouldn't it fail with disposed exception, just like one attempt before? What am I missing here or getting wrong?

**Comment by pedrobsaila** [comment]
> But one thing that still makes me wonder is why in original code example this finally block:
> 
> ```cs
> finally
> {
>     Logger.LogInformation("Finally outside the loop works also.");
> }
> ```
> 
> still manages to log the message correctly, event though the service container is already disposed and the host is shutting down?

It is because the event log logger is configured to log only Warning/Error messages by default.
