### ISSUE TITLE
DNS tests are failing deterministically in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48751]
![image](https://user-images.githubusercontent.com/7412651/109138927-30d61d80-775b-11eb-9fc6-a1fb1029d099.png)

https://dev.azure.com/dnceng/public/_build/results?buildId=1011172&view=ms.vss-test-web.build-test-results-tab

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
 at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 404
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 385
   at System.Net.Dns.GetHostByName(String hostName) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 272
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 108
```

We probably need to disable the failing tests right now as apparently something changed in the dns detection which is causing these tests to fail deterministically in CI.

cc @dotnet/ncl

**Comment by wfurt** [comment]
Do you know if anything changed with infrastructure @MattGal ? From the logs it seems like the instance cannot resolve it's own name. I'll keep looking as it is not clear why this would happen only on particular distro.

**Comment by MattGal** [comment]
> Do you know if anything changed with infrastructure @MattGal ? From the logs it seems like the instance cannot resolve it's own name. I'll keep looking as it is not clear why this would happen only on particular distro.

Interesting;  I know of no intentional changes from this but Weds. is rollout days so if something changed, it would have been yesterday.  Taking a look.

**Comment by MattGal** [comment]
> > Do you know if anything changed with infrastructure @MattGal ? From the logs it seems like the instance cannot resolve it's own name. I'll keep looking as it is not clear why this would happen only on particular distro.
> 
> Interesting; I know of no intentional changes from this but Weds. is rollout days so if something changed, it would have been yesterday. Taking a look.

Ah. SLES 15.  Yes, we did update this one yesterday, because SUSE deleted the SLES 15 SP1 image from the gallery, forcing us onto SP2.  I'll check it out and see if there's anything we can do and report back.  Tracking issue: https://github.com/dotnet/core-eng/issues/12333

**Comment by wfurt** [comment]
thanks @MattGal. If needed, I can help with the investigation.

**Comment by wfurt** [comment]
cc @dnceng for visibility.

**Comment by MattGal** [comment]
@dotnet/dnceng also

**Comment by MattGal** [comment]
the problem comes from including git-core, I am looking at working around it.

**Comment by VincentBu** [comment]
Failed again in [runtime 20210225.61](https://dev.azure.com/dnceng/public/_build/results?buildId=1012154&view=ms.vss-test-web.build-test-results-tab&runId=31540272&resultId=147298&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open

 -System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName
```

**Error message:**
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known


Stack trace
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 404
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 385
   at System.Net.Dns.GetHostByName(String hostName) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 272
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 108
```

**Comment by MattGal** [comment]
@VincentBu yes, while I have a lead on what caused this, the earliest this will be fixed on the machines is next Weds.  I was under the impression from @wfurt this test was disabled on that platform for the time being?

**Comment by ViktorHofer** [comment]
Yes, the tests are already disabled.

**Comment by karelz** [comment]
@MattGal @ViktorHofer did the DNS get fixed in CI? Should we re-enable the tests?

**Comment by MattGal** [comment]
> @MattGal @ViktorHofer did the DNS get fixed in CI? Should we re-enable the tests?

It's hard to be certain since the tests are off, but in retrospect we were definitely having global issues with DNS in Azure machines that has subsided (down to a single domain that may have problems from creating hosts fast?).  

I'd say it's worth a try, since various things have changed since Mar. 3. I'll take a stab when I finish my inbox but the tricky part is with your test disabled I don't have a simple repro path.

**Comment by MattGal** [comment]
@karelz sorry for the delay.  The workaround I made for the strange symptom from before (inability to resolve the local host) is still holding, so  yes you should reenable these tests on SLES 15.
