### ISSUE TITLE
Apple Silicon threadstart/GThread* jitstress1 fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#48791]
In a single jitstress1 run two threadstart tests failed.
```
baseservices/threading/generics/threadstart/GThread22/GThread22.sh
baseservices/threading/generics/threadstart/GThread24/GThread24.sh
```

```
    baseservices/threading/generics/threadstart/GThread22/GThread22.sh [FAIL]
      Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception.Unhandled exception.  Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
      System.NullReferenceException: Object reference not set to an instance of an object.
         at GenString.Target[U]()
         at System.Threading.Thread.StartCallback()
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1011906&view=ms.vss-test-web.build-test-results-tab

**Comment by JulieLeeMSFT** [comment]
CC @sandreenko if this is CodeGen issue or if we need to assign it to @mangod9's team since it is related to Threading.

**Comment by sandreenko** [comment]
With JitStress failures we usually start with codegen label, I will look at it and change the label if it is not Jit.

**Comment by sandreenko** [comment]
I have ran both tests 10000 times with JitStress=1 and did not see any failures, it looks like it was a spurious GC hole that was not related to JitStress1.
I have not seen it in CI runs as well.
Feel free to reopen if you encounter it again.

**Comment by sdmaclea** [comment]
```xml
src/tests/issues.targets:            <Issue>https://github.com/dotnet/runtime/issues/48791</Issue>
```

Test needs to be reenabled.

**Comment by sandreenko** [comment]
@sdmaclea could you please link the issues into the PRs that disable the tests so it is easier to see if the test was disabled and how.

For stress issue we prefer to disable the tests in the test project files, using the following syntaxis:
```
    <!-- https://github.com/dotnet/runtime/issues/issueNumber-->
    <JitOptimizationSensitive Condition="'$(TargetArchitecture)' == 'arm64 or the problematic arch'">true</JitOptimizationSensitive>
```
example https://github.com/dotnet/runtime/blob/main/src/tests/Interop/PInvoke/Vector2_3_4/Vector2_3_4.csproj

so the test keeps running without stress modes.
