### ISSUE TITLE
.NET 6 preview 1 singlefile on Mac unable to find libSystem.Security.Cryptography.Native.Apple.dylib

### ISSUE THREAD

**Issue by Meowzz95** [dotnet/runtime#48801]
### Description

* `dotnet publish -c Release --self-contained --runtime osx-x64 -p:PublishSingleFile=true -p:DebugType=None`

* Run built binary
* Exception is thrown

> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.Apple.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.Security.Cryptography.Native.Apple.dylib, 1): image not found

It works if I copy the file `liblibSystem.Security.Cryptography.Native.Apple.dylib` from .NET 5 built output to the folder where the .NET 6 binary is loacted.
### Configuration

.NET version: 
6.0.100-preview.1.21103.13
macOS version: 11.2.1
mac arch: Intel

### Other information

If repro code is needed, I can provide it upon request.

**Comment by Meowzz95** [comment]
I don't think the bot labelled it correctly, it should be area-Single-File?

**Comment by jkotas** [comment]
cc @VSadov

**Comment by Meowzz95** [comment]
Here is the repro

https://github.com/Meowzz95/DotNet6DemoMissingLib

**Comment by hoffmann-jan** [comment]
@Meowzz95 
How can I get the missing lib into the self-contained output?
Can I use copy into output?
Thanks!

**Comment by VSadov** [comment]
`System.Security.Cryptography.Native.Apple` should be statically linked into the app binary. 
It is unexpected that it needs the .dylib 

I do not know yet why this could happened, but it looks like a bug.

**Comment by Meowzz95** [comment]
@hoffmann-jan 
For a temp workaround, you can copy the missing lib from the build output of a .NET5 single-file application. I think you can get it simply by creating a .NET5 console app and run publish single-file.

**Comment by VSadov** [comment]
Thanks for reporting this issue!! 

The lib is included in the singlefile binary, but right now is not used because of a bug.
It should be fixed in #49401 and correct behavior should appear in the next preview.

One possible temporary workaround is to copy `libSystem.Security.Cryptography.Native.Apple.dylib` from `bin\Release\net6.0\osx-x64` (i.e above the publish directory) to the location of the singlefile binary.

**Comment by Meowzz95** [comment]
@VSadov 
Hi, just upgraded to preview 2, the same(well same root cause) error persists.

I've upgraded the repro repo here: https://github.com/Meowzz95/DotNet6DemoMissingLib

Command to build: ` dotnet publish -c Release --self-contained --runtime osx-x64 -p:PublishSingleFile=true`
.NET SDK version: `Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET`
macOS version: 11.2.3 (20D91) (Intel CPU)

Attached the stack trace.
```
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.Apple.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.Security.Cryptography.Native.Apple.dylib, 1): image not found
         at Interop.AppleCrypto.SslCreateContext(Int32 isServer)
         at System.Net.SafeDeleteSslContext.CreateSslContext(SafeFreeSslCredentials credential, Boolean isServer)
         at System.Net.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at DemoMissingLib.Worker.ExecuteAsync(CancellationToken stoppingToken)
         at Microsoft.Extensions.Hosting.Internal.Host.HandleBackgroundException(BackgroundService backgroundService)
```

**Comment by VSadov** [comment]
Sorry for the confusion. Preview 2 was released on the same day this fix was merged. When I said "in the next preview", I meant preview3.

The fix could not possibly make it into preview2 since a preview branch is created many days before the release - to have time for extra validation and stabilization. The fix should be in the Preview3 though.
