### ISSUE TITLE
DisableAiaOptionWorks test failing on Mono Win81

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#49014]
https://dev.azure.com/dnceng/public/_build/results?buildId=1018830&view=ms.vss-test-web.build-test-results-tab&runId=31715448&resultId=158099&paneView=debug

Configuration: `net6.0-windows-Debug-x64-Mono_release-Windows.81.Amd64.Open`

```
System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks

Chain build with no intermediate, AIA enabled\r\nExpected: True\r\nActual:   False
 at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/AiaTests.cs:line 126
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
```

**Comment by danmoseley** [comment]
Also failed on net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open and broke a PR validation:
```
Console log: 'System.Security.Cryptography.X509Certificates.Tests' from job 77f09329-8856-43af-8900-2ddccac4b53a workitem acfa9fe1-d9d7-4e4f-89a1-f24d5b1e0e47 (osx.1015.amd64.open) executed on machine dci-mac-build-137
+ ./RunTests.sh --runtime-path /tmp/helix/working/9F8D094D/p
----- start Fri Apr 30 15:00:15 PDT 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/9F8D094D/p/dotnet exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/9F8D094D/w/C66C0A40/e /private/tmp/helix/working/9F8D094D/w/C66C0A40/e
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
Run 'security unlock-keychain' to make tests runable.
  Discovered:  System.Security.Cryptography.X509Certificates.Tests (found 592 of 682 test cases)
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 4)
    System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks [FAIL]
      Chain build with no intermediate, AIA enabled
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/AiaTests.cs(127,0): at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.DisableAiaOptionWorks()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Warning: unable to build chain to self-signed root for signer "(null)"
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

**Comment by vcsjones** [comment]
@danmoseley if you could kindly assign this one to me I will take a look at it soon. Getting it assigned will help me not forget about it 😄 .

**Comment by danmoseley** [comment]
Sure - done ! Thanks. I'll see if I can get you triage permissions so that you don't need to ask.

**Comment by danmoseley** [comment]
@vcsjones you should now have triage rights, feel free to close issues, relabel, and assign as seems appropriate ad consistent with what we normally do 🙂

**Comment by vcsjones** [comment]
> you should now have triage rights

Thank you!

**Comment by bartonjs** [comment]
Honestly these are probably network/timeout issues.  Sure, it's loopback, but that still has to go through some signalling mechanism, interrupts, and context switches.

Wrapping https://github.com/dotnet/runtime/blob/fe9a54df8f4b5e6a2e4cafc0e4234a64e8c9cf8e/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/AiaTests.cs#L129 in a "try a few times" would probably make these intermittencies go from one a week or so to almost never.

**Comment by vcsjones** [comment]
Agree, was going to do similar solution as we did for revocation:

https://github.com/dotnet/runtime/blob/fe9a54df8f4b5e6a2e4cafc0e4234a64e8c9cf8e/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/TimeoutTests.cs#L20

I see this is still on my plate. Next week I have lots of time to focus on these things.
