### ISSUE TITLE
[macOS-arm64] System.Text.Json.Tests failing with CoreCLR

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#49089]
From https://dev.azure.com/dnceng/public/_build/results?buildId=1019012
```
----- start Tue Mar 2 10:20:49 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/A43F08FC/p/dotnet exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/A43F08FC/w/9D520897/e /private/tmp/helix/working/A43F08FC/w/9D520897/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 25 of 2319 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 8)
    System.Text.Json.Serialization.Tests.ConstructorTests_Stream.MultipleThreadsLooping [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs(264,0): at System.Text.Json.Serialization.ReflectionEmitMemberAccessor.CreatePropertySetter[TProperty](PropertyInfo propertyInfo)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs(74,0): at System.Text.Json.JsonPropertyInfo`1.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, ClassType runtimeClassType, MemberInfo memberInfo, JsonConverter converter, Nullable`1 ignoreCondition, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(99,0): at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, MemberInfo memberInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options, Nullable`1 parentTypeNumberHandling, Nullable`1 ignoreCondition)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(75,0): at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(256,0): at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(151,0): at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(523,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(538,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs(101,0): at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(61,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.StreamDeserializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(39,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectMinimalAsync|13_1(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(85,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(20,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_String.MultipleThreadsLooping [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs(264,0): at System.Text.Json.Serialization.ReflectionEmitMemberAccessor.CreatePropertySetter[TProperty](PropertyInfo propertyInfo)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs(74,0): at System.Text.Json.JsonPropertyInfo`1.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, ClassType runtimeClassType, MemberInfo memberInfo, JsonConverter converter, Nullable`1 ignoreCondition, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(99,0): at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, MemberInfo memberInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options, Nullable`1 parentTypeNumberHandling, Nullable`1 ignoreCondition)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(75,0): at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(256,0): at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(151,0): at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(523,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(538,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(121,0): at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(33,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.StringDeserializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(39,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectMinimalAsync|13_1(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(85,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(20,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_Span.MultipleThreadsLooping [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs(264,0): at System.Text.Json.Serialization.ReflectionEmitMemberAccessor.CreatePropertySetter[TProperty](PropertyInfo propertyInfo)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs(74,0): at System.Text.Json.JsonPropertyInfo`1.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, ClassType runtimeClassType, MemberInfo memberInfo, JsonConverter converter, Nullable`1 ignoreCondition, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(99,0): at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, MemberInfo memberInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options, Nullable`1 parentTypeNumberHandling, Nullable`1 ignoreCondition)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(75,0): at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(256,0): at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(151,0): at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(523,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(538,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(162,0): at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(75,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.SpanDesearializationWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(39,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectMinimalAsync|13_1(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(85,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(20,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping()
        --- End of stack trace from previous location ---
./RunTests.sh: line 162: 41390 Bus error: 10           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing $RSP_FILE
/private/tmp/helix/working/A43F08FC/w/9D520897/e
----- end Tue Mar 2 10:20:56 PST 2021 ----- exit code 138 ----------------------------------------------------------
```
```
----- start Tue Mar 2 13:23:17 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/B4700970/p/dotnet exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/B4700970/w/B4DF09A2/e /private/tmp/helix/working/B4700970/w/B4DF09A2/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 25 of 2319 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 8)
./RunTests.sh: line 162: 64980 Bus error: 10           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing $RSP_FILE
/private/tmp/helix/working/B4700970/w/B4DF09A2/e
----- end Tue Mar 2 13:23:24 PST 2021 ----- exit code 138 ----------------------------------------------------------
```

**Comment by sdmaclea** [comment]
This is two different issues #49110 & #49365.

Closing as dup.
