### ISSUE TITLE
[iOS] NullReferenceException in HttpConnectionPool constructor

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#49187]
This exception can easily be triggered by running the following tests, which will be skipped for now:

- [System.Xml.Tests.AsyncReaderLateInitTests.InitializationWithUriOnNonAsyncReaderThrows](https://github.com/dotnet/runtime/blob/d70f317ddd648afb8fda6e67df8aba3985c73928/src/libraries/System.Private.Xml/tests/XmlReader/Tests/AsyncReaderLateInitTests.cs#L89-L93)
- [System.Xml.Tests.AsyncReaderLateInitTests.ReadAfterInitializationWithUriOnAsyncReaderTrows](https://github.com/dotnet/runtime/blob/d70f317ddd648afb8fda6e67df8aba3985c73928/src/libraries/System.Private.Xml/tests/XmlReader/Tests/AsyncReaderLateInitTests.cs#L80-L87)
- [System.Xml.Tests.AsyncReaderLateInitTests.ReadAsyncAfterInitializationWithUriThrows](https://github.com/dotnet/runtime/blob/d70f317ddd648afb8fda6e67df8aba3985c73928/src/libraries/System.Private.Xml/tests/XmlReader/Tests/AsyncReaderLateInitTests.cs#L71-L78)

Stack trace:
```
System.NullReferenceException : Object reference not set to an instance of an object
   at System.Net.Http.HttpConnectionPool..ctor(HttpConnectionPoolManager poolManager, HttpConnectionKind kind, String host, Int32 port, String sslHostName, Uri proxyUri, Int32 maxConnections)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Xml.XmlDownloadManager.GetNonFileStreamAsync(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Tests.AsyncReaderLateInitTests.<>c.<InitializationWithUriOnNonAsyncReaderThrows>b__9_0()
```

**Comment by karelz** [comment]
Triage: @ManickaP is helping with the PR ...
