### ISSUE TITLE
[mono] Intrinsics runtime tests failure: Unhandled Exception

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#49216]
On OSX x64, these two intrinsics tests failed:

- JIT/HardwareIntrinsics/X86/General/IsSupported_r/IsSupported_r.sh
- JIT/HardwareIntrinsics/X86/General/IsSupported_ro/IsSupported_ro.sh

Failure log:

```
Unhandled Exception:
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.PlatformNotSupportedException
         at System.Runtime.Intrinsics.X86.Sse.get_IsSupported() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Sse.cs:line 17
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
         --- End of inner exception stack trace ---
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 390
         at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 53
         at IntelHardwareIntrinsicTest.Program.Main(String[] args)
      [ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.PlatformNotSupportedException
         at System.Runtime.Intrinsics.X86.Sse.get_IsSupported() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Sse.cs:line 17
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
         --- End of inner exception stack trace ---
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 390
         at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 53
         at IntelHardwareIntrinsicTest.Program.Main(String[] args)
```

**Comment by SamMonoRT** [comment]
@imhameed - were these fixed as part of your work in last couple weeks ?

**Comment by imhameed** [comment]
Should be, yeah. I'll take me > 1 hour to verify this though (mostly because of our build system on this small laptop)

**Comment by SamMonoRT** [comment]
@imhameed - did you get a chance to verify this ?
