### ISSUE TITLE
Test failure System.IO.Compression.Tests.zip_UpdateTests.UpdateCreate(zipFolder: \"normal\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49351]
Run: [runtime-coreclr libraries-jitstress 20210307.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1026925&view=ms.vss-test-web.build-test-results-tab&runId=31898722&resultId=147242&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 -System.IO.Compression.Tests.zip_UpdateTests.UpdateCreate(zipFolder: \"normal\")
```

**Error message:**
```
Assert.All() Failure: 1 out of 6 items in the collection did not pass.
[0]: Item: binary.wmv
 Xunit.Sdk.EqualException: Assert.Equal() Failure
 Expected: 835513040
 Actual: 740169638
 at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at System.IO.Compression.Tests.ZipFileTestBase.<>c__DisplayClass16_0.<IsZipSameAsDir>b__0(FileData file) in /_/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs:line 176
 at Xunit.Assert.All[T](IEnumerable1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36

Stack trace
   at System.IO.Compression.Tests.ZipFileTestBase.IsZipSameAsDir(Stream archiveFile, String directory, ZipArchiveMode mode, Boolean requireExplicit, Boolean checkTimes) in /_/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs:line 154
   at System.IO.Compression.Tests.zip_UpdateTests.UpdateCreate(String zipFolder) in /_/src/libraries/System.IO.Compression/tests/ZipArchive/zip_UpdateTests.cs:line 53
--- End of stack trace from previous location ---

```

**Comment by adamsitnik** [comment]
I've failed to find any repros using the following Kusto query:

```sql
TestResults 
| where Type startswith "System.IO.Compression.Tests.zip_UpdateTests" 
| where Method == "UpdateCreate"
| join kind=inner WorkItems on WorkItemId 
| where Finished >= datetime(2021-01-01 0:00:00)
| join kind=inner Jobs on JobId
| where Branch == "refs/heads/master"
| project Started, Duration, Method, QueueName, Message, StackTrace, Arguments, Type, QueueAlias, DockerTag, Type1, Result
| summarize count() by Message, Type, Method, Result, QueueName, StackTrace
```
