### ISSUE TITLE
Single File application crashes with File Not Found error

### ISSUE THREAD

**Issue by greatoceansoftware** [dotnet/runtime#49366]
This was reported in other topics as 'Single File application crashes when trying to access Application Settings', but I have added the workaround to the publish profile `(<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>),` eliminated the dependency on Application Settings by skipping that call upon window initialization, and I still get the 'File not found' error below. I did not use the Trim option for the Single File Application build.

CONFIGURATION:

.NET 5.0
Windows 10.0.19042
x64

FROM WINDOWS APPLICATION EVENT VIEWER:

Log Name:      Application
Source:        .NET Runtime
Date:          3/9/2021 8:23:09 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      RANDYS-LATITUDE
Description:
Application: EMC2.exe
CoreCLR Version: 5.0.321.7212
.NET Version: 5.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.FrameworkElement' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.TextElement' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.Typography' threw an exception.
 ---> **System.IO.FileNotFoundException**: 
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Windows.Media.TextFormatting.TextRunTypographyProperties.OnPropertiesChanged()
   at MS.Internal.Text.TypographyProperties.ResetProperties()
   at MS.Internal.Text.TypographyProperties..ctor()
   at System.Windows.Documents.Typography..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Documents.TextElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement.FindResourceFromAppOrSystem(Object resourceKey, Object& source, Boolean disableThrowOnResourceNotFound, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList`1 staticResources, IServiceProvider serviceProvider, StaticResourceExtension staticResourceWorker)
   at System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   at System.Windows.ResourceDictionary.set_DeferrableContent(DeferrableContent value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_DeferrableContent>b__297_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at EMC2.App.InitializeComponent()
   at EMC2.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-03-09T16:23:09.7881727Z" />
    <EventRecordID>38729</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>RANDYS-LATITUDE</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: EMC2.exe
CoreCLR Version: 5.0.321.7212
.NET Version: 5.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: Set property 'System.Windows.ResourceDictionary.DeferrableContent' threw an exception.
 ---&gt; System.TypeInitializationException: The type initializer for 'System.Windows.FrameworkElement' threw an exception.
 ---&gt; System.TypeInitializationException: The type initializer for 'System.Windows.Documents.TextElement' threw an exception.
 ---&gt; System.TypeInitializationException: The type initializer for 'System.Windows.Documents.Typography' threw an exception.
 ---&gt; System.IO.FileNotFoundException: 
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Windows.Media.TextFormatting.TextRunTypographyProperties.OnPropertiesChanged()
   at MS.Internal.Text.TypographyProperties.ResetProperties()
   at MS.Internal.Text.TypographyProperties..ctor()
   at System.Windows.Documents.Typography..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Documents.TextElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement.FindResourceFromAppOrSystem(Object resourceKey, Object&amp; source, Boolean disableThrowOnResourceNotFound, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
   at System.Windows.ResourceDictionary.SetOptimizedStaticResources(IList`1 staticResources, IServiceProvider serviceProvider, StaticResourceExtension staticResourceWorker)
   at System.Windows.ResourceDictionary.SetKeys(IList`1 keyCollection, IServiceProvider serviceProvider)
   at System.Windows.ResourceDictionary.SetDeferrableContent(DeferrableContent deferrableContent)
   at System.Windows.ResourceDictionary.set_DeferrableContent(DeferrableContent value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.&lt;&gt;c.&lt;Create_BamlProperty_ResourceDictionary_DeferrableContent&gt;b__297_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at EMC2.App.InitializeComponent()
   at EMC2.App.Main()
</Data>
  </EventData>
</Event>

**Comment by huoyaoyuan** [comment]
WPF should be unsupported by single file at this time.

**Comment by vitek-karas** [comment]
When you run the app, it should extract into `C:\Users\<user>\AppData\Local\Temp\.net\<appname>\<weirdname>`. Can you check if the `System.Runtime.dll` is present in that directory?

Does the app work when published a non-single-file? (same settings, just disable single-file).

**Comment by greatoceansoftware** [comment]
No, it is not in the directory. The list of Runtime files present are shown below.

**Comment by greatoceansoftware** [comment]
![image](https://user-images.githubusercontent.com/78753788/110549927-a5a84080-80e7-11eb-9bda-09e8d7a3573b.png)

**Comment by vitek-karas** [comment]
Can you try to build the app non-single-file - just turn that setting off (I don't know if you're doing this from VS or command line) - and see if the app works/the file is there in the output.
This looks really weird...
I would bet it's trimmed - but only some of it... (for example the System.Runtime.InteropServices.dll is 48kb in the framework, but only 23kb here. But then System.Private.CoreLib.dll is the exact same size in both).

Actually one more thing - if you switched trimming on/off - can you please just delete the entire `obj` and `bin` folder and rebuild everything. There are some known issues where certain changes are not correctly propagated across "incremental" builds.

**Comment by greatoceansoftware** [comment]
Everything is there if I build it normally (not single file).  See the screen shot below.

I deleted the bin and obj folders and rebuilt. Published in VS as single file. This time, an extraction folder was not even created in the temp\.net\appname folder. Same output error in the Windows Event Viewer, however.
![without trim](https://user-images.githubusercontent.com/78753788/110561232-2cffaf00-80fc-11eb-9418-f1088fceb40d.png)

**Comment by greatoceansoftware** [comment]
Another update... I republished without trim and ran the single file exe with Administrator permissions and it worked. Now it works every time whether I use Administrator permissions or not. Still doesn't work using Trim. But the entire users/randy/appdata/local/temp/.net/appname extraction folder is empty, and I can't find where they're going. Did a complete C: drive search.

And, the single file exe doesn't work without it's supporting files in the publish folder. But I understand this is something that is going to be fixed by .net 6? So that the end result is a truly independently functioning single file exe?

**Comment by vitek-karas** [comment]
Did you set the `IncludeAllContentForSelfExtract` to true in the latest attempt or not? If it's `false` (default for 5+), there will be no extraction and thus no folder created in temp.

Just to be sure - you could delete the `.net` folder in temp and try again - it's possible that running the app as admin might have caused some problems with the setup of the temp folder - should not, but still.

Note that even in 6 WPF apps will probably not be true single-file without extraction. What 6 does is it puts all of the core runtime dependencies into the executable. We still don't have a solution to include random native library without extraction - WPF contains several native libraries in the framework - so those will need to remain next to the executable. (Or you will have to opt into extraction).

**Comment by greatoceansoftware** [comment]
Sorry for the delay. Yes, Trim is having some issues. Everything works fine without trim and crashes with trim. I've attached the temp folder results for each case.

[With Trim.txt](https://github.com/dotnet/runtime/files/6131233/With.Trim.txt)

[without trim.txt](https://github.com/dotnet/runtime/files/6131235/without.trim.txt)

**Comment by vitek-karas** [comment]
Trimming WPF is basically not supported - there are several severe issues with it. We're trying to get some of it fixed for 6, but we're not there yet.
I would strongly recommend to NOT trim WPF apps.

**Comment by greatoceansoftware** [comment]
OK, that makes sense. Thanks!

**Comment by agocke** [comment]
Closing, since trimming WPF is not supported.
