### ISSUE TITLE
[macOS-arm64] CoreCLR - Libraries intermittent null reference failures

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#49365]
From https://dev.azure.com/dnceng/public/_build/results?buildId=1019012
```console
----- start Tue Mar 2 10:20:49 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/A43F08FC/p/dotnet exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/A43F08FC/w/9D520897/e /private/tmp/helix/working/A43F08FC/w/9D520897/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 25 of 2319 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 8)
    System.Text.Json.Serialization.Tests.ConstructorTests_Stream.MultipleThreadsLooping [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs(264,0): at System.Text.Json.Serialization.ReflectionEmitMemberAccessor.CreatePropertySetter[TProperty](PropertyInfo propertyInfo)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs(74,0): at System.Text.Json.JsonPropertyInfo`1.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, ClassType runtimeClassType, MemberInfo memberInfo, JsonConverter converter, Nullable`1 ignoreCondition, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(99,0): at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, MemberInfo memberInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options, Nullable`1 parentTypeNumberHandling, Nullable`1 ignoreCondition)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(75,0): at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(256,0): at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(151,0): at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(523,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(538,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs(101,0): at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(61,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.StreamDeserializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(39,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectMinimalAsync|13_1(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(85,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(20,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_String.MultipleThreadsLooping [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs(264,0): at System.Text.Json.Serialization.ReflectionEmitMemberAccessor.CreatePropertySetter[TProperty](PropertyInfo propertyInfo)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs(74,0): at System.Text.Json.JsonPropertyInfo`1.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, ClassType runtimeClassType, MemberInfo memberInfo, JsonConverter converter, Nullable`1 ignoreCondition, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(99,0): at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, MemberInfo memberInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options, Nullable`1 parentTypeNumberHandling, Nullable`1 ignoreCondition)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(75,0): at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(256,0): at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(151,0): at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(523,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(538,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(121,0): at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(33,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.StringDeserializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(39,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectMinimalAsync|13_1(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(85,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(20,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_Span.MultipleThreadsLooping [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReflectionEmitMemberAccessor.cs(264,0): at System.Text.Json.Serialization.ReflectionEmitMemberAccessor.CreatePropertySetter[TProperty](PropertyInfo propertyInfo)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoOfT.cs(74,0): at System.Text.Json.JsonPropertyInfo`1.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, ClassType runtimeClassType, MemberInfo memberInfo, JsonConverter converter, Nullable`1 ignoreCondition, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(99,0): at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, MemberInfo memberInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options, Nullable`1 parentTypeNumberHandling, Nullable`1 ignoreCondition)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs(75,0): at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(256,0): at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs(151,0): at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(523,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(538,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(162,0): at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(75,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.SpanDesearializationWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(39,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectMinimalAsync|13_1(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(85,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(20,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping()
        --- End of stack trace from previous location ---
./RunTests.sh: line 162: 41390 Bus error: 10           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing $RSP_FILE
/private/tmp/helix/working/A43F08FC/w/9D520897/e
----- end Tue Mar 2 10:20:56 PST 2021 ----- exit code 138 ----------------------------------------------------------
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1028375
```console
----- start Mon Mar 8 19:52:05 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/AA8B09AA/p/dotnet exec --runtimeconfig System.ComponentModel.Composition.Tests.runtimeconfig.json --depsfile System.ComponentModel.Composition.Tests.deps.json xunit.console.dll System.ComponentModel.Composition.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/AA8B09AA/w/B5FA09D4/e /private/tmp/helix/working/AA8B09AA/w/B5FA09D4/e
  Discovering: System.ComponentModel.Composition.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.Composition.Tests (found 1430 of 1588 test cases)
  Starting:    System.ComponentModel.Composition.Tests (parallel test collections = on, max threads = 8)
    System.ComponentModel.Composition.ExportCollectionTests.ImportCollectionsFromContainerOnly [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(522,0): at System.SZArrayHelper.GetEnumerator[T]()
        /_/src/libraries/System.ComponentModel.Composition/tests/System/UnitTesting/EqualityExtensions.cs(23,0): at System.UnitTesting.EqualityExtensions.IsTrueForAll[T](IEnumerable`1 source, Predicate`1 predicate, String message)
        /_/src/libraries/System.ComponentModel.Composition/tests/System/UnitTesting/EqualityExtensions.cs(16,0): at System.UnitTesting.EqualityExtensions.IsTrueForAll[T](IEnumerable`1 source, Predicate`1 predicate)
        /_/src/libraries/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/ExportCollectionTests.cs(108,0): at System.ComponentModel.Composition.ExportCollectionTests.Importer.VerifyImport(Int32[] expectedValues)
        /_/src/libraries/System.ComponentModel.Composition/tests/System/ComponentModel/Composition/ExportCollectionTests.cs(160,0): at System.ComponentModel.Composition.ExportCollectionTests.ImportCollectionsFromContainerOnly()
  Finished:    System.ComponentModel.Composition.Tests
=== TEST EXECUTION SUMMARY ===
   System.ComponentModel.Composition.Tests  Total: 1430, Errors: 0, Failed: 1, Skipped: 0, Time: 0.340s
/private/tmp/helix/working/AA8B09AA/w/B5FA09D4/e
----- end Mon Mar 8 19:52:06 PST 2021 ----- exit code 1 ----------------------------------------------------------
```
https://dev.azure.com/dnceng/public/_build/results?buildId=1029228
```console
----- start Tue Mar 9 09:58:59 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/A5390932/p/dotnet exec --runtimeconfig System.Xml.RW.XmlWriterApi.Tests.runtimeconfig.json --depsfile System.Xml.RW.XmlWriterApi.Tests.deps.json xunit.console.dll System.Xml.RW.XmlWriterApi.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/A5390932/w/B0D70978/e /private/tmp/helix/working/A5390932/w/B0D70978/e
  Discovering: System.Xml.RW.XmlWriterApi.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Xml.RW.XmlWriterApi.Tests (found 623 test cases)
  Starting:    System.Xml.RW.XmlWriterApi.Tests (parallel test collections = on, max threads = 8)
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForOneElementWithEndElement [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForOneElementwithAttribute [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForOneElement [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForOneElementwithNamespace [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForOneElementwithAttributeValue [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForMultiElements [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForElementsWithOneEndElement [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCWriteEndDocumentOnCloseTest.TestWriteEndDocumentOnCoseForOneElementwithText [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCErrorConditionWriter.var_14 [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCErrorConditionWriter.var_11 [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
    System.Xml.Tests.TCEOFHandling.EOF_Handling_20 [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs(523,0): at System.SZArrayHelper.GetEnumerator[T]()
  Finished:    System.Xml.RW.XmlWriterApi.Tests
=== TEST EXECUTION SUMMARY ===
   System.Xml.RW.XmlWriterApi.Tests  Total: 23202, Errors: 0, Failed: 11, Skipped: 0, Time: 2.948s
/private/tmp/helix/working/A5390932/w/B0D70978/e
----- end Tue Mar 9 09:59:02 PST 2021 ----- exit code 1 ----------------------------------------------------------
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1031819

```console
----- start Wed Mar 10 11:44:25 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/A42A0995/p/dotnet exec --runtimeconfig System.Dynamic.Runtime.Tests.runtimeconfig.json --depsfile System.Dynamic.Runtime.Tests.deps.json xunit.console.dll System.Dynamic.Runtime.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/A42A0995/w/B15E09D8/e /private/tmp/helix/working/A42A0995/w/B15E09D8/e
  Discovering: System.Dynamic.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Dynamic.Runtime.Tests (found 2901 test cases)
  Starting:    System.Dynamic.Runtime.Tests (parallel test collections = on, max threads = 8)
    ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.compound.conversion.conversion003.conversion003.Test.DynamicCSharpRunTest [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs(17,0): at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
        /_/src/libraries/System.Dynamic.Runtime/tests/Dynamic.Context/Conformance.dynamic.context.operator.compound.conversion.cs(263,0): at ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.compound.conversion.conversion003.conversion003.Test.MainMethod(String[] ars)
        /_/src/libraries/System.Dynamic.Runtime/tests/Dynamic.Context/Conformance.dynamic.context.operator.compound.conversion.cs(237,0): at ManagedTests.DynamicCSharp.Conformance.dynamic.context.operate.compound.conversion.conversion003.conversion003.Test.DynamicCSharpRunTest()
  Finished:    System.Dynamic.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Dynamic.Runtime.Tests  Total: 2901, Errors: 0, Failed: 1, Skipped: 0, Time: 22.187s
/private/tmp/helix/working/A42A0995/w/B15E09D8/e
----- end Wed Mar 10 11:44:50 PST 2021 ----- exit code 1 ----------------------------------------------------------
```
```console
----- start Wed Mar 10 11:45:49 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/A42A0995/p/dotnet exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/A42A0995/w/BDCC0A46/e /private/tmp/helix/working/A42A0995/w/BDCC0A46/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 2281 of 2325 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 8)
    System.Text.Json.Serialization.Tests.ConstructorTests_Span.IgnoreNullValues_DontSetNull_ToConstructorArguments_ThatCantBeNull [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(70,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.SpanDesearializationWrapper.DeserializeWrapper[T](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.ParameterMatching.cs(350,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<>c__DisplayClass65_0.<IgnoreNullValues_DontSetNull_ToConstructorArguments_ThatCantBeNull>b__1()
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Text.Json/tests/Serialization/DeserializationWrapper.cs(70,0): at System.Text.Json.Serialization.Tests.DeserializationWrapper.SpanDesearializationWrapper.DeserializeWrapper[T](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.ParameterMatching.cs(350,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<>c__DisplayClass65_0.<IgnoreNullValues_DontSetNull_ToConstructorArguments_ThatCantBeNull>b__1()
  Finished:    System.Text.Json.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.Json.Tests  Total: 15753, Errors: 0, Failed: 1, Skipped: 0, Time: 49.931s
/private/tmp/helix/working/A42A0995/w/BDCC0A46/e
----- end Wed Mar 10 11:46:41 PST 2021 ----- exit code 1 ----------------------------------------------------------
```

**Comment by mangod9** [comment]
Look to be related to Enumerator and/or Reflection.Emit?

**Comment by danwalmsley** [comment]
@sdmaclea any updates on this? Do you think we can expect this to be resolved for .net 6 release?

**Comment by sdmaclea** [comment]
Based on triaging other test, I think updating to `macOS 11.3` will fix all/most of these issues.  We are in the process of updating our CI machines to 11.3.  I will try to re-enable these tests when those machines are ready.
