### ISSUE TITLE
Test failure System.ServiceProcess.Tests.ServiceBaseTests.TestOnPauseThenStop

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49404]
Run: [runtime-libraries-coreclr outerloop 20210309.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1028781&view=ms.vss-test-web.build-test-results-tab&runId=31938272&resultId=104522&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
 -System.ServiceProcess.Tests.ServiceBaseTests.TestOnPauseThenStop
```

**Error message:**
```
System.ServiceProcess.TimeoutException : The operation requested for service '6b720584-abdc-4619-bc64-2a782259f505.Dependent' has not been completed within the specified time interval.


Stack trace
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 964
   at System.ServiceProcess.Tests.TestServiceInstaller.StopService() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs:line 154
   at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestServiceInstaller.cs:line 119
   at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/TestServiceProvider.cs:line 142
   at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/TestServiceProvider.cs:line 150
   at System.ServiceProcess.Tests.ServiceBaseTests.Dispose() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 229
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```

**Comment by danmoseley** [comment]
In the last 589 executions (at least 90 days) there have been zero failures.
