### ISSUE TITLE
X500DistinguishedName throws if using 'ST' alias instead of 'S'

### ISSUE THREAD

**Issue by stewartadam** [dotnet/runtime#49612]
### Description
Constructing a X500DistinguishedName with `ST` alias instead of `S` for the state (OID 2.5.4.8) on macOS fails and throws an exception:
```
System.Security.Cryptography.CryptographicException: The string contains an invalid X500 name attribute key, oid, value or delimiter.
 ---> System.ArgumentException: The OID value is invalid. (Parameter 'oidValue')
   at System.Formats.Asn1.AsnWriter.WriteObjectIdentifierCore(Asn1Tag tag, ReadOnlySpan`1 oidValue)
   at System.Formats.Asn1.AsnWriter.WriteObjectIdentifier(ReadOnlySpan`1 oidValue, Nullable`1 tag)
   at System.Formats.Asn1.AsnWriter.WriteObjectIdentifier(String oidValue, Nullable`1 tag)
   at Internal.Cryptography.Pal.X500NameEncoder.ParseRdn(Oid tagOid, ReadOnlySpan`1 chars, Boolean hadEscapedQuote)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.X500NameEncoder.ParseRdn(Oid tagOid, ReadOnlySpan`1 chars, Boolean hadEscapedQuote)
   at Internal.Cryptography.Pal.X500NameEncoder.ParseDistinguishedName(String stringForm, List`1 dnSeparators, Boolean noQuotes)
   at Internal.Cryptography.Pal.X500NameEncoder.X500DistinguishedNameEncode(String stringForm, X500DistinguishedNameFlags flags)
   at Internal.Cryptography.Pal.X509Pal.AppleX509Pal.X500DistinguishedNameEncode(String distinguishedName, X500DistinguishedNameFlags flag)
   at System.Security.Cryptography.X509Certificates.X500DistinguishedName.Encode(String distinguishedName, X500DistinguishedNameFlags flags)
   at System.Security.Cryptography.X509Certificates.X500DistinguishedName..ctor(String distinguishedName, X500DistinguishedNameFlags flag)
   at System.Security.Cryptography.X509Certificates.X500DistinguishedName..ctor(String distinguishedName)
```

Works:
```
var subjectDN = new X500DistinguishedName("CN=IoT Device Signing Root, O=Fake Org, L=My City, S=WA, C=US");
```

Fails:
```
var subjectDN = new X500DistinguishedName("CN=IoT Device Signing Root, O=Fake Org, L=My City, ST=WA, C=US");
```

### Configuration
```
$ dotnet --info

.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by vcsjones** [comment]
Using "S" should work on all platforms, so I would recommend switching to that if possible. However, it seems sensible to match Windows' behavior here. I think it makes sense to fix going forward, so I opened a PR.
