### ISSUE TITLE
Test failure baseservices\\exceptions\\unittests\\EHPatternTests\\EHPatternTests.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49623]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20210314.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1038574&view=ms.vss-test-web.build-test-results-tab&runId=32191838&resultId=109723&paneView=debug)

Failed tests:
```
CoreCLR windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
 -baseservices\\exceptions\\unittests\\EHPatternTests\\EHPatternTests.cmd
```

**Error message:**
```
Assert failure(PID 10048 [0x00002740], Thread: 2712 [0x0a98]): !CREATE_CHECK_STRING(pMT && pMT->Validate())

CORECLR! Object::ValidateInner + 0x14C (0x00007ffcd91ba27c)
CORECLR! Object::Validate + 0x118 (0x00007ffcd91ba0e8)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x127 (0x00007ffcd95cafb7)
CORECLR! GcInfoDecoder::ReportSlotToGC + 0xCD (0x00007ffcd95cb1e5)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0xCE5 (0x00007ffcd95ca3e9)
CORECLR! EECodeManager::EnumGcRefs + 0x389 (0x00007ffcd90c4899)
CORECLR! GcStackCrawlCallBack + 0x2CC (0x00007ffcd931652c)
CORECLR! Thread::MakeStackwalkerCallback + 0x6B (0x00007ffcd92103f7)
CORECLR! Thread::StackWalkFramesEx + 0x164 (0x00007ffcd9211ca0)
CORECLR! Thread::StackWalkFrames + 0x184 (0x00007ffcd9211a9c)
 File: D:\workspace\_work\1\s\src\coreclr\vm\object.cpp Line: 516
 Image: C:\h\w\A76908BC\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\A76908BC\w\B91E0989\e\baseservices\exceptions\Reports\baseservices.exceptions\unittests\EHPatternTests\EHPatternTests.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A76908BC\p\corerun.exe" EHPatternTests.dll 
-----------------------------
BaseClassTest
-----------------------------
System.IO.FileNotFoundException: 1
 at BaseClassTest.f2()
 at BaseClassTest.f1()
System.IO.FileNotFoundException: 1
 at BaseClassTest.f1()
 at BaseClassTest.Run()
0121: PASS
-----------------------------
TryCatchInFinallyTest
-----------------------------
System.InvalidProgramException: Common Language Runtime detected an invalid program.
 at TryCatchInFinallyTest.Run()
0123456: PASS
-----------------------------
RecurseTest
-----------------------------
System.Exception: 7
 at RecurseTest.DoTest(Int32 level)
System.Exception: 5
 at RecurseTest.DoTest(Int32 level)
System.Exception: 3
 at RecurseTest.DoTest(Int32 level)
System.Exception: 1
 at RecurseTest.DoTest(Int32 level)
876543210: PASS
-----------------------------
ThrowInFinallyNestedInTryTest
-----------------------------
System.ArgumentException: Value does not fall within the expected range.
 at ThrowInFinallyNestedInTryTest.MiddleMethod()
 at ThrowInFinallyNestedInTryTest.Run()
0123456789a: PASS
-----------------------------
GoryManagedPresentTest
-----------------------------
System.DivideByZeroException: Attempted to divide by zero.
 at GoryManagedPresentTest.foo(Int32 dummy)
 at GoryManagedPresentTest.Run()
0123456: PASS
-----------------------------
InnerFinallyAndCatchTest
-----------------------------
abcdefghijklm13: PASS
-----------------------------
InnerFinallyTest
-----------------------------
 try 1
 try 1.1
 finally 1.1
 try 1.1.1
 Throwing an exception here!
 finally 1.1.1
 catch 1
 finally 1
: PASS
-----------------------------
ThrowInFinallyTest
-----------------------------
System.Exception: C
 at ThrowInFinallyTest.Dumb()
 at ThrowInFinallyTest.Run()
0123456789Ca: PASS
-----------------------------
RecursiveRethrow
-----------------------------
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.Run()
210C0C1C2: PASS
-----------------------------
RecursiveThrowNew
-----------------------------
System.Exception: eX
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e0
 at RecursiveThrowNew.LoveToRec

Stack trace
   at baseservices_exceptions._unittests_EHPatternTests_EHPatternTests_._unittests_EHPatternTests_EHPatternTests_cmd()

```

**Comment by VincentBu** [comment]
Same test failed in [runtime-coreclr gcstress0x3-gcstress0xc 20210321.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1049735&view=ms.vss-test-web.build-test-results-tab&runId=32444382&resultId=109012&paneView=debug)

Failed test:
```
CoreCLR windows arm64 Checked gcstress0x3 @ Windows.10.Arm64v8.Open
 -baseservices\\exceptions\\unittests\\EHPatternTests\\EHPatternTests.cmd
```

**Error message:**
```
Assert failure(PID 1820 [0x0000071c], Thread: 14596 [0x3904]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner'::1'::catch$12 + 0x12C (0x00007ffbe5bda244)
CORECLR! CallSettingFrame + 0x68 (0x00007ffbe56d2f10)
CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x160 (0x00007ffbe5b3b670)
NTDLL! RtlRestoreContext + 0xEC (0x00007ffc149a369c)
CORECLR! Object::ValidateInner + 0x14C (0x00007ffbe57bec2c)
CORECLR! Object::Validate + 0xC0 (0x00007ffbe57beab8)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x13C (0x00007ffbe59886d4)
CORECLR! GcInfoDecoder::ReportSlotToGC + 0xE4 (0x00007ffbe5988924)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0xD40 (0x00007ffbe5987760)
CORECLR! EECodeManager::EnumGcRefs + 0x2CC (0x00007ffbe574d2cc)
 File: D:\workspace\_work\1\s\src\coreclr\vm\object.cpp Line: 593
 Image: D:\h\w\A3AB0918\p\corerun.exe


Return code: 1
Raw output file: D:\h\w\A3AB0918\w\B64A0A2E\e\baseservices\exceptions\Reports\baseservices.exceptions\unittests\EHPatternTests\EHPatternTests.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A3AB0918\p\corerun.exe" EHPatternTests.dll 
-----------------------------
BaseClassTest
-----------------------------
System.IO.FileNotFoundException: 1
 at BaseClassTest.f2()
 at BaseClassTest.f1()
System.IO.FileNotFoundException: 1
 at BaseClassTest.f1()
 at BaseClassTest.Run()
0121: PASS
-----------------------------
TryCatchInFinallyTest
-----------------------------
System.InvalidProgramException: Common Language Runtime detected an invalid program.
 at TryCatchInFinallyTest.Run()
0123456: PASS
-----------------------------
RecurseTest
-----------------------------
System.Exception: 7
 at RecurseTest.DoTest(Int32 level)
System.Exception: 5
 at RecurseTest.DoTest(Int32 level)
System.Exception: 3
 at RecurseTest.DoTest(Int32 level)
System.Exception: 1
 at RecurseTest.DoTest(Int32 level)
876543210: PASS
-----------------------------
ThrowInFinallyNestedInTryTest
-----------------------------
System.ArgumentException: Value does not fall within the expected range.
 at ThrowInFinallyNestedInTryTest.MiddleMethod()
 at ThrowInFinallyNestedInTryTest.Run()
0123456789a: PASS
-----------------------------
GoryManagedPresentTest
-----------------------------
System.DivideByZeroException: Attempted to divide by zero.
 at GoryManagedPresentTest.foo(Int32 dummy)
 at GoryManagedPresentTest.Run()
0123456: PASS
-----------------------------
InnerFinallyAndCatchTest
-----------------------------
abcdefghijklm13: PASS
-----------------------------
InnerFinallyTest
-----------------------------
 try 1
 try 1.1
 finally 1.1
 try 1.1.1
 Throwing an exception here!
 finally 1.1.1
 catch 1
 finally 1
: PASS
-----------------------------
ThrowInFinallyTest
-----------------------------
System.Exception: C
 at ThrowInFinallyTest.Dumb()
 at ThrowInFinallyTest.Run()
0123456789Ca: PASS
-----------------------------
RecursiveRethrow
-----------------------------
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.Run()
210C0C1C2: PASS
-----------------------------
RecursiveThrowNew
-----------------------------
System.Exception: eX
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception:

Stack trace
   at baseservices_exceptions._unittests_EHPatternTests_EHPatternTests_._unittests_EHPatternTests_EHPatternTests_cmd()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress-extra 20210321.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32449262&resultId=109282&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_zapdisable_heapverify1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 -baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh
```

**Error message:**
```
Assert failure(PID 1483 [0x000005cb], Thread: 1483 [0x05cb]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
 File: /__w/1/s/src/coreclr/vm/object.cpp Line: 516
 Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fb1c96108)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fb1c96108)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fb1c8b1d0)
/root/helix/work/workitem/baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh: line 377: 1483 Aborted (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/exceptions/Reports/baseservices.exceptions/unittests/EHPatternTests/EHPatternTests.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun EHPatternTests.dll ''
-----------------------------
BaseClassTest
-----------------------------
System.IO.FileNotFoundException: 1
 at BaseClassTest.f2()
 at BaseClassTest.f1()
System.IO.FileNotFoundException: 1
 at BaseClassTest.f1()
 at BaseClassTest.Run()
0121: PASS
-----------------------------
TryCatchInFinallyTest
-----------------------------
System.InvalidProgramException: Common Language Runtime detected an invalid program.
 at TryCatchInFinallyTest.Run()
0123456: PASS
-----------------------------
RecurseTest
-----------------------------
System.Exception: 7
 at RecurseTest.DoTest(Int32 level)
System.Exception: 5
 at RecurseTest.DoTest(Int32 level)
System.Exception: 3
 at RecurseTest.DoTest(Int32 level)
System.Exception: 1
 at RecurseTest.DoTest(Int32 level)
876543210: PASS
-----------------------------
ThrowInFinallyNestedInTryTest
-----------------------------
System.ArgumentException: Value does not fall within the expected range.
 at ThrowInFinallyNestedInTryTest.MiddleMethod()
 at ThrowInFinallyNestedInTryTest.Run()
0123456789a: PASS
-----------------------------
GoryManagedPresentTest
-----------------------------
System.DivideByZeroException: Attempted to divide by zero.
 at GoryManagedPresentTest.foo(Int32 dummy)
 at GoryManagedPresentTest.Run()
0123456: PASS
-----------------------------
InnerFinallyAndCatchTest
-----------------------------
abcdefghijklm13: PASS
-----------------------------
InnerFinallyTest
-----------------------------
 try 1
 try 1.1
 finally 1.1
 try 1.1.1
 Throwing an exception here!
 finally 1.1.1
 catch 1
 finally 1
: PASS
-----------------------------
ThrowInFinallyTest
-----------------------------
System.Exception: C
 at ThrowInFinallyTest.Dumb()
 at ThrowInFinallyTest.Run()
0123456789Ca: PASS
-----------------------------
RecursiveRethrow
-----------------------------
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.Run()
210C0C1C2: PASS
-----------------------------
RecursiveThrowNew
-----------------------------
System.Exception: eX
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e0
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e1
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e2
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.Run()
210C0(eX)C1(e0)C2(e1)CM(e2): PASS
-----------------------------
PendingTest
-----------------------------
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTes

Stack trace
   at baseservices_exceptions._unittests_EHPatternTests_EHPatternTests_._unittests_EHPatternTests_EHPatternTests_sh()

```

**Comment by kunalspathak** [comment]
Fixed by #50115

**Comment by janvorli** [comment]
@kunalspathak I am hitting this issue with GCStress 3 on x64 with the current main branch in local testing. This is the piece of code where it happens with GC info:
```
C:\Users\LocalJanvorli\git\runtime\src\tests\baseservices\exceptions\unittests\EHPatternTests.cs @ 956:
00000621 -rdx -rcx
00007ffc`cbf8a3a1 ba06000000      mov     edx,6
00007ffc`cbf8a3a6 83fa06          cmp     edx,6
00007ffc`cbf8a3a9 7611            jbe     EHPatternTests!StrSwitchFinalTest.Run()+0x63c (00007ffc`cbf8a3bc)
00007ffc`cbf8a3ab 488b5740        mov     rdx,qword ptr [rdi+40h]
0000062f +rdx
00007ffc`cbf8a3af 488b4e08        mov     rcx,qword ptr [rsi+8]
00000633 +rcx
00007ffc`cbf8a3b3 3909            cmp     dword ptr [rcx],ecx
00007ffc`cbf8a3b5 e876e29fff      call    CLRStub[MethodDescPrestub]@7ffccb988630 (00007ffc`cb988630) (Trace.WriteLine(System.String), mdToken: 0000000006000003)
0000063a -rdx -rcx
00007ffc`cbf8a3ba eb6e            jmp     EHPatternTests!StrSwitchFinalTest.Run()+0x6aa (00007ffc`cbf8a42a)
0000063c -rsi +rbx
00007ffc`cbf8a3bc e8df8b175f      call    coreclr!JIT_RngChkFail (00007ffd`2b102fa0)
>>> 00007ffc`cbf8a3c1 cc              int     3
```
The Rip of the frame is the one marked by `>>>`. The `GcInfoDecoder::ReportRegisterToGC` is called with regNum = 3, which represents `RBX`. It is not clear to me why RBX is marked as live at that place, as it doesn't seem to contain any reference.

The whole disassembly can be viewed here:
https://gist.github.com/janvorli/db2c98ef8029aad2b78003fb18bf6750

**Comment by janvorli** [comment]
It is 100% repro for me, at least in checked build of coreclr - setting the `COMPlus_GCStress=3` and then running the test.

**Comment by kunalspathak** [comment]
Thanks @janvorli for the repro. By the way, has anything changed recently in runtime? I kicked off the gcstress CI job this morning and seeing [250 failures](https://dev.azure.com/dnceng/public/_build/results?buildId=1137403&view=ms.vss-test-web.build-test-results-tab) vs. 12 failures on [last weekend's run](https://dev.azure.com/dnceng/public/_build/results?buildId=1129737&view=ms.vss-test-web.build-test-results-tab).

FYI - @BruceForstall

**Comment by janvorli** [comment]
@kunalspathak I am sorry, I have just found that I have somehow updated my main branch incorrectly to an older version before your fix. I'm not sure how that happened, but that means that we can really close this issue.
