### ISSUE TITLE
Test failure baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49625]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20210314.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1038574&view=ms.vss-test-web.build-test-results-tab&runId=32191738&resultId=109665&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0x3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 -baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh
```

**Error message:**
```
/root/helix/work/workitem/baseservices/exceptions/unittests/EHPatternTests/EHPatternTests.sh: line 376: 5136 Segmentation fault (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/exceptions/Reports/baseservices.exceptions/unittests/EHPatternTests/EHPatternTests.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun EHPatternTests.dll ''
-----------------------------
BaseClassTest
-----------------------------
System.IO.FileNotFoundException: 1
 at BaseClassTest.f2()
 at BaseClassTest.f1()
System.IO.FileNotFoundException: 1
 at BaseClassTest.f1()
 at BaseClassTest.Run()
0121: PASS
-----------------------------
TryCatchInFinallyTest
-----------------------------
System.InvalidProgramException: Common Language Runtime detected an invalid program.
 at TryCatchInFinallyTest.Run()
0123456: PASS
-----------------------------
RecurseTest
-----------------------------
System.Exception: 7
 at RecurseTest.DoTest(Int32 level)
System.Exception: 5
 at RecurseTest.DoTest(Int32 level)
System.Exception: 3
 at RecurseTest.DoTest(Int32 level)
System.Exception: 1
 at RecurseTest.DoTest(Int32 level)
876543210: PASS
-----------------------------
ThrowInFinallyNestedInTryTest
-----------------------------
System.ArgumentException: Value does not fall within the expected range.
 at ThrowInFinallyNestedInTryTest.MiddleMethod()
 at ThrowInFinallyNestedInTryTest.Run()
0123456789a: PASS
-----------------------------
GoryManagedPresentTest
-----------------------------
System.DivideByZeroException: Attempted to divide by zero.
 at GoryManagedPresentTest.foo(Int32 dummy)
 at GoryManagedPresentTest.Run()
0123456: PASS
-----------------------------
InnerFinallyAndCatchTest
-----------------------------
abcdefghijklm13: PASS
-----------------------------
InnerFinallyTest
-----------------------------
 try 1
 try 1.1
 finally 1.1
 try 1.1.1
 Throwing an exception here!
 finally 1.1.1
 catch 1
 finally 1
: PASS
-----------------------------
ThrowInFinallyTest
-----------------------------
System.Exception: C
 at ThrowInFinallyTest.Dumb()
 at ThrowInFinallyTest.Run()
0123456789Ca: PASS
-----------------------------
RecursiveRethrow
-----------------------------
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
 at RecursiveRethrow.LoveToRecurse(Int32 i)
 at RecursiveRethrow.Run()
210C0C1C2: PASS
-----------------------------
RecursiveThrowNew
-----------------------------
System.Exception: eX
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e0
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e1
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
System.Exception: e2
 at RecursiveThrowNew.LoveToRecurse(Int32 i)
 at RecursiveThrowNew.Run()
210C0(eX)C1(e0)C2(e1)CM(e2): PASS
-----------------------------
PendingTest
-----------------------------
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTest.f2()
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTest.f2()
 at PendingTest.f1()
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f1()
 at PendingTest.Run()
System.Exception: Exception of type 'System.Exception' was thrown.
 at PendingTest.f3()
 at PendingTest.f2()
System.Exception: Exception of type 'System.Exceptio

Stack trace
   at baseservices_exceptions._unittests_EHPatternTests_EHPatternTests_._unittests_EHPatternTests_EHPatternTests_sh()

```

**Comment by BruceForstall** [comment]
Probably a dup of https://github.com/dotnet/runtime/issues/49623
