### ISSUE TITLE
Test failure JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49631]
Run: [runtime-coreclr gcstress-extra 20210313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1038123&view=ms.vss-test-web.build-test-results-tab&runId=32184208&resultId=106684&paneView=debug)

Failed tests:
```
CoreCLR Linux x64 Checked gcstress0xc_jitstress2 @ Ubuntu.1804.Amd64.Open
 -JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
 -JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
```

**Error message:**
```
/home/helixbot/work/AA000949/w/BC220A5C/e/JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh: line 374: 8888 Segmentation fault (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /home/helixbot/work/AA000949/w/BC220A5C/e/JIT/Performance/Reports/JIT.Performance/CodeQuality/Serialization/Serialize/Serialize.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/AA000949/p/corerun Serialize.dll ''
Gathering state for process 8888 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.8888.dmp
Written 68923392 bytes (16827 pages) to core file
Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/AA000949/p
> /home/helixbot/work/AA000949/w/BC220A5C/e/JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
Expected: True
Actual: False

Stack trace
   at JIT_Performance._CodeQuality_Serialization_Serialize_Serialize_._CodeQuality_Serialization_Serialize_Serialize_sh()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress-extra 20210327.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679000&resultId=108918&paneView=debug)

Failed test:
```
CoreCLR Linux x64 Checked gcstress0xc_zapdisable_jitstress2 @ Ubuntu.1804.Amd64.Open
 -JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
 -JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
```

**Error message:**
```
/home/helixbot/work/9AE4088E/w/96B30896/e/JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh: line 375: 20882 Segmentation fault (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /home/helixbot/work/9AE4088E/w/96B30896/e/JIT/Performance/Reports/JIT.Performance/CodeQuality/Serialization/Deserialize/Deserialize.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/9AE4088E/p/corerun Deserialize.dll ''
Gathering state for process 20882 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.20882.dmp
Written 70447104 bytes (17199 pages) to core file
Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/9AE4088E/p
> /home/helixbot/work/9AE4088E/w/96B30896/e/JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
Expected: True
Actual: False

Stack trace
   at JIT_Performance._CodeQuality_Serialization_Deserialize_Deserialize_._CodeQuality_Serialization_Deserialize_Deserialize_sh()

```

**Comment by VincentBu** [comment]
Same test failed with `Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object`
Run: [runtime-coreclr jitstress 20210421.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1101366&view=ms.vss-test-web.build-test-results-tab&runId=33666676&resultId=108882&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked jitstress1_tiered @ OSX.1100.ARM64.Open
 -JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
```

**Error message:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
 at System.SZArrayHelper.get_CountT in System.Private.CoreLib.dll:token 0x6000160+0x0
 at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable1 source) in /_/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.Linq.cs:line 70
 at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source) in //src/libraries/System.Linq/src/System/Linq/ToCollection.cs:line 12
 at System.Runtime.Serialization.DataContract.TryGetDCAttribute(Type type, DataContractAttribute& dataContractAttribute) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 1432
 at System.Runtime.Serialization.DataContract.GetStableName(Type type, Boolean& hasDataContract) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 1335
 at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/ClassDataContract.cs:line 739
 at System.Runtime.Serialization.ClassDataContract..ctor(Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/ClassDataContract.cs:line 45
 at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 537
 at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 500
 at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 387
 at System.Runtime.Serialization.DataContract.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 102
 at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 88
 at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 81
 at System.Runtime.Serialization.DataContract.GetDataContract(Type type) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 75
 at System.Runtime.Serialization.DataContractSerializer.get_RootContract() in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializer.cs:line 227
 at System.Runtime.Serialization.DataContractSerializer.InternalWriteStartObject(XmlWriterDelegator writer, Object graph) in //src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializer.cs:line 335
 at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializer.cs:line 243
 at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolv

Stack trace
   at JIT_Performance._CodeQuality_Serialization_Serialize_Serialize_._CodeQuality_Serialization_Serialize_Serialize_sh()

```

**Comment by VincentBu** [comment]
Historical failures of this test:

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-04-22T07:25:59.309Z | osx.1100.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=1101366&view=ms.vss-test-web.build-test-results-tab&runId=33666676&resultId=108882&paneView=debug)
2021-04-01T10:19:26.12Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2 outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835888&resultId=106505&paneView=debug)
2021-04-01T10:19:24.528Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2 outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835886&resultId=106790&paneView=debug)
2021-04-01T10:16:56.526Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835860&resultId=106531&paneView=debug)
2021-04-01T10:16:55.583Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835858&resultId=105960&paneView=debug)
2021-04-01T09:49:28.034Z | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835408&resultId=106013&paneView=debug)
2021-04-01T07:58:14.852Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833158&resultId=102043&paneView=debug)
2021-04-01T07:58:13.727Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833156&resultId=102268&paneView=debug)
2021-04-01T07:56:44.714Z | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833114&resultId=102201&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-04-01T07:56:34.509Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833106&resultId=102054&paneView=debug)
2021-04-01T07:56:33.895Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833102&resultId=102059&paneView=debug)
2021-03-29T08:47:20.892Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060923&view=ms.vss-test-web.build-test-results-tab&runId=32697250&resultId=101858&paneView=debug)
2021-03-29T00:28:41.142Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060562&view=ms.vss-test-web.build-test-results-tab&runId=32689394&resultId=107965&paneView=debug)
2021-03-28T23:28:25.642Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060562&view=ms.vss-test-web.build-test-results-tab&runId=32688718&resultId=105149&paneView=debug)
2021-03-28T09:00:36.893Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060200&view=ms.vss-test-web.build-test-results-tab&runId=32681572&resultId=105592&paneView=debug)
2021-03-28T01:14:28.764Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679900&resultId=107879&paneView=debug)
2021-03-27T23:58:26.734Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679000&resultId=108918&paneView=debug)
2021-03-22T08:57:24.144Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1050218&view=ms.vss-test-web.build-test-results-tab&runId=32457492&resultId=105754&paneView=debug)
2021-03-22T00:24:24.957Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32449834&resultId=107150&paneView=debug)
2021-03-21T23:51:31.875Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32449222&resultId=107186&paneView=debug)
2021-03-21T08:42:38.129Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049654&view=ms.vss-test-web.build-test-results-tab&runId=32441978&resultId=111048&paneView=debug)
2021-03-21T02:19:49.047Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049449&view=ms.vss-test-web.build-test-results-tab&runId=32439512&resultId=110726&paneView=debug)
2021-03-20T23:46:18.917Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049449&view=ms.vss-test-web.build-test-results-tab&runId=32437552&resultId=110732&paneView=debug)
2021-03-15T08:50:16.391Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1039046&view=ms.vss-test-web.build-test-results-tab&runId=32202924&resultId=105371&paneView=debug)
2021-03-15T01:00:07.956Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038776&view=ms.vss-test-web.build-test-results-tab&runId=32197646&resultId=104705&paneView=debug)
2021-03-14T23:46:18.965Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038776&view=ms.vss-test-web.build-test-results-tab&runId=32196892&resultId=103485&paneView=debug)
2021-03-14T08:30:52.344Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038402&view=ms.vss-test-web.build-test-results-tab&runId=32187942&resultId=107908&paneView=debug)
2021-03-14T00:57:37.666Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038123&view=ms.vss-test-web.build-test-results-tab&runId=32184208&resultId=106684&paneView=debug)
2021-03-14T00:16:04.368Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038123&view=ms.vss-test-web.build-test-results-tab&runId=32183418&resultId=106059&paneView=debug)


</details>

**Comment by StephenMolloy** [comment]
@VincentBu, is this still an issue? We aren't aware of any changes in Serialization around this time that would trigger an issue like this.

**Comment by VincentBu** [comment]
> @VincentBu, is this still an issue? We aren't aware of any changes in Serialization around this time that would trigger an issue like this.

This test didn't fail recently.

**Comment by StephenMolloy** [comment]
Seems like this was probably a transient issue then. Also, I'm not familiar with the runtime test setup, so there doesn't seem like there is much upside to spending the time on ramp up and investigating this any further at this point. If it reappears in the future, we can take a closer look. Closing for now.
