### ISSUE TITLE
Test failure ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49632]
Run: [runtime-coreclr gcstress-extra 20210313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1038123&view=ms.vss-test-web.build-test-results-tab&runId=32184208&resultId=109203&paneView=debug)

Failed test:
```
CoreCLR Linux x64 Checked gcstress0xc_jitstress2 @ Ubuntu.1804.Amd64.Open
 -ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh
```

**Error message:**
```
/home/helixbot/work/AA000949/w/B1AD0A0B/e/ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh: line 374: 24063 Segmentation fault (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /home/helixbot/work/AA000949/w/B1AD0A0B/e/ilasm/PortablePdb/Reports/ilasm.PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/AA000949/p/corerun IlasmPortablePdbTests.dll ''
Discovering...
Gathering state for process 24063 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.24063.dmp
Written 95232000 bytes (23250 pages) to core file
Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/AA000949/p
> /home/helixbot/work/AA000949/w/B1AD0A0B/e/ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh
Expected: True
Actual: False

Stack trace
   at ilasm_PortablePdb._IlasmPortablePdbTests_IlasmPortablePdbTests_._IlasmPortablePdbTests_IlasmPortablePdbTests_sh()

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr gcstress-extra 20210327.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679000&resultId=108245&paneView=debug)

Failed test:
```
CoreCLR Linux x64 Checked gcstress0xc_zapdisable_jitstress2 @ Ubuntu.1804.Amd64.Open
 -ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh
```

**Error message:**
```
/home/helixbot/work/9AE4088E/w/B5C70A32/e/ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh: line 375: 6820 Segmentation fault (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code: 1
Raw output file: /home/helixbot/work/9AE4088E/w/B5C70A32/e/ilasm/PortablePdb/Reports/ilasm.PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.output.txt
Raw output:
BEGIN EXECUTION
/home/helixbot/work/9AE4088E/p/corerun IlasmPortablePdbTests.dll ''
Discovering...
Gathering state for process 6820 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.6820.dmp
Written 101179392 bytes (24702 pages) to core file
Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/9AE4088E/p
> /home/helixbot/work/9AE4088E/w/B5C70A32/e/ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh
Expected: True
Actual: False

Stack trace
   at ilasm_PortablePdb._IlasmPortablePdbTests_IlasmPortablePdbTests_._IlasmPortablePdbTests_IlasmPortablePdbTests_sh()

```

**Comment by kunalspathak** [comment]
Historical failures of this test:

Queued | OS | Arch | Column1
-- | -- | -- | --
2021-04-01 09:53:50.6200000 | windows.10.arm64v8.open | arm64 | [runtime-coreclr crossgen2 outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835488&resultId=110493&paneView=debug)
2021-04-01 09:53:49.1820000 | windows.10.arm64v8.open | arm64 | [runtime-coreclr crossgen2 outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835486&resultId=110493&paneView=debug)
2021-04-01 09:52:42.7110000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2 outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835476&resultId=110506&paneView=debug)
2021-04-01 09:52:41.8360000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2 outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835478&resultId=110506&paneView=debug)
2021-04-01 09:49:28.0340000 | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835408&resultId=105616&paneView=debug)
2021-04-01 09:47:40.3000000 | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835364&resultId=107727&paneView=debug)
2021-04-01 07:58:14.8520000 | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833158&resultId=102248&paneView=debug)
2021-04-01 07:58:13.7270000 | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833156&resultId=101957&paneView=debug)
2021-04-01 07:56:44.7140000 | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833114&resultId=101905&paneView=debug)
2021-04-01 07:56:44.0100000 | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833112&resultId=101825&paneView=debug)
2021-04-01 07:56:34.5090000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2 Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833106&resultId=101836&paneView=debug)
2021-04-01 07:56:33.8950000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2 Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833102&resultId=101836&paneView=debug)
2021-04-01 07:51:19.1240000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2 Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32832982&resultId=102510&paneView=debug)
2021-04-01 07:51:17.9790000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2 Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32832984&resultId=102510&paneView=debug)
2021-04-01 07:50:51.7180000 | windows.10.arm64v8.open | arm64 | [runtime-coreclr crossgen2 Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32832958&resultId=102499&paneView=debug)
2021-04-01 07:50:51.0230000 | windows.10.arm64v8.open | arm64 | [runtime-coreclr crossgen2 Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32832960&resultId=102853&paneView=debug)
2021-03-29 08:47:20.8920000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060923&view=ms.vss-test-web.build-test-results-tab&runId=32697250&resultId=110123&paneView=debug)
2021-03-29 08:38:59.3830000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060923&view=ms.vss-test-web.build-test-results-tab&runId=32697026&resultId=110505&paneView=debug)
2021-03-29 00:31:39.5610000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060562&view=ms.vss-test-web.build-test-results-tab&runId=32689450&resultId=108805&paneView=debug)
2021-03-29 00:28:41.1420000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060562&view=ms.vss-test-web.build-test-results-tab&runId=32689394&resultId=106577&paneView=debug)
2021-03-28 23:28:25.6420000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060562&view=ms.vss-test-web.build-test-results-tab&runId=32688718&resultId=108441&paneView=debug)
2021-03-28 23:27:13.6930000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060562&view=ms.vss-test-web.build-test-results-tab&runId=32688690&resultId=108805&paneView=debug)
2021-03-28 09:00:36.8930000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060200&view=ms.vss-test-web.build-test-results-tab&runId=32681572&resultId=110437&paneView=debug)
2021-03-28 08:48:19.7690000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060200&view=ms.vss-test-web.build-test-results-tab&runId=32681532&resultId=110505&paneView=debug)
2021-03-28 01:14:28.7640000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679900&resultId=106950&paneView=debug)
2021-03-28 00:29:38.3330000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679516&resultId=108805&paneView=debug)
2021-03-27 23:58:26.7340000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32679000&resultId=108245&paneView=debug)
2021-03-27 23:53:44.7360000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1060034&view=ms.vss-test-web.build-test-results-tab&runId=32678958&resultId=108805&paneView=debug)
2021-03-22 08:57:24.1440000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1050218&view=ms.vss-test-web.build-test-results-tab&runId=32457492&resultId=109182&paneView=debug)
2021-03-22 08:53:36.8620000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1050218&view=ms.vss-test-web.build-test-results-tab&runId=32457428&resultId=110502&paneView=debug)
2021-03-22 00:55:25.1780000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32450252&resultId=108351&paneView=debug)
2021-03-22 00:24:24.9570000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32449834&resultId=104090&paneView=debug)
2021-03-21 23:57:35.2640000 | windows.10.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32449306&resultId=108806&paneView=debug)
2021-03-21 23:51:31.8750000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049876&view=ms.vss-test-web.build-test-results-tab&runId=32449222&resultId=104346&paneView=debug)
2021-03-21 08:42:38.1290000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049654&view=ms.vss-test-web.build-test-results-tab&runId=32441978&resultId=109655&paneView=debug)
2021-03-21 02:19:49.0470000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049449&view=ms.vss-test-web.build-test-results-tab&runId=32439512&resultId=106681&paneView=debug)
2021-03-20 23:46:18.9170000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1049449&view=ms.vss-test-web.build-test-results-tab&runId=32437552&resultId=108418&paneView=debug)
2021-03-15 08:50:16.3910000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1039046&view=ms.vss-test-web.build-test-results-tab&runId=32202924&resultId=111050&paneView=debug)
2021-03-15 01:00:07.9560000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038776&view=ms.vss-test-web.build-test-results-tab&runId=32197646&resultId=109469&paneView=debug)
2021-03-14 23:46:18.9650000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038776&view=ms.vss-test-web.build-test-results-tab&runId=32196892&resultId=110078&paneView=debug)
2021-03-14 08:30:52.3440000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr crossgen2-composite gcstress Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038402&view=ms.vss-test-web.build-test-results-tab&runId=32187942&resultId=110354&paneView=debug)
2021-03-14 00:57:37.6660000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038123&view=ms.vss-test-web.build-test-results-tab&runId=32184208&resultId=109203&paneView=debug)
2021-03-14 00:16:04.3680000 | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1038123&view=ms.vss-test-web.build-test-results-tab&runId=32183418&resultId=109812&paneView=debug)

**Comment by kunalspathak** [comment]
This test started failing with the composite errors:

```cmd
 Could Not Find C:\h\w\AD4508E7\w\B61909FD\e\ilasm\PortablePdb\IlasmPortablePdbTests\composite-r2r.dll.rsp
      Unhandled exception. System.AggregateException: One or more errors occurred. (Code generation failed for method '[IlasmPortablePdbTests]IlasmPortablePdbTests.IlasmPortablePdbTesterCommon.GetExpectedForTestLocalScopes(string)')
       ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[IlasmPortablePdbTests]IlasmPortablePdbTests.IlasmPortablePdbTesterCommon.GetExpectedForTestLocalScopes(string)'
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at ILCompiler.ReadyToRunCompilationModuleGroupBase.VersionsWithType(TypeDesc typeDesc)
         at ILCompiler.DependencyAnalysis.ReadyToRun.ModuleTokenResolver.AddModuleTokenForType(TypeDesc type, ModuleToken token)
         at Internal.JitInterface.CorInfoImpl.resolveToken(CORINFO_RESOLVED_TOKEN& pResolvedToken)
         at Internal.JitInterface.CorInfoImpl._resolveToken(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken)
         --- End of inner exception stack trace ---
         at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
         at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger)
         at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__36_0(DependencyNodeCore`1 dependency)
         at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
         at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
         at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
         at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
         at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
         at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
         at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
         at ILCompiler.ReadyToRunCodegenCompilation.ComputeDependencyNodeDependencies(List`1 obj)
         at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
         at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
         at ILCompiler.Program.Run(String[] args)
         at ILCompiler.Program.Main(String[] args)
```

@mangod9 - I am assigning it to you. It looks similar to https://github.com/dotnet/runtime/issues/49985

**Comment by trylek** [comment]
@kunalspathak - I believe that the compilation failure you quoted was https://github.com/dotnet/runtime/issues/50520 and that got fixed by https://github.com/dotnet/runtime/pull/50539. This corresponds to the fact that the Crossgen2 compilation issue hasn't reproed since JanK merged the fix in. For the actual GC stress-related crash in the test that Vincent originally created this issue for, I guess that probably got independently fixed as you're not tracking any reproes since 4/1 and in March it was failing several times a day.

**Comment by kunalspathak** [comment]
It failed again because of timeout - [runtime-coreclr r2r-extra Checked-gcstress0xf](https://dev.azure.com/dnceng/public/_build/results?buildId=1082163&view=ms.vss-test-web.build-test-results-tab&runId=33187792&resultId=110228&paneView=debug)
