### ISSUE TITLE
Test failure System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49681]
Run: [runtime-libraries-coreclr outerloop 20210315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1039207&view=ms.vss-test-web.build-test-results-tab&runId=32204794&resultId=103970&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
 -System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop
```

**Error message:**
```
System.InvalidOperationException : Cannot start service '5f2f37f0-4b7d-43e1-abb9-eb4d5a76ebd1' on computer '.'.
---- System.ComponentModel.Win32Exception : The service did not respond to the start or control request in a timely fashion.


Stack trace
   at System.ServiceProcess.ServiceController.Start(String[] args) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 898
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 92
----- Inner Stack Trace -----
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210701.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1215448&view=ms.vss-test-web.build-test-results-tab&runId=36278036&resultId=104334&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop

```
**Error message:**
```
System.InvalidOperationException : Cannot start service 'bb000558-f73e-4880-a822-968aeec809b2' on computer '.'.
---- System.ComponentModel.Win32Exception : The service did not respond to the start or control request in a timely fashion.


Stack trace
   at System.ServiceProcess.ServiceController.Start(String[] args) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 898
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 92
----- Inner Stack Trace -----
```

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210721.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1250405&view=ms.vss-test-web.build-test-results-tab&runId=37128392&paneView=debug&resultId=104314)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop

```
**Error message:**
```
System.InvalidOperationException : Cannot start service '5ef601a2-59c3-45ba-a7b1-38817a25113d' on computer '.'.
---- System.ComponentModel.Win32Exception : The service did not respond to the start or control request in a timely fashion.


Stack trace
   at System.ServiceProcess.ServiceController.Start(String[] args) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 898
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 92
----- Inner Stack Trace -----
```

**Comment by danmoseley** [comment]
ERROR_SERVICE_REQUEST_TIMEOUT = "The process for the service was started, but it did not call StartServiceCtrlDispatcher, or the thread that called StartServiceCtrlDispatcher may be blocked in a control handler function."

Either the test service is not properly installed, or broken, or just slow. Always on Windows 8.1 (and above on 7) suggesting the OS is relevant.

Failed 8 times in July.


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-120d)
| where Result == "Fail"
| where  Method == "TestOnStartWithArgsThenStop"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,
  Duration,
Build = tostring(parse_json(Properties).BuildNumber) 
```

|Pipeline|Pipeline_Configuration|OS|Arch|Test|Result|Finished|Duration|Build|
|---|---|---|---|---|---|---|---|---|
|runtime-libraries-coreclr outerloop-windows|Release|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-06-20 11:56:56.1620000|1.997|20210620.2|
|runtime-libraries-coreclr outerloop|Release|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-01 12:20:19.5170000|1.8|20210701.3|
|runtime-libraries-coreclr outerloop|Debug|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-02 16:10:48.5990000|2.877|20210702.8|
|runtime-libraries-coreclr outerloop|Debug|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-07 16:24:50.9200000|2.466|20210707.6|
|runtime-libraries-coreclr outerloop|Release|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-21 12:09:18.7490000|2.563|20210721.3|
|runtime-libraries-coreclr outerloop|Debug|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-21 18:13:39.5820000|2.673|20210721.8|
|runtime-libraries-coreclr outerloop-windows|Release|windows.81.amd64.open.svc|x64|test/functional/cli/outerloop/|Fail|2021-07-22 12:14:32.2950000|2.21|20210722.2|
|runtime-libraries-coreclr outerloop-windows|Release|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-27 12:33:17.5990000|1.593|20210727.3|
|runtime-libraries-coreclr outerloop|Release|windows.81.amd64.open.rt|x64|test/functional/cli/outerloop/|Fail|2021-07-31 12:19:32.8580000|1.944|20210731.6|


Likely OS flakiness we can do little about. My only idea is some try/catch retries in the test around StartService(..)

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20211013.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1417592&view=ms.vss-test-web.build-test-results-tab&runId=41064452&paneView=debug&resultId=104257)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop

```
**Error message:**
```
System.InvalidOperationException : Cannot start service 'cc6282cd-15bc-4a98-bc3d-d7a965a8a0f9' on computer '.'.
---- System.ComponentModel.Win32Exception : The service did not respond to the start or control request in a timely fashion.


Stack trace
   at System.ServiceProcess.ServiceController.Start(String[] args) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 898
   at System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartWithArgsThenStop() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 92
----- Inner Stack Trace -----
```

**Comment by danmoseley** [comment]
It's failing once every 10 days per the query above. Always on Windows 8.1. 

It's only failing this way in TestOnStartWithArgsThenStop, and that's because that's the only test that causes TestService.OnStart to write to the pipe back to the test. It's not clear why that's problematic on Win 8.1. I don't think it's worth analyzing, given it's very likely a test issue and we're covered on newer OS. I'll disable on Win 7/8.
