### ISSUE TITLE
[Mono][Test] Wasm-AOT runtime tests failing with Running wasm-aot libraries tests if failing locally with `System.InvalidOperationException: Sequence contains more than one element.`

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#49717]
Running wasm-aot libraries tests if failing locally with `System.InvalidOperationException: Sequence contains more than one element.` (full error message and stack trace below). This seem to happen with all libraries tests.

Tests runtime was built using:

```
./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/tests.proj 
```

Command to run tests:

```
 ./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true  /p:WasmNativeStrip=false /p:WasmNativeDebug=true 
 src/libraries/System.ComponentModel.TypeConverter/tests/
 ```

Output:

```
 XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/naricc/workspace/runtime-wasm-lib-test/artifacts/bin/System.ComponentModel.TypeConverter.Tests/net6.0-Debug/browser-wasm/AppBundle/xharness-output -- --run WasmTestRunner.dll System.ComponentModel.TypeConverter.Tests.dll -notrait category=OuterLoop -notrait category=failing
  info: 15:18:18.5334530 Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.ComponentModel.TypeConverter.Tests.dll -notrait category=OuterLoop -notrait category=failing
        
        
  fail: 15:18:19.4135220 console.error: System.AggregateException: AggregateException_ctor_DefaultMessage (Sequence contains more than one element)
        
  fail: 15:18:19.4138440  ---> System.InvalidOperationException: Sequence contains more than one element
        
  fail: 15:18:19.4138720 
        
  fail: 15:18:19.4138810    Exception_EndOfInnerExceptionStack
        
  fail: 15:18:19.4139410 console.error: program exited (with status: 1), but EXIT_RUNTIME is not set, so halting execution but not exiting the runtime or preventing further async execution (build with EXIT_RUNTIME=1, if you want a true shutdown)
        
  info: console.info: Arguments: --run,WasmTestRunner.dll,System.ComponentModel.TypeConverter.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: console.info: Initializing.....
  info: Assembly-level test framework attribute was not decorated with [TestFrameworkDiscoverer]
  info: Throw stacktrace:
  info: 
  info: Error
  info:     at 171549 (dotnet.js:1599:32)
  info:     at _emscripten_asm_const_int (dotnet.js:5983:31)
  info:     at mono_llvm_cpp_throw_exception (<anonymous>:wasm-function[6363]:0x18c453)
  info:     at throw_exception (<anonymous>:wasm-function[5795]:0x170757)
  info:     at mono_llvm_throw_exception (<anonymous>:wasm-function[5751]:0x16bfbc)
  info:     at System_Linq_System_Linq_ThrowHelper_ThrowMoreThanOneElementException (<anonymous>:wasm-function[55516]:0xf1b978)
  info:     at System_Linq_System_Linq_Enumerable_SingleOrDefault_TSource_REF_System_Collections_Generic_IEnumerable_1_TSource_REF (<anonymous>:wasm-function[55519]:0xf1cc9b)
  info:     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkDiscoverer__ctor_Xunit_Abstractions_IAssemblyInfo_Xunit_Abstractions_ISourceInformationProvider_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IXunitTestCollectionFactory (<anonymous>:wasm-function[34640]:0x8dfa0b)
  info:     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFramework_CreateDiscoverer_Xunit_Abstractions_IAssemblyInfo (<anonymous>:wasm-function[34639]:0x8df82f)
  info:     at xunit_execution_dotnet_Xunit_Sdk_TestFramework_GetDiscoverer_Xunit_Abstractions_IAssemblyInfo (<anonymous>:wasm-function[34500]:0x8cb163)
  info:     at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkProxy_GetDiscoverer_Xunit_Abstractions_IAssemblyInfo (<anonymous>:wasm-function[34541]:0x8ce8ea)
  info:     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2Discoverer__ctor_Xunit_AppDomainSupport_Xunit_Abstractions_ISourceInformationProvider_Xunit_Abstractions_IAssemblyInfo_string_string_string_bool_string_Xunit_Abstractions_IMessageSink_bool (<anonymous>:wasm-function[33647]:0x84be9c)
  info:     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2Discoverer__ctor_Xunit_AppDomainSupport_Xunit_Abstractions_ISourceInformationProvider_string_string_bool_string_Xunit_Abstractions_IMessageSink_bool (<anonymous>:wasm-function[33641]:0x84add7)
  info:     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2__ctor_Xunit_AppDomainSupport_Xunit_Abstractions_ISourceInformationProvider_string_string_bool_string_Xunit_Abstractions_IMessageSink_bool (<anonymous>:wasm-function[33640]:0x84ab25)
  info:     at invoke_viiiiiiiiii (dotnet.js:11864:25)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[64882]:0x129f973)
  info:     at invoke_vii (dotnet.js:11666:25)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[64920]:0x12a9ca8)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[64868]:0x129e705)
  info:     at invoke_iiiiii (dotnet.js:11721:32)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[64903]:0x12a69d6)
  info:     at invoke_vii (dotnet.js:11666:25)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[64930]:0x12aa756)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[64900]:0x12a3922)
  info:     at invoke_iii (dotnet.js:11655:32)
  info:     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[36199]:0x973902)
  info:     at invoke_vii (dotnet.js:11666:25)
  info:     at corlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_REF_TStateMachine_REF_ (<anonymous>:wasm-function[45343]:0xc13eff)
  info:     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[36194]:0x971bca)
  info:     at aot_instances_aot_wrapper_gsharedvt_out_sig_obj_obj (<anonymous>:wasm-function[19876]:0x3bfa6a)
  info:     at invoke_viii (dotnet.js:11710:25)
  info:     at aot_instances_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[20388]:0x3dbcf6)
  info:     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[5398]:0x1536cb)
  info:     at mono_jit_runtime_invoke (<anonymous>:wasm-function[5377]:0x15190a)
  info:     at do_runtime_invoke (<anonymous>:wasm-function[2467]:0xc0c4e)
  info:     at mono_runtime_try_invoke (<anonymous>:wasm-function[2483]:0xc17d5)
  info:     at mono_runtime_invoke (<anonymous>:wasm-function[2545]:0xc5786)
  info:     at mono_wasm_invoke_method (<anonymous>:wasm-function[65878]:0x1323510)
  info:     at dotnet.js:1431:22
  info:     at ccall (dotnet.js:645:18)
  info:     at Object.invoke_method (dotnet.js:657:12)
  info:     at Object._call_method_with_converted_args (dotnet.js:9483:30)
  info:     at Object.call_method (dotnet.js:9443:18)
  info:     at dotnet.js:9702:29
  info:     at Object.call_assembly_entry_point (dotnet.js:9709:66)
  info:     at Object.init (runtime.js:355:24)
  info:     at Object.config.loaded_cb (runtime.js:241:8)
  info:     at Object._finalize_startup (dotnet.js:7662:11)
  info:     at onPendingRequestComplete (dotnet.js:7699:14)
  info:     at processFetchResponseBuffer (dotnet.js:7714:8)
  info: Throw stacktrace:
  info: 
  info: Error
  info:     at 171549 (dotnet.js:1599:32)
  info:     at _emscripten_asm_const_int (dotnet.js:5983:31)
  info:     at mono_llvm_cpp_throw_exception (<anonymous>:wasm-function[6363]:0x18c453)
  info:     at throw_exception (<anonymous>:wasm-function[5795]:0x170757)
  info:     at mono_llvm_throw_exception (<anonymous>:wasm-function[5751]:0x16bfbc)
  info:     at corlib_System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw (<anonymous>:wasm-function[41776]:0xb29ea5)
  info:     at corlib_System_Runtime_CompilerServices_TaskAwaiter_ThrowForNonSuccess_System_Threading_Tasks_Task (<anonymous>:wasm-function[46222]:0xc50114)
  info:     at corlib_System_Runtime_CompilerServices_TaskAwaiter_HandleNonSuccessAndDebuggerNotification_System_Threading_Tasks_Task (<anonymous>:wasm-function[46221]:0xc4fefa)
  info:     at corlib_System_Runtime_CompilerServices_TaskAwaiter_ValidateEnd_System_Threading_Tasks_Task (<anonymous>:wasm-function[45867]:0xc3f8b6)
  info:     at aot_instances_System_Runtime_CompilerServices_TaskAwaiter_1_TResult_INT_GetResult (<anonymous>:wasm-function[16935]:0x317b0c)
  info:     at invoke_iii (dotnet.js:11655:32)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[64903]:0x12a6d94)
  info:     at invoke_vii (dotnet.js:11666:25)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[64930]:0x12aa756)
  info:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[64900]:0x12a3922)
  info:     at invoke_iii (dotnet.js:11655:32)
  info:     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[36199]:0x973902)
  info:     at invoke_vii (dotnet.js:11666:25)
  info:     at corlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_REF_TStateMachine_REF_ (<anonymous>:wasm-function[45343]:0xc13eff)
  info:     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[36194]:0x971bca)
  info:     at aot_instances_aot_wrapper_gsharedvt_out_sig_obj_obj (<anonymous>:wasm-function[19876]:0x3bfa6a)
  info:     at invoke_viii (dotnet.js:11710:25)
  info:     at aot_instances_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[20388]:0x3dbcf6)
  info:     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[5398]:0x1536cb)
  info:     at mono_jit_runtime_invoke (<anonymous>:wasm-function[5377]:0x15190a)
  info:     at do_runtime_invoke (<anonymous>:wasm-function[2467]:0xc0c4e)
  info:     at mono_runtime_try_invoke (<anonymous>:wasm-function[2483]:0xc17d5)
  info:     at mono_runtime_invoke (<anonymous>:wasm-function[2545]:0xc5786)
  info:     at mono_wasm_invoke_method (<anonymous>:wasm-function[65878]:0x1323510)
  info:     at dotnet.js:1431:22
  info:     at ccall (dotnet.js:645:18)
  info:     at Object.invoke_method (dotnet.js:657:12)
  info:     at Object._call_method_with_converted_args (dotnet.js:9483:30)
  info:     at Object.call_method (dotnet.js:9443:18)
  info:     at dotnet.js:9702:29
  info:     at Object.call_assembly_entry_point (dotnet.js:9709:66)
  info:     at Object.init (runtime.js:355:24)
  info:     at Object.config.loaded_cb (runtime.js:241:8)
  info:     at Object._finalize_startup (dotnet.js:7662:11)
  info:     at onPendingRequestComplete (dotnet.js:7699:14)
  info:     at processFetchResponseBuffer (dotnet.js:7714:8)
  info: Throw stacktrace:
  info: 
  info: Error
  info:     at 171549 (dotnet.js:1599:32)
  info:     at _emscripten_asm_const_int (dotnet.js:5983:31)
  info:     at mono_llvm_cpp_throw_exception (<anonymous>:wasm-function[6363]:0x18c453)
  info:     at throw_exception (<anonymous>:wasm-function[5795]:0x170757)
  info:     at mono_llvm_throw_exception (<anonymous>:wasm-function[5751]:0x16bfbc)
  info:     at corlib_System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw (<anonymous>:wasm-function[41776]:0xb29ea5)
  info:     at corlib_System_Runtime_CompilerServices_TaskAwaiter_ThrowForNonSuccess_System_Threading_Tasks_Task (<anonymous>:wasm-function[46222]:0xc50114)
  info:     at corlib_System_Runtime_CompilerServices_TaskAwaiter_HandleNonSuccessAndDebuggerNotification_System_Threading_Tasks_Task (<anonymous>:wasm-function[46221]:0xc4fefa)
  info:     at corlib_System_Runtime_CompilerServices_TaskAwaiter_ValidateEnd_System_Threading_Tasks_Task (<anonymous>:wasm-function[45867]:0xc3f8b6)
  info:     at aot_instances_System_Runtime_CompilerServices_TaskAwaiter_1_TResult_INT_GetResult (<anonymous>:wasm-function[16935]:0x317b0c)
  info:     at invoke_iii (dotnet.js:11655:32)
  info:     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[36199]:0x97505b)
  info:     at invoke_vii (dotnet.js:11666:25)
  info:     at corlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_REF_TStateMachine_REF_ (<anonymous>:wasm-function[45343]:0xc13eff)
  info:     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[36194]:0x971bca)
  info:     at aot_instances_aot_wrapper_gsharedvt_out_sig_obj_obj (<anonymous>:wasm-function[19876]:0x3bfa6a)
  info:     at invoke_viii (dotnet.js:11710:25)
  info:     at aot_instances_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[20388]:0x3dbcf6)
  info:     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[5398]:0x1536cb)
  info:     at mono_jit_runtime_invoke (<anonymous>:wasm-function[5377]:0x15190a)
  info:     at do_runtime_invoke (<anonymous>:wasm-function[2467]:0xc0c4e)
  info:     at mono_runtime_try_invoke (<anonymous>:wasm-function[2483]:0xc17d5)
  info:     at mono_runtime_invoke (<anonymous>:wasm-function[2545]:0xc5786)
  info:     at mono_wasm_invoke_method (<anonymous>:wasm-function[65878]:0x1323510)
  info:     at dotnet.js:1431:22
  info:     at ccall (dotnet.js:645:18)
  info:     at Object.invoke_method (dotnet.js:657:12)
  info:     at Object._call_method_with_converted_args (dotnet.js:9483:30)
  info:     at Object.call_method (dotnet.js:9443:18)
  info:     at dotnet.js:9702:29
  info:     at Object.call_assembly_entry_point (dotnet.js:9709:66)
  info:     at Object.init (runtime.js:355:24)
  info:     at Object.config.loaded_cb (runtime.js:241:8)
  info:     at Object._finalize_startup (dotnet.js:7662:11)
  info:     at onPendingRequestComplete (dotnet.js:7699:14)
  info:     at processFetchResponseBuffer (dotnet.js:7714:8)
  info: 15:18:19.5156760 Process v8 exited with 1
        
  fail: Application has finished with exit code 1 but 0 was expected
  XHarness exit code: 71 (GENERAL_FAILURE)
  XHarness artifacts: /Users/naricc/workspace/runtime-wasm-lib-test/artifacts/bin/System.ComponentModel.TypeConverter.Tests/net6.0-Debug/browser-wasm/AppBundle/xharness-output
/Users/naricc/workspace/runtime-wasm-lib-test/eng/testing/tests.targets(117,5): error : One or more tests failed while running tests from 'System.ComponentModel.TypeConverter.Tests'. [/Users/naricc/workspace/runtime-wasm-lib-test/src/libraries/System.ComponentModel.TypeConverter/tests/System.ComponentModel.TypeConverter.Tests.csproj]

Build FAILED.

/Users/naricc/workspace/runtime-wasm-lib-test/eng/testing/tests.targets(117,5): error : One or more tests failed while running tests from 'System.ComponentModel.TypeConverter.Tests'. [/Users/naricc/workspace/runtime-wasm-lib-test/src/libraries/System.ComponentModel.TypeConverter/tests/System.ComponentModel.TypeConverter.Tests.csproj]
    0 Warning(s)
    1 Error(s)
```

**Comment by naricc** [comment]
@mdh1418 I couldn't find an existing issue for this, so I created one.

**Comment by naricc** [comment]
After tracing this a while, it seems like this is the not very helpful error message you get from XUnit if you supply an incompatible list of attributes: https://github.com/xunit/xunit/blob/5d00c2d668705b0f9303a124e0f8c8471e5f1e93/src/xunit.v3.core/Sdk/v3/Framework/XunitTestFrameworkDiscoverer.cs#L40

 I am not sure where we are adding these attributes so that every, or most  tests, are effected though.

**Comment by tqiu8** [comment]
This issue seems to happen after #49538 was merged.

**Comment by naricc** [comment]
Fixed.
