### ISSUE TITLE
Regressions in loader on Mono x64 OSX

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#49773]
### Description

```
  Starting:    Loader.regressions.XUnitWrapper
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.Stack`1.Enumerator.MoveNext()
   at Xunit.Sdk.DisposalTracker.Dispose() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\DisposalTracker.cs:line 26
   at Xunit.Sdk.ExtensibilityPointFactory.Dispose() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs:line 53
   at Xunit.Sdk.TestFramework.Dispose() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 52
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
/tmp/helix/working/B7460A0A/p/scripts/02456cd7950e423588d4afed82b0ac6d/execute.sh: line 13:  3446 Abort trap: 6           (core dumped) 
```

Happens on both interp and normal runs:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-00cb61dfba1546df93/PayloadGroup0/console.04093ffc.log
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-691b300e8557478eab/PayloadGroup0/console.76d387e4.log

**Comment by directhex** [comment]
Apparently this is a duplicate of https://github.com/dotnet/runtime/issues/11063
