### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.PostAsync_RedirectWith307_LargePayload(remoteServer: (BaseUri: https://corefx-net-http11.azurewebsites.net/, HttpVersion: 1.1))

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49849]
Run: [runtime-libraries-coreclr outerloop 20210318.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1045261&view=ms.vss-test-web.build-test-results-tab&runId=32342982&resultId=103865&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open
 -System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.PostAsync_RedirectWith307_LargePayload(remoteServer: (BaseUri: https://corefx-net-http11.azurewebsites.net/, HttpVersion: 1.1))
```

**Error message:**
```
System.Net.Http.HttpRequestException : Resource temporarily unavailable (corefx-net-http11.azurewebsites.net:443)
---- System.Net.Sockets.SocketException : Resource temporarily unavailable

Stack trace
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1337
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1281
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1350
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 539
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 850
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.Http.Functional.Tests.HttpClientHandlerTestBase.VersionCheckerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTestBase.cs:line 125
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.PostAsync_Redirect_LargePayload_Helper(RemoteServer remoteServer, Int32 statusCode, Boolean expectRedirectToPost) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.RemoteServer.cs:line 675
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.PostAsync_RedirectWith307_LargePayload(RemoteServer remoteServer) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.RemoteServer.cs:line 639
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1233
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1175
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|271_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 138
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1337

```

**Comment by karelz** [comment]
Triage: Looks like remote server temporary hiccup, no signs in CI report of more problems. Closing.
