### ISSUE TITLE
CancellationTokenSource.CancelAfter may cause unhandled InvalidOperationException

### ISSUE THREAD

**Issue by ccruden-shookiot** [dotnet/runtime#49896]
I'm not sure if this is the right place to be posting this, so please let me know if there is a better option....

Under certain circumstances, creating a linked token source where one of the tokens is canceled on a timer seems to cause unhandled InvalidOperationExceptions when the timer eventually fires. Stack trace from Event Viewer:
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
at System.Threading.Tasks.TaskCompletionSource`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetCanceled()
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.CancellationCallbackInfo.ExecuteCallback()
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)

Exception Info: System.AggregateException
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean)
at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate(System.Object)
at System.Threading.CancellationCallbackInfo.ExecuteCallback()
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)

Exception Info: System.AggregateException
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean)
at System.Threading.CancellationTokenSource.LinkedTokenCancelDelegate(System.Object)
at System.Threading.CancellationCallbackInfo.ExecuteCallback()
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)

Exception Info: System.AggregateException
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean)
at System.Threading.CancellationTokenSource.TimerCallbackLogic(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.TimerQueueTimer.CallCallback()
at System.Threading.TimerQueueTimer.Fire()
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()

This seems to arise from the following segment of code:

`
try
{
    using (AsyncServerStreamingCall<TNotification> call = Subscribe())
    {
        while (true)
        {
            using (CancellationTokenSource pingTimer = new CancellationTokenSource())
            {
                using (CancellationTokenSource responseToken = CancellationTokenSource.CreateLinkedTokenSource(pingTimer.Token, token))
                {
                    pingTimer.CancelAfter(MaxTimeBetweenPings);
                    if (await call.ResponseStream.MoveNext(responseToken.Token))
                    {
                        TNotification notification = call.ResponseStream.Current;
                        if (!IsPing(notification))
                        {
                            NotificationHandler?.Invoke(notification);
                        }
                    }
                    else
                    {
                        break;
                    }
                }
            }
        }
    }
}
catch (RpcException ex)
{
  // handle RPC exceptions
}
catch (Exception e)
{
  // handle unexpected exceptions
}
`

(The code formatter doesn't seem to want to do indents or line returns....)

**Comment by stephentoub** [comment]
This looks like an exception on .NET Framework.  This repo is for .NET Core.  Are you hitting the same issue on .NET Core?

Thanks.

**Comment by ccruden-uptake** [comment]
The program is .NET Framework, but the assembly containing the above code is .NET standard 2.0 - not sure if that makes a difference or not.... If it's still a .NET Framework issue, where should I be posting this? I didn't see anything in the list of projects on github.com/dotnet that screamed .NET Framework, but there were a lot of them and I may have missed it....

**Comment by stephentoub** [comment]
There's no dotnet/* repo for the .NET Framework as it's not open source.  You can submit bug reports at https://developercommunity.visualstudio.com/report?space=61&entry=problem.

That said, this doesn't look like a bug in CancellationTokenSource to me.  The call stack you shared shows:
```
Exception Info: System.InvalidOperationException
at System.Threading.Tasks.TaskCompletionSource`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetCanceled()
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.CancellationCallbackInfo.ExecuteCallback()
at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean)
```
which highlights that the exception is coming from a handler that was registered with the CancellationToken, e.g. something called `cancellationToken.Register(() => ...)` and the code in that delegate ended up throwing an exception.  It looks like something registered a callback that tried to call SetCanceled on an already completed TaskCompletionSource, such that SetCanceled is then (correctly) throwing an exception.  In your example with `call.ResponseStream.MoveNext(responseToken.Token)`, I don't know what call.ResponseStream.MoveNext is here, but most likely it has a race condition / bug that's causing this problem.

**Comment by jeffschwMSFT** [comment]
Please link the dev community item back to this issue, if @stephentoub's recommendation did not help.

**Comment by ccruden-uptake** [comment]
There is a race condition in ResponseStream.MoveNext. (Issue here https://github.com/cyanfish/grpc-dotnet-namedpipes/issues/20) I'm confused as to why it would show up in one stack trace and not another though....

**Comment by stephentoub** [comment]
> I'm confused as to why the stack trace would be that different for the same underlying cause though....

That issue says it's running on .NET 5, whereas this one is .NET Framework.  There are non-trivial differences between the runtimes that could lead to differences in the reported stack traces.

**Comment by ccruden-uptake** [comment]
Fair enough. Thanks for the help!
