### ISSUE TITLE
GetLinuxNetworkInterfaces crash if /proc/net/route inaccessible

### ISSUE THREAD

**Issue by uumas** [dotnet/runtime#49946]
### Description

If the user running a dotnet application doesn't have permission to read `/proc/net/route`, and the application calls GetLinuxNetworkInterfaces, it crashes. One application where this is reproducible is Jellyfin, issue at jellyfin/jellyfin#5571

### Configuration

.NET 5.0.3
Linux (Debian x86_64 but should make no difference)

### Crash log

```
System.UnauthorizedAccessException: Access to the path '/proc/net/route' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at System.Net.NetworkInformation.LinuxNetworkInterface.LinuxNetworkInterfaceSystemProperties..ctor()
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
```

### Other information

[GetLinuxNetworkInterfaces](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L23) seems to check if the file exists before trying to read it but it doesn't check if it actually is allowed to be read. A workaround is to remove permissions from the directory /proc/net so .NET can't validate the file's existence and it just skips the file. A simple solution would be to just add another if statement to check if the file can be read. Or catch the UnauthorizedAccessException.

**Comment by ManickaP** [comment]
Triage: we should look into this problem in general, potentially make the properties lazy. In the meantime, we should try to fix this for 6.0, e.g. simple try-catch.

**Comment by karelz** [comment]
BTW: I looked into the option to make the properties lazy, but they are read early on from constructors anyway, so it would require much larger redesign of a few related classes -- not sure if it is worth it even after we address the specific problem.
