### ISSUE TITLE
AddAzureWebAppDiagnostics throws an exception if used in combination with azure webapp zip deploy

### ISSUE THREAD

**Issue by saithis** [dotnet/runtime#50034]
# Describe the bug
AddAzureWebAppDiagnostics throws an exception if used in combination with azure webapp zip deploy.
There is no exception if we deploy the code with Visual Studio (no zip deploy).

### To Reproduce
1. Using version '3.0.0' of package 'Microsoft.Extensions.Logging.AzureAppServices'
2. Run this code:
```
        private static readonly LoggerProviderCollection LoggerProvider = new LoggerProviderCollection();

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    .UseSerilog(providers: LoggerProvider)
                    .ConfigureLogging(config =>
                    {
                        config.ClearProviders();
                        config.SetMinimumLevel(LogLevel.Trace);
                        config.AddAzureWebAppDiagnostics();
                    })
                    .UseStartup<Startup>();
                });
```
3. Deploy to Azure with Zip Deployment/WEBSITE_RUN_FROM_PACKAGE: 1
4. See error:

> System.IO.FileNotFoundException: Error reading the D:\home\site\diagnostics\ directory.
>    at System.IO.FileSystemWatcher.StartRaisingEvents()
>    at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
>    at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
>    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
>    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
>    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
>    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
>    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Microsoft.Extensions.Logging.AzureAppServices.SiteConfigurationProvider.GetAzureLoggingConfiguration(IWebAppContext context)
>    at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggingBuilder builder, IWebAppContext context)
>    at Microsoft.Extensions.Logging.AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics(ILoggingBuilder builder)
>    at Prosoft.Tenant.Api.Program.<>c.<CreateHostBuilder>b__1_2(ILoggingBuilder config) in C:\j\ws\Recruiting\prosoft-recruiting-qa\Prosoft.Tenant.Api\Program.cs:line 66
>    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureLogging>b__0(IServiceCollection collection)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureServices>b__0(WebHostBuilderContext context, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(HostBuilderContext context, IServiceCollection builder)
>    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()

### Expected behavior
It should find and be able to read the D:\home\site\diagnostics\settings.json, as it is definitelly there.

### Additional context
We use AspNetCoreModuleV2 with InProcess hosting and .NET Core 3.0

**Comment by ZenwalkerD** [comment]
Hi What is the solution this?

We are also facing the same issue in Azure App Service. 
Dotnet 5 is being used.

**Comment by asilverstein** [comment]
We are also experiencing the same exact error as described. 

The only solution for us was to change (in web.config) AspNetCoreModuleV2 to AspNetCoreModule. 

We don't think this is a good solution, since (I believe) it takes us out of process, although it works.

Please advise.

**Comment by saithis** [comment]
Unfortunately we never found a solution and stopped using azure web app diagnostics.

**Comment by ZenwalkerD** [comment]
> 
> 
> Unfortunately we never found a solution and stopped using azure web app diagnostics.

Then how are you analyzing the app logs? Diagnostics is for debugging of app right?

**Comment by saithis** [comment]
We use Serilog to log to a different place now.

**Comment by eerhardt** [comment]
Since the [`AzureAppServicesLoggerFactoryExtensions.AddAzureWebAppDiagnostics` code](https://github.com/dotnet/aspnetcore/blob/406a536267f7104e4f203e1bd60167609fad5869/src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs#L26) is in `dotnet/aspnetcore`, I am transferring this issue to that repo.
