### ISSUE TITLE
Test failure System.Net.Sockets.Tests.ConnectCancellableTask.ConnectMultiAddressAndPort_CancelDuringConnect_Throws

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50152]
Run: [runtime-libraries-coreclr outerloop 20210323.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1052244&view=ms.vss-test-web.build-test-results-tab&runId=32498398&resultId=103989&paneView=debug)

Failed tests:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
 -System.Net.Sockets.Tests.ConnectCancellableTask.ConnectMultiAddressAndPort_CancelDuringConnect_Throws
 -System.Net.Sockets.Tests.ConnectCancellableTask.ConnectAddressAndPort_CancelDuringConnect_Throws
 -System.Net.Sockets.Tests.ConnectCancellableTask.ConnectEndPoint_CancelDuringConnect_Throws
```

**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Net.Sockets.SocketException): A socket operation was attempted to an unreachable host.
---- System.Net.Sockets.SocketException : A socket operation was attempted to an unreachable host.


Stack trace
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1236
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1175
   at System.Net.Sockets.Tests.ConnectCancellableTask.<>c__DisplayClass5_0.<<ConnectEndPoint_CancelDuringConnect_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs:line 286
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1236
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1175
   at System.Net.Sockets.Tests.ConnectCancellableTask.<>c__DisplayClass5_0.<<ConnectEndPoint_CancelDuringConnect_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs:line 286
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
This is the only failure between 2/23-5/10 (incl. PRs).
Closing due to low frequency (<= 1 per month).
