### ISSUE TITLE
macOS: System.Diagnostics.Process fails to obtain certain information about select system processes

### ISSUE THREAD

**Issue by mklement0** [dotnet/runtime#50207]
### Description

On macOS, the following two system processes _may_ be running on a given system:

* `/usr/libexec/firmwarecheckers/ethcheck/ethcheck`
* `/usr/sbin/cupsd`

Their file modes are unusual - `-rwx--x--x` and `-r-x------` respectively. That is, they deny _read_ access to everyone but the root user.

Presumably that is the reason that `System.Diagnostics.Process` fails to obtain the process _name_ and fails to populate the modules' `Modules` `.FileInfoVersion` property, whereas `.FileName` _does_ work.

```csharp
int pid = ??; // IMPORTANT: Substitute one of the PIDs reported by `pgrep cupsd ethcheck` in a shell here:
var p = System.Diagnostics.Process.GetProcessById(pid);
Console.WriteLine($"Name: {p.ProcessName}");
foreach (System.Diagnostics.ProcessModule m in p.Modules)
{ 
  Console.WriteLine(m.FileName);
  Console.WriteLine(m.FileVersionInfo.FileName);
}
```

Note: These processes aren't necessarily running on _all_ macOS systems.

With `pid` set to the value of `pgrep ethcheck`, for instance, the **expected output** is:

```
Name: ethcheck
/usr/libexec/firmwarecheckers/ethcheck/ethcheck
/usr/libexec/firmwarecheckers/ethcheck/ethcheck
```

The **actual output** is:

```
Name: 
/usr/libexec/firmwarecheckers/ethcheck/ethcheck
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/usr/libexec/firmwarecheckers/ethcheck/ethcheck' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Diagnostics.FileVersionInfo.TryLoadManagedAssemblyMetadata()
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at System.Diagnostics.ProcessModule.get_FileVersionInfo()
   at demo.ConsoleApp.Main(String[] args) in /Users/.../Program.cs:line 74
```

That is, `.ProcessName` quietly returned `""` (the empty string), and accessing a module's `.FileVersionInfo.FileName` property caused an access-denied exception.

Note: When run with `sudo` , the behavior is as expected, but _this shouldn't be required_, given that standard utilities such as `pgrep` and `ps` can access this information without it.

### Configuration

.NET 6.0.100-preview.2.21155.3 on macOS 10.15.7 (Catalina)

### Regression?

No.

**Comment by danmoseley** [comment]
Do I understand correctly, that ProcessName ought to be able to work (returning the file name) even if no information about the process itself can be read? Or are you expecting that more should work than ProcessName?

**Comment by mklement0** [comment]
Yes, `.ProcessName` should work, and so should  `.FileName` and `.FileVersionInfo.FileName` on the elements of the `.Modules` collection - accessing this information does _not_ require `sudo`.

This may apply to other properties too - I haven't looked.

**Comment by mklement0** [comment]
P.S.: It's an interesting question what native utilities such as `pgrep` use to determine the process name - whether they truly just use the underlying binary's _file name_ I do not know.
