### ISSUE TITLE
Test failure System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsUsingCertWithPrivateKey.DecryptUsingCertificateWithSameSubjectKeyIdentifierButDifferentKeyPair

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50222]
Run: [runtime-coreclr libraries-jitstress 20210324.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1053900&view=ms.vss-test-web.build-test-results-tab&runId=32540382&resultId=152378&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_checked-zapdisable-Ubuntu.1804.Amd64.Open
 -System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsUsingCertWithPrivateKey.DecryptUsingCertificateWithSameSubjectKeyIdentifierButDifferentKeyPair
```

**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.Security.Cryptography.CryptographicException)
Actual:   typeof(System.ArgumentException): Specified key is not a valid size for this algorithm. (Parameter 'rgbKey')
---- System.ArgumentException : Specified key is not a valid size for this algorithm. (Parameter 'rgbKey')


Stack trace
   at Internal.Cryptography.AesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting) in /_/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/AesImplementation.cs:line 55
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.DecryptContent(ReadOnlyMemory`1 encryptedContent, Byte[] cek, AlgorithmIdentifierAsn contentEncryptionAlgorithm, Exception& exception) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 173
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.TryDecryptCore(Byte[] cek, String contentType, Nullable`1 content, AlgorithmIdentifierAsn contentEncryptionAlgorithm, Exception& exception) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 108
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.TryDecrypt(RecipientInfo recipientInfo, X509Certificate2 cert, AsymmetricAlgorithm privateKey, X509Certificate2Collection originatorCerts, X509Certificate2Collection extraStore, Exception& exception) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 66
   at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 249
----- Inner Stack Trace -----
   at Internal.Cryptography.AesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting) in /_/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/AesImplementation.cs:line 55
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.DecryptContent(ReadOnlyMemory`1 encryptedContent, Byte[] cek, AlgorithmIdentifierAsn contentEncryptionAlgorithm, Exception& exception) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 173
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.TryDecryptCore(Byte[] cek, String contentType, Nullable`1 content, AlgorithmIdentifierAsn contentEncryptionAlgorithm, Exception& exception) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 108
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.ManagedDecryptorPal.TryDecrypt(RecipientInfo recipientInfo, X509Certificate2 cert, AsymmetricAlgorithm privateKey, X509Certificate2Collection originatorCerts, X509Certificate2Collection extraStore, Exception& exception) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Decrypt.cs:line 66
   at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 249
```

**Comment by bartonjs** [comment]
Ooh, interesting.

The decryption "succeeded" due to the PKCS#1 "the wrong key produces successful nonsense 1" edge case (almost perfectly 1 in 10,000 for RSA-2048), but produced an answer that was none of 16/24/32 bytes.

Rather than having ArgumentExceptions slip out in cases like this, we probably want to try/catch calls to CreateTransform and turn the ArgumentException into a CryptograhicException.
