### ISSUE TITLE
tracing.eventcounter failure on OSX arm64 Checked

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#50238]
### Description

```
  Discovering: tracing.eventcounter.XUnitWrapper
  Discovered:  tracing.eventcounter.XUnitWrapper
  Starting:    tracing.eventcounter.XUnitWrapper
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
/tmp/helix/working/BBBB0A26/p/scripts/01e90a5d37c14a03ab0b217f91138626/execute.sh: line 13: 28532 Abort trap: 6           (core dumped)
```

### Other information

https://dev.azure.com/dnceng/public/_build/results?buildId=1047249&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1055598&view=results

**Comment by stephentoub** [comment]
From the ExecutionContext-related code, I don't see how this is possible.  Seems likely there's something in the codegen or runtime impacting this.

**Comment by directhex** [comment]
I never said it was _possible_, just that it's happening. Sometimes I believe in as many as six impossible things before breakfast.

**Comment by stephentoub** [comment]
I believe it happened.  I was providing context as to where I thought the source of the problem may be.

**Comment by directhex** [comment]
Well, test disable PR is https://github.com/dotnet/runtime/pull/50241

**Comment by stephentoub** [comment]
> Well, test disable PR is 50241

I suspect this issue is not related to this specific test.

**Comment by mangod9** [comment]
Adding @sdmaclea and @sandreenko since this is osx arm64.

**Comment by BruceForstall** [comment]
@sdmaclea @sandreenko I see more cases of this:

https://dev.azure.com/dnceng/public/_build/results?buildId=1069983&view=ms.vss-test-web.build-test-results-tab&runId=32893724&resultId=108661&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

https://dev.azure.com/dnceng/public/_build/results?buildId=1069331&view=ms.vss-test-web.build-test-results-tab&runId=32877370&resultId=108661&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Can we merge https://github.com/dotnet/runtime/pull/50241 for now?

**Comment by sandreenko** [comment]
@BruceForstall sure, it makes sense.
