### ISSUE TITLE
SyncHttpHandlerTest_AutoRedirect.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection failed with "Socket is already connected" on macOS

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#50271]
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50230-merge-001f2684f6144ecaac/System.Net.Http.Functional.Tests/console.c778e7cf.log?sv=2019-07-07&se=2021-04-15T01%3A15%3A45Z&sr=c&sp=rl&sig=M0kFthVtZmPCi23KZh4STObky%2Fv0HtrR3KJ%2BnXYQ0SE%3D
```
Console log: 'System.Net.Http.Functional.Tests' from job 001f2684-f614-4eca-acaf-190a6925c1e3 workitem 53c7e055-cce0-41f4-832f-b6c8535dbd1f (osx.1014.amd64.open) executed on machine dci-mac-build-150
...
    System.Net.Http.Functional.Tests.SyncHttpHandlerTest_AutoRedirect.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(statusCode: 308, oldMethod: "HEAD", newMethod: "HEAD") [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (Socket is already connected [::ffff:127.0.0.1]:54917 (127.0.0.1:54917))) (One or more errors occurred. (Unexpected EOF trying to read request header))
      ---- System.AggregateException : One or more errors occurred. (Socket is already connected [::ffff:127.0.0.1]:54917 (127.0.0.1:54917))
      -------- System.Net.Http.HttpRequestException : Socket is already connected [::ffff:127.0.0.1]:54917 (127.0.0.1:54917)
      ------------ System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Socket is already connected [::ffff:127.0.0.1]:54917
      ---- System.AggregateException : One or more errors occurred. (Unexpected EOF trying to read request header)
      -------- System.IO.IOException : Unexpected EOF trying to read request header
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(80,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs(117,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_AutoRedirect.<>c__DisplayClass8_2.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(72,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs(106,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_AutoRedirect.<>c__DisplayClass8_1.<<AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(72,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs(100,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_AutoRedirect.AllowAutoRedirect_True_ValidateNewMethodUsedOnRedirection(Int32 statusCode, String oldMethod, String newMethod)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1333,0): at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1239,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1341,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(526,0): at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(850,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(79,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpMessageHandlerStage.cs(15,0): at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs(522,0): at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs(294,0): at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.SocketsHttpHandler.cs(99,0): at System.Net.Http.Functional.Tests.VersionHttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs(66,0): at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(467,0): at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTestBase.cs(142,0): at System.Net.Http.Functional.Tests.HttpClientExtensions.<>c__DisplayClass0_0.<SendAsync>b__0()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs(503,0): at System.Threading.Tasks.Task`1.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2369,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(268,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(293,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2331,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(63,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3246,0): at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(869,0): at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(899,0): at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(925,0): at System.Net.Sockets.Socket.Connect(String host, Int32 port)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(855,0): at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1321,0): at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(639,0): at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync()
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(708,0): at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendResponseAsync(HttpStatusCode statusCode, String additionalHeaders, String content)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(164,0): at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass19_0.<<AcceptConnectionSendResponseAndCloseAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(124,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(162,0): at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendResponseAndCloseAsync(HttpStatusCode statusCode, String additionalHeaders, String content)
```

**Comment by karelz** [comment]
No failure in main/master branch in last 2 months: 2/23-4/23.

**Comment by karelz** [comment]
Failures during 2/23-5/10 (incl. PRs):

Date | Build / PR | OS
-- | -- | --
3/13 | PR #41097 | OSX.1015.Amd64.Open
3/26 | PR #50230 | OSX.1014.Amd64.Open
3/26 | PR #50193 | OSX.1014.Amd64.Open
5/6 | PR #52109 | OSX.1014.Amd64.Open

**Comment by ManickaP** [comment]
Doesn't fail anymore.
