### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50399]
Run: [runtime-libraries-coreclr outerloop 20210329.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1061122&view=ms.vss-test-web.build-test-results-tab&runId=32700794&resultId=103213&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
 -System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
```

**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'.


Stack trace
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
   at System.Net.Http.Functional.Tests.HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AcceptAllCerts.cs:line 101
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942
```

**Comment by karelz** [comment]
Failures: 2/23-4/23 (main/master branch only)

When | OS | Exception
-- | -- | --
2021-03-29T12:15:27.637Z | windows.10.amd64.server20h1.open.rt | System.Net.Http.HttpRequestException : An   error occurred while sending the request.\r\n----   System.Net.Http.WinHttpException : Error 12007 calling   WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not   be resolved'.

Looks like temporary DNS problem or remote server problem, closing.
