### ISSUE TITLE
FileSystemWatcher_Directory_Delete_MultipleFilters - DirectoryNotFoundException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#504]
Affected test:
- `System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters`

Runfo failures in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22system.io.tests.filesystemwatchertests.filesystemwatcher_directory_delete_multiplefilters%22) as of 2022/9/23:

Day | Run | OS
-- | -- | --
9/22 | Rolling run [25951](https://runfo.azurewebsites.net/view/build/?number=25951) (7.0) | net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open
9/20 | Rolling run [23975](https://runfo.azurewebsites.net/view/build/?number=23975) | net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open
9/20 | PR [23345](https://runfo.azurewebsites.net/view/build/?number=23345) | net7.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open
9/14 | PR [17924](https://runfo.azurewebsites.net/view/build/?number=17924) | net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
9/8 | PR [8477](https://runfo.azurewebsites.net/view/build/?number=8477) (7.0) | net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open
9/7 | PR [7334](https://runfo.azurewebsites.net/view/build/?number=7334) (7.0) | net7.0-windows-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

Kusto shows even more historical failures before September 2022:
- 1x September ... unclear why Runfo shows more failures -- digging into that
- 1x August
- 7x July
- 3x June (note: ignoring 3x unrelated failures on 6/10 in PR #70598)

```kusto
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName contains 'FileSystemWatcher_Directory_Delete_MultipleFilters'
    | distinct JobId, WorkItemId, Message, StackTrace, TestName, Arguments, Outcome
    | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
        //| where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")))
        | where Type startswith "test/functional/cli/"
            and not(Properties contains "runtime-staging")
        | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
        | project-rename JobType = Type) on JobId;
```

### Original report

https://helix.dot.net/api/2019-06-17/jobs/41287641-18f2-4a8c-945a-e37b231681dd/workitems/System.IO.FileSystem.Watcher.Tests/console

Failed on an unrelated PR: https://github.com/dotnet/runtime/pull/346

`netcoreapp-Windows_NT-Debug-x64-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open`
https://dev.azure.com/dnceng/public/_build/results?buildId=445065&view=ms.vss-test-web.build-test-results-tab&runId=14186298&paneView=debug&resultId=179779

```text
Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 2)
    System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters [FAIL]
      System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Windows\TEMP\FileSystemWatcherTests_spavgqsp.vm1\FileSystemWatcher_Directory_Delete_MultipleFilters_1021_397ed6d6\FileSystemWatcher_Directory_Delete_MultipleFilters_1022_a8b0b478'.
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs(359,0): at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs(184,0): at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs(238,0): at System.IO.DirectoryInfo.Delete()
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(1031,0): at System.IO.Tests.FileSystemWatcherTests.<>c__DisplayClass61_0.<FileSystemWatcher_Directory_Delete_MultipleFilters>b__0()
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(296,0): at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(227,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(197,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(1031,0): at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters()
Unhandled exception. Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: C:\Windows\TEMP\FileSystemWatcherTests_spavgqsp.vm1\FileSystemWatcher_Directory_Delete_MultipleFilters_1021_397ed6d6\FileSystemWatcher_Directory_Delete_MultipleFilters_1023_97128ebf
In value:  String[] ["C:\\Windows\\TEMP\\FileSystemWatcherTests_spavgqsp"...]
   at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection, IEqualityComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 114
   at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 96
   at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass10_0.<WatchDeleted>b__0(Object o, FileSystemEventArgs e) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 113
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 453
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 317
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 240
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 63
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/System.Private.CoreLib/src/System/Threading/ClrThreadPoolBoundHandleOverlapped.cs:line 50
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in /_/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs:line 63
----- end Tue 12/03/2019 16:09:30.58 ----- exit code -532462766 ----------------------------------------------------------
```

cc @JeremyKuhne, @carlossanlop 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by JeremyKuhne** [comment]
Triage: Closing. Please reopen if this gets hit in the runs again.

**Comment by jkotas** [comment]
Hit again in https://github.com/dotnet/runtime/pull/36597:

https://helix.dot.net/api/2019-06-17/jobs/068109ca-a58d-4550-b675-236f600d911f/workitems/System.IO.FileSystem.Watcher.Tests/console

```
  Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 2)
Unhandled exception. Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: C:\Windows\TEMP\FileSystemWatcherTests_pn4jj3kd.lcq\FileSystemWatcher_Directory_Delete_MultipleFilters_1022_9ca3cd01\FileSystemWatcher_Directory_Delete_MultipleFilters_1024_59beabe7
In value:  String[] ["C:\\Windows\\TEMP\\FileSystemWatcherTests_pn4jj3kd"...]
   at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection, IEqualityComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 114
   at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 95
   at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass10_0.<WatchDeleted>b__0(Object o, FileSystemEventArgs e) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 113
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 455
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 320
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 243
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__84_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 64
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs:line 63
    System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters [FAIL]
      System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Windows\TEMP\FileSystemWatcherTests_pn4jj3kd.lcq\FileSystemWatcher_Directory_Delete_MultipleFilters_1022_9ca3cd01\FileSystemWatcher_Directory_Delete_MultipleFilters_1023_a22653e7'.
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs(357,0): at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs(184,0): at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs(242,0): at System.IO.DirectoryInfo.Delete(Boolean recursive)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs(238,0): at System.IO.DirectoryInfo.Delete()
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(1032,0): at System.IO.Tests.FileSystemWatcherTests.<>c__DisplayClass61_0.<FileSystemWatcher_Directory_Delete_MultipleFilters>b__0()
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(296,0): at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(227,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(197,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(1032,0): at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters()
```

**Comment by ViktorHofer** [comment]
Hit again but on x86, not Nano:

```
C:\h\w\AE0409C4\w\B8FE09DE\e>"C:\h\w\AE0409C4\p\dotnet.exe" exec --runtimeconfig System.IO.FileSystem.Watcher.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Watcher.Tests.deps.json xunit.console.dll System.IO.FileSystem.Watcher.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.IO.FileSystem.Watcher.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Watcher.Tests (found 154 of 182 test cases)
  Starting:    System.IO.FileSystem.Watcher.Tests (parallel test collections = on, max threads = 2)
Unhandled exception. Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: C:\h\w\AE0409C4\t\FileSystemWatcherTests_gpqwq4co.yz2\FileSystemWatcher_Directory_Delete_MultipleFilters_1020_adb2e92a\FileSystemWatcher_Directory_Delete_MultipleFilters_1022_adf3317f
In value:  String[] ["C:\\h\\w\\AE0409C4\\t\\FileSystemWatcherTests_gpqw"...]
   at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection, IEqualityComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 114
   at Xunit.Assert.Contains[T](T expected, IEnumerable`1 collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 95
   at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass10_0.<WatchDeleted>b__0(Object o, FileSystemEventArgs e) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 111
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 454
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(Byte[] buffer, UInt32 numBytes) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 338
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 238
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__83_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs:line 63
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/ClrThreadPoolBoundHandleOverlapped.cs:line 48
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Overlapped.cs:line 62
    System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters [FAIL]
      System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\h\w\AE0409C4\t\FileSystemWatcherTests_gpqwq4co.yz2\FileSystemWatcher_Directory_Delete_MultipleFilters_1020_adb2e92a\FileSystemWatcher_Directory_Delete_MultipleFilters_1021_bdd83af9'.
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs(356,0): at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Windows.cs(183,0): at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs(241,0): at System.IO.DirectoryInfo.Delete(Boolean recursive)
        /_/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs(237,0): at System.IO.DirectoryInfo.Delete()
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(1030,0): at System.IO.Tests.FileSystemWatcherTests.<>c__DisplayClass61_0.<FileSystemWatcher_Directory_Delete_MultipleFilters>b__0()
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(294,0): at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(225,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(195,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(1030,0): at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters()
----- end Sat 10/10/2020  2:39:45.35 ----- exit code -532462766 ----------------------------------------------------------
```

dotnet.exe.876.dmp:
  https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43185-merge-9d968985260c47eabb/System.IO.FileSystem.Watcher.Tests/dotnet.exe.876.dmp?sv=2019-07-07&se=2020-10-30T02%3A28%3A46Z&sr=c&sp=rl&sig=KLeTePcQi43n%2Fa%2BObbo8DWx0zsuJoFWUYD0FJjQHerw%3D

console.7f00bdb8.log:
  https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43185-merge-9d968985260c47eabb/System.IO.FileSystem.Watcher.Tests/console.7f00bdb8.log?sv=2019-07-07&se=2020-10-30T02%3A28%3A46Z&sr=c&sp=rl&sig=KLeTePcQi43n%2Fa%2BObbo8DWx0zsuJoFWUYD0FJjQHerw%3D

**Comment by krwq** [comment]
This has also failed here: https://dev.azure.com/dnceng/public/_build/results?buildId=1949154&view=ms.vss-test-web.build-test-results-tab&runId=50175432&resultId=132805&paneView=debug

```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\h\w\A8CB0934\t#FileSystemWatcherTests_jqlykjpm.bh3\FileSystemWatcher_Directory_Delete_MultipleFilters_1009_swudns4x\FileSystemWatcher_Directory_Delete_MultipleFilters_1010_zg7wlds6'.

   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 436
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 261
   at System.IO.DirectoryInfo.Delete() in /_/src/libraries/System.Private.CoreLib/src/System/IO/DirectoryInfo.cs:line 223
   at System.IO.Tests.FileSystemWatcherTests.<>c__DisplayClass61_0.<FileSystemWatcher_Directory_Delete_MultipleFilters>b__0() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs:line 1019
   at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 309
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 198
   at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 168
   at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Delete_MultipleFilters() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs:line 1019
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by karelz** [comment]
It seems to happen 1x-2x per week, marking for re-triage and as blocking-clean-ci
