### ISSUE TITLE
.NET 6 preview 2 singlefile on Mac unable to find libSystem.Security.Cryptography.Native.Apple.dylib

### ISSUE THREAD

**Issue by Meowzz95** [dotnet/runtime#50543]
@VSadov 
Hi, just upgraded to preview 2, the same(well same root cause) error persists.

I've upgraded the repro repo here: https://github.com/Meowzz95/DotNet6DemoMissingLib

Command to build: ` dotnet publish -c Release --self-contained --runtime osx-x64 -p:PublishSingleFile=true`
.NET SDK version: `Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET`
macOS version: 11.2.3 (20D91) (Intel CPU)

Attached the stack trace.
```
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.DllNotFoundException: Unable to load shared library 'libSystem.Security.Cryptography.Native.Apple.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.Security.Cryptography.Native.Apple.dylib, 1): image not found
         at Interop.AppleCrypto.SslCreateContext(Int32 isServer)
         at System.Net.SafeDeleteSslContext.CreateSslContext(SafeFreeSslCredentials credential, Boolean isServer)
         at System.Net.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at DemoMissingLib.Worker.ExecuteAsync(CancellationToken stoppingToken)
         at Microsoft.Extensions.Hosting.Internal.Host.HandleBackgroundException(BackgroundService backgroundService)
```

I couldn't reopen the issue for preview 1 but I think as it is now preview 2, I should open a new one instead? If you prefer to maintain this in a single thread, please close this and reopen the below issue.
_Originally posted by @Meowzz95 in https://github.com/dotnet/runtime/issues/48801#issuecomment-811676299_

**Comment by VSadov** [comment]
Sorry for the confusion. Preview 2 was released on the same day this fix was merged. When I said "in the next preview", I meant preview3.

The fix could not possibly make it into preview2 since a preview branch is created many days before the release - to have time for extra validation and stabilization. The fix should be in the Preview3 though.

@Meowzz95  If this fix is of high importance or you want to validate that issue is really fixed, you can try a daily Preview3 build from - https://github.com/dotnet/installer

**Comment by Meowzz95** [comment]
@VSadov 
Noted with thanks, I'll close the issue!
