### ISSUE TITLE
DeflateStream doesn't work as intended

### ISSUE THREAD

**Issue by frabert** [dotnet/runtime#50560]
### Description

`DeflateStream` has difficulty inflating data which is accepted by zlib, failing with `InvalidDataException`

#### Steps to reproduce:
```c#
using System;
using System.IO;
using System.IO.Compression;

static string Decompress(byte[] data)
{
  using var ms = new MemoryStream(data);
  using var ds = new DeflateStream(ms, CompressionMode.Decompress);
  using var sr = new StreamReader(ds);
  return sr.ReadToEnd();
}

var data = Convert.FromBase64String("eJxLy89PSiwCAAirAno=");
Console.WriteLine(Decompress(data));
```

Expected output: `foobar`

Actual result: `InvalidDataException` thrown

Example nodejs code which behaves correctly:
```javascript
const zlib = require('zlib')
const buffer = Buffer.from("eJxLy89PSiwCAAirAno=", 'base64')
console.log(zlib.inflateSync(buffer).toString())
```

### Configuration
Tested on Windows 10 19042.867 x64, .NET 5.0.103

### Other information

Stack trace:

```
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
   at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at <Program>$.<<Main>$>g__Decompress|0_0(Byte[] data) in D:\repos\Factorilog\Factorilog\Program.cs:line 10
   at <Program>$.<Main>$(String[] args) in D:\repos\Factorilog\Factorilog\Program.cs:line 14
```

**Comment by stephentoub** [comment]
That payload isn't a raw deflate payload but rather is wrapped in a zlib format container.  Change "DeflateStream" to "ZLibStream" in your repro, and it then prints out "foobar" as you want it to.  ZLibStream was added in .NET 6 and exists in the .NET 6 preview builds.
