### ISSUE TITLE
System.Net.NetworkInformation.Functional.Tests fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50567]
## Several tests from System.Net.NetworkInformation.Functional.Tests fail on Android

- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.GetUnicastAddresses_NotEmpty
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets(ipv6: False)
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets(ipv6: True)
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_ExceptionIfV6NotSupported
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetNetworkInterfaces_AtLeastOne
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_MatchesLoopbackNetworkInterface
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_MatchesLoopbackNetworkInterface
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetIsNetworkAvailable_Success
- [ ] System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_ExceptionIfV4NotSupported

## The following tests failed with some form of PlatformNotSupportedException

- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1)
- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: ::1)
- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors
- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_NotListening
- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: 127.0.0.1)
- [ ] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: ::1)

Based on CI runs from https://github.com/dotnet/runtime/pull/50095

**Comment by mdh1418** [comment]
```
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1)
    System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
       at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpConnectionsFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in System.Net.NetworkInformation.dll:token 0x6000194+0x15
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpConnections() in System.Net.NetworkInformation.dll:token 0x6000242+0x0
   at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(IPAddress address) in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 95
--- End of stack trace from previous location ---
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: ::1)
    System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
       at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpConnectionsFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in System.Net.NetworkInformation.dll:token 0x6000194+0x15
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpConnections() in System.Net.NetworkInformation.dll:token 0x6000242+0x0
   at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(IPAddress address) in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 95
--- End of stack trace from previous location ---
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors
    System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
       at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpConnectionsFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in System.Net.NetworkInformation.dll:token 0x6000194+0x15
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpConnections() in System.Net.NetworkInformation.dll:token 0x6000242+0x0
   at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 34
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_NotListening
    System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
       at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpConnectionsFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in System.Net.NetworkInformation.dll:token 0x6000194+0x15
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpConnections() in System.Net.NetworkInformation.dll:token 0x6000242+0x0
   at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_NotListening() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 114
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.GetUnicastAddresses_NotEmpty
    Assert.NotEmpty() Failure
       at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.GetUnicastAddresses_NotEmpty() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 125
--- End of stack trace from previous location ---
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: 127.0.0.1)
    System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
       at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in System.Net.NetworkInformation.dll:token 0x6000195+0x15
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpListeners() in System.Net.NetworkInformation.dll:token 0x6000243+0x0
   at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(IPAddress address) in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 64
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: ::1)
    System.PlatformNotSupportedException : The information requested is unavailable on the current platform.
       at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpListenersFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in System.Net.NetworkInformation.dll:token 0x6000195+0x15
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpListeners() in System.Net.NetworkInformation.dll:token 0x6000243+0x0
   at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(IPAddress address) in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 64
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a

System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_ExceptionIfV6NotSupported
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000283+0x0
   at System.Net.NetworkInformation.NetworkInterfacePal.get_IPv6LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000282+0x0
   at System.Net.NetworkInformation.NetworkInterface.get_IPv6LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x600012b+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_ExceptionIfV6NotSupported() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 193
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetNetworkInterfaces_AtLeastOne
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000280+0x0
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000129+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetNetworkInterfaces_AtLeastOne() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 25
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets(ipv6: False)
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000283+0x0
   at System.Net.NetworkInformation.NetworkInterface.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x600012c+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets(Boolean ipv6) in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 298
--- End of stack trace from previous location ---
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets(ipv6: True)
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000283+0x0
   at System.Net.NetworkInformation.NetworkInterfacePal.get_IPv6LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000282+0x0
   at System.Net.NetworkInformation.NetworkInterface.get_IPv6LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x600012b+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.NetworkInterface_LoopbackInterfaceIndex_MatchesReceivedPackets(Boolean ipv6) in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 298
--- End of stack trace from previous location ---
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_MatchesLoopbackNetworkInterface
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000283+0x0
   at System.Net.NetworkInformation.NetworkInterface.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x600012c+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_MatchesLoopbackNetworkInterface() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 138
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_MatchesLoopbackNetworkInterface
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000283+0x0
   at System.Net.NetworkInformation.NetworkInterfacePal.get_IPv6LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000282+0x0
   at System.Net.NetworkInformation.NetworkInterface.get_IPv6LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x600012b+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_MatchesLoopbackNetworkInterface() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 170
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetIsNetworkAvailable_Success
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000280+0x0
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable() in System.Net.NetworkInformation.dll:token 0x6000281+0x0
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable() in System.Net.NetworkInformation.dll:token 0x600012a+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_GetIsNetworkAvailable_Success() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 273
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_ExceptionIfV4NotSupported
    System.Net.NetworkInformation.NetworkInformationException : No such file or directory
       at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces() in System.Net.NetworkInformation.dll:token 0x6000285+0x40
   at System.Net.NetworkInformation.NetworkInterfacePal.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x6000283+0x0
   at System.Net.NetworkInformation.NetworkInterface.get_LoopbackInterfaceIndex() in System.Net.NetworkInformation.dll:token 0x600012c+0x0
   at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticLoopbackIndex_ExceptionIfV4NotSupported() in /Users/mdhwang/runtime_droid/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs:line 161
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f66+0x6a
```

The PlatformNotSupportedException is a result of https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L32-L37
and on Android shell
```
generic_x86_64:/ $ ls -al /proc/net/tcp*
-r--r--r-- 1 root root 0 2021-08-04 13:33 /proc/net/tcp
-r--r--r-- 1 root root 0 2021-08-04 13:33 /proc/net/tcp6
```

It should be evaluated again after #51303
