### ISSUE TITLE
Test failure System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50639]
Run: [runtime-libraries-coreclr outerloop 20210401.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1067573&view=ms.vss-test-web.build-test-results-tab&runId=32839640&resultId=103634&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
 -System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
```

**Error message:**
```
Half-way through waiting for remote process.
Memory load: 26

Image Name PID Services 
========================= ======== ============================================
svchost.exe 3536 DcomLaunch, LSM, SystemEventsBroker 
svchost.exe 1508 RpcEptMapper, RpcSs 
svchost.exe 2472 gpsvc, iphlpsvc, ProfSvc, Schedule, SENS, 
 UserManager, Winmgmt 
svchost.exe 2708 EventSystem, nsi, RemoteRegistry 
svchost.exe 4784 Dhcp, EventLog, TimeBrokerSvc, 
 WinHttpAutoProxySvc 
svchost.exe 4392 CryptSvc, Dnscache, LanmanWorkstation, WinR 
svchost.exe 3440 CoreMessagingRegistrar 
svchost.exe 3652 DiagTrack 
svchost.exe 3732 SysMain 
Timed out at 4/1/2021 12:45:37 PM after 60000ms waiting for remote process.
Wrote mini dump to: C:\helix\work\workitem\uploads\2156.pfqf1yf5.auh.dmp
\tProcess ID: 2156
\tHandle: 1868
\tName: dotnet
\tMainModule: C:\helix\work\correlation\dotnet.exe
\tStartTime: 4/1/2021 12:44:37 PM
\tTotalProcessorTime: 00:00:00.3906250

Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/LoggingTest.cs:line 38

```

**Comment by VincentBu** [comment]
Same test failed with `Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.`

Run: [runtime-libraries-coreclr outerloop 20210509.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1129695&view=ms.vss-test-web.build-test-results-tab&runId=34306712&resultId=103246&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Debian.10.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-bfcd90a-20200121150006

- System.Net.Sockets.Tests.LoggingTest.EventSource_EventsRaisedAsExpected

```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.DoesNotContainException: Assert.DoesNotContain() Failure
Found:    (filter expression)
In value: ConcurrentQueue<EventWrittenEventArgs> [EventWrittenEventArgs { ActivityId = 00000000-0000-0000-0000-000000000000, Channel = None, EventId = 4, EventName = "Info", EventSource = EventSource(Private.InternalDiagnostics.System.Net.Sockets, ae391de7-a2cb-557c-dd34-fe00d0b98c7f), ... }, EventWrittenEventArgs { ActivityId = 00000000-0000-0000-0000-000000000000, Channel = None, EventId = 4, EventName = "Info", EventSource = EventSource(Private.InternalDiagnostics.System.Net.Sockets, ae391de7-a2cb-557c-dd34-fe00d0b98c7f), ... }, EventWrittenEventArgs { ActivityId = 00000000-0000-0000-0000-000000000000, Channel = None, EventId = 4, EventName = "Info", EventSource = EventSource(Private.InternalDiagnostics.System.Net.Sockets, ae391de7-a2cb-557c-dd34-fe00d0b98c7f), ... }, EventWrittenEventArgs { ActivityId = 00000000-0000-0000-0000-000000000000, Channel = None, EventId = 4, EventName = "Info", EventSource = EventSource(Private.InternalDiagnostics.System.Net.Sockets, ae391de7-a2cb-557c-dd34-fe00d0b98c7f), ... }, EventWrittenEventArgs { ActivityId = 00000000-0000-0000-0000-000000000000, Channel = None, EventId = 4, EventName = "Info", EventSource = EventSource(Private.InternalDiagnostics.System.Net.Sockets, ae391de7-a2cb-557c-dd34-fe00d0b98c7f), ... }, ...]
   at System.Net.Sockets.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__3_0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/LoggingTest.cs:line 62

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.LoggingTest+<>c Void <EventSource_EventsRaisedAsExpected>b__3_0()
```
