### ISSUE TITLE
[wasm][tests][eat] Moq.Internals.InterfaceProxy is not a valid base type for interface proxy

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50709]
Seen for:
- [Microsoft.Extensions.Configuration.FileExtensions.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/Microsoft.Extensions.Configuration.FileExtensions.Tests/console.c6dd6856.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [Microsoft.Extensions.Configuration.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/Microsoft.Extensions.Configuration.Tests/console.fa972be8.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [Microsoft.Extensions.FileProviders.Composite.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/Microsoft.Extensions.FileProviders.Composite.Tests/console.b053f8ac.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [Microsoft.Extensions.Logging.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/Microsoft.Extensions.Logging.Tests/console.1739f8e1.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [Microsoft.Extensions.Primitives.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/Microsoft.Extensions.Primitives.Tests/console.95140387.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

Exact traces might differ, so check the logs.

```
[02:18:46] info: Starting:    Microsoft.Extensions.Configuration.Tests.dll
[02:18:47] fail: [FAIL] Microsoft.Extensions.Configuration.Test.ConfigurationRootTest.RootDisposesChangeTokenRegistrations
[02:18:47] info: System.ArgumentException : Type Moq.Internals.InterfaceProxy is not valid base type for interface proxy, because it does not have accessible parameterless constructor. Only a non-sealed class with non-private default constructor can be used as base type for interface proxy. Please use some other valid type.
[02:18:47] info:    at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.ThrowInvalidBaseType(Type type, String doesNotHaveAccessibleParameterlessConstructor)
[02:18:47] info:    at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.EnsureValidBaseType(Type type)
[02:18:47] info:    at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateCode(Type proxyTargetType, Type[] interfaces, ProxyGenerationOptions options)
[02:18:47] info:    at Castle.DynamicProxy.DefaultProxyBuilder.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
[02:18:47] info:    at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyTypeWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
[02:18:47] info:    at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithoutTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, IInterceptor[] interceptors)
[02:18:47] info:    at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments)
[02:18:47] info:    at Moq.Mock`1[[Microsoft.Extensions.Configuration.IConfigurationProvider, Microsoft.Extensions.Configuration.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].InitializeInstance()
[02:18:47] info:    at Moq.Mock`1[[Microsoft.Extensions.Configuration.IConfigurationProvider, Microsoft.Extensions.Configuration.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnGetObject()
[02:18:47] info:    at Moq.Mock.get_Object()
[02:18:47] info:    at Moq.Mock`1[[Microsoft.Extensions.Configuration.IConfigurationProvider, Microsoft.Extensions.Configuration.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].get_Object()
[02:18:47] info:    at Microsoft.Extensions.Configuration.Test.ConfigurationRootTest.RootDisposesChangeTokenRegistrations()
[02:18:47] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:18:47] info: Finished:    Microsoft.Extensions.Configuration.Tests.dll
```

**Comment by danmoseley** [comment]
Should this have a mono area label?

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/51697
