### ISSUE TITLE
[wasm][tests][eat] System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.NoExceptionThrownWhenProcessingStaticActivityProperties

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50711]
seen in https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Diagnostics.DiagnosticSource.Tests/console.bd761da3.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D

```
[02:18:44] fail: [FAIL] System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.NoExceptionThrownWhenProcessingStaticActivityProperties
[02:18:44] info: System.ArgumentNullException : Value cannot be null. (Parameter 'eventSource')
[02:18:44] info:    at System.Diagnostics.Tracing.EventListener.EnableEvents(EventSource eventSource, EventLevel level, EventKeywords matchAnyKeyword, IDictionary`2 arguments)
[02:18:44] info:    at System.Diagnostics.Tests.DiagnosticSourceEventListener.Enable(String filterAndPayloadSpecs, EventKeywords keywords)
[02:18:44] info:    at System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.NoExceptionThrownWhenProcessingStaticActivityProperties()
[02:18:44] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by tommcdon** [comment]
Looks like a possible duplicate to #50924 
cc @mdh1418

**Comment by radical** [comment]
This is still reproducible for wasm: [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1275375&view=logs&jobId=fddee5b2-3265-5a91-40c1-750d81e69f3f&j=fddee5b2-3265-5a91-40c1-750d81e69f3f&t=b539fe9c-4231-5c9f-4235-451fd41db683), [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-7a4dd01ba7eb45b883/System.Diagnostics.DiagnosticSource.Tests/1/console.67bceb29.log?sv=2019-07-07&se=2021-08-24T06%3A48%3A53Z&sr=c&sp=rl&sig=IhTugai%2BC8NrqjQD9I2jBBfVtHJGbKMeEI0anAMGtes%3D)

**Comment by ilonatommy** [comment]
Still failing with the same message.
