### ISSUE TITLE
[wasm][tests][eat] Castle.DynamicProxy.Generators.Emitters.SimpleAST.ConstructorInvocationStatement..ctor throws ArgumentNullException

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50710]
Seen in:

- [Microsoft.Extensions.Http.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/Microsoft.Extensions.Http.Tests/console.2e8c689f.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.ComponentModel.TypeConverter.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.ComponentModel.TypeConverter.Tests/console.ed38233b.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Runtime.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.Tests/console.f316e946.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

```
[02:18:24] info: System.ArgumentNullException : Value cannot be null. (Parameter 'method')
[02:18:24] info:    at Castle.DynamicProxy.Generators.Emitters.SimpleAST.ConstructorInvocationStatement..ctor(ConstructorInfo method, Expression[] args)
[02:18:24] info:    at Castle.DynamicProxy.Generators.Emitters.CodeBuilders.ConstructorCodeBuilder.InvokeBaseConstructor(ConstructorInfo constructor, ArgumentReference[] arguments)
[02:18:24] info:    at Castle.DynamicProxy.Generators.InvocationTypeGenerator.CreateConstructor(AbstractTypeEmitter invocation, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.Generators.InvocationTypeGenerator.Generate(ClassEmitter class, ProxyGenerationOptions options, INamingScope namingScope)
[02:18:24] info:    at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.BuildInvocationType(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.GetInvocationType(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.Contributors.ClassProxyTargetContributor.GetMethodGenerator(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
[02:18:24] info:    at Castle.DynamicProxy.Contributors.CompositeTypeContributor.ImplementMethod(MetaMethod method, ClassEmitter class, ProxyGenerationOptions options, OverrideMethodDelegate overrideMethod)
[02:18:24] info:    at Castle.DynamicProxy.Contributors.CompositeTypeContributor.Generate(ClassEmitter class, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
[02:18:24] info:    at Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s)
[02:18:24] info:    at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass33_0.<ObtainProxyType>b__0(CacheKey _)
[02:18:24] info:    at Castle.Core.Internal.SynchronizedDictionary`2[[Castle.DynamicProxy.Generators.CacheKey, Castle.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc],[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(CacheKey key, Func`2 valueFactory)
[02:18:24] info:    at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
[02:18:24] info:    at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
[02:18:24] info:    at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
[02:18:24] info:    at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments)
[02:18:24] info:    at Moq.Mock`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InitializeInstance()
[02:18:24] info:    at Moq.Mock`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].OnGetObject()
[02:18:24] info:    at Moq.Mock.get_Object()
[02:18:24] info:    at Moq.Mock`1[[System.Net.Http.HttpMessageHandler, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].get_Object()
[02:18:24] info:    at Moq.Mock.Of[HttpMessageHandler](MockBehavior behavior)
[02:18:24] info:    at Moq.Mock.Of[HttpMessageHandler]()
[02:18:24] info:    at Microsoft.Extensions.Http.Test.HttpMessageHandlerBuilderTest.Build_AdditionalHandlerIsNull_ThrowsException()
[02:18:24] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/51697
