### ISSUE TITLE
[wasm][tests][eat]  System.Reflection.Tests.AssemblyTests.EntryPoint

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50713]
[System.Reflection.CoreCLR.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Reflection.CoreCLR.Tests/console.58f42b8a.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

```
[02:19:14] fail: [FAIL] System.Reflection.Tests.AssemblyTests.EntryPoint
[02:19:14] info: Assert.NotNull() Failure
[02:19:14] info:    at System.Reflection.Tests.AssemblyTests.EntryPoint()
[02:19:14] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/51697
