### ISSUE TITLE
[wasm][tests][eat] System.Reflection.Metadata.Tests.dll

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50714]
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Reflection.Metadata.Tests/console.8b65fc74.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D

```
[02:19:20] fail: [FAIL] System.Reflection.Metadata.Decoding.Tests.CustomAttributeDecoderTests.TestCustomAttributeDecoder
[02:19:20] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:19:20] info:    at System.Reflection.Metadata.Decoding.Tests.CustomAttributeDecoderTests.CustomAttributeTypeProvider.GetUnderlyingEnumType(String type)
[02:19:20] info:    at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DecodeFixedArgumentType(BlobReader& signatureReader, Boolean isElementType)
[02:19:20] info:    at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DecodeFixedArguments(BlobReader& signatureReader, BlobReader& valueReader, Int32 count)
[02:19:20] info:    at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DecodeValue(EntityHandle constructor, BlobHandle value)
[02:19:20] info:    at System.Reflection.Metadata.CustomAttribute.DecodeValue[String](ICustomAttributeTypeProvider`1 provider)
[02:19:20] info:    at System.Reflection.Metadata.Decoding.Tests.CustomAttributeDecoderTests.TestCustomAttributeDecoder()
[02:19:20] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:20] fail: [FAIL] System.Reflection.Metadata.Decoding.Tests.SignatureDecoderTests.SimpleSignatureProviderCoverage
[02:19:20] info: Assert.Equal() Failure
[02:19:20] info:                                  â†“ (pos 21)
[02:19:20] info: Expected: Â·Â·Â·nt32 modreq([System.Runtime]System.Runtime.CompilerServices.IÂ·Â·Â·
[02:19:20] info: Actual:   Â·Â·Â·nt32 modreq([System.Private.CoreLib]System.Runtime.CompilerSeÂ·Â·Â·
[02:19:20] info:                                  â†‘ (pos 21)
[02:19:20] info:    at System.Reflection.Metadata.Decoding.Tests.SignatureDecoderTests.SimpleSignatureProviderCoverage()
[02:19:20] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:21] fail: [FAIL] System.Reflection.Metadata.Tests.TagToTokenTests.ValidateTagToTokenConversion
[02:19:21] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:19:21] info:    at System.Reflection.Metadata.Tests.TagToTokenTests.<>c__DisplayClass1_0.<GetTags>b__3()
[02:19:21] info:    at System.Reflection.Metadata.Tests.TagToTokenTests.ValidateTagToTokenConversion()
[02:19:21] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by radical** [comment]
One failure left:

```
[07:29:18] fail: [FAIL] System.Reflection.Metadata.Tests.TagToTokenTests.ValidateTagToTokenConversion
[07:29:18] info: System.NullReferenceException : Object reference not set to an instance of an object.
[07:29:18] info:    at System.Reflection.Metadata.Tests.TagToTokenTests.<>c__DisplayClass1_0.<GetTags>b__3()
[07:29:18] info:    at System.Reflection.Metadata.Tests.TagToTokenTests.ValidateTagToTokenConversion()
[07:29:18] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by MaximLipnin** [comment]
> One failure left:
> 
> ```
> [07:29:18] fail: [FAIL] System.Reflection.Metadata.Tests.TagToTokenTests.ValidateTagToTokenConversion
> [07:29:18] info: System.NullReferenceException : Object reference not set to an instance of an object.
> [07:29:18] info:    at System.Reflection.Metadata.Tests.TagToTokenTests.<>c__DisplayClass1_0.<GetTags>b__3()
> [07:29:18] info:    at System.Reflection.Metadata.Tests.TagToTokenTests.ValidateTagToTokenConversion()
> [07:29:18] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> ```

I've seen the same error on Android AOT
