### ISSUE TITLE
[wasm][tests][eat] Could not load `System.Runtime` in `System.Runtime.Loader.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50718]
Seen in:
- [System.Runtime.Loader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.Loader.Tests/console.a9b9cea3.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- ~~[System.Runtime.Loader.DefaultContext.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.Loader.DefaultContext.Tests/console.2797ea5c.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)~~

Not all of these might be due to the same issue though.

```
[02:19:22] fail: [FAIL] System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByStream_ValidUserAssembly
[02:19:22] info: System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
[02:19:22] info:    at System.Reflection.RuntimeModule.GetTypes()
[02:19:22] info:    at System.Reflection.Assembly.GetTypes()
[02:19:22] info:    at System.Reflection.Assembly.get_DefinedTypes()
[02:19:22] info:    at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByStream_ValidUserAssembly()
[02:19:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:22] info: System.MissingMethodException: Method 'ReferencedClassLib.Program.Describe' not found.
[02:19:22] info:    at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
[02:19:22] info:    at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
[02:19:22] info:    at System.Runtime.Loader.Tests.SatelliteAssembliesTests.describeLib(String alc, String type, String culture, String expected)
```

**Comment by radical** [comment]
Superseded by https://github.com/dotnet/runtime/issues/51893
