### ISSUE TITLE
[wasm][tests][eat] System.Reflection.Tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50715]
```
[02:19:20] fail: [FAIL] System.Reflection.Tests.AssemblyTests.AssemblyGetForwardedTypesLoadFailure
[02:19:20] info: Assert.Throws() Failure
[02:19:20] info: Expected: typeof(System.Reflection.ReflectionTypeLoadException)
[02:19:20] info: Actual:   (No exception was thrown)
[02:19:20] info:    at System.Reflection.Tests.AssemblyTests.AssemblyGetForwardedTypesLoadFailure()
[02:19:20] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:20] fail: [FAIL] System.Reflection.Tests.TypeInfoTests.IsAssignable(type: typeof(System.Collections.IList), c: typeof(System.Collections.ArrayList), expected: True)
[02:19:20] info: Assert.Equal() Failure
[02:19:20] info: Expected: True
[02:19:20] info: Actual:   False
[02:19:20] info:    at System.Reflection.Tests.TypeInfoTests.IsAssignable(Type type, Type c, Boolean expected)
[02:19:20] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by joperezr** [comment]
Hey @radical quick question. What is the expectation from our side (we own area-System.Reflection) for these issues that got created for wasm? Are you going to look at them or are we supposed to look at them?

**Comment by radical** [comment]
@joperezr These (`[wasm][eat]`) issues are seen when building the tests with `/p:EnableAggressiveTrimming=true`. It would be very helpful if you could take a look at it as you would understand the tests.
We have a build on `runtime` pipeline now, for wasm, that builds with this too. And on that build, this particular test is disabled.

Though if this is not reproducible for non-wasm, then I can check it out.
