### ISSUE TITLE
[wasm][tests][eat] System.Runtime.InteropServices.Tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50717]
Seen [here](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.InteropServices.Tests/console.8bd0e04f.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

```
[02:19:22] fail: [FAIL] System.Runtime.InteropServices.Tests.IDispatchImplAttributeTests.Ctor_ImplTypeShort(implType: -1)
[02:19:22] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:19:22] info:    at System.Runtime.InteropServices.Tests.IDispatchImplAttributeTests.Ctor_ImplTypeShort(Int16 implType)
[02:19:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:22] fail: [FAIL] System.Runtime.InteropServices.Tests.IDispatchImplAttributeTests.Ctor_ImplTypeShort(implType: 0)
[02:19:22] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:19:22] info:    at System.Runtime.InteropServices.Tests.IDispatchImplAttributeTests.Ctor_ImplTypeShort(Int16 implType)
[02:19:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:22] fail: [FAIL] System.Runtime.InteropServices.Tests.IDispatchImplAttributeTests.Ctor_ImplTypeShort(implType: 2)
[02:19:22] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:19:22] info:    at System.Runtime.InteropServices.Tests.IDispatchImplAttributeTests.Ctor_ImplTypeShort(Int16 implType)
[02:19:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:24] fail: [FAIL] System.Runtime.InteropServices.Tests.SetWin32ContextInIDispatchAttributeTests.Ctor_Default_ExistsInSrc
[02:19:24] info: Assert.NotNull() Failure
[02:19:24] info:    at System.Runtime.InteropServices.Tests.SetWin32ContextInIDispatchAttributeTests.Ctor_Default_ExistsInSrc()
[02:19:24] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:24] info: Finished:    System.Runtime.InteropServices.Tests.dll
```

**Comment by AaronRobinsonMSFT** [comment]
This test should not run on WASM.

**Comment by MaximLipnin** [comment]
The same errors occur on Android AOT

**Comment by lewing** [comment]
@SamMonoRT these are EAT failures and are definitely worth looking into.

**Comment by radical** [comment]
This one seems windows specific:
`System.Runtime.InteropServices.Tests.SetWin32ContextInIDispatchAttributeTests.Ctor_Default_ExistsInSrc`

@aaron Why do the others fail on wasm, and android? Just trying to see if this might be hiding any other issue.
