### ISSUE TITLE
[wasm][tests][eat] System.Globalization.Tests.InvariantModeTests.IcuShouldNotBeLoaded

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50727]
```
[02:18:21] fail: [FAIL] System.Globalization.Tests.InvariantModeTests.IcuShouldNotBeLoaded
[02:18:21] info: Assert.False() Failure
[02:18:21] info: Expected: False
[02:18:21] info: Actual:   True
[02:18:21] info:    at System.Globalization.Tests.InvariantModeTests.IcuShouldNotBeLoaded()
[02:18:21] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by radical** [comment]
Fixed on main.
