### ISSUE TITLE
[wasm][tests][eat] System.MissingMethodException : Constructor on type 'OLEDB.Test.ModuleCore.XmlInlineDataDiscoverer' not found.

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50723]
Seen in:

- [System.Xml.RW.CharCheckingReader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.CharCheckingReader.Tests/console.92542587.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.FactoryReader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.FactoryReader.Tests/console.75395b8a.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.NameTable.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.NameTable.Tests/console.2377e53d.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.ReaderSettings.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.ReaderSettings.Tests/console.267d221d.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.RwFactory.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.RwFactory.Tests/console.560f9a29.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.SubtreeReader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.SubtreeReader.Tests/console.7fcfbcb4.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.WrappedReader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.WrappedReader.Tests/console.d93c042a.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.XmlConvert.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.XmlConvert.Tests/console.fb3c7441.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Xml.RW.CustomReader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Xml.RW.CustomReader.Tests/console.5e8d452b.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

```
[02:19:48] info: System.MissingMethodException : Constructor on type 'OLEDB.Test.ModuleCore.XmlInlineDataDiscoverer' not found.
[02:19:48] info:    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
[02:19:48] info:    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
[02:19:48] info:    at System.Activator.CreateInstance(Type type, Object[] args)
[02:19:48] info:    at DictionaryExtensions.GetOrAdd[Tuple`2,Object](IDictionary`2 dictionary, Tuple`2 key, Func`1 newValue)
```

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/51697
