### ISSUE TITLE
[mono][tests][eat] System.Threading.Tasks.Extensions.Tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50722]
- [System.Threading.Tasks.Extensions.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-d7050d97e17f4af48c/System.Threading.Tasks.Extensions.Tests/console.8c052c97.log?sv=2019-07-07&se=2021-05-14T10%3A12%3A51Z&sr=c&sp=rl&sig=joFjNEgxpTnETLo%2BQpy0GG9W3JRhjUYwDz51sJW1Qcs%3D)

```
[02:19:36] fail: [FAIL] System.Threading.Tasks.Tests.ValueTaskTests.NonGeneric_AsyncMethodBuilderAttribute_ValueTaskAttributed(valueTaskType: typeof(System.Threading.Tasks.ValueTask))
[02:19:36] info: System.InvalidOperationException : Sequence contains no matching element
[02:19:36] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[02:19:36] info:    at System.Linq.Enumerable.Single[CustomAttributeData](IEnumerable`1 source, Func`2 predicate)
[02:19:36] info:    at System.Threading.Tasks.Tests.ValueTaskTests.NonGeneric_AsyncMethodBuilderAttribute_ValueTaskAttributed(Type valueTaskType)
[02:19:36] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:36] fail: [FAIL] System.Threading.Tasks.Tests.ValueTaskTests.Generic_AsyncMethodBuilderAttribute_ValueTaskAttributed(valueTaskType: typeof(System.Threading.Tasks.ValueTask<>))
[02:19:36] info: System.InvalidOperationException : Sequence contains no matching element
[02:19:36] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[02:19:36] info:    at System.Linq.Enumerable.Single[CustomAttributeData](IEnumerable`1 source, Func`2 predicate)
[02:19:36] info:    at System.Threading.Tasks.Tests.ValueTaskTests.Generic_AsyncMethodBuilderAttribute_ValueTaskAttributed(Type valueTaskType)
[02:19:36] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:36] fail: [FAIL] System.Threading.Tasks.Tests.ValueTaskTests.Generic_AsyncMethodBuilderAttribute_ValueTaskAttributed(valueTaskType: typeof(System.Threading.Tasks.ValueTask<int>))
[02:19:36] info: System.InvalidOperationException : Sequence contains no matching element
[02:19:36] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[02:19:36] info:    at System.Linq.Enumerable.Single[CustomAttributeData](IEnumerable`1 source, Func`2 predicate)
[02:19:36] info:    at System.Threading.Tasks.Tests.ValueTaskTests.Generic_AsyncMethodBuilderAttribute_ValueTaskAttributed(Type valueTaskType)
[02:19:36] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:36] fail: [FAIL] System.Threading.Tasks.Tests.ValueTaskTests.Generic_AsyncMethodBuilderAttribute_ValueTaskAttributed(valueTaskType: typeof(System.Threading.Tasks.ValueTask<string>))
[02:19:36] info: System.InvalidOperationException : Sequence contains no matching element
[02:19:36] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[02:19:36] info:    at System.Linq.Enumerable.Single[CustomAttributeData](IEnumerable`1 source, Func`2 predicate)
[02:19:36] info:    at System.Threading.Tasks.Tests.ValueTaskTests.Generic_AsyncMethodBuilderAttribute_ValueTaskAttributed(Type valueTaskType)
[02:19:36] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:19:37] info: Finished:    System.Threading.Tasks.Extensions.Tests.dll
```

**Comment by radical** [comment]
Cannot reproduce this after other fixes on https://github.com/dotnet/runtime/pull/51697 .

**Comment by radical** [comment]
Mistakenly closed. I couldn't see it reproducing, because it has been disabled citing this issue!

**Comment by MaximLipnin** [comment]
Same error occur on Android AOT

**Comment by CoffeeFlux** [comment]
Doesn't seem to be wasm-specific. We should try to fix this for 6.

**Comment by marek-safar** [comment]
This is a minor test issue because we aggressively remove AsyncMethodBuilderAttribute attribute in SPC's ILLink.LinkAttributes.xml. The fix would be to override that with ILLink.Descriptors.xml for this test library.
