### ISSUE TITLE
[wasm][tests][eat] NRE in System.Text.Json.Serialization.Tests.CollectionTests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50721]
Seen in:
- [System.Text.Json.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Text.Json.Tests/console.70a41acd.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

```
[02:25:39] fail: [FAIL] System.Text.Json.Serialization.Tests.CollectionTests.WriteHashSetTOfHashSetT
[02:25:39] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:25:39] info:    at System.Text.Json.Serialization.Tests.CollectionTests.WriteHashSetTOfHashSetT()
[02:25:39] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:25:40] fail: [FAIL] System.Text.Json.Serialization.Tests.CollectionTests.WriteArrayOfHashSetT
[02:25:40] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:25:40] info:    at System.Text.Json.Serialization.Tests.CollectionTests.WriteArrayOfHashSetT()
[02:25:40] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:25:40] fail: [FAIL] System.Text.Json.Serialization.Tests.CollectionTests.ReadISetTOfHashSetT
[02:25:40] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:25:40] info:    at System.Text.Json.Serialization.Tests.CollectionTests.ReadISetTOfHashSetT()
[02:25:40] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:25:40] fail: [FAIL] System.Text.Json.Serialization.Tests.CollectionTests.WriteISetTOfISetT
[02:25:40] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:25:40] info:    at System.Text.Json.Serialization.Tests.CollectionTests.WriteISetTOfISetT()
[02:25:40] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:25:40] fail: [FAIL] System.Text.Json.Serialization.Tests.CollectionTests.WriteISetTOfHashSetT
[02:25:40] info: System.NullReferenceException : Object reference not set to an instance of an object.
[02:25:42] info:    at System.Text.Json.Serialization.Tests.CollectionTests.WriteISetTOfHashSetT()
[02:25:42] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[02:30:19] info: Finished:    System.Text.Json.Tests.dll
```

**Comment by lewing** [comment]
cc @SamMonoRT

**Comment by fanyang-mono** [comment]
It seems that something went wrong with `Assert.Equal`, when comparing two `System.Collections.Generic.HashSet`1[System.Int32]` objects.

**Comment by fanyang-mono** [comment]
This is a better stack trace:
```
  fail: console.error:   at <unknown> <0xffffffff>
        
  fail: console.error:   at Xunit.Sdk.AssertEqualityComparer`1<System.Collections.Generic.HashSet`1<int>>.CheckIfSetsAreEqual (System.Collections.Generic.HashSet`1<int>,System.Collections.Generic.HashSet`1<int>,System.Reflection.TypeInfo) [0x0008f] in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Sdk\AssertEqualityComparer.cs:249
        
  fail: console.error:   at Xunit.Sdk.AssertEqualityComparer`1<System.Collections.Generic.HashSet`1<int>>.Equals (System.Collections.Generic.HashSet`1<int>,System.Collections.Generic.HashSet`1<int>) [0x00109] in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Sdk\AssertEqualityComparer.cs:89
        
  fail: console.error:   at Xunit.Assert.Equal<System.Collections.Generic.HashSet`1<int>> (System.Collections.Generic.HashSet`1<int>,System.Collections.Generic.HashSet`1<int>,System.Collections.Generic.IEqualityComparer`1<System.Collections.Generic.HashSet`1<int>>) [0x0000b] in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:39
        
  fail: console.error:   at Xunit.Assert.Equal<System.Collections.Generic.HashSet`1<int>> (System.Collections.Generic.HashSet`1<int>,System.Collections.Generic.HashSet`1<int>) [0x00000] in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:24
```

**Comment by jkotas** [comment]
We still have several tests disabled against this issue: https://github.com/dotnet/runtime/blob/f25b23e075d311abe7114d0f73cdb1f71a0de3f4/src/libraries/System.Text.Json/tests/Common/CollectionTests/CollectionTests.Generic.Read.cs#L619
