### ISSUE TITLE
[wasm][tests][eat] System.Runtime.Serialization.InvalidDataContractException : No set method for property 'Key' in type 'System.Runtime.Serialization.KeyValue`2[System.String,System.Int32]'.

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50730]
Multiple test failures in

- [System.Runtime.Serialization.Json.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.Serialization.Json.Tests/console.a8c59d0e.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Runtime.Serialization.Json.ReflectionOnly.Tests/](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.Serialization.Json.ReflectionOnly.Tests/console.96057d8d.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)
- [System.Runtime.Serialization.Xml.ReflectionOnly.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50657-merge-fbdd385f15244375b3/System.Runtime.Serialization.Xml.ReflectionOnly.Tests/console.0de687bc.log?sv=2019-07-07&se=2021-04-25T01%3A56%3A12Z&sr=c&sp=rl&sig=wYlbyPPmVwzBZv0VHWKKRXKSpRm%2FWQqGnMqpIrN0%2BEQ%3D)

```
[02:19:23] info: System.Runtime.Serialization.InvalidDataContractException : No set method for property 'Key' in type 'System.Runtime.Serialization.KeyValue`2[System.String,System.Int32]'.
[02:19:23] info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
[02:19:23] info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message)
[02:19:23] info:    at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers()
[02:19:23] info:    at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type, XmlDictionaryString ns, String[] memberNames)
[02:19:23] info:    at System.Runtime.Serialization.ClassDataContract..ctor(Type type, XmlDictionaryString ns, String[] memberNames)
[02:19:23] info:    at System.Runtime.Serialization.ClassDataContract.CreateClassDataContractForKeyValue(Type type, XmlDictionaryString ns, String[] memberNames)
[02:19:23] info:    at System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.get_ItemContract()
[02:19:23] info:    at System.Runtime.Serialization.CollectionDataContract.InitCollectionDataContract(DataContract sharedTypeContract)
[02:19:23] info:    at System.Runtime.Serialization.CollectionDataContract..ctor(Type type, CollectionKind kind, Type itemType, MethodInfo getEnumeratorMethod, MethodInfo addMethod, ConstructorInfo constructor)
[02:19:23] info:    at System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(Type type, Boolean tryCreate, DataContract& dataContract, Type& itemType, Boolean constructorRequired)
[02:19:23] info:    at System.Runtime.Serialization.CollectionDataContract.TryCreate(Type type, DataContract& dataContract)
[02:19:23] info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
[02:19:23] info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
[02:19:23] info:    at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
[02:19:23] info:    at System.Runtime.Serialization.DataContract.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
[02:19:23] info:    at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(RuntimeTypeHandle typeHandle, Type type)
[02:19:23] info:    at System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetDataContract(RuntimeTypeHandle typeHandle, Type type)
[02:19:23] info:    at System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerializeReference(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.Json.JsonClassDataContract.WriteJsonValueCore(XmlWriterDelegator jsonWriter, Object obj, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue(XmlWriterDelegator jsonWriter, Object obj, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteJsonValue(JsonDataContract contract, XmlWriterDelegator writer, Object graph, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
[02:19:23] info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
[02:19:23] info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
[02:19:23] info:    at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph)
[02:19:23] info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
[02:19:23] info:    at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
[02:19:23] info:    at System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject(Stream stream, Object graph)
[02:19:23] info:    at DataContractJsonSerializerTests.SerializeAndDeserialize[ReadOnlyDictionary`2](ReadOnlyDictionary`2 value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
[02:19:23] info:    at DataContractJsonSerializerTests.DCJS_ReadOnlyDictionaryCausingDuplicateInvalidDataContract()
[02:19:23] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/51697
