### ISSUE TITLE
Test failure System.Net.Sockets.Tests.SendReceive_Sync.SendRecvPollSync_TcpListener_Socket

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50769]
Run: [runtime-libraries-coreclr outerloop 20210405.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1072431&view=ms.vss-test-web.build-test-results-tab&runId=32940604&paneView=debug&resultId=100529)

Failed tests:
```
net6.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open
 -System.Net.Sockets.Tests.SendReceive_Sync.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: False)
 -System.Net.Sockets.Tests.SendReceive_Sync.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: False)

Error message:
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Broken pipe))
---- System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
-------- System.NullReferenceException : Object reference not set to an instance of an object.
---- System.AggregateException : One or more errors occurred. (Broken pipe)
-------- System.Net.Sockets.SocketException : Broken pipe

Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 80
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs:line 561
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----
```

Failed tests:
```
net6.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open
 -System.Net.Sockets.Tests.SendReceive_Sync.SendRecvPollSync_TcpListener_Socket(listenAt: 127.0.0.1, pollBeforeOperation: True)
 -System.Net.Sockets.Tests.SendReceive_Sync.SendRecvPollSync_TcpListener_Socket(listenAt: ::1, pollBeforeOperation: True)


Error message
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Expected writer's read poll to fail after timeout
Expected: False
Actual: True))
---- System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
-------- System.NullReferenceException : Object reference not set to an instance of an object.
---- System.AggregateException : One or more errors occurred. (Expected writer's read poll to fail after timeout
Expected: False
Actual: True)
-------- Expected writer's read poll to fail after timeout
Expected: False
Actual: True

Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 80
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.Sockets.Tests.SendReceive`1.SendRecvPollSync_TcpListener_Socket(IPAddress listenAt, Boolean pollBeforeOperation) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs:line 561
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass7_0.<<SendRecvPollSync_TcpListener_Socket>b__0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs:line 500
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 63
----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass7_0.<<SendRecvPollSync_TcpListener_Socket>b__1>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs:line 536
```

**Comment by antonfirsov** [comment]
So far this happened only on one specific machine, `dci-macm1-build-004.local` (socket failed with `EPIPE`).

Note that this seems to be unrelated to #1479 which happens exclusively on windows, when `pollBeforeOperation: False`.

**Comment by wfurt** [comment]
Interesting. Similar issue was reported with Node: https://github.com/nodejs/node/issues/36826
Perhaps time to crank tests on M1 hardware.

**Comment by BruceForstall** [comment]
cc @sdmaclea

**Comment by sdmaclea** [comment]
This is probably related to the generic runtime instability for Apple Silicon prior to `macOS 11.3 Beta 6`.  There is an issue to update the Helix machines when Apple releases 11.3.

**Comment by k15tfu** [comment]
Probably this one should be reopened as per https://github.com/dotnet/runtime/pull/51186#issuecomment-821784833. // cc @MihaZupan

**Comment by rzikm** [comment]
No recent hits, not actionable at this moment, closing until issue resurfaces.
