### ISSUE TITLE
[Android][libraries] Invariant.Tests crashes with Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50785]
In assessing the state of Android library tests, `Invariant.Tests.csproj` crashes with `Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7d279c400000 in tid 6033 (.NET ThreadPool), pid 6003 (Invariant.Tests)`

```
[FAIL] System.Globalization.Tests.InvariantModeTests.TestEnum   Test name: System.Globalization.Tests.InvariantModeTests.TestEnum
Assembly:  [Invariant.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
Exception messages: Assert.Equal() Failure
Expected: CultureInfo[] []
Actual:   CultureInfo[] [, af, af-NA, af-ZA, agq, ...]   Exception stack traces:    at System.Globalization.Tests.InvariantModeTests.TestEnum() in /Users/mdhwang/runtime_droid/src/libraries/System.Globalization/tests/Invariant/InvariantMode.cs:line 658
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Execution time: 0.0055422

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7d279c400000 in tid 6033 (.NET ThreadPool), pid 6003 (Invariant.Tests)
crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
tombstoned: received crash request for pid 6033
crash_dump64: performing dump of process 6003 (target tid = 6033)
DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
DEBUG   : Build fingerprint: 'google/sdk_gphone_x86_64_arm64/generic_x86_64_arm64:11/RSR1.200819.001.A1/6823625:userdebug/dev-keys'
DEBUG   : Revision: '0'
DEBUG   : ABI: 'x86_64'
DEBUG   : Timestamp: 2021-04-02 10:40:33-0400
DEBUG   : pid: 6003, tid: 6033, name: .NET ThreadPool  >>> net.dot.Invariant.Tests <<<
DEBUG   : uid: 10223
DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7d279c400000
DEBUG   :     rax 00007d279c400000  rbx 00007d279a0006d0  rcx 00007d279c400002  rdx 00007d279a00092c
DEBUG   :     r8  0000000000000001  r9  0000000000000000  r10 00007d28748da860  r11 00007d279c6c9130
DEBUG   :     r12 000000000000000b  r13 0000000000000016  r14 00007d279a00092c  r15 00007d279a00092c
DEBUG   :     rdi 00007d279a0006d0  rsi 00007d279a0004c4
DEBUG   :     rbp 0000000000000000  rsp 00007d279a0004b8  rip 00007d2a8776e87b
DEBUG   : backtrace:
DEBUG   :       #00 pc 000000000026d87b  /apex/com.android.art/lib64/libicui18n.so (icu_66::UTF16CollationIterator::handleNextCE32(int&, UErrorCode&)+27) (BuildId: 9867227fd33d977e19de5b350a8cd99a)
DEBUG   :       #01 pc 000000000010f443  /apex/com.android.art/lib64/libicui18n.so (icu_66::CollationIterator::nextCE(UErrorCode&)+131) (BuildId: 9867227fd33d977e19de5b350a8cd99a)
DEBUG   :       #02 pc 0000000000127df9  /apex/com.android.art/lib64/libicui18n.so (icu_66::CollationKeys::writeSortKeyUpToQuaternary(icu_66::CollationIterator&, signed char const*, icu_66::CollationSettings const&, icu_66::SortKeyByteSink&, icu_66::Collation::Level, icu_66::CollationKeys::LevelCallback&, signed char, UErrorCode&)+745) (BuildId: 9867227fd33d977e19de5b350a8cd99a)
DEBUG   :       #03 pc 000000000021a3ce  /apex/com.android.art/lib64/libicui18n.so (icu_66::RuleBasedCollator::writeSortKey(char16_t const*, int, icu_66::SortKeyByteSink&, UErrorCode&) const+318) (BuildId: 9867227fd33d977e19de5b350a8cd99a)
DEBUG   :       #04 pc 000000000021a672  /apex/com.android.art/lib64/libicui18n.so (icu_66::RuleBasedCollator::getSortKey(char16_t const*, int, unsigned char*, int) const+146) (BuildId: 9867227fd33d977e19de5b350a8cd99a)
DEBUG   :       #05 pc 00000000001488b7  /data/app/~~IjY-zVuHtOxiHEvPGQzyUQ==/net.dot.Invariant.Tests-RieRhoX_jhYtLeful2EdZg==/lib/x86_64/libmonodroid.so (GlobalizationNative_GetSortKey+71) (BuildId: 6ed5ac96ad70fb14b244b1b46f37125f238aaf43)
DEBUG   :       #06 pc 0000000000133dbe  <anonymous:5ae2e000>
```

Worth noting that the backtrace shows icu functions, which shouldn't be ran in invariant mode tests.
[adb-logcat-net.dot.Invariant.Tests.log](https://github.com/dotnet/runtime/files/6265589/adb-logcat-net.dot.Invariant.Tests.log)

**Comment by mdh1418** [comment]
Looks like this passes locally now based on main @d3e9a114f12
