### ISSUE TITLE
Test failure System.Reflection.Tests.ModuleTests.GetMethods

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50831]
Run: [runtime-coreclr libraries-jitstress 20210406.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1073847&view=ms.vss-test-web.build-test-results-tab&runId=32968398&resultId=166378&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 -System.Reflection.Tests.ModuleTests.GetMethods
```

**Error message:**
```
Showing first 10 differences\n
  Position 0: Expected: TestMethodFoo, Actual: TestMethodBar
  Position 2: Expected: TestMethodBar, Actual: TestMethodFoo
Total number of differences: 2 out of 3


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 478
   at System.AssertExtensions.SequenceEqual[T](T[] expected, T[] actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 480
   at System.Reflection.Tests.ModuleTests.GetMethods() in /_/src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs:line 230
```

**Comment by BruceForstall** [comment]
Looks like this test was added with https://github.com/dotnet/runtime/pull/50076

**Comment by BruceForstall** [comment]
@MichalStrehovsky @erafalovsky PTAL

**Comment by MichalStrehovsky** [comment]
@erafalovsky would you be interested in fixing this? Maybe we can just sort the sequence before comparing. I forgot that the reflection stack doesn't guarantee ordering of members.

From the docs:

> ## Remarks
>
> The GetMethods method does not return methods in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which methods are returned, because that order varies.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress 20210428.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1111409&view=ms.vss-test-web.build-test-results-tab&runId=33887152&resultId=161841&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_checked-no_tiered_compilation-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 -System.Reflection.Tests.ModuleTests.GetMethods
```

**Error message:**
```
Showing first 10 differences
 Position 0: Expected: TestMethodFoo, Actual: TestMethodBar
 Position 2: Expected: TestMethodBar, Actual: TestMethodFoo
Total number of differences: 2 out of 3

Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 478
   at System.AssertExtensions.SequenceEqual[T](T[] expected, T[] actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 480
   at System.Reflection.Tests.ModuleTests.GetMethods() in /_/src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs:line 238

```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress 20210512.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1134240&view=ms.vss-test-web.build-test-results-tab&runId=34426036&resultId=164729&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855
 -System.Reflection.Tests.ModuleTests.GetMethods
```

**Error message:**
```
Showing first 10 differences
Position 0: Expected: TestMethodFoo, Actual: TestMethodBar
Position 2: Expected: TestMethodBar, Actual: TestMethodFoo
Total number of differences: 2 out of 3


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 478
   at System.AssertExtensions.SequenceEqual[T](T[] expected, T[] actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 480
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress2-jitstressregs 20210605.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1172838&view=ms.vss-test-web.build-test-results-tab&runId=35332872&resultId=176934&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open

- System.Reflection.Tests.ModuleTests.GetMethods

```
**Error message:**
```
Showing first 10 differences
Position 0: Expected: TestMethodFoo, Actual: TestMethodBar
Position 2: Expected: TestMethodBar, Actual: TestMethodFoo
Total number of differences: 2 out of 3


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 491
   at System.AssertExtensions.SequenceEqual[T](T[] expected, T[] actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 493
   at System.Reflection.Tests.ModuleTests.GetMethods() in /_/src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs:line 241
```

**Comment by BruceForstall** [comment]
Another failure: net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs1:

https://dev.azure.com/dnceng/public/_build/results?buildId=1198817&view=ms.vss-test-web.build-test-results-tab&runId=35932930&resultId=180136&paneView=debug

```
    System.Reflection.Tests.ModuleTests.GetMethods [FAIL]
      Showing first 10 differences
        Position 0: Expected: TestMethodFoo, Actual: TestMethodBar
        Position 2: Expected: TestMethodBar, Actual: TestMethodFoo
      Total number of differences: 2 out of 3
      Stack Trace:
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(473,0): at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual)
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(491,0): at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual)
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(493,0): at System.AssertExtensions.SequenceEqual[T](T[] expected, T[] actual)
```

**Comment by steveharter** [comment]
The proposed fix is trivial: sort the returned methods and compare:

> Maybe we can just sort the sequence before comparing

FWIW the tests in System.Text.Json also sort in a similar fashion - the properties for a JSON object produced by serializing a CLR object are typically sorted by property name due to nondeterminstic reflection ordering (i.e. the JSON is serialized in the order of the reflected properties).
