### ISSUE TITLE
System.ComponentModel.TypeConverter.Tests fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50916]
System.ComponentModel.TypeConverter.Tests
- [ ] System.ComponentModel.Tests.ContainerTest.Add2_Name_Duplicate
- [ ] System.ComponentModel.Tests.ContainerTest.ValidateName_Name_Duplicate
- [ ] System.ComponentModel.Tests.CultureInfoConverterTests.GetCultureName_Overriden_ConversionsReturnsExpected
- [ ] System.ComponentModel.Tests.CultureInfoConverterTests.ConvertTo_DestinationType_Success
- [ ] System.ComponentModel.Tests.ReferenceConverterTests.ConvertTo_DestinationType_Success
- [ ] System.ComponentModel.Tests.MultilineStringConverterTests.ConvertTo_WithContext_MultilineStringConverter
- [ ] System.ComponentModel.Tests.WarningExceptionTests.Ctor_SerializationInfo_StreamingContext
- [ ] System.ComponentModel.Design.Tests.CheckoutExceptionTests.Ctor_SerializationInfo_StreamingContext
- [ ] System.ComponentModel.Tests.InstanceCreationEditorTests.Text_Get_ReturnsExpected
- [ ] System.ComponentModel.Tests.LicenseExceptionTests.Ctor_SerializationInfo_StreamingContext
- [ ] System.ComponentModel.Tests.CollectionConverterTests.ConvertTo_DestinationType_Success
- [ ] System.ComponentModel.Tests.ArrayConverterTests.ConvertTo_DestinationType_Success
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Category_DontGetModifyAttributesAndGet_DoesNotCacheFirstResult
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Category_GetModifyAttributesAndGet_CachesFirstResult
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Equals_Invoke_ReturnsExpected
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptorWithNullName
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Category_GetWithCategoryAttribute_ReturnsExpected
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes
- [ ] System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes
- [ ] System.ComponentModel.Design.Tests.DesignerOptionServiceTests.DesignerOptionConverter_ConvertToString_ReturnsExpected
- [ ] System.ComponentModel.Tests.TypeListConverterTests.ConvertTo_WithContext_TypeListConverter
- [ ] System.Timers.Tests.TimersDescriptionAttributeTests.Ctor_String
- [ ] System.Timers.Tests.TimersDescriptionAttributeTests.Description_GetWithNullDescription_ThrowsArgumentNullException
- [ ] System.ComponentModel.Tests.ComponentConverterTests.ConvertTo_DestinationType_Success

```
System.ComponentModel.TypeConverter.Tests.dll   Failed: 47

Test collection for System.ComponentModel.Tests.InstanceCreationEditorTests
System.ComponentModel.Tests.InstanceCreationEditorTests.Text_Get_ReturnsExpected
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: (New...)\nActual:   InstanceCreationEditorDefaultText\n          ↑ (pos 0)

Test collection for System.ComponentModel.Tests.ArrayConverterTests
System.ComponentModel.Tests.ArrayConverterTests.ConvertTo_DestinationType_Success
    Assert.All() Failure: 1 out of 5 items in the collection did not pass.\n[0]: Item: Source='System.Int32[]', Type='System.String', Culture='(null)', RemoteCulture=''\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: Int32[] Array\n     Actual:   Array, Int32[]\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 60\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)

Test collection for System.ComponentModel.Tests.WarningExceptionTests
System.ComponentModel.Tests.WarningExceptionTests.Ctor_SerializationInfo_StreamingContext
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

Test collection for System.ComponentModel.Tests.CultureInfoConverterTests
System.ComponentModel.Tests.CultureInfoConverterTests.GetCultureName_Overriden_ConversionsReturnsExpected
    Assert.Equal() Failure\nExpected: (Default)\nActual:   CultureInfoConverterDefaultCultureString
System.ComponentModel.Tests.CultureInfoConverterTests.ConvertTo_DestinationType_Success
    Assert.All() Failure: 2 out of 9 items in the collection did not pass.\n[2]: Item: Source='', Type='System.String', Culture='(null)', RemoteCulture='(null)'\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (Default)\n     Actual:   CultureInfoConverterDefaultCultureString\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.AssertEqualInstanceDescriptor(Object expected, Object actual) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 195\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 44\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)\n[1]: Item: Source='', Type='System.String', Culture='(null)', RemoteCulture='(null)'\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (Default)\n     Actual:   CultureInfoConverterDefaultCultureString\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.AssertEqualInstanceDescriptor(Object expected, Object actual) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 195\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 44\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)

NoParallelTests
System.ComponentModel.Tests.MemberDescriptorTests.Category_DontGetModifyAttributesAndGet_DoesNotCacheFirstResult(originalCategory: \"\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category2\nActual:   PropertyCategoryCategory2\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_DontGetModifyAttributesAndGet_DoesNotCacheFirstResult(originalCategory: null)
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category2\nActual:   PropertyCategoryCategory2\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_DontGetModifyAttributesAndGet_DoesNotCacheFirstResult(originalCategory: \"Category\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category2\nActual:   PropertyCategoryCategory2\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor(name: \"name\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor(name: \"  \")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetModifyAttributesAndGet_CachesFirstResult(originalCategory: null, expected: \"Category2\")
    Assert.Equal() Failure\nExpected: (null)\nActual:   PropertyCategory
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetModifyAttributesAndGet_CachesFirstResult(originalCategory: \"Category\", expected: \"Category\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetModifyAttributesAndGet_CachesFirstResult(originalCategory: \"\", expected: \"\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: \nActual:   PropertyCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Equals_Invoke_ReturnsExpected
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptorWithNullName
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetWithCategoryAttribute_ReturnsExpected(attribute: CategoryAttribute { Category = \"PropertyCategoryDefault\", TypeId = typeof(System.ComponentModel.CategoryAttribute) }, expected: \"Misc\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetWithCategoryAttribute_ReturnsExpected(attribute: CategoryAttribute { Category = \"PropertyCategory\", TypeId = typeof(System.ComponentModel.CategoryAttribute) }, expected: null)
    Assert.Equal() Failure\nExpected: (null)\nActual:   PropertyCategory
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetWithCategoryAttribute_ReturnsExpected(attribute: CategoryAttribute { Category = \"PropertyCategory\", TypeId = typeof(System.ComponentModel.CategoryAttribute) }, expected: \"\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: \nActual:   PropertyCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetWithCategoryAttribute_ReturnsExpected(attribute: CategoryAttribute { Category = \"PropertyCategory  \", TypeId = typeof(System.ComponentModel.CategoryAttribute) }, expected: \"  \")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected:   \nActual:   PropertyCategory  \n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Category_GetWithCategoryAttribute_ReturnsExpected(attribute: CategoryAttribute { Category = \"PropertyCategoryCategory\", TypeId = typeof(System.ComponentModel.CategoryAttribute) }, expected: \"Category\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String(name: \"name\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String(name: \"  \")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes(name: \"  \", attributes: null, expected: [])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes(name: \"  \", attributes: [], expected: [])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes(name: \"name\", attributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }, MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }], expected: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes(name: \"name\", attributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }, MockAttribute2 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute2) }], expected: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }, MockAttribute2 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute2) }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes(name: \"name\", attributes: [null, MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }], expected: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_String_Attributes(name: \"name\", attributes: [CustomTypeIdAttribute { TypeId = 1 }, CustomTypeIdAttribute { TypeId = 1 }, CustomTypeIdAttribute { TypeId = 2 }, CustomTypeIdAttribute { TypeId = null }], expected: [CustomTypeIdAttribute { TypeId = 1 }, CustomTypeIdAttribute { TypeId = 2 }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Misc\nActual:   PropertyCategoryDefault\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes(name: \"  \", attributes: null, expectedAttributes: [])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes(name: \"  \", attributes: [], expectedAttributes: [])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes(name: \"name\", attributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }, MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }], expectedAttributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes(name: \"name\", attributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }, MockAttribute2 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute2) }], expectedAttributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }, MockAttribute2 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute2) }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes(name: \"name\", attributes: [null, MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }], expectedAttributes: [MockAttribute1 { TypeId = typeof(System.ComponentModel.Tests.MemberDescriptorTests+MockAttribute1) }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)
System.ComponentModel.Tests.MemberDescriptorTests.Ctor_MemberDescriptor_Attributes(name: \"name\", attributes: [CustomTypeIdAttribute { TypeId = 1 }, CustomTypeIdAttribute { TypeId = 1 }, CustomTypeIdAttribute { TypeId = 2 }, CustomTypeIdAttribute { TypeId = null }], expectedAttributes: [CustomTypeIdAttribute { TypeId = 1 }, CustomTypeIdAttribute { TypeId = 2 }])
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: Category\nActual:   PropertyCategoryCategory\n          ↑ (pos 0)

Test collection for System.ComponentModel.Design.Tests.CheckoutExceptionTests
System.ComponentModel.Design.Tests.CheckoutExceptionTests.Ctor_SerializationInfo_StreamingContext
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

Test collection for System.ComponentModel.Design.Tests.DesignerOptionServiceTests
System.ComponentModel.Design.Tests.DesignerOptionServiceTests.DesignerOptionConverter_ConvertToString_ReturnsExpected
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: (Collection)\nActual:   CollectionConverterText\n          ↑ (pos 0)

Test collection for System.ComponentModel.Tests.ReferenceConverterTests
System.ComponentModel.Tests.ReferenceConverterTests.ConvertTo_DestinationType_Success
    Assert.All() Failure: 2 out of 16 items in the collection did not pass.\n[1]: Item: Source='', Type='System.String', Culture='(null)', RemoteCulture=''\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (none)\n     Actual:   toStringNone\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 60\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)\n[0]: Item: Source='', Type='System.String', Culture='(null)', RemoteCulture=''\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (none)\n     Actual:   toStringNone\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 60\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)

Test collection for System.ComponentModel.Tests.ContainerTest
System.ComponentModel.Tests.ContainerTest.Add2_Name_Duplicate
    Assert.True() Failure\nExpected: True\nActual:   False
System.ComponentModel.Tests.ContainerTest.ValidateName_Name_Duplicate
    Assert.True() Failure\nExpected: True\nActual:   False

Test collection for System.ComponentModel.Tests.MultilineStringConverterTests
System.ComponentModel.Tests.MultilineStringConverterTests.ConvertTo_WithContext_MultilineStringConverter
    Assert.Equal() Failure\nExpected: (Text)\nActual:   Text

Test collection for System.ComponentModel.Tests.LicenseExceptionTests
System.ComponentModel.Tests.LicenseExceptionTests.Ctor_SerializationInfo_StreamingContext
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

Test collection for System.ComponentModel.Tests.CollectionConverterTests
System.ComponentModel.Tests.CollectionConverterTests.ConvertTo_DestinationType_Success
    Assert.All() Failure: 1 out of 5 items in the collection did not pass.\n[0]: Item: Source='System.ComponentModel.Tests.CollectionConverterTests+CustomCollection', Type='System.String', Culture='(null)', RemoteCulture=''\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (Collection)\n     Actual:   Collection\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 60\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)

Test collection for System.ComponentModel.Tests.TypeListConverterTests
System.ComponentModel.Tests.TypeListConverterTests.ConvertTo_WithContext_TypeListConverter
    Assert.Equal() Failure\nExpected: (none)\nActual:   none

Test collection for System.Timers.Tests.TimersDescriptionAttributeTests
System.Timers.Tests.TimersDescriptionAttributeTests.Ctor_String(description: \"\")
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: \nActual:   , \n          ↑ (pos 0)
System.Timers.Tests.TimersDescriptionAttributeTests.Ctor_String(description: \"description\")
    Assert.Equal() Failure\n                     ↓ (pos 11)\nExpected: description\nActual:   description, \n                     ↑ (pos 11)
System.Timers.Tests.TimersDescriptionAttributeTests.Description_GetWithNullDescription_ThrowsArgumentNullException
    Assert.Throws() Failure\nExpected: typeof(System.ArgumentNullException)\nActual:   (No exception was thrown)

Test collection for System.ComponentModel.Tests.ComponentConverterTests
System.ComponentModel.Tests.ComponentConverterTests.ConvertTo_DestinationType_Success
    Assert.All() Failure: 2 out of 16 items in the collection did not pass.\n[1]: Item: Source='', Type='System.String', Culture='(null)', RemoteCulture=''\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (none)\n     Actual:   toStringNone\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 60\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)\n[0]: Item: Source='', Type='System.String', Culture='(null)', RemoteCulture=''\n     Xunit.Sdk.EqualException: Assert.Equal() Failure\n     Expected: (none)\n     Actual:   toStringNone\n        at Xunit.Assert.Equal[Object](Object expected, Object actual, IEqualityComparer`1 comparer)\n        at Xunit.Assert.Equal[Object](Object expected, Object actual)\n        at System.ComponentModel.Tests.TypeConverterTestBase.<ConvertTo_DestinationType_Success>b__14_0(ConvertTest convertTest) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeConverterTestBase.cs:line 60\n        at Xunit.Assert.All[ConvertTest](IEnumerable`1 collection, Action`1 action)

**Comment by steveisok** [comment]
@mdh1418 These tests pass on Android and can be re-enabled.
