### ISSUE TITLE
.NET Core 3.1 - AssemblyLoadContext.LoadFromStream() throwing AccessDeniedException randomly in Azure Function

### ISSUE THREAD

**Issue by fberasategui** [dotnet/runtime#50920]
Sorry, I'll start off by saying I feel bad for reporting an issue without a proper repro, but so far I've been unable to properly and consistently reproduce this issue outside of production environments and it's causing us a lot of trouble.

I'm using `AssemblyLoadContext` to load and execute plugins inside Azure Functions. The DLL and PDB files for the plugins are hosted on Azure Blob, so I'm not using Filesystem-based assembly load or resolution.

This is the relevant code:

```csharp
    internal class InMemoryPluginLoadContext : AssemblyLoadContext
    {
        private static readonly object Lock = new object();
        private readonly Dictionary<string, PluginAssembly> _pluginAssemblies;
        private readonly Dictionary<string, Assembly> _loadedAssemblies = new Dictionary<string, Assembly>();

        public InMemoryPluginLoadContext(IEnumerable<PluginAssembly> assemblies) : base(isCollectible: true)
        {
            _pluginAssemblies = assemblies.ToDictionary(x => Path.GetFileNameWithoutExtension(x.FileName), x => x);

            var hexaSdkAssembly = typeof(Entity).Assembly;
            _loadedAssemblies[hexaSdkAssembly.GetName().Name] = hexaSdkAssembly;
        }

        private Assembly Load(PluginAssembly pluginAssembly)
        {
            try
            {
                lock(Lock)
                {
                    using var dll = new MemoryStream(pluginAssembly.AssemblyBytes);
                    using var pdb =
                        pluginAssembly.SymbolBytes != null
                        ? new MemoryStream(pluginAssembly.SymbolBytes)
                        : null;

                    var assembly = LoadFromStream(dll, pdb);

                    _loadedAssemblies[pluginAssembly.FileName] = assembly;

                    return assembly;
                }
            }
            catch(Exception ex)
            {
                throw new Exception($"An error has ocurred trying to load PluginAssembly: {pluginAssembly.FileName}. DLL: {pluginAssembly.AssemblyBytes?.Length} bytes. PDB: {pluginAssembly.SymbolBytes?.Length} bytes.", ex);
            }
            
        }

        protected override Assembly Load(AssemblyName assemblyName) =>
            _loadedAssemblies.TryGetValueOr(assemblyName.Name, (Assembly)null)
            ?? (_pluginAssemblies.TryGetValue(assemblyName.Name, out var pluginAssembly)
            ? Load(_pluginAssemblies[assemblyName.Name])
            : null);

        public List<PluginBase> GetPlugins()
        {
            return 
                _pluginAssemblies
                    .Select(x => Load(x.Value))
                    .SelectMany(a => a.GetTypes())
                    .Where(t => typeof(PluginBase).IsAssignableFrom(t))
                    .Where(t => !t.IsAbstract)
                    .Select(t => Activator.CreateInstance(t))
                    .Cast<PluginBase>()
                    .ToList();
        }
    }

    public class PluginAssembly
    {
        public byte[] AssemblyBytes { get; set; }

        public byte[] SymbolBytes { get; set; }

        public string FileName { get; set; }

        public string AssemblyHash { get; set; }
    }
```

so I basically provide all the DLLs and PDBs in memory as `byte[]`s to the `AssemblyLoadContext`, and then use `LoadFromStream()` to load them as needed.

This works very well for some time, but at unidentified circumstances it will start throwing the following exception:

```
---> System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
at Hexa.Api.Management.InMemoryPluginLoadContext.Load(PluginAssembly pluginAssembly)
```

whenever this exception happens, it starts happening for ALL assemblies in ALL requests to the Azure Function, so it basically crashes my whole project down and I'm forced to restart the function entirely.

I've tracked the exception down to [this method](https://github.com/dotnet/runtime/blob/49653839ef21f0cd886ee24caaf404ccaa1ac27e/src/coreclr/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.CoreCLR.cs#L61) in the .NET runtime, but I have no idea what might be causing the exception. I've also checked that the `byte[]`s are properly loaded with the dll/pdb contents.

Please someone give me a clue about how to troubleshoot this and how to properly reproduce and fix this error

**Comment by vitek-karas** [comment]
It's really hard to tell what's wrong here unfortunately. Couple of things which might help to figure this out:
* Can you try this on .NET 5? Maybe it's hitting some issue we've already fixed since (I know this is tricky if it only happens in production though)
* How many assemblies are you loading this way? The fact that once it happens, then it happens for anything sounds like some process-wide issue. For example out of memory (or out of VM space), or something along those lines. The system should be scalable pretty well, but I don't think we've tested it with tens of thousands of assemblies for example.
  * If you have the ability to print out some additional info when the problem happens, you can try to print out things like `AppDomain.Current.GetAssemblies.Length` which is the total number of assemblies in the process.

Another alternative is that one of the plugins is doing something bad to the process... but then I don't know why it would only affect assembly loading... hard to tell.

**Comment by fberasategui** [comment]
@vitek-karas I tried your suggestion about `AppDomain.CurrentDomain.GetAssemblies.Length` and I got back around 811 assemblies in one of the latest occurrences. I have now added code to print out the assembly names of those 811.

**Comment by vitek-karas** [comment]
That's not that much (I mean it's not small, but nowhere near the number I would expect to start getting issues with)

**Comment by fberasategui** [comment]
@vitek-karas Do you detect any deficiency or possible issue in my code posted above?

**Comment by vitek-karas** [comment]
Not really - but at the same time it's really hard to tell what went wrong. The failure could be coming from the file system/OS/anything really. I quickly scanned through CoreCLR code to see if we use this error code somewhere, but I only found one case which should not run in the scenarios you describe (and not on the callstack you have above).

What throws me off the most is that once it happens, then it sticks. That basically rules out things which would be specific to a given assembly. That might be another interesting data point - if this happens when you load a specific assembly - if it's always the same assembly, then we have something to look into. If it's random assembly each time, then it feels like something unrelated to the specific assembly and more of an environment problem.

**Comment by well0549** [comment]
I have exactly the same issue. I am using a compiled transform. This Compiled transform gets it's assemblies form Cached entries in a dictionary. So no actual loading from file or share is going oin....... The assemblybytes are cached.

I have exactly the same function app (but then compiled to the .Net framewrok 4.81, and that runs without any problems.
The behaviour is quite random and the Azure function  is effectively broken and wil will give back the same error (see below) for each call from that moment on.

Some backround on this. 

I have two Azure Transformation Functions, I have both a a .net core and a .net481 version of this function. (because the compiledtransform of 4.81 is much more capable).

Both of these have the exact same piece of code to load the assemblies......


````
                // Add an argument for each defined extension object
                foreach (var extension in transformation.Extensions)
                {
                    FileInformation assemblyInfo = new FileInformation();
                    assemblyInfo.FileName = Path.GetFileName(extension.AssemblyFileName);
                    connections.LoadExtensionBinary(transformation.Name, assemblyInfo);

                    var assembly = Assembly.Load(assemblyInfo.FileBytes);
                    var type = assembly.GetType($"{extension.Namespace}.{extension.ClassName}");
                    if (type == null)
                        throw new Exception($"Cannot get type {extension.AssemblyName}");
                    string ns = $"http://schemas.microsoft.com/BizTalk/2003/ScriptNS{counter}";
                    arguments.AddExtensionObject(ns, Activator.CreateInstance(type)!);
                    counter++;
                }
````

The error i get is:

````
SpaarpuntenTransformSSO.cc0527ef-1876-4ffc-b9a7-7459aafa5dcb Exception during transformation:System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyLoadContext, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
   at HTTPTransformCoreIsolated.Components.TransformationCore.TransformXslt(XmlReader inputDocument, XmlReader stylesheet, Transformation transformation, ILogger _logger, BlobClient blobClientInput, String blobName, ConcurrentDictionary`2 mapCache, BlobContainerClient containerClient, Connections connections)
   at HTTPTransformCoreIsolated.Components.TransformationCore.ExecuteTransform(Stream inputXml, Transformation transformation, ILogger _logger, BlobClient blobClient, String blobName, ConcurrentDictionary`2 mapCache, BlobContainerClient containerClient, Connections connections)
   at HTTPTransformCoreIsolated.TransformCore.ExecuteTransformation(ILogger log, String transformName, String blobName, ConcurrentDictionary`2 mapCache, String storageAccount, String containerName, Connections connections).
````

Not really sure how to fix this, and any help will be apreciated

**Comment by well0549** [comment]
Tried something else. Copy the array first an then try a load from the copy, The result is unfortunately the same...... Goes ok for 600 times and the starts throwing the same exception over and over again.........

**Comment by well0549** [comment]
One other thing i tried, When the error occurred i write data in to a toggle folder. This toggle folder is also in my watchlist.

````
 "watchDirectories": [ "c:\\home\\logfiles\\toggle" ],
````

I can see the file is written. But the error even persists afte ar restart ofthe function itselg. Only a restart of the host will solve the problem.

The function runs as an isolated function in azure
