### ISSUE TITLE
[wasm][tests][aot] System.IO.Pipelines.Tests - failing tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50959]
This can be reproduced on `main`.

[Logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.IO.Pipelines.Tests/console.e4d935c5.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
[19:45:14] fail: [FAIL] System.IO.Pipelines.Tests.PipelineReaderWriterFacts.ReadAsync_ThrowsIfWriterCompletedWithException
[19:45:14] info: Assert.Contains() Failure
[19:45:14] info: Not found: ThrowTestException
[19:45:14] info: In value:
[19:45:14] info: 
[19:45:14] fail: [FAIL] System.IO.Pipelines.Tests.PipelineReaderWriterFacts.WriteAsync_ThrowsIfReaderCompletedWithException
[19:45:14] info: Assert.Contains() Failure
[19:45:14] info: Not found: ThrowTestException
[19:45:14] info: In value:
[19:45:14] info: 
[19:45:14] fail: [FAIL] System.IO.Pipelines.Tests.FlushAsyncTests.FlushAsync_ThrowsIfWriterReaderWithException
[19:45:14] info: Assert.Contains() Failure
[19:45:14] info: Not found: ThrowTestException
[19:45:14] info: In value:
[19:45:14] info: 
[19:45:15] info: Finished:    System.IO.Pipelines.Tests.dll
```

**Comment by radical** [comment]
This seems to be timing out now:

```
[10:39:45] info: Starting:    System.IO.Pipelines.Tests.dll
[10:40:15] fail: [FAIL] System.IO.Pipelines.Tests.FlushAsyncTests.FlushAsync_ThrowsIfWriterReaderWithException
[10:40:15] info: Assert.Contains() Failure
[10:40:15] info: Not found: ThrowTestException
[10:40:15] info: In value:
[10:40:15] info: 
[10:40:15] fail: console.error: ThreadPool Callback threw an unhandled exception of type System.InvalidOperationException
                 
[10:54:43] info: Process 4113 didn't exit within 00:15:00 and will be killed
                 
[10:54:43] info: Killing process tree of 4113...
                 
[10:54:43] info: Pids to kill: 4113, 4114
                 
[10:54:43] info: Running lldb diagnostics for pid 4113
                 
[10:54:43] info: Printing backtrace for pid=4113
                 
[10:54:43] info: lldb was not found, skipping diagnosis..
                 
[10:54:43] info: Running lldb diagnostics for pid 4114
                 
[10:54:43] info: Printing backtrace for pid=4114
                 
[10:54:43] info: lldb was not found, skipping diagnosis..
                 
[10:54:43] info: 4113 Execution timed out after 900 seconds and the process was killed.
                 
[10:54:43] info: Process v8 exited with 137
```

**Comment by radical** [comment]
[3 failing tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-f01f1955e1554379ac/System.IO.Pipelines.Tests/console.405c6bc5.log?sv=2019-07-07&se=2021-06-29T21%3A46%3A31Z&sr=c&sp=rl&sig=RKGdRH0GnjjBhr4K9TTjqFeL8LqFuassS1BGn5Rz4v4%3D)

```
[22:24:27] fail: [FAIL] System.IO.Pipelines.Tests.PipelineReaderWriterFacts.ReadAsync_ThrowsIfWriterCompletedWithException
[22:24:27] info: The collection was expected to contain a single element, but it was empty.
[22:24:27] info:    at System.IO.Pipelines.Tests.PipelineReaderWriterFacts.ReadAsync_ThrowsIfWriterCompletedWithException()
[22:24:27] info: --- End of stack trace from previous location ---
[22:24:28] fail: [FAIL] System.IO.Pipelines.Tests.FlushAsyncTests.FlushAsync_ThrowsIfWriterReaderWithException
[22:24:28] info: The collection was expected to contain a single element, but it was empty.
[22:24:28] info:    at System.IO.Pipelines.Tests.FlushAsyncTests.FlushAsync_ThrowsIfWriterReaderWithException()
[22:24:28] info: --- End of stack trace from previous location ---
```

**Comment by lewing** [comment]
These are all AOT stack trace issues

**Comment by radical** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/50957, because as Larry said the failures are all AOT stack trace issues.

**Comment by VincentBu** [comment]
Failed again in [runtime 20210701.106](https://dev.azure.com/dnceng/public/_build/results?buildId=1216814&view=ms.vss-test-web.build-test-results-tab&runId=36305748&resultId=134541&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open

- System.IO.Pipelines.Tests.FlushAsyncTests.FlushAsync_ThrowsIfWriterReaderWithException

```
**Error message:**
```
The collection was expected to contain a single element, but it was empty.


Stack trace
   at System.IO.Pipelines.Tests.FlushAsyncTests.FlushAsync_ThrowsIfWriterReaderWithException() in /_/src/libraries/System.IO.Pipelines/tests/FlushAsyncTests.cs:line 52
--- End of stack trace from previous location ---
```

**Comment by lewing** [comment]
@VincentBu that is the not a wasm lane
