### ISSUE TITLE
[wasm][tests][aot] Runtime crash in System.Reflection.Emit.ILGeneration.Tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50961]
[Logs for System.Reflection.Emit.ILGeneration.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.Reflection.Emit.ILGeneration.Tests/console.1949a64f.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
[19:46:16] info: console.info: Arguments: --run,WasmTestRunner.dll,System.Reflection.Emit.ILGeneration.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[19:46:16] info: console.debug: MONO_WASM: Initializing mono runtime
[19:46:16] info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[19:46:16] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[19:46:16] info: console.info: Initializing.....
[19:46:16] info: Discovering: System.Reflection.Emit.ILGeneration.Tests.dll (method display = ClassAndMethod, method display options = None)
[19:46:16] info: Discovered:  System.Reflection.Emit.ILGeneration.Tests.dll (found 72 of 129 test cases)
[19:46:16] info: Starting:    System.Reflection.Emit.ILGeneration.Tests.dll
[19:46:17] fail: 19:46:17.0381515 console.error: RuntimeError: memory access out of bounds
[19:46:17] fail: 19:46:17.0528568 console.error: RuntimeError: memory access out of bounds
[19:46:17] fail: 19:46:17.0529001     at xunit_execution_dotnet_Xunit_Sdk_TestMessage__ctor_Xunit_Abstractions_ITest (<anonymous>:wasm-function[2620]:0x8efe6)
[19:46:17] fail: 19:46:17.0529058     at xunit_execution_dotnet_Xunit_Sdk_TestFinished__ctor_Xunit_Abstractions_ITest_System_Decimal_string (<anonymous>:wasm-function[5189]:0x148e16)
[19:46:17] fail: 19:46:17.0529124     at invoke_viiiii (dotnet.js:1:257660)
[19:46:17] fail: 19:46:17.0529241     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7842]:0x24121d)
[19:46:17] fail: 19:46:17.0529286     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0529340     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__9 (<anonymous>:wasm-function[18394]:0x5c0bba)
[19:46:17] fail: 19:46:17.0529382     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[8011]:0x26ba13)
[19:46:17] fail: 19:46:17.0529483     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[7844]:0x241a29)
[19:46:17] fail: 19:46:17.0529818     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0529969     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_MoveNext (<anonymous>:wasm-function[7798]:0x223d8f)
[19:46:17] fail: 19:46:17.0530017     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0530066     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_ (<anonymous>:wasm-function[18378]:0x5bea42)
[19:46:17] fail: 19:46:17.0530113     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[17545]:0x56d54b)
[19:46:17] fail: 19:46:17.0530185     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0530223     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7900]:0x259c38)
[19:46:17] fail: 19:46:17.0530260     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0530298     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[18402]:0x5c2966)
[19:46:17] fail: 19:46:17.0530695     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[8018]:0x26bd38)
[19:46:17] fail: 19:46:17.0530742     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[3826]:0xdf0fa)
[19:46:17] fail: 19:46:17.0530838     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[17536]:0x56cd5f)
[19:46:17] fail: 19:46:17.0531126     at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[17551]:0x56db2f)
[19:46:17] fail: 19:46:17.0531172     at invoke_iiii (dotnet.js:1:256301)
[19:46:17] fail: 19:46:17.0531209     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCasesAsyncd__32_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7851]:0x243b02)
[19:46:17] fail: 19:46:17.0531247     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0531488     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[18395]:0x5c0f64)
[19:46:17] fail: 19:46:17.0531535     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[8012]:0x26ba86)
[19:46:17] fail: 19:46:17.0531573     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunTestCasesAsync (<anonymous>:wasm-function[17687]:0x587f78)
[19:46:17] fail: 19:46:17.0531615     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0531770     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__31_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7853]:0x244886)
[19:46:17] fail: 19:46:17.0531958     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0531999     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[18396]:0x5c130e)
[19:46:17] fail: 19:46:17.0532037     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[8013]:0x26baf9)
[19:46:17] fail: 19:46:17.0540342     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[7855]:0x245ec4)
[19:46:17] fail: 19:46:17.0540627     at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[17595]:0x575ec8)
[19:46:17] fail: 19:46:17.0540677     at invoke_iiiiiii (dotnet.js:1:258416)
[19:46:17] fail: 19:46:17.0540716     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMethodsAsyncd__38_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7892]:0x256551)
[19:46:17] fail: 19:46:17.0540755     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0540794     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[18400]:0x5c221c)
[19:46:17] fail: 19:46:17.0540867     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[8016]:0x26bc52)
[19:46:17] fail: 19:46:17.0541069     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunTestMethodsAsync (<anonymous>:wasm-function[17761]:0x58c8c8)
[19:46:17] fail: 19:46:17.0541117     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0541298     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__37_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7894]:0x2577ba)
[19:46:17] fail: 19:46:17.0541341     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0541378     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[18401]:0x5c25c6)
[19:46:17] fail: 19:46:17.0541417     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[8017]:0x26bcc5)
[19:46:17] fail: 19:46:17.0541456     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[7896]:0x2590f7)
[19:46:17] fail: 19:46:17.0541566     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[17575]:0x572704)
[19:46:17] fail: 19:46:17.0541733     at invoke_iiiiii (dotnet.js:1:256121)
[19:46:17] fail: 19:46:17.0541778     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTestClassesAsyncd__28_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7882]:0x250011)
[19:46:17] fail: 19:46:17.0541816     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0541852     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[18398]:0x5c1ad2)
[19:46:17] fail: 19:46:17.0541948     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[8014]:0x26bb6c)
[19:46:17] fail: 19:46:17.0541986     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunTestClassesAsync (<anonymous>:wasm-function[17736]:0x58adec)
[19:46:17] fail: 19:46:17.0542023     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0542060     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyncd__27_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7884]:0x251188)
[19:46:17] fail: 19:46:17.0542098     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0542386     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[18399]:0x5c1e7c)
[19:46:17] fail: 19:46:17.0542434     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[8015]:0x26bbdf)
[19:46:17] fail: 19:46:17.0542473     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[7886]:0x252a82)
[19:46:17] fail: 19:46:17.0542512     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[17628]:0x57a5b4)
[19:46:17] fail: 19:46:17.0542609     at invoke_iiiiiii (dotnet.js:1:258416)
[19:46:17] fail: 19:46:17.0542646     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCollectionsAsyncd__42_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7907]:0x25bce8)
[19:46:17] fail: 19:46:17.0542685     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0542917     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[18403]:0x5c2d07)
[19:46:17] fail: 19:46:17.0542963     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[8019]:0x26bdab)
[19:46:17] fail: 19:46:17.0543122     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[7911]:0x25f077)
[19:46:17] fail: 19:46:17.0543163     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[17618]:0x579ee2)
[19:46:17] fail: 19:46:17.0543200     at invoke_iiiii (dotnet.js:1:256653)
[19:46:17] fail: 19:46:17.0543239     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_MoveNext (<anonymous>:wasm-function[7833]:0x239a47)
[19:46:17] fail: 19:46:17.0543278     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0543498     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[18389]:0x5c00e7)
[19:46:17] fail: 19:46:17.0543545     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[17627]:0x57a45b)
[19:46:17] fail: 19:46:17.0543584     at invoke_iiiii (dotnet.js:1:256653)
[19:46:17] fail: 19:46:17.0543621     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd__41_TTestCase_REF_MoveNext (<anonymous>:wasm-function[7909]:0x25d1de)
[19:46:17] fail: 19:46:17.0543711     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0543749     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[18404]:0x5c30ca)
[19:46:17] fail: 19:46:17.0543787     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[8020]:0x26be1e)
[19:46:17] fail: 19:46:17.0544017     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[17787]:0x58f0fc)
[19:46:17] fail: 19:46:17.0544065     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0544103     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_MoveNext (<anonymous>:wasm-function[7812]:0x22eba7)
[19:46:17] fail: 19:46:17.0544141     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0544178     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[18382]:0x5bf27e)
[19:46:17] fail: 19:46:17.0544298     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[17562]:0x57049b)
[19:46:17] fail: 19:46:17.0544364     at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[17722]:0x58a2fd)
[19:46:17] fail: 19:46:17.0544580     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[17049]:0x532071)
[19:46:17] fail: 19:46:17.0544629     at invoke_viiiii (dotnet.js:1:257660)
[19:46:17] fail: 19:46:17.0544667     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[16983]:0x52981f)
[19:46:17] fail: 19:46:17.0544705     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0544744     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[41321]:0xd31f0d)
[19:46:17] fail: 19:46:17.0544996     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[41350]:0xd33e61)
[19:46:17] fail: 19:46:17.0545105     at invoke_iiiii (dotnet.js:1:256653)
[19:46:17] fail: 19:46:17.0545143     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[16981]:0x526adc)
[19:46:17] fail: 19:46:17.0545182     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0545220     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[41320]:0xd31cfd)
[19:46:17] fail: 19:46:17.0545338     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[41339]:0xd32bac)
[19:46:17] fail: 19:46:17.0545381     at invoke_iii (dotnet.js:1:255942)
[19:46:17] fail: 19:46:17.0545512     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[13640]:0x3c12b1)
[19:46:17] fail: 19:46:17.0545556     at invoke_vii (dotnet.js:1:257167)
[19:46:17] fail: 19:46:17.0545821     at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[31724]:0x828598)
[19:46:17] fail: 19:46:17.0545924     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[13641]:0x3c1847)
[19:46:17] fail: 19:46:17.0545964     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_i4_obj (<anonymous>:wasm-function[457]:0x30bd6)
[19:46:17] fail: 19:46:17.0546003     at invoke_viii (dotnet.js:1:257331)
[19:46:17] fail: 19:46:17.0546040     at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[26575]:0x6dda0e)
[19:46:17] fail: 19:46:17.0546079     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[23135]:0x652a07)
[19:46:17] fail: 19:46:17.0546116     at mono_jit_runtime_invoke (<anonymous>:wasm-function[23144]:0x652fd0)
[19:46:17] fail: 19:46:17.0546204     at do_runtime_invoke (<anonymous>:wasm-function[6161]:0x1781b6)
[19:46:17] fail: 19:46:17.0546245     at mono_runtime_try_invoke (<anonymous>:wasm-function[1366]:0x54f35)
[19:46:17] fail: 19:46:17.0546282     at mono_runtime_invoke (<anonymous>:wasm-function[22947]:0x649d75)
[19:46:17] fail: 19:46:17.0546319     at mono_wasm_invoke_method (<anonymous>:wasm-function[22780]:0x644b9a)
[19:46:17] fail: 19:46:17.0546661     at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:248436)
[19:46:17] fail: 19:46:17.0546707     at Object._call_method_with_converted_args (dotnet.js:1:197234)
[19:46:17] fail: 19:46:17.0546746     at Object.call_method (dotnet.js:1:195707)
[19:46:17] fail: 19:46:17.0546855     at dotnet.js:1:203446
[19:46:17] fail: 19:46:17.0546894     at Object.call_assembly_entry_point (dotnet.js:1:203679)
[19:46:17] fail: 19:46:17.0546932     at Object.init (runtime.js:355:24)
[19:46:17] fail: 19:46:17.0546969     at Object.config.loaded_cb (runtime.js:241:8)
[19:46:17] fail: 19:46:17.0547009     at Object._finalize_startup (dotnet.js:1:147787)
[19:46:17] fail: 19:46:17.0547047     at onPendingRequestComplete (dotnet.js:1:148986)
[19:46:17] fail: 19:46:17.0557730     at processFetchResponseBuffer (dotnet.js:1:149306)
[19:46:17] info: 19:46:17.0835591 Process v8 exited with 1
[19:46:17] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by radical** [comment]
And a second instance of the same crash, in `System.CodeDom.Tests`:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-b46de50534b546c4b0/System.CodeDom.Tests/console.98ab480b.log?sv=2019-07-07&se=2021-04-29T20%3A52%3A18Z&sr=c&sp=rl&sig=laqAoCBV6F8dj9Rk%2BSRtLkM6qvQPlv71zJ4G3JBoJ4o%3D

**Comment by radical** [comment]
Not reproducible anymore.
