### ISSUE TITLE
[wasm][tests][aot] System.Runtime.Numerics.Tests failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50963]
[Logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.Runtime.Numerics.Tests/console.41f7cfbb.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
[19:48:49] info: Starting:    System.Runtime.Numerics.Tests.dll
[19:48:49] fail: [FAIL] System.Numerics.Tests.powTest.RunPowPositive
[19:48:49] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:49] info: 
[19:48:50] fail: [FAIL] System.Numerics.Tests.divremTest.RunDivRem_TwoLargeBI
[19:48:50] info: System.Exception : VerifyDivRemString failed: make 183 139 5 144 244 227 116 253 187 11 241 5 31 203 85 0 249 233 9 181 178 72 endmake make 147 237 133 64 244 157 130 226 136 245 30 70 50 228 235 5 29 209 111 25 124 74 73 31 108 167 210 143 88 209 195 10 110 176 113 163 111 163 127 95 57 41 104 16 0 133 35 28 13 227 235 228 67 46 94 73 163 101 211 76 203 242 137 183 49 20 215 129 115 71 150 122 81 16 224 83 225 57 31 231 132 182 129 116 229 222 endmake bDivRem System.NullReferenceException: Object reference not set to an instance of an object.
[19:48:50] info:    at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
[19:48:50] info: ---- System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:50] info: 
[19:48:50] info: ----- Inner Stack Trace -----
[19:48:50] info:    at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
[19:48:50] fail: [FAIL] System.Numerics.Tests.divremTest.RunDivRemTests
[19:48:50] info: System.Exception : VerifyDivRemString failed: make 139 180 85 123 49 195 90 182 5 182 26 155 223 247 21 180 255 120 81 61 134 94 83 118 122 26 142 122 218 67 137 35 116 49 247 32 250 168 225 58 204 130 39 163 20 232 213 174 188 97 19 97 67 68 179 44 96 223 1 22 53 223 219 193 44 247 38 173 0 244 186 87 151 23 113 4 54 endmake make 97 146 69 223 189 121 48 40 223 48 126 202 192 27 166 202 4 236 166 102 118 28 193 39 174 200 167 188 202 44 211 174 246 176 125 111 209 85 34 98 145 4 24 246 46 54 52 158 176 204 19 132 94 208 57 68 208 29 49 245 210 116 94 178 92 208 211 15 157 55 249 174 202 67 212 114 4 202 249 120 148 8 11 253 25 79 79 38 119 57 158 179 36 44 144 29 166 endmake bDivRem System.NullReferenceException: Object reference not set to an instance of an object.
[19:48:50] info:    at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
[19:48:50] info: ---- System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:50] info: 
[19:48:50] info: ----- Inner Stack Trace -----
[19:48:50] info:    at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
[19:48:50] fail: [FAIL] System.Numerics.Tests.divremTest.RunDivRem_OneSmallOneLargeBI
[19:48:50] info: System.Exception : VerifyDivRemString failed: make 255 62 endmake make 157 123 42 248 184 131 54 29 201 240 88 237 190 192 134 238 3 4 12 195 182 35 145 5 219 206 86 72 24 75 23 194 14 108 147 77 116 59 40 158 189 144 229 183 103 253 142 208 43 134 237 77 243 122 82 122 234 37 28 234 45 238 4 125 217 149 223 82 44 57 122 199 endmake bDivRem System.NullReferenceException: Object reference not set to an instance of an object.
[19:48:50] info:    at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
[19:48:50] info: ---- System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:50] info: 
[19:48:50] info: ----- Inner Stack Trace -----
[19:48:50] info:    at System.Numerics.Tests.divremTest.VerifyDivRemString(String opstring)
[19:48:53] fail: [FAIL] System.Numerics.Tests.remainderTest.RunRemainderPositive
[19:48:53] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:53] info: 
[19:48:53] fail: [FAIL] System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt
[19:48:53] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:53] info: 
[19:48:53] fail: [FAIL] System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt_Threshold
[19:48:53] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:53] info: 
[19:48:53] fail: [FAIL] System.Numerics.Tests.modpowTest.ModPow2Large1SmallInt_Threshold
[19:48:53] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:53] info: 
[19:48:53] fail: [FAIL] System.Numerics.Tests.modpowTest.ModPow2Large1SmallInt
[19:48:53] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:53] info: 
[19:48:53] fail: [FAIL] System.Numerics.Tests.modpowTest.ModPow0Base
[19:48:53] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:48:53] info: 
[19:49:05] fail: [FAIL] System.Numerics.Tests.op_divideTest.RunDividePositivenonZero
[19:49:05] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:05] info: 
[19:49:05] fail: [FAIL] System.Numerics.Tests.gcdTest.RunGCDTests
[19:49:05] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:05] info: 
[19:49:05] fail: [FAIL] System.Numerics.Tests.multiplyTest.RunMultiply_OneLargeOneSmall
[19:49:05] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:05] info: 
[19:49:06] fail: [FAIL] System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers_Threshold
[19:49:06] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:06] info: 
[19:49:06] fail: [FAIL] System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers
[19:49:06] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:06] info: 
[19:49:06] fail: [FAIL] System.Numerics.Tests.multiplyTest.RunMultiply_OneLargeOneZero
[19:49:06] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:06] info: 
[19:49:06] fail: [FAIL] System.Numerics.Tests.op_modulusTest.RunRemainderTestsPositive
[19:49:06] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:06] info: 
[19:49:07] fail: [FAIL] System.Numerics.Tests.op_multiplyTest.RunMultiplyTests
[19:49:07] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:07] info: 
[19:49:07] fail: [FAIL] System.Numerics.Tests.op_multiplyTest.RunMultiplyPositive
[19:49:07] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:07] info: 
[19:49:07] fail: [FAIL] System.Numerics.Tests.op_multiplyTest.RunMultiplyPositiveWith0
[19:49:07] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:07] info: 
[19:49:07] fail: [FAIL] System.Numerics.Tests.DivideTest.RunDivideOneLargeOneSmallBI
[19:49:07] info: System.NullReferenceException : Object reference not set to an instance of an object.
[19:49:07] info: 

```

**Comment by radical** [comment]
Not reproducible anymore.
