### ISSUE TITLE
[wasm][tests][aot] Runtime crash in System.Xml.XPath.Tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50970]
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.Xml.XPath.Tests/console.0042ae02.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
XHarness command issued: wasm test --app=. --output-directory=/home/helixbot/work/96610860/w/B61B09F8/uploads/xharness-output --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js -- --run WasmTestRunner.dll System.Xml.XPath.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[19:58:15] info: 19:58:15.2130749 Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.Xml.XPath.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing

[19:58:17] fail: 19:58:17.1881220 console.error: RuntimeError: invalid index into function table

[19:58:17] fail: 19:58:17.2070882 console.error: RuntimeError: invalid index into function table

[19:58:17] fail: 19:58:17.2071525     at xunit_execution_dotnet_DictionaryExtensions_GetOrAdd_TKey_REF_TValue_REF_System_Collections_Generic_IDictionary_2_TKey_REF_TValue_REF_TKey_REF_System_Func_1_TValue_REF (<anonymous>:wasm-function[4332]:0x10aa4d)
[19:58:17] fail: 19:58:17.2071685     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCase_GetCachedTraitAttributes_Xunit_Abstractions_IAssemblyInfo (<anonymous>:wasm-function[8846]:0x29a4ea)
[19:58:17] fail: 19:58:17.2071739     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCase_GetTraitAttributesData_Xunit_Abstractions_ITestMethod (<anonymous>:wasm-function[8844]:0x29a0ab)
[19:58:17] fail: 19:58:17.2071800     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCase_Initialize (<anonymous>:wasm-function[20125]:0x68494e)
[19:58:17] fail: 19:58:17.2072041     at xunit_execution_dotnet_Xunit_Sdk_TestMethodTestCase_get_Traits (<anonymous>:wasm-function[20188]:0x691fab)
[19:58:17] fail: 19:58:17.2072087     at xunit_runner_utility_netcoreapp10_Xunit_XunitFilters_FilterExcludedTraits_Xunit_Abstractions_ITestCase (<anonymous>:wasm-function[8695]:0x27ab14)
[19:58:17] fail: 19:58:17.2072573     at xunit_runner_utility_netcoreapp10_Xunit_XunitFilters_Filter_Xunit_Abstractions_ITestCase (<anonymous>:wasm-function[19553]:0x63d8de)
[19:58:17] fail: 19:58:17.2072628     at Microsoft_DotNet_XHarness_TestRunners_Xunit_wrapper_delegate_invoke_System_Func_2_Xunit_Abstractions_ITestCase_bool_invoke_TResult_T_Xunit_Abstractions_ITestCase (<anonymous>:wasm-function[49190]:0x1478c04)
[19:58:17] fail: 19:58:17.2072684     at System_Linq_System_Linq_Enumerable_WhereListIterator_1_TSource_REF_MoveNext (<anonymous>:wasm-function[41774]:0x105aab5)
[19:58:17] fail: 19:58:17.2072800     at invoke_iii (dotnet.js:1:257040)
[19:58:17] fail: 19:58:17.2072842     at corlib_System_Collections_Generic_List_1_T_REF__ctor_System_Collections_Generic_IEnumerable_1_T_REF (<anonymous>:wasm-function[5220]:0x14884a)
[19:58:17] fail: 19:58:17.2072878     at System_Linq_System_Linq_Enumerable_ToList_TSource_REF_System_Collections_Generic_IEnumerable_1_TSource_REF (<anonymous>:wasm-function[41812]:0x1061b99)
[19:58:17] fail: 19:58:17.2072914     at invoke_iii (dotnet.js:1:257040)
[19:58:17] fail: 19:58:17.2073103     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[19498]:0x634498)
[19:58:17] fail: 19:58:17.2073142     at invoke_vii (dotnet.js:1:258265)
[19:58:17] fail: 19:58:17.2073360     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[49263]:0x147e013)
[19:58:17] fail: 19:58:17.2073411     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[49292]:0x147ff67)
[19:58:17] fail: 19:58:17.2073448     at invoke_iiiii (dotnet.js:1:257751)
[19:58:17] fail: 19:58:17.2073538     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[19496]:0x632ea3)
[19:58:17] fail: 19:58:17.2073630     at invoke_vii (dotnet.js:1:258265)
[19:58:17] fail: 19:58:17.2073832     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[49262]:0x147de03)
[19:58:17] fail: 19:58:17.2073929     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[49281]:0x147ecb2)
[19:58:17] fail: 19:58:17.2073968     at invoke_iii (dotnet.js:1:257040)
[19:58:17] fail: 19:58:17.2074004     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[14777]:0x42ff1d)
[19:58:17] fail: 19:58:17.2074043     at invoke_vii (dotnet.js:1:258265)
[19:58:17] fail: 19:58:17.2074084     at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[34861]:0x9405c0)
[19:58:17] fail: 19:58:17.2074127     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[14778]:0x4304b3)
[19:58:17] fail: 19:58:17.2074256     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_i4_obj (<anonymous>:wasm-function[431]:0x3ab36)
[19:58:17] fail: 19:58:17.2074647     at invoke_viii (dotnet.js:1:258429)
[19:58:17] fail: 19:58:17.2074847     at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[29638]:0x7eb9c1)
[19:58:17] fail: 19:58:17.2075015     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[26215]:0x762fd6)
[19:58:17] fail: 19:58:17.2075052     at mono_jit_runtime_invoke (<anonymous>:wasm-function[26224]:0x76359f)
[19:58:17] fail: 19:58:17.2083728     at do_runtime_invoke (<anonymous>:wasm-function[6815]:0x1b3201)
[19:58:17] fail: 19:58:17.2083963     at mono_runtime_try_invoke (<anonymous>:wasm-function[1493]:0x66408)
[19:58:17] fail: 19:58:17.2084003     at mono_runtime_invoke (<anonymous>:wasm-function[26028]:0x75a6d6)
[19:58:17] fail: 19:58:17.2084174     at mono_wasm_invoke_method (<anonymous>:wasm-function[25861]:0x7554fb)
[19:58:17] fail: 19:58:17.2084212     at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:249250)
[19:58:17] fail: 19:58:17.2084247     at Object._call_method_with_converted_args (dotnet.js:1:197234)
[19:58:17] fail: 19:58:17.2084279     at Object.call_method (dotnet.js:1:195707)
[19:58:17] fail: 19:58:17.2084317     at dotnet.js:1:203446
[19:58:17] fail: 19:58:17.2084350     at Object.call_assembly_entry_point (dotnet.js:1:203679)
[19:58:17] fail: 19:58:17.2084385     at Object.init (runtime.js:355:24)
[19:58:17] fail: 19:58:17.2084419     at Object.config.loaded_cb (runtime.js:241:8)
[19:58:17] fail: 19:58:17.2084450     at Object._finalize_startup (dotnet.js:1:147787)
[19:58:17] fail: 19:58:17.2084483     at onPendingRequestComplete (dotnet.js:1:148986)
[19:58:17] fail: 19:58:17.2094913     at processFetchResponseBuffer (dotnet.js:1:149306)

[19:58:17] info: console.info: Arguments: --run,WasmTestRunner.dll,System.Xml.XPath.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[19:58:17] info: console.debug: MONO_WASM: Initializing mono runtime
[19:58:17] info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[19:58:17] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[19:58:17] info: console.info: Initializing.....
[19:58:17] info: Discovering: System.Xml.XPath.Tests.dll (method display = ClassAndMethod, method display options = None)
[19:58:17] info: 19:58:17.2628429 Process v8 exited with 1
[19:58:17] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
XHarness artifacts: /home/helixbot/work/96610860/w/B61B09F8/uploads/xharness-output
```

**Comment by radical** [comment]
Not reproducible anymore
