### ISSUE TITLE
run tests with -nocolor option in CI

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#510]
I was recently investigating some test failures like https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190222.1/workItem/System.Net.Ping.Functional.Tests/wilogs

```
~/dotnetbuild/work/4d1f03a2-8a44-4da6-b448-df041fe2cf02/Work/15c6cbee-44ce-42e3-b2bf-ce88affa07a5/Exec ~/dotnetbuild/work/4d1f03a2-8a44-4da6-b448-df041fe2cf02/Work/15c6cbee-44ce-42e3-b2bf-ce88affa07a5/Exec
[37m  Discovering: System.Net.Ping.Functional.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Net.Ping.Functional.Tests (found 38 of 46 test cases)
[m[37m  Starting:    System.Net.Ping.Functional.Tests (parallel test collections = on, max threads = 2)
[m[31;1m    System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest [FAIL]
[m[37m      System.Net.NetworkInformation.PingException : An exception occurred during a Ping request.
[m[37m      ---- System.InvalidOperationException : Cannot process request because the process (3040) has exited.
[m[30;1m      Stack Trace:
[m[37m        /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs(408,0): at System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
[m[37m        /__w/1/s/src/System.Net.Ping/tests/FunctionalTests/PingTest.cs(797,0): at System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest()
[m[37m        --- End of stack trace from previous location where exception was thrown ---
[m[37m        ----- Inner Stack Trace -----
[m[37m        /__w/1/s/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(321,0): at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
[m[37m        /__w/1/s/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(932,0): at System.Diagnostics.Process.EnsureState(State state)
[m[37m        /__w/1/s/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(61,0): at System.Diagnostics.Process.Kill()
[m[37m        /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs(334,0): at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
[m[37m        /__w/1/s/src/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs(48,0): at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[
```

You may notice the garbage characters on each line. 
They are ANSI color sequences and they have absolutely no use when  stdout is not tty terminal.  

With new XUnit, there is -nocolor option  we should always use when redirecting test output.

**Comment by davidsh** [comment]
>This code doesn't live in Arcade any longer. Moving the issue to dotnet/runtime.

Changing the Xunit options is probably in some common file in the repo. Adding the '-nocolor' option is a good idea generally. But making that change would affect all the libraries tests (I think). Still it's a good idea.

**Comment by ViktorHofer** [comment]
> Still it's a good idea.

This is about a recent regression. We have been running with nocolor on CI for quite a while. This regressed when I ported the CoreFX testing framework from Arcade to the runtime repo over. There's no reason to disable color locally.

**Comment by ViktorHofer** [comment]
@wfurt thanks for reporting. Submitted a fix: https://github.com/dotnet/runtime/pull/511
