### ISSUE TITLE
[Android] Failed to find compatible device: arm64-v8a 

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51020]
Nearly 100 test suites are failing on Android arm64 due to not being able to find the compatible device

```
Console log: 'Common.Tests' from job a86ff6d6-3d82-45e5-9d4a-227c66d4ce2b workitem 4c7af79e-0a64-48c9-b126-f434b4ecb4f1 (windows.10.amd64.android.open) executed on machine DNCENGWIN-078

C:\h\w\B22A09B4\w\B10909A9\e>set PATH=C:\h\w\B22A09B4\p/dotnet-cli;C:\python3.9.1\Scripts\;C:\python3.9.1\;C:\python\python37\Scripts\;C:\python\python37\;D:\WINDOWS\system32;D:\WINDOWS;D:\WINDOWS\System32\Wbem;D:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\WINDOWS\System32\OpenSSH\;D:\Users\dotnet-bot\AppData\Local\Programs\Git\cmd;D:\Users\runner\AppData\Local\Microsoft\WindowsApps 

C:\h\w\B22A09B4\w\B10909A9\e>set DOTNET_ROOT=C:\h\w\B22A09B4\p/dotnet-cli 

C:\h\w\B22A09B4\w\B10909A9\e>set DOTNET_CLI_TELEMETRY_OPTOUT=1 

C:\h\w\B22A09B4\w\B10909A9\e>set PATH=C:\h\w\B22A09B4\p/xharness-cli;C:\h\w\B22A09B4\p/dotnet-cli;C:\python3.9.1\Scripts\;C:\python3.9.1\;C:\python\python37\Scripts\;C:\python\python37\;D:\WINDOWS\system32;D:\WINDOWS;D:\WINDOWS\System32\Wbem;D:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\WINDOWS\System32\OpenSSH\;D:\Users\dotnet-bot\AppData\Local\Programs\Git\cmd;D:\Users\runner\AppData\Local\Microsoft\WindowsApps 

C:\h\w\B22A09B4\w\B10909A9\e>set XHARNESS_DISABLE_COLORED_OUTPUT=true 

C:\h\w\B22A09B4\w\B10909A9\e>set XHARNESS_LOG_WITH_TIMESTAMPS=true 

C:\h\w\B22A09B4\w\B10909A9\e>set XHARNESS_CLI_PATH=C:\h\w\B22A09B4\p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21207.1/tools/net6.0/any/Microsoft.DotNet.XHarness.CLI.dll 

C:\h\w\B22A09B4\w\B10909A9\e>call xharness-helix-job.android.bat dotnet exec "C:\h\w\B22A09B4\p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21207.1/tools/net6.0/any/Microsoft.DotNet.XHarness.CLI.dll" android test --app "Common.Tests.apk" --output-directory "C:\h\w\B22A09B4\w\B10909A9\uploads" --timeout "00:30:00" -p="net.dot.Common.Tests" -v -i=net.dot.MonoRunner  
Xharness Helix Wrapper: Arguments: dotnet exec "C:\h\w\B22A09B4\p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21207.1/tools/net6.0/any/Microsoft.DotNet.XHarness.CLI.dll" android test --app "Common.Tests.apk" --output-directory "C:\h\w\B22A09B4\w\B10909A9\uploads" --timeout "00:30:00" -p="net.dot.Common.Tests" -v -i=net.dot.MonoRunner
XHarness command issued: android test --app Common.Tests.apk --output-directory C:\h\w\B22A09B4\w\B10909A9\uploads --timeout 00:30:00 -p=net.dot.Common.Tests -v -i=net.dot.MonoRunner
[09:22:49] dbug: Android Test command called: App = C:\h\w\B22A09B4\w\B10909A9\e\Common.Tests.apk
                 Instrumentation Name = net.dot.MonoRunner
[09:22:49] dbug: Output Directory:C:\h\w\B22A09B4\w\B10909A9\uploads
                 Timeout = 1800 seconds.
[09:22:49] dbug: Arguments to instrumentation:
[09:22:49] dbug: ADBRunner using ADB.exe supplied from C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\tools\net6.0\any\..\..\..\runtimes\any\native\adb\windows\adb.exe
[09:22:49] dbug: Full resolved path:'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe'
[09:22:49] info: Will attempt to run device on detected architecture: 'arm64-v8a'
[09:22:49] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  start-server'
[09:22:49] dbug: 
[09:22:49] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:22:49] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:22:59] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:22:59] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:23:09] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:23:09] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:23:19] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:23:19] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:23:29] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:23:29] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:23:39] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:23:39] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:23:49] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:23:49] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:23:59] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:23:59] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:24:09] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:24:09] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:24:19] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:24:19] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:24:29] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:24:29] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:24:39] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:24:39] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:24:49] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:24:49] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:24:59] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:24:59] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:25:09] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:25:09] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:25:19] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:25:19] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:25:29] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:25:29] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:25:39] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:25:39] dbug: Unexpected response from adb devices -l:
                 Exit code=0
                 Std. Output: List of devices attached
                 
                  
                 Std. Error: 
[09:25:49] dbug: Executing command: 'C:\h\w\B22A09B4\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21207.1\runtimes\any\native\adb\windows\adb.exe  devices -l'
[09:25:49] fail: Error: listing attached devices / emulators: . Check that any emulators have been started, and attached device(s) are connected via USB, powered-on, and unlocked.
[09:25:49] fail: Exception thrown while trying to find compatible device with architecture arm64-v8a
                 System.Exception: One or more attached Android devices are offline
                    at Microsoft.DotNet.XHarness.Android.AdbRunner.GetAttachedDevicesWithProperties(String property) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 412
                    at Microsoft.DotNet.XHarness.Android.AdbRunner.GetAllDevicesToUse(ILogger logger, String apkRequiredProperty, String propertyName) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 453
[09:25:49] crit: Failed to run test package: Failed to find compatible device: arm64-v8a
                 System.Exception: Failed to run test package: Failed to find compatible device: arm64-v8a
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidInstallCommand.InvokeHelper(ILogger logger, String apkPackageName, String appPackagePath, String apkRequiredArchitecture, String deviceId, AdbRunner runner) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs:line 117
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 77
XHarness exit code: 71 (GENERAL_FAILURE)
 Fri 04/09/2021- 9:25:49.98
 Fri 04/09/2021- 9:25:50.37
2021-04-09 09:25:50,933: INFO: 5012: run(82): main: Main thread starting 10 workers
Worker 0: starting...
Worker 1: starting...
Worker 2: starting...
Worker 3: starting...
Worker 4: starting...
Worker 5: starting...
Worker 6: starting...
Worker 7: starting...
Worker 8: starting...
Worker 9: starting...
2021-04-09 09:25:50,933: INFO: 5012: run(89): main: Beginning reading of test results.
2021-04-09 09:25:50,933: INFO: 5012: run(98): main: Uploading results in batches of size 1000
2021-04-09 09:25:50,933: INFO: 5012: run(103): main: Main thread finished queueing batches
2021-04-09 09:25:50,933: INFO: 5012: run(107): main: Main thread exiting
Searching 'C:\h\w\B22A09B4\w\B10909A9\e\..' for log files
Found log 'C:\h\w\B22A09B4\w\B10909A9\e\..\console.c12f304a.log'
Uri 'https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50095-merge-a86ff6d63d8245e59d/Common.Tests/console.c12f304a.log?sv=2019-07-07&se=2021-04-29T16%3A22%3A32Z&sr=c&sp=rl&sig=AelVJ3%2F49S%2BlKx6HiyAaiHJqg4JakvlZtWc9rq3ednQ%3D'
Generated log list: console.c12f304a.log:
  https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50095-merge-a86ff6d63d8245e59d/Common.Tests/console.c12f304a.log?sv=2019-07-07&se=2021-04-29T16%3A22%3A32Z&sr=c&sp=rl&sig=AelVJ3%2F49S%2BlKx6HiyAaiHJqg4JakvlZtWc9rq3ednQ%3D

Searching 'C:\h\w\B22A09B4\w\B10909A9\e' for test results files
Searching 'C:\h\w\B22A09B4\w\B10909A9\uploads' for test results files
No results file found in any of the following formats: xunit, junit, trx
 Fri 04/09/2021- 9:25:50.96
```

**Comment by steveisok** [comment]
This happens when the devices panic and need manual intervention in order to come back online.  Nothing we can do from a runtime perspective.
