### ISSUE TITLE
[wasm][aot] Tests timing out - `System.Collections.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51037]
[Logs for System.Collections.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-b46de50534b546c4b0/System.Collections.Tests/console.9a30e429.log?sv=2019-07-07&se=2021-04-29T20%3A52%3A18Z&sr=c&sp=rl&sig=laqAoCBV6F8dj9Rk%2BSRtLkM6qvQPlv71zJ4G3JBoJ4o%3D)

```
[21:30:10] info: Starting:    System.Collections.Tests.dll

[21:32:55] fail: 21:32:55.6321523 console.error: RuntimeError: memory access out of bounds
[21:32:55] fail: 21:32:55.6486420 console.error: RuntimeError: memory access out of bounds

[21:32:55] fail: 21:32:55.6486963     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF__ctor_Xunit_Abstractions_ITest_Xunit_Sdk_IMessageBus_System_Type_object___System_Reflection_MethodInfo_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8403]:0x28f34f)
[21:32:55] fail: 21:32:55.6487035     at xunit_execution_dotnet_Xunit_Sdk_XunitTestInvoker__ctor_Xunit_Abstractions_ITest_Xunit_Sdk_IMessageBus_System_Type_object___System_Reflection_MethodInfo_object___System_Collections_Generic_IReadOnlyList_1_Xunit_Sdk_BeforeAfterTestAttribute_Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8344]:0x271134)
[21:32:55] fail: 21:32:55.6487170     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestMethodAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[19480]:0x62af92)
[21:32:55] fail: 21:32:55.6487216     at invoke_iiii (dotnet.js:1:256935)
[21:32:55] fail: 21:32:55.6487252     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_MoveNext (<anonymous>:wasm-function[8342]:0x270a3f)
[21:32:55] fail: 21:32:55.6487524     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6487574     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_ (<anonymous>:wasm-function[20316]:0x67c754)
[21:32:55] fail: 21:32:55.6487613     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[19481]:0x62b081)
[21:32:55] fail: 21:32:55.6487649     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__c__DisplayClass43_0_TTestCase_REF__RunAsyncb__0 (<anonymous>:wasm-function[19587]:0x6419fc)
[21:32:55] fail: 21:32:55.6487900     at xunit_execution_dotnet_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_1_System_Tuple_2_System_Decimal_string_invoke_TResult (<anonymous>:wasm-function[19371]:0x61a469)
[21:32:55] fail: 21:32:55.6487939     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6487982     at xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_T_REF_MoveNext (<anonymous>:wasm-function[8686]:0x2b63e3)
[21:32:55] fail: 21:32:55.6488019     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6488230     at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[21086]:0x6c790c)
[21:32:55] fail: 21:32:55.6488274     at xunit_core_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[8724]:0x2bc057)
[21:32:55] fail: 21:32:55.6488309     at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_T_REF_System_Func_1_System_Threading_Tasks_Task_1_T_REF (<anonymous>:wasm-function[20920]:0x6b8663)
[21:32:55] fail: 21:32:55.6488340     at invoke_iiii (dotnet.js:1:256935)
[21:32:55] fail: 21:32:55.6488430     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8381]:0x2836b6)
[21:32:55] fail: 21:32:55.6488468     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6488504     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__9 (<anonymous>:wasm-function[20330]:0x67e4ae)
[21:32:55] fail: 21:32:55.6488904     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[8547]:0x2af4e9)
[21:32:55] fail: 21:32:55.6489053     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8383]:0x28553b)
[21:32:55] fail: 21:32:55.6489092     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6489304     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_MoveNext (<anonymous>:wasm-function[8337]:0x267884)
[21:32:55] fail: 21:32:55.6489335     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6489366     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_ (<anonymous>:wasm-function[20314]:0x67c336)
[21:32:55] fail: 21:32:55.6489398     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[19476]:0x62ac21)
[21:32:55] fail: 21:32:55.6489433     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6489570     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8438]:0x29d72f)
[21:32:55] fail: 21:32:55.6489660     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6489798     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[20338]:0x68025a)
[21:32:55] fail: 21:32:55.6489904     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[8554]:0x2af80e)
[21:32:55] fail: 21:32:55.6497189     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[4059]:0xfffc6)
[21:32:55] fail: 21:32:55.6497409     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19467]:0x62a435)
[21:32:55] fail: 21:32:55.6497447     at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[19482]:0x62b205)
[21:32:55] fail: 21:32:55.6497606     at invoke_iiii (dotnet.js:1:256935)
[21:32:55] fail: 21:32:55.6497639     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCasesAsyncd__32_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8389]:0x2875ee)
[21:32:55] fail: 21:32:55.6497671     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6497892     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[20331]:0x67e858)
[21:32:55] fail: 21:32:55.6498001     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[8548]:0x2af55c)
[21:32:55] fail: 21:32:55.6498035     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunTestCasesAsync (<anonymous>:wasm-function[19618]:0x645676)
[21:32:55] fail: 21:32:55.6498067     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6498104     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__31_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8391]:0x288372)
[21:32:55] fail: 21:32:55.6498137     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6498173     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[20332]:0x67ec02)
[21:32:55] fail: 21:32:55.6498380     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[8549]:0x2af5cf)
[21:32:55] fail: 21:32:55.6498422     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8393]:0x2899b0)
[21:32:55] fail: 21:32:55.6498514     at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[19526]:0x6335a2)
[21:32:55] fail: 21:32:55.6498730     at invoke_iiiiiii (dotnet.js:1:258493)
[21:32:55] fail: 21:32:55.6498766     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMethodsAsyncd__38_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8430]:0x29a048)
[21:32:55] fail: 21:32:55.6498800     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6498833     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[20336]:0x67fb10)
[21:32:55] fail: 21:32:55.6498869     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[8552]:0x2af728)
[21:32:55] fail: 21:32:55.6499079     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunTestMethodsAsync (<anonymous>:wasm-function[19692]:0x649fc9)
[21:32:55] fail: 21:32:55.6499119     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6499150     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__37_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8432]:0x29b2b1)
[21:32:55] fail: 21:32:55.6499189     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6499221     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[20337]:0x67feba)
[21:32:55] fail: 21:32:55.6499347     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[8553]:0x2af79b)
[21:32:55] fail: 21:32:55.6499383     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8434]:0x29cbee)
[21:32:55] fail: 21:32:55.6499595     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[19506]:0x62fde0)
[21:32:55] fail: 21:32:55.6499637     at invoke_iiiiii (dotnet.js:1:256755)
[21:32:55] fail: 21:32:55.6499669     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTestClassesAsyncd__28_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8420]:0x293b09)
[21:32:55] fail: 21:32:55.6499714     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6499749     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[20334]:0x67f3c6)
[21:32:55] fail: 21:32:55.6499838     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[8550]:0x2af642)
[21:32:55] fail: 21:32:55.6499877     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunTestClassesAsync (<anonymous>:wasm-function[19667]:0x6484ec)
[21:32:55] fail: 21:32:55.6499912     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6499951     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyncd__27_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8422]:0x294c80)
[21:32:55] fail: 21:32:55.6500139     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6500180     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[20335]:0x67f770)
[21:32:55] fail: 21:32:55.6500213     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[8551]:0x2af6b5)
[21:32:55] fail: 21:32:55.6500247     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8424]:0x29657a)
[21:32:55] fail: 21:32:55.6500283     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19559]:0x637c92)
[21:32:55] fail: 21:32:55.6500373     at invoke_iiiiiii (dotnet.js:1:258493)
[21:32:55] fail: 21:32:55.6500409     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCollectionsAsyncd__42_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8444]:0x29f7c8)
[21:32:55] fail: 21:32:55.6500533     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6500575     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[20339]:0x6805fb)
[21:32:55] fail: 21:32:55.6500639     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[8555]:0x2af881)
[21:32:55] fail: 21:32:55.6500674     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8448]:0x2a2b57)
[21:32:55] fail: 21:32:55.6500815     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19549]:0x6375c0)
[21:32:55] fail: 21:32:55.6500851     at invoke_iiiii (dotnet.js:1:257287)
[21:32:55] fail: 21:32:55.6500885     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_MoveNext (<anonymous>:wasm-function[8372]:0x27d552)
[21:32:55] fail: 21:32:55.6500920     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6501121     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[20325]:0x67d9db)
[21:32:55] fail: 21:32:55.6501166     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19558]:0x637b39)
[21:32:55] fail: 21:32:55.6501200     at invoke_iiiii (dotnet.js:1:257287)
[21:32:55] fail: 21:32:55.6501235     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd__41_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8446]:0x2a0cbe)
[21:32:55] fail: 21:32:55.6501273     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6501378     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[20340]:0x6809be)
[21:32:55] fail: 21:32:55.6501413     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[8556]:0x2af8f4)
[21:32:55] fail: 21:32:55.6501543     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19718]:0x64c803)
[21:32:55] fail: 21:32:55.6501581     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6501670     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_MoveNext (<anonymous>:wasm-function[8351]:0x2726ab)
[21:32:55] fail: 21:32:55.6501706     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6501742     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[20318]:0x67cb72)
[21:32:55] fail: 21:32:55.6501839     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[19493]:0x62db73)
[21:32:55] fail: 21:32:55.6502079     at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[19653]:0x6479fd)
[21:32:55] fail: 21:32:55.6502154     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[18843]:0x5dfc85)
[21:32:55] fail: 21:32:55.6502188     at invoke_viiiii (dotnet.js:1:258677)
[21:32:55] fail: 21:32:55.6502225     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[18772]:0x5d62eb)
[21:32:55] fail: 21:32:55.6502256     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6502288     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[55153]:0x15637e8)
[21:32:55] fail: 21:32:55.6502530     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[55182]:0x1565745)
[21:32:55] fail: 21:32:55.6502626     at invoke_iiiii (dotnet.js:1:257287)
[21:32:55] fail: 21:32:55.6502661     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[18770]:0x5d35a8)
[21:32:55] fail: 21:32:55.6502695     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6502729     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[55152]:0x15635d8)
[21:32:55] fail: 21:32:55.6502763     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[55171]:0x1564487)
[21:32:55] fail: 21:32:55.6513545     at invoke_iii (dotnet.js:1:256576)
[21:32:55] fail: 21:32:55.6513666     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[14328]:0x40e13d)
[21:32:55] fail: 21:32:55.6515953     at invoke_vii (dotnet.js:1:257801)
[21:32:55] fail: 21:32:55.6516031     at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[34921]:0x91e7b2)
[21:32:55] fail: 21:32:55.6516067     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[14329]:0x40e6d3)
[21:32:55] fail: 21:32:55.6516173     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_i4_obj (<anonymous>:wasm-function[467]:0x41174)
[21:32:55] fail: 21:32:55.6516204     at invoke_viii (dotnet.js:1:257965)
[21:32:55] fail: 21:32:55.6516237     at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[29560]:0x7b2589)
[21:32:55] fail: 21:32:55.6516269     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[26142]:0x729c1e)
[21:32:55] fail: 21:32:55.6516301     at mono_jit_runtime_invoke (<anonymous>:wasm-function[26151]:0x72a1e7)
[21:32:55] fail: 21:32:55.6516356     at do_runtime_invoke (<anonymous>:wasm-function[6516]:0x1add54)
[21:32:55] fail: 21:32:55.6516385     at mono_runtime_try_invoke (<anonymous>:wasm-function[1462]:0x680ab)
[21:32:55] fail: 21:32:55.6516464     at mono_runtime_invoke (<anonymous>:wasm-function[25955]:0x72131e)
[21:32:55] fail: 21:32:55.6518910     at mono_wasm_invoke_method (<anonymous>:wasm-function[25788]:0x71c143)
[21:32:55] fail: 21:32:55.6518986     at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:248790)
[21:32:55] fail: 21:32:55.6519020     at Object._call_method_with_converted_args (dotnet.js:1:197234)
[21:32:55] fail: 21:32:55.6519050     at Object.call_method (dotnet.js:1:195707)
[21:32:55] fail: 21:32:55.6519081     at dotnet.js:1:203446
[21:32:55] fail: 21:32:55.6519112     at Object.call_assembly_entry_point (dotnet.js:1:203679)
[21:32:55] fail: 21:32:55.6519263     at Object.init (runtime.js:355:24)
[21:32:55] fail: 21:32:55.6519294     at Object.config.loaded_cb (runtime.js:241:8)
[21:32:55] fail: 21:32:55.6519322     at Object._finalize_startup (dotnet.js:1:147787)
[21:32:55] fail: 21:32:55.6519355     at onPendingRequestComplete (dotnet.js:1:148986)
[21:32:55] fail: 21:32:55.6519384     at processFetchResponseBuffer (dotnet.js:1:149306)

[21:32:55] info: 21:32:55.6973552 Process v8 exited with 1
[21:32:55] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)

```

**Comment by radical** [comment]
Instead of a crash, tests are timing out now: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50885-merge-0e7ebf1b0da04b00b1/System.Collections.Tests/console.603fc8fc.log?sv=2019-07-07&se=2021-05-12T02%3A28%3A52Z&sr=c&sp=rl&sig=XfNwfMkn0ixVuoIGUXmVbXd2Ii65btZ5xFSp0cRA%2FLQ%3D

**Comment by radical** [comment]
All the tests are passing now. [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-3dd81fa5d0b34cd8a4/System.Collections.Tests/console.ae495d47.log?sv=2019-07-07&)

`[10:45:17] info: Total: 32456, Errors: 0, Failed: 0, Skipped: 139, Time: 275.606078s`

The build part of it took `Time Elapsed 00:11:38.07`.
