### ISSUE TITLE
[wasm][aot] `RuntimeError: memory access out of bounds` in `System.Xml.RW.XmlWriterApi.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51038]
[Logs for  System.Xml.RW.XmlWriterApi.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-b46de50534b546c4b0/System.Xml.RW.XmlWriterApi.Tests/console.b9b7d324.log?sv=2019-07-07&se=2021-04-29T20%3A52%3A18Z&sr=c&sp=rl&sig=laqAoCBV6F8dj9Rk%2BSRtLkM6qvQPlv71zJ4G3JBoJ4o%3D)

```
[21:40:20] info: Starting:    System.Xml.RW.XmlWriterApi.Tests.dll
[21:40:29] fail: 21:40:29.4995918 console.error: RuntimeError: memory access out of bounds
[21:40:29] fail: 21:40:29.5197638 console.error: RuntimeError: memory access out of bounds

[21:40:29] fail: 21:40:29.5198314     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF__ctor_Xunit_Abstractions_ITest_Xunit_Sdk_IMessageBus_System_Type_object___System_Reflection_MethodInfo_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8910]:0x2c97f6)
[21:40:29] fail: 21:40:29.5198646     at xunit_execution_dotnet_Xunit_Sdk_XunitTestInvoker__ctor_Xunit_Abstractions_ITest_Xunit_Sdk_IMessageBus_System_Type_object___System_Reflection_MethodInfo_object___System_Collections_Generic_IReadOnlyList_1_Xunit_Sdk_BeforeAfterTestAttribute_Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8850]:0x2ab5c5)
[21:40:29] fail: 21:40:29.5198726     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestMethodAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[20637]:0x7c9719)
[21:40:29] fail: 21:40:29.5198771     at invoke_iiii (dotnet.js:1:257956)
[21:40:29] fail: 21:40:29.5198864     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_MoveNext (<anonymous>:wasm-function[8848]:0x2aaed0)
[21:40:29] fail: 21:40:29.5199176     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5199226     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_ (<anonymous>:wasm-function[21478]:0x81b953)
[21:40:29] fail: 21:40:29.5199319     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[20638]:0x7c9808)
[21:40:29] fail: 21:40:29.5199355     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__c__DisplayClass43_0_TTestCase_REF__RunAsyncb__0 (<anonymous>:wasm-function[20744]:0x7e015f)
[21:40:29] fail: 21:40:29.5199535     at xunit_execution_dotnet_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_1_System_Tuple_2_System_Decimal_string_invoke_TResult (<anonymous>:wasm-function[20559]:0x7bdc8f)
[21:40:29] fail: 21:40:29.5199577     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5199624     at xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_T_REF_MoveNext (<anonymous>:wasm-function[9194]:0x2f0887)
[21:40:29] fail: 21:40:29.5199661     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5199883     at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[22087]:0x8594f9)
[21:40:29] fail: 21:40:29.5199929     at xunit_core_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[9233]:0x2f650d)
[21:40:29] fail: 21:40:29.5199965     at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_T_REF_System_Func_1_System_Threading_Tasks_Task_1_T_REF (<anonymous>:wasm-function[21912]:0x84980a)
[21:40:29] fail: 21:40:29.5199998     at invoke_iiii (dotnet.js:1:257956)
[21:40:29] fail: 21:40:29.5200031     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8887]:0x2bdb3d)
[21:40:29] fail: 21:40:29.5200118     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5200151     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__9 (<anonymous>:wasm-function[21492]:0x81d6ad)
[21:40:29] fail: 21:40:29.5200422     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[9052]:0x2e9964)
[21:40:29] fail: 21:40:29.5200590     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8889]:0x2bf9c2)
[21:40:29] fail: 21:40:29.5200684     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5200804     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_MoveNext (<anonymous>:wasm-function[8843]:0x2a1d21)
[21:40:29] fail: 21:40:29.5200839     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5200872     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_ (<anonymous>:wasm-function[21476]:0x81b535)
[21:40:29] fail: 21:40:29.5200906     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[20633]:0x7c93a8)
[21:40:29] fail: 21:40:29.5200945     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5201047     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8945]:0x2d7bd5)
[21:40:29] fail: 21:40:29.5201204     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5201381     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[21500]:0x81f459)
[21:40:29] fail: 21:40:29.5201475     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[9059]:0x2e9c89)
[21:40:29] fail: 21:40:29.5210468     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[4319]:0x10eb65)
[21:40:29] fail: 21:40:29.5210692     at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20624]:0x7c8bbc)
[21:40:29] fail: 21:40:29.5210739     at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[20639]:0x7c998c)
[21:40:29] fail: 21:40:29.5210886     at invoke_iiii (dotnet.js:1:257956)
[21:40:29] fail: 21:40:29.5210923     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCasesAsyncd__32_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8896]:0x2c1a9c)
[21:40:29] fail: 21:40:29.5210959     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5211194     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[21493]:0x81da57)
[21:40:29] fail: 21:40:29.5211292     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[9053]:0x2e99d7)
[21:40:29] fail: 21:40:29.5211329     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunTestCasesAsync (<anonymous>:wasm-function[20774]:0x7e3dc7)
[21:40:29] fail: 21:40:29.5211361     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5211394     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__31_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8898]:0x2c2820)
[21:40:29] fail: 21:40:29.5211428     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5211461     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[21494]:0x81de01)
[21:40:29] fail: 21:40:29.5211673     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[9054]:0x2e9a4a)
[21:40:29] fail: 21:40:29.5211718     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8900]:0x2c3e5e)
[21:40:29] fail: 21:40:29.5211806     at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[20683]:0x7d1d24)
[21:40:29] fail: 21:40:29.5211950     at invoke_iiiiiii (dotnet.js:1:260071)
[21:40:29] fail: 21:40:29.5211987     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMethodsAsyncd__38_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8937]:0x2d44ee)
[21:40:29] fail: 21:40:29.5212020     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5212052     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[21498]:0x81ed0f)
[21:40:29] fail: 21:40:29.5212087     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[9057]:0x2e9ba3)
[21:40:29] fail: 21:40:29.5212400     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunTestMethodsAsync (<anonymous>:wasm-function[20848]:0x7e8716)
[21:40:29] fail: 21:40:29.5212444     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5212478     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__37_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8939]:0x2d5757)
[21:40:29] fail: 21:40:29.5212509     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5212541     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[21499]:0x81f0b9)
[21:40:29] fail: 21:40:29.5212627     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[9058]:0x2e9c16)
[21:40:29] fail: 21:40:29.5212664     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8941]:0x2d7094)
[21:40:29] fail: 21:40:29.5212917     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[20663]:0x7ce563)
[21:40:29] fail: 21:40:29.5212962     at invoke_iiiiii (dotnet.js:1:257776)
[21:40:29] fail: 21:40:29.5212997     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTestClassesAsyncd__28_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8927]:0x2cdfac)
[21:40:29] fail: 21:40:29.5213033     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5213068     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[21496]:0x81e5c5)
[21:40:29] fail: 21:40:29.5213156     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[9055]:0x2e9abd)
[21:40:29] fail: 21:40:29.5213193     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunTestClassesAsync (<anonymous>:wasm-function[20823]:0x7e6c3a)
[21:40:29] fail: 21:40:29.5213228     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5213261     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyncd__27_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8929]:0x2cf123)
[21:40:29] fail: 21:40:29.5213442     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5213482     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[21497]:0x81e96f)
[21:40:29] fail: 21:40:29.5213537     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[9056]:0x2e9b30)
[21:40:29] fail: 21:40:29.5213570     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8931]:0x2d0a1d)
[21:40:29] fail: 21:40:29.5213605     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20716]:0x7d6412)
[21:40:29] fail: 21:40:29.5213690     at invoke_iiiiiii (dotnet.js:1:260071)
[21:40:29] fail: 21:40:29.5213726     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCollectionsAsyncd__42_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8950]:0x2d9c5a)
[21:40:29] fail: 21:40:29.5213859     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5213901     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[21501]:0x81f7fa)
[21:40:29] fail: 21:40:29.5214008     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[9060]:0x2e9cfc)
[21:40:29] fail: 21:40:29.5214047     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8954]:0x2dcfe9)
[21:40:29] fail: 21:40:29.5214082     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20706]:0x7d5d40)
[21:40:29] fail: 21:40:29.5214115     at invoke_iiiii (dotnet.js:1:258308)
[21:40:29] fail: 21:40:29.5214146     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_MoveNext (<anonymous>:wasm-function[8878]:0x2b79df)
[21:40:29] fail: 21:40:29.5214179     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5214383     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[21487]:0x81cbda)
[21:40:29] fail: 21:40:29.5214422     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20715]:0x7d62b9)
[21:40:29] fail: 21:40:29.5214455     at invoke_iiiii (dotnet.js:1:258308)
[21:40:29] fail: 21:40:29.5214593     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd__41_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8952]:0x2db150)
[21:40:29] fail: 21:40:29.5214632     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5214665     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[21502]:0x81fbbd)
[21:40:29] fail: 21:40:29.5214700     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[9061]:0x2e9d6f)
[21:40:29] fail: 21:40:29.5214889     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[20874]:0x7eaf4a)
[21:40:29] fail: 21:40:29.5214932     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5214966     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_MoveNext (<anonymous>:wasm-function[8857]:0x2acb3a)
[21:40:29] fail: 21:40:29.5214999     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5215031     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[21480]:0x81bd71)
[21:40:29] fail: 21:40:29.5215125     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20650]:0x7cc2f9)
[21:40:29] fail: 21:40:29.5215368     at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20809]:0x7e614b)
[21:40:29] fail: 21:40:29.5215461     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20138]:0x78d5ce)
[21:40:29] fail: 21:40:29.5215498     at invoke_viiiii (dotnet.js:1:259315)
[21:40:29] fail: 21:40:29.5215531     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[20073]:0x784de3)
[21:40:29] fail: 21:40:29.5215565     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5215597     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[52764]:0x12bf6a2)
[21:40:29] fail: 21:40:29.5215824     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[52793]:0x12c15f6)
[21:40:29] fail: 21:40:29.5215900     at invoke_iiiii (dotnet.js:1:258308)
[21:40:29] fail: 21:40:29.5215937     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[20071]:0x7820a0)
[21:40:29] fail: 21:40:29.5215971     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5216003     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[52763]:0x12bf492)
[21:40:29] fail: 21:40:29.5216138     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[52782]:0x12c0341)
[21:40:29] fail: 21:40:29.5216178     at invoke_iii (dotnet.js:1:257597)
[21:40:29] fail: 21:40:29.5216231     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[14932]:0x4556ef)
[21:40:29] fail: 21:40:29.5216384     at invoke_vii (dotnet.js:1:258822)
[21:40:29] fail: 21:40:29.5216470     at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[36350]:0xab2a46)
[21:40:29] fail: 21:40:29.5216508     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[14933]:0x455c85)
[21:40:29] fail: 21:40:29.5216540     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_i4_obj (<anonymous>:wasm-function[425]:0x3cd07)
[21:40:29] fail: 21:40:29.5216573     at invoke_viii (dotnet.js:1:258986)
[21:40:29] fail: 21:40:29.5216606     at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[30849]:0x93e965)
[21:40:29] fail: 21:40:29.5216640     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[27413]:0x8b563f)
[21:40:29] fail: 21:40:29.5216725     at mono_jit_runtime_invoke (<anonymous>:wasm-function[27422]:0x8b5c08)
[21:40:29] fail: 21:40:29.5216764     at do_runtime_invoke (<anonymous>:wasm-function[6821]:0x1c9d75)
[21:40:29] fail: 21:40:29.5216797     at mono_runtime_try_invoke (<anonymous>:wasm-function[1516]:0x6c0c0)
[21:40:29] fail: 21:40:29.5216830     at mono_runtime_invoke (<anonymous>:wasm-function[27226]:0x8acd3f)
[21:40:29] fail: 21:40:29.5216958     at mono_wasm_invoke_method (<anonymous>:wasm-function[27059]:0x8a7b64)
[21:40:29] fail: 21:40:29.5216997     at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:249669)
[21:40:29] fail: 21:40:29.5217032     at Object._call_method_with_converted_args (dotnet.js:1:197234)
[21:40:29] fail: 21:40:29.5217123     at Object.call_method (dotnet.js:1:195707)
[21:40:29] fail: 21:40:29.5217160     at dotnet.js:1:203446
[21:40:29] fail: 21:40:29.5217196     at Object.call_assembly_entry_point (dotnet.js:1:203679)
[21:40:29] fail: 21:40:29.5217230     at Object.init (runtime.js:355:24)
[21:40:29] fail: 21:40:29.5217264     at Object.config.loaded_cb (runtime.js:241:8)
[21:40:29] fail: 21:40:29.5217297     at Object._finalize_startup (dotnet.js:1:147787)
[21:40:29] fail: 21:40:29.5217330     at onPendingRequestComplete (dotnet.js:1:148986)
[21:40:29] fail: 21:40:29.5230681     at processFetchResponseBuffer (dotnet.js:1:149306)

[21:40:29] info: 21:40:29.5661768 Process v8 exited with 1
[21:40:29] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by radical** [comment]
Not reproducible anymore.
