### ISSUE TITLE
[wasm][aot] `RuntimeError: memory access out of bounds` in `System.Xml.XmlSchemaSet.Test`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51040]
[Logs for System.Xml.XmlSchemaSet.Test](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-b46de50534b546c4b0/System.Xml.XmlSchemaSet.Tests/console.990917d2.log?sv=2019-07-07&se=2021-04-29T20%3A52%3A18Z&sr=c&sp=rl&sig=laqAoCBV6F8dj9Rk%2BSRtLkM6qvQPlv71zJ4G3JBoJ4o%3D)

```
XHarness command issued: wasm test --app=. --output-directory=/home/helixbot/work/A95F0914/w/B3B90974/uploads/xharness-output --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js -- --run WasmTestRunner.dll System.Xml.XmlSchemaSet.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.Xml.XmlSchemaSet.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
console.error: RuntimeError: memory access out of bounds
console.error: RuntimeError: memory access out of bounds
    at xunit_execution_dotnet_Xunit_Sdk_TestMessage__ctor_Xunit_Abstractions_ITest (<anonymous>:wasm-function[3318]:0xf4c9d)
    at xunit_execution_dotnet_Xunit_Sdk_TestResultMessage__ctor_Xunit_Abstractions_ITest_System_Decimal_string (<anonymous>:wasm-function[3995]:0x136cfc)
    at xunit_execution_dotnet_Xunit_Sdk_TestPassed__ctor_Xunit_Abstractions_ITest_System_Decimal_string (<anonymous>:wasm-function[23488]:0x95e9dd)
    at invoke_viiiii (dotnet.js:1:259242)
    at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10588]:0x4158df)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__9 (<anonymous>:wasm-function[24236]:0x99bd16)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[10753]:0x4412f2)
    at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[10590]:0x416dff)
    at invoke_iii (dotnet.js:1:257336)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_MoveNext (<anonymous>:wasm-function[10544]:0x3f914c)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_ (<anonymous>:wasm-function[24220]:0x999b9e)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[23375]:0x947b4c)
    at invoke_iii (dotnet.js:1:257336)
    at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10647]:0x42f4cf)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[24244]:0x99dac2)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[10760]:0x441617)
    at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[5020]:0x1a0e7f)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[23366]:0x947360)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[23381]:0x948130)
    at invoke_iiii (dotnet.js:1:257695)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCasesAsyncd__32_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10598]:0x419390)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[24237]:0x99c0c0)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[10754]:0x441365)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunTestCasesAsync (<anonymous>:wasm-function[23519]:0x96272d)
    at invoke_iii (dotnet.js:1:257336)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__31_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10600]:0x41a114)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[24238]:0x99c46a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[10755]:0x4413d8)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[10602]:0x41b752)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[23425]:0x9504cd)
    at invoke_iiiiiii (dotnet.js:1:259998)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMethodsAsyncd__38_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10639]:0x42bde8)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[24242]:0x99d378)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[10758]:0x441531)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunTestMethodsAsync (<anonymous>:wasm-function[23593]:0x967080)
    at invoke_iii (dotnet.js:1:257336)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__37_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10641]:0x42d051)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[24243]:0x99d722)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[10759]:0x4415a4)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[10643]:0x42e98e)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[23405]:0x94cd08)
    at invoke_iiiiii (dotnet.js:1:257515)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTestClassesAsyncd__28_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10629]:0x4258ab)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[24240]:0x99cc2e)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[10756]:0x44144b)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunTestClassesAsync (<anonymous>:wasm-function[23568]:0x9655a3)
    at invoke_iii (dotnet.js:1:257336)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyncd__27_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10631]:0x426a22)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[24241]:0x99cfd8)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[10757]:0x4414be)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[10633]:0x42831c)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[23458]:0x954bbb)
    at invoke_iiiiiii (dotnet.js:1:259998)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCollectionsAsyncd__42_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10651]:0x43152d)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[24245]:0x99de63)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[10761]:0x44168a)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[10655]:0x4348bc)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[23448]:0x9544e9)
    at invoke_iiiii (dotnet.js:1:258047)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_MoveNext (<anonymous>:wasm-function[10579]:0x40ee17)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[24231]:0x99b243)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[23457]:0x954a62)
    at invoke_iiiii (dotnet.js:1:258047)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd__41_TTestCase_REF_MoveNext (<anonymous>:wasm-function[10653]:0x432a23)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[24246]:0x99e226)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[10762]:0x4416fd)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[23619]:0x9698ba)
    at invoke_iii (dotnet.js:1:257336)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_MoveNext (<anonymous>:wasm-function[10558]:0x403f72)
    at invoke_vii (dotnet.js:1:258561)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[24224]:0x99a3da)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[23392]:0x94aa9d)
    at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[23554]:0x964ab4)
    at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[22848]:0x907945)
    at invoke_viiiii (dotnet.js:1:259242)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[22782]:0x8ff119)
    at invoke_vii (dotnet.js:1:258561)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[55184]:0x1426d57)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[55213]:0x1428cb4)
    at invoke_iiiii (dotnet.js:1:258047)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[22780]:0x8fc3d6)
    at invoke_vii (dotnet.js:1:258561)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[55183]:0x1426b47)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[55202]:0x14279f6)
    at invoke_iii (dotnet.js:1:257336)
    at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[16749]:0x5b7cee)
    at invoke_vii (dotnet.js:1:258561)
    at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[39600]:0xc5d791)
    at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[16750]:0x5b8284)
    at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_i4_obj (<anonymous>:wasm-function[475]:0x41db3)
    at invoke_viii (dotnet.js:1:258725)
    at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[33457]:0xac0c90)
    at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[30033]:0xa3804e)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[30042]:0xa38617)
    at do_runtime_invoke (<anonymous>:wasm-function[7835]:0x28d8ff)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1668]:0x7d9bf)
    at mono_runtime_invoke (<anonymous>:wasm-function[29845]:0xa2f3bb)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[29678]:0xa2a1dd)
    at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:249404)
    at Object._call_method_with_converted_args (dotnet.js:1:197600)
    at Object.call_method (dotnet.js:1:196073)
    at dotnet.js:1:203812
    at Object.call_assembly_entry_point (dotnet.js:1:204045)
    at Object.init (runtime.js:355:24)
    at Object.config.loaded_cb (runtime.js:241:8)
    at Object._finalize_startup (dotnet.js:1:148153)
    at onPendingRequestComplete (dotnet.js:1:149352)
    at processFetchResponseBuffer (dotnet.js:1:149672)

[21:40:57] info: console.info: Arguments: --run,WasmTestRunner.dll,System.Xml.XmlSchemaSet.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[21:40:57] info: console.debug: MONO_WASM: Initializing mono runtime
[21:40:57] info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[21:40:57] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[21:40:57] info: console.info: Initializing.....
[21:40:57] info: Discovering: System.Xml.XmlSchemaSet.Tests.dll (method display = ClassAndMethod, method display options = None)
[21:40:57] info: Discovered:  System.Xml.XmlSchemaSet.Tests.dll (found 322 of 324 test cases)
[21:40:57] info: Starting:    System.Xml.XmlSchemaSet.Tests.dll

Process v8 exited with 1
[21:40:57] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
XHarness artifacts: /home/helixbot/work/A95F0914/w/B3B90974/uploads/xharness-output

```

**Comment by vargaz** [comment]
Can't reproduce this using:
./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Private.Xml/tests/XmlSchema/XmlSchemaSet/

**Comment by radical** [comment]
Can't reproduce this in https://github.com/dotnet/runtime/pull/50885 .
