### ISSUE TITLE
HttpStress.csproj fails to build again

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#51117]
According to [the log](https://dev.azure.com/dnceng/public/_build?definitionId=694) a change between  #50265 and #50244 broke the HttpStress builds:
https://dev.azure.com/dnceng/public/_build/results?buildId=1078046&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=8ca65746-3bfa-57bf-9141-d805b5d39db5

Call stack:
```
C:\Program Files\dotnet\sdk\5.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.IO.Strategies.SyncWindowsFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/SyncWindowsFileStreamStrategy.cs:line 64
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs:line 778
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs:line 167
   at System.IO.Stream.Close() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 165
   at System.IO.BinaryWriter.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/BinaryWriter.cs:line 75
   at System.IO.BinaryWriter.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/IO/BinaryWriter.cs:line 81
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteToCacheFile()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\app\HttpStress.csproj]
```

@ViktorHofer any hints?

**Comment by ViktorHofer** [comment]
Taking a look now

**Comment by ViktorHofer** [comment]
Without a binlog (which isn't produced nor uploaded) this is really hard to diagnose.

**Comment by antonfirsov** [comment]
I have a local repro. How can I get the binlog(s) that can help diagnosing this?

Here is the PR history between the last successful and the first failing CI run, in case any of them is obviously suspicious:

- [wasm] Add targets to run samples (#50244)
- [main] Update dependencies from dotnet/runtime dotnet/arcade dotnet/icu dotnet/xharness dotnet/llvm-project (#50733)
- Make ModuleTests.ResolveField/Method actually test something (#50280)
- Disable Net5CompatFileStream by default (#50166)
- Resolve ILLink warnings on System.Private.DataContractSerialization Part 1; Json) (#50619)
- Fix handling of not found exported types (#50845)
- Fix contained LCL_VAR_ADDR in RMW. (#50669)
- Update build-runtime.cmd help documentation (#50829)
- Delete infra changes (#50789)
- Fix JIT rolling build for new build-runtime script arguments (#50876)
- [wasm] Set __DistroRid on Windows to browser-wasm (#50842)
- [wasm] Fix order of include paths, to have the obj dir first (#50303)
- [wasm] Fix debug build of AOT cross compiler (#50418)
- Fix outdated comment (#50834)
- [wasm][tests] Add properties to allow passing args to xharness (#50678)
- Vectorized common String.Split() paths (#38001)
- Fix binplacing symbol files. (#50819)
- Move type check to after the null ref branch in out marshalling of blittable classes. (#50735)
- Remove extraneous CMake version requirement. (#50805)
- [wasm] Remove unncessary condition for EMSDK (#50810)
- Add loop alignment stats to JitLogCsv (#50624)
- Resolve ILLink warnings in System.Diagnostics.DiagnosticSource (#50265)

**Comment by ViktorHofer** [comment]
Add /bl to the build command and send me the binlog (name by default is msbuild.binlog) via Teams please (a binlog contains env vars).

**Comment by antonfirsov** [comment]
I managed to track this to #50166 with git bisect. Setting `DOTNET_SYSTEM_IO_USENET5COMPATFILESTREAM=1` fixes the issue.

#50166  might be concerning regarding the ability of using .NET 6 with `dotnet build` from within a Windows docker container.

/cc @adamsitnik

**Comment by antonfirsov** [comment]
I see it has been addressed in #51151, trying again with fresh main.

**Comment by antonfirsov** [comment]
#51151 fixed this, looks like an exceptional case (a runtime bug broke the SDK). @ViktorHofer thanks for your support!

**Comment by adamsitnik** [comment]
> #51151 fixed this

@antonfirsov thank you for the confirmation!
