### ISSUE TITLE
Exception from Array.CreateInstance(typeof(object),new int[]{1},new int[]{Int32.MaxValue})

### ISSUE THREAD

**Issue by dmitry-lipetsk** [dotnet/runtime#51128]
### Description

`var arr=Array.CreateInstance(typeof(object),new int[]{1},new int[]{Int32.MaxValue});
`

This code:
- works fine on .NET FW3.5-4.8 (Windows)
- throws exception on the  .NET Core 3.1 (netcoreapp3.1), NET5 (Windows)

``` c#
EXCEPTION: System.ArgumentOutOfRangeException
ERROR: System.Private.CoreLib - Higher indices will exceed Int32.MaxValue because of large lower bound and/or length.
STACK:
   at System.Array.InternalCreate(Void* elementType, Int32 rank, Int32* pLengths, Int32* pLowerBounds)
   at System.Array.CreateInstance(Type elementType, Int32[] lengths, Int32[] lowerBounds)
   at ConsoleApp1.Program.Main(String[] args)
```

Tested on two different computer.

### Configuration
Windows 10 Pro, x64, Build 19042.867 (Intel)
Visual Studio 2019, Version 16.10.0 Preview 1.0

---
project file (Console)

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```
Test sample:
``` c#
using System;

namespace ConsoleApp1
{
 class Program
 {
  static void Main(string[] args)
  {
   try
   {
    var arr=Array.CreateInstance(typeof(object),new int[]{1},new int[]{Int32.MaxValue});
   }
   catch(Exception exc)
   {
    Console.WriteLine("EXCEPTION: {0}",exc.GetType().FullName);

    Console.WriteLine("ERROR: {0} - {1}",exc.Source,exc.Message);
    
    Console.WriteLine("STACK:\n{0}",exc.StackTrace);
   }
  }
 }
}

```

**Comment by GrabYourPitchforks** [comment]
This seems to be a bug in Full Framework. It is generally illegal to have an array where the element `arr[int.MaxValue]` is addressable, because that would imply that `arr[int.MaxValue + 1]` is also a legal GC-trackable reference and occurs at a memory address which is strictly greater than the address of every addressable array element.

(Yes, technically if you use 64-bit indices instead of 32-bit indices you won't integer overflow and you'll avoid this problem. But I imagine there are numerous code paths within the runtime that don't guard against this and when they see such an array will fall over dead due to using signed 32-bit values for indices.)

**Comment by jkotas** [comment]
This is about multidimensional arrays. Multidimensional arrays do not have `int.MaxValue` limit for total number of elements.

Note that this is only broken on Windows. It works fine on Linux. It looks like C++ compiler does not produce the expected code for the bounds check.

> I imagine there are numerous code paths within the runtime that don't guard against this 

The runtime should be able to handle multi-dimensional arrays with more than `int.MaxValue` elements fine. As always, we can have bugs here and there that we would want to fix.

**Comment by jkotas** [comment]
>  But I imagine there are numerous code paths within the runtime that don't guard against this 

There actually many paths in the libraries that do not work in this situation. For example, the [recomended pattern](https://docs.microsoft.com/en-us/dotnet/api/system.array.getlowerbound?view=net-5.0#examples) for walking through multi-dimm arrays does not work in this situation. This pattern is replicated many times.

It suggests that we should consistently block it.

**Comment by dmitry-lipetsk** [comment]
Could you please point me to the line of code that is causing this exception?

Thank you.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/coreclr/vm/gchelpers.cpp#L604-L605

**Comment by dmitry-lipetsk** [comment]
`if ((length > 0) && (lowerBound + (length - 1) < lowerBound))
`

I do not understand - how this condition returns **true**?

It is some specific problem with C++ compiler?

---
length=1
lowerBound=2147483647 (int.MaxValue)

`((1 > 0) && (2147483647 + (1 - 1) < 2147483647))  ----> (true && (2147483647  < 2147483647)) ----> (true && false)
`

returns false.

Or no?

---
**Test on C# (NUnit)**

``` c#
 [Test]
 public static void test_04__dim1__sz1_max()
 {
  // if ((length > 0) && (lowerBound + (length - 1) < lowerBound))
  //     COMPlusThrow(kArgumentOutOfRangeException, W("ArgumentOutOfRange_ArrayLBAndLength"));

  var v_lengths=new int[]{1};
  var v_lbounds=new int[]{Int32.MaxValue};

  Assert.IsFalse
   ((v_lengths[0] > 0) && (v_lbounds[0] + (v_lengths[0]-1) < v_lbounds[0])); // ok!

  var arr0=Array.CreateInstance(typeof(object),v_lengths,v_lbounds); // fail!
}//test_04__dim1__sz1_max

```

**Comment by evilguest** [comment]
The only possible explanation for this code to fail is that the C++ compiler reorders the operations in `(lowerBound + (length - 1) < lowerBound`. So the overflow happens somewhere in the temp values and affects the result.

**Comment by evilguest** [comment]
> > But I imagine there are numerous code paths within the runtime that don't guard against this
> 
> There actually many paths in the libraries that do not work in this situation. For example, the [recomended pattern](https://docs.microsoft.com/en-us/dotnet/api/system.array.getlowerbound?view=net-5.0#examples) for walking through multi-dimm arrays does not work in this situation. This pattern is replicated many times.
> 
> It suggests that we should consistently block it.

I don't see why would such an array fail the recommended pattern. Both GetUpperBound and GetLowerBound will return MAX_INT, and the iteration code would work just fine.

**Comment by jkotas** [comment]
> It is some specific problem with C++ compiler?

Yes, it looks like a bug in the Windows C++ compiler.

> Both GetUpperBound and GetLowerBound will return MAX_INT, and the iteration code would work just fine.

It won't work just fine. It will turn into `for (int i = Int32.MaxValue; i <= Int32.MaxValue; i++) { ... }` that is infinite loop.

**Comment by evilguest** [comment]
Oh my! 10 points to Griffindor. You're right, i<= MaxInt does never evaluate to false.

**Comment by jkotas** [comment]
Opened issue for the C++ compiler bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1311192 (internal MSFT link)
