### ISSUE TITLE
[wasm][tests][eat] Trimming errors related to custom attributes

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51211]
- [System.Runtime.CompilerServices.VisualC.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50885-merge-5d244ac34e9341618c/System.Runtime.CompilerServices.VisualC.Tests/console.9e912f29.log?sv=2019-07-07&se=2021-05-04T02%3A05%3A53Z&sr=c&sp=rl&sig=wxyooJea6f87VGigAGTLDSa7LgvNsO7XIK84zR0fTj8%3D)

```
[02:41:15] fail: [FAIL] System.Runtime.CompilerServices.Tests.RequiredAttributeAttributeTests.Ctor_RequiredContract
[02:41:15] info: System.TypeLoadException : Could not load type System.Int32, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[02:41:15] info:    at System.Reflection.CustomAttributeData.ResolveArguments()
[02:41:15] info:    at System.Reflection.CustomAttributeData.get_ConstructorArguments()
[02:41:15] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
[02:41:15] info: Finished:    System.Runtime.CompilerServices.VisualC.Tests.dll
```

- [System.Reflection.TypeExtensions.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50885-merge-5d244ac34e9341618c/System.Reflection.TypeExtensions.Tests/console.6cd6353f.log?sv=2019-07-07&se=2021-05-04T02%3A05%3A53Z&sr=c&sp=rl&sig=wxyooJea6f87VGigAGTLDSa7LgvNsO7XIK84zR0fTj8%3D)

```
[02:41:16] fail: [FAIL] System.Reflection.Tests.ConstructorInfoTests.Properties
[02:41:16] info: System.TypeLoadException : Could not load type System.Char, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[02:41:16] info:    at System.Reflection.CustomAttributeData.ResolveArguments()
[02:41:16] info:    at System.Reflection.CustomAttributeData.get_ConstructorArguments()
[02:41:16] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
```

- [System.Reflection.Emit.Lightweight.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50885-merge-5d244ac34e9341618c/System.Reflection.Emit.Lightweight.Tests/console.2c043023.log?sv=2019-07-07&se=2021-05-04T02%3A05%3A53Z&sr=c&sp=rl&sig=wxyooJea6f87VGigAGTLDSa7LgvNsO7XIK84zR0fTj8%3D)

```
[02:41:13] fail: [FAIL] System.Reflection.Emit.Tests.DynamicMethodctor1.String_Type_TypeArray_Module
[02:41:13] info: System.TypeLoadException : Could not load type System.Nullable`1[[System.Char, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[02:41:13] info:    at System.Reflection.CustomAttributeData.ResolveArguments()
[02:41:13] info:    at System.Reflection.CustomAttributeData.get_ConstructorArguments()
[02:41:13] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
```

- [Microsoft.Extensions.Configuration.Binder.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50885-merge-5d244ac34e9341618c/Microsoft.Extensions.Configuration.Binder.Tests/console.7b0da688.log?sv=2019-07-07&se=2021-05-04T02%3A05%3A53Z&sr=c&sp=rl&sig=wxyooJea6f87VGigAGTLDSa7LgvNsO7XIK84zR0fTj8%3D)

```
[02:40:39] fail: [FAIL] Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.ConsistentExceptionOnFailedBinding
[02:40:39] info: System.TypeLoadException : Could not load type System.UInt32, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[02:40:39] info:    at System.Reflection.CustomAttributeData.ResolveArguments()
[02:40:39] info:    at System.Reflection.CustomAttributeData.get_ConstructorArguments()
[02:40:39] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
[02:40:39] fail: [FAIL] Microsoft.Extensions.Configuration.Binder.Test.ConfigurationBinderTests.CanReadAllSupportedTypes
[02:40:40] info: System.TypeLoadException : Could not load type System.UInt32, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[02:40:40] info:    at System.Reflection.CustomAttributeData.ResolveArguments()
[02:40:40] info:    at System.Reflection.CustomAttributeData.get_ConstructorArguments()
[02:40:40] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
```

**Comment by ilonatommy** [comment]
@lewing, what is the status here?
