### ISSUE TITLE
Test failure System.Net.Tests.HttpWebRequestTest_Sync.ReadWriteTimeout_CancelsResponse(forceTimeoutDuringHeaders: False)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#51292]
Run: [runtime 20210414.62](https://dev.azure.com/dnceng/public/_build/results?buildId=1088761&view=ms.vss-test-web.build-test-results-tab&runId=33384256&resultId=151981&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open
 -System.Net.Tests.HttpWebRequestTest_Sync.ReadWriteTimeout_CancelsResponse(forceTimeoutDuringHeaders: False)
```

**Error message:**
```
System.Net.WebException: Connection timed out [::ffff:127.0.0.1]:42041 (127.0.0.1:42041)
 ---> System.Net.Http.HttpRequestException: Connection timed out [::ffff:127.0.0.1]:42041 (127.0.0.1:42041)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (110): Connection timed out [::ffff:127.0.0.1]:42041
 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3246
 at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 869
 at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 899
 at System.Net.Sockets.Socket.Connect(String host, Int32 port) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 925
 at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 855
 at System.Net.HttpWebRequest.<>c__DisplayClass216_0.<<CreateHttpClient>b__1>d.MoveNext() in //src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1571
--- End of stack trace from previous location ---
 at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1269
 --- End of inner exception stack trace ---
 at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1296
 at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1209
 at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1304
 at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 513
 at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 827
 at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
 at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpMessageHandlerStage.cs:line 15
 at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs:line 522
 at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs:line 66
 at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken) in //src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 467
 at System.Net.HttpWebRequest.SendRequest(Boolean async) in System.Net.Requests.dll:token 0x600012a+0x0
 at System.Net.HttpWebRequest.GetResponse() in //src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1028
 --- End of inner exception stack trace ---
 at System.Net.HttpWebRequest.GetResponse() in //src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1032
 at System.Net.Tests.HttpWebRequestTest_Sync.<>c__DisplayClass1_0.<GetResponseAsync>b__0() in //src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 36
 at System.Threading.Tasks.Task1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 503
 at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2369
 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
--- End of stack trace from previous location ---
 at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 293
 at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2331
--- End of stack trace from previous location ---
 at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass90_2.<<ReadWriteTimeout_CancelsResponse>b__3>d.MoveNext() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1091
--- End of stack trace from previous location ---
 at Xunit.Assert.RecordExceptionAsync(Func1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 81
Expected: True
Actual: False

Stack trace
   at System.Net.Tests.HttpWebRequestTest.<>c__DisplayClass90_1.<<ReadWriteTimeout_CancelsResponse>b__2>d.MoveNext() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1104
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 88
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Tests.HttpWebRequestTest.ReadWriteTimeout_CancelsResponse(Boolean forceTimeoutDuringHeaders) in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1083
--- End of stack trace from previous location ---


```

**Comment by karelz** [comment]
Failures during 2/23-5/7: -- only RedHat7.amd64 during 4/11-4/17
- 3 failures in official runs (2x Mono, 1x CoreCLR)
- 9 failures in PRs (7x CoreCLR, 2x Mono)

It seems to be transient failure that went away, closing.
