### ISSUE TITLE
[wasm][tests][eat] System.Data.Tests.XmlDataReaderTest.XmlLoadTest

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51369]
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-aefda0fb1dc846088b/System.Data.Common.Tests/console.019086d7.log?sv=2019-07-07&se=2021-05-06T05%3A54%3A59Z&sr=c&sp=rl&sig=YzKcg6gONs0lcD0%2FuFKJbSnMTU6e%2F1f0HWmaDDwYAYQ%3D)

```
System.Data.Tests.XmlDataReaderTest.XmlLoadTest

System.ArgumentException : Column requires a valid DataType.

   at System.Data.DataColumn.set_DataType(Type value)
   at System.Data.XSDSchema.SetProperties(Object instance, XmlAttribute[] attrs)
   at System.Data.XSDSchema.HandleElementColumn(XmlSchemaElement elem, DataTable table, Boolean isBase)
   at System.Data.XSDSchema.HandleParticle(XmlSchemaParticle pt, DataTable table, ArrayList tableChildren, Boolean isBase)
   at System.Data.XSDSchema.HandleComplexType(XmlSchemaComplexType ct, DataTable table, ArrayList tableChildren, Boolean isNillable)
   at System.Data.XSDSchema.InstantiateTable(XmlSchemaElement node, XmlSchemaComplexType typeNode, Boolean isRef)
   at System.Data.XSDSchema.HandleTable(XmlSchemaElement node)
   at System.Data.XSDSchema.HandleDataSet(XmlSchemaElement node, Boolean isNewDataSet)
   at System.Data.XSDSchema.LoadSchema(XmlSchemaSet schemaSet, DataSet ds)
   at System.Data.DataSet.ReadXSDSchema(XmlReader reader, Boolean denyResolving)
   at System.Data.DataSet.ReadXmlSchema(XmlReader reader, Boolean denyResolving)
   at System.Data.DataSet.ReadXmlSchema(TextReader reader)
   at System.Data.Tests.XmlDataReaderTest.XmlLoadTest()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]>
```

**Comment by eerhardt** [comment]
fyi @krwq - since you are addressing ILLink warnings in this assembly.
