### ISSUE TITLE
Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks tests are failing in CI

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#51372]
See 

* https://github.com/dotnet/runtime/pull/51348#issuecomment-821114485
* https://dev.azure.com/dnceng/public/_build/results?buildId=1091966&view=ms.vss-test-web.build-test-results-tab&runId=33470914&resultId=100347&paneView=debug

```
Put_dotnet_behind_symlink

Error message
System.IO.DirectoryNotFoundException : Could not find a part of the path '/root/runtime/artifacts/tests/Release/hma/zz10t5cr.qbb/dotnet'.

Stack trace
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path)
   at Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_dotnet_behind_symlink() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUsedWithSymbolicLinks.cs:line 205
```
```
Run_apphost_behind_transitive_symlinks

System.IO.DirectoryNotFoundException : Could not find a part of the path '/root/runtime/artifacts/tests/Release/hma/nhgciwzt.nyo/a/FirstSymlink'.

Stack trace
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path)
   at Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Run_apphost_behind_transitive_symlinks(String firstSymlinkRelativePath, String secondSymlinkRelativePath) in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUsedWithSymbolicLinks.cs:line 92
```

**Comment by vitek-karas** [comment]
@mateoatr

**Comment by mateoatr** [comment]
Thanks. I'm already taking a look #51373.
