### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#51612]
Run: [runtime-coreclr jitstress 20210419.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1097089&view=ms.vss-test-web.build-test-results-tab&runId=33568258&resultId=107719&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
 -JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd
```

**Error message:**
```
Assert failure(PID 536 [0x00000218], Thread: 5392 [0x1510]): Assertion failed 'header->gsCookieOffset != INVALID_GS_COOKIE_OFFSET' in 'System.Runtime.Intrinsics.Vector641[IntPtr][System.IntPtr]:get_AllBitsSet():System.Runtime.Intrinsics.Vector641[IntPtr]' during 'Emit GC+EH tables' (IL size 17)

 File: D:\workspace\_work\1\s\src\coreclr\jit\gcencode.cpp Line: 1602
 Image: C:\h\w\A75F094C\p\corerun.exe


Return code: 1
Raw output file: C:\h\w\A75F094C\w\BDC509D9\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A75F094C\p\corerun.exe" NotSupported_r.dll 
Beginning test case Vector64BooleanZero at 4/20/2021 7:20:41 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64BooleanAllBitsSet at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64BooleanAsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64ByteAsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64DoubleAsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64Int16AsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64Int32AsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64Int64AsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64SByteAsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64SingleAsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64UInt16AsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64UInt32AsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64UInt64AsGeneric_Boolean at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64BooleanAsGeneric_Byte at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
Beginning test case Vector64BooleanAsGeneric_Double at 4/20/2021 7:20:42 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/20/2021 7:20:42 AM
B

Stack trace
   at JIT_HardwareIntrinsics._General_NotSupported_NotSupported_r_NotSupported_r_._General_NotSupported_NotSupported_r_NotSupported_r_cmd()

```

**Comment by VincentBu** [comment]
Failed again in  [runtime-coreclr jitstress 20210427.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1111281&view=ms.vss-test-web.build-test-results-tab&runId=33886568&resultId=105933&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
 -JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd
```

**Error message:**
```
Assert failure(PID 4412 [0x0000113c], Thread: 2696 [0x0a88]): Assertion failed 'header->gsCookieOffset != INVALID_GS_COOKIE_OFFSET' in 'System.Runtime.Intrinsics.Vector641[IntPtr][System.IntPtr]:get_AllBitsSet():System.Runtime.Intrinsics.Vector641[IntPtr]' during 'Emit GC+EH tables' (IL size 17)

 File: D:\workspace\_work\1\s\src\coreclr\jit\gcencode.cpp Line: 1602
 Image: C:\h\w\A0860938\p\corerun.exe


Return code: 1
Raw output file: C:\h\w\A0860938\w\B58A09AF\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\General\NotSupported\NotSupported_r\NotSupported_r.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A0860938\p\corerun.exe" NotSupported_r.dll 
Beginning test case Vector64BooleanZero at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64BooleanAllBitsSet at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64BooleanAsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64ByteAsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64DoubleAsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64Int16AsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64Int32AsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64Int64AsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64SByteAsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64SingleAsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64UInt16AsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64UInt32AsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64UInt64AsGeneric_Boolean at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64BooleanAsGeneric_Byte at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM
Beginning test case Vector64BooleanAsGeneric_Double at 4/28/2021 7:49:16 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro


Ending test case at 4/28/2021 7:49:16 AM

Stack trace
   at JIT_HardwareIntrinsics._General_NotSupported_NotSupported_r_NotSupported_r_._General_NotSupported_NotSupported_r_NotSupported_r_cmd()

```

**Comment by VincentBu** [comment]
Historical failures of this test:

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-04-28T07:01:46.907Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1111281&view=ms.vss-test-web.build-test-results-tab&runId=33886568&resultId=105933&paneView=debug)
2021-04-27T06:35:18.722Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1109270&view=ms.vss-test-web.build-test-results-tab&runId=33842460&resultId=108149&paneView=debug)
2021-04-26T06:38:35.679Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1107161&view=ms.vss-test-web.build-test-results-tab&runId=33800630&resultId=107881&paneView=debug)
2021-04-26T04:54:57.4Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr r2r-extra   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1107112&view=ms.vss-test-web.build-test-results-tab&runId=33799462&resultId=107612&paneView=debug)
2021-04-25T23:53:23.475Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106954&view=ms.vss-test-web.build-test-results-tab&runId=33796162&resultId=109723&paneView=debug)
2021-04-25T23:14:11.68Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106954&view=ms.vss-test-web.build-test-results-tab&runId=33795886&resultId=109880&paneView=debug)
2021-04-25T20:10:39.19Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x1000](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33794030&resultId=108874&paneView=debug)
2021-04-25T20:03:45.803Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x80](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793950&resultId=107375&paneView=debug)
2021-04-25T19:59:17.125Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x10](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793936&resultId=108757&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-04-25T19:52:52.34Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs8](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793926&resultId=107474&paneView=debug)
2021-04-25T19:31:24.556Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs3](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793798&resultId=107373&paneView=debug)
2021-04-25T19:31:23.494Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs1](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793796&resultId=107249&paneView=debug)
2021-04-25T19:31:22.868Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs4](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793800&resultId=107156&paneView=debug)
2021-04-25T19:31:21.88Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106847&view=ms.vss-test-web.build-test-results-tab&runId=33793802&resultId=107214&paneView=debug)
2021-04-25T06:58:23.894Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106546&view=ms.vss-test-web.build-test-results-tab&runId=33785378&resultId=108714&paneView=debug)
2021-04-25T04:44:01.577Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr r2r-extra   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106519&view=ms.vss-test-web.build-test-results-tab&runId=33784672&resultId=108002&paneView=debug)
2021-04-25T00:33:38.335Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106346&view=ms.vss-test-web.build-test-results-tab&runId=33783376&resultId=109790&paneView=debug)
2021-04-24T23:42:41.312Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106346&view=ms.vss-test-web.build-test-results-tab&runId=33782730&resultId=109694&paneView=debug)
2021-04-24T21:48:30.131Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x1000](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33781064&resultId=108466&paneView=debug)
2021-04-24T21:47:31.671Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x80](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33781024&resultId=107592&paneView=debug)
2021-04-24T21:46:49.705Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x10](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33781014&resultId=108357&paneView=debug)
2021-04-24T21:36:49.199Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs8](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33780808&resultId=108400&paneView=debug)
2021-04-24T20:59:08.348Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs3](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33780356&resultId=108102&paneView=debug)
2021-04-24T20:59:07.683Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs4](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33780360&resultId=107607&paneView=debug)
2021-04-24T20:59:06.81Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs2](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33780358&resultId=104922&paneView=debug)
2021-04-24T20:59:05.495Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs1](https://dev.azure.com/dnceng/public/_build/results?buildId=1106211&view=ms.vss-test-web.build-test-results-tab&runId=33780354&resultId=103602&paneView=debug)
2021-04-24T06:20:02.913Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1105539&view=ms.vss-test-web.build-test-results-tab&runId=33761450&resultId=107611&paneView=debug)
2021-04-23T07:06:16.365Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1103643&view=ms.vss-test-web.build-test-results-tab&runId=33720476&resultId=107161&paneView=debug)
2021-04-22T06:48:15.692Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1101366&view=ms.vss-test-web.build-test-results-tab&runId=33665660&resultId=107461&paneView=debug)
2021-04-21T06:46:38.143Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1099128&view=ms.vss-test-web.build-test-results-tab&runId=33614028&resultId=107796&paneView=debug)
2021-04-20T06:48:32.682Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1097089&view=ms.vss-test-web.build-test-results-tab&runId=33568258&resultId=107719&paneView=debug)
2021-04-01T10:16:56.526Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835860&resultId=106151&paneView=debug)
2021-04-01T10:16:56.526Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835860&resultId=106172&paneView=debug)
2021-04-01T10:16:55.583Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835858&resultId=107073&paneView=debug)
2021-04-01T10:16:55.583Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2 outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835858&resultId=107108&paneView=debug)
2021-04-01T09:47:40.3Z | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835364&resultId=104097&paneView=debug)
2021-04-01T09:47:40.3Z | osx.1013.amd64.open | x64 | [runtime-coreclr crossgen2 outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1067341&view=ms.vss-test-web.build-test-results-tab&runId=32835364&resultId=104098&paneView=debug)
2021-04-01T07:58:13.727Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833156&resultId=102457&paneView=debug)
2021-04-01T07:58:13.727Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833156&resultId=102599&paneView=debug)


</details>
