### ISSUE TITLE
Tests crash for `Microsoft.Extensions.Hosting.Unit.Tests` in `Libraries Test Run release mono OSX x64 Debug`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51611]
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-49c01169a7014d18bb/Microsoft.Extensions.Hosting.Unit.Tests/console.f3dc96fe.log?sv=2019-07-07&se=2021-05-11T04%3A20%3A01Z&sr=c&sp=rl&sig=RGudxk2x8A28NhhITwJQc2ShNw22Qq7kPc50yidjCHw%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1099089&view=logs&jobId=71afe768-e493-597c-228c-037834193aeb&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb

```
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 106 of 107 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 4)

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
   at System.IO.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr streamRef, IntPtr clientCallBackInfo, IntPtr numEvents, Byte** eventPaths, FSEventStreamEventFlags* eventFlags, UInt64* eventIds) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 354
   at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.WatchForFileSystemEventsThreadStart(ManualResetEventSlim runLoopStarted, SafeEventStreamHandle eventStream) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 255
   at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.<>c.<ScheduleEventStream>b__3_0(Object args) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 205
   at System.Threading.Thread.StartCallback() in /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 237

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x101732556 - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_dump_native_crash_info
	0x1016d29be - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_handle_native_crash
	0x10162ab2f - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_sigsegv_signal_handler_debug
	0x7fff5df2bb5d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7fd3ed700000 - Unknown
	0x106787708 - Unknown
	0x10162dcf2 - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_jit_runtime_invoke
	0x1015472cf - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_runtime_try_invoke
	0x101552039 - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_object_try_to_string
	0x1014fccfb - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_invoke_unhandled_exception_hook
	0x10155e567 - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : start_wrapper_internal
	0x10155e29e - /private/tmp/helix/working/A1F20910/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : start_wrapper
	0x7fff5df342eb - /usr/lib/system/libsystem_pthread.dylib : _pthread_body
	0x7fff5df37249 - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x7fff5df3340d - /usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x123145529155584x from 0x123145537593344x
Pkilling 0x123145527046144x from 0x123145537593344x
Pkilling 0x123145524936704x from 0x123145537593344x
Pkilling 0x123145522827264x from 0x123145537593344x
Pkilling 0x123145517260800x from 0x123145537593344x
Pkilling 0x123145541812224x from 0x123145537593344x
Pkilling 0x4545529280x from 0x123145537593344x
Pkilling 0x123145515151360x from 0x123145537593344x
Pkilling 0x123145520717824x from 0x123145537593344x
Pkilling 0x123145539702784x from 0x123145537593344x
Pkilling 0x123145518608384x from 0x123145537593344x
Pkilling 0x123145513041920x from 0x123145537593344x
Pkilling 0x123145510932480x from 0x123145537593344x
Pkilling 0x123145535483904x from 0x123145537593344x
Pkilling 0x123145533374464x from 0x123145537593344x
Pkilling 0x123145531265024x from 0x123145537593344x
Entering thread summarizer pause from 0x123145537593344x
Could not exec mono-hang-watchdog, expected on path '/Users/runner/work/1/s/artifacts/obj/mono/OSX.x64.Release/out/etc/../bin/mono-hang-watchdog' (errno 2)
Finished thread summarizer pause from 0x123145537593344x.
Failed to create breadcrumb file (null)/crash_hash_0x1267f66204

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1016cf653):0x1016cf643  e8 18 ef e4 ff 48 89 c3 4c 89 e7 e8 0d ef e4 ff  .....H..L.......
0x1016cf653  f6 40 20 7c 0f 84 d3 00 00 00 49 c7 46 28 00 00  .@ |......I.F(..
0x1016cf663  00 00 49 89 df 48 89 df be 01 00 00 00 31 d2 b9  ..I..H.......1..
0x1016cf673  01 00 00 00 e8 c4 83 e2 ff 4c 89 6d 88 49 89 c5  .........L.m.I..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Diagnostics.StackTrace:get_trace <0x00087>
	  at System.Diagnostics.StackTrace:InitializeForException <0x0006a>
	  at System.Diagnostics.StackTrace:.ctor <0x00062>
	  at System.Exception:GetStackTrace <0x000b2>
	  at System.Exception:get_StackTrace <0x00042>
	  at System.Exception:ToString <0x000e9>
	  at <Module>:runtime_invoke_object__this__ <0x000b0>
=================================================================
./RunTests.sh: line 162: 96012 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig Microsoft.Extensions.Hosting.Unit.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.Hosting.Unit.Tests.deps.json xunit.console.dll Microsoft.Extensions.Hosting.Unit.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/A1F20910/w/A2B7091C/e
----- end Tue Apr 20 21:20:30 PDT 2021 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

**Comment by eerhardt** [comment]
Failed again here:

https://dev.azure.com/dnceng/public/_build/results?buildId=1110822&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=5d5289b6-723b-5155-5d15-b590d280a14a&l=73

https://helix.dot.net/api/2019-06-17/jobs/ac3fc3cd-cc46-48cb-8299-aed64c18f4ee/workitems/Microsoft.Extensions.Hosting.Unit.Tests/console

```
/private/tmp/helix/working/C3CB0A70/w/ACAC097A/e /private/tmp/helix/working/C3CB0A70/w/ACAC097A/e
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 108 of 109 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 12)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1077514e6 - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_dump_native_crash_info
	0x1076f194e - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_handle_native_crash
	0x1076497df - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_sigsegv_signal_handler_debug
	0x7fff684ae5fd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x100000006 - Unknown
	0x10bf94898 - Unknown
	0x10764c9c2 - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_jit_runtime_invoke
	0x107565e1f - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_runtime_try_invoke
	0x10756ba07 - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_print_unhandled_exception_internal
	0x10756b278 - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_unhandled_exception_checked
	0x10756afff - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : mono_unhandled_exception_internal
	0x10757d0af - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : start_wrapper_internal
	0x10757cdee - /private/tmp/helix/working/C3CB0A70/p/shared/Microsoft.NETCore.App/6.0.0/libcoreclr.dylib : start_wrapper
	0x7fff684ba109 - /usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x7fff684b5b8b - /usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x123145603325952x from 0x123145609654272x
Pkilling 0x123145573793792x from 0x123145609654272x
Pkilling 0x123145571409920x from 0x123145609654272x
Pkilling 0x123145580122112x from 0x123145609654272x
Pkilling 0x123145586450432x from 0x123145609654272x
Pkilling 0x123145592778752x from 0x123145609654272x
Pkilling 0x123145612300288x from 0x123145609654272x
Pkilling 0x123145599107072x from 0x123145609654272x
Could not exec mono-hang-watchdog, expected on path '/Users/runner/work/1/s/artifacts/obj/mono/OSX.x64.Release/out/etc/../bin/mono-hang-watchdog' (errno 2)
Pkilling 0x123145618628608x from 0x123145609654272x
Pkilling 0x123145605435392x from 0x123145609654272x
Pkilling 0x123145567191040x from 0x123145609654272x
Pkilling 0x123145575903232x from 0x123145609654272x
Pkilling 0x123145573519360x from 0x123145609654272x
Pkilling 0x123145582231552x from 0x123145609654272x
Pkilling 0x4661095872x from 0x123145609654272x
Pkilling 0x123145588559872x from 0x123145609654272x
Pkilling 0x123145594888192x from 0x123145609654272x
Pkilling 0x123145614409728x from 0x123145609654272x
Pkilling 0x123145601216512x from 0x123145609654272x
Pkilling 0x123145607544832x from 0x123145609654272x
Pkilling 0x123145569300480x from 0x123145609654272x
Pkilling 0x123145578012672x from 0x123145609654272x
Pkilling 0x123145584340992x from 0x123145609654272x
Pkilling 0x123145590669312x from 0x123145609654272x
Pkilling 0x123145596997632x from 0x123145609654272x
Entering thread summarizer pause from 0x123145609654272x
Finished thread summarizer pause from 0x123145609654272x.
Failed to create breadcrumb file (null)/crash_hash_0x1268026cbb

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1076ee5c3):0x1076ee5b3  e8 f8 ea e4 ff 48 89 c3 4c 89 e7 e8 ed ea e4 ff  .....H..L.......
0x1076ee5c3  f6 40 20 7c 0f 84 d3 00 00 00 49 c7 46 28 00 00  .@ |......I.F(..
0x1076ee5d3  00 00 49 89 df 48 89 df be 01 00 00 00 31 d2 b9  ..I..H.......1..
0x1076ee5e3  01 00 00 00 e8 24 84 e2 ff 4c 89 6d 88 49 89 c5  .....$...L.m.I..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Diagnostics.StackTrace:get_trace <0x00087>
	  at System.Diagnostics.StackTrace:InitializeForException <0x0006a>
	  at System.Diagnostics.StackTrace:.ctor <0x00062>
	  at System.Exception:GetStackTrace <0x000b2>
	  at System.Exception:get_StackTrace <0x00042>
	  at System.Exception:ToString <0x000e9>
	  at <Module>:runtime_invoke_object__this__ <0x000b0>
=================================================================
./RunTests.sh: line 162:  3774 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig Microsoft.Extensions.Hosting.Unit.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.Hosting.Unit.Tests.deps.json xunit.console.dll Microsoft.Extensions.Hosting.Unit.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/C3CB0A70/w/ACAC097A/e
----- end Tue Apr 27 18:50:34 EDT 2021 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```
