### ISSUE TITLE
Intermittent failure in sorting tests on Linux ARM64

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#51655]
"Libraries Test Run checked coreclr Linux_musl arm64 Release" leg failed in [this run](https://github.com/dotnet/runtime/pull/51639/checks?check_run_id=2405086801):
```
    System.Linq.Tests.OrderByDescendingTests.SortsRandomizedEnumerableCorrectly(items: 1000000) [FAIL]
      Assert.Equal() Failure
      Expected: Int32[] [3736, 6229, 9573, 13642, 14998, ...]
      Actual:   Int32[] [3736, 6229, 9573, 13642, 14998, ...]
      Stack Trace:
        /_/src/libraries/System.Linq/tests/OrderByDescendingTests.cs(222,0): at System.Linq.Tests.OrderByDescendingTests.SortsRandomizedEnumerableCorrectly(Int32 items)
    System.Linq.Tests.TakeWhileTests.IndexTakeWhileOverflowBeyondIntMaxValueElements [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Linq.Tests.ThenByDescendingTests.SortsLargeRandomizedEnumerableCorrectly(thenBys: 3) [FAIL]
      Assert.Equal() Failure
      Expected: Int32[] [6229, 17946, 27100, 35598, 60852, ...]
      Actual:   OrderedEnumerable<Int32, Int32> [6229, 17946, 27100, 35598, 60852, ...]
      Stack Trace:
        /_/src/libraries/System.Linq/tests/ThenByDescendingTests.cs(231,0): at System.Linq.Tests.ThenByDescendingTests.SortsLargeRandomizedEnumerableCorrectly(Int32 thenBys)
```

**Comment by eiriktsarpalis** [comment]
I went through the recent test history but couldn't find any instances of the test failure reoccurring. We can revisit if it shows up again.
