### ISSUE TITLE
Test failure SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#51682]
Run: [runtime-coreclr libraries-jitstress 20210421.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1099278&view=ms.vss-test-web.build-test-results-tab&runId=33616000&resultId=133043&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open
 -SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties
```

**Error message:**
```
System.OutOfMemoryException : Insufficient memory to continue the execution of the program.


Stack trace
   at System.Speech.Internal.SapiInterop.ISpRecognizer.CreateRecoContext(ISpRecoContext& ppNewCtxt)
   at System.Speech.Internal.SapiInterop.SapiRecognizer.<>c__DisplayClass9_0.<CreateRecoContext>b__0() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134
   at System.Speech.Internal.SapiInterop.SapiRecognizer.CreateRecoContext() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134
   at System.Speech.Recognition.RecognizerBase.Initialize(SapiRecognizer recognizer, Boolean inproc) in /_/src/libraries/System.Speech/src/Recognition/RecognizerBase.cs:line 442
   at System.Speech.Recognition.SpeechRecognitionEngine.get_RecoBase() in /_/src/libraries/System.Speech/src/Recognition/SpeechRecognitionEngine.cs:line 660
   at SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties() in /_/src/libraries/System.Speech/tests/SynthesizeRecognizeTests.cs:line 75
```

**Comment by danmoseley** [comment]
Has not failed since. If this happens again, please reactivate and we can disable for jit stress runs.
