### ISSUE TITLE
Custom Json Serializer Options are omitted if a NumberHandling flag is not set

### ISSUE THREAD

**Issue by Mijalski** [dotnet/runtime#51685]
### Description

When creating a JsonSerializerOptions instance with custom Conventer it will not be used if NumberHandling flag is not set to Strict.

### Configuration

.NET6 preview 1 or greater
Blazor WASM (Chrome or Firefox)
```
protected static readonly JsonSerializerOptions MyCustomSerializerOptions =
            new JsonSerializerOptions(JsonSerializerDefaults.Web)
            {
                Converters =
                {
                    new MyConventer()
                },
                NumberHandling = JsonNumberHandling.Strict // does not work without this line
            }
```

### Regression?

It used to work in .NET5 without the flag.
It seems to be introduced with [this commit](https://github.com/dotnet/runtime/commit/149b235d6792be337ac6d9151a9f8ee9844c3e2f)
By removing the check for: `if (IsInternalConverterForNumberType)` on: `JsonConverterOfT.cs`

### Other information

Stack:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not valid due to the current state of the object.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.DictionaryDefaultConverter`3[[System.Collections.Generic.IReadOnlyDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, IReadOnlyDictionary`2& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.IReadOnlyDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, IReadOnlyDictionary`2& value)
   at System.Text.Json.JsonPropertyInfo`1[[System.Collections.Generic.IReadOnlyDictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[DeviceSimulator.Manager.Application.Shared.VirtualDevices.Responses.VirtualDeviceDto, DeviceSimulator.Manager.Application.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, VirtualDeviceDto& value)
   at System.Text.Json.Serialization.JsonConverter`1[[DeviceSimulator.Manager.Application.Shared.VirtualDevices.Responses.VirtualDeviceDto, DeviceSimulator.Manager.Application.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, VirtualDeviceDto& value)
   at System.Text.Json.Serialization.JsonConverter`1[[DeviceSimulator.Manager.Application.Shared.VirtualDevices.Responses.VirtualDeviceDto, DeviceSimulator.Manager.Application.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[VirtualDeviceDto](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[VirtualDeviceDto](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
```

**Comment by eiriktsarpalis** [comment]
Hi @Mijalski, in the interest of reproducing the issue, what is the implementation of your custom converter? Would you be able to provide a minimal reproduction that generates the exception you shared?

**Comment by Mijalski** [comment]
Yes this is my model that I am sending between Blazor and Server:
```
public class MyCustomObject
    {
        public string SomeStringValue { get; set; } = string.Empty;
        public IReadOnlyDictionary<string, object> DictionaryOfValues { get; set; } = new Dictionary<string, object>();
        public bool SomeBooleanValue{ get; set; }
    }
```
and my JsonConventer:
```
public class MyConventer : JsonConverter<object?>
    {
        public override object? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            reader.TokenType switch
            {
                JsonTokenType.True => true,
                JsonTokenType.False => false,
                JsonTokenType.Number when reader.TryGetInt64(out long l) => l,
                JsonTokenType.Number when reader.TryGetInt32(out int i) => i,
                JsonTokenType.Number => reader.GetDouble(),
                JsonTokenType.String when reader.TryGetDateTime(out DateTime datetime) => datetime,
                JsonTokenType.String => reader.GetString(),
                JsonTokenType.Null => null,
                JsonTokenType.StartArray => ReadArray(ref reader, typeToConvert, options),
                _ => throw new JsonException() //JsonDocument.ParseValue(ref reader).RootElement.Clone()
            };

        private object ReadArray(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var list = new List<object?>();

            while (reader.Read())
            {
                if (reader.TokenType == JsonTokenType.EndArray)
                {
                    return list;
                }

                list.Add(Read(ref reader, typeToConvert, options));
            }

            throw new JsonException();
        }
```

**Comment by eiriktsarpalis** [comment]
What JSON data are you deserializing from though? Could you please provide a self-containing console app that demonstrates the error?

**Comment by Mijalski** [comment]
I have provided the payload, hopefully it will be enough?

**Comment by devsko** [comment]
Herer is a minimal repro:
```cs
        [Fact]
        public static void WebDefaultsShouldWork()
        {
            string json = @"{ ""MyInt"": 25, ""MyDouble"": 5.1, ""MyString"": ""Hello"", ""MyBool"": true }";
            JsonSerializerOptions options = new(JsonSerializerDefaults.Web)
            {
                Converters = { new ObjectConverter() },
            };
            var dictionary = JsonSerializer.Deserialize<Dictionary<string, object?>>(json, options);
        }

        private class ObjectConverter : JsonConverter<object?>
        {
            public override object? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
                => reader.TokenType switch
                {
                    JsonTokenType.True => true,
                    JsonTokenType.False => false,
                    JsonTokenType.Number when reader.TryGetInt64(out long l) => l,
                    JsonTokenType.Number when reader.TryGetInt32(out int i) => i,
                    JsonTokenType.Number => reader.GetDouble(),
                    JsonTokenType.String when reader.TryGetDateTime(out DateTime datetime) => datetime,
                    JsonTokenType.String => reader.GetString(),
                    JsonTokenType.Null => null,
                    _ => throw new JsonException()
                };

             public override void Write(Utf8JsonWriter writer, object? value, JsonSerializerOptions options)
                => throw new NotImplementedException();
        }
```
Result:
```
Message: 
    System.InvalidOperationException : Operation is not valid due to the current state of the object.
  Stack Trace: 
    JsonConverter`1.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling) line 558
    JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) line 187
    DictionaryDefaultConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value) line 115
    JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) line 270
    JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) line 62
    JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) line 25
    JsonSerializer.Deserialize[TValue](JsonConverter jsonConverter, ReadOnlySpan`1 json, JsonSerializerOptions options, ReadStack& state) line 211
    JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options) line 182
    JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) line 51
    DictionaryTests.WebDefaultsShouldWork() line 24
```

**Comment by eiriktsarpalis** [comment]
Thanks, I can reproduce the issue. This is a regression from .NET 5.

**Comment by eiriktsarpalis** [comment]
Original PR meant to address this: #42239
