### ISSUE TITLE
Cli not working after install of .net 5 SDK 

### ISSUE THREAD

**Issue by gre-gstevens** [dotnet/runtime#51698]
Having worked with .net core for a couple of years (versions 2 and 3), I decided to try out .net 5. After the install, whenever I run a dotnet command, in this case `dotnet version`, I get the following exception:

`Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Globalization.CompareInfo.IcuCompareString(System.ReadOnlySpan1<Char>, System.ReadOnlySpan1<Char>, System.Globalization.CompareOptions)
   at System.Globalization.CompareInfo.Compare(System.ReadOnlySpan1<Char>, System.ReadOnlySpan1<Char>, System.Globalization.CompareOptions)
   at System.Globalization.CompareInfo.Compare(System.String, System.String, System.Globalization.CompareOptions)
   at System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant()
   at System.Globalization.TextInfo.ChangeCaseCommon[[System.Globalization.TextInfo+ToUpperConversion, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String)
   at System.Globalization.TextInfo.ToUpper(System.String)
   at System.Diagnostics.Tracing.EventSource.GetGuid(System.Type)
   at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
   at System.Diagnostics.Tracing.EventSource..ctor()
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager..cctor()
   at Microsoft.AspNetCore.DeveloperCertificates.XPlat.CertificateGenerator.GenerateAspNetHttpsCertificate()
   at Microsoft.DotNet.Cli.AspNetCoreCertificateGenerator.GenerateAspNetCoreDevelopmentCertificate()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(Microsoft.DotNet.Configurer.IFirstTimeUseNoticeSentinel, Microsoft.DotNet.Configurer.IAspNetCertificateSentinel, Microsoft.DotNet.Configurer.IFileSentinel, Boolean, Microsoft.DotNet.Configurer.DotnetFirstRunConfiguration, Microsoft.DotNet.Cli.Utils.IEnvironmentProvider, System.Collections.Generic.Dictionary2<System.String,Double>)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(System.String[], System.TimeSpan, Microsoft.DotNet.Cli.Telemetry.ITelemetry)
   at Microsoft.DotNet.Cli.Program.Main(System.String[])`

I have tried uninstalling all SDKs (& runtimes) and starting from scratch, however this doesnt seem to have fixed the problem. Running on Win10.

Any help much appreciated.

**Comment by elinor-fung** [comment]
@gre-gstevens are you able to run `dotnet --info`? Do you know which exact version of .NET 5 you installed? Would be able to check if you are also hitting this on the latest .NET 5 (5.0.7) and/or .NET 6 preview?

The `System.Runtime.InteropServices.SEHException` is indicating that the invoked native function - `GlobalizationNative_CompareString` in this case - threw, so I expect this is an error on globalization shim side.

@safern / @tarekgh do you know if there are/were first-run issues related to globalization and ICU on Windows (specifically `PopulateIsAsciiCasingSameAsInvariant` / `IcuCompareString`)?

**Comment by safern** [comment]
We've never hit any issues at first run with ICU on windows, so I wonder if it might be related to windows settings or configuration.

Also, something that might be worth trying to get the list of dotnet runtimes and SDKs installed is setting `DOTNET_SYSTEM_GLOBALIZATION_USENLS` env var to 1 and then running `dotnet --info`.

**Comment by gre-gstevens** [comment]
Thanks for the replies. The above may have worked, however after exhausting various suggestions from SO, the only way I was able to solve this was to format the drive and install Windows from scratch. Frustraiting but full-proof!
