### ISSUE TITLE
[wasm][tests] NullReferenceException errors in `System.Linq.Expressions.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51708]
Building with `/p:EnableAggressiveTrimming=true` fails with:

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1102290&view=logs&jobId=f217f715-90ad-5404-53bd-b93e3b80f465&j=fddee5b2-3265-5a91-40c1-750d81e69f3f&t=49df836a-1a9c-56d6-1c55-f10381605179)

```
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(503,82): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c.<Property_GenericPropertyAccessor_ThrowsArgumentException>b__38_0(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(504,82): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c.<Property_GenericPropertyAccessor_ThrowsArgumentException>b__38_1(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(459,74): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c.<Property_InstanceProperty_NullExpression_ThrowsArgumentException>b__33_3(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(511,82): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c.<Property_PropertyAccessorNotFromProperty_ThrowsArgumentException>b__39_0(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(448,76): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c__DisplayClass32_0.<Property_StaticProperty_NonNullExpression_ThrowsArgumentException>b__2(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(472,76): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c__DisplayClass34_0.<Property_ExpressionNotReadable_ThrowsArgumentException>b__3(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
/_/src/libraries/System.Linq.Expressions/tests/Member/MemberAccessTests.cs(482,74): Trim analysis error IL2103: System.Linq.Expressions.Tests.MemberAccessTests.<>c__DisplayClass35_0.<Property_ExpressionNotTypeOfDeclaringType_ThrowsArgumentException>b__2(): Value passed to the '#1' parameter of method 'System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)' cannot be statically determined as a property accessor. [/__w/1/s/src/libraries/System.Linq.Expressions/tests/System.Linq.Expressions.Tests.csproj]
```

**Comment by radical** [comment]
cc @eerhardt

**Comment by ilonatommy** [comment]
The error changed - I checked locally. Now we have 2 failures:
```
[FAIL] System.Linq.Expressions.Tests.InterpreterTests.VerifyInstructions_Simple
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Linq.Expressions.Tests.InterpreterTests.GetInstructions(LambdaExpression expression)
   at System.Linq.Expressions.Tests.InterpreterTests.VerifyInstructions(LambdaExpression expression, String expected)
   at System.Linq.Expressions.Tests.InterpreterTests.VerifyInstructions_Simple()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
[FAIL] System.Linq.Expressions.Tests.InterpreterTests.VerifyInstructions_Exceptions
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Linq.Expressions.Tests.InterpreterTests.GetInstructions(LambdaExpression expression)
   at System.Linq.Expressions.Tests.InterpreterTests.VerifyInstructions(LambdaExpression expression, String expected)
   at System.Linq.Expressions.Tests.InterpreterTests.VerifyInstructions_Exceptions()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
```
