### ISSUE TITLE
[wasm][aot] Runtime crash in `System.Linq.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51722]
This can be reproduced on `main`.

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f34e3e28ae714e2795/System.Linq.Tests/console.8c6c08a0.log?sv=2019-07-07&se=2021-05-12T23%3A02%3A39Z&sr=c&sp=rl&sig=M8G1aHX8aeJsmFgDbRdAoQbfgJYVaT9xU2xSfUEI%2Bi4%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1103095&view=logs&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=9df76bd4-3041-5537-002b-9e29a53263b9)

```
 Starting:    System.Linq.Tests.dll

 console.error: RuntimeError: memory access out of bounds
 console.error: RuntimeError: memory access out of bounds

     at mono_class_has_parent_fast (<anonymous>:wasm-function[4501]:0x13d54e)
     at mono_class_has_parent (<anonymous>:wasm-function[1407]:0x67a14)
     at mono_class_is_assignable_from_general (<anonymous>:wasm-function[10356]:0x3b95f8)
     at mono_class_is_assignable_from_checked (<anonymous>:wasm-function[3610]:0xefe69)
     at mono_class_is_assignable_from_internal (<anonymous>:wasm-function[1014]:0x557ae)
     at mono_object_handle_isinst (<anonymous>:wasm-function[6070]:0x1df905)
     at mono_object_isinst_checked (<anonymous>:wasm-function[1315]:0x633cf)
     at interp_throw (<anonymous>:wasm-function[237]:0x393e4)
     at interp_exec_method (<anonymous>:wasm-function[4547]:0x140c10)
     at interp_entry (<anonymous>:wasm-function[612]:0x44da5)
     at interp_entry_instance_1 (<anonymous>:wasm-function[27608]:0x995e03)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_in_sig_void_this_clse_DateTimeOffset_ (<anonymous>:wasm-function[364]:0x3de0f)
     at System_Linq_Tests_System_Linq_Tests_LifecycleTests__c__BinaryOperations_SourceEnumeratorsDisposedb__1_6_System_ValueTuple_4_System_Linq_Tests_LifecycleTests_Source_System_Linq_Tests_LifecycleTests_Unary_System_Linq_Tests_LifecycleTests_Binary_System_Linq_Tests_LifecycleTests_Sink (<anonymous>:wasm-function[40318]:0xf2ba31)
     at System_Linq_Tests_wrapper_delegate_invoke_System_Action_1_System_ValueTuple_4_System_Linq_Tests_LifecycleTests_Source_System_Linq_Tests_LifecycleTests_Unary_System_Linq_Tests_LifecycleTests_Binary_System_Linq_Tests_LifecycleTests_Sink_invoke_void_T_System_ValueTuple_4_System_Linq_Tests_LifecycleTests_Source_System_Linq_Tests_LifecycleTests_Unary_System_Linq_Tests_LifecycleTests_Binary_System_Linq_Tests_LifecycleTests_Sink (<anonymous>:wasm-function[37515]:0xcb50dc)
     at invoke_viii (dotnet.js:1:260395)
     at System_Linq_Tests_Xunit_Assert_All_T_INST_System_Collections_Generic_IEnumerable_1_T_INST_System_Action_1_T_INST (<anonymous>:wasm-function[37897]:0xd07ff5)
     at System_Linq_Tests_System_Linq_Tests_LifecycleTests_BinaryOperations_SourceEnumeratorsDisposed (<anonymous>:wasm-function[40345]:0xf40d7a)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_in_sig_void_this_ (<anonymous>:wasm-function[451]:0x3ff90)
     at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[30373]:0xa031d3)
     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[26940]:0x97acd8)
     at mono_jit_runtime_invoke (<anonymous>:wasm-function[26950]:0x97b37f)
     at do_runtime_invoke (<anonymous>:wasm-function[6726]:0x1f5edc)
     at mono_runtime_invoke_checked (<anonymous>:wasm-function[1009]:0x55388)
     at mono_runtime_try_invoke_array (<anonymous>:wasm-function[26748]:0x971ad5)
     at ves_icall_InternalInvoke (<anonymous>:wasm-function[22840]:0x9458c5)
     at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[9560]:0x39e796)
     at aot_wrapper_corlib_System_dot_Reflection_System_dot_Reflection_dot_RuntimeMethodInfo__InternalInvoke_pinvoke_obj_this_objclc_object_5b_5d_bclsc_Exception_26__attrs_2obj_cls1d_Reflection_dRuntimeMethodInfo_objclc_object_5b_5d_bclsc_Exception_26__attrs_2 (<anonymous>:wasm-function[7582]:0x258435)
     at invoke_iiiiii (dotnet.js:1:259185)
     at corlib_System_Reflection_RuntimeMethodInfo_Invoke_object_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo (<anonymous>:wasm-function[32822]:0xac16fd)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_CallTestMethod_object (<anonymous>:wasm-function[20904]:0x8741ea)
     at invoke_iiii (dotnet.js:1:259365)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass48_1___InvokeTestMethodAsyncb__1d_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8917]:0x35146d)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[21614]:0x8c5437)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[9063]:0x37da7b)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass48_1_TTestCase_REF__InvokeTestMethodAsyncb__1 (<anonymous>:wasm-function[20894]:0x8729a4)
     at corlib_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_invoke_TResult (<anonymous>:wasm-function[30518]:0xa1c8c3)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_MoveNext (<anonymous>:wasm-function[8996]:0x374ee2)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_ (<anonymous>:wasm-function[21608]:0x8c3d31)
     at xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer_AggregateAsync_System_Func_1_System_Threading_Tasks_Task (<anonymous>:wasm-function[8998]:0x375953)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass48_1_TTestCase_REF__InvokeTestMethodAsyncb__0 (<anonymous>:wasm-function[20895]:0x872cf3)
     at corlib_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_invoke_TResult (<anonymous>:wasm-function[30518]:0xa1c8c3)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_MoveNext (<anonymous>:wasm-function[9194]:0x385022)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_ (<anonymous>:wasm-function[22228]:0x911b4e)
     at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Func_1_System_Threading_Tasks_Task (<anonymous>:wasm-function[22061]:0x8fdd36)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_obj_this_obj (<anonymous>:wasm-function[916]:0x52c7e)
     at jit_call_cb (<anonymous>:wasm-function[10531]:0x3c0c2e)
     at invoke_vi (dotnet.js:1:258535)
     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[26942]:0x97ad51)
     at do_jit_call (<anonymous>:wasm-function[11689]:0x3f178c)
     at interp_exec_method (<anonymous>:wasm-function[4547]:0x140bed)
     at interp_entry (<anonymous>:wasm-function[612]:0x44da5)
     at interp_entry_instance_1 (<anonymous>:wasm-function[27608]:0x995e03)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_in_sig_void_this_clse_DateTimeOffset_ (<anonymous>:wasm-function[364]:0x3de0f)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_InvokeTestMethodAsync_object (<anonymous>:wasm-function[5755]:0x1c2509)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestInvoker_InvokeTestMethodAsync_object (<anonymous>:wasm-function[20752]:0x84e960)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_obj_this_obj (<anonymous>:wasm-function[916]:0x52c7e)
     at jit_call_cb (<anonymous>:wasm-function[10531]:0x3c0c2e)
     at invoke_vi (dotnet.js:1:258535)
     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[26942]:0x97ad51)
     at do_jit_call (<anonymous>:wasm-function[11689]:0x3f178c)
     at interp_exec_method (<anonymous>:wasm-function[4547]:0x140aa7)
     at interp_entry (<anonymous>:wasm-function[612]:0x44da5)
     at interp_entry_instance_1 (<anonymous>:wasm-function[27608]:0x995e03)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_in_sig_void_this_clse_DateTimeOffset_ (<anonymous>:wasm-function[364]:0x3de0f)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF__RunAsyncb__47_0 (<anonymous>:wasm-function[20900]:0x873220)
     at xunit_execution_dotnet_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_1_System_Decimal_invoke_TResult (<anonymous>:wasm-function[20660]:0x83cbd2)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_MoveNext (<anonymous>:wasm-function[9003]:0x375f98)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_ (<anonymous>:wasm-function[21609]:0x8c4012)
     at xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Decimal_System_Func_1_System_Threading_Tasks_Task_1_System_Decimal (<anonymous>:wasm-function[21138]:0x893905)
     at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8924]:0x356aaa)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestMethodAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[20745]:0x84db55)
     at invoke_iiii (dotnet.js:1:259365)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_MoveNext (<anonymous>:wasm-function[8862]:0x32fe9c)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_ (<anonymous>:wasm-function[21597]:0x8c1d86)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[20746]:0x84dc63)
     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__c__DisplayClass43_0_TTestCase_REF__RunAsyncb__0 (<anonymous>:wasm-function[20856]:0x86d6d1)
     at xunit_execution_dotnet_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_1_System_Tuple_2_System_Decimal_string_invoke_TResult (<anonymous>:wasm-function[20659]:0x83c7bc)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_T_REF_MoveNext (<anonymous>:wasm-function[9196]:0x385d89)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[22230]:0x91219a)
     at xunit_core_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[9236]:0x38cf82)
     at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_T_REF_System_Func_1_System_Threading_Tasks_Task_1_T_REF (<anonymous>:wasm-function[22060]:0x8fdb7f)
     at invoke_iiii (dotnet.js:1:259365)
     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8902]:0x347568)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__9 (<anonymous>:wasm-function[21611]:0x8c465c)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[9065]:0x37db64)
     at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8904]:0x349db5)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[20813]:0x860423)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8959]:0x3680d2)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[21619]:0x8c6b12)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[9072]:0x37de89)
     at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[4263]:0x132783)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20807]:0x85d8d5)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[20747]:0x84def6)
     at invoke_iiii (dotnet.js:1:259365)
     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCasesAsyncd__32_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8910]:0x34cac5)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[21612]:0x8c4ae8)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[9066]:0x37dbd7)
     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunTestCasesAsync (<anonymous>:wasm-function[20887]:0x871fc9)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__31_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8912]:0x34da44)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[21613]:0x8c4f74)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[9067]:0x37dc4a)
     at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8914]:0x34f72d)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[20794]:0x85b140)
     at invoke_iiiiiii (dotnet.js:1:261306)
     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMethodsAsyncd__38_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8952]:0x363d83)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[21617]:0x8c6206)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[9070]:0x37dda3)
     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunTestMethodsAsync (<anonymous>:wasm-function[20971]:0x87c69f)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__37_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8954]:0x365293)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[21618]:0x8c6692)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[9071]:0x37de16)
     at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8956]:0x367345)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[20774]:0x855fe2)
     at invoke_iiiiii (dotnet.js:1:259185)
     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTestClassesAsyncd__28_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8943]:0x35c337)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[21615]:0x8c58fa)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[9068]:0x37dcbd)
     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunTestClassesAsync (<anonymous>:wasm-function[20946]:0x879fac)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyncd__27_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8945]:0x35d789)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[21616]:0x8c5d86)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[9069]:0x37dd30)
     at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[8947]:0x35f775)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20828]:0x861782)
     at invoke_iiiiiii (dotnet.js:1:261306)
     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCollectionsAsyncd__42_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8962]:0x36a74c)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[21620]:0x8c6f92)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[9073]:0x37defc)
     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[8966]:0x36e4f5)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20817]:0x860c8e)
     at invoke_iiiii (dotnet.js:1:259717)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_MoveNext (<anonymous>:wasm-function[8893]:0x33f86a)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[21606]:0x8c376f)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20827]:0x861509)
     at invoke_iiiii (dotnet.js:1:259717)
     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd__41_TTestCase_REF_MoveNext (<anonymous>:wasm-function[8964]:0x36bf18)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[21621]:0x8c7434)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[9074]:0x37df6f)
     at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[20996]:0x880078)
     at invoke_iii (dotnet.js:1:259006)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_MoveNext (<anonymous>:wasm-function[8871]:0x33233c)
     at invoke_vii (dotnet.js:1:260231)
     at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[21599]:0x8c2348)
     at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20758]:0x8515f1)
     at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20922]:0x87530d)
     at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[19149]:0x77af91)
     at invoke_viiiii (dotnet.js:1:260724)
     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[18912]:0x74c23f)
     at invoke_vii (dotnet.js:1:260231)
     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[52646]:0x17cab08)
     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[52675]:0x17cd7ee)
     at invoke_iiiii (dotnet.js:1:259717)
     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[18910]:0x748138)
     at invoke_vii (dotnet.js:1:260231)
     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[52645]:0x17ca826)
     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[52664]:0x17cbbf5)
     at invoke_iii (dotnet.js:1:259006)
     at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[14796]:0x523e68)
     at invoke_vii (dotnet.js:1:260231)
     at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[35706]:0xbbfed0)
     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[14797]:0x524588)
     at xunit_runner_utility_netcoreapp10_aot_wrapper_gsharedvt_out_sig_obj_obj (<anonymous>:wasm-function[730]:0x49ce3)
     at invoke_viii (dotnet.js:1:260395)
     at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[30374]:0xa03578)
     at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[26940]:0x97acd8)
     at mono_jit_runtime_invoke (<anonymous>:wasm-function[26950]:0x97b37f)
     at do_runtime_invoke (<anonymous>:wasm-function[6726]:0x1f5edc)
     at mono_runtime_try_invoke (<anonymous>:wasm-function[1398]:0x67430)
     at mono_runtime_invoke (<anonymous>:wasm-function[26754]:0x971f23)
     at mono_wasm_invoke_method (<anonymous>:wasm-function[26587]:0x96cd5c)
     at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:1:251730)
     at Object._call_method_with_converted_args (dotnet.js:1:198453)
     at Object.call_method (dotnet.js:1:196926)
     at dotnet.js:1:204665
     at Object.call_assembly_entry_point (dotnet.js:1:204898)
     at Object.init (runtime.js:355:24)
     at Object.config.loaded_cb (runtime.js:241:8)
     at Object._finalize_startup (dotnet.js:1:148964)
     at onPendingRequestComplete (dotnet.js:1:150163)
     at processFetchResponseBuffer (dotnet.js:1:150483)
 Process v8 exited with 1

```

**Comment by radical** [comment]
This is passing on the test PR. [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-3dd81fa5d0b34cd8a4/System.Linq.Tests/console.31411bfd.log?sv=2019-07-07&): `[10:44:42] info: Total: 4315, Errors: 0, Failed: 0, Skipped: 15, Time: 288.6786308s`

Can this be closed?
