### ISSUE TITLE
Crossgen2: System.BadImageFormatException: Read out of bounds

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#51732]
### Description
I'm trying to use crossgen2 to compile an Avalonia app:

```bash
dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true
```

However, I got `System.BadImageFormatException` while compiling the app:
```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
   at System.Reflection.Metadata.TypeDefinition.get_BaseType()
   at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType()
   at Internal.TypeSystem.Ecma.EcmaType.get_BaseType()
   at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags mask)
   at Internal.TypeSystem.TypeDesc.get_IsValueType()
   at ILCompiler.IBC.IBCProfileParser.LoadTypeFromIBCZapSig(IBCModule ibcModule, EcmaModule ecmaModule, CorElementType typ, BlobReader& sig)
   at ILCompiler.IBC.IBCProfileParser.GetSigTypeFromIBCZapSig(IBCModule ibcModule, EcmaModule ecmaModule, BlobReader sig)
   at ILCompiler.IBC.IBCProfileParser.GetSigTypeFromIBCZapSig(IBCModule ibcModule, EcmaModule ecmaModule, BlobReader sig)
   at ILCompiler.IBC.IBCProfileParser.GetSigMethodInstantiationFromIBCMethodSpec(IBCModule ibcModule, BlobReader sig)
   at ILCompiler.IBC.IBCProfileParser.ParseIBCDataFromModule(EcmaModule ecmaModule)
   at ILCompiler.ProfileDataManager..ctor(Logger logger, IEnumerable`1 possibleReferenceModules, IEnumerable`1 inputModules, IEnumerable`1 versionBubbleModules, ModuleDesc nonLocalGenericsHome, IReadOnlyList`1 mibcFiles, CallChainProfile callChainProfile, CompilerTypeSystemContext context, ReadyToRunCompilationModuleGroupBase compilationGroup, Boolean embedPgoDataInR2RImage)
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```

A minimal repro project:
[Cg2Test.zip](https://github.com/dotnet/runtime/files/6364352/Cg2Test.zip)

### Configuration
.NET version: .NET 6 Preview 3
Windows version: 10 build 21364
Visual Studio version: 16.10 preview 2.1

**Comment by davidwrighton** [comment]
This is both a problem loading IBC data, and when it doesn't fail something goes wrong in the JIT itself. After applying #51768, if using a debug build of the JIT it hits

Assertion failed '((regMask & emitThisGCrefRegs) && (ins == INS_add)) || ((regMask & emitThisByrefRegs) && (ins == INS_add || ins == INS_sub))' in 'System.Text.Encoding:GetCharsWithFallback(long,int,long,int,int,int,System.Text.DecoderNLS):int:this' during 'Emit code' (IL size 183)

(In a release build, the build passes).

@dotnet/jit-contrib  Could I get someone from the JIT team to look into the jit issue? Contact me offline if you need instructions on how to use  a private copy of crossgen2 on this.

**Comment by AndyAyersMS** [comment]
This is a known issue, see #51728 and/or #10821.

I don't think there is an actual codegen bug, just case where the assert is overly paranoid.

**Comment by JulieLeeMSFT** [comment]
> I don't think there is an actual codegen bug, just case where the assert is overly paranoid.

Changed back to crossgen2 area becuase David has a fix and Andy thinks that there is no JIT issue.

**Comment by AndyAyersMS** [comment]
There is a jit issue, but (as far as I can tell) not one that will affect end users.

**Comment by davidwrighton** [comment]
Ok, well, fixed then. Fix should included in Preview 5.
