### ISSUE TITLE
Test failure Microsoft.Extensions.DependencyInjection.Specification.UnityDependencyInjectionSpecificationTests.FactoryServicesAreCreatedAsPartOfCreatingObjectGraph

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#51832]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20210424.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1105738&view=ms.vss-test-web.build-test-results-tab&runId=33765604&resultId=120123&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs0x10-Windows.10.Arm64v8.Open
 -Microsoft.Extensions.DependencyInjection.Specification.UnityDependencyInjectionSpecificationTests.FactoryServicesAreCreatedAsPartOfCreatingObjectGraph
```

**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at Microsoft.Extensions.DependencyInjection.Specification.DependencyInjectionSpecificationTests.FactoryServicesAreCreatedAsPartOfCreatingObjectGraph() in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs:line 292
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1557861&view=ms.vss-test-web.build-test-results-tab&runId=43901720&paneView=debug&resultId=102165)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- Microsoft.Extensions.DependencyInjection.Specification.UnityDependencyInjectionSpecificationTests.FactoryServicesAreCreatedAsPartOfCreatingObjectGraph

```
**Error message：**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at Microsoft.Extensions.DependencyInjection.Specification.DependencyInjectionSpecificationTests.FactoryServicesAreCreatedAsPartOfCreatingObjectGraph() in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs:line 300
```

**Comment by AndyAyersMS** [comment]
Stale issue, closing
