### ISSUE TITLE
[mono][eat] `System.Xml.XmlException : Resolving of external URIs was prohibited.`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51911]
Failing with `/p:EnableAggressiveTrimming=true`

[System.Xml.Xsl.XslCompiledTransformApi.Test](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-90ffb7de7255439c90/System.Xml.Xsl.XslCompiledTransformApi.Tests/console.50cf576c.log?sv=2019-07-07&se=2021-05-17T03%3A12%3A00Z&sr=c&sp=rl&sig=bXMAyTUXxvq97zAdN2V2kiBsJmBvk5%2BGJAHi0YFh1Ok%3D)

```
[03:37:36] fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver3(param: "xmlResolver_document_function.txt", xslInputType: Navigator, readerType: XmlValidatingReader)
[03:37:36] info: System.Xml.Xsl.XslTransformException : An error occurred while loading document 'xmlResolver_document_function.xml'. See InnerException for a complete description of the error.
[03:37:36] info: ---- System.Xml.XmlException : Resolving of external URIs was prohibited.
[03:37:36] info:    at System.Xml.Xsl.Runtime.XmlQueryContext.GetDataSource(String uriRelative, String uriBase)
[03:37:36] info:    at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlSequenceWriter results)
[03:37:36] info:    at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer)
[03:37:36] info:    at System.Xml.Xsl.XslCompiledTransform.Transform(XmlReader input, XsltArgumentList arguments, XmlWriter results, XmlResolver documentResolver)
[03:37:36] info:    at System.Xml.Xsl.XslCompiledTransform.Transform(String inputUri, String resultsFile)
[03:37:36] info:    at System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver3(Object param, XslInputType xslInputType, ReaderType readerType)
[03:37:36] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:36] info: ----- Inner Stack Trace -----
[03:37:36] info:    at System.Xml.XmlNullResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
[03:37:36] info:    at System.Xml.Xsl.Runtime.XmlQueryContext.GetDataSource(String uriRelative, String uriBase)
```

List of failing tests:

```
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver2(param: "xmlResolver_document_function.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CTransformResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: URI, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Reader, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: Writer, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXmlResolverTest.XmlResolver3(param: "DefaultResolver.txt", xslInputType: Navigator, readerType: XmlValidatingReader, outputType: TextWriter, navType: XPathDocument)
fail: [FAIL] System.Xml.Tests.CXsltSettings.XsltSettings1_1_ExternalURI(param0: 5, param1: "XsltSettings.xml", param2: "XsltSettings2.xsl", param3: True, param4: False)
fail: [FAIL] System.Xml.Tests.CXsltSettings.XsltSettings1_1_ExternalURI(param0: 8, param1: "XsltSettings.xml", param2: "XsltSettings2.xsl", param3: True, param4: True)
fail: [FAIL] System.Xml.Tests.CXsltSettings.XsltSettings1_2_ExternalURI(param0: 18, param1: "XsltSettings.xml", param2: "XsltSettings2.xsl", param3: False, param4: False, param5: True, param6: False)
fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver3(param: "xmlResolver_document_function.txt", xslInputType: Reader, readerType: XmlValidatingReader)
fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver3(param: "xmlResolver_document_function.txt", xslInputType: URI, readerType: XmlValidatingReader)
fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver3(param: "xmlResolver_document_function.txt", xslInputType: Navigator, readerType: XmlValidatingReader)
fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver2(xslInputType: Reader, readerType: XmlValidatingReader)
fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver2(xslInputType: URI, readerType: XmlValidatingReader)
fail: [FAIL] System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver2(xslInputType: Navigator, readerType: XmlValidatingReader)

```

**Comment by lewing** [comment]
cc @SamMonoRT
