### ISSUE TITLE
Test failure System.Text.Json.Tests.Serialization.MetadataTests_String.RoundTripSerializerOverloads

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#51969]
Run: [runtime 20210427.88](https://dev.azure.com/dnceng/public/_build/results?buildId=1110844&view=ms.vss-test-web.build-test-results-tab&runId=33874118&resultId=182430&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open
 -System.Text.Json.Tests.Serialization.MetadataTests_String.RoundTripSerializerOverloads
```

**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Text.Json.WriteStack.Initialize(JsonTypeInfo jsonTypeInfo, Boolean supportContinuation) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/WriteStack.cs:line 100
   at System.Text.Json.JsonSerializer.WriteUsingMetadata[TValue](TValue& value, JsonTypeInfo jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs:line 126
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonTypeInfo`1 jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs:line 79
   at System.Text.Json.Serialization.Tests.SerializationWrapper.StringSerializerWrapper.SerializeWrapper[T](T value, JsonTypeInfo`1 jsonTypeInfo) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/SerializationWrapper.cs:line 78
   at System.Text.Json.Tests.Serialization.MetadataTests.RoundTripSerializerOverloads() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/MetadataTests/MetadataTests.JsonSerializer.cs:line 17
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed in [runtime-coreclr libraries-jitstress 20210506.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1125101&view=ms.vss-test-web.build-test-results-tab&runId=34209738&resultId=173300&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 -System.Text.Json.Tests.Serialization.MetadataTests_LowLevel.RoundTripSerializerOverloads
```

**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Text.Json.WriteStack.Initialize(JsonTypeInfo jsonTypeInfo, Boolean supportContinuation) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/WriteStack.cs:line 100
   at System.Text.Json.JsonSerializer.WriteUsingMetadata[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Helpers.cs:line 44
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonTypeInfo`1 jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Utf8JsonWriter.cs:line 90
   at System.Text.Json.Serialization.Tests.SerializationWrapper.WriterSerializerWrapper.SerializeWrapper[T](T value, JsonTypeInfo`1 jsonTypeInfo) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/SerializationWrapper.cs:line 161
   at System.Text.Json.Tests.Serialization.MetadataTests.RoundTripSerializerOverloads() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/MetadataTests/MetadataTests.JsonSerializer.cs:line 17
--- End of stack trace from previous location ---
```

**Comment by ericstj** [comment]
@layomia looks like we have a bug here.  This tests seems to be failing intermittently since being introduced.

**Comment by steveharter** [comment]
I haven't seen any more hits; the test is not disabled.

The test uses a static `JsonContext.Default` that can be hit by multiple threads (i.e. other tests):
```cs
 string json = await Serializer.SerializeWrapper(expected, JsonContext.Default.WeatherForecastWithPOCOs);
```
and my guess is that the generated code for `WeatherForecastWithPOCOs` was not thread-safe when initializing the property:
```cs
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Text.Json.Serialization.Tests.WeatherForecastWithPOCOs> WeatherForecastWithPOCOs
        {
            get
            {
                if (_WeatherForecastWithPOCOs == null)
```

however it looks to be thread-safe now.

Closing until we get another hit or more information.
