### ISSUE TITLE
[wasm] System.Runtime tests fail on windows, timezone issues

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#52007]
I see many tests fail like

```
fail: [FAIL] System.Tests.TimeZoneInfoTests.TimeZoneInfo_DaylightDeltaIsNoMoreThan12Hours
  info: System.TypeInitializationException : The type initializer for 'System.Tests.TimeZoneInfoTests' threw an exception.
  info: ---- System.TimeZoneNotFoundException : The time zone ID 'Europe/London' was not found on the local computer.
  info: -------- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/zoneinfo/Europe/London'.
  info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  info: ----- Inner Stack Trace -----
  info:    at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
  info:    at System.Tests.TimeZoneInfoTests..cctor()
  info: ----- Inner Stack Trace -----
  info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
  info:    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
  info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
  info:    at System.IO.Strategies.FileStreamHelpers.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options)
  info:    at System.IO.Strategies.Net5CompatFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
  info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
  info:    at Internal.IO.File.ReadAllBytes(String path)
  info:    at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(String id, TimeZoneInfo& value, Exception& e)
```

It fails locally and on [helix](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51951-merge-3e019a9a3ed04e638c/System.Runtime.Tests/console.b7d0a477.log?sv=2019-07-07&se=2021-05-18T15%3A31%3A07Z&sr=c&sp=rl&sig=X3%2Fj0nB7%2BUamfWWmRApiDZENx%2Frc0bmFOzcD5xBx1TA%3D) too.

**Comment by lewing** [comment]
Interesting, not sure why this would happen.

cc @tqiu8

**Comment by tqiu8** [comment]
Hmmm...maybe it had to do with that change that split TimeZoneInfo because of size?

**Comment by lewing** [comment]
@radekdoulik can you send me the .blat file?

**Comment by lewing** [comment]
I think we just need to make https://github.com/dotnet/runtime/blob/main/src/tasks/WasmBuildTasks/GenerateWasmBundle.cs#L35 us unix path separators on windows too

**Comment by radekdoulik** [comment]
That does the trick. I will open PR for it.
```
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 38018, Errors: 0, Failed: 0, Skipped: 66, Time: 109.6852609s
```
