### ISSUE TITLE
[wasm] Microsoft.Extensions.Http tests fail on windows

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#52008]
2 tests are failing

```
  info: console.info: Arguments: --run,WasmTestRunner.dll,Microsoft.Extensions.Http.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready,fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: console.info: Initializing.....
  info: Discovering: Microsoft.Extensions.Http.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  Microsoft.Extensions.Http.Tests.dll (found 70 of 70 test cases)
  info: Starting:    Microsoft.Extensions.Http.Tests.dll
  fail: [FAIL] Microsoft.Extensions.Http.Logging.RedactedLogValueIntegrationTest.RedactHeaderValueWithPredicate_ValueIsRedactedBeforeLogging
  info: Assert.StartsWith() Failure:
  info: Expected: Request Headers:
  info:
  info: Authorization: *
  info:
  info: Cache-Control: no-cache
  info:
  info:
  info: Actual:   Request Headers:
  info: Authorization: *
  info: Cache-Control: no-cache
  info:
  info:    at Microsoft.Extensions.Http.Logging.RedactedLogValueIntegrationTest.RedactHeaderValueWithPredicate_ValueIsRedactedBeforeLogging()
  info: --- End of stack trace from previous location ---
  fail: [FAIL] Microsoft.Extensions.Http.Logging.RedactedLogValueIntegrationTest.RedactHeaderValueWithHeaderList_ValueIsRedactedBeforeLogging
  info: Assert.StartsWith() Failure:
  info: Expected: Request Headers:
  info:
  info: Authorization: *
  info:
  info: Cache-Control: no-cache
  info:
  info:
  info: Actual:   Request Headers:
  info: Authorization: *
  info: Cache-Control: no-cache
  info:
  info:    at Microsoft.Extensions.Http.Logging.RedactedLogValueIntegrationTest.RedactHeaderValueWithHeaderList_ValueIsRedactedBeforeLogging()
  info: --- End of stack trace from previous location ---
  info: Finished:    Microsoft.Extensions.Http.Tests.dll
  info:
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 70, Errors: 0, Failed: 2, Skipped: 49, Time: 0.436583s
```

**Comment by lewing** [comment]
are you running these in the browser or on v8?

**Comment by lewing** [comment]
haha newlines...
