### ISSUE TITLE
QUIC: Error loading credential in ASP.NET Core HTTP/3 sample app

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#52020]
The Kestrel ASP.NET Core sample app, which use to work, now fails when starting up with an error.

Source code: https://github.com/dotnet/aspnetcore/tree/main/src/Servers/Kestrel/samples/Http3SampleApp

It uses the ASP.NET Core development certificate (which has been trusted) as the TLS cert.

Exception details:

```
System.Net.Quic.QuicException
  HResult=0x80131500
  Message=ConfigurationLoadCredential failed. Error Code: 0xABB949FC
  Source=System.Net.Quic
  StackTrace:
   at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
   at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, List`1 alpnProtocols)
   at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener.State..ctor(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateListener(QuicListenerOptions options)
   at System.Net.Quic.QuicListener..ctor(QuicImplementationProvider implementationProvider, QuicListenerOptions options)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener..ctor(QuicTransportOptions options, IQuicTrace log, EndPoint endpoint, SslServerAuthenticationOptions sslServerAuthenticationOptions) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionListener.cs:line 46
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(EndPoint endpoint, IFeatureCollection features, CancellationToken cancellationToken) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\QuicTransportFactory.cs:line 62
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.<BindAsync>d__10.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\TransportManager.cs:line 71
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\KestrelServerImpl.cs:line 178
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindEndpointAsync>d__3.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\AddressBinder.cs:line 94
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.<BindAsync>d__47.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\ListenOptions.cs:line 181
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.<BindAsync>d__2.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\AddressBinder.cs:line 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\AddressBinder.cs:line 36
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<BindAsync>d__32.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\KestrelServerImpl.cs:line 276
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__29`1.MoveNext() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\KestrelServerImpl.cs:line 204
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__34.MoveNext() in C:\Development\Source\AspNetCore\src\Hosting\Hosting\src\GenericHost\GenericWebHostedService.cs:line 119
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Http3SampleApp.Program.Main(String[] args) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\samples\Http3SampleApp\Program.cs:line 51

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.QuicConnectionListener(Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportOptions, Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.IQuicTrace, System.Net.EndPoint, System.Net.Security.SslServerAuthenticationOptions) in QuicConnectionListener.cs
    Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(System.Net.EndPoint, Microsoft.AspNetCore.Http.Features.IFeatureCollection, System.Threading.CancellationToken) in QuicTransportFactory.cs
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(System.Net.EndPoint, Microsoft.AspNetCore.Connections.MultiplexedConnectionDelegate, Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, System.Threading.CancellationToken) in TransportManager.cs
    [External Code]
    Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync.__OnBind|0(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, System.Threading.CancellationToken) in KestrelServerImpl.cs
    [External Code]
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext, System.Threading.CancellationToken) in AddressBinder.cs
    [External Code]
    Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext, System.Threading.CancellationToken) in ListenOptions.cs
    ...
    [Call Stack Truncated]
```

**Comment by JamesNK** [comment]
@wfurt I believe there have been a number of changes in QUIC for loading the cert. Could this be a regression?

**Comment by wfurt** [comment]
what platform @JamesNK? And what version of msquick do you use?

**Comment by JamesNK** [comment]
Windows 10 Build 22357.

I don't know what the version of msquic is. I haven't paid attent to how msquic is packaged.

This error is happening in the latest source code of dotnet/aspnetcore. We update our runtime dependency regularly. Whatever version is pulled in automatically.

**Comment by wfurt** [comment]
ok. I'll give it try. For runtime, squick needs to be built manually and there is no automation. 

cc @ManickaP @CarnaViire in case they have some insight.

**Comment by JamesNK** [comment]
> ok. I'll give it try. For runtime, squick needs to be built manually and there is no automation.

Are you saying that msquic is currently not bundled with the Windows .NET 6 runtime? It needs to be built and installed manually on each computer?

**Comment by CarnaViire** [comment]
That's right, at least for now. The way how msquic will be packaged upon 6.0 release is still under discussion.

We are currently using https://github.com/microsoft/msquic/commit/7b31e149a9d1ed7a6850e8253ba3d0af707150e5 revision. We are keeping the revision number here for now https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/readme.md

**Comment by karelz** [comment]
Triage: @JamesNK can you please confirm it is a regression? Do you have msquic deployed on the machine manually?

**Comment by JamesNK** [comment]
I suspect the issue is caused by not having msquic.dll. I'll retry after getting the recommended version in place.

**Comment by JamesNK** [comment]
I think this is resolved when using modern msquic.dll. Will reopen if I see this error again.
