### ISSUE TITLE
[wasm] System.IO.Compression tests fail on windows/helix

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#52108]
7 tests fail there. It might be related to localization and/or path separators.

One of the failed tests:

```
  fail: [FAIL] System.IO.Compression.Tests.zip_UpdateTests.UpdateCreate(zipFolder: "unicode")
  info: System.IO.DirectoryNotFoundException : Could not find a part of the path '/ZipTestData/refzipfolders/unicode/??.txt'.
  info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
  info:    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
  info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
  info:    at System.IO.Strategies.FileStreamHelpers.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options)
  info:    at System.IO.Strategies.Net5CompatFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
  info:    at System.IO.File.ReadAllBytes(String path)
  info:    at StreamHelpers.CreateTempCopyStream(String path)
  info:    at System.IO.Compression.Tests.ZipFileTestBase.CreateFromDir(String directory, Stream archiveStream, ZipArchiveMode mode, Boolean useSpansForWriting, Boolean writeInChunks)
  info:    at System.IO.Compression.Tests.zip_UpdateTests.UpdateCreate(String zipFolder)
  info: --- End of stack trace from previous location ---
  info: Finished:    System.IO.Compression.Tests.dll
  info:
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 128, Errors: 0, Failed: 7, Skipped: 0, Time: 13.158472s
```

**Comment by radekdoulik** [comment]
Probably same issue if causing fails in `System.IO.Compression.ZipFile` tests.
```
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 44, Errors: 0, Failed: 3, Skipped: 0, Time: 2.442164s
```

**Comment by radekdoulik** [comment]
During startup we get:
```
fail: console.error: MONO_WASM: Failed to load supportFiles/331_??.txt

fail: console.error: MONO_WASM: Unhandled exception in handleFetchResponse attemptNextSource for asset supportFiles/331_??.txt Error: MONO_WASM: Failed to load supportFiles/331_??.txt
```
interestingly it only happens with console engines, like V8 or SpiderMonkey.

In chrome this file loads ok:
```
MONO_WASM: Loaded: supportFiles/331_한글.txt size 1418 from http://localhost:63936/supportFiles/331_%ED%95%9C%EA%B8%80.txt
```

**Comment by pavelsavara** [comment]
This is probably manifestation of https://bugs.chromium.org/p/v8/issues/detail?id=12541 on V8 on windows. 
Does SpiderMonkey have same issue ?
