### ISSUE TITLE
[wasm] System.Xml.Xsl.XslCompiledTransformApi tests fail on windows/helix

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#52136]
Similar issue to `System.IO.Compression` tests:
```
[15:59:49] fail: [FAIL] System.Xml.Tests.CTransformRegressionTest.RegressionTest1(xslInputType: URI, readerType: XmlValidatingReader, outputType: Stream, navType: XPathDocument)
[15:59:49] info: System.IO.FileNotFoundException : Could not find file '/TestFiles/TestData/XsltApiV2/Straße.xml'.
[15:59:49] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
[15:59:49] info:    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
[15:59:49] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
[15:59:49] info:    at System.IO.Strategies.FileStreamHelpers.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options)
[15:59:49] info:    at System.IO.Strategies.Net5CompatFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[15:59:49] info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[15:59:49] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[15:59:49] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[15:59:49] info:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
[15:59:49] info:    at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
[15:59:49] info:    at System.IO.File.Open(String path, FileMode mode)
[15:59:49] info:    at System.Xml.Tests.CTransformRegressionTest.RegressionTest1(XslInputType xslInputType, ReaderType readerType, OutputType outputType, NavType navType)
[15:59:49] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[15:59:49] info: Finished:    System.Xml.Xsl.XslCompiledTransformApi.Tests.dll
[15:59:49] info: 
[15:59:49] info: === TEST EXECUTION SUMMARY ===
[15:59:49] info: Total: 1615, Errors: 0, Failed: 1, Skipped: 29, Time: 22.261575s
```

**Comment by pavelsavara** [comment]
The file is in the emscripten VFS

**Comment by lewing** [comment]
given the name, is this an encoding issue when creating the vfs file?

**Comment by pavelsavara** [comment]
This fails because V8 shell doesn't support unicode filenames
https://bugs.chromium.org/p/v8/issues/detail?id=12541
