### ISSUE TITLE
Test failure System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: True)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#52426]
Run: [runtime 20210506.92](https://dev.azure.com/dnceng/public/_build/results?buildId=1126350&view=ms.vss-test-web.build-test-results-tab&runId=34238916&resultId=121865&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
 -System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: True)
```

**Error message:**
```
System.Diagnostics.Eventing.Reader.EventLogException : The specified publisher name is invalid.


Stack trace
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs:line 46
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName, EventLogSession session, CultureInfo targetCultureInfo, String logFilePath) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 72
   at System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(Boolean noProviderName) in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 35
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress2-jitstressregs 20210724.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1256884&view=ms.vss-test-web.build-test-results-tab&runId=37281924&resultId=134889&paneView=debug)

Failed tests:
```
net6.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open
    System.Diagnostics.Tests.EventLogConfigurationTests.EventLogConfiguration_CheckProperties_RemainsTheSame
    System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests
```

Error Message:
```
System.Diagnostics.Eventing.Reader.EventLogException : The RPC server is unavailable.

Stack trace
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs:line 46
   at System.Diagnostics.Eventing.Reader.EventLogConfiguration..ctor(String logName, EventLogSession session) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogConfiguration.cs:line 46
   at System.Diagnostics.Tests.EventLogConfigurationTests.EventLogConfiguration_CheckProperties_RemainsTheSame(String logName) in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogConfigurationTests.cs:line 33
```

**Comment by danmoseley** [comment]
Test isn't disabled, and hasn't failed for a while. @dotnet/area-system-diagnostics-eventlog such issue can be closed.

Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI2QQUvDQBCF74X%2bhyGnBEopeI4HEUHB0trcRGSTnSYTk52ws6sE%2fPFmd9Veexp4783H41Uo7gXFD07Wq2%2f46tAiJAHKErIHRUN2cZ7Rdayjc7D8SRrtXo1YLRSJsZ7JwAcZXZIxaOGJawE24T7qC%2bfo0aOGW1At5zc7XQRrstxj49YrSH4gb36jm6BW87QIqUO4IqrF6Bw6JTEPJTgWZ8m0%2baSs4HsvbPKl7ITWEUrxmp1mcThu%2f3%2bytyJBaMKBzBWM7T2eyZAjNgGQ3k%2fsbZPq3Hka9BWYmNv7sUYbF2C7DAr1%2fLePRml%2bAJUloRGiAQAA) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI2QQUvDQBCF74X%2bhyGnBEopeI4HEUHB0trcRGSTnSYTk52ws6sE%2fPFmd9Veexp4783H41Uo7gXFD07Wq2%2f46tAiJAHKErIHRUN2cZ7Rdayjc7D8SRrtXo1YLRSJsZ7JwAcZXZIxaOGJawE24T7qC%2bfo0aOGW1At5zc7XQRrstxj49YrSH4gb36jm6BW87QIqUO4IqrF6Bw6JTEPJTgWZ8m0%2baSs4HsvbPKl7ITWEUrxmp1mcThu%2f3%2bytyJBaMKBzBWM7T2eyZAjNgGQ3k%2fsbZPq3Hka9BWYmNv7sUYbF2C7DAr1%2fLePRml%2bAJUloRGiAQAA&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI2QQUvDQBCF74X%2bhyGnBEopeI4HEUHB0trcRGSTnSYTk52ws6sE%2fPFmd9Veexp4783H41Uo7gXFD07Wq2%2f46tAiJAHKErIHRUN2cZ7Rdayjc7D8SRrtXo1YLRSJsZ7JwAcZXZIxaOGJawE24T7qC%2bfo0aOGW1At5zc7XQRrstxj49YrSH4gb36jm6BW87QIqUO4IqrF6Bw6JTEPJTgWZ8m0%2baSs4HsvbPKl7ITWEUrxmp1mcThu%2f3%2bytyJBaMKBzBWM7T2eyZAjNgGQ3k%2fsbZPq3Hka9BWYmNv7sUYbF2C7DAr1%2fLePRml%2bAJUloRGiAQAA&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI2QQUvDQBCF74X%2bhyGnBEopeI4HEUHB0trcRGSTnSYTk52ws6sE%2fPFmd9Veexp4783H41Uo7gXFD07Wq2%2f46tAiJAHKErIHRUN2cZ7Rdayjc7D8SRrtXo1YLRSJsZ7JwAcZXZIxaOGJawE24T7qC%2bfo0aOGW1At5zc7XQRrstxj49YrSH4gb36jm6BW87QIqUO4IqrF6Bw6JTEPJTgWZ8m0%2baSs4HsvbPKl7ITWEUrxmp1mcThu%2f3%2bytyJBaMKBzBWM7T2eyZAjNgGQ3k%2fsbZPq3Hka9BWYmNv7sUYbF2C7DAr1%2fLePRml%2bAJUloRGiAQAA&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults
| where Result == "Fail"
| where Method == "ProviderNameTests"
| join kind=inner Jobs on JobId
| where Queued > ago(30d)
| project
  QueueName, Queued,
  Type, Method, Message,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Source,
  Build = tostring(parse_json(Properties).BuildNumber)
| order by Queued desc
```
