### ISSUE TITLE
MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters fail in CI

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#52464]
https://helix.dot.net/api/2019-06-17/jobs/b74d646c-0b23-426a-a216-4558f6f696dc/workitems/System.Runtime.Caching.Tests/console

https://dev.azure.com/dnceng/public/_build/results?buildId=1127816&view=logs&j=a68d6dca-d11c-59af-6c4a-cf852cb20e3a&t=28d89dec-7e09-5293-5fd2-aeb03e603264&l=55

```
C:\h\w\A5DB091B\w\AA940930\e>"C:\h\w\A5DB091B\p\dotnet.exe" exec --runtimeconfig System.Runtime.Caching.Tests.runtimeconfig.json --depsfile System.Runtime.Caching.Tests.deps.json xunit.console.dll System.Runtime.Caching.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Runtime.Caching.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Caching.Tests (found 31 of 37 test cases)
  Starting:    System.Runtime.Caching.Tests (parallel test collections = on, max threads = 4)
    MonoTests.System.Runtime.Caching.MemoryCacheTest.PhysicalMemoryLimitNotSupported [SKIP]
      Condition(s) not met: "DoesNotSupportPhysicalMemoryMonitor"
    MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs(94,0): at MonoTests.System.Runtime.Caching.CountersTest.PollCounters(String cacheName)
        /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs(49,0): at MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(1896,0): at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
  Finished:    System.Runtime.Caching.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Caching.Tests  Total: 31, Errors: 0, Failed: 1, Skipped: 1, Time: 7.586s
```

cc @StephenMolloy - looks like these tests were just added in https://github.com/dotnet/runtime/pull/51760

**Comment by ericstj** [comment]
Another hit https://dev.azure.com/dnceng/public/_build/results?buildId=1128311&view=ms.vss-test-web.build-test-results-tab&runId=34278178&resultId=118890&paneView=debug.

**Comment by steveisok** [comment]
The namespace confused me for a bit ;-)

**Comment by MihaZupan** [comment]
https://github.com/dotnet/runtime/pull/52488 should fix this

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress 20210507.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1127245&view=ms.vss-test-web.build-test-results-tab&runId=34256342&resultId=120034&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_checked-zapdisable-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 -MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at MonoTests.System.Runtime.Caching.CountersTest.PollCounters(String cacheName) in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs:line 94
   at MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters() in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs:line 49
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1896
```

**Comment by StephenMolloy** [comment]
#52490 should fix this. Waiting for it to pass all checks.

**Comment by ericstj** [comment]
Indeed this appears to be fixed, last instance was https://dev.azure.com/dnceng/public/_build/results?buildId=1128770&view=results which was before this was merged.  Thank you for the fast turn around @StephenMolloy!
