### ISSUE TITLE
 MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters failed

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#52527]
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at MonoTests.System.Runtime.Caching.CountersTest.PollCounters(String cacheName) in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs:line 94
   at MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters() in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs:line 49
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1896
```
https://dev.azure.com/dnceng/public/_build/results?buildId=1128710&view=ms.vss-test-web.build-test-results-tab&runId=34284980&resultId=177413&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

net6.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open

@StephenMolloy it looks like you only just added this test.

**Comment by danmoseley** [comment]
I don't know, happy to close and see.
