### ISSUE TITLE
SocketsHttpHandler stops sending intermediate certificates on recreated connection

### ISSUE THREAD

**Issue by iouri-s** [dotnet/runtime#52550]
### Description

When using an HttpClient with client certificate authentication, the certificate is sent along with intermediate certificates. After some time, however, it stops sending the intermediate certs. We were able to confirm that this timeout is the same as the value of PooledConnectionLifetime.

We are using a static HttpClient:
```c#
            _httpClient = new HttpClient(new SocketsHttpHandler
            {
                SslOptions = new SslClientAuthenticationOptions
                {
                    CertificateRevocationCheckMode = X509RevocationMode.NoCheck,
                    ClientCertificates = new X509CertificateCollection(new[] { clientCert })
                },
                AutomaticDecompression = System.Net.DecompressionMethods.GZip,
                UseCookies = false,
                ConnectTimeout = TimeSpan.FromSeconds(15),
                PooledConnectionLifetime = lifetime,
                PooledConnectionIdleTimeout = TimeSpan.FromMinutes(1),
            });
```
If you send requests using this client, then after `lifetime` there will be an exception if the server does not download imntermediate certs (and our server doesn't).We are able to repro the issue reliably in a console app. Not including the project here because it uses a production cert.
```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
 ```

### Configuration

* Which version of .NET is the code running on? 5.0.103
* What OS and version, and what distro if applicable? Ubuntu 20.04
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? Linux-specific

### Regression?

This is a regression from .Net Core 3.1

### Other information

The reason the exception is thrown is that the server we are connecting to does not download intermediate certificates. With a different server, the code works fine.

**Comment by scalablecory** [comment]
@wfurt

**Comment by iouri-s** [comment]
Other things we tried with the same result:
* Using HttpClientHandler
* Recreating the client without waiting for the connection lifetime to expire:
Create client
Send request
Wait 10 seconds
Create client
Send request - *boom! - exception*
Running on Windows works fine

**Comment by wfurt** [comment]
Can you check with updated sdk/runtime @iouri-s?

**Comment by iouri-s** [comment]
It is indeed fixed with the latest runtime!
