### ISSUE TITLE
Blazor: BindConverter.TryConvertTo<Guid> throws an exception

### ISSUE THREAD

**Issue by anranruye** [dotnet/runtime#52636]
### Describe the bug

`BindConverter.TryConvertTo<Guid>` throws an exception when the input value is not well-formated(for example, an incomplete Guid string). It's strange that a TryXXX method throws an exception, but it does.

### To Reproduce

```
<button @onclick="Click">Click</button>

@code{
    void Click()
    {
        string guidString = Guid.NewGuid().ToString();
        Console.WriteLine(BindConverter.TryConvertTo<Guid>(guidString, System.Globalization.CultureInfo.CurrentCulture, out var guid)); // output: true
        Console.WriteLine(BindConverter.TryConvertTo<Guid>(guidString[0..5], System.Globalization.CultureInfo.CurrentCulture, out guid)); // throws exception
    }
}
```
### Exceptions (if any)

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid..ctor(String g)
   at System.ComponentModel.GuidConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Microsoft.AspNetCore.Components.BindConverter.ParserDelegateCache.<>c__DisplayClass4_0`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<MakeTypeConverterConverter>g__ConvertWithTypeConverter|0(Object obj, CultureInfo culture, Guid& value)
   at Microsoft.AspNetCore.Components.BindConverter.TryConvertTo[Guid](Object obj, CultureInfo culture, Guid& value)
```
### Further technical details
- ASP.NET Core version: 5.x

**Comment by campersau** [comment]
@javiercn from the stacktrace it looks like the correct behavior since the `Guid` ctor is called from `GuidConverter` which is called by `BindConverter`.
Maybe a new case for `Guid` should be added here?
https://github.com/dotnet/aspnetcore/blob/d8906c8523f071371ce95d4e2d2fdfa89858047e/src/Components/Components/src/BindConverter.cs#L1416-L1509
Or add a try catch here?
https://github.com/dotnet/aspnetcore/blob/d8906c8523f071371ce95d4e2d2fdfa89858047e/src/Components/Components/src/BindConverter.cs#L1533

**Comment by jeffl8n** [comment]
I agree with @campersau.  It looks like this would be handled on the aspnetcore side in the BindConverter.cs class.  Other types are handling some validation checks (ex: empty string when converting to int).  If the design is to not through an exception in BindConverter.TryConvertTo(...), it may be best to put a try/catch in that statement and return false in case of an exception - https://github.com/dotnet/aspnetcore/blob/d8906c8523f071371ce95d4e2d2fdfa89858047e/src/Components/Components/src/BindConverter.cs#L1276

**Comment by safern** [comment]
Yes I agree this is by design on the `GuidConverter` front as it is just calling the `Guid` constructor and that is the behavior for all the type converters. Definitely it seems like `BindConverter.tryConvertTo` is not following the `Try` pattern which is catching exceptions and returning false when there is an exception. 

I think we should transfer this back to aspnetcore.
