### ISSUE TITLE
Test failure System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendSuper)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#52737]
Run: [runtime 20210513.81](https://dev.azure.com/dnceng/public/_build/results?buildId=1138119&view=ms.vss-test-web.build-test-results-tab&runId=34528676&resultId=151590&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_checked-OSX.1013.Amd64.Open

- System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendSuper)
- System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendFpret)
- System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSend)

```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70

Child process:
  System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)

Child arguments:
  MsgSendSuper
```

**Comment by AaronRobinsonMSFT** [comment]
Oh sad. This was missed in the PR build because there is no build that runs where the `msgSend` P/Invokes would be inlined. In this case the problem is because the signatures are blittable and therefore inlined the logic to check for a pending exception has been elided.

**Comment by AaronRobinsonMSFT** [comment]
See https://github.com/AaronRobinsonMSFT/runtime/tree/runtime52737 for a preliminary fix.
