### ISSUE TITLE
[Mono Android][Test] tracing/eventactivityidcontrol/eventactivityidcontrol fails on Android

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#52763]
tracing/eventactivityidcontrol/eventactivityidcontrol fails on Android for both x64 and arm64

Here is the failure log:

```
3241  3267 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.322  3241  3267 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.322  3241  3267 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.322  3241  3267 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.326  3241  3282 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.326  3241  3282 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.326  3241  3282 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.326  3241  3282 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.327  3241  3284 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.327  3241  3284 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.327  3241  3284 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.327  3241  3284 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.327  3241  3283 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.327  3241  3283 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.327  3241  3283 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.327  3241  3283 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.330  3241  3285 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.330  3241  3285 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.330  3241  3285 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.330  3241  3285 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.333  3241  3286 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.333  3241  3286 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.333  3241  3286 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.333  3241  3286 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.334  3241  3287 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.334  3241  3287 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.334  3241  3287 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.334  3241  3287 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.334  3241  3288 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.334  3241  3288 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.334  3241  3288 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.334  3241  3288 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.335  3241  3289 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.335  3241  3289 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.335  3241  3289 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.335  3241  3289 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.335  3241  3290 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.335  3241  3290 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.335  3241  3290 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.335  3241  3290 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.336  3241  3291 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.336  3241  3291 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.336  3241  3291 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.336  3241  3291 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.343  1585  1662 I RoleManagerService: Granting default roles...
05-13 15:21:00.374  3241  3299 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.374  3241  3299 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.374  3241  3299 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.374  3241  3299 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.374  3241  3300 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.374  3241  3300 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.374  3241  3300 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3300 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3298 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3298 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3298 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3298 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3295 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3295 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3295 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3295 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3292 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3292 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3292 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3292 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3296 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3296 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3296 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3296 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.375  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.375  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.375  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.375  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.376  3241  3297 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.376  3241  3297 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.376  3241  3297 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.376  3241  3297 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3292 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3292 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3296 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3296 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3296 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3296 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3298 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3298 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3297 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3297 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3297 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3297 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3292 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3292 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3292 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.385  3241  3298 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.385  3241  3298 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.385  3241  3298 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3299 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3299 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3299 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3299 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3295 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3295 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3295 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3295 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3294 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3294 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3294 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3294 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.386  3241  3296 I DOTNET  : System.Exception: Values for 'retCode' are not equal! Left='1' Right='0'
05-13 15:21:00.386  3241  3296 I DOTNET  :    at Tracing.Tests.Common.Assert.Equal[Int32](String name, Int32 left, Int32 right) in common.dll:token 0x6000002+0x75
05-13 15:21:00.386  3241  3296 I DOTNET  :    at Tracing.Tests.EventActivityIdControlTest.TestThreadProc()
05-13 15:21:00.386  3241  3296 I DOTNET  :  in eventactivityidcontrol.dll:token 0x6000002+0xf
05-13 15:21:00.390  3241  3267 D DOTNET  : Exit code: 0.
```

**Comment by fanyang-mono** [comment]
Could you take a look at these tests? @lateralusX

**Comment by lateralusX** [comment]
We will need to start including runtime components (in this case diagnostics_tracing) as part of our device testing for these tests to work.
