### ISSUE TITLE
Settings to access printer '\\IP_Address\Printer_Name' are not valid

### ISSUE THREAD

**Issue by apetrut** [dotnet/runtime#52821]
Hi,

I am using the code below to print using a network printer:

```
report.CreateDocument(false);
report.PrintingSystem.ShowMarginsWarning = false;
report.PrintingSystem.ShowPrintStatusDialog = false;
report.PrintingSystem.PageSettings.PrinterName = printerName;

```

and I am getting the errors below:

```
Settings to access printer '\\IP_Address\Printer_Name' are not valid.
   at System.Drawing.Printing.PageSettings.get_PaperSize()
   at System.Drawing.Printing.PrintingServices.CreateGraphicsContext(PrinterSettings settings, PageSettings default_page_settings)
   at System.Drawing.Printing.StandardPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e)
   at System.Drawing.Printing.PrintDocument.Print()
   at DevExpress.XtraPrinting.PrintingSystemBase.PrintDocument(PrintDocument pd)
```

and also:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Drawing.Printing.PrintingServices.EndDoc(GraphicsPrinter gr)
   at System.Drawing.Printing.StandardPrintController.OnEndPrint(PrintDocument document, PrintEventArgs e)
   at DevExpress.XtraPrinting.PrintingSystemBase.PrintDocument(PrintDocument pd)
```

I couldn't find how to set the pageSize before sending to the printer. Are there any other settings that needs to be made in order for this code to work?

Thanks,
Andrei

**Comment by apetrut** [comment]
A possible solution was posted [here](https://github.com/dotnet/runtime/issues/52761).
