### ISSUE TITLE
ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting fails on Mono

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#52910]
The test was added in https://github.com/dotnet/runtime/pull/52690 but it fails on Mono in the runtime-staging pipeline:

```
   System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(maxRate: 8000, minRate: 0, procCountConfig: "1") [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   2
      Stack Trace:
        /_/src/libraries/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs(165,0): at System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(UInt16 maxRate, UInt16 minRate, String procCountConfig)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(maxRate: 2000, minRate: 0, procCountConfig: null) [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   2
      Stack Trace:
        /_/src/libraries/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs(165,0): at System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(UInt16 maxRate, UInt16 minRate, String procCountConfig)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(maxRate: 2000, minRate: 0, procCountConfig: " 0x11 ") [FAIL]
      Assert.Equal() Failure
      Expected: 17
      Actual:   2
      Stack Trace:
        /_/src/libraries/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs(165,0): at System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(UInt16 maxRate, UInt16 minRate, String procCountConfig)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(maxRate: 0, minRate: 0, procCountConfig: "3") [FAIL]
      Assert.Equal() Failure
      Expected: 3
      Actual:   2
      Stack Trace:
        /_/src/libraries/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs(165,0): at System.Tests.EnvironmentProcessorCount.ProcessorCount_Windows_RespectsJobCpuRateAndConfigurationSetting(UInt16 maxRate, UInt16 minRate, String procCountConfig)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Runtime.Extensions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Extensions.Tests  Total: 7835, Errors: 0, Failed: 4, Skipped: 3, Time: 10.021s

```

**Comment by mangod9** [comment]
@AntonLapounov  as FYI.. perhaps an equivalent change is required for mono?

**Comment by AntonLapounov** [comment]
@mangod9 At present Mono does not support cgroup limits on Unix or process affinity on Windows, so it would require more work than just doing an equivalent change.

**Comment by CoffeeFlux** [comment]
This seems to mostly matter for containers, which aren't an immediate priority.
