### ISSUE TITLE
[wasm][aot] `RuntimeError: memory access out of bounds` for `System.Collections.NonGeneric.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#52939]
[Log for failure on the test PR](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-1e0646b76107432086/System.Collections.NonGeneric.Tests/console.7a740a5e.log?sv=2019-07-07&se=2021-06-03T17%3A06%3A01Z&sr=c&sp=rl&sig=WZRe8gUkcywUHDZabCLAzwOX9qIE3HuTcj5stqRw6v4%3D)

This was also seen on https://github.com/dotnet/runtime/pull/52870 ([log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52870-merge-ba0f9e86d0c6488984/System.Collections.NonGeneric.Tests/console.a93eb783.log?sv=2019-07-07&se=2021-06-07T19%3A25%3A03Z&sr=c&sp=rl&sig=cJqG961uNnivC7nYIA%2Fn29ye1b%2B0DCXY%2FDW%2FV1V4cJo%3D))

```
Starting:    System.Collections.NonGeneric.Tests.dll

console.error: RuntimeError: memory access out of bounds
console.error: RuntimeError: memory access out of bounds

    at corlib_string_CompareTo_object (<anonymous>:wasm-function[30802]:0x749b5a)
    at invoke_iiii (dotnet.js:11761:32)
    at xunit_assert_Xunit_Sdk_AssertEqualityComparer_1_T_REF_Equals_T_REF_T_REF (<anonymous>:wasm-function[23511]:0x50d346)
    at xunit_assert_Xunit_Assert_Equal_T_REF_T_REF_T_REF_System_Collections_Generic_IEqualityComparer_1_T_REF (<anonymous>:wasm-function[23437]:0x5014dd)
    at xunit_assert_Xunit_Assert_Equal_T_REF_T_REF_T_REF (<anonymous>:wasm-function[23436]:0x501367)
    at System_Collections_NonGeneric_Tests_System_Collections_Tests_SortedListTests__c__DisplayClass25_0__CopyTob__0_System_Collections_SortedList (<anonymous>:wasm-function[64274]:0x14f593e)
    at System_Collections_NonGeneric_Tests_wrapper_delegate_invoke_System_Action_1_System_Collections_SortedList_invoke_void_T_System_Collections_SortedList (<anonymous>:wasm-function[64702]:0x152073f)
    at System_Collections_NonGeneric_Tests_System_Collections_Tests_Helpers_PerformActionOnAllSortedListWrappers_System_Collections_SortedList_System_Action_1_System_Collections_SortedList (<anonymous>:wasm-function[62933]:0x1450aa0)
    at System_Collections_NonGeneric_Tests_System_Collections_Tests_SortedListTests_CopyTo_int_int (<anonymous>:wasm-function[63206]:0x14916c7)
    at corlib_aot_wrapper_gsharedvt_out_sig_void_this_i4i4 (<anonymous>:wasm-function[41989]:0xb32ef6)
    at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[41135]:0xae585a)
    at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[4848]:0xbd4ca)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4820]:0xbbc53)
    at do_runtime_invoke (<anonymous>:wasm-function[2188]:0x77fa3)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[2186]:0x77f4e)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[2338]:0x7c10e)
    at mono_runtime_invoke_array_checked (<anonymous>:wasm-function[2342]:0x7c72f)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[1038]:0x57a4a)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1196]:0x5c7fe)
    at aot_wrapper_corlib_System_dot_Reflection_System_dot_Reflection_dot_RuntimeMethodInfo__InternalInvoke_pinvoke_obj_this_objclc_object_5b_5d_bclsc_Exception_26__attrs_2obj_cls1d_Reflection_dRuntimeMethodInfo_objclc_object_5b_5d_bclsc_Exception_26__attrs_2 (<anonymous>:wasm-function[37049]:0x972ad6)
    at invoke_iiiiii (dotnet.js:11783:32)
    at corlib_System_Reflection_RuntimeMethodInfo_Invoke_object_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo (<anonymous>:wasm-function[37050]:0x973052)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_CallTestMethod_object (<anonymous>:wasm-function[19811]:0x396d8b)
    at invoke_iiii (dotnet.js:11761:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass48_1___InvokeTestMethodAsyncb__1d_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19826]:0x399fb6)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[22085]:0x4a530d)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[21520]:0x480768)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass48_1_TTestCase_REF__InvokeTestMethodAsyncb__1 (<anonymous>:wasm-function[19825]:0x398402)
    at corlib_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_invoke_TResult (<anonymous>:wasm-function[40040]:0xa75c59)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_MoveNext (<anonymous>:wasm-function[19658]:0x379491)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_ (<anonymous>:wasm-function[21431]:0x47a6ee)
    at xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer_AggregateAsync_System_Func_1_System_Threading_Tasks_Task (<anonymous>:wasm-function[19656]:0x3790fe)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1__c__DisplayClass48_1_TTestCase_REF__InvokeTestMethodAsyncb__0 (<anonymous>:wasm-function[19824]:0x3982e8)
    at corlib_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_invoke_TResult (<anonymous>:wasm-function[40040]:0xa75c59)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_MoveNext (<anonymous>:wasm-function[22807]:0x4cdcfd)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_ (<anonymous>:wasm-function[23031]:0x4eab87)
    at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Func_1_System_Threading_Tasks_Task (<anonymous>:wasm-function[22803]:0x4cd5ba)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[41396]:0xb21be6)
    at jit_call_cb (<anonymous>:wasm-function[9011]:0x149942)
    at invoke_vi (dotnet.js:11717:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5847]:0xdd3d8)
    at do_jit_call (<anonymous>:wasm-function[8970]:0x148bfd)
    at interp_exec_method (<anonymous>:wasm-function[8911]:0x13b945)
    at interp_entry (<anonymous>:wasm-function[8953]:0x1481ab)
    at interp_entry_instance_1 (<anonymous>:wasm-function[9026]:0x149df7)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_this_bii (<anonymous>:wasm-function[43031]:0xb5017f)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_InvokeTestMethodAsync_object (<anonymous>:wasm-function[19814]:0x3979bf)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestInvoker_InvokeTestMethodAsync_object (<anonymous>:wasm-function[19999]:0x3cb3aa)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[41396]:0xb21be6)
    at jit_call_cb (<anonymous>:wasm-function[9011]:0x149942)
    at invoke_vi (dotnet.js:11717:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5847]:0xdd3d8)
    at do_jit_call (<anonymous>:wasm-function[8970]:0x148bfd)
    at interp_exec_method (<anonymous>:wasm-function[8911]:0x13b7ff)
    at interp_entry (<anonymous>:wasm-function[8953]:0x1481ab)
    at interp_entry_instance_1 (<anonymous>:wasm-function[9026]:0x149df7)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_this_bii (<anonymous>:wasm-function[43031]:0xb5017f)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF__RunAsyncb__47_0 (<anonymous>:wasm-function[19816]:0x397bc4)
    at xunit_execution_dotnet_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_1_System_Decimal_invoke_TResult (<anonymous>:wasm-function[20937]:0x4446ef)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_MoveNext (<anonymous>:wasm-function[21517]:0x47fb07)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_ (<anonymous>:wasm-function[22074]:0x4a4223)
    at xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Decimal_System_Func_1_System_Threading_Tasks_Task_1_System_Decimal (<anonymous>:wasm-function[21516]:0x47f81f)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19813]:0x397885)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestMethodAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[20013]:0x3cd3e0)
    at invoke_iiii (dotnet.js:11761:32)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_MoveNext (<anonymous>:wasm-function[20014]:0x3cd99a)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_ (<anonymous>:wasm-function[21638]:0x48a282)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[20012]:0x3cd0a1)
    at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__c__DisplayClass43_0_TTestCase_REF__RunAsyncb__0 (<anonymous>:wasm-function[19879]:0x3a451f)
    at xunit_execution_dotnet_wrapper_delegate_invoke_System_Func_1_System_Threading_Tasks_Task_1_System_Tuple_2_System_Decimal_string_invoke_TResult (<anonymous>:wasm-function[20975]:0x44705a)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_core_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_T_REF_MoveNext (<anonymous>:wasm-function[22809]:0x4cea5d)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[23189]:0x4f18e3)
    at xunit_core_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[23033]:0x4eaedf)
    at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_T_REF_System_Func_1_System_Threading_Tasks_Task_1_T_REF (<anonymous>:wasm-function[22804]:0x4cd789)
    at invoke_iiii (dotnet.js:11761:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1__RunAsyncd__43_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19880]:0x3a5975)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__9 (<anonymous>:wasm-function[22090]:0x4a62f4)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[21529]:0x480c65)
    at xunit_execution_dotnet_Xunit_Sdk_TestRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19877]:0x3a4372)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_MoveNext (<anonymous>:wasm-function[20037]:0x3dc128)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_ (<anonymous>:wasm-function[21651]:0x48b51b)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[20022]:0x3cee56)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1__RunAsyncd__19_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19719]:0x3844af)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[22064]:0x4a27b0)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[21497]:0x47e52b)
    at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19650]:0x3787e7)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20275]:0x4062cc)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[20010]:0x3ccf4e)
    at invoke_iiii (dotnet.js:11761:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunTestCasesAsyncd__32_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19854]:0x3a2cdd)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__8 (<anonymous>:wasm-function[22087]:0x4a5cb3)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[21525]:0x4809e5)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunTestCasesAsync (<anonymous>:wasm-function[19848]:0x39f9a6)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1__RunAsyncd__31_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19849]:0x3a0213)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[22086]:0x4a57e3)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[21524]:0x48096f)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19847]:0x39f7e6)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[19942]:0x3b6cd5)
    at invoke_iiiiiii (dotnet.js:11893:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunTestMethodsAsyncd__38_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19760]:0x38f58b)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[22067]:0x4a319e)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__3 (<anonymous>:wasm-function[21505]:0x47f1da)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunTestMethodsAsync (<anonymous>:wasm-function[19747]:0x388cbf)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1__RunAsyncd__37_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19755]:0x38a7a7)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[22066]:0x4a2d11)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[21504]:0x47f164)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19746]:0x388aff)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[19975]:0x3c404f)
    at invoke_iiiiii (dotnet.js:11783:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunTestClassesAsyncd__28_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19787]:0x3950d6)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[22071]:0x4a3c6c)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__5 (<anonymous>:wasm-function[21512]:0x47f589)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunTestClassesAsync (<anonymous>:wasm-function[19778]:0x39091d)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1__RunAsyncd__27_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19779]:0x3915f5)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[22070]:0x4a37df)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[21511]:0x47f513)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19777]:0x39075d)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19898]:0x3ac91c)
    at invoke_iiiiiii (dotnet.js:11893:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunTestCollectionsAsyncd__42_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19707]:0x382f22)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[22060]:0x4a2111)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[21489]:0x47e1cc)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19694]:0x37e650)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19900]:0x3acb66)
    at invoke_iiiii (dotnet.js:11805:32)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_MoveNext (<anonymous>:wasm-function[19912]:0x3adf52)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[21533]:0x480ede)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19897]:0x3ac696)
    at invoke_iiiii (dotnet.js:11805:32)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1__RunAsyncd__41_TTestCase_REF_MoveNext (<anonymous>:wasm-function[19702]:0x37fe4e)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[22059]:0x4a1c6e)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST_ (<anonymous>:wasm-function[21488]:0x47e156)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19693]:0x37e40c)
    at invoke_iii (dotnet.js:11739:32)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_MoveNext (<anonymous>:wasm-function[20272]:0x4056a0)
    at invoke_vii (dotnet.js:11772:25)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[21713]:0x48ef40)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20270]:0x405155)
    at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20142]:0x3e7a84)
    at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[15882]:0x21347a)
    at invoke_viiiii (dotnet.js:11860:25)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_MoveNext (<anonymous>:wasm-function[66465]:0x1594d78)
    at invoke_vii (dotnet.js:11772:25)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[66593]:0x15a4427)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[66452]:0x158fec3)
    at invoke_iiiii (dotnet.js:11805:32)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_MoveNext (<anonymous>:wasm-function[66486]:0x159ac97)
    at invoke_vii (dotnet.js:11772:25)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[66657]:0x15a6b7a)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[66483]:0x15973f7)
    at invoke_iii (dotnet.js:11739:32)
    at WasmTestRunner_SimpleWasmTestRunner__Maind__0_MoveNext (<anonymous>:wasm-function[24125]:0x53f7e7)
    at invoke_vii (dotnet.js:11772:25)
    at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[24169]:0x543c6e)
    at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[24121]:0x53cb0d)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_obj (<anonymous>:wasm-function[41380]:0xb21658)
    at invoke_viii (dotnet.js:11750:25)
    at corlib_wrapper_runtime_invoke_object_runtime_invoke_sig_void_intptr_intptr_intptr_object_intptr_intptr_intptr (<anonymous>:wasm-function[41134]:0xae5595)
    at mono_llvmonly_runtime_invoke (<anonymous>:wasm-function[4848]:0xbd4ca)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4820]:0xbbc53)
    at do_runtime_invoke (<anonymous>:wasm-function[2188]:0x77fa3)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[2197]:0x78598)
    at mono_runtime_invoke (<anonymous>:wasm-function[2272]:0x7a5da)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[66887]:0x15ac386)
    at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:11110:117)
    at Object._call_method_with_converted_args (dotnet.js:9181:30)
    at Object.call_method (dotnet.js:9141:18)
    at dotnet.js:9400:29
    at Object.call_assembly_entry_point (dotnet.js:9407:66)
    at Object.init (runtime.js:355:24)
    at Object.config.loaded_cb (runtime.js:241:8)
    at Object._finalize_startup (dotnet.js:7357:11)
    at onPendingRequestComplete (dotnet.js:7394:14)
    at processFetchResponseBuffer (dotnet.js:7409:8)
Process v8 exited with 1
Application has finished with exit code 1 but 0 was expected
```

**Comment by radical** [comment]
This hasn't been hit in the last few weeks.
