### ISSUE TITLE
[wasm][http] BrowserHttpHandler.SendAsync - JavaScript host object 'Headers' not found

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#52969]
Unit test `System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.SendAsync_SimpleGet_Success` failure `JavaScript host object 'Headers' not found`

### Description

```
[FAIL] System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.SendAsync_SimpleGet_Success(remoteServer: (BaseUri: http://127.0.0.1:63172/, HttpVersion: 1.1))
System.Net.Http.HttpRequestException : JavaScript host object 'Headers' not found.
    at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 323
    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
    at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.SendAsync_SimpleGet_Success(RemoteServer remoteServer) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.RemoteServer.cs:line 83
```

### Configuration
V8 on windows, the tests are currently hidden in [OuterLoop]
Regression: Probably not

**Comment by lewing** [comment]
None of the networking tests are expected to work on v8 right now they'd need to add a check like [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsBrowserDomSupported))] since `PlatformDetection.IsBrowserDomSupported` is the (somewhat poorly named) property that indicates to the test that it is inside an actual browser and can do things like create websockets and call fetch.

**Comment by karelz** [comment]
@lewing @pavelsavara can you please triage this one? (set milestone + remove Untriaged label) Thanks!

**Comment by pavelsavara** [comment]
Closed by https://github.com/dotnet/runtime/pull/53027
