### ISSUE TITLE
[wasm][HTTP] TypeError: Failed to fetch

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#53018]
Broken tests in
- System.Net.Http.Functional.Tests.SyncHttpHandler_PostScenarioTest
- System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest 

Tests fail with 
```
System.Net.Http.HttpRequestException : TypeError: Failed to fetch   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.SendAsync_SendRequestUsingMethodToEchoServerWithNoContent_MethodCorrectlySent(String method, Uri serverUri)
```

Part of the failures could be caused by lack of CORS support on the remote test server in Azure.

**Comment by karelz** [comment]
@lewing @pavelsavara can you please triage this one? (set milestone + remove Untriaged label) Thanks!

**Comment by pavelsavara** [comment]
Caused by using HTTPS for HTTP listener port in the unit test.

**Comment by karelz** [comment]
@pavelsavara FYI: I marked it triaged on your behalf
