### ISSUE TITLE
[wasm] emscripten 2.0.21 introduces failures where UnauthorizedAccessException is not thrown

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#53021]
Happens in `System.IO.FileSystem.Tests.dll` and `System.IO.MemoryMappedFiles.Tests.dll`.

```
[23:13:25] info: console.info: Arguments: --working-dir=/test-dir,--run,WasmTestRunner.dll,System.IO.FileSystem.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[23:13:25] info: console.debug: MONO_WASM: Initializing mono runtime
[23:13:25] info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[23:13:25] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[23:13:25] info: console.info: Initializing.....
[23:13:25] info: Discovering: System.IO.FileSystem.Tests.dll (method display = ClassAndMethod, method display options = None)
[23:13:25] info: Discovered:  System.IO.FileSystem.Tests.dll (found 2619 of 3450 test cases)
[23:13:25] info: Starting:    System.IO.FileSystem.Tests.dll
[23:13:26] fail: [FAIL] System.IO.Tests.File_ReadLines.WriteToReadOnlyFile
[23:13:26] info: Assert.Throws() Failure
[23:13:26] info: Expected: typeof(System.UnauthorizedAccessException)
[23:13:26] info: Actual:   (No exception was thrown)
[23:13:26] info:    at System.IO.Tests.File_ReadWriteAllLines_Enumerable.WriteToReadOnlyFile()
[23:13:26] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
...
```

**Comment by radekdoulik** [comment]
This issue was introduced between emscripten `2.0.17` and `2.0.18`.

Tracked it down to not failing `SystemNative_Open` call:

    info: rodo: SystemNative_Open path: /tmp/File_AppendText_qpzicxrj.0hj/WriteToReadOnlyFile_116_673e65f1 flags: 524353 mode: 438 result 4 0x4

which should fail because of errno 8, `Bad file descriptor`, we are opening read-only file for writting.

It should return `-1` like with current main and emscripten 2.0.12:

    rodo: SystemNative_Open path: /tmp/test.txt flags: 524353 mode: 438 result -1 0xFFFFFFFF

After further inspection, found an issue in the `FS.nodePermissions` function, where we ignore the permissions, because `FS.ignorePermissions` is set to `true`.

In earlier versions, the `FS.ignorePermissions` was set to `false` in `preMain` function. This function is now missing from `dotnet.js`.

I will further look into why this function is missing, whether we want it back or set `FS.ignorePermissions` in another place.

**Comment by radekdoulik** [comment]
The `preMain()` was removed intentionally in emscripten. It broke the permissions after FS initialization. Opened https://github.com/emscripten-core/emscripten/issues/14299

**Comment by ilonatommy** [comment]
They are not failing anymore, @radekdoulik do you agree with enabling these 3 tests and closing?
