### ISSUE TITLE
System.CodeDom.Tests failed with System.NullReferenceException : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53055]
Run: [runtime 20210520.95](https://dev.azure.com/dnceng/public/_build/results?buildId=1148867&view=ms.vss-test-web.build-test-results-tab&runId=34758812&resultId=113750&paneView=debug)

Failed tests:
```
net6.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.312.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-arm64v8-20200602002604-25f8a3e

- System.CodeDom.Tests.CodeTypeParameterCollectionTests.AddRange_CodeStatementArray_Works
- System.CodeDom.Tests.CodeTypeParameterCollectionTests.AddRange_CodeStatementCollection_Works
- System.CodeDom.Tests.CodeTypeParameterCollectionTests.Ctor_Array_Works
- System.CodeDom.Tests.CodeTypeParameterCollectionTests.Ctor_CodeStatementCollection_Works

net6.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

- System.CodeDom.Tests.CodeAttributeArgumentCollectionTests.AddRange_CodeStatementArray_Works
- System.CodeDom.Tests.CodeAttributeArgumentCollectionTests.AddRange_CodeStatementCollection_Works
- System.CodeDom.Tests.CodeAttributeArgumentCollectionTests.Ctor_Array_Works
- System.CodeDom.Tests.CodeAttributeArgumentCollectionTests.Ctor_CodeStatementCollection_Works

```
**One of Error messages:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.CodeDom.Tests.CodeCollectionTestBase`2.AddRange_TestData() in System.CodeDom.Tests.dll:token 0x6000423+0x0
```

**Comment by VincentBu** [comment]
Also failed in `MonoTests`

Run: [runtime-coreclr libraries-jitstress 20210523.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1152028&view=ms.vss-test-web.build-test-results-tab&runId=34829674&resultId=105496&paneView=debug)

Failed tests:
```
MonoTests.System.Data.EnumerableRowCollectionTest.ThenBy
MonoTests.System.Data.EnumerableRowCollectionTest.QueryWhereSelectOrderBy
MonoTests.System.Data.EnumerableRowCollectionTest.ThenByDescending
MonoTests.System.Data.EnumerableRowCollectionTest.QueryWhereSelectOrderByDescending
MonoTests.System.Data.EnumerableRowCollectionTest.QueryWhereSelect
```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Data.DataRowExtensions.UnboxT`1.ReferenceField(Object value) in /_/src/libraries/System.Data.Common/src/System/Data/DataRowExtensions.cs:line 163
   at System.Data.DataRowExtensions.Field[T](DataRow row, String columnName) in /_/src/libraries/System.Data.Common/src/System/Data/DataRowExtensions.cs:line 25
   at MonoTests.System.Data.EnumerableRowCollectionTest.<>c.<ThenBy>b__5_3(DataRow line) in /_/src/libraries/System.Data.DataSetExtensions/tests/Mono/EnumerableRowCollectionTest.cs:line 161
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 138
   at MonoTests.System.Data.EnumerableRowCollectionTest.ThenBy() in /_/src/libraries/System.Data.DataSetExtensions/tests/Mono/EnumerableRowCollectionTest.cs:line 166
```

**Comment by danmoseley** [comment]
Good bug report but I'll dupe against https://github.com/dotnet/runtime/issues/53042 where there's discussion.
