### ISSUE TITLE
Again: HttpClient: The operation was canceled

### ISSUE THREAD

**Issue by DenisNP** [dotnet/runtime#53083]
Why is #33280 closed? I have exactly same issue with C#9.0 and `mcr.microsoft.com/dotnet/aspnet:5.0` image.

Request works fine on Windows, but from container on Ubuntu it fails with `The operation was canceled`:

```cs
var handler = new HttpClientHandler
{
    AutomaticDecompression = DecompressionMethods.GZip
                             | DecompressionMethods.Deflate
                             | DecompressionMethods.Brotli
};

var client = new HttpClient(handler)
{
    Timeout = TimeSpan.FromSeconds(10)
};
client.DefaultRequestHeaders.Add("Accept", "application/json");
client.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
client.DefaultRequestHeaders.Add("Accept-Encoding", "gzip, deflate, br");
client.DefaultRequestHeaders.Add("Connection", "keep-alive");

string dataStr = JsonConvert.SerializeObject(data);
string address = _endpoint + method;

HttpResponseMessage response;
try
{
    response = await client.PostAsync(
            address,
            new StringContent(dataStr, Encoding.UTF8, "application/json")
        ).ConfigureAwait(false);
}
catch (Exception e)
{
    Console.WriteLine(e);
    throw;
}

string stringResponse = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
return stringResponse;
```

**Comment by antonfirsov** [comment]
@DenisNP any chance you can also post minimalistic server code? It's part of the repro, and would make it much easier for us to act on the issue.

**Comment by DenisNP** [comment]
@antonfirsov solving this problem is extremely important to me, so I can do even better.

This is the **full minimal reproducing program** with dockerfile included: https://github.com/DenisNP/HttpClientBug
It has only one method, no external libraries. 

It works ok on my Windows 10 machine, console output also provided there.
But it fails with exception on my remote server under Ubuntu 18.04 with exception:

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
2021-05-21T17:07:08.660211370Z app[web.1]:  ---> System.TimeoutException: The operation was canceled.
2021-05-21T17:07:08.665905984Z app[web.1]:  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
2021-05-21T17:07:08.665927532Z app[web.1]:  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
2021-05-21T17:07:08.665931366Z app[web.1]:  ---> System.Net.Sockets.SocketException (125): Operation canceled
2021-05-21T17:07:08.665935070Z app[web.1]:    --- End of inner exception stack trace ---
2021-05-21T17:07:08.665938823Z app[web.1]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-05-21T17:07:08.665942184Z app[web.1]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-05-21T17:07:08.665949858Z app[web.1]:    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-05-21T17:07:08.665953888Z app[web.1]:    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2021-05-21T17:07:08.665957108Z app[web.1]:    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
2021-05-21T17:07:08.665993234Z app[web.1]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-21T17:07:08.666006885Z app[web.1]:    --- End of inner exception stack trace ---
2021-05-21T17:07:08.666062764Z app[web.1]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-21T17:07:08.666068483Z app[web.1]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-05-21T17:07:08.666088000Z app[web.1]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-21T17:07:08.666091993Z app[web.1]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-21T17:07:08.666168353Z app[web.1]:    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2021-05-21T17:07:08.666175588Z app[web.1]:    --- End of inner exception stack trace ---
2021-05-21T17:07:08.666178907Z app[web.1]:    --- End of inner exception stack trace ---
2021-05-21T17:07:08.666231490Z app[web.1]:    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2021-05-21T17:07:08.666237411Z app[web.1]:    at HttpClientBug.Program.DoRequest() in /app/HttpClientBug/Program.cs:line 40
```

`cURL` from this machine (even from inside container!) to the same Nespresso api works fine.

**Comment by ManickaP** [comment]
I just did a quick run of the repro, in and out of docker and it works for me, no exception on my side:
```
docker run 754b7c120b97
Request to https://www.nespresso.com/ru/ru/rest/V1/alice/customers/getProfile
OK got response, it works:
{"message":"The consumer isn't authorized to access %resources.","parameters":{"resources":"Nespresso_Alice::customer"}}
```

Note that I'm running Linux natively, so my docker set up is Linux on Linux.

**Comment by DenisNP** [comment]
So, it is not platform-dependent, not network-dependent (cURL works fine), then what is it?

@ManickaP what version of Linux do you have?

**Comment by ManickaP** [comment]
```
OS: Manjaro 21.0.5 Ornara
Kernel: x86_64 Linux 5.12.2-1-MANJARO
```

It might be specific for Linux image on Windows though. Do you have docker set up to use [WSL](https://docs.docker.com/docker-for-windows/wsl/)? If yes, does the problem reproduces in WSL?

**Comment by DenisNP** [comment]
I dont have Docker installed on Windows at all. I tried my program on Windows outside of container.  I'll check it on Linux outdise of container as well.

**Comment by MihaZupan** [comment]
FWIW I tried it on a Ubuntu VM in Azure and it works.

Can you do a packet capture?

**Comment by DenisNP** [comment]
How? I am not so familiar with Linux, `tcpdump host 184.30.19.22` shows nothing

**Comment by DenisNP** [comment]
Ok, just bought a completely new server in other country, and it works there. So, there is some issue with DigitalOcean network, I suppose.

Thank you all. I think this can be closed now.

**Comment by wfurt** [comment]
Is there chance that your old setup resolved to IPv6? .NET will prefer IPv6 if available and that can lead to issues lie this when there is something wrong with the transport.  @DenisNP

The "bad chum" is pretty normal for cases when it is computed by your NIC. When supported, OS is smart enough to not calculate it and defer to HW but that is after tcpdump gets the frames.

**Comment by DenisNP** [comment]
@wfurt no, my setup uses only IPv4 on all machines. 
The main mystery for me is why `cURL` works from this server but `HttpClient` doesn't.
