### ISSUE TITLE
[HTTP/3] ReservedFrameType_Throws test fails

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#53090]
## System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.ReservedFrameType_Throws
Intermittently fails with:
```
Assert.Throws() Failure\nExpected: typeof(System.Net.Quic.QuicConnectionAbortedException)\nActual:   typeof(System.Exception): unable to read request headers; unexpected end of stream.\n---- System.Exception : unable to read request headers; unexpected end of stream.
   at System.Net.Test.Common.Http3LoopbackStream.ReadRequestDataAsync(Boolean readBody) in /home/manicka/Repositories/runtime.2/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 179
   at System.Net.Test.Common.Http3LoopbackStream.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in /home/manicka/Repositories/runtime.2/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 48
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass5_1.<<ReservedFrameType_Throws>b__2>d.MoveNext() in /home/manicka/Repositories/runtime.2/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 136
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Test.Common.Http3LoopbackStream.ReadRequestDataAsync(Boolean readBody) in /home/manicka/Repositories/runtime.2/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 179
   at System.Net.Test.Common.Http3LoopbackStream.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in /home/manicka/Repositories/runtime.2/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 48
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass5_1.<<ReservedFrameType_Throws>b__2>d.MoveNext() in /home/manicka/Repositories/runtime.2/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 136
--- End of stack trace from previous location ---
```

**Comment by CarnaViire** [comment]
I've seen that on 8/24 on that day's runtime main. I will re-check later
```
     System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.ReservedFrameType_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicConnectionAbortedException)
      Actual:   typeof(System.Net.Quic.QuicException): Could not send data to peer. Error Code: INVALID_STATE
      ---- System.Net.Quic.QuicException : Could not send data to peer. Error Code: INVALID_STATE
      Stack Trace:
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\Internal\QuicExceptionHelpers.cs(14,0): at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\MsQuicStream.cs(1209,0): at System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(ReadOnlyMemory`1 buffer, QUIC_SEND_FLAGS flags)
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\MsQuicStream.cs(296,0): at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlyMemory`1 buffer, Boolean endStream, CancellationToken cancellationToken)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(162,0): at System.Net.Test.Common.Http3LoopbackStream.SendFrameHeaderAsync(Int64 frameType, Int32 payloadLength)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(167,0): at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(123,0): at System.Net.Test.Common.Http3LoopbackStream.SendHeadersFrameAsync(HttpStatusCode statusCode, IEnumerable`1 headers, Boolean qpackEncodeStatus)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(264,0): at System.Net.Test.Common.Http3LoopbackStream.SendResponseHeadersAsync(HttpStatusCode statusCode, IEnumerable`1 headers)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(247,0): at System.Net.Test.Common.Http3LoopbackStream.SendResponseAsync(HttpStatusCode statusCode, IList`1 headers, String content, Boolean isFinal)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(53,0): at System.Net.Test.Common.Http3LoopbackStream.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content)
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Http3.cs(299,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass7_1.<<ReservedFrameType_Throws>b__2>d.MoveNext()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\Internal\QuicExceptionHelpers.cs(14,0): at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\MsQuicStream.cs(1209,0): at System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(ReadOnlyMemory`1 buffer, QUIC_SEND_FLAGS flags)
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\MsQuicStream.cs(296,0): at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlyMemory`1 buffer, Boolean endStream, CancellationToken cancellationToken)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(162,0): at System.Net.Test.Common.Http3LoopbackStream.SendFrameHeaderAsync(Int64 frameType, Int32 payloadLength)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(167,0): at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(123,0): at System.Net.Test.Common.Http3LoopbackStream.SendHeadersFrameAsync(HttpStatusCode statusCode, IEnumerable`1 headers, Boolean qpackEncodeStatus)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(264,0): at System.Net.Test.Common.Http3LoopbackStream.SendResponseHeadersAsync(HttpStatusCode statusCode, IEnumerable`1 headers)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(247,0): at System.Net.Test.Common.Http3LoopbackStream.SendResponseAsync(HttpStatusCode statusCode, IList`1 headers, String content, Boolean isFinal)
        C:\Users\knatalia\dev\git\runtime\src\libraries\Common\tests\System\Net\Http\Http3LoopbackStream.cs(53,0): at System.Net.Test.Common.Http3LoopbackStream.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content)
        C:\Users\knatalia\dev\git\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Http3.cs(299,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass7_1.<<ReservedFrameType_Throws>b__2>d.MoveNext()
        --- End of stack trace from previous location ---
```

**Comment by wfurt** [comment]
OK. I was expecting we would no longer see this after #57541 as that should  bring https://github.com/microsoft/msquic/pull/1875
cc: @ThadHouse @nibanks

**Comment by ThadHouse** [comment]
You can still get invalid state if you have closed the connection locally. Are you sure that hasn't happened?

**Comment by wfurt** [comment]
I would expect not but @CarnaViire to confirm. `WriteAsync` should not try to call msquic if locally closed.

**Comment by CarnaViire** [comment]
I was looking at https://github.com/microsoft/msquic/pull/1875 and it seems to fix that only for StreamStart and StreamOpen, but not for StreamSend. Is it possible INVALID_STATE is still used for StreamSend? @nibanks @thhous-msft

**Comment by thhous-msft** [comment]
StreamSend wasn't part of the changes done before, as the bug we got seemed to only apply to Start. I'll look into StreamSend.

**Comment by nibanks** [comment]
@CarnaViire would you mind opening a new MsQuic Issue to track `StreamSend` and we'll prioritize accordingly. We've still got a number of v2 things that need to get fixed ASAP. This can be fixed in a new minor version later.

**Comment by CarnaViire** [comment]
Judging from the discussion here https://github.com/dotnet/runtime/issues/55485#issuecomment-1042320209 is it correct that if SEND_COMPLETE contains Canceled=true, that could only mean that the stream is being closed (because of connection shutdown or other reasons)? Meaning, can we skip that event and wait for the following STREAM_SHUTDOWN* event? @nibanks @thhous-msft

**Comment by nibanks** [comment]
A canceled send can happen for one of the following reasons:

1. The peer aborted their receive.
2. The local app aborted their send.
3. The connection was shutdown (by either side).
