### ISSUE TITLE
Test failure JIT/Stress/ABI/stubs_do/stubs_do.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53163]
Run: [runtime-coreclr r2r-extra 20210522.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1151933&view=ms.vss-test-web.build-test-results-tab&runId=34828162&resultId=100389&paneView=debug)

Failed test:
```
R2R Linux arm64 Checked forcerelocs @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

- JIT/Stress/ABI/stubs_do/stubs_do.sh

```
**Error message:**
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.NullReferenceException: Object reference not set to an instance of an object.
at ABIStress_InstantiatingStub_Caller91StaticValueTypeGenericOverReferenceTypeNotGeneric_GenericTarget.Method(Single ) in RefEmit_InMemoryManifestModule:token 0x60005ba+0x0
at ABIStress_InstantiatingStub_Caller91StaticValueTypeGenericOverReferenceTypeNotGeneric(Single )
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.Emit.DynamicMethod.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6005164+0x83 at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x6004c42+0x0 at ABIStress.Program.InvokeCallerCallee(DynamicMethod caller, List1 callerParameters, DynamicMethod callee, List`1 passedArgs, Random rand) in stubs_do.dll:token 0x600004c+0x9b
at ABIStress.Program.DoStubCall(Int32 callerIndex, Boolean staticMethod, Boolean onValueType, GenericShape typeGenericShape, GenericShape methodGenericShape) in stubs_do.dll:token 0x6000056+0x6d4
at ABIStress.Program.DoCall(Int32 index) in stubs_do.dll:token 0x6000045+0xbc
at ABIStress.Program.Main(String[] args) in stubs_do.dll:token 0x6000044+0x236
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f787bf7f8)
/root/helix/work/workitem/JIT/Stress/ABI/stubs_do/stubs_do.sh: line 396:   181 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/Stress/Reports/JIT.Stress/ABI/stubs_do/stubs_do.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image stubs_do.dll generated successfully.

in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun stubs_do.dll '--instantiatingstubs' '--unboxingstubs' '--sharedgenericunboxingstubs' '--num-calls' '100' '--max-params' '5' '--no-ctrlc-summary'
Stressing instantiatingstubs
Stressing unboxingstubs
Stressing sharedgenericunboxingstubs
OSVersion: Unix 4.9.140.0
OSArchitecture: Arm64
ProcessArchitecture: Arm64
Selecting arm64 ABI.
50 callers done
Gathering state for process 181 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.181.dmp
Written 76996608 bytes (18798 pages) to core file
Dump successfully written
in ReleaseLock
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/JIT/Stress/ABI/stubs_do/stubs_do.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Stress._ABI_stubs_do_stubs_do_._ABI_stubs_do_stubs_do_sh()
```

**Comment by VincentBu** [comment]
Historical failures of this test:

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-05-24T04:30:12.495Z | osx.1100.arm64.open | arm64 | [runtime-coreclr r2r-extra   Checked-forcerelocs](https://dev.azure.com/dnceng/public/_build/results?buildId=1152461&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34839912&amp;resultId=104502&amp;paneView=debug)
2021-05-24T04:18:39.942Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr r2r-extra   Checked-forcerelocs](https://dev.azure.com/dnceng/public/_build/results?buildId=1152461&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34839730&amp;resultId=100743&amp;paneView=debug)
2021-05-23T04:40:09.437Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr r2r-extra   Checked-forcerelocs](https://dev.azure.com/dnceng/public/_build/results?buildId=1151933&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34828162&amp;resultId=100389&amp;paneView=debug)
2021-05-23T04:26:36.081Z | osx.1100.arm64.open | arm64 | [runtime-coreclr r2r-extra   Checked-forcerelocs](https://dev.azure.com/dnceng/public/_build/results?buildId=1151933&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34827838&amp;resultId=102965&amp;paneView=debug)

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr r2r-extra 20210530.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1163835&view=ms.vss-test-web.build-test-results-tab&runId=35089678&resultId=100533&paneView=debug)

Failed test:
```
R2R Linux arm64 Checked forcerelocs @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

- JIT/Stress/ABI/stubs_do/stubs_do.sh

```
**Error message:**
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.NullReferenceException: Object reference not set to an instance of an object.
at ABIStress_InstantiatingStub_Caller91StaticValueTypeGenericOverReferenceTypeNotGeneric_GenericTarget.Method(Single ) in RefEmit_InMemoryManifestModule:token 0x60005ba+0x0
at ABIStress_InstantiatingStub_Caller91StaticValueTypeGenericOverReferenceTypeNotGeneric(Single )
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Span1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.Emit.DynamicMethod.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6005185+0x83 at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Private.CoreLib.dll:token 0x6004c63+0x0 at ABIStress.Program.InvokeCallerCallee(DynamicMethod caller, List1 callerParameters, DynamicMethod callee, List`1 passedArgs, Random rand) in stubs_do.dll:token 0x600004c+0x9b
at ABIStress.Program.DoStubCall(Int32 callerIndex, Boolean staticMethod, Boolean onValueType, GenericShape typeGenericShape, GenericShape methodGenericShape) in stubs_do.dll:token 0x6000056+0x6d4
at ABIStress.Program.DoCall(Int32 index) in stubs_do.dll:token 0x6000045+0xbc
at ABIStress.Program.Main(String[] args) in stubs_do.dll:token 0x6000044+0x236
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7d4a2a14)
/root/helix/work/workitem/JIT/Stress/ABI/stubs_do/stubs_do.sh: line 396:   170 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/Stress/Reports/JIT.Stress/ABI/stubs_do/stubs_do.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.

Native image stubs_do.dll generated successfully.

in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun stubs_do.dll '--instantiatingstubs' '--unboxingstubs' '--sharedgenericunboxingstubs' '--num-calls' '100' '--max-params' '5' '--no-ctrlc-summary'
Stressing instantiatingstubs
Stressing unboxingstubs
Stressing sharedgenericunboxingstubs
OSVersion: Unix 4.9.140.0
OSArchitecture: Arm64
ProcessArchitecture: Arm64
Selecting arm64 ABI.
50 callers done
Gathering state for process 170 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.170.dmp
Written 85610496 bytes (20901 pages) to core file
Dump successfully written
in ReleaseLock
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/JIT/Stress/ABI/stubs_do/stubs_do.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Stress._ABI_stubs_do_stubs_do_._ABI_stubs_do_stubs_do_sh()
```

**Historical failures of this test has updated in this [comment](https://github.com/dotnet/runtime/issues/53163#issuecomment-846822881).**

**Comment by mangod9** [comment]
Closing the r2r specific failures since crossgen has been replaced with crossgen2. Please reopen a separate issue if these tests continue to fail.
