### ISSUE TITLE
Test failure MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53261]
Run: [runtime 20210525.112](https://dev.azure.com/dnceng/public/_build/results?buildId=1156287&view=ms.vss-test-web.build-test-results-tab&runId=34923730&resultId=113491&paneView=debug)

Failed test:
```
net48-windows-Release-x86-Windows.10.Amd64.Client19H1.Open

- MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters

```

**Error message:**
```
System.InvalidOperationException : Category does not exist.


Stack trace
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
   at System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(String categoryName, String machineName)
   at MonoTests.System.Runtime.Caching.CountersTest.<PollCounters>d__1.MoveNext() in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MonoTests.System.Runtime.Caching.CountersTest.<Basic_Counters>d__0.MoveNext() in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by StephenMolloy** [comment]
I believe this was the result of the more generic PerfCounter issue that was fixed by #73170.
