### ISSUE TITLE
DllImport doesn't work when running from a network share

### ISSUE THREAD

**Issue by Doomblaster** [dotnet/runtime#53352]
Originally posted https://github.com/dotnet/SqlClient/issues/1086

### Description

So as title says, I've published a standalone dotnet core (3.1.15) console application and put it on a network share and it's utilizing Microsoft.Data.SqlClient which utilizes the unmanaged dll Microsoft.Data.SqlClient.SNI.dll. I've also tried upgrading to net5.0. Basically it fails when people are trying to run it directly from that network location. It fails with the following:
`System.DllNotFoundException: Dll was not found.
   at Microsoft.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at Microsoft.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative()
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource``1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource``1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource``1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource``1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)`

If they copy it to their local machine, it works without problems.

Just to test, I added a DllImport in my own code and called the same method to in a way force load the unmanaged dll, which got me one step further (and possibly 2 back), because then it started failing with:

`System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
---> System.IO.FileLoadException: 
File name: 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
--- End of inner exception stack trace ---
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()`

Obviously it's related to being on a windows share, but I'm not sure if this is specific to Microsoft.Data.SqlClient or dotnet core itself, and if it's possible at all to actually fix it. Experienced the same issue with System.Data.SqlClient which tries to do some stuff with sni.dll.

Expectation:
Being able to run application from a network share

### Configuration

Using dotnet core 3.1.15 on Windows 10

### Other information
Double clicking exe file fails
When running exe from mapped folder in cmd it fails
When running exe from mapped folder in powershell it fails
When running exe from UNC path in powershell it fails

downloaded dotnet runtime 3.1.15 zip and unpacked it to C:\dotnet, then started doing various "C:\dotnet\dotnet.exe program.dll"

When running with dotnet runtime manually from mapped folder in cmd it fails
When running with dotnet runtime manually from mapped folder in powershell it fails
When running with dotnet runtime manually from UNC path in powershell it works

someone please explain!

**Comment by Doomblaster** [comment]
@David-Engel, you are probably right that it is due to some corporate policy and so on, but still I'm able to circumvent it by executing this via powershell and using dotnet.exe instead of using the compiled exe. To me that seems like it's either some security hole or the DllImport has some issues.
Either way, you have any idea how that trust could be changed?

**Comment by David-Engel** [comment]
> Either way, you have any idea how that trust could be changed?

I don't have any additional ideas beyond what you've already tried (mapping the UNC to a driver letter). I'd have to try things from a [search](https://www.google.com/search?q=windows+trust+unc+path).

> Edit: When enabling managed networking on Windows it just starts screaming about missing System.Configuration.ConfigurationManager v4.0.3.0, which I guess is a Microsoft.Data.SqlClient issue, but solution doesn't work either way :/ System.Configuration.ConfigurationManager is present, although it's version 4.7

Adding a dependency on System.Configuration.ConfigurationManager to your application should resolve it. It's strange that it isn't. This should also be addressed in the M.D.SqlClient 3.0.0 GA release planned for Monday.
https://github.com/dotnet/SqlClient/milestone/24?closed=1

**Comment by cheenamalhotra** [comment]
[Microsoft.Data.SqlClient v3.0.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0) includes dependency on ConfigurationManagerfor .NET Standard, closing issue.
