### ISSUE TITLE
Five CodeDom tests failing when the source assembly compiles against .NETCoreApp

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53522]
Five CodeDom tests are failing when testing against the .NETCoreApp variant of System.CodeDom (and not against the .NETStandard one).

```
[xUnit.net 00:00:04.72]     System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Arrays_WithinArrays_Empty_NonPrimitiveTypes [FAIL]
  Failed System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Arrays_WithinArrays_Empty_NonPrimitiveTypes [41 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 112)
Expected: ···er = New Integer()() {New Integer() {3, 4}, New Integer((1) -···
Actual:   ···er = New Integer()()() {New Integer()() {3, 4}, New Integer((···
                                 ↑ (pos 112)
  Stack Trace:
     at System.CodeDom.Compiler.Tests.CodeGenerationTests.AssertEqual(CodeObject c, String expected) in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\CodeGenerationTests.cs:line 113
   at System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Arrays_WithinArrays_Empty_NonPrimitiveTypes() in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\VBCodeGenerationTests.cs:line 570
[xUnit.net 00:00:05.02]     System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Indexers [FAIL]
  Failed System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Indexers [4 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 78)
Expected: ···nteger = New Integer() {0, 0, 0, 0, 0, 0, 0} Public Overloads···
Actual:   ···nteger = New Integer {0, 0, 0, 0, 0, 0, 0} Public Overloads D···
                                 ↑ (pos 78)
  Stack Trace:
     at System.CodeDom.Compiler.Tests.CodeGenerationTests.AssertEqual(CodeObject c, String expected) in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\CodeGenerationTests.cs:line 113
   at System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Indexers() in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\VBCodeGenerationTests.cs:line 2162
[xUnit.net 00:00:05.14]     System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Arrays_SingleDimensional_PrimitiveTypes [FAIL]
  Failed System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Arrays_SingleDimensional_PrimitiveTypes [4 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 183)
Expected: ··· Short = New Short() {1, 4, 9} array1 = New Integer((arraySiz···
Actual:   ··· Short = New Short()() {1, 4, 9} array1 = New Integer((arrayS···
                                 ↑ (pos 183)
  Stack Trace:
     at System.CodeDom.Compiler.Tests.CodeGenerationTests.AssertEqual(CodeObject c, String expected) in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\CodeGenerationTests.cs:line 113
   at System.CodeDom.Compiler.Tests.VBCodeGenerationTests.Arrays_SingleDimensional_PrimitiveTypes() in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\VBCodeGenerationTests.cs:line 519
[xUnit.net 00:00:05.41]     System.CodeDom.Compiler.Tests.VBCodeGenerationTests.GenericTypesAndConstraints [FAIL]
  Failed System.CodeDom.Compiler.Tests.VBCodeGenerationTests.GenericTypesAndConstraints [4 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 661)
Expected: ···c.List(Of String))() {Nothing} End Sub End Class End Namespac···
Actual:   ···c.List(Of String))()() {Nothing} End Sub End Class End Namesp···
                                 ↑ (pos 661)
  Stack Trace:
     at System.CodeDom.Compiler.Tests.CodeGenerationTests.AssertEqual(CodeObject c, String expected) in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\CodeGenerationTests.cs:line 113
   at System.CodeDom.Compiler.Tests.VBCodeGenerationTests.GenericTypesAndConstraints() in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\VBCodeGenerationTests.cs:line 3253
[xUnit.net 00:00:05.65]     System.CodeDom.Compiler.Tests.VBCodeGenerationTests.ProviderSupports [FAIL]
  Failed System.CodeDom.Compiler.Tests.VBCodeGenerationTests.ProviderSupports [23 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 714)
Expected: ···er = New Integer()() {New Integer() {3, 4}, New Integer() {1}···
Actual:   ···er = New Integer()()() {New Integer()() {3, 4}, New Integer()···
                                 ↑ (pos 714)
  Stack Trace:
     at System.CodeDom.Compiler.Tests.CodeGenerationTests.AssertEqual(CodeObject c, String expected) in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\CodeGenerationTests.cs:line 113
   at System.CodeDom.Compiler.Tests.VBCodeGenerationTests.ProviderSupports() in C:\git\runtime2\src\libraries\System.CodeDom\tests\System\CodeDom\Compiler\VBCodeGenerationTests.cs:line 2924
Results File: C:\git\runtime2\artifacts\bin\System.CodeDom.Tests\net6.0-Debug\TestResults\vihofer_DESKTOP-803H9R0_2021-06-01_13_44_36.trx
Html test results file : C:\git\runtime2\artifacts\bin\System.CodeDom.Tests\net6.0-Debug\TestResults\TestResult_vihofer_DESKTOP-803H9R0_20210601_134442.html

Failed!  - Failed:     5, Passed:  5801, Skipped:     0, Total:  5806, Duration: 4 s - System.CodeDom.Tests.dll (net6.0)
```

**Comment by krwq** [comment]
looking at just the output looks like some sort of regression but looking at the changes to the src of CodeDom I do not see anything obvious which could have caused this. @buyaa-n @joperezr this is something we should definitely look into in 6.0. It might also be related to https://github.com/dotnet/runtime/pull/53524 but still we should take a look at this.

**Comment by ericstj** [comment]
I believe @ViktorHofer is introducing this failure in https://github.com/dotnet/runtime/pull/53023 by adding a `NETCoreApp` configuration to the project.  Random thought: is there an ifdef that's broken by this that's causing this to break?

**Comment by buyaa-n** [comment]
> Random thought: is there an ifdef that's broken by this that's causing this to break?

You are right, looks like forgot `!` operator in the #ifdef

**Comment by ViktorHofer** [comment]
LOL - I failed converting an IndexOf expression into a Contains one without loosing the inversion... Sorry for that and thanks @buyaa-n for spotting the mistake.
