### ISSUE TITLE
[wasm] NRE in `System.Runtime.InteropServices.JavaScript.Runtime.SetupJSContinuation`, for `System.Xml.Linq.xNodeBuilder.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#53614]
PR: https://github.com/dotnet/runtime/pull/53557
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1166367&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4
Test log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53557-merge-f508128941754676b8/System.Xml.Linq.xNodeBuilder.Tests/console.14abc845.log?sv=2019-07-07&se=2021-06-21T23%3A56%3A15Z&sr=c&sp=rl&sig=LF0p6D8awZ1HOuwt79yvT8cmtp4%2FQhoKfPQ22FLswvI%3D

```
[00:08:46] warn: /__w/1/s/src/mono/mono/utils/memfuncs.c:360 <disabled>
[00:08:46] info: {"method":"console.error","payload":{},"arguments":[{}]}
[00:08:46] fail: Error: System.NullReferenceException: Object reference not set to an instance of an object.
                    at System.Runtime.InteropServices.JavaScript.Runtime.<>c__DisplayClass27_0.<SetupJSContinuation>g__Complete|0()
                    at System.Runtime.InteropServices.JavaScript.Runtime.SetupJSContinuation(Task task, JSObject continuationObj)
                     at Object._convert_exception_for_method_call (http://127.0.0.1:41301/dotnet.js:1:196628)
                     at Object._handle_exception_for_call (http://127.0.0.1:41301/dotnet.js:1:198597)
                     at Object._handle_exception_and_produce_result_for_call (http://127.0.0.1:41301/dotnet.js:1:198918)
                     at Object._call_method_with_converted_args (http://127.0.0.1:41301/dotnet.js:1:199992)
                     at Object.call_method (http://127.0.0.1:41301/dotnet.js:1:198387)
                     at Object._unbox_task_rooted (http://127.0.0.1:41301/dotnet.js:1:177443)
                     at Object._unbox_mono_obj_rooted_with_known_nonprimitive_type (http://127.0.0.1:41301/dotnet.js:1:178374)
                     at Object._unbox_mono_obj_root (http://127.0.0.1:41301/dotnet.js:1:179611)
                     at Object._handle_exception_and_produce_result_for_call (http://127.0.0.1:41301/dotnet.js:1:199038)
                     at Object._call_method_with_converted_args (http://127.0.0.1:41301/dotnet.js:1:199992)
```

The error went away on a rebuild though. Opening this issue, in case this is seen again.

cc @kg

**Comment by ViktorHofer** [comment]
Happened again here: https://dev.azure.com/dnceng/public/_build/results?buildId=1167323&view=ms.vss-test-web.build-test-results-tab&runId=35185594&resultId=169030&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by radical** [comment]
Another instance - https://github.com/dotnet/runtime/pull/53656/checks?check_run_id=2751110132
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53656-merge-973bd3fc91754808a6/System.Xml.Linq.xNodeBuilder.Tests/console.ecac7674.log?sv=2019-07-07&se=2021-06-25T01%3A39%3A59Z&sr=c&sp=rl&sig=Qs8uLN8oIHhmPSwvppvb9bUeckOhQ9nA2hICx2h390I%3D

**Comment by kg** [comment]
Does this seem like a regression? Or just an existing bug we weren't noticing?

**Comment by lewing** [comment]
My first check around continuations would be GC.

**Comment by kg** [comment]
Yeah, it's quite likely this is a GC issue, but also the arguments to this function are marked as non-nullable when they're nullable, so it's possible a null is making its way in from the JS side. The code doesn't handle that.

**Comment by kg** [comment]
I spent a while trying to reproduce this but can't get it to fail, it must rely on something about the CI hardware. I'll have to just audit and rework the code.

**Comment by radical** [comment]
Happened again on `main` rolling build - https://dev.azure.com/dnceng/public/_build/results?buildId=1204077&view=logs&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4

```
[15:43:33] info: Initializing.....
[15:43:34] info: {"method":"console.error","payload":{},"arguments":[{}]}
[15:43:34] fail: Error: System.NullReferenceException: Object reference not set to an instance of an object.
                    at System.Runtime.InteropServices.JavaScript.Runtime.<>c__DisplayClass27_0.<SetupJSContinuation>g__Complete|0()
                    at System.Runtime.InteropServices.JavaScript.Runtime.SetupJSContinuation(Task task, JSObject continuationObj)
                     at Object._convert_exception_for_method_call (http://127.0.0.1:36893/dotnet.js:1:171681)
                     at Object._handle_exception_for_call (http://127.0.0.1:36893/dotnet.js:1:173650)
                     at Object._handle_exception_and_produce_result_for_call (http://127.0.0.1:36893/dotnet.js:1:173971)
                     at Object._call_method_with_converted_args (http://127.0.0.1:36893/dotnet.js:1:175045)
                     at Object.call_method (http://127.0.0.1:36893/dotnet.js:1:173440)
                     at Object._unbox_task_rooted (http://127.0.0.1:36893/dotnet.js:1:152548)
                     at Object._unbox_mono_obj_rooted_with_known_nonprimitive_type (http://127.0.0.1:36893/dotnet.js:1:153434)
                     at Object._unbox_mono_obj_root (http://127.0.0.1:36893/dotnet.js:1:154670)
                     at Object._handle_exception_and_produce_result_for_call (http://127.0.0.1:36893/dotnet.js:1:174091)
                     at Object._call_method_with_converted_args (http://127.0.0.1:36893/dotnet.js:1:175045)
```

**Comment by lewing** [comment]
> [15:43:34] info: {"method":"console.error","payload":{},"arguments":[{}]}
 
🤕

**Comment by lewing** [comment]
Happened here too https://github.com/dotnet/runtime/pull/54186/
