### ISSUE TITLE
FileSystemWatcher crashes application with 'Illegal characters in path.'

### ISSUE THREAD

**Issue by milos12345** [dotnet/runtime#53616]
### Description

Even thought everything is wrapped in try/catch an invalid character in path will bring down the application because of it cannot be caught in FileSystemWatcher.
There should be a way to instantiate FileSystemWatcher with ignore errors parameter

### Configuration

.NET 4.8, x64, WPF

### Other information
```
FATAL UNHANDLED EXCEPTION from AppDomain.CurrentDomain.UnhandledException
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.FileSystemWatcher.MatchPattern(String relativePath)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

```
In my case it is a file manager and sooner or later user will encounter a file with invalid characters. After getting a ton of crash reports when watching the entire disk, I've narrowed it down to reinitialize FSW for each opened folder but I still get crash reports about this.

**Comment by adamsitnik** [comment]
@milos12345 It's a Full Framework bug that has been fixed in .NET Core. Since it's not a security issue, I am going to close the issue.
