### ISSUE TITLE
[Android][AOT] System.Security.Cryptography.Xml.Tests: Lots of NRE and CryptographicException

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#53682]
An example of CryptographicException:
```
<test name="System.Security.Cryptography.Xml.Tests.SigningAndVerifying.SignedXmlHasVerifiableSignature" type="System.Security.Cryptography.Xml.Tests.SigningAndVerifying" method="SignedXmlHasVerifiableSignature" time="0.0034534" result="Fail">
    <failure exception-type="System.Security.Cryptography.CryptographicException">
        <message><![CDATA[System.Security.Cryptography.CryptographicException : Could not create hash algorithm object.]]></message>
        <stack-trace><![CDATA[   at System.Security.Cryptography.Xml.Reference.CalculateHashValue(XmlDocument , CanonicalXmlNodeList ) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Reference.cs:line 472
        at System.Security.Cryptography.Xml.Reference.UpdateHashValue(XmlDocument , CanonicalXmlNodeList ) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Reference.cs:line 328
        at System.Security.Cryptography.Xml.SignedXml.BuildDigestedReferences() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 900
        at System.Security.Cryptography.Xml.SignedXml.ComputeSignature() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 377
        at System.Security.Cryptography.Xml.Tests.SigningAndVerifying.SignXml(XmlDocument doc, RSA key) in /_/src/libraries/System.Security.Cryptography.Xml/tests/Samples/SigningVerifying.cs:line 38
        at System.Security.Cryptography.Xml.Tests.SigningAndVerifying.SignedXmlHasVerifiableSignature() in /_/src/libraries/System.Security.Cryptography.Xml/tests/Samples/SigningVerifying.cs:line 63
        at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo ) in System.Private.CoreLib.dll:token 0x600226f+0x6a]]></stack-trace>
    </failure>
</test>
```

An example of NRE:
```
<test name="System.Security.Cryptography.Xml.Tests.Signature_ArbitraryElements.ExtraAttributes_Lang" type="System.Security.Cryptography.Xml.Tests.Signature_ArbitraryElements" method="ExtraAttributes_Lang" time="0.0066722" result="Fail">
    <failure exception-type="System.NullReferenceException">
        <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object]]></message>
        <stack-trace>
            <![CDATA[   at System.Security.Cryptography.Xml.RSAPKCS1SignatureDescription.CreateDeformatter(AsymmetricAlgorithm ) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/RSAPKCS1SignatureDescription.cs:line 19
            at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm ) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 1016
            at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm ) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 283
            at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& ) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 267
            at System.Security.Cryptography.Xml.SignedXml.CheckSignature() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs:line 246
            at System.Security.Cryptography.Xml.Tests.Helpers.VerifyCryptoExceptionOnLoad(String xml, Boolean loadXmlThrows) in /_/src/libraries/System.Security.Cryptography.Xml/tests/SignedXml_Helpers.cs:line 28
            at System.Security.Cryptography.Xml.Tests.Signature_ArbitraryElements.ExtraAttributes_Lang() in /_/src/libraries/System.Security.Cryptography.Xml/tests/Signature_ArbitraryElements.cs:line 70
            at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo ) in System.Private.CoreLib.dll:token 0x600226f+0x6a]]>
    </stack-trace>
    </failure>
</test>
```

[testResults - System.Security.Cryptography.Xml.txt](https://github.com/dotnet/runtime/files/6592742/testResults.-.System.Security.Cryptography.Xml.txt)

@steveisok

**Comment by bartonjs** [comment]
@jkoritzinsky Is this something you could look at?

**Comment by jkoritzinsky** [comment]
I don't have my Android setup ready any more, so I'm not sure I'll be able to get to this in a timely manner.

**Comment by steveisok** [comment]
I'll assign someone from my team to take a look.

**Comment by steveisok** [comment]
Since this happens under fullaot, the priority is pretty low.
