### ISSUE TITLE
[Android][AOT] System.Reflection.Tests.MetadataLoadContextTests.RelocatableAssembly test fails with System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#53680]
```
<test name="System.Reflection.Tests.MetadataLoadContextTests.RelocatableAssembly" type="System.Reflection.Tests.MetadataLoadContextTests" method="RelocatableAssembly" time="0.008538" result="Fail">
    <failure exception-type="System.IO.FileNotFoundException">
        <message><![CDATA[System.IO.FileNotFoundException : Could not find file '/data/user/0/net.dot.System.Reflection.MetadataLoadContext.Tests/files/mscorlib.dll'.]]></message>
        <stack-trace><![CDATA[   at Interop.ThrowExceptionForIoErrno(ErrorInfo , String , Boolean , Func`2 ) in System.Private.CoreLib.dll:token 0x6000002+0x14
            at Interop.CheckIo(Error , String , Boolean , Func`2 ) in System.Private.CoreLib.dll:token 0x6000003+0x9
            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , OpenFlags , Int32 ) in System.Private.CoreLib.dll:token 0x6000082+0x52
            at System.IO.Strategies.FileStreamHelpers.OpenHandle(String , FileMode , FileAccess , FileShare , FileOptions , Int64 ) in System.Private.CoreLib.dll:token 0x6002b67+0xb
            at System.IO.Strategies.Net5CompatFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 ) in System.Private.CoreLib.dll:token 0x6002b72+0x3c
            at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 ) in System.Private.CoreLib.dll:token 0x6002b66+0x0
            at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 ) in System.Private.CoreLib.dll:token 0x6002b61+0x0
            at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 ) in System.Private.CoreLib.dll:token 0x600299d+0x123
            at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions ) in System.Private.CoreLib.dll:token 0x600299c+0x0
            at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean ) in System.Private.CoreLib.dll:token 0x600299b+0x0
            at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare ) in System.Private.CoreLib.dll:token 0x6002999+0x0
            at System.IO.File.OpenRead(String ) in System.Private.CoreLib.dll:token 0x6002980+0x0
            at System.Reflection.MetadataLoadContext.LoadFromAssemblyPath(String ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/MetadataLoadContext.Apis.cs:line 136
            at System.Reflection.PathAssemblyResolver.Resolve(MetadataLoadContext , AssemblyName ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/PathAssemblyResolver.cs:line 66
            at System.Reflection.MetadataLoadContext.TryFindAssemblyByCallingResolveHandler(RoAssemblyName ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/MetadataLoadContext.Resolving.cs:line 61
            at System.Reflection.MetadataLoadContext.ResolveToAssemblyOrExceptionAssembly(RoAssemblyName ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/MetadataLoadContext.Resolving.cs:line 53
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.<>c.<.cctor>b__15_3(EntityHandle , EcmaModule ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 177
            at System.Reflection.TypeLoading.Ecma.MetadataTable`2[[System.Reflection.TypeLoading.RoAssembly, System.Reflection.MetadataLoadContext, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[System.Reflection.TypeLoading.Ecma.EcmaModule, System.Reflection.MetadataLoadContext, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].GetOrAdd(EntityHandle , EcmaModule , Func`3 ) in System.Reflection.MetadataLoadContext.dll:token 0x6000640+0x2c
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveToAssemblyOrExceptionAssembly(AssemblyReferenceHandle , EcmaModule ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 170
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.TryResolveAssembly(AssemblyReferenceHandle , EcmaModule , Exception& ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 159
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveAssembly(AssemblyReferenceHandle , EcmaModule ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 150
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle , EcmaModule ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 78
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.<>c.<.cctor>b__15_1(EntityHandle , EcmaModule ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 48
            at System.Reflection.TypeLoading.Ecma.MetadataTable`2[[System.Reflection.TypeLoading.RoDefinitionType, System.Reflection.MetadataLoadContext, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[System.Reflection.TypeLoading.Ecma.EcmaModule, System.Reflection.MetadataLoadContext, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].GetOrAdd(EntityHandle , EcmaModule , Func`3 ) in System.Reflection.MetadataLoadContext.dll:token 0x6000640+0x2c
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeRef(TypeReferenceHandle , EcmaModule ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 44
            at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeDefRefOrSpec(EntityHandle , EcmaModule , TypeContext& ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaResolver.cs:line 22
            at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.SpecializeBaseType(RoType[] ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/Ecma/EcmaDefinitionType.cs:line 57
            at System.Reflection.TypeLoading.RoDefinitionType.ComputeBaseTypeWithoutDesktopQuirk() in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoDefinitionType.cs:line 80
            at System.Reflection.TypeLoading.RoType.ComputeBaseType() in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoType.cs:line 121
            at System.Reflection.TypeLoading.RoType.GetRoBaseType() in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoType.cs:line 118
            at System.Reflection.TypeLoading.RoType.get_BaseType() in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoType.cs:line 117
            at System.Reflection.Runtime.BindingFlagSupport.QueriedMemberList`1[[System.Reflection.FieldInfo, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Create(RoType , String , Boolean , Boolean ) in System.Reflection.MetadataLoadContext.dll:token 0x6000776+0xf2
            at System.Reflection.TypeLoading.RoType.TypeComponentsCache.GetQueriedMembers[FieldInfo](Boolean ) in System.Reflection.MetadataLoadContext.dll:token 0x60003ff+0x1b
            at System.Reflection.TypeLoading.RoType.Query[FieldInfo](String , BindingFlags , Func`2 ) in System.Reflection.MetadataLoadContext.dll:token 0x600038c+0x27
            at System.Reflection.TypeLoading.RoType.Query[FieldInfo](BindingFlags ) in System.Reflection.MetadataLoadContext.dll:token 0x600038a+0x0
            at System.Reflection.TypeLoading.RoType.GetFields(BindingFlags ) in /_/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/RuntimeTypeInfo.BindingFlags.cs:line 50
            at System.Type.GetFields() in System.Private.CoreLib.dll:token 0x600048b+0x0
            at System.Reflection.Tests.MetadataLoadContextTests.RelocatableAssembly() in /_/src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/MetadataLoadContext/PathAssemblyResolver.cs:line 354
            at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo ) in System.Private.CoreLib.dll:token 0x6002363+0x6a]]>
        </stack-trace>
    </failure>
</test>
```

@steveisok

**Comment by steveisok** [comment]
This is likely build infra related.

**Comment by steveharter** [comment]
Closing; please add hits if this occurs again.
