### ISSUE TITLE
JIT.Methodical tests failed with Unhandled exception. System.AggregateException: One or more errors occurred

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53708]
Run: [runtime-coreclr crossgen2 20210602.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1168741&view=ms.vss-test-web.build-test-results-tab&runId=35219998&resultId=101345&paneView=debug)

Failed tests:
```
R2R-CG2 OSX arm64 Checked @ OSX.1100.ARM64.Open

- JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.sh
- JIT/Methodical/explicit/basic/_il_dbgrefarg_o/_il_dbgrefarg_o.sh
- JIT/Methodical/explicit/basic/_il_relrefarg_c/_il_relrefarg_c.sh

```
**Error message:**
```
/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.sh: line 254: -r:/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.dll.rsp: No such file or directory
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.Wait() at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSortApi(TDataStructure arrayToSort, TComparer comparer)
at ILCompiler.DependencyAnalysis.ReadyToRun.InliningInfoNode.GetData(NodeFactory factory, Boolean relocsOnly)
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable()
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)
dyld: Library not loaded: @rpath/libmscordaccore.dylib
Referenced from: /private/tmp/helix/working/A2730911/p/dotnet-cli/shared/Microsoft.NETCore.App/6.0.0-preview.3.21201.4/createdump
Reason: image not found
/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.sh: line 204: 97068 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/Reports/JIT.Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/IL-CG2/_il_dbgrefarg_s.dll
Response file: /private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.dll.rsp
/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/IL-CG2/_il_dbgrefarg_s.dll
-o:/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.dll
-r:/tmp/helix/working/A2730911/p/System..dll
-r:/tmp/helix/working/A2730911/p/Microsoft..dll
-r:/tmp/helix/working/A2730911/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /tmp/helix/working/A2730911/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.dll
Crossgen2 failed with exitcode: 134
in ReleaseLock
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A2730911/p
/private/tmp/helix/working/A2730911/w/B64009B7/e/JIT/Methodical/explicit/basic/_il_dbgrefarg_s/_il_dbgrefarg_s.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._explicit_basic__il_dbgrefarg_s__il_dbgrefarg_s_._explicit_basic__il_dbgrefarg_s__il_dbgrefarg_s_sh()
```

**Comment by BruceForstall** [comment]
Lots more cases of this failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1198802&view=ms.vss-test-web.build-test-results-tab

**Comment by mateoatr** [comment]
Still failing: https://dev.azure.com/dnceng/public/_build/results?buildId=1223384&view=ms.vss-test-web.build-test-results-tab

**Comment by BruceForstall** [comment]
@dotnet/crossgen-contrib @mangod9

**Comment by davidwrighton** [comment]
This is a known issue that reproduces on all .NET applications on OSX arm64. It is most commonly seen in crossgen2 executions, but all heavily multithreaded OSX arm64 applications are vulnerable. At this time, this stress issue is not understood, although indications are that it occurs in functions which take an explicit generic context.

**Comment by BruceForstall** [comment]
Tons of these failures in the r2r-extra job: https://dev.azure.com/dnceng/public/_build/results?buildId=1232094&view=ms.vss-test-web.build-test-results-tab

**Comment by mateoatr** [comment]
More test failures due to this exception in [runtime-coreclr r2r](https://dev.azure.com/dnceng/public/_build/results?buildId=1236942&view=ms.vss-test-web.build-test-results-tab).

**Comment by mateoatr** [comment]
Lots of failures related to this on different pipelines. To list a few: [runtime-coreclr r2r](https://dev.azure.com/dnceng/public/_build/results?buildId=1244601&view=results), [runtime-coreclr crossgen2](https://dev.azure.com/dnceng/public/_build/results?buildId=1244622&view=results), [runtime-libraries-coreclr outerloop](https://dev.azure.com/dnceng/public/_build/results?buildId=1244733&view=results).

**Comment by mangod9** [comment]
Dupe of #51250
