### ISSUE TITLE
Test failing in CI: Microsoft.Extensions.Hosting.InternalHostTests.HostApplicationLifetimeEventsOrderedCorrectlyDuringShutdown

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#53720]
https://dev.azure.com/dnceng/public/_build/results?buildId=1170895&view=ms.vss-test-web.build-test-results-tab&runId=35271328&resultId=115693&paneView=debug

```console
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.Hosting.Internal.HostTests.HostApplicationLifetimeEventsOrderedCorrectlyDuringShutdown() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs:line 807
```

**Comment by SakeTao** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20250906.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=1141204)

**Failed tests:**
```
net10.0-windows-Release-x64-syntheticpgo-Windows.10.Amd64.Open
    - Microsoft.Extensions.Hosting.Internal.HostTests.HostApplicationLifetimeEventsOrderedCorrectlyDuringShutdown
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at Microsoft.Extensions.Hosting.Internal.HostTests.HostApplicationLifetimeEventsOrderedCorrectlyDuringShutdown() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Internal/HostTests.cs:line 838
   at System.RuntimeMethodHandle.InvokeMethod(ObjectHandleOnStack target, Void** arguments, ObjectHandleOnStack sig, BOOL isConstructor, ObjectHandleOnStack result)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs:line 1168
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by karelz** [comment]
Triage: Let's check Kusto DB if it happened in some reasonable time recently. If not, let's close it.
@mrek-msft

**Comment by jkotas** [comment]
Hit by #128950
