### ISSUE TITLE
Test failure System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(fileName: \"C:\\\\h\\\\w\\\\9C600885\\\\w\\\\BCB80A07\\\\e\\\\bitmaps\\\\inval\"..., size: {Width=0, Height=0})

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53846]
Run: [runtime-coreclr libraries-jitstress 20210607.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1174173&view=ms.vss-test-web.build-test-results-tab&runId=35362668&resultId=130822&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(fileName: \"C:\\\\h\\\\w\\\\9C600885\\\\w\\\\BCB80A07\\\\e\\\\bitmaps\\\\inval\"..., size: {Width=0, Height=0})

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.IO.Stream.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 158
   at System.Drawing.ToolboxBitmapAttribute.GetImageFromFile(String imageFile, Boolean large, Boolean scaled) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs:line 201
   at System.Drawing.ToolboxBitmapAttribute..ctor(String imageFile) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs:line 35
   at System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(String fileName, Size size) in /_/src/libraries/System.Drawing.Common/tests/ToolboxBitmapAttributeTests.cs:line 53
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20210817.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1297863&view=ms.vss-test-web.build-test-results-tab&runId=38273664&paneView=debug&resultId=150055)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(fileName: \"C:\\\\h\\\\w\\\\99C60896\\\\w\\\\B06A0985\\\\e\\\\bitmaps\\\\inval\"..., size: {Width=0, Height=0})
```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.IO.Stream.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 158
   at System.Drawing.ToolboxBitmapAttribute.GetImageFromFile(String imageFile, Boolean large, Boolean scaled) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs:line 182
   at System.Drawing.ToolboxBitmapAttribute..ctor(String imageFile) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs:line 31
   at System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(String fileName, Size size) in /_/src/libraries/System.Drawing.Common/tests/ToolboxBitmapAttributeTests.cs:line 53
```
