### ISSUE TITLE
[windows][mono] Test failure: Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.RegisterFromSTAThreadThatGoesAway_MessageStillDelivered

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#53863]
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50510-merge-61b0571fefe94470ad/Microsoft.Win32.SystemEvents.Tests/console.03a3007e.log?sv=2019-07-07&se=2021-06-28T08%3A23%3A38Z&sr=c&sp=rl&sig=AlmDroaP5I7kmtou2yVWqB%2BQ2Lp9JyTfuez%2BFMXHiNs%3D

```
Unhandled Exception:
System.PlatformNotSupportedException: COM Interop is not supported on this platform.

   at System.Threading.Thread.SetApartmentStateUnchecked(ApartmentState state, Boolean throwOnError) in /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 275

   at System.Threading.Thread.SetApartmentState(ApartmentState state, Boolean throwOnError) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs:line 507

   at System.Threading.Thread.SetApartmentState(ApartmentState state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs:line 486

   at Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.<RegisterFromSTAThreadThatGoesAway_MessageStillDelivered>b__2_0() in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/SystemEvents.InvokeOnEventsThread.cs:line 69

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378

--- End of stack trace from previous location ---

   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
[ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: COM Interop is not supported on this platform.

   at System.Threading.Thread.SetApartmentStateUnchecked(ApartmentState state, Boolean throwOnError) in /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 275

   at System.Threading.Thread.SetApartmentState(ApartmentState state, Boolean throwOnError) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs:line 507

   at System.Threading.Thread.SetApartmentState(ApartmentState state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs:line 486

   at Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.<RegisterFromSTAThreadThatGoesAway_MessageStillDelivered>b__2_0() in /_/src/libraries/Microsoft.Win32.SystemEvents/tests/SystemEvents.InvokeOnEventsThread.cs:line 69

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378

--- End of stack trace from previous location ---

   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.RegisterFromSTAThreadThatGoesAway_MessageStillDelivered [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          System.PlatformNotSupportedException: COM Interop is not supported on this platform.
        /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs(275,0): at System.Threading.Thread.SetApartmentStateUnchecked(ApartmentState state, Boolean throwOnError)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs(507,0): at System.Threading.Thread.SetApartmentState(ApartmentState state, Boolean throwOnError)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs(486,0): at System.Threading.Thread.SetApartmentState(ApartmentState state)
        /_/src/libraries/Microsoft.Win32.SystemEvents/tests/SystemEvents.InvokeOnEventsThread.cs(69,0): at Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.<RegisterFromSTAThreadThatGoesAway_MessageStillDelivered>b__2_0()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        
        Child process:
          Microsoft.Win32.SystemEvents.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests Void <RegisterFromSTAThreadThatGoesAway_MessageStillDelivered>b__2_0()
        
        
  Finished:    Microsoft.Win32.SystemEvents.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Win32.SystemEvents.Tests  Total: 208, Errors: 0, Failed: 1, Skipped: 0, Time: 0.335s
----- end Tue 06/08/2021  8:34:33.40 ----- exit code 1 ----------------------------------------------------------
```

The `Microsoft.Win32.SystemEventsTests.InvokeOnEventsThreadTests.RegisterFromSTAThreadThatGoesAway_MessageStillDelivered` test was added in https://github.com/dotnet/runtime/pull/53467

**Comment by MaximLipnin** [comment]
The test is disabled in https://github.com/dotnet/runtime/pull/53893

**Comment by SamMonoRT** [comment]
@marek-safar - do we know if we need to add COM Interop support for Windows for 6.0 ?

**Comment by marek-safar** [comment]
Move any COM features to Future
