### ISSUE TITLE
SocketsHttpHandler.SendAsync reads request Content stream twice

### ISSUE THREAD

**Issue by davidni** [dotnet/runtime#53914]
### Description

Under very specific conditions, SocketsHttpHandler.SendAsync when using HTTP/2 attempts to copy the HttpRequestMessage.Content twice.

In Island Gateway (AKA what eventually became YARP), we have code similar to the following, and this invariant that we do a best-effort check is being violated:

https://github.com/microsoft/reverse-proxy/blob/961608d01adc9ab07d4cd3f5adf7d4d3dfff3f0f/src/ReverseProxy/Proxy/StreamCopyHttpContent.cs#L118-L125

The following criteria seem to be necessary to trigger this bug, though it may be broader than this:

* Request specifies `Expect: 100-continue`
* Destination does not produce a `100` response within the first 1 second
* HttpConnectionPool.SendWithRetryAsync decides to retry (just a hypothesis)

It seems like the SocketsHttpHandler machinery may be deciding it is safe to retry because the destination service provably did not start processing the first attempt, but it seems to make the wrong assumption that it is okay to read the HttpRequestMessage.Content again on the next attempt. This is not a valid assumption, and leads to issues in applications such as YARP where the Content is a wrapper around Kestrel's incoming request body stream, which cannot be read twice.

### Configuration

* .NET Core 3.1.15
* Windows Server Datacenter 2019

### Other information

Filing this as a result of an offline discussion with @halter73 and @davidfowl. Thanks folks for helping investigate.

@karelz FYI.

**Comment by geoffkizer** [comment]
Can you try with a recent .NET 6 build?

There are a bunch of situations that can cause us to try to read the content stream twice. If the content doesn't support this, it can throw and we should fail the request. There's not really anything else we can do at that point.

**Comment by geoffkizer** [comment]
More info:

Things that can cause the content stream to be read twice include stuff like redirects and authentication. We will handle specific status codes like 302 or 401 and issue another request and try to send the content again. Expect: 100-continue can be used to try to avoid having to read the content twice in cases like this, because hopefully we will get the 302 or 401 before proceeding to send content; but obviously this only will work if the expect timeout doesn't expire.

Are you using redirects or authentication here?

We do have logic to retry requests on connection shutdown -- that's what HttpConnectionPool.SendWithRetryAsync is about. But this shouldn't cause the content stream to be read twice. Once we start sending any content, the request is no longer retryable.

**Comment by davidni** [comment]
Thanks Geoff.

1: Unfortunately I do not have a minimal repro of this atm and I am unable to verify on .NET 6 (we will not transition our production workloads before GA).

2: There are no redirects nor authentication at play here. Connection shutdown is likely the trigger -- during the incident where we had this happen, the destination service was overwhelmed and couldn't handle the load. This meant many of our requests were hitting the 1-second timeout for Expect:100-continue. And some *were* reading the content stream twice. We have unambiguous evidence of this based on a few occurrences of the error I mentioned in the issue above (`"Stream was already consumed"`). We have indirect evidence of this based on Kestrel logs with the following stack trace, indicating two concurrent calls to read the request content:

```
System.NotSupportedException:  The ReadAsync method cannot be called when another read operation is pending.
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at IslandGateway.Core.Service.Proxy.StreamCopier.CopyAsync(Stream source, Stream destination, CancellationToken cancellation)
   at IslandGateway.Core.Service.Proxy.StreamCopyHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at IslandGateway.Core.Service.Proxy.HttpProxy.<>c__DisplayClass13_0.<<ExecuteRequestAsync>b__0>d.MoveNext()
```

**Comment by geoffkizer** [comment]
Ahhhh, this is HTTP2. I had assumed HTTP/1.1.

Yes, with HTTP2, there are additional scenarios. When we receive a GOAWAY (server-initiated connection shutdown), the server tells us which streams will be processed and which won't; the ones that haven't are retryable, even if we already started sending the content. So in this case you will definitely see us try to read the content twice.

That said, this is expected behavior. If you can't support reading the content again, then you should throw and the request should be failed.

**Comment by davidni** [comment]
@Tratcher for your take re. YARP. If confirmed this is acceptable, we would at least want to make sure we are handling it correctly and emitting the right data to telemetry. E.g. perhaps this should count as a Transport error (?)

**Comment by geoffkizer** [comment]
You can also consider increasing the Expect100ContinueTimeout so that you'll hit this less frequently.

**Comment by Tratcher** [comment]
> We have indirect evidence of this based on Kestrel logs with the following stack trace, indicating two concurrent calls to read the request content

This part's concerning, it means SerializeToStreamAsync is called concurrently on two threads and the `Started` check in YARP isn't thread safe. The two concurrent threads make sense if the retry is happing at the same time as the 100-continue expires. @geoffkizer that sounds like a potential race in the client logic. If the 100-continue expired and is sending content then the retry should wait for that to abort.

This could be mitigated by making the Started check in YARP thread safe. I'll file an issue for that.

As for the retry scenario in general, yes that's expected to fail in YARP and it _should_ be reported accordingly. What type of failure is it currently reported as? It might depend on if it sent the whole request body before retrying, or if it was aborted part way through.

**Comment by Tratcher** [comment]
Raising the 100-continue timeout is a valid mitigation and shouldn't affect responsive servers.

**Comment by davidni** [comment]
> (1) Cancel the cancellation token passed to SerializeToStreamAsync

@geoffkizer there's no cancellation parameter here, can you clarify what you're referring to? This may be the issue at hand. We really are making no effort to stop the first SerializeToStreamAsync, because there doesn't seem to be any signal we should be reacting to.

```cs
public abstract class HttpContent : IDisposable
{
  //...
  protected abstract Task SerializeToStreamAsync(Stream stream, TransportContext context);
}
```

---

> (2) Throw on any attempt to use the request body stream passed to SerializeToStreamAsync

The failure we are experiencing happens *before* we attempt to write to the request body stream. We were still waiting to read bytes from the other side before proxying to the destination.

**Comment by Tratcher** [comment]
SerializeToStreamAsync added a new cancellable overload in 5.0. YARP hasn't implemented it yet since we're still supporting 3.1.
https://github.com/dotnet/runtime/blob/c14ac488cc5f7d2ad71e7f81d6a05a1da8c76237/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L354

**Comment by MihaZupan** [comment]
Wouldn't we throw it away in YARP anyway? Right now we have [a comment in the code about it](https://github.com/microsoft/reverse-proxy/blob/d593701b5839ddd8d2422c2044d1e0ada74f2b18/src/ReverseProxy/Proxy/StreamCopyHttpContent.cs#L116-L118)

> Note we do not need to implement the SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken token) overload because the token it provides is the short request token, not the long body token passed from the constructor. Using the short token would break bidirectional streaming scenarios.

**Comment by Tratcher** [comment]
> Note that in cases like this, where we get a GOAWAY or similar and need to cancel sending the request body, we will do two things:
> 
> (1) Cancel the cancellation token passed to SerializeToStreamAsync

@geoffkizer @MihaZupan is this a linked token? What are the possible triggers for it?

**Comment by karelz** [comment]
@MihaZupan did you get chance to look at it? It is not clear why untriaged label was removed.

**Comment by MihaZupan** [comment]
From reading the code, it looks like it is possible that the request content will be read multiple times concurrently on HTTP 1:
- Thread A creates an [`expect100Timer`](https://github.com/dotnet/runtime/blob/3e3b00c53b127ec20e1d4d74bb75992fb650e08a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L531-L535)
- Thread A [reads an EOF from the server, sees `_startedSendingRequestBody == false` and sets `_canRetry = true`, throws an IO exception](https://github.com/dotnet/runtime/blob/3e3b00c53b127ec20e1d4d74bb75992fb650e08a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L583-L594)
- Timer wakes up thread B, signals `allowExpect100ToContinue` with true and starts reading the request content
- Thread A enters `catch`, [sees `sendRequestContentTask` hasn't completed, but doesn't await it](https://github.com/dotnet/runtime/blob/3e3b00c53b127ec20e1d4d74bb75992fb650e08a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L790-L808)
- Thread A throws a retryable exception and retries the request on a new connection, reading the request content again
- Both A and B are reading the content, the CT may not be signaled for either

This could cause the exception seen in https://github.com/dotnet/aspnetcore/issues/33409#issuecomment-859829081.


Judging from the [stack trace](https://github.com/dotnet/runtime/issues/53914#issuecomment-857321400) seen by David, I suspect a similar race exists for HTTP/2. 

@geoffkizer If we're saying that the content may be read multiple times, are we also saying that those reads may happen concurrently?
If so, we should fix cases like [`StreamContent`](https://github.com/dotnet/runtime/blob/3e3b00c53b127ec20e1d4d74bb75992fb650e08a/src/libraries/System.Net.Http/src/System/Net/Http/StreamContent.cs#L124) that aren't using a thread-safe check.
If not, we should fix races in `Http*Connection`.

**Comment by geoffkizer** [comment]
> @geoffkizer If we're saying that the content may be read multiple times, are we also saying that those reads may happen concurrently?

No, the read should never happen concurrently.

**Comment by geoffkizer** [comment]
Your analysis seems correct to me.

Seems like we need to possibly do a couple things here.

The primary one is, we should wait for the sendRequestContentTask to complete before we propagate the exception upward. That should ensure we don't read concurrently from the request content.

However, doing that may introduce some new issues. In order to ensure the sendRequestContentTask completes promptly (or indeed at all), we need to cancel it. Unlike HTTP2, we don't seem to have logic to do this for HTTP1.1; I think we should.

> Judging from the stack trace seen by David, I suspect a similar race exists for HTTP/2.

It's certainly possible, but the HTTP2 code is pretty different so we should investigate and confirm

One thing I noticed from the stack trace you linked is, the derived HttpContent class doesn't implement the SerializeToStreamAsync overload with a cancellation token. That means that even if we try to cancel sending the request body, it won't necessarily be cancelled promptly. I'm not sure this matters or not in terms of reproducing the issue -- I can't see how it would matter, but maybe I'm missing something.

As an aside, this all makes me wish we had common Expect: 100-Continue logic across different HTTP versions. We now have this implemented in three different places, unfortunately.

**Comment by karelz** [comment]
Triage: There is workaround (lock in custom HttpContent), so not critical for 6.0. But we should fix it -- i.e. make sure we don't start 2nd read before fully cancelling the 1st one.

**Comment by geoffkizer** [comment]
Actually I think there's an even more basic issue here:

>Thread A reads an EOF from the server, sees _startedSendingRequestBody == false, sets _canRetry = true and throws an IO exception
Timer wakes up thread B, signals allowExpect100ToContinue with true and starts reading the request content

We shouldn't be both setting _canRetry = true and actually starting to send the body. We either need to prevent the body from sending when _canRetry is set to true, or if we can't (i.e. we lose the race), then don't set _canRetry to true.

**Comment by shawncx** [comment]
Hi team, we meet the exact same issue. We are using .NET Core 3.1 and HTTP/2. May I ask is there any recommended action to mitigate this issue? Or what kind of error is recommended to return to user for this case?

**Comment by karelz** [comment]
Triage: This problem exists already in 6.0, so not a regression.
Only 1 customer report which has workaround in YARP.
We should look at it from reliability perspective, but given low impact on customers, moving to 8.0.

**Comment by ManickaP** [comment]
Triage: still limited customer impact, moving to future.

**Comment by MihaZupan** [comment]
I think I figured out how concurrent calls to `SerializeToStreamAsync` can occur with HTTP/2 as well:
1.  Send a request with Expect 100-Continue set.
1. The Http2Connection [sends the request headers](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L2052-L2062) and calls `Http2Stream.SendRequestBodyAsync`, storing the `requestBodyTask`.
1. `SendRequestBodyAsync` starts waiting on [`WaitFor100ContinueAsync`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L326) and yields.
1. The Http2Connection starts [waiting on the request body or response headers tasks](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L2078) to complete.
1. After some time, the `Expect100ContinueTimeout` timer in `WaitFor100ContinueAsync` fires. `SendRequestBodyAsync` sees that the request cancellation hasn't been requested yet and is about to call `HttpContent.SerializeToStreamAsync` in the background.
1. At about the same time in a different thread, the server sends us a GOAWAY frame or a `REFUSED_STREAM` RST. Http2Connection decides that the request is retryable and calls [`Http2Stream.OnReset`](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L899) with `canRetry: true`.
1. `OnReset()` sets `Http2Stream._canRetry` to true and calls `Http2Stream.Cancel()`, which signals the waiter.
1. The waiter getting signaled wakes up the `ReadResponseHeadersAsync` task, which sees that the stream was reset and throws the retryable exception.
1. The `Http2Connection.SendAsync` which was waiting on the request body or response headers to complete now wakes up and sees that the response headers task completed first.
1. [It doesn't wait for the `requestBodyTask` to complete, but sets up a continuation that will observe any exceptions.](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L2103)
1. The retryable exception from `responseHeadersTask` is propagated out of `SendAsync` and into [`HttpConnectionPool.SendWithVersionDetectionAndRetryAsync`](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1031) which will now attempt to send the request again.
1. The request is sent again, and `HttpContent.SerializeToStreamAsync` is called.
1. In the background, the original `SendRequestBodyAsync` task (nr. 3) may just now be calling into `SerializeToStreamAsync` at the same time.

The gist is that we aren't waiting for `requestBodyTask` to complete before returning a retryable exception from [`Http2Connection.SendAsync`](https://github.com/dotnet/runtime/blob/0202b242169f8d5955e0411dc5e4f42a5d016c1b/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L2044), allowing `SerializeToStreamAsync` to be called multiple times concurrently.

**Comment by sberube** [comment]
> Triage: This problem exists already in 6.0, so not a regression. Only 1 customer report which has workaround in YARP. We should look at it from reliability perspective, but given low impact on customers, moving to 8.0.

@karelz we seem to observe the same behavior using YARP 2.2 and .NET Core 8. You were mentionning that 1 customer has a workaround, what is this workaround and how can we add it in our system?

Thanks!

**Comment by MihaZupan** [comment]
@sberube I take it you're seeing the `"Stream was already consumed."` error message?
See https://github.com/microsoft/reverse-proxy/issues/1683

That may happen during normal proxy operation if HttpClient decodes to retry a request, something that YARP doesn't support as we don't buffer the request body.

This issue is tracking a bug in SocketsHttpHandler where those reads may happen concurrently. The [workaround mentioned](https://github.com/microsoft/reverse-proxy/pull/1071) is mitigating just that aspect, and it's being used by YARP internally.

**Comment by nlyu** [comment]
We are seeing this issue get escalated more frequent now. As we have more customer behind our reverse proxy, using chat bot which is on HTTP2.

Is this fixed in NET8? 😕 See people report still see this issue in above thread. Bump up

**Comment by MihaZupan** [comment]
Copying from offline discussions since there have been misunderstandings about this issue.

There are two related but separate things going on in this GitHub issue:
- The fact that _"SocketsHttpHandler.SendAsync reads request Content stream twice"_ is not a bug[^1].
  - HttpClient can in some cases retry requests internally, even if content was already sent. In the case of HTTP/2, that might happen if the backend server tells you to stop using that HTTP/2 connection.
  - If that happens in YARP, you'll see the _"Stream was already consumed"_ error. This is pretty much always a false positive - it's not really an error, but an indication that YARP couldn't process the request, but that it should otherwise be fine to retry. (it's an error from the client talking to YARP's perspective, but not from the backend server's perspective)
  - [Improve the exception for double HttpContent reads #1683](https://github.com/dotnet/yarp/issues/1683) is tracking making that more obvious for YARP users.
- The bug part of this issue that there are cases where the second sending of content may happen concurrently with the first attempt. Those are edge-case race conditions in the HttpClient implementation that [we've fixed for HTTP/1.1](https://github.com/dotnet/runtime/issues/53914#issuecomment-900486971), but that [still exists for HTTP/2](https://github.com/dotnet/runtime/issues/53914#issuecomment-1431560360). The workaround for this bug is in YARP since 1.0.

---

`Expect: 100-Continue`:
While it is one of the conditions to hit the race condition bugs in H1 and H2, sending the stream twice can happen regardless of it being set or not.

In HTTP/2, the cases where you might see double reads are called out in https://github.com/dotnet/yarp/issues/2721#issuecomment-2754611848:
- The backend server is closing connections on YARP (via HTTP/2 GOAWAY) -- e.g. restarts / scaling down
- The backend server is refusing requests via HTTP/2 REFUSED_STREAM
- The backend server is lowering the MaxStreamsPerConnection limits under the default 100 (won't happen by default with Kestrel for example)

These are the sort of conditions where it's most likely that the server will tell you to back off immediately after it receives a request, in which case Expect continue helps since you don't proactively send the content, and get to do so "for the first time" in the retry.

[^1]: It's not a bug as far as HttpClient is concerned, but it is problematic that there's no way to communicate that the content may not support being read again. We might need an API here.
