### ISSUE TITLE
[wasm] SendReceive_VaryingLengthBuffers_Success failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53957]
```
[20:06:15] info: Discovering: System.Net.WebSockets.Client.Tests.dll (method display = ClassAndMethod, method display options = None)
[20:06:15] info: Discovered:  System.Net.WebSockets.Client.Tests.dll (found 53 of 87 test cases)
[20:06:15] info: Starting:    System.Net.WebSockets.Client.Tests.dll
[20:07:51] info: http://127.0.0.1:34693/dotnet.js 0 WebSocket connection to 'ws://074bf40fe279493f8fb2a570a8bfbea8/' failed: WebSocket is closed before the connection is established.
[20:10:00] fail: [FAIL] System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: ws://127.0.0.1:34693/WebSocket/EchoWebSocket.ashx)
[20:10:00] info: System.OperationCanceledException : The operation was canceled.
[20:10:00] info:    at System.Threading.Channels.AsyncOperation`1[[System.Net.WebSockets.ReceivePayload, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetResult(Int16 token)
[20:10:00] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
[20:10:00] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
[20:10:00] info:    at System.Net.WebSockets.WebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken)
[20:10:00] info:    at System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync(WebSocket ws, ArraySegment`1 arraySegment, CancellationToken cancellationToken)
[20:10:00] info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server)
[20:10:00] info: --- End of stack trace from previous location ---
[20:11:11] info: http://127.0.0.1:34693/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:34693/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[20:11:12] info: http://127.0.0.1:34693/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:41047/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[20:11:42] info: Finished:    System.Net.WebSockets.Client.Tests.dll
[20:11:42] info: 
[20:11:42] info: === TEST EXECUTION SUMMARY ===
[20:11:42] info: Total: 89, Errors: 0, Failed: 1, Skipped: 0, Time: 327.6009649s
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53905-merge-5a8d9815e63046a192/System.Net.WebSockets.Client.Tests/console.608b53e4.log?sv=2019-07-07&se=2021-06-29T19%3A48%3A07Z&sr=c&sp=rl&sig=pEysk8NCg3vGVdQFHK7K1Q12bdrdQ83pA6K9hLXcrb0%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1179573&view=logs&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4

Configuration: Build Browser wasm Release AllSubsets_Mono

**Comment by lewing** [comment]
Not sure what is going on here @pavelsavara can you take a look?

**Comment by karelz** [comment]
Note: There is also bunch of similar failures of this test, but perhaps that has been already addressed?
```
System.Net.WebSockets.WebSocketException : Unable to connect to the remote server
---- System.Net.Http.HttpRequestException : Unknown error (0xffffffff) (corefx-net-http11.azurewebsites.net:443)
-------- System.Net.Sockets.SocketException : Unknown error (0xffffffff)
```

Date | Build | Notes
-- | -- | --
5/18 | PR #52923 | `System.OperationCanceledException : The operation was canceled.`
5/19 | official test run | 16x - `WebSocketException : Unable to connect to the remote server`
5/20-6/2 | PR #53027 | 143x - mix of failures, incl. 5x `State immediately after ConnectAsync incorrect: Closed`
5/26 | official test run | 29x - `WebSocketException : Unable to connect to the remote server`
5/26 | PR #53277 | 16x - `WebSocketException : Unable to connect to the remote server` &<br/>1x `State immediately after ConnectAsync incorrect: Closed`
5/26-5/27 | PR #53280 | 18x - `WebSocketException : Unable to connect to the remote server`
6/9 | official test run | `System.OperationCanceledException : The operation was canceled.`
6/9 | PR #53905 | `System.OperationCanceledException : The operation was canceled.`
6/9 | PR #53023 | `System.OperationCanceledException : The operation was canceled.`
6/0 | PR #49876 | `System.OperationCanceledException : The operation was canceled.`
6/11 | PR #53644 | `System.OperationCanceledException : The operation was canceled.`
6/12 | PR #54089 | `System.Net.WebSockets.WebSocketException : The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Connecting, Open, CloseReceived, CloseSent'`
6/13 | PR #54124 | `System.OperationCanceledException : The operation was canceled.`
6/14 | PR #54136 | `System.OperationCanceledException : The operation was canceled.`
6/14 | PR #52510 | `System.OperationCanceledException : The operation was canceled.`
6/15 | PR #53294 | `System.OperationCanceledException : The operation was canceled.`
6/15 | PR #54053 | `System.OperationCanceledException : The operation was canceled.`
6/16 | PR #54286 | `System.OperationCanceledException : The operation was canceled.`

**Comment by pavelsavara** [comment]
error `0xffffffff` is already captured here https://github.com/dotnet/runtime/issues/53281

**Comment by pavelsavara** [comment]
Running this locally in tight loop I was able to only reproduce 
```
Retry after attempt #1 failed with System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.WebSockets.WebSocketException (0x80004005): An internal WebSocket error occurred. Please see the innerException, if present, for more details.
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncJavaScript(Uri uri, CancellationToken cancellationToken, List`1 requestedSubProtocols)
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncJavaScript(Uri uri, CancellationToken cancellationToken, List`1 requestedSubProtocols)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<>c__DisplayClass4_0.<<GetConnectedWebSocket>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<Retry>d__5`1[[System.Net.WebSockets.ClientWebSocket, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
```

**Comment by pavelsavara** [comment]
With timeout down  to 3000ms 
```
  info: http://127.0.0.1:49635/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:49636/WebSocket/EchoWebSocket.ashx' failed: WebSocket is closed before the connection is established.
  fail: [FAIL] System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: wss://127.0.0.1:49636/WebSocket/EchoWebSocket.ashx)
  info: System.Threading.Tasks.TaskCanceledException : A task was canceled.
  info:    at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncJavaScript(Uri uri, CancellationToken cancellationToken, List`1 requestedSubProtocols)
  info:    at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
  info:    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
  info:    at System.Net.WebSockets.Client.Tests.WebSocketHelper.<>c__DisplayClass4_0.<<GetConnectedWebSocket>b__0>d.MoveNext()
  info: --- End of stack trace from previous location ---
  info:    at System.Net.WebSockets.Client.Tests.WebSocketHelper.<Retry>d__5`1[[System.Net.WebSockets.ClientWebSocket, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
  info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server)
  info: --- End of stack trace from previous location ---
```

**Comment by radical** [comment]
I'm seeing this again in #55899, which includes the fix from #54453.

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55899-merge-b51cb13c0b43434693/System.Net.WebSockets.Client.Tests/console.444a12bc.log?sv=2019-07-07&se=2021-08-08T06%3A13%3A38Z&sr=c&sp=rl&sig=RHqobh6hXwjjb4rcKaASc6vaBXrU8X1k63Nl3bRE7mk%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1245274&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4)

```
[06:29:20] info: Starting:    System.Net.WebSockets.Client.Tests.dll
[06:30:52] info: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:35747/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[06:30:53] info: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:36447/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[06:33:26] fail: [FAIL] System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: ws://127.0.0.1:35747/WebSocket/EchoWebSocket.ashx)
[06:33:26] info: System.OperationCanceledException : The operation was canceled.
[06:33:26] info:    at System.Threading.Channels.AsyncOperation`1[[System.Net.WebSockets.ReceivePayload, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetResult(Int16 token) in System.Threading.Channels.dll:token 0x600001d+0x53
[06:33:26] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x1e1
[06:33:26] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x2b4
[06:33:26] info:    at System.Net.WebSockets.WebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.dll:token 0x600005a+0x97
[06:33:26] info:    at System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync(WebSocket ws, ArraySegment`1 arraySegment, CancellationToken cancellationToken) in System.Net.WebSockets.Client.Tests.dll:token 0x600012c+0x87
[06:33:26] info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server) in System.Net.WebSockets.Client.Tests.dll:token 0x600013a+0x23a
[06:33:26] info: --- End of stack trace from previous location ---
[06:34:40] fail: [out of order message from the browser]: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:35747/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[06:34:50] fail: [out of order message from the browser]: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:36447/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[06:34:51] info: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:42637/' failed: WebSocket is closed before the connection is established.
[06:35:00] info: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'ws://a3b37ae5bfa94d849b08f02430a1a365/' failed: WebSocket is closed before the connection is established.
[06:35:11] info: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:35747/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[06:35:11] info: http://127.0.0.1:35747/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:36447/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[06:35:11] info: Finished:    System.Net.WebSockets.Client.Tests.dll
```

**Comment by lewing** [comment]
cc @kg 

Pavel is out of office this week.

**Comment by radical** [comment]
wasm/Windows
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55939-merge-34000b0db074409ab2/System.Net.WebSockets.Client.Tests/console.b53044a0.log?sv=2019-07-07&se=2021-08-08T18%3A23%3A38Z&sr=c&sp=rl&sig=I%2B%2BFo%2B2pTqMtiJ9W5LXobLW8J2VXwbLxx8%2FD%2BEd1zYg%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1246281&view=logs&jobId=f9ca8601-c4c2-5da2-61cf-0da7d83d7557&j=f9ca8601-c4c2-5da2-61cf-0da7d83d7557&t=6f9dc6e4-5fb8-536e-70b9-642f2da0a848)

```
18:33:44] info: Starting:    System.Net.WebSockets.Client.Tests.dll
[18:33:45] info: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:54545/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[18:33:45] info: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:54546/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[18:37:44] fail: [FAIL] System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: wss://127.0.0.1:54546/WebSocket/EchoWebSocket.ashx)
[18:37:44] info: System.OperationCanceledException : The operation was canceled.
[18:37:44] info:    at System.Threading.Channels.AsyncOperation`1[[System.Net.WebSockets.ReceivePayload, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetResult(Int16 token) in System.Threading.Channels.dll:token 0x600001d+0x53
[18:37:44] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x1e1
[18:37:44] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x2b4
[18:37:44] info:    at System.Net.WebSockets.WebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.dll:token 0x600005a+0x97
[18:37:44] info:    at System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync(WebSocket ws, ArraySegment`1 arraySegment, CancellationToken cancellationToken) in System.Net.WebSockets.Client.Tests.dll:token 0x600012c+0x87
[18:37:44] info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server) in System.Net.WebSockets.Client.Tests.dll:token 0x600013a+0x23a
[18:37:44] info: --- End of stack trace from previous location ---
[18:38:39] fail: [out of order message from the browser]: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:54545/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[18:38:39] fail: [out of order message from the browser]: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:54546/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[18:38:52] info: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'ws://127.0.0.1:54675/' failed: WebSocket is closed before the connection is established.
[18:39:05] info: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'ws://382fb62d56174c8685828c087252959d/' failed: WebSocket is closed before the connection is established.
[18:39:30] fail: [FAIL] System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://127.0.0.1:54545/WebSocket/EchoWebSocket.ashx)
[18:39:30] info: Assert.Throws() Failure
[18:39:30] info: Expected: typeof(System.OperationCanceledException)
[18:39:30] info: Actual:   (No exception was thrown)
[18:39:30] info:    at System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(Uri server) in System.Net.WebSockets.Client.Tests.dll:token 0x60000de+0xd0
[18:39:30] info: --- End of stack trace from previous location ---
[18:39:31] info: http://127.0.0.1:54545/dotnet.js 0 WebSocket connection to 'wss://127.0.0.1:54546/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
```

**Comment by stephentoub** [comment]
Failed again here:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55955-merge-5df4c1f8a69541b68e/System.Net.WebSockets.Client.Tests/console.db828456.log?sv=2019-07-07&se=2021-08-09T14%3A12%3A24Z&sr=c&sp=rl&sig=pF6KOcksZz%2B%2FWaGeUwxvJAt8IdRRUvFPqG0b0nmvoFw%3D

https://dev.azure.com/dnceng/public/_build/results?buildId=1248297&view=ms.vss-test-web.build-test-results-tab&runId=37078604&resultId=168062&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

[14:48:00] fail: [FAIL] System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: ws://127.0.0.1:45735/WebSocket/EchoWebSocket.ashx)
[14:48:00] info: System.OperationCanceledException : The operation was canceled.
[14:48:00] info:    at System.Threading.Channels.AsyncOperation`1[[System.Net.WebSockets.ReceivePayload, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetResult(Int16 token) in System.Threading.Channels.dll:token 0x600001d+0x53
[14:48:00] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x1e1
[14:48:00] info:    at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x2b4
[14:48:00] info:    at System.Net.WebSockets.WebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.dll:token 0x600005a+0x97
[14:48:00] info:    at System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync(WebSocket ws, ArraySegment`1 arraySegment, CancellationToken cancellationToken) in System.Net.WebSockets.Client.Tests.dll:token 0x600012c+0x87
[14:48:00] info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server) in System.Net.WebSockets.Client.Tests.dll:token 0x600013a+0x23a
[14:48:00] info: --- End of stack trace from previous location ---

**Comment by karelz** [comment]
It started failing after it was re-enabled on 7/15 in PR #54453:

Day | Failures
-- | --
7/1 | 1x PR
7/15 | 2x PR
7/16 | 6x PR
7/17 | 1x Official run + 1x PR
7/18 | 1x PR
7/19 | 3x PR
7/20 | 8x PR

I think the test needs to be disabled again ...

**Comment by karelz** [comment]
@kg @lewing can you please disable the test? It seems to be failing rather often ...

**Comment by pavelsavara** [comment]
I'm on it

**Comment by pavelsavara** [comment]
I'm able to reproduce it locally if I decrease timeout or run the body of the test in a loop many times. So, now I think that it's a consequence of timeout. But the timeout is 30s for a test here, so I'm not clear if the CI machine could be so slow.

**Comment by pavelsavara** [comment]
Possibly related failure I was able to reproduce locally.
```
System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---- System.TimeoutException : The operation was canceled.
-------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
------------ System.Runtime.InteropServices.JavaScript.JSException : AbortError: The user aborted a request.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 623
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 546
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_LargeRequestHeader_HeadersAndValuesSent(RemoteServer remoteServer, Uri uri) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.RemoteServer.cs:line 241
```

And also
```
System.Net.Http.HttpRequestException : TypeError: Failed to fetch
---- System.Runtime.InteropServices.JavaScript.JSException : TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 332
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 547
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.PostAsync_Redirect_LargePayload_Helper(RemoteServer remoteServer, Int32 statusCode, Boolean expectRedirectToPost) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.RemoteServer.cs:line 725
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.PostAsync_RedirectWith302_LargePayload(RemoteServer remoteServer) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.RemoteServer.cs:line 688
```

And also in CI
```
System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://127.0.0.1:49261/WebSocket/EchoWebSocket.ashx)

Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)
```

**Comment by kg** [comment]
Is there a way for us to identify whether a timeout happened deeper in the stack (i.e. a browser quirk or issue with the server) vs inside our code? I feel like it's possible the intermittent failures here aren't our fault and could be due to something about how we're running these tests, but we'd need some way to verify that.

**Comment by pavelsavara** [comment]
WASM network tests are running with echo server inside xharness process, which is different process on the same machine.

For part of HTTP tests, we are talking directly to the xharness kestrel. 
(That is, _not_ via internet, as opposed to coreCLR tests)

For the Loopback part of the tests, we are unable to implement loopback directly on the WASM and therefore we use WebSockets to control the remote loop on the xharness process.
(That is, _not_ in the same process as opposed to coreCLR tests)

On top of that we have extra layer of browser networking stack. 

Also, our WS implementation has extra layer of buffering between WASM and browser. https://github.com/dotnet/runtime/issues/44614 

I will try to run `SendReceive_VaryingLengthBuffers_Success` in tight loop to see if I can figure out more details of that behavior.

**Comment by ilonatommy** [comment]
@pavelsavara, did you get any more details when running `SendReceive_VaryingLengthBuffers_Success` as planned?

**Comment by pavelsavara** [comment]
not really, but maybe this could be related to the issue we found with @maraf yesterday ?
