### ISSUE TITLE
TwoConfigElementsInARow ConfigurationManager test failing when the source assembly compiles against .NETCoreApp

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53960]
The TwoConfigElementsInARow test is failing when testing against the .NETCoreApp variant of System.Configuration.ConfigurationManager (and not against the .NETStandard one).

```
MonoTests.System.Configuration.ConfigurationSectionTest.TwoConfigElementsInARow

System.Configuration.ConfigurationErrorsException : Unrecognized element 'foo'.

 at System.Configuration.ConfigurationElement.DeserializeElement(XmlReader reader, Boolean serializeCollectionKey) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationElement.cs:line 1588
   at System.Configuration.ConfigurationSection.DeserializeSection(XmlReader reader) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ConfigurationSection.cs:line 42
   at MonoTests.System.Configuration.ConfigurationSectionTest.FooConfigSection.Load(String xml) in /_/src/libraries/System.Configuration.ConfigurationManager/tests/Mono/ConfigurationSectionTest.cs:line 57
   at MonoTests.System.Configuration.ConfigurationSectionTest.TwoConfigElementsInARow() in /_/src/libraries/System.Configuration.ConfigurationManager/tests/Mono/ConfigurationSectionTest.cs:line 46
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1178581&view=ms.vss-test-web.build-test-results-tab&runId=35469702&resultId=119514&paneView=debug

**Comment by ViktorHofer** [comment]
Same as in https://github.com/dotnet/runtime/issues/53522#issuecomment-858498485 I accidentally lost the inversion while changing an IndexOf to a Contains function.
