### ISSUE TITLE
RemoteExecutor long running test with dump: ExitDetectionNotBlockedByHandler

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54033]
```
  Discovering: System.Console.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Console.Tests (found 102 of 136 test cases)
  Starting:    System.Console.Tests (parallel test collections = on, max threads = 4)
Assertion failed: (g_hasTty), function UninitializeTerminal, file /Users/runner/work/1/s/src/libraries/Native/Unix/System.Native/pal_console.c, line 208.
    CancelKeyPressTests.ExitDetectionNotBlockedByHandler [FAIL]
      Half-way through waiting for remote process.
      Timed out at 6/10/2021 2:24:51 PM after 60000ms waiting for remote process.
      	Process ID: 22082
      	Handle: 876
      	Name: dotnet
      	MainModule: /private/tmp/helix/working/AA2F08AC/p/dotnet
      	StartTime: 6/10/2021 2:23:50 PM
      	TotalProcessorTime: 00:00:05.6924935
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs(54,0): at CancelKeyPressTests.ExitDetectionNotBlockedByHandler()

Assert failure(PID 22095 [0x0000564f], Thread: 1208526 [0x1270ce]): waitResult == WAIT_TIMEOUT
    File: /Users/runner/work/1/s/src/coreclr/vm/tieredcompilation.cpp Line: 507
    Image: /private/tmp/helix/working/AA2F08AC/p/dotnet

0
0
  Finished:    System.Console.Tests
=== TEST EXECUTION SUMMARY ===
   System.Console.Tests  Total: 143, Errors: 0, Failed: 1, Skipped: 0, Time: 95.678s
/private/tmp/helix/working/AA2F08AC/w/9A5908FD/e
----- end Thu Jun 10 14:25:24 PDT 2021 ----- exit code 1 ----------------------------------------------------------
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1181877&view=ms.vss-test-web.build-test-results-tab&runId=35560014&resultId=156974&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Configuration: `net6.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open`

Dump: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53023-merge-0a8ba24ab0a547739b/System.Console.Tests/core.22082?sv=2019-07-07&se=2021-06-30T21%3A23%3A21Z&sr=c&sp=rl&sig=rSJZdjuyYy2YH%2FxljCutt21WDwauAW0yqahAhUJnr08%3D

cc @jkotas @stephentoub

**Comment by jkotas** [comment]
```
Assert failure(PID 22095 [0x0000564f], Thread: 1208526 [0x1270ce]): waitResult == WAIT_TIMEOUT
    File: /Users/runner/work/1/s/src/coreclr/vm/tieredcompilation.cpp Line: 507
```

**Comment by kouvel** [comment]
The only other result that seems possible is `WAIT_FAILED` if the event handle value is corrupted. Wasn't able to repro the issue, going to see if it happens again.
