### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Ssl3, url: \"https://www.ssllabs.com:10300/\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54044]
Run: [runtime-libraries-coreclr outerloop 20210609.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1180939&view=ms.vss-test-web.build-test-results-tab&runId=35535976&resultId=100214&paneView=debug)

Failed test:
```
net48-windows-Release-x64-Windows.10.Amd64.Client19H1.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Ssl3, url: \"https://www.ssllabs.com:10300/\")

```
**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'.


Stack trace
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Test.Common.RemoteServerQuery.<Run>d__0`1.MoveNext() in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<GetAsync_SupportedSSLVersion_Succeeds>d__7.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__121.MoveNext() in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942
```

**Comment by karelz** [comment]
Triage: Looks like external server problem. It is on WinHttpHandler.
If we see more of these, we should revisit. Closing now.
