### ISSUE TITLE
ilverify fails with various file not found errors

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#54110]
After `dotnet tool update --global dotnet-ilverify --version 5.0.0`, any invocation of `ilverify` that includes a dll (I tried several) fails with:

```
Error: Internal.IL.VerifierException: Assembly or module not found: mscorlib
   at ILVerify.Verifier.SetSystemModuleName(AssemblyName name)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
```

The latest prerelease also fails, but with a different message:
```
dotnet tool install --global dotnet-ilverify --version 6.0.0-preview.4.21253.7
```

```
Error:
  An assembly specified in the application dependencies manifest (ILVerify.deps.json) was not found:
    package: 'System.Collections.Immutable', version: '5.0.0'
    path: 'lib/netstandard2.0/System.Collections.Immutable.dll'
```

**Comment by jkotas** [comment]
> Error: Internal.IL.VerifierException: Assembly or module not found: mscorlib

What is the command line that you are using to invoke ilverify?

ilverify requires explicitly all references, including mscorlib, to be explicitly specified on the command line. It looks like that mscorlib reference is not specified. https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/ILVerify#how-to-use-ilverify

**Comment by AArnott** [comment]
I only specified the one assembly on the command line. I had no idea I had to specify all its references too. Can that be added to the `-?` usage help? It didn't mention it. What's more, peverify.exe doesn't share that requirement, so it would be great to call it out.

**Comment by lovettchris** [comment]
Yeah, I found this confusing too until I found the "-r" command line argument.  I found it to be quite difficult to find all the right folders, and it would be cool if ilverify provided an option that automatically does all this:

```powershell
function FindDotNet($dotnet) {
    $dotnet_path = $ENV:PATH.split([System.IO.Path]::PathSeparator) | ForEach-Object {
        $test = Join-Path -Path $_ -ChildPath $dotnet
        if ($IsWindows) {
            $test = $test + ".exe"
        }
        if (Test-Path -Path $test) {
            return $_
        }
        $candidate = [System.IO.Path]::Combine($_, "dotnet")
        if (Test-Path -Path $candidate) {
            $candidate = TraverseLink($candidate)
            if (Test-Path -Path $candidate -PathType Leaf) {
                $candidate = [System.IO.Path]::GetDirectoryname($candidate)
            }
            return $candidate
        }
    }

    if ($dotnet_path -is [array]) {
        $dotnet_path = $dotnet_path[0]
    }
    return $dotnet_path
}

function FindNetCoreApp($dotnet_path, $version) {
    # find the matching version in c:\Program Files\dotnet\shared\Microsoft.NETCore.App\*
    $result = $null
    $latest = $null
    $path = Join-Path -Path $dotnet_path -ChildPath "shared" -AdditionalChildPath "Microsoft.NETCore.App"
    foreach ($item in Get-ChildItem -Path $path -Directory) {
        if ($item.Name.StartsWith($version)) {
            $v = [version] $item.Name
            if ($null -eq $latest -or $v -gt $latest) {
                $latest = $v
                $result = $item.FullName
            }
        }
    }
    if ($null -eq $result) {
        Write-Error("Microsoft.NETCore.App folder matching $version not found")
        exit 1
    }
    return $result
}

$dotnet_path = FindDotNet("dotnet");
$AssemblyName = GetAssemblyName($target)
$NetCoreApp = FindNetCoreApp -dotnet_path $dotnet_path -version "5.0"
$command = "$PSScriptRoot/bin/net5.0/$AssemblyName.dll"
$command = $command + ' -r "' + "$PSScriptRoot/bin/net5.0/*.dll" + '"'
$command = $command + ' -r "' + "$dotnet_path/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/*.dll" + '"'
$command = $command + ' -r "' + "$PSScriptRoot/../bin/net5.0/*.dll" + '"'
$command = $command + ' -r "' + $NetCoreApp + '/*.dll"'
```

**Comment by JulieLeeMSFT** [comment]
Moving to future since ILVerify is preview feature.

**Comment by zachrybaker** [comment]
The error "Error: Internal.IL.VerifierException: Assembly or module not found: mscorlib" can still occur even after RTFM and following the directions. For example, for a net6.0 tf dll:

> dotnet tool install --global dotnet-ilverify --version 6.0.0            
> ILVerify.exe myTarget.dll -r "c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.9\*.dll" 

Error: Internal.IL.VerifierException: Assembly or module not found: mscorlib
   at ILVerify.Verifier.SetSystemModuleName(AssemblyName name)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
   
   It doesn't seem to matter if I give it the x86 or 64-bit program files base. It doesn't seem to accept the mscorlib dll in ANY of the runtime folders.

**Comment by jkotas** [comment]
> ILVerify.exe myTarget.dll -r "c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.9*.dll"

`c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App` is ASP.NET Core only. It does not contain mscorlib. Try running `ILVerify.exe  myTarget.dll -r "c:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\*.dll"` instead.

**Comment by zachrybaker** [comment]
Wow totally missed that I was referencing asp there!Sent from my iPhoneOn Apr 5, 2023, at 2:46 PM, Jan Kotas ***@***.***> wrote:﻿

ILVerify.exe myTarget.dll -r "c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.9*.dll"

c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App is ASP.NET Core only. It does not contain mscorlib. Try running ILVerify.exe  myTarget.dll -r "c:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.14\*.dll" instead.

**Comment by ForNeVeR** [comment]
ILVerify 8 now just outright throws NRE if called without `-r`:
```console
$ ilverify.exe .\EntryPoint.dll
Error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILVerify.Program.Resolve(String simpleName)
   at ILVerify.Program.ILVerify.IResolver.ResolveAssembly(AssemblyName assemblyName)
   at ILVerify.Verifier.SetSystemModuleName(AssemblyName name)
   at ILVerify.Program.Run()
   at ILVerify.ILVerifyRootCommand.<.ctor>b__40_0(ParseResult result)
```

If called with `-r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\*.dll"` then it works.

I wonder if we could just make it use the SDK references by default (either from the SDK that ILVerify itself is using, or taken from the `.runtimeconfig` of the inspected assembly, if available).
