### ISSUE TITLE
[wasm][websocket] CloseAsync_CancelableEvenWhenPendingReceive_Throws

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#54153]
in `System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CancelableEvenWhenPendingReceive_Throws` in Browser on windows.

```
[FAIL] System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CancelableEvenWhenPendingReceive_Throws
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)
   at System.Net.WebSockets.Client.Tests.CloseTest.<>c__DisplayClass14_0.<<CloseAsync_CancelableEvenWhenPendingReceive_Throws>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\System.Net.WebSockets.Client\tests\CloseTest.cs:line 394
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass16_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 123
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 105
   at System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CancelableEvenWhenPendingReceive_Throws() in C:\Dev\runtime\src\libraries\System.Net.WebSockets.Client\tests\CloseTest.cs:line 382
```

**Comment by lewing** [comment]
This is a definite difference in behavior but it isn't near critical path for NET6

**Comment by pavelsavara** [comment]
I confirmed this still happens with latest code for Net7, moving to Future.

**Comment by pavelsavara** [comment]
@CarnaViire I can see this now also on windows. Maybe that's a problem of the test ? Something is too slow or fast ?

[Log](https://helixr18s23ayyejvk1x8qcc.blob.core.windows.net/dotnet-runtime-refs-pull-133128-merge-5af982fcf44a44bd86/System.Net.WebSockets.Tests/1/console.8afff70f.log?helixlogtype=result)
```
C:\h\w\B87809BC\w\BFBD0A81\e>"C:\h\w\B87809BC\p\dotnet.exe" exec --runtimeconfig System.Net.WebSockets.Tests.runtimeconfig.json --depsfile System.Net.WebSockets.Tests.deps.json xunit.console.dll System.Net.WebSockets.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.WebSockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.WebSockets.Tests (found 155 of 165 test cases)
  Starting:    System.Net.WebSockets.Tests (parallel test collections = on [4 threads], stop on fail = off)
    System.Net.WebSockets.Tests.WebSocketCloseTests.CloseAsync_CancelableEvenWhenPendingReceive_Throws [FAIL]
      Assert.ThrowsAny() Failure: No exception was thrown
      Expected: typeof(System.OperationCanceledException)
      Stack Trace:
        /_/src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeAsyncTaskContinuation.cs(139,0): at System.Runtime.CompilerServices.RuntimeAsyncTaskContinuation.GetResult[T](Task task, Byte& result)
        /_/src/libraries/System.Net.WebSockets/tests/WebSocketCloseTests.cs(98,0): at System.Net.WebSockets.Tests.WebSocketCloseTests.CloseAsync_CancelableEvenWhenPendingReceive_Throws()
```
