### ISSUE TITLE
[wasm] System.Runtime.InteropServices.JavaScript.JSException: Invalid JS object handle '17'

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#54152]
In unit test `System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_CancellationRequestedAfterConnect_ThrowsOperationCanceledException` on Browser on windows, with remote loopback in xharness.

```
Unhandled Exception:
System.Runtime.InteropServices.JavaScript.JSException: Invalid JS object handle '17'
    at System.Runtime.InteropServices.JavaScript.JSObject.GetObjectProperty(String name) in C:\\Dev\\runtime\\src\\libraries\\System.Private.Runtime.InteropServices.JavaScript\\src\\System\\Runtime\\InteropServices\\JavaScript\\JSObject.cs:line 105
    at System.Net.WebSockets.BrowserWebSocket.CloseAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken) in C:\\Dev\\runtime\\src\\libraries\\System.Net.WebSockets.Client\\src\\System\\Net\\WebSockets\\BrowserWebSockets\\BrowserWebSocket.cs:line 577
--- End of stack trace from previous location ---
    at System.Net.WebSockets.BrowserWebSocket.AbortRequest() in C:\\Dev\\runtime\\src\\libraries\\System.Net.WebSockets.Client\\src\\System\\Net\\WebSockets\\BrowserWebSockets\\BrowserWebSocket.cs:line 377
```

**Comment by pavelsavara** [comment]
```
  Unhandled Exception:
  System.Runtime.InteropServices.JavaScript.JSException: Invalid JS object handle '1'
     at System.Runtime.InteropServices.JavaScript.JSObject.GetObjectProperty(String name)
     at System.Net.WebSockets.BrowserWebSocket.CloseAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
  --- End of stack trace from previous location ---
     at System.Net.WebSockets.BrowserWebSocket.AbortRequest()
     at System.Threading.Tasks.Task.\u003C>c.\u003CThrowAsync>b__140_1(Object state)
     at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading.ThreadPool.Callback()
  ThreadPool Callback threw an unhandled exception of type System.Runtime.InteropServices.JavaScript.JSException
```
