### ISSUE TITLE
[wasm][http] System.Net.Http.Functional.Tests should throw HttpRequestException

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#54160]
## GetAsync_InvalidHeaderNameValue_ThrowsHttpRequestException

```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   (No exception was thrown)
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass16_0.<<GetAsync_InvalidHeaderNameValue_ThrowsHttpRequestException>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 356
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass16_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 126
```

## GetAsync_IncompleteData_ThrowsHttpRequestException

```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   (No exception was thrown)
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass17_0.<<GetAsync_IncompleteData_ThrowsHttpRequestException>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 387
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass16_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 126
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 104
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_IncompleteData_ThrowsHttpRequestException(Boolean failDuringHeaders, Boolean getString) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 380

```

## GetAsync_StatusCodeOutOfRange_ExpectedException

```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   (No exception was thrown)
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass30_0.<<GetAsync_StatusCodeOutOfRange_ExpectedException>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 1280
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 104
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_StatusCodeOutOfRange_ExpectedException(Int32 statusCode) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 1268
```

## PostAsync_ThrowFromContentCopy_RequestFails

```
Assert.Throws() Failure
Expected: typeof(System.FormatException)
Actual:   typeof(System.Net.Http.HttpRequestException): One of the identified items was in an invalid format.
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 332
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
----- Inner Stack Trace -----
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 332
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
----- Inner Stack Trace -----
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass40_3.<PostAsync_ThrowFromContentCopy_RequestFails>b__8(Task _) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 1693
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke() in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\TaskContinuation.cs:line 88
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 2369
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ExecutionContext.cs:line 268
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ExecutionContext.cs:line 293
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 2331
--- End of stack trace from previous location ---
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\IO\Stream.cs:line 108
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 543
   at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__84`2[[System.Net.Http.HttpContent, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 845
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 191]]>
```

## GetAsync_NonTraditionalChunkSizes_Accepted

```
System.Net.Http.HttpRequestException : TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 414
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 428
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 543
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 82
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 49
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<GetAsync_NonTraditionalChunkSizes_Accepted>b__21_0(LoopbackServer server, Uri url) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 730
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 104
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_NonTraditionalChunkSizes_Accepted() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\HttpClientHandlerTest.cs:line 725
```

## `SendAsync_Expect100Continue_RequestBodyFails_ThrowsContentException`

```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.Functional.Tests.ThrowingContentException)
Actual:   typeof(System.Net.Http.HttpRequestException): Exception of type 'System.Net.Http.Functional.Tests.ThrowingContentException' was thrown.
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 332
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
----- Inner Stack Trace -----
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 332
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
----- Inner Stack Trace -----
   at System.Net.Http.Functional.Tests.ThrowingContent.SerializeToStreamAsync(Stream stream, TransportContext context) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\ThrowingContent.cs:line 26
   at System.Net.Http.HttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 355
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 521
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 501
   at System.Net.Http.HttpContent.ReadAsByteArrayAsync(CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 243
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 191]]
```

## `System.Net.Http.Functional.Tests.SocketsHttpHandler_ResponseStreamTest.ReadAsStreamAsync_InvalidServerResponse_ThrowsIOException`

```
Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   typeof(System.Net.Http.HttpRequestException): TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 328
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
   at System.Net.Http.Functional.Tests.ResponseStreamTest.ReadAsStreamHelper(Uri serverUri) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\ResponseStreamTest.cs:line 361
----- Inner Stack Trace -----
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 328
```

## `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.SendAsync_WithZeroLengthHeaderName_Throws`

```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   (No exception was thrown
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.<SendAsync_WithZeroLengthHeaderName_Throws>b__16_0(Uri uri) in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Headers.cs:line 410
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 63
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 82
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\GenericLoopbackServer.cs:line 38
```

## `System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_InvalidCharactersInHeader_Throw`
```
System.TimeoutException : The operation has timed out.
```

## `System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.GetAsync_InvalidChunkTerminator_ThrowsHttpRequestException`
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.Runtime.InteropServices.JavaScript.JSException): TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 395
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 417
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 543
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
----- Inner Stack Trace -----
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 395
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 417
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 543
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
```

## `System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.GetAsync_InfiniteChunkSize_ThrowsHttpRequestException`
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.Runtime.InteropServices.JavaScript.JSException): TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 395
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 417
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 543
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
----- Inner Stack Trace -----
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 395
   at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 417
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 543
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 542
```

**Comment by lewing** [comment]
Several of these look like they are failing because the browser silently ignores the invalid value?
