### ISSUE TITLE
Test failure System.IO.Tests.DirectoryInfo_GetFileSystemInfos_str.PatternTests_DosDotTrailingDot(pattern: \"foo.?\", sourceFiles: [\"foo\", \"foo.\", \"foo.t\", \"foo.tx\", \"foo.txt\", ...], expected: [\"foo\", \"foo.\", \"foo.t\"])

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54258]
Run: [runtime 20210615.86](https://dev.azure.com/dnceng/public/_build/results?buildId=1188717&view=ms.vss-test-web.build-test-results-tab&runId=35704450&resultId=131894&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm64-Mono_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673

- System.IO.Tests.DirectoryInfo_GetFileSystemInfos_str.PatternTests_DosDotTrailingDot(pattern: \"foo.?\", sourceFiles: [\"foo\", \"foo.\", \"foo.t\", \"foo.tx\", \"foo.txt\", ...], expected: [\"foo\", \"foo.\", \"foo.t\"])

```
**Error message:**
```
System.UnauthorizedAccessException : Access to the path '/tmp/DirectoryInfo_GetFileSystemInfos_str_jqnpwbzw.etr/PrepareDirectory_539_777b29c6' is denied.
---- System.IO.IOException : Bad file descriptor


Stack trace
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.IO.FileSystemInfo, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:line 197
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.IO.FileSystemInfo, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:line 110
   at System.Collections.Generic.List`1[[System.IO.FileSystemInfo, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(IEnumerable`1 collection) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs:line 85
   at System.IO.DirectoryInfo.GetFileSystemInfos(String searchPattern, EnumerationOptions enumerationOptions) in /_/src/libraries/System.Private.CoreLib/src/System/IO/DirectoryInfo.cs:line 124
   at System.IO.DirectoryInfo.GetFileSystemInfos(String searchPattern) in /_/src/libraries/System.Private.CoreLib/src/System/IO/DirectoryInfo.cs:line 118
   at System.IO.Tests.DirectoryInfo_GetFileSystemInfos_str.GetEntries(String path, String searchPattern) in /_/src/libraries/System.IO.FileSystem/tests/DirectoryInfo/GetFileSystemInfos.cs:line 26
   at System.IO.Tests.Directory_GetFileSystemEntries_str_str.PatternTests_DosDotTrailingDot(String pattern, String[] sourceFiles, String[] expected) in /_/src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:line 343
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
----- Inner Stack Trace -----
```

**Comment by danmoseley** [comment]
I'll dupe against https://github.com/dotnet/runtime/issues/54589 since I put the query in there.
