### ISSUE TITLE
[wasm][http] System.Net.Http.Functional.Tests.HttpClientTest - Expected: System.Threading.Tasks.TaskCanceledException

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#54270]
Unit tests:
- `GetStreamAsync_CanBeCanceled_AlreadyCanceledCts`
- `GetStringAsync_CanBeCanceled`
- `GetStreamAsync_CanBeCanceled`
- `GetByteArrayAsync_CanBeCanceled`
- `GetByteArrayAsync_CanBeCanceled_AlreadyCanceledCts`
- `GetStringAsync_CanBeCanceled_AlreadyCanceledCts`

```
Assert.Throws() Failure
Expected: typeof(System.Threading.Tasks.TaskCanceledException)
Actual:   typeof(System.OperationCanceledException): The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 618
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 217
----- Inner Stack Trace -----
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 618
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 217
```

Test `System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled`
```
 Assert.Throws() Failure
 Expected: typeof(System.Threading.Tasks.TaskCanceledException)
 Actual:   typeof(System.ObjectDisposedException): The CancellationTokenSource has been disposed.
 ---- System.ObjectDisposedException : The CancellationTokenSource has been disposed.
    at System.Threading.CancellationTokenSource.ThrowIfDisposed() in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\CancellationTokenSource.cs:line 485
    at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\CancellationTokenSource.cs:line 249
    at System.Threading.CancellationTokenSource.Cancel() in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\CancellationTokenSource.cs:line 221
    at System.Net.Http.BrowserHttpHandler.WasmFetchResponse.Dispose() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 369
    at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.Dispose(Boolean disposing) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 434
    at System.Net.Http.HttpContent.Dispose() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 689
    at System.Net.Http.HttpResponseMessage.Dispose(Boolean disposing) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpResponseMessage.cs:line 235
    at System.Net.Http.HttpResponseMessage.Dispose() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpResponseMessage.cs:line 242
    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 583
    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 217
    at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_1.<<GetAsync_ContentCanBeCanceled>b__2>d.MoveNext() in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientTest.cs:line 467
 --- End of stack trace from previous location ---
 ----- Inner Stack Trace -----
    at System.Threading.CancellationTokenSource.ThrowIfDisposed() in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\CancellationTokenSource.cs:line 485
    at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\CancellationTokenSource.cs:line 249
    at System.Threading.CancellationTokenSource.Cancel() in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\CancellationTokenSource.cs:line 221
    at System.Net.Http.BrowserHttpHandler.WasmFetchResponse.Dispose() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 369
    at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.Dispose(Boolean disposing) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\BrowserHttpHandler\BrowserHttpHandler.cs:line 434
    at System.Net.Http.HttpContent.Dispose() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpContent.cs:line 689
    at System.Net.Http.HttpResponseMessage.Dispose(Boolean disposing) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpResponseMessage.cs:line 235
    at System.Net.Http.HttpResponseMessage.Dispose() in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpResponseMessage.cs:line 242
    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 583
    at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 217
    at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_1.<<GetAsync_ContentCanBeCanceled>b__2>d.MoveNext() in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientTest.cs:line 467
```

**Comment by danmoseley** [comment]
Curious why the inner exception stack is identical, or whether ToString() is doing something wrong.
