### ISSUE TITLE
System.IO.Tests.Directory_EnumFiles_str_str.SearchPatternLongPath failing on CI with UnauthorizedException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54329]
Configuration: `net6.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open`

```
System.UnauthorizedAccessException : Access to the path '/var/folders/jx/8b1hb4vd5rx3vxkm4gz9kck00000gy/T/Directory_EnumFiles_str_str_mlcmea1d.4ka/SearchPatternLongPath_587_1e306b38' is denied.
---- System.IO.IOException : Bad file descriptor
 at System.IO.Enumeration.FileSystemEnumerator`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:line 197
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:line 110
   at System.Collections.Generic.LargeArrayBuilder`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(IEnumerable`1 items) in /_/src/libraries/Common/src/System/Collections/Generic/LargeArrayBuilder.SpeedOpt.cs:line 116
   at System.Collections.Generic.EnumerableHelpers.ToArray[String](IEnumerable`1 source) in /_/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.Linq.cs:line 84
   at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source) in /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs:line 17
   at System.IO.Tests.Directory_EnumFiles_str_str.GetEntries(String path, String searchPattern) in /_/src/libraries/System.IO.FileSystem/tests/Directory/EnumerableAPIs.cs:line 29
   at System.IO.Tests.Directory_GetFileSystemEntries_str_str.SearchPatternLongPath() in /_/src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:line 601
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
----- Inner Stack Trace -----
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1191788&view=ms.vss-test-web.build-test-results-tab&runId=35771342&paneView=debug&resultId=125787

**Comment by adamsitnik** [comment]
Fixed by @danmoseley in https://github.com/dotnet/runtime/pull/54660
