### ISSUE TITLE
[MONO][Interp] JIT/CodeGenBringUpTests/Localloc_* failed with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54359]
Here is the error message:

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.CodeGenBringUpTests/console.692cbdf5.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
06-17 16:44:14.025 10123 10141 I DOTNET  : MonoRunner initialize,, entryPointLibName=Localloc_d.dll
      06-17 16:44:14.025 10123 10141 D DOTNET  : file_path: /data/user/0/net.dot.JIT_CodeGenBringUpTests/files/runtimeconfig.bin
      06-17 16:44:14.026 10123 10141 D DOTNET  : Interp Enabled
      06-17 16:44:14.028 10123 10141 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_CodeGenBringUpTests/files
      06-17 16:44:14.070 10123 10141 D DOTNET  : assembly_preload_hook: Localloc_d.dll (null) /data/user/0/net.dot.JIT_CodeGenBringUpTests/files
      06-17 16:44:14.072 10123 10141 D DOTNET  : Executable: Localloc_d.dll
      06-17 16:44:14.072 10123 10141 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_CodeGenBringUpTests/files
      06-17 16:44:14.073 10123 10141 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_CodeGenBringUpTests/files
      06-17 16:44:14.074 10123 10141 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_CodeGenBringUpTests/files
      06-17 16:44:14.119 10123 10141 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_CodeGenBringUpTests/files
      06-17 16:44:14.125 10123 10141 I DOTNET  : 1
      06-17 16:44:14.125 10123 10141 I DOTNET  : 
      06-17 16:44:14.125 10123 10141 I DOTNET  : 2
      06-17 16:44:14.125 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 3
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 4
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 1
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 2
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 3
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 4
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 5
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 6
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 7
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 8
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 9
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 10
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 11
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 12
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.126 10123 10141 I DOTNET  : 13
      06-17 16:44:14.126 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 14
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 15
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 16
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 17
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 18
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 19
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 20
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 21
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 22
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 23
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 I DOTNET  : 24
      06-17 16:44:14.127 10123 10141 I DOTNET  : 
      06-17 16:44:14.127 10123 10141 D DOTNET  : Exit code: -1.
      06-17 16:44:14.149 10123 10141 I DOTNET  : MonoRunner finished, return-code=-1
      06-17 16:44:14.150  1793  2133 I ActivityManager: Force stopping net.dot.JIT_CodeGenBringUpTests appid=10154 user=0: finished inst
      06-17 16:44:14.153  1793  8196 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:44:14.153  1793  8196 W Binder  : java.lang.Throwable
      06-17 16:44:14.153  1793  8196 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:44:14.153  1793  8196 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:44:14.153  1793  8196 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:44:14.155 10113 10113 D AndroidRuntime: Shutting down VM
      06-17 16:44:14.167  1793  2133 I ActivityManager: Killing 10123:net.dot.JIT_CodeGenBringUpTests/u0a154 (adj 0): stop net.dot.JIT_CodeGenBringUpTests
      06-17 16:44:14.179 10113 10144 W app_process: Thread attaching while runtime is shutting down: Binder:10113_3
      06-17 16:44:14.179 10113 10144 I AndroidRuntime: NOTE: attach of thread 'Binder:10113_3' failed
      06-17 16:44:14.196  1534  1534 I Zygote  : Process 10123 exited due to signal 9 (Killed)
      06-17 16:44:14.213  1793  1820 I libprocessgroup: Successfully killed process cgroup uid 10154 pid 10123 in 44ms
```

**Comment by SamMonoRT** [comment]
Assigning for accurate tracking and triaging
