### ISSUE TITLE
[MONO][Interp] function call tests failed with SEGV with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54374]
Failed tests list:

- JIT/Directed/tailcall/tailcall/tailcall.sh
- JIT/Methodical/VT/callconv/_il_reljumper3/_il_reljumper3.sh
- Regressions/coreclr/22386/debug3/debug3.sh

Here is the error message:

[JIT/Directed/* full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Directed/console.850ee7bc.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)
[JIT/Methodical/* full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Methodical/console.d471468f.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)
[Regressions/coreclr/* full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/PayloadGroup0/console.03aff470.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
06-17 17:03:36.303 17347 17365 I DOTNET  : MonoRunner initialize,, entryPointLibName=tailcall.dll
      06-17 17:03:36.303 17347 17365 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Directed/files/runtimeconfig.bin
      06-17 17:03:36.303 17347 17365 D DOTNET  : Interp Enabled
      06-17 17:03:36.306 17347 17365 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.339 17347 17365 D DOTNET  : assembly_preload_hook: tailcall.dll (null) /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.339 17347 17365 D DOTNET  : Executable: tailcall.dll
      06-17 17:03:36.339 17347 17365 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.340 17347 17365 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.340 17347 17365 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.341 17347 17365 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.363 17347 17365 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_Directed/files
      06-17 17:03:36.366 17347 17365 I DOTNET  : Test Start
      06-17 17:03:36.367 17347 17365 D DOTNET  : assembly_preload_hook: System.Runtime.Extensions  /data/user/0/net.dot.JIT_Directed/files
      --------- beginning of crash
      06-17 17:03:36.370 17347 17365 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x75850e7a2ff8 in tid 17365 (.dot.MonoRunner), pid 17347 (ot.JIT_Directed)
      06-17 17:03:36.386 17370 17370 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
      06-17 17:03:36.386  1596  1596 I /system/bin/tombstoned: received crash request for pid 17365
      06-17 17:03:36.386 17370 17370 I crash_dump64: performing dump of process 17347 (target tid = 17365)
      06-17 17:03:36.390 17370 17370 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
      06-17 17:03:36.390 17370 17370 F DEBUG   : Build fingerprint: 'Android/sdk_phone_x86_64/generic_x86_64:10/QPP6.190730.005.B1/5775370:userdebug/test-keys'
      06-17 17:03:36.390 17370 17370 F DEBUG   : Revision: '0'
      06-17 17:03:36.390 17370 17370 F DEBUG   : ABI: 'x86_64'
      06-17 17:03:36.390 17370 17370 F DEBUG   : Timestamp: 2021-06-17 17:03:36+0000
      06-17 17:03:36.390 17370 17370 F DEBUG   : pid: 17347, tid: 17365, name: .dot.MonoRunner  >>> net.dot.JIT_Directed <<<
      06-17 17:03:36.391 17370 17370 F DEBUG   : uid: 10110
      06-17 17:03:36.391 17370 17370 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x75850e7a2ff8
      06-17 17:03:36.391 17370 17370 F DEBUG   :     rax 000075850ec3d954  rbx 0000000000000014  rcx 0000000000000001  rdx 000075850e8a6060
      06-17 17:03:36.391 17370 17370 F DEBUG   :     r8  00007585e9882be8  r9  000075850cac0136  r10 00007585e9882c10  r11 0000000000000000
      06-17 17:03:36.391 17370 17370 F DEBUG   :     r12 0000000000000014  r13 000075850e68e458  r14 000075850caee520  r15 00007585e9899700
      06-17 17:03:36.391 17370 17370 F DEBUG   :     rdi 0000000080000013  rsi 0000000000000014
      06-17 17:03:36.391 17370 17370 F DEBUG   :     rbp 000075850e8a2ae0  rsp 000075850e7a3000  rip 000075850e9b659a
      06-17 17:03:36.616 17370 17370 F DEBUG   : 
      06-17 17:03:36.616 17370 17370 F DEBUG   : backtrace:
      06-17 17:03:36.616 17370 17370 F DEBUG   :       #00 pc 000000000010c59a  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.616 17370 17370 F DEBUG   :       #01 pc 000000000010c8a8  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #02 pc 00000000000ddfd5  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #03 pc 00000000002577cf  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #04 pc 000000000024d6a7  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #05 pc 0000000000164acc  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #06 pc 0000000000093aa7  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #07 pc 0000000000099b9a  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #08 pc 00000000001b675b  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonosgen-2.0.so (mono_jit_exec+331) (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #09 pc 0000000000001d7f  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonodroid.so (mono_droid_runtime_init+540) (BuildId: fe77d42b65eddb4d787d5caa705e079f15611d57)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #10 pc 0000000000002421  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/lib/x86_64/libmonodroid.so (Java_net_dot_MonoRunner_initRuntime+426) (BuildId: fe77d42b65eddb4d787d5caa705e079f15611d57)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #11 pc 0000000000002183  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/oat/x86_64/base.odex (art_jni_trampoline+371)
      06-17 17:03:36.618 17370 17370 F DEBUG   :       #12 pc 00000000001696b6  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+806) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #13 pc 0000000000179c61  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+305) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #14 pc 0000000000340ffc  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+380) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #15 pc 000000000033b20f  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1151) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #16 pc 000000000066c545  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+677) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #17 pc 0000000000162999  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+25) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #18 pc 0000000000000aba  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/oat/x86_64/base.vdex (net.dot.MonoRunner.initialize+98)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #19 pc 000000000066c86d  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1485) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #20 pc 0000000000162999  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+25) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #21 pc 0000000000000d60  /data/app/net.dot.JIT_Directed-8zaiVkSbhzzuLDpOjyXotg==/oat/x86_64/base.vdex (net.dot.MonoRunner.onStart+60)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #22 pc 00000000006692dd  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1789) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #23 pc 0000000000162819  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+25) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #24 pc 00000000001edea6  /system/framework/framework.jar (android.app.Instrumentation$InstrumentationThread.run+94)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #25 pc 000000000030dcad  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.13960599661070883162+253) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #26 pc 000000000065854a  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1210) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #27 pc 00000000001747cc  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+140) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #28 pc 0000000000169354  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+756) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #29 pc 0000000000179c50  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+288) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #30 pc 0000000000549d29  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+89) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #31 pc 000000000054afc5  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+437) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #32 pc 00000000005a0a7e  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1438) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #33 pc 0000000000100fce  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+30) (BuildId: a08a19770d6696739c847e29c3f5f650)
      06-17 17:03:36.619 17370 17370 F DEBUG   :       #34 pc 0000000000098fe7  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+55) (BuildId: a08a19770d6696739c847e29c3f5f650)
      06-17 17:03:37.867  1596  1596 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
      06-17 17:03:37.878  1536  1536 I Zygote  : Process 17347 exited due to signal 11 (Segmentation fault)
      06-17 17:03:37.889  1792  1823 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
      06-17 17:03:37.889  1792  1823 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
      06-17 17:03:37.897  1792  6219 I ActivityManager: Process net.dot.JIT_Directed (pid 17347) has died: fore FGS 
      06-17 17:03:37.897  1792  1819 I libprocessgroup: Successfully killed process cgroup uid 10110 pid 17347 in 0ms
      06-17 17:03:37.900  1792  6219 W ActivityManager: Crash of app net.dot.JIT_Directed running instrumentation ComponentInfo{net.dot.JIT_Directed/net.dot.MonoRunner}
      06-17 17:03:37.900  1792  6219 I ActivityManager: Force stopping net.dot.JIT_Directed appid=10110 user=0: finished inst
      06-17 17:03:37.900  1792 13172 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 17:03:37.900  1792 13172 W Binder  : java.lang.Throwable
      06-17 17:03:37.900  1792 13172 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 17:03:37.900  1792 13172 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 17:03:37.900  1792 13172 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 17:03:37.903 17337 17337 D AndroidRuntime: Shutting down VM
      06-17 17:03:37.924  1792 17380 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
```

**Comment by BrzVlad** [comment]
These are IL tests, I don't think they represent the highest priority for .NET 6
