### ISSUE TITLE
[MONO][Interp] JIT/IL_Conformance/* tests failed return the correct return code with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54376]
Failed tests list:

- JIT/IL_Conformance/Old/Base/ckfinite/ckfinite.sh
- JIT/IL_Conformance/Old/Conformance_Base/add_r4/add_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/ckfinite_r4/ckfinite_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/div_r4/div_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/ldc_ckfinite_r4/ldc_ckfinite_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/mul_r4/mul_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/neg_r4/neg_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/rem_r4/rem_r4.sh
- JIT/IL_Conformance/Old/Conformance_Base/sub_r4/sub_r4.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.IL_Conformance/console.faf36407.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

Error message:

```
06-17 16:46:12.048  7416  7434 I DOTNET  : MonoRunner initialize,, entryPointLibName=ckfinite.dll
      06-17 16:46:12.048  7416  7434 D DOTNET  : file_path: /data/user/0/net.dot.JIT_IL_Conformance/files/runtimeconfig.bin
      06-17 16:46:12.048  7416  7434 D DOTNET  : Interp Enabled
      06-17 16:46:12.050  7416  7434 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_IL_Conformance/files
      06-17 16:46:12.086  7416  7434 D DOTNET  : assembly_preload_hook: ckfinite.dll (null) /data/user/0/net.dot.JIT_IL_Conformance/files
      06-17 16:46:12.086  7416  7434 D DOTNET  : Executable: ckfinite.dll
      06-17 16:46:12.086  7416  7434 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_IL_Conformance/files
      06-17 16:46:12.087  7416  7434 D DOTNET  : Exit code: 0.
      06-17 16:46:12.100  7416  7434 I DOTNET  : MonoRunner finished, return-code=0
      06-17 16:46:12.102  1797  3117 I ActivityManager: Force stopping net.dot.JIT_IL_Conformance appid=10119 user=0: finished inst
      06-17 16:46:12.102  1797  3117 I ActivityManager: Killing 7416:net.dot.JIT_IL_Conformance/u0a119 (adj 0): stop net.dot.JIT_IL_Conformance
      06-17 16:46:12.102  1797  7393 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:46:12.102  1797  7393 W Binder  : java.lang.Throwable
      06-17 16:46:12.102  1797  7393 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:46:12.102  1797  7393 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:46:12.102  1797  7393 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:46:12.111  7406  7406 D AndroidRuntime: Shutting down VM
      06-17 16:46:12.115  1544  1544 I Zygote  : Process 7416 exited due to signal 9 (Killed)
      06-17 16:46:12.130  1797  7393 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{net.dot.JIT_IL_Conformance/net.dot.MonoRunner} results=Bundle[mParcelledData.dataSize=40]
      06-17 16:46:12.148  1797  1826 I libprocessgroup: Successfully killed process cgroup uid 10119 pid 7416 in 45ms
```

**Comment by am11** [comment]
Not sure if call to std lib's `isinfinity()` the right thing mono is currently using (for interpreter as well as jit?), but going by coreclr/jit, ckfinite emulation in C is essentially: https://godbolt.org/z/vxMYrvb8d. "exponent bits all-ON" check takes care of both; isInfinity and isNaN.
cc @lambdageek
