### ISSUE TITLE
[MONO][Android][Interp] JIT/Methodical/* test failed with unhandled exception on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54388]
Failed tests list:

- JIT/Methodical/Boxing/boxunbox/_il_dbghuge_filter/_il_dbghuge_filter.sh
- JIT/Methodical/Boxing/boxunbox/_il_dbgtailcall/_il_dbgtailcall.sh
- JIT/Methodical/Boxing/boxunbox/_il_relhuge_filter/_il_relhuge_filter.sh
- JIT/Methodical/Boxing/boxunbox/_il_reltailcall/_il_reltailcall.sh
- JIT/Methodical/Coverage/b39946/b39946.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Methodical.a-dA-D/console.8bb65394.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
      06-17 16:55:33.571 11662 11679 E mono    : Unhandled Exception:
      06-17 16:55:33.571 11662 11679 E mono    : System.ArgumentException: Value does not fall within the expected range.
      06-17 16:55:33.571 11662 11679 E mono    :    at JitTest.App.Test(Boolean path)
      06-17 16:55:33.571 11662 11679 E mono    :    at JitTest.App.Main()
      06-17 16:55:33.571 11662 11679 E DOTNET  : UnhandledException: System.ArgumentException Value does not fall within the expected range.    at JitTest.App.Test(Boolean path)
      06-17 16:55:33.571 11662 11679 E DOTNET  :    at JitTest.App.Main()
      06-17 16:55:33.611  1793  2593 I ActivityManager: Process net.dot.JIT_Methodical (pid 11662) has died: fore FGS 
      06-17 16:55:33.611  1793  2593 W ActivityManager: Crash of app net.dot.JIT_Methodical running instrumentation ComponentInfo{net.dot.JIT_Methodical/net.dot.MonoRunner}
      06-17 16:55:33.611  1793  2593 I ActivityManager: Force stopping net.dot.JIT_Methodical appid=10114 user=0: finished inst
      06-17 16:55:33.611  1793  8998 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:55:33.611  1793  8998 W Binder  : java.lang.Throwable
      06-17 16:55:33.611  1793  8998 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:55:33.611  1793  8998 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:55:33.611  1793  8998 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:55:33.612 11651 11651 D AndroidRuntime: Shutting down VM
      06-17 16:55:33.625  1535  1535 I Zygote  : Process 11662 exited cleanly (1)
      06-17 16:55:33.652  1793  1820 I libprocessgroup: Successfully killed process cgroup uid 10114 pid 11662 in 41ms
```

**Comment by SamMonoRT** [comment]
Assigning for accurate tracking and triaging
