### ISSUE TITLE
[MONO][Android][Interp] JIT/Methodical/* tests failed return the correct return code on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54382]
Failed tests list:

- JIT/Methodical/localloc/verify/verify01_dynamic/verify01_dynamic.sh
- JIT/Methodical/localloc/verify/verify01_large/verify01_large.sh
- JIT/Methodical/localloc/verify/verify01_small/verify01_small.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Methodical/console.d471468f.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

Error message:
```
06-17 16:43:01.203  6749  6767 I DOTNET  : MonoRunner initialize,, entryPointLibName=verify01_dynamic.dll
      06-17 16:43:01.204  6749  6767 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Methodical/files/runtimeconfig.bin
      06-17 16:43:01.204  6749  6767 D DOTNET  : Interp Enabled
      06-17 16:43:01.205  6749  6767 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.232  6749  6767 D DOTNET  : assembly_preload_hook: verify01_dynamic.dll (null) /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.232  6749  6767 D DOTNET  : Executable: verify01_dynamic.dll
      06-17 16:43:01.232  6749  6767 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.232  6749  6767 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.232  6749  6767 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.233  6749  6767 D DOTNET  : ((null) warning) CEE_LOCALLOC: stack not empty
      06-17 16:43:01.233  6749  6767 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.238  6749  6767 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:43:01.242  6749  6767 I DOTNET  : Failed
      06-17 16:43:01.242  6749  6767 D DOTNET  : Exit code: 1.
      06-17 16:43:01.246  6749  6767 I DOTNET  : MonoRunner finished, return-code=1
      06-17 16:43:01.247  1788  1803 I ActivityManager: Force stopping net.dot.JIT_Methodical appid=10135 user=0: finished inst
      06-17 16:43:01.247  1788  1803 I ActivityManager: Killing 6749:net.dot.JIT_Methodical/u0a135 (adj 0): stop net.dot.JIT_Methodical
      06-17 16:43:01.247  1788  6682 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:43:01.247  1788  6682 W Binder  : java.lang.Throwable
      06-17 16:43:01.247  1788  6682 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:43:01.247  1788  6682 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:43:01.247  1788  6682 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:43:01.248  6739  6739 D AndroidRuntime: Shutting down VM
      06-17 16:43:01.290  1534  1534 I Zygote  : Process 6749 exited due to signal 9 (Killed)
      06-17 16:43:01.330  1788  1816 I libprocessgroup: Successfully killed process cgroup uid 10135 pid 6749 in 82ms
```

**Comment by SamMonoRT** [comment]
Assigning for accurate tracking and triaging
