### ISSUE TITLE
[MONO][Android][Interp] JIT/Regression/* failed return the correct return code on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54392]
Failed tests list:

- JIT/Regression/CLR-x86-JIT/V1.2-M01/b13452/b13452/b13452.sh
- JIT/Regression/JitBlue/DevDiv_405852/DevDiv_405852/DevDiv_405852.sh
- JIT/Regression/JitBlue/GitHub_24846/GitHub_24846/GitHub_24846.sh
- JIT/Regression/VS-ia64-JIT/M00/b109878/b109878/b109878.sh
- JIT/Regression/VS-ia64-JIT/M00/b92726/b92726/b92726.sh

[full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Regression/console.ac1fbdb7.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
      06-17 16:49:00.402  8772  8791 I DOTNET  : MonoRunner initialize,, entryPointLibName=b13452.dll
      06-17 16:49:00.403  8772  8791 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Regression/files/runtimeconfig.bin
      06-17 16:49:00.403  8772  8791 D DOTNET  : Interp Enabled
      06-17 16:49:00.405  8772  8791 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Regression/files
      06-17 16:49:00.428  8772  8791 D DOTNET  : assembly_preload_hook: b13452.dll (null) /data/user/0/net.dot.JIT_Regression/files
      06-17 16:49:00.428  8772  8791 D DOTNET  : Executable: b13452.dll
      06-17 16:49:00.428  8772  8791 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Regression/files
      06-17 16:49:00.429  8772  8791 D DOTNET  : Exit code: 1.
      06-17 16:49:00.433  8772  8791 I DOTNET  : MonoRunner finished, return-code=1
      06-17 16:49:00.434  1792  7377 I ActivityManager: Force stopping net.dot.JIT_Regression appid=10114 user=0: finished inst
      06-17 16:49:00.434  1792  7377 I ActivityManager: Killing 8772:net.dot.JIT_Regression/u0a114 (adj 0): stop net.dot.JIT_Regression
      06-17 16:49:00.434  1792  8528 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:49:00.434  1792  8528 W Binder  : java.lang.Throwable
      06-17 16:49:00.434  1792  8528 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:49:00.434  1792  8528 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:49:00.434  1792  8528 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:49:00.435  8762  8762 D AndroidRuntime: Shutting down VM
      06-17 16:49:00.463  1535  1535 I Zygote  : Process 8772 exited due to signal 9 (Killed)
      06-17 16:49:00.478  1792  1820 I libprocessgroup: Successfully killed process cgroup uid 10114 pid 8772 in 43ms
```

```
06-17 17:16:15.390 30257 30275 I DOTNET  : MonoRunner initialize,, entryPointLibName=b109878.dll
      06-17 17:16:15.391 30257 30275 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Regression/files/runtimeconfig.bin
      06-17 17:16:15.391 30257 30275 D DOTNET  : Interp Enabled
      06-17 17:16:15.392 30257 30275 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Regression/files
      06-17 17:16:15.413 30257 30275 D DOTNET  : assembly_preload_hook: b109878.dll (null) /data/user/0/net.dot.JIT_Regression/files
      06-17 17:16:15.413 30257 30275 D DOTNET  : Executable: b109878.dll
      06-17 17:16:15.413 30257 30275 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Regression/files
      06-17 17:16:15.414 30257 30275 D DOTNET  : Exit code: 0.
      06-17 17:16:15.417 30257 30275 I DOTNET  : MonoRunner finished, return-code=0
      06-17 17:16:15.418  1792  7377 I ActivityManager: Force stopping net.dot.JIT_Regression appid=10114 user=0: finished inst
      06-17 17:16:15.418  1792  7377 I ActivityManager: Killing 30257:net.dot.JIT_Regression/u0a114 (adj 0): stop net.dot.JIT_Regression
      06-17 17:16:15.418  1792 30234 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 17:16:15.418  1792 30234 W Binder  : java.lang.Throwable
      06-17 17:16:15.418  1792 30234 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 17:16:15.418  1792 30234 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 17:16:15.418  1792 30234 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 17:16:15.419 30247 30247 D AndroidRuntime: Shutting down VM
      06-17 17:16:15.438  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.438  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.438  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.438  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.438  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.438  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.439  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.439  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.439  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.439  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.439  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.439  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.439  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.439  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.439  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.439  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.439  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.439  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.440  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.440  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.441  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.441  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.441  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.441  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.442  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.442  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.443  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.443  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.443  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.443  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.443  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.443  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.445  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.445  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.447  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.447  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.456  1535  1535 I Zygote  : Process 30257 exited due to signal 9 (Killed)
      06-17 17:16:15.456  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.456  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.458  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.458  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.459  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.459  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.461  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.461  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.462  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.462  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.463  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.463  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.464  1792  1820 I libprocessgroup: Successfully killed process cgroup uid 10114 pid 30257 in 45ms
      06-17 17:16:15.464  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.464  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.465  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.465  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.467  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.467  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
      06-17 17:16:15.469  1792  1817 E memtrack: Couldn't load memtrack module
      06-17 17:16:15.469  1792  1817 W android.os.Debug: failed to get memory consumption info: -1
```

**Comment by SamMonoRT** [comment]
Assigning for accurate tracking and triaging
