### ISSUE TITLE
[MONO][Interp]  Assertion at /__w/1/s/src/mono/mono/mini/interp/transform.c:4527, condition `td->sp >= td->stack' not met on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54395]
Fail tests list:

- JIT/jit64/localloc/ehverify/eh07_large/eh07_large.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.jit64/console.0629b13a.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
      06-17 16:43:41.916 12577 12595 I DOTNET  : MonoRunner initialize,, entryPointLibName=eh07_large.dll
      06-17 16:43:41.916 12577 12595 D DOTNET  : file_path: /data/user/0/net.dot.JIT_jit64/files/runtimeconfig.bin
      06-17 16:43:41.916 12577 12595 D DOTNET  : Interp Enabled
      06-17 16:43:41.918 12577 12595 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_jit64/files
      06-17 16:43:41.939 12577 12595 D DOTNET  : assembly_preload_hook: eh07_large.dll (null) /data/user/0/net.dot.JIT_jit64/files
      06-17 16:43:41.939 12577 12595 D DOTNET  : Executable: eh07_large.dll
      06-17 16:43:41.939 12577 12595 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_jit64/files
      06-17 16:43:41.940 12577 12595 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_jit64/files
      06-17 16:43:41.940 12577 12595 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_jit64/files
      06-17 16:43:41.940 12577 12595 D DOTNET  : ((null) warning) LocallocTest.func: not enough values (0 < 1) on stack at 0016
      06-17 16:43:41.940 12577 12595 D DOTNET  : ((null) error) * Assertion at /__w/1/s/src/mono/mono/mini/interp/transform.c:4527, condition `td->sp >= td->stack' not met
      06-17 16:43:41.940 12577 12595 E DOTNET  : Exit code: 1.
      06-17 16:43:41.967  1536  1536 I Zygote  : Process 12577 exited cleanly (1)
      06-17 16:43:41.967  1792  2649 I ActivityManager: Process net.dot.JIT_jit64 (pid 12577) has died: fore FGS 
      06-17 16:43:41.967  1792  1819 I libprocessgroup: Successfully killed process cgroup uid 10128 pid 12577 in 0ms
      06-17 16:43:41.968  1792  2649 W ActivityManager: Crash of app net.dot.JIT_jit64 running instrumentation ComponentInfo{net.dot.JIT_jit64/net.dot.MonoRunner}
      06-17 16:43:41.968  1792  2649 I ActivityManager: Force stopping net.dot.JIT_jit64 appid=10128 user=0: finished inst
      06-17 16:43:41.968  1792 12333 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:43:41.968  1792 12333 W Binder  : java.lang.Throwable
      06-17 16:43:41.968  1792 12333 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:43:41.968  1792 12333 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:43:41.968  1792 12333 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:43:41.969 12567 12567 D AndroidRuntime: Shutting down VM
```

**Comment by lambdageek** [comment]
Might be a dup of https://github.com/dotnet/runtime/issues/46622

**Comment by SamMonoRT** [comment]
Assigning for accurate tracking and triaging
