### ISSUE TITLE
[MONO][Android][Interp] Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/transform.c:5794 on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54391]
Failed tests list:

- JIT/Regression/JitBlue/DevDiv_362706/DevDiv_362706/DevDiv_362706.sh
- JIT/Regression/JitBlue/DevDiv_544983/DevDiv_544983/DevDiv_544983.sh
- JIT/Regression/JitBlue/DevDiv_605447/DevDiv_605447/DevDiv_605447.sh
- JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b309576/b309576/b309576.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Regression/console.ac1fbdb7.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
      06-17 16:53:04.753 11660 11677 I DOTNET  : MonoRunner initialize,, entryPointLibName=DevDiv_362706.dll
      06-17 16:53:04.753 11660 11677 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Regression/files/runtimeconfig.bin
      06-17 16:53:04.753 11660 11677 D DOTNET  : Interp Enabled
      06-17 16:53:04.756 11660 11677 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Regression/files
      06-17 16:53:04.777 11660 11677 D DOTNET  : assembly_preload_hook: DevDiv_362706.dll (null) /data/user/0/net.dot.JIT_Regression/files
      06-17 16:53:04.777 11660 11677 D DOTNET  : Executable: DevDiv_362706.dll
      06-17 16:53:04.777 11660 11677 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Regression/files
      06-17 16:53:04.778 11660 11677 D DOTNET  : ((null) warning) C.M: shift type mismatch 1
      06-17 16:53:04.778 11660 11677 D DOTNET  : ((null) error) * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/transform.c:5794
      06-17 16:53:04.778 11660 11677 E DOTNET  : Exit code: 1.
      06-17 16:53:04.835  1792  7381 I ActivityManager: Process net.dot.JIT_Regression (pid 11660) has died: fore FGS 
      06-17 16:53:04.837  1792  7381 W ActivityManager: Crash of app net.dot.JIT_Regression running instrumentation ComponentInfo{net.dot.JIT_Regression/net.dot.MonoRunner}
      06-17 16:53:04.837  1792 10529 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:53:04.837  1792 10529 W Binder  : java.lang.Throwable
      06-17 16:53:04.837  1792 10529 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:53:04.837  1792 10529 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:53:04.837  1792 10529 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:53:04.841  1792  7381 I ActivityManager: Force stopping net.dot.JIT_Regression appid=10114 user=0: finished inst
      06-17 16:53:04.844  1535  1535 I Zygote  : Process 11660 exited cleanly (1)
      06-17 16:53:04.845 11649 11649 D AndroidRuntime: Shutting down VM
      06-17 16:53:04.854 11649 11680 E app_process: Thread attaching to non-existent runtime: Binder:11649_3
      06-17 16:53:04.854 11649 11680 I AndroidRuntime: NOTE: attach of thread 'Binder:11649_3' failed
      06-17 16:53:04.862  1792 10529 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{net.dot.JIT_Regression/net.dot.MonoRunner} results=Bundle[{shortMsg=Process crashed.}]
      06-17 16:53:04.874  1792  1820 I libprocessgroup: Successfully killed process cgroup uid 10114 pid 11660 in 37ms
```

**Comment by BrzVlad** [comment]
Only `shift type mismatch` warning on `DevDiv_362706`
