### ISSUE TITLE
[MONO][Android][Interp] Loader/classloader/* tests failed on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54399]
Failed tests list:

- Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh
- Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_r/diamondshape_r.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/Loader.classloader/console.91afb0ea.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
      06-17 16:47:40.304  8650  8668 I DOTNET  : MonoRunner initialize,, entryPointLibName=diamondshape_d.dll
      06-17 16:47:40.304  8650  8668 D DOTNET  : file_path: /data/user/0/net.dot.Loader_classloader/files/runtimeconfig.bin
      06-17 16:47:40.304  8650  8668 D DOTNET  : Interp Enabled
      06-17 16:47:40.305  8650  8668 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.326  8650  8668 D DOTNET  : assembly_preload_hook: diamondshape_d.dll (null) /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.327  8650  8668 D DOTNET  : Executable: diamondshape_d.dll
      06-17 16:47:40.327  8650  8668 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.327  8650  8668 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.327  8650  8668 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.337  8650  8668 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.344  8650  8668 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.Loader_classloader/files
      06-17 16:47:40.346  8650  8668 I DOTNET  : Calling IFoo.Foo on Foo - expecting exception.
      06-17 16:47:40.346  8650  8668 I DOTNET  : At IFooEx.Foo
      06-17 16:47:40.346  8650  8668 I DOTNET  : FAIL: Expecting exception on Foo
      06-17 16:47:40.346  8650  8668 I DOTNET  : Calling I1.Func on I47Class - expecting exception
      06-17 16:47:40.346  8650  8668 I DOTNET  : At I6.Func
      06-17 16:47:40.346  8650  8668 I DOTNET  : FAIL: Expecting exception on I47Class
      06-17 16:47:40.346  8650  8668 I DOTNET  : Calling GI1<T>.Func on GI23Class<S> - expecting exception
      06-17 16:47:40.346  8650  8668 I DOTNET  : System.Object, System.String, GI3
      06-17 16:47:40.346  8650  8668 I DOTNET  : FAIL: Expecting exception on GI23Class
      06-17 16:47:40.346  8650  8668 I DOTNET  : Calling I1.Func on I4Class - expecting I4.Func
      06-17 16:47:40.346  8650  8668 I DOTNET  : At I4.Func
      06-17 16:47:40.346  8650  8668 I DOTNET  : PASS
      06-17 16:47:40.346  8650  8668 I DOTNET  : Calling I1.Func on I8Class - expecting I8.Func
      06-17 16:47:40.346  8650  8668 I DOTNET  : At I8.Func
      06-17 16:47:40.346  8650  8668 I DOTNET  : PASS
      06-17 16:47:40.346  8650  8668 I DOTNET  : Calling GI1.Func on GI4Class<object> - expecting GI4.Func<S>
      06-17 16:47:40.346  8650  8668 I DOTNET  : System.Object, System.String, GI4
      06-17 16:47:40.346  8650  8668 I DOTNET  : PASS
      06-17 16:47:40.346  8650  8668 I chatty  : uid=10128(net.dot.Loader_classloader) identical 1 line
      06-17 16:47:40.346  8650  8668 I DOTNET  : PASS
      06-17 16:47:40.346  8650  8668 D DOTNET  : Exit code: 101.
      06-17 16:47:40.350  8650  8668 I DOTNET  : MonoRunner finished, return-code=101
      06-17 16:47:40.350  1792  3346 I ActivityManager: Force stopping net.dot.Loader_classloader appid=10128 user=0: finished inst
      06-17 16:47:40.351  1792  3346 I ActivityManager: Killing 8650:net.dot.Loader_classloader/u0a128 (adj 0): stop net.dot.Loader_classloader
      06-17 16:47:40.351  1792  8406 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:47:40.351  1792  8406 W Binder  : java.lang.Throwable
      06-17 16:47:40.351  1792  8406 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:47:40.351  1792  8406 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:47:40.351  1792  8406 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:47:40.352  8640  8640 D AndroidRuntime: Shutting down VM
      06-17 16:47:40.364  8640  8671 E app_process: Thread attaching to non-existent runtime: Binder:8640_3
      06-17 16:47:40.364  8640  8671 I AndroidRuntime: NOTE: attach of thread 'Binder:8640_3' failed
      06-17 16:47:40.381  1535  1535 I Zygote  : Process 8650 exited due to signal 9 (Killed)
      06-17 16:47:40.396  1792  1819 I libprocessgroup: Successfully killed process cgroup uid 10128 pid 8650 in 44ms
```

**Comment by lambdageek** [comment]
This is probably not purely an interpreter issue since it's a DIM test.

**Comment by SamMonoRT** [comment]
Assigning for accurate tracking and triaging

**Comment by lambdageek** [comment]
Related to https://github.com/dotnet/runtime/issues/67540

**Comment by jkotas** [comment]
Tests are still disabled with ActiveIssue
