### ISSUE TITLE
[MONO][Interp] HardwareIntrinsics tests failed with SEGV with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54559]
Failed tests list:
- JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_r/Vector128_1_r.sh
- JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh

[JIT/HardwareIntrinsics/* full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.HardwareIntrinsics/console.e9f6d677.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
--------- beginning of crash
      06-17 16:57:06.158 13788 13806 F libc    : Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 13806 (.dot.MonoRunner), pid 13788 (dwareIntrinsics)
      06-17 16:57:06.267 13811 13811 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
      06-17 16:57:06.268  1616  1616 I /system/bin/tombstoned: received crash request for pid 13806
      06-17 16:57:06.268 13811 13811 I crash_dump64: performing dump of process 13788 (target tid = 13806)
      06-17 16:57:06.275 13811 13811 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
      06-17 16:57:06.275 13811 13811 F DEBUG   : Build fingerprint: 'Android/sdk_phone_x86_64/generic_x86_64:10/QPP6.190730.005.B1/5775370:userdebug/test-keys'
      06-17 16:57:06.275 13811 13811 F DEBUG   : Revision: '0'
      06-17 16:57:06.275 13811 13811 F DEBUG   : ABI: 'x86_64'
      06-17 16:57:06.275 13811 13811 F DEBUG   : Timestamp: 2021-06-17 16:57:06+0000
      06-17 16:57:06.275 13811 13811 F DEBUG   : pid: 13788, tid: 13806, name: .dot.MonoRunner  >>> net.dot.JIT_HardwareIntrinsics <<<
      06-17 16:57:06.275 13811 13811 F DEBUG   : uid: 10155
      06-17 16:57:06.275 13811 13811 F DEBUG   : signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
      06-17 16:57:06.275 13811 13811 F DEBUG   :     rax 00007a7485a7135a  rbx 00007a7485a713a4  rcx 00007a74d346b038  rdx 00007a74d346b060
      06-17 16:57:06.275 13811 13811 F DEBUG   :     r8  00007a74d346b038  r9  00007a7485a71362  r10 00007a74d346b060  r11 0000000000000000
      06-17 16:57:06.275 13811 13811 F DEBUG   :     r12 00007a7488423890  r13 00007a74880a4170  r14 ffffffffffffffdb  r15 00007a7485a71362
      06-17 16:57:06.275 13811 13811 F DEBUG   :     rdi 0000000000000000  rsi 26dcc2a779072dfd
      06-17 16:57:06.275 13811 13811 F DEBUG   :     rbp 00007a7488423ae0  rsp 00007a74884233b0  rip 00007a7488683040
      06-17 16:57:06.473 13811 13811 F DEBUG   : 
      06-17 16:57:06.473 13811 13811 F DEBUG   : backtrace:
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #00 pc 0000000000258040  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #01 pc 000000000024d6a7  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #02 pc 0000000000164acc  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #03 pc 0000000000093aa7  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #04 pc 0000000000099b9a  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonosgen-2.0.so (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #05 pc 00000000001b675b  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonosgen-2.0.so (mono_jit_exec+331) (BuildId: b8502093d5cbaaad2c56b78a2971bae3d39fed99)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #06 pc 0000000000001d7f  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonodroid.so (mono_droid_runtime_init+540) (BuildId: fe77d42b65eddb4d787d5caa705e079f15611d57)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #07 pc 0000000000002421  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/lib/x86_64/libmonodroid.so (Java_net_dot_MonoRunner_initRuntime+426) (BuildId: fe77d42b65eddb4d787d5caa705e079f15611d57)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #08 pc 0000000000002183  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/oat/x86_64/base.odex (art_jni_trampoline+371)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #09 pc 00000000001696b6  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+806) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #10 pc 0000000000179c61  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+305) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #11 pc 0000000000340ffc  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+380) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #12 pc 000000000033b20f  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1151) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #13 pc 000000000066c545  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+677) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #14 pc 0000000000162999  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+25) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #15 pc 0000000000000aba  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/oat/x86_64/base.vdex (net.dot.MonoRunner.initialize+98)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #16 pc 000000000066c86d  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1485) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #17 pc 0000000000162999  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+25) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #18 pc 0000000000000d60  /data/app/net.dot.JIT_HardwareIntrinsics-E_fbz7gmkh-Zbx4sc8p5Eg==/oat/x86_64/base.vdex (net.dot.MonoRunner.onStart+60)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #19 pc 00000000006692dd  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1789) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #20 pc 0000000000162819  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+25) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #21 pc 00000000001edea6  /system/framework/framework.jar (android.app.Instrumentation$InstrumentationThread.run+94)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #22 pc 000000000030dcad  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.13960599661070883162+253) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #23 pc 000000000065854a  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1210) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #24 pc 00000000001747cc  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+140) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #25 pc 0000000000169354  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+756) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #26 pc 0000000000179c50  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+288) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #27 pc 0000000000549d29  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+89) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #28 pc 000000000054afc5  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+437) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #29 pc 00000000005a0a7e  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1438) (BuildId: 8bb3225e7c408f2ca23abac3db0417f2)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #30 pc 0000000000100fce  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+30) (BuildId: a08a19770d6696739c847e29c3f5f650)
      06-17 16:57:06.474 13811 13811 F DEBUG   :       #31 pc 0000000000098fe7  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+55) (BuildId: a08a19770d6696739c847e29c3f5f650)
      06-17 16:57:06.500  1793  3289 E memtrack: Couldn't load memtrack module
      06-17 16:57:06.500  1793  3289 W android.os.Debug: failed to get memory consumption info: -1
      06-17 16:57:07.328  1616  1616 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
      06-17 16:57:07.350  1534  1534 I Zygote  : Process 13788 exited due to signal 11 (Segmentation fault)
      06-17 16:57:07.356  1793 13819 I DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
      06-17 16:57:07.359  1793  1824 I BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
      06-17 16:57:07.363  1793  3289 I ActivityManager: Process net.dot.JIT_HardwareIntrinsics (pid 13788) has died: fore FGS 
      06-17 16:57:07.364  1793  3289 W ActivityManager: Crash of app net.dot.JIT_HardwareIntrinsics running instrumentation ComponentInfo{net.dot.JIT_HardwareIntrinsics/net.dot.MonoRunner}
      06-17 16:57:07.364  1793  3289 I ActivityManager: Force stopping net.dot.JIT_HardwareIntrinsics appid=10155 user=0: finished inst
      06-17 16:57:07.370  1793  1824 I DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
      06-17 16:57:07.375  1793 13820 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:57:07.375  1793 13820 W Binder  : java.lang.Throwable
      06-17 16:57:07.375  1793 13820 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:57:07.375  1793 13820 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:57:07.375  1793 13820 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:57:07.376 13778 13778 D AndroidRuntime: Shutting down VM
      06-17 16:57:07.403  1793  1820 I libprocessgroup: Successfully killed process cgroup uid 10155 pid 13788 in 38ms
```

**Comment by BrzVlad** [comment]
I think this is fixed by https://github.com/dotnet/runtime/pull/54734

**Comment by BrzVlad** [comment]
Re-enabled the test
