### ISSUE TITLE
UnixSearchPatternFileValidChar test failing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54594]
```
System.IO.Tests.DirectoryInfo_GetFileSystemInfos_str.UnixSearchPatternFileValidChar(valid: \">\")

System.UnauthorizedAccessException : Access to the path '/var/folders/6f/5yk_94p53cg_ltnfts0_9cmc0000gq/T/DirectoryInfo_GetFileSystemInfos_str_jspyhvh5.lqb/UnixSearchPatternFileValidChar_757_0e6c5d1a/>' is denied.
---- System.IO.IOException : Bad file descriptor
at System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs:line 121
   at System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeInternal(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.cs:line 110
   at System.IO.FileStream.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs:line 476
   at System.IO.Stream.Close() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 165
   at System.IO.Stream.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 158
   at System.IO.Tests.Directory_GetFileSystemEntries_str_str.UnixSearchPatternFileValidChar(String valid) in /_/src/libraries/System.IO.FileSystem/tests/Directory/GetFileSystemEntries_str_str.cs:line 758
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
----- Inner Stack Trace -----
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1200703&view=ms.vss-test-web.build-test-results-tab&runId=35966190&resultId=120781&paneView=debug

Configuration: `net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open`

**Comment by stephentoub** [comment]
Another case of https://github.com/dotnet/runtime/issues/54589

**Comment by adamsitnik** [comment]
Fixed by @danmoseley in https://github.com/dotnet/runtime/pull/54660
