### ISSUE TITLE
`System.IO.Tests` failing on `Libraries Test Run release mono OSX x64 Debug`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#54624]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1201745&view=logs&jobId=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=5d5289b6-723b-5155-5d15-b590d280a14a)

Seen on https://github.com/dotnet/runtime/pull/54053 .

```
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 12)
    System.IO.Tests.FileStream_Dispose.NoDispose_CallsVirtualDisposeFalseArg_ThrowsDuringFlushWriteBuffer_FinalizerWontThrow [SKIP]
      Condition(s) not met: "IsPreciseGcSupportedAndRemoteExecutorSupported"
    System.IO.Tests.FileStream_Dispose.FinalizeFlushesWriteBuffer [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.IO.Tests.FileStream_Dispose.Finalizer_CallsVirtualDispose_FalseArg [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.IO.Tests.FileStream_Dispose.Dispose_CallsVirtualDispose_TrueArg [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.DirectoryInfo_ToString.ParentToString_Framework [SKIP]
      Condition(s) not met: "IsNetFramework"
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.File_GetSetTimes.SetDateTimeMax [SKIP]
      Condition(s) not met: "SupportsLongMaxDateTime"
    System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async [SKIP]
      Condition(s) not met: "IsNet5CompatFileStreamEnabled"
    System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync [SKIP]
      Condition(s) not met: "IsNet5CompatFileStreamEnabled"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToMillisecondPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.MoveToMillisecondPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.Directory_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.DirectoryInfo_Create.PathWithReservedDeviceNameAsPath_ThrowsDirectoryNotFoundException [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.Directory_CreateDirectory.PathWithReservedDeviceNameAsPath_ThrowsDirectoryNotFoundException [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.DirectoryInfo_Create.PathWithReservedDeviceNameAsExtendedPath [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.Directory_CreateDirectory.PathWithReservedDeviceNameAsExtendedPath [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.AnonymousPipeFileStreamConnectedConformanceTests.Read_Eof_Returns0(mode: AsyncArray, dataAvailableFirst: True) [FAIL]
      System.IO.IOException : Broken pipe
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.Unix.cs(29,0): at System.IO.Strategies.FileStreamHelpers.CheckFileCall(Int64 result, String path, Boolean ignoreNotSupported)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs(624,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.CheckFileCall(Int32 result, Boolean ignoreNotSupported)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs(457,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.WriteNative(ReadOnlySpan`1 source)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs(189,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(Boolean calledFromFinalizer)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs(93,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.cs(110,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeInternal(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs(476,0): at System.IO.FileStream.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs(165,0): at System.IO.Stream.Close()
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs(158,0): at System.IO.Stream.Dispose()
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(3038,0): at System.IO.Tests.StreamPair.Dispose()
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(1870,0): at System.IO.Tests.ConnectedStreamConformanceTests.Read_Eof_Returns0(ReadWriteMode mode, Boolean dataAvailableFirst)
        --- End of stack trace from previous location ---
    System.IO.Tests.FileStream_BeginEndWrite_AsyncWrites.BufferCorrectlyMaintainedWhenReadAndWrite(useAsync: False) [FAIL]
      System.UnauthorizedAccessException : Access to the path '/var/folders/kg/md95k0d54xl7q6qsmlgwcbqr0000gq/T/FileStream_BeginEndWrite_AsyncWrites_5drflqsc.qo2/BufferCorrectlyMaintainedWhenReadAndWrite_253_2389deda' is denied.
      ---- System.IO.IOException : Bad file descriptor
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs(121,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.cs(110,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeInternal(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs(476,0): at System.IO.FileStream.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs(165,0): at System.IO.Stream.Close()
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs(158,0): at System.IO.Stream.Dispose()
        /_/src/libraries/System.IO.FileSystem/tests/FileStream/WriteAsync.cs(271,0): at System.IO.Tests.FileStream_AsyncWrites.BufferCorrectlyMaintainedWhenReadAndWrite(Boolean useAsync)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        
    System.IO.Tests.BufferedAsyncFileStreamStandaloneConformanceTests.CopyTo_CopiesAllDataFromRightPosition_Success(useAsync: True, expected: [23, 226, 154, 72, 99, ...], position: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 16384
      Actual:   8
      Stack Trace:
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(1037,0): at System.IO.Tests.StandaloneStreamConformanceTests.CopyTo_CopiesAllDataFromRightPosition_Success(Boolean useAsync, Byte[] expected, Int32 position)
        --- End of stack trace from previous location ---
  Finished:    System.IO.FileSystem.Tests
```

**Comment by radical** [comment]
Another failure ([log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54653-merge-e36016a7eeef474f8d/System.IO.FileSystem.Tests/console.38d24eaa.log?sv=2019-07-07&se=2021-07-14T00%3A11%3A40Z&sr=c&sp=rl&sig=hEXlP0sfHSwDu0uEUOl3QZVzLrryNE8XmMjLEKFb8tE%3D), [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1202822&view=logs&jobId=c6f8dc49-92a1-5760-c098-ba97b8142bfb&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=5d5289b6-723b-5155-5d15-b590d280a14a)):

```
    System.IO.Tests.File_AppendAllLines.DisposingEnumeratorClosesFile [FAIL]
      System.UnauthorizedAccessException : Access to the path '/var/folders/7r/sy0tt91943scjzwlx5c9ygh00000gy/T/File_AppendAllLines_hwucbn5q.psg/DisposingEnumeratorClosesFile_133_fdb47d50' is denied.
      ---- System.IO.IOException : Bad file descriptor
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.Unix.cs(121,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/Net5CompatFileStreamStrategy.cs(110,0): at System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeInternal(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs(476,0): at System.IO.FileStream.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs(165,0): at System.IO.Stream.Close()
        /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs(261,0): at System.IO.StreamReader.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/TextReader.cs(34,0): at System.IO.TextReader.Dispose()
        /_/src/libraries/System.Private.CoreLib/src/System/IO/ReadLinesIterator.cs(81,0): at System.IO.ReadLinesIterator.Dispose(Boolean disposing)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Iterator.cs(30,0): at System.IO.Iterator`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Dispose()
        /_/src/libraries/System.IO.FileSystem/tests/File/ReadWriteAllLines.cs(142,0): at System.IO.Tests.File_ReadWriteAllLines_Enumerable.DisposingEnumeratorClosesFile()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(370,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
```

**Comment by danmoseley** [comment]
#54589
