### ISSUE TITLE
System.Net.Sockets.Tests.ConnectCancellableTask tests failing on PR

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#54623]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1201745&view=logs&jobId=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6)
Seen on https://github.com/dotnet/runtime/pull/54053 .

```
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 2)
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
    System.Net.Sockets.Tests.ConnectCancellableTask.Connect_DualMode_DnsConnect_RetrievedEndPoints_Success [FAIL]
      Assert.Equal() Failure
      Expected: ::ffff:127.0.0.1
      Actual:   ::1
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs(132,0): at System.Net.Sockets.Tests.Connect`1.Connect_DualMode_DnsConnect_RetrievedEndPoints_Success()
        --- End of stack trace from previous location ---
    System.Net.Sockets.Tests.LocalEndPointTestIPv6Sync.TcpClientSocket_WhenNotBound_LocalEPChangeToSpecificOnConnnect [FAIL]
      Assert.Equal() Failure
      Expected: [::1]:41198
      Actual:   [::1]:41206
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/LocalEndPointTest.cs(117,0): at System.Net.Sockets.Tests.LocalEndPointTest`1.TcpClientSocket_WhenNotBound_LocalEPChangeToSpecificOnConnnect()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Sockets.Tests
```

**Comment by karelz** [comment]
`TcpClientSocket_WhenNotBound_LocalEPChangeToSpecificOnConnnect` failed only once 3/12-6/23 (incl. PRs), not worth tracking.
`Connect_DualMode_DnsConnect_RetrievedEndPoints_Success` shows lots of failures since 6/6 - tracked separately in #54677.

Closing.
