### ISSUE TITLE
`System.IO.Tests.DirectoryInfo_Exists.SymLinksMayExistIndependentlyOfTarget` failing on `Libraries Test Run checked coreclr windows x86 Release`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#54628]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1201745&view=logs&jobId=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&j=4b63c0bc-98ed-52ad-dbe3-c1041017a20f&t=5f31c76d-daa9-5833-78dc-df7322e06497)

Seen on #54053 .

```
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 4)
The system cannot find the path specified.
    System.IO.Tests.DirectoryInfo_Exists.SymLinksMayExistIndependentlyOfTarget [FAIL]
      System.Runtime.InteropServices.COMException : The handle is invalid. (0x80070006 (E_HANDLE))
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs(905,0): at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
        /_/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.ProcessWaitHandle.cs(31,0): at Interop.Kernel32.ProcessWaitHandle..ctor(SafeProcessHandle processHandle)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs(177,0): at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1392,0): at System.Diagnostics.Process.WaitForExit(Int32 milliseconds)
        /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1383,0): at System.Diagnostics.Process.WaitForExit()
        /_/src/libraries/System.IO.FileSystem/tests/PortedCommon/ReparsePointUtilities.cs(53,0): at MountHelper.CreateSymbolicLink(String linkPath, String targetPath, Boolean isDirectory)
        /_/src/libraries/System.IO.FileSystem/tests/DirectoryInfo/Exists.cs(146,0): at System.IO.Tests.DirectoryInfo_Exists.SymLinksMayExistIndependentlyOfTarget()
```

**Comment by adamsitnik** [comment]
Fixed by @danmoseley in #54660
