### ISSUE TITLE
[HTTP/3] Test failure System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_Mock.ConnectTimeout_TimesOutSSLAuth_Throws

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54806]
Run: [runtime-libraries-coreclr outerloop 20210627.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1208254&view=ms.vss-test-web.build-test-results-tab&runId=36131070&resultId=103278&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_release-(Debian.9.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-bfcd90a-20200121150037

- System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_Mock.ConnectTimeout_TimesOutSSLAuth_Throws

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Net.Http.HttpRequestException): Connection refused (127.0.0.1:1)
---- System.Net.Http.HttpRequestException : Connection refused (127.0.0.1:1)
-------- System.Net.Sockets.SocketException : Connection refused


Stack trace
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1355
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1263
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 525
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp2Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 822
   at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 884
   at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 901
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 920
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1355
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1263
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 525
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp2Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 822
   at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 884
   at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 901
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 92
```

**Comment by wfurt** [comment]
The port is really strange `127.0.0.1:1` => 1 is reserved port.

**Comment by karelz** [comment]
Failures **4/28-6/27 (incl. PRs)**:

Date | Run | Details
-- | -- | --
6/26 | PR #54755 | 13 failures
6/26 | Official run | 39 failures
6/27 | Official run | 39 failures

We need to disable the tests ASAP.

**Comment by karelz** [comment]
@ManickaP @wfurt @geoffkizer any thoughts how to disable the test just for HTTP/3?

**Comment by wfurt** [comment]
is everything on ARM @karelz ?

**Comment by karelz** [comment]
Nope, arm, amd64, all OS versions - Windows, Linux, OSX

**Comment by ManickaP** [comment]
The port "1" in the exception looks suspicious. Are we really using TCPMUX? Or is this some magic in our test environment and it should "just work" tm?

**Comment by ManickaP** [comment]
Even more, this is SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_Mock and mocks are using in memory buffers. There shouldn't even be any networking involved. This is suspicious.

**Comment by wfurt** [comment]
typically the server would bind on anonymous port (e.g. 0) and then OS would assign some real unused port. Then we would tell client where to connect to. I'm not sure what exactly we do for mock.

**Comment by ManickaP** [comment]
> I'm not sure what exactly we do for mock.

Nothing, we don't do any networking, we use in-memory buffers to exchange data between client and server.

**Comment by ManickaP** [comment]
This might be the problem:
https://github.com/dotnet/runtime/blob/cef40a107ff2f810219b3b28af709b0b778a3472/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Cancellation.cs#L35

It basically walks around the whole handler set up we do for testing clients:
https://github.com/dotnet/runtime/blob/cef40a107ff2f810219b3b28af709b0b778a3472/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTestBase.SocketsHttpHandler.cs#L38-L57

This should be quick, I'll put up a PR. If it helps, great, if not, I'll disable the test.

**Comment by geoffkizer** [comment]
> I'm not sure what exactly we do for mock.

We have to create a fake IPEndPoint for Mock. That's where the :1 is coming from.

The problem is, we seem to have a mismatch in this test where we are using Mock on the loopback server but MsQuic on the client. So we end up actually trying to connect to the fake endpoint. 

The reason for the mismatch is what @ManickaP pointed out above -- we are constructing the SocketsHttpHandler directly instead of using CreateHttpClientHandler. As a result it doesn't get configured to use Mock.

Interestingly, this test seems to run fine on Windows. I guess the difference here is that Linux is actively denying an attempt to connect to 127.0.0.1:1 whereas Windows is not.

**Comment by geoffkizer** [comment]
This is a weird test because it's intentionally *not* completing the connection -- specifically, it's written so that the connection should be accepted but the SSL establishment shouldn't happen.

This doesn't really make sense for HTTP3. I think we should just disable this test for HTTP3, like we do the one just below.
