### ISSUE TITLE
[Mono][Android][Interop] Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54905]
Failed test list:

- Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
- Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.sh

```
      06-21 22:19:56.080  3815  3832 I DOTNET  : MonoRunner initialize,, entryPointLibName=NativeLibraryTests.dll
      06-21 22:19:56.080  3815  3832 D DOTNET  : file_path: /data/user/0/net.dot.Interop_NativeLibrary/files/runtimeconfig.bin
      06-21 22:19:56.082  3815  3832 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.Interop_NativeLibrary/files
      06-21 22:19:56.101  3815  3832 D DOTNET  : assembly_preload_hook: NativeLibraryTests.dll (null) /data/user/0/net.dot.Interop_NativeLibrary/files
      06-21 22:19:56.101  3815  3832 D DOTNET  : Executable: NativeLibraryTests.dll
      06-21 22:19:56.101  3815  3832 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.Interop_NativeLibrary/files
      06-21 22:19:56.101  3815  3832 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.Interop_NativeLibrary/files
      06-21 22:19:56.101  3815  3832 D DOTNET  : assembly_preload_hook: TestLibrary  /data/user/0/net.dot.Interop_NativeLibrary/files
      06-21 22:19:56.102  3815  3832 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.Interop_NativeLibrary/files
      06-21 22:19:56.179  3815  3832 E mono    : 
      06-21 22:19:56.179  3815  3832 E mono    : Unhandled Exception:
      06-21 22:19:56.179  3815  3832 E mono    : System.PlatformNotSupportedException: Operation is not supported on this platform.
      06-21 22:19:56.179  3815  3832 E mono    :    at NativeLibraryToLoad.GetFileName() in NativeLibraryTests.dll:token 0x600000d+0x27
      06-21 22:19:56.179  3815  3832 E mono    :    at NativeLibraryToLoad.GetFullPath() in NativeLibraryTests.dll:token 0x600000e+0x12
      06-21 22:19:56.179  3815  3832 E mono    :    at NativeLibraryTest.Main() in NativeLibraryTests.dll:token 0x6000001+0x14
      06-21 22:19:56.179  3815  3832 E DOTNET  : UnhandledException: System.PlatformNotSupportedException Operation is not supported on this platform.    at NativeLibraryToLoad.GetFileName() in NativeLibraryTests.dll:token 0x600000d+0x27
      06-21 22:19:56.179  3815  3832 E DOTNET  :    at NativeLibraryToLoad.GetFullPath() in NativeLibraryTests.dll:token 0x600000e+0x12
      06-21 22:19:56.179  3815  3832 E DOTNET  :    at NativeLibraryTest.Main() in NativeLibraryTests.dll:token 0x6000001+0x14
      06-21 22:19:56.215  1792  3093 I ActivityManager: Process net.dot.Interop_NativeLibrary (pid 3815) has died: fore FGS 
      06-21 22:19:56.215  1792  3093 W ActivityManager: Crash of app net.dot.Interop_NativeLibrary running instrumentation ComponentInfo{net.dot.Interop_NativeLibrary/net.dot.MonoRunner}
      06-21 22:19:56.215  1792  3093 I ActivityManager: Force stopping net.dot.Interop_NativeLibrary appid=10158 user=0: finished inst
      06-21 22:19:56.217  1535  1535 I Zygote  : Process 3815 exited cleanly (1)
      06-21 22:19:56.217  1792  3835 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-21 22:19:56.217  1792  3835 W Binder  : java.lang.Throwable
      06-21 22:19:56.217  1792  3835 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-21 22:19:56.217  1792  3835 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-21 22:19:56.217  1792  3835 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-21 22:19:56.218  3804  3804 D AndroidRuntime: Shutting down VM
      06-21 22:19:56.260  1792  1819 I libprocessgroup: Successfully killed process cgroup uid 10158 pid 3815 in 44ms
```

**Comment by steveisok** [comment]
@fanyang-mono I believe there needs to be an additional OS check added https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/tests/Interop/NativeLibrary/NativeLibraryToLoad/NativeLibraryToLoad.cs#L14-L26

**Comment by fanyang-mono** [comment]
Tests didn't pass after adding an Android switch to `NativeLibraryToLoad.cs`. There are more work to be done, in order to make the tests pass. 

1. Make runtime tests native build work for Android https://github.com/dotnet/runtime/blob/main/src/tests/build.sh#L265-L266
2. Include the generated native libraries (`.so` files) in the Android app.

**Comment by steveisok** [comment]
@fanyang-mono Is this still an issue?

**Comment by fanyang-mono** [comment]
Moving to 8.0.0

**Comment by fanyang-mono** [comment]
Moving to 9.0.0
