### ISSUE TITLE
[Mono][Android][Test] Could not load file or assembly 'xunit.runner.utility.netcoreapp10, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54906]
Failed test list:

- ilasm/PortablePdb/IlasmPortablePdbTests/IlasmPortablePdbTests.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54516-merge-486ed47802b44cd5a6/PayloadGroup0/console.fc0b92d4.log?sv=2019-07-07&se=2021-07-11T21%3A42%3A12Z&sr=c&sp=rl&sig=bNVwODgwBmw9vhsZfWcoh08Yt4ZA4ne2wpc0el0XP%2FM%3D)

```
      06-21 22:20:19.597 15323 15341 I DOTNET  : MonoRunner initialize,, entryPointLibName=IlasmPortablePdbTests.dll
      06-21 22:20:19.598 15323 15341 D DOTNET  : file_path: /data/user/0/net.dot.ilasm_PortablePdb/files/runtimeconfig.bin
      06-21 22:20:19.600 15323 15341 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.ilasm_PortablePdb/files
      06-21 22:20:19.618 15323 15341 D DOTNET  : assembly_preload_hook: IlasmPortablePdbTests.dll (null) /data/user/0/net.dot.ilasm_PortablePdb/files
      06-21 22:20:19.618 15323 15341 D DOTNET  : Executable: IlasmPortablePdbTests.dll
      06-21 22:20:19.618 15323 15341 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.ilasm_PortablePdb/files
      06-21 22:20:19.619 15323 15341 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.ilasm_PortablePdb/files
      06-21 22:20:19.630 15323 15341 D DOTNET  : assembly_preload_hook: xunit.runner.utility.netcoreapp10  /data/user/0/net.dot.ilasm_PortablePdb/files
      06-21 22:20:19.678 15323 15341 E mono    : 
      06-21 22:20:19.678 15323 15341 E mono    : Unhandled Exception:
      06-21 22:20:19.678 15323 15341 E mono    : System.IO.FileNotFoundException: Could not load file or assembly 'xunit.runner.utility.netcoreapp10, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.
      06-21 22:20:19.678 15323 15341 E mono    : File name: 'xunit.runner.utility.netcoreapp10, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
      06-21 22:20:19.678 15323 15341 E mono    :    at IlasmPortablePdbTests.IlasmPortablePdbTester.Main(String[] args) in IlasmPortablePdbTests.dll:token 0x6000016+0x5
      06-21 22:20:19.678 15323 15341 E DOTNET  : UnhandledException: System.IO.FileNotFoundException Could not load file or assembly 'xunit.runner.utility.netcoreapp10, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.    at IlasmPortablePdbTests.IlasmPortablePdbTester.Main(String[] args) in IlasmPortablePdbTests.dll:token 0x6000016+0x5
      06-21 22:20:19.718  1535  1535 I Zygote  : Process 15323 exited cleanly (1)
      06-21 22:20:19.720  1792  1807 I ActivityManager: Process net.dot.ilasm_PortablePdb (pid 15323) has died: fore FGS 
      06-21 22:20:19.721  1792  1820 I libprocessgroup: Successfully killed process cgroup uid 10137 pid 15323 in 0ms
      06-21 22:20:19.722  1792  1807 W ActivityManager: Crash of app net.dot.ilasm_PortablePdb running instrumentation ComponentInfo{net.dot.ilasm_PortablePdb/net.dot.MonoRunner}
      06-21 22:20:19.723  1792  1807 I ActivityManager: Force stopping net.dot.ilasm_PortablePdb appid=10137 user=0: finished inst
      06-21 22:20:19.725  1792 15344 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-21 22:20:19.725  1792 15344 W Binder  : java.lang.Throwable
      06-21 22:20:19.725  1792 15344 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-21 22:20:19.725  1792 15344 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-21 22:20:19.725  1792 15344 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-21 22:20:19.726 15313 15313 D AndroidRuntime: Shutting down VM
```

**Comment by fanyang-mono** [comment]
Imran's comment could be helpful here
https://github.com/dotnet/runtime/issues/44648#issuecomment-841507555

**Comment by fanyang-mono** [comment]
Moving to 8.0.0

**Comment by fanyang-mono** [comment]
Test related issue. Moving to 9.0.0

**Comment by Xinlong-Wu** [comment]
there might be same problem on RISCV64 Arch. the founction `dlopen` at `mono-dl.c:250` can't open existing Native Library `libGCPollNative.so`. Hopes the information may helps.

**Comment by Xinlong-Wu** [comment]
I have solve the problem on riscv64. 
I use command `./src/tests//build.sh -mono -debug -riscv64 -ninja /p:KeepNativeSymbols=true` to build the test, but it genertae DLLs with HOST's arch instead of TARGET's Arch ( `libGCPollNative.so` is x86 arch as example). That is why RISCV64 mono can't open it.
Hope this infomation will helps.

**Comment by lewing** [comment]
@fanyang-mono is this still a problem?

**Comment by fanyang-mono** [comment]
Yes, this issue still need to be resolved.
