### ISSUE TITLE
[Mono][Android][Test] CORE_ROOT was not set for the test

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54908]
Failed tests list:

- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54516-merge-486ed47802b44cd5a6/JIT/console.de38ff03.log?sv=2019-07-07&se=2021-07-11T21%3A42%3A12Z&sr=c&sp=rl&sig=bNVwODgwBmw9vhsZfWcoh08Yt4ZA4ne2wpc0el0XP%2FM%3D)

```
      06-21 22:49:48.376  9695  9712 I DOTNET  : MonoRunner initialize,, entryPointLibName=CscBench.dll
      06-21 22:49:48.376  9695  9712 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Performance/files/runtimeconfig.bin
      06-21 22:49:48.379  9695  9712 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.488  9695  9712 D DOTNET  : assembly_preload_hook: CscBench.dll (null) /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.489  9695  9712 D DOTNET  : Executable: CscBench.dll
      06-21 22:49:48.489  9695  9712 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.489  9695  9712 D DOTNET  : assembly_preload_hook: xunit.performance.core  /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.503  9695  9712 D DOTNET  : ((null) warning) Can't find custom attr constructor image: /data/data/net.dot.JIT_Performance/files/CscBench.dll mtoken: 0x0a000004 due to: Could not load file or assembly 'xunit.performance.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=67066efe964d3b03' or one of its dependencies.
      06-21 22:49:48.503  9695  9712 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.517  9695  9712 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.521  9695  9712 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_Performance/files
      06-21 22:49:48.632  9695  9712 I DOTNET  : This test requires CORE_ROOT to be set
      06-21 22:49:48.633  9695  9712 D DOTNET  : Exit code: -1.
      06-21 22:49:48.704  9695  9712 I DOTNET  : MonoRunner finished, return-code=-1
      06-21 22:49:48.706  1793  1808 I ActivityManager: Force stopping net.dot.JIT_Performance appid=10170 user=0: finished inst
      06-21 22:49:48.706  1793  1808 I ActivityManager: Killing 9695:net.dot.JIT_Performance/u0a170 (adj 0): stop net.dot.JIT_Performance
      06-21 22:49:48.715  1793  1810 W Looper  : Slow delivery took 2017ms android.fg h=com.android.server.AppStateTracker$MyHandler c=null m=12
      06-21 22:49:48.716  1793  1810 W Looper  : Drained
      06-21 22:49:48.720  1793  9671 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-21 22:49:48.720  1793  9671 W Binder  : java.lang.Throwable
      06-21 22:49:48.720  1793  9671 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-21 22:49:48.720  1793  9671 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-21 22:49:48.720  1793  9671 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-21 22:49:48.721  9684  9684 D AndroidRuntime: Shutting down VM
```

**Comment by steveisok** [comment]
@fanyang-mono Is this still an issue?

**Comment by fanyang-mono** [comment]
Moving to 8.0.0

**Comment by fanyang-mono** [comment]
Moving to 9.0.0
