### ISSUE TITLE
[Mono][Android] Test app crashed on exit

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54911]
Failed tests list:

- JIT/Methodical/switch/switch5/switch5.sh
- JIT/Methodical/switch/switch6/switch6.sh
- JIT/Methodical/tailcall/_il_dbgrecurse_ep_void/_il_dbgrecurse_ep_void.sh
- JIT/Methodical/tailcall/_il_dbgtest_void/_il_dbgtest_void.sh
- JIT/Methodical/tailcall/_il_relrecurse_ep_void/_il_relrecurse_ep_void.sh
- JIT/Methodical/tailcall/_il_reltest_void/_il_reltest_void.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54516-merge-486ed47802b44cd5a6/JIT.Methodical/console.4102714a.log?sv=2019-07-07&se=2021-07-11T21%3A42%3A12Z&sr=c&sp=rl&sig=bNVwODgwBmw9vhsZfWcoh08Yt4ZA4ne2wpc0el0XP%2FM%3D)

```
      06-21 22:27:17.033 13935 13953 I DOTNET  : MonoRunner initialize,, entryPointLibName=switch5.dll
      06-21 22:27:17.034 13935 13953 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Methodical/files/runtimeconfig.bin
      06-21 22:27:17.035 13935 13953 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.122 13935 13945 I .JIT_Methodica: Background young concurrent copying GC freed 87649(6647KB) AllocSpace objects, 0(0B) LOS objects, 81% free, 1432KB/7576KB, paused 593us total 139.192ms
      06-21 22:27:17.156 13935 13953 D DOTNET  : assembly_preload_hook: switch5.dll (null) /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.156 13935 13953 D DOTNET  : Executable: switch5.dll
      06-21 22:27:17.156 13935 13953 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.157 13935 13953 D DOTNET  : assembly_preload_hook: System.Runtime.Extensions  /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.160 13935 13953 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.160 13935 13953 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.167 13935 13953 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.170 13935 13953 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_Methodical/files
      06-21 22:27:17.287 13935 13953 I DOTNET  : Test passed
      06-21 22:27:17.398  1538  1538 I Zygote  : Process 13935 exited cleanly (100)
      06-21 22:27:17.398  1795  2488 I ActivityManager: Process net.dot.JIT_Methodical (pid 13935) has died: fore FGS 
      06-21 22:27:17.399  1795  1824 I libprocessgroup: Successfully killed process cgroup uid 10113 pid 13935 in 0ms
      06-21 22:27:17.400  1795  2488 W ActivityManager: Crash of app net.dot.JIT_Methodical running instrumentation ComponentInfo{net.dot.JIT_Methodical/net.dot.MonoRunner}
      06-21 22:27:17.401  1795  2488 I ActivityManager: Force stopping net.dot.JIT_Methodical appid=10113 user=0: finished inst
      06-21 22:27:17.402  1795 10876 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-21 22:27:17.402  1795 10876 W Binder  : java.lang.Throwable
      06-21 22:27:17.402  1795 10876 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-21 22:27:17.402  1795 10876 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-21 22:27:17.402  1795 10876 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-21 22:27:17.403 13925 13925 D AndroidRuntime: Shutting down VM
```

**Comment by thaystg** [comment]
It's happening again: https://dev.azure.com/dnceng/public/_build/results?buildId=1642506&view=ms.vss-test-web.build-test-results-tab&runId=45413648&resultId=100522&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by fanyang-mono** [comment]
> It's happening again: https://dev.azure.com/dnceng/public/_build/results?buildId=1642506&view=ms.vss-test-web.build-test-results-tab&runId=45413648&resultId=100522&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

The error of the above link is a CI reporting failure, whereas, this issue tracks mono product failure. Please create a separate issue for CI reporting failure.
```
[DevOpsReportFailure: Failed to upload results: Error occurred in request., RetryError: HTTPSConnectionPool(host='dev.azure.com', port=443): Max retries exceeded with url: /dnceng/public/_apis/test/Runs/45413648/Results (Caused by ResponseError('too many 503 error responses',))]()
```

**Comment by fanyang-mono** [comment]
Moving to 8.0.0

**Comment by SamMonoRT** [comment]
@fanyang-mono - please update with current status.

**Comment by fanyang-mono** [comment]
These are iL tests testing scenarios that the customer unlikely run into. Moving to 9.0.0.
