### ISSUE TITLE
TypeLoadException when inspecting state machine attribute updated by EnC

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#54929]
### Description

.NET 6.0.100-preview.6.21321.13

Repro:
1) Create a console app with the following code 
2) F10 (start debugging and step into Main)
3) Change `Console.WriteLine(1);` in `F()` to `Console.WriteLine(2);`
5) F5

```C#
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

class Program
{
    static async Task F()
    {
        Console.WriteLine(1);
    }

    static void Main(string[] args)
    {
        F().Wait();

        var attributes = typeof(Program).GetMethod("F", BindingFlags.NonPublic | BindingFlags.Static).GetCustomAttributes(true);
        foreach (var attribute in attributes)
        {
            if (attribute is AsyncStateMachineAttribute asm)
            {
                Console.WriteLine(asm.StateMachineType);
            }
        }
    }
}
```

```
System.TypeLoadException: 'Could not load type 'Program+<F>d__0#1' from assembly 'ConsoleApp2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'

   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs:line 1547
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs:line 1300
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs:line 1059
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Boolean inherit) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 243
   at Program.Main(String[] args) in ConsoleApp2\Program.cs:line 17
```

**Comment by tmat** [comment]
Also seeing exception from JIT:

```
KERNELBASE.dll!RaiseException()	Unknown
>	clrjit.dll!Compiler::impImportBlockCode(BasicBlock * block) Line 14417	C++
 	clrjit.dll!Compiler::impImportBlock(BasicBlock * block) Line 17681	C++
 	clrjit.dll!Compiler::impImport() Line 18761	C++
 	clrjit.dll!Compiler::fgImport() Line 632	C++
 	[Inline Frame] clrjit.dll!Phase::Run() Line 61	C++
 	[Inline Frame] clrjit.dll!DoPhase(Compiler *) Line 136	C++
 	clrjit.dll!Compiler::compCompile(void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags) Line 4505	C++
 	clrjit.dll!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags) Line 6499	C++
 	clrjit.dll!Compiler::compCompile(CORINFO_MODULE_STRUCT_ * classPtr, void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags) Line 5765	C++
 	clrjit.dll!jitNativeCode(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags, void * inlineInfoPtr) Line 7132	C++
 	clrjit.dll!CILJit::compileMethod(ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, unsigned int flags, unsigned char * * entryAddress, unsigned int * nativeSizeOfCode) Line 279	C++
 	[Managed to Native Transition]	
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<System.__Canon>(ref System.__Canon stateMachine)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<WebApplication_SaveRepro.Pages.Pages_Index.<ExecuteAsync>d__0#1>(ref WebApplication_SaveRepro.Pages.Pages_Index.<ExecuteAsync>d__0#1 stateMachine)	Unknown
 	WebApplication-SaveRepro.dll!WebApplication_SaveRepro.Pages.Pages_Index.ExecuteAsync()	Unknown
```

More info on https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348122

**Comment by pranavkm** [comment]
@mikem8361 is this something we could address in 6.0? I ran in to this as part of the reloadable type work - the runtime throws an error trying to print a stack trace which makes it really hard to diagnose, particularly since attaching a debugger is also disallowed:

```C#
 System.TypeLoadException: Could not load type 'AspNetCoreGeneratedDocument.Views_Shared__Layout+<ExecuteAsync>d__17#1' from assembly 'm1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
         at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
         at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes) in System.Private.CoreLib.dll:token 0x600537e+0x1e2
         at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType) in System.Private.CoreLib.dll:token 0x600537d+0x0
         at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit) in System.Private.CoreLib.dll:token 0x6005373+0x46
         at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit) in System.Private.CoreLib.dll:token 0x60053e6+0x39
         at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit) in System.Private.CoreLib.dll:token 0x600021d+0x56
         at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit) in System.Private.CoreLib.dll:token 0x60054ea+0x0
         at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType) in System.Private.CoreLib.dll:token 0x60063f7+0x31
         at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb) in System.Private.CoreLib.dll:token 0x60063f5+0x100
         at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat) in System.Private.CoreLib.dll:token 0x60063f4+0xb
         at System.Exception.get_StackTrace() in System.Private.CoreLib.dll:token 0x6000441+0x23
```

**Comment by mikem8361** [comment]
The stack trace issue is being tracked with https://github.com/dotnet/runtime/issues/56335. Currently isn't planned for 6.0 because it will require quite a bit of work.

**Comment by vritant24** [comment]
The issue of the type load exception (not stack traces) occurring as a result of checking the state machine custom attribute also blocks the test experience from supporting the addition of Async tests. 
To not degrade the testing experience, the capabilities are limited to purely Baseline to force async method additions to be rude edits. 
It would be great if we could get a fix for this in .NET 6.

**Comment by mikem8361** [comment]
Moved to back to 6.0 to investigate the actual reason for the TypeLoadException not the problem that the runtime unhandled exception stack trace is broken.
