### ISSUE TITLE
Test failure System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54943]
Run: [runtime-coreclr libraries-jitstress 20210629.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1210759&view=ms.vss-test-web.build-test-results-tab&runId=36181088&resultId=116740&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

```
**Error message:**
```
System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.


Stack trace
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20210807.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1281772&view=ms.vss-test-web.build-test-results-tab&runId=37869924&paneView=debug&resultId=122695)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs0x1000-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD
```
**Error message:**
```
System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.


Stack trace
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131
```

**Comment by danmoseley** [comment]
In the last 2 months this test has failed 11 times, usually on jitstress (so likely due to slowness) and on one occasion in a different failure mode.

Unlikely to be a product issue, at best perhaps we could retry, and unlikely to be a new issue. Moving to future.


Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI1TTW%2faQBC9R8p%2fmPoEErVDVVW9UCkxpaUSgQJqjtZiD%2faCvWvNrusi5cdndk2o%2byElJ%2b%2fMvDfz5sNbNHaNpimtub56hIOWCo5SZROpFBI8aDrOLVYGtLoY8%2bx%2f0G9651H8dYAoeoS2QEKYSSVNgRl8moDS7eDt%2bN1NNnQpunhXHiYTCGZCloHjnkPfG2zwXlTooy0X060JxzehoOrD%2b58fQ12jCkDTC8gO1xcFC7SFzjx6yzNYqo0VZB%2bkLW4pN9sC2aHrgKVw9h54Rrr6mqVzZZGUKJMvaKdxskbbkDKff9WYWswCgCj6m9SqLPkhSpn51z%2bMKNLUV7g91V0zC620k2jCzcnw%2bMN1o6ysMIxFWkiVhwusNJ2chQ4X%2fB5tT8IKaa%2bpEirFWDdOfSws5kxMYkJ%2bJsud0SXyI46nvRx3xJwC3hg3H9PygCAg3JuobsrS42rSB24Crq%2fA9X2uOvLmme6NlayxlIq7AquNJdY%2bqAUZTA5Gq8GKeEtkJZphOMU9X42VWrmdDv%2bgJ7FWe5k3JFz8FcnSPr7Ltdww73Iz3nVL3OXLyQTDpOV2GzrriiI3daa6jY29qzvp0fPle9%2f0LICNu0aW2Stqedx9U%2b2QhjAC4MbdipJS58xeoDEiR%2fYD32563JJI0cl5%2fk9nJFFl5cm3eN5KFO2kGlyEwdj9icCrewI6Dp8VCQQAAA%3d%3d) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1TTW%2faQBC9R8p%2fmPoEErVDVVW9UCkxpaUSgQJqjtZiD%2faCvWvNrusi5cdndk2o%2byElJ%2b%2fMvDfz5sNbNHaNpimtub56hIOWCo5SZROpFBI8aDrOLVYGtLoY8%2bx%2f0G9651H8dYAoeoS2QEKYSSVNgRl8moDS7eDt%2bN1NNnQpunhXHiYTCGZCloHjnkPfG2zwXlTooy0X060JxzehoOrD%2b58fQ12jCkDTC8gO1xcFC7SFzjx6yzNYqo0VZB%2bkLW4pN9sC2aHrgKVw9h54Rrr6mqVzZZGUKJMvaKdxskbbkDKff9WYWswCgCj6m9SqLPkhSpn51z%2bMKNLUV7g91V0zC620k2jCzcnw%2bMN1o6ysMIxFWkiVhwusNJ2chQ4X%2fB5tT8IKaa%2bpEirFWDdOfSws5kxMYkJ%2bJsud0SXyI46nvRx3xJwC3hg3H9PygCAg3JuobsrS42rSB24Crq%2fA9X2uOvLmme6NlayxlIq7AquNJdY%2bqAUZTA5Gq8GKeEtkJZphOMU9X42VWrmdDv%2bgJ7FWe5k3JFz8FcnSPr7Ltdww73Iz3nVL3OXLyQTDpOV2GzrriiI3daa6jY29qzvp0fPle9%2f0LICNu0aW2Stqedx9U%2b2QhjAC4MbdipJS58xeoDEiR%2fYD32563JJI0cl5%2fk9nJFFl5cm3eN5KFO2kGlyEwdj9icCrewI6Dp8VCQQAAA%3d%3d&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI1TTW%2faQBC9R8p%2fmPoEErVDVVW9UCkxpaUSgQJqjtZiD%2faCvWvNrusi5cdndk2o%2byElJ%2b%2fMvDfz5sNbNHaNpimtub56hIOWCo5SZROpFBI8aDrOLVYGtLoY8%2bx%2f0G9651H8dYAoeoS2QEKYSSVNgRl8moDS7eDt%2bN1NNnQpunhXHiYTCGZCloHjnkPfG2zwXlTooy0X060JxzehoOrD%2b58fQ12jCkDTC8gO1xcFC7SFzjx6yzNYqo0VZB%2bkLW4pN9sC2aHrgKVw9h54Rrr6mqVzZZGUKJMvaKdxskbbkDKff9WYWswCgCj6m9SqLPkhSpn51z%2bMKNLUV7g91V0zC620k2jCzcnw%2bMN1o6ysMIxFWkiVhwusNJ2chQ4X%2fB5tT8IKaa%2bpEirFWDdOfSws5kxMYkJ%2bJsud0SXyI46nvRx3xJwC3hg3H9PygCAg3JuobsrS42rSB24Crq%2fA9X2uOvLmme6NlayxlIq7AquNJdY%2bqAUZTA5Gq8GKeEtkJZphOMU9X42VWrmdDv%2bgJ7FWe5k3JFz8FcnSPr7Ltdww73Iz3nVL3OXLyQTDpOV2GzrriiI3daa6jY29qzvp0fPle9%2f0LICNu0aW2Stqedx9U%2b2QhjAC4MbdipJS58xeoDEiR%2fYD32563JJI0cl5%2fk9nJFFl5cm3eN5KFO2kGlyEwdj9icCrewI6Dp8VCQQAAA%3d%3d&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1TTW%2faQBC9R8p%2fmPoEErVDVVW9UCkxpaUSgQJqjtZiD%2faCvWvNrusi5cdndk2o%2byElJ%2b%2fMvDfz5sNbNHaNpimtub56hIOWCo5SZROpFBI8aDrOLVYGtLoY8%2bx%2f0G9651H8dYAoeoS2QEKYSSVNgRl8moDS7eDt%2bN1NNnQpunhXHiYTCGZCloHjnkPfG2zwXlTooy0X060JxzehoOrD%2b58fQ12jCkDTC8gO1xcFC7SFzjx6yzNYqo0VZB%2bkLW4pN9sC2aHrgKVw9h54Rrr6mqVzZZGUKJMvaKdxskbbkDKff9WYWswCgCj6m9SqLPkhSpn51z%2bMKNLUV7g91V0zC620k2jCzcnw%2bMN1o6ysMIxFWkiVhwusNJ2chQ4X%2fB5tT8IKaa%2bpEirFWDdOfSws5kxMYkJ%2bJsud0SXyI46nvRx3xJwC3hg3H9PygCAg3JuobsrS42rSB24Crq%2fA9X2uOvLmme6NlayxlIq7AquNJdY%2bqAUZTA5Gq8GKeEtkJZphOMU9X42VWrmdDv%2bgJ7FWe5k3JFz8FcnSPr7Ltdww73Iz3nVL3OXLyQTDpOV2GzrriiI3daa6jY29qzvp0fPle9%2f0LICNu0aW2Stqedx9U%2b2QhjAC4MbdipJS58xeoDEiR%2fYD32563JJI0cl5%2fk9nJFFl5cm3eN5KFO2kGlyEwdj9icCrewI6Dp8VCQQAAA%3d%3d&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Result == "Fail"
| where Method == "PerformanceCounterCategory_Create_Obsolete_CCD"
| where Branch !startswith "refs/pull"
| project 
    Branch,
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Result,Finished,
  Duration,
Build = tostring(parse_json(Properties).BuildNumber) ,  Console_log = Message,   StackTrace  
```

|Branch|Pipeline|Pipeline_Configuration|OS|Arch|Result|Finished|Duration|Build|Console_log|StackTrace|
|---|---|---|---|---|---|---|---|---|---|---|
|refs/heads/main|runtime|Release|windows.10.amd64.client19h1.open.rt|x86|Fail|2021-06-16 21:32:44.3850000|1.603|20210616.88|System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.|   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)<br>   at System.Diagnostics.PerformanceCounterLib.get_NameTable()<br>   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()<br>   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category)<br>   at System.Diagnostics.PerformanceCounterCategory.Exists(String categoryName, String machineName)<br>   at System.Diagnostics.Tests.Helpers.DeleteCategory(String name) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 46<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-06-23 07:53:01.9000000|0.047|20210623.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-06-26 09:01:39.0980000|3.12|20210626.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-06-27 08:15:18.1600000|10.65|20210627.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-06-29 07:47:00.4040000|3.22|20210629.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-06-29 07:47:00.4040000|3.22|20210629.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstressregs|Release|windows.10.arm64v8.open|arm64|Fail|2021-07-04 12:01:35.1880000|3.637|20210704.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstressregs|Release|windows.10.arm64v8.open|arm64|Fail|2021-07-04 13:21:09.9540000|3.593|20210704.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-07-05 09:58:12.6250000|0.11|20210705.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress2-jitstressregs|Release|windows.10.arm64v8.open|arm64|Fail|2021-08-07 12:15:32.8100000|11.46|20210807.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|
|refs/heads/main|runtime-coreclr libraries-jitstress|Release|windows.10.arm64v8.open|arm64|Fail|2021-08-09 10:20:41.3910000|3.797|20210809.1|System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.|   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237<br>   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131|

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress2-jitstressregs 20210821.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1309826&view=ms.vss-test-web.build-test-results-tab&runId=38560078&resultId=119633&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs1-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

```
**Error message:**
```
System.InvalidOperationException : Cannot create Performance Category
'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.


Stack trace
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20210904.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1343241&view=ms.vss-test-web.build-test-results-tab&runId=39339644&paneView=debug&resultId=124577)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs8-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

```
**Error message:**
```
System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.


Stack trace
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20211012.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1415249&view=ms.vss-test-web.build-test-results-tab&runId=41006756&resultId=124648&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

```
**Error message:**
```
System.InvalidOperationException : Cannot create Performance Category 'PerformanceCounterCategory_Create_Obsolete_CCD_Counter_Category' because it already exists.


Stack trace
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 131
```
