### ISSUE TITLE
[Mono][Android][Test] System.ArgumentNullException: Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54974]
Fail test:

- tracing/eventpipe/complus_config/name_config_with_pid/name_config_with_pid.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54516-merge-d98c875f67114f4dbf/PayloadGroup0/console.ad8277f6.log?sv=2019-07-07&se=2021-07-20T15%3A01%3A22Z&sr=c&sp=rl&sig=fGYG9mtBnx%2Bo7uMjVvk1T12aY5r6riQmE9IRkexYFVg%3D)

```
      06-30 15:29:43.213  4486  4503 I DOTNET  : MonoRunner initialize,, entryPointLibName=name_config_with_pid.dll
      06-30 15:29:43.213  4486  4503 D DOTNET  : file_path: /data/user/0/net.dot.tracing_eventpipe/files/runtimeconfig.bin
      06-30 15:29:43.216  4486  4503 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.245  4486  4503 D DOTNET  : assembly_preload_hook: name_config_with_pid.dll (null) /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.245  4486  4503 D DOTNET  : Executable: name_config_with_pid.dll
      06-30 15:29:43.245  4486  4503 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.246  4486  4503 D DOTNET  : assembly_preload_hook: System.Diagnostics.Process  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.246  4486  4503 D DOTNET  : assembly_preload_hook: System.ComponentModel.Primitives  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.246  4486  4503 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.247  4486  4503 D DOTNET  : assembly_preload_hook: System.ComponentModel  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.247  4486  4503 D DOTNET  : assembly_preload_hook: System.Collections.NonGeneric  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.247  4486  4503 D DOTNET  : assembly_preload_hook: System.Threading.ThreadPool  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.247  4486  4503 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.247  4486  4503 D DOTNET  : assembly_preload_hook: System.Threading.Thread  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.248  4486  4503 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.tracing_eventpipe/files
      06-30 15:29:43.309  4486  4503 E mono    : 
      06-30 15:29:43.309  4486  4503 E mono    : Unhandled Exception:
      06-30 15:29:43.309  4486  4503 E mono    : System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
      06-30 15:29:43.309  4486  4503 E mono    :    at System.IO.Path.Combine(String path1, String path2) in System.Private.CoreLib.dll:token 0x6005518+0x6
      06-30 15:29:43.309  4486  4503 E mono    :    at NameConfigWithPid.Main(String[] args) in name_config_with_pid.dll:token 0x6000001+0x53
      06-30 15:29:43.309  4486  4503 E DOTNET  : UnhandledException: System.ArgumentNullException Value cannot be null. (Parameter 'path1')    at System.IO.Path.Combine(String path1, String path2) in System.Private.CoreLib.dll:token 0x6005518+0x6
      06-30 15:29:43.309  4486  4503 E DOTNET  :    at NameConfigWithPid.Main(String[] args) in name_config_with_pid.dll:token 0x6000001+0x53
      06-30 15:29:43.357  1794  1941 I ActivityManager: Process net.dot.tracing_eventpipe (pid 4486) has died: fore FGS 
      06-30 15:29:43.358  1794  1941 W ActivityManager: Crash of app net.dot.tracing_eventpipe running instrumentation ComponentInfo{net.dot.tracing_eventpipe/net.dot.MonoRunner}
      06-30 15:29:43.358  1794  4146 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-30 15:29:43.358  1794  4146 W Binder  : java.lang.Throwable
      06-30 15:29:43.358  1794  4146 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-30 15:29:43.358  1794  4146 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-30 15:29:43.358  1794  4146 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-30 15:29:43.361  4475  4475 D AndroidRuntime: Shutting down VM
```

**Comment by fanyang-mono** [comment]
Moving to 8.0.0

**Comment by fanyang-mono** [comment]
Moving to 9.0.0
