### ISSUE TITLE
[iOS] System.Linq.Expressions.Tests.NewWithByRefParameterTests.CreateByRefAliasingCompiled failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55069]
The `System.Linq.Expressions.Tests.NewWithByRefParameterTests.CreateByRefAliasingCompiled` library test fails in #54970 with the following error:
```
      <test name="System.Linq.Expressions.Tests.NewWithByRefParameterTests.CreateByRefAliasingCompiled" type="System.Linq.Expressions.Tests.NewWithByRefParameterTests" method="CreateByRefAliasingCompiled" time="0.0004832" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: 16\nActual:   12]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.NewWithByRefParameterTests.CreateByRefAliasing(Boolean useInterpreter)
   at System.Linq.Expressions.Tests.NewWithByRefParameterTests.CreateByRefAliasingCompiled()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
```
https://github.com/dotnet/runtime/pull/54970/checks?check_run_id=2961997278

cc @steveisok

**Comment by MaximLipnin** [comment]
Setting `<IsInterpreting Condition="'$(TargetsiOS)' == 'true' or '$(TargetstvOS)' == 'true' or '$(TargetsMacCatalyst)' == 'true'">true</IsInterpreting>` in the test project file helped to address the issue, closing it.
