### ISSUE TITLE
[iOS] Failures in System.Linq.Expressions.Tests.CompilerTests test suite

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55065]
When trying to enable the interpretation mode for LambdaCompiler on iOS-like targets in https://github.com/dotnet/runtime/pull/54970, I get the test failures in `System.Linq.Expressions.Tests.CompilerTests` test suite like below:
```
    <collection total="8" passed="2" failed="6" skipped="0" name="Test collection for System.Linq.Expressions.Tests.CompilerTests" time="0.006">
      <test name="System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_ShareReferences" type="System.Linq.Expressions.Tests.CompilerTests" method="EmitConstantsToIL_ShareReferences" time="0.0014656" result="Fail">
        <failure exception-type="System.TypeLoadException">
          <message><![CDATA[System.TypeLoadException : Could not resolve type with token 01000085 from typeref (expected class 'System.Runtime.CompilerServices.Closure' in assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_ShareReferences()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_ReferenceTypes" type="System.Linq.Expressions.Tests.CompilerTests" method="EmitConstantsToIL_ReferenceTypes" time="0.0001519" result="Fail">
        <failure exception-type="System.TypeLoadException">
          <message><![CDATA[System.TypeLoadException : Could not resolve type with token 01000085 from typeref (expected class 'System.Runtime.CompilerServices.Closure' in assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[String](String value, Int32 expectedCount)
   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[String](String value)
   at System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_ReferenceTypes()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Linq.Expressions.Tests.CompilerTests.VariableBinder_CatchBlock_Filter2" type="System.Linq.Expressions.Tests.CompilerTests" method="VariableBinder_CatchBlock_Filter2" time="0.002529" result="Pass" />
      <test name="System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_NonNullableValueTypes" type="System.Linq.Expressions.Tests.CompilerTests" method="EmitConstantsToIL_NonNullableValueTypes" time="0.000228" result="Fail">
        <failure exception-type="System.TypeLoadException">
          <message><![CDATA[System.TypeLoadException : Could not resolve type with token 01000085 from typeref (expected class 'System.Runtime.CompilerServices.Closure' in assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[Boolean](Boolean value, Int32 expectedCount)
   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[Boolean](Boolean value)
   at System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_NonNullableValueTypes()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Linq.Expressions.Tests.CompilerTests.VariableBinder_CatchBlock_Filter1" type="System.Linq.Expressions.Tests.CompilerTests" method="VariableBinder_CatchBlock_Filter1" time="0.0002116" result="Pass" />
      <test name="System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_NullableValueTypes" type="System.Linq.Expressions.Tests.CompilerTests" method="EmitConstantsToIL_NullableValueTypes" time="0.0005196" result="Fail">
        <failure exception-type="System.TypeLoadException">
          <message><![CDATA[System.TypeLoadException : Could not resolve type with token 01000085 from typeref (expected class 'System.Runtime.CompilerServices.Closure' in assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[Nullable`1](Nullable`1 value, Int32 expectedCount)
   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[Nullable`1](Nullable`1 value)
   at System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_NullableValueTypes()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_LiftedToClosure" type="System.Linq.Expressions.Tests.CompilerTests" method="EmitConstantsToIL_LiftedToClosure" time="0.0001895" result="Fail">
        <failure exception-type="System.TypeLoadException">
          <message><![CDATA[System.TypeLoadException : Could not resolve type with token 01000085 from typeref (expected class 'System.Runtime.CompilerServices.Closure' in assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[DateTime](DateTime value, Int32 expectedCount)
   at System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_LiftedToClosure()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_Enums" type="System.Linq.Expressions.Tests.CompilerTests" method="EmitConstantsToIL_Enums" time="0.0002065" result="Fail">
        <failure exception-type="System.TypeLoadException">
          <message><![CDATA[System.TypeLoadException : Could not resolve type with token 01000085 from typeref (expected class 'System.Runtime.CompilerServices.Closure' in assembly 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')]]></message>
          <stack-trace><![CDATA[   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[ConstantsEnum](ConstantsEnum value, Int32 expectedCount)
   at System.Linq.Expressions.Tests.CompilerTests.VerifyEmitConstantsToIL[ConstantsEnum](ConstantsEnum value)
   at System.Linq.Expressions.Tests.CompilerTests.EmitConstantsToIL_Enums()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
    </collection>
```
https://github.com/dotnet/runtime/pull/54970/checks?check_run_id=2961997278

cc @steveisok

**Comment by MaximLipnin** [comment]
Perhaps, it may be addressed by setting the right condition for `IsInterpreting` property in the test csproj file.

**Comment by MaximLipnin** [comment]
Setting `<IsInterpreting Condition="'$(TargetsiOS)' == 'true' or '$(TargetstvOS)' == 'true' or '$(TargetsMacCatalyst)' == 'true'">true</IsInterpreting>`  in the test project file did the trick, closing it.
