### ISSUE TITLE
[iOS] PlatformNotSupportedException in System.Linq.Expressions.Tests.GetDelegateTypeTests test suite

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55068]
When trying to enable the interpretation mode for LambdaCompiler on iOS-like targets in #54970, some of the tests from the `System.Linq.Expressions.Tests.GetDelegateTypeTests` library test suite fail with `PlatformNotSupportedException`:
```
System.PlatformNotSupportedException : Operation is not supported on this platform.
   at System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewCustomDelegate(Type[] types)
   at System.Linq.Expressions.Compiler.DelegateHelpers.MakeNewDelegate(Type[] types)
   at System.Linq.Expressions.Compiler.DelegateHelpers.MakeDelegateType(Type[] types)
   at System.Linq.Expressions.Expression.GetDelegateType(Type[] typeArgs)
   at System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeFunc(Type[] typeArgs)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
The failing tests are:
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeFunc(typeArgs: [typeof(string), typeof(System.Double*), typeof(int)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.Int32*)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(int), typeof(System.String*), typeof(double)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(int), typeof(System.Int32&amp;), typeof(string)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(string), typeof(System.Double*), typeof(int)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.String*)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.Collections.Generic.List&lt;int&gt;), typeof(System.Collections.Generic.List&lt;int&gt;), typeof(System.Collections.Generic.List&lt;int&gt;), typeof(System.Collections.Generic.List&lt;int&gt;), typeof(System.Collections.Generic.List&lt;int&gt;), ...])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.String*), typeof(System.String*), typeof(System.String*), typeof(System.String*), typeof(System.String*), ...])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.Span&lt;char&gt;)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(int), typeof(int), typeof(int), typeof(int), typeof(int), ...])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.Int32&amp;)])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.Int32*), typeof(System.Int32*), typeof(System.Int32*), typeof(System.Int32*), typeof(System.Int32*), ...])
- System.Linq.Expressions.Tests.GetDelegateTypeTests.CantBeAction(typeArgs: [typeof(System.Double&amp;), typeof(System.Double&amp;), typeof(System.Double&amp;), typeof(System.Double&amp;), typeof(System.Double&amp;), ...])

https://github.com/dotnet/runtime/pull/54970/checks?check_run_id=2961997278

cc @steveisok

**Comment by MaximLipnin** [comment]
Setting `<IsInterpreting Condition="'$(TargetsiOS)' == 'true' or '$(TargetstvOS)' == 'true' or '$(TargetsMacCatalyst)' == 'true'">true</IsInterpreting>` in the test project file helped to address the issue, closing it.
