### ISSUE TITLE
[iOS] System.Dynamic.Tests.InvokeMemberBindingTests.InvokeVirtualMethod(value: 0) failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55070]
The `System.Dynamic.Tests.InvokeMemberBindingTests.InvokeVirtualMethod(value: 0)` library test fails in #54970 with the following error:
```
Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: 0\nActual:   -1307871456\n          ↑ (pos 0)
at System.Linq.Expressions.Interpreter.ActionCallInstruction`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] arguments)
   at System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke(LightLambda targetLambda, Object[] args)
   at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] arguments)
   at System.Dynamic.Tests.InvokeMemberBindingTests.InvokeVirtualMethod(Object value)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
https://github.com/dotnet/runtime/pull/54970/checks?check_run_id=2961997278

cc @steveisok

**Comment by mdh1418** [comment]
Currently hitting an error similar to this when testing on iOS locally https://github.com/dotnet/runtime/issues/73041

**Comment by mkhamoyan** [comment]
Still hitting an error , checked on CI https://github.com/dotnet/runtime/pull/73619
