### ISSUE TITLE
[iOS] System.Dynamic.Tests.InvokeMemberBindingTests.InvokeFuncMember failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55071]
The `System.Dynamic.Tests.InvokeMemberBindingTests.InvokeFuncMember` library test fails in #54970 with the following error:
```
System.ArgumentException : Expression of type 'System.Int32' cannot be used for parameter of type 'System.Object' (Parameter 'arg2')

    at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi, String methodParamName, String argumentParamName)
   at System.Linq.Expressions.Expression.Invoke(Expression expression, Expression arg0, Expression arg1, Expression arg2)
   at System.Linq.Expressions.Expression.Invoke(Expression expression, IEnumerable`1 arguments)
   at System.Linq.Expressions.DynamicExpression.Reduce()
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileGotoExpression(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr, Boolean asVoid)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(Expression expr, Boolean asVoid)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockStart(BlockExpression node)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockExpression(Expression expr, Boolean asVoid)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.Compile(Expression expr)
   at System.Linq.Expressions.Interpreter.LightCompiler.CompileTop(LambdaExpression node)
   at System.Linq.Expressions.Expression`1[[<>A{00000004}`3[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Linq.Expressions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Compile()
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[<>A{00000004}`3](CallSite`1 site, Object[] args)
   at System.Runtime.CompilerServices.CallSiteOps.Bind[<>A{00000004}`3](CallSiteBinder binder, CallSite`1 site, Object[] args)
   at System.Linq.Expressions.Interpreter.FuncCallInstruction`4[[System.Runtime.CompilerServices.CallSiteBinder, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Runtime.CompilerServices.CallSite`1[[<>A{00000004}`3[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Linq.Expressions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[<>A{00000004}`3[[System.Runtime.CompilerServices.CallSite, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Linq.Expressions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Linq.Expressions.Interpreter.LightLambda.RunVoid(Object[] arguments)
   at System.Dynamic.Tests.InvokeMemberBindingTests.InvokeFuncMember()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture
```
https://github.com/dotnet/runtime/pull/54970/checks?check_run_id=2961997278

cc @steveisok

**Comment by mkhamoyan** [comment]
Still hitting an error , checked on https://github.com/dotnet/runtime/pull/73619

**Comment by mkhamoyan** [comment]
cc @vitek-karas
