### ISSUE TITLE
Failing SendReceive_MemoryArrayTask.SendAsync_ConcurrentDispose_SucceedsOrThrowsAppropriateException  test

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#55085]
```
pushd .
/tmp/helix/working/A15308CE/p/dotnet exec --runtimeconfig System.Net.Sockets.Tests.runtimeconfig.json --depsfile System.Net.Sockets.Tests.deps.json xunit.console.dll System.Net.Sockets.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/A15308CE/w/B05D09BF/e /private/tmp/helix/working/A15308CE/w/B05D09BF/e
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 1216 of 1677 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 12)
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
    System.Net.Sockets.Tests.SendReceive_MemoryArrayTask.SendAsync_ConcurrentDispose_SucceedsOrThrowsAppropriateException [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Socket is already connected 127.0.0.1:62820
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3201,0): at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(855,0): at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
        /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestExtensions.cs(54,0): at System.Net.Sockets.Tests.SocketTestExtensions.CreateConnectedSocketPair(Boolean ipv6, Boolean dualModeClient)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs(855,0): at System.Net.Sockets.Tests.SendReceive`1.SendAsync_ConcurrentDispose_SucceedsOrThrowsAppropriateException()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Sockets.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 1890, Errors: 0, Failed: 1, Skipped: 1, Time: 5.184s
/private/tmp/helix/working/A15308CE/w/B05D09BF/e
----- end Fri Jul 2 10:06:11 EDT 2021 ----- exit code 1 ----------------------------------------------------------
ulimit -c value: unlimited

```
log https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54250-merge-45730aa3d31442e0ab/System.Net.Sockets.Tests/console.13f3b061.log?sv=2019-07-07&se=2021-07-22T14%3A04%3A00Z&sr=c&sp=rl&sig=x5qtTw40caK77xqoRM%2Fxmm9RS7F%2FvghBnbL39dGEs4M%3D
build https://dev.azure.com/dnceng/public/_build/results?buildId=1217853&view=logs&jobId=4724cd84-0a26-56bc-9b1d-ca1983f340b0&j=4724cd84-0a26-56bc-9b1d-ca1983f340b0&t=bd2814f3-22fe-5d50-acb1-9c92a93a7f5f

**Comment by wfurt** [comment]
seems similar to  #52141 and #50271

**Comment by mdh1418** [comment]
Seeing this fail on https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54845-merge-c8d558ec775f4b83a5/System.Net.Sockets.Tests/console.4f36016a.log?sv=2019-07-07&se=2021-08-08T17%3A43%3A33Z&sr=c&sp=rl&sig=v7AkUOlF%2BTZv7IHldTGCTCnOnoCxtaWLBL%2FmBeUl1fA%3D on unrelated PR https://github.com/dotnet/runtime/pull/54845

**Comment by karelz** [comment]
Failures 5/20-7/20 (incl. PRs):

Day | Run | OS
-- | -- | --
6/24 | PR #54451 | OSX.1014.Amd64.Open
6/24 | PR #54681 | OSX.1015.Amd64.Open
6/25 | PR #54451 | OSX.1014.Amd64.Open
7/1 | PR #54266 | OSX.1015.Amd64.Open
7/2 | PR #54250 | OSX.1015.Amd64.Open
7/19 | PR #54845 | OSX.1014.Amd64.Open

**Comment by wfurt** [comment]
triage: we should check for recent failures and close otherwise.

**Comment by antonfirsov** [comment]
No failures in the last 90 days, closing.
