### ISSUE TITLE
[iOS] Test failed: ManagedTests.DynamicCSharp.Conformance.dynamic.Variance.assign.assignment07.assignment07.C.DynamicCSharpRunTest

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55119]
When running `System.Dynamic.Runtime.Test` library test suite in #54970, `ManagedTests.DynamicCSharp.Conformance.dynamic.Variance.assign.assignment07.assignment07.C.DynamicCSharpRunTest` fails in CI with the following:

```
System.InvalidCastException :
    at System.Array.InternalSetValue(Object value, IntPtr index)
    at System.Array.SetValue(Object value, Int32 index)
    at System.Linq.Expressions.Interpreter.SetArrayItemInstruction.Run(InterpretedFrame frame)
    at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
    at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments)
    at System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke(LightLambda targetLambda, Object[] args)
    at System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(InterpretedFrame frame)
    at System.Linq.Expressions.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame frame)
    at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] arguments)
    at ManagedTests.DynamicCSharp.Conformance.dynamic.Variance.assign.assignment07.assignment07.C.MainMethod()
    at ManagedTests.DynamicCSharp.Conformance.dynamic.Variance.assign.assignment07.assignment07.C.DynamicCSharpRunTest()
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

cc @steveisok

**Comment by mdh1418** [comment]
Currently hitting an error similar to this when testing on iOS locally https://github.com/dotnet/runtime/issues/73041
