### ISSUE TITLE
System.Linq.Parallel.Tests failed with System.OperationCanceledException : The operation was canceled.

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55167]
Run: [runtime-coreclr libraries-jitstress 20210704.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1219863&view=ms.vss-test-web.build-test-results-tab&runId=36366366&resultId=150004&paneView=debug)

Failed tests:
```
net6.0-Linux-Release-arm-CoreCLR_checked-jitstress1_tiered-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.Linq.Parallel.Tests.GroupByTests.GroupBy_ResultSelector_CustomComparator(labeled: Array-Ordered, count: 8)
- System.Linq.Parallel.Tests.GroupJoinTests.GroupJoin(left: Array-Ordered, leftCount: 16, rightCount: 1)
- System.Linq.Parallel.Tests.GroupJoinTests.GroupJoin(left: Enumerable.Range-Ordered, leftCount: 1, rightCount: 16)
- System.Linq.Parallel.Tests.GroupByTests.GroupBy_ElementSelector_ResultSelector(labeled: Partitioner-Ordered, count: 16)

```

**Error message:**
```
System.AggregateException : One or more errors occurred. (The operation was canceled.) (The operation was canceled.)
---- System.OperationCanceledException : The operation was canceled.
---- System.OperationCanceledException : The operation was canceled.


Stack trace
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/QueryTaskGroupState.cs:line 131
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.Spool(QueryTaskGroupState groupState, PartitionedStream`2 partitions, Shared`1 results, TaskScheduler taskScheduler) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/OrderPreservingSpoolingTask.cs:line 121
   at System.Linq.Parallel.OrderPreservingMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Merging/OrderPreservingMergeHelper.cs:line 60
   at System.Linq.Parallel.MergeExecutor`1.Execute() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Merging/MergeExecutor.cs:line 102
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Merging/MergeExecutor.cs:line 91
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/PartitionedStreamMerger.cs:line 60
   at System.Linq.Parallel.SelectQueryOperator`2.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/Unary/SelectQueryOperator.cs:line 52
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/UnaryQueryOperator.cs:line 161
   at System.Linq.Parallel.GroupByQueryOperator`3.WrapPartitionedStreamHelperOrdered[TKey](PartitionedStream`2 hashStream, IPartitionedStreamRecipient`1 recipient, CancellationToken cancellationToken) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/Unary/GroupByQueryOperator.cs:line 168
   at System.Linq.Parallel.GroupByQueryOperator`3.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/Unary/GroupByQueryOperator.cs:line 75
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/UnaryQueryOperator.cs:line 162
   at System.Linq.Parallel.PartitionerQueryOperator`1.PartitionerQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/PartitionerQueryOperator.cs:line 199
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/UnaryQueryOperator.cs:line 130
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/UnaryQueryOperator.cs:line 130
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/QueryOperator.cs:line 163
   at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/QueryOpeningEnumerator.cs:line 152
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/QueryOperators/QueryOpeningEnumerator.cs:line 107
   at System.Linq.Parallel.Tests.GroupByTests.GroupBy_ElementSelector_ResultSelector(Labeled`1 labeled, Int32 count) in /_/src/libraries/System.Linq.Parallel/tests/QueryOperators/GroupByTests.cs:line 441
----- Inner Stack Trace #1 (System.OperationCanceledException) -----
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Utils/Sorting.cs:line 246
   at System.Linq.Parallel.SortHelper`2.Sort() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Utils/Sorting.cs:line 196
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/OrderPreservingSpoolingTask.cs:line 135
   at System.Linq.Parallel.SpoolingTaskBase.Work() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/SpoolingTaskBase.cs:line 73
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/QueryTask.cs:line 109
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/QueryTask.cs:line 76
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2391
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2370
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 294
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 294
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2363
----- Inner Stack Trace #2 (System.OperationCanceledException) -----
   at System.Linq.Parallel.SortHelper`2.BuildKeysFromSource(GrowingArray`1& keys, List`1& values) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Utils/Sorting.cs:line 246
   at System.Linq.Parallel.SortHelper`2.Sort() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Utils/Sorting.cs:line 196
   at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/OrderPreservingSpoolingTask.cs:line 135
   at System.Linq.Parallel.SpoolingTaskBase.Work() in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/SpoolingTaskBase.cs:line 73
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/QueryTask.cs:line 109
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o) in /_/src/libraries/System.Linq.Parallel/src/System/Linq/Parallel/Scheduling/QueryTask.cs:line 76
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2391
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2370
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 294
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 294
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2363
```

**Comment by adamsitnik** [comment]
@stephentoub have we recently introduced any changes that could disturb this test?

**Comment by stephentoub** [comment]
Not to my knowledge.  Note this is from JitStress.

**Comment by AriNuer** [comment]
Failed again in [runtime 20210720.80](https://dev.azure.com/dnceng/public/_build/results?buildId=1249365&view=ms.vss-test-web.build-test-results-tab&runId=37103858&resultId=168072&paneView=debug)

Failed test:
```
net6.0-Browser-Release-wasm-Mono_Release-wasmtestonbrowser-Ubuntu.1804.Amd64.Open

- System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendReceive_VaryingLengthBuffers_Success(server: ws://127.0.0.1:36969/WebSocket/EchoWebSocket.ashx)
```
**Error message:**
```
System.OperationCanceledException : The operation was canceled.


Stack trace
   at System.Threading.Channels.AsyncOperation`1[[System.Net.WebSockets.ReceivePayload, System.Net.WebSockets.Client, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetResult(Int16 token) in System.Threading.Channels.dll:token 0x600001d+0x53
   at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x1e1
   at System.Net.WebSockets.BrowserWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.Client.dll:token 0x6000049+0x2b4
   at System.Net.WebSockets.WebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken) in System.Net.WebSockets.dll:token 0x600005a+0x97
   at System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync(WebSocket ws, ArraySegment`1 arraySegment, CancellationToken cancellationToken) in System.Net.WebSockets.Client.Tests.dll:token 0x600012c+0x87
   at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_VaryingLengthBuffers_Success(Uri server) in System.Net.WebSockets.Client.Tests.dll:token 0x600013a+0x23a
--- End of stack trace from previous location ---
```

**Comment by stephentoub** [comment]
That's https://github.com/dotnet/runtime/issues/53957 rather than this issue.

**Comment by danmoseley** [comment]
The top issue happened for 5 days in a row and not in the 18 days since. I do not see an obvious change that fixed it, but it's apparently fixed.

https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2QQU8CMRCF7yT8h3FPmGgXEg9e1kQwGIwaFBKPpOyObqXbWTttcI0%2f3tJFAcOpmfb1e%2b%2fNHNk9I3vtuNv5hndSBlbKFJkyBi28kF1NHFYMZP6GSXFMekfLqApnK1iXaBHGyigusYCrDAyte%2beDfr847XbS9Fcxb2qELINk1nCgixsl3wyxUzmLeYjHYmopR%2bY4JDt0mzt%2bHUul916GVpq8hBN20jpeK1dCYvGV09rrjW5jzr6qpFVfCDl543qnsGzgAV1JxRk8efR4rZXkHbQNuo%2fcBr5X5kNMpZVao95GvrXk62S%2fZkQ%2byuoQQfyZpge6NkJsFSHDZtEWnaHG3JFdjDw7qkZU1cEzXCRw1GcQGX4ZynkxuOxfCGlD47wUVKOJ2zq6g9kmHv5bQrfzA%2f%2flJtQqAgAA&web=0

TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-100d)
//| where Type == "System.Diagnostics.Tests.ProcessTests"
| where Result == "Fail"
| where Branch !startswith "refs/pull"
//| summarize count() by Method, QueueAlias
| where  Type startswith "System.Linq.Parallel.Tests.Group"
//| where QueueName startswith "osx//"
//| where Method == "GroupBy_ResultSelector_CustomComparator" 
//| where QueueName1 == "ubuntu.1804.armarch.open"
| summarize count() by Started, QueueAlias


|Started|QueueAlias|count_|
|---|---|---|
|2021-07-04 08:18:44.7660000|ubuntu.1804.arm32.open|4|
|2021-07-05 08:15:28.7380000|ubuntu.1804.arm32.open|3|
|2021-07-06 08:12:33.6750000|ubuntu.1804.arm32.open|3|
|2021-07-07 08:18:23.5950000|ubuntu.1804.arm32.open|2|
|2021-07-08 09:01:09.2620000|ubuntu.1804.arm32.open|1|
