### ISSUE TITLE
[HTTP/3] ServerCertificateCustomValidationCallback causes connection error

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55192]
Adding `ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator` causes a connection error on send.

Code:
```cs
// HTTP/3
var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

using (var client = new HttpClient(httpClientHandler))
{
    var request = new HttpRequestMessage(HttpMethod.Get, $"https://127.0.0.1:{http3Port}/");
    request.Version = HttpVersion.Version30;
    request.VersionPolicy = HttpVersionPolicy.RequestVersionExact;

    // Act
    var response = await client.SendAsync(request).DefaultTimeout();

    // Assert
    response.EnsureSuccessStatusCode();
    Assert.Equal(HttpVersion.Version30, response.Version);
    var responseText = await response.Content.ReadAsStringAsync().DefaultTimeout();
    Assert.Equal("hello, world", responseText);
}
```

Error:
```
    System.Net.Http.HttpRequestException : Connection has been shutdown by transport. Error Code: 0x8041012A (127.0.0.1:5005)
    ---- System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: 0x8041012A
```

**Comment by wfurt** [comment]
BTW if you register real callback do you see the correct certificate there?

**Comment by JamesNK** [comment]
Same error, breakpoint in callback never hit:
```cs
var httpClientHandler = new HttpClientHandler();
httpClientHandler.ServerCertificateCustomValidationCallback = (_, __, ___, ____) =>
{
    return true;
};
```

**Comment by wfurt** [comment]
```
HandleEventPeerCertificateReceived going to call System.Net.Security.RemoteCertificateValidationCallback
System.InvalidCastException: Unable to cast object of type 'System.Net.Quic.Implementations.MsQuic.MsQuicConnection' to type 'System.Net.Http.HttpRequestMessage'.
   at System.Net.Http.ConnectHelper.CertificateCallbackMapper.<.ctor>b__2_0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in C:\Users\test\github\wfurt-runtime2\src\libraries\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\ConnectHelper.cs:line 32
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventPeerCertificateReceived(State state, ConnectionEvent& connectionEvent) in C:\Users\test\github\wfurt-runtime2\src\libraries\System.Net.Quic\src\System\Net\Quic\Implementations\MsQuic\MsQuicConnection.cs:line 401
QUIC_CONNECTION_EVENT_TYPE.PEER_CERTIFICATE_RECEIVED returning 2151743491 0x80410003
```
this looks like a problem mapping (Ms)Quic connection back to `HttpRequestMessage`

#55193 may have similar reason.

**Comment by ManickaP** [comment]
Got repro, will continue on Mon.
