### ISSUE TITLE
Test failure:System.Linq.Tests.LifecycleTests.UnaryOperations_SourceEnumeratorDisposed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55252]
Run: [runtime 20210706.106](https://dev.azure.com/dnceng/public/_build/results?buildId=1223228&view=ms.vss-test-web.build-test-results-tab&runId=36449836&resultId=145128&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open

- System.Linq.Tests.LifecycleTests.UnaryOperations_SourceEnumeratorDisposed

```
**Error message:**
```
Assert.All() Failure: 1 out of 113535 items in the collection did not pass.
[0]: Item: (Enumerable0, Append, Append, All)
System.TypeLoadException: GenericArguments[0], 'System.Int32', on 'System.IBitwiseOperators3[TSelf,TOther,TResult]' violates the constraint of type parameter 'TSelf'. at Xunit.Sdk.AssertComparer1.Compare(T x, T y)
at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\RangeAsserts.cs:line 40 at Xunit.Assert.InRange[T](T actual, T low, T high) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\RangeAsserts.cs:line 24 at System.Linq.Tests.LifecycleTests.<>c.<UnaryOperations_SourceEnumeratorDisposed>b__0_6(ValueTuple4 input) in /_/src/libraries/System.Linq/tests/LifecycleTests.cs:line 44
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36


Stack trace
   at System.Linq.Tests.LifecycleTests.UnaryOperations_SourceEnumeratorDisposed() in /_/src/libraries/System.Linq/tests/LifecycleTests.cs:line 24
```

**Comment by stephentoub** [comment]
This looks like a dup of https://github.com/dotnet/runtime/issues/54941

**Comment by eiriktsarpalis** [comment]
> This looks like a dup of #54941

Likely. [Recent test history](https://dev.azure.com/dnceng/public/_build/results?buildId=1250341&view=ms.vss-test-web.build-test-results-tab&runId=37126526&resultId=169622&paneView=history) indicates no recurring failures.
