### ISSUE TITLE
Test Failure System.ComponentModel.TypeConverterTests.SizeConverterTests.ConvertToInvariantString(width: 0, height: 0)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55251]
Run：[runtime 20210706.106](https://dev.azure.com/dnceng/public/_build/results?buildId=1223228&view=ms.vss-test-web.build-test-results-tab&runId=36449882&resultId=111292&paneView=debug)

Failed test :
```
net6.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

- System.ComponentModel.TypeConverterTests.SizeConverterTests.ConvertToInvariantString(width: 0, height: 0)

```
**Error message:**
```
System.TypeLoadException : GenericArguments[0], 'System.Int32', on 'System.IModulusOperators`3[TSelf,TOther,TResult]' violates the constraint of type parameter 'TSelf'.


Stack trace
   at System.RuntimeTypeHandle.GetInterfaces(RuntimeType type)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.PopulateInterfaces(Filter filter) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 1026
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetListByName(Char* pName, Int32 cNameLen, Byte* pUtf8Name, Int32 cUtf8Name, MemberListType listType, CacheType cacheType) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 414
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.Populate(String name, MemberListType listType, CacheType cacheType) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 353
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetMemberList(MemberListType listType, String name, CacheType cacheType) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 1428
   at System.RuntimeType.GetInterfaces() in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 2634
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes() in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs:line 98
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetAttributes(Type type) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs:line 312
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetAttributes() in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 3625
   at System.ComponentModel.TypeDescriptor.GetAttributes(Type componentType) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 663
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.ReflectedTypeData.cs:line 204
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type, Object instance) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs:line 366
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter() in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 3703
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 831
   at System.ComponentModel.TypeDescriptor.GetConverterTrimUnsafe(Type type) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 837
   at System.Drawing.SizeConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/Drawing/SizeConverter.cs:line 79
   at System.ComponentModel.TypeConverter.ConvertToString(ITypeDescriptorContext context, CultureInfo culture, Object value) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs:line 176
   at System.ComponentModel.TypeConverter.ConvertToInvariantString(Object value) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs:line 144
   at System.ComponentModel.TypeConverterTests.SizeConverterTests.ConvertToInvariantString(Int32 width, Int32 height) in /_/src/libraries/System.ComponentModel.TypeConverter/tests/Drawing/SizeConverterTests.cs:line 251
···

**Comment by stephentoub** [comment]
This looks like a dup of https://github.com/dotnet/runtime/issues/54941

**Comment by BruceForstall** [comment]
Although interestingly, here there is no stress involved.

**Comment by safern** [comment]
Which area should we assign to this issue, this doesn't look like a ComponentModel issue?

**Comment by safern** [comment]
Dup of #54941
