### ISSUE TITLE
Test Failure:System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55317]
Run: [runtime-libraries-coreclr outerloop 20210707.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1223761&view=ms.vss-test-web.build-test-results-tab&runId=36472070&resultId=102820&paneView=debug)
Failed Test:
```
net6.0-Linux-Release-arm-CoreCLR_release-(Debian.9.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-bfcd90a-20200121150037

- System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectFailure_LogsConnectFailed(connectMethod: \"Sync\", useDnsEndPoint: True)

```
**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Exception)
Actual:   (No exception was thrown)
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass10_0.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 176
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 118
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 170
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectFailure_LogsConnectFailed>b__10_0(System.String, System.String)

Child arguments:
  Sync, True
```

**Comment by MihaZupan** [comment]
Only happened on 7th and 8th, looks like the [connect](https://github.com/dotnet/runtime/blob/71d0d2b275efa091f235c569f01869f39bfb7638/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs#L178) did not throw for some reason.
Not sure it's actionable here

**Comment by karelz** [comment]
Failures 5/16-7/15 (incl. PRs):

Date | Run | OS
-- | -- | --
7/7 | Official build | Debian.9.Arm32.Open
7/7 | Official build | Centos.8.Amd64.Open
7/7 | Official build | Ubuntu.1804.Amd64.Open
7/7 | Official build | Windows.10.Amd64.Server19H1.Open
7/7 | Official build | Windows.7.Amd64.Open
7/8 | Official build | Alpine.312.Amd64.Open
7/8 | Official build | Alpine.312.Amd64.Open
7/8 | Official build | Ubuntu.1804.ArmArch.Open

Given the info above, closing for now. Please reopen if it happens again.
