### ISSUE TITLE
Test failure:System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55313]
Run: [runtime 20210707.124](https://dev.azure.com/dnceng/public/_build/results?buildId=1225692&view=ms.vss-test-web.build-test-results-tab&runId=36531372&resultId=123408&paneView=debug)
Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.312.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-arm64v8-20200602002604-25f8a3e

- System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments

```
**Error message**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.AssertCounterEventsPresent(EventWrittenEventArgs[] events, String meterName, String instrumentName, String tags, String expectedUnit, String[] expectedRates) in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 710
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 292
```

**Comment by noahfalk** [comment]
This is hopefully resolved with #55385, if it fails again please reopen and I can investigate further

**Comment by MihaZupan** [comment]
Failed again in #56614:
https://helix.dot.net/api/2019-06-17/jobs/5702a0df-b9d9-4ab2-8727-84d96b73d659/workitems/System.Diagnostics.DiagnosticSource.Tests/console

**Comment by noahfalk** [comment]
New issue is hopefully resolved. Ultimately this test is timing dependent so we can't guarantee it works, we can just keep increasing the allowed time window making it increasingly likely that code runs fast enough to complete in the expected time. The penalty for being overly conservative is that we make the test take a very long time to run.
