### ISSUE TITLE
[iOS] System.Tests.PosixSignalRegistrationTests: RemoteExecutor is not supported on this platform.

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55328]
A couple of tests, added recently in https://github.com/dotnet/runtime/pull/54136, fail with the following:
```
System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.]]>
   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments)
   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options)
   at System.Tests.PosixSignalRegistrationTests.SignalHandlerCalledForRawSignals(PosixSignal s)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

- System.Tests.PosixSignalRegistrationTests.SignalHandlerCalledForRawSignals
- System.Tests.PosixSignalRegistrationTests.SignalHandlerCalledForKnownSignals

cc @steveisok

**Comment by steveisok** [comment]
@MaximLipnin can you check if the tests you reference feature detect for RemoteExecutor?

**Comment by MaximLipnin** [comment]
> @MaximLipnin can you check if the tests you reference feature detect for RemoteExecutor?

No, they don't, I'll open a PR to update the tests with `[ConditionalTheory(typeof(RemoteExecutor), nameof(RemoteExecutor.IsSupported))]`

**Comment by stephentoub** [comment]
I will take care of it.  I'm currently editing all these files.
