### ISSUE TITLE
Test Failure：System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55382]
Run [runtime-libraries-coreclr outerloop 20210708.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1226519&view=ms.vss-test-web.build-test-results-tab&runId=36549260&resultId=102839&paneView=debug)
Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673

- System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Task\", useDnsEndPoint: False)
- System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Task\", useDnsEndPoint: True)

net6.0-Linux-Release-x64-CoreCLR_release-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200601195603-e06dc59

- System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(connectMethod: \"Task\", useDnsEndPoint: True)
```

**EventSource_SocketConnectsRemote_LogsConnectStartStop:**
```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(String connectMethod, Boolean useDnsEndPoint) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 131
```
 or

```
Child exception:
  Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: False
Actual:   True
   at System.Net.Sockets.Tests.TelemetryTest.VerifyEvents(ConcurrentQueue`1 events, Boolean connect, Nullable`1 expectedCount, Boolean shouldHaveFailures) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 437
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 151
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Task, True
```

or

```
Child exception:
  System.Net.Sockets.SocketException (54): Connection reset by peer
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1370
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1286
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 251
--- End of stack trace from previous location ---
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass9_0.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 144
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 118
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 137
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Task, False
```

or

```
Child exception:
  System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:104.215.148.63]:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3201
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 855
   at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass3_0.<ConnectAsync>b__0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs:line 61
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2381
   at System.Threading.Tasks.Task.<>c.<.cctor>b__284_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2369
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 293
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2331
--- End of stack trace from previous location ---
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass9_0.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 144
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 118
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 137
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Sync, False
```

**Comment by MihaZupan** [comment]
Failed only on release/* branches. Looks like we failed to connect to `microsoft.com:443`.

Seems like an external failure, not telemetry

**Comment by karelz** [comment]
@MihaZupan the failures in the above table are only from main branch ... what am I missing?

**Comment by VincentBu** [comment]
Failed again in [runtime-libraries-coreclr outerloop 20210809.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1283174&view=ms.vss-test-web.build-test-results-tab&runId=37895798&paneView=debug&resultId=103993)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1013.Amd64.Open

- System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(connectMethod: \"Task\", useDnsEndPoint: False)

```
**Error message:**
```
Half-way through waiting for remote process.
Timed out at 8/9/2021 5:09:39 AM after 60000ms waiting for remote process.
Process ID: 89232
Handle: 2120
Name: dotnet
MainModule: /private/tmp/helix/working/A52A094C/p/dotnet
StartTime: 8/9/2021 5:08:39 AM
TotalProcessorTime: 00:00:00.6555018


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Net.Sockets.Tests.TelemetryTest.EventSource_ConnectAsyncCanceled_LogsConnectFailed(String connectMethod, Boolean useDnsEndPoint) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 243
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20210816.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1295467&view=ms.vss-test-web.build-test-results-tab&runId=38209942&resultId=103859&paneView=debug)

Failed test:
```
net6.0-OSX-Release-x64-CoreCLR_release-OSX.1013.Amd64.Open

- System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(connectMethod: \"Apm\", useDnsEndPoint: True)

- System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketAcceptFailure_LogsAcceptFailed(acceptMethod: \"Apm\")

```
**Error message:**
```
Half-way through waiting for remote process.
Timed out at 8/16/2021 5:27:10 AM after 60000ms waiting for remote process.
Process ID: 27167
Handle: 2268
Name: dotnet
MainModule: /private/tmp/helix/working/AC7D0940/p/dotnet
StartTime: 8/16/2021 5:26:10 AM
TotalProcessorTime: 00:00:00.5521407


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop(String connectMethod, Boolean useDnsEndPoint) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 130
```
or
```
Half-way through waiting for remote process.
Timed out at 8/16/2021 5:25:01 AM after 60000ms waiting for remote process.
Process ID: 27121
Handle: 1364
Name: dotnet
MainModule: /private/tmp/helix/working/AC7D0940/p/dotnet
StartTime: 8/16/2021 5:24:00 AM
TotalProcessorTime: 00:00:00.0188344


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketAcceptFailure_LogsAcceptFailed(String acceptMethod) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 205
```
