### ISSUE TITLE
[Mono][Android][Interp] Missing dll - Could not load file or assembly 'xunit.performance.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=67066efe964d3b03' or one of its dependencies.

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#55528]
Failed test:

- JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot/mandelbrot-7/mandelbrot-7.sh

Full log

Failure log:
```
      07-09 21:42:32.211  7539  7557 I DOTNET  : MonoRunner initialize,, entryPointLibName=mandelbrot-7.dll
      07-09 21:42:32.211  7539  7557 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Performance/files/runtimeconfig.bin
      07-09 21:42:32.212  7539  7557 D DOTNET  : Interp Enabled
      07-09 21:42:32.213  7539  7557 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.235  7539  7557 D DOTNET  : assembly_preload_hook: mandelbrot-7.dll (null) /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.235  7539  7557 D DOTNET  : Executable: mandelbrot-7.dll
      07-09 21:42:32.235  7539  7557 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.236  7539  7557 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.236  7539  7557 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.236  7539  7557 D DOTNET  : assembly_preload_hook: System.Numerics.Vectors  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.237  7539  7557 D DOTNET  : assembly_preload_hook: System.Runtime.CompilerServices.Unsafe  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.237  7539  7557 D DOTNET  : assembly_preload_hook: System.Threading.Tasks.Parallel  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.240  7539  7557 D DOTNET  : assembly_preload_hook: System.Diagnostics.Tracing  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.240  7539  7557 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.240  7539  7557 D DOTNET  : assembly_preload_hook: System.Collections.Concurrent  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.275  7539  7560 D DOTNET  : assembly_preload_hook: xunit.performance.core  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.277  7539  7557 D DOTNET  : assembly_preload_hook: xunit.performance.core  /data/user/0/net.dot.JIT_Performance/files
      07-09 21:42:32.278  7539  7557 D DOTNET  : ((null) warning) Can't find custom attr constructor image: /data/data/net.dot.JIT_Performance/files/mandelbrot-7.dll mtoken: 0x0a000004 due to: Could not load file or assembly 'xunit.performance.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=67066efe964d3b03' or one of its dependencies.
      07-09 21:42:32.278  7539  7557 D DOTNET  : ((null) error) * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:2061, condition `is_ok (error)' not met, function:mono_assembly_load_friends, Could not load file or assembly 'xunit.performance.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=67066efe964d3b03' or one of its dependencies.
      07-09 21:42:32.278  7539  7557 E DOTNET  : Exit code: 1.
      07-09 21:42:32.307  1543  1543 I Zygote  : Process 7539 exited cleanly (1)
      07-09 21:42:32.307  1797  2723 I ActivityManager: Process net.dot.JIT_Performance (pid 7539) has died: fore FGS 
      07-09 21:42:32.308  1797  1825 I libprocessgroup: Successfully killed process cgroup uid 10119 pid 7539 in 0ms
      07-09 21:42:32.308  1797  2723 W ActivityManager: Crash of app net.dot.JIT_Performance running instrumentation ComponentInfo{net.dot.JIT_Performance/net.dot.MonoRunner}
      07-09 21:42:32.308  1797  2723 I ActivityManager: Force stopping net.dot.JIT_Performance appid=10119 user=0: finished inst
      07-09 21:42:32.308  1797  7250 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      07-09 21:42:32.308  1797  7250 W Binder  : java.lang.Throwable
      07-09 21:42:32.308  1797  7250 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      07-09 21:42:32.308  1797  7250 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      07-09 21:42:32.308  1797  7250 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      07-09 21:42:32.309  7529  7529 D AndroidRuntime: Shutting down VM
```

**Comment by fanyang-mono** [comment]
This test passes on Android x64 with JIT and desktop linux x64 with interpreter.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by fanyang-mono** [comment]
Moving to Future. Will revisit when planing for .NET8.

**Comment by SamMonoRT** [comment]
@DrewScoggins - do you know anything about "'xunit.performance.core", assembly - that's the one that is actually missing. 
@fanyang-mono  - is it's an easy case of including that as a dependency, lets make that quick fix. If it's more complicated, ok to move to Future.

**Comment by DrewScoggins** [comment]
Uhh, that is the previous performance test harness. As far as I know it is not used anywhere and can be removed.

**Comment by SamMonoRT** [comment]
Drew, can you follow up on that, seems like this is running a Benchmark test case, and not sure what effect it has if that is completely removed.

**Comment by DrewScoggins** [comment]
Is this still happening? Looks like @BruceForstall fixed this back in October, https://github.com/dotnet/runtime/pull/60711

**Comment by SamMonoRT** [comment]
@fanyang-mono is going to run locally and verify
