### ISSUE TITLE
Test failure:SetOut.SetOutReadToEnd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55547]
Run [runtime 20210712.116](https://dev.azure.com/dnceng/public/_build/results?buildId=1233668&view=ms.vss-test-web.build-test-results-tab&runId=36716822&resultId=120580&paneView=debug)
Failed test:
```
net6.0-Linux-Release-x64-Mono_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759

- SetOut.SetOutReadToEnd
```
**Error  message:**
```
System.ObjectDisposedException : Cannot access a closed Stream.


Stack trace
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer) in /_/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs:line 692
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 327
   at System.IO.StreamWriter.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 220
   at System.IO.TextWriter.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs:line 77
   at Helpers.SetAndReadHelper(Action`1 setHelper, Func`1 getHelper, Func`2 readHelper) in /_/src/libraries/System.Console/tests/Helpers.cs:line 40
   at SetOut.SetOutReadToEnd() in /_/src/libraries/System.Console/tests/SetOut.cs:line 33
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

**Comment by stephentoub** [comment]
This code was changed in #55499, and if this ends up reproing again, it won't repro in the same way, so I'm going to close it.  I suspect, however, that it was related to another issue that has also since been fixed.
