### ISSUE TITLE
ResolveLinkTarget_Succeeds tests fail with "You can't access this shared folder because your organization's security policies block unauthenticated guest access."

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#55573]
This is on my home, domain joined VPN'ed machine using HEAD from last night.

```
    <test name="System.IO.Tests.FileInfo_SymbolicLinks.ResolveLinkTarget_Succeeds(pathToTarget: \&quot;\\\\\\\\SERVER\\\\share\\\\path\&quot;, returnFinalTarget: True)" type="System.IO.Tests.FileInfo_SymbolicLinks" method="ResolveLinkTarget_Succeeds" time="19.4802194" result="Fail">
        <failure exception-type="System.IO.IOException">
          <message><![CDATA[System.IO.IOException : You can't access this shared folder because your organization's security policies block unauthenticated guest access. These policies help protect your PC from unsafe or malicious devices on the network. : 'C:\\Users\\danmose\\AppData\\Local\\Temp\\FileInfo_SymbolicLinks_gzoosz4k.00g\\GetRandomLinkName_25_341eea4b.link']]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs:line 614
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs:line 432
   at System.IO.Tests.BaseSymbolicLinks_FileSystemInfo.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget) in C:\git\runtime\src\libraries\System.IO.FileSystem\tests\Base\SymbolicLinks\BaseSymbolicLinks.FileSystemInfo.cs:line 24
   at System.IO.Tests.BaseSymbolicLinks_FileSystem.ResolveLinkTarget_Succeeds(String pathToTarget, Boolean returnFinalTarget) in C:\git\runtime\src\libraries\System.IO.FileSystem\tests\Base\SymbolicLinks\BaseSymbolicLinks.FileSystem.cs:line 168]]></stack-trace>
        </failure>
      </test>


            <test name="System.IO.Tests.DirectoryInfo_SymbolicLinks.ResolveLinkTarget_Succeeds(pathToTarget: \&quot;\\\\\\\\SERVER\\\\share\\\\path\&quot;, returnFinalTarget: True)" type="System.IO.Tests.DirectoryInfo_SymbolicLinks" method="ResolveLinkTarget_Succeeds" time="16.4175355" result="Fail">
        <failure exception-type="System.IO.IOException">
          <message><![CDATA[System.IO.IOException : You can't access this shared folder because your organization's security policies block unauthenticated guest access. These policies help protect your PC from unsafe or malicious devices on the network. : 'C:\\Users\\danmose\\AppData\\Local\\Temp\\DirectoryInfo_SymbolicLinks_z5irvvrj.tdm\\GetRandomLinkName_25_0302078d.link']]></message>
          <stack-trace><![CDATA[   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs:line 614
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs:line 432
   at System.IO.Tests.BaseSymbolicLinks_FileSystemInfo.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget) in C:\git\runtime\src\libraries\System.IO.FileSystem\tests\Base\SymbolicLinks\BaseSymbolicLinks.FileSystemInfo.cs:line 24
   at System.IO.Tests.BaseSymbolicLinks_FileSystem.ResolveLinkTarget_Succeeds(String pathToTarget, Boolean returnFinalTarget) in C:\git\runtime\src\libraries\System.IO.FileSystem\tests\Base\SymbolicLinks\BaseSymbolicLinks.FileSystem.cs:line 168]]></stack-trace>
        </failure>
      </test>
```

**Comment by danmoseley** [comment]
I'm curious what security policies my machine has applied that other FTE don't have applied.

**Comment by danmoseley** [comment]
Aha, someone created a machine named 'server' 😸 

```

C:\git\runtime>ping server

Pinging server.guest.corp.microsoft.com [10.171.1.169] with 32 bytes of data:
Reply from 10.171.1.169: bytes=32 time=326ms TTL=103
Reply from 10.171.1.169: bytes=32 time=328ms TTL=103
Reply from 10.171.1.169: bytes=32 time=326ms TTL=103
```
We just need to change the name in the tests.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/55488

**Comment by danmoseley** [comment]
Ah, I didn't see the dupe because you already fixed it..
