### ISSUE TITLE
System.Drawing.Common tests failed on Windows Mono due to COM wrappers

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#55655]
After https://github.com/dotnet/runtime/pull/54884 these tests started failing on Mono on Windows:

- ToBitmap_PngIconSupportedInSwitches_Success
- ToBitmap_PngIconNotSupportedInSwitches_ThrowsArgumentOutOfRangeException
- Ctor_IntPtrZeroIV_ThrowsArgumentException
- Ctor_InvalidFrameUnitIII_ThrowsArgumentException
- Ctor_InvalidEmfTypeIII_ThrowsArgumentException

Probably something to do with Mono not supporting COM on Windows: https://github.com/dotnet/runtime/issues/39704#issuecomment-675915108

Example stacktrace:

```
  System.TypeInitializationException: The type initializer for 'System.Drawing.DrawingCom' threw an exception.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Drawing.DrawingCom.InitializeComInterfaceEntry() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/DrawingCom.COMWrappers.cs:line 30
   at System.Drawing.DrawingCom..cctor() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/DrawingCom.COMWrappers.cs:line 22
   --- End of inner exception stack trace ---
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Image.Windows.cs:line 248
   at System.Drawing.Image.Save(Stream stream, ImageFormat format) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Image.Windows.cs:line 210
   at System.Drawing.Tests.IconTests.GetPngIcon() in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 685
   at System.Drawing.Tests.IconTests.<ToBitmap_PngIconSupportedInSwitches_Success>g__VerifyPng|44_0() in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 618
   at System.Drawing.Tests.IconTests.<>c.<ToBitmap_PngIconSupportedInSwitches_Success>b__44_1() in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 640
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

**Comment by danmoseley** [comment]
@safern do we support System.Drawing on Mono Windows at all? I assume not -- the whole test library should not run in that config.

**Comment by safern** [comment]
Actually we do 😄

**Comment by danmoseley** [comment]
Ah I see, we only use COM for a few things - Bitmaps, Images, Metafiles? In that case, unless we think the message is bad, this issue can be closed as by design.

**Comment by safern** [comment]
This was caused because we needed to use COMWrappers on 6.0 to make it trimmable safe. However it seems like Mono doesn't support COMWrappers? And yeah, the COMWrappers are mostly used to read Images from streams as we need to use an `IStream` com interface because that is what GDI+ uses.

Perhaps we could condition the code to use the legacy COM if running on Mono?

cc: @eerhardt

**Comment by eerhardt** [comment]
I was under the impression that Mono didn't support COM at all.

> Perhaps we could condition the code to use the legacy COM if running on Mono?

Is that worth it? What are the scenarios where customers will run with Mono on Windows?

COMWrappers are the way forward. If we believe "Mono on Windows" is important, then Mono needs to support COMWrappers. We are going to be converting more and more COM usage over to COMWrappers, so this will just crop up in more places.

cc @jkotas @AaronRobinsonMSFT

**Comment by jkotas** [comment]
We do not have official support for Mono on Windows.

**Comment by marek-safar** [comment]
It's not in our plans so this we should just disable the tests if it's blocking anyone

**Comment by lambdageek** [comment]
> I was under the impression that Mono didn't support COM at all.

There is support for the legacy COM interop in Mono on Windows and Linux, but yea Mono on Windows is not supported in .net 6.

> 
> COMWrappers are the way forward. If we believe "Mono on Windows" is important, then Mono needs to support COMWrappers. We are going to be converting more and more COM usage over to COMWrappers, so this will just crop up in more places.

Agreed.

>  what would it take to enable COM Wrapper support on mono?

A bunch of work.  I made a new issue to keep track https://github.com/dotnet/runtime/issues/55742

**Comment by IllidanS4** [comment]
I started getting this same issue after trying 6.0 preview, on Windows 7, where I am fairly sure GDI+ is supported. Is it related to this issue?

**Comment by akoeplinger** [comment]
@IllidanS4 no that's unrelated, I'd suggest filing a separate issue.

**Comment by JeremyKuhne** [comment]
System.Drawing.Common has moved to WinForms.
