### ISSUE TITLE
[Suggestion]: Exception Class should contain call stack .

### ISSUE THREAD

**Issue by athinboy** [dotnet/runtime#55705]
Thank for your work and sorry for my bad english .
I had been a .net developer ,and had turn to java ,like almost .net developer in china .
I find some feature of java is useful for developer , so I hope that dotnet shoud adopt these features .

Suggestion:
Exception Class should contain call stack of the throw time,so the log system/IDE can log/show the  call chain exactly and entirely.It is useful for developer to find the clue of exception .
Exception.StackTrace is not enough . log system may have special request .

https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#getStackTrace()

Also, Exception.ToString() is not good enough ,because there are just one stackframe ,not all the call stack . The output of  Throwable.printStackTrace()  in java is more useful.
https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html#printStackTrace()

**Comment by stephentoub** [comment]
An Exception's stack trace contains all the frames between where it was thrown and where it was caught (or, if unhandled, the whole stack).  Are you saying you wished it would contain all frames that go below even where it's caught?  I don't expect that to change, but .NET 5 introduced the SetCurrentStackTrace method, which will store into the Exception object the entire current stack.

**Comment by athinboy** [comment]
@stephentoub 

 Thanks for your reply.
 I will explain it by a sample:
```
    class Program1
    {
        class Bussiness
        {
            public static void Call()
            {
                DBTransactionManager.Call();
            }
        }


        class AOP1
        {
            public static void Call()
            {
                Log.Call();
            }
        }
        class AOP2
        {
            public static void Call()
            {
                Log.Call();
            }
        }
        class AOP3
        {
            public static void Call()
            {
                Log.Call();
            }
        }
        class Log
        {
            public static void Call()
            {

                try
                {
                    Bussiness.Call();
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Log:");
                    Console.WriteLine(ex);
                    throw;
                }

            }
        }

        interface IDBClient
        {
            public static void Call()
            {
                throw new Exception("Some Exception");
            }
        }

        class DBTransactionManagerLog
        {
            public static void Call()
            {
                try
                {
                    IDBClient.Call();
                }
                catch (Exception ex)
                {
                    Console.WriteLine("DBTransactionManagerLog:");
                    Console.WriteLine(ex);
                    throw;
                }

            }
        }

        class DBTransactionManager
        {
            public static void Call()
            {
                DBTransactionManagerLog.Call();
            }
        }
        class DIFramework
        {
            public static void Call()
            {
                AOP2.Call();
            }
        }
        static void Main(string[] args)
        {

            try
            {
                DIFramework.Call();

            }
            catch (Exception ex)
            {

                Console.WriteLine("Main:");
                Console.WriteLine(ex);
            }

        }
    }
```

 As we see,There are many component:DI framework,Log framework,AOP framework(AOP1,AOP2,AOP3),DB Transaction Manager framework,some sub class of IDBClient . these components are all open source ,and are of variable quality.

 The Log System has output the debug message to the ELK system:

```
 System.Exception: Some Exception
   at ConsoleApp1.Program1.IDBClient.Call() in C:\src\nlog\configtest1\Program1.cs:line 63
   at ConsoleApp1.Program1.DBTransactionManagerLog.Call() in C:\src\nlog\configtest1\Program1.cs:line 73
   at ConsoleApp1.Program1.DBTransactionManager.Call() in C:\src\nlog\configtest1\Program1.cs:line 89
   at ConsoleApp1.Program1.Bussiness.Call() in C:\src\nlog\configtest1\Program1.cs:line 14
   at ConsoleApp1.Program1.Log.Call() in C:\src\nlog\configtest1\Program1.cs:line 47   
```

 But ,If the developer search ELK, he can not find which aop component (AOP1,AOP2,AOP3) had been DI,so it is hard work to find AOP2 can not work correctly! 
Additionally ,we can not guarantee that all component developer use SetCurrentStackTrace  correctly,event the Microsoft component.
So,

> Are you saying you wished it would contain all frames that go below even where it's caught? 

Right!

 
 Thanks for you reply and sorry for my englishi ,i wish i had express myself correctly.
