### ISSUE TITLE
JitInfoIsPopulated failed with after is not greater than before

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#55712]
System.Runtime.Tests.JitInfoTests.JitInfoIsPopulated [Details] [History] [Helix Test Artifacts]

Exception Message
CompilationTime: after not greater than before! (after: 00:00:00.0257376, before: 00:00:00.0257376)
Expected: True
Actual:   False
CallStack
   at System.Runtime.Tests.JitInfoTests.JitInfoIsPopulated()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Pass Rate
Test has failed 40 out of 958 runs (4.18%)
Failing Configuration
net6.0-iOSSimulator-Release-x64-Mono_Release-OSX.1015.Amd64.Open

https://github.com/dotnet/runtime/runs/3071937514

Did the code run in less than 100ns? Seems unlikely that would pop up on the iOS simulator which is not our fastest configuration. So maybe a real bug?

**Comment by danmoseley** [comment]
@josalem  this is a new test you added. I see you special case the mono interpreter. Should the simulator also have this special case?

**Comment by danmoseley** [comment]
src/libraries/System.Runtime/tests/System/Runtime/JitInfoTests.cs

https://github.com/dotnet/runtime/commit/21a76328b8b64625a9ed0a95a433d742cf92f1de#diff-b05d7e9d113484fa5e220a32499d986f133738f27ef161a664e93783e59a3afc

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/runs/3071937514
https://github.com/dotnet/runtime/pull/55673

**Comment by josalem** [comment]
I would expect iOS to not run this test due to the `IsNotMonoAot` conditional fact attribute.  Is there a reason that isn't the case? Based on the behavior it looks like the same as the interpreter. Is the simulator running under the interpreter perhaps?

**Comment by danmoseley** [comment]
@steveisok can answer that.

**Comment by steveisok** [comment]
@fanyang-mono what are your thoughts?

**Comment by lambdageek** [comment]
@steveisok What sets the `MONO_AOT_MODE` environment variable?  I see in wasm it's set by the driver.c.  I would have expected that something in eng/testing/tests.mobile.targets sets is for other configurations.

**Comment by fanyang-mono** [comment]
I took a look at the code. And this is my understanding. The failed check in the test is checking `System.Runtime.JitInfo.GetCompilationTime()`. The mono definition lives at 
https://github.com/dotnet/runtime/blob/21a76328b8b64625a9ed0a95a433d742cf92f1de/src/mono/System.Private.CoreLib/src/System/Runtime/JitInfo.Mono.cs#L33-L36
It eventually queries the `jit_time` field of struct `MonoJitStats`, which only gets updated during JIT inside `mono_jit_compile_method_inner`
https://github.com/dotnet/runtime/blob/41e6601c5f9458fa8c5dea25ee78cbf121aa322f/src/mono/mono/mini/mini.c#L4112-L4116
Function `mono_jit_compile_method_inner` will only be executed during JIT. It won't be executed when it is interpreter mode. Thus, for interpreter mode, the test was actually getting the original garbage value of `jit_time` field. That's why it doesn't change before and after compile.

Based on the error message, it seems that `afterCompilationTime` equals to `beforeCompilationTime`, which means the check `PlatformDetection.IsMonoInterpreter` failed. (I thought `net6.0-iOSSimulator-Release-x64-Mono_Release` was running with interpreter mode, too. It may running with JIT right now. @steveisok Could you please check this?) 

For JIT, it seems that the `jit_time` was tracking compile time for the last compiled method. In that case, it seems that it took almost the same amount of time compiling the dynamic method and whatever function before that. (or the difference is at nano second level).

@BrzVlad Please correct me, if I were wrong.

**Comment by steveisok** [comment]
We are using interp for iOSSimulator, but with a mode that has *some* JIT elements to it.  

https://github.com/dotnet/runtime/blob/7aaffcb2b3d42c79a23a86aecd6d0e2df049ee44/eng/pipelines/runtime-staging.yml#L78

I have a PR up to change iOS/tvOSSimulator to be like Catalyst, which uses AOT JustInterp.  

https://github.com/dotnet/runtime/pull/55577

**Comment by lambdageek** [comment]
Ah ok. So `PlatformDetection.IsMonoInterpreter` needs to be changed.

https://github.com/dotnet/runtime/blob/7aaffcb2b3d42c79a23a86aecd6d0e2df049ee44/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L436-L446

This should probably just be 

```
   return RuntimeFeature.IsDynamicCodeSupported && !RuntimeFeature.IsDynamicCodeCompiled;
```

The `MONO_ENV_OPTIONS` check for `--interpreter` is wrong.  (first it should probably just check for `--interp`, second I don't think we use the environment variable for the AppleAppBuilder - we set the execution mode in the host app directly)

**Comment by josalem** [comment]
Just to make sure I am grokking the full situation, so I don't duplicate efforts:

* The iOSSimulator leg is running under the interpreter but with _some_ jitting, hence the value we see in `mono_jit_stats.jit_time`.
* `GetIsRunningMonoInterpreter` is currently implemented wrong causing this test to check with `>` instead of `>=`, hence the failure. <-- This requires a PR to fix the interp check
* Steve's change will make iOSSimulator show up as an AOT mode which won't run this test at all bypassing the fialure.

The only thing left to do besides #55577 (which should close this GH issue) is to fix `PlatformDetection.IsMonoInterpreter`, correct?

**Comment by fanyang-mono** [comment]
I think that mono interpreter mode should be excluded from this test as well, since the fields only matter to JIT.

**Comment by JulieLeeMSFT** [comment]
It seems that the area label needs to be mono JIT, not codegen-coreclr?

**Comment by steveisok** [comment]
@josalem I believe you are correct.  I think the appropriate label would be infrastructure-mono.
