### ISSUE TITLE
Host Activation tests failing with preview 5 update

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#55780]
2 of the hostactivation test are failing on updating the runtime to preview5

```
Failed tests
6.7899277s✘ Microsoft.DotNet.CoreSetup.Test.HostActivation.LightupAppActivation.Muxer_activation_of_LightupApp_WithLightupLib_Succeeds
Expected command to pass but it did not.\"\\r\\nFile Name: C:\\git\\runtime5\\artifacts\\tests\\Debug\\ha\\sharedFrameworkPublish\\dotnet.exe\\r\\nArguments: exec --additional-deps C:\\git\\runtime5\\artifacts\\tests\\Debug\\ha\\r1nmblem.nza\\LightupClient C:\\git\\runtime5\\artifacts\\tests\\Debug\\ha\\r1nmblem.nza\\LightupClient\\bin\\LightupClient.dll\\r\\nExit Code: -2147450740\\r\\nStdOut:\\r\\n\\r\\nStdErr:\\r\\nError:\\r\\n  An assembly specified in the application dependencies manifest (LightupLib.deps.json) was not found:\\r\\n    package: 'Newtonsoft.Json', version: '9.0.1'\\r\\n    path: 'lib/netstandard1.0/Newtonsoft.Json.dll'\\r\\n\\r\\n\"
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in FluentAssertions.dll:token 0x600015c+0x1d
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in FluentAssertions.dll:token 0x6000164+0x11
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in FluentAssertions.Core.dll:token 0x6000373+0x0
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in FluentAssertions.Core.dll:token 0x600034f+0x71
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in C:\git\runtime5\src\installer\tests\TestUtils\Assertions\CommandResultAssertions.cs:line 30
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.LightupAppActivation.Muxer_activation_of_LightupApp_WithLightupLib_Succeeds() in C:\git\runtime5\src\installer\tests\HostActivation.Tests\LightupAppActivation.cs:line 136
4.3097953s✘ Microsoft.DotNet.CoreSetup.Test.HostActivation.PortableAppActivation.Muxer_Exec_activation_of_Build_Output_Portable_DLL_with_DepsJson_Remote_and_RuntimeConfig_Local_Succeeds
Expected command to pass but it did not.\"\\r\\nFile Name: C:\\git\\runtime5\\artifacts\\tests\\Debug\\ha\\sharedFrameworkPublish\\dotnet.exe\\r\\nArguments: exec --depsfile C:\\git\\runtime5\\artifacts\\tests\\Debug\\ha\\wcvnhpmb.gav\\PortableApp\\d\\PortableApp.deps.json C:\\git\\runtime5\\artifacts\\tests\\Debug\\ha\\wcvnhpmb.gav\\PortableApp\\bin\\PortableApp.dll\\r\\nExit Code: -532462766\\r\\nStdOut:\\r\\n\\r\\nStdErr:\\r\\nUnhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.\\r\\nFile name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'\\r\\n   at PortableApp.Program.Main(String[] args)\\r\\n\\r\\n\"
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in FluentAssertions.dll:token 0x600015c+0x1d
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in FluentAssertions.dll:token 0x6000164+0x11
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in FluentAssertions.Core.dll:token 0x6000373+0x0
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in FluentAssertions.Core.dll:token 0x600034f+0x71
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in C:\git\runtime5\src\installer\tests\TestUtils\Assertions\CommandResultAssertions.cs:line 30
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.PortableAppActivation.Muxer_Exec_activation_of_Build_Output_Portable_DLL_with_DepsJson_Remote_and_RuntimeConfig_Local_Succeeds() in C:\git\runtime5\src\installer\tests\HostActivation.Tests\PortableAppActivation.cs:line 170
```

related PR https://github.com/dotnet/runtime/pull/55283

cc @dotnet/runtime-infrastructure

**Comment by safern** [comment]
cc: @mateoatr @agocke

**Comment by vitek-karas** [comment]
This has been fixed in the integration PR with https://github.com/dotnet/runtime/pull/55283/commits/077b5008829b788d7f7671788d91839066455fa1.
