### ISSUE TITLE
TestWithRelativePaths, TestWithAbsolutePaths, and TestWithRelativePathsDirSeparator installer tests failed in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#55918]
https://dev.azure.com/dnceng/public/_build/results?buildId=1245511&view=ms.vss-test-web.build-test-results-tab&runId=37015060&paneView=debug&resultId=100351

Installer-coreclr-Linux_x64-Release
Error:
"The following constructor parameters did not have matching fixture data: SharedTestState fixture"

```

Error message
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-x64 -property:MNAVersion=6.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-x64 -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/AppWithSubDirs.csproj]\n\n) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)\n---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-x64 -property:MNAVersion=6.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-x64 -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/AppWithSubDirs.csproj]\n\n\n---- The following constructor parameters did not have matching fixture data: SharedTestState fixture


Stack trace

----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 317
   at Microsoft.NET.HostModel.Tests.BundleAndRun.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleAndRun.cs:line 138
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-x64 -property:MNAVersion=6.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-x64 -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/AppWithSubDirs.csproj]\n\n) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)\n---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-x64 -property:MNAVersion=6.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-x64 -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/AppWithSubDirs.csproj]\n\n\n---- The following constructor parameters did not have matching fixture data: SharedTestState fixture


Stack trace

----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 317
   at Microsoft.NET.HostModel.Tests.BundleAndRun.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleAndRun.cs:line 138
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-x64 -property:MNAVersion=6.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-x64 -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/AppWithSubDirs.csproj]\n\n) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)\n---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net6.0 /p:NetCoreAppCurrent=net6.0 -o /root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=6.0.0-ci\nStandard Output:\nMicrosoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/MSBuild.dll -maxcpucount -property:NetCoreAppCurrent=net6.0 -property:TestTargetRid=linux-x64 -property:MNAVersion=6.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/publish -property:TargetFramework=net6.0 -property:RuntimeIdentifier=linux-x64 -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithSubDirs.csproj\n/root/runtime/.dotnet/sdk/6.0.100-preview.4.21255.9/Current/Microsoft.Common.props(33,3): error MSB4024: The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. [/root/runtime/artifacts/tests/Release/hmb/wtb3neyp.vwb/AppWithSubDirs/AppWithSubDirs.csproj]\n\n\n---- The following constructor parameters did not have matching fixture data: SharedTestState fixture


Stack trace

----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 317
   at Microsoft.NET.HostModel.Tests.BundleAndRun.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.Bundle.Tests/BundleAndRun.cs:line 138
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by vitek-karas** [comment]
The root error is:
```console
 The imported project file "/root/runtime/artifacts/tests/Release/hmb/Directory.Build.props" could not be loaded. Root element is missing. 
```

**Comment by ViktorHofer** [comment]
Closing as a dup of https://github.com/dotnet/runtime/issues/38530.
