### ISSUE TITLE
[HTTP/3] SendMoreThanStreamLimitRequests_Succeeds times out

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#55957]
Type:
- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_Mock -- Mock
- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic -- MsQuic

### Mock

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_Mock.SendMoreThanStreamLimitRequests_Succeeds(streamLimit: 10) [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (The operation has timed out.)) (One or more errors occurred. (Stream aborted by peer (268).))
      ---- System.AggregateException : One or more errors occurred. (The operation has timed out.)
      -------- System.TimeoutException : The operation has timed out.
      ---- System.AggregateException : One or more errors occurred. (Stream aborted by peer (268).)
      -------- System.Net.Quic.QuicStreamAbortedException : Stream aborted by peer (268).
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(80,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(117,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequests_Succeeds(Int32 streamLimit)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(113,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass4_0.<<SendMoreThanStreamLimitRequests_Succeeds>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(63,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/Mock/MockStream.cs(76,0): at System.Net.Quic.Implementations.Mock.MockStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(400,0): at System.Net.Test.Common.Http3LoopbackStream.ReadIntegerAsync()
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(370,0): at System.Net.Test.Common.Http3LoopbackStream.ReadFrameAsync()
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(200,0): at System.Net.Test.Common.Http3LoopbackStream.ReadRequestBodyAsync()
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(224,0): at System.Net.Test.Common.Http3LoopbackStream.ReadRequestDataAsync(Boolean readBody)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(52,0): at System.Net.Test.Common.Http3LoopbackStream.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(96,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass4_0.<<SendMoreThanStreamLimitRequests_Succeeds>b__0>d.MoveNext()
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54845-merge-281d2557555b40c185/System.Net.Http.Functional.Tests/console.b4270b74.log?sv=2019-07-07&se=2021-08-08T17%3A25%3A26Z&sr=c&sp=rl&sig=Ili2HVRMJUMjyhEZObd2yR6udqbRONrd6qRiNGOIOFc%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1246061&view=logs&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6

### MsQuic

```
System.TimeoutException : The operation has timed out.

   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass4_0.<<SendMoreThanStreamLimitRequests_Succeeds>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 113
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 82
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequests_Succeeds(Int32 streamLimit) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 117
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Failures 5/19-7/18 (incl. PRs):

Day | Build | OS
-- | -- | --
7/16 | PR #55844 | Ubuntu.1604.Amd64.Open
7/19 | PR #55283 | RedHat.7.Amd64.Open
7/19 | PR #54845 | RedHat.7.Amd64.Open
7/19 | PR #55283 | Fedora.32.Amd64.Open -- Timeout only exception

We should likely disable the test

**Comment by karelz** [comment]
Triage: Disable only the Mock test, then move to Future.

**Comment by karelz** [comment]
Test disabled for Mock only in PR #56064

**Comment by ericstj** [comment]
This seems to still be happening.  Hit twice in this build: https://dev.azure.com/dnceng/public/_build/results?buildId=1248759&view=ms.vss-test-web.build-test-results-tab&runId=37330520&resultId=189158&paneView=debug

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequests_Succeeds(streamLimit: 10) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(113,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass4_0.<<SendMoreThanStreamLimitRequests_Succeeds>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(82,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(117,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequests_Succeeds(Int32 streamLimit)
        --- End of stack trace from previous location ---
```

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_Mock.SendMoreThanStreamLimitRequests_Succeeds(streamLimit: 10) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(117,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequests_Succeeds(Int32 streamLimit)
        --- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
@ericstj the PR likely didn't have the test disabled for Mock yet (it was created prior to the disabling and I think it didn't merge main changes afterwards).
For MsQuic, the failure rate so far is small, so we didn't disable it yet.

**Comment by ericstj** [comment]
Ok that makes sense. We reran after the commit went in to disable the test but rerun doesn’t pick up a new merge commit.

**Comment by karelz** [comment]
Test disabled for all configurations (incl. MsQuic) in PR #56566 on 7/30

**Comment by ManickaP** [comment]
Triage: not actively worked on, punting.
