### ISSUE TITLE
[Regression] Ping.SendPingAsync API throws SocketException: Message too long exception on .NET 6 Preview 6

### ISSUE THREAD

**Issue by adityapatwardhan** [dotnet/runtime#55961]
### Description

PowerShell uses the API `System.Net.NetworkInformation.Ping.SendPingAsync` for the Test-Connection cmdlet. 

Only on macOS and on .NET 6 Preview 6, we get an exception when trying to find the supported MTUSize.

The exception is a System.Net.NetworkInformation.PingException with an inner exception of System.Net.Sockets.SocketException with a message "Message too long".

### Configuration

.NET 6 Preview 6 - osx-x64.

### Regression?

This is a regression from .NET 6 preview 4. We did not test on Preview 5.

### Other information

Exception :
Type : System.Net.NetworkInformation.PingException
Message : Testing connection to computer '127.0.0.1' failed: An exception occurred during a Ping request.
InnerException :
Type : System.Net.Sockets.SocketException
Message : Message too long
SocketErrorCode : MessageSize
ErrorCode : 40
NativeErrorCode : 40
TargetSite :
Name : Throw
DeclaringType : System.Runtime.ExceptionServices.ExceptionDispatchInfo
MemberType : Method
Module : System.Private.CoreLib.dll
Source : System.Private.CoreLib
HResult : -2147467259
StackTrace :

```
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow) in System.Net.Sockets.dll:token 0x60002ba+0xa
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(Socket socket, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x60002ac+0x32
at System.Net.Sockets.Socket.SendToAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x6000286+0x51
at System.Net.NetworkInformation.Ping.SendIcmpEchoRequestOverRawSocketAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in System.Net.Ping.dll:token 0x600004b+0xa2
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in System.Private.CoreLib.dll:token 0x6004877+0x28
at System.Net.NetworkInformation.Ping.SendIcmpEchoRequestOverRawSocketAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in System.Net.Ping.dll:token 0x600004b+0x3d
at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in System.Net.Ping.dll:token 0x6000053+0xe
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in System.Private.CoreLib.dll:token 0x6004877+0x28
at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in System.Net.Ping.dll:token 0x6000053+0x3d
at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options) in System.Net.Ping.dll:token 0x6000040+0x24
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in System.Private.CoreLib.dll:token 0x6004877+0x28
at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options) in System.Net.Ping.dll:token 0x6000040+0x3d
at System.Net.NetworkInformation.Ping.SendPingAsync(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options) in System.Net.Ping.dll:token 0x600003f+0x0
at Microsoft.PowerShell.Commands.TestConnectionCommand.SendCancellablePing(IPAddress targetAddress, Int32 timeout, Byte[] buffer, PingOptions pingOptions, Stopwatch timer) in
/Users/travisplunk/git/powershell/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs:line 863
at Microsoft.PowerShell.Commands.TestConnectionCommand.ProcessMTUSize(String targetNameOrAddress) in /Users/travisplunk/git/powershell/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs:line 515
at Microsoft.PowerShell.Commands.TestConnectionCommand.ProcessRecord() in /Users/travisplunk/git/powershell/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs:line 260
at System.Management.Automation.Cmdlet.DoProcessRecord() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/cmdlet.cs:line 173
at System.Management.Automation.CommandProcessor.ProcessRecord() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/CommandProcessor.cs:line 387
at System.Management.Automation.CommandProcessorBase.DoExecute() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/CommandProcessorBase.cs:line 568
at System.Management.Automation.Internal.PipelineProcessor.Inject(Object input, Boolean enumerate) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/pipeline.cs:line 1165
at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/pipeline.cs:line 495
at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext
funcContext) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/runtime/Operations/MiscOps.cs:line 498
at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/interpreter/CallInstruction.Generated.cs:line 608
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs:line 358
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs:line 358
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/interpreter/ControlFlowInstructions.cs:line 358
at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/interpreter/Interpreter.cs:line 105
at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/interpreter/LightLambda.Generated.cs:line 81
at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/ScriptCommandProcessor.cs:line
547
at System.Management.Automation.DlrScriptCommandProcessor.Complete() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/ScriptCommandProcessor.cs:line 425
at System.Management.Automation.CommandProcessorBase.DoComplete() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/CommandProcessorBase.cs:line 642
at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/pipeline.cs:line 603
at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input) in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/pipeline.cs:line 514
at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:line 400
at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:line 591
at System.Management.Automation.Runspaces.PipelineThread.WorkerProc() in /Users/travisplunk/git/powershell/src/System.Management.Automation/engine/hostifaces/LocalPipeline.cs:line 1220
at System.Threading.Thread.StartHelper.Callback(Object state) in System.Private.CoreLib.dll:token 0x60027aa+0x0
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002968+0x40
at System.Threading.Thread.StartCallback() in System.Private.CoreLib.dll:token 0x600272e+0xe
--- End of stack trace from previous location ---
at System.Net.NetworkInformation.Ping.SendIcmpEchoRequestOverRawSocketAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in System.Net.Ping.dll:token 0x600004b+0x11f
at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options) in System.Net.Ping.dll:token 0x6000053+0x89
at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options) in System.Net.Ping.dll:token 0x6000040+0x9c
```

**Comment by wfurt** [comment]
I assume you simple add body bigger than MTU and you try to send ping @adityapatwardhan? Any repro code would be helpful. 

cc: @filipnavara . Probably because the switch from utility to socket...

**Comment by filipnavara** [comment]
This is actually resurfacing of problems reported back in 2019 (https://github.com/dotnet/runtime/issues/927#issuecomment-541330498). The code for sending ping over raw socket doesn't handle translation of the "too big message" socket error into `IPStatus.PacketTooBig` reply. It should be fairly trivial to fix that by adding a new catch block:
```csharp
catch (SocketException ex) when (ex.SocketErrorCode == SocketError. MessageSize)
{
    return new PingReply(new IPAddress(0), null, IPStatus.PacketTooBig, 0, Array.Empty<byte>());
}
```

**Comment by stephentoub** [comment]
That seems reasonable.  Are there other SocketError => IPStatus we need to map as well?

**Comment by wfurt** [comment]
Should _any_ socket error lead to failed reply instead of surfacing the low-level error? 
I know it may be useful for debug but creates platform inconsistency.

**Comment by filipnavara** [comment]
> Are there other SocketError => IPStatus we need to map as well?

Great question.

There are other errors that could be reasonably mapped. On Windows at least `IPStatus.DestinationNetworkUnreachable` and `IPStatus.DestinationHostUnreachable` seem like values that get mapped (based on documentation of `IcmpSendEcho2` API). Other errors may get mapped but they can also result in `Win32Exception` exception.

The Unix implementation running the `ping` utility traditionally only mapped `Success`, `TimedOut` (both for timeout and the packet too big error) and everything else resulted in `PingException` exception.

Not mapping `PacketTooBig` was already inconsistent on Unix for the two implementations (raw sockets, `ping` utility). Not mapping other socket errors to `IPStatus` was consistent.

**Comment by adityapatwardhan** [comment]
@wfurt - here is our usage of the API:

https://github.com/PowerShell/PowerShell/blob/658837323599ab1c7a81fe66fcd43f7420e4402b/src/Microsoft.PowerShell.Commands.Management/commands/management/TestConnectionCommand.cs#L848-L876

**Comment by karelz** [comment]
@filipnavara will you be able to put up a PR?
We should scope it to new regressions against 5.0 at this moment.

**Comment by filipnavara** [comment]
I'm somewhat busy at the moment but I'll try to PR it tomorrow.
