### ISSUE TITLE
System.Net.Quic.Tests.QuicStreamTests_MockProvider.WriteCanceled_NextWriteThrows is failing on redhat.7.amd64

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#55995]
[console logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55916-merge-3a6e913985424fcd9f/System.Net.Quic.Functional.Tests/console.5e8340a8.log?sv=2019-07-07&se=2021-08-09T11%3A31%3A01Z&sr=c&sp=rl&sig=aco%2BUr6P7BHcJi8FcDMa%2BNRHJ3p5RLjyZVOuwjJ8Ax0%3D)

```
----- start Tue Jul 20 11:50:16 UTC 2021 =============== To repro directly: =====================================================
pushd .
/mnt/work/ABA509B8/p/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/mnt/work/ABA509B8/w/A7AE094B/e /mnt/work/ABA509B8/w/A7AE094B/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 48 of 121 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.QuicStreamTests_MockProvider.WriteCanceled_NextWriteThrows [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicStreamAbortedException)
      Actual:   (No exception was thrown))) (One or more errors occurred. (Assert.Throws() Failure
      Expected: typeof(System.OperationCanceledException)
      Actual:   (No exception was thrown)))
      ---- System.AggregateException : One or more errors occurred. (Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicStreamAbortedException)
      Actual:   (No exception was thrown))
      -------- Assert.Throws() Failure
      Expected: typeof(System.Net.Quic.QuicStreamAbortedException)
      Actual:   (No exception was thrown)
      ---- System.AggregateException : One or more errors occurred. (Assert.Throws() Failure
      Expected: typeof(System.OperationCanceledException)
      Actual:   (No exception was thrown))
      -------- Assert.Throws() Failure
      Expected: typeof(System.OperationCanceledException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(80,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(132,0): at System.Net.Quic.Tests.QuicTestBase`1.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(620,0): at System.Net.Quic.Tests.QuicStreamTests`1.WriteCanceled_NextWriteThrows()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace #1 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(664,0): at System.Net.Quic.Tests.QuicStreamTests`1.<>c.<<WriteCanceled_NextWriteThrows>b__23_1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(666,0): at System.Net.Quic.Tests.QuicStreamTests`1.<>c.<<WriteCanceled_NextWriteThrows>b__23_1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(137,0): at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass22_0.<<RunClientServer>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(63,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        ----- Inner Stack Trace #2 (System.AggregateException) -----
        
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(640,0): at System.Net.Quic.Tests.QuicStreamTests`1.<>c.<<WriteCanceled_NextWriteThrows>b__23_0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(645,0): at System.Net.Quic.Tests.QuicStreamTests`1.<>c.<<WriteCanceled_NextWriteThrows>b__23_0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(147,0): at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass22_0.<<RunClientServer>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 244, Errors: 0, Failed: 1, Skipped: 0, Time: 5.161s
/mnt/work/ABA509B8/w/A7AE094B/e
----- end Tue Jul 20 11:50:22 UTC 2021 ----- exit code 1 ----------------------------------------------------------
```

Noticed in PR: #55916

**Comment by karelz** [comment]
Failures 5/20-7/20 (incl. PRs):

Day | Failures
-- | --
previously | more failures with different errors
7/12 | PR #55075
7/14 | PR #55647
7/16 | PR #55782
7/16 | PR #55726
7/19 | PR #53151 
7/20 | PR #55925
7/20 | PR #55916
7/20 | PR #54640

It's a mock test, we should disable it.

**Comment by karelz** [comment]
Test disabled on Mock by PR #56078 on 7/21.

**Comment by ManickaP** [comment]
https://github.com/dotnet/runtime/pull/70421
