### ISSUE TITLE
CTRL+C on a BackgroundService waiting on an async operation causes errors in the log

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#56032]
### Repro steps
1. Run the following app
```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace BackgroundServiceTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using var host = CreateHostBuilder(args).Build();

            await host.RunAsync();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseConsoleLifetime()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
    }

    class Worker : BackgroundService
    {
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(10), stoppingToken);
            }
        }
    }
}
```

2. CTRL+C to shut the app down

### Expected result
The app should exit normally

### Actual result

```
❯ dotnet run
Building...
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\DotNetTest\Net6Hosting
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at BackgroundServiceTest.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\DotNetTest\Net6Hosting\Program.cs:line 33
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService) in Microsoft.Extensions.Hosting.dll:token 0x6000073+0x76
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at BackgroundServiceTest.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\DotNetTest\Net6Hosting\Program.cs:line 33
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService) in Microsoft.Extensions.Hosting.dll:token 0x6000073+0x76
```

### Notes

We should be ignoring `TaskCanceledException` in

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L79-L94

Maybe we could also check if the Host is shutting down, and only ignore `TaskCanceledException` then?

cc @maryamariyan @davidfowl @Tratcher @IEvangelist

**Comment by IEvangelist** [comment]
Hi @eerhardt  - Is it as simple as saying `catch (Exception ex) when (ex is not TaskCanceledException)`? Are there ever concerns about valid `TaskCanceledException` that should cause error logs?

**Comment by eerhardt** [comment]
I'm not 100% sure honestly.

Maybe the rule should be:

If the `backgroundService.ExecuteTask.IsCanceled` && the Host is in the middle of stopping, don't log an `OperationCanceledException`.

Thoughts?
