### ISSUE TITLE
[libraries][tvOS] HatchBrushTests.Ctor_InvalidHatchStyle_ThrowsArgumentException fails The type initializer for 'Gdip' threw an exception.

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#56049]
```
Assert.Throws() Failure\nExpected: typeof(System.ArgumentException)\nActual:   typeof(System.TypeInitializationException): The type initializer for 'Gdip' threw an exception.\n---- System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.\n-------- System.DllNotFoundException : libgdiplus
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.LibraryResolver.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at System.Runtime.InteropServices.NativeLibrary.MonoLoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags, IntPtr& dll)
   at System.Drawing.Drawing2D.HatchBrush..ctor(HatchStyle hatchstyle, Color foreColor)
   at System.Drawing.Drawing2D.Tests.HatchBrushTests.<>c__DisplayClass4_0.<Ctor_InvalidHatchStyle_ThrowsArgumentException>b__0()
----- Inner Stack Trace -----
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.LibraryResolver.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at System.Runtime.InteropServices.NativeLibrary.MonoLoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags, IntPtr& dll)
   at System.Drawing.Drawing2D.HatchBrush..ctor(HatchStyle hatchstyle, Color foreColor)
   at System.Drawing.Drawing2D.Tests.HatchBrushTests.<>c__DisplayClass4_0.<Ctor_InvalidHatchStyle_ThrowsArgumentException>b__0()
----- Inner Stack Trace -----
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55974-merge-d6747e4bc7824e1984/System.Drawing.Common.Tests/console.7a20274b.log?sv=2019-07-07&se=2021-08-09T02%3A29%3A58Z&sr=c&sp=rl&sig=bv55K3ET7nrX08jZoGvJCfQ7PNIjOlfTmZ9FhX38BRg%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1247256&view=logs&j=e4e455c5-b032-5051-d2c5-a64982c9ac45&t=0263a457-10d3-5b56-3414-171b09292e09

**Comment by MaximLipnin** [comment]
The same failure as in https://github.com/dotnet/runtime/issues/56048

**Comment by danmoseley** [comment]
Is there a setup step on simulator and tvos that installs libgdiplus package, and simply failed in these cases?

**Comment by safern** [comment]
To me it seems like this test should be a conditional fact like all others in system drawing to use `Helpers.IsDrawingSupported`.

**Comment by danmoseley** [comment]
already fixed https://github.com/dotnet/runtime/commit/f5ed68b1832a0fca2c0db3e0a10b7268b709ee9f#diff-415b0dd5e3c9dfb606d8f5640321e8a8c6e8d188c5e22a25ff560a10240bcc49R54
