### ISSUE TITLE
[libraries][iOSSimulator] ImageTests.FromFile_NullFileName_ThrowsArgumentNullException fails 

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#56048]
```
Assert.Throws() Failure\nExpected: typeof(System.ArgumentNullException)\nActual:   typeof(System.TypeInitializationException): The type initializer for 'Gdip' threw an exception.\n---- System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.\n-------- System.DllNotFoundException : libgdiplus
at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.LibraryResolver.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at System.Runtime.InteropServices.NativeLibrary.MonoLoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags, IntPtr& dll)
   at System.Drawing.Image.FromFile(String filename)
   at System.Drawing.Tests.ImageTests.<>c.<FromFile_NullFileName_ThrowsArgumentNullException>b__24_0()
----- Inner Stack Trace -----
   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
   at System.Drawing.LibraryResolver.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at System.Runtime.InteropServices.NativeLibrary.MonoLoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags, IntPtr& dll)
   at System.Drawing.Image.FromFile(String filename)
   at System.Drawing.Tests.ImageTests.<>c.<FromFile_NullFileName_ThrowsArgumentNullException>b__24_0()
----- Inner Stack Trace -----
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55974-merge-1ee0573a687a4a1890/System.Drawing.Common.Tests/console.76c2bd7e.log?sv=2019-07-07&se=2021-08-09T02%3A17%3A12Z&sr=c&sp=rl&sig=U3vDMKA%2FTiGgV7VjC5sRHw44128SB9OvJVtPUYyP6kY%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1247256&view=logs&j=accacb66-0a14-52ef-4079-6344686d9d4c&t=34fbd35e-866b-51a1-9063-fb50703b1957

**Comment by MaximLipnin** [comment]
`System.Drawing.Tests.ImageTests.FromFile_LongSegment_ThrowsException` is failing as well.

**Comment by MaximLipnin** [comment]
Using `[ConditionalFact(Helpers.IsDrawingSupported)]` or `[ConditionalTheory(Helpers.IsDrawingSupported)]` should help to avoid these failures.

**Comment by danmoseley** [comment]
fixed
https://github.com/dotnet/runtime/commit/f5ed68b1832a0fca2c0db3e0a10b7268b709ee9f#diff-8963c1955850b6f7f51ab87536f55e760ea4c8e59a0712a85c4bdb169d0f1501R17
