### ISSUE TITLE
[libraries][iOSSimulator/tvOSSimulator] System.Diagnostics.Tracing.Tests fails with empty/default guid

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#56045]
```
<test name="BasicEventSourceTests.ActivityTracking.StartStopCreatesActivity" type="BasicEventSourceTests.ActivityTracking" method="StartStopCreatesActivity" time="0.0397151" result="Fail">
  <failure exception-type="Xunit.Sdk.NotEqualException">
    <message><![CDATA[Assert.NotEqual() Failure\nExpected: Not 00000000-0000-0000-0000-000000000000\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.StartStopCreatesActivity()
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
  </failure>
</test>
<test name="BasicEventSourceTests.ActivityTracking.ActivityFlowsAsync" type="BasicEventSourceTests.ActivityTracking" method="ActivityFlowsAsync" time="0.0011947" result="Fail">
  <failure exception-type="Xunit.Sdk.NotEqualException">
    <message><![CDATA[Assert.NotEqual() Failure\nExpected: Not 00000000-0000-0000-0000-000000000000\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.ActivityFlowsAsync()
--- End of stack trace from previous location ---]]></stack-trace>
  </failure>
</test>
<test name="BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdBeforeEventFlowsAsync" type="BasicEventSourceTests.ActivityTracking" method="SetCurrentActivityIdBeforeEventFlowsAsync" time="0.0022982" result="Fail">
  <failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 8b6855d1-d54e-42b9-8fec-f05e5e9bc44e\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdBeforeEventFlowsAsync()
--- End of stack trace from previous location ---]]></stack-trace>
  </failure>
</test>
<test name="BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdAfterEventDoesNotFlowAsync" type="BasicEventSourceTests.ActivityTracking" method="SetCurrentActivityIdAfterEventDoesNotFlowAsync" time="0.000979" result="Fail">
  <failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: dde6c44c-f633-4ab2-a858-e2800a71a5d7\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdAfterEventDoesNotFlowAsync()
--- End of stack trace from previous location ---]]></stack-trace>
  </failure>
</test>
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55974-merge-1ee0573a687a4a1890/System.Diagnostics.Tracing.Tests/console.a09c02b0.log?sv=2019-07-07&se=2021-08-09T02%3A17%3A12Z&sr=c&sp=rl&sig=U3vDMKA%2FTiGgV7VjC5sRHw44128SB9OvJVtPUYyP6kY%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1247256&view=logs&j=accacb66-0a14-52ef-4079-6344686d9d4c&t=34fbd35e-866b-51a1-9063-fb50703b1957

**Comment by MaximLipnin** [comment]
Closing it as a duplicate in favor of https://github.com/dotnet/runtime/issues/56073
