### ISSUE TITLE
Setting do not work on NEW VB .Net 5 Winforms application

### ISSUE THREAD

**Issue by paul1956** [dotnet/runtime#56066]
* .NET Core Version:  What I have installed is below
```
Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Create a new VB WinForm App, that will read settings, add settings, run app and application will crash as below.

![image](https://user-images.githubusercontent.com/12789369/119243280-20470080-bb1a-11eb-9bcc-4c95a6dd18f3.png)
```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName)
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at CareLink.My.MySettings.get_username() in C:\Users\PaulM\Source\Repos\CareLink\CareLink\My Project\Settings.Designer.vb:line 62
   at CareLink.LoginForm1.LoginForm1_Load(Object sender, EventArgs e) in C:\Users\PaulM\Source\Repos\CareLink\CareLink\LoginForm1.vb:line 12
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (C:\Users\PaulM\Source\Repos\CareLink\CareLink\bin\Debug\net5.0-windows\CareLink.dll.config line 8)
```

**Expected behavior:**
I can read settings

**Minimal repro:**
Contents of .config file
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
            <section name="CareLink.My.MySettings" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
```
Manually deleting system.diagnostics section fixes the issue until a rebuild.
```
    <system.diagnostics>
        <sources>
            <!-- This section defines the logging configuration for My.Application.Log -->
            <source name="DefaultSource" switchName="DefaultSwitch">
                <listeners>
                    <add name="FileLog"/>
                    <!-- Uncomment the below section to write to the Application Event Log -->
                    <!--<add name="EventLog"/>-->
                </listeners>
            </source>
        </sources>
        <switches>
            <add name="DefaultSwitch" value="Information" />
        </switches>
        <sharedListeners>
            <add name="FileLog"
                 type="Microsoft.VisualBasic.Logging.FileLogTraceListener, Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL"
                 initializeData="FileLogWriter"/>
            <!-- Uncomment the below section and replace APPLICATION_NAME with the name of your application to write to the Application Event Log -->
            <!--<add name="EventLog" type="System.Diagnostics.EventLogTraceListener" initializeData="APPLICATION_NAME"/> -->
        </sharedListeners>
    </system.diagnostics>
```
From here down works
```
    <userSettings>
        <CareLink.My.MySettings>
            <setting name="username" serializeAs="String">
                <value />
            </setting>
            <setting name="password" serializeAs="String">
                <value />
            </setting>
        </CareLink.My.MySettings>
    </userSettings>
</configuration>
```

**Comment by RussKie** [comment]
This issue is blocking migration scenarios.

**Comment by safern** [comment]
cc @dotnet/area-system-configuration

**Comment by buyaa-n** [comment]
Probably related to https://github.com/dotnet/runtime/issues/931, cc @JeremyKuhne 

@paul1956 could you try the workaround mentioned here https://github.com/dotnet/runtime/issues/931#issuecomment-483924246?

**Comment by RussKie** [comment]
@buyaa-n this needs to be fixed in .NET 6.0 timeframe, and possibly served in .NET 5.0 and 3.1. This is a regression which is blocking migration scenarios.

**Comment by paul1956** [comment]
@buyaa-n I read the workaround multiple times and I don't see what I need to do. I don't have any code that looks like that.
The first time I read any setting the program crashes at the line below with an error.
```
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\SQLEXPRESS;Initial Catalog=VolunteerHours;Integrated Security=True;"& _ 
            "Pooling=False")>  _
        Public ReadOnly Property masterConnectionString() As String
            Get
                Return CType(Me("masterConnectionString"),String) ' <------ ERROR
            End Get
        End Property
```

**Comment by danmoseley** [comment]
@paul1956 am I correct that you don't need the `<system.diagnostics>` section? ie., you can build, remove that section, and deploy your app without it and you're fine with that -- the problem is that it puts it back when you rebuild? 

If so, perhaps this is something that the project system should not add for .NET Core based projects.

**Comment by paul1956** [comment]
@danmoseley I only use userSettings. If I edit the APPLICATIONNAME.dll.config file and delete the 2 problem sections they comes back when I rebuild. If I edit the application.config file doesn't come back for that project. The problem happens in two scenarios, "New Projects" where the project system adds the Diagnostic and Switches sections and at least initially they are not used and may never be so deleting it should not be an issue, and ported projects (either manually or with TryConvert). In the TryConvert and manual porting scenario the data in Version and PublicKeyToken are wrong (it is 4.0.0.0 or less and has a different PublicKeyToken) and unless you read this thread you have no idea where to get the values.
```
<sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
```
I don't know what switches does so it might work or not, Logging might work if I knew how to set the Type Line above.

Related issue is it fails pointing to perfectly valid code (that I need) making it even more difficult to diagnose.

**Comment by buyaa-n** [comment]
> @buyaa-n I read the workaround multiple times and I don't see what I need to do. I don't have any code that looks like that.

@paul1956 sorry the workaround mentioned was in the above comment, here is the exact comment i wanted to read:

> > Do we have a customer report about what people end up doing to make this work today?
> 
> They are having to rewrite their code or copy over the shared test app.config on the box.

But it might not be directly be related to your issue, looks like it is more related to the @RussKie's exception log.

 Your issue might be related to https://github.com/dotnet/runtime/issues/32307 and I am not sure if there is a workaround cc @eerhardt

**Comment by paul1956** [comment]
@buyaa-n I currently don't have apps that use exception log, I am working on a consumer medical display application where it would be very useful but as I said [here](https://github.com/dotnet/runtime/issues/56066#issuecomment-887157115) the information to get it to work is missing. Where do I find "copy over the shared test app.config". All the app.config files that get installed with .Net have similar issues.
