### ISSUE TITLE
[iOS/tvOS/MacCatalyst] Test failures in System.Diagnostics.Tracing.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#56073]
- BasicEventSourceTests.ActivityTracking.StartStopCreatesActivity
```
<failure exception-type="Xunit.Sdk.NotEqualException">
    <message><![CDATA[Assert.NotEqual() Failure\nExpected: Not 00000000-0000-0000-0000-000000000000\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.StartStopCreatesActivity()
    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]>
    </stack-trace>
</failure>
```
- BasicEventSourceTests.ActivityTracking.ActivityFlowsAsync
```
<failure exception-type="Xunit.Sdk.NotEqualException">
    <message><![CDATA[Assert.NotEqual() Failure\nExpected: Not 00000000-0000-0000-0000-000000000000\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.ActivityFlowsAsync()
    --- End of stack trace from previous location ---]]>
    </stack-trace>
</failure>
```
- BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdBeforeEventFlowsAsync
```
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: ed27419e-317a-43a7-be88-6b793b146141\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdBeforeEventFlowsAsync()
    --- End of stack trace from previous location ---]]>
    </stack-trace>
</failure>
```
- BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdAfterEventDoesNotFlowAsync
```
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 33f1669b-7f05-46a8-bf4c-f321de6083f6\nActual:   00000000-0000-0000-0000-000000000000]]></message>
    <stack-trace><![CDATA[   at BasicEventSourceTests.ActivityTracking.SetCurrentActivityIdAfterEventDoesNotFlowAsync()
    --- End of stack trace from previous location ---]]>
    </stack-trace>
</failure>
```

cc @steveisok

**Comment by MaximLipnin** [comment]
Those tests have been added recently in https://github.com/dotnet/runtime/pull/55625. They are skipped for WASM, I'm not sure if we want to do the same for Apple mobile platforms.

**Comment by steveisok** [comment]
@MaximLipnin Can you check to see what the value is for `<EventSourceSupport>` ?

**Comment by MaximLipnin** [comment]
@steveisok Something close to the mobile targets is https://github.com/dotnet/runtime/blob/main/eng/testing/tests.mobile.targets#L26 but we don't set EAT for the staging lanes so perhaps `EventSourceSupport` is not set

**Comment by lateralusX** [comment]
Do we build with diagnostics tracing component support enabled when running tests on mobile? Link or deploy needed components? I guess this tests will end up in ves_icall_System_Diagnostics_Tracing_EventPipeInternal_EventActivityIdControl and if we don't have component support loaded that will be a nop operation so won't set thread activity ID and that will trigger the assert in this test.

**Comment by steveisok** [comment]
I don't think we do.  We probably should skip these for the time being.

**Comment by steveisok** [comment]
These are now enabled.  Closing.

**Comment by mdh1418** [comment]
These are still failing on tvOS

**Comment by pavelsavara** [comment]
I'm trying to make this work on browser now. 
And I'm not clear how this could work on Mono. I can't find what's calling `ActivityTracker.Instance.Enable()` on Mono

**Comment by pavelsavara** [comment]
> enables an ActivityTracker instance

Yes, but that's just instance, but not `Enable()` and `ActivityTracker.OnStart` would enable it only if you have `TplEventSource` enabled, right ?

https://github.com/dotnet/runtime/blob/9c9178f37155eae923db9b686538297bd3afcfc8/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/ActivityTracker.cs#L47-L59

**Comment by mdh1418** [comment]
Right. I think what's happening is the test has a custom EventSource/EventListener that [looks for TplEventSource being created](https://github.com/dotnet/runtime/blob/9c9178f37155eae923db9b686538297bd3afcfc8/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/ActivityTracking.cs#L144-L147) to enable that provider. Then later in these tests `SetCurrentActivityIdBeforeEventFlowsAsync` and `SetCurrentActivityIdAfterEventDoesNotFlowAsync`, they call `SetCurrentThreadActivityId` which then instantiates [`TplEventSource.Log`](https://github.com/dotnet/runtime/blob/9c9178f37155eae923db9b686538297bd3afcfc8/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L615).

**Comment by pavelsavara** [comment]
> they call `SetCurrentThreadActivityId` which then instantiates `TplEventSource.Log`

That solves how it works in the unit test, but it would not make it work in production, unless user code also enables `System.Threading.Tasks.TplEventSource` in the `OnEventSourceCreated`. That sounds fishy.

It seems to me that CoreCLR does it always when `FEATURE_EVENT_TRACE` is enabled. That's always true, right ?

`FireAssemblyLoadStart` -> `ActivityTracker::Start` -> `AssemblyLoadContext.StartAssemblyLoad` -> `ActivityTracker.Instance.Enable()`

Should we do `ActivityTracker.Instance.Enable()` fist time that any `EventListener` is created ? 

Or do something Mono specific when ? Maybe any time that we link `libmono-component-diagnostics_tracing-static.lib` ?

cc @lewing

**Comment by mdh1418** [comment]
Yeah, I think you're right that CoreCLR will enable ActivityTracker by default, but I don't know if Mono also should. If Browser needs ActivityTracking, I think we could try turning it on in 10. @lateralusX, do you happen to know if ActivityTracker was not on by default on Mono for a particular reason?

**Comment by lateralusX** [comment]
The trigger in CoreCLR is when its raising FireEtwAssemblyLoadStart/FireEtwAssemblyLoadStop event pairs (and there is a listener registering for those events), https://github.com/dotnet/runtime/blob/a9b700a1f6f3f524595393433bda6115b39afd71/src/coreclr/binder/bindertracing.cpp#L28. That will call into ActivityTracker start/stop that will end up in the managed call that will enable ActivityTracker.Instance.Enable(). The other option is to enable specific keyword on the TPLEventSource. Those are the only two scenarios actively supporting activity tracking and since activity tracking comes with some overhead it only gets enabled when really used.

Mono never ported the specific assembly start/stop events, probably since tools at that point didn't consume them, we just emit FireEtwModuleLoad/FireEtwModuleUnload and FireEtwAssemblyLoad/FireEtwAssemblyUnload. Since Mono don't support the events that uses activity tracking, it will only enable it in the scenario that we support, when using TPLEventSource listener with TasksFlowActivityIds keyword.

If we decide to support FireEtwAssemblyLoadStart/FireEtwAssemblyLoadStop then we would enable it in similar way as CoreClr does.
