### ISSUE TITLE
[iOS/tvOS/MacCatalyst] Test failure: System.Drawing.Tests.ImageTests.FromFile_NullFileName_ThrowsArgumentNullException

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#56076]
```
<failure exception-type="Xunit.Sdk.ThrowsException">
    <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.ArgumentNullException)\nActual:   typeof(System.TypeInitializationException): The type initializer for 'Gdip' threw an exception.\n---- System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.\n-------- System.DllNotFoundException : libgdiplus]]></message>
    <stack-trace><![CDATA[   at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
        at System.Drawing.LibraryResolver.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
        at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
        at System.Runtime.InteropServices.NativeLibrary.MonoLoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags, IntPtr& dll)
        at System.Drawing.Image.FromFile(String filename)
        at System.Drawing.Tests.ImageTests.<>c.<FromFile_NullFileName_ThrowsArgumentNullException>b__24_0()
        ----- Inner Stack Trace -----
        at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
        at System.Drawing.LibraryResolver.DllImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
        at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
        at System.Runtime.InteropServices.NativeLibrary.MonoLoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags, IntPtr& dll)
        at System.Drawing.Image.FromFile(String filename)
        at System.Drawing.Tests.ImageTests.<>c.<FromFile_NullFileName_ThrowsArgumentNullException>b__24_0()
        ----- Inner Stack Trace -----
        at System.Drawing.SafeNativeMethods.Gdip..cctor()]]>
    </stack-trace>
</failure>
```

@steveisok

**Comment by MaximLipnin** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/56048
