### ISSUE TITLE
[HTTP/3] Response stream ReadAsync hang with large buffer size

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#56115]
Imagine the server:

* Writes 11 bytes to the response body
* Flushes data to client
* Pauses

The client tries to read the response bytes like this:

```cs
var responseTask = client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);

var requestStream = await requestContent.GetStreamAsync();

var buffer = new byte[1024];
var readCount = await requestStream.ReadAsync(buffer);
```

Current behavior:
ReadAsync will hang forever. If the buffer size is changed to match the written content, `new byte[11]`, then ReadAsync will return.

Expected behavior:
ReadAsync returns readCount of up to 11 with matching data in the buffer.

Test: GET_ClientCancellationAfterResponseReceived_ClientGetsResponse - https://github.com/dotnet/aspnetcore/commit/6fbf0446ae906592eaecefce6d747d88e1a1801b

Logs:

```
 Interop.FunctionalTests.Http3.Http3RequestTests.GET_ClientCancellationAfterResponseReceived_ClientGetsResponse
   Source: Http3RequestTests.cs line 77
   Duration: 21.5 sec

  Message: 
System.IO.IOException : An error occurred while sending the request.
---- System.Net.Http.HttpRequestException : An error occurred while sending the request.
-------- System.Net.Quic.QuicOperationAbortedException : Operation aborted.

  Stack Trace: 
Http.dll:token 0x60006db+0xd1
Http.dll:token 0x60006da+0x282
Http3RequestTests.ReadLengthAsync(Stream body, Int32 length) line 145
Http3RequestTests.GET_ClientCancellationAfterResponseReceived_ClientGetsResponse() line 131
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
----- Inner Stack Trace -----
Quic.dll:token 0x6000158+0x109
Quic.dll:token 0x600014d+0x14
Quic.dll:token 0x6000148+0xbc
Quic.dll:token 0x6000147+0x14
--- End of stack trace from previous location ---
Quic.dll:token 0x600019c+0xf
Http.dll:token 0x60006d1+0xa5
Http.dll:token 0x60006dc+0x94
Http.dll:token 0x60006da+0xb2

  Standard Output: 
| [0.014s] TestLifetime Information: Starting test GET_ClientCancellationAfterResponseReceived_ClientGetsResponse at 2021-07-21T23:11:24
<- Event Private.InternalDiagnostics.System.Net.Http - Info : HttpClientHandler#45982785,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : SocketsHttpHandler#21168530,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpClient#48190266,.ctor,HttpClient#48190266,HttpClientHandler#45982785 ->
| [0.094s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
| [0.139s] Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer Debug: Using development certificate: CN=localhost (Thumbprint: 2584996C10BB6B5D974C7FF0A7D513F6E9BD16B8)
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#4530763,.ctor,[list][0x1DC40F046E0] Listener created ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#4530763,.ctor,[list][0x1DC40F046E0] Listener started ->
| [0.185s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:57997
| [0.192s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
| [0.193s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
| [0.193s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
| [0.193s] Microsoft.Hosting.Lifetime Information: Content root path: C:\Development\Source\AspNetCore\artifacts\bin\Interop.FunctionalTests\Debug\net6.0\
| [0.194s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
<- Event Private.InternalDiagnostics.System.Net.Http - Info : StreamingHttpContext#38803894,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpRequestMessage#43340473,Content,HttpRequestMessage#43340473,StreamingHttpContext#38803894 ->
<- Event System.Net.Http - RequestStart : https,127.0.0.1,57997,/,3,0,2 ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#15343725,.ctor,AutoConfigUrl=(null), AutoDetect=True, Proxy=(null), ProxyBypass=(null) ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#15343725,.ctor,_useProxy=True ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#15343725,TryCreate,AutoSettingsUsed, calling WinHttpOpen ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : HttpConnectionHandler#7911073,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : DiagnosticsHandler#16633715,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : RedirectHandler#9171697,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - ErrorMessage : WinInetProxyHelper#15343725,GetProxyForUrl,error=12180 ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#15343725,GetProxyForUrl,useProxy=False ->
<- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 57906006,0,0,.ctor,HttpConnectionPool https://127.0.0.1:57997 ->
<- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 57906006,0,0,GetHttp3ConnectionAsync,Attempting new HTTP3 connection. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,.ctor,[conn][0x1DC40F09FA0] Outbound connection created ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,.ctor,[conn][0x1DC41302F30] Inbound connection created ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,NativeCallbackHandler,[conn][0x1DC41302F30] Connection received event IDEAL_PROCESSOR_CHANGED ->
| [0.249s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HMACJJEBHOO8" accepted.
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event STREAMS_AVAILABLE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event DATAGRAM_STATE_CHANGED ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event PEER_CERTIFICATE_RECEIVED ->
| [0.256s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMACJJEBHOO8" accepted.
| [0.259s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMACJJEBHOO8" started.
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,HandleEvent,(null) Stream received event START_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,.ctor,[strm][0x1DC40F0DFA0] Outbound unidirectional stream created in connection [conn][0x1DC41302F30]. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,HandleEventPeerCertificateReceived,[conn][0x1DC40F09FA0] Certificate validation for '$CN=localhost' finished with $None ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event CONNECTED ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,NativeCallbackHandler,[conn][0x1DC41302F30] Connection received event CONNECTED ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22460983,HandleEvent,(null) Stream received event START_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22460983,.ctor,[strm][0x1DC40F0DB30] Outbound unidirectional stream created in connection [conn][0x1DC40F09FA0]. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22460983,HandleEvent,[strm][0x1DC40F0DB30] Stream received event SEND_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,NativeCallbackHandler,[conn][0x1DC41302F30] Connection received event PEER_STREAM_STARTED ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#60644701,.ctor,[strm][0x1DC4134E4C0] Inbound unidirectional stream created in connection [conn][0x1DC41302F30]. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#60644701,HandleEvent,[strm][0x1DC4134E4C0] Stream received event RECEIVE ->
| [0.297s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:3" type Unidirectional connected.
<- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 57906006,0,0,GetHttp3ConnectionAsync,New HTTP3 connection established. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEvent,(null) Stream received event START_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,.ctor,[strm][0x1DC413B2CC0] Outbound bidirectional stream created in connection [conn][0x1DC40F09FA0]. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,ReadAsync,[strm][0x1DC413B2CC0] Stream reading into Memory of '64' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEvent,[strm][0x1DC413B2CC0] Stream received event SEND_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,NativeCallbackHandler,[conn][0x1DC41302F30] Connection received event PEER_STREAM_STARTED ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,.ctor,[strm][0x1DC413155E0] Inbound bidirectional stream created in connection [conn][0x1DC41302F30]. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEvent,[strm][0x1DC413155E0] Stream received event RECEIVE ->
| [0.308s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Waiting for headers on client
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,HandleEvent,[strm][0x1DC40F0DFA0] Stream received event SEND_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event PEER_STREAM_STARTED ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,.ctor,[strm][0x1DC413C3FA0] Inbound unidirectional stream created in connection [conn][0x1DC40F09FA0]. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,HandleEvent,[strm][0x1DC413C3FA0] Stream received event RECEIVE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,HandleEvent,[strm][0x1DC40F0DFA0] Stream received event SEND_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,ReadAsync,[strm][0x1DC413C3FA0] Stream reading into Memory of '32' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,HandleEvent,[strm][0x1DC413C3FA0] Stream received event RECEIVE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,ReadAsync,[strm][0x1DC413C3FA0] Stream reading into Memory of '32' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,ReadAsync,[strm][0x1DC413C3FA0] Stream reading into Memory of '32' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#60644701,ReadAsync,[strm][0x1DC4134E4C0] Stream reading into Memory of '4096' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#60644701,ReadAsync,[strm][0x1DC4134E4C0] Stream reading into Memory of '4096' bytes. ->
| [0.323s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:2" type Unidirectional accepted.
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,ReadAsync,[strm][0x1DC413155E0] Stream reading into Memory of '4096' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,ReadAsync,[strm][0x1DC413155E0] Stream reading into Memory of '4096' bytes. ->
| [0.324s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:0" type Bidirectional accepted.
| [0.332s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HMACJJEBHOO8:2" received SETTINGS frame for stream ID 2 with length 5.
| [0.336s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HMACJJEBHOO8:0" received HEADERS frame for stream ID 0 with length 48.
| [0.361s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HMACJJEBHOO8:0" received DATA frame for stream ID 0 with length 11.
| [0.394s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/3 POST https://127.0.0.1:57997/ - -
| [0.400s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Flush headers on server
| [0.412s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HMACJJEBHOO8:0" sending HEADERS frame for stream ID 0 with length 53.
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEvent,[strm][0x1DC413155E0] Stream received event SEND_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEvent,[strm][0x1DC413B2CC0] Stream received event RECEIVE ->
| [0.413s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Server read body
<- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 57906006,51535865,0,ReadFrameEnvelopeAsync,Received frame 1 of length 53. ->
<- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpResponseMessage#47046334,RequestMessage,HttpResponseMessage#47046334,HttpRequestMessage#43340473 ->
<- Event Private.InternalDiagnostics.System.Net.Http - Info : HttpConnectionResponseContent#10427771,.ctor, ->
<- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpResponseMessage#47046334,Content,HttpResponseMessage#47046334,HttpConnectionResponseContent#10427771 ->
| [0.417s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMACJJEBHOO8:0", Request id "0HMACJJEBHOO8:0": started reading request body.
<- Event System.Net.Http - RequestStop :  ->
| [0.422s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Client read body
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,ReadAsync,[strm][0x1DC413B2CC0] Stream reading into Memory of '64' bytes. ->
| [0.423s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HMACJJEBHOO8:0" sending DATA frame for stream ID 0 with length 11.
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEvent,[strm][0x1DC413155E0] Stream received event SEND_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEvent,[strm][0x1DC413B2CC0] Stream received event RECEIVE ->
<- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 57906006,51535865,0,ReadFrameEnvelopeAsync,Received frame 0 of length 11. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEvent,[strm][0x1DC413155E0] Stream received event IDEAL_SEND_BUFFER_SIZE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,ReadAsync,[strm][0x1DC413B2CC0] Stream reading into Memory of '64' bytes. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,NativeCallbackHandler,[conn][0x1DC41302F30] Connection received event SHUTDOWN_INITIATED_BY_TRANSPORT ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEvent,[strm][0x1DC413155E0] Stream received event SEND_SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEvent,[strm][0x1DC413155E0] Stream received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#13273752,HandleEventConnectionClose,[strm][0x1DC413155E0] Stream handling connection [conn][0x1DC41302F30] close ->
| [20.440s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Connection id "0HMACJJEBHOO8" is closed. The last processed stream ID was 0.
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#60644701,HandleEvent,[strm][0x1DC4134E4C0] Stream received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#60644701,HandleEventConnectionClose,[strm][0x1DC4134E4C0] Stream handling connection [conn][0x1DC41302F30] close ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,HandleEvent,[strm][0x1DC40F0DFA0] Stream received event SEND_SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,HandleEvent,[strm][0x1DC40F0DFA0] Stream received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#34717384,HandleEventConnectionClose,[strm][0x1DC40F0DFA0] Stream handling connection [conn][0x1DC41302F30] close ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#6451435,NativeCallbackHandler,[conn][0x1DC41302F30] Connection received event SHUTDOWN_COMPLETE ->
| [20.448s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" sending GO_AWAY frame for stream ID 3 with length 1.
| [20.450s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:3" shutting down writes because: "The QUIC transport's send loop completed gracefully.".
| [20.452s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Trace id "0HMACJJEBHOO8:0": HTTP/3 stream error "0". An abort is being sent to the stream.
| Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/3 connection faulted.
| [20.452s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:0" aborted by application because: "The HTTP/3 connection faulted.".
| [20.453s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:0" shutting down writes because: "The QUIC transport's send loop completed gracefully.".
| [20.449s] Microsoft.AspNetCore.Server.Kestrel Warning: Stream threw an unexpected exception.
| System.Net.Quic.QuicOperationAbortedException: Operation aborted.
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(State state) in System.Net.Quic.dll:token 0x6000158+0x109
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(State state, StreamEvent& evt) in System.Net.Quic.dll:token 0x600014d+0x14
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(State state, StreamEvent& evt) in System.Net.Quic.dll:token 0x6000148+0xbc
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler(IntPtr stream, IntPtr context, StreamEvent& streamEvent) in System.Net.Quic.dll:token 0x6000147+0x14
| --- End of stack trace from previous location ---
|    at System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource`1.GetResult(Int16 token) in System.Net.Quic.dll:token 0x600019c+0xf
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.ProcessReceives() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 226
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.DoReceive() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 184
|    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result) in System.IO.Pipelines.dll:token 0x6000075+0x0
|    at System.IO.Pipelines.Pipe.GetReadAsyncResult() in System.IO.Pipelines.dll:token 0x6000074+0x42
|    at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token) in System.IO.Pipelines.dll:token 0x600018d+0x0
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Stream.ProcessRequestAsync[TContext](IHttpApplication`1 application) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http3\Http3Stream.cs:line 390
| [20.455s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Trace id "(null)": HTTP/3 stream error "0". An abort is being sent to the stream.
| Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/3 connection faulted.
| [20.456s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMACJJEBHOO8:3" aborted by application because: "The HTTP/3 connection faulted.".
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event SHUTDOWN_INITIATED_BY_TRANSPORT ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEvent,[strm][0x1DC413B2CC0] Stream received event SEND_SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEvent,[strm][0x1DC413B2CC0] Stream received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#30135413,HandleEventConnectionClose,[strm][0x1DC413B2CC0] Stream handling connection [conn][0x1DC40F09FA0] close ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22460983,HandleEvent,[strm][0x1DC40F0DB30] Stream received event SEND_SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22460983,HandleEvent,[strm][0x1DC40F0DB30] Stream received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22460983,HandleEventConnectionClose,[strm][0x1DC40F0DB30] Stream handling connection [conn][0x1DC40F09FA0] close ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,HandleEvent,[strm][0x1DC413C3FA0] Stream received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,HandleEventConnectionClose,[strm][0x1DC413C3FA0] Stream handling connection [conn][0x1DC40F09FA0] close ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#49119442,NativeCallbackHandler,[conn][0x1DC40F09FA0] Connection received event SHUTDOWN_COMPLETE ->
<- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 57906006,0,0,Dispose,Disposing pool. ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,Dispose,[strm][0x1DC413C3FA0] Stream disposing True ->
<- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#11373314,Dispose,[strm][0x1DC413C3FA0] Stream disposed ->
| [20.477s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Listener has aborted with exception: Operation aborted.
| [20.480s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HMACJJEBHOO8" aborted by application because: "The connection was aborted by the application via MultiplexedConnectionContext.Abort().".
| [20.483s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to close gracefully during server shutdown.
| [20.489s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HMACJJEBHOO8" aborted by application because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.".
| [21.493s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to abort during server shutdown.
| [21.501s] Interop.FunctionalTests.Http3.Http3RequestTests Error: Test threw an exception.
| System.IO.IOException: An error occurred while sending the request.
|  ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
|  ---> System.Net.Quic.QuicOperationAbortedException: Operation aborted.
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(State state) in System.Net.Quic.dll:token 0x6000158+0x109
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(State state, StreamEvent& evt) in System.Net.Quic.dll:token 0x600014d+0x14
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(State state, StreamEvent& evt) in System.Net.Quic.dll:token 0x6000148+0xbc
|    at System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler(IntPtr stream, IntPtr context, StreamEvent& streamEvent) in System.Net.Quic.dll:token 0x6000147+0x14
| --- End of stack trace from previous location ---
|    at System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource`1.GetResult(Int16 token) in System.Net.Quic.dll:token 0x600019c+0xf
|    at System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006d1+0xa5
|    at System.Net.Http.Http3RequestStream.ReadNextDataFrameAsync(HttpResponseMessage response, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006dc+0x94
|    at System.Net.Http.Http3RequestStream.ReadResponseContentAsync(HttpResponseMessage response, Memory`1 buffer, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006da+0xb2
|    --- End of inner exception stack trace ---
|    --- End of inner exception stack trace ---
|    at System.Net.Http.Http3RequestStream.HandleReadResponseContentException(Exception ex, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006db+0xd1
|    at System.Net.Http.Http3RequestStream.ReadResponseContentAsync(HttpResponseMessage response, Memory`1 buffer, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006da+0x282
|    at Interop.FunctionalTests.Http3.Http3RequestTests.ReadLengthAsync(Stream body, Int32 length) in C:\Development\Source\AspNetCore\src\Servers\Kestrel\test\Interop.FunctionalTests\Http3\Http3RequestTests.cs:line 145
|    at Interop.FunctionalTests.Http3.Http3RequestTests.GET_ClientCancellationAfterResponseReceived_ClientGetsResponse() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\test\Interop.FunctionalTests\Http3\Http3RequestTests.cs:line 131
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
| [21.516s] TestLifetime Information: Finished test GET_ClientCancellationAfterResponseReceived_ClientGetsResponse in 21.5100008s
```

**Comment by geoffkizer** [comment]
That seems really bad.

@CarnaViire is this related to your recent read changes? I doubt it, or we would have seen it in QUIC tests...

I'll investigate later.

**Comment by geoffkizer** [comment]
@jamesnk is this a duplex scenario?

**Comment by JamesNK** [comment]
Yes

**Comment by geoffkizer** [comment]
Ah that makes more sense, thanks.

We have no duplex tests for HTTP3 yet. The existing ones are HTTP2-specific and so need to be modified manually to work with HTTP3.

We'll put this on the TODO list, hopefully it's not blocking you too badly...

**Comment by JamesNK** [comment]
It appears I can read the exact length successfully. I'm not blocked. _Yet_ 😋

**Comment by CarnaViire** [comment]
I don't remember duplex tests for S.N.Quic either, but I've just tried this
```c#
        [Fact]
        public async Task ReadWriteWithoutFin()
        {
            int bytesSent = 11;
            var clientData1 = new byte[bytesSent];
            var clientData2 = new byte[bytesSent];
            var serverData = new byte[bytesSent];
            Random.Shared.NextBytes(clientData1);
            Random.Shared.NextBytes(clientData2);
            Random.Shared.NextBytes(serverData);

            using var sem = new SemaphoreSlim(0);

            await RunClientServer(
                serverFunction: async connection =>
                {
                    await using QuicStream stream = await connection.AcceptStreamAsync();

                    byte[] buffer = new byte[1024];
                    int bytesRead = await stream.ReadAsync(buffer);
                    // no FIN flag from peer here
                    Assert.Equal(bytesSent, bytesRead);
                    AssertExtensions.SequenceEqual(clientData1, buffer[..bytesRead]);

                    await stream.WriteAsync(serverData);
                    // no FIN flag sent to peer here

                    bytesRead = await stream.ReadAsync(buffer);
                    Assert.Equal(bytesSent, bytesRead);
                    AssertExtensions.SequenceEqual(clientData2, buffer[..bytesRead]);

                    sem.Release();

                    stream.Shutdown();
                    await stream.ShutdownCompleted();
                },
                clientFunction: async connection =>
                {
                    await using QuicStream stream = connection.OpenBidirectionalStream();

                    await stream.WriteAsync(clientData1);
                    // no FIN flag sent to peer here

                    byte[] buffer = new byte[1024];
                    int bytesRead = await stream.ReadAsync(buffer);
                    // no FIN flag from peer here
                    Assert.Equal(bytesSent, bytesRead);
                    AssertExtensions.SequenceEqual(serverData, buffer[..bytesRead]);

                    await stream.WriteAsync(clientData2);
                    // no FIN flag sent to peer here

                    await sem.WaitAsync();

                    stream.Shutdown();
                    await stream.ShutdownCompleted();
                }
            );
        }
```
And duplex on Quic side seems ok. Possibly something on HTTP/3 side. I don't know how to easily check HTTP/3 yet.

**Comment by geoffkizer** [comment]
The HTTP2 duplex tests are here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L2497

Most of the relevant test methods are named "PostAsyncDuplex_*".

**Comment by karelz** [comment]
Triage: We should find out if it is Duplex specific - if yes, punt it to 7.0.

**Comment by JamesNK** [comment]
It isn't specific to duplex. Unit test repo of GET request with this issue: https://github.com/dotnet/aspnetcore/commit/c8424252bb5e1fadea91fa7e15057f0ed73bff35
