### ISSUE TITLE
QUIC: Wrong exception for Open*Stream after connection is closed

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#56133]
If you call Open*Stream after closing a QuicConnection (or having it closed by the peer), you get a QuicException with a message that says "Failed to open stream to peer. Error Code: INVALID_STATE".

Expected behavior: QuicOperationAbortedException (if you closed locally) or QuicConnectionAbortedException (if the peer closed the connection).

**Comment by wfurt** [comment]
I got similar one as:
```
Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Net.Quic.QuicStreamAbortedException)
Actual:   typeof(System.Net.Quic.QuicException): Could not send data to peer. Error Code: INVALID_STATE
   at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/QuicExceptionHelpers.cs:line 12
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(ReadOnlyMemory`1 buffer, QUIC_SEND_FLAGS flags) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1155
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlyMemory`1 buffer, Boolean endStream, CancellationToken cancellationToken) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 257
   at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload) in /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 155
   at System.Net.Test.Common.Http3LoopbackStream.SendDataFrameAsync(ReadOnlyMemory`1 data) in /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 126
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendDataForever(Http3LoopbackStream stream) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 714
   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 81
```

as @ManickaP mentioned in #53224, 
https://github.com/microsoft/msquic/blob/3898b2b88085a478eeb844885ea78daa9b060d06/src/core/stream.c#L207-L211

this can happen when the connection is closed either locally or remotely. 
It feels like this is pretty hard to disambiguate and handle. 
Would it be possible to get different/unique error @nibanks at least for the case when this was closed by the peer?

**Comment by nibanks** [comment]
@wfurt yes, it'd be possible to do so. We'd have to make sure that there's no existing code depending on the `QUIC_STATUS_INVALID_STATE`. Please open an issue on MsQuic and we can discuss it there.

**Comment by wfurt** [comment]
thanks @nibanks.

**Comment by ManickaP** [comment]
We should test this and confirm it's fixed, eventually fix up exception we throw. But msquic side should be fixed.

**Comment by ManickaP** [comment]
I retested this and we get: `System.Net.Quic.QuicException: Failed to open stream to peer. Error Code: ABORTED` so atm it's up to us to translate the error code properly into better exception.
