### ISSUE TITLE
Https requests on Debian fails with SSL error

### ISSUE THREAD

**Issue by alyssajotice** [dotnet/runtime#56169]
### Description

Live Share from a Debian machine does not work due to the following error: `Could not connect to the server. HTTPS connection failed, verify there are no self-signed certificates or custom cert validation policies blocking Live Share.`

Looks similar to https://github.com/dotnet/runtime/issues/29855, but I am using openssl 1.1.1d and do not have any previous versions downloaded. 

Error

```
[2021-07-22 16:39:38.081 Agent.Rpc.Auth V] < #1 {Id=12 Error={Code=-32060 Message=The SSL connection could not be established, see inner exception. Data=(StackTrace=System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.LiveShare.Tracing.TracingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\a\1\s\src\Tracing\Tracing\TracingHttpMessageHandler.cs:line 63
   at Microsoft.Cascade.Agent.ForwardResponseMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\a\1\s\src\Agent\ForwardResponseMessageHandler.cs:line 50
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Cascade.Agent.AuthenticationService.GetCurrentUserAsync(CancellationToken cancellationToken) in C:\a\1\s\src\Agent\AuthenticationService.cs:line 800
   at Microsoft.Cascade.Agent.AuthenticationService.RetrieveUserInfoAsync(String authToken, AuthenticationOptions options, Boolean shouldUpdateCurrentSession, CancellationToken cancellationToken) in C:\a\1\s\src\Agent\AuthenticationService.cs:line 525
   at Microsoft.Cascade.Agent.AuthenticationService.LoginAsync(AuthenticationToken loginTokenOrCode, AuthenticationOptions options, UserInfo userInfo, CancellationToken cancellationToken) in C:\a\1\s\src\Agent\AuthenticationService.cs:line 218
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in C:\a\1\s\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous locat...
```

### Configuration

* What OS and version, and what distro if applicable?  Debian GNU\Linux 10 (buster) WSL
* What is the architecture (x64, x86, ARM, ARM64)? 5.10.16.3-microsoft-standard-WSL2
* Do you know whether it is specific to that configuration? The problem reproduces with Debian 10 outside of WSL as well

Live Share bug: https://github.com/MicrosoftDocs/live-share/issues/4000

**Comment by wfurt** [comment]
Try to add custom validation and check why:
```c#
            handler.ServerCertificateCustomValidationCallback = (request, cert, chain, errors) =>
                {
                    Console.WriteLine($"SslPolicyErrors: {errors}");

                    if (chain == null)
                    {
                        Console.WriteLine("No chain...");
                    }
                    else
                    {
                        foreach (X509ChainElement element in chain.ChainElements)
                        {
                            Console.WriteLine();
                            Console.WriteLine(element.Certificate.Subject);
                            Console.WriteLine(element.ChainElementStatus.Length);
                            foreach (X509ChainStatus status in element.ChainElementStatus)
                            {
                                Console.WriteLine($"Status:  {status.Status}: {status.StatusInformation}");
                            }
                        }
                    }

                    return true;
                };
```
You can also iterate through system's `Root` certificate store and check that the server you connecting to is signed by CA from that list.

**Comment by wfurt** [comment]
The trace looks like 3.1, can you confirm?

**Comment by alyssajotice** [comment]
Yes, we're on 3.1.408.

**Comment by karelz** [comment]
Triage: @alyssajotice did you get chance to try the above suggestion?
Also, are you in position to try it on 5.0 or 6.0 bits?

**Comment by alyssajotice** [comment]
@karelz, here is the result of the code. I added the first line above the custom validation code. There is a different error now. However, I do not see any of strings that are in the callback code you wrote. 

```
[2021-07-28 19:36:39.697 Agent.Auth E] Test Error in ForwardResponseMessageHandler
[2021-07-28 19:36:39.701 Agent-HubConnectionService V] SetUserInfoAsync -> <null>
[2021-07-28 19:36:39.701 Agent.Rpc.Auth V] < #1 {Name=auth.authenticationChanged}
[2021-07-28 19:36:39.716 Agent.Rpc.Auth E] Exception in auth.login request handler: System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.
   at System.Net.Http.SocketsHttpHandler.CheckDisposedOrStarted()
   at System.Net.Http.HttpClientHandler.set_ServerCertificateCustomValidationCallback(Func`5 value)
   at Microsoft.Cascade.Agent.ForwardResponseMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\ForwardResponseMessageHandler.cs:line 84
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Cascade.Agent.AuthenticationService.GetCurrentUserAsync(CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\AuthenticationService.cs:line 800
   at Microsoft.Cascade.Agent.AuthenticationService.RetrieveUserInfoAsync(String authToken, AuthenticationOptions options, Boolean shouldUpdateCurrentSession, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\AuthenticationService.cs:line 525
   at Microsoft.Cascade.Agent.AuthenticationService.LoginAsync(AuthenticationToken loginTokenOrCode, AuthenticationOptions options, UserInfo userInfo, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\AuthenticationService.cs:line 218
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in C:\Users\allytice\Cascade\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in C:\Users\allytice\Cascade\src\Rpc\RpcSession.cs:line 712
[2021-07-28 19:36:39.721 Agent.Rpc.Auth V] < #1 {Id=12 Error={Code=-32098 Message=This instance has already started one or more requests. Properties can only be modified before sending the first request. Data=(StackTrace=System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.
   at System.Net.Http.SocketsHttpHandler.CheckDisposedOrStarted()
   at System.Net.Http.HttpClientHandler.set_ServerCertificateCustomValidationCallback(Func`5 value)
   at Microsoft.Cascade.Agent.ForwardResponseMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\ForwardResponseMessageHandler.cs:line 84
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Cascade.Agent.AuthenticationService.GetCurrentUserAsync(CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\AuthenticationService.cs:line 800
   at Microsoft.Cascade.Agent.AuthenticationService.RetrieveUserInfoAsync(String authToken, AuthenticationOptions options, Boolean shouldUpdateCurrentSession, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\AuthenticationService.cs:line 525
   at Microsoft.Cascade.Agent.AuthenticationService.LoginAsync(AuthenticationToken loginTokenOrCode, AuthenticationOptions options, UserInfo userInfo, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Agent\AuthenticationService.cs:line 218
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in C:\Users\allytice\Cascade\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in C:\Users\allytice\Cascade\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in C:\Users\allytice\Cascade\src\Rpc\RpcSession.cs:line 712)}}
[2021-07-28 19:37:02.317 Agent-ObjectTracker V] Remove item:KeepAliveAgent reason:AgentStarted delay:30000 count:1 others:[RpcSession #1]
```

**Comment by wfurt** [comment]
```
[2021-07-28 19:36:39.716 Agent.Rpc.Auth E] Exception in auth.login request handler: System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before sending the first request.
   at System.Net.Http.SocketsHttpHandler.CheckDisposedOrStarted()
   at System.Net.Http.HttpClientHandler.set_ServerCertificateCustomValidationCallback(Func`5 value)
```
something funky is going on with your code. Make sure the HttpClient/Handler is in good shape. 

One way how to proceed would be minimal repro just with SslStream or HttpClient. 
If the problem lives with certificate trust or SSL you should see same results without all the other layers @alyssajotice

**Comment by alyssajotice** [comment]
It ended up being an incorrectly signed certificate. Thanks for the help! Closing the issue.
