### ISSUE TITLE
Test failure: ConnectWithCertificateCallback

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56263]
Test type: System.Net.Quic.Tests.MsQuicTests

```
System.NullReferenceException : Object reference not set to an instance of an object

   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 607
   at System.Net.Quic.QuicConnection.ConnectAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 68
   at System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateCallback() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 220
--- End of stack trace from previous location ---
```

Failures 5/24-7/27 (incl. PRs):

Day | Failures
-- | --
7/23 | 7x PR failures (6 distinct PRs)
7/24 | 2x Official run
7/25 | 1x PR
7/26 | 2x PR
7/26 | **Test disabled**
7/27 (incomplete date) | 1x PR

We should disable the test due to high failure rate

**Comment by wfurt** [comment]
That code was reworked recently. I think we should wait to see at least some more failures on official runs. PRs can be pretty stale IMHO. (with regard to quic/h3)

**Comment by karelz** [comment]
@wfurt 2 failures are now on official runs -- test is now disabled.
