### ISSUE TITLE
System.Net.NameResolution.Functional.Tests failing on Ubuntu 16.04 and Debian9

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56295]
Failing tests ("Name or service not known"):
- System.Net.NameResolution.Tests.GetHostEntryTest:
  - Dns_GetHostEntry_HostString_Ok("")
  - Dns_GetHostEntryAsync_HostString_Ok("")
  - Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses("")
  - Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses("")
- System.Net.NameResolution.Tests.GetHostByNameTest:
  - DnsObsoleteGetHostByName_EmptyString_ReturnsHostName
  - DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName

Similar to SLES failures in #55271

Failures 5/26-7/27 (incl. PRs):

Day | Failures
-- | --
7/25 | 3x Official run + 6x PR
7/26 | 9x Official + 50x PR
7/27 (incomplete day) | 2x PR

Failures callstacks:
<details>
Failure:
  - DnsObsoleteGetHostByName_EmptyString_ReturnsHostName
  - DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known

   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 403
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 384
   at System.Net.Dns.GetHostByName(String hostName) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 271
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 116
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

Failure:
  - Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses
  - Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Child exception:
  System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 403
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 384
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_1(Object s) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 591
   at System.Net.Dns.<>c__DisplayClass39_0`1[[System.Net.IPHostEntry, System.Net.NameResolution, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RunAsync>b__0(Task <p0>, Object <p1>) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 688
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Net.IPHostEntry, System.Net.NameResolution, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 94
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2369
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 293
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2331
--- End of stack trace from previous location ---
   at System.Net.NameResolution.Tests.GetHostEntryTest.<Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses>g__RunTest|8_0(String hostnameInner) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 152
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in Microsoft.DotNet.RemoteExecutor.dll:token 0x6000006+0xf5

Child process:
  System.Net.NameResolution.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.GetHostEntryTest System.Threading.Tasks.Task <Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses>g__RunTest|8_0(System.String)

Child arguments:
```

Failure: Dns_GetHostEntry_HostString_Ok
```
System.Exception : Failed for empty hostname.
Dns.GetHostName() == a008NNH
getHostEntryException==System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 403
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 384
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 91
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 60
   at System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_HostString_Ok(String hostName) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 60
etcHostsException==
/etc/host ==
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
```

Failure Dns_GetHostEntryAsync_HostString_Ok:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Name or service not known)) (One or more errors occurred. (Name or service not known))
---- System.AggregateException : One or more errors occurred. (Name or service not known)
-------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
---- System.AggregateException : One or more errors occurred. (Name or service not known)
-------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known

   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 80
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 112
   at System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_HostString_Ok(String hostName) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 100
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 403
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 384
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_1(Object s) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 591
   at System.Net.Dns.<>c__DisplayClass39_0`1[[System.Net.IPHostEntry, System.Net.NameResolution, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RunAsync>b__0(Task <p0>, Object <p1>) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 688
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Net.IPHostEntry, System.Net.NameResolution, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 94
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2369
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 293
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2331
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 63
----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 403
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 384
   at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_1(Object s) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 591
   at System.Net.Dns.<>c__DisplayClass39_0`1[[System.Net.IPHostEntry, System.Net.NameResolution, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].<RunAsync>b__0(Task <p0>, Object <p1>) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 688
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.Net.IPHostEntry, System.Net.NameResolution, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 94
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2369
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 293
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2331
```
</details>

**Comment by karelz** [comment]
@antonfirsov @wfurt any idea what is going on? Looks like 2 more distros (beside SLES) have now problem with DNS resolution of empty string.

**Comment by karelz** [comment]
Tests disabled in PR #56296 on 7/26

**Comment by karelz** [comment]
@dotnet/dncenghot it looks like these 2 images changed and regressed behavior of self-resolution (empty string passed to DNS). Can they be fixed please?
It is similar to what happened recently on SLES (2-3 weeks ago). We are slowly loosing coverage./

Also, is there a way to add it as a smoke test for new images?

**Comment by MattGal** [comment]
> @dotnet/dncenghot it looks like these 2 images changed and regressed behavior of self-resolution (empty string passed to DNS). Can they be fixed please?
> It is similar to what happened recently on SLES (2-3 weeks ago). We are slowly loosing coverage./
> 
> Also, is there a way to add it as a smoke test for new images?

Nothing has changed in the time range you're listing; we roll out updates on Wednesdays, and the first day you list is 7/25.    Neither image has changed since 6/25/2021, nor has anything we run on them.

I'll take a few minutes to investigate your failures; I suspect something running before your work items is badly behaved.

**Comment by wfurt** [comment]
This is not necessarily just about the image. It is about ability for machine to resolve own name.

**Comment by MattGal** [comment]
Sure, I was responding to " it looks like these 2 images changed" and letting you know that hasn't happened for over a month.

**Comment by karelz** [comment]
For completeness: We discussed making our tests resilient to this technically valid setup of Linux, however -- that would remove our code coverage as we wouldn't know if all images are already in the bucket of "tainted" or not ...
Hopefully we will find out what ran before us that caused this ...

**Comment by MattGal** [comment]
Created https://github.com/dotnet/core-eng/issues/13889.  I ran your exact failing work items on Debian 9 and Ubuntu 16.04 and am convinced the problem has nothing to do with the behaviors of any previous work items, rather this seems like a symptom of VMs starting up a bit fast and the child processes of the Helix client not having functional DNS ready.  We had worked around this in the past but unintentionally lost the kludge when moving off cron to start agents. (see other issue for notes)

**Comment by karelz** [comment]
THanks @MattGal for tracking it down! I assume it may help us also with the same problem on SLES - see #55271.

**Comment by MattGal** [comment]
> Thanks @MattGal for tracking it down! I assume it may help us also with the same problem on SLES - see #55271.

Yes, I'd expect this to help that as well, though it missed this week's "train" and wouldn't roll out until next Weds.  Fingers crossed.

**Comment by karelz** [comment]
@MattGal no rush - if the number of affected distros doesn't go up in the meantime, we can live in this state for a while.
