### ISSUE TITLE
SerialPort: Cannot open with 128000 baudrate.

### ISSUE THREAD

**Issue by pawelpetruch** [dotnet/runtime#563]
Hi,

I am experiencing a problem when trying to open a serial port using 128000 baudrate on RPi 3 Model B v 1.2. The Pi supports this baudrate using Python serial library just fine. 

The issue doesn't occur with other baudrates.

Is there any quick workaround this?  

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/dotnet-arm32/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/home/pi/dotnet-arm32/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/home/pi/dotnet-arm32/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/home/pi/dotnet-arm32/shared/Microsoft.NETCore.App]
```

Code:

```
Available serial ports:
0. /dev/ttyAMA0
1. /dev/ttyACM0

Selected com port: /dev/ttyACM0 with baudrate: 128000.
Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
```

**Comment by krwq** [comment]
@pawelpetruch this is not RPi specific, it's related to the issue already mentioned in here: https://github.com/dotnet/corefx/issues/33146#issuecomment-559659142

In short, we only support following baud rates at the moment:
https://github.com/dotnet/runtime/blob/master/src/libraries/Native/Unix/System.IO.Ports.Native/pal_termios.c#L147

in order to support baud rates in between those values we would need to set custom_divisor as mentioned in here:
https://github.com/dotnet/corefx/issues/33146#issuecomment-562250631

**Comment by krwq** [comment]
@wfurt did you perhaps had a chance to play with higher baud rates? I can't see any larger baud rate which would divide nicely to give 128000 so I'm not sure if we can use similar baud rate or if python is doing something different (assuming the license allows it we can probably check)

**Comment by wfurt** [comment]
no I don't @krwq. If we can trace of what Python does (or get simple C example) we can probably fix it. I look at termios.h on Linux and there are higher speeds but 128000 is not there. 
One can execute setserial or pinvoke functions. As far as I know we will try to set speed only once and that can be changed later without impacting IO.Ports AFAIK.

**Comment by dmrayt** [comment]
I had the same error as i tried to connect to serial port on an embedded linux with a baud rate of 750000.

I found the following C code to set a custom baud rate on linux at [https://developer.toradex.com/knowledge-base/uart-(linux)#vybrid-modules](https://developer.toradex.com/knowledge-base/uart-(linux)#vybrid-modules)

```c
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>
#include <asm/termios.h>
 
int main(int argc, char* argv[]) {
 
	int retval, fd, speed;
	struct termios2 ntio;
 
	if (argc != 3) {
		printf("Usage: %s /dev/ttyXXX 20000\n", argv[0], argv[0]);                   
		return -1;
	}
 
	speed = atoi(argv[2]);
	fd = open(argv[1], O_RDONLY);
	if (fd < 0) {
		perror("Open");
		return -1;
	}
 
	ioctl(fd, TCGETS2, &ntio);
	ntio.c_cflag &= ~CBAUD;
	ntio.c_cflag |= BOTHER;
	ntio.c_ispeed = speed;
	ntio.c_ospeed = speed;
	retval = ioctl(fd, TCSETS2, &ntio);
	close(fd);
 
	if (retval == 0)
		printf("New baud configured\n");
	else
		perror("ioctl");
 
	return 0;
}
```

I hope this can help you.

**Comment by MichaelCarey** [comment]
@carlossanlop  Hi, I noticed that this is marked as "future". Is there any update on when this might be released?? 
dotnet appears to reset the uart clock freq to a default setting when the port is opened which closes any back door to playing with the base baud. I may have missed some other "back door" but not savvy enough to figure it out.  So... appreciate any news on a release to allows non-standard baud rates. Thanks much!
