### ISSUE TITLE
[Regression] NegotiateClientCertificateAsync exceptions do not clear the read or write locks

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#56345]
Receiving POST request body data during NegotiateClientCertificateAsync isn't supported since it can clog the connection, and an InvalidOperationException("Client stream needs to be drained before renegotiation.") is thrown as expected. However, after the exception is thrown the stream is left in a bad state and hit the following errors:
```
 Standard Output: 
    | [0.006s] TestLifetime Information: Starting test RenegotiateForClientCertificateOnPostWithoutBufferingThrows_TLS13 at 2021-07-26T23:36:40
    | [0.039s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
    | [0.155s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:0
    | [0.159s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly InMemory.FunctionalTests
    | [0.159s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
    | [0.159s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
    | [0.159s] Microsoft.Hosting.Lifetime Information: Content root path: D:\github\AspNetCore\artifacts\bin\InMemory.FunctionalTests\Debug\net6.0\
    | [0.160s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
    | [0.167s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAGHOS51GCO" accepted.
    | [0.169s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAGHOS51GCO" started.
    | [0.197s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection "0HMAGHOS51GCO" established using the following protocol: Tls13
    | [0.242s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.0 POST https:/// - 4096
    | [0.265s] Microsoft.AspNetCore.Server.Kestrel Error: Unexpected exception in TimingPipeFlusher.FlushAsync.
    | System.NotSupportedException:  The WriteAsync method cannot be called when another write operation is pending.
    |    at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer) in System.Net.Security.dll:token 0x60002fd+0x4b
    |    at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken) in System.IO.Pipelines.dll:token 0x6000151+0x16e
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.ConcurrentPipeWriter.FlushAsyncAwaited(ValueTask`1 flushTask, CancellationToken cancellationToken) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\PipeWriterHelpers\ConcurrentPipeWriter.cs:line 154
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.TimingPipeFlusher.TimeFlushAsyncAwaited(ValueTask`1 pipeFlushTask, MinDataRate minRate, IHttpOutputAborter outputAborter, CancellationToken cancellationToken) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\PipeWriterHelpers\TimingPipeFlusher.cs:line 89
    | [0.302s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.0 POST https:/// - 4096 - 200 0 - 61.5421ms
    | [0.308s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMAGHOS51GCO", Request id "0HMAGHOS51GCO:00000002": started reading request body.
    | [0.313s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HMAGHOS51GCO", Request id "0HMAGHOS51GCO:00000002": the application completed without reading the entire request body.
    | [0.315s] Microsoft.AspNetCore.Server.Kestrel Warning: Connection processing ended abnormally.
    | System.NotSupportedException:  The ReadAsync method cannot be called when another read operation is pending.
    |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer) in System.Net.Security.dll:token 0x60002fb+0x3a
    |    at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|36_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken) in System.IO.Pipelines.dll:token 0x6000132+0x111
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\Http1ContentLengthMessageBody.cs:line 63
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsyncAwaited() in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\Http1MessageBody.cs:line 94
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 750
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 569
    | [0.318s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAGHOS51GCO" disconnecting.
    | [0.322s] Microsoft.AspNetCore.Server.Kestrel Error: Unhandled exception while processing 0HMAGHOS51GCO.
    | System.NotSupportedException:  The WriteAsync method cannot be called when another write operation is pending.
    |    at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer) in System.Net.Security.dll:token 0x60002fd+0x4b
    |    at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken) in System.IO.Pipelines.dll:token 0x6000151+0x16e
    |    at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception) in System.IO.Pipelines.dll:token 0x600014c+0xaa
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter`1.DisposeAsync() in D:\github\AspNetCore\src\Shared\ServerInfrastructure\DuplexPipeStreamAdapter.cs:line 52
    |    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Middleware\HttpsConnectionMiddleware.cs:line 218
    |    at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context) in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Middleware\HttpsConnectionMiddleware.cs:line 218
    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync() in D:\github\AspNetCore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\KestrelConnectionOfT.cs:line 55
    | [0.324s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAGHOS51GCO" stopped.
    | [0.330s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
    | [0.331s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
    | [0.336s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
    | [0.344s] Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsConnectionMiddlewareTests Error: Test threw an exception.
    | System.InvalidOperationException: Memory pool with active blocks is being disposed, 7 of 8 returned
    |    at System.Buffers.MemoryPoolThrowHelper.ThrowInvalidOperationException_DisposingPoolWithActiveBlocks(Int32 returned, Int32 total, DiagnosticPoolBlock[] blocks) in D:\github\AspNetCore\src\Shared\Buffers.MemoryPool\MemoryPoolThrowHelper.cs:line 62
    |    at System.Buffers.DiagnosticMemoryPool.Dispose(Boolean disposing) in D:\github\AspNetCore\src\Shared\Buffers.MemoryPool\DiagnosticMemoryPool.cs:line 119
    |    at System.Buffers.MemoryPool`1.Dispose() in System.Memory.dll:token 0x6000051+0x0
    |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.TestServer.DisposeAsync() in D:\github\AspNetCore\src\Servers\Kestrel\test\InMemory.FunctionalTests\TestTransport\TestServer.cs:line 147
    |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsConnectionMiddlewareTests.RenegotiateForClientCertificateOnPostWithoutBufferingThrows_TLS13() in D:\github\AspNetCore\src\Servers\Kestrel\test\InMemory.FunctionalTests\HttpsConnectionMiddlewareTests.cs:line 795
    |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
    | --- End of stack trace from previous location ---
    |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
    |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
    | [0.371s] TestLifetime Information: Finished test RenegotiateForClientCertificateOnPostWithoutBufferingThrows_TLS13 in 0.3684851s
```

These make it difficult for Kestrel to even abort and clean up the connection gracefully.

This appears to be a regression since the initial implementation. @wfurt suggested that the read and write locks need to be released on failure.

Expectation: Either
- the locks should be released and the stream be usable again or
- the stream should throw better errors about being aborted/invalid, etc.

**Comment by wfurt** [comment]
can you take a look @aik-jahoda

**Comment by wfurt** [comment]
https://github.com/dotnet/runtime/blob/16b456426dfb5212a24bfb78bfd5d9adfcc95185/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L271 should be probably moved before grabbing the read/write lock.
