### ISSUE TITLE
Test failure: StreamWindowScaleThresholdMultiplier_HighValue_WindowScalesSlower

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56372]
Test: System.Net.Http.Functional.Tests.SocketsHttpHandler_Http2FlowControl_Test.StreamWindowScaleThresholdMultiplier_HighValue_WindowScalesSlower

Failures 5/27-7/28 (incl. PRs):

Day | Run | OS
-- | -- | --
7/22 | Official run | Windows.10.Amd64.ServerRS5.Open
7/23 | Official run | Windows.81.Amd64.Open
7/26 | Official run | Windows.Nano.1809.Amd64.Open
7/27 | Official run | Windows.Nano.1809.Amd64.Open
7/28 | Official run | Fedora.30.Amd64.Open

```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_Http2FlowControl_Test.<StreamWindowScaleThresholdMultiplier_HighValue_WindowScalesSlower>g__RunTest|11_0() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.Http2FlowControl.cs:line 147
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Http.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.SocketsHttpHandler_Http2FlowControl_Test System.Threading.Tasks.Task <StreamWindowScaleThresholdMultiplier_HighValue_WindowScalesSlower>g__RunTest|11_0()
```

**Comment by karelz** [comment]
@antonfirsov this looks like a new test, perhaps related to your recent feature?
