### ISSUE TITLE
Failure test:baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56444]
Run [runtime-coreclr jitstress 20210726.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1260236&view=ms.vss-test-web.build-test-results-tab&runId=37356246&resultId=111085&paneView=debug)
Failed test:
```
CoreCLR Linux arm64 Checked jitminopts @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

```
**Error message:**
```
Process terminated. Parallel crash in thread 2!

at System.Environment.FailFast(System.String)
at ParallelCrash.CrashInParallel()
at System.Threading.Thread.StartCallback()
{0x1bb2-0x7f96d7d728} ASSERT [DEBUG  ] at /__w/1/s/src/coreclr/pal/src/debug/debug.cpp.216: failed to convert wide chars to multibytes
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f96daf42c)

cmdLine:/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 7/27/2021 5:23:03 AM, end: 7/27/2021 5:53:03 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/root/helix/work/correlation/corerun ParallelCrash.dll '2'
Gathering state for process 7072 corerun
Crashing thread 00001bb1 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7072.dmp
Written 138911744 bytes (33914 pages) to core file
Dump successfully written

cmdLine:/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 7/27/2021 5:23:03 AM, end: 7/27/2021 5:53:03 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh() in baseservices.exceptions.XUnitWrapper.dll:token 0x60000ee+0x295
```

**Comment by mangod9** [comment]
@janvorli I remember you discussing the unicode -> utf8 conversion issue yesterday. Is this assert related to the same issue?

**Comment by janvorli** [comment]
Yes, this is the issue I've fixed

**Comment by janvorli** [comment]
By #56388

**Comment by mangod9** [comment]
Ok closing based on that.
