### ISSUE TITLE
Assertion failed in PoolingAsyncValueTaskMethodBuilderT

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#56459]
@stephentoub I've found one interesting failure in the [logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56424-merge-c50d453f92c741ee9a/System.IO.FileSystem.DisabledFileLocking.Tests/console.c1d1b5ac.log?sv=2019-07-07&se=2021-08-16T22%3A05%3A14Z&sr=c&sp=rl&sig=befKPtSZ4zIoEl4wOIu9%2BLoUlQkS0bJzg2eIM%2FlwxNs%3D) of the CI run for #56424.

```log
Process terminated. Assertion failed.
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:line 419
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 638
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs:line 233
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs:line 62
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox.SetResult(TResult result) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:line 250
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.SetResult(TResult result) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:line 60
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadAsyncSlowPath(Task semaphoreLockTask, Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs:line 492
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:line 389
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 183
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs:line 410
   at System.Threading.ThreadPool.<>c.<.cctor>b__84_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1059
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs:line 233
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SetResult(TResult result) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs:line 62
   at System.IO.Strategies.UnixFileStreamStrategy.ReadAsyncTaskSource.Read() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/UnixFileStreamStrategy.cs:line 147
   at System.IO.Strategies.UnixFileStreamStrategy.ReadAsyncTaskSource.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/UnixFileStreamStrategy.cs:line 106
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 708
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 63
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
./RunTests.sh: line 162: 71058 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.FileSystem.DisabledFileLocking.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.DisabledFileLocking.Tests.deps.json xunit.console.dll System.IO.FileSystem.DisabledFileLocking.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait 
```

Doest it mean we have a bug somewhere?

**Comment by stephentoub** [comment]
What assert triggered?

**Comment by adamsitnik** [comment]
> What assert triggered?

To be honest I don't know. The log points to a line of code that has no assert at all:

Stack trace:

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs#L419

https://github.com/dotnet/runtime/blob/d1b866eb2f6f5cb27ca8cc7b5e835a97e4148cea/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs#L638

https://github.com/dotnet/runtime/blob/d1b866eb2f6f5cb27ca8cc7b5e835a97e4148cea/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs#L233

https://github.com/dotnet/runtime/blob/d1b866eb2f6f5cb27ca8cc7b5e835a97e4148cea/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs#L62

https://github.com/dotnet/runtime/blob/d1b866eb2f6f5cb27ca8cc7b5e835a97e4148cea/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs#L250

https://github.com/dotnet/runtime/blob/d1b866eb2f6f5cb27ca8cc7b5e835a97e4148cea/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs#L60

The most suspicious is last line of the method which has `[AsyncMethodBuilder(typeof(PoolingAsyncValueTaskMethodBuilder<>))]` applied:

https://github.com/dotnet/runtime/blob/d1b866eb2f6f5cb27ca8cc7b5e835a97e4148cea/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/BufferedFileStreamStrategy.cs#L492

@stephentoub does it mean that the assert comes from the code generated by the compiler? (I am guessing)

**Comment by zlatanov** [comment]
I want to ask something about the this code fragment: 

https://github.com/dotnet/runtime/blob/38477909eeb6296664cc184d461035b1774ea2df/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/PoolingAsyncValueTaskMethodBuilderT.cs#L356-L367

What happens if the running thread is suspended right after executing line 360
```c#
 int i = (int)((uint)Thread.GetCurrentProcessorId() % (uint)Environment.ProcessorCount);
```
and then resumed on another processor? Wouldn't that make the value that `i` holds incorrect here

```c#
Debug.Assert(s_perCoreCache[i].Object is null || s_perCoreCache[i].Object is StateMachineBox<TStateMachine>);
return ref Unsafe.As<object?, StateMachineBox<TStateMachine>?>(ref s_perCoreCache[i].Object);
```

and could that cause issue if another thread went through the same code path on the same processor, while this thread was suspended?

**Comment by stephentoub** [comment]
It's possible the assert could erroneously fire if between the two expressions in the assert the value went from non-null to null. I can fix that, but this doesn't correspond to the flagged stack trace.

**Comment by zlatanov** [comment]
@stephentoub I think it might, because `PerCoreCacheSlot` is marked with `[MethodImpl(MethodImplOptions.AggressiveInlining)]` which is called from `ReturnToCache` method which also is being aggressively inlined, which in turn is called from `void IValueTaskSource.GetResult(short token)`.

**Comment by stephentoub** [comment]
Hmm.  Maybe?  That would mean the line number is wrong.

**Comment by zlatanov** [comment]
If you run the following code with `dotnet run`

```c#
using System.Diagnostics;
using System.Runtime.CompilerServices;

class Program
{
    static void Main()
    {
        try
        {
            Run();
        }
        finally
        {
            Throw();
        }
    }

    private static void Run()
    {
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Throw() => Debug.Assert(false);
}
```
you should see something like
```txt
Process terminated. Assertion failed.
   at Program.Main() in C:\Users\ivan\source\repos\ConsoleApp2\Program.cs:line 7
```

Line 7 is the start of the Main() method and not where the assert occurred. If I change the `Debug.Assert` with a throw statement, then the output is:

```txt
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at Program.Main() in C:\Users\ivan\source\repos\ConsoleApp2\Program.cs:line 14
```

**Comment by stephentoub** [comment]
Yes, but with the corresponding stack trace, it was highlighting the line inside the try, e.g. in your example it would have been line 10.

**Comment by zlatanov** [comment]
I am not sure if this was checked build, where the test are run with optimizations on, but if I add

```xml
<Optimize>true</Optimize>
```

to the csproj, then the output with `Debug.Assert(false)` becomes:

```txt
Process terminated. Assertion failed.
   at Program.Main() in C:\Users\ivan\source\repos\ConsoleApp2\Program.cs:line 10
```

**Comment by stephentoub** [comment]
> I am not sure if this was checked build

It would have to be, given inlining plus asserts.

**Comment by stephentoub** [comment]
> then the output with Debug.Assert(false) becomes
> line 10

Right, which suggests there's an issue with how line numbers are being mapped in such cases.
