### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56515]
Run: [runtime-libraries-coreclr outerloop 20210728.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1263342&view=ms.vss-test-web.build-test-results-tab&runId=37427364&resultId=104472&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed(maxConnections: 3, numRequests: 5, secure: False)

```
**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.


Stack trace
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed(Int32 maxConnections, Int32 numRequests, Boolean secure) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.MaxConnectionsPerServer.cs:line 73
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 959
```

**Comment by karelz** [comment]
Only 1 failure in last 2 months 5/29-7/29 (incl. PRs), closing.
