### ISSUE TITLE
TcpReceiveSendGetsCanceledByDispose timed out

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#56580]
I got this on my home Windows 10 machine. Seems this happened 8 times in the last week, on Windows and macOS: https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+name%3ATcpReceiveSendGetsCanceledByDispose+
```
      <test name="System.Net.Sockets.Tests.SendReceive_MemoryNativeTask.TcpReceiveSendGetsCanceledByDispose(receiveOrSend: False, ipv6Server: False, dualModeClient: True)" type="System.Net.Sockets.Tests.SendReceive_MemoryNativeTask" method="TcpReceiveSendGetsCanceledByDispose" time="13.056121" result="Fail">

System.TimeoutException : The operation has timed out.
at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass21_1.<TcpReceiveSendGetsCanceledByDispose>b__2() in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendReceive\SendReceive.cs:line 1032
   at System.Threading.Tasks.Task`1.InnerInvoke() in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Future.cs:line 513
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ExecutionContext.cs:line 294
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 2363
--- End of stack trace from previous location ---
   at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass21_0.<<TcpReceiveSendGetsCanceledByDispose>b__0>d.MoveNext() in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendReceive\SendReceive.cs:line 1053
--- End of stack trace from previous location ---
   at System.RetryHelper.ExecuteAsync(Func`1 test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 81
   at System.Net.Sockets.Tests.SendReceive`1.TcpReceiveSendGetsCanceledByDispose(Boolean receiveOrSend, Boolean ipv6Server, Boolean dualModeClient) in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SendReceive\SendReceive.cs:line 1015
--- End of stack trace from previous location ---
```
```

**Comment by antonfirsov** [comment]
Vast majority of the failures is noise from #56294 and #56228. I see about 10 actual failures in total, including PR-s. Happens once or twice every two weeks.

**Comment by ViktorHofer** [comment]
Happened again in https://github.com/dotnet/runtime/pull/57833

Configuration: `net6.0-windows-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open`

Console: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57833-merge-c22d475e6a2e444585/System.Net.Sockets.Tests/1/console.8ade567c.log?sv=2019-07-07&se=2021-09-09T16%3A07%3A09Z&sr=c&sp=rl&sig=l2DKYMt5GVG1%2Ba0LpXKlRwO2TNuxAynru%2BS%2FVOmjZCc%3D

```
    System.Net.Sockets.Tests.SendReceive_MemoryNativeTask.TcpReceiveSendGetsCanceledByDispose(receiveOrSend: False, ipv6Server: True, dualModeClient: False) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs(1032,0): at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass21_1.<TcpReceiveSendGetsCanceledByDispose>b__2()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs(513,0): at System.Threading.Tasks.Task`1.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(294,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2363,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs(1053,0): at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass21_0.<<TcpReceiveSendGetsCanceledByDispose>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs(81,0): at System.RetryHelper.ExecuteAsync(Func`1 test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceive.cs(1015,0): at System.Net.Sockets.Tests.SendReceive`1.TcpReceiveSendGetsCanceledByDispose(Boolean receiveOrSend, Boolean ipv6Server, Boolean dualModeClient)
        --- End of stack trace from previous location ---
```

**Comment by wfurt** [comment]
Do we have any recent failures @rzikm?

**Comment by antonfirsov** [comment]
I do not see any recent failures, closing.
