### ISSUE TITLE
[HTTP/3] Test Timeout: Alpn_H3_Success

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56609]
Test: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Alpn_H3_Success

Failures 5/30-7/31 (incl. PRs):

Day | Failures
-- | --
7/27 | 2x PR #56215 -- newly introduced test, merged on 7/29
7/30 | 2x Official run + 17x PR

We need to disable the test.

<details>

Failure -- TimeoutException:
```
System.TimeoutException : The operation has timed out.

   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass15_0.<<Alpn_H3_Success>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 677
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Alpn_H3_Success() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 686
--- End of stack trace from previous location ---
```

Failure -- AggregateException:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (The operation has timed out.)) (One or more errors occurred. (Stream aborted by peer (4294967295).))
---- System.AggregateException : One or more errors occurred. (The operation has timed out.)
-------- System.TimeoutException : The operation has timed out.
---- System.AggregateException : One or more errors occurred. (Stream aborted by peer (4294967295).)
-------- System.Net.Quic.QuicStreamAbortedException : Stream aborted by peer (4294967295).

   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 89
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Alpn_H3_Success() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 686
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass15_0.<<Alpn_H3_Success>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 677
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 72
----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 268
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlyMemory`1 buffer, Boolean endStream, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 251
   at System.Net.Test.Common.Http3LoopbackStream.SendFrameHeaderAsync(Int64 frameType, Int32 payloadLength) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 148
   at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 153
   at System.Net.Test.Common.Http3LoopbackStream.SendHeadersFrameAsync(IEnumerable`1 headers) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 109
   at System.Net.Test.Common.Http3LoopbackStream.SendResponseHeadersAsync(HttpStatusCode statusCode, IEnumerable`1 headers) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 252
   at System.Net.Test.Common.Http3LoopbackStream.SendResponseAsync(HttpStatusCode statusCode, IList`1 headers, String content, Boolean isFinal) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 233
   at System.Net.Test.Common.Http3LoopbackStream.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 53
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass15_0.<<Alpn_H3_Success>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 660
```
</details>

**Comment by karelz** [comment]
Test disabled in PR #56610 on 7/30
