### ISSUE TITLE
Test failure: Read_DataStoredAtDesiredOffset - CONNECTION_REFUSED

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56613]
Test: System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.Read_DataStoredAtDesiredOffset

Failures 5/30-7/30 (incl. PRs):

Day | Failure
-- | --
7/19 | PR #54640
7/23 | PR #56218
7/29 | PR #56471

Failure:
```
System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED

   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 252
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 645
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass6_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 82
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 567
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 69
   at System.IO.Tests.ConnectedStreamConformanceTests.Read_DataStoredAtDesiredOffset(ReadWriteMode mode) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1880
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Triage: This may be caused by QuicListener refusing connections under load due to msquic protection.
If it went away after our parallelization, we should just close it.
Next step: Confirm the test didn't fail recently.

**Comment by rzikm** [comment]
No recent hits in the test DB for this test. Closing now. General problem of connection being refused is tackled in #55979
