### ISSUE TITLE
[libraries] CoreCLR Windows x86 Microsoft.Extensions.FileProviders.Physical.Tests FileNotFoundException

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#56643]
```
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\h\w\A55B08F1\t\nf1hpxkl.qvb\uw23btx3.aw4'.
File name: 'C:\h\w\A55B08F1\t\nf1hpxkl.qvb\uw23btx3.aw4'
   at System.IO.FileSystem.GetFindData(String fullPath, Boolean isDirectory, WIN32_FIND_DATA& findData) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 214
   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 533
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 428
   at System.IO.FileSystemInfo.ResolveLinkTarget(Boolean returnFinalTarget) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystemInfo.cs:line 170
   at Microsoft.Extensions.FileProviders.Physical.FileSystemInfoHelper.GetFileLinkTargetLastWriteTimeUtc(FileInfo fileInfo) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Internal/FileSystemInfoHelper.cs:line 54
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 57
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 101
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 455
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 693
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 672
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 327
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id) in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Timer.CoreCLR.cs:line 59
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1268612&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56583-merge-6bcb853222e6486085/Microsoft.Extensions.FileProviders.Physical.Tests/console.59a2c30d.log?sv=2019-07-07&se=2021-08-19T16%3A20%3A08Z&sr=c&sp=rl&sig=fxnMmJrGTiPmf8Cc4vJ7GXCiefdJwx34Js7FXZA1ZqY%3D

**Comment by jeffschwMSFT** [comment]
@antonfirsov do you have a suggestion on what area path this would go into?

**Comment by adamsitnik** [comment]
No matter if it's `System.IO` or `Extensions-FileSystem` the owners are the same ;)
