### ISSUE TITLE
Test failure:SampleSynthesisTests.SynthesizeRecognizeTests.SpeechSynthesizerToSpeechRecognitionEngine

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56707]
Run: [runtime-coreclr libraries-jitstressregs 20210801.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1270561&view=ms.vss-test-web.build-test-results-tab&runId=37592848&paneView=debug&resultId=167393)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstressregs4-Windows.10.Arm64v8.Open

- SampleSynthesisTests.SynthesizeRecognizeTests.SpeechSynthesizerToSpeechRecognitionEngine

```
**Error message:**
```
System.OutOfMemoryException : Insufficient memory to continue the execution of the program.


Stack trace
   at System.Speech.Internal.SapiInterop.ISpRecognizer.CreateRecoContext(ISpRecoContext& ppNewCtxt)
   at System.Speech.Internal.SapiInterop.SapiRecognizer.<>c__DisplayClass9_0.<CreateRecoContext>b__0() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134
   at System.Speech.Internal.SapiInterop.SapiRecognizer.CreateRecoContext() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134
   at System.Speech.Recognition.RecognizerBase.Initialize(SapiRecognizer recognizer, Boolean inproc) in /_/src/libraries/System.Speech/src/Recognition/RecognizerBase.cs:line 442
   at System.Speech.Recognition.SpeechRecognitionEngine.get_RecoBase() in /_/src/libraries/System.Speech/src/Recognition/SpeechRecognitionEngine.cs:line 660
   at SampleSynthesisTests.SynthesizeRecognizeTests.SpeechSynthesizerToSpeechRecognitionEngine() in /_/src/libraries/System.Speech/tests/SynthesizeRecognizeTests.cs:line 48
```

**Comment by kunalspathak** [comment]
This seems to be machine specific issue. If we don't see it in other runs, I will go ahead and close it.

**Comment by kunalspathak** [comment]
The test didn't fail in latest run so seems to be intermittent. Closing.
