### ISSUE TITLE
Test failure:System.IO.Tests.FileStream_BeginEndRead_AsyncReads.IncompleteReadCantSetPositionBeyondEndOfFile(fileShare: None, options: None)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56815]
Run: [runtime 20210803.116](https://dev.azure.com/dnceng/public/_build/results?buildId=1274305&view=ms.vss-test-web.build-test-results-tab&runId=37688594&paneView=debug&resultId=139336)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

- System.IO.Tests.FileStream_BeginEndRead_AsyncReads.IncompleteReadCantSetPositionBeyondEndOfFile(fileShare: None, options: None)

```
**Error message:**
```
Showing first 10 differences
Position 5880: Expected: 32, Actual: 255
Position 9976: Expected: 63, Actual: 255
Total number of differences: 2 out of 10000


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 491
   at System.IO.Tests.FileStream_AsyncReads.IncompleteReadCantSetPositionBeyondEndOfFile(FileShare fileShare, FileOptions options) in /_/src/libraries/System.IO.FileSystem/tests/FileStream/ReadAsync.cs:line 122
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment]
> Showing first 10 differences
Position 5880: Expected: 32, Actual: 255
Position 9976: Expected: 63, Actual: 255
Total number of differences: 2 out of 10000

This is very strange and I suspect a hardware issue as I can't see another explanation for why two out of ten thousand bytes would have invalid values. The machine name was `DDARM64S-013`, which belongs to `windows.10.arm64.open` queue. Let's wait until it happens again.

**Comment by hoyosjs** [comment]
![image](https://user-images.githubusercontent.com/19413848/128596514-04b6a09c-71ad-498a-aa2c-2c2869d886fd.png)

@adamsitnik it's happened 19 times in rolling CI's over 30 days. Always ARM64 (save for 1 amd failure) but not machine specific for sure.

**Comment by VincentBu** [comment]
Failed again in [runtime 20210811.67](https://dev.azure.com/dnceng/public/_build/results?buildId=1288495&view=ms.vss-test-web.build-test-results-tab&runId=38035612&resultId=140241&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

- System.IO.Tests.FileStream_BeginEndRead_AsyncReads.IncompleteReadCantSetPositionBeyondEndOfFile(fileShare: ReadWrite, options: None)

```
**Error message:**
```
Showing first 10 differences
Position 2416: Expected: 56, Actual: 255
Total number of differences: 1 out of 10000


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.AssertExtensions.SequenceEqual[T](Span`1 expected, Span`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 491
   at System.IO.Tests.FileStream_AsyncReads.IncompleteReadCantSetPositionBeyondEndOfFile(FileShare fileShare, FileOptions options) in /_/src/libraries/System.IO.FileSystem/tests/FileStream/ReadAsync.cs:line 128
--- End of stack trace from previous location ---
```
