### ISSUE TITLE
Test failure:System.Net.NameResolution.Tests.TelemetryTest.EventSource_ResolveValidHostName_LogsStartStop

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56816]
Run: [runtime-libraries-coreclr outerloop 20210803.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1272892&view=ms.vss-test-web.build-test-results-tab&runId=37645518&resultId=102262&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

- System.Net.NameResolution.Tests.TelemetryTest.EventSource_ResolveValidHostName_LogsStartStop

```
**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 220
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 192
--- End of stack trace from previous location ---
   at System.Net.Dns.<GetAddrInfoWithTelemetryAsync>g__CompleteAsync|34_0[T](Task task, String hostName, ValueStopwatch stopwatch) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 627
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveValidHostName_LogsStartStop>b__1_2>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 45
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 118
   at System.Net.NameResolution.Tests.TelemetryTest.<>c.<<EventSource_ResolveValidHostName_LogsStartStop>b__1_0>d.MoveNext() in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs:line 43
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.NameResolution.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_ResolveValidHostName_LogsStartStop>b__1_0()

```

**Comment by MihaZupan** [comment]
DNS failed to resolve `microsoft.com`.

Only one failure in Kusto history, closing.

**Comment by wfurt** [comment]
For the tests, we can try to do one run without tracing and skip the EvenSource part if that fails. 
DNS failures are annoying.
