### ISSUE TITLE
[Mono][WASM][Interp] System.Security.Cryptography.Algorithms is not supported on WASM

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#56814]
Failed tests:

- JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot/mandelbrot-2/mandelbrot-2.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55529-merge-69a4140388e04190bf/JIT/console.fdd237c6.log?sv=2019-07-07&se=2021-08-08T16%3A03%3A15Z&sr=c&sp=rl&sig=qihStr2Wlfrg2EEIKTwHEsYzifrrJunwPP9ltdRSUZw%3D)

Failure log:
```
      console.error: Unhandled Exception:
      console.error: System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
      console.error:    at System.Security.Cryptography.MD5.Create() in System.Security.Cryptography.Algorithms.dll:token 0x600026a+0x5
      console.error:    at BenchmarksGame.Mandelbrot_2.MatchesChecksum(Byte[] bytes, String checksum) in mandelbrot-2.dll:token 0x6000003+0x0
      console.error:    at BenchmarksGame.Mandelbrot_2.Main(String[] args) in mandelbrot-2.dll:token 0x6000001+0x30
      console.error: Error: System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
         at System.Security.Cryptography.MD5.Create() in System.Security.Cryptography.Algorithms.dll:token 0x600026a+0x5
         at BenchmarksGame.Mandelbrot_2.MatchesChecksum(Byte[] bytes, String checksum) in mandelbrot-2.dll:token 0x6000003+0x0
         at BenchmarksGame.Mandelbrot_2.Main(String[] args) in mandelbrot-2.dll:token 0x6000001+0x30
      console.error: Error: System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
         at System.Security.Cryptography.MD5.Create() in System.Security.Cryptography.Algorithms.dll:token 0x600026a+0x5
         at BenchmarksGame.Mandelbrot_2.MatchesChecksum(Byte[] bytes, String checksum) in mandelbrot-2.dll:token 0x6000003+0x0
         at BenchmarksGame.Mandelbrot_2.Main(String[] args) in mandelbrot-2.dll:token 0x6000001+0x30
          at Object._convert_exception_for_method_call (dotnet.js:1:175308)
          at Object._handle_exception_for_call (dotnet.js:1:177277)
          at Object._handle_exception_and_produce_result_for_call (dotnet.js:1:177598)
          at Object._call_method_with_converted_args (dotnet.js:1:178672)
          at Object.call_method (dotnet.js:1:177067)
          at dotnet.js:1:184806
          at Object.call_assembly_entry_point (dotnet.js:1:185039)
          at Object.init (runtime.js:356:24)
          at Object.Module.config.loaded_cb (runtime.js:243:8)
          at Object._finalize_startup (dotnet.js:1:136358)
```

**Comment by lewing** [comment]
MD5 is unlikely to ever be supported on wasm

**Comment by fanyang-mono** [comment]
@lewing I just changed the milestone of this issue to Future. If this issue will be unlikely actionable, feel free to close it.

**Comment by radical** [comment]
> MD5 is unlikely to ever be supported on wasm

Should this issue be closed? With `main`, I get:
```
[20:32:02] info: host[0] Unhandled Exception:
[20:32:02] info: host[0] System.Security.Cryptography.CryptographicException: 'MD5' is not a known hash algorithm.
[20:32:02] info: host[0]    at System.Security.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
[20:32:02] info: host[0]    at System.Security.Cryptography.MD5.Implementation..ctor()
[20:32:02] info: host[0]    at System.Security.Cryptography.MD5.Create()
[20:32:02] info: host[0]    at BenchmarksGame.Mandelbrot_2.MatchesChecksum(Byte[] bytes, String checksum) in /tmp/c0/Program.cs:line 44
[20:32:02] info: host[0]    at BenchmarksGame.Mandelbrot_2.Main(String[] args) in /tmp/c0/Program.cs:line 35
[20:32:02] info: host[0] Error: System.Security.Cryptography.CryptographicException: 'MD5' is not a known hash algorithm.
[20:32:02] info: host[0]    at System.Security.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
[20:32:02] info: host[0]    at System.Security.Cryptography.MD5.Implementation..ctor()
[20:32:02] info: host[0]    at System.Security.Cryptography.MD5.Create()
[20:32:02] info: host[0]    at BenchmarksGame.Mandelbrot_2.MatchesChecksum(Byte[] bytes, String checksum) in /tmp/c0/Program.cs:line 44
[20:32:02] info: host[0]    at BenchmarksGame.Mandelbrot_2.Main(String[] args) in /tmp/c0/Program.cs:line 35
[20:32:02] info: host[0]     at _convert_exception_for_method_call (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:56052)
[20:32:02] info: host[0]     at _handle_exception_for_call (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:56812)
[20:32:02] info: host[0]     at _handle_exception_and_produce_result_for_call (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:56982)
[20:32:02] info: host[0]     at _call_method_with_converted_args (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:57586)
[20:32:02] info: host[0]     at call_method_ref (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:56704)
[20:32:02] info: host[0]     at /tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:58587
[20:32:02] info: host[0]     at mono_call_assembly_entry_point (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:58719)
[20:32:02] info: host[0]     at mono_run_main (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:68188)
[20:32:02] info: host[0]     at Object.mono_run_main_and_exit (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/dotnet.js:3:67867)
[20:32:02] info: host[0]     at Object.App.init (/tmp/c0/bin/Debug/net7.0/browser-wasm/AppBundle/main.cjs:4:20)
[20:32:02] info: host[0] exiting due to exception: Error: System.Security.Cryptography.CryptographicException: 'MD5' is not a known hash algorithm.
[20:32:02] info: host[0]    at System.Security.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
[20:32:02] info: host[0]    at System.Security.Cryptography.MD5.Implementation..ctor()
[20:32:02] info: host[0]    at System.Security.Cryptography.MD5.Create()
[20:32:02] info: host[0]    at BenchmarksGame.Mandelbrot_2.MatchesChecksum(Byte[] bytes, String checksum) in /tmp/c0/Program.cs:line 44
[20:32:02] info: host[0]    at BenchmarksGame.Mandelbrot_2.Main(String[] args) in /tmp/c0/Program.cs:line 35
```

**Comment by lewing** [comment]
I don't think we ever plan on supporting MD5,  can we just change the benchmark game test?

**Comment by lewing** [comment]
we should either close it or cut and paste a managed MD5 implementation there for wasm ;)

**Comment by trylek** [comment]
Reopening as there exist test exclusions in the issues.targets file tagged with this issue and the tests continue failing after removal of the exclusions in @eduardo-vp's PR #75363. We need to decide what to do here, ideally issues.targets should only be used for temporary test blocking until a particular bug is fixed; if we come to the conclusion that a certain test is not designed to work in a given configuration, we should express it in the test project using the <code>CLRTestTargetUnsupported</code> property. In other words, I'm envisioning a day in the future when issues.targets is just an empty file.
