### ISSUE TITLE
Json serialize error when pass key word 'in' in construct

### ISSUE THREAD

**Issue by bkren** [dotnet/runtime#56822]
### Description

When running the code below, runtime report 

```
Unhandled exception. System.ArgumentException: The type 'Test.Program+S1&' may not be used as a type argument.
   at System.RuntimeType.ThrowIfTypeNeverValidGenericArgument(RuntimeType type)
   at System.RuntimeType.SanityCheckGenericArguments(RuntimeType[] genericArguments, RuntimeType[] genericParamters)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
   at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
   at System.Text.Json.WriteStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Test.Program.C1.toJson() in D:\Codes\ChangeIdx\ChangeIdx\Program.cs:line 29
   at Test.Program.Main(String[] args) in D:\Codes\ChangeIdx\ChangeIdx\Program.cs:line 36
```

But when I remove the key word "in" from line `public C1(in S1 v)` the error disappear.

Code:

```
using System;
using System.Text.Json;

namespace Test
{
    class Program
    {
        readonly struct S1
        {
            public S1(int vv)
            {
                this.vv = vv;
            }

            public readonly int vv;
        }

        class C1
        {
            public C1(in S1 v)
            {
                this.vv = v.vv;
            }

            public int vv { get; init; }

            public string toJson()
            {
                return JsonSerializer.Serialize(this);
            }
        }       

        static void Main(string[] args)
        {
            S1 v = new S1(32);
            new C1(v).toJson();
        }
    }
}
```

### Other information

runtime: .Net 5.0.8
OS: windows 10, Ubuntu 20.04

**Comment by bkren** [comment]
I look into the source deeply, the error is caused by making the deserializer converter. I will close the issue
