### ISSUE TITLE
[wasm][eat] `Microsoft.Extensions.DependencyInjection.Tests` test failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56844]
[Microsoft.Extensions.DependencyInjection.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-7a4dd01ba7eb45b883/Microsoft.Extensions.DependencyInjection.Tests/1/console.86662e2c.log?sv=2019-07-07&se=2021-08-24T06%3A48%3A53Z&sr=c&sp=rl&sig=IhTugai%2BC8NrqjQD9I2jBBfVtHJGbKMeEI0anAMGtes%3D)

```
[07:26:48] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceResolvedEvent
[07:26:48] info: Assert.Equal() Failure
[07:26:48] info: Expected: 3
[07:26:48] info: Actual:   0
[07:26:48] info:    at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceResolvedEvent()
[07:26:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:48] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceRealizationFailedEvent
[07:26:48] info: System.InvalidOperationException : Sequence contains no matching element
[07:26:48] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[07:26:48] info:    at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
[07:26:48] info:    at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceRealizationFailedEvent()
[07:26:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:48] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsExpressionTreeBuiltEvent
[07:26:48] info: System.InvalidOperationException : Sequence contains no matching element
[07:26:48] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[07:26:48] info:    at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
[07:26:48] info:    at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsExpressionTreeBuiltEvent()
[07:26:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:48] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.ExistsWithCorrectId
[07:26:48] info: Assert.Equal() Failure
[07:26:48] info:           â†“ (pos 0)
[07:26:48] info: Expected: Microsoft-Extensions-DependencyInjection
[07:26:48] info: Actual:   DependencyInjectionEventSource
[07:26:48] info:           â†‘ (pos 0)
[07:26:48] info:    at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.ExistsWithCorrectId()
[07:26:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:48] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsCallSiteBuiltEvent
[07:26:48] info: System.InvalidOperationException : Sequence contains no matching element
[07:26:48] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[07:26:48] info:    at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
[07:26:48] info:    at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsCallSiteBuiltEvent()
[07:26:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:48] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsDynamicMethodBuiltEvent
[07:26:48] info: System.InvalidOperationException : Sequence contains no matching element
[07:26:48] info:    at System.Linq.ThrowHelper.ThrowNoMatchException()
[07:26:48] info:    at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
[07:26:48] info:    at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsDynamicMethodBuiltEvent()
[07:26:48] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
```

Test built with `/p:EnableAggressiveTrimming=true`

**Comment by ilonatommy** [comment]
There are some new failures when `DependencyInjection.Tests` enabled:
```
[FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceProviderBuilt
       System.InvalidOperationException : Sequence contains no matching element
       at System.Linq.ThrowHelper.ThrowNoMatchException()
       at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceProviderBuilt()
       at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceProviderBuiltOnAttach
       System.InvalidOperationException : Sequence contains no matching element
       at System.Linq.ThrowHelper.ThrowNoMatchException()
       at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsServiceProviderBuiltOnAttach()
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsScopeDisposedEvent
        System.InvalidOperationException : Sequence contains no matching element
        at System.Linq.ThrowHelper.ThrowNoMatchException()
        at System.Linq.Enumerable.Single[EventWrittenEventArgs](IEnumerable`1 source, Func`2 predicate)
        at Microsoft.Extensions.DependencyInjection.Tests.DependencyInjectionEventSourceTests.EmitsScopeDisposedEvent()
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_Throws_IfClosedTypeDoesNotSatisfyNewGenericConstraint
        System.ArgumentException : Generic implementation type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithNewConstraint`1' has a DefaultConstructorConstraint ('new()' constraint), but the generic service type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService`1' doesn't.
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type , Type[] , Type , Type[] )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.GetCallSiteFactory(ServiceDescriptor[] descriptors)
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_Throws_IfClosedTypeDoesNotSatisfyNewGenericConstraint()
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_ReturnsService_IfClosedTypeSatisfiesNewGenericConstraint
        System.ArgumentException : Generic implementation type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithNewConstraint`1' has a DefaultConstructorConstraint ('new()' constraint), but the generic service type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService`1' doesn't.
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type , Type[] , Type , Type[] )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.GetCallSiteFactory(ServiceDescriptor[] descriptors)
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_ReturnsService_IfClosedTypeSatisfiesNewGenericConstraint()
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_ReturnsMatchingTypesThatMatchCorrectConstraints(closedServiceType: typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService<int[]>), value: [1, 2, 3], matchingImplementationTypes: [typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.FakeOpenGenericService<int[]>), typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithClassConstraint<int[]>), typeof(Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithInterfaceConstraint<int[]>)])
        System.ArgumentException : Generic implementation type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithStructConstraint`1' has a DefaultConstructorConstraint ('new()' constraint), but the generic service type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService`1' doesn't.
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type , Type[] , Type , Type[] )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.GetCallSiteFactory(ServiceDescriptor[] descriptors)
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_ReturnsMatchingTypesThatMatchCorrectConstraints(Type closedServiceType, Object value, Type[] matchingImplementationTypes)
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_ReturnsService_IfClosedTypeSatisfiesStructGenericConstraint
        System.ArgumentException : Generic implementation type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithStructConstraint`1' has a DefaultConstructorConstraint ('new()' constraint), but the generic service type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService`1' doesn't.
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type , Type[] , Type , Type[] )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.GetCallSiteFactory(ServiceDescriptor[] descriptors)
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_ReturnsService_IfClosedTypeSatisfiesStructGenericConstraint()
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_Throws_IfClosedTypeDoesNotSatisfyStructGenericConstraint
        System.ArgumentException : Generic implementation type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithStructConstraint`1' has a DefaultConstructorConstraint ('new()' constraint), but the generic service type 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService`1' doesn't.
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(Type , Type[] , Type , Type[] )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 )
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.GetCallSiteFactory(ServiceDescriptor[] descriptors)
        at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactoryTest.CreateCallSite_Throws_IfClosedTypeDoesNotSatisfyStructGenericConstraint()
        at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
```
