### ISSUE TITLE
[wasm][eat] `System.Composition.Tests` test failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56845]
[System.Composition.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-7a4dd01ba7eb45b883/System.Composition.Tests/1/console.33cbae68.log?sv=2019-07-07&se=2021-08-24T06%3A48%3A53Z&sr=c&sp=rl&sig=IhTugai%2BC8NrqjQD9I2jBBfVtHJGbKMeEI0anAMGtes%3D)

```
07:26:50] fail: [FAIL] System.Composition.UnitTests.LightContainerTests.VerifyAssemblyWithTwoBaseTypeWithOnlyOneExportedWorks
[07:26:50] info: System.Composition.Hosting.CompositionFailedException : No importing constructor was found on type 'TestLibrary.ClassWithDependecyAndSameBaseType'.
[07:26:50] info:    at System.Composition.TypedParts.Discovery.DiscoveredPart.GetPartActivatorDependencies(DependencyAccessor )+MoveNext()
[07:26:50] info:    at System.Linq.Enumerable.ConcatIterator`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[07:26:50] info:    at System.Linq.Enumerable.WhereEnumerableIterator`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[07:26:50] info:    at System.Collections.Generic.LargeArrayBuilder`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].AddRange(IEnumerable`1 )
[07:26:50] info:    at System.Collections.Generic.EnumerableHelpers.ToArray[CompositionDependency](IEnumerable`1 )
[07:26:50] info:    at System.Linq.Enumerable.ToArray[CompositionDependency](IEnumerable`1 source)
[07:26:50] info:    at System.Composition.TypedParts.Discovery.DiscoveredPart.GetDependencies(DependencyAccessor )
[07:26:50] info:    at System.Composition.TypedParts.Discovery.DiscoveredExport.<>c__DisplayClass11_0.<GetExportDescriptorPromise>b__0()
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorPromise.<>c__DisplayClass6_0.<.ctor>b__0()
[07:26:50] info:    at System.Lazy`1[[System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode )
[07:26:50] info:    at System.Lazy`1[[System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
[07:26:50] info:    at System.Lazy`1[[System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorPromise.get_Dependencies()
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract )
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract , ExportDescriptor& )
[07:26:50] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:50] info:    at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract , Object& )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport[ClassWithDependecyAndSameBaseType](String )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport[ClassWithDependecyAndSameBaseType]()
[07:26:50] info:    at System.Composition.UnitTests.LightContainerTests.VerifyAssemblyWithTwoBaseTypeWithOnlyOneExportedWorks()
[07:26:50] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:50] fail: [FAIL] System.Composition.UnitTests.LightContainerTests.VerifyAssemblyNameCanBeUsedWithContainer
[07:26:50] info: System.Composition.Hosting.CompositionFailedException : No importing constructor was found on type 'TestLibrary.ClassWithDependecy'.
[07:26:50] info:    at System.Composition.TypedParts.Discovery.DiscoveredPart.GetPartActivatorDependencies(DependencyAccessor )+MoveNext()
[07:26:50] info:    at System.Linq.Enumerable.ConcatIterator`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[07:26:50] info:    at System.Linq.Enumerable.WhereEnumerableIterator`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[07:26:50] info:    at System.Collections.Generic.LargeArrayBuilder`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].AddRange(IEnumerable`1 )
[07:26:50] info:    at System.Collections.Generic.EnumerableHelpers.ToArray[CompositionDependency](IEnumerable`1 )
[07:26:50] info:    at System.Linq.Enumerable.ToArray[CompositionDependency](IEnumerable`1 source)
[07:26:50] info:    at System.Composition.TypedParts.Discovery.DiscoveredPart.GetDependencies(DependencyAccessor )
[07:26:50] info:    at System.Composition.TypedParts.Discovery.DiscoveredExport.<>c__DisplayClass11_0.<GetExportDescriptorPromise>b__0()
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorPromise.<>c__DisplayClass6_0.<.ctor>b__0()
[07:26:50] info:    at System.Lazy`1[[System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ViaFactory(LazyThreadSafetyMode )
[07:26:50] info:    at System.Lazy`1[[System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValue()
[07:26:50] info:    at System.Lazy`1[[System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Composition.Hosting.Core.CompositionDependency, System.Composition.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorPromise.get_Dependencies()
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract )
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract , ExportDescriptor& )
[07:26:50] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:50] info:    at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract , Object& )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport[ClassWithDependecy](String )
[07:26:50] info:    at System.Composition.CompositionContext.GetExport[ClassWithDependecy]()
[07:26:50] info:    at System.Composition.UnitTests.LightContainerTests.VerifyAssemblyNameCanBeUsedWithContainer()
[07:26:50] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:50] fail: [FAIL] System.Composition.UnitTests.ImportOrderingTests.CollectionsImportedWithAnOrderingAttributeComeInOrder
[07:26:50] info: System.Composition.Hosting.CompositionFailedException : No export was found for the contract 'IItem[]'
[07:26:50] info:  -> required by import 'OrderedItems' of part 'HasImportedItems'
[07:26:50] info:  -> required by initial request for contract 'HasImportedItems'
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:50] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract , ExportDescriptor& )
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[HasImportedItems](String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[HasImportedItems]()
[07:26:51] info:    at System.Composition.UnitTests.ImportOrderingTests.CollectionsImportedWithAnOrderingAttributeComeInOrder()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.ImportOrderingTests.IfAnItemIsMissingMetadataAnInformativeExceptionIsThrown
[07:26:51] info: Assert.Equal() Failure
[07:26:51] info:           â†“ (pos 0)
[07:26:51] info: Expected: The metadata 'Order' cannot be used for oÂ·Â·Â·
[07:26:51] info: Actual:   No export was found for the contract 'IItÂ·Â·Â·
[07:26:51] info:           â†‘ (pos 0)
[07:26:51] info:    at System.Composition.UnitTests.ImportOrderingTests.IfAnItemIsMissingMetadataAnInformativeExceptionIsThrown()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.SharingTest.CircularBoundarySharingTest
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : The component (unknown) cannot be created outside the Boundary sharing boundary.
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.FindContextWithin(String )
[07:26:51] info:    at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext , CompositionOperation )
[07:26:51] info:    at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext , CompositeActivator )
[07:26:51] info:    at System.Composition.Hosting.Providers.ExportFactory.ExportFactoryExportDescriptorProvider.<>c__DisplayClass2_3`1[[System.Composition.UnitTests.CirB, System.Composition.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].<GetExportFactoryDescriptors>b__4()
[07:26:51] info:    at System.Composition.ExportFactory`1[[System.Composition.UnitTests.CirB, System.Composition.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].CreateExport()
[07:26:51] info:    at System.Composition.UnitTests.CirA.CreateInstance()
[07:26:51] info:    at System.Composition.UnitTests.SharingTest.CircularBoundarySharingTest()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.SharingTest.MultipleBoundarySpecified
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : The component (unknown) cannot be created outside the B1 sharing boundary.
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.FindContextWithin(String )
[07:26:51] info:    at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext , CompositionOperation )
[07:26:51] info:    at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext , CompositeActivator )
[07:26:51] info:    at System.Composition.Hosting.Providers.ExportFactory.ExportFactoryExportDescriptorProvider.<>c__DisplayClass2_3`1[[System.Composition.UnitTests.IProj, System.Composition.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].<GetExportFactoryDescriptors>b__4()
[07:26:51] info:    at System.Composition.ExportFactory`1[[System.Composition.UnitTests.IProj, System.Composition.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].CreateExport()
[07:26:51] info:    at System.Composition.UnitTests.SolA.SetupProject()
[07:26:51] info:    at System.Composition.UnitTests.SharingTest.MultipleBoundarySpecified()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.SharingTest.BoundarySharingTest
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : The component (unknown) cannot be created outside the Boundary sharing boundary.
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.FindContextWithin(String )
[07:26:51] info:    at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext , CompositionOperation )
[07:26:51] info:    at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext , CompositeActivator )
[07:26:51] info:    at System.Composition.Hosting.Providers.ExportFactory.ExportFactoryExportDescriptorProvider.<>c__DisplayClass2_3`1[[System.Composition.UnitTests.B, System.Composition.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].<GetExportFactoryDescriptors>b__4()
[07:26:51] info:    at System.Composition.ExportFactory`1[[System.Composition.UnitTests.B, System.Composition.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].CreateExport()
[07:26:51] info:    at System.Composition.UnitTests.C.CreateInstance()
[07:26:51] info:    at System.Composition.UnitTests.SharingTest.BoundarySharingTest()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.DictionaryImportTests.DictionaryImportsCompatibleWithConventionBuilder
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : No export was found for the contract 'IDictionary<String, IValued>'
[07:26:51] info:  -> required by import 'values' of part 'ConventionConsumer'
[07:26:51] info:  -> required by initial request for contract 'ConventionConsumer'
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract , ExportDescriptor& )
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[ConventionConsumer](String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[ConventionConsumer]()
[07:26:51] info:    at System.Composition.UnitTests.DictionaryImportTests.DictionaryImportsCompatibleWithConventionBuilder()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.DictionaryImportTests.WhenAMetadataKeyIsMissingAnInformativeExceptionIsThrown
[07:26:51] info: Assert.Equal() Failure
[07:26:51] info:           â†“ (pos 0)
[07:26:51] info: Expected: The metadata 'Value' cannot be used as a Â·Â·Â·
[07:26:51] info: Actual:   No export was found for the contract 'IDiÂ·Â·Â·
[07:26:51] info:           â†‘ (pos 0)
[07:26:51] info:    at System.Composition.UnitTests.DictionaryImportTests.WhenAMetadataKeyIsMissingAnInformativeExceptionIsThrown()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.DictionaryImportTests.DictionaryImportsReceiveMetadataFromNestedAdapters
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : No export was found for the contract 'IDictionary<String, Lazy<IValued>>'
[07:26:51] info:  -> required by import 'Values' of part 'LazyConsumer'
[07:26:51] info:  -> required by initial request for contract 'LazyConsumer'
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract , ExportDescriptor& )
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[LazyConsumer](String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[LazyConsumer]()
[07:26:51] info:    at System.Composition.UnitTests.DictionaryImportTests.DictionaryImportsReceiveMetadataFromNestedAdapters()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.DictionaryImportTests.DictionaryImportsKeyedByMetadata
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : No export was found for the contract 'IDictionary<String, IValued>'
[07:26:51] info:  -> required by import 'Values' of part 'Consumer'
[07:26:51] info:  -> required by initial request for contract 'Consumer'
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckDependency(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.CheckTarget(CompositionDependency , HashSet`1 , Stack`1 )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistryUpdate.Execute(CompositionContract )
[07:26:51] info:    at System.Composition.Hosting.Core.ExportDescriptorRegistry.TryGetSingleForExport(CompositionContract , ExportDescriptor& )
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.Hosting.CompositionHost.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[Consumer](String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[Consumer]()
[07:26:51] info:    at System.Composition.UnitTests.DictionaryImportTests.DictionaryImportsKeyedByMetadata()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.DictionaryImportTests.WhenAMetadataValueIsOfTheWrongTypeAnInformativeExceptionIsThrown
[07:26:51] info: Assert.Equal() Failure
[07:26:51] info:           â†“ (pos 0)
[07:26:51] info: Expected: The metadata 'Value' cannot be used as a Â·Â·Â·
[07:26:51] info: Actual:   No export was found for the contract 'IDiÂ·Â·Â·
[07:26:51] info:           â†‘ (pos 0)
[07:26:51] info:    at System.Composition.UnitTests.DictionaryImportTests.WhenAMetadataValueIsOfTheWrongTypeAnInformativeExceptionIsThrown()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.DictionaryImportTests.WhenAMetadataKeyIsDuplicatedAnInformativeExceptionIsThrown
[07:26:51] info: Assert.Equal() Failure
[07:26:51] info:           â†“ (pos 0)
[07:26:51] info: Expected: The metadata 'Value' cannot be used as a Â·Â·Â·
[07:26:51] info: Actual:   No export was found for the contract 'IDiÂ·Â·Â·
[07:26:51] info:           â†‘ (pos 0)
[07:26:51] info:    at System.Composition.UnitTests.DictionaryImportTests.WhenAMetadataKeyIsDuplicatedAnInformativeExceptionIsThrown()
[07:26:51] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[07:26:51] fail: [FAIL] System.Composition.UnitTests.ExportFactoryTests.TheSameSharedInstanceIsReusedWithinItsSharingBoundary
[07:26:51] info: System.Composition.Hosting.CompositionFailedException : The component (unknown) cannot be created outside the DataConsistency sharing boundary.
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.FindContextWithin(String )
[07:26:51] info:    at System.Composition.TypedParts.ActivationFeatures.LifetimeFeature.<>c__DisplayClass1_0.<RewriteActivator>b__0(LifetimeContext , CompositionOperation )
[07:26:51] info:    at System.Composition.Hosting.Core.CompositionOperation.Run(LifetimeContext , CompositeActivator )
[07:26:51] info:    at System.Composition.Hosting.Core.LifetimeContext.TryGetExport(CompositionContract , Object& )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(CompositionContract )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport(Type , String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[SharedPartConsumer](String )
[07:26:51] info:    at System.Composition.CompositionContext.GetExport[SharedPartConsumer]()
[07:26:51] info:    at System.Composition.UnitTests.ExportFactoryTests.TheSameSharedInstanceIsReusedWithinItsSharingBoundary()
[07:26:52] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
```

Test built with `/p:EnableAggressiveTrimming=true`

**Comment by lewing** [comment]
@jeffhandley this is targeting 7 why are you assigning me?

**Comment by jeffhandley** [comment]
Sorry about that @lewing; it was in a query run before it got moved to 7.0.0 and I didn’t notice it had been updated already.
