### ISSUE TITLE
[wasm][eat] `System.Reflection.Emit.Lightweight.Tests` test failure

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56848]
[System.Reflection.Emit.Lightweight.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-7a4dd01ba7eb45b883/System.Reflection.Emit.Lightweight.Tests/1/console.22ba3369.log?sv=2019-07-07&se=2021-08-24T06%3A48%3A53Z&sr=c&sp=rl&sig=IhTugai%2BC8NrqjQD9I2jBBfVtHJGbKMeEI0anAMGtes%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1275375&view=logs&jobId=fddee5b2-3265-5a91-40c1-750d81e69f3f&j=fddee5b2-3265-5a91-40c1-750d81e69f3f&t=b539fe9c-4231-5c9f-4235-451fd41db683)

```
[07:27:29] fail: [FAIL] System.Reflection.Emit.Tests.DynamicMethodctor1.String_Type_TypeArray_Module
[07:27:29] info: System.TypeLoadException : Could not load type System.Nullable`1[[System.Char, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[07:27:29] info:    at System.Reflection.RuntimeCustomAttributeData.ResolveArguments()
[07:27:29] info:    at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
[07:27:29] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo , Type )
```

Tests built with `/p:EnableAggressiveTrimming=true`

**Comment by lewing** [comment]
This is mentioned in https://github.com/dotnet/runtime/issues/51211

**Comment by radical** [comment]
> This is mentioned in #51211

👍
