### ISSUE TITLE
Multiple calls of QuicConnection.CloseAsync lead to Debug.Assert

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#56851]
I bump to this while looking at #56115
On failure, Kestrel calls
```
ShutdownAsync: called on [conn][0x7FEA58000B60] with NONE and 256
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ShutdownAsync(QUIC_CONNECTION_SHUTDOWN_FLAGS Flags, Int64 ErrorCode) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 659
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 850
   at System.Net.Quic.QuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 106
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.Abort(ConnectionAbortedException abortReason) in /home/furt/github/aspnetcore/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 73
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.Abort() in /home/furt/github/aspnetcore/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 67
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Connection.StopProcessingNextRequest(Boolean serverInitiated) in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs:line 112
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Connection.StopProcessingNextRequest() in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs:line 87
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.StopProcessingNextRequest() in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/HttpConnection.cs:line 145
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.<>c__12`1.<ProcessRequestsAsync>b__12_1(Object state) in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/HttpConnection.cs:line 104
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 885
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 1127
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 183
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback() in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 1123
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 711
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 625
   at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 250
   at System.Threading.CancellationTokenSource.Cancel() in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 221
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.RequestClose() in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelConnection.cs:line 158
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportConnectionManager.CloseAllConnectionsAsync(CancellationToken token) in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportConnectionManager.cs:line 67
```
[conn][0x7FEA58000B60] Connection received event SHUTDOWN_COMPLETE 8/4/2021 10:54:09 AM

that will close the connection. And than again 
```
ShutdownAsync: called on [conn][0x7FEA58000B60] with NONE and 256
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ShutdownAsync(QUIC_CONNECTION_SHUTDOWN_FLAGS Flags, Int64 ErrorCode) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 659
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 850
   at System.Net.Quic.QuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 106
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.Abort(ConnectionAbortedException abortReason) in /home/furt/github/aspnetcore/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 73
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportConnectionManager.AbortAllConnectionsAsync() in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportConnectionManager.cs:line 84
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportConnectionManager.AbortAllConnectionsAsync() in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x60006e1+0x1f
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.<>c__DisplayClass14_0.<<StopTransportsAsync>g__StopTransportConnection|0>d.MoveNext() in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 114
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /home/furt/github/wfurt-runtime/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.<>c__DisplayClass14_0.<StopTransportsAsync>g__StopTransportConnection|0(ActiveTransport transport) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x60010b8+0x26
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.StopTransportsAsync(List`1 transportsToStop, CancellationToken cancellationToken) in /home/furt/github/aspnetcore/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 123
```

This may be wrong pattern but I feel we should eater act in some more predictable way: either ignore the second call and throw `InvalidOperationException`. It either case it would be nice to add some tests for this.

cc: @JamesNK

**Comment by geoffkizer** [comment]
Yeah, seems like we should ignore a call to CloseAsync if we are already closed. 

These are not concurrent calls, are they? We should probably handle that too. Would Kestrel ever call CloseAsync from multiple threads at the same time? Seems like it very well might.

**Comment by wfurt** [comment]
It does not seems to call it in parallel  - at least not in case I'm looking at. I was just surprised to see assert when I run asp tests with debug runtime. So far no other sign of specific badness.

**Comment by geoffkizer** [comment]
Running ASP.NET tests with a debug runtime seems like a very good idea.

**Comment by wfurt** [comment]
I would like to to that also with out stress and debug build of msquic. @nibanks mentioned they find interesting stuff that way. I have basic packages changes in but the whole loop still did not close.

**Comment by ManickaP** [comment]
Triage: we should investigate if there's no serious underlying issue and clean up Kestrel runs. If it's easy we should fix this.

**Comment by rzikm** [comment]
I am not observing any Debug.Assert on duplicate `CloseAsync` calls. But I see an assert can be fired if called concurrently, but otherwise the race is benign.

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs#L596

I think we should remove the assert if we care enough about it. I will try running Kestrel tests to see if it pops up

**Comment by rzikm** [comment]
I have tried running Kestrel tests with debug libraries and haven't seen any weird crashes.

**Comment by jeffhandley** [comment]
I believe this was encountered on #71908 ([log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71908-merge-55ca21e7298c43fe91/System.Net.Quic.Functional.Tests/1/console.e7eb98b1.log?helixlogtype=result)).

```
Console log: 'System.Net.Quic.Functional.Tests' from job 55ca21e7-298c-43fe-9126-7757614c49bd workitem 3e33318e-d810-4cd6-b536-8dd40db45df2 (windows.11.amd64.client.open.rt) executed on machine a0005XJ

C:\h\w\A59408F7\w\A8150971\e>taskkill.exe /f /im corerun.exe 
ERROR: The process "corerun.exe" not found.

C:\h\w\A59408F7\w\A8150971\e>call RunTests.cmd --runtime-path C:\h\w\A59408F7\p 
----- start Mon 07/11/2022 20:22:25.19 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A59408F7\w\A8150971\e\
"C:\h\w\A59408F7\p\dotnet.exe" exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A59408F7\w\A8150971\e>"C:\h\w\A59408F7\p\dotnet.exe" exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 86 of 96 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
Process terminated. Assertion failed.
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ShutdownAsync(QUIC_CONNECTION_SHUTDOWN_FLAGS Flags, Int64 ErrorCode) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 598
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 762
   at System.Net.Quic.QuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 79
   at System.Net.Quic.QuicListener.PendingConnection.StartHandshake(QuicConnection connection, SslClientHelloInfo clientHello, Func`4 connectionOptionsCallback) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.PendingConnection.cs:line 74
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 328
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
----- end Mon 07/11/2022 20:22:53.26 ----- exit code -2146232797 ----------------------------------------------------------
2022-07-11T20:22:53.937Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-07-11T20:22:53.937Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\A59408F7\w\A8150971\e' for test results files
2022-07-11T20:22:53.937Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\A59408F7\w\A8150971\uploads' for test results files
2022-07-11T20:22:53.937Z	WARNING	run.py	__init__(55)	read_results	No results file found in any of the following formats: xunit, junit, trx
2022-07-11T20:22:53.937Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to 'C:\h\w\A59408F7\w\A8150971\e\__test_report.json'
2022-07-11T20:22:53.953Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1414 bytes
read file: C:\h\w\A59408F7\p\debug-dump-template.md
writing output file: C:\h\w\A59408F7\w\A8150971\uploads\how-to-debug-dump.md
done writing debug dump information
```

**Comment by CarnaViire** [comment]
Tracked in #71995
