### ISSUE TITLE
FileStream_WriteAsync_AsyncWrites.WriteAsyncCancelledFile test failed

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#56894]
```

C:\h\w\AF2309CA\w\B67809CD\e>"C:\h\w\AF2309CA\p\dotnet.exe" exec --runtimeconfig System.IO.FileSystem.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Tests.deps.json xunit.console.dll System.IO.FileSystem.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.IO.FileSystem.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Tests (found 3576 of 3982 test cases)
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 2)
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToMillisecondPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.MoveToMillisecondPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async [SKIP]
      Condition(s) not met: "IsNet5CompatFileStreamEnabled"
    System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync [SKIP]
      Condition(s) not met: "IsNet5CompatFileStreamEnabled"
    System.IO.Tests.DirectoryInfo_ToString.ParentToString_Framework [SKIP]
      Condition(s) not met: "IsNetFramework"
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.Directory_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncCancelledFile(bufferSize: 0, isAsync: True) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   189576032
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/tests/FileStream/WriteAsync.cs(128,0): at System.IO.Tests.FileStream_AsyncWrites.WriteAsyncCancelledFile(Int32 bufferSize, Boolean isAsync)
        --- End of stack trace from previous location ---
    System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncCancelledFile(bufferSize: 4096, isAsync: True) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   192495168
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/tests/FileStream/WriteAsync.cs(128,0): at System.IO.Tests.FileStream_AsyncWrites.WriteAsyncCancelledFile(Int32 bufferSize, Boolean isAsync)
        --- End of stack trace from previous location ---
    System.IO.Tests.FileStream_ctor_options_as.WhenFileIsTooLargeTheErrorMessageContainsAllDetails [SKIP]
      Condition(s) not met: "IsFat32"
    System.IO.Tests.FileInfo_Open_options_as.WhenFileIsTooLargeTheErrorMessageContainsAllDetails [SKIP]
      Condition(s) not met: "IsFat32"
    System.IO.Tests.File_Open_str_options_as.WhenFileIsTooLargeTheErrorMessageContainsAllDetails [SKIP]
      Condition(s) not met: "IsFat32"
    System.IO.Tests.File_OpenHandle.WhenFileIsTooLargeTheErrorMessageContainsAllDetails [SKIP]
      Condition(s) not met: "IsFat32"
  Finished:    System.IO.FileSystem.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 7961, Errors: 0, Failed: 2, Skipped: 16, Time: 35.218s
----- end Thu 08/05/2021  7:51:22.22 ----- exit code 1 ----------------------------------------------------------
```

Configuration: `Libraries Test Run release coreclr windows x86 Debug`

Console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56712-merge-c083d1b3869d4a13bc/System.IO.FileSystem.Tests/1/console.7aac5a3d.log?sv=2019-07-07&se=2021-08-25T07%3A40%3A08Z&sr=c&sp=rl&sig=OvyvEWqdM7XTBoPT9NzUEPfA21XoOfUo2%2BjKOeV6MUc%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1277582&view=logs&j=9d8498d2-c5b7-54d8-6df7-a2ce7e14e68c&t=34b459a3-e64e-5ccc-0adc-77ebca2601a8&l=71

**Comment by danmoseley** [comment]
Hit this on net6.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open
```
    System.IO.Tests.FileStream_WriteAsync_AsyncWrites.WriteAsyncCancelledFile(bufferSize: 4096, isAsync: True) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   181866512
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/tests/FileStream/WriteAsync.cs(128,0): at System.IO.Tests.FileStream_AsyncWrites.WriteAsyncCancelledFile(Int32 bufferSize, Boolean isAsync)
        --- End of stack trace from previous location ---
```

**Comment by ViktorHofer** [comment]
Failed again in https://dev.azure.com/dnceng/public/_build/results?buildId=1285173&view=ms.vss-test-web.build-test-results-tab&runId=37939506&paneView=debug&resultId=137121

Configuration: `net6.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open`
