### ISSUE TITLE
Reading configuration settings fails with System.UriFormatException: 'Invalid URI: The hostname could not be parsed.'

### ISSUE THREAD

**Issue by RussKie** [dotnet/runtime#56897]
### Description

Observed while using the new Windows Forms designer to design a migrated app from net461 to net5.0. 
**This doesn't appear to be a problem while running an app, but it is a problem when the code is executed in the Windows Forms designers (which is now run out of proc).**

![image](https://user-images.githubusercontent.com/4403806/126037495-ec7307fe-9546-4505-9176-6ad530192ab1.png)

![image](https://user-images.githubusercontent.com/4403806/126037519-48a4dde9-a942-40d3-9826-d253e3442cad.png)
```
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
at System.Configuration.Internal.ConfigurationManagerInternal.System.Configuration.Internal.IConfigurationManagerInternal.get_ExeProductName()
at System.Configuration.ApplicationSettingsBase.get_Initializer()
at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propertyInfo)
at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
at System.Configuration.ApplicationSettingsBase.get_Properties()
at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
at System.Configuration.SettingsBase.get_Item(String propertyName)
at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
at GitCommands.Properties.Settings.get_IsPortable() in D:\Development\gitextensions2\GitCommands\Properties\Settings.Designer.cs:line 31
```

When I debugged in, for some strange reason `AppDomain.CurrentDomain.BaseDirectory` was returning `\\?\C:\Users\igveliko\AppData\Local\Temp\WinFormsCache\exm5a4ew.gwt\`
![image](https://user-images.githubusercontent.com/4403806/128333418-846ea579-85a3-4386-8e92-36265c9440e7.png)

However when try run the same code locally `AppDomain.CurrentDomain.BaseDirectory` returns path without leading `\\?\`:
![image](https://user-images.githubusercontent.com/4403806/128333761-363c58ba-b5b0-46df-8cc1-0d277cbd800c.png)

In essence this, what I think, is happening:
```cs
string baseDirectory = @"\\?\C:\Users\igveliko\AppData\Local\Temp\WinFormsCache\exm5a4ew.gwt\";
string manifestModuleName = @"DesignToolsServer.dll";
string configBasePath = Path.Combine(baseDirectory, manifestModuleName);
Uri uri = new Uri(configBasePath);
Console.WriteLine(uri.LocalPath);
```

![image](https://user-images.githubusercontent.com/4403806/128280189-a2e33d91-c1d2-4dc7-bead-99f49b1357da.png)

<details>
<summary>Repro steps</summary>

1. `git clone -v --recurse-submodules --depth 1 --no-single-branch --progress "https://github.com/gitextensions/gitextensions.git" "<path>/gitextensions"`
1. `dotnet restore`
2. Open GitExtensions.sln in VS
3. Ignore Wix warning, trust all repos
4. Navigate to `AppSettings.IsPortable()` and remove `IsDesignMode`	
    ```diff
    diff --git a/GitCommands/Settings/AppSettings.cs b/GitCommands/Settings/AppSettings.cs

    -        public static bool IsPortable() => !IsDesignMode && Properties.Settings.Default.IsPortable;
    +        public static bool IsPortable() => Properties.Settings.Default.IsPortable;
    ```
5. Compile
6. Open `FormAbout` in designer
    ![image](https://user-images.githubusercontent.com/4403806/129816051-6f418a80-5fb5-45a3-b151-891181c78be6.png)

</details>

### Configuration

* .NET 5.0.6
* .NET: 6.0.0-rc.1.21401.1

### Regression?

 ¯\\_(ツ)\_/¯ I struggle to tell what is the cause of this strange behaviour

**Comment by RussKie** [comment]
@JeremyKuhne @Shyam-Gupta whilst we're waiting for a proper fix, is there something that we're setting in the designer that's causing this?

**Comment by krwq** [comment]
@RussKie perhaps this help has some answers or workarounds: https://github.com/dotnet/runtime/issues/3095

**Comment by RussKie** [comment]
@krwq thank you, but I don't see any workarounds in that thread.

**Comment by RussKie** [comment]
Added repro steps to the 1st post.

**Comment by Shyam-Gupta** [comment]
While launching server process, WinForms designer [sets process path](https://github.com/dotnet/winforms-designer/blob/67d76f473fb8770488015475450cf6f27ee9ac62/src/Microsoft.DotNet.DesignTools.Client/Host/ServerProcess.cs#L230) in long path format. This is because the server process is launched from a `ShadowCacheFolder` under temp directory and it can potentially run into max path issues. It seems this path is returned as is by `AppDomain.CurrentDomain.BaseDirectory`. On removing long path characters from process path, issue gets fixed.

So I _think_ `AppDomain.CurrentDomain.BaseDirectory` needs to account for long path format. Requesting @JeremyKuhne for his thoughts.

/cc: @merriemcgaw

**Comment by RussKie** [comment]
/cc: @jeffhandley @danmoseley - can this be fixed in .NET 6.0?

**Comment by jeffhandley** [comment]
This is reasonable to target for RC2 given that it's a regression from .NET Framework and blocking a key scenario. We'll need to get the fix into `main` first though, and ideally validate the fix there before porting into the `release/6.0` branch.

The port PR template will need to cover the details of potential risks that this introduces.

**Comment by krwq** [comment]
@Shyam-Gupta @RussKie I’ve just tried to repro the issue and I’m able to when I set ProcessStartInfo.FileName to anything starting with `\\?\` - when I set separately WorkingDirectory to anything starting with \\?\ and then FileName as just a file name that works for me because AppDomain.CurrentDomain.BaseDirectory doesn’t contain `\\?\`.

However when I tried to setup the same thing with the actual long paths I'm not able to run either of them and getting different kinds of errors when starting another process, i.e.:

Setting just FileName with long path starting with `\\?\` gives me:

```
Unhandled exception. System.ComponentModel.Win32Exception (206): The filename or extension is too long.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ConsoleApp40.Program.Main(String[] args) in C:\Users\kwicher\source\repos\ConsoleApp40\x\ConsoleApp40\Program.cs:line 28
```

which means the process is not even executed which wouldn't solve the issue.

If I try to set WorkingDirectory with long path starting with `\\?\` and FileName with just a file name I get:

```
Unhandled exception. System.ComponentModel.Win32Exception (267): The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ConsoleApp40.Program.Main(String[] args) in C:\Users\kwicher\source\repos\ConsoleApp40\x\ConsoleApp40\Program.cs:line 28
```

on top of that trying to run any dotnet exe (hello world app) which is on a long path from a command line ends up with:

```
C:\Users\kwicher\source\repos\ConsoleApp40\looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong\ConsoleApp40\bin\Debug\net5.0>ConsoleApp40.exe
The current directory is invalid.
```

I'm not sure fixing just this issue will help in the long path issue case anyway so I'd suggest just not prepend `\\?\` for now. I'm guessing there will need to be more fixes done to get this fixed for long path.

I've also tried the same on latest 6.0 and the output was same.

**Comment by JeremyKuhne** [comment]
@krwq This stuff _should_ work. Feel free to ping me on teams regarding long path technical details. :)

**Comment by RussKie** [comment]
We've had a chat with @JeremyKuhne, and it won't be correct move to modify the designer start up sequence. The BCL and the .NET runtime must handle long paths correctly, and in general they are. `Uri` appears to be an outlier here.

Here's a document outlining how to enable long paths https://docs.microsoft.com/windows/win32/fileio/maximum-file-path-limitation which you find helpful.

**Comment by krwq** [comment]
I'll sync with @JeremyKuhne  - my registry already shows that long paths are enabled and I added manifest file with longPathAware=true and I'm still getting "The current directory is invalid." when I try to run from the command line - although this looks like it comes from cmd.exe and not my .exe itself

**Comment by krwq** [comment]
After syncing with @JeremyKuhne I believe I was correctly using manifest file and correctly enabled everything. I was able to run the app in cmd.exe from outside of the current directory (so that current directory is relatively short) and then using full path. For System.Diagnostics.Process I don't think it works with long paths, see the issue I've created - I've added potential workaround for long paths as well but it will only work if you don't pass any arguments to the exe:
https://github.com/dotnet/runtime/issues/58492

If you use the workaround then after fixing this issue this scenario can be unblocked (assuming you don't pass any arguments to the app, if you do then last bullet point in #58492 has to be fixed as well)

**Comment by RussKie** [comment]
@krwq  I've used the private binaries and followed the steps you have kindly provided, but either I'm doing something wrong, or the issue isn't quite fixed.

Here's the stack trace I'm now getting (note it is not failing in `System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(String exePath, Boolean isSingleFile)`):
```
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(String exePath, Boolean isSingleFile)
at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
at System.Configuration.ClientConfigPaths.get_Current()
at System.Configuration.Internal.ConfigurationManagerInternal.System.Configuration.Internal.IConfigurationManagerInternal.get_ExeProductName()
at System.Configuration.ApplicationSettingsBase.get_Initializer()
at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propertyInfo)
at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
at System.Configuration.ApplicationSettingsBase.get_Properties()
at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
at System.Configuration.SettingsBase.get_Item(String propertyName)
at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
at WinFormsApp3.Properties.Settings.get_IsPortable() in D:\Development\throwaway\WinFormsApp3\Properties\Settings.Designer.cs:line 31
at WinFormsApp3.AppSettings.IsPortable() in D:\Development\throwaway\WinFormsApp3\Form1.cs:line 115
at WinFormsApp3.AppSettings.<>c.<.cctor>b__1_0() in D:\Development\throwaway\WinFormsApp3\Form1.cs:line 57
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at System.Lazy`1.get_Value()
at WinFormsApp3.AppSettings.get_SettingsFilePath() in D:\Development\throwaway\WinFormsApp3\Form1.cs:line 123
at WinFormsApp3.AppSettings.<.cctor>g__CreateEmptySettingsFileIfMissing|1_2() in D:\Development\throwaway\WinFormsApp3\Form1.cs:line 98
at WinFormsApp3.AppSettings..cctor() in D:\Development\throwaway\WinFormsApp3\Form1.cs:line 80  
```

Here's a repro app (a butchered version of the real app that's exhibiting the issue): [56897.zip](https://github.com/dotnet/runtime/files/7193446/56897.zip)

Repro steps:
1. Launch WinFormsApp3.sln
2. Build
3. Open Form1 in the designer

**Comment by krwq** [comment]
@RussKie let's sync offline - the attached zip doesn't build for me
