### ISSUE TITLE
Failures on ARM64 Windows R2R Crossgen2 outerloop legs

### ISSUE THREAD

**Issue by josalem** [dotnet/runtime#56941]
On some _but not all_ ARM64 Windows outerloop test legs for Crossgen 2 on a recent PR, I was seeing >50% of all tests failing with the following stackoverflow:

```
	  --------------------------------
         at System.SR.GetResourceString(System.String)
         at System.AccessViolationException..ctor()
         at System.SR.InternalGetResourceString(System.String)
      --------------------------------
         at System.SR.GetResourceString(System.String)
         at System.AccessViolationException..ctor()
         at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..cctor()
         at System.SR.InternalGetResourceString(System.String)
         at System.SR.GetResourceString(System.String)
         at System.AccessViolationException..ctor()
         at System.SR..cctor()
         at System.SR.GetResourceString(System.String)
         at System.AccessViolationException..ctor()
         at System.Collections.HashHelpers..cctor()
         at System.Collections.HashHelpers.GetPrime(Int32)
         at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Initialize(Int32)
         at System.Collections.Generic.Dictionary`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Int32, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
         at System.AppContext.Setup(Char**, Char**, Int32)
```

Link to the console log for PayloadGroup0 on one of the legs: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56507-merge-e5626f1b9ca24c9eb8/PayloadGroup0/console.5312eb1e.log?sv=2019-07-07&se=2021-08-19T17%3A53%3A02Z&sr=c&sp=rl&sig=Ocs%2F%2BHs%2FpBRUF3ethO06ztOU78AUAl5CN8ts%2BYd9eRw%3D

Link to the build in AzDO: https://dev.azure.com/dnceng/public/_build/results?buildId=1268719&view=ms.vss-test-web.build-test-results-tab

I couldn't find a pattern in which tests failed and which tests passed. For the PayloadGroup0 I linked above, this was the breakdown:
```
=== TEST EXECUTION SUMMARY ===
   baseservices.compilerservices.XUnitWrapper           Total:  10, Errors: 0, Failed:  10, Skipped: 0, Time:   6.217s
   baseservices.exceptions.XUnitWrapper                 Total: 139, Errors: 0, Failed: 139, Skipped: 0, Time:  26.364s
   baseservices.multidimmarray.XUnitWrapper             Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.638s
   baseservices.TieredCompilation.XUnitWrapper          Total:  14, Errors: 0, Failed:  13, Skipped: 0, Time:   6.821s
   baseservices.typeequivalence.XUnitWrapper            Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.676s
   baseservices.varargs.XUnitWrapper                    Total:   2, Errors: 0, Failed:   2, Skipped: 0, Time:   3.173s
   CoreMangLib.system.XUnitWrapper                      Total:  62, Errors: 0, Failed:  62, Skipped: 0, Time:  10.706s
   Exceptions.ForeignThread.XUnitWrapper                Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.608s
   GC.API.XUnitWrapper                                  Total:  66, Errors: 0, Failed:  64, Skipped: 0, Time:  11.446s
   GC.Coverage.XUnitWrapper                             Total:   3, Errors: 0, Failed:   2, Skipped: 0, Time:   3.042s
   GC.Features.XUnitWrapper                             Total:  39, Errors: 0, Failed:  28, Skipped: 0, Time:   7.005s
   GC.LargeMemory.XUnitWrapper                          Total:   6, Errors: 0, Failed:   6, Skipped: 0, Time:   3.274s
   GC.Regressions.XUnitWrapper                          Total:  10, Errors: 0, Failed:   9, Skipped: 0, Time:   3.162s
   GC.Scenarios.XUnitWrapper                            Total: 477, Errors: 0, Failed:  46, Skipped: 0, Time:  20.908s
   GC.Stress.XUnitWrapper                               Total:   1, Errors: 0, Failed:   0, Skipped: 0, Time:   0.073s
   hosting.stress.XUnitWrapper                          Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.817s
   ilasm.PortablePdb.XUnitWrapper                       Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.864s
   ilasm.System.XUnitWrapper                            Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.788s
   Loader.AssemblyDependencyResolver.XUnitWrapper       Total:   2, Errors: 0, Failed:   2, Skipped: 0, Time:   2.948s
   Loader.AssemblyLoadContext30Extensions.XUnitWrapper  Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.963s
   Loader.binding.XUnitWrapper                          Total:   7, Errors: 0, Failed:   7, Skipped: 0, Time:   3.144s
   Loader.CollectibleAssemblies.XUnitWrapper            Total:   2, Errors: 0, Failed:   2, Skipped: 0, Time:   5.474s
   Loader.ContextualReflection.XUnitWrapper             Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:  17.944s
   Loader.lowlevel.XUnitWrapper                         Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.824s
   Loader.NativeLibs.XUnitWrapper                       Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.846s
   Loader.regressions.XUnitWrapper                      Total:   4, Errors: 0, Failed:   4, Skipped: 0, Time:   3.042s
   managed.Compilation.XUnitWrapper                     Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.873s
   readytorun.coreroot_determinism.XUnitWrapper         Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.776s
   readytorun.crossboundarylayout.XUnitWrapper          Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.673s
   readytorun.crossgen2.XUnitWrapper                    Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.958s
   readytorun.determinism.XUnitWrapper                  Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   7.887s
   readytorun.DynamicMethodGCStress.XUnitWrapper.dll    Total:   0
   readytorun.r2rdump.XUnitWrapper                      Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.691s
   readytorun.tests.XUnitWrapper                        Total:   7, Errors: 0, Failed:   7, Skipped: 0, Time:   3.423s
   reflection.DefaultInterfaceMethods.XUnitWrapper      Total:   3, Errors: 0, Failed:   3, Skipped: 0, Time:   3.009s
   reflection.ldtoken.XUnitWrapper                      Total:   3, Errors: 0, Failed:   3, Skipped: 0, Time:   2.934s
   reflection.Modifiers.XUnitWrapper                    Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.745s
   reflection.RefEmit.XUnitWrapper                      Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   3.947s
   reflection.regression.XUnitWrapper                   Total:   4, Errors: 0, Failed:   4, Skipped: 0, Time:   3.765s
   reflection.SetValue.XUnitWrapper                     Total:   2, Errors: 0, Failed:   2, Skipped: 0, Time:   2.680s
   reflection.StaticInterfaceMembers.XUnitWrapper       Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.716s
   reflection.Tier1Collectible.XUnitWrapper             Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.657s
   Regressions.coreclr.XUnitWrapper                     Total:  57, Errors: 0, Failed:  56, Skipped: 0, Time:  12.527s
   tracing.eventactivityidcontrol.XUnitWrapper          Total:   1, Errors: 0, Failed:   1, Skipped: 0, Time:   2.714s
   tracing.eventcounter.XUnitWrapper                    Total:   8, Errors: 0, Failed:   0, Skipped: 0, Time:   0.223s
   tracing.eventlistener.XUnitWrapper                   Total:   2, Errors: 0, Failed:   2, Skipped: 0, Time:   2.778s
   tracing.eventpipe.XUnitWrapper                       Total:  18, Errors: 0, Failed:   3, Skipped: 0, Time:   3.450s
                                                               ---          -          ---           -        --------
                                                  GRAND TOTAL: 969          0          497           0        231.192s (232.082s)
```

**Comment by trylek** [comment]
@davidwrighton / @AntonLapounov - have you got any idea what could be amiss here? I tried to disassemble SPC from the run quoted by John where all the .cctors mentioned in the call stack reside but I'm afraid I'm not yet sufficiently fluent in ARM64 assembly to recognize a potential codegen bug. What makes it even weirder is the non-deterministic nature of the errors even within a single run - I would expect that, if theoretically SPC gets compiled with a codegen bug making some .cctors throw, all tests would fail.

**Comment by AntonLapounov** [comment]
@josalem Do we have any crash dumps or easy way to reproduce?

**Comment by josalem** [comment]
I didn't attempt to repro these locally. I just glanced through the artifacts in the AzDO link above and I didn't see any dumps.

**Comment by AntonLapounov** [comment]
Could this be some random glitch? According to logs, tests failed in "windows arm Checked" legs, i.e. ARM32, not ARM64. If we do not see this failure in other runs, we should close this.

**Comment by davidwrighton** [comment]
I think we should close this. I've only ever seen this failure when startup is completely broken, and we're not seeing much of this, so possibly a bad build or network or something
