### ISSUE TITLE
Android .NET 6 Exception Messages missing

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#56990]
### Description

In a .NET 6 Android Application (`dotnet new android`), do something that throws an `Exception` by default like:

```csharp
new BinaryFormatter().Serialize(new MemoryStream(), "Hello!");
```

This throws:
```
08-06 11:30:44.944 23353 23353 I MonoDroid: android.runtime.JavaProxyThrowable: System.PlatformNotSupportedException: BinaryFormatter_SerializationDisallowed
08-06 11:30:44.944 23353 23353 I MonoDroid:    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph) in System.Runtime.Serialization.Formatters.dll:token 0x600013d+0x5
08-06 11:30:44.944 23353 23353 I MonoDroid:    at foo.MainActivity.OnCreate(Bundle savedInstanceState) in foo.dll:token 0x6000001+0x13
08-06 11:30:44.944 23353 23353 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in Mono.Android.dll:token 0x60150da+0xf
08-06 11:30:44.944 23353 23353 I MonoDroid:     at crc64808a40cc7e533249.MainActivity.n_onCreate(Native Method)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at crc64808a40cc7e533249.MainActivity.onCreate(MainActivity.java:29)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7136)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7127)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.os.Looper.loop(Looper.java:193)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:6669)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-06 11:30:44.944 23353 23353 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-06 11:30:44.944 23353 23353 I MonoDroid:
08-06 11:30:44.944 23353 23353 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
```

Note that the exception message is `BinaryFormatter_SerializationDisallowed` instead of:

https://github.com/dotnet/runtime/blob/577d079a72dbb1cf48e032c015f202770526ff52/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L3727-L3729

I think it would be fine for `BinaryFormatter_SerializationDisallowed` to be printed in a Release build with trimming enabled. However, I think we want the full exception message for Debug builds?

### Configuration

```
dotnet --version
6.0.100-preview.7.21379.14
```

### Regression?

I think this was always this way in .NET 6. It works in legacy Xamarin.Android that uses mono/mono.

**Comment by filipnavara** [comment]
For reference, this is controlled by the `<UseSystemResourceKeys>` property.

**Comment by jonathanpeppers** [comment]
Is there any precedence for setting `$(UseSystemResourceKeys)` for `Release` builds but not `Debug` builds?

It looks like Apple platforms are doing this as well:

https://github.com/xamarin/xamarin-macios/blob/4371133cf7413aa8f3e8ee79a8817b96ef65d202/dotnet/targets/Xamarin.Shared.Sdk.targets#L133

So no one will get good exception messages while debugging right now on mobile...

**Comment by steveisok** [comment]
@jonathanpeppers good question.  Does it work better if you turn it off?

**Comment by jonathanpeppers** [comment]
Yeah, if I put this in my app's `.csproj`:
```xml
<UseSystemResourceKeys>false</UseSystemResourceKeys>
```

I get:

![image](https://user-images.githubusercontent.com/840039/128877339-2346c5c7-b03f-4e8b-bc71-172e868ccdb0.png)

**Comment by akoeplinger** [comment]
We discussed this and decided the Android and iOS SDKs should set a default value for UseSystemResourceKeys for Debug, moving this issue to the respective repos:
- https://github.com/xamarin/xamarin-android/issues/6185
- https://github.com/xamarin/xamarin-macios/issues/12438
