### ISSUE TITLE
NullReferenceException if QuicListenerOptions.ListenEndPoint is not set

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#57091]
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet(IPEndPoint endpoint)
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateListener(QuicListenerOptions options)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
```

Related to https://github.com/dotnet/aspnetcore/issues/35200
Priority: Low

**Comment by wfurt** [comment]
We have checks in `ConnectAsync`  AFAIK so we should probably apply same rules for Listener.
