### ISSUE TITLE
Failure in RunThreadLocalTest5_Dispose

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#57102]
https://dev.azure.com/dnceng/public/_build/results?buildId=1271572&view=ms.vss-test-web.build-test-results-tab&runId=37617006&resultId=187161&paneView=debug
net6.0-Linux-Debug-x64-Mono_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20210728124700-4f64125

Not much to go on. Suggestion: assert the return value here is true. Then next failure we will know whether it timed out (suggesting possibly it needs to wait more than 60 sec) or something else.

https://github.com/danmoseley/runtimelab/blob/3483068cf9a7adb7a24e9d2b6b21679ae5d2b2ff/src/libraries/System.Threading/tests/ThreadLocalTests.cs#L131-L139
```c#
            SpinWait.SpinUntil(() =>
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                return mres.IsSet;
            }, ThreadTestHelpers.UnexpectedTimeoutMilliseconds);


            Assert.True(mres.IsSet);
```
```

Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest5_Dispose() in /_/src/libraries/System.Threading/tests/ThreadLocalTests.cs:line 139
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

**Comment by danmoseley** [comment]
cc @kouvel

**Comment by kouvel** [comment]
This could have timed out due to https://github.com/dotnet/runtime/issues/55796 depending on the order in which tests ran on the same thread, will see if it fails again after the fix

**Comment by danmoseley** [comment]
@kouvel what do you think of changing all the `SpinWait.SpinUntil(..)` in our tests to assert the return value? Some do already. Of course not those that just do `SpinWait.SpinUntil(false, ...)`

That might make future failures easier to reason about.

**Comment by kouvel** [comment]
In this case it seems clear to me that it would have timed out, as that's the only way the assertion would have failed. I'd prefer using the wait helpers in `ThreadTestHelpers` instead for this sort of stuff, but that's probably newer than these tests.

**Comment by ViktorHofer** [comment]
Failed again in https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58314-merge-0e292e5745a3493ca8/System.Threading.Tests/1/console.393c4276.log?sv=2019-07-07&se=2021-09-19T14%3A59%3A48Z&sr=c&sp=rl&sig=fhlRR2MVDyQ61ZP7Byme1Bfr3ES2bafCwufZRGPOWOE%3D.

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1328371&view=ms.vss-test-web.build-test-results-tab&runId=38984868&resultId=187108&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
  Discovering: System.Threading.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tests (found 206 of 239 test cases)
  Starting:    System.Threading.Tests (parallel test collections = on, max threads = 2)
    System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest8_Values_NegativeCases [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest5_Dispose [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Threading/tests/ThreadLocalTests.cs(139,0): at System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest5_Dispose()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(370,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest7_WeakReference [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
  Finished:    System.Threading.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Tests  Total: 474, Errors: 0, Failed: 1, Skipped: 2, Time: 70.472s
```

**Comment by danmoseley** [comment]
@kouvel another hit: https://github.com/dotnet/runtime/pull/59194

**Comment by VincentBu** [comment]
Failed again in: [runtime 20211008.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1409599&view=ms.vss-test-web.build-test-results-tab&runId=40883062&paneView=debug&resultId=199829)

Failed test:
```
net7.0-Linux-Release-x64-Mono_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673
System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest5_Dispose
```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest5_Dispose() in /_/src/libraries/System.Threading/tests/ThreadLocalTests.cs:line 139
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```
