### ISSUE TITLE
Test failure: SimpleScenario_UseGETVerb_Success

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57123]
Test type: `System.Net.Tests.HttpWebRequestTest_Sync`

Configuration: `net6.0-Linux-Debug-x64-CoreCLR_release-RedHat.7.Amd64.Open`

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1285173&view=ms.vss-test-web.build-test-results-tab&runId=37939164&paneView=debug

```
System.IO.IOException : Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1420
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 478
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 381
   at System.Net.Test.Common.LoopbackServer.Connection.CreateAsync(SocketWrapper socket, Stream stream, Options httpOptions) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 474
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 148
   at System.Net.Test.Common.LoopbackServer.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 1066
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass15_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 117
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 101
   at System.Net.Tests.HttpWebRequestTest.SimpleScenario_UseGETVerb_Success(Boolean useSsl) in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1651
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
So far 3 occurrences of this error message since 23.7.
Doesn't seem to be extremely recent, punting.

```
TestResults
| where Message == "System.IO.IOException : Cannot determine the frame size or a corrupted frame was received."
| join kind=inner Jobs on JobId
| join kind=inner WorkItems on WorkItemId
```

**Comment by rzikm** [comment]
No test failures in last 2 months, closing for now.
