### ISSUE TITLE
Test timeout: SendAsync_CorrectVersionSelected_ExternalServer

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#57135]
Test: System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_CorrectVersionSelected_ExternalServer

Day | Run | OS | Details
-- | -- | -- | --
8/2 | PR #56723 | Alpine.312.Amd64.Open | TimeoutException
8/7 | Official run | Alpine.312.Amd64.Open | Assert on exception type
8/8 | Official run | Ubuntu.1910.Amd64.Open | 3x TimeoutException (possibly duplicates)
8/8 | Official run | Debian.10.Amd64.Open | 2x TimeoutException (possibly duplicates)
8/8 | Official run | Alpine.312.Amd64.Open | 1x TimeoutException + 1x Assert on exception type
8/8 | Official run | Alpine.312.Amd64.Open (not duplicate of above) | 1x TimeoutException + 1x Assert on exception type

Failure - TimeoutException:
```
System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---- System.TimeoutException : A task was canceled.
-------- System.Threading.Tasks.TaskCanceledException : A task was canceled.

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 616
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_CorrectVersionSelected_ExternalServer(Version requestVersion, HttpVersionPolicy versionPolicy, Version serverVersion, Boolean useSsl, Object expectedResult) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 1244
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs:line 23
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 778
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp2Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 954
   at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1004
   at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1017
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1027
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
```

Failure - assert on exception type:
```
Assert.IsType() Failure
Expected: System.Net.Http.HttpRequestException
Actual:   System.Threading.Tasks.TaskCanceledException

   at System.Net.Http.Functional.Tests.HttpClientTest.SendAsync_CorrectVersionSelected_ExternalServer(Version requestVersion, HttpVersionPolicy versionPolicy, Version serverVersion, Boolean useSsl, Object expectedResult) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 1247
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Also looks like recent regression ...

**Comment by ManickaP** [comment]
This an outerloop tests communicating with our external, azure based endpoint. I tried to divine some correlating info about worse availability from the azure portal with no success, so I cannot confirm that it was caused by the servers. However, AFAIK, we haven't done any recent changes on around 7.-8.8. so this really looks like an environmental fluke, punting out of 6.0.

**Comment by karelz** [comment]
Duplicate of #57134
