### ISSUE TITLE
Test fails: ConnectV4IPAddressToV6Host_Fails

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#57132]
Test: System.Net.Sockets.Tests.DualModeConnectToIPAddress.ConnectV4IPAddressToV6Host_Fails

Failures 6/11-8/13 (incl. PRs):

Day | Run | OS | Notes
-- | -- | -- | --
7/23 | PR #56228 | Centos.8.Amd64.Open | Mono
7/23 | PR #56228 | Centos.8.Amd64.Open | CoreCLR
8/6 | PR #56997 | Ubuntu.1804.Amd64.Open | Mono
8/6 | Official run | Fedora.34.Amd64.Open | Mono
8/10 | PR #57144 | Debian.10.Amd64.Open | CoreCLR

Failure:
```
Assert.Throws() Failure
Expected: typeof(System.Net.Sockets.SocketException)
Actual:   (No exception was thrown)

   at System.Net.Sockets.Tests.DualModeConnectToIPAddress.DualModeConnect_IPAddressToHost_Fails_Helper(IPAddress connectTo, IPAddress listenOn) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 154
   at System.Net.Sockets.Tests.DualModeConnectToIPAddress.ConnectV4IPAddressToV6Host_Fails() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 121
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

**Comment by wfurt** [comment]
triage: we should look for recent failures and also possibly check if this could be improved with recent PR

**Comment by antonfirsov** [comment]
No failures in the last 90 days, closing.
