### ISSUE TITLE
HttpClient throws No such host is known error when requesting any Url

### ISSUE THREAD

**Issue by vkbandi** [dotnet/runtime#57191]
### Description

For the code shown below, HttpClient in dotnet core 3.1 throws System.Net.Http.HttpRequestException: 'No such host is known.' exception when requesting any url (including http://localhost, http://127.0.0.1, https://google.com, etc.,). The same code when called from .net framework 4.7.2 application fetches the response without throwing any error.

Code

```c#
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync("https://google.com");
                var responseContent = await response.Content.ReadAsStringAsync();

                Console.WriteLine(responseContent);
            }
        }
    }
}
```

### Expected behaviour
The HttpClient should fetch the response in dotnet core 3.1 aplication

### Configuration

* Which version of .NET is the code running on? - .net core 3.1
* What OS and version, and what distro if applicable? - Windows 10 - 1909
* What is the architecture (x64, x86, ARM, ARM64)? - x64
* Do you know whether it is specific to that configuration? - No

### Regression?

This issue occurs in .net core 3.1 and .net 5, but doesn't occur in .net framework 4.7.2

### Other information

The application is running behind a corporate proxy server, the StackTrace for the exception can be found below

```
System.Net.Http.HttpRequestException
  HResult=0x80004005
  Message=No such host is known.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.ConnectHelper.<ConnectAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<CreateHttp11ConnectionAsync>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<GetHttpConnectionAsync>d__45.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithRetryAsync>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.AuthenticationHelper.<SendWithAuthAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__70.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.Program.<Main>d__0.MoveNext() in C:\Users\TestUser\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 13

Inner Exception 1:
SocketException: No such host is known.

```

**Comment by ManickaP** [comment]
Works perfectly fine with `https://google.com` for me. Are you sure you can reach servers on those addresses? Can you access them via browser / ping them from command line?
This is a very basic scenario so it's highly unlikely that something is wrong with `HttpClient`. This is most probably environmental issue.

**Comment by vkbandi** [comment]
I can access the url's from my browser and also from HttpClient from application targeting .net Framework 4.7.2, it only throws the exception from application targeting .net core 3.1 and .net 5.

I have wsl2 (ubuntu) installed on my machine, but the application is not running on wsl2, I am behind my company proxy server, but these shouldn't matter as the .net framework 4.7.2 application works as expected in the same environment.

**Comment by ManickaP** [comment]
> I am behind my company proxy server,

This absolutely matters! .NET framework and browser will automatically pick up the settings from your internet options whereas .NET Core won't AFAIK. You have to tell it to use it either via [env variables](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-5.0#remarks) or set up a [Proxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=net-5.0) property

**Comment by wfurt** [comment]
That is not 100% correct. The proxy matter but there are different ways to configure it and .NET supports only some. 
There was also issue with auto-configuration and scripts possibly returning more than one site. I would suggest following steps to troubleshoot:
1) set the proxy explicitly as @ManickaP suggested
2) configure proxy manually via system setting

3) if the 2 above work then go back to what ever you have. I would suggest to try 5.0 as I remember some fixes in this area. 
If you cannot make the 3) work we can troubleshoot the proxy setting.

**Comment by vkbandi** [comment]
I'm currently working with my IT support team to check if there is any issue with my proxy configuration. I will update back once I have something
