### ISSUE TITLE
FailFast in System.Threading.Tasks.Tests.ExecutionContextFlowTest

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#57331]
There is a dump uploaded, and the usual markdown instruction file to get the payload and symbols
https://dev.azure.com/dnceng/public/_build/results?buildId=1291092&view=ms.vss-test-web.build-test-results-tab&runId=38106242&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=198734

Console log: 'System.Threading.Tasks.Tests' from job df4bd733-ac6f-43b9-aa20-4db008f69725 workitem 02303039-2752-4888-a303-ac1e36d56fa7 (windows.81.amd64.open.rt) executed on machine a001BRJ

FailFast is here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Threading.Tasks/tests/Task/ExecutionContextFlowTest.cs#L65
```
Process terminated. Look at the created dump
   at System.Environment.FailFast(System.String)
   at System.Threading.Tasks.Tests.ExecutionContextFlowTest+<TaskDropsExecutionContextUponCompletion>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation+<>c.<.cctor>b__8_0(System.Object)
   at Xunit.Sdk.AsyncTestSyncContext+<>c__DisplayClass7_0.<Post>b__0()
   at Xunit.Sdk.XunitWorkerThread+<>c.<QueueUserWorkItem>b__5_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.Thread+StartHelper.RunWorker()
   at System.Threading.Thread+StartHelper.Run()
   at System.Threading.Thread.StartCallback()
----- end Thu 08/12/2021 22:54:39.72 ----- exit code -2146232797 ----------------------------------------------------------
```

@tarekgh @stephentoub seems you have worked on this test. I verified I can open the dump and resolve symbols, but I'm not familiar with this area.

was in https://github.com/dotnet/runtime/pull/57313/checks

**Comment by karelz** [comment]
Hit again in PR #57747 - [logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57747-merge-3600f6c8430f4f4ea3/System.Threading.Tasks.Tests/1/console.1a7e1da3.log?sv=2019-07-07&se=2021-09-08T19%3A54%3A35Z&sr=c&sp=rl&sig=X5uca7OZN15MnflHJyMYq6KXQ3eKR2rrtEdEUDpLJIc%3D)
