### ISSUE TITLE
Test failure: DefaultConnect_EndToEnd_Ok

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#57342]
Test: System.Net.Security.Tests.CertificateValidationRemoteServer

Failures 6/13-8/13 (incl. PRs):

Day | Run | OS
-- | -- | --
7/29 | PR #56500 | Centos.8.Amd64.Open
8/2 | PR #56736 | SLES.15.Amd64.Open
8/7 | Official run | SLES.15.Amd64.Open
8/7 | Official run | Windows.10.Amd64.Server19H1.Open

Failure:
```
System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
---- System.Net.Sockets.SocketException : Connection reset by peer

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1370
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1267
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1098
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 461
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 380
   at System.Net.Security.Tests.CertificateValidationRemoteServer.EndToEndHelper(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 105
   at System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 86
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

Alternative failure (Windows):
```
System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1370
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1267
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1099
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 462
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 381
   at System.Net.Security.Tests.CertificateValidationRemoteServer.EndToEndHelper(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 105
   at System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 84
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

**Comment by wfurt** [comment]
This connects to external server so the failures are likely environmental. 
Perhaps the fix is to capture and ignore SocketException as that is unrelated to intent of the test e.g. verify ability to negotiate TLS to .NET independent implementation.
