### ISSUE TITLE
Test failure: GetAsync_AllowedSSLVersion_Succeeds

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#57343]
Tests affected:
- `System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test`
- `System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test`

Failures 6/13-9/6 (incl. PRs):

Day | Run | Notes
-- | -- | --
6/17 | zapdisable | Windows.10.Arm64v8.Open - both tests
6/21 | jitminopts | Windows.10.Arm64v8.Open - both tests
6/22 | tailcallstress | Windows.10.Arm64v8.Open - both tests
6/23 | jitstress2_jitstressregs3 | Windows.10.Arm64v8.Open - both tests
6/23 | jitstress2_jitstressregs0x10 | Windows.10.Arm64v8.Open - both tests
7/5 | jitstress2 | Windows.10.Arm64v8.Open - both tests
7/6 | jitstress1_tiered | Windows.10.Arm64v8.Open - both tests
7/17 | jitstress2_jitstressregs4 | Windows.10.Arm64v8.Open - both tests
7/17 | jitstress2_jitstressregs4 | Windows.10.Arm64v8.Open - both tests (not duplicate of above)
7/24 | tailcallstress | Windows.10.Arm64v8.Open - both tests
8/9 | jitstress1_tiered | Windows.10.Arm64v8.Open - both tests
8/28 | PR #57691 - jitminopts | Windows.10.Arm64v8.Open - both tests
8/29 | jitstress1_tiered | Windows.10.Arm64v8.Open - both tests
8/29 | PR #57691 - jitstress1 | Windows.10.Arm64v8.Open - both tests
8/29 | defaultpgo | Windows.10.Arm64v8.Open - both tests
_9/2-9/4_ | _PR #58570 - Win11 queue bring up_ | _Windows.11.Amd64.ClientPre.Open_
9/4 | jitstress2_jitstressregs0x80 | Windows.10.Arm64v8.Open - both tests

Failure:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. ( Received an unexpected EOF or 0 bytes from the transport stream.)) (One or more errors occurred. (An error occurred while sending the request.))
---- System.AggregateException : One or more errors occurred. ( Received an unexpected EOF or 0 bytes from the transport stream.)
-------- System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.
---- System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
-------- System.Net.Http.HttpRequestException : An error occurred while sending the request.
------------ System.Net.Http.WinHttpException : Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'.

   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 89
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.<>c__DisplayClass5_1.<<GetAsync_AllowedSSLVersion_Succeeds>b__2>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 135
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 103
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_AllowedSSLVersion_Succeeds(SslProtocols acceptedProtocol, Boolean requestOnlyThisProtocol) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 133
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 465
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 381
   at System.Net.Test.Common.LoopbackServer.Connection.CreateAsync(SocketWrapper socket, Stream stream, Options httpOptions) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 474
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 155
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 163
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendResponseAndCloseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 199
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 72
----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 71
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 959
```

**Comment by wfurt** [comment]
seems all stress conditions on ARM. Im not sure how much we care for platform handler.

**Comment by ManickaP** [comment]
Doesn't fail anymore.
