### ISSUE TITLE
Source generator for System.Text.Json fails when generating info for a nested type with same name as another nested type.

### ISSUE THREAD

**Issue by Ithline** [dotnet/runtime#57378]
### Description
**Source generator for `System.Text.Json` fails when generating info for a nested type with same name as another nested type.**

If I generate metadata only for `RootA`, generator creates files `MyJsonContext.RootA.g.cs`, `MyJsonContext.Item.g.cs`... 
When `RootB` is added to the context, the generator silently fails, probably because file with the name `MyJsonContext.Item.g.cs` already exists.
Even if I remove one of the root types, the project needs to be reloaded for the generator to work again.

Minimal repro of the issue.
```C#
[JsonSerializable(typeof(RootA), GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(RootB), GenerationMode = JsonSourceGenerationMode.Metadata)]
internal partial class MyJsonContext : JsonSerializerContext
{
}
internal class RootA
{
    public Item? ItemProperty { get; set; }

    internal class Item
    {
        public int IntId { get; set; }
    }
}
internal class RootB
{
    public Item? ItemProperty { get; set; }

    internal class Item
    {
        public long LongId { get; set; }
    }
}
```

### Configuration
Running on 6.0.100-preview.7.21379.14

**Comment by eiriktsarpalis** [comment]
When trying this locally using SDK v6.0.100-rc.1.21415.3 with the following code:
```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Repro
{
    public class Program
    {
        public static void Main()
        {
            Console.WriteLine(JsonSerializer.Serialize(new RootA(), MyJsonContext.Default.RootA));
            Console.WriteLine(JsonSerializer.Serialize(new RootB(), MyJsonContext.Default.RootB));
        }
    }

    [JsonSerializable(typeof(RootA), GenerationMode = JsonSourceGenerationMode.Metadata)]
    [JsonSerializable(typeof(RootB), GenerationMode = JsonSourceGenerationMode.Metadata)]
    internal partial class MyJsonContext : JsonSerializerContext
    {
    }

    internal class RootA
    {
        public Item? ItemProperty { get; set; }

        internal class Item
        {
            public int IntId { get; set; }
        }
    }

    internal class RootB
    {
        public Item? ItemProperty { get; set; }

        internal class Item
        {
            public long LongId { get; set; }
        }
    }
}
```
Compilation seems to be working however I'm getting the following runtime error:
```
Unhandled exception. System.InvalidOperationException: The generic type of the converter for property 'Repro.RootB.ItemProperty' must match with the specified converter type 'Repro.RootB+Item'. The converter must not be 'null'.
   at System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo[T](JsonSerializerOptions options, Boolean isProperty, Boolean isPublic, Boolean isVirtual, Type declaringType, JsonTypeInfo propertyTypeInfo, JsonConverter`1 converter, Func`2 getter, Action`2 setter, Nullable`1 ignoreCondition, Boolean hasJsonInclude, Nullable`1 numberHandling, String propertyName, String jsonPropertyName)
   at Repro.MyJsonContext.RootBPropInit(JsonSerializerContext context) in C:\Users\eitsarpa\source\repos\ConsoleApp1\ConsoleApp1\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyJsonContext.RootB.g.cs:line 47
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache()
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingMetadata[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteUsingMetadata[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonTypeInfo`1 jsonTypeInfo)
   at Repro.Program.Main() in C:\Users\eitsarpa\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 12
```
@Ithline does this match what you're experiencing? If not, could you share a standalone console app that does?

**Comment by Ithline** [comment]
@eiriktsarpalis I copied the exact snippet you posted into a clean project and I still get errors from failed source generator.

These are the errors I get when running `dotnet run` from the project directory. 
```
CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'MyJsonContext.Item.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'
```
```
error CS0534: 'MyJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
```
Visual Studio does not show any src gen errors, just the second compilation error about missing implementation.

Same result when run on `6.0.100-preview.7.21379.14` or `6.0.100-rc.1.21416.3`

**Comment by eiriktsarpalis** [comment]
What version of Visual Studio are you using? Does the same error appear if you try to build from the cli?

**Comment by Ithline** [comment]
Yes, the same error appears in both VS and cli. I have edited my previous comment to clarify when each of those two messages occur.
I'm using VS2022 Preview 3 and 3.1.
