### ISSUE TITLE
[wasm][eat] System.Runtime.CompilerServices.Tests.RequiredAttributeAttributeTests.Ctor_RequiredContract

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#57460]
This is an interesting one since it looks like we trimmed out System.Int32 on mono
```
[23:37:43] info: Starting:    System.Runtime.CompilerServices.VisualC.Tests.dll
[23:37:43] fail: [FAIL] System.Runtime.CompilerServices.Tests.RequiredAttributeAttributeTests.Ctor_RequiredContract
[23:37:43] info: System.TypeLoadException : Could not load type System.Int32, System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a while decoding custom attribute: (null)
[23:37:43] info:    at System.Reflection.RuntimeCustomAttributeData.ResolveArguments()
[23:37:43] info:    at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
[23:37:43] info:    at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo , Type )
[23:37:43] info: Finished:    System.Runtime.CompilerServices.VisualC.Tests.dll
```

**Comment by lewing** [comment]
search failed me the first time https://github.com/dotnet/runtime/issues/51211 covers this.
