### ISSUE TITLE
Cannot migrate Blazor WASM from Preview 5 to 7

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/runtime#57572]
### Description

When migrating a Blazor WASM application from Preview 5 to 7, compilation runs properly and the application launches properly but it does not upgrade the application in the browser properly.  The following error is raised:

```
'System.Reflection.Metadata.MetadataUpdater' in assembly 'System.Runtime.Loader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'))
 ---> System.TypeLoadException: Could not resolve type with token 010000b6 from typeref (expected class 'System.Reflection.Metadata.MetadataUpdater' in assembly 'System.Runtime.Loader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<RunAsyncCore>d__15](<RunAsyncCore>d__15& stateMachine)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken cancellationToken, WebAssemblyCultureProvider cultureProvider)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsync()
   at KlipTok.Client.Program.Main(String[] args)
   --- End of inner exception stack trace --- blazor.webassembly.js:1:38631
    callEntryPoint http://localhost:5000/_framework/blazor.webassembly.js:1
    lt http://localhost:5000/_framework/blazor.webassembly.js:1
    <anonymous> http://localhost:5000/_framework/blazor.webassembly.js:1
    <anonymous> http://localhost:5000/_framework/blazor.webassembly.js:1
```

### Configuration

* .NET 6 preview 7
* Windows 10
* x64
* Firefox, 

### Regression?

* I was able to migrate and update applications from preview 1 through each version to 6.  I did not deploy preview 6 as GitHub Actions did not support it.

### Other information

Source code available on request

**Comment by csharpfritz** [comment]
My bad...  had multiple versions ccriss-crossing with global.json.

Closing
