### ISSUE TITLE
[trimming] System.Diagnostics trimming out DebuggerTypeProxyAttribute.

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#57588]
```
[01:53:09] fail: [FAIL] System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.DebuggerAttribute_NullDictionary_ThrowsArgumentNullException
[01:53:09] info: Assert.Throws() Failure
[01:53:09] info: Expected: typeof(System.Reflection.TargetInvocationException)
[01:53:09] info: Actual:   typeof(System.InvalidOperationException): Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ReadOnlyDictionary`2[System.Int32,System.Int32].
[01:53:09] info: ---- System.InvalidOperationException : Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ReadOnlyDictionary`2[System.Int32,System.Int32].
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.<>c.<DebuggerAttribute_NullDictionary_ThrowsArgumentNullException>b__13_0()
[01:53:09] info: ----- Inner Stack Trace -----
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.<>c.<DebuggerAttribute_NullDictionary_ThrowsArgumentNullException>b__13_0()
[01:53:09] fail: [FAIL] System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.DebuggerAttribute_NullDictionaryKeys_ThrowsArgumentNullException
[01:53:09] info: Assert.Throws() Failure
[01:53:09] info: Expected: typeof(System.Reflection.TargetInvocationException)
[01:53:09] info: Actual:   typeof(System.InvalidOperationException): Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ReadOnlyDictionary`2+KeyCollection[System.Int32,System.Int32].
[01:53:09] info: ---- System.InvalidOperationException : Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ReadOnlyDictionary`2+KeyCollection[System.Int32,System.Int32].
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.<>c.<DebuggerAttribute_NullDictionaryKeys_ThrowsArgumentNullException>b__14_0()
[01:53:09] info: ----- Inner Stack Trace -----
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.<>c.<DebuggerAttribute_NullDictionaryKeys_ThrowsArgumentNullException>b__14_0()
[01:53:09] fail: [FAIL] System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.DebuggerAttributeTests
[01:53:09] info: System.InvalidOperationException : Expected one DebuggerDisplayAttribute on System.Collections.ObjectModel.ReadOnlyDictionary`2[System.Int32,System.Int32].
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerDisplayReferences(Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ReadOnlyDictionaryTests.DebuggerAttributeTests()
[01:53:09] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[01:53:09] fail: [FAIL] System.Collections.ObjectModel.Tests.ConstructorAndPropertyTests.DebuggerAttributeTests
[01:53:09] info: System.InvalidOperationException : Expected one DebuggerDisplayAttribute on System.Collections.ObjectModel.ObservableCollection`1[System.Int32].
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerDisplayReferences(Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ConstructorAndPropertyTests.DebuggerAttributeTests()
[01:53:09] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[01:53:09] fail: [FAIL] System.Collections.ObjectModel.Tests.ConstructorAndPropertyTests.DebuggerAttribute_NullCollection_ThrowsArgumentNullException
[01:53:09] info: Assert.Throws() Failure
[01:53:09] info: Expected: typeof(System.Reflection.TargetInvocationException)
[01:53:09] info: Actual:   typeof(System.InvalidOperationException): Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ObservableCollection`1[System.Int32].
[01:53:09] info: ---- System.InvalidOperationException : Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ObservableCollection`1[System.Int32].
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ConstructorAndPropertyTests.<>c.<DebuggerAttribute_NullCollection_ThrowsArgumentNullException>b__11_0()
[01:53:09] info: ----- Inner Stack Trace -----
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:09] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Object obj)
[01:53:09] info:    at System.Collections.ObjectModel.Tests.ConstructorAndPropertyTests.<>c.<DebuggerAttribute_NullCollection_ThrowsArgumentNullException>b__11_0()
[01:53:20] fail: [FAIL] System.Collections.ObjectModel.Tests.ObservableCollection_Serialization.OnDeserialized_MonitorNotInitialized_ExpectSuccess
[01:53:20] info: Assert.NotNull() Failure
[01:53:20] info:    at System.Collections.ObjectModel.Tests.ObservableCollection_Serialization.OnDeserialized_MonitorNotInitialized_ExpectSuccess()
[01:53:20] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[01:53:21] fail: [FAIL] System.Collections.ObjectModel.Tests.ReadOnlyObservableCollectionTests.DebuggerAttribute_Tests
[01:53:21] info: System.InvalidOperationException : Expected one DebuggerDisplayAttribute on System.Collections.ObjectModel.ReadOnlyObservableCollection`1[System.Int32].
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerDisplayReferences(Object obj)
[01:53:21] info:    at System.Collections.ObjectModel.Tests.ReadOnlyObservableCollectionTests.DebuggerAttribute_Tests()
[01:53:21] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[01:53:21] fail: [FAIL] System.Collections.ObjectModel.Tests.ReadOnlyObservableCollectionTests.DebuggerAttribute_NullCollection_ThrowsArgumentNullException
[01:53:21] info: Assert.Throws() Failure
[01:53:21] info: Expected: typeof(System.Reflection.TargetInvocationException)
[01:53:21] info: Actual:   typeof(System.InvalidOperationException): Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ReadOnlyObservableCollection`1[System.Int32].
[01:53:21] info: ---- System.InvalidOperationException : Expected one DebuggerTypeProxyAttribute on System.Collections.ObjectModel.ReadOnlyObservableCollection`1[System.Int32].
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Object obj)
[01:53:21] info:    at System.Collections.ObjectModel.Tests.ReadOnlyObservableCollectionTests.<>c.<DebuggerAttribute_NullCollection_ThrowsArgumentNullException>b__10_0()
[01:53:21] info: ----- Inner Stack Trace -----
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.GetProxyType(Type type, Type[] genericTypeArguments)
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Type[] genericTypeArguments, Object obj)
[01:53:21] info:    at System.Diagnostics.DebuggerAttributes.ValidateDebuggerTypeProxyProperties(Type type, Object obj)
[01:53:21] info:    at System.Collections.ObjectModel.Tests.ReadOnlyObservableCollectionTests.<>c.<DebuggerAttribute_NullCollection_ThrowsArgumentNullException>b__10_0()
[01:53:21] info: Finished:    System.ObjectModel.Tests.dll
[01:53:21] info: 
[01:53:21] info: === TEST EXECUTION SUMMARY ===
[01:53:21] info: Total: 2152, Errors: 0, Failed: 8, Skipped: 4, Time: 24.01992s
```

**Comment by jkotas** [comment]
We have `PlatformDetection.IsDebuggerTypeProxyAttributeSupported`. If it is not done already, it should get wired in for wasm and the tests marked with it `[ConditionalTheory(typeof(PlatformDetection), nameof(PlatformDetection.IsDebuggerTypeProxyAttributeSupported))]`.

**Comment by jkotas** [comment]
Updating aread label - the failing tests are under System.Collections.

**Comment by layomia** [comment]
@lewing @ilonatommy, any idea if this issue still occurs?

**Comment by jkotas** [comment]
We still have test disabled against this issue.

**Comment by ilonatommy** [comment]
Still failing, I will take a look

**Comment by ilonatommy** [comment]
I do not see a point to expect from `Activator.CreateInstance(proxyType, obj)` to throw when `obj == null`. When obj is null then the Activator uses the "the constructor that takes no parameters (the parameterless constructor)" and `ObservableCollection` has a parentless one. From this reason I am changing the expected behavior in the tests to throw when `customAttributes.Lentgh != 1` (in the failing tests it's 0).

**Comment by kotlarmilos** [comment]
The failures are still relevant.
