### ISSUE TITLE
Test failure baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#57621]
Run: [runtime-coreclr outerloop 20210817.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1299333&view=ms.vss-test-web.build-test-results-tab&runId=38310366&resultId=110466&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked no_tiered_compilation @ OSX.1013.Amd64.Open

- baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
- baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh

```
**Error message:**
```
Process terminated. Parallel crash in thread 5!

at System.Environment.FailFast(System.String)
at ParallelCrash.CrashInParallel()
at System.Threading.Thread.StartCallback()
task_for_pid(69869) FAILED 5 (os/kern) failure

cmdLine:/private/tmp/helix/working/B19409A0/w/A1A508F2/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 8/17/2021 3:07:45 PM, end: 8/17/2021 3:17:45 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/B19409A0/w/A1A508F2/uploads/Reports/baseservices.exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/B19409A0/w/A1A508F2/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '2'
BEGIN EXECUTION
/tmp/helix/working/B19409A0/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll '2'

cmdLine:/private/tmp/helix/working/B19409A0/w/A1A508F2/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 8/17/2021 3:07:45 PM, end: 8/17/2021 3:17:45 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/tmp/helix/working/B19409A0/p
/private/tmp/helix/working/B19409A0/w/A1A508F2/e/baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCraWorkerThreads_ParallelCraWorkerThreads_._simple_ParallelCrashWorkerThreads_ParallelCrashWorkerThreads_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr outerloop 20210905.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1344037&view=ms.vss-test-web.build-test-results-tab&runId=39356156&resultId=110483&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked @ OSX.1014.Amd64.Open

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
- baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
- baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh

```
**Error message:**
```
Process terminated. Parallel crash in thread 7!

at System.Environment.FailFast(System.String)
at ParallelCrash.CrashInParallel()
at System.Threading.Thread.StartCallback()
task_for_pid(68713) FAILED 5 (os/kern) failure

cmdLine:/private/tmp/helix/working/A28F0973/w/AECB099B/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 9/5/2021 2:54:57 PM, end: 9/5/2021 3:04:58 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/A28F0973/w/AECB099B/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A28F0973/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''

cmdLine:/private/tmp/helix/working/A28F0973/w/AECB099B/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 9/5/2021 2:54:57 PM, end: 9/5/2021 3:04:58 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/tmp/helix/working/A28F0973/p
/private/tmp/helix/working/A28F0973/w/AECB099B/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr ilasm 20210925.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1386471&view=ms.vss-test-web.build-test-results-tab&runId=40374126&paneView=debug&resultId=110486)

Failed test:
```
CoreCLR OSX x64 Checked ilasmroundtrip @ OSX.1014.Amd64.Open

- baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh
- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
- baseservices/exceptions/simple/ParallelCrashWorkerThreads/ParallelCrashWorkerThreads.sh
```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
task_for_pid(95045) FAILED 5 (os/kern) failure
../ParallelCrash/ParallelCrash.sh: line 362: 95045 Abort trap: 6           (core dumped) $LAUNCHER ParallelCrash.asm.dll "${CLRTestExecutionArguments[@]}"
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
task_for_pid(95173) FAILED 5 (os/kern) failure

cmdLine:/private/tmp/helix/working/BFF30A7E/w/BB770A4E/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 1200000 from variable __TestTimeout, start: 9/25/2021 1:34:44 PM, end: 9/25/2021 1:54:44 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/BFF30A7E/w/BB770A4E/uploads/Reports/baseservices.exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/BFF30A7E/w/BB770A4E/e/baseservices/exceptions/simple/ParallelCrashMainThread
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '1'
BEGIN EXECUTION
/tmp/helix/working/BFF30A7E/p/ildasm -raweh -out=ParallelCrash.dasm.il ParallelCrash.dll
/tmp/helix/working/BFF30A7E/p/ilasm -output=ParallelCrash.asm.dll ParallelCrash.dasm.il

Microsoft (R) .NET IL Assembler.  Version 7.0.0-ci
C
Assembling 'ParallelCrash.dasm.il'  to EXE --> 'ParallelCrash.asm.dll'
Source file is UTF-8

Assembled method ParallelCrash::Main
Assembled method ParallelCrash::CrashInParallel
Assembled method ParallelCrash::.ctor
Creating PE file

Emitting classes:
Class 1:ParallelCrash

Emitting fields and methods:
Global
Class 1Fields: 4;Methods: 3;
Resolving local member refs: 9 -> 9 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
/tmp/helix/working/BFF30A7E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.asm.dll '1'
/tmp/helix/working/BFF30A7E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll '1'

cmdLine:/private/tmp/helix/working/BFF30A7E/w/BB770A4E/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 1200000 from variable __TestTimeout, start: 9/25/2021 1:34:44 PM, end: 9/25/2021 1:54:44 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/tmp/helix/working/BFF30A7E/p
/private/tmp/helix/working/BFF30A7E/w/BB770A4E/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCraMainThread_ParallelCraMainThread_._simple_ParallelCrashMainThread_ParallelCrashMainThread_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr outerloop 20211020.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1432566&view=ms.vss-test-web.build-test-results-tab&runId=41386122&resultId=110508&paneView=debug)

Failed test:
```
CoreCLR OSX x64 Checked @ OSX.1014.Amd64.Open

- baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
task_for_pid(27324) FAILED 5 (os/kern) failure

cmdLine:/private/tmp/helix/working/A888092A/w/B12F09CE/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 10/20/2021 12:16:20 PM, end: 10/20/2021 12:26:20 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/A888092A/w/B12F09CE/uploads/Reports/baseservices.exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/private/tmp/helix/working/A888092A/w/B12F09CE/e/baseservices/exceptions/simple/ParallelCrashMainThread
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '1'
BEGIN EXECUTION
/tmp/helix/working/A888092A/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll '1'

cmdLine:/private/tmp/helix/working/A888092A/w/B12F09CE/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 10/20/2021 12:16:20 PM, end: 10/20/2021 12:26:20 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/tmp/helix/working/A888092A/p
/private/tmp/helix/working/A888092A/w/B12F09CE/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCraMainThread_ParallelCraMainThread_._simple_ParallelCrashMainThread_ParallelCrashMainThread_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20220320.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1673015&view=ms.vss-test-web.build-test-results-tab&runId=45914772&resultId=110738&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_zapdisable_heapverify1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 3/20/2022 11:37:50 PM, end: 3/21/2022 1:07:50 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''
Gathering state for process 5102 corerun
Crashing thread 000013ee signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5102.dmp
Written 217346048 bytes (53063 pages) to core file
Dump successfully written

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 3/20/2022 11:37:50 PM, end: 3/21/2022 1:07:50 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr gcstress0x3-gcstress0xc 20220717.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1886281&view=ms.vss-test-web.build-test-results-tab&runId=49269048&paneView=debug&resultId=110235)

Failed test:
```
coreclr Linux arm64 Checked gcstress0xc @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f8a62ec90)

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 7/17/2022 3:49:26 PM, end: 7/17/2022 4:49:26 PM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''
[createdump] Gathering state for process 3494 corerun
[createdump] Crashing thread 00000da6 signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3494.dmp
[createdump] Written 219242496 bytes (53526 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 3603ms

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 7/17/2022 3:49:26 PM, end: 7/17/2022 4:49:26 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Closing since a related bug https://github.com/dotnet/runtime/issues/72565 has been fixed. If this occurs again please reopen.
