### ISSUE TITLE
[WinHttpHandler] System.Net.Http.WinHttpHandler.Functional.Tests crashing with assertion failed

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57737]
Configuration: `net6.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open`
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57730-merge-96b2d8dba97c461a86/System.Net.Http.WinHttpHandler.Functional.Tests/1/console.d970de3a.log?sv=2019-07-07&se=2021-09-08T14%3A39%3A11Z&sr=c&sp=rl&sig=h607nUjTFpIhAsZcxqHwSXBA7qNzcJI1WCNA3e%2BrRfA%3D
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1304329&view=ms.vss-test-web.build-test-results-tab&runId=38416918&paneView=debug
Branch: release/6.0-rc1

**Dump is available**

```
  Discovering: System.Net.Http.WinHttpHandler.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.WinHttpHandler.Functional.Tests (found 293 of 519 test cases)
  Starting:    System.Net.Http.WinHttpHandler.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
      Condition(s) not met: "IsSelectedSitesTestEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
      Condition(s) not met: "IsSelectedSitesTestEnabled"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "CanTestCertificates"
    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
      Condition(s) not met: "CanTestCertificates"
Process terminated. Assertion failed.
   at Interop.WinHttp.SafeWinHttpHandle.SetParentHandle(SafeWinHttpHandle parentHandle) in /_/src/libraries/Common/src/Interop/Windows/WinHttp/Interop.SafeWinHttpHandle.cs:line 34
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 910
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<>c.<SendAsync>b__117_0(Object s) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 629
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2331
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 708
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 63
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
----- end Thu 08/19/2021 15:01:55.07 ----- exit code -2146232797 ----------------------------------------------------------
```

**Comment by karelz** [comment]
Triage: Happened only once so far, moving to 7.0.

**Comment by ViktorHofer** [comment]
@karelz which data source do you use for finding hits?

**Comment by karelz** [comment]
Yes, Kusto. I reviewed today data from 7/30 (older data is not available).

**Comment by rzikm** [comment]
No recent (<60 days) hits as of 2022-05-02. Closing until this resurfaced
