### ISSUE TITLE
System.Threading.Tasks.Tests FailFast

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57751]
Configuration: `net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open`

Console: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ba682e275827487daf/System.Threading.Tasks.Tests/1/console.cd7d4d5f.log?sv=2019-07-07&se=2021-09-02T05%3A41%3A20Z&sr=c&sp=rl&sig=3%2BNS2Pg%2BbC3b8eMj8b%2FwjkyfF9OQjb0excO11zGNt5k%3D

Dump: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ba682e275827487daf/System.Threading.Tasks.Tests/1/dotnet.exe.3996.dmp?sv=2019-07-07&se=2021-09-02T05%3A41%3A20Z&sr=c&sp=rl&sig=3%2BNS2Pg%2BbC3b8eMj8b%2FwjkyfF9OQjb0excO11zGNt5k%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1291774&view=ms.vss-test-web.build-test-results-tab&runId=38121666&resultId=198580&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tasks.Tests (found 574 of 752 test cases)
  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 2)
Process terminated. Look at the created dump
   at System.Environment.FailFast(System.String)
   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion>d__32, System.Threading.Tasks.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion>d__32, System.Threading.Tasks.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion>d__32, System.Threading.Tasks.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
----- end Fri 08/13/2021  6:00:45.93 ----- exit code -2146232797 ----------------------------------------------------------
```

**Comment by stephentoub** [comment]
I've tried multiple times to make this test reliable, and apparently still have not succeeded.  Invariably I end up debugging a dump that shows the object is unreachable but not yet finalized.  Will just disable it for now.

**Comment by adamsitnik** [comment]
@stephentoub have you tried to repro https://github.com/dotnet/runtime/issues/57331 ? Should we disable it as well?

**Comment by ViktorHofer** [comment]
Happened again in https://dev.azure.com/dnceng/public/_build/results?buildId=1301031&view=ms.vss-test-web.build-test-results-tab&runId=38343962&resultId=198394&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab.

**Comment by stephentoub** [comment]
> Happened again

It's been disabled.  Presumably this run is just from before that happened?

**Comment by stephentoub** [comment]
> have you tried to repro #57331 ? Should we disable it as well?

That's likely a similar cause; I've been unable to make either of these stable, for unknown reasons.  I can disable it as well.

**Comment by ViktorHofer** [comment]
> It's been disabled. Presumably this run is just from before that happened?

The test ran on "8/18/2021, 12:57:36 PM" (main).

**Comment by stephentoub** [comment]
And it was disabled on the 19th.
