### ISSUE TITLE
Microsoft.Extensions.FileProviders.Physical.Tests failing with "Nullable object must have a value."

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57755]
Configuration: `net6.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open`

Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-26a41069e65141db99/Microsoft.Extensions.FileProviders.Physical.Tests/1/console.5b5c56fe.log?sv=2019-07-07&se=2021-09-03T05%3A59%3A46Z&sr=c&sp=rl&sig=TOh52NGCkmX9ydvCJV8V%2FdA8M1m59eFp2%2FIUj9fvW%2Fs%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1293627&view=ms.vss-test-web.build-test-results-tab&runId=38169646&resultId=194013&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
  Discovering: Microsoft.Extensions.FileProviders.Physical.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.FileProviders.Physical.Tests (found 76 of 92 test cases)
  Starting:    Microsoft.Extensions.FileProviders.Physical.Tests (parallel test collections = on, max threads = 4)
Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value() in /_/src/libraries/System.Private.CoreLib/src/System/Nullable.cs:line 40
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 68
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 112
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 455
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 673
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 327
./RunTests.sh: line 162: 10114 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig Microsoft.Extensions.FileProviders.Physical.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.FileProviders.Physical.Tests.deps.json xunit.console.dll Microsoft.Extensions.FileProviders.Physical.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/9D5A0889/w/BB5F09BA/e
----- end Fri Aug 13 23:02:40 PDT 2021 ----- exit code 134 ----------------------------------------------------------
```

**Comment by Jozkee** [comment]
Fixed with multiple recent changes (https://github.com/dotnet/runtime/pull/57415, https://github.com/dotnet/runtime/pull/57551) that build is from 08/13; this should no longer occur in builds containing the PRs that I just mentioned.
