### ISSUE TITLE
JIT: Assertion failed 'false'

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#57774]
```
export COMPlus_TieredCompilation=0
export COMPlus_ReadyToRun=0
export COMPlus_ZapDisable=1

 JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh [FAIL]
      
      Assert failure(PID 7987 [0x00001f33], Thread: 7987 [0x1f33]): Assertion failed 'false' in 'System.Collections.Generic.Dictionary`2[Char,__Canon][System.Char,System.__Canon]:TryInsert(ushort,System.__Canon,ubyte):bool:this' during 'Early Value Propagation' (IL size 739)
      
          File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 199
          Image: /datadisks/disk1/work/A11008DE/p/corerun
      
      /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh: line 351:  7987 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A11008DE/w/B72709EF/uploads/Reports/JIT.Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.output.txt
      Raw output:
      BEGIN EXECUTION
      /datadisks/disk1/work/A11008DE/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_56953.dll ''
      BBF_HAS_IDX_LEN is not set on BB15 but is required because of the following tree 
      N002 (  3,  3) [000967] ---X---H----              *  ARR_LENGTH int   
      N001 (  1,  1) [000968] -------H----              \--*  LCL_VAR   ref    V04 loc0         u:1
      Gathering state for process 7987 corerun
      Crashing thread 00001f33 signal 00000006
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7987.dmp
      Written 52674560 bytes (12860 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/A11008DE/p
      > /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Regression._JitBlue_Runtime_56953_Runtime_56953_Runtime_56953_._JitBlue_Runtime_56953_Runtime_56953_Runtime_56953_sh()
      Output:
        
        Assert failure(PID 7987 [0x00001f33], Thread: 7987 [0x1f33]): Assertion failed 'false' in 'System.Collections.Generic.Dictionary`2[Char,__Canon][System.Char,System.__Canon]:TryInsert(ushort,System.__Canon,ubyte):bool:this' during 'Early Value Propagation' (IL size 739)
        
            File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 199
            Image: /datadisks/disk1/work/A11008DE/p/corerun
        
        /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh: line 351:  7987 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A11008DE/w/B72709EF/uploads/Reports/JIT.Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.output.txt
        Raw output:
        BEGIN EXECUTION
        /datadisks/disk1/work/A11008DE/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_56953.dll ''
        BBF_HAS_IDX_LEN is not set on BB15 but is required because of the following tree 
        N002 (  3,  3) [000967] ---X---H----              *  ARR_LENGTH int   
        N001 (  1,  1) [000968] -------H----              \--*  LCL_VAR   ref    V04 loc0         u:1
        Gathering state for process 7987 corerun
        Crashing thread 00001f33 signal 00000006
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7987.dmp
        Written 52674560 bytes (12860 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/A11008DE/p
        > /datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh
```

**Comment by EgorBo** [comment]
I assume earlyprop propagated GT_ARR_LEN node but forgot to set BBF_HAS_IDX_LEN to destination block

**Comment by SingleAccretion** [comment]
So this is another `JitOptRepeat` issue, heh. I think we should reset `BBF_HAS_IDX_LEN` and `BBF_HAS_NULLCHECK` in `ResetOptAnnotations`.

In this case it is hoisting that has created a statement with `ARR_LENGTH` (but without the annotation, obviously). In the normal compilation early prop runs before hoisting, so it is not an actual problem.

**Comment by VincentBu** [comment]
Failed in: [runtime-coreclr jitstress 20210818.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1303648&view=ms.vss-test-web.build-test-results-tab&runId=38399508&paneView=debug&resultId=109948)

Faied test:
```
CoreCLR Linux x64 Checked zapdisable @ Ubuntu.1804.Amd64.Open

- JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh

```
**Error message:**
```
Assert failure(PID 7987 [0x00001f33], Thread: 7987 [0x1f33]): Assertion failed 'false' in 'System.Collections.Generic.Dictionary`2[Char,__Canon][System.Char,System.__Canon]:TryInsert(ushort,System.__Canon,ubyte):bool:this' during 'Early Value Propagation' (IL size 739)

File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 199
Image: /datadisks/disk1/work/A11008DE/p/corerun
/datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh: line 351:  7987 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/A11008DE/w/B72709EF/uploads/Reports/JIT.Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/A11008DE/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_56953.dll ''
BBF_HAS_IDX_LEN is not set on BB15 but is required because of the following tree
N002 (  3,  3) [000967] ---X---H----              *  ARR_LENGTH int

N001 (  1,  1) [000968] -------H----              --*  LCL_VAR   ref    V04 loc0         u:1
Gathering state for process 7987 corerun
Crashing thread 00001f33 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7987.dmp
Written 52674560 bytes (12860 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/A11008DE/p
/datadisks/disk1/work/A11008DE/w/B72709EF/e/JIT/Regression/JitBlue/Runtime_56953/Runtime_56953/Runtime_56953.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_56953_Runtime_56953_Runtime_56953_._JitBlue_Runtime_56953_Runtime_56953_Runtime_56953_sh()
```
