### ISSUE TITLE
Test JITLoad_CustomALC failed: TestLibrary.AssertTestException: Assert.IsTrue: Bind event count for AssemblyToLoad

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#57786]
```
set RunCrossGen2=1 
set CompositeBuildMode=1 
```

```
    Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd [FAIL]
      Could Not Find D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\IL-CG2\composite-r2r.dll
      Could Not Find D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\composite-r2r.dll.rsp
      Return code:      1
      Raw output file:      D:\h\w\AC68099A\w\B26E09BB\uploads\Reports\Loader.binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.output.txt
      Raw output:
      BEGIN EXECUTION
      AssemblyToLoad.dll
      BinderTracingTest.Basic.dll
      TestLibrary.dll
              3 file(s) copied.
      Response file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll.rsp
      D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\IL-CG2\*.dll
      -o:D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll
      --targetarch:arm64
      --verify-type-and-field-layout
      -r:D:\h\w\AC68099A\p\System.*.dll
      -r:D:\h\w\AC68099A\p\Microsoft.*.dll
      -r:D:\h\w\AC68099A\p\mscorlib.dll
      -r:D:\h\w\AC68099A\p\netstandard.dll
      -O
      " "dotnet" "D:\h\w\AC68099A\p\crossgen2\crossgen2.dll" @"D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll.rsp"   --composite"
      Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll
      Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\AssemblyToLoad.dll
      Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.dll
      Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\TestLibrary.dll
       "D:\h\w\AC68099A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" BinderTracingTest.Basic.dll 
      [2:17:58 AM] Running LoadFile...
      [2:17:59 AM] Running LoadBytes...
      [2:17:59 AM] Running LoadFromStream...
      [2:17:59 AM] Running LoadFromAssemblyPath...
      [2:17:59 AM] Launching process for LoadFromAssemblyName...
      [2:18:00 AM] Running LoadFromAssemblyName...
      
      [2:18:00 AM] Launching process for LoadFrom...
      [2:18:00 AM] Running LoadFrom...
      
      [2:18:01 AM] Launching process for PlatformAssembly...
      [2:18:01 AM] Running PlatformAssembly...
      
      [2:18:02 AM] Launching process for PlatformAssembly_Cached...
      [2:18:02 AM] Running PlatformAssembly_Cached...
      
      [2:18:02 AM] Launching process for Reflection...
      [2:18:03 AM] Running Reflection...
      
      [2:18:03 AM] Launching process for Reflection_Cached...
      [2:18:04 AM] Running Reflection_Cached...
      
      [2:18:04 AM] Launching process for Reflection_CustomALC...
      [2:18:04 AM] Running Reflection_CustomALC...
      
      [2:18:05 AM] Launching process for ContextualReflection_DefaultToCustomALC...
      [2:18:05 AM] Running ContextualReflection_DefaultToCustomALC...
      
      [2:18:06 AM] Launching process for ContextualReflection_CustomToDefaultALC...
      [2:18:06 AM] Running ContextualReflection_CustomToDefaultALC...
      
      [2:18:06 AM] Launching process for JITLoad...
      [2:18:07 AM] Running JITLoad...
      
      [2:18:07 AM] Launching process for JITLoad_CustomALC...
      [2:18:07 AM] Running JITLoad_CustomALC...
      Test JITLoad_CustomALC failed: TestLibrary.AssertTestException: Assert.IsTrue: Bind event count for AssemblyToLoad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null - expected: 1, actual: 2
         at TestLibrary.Assert.HandleFail(String assertionName, String message)
         at BinderTracingTests.BinderTracingTest.ValidateSingleBind(BinderEventListener listener, AssemblyName assemblyName, BindOperation expected)
         at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method)
      
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\AC68099A\p
      > D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at Loader_binding._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_._tracing_BinderTracingTest_Basic_BinderTracingTest_Basic_cmd()
      Output:
        Could Not Find D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\IL-CG2\composite-r2r.dll
        Could Not Find D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\composite-r2r.dll.rsp
        
        
        
        
        
        
        
        
        
        
        
        
        Return code:      1
        Raw output file:      D:\h\w\AC68099A\w\B26E09BB\uploads\Reports\Loader.binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.output.txt
        Raw output:
        BEGIN EXECUTION
        AssemblyToLoad.dll
        BinderTracingTest.Basic.dll
        TestLibrary.dll
                3 file(s) copied.
        Response file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll.rsp
        D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\IL-CG2\*.dll
        -o:D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll
        --targetarch:arm64
        --verify-type-and-field-layout
        -r:D:\h\w\AC68099A\p\System.*.dll
        -r:D:\h\w\AC68099A\p\Microsoft.*.dll
        -r:D:\h\w\AC68099A\p\mscorlib.dll
        -r:D:\h\w\AC68099A\p\netstandard.dll
        -O
        " "dotnet" "D:\h\w\AC68099A\p\crossgen2\crossgen2.dll" @"D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll.rsp"   --composite"
        Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\\composite-r2r.dll
        Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\AssemblyToLoad.dll
        Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.dll
        Emitting R2R PE file: D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\TestLibrary.dll
         "D:\h\w\AC68099A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" BinderTracingTest.Basic.dll 
        [2:17:58 AM] Running LoadFile...
        [2:17:59 AM] Running LoadBytes...
        [2:17:59 AM] Running LoadFromStream...
        [2:17:59 AM] Running LoadFromAssemblyPath...
        [2:17:59 AM] Launching process for LoadFromAssemblyName...
        [2:18:00 AM] Running LoadFromAssemblyName...
        
        [2:18:00 AM] Launching process for LoadFrom...
        [2:18:00 AM] Running LoadFrom...
        
        [2:18:01 AM] Launching process for PlatformAssembly...
        [2:18:01 AM] Running PlatformAssembly...
        
        [2:18:02 AM] Launching process for PlatformAssembly_Cached...
        [2:18:02 AM] Running PlatformAssembly_Cached...
        
        [2:18:02 AM] Launching process for Reflection...
        [2:18:03 AM] Running Reflection...
        
        [2:18:03 AM] Launching process for Reflection_Cached...
        [2:18:04 AM] Running Reflection_Cached...
        
        [2:18:04 AM] Launching process for Reflection_CustomALC...
        [2:18:04 AM] Running Reflection_CustomALC...
        
        [2:18:05 AM] Launching process for ContextualReflection_DefaultToCustomALC...
        [2:18:05 AM] Running ContextualReflection_DefaultToCustomALC...
        
        [2:18:06 AM] Launching process for ContextualReflection_CustomToDefaultALC...
        [2:18:06 AM] Running ContextualReflection_CustomToDefaultALC...
        
        [2:18:06 AM] Launching process for JITLoad...
        [2:18:07 AM] Running JITLoad...
        
        [2:18:07 AM] Launching process for JITLoad_CustomALC...
        [2:18:07 AM] Running JITLoad_CustomALC...
        Test JITLoad_CustomALC failed: TestLibrary.AssertTestException: Assert.IsTrue: Bind event count for AssemblyToLoad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null - expected: 1, actual: 2
           at TestLibrary.Assert.HandleFail(String assertionName, String message)
           at BinderTracingTests.BinderTracingTest.ValidateSingleBind(BinderEventListener listener, AssemblyName assemblyName, BindOperation expected)
           at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method)
        
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\h\w\AC68099A\p
        > D:\h\w\AC68099A\w\B26E09BB\e\Loader\binding\tracing\BinderTracingTest.Basic\BinderTracingTest.Basic.cmd
```

**Comment by mangod9** [comment]
Hi @echesakovMSFT, is this a regression? Also looks like it only repros with composite mode?

**Comment by mangod9** [comment]
Possibly by design if the test is counting actual assembly loads which might be different with composite? @trylek ?
