### ISSUE TITLE
Unhandled exception about "System.Drawing.Common is not supported on this platform" occurs when running winforms application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/runtime#57791]
* .NET Core Version: 
.Net 6.0 RC1 build: 6.0.100-rc.1.21418.27 from release/6.0.1xx-rc1 branch in https://github.com/dotnet/installer
**This is a regression issue**, cannot repro previous .Net 6.0 build: 6.0.100-rc.1.21417.19

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**
1. Create a Winforms .Net 6.0 application
2. Build and run app

**Expected behavior:**
Form designer can be loaded successfully, Build and run app successfully

**Actual behavior:**
1. Form designer is still in loading state
2. Run app failed with an exception: "System.Drawing.Common is not supported on this platform" 
![image](https://user-images.githubusercontent.com/26474449/130025157-be38b9ab-1e8c-4bc2-a1d3-b4a120b1ec1d.png)

System.PlatformNotSupportedException
  HResult=0x80131539
  Message=System.Drawing.Common is not supported on this platform.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.SystemFonts.get_MessageBoxFont()
   at System.Windows.Forms.Control.get_DefaultFont()
   at System.Windows.Forms.Control.GetDefaultFontHandleWrapper()
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.ContainerControl.GetFontAutoScaleDimensions()
   at System.Windows.Forms.ContainerControl.get_CurrentAutoScaleDimensions()
   at System.Windows.Forms.ContainerControl.get_AutoScaleFactor()
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds, Boolean causedByFontChanged)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.Form.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(IArrangedElement affectedElement, String affectedProperty)
   at System.Windows.Forms.ContainerControl.LayoutScalingNeeded()
   at System.Windows.Forms.ContainerControl.set_AutoScaleMode(AutoScaleMode value)
   at WinFormsApp31.Form1.InitializeComponent() in C:\Users\v-olzhan\source\repos\WinFormsApp31\WinFormsApp31\Form1.Designer.cs:line 32
   at WinFormsApp31.Form1..ctor() in C:\Users\v-olzhan\source\repos\WinFormsApp31\WinFormsApp31\Form1.cs:line 17
   at WinFormsApp31.Program.Main() in C:\Users\v-olzhan\source\repos\WinFormsApp31\WinFormsApp31\Program.cs:line 20

**Comment by tarekgh** [comment]
@ViktorHofer I have labeled this issue as infrastructure and 6.0 milestone. Feel free to label it back to System.Drawing if this is not the case.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang , is this the case with `main` as well?

  For the latest builds today, both of .Net 6.0 RC1 and RC2 have this issue, cannot find main branch to verify.
![image](https://user-images.githubusercontent.com/26474449/130166652-881913a0-52d2-480c-9b69-8a225a096429.png)

**Comment by ViktorHofer** [comment]
The fix went into dotnet/runtime and will automatically flow into wimdowsdesktop which will fix this.

Sorry for the inconvenience.

**Comment by ericstj** [comment]
@dreddy-work I just checked dotnet-sdk-6.0.100-rc.2.21428.9-win-x64.zip and it has the fix.  If you are still facing issues please double check that you're using the latest build and open a new issue with repro steps.  Make sure you include the exact version of the SDK you are using so that we can ensure we're looking at the same thing.

For the separate issue, same thing applies: ensure clear repro steps with versions and open a new issue.  If I had to guess, that looks to me like a case where the SDK is writing one version to the runtimeconfig that doesn't match the shared framework which was installed.  I can imagine a case where this might happen if you're swapping builds out for an app without rebuilding everything.

**Comment by Zheng-Li01** [comment]
@dreddy-work @ericstj, verified the issue with latest .NET 6.0.100-rc.2.21428.23 build, the issue has been fixed that the core project targeting latest 6.0 rc2 can running successfully.

Thanks for all your help 👍 .
