### ISSUE TITLE
System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected failing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57809]
Configuration: `net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open`

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1304608&view=ms.vss-test-web.build-test-results-tab&runId=38423284&paneView=debug

Console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-53ecd4535bcc4e978c/System.Drawing.Common.Tests/1/console.765b5c7d.log?sv=2019-07-07&se=2021-09-08T16%3A50%3A59Z&sr=c&sp=rl&sig=LPuJcqGgWEzROrBEs5LOCFOwTg7tXQQbATGG6en%2F3P0%3D

```
  Discovering: System.Drawing.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Drawing.Common.Tests (found 2025 of 2061 test cases)
  Starting:    System.Drawing.Common.Tests (parallel test collections = on, max threads = 2)
    System.Drawing.Tests.ImageAnimatorManualTests.AnimateAndCaptureFrames [SKIP]
      Condition(s) not met: "ManualTestsEnabled"
    System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 [SKIP]
      Condition(s) not met: "IsOSX"
    System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected(getIcon: Func`1 { Method = System.Drawing.Icon <SystemIcons_TestData>b__0_1(), Target = <>c { } }) [FAIL]
      Assert.Same() Failure
      Expected: (Icon)
      Actual:   (Icon)
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/SystemIconsTests.cs(32,0): at System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected(Func`1 getIcon)
  Finished:    System.Drawing.Common.Tests
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220425.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1736001&view=ms.vss-test-web.build-test-results-tab&runId=46987436&paneView=debug&resultId=124686)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.10.Arm64v8.Open

- System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected(getIcon: Func`1 { Method = System.Drawing.Icon <SystemIcons_TestData>b__0_2(), Target = <>c { } })

```
**Error message:**
```
Assert.Same() Failure
Expected: (Icon)
Actual:   (Icon)


Stack trace
   at System.Drawing.Tests.SystemIconsTests.SystemIcons_Get_ReturnsExpected(Func`1 getIcon) in /_/src/libraries/System.Drawing.Common/tests/SystemIconsTests.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 387
```
