### ISSUE TITLE
Runtime tests failing `The given key 'appContextSwitch' was not present in the dictionary.`

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#57886]
```
      Expected: True
      Actual:   False
      Stack Trace:
           at tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_sh()
      Output:
        console.error: 
        console.error: Unhandled Exception:
        console.error: System.Collections.Generic.KeyNotFoundException: The given key 'appContextSwitch' was not present in the dictionary.
        console.error:    at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(String key)
        console.error:    at RuntimeEventListener.Verify()
        console.error:    at Program.<Main>$(String[] args)
        console.error: Error: System.Collections.Generic.KeyNotFoundException: The given key 'appContextSwitch' was not present in the dictionary.
           at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(String key)
           at RuntimeEventListener.Verify()
           at Program.<Main>$(String[] args)
        console.error: Error: System.Collections.Generic.KeyNotFoundException: The given key 'appContextSwitch' was not present in the dictionary.
           at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(String key)
           at RuntimeEventListener.Verify()
           at Program.<Main>$(String[] args)
            at Object._convert_exception_for_method_call (dotnet.js:1:177569)
            at Object._handle_exception_for_call (dotnet.js:1:179538)
            at Object._handle_exception_and_produce_result_for_call (dotnet.js:1:179859)
            at Object._call_method_with_converted_args (dotnet.js:1:180933)
            at Object.call_method (dotnet.js:1:179328)
            at dotnet.js:1:186013
            at Object.call_assembly_entry_point (dotnet.js:1:186246)
            at Object.init (runtime.js:368:24)
            at Object.Module.config.loaded_cb (runtime.js:255:8)
            at Object._finalize_startup (dotnet.js:1:136368)
```

**Comment by lewing** [comment]
Looks like it started in https://github.com/dotnet/runtime/pull/57303

https://github.com/dotnet/runtime/pull/57857

https://github.com/dotnet/runtime/pull/57847

**Comment by lewing** [comment]
cc @agocke
