### ISSUE TITLE
Test failure profiler/multiple/multiple/multiple.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#57906]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20210822.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1310776&view=ms.vss-test-web.build-test-results-tab&runId=38582630&resultId=109428&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked gcstress0x3 @ OSX.1100.ARM64.Open

- profiler/multiple/multiple/multiple.sh
- profiler/unittest/releaseondetach/releaseondetach.sh

CoreCLR windows x64 Checked gcstress0x3 @ Windows.10.Amd64.Open

- profiler\\multiple\\multiple\\multiple.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd

CoreCLR windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open

- profiler\\multiple\\multiple\\multiple.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

- profiler\\multiple\\multiple\\multiple.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd

CoreCLR windows arm64 Checked gcstress0x3 @ Windows.10.Arm64v8.Open

- profiler\\multiple\\multiple\\multiple.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open

- profiler\\multiple\\multiple\\multiple.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd
- 

CoreCLR Linux x64 Checked gcstress0xc @ Ubuntu.1804.Amd64.Open

- profiler/multiple/multiple/multiple.sh
- profiler/unittest/releaseondetach/releaseondetach.sh
- 

CoreCLR OSX arm64 Checked gcstress0xc @ OSX.1100.ARM64.Open

- profiler/unittest/releaseondetach/releaseondetach.sh
- profiler/multiple/multiple/multiple.sh

CoreCLR windows arm64 Checked gcstress0xc @ Windows.10.Arm64v8.Open

- profiler\\multiple\\multiple\\multiple.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd

```
**Error message:**
```
Fatal error while logging another fatal error.
task_for_pid(99111) FAILED 5 (os/kern) failure
Unhandled exception. System.Exception: Profilee returned exit code 134 instead of expected exit code 100.
at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
at Profiler.Tests.MultiplyLoaded.Main(String[] args)
task_for_pid(99092) FAILED 5 (os/kern) failure
/private/tmp/helix/working/C14F0A74/w/C4E60A91/e/profiler/multiple/multiple/multiple.sh: line 348: 99092 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/C14F0A74/w/C4E60A91/uploads/Reports/profiler.multiple/multiple/multiple.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/C14F0A74/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false multiple.dll ''
Profiler path: /private/tmp/helix/working/C14F0A74/w/C4E60A91/e/profiler/multiple/multiple/libProfiler.dylib
Profiler path: /private/tmp/helix/working/C14F0A74/w/C4E60A91/e/profiler/multiple/multiple/libProfiler.dylib
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Setting exception mask
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Profiler path: /private/tmp/helix/working/C14F0A74/w/C4E60A91/e/profiler/multiple/multiple/libProfiler.dylib
Setting exception mask
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Throwing exception
Exception caught
Waiting for profilers to all detach
Setting exception mask
MultiplyLoaded::ExceptionThrown, number seen = 0
MultiplyLoaded::ExceptionThrown, number seen = 1
MultiplyLoaded::ExceptionThrown, number seen = 2
Requesting detach!!
Requesting detach!!
Requesting detach!!
RequestProfilerDetach hr=0x0
RequestProfilerDetach hr=0x0
RequestProfilerDetach hr=0x0
ProfilerDetachSucceeded _detachCount=1
ProfilerDetachSucceeded _detachCount=2
PROFILER TEST PASSES

Test failed: Profilee returned exit code 134 instead of expected exit code 100.
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/C14F0A74/p
/private/tmp/helix/working/C14F0A74/w/C4E60A91/e/profiler/multiple/multiple/multiple.sh
Expected: True
Actual:   False


Stack trace
   at profiler_multiple._multiple_multiple_._multiple_multiple_sh()
```
or
```
Assert failure(PID 4768 [0x000012a0], Thread: 4024 [0x0fb8]): CONTRACT VIOLATION by UMEntryThunk::ReportViolation at "D:\workspace_work\1\s\src\coreclr\vm\dllimportcallback.cpp" @ 361

You must have called SetupThread in order to be in GC Cooperative mode.

                    CONTRACT in UMEntryThunk::ReportViolation at "D:\workspace\_work\1\s\src\coreclr\vm\dllimportcallback.cpp" @ 361
We can't find the violated contract. Look for an old-style non-holder-based contract.

CORECLR! CONTRACT_ASSERT + 0x2C8 (0x6ffc5d91)
CORECLR! EEContract::DoChecks + 0x15F (0x7025f927)
CORECLR! UMEntryThunk::ReportViolation + 0x155 (0x70259325)
PROFILER! DoPInvoke + 0x6F027 (0x6f0cbbe7)
PROFILER! DoPInvoke + 0x6E6FB (0x6f0cb2bb)
PROFILER! DoPInvoke + 0x6D86C (0x6f0ca42c)
PROFILER! DoPInvoke + 0x10C392 (0x6f168f52)
KERNEL32! BaseThreadInitThunk + 0x24 (0x73d562c4)
NTDLL! RtlSubscribeWnfStateChangeNotification + 0x439 (0x771c1b69)
NTDLL! RtlSubscribeWnfStateChangeNotification + 0x404 (0x771c1b34)
File: D:\workspace_work\1\s\src\coreclr\vm\dllimportcallback.cpp Line: 361
Image: C:\h\w\A75508F6\p\CoreRun.exe

Unhandled exception. System.Exception: Profilee returned exit code -1073740286 instead of expected exit code 100.
at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
at Profiler.Tests.ReleaseOnShutdown.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A75508F6\w\A09008BB\uploads\Reports\profiler.unittest\releaseondetach\releaseondetach.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A75508F6\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" releaseondetach.dll
Profiler path: C:\h\w\A75508F6\w\A09008BB\e\profiler\unittest\releaseondetach\Profiler.dll
Attaching profiler C:\h\w\A75508F6\w\A09008BB\e\profiler\unittest\releaseondetach\Profiler.dll to self.
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Initialize for attach started
RequestProfilerDetach successful
Profiler detach succeeded
PROFILER TEST PASSES

Test failed: Profilee returned exit code -1073740286 instead of expected exit code 100.
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A75508F6\p
C:\h\w\A75508F6\w\A09008BB\e\profiler\unittest\releaseondetach\releaseondetach.cmd
Expected: True
Actual:   False


Stack trace
   at profiler_unittest._releaseondetach_releaseondetach_._releaseondetach_releaseondetach_cmd()
```

**Comment by tommcdon** [comment]
@davmason

**Comment by tommcdon** [comment]
Possible duplicate to #57461
