### ISSUE TITLE
Test failure GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#58018]
Test type:
- `System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest`
- `System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Decompression_Tests`
- `System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Decompression_Tests`

External server http://httpbin.org hiccup

Failures 3/12-8/25 (incl. PRs):

Day | Failures
-- | --
_3/12_ | _... main branch data only ..._
5/17 @ 12:06:04 | 1x failure (1x main)
_6/25_ | _... Includes release/6.0* branches data ..._
6/30 @ 12:01:55-12:32:29 (30 min) | 16x failures (7x 6.0-preview3, 4x 6.0-preview5, 4x 6.0-preview6, 1x **main**)
7/15 @ 12:14:18 | 1x failure (1x 6.0-preview5)
7/16 @ 12:09:12 | 1x failure (1x 6.0-preview7)
7/19 @ 12:11:50 | 1x failure (1x 6.0-preview5)
7/21 @ 12:11:42-13:17:50 (1:06 h:min) | 5x failure (2x 6.0-preview3, 2x 6.0-preview6, 1x 6.0-preview5)
8/3 @ 12:08:27-12:19:33 (11 min) | 3x failure (2x 6.0-preview3, 1x 6.0-preview6)
8/16 @ 14:35:27 | 1x failure (1x **main**)
8/20 @ 12:15:14-15:18:24 (3:03 h:min) | 7x failure (1x 6.0-rc1, 6x PR #57747 off **main** branch)
8/21 @ 12:13:14-12:31:46 (18 min) | 2x failures (1x 6.0-rc1, 1x **main**)
8/22 @ 12:09:25 | 1x failure (1x release/6.0)
8/23 @ 13:06:49 | 1x failure (1x 6.0-rc1)
8/24 @ 10:40:06 | 1x failure (PR #58002 off release/6.0 branch)

Failure 1:
```
System.Net.Http.HttpRequestException : Response status code does not indicate success: 502 (Bad Gateway).

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 172
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 187
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.RemoteServer.cs:line 1295
--- End of stack trace from previous location ---
```

Failure 2:
```
System.Net.Http.HttpRequestException : Response status code does not indicate success: 504 (Gateway Time-out).

   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 172
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 187
   at System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.RemoteServer.cs:line 1295
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Previously tracked by #46439 and #52889

**Comment by geoffkizer** [comment]
This is why we should do this: https://github.com/dotnet/runtime/issues/47351

**Comment by wfurt** [comment]
I'm wondering if we should extend the enterprise scenario tests. We are already running Apache server so we should be able to do it right now and adding compression should trivial IMHO.

**Comment by rzikm** [comment]
No hits in last 60 days, closing until this resurfaces.
