### ISSUE TITLE
[wasm] ReleaseJSOwnedObjectByGCHandle - Value cannot be null

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#58031]
While running System.Net.Http.Functional.Tests locally 

```
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.Remove(Object key) in C:\\Dev\\runtime\\src\\libraries\\System.Private.CoreLib\\src\\System\\Collections\\Generic\\Dictionary.cs:line 976
   at System.Runtime.InteropServices.JavaScript.Runtime.ReleaseJSOwnedObjectByGCHandle(Int32 gcHandle) in C:\\Dev\\runtime\\src\\libraries\\System.Private.Runtime.InteropServices.JavaScript\\src\\System\\Runtime\\InteropServices\\JavaScript\\Runtime.JS.Owned.cs:line 53
```

**Comment by pavelsavara** [comment]
Hmm, I could not reproduce it anymore.

**Comment by pavelsavara** [comment]
`The FinalizationRegistry callback is called potentially multiple times` see https://github.com/tc39/proposal-weakrefs
