### ISSUE TITLE
Memory access violation when using named pipes on Alpine

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#58045]
We get the intermittent failure that I have copied below on our Alpine runs for this [test](https://github.com/dotnet/performance/blob/f7ec27a4da2d61b97184f07989e5d9c6e0c21988/src/benchmarks/micro/libraries/System.IO.Pipes/Perf.PipeTest.cs) run on this [type](https://github.com/dotnet/performance/blob/d7dac8a7ca12a28d099192f8a901cf8e30361384/src/benchmarks/micro/libraries/System.IO.Pipes/Perf.NamedPipeStream.cs). This could be a BDN issue, but it looks like the failure happened when we were executing the test code, not in BDN. Going to tag @adamsitnik just in case though. 

```
[2021/08/24 06:48:02][INFO] Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[2021/08/24 06:48:02][INFO]    at System.Collections.Concurrent.ConcurrentQueueSegment`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryDequeue(System.__Canon ByRef)
[2021/08/24 06:48:02][INFO]    at System.Threading.ThreadPoolWorkQueue.Dequeue(System.Threading.ThreadPoolWorkQueueThreadLocals, Boolean ByRef)
[2021/08/24 06:48:02][INFO]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[2021/08/24 06:48:02][INFO]    at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
[2021/08/24 06:48:02][INFO]    at System.Threading.Thread.StartCallback()
[2021/08/24 06:48:03][INFO] // Benchmark Process 18404 has exited with code 134.
[2021/08/24 06:48:03][INFO] Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
[2021/08/24 06:48:03][INFO]    at System.Linq.ThrowHelper.ThrowNoMatchException()
[2021/08/24 06:48:03][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
[2021/08/24 06:48:03][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
[2021/08/24 06:48:03][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
[2021/08/24 06:48:03][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
[2021/08/24 06:48:03][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
[2021/08/24 06:48:03][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[2021/08/24 06:48:03][INFO]    at MicroBenchmarks.Program.Main(String[] args) in /home/helixbot/work/B34C09E2/p/performance/src/benchmarks/micro/Program.cs:line 41
[2021/08/24 06:48:03][INFO] $ popd
[2021/08/24 06:48:03][ERROR] Process exited with status 134
```

**Comment by adamsitnik** [comment]
@kouvel @stephentoub Is there any chance it's a bug in `ThreadPool`?

**Comment by kouvel** [comment]
I guess it's some sort of memory corruption leading to a crash at some point related to where the memory was corrupted, the stack trace may not indicate what caused the memory corruption. Afaik safe managed code shouldn't be able to create this type of issue aside from runtime bugs.

**Comment by mangod9** [comment]
@DrewScoggins is there a repro and/or dump available for the issue?

**Comment by DrewScoggins** [comment]
I do not have a dump for this. We do not auto-collect dumps of failures in the perf lab. I could try and collect one by running that test over and over and seeing if I can reproduce the crash, but that is the only way I know of trying to repro this.

**Comment by janvorli** [comment]
@DrewScoggins does this issue still occur?

**Comment by mangod9** [comment]
Closing this for now, please reopen if still an issue.
