### ISSUE TITLE
System.PlatformNotSupportedException : The PKCS#12 Exportable flag is not supported on this platform. breaking many tests on tvOS simulator

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#58044]
This is failing many tests in `System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_*`
```
System.PlatformNotSupportedException : The PKCS#12 Exportable flag is not supported on this platform.


Stack trace
   at Internal.Cryptography.Pal.AppleCertificatePal.FromDerBlob(ReadOnlySpan`1 rawData, X509ContentType contentType, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at Internal.Cryptography.Pal.AppleCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_SingleCert.ReadPfx(Byte[] pfxBytes, String correctPassword, X509Certificate2 expectedCert, Action`1 otherWork, X509KeyStorageFlags flags)
   at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests_SingleCert.ReadMultiPfx(Byte[] pfxBytes, String correctPassword, X509Certificate2 expectedSingleCert, X509Certificate2[] expectedOrder, X509KeyStorageFlags nonExportFlags, Action`1 perCertOtherWork)
   at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests.ReadMultiPfx(Byte[] pfxBytes, String correctPassword, X509Certificate2 expectedSingleCert, X509Certificate2[] expectedOrder, Action`1 perCertOtherWork)
   at System.Security.Cryptography.X509Certificates.Tests.PfxFormatTests.TwoCerts_TwoKeys_ManySafeContentsValues(Boolean invertCertOrder, Boolean invertKeyOrder)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1313534&view=ms.vss-test-web.build-test-results-tab&runId=38657078&resultId=142723&paneView=debug

@mdh1418 this is making a lot of noise when looking through staging failures.

@dotnet/area-system-security is the correct change here to just disable these tests permanently for tvOS?

**Comment by danmoseley** [comment]
was in https://github.com/dotnet/runtime/pull/57992

**Comment by danmoseley** [comment]
Looks like it's also net6.0-MacCatalyst-Release-x64-Mono_Release-OSX.1015.Amd64.Open

**Comment by mdh1418** [comment]
Thanks! There were recent changes to throw PNSE on that flag for iOS,tvOS,MacCatalyst in https://github.com/dotnet/runtime/pull/57153, same for Android with https://github.com/dotnet/runtime/pull/57494
Theres a PR open to skip the tests because of the PNSE, in addition to skipping other test suites crashing on iOS,tvOS,MacCatalyst as well https://github.com/dotnet/runtime/pull/57208
