### ISSUE TITLE
Test failure ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58151]
Run: [runtime 20210825.48](https://dev.azure.com/dnceng/public/_build/results?buildId=1317614&view=ms.vss-test-web.build-test-results-tab&runId=38752534&resultId=189062&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest

```
**Error message:**
```
System.AggregateException : changeInCompletedWorkItemCount: 1 (Assert.InRange() Failure
Range:  (0 - 60000)
Actual: 60015)
---- Assert.InRange() Failure
Range:  (0 - 60000)
Actual: 60015


Stack trace
   at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest() in /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs:line 29
----- Inner Stack Trace -----
   at System.Threading.Tests.ThreadTestHelpers.WaitForConditionWithCustomDelay(Func`1 condition, Action delay) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 147
   at System.Threading.Tests.ThreadTestHelpers.WaitForCondition(Func`1 condition) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 117
   at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest() in /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs:line 20
```

**Comment by mangod9** [comment]
@kouvel, this appears to be a test issue?

**Comment by kouvel** [comment]
The test was disabled in https://github.com/dotnet/runtime/pull/57957, https://github.com/dotnet/runtime/issues/49700 is tracking the disabled test
