### ISSUE TITLE
Crossgen2 fails with null reference exception.

### ISSUE THREAD

**Issue by mfilippov** [dotnet/runtime#58181]
### Description

Crossgen2 fails when I try to use it on my project.
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ILCompiler.CompilerTypeSystemContext.GetModuleForSimpleName(String simpleName, Boolean throwIfNotFound)
   at ILCompiler.CompilerTypeSystemContext.ResolveAssembly(AssemblyName name, Boolean throwIfNotFound)
   at Internal.TypeSystem.Ecma.EcmaModule.ResolveAssemblyReference(AssemblyReferenceHandle handle) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaModule.cs:line 581
   at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaModule.cs:line 122
   at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Common\Utilities\LockFreeReaderHashtable.cs:line 560
   at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaModule.cs:line 368
   at Internal.TypeSystem.Ecma.EcmaModule.ResolveTypeReference(TypeReferenceHandle handle) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaModule.cs:line 530
   at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaModule.cs:line 114
   at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Common\Utilities\LockFreeReaderHashtable.cs:line 560
   at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaModule.cs:line 368
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ResolveHandle(EntityHandle handle) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 65
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode)
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 102
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 334
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 324
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 238
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 102
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 334
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 324
   at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseFieldSignature() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaSignatureParser.cs:line 470
   at Internal.TypeSystem.Ecma.EcmaField.InitializeFieldType() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaField.cs:line 102
   at Internal.TypeSystem.Ecma.EcmaField.get_FieldType() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Ecma\EcmaField.cs:line 111
   at Internal.TypeSystem.MetadataFieldLayoutAlgorithm.ComputeInstanceLayout(DefType defType, InstanceLayoutKind layoutKind) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Common\MetadataFieldLayoutAlgorithm.cs:line 38
   at Internal.TypeSystem.DefType.ComputeInstanceLayout(InstanceLayoutKind layoutKind) in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Common\DefType.FieldLayout.cs:line 399
   at Internal.TypeSystem.DefType.get_InstanceFieldSize() in C:\Work\GitHub\runtime\src\coreclr\tools\Common\TypeSystem\Common\DefType.FieldLayout.cs:line 128
   at ILCompiler.ReadyToRunRootProvider.CheckTypeCanBeUsedInSignature(TypeDesc type)
   at ILCompiler.ReadyToRunRootProvider.CheckCanGenerateMethod(MethodDesc method)
   at ILCompiler.ReadyToRunRootProvider.RootMethods(TypeDesc type, String reason, IRootingServiceProvider rootProvider)
   at ILCompiler.ReadyToRunRootProvider.AddCompilationRoots(IRootingServiceProvider rootProvider)
   at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 compilationRoots, ILProvider ilProvider, DevirtualizationManager devirtualizationManager, IEnumerable`1 modulesBeingInstrumented, Logger logger, InstructionSetSupport instructionSetSupport)
   at ILCompiler.ReadyToRunCodegenCompilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 roots, ILProvider ilProvider, Logger logger, DevirtualizationManager devirtualizationManager, IEnumerable`1 inputFiles, String compositeRootPath, InstructionSetSupport instructionSetSupport, Boolean resilient, Boolean generateMapFile, Boolean generateMapCsvFile, Boolean generatePdbFile, Func`2 printReproInstructions, String pdbPath, Boolean generatePerfMapFile, String perfMapPath, Int32 perfMapFormatVersion, Boolean generateProfileFile, Int32 parallelism, ProfileDataManager profileData, ReadyToRunMethodLayoutAlgorithm methodLayoutAlgorithm, ReadyToRunFileLayoutAlgorithm fileLayoutAlgorithm, Int32 customPESectionAlignment, Boolean verifyTypeAndFieldLayout)
   at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation()
   at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```
### Configuration

Windows 10 x64
runtime built from source 17d7b2cdf4593d5eefcc21cfda021b61872a8804

### Regression?

No

**Comment by mfilippov** [comment]
Fixed vi #58183
