### ISSUE TITLE
System.Security.Principal.Windows outerloop tests fail if run as non-admin

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#58207]
```
    Discovering: System.Security.Principal.Windows.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Security.Principal.Windows.Tests (found 30 test cases)
    Starting:    System.Security.Principal.Windows.Tests (parallel test collections = on, max threads = 12)
      WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution [FAIL]
        System.AggregateException : One or more errors occurred. (Failed to get SafeAccessTokenHandle for test account CorFxTstWiIde01kiu) (The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture)
        ---- System.Exception : Failed to get SafeAccessTokenHandle for test account CorFxTstWiIde01kiu
        -------- System.ComponentModel.Win32Exception : The user name or password is incorrect.
        ---- The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture
        Stack Trace:

          ----- Inner Stack Trace #1 (System.Exception) -----
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(171,0): at WindowsTestAccount.CreateUser()
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(125,0): at WindowsTestAccount..ctor(String userName)
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(106,0): at WindowsIdentityFixture..ctor()
          ----- Inner Stack Trace -----

          ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

      WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT [FAIL]
        System.AggregateException : One or more errors occurred. (Failed to get SafeAccessTokenHandle for test account CorFxTstWiIde01kiu) (The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture)
        ---- System.Exception : Failed to get SafeAccessTokenHandle for test account CorFxTstWiIde01kiu
        -------- System.ComponentModel.Win32Exception : The user name or password is incorrect.
        ---- The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture
        Stack Trace:

          ----- Inner Stack Trace #1 (System.Exception) -----
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(171,0): at WindowsTestAccount.CreateUser()
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(125,0): at WindowsTestAccount..ctor(String userName)
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(106,0): at WindowsIdentityFixture..ctor()
          ----- Inner Stack Trace -----

          ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

        System.AggregateException : One or more errors occurred. (Failed to get SafeAccessTokenHandle for test account CorFxTstWiIde01kiu) (The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture)
        ---- System.Exception : Failed to get SafeAccessTokenHandle for test account CorFxTstWiIde01kiu
      WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution [FAIL]
        -------- System.ComponentModel.Win32Exception : The user name or password is incorrect.
        ---- The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture
        Stack Trace:

          ----- Inner Stack Trace #1 (System.Exception) -----
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(171,0): at WindowsTestAccount.CreateUser()
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(125,0): at WindowsTestAccount..ctor(String userName)
          D:\repos\runtime\src\libraries\System.Security.Principal.Windows\tests\WindowsIdentityImpersonatedTests.netcoreapp.cs(106,0): at WindowsIdentityFixture..ctor()
          ----- Inner Stack Trace -----

          ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

      WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType_Netcoreapp [SKIP]
        Condition(s) not met: "AccountIsDomainJoined"
      WellKnownSidTypeTests.CanCreateSecurityIdentifierFromWellKnownSidType [SKIP]
        Condition(s) not met: "AccountIsDomainJoined"
    Finished:    System.Security.Principal.Windows.Tests
  === TEST EXECUTION SUMMARY ===
     System.Security.Principal.Windows.Tests  Total: 32, Errors: 0, Failed: 3, Skipped: 2, Time: 0.479s
  ----- end Thu 08/26/2021 15:16:56.86 ----- exit code 1 ----------------------------------------------------------
```

**Comment by danmoseley** [comment]
@krwq I think we have no protection against tests that require admin, right? as test runs are all run elevated.

**Comment by vcsjones** [comment]
Sometimes we guard tests with `PlatformDetection.IsWindowsAndElevated` (we do this in CNG tests, at least). Perhaps that would be a suitable solution for these outer loop tests.

**Comment by vcsjones** [comment]
It looks like this got fixed by https://github.com/dotnet/runtime/pull/62559. The failing tests are now conditioned on `PlatformDetection.CanRunImpersonatedTests` which checks to see if we're elevated.

Given that I think this can be closed.
