### ISSUE TITLE
Test failure Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.RollForwardOnNoCandidateFxMultipleFrameworks.ReconcileFrameworkReferences_InnerFrameworkReference_PreRelease(versionReference: \"6.0.0\", rollForwardOnNoCandidateFx: null, applyPatches: null, resolvedFramework: \"6.2.1\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58228]
Run: [runtime 20210826.108](https://dev.azure.com/dnceng/public/_build/results?buildId=1321749&view=ms.vss-test-web.build-test-results-tab&runId=38835426&resultId=100086&paneView=debug)

Failed test:
```
Installer-coreclr-windows_x86-Release

- Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.RollForwardOnNoCandidateFxMultipleFrameworks.ReconcileFrameworkReferences_InnerFrameworkReference_PreRelease(versionReference: \"6.0.0\", rollForwardOnNoCandidateFx: null, applyPatches: null, resolvedFramework: \"6.2.1\")
- Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.RollForwardOnNoCandidateFx.RollForwardOnMinor_RollOverPreRelease(rollForwardOnNoCandidateFx: 2, applyPatches: False, resolvedFramework: \"4.5.2\")
- Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.RollForwardOnNoCandidateFx.RollForwardOnMinor_RollOverPreRelease(rollForwardOnNoCandidateFx: 2, applyPatches: null, resolvedFramework: \"4.5.2\")

```
**Error message:**
```
The command output did not contain expected result: "mock frameworks: Microsoft.NETCore.App 6.2.1""\r\nFile Name: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\dotnet.exe\r\nArguments: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.dll\r\nExit Code: 0\r\nStdOut:\r\n--- Invoked hostpolicy mock - corehost_load\r\nmock version: 369365249 124\r\nmock config: <empty>\r\nmock fx_dir: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\r\nmock fx_name: MiddleWare\r\nmock deps_file: \r\nmock is_framework_dependent: 1\r\nmock probe_paths: <empty>\r\nmock host_mode: 1\r\nmock tfm: \r\nmock additional_deps_serialized: \r\nmock fx_ver: 2.1.0\r\nmock fx_names: \r\nmock fx_names: MiddleWare\r\nmock fx_names: Microsoft.NETCore.App\r\nmock fx_dirs: \r\nmock fx_dirs: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\r\nmock fx_dirs: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\r\nmock fx_requested_versions: \r\nmock fx_requested_versions: 2.1.0\r\nmock fx_requested_versions: 6.1.1-preview.1\r\nmock fx_found_versions: \r\nmock fx_found_versions: 2.1.2\r\nmock fx_found_versions: 6.1.1-preview.2\r\nmock host_command:\r\nmock host_info_host_path:D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\dotnet.exe\r\nmock host_info_dotnet_root:D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\\r\nmock host_info_app_path:D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\dotnet.dll\r\nmock single_file_bundle_header_offset:0\r\nmock frameworks:   [requested: ] [path: ]\r\nmock frameworks: MiddleWare 2.1.2 [requested: 2.1.0] [path: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2]\r\nmock frameworks: Microsoft.NETCore.App 6.1.1-preview.2 [requested: 6.1.1-preview.1] [path: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2]\r\n\r\nStdErr:\r\nTracing enabled @ Thu Aug 26 21:32:58 2021 GMT\r\n--- Invoked dotnet [version: 7.0.0-ci, commit hash: a026b1de1fd82898c8379b4053cb613405f6e13d] main = {\r\nD:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\dotnet.exe\r\nD:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.dll\r\n}\r\nReading fx resolver directory=[D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\host\fxr]\r\nConsidering fxr version=[7.0.0-ci]...\r\nDetected latest fxr version=[D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\host\fxr\7.0.0-ci]...\r\nResolved fxr [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\host\fxr\7.0.0-ci\hostfxr.dll]...\r\nLoaded library from D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\host\fxr\7.0.0-ci\hostfxr.dll\r\nInvoking fx resolver [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\host\fxr\7.0.0-ci\hostfxr.dll] hostfxr_main_startupinfo\r\nHost path: [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\dotnet.exe]\r\nDotnet path: [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\]\r\nApp path: [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\dotnet.dll]\r\nTracing enabled @ Thu Aug 26 21:32:58 2021 GMT\r\n--- Invoked hostfxr_main_startupinfo [commit hash: a026b1de1fd82898c8379b4053cb613405f6e13d]\r\nChecking if CoreCLR path exists=[D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\coreclr.dll]\r\n--- Executing in muxer mode...\r\nUsing the provided arguments to determine the application to execute.\r\nUsing dotnet root path [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\]\r\nApp runtimeconfig.json from [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.dll]\r\nRuntime config is cfg=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json dev=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.dev.json\r\nAttempting to read runtime config: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json\r\nAttempting to read dev runtime config: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.dev.json\r\nRuntime config [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json] is valid=[1]\r\n--- The specified framework 'Microsoft.NETCore.App', version '6.1.1-preview.1', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '6.1.1-preview.1'.\r\n--- Resolving FX directory, name 'Microsoft.NETCore.App' version '6.1.1-preview.1'\r\nDOTNET_MULTILEVEL_LOOKUP is set to 0\r\nMultilevel lookup is false\r\nSearching FX directory in [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework]\r\nAttempting FX roll forward starting from version='[6.1.1-preview.1]', apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, prefer_release=0\r\n'Roll forward' enabled with version_compatibility_range [minor]. Looking for the lowest release/pre-release greater than or equal version to [6.1.1-preview.1]\r\nFound version [6.1.1-preview.2]\r\nFramework reference resolved to version '6.1.1-preview.2'.\r\nChanging Selected FX version from [] to [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2]\r\nChose FX version [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2]\r\nRuntime config is cfg=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.runtimeconfig.json dev=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.runtimeconfig.dev.json\r\nAttempting to read runtime config: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.runtimeconfig.json\r\nAttempting to read dev runtime config: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.runtimeconfig.dev.json\r\nRuntime config [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.runtimeconfig.json] is valid=[1]\r\n--- The specified framework 'MiddleWare', version '2.1.0', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '2.1.0'.\r\n--- Resolving FX directory, name 'MiddleWare' version '2.1.0'\r\nDOTNET_MULTILEVEL_LOOKUP is set to 0\r\nMultilevel lookup is false\r\nSearching FX directory in [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework]\r\nAttempting FX roll forward starting from version='[2.1.0]', apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, prefer_release=0\r\n'Roll forward' enabled with version_compatibility_range [minor]. Looking for the lowest release/pre-release greater than or equal version to [2.1.0]\r\nFound version [2.1.2]\r\nApplying patch roll forward from [2.1.2] on release/pre-release\r\nInspecting version... [2.1.2]\r\nFramework reference resolved to version '2.1.2'.\r\nChanging Selected FX version from [] to [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2]\r\nChose FX version [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2]\r\nRuntime config is cfg=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\MiddleWare.runtimeconfig.json dev=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\MiddleWare.runtimeconfig.dev.json\r\nAttempting to read runtime config: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\MiddleWare.runtimeconfig.json\r\nAttempting to read dev runtime config: D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\MiddleWare.runtimeconfig.dev.json\r\nRuntime config [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\MiddleWare.runtimeconfig.json] is valid=[1]\r\n--- The specified framework 'Microsoft.NETCore.App', version '6.0.0', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '6.1.1-preview.1'.\r\n--- Summary of all frameworks:\r\n     framework:'MiddleWare', lowest requested version='2.1.0', found version='2.1.2', effective reference version='2.1.0' apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, folder=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\MiddleWare\2.1.2\r\n     framework:'Microsoft.NETCore.App', lowest requested version='6.1.1-preview.1', found version='6.1.1-preview.2', effective reference version='6.1.1-preview.1' apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, folder=D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\r\nExecuting as a framework-dependent app as per config file [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json]\r\n--- Resolving hostpolicy.dll version from deps json [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.deps.json]\r\nCannot use file stream for [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\Microsoft.NETCore.App.deps.json]: No such file or directory\r\nThe expected hostpolicy.dll directory is [D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2]\r\nLoaded library from D:\workspace\_work\1\s\artifacts\tests\Release\ha\frameworkResolution\0\WithOneFramework\shared\Microsoft.NETCore.App\6.1.1-preview.2\hostpolicy.dll\r\nProbed for and did not resolve library symbol corehost_main_with_output_buffer\r\nProbed for and did not resolve library symbol corehost_initialize\r\nTracing enabled @ Thu Aug 26 21:32:58 2021 GMT\r\n--- Invoked hostpolicy mock - corehost_load\r\n--- Invoked hostpolicy mock - corehost_main\r\n--- Invoked hostpolicy mock - corehost_unload\r\n\r\n"


Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.HaveStdOutContaining(String pattern) in /_/src/installer/tests/TestUtils/Assertions/CommandResultAssertions.cs:line 60
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.RollForwardOnNoCandidateFxMultipleFrameworks.ReconcileFrameworkReferences_InnerFrameworkReference_PreRelease(String versionReference, Nullable`1 rollForwardOnNoCandidateFx, Nullable`1 applyPatches, String resolvedFramework) in /_/src/installer/tests/HostActivation.Tests/FrameworkResolution/RollForwardOnNoCandidateFxMultipleFrameworks.cs:line 195
```

**Comment by mateoatr** [comment]
> @mateoatr could you see if this regressed as part of the SDK changes?

I don't think those changes are related. It looks like these tests have been intermittently failing for some time, but commonly these succeed after the second attempt (e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=1299520&view=ms.vss-test-web.build-test-results-tab).

**Comment by vitek-karas** [comment]
Another similar failure: https://github.com/dotnet/runtime/issues/58501

Interestingly all of these are x86 Debug...

**Comment by agocke** [comment]
Looks like this is stale. Closing.
