### ISSUE TITLE
Test failure: GetResponseAsync_UseDefaultCredentials_ExpectSuccess

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#58349]
Test type: `System.Net.Tests.HttpWebRequestTest_Async`

Failures 6/30-8/30 (incl. PRs):

Day | Run | OS
-- | -- | --
7/27 | Official run | Fedora.30.Amd64.Open
8/27 | PR #58232 | Alpine.312.Amd64.Open
8/29 | PR #58270 | Ubuntu.1804.Amd64.Open - Mono
8/31 | PR #58444 | Alpine.312.Amd64.Open

Failure:
```
System.IO.IOException : Cannot determine the frame size or a corrupted frame was received.

   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1420
   at System.Net.Security.SslStream.<ReceiveBlobAsync>d__174`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext() in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 478
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__173`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext() in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 381
   at System.Net.Test.Common.LoopbackServer.Connection.CreateAsync(SocketWrapper socket, Stream stream, Options httpOptions) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 474
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 153
   at System.Net.Test.Common.LoopbackServer.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 1066
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass15_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 117
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 101
   at System.Net.Tests.HttpWebRequestTest.GetResponseAsync_UseDefaultCredentials_ExpectSuccess(Boolean useSsl) in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1469
--- End of stack trace from previous location ---
```

**Comment by rzikm** [comment]
Test failure stopped occuring some 3 weeks ago, since then it happened only on release/6..0 PRs. I'd give it a few more weeks and otherwise close it

**Comment by rzikm** [comment]
no recent failures on main, closing
