### ISSUE TITLE
System.Diagnostics.Process long paths issues

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#58492]
Couple of issues related to using long paths with System.Diagnostics.Process

In all cases below I've used following ProcessStartInfo options:

```csharp
ProcessStartInfo si = new();
si.WorkingDirectory = dir; // depending on case this line might have been skipped
si.FileName = file;

si.ArgumentList.Add("foo");
si.RedirectStandardOutput = true;
si.RedirectStandardError = true;
si.CreateNoWindow = true;
si.UseShellExecute = false;

// and then process started with:
Process process = Process.Start(si);
```

- Starting a process by passing FileName into ProcessStartInfo where file name is a full path longer than MAX_PATH regardless of prefixing path with `\\?\` always ends up with exception:

<details>
<summary>Click to see exception details</summary>
When using `\\?\` prefix:

```
Unhandled exception. System.ComponentModel.Win32Exception (206): The filename or extension is too long.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x600016a+0x37c
   at System.Diagnostics.Process.Start() in System.Diagnostics.Process.dll:token 0x600013f+0xab
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x6000143+0x1b
   at ConsoleApp40.Program.Main(String[] args) in C:\Users\kwicher\source\repos\ConsoleApp40\x\ConsoleApp40\Program.cs:line 77
```

When using path directly:

```
Unhandled exception. System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x600016a+0x37c
   at System.Diagnostics.Process.Start() in System.Diagnostics.Process.dll:token 0x600013f+0xab
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x6000143+0x1b
   at ConsoleApp40.Program.Main(String[] args) in C:\Users\kwicher\source\repos\ConsoleApp40\x\ConsoleApp40\Program.cs:line 77
```

</details>
It's possible to workaround this issue by using `GetShortPathName`, i.e. (in this example shorten the path by using `GetFileName` method):

<details>
<summary>Click to expand code</summary>

```csharp
        [DllImport("kernel32.dll", CharSet = CharSet.Unicode)]
        private static unsafe extern int GetShortPathName(char* longPath, char* shortPath, int numChars);

        public static unsafe string GetFileName(string longPath)
        {
            longPath = Path.GetFullPath(longPath);
            const int MAX_PATH = 260;
            if (longPath.Length < MAX_PATH)
            {
                return longPath;
            }

            if (!longPath.StartsWith(@"\\?\"))
            {
                longPath = @"\\?\" + longPath;
            }

            fixed (char* longPathBuff = longPath)
            {
                int size = GetShortPathName(longPathBuff, null, 0);
                if (size == 0)
                {
                    // error, best attempt is to at least try with that path:
                    return longPath;
                }

                char[] buff = new char[size];
                fixed (char* shortPathBuff = buff)
                {
                    if (GetShortPathName(longPathBuff, shortPathBuff, size) == 0)
                    {
                        // error, best attempt:
                        return longPath;
                    }
                }

                return new string(buff);
            }
        }
```

</details>

- When starting a process by passing just a file name (without directory) to `FileName` and directory to `WorkingDirectory` in the ProcessStructInfo this always throws an exception as well:

<details>
<summary>Click to see exception details</summary>

Regardless of using `\\?\` prefix you get the same exception:

```
Unhandled exception. System.ComponentModel.Win32Exception (267): The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x600016a+0x37c
   at System.Diagnostics.Process.Start() in System.Diagnostics.Process.dll:token 0x600013f+0xab
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x6000143+0x1b
   at ConsoleApp40.Program.Main(String[] args) in C:\Users\kwicher\source\repos\ConsoleApp40\x\ConsoleApp40\Program.cs:line 78
```

Possibly  same workaround as above could work to fix this although have not tried.

</details>

- When using workaround from the first bullet point the arguments passed to ProcessStartInfo disappear, meaning that `args` in main has zero length even though arguments were passed - I have not digged into why this happens or where do they get lost

I've tried on netcoreapp3.1, net5.0 and net6.0 (preview) and seeing the same results.

**Comment by deeprobin** [comment]
I would assume based on the exception that this bug only occurs on Windows.
Can you label this `os-windows`?

Does the error also occur with `ShellExecute`, because internally different paths are chosen in the ShellExecute case?

https://github.com/dotnet/runtime/blob/42044c65e9a09ae3d6f056d53bb1af83aa6ae449/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L25-L27

& does this also occur if specify a [`UserName`](https://docs.microsoft.com/de-de/dotnet/api/system.diagnostics.processstartinfo.username?view=net-6.0), because this uses CreateProcessAsUserW afaik.

Also, can you verify if this is due to the .NET API or simply a limitation of the WinAPI - See [`CreateProcessW`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw)?

**Comment by rseanhall** [comment]
I'm running into this issue, too. The problem is this line:

https://github.com/dotnet/runtime/blob/bfceef9dbd57c1ae9170949ea7845c48ca1ad2ce/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L569

According to the documentation:

> If lpApplicationName is NULL, the module name portion of lpCommandLine is limited to MAX_PATH characters.

The code needs to pass the path to the executable into `lpApplicationName` as well so that it can be longer than `MAX_PATH`.

**Comment by RussKie** [comment]
May be @JeremyKuhne has any insights?

**Comment by danmoseley** [comment]
> The code needs to pass the path to the executable into lpApplicationName as well so that it can be longer than MAX_PATH.

If this wouldn't break anyone, we'd welcome a PR.

Does enabling long paths change behaviors:

https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later

**Comment by rseanhall** [comment]
> Does enabling long paths change behaviors

No, at least as of the current Win11.

> If this wouldn't break anyone

Yeah, about that... it turns out this probably can't be done in a non-breaking way.

1. From the documentation: `If the executable module is a 16-bit application, lpApplicationName should be NULL, and the string pointed to by lpCommandLine should specify the executable module as well as its arguments.` I don't know how many .NET 7 applications will be running 16-bit .exes though.

2. From the documentation: `If lpApplicationName is NULL, ... If the file name does not contain an extension, .exe is appended. Therefore, if the file name extension is .com, this parameter must include the .com extension. If the file name ends in a period (.) with no extension, or if the file name contains a path, .exe is not appended. If the file name does not contain a directory path, the system searches for the executable file in the following sequence.` None of this behavior is done when `lpApplicationName` is not null. I guess this could theoretically be worked around but it wouldn't be pretty.

3. `System.Diagnostics.Process` tries to always add double quotes around the module name, but it is not properly ensuring that this happens. For example, if the file name is `my exe` then it will properly quote it as `"my exe"`. But `"my" "exe"` will be left as is instead of properly escaping it to `"\"my\" \"exe\""`. On top of that, it currently accepts `"my exe"` as valid but if you pass `"C:\my exe.exe"` into `lpApplicationName` then `CreateProcessW` will literally look for `"C:\my exe.exe"` instead of `C:\my exe.exe`.

**Comment by danmoseley** [comment]
For (1) -- 16 bit support does not exist on 64 bit Windows. It's off by default on 32 bit Windows 10 apparently, and 32 bit Windows 11 doesn't exist. So at least in theory, it could safely work on those.

But for (2) and (3) .. that does seem risky as you say.

**Comment by danmoseley** [comment]
What about only following this code path when we know the path is too long and will fail anyway? Or, conversely, when process start has failed and we believe this is why (eg error 206 when path is prefixed with `\\?\`) then try again with the other code path?

**Comment by rseanhall** [comment]
We would have to assume people weren't doing something crazy like putting all the arguments in the file name. `"path\to\my.exe" assume all the arguments are longer than MAX_PATH "here"` for example.

**Comment by rseanhall** [comment]
Repro arguments for what exactly? All I was trying to point out was that because the current `System.Diagnostics.Process` code allows double quotes in the file name, it makes it impossible for us to tell whether the entire string is supposed to be the file name. So the `ProcessStartInfo.FileName` string might be more than MAX_PATH, but the actual file portion isn't. And if we try to parse the file name as if it's a command line, then we might run into issues because pathological cases like `my.exe" arg1 "arg2` can work today (that will be changed to `"my.exe" arg1 "arg2"` before passing it to `CreateProcess`).

**Comment by JeremyKuhne** [comment]
> Repro arguments for what exactly? 

@rseanhall your repro of the `MAX_PATH` problem.

**Comment by rseanhall** [comment]
This is a simplified repro. The actual test is running our native executable to verify we have removed MAX_PATH limitations from it. That is a work in progress and will eventually be at https://github.com/wixtoolset/wix4.

```c#
using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using Xunit;

namespace LongPathTests
{
    
    public class Process
    {
        [Fact]
        public void CanStartProcessFromLongPath()
        {
            const int subdirLength = 100;
            var baseFolder = Path.Combine(Path.GetTempPath(), new string('a', subdirLength), new string('b', subdirLength), new string('c', subdirLength));
            Directory.CreateDirectory(baseFolder);

            try
            {
                const string targetExe = "cmd.exe";
                var sourceFile = new FileInfo(Path.Combine(Environment.SystemDirectory, targetExe));
                var destFilePath = Path.Combine(baseFolder, targetExe);
                sourceFile.CopyTo(destFilePath);

                var exitCode = new Random().Next();
                var psi = new ProcessStartInfo(destFilePath, $"/c exit /b {exitCode}")
                {
                    CreateNoWindow = true,
                    RedirectStandardError = true,
                    RedirectStandardOutput = true,
                    UseShellExecute = false,
                    WorkingDirectory = string.Empty,
                };

                using (var process = Process.Start(psi))
                {
                    var standardOutput = new StringBuilder();
                    var standardError = new StringBuilder();

                    process.ErrorDataReceived += (s, e) => { if (e.Data != null) { standardError.AppendLine(e.Data); } };
                    process.OutputDataReceived += (s, e) => { if (e.Data != null) { standardOutput.AppendLine(e.Data); } };

                    process.BeginErrorReadLine();
                    process.BeginOutputReadLine();

                    process.WaitForExit();

                    if (exitCode != process.ExitCode)
                    {
                        Assert.True(false, $"Expected exit code {exitCode}, but got {process.ExitCode}.\r\nOutput: {standardOutput}\r\nError: {standardError}");
                    }
                }
            }
            finally
            {
                Directory.Delete(baseFolder, true);
            }
        }
    }
}
```

**Comment by rseanhall** [comment]
> There is definitely a MAX_PATH restriction on lpCurrentDirectory if you specify it (which the original description does).

Another thing to consider is that `CreateProcessW` tries to use the current directory of the current process if `lpCurrentDirectory` is NULL or an empty string. When long paths are enabled, the current directory can be longer than `MAX_PATH`. In this case, `CreateProcessW` returns `ERROR_INVALID_PARAMETER` (87). You have to pass in a valid path less than `MAX_PATH` to avoid this error.

**Comment by deeprobin** [comment]
Does this also occur if `lpCurrentDirectory` is not NULL and the current work directory is longer than `MAX_PATH`?

**Comment by deeprobin** [comment]
I took a look at what CreateProcessW does:
```
CreateProcessW 
-> stdcall into KernelBase.dll - CreateProcessW
-> fastcall to KernelBase.dll - CreateProcessInternalW
-> some logic and call into ntdll.dll NtCreateUserProcess
-> syscall into ntoskernl.exe
```

My assumption is that CreateProcessInternalW checks for `MAX_PATH`.
The method `NtCreateUserProcess` would accept a Unicode `PWSTR`. What is the policy here to call into undocumented APIs of the ntdll? I know that somewhere we already consume NT APIs.

**Comment by tannergooding** [comment]
We cannot consume APIs which are not publicly documented (generally this means documented on `docs.microsoft.com`).

They are not publicly available and are not meant for direct consumption. The have no guarantees, can be removed at any time, and are effectively "private implementation detail".

**Comment by loligans** [comment]
Taken from the documentation here: https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw#parameters

> `[in, out, optional] lpCommandLine`
> 
> The command line to be executed.
> 
> The maximum length of this string is 32,767 characters, including the Unicode terminating null character. If `lpApplicationName` is NULL, the module name portion of `lpCommandLine` is limited to MAX_PATH characters.

This suggests when `lpApplicationName` is NULL then the `lpCommandLine` is limited to `MAX_PATH`

Looking at the code for `System.Diagnostics.Process` it appears we pass `NULL` for `lpApplicationName` and I wonder if that could be what is triggering the `MAX_PATH` limit. Reference to places in code below.

Here:
https://github.com/dotnet/runtime/blob/07b6e338bb010b0dba1e72bdf546c69ade6f3f6c/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L555C33-L566C94

And Here:
https://github.com/dotnet/runtime/blob/07b6e338bb010b0dba1e72bdf546c69ade6f3f6c/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L583C29-L594C31

**Comment by loligans** [comment]
One potential fix would be to expose a property `ApplicationName` with a default value of `null` and use the property for setting the `lpApplicationName` field. That way developers can override the `ApplicationName` how they see fit and the existing functionality is preserved @danmoseley

**Comment by loligans** [comment]
I did some testing on my own and confirmed that adding `lpApplicationName` as well as `lpCommandLine` does not resolve the problem. `lpCurrentDirectory` is still limited by `MAX_PATH`. However, in addition I tested using the extended-length path prefix `\\?\` which correctly functions as a path string but it ironically does not allow paths longer than `MAX_PATH`.

Now if I pass a `ShortPath` string that resolves to a path longer than `MAX_PATH` it works correctly. https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew

Take the following 319-character longpath example:
> C:\tmp\longpathnamelongpathnamelongpathnamelongpathname\longpathnamelongpathnamelongpathnamelongpathname\longpathnamelongpathnamelongpathnamelongpathname\longpathnamelongpathnamelongpathnamelongpathnamelongpathnamelongpathnamelongpathnamelongpathn\longpathnamelongpathnamelongpathnamelongpath\longname\longname\longname

If I pass it to `GetShortPathName` I receive the following path:
> C:\tmp\LONGPA\~1\LONGPA\~1\LONGPA\~1\LONGPA\~1\LONGPA\~1\longname\longname\longname

Passing the short path into the `lpCurrentDirectory` will resolve to the full path and start the application correctly

I think this is a bug with `CreateProcessW` WinAPI and using short paths is simply a workaround.
