### ISSUE TITLE
dotnet-dump.dll fails if executed by corerun

### ISSUE THREAD

**Issue by o-lek** [dotnet/runtime#58515]
I've got a problem running dotnet-stack.dll by corerun:

I've build diagnostics from sources (branch main) and installed dotnet sdk 6.0.100-preview.7.21379.14

Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.TraceEvent, Version=2.0.64.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'Microsoft.Diagnostics.Tracing.TraceEvent, Version=2.0.64.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()

It seems like my diagnostics directory really doesn't have Microsoft.Diagnostics.Tracing.TraceEvent.dll,
but if I run dotnet-stack by dotnet - it works fine. What am I doing wrong?

**Comment by jkotas** [comment]
`corerun` is our internal host that is only used for testing. It is not guaranteed that the output of regular `dotnet build` can be launched using corerun.

> if I run dotnet-stack by dotnet - it works fine. What am I doing wrong?

Where does it fine `Microsoft.Diagnostics.Tracing.TraceEvent.dll`? You may need to manually copy `Microsoft.Diagnostics.Tracing.TraceEvent.dll` to a place where it can be found by corerun if you would like to run it using corerun.
