### ISSUE TITLE
Build workload artifacts step failing in official builds

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#58561]
```
light.exe : error LGHT0001: The wait completed due to an abandoned mutex. [D:\workspace\_work\1\s\src\workloads\workloads.csproj]
##[error]light.exe(0,0): error LGHT0001: (NETCORE_ENGINEERING_TELEMETRY=Build) The wait completed due to an abandoned mutex.
  
  Exception Type: System.Threading.AbandonedMutexException
  
  Stack Trace:
     at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
     at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
     at System.Threading.WaitHandle.WaitOne()
     at Microsoft.Tools.WindowsInstallerXml.Validator.Validate(String databaseFile)
     at Microsoft.Tools.WindowsInstallerXml.Binder.BindDatabase(Output output, String databaseFile)
     at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
     at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error MSB6006: "light.exe" exited with code -1073741819.
##[error]src\workloads\workloads.csproj(115,5): error MSB6006: (NETCORE_ENGINEERING_TELEMETRY=Build) "light.exe" exited with code -1073741819.
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : One or more errors occurred. (One or more errors occurred. (Failed to link MSI.)) (One or more errors occurred. (Failed to link MSI.)) (One or more errors occurred. (Failed to link MSI.))
##[error]src\workloads\workloads.csproj(115,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) One or more errors occurred. (One or more errors occurred. (Failed to link MSI.)) (One or more errors occurred. (Failed to link MSI.)) (One or more errors occurred. (Failed to link MSI.))
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : Failed to generate MSIs for workload packs.
##[error]src\workloads\workloads.csproj(115,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Failed to generate MSIs for workload packs.
  microsoft-net-runtime-macos platforms does not support Windows and will be skipped (osx-arm64, osx-x64).

Build FAILED.

D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error MSB6006: "light.exe" exited with code -1073741819.
light.exe : error LGHT0001: The wait completed due to an abandoned mutex. [D:\workspace\_work\1\s\src\workloads\workloads.csproj]
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error MSB6006: "light.exe" exited with code -1073741819.
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : One or more errors occurred. (One or more errors occurred. (Failed to link MSI.)) (One or more errors occurred. (Failed to link MSI.)) (One or more errors occurred. (Failed to link MSI.))
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : Failed to generate MSIs for workload packs.
    0 Warning(s)
    5 Error(s)
```

Happened in https://dev.azure.com/dnceng/internal/_build/results?buildId=1337505&view=logs&j=ad7bcd52-9916-5a50-47a2-92ef15ba97c4&t=8cee33e7-9c2d-5970-c8fa-131fff74a1fb

cc @steveisok

**Comment by ViktorHofer** [comment]
Another error in a previous official build with a different error message:

```
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : One or more errors occurred. (Index was outside the bounds of the array.) (Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.)
##[error]src\workloads\workloads.csproj(115,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) One or more errors occurred. (Index was outside the bounds of the array.) (Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.)
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : Failed to generate MSIs for workload packs.
##[error]src\workloads\workloads.csproj(115,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Failed to generate MSIs for workload packs.
  microsoft-net-runtime-macos platforms does not support Windows and will be skipped (osx-arm64, osx-x64).

Build FAILED.

D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : One or more errors occurred. (Index was outside the bounds of the array.) (Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.) (Index was outside the bounds of the array.)
D:\workspace\_work\1\s\src\workloads\workloads.csproj(115,5): error : Failed to generate MSIs for workload packs.
    0 Warning(s)
    2 Error(s)
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=1335300&view=logs&j=ad7bcd52-9916-5a50-47a2-92ef15ba97c4&t=8cee33e7-9c2d-5970-c8fa-131fff74a1fb&l=932

**Comment by ViktorHofer** [comment]
Failed again in https://dev.azure.com/dnceng/internal/_build/results?buildId=1332321&view=results

**Comment by joeloff** [comment]
Let me take a look, that's a first

**Comment by joeloff** [comment]
@lewing were there any changes recently to the manifests?

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/57270 appears to be the last change

**Comment by joeloff** [comment]
Did we take any Arcade updates? I think Peter might have made a change to deal with a file lock which added a mutex in one of the steps to parallelize the builds of the installers they saw with Android, but I've generally never had any luck with running multiple instances of WiX over the same source files at the same time.

**Comment by joeloff** [comment]
I wonder if parallelizing the commands is causing this. Long ago back in April when I started work on this I tried to speed up the builds in a similar fashion and ran into problems locally as well and ended up just making them sequential.

I wonder if https://github.com/dotnet/arcade/commit/c17de7fcb8e37291c7dff7e153cdabfdee4c5eb7#diff-ad9523f5675c0de8ffd78ea2a1b647033b2859cc9f2a25b9217f35cb6ed700c7 is what's causing issues for us

The problem is that we go from a single manifest to a single VS component and in-between that we have to extract, harvest, compile and link each MSI before we can add that information to the VS component authoring we generate, much of which depends on information we obtain at the various steps of each manifest.

**Comment by joeloff** [comment]
@ViktorHofer is this issue in all branches? I can prep a fix for Arcade, but for RC1 it gets tricky since we either take an Arcade update into runtime or revert the previous Arcade update in RC1 and take the fix in RC2/main

**Comment by lewing** [comment]
It doesn't look so frequent to me that we need to fix it for rc1 which shouldn't need many more builds.

**Comment by steveisok** [comment]
I would prefer we take the fix in RC2/main if we can.

**Comment by ViktorHofer** [comment]
Just ignore the RC1 branch which won't trigger builds for much longer (as we are close to its release).

I saw this failing only in the build that I provided but there could be more. Runfo should tell.

**Comment by steveisok** [comment]
Seems to be no longer happening.  Closing.
