### ISSUE TITLE
Test failure: PostAsyncNonDuplex_ServerCompletesResponseBodyThenResetsStreamWithNoError_SuccessAndRequestBodyCancelled

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#58624]
Test type: `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2`

Failures 3/12-9/3 (incl. PRs)

Day | Run | OS
-- | -- | --
3/17 | PR #49777 | Windows.10.Amd64.Server19H1.Open
3/23 | PR #49414 | OSX.1015.Amd64.Open
5/8 | PR #51772 | OSX.1015.Amd64.Open
6/12 | PR #53752 | OSX.1015.Amd64.Open
7/12 | PR #55493 | OSX.1015.Amd64.Open
7/23 | Official run | OSX.1014.Amd64.Open
8/17 | PR #57303 | Windows.81.Amd64.Open
9/2 | Official run - release/6.0 | OSX.1015.Amd64.Open

Failure:
```
System.Exception : Connection closed when expecting more data.

   at System.Net.Test.Common.Http2LoopbackConnection.FillBufferAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 149
   at System.Net.Test.Common.Http2LoopbackConnection.ReadFrameAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 186
   at System.Net.Test.Common.Http2LoopbackConnection.ReadFrameAsync(TimeSpan timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 161
   at System.Net.Test.Common.Http2LoopbackConnection.WaitForClientDisconnectAsync(Boolean ignoreUnexpectedFrames) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 315
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.PostAsyncNonDuplex_ServerCompletesResponseBodyThenResetsStreamWithNoError_SuccessAndRequestBodyCancelled() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 3027
--- End of stack trace from previous location ---
```

**Comment by rzikm** [comment]
No recent hits on main in last 60 days. Closing until it resurfaces
