### ISSUE TITLE
Serialization.Formatters.Tests - numerous failures with server GC

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#58642]
To repro:
```
> set COMPlus_gcServer=1
> pushd C:\dotnet002\runtime\artifacts\bin\System.Runtime.Serialization.Formatters.Tests\net6.0-windows-Release\
  "C:\dotnet002\runtime\artifacts\bin\testhost\net6.0-windows-Release-x64\dotnet.exe" exec --runtimeconfig System.Runtime.Serialization.Formatters.Tests.runtimeconfig.json --depsfile System.Runtime.Serialization.Formatters.Tests.deps.json xunit.console.dll System.Runtime.Serialization.Formatters.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing

```

I get lots of failures that look like:

```
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: name1=value, blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]
      The stored blob for type System.Net.Cookie is outdated and needs to be updated.

      -------------------- Stored blob ---------------------
      Encoded: AAEAAAD/////AQAAAAAAAAAMAgAAAElTeXN0ZW0sIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BQEAAAARU3lzdGVtLk5ldC5Db29raWUVAAAACW1fY29tbWVudAxtX2NvbW1lbnRVcmkPbV9jb29raWVWYXJpYW50CW1fZGlzY2FyZAhtX2RvbWFpbhFtX2RvbWFpbl9pbXBsaWNpdAltX2V4cGlyZXMGbV9uYW1lBm1fcGF0aA9tX3BhdGhfaW1wbGljaXQGbV9wb3J0D21fcG9ydF9pbXBsaWNpdAttX3BvcnRfbGlzdAhtX3NlY3VyZQptX2h0dHBPbmx5C21fdGltZVN0YW1wB21fdmFsdWUJbV92ZXJzaW9uC21fZG9tYWluS2V5D0lzUXVvdGVkVmVyc2lvbg5Jc1F1b3RlZERvbWFpbgEEBAABAAABAQABAAcAAAABAAEAAApTeXN0ZW0uVXJpAgAAABhTeXN0ZW0uTmV0LkNvb2tpZVZhcmlhbnQCAAAAAQENAQEIAQENCAEBAgAAAAYDAAAAAAoF/P///xhTeXN0ZW0uTmV0LkNvb2tpZVZhcmlhbnQBAAAAB3ZhbHVlX18ACAIAAAABAAAAAAYFAAAACTEyNy4wLjAuMQAAAAAAAAAAAAYGAAAABW5hbWUxBgcAAAAFL3BhdGgACQMAAAABCgAAgFhsCQ2+tQgGCQAAAAV2YWx1ZQAAAAAJAwAAAAAACw==
      Decoded:  ☺   ????☺       ♀☻   ISystem, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089♣☺   ◄System.Net.Cookie§          m_comment♀m_commentUri☼m_cookieVariant  m_discarm_domain◄m_domain_implicit     m_expires♠m_name♠m_path☼m_path_implicit♠m_port☼m_port_implicit♂m_port_lism_securem_httpOnly♂m_timeStampm_value  m_version♂m_domainKey☼IsQuotedVersion♫IsQuotedDomain☺♦♦ ☺  ☺☺ ☺    ☺ ☺  System.Uri☻   ↑System.Net.CookieVariant☻   ☺☺☺☺☻   ♠♥    ♣????↑System.Net.CookieVariant☺   value__☻   ☺    ♠♣          127.0.0.1         ♠♠   ♣name1♠   ♣/path         ♥   ☺  ?Xl      ?♠         ♣value       ♥     ♂

      --------------- Runtime generated blob ---------------
      Encoded: AAEAAAD/////AQAAAAAAAAAMAgAAAElTeXN0ZW0sIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BQEAAAARU3lzdGVtLk5ldC5Db29raWUVAAAAC21fdGltZVN0YW1wCW1fY29tbWVudAxtX2NvbW1lbnRVcmkPbV9jb29raWVWYXJpYW50CW1fZGlzY2FyZAhtX2RvbWFpbhFtX2RvbWFpbl9pbXBsaWNpdAltX2V4cGlyZXMGbV9uYW1lBm1fcGF0aA9tX3BhdGhfaW1wbGljaXQGbV9wb3J0D21fcG9ydF9pbXBsaWNpdAttX3BvcnRfbGlzdAhtX3NlY3VyZQptX2h0dHBPbmx5B21fdmFsdWUJbV92ZXJzaW9uC21fZG9tYWluS2V5D0lzUXVvdGVkVmVyc2lvbg5Jc1F1b3RlZERvbWFpbgABBAQAAQAAAQEAAQAHAAABAAEAAA0KU3lzdGVtLlVyaQIAAAAYU3lzdGVtLk5ldC5Db29raWVWYXJpYW50AgAAAAEBDQEBCAEBCAEBAgAAAIBYbAkNvrUIBgMAAAAACgX8////GFN5c3RlbS5OZXQuQ29va2llVmFyaWFudAEAAAAHdmFsdWVfXwAIAgAAAAEAAAAABgUAAAAJMTI3LjAuMC4xAAAAAAAAAAAABgYAAAAFbmFtZTEGBwAAAAUvcGF0aAAJAwAAAAEKAAAGCQAAAAV2YWx1ZQAAAAAJAwAAAAAACw==
      Decoded:  ☺   ????☺       ♀☻   ISystem, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089♣☺   ◄System.Net.Cookie§   ♂m_timeStamp   m_comment♀m_commentUri☼m_cookieVariant  m_discarm_domain◄m_domain_implicit     m_expires♠m_name♠m_path☼m_path_implicit♠m_port☼m_port_implicit♂m_port_lism_securem_httpOnlym_value      m_version♂m_domainKey☼IsQuotedVersion♫IsQuotedDomain ☺♦♦ ☺  ☺☺ ☺   ☺ ☺  System.Uri☻   ↑System.Net.CookieVariant☻   ☺☺☺☺☻   ?Xl ?♠♥    ♣????↑System.Net.CookieVariant☺   value_☻   ☺    ♠♣      127.0.0.1         ♠♠   ♣name1♠   ♣/path         ♥   ☺  ♠           ♣value       ♥     ♂
      Expected: True
      Actual:   False
      Stack Trace:
        C:\dotnet002\runtime\src\libraries\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(601,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SanityCheckBlob(Object obj, TypeSerializableValue[] blobs)
        C:\dotnet002\runtime\src\libraries\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(110,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAndRoundtrip(Object obj, TypeSerializableValue[] blobs, Boolean isEqualityComparer)
        C:\dotnet002\runtime\src\libraries\System.Runtime.Serialization.Formatters\tests\BinaryFormatterTests.cs(72,0): at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(Object obj, TypeSerializableValue[] blobs)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: [name1=value], blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]
      The stored blob for type System.Net.CookieCollection is outdated and needs to be updated.

      -------------------- Stored blob ---------------------
      Encoded: AAEAAAD/////AQAAAAAAAAAMAgAAAElTeXN0ZW0sIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BQEAAAAbU3lzdGVtLk5ldC5Db29raWVDb2xsZWN0aW9uBAAAAAZtX2xpc3QJbV92ZXJzaW9uC21fVGltZVN0YW1wFG1faGFzX290aGVyX3ZlcnNpb25zAwAAABxTeXN0ZW0uQ29sbGVjdGlvbnMuQXJyYXlMaXN0CA0BAgAAAAkDAAAAAQAAAAAAAAAAAAAAAAQDAAAAHFN5c3RlbS5Db2xsZWN0aW9ucy5BcnJheUxpc3QDAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgUAAAgICQQAAAABAAAAAQAAABAEAAAABAAAAAkFAAAADQMFBQAAABFTeXN0ZW0uTmV0LkNvb2tpZRUAAAAJbV9jb21tZW50DG1fY29tbWVudFVyaQ9tX2Nvb2tpZVZhcmlhbnQJbV9kaXNjYXJkCG1fZG9tYWluEW1fZG9tYWluX2ltcGxpY2l0CW1fZXhwaXJlcwZtX25hbWUGbV9wYXRoD21fcGF0aF9pbXBsaWNpdAZtX3BvcnQPbV9wb3J0X2ltcGxpY2l0C21fcG9ydF9saXN0CG1fc2VjdXJlCm1faHR0cE9ubHkLbV90aW1lU3RhbXAHbV92YWx1ZQltX3ZlcnNpb24LbV9kb21haW5LZXkPSXNRdW90ZWRWZXJzaW9uDklzUXVvdGVkRG9tYWluAQQEAAEAAAEBAAEABwAAAAEAAQAAClN5c3RlbS5VcmkCAAAAGFN5c3RlbS5OZXQuQ29va2llVmFyaWFudAIAAAABAQ0BAQgBAQ0IAQECAAAABgYAAAAACgX5////GFN5c3RlbS5OZXQuQ29va2llVmFyaWFudAEAAAAHdmFsdWVfXwAIAgAAAAEAAAAABggAAAAJMTI3LjAuMC4xAAAAAAAAAAAABgkAAAAFbmFtZTEGCgAAAAUvcGF0aAAJBgAAAAEKAACAWGwJDb61CAYMAAAABXZhbHVlAAAAAAkGAAAAAAAL
      Decoded:  ☺   ????☺       ♀☻   ISystem, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089♣☺   ←System.Net.CookieCollection♦   ♠m_list      m_version♂m_TimeStamp¶m_has_other_versions♥   ∟System.Collections.ArrayLis☺☻           ♥   ☺            ♦♥   ∟System.Collections.ArrayList♥   ♠_items♣_siz_versio      ♦   ☺   ☺   ►♦   ♦      ♣   ♥♣♣   ◄System.Net.Cookie§           m_comment♀m_commentUri☼m_cookieVariant m_discarm_domain◄m_domain_implicit      m_expires♠m_name♠m_path☼m_path_implicit♠m_port☼m_port_implicit♂m_port_lism_securem_httpOnly♂m_timeStampm_value  m_version♂m_domainKey☼IsQuotedVersion♫IsQuotedDomain☺♦♦ ☺  ☺☺ ☺    ☺ ☺  System.Uri☻   ↑System.Net.CookieVariant☻   ☺☺☺☺☻   ♠♠    ♣????↑System.Net.CookieVariant☺   value__☻   ☺        127.0.0.1         ♠        ♣name1♠   ♣/path     ♠   ☺  ?Xl
        ?♠♀   ♣value            ♠     ♂

      --------------- Runtime generated blob ---------------
      Encoded: AAEAAAD/////AQAAAAAAAAAMAgAAAElTeXN0ZW0sIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BQEAAAAbU3lzdGVtLk5ldC5Db29raWVDb2xsZWN0aW9uBAAAAAZtX2xpc3QJbV92ZXJzaW9uC21fVGltZVN0YW1wFG1faGFzX290aGVyX3ZlcnNpb25zAwAAABxTeXN0ZW0uQ29sbGVjdGlvbnMuQXJyYXlMaXN0CA0BAgAAAAkDAAAAAQAAAAAAAAAAAAAAAAQDAAAAHFN5c3RlbS5Db2xsZWN0aW9ucy5BcnJheUxpc3QDAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgUAAAgICQQAAAABAAAAAQAAABAEAAAABAAAAAkFAAAADQMFBQAAABFTeXN0ZW0uTmV0LkNvb2tpZRUAAAALbV90aW1lU3RhbXAJbV9jb21tZW50DG1fY29tbWVudFVyaQ9tX2Nvb2tpZVZhcmlhbnQJbV9kaXNjYXJkCG1fZG9tYWluEW1fZG9tYWluX2ltcGxpY2l0CW1fZXhwaXJlcwZtX25hbWUGbV9wYXRoD21fcGF0aF9pbXBsaWNpdAZtX3BvcnQPbV9wb3J0X2ltcGxpY2l0C21fcG9ydF9saXN0CG1fc2VjdXJlCm1faHR0cE9ubHkHbV92YWx1ZQltX3ZlcnNpb24LbV9kb21haW5LZXkPSXNRdW90ZWRWZXJzaW9uDklzUXVvdGVkRG9tYWluAAEEBAABAAABAQABAAcAAAEAAQAADQpTeXN0ZW0uVXJpAgAAABhTeXN0ZW0uTmV0LkNvb2tpZVZhcmlhbnQCAAAAAQENAQEIAQEIAQECAAAAgFhsCQ2+tQgGBgAAAAAKBfn///8YU3lzdGVtLk5ldC5Db29raWVWYXJpYW50AQAAAAd2YWx1ZV9fAAgCAAAAAQAAAAAGCAAAAAkxMjcuMC4wLjEAAAAAAAAAAAAGCQAAAAVuYW1lMQYKAAAABS9wYXRoAAkGAAAAAQoAAAYMAAAABXZhbHVlAAAAAAkGAAAAAAAL
      Decoded:  ☺   ????☺       ♀☻   ISystem, Version=0.0.0.0 Culture=neutral, PublicKeyToken=b77a5c561934e089♣☺   ←System.Net.CookieCollection♦   ♠m_list      m_version♂m_TimeStamp¶m_has_other_versions♥   ∟System.Collections.ArrayLis☺☻           ♥   ☺            ♦♥   ∟System.Collections.ArrayList♥   ♠_items♣_siz_versio      ♦   ☺   ☺   ►♦   ♦      ♣   ♥♣♣   ◄System.Net.Cookie§   ♂m_timeStamp    m_comment♀m_commentUri☼m_cookieVariant m_discarm_domain◄m_domain_implicit      m_expires♠m_name♠m_path☼m_path_implicit♠m_port☼m_port_implicit♂m_port_lism_securem_httpOnlym_value      m_version♂m_domainKey☼IsQuotedVersion♫IsQuotedDomain ☺♦♦ ☺  ☺☺ ☺   ☺ ☺  System.Uri☻   ↑System.Net.CookieVariant☻   ☺☺☺☺☻   ?Xl ?♠♠    ♣????↑System.Net.CookieVariant☺   value__☻   ☺           127.0.0.1         ♠        ♣name1♠   ♣/path     ♠   ☺  ♠♀   ♣value     ♠     ♂
```

This is not a GC test so it should not be sensitive to GC flavor.

**Comment by danmoseley** [comment]
How curious, do you have an idea how the GC could possibly affect this? As far as I know there's no concurrency. It's as if the ordering in a hash table changed, eg.

Does this matter -- do you have a way to disable for server GC? We will likely remove BinaryFormatter tests as we obsolete it away.

**Comment by steveharter** [comment]
I believe this is related to https://github.com/dotnet/runtime/issues/46272#issuecomment-1109019672 where field ordering is non-deterministic.

**Comment by dakersnar** [comment]
I believe this is the correct area label, but let me know if it is not

**Comment by danmoseley** [comment]
@dakersnar unless there was separate discussion, it's not clear to me that a GC change is expected here. apparently binary formatter relies on the ordering that reflection returns stuff, and that was not stable until https://github.com/dotnet/runtime/pull/69506

The tests are owned by System.Runtime label as they test BinaryFormatter which is in System.Runtime.Serialization.Formatters -- https://github.com/dotnet/runtime/blob/main/docs/area-owners.md

My guess is that these tests may well be fixed, or at least consistent, since https://github.com/dotnet/runtime/pull/69506 and this issue can simply be closed.

**Comment by dakersnar** [comment]
Noted, thanks for the explanation. I think in that case we can close this issue.
