### ISSUE TITLE
[wasm][aot] Windows: Test failures for `System.IO.FileSystem.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#58707]
PR to enable AOT tests on windows: https://github.com/dotnet/runtime/pull/58578a

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1344204&view=logs&j=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&t=57689805-9064-5d56-984a-6ae89a8efb73)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58578-merge-bacb37a0e62d4c33a9/System.IO.FileSystem.Tests/1/console.f7f71b8e.log?sv=2019-07-07&se=2021-09-26T01%3A39%3A40Z&sr=c&sp=rl&sig=GwFCOO3sqL7iYknbzkJ9Xu8b3ANVZLQ%2BWZ8%2Fz2pQW%2BY%3D)

```
[02:34:11] fail: [FAIL] System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData(data: ['è', 'f', 'à', 'Ù', 0x008c, ...], readOnly: True)
[02:34:11] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:34:11] info:    at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
[02:34:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:34:11] fail: [FAIL] System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData(data: ['V', 'O', '}', 0x0094, '"', ...], readOnly: True)
[02:34:11] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:34:11] info:    at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
[02:34:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:34:11] fail: [FAIL] System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData(data: ['*', '4', 0x0018, 0x007f, 0x000e, ...], readOnly: True)
[02:34:11] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:34:11] info:    at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
[02:34:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:34:11] fail: [FAIL] System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData(data: ['|', '^', 0x0015, 'J', 0x009e, ...], readOnly: False)
[02:34:11] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:34:11] info:    at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
[02:34:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:34:11] fail: [FAIL] System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData(data: [0x0010, 0x0090, 'í', 'é', '¸', ...], readOnly: False)
[02:34:11] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:34:11] info:    at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
[02:34:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:34:11] fail: [FAIL] System.IO.Tests.FileInfo_CopyTo_str.CopyFileWithData(data: [0x0003, 'R', 'Ð', '0', 0x00b2, ...], readOnly: False)
[02:34:11] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:34:11] info:    at System.IO.Tests.File_Copy_str_str.CopyFileWithData(Char[] data, Boolean readOnly)
[02:34:11] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:34:35] info: Finished:    System.IO.FileSystem.Tests.dll
[02:34:35] info: 
[02:34:35] info: === TEST EXECUTION SUMMARY ===
[02:34:35] info: Total: 4948, Errors: 0, Failed: 6, Skipped: 158, Time: 33.631588s
```

**Comment by radical** [comment]
cc @lewing @radekdoulik

**Comment by ilonatommy** [comment]
@radekdoulik, are we able to fix it in 7.0?

**Comment by radical** [comment]
@ilonatommy do these tests still fail? Has the failure changed?

**Comment by ilonatommy** [comment]
You're right, running `dotnet build /t:Test src/libraries/System.IO.FileSystem/tests /p:TargetOS=Browser /p:Configuration=Release /p:RunAOTCompilation=true` results in [PASS] for all 48 kinds of `CopyFileWithData`.
