### ISSUE TITLE
[wasm][aot] Windows: Test failures for `System.Globalization.Extensions.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#58708]
PR to enable AOT tests on windows: https://github.com/dotnet/runtime/pull/58578

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1344204&view=logs&j=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&t=57689805-9064-5d56-984a-6ae89a8efb73)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58578-merge-bacb37a0e62d4c33a9/System.Globalization.Extensions.Tests/1/console.733e9e06.log?sv=2019-07-07&se=2021-09-26T01%3A39%3A40Z&sr=c&sp=rl&sig=GwFCOO3sqL7iYknbzkJ9Xu8b3ANVZLQ%2BWZ8%2Fz2pQW%2BY%3D)

```
[02:31:36] fail: [FAIL] System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Success
[02:31:36] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:31:36] info:    at System.Globalization.Tests.Factory.ParseFile(Stream stream, Func`3 f)+MoveNext()
[02:31:36] info:    at System.Globalization.Tests.Factory.GetDataset()+MoveNext()
[02:31:36] info:    at System.Linq.Enumerable.WhereEnumerableIterator`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
[02:31:37] info:    at System.Collections.Generic.LargeArrayBuilder`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].AddRange(IEnumerable`1 )
[02:31:37] info:    at System.Collections.Generic.EnumerableHelpers.ToArray[IConformanceIdnaTest](IEnumerable`1 )
[02:31:37] info:    at System.Linq.Enumerable.ToArray[IConformanceIdnaTest](IEnumerable`1 source)
[02:31:37] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:31:37] fail: [FAIL] System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Success
[02:31:37] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:31:37] info:    at System.Globalization.Tests.Factory.ParseFile(Stream stream, Func`3 f)+MoveNext()
[02:31:37] info:    at System.Globalization.Tests.Factory.GetDataset()+MoveNext()
[02:31:37] info:    at System.Linq.Enumerable.WhereEnumerableIterator`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
[02:31:37] info:    at System.Collections.Generic.LargeArrayBuilder`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].AddRange(IEnumerable`1 )
[02:31:37] info:    at System.Collections.Generic.EnumerableHelpers.ToArray[IConformanceIdnaTest](IEnumerable`1 )
[02:31:37] info:    at System.Linq.Enumerable.ToArray[IConformanceIdnaTest](IEnumerable`1 source)
[02:31:37] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:31:37] fail: [FAIL] System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid
[02:31:37] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:31:37] info:    at System.Globalization.Tests.Factory.ParseFile(Stream stream, Func`3 f)+MoveNext()
[02:31:37] info:    at System.Globalization.Tests.Factory.GetDataset()+MoveNext()
[02:31:37] info:    at System.Linq.Enumerable.WhereEnumerableIterator`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
[02:31:37] info:    at System.Collections.Generic.LargeArrayBuilder`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].AddRange(IEnumerable`1 )
[02:31:37] info:    at System.Collections.Generic.EnumerableHelpers.ToArray[IConformanceIdnaTest](IEnumerable`1 )
[02:31:37] info:    at System.Linq.Enumerable.ToArray[IConformanceIdnaTest](IEnumerable`1 source)
[02:31:37] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:31:37] fail: [FAIL] System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid
[02:31:37] info: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
[02:31:37] info:    at System.Globalization.Tests.Factory.ParseFile(Stream stream, Func`3 f)+MoveNext()
[02:31:37] info:    at System.Globalization.Tests.Factory.GetDataset()+MoveNext()
[02:31:37] info:    at System.Linq.Enumerable.WhereEnumerableIterator`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
[02:31:37] info:    at System.Collections.Generic.LargeArrayBuilder`1[[System.Globalization.Tests.IConformanceIdnaTest, System.Globalization.Extensions.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].AddRange(IEnumerable`1 )
[02:31:37] info:    at System.Collections.Generic.EnumerableHelpers.ToArray[IConformanceIdnaTest](IEnumerable`1 )
[02:31:37] info:    at System.Linq.Enumerable.ToArray[IConformanceIdnaTest](IEnumerable`1 source)
[02:31:37] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[02:31:42] info: Finished:    System.Globalization.Extensions.Tests.dll
[02:31:42] info: 
[02:31:42] info: === TEST EXECUTION SUMMARY ===
[02:31:42] info: Total: 290, Errors: 0, Failed: 4, Skipped: 0, Time: 6.257763s
```

**Comment by radical** [comment]
cc @lewing @radekdoulik
