### ISSUE TITLE
SendPacketsElement_FileStreamMultiPartMixed_MultipleFileStreams_Success failed on windows.11.amd64.clientpre.open

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#58898]
[console logs](https://helix.dot.net/api/2019-06-17/jobs/e457674b-7219-466a-98c7-d70d9c28d450/workitems/System.Net.Sockets.Tests/console)

```cmd
Console log: 'System.Net.Sockets.Tests' from job e457674b-7219-466a-98c7-d70d9c28d450 workitem 92e9af85-9f63-4cdc-ac3e-0569378e4d26 (windows.11.amd64.clientpre.open) executed on machine a0000GB
[snip]
C:\h\w\9FFD08CE\w\B423098F\e>"C:\h\w\9FFD08CE\p\dotnet.exe" exec --runtimeconfig System.Net.Sockets.Tests.runtimeconfig.json --depsfile System.Net.Sockets.Tests.deps.json xunit.console.dll System.Net.Sockets.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 1305 of 1676 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 2)
    System.Net.Sockets.Tests.KeepAliveTest.Socket_KeepAlive_RetryCount_Failure [SKIP]
      Condition(s) not met: "IsWindowsBelow1703"
    System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_CreateUnixDomainSocket_Throws_OnWindows [SKIP]
      Condition(s) not met: "IsSubWindows10"
    System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FileStreamMultiPartMixed_MultipleFileStreams_Success [FAIL]
      Timed out
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs(693,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SendPacketsElement[] elements, SocketError expectedResult, Int32 bytesExpected, Byte[] contentExpected)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs(598,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FileStreamMultiPartMixed_MultipleFileStreams_Success()
```

**Comment by karelz** [comment]
@antonfirsov can you help with this one? It seems to fail in CI on Win11.

**Comment by aik-jahoda** [comment]
Test disabled in #59203 to suppress CI noise. We should fix/investigate the timeout soon ideally prior backport to 6.0

**Comment by antonfirsov** [comment]
Failures are not specific to the test case mentioned, disabling 2 more cases in #59359.

**Comment by wfurt** [comment]
looks similar to  #51651. Probably just timing....?

**Comment by antonfirsov** [comment]
The following code timeouts (hangs) regardless of the timeout value being used:

```C#
string tempFile = Path.GetTempFileName();
byte[] content = new byte[1024];
File.WriteAllBytes(tempFile, content);
using FileStream fileStream1 = new FileStream(tempFile, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, FileOptions.Asynchronous);
using FileStream fileStream2 = new FileStream(tempFile, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, FileOptions.Asynchronous);

using Socket listener = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
listener.Bind(new IPEndPoint(IPAddress.Loopback, 0));
int port = ((IPEndPoint)listener.LocalEndPoint).Port;
listener.Listen();

EventWaitHandle completed = new ManualResetEvent(false);
using Socket client = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
client.Connect(new IPEndPoint(IPAddress.Loopback, port));
using Socket server = listener.Accept();

for (int i = 0; i < 10_000; i++)
{
    completed.Reset();

    using SocketAsyncEventArgs args = new SocketAsyncEventArgs();

    args.Completed += static (_, e) => ((EventWaitHandle)e.UserToken).Set();
    args.UserToken = completed;
    args.SendPacketsElements = GetElements();

    if (client.SendPacketsAsync(args))
    {
        if (!completed.WaitOne(30_000))
        {
            throw new Exception($"Timed out @ {i}");
        }
    }
}

SendPacketsElement[] GetElements()
{
    const int N = 64;
    int part = (int)fileStream1.Length / N;
    SendPacketsElement[] result = new SendPacketsElement[N];
    for (int i = 0; i < result.Length; i++)
    {
        result[i] = new SendPacketsElement(i % 2 == 0 ? fileStream1 : fileStream2, i * part, 10);
    }
    return result;
}
```

It needs different amount of itereations on different platforms:
- On Windows 10: 4094 iterations
- On Windows 11: 3479 iterations
- Ubuntu (surprisingly): 858 iterations

I don't understand why don't we see any Linux failures in CI, but it's possible that some internal winsock tuning made a bug visible on Windows 11.

@wfurt I wonder if you can spot something incorrect / unusual in my repro code, or are we safe to declare this as a bug?

**Comment by danmoseley** [comment]
This now failed on `net6.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open` as well. -- https://github.com/dotnet/runtime/issues/58898

@antonfirsov per links above there's several failures in 2 days on release/6.0.
