### ISSUE TITLE
Test failure CtorAndAccept_SocketNotKeptAliveViaInheritance

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#58903]
Test type: `System.Net.Sockets.Tests.CreateSocket`

Failures 3/12-9/10 (incl. PRs):

Day | Run | OS | Failure
-- | -- | -- | --
4/8 | PR #50893 | OSX.1014.Amd64.Open - CoreCLR | Assert: Expected: False / Actual: True
9/9 | PR #58841 (off release/6.0) | Fedora.34.Amd64.Open - Mono | Timeout

Failure in unrelated release/6.0 backport PR #58841:
```
System.Net.Sockets.Tests.CreateSocket.CtorAndAccept_SocketNotKeptAliveViaInheritance(validateClientOuter: True, acceptApiOuter: 0) [FAIL]
      Half-way through waiting for remote process.
      Timed out at 9/9/2021 4:52:19 PM after 60000ms waiting for remote process.
      	Process ID: 233
      	Handle: 2214
      	Name: dotnet
      	MainModule: /root/helix/work/correlation/dotnet
      	StartTime: 9/9/2021 4:51:19 PM
      	TotalProcessorTime: 00:00:00.2800000
      
      Stack Trace:
           at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
           at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/CreateSocketTests.cs(141,0): at System.Net.Sockets.Tests.CreateSocket.CtorAndAccept_SocketNotKeptAliveViaInheritance(Boolean validateClientOuter, Int32 acceptApiOuter)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(370,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

Unhandled Exception:
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 42
Actual:   -1
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual)
   at System.Net.Sockets.Tests.CreateSocket.<>c.<CtorAndAccept_SocketNotKeptAliveViaInheritance>b__16_1(String clientPipeHandle) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/CreateSocketTests.cs:line 178
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 42
Actual:   -1
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual)
   at System.Net.Sockets.Tests.CreateSocket.<>c.<CtorAndAccept_SocketNotKeptAliveViaInheritance>b__16_1(String clientPipeHandle) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/CreateSocketTests.cs:line 178
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1352372&view=logs&j=b4344b0d-0f92-5d69-ccaf-e0b24fbf14a2&t=65a58faa-a542-5344-b5c8-897139f242cd
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58841-merge-d9fc5574e9d543958d/System.Net.Sockets.Tests/1/console.b7ea1d4a.log?sv=2019-07-07&se=2021-09-29T16%3A29%3A55Z&sr=c&sp=rl&sig=1d%2BnE1EhI1m1ZXt7En1n1oOzhShN1ydF5tgIwkB4B2Y%3D

Failure on 4/8 in PR #50893:
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Child exception:
  Xunit.Sdk.FalseException: Assert.False() Failure
Expected: False
Actual:   True
   at System.Net.Sockets.Tests.CreateSocket.<>c.<CtorAndAccept_SocketNotKeptAliveViaInheritance>b__16_0(String validateClientString, String acceptApiString) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/CreateSocketTests.cs:line 208

Child process:
  System.Net.Sockets.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.CreateSocket+<>c Void <CtorAndAccept_SocketNotKeptAliveViaInheritance>b__16_0(System.String, System.String)

Child arguments:
  False, 2
```

**Comment by karelz** [comment]
Closing for now due to very low failure rate.
