### ISSUE TITLE
Test Failure UnixPingUtilityTests.TimeoutIsRespected in macOS beta 8

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#58946]
This test is failing in macOS 12 beta 8

```
[xUnit.net 00:00:00.62]     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 100) [FAIL]
[xUnit.net 00:00:00.63]     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 1000) [FAIL]
[xUnit.net 00:00:00.63]     System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 1500) [FAIL]
  Failed System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 100) [38 ms]
  Error Message:
   Assert.InRange() Failure
Range:  (90 - 5000)
Actual: 37
  Stack Trace:
     at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(Int32 timeout) in /Users/kjones/Projects/dotnet/runtime-main/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 41
  Failed System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 1000) [65 ms]
  Error Message:
   Assert.InRange() Failure
Range:  (990 - 5000)
Actual: 65
  Stack Trace:
     at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(Int32 timeout) in /Users/kjones/Projects/dotnet/runtime-main/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 41
  Failed System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(timeout: 1500) [38 ms]
  Error Message:
   Assert.InRange() Failure
Range:  (1490 - 5000)
Actual: 38
  Stack Trace:
     at System.Net.NetworkInformation.Tests.UnixPingUtilityTests.TimeoutIsRespected(Int32 timeout) in /Users/kjones/Projects/dotnet/runtime-main/src/libraries/System.Net.Ping/tests/FunctionalTests/UnixPingUtilityTests.cs:line 41
```

<details>
<summary>dotnet --info</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21430.12
 Commit:    2b28e04218

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /Users/kjones/Projects/dotnet/runtime-main/.dotnet/sdk/6.0.100-rc.1.21430.12/

Host (useful for support):
  Version: 6.0.0-rc.1.21430.1
  Commit:  38e07e093e

.NET SDKs installed:
  6.0.100-rc.1.21430.12 [/Users/kjones/Projects/dotnet/runtime-main/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21430.5 [/Users/kjones/Projects/dotnet/runtime-main/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21430.1 [/Users/kjones/Projects/dotnet/runtime-main/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by vcsjones** [comment]
This turned out to be an issue on my end. The "unreachable" address that is used for testing 192.0.2.0. However, that address is reachable on my network, so it never timed out.

Using an unreachable address (for me), the test passed as expected.
