### ISSUE TITLE
Custom equality operator in generic expressions provoke BadImageFormatExceptions

### ISSUE THREAD

**Issue by danielcweber** [dotnet/runtime#59035]
### Description

The following minimal repro (available [here](https://github.com/danielcweber/BadImageFormatExceptionRepro) as well) will throw a `BadImageFormatException` and it's unclear what the unsupported expression is, why it's unsupported, and how it can be avoided, which is why I consider it a bug:

```
using System;
using System.Linq.Expressions;

namespace BadImageFormatExceptionRepro
{
    class Program
    {
        private readonly struct Wrapper<T>
        {
            public static bool operator ==(T t, Wrapper<T> wrapper) => true;

            public static bool operator !=(T t, Wrapper<T> wrapper) => false;
        }

        private interface IInterface<T>
        {
            void InterfaceMethod(Expression<Func<T, bool>> expression);
        }

        static void Main()
        {
            GenericMethod<string>();
        }

        private static void GenericMethod<T>() where T : class
        {
            Action<IInterface<T>, Wrapper<T>> func = (iface, wrapper) => iface
                .InterfaceMethod(x => x == wrapper);

            func(default, default);
        }
    }
}
```

Expected behaviour: The delegate `func` being run (which would throw a NRE in the process, but this is secondary here). 

Actual behaviour: The delegate isn't run, at least the breakpoint isn't hit. Instead, a `BadImageFormatException` is thrown.

Stack trace:
```
   at BadImageFormatExceptionRepro.Program.<>c__3`1.<GenericMethod>b__3_0(IInterface`1 iface, Wrapper`1 wrapper) in C:\Github\BadImageFormatExceptionRepro\BadImageFormatExceptionRepro\Program.cs:line 27
   at BadImageFormatExceptionRepro.Program.GenericMethod[T]() in C:\Github\BadImageFormatExceptionRepro\BadImageFormatExceptionRepro\Program.cs:line 30
   at BadImageFormatExceptionRepro.Program.Main() in C:\Github\BadImageFormatExceptionRepro\BadImageFormatExceptionRepro\Program.cs:line 22
```

Which version of .NET is the code running on?
.net5.0, .net6.0. Actually, experimenting with this [in SharpLab](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWAChMAGAAk1wDoAZAS1QEcqBRMAB0QFMBnHugPaoeAbiJFUAQwC2vdpIDGXMgCFJAEwCS0yQHMuAMQGIdcNkvZxBqAEpdOAogG8iZNxWwVcAdlfuXhO5BZJx0AG6ScMrcGkIANgCeZDxwKApwZADqiJLs7FyIADwAKgB8fsFkAZWVmADMXhBkwAICcWQC+TlwxmQAvH0AFMVkcDBZOXkFJaVkAO6TXQCU/bOpyFxihBU1bvWNza3tnQWRvQCEQyNjE7ldM/OLBSt9swBmknE8mztBAL7iQI1UIRKJkBhRRAfJRkTSaVCQ6FcGa/fyo2pQWEIgpIgCyXDgAAsBOpBmxOLx+EJCpgAKwlcYtNqlWZcDjcPjWJYiMjosgA7ZA2q4JqYTG4yQMQZLPnVXbuADiXFQBToCnxRJJNNwJFK0q2uwFfJBkWUlFFmKVKsQao1xPUM2l80JBWUIxAHllfKClGwhTh2KhimRZXG2Tu0zK7zQCn6ZEGdCR4wWEcQL1mieD3pqVHhiODdpJgzAqzIJYGj1T3MB8vcbxjg3UXA+yDiNybLbb1aFwQF/yIAqAA===) I could not find a working configuration.

What OS and version, and what distro if applicable?
Windows.

What is the architecture (x64, x86, ARM, ARM64)?
x64

Do you know whether it is specific to that configuration?
I assume it's not.

**Comment by tfenise** [comment]
Looks like a bug in Roslyn to me.

In [https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyAMABMugHQAyYAdgI4kCiAHgA4BOApgM4dgD2lHAbhw5KAQwC2nJqIDGbAgCFRMAJLjRAczYAxHi3XBGcpsF6UASm1Y8cAbxwFHRVEXQB2B0/vYnvgqzAAN1FgeXZlPggATwIOYBYAVxlgAgB1FlEmJjYWAB4AFQA+Tz8Cb1LS5ABmVwA2AgAjHh4IAh5sjOA9AgBeHoAKfIJgKDSMrJyCwoIAd3GOgEpe6fiEtiFsEorHarrG5tb2nJDugEIBoZGxzI6p2fmcpZ7pgDNRCA51rd8AX2EfCoBYKhAhUUIsN5yAgqFSUcGQthTb5eZGVAAs0LhOQRAFk2MAABY8GD9RisTjcPi5ZAAVgKoyaLUK0zYzHYXDMCwEBFRBD+mwBlXQ9WQGJxoio/QWvPK2ycAHE2JQcmAZHjCcTqeg8IUpRttvzeUCQvJiCKMYrlSxVeqiTAplLZgScvIhiBnDLeb5iKhcjCsRDZIiiqN0jdJkVXglKDJegR+mAEaM5uGWE9pomg16KiRYfCg7bif0GMsCCW+vdU1z/nKnC9ozJ+jA2G8EhArs3W+3q4K/Pzfjh+UA===](url),
```
    .class nested private auto ansi sealed serializable beforefieldinit '<>c__3`1'<class T>
        extends [System.Private.CoreLib]System.Object
    {
        ...

        .method assembly hidebysig 
            instance void '<GenericMethod>b__3_0' (
                class BadImageFormatExceptionRepro.Program/IInterface`1<!T> iface,
                valuetype BadImageFormatExceptionRepro.Program/Wrapper`1<!T> 'wrapper'
            ) cil managed 
        {
            // Method begins at RVA 0x20b8
            // Code size 120 (0x78)
            .maxstack 6
            .locals init (
                [0] class BadImageFormatExceptionRepro.Program/'<>c__DisplayClass3_0`1'<!T> 'CS$<>8__locals0',
                [1] class [System.Linq.Expressions]System.Linq.Expressions.ParameterExpression
            )

            // sequence point: hidden
            IL_0000: newobj instance void class BadImageFormatExceptionRepro.Program/'<>c__DisplayClass3_0`1'<!T>::.ctor()
            IL_0005: stloc.0
            IL_0006: ldloc.0
            IL_0007: ldarg.2
            IL_0008: stfld valuetype BadImageFormatExceptionRepro.Program/Wrapper`1<!0> class BadImageFormatExceptionRepro.Program/'<>c__DisplayClass3_0`1'<!T>::'wrapper'
            IL_000d: ldarg.1
            IL_000e: ldtoken !T
            IL_0013: call class [System.Private.CoreLib]System.Type [System.Private.CoreLib]System.Type::GetTypeFromHandle(valuetype [System.Private.CoreLib]System.RuntimeTypeHandle)
            IL_0018: ldstr "x"
            IL_001d: call class [System.Linq.Expressions]System.Linq.Expressions.ParameterExpression [System.Linq.Expressions]System.Linq.Expressions.Expression::Parameter(class [System.Private.CoreLib]System.Type, string)
            IL_0022: stloc.1
            IL_0023: ldloc.1
            IL_0024: ldloc.0
            IL_0025: ldtoken class BadImageFormatExceptionRepro.Program/'<>c__DisplayClass3_0`1'<!T>
            IL_002a: call class [System.Private.CoreLib]System.Type [System.Private.CoreLib]System.Type::GetTypeFromHandle(valuetype [System.Private.CoreLib]System.RuntimeTypeHandle)
            IL_002f: call class [System.Linq.Expressions]System.Linq.Expressions.ConstantExpression [System.Linq.Expressions]System.Linq.Expressions.Expression::Constant(object, class [System.Private.CoreLib]System.Type)
            IL_0034: ldtoken field valuetype BadImageFormatExceptionRepro.Program/Wrapper`1<!0> class BadImageFormatExceptionRepro.Program/'<>c__DisplayClass3_0`1'<!T>::'wrapper'
            IL_0039: ldtoken class BadImageFormatExceptionRepro.Program/'<>c__DisplayClass3_0`1'<!T>
            IL_003e: call class [System.Private.CoreLib]System.Reflection.FieldInfo [System.Private.CoreLib]System.Reflection.FieldInfo::GetFieldFromHandle(valuetype [System.Private.CoreLib]System.RuntimeFieldHandle, valuetype [System.Private.CoreLib]System.RuntimeTypeHandle)
            IL_0043: call class [System.Linq.Expressions]System.Linq.Expressions.MemberExpression [System.Linq.Expressions]System.Linq.Expressions.Expression::Field(class [System.Linq.Expressions]System.Linq.Expressions.Expression, class [System.Private.CoreLib]System.Reflection.FieldInfo)
            IL_0048: ldc.i4.0
            IL_0049: ldtoken method bool valuetype BadImageFormatExceptionRepro.Program/Wrapper`1<!!0>::op_Equality(!0, valuetype BadImageFormatExceptionRepro.Program/Wrapper`1<!0>)
            IL_004e: ldtoken valuetype BadImageFormatExceptionRepro.Program/Wrapper`1<!!0>
            IL_0053: call class [System.Private.CoreLib]System.Reflection.MethodBase [System.Private.CoreLib]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [System.Private.CoreLib]System.RuntimeMethodHandle, valuetype [System.Private.CoreLib]System.RuntimeTypeHandle)
            IL_0058: castclass [System.Private.CoreLib]System.Reflection.MethodInfo
            IL_005d: call class [System.Linq.Expressions]System.Linq.Expressions.BinaryExpression [System.Linq.Expressions]System.Linq.Expressions.Expression::Equal(class [System.Linq.Expressions]System.Linq.Expressions.Expression, class [System.Linq.Expressions]System.Linq.Expressions.Expression, bool, class [System.Private.CoreLib]System.Reflection.MethodInfo)
            IL_0062: ldc.i4.1
            IL_0063: newarr [System.Linq.Expressions]System.Linq.Expressions.ParameterExpression
            IL_0068: dup
            IL_0069: ldc.i4.0
            IL_006a: ldloc.1
            IL_006b: stelem.ref
            IL_006c: call class [System.Linq.Expressions]System.Linq.Expressions.Expression`1<!!0> [System.Linq.Expressions]System.Linq.Expressions.Expression::Lambda<class [System.Private.CoreLib]System.Func`2<!T, bool>>(class [System.Linq.Expressions]System.Linq.Expressions.Expression, class [System.Linq.Expressions]System.Linq.Expressions.ParameterExpression[])
            IL_0071: callvirt instance void class BadImageFormatExceptionRepro.Program/IInterface`1<!T>::InterfaceMethod(class [System.Linq.Expressions]System.Linq.Expressions.Expression`1<class [System.Private.CoreLib]System.Func`2<!0, bool>>)
            IL_0076: nop
            IL_0077: ret
        } // end of method '<>c__3`1'::'<GenericMethod>b__3_0'

    } // end of class <>c__3`1
```

IL_0049 and IL_004e are incorrect. It should be `!T`(generic parameter of the type) rather than `!!0`(generic parameter of the method).
