### ISSUE TITLE
X509Certificate2Collection PKCS7 export throws on macOS if empty

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#59206]
### Description

Attempting to do a PKCS7 export on macOS with `X509Certificate2Collection` with no certificates in the collection results in a `CryptographicException` that I do not think is expected.

Simple repro:

```csharp
using System.Security.Cryptography.X509Certificates;

X509Certificate2Collection cc = new();
cc.Export(X509ContentType.Pkcs7);
```

Result:

```plain
Unhandled exception. Interop+AppleCrypto+AppleCommonCryptoCryptographicException: errSecInternalComponent
   at Interop.AppleCrypto.X509Export(X509ContentType contentType, SafeCreateHandle cfPassphrase, IntPtr[] certHandles)
   at Internal.Cryptography.Pal.StorePal.AppleCertificateExporter.ExportPkcs7()
   at Internal.Cryptography.Pal.UnixExportProvider.Export(X509ContentType contentType, SafePasswordHandle password)
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export(X509ContentType contentType, String password)
   at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export(X509ContentType contentType)
   at Program.<Main>$(String[] args)
```

### Configuration

Occurs in .NET 6 RC1 and `main` on macOS Big Sur and Monterey Beta 12.

### Regression?

No.

### Other information

Windows creates an empty PKCS7.

Found while implementing #51630.

**Comment by bartonjs** [comment]
I guess an easy workaround is something like

```C#
private ReadOnlySpan<byte> EmptyPkcs7 = whatever pattern makes it a non-alloc property;

...

if (certs.Count == 0)
{
    return EmptyPkcs7.ToArray();
}

// rest of code here.
```

**Comment by vcsjones** [comment]
Heh, okay. And now I find out that macOS cannot import them, either. 🕳️🐇<sup>...down we go</sup>

**Comment by bartonjs** [comment]
Hm, Import's trickier, especially depending on where it fails (does GetContentType work?).  If it's not trivial, I'd call it a separate issue with lower priority, and it'd probably get fixed along with making `new X509Certificate(signedCms)` extract the first signer's certificate.

**Comment by vcsjones** [comment]
> does GetContentType work?

No. But we can try to help macOS like we do with PFX here:

https://github.com/dotnet/runtime/blob/f1425cfe5c6e456a1f160127955f590f7954f057/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/X509Pal.cs#L126-L127

We can try cracking it open with `ContentInfoAsn` and inspect a few OIDs. Let's try that:

```plain
 Failed System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportPkcs7_Empty_Roundtrip [5 ms]
  Error Message:
   Interop+AppleCrypto+AppleCommonCryptoCryptographicException : Import/Export format unsupported.
  Stack Trace:
     at Interop.AppleCrypto.X509ImportCollection(ReadOnlySpan`1 bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable) in /Users/kjones/Projects/dotnet/runtime/src/libraries/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.X509.macOS.cs:line 242
```

Ah, now the real import fails here:

https://github.com/dotnet/runtime/blob/e55a569d54d8a74f542d6a07d4d65ef55364d26c/src/libraries/Native/Unix/System.Security.Cryptography.Native.Apple/pal_x509_macos.c#L165

We get `errSecUnsupportedFormat` back. I tried re-attempting the import with a few different flags, but I could not get it to import correctly.
