### ISSUE TITLE
System.TypeLoadException : Type 'System.Configuration.ClientSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'

### ISSUE THREAD

**Issue by RussKie** [dotnet/runtime#59239]
### Description

Lately (RC1 timeframe?) dotnet/winforms tests for functionality that depends on `System.Configuration.ApplicationSettingsBase` started randomly failing with the following callstack (e.g. [#1](https://dev.azure.com/dnceng/public/_build/results?buildId=1367547&view=logs&j=fdea2036-e6b2-512d-a259-98f88c972586&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c), [#2](https://dev.azure.com/dnceng/public/_build/results?buildId=1367438&view=results)):
```
    System.Windows.Forms.Tests.ToolStripSettingsManagerTests.ToolStripSettingsManager_Save_Load_RoundTripExpected [FAIL]
      System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for userSettings/System.Windows.Forms.ToolStripSettings.MainForm.Child: Type 'System.Configuration.ClientSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'. (C:\Users\vsagent\AppData\Local\.NET_Foundation\xunit.console_StrongName_fmofxrdwgybamyp2bf020liphqsc2hhw\2.4.1.0\user.config line 5)
      ---- System.TypeLoadException : Type 'System.Configuration.ClientSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'.
      Stack Trace:
           at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
           at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
           at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
           at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
           at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
           at System.Configuration.ConfigurationManager.GetSection(String sectionName)
           at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
           at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
           at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
           at System.Configuration.SettingsBase.SetPropertyValueByName(String propertyName, Object propertyValue)
           at System.Configuration.SettingsBase.set_Item(String propertyName, Object value)
           at System.Configuration.ApplicationSettingsBase.set_Item(String propertyName, Object value)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs(42,0): at System.Windows.Forms.ToolStripSettings.set_ItemOrder(String value)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs(65,0): at System.Windows.Forms.ToolStripSettingsManager.Save()
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs(23,0): at System.Windows.Forms.Tests.ToolStripSettingsManagerTests.ToolStripSettingsManager_Save_Load_RoundTripExpected()
        ----- Inner Stack Trace -----
           at System.Configuration.TypeUtil.VerifyAssignableType(Type baseType, Type type, Boolean throwOnError)
           at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.Init(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
           at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory..ctor(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
           at System.Configuration.RuntimeConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
           at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
```

Upon a restart tests would generally pass (though it may take few attempts). There is no detectable pattern - a failure can occur on any bitness and in any build configuration.

**WHY:** I have no idea why this is starting failing. Has their been any changes in the Settings related area? 
This could be that build agents aren't getting cleaned, and we get something else interfering /cc: @MattGal 

There is nothing Windows Forms specific in this callstack.
We have a [`ToolStripSettings class`](https://github.com/dotnet/winforms/blob/8b918a8f476b7e5742e719aa7a9bb0debcb1590c/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs#L15):
![image](https://user-images.githubusercontent.com/4403806/133712965-53b2c882-313b-4b1f-97fd-ebbb4e006ae7.png)
which we use to [persist toolstrip-related settings](https://github.com/dotnet/winforms/blob/8b918a8f476b7e5742e719aa7a9bb0debcb1590c/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs#L62):
![image](https://user-images.githubusercontent.com/4403806/133713178-c4e4c21f-f8c9-469b-9c5b-cefce57ba82a.png)

When I run the same test locally I get the following configuration persisted under `C:\Users\<user>\AppData\Local\Microsoft_Corporation\testhost_StrongName_ncwojqheyhc0dhynwiffp31oq4puy42y\15.0.0.0\user.config` with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
            <section name="System.Windows.Forms.ToolStripSettings.MainForm.Child" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    ...omited for brevity...
</configuration>
```

With a high degree of probability and based on the raft of other similar issues, I can speculate that the issue is caused by the persisted identity `System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`. 
The original .NET Framework serialised the settings with the following identities:
```xml
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="settings_issue.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
```

The same underlying issue is causing the following issues that are affecting the runtime and design-time (i.e. VS) experience of Windows Forms apps:
* AB#1388851
* https://github.com/dotnet/project-system/issues/6784
* https://github.com/dotnet/project-system/issues/6799
* https://github.com/dotnet/winforms/issues/3346
* https://github.com/dotnet/winforms/issues/4308

**FIX:** Instead of writing the versions that the app targets we should continue writing the original .NET Framework versions, which will continue to work via the TF.
@ericstj do you have any thoughts on this?

The only truly affected scenario is custom user types in the Settings editor in VS (and causes AB#1388857), but Windows Forms teams has a number of internal discussions, and we believe this scenario can/should be deprecated, and any customer depending on it should roll their own implementation, if truly necessary:
![image](https://user-images.githubusercontent.com/4403806/133718159-6d8a6152-9d41-47c7-b8cb-aa742d062a47.png)

### Regression?

I believe it is a regression since it breaks back-compat (e.g. in VS scenarios - VS is run on net472 whilst customer apps are built on .NET stack).

/cc: @merriemcgaw  @dotnet/dotnet-winforms

**Comment by ericstj** [comment]
My best guess at what's happening is a type unification issue.  That could be caused by your environment and how types bind and have nothing to do with System.Configuration itself.  When you hit this exception you should check if two different copies of `System.Configuration.ConfigurationManager` are loaded in the process.  Then you can find out why that is the case.

Normally what happens for these loads is that the framework deps or apps deps file will decide the highest version to load and everything will unify to that.  If you happen to have a reference in your assemblies to a higher version, and you permit probing for that, you could end up with two versions loaded side-by-side in the same process.  You could also hit this is you were using AssemblyLoadContexts, or AppDomain.AssemblyResolve handler (which are somewhat common in tests).   cc @vitek-karas @agocke if they have any suggestions to debug if this an assembly unification issue.

**Comment by RussKie** [comment]
Thank you.

What do you think about serializing types as "4.0.0.0"?

**Comment by agocke** [comment]
If this is the WinForms designer, isn't the workflow here that you're reflecting against .NET Framework types and then trying to serialize and load these types in .NET Core?

**Comment by RussKie** [comment]
Unfortunately this is not _just_ Windows Forms designer issue. These include Settings and Resources management scenarios, which are part of Project System, and runtime scenarios (like the test failures).

**Comment by agocke** [comment]
But do I understand the workflow here? Is the system reflecting against Framework and then trying to run in Core?

**Comment by RussKie** [comment]
There are multiple issues here, which I _think_ are all linked to the same underlying issue.

In the case of failing tests - I don't know what the exact issue is, nor when exactly or why it started. We've been observing test instability for some time, and generally re-run intermittently failed legs. I think I've been observing these specific test failures for few weeks.

In the case of other related issues (e.g. Settings) this is squarely caused by serializing against client app's TFM instead of the lowest common denominator (which is .NET Framework).

**Comment by agocke** [comment]
> client app's TFM instead of the lowest common denominator (which is .NET Framework).

This is the part that doesn't make sense to me. The common denominator between .NET Framework and .NET Core is .NET Standard 2.0.

Broadly, my guess is that your test is somehow mixing .NET Framework and .NET Core DLLs somehow. You could probably confirm this with a crash dump that you can use to list the modules.

**Comment by ericstj** [comment]
> What do you think about serializing types as "4.0.0.0"?

It might workaround it, though depending on what is causing the two different loads in your test cases it could still be a problem.  If you need this stuff to work with NETFx then definitely you need to write the .NETFramework identity, that's the whole TypeForwardedFrom problem, which we've pointed out to the resource editor before. https://github.com/dotnet/project-system/issues/4806

For your own tests: Imagine the scenario when you're getting an older version of ConfigurationManager from the framework, and a newer version from the app, and you were missing the deps file entry.  Serializing as 4.0.0.0 (and System.Configuration, instead of System.ConfigurationManager) would still load the version from the windowsdesktop shared framework.  You really need to understand what two type definitions are being loaded and *why* they don't agree.  I really think you should find a way to get traces or dump of this situation to better understand what's going on. 

> I think I've been observing these specific test failures for few weeks.

Could be due to new 7.0.0.0 assemblies getting in the mix.

**Comment by RussKie** [comment]
> The common denominator between .NET Framework and .NET Core is .NET Standard 2.0.

VS is run in net472.

**Comment by RussKie** [comment]
> find a way to get traces or dump of this situation to better understand what's going on.

@MattGal is there a some way we could get dumps?
We're not running on Helix infra (it's a long story), and it's not something we could get on easily...

**Comment by agocke** [comment]
OK, @ericstj's issue helped. If the intent is to rely on the type forwards to keep everything working then I think the most likely thing that could be failing is that instead of just referencing the framework DLLs and then loading Core DLLs through the type forwards, you're somehow actually loading a desktop Framework DLL into the process.

This is very likely to cause type identity problems like you describe. Dump is almost certainly the best way to diagnose that it's happening. If you confirm that that's the problem, then you'll probably need to figure out why it's happening. You could try setting `COREHOST_TRACE` for direct dependency loading (https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-do-i-debug-the-probing-properties-construction). If this is happening later in the app run, you may need to trace dynamic assembly loading.

I believe `dotnet trace` can get this information, but unfortunately I've never used it myself.

**Comment by MattGal** [comment]
> > find a way to get traces or dump of this situation to better understand what's going on.
> 
> @MattGal is there a some way we could get dumps?
> We're not running on Helix infra (it's a long story), and it's not something we could get on easily...

- While you happen to still be on Helix-based build agents (anything with a pool name starting with NetCore), you can still find the environment variable `HELIX_WORKITEM_UPLOAD_ROOT` and put files in there.  I'll be able to find them from your build.
- Permanently, you can simply use [logging commands](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#upload-upload-an-artifact) to upload a dump as an artifact.  This is the preferable approach as it will be accessible directly from the build.

**Comment by KlausLoeffelmann** [comment]
Tagging @KathleenDollard for this conversation.

**Comment by ericstj** [comment]
I found out what's happening.  Here's a simple repro:
[toolstripTest.zip](https://github.com/dotnet/runtime/files/7205522/toolstripTest.zip)
Run the 6.0 version of that test, then the 5.0 version.

Since both versions of the test have the same assembly name they end up writing the user config to the same location.  In my case this was `C:\Users\erics\AppData\Local\System.Windows.Forms.Test\System.Windows.Forms.Test_StrongName_yq1ndijnbyys10s0pust04dzimv1t0ud\1.0.0.0\user.config`

In my case the `net6.0` test ran first, writing a config file with the 6.0.0.0 versions, then the 5.0 test would fail.  This is similar to the issue discussed here: https://github.com/dotnet/runtime/issues/28833

So Winforms could have avoided this in the tests by ensuring their test assemblies always version when major versions of their dependencies version.  

Perhaps a better fix would be to have the tests cleanup after themselves, with something like this:
```C#
var configuration = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoamingAndLocal);
Console.WriteLine(configuration.FilePath);
if (File.Exists(configuration.FilePath))
{
    File.Delete(configuration.FilePath);
}
```

**Comment by jeffschwMSFT** [comment]
Should this issue be moved to the winforms repo?
