### ISSUE TITLE
MutualThdRecur-fptr.sh failed with NullReferenceException on Ubuntu 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#59260]
```
Console log: 'JIT.Directed' from job e1917e03-c5e2-4421-aa84-aaad597cfd27 workitem acadb29a-ffe9-4ccf-91ac-a1108fc76ffd (ubuntu.1804.amd64.open.svc) executed on machine a001216
+ export CORE_ROOT=/datadisks/disk1/work/AAF6099E/p
+ export __TestEnv=/datadisks/disk1/work/AAF6099E/w/CF0E0AF5/u/SetStressModes_normal.sh
+ export __TestTimeout=600000
+ export __CollectDumps=1
+ export __CrashDumpFolder=/home/helixbot/dotnetbuild/dumps
+ cat /datadisks/disk1/work/AAF6099E/w/CF0E0AF5/u/SetStressModes_normal.sh
#!/usr/bin/env bash
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export MONO_ENV_OPTIONS=--llvm
+ export PATH=/datadisks/disk1/work/AAF6099E/p/dotnet-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ export DOTNET_ROOT=/datadisks/disk1/work/AAF6099E/p/dotnet-cli
+ export DOTNET_CLI_TELEMETRY_OPTOUT=1
+ export DOTNET_CLI_HOME=/datadisks/disk1/work/AAF6099E/w/CF0E0AF5/e/.dotnet
+ export NUGET_PACKAGES=/datadisks/disk1/work/AAF6099E/w/CF0E0AF5/e/.nuget
+ dotnet /datadisks/disk1/work/AAF6099E/p/xunit/xunit.console.dll JIT/Directed/JIT.Directed.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.Directed
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 6.0.0-rc.1.21430.1)
  Discovering: JIT.Directed.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Directed.XUnitWrapper (found 131 test cases)
  Starting:    JIT.Directed.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/Directed/Misc/function_pointer/MutualThdRecur-fptr/MutualThdRecur-fptr.sh [FAIL]
      
      Unhandled Exception:
      System.NullReferenceException: Object reference not set to an instance of an object.
         at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
         at Thread_EA.Run()
         at System.Threading.Thread.StartCallback()
      
      Unhandled Exception:
      System.NullReferenceException: Object reference not set to an instance of an object.
         at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
         at Thread_EA.Run()
         at System.Threading.Thread.StartCallback()
      
      Unhandled Exception:
      System.NullReferenceException: Object reference not set to an instance of an object.
         at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
         at Thread_EA.Run()
         at System.Threading.Thread.StartCallback()
      [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
         at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
         at Thread_EA.Run()
         at System.Threading.Thread.StartCallback()
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/AAF6099E/w/CF0E0AF5/uploads/Reports/JIT.Directed/Misc/function_pointer/MutualThdRecur-fptr/MutualThdRecur-fptr.output.txt
      Raw output:
      BEGIN EXECUTION
      /datadisks/disk1/work/AAF6099E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false MutualThdRecur-fptr.dll ''
      test started
      on thread finished
      on thread finished
      on thread finished
      on thread finished
      on thread finished
      on thread finished
      on thread finished
      Expected: 100
      Actual: 1
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/AAF6099E/p
      > /datadisks/disk1/work/AAF6099E/w/CF0E0AF5/e/JIT/Directed/Misc/function_pointer/MutualThdRecur-fptr/MutualThdRecur-fptr.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Directed._Misc_function_pointer_MutualThdRecur_fptr_MutualThdRecur_fptr_._Misc_function_pointer_MutualThdRecur_fptr_MutualThdRecur_fptr_sh()
      Output:
        
        Unhandled Exception:
        System.NullReferenceException: Object reference not set to an instance of an object.
           at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
           at Thread_EA.Run()
           at System.Threading.Thread.StartCallback()
        
        Unhandled Exception:
        System.NullReferenceException: Object reference not set to an instance of an object.
           at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
           at Thread_EA.Run()
           at System.Threading.Thread.StartCallback()
        
        Unhandled Exception:
        System.NullReferenceException: Object reference not set to an instance of an object.
           at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
           at Thread_EA.Run()
           at System.Threading.Thread.StartCallback()
        [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
           at <Module>.?Function1_1@@YAXH@Z(Int32 A_0)
           at Thread_EA.Run()
           at System.Threading.Thread.StartCallback()
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/AAF6099E/w/CF0E0AF5/uploads/Reports/JIT.Directed/Misc/function_pointer/MutualThdRecur-fptr/MutualThdRecur-fptr.output.txt
        Raw output:
        BEGIN EXECUTION
        /datadisks/disk1/work/AAF6099E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false MutualThdRecur-fptr.dll ''
        test started
        on thread finished
        on thread finished
        on thread finished
        on thread finished
        on thread finished
        on thread finished
        on thread finished
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/AAF6099E/p
        > /datadisks/disk1/work/AAF6099E/w/CF0E0AF5/e/JIT/Directed/Misc/function_pointer/MutualThdRecur-fptr/MutualThdRecur-fptr.sh
  Finished:    JIT.Directed.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Directed.XUnitWrapper  Total: 131, Errors: 0, Failed: 1, Skipped: 0, Time: 248.631s
```
https://github.com/dotnet/runtime/pull/59194

**Comment by JulieLeeMSFT** [comment]
cc @BruceForstall PTAL. It is multithreading related issue.

**Comment by BruceForstall** [comment]
This is a Mono failure, not a RyuJIT failure.

Log file for the failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1367894&view=ms.vss-test-web.build-test-results-tab&runId=39931020&resultId=101135&paneView=debug

**Comment by SamMonoRT** [comment]
cc @vargaz @lambdageek - not certain what this is about - any ideas ?

**Comment by lambdageek** [comment]
(Aside: the wacky method names are not a bug - that's what they're called in the .il file)

The code is doing a `ldftn` and then passing the managed function pointer to a "Dispatch" function that does `ldarg` and then a `calli`.  The thing that's a little bit unexpected is that it's an `ldftn` of a static method but the callsite says `method explicit instance` for the function pointer.  @vargaz Does this seem problematic?


The code is like this:

```
  .method public static void Dispatch(method explicit instance void *(int32), int32)
  {
    .maxstack  8
    ldarg 1
    ldarg 0
    calli void (int32)
    ret
  }
```

In `Run`:

```
              ldftn      void ?Function1_1@@YAXH@Z(int32)
    IL_0006:  ldloc.0
    IL_0007:  ldc.i4     0x1
    IL_000c:  add
     call       void Thread_EA::Dispatch(method explicit instance void *(int32), int32)
```

The `?Function1_1@@YAXH@Z` method:

```
.method public static void ?Function1_1@@YAXH@Z(int32 A_0) il managed
{
```
