### ISSUE TITLE
Asc_Chr_Invariant fail tests on net48 with current culture is not English

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#59325]
### Description

When the current culture is not English, then  Microsoft.VisualBasic.Tests.StringsTests.Asc_Chr_Invariant fail tests on net48 with next log:
```
 Microsoft.VisualBasic.Tests.StringsTests.Asc_Chr_Invariant
   Source: StringsTests.cs line 121

Test has multiple result outcomes
   3 Passed
   1 Failed

Results
    4)   Microsoft.VisualBasic.Tests.StringsTests.Asc_Chr_Invariant(charCode: 255, expected: 255) 
      Duration: 19 ms

      Message: 
Assert.Equal() Failure
Expected: 255
Actual:   121

      Stack Trace: 
StringsTests.Asc_Chr_Invariant(Int32 charCode, Int32 expected) line 127
```

`Strings.Asc()` returns 211 but 255 is expected. Unfortunately, I don't know how to debug inside it to make PR. 
Can anyone give me a link with help on how to compile tests with a possibility to debug inside library methods?

### Configuration

net48 target
Windows 10 (Russian)
x64

**Comment by danmoseley** [comment]
@AlexRadch I would expect it to just work. There are several ways to debug tests, eg.,
* the console output says to pushd to a folder and then run a certain command line. You can set up your debugger to launch that command line in that folder and set a breakpoint.
* or, you can add a `Debugger.Break()` command and then attach
* or, it's supposed to work to start debugging the test from the Test Explorer but I have not tried this recently especially for .NET Framework 4.8 target

For such a simple test, it may be easier to paste the code into a standalone app targeting .NET Framework.  If you have disabled "Just my Code" and enabled "Step into .NET Framework" and "Use Microsoft symbol server" it should load the symbols for Microsoft.VisualBasic.dll and allow you to step into the code.

If this only repros for .NET Framework target and .NET Core another option is to use ILSPY and just compare the implementations of Strings.Asc and Strings.Chr. Or transliterate what you see in ILSPY into C# and debug that, etc etc.

**Comment by tarekgh** [comment]
@AlexRadch I tried running with default culture as Russian culture but couldn't get this specific failure. Are you consistently getting this failure on your machine? For testing you may follow the instructions in the link https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/visualstudio.md

I got other failures though because the `NaN` symbol for this language is defined as `не число`. Here is an example of the failures:

```
      Microsoft.VisualBasic.Tests.ConversionsTests.ToString_IConvertible_ReturnsExpected(value: ?? ?????, expected: "NaN") [FAIL]
        Assert.Equal() Failure
        Expected: NaN
        Actual:   ?? ?????
        Stack Trace:
          C:\oss\runtime\src\libraries\Microsoft.VisualBasic.Core\tests\ConversionsTests.cs(2874,0): at Microsoft.VisualBasic.Tests.ConversionsTests.AssertEqual(Object expected, Object actual)
          C:\oss\runtime\src\libraries\Microsoft.VisualBasic.Core\tests\ConversionsTests.cs(2689,0): at Microsoft.VisualBasic.Tests.ConversionsTests.ToString_IConvertible_ReturnsExpected(IConvertible value, String expected)
```


CC @tannergooding

**Comment by tannergooding** [comment]
@tarekgh I beleive that should be expected. We rely on `NumberFormatInfo.NaNSymbol`: https://github.com/dotnet/runtime/blob/78593b9e095f974305b2033b465455e458e30267/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs#L1804-L1815

If you want just "NaN" to work, you'd need to use the `InvariantCulture`.

**Comment by tarekgh** [comment]
@tannergooding you are right. I just cc'ed for awareness. The test needs to be fixed. 


@danmoseley @AlexRadch 

The issue here is on NETFX 4.8, `Microsoft.VisualBasic.Strings.Asc()` calls the following:

```C#
Encoding fileIOEncoding = Utils.GetFileIOEncoding();
```

And `GetFileIOEncoding` implemented as follows:

```C#
// Microsoft.VisualBasic.CompilerServices.Utils
internal static Encoding GetFileIOEncoding()
{
	return Encoding.Default;
}
```

That will cause always use the system encoding regardless of the current culture.


On net core, 
On net core, `Microsoft.VisualBasic.Strings.Asc()` calls the following:

```C#
enc = GetAscChrEncoding()
```

and `GetAscChrEncoding` implemented as:

```VB
        Private Function GetAscChrEncoding() As Encoding
            Return Encoding.GetEncoding(GetLocaleCodePage())
        End Function

        Friend Shared Function GetLocaleCodePage() As Integer
            Return System.Threading.Thread.CurrentThread.CurrentCulture.TextInfo.ANSICodePage
        End Function
```

which return the encoding from the current culture and not the system one.

The test need to be fixed to support such case.
