### ISSUE TITLE
Disabled GC tests

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/runtime#5933]
~~We need this script to update info in the Versions github repo when we publish packages to myget.~~

**Comment by trylek** [comment]
@dotnet/gc - @eduardo-vp's PR

https://github.com/dotnet/runtime/pull/75363/files

tries to remove this closed issue and hits failures in the previously disabled tests:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=28045&view=ms.vss-test-web.build-test-results-tab&runId=599430&resultId=110132&paneView=debug

This issue is pretty old, could someone familiar with these tests take a look and try to assess whether the failures in the tests still hit this old issue or something new?

Thanks a lot

Tomas

**Comment by trylek** [comment]
I'm reopening this issue for tracking purposes before the new failure is triaged and understood so that Eduardo can finish his PR I believe to be general goodness.

**Comment by trylek** [comment]
Example failures on Linux x64 without CG2:

<pre>
    GC/LargeMemory/API/gc/getgeneration/getgeneration.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.LargeMemory/API/gc/getgeneration/getgeneration.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false getgeneration.dll '2048'
      getGeneration passed
      0
      getGenerationWR failed
      Test failed
      Expected: 100
      Actual: 0
</pre>

<pre>
    GC/Features/LOHFragmentation/lohfragmentation/lohfragmentation.sh [FAIL]
      /root/helix/work/workitem/e/GC/Features/LOHFragmentation/lohfragmentation/lohfragmentation.sh: line 412: 10449 Killed                  $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Features/LOHFragmentation/lohfragmentation/lohfragmentation.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false lohfragmentation.dll ''
      Expected: 100
      Actual: 137
      END EXECUTION - FAILED
</pre>

<pre>
      Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Coverage/271010/271010.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false 271010.dll ''
      Expected: 100
      Actual: 1
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/GC/Coverage/271010/271010.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at GC_Coverage._271010_271010_._271010_271010_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
</pre>

There are some more cases that manifest as timeouts, it's unclear to me at this moment whether the timeouts are infrastructural or also somehow related to this problem.

**Comment by janvorli** [comment]
I've scanned the URLs of issues in the coreclr tests sources and csproj files and found none that would be already closed.

**Comment by MichalStrehovsky** [comment]
> I've scanned the URLs of issues in the coreclr tests sources and csproj files and found none that would be already closed.

There are 7 tests ActiveIssue'd on this, why close this issue? https://github.com/search?q=repo%3Adotnet%2Fruntime%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fissues%2F5933&type=code

We just ran into a test that is disabled only on CoreCLR (not native AOT) on this issue here: https://github.com/dotnet/runtime/issues/131565#issuecomment-5129175088

**Comment by janvorli** [comment]
Oh, the catch was that I was scanning for closed issues referenced by .cs / .csproj. There were none. I have not realized that the purpose of this one was actually to be referenced from tests.
