### ISSUE TITLE
Parsing CSV (TextFieldParser) from ZipArchive fails with .net 6 RC1. 

### ISSUE THREAD

**Issue by ashcor** [dotnet/runtime#59371]
### Describe the bug
Parsing a CSV file extracted from a ZipArchive fails with a MalformedLineExceptionin .net 6 RC 1.
```
         class Program
       {
        static void Main(string[] args)
        {
            Console.WriteLine($"Lines: {ReadCsv().Count()}");
        }

        public static IEnumerable<string[]> ReadCsv()
        {
            using (var zipStream = File.OpenRead("stops.zip"))
            using (var archive = new ZipArchive(zipStream))
            using (var stream = archive.GetEntry("stops.txt").Open())
            using (var reader = new StreamReader(stream))
            using (var parser = new TextFieldParser(reader)
            {
                TextFieldType = FieldType.Delimited,
                Delimiters = new string[] { "," },
                HasFieldsEnclosedInQuotes = true,
            })
            {
                while (!parser.EndOfData)
                    yield return parser.ReadFields();
            }
        }
    }
```

### To Reproduce
clone https://github.com/ashcor/net6parse/tree/main/ConsoleApp1 and do `dotnet run`. The code fails with .net 6 RC1 but works fine when changing to `<TargetFramework>net5.0</TargetFramework>`. The zip file in question was produced with 7zip with the default settings. The encoding of the zipped file is UTF-8 BOM.

### Exceptions (if any)
```
PS C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1> dotnet run
Unhandled exception. Microsoft.VisualBasic.FileIO.MalformedLineException: Line 39136 cannot be parsed using the current Delimiters.
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ParseDelimitedLine()
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ReadFields()
   at ConsoleApp1.Program.ReadCsv()+MoveNext() in C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1\Program.cs:line 31
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1\Program.cs:line 14 Line Number:39136
```

### Further technical details
`dotnet --info`
```
PS C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1
```

**Comment by cston** [comment]
See also https://github.com/dotnet/runtime/issues/58857.

**Comment by cston** [comment]
@ashcor, thanks for logging this issue!
