### ISSUE TITLE
Test failure tracing/eventpipe/bigevent/bigevent/bigevent.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59448]
Run：[runtime-coreclr r2r-extra 20210919.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1371680&view=ms.vss-test-web.build-test-results-tab&runId=40018866&resultId=110600&paneView=debug)

Failed test:
```
R2R Linux x64 Checked gcstress0xf @ Ubuntu.1804.Amd64.Open

- tracing/eventpipe/bigevent/bigevent/bigevent.sh

```
**Error messag:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh: line 265: -r:/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/.dll: No such file or directory
rm: cannot remove '/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll.rsp': No such file or directory
rm: cannot remove '/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/common.dll.rsp': No such file or directory
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.Diagnostics.Tracing.TraceEvent.CopyBlob(IntPtr, IntPtr, Int32)
at Microsoft.Diagnostics.Tracing.TraceEvent.Clone()
at Microsoft.Diagnostics.Tracing.Parsers.ExternalTraceEventParser.<.ctor>b__0_0(Microsoft.Diagnostics.Tracing.TraceEvent)
at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Lookup(EVENT_RECORD)
at Microsoft.Diagnostics.Tracing.EventPipeEventSource.DispatchEventRecord(EVENT_RECORD*)
at Microsoft.Diagnostics.Tracing.EventPipeEventSource.EventCache_OnEvent(Microsoft.Diagnostics.Tracing.EventPipeEventHeader ByRef)
at Microsoft.Diagnostics.Tracing.EventPipe.EventCache.SortAndDispatch(Int64)
at Microsoft.Diagnostics.Tracing.EventPipe.EventCache.ProcessSequencePointBlock(Byte[])
at Microsoft.Diagnostics.Tracing.EventPipeSequencePointBlock.ReadBlockContents(FastSerialization.PinnedStreamReader)
at Microsoft.Diagnostics.Tracing.EventPipeBlock.FromStream(FastSerialization.Deserializer)
at FastSerialization.Deserializer.ReadObjectDefinition(FastSerialization.Tags, FastSerialization.StreamLabel)
at FastSerialization.Deserializer.ReadObject()
at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
at Tracing.Tests.Common.IpcTraceTest+<>c__DisplayClass8_0.<Validate>b__1()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()
/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh: line 389: 19736 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/9ABF08F7/w/ADF8091F/uploads/Reports/tracing.eventpipe/bigevent/bigevent/bigevent.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/bigevent.dll
Response file: /datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll.rsp
/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/bigevent.dll
-o:/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll
-r:/datadisks/disk1/work/9ABF08F7/p/System..dll
-r:/datadisks/disk1/work/9ABF08F7/p/Microsoft..dll
-r:/datadisks/disk1/work/9ABF08F7/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /datadisks/disk1/work/9ABF08F7/p/crossgen2/crossgen2.dll @/datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll.rsp

Emitting R2R PE file: /datadisks/disk1/work/9ABF08F7/w/ADF8091F/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll
/datadisks/disk1/work/9ABF08F7/w/ADF80


Stack trace
   at tracing_eventpipe._bigevent_bigevent_bigevent_._bigevent_bigevent_bigevent_sh()
```

**Comment by tommcdon** [comment]
@josalem

**Comment by josalem** [comment]
This is a dup of #54801 which requires a fix in TraceEvent being tracked in microsoft/perfview/issues/1474.
