### ISSUE TITLE
Test failure System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59455]
Run:[ runtime-coreclr libraries-jitstress 20210921.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1374686&view=ms.vss-test-web.build-test-results-tab&runId=40099778&resultId=136382&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)
```
**Error message:**
```
Assert.Equal() Failure
Expected: 85
Actual:   0


Stack trace
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.VerifyExpectedRequest(Rfc3161TimestampRequest request, Boolean viaSpan) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 115
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(Boolean viaSpan) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 54
```

**Comment by vcsjones** [comment]
Weird. I'll take a look at this one.

**Comment by VincentBu** [comment]
Run: [runtime-coreclr libraries-jitstress  20210929.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1392386&view=ms.vss-test-web.build-test-results-tab&runId=40490428&resultId=138444&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)

```
**Error message:**
```
Assert.Equal() Failure
Expected: 85
Actual:   0


Stack trace
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.VerifyExpectedRequest(Rfc3161TimestampRequest request, Boolean viaSpan) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 115
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(Boolean viaSpan) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 54
```

**Comment by bartonjs** [comment]
This is a consequence of Fill being broken: https://github.com/dotnet/runtime/issues/59444

**Comment by bartonjs** [comment]
Since this is effectively a dupe, closing the issue.
