### ISSUE TITLE
Test failure System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59456]
Run: [runtime-coreclr libraries-jitstress 20210921.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1374686&view=ms.vss-test-web.build-test-results-tab&runId=40099778&resultId=190408&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth

net7.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth

net7.0-windows-Release-x86-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth

net7.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth

net7.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth


```
**Error message:**
```
System.Text.Json.JsonReaderException : '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 528.


Stack trace
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.cs:line 290
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1110
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 868
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs:line 973
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs:line 692
   at System.Text.Json.Tests.JsonDomWriteTests.WriteIncredibleDepth() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonElementWriteTests.cs:line 1134
```

**Comment by layomia** [comment]
cc @steveharter

Likely not a 6.0 bug. We should observe if there are more hits.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20210929.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1392386&view=ms.vss-test-web.build-test-results-tab&runId=40490428&paneView=debug&resultId=190115)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth

net7.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth

net7.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonDocumentWriteTests.WriteIncredibleDepth
- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth

```
**Error message:**
```
System.Text.Json.JsonReaderException : '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 528.


Stack trace
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.cs:line 290
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1110
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 872
   at System.Text.Json.Utf8JsonReader.Read() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 272
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs:line 951
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs:line 692
   at System.Text.Json.Tests.JsonDomWriteTests.WriteIncredibleDepth() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonElementWriteTests.cs:line 1135
```

**Comment by BruceForstall** [comment]
Maybe related to https://github.com/dotnet/runtime/issues/59444?

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20211003.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1400246&view=ms.vss-test-web.build-test-results-tab&runId=40666302&paneView=debug&resultId=190116)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs3-Windows.10.Amd64.Open

- System.Text.Json.Tests.JsonElementWriteTests.WriteIncredibleDepth

```
**Error message:**
```
System.Text.Json.JsonReaderException : '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 528.


Stack trace
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.cs:line 290
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1110
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 872
   at System.Text.Json.Utf8JsonReader.Read() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 272
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs:line 951
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs:line 692
   at System.Text.Json.Tests.JsonDomWriteTests.WriteIncredibleDepth() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonElementWriteTests.cs:line 1135
```
