### ISSUE TITLE
Unhandled Exception in Pipeline Execution Thread,Exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59460]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unhandled-Exception-in-Pipeline-Executio/1522032)._

---
My application observes an unhandled exception in Pipeline Execution Thread - which is not one of my application threads but appears to be a framework thread.
The exception is 
System.IO.IOException: Das Handle ist ungültig. (English: invalid handle)
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.EventWaitHandle.Set()
   at System.Management.Automation.Runspaces.RunspaceBase.RemoveFromRunningPipelineList(PipelineBase pipeline)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unfortunately I have no idea about the root cause nor how to catch that exception.
The issue occured on Windows 10 Pro 2009 10.0.19043 and .Net 4.8.04084 (528372).

Any idea on how to spot root cause?
Thanks, Joachim

---
#### Feedback Bot on 9/6/2021, 04:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by SKuebbe1-Quest** [comment]
We have seen the same issue in of our applications running at a customer on v4.0.30319.

**Comment by ViktorHofer** [comment]
Please excuse the late response, we didn't notice this issue. Based on your information provided, this looks like a .NET Framework issue and hence this issues shouldn't have been moved over from developercommunity. Are you still impacted by this? If yes, then I can get this issue moved back.
