### ISSUE TITLE
Test failure System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: \"api.nuget.org\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59508]
Run: [runtime-libraries-coreclr outerloop 20210922.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1377661&view=ms.vss-test-web.build-test-results-tab&runId=40172436&resultId=101786&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_release-(Debian.11.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm32v7-20210304164347-5a7c380

- System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: \"api.nuget.org\")

```

**Error message:**
```
Assert.Equal() Failure
Expected: None
Actual:   RemoteCertificateChainErrors


Stack trace
   at System.Net.Security.Tests.CertificateValidationRemoteServer.RemoteHttpsCertValidation(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 112
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 998
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 646
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 670
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 435
   at System.Net.Security.Tests.CertificateValidationRemoteServer.EndToEndHelper(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 105
   at System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 86
--- End of stack trace from previous location ---
```

**Comment by rzikm** [comment]
Seems to have been a transient failure, has not been repeated since. closing
