### ISSUE TITLE
Kerberos authentication not work on .NET 6 RC1 with official docker images

### ISSUE THREAD

**Issue by kotovaleksandr** [dotnet/runtime#59518]
### Description
Kerberos authentication doesn't work after update to RC1 from .NET 5.0:
```**Cannot load library libgssapi_krb5.so**
Error: libgssapi_krb5.so: cannot open shared object file: No such file or directory
Unhandled exception. System.ComponentModel.Win32Exception (0x80090020): The type initializer for 'NetSecurityNative' threw an exception.
   at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
   at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendUsingHttp11Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request)
```
Reproduced on mcr.microsoft.com/dotnet/aspnet:6.0 and mcr.microsoft.com/dotnet/aspnet:6.0-focal.

### Configuration
```
dotnet --info

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Other information
Workaround:
```
ln /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so
```

Caused by  Shim gss api on Linux to delay loading libgssapi_krb5.so #55037

**Comment by karelz** [comment]
@VSadov @janvorli looks related to the shim of GSS APIs in #55037 (thanks @kotovaleksandr for finding it!) ... any thoughts what might be wrong?
cc @wfurt

**Comment by janvorli** [comment]
Using the libgssapi_krb5.so name is wrong, this form of name should by used only at build time. So when the development version of the libkrb5 is installed, things work. If not, then only the libgssapi_krb5.so.2 is present. I am sorry, I have missed that while reviewing the PR that added the shim.

**Comment by karelz** [comment]
Great, thanks for clarification ... mistakes happen. We should probably fix this one for 6.0 as it is a regression and it will impact Docker users heavily.
@janvorli do you know who would be in best position to put up a fix?

**Comment by janvorli** [comment]
Let me actually make the change to increase the chance that it will make it in time for the RC2.

**Comment by karelz** [comment]
Reopening to track backport to 6.0 branch

**Comment by karelz** [comment]
Fixed in 6.0 RC2 in PR #59566.
Fixed in 7.0 (main) in PR #59526.

**Comment by danmoseley** [comment]
@kotovaleksandr RC2 should be released in a week or two. It would be great if you can pull it down then and verify that this is fixed.

**Comment by karelz** [comment]
Thanks @kotovaleksandr for your verification!
