### ISSUE TITLE
Test failure JIT\\CodeGenBringUpTests\\NotRMW_do\\NotRMW_do.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59555]
Run: [runtime-coreclr jitstress 20210922.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1380040&view=ms.vss-test-web.build-test-results-tab&runId=40238420&paneView=debug&resultId=107401)

Failed test:
```
CoreCLR windows arm64 Checked jitstress2_tiered @ Windows.10.Arm64v8.Open

- JIT\\CodeGenBringUpTests\\NotRMW_do\\NotRMW_do.cmd

```
**Error message:**
```
Assert failure(PID 15140 [0x00003b24], Thread: 5548 [0x15ac]): The 'LastThrownObject' should not be, but is, NULL.
The runtime may have lost track of the type of an exception in flight.
Please get a good stack trace, find the caller of Validate, and file a bug against the owner.

To suppress this assert 'set COMPlus_SuppressLostExceptionTypeAssert=1'

CORECLR! CLRLastThrownObjectException::Validate + 0x120 (0x00007fffc724a460) CORECLR!ClassLoader::LoadTypeHandleForTypeKey_Body'::1'::catch$39 + 0xF8 (0x00007fffc75f0500)
CORECLR! CallSettingFrame + 0x68 (0x00007fffc70f2ec0) CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x130 (0x00007fffc756f510)
NTDLL! RtlRestoreContext + 0xEC (0x00007ffffa06369c) CORECLR! ClassLoader::LoadTypeHandleForTypeKey_Body + 0x908 (0x00007fffc713b9d0)
CORECLR! ClassLoader::LoadTypeHandleForTypeKey + 0x174 (0x00007fffc713ae2c) CORECLR! ClassLoader::LoadTypeDefThrowing + 0x450 (0x00007fffc713ab58)
CORECLR! MemberLoader::GetMethodDescFromMethodDef + 0xD8 (0x00007fffc71addf8) CORECLR! CEEInfo::resolveToken + 0x2E0 (0x00007fffc71a3ff0)
File: D:\workspace_work\1\s\src\coreclr\vm\clrex.cpp Line: 2168
Image: D:\h\w\B021096C\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\B021096C\w\8F0807FC\uploads\Reports\JIT.CodeGenBringUpTests\NotRMW_do\NotRMW_do.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B021096C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  NotRMW_do.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B021096C\p
D:\h\w\B021096C\w\8F0807FC\e\JIT\CodeGenBringUpTests\NotRMW_do\NotRMW_do.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_CodeGenBringUpTests._NotRMW_do_NotRMW_do_._NotRMW_do_NotRMW_do_cmd()
```

**Comment by VincentBu** [comment]
Failed again in:  [runtime-coreclr jitstress 20220527.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1794388&view=ms.vss-test-web.build-test-results-tab&runId=47927878&resultId=104127&paneView=debug)

Failed test:
```
coreclr windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open

- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- readytorun\\tests\\mainv1\\mainv1.cmd
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- readytorun\\tests\\mainv2\\mainv2.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd
- JIT\\opt\\OSR\\tailpgo2\\tailpgo2.cmd
- Loader\\binding\\tracing\\BinderTracingTest.ResolutionFlow\\BinderTracingTest.ResolutionFlow.cmd
- JIT\\jit64\\opt\\cse\\VolatileTest_op_mod\\VolatileTest_op_mod.cmd
- tracing\\runtimeeventsource\\nativeruntimeeventsource\\nativeruntimeeventsource.cmd

coreclr windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open

- GC\\Features\\SustainedLowLatency\\scenario\\scenario.cmd
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- GC\\Scenarios\\LeakWheel\\leakwheel\\leakwheel.cmd

coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Avx2_Vector128\\Avx2_ro\\Avx2_ro.cmd
- GC\\Features\\SustainedLowLatency\\scenario\\scenario.cmd
- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd
- JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b425314\\b425314\\b425314.cmd
- profiler\\unittest\\getappdomainstaticaddress\\getappdomainstaticaddress.cmd
- JIT\\opt\\Vectorization\\UnrollEqualsStartsWIth\\UnrollEqualsStartsWIth.cmd
- profiler\\unittest\\metadatagetdispenser\\metadatagetdispenser.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\Sse_ro\\Sse_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Fma_Vector128\\Fma_ro\\Fma_ro.cmd
- profiler\\unittest\\inlining\\inlining.cmd
- profiler\\gc\\gcbasic\\gcbasic.cmd
- Loader\\classloader\\TypeInitialization\\CircularCctors\\CircularCctorThreeThreads03BFI\\CircularCctorThreeThreads03BFI.cmd
```
Error message:
```
Assert failure(PID 3360 [0x00000d20], Thread: 5476 [0x1564]): The 'LastThrownObject' should not be, but is, NULL.
The runtime may have lost track of the type of an exception in flight.
Please get a good stack trace, find the caller of Validate, and file a bug against the owner.

To suppress this assert 'set COMPlus_SuppressLostExceptionTypeAssert=1'

CORECLR! CLRLastThrownObjectException::Validate + 0x2F6 (0x00007ffdc366a086) CORECLR!TieredCompilationManager::CompileCodeVersion'::1'::catch$12 + 0xC4 (0x00007ffdc3d8fd54)
CORECLR! CallSettingFrame_LookupContinuationIndex + 0x20 (0x00007ffdc3cd7f80) CORECLR! _FrameHandler4::CxxCallCatchBlock + 0x1DE (0x00007ffdc3cd5efe)
NTDLL! RtlCaptureContext + 0x3C3 (0x00007ffdf31f9d63) CORECLR! TieredCompilationManager::CompileCodeVersion + 0x211 (0x00007ffdc35ee851)
CORECLR! TieredCompilationManager::OptimizeMethod + 0xF1 (0x00007ffdc35f0561) CORECLR! TieredCompilationManager::DoBackgroundWork + 0x576 (0x00007ffdc35ef1c6)
CORECLR! TieredCompilationManager::BackgroundWorkerStart + 0x20A (0x00007ffdc35ee51a) CORECLR! TieredCompilationManager::BackgroundWorkerBootstrapper1 + 0xDD (0x00007ffdc35ee2ad)
File: D:\a_work\1\s\src\coreclr\vm\clrex.cpp Line: 2165
Image: C:\h\w\A72D091C\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A72D091C\w\A5970982\uploads\Reports\JIT.superpmi\superpmicollect\Bytemark\Bytemark.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A72D091C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Bytemark.dll
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 1456.59846  Index: 37.35538
NUMERIC SORT(rectangle):  Iterations/sec: 338.80015  Index: 8.68874
STRING SORT:  Iterations/sec: 3222.76352  Index: 1440.01944
BITFIELD:  Iterations/sec: 317526401.74629  Index: 54.46699
FP EMULATION(struct):  Iterations/sec: 117.91670  Index: 56.58191
FP EMULATION(class):Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A72D091C\p
C:\h\w\A72D091C\w\A5970982\e\JIT\superpmi\superpmicollect\Bytemark\Bytemark.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_superpmi._superpmicollect_Bytemark_Bytemark_._superpmicollect_Bytemark_Bytemark_cmd()
```

**Comment by mangod9** [comment]
Closing since seems to be failing in the superpmi case with jitstress enabled.
