### ISSUE TITLE
.NET 6 regression on writing to character device

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#59754]
Create a console app with following content in Program.cs:

```c#
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

string path = "/dev/tty";
if (!File.Exists(path))
{
    throw new Exception(path + " is not available in this environment.");
}

var contentBytes = new byte[] { 1, 2, 3 };

using (var cts = new CancellationTokenSource())
{
    Task writingTask = File.WriteAllBytesAsync(path, contentBytes, cts.Token);
    cts.CancelAfter(TimeSpan.FromMilliseconds(500));

    await writingTask;
}

Console.WriteLine("Passed!");
```

On macOS (x64), run with .NET 5 (5.0.400), it prints `Passed!`. In .NET 6 (6.0.100-rtm.21479.10) it throws:
```
Unhandled exception. System.IO.IOException: Device not configured : '/dev/tty'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.IO.File.<WriteAllBytesAsync>g__Core|72_0(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /Users/adeel/projects/testdevtty/Program.cs:line 21
   at Program.<Main>(String[] args)
```

**Comment by am11** [comment]
This is not reproducible on Linux with .NET 6, so macOS (and likely other non-Linux Unices) are affected.

**Comment by am11** [comment]
Output of `dtruss -f ~/.dotnet6/dotnet bin/Release/net6.0/testdevtty.dll | curl -F"sprunge=<-" http://sprunge.us`: http://sprunge.us/6QWmAA

^ @tmds, `open("/dev/tty"` looks normal, nothing is jumping out at me. 😕

**Comment by tmds** [comment]
Your stacktrace is different:
```
Unhandled exception. System.IO.IOException: Device not configured : '/dev/tty'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.IO.File.<WriteAllBytesAsync>g__Core|72_0(String path, Byte[] bytes, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /Users/am11/projects/testdevtty/Program.cs:line 19
   at Program.<Main>(String[] args)
```

This is interesting:
```
lseek(0x14, 0x0, 0x1)		 = 0 0
```
.NET does this to find out whether the file is 'seekable'.

On Linux this fails with `ESPIPE`. On macOS it succeeds.

That determines whether bytes are written using `write` or `pwrite` (introduced in .NET 6):

https://github.com/dotnet/runtime/blob/8e4c996ae35aa803813a89faebb03eb01821c1a2/src/libraries/System.Private.CoreLib/src/System/IO/RandomAccess.Unix.cs#L93-L95

So on Linux this uses `write` as before, while on macOS this is now using `pwrite` which fails.

**Comment by tmds** [comment]
> Your stacktrace is different:

I mean from the one in CI on https://github.com/dotnet/runtime/pull/58434 which fails on `open` with the same message. I assume that has to do with how the terminal is setup in CI, and is not a regression.

**Comment by tmds** [comment]
The root cause is that `CanSeek` does not indicate support for `pwrite`/`pread`.

I see two options:
- Let `Stream` use `write`/`read` always. Then using `Stream` always works. Using `RandomAccess` may not work for files that don't support random access (like `/dev/tty`).
This has a behavioral impact on `Stream` which does now do its own position tracking and uses that offset for reading/writing.
- Make `RandomAccess` fall back from `pread`/`pwrite` to `read`/`write` after observing specific errors like `ESPIPE` and `ENXIO`.

@stephentoub @am11 @Jozkee @carlossanlop @adamsitnik do you prefer one of these options? or see other options?

**Comment by Jozkee** [comment]
Why `lseek` succeds in macOS? Even the [doc page](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/lseek.2.html) says that it should fail with ESPIPE for a FIFO. 
Could another approach be: fix `CanSeek` in macOS so it can behave as Linux?

**Comment by Jozkee** [comment]
> Let Stream use write/read always. Then using Stream always works. Using RandomAccess may not work for files that don't support random access (like /dev/tty).
This has a behavioral impact on Stream which does now do its own position tracking and uses that offset for reading/writing.

Could there be any perf. regressions in doing this? I assume perf. was the main reason why we changed to pread/pwrite.

**Comment by am11** [comment]
> Make `RandomAccess` fall back from `pread`/`pwrite` to `read`/`write` after observing specific errors like `ESPIPE` and `ENXIO`.

Perhaps a bit more defensive approach:
`if ((e is ESPIPE || e is ENXIO) && device.mode is not S_IFREG) { /* fallback to .NET 5 behavior */ }`

**Comment by tmds** [comment]
> Why lseek succeds in macOS? Even the doc page says that it should fail with ESPIPE for a FIFO.
Could another approach be: fix CanSeek in macOS so it can behave as Linux?

`/dev/tty` is a character oriented device, and not a fifo.

I don't know how to fix `CanSeek` so it is guaranteed to match _supports pread/pwrite_.

I think it's better to do this based on the `pread`/`pwrite` errno, which actually saves you the cost of the syscalls performed in 'improved' `CanSeek`.

> Could there be any perf. regressions in doing this? I assume perf. was the main reason why we changed to pread/pwrite.

I think not. It impacts the ordering of concurrent reads/writes, which is well defined when using `pread`/`pwrite`.

Personally, I think users should be using `RandomAccess` and be explicit about the offsets if they want to want to do concurrent operations.

> Perhaps a bit more defensive approach:
if ((e is ESPIPE || e is ENXIO) && device.mode is not S_IFREG) { /* fallback to .NET 5 behavior */ }

`device.mode is not S_IFREG` is not needed (and would require an extra syscall).

`fallback to .NET 5 behavior.` That is: use `read`/`write` instead of `pread`/`pwrite`, or do you mean something else?

**Comment by stephentoub** [comment]
> do you prefer one of these options? or see other options?

We should do:
> Make RandomAccess fall back from pread/pwrite to read/write after observing specific errors like ESPIPE and ENXIO.

We plan to allow RandomAccess to be used with arbitrary file handles, not just seekable ones, and not just unseekable ones from FileStream, e.g.
https://github.com/dotnet/runtime/issues/58381
so we shouldn't further special-case FileStream with internal hooks into RandomAccess.  One of the issues I raised from the get-go is RandomAccess isn't the ideal name given this, but it's what we chose and it could be worse :)

**Comment by Jozkee** [comment]
@stephentoub so should the plan be to merge the PR https://github.com/dotnet/runtime/pull/58506? If so, do you think is far from merging?
