### ISSUE TITLE
[tvOS] System.ExecutionEngineException : Attempting to JIT compile method while running in aot-only mode.

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#59855]
https://github.com/dotnet/runtime/pull/59503/checks?check_run_id=3748806564

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59503-merge-0d23189e73774107af/System.Xml.XmlSerializer.ReflectionOnly.Tests/1/testResults.xml?sv=2019-07-07&se=2021-10-19T18%3A57%3A45Z&sr=c&sp=rl&sig=2%2BW5uhjsUT%2FqCvzJ1b3X2b2JKMkyQq6smjUoPD6aaOc%3D

```
<test name="XmlSerializerTests.DerivedTypeWithDifferentOverrides" type="XmlSerializerTests" method="DerivedTypeWithDifferentOverrides" time="0.0072259" result="Fail">
    <failure exception-type="System.InvalidOperationException">
        <message><![CDATA[System.InvalidOperationException : There is an error in XML document (1, 194).\n---- System.ExecutionEngineException : Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_DerivedTypeWithDifferentOverrides_string (SerializationTypes.DerivedTypeWithDifferentOverrides,string)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.\n]]></message>
        <stack-trace><![CDATA[   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
        at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
        at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
        at XmlSerializerTests.SerializeAndDeserialize[DerivedTypeWithDifferentOverrides](DerivedTypeWithDifferentOverrides value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns)
        at XmlSerializerTests.DerivedTypeWithDifferentOverrides()
        at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        at System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.<>c__DisplayClass1_2`2[[SerializationTypes.DerivedTypeWithDifferentOverrides, System.Xml.XmlSerializer.ReflectionOnly.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetSetMemberValueDelegateWithType>b__2(Object o, Object p)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.<>c__DisplayClass53_4.<WriteLiteralStructMethod>b__7(Object value)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMembers(Object& o, Member[] members, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.ReadObject()
        at System.Xml.Serialization.XmlSerializer.DeserializeUsingReflection(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
        at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)]]></stack-trace>
    </failure>
</test>
<test name="XmlSerializerTests.Xml_SerializeClassThatImplementsInteface" type="XmlSerializerTests" method="Xml_SerializeClassThatImplementsInteface" time="0.0039248" result="Fail">
    <failure exception-type="System.InvalidOperationException">
        <message><![CDATA[System.InvalidOperationException : There is an error in XML document (1, 191).\n---- System.ExecutionEngineException : Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_ClassImplementsInterface_string (SerializationTypes.ClassImplementsInterface,string)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.\n]]></message>
        <stack-trace><![CDATA[   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
        at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
        at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
        at XmlSerializerTests.SerializeAndDeserialize[ClassImplementsInterface](ClassImplementsInterface value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns)
        at XmlSerializerTests.Xml_SerializeClassThatImplementsInteface()
        at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        at System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.<>c__DisplayClass1_2`2[[SerializationTypes.ClassImplementsInterface, System.Xml.XmlSerializer.ReflectionOnly.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetSetMemberValueDelegateWithType>b__2(Object o, Object p)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.<>c__DisplayClass53_4.<WriteLiteralStructMethod>b__7(Object value)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMembers(Object& o, Member[] members, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.ReadObject()
        at System.Xml.Serialization.XmlSerializer.DeserializeUsingReflection(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
        at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)]]></stack-trace>
    </failure>
</test>
<test name="XmlSerializerTests.DerivedTypeWithDifferentOverrides2" type="XmlSerializerTests" method="DerivedTypeWithDifferentOverrides2" time="0.0047674" result="Fail">
    <failure exception-type="System.InvalidOperationException">
        <message><![CDATA[System.InvalidOperationException : There is an error in XML document (1, 195).\n---- System.ExecutionEngineException : Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_DerivedTypeWithDifferentOverrides2_string (SerializationTypes.DerivedTypeWithDifferentOverrides2,string)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.\n]]></message>
        <stack-trace><![CDATA[   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
        at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
        at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
        at XmlSerializerTests.SerializeAndDeserialize[DerivedTypeWithDifferentOverrides2](DerivedTypeWithDifferentOverrides2 value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns)
        at XmlSerializerTests.DerivedTypeWithDifferentOverrides2()
        at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        at System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.<>c__DisplayClass1_2`2[[SerializationTypes.DerivedTypeWithDifferentOverrides2, System.Xml.XmlSerializer.ReflectionOnly.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<GetSetMemberValueDelegateWithType>b__2(Object o, Object p)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.<>c__DisplayClass53_4.<WriteLiteralStructMethod>b__7(Object value)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMembers(Object& o, Member[] members, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, Fixup fixup, Member member)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(Member[] expectedMembers, Member anyElementMember, UnknownNodeAction elementElseAction, Fixup fixup, CheckTypeSource checkTypeSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElements(Member[] expectedMembers, UnknownNodeAction elementElseAction, UnknownNodeAction elseAction, Member anyElement, Member anyText, Fixup fixup, List`1 checkTypeHrefsSource)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping)
        at System.Xml.Serialization.ReflectionXmlSerializationReader.ReadObject()
        at System.Xml.Serialization.XmlSerializer.DeserializeUsingReflection(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
        at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)]]></stack-trace>
    </failure>
</test>
```

cc @steveisok

**Comment by steveisok** [comment]
As a workaround, we can enable interpreter fallback in order to get around this.

**Comment by steveisok** [comment]
Interpreter fallback is the only supported option at this time.  Closing as we aren't going to fix it.

**Comment by StephenMolloy** [comment]
We'll look at using a potential workaround on the serializer side for this.

**Comment by StephenMolloy** [comment]
I have re-enabled a bunch of serialization tests in PR #118507.
Per these two runs ([1118444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118444), [1118071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118071)), none of these testcases are failing anymore.
