### ISSUE TITLE
parameterBuilder.SetConstant NullReferenceException

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#5987]
```
        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("x"), AssemblyBuilderAccess.RunAndSave);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule("x");
        var typeBuilder = moduleBuilder.DefineType("C", TypeAttributes.Class);
        var methodBuilder = typeBuilder.DefineMethod("M", MethodAttributes.Static);
        methodBuilder.SetParameters(typeof(void), typeof(TimeSpan));

        var parameterBuilder = methodBuilder.DefineParameter(0, ParameterAttributes.HasDefault, "p");
        parameterBuilder.SetConstant(null); //NullReferenceException
```

**Comment by steveharter** [comment]
NullReferenceException still repros on 4.8

```
at System.Reflection.Emit.TypeBuilder.SetConstantValue(ModuleBuilder module, Int32 tk, Type destType, Object value)
at System.Reflection.Emit.ParameterBuilder.SetConstant(Object defaultValue)
```

**Comment by am11** [comment]
> NullReferenceException still repros on 4.8

It does not repro with .NET Core since release 3.0 (https://github.com/dotnet/coreclr/commit/fceac03e8202fb07dc1bb3b4f3ec3cf0921e12de).
Should this be moved to https://github.com/microsoft/dotnet-framework-early-access/issues repository to track 4.8 progress as there is nothing to fix in this repo?

**Comment by steveharter** [comment]
Closing; this does not meet the bar for .NET Framework servicing.
