### ISSUE TITLE
plugins fail to load for dotnet 6 single file - self contained app

### ISSUE THREAD

**Issue by freddyrios** [dotnet/runtime#59961]
### Description

Running plugins with dotnet 6 rc1 for single file, self contained applications broke. The issue was found originally in Linux, but was also reproduced on windows. Specifically the AssemblyDependencyResolver's constructor throws an exception when loading the plugin.

To reproduce follow the instructions on the readme in this isolated reproduction of the issue: https://github.com/freddyrios/pluginsloadfailure.

Alternatively follow microsoft documentation on creating an application with plugins https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support and publish it as a single file, self contained app with the runtime identifier that matches your system.

### Configuration

dotnet --version: 6.0.100-rc.1.21463.6
reproduced both on windows 10 and raspbian (linux / debian)
windows 10 was x64 and raspbian is arm
doesn't look specific to the OS or architecture

### Regression?

It is a regression, see the demo which shows doing the same steps with a different target breaks.

### Other information

This is the stacktrace:
> System.InvalidOperationException: Cannot load hostpolicy library. AssemblyDependencyResolver is currently only supported if the runtime is hosted through hostpolicy library.
>  ---> System.EntryPointNotFoundException: Entry point was not found.
>    at Interop.HostPolicy.corehost_set_error_writer(IntPtr errorWriter)
>    at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
>    --- End of inner exception stack trace ---
>    at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componeyntAssemblyPath)
>    at AppWithPlugin.PluginLoadContext..ctor(String pluginPath) in [redacted]\pluginsloadfailure\AppWithPlugin\PluginLoadContext.cs:line 13
>    at AppWithPlugin.Program.LoadPlugin(String relativePath) in [redacted]\pluginsloadfailure\AppWithPlugin\Program.cs:line 71
>    at AppWithPlugin.Program.<>c.<Main>b__0_0(String pluginPath) in [redacted]\pluginsloadfailure\AppWithPlugin\Program.cs:line 29
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
>    at AppWithPlugin.Program.Main(String[] args) in [redacted]\pluginsloadfailure\AppWithPlugin\Program.cs:line 16

**Comment by vitek-karas** [comment]
As far as I can tell it's a "regression" in single-file - specifically when hostpolicy is part of the apphost, which is true for any superhost.

It works a non-single-file SCD app just fine.
My guess - the PInvoke redirection doesn't kick in for hostpolicy - don't know why.

**Comment by freddyrios** [comment]
@vitek-karas yes, it is only a regression when making it a single file + self contained app.

Making it non single file or non self contained works.

**Comment by freddyrios** [comment]
@vitek-karas forgot to add, that's what we have been running with .net 5.

**Comment by vitek-karas** [comment]
I'm actually surprised that it worked on .net 5 - I would expect this to break even on .net 5 (windows or not)

**Comment by vitek-karas** [comment]
It does indeed work on .net 5 - interesting...

The theory is that in both cases the `hostpolicy` is part of the host/superhost, and since it seems the DllImport fails, it's probably because we don't correctly "Redirect" the PInvoke "inside".

This was the case already in .NET 5, but maybe something else changed.

This will be much easier to solve for @VSadov because he knows exactly how this works...

**Comment by am11** [comment]
```sh
$ dotnet publish HelloPlugin -c Release -f net6.0 -o test
$ dotnet publish AppWithPlugin -c Release --use-current-runtime -self-contained -p:PublishSingleFile=true -f net6.0 -o test
$ test/AppWithPlugin

Loading commands from: /home/am11/projects/pluginsloadfailure/HelloPlugin.dll
System.InvalidOperationException: Cannot load hostpolicy library. AssemblyDependencyResolver is currently only supported if the runtime is hosted through hostpolicy library.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'corehost_set_error_writer' in shared library 'libhostpolicy'.
   at Interop.HostPolicy.corehost_set_error_writer(IntPtr errorWriter)
   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
```

`corehost_set_error_writer` is indeed missing from singlefile host:

```sh
$ strings ~/.dotnet6/packs/Microsoft.NETCore.App.Host.linux-musl-x64/6.0.0-rtm.21504.6/runtimes/linux-musl-x64/native/singlefilehost |\
    grep corehost_

corehost_main
corehost_main_with_output_buffer
corehost_initialize
corehost_resolve_component_dependencies
Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.
corehost_resolve_component_dependencies results: {
```

vs. 5.0
```sh
$ strings ~/.dotnet5/packs/Microsoft.NETCore.App.Host.linux-musl-x64/5.0.10/runtimes/linux-musl-x64/native/singlefilehost |\
    grep corehost_

corehost_resolve_component_dependencies
corehost_main
corehost_load
corehost_set_error_writer
corehost_main_with_output_buffer
corehost_initialize
corehost_unload
corehost_main
corehost_main_with_output_buffer
corehost_initialize
corehost_resolve_component_dependencies
Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.
corehost_resolve_component_dependencies results: {
```

**Comment by VSadov** [comment]
I have implemented a fix, and it works on 6.0, but I see 1 failure in `Bundled_Framework_dependent_Targeting50_App`

It is a framework dependent singlefile configuration.  (so far I only tested on Windows).
It fails with 
```
2147450750. Detailed error: Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.\\r\\n\\r\\n   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssembl
```

@vitek-karas  - do we expect this configuration to work? 
I am not entirely sure what the error means. We should have called main, I think.

**Comment by vitek-karas** [comment]
It should not fail like that. I'll have to look into this.

**Comment by vitek-karas** [comment]
I prepared a fix and sent it to your PR via another PR https://github.com/VSadov/runtime/pull/3.

**Comment by eglasius** [comment]
@VSadov did the fix merged into the dotnet 6 branch made it to the rc2?

**Comment by freddyrios** [comment]
thanks all for the quick response!
