### ISSUE TITLE
System.Tests.TimeZoneInfoTests.TestWindowsNlsDisplayNames failed on release coreclr windows x86 Debug 

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#60097]
See https://github.com/dotnet/runtime/pull/53645/checks?check_run_id=3820429571

https://helix.dot.net/api/2019-06-17/jobs/79625b47-4c55-4ca7-a9aa-d10c53e4099c/workitems/System.Runtime.Tests/console

```
Unhandled exception. Xunit.Sdk.TrueException: The display name '(UTC-08:00) Pacific Time (US & Canada)' should be different between en-US and zh-HK.
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 95
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 83
   at System.Tests.TimeZoneInfoTests.<>c.<TestWindowsNlsDisplayNames>b__122_0() in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 2806
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Tests.TimeZoneInfoTests.TestWindowsNlsDisplayNames [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.TrueException: The display name '(UTC-08:00) Pacific Time (US & Canada)' should be different between en-US and zh-HK.
        Expected: True
        Actual:   False
        /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs(2806,0): at System.Tests.TimeZoneInfoTests.<>c.<TestWindowsNlsDisplayNames>b__122_0()
        
        Child process:
          System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.TimeZoneInfoTests+<>c Void <TestWindowsNlsDisplayNames>b__122_0()    
```

FYI @tarekgh @mattjohnsonpint

**Comment by tarekgh** [comment]
Looks it is Win7 specific failure.

**Comment by tarekgh** [comment]
Closing this one as it is tracked by https://github.com/dotnet/runtime/issues/60119
