### ISSUE TITLE
Test failure System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60157]
Run: [runtime-coreclr libraries-jitstressregs 20211003.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1400246&view=ms.vss-test-web.build-test-results-tab&runId=40666302&resultId=133045&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs3-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndName(viaSpan: True)

net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs4-Windows.10.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(viaSpan: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromData(viaSpan: True)

```
**Error message:**
```
Assert.Equal() Failure
Expected: 85
Actual:   0


Stack trace
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.VerifyExpectedRequest(Rfc3161TimestampRequest request, Boolean viaSpan) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 115
   at System.Security.Cryptography.Pkcs.Tests.TimestampRequestTests.BuildExpectedRequest_FromHashAndOid(Boolean viaSpan) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/Rfc3161/TimestampRequestTests.cs:line 54
```

**Comment by bartonjs** [comment]
Duplicate of #59455 / #59444
