### ISSUE TITLE
System.ArgumentException : Font '?' cannot be found. on openSUSE docker

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/runtime#60290]
When added openSUSE docker into the CI matrix I got following error:

Font '?' cannot be found.

<details>
  <summary>Failing tests:</summary>

```
  MonoTests.System.Drawing.Imaging.MetafileFulltrustTest.Measure [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/mono/System.Imaging/MetafileTest.cs(378,0): at MonoTests.System.Drawing.Imaging.MetafileFulltrustTest.Measure()
    System.Drawing.Printing.Tests.PrintControllerTests.OnStartPage_InvokeWithPrint_ReturnsNull [SKIP]
      Condition(s) not met: "IsAnyInstalledPrinters"
    System.Drawing.Tests.SolidBrushTests.Ctor_Color [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.SolidBrushTests.Color_EmptyAndGetDisposed_ThrowsArgumentException [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.Font_Equals_DifferentFontFamily [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(28,0): at System.Drawing.Tests.FontTests.FontFamily_Equals_DifferentFamily_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_GdiCharSet [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(236,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_GdiCharSet_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.ToString_Invoke_ReturnsExpected [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.GetHeight_NullGraphics_ThrowsArgumentNullException [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(584,0): at System.Drawing.Tests.FontTests.GetHeight_NullGraphics_ThrowsArgumentNullException()
    System.Drawing.Tests.FontTests.FontFamily_Equals_NullObject [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(61,0): at System.Drawing.Tests.FontTests.FontFamily_Equals_NullObject()
    System.Drawing.Tests.FontTests.Ctor_Family_Size [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(15,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.GetHeight_Parameterless_ReturnsExpected [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.Ctor_FamilyName_Size [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(15,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_FamilyName_Size_Unit [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(146,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Unit_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_Family_Size_Style [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(100,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_FamilyName_Size_Style_Unit_GdiCharSet_GdiVerticalFont [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(282,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_GdiCharSet_GdiVerticalFont_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_FamilyName_Size_Style_Unit [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(190,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_FamilyName_Size_Style_Unit_GdiCharSet [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(236,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_GdiCharSet_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_InvalidUnit_ThrowsArgumentException [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.Ctor_FamilyName_Size_Style [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(100,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.GetHashCode_DifferentNameSameSizeStyleUnit_HashCodeIsNotSame [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(986,0): at System.Drawing.Tests.FontTests.GetHashCode_DifferentNameSameSizeStyleUnit_HashCodeIsNotSame()
    System.ComponentModel.TypeConverterTests.FontConverterTest.GetFontPropsSorted [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Font.Unix.cs(61,0): at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Font.Unix.cs(300,0): at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
        /_/src/libraries/System.Drawing.Common/tests/System/Drawing/FontConverterTests.cs(102,0): at System.ComponentModel.TypeConverterTests.FontConverterTest.GetFontPropsSorted()
    System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_GdiCharSet_GdiVerticalFont [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(282,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_GdiCharSet_GdiVerticalFont_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.GetHeight_Graphics_ReturnsExpected [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.Clone_Invoke_ReturnsExpected [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.Ctor_DisposedFont_Success [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
    System.Drawing.Tests.FontTests.Equals_Other_ReturnsExpected [FAIL]
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(463,0): at System.Drawing.Tests.FontTests.Equals_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Font_Equals_SameFontFamily [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(21,0): at System.Drawing.Tests.FontTests.FontFamily_Equals_SameFamily_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.ToLogFont_NullLogFont_ThrowsArgumentNullException [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.ComponentModel.TypeConverterTests.FontConverterTest.TestConvertFrom [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/tests/System/Drawing/FontConverterTests.cs(118,0): at System.ComponentModel.TypeConverterTests.FontConverterTest.TestConvertFormData()
    System.Drawing.Tests.FontTests.ToLogFont_DisposedGraphics_ThrowsArgumentException [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(876,0): at System.Drawing.Tests.FontTests.ToLogFont_DisposedGraphics_ThrowsArgumentException()
    System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(unit: Document) [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(768,0): at System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(GraphicsUnit unit)
    System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(unit: Inch) [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(768,0): at System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(GraphicsUnit unit)
    System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(unit: Millimeter) [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(768,0): at System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(GraphicsUnit unit)
    System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(unit: Pixel) [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(768,0): at System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(GraphicsUnit unit)
    System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(unit: Point) [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(768,0): at System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(GraphicsUnit unit)
    System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(unit: World) [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(768,0): at System.Drawing.Tests.FontTests.SizeInPoints_Get_ReturnsExpected(GraphicsUnit unit)
    System.Drawing.Tests.FontTests.ToHfont_Disposed_ThrowsArgumentException [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.ToLogFont_NullGraphics_ThrowsArgumentNullException [SKIP]
      Condition(s) not met: "GetIsWindowsOrAtLeastLibgdiplus6"
    System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(190,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Style_Unit_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
    System.Drawing.Tests.FontTests.Ctor_DisposedFamily_ThrowsArgumentException [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(374,0): at System.Drawing.Tests.FontTests.Ctor_DisposedFamily_ThrowsArgumentException()
    System.Drawing.Tests.FontTests.GetHeight_Disposed_ThrowsArgumentException [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(209,0): at System.Drawing.FontFamily.GetGdipGenericSansSerif()
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(203,0): at System.Drawing.FontFamily.get_GenericSansSerif()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(609,0): at System.Drawing.Tests.FontTests.GetHeight_Disposed_ThrowsArgumentException()
    System.Drawing.Tests.FontTests.Ctor_Family_Size_Unit [FAIL]
      System.ArgumentException : Font '?' cannot be found.
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(96,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(124,0): at System.Drawing.FontFamily..ctor(GenericFontFamilies genericFamily)
        /_/src/libraries/System.Drawing.Common/src/System/Drawing/FontFamily.cs(222,0): at System.Drawing.FontFamily.get_GenericMonospace()
        /_/src/libraries/System.Drawing.Common/tests/FontTests.cs(146,0): at System.Drawing.Tests.FontTests.Ctor_Family_Size_Unit_TestData()+MoveNext()
        /_/src/libraries/System.Linq/src/System/Linq/Select.cs(136,0): at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
```
</details>

The docker file is: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/opensuse/15.2/helix/amd64/Dockerfile

Do you have any suggestion what package is missing or what is going on?

/cc @tarekgh

**Comment by safern** [comment]
Based on the openSuse docs:

> System fonts must be installed in the /usr/share/fonts/ directory. These fonts can be used by all users on the machine.

I just inspected the docker container and `/usr/share/fonts/` is empty. 

> If the font you want to install is provided by openSUSE online repositories, use YaST or zypper to install the package.

I guess we need to install some font from: http://download.opensuse.org/repositories/M17N:/fonts/openSUSE_Leap_15.2/src/

I don't know which one though as libgdiplus uses `Courier New` for the API we are calling for the tests.

**Comment by safern** [comment]
Yeah it would be more resilient if /usr/share/fonts is empty.

**Comment by ViktorHofer** [comment]
We no longer support System.Drawing on non Windows. Closing.
