### ISSUE TITLE
Crossgen2: System.BadImageFormatException: Read out of bounds

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#60343]
### Description

I'm compiling my app using composite crossgen2, with custom trimming behavior, but I got `System.BadImageFormatException: Read out of bounds`.

### Reproduction Steps

1. Clone https://github.com/hez2010/GitHubAvalon
2. `dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true /p:PublishReadyToRunComposite=true /p:PublishSingleFile=true /p:PublishTrimmed=true /p:TrimMode=Link`
3. See error

The code causing error (for skipping trimming `Avalonia.*` and `GitHubAvalon` assemblies):

```xml
  <Target Name="ConfigureTrimming"
        BeforeTargets="PrepareForILLink">
    <ItemGroup>
      <ManagedAssemblyToLink Condition="!$([System.String]::new('%(Filename)').StartsWith('Avalonia')) AND '%(Filename)' != 'GitHubAvalon'">
        <IsTrimmable>true</IsTrimmable>
      </ManagedAssemblyToLink>
    </ItemGroup>
  </Target>
```

### Expected behavior

No error while building

### Actual behavior

```
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetFlags(TypeDefinitionHandle handle)
   at System.Reflection.Metadata.TypeDefinition.get_Attributes()
   at Internal.TypeSystem.Ecma.EcmaType.get_ContainingType()
   at Internal.TypeSystem.Ecma.EcmaType.InitializeHashCode()
   at Internal.TypeSystem.Ecma.EcmaType.GetHashCode()
   at Internal.TypeSystem.MethodDesc.ComputeHashCode()
   at Internal.TypeSystem.MethodDesc.GetHashCode()
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at ILCompiler.IBC.IBCProfileParser.ParseIBCDataFromModule(EcmaModule ecmaModule)
   at ILCompiler.ProfileDataManager..ctor(Logger logger, IEnumerable`1 possibleReferenceModules, IEnumerable`1 inputModules, IEnumerable`1 versionBubbleModules, ModuleDesc nonLocalGenericsHome, IReadOnlyList`1 mibcFiles, CallChainProfile callChainProfile, CompilerTypeSystemContext context, ReadyToRunCompilationModuleGroupBase compilationGroup, Boolean embedPgoDataInR2RImage)
   at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```

### Regression?

No

### Known Workarounds

No

### Configuration

.NET 6 RC2

### Other information

Binary log: 
[binlog.zip](https://github.com/dotnet/runtime/files/7339460/binlog.zip)

**Comment by mangod9** [comment]
Hey @hez2010, so I assume the exception occurs only with Trimming enabled, but works with R2RComposite + SingleFile?

**Comment by hez2010** [comment]
Yes.

**Comment by mangod9** [comment]
Adding @agocke @VSadov

**Comment by mangod9** [comment]
@agocke perhaps this needs to be moved to the trimming area? @hez2010 does this still repro on .NET 7 previews?

**Comment by ivdiazsa** [comment]
@mangod9 I just confirmed, this still repros on Preview 7.

**Comment by agocke** [comment]
@sbomer Could you take a look?

**Comment by davidwrighton** [comment]
As Ibc isn't the static pgo tech we want to maintain going forward, instead of adding a flag to disable ibc processing, I'm going to add a flag to enable ibc processing. We haven't had good results with Ibc tech as the mibc logic works much better, and its been a bit of a bug farm, so I'd prefer to just turn it off, and push folks to our more capable mibc pathway.
