### ISSUE TITLE
Couldn't find a valid ICU package installed on the system. 

### ISSUE THREAD

**Issue by qyangaa** [dotnet/runtime#60439]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: linux

I followed  https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md#troubleshooting
to install the package and change library path. But still doesn't work. 

```
dotnet run
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at System.Text.EncodingHelper.GetCharset()
   at System.Text.EncodingHelper.GetEncodingFromCharset()
   at System.ConsolePal.GetConsoleEncoding()
   at System.Console+<>c.<get_OutputEncoding>b__19_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_OutputEncoding()
   at System.Console.CreateOutputWriter(System.IO.Stream)
   at System.Console+<>c.<get_Out>b__26_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_Out()
   at System.Console.WriteLine(System.String)
   at myApp.Program.Main(System.String[])
```

**Comment by daxxog** [comment]
> Hi @qyangaa
> 
> ```
> export CLR_ICU_VERSION_OVERRIDE="50.2"
> ```
> 
> If your RHEL icu version is 50.2, it is able to run `yum info icu` for double check the version.
> 
> We met [the similar issue](https://github.com/dotnet/runtime/issues/13527) when porting to MIPS64. [Fixed in 5.0.0](https://github.com/dotnet/runtime/pull/34095).
> 
> Thanks, Leslie Zhai

I had something similar happen to me on Archlinux, when the icu package was recently updated: https://github.com/archlinux/svntogit-packages/tree/36f4025b3bb8b0832b7ad452afe6bd605e894158/trunk

I did something like:
`export CLR_ICU_VERSION_OVERRIDE=$(pacman -Q icu | awk '{split($0,a," ");print a[2]}' | awk '{split($0,a,"-");print a[1]}')`
to fix.

Thanks for the tip!

**Comment by WildReiserUE** [comment]
> > Hi @qyangaa
> > ```
> > export CLR_ICU_VERSION_OVERRIDE="50.2"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your RHEL icu version is 50.2, it is able to run `yum info icu` for double check the version.
> > We met [the similar issue](https://github.com/dotnet/runtime/issues/13527) when porting to MIPS64. [Fixed in 5.0.0](https://github.com/dotnet/runtime/pull/34095).
> > Thanks, Leslie Zhai
> 
> I had something similar happen to me on Archlinux, when the icu package was recently updated: https://github.com/archlinux/svntogit-packages/tree/36f4025b3bb8b0832b7ad452afe6bd605e894158/trunk
> 
> I did something like: `export CLR_ICU_VERSION_OVERRIDE=$(pacman -Q icu | awk '{split($0,a," ");print a[2]}' | awk '{split($0,a,"-");print a[1]}')` to fix.
> 
> Thanks for the tip!

This work for me! THX!!! But this has to be done before each call to the ICU. It feels like it's being overwritten by something.

**Comment by nfp0** [comment]
> > Hi @qyangaa
> > ```
> > export CLR_ICU_VERSION_OVERRIDE="50.2"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your RHEL icu version is 50.2, it is able to run `yum info icu` for double check the version.
> > We met [the similar issue](https://github.com/dotnet/runtime/issues/13527) when porting to MIPS64. [Fixed in 5.0.0](https://github.com/dotnet/runtime/pull/34095).
> > Thanks, Leslie Zhai
> 
> I had something similar happen to me on Archlinux, when the icu package was recently updated: https://github.com/archlinux/svntogit-packages/tree/36f4025b3bb8b0832b7ad452afe6bd605e894158/trunk
> 
> I did something like: `export CLR_ICU_VERSION_OVERRIDE=$(pacman -Q icu | awk '{split($0,a," ");print a[2]}' | awk '{split($0,a,"-");print a[1]}')` to fix.
> 
> Thanks for the tip!

@daxxog This worked for me. Thanks!
I'm still being affected by this issue today on Arch. So, in our case, the root cause is on the Arch package?
Is there an issue open for it?

**Comment by bernardbr** [comment]
> CLR_ICU_VERSION_OVERRIDE

Thank you!

For the Ubuntu, you can do the same:

`export CLR_ICU_VERSION_OVERRIDE=$(dpkg -s libicu-dev | grep '^Version:' | awk '{split($2,a,"-"); print a[1]}')

**Comment by bernardbr** [comment]
> > Hi @qyangaa
> > ```
> > export CLR_ICU_VERSION_OVERRIDE="50.2"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your RHEL icu version is 50.2, it is able to run `yum info icu` for double check the version.
> > We met [the similar issue](https://github.com/dotnet/runtime/issues/13527) when porting to MIPS64. [Fixed in 5.0.0](https://github.com/dotnet/runtime/pull/34095).
> > Thanks, Leslie Zhai
> 
> I had something similar happen to me on Archlinux, when the icu package was recently updated: https://github.com/archlinux/svntogit-packages/tree/36f4025b3bb8b0832b7ad452afe6bd605e894158/trunk
> 
> I did something like: `export CLR_ICU_VERSION_OVERRIDE=$(pacman -Q icu | awk '{split($0,a," ");print a[2]}' | awk '{split($0,a,"-");print a[1]}')` to fix.
> 
> Thanks for the tip!

Thank you!

For the Ubuntu, you can do the same:

`export CLR_ICU_VERSION_OVERRIDE=$(dpkg -s libicu-dev | grep '^Version:' | awk '{split($2,a,"-"); print a[1]}')`

**Comment by MichaelSimons** [comment]
[Triage] Canonical has taken over the ownership and production of .NET Snaps.  This is described in the [runtime](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap-runtime) and [sdk](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap-sdk) snap documentation.  If you experience issues with the snaps or have suggestions on how to improve them, please open an issue at https://github.com/canonical/dotnet-snap. Closing issue.
