### ISSUE TITLE
NullReferenceException in JsonSerializer.Deserialize

### ISSUE THREAD

**Issue by Silvenga** [dotnet/runtime#60448]
### Description

When attempting to deserialize a complex type, the deserializer throws a NRE.

### Reproduction Steps

Given the code (occurs in Linqpad + solution code):

```csharp
void Main()
{
	var json = "{\"friendlyName\":\"blah\",\"uri\":\"test:\\/\\/blah\",\"intervalSeconds\":1,\"timeoutSeconds\":1}";
	System.Text.Json.JsonSerializer.Deserialize<Command>(json);
}

public record Command(string FriendlyName,
                      Uri Uri,
                      int IntervalSeconds,
                      int TimeoutSeconds = 10,
                      [property: System.Text.Json.Serialization.JsonIgnore] Guid SubscriptionId = default);
```

### Expected behavior

`System.Text.Json.JsonSerializer.Deserialize` should never throw a NRE.

### Actual behavior

`System.Text.Json.JsonSerializer.Deserialize` throws a NRE with the stack:

```
at .ctor(Object[] )
at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.CreateObject(ReadStackFrame& frame)
at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
at UserQuery.Main(), line 4
```

### Known Workarounds

Removing any one property from my record fixes this. It's somehow the combination of all 4 properties that cause this - which seems just bonkers.

### Configuration

SDK: 5.0.400
Runtime: Microsoft.AspNetCore.App 5.0.9
Architecture: x64

**Comment by eiriktsarpalis** [comment]
I can confirm that the issue reproduces in .NET 5 but has been fixed in .NET 6. I'm not sure what change might have fixed this, @layomia might know.
