### ISSUE TITLE
[tvOS] System.Threading.Channels.Tests : System.InvalidOperationException : The result of the operation was already consumed and may not be used again

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#60472]
Some System.Threading.Channels.Tests tests failed during the library tests run in https://github.com/dotnet/runtime/pull/59503. 

```
Exception messages: System.InvalidOperationException : The result of the operation was already consumed and may not be used again.
Exception stack traces:    at System.Threading.Channels.AsyncOperation.ThrowIncorrectCurrentIdException()
at System.Threading.Channels.AsyncOperation`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetStatus(Int16 token)
at System.Threading.Channels.Tests.ChannelTestBase.ReadAsync_Canceled_CanceledAsynchronously()
--- End of stack trace from previous location ---
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59503-merge-6a39ae2c5ebe465885/System.Threading.Channels.Tests/1/net.dot.System.Threading.Channels.Tests.log?sv=2019-07-07&se=2021-11-04T12%3A32%3A55Z&sr=c&sp=rl&sig=uGlnckHfuNwI574Zg9QR%2Fr0%2BDjML7iDVVEgDHDmLF58%3D

cc @steveisok @akoeplinger

**Comment by stephentoub** [comment]
@steveisok, are these tests disabled?  I don't see a disabled test label, and the issue is from a year and a half ago.

**Comment by steveisok** [comment]
Yes, the entire suite is disabled in tests.proj
