### ISSUE TITLE
[iOS/tvOS] System.Diagnostics.Tests.ProcessTests.TestGetProcesses fails on devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#60588]
This [test](https://github.com/dotnet/runtime/blob/defa26b9e1159f1a2a3470c52084410edff982b6/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs#L1108-L1124) fails with:

```
System.ComponentModel.Win32Exception : Could not get all running Process IDs.

Stack trace
   at Interop.libproc.proc_listallpids()
   at System.Diagnostics.ProcessManager.GetProcessInfos(String machineName)
   at System.Diagnostics.Process.GetProcesses(String machineName)
   at System.Diagnostics.Process.GetProcesses()
   at System.Diagnostics.Tests.ProcessTests.TestGetProcesses()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
I suspect we'll need to bring in the [headers](https://opensource.apple.com/source/xnu/xnu-2422.1.72/libsyscall/wrappers/libproc/libproc.h.auto.html) for proc_listallpids

**Comment by MaximLipnin** [comment]
It might be addressed when https://github.com/dotnet/runtime/issues/61265#issuecomment-966981009 is done.

**Comment by akoeplinger** [comment]
This and the other tests disabled against #60588 on iOS/tvOS can be skipped with SkipOnPlatform since these APIs throw PNSE now.

**Comment by MaximLipnin** [comment]
> This and the other tests disabled against #60588 on iOS/tvOS can be skipped with SkipOnPlatform since these APIs throw PNSE now.

Addressed in https://github.com/dotnet/runtime/pull/61670
