### ISSUE TITLE
[iOS/tvOS] System.IO.Compression.Tests.ZipFile_Unix.UnixCreateSetsPermissionsInExternalAttributes fails on devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#60581]
Most likely not taking into account platform specifics re: permissions

The [test](https://github.com/dotnet/runtime/blob/1c949ace34b913e3d5e3070f132c87b670cac8c9/src/libraries/System.IO.Compression.ZipFile/tests/ZipFile.Unix.cs#L12-L57) fails with:

```
Assert.Equal() Failure
Expected: 3968
Actual:   896

at System.IO.Compression.Tests.ZipFile_Unix.<UnixCreateSetsPermissionsInExternalAttributes>g__EnsureExternalAttributes|0_0(String permissions, ZipArchiveEntry entry)
   at System.IO.Compression.Tests.ZipFile_Unix.UnixCreateSetsPermissionsInExternalAttributes()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by carlossanlop** [comment]
Also affecting the `release/6.0` branch. I'm disabling the tests there too: https://github.com/dotnet/runtime/pull/68867

When this issue gets fixed, the fix needs to get backported to `release/6.0`.
