### ISSUE TITLE
[iOS/tvOS] System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests.TestGetDrives fails on devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#60586]
The [test](https://github.com/dotnet/runtime/blob/fe4d5cf36ff0b421af7d128f32ea6b6fbe10c51a/src/libraries/System.IO.FileSystem.DriveInfo/tests/DriveInfo.Unix.Tests.cs#L27-L41) fails with:

```
System.ExecutionEngineException : Attempting to JIT compile method '(wrapper native-to-managed) void Interop/Sys/<>c__DisplayClass13_0:<GetAllMountPoints>b__0 (byte*)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
Stack trace
   at Interop.Sys.GetAllMountPoints()
   at System.IO.DriveInfo.GetDrives()
   at System.IO.FileSystem.DriveInfoTests.DriveInfoUnixTests.TestGetDrives()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by steveisok** [comment]
The issue manifests itself when calling `Array.Resize` from `GetAllMountPoints`

https://github.com/dotnet/runtime/blob/c2ec86b1c552ac8a1749f9f98e012f707e325660/src/libraries/Common/src/Interop/Unix/System.Native/Interop.MountPoints.cs#L28

@vargaz it looks like Buffer.memmove might be the culprit, but I don't have a good explanation.

https://github.com/dotnet/runtime/blob/c2ec86b1c552ac8a1749f9f98e012f707e325660/src/libraries/System.Private.CoreLib/src/System/Array.cs#L60-L63
