### ISSUE TITLE
Test failure profiler/elt/slowpatheltleave/slowpatheltleave.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60665]
Run: [runtime-coreclr jitstress 20211018.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1429134&view=ms.vss-test-web.build-test-results-tab&runId=41315724&paneView=debug&resultId=100015)

Failed test:
```
CoreCLR Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- profiler/elt/slowpatheltleave/slowpatheltleave.sh

```
**Error message:**
```
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
at SlowPathELTTests.SlowPathELTLeave.Main(String[] args)
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/slowpatheltleave.sh: line 377:    76 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.elt/slowpatheltleave/slowpatheltleave.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false slowpatheltleave.dll ''
Profiler path: /root/helix/work/workitem/e/profiler/elt/slowpatheltleave/libProfiler.so
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Testing leave hooks
x=-123 y=-4.3 str=Hello, test!
SimpleArgsFunc returned Hello from SimpleArgsFunc!
ss=x=1 d=1
MixedStructFunc returned x=4 d=1
ls=x0=0 d0=0 x1=1 d1=1 x2=2 d2=2 x3=3 d3=3
LargeStructFunc returned 3
IntegerStructFunc returned x=21 y=256
Fp32x2StructFunc returned x=1.2 y=2
Fp32x2StructFp32x3StructFunc returned x=6.7 y=10.11 z=13.14
Fp32x3StructFunc returned x=6.7 y=10.11 z=3
Fp32x3StructFp32x2StructFunc returned x=1.2 y=3.5
Fp32x3StructSingleFp32x3StructSingleFunc returned x=6.7 y=10.11 z=13.14

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Gathering state for process 76 corerun
Crashing thread 0000004c signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.76.dmp
Written 117256192 bytes (28627 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/slowpatheltleave.sh
Expected: True
Actual:   False


Stack trace
   at profiler_elt._slowpatheltleave_slowpatheltleave_._slowpatheltleave_slowpatheltleave_sh()
```

**Comment by davmason** [comment]
I spent quite a bit of time trying to get anything actionable out of the attached dump and was unable. Closing this, will investigate more if it happens again
