### ISSUE TITLE
[7.0] microsoft.net.workload.mono.toolchain\WorkloadManifest.targets hardcodes net6.0 as TFM

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#60745]
### Description

@LoopedBard3 discovered this as part of the benchmarking infrastructure trying to build a net7 blazor-wasm app. The workload manifests hardcodes a `net6.0` TFM: https://github.com/dotnet/runtime/blob/main/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets.in#L118. This causes a build failure:

```
C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\dotnet\sdk\7.0.100-alpha.1.21518.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error MSB4018: The "ProcessFrameworkReferences" task failed unexpectedly.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\WDAGUtilityAccount\Desktop\performance\src\scenarios\test\test.csproj]
```

### Reproduction Steps

* Install latest dotnet 7
* Install wasm-tools workload
* create new blazorwasm project with 'dotnet new blazorwasm'
* attempt to build with 'dotnet build -f net7.0'

### Expected behavior

Works

### Actual behavior

Does not work

**Comment by radical** [comment]
The value is no longer hardcoded: https://github.com/dotnet/runtime/commit/95488fe85a1b3bf3807f310801eadd477b64ce4e .
