### ISSUE TITLE
Test failure System.Drawing.Tests.IconTests.Save_OutputStream_Success(fileName: \"96x96_one_entry_8bit.ico\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60823]
Run: [runtime-coreclr libraries-jitstressregs 20211024.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1438213&view=ms.vss-test-web.build-test-results-tab&runId=41512576&paneView=debug&resultId=125047)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.Drawing.Tests.IconTests.Save_OutputStream_Success(fileName: \"96x96_one_entry_8bit.ico\")

```
**Error message:**
```
System.ArgumentException : Parameter is not valid.


Stack trace
   at System.Drawing.Image.get_RawFormat() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Image.cs:line 284
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Bitmap.cs:line 132
   at System.Drawing.Icon.ToBitmap() in /_/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Unix.cs:line 645
   at System.Drawing.Tests.IconTests.SaveAndCompare(Icon icon, Boolean alpha) in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 795
```

**Comment by ViktorHofer** [comment]
Closing as we support Drawing on non Windows anymore.
