### ISSUE TITLE
[wasm][tests] Regex source generator test failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#60899]
*not* AOT specific.

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1441851&view=logs&jobId=fddee5b2-3265-5a91-40c1-750d81e69f3f&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60701-merge-279b0ef11ef9453caf/System.Text.RegularExpressions.Tests/1/console.9182b2b2.log?sv=2019-07-07&se=2021-11-16T00%3A03%3A20Z&sr=c&sp=rl&sig=%2Bds1Sk032he2qGUBtJpUld%2F2uI%2BKfwxc9tBc7keo6L8%3D)

Hitting this on https://github.com/dotnet/runtime/pull/60701 which fixes https://github.com/dotnet/runtime/issues/60048, and enables these tests.

```
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: None, culture: , input: "abcIiİxyz", match_expected: "Iiİ")
info: Assert.Equal() Failure
info:             ↓ (pos 2)
info: Expected: Iiİ
info: Actual:   Ii
info:             ↑ (pos 2)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: None, culture: , input: "abcIİixyz", match_expected: "Iİi")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: Iİi
info: Actual:
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: None, culture: , input: "abcİIIxyz", match_expected: "İII")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: İII
info: Actual:   II
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: None, culture: , input: "abcİIixyz", match_expected: "İIi")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: İIi
info: Actual:   Ii
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:[^IJKLM]I)", options: None, culture: , input: "iiİiıab", match_expected: "")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected:
info: Actual:   İi
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: Compiled, culture: , input: "abcIiİxyz", match_expected: "Iiİ")
info: Assert.Equal() Failure
info:             ↓ (pos 2)
info: Expected: Iiİ
info: Actual:   Ii
info:             ↑ (pos 2)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: Compiled, culture: , input: "abcIİixyz", match_expected: "Iİi")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: Iİi
info: Actual:
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: Compiled, culture: , input: "abcİIIxyz", match_expected: "İII")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: İII
info: Actual:   II
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: Compiled, culture: , input: "abcİIixyz", match_expected: "İIi")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: İIi
info: Actual:   Ii
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:[^IJKLM]I)", options: Compiled, culture: , input: "iiİiıab", match_expected: "")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected:
info: Actual:   İi
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: NonBacktracking, culture: , input: "abcIiİxyz", match_expected: "Iiİ")
info: Assert.Equal() Failure
info:             ↓ (pos 2)
info: Expected: Iiİ
info: Actual:   Ii
info:             ↑ (pos 2)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: NonBacktracking, culture: , input: "abcIİixyz", match_expected: "Iİi")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: Iİi
info: Actual:
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: NonBacktracking, culture: , input: "abcİIIxyz", match_expected: "İII")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: İII
info: Actual:   II
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:iI+)", options: NonBacktracking, culture: , input: "abcİIixyz", match_expected: "İIi")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected: İIi
info: Actual:   Ii
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: "(?i:[^IJKLM]I)", options: NonBacktracking, culture: , input: "iiİiıab", match_expected: "")
info: Assert.Equal() Failure
info:           ↓ (pos 0)
info: Expected:
info: Actual:   İi
info:           ↑ (pos 0)
info:    at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs:line 334
info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
info: Finished:    System.Text.RegularExpressions.Tests.dll

```

**Comment by stephentoub** [comment]
Thanks, @radical.  That looks like a bug in the test and it shouldn't be assuming the current isn't invariant.  I'll fix it if that's the case.
