### ISSUE TITLE
Test failure System.Security.Cryptography.Hashing.Tests.HashAlgorithmTest.ComputeHashAsync_SupportsCancellation

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61138]
Run: [runtime 20211102.46](https://dev.azure.com/dnceng/public/_build/results?buildId=1451235&view=ms.vss-test-web.build-test-results-tab&runId=41767194&resultId=136925&paneView=debug)

Failed test:
```
net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open

- System.Security.Cryptography.Hashing.Tests.HashAlgorithmTest.ComputeHashAsync_SupportsCancellation
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedCreate_Mismatch

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)


Stack trace
   at System.Security.Cryptography.Hashing.Tests.HashAlgorithmTest.ComputeHashAsync_SupportsCancellation()
--- End of stack trace from previous location ---
```
Failed test:
```
net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"http://www.w3.org/2001/04/xmlenc#sha512\", baseType: typeof(System.Security.Cryptography.SHA512))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"http://www.w3.org/2001/04/xmldsig-more#sha384\", baseType: typeof(System.Security.Cryptography.SHA384))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"http://www.w3.org/2001/04/xmlenc#sha256\", baseType: typeof(System.Security.Cryptography.SHA256))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"http://www.w3.org/2000/09/xmldsig#sha1\", baseType: typeof(System.Security.Cryptography.SHA1))
```
**Error message:**
```
Assert.NotNull() Failure


Stack trace
   at System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(String identifier, Type baseType)
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object , BindingFlags , Span`1& )
```
Failed test:
```
net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open

- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"SHA-512\", baseType: typeof(System.Security.Cryptography.SHA512))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"SHA512\", baseType: typeof(System.Security.Cryptography.SHA512))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"SHA-384\", baseType: typeof(System.Security.Cryptography.SHA384))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(identifier: \"SHA384\", baseType: typeof(System.Security.Cryptography.SHA384))

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedHashAlgorithmCreate(String identifier, Type baseType)
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object , BindingFlags , Span`1& )
```
Failed test:
```
net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open

- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(identifier: \"http://www.w3.org/2001/04/xmldsig-more#hmac-md5\", actualType: typeof(System.Security.Cryptography.HMACMD5))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(identifier: \"http://www.w3.org/2001/04/xmldsig-more#hmac-sha256\", actualType: typeof(System.Security.Cryptography.HMACSHA256))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(identifier: \"System.Security.Cryptography.KeyedHashAlgorithm\", actualType: typeof(System.Security.Cryptography.HMACSHA1))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(identifier: \"System.Security.Cryptography.HMACSHA1\", actualType: typeof(System.Security.Cryptography.HMACSHA1))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(identifier: \"HMACSHA1\", actualType: typeof(System.Security.Cryptography.HMACSHA1))
- System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(identifier: \"http://www.w3.org/2000/09/xmldsig#hmac-sha1\", actualType: typeof(System.Security.Cryptography.HMACSHA1))

```
**Error message:**
```
Assert.IsType() Failure
Expected: System.Security.Cryptography.HMACMD5
Actual:   (null)


Stack trace
   at System.Security.Cryptography.CryptoConfigTests.CryptoConfigTests.NamedKeyedHashAlgorithmCreate(String identifier, Type actualType)
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object , BindingFlags , Span`1& )
```

**Comment by vcsjones** [comment]
I think this should be addressed by https://github.com/dotnet/runtime/pull/61102

**Comment by bartonjs** [comment]
Yep, already fixed.
