### ISSUE TITLE
Visual Studio 2019 is crashing when trying to load a solution with System.AccessViolationException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#61200]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2019-is-crashing-when-tryi/1555393)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9]
I've got a solution for a .NET Framework 4.6.1 desktop app that I'm now unable to load in Visual Studio 2019 after updating to the latest version. It appears to be loading the solution, but then everything disappears.

I checked the Windows Event Log and this is the .NET Runtime entry that's logged:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(System.Data.OleDb.OleDbConnectionString, System.Data.OleDb.DataSourceWrapper ByRef)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(System.Data.OleDb.OleDbConnectionString, System.Data.OleDb.OleDbConnection)
   at System.Data.OleDb.OleDbConnectionStringBuilder.GetProviderInfo(System.String)
   at System.Data.OleDb.OleDbConnectionStringBuilder.get_Keys()
   at System.Data.Common.DbConnectionStringBuilder.get_ConnectionString()
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(System.String)
   at Microsoft.Data.ConnectionUI.AdoDotNetConnectionProperties.Parse(System.String)
   at Microsoft.VisualStudio.DataTools.Providers.Common.CommonConnectionProperties`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Parse(System.String)
   at Microsoft.VisualStudio.Data.Compatibility.NewConnectionProperties.Parse(System.String)
   at Microsoft.VSDesigner.Data.ConnectionString..ctor(System.String, System.String)
   at Microsoft.VSDesigner.VSDesignerPackage.AppSettingsHelper.AddServerExplorerConnections(System.IServiceProvider, System.Collections.IList)
   at Microsoft.VSDesigner.VSDesignerPackage.GlobalConnectionService.Microsoft.VSDesigner.VSDesignerPackage.IGlobalConnectionService.GetConnections(System.IServiceProvider, EnvDTE.Project)
   at Microsoft.VSDesigner.DataSource.DesignConnection.GetConnectionFromAppSettings(System.String, System.String, EnvDTE.Project)
   at Microsoft.VSDesigner.DataSource.DesignConnection.GetConnectionStringObject(EnvDTE.Project)
   at Microsoft.VSDesigner.DataSource.DesignConnection.get_ConnectionStringObject()
   at Microsoft.VSDesigner.DataSource.DbSource.set_Connection(Microsoft.VSDesigner.DataSource.IDesignConnection)
   at Microsoft.VSDesigner.DataSource.DesignDataSource.SetConnectionProperty(Microsoft.VSDesigner.DataSource.Source)
   at Microsoft.VSDesigner.DataSource.DesignDataSource.ReadXmlSchema(Microsoft.VSDesigner.DataSource.DataSourceXmlTextReader)
   at Microsoft.VSDesigner.DataSource.DesignDataSource.ReadXmlSchema(System.String)
   at Microsoft.VSDesigner.DataSource.ProjectDataSourceStorage.GetReadOnlyDataSource(System.Object, EnvDTE.ProjectItem, Boolean, Boolean)
   at Microsoft.VSDesigner.DataSource.Designer.DataSourceEditorFactory.HasIncompatibleSqlCeConnections(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32, System.String)
   at Microsoft.VSDesigner.DataSource.Designer.DataSourceEditorFactory.CreateEditorInstance(UInt32, System.String, System.String, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32, System.Object, System.Object ByRef, System.Object ByRef, System.String ByRef, System.Guid ByRef, Boolean ByRef)
   at Microsoft.VSDesigner.DesignerFramework.BaseEditorFactory.Microsoft.VisualStudio.Shell.Interop.IVsEditorFactory.CreateEditorInstance(UInt32, System.String, System.String, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, UInt32, IntPtr, IntPtr ByRef, IntPtr ByRef, System.String ByRef, System.Guid ByRef, Int32 ByRef)
   at Microsoft.VisualStudio.Shell.Interop.IVsProject2.ReopenItem(UInt32, System.Guid ByRef, System.String, System.Guid ByRef, IntPtr, Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame ByRef)
   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.ReopenDocumentFrame(Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService, Microsoft.VisualStudio.Platform.WindowManagement.StubWindowInfo, Microsoft.VisualStudio.Platform.WindowManagement.ReopenDocumentOptions, Microsoft.VisualStudio.PlatformUI.Shell.DocumentGroup, Int32 ByRef)
   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.ReopenDocumentFrame(Microsoft.VisualStudio.Platform.WindowManagement.IWindowManagerPrivate, Microsoft.VisualStudio.Platform.WindowManagement.StubWindowInfo, Microsoft.VisualStudio.Platform.WindowManagement.ReopenDocumentOptions, Microsoft.VisualStudio.PlatformUI.Shell.DocumentGroup, Int32 ByRef)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.EnsureStubFrameInitialized(Boolean, Microsoft.VisualStudio.Platform.WindowManagement.StubWindowInitializationReason)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame+<>c__DisplayClass502_0.<GetProperty>b__0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetProperty(Int32, System.Object ByRef)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame+MarshalingWindowFrame+<>c__DisplayClass4_0.<Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.GetProperty>b__0()
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`1<Int32>)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame+MarshalingWindowFrame.Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame.GetProperty(Int32, System.Object ByRef)
   at Microsoft.TeamFoundation.Git.Provider.SccSolutionExplorerService.TryGetHierarchyWindow(Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame, Microsoft.VisualStudio.Shell.Interop.IVsUIHierarchyWindow ByRef)
   at Microsoft.TeamFoundation.Git.Provider.SccSolutionExplorerService+<>c__DisplayClass29_0.<Microsoft.VisualStudio.Shell.Interop.IVsWindowFrameEvents.OnFrameIsVisibleChanged>b__0()
   at Microsoft.TeamFoundation.Git.Provider.ComConventionHelper+<>c__DisplayClass1_0.<CallWithCOMConvention>b__0()
   at Microsoft.TeamFoundation.Git.Provider.ComConventionHelper.CallWithCOMConvention(Microsoft.TeamFoundation.Git.CoreServices.ISccServiceHost, System.Func`1<Int32>, Boolean)
   at Microsoft.TeamFoundation.Git.Provider.ComConventionHelper.CallWithCOMConvention(Microsoft.TeamFoundation.Git.CoreServices.ISccServiceHost, System.Action, Boolean)
   at Microsoft.TeamFoundation.Git.Provider.SccSolutionExplorerService.Microsoft.VisualStudio.Shell.Interop.IVsWindowFrameEvents.OnFrameIsVisibleChanged(Microsoft.VisualStudio.Shell.Interop.IVsWindowFrame, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService+<>c__DisplayClass398_0.<OnFrameIsVisibleChanged>b__0(UInt32, Microsoft.VisualStudio.Shell.Interop.IVsWindowFrameEvents)
   at Microsoft.Internal.VisualStudio.PlatformUI.CookieTable`2[[System.UInt32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(Microsoft.Internal.VisualStudio.PlatformUI.CookieTableCallback`2<UInt32,System.__Canon>, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.OnFrameIsVisibleChanged(System.Object, Microsoft.VisualStudio.Platform.WindowManagement.WindowFrameEventArgs)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.RaiseWindowFrameEvent(System.EventHandler`1<Microsoft.VisualStudio.Platform.WindowManagement.WindowFrameEventArgs>)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame+<>c__DisplayClass557_0.<NotifyOnShow>b__0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.NotifyOnShow(Int32)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.frameView_IsSelectedChanged(System.Object, System.EventArgs)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent(System.EventHandler, System.Object, System.EventArgs)
   at Microsoft.VisualStudio.PlatformUI.Shell.View.OnIsSelectedChanged()
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewElement.OnIsSelectedChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup.OnSelectedElementChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at Microsoft.VisualStudio.PlatformUI.Shell.NestedGroup.UpdateSelectionCore(Int32)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup.UpdateSelection(Int32)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup+ViewElementCollection.RemoveSelection(Int32)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup+ViewElementCollection.RemoveItem(Int32)
   at System.Collections.ObjectModel.Collection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Remove(System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewElement.Detach()
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup+ViewElementCollection.TakeOwnership(Microsoft.VisualStudio.PlatformUI.Shell.ViewElement)
   at Microsoft.VisualStudio.PlatformUI.Shell.OwnershipCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AfterBaseInsertItem(Int32, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.OwnershipCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InsertItem(Int32, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewGroup+ViewElementCollection.InsertItem(Int32, Microsoft.VisualStudio.PlatformUI.Shell.ViewElement)
   at System.Collections.ObjectModel.Collection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CopyDocumentGroupContainer(Microsoft.VisualStudio.Platform.WindowManagement.WMDocumentGroupContainer, Microsoft.VisualStudio.Platform.WindowManagement.WMDocumentGroupContainer, System.Collections.Generic.List`1<Microsoft.VisualStudio.Platform.WindowManagement.DocumentView>)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CopyDocumentGroupStructure(Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile, Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile, System.Collections.Generic.List`1<Microsoft.VisualStudio.Platform.WindowManagement.DocumentView>)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.viewManager_WindowProfileChanging(System.Object, Microsoft.VisualStudio.PlatformUI.Shell.WindowProfileChangingEventArgs)
   at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.ExtensionMethods.RaiseEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.EventHandler`1<System.__Canon>, System.Object, System.__Canon)
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.set_WindowProfile(Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.set_ActiveProfile(Microsoft.VisualStudio.PlatformUI.Shell.WindowProfile)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService+<>c__DisplayClass198_0.<LoadFrameLayout>b__0()
   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func`1<Int32>, Boolean, Boolean)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.LoadFrameLayout(System.String, System.String, System.String, System.String)

I have a very similar project (all the same technology) that does open successfully, so I don't know what's going on with this one.

---
#### Feedback Bot on 10/18/2021, 03:10 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Alison jia [MSFT] on 10/19/2021, 03:54 AM: 

<p>Dear customer,</p>
<p>Thanks for your feedback! Right now, we don’t have enough information to investigate this issue.</p>
<p>For helping us to investigate this further, Could you please provide the following information:</p>
<ol>
<li>The project you created on Dev15 Or Dev16.10 Or Dev16.9, etc?</li>
<li>What actions did you do to your project?</li>
<li>The detailed steps Or your sample project so that we can reproduce your issue?</li>
</ol>
<p>Thanks</p>

#### John Henderson on 11/1/2021, 11:10 AM: 

<p>The solution that’s failing consists of 33 projects, so I can’t really provide you all of that (you can always send me all the Visual Studio source code!). I don’t get the issue on any other solutions, so I don’t see how I can create a sample project.</p>
<p>I haven’t changed anything in any of these projects from when it worked before. It also still works for other people, so it seems to be an issue with my Visual Studio installation or environment.</p>
<p>I can provide any logs required, or run debug versions of Visual Studio with more telemetry, if you have them.</p>

#### Feedback Bot on 11/2/2021, 07:22 AM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Alison jia [MSFT] on 11/3/2021, 02:02 AM: 

<p>Dear customer,</p>
<p>Thank you for your feedback! Unfortunately, we can’t reproduce your issue. If it’s reproduce with the specific project, could you please provide a sample solution that reproduces this problem so that we can conduct further research?</p>
<p>Thanks</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Possibly related to #981 or #46187.

/cc @saurabh500 @roji @lauxjpn

**Comment by lauxjpn** [comment]
What is the backend database that is accessed through OLE DB in this sceneario?

**Comment by JohnH-Work** [comment]
FYI. I no longer have this issue when using a fresh install of VS2022.
