### ISSUE TITLE
Test failure System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocationName(pkiOptions: IssuerRevocationViaOcsp | AllEndEntityRevocation | RootAuthorityHasDesignatedOcspResponder)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61238]
Run: [runtime-libraries-coreclr outerloop 20211104.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1453959&view=ms.vss-test-web.build-test-results-tab&runId=41830130&resultId=104315&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocationName(pkiOptions: IssuerRevocationViaOcsp | AllEndEntityRevocation | RootAuthorityHasDesignatedOcspResponder)

```
**Error message:**
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal consistency check failed.


Stack trace
   at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize) in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/CngKeyLite.cs:line 411
   at System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle() in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSACng.cs:line 44
   at System.Security.Cryptography.RSAImplementation.RSACng.ExportKeyBlob(Boolean includePrivateParameters) in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSACng.cs:line 66
   at System.Security.Cryptography.RSAImplementation.RSACng.ExportParameters(Boolean includePrivateParameters) in /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.ImportExport.cs:line 295
   at System.Security.Cryptography.RSA.ExportRSAPublicKey() in /_/src/libraries/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSA.cs:line 307
   at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.BuildPublicKey(RSA rsa) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/RSAPkcs1X509SignatureGenerator.cs:line 36
   at System.Security.Cryptography.X509Certificates.CertificateRequest..ctor(String subjectName, RSA key, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs:line 130
   at System.Security.Cryptography.X509Certificates.Tests.Common.CertificateAuthority.BuildPrivatePki(PkiOptions pkiOptions, RevocationResponder& responder, CertificateAuthority& rootAuthority, CertificateAuthority[]& intermediateAuthorities, X509Certificate2& endEntityCert, Int32 intermediateAuthorityCount, String testName, Boolean registerAuthorities, Boolean pkiOptionsInSubject, String subjectName, Int32 keySize, X509ExtensionCollection extensions) in /_/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs:line 852
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.BuildPrivatePki(PkiOptions pkiOptions, RevocationResponder& responder, CertificateAuthority& rootAuthority, CertificateAuthority& intermediateAuthority, X509Certificate2& endEntityCert, String testName, Boolean registerAuthorities, Boolean pkiOptionsInSubject) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1595
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.SimpleTest(PkiOptions pkiOptions, RunSimpleTest callback, String callerName, Boolean pkiOptionsInTestName) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1544
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocationName(PkiOptions pkiOptions) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 909
```

**Comment by vcsjones** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/25979
