### ISSUE TITLE
HttpConnection leaks UnobservedTaskExceptions

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#61256]
If the `SocketsHttpHandler` is not disposed, [`HttpConnection.Dispose`](https://github.com/dotnet/runtime/blob/852405c649c1f26124974c97199053d6d8f2adab/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L110) will not be called in time to [observe the exception from the `readAheadTask`](https://github.com/dotnet/runtime/blob/852405c649c1f26124974c97199053d6d8f2adab/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L135-L141). The `Dispose` will run as part of the finalizer, but since the `ExceptionHolder` in `_readAheadTask` is also finalizable, it may be too late as the execution order is not guaranteed.

Impact: Noise
The exceptions that leak to `UnobservedTaskExceptions` would be ignored anyway, so there is no adverse side effects aside from noise.

I am able to reproduce the same thing on 5.0 as well. The code is pretty much the same on 3.1, so I assume it would repro there as well (haven't tried since I am relying on the `ConnectCallback`).

**Comment by karelz** [comment]
Triage: Might be fixed by #60729

**Comment by davidfowl** [comment]
Why not backport this one? Feel like a reliability issue and it'll end up in people's logs (they're logging unobserved tasks).

**Comment by MihaZupan** [comment]
I think we should fix this in 8.0. Leaking internal exceptions like this is ugly.

**Comment by ramonsmits** [comment]
I observe a lot of these via `FirstChanceException` logging:

```txt
System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<CheckUsabilityOnScavenge>g__ReadAheadWithZeroByteReadAsync|44_0()
```

I discovered that these are related to pooling. I can significantly reduce these by setting the ` PooledConnection*` properties:

```c#
var handler = new SocketsHttpHandler
{
    PooledConnectionIdleTimeout = TimeSpan.FromHours(1),
    PooledConnectionLifetime = TimeSpan.FromHours(1),
};
```

Issue is that I cannot control all created HttpClients.
