### ISSUE TITLE
PublishSingleFile Fails to publish as a Single File when using WPF

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#61279]
### Description

When publishing a WPF app as a single file, multiple files are generated as shown here:
![image](https://user-images.githubusercontent.com/13609558/140612655-43a1c10e-702f-489c-8fc4-08f63ce71c64.png)

Moving the EXE into its own folder and running just the single EXE causes an app crash with the following error:
```
Application: WpfApp7.exe
CoreCLR Version: 6.0.21.48005
.NET Version: 6.0.0-rc.2.21480.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Dll was not found.
   at MS.Internal.WindowsBase.NativeMethodsSetLastError.SetWindowLongPtrWndProc(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
   at MS.Win32.UnsafeNativeMethods.CriticalSetWindowLong(HandleRef hWnd, Int32 nIndex, WndProc dwNewLong)
   at MS.Win32.HwndSubclass.HookWindowProc(IntPtr hwnd, WndProc newWndProc, IntPtr oldWndProc)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


Faulting application name: WpfApp7.exe, version: 1.0.0.0, time stamp: 0x6155d1f3
Faulting module name: KERNELBASE.dll, version: 10.0.22000.282, time stamp: 0x15492aba
Exception code: 0xe0434352
Fault offset: 0x000000000004466c
Faulting process id: 0x4f34
Faulting application start time: 0x01d7d317c9c3830a
Faulting application path: C:\temp\Example\JustApp\WpfApp7.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 9fb9a8b6-97be-4f3d-8b61-c37eee06b1ec
Faulting package full name: 
Faulting package-relative application ID: 
```

### Reproduction Steps

Create a brand new WPF app with these settings in your CSProj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>

    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
```

And put this in your PublishProfile.pubxml file:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>C:\Temp\Example\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishReadyToRun>False</PublishReadyToRun>
  </PropertyGroup>
</Project>
```

### Expected behavior

A single file executable is produced that runs.

### Actual behavior

Multiple files are generated and running just the single file results in an app crash.

### Regression?

I think so.

### Known Workarounds

None

### Configuration

.NET 6.0 x64 on Windows 11.

### Other information

Please fix.  I'm pretty sure this used to work.

**Comment by Symbai** [comment]
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#including-native-libraries

**Comment by agocke** [comment]
@Symbai is correct -- those are native libraries from WPF, so the app needs to be marked to embed-and-extract native libraries.
