### ISSUE TITLE
HTTPListener may not close the TCP port properly after Exception

### ISSUE THREAD

**Issue by derSchweiger** [dotnet/runtime#61303]
I'm not 100% sure if this bug is related to the .Net Core integration. Please forgive me, if I'm wrong.

I'm using the HTTPListener within a Windows Webservice (using LocalSystem account). Under some special circumstances (I haven't them figured out yet) the service will not start properly after the system has rebooted. The error is:
```
System.Net.HttpListenerException (5): Access is denied.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
```

I'm trying to start the HTTPListener with the following lines of code:
```
_httpListener.Prefixes.Add(String.Format(@"http://{0}:{1}/", _config.GetValue<string>("WebServerConfig:ServerIP"), _config.GetValue<int>("WebServerConfig:ServerPort")));
_httpListener.IgnoreWriteExceptions = true;
_httpListener.Start();
```

- IP: local IP-Adress of the server (e.g 10.0.0.1)
- Port: most of the time its port 8080

After this exception has occured, I'm not able to start the service with this port. I get the following exception everytime:
```
System.Net.HttpListenerException (32): The process cannot access the file because it is being used by another process.
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
```

So it seems that this port is already in use, but it isn't. At least "netstat -ano" doesn't show any results. I've also tried other programs like CurrPorts or TCPView but port 8080 doesn't seem to be open at all. It's no problem to start the service with any other port except this one. The only way to restart the service with port 8080 is to restart the whole system.

- Why does the initial "access denied" exception occur? Especially why does it only happen under some special circumstances?
- Why is the used port 8080 blocked for future attempts? The service will shutdown completely. Do I've to integrate a special error handling to avoid such a behaviour?

**Configuration**
- .NET Core 5
- Windows Server 2016 / Windows Server 2019
- 64bit

**Comment by karelz** [comment]
Triage: Might be bug, fairly corner case. Moving to Future.

**Comment by yukieiji** [comment]
I encountered a similar situation in a .NET 6 environment...

**Comment by notofug** [comment]
Me too, with .NET 8
- first got exception when trying to start listener with multiple prefixes
- next reduced to just one prefix ; then was stuck at "cannot access .. used by another .."
