### ISSUE TITLE
FileStream constructor throws UnauthorizedAccessException with no clear cause

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#61395]
### Description

In concurrent scenarios, very rarely I see `FileStream` throw `UnauthorizedAccessException`s that I can't explain. From the docs it seems like there are many potential causes of this error that make sense (e. g. attempting to open a read-only file with write access), but in my case I'm not sure why any of those reasons would apply.

### Reproduction Steps

```
var taskCount = 20;
using var barrier = new Barrier(taskCount);

var path = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());

var tasks = Enumerable.Range(0, taskCount)
	.Select(i => Task.Run(() =>
	{
		barrier.SignalAndWait();

		for (var i = 0; i < 1000; ++i)
		{
			try
			{
				var stream = new FileStream(path, FileMode.OpenOrCreate, FileAccess.Read, FileShare.None, bufferSize: 1, FileOptions.DeleteOnClose);
				stream.Dispose();
			}
			catch (IOException) { }
		}
	}))
	.ToArray();

try 
{
	Task.WaitAll(tasks); // fails with UnauthorizedAccessException (wrapped in AggregateException)
}
finally 
{
	File.Delete(path);
}
```

### Expected behavior

No error.

### Actual behavior

Fails with UnauthorizedAccessException wrapped in AggregateException.

Stack trace:
```
 at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
```

### Known Workarounds

Catch and retry on UnauthorizedAccessException?

### Configuration

.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

**Comment by adamsitnik** [comment]
Hi @madelson 

In the example that you have provided you are using `FileShare.None` which according to the [docs](https://docs.microsoft.com/dotnet/api/system.io.fileshare) stands for exclusive file access:

> Declines sharing of the current file. Any request to open the file (by this process or another process) will fail until the file is closed.

If you would like to open the same file for reading (`FileAccess.Read`) multiple times at the same time, you need specify  `FileShare.Read` (allow others for reading).

**Comment by madelson** [comment]
@adamsitnik I understand the FileShare semantics, but in most cases that results in `IOException` not `UnauthorizedAccessException`. For example:

```
var f = File.Open(Path.GetTempFileName(), FileMode.OpenOrCreate);
var f2 = File.Open(f.Name, FileMode.OpenOrCreate); // throws IOException "The process cannot access the file '...' because it is being used by another process."
```

**Comment by tmds** [comment]
@madelson the exception probably occurs due to using `FileOptions.DeleteOnClose`. See https://github.com/NuGet/NuGet.Client/commit/f91624e099fdc1bac8aaf69eba4bbf5b8f99dc5f.

**Comment by madelson** [comment]
@tmds in the code you linked it looks like they are catching `UnauthorizedAccessException` and retrying. However, the problem with that is that sometimes `UnauthorizedAccessException` means that you lack permission to create/open the file, in which case retrying won't fix it. I've worked around this for now by retrying a fixed number of times, but I think it would be preferable if .NET gave callers a way to differentiate between concurrency errors and permissions errors.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/926 Is a proposal for dinner grained IO errors

**Comment by madelson** [comment]
@danmoseley i like that proposal but as written I don’t think it quite covers this case because here it’s throwing UnauthorizedAccess instead of IOException. My request is that UnauthorizedAccess be thrown only for permissions errors with concurrency errors consistently throwing IOException.

**Comment by tmds** [comment]
>  I think it would be preferable if .NET gave callers a way to differentiate between concurrency errors and permissions errors.

Unfortunately, I think in this case, the error code that you get from the Win32 API is `ERROR_ACCESS_DENIED` for both the permission error, as the 'file is being deleted' case. So, I don't think .NET can make the distinction either.

> I've worked around this for now by retrying a fixed number of times

The latest version of the NuGet code also retries: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/ConcurrencyUtilities.cs.

From the way you're using the FileStream, it seems you are trying to protect against concurrent access from multiple threads/processes. Maybe adding a named Mutex can improve how it works.
