### ISSUE TITLE
System.IO.Pipelines.PipeReader.CopyToAsyncCore: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')

### ISSUE THREAD

**Issue by usaguerrilla** [dotnet/runtime#61525]
### Description

Getting this exception in ASP.NET Core Runtime 5.0.11
Occurs occasionaly (quite small %).
I checked and request seems to be not in cancelled state after it throws.

```
context?.HttpContext?.RequestAborted.IsCancellationRequested == false
```

Exception:

```
An unhandled exception was thrown by the application. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at MP.Sdk.Edge.Web.Formatters.InputFormatterBase.ToBytesAsync(Stream stream) in /opt/teamcity/work/af8a0ab010c87174/src/Sdk/MP.Sdk.Edge.Web/Formatters/InputFormatterBase.cs:line 65
```

```
using (MemoryStream memoryStream = new MemoryStream())
{
    using (stream)
    {
        // below throws
        await stream.CopyToAsync(memoryStream);
    }

    return memoryStream.ToArray();
}
```

### Reproduction Steps

Reproes in AWS with load balancer. No luck reproducing locally so far.

### Expected behavior

shouldn't throw exception

### Actual behavior

Exception:

```
An unhandled exception was thrown by the application. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at MP.Sdk.Edge.Web.Formatters.InputFormatterBase.ToBytesAsync(Stream stream) in /opt/teamcity/work/af8a0ab010c87174/src/Sdk/MP.Sdk.Edge.Web/Formatters/InputFormatterBase.cs:line 65
```

### Regression?

was okay in netcoreapp2.1

### Known Workarounds

none so far

**Comment by adityamandaleeka** [comment]
Triage: there's unfortunately not much we can do here without a repro.

**Comment by halter73** [comment]
> `context?.HttpContext?.RequestAborted.IsCancellationRequested`

Is this using `IHttpContextAccessor` on a background thread? I'm always nervous when I see a stack accessing the HttpContext without middleware directly invoking it.

**Comment by usaguerrilla** [comment]
This code is being called inside InputFormatter.

Working on a repro.

**Comment by usaguerrilla** [comment]
Any hints on where start ia used and why it might be failing?

**Comment by halter73** [comment]
Do you have any details about the request that induced this error like whether it was a chunked HTTP/1.1 request or had a Content-Length?

**Comment by usaguerrilla** [comment]
No chunked http afaik. Data can be huge ocassionally, we are seeing very small percentage of errors. Sadly we are in a code freeze for holidays so couldn't change prod much, no repro in qa or locally. But i am working on it. 

I am investigating. Sending messages and cancelling request at random time didn't lead to much. I checked out .net and trying to repro that way.

Problem is that due to properties / optimizations exception shows that copyToAsync throws exception but most likely it is readOnltSequence or readonlyMemory. As they have a bunch of places where they throw this exception.

**Comment by usaguerrilla** [comment]
additional info: we do not include content length.

**Comment by usaguerrilla** [comment]
Reproduced!!!

Some requests seem to have incorrect content-type. Reproes 100%.

that works:
```curl -X POST "http://%ip%:3611/events" -d %data% --header "Content-Type: application/json; charset=utf-8"```

that doesn't:
```curl -X POST "http://%ip%:3611/events" -d %data%```

```
2021/12/01 09:36:50.452||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Stats.Agents.DatadogStatsAgent|1|mpEventLevel=I|Repeated=|ecsLocation=@|Default Sampling Rate: 1
2021/12/01 09:36:50.482||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Program|1|mpEventLevel=I|Repeated=|ecsLocation=@|Invoking the ServerInitializer for Edge
2021/12/01 09:36:52.215||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Utils.EncryptedConfigHelper|1|mpEventLevel=I|Repeated=|ecsLocation=@|Executed KMS Decrypt using key 'arn:aws:kms:us-east-1:457804467337:key/c916cc31-c184-4fb8-9669-c0a2b003363d'
2021/12/01 09:36:56.967||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Program|1|mpEventLevel=I|Repeated=|ecsLocation=@|Starting
2021/12/01 09:36:56.967||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.HttpService|1|mpEventLevel=I|Repeated=|ecsLocation=@|Starting Kestrel Host for MP.Sdk.Edge.Web
2021/12/01 09:36:56.999||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Observability.Tracing.TraceManager|1|mpEventLevel=I|Repeated=|ecsLocation=@|Observability: CreatingTraceProvider
2021/12/01 09:36:57.019||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Observability.Tracing.CoreExtensions|1|mpEventLevel=I|Repeated=|ecsLocation=@|Zipkin Endpoint: http://otel-collector.qa.corp.mparticle.com:9411/api/v2/spans
2021/12/01 09:36:57.019||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Observability.Tracing.TraceManager|1|mpEventLevel=I|Repeated=|ecsLocation=@|Observability: AddTracing
2021/12/01 09:36:57.516||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Utils.HealthMonitorServer|1|mpEventLevel=I|Repeated=|ecsLocation=@|Health status pseudo-HTTP server now listening on port 8000
2021/12/01 09:36:57.516||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.HttpService|1|mpEventLevel=I|Repeated=|ecsLocation=@|Your application is running on http://10.173.0.108:3611
2021/12/01 09:36:57.516||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Utils.HealthMonitorServer|16|mpEventLevel=I|Repeated=|ecsLocation=@|Not enabling Consul health checks due to being disabled in config.
Service is running. Press CTRL+C to stop...
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::IHeaderDictionary::key='Content-Type',value='application/x-www-form-urlencoded'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::IHeaderDictionary::key='Accept',value='*/*'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::IHeaderDictionary::key='Host',value='10.173.0.108:3611'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::IHeaderDictionary::key='User-Agent',value='curl/7.55.1'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::IHeaderDictionary::key='Content-Length',value='397'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::ContentLength='397'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::Protocol='HTTP/1.1'
2021/12/01 09:37:22.864||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::RequestAborted='False'
2021/12/01 09:37:22.872||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::BodyReaderType='Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader'
2021/12/01 09:37:22.872||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|MP.Sdk.Edge.Web.Formatters.DebugInformationLogger|16|mpEventLevel=W|Repeated=|ecsLocation=@|pkrupets::DebugInformationLogger::BodyType='Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream'
2021/12/01 09:37:22.942||squad=Platformers|mp_environment_label=|AWSAccount=|pod=|Silo=|mpApp=|mpDGid=|Microsoft.AspNetCore.Server.Kestrel|16|mpEventLevel=E|Repeated=|ecsLocation=@|Connection id "0HMDKU4NSO314", Request id "0HMDKU4NSO314:00000002": An unhandled exception was thrown by the application. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.Buffers.ReadOnlySequence`1.TryGet(SequencePosition& position, ReadOnlyMemory`1& memory, Boolean advance)
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at MP.Sdk.Edge.Web.Formatters.InputFormatterBase.ToBytesAsync(Stream stream) in C:\dev\mPServer.sdkEdgeNet5\src\Sdk\MP.Sdk.Edge.Web\Formatters\InputFormatterBase.cs:line 60
   at MP.Sdk.Edge.Web.Formatters.SdkWebContextInputFormatter.ReadRequestBodyAsync(InputFormatterContext context) in C:\dev\mPServer.sdkEdgeNet5\src\Sdk\MP.Sdk.Edge.Web\Formatters\SdkWebContextInputFormatter.cs:line 45
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
