### ISSUE TITLE
Test failure System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.BadSignatureFormat

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61578]
Run: [runtime 20211114.14](https://dev.azure.com/dnceng/public/_build/results?buildId=1468856&view=ms.vss-test-web.build-test-results-tab&runId=42140828&resultId=176732&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.BadSignatureFormat
- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.EmptyHashAlgorithm
- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.NullInputs
- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.OffsetAndCountOutOfRange
- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.SignatureFormatsAreNotCompatible(signFormat: Rfc3279DerSequence, verifyFormat: IeeeP1363FixedFieldConcatenation)
- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.SignatureFormatsAreNotCompatible(signFormat: IeeeP1363FixedFieldConcatenation, verifyFormat: Rfc3279DerSequence)
- System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.*
```

**Error message:**
```
System.TypeInitializationException : The type initializer for 'System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests' threw an exception.
---- Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal error occurred.


Stack trace
   at System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests.GenerateTestKeys() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatTests.cs:line 119
   at System.Security.Cryptography.Algorithms.Tests.DsaFamilySignatureFormatTests..ctor() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DsaFamilySignatureFormatTests.cs:line 36
   at System.Security.Cryptography.Dsa.Tests.DSASignatureFormatTests..ctor()
   at System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 3747
----- Inner Stack Trace -----
   at Internal.NativeCrypto.CapiHelper.ImportKeyBlob(SafeProvHandle saveProvHandle, CspProviderFlags flags, Boolean addNoSaltFlag, Byte[] keyBlob, SafeKeyHandle& safeKeyHandle) in /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/CapiHelper.Windows.cs:line 997
   at System.Security.Cryptography.DSACryptoServiceProvider.ImportCspBlob(Byte[] keyBlob) in /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/DSACryptoServiceProvider.Windows.cs:line 351
   at System.Security.Cryptography.DSACryptoServiceProvider.ImportParameters(DSAParameters parameters) in /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/DSACryptoServiceProvider.Windows.cs:line 361
   at System.Security.Cryptography.Dsa.Tests.DSAFactory.Create(DSAParameters& dsaParameters) in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSAFactory.cs:line 29
   at System.Security.Cryptography.Dsa.Tests.DSASignatureFormatTests.OpenKey(DSAParameters& dsaParameters) in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatTests.cs:line 44
   at System.Security.Cryptography.Dsa.Tests.DSASignatureFormatTests.LocalGenerateTestKeys()+MoveNext() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatTests.cs:line 67
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items) in /_/src/libraries/Common/src/System/Collections/Generic/LargeArrayBuilder.SpeedOpt.cs:line 116
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source) in /_/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.Linq.cs:line 84
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) in /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs:line 17
   at System.Security.Cryptography.Dsa.Tests.DsaArrayOffsetSignatureFormatTests..cctor() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignatureFormatTests.cs:line 117
```

**Comment by bartonjs** [comment]
CNG internal error.  Duplicate of #29683.
