### ISSUE TITLE
System.Text.Json SignalR Hub issue

### ISSUE THREAD

**Issue by brandonseydel** [dotnet/runtime#61648]
### Description

When using the new System.Text.Json 6.0.0 in a 3.1 core project there is an error when trying to use a SignalR Hub.

### Reproduction Steps

Set up a .net core 3.1 asp.net app and try to use a signalr hub.

### Expected behavior

Works

### Actual behavior

Throws unhandled exception

```
Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.WaitHandle.Handle.
```

```
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteArguments(Object[] arguments, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteInvocationMessage(InvocationMessage message, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.Azure.SignalR.DefaultHubMessageSerializer.SerializeMessage(HubMessage message)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.SerializeAllProtocols(String method, Object[] args)
   at Microsoft.Azure.SignalR.ServiceLifetimeManagerBase`1.SendAllAsync(String methodName, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Internal.AllClientProxy`1.SendCoreAsync(String method, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.TypedClientBuilder.ISignalRClientImpl.SendApprovalQueueModifiedAsync(CancellationToken )
   at XXX.ClientMdm.Logic.SignalR.SignalRLogic.SendApprovalQueueModifiedAsync(CancellationToken cancellationToken) in C:\Users\e060589\source\repos\XXX.ClientMDM\Server\XXX.ClientMdm.Logic\SignalR\SignalRLogic.cs:line 29
```

**Comment by BrennanConroy** [comment]
What does your `SendApprovalQueueModifiedAsync` method look like?

**Comment by eiriktsarpalis** [comment]
@BrennanConroy should this be transfered to the aspnetcore repo perhaps?

**Comment by brandonseydel** [comment]
```
		public Task SendApprovalQueueModifiedAsync(CancellationToken cancellationToken = default)
		{
			return _hubContext.Clients.All.SendApprovalQueueModifiedAsync(cancellationToken);
		}
```

**Comment by brandonseydel** [comment]
CancellationToken being sent is indeed odd, but this worked prior without error.

**Comment by BrennanConroy** [comment]
> should this be transfered to the aspnetcore repo perhaps?

No, SignalR is just passing the users object through to Json in this case.

> CancellationToken being sent is indeed odd, but this worked prior without error.

CancellationToken is very likely an unsupported type (and probably always will be), it might have worked before but shouldn't have. This likely changed with https://github.com/dotnet/runtime/pull/47899 which now throws when `IntPtr` is encountered.

**Comment by brandonseydel** [comment]
@BrennanConroy - I accept that.  It would be nice if it was listed as a breaking change somewhere.  This was old code I was trying to bring up to latest libs and found this guy luckily before prod release.
