### ISSUE TITLE
Test failure System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Loop_Throws(engine: Compiled)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61710]
Run: [runtime-libraries-coreclr outerloop 20211116.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1471742&view=ms.vss-test-web.build-test-results-tab&runId=42206400&resultId=104237&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Loop_Throws(engine: Compiled)

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.Text.RegularExpressions.RegexMatchTimeoutException)
Actual:   (No exception was thrown)


Stack trace
   at System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Loop_Throws(RegexEngine engine) in /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs:line 796
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20220227.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1634822&view=ms.vss-test-web.build-test-results-tab&runId=45281216&paneView=debug&resultId=104519)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Loop_Throws(engine: Compiled)

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.Text.RegularExpressions.RegexMatchTimeoutException)
Actual:   (No exception was thrown)


Stack trace
   at System.Text.RegularExpressions.Tests.RegexMatchTests.Match_Timeout_Loop_Throws(RegexEngine engine) in /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs:line 1060
--- End of stack trace from previous location ---
```

**Comment by stephentoub** [comment]
This test no longer exists.
