### ISSUE TITLE
[wasm] Some AOT crashes on Windows, in Wasm.Build.Tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#61725]
https://github.com/dotnet/runtime/pull/59479 enables WBT on windows. And some of the AOT tests crash:

1. `Wasm.Build.NativeRebuild.Tests.ReferenceNewAssemblyRebuildTest.ReferenceNewAssembly`+AOT:
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1473500&view=logs&j=439c6dc4-74cd-57d7-0b7a-a049ccfd9d90&t=4104ed37-d8c2-5ff0-cfcf-7ffa1988d34d)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-b43a84b5a5d9450aba/Workloads-.ReferenceNewAssemblyRebuildTest/1/console.bca0dd3f.log?sv=2019-07-07&)

```
        [wasm test] [08:06:40] fail: RuntimeError: null function or function signature mismatch
        [wasm test] [08:06:40] fail: RuntimeError: null function or function signature mismatch
        [wasm test] [08:06:40] fail:     at corlib_System_GC_AllocateUninitializedArray_T_BYTE_int_bool (<anonymous>:wasm-function[8898]:0x172ab6)
        [wasm test] [08:06:40] fail:     at corlib_System_Buffers_TlsOverPerCoreLockedStacksArrayPool_1_T_BYTE_Rent_int (<anonymous>:wasm-function[10296]:0x1b9b42)
        [wasm test] [08:06:40] fail:     at System_Text_Json_System_Text_Json_JsonDocument_MetadataDb_CreateRented_int_bool (<anonymous>:wasm-function[16505]:0x2aacdd)
        [wasm test] [08:06:40] fail:     at System_Text_Json_aot_wrapper_gsharedvt_out_sig_cl2f_Mono_dValueTuple_603_3cint_2c_20int_2c_20int_3e__i4u1 (<anonymous>:wasm-function[17335]:0x2dcc03)
        [wasm test] [08:06:40] fail:     at jit_call_cb (<anonymous>:wasm-function[17816]:0x2f8f91)
        [wasm test] [08:06:40] fail:     at invoke_vi (./dotnet.js:6436:25)
        [wasm test] [08:06:40] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[23889]:0x3b890b)
        [wasm test] [08:06:40] fail:     at do_jit_call (<anonymous>:wasm-function[17773]:0x2f803c)
        [wasm test] [08:06:40] fail:     at interp_exec_method (<anonymous>:wasm-function[17707]:0x2eaf76)
        [wasm test] [08:06:40] fail:     at interp_entry (<anonymous>:wasm-function[17754]:0x2f74c8)
```

2. `Wasm.Build.Tests.WasmBuildAppTest.AsyncMain(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, host: V8) `
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-b43a84b5a5d9450aba/Workloads-.WasmBuildAppTest/1/console.f842265f.log?sv=2019-07-07&se=2021-12-07T07%3A24%3A10Z&sr=c&sp=rl&sig=cVrHsxYKO53nKHQ39dTKWrcZ%2BATw9KDSv5eV%2FyVp6dE%3D)

```
        [wasm test-browser] [08:30:37] fail: RuntimeError: memory access out of bounds
        [wasm test-browser] [08:30:37] fail: RuntimeError: memory access out of bounds
        [wasm test-browser]     at m_class_get_class_kind.11 (http://127.0.0.1:49226/dotnet.wasm:wasm-function[19088]:0x319c18)
        [wasm test-browser]     at m_class_get_mem_manager.5 (http://127.0.0.1:49226/dotnet.wasm:wasm-function[19072]:0x319049)
        [wasm test-browser]     at mono_runtime_class_init_full (http://127.0.0.1:49226/dotnet.wasm:wasm-function[19071]:0x318c65)
        [wasm test-browser]     at mono_generic_class_init (http://127.0.0.1:49226/dotnet.wasm:wasm-function[30259]:0x457db3)
        [wasm test-browser]     at aot_wrapper_icall_mono_generic_class_init (http://127.0.0.1:49226/dotnet.wasm:wasm-function[752]:0x26d9f)
        [wasm test-browser]     at corlib_System_Threading_Tasks_TaskCache_CreateCacheableTask_TResult_BOOL_TResult_BOOL (http://127.0.0.1:49226/dotnet.wasm:wasm-function[7064]:0x134293)
        [wasm test-browser]     at corlib_System_Threading_Tasks_TaskCache__cctor (http://127.0.0.1:49226/dotnet.wasm:wasm-function[7063]:0x1341e4)
        [wasm test-browser]     at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_void_ (http://127.0.0.1:49226/dotnet.wasm:wasm-function[12349]:0x22e17a)
        [wasm test-browser]     at jit_call_cb (http://127.0.0.1:49226/dotnet.wasm:wasm-function[16562]:0x2bb545)
        [wasm test-browser]     at invoke_vi (http://127.0.0.1:49226/dotnet.js:6514:25)
        [wasm test-browser] [08:30:37] info: Flushed stdout!
        [wasm test-browser] [08:30:37] info: 1 Exit called with 1 when isXUnitDoneCheck=false  at set_exit_code (/main.js:240:24) at Object.init (/main.js:206:17).
        [wasm test-browser] [08:30:37] info: WASM EXIT 1
        [wasm test-browser] [08:30:37] dbug: Reached wasm exit
        [wasm test-browser] [08:30:37] info: 2 Exit called with 1 when isXUnitDoneCheck=false  at set_exit_code (/main.js:240:24) at Object.init (/main.js:206:17).
```

3. `Wasm.Build.Tests.WasmBuildAppTest.TopLevelMain`
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-b43a84b5a5d9450aba/Workloads-.WasmBuildAppTest/1/console.f842265f.log?sv=2019-07-07&se=2021-12-07T07%3A24%3A10Z&sr=c&sp=rl&sig=cVrHsxYKO53nKHQ39dTKWrcZ%2BATw9KDSv5eV%2FyVp6dE%3D)

```
[wasm test] [08:34:07] info: Hello, World!
[wasm test] [08:34:07] fail: 
[wasm test] [08:34:07] fail: ==== JS stack trace =========================================
[wasm test] [08:34:07] fail: 
[wasm test] [08:34:07] fail: Security context: 0x03f3081d0a8d <JSObject>#0#
[wasm test] [08:34:07] fail:     0: builtin exit frame: trace(this=0x03f3081c5d29 <console map = 000003F308202911>#1#,0x03f3081c5d29 <console map = 000003F308202911>#1#,0x03f308617555 <String[97]: c"* Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/metadata/class-accessors.c:86\n">)
[wasm test] [08:34:07] fail: 
[wasm test] [08:34:07] fail:     1: 1336856 [000003F3083194A1] [./dotnet.js:1427] [bytecode=000003F3082E59AD offset=113](this=0x03f3081c33f9 <JSGlobal Object>#2#,724257,31140104,4,0,0)
[wasm test] [08:34:07] fail:     2: _emscripten_asm_const_int [000003F3081F5425] [./dotnet.js:4566] [bytecode=000003F3082E5731 offset=27](this=0x03f3081c33f9 <JSGlobal Object>#2#,1336856,6694744,6694720)
[wasm test] [08:34:07] fail:     3: WasmToJsFrame [pc: 0000008DB89BD694]
[wasm test] [08:34:07] fail:     4: WASM [wasm://wasm/03c0dd8e], function #32041 ('wasm_trace_logger'), pc=0000008DB7BD66F0 (+0xb0), pos=4799489 (+78)
[wasm test] [08:34:07] fail:     5: WASM [wasm://wasm/03c0dd8e], function #20400 ('eglib_log_adapter'), pc=0000008DB8010988 (+0xc8), pos=3383520 (+39)
[wasm test] [08:34:07] fail:     6: WASM [wasm://wasm/03c0dd8e], function #31298 ('monoeg_g_logstr'), pc=0000008DB7C1FB1C (+0xbc), pos=4693725 (+52)
[wasm test] [08:34:07] fail:     7: WASM [wasm://wasm/03c0dd8e], function #31296 ('monoeg_g_logv_nofree'), pc=0000008DB7C1FC85 (+0xc5), pos=4693639 (+64)
[wasm test] [08:34:07] fail:     8: WASM [wasm://wasm/03c0dd8e], function #31301 ('monoeg_assertion_message'), pc=0000008DB7C1F896 (+0x56), pos=4693851 (+32)
[wasm test] [08:34:07] fail:     9: WASM [wasm://wasm/03c0dd8e], function #31304 ('mono_assertion_message_unreachable'), pc=0000008DB7C1F6F5 (+0x55), pos=4693959 (+32)
[wasm test] [08:34:07] fail:    10: WASM [wasm://wasm/03c0dd8e], function #17511 ('mono_class_get_flags'), pc=0000008DB8103FFD (+0x19d), pos=3068824 (+147)
[wasm test] [08:34:07] fail:    11: WASM [wasm://wasm/03c0dd8e], function #17416 ('mono_class_setup_fields'), pc=0000008DB81142A4 (+0x64), pos=3043553 (+49)
[wasm test] [08:34:07] fail:    12: WASM [wasm://wasm/03c0dd8e], function #17423 ('init_sizes_with_info'), pc=0000008DB81105F3 (+0x173), pos=3050472 (+212)
[wasm test] [08:34:07] fail:    13: WASM [wasm://wasm/03c0dd8e], function #17417 ('mono_class_init_internal'), pc=0000008DB811358F (+0x40f), pos=3044894 (+413)
[wasm test] [08:34:07] fail:    14: WASM [wasm://wasm/03c0dd8e], function #17417 ('mono_class_init_internal'), pc=0000008DB811354B (+0x3cb), pos=3044865 (+384)
[wasm test] [08:34:07] fail:    15: WASM [wasm://wasm/03c0dd8e], function #17344 ('mono_class_get_cctor'), pc=0000008DB811B163 (+0xc3), pos=3035583 (+81)
[wasm test] [08:34:07] fail:    16: WASM [wasm://wasm/03c0dd8e], function #19072 ('mono_runtime_class_init_full'), pc=0000008DB80783A5 (+0xc5), pos=3247250 (+87)
[wasm test] [08:34:07] fail:    17: WASM [wasm://wasm/03c0dd8e], function #30260 ('mono_generic_class_init'), pc=0000008DB7C8976F (+0x4f), pos=4554183 (+26)
[wasm test] [08:34:07] fail:    18: WASM [wasm://wasm/03c0dd8e], function #647 ('aot_wrapper_icall_mono_generic_class_init'), pc=0000008DB896AE00 (+0x40), pos=147199 (+14)
[wasm test] [08:34:07] fail:    19: WASM [wasm://wasm/03c0dd8e], function #6959 ('corlib_System_Threading_Tasks_TaskCache_CreateCacheableTask_TRes'), pc=0000008DB8652DEB (+0x12b), pos=1250291 (+119)
[wasm test] [08:34:07] fail:    20: WASM [wasm://wasm/03c0dd8e], function #6958 ('corlib_System_Threading_Tasks_TaskCache__cctor'), pc=0000008DB8653110 (+0xd0), pos=1250116 (+88)
[wasm test] [08:34:07] fail:    21: WASM [wasm://wasm/03c0dd8e], function #12244 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_void_'), pc=0000008DB8363C04 (+0x84), pos=2274010 (+11)
[wasm test] [08:34:07] fail:    22: WASM [wasm://wasm/03c0dd8e], function #16563 ('jit_call_cb'), pc=0000008DB817DED2 (+0x612), pos=2864473 (+335)
[wasm test] [08:34:07] fail:    23: JsToWasmFrame [pc: 000003F3000B4A95]
[wasm test] [08:34:07] fail:    24: invoke_vi [000003F3081F6E79] [./dotnet.js:6514] [bytecode=000003F3082DD9E1 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#2#,16277,6695264)
[wasm test] [08:34:07] fail:    25: WasmToJsFrame [pc: 0000008DB89BDF5D]
[wasm test] [08:34:07] fail:    26: WASM [wasm://wasm/03c0dd8e], function #31188 ('mono_llvm_cpp_catch_exception'), pc=0000008DB7C2B0F2 (+0x52), pos=4671000 (+26)
[wasm test] [08:34:07] fail:    27: WASM [wasm://wasm/03c0dd8e], function #16520 ('do_jit_call'), pc=0000008DB81819FA (+0x31a), pos=2860331 (+353)
[wasm test] [08:34:07] fail:    28: WASM [wasm://wasm/03c0dd8e], function #16454 ('interp_exec_method'), pc=0000008DB7B2CD48 (+0x43a8), pos=2806883 (+5248)
[wasm test] [08:34:07] fail:    29: WASM [wasm://wasm/03c0dd8e], function #16453 ('interp_runtime_invoke'), pc=0000008DB81883AD (+0x1ed), pos=2801570 (+247)
[wasm test] [08:34:07] fail:    30: WASM [wasm://wasm/03c0dd8e], function #30120 ('mono_jit_runtime_invoke'), pc=0000008DB7C967D3 (+0x633), pos=4536394 (+625)
[wasm test] [08:34:07] fail:    31: WASM [wasm://wasm/03c0dd8e], function #19068 ('do_runtime_invoke'), pc=0000008DB807900E (+0xee), pos=3246932 (+53)
[wasm test] [08:34:07] fail:    32: WASM [wasm://wasm/03c0dd8e], function #19079 ('mono_runtime_try_invoke'), pc=0000008DB8077B89 (+0x89), pos=3248752 (+37)
[wasm test] [08:34:07] fail:    33: WASM [wasm://wasm/03c0dd8e], function #19072 ('mono_runtime_class_init_full'), pc=0000008DB80786B2 (+0x3d2), pos=3247615 (+452)
[wasm test] [08:34:07] fail:    34: WASM [wasm://wasm/03c0dd8e], function #30081 ('mono_resolve_patch_target_ext'), pc=0000008DB7C9AD8C (+0xbec), pos=4530099 (+748)
[wasm test] [08:34:07] fail:    35: WASM [wasm://wasm/03c0dd8e], function #30087 ('mono_resolve_patch_target'), pc=0000008DB7C99EBB (+0x5b), pos=4530981 (+15)
[wasm test] [08:34:07] fail:    36: WASM [wasm://wasm/03c0dd8e], function #30416 ('init_method'), pc=0000008DB7C7031D (+0x59d), pos=4590426 (+583)
[wasm test] [08:34:07] fail:    37: WASM [wasm://wasm/03c0dd8e], function #30415 ('mono_aot_init_llvm_method'), pc=0000008DB7C7087B (+0x3b), pos=4589836 (+13)
[wasm test] [08:34:07] fail:    38: WASM [wasm://wasm/03c0dd8e], function #30927 ('mini_llvm_init_method'), pc=0000008DB7C3C02B (+0x8b), pos=4658111 (+49)
[wasm test] [08:34:07] fail:    39: WASM [wasm://wasm/03c0dd8e], function #16318 ('mono_aot_top_level_init_method_gshared_vtable'), pc=0000008DB8194FD3 (+0xb3), pos=2786950 (+47)
[wasm test] [08:34:07] fail:    40: WASM [wasm://wasm/03c0dd8e], function #16334 ('top_level_System_Runtime_CompilerServices_AsyncTaskMethodBuilder'), pc=0000008DB8192E6E (+0x6e), pos=2788850 (+35)
[wasm test] [08:34:07] fail:    41: WASM [wasm://wasm/03c0dd8e], function #12531 ('corlib_aot_wrapper_gsharedvt_out_sig_void_this_i4'), pc=0000008DB834F433 (+0x93), pos=2294082 (+18)
[wasm test] [08:34:07] fail:    42: WASM [wasm://wasm/03c0dd8e], function #16563 ('jit_call_cb'), pc=0000008DB817DA88 (+0x1c8), pos=2864232 (+94)
[wasm test] [08:34:07] fail:    43: JsToWasmFrame [pc: 000003F3000B4A95]
[wasm test] [08:34:07] fail:    44: invoke_vi [000003F3081F6E79] [./dotnet.js:6514] [bytecode=000003F3082DD9E1 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#2#,16277,6695856)
[wasm test] [08:34:07] fail:    45: WasmToJsFrame [pc: 0000008DB89BDF5D]
[wasm test] [08:34:07] fail:    46: WASM [wasm://wasm/03c0dd8e], function #31188 ('mono_llvm_cpp_catch_exception'), pc=0000008DB7C2B0F2 (+0x52), pos=4671000 (+26)
[wasm test] [08:34:07] fail:    47: WASM [wasm://wasm/03c0dd8e], function #16520 ('do_jit_call'), pc=0000008DB81819FA (+0x31a), pos=2860331 (+353)
[wasm test] [08:34:07] fail:    48: WASM [wasm://wasm/03c0dd8e], function #16454 ('interp_exec_method'), pc=0000008DB7B2CD48 (+0x43a8), pos=2806883 (+5248)
[wasm test] [08:34:07] fail:    49: WASM [wasm://wasm/03c0dd8e], function #16501 ('interp_entry'), pc=0000008DB8183CE6 (+0x3a6), pos=2857398 (+468)
[wasm test] [08:34:07] fail:    50: WASM [wasm://wasm/03c0dd8e], function #16596 ('interp_entry_static_1'), pc=0000008DB817B67D (+0x5d), pos=2866974 (+43)
[wasm test] [08:34:07] fail:    51: WASM [wasm://wasm/03c0dd8e], function #13701 ('corlib_aot_wrapper_gsharedvt_in_sig_void_bii'), pc=0000008DB82E4F20 (+0x80), pos=2385503 (+13)
[wasm test] [08:34:07] fail:    52: WASM [wasm://wasm/03c0dd8e], function #16365 ('top_level_System_Runtime_CompilerServices_AsyncMethodBuilderCore'), pc=0000008DB818E38F (+0xef), pos=2795549 (+56)
[wasm test] [08:34:07] fail:    53: WASM [wasm://wasm/03c0dd8e], function #16319 ('top_level_Program__Main__string__'), pc=0000008DB8194DAC (+0x10c), pos=2787051 (+87)
[wasm test] [08:34:07] fail:    54: WASM [wasm://wasm/03c0dd8e], function #12197 ('corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_obj'), pc=0000008DB8367144 (+0xa4), pos=2271826 (+38)
[wasm test] [08:34:07] fail:    55: WASM [wasm://wasm/03c0dd8e], function #16563 ('jit_call_cb'), pc=0000008DB817DA88 (+0x1c8), pos=2864232 (+94)
[wasm test] [08:34:07] fail:    56: JsToWasmFrame [pc: 000003F3000B4A95]
[wasm test] [08:34:07] fail:    57: invoke_vi [000003F3081F6E79] [./dotnet.js:6514] [bytecode=000003F3082DD9E1 offset=26](this=0x03f3081c33f9 <JSGlobal Object>#2#,16277,6696496)
[wasm test] [08:34:07] fail:    58: WasmToJsFrame [pc: 0000008DB89BDF5D]
[wasm test] [08:34:07] fail:    59: WASM [wasm://wasm/03c0dd8e], function #31188 ('mono_llvm_cpp_catch_exception'), pc=0000008DB7C2B0F2 (+0x52), pos=4671000 (+26)
[wasm test] [08:34:07] fail:    60: WASM [wasm://wasm/03c0dd8e], function #16520 ('do_jit_call'), pc=0000008DB81819FA (+0x31a), pos=2860331 (+353)
[wasm test] [08:34:07] fail:    61: WASM [wasm://wasm/03c0dd8e], function #16454 ('interp_exec_method'), pc=0000008DB7B2CD48 (+0x43a8), pos=2806883 (+5248)
[wasm test] [08:34:07] fail:    62: WASM [wasm://wasm/03c0dd8e], function #16453 ('interp_runtime_invoke'), pc=0000008DB81883AD (+0x1ed), pos=2801570 (+247)
[wasm test] [08:34:07] fail:    63: WASM [wasm://wasm/03c0dd8e], function #30120 ('mono_jit_runtime_invoke'), pc=0000008DB7C967D3 (+0x633), pos=4536394 (+625)
[wasm test] [08:34:07] fail:    64: WASM [wasm://wasm/03c0dd8e], function #19068 ('do_runtime_invoke'), pc=0000008DB807900E (+0xee), pos=3246932 (+53)
[wasm test] [08:34:07] fail:    65: WASM [wasm://wasm/03c0dd8e], function #19079 ('mono_runtime_try_invoke'), pc=0000008DB8077B89 (+0x89), pos=3248752 (+37)
[wasm test] [08:34:07] fail:    66: WASM [wasm://wasm/03c0dd8e], function #19154 ('mono_runtime_invoke'), pc=0000008DB8070AAC (+0xac), pos=3257321 (+65)
[wasm test] [08:34:07] fail:    67: WASM [wasm://wasm/03c0dd8e], function #32033 ('mono_wasm_invoke_method'), pc=0000008DB7BD7254 (+0x74), pos=4798345 (+42)
[wasm test] [08:34:07] fail:    68: JsToWasmFrame [pc: 000003F3000B4A95]
[wasm test] [08:34:07] fail:    69: /* anonymous */ [000003F3082C9D2D] [./dotnet.js:5786] [bytecode=000003F3082ED685 offset=39](this=0x03f3081c33f9 <JSGlobal Object>#2#)
[wasm test] [08:34:07] fail:    70: /* anonymous */ [000003F3082C2D65] [./dotnet.js:3] [bytecode=000003F3082D7551 offset=100](this=0x03f308311005 <Object map = 000003F308205729>#3#)
[wasm test] [08:34:07] fail:    71: _call_method_with_converted_args(aka _call_method_with_converted_args) [000003F30831209D] [./dotnet.js:3] [bytecode=000003F3082ED3F5 offset=43](this=0x03f3080023b5 <undefined>,29512832,0,0x03f3084bc02d <Object map = 000003F308213829>#4#,0x03f308002235 <null>,29527272,0x03f30800248d <true>,0x03f3080023b5 <undefined>)
[wasm test] [08:34:07] fail:    72: call_method(aka call_method) [000003F30831201D] [./dotnet.js:3] [bytecode=000003F3082EAFC1 offset=185](this=0x03f3080023b5 <undefined>,29512832,0,0x03f3081d2dd9 <String[1]: #m>,0x03f3084bb315 <JSArray[1]>#5#)
[wasm test] [08:34:07] fail:    73: /* anonymous */(aka /* anonymous */) [000003F3084BB2E9] [./dotnet.js:3] [bytecode=000003F3082EA091 offset=84](this=0x03f3080023b5 <undefined>)
[wasm test] [08:34:07] fail:    74: call_assembly_entry_point(aka mono_call_assembly_entry_point) [000003F30831211D] [./dotnet.js:3] [bytecode=000003F3082E9D41 offset=14](this=0x03f308305e7d <Object map = 000003F30820D451>#6#,0x03f3083193ad <String[13]: "top_level.dll">,0x03f3084b8751 <JSArray[1]>#7#,0x03f3081d2dd9 <String[1]: #m>)
[wasm test] [08:34:07] fail:    75: init [000003F3083190CD] [main.js:203] [bytecode=000003F3082E9315 offset=580](this=0x03f308305905 <Object map = 000003F308207731>#8#)
[wasm test] [08:34:07] fail:    76: onDotNetReady [000003F308319459] [main.js:143] [bytecode=000003F3082E8D09 offset=128](this=0x03f30830593d <Object map = 000003F30820D771>#9#)
[wasm test] [08:34:07] fail:    77: _finalize_startup(aka _finalize_startup) [000003F30831253D] [./dotnet.js:3] [bytecode=000003F3082E31D5 offset=547](this=0x03f3080023b5 <undefined>,0x03f308310fad <Object map = 000003F30820DC99>#10#,0x03f3082d979d <Object map = 000003F308210011>#11#)
[wasm test] [08:34:07] fail:    78: mono_load_runtime_and_bcl_args(aka mono_load_runtime_and_bcl_args) [000003F30831257D] [./dotnet.js:3] [bytecode=000003F3082D7071 offset=428](this=0x03f3080023b5 <undefined>,0x03f308310fad <Object map = 000003F30820DC99>#10#)
[wasm test] [08:34:07] fail:    79: /* anonymous */ [000003F3086C90B1](this=0x03f3081c33f9 <JSGlobal Object>#2#,0x03f30848f9cd <JSArray[10]>#12#)
[wasm test] [08:34:07] fail:    80: StubFrame [pc: 000003F300106018]
[wasm test] [08:34:07] fail:    81: StubFrame [pc: 000003F30006E950]
[wasm test] [08:34:07] fail:    82: EntryFrame [pc: 000003F30004993B]
[wasm test] [08:34:07] fail: =====================
[wasm test] [08:34:07] fail: 
[wasm test] [08:34:07] fail: * Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/metadata/class-accessors.c:86
[wasm test] [08:34:07] fail: 
```

**Comment by radical** [comment]
cc @vargaz @radekdoulik

**Comment by radical** [comment]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1478549&view=logs&jobId=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&j=439c6dc4-74cd-57d7-0b7a-a049ccfd9d90&t=4104ed37-d8c2-5ff0-cfcf-7ffa1988d34d), [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-77a06258b28b431989/EMSDK-.MainWithArgsTests/1/console.7cd126ef.log?sv=2019-07-07&se=2021-12-09T23%3A19%3A41Z&sr=c&sp=rl&sig=aipJOIgIfQpag%2FV8FMpTran1f6ALMcm8qnqgnm3z5cw%3D)
```
fail: RuntimeError: divide by zero
fail:     at mono_aot_get_offset (<anonymous>:wasm-function[26829]:0x3865b9)
fail:     at mono_aot_get_cached_class_info (<anonymous>:wasm-function[26836]:0x387855)
fail:     at mono_class_get_cached_class_info (<anonymous>:wasm-function[11586]:0x1e3eb4)
fail:     at mono_class_init_internal (<anonymous>:wasm-function[11657]:0x1e5fa5)
fail:     at mono_class_get_cctor (<anonymous>:wasm-function[11583]:0x1e3cca)
fail:     at mono_runtime_class_init_full (<anonymous>:wasm-function[15362]:0x240f08)
fail:     at mono_generic_class_init (<anonymous>:wasm-function[26716]:0x38127a)
fail:     at aot_wrapper_icall_mono_generic_class_init (<anonymous>:wasm-function[526]:0x1c2bd)
fail:     at corlib_System_Threading_Tasks_TaskCache_CreateCacheableTask_TResult_BOOL_TResult_BOOL (<anonymous>:wasm-function[4844]:0xd4916)
fail:     at corlib_System_Threading_Tasks_TaskCache__cctor (<anonymous>:wasm-function[4843]:0xd4867)
```

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1478549&view=logs&jobId=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&j=439c6dc4-74cd-57d7-0b7a-a049ccfd9d90&t=4104ed37-d8c2-5ff0-cfcf-7ffa1988d34d), [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-9a24d1934ea743a9b1/Workloads-.WasmBuildAppTest/1/console.6654d122.log?sv=2019-07-07&se=2021-12-09T23%3A19%3A26Z&sr=c&sp=rl&sig=dd1lyAUnpRbzaQF5NyJbLVTaU2y5WQbqgoTJpXVcfls%3D)
```
fail: Error: System.TypeInitializationException: The type initializer for 'System.Threading.Tasks.TaskCache' threw an exception.
fail:  ---> System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
fail:    --- End of inner exception stack trace ---
fail:    at TestClass.Main()
fail:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<Main>d__0](<Main>d__0& )
fail: Error: System.TypeInitializationException: The type initializer for 'System.Threading.Tasks.TaskCache' threw an exception.
fail:  ---> System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
fail:    --- End of inner exception stack trace ---
fail:    at TestClass.Main()
fail:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<Main>d__0](<Main>d__0& )
fail:     at _convert_exception_for_method_call (./dotnet.js:3:47429)
fail:     at _handle_exception_for_call (./dotnet.js:3:48069)
fail:     at _handle_exception_and_produce_result_for_call (./dotnet.js:3:48238)
fail:     at _call_method_with_converted_args (./dotnet.js:3:48890)
fail:     at call_method (./dotnet.js:3:47961)
fail:     at ./dotnet.js:3:49803
fail:     at Object.mono_call_assembly_entry_point [as call_assembly_entry_point] (./dotnet.js:3:49980)
fail:     at Object.init (main.js:203:46)
fail:     at Object.onDotNetReady (main.js:143:13)
fail:     at _finalize_startup (./dotnet.js:3:62462)
```

**Comment by radical** [comment]
Multiple tests have `fail: * Assertion: should not be reached at D:/a/_work/1/s/src/mono/mono/metadata/class-accessors.c:86`
