### ISSUE TITLE
[wasm][aot] Almost all library tests failing on Windows with `RuntimeError: null function or function signature mismatch`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#61721]
[PR](https://github.com/dotnet/runtime/pull/59479) failing on windows:

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1470955&view=logs&jobId=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&j=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&t=57689805-9064-5d56-984a-6ae89a8efb73)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-6a38bcf8178e4e048c/System.Runtime.Tests/1/console.06ad8d51.log?sv=2019-07-07&se=2021-12-06T01%3A38%3A57Z&sr=c&sp=rl&sig=qot8aTvXCwUKHtSUP0gphYX3TbOnbmUPhUlf3As1CfI%3D)

```
[02:22:37] fail: RuntimeError: null function or function signature mismatch
[02:22:38] fail: RuntimeError: null function or function signature mismatch
[02:22:38] fail:     at corlib_System_GC_AllocateUninitializedArray_T_CHAR_int_bool (<anonymous>:wasm-function[37049]:0x8670f8)
[02:22:38] fail:     at corlib_System_Text_StringBuilder_ExpandByABlock_int (<anonymous>:wasm-function[37062]:0x867b72)
[02:22:38] fail:     at corlib_System_Text_StringBuilder_Append_char_int (<anonymous>:wasm-function[30675]:0x77f13c)
[02:22:38] fail:     at corlib_System_Text_StringBuilder_Append_char (<anonymous>:wasm-function[29788]:0x754a89)
[02:22:38] fail:     at corlib_System_Reflection_AssemblyNameFormatter_AppendQuoted_System_Text_StringBuilder_string (<anonymous>:wasm-function[41322]:0x918d6a)
[02:22:38] fail:     at corlib_System_Reflection_AssemblyNameFormatter_ComputeDisplayName_string_System_Version_string_byte___System_Reflection_AssemblyNameFlags_System_Reflection_AssemblyContentType (<anonymous>:wasm-function[40872]:0x904ff0)
[02:22:38] fail:     at corlib_System_Reflection_AssemblyName_get_FullName (<anonymous>:wasm-function[40871]:0x904f31)
[02:22:38] fail:     at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_ (<anonymous>:wasm-function[48366]:0xa63e08)
[02:22:38] fail:     at jit_call_cb (<anonymous>:wasm-function[96773]:0x16f48e2)
[02:22:38] fail:     at invoke_vi (./dotnet.js:8173:25)
[02:22:38] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[114048]:0x18ea304)
[02:22:38] fail:     at do_jit_call (<anonymous>:wasm-function[96730]:0x16f3996)
[02:22:38] fail:     at interp_exec_method (<anonymous>:wasm-function[96664]:0x16e692f)
[02:22:38] fail:     at interp_entry (<anonymous>:wasm-function[96711]:0x16f2e1d)
[02:22:38] fail:     at interp_entry_static_1 (<anonymous>:wasm-function[96806]:0x16f539f)
[02:22:38] fail:     at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[49882]:0xa82fcb)
[02:22:38] fail:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[8421]:0x1eb541)
[02:22:38] fail:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[8235]:0x1e2fa4)
[02:22:38] fail:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_aot_wrapper_gsharedvt_out_sig_obj_obju1obj (<anonymous>:wasm-function[8422]:0x1eb583)
[02:22:38] fail:     at jit_call_cb (<anonymous>:wasm-function[96773]:0x16f4917)
[02:22:38] fail:     at invoke_vi (./dotnet.js:8173:25)
[02:22:38] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[114048]:0x18ea304)
[02:22:38] fail:     at do_jit_call (<anonymous>:wasm-function[96730]:0x16f3996)
[02:22:38] fail:     at interp_exec_method (<anonymous>:wasm-function[96664]:0x16e692f)
[02:22:38] fail:     at interp_entry (<anonymous>:wasm-function[96711]:0x16f2e1d)
[02:22:38] fail:     at interp_entry_static_1 (<anonymous>:wasm-function[96806]:0x16f539f)
[02:22:38] fail:     at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[49882]:0xa82fcb)
[02:22:38] fail:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[8525]:0x1ee1d1)
[02:22:38] fail:     at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[8267]:0x1e4669)
[02:22:38] fail:     at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_ (<anonymous>:wasm-function[48366]:0xa63e08)
[02:22:38] fail:     at jit_call_cb (<anonymous>:wasm-function[96773]:0x16f48e2)
[02:22:38] fail:     at invoke_vi (./dotnet.js:8173:25)
[02:22:38] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[114048]:0x18ea304)
[02:22:38] fail:     at do_jit_call (<anonymous>:wasm-function[96730]:0x16f3996)
[02:22:38] fail:     at interp_exec_method (<anonymous>:wasm-function[96664]:0x16e692f)
[02:22:38] fail:     at interp_entry (<anonymous>:wasm-function[96711]:0x16f2e1d)
[02:22:38] fail:     at interp_entry_static_1 (<anonymous>:wasm-function[96806]:0x16f539f)
[02:22:38] fail:     at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[49882]:0xa82fcb)
[02:22:38] fail:     at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[88340]:0x156d66d)
[02:22:38] fail:     at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[88283]:0x156a522)
[02:22:38] fail:     at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_obj (<anonymous>:wasm-function[48364]:0xa63d77)
[02:22:38] fail:     at jit_call_cb (<anonymous>:wasm-function[96773]:0x16f48e2)
[02:22:38] fail:     at invoke_vi (./dotnet.js:8173:25)
[02:22:38] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[114048]:0x18ea304)
[02:22:38] fail:     at do_jit_call (<anonymous>:wasm-function[96730]:0x16f3996)
[02:22:38] fail:     at interp_exec_method (<anonymous>:wasm-function[96664]:0x16e692f)
[02:22:38] fail:     at interp_runtime_invoke (<anonymous>:wasm-function[96663]:0x16e5471)
[02:22:38] fail:     at mono_jit_runtime_invoke (<anonymous>:wasm-function[112977]:0x18c9916)
[02:22:38] fail:     at do_runtime_invoke (<anonymous>:wasm-function[101563]:0x178586d)
[02:22:38] fail:     at mono_runtime_try_invoke (<anonymous>:wasm-function[101574]:0x1785f81)
[02:22:38] fail:     at mono_runtime_invoke (<anonymous>:wasm-function[101652]:0x1788186)
[02:22:38] fail:     at mono_wasm_invoke_method (<anonymous>:wasm-function[114959]:0x190a4ed)
[02:22:38] fail:     at Module._mono_wasm_invoke_method (./dotnet.js:7265:117)
[02:22:38] fail:     at Object._.<computed> (./dotnet.js:24:3681)
[02:22:38] fail:     at _call_method_with_converted_args (./dotnet.js:38:35964)
[02:22:38] fail:     at call_method (./dotnet.js:38:35086)
[02:22:38] fail:     at ./dotnet.js:38:36968
[02:22:38] fail:     at Object.mono_call_assembly_entry_point [as call_assembly_entry_point] (./dotnet.js:38:37146)
[02:22:38] fail:     at Object.init (runtime.js:194:36)
[02:22:38] fail:     at Object.onDotNetReady (runtime.js:135:13)
[02:22:38] fail:     at _finalize_startup (./dotnet.js:38:49544)
[02:22:38] fail:     at ./dotnet.js:38:53722
[02:22:38] fail:     at i (./dotnet.js:38:1385)
[02:22:38] fail:     at Object.next (./dotnet.js:38:677)
[02:22:38] fail:     at a (./dotnet.js:38:242)
```

**Comment by radical** [comment]
Similar failure with `Wasm.Build.NativeRebuild.Tests.ReferenceNewAssemblyRebuildTest.ReferenceNewAssembly`+AOT:
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1473500&view=logs&j=439c6dc4-74cd-57d7-0b7a-a049ccfd9d90&t=4104ed37-d8c2-5ff0-cfcf-7ffa1988d34d)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-b43a84b5a5d9450aba/Workloads-.ReferenceNewAssemblyRebuildTest/1/console.bca0dd3f.log?sv=2019-07-07&)

```
        [wasm test] [08:06:40] fail: RuntimeError: null function or function signature mismatch
        [wasm test] [08:06:40] fail: RuntimeError: null function or function signature mismatch
        [wasm test] [08:06:40] fail:     at corlib_System_GC_AllocateUninitializedArray_T_BYTE_int_bool (<anonymous>:wasm-function[8898]:0x172ab6)
        [wasm test] [08:06:40] fail:     at corlib_System_Buffers_TlsOverPerCoreLockedStacksArrayPool_1_T_BYTE_Rent_int (<anonymous>:wasm-function[10296]:0x1b9b42)
        [wasm test] [08:06:40] fail:     at System_Text_Json_System_Text_Json_JsonDocument_MetadataDb_CreateRented_int_bool (<anonymous>:wasm-function[16505]:0x2aacdd)
        [wasm test] [08:06:40] fail:     at System_Text_Json_aot_wrapper_gsharedvt_out_sig_cl2f_Mono_dValueTuple_603_3cint_2c_20int_2c_20int_3e__i4u1 (<anonymous>:wasm-function[17335]:0x2dcc03)
        [wasm test] [08:06:40] fail:     at jit_call_cb (<anonymous>:wasm-function[17816]:0x2f8f91)
        [wasm test] [08:06:40] fail:     at invoke_vi (./dotnet.js:6436:25)
        [wasm test] [08:06:40] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[23889]:0x3b890b)
        [wasm test] [08:06:40] fail:     at do_jit_call (<anonymous>:wasm-function[17773]:0x2f803c)
        [wasm test] [08:06:40] fail:     at interp_exec_method (<anonymous>:wasm-function[17707]:0x2eaf76)
        [wasm test] [08:06:40] fail:     at interp_entry (<anonymous>:wasm-function[17754]:0x2f74c8)
```

**Comment by radical** [comment]
cc @vargaz @radekdoulik

**Comment by vargaz** [comment]
Does this only fail on windows ?

**Comment by radical** [comment]
I've only seen this on windows.

**Comment by lewing** [comment]
It's hitting here https://github.com/dotnet/runtime/blob/fc3787d17d37c73e4f9fcf01bc2cb8e4e5645193/src/mono/System.Private.CoreLib/src/System/GC.Mono.cs#L273

cc @BrzVlad

**Comment by radekdoulik** [comment]
I am able to reproduce it with browser-bench sample on windows.

It fails in `System_Linq_System_Linq_Enumerable_ToDictionary_TSource_REF_TKey_REF_TElement_REF_TSource_REF___System_Func_2_TSource_REF_TKey_REF_System_Func_2_TSource_REF_TElement_REF_System_Collections_Generic_IEqualityComparer_1_TKey_REF` function with `RuntimeError: indirect call signature mismatch`.

Here is the function from [bench sample](https://github.com/dotnet/runtime/files/7621422/wo.txt) build on windows. The error happens in `0x0002c3c3: call.indirect (func (param i32 i32 i32 i32))`. Didn't try it with https://github.com/vargaz/v8/tree/sig-mismatch yet.

The [diff](https://github.com/dotnet/runtime/files/7621433/i-w.diff.txt) between windows sample and imac sample.

I have also tried to bisect the problem on windows. The bench sample AOT version started to fail with https://github.com/dotnet/runtime/commit/62eafc1e67d332b902772065cb36b3c51c40c732. It doesn't crash the same way though, as the bench sample changed too and I am not able to build the current version with 62eafc1e67d332b902772065cb36b3c51c40c732 build.

@vargaz do you know what might be wrong here?

**Comment by radekdoulik** [comment]
I got a bit further, it looks like the above method is trying to call a method/constructor from `System.Collections.Generic.Dictionary`2<TKey_REF, TElement_REF>` class. It looks like we are missing bunch of methods there.

In app built on macos I see 664 functions, while in the app built on windows we have only 279 functions.

So we are missing these 385 [functions](https://github.com/dotnet/runtime/files/7637487/missing.txt) for that generic class.

I think the app is trying to call the missing `Wasm_Browser_Bench_Sample_System_Collections_Generic_Dictionary_2_TKey_REF_TValue_DOUBLE__ctor_System_Collections_Generic_IDictionary_2_TKey_REF_TValue_DOUBLE_System_Collections_Generic_IEqualityComparer_1_TKey_REF(param i32 i32 i32 i32))` function. I might confirm it by using the modified v8, I don't have it yet though.

I will try to find out why we are not generating functions for these generics on windows.
