### ISSUE TITLE
crossgen2 asserts: "OwningType == other.OwningType" in MethodWithToken.CompareTo

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#61732]
I'm trying to prejitt the latest version of PowerShell in R2R-Composite mode with mibc data and at some point it asserts here: https://github.com/dotnet/runtime/blob/83661ff53d0a43e354d839a3efeede3c089284c8/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs#L300

the types in that asserts are:
```
{[Microsoft.CodeAnalysis.CSharp]Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2+ILocalState<Microsoft.CodeAnalysis.CSharp.NullableWalker+LocalState,Microsoft.CodeAnalysis.CSharp.NullableWalker+LocalFunctionState>}
!=
{[Microsoft.CodeAnalysis.CSharp]Microsoft.CodeAnalysis.CSharp.AbstractFlowPass`2+ILocalState<Microsoft.CodeAnalysis.CSharp.NullableWalker+LocalState,System.__Canon>}
```

### Steps to reproduce
1) Build https://github.com/PowerShell/PowerShell locally, it should be just:
```ps
Import-Module ./build.psm1
Start-PSBootstrap
Start-PSBuild --configuration Release
```
2) Collect mibc data for a scenario where you only execute `pwsh.exe HelloWorld.ps1` where `HelloWorld.ps1` is just `Write-Host "Hello, World!"` or use my `ps.mibc` (here)
3) Try to prejit it using this command:
```
crossgen2.exe --targetos:windows --targetarch:x64 --embed-pgo-data --mibc:ps.mibc --Ot
 --composite --out:"C:\PS\pwsh.r2r.dll" C:\prj\PS\*.dll
```
### Expected:
pwsh.r2r.dll is successfully emitted

### Actual:
```
Process terminated. Assertion failed.
   at Internal.JitInterface.MethodWithToken.CompareTo(MethodWithToken other, TypeSystemComparer comparer) in C:\prj\runtime\src\coreclr\tools\aot\ILCompiler.ReadyToRun\JitInterface\CorInfoImpl.ReadyToRun.cs:line 300
   at ILCompiler.DependencyAnalysis.ReadyToRun.MethodFixupSignature.CompareToImpl(ISortableNode other, CompilerComparer comparer) in C:\prj\runtime\src\coreclr\tools\aot\ILCompiler.ReadyToRun\Compiler\DependencyAnalysis\ReadyToRun\MethodFixupSignature.cs:line 143
   at ILCompiler.DependencyAnalysis.SortableDependencyNode.ObjectNodeComparer.Compare(DependencyNodeCore`1 x1, DependencyNodeCore`1 y1) in C:\prj\runtime\src\coreclr\tools\Common\Compiler\DependencyAnalysis\SortableDependencyNode.cs:line 147
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.Merge(T[] localCopyOfHalfOfArray, TDataStructure arrayToSort, Int32 index, Int32 halfLen, Int32 length, TComparer comparer) in C:\prj\runtime\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 89
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in C:\prj\runtime\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 49
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.UnwrapPromise`1.TrySetFromTask(Task task, Boolean lookForOce)
   at System.Threading.Tasks.Task.RunOrQueueCompletionAction(ITaskCompletionAction completionAction, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) in C:\prj\runtime\src\coreclr\tools\Common\Sorting\MergeSortCore.cs:line 51
```
It also crashes on Release version of .NET 6.0

PS: Checked JIT might assert like this https://github.com/dotnet/runtime/issues/61705 but that assert can be removed/ignored for this issue.

**Comment by AndyAyersMS** [comment]
FYI @daxian-dbw in case you run into this too.

**Comment by EgorBo** [comment]
With Release version of jit/crossgen it crashes with
```
Failed to create CoreCLR, HRESULT: 0x80070002
```

**Comment by mangod9** [comment]
@EgorBo is this something we are tracking for 7?

**Comment by EgorBo** [comment]
> @EgorBo is this something we are tracking for 7?

I think we can move to 8.0 this, afaik it's Debug-only assert.

**Comment by davidwrighton** [comment]
This was fixed for .NET 7 as part of #71271, but it still fails in debug builds due to name mangling duplication. I'm putting a fix together for that for .NET 8.
