### ISSUE TITLE
Cannot sign certificates with elliptic curve secp256k1

### ISSUE THREAD

**Issue by msfcolombo** [dotnet/runtime#61767]
### Description

The `CertificateRequest.CreateSelfSigned` does not work with the blockchain curve secp256k1. I get an exception with message `The provided key does not match the public key for this certificate. (Parameter 'privateKey')`. The NIST P-256 curve works fine.

### Reproduction Steps

Run the following on Win10 x64 and dotnet 5.0.12:

```c#
using System;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace Secp256k1Repro
{
    public static class Secp256k1Repro
    {
        public static void Main()
        {
            Console.WriteLine("FrameworkDescription: {0}", RuntimeInformation.FrameworkDescription);
            Console.WriteLine("RuntimeIdentifier: {0}", RuntimeInformation.RuntimeIdentifier);
            Console.WriteLine("OSArchitecture: {0}", RuntimeInformation.OSArchitecture);
            Console.WriteLine("OSDescription: {0}", RuntimeInformation.OSDescription);
            Console.WriteLine("Environment Version: {0}", Environment.Version);

            TestCurve(ECCurve.NamedCurves.nistP256);
            TestCurve(ECCurve.CreateFromFriendlyName("secp256k1"));
        }

        private static void TestCurve(ECCurve curve)
        {
            Console.WriteLine("---------------------------");
            Console.WriteLine("Using curve oid={0}, friendlyName={1}", curve.Oid.Value, curve.Oid.FriendlyName ?? "(null)");
            try
            {
                ECDsa ecdsa = ECDsa.Create(curve);
                CertificateRequest req = new("CN=foo.com", ecdsa, HashAlgorithmName.SHA256);
                DateTimeOffset now = DateTimeOffset.UtcNow;
                req.CreateSelfSigned(now, now + TimeSpan.FromDays(180));
                Console.WriteLine("Worked.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0}", ex);
            }

            Console.WriteLine("---------------------------");
        }
    }
}

```

The output will be:

```
FrameworkDescription: .NET 5.0.12
RuntimeIdentifier: win10-x64
OSArchitecture: X64
OSDescription: Microsoft Windows 10.0.19043
Environment Version: 5.0.12
---------------------------
Using curve oid=1.2.840.10045.3.1.7, friendlyName=nistP256
Worked.
---------------------------
---------------------------
Using curve oid=1.3.132.0.10, friendlyName=secp256k1
System.ArgumentException: The provided key does not match the public key for this certificate. (Parameter 'privateKey')
   at System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, ECDsa privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Secp256k1Repro.Secp256k1Repro.TestCurve(ECCurve curve)
---------------------------
```

### Expected behavior

The `CertificateRequest.CreateSelfSigned` with curve SECP256K1 should return a valid certificate, just like it works when we use NIST curve P-256.

### Actual behavior

It's throwing the following exception:

```
System.ArgumentException: The provided key does not match the public key for this certificate. (Parameter 'privateKey')
   at System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, ECDsa privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
```

### Configuration

The repro steps outputs the framework version. For more details, see below:

```
C:\Secp256k1Repro>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Other information

Related: #25867.

**Comment by vcsjones** [comment]
Hm. Interestingly, this does work with a secp256k1 certificate on Windows:

```csharp
using System;
using System.Security.Cryptography.X509Certificates;

// Self-signed SecP256k1 PFX.
string pfx = "30820411020103308203cd06092a864886f70d010701a08203be048203ba" +
"308203b6308201c506092a864886f70d010701a08201b6048201b2308201" +
"ae308201aa060b2a864886f70d010c0a0102a081c43081c1301c060a2a86" +
"4886f70d010c0103300e0408013f471d711c2d15020207d00481a075053a" +
"6f4d6dade2cc4a74ce760e444f32d811723c2b6ab3fbd2a13197362a3507" +
"94a19ab5ef91402b2bc6679e4a8c5167e395e64dbdb0abd02f2040c16446" +
"a54705be2e9682fae59f0242f4fafa32763ed349aadae672ae7d37cc81cd" +
"0653205e4ff22ae27aa47b46fc3f2f8377bcf7d3a667ea552df4abbc2fb7" +
"ca62c61a21064704e315c5b7ccef47d3b340cb5d4c5c2d8634cddd07f11f" +
"9240a69a133d043181d3301306092a864886f70d01091531060404010000" +
"00305d06092a864886f70d01091431501e4e00740065002d003800620032" +
"00310039003500640062002d0036006200660034002d0034006600320032" +
"002d0061006300310037002d003200390063006600300035003400650038" +
"006300650066305d06092b060104018237110131501e4e004d0069006300" +
"72006f0073006f0066007400200053006f00660074007700610072006500" +
"20004b00650079002000530074006f007200610067006500200050007200" +
"6f00760069006400650072308201e906092a864886f70d010701a08201da" +
"048201d6308201d2308201ce060b2a864886f70d010c0a0103a08201a630" +
"8201a2060a2a864886f70d01091601a08201920482018e3082018a308201" +
"2fa003020102021042e803bd9684cba54784e01290323bb8300a06082a86" +
"48ce3d04030230143112301006035504030c096c6f63616c686f7374301e" +
"170d3231313131383137343931355a170d3232313131383138303931355a" +
"30143112301006035504030c096c6f63616c686f73743056301006072a86" +
"48ce3d020106052b8104000a03420004f7d1b21c4218adf938911480ff9f" +
"2ed1fe6c5bfbddf88665d52037f0e0ea034d35d5e2210049c86049bdfc98" +
"20ac217abe5948ba0cd9b1b7e4c2768d128541d6a3663064300e0603551d" +
"0f0101ff0404030205a0301d0603551d250416301406082b060105050703" +
"0206082b0601050507030130140603551d11040d300b82096c6f63616c68" +
"6f7374301d0603551d0e04160414e44a9c1a2968af202695b56f68957661" +
"6fb9ab29300a06082a8648ce3d0403020349003046022100dc2acbb617de" +
"3797a34e339c635c529fcbb1f53cc61c084e0440209a9a31442f022100a2" +
"14efc67e243a8277c814c56b93176b1296cb77b95b64a4eeb046c06acf45" +
"663115301306092a864886f70d0109153106040401000000303b301f3007" +
"06052b0e03021a04147323fc176c741b90076646ae9618cb9c4ab91edb04" +
"14340320435d36e5889c425ba0ced83ec552a211c2020207d0";

using X509Certificate2 cert = new(Convert.FromHexString(pfx), "test");
using X509Certificate2 pubOnly = new(cert.RawData);
using X509Certificate2 reCreate = pubOnly.CopyWithPrivateKey(cert.GetECDsaPrivateKey());
```

I would expect secp256k1 to work on Windows 10+ (and Linux). I'll take a look at this.

**Comment by vcsjones** [comment]
Heh, okay. This is a casing issue when we are comparing named curves. If you change to test example to:

```csharp
TestCurve(ECCurve.CreateFromFriendlyName("secP256k1"));
```

It will work. Note the capital P.

So this doesn't have anything to do with the curve, you can reproduce this with the NIST curve, too:

```csharp
TestCurve(ECCurve.CreateFromFriendlyName("NISTP256"));
```

I'll get a PR and some tests up to correct this behavior, but for now I would just use the "correct" casing of the curve name to get unblocked.

**Comment by vcsjones** [comment]
Also, thank you for the excellent steps and complete example to reproduce the problem.

**Comment by vcsjones** [comment]
Another interesting case is where one curve has multiple friendly names. e.g. even though this one is cased correctly, it will still fail because it is not the canonical friendly name.

```csharp
TestCurve(ECCurve.CreateFromFriendlyName("secP256r1"));
```

I think I have a handle on what needs to change here, PR coming soon.

**Comment by msfcolombo** [comment]
@vcsjones Thanks for quick answering this. It's odd that private key validation uses the friendly name for anything. I think algorithm type comparisons should use more discrete codes such as the OID.

**Comment by vcsjones** [comment]
> I think algorithm type comparisons should use more discrete codes such as the OID.

Right now it is using both the OID and and the FriendlyName. I think this is to handle some corner cases where some curves don't have an OID. e.g. ECDH can use `Curve25519` but that does not have an OID.

In general I would recommend using OIDs in place of friendly names where possible. For secP256k1:

```
ECCurve secP256k1 = ECCurve.CreateFromValue("1.3.132.0.10");
TestCurve(secP256k1);
```
