### ISSUE TITLE
HttpClient PutAsync/PostAsync with big payload works on .Net472 but not in .NetCore5 

### ISSUE THREAD

**Issue by Master-Oliveira** [dotnet/runtime#61921]
### Description

I have a very simple code to send a Put to an REST Api (Api developed in .NetCore) and published in Azure as an AppService. 

The code works with small payloads (json up to around 70k) but if the payload starts to become bigger than that, the problem starts to appear (in .Net5 only).

This exact same code works perfectly in .Net4.7.2 but in .NetCore5 it throws an error. 

One important note is that the problem only seems to appear when I publish the AppService to Azure and turn on **Client Certificate mode = allow/required**. If I keep this setting = Ignore the problem does not seems to appear.

I've noticed that the same behavior happens when I user the PowerShell Invoke-RestMethod. It works on PowerShell 5.1 but not in PowerShell Core 7.1.

Any help would be very appreciated because I have no idea where to look for the problem. 

```
 static async Task<string> SendSimple()
        {
            var result = string.Empty;

            using (var client = new HttpClient())
            {
                string text = File.ReadAllText("payload.json");

                var content = new StringContent(text, UnicodeEncoding.UTF8, "application/json");

                var response = await client.PutAsync("https://demoapi4.azurewebsites.net/WeatherForecast", content);

                result = await response.Content.ReadAsStringAsync();
            }

            return result;
        }
```

### Configuration

You can use this code and Azure Api to reproduce, just make 2 versions of a console application, one in .Net472 and other in .Net5 and run.

### Other information
The exception I get in .NetCore (after a while)
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (A task was canceled.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConnectionDemo.Program.Main(String[] args) in C:\Users\paolive\source\repos\ABB\Container Deployment\ConnectionDemo\ConnectionDemo\Program.cs:line 19

Inner Exception 1:
TaskCanceledException: A task was canceled.
```

**Comment by karelz** [comment]
Is it possible you are hitting default 100s timeout for requests? Did you try to adjust it? https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-6.0

**Comment by Master-Oliveira** [comment]
> Is it possible you are hitting default 100s timeout for requests? Did you try to adjust it? https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-6.0

Added the **client.Timeout = TimeSpan.FromMinutes(10);** 
Same issue. It throws the error (it's definitely some kind of timeout) at 2 minutes.

The API is a demo (weather forecast example from vs api templates) and returns in milliseconds and does not access any database. Just returns a dummy entity ;)

**Comment by scalablecory** [comment]
Can you show a full stack trace for the inner `TaskCanceledException` please?

**Comment by Master-Oliveira** [comment]
> Can you show a full stack trace for the inner `TaskCanceledException` please?

System.AggregateException: One or more errors occurred. (An error occurred while sending the request.)
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at ConnectionDemo.Program.SendSimple() in C:\Users\paolive\source\repos\ABB\Container Deployment\ConnectionDemo\ConnectionDemo\Program.cs:line 36
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConnectionDemo.Program.Main(String[] args) in C:\Users\paolive\source\repos\ABB\Container Deployment\ConnectionDemo\ConnectionDemo\Program.cs:line 19

**Comment by scalablecory** [comment]
Thanks. Note, this is not a `TaskCanceledException`, is this the correct error? It indicates the server, or maybe a firewall, unexpectedly reset the connection:

> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

**Comment by wfurt** [comment]
How big is your payload.json @Master-Oliveira? It seems like the site is reachable and I can give it try. 
When you allow/require the client certificate, IIS will cause TLS renegotiation on first request AFAIK. That on Windows has some major implication for SslStream. 
Can you try .NET 6 as well do following modification
```c#
_ = await client.GetAsync("https://demoapi4.azurewebsites.net/WeatherForecast");
var response = await client.PutAsync("https://demoapi4.azurewebsites.net/WeatherForecast", content);
```

**Comment by Master-Oliveira** [comment]
> Thanks. Note, this is not a `TaskCanceledException`, is this the correct error? It indicates the server, or maybe a firewall, unexpectedly reset the connection:
> 
> > System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

I don't really know how I got that TaskCanceledException :( sorry about that, maybe it was one of my debugs. This is the correct error I get.

**Comment by Master-Oliveira** [comment]
> How big is your payload.json @Master-Oliveira? It seems like the site is reachable and I can give it try. When you allow/require the client certificate, IIS will cause TLS renegotiation on first request AFAIK. That on Windows has some major implication for SslStream. Can you try .NET 6 as well do following modification
> 
> ```cs
> _ = await client.GetAsync("https://demoapi4.azurewebsites.net/WeatherForecast");
> var response = await client.PutAsync("https://demoapi4.azurewebsites.net/WeatherForecast", content);
> ```

@wfurt the exception is only thrown when the payload is bigger that 70Kb. Less than that we have no exception. 
The site on this thread is a simple api created by me to debug the issue, and you can use it to test ;) no problem. Its a weather forecast api from the visual studio templates.

One important note is, this code is being used in .Net 472 as a workaround. It only fails with .Net Core (just tested with .Net5).

I will try your suggestion with .Net6 and get back to you :)

**Comment by Master-Oliveira** [comment]
> How big is your payload.json @Master-Oliveira? It seems like the site is reachable and I can give it try. When you allow/require the client certificate, IIS will cause TLS renegotiation on first request AFAIK. That on Windows has some major implication for SslStream. Can you try .NET 6 as well do following modification
> 
> ```cs
> _ = await client.GetAsync("https://demoapi4.azurewebsites.net/WeatherForecast");
> var response = await client.PutAsync("https://demoapi4.azurewebsites.net/WeatherForecast", content);
> ```

@wfurt , the exception is only thrown when the payload is bigger that 70Kb. Less than that we have no exception. 
The site on this thread is a simple api created by me to debug the issue, and you can use it to test ;) no problem. Its a weather forecast api from visualstudio templates.

One note is, this code is being used in .Net 472 as a workaround. It only fails with .Net Core (just tested with .Net5).

**Comment by karelz** [comment]
Triage: Looks like something we should understand -- and fix, or close if it is still just some timeout.
Not regression in recent .NET Core, so impact is likely limited to specific scenarios -- fine for 7.0. No need to service unless we hear about more impacted customers.

**Comment by calvindoosy** [comment]
I am having the same issue, .NetCore5 console application.

**Comment by wfurt** [comment]
Is it also visible _only_ with `Certificate mode = allow/required` @calvindoosy? (and of course stack trace & repro may be helpful)

**Comment by saintogod** [comment]
When server response StatusCodes.Status413PayloadTooLarge, HttpClient throw SockectException. While it should throw the HttpRequestException with the correct status code.

**Comment by saintogod** [comment]
same error, if server response before read all the request stream (e.g. response 413), the HttpClient will fail at copying the request stream, and the response will be ignored. The same endpoint works fine in postman.

**Comment by wfurt** [comment]
That was just guess @Master-Oliveira. I tried to take closet look and it seems like the site is down. 
I did not ask before, but there is no authentication, right? 

Thinking about it again, it reminds me issue @Tratcher was investigating. With the request for certificates, IIS (or some other server) needs to wait for request to come. With the PUT/POST it cannot be done and the session fails. There _may_ be some way how to configure it. This is why the extra GET fixes it as the renegotiation happens during that. 
The difference with 4.7 is still curious. I'm wondering if that sends 100Continue by default.

**Comment by Master-Oliveira** [comment]
> That was just guess @Master-Oliveira. I tried to take closet look and it seems like the site is down. I did not ask before, but there is no authentication, right?
> 
> Thinking about it again, it reminds me issue @Tratcher was investigating. With the request for certificates, IIS (or some other server) needs to wait for request to come. With the PUT/POST it cannot be done and the session fails. There _may_ be some way how to configure it. This is why the extra GET fixes it as the renegotiation happens during that. The difference with 4.7 is still curious. I'm wondering if that sends 100Continue by default.

Hi @wfurt, I deleted the demo api site. I've recreated the site again and you should be able to try again :)

There is no authentication, except the setting for allow client certificates.

**Comment by Tratcher** [comment]
Delayed client cert negotiation is inherently problematic for POST/PUT requests. There's a server focused write-up of the challenges here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/certauth?view=aspnetcore-6.0#optional-client-certificates

The request body fills up the connection and then the TLS session can't renegotiate to retrieve the client cert. IIS/AppService mitigates this by buffering the request body, but only up to about 50kb(?).

100-continue can also help mitigate the issue, but you may need to raise the 100-continue timeout.

**Comment by karelz** [comment]
Triage: Low impact on customers, not a regression. Moving to Future.
