### ISSUE TITLE
[wasm] JS Interop tests failing with latest chrome - `JavaScript host object 'SharedArrayBuffer' not found`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#61945]
https://github.com/dotnet/runtime/pull/61937 upgrades chrome used to run the tests, to the latest stable version - `96.0.4664.45`:

```
[22:46:06] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTests.CoreTypes
[22:46:06] info: System.Runtime.InteropServices.JavaScript.JSException : JavaScript host object 'SharedArrayBuffer' not found.
[22:46:06] info:    at System.Runtime.InteropServices.JavaScript.Runtime.CreateCSOwnedObject(JSObject proxy, String typeName, Object[] parms)
[22:46:06] info:    at System.Runtime.InteropServices.JavaScript.JSObject..ctor(String typeName, Object[] _params)
[22:46:06] info:    at System.Runtime.InteropServices.JavaScript.CoreObject..ctor(String typeName, Object[] _params)
[22:46:06] info:    at System.Runtime.InteropServices.JavaScript.SharedArrayBuffer..ctor(Int32 length)
[22:46:06] info:    at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTests.CoreTypes()
[22:46:06] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1481554&view=logs&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c), and [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61937-merge-d2b2afdfaf62417cb3/System.Private.Runtime.InteropServices.JavaScript.Tests/1/console.280fc281.log?sv=2019-07-07&)

**Comment by radical** [comment]
cc @kg @pavelsavara

**Comment by radical** [comment]
Strangely, this doesn't seem to fail on AOT - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61937-merge-a4bb0d1fb1df4755bf/System.Private.Runtime.InteropServices.JavaScript.Tests/1/console.dfb115ec.log?sv=2019-07-07& .

**Comment by kg** [comment]
What version of chrome was it previously? They're changing the requirements to access it. https://developer.chrome.com/blog/enabling-shared-array-buffer/

**Comment by radical** [comment]
We were running with - 84.0.4147.105

**Comment by kg** [comment]
Then based on that post I linked, this is an expected failure and we need to make policy header changes. I don't know exactly how it works since COEP/COOP/etc headers are a nightmare. It might be as simple as generating the right headers in whatever httpd we use to serve tests.

**Comment by pavelsavara** [comment]
I can reproduce it locally. I will have look at xharness http server and see if we could set the headers. 
Possibly there are few remaining endpoints we touch on Azure for HTTP unit tests in [OuterLoop] I wonder if that's impacted.
