### ISSUE TITLE
System.Diagnostics.Tests.StopwatchTests.GetTimestamp test fails in the CI

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#62021]
### Description

https://dev.azure.com/dnceng/public/_build/results?buildId=1483932&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61992-merge-7fb43d6a883f4488b6/System.Runtime.Extensions.Tests/1/console.767e6c7f.log?sv=2019-07-07&se=2021-12-14T02%3A29%3A30Z&sr=c&sp=rl&sig=z6v3ggZBbFYzzSs7RnkjjXGrSz8%2Fu01LaKM7xQ8zMAw%3D

```
[02:51:21] info: Incoming arguments: --run WasmTestRunner.dll System.Runtime.Extensions.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[02:51:21] info: Application arguments: --run WasmTestRunner.dll System.Runtime.Extensions.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[02:51:21] info: browser: Console websocket connected.
[02:51:22] info: Initializing.....
[02:51:23] info: Discovering: System.Runtime.Extensions.Tests.dll (method display = ClassAndMethod, method display options = None)
[02:51:24] info: Discovered:  System.Runtime.Extensions.Tests.dll (found 912 of 1000 test cases)
[02:51:24] info: Starting:    System.Runtime.Extensions.Tests.dll
[02:51:25] fail: [FAIL] System.Diagnostics.Tests.StopwatchTests.GetTimestamp
[02:51:25] info: Assert.NotEqual() Failure
[02:51:25] info: Expected: Not 4485599999
[02:51:25] info: Actual:   4485599999
[02:51:25] info:    at System.Diagnostics.Tests.StopwatchTests.GetTimestamp()
[02:51:25] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
[02:51:51] info: Finished:    System.Runtime.Extensions.Tests.dll
```

### Reproduction Steps

CI run

### Expected behavior

No failures

### Actual behavior

The test fails

**Comment by danmoseley** [comment]
same in #61768 
```
❌ System.Diagnostics.Tests.StopwatchTests.GetTimestamp [Details] [History] [Artifacts]
Exception Message
Assert.NotEqual() Failure
Expected: Not 8873699999
Actual:   8873699999
CallStack
   at System.Diagnostics.Tests.StopwatchTests.GetTimestamp()
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
Pass Rate
Test has failed 7 out of 37212 runs (0.02%)
Failing Configuration
net7.0-Browser-Release-wasm-Mono_Release-wasmtestonbrowser-Ubuntu.1804.Amd64.Open
```

**Comment by danmoseley** [comment]
This means that this is getting called twice in approx 1ms and returning the same result. @lewing does Wasm have a larger quantum, or jitter? If so we should make the test sleep longer.

https://github.com/dotnet/runtime/blob/6f44dbe5e764972c29ef529ec3ee297b5e7a5a65/src/native/libs/System.Native/pal_time.c#L56

**Comment by akoeplinger** [comment]
Also saw it in https://github.com/dotnet/runtime/pull/62244, I wonder though why this started failing recently since the test is untouched since 2020.

**Comment by danmoseley** [comment]
The test is untouched, my assumption is that clock_gettime (or clock_gettime_nsec_np) changed on Blazor (?)

**Comment by danmoseley** [comment]
@lewing may know.

**Comment by lewing** [comment]
The browser definitely has lower resolution than desktop but I'm also a bit unsure why it started failing recently. @pavelsavara any thoughts?

**Comment by pavelsavara** [comment]
We have new chrome, it may be the cause.
https://developer.chrome.com/blog/cross-origin-isolated-hr-timers/

**Comment by pavelsavara** [comment]
@radical could we close this one ?

**Comment by radical** [comment]
If we are good with the workaround, and won't be fixing it, then feel free to close the issue.

**Comment by pavelsavara** [comment]
There is also CLOCK_MONOTONIC feature in emscripten. I don't  know much about it yet.
https://github.com/emscripten-core/emscripten/pull/2761

Should we explore this topic further @lewing ?

**Comment by radical** [comment]
Another failure due to the same reason, IIUC:

```
[00:32:41] fail: [FAIL] System.Diagnostics.Tests.StopwatchTests.StartNewAndReset
[00:32:41] info: Assert.True() Failure
[00:32:41] info: Expected: True
[00:32:41] info: Actual:   False
[00:32:41] info:    at System.Diagnostics.Tests.StopwatchTests.StartNewAndReset()
[00:32:41] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62400-merge-731c7d739fe9436695/System.Runtime.Extensions.Tests/1/console.962c38b0.log?sv=2019-07-07&se=2021-12-25T00%3A01%3A26Z&sr=c&sp=rl&sig=63muZ%2BiSX5Pm0bcwz2%2Ba7oX5Rth1zzdcep6ib91CAI8%3D
