### ISSUE TITLE
Test failure JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62033]
Run: [runtime-coreclr outerloop 20211124.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1484981&view=ms.vss-test-web.build-test-results-tab&runId=42484430&paneView=debug&resultId=107774)

Failed test:
```
R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

```
**Error message:**
```
Could Not Find C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\poison.dll.rsp

Return code:      1
Raw output file:      C:\h\w\AD300929\w\B36A09CB\uploads\Reports\JIT.Directed\debugging\poisoning\poison\poison.output.txt
Raw output:
BEGIN EXECUTION
poison.dll
1 file(s) copied.
Response file: C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\poison.dll.rsp
C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\IL-CG2\poison.dll
-o:C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\poison.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AD300929\p\System..dll
-r:C:\h\w\AD300929\p\Microsoft..dll
-r:C:\h\w\AD300929\p\mscorlib.dll
-r:C:\h\w\AD300929\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AD300929\p\crossgen2\crossgen2.dll" @"C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\poison.dll.rsp"   -r:C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\poison.dll
"C:\h\w\AD300929\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  poison.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AD300929\p
C:\h\w\AD300929\w\B36A09CB\e\JIT\Directed\debugging\poisoning\poison\poison.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._debugging_poisoning_poison_poison_._debugging_poisoning_poison_poison_cmd()
```
Failed test:
```
R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Directed/debugging/poisoning/poison/poison.sh

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Directed/debugging/poisoning/poison/poison.sh

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1014.Amd64.Open
- JIT/Directed/debugging/poisoning/poison/poison.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3
- JIT/Directed/debugging/poisoning/poison/poison.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT/Directed/debugging/poisoning/poison/poison.sh

R2R-CG2 OSX x64 Checked @ OSX.1014.Amd64.Open
- JIT/Directed/debugging/poisoning/poison/poison.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.sh: line 246: -r:/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.dll.rsp': No such file or directory

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Directed/debugging/poisoning/poison/poison.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/IL-CG2/poison.dll
Response file: /root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.dll.rsp
/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/IL-CG2/poison.dll
-o:/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.dll
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false poison.dll ''
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/Directed/debugging/poisoning/poison/poison.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._debugging_poisoning_poison_poison_._debugging_poisoning_poison_poison_sh()
```

**Comment by jakobbotsch** [comment]
Fixed with #62051
