### ISSUE TITLE
Test failure Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62067]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20211124.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1485225&view=ms.vss-test-web.build-test-results-tab&runId=42488674&paneView=debug&resultId=103086)

Failed test:
```
CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x64 Checked gcstress0x3 @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd
```
**Error message:**
```
Assert failure(PID 3468 [0x00000d8c], Thread: 4896 [0x1320]): !th.IsNull()

CORECLR! SigPointer::GetTypeHandleThrowing + 0x620 (0x70dce98d)
CORECLR! SigPointer::PeekElemTypeNormalized + 0x1D7 (0x70dd2f32)
CORECLR! MetaSig::PeekArgNormalized + 0x20 (0x70dd2aae)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::ForceSigWalk + 0x189 (0x70c1b603)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::SizeOfArgStack + 0x10 (0x70c372cb)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::GetNextOffset + 0x66 (0x70c36338)
CORECLR! TransitionFrame::PromoteCallerStackHelper + 0x113 (0x70d0ba35)
CORECLR! TransitionFrame::PromoteCallerStack + 0xEE (0x70d0b91b)
CORECLR! GcStackCrawlCallBack + 0x1EA (0x70ec3c1a)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x70dd5e83)
File: D:\a_work\1\s\src\coreclr\vm\siginfo.cpp Line: 1112
Image: C:\h\w\A93B08DB\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A93B08DB\w\A06008C3\uploads\Reports\Interop.COM\Activator\ActivatorBuiltInComDisabled\ActivatorBuiltInComDisabled.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A93B08DB\p\corerun.exe" -p "System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ActivatorBuiltInComDisabled.dll
Built-in COM Disabled?: True
Running InvalidInterfaceRequest...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A93B08DB\p
C:\h\w\A93B08DB\w\A06008C3\e\Interop\COM\Activator\ActivatorBuiltInComDisabled\ActivatorBuiltInComDisabled.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._Activator_ActivatorBuiltInComDisabled_ActivatorBuiltInComDisabled_._Activator_ActivatorBuiltInComDisabled_ActivatorBuiltInComDisabled_cmd()
```

**Comment by AaronRobinsonMSFT** [comment]
This appears to have uncovered an issue with the changes in https://github.com/dotnet/runtime/pull/61754. It seems the type system is failing to preload the type, but honestly I don't fully understand this part of the codebase.

https://github.com/dotnet/runtime/blob/39b4f2661f7ea5abbffcb1cb15e78363af9a81c7/src/coreclr/vm/siginfo.cpp#L1095-L1114

@jkotas or @davidwrighton Any thoughts on why the above would trigger for GCStress when during the JIT of `GetClassFactoryForType`?

https://github.com/dotnet/runtime/blob/39b4f2661f7ea5abbffcb1cb15e78363af9a81c7/src/tests/Interop/COM/Activator/Program.cs#L55-L61

**Comment by jkotas** [comment]
It looks like a bug in `RuntimeMethodHandle_GetFunctionPointer` and potentially other places that hand back function pointers to unsafe code. The runtime requires that all types in method signatures are loaded before the method is called. This invariant is violated here.

Can you try to add `pMethod->PrepareForUseAsADependencyOfANativeImage()` to `RuntimeMethodHandle_GetFunctionPointer` to see whether it fixes the problem?

If it does, we should introduce a new method (e.g. called `PrepareForUseAsAFunctionPointer`) that is just like `PrepareForUseAsADependencyOfANativeImage` expect that it does not catch exceptions, and call it there.

**Comment by AaronRobinsonMSFT** [comment]
That doesn't seem to do anything for this case. From what I can tell all it does it resolve to the correct TypeDef Token. Looking at other uses, Type Equivalence, I need to also load the type so I am trying that now.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr gcstress0x3-gcstress0xc 20211205.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1497785&view=ms.vss-test-web.build-test-results-tab&runId=42737494&paneView=debug&resultId=100736)

Failed test:
```
CoreCLR windows x64 Checked gcstress0x3 @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd

CoreCLR windows x64 Checked gcstress0xc @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\Activator\\Activator.cmd
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\Activator\\Activator.cmd
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open
- Interop\\COM\\Activator\\Activator\\Activator.cmd
- Interop\\COM\\Activator\\ActivatorBuiltInComDisabled\\ActivatorBuiltInComDisabled.cmd

```
**Error message:**
```
Assert failure(PID 4000 [0x00000fa0], Thread: 3596 [0x0e0c]): !th.IsNull()

CORECLR! SigPointer::GetTypeHandleThrowing + 0xACD (0x00007ff82e9bf71d) CORECLR! SigPointer::PeekElemTypeNormalized + 0x2C4 (0x00007ff82e9c6124)
CORECLR! ArgIteratorTemplate<ArgIteratorBase>::GetNextOffset + 0x119 (0x00007ff82e752ed9) CORECLR! TransitionFrame::PromoteCallerStackHelper + 0x1A7 (0x00007ff82e8a1d47)
CORECLR! TransitionFrame::PromoteCallerStack + 0x168 (0x00007ff82e8a1a38) CORECLR! GcStackCrawlCallBack + 0x47C (0x00007ff82eb2295c)
CORECLR! Thread::StackWalkFramesEx + 0x26C (0x00007ff82e9cd7cc) CORECLR! Thread::StackWalkFrames + 0x184 (0x00007ff82e9cd4b4)
CORECLR! ScanStackRoots + 0x284 (0x00007ff82eb21124) CORECLR! GCToEEInterface::GcScanRoots + 0x1A2 (0x00007ff82eb1ead2)
File: D:\a_work\1\s\src\coreclr\vm\siginfo.cpp Line: 1112
Image: C:\h\w\A3E60919\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A3E60919\w\A63408FD\uploads\Reports\Interop.COM\Activator\ActivatorBuiltInComDisabled\ActivatorBuiltInComDisabled.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A3E60919\p\corerun.exe" -p "System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ActivatorBuiltInComDisabled.dll
Built-in COM Disabled?: True
Running InvalidInterfaceRequest...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A3E60919\p
C:\h\w\A3E60919\w\A63408FD\e\Interop\COM\Activator\ActivatorBuiltInComDisabled\ActivatorBuiltInComDisabled.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._Activator_ActivatorBuiltInComDisabled_ActivatorBuiltInComDisabled_._Activator_ActivatorBuiltInComDisabled_ActivatorBuiltInComDisabled_cmd()
```
