### ISSUE TITLE
[WASM] System.Text.Json.Serialization.Tests - Specified cast is not valid.

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#62125]
### Description

There is problem with `libmono-component-diagnostics_tracing-stub-static.a` vs `libmono-component-diagnostics_tracing-static.a` happens by including both in `artifacts\obj\System.Text.Json.Tests\net7.0-Release\browser-wasm\wasm\for-publish\emcc-link.rsp` in semi-random order. 

- If we have both, all is "fine" - currently on main branch, with AOT, without workload.
- When full implementation goes first, we will get the IPC socket initialization failure https://github.com/dotnet/runtime/issues/61294. 
- If we only have stub, we get problems with json described in this issue

### Reproduction Steps

1) When we don't link full version of eventPipe is causing it. Here are the changes which are triggering it: 
https://github.com/dotnet/runtime/pull/62116

2) Or When we don't even compile full version at all:
https://github.com/dotnet/runtime/pull/62143

### Failures

```
[FAIL] System.Text.Json.Serialization.Tests.StreamTests_Async.ReadObjectWithWhitespaceAndThenInvalid(bufferSize: 16)
Assert.Throws() Failure
Expected: typeof(System.Text.Json.JsonException)
Actual:   typeof(System.InvalidCastException): Specified cast is not valid.
---- System.InvalidCastException : Specified cast is not valid.
   at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at System.Text.Json.Serialization.Tests.JsonSerializerWrapperForStream.AsyncStreamSerializerWrapper.<DeserializeWrapper>d__3`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at System.Text.Json.Serialization.Tests.StreamTests.<>c__DisplayClass44_1.<<ReadObjectWithWhitespaceAndThenInvalid>b__0>d.MoveNext()
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at System.Text.Json.Serialization.Tests.JsonSerializerWrapperForStream.AsyncStreamSerializerWrapper.<DeserializeWrapper>d__3`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at System.Text.Json.Serialization.Tests.StreamTests.<>c__DisplayClass44_1.<<ReadObjectWithWhitespaceAndThenInvalid>b__0>d.MoveNext()
```

```
[FAIL] System.Text.Json.Serialization.Tests.StreamTests_Async.VeryLargeJsonFileTest(payloadSize: 1, ignoreNull: False, writeIndented: True)
System.InvalidCastException : Specified cast is not valid.
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[System.Text.Json.Serialization.Tests.Schemas.OrderPayload.Order, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(Utf8JsonWriter writer, List`1& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[List`1](List`1& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.Serialization.Tests.StreamTests.VeryLargeJsonFileTest(Int32 payloadSize, Boolean ignoreNull, Boolean writeIndented)
```

```
[FAIL] System.Text.Json.Serialization.Tests.StreamTests_Async.VeryLargeJsonFileTest(payloadSize: 10, ignoreNull: True, writeIndented: False)
System.InvalidCastException : Specified cast is not valid.
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[System.Text.Json.Serialization.Tests.Schemas.OrderPayload.Order, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[List`1](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.Serialization.Tests.StreamTests.VeryLargeJsonFileTest(Int32 payloadSize, Boolean ignoreNull, Boolean writeIndented)
```

```
[FAIL] System.Text.Json.Serialization.Tests.CacheTests.MultipleTypes(testObj: SimpleTestClass { MyBooleanFalse = False, MyBooleanFalseArray = null, MyBooleanTrue = False, MyBooleanTrueArray = null, MyByte = 0, ... })
System.InvalidCastException : Specified cast is not valid.
   at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[Object](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Text.Json.Serialization.Tests.CacheTests.MultipleTypes(ITestClass testObj)
```

```
[FAIL] System.Text.Json.Serialization.Tests.StreamTests_Async.VeryLargeJsonFileTest(payloadSize: 1, ignoreNull: True, writeIndented: True)
[17:41:23] info: Assert.Equal() Failure
[17:41:23] info:                                   ↓ (pos 87)
[17:41:23] info: Expected: ···fbbb888kkk",\n      "Name": "John Doe",\n      "Username": "joh···
[17:41:23] info: Actual:   ···fbbb888kkk",\n      "Username": "johndoe",\n      "CreatedAt": ···
```

### Expected behavior

Unit tests passing

### Actual behavior

Unit tests fail. 

### Regression?

Probably this just uncovers some issue with ordering of Tasks/Promises or attribution of exceptions.

### Configuration

Only AOT, both Debug and Release.

**Comment by pavelsavara** [comment]
@radical does this happen also in your attempt to fix https://github.com/dotnet/runtime/issues/61294 ?
cc @lewing @kg @radekdoulik @maraf - guys any ideas why this is happening are appreciated, thanks!

**Comment by radical** [comment]
> @radical does this happen also in your attempt to fix https://github.com/dotnet/runtime/issues/61294 ?

No

**Comment by pavelsavara** [comment]
> > @radical does this happen also in your attempt to fix #61294 ?
> 
> No

What makes the difference ? Is workload in your fix doing more than setting `_MonoRuntimeComponentDontLink` ? @radical

**Comment by pavelsavara** [comment]
The problem with `libmono-component-diagnostics_tracing-stub-static.a` vs `libmono-component-diagnostics_tracing-static.a` happens by including both in `artifacts\obj\System.Text.Json.Tests\net7.0-Release\browser-wasm\wasm\for-publish\emcc-link.rsp` in semi-random order. 
- When full implementation goes first, we will get the IPC socket initialization failure. 
- If we have both, all is "fine"
- If we only have stub, we get problems with json

**Comment by pavelsavara** [comment]
More test runs locally, with detailed exception about type mismatch
It seems it's some race condition and very simillar next test has another unexpected type `TestClassWithNestedObjectOuter` vs .
`Concurrent.ConcurrentQueue<UInt32>`

```
[FAIL] System.Text.Json.Serialization.Tests.StreamTests_Async.ReadObjectWithWhitespaceAndThenInvalid(bufferSize: 1)
Assert.Throws() Failure
Expected: typeof(System.Text.Json.JsonException)
Actual:   typeof(System.Exception): Pavel Expected type 'System.Text.Json.Serialization.Tests.SimpleTestClass', got 'System.Text.Json.Serialization.Tests.TestClassWithNestedObjectOuter'.
---- System.Exception : Pavel Expected type 'System.Text.Json.Serialization.Tests.SimpleTestClass', got 'System.Text.Json.Serialization.Tests.TestClassWithNestedObjectOuter'.
[FAIL] System.Text.Json.Serialization.Tests.StreamTests_Async.ReadObjectWithWhitespaceAndThenInvalid(bufferSize: 16)
Assert.Throws() Failure
Expected: typeof(System.Text.Json.JsonException)
Actual:   typeof(System.Exception): Pavel Expected type 'System.Text.Json.Serialization.Tests.SimpleTestClass', got 'System.Collections.Concurrent.ConcurrentQueue`1[[System.UInt32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
---- System.Exception : Pavel Expected type 'System.Text.Json.Serialization.Tests.SimpleTestClass', got 'System.Collections.Concurrent.ConcurrentQueue`1[[System.UInt32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at System.Text.Json.Serialization.JsonConverter`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[System.Text.Json.Serialization.Tests.SimpleTestClass, System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
```

**Comment by pavelsavara** [comment]
Not compiling the full version of eventPipe causes the problems in same way and linking them out does. 
See https://github.com/dotnet/runtime/pull/62143

**Comment by pavelsavara** [comment]
We had conversation with @lateralusX, we think that EventPipe is not the cause of the real issue, but it covers the issue when it's present.
I also think that json issues are just symptom of some race condition. Is that order of Tasks processing ? Or something wrong with streams/buffers ? Or how locks interact with async ?

**Comment by pavelsavara** [comment]
@lambdageek noted: I was also looking at ExceptionDispatchInfo.Capture (used here https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs#L275) which is something that interacts with all the pieces in the issue except EventPipe

**Comment by lewing** [comment]
@lambdageek is this resolved now?
