### ISSUE TITLE
FileLoadException thrown while loading the assembly name

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#62159]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FileLoadException-thrown-while-loading-t/1595810)._

---
We faced the file load exception while loading the assembly name. But it works fine in the .net framework. We faced the issue only in NET50. We created the simple sample by getting the assembly name using Assembly.GetAssembly method in the Button click and then load the by invoking the Assembly.LoadFile method. Please refer to the following screenshot for your reference. Please find the stack trace details below,&nbsp;&nbsp;

 
[MicrosoftTeams-image (133).png](https://aka.ms/dc/file?name=B0e4d7f7fd9024385a28584728182da3a637734517058007189_MicrosoftTeams-image_(133).png&tid=0e4d7f7fd9024385a28584728182da3a637734517058007189)

```
at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)

   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)

   at System.Reflection.Assembly.LoadFile(String path)

   at WpfApp1.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in D:\Incident\170660\WpfApp1\MainWindow.xaml.cs:line 33

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)

   at System.Windows.Controls.Primitives.ButtonBase.OnClick()

   at System.Windows.Controls.Button.OnClick()

   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)

   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)

   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)

   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)

   at System.Windows.Input.InputManager.ProcessStagingArea()

   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)

   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)

   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.Run()

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run()

   at WpfApp1.App.Main()
```

&nbsp;Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/WpfApp11903085856

Replication steps:
1. Run the attached demo
2. Click the Button.
3. System.IO.FileLoadException thrown after clicking the button.

Could you please advise me on how to resolve the following problem?

---
#### Feedback Bot on 11/25/2021, 10:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ThirupathiBalakrishnan** [comment]
Hi @vitek-karas,

Actually, we used the above code for Intellisense support, which is what we needed. We use the custom control by default to offer Intellisense support. We'll find out the namespaces, public APIs and methods based on the specified assembly by using the Assembly.LoadFile method. We did not encounter any exceptions in the.Net framework, and we can also access the assembly's properties and methods. We expect the same functionality in NET50 . We attempted to do the same in NET50, but were met with a FileLoadException.

Could you please recommend a solution to this problem?

Thanks in advance.

Regards,
Thirupathi B.

**Comment by vitek-karas** [comment]
If all you need is inspection on the assembly, so just metadata, and you won't try to run any code from it, then the best solution is [`MetadataLoadContext`](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext). This has many advantages over loading the assembly directly by the runtime:
* Fully collectible memory - `MetadataLoadContext` parses the file and creates pure managed objects from it, it does not load any parts of the assembly into the runtime. As such all of it is just your typical GC collected memory and will go away once you don't need it.
* Can load any assembly - even if the versions don't match. For example this would let you load .NET 6 assembly in a .NET 5 process (which would otherwise not be possible). Or in fact you can load .NET Framework assembly in a .NET 5 process.
* It's faster then loading things into the runtime - and probably more memory efficient (I didn't run the numbers) as it doesn't need to create the relevant runtime structures around it.

On the other hand, it exposes the assembly via normal reflection APIs like `System.Type`, `System.Reflection.MethodInfo` and so on, so you should not need to change your code (mostly).
You can use the NuGet package `System.Reflection.MetadataLoadContext` even in .NET Framework. So if you need to slowly migrate, you can change your code to use `MetadataLoadContext` and run it on both .NET Framework and .NET 5 - same code should work in both.
