### ISSUE TITLE
Test failure System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Tls13)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62168]
Run: [runtime 20211129.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1489344&view=ms.vss-test-web.build-test-results-tab&runId=42576978&resultId=197112&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server20H2.Open

- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Tls13)

```
**Error message:**
```
System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.


Stack trace
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 1101
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 556
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 381
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 397
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(SslProtocols protocol) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Triage: New OS in the matrix, @aik-jahoda is looking into it.

**Comment by rzikm** [comment]
There have been 2 occurrences of this failure over the past 2.5 months, both with Ssl3 on `Windows.10.Arm64v8.Open` queues. We are unlikely to fix a failure with such low occurence.
