### ISSUE TITLE
Test failure System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls13)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62171]
Run: [runtime 20211129.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1489344&view=ms.vss-test-web.build-test-results-tab&runId=42576978&resultId=197107&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server20H2.Open
- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(serverProtocol: Tls13)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 10240, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 10240, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 42, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 42, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 1, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 1, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.Read_Eof_Returns0(mode: AsyncAPM, dataAvailableFirst: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.Read_Eof_Returns0(mode: SyncAPM, dataAvailableFirst: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.Read_Eof_Returns0(mode: AsyncMemory, dataAvailableFirst: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.CopyToAsync_AllDataCopied(byteCount: 4096, useAsync: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.CopyToAsync_AllDataCopied(byteCount: 4095, useAsync: False)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.CopyToAsync_AllDataCopied(byteCount: 4095, useAsync: True)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.CopyToAsync_AllDataCopied(byteCount: 1024, useAsync: False)
- System.Net.Security.Tests.SslStreamTls13NetworkConformanceTests.***
```
**Error message:**
```
System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.


Stack trace
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc) in /_/src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs:line 138
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 574
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 276
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 126
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 713
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 782
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 745
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 593
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 556
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 381
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 397
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_AllClientVsIndividualServerSupportedProtocols_Success(SslProtocols serverProtocol) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 71
--- End of stack trace from previous location ---
```

**Comment by wfurt** [comment]
There should not be Tls13 on Server20H2 AFAIK. I'm wondering if this was forced/enable via registry.
cc: @MattGal

**Comment by karelz** [comment]
Triage: New OS in the matrix, @aik-jahoda is looking into it.

**Comment by aik-jahoda** [comment]
Reenabling 20H2 as there is update 20H2 image in Helix: https://github.com/dotnet/runtime/pull/62435
