### ISSUE TITLE
Test failure DllImportGenerator.UnitTests.ManualTypeMarshallingAnalyzerTests.NativeTypeWithGetPinnableReferenceNoValueProperty_ReportsDiagnostic

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62223]
Run: [runtime 20211130.61](https://dev.azure.com/dnceng/public/_build/results?buildId=1491004&view=ms.vss-test-web.build-test-results-tab&runId=42612220&resultId=102968&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

- DllImportGenerator.UnitTests.ManualTypeMarshallingAnalyzerTests.NativeTypeWithGetPinnableReferenceNoValueProperty_ReportsDiagnostic

```
**Error message:**
```
Context: Diagnostics of test state
Expected diagnostic to be in file "/0/Test0.cs" was actually in file ""

Expected diagnostic:
// /0/Test0.cs(21,21,21,41): error DLLIMPORTGENANALYZER018: The 'GetPinnableReference' method cannot be provided on the native type 'Native' unless a 'Value' property is also provided
VerifyCS.Diagnostic(ManualTypeMarshallingAnalyzer.DLLIMPORTGENANALYZER018).WithSpan(21, 21, 21, 41).WithArguments("Native"),

Actual diagnostic:
// error AD0001: Analyzer 'Microsoft.Interop.Analyzers.ManualTypeMarshallingAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: TestProject

System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.MetadataHelpers.GetInfoForImmediateNamespaceMembers(Boolean isGlobalNamespace, Int32 namespaceNameLength, IEnumerable1 typesByNS, StringComparer nameComparer, IEnumerable1& types, IEnumerable1& namespaces) at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamespaceSymbol.LoadAllMembers(IEnumerable1 typesByNS)
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENestedNamespaceSymbol.EnsureAllMembersLoaded()
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamespaceSymbol.GetMembers(String name)
at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.LookupNestedNamespace(ImmutableArray1 names) at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingModuleSymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName) at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(MetadataTypeName& emittedName, ConsList1 visitedAssemblies, Boolean digThroughForwardedTypes)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(AssemblySymbol assembly, MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt, Boolean includeReferences, Boolean isWellKnownType, ValueTuple2& conflicts, DiagnosticBag warnings, Boolean ignoreCorLibraryDuplicatedTypes) at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTypeByMetadataName(String metadataName, Boolean includeReferences, Boolean isWellKnownType, ValueTuple2& conflicts, Boolean useCLSCompliantNameArityEncoding, DiagnosticBag warnings, Boolean ignoreCorLibraryDuplicatedTypes)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetTypeByMetadataName(String metadataName)
at Microsoft.Interop.Analyzers.ManualTypeMarshallingAnalyzer.PrepareForAnalysis(CompilationStartAnalysisContext context) in /_/src/libraries/System.Runtime.InteropServices/gen/DllImportGenerator/Analyzers/ManualTypeMarshallingAnalyzer.cs:line 208
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationStartActions>b__44_0(ValueTuple2 data) at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action1 analyze, TArg argument, Nullable`1 info)
Suppress the following diagnostics to disable this analyzer: DLLIMPORTGENANALYZER001, DLLIMPORTGENANALYZER002, DLLIMPORTGENANALYZER003, DLLIMPORTGENANALYZER004, DLLIMPORTGENANALYZER005, DLLIMPORTGENANALYZER006, DLLIMPORTGENANALYZER007, DLLIMPORTGENANALYZER008, DLLIMPORTGENANALYZER009, DLLIMPORTGENANALYZER010, DLLIMPORTGENANALYZER011, DLLIMPORTGENANALYZER012, DLLIMPORTGENANALYZER014, DLLIMPORTGENANALYZER016, DLLIMPORTGENANALYZER018
DiagnosticResult.CompilerError("AD0001").WithArguments("Microsoft.Interop.Analyzers.ManualTypeMarshallingAnalyzer", "System.NullReferenceException", "Object reference not set to an instance of an object.", "Exception occurred with following context:
Compilation: TestProject

System.NullRefer


Stack trace
   at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.True(Boolean assert, String message) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 62
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticLocation(ImmutableArray`1 analyzers, Diagnostic diagnostic, DiagnosticResult expectedDiagnostic, Location actual, DiagnosticLocation expected, IVerifier verifier) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 717
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticResults(IEnumerable`1 actualResults, ImmutableArray`1 analyzers, DiagnosticResult[] expectedResults, IVerifier verifier) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 373
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 272
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunImplAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 264
   at DllImportGenerator.UnitTests.Verifiers.CSharpCodeFixVerifier`2.Test.RunImplAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Verifiers/CSharpCodeFixVerifier.cs:line 131
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 180
   at DllImportGenerator.UnitTests.Verifiers.CSharpAnalyzerVerifier`1.VerifyAnalyzerAsync(String source, DiagnosticResult[] expected) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Verifiers/CSharpAnalyzerVerifier.cs:line 38
   at DllImportGenerator.UnitTests.ManualTypeMarshallingAnalyzerTests.NativeTypeWithGetPinnableReferenceNoValueProperty_ReportsDiagnostic() in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/ManualTypeMarshallingAnalyzerTests.cs:line 674
--- End of stack trace from previous location ---
```

**Comment by AaronRobinsonMSFT** [comment]
This was fixed with our updated Roslyn SDK.
