### ISSUE TITLE
Test failure JIT\\Directed\\LoopAlignment\\LoopsToProcess\\LoopsToProcess.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62260]
Run: [runtime-coreclr outerloop 20211201.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1492640&view=ms.vss-test-web.build-test-results-tab&runId=42647828&resultId=108356&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\Directed\\LoopAlignment\\LoopsToProcess\\LoopsToProcess.cmd

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open
- JIT\\Directed\\LoopAlignment\\LoopsToProcess\\LoopsToProcess.cmd

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Directed\\LoopAlignment\\LoopsToProcess\\LoopsToProcess.cmd

R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\Directed\\LoopAlignment\\LoopsToProcess\\LoopsToProcess.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Directed\\LoopAlignment\\LoopsToProcess\\LoopsToProcess.cmd

CoreCLR OSX arm64 Checked @ OSX.1100.ARM64.Open
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

CoreCLR Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

```
**Error message:**
```
Could Not Find D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.dll.rsp

Return code:      1
Raw output file:      D:\h\w\A8560913\w\A0F50948\uploads\Reports\JIT.Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.output.txt
Raw output:
BEGIN EXECUTION
LoopsToProcess.dll
1 file(s) copied.
Response file: D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.dll.rsp
D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\IL-CG2\LoopsToProcess.dll
-o:D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A8560913\p\System..dll
-r:D:\h\w\A8560913\p\Microsoft..dll
-r:D:\h\w\A8560913\p\mscorlib.dll
-r:D:\h\w\A8560913\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A8560913\p\crossgen2\crossgen2.dll" @"D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.dll.rsp"   -r:D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.dll
"D:\h\w\A8560913\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  LoopsToProcess.dll
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A8560913\p
D:\h\w\A8560913\w\A0F50948\e\JIT\Directed\LoopAlignment\LoopsToProcess\LoopsToProcess.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._LoopAlignment_LoopsToProcess_LoopsToProcess_._LoopAlignment_LoopsToProcess_LoopsToProcess_cmd()
```
Failed test:
```
R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1014.Amd64.Open
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

CoreCLR OSX x64 Checked @ OSX.1014.Amd64.Open
- JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh: line 249: -r:/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.dll.rsp': No such file or directory

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/IL-CG2/LoopsToProcess.dll
Response file: /root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.dll.rsp
/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/IL-CG2/LoopsToProcess.dll
-o:/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.dll
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false LoopsToProcess.dll ''
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/Directed/LoopAlignment/LoopsToProcess/LoopsToProcess.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._LoopAlignment_LoopsToProcess_LoopsToProcess_._LoopAlignment_LoopsToProcess_LoopsToProcess_sh()
```

**Comment by kunalspathak** [comment]
Yes, I missed returning `100` from the test. I will send out the fix.
