### ISSUE TITLE
Deadlock due to managed code execution while holding the loader lock

### ISSUE THREAD

**Issue by BrzVlad** [dotnet/runtime#62419]
Here is the stack trace for the thread holding the loader lock. The lock is acquired in `mono_class_create_from_typedef`.
```
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f040403a27c) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f0404203240, cond=0x7f040403a250) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f040403a250, mutex=0x7f0404203240) at pthread_cond_wait.c:638
#3  0x00007f0448a9f449 in mono_os_cond_wait (cond=0x7f040403a250, mutex=0x7f0404203240)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/../../mono/utils/mono-os-mutex.h:219
#4  mono_coop_cond_wait (cond=<optimized out>, mutex=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/../../mono/utils/mono-coop-mutex.h:91
#5  mono_monitor_try_enter_inflated (obj=0x7f043cd54590, ms=4294967295, allow_interruption=1, id=74)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/monitor.c:889
#6  0x00007f0448a9e332 in mono_monitor_try_enter_internal (obj=<optimized out>, ms=<optimized out>, allow_interruption=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/monitor.c:467
#7  0x00007f0448a9df89 in mono_monitor_try_enter_loop_if_interrupted (obj=0x7f043cd54590, ms=4294967295, allow_interruption=<optimized out>, 
    lockTaken=0x7f041fa00900 "", error=<optimized out>) at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/monitor.c:1153
#8  0x00007f0448a3129c in ves_icall_System_Threading_Monitor_Monitor_try_enter_with_atomic_var_raw (a0=0x7f041fa00980, a1=4294967295, a2=1 '\001', 
    a3=0x7f041fa00900 "") at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/icall-def-netcore.h:471
#9  0x00007f0448c3be03 in do_icall (sig=0x5582f3c5f2a8, op=<optimized out>, ret_sp=0x7f041fa009a0, sp=0x7f041fa009a8, 
    ptr=0x7f0448a31240 <ves_icall_System_Threading_Monitor_Monitor_try_enter_with_atomic_var_raw>, save_last_error=0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:2157
#10 0x00007f0448c3af55 in do_icall_wrapper (frame=0x7f041fffa210, sig=0x5582f3c5f2a8, op=557, ret_sp=0x7f041fa009a0, sp=0x7f041fa009a8, 
    ptr=0x7f0448a31240 <ves_icall_System_Threading_Monitor_Monitor_try_enter_with_atomic_var_raw>, save_last_error=0, gc_transitions=0x7f041fffa3e4)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:2219
#11 0x00007f0448c2cd98 in interp_exec_method (frame=<optimized out>, context=<optimized out>, clause_args=0x0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:3600
#12 0x00007f0448c2af54 in interp_runtime_invoke (method=<optimized out>, obj=0x0, params=0x7f041fffa5d0, exc=<optimized out>, error=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:1977
#13 0x00007f0448a60cad in do_runtime_invoke (method=0x7f0418475f08, obj=0x0, params=0x7f041fffa5d0, exc=0x7f041fffa590, error=0x7f041fffa620)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2395
#14 mono_runtime_try_invoke (method=0x7f0418475f08, obj=0x0, params=0x7f041fffa5d0, exc=0x7f041fffa590, error=0x7f041fffa620)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2504
#15 0x00007f0448a62f76 in mono_runtime_try_invoke_handle (method=0x7f040403a27c, obj=..., params=0x0, error=0x7f041fffa620)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2512
#16 0x00007f0448a979c6 in invoke_resolve_method (resolve_method=0x7f0418475f08, alc=0x7f04151fcf10, aname=<optimized out>, error=0x7f041fffa620)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/assembly-load-context.c:470
#17 0x00007f0448a9720d in mono_alc_invoke_resolve_using_load (alc=<optimized out>, aname=<optimized out>, error=0x7f041fffa620)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/assembly-load-context.c:496
#18 mono_alc_invoke_resolve_using_load_nofail (alc=0x7f04151fcf10, aname=0x7f041fffa810)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/assembly-load-context.c:505
#19 0x00007f04489f899d in netcore_load_reference (aname=0x7f041fffa810, alc=0x7f04151fcf10, requesting=0x7f04151f9810, postload=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/assembly.c:1015
#20 mono_assembly_request_byname (aname=<optimized out>, req=<optimized out>, status=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/assembly.c:2985
#21 0x00007f04489f85c0 in mono_assembly_load_reference (image=0x7f0415201ce0, index=0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/assembly.c:1219
#22 0x00007f04489fd595 in mono_class_from_typeref_checked (image=0x7f0415201ce0, type_token=16777225, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/class.c:200
#23 0x00007f0448a018d8 in mono_class_get_checked (image=0x7f0415201ce0, type_token=16777225, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/class.c:2875

#24 0x00007f0448a09d9b in mono_class_create_from_typedef (image=0x7f0415201ce0, type_token=33554437, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/class-init.c:502
#25 0x00007f0448a0186c in mono_class_get_checked (image=0x7f0415201ce0, type_token=33554437, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/class.c:2872
#26 0x00007f0448a02476 in mono_class_from_name_checked_aux (image=0x7f0415201ce0, name_space=0x7f0448d0689d "", name=<optimized out>, 
    visited_images=0x7f0415202740, case_sensitive=1, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/class.c:3394
#27 0x00007f04489fd835 in mono_class_from_name_checked (image=0x7f040403a27c, name_space=0x80 <error: Cannot access memory at address 0x80>, 
    name=0x0, error=0x4) at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/class.c:3420
#28 0x00007f0448a8241c in mono_reflection_get_type_internal (alc=0x5582f3b028a0, rootimage=0x7f0415201ce0, image=0x7f0415201ce0, 
    info=0x7f041fffb1b8, ignorecase=0, search_mscorlib=0, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/reflection.c:2029
#29 0x00007f0448a7fca4 in mono_reflection_get_type_with_rootimage (alc=0x5582f3b028a0, rootimage=0x7f0415201ce0, image=<optimized out>, 
    info=0x7f041fffb1b8, ignorecase=0, search_mscorlib=0, type_resolve=0x7f041fffb16c, error=0x7f041fffb328)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/reflection.c:2273
#30 0x00007f0448a7fee0 in mono_reflection_get_type_checked (alc=0x7f040403a27c, rootimage=0x80, image=0x0, 
    info=0x7f04493d2376 <__pthread_cond_wait+534>, ignorecase=0, search_mscorlib=4, type_resolve=0x7f041fffb328, error=0x7f0415201ce0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/reflection.c:2183
#31 0x00007f0448a23065 in ves_icall_System_Reflection_Assembly_InternalGetType (assembly_h=..., module=..., name=..., throwOnError=0 '\000', 
    ignoreCase=<optimized out>, error=0x7f041fffb328) at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/icall.c:4406
#32 0x00007f0448a2a777 in ves_icall_System_Reflection_Assembly_InternalGetType_raw (a0=0x7f041fa00690, a1=0x7f041fa00698, a2=0x7f041fa006a0, 
    a3=0 '\000', a4=0 '\000') at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/icall-def-netcore.h:176
#33 0x00007f0448c3bced in do_icall (sig=0x5582f4bdc4b0, op=<optimized out>, ret_sp=0x7f041fa006b8, sp=0x7f041fa006c0, 
    ptr=0x7f0448a2a710 <ves_icall_System_Reflection_Assembly_InternalGetType_raw>, save_last_error=0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:2175
#34 0x00007f0448c3af55 in do_icall_wrapper (frame=0x7f041fffcc80, sig=0x5582f4bdc4b0, op=560, ret_sp=0x7f041fa006b8, sp=0x7f041fa006c0, 
    ptr=0x7f0448a2a710 <ves_icall_System_Reflection_Assembly_InternalGetType_raw>, save_last_error=0, gc_transitions=0x7f041fffcfd4)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:2219
#35 0x00007f0448c2cd98 in interp_exec_method (frame=<optimized out>, context=<optimized out>, clause_args=0x0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:3600
#36 0x00007f0448c2af54 in interp_runtime_invoke (method=<optimized out>, obj=0x7f0447f26868, params=0x7f041fffd170, exc=<optimized out>, 
    error=<optimized out>) at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:1977
#37 0x00007f0448a5f188 in do_runtime_invoke (method=0x7f04341751d0, obj=0x7f0447f26868, params=0x7f041fffd170, exc=0x0, error=0x7f041fffd2b8)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2395
#38 mono_runtime_invoke_checked (method=0x7f04341751d0, obj=0x7f0447f26868, params=0x7f041fffd170, error=0x7f041fffd2b8)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2563
#39 0x00007f0448a674ec in mono_runtime_try_invoke_span (method=0x7f04341751d0, obj=0x80, params_span=0x7f041f9ffd40, exc=0x0, error=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:4772
#40 0x00007f0448a66ebd in mono_runtime_invoke_span_checked (method=0x7f040403a27c, obj=0x80, params=0x0, error=0x0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:4863
#41 0x00007f0448a20d52 in ves_icall_InternalInvoke (method_handle=..., this_arg_handle=..., params_span=0x0, exception_out=..., 
    error=0x7f04493d2376 <__pthread_cond_wait+534>) at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/icall.c:3480
#42 0x00007f0448a2c1fb in ves_icall_InternalInvoke_raw (a0=0x7f041f9ffd90, a1=0x7f041f9ffd98, a2=0x7f041f9ffd40, a3=0x7f041f9ffdb0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/icall-def-netcore.h:255
#43 0x00007f0448c3bd3f in do_icall (sig=0x5582f4a75d30, op=<optimized out>, ret_sp=0x7f041f9ffdb8, sp=0x7f041f9ffdc8, 
    ptr=0x7f0448a2c1a0 <ves_icall_InternalInvoke_raw>, save_last_error=0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:2163
#44 0x00007f0448c3af55 in do_icall_wrapper (frame=0x7f041fffdb90, sig=0x5582f4a75d30, op=558, ret_sp=0x7f041f9ffdb8, sp=0x7f041f9ffdc8, 
    ptr=0x7f0448a2c1a0 <ves_icall_InternalInvoke_raw>, save_last_error=0, gc_transitions=0x7f041fffecc4)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:2219
#45 0x00007f0448c2cd98 in interp_exec_method (frame=<optimized out>, context=<optimized out>, clause_args=0x0)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:3600
#46 0x00007f0448c2af54 in interp_runtime_invoke (method=<optimized out>, obj=0x7f0447fe0ef0, params=0x0, exc=<optimized out>, error=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/mini/interp/interp.c:1977
#47 0x00007f0448a5f188 in do_runtime_invoke (method=0x5582f4d66288, obj=0x7f0447fe0ef0, params=0x0, exc=0x0, error=0x7f041fffee68)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2395
#48 mono_runtime_invoke_checked (method=0x5582f4d66288, obj=0x7f0447fe0ef0, params=0x0, error=0x7f041fffee68)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/object.c:2563
#49 0x00007f0448a765e7 in start_wrapper_internal (start_info=0x0, stack_ptr=<optimized out>)
    at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/threads.c:1211
#50 0x00007f0448a763d9 in start_wrapper (data=0x5582f50ed080) at /home/vbrezae/Xamarin/repos/runtime2/src/mono/mono/metadata/threads.c:1262
#51 0x00007f04493cb609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#52 0x00007f0448fa0293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Although it is rather irrelevant, here this is what the managed code is doing.
```
(wrapper managed-to-native) System.Threading.Monitor:try_enter_with_atomic_var (object,int,bool,bool&)
System.Threading.Monitor:ReliableEnterTimeout (object,int,bool&)
System.Threading.Monitor:Enter (object,bool&)
System.Globalization.CultureInfo:GetCultureInfo (string)
System.Reflection.AssemblyName:FillName (Mono.MonoAssemblyName*,string,bool,bool,bool)
System.Reflection.AssemblyName:.ctor (string)
System.Runtime.Loader.AssemblyLoadContext:MonoResolveUsingLoad (intptr,string)
(wrapper runtime-invoke) <Module>:runtime_invoke_direct_Assembly_intptr_string (object,intptr,intptr,intptr)
```

The hang reproduces intermittently when running the `System.Text.RegularExpressions.Tests` in Release mode with interpreter. It probably reproduces in other configurations also

**Comment by BrzVlad** [comment]
@lambdageek Any comments on this ?

**Comment by stephentoub** [comment]
@BrzVlad, I assume this is the issue I pinged you about? Thanks for following up.

**Comment by lambdageek** [comment]
I need to stare at the stack trace in a bit more detail, but it is likely the same underlying issue as https://github.com/dotnet/runtime/issues/51864: our current setup makes it possible to run managed code (assembly loader managed callbacks) while holding the global loader lock.  Avoiding doing so [is hard](https://github.com/dotnet/runtime/issues/51864#issuecomment-953977929)

**Comment by BrzVlad** [comment]
Looks like we should close this issue as duplicate then.

**Comment by lambdageek** [comment]
Duplicate of #51864
