### ISSUE TITLE
Test failure DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Standard, expectFallbackForwarder: False)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62467]
Run: [runtime 20211206.59](https://dev.azure.com/dnceng/public/_build/results?buildId=1499304&view=ms.vss-test-web.build-test-results-tab&runId=42764382&paneView=debug&resultId=123473)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_checked-OSX.1014.Amd64.Open

- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(targetFramework: Net5)
- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(targetFramework: Standard)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Standard, expectFallbackForwarder: True)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Net5, expectFallbackForwarder: True)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Standard, expectFallbackForwarder: False)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Net5, expectFallbackForwarder: False)
- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoDiagnostic(targetFramework: Net5)
- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoDiagnostic(targetFramework: Standard)
```
**Error message:**
```
Assert.All() Failure: 5 out of 9 items in the collection did not pass.
[7]: Item: (3,15): error CS1729: 'object' does not contain a constructor that takes 0 arguments
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS1729"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[6]: Item: (5,16): error CS0518: Predefined type 'System.String' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[3]: Item: (5,6): error CS0518: Predefined type 'System.Object' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[2]: Item: (6,26): error CS0518: Predefined type 'System.Void' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[1]: Item: (3,15): error CS0518: Predefined type 'System.Object' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 36


Stack trace
   at DllImportGenerator.UnitTests.TestUtils.AssertPreSourceGeneratorCompilation(Compilation comp) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 73
   at DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(TestTargetFramework targetFramework) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Diagnostics.cs:line 61
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in: [runtime 20211221.38](https://dev.azure.com/dnceng/public/_build/results?buildId=1523071&view=ms.vss-test-web.build-test-results-tab&runId=43267200&paneView=debug&resultId=144948)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_checked-OSX.1014.Amd64.Open

- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(targetFramework: Core)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Core, expectFallbackForwarder: True)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Core, expectFallbackForwarder: False)
- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoDiagnostic(targetFramework: Core)

```
**Error message:**
```
Assert.All() Failure: 5 out of 9 items in the collection did not pass.
[7]: Item: (3,15): error CS1729: 'object' does not contain a constructor that takes 0 arguments
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS1729"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[6]: Item: (5,16): error CS0518: Predefined type 'System.String' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[3]: Item: (5,6): error CS0518: Predefined type 'System.Object' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[2]: Item: (6,26): error CS0518: Predefined type 'System.Void' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[1]: Item: (3,15): error CS0518: Predefined type 'System.Object' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 36


Stack trace
   at DllImportGenerator.UnitTests.TestUtils.AssertPreSourceGeneratorCompilation(Compilation comp) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 73
   at DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(TestTargetFramework targetFramework) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Diagnostics.cs:line 61
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in: [runtime 20220105.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1536553&view=ms.vss-test-web.build-test-results-tab&runId=43503028&resultId=129380&paneView=debug)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_checked-OSX.1014.Amd64.Open

- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(targetFramework: Core)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Core, expectFallbackForwarder: True)
- DllImportGenerator.UnitTests.Compiles.ValidateSnippetsFallbackForwarder(source: \"\\nusing System.Runtime.InteropServices;\\n\\nnamespa\"..., targetFramework: Core, expectFallbackForwarder: False)
- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoDiagnostic(targetFramework: Core)
```
**Error message:**
```
Assert.All() Failure: 5 out of 9 items in the collection did not pass.
[7]: Item: (3,15): error CS1729: 'object' does not contain a constructor that takes 0 arguments
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS1729"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[6]: Item: (5,16): error CS0518: Predefined type 'System.String' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[3]: Item: (5,6): error CS0518: Predefined type 'System.Object' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[2]: Item: (6,26): error CS0518: Predefined type 'System.Void' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in //src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
[1]: Item: (3,15): error CS0518: Predefined type 'System.Object' is not defined or imported
Xunit.Sdk.SubsetException: Assert.Subset() Failure
Expected: HashSet<String> ["CS8795", "CS0234", "CS0246", "CS8019"]
Actual:   HashSet<String> ["CS0518"]
at Xunit.Assert.Subset[T](ISet1 expectedSuperset, ISet1 actual) in //src/xunit.assert/Asserts/SetAsserts.cs:line 55
at DllImportGenerator.UnitTests.TestUtils.<>c__DisplayClass0_0.<AssertPreSourceGeneratorCompilation>b__0(Diagnostic diag) in //src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 75
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 36


Stack trace
   at DllImportGenerator.UnitTests.TestUtils.AssertPreSourceGeneratorCompilation(Compilation comp) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 73
   at DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(TestTargetFramework targetFramework) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Diagnostics.cs:line 61
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220212.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1610130&view=ms.vss-test-web.build-test-results-tab&runId=44858352&paneView=debug&resultId=155241)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

- DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(targetFramework: Framework)

```
**Error message:**
```
NuGet.Protocol.Core.Types.FatalProtocolException : Error downloading 'Microsoft.NETFramework.ReferenceAssemblies.net48.1.0.2' from 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/microsoft.netframework.referenceassemblies.net48/1.0.2/microsoft.netframework.referenceassemblies.net48.1.0.2.nupkg'.
---- System.Net.Http.HttpRequestException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (5dkvsblobprodcus355.vsblob.vsassets.io:443)
-------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.


Stack trace
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at NuGet.Protocol.DownloadResourceV3.GetDownloadResourceResultAsync(PackageIdentity identity, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 323
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 197
   at DllImportGenerator.UnitTests.TestUtils.ResolveReferenceAssemblies(ReferenceAssemblies referenceAssemblies) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 230
   at DllImportGenerator.UnitTests.TestUtils.GetReferenceAssemblies(TestTargetFramework targetFramework) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 168
   at DllImportGenerator.UnitTests.TestUtils.CreateCompilation(SyntaxTree[] sources, TestTargetFramework targetFramework, OutputKind outputKind) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/TestUtils.cs:line 126
   at DllImportGenerator.UnitTests.Diagnostics.TargetFrameworkNotSupported_NoGeneratedDllImport_NoDiagnostic(TestTargetFramework targetFramework) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Diagnostics.cs:line 60
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1436
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1349
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1444
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 454
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs:line 0
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 548
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1002
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs:line 240
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 81
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs:line 69
   at NuGet.Protocol.ServerWarningLogHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 532
   at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass2_1.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Protocol.TimeoutUtility.StartWithTimeout[T](Func`2 getTask, TimeSpan timeout, String timeoutMessage, CancellationToken token)
   at NuGet.Protocol.HttpRetryHandler.SendAsync(HttpRetryHandlerRequest request, String source, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
   at NuGet.Protocol.HttpSource.ProcessResponseAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.HttpSource.ProcessStreamAsync[T](HttpSourceRequest request, Func`2 processAsync, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.GetDownloadResultUtility.GetDownloadResultAsync(HttpSource client, PackageIdentity identity, Uri uri, PackageDownloadContext downloadContext, String globalPackagesFolder, ILogger logger, CancellationToken token)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1372
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|278_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 118
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1418
```
