### ISSUE TITLE
[wasm][windows][aot] `emcc` fails to download `zlib` on rolling build, causing tests to fail

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#62553]
Seen on rolling [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1503552&view=logs&j=c24b3bf0-34d4-58dc-62fd-621ef62beaf8&t=57689805-9064-5d56-984a-6ae89a8efb73), [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ff20adda136e4c69b4/System.Xml.XPath.Tests/1/console.3d1621c9.log?sv=2019-07-07&se=2021-12-28T20%3A23%3A21Z&sr=c&sp=rl&sig=rjU4LyO5x0rmYPLs%2BPPZi12prhJ2Kh%2FS6YtPuPHrQJw%3D) for `System.Xml.XPath.Tests`:

```
Failed to compile C:\helix\work\correlation\build\microsoft.netcore.app.runtime.browser-wasm\runtimes\browser-wasm\native\src\driver.c -> C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\driver.o [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>setlocal [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>set errorlevel=dummy  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>set errorlevel=  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>emcc "@C:\helix\work\correlation\build\microsoft.netcore.app.runtime.browser-wasm\runtimes\browser-wasm\native\src\emcc-default.rsp" "@C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\emcc-compile.rsp" -c -o "C:\Users\ContainerAdministrator\AppData\Local\Temp\tmp43A.tmp" "C:\helix\work\correlation\build\microsoft.netcore.app.runtime.browser-wasm\runtimes\browser-wasm\native\src\driver.c"  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
system_libs:INFO: retrieving port: zlib from https://github.com/madler/zlib/archive/v1.2.11.zip [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
Traceback (most recent call last): [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\tools\system_libs.py", line 1754, in retrieve [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    import requests [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
ModuleNotFoundError: No module named 'requests' [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
During handling of the above exception, another exception occurred: [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
Traceback (most recent call last): [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 1346, in do_open [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    h.request(req.get_method(), req.selector, req.data, headers, [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 1257, in request [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    self._send_request(method, url, body, headers, encode_chunked) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 1303, in _send_request [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    self.endheaders(body, encode_chunked=encode_chunked) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 1252, in endheaders [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    self._send_output(message_body, encode_chunked=encode_chunked) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 1012, in _send_output [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    self.send(msg) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 952, in send [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    self.connect() [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 1419, in connect [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    super().connect() [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\http\client.py", line 923, in connect [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    self.sock = self._create_connection( [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\socket.py", line 822, in create_connection [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    for res in getaddrinfo(host, port, 0, SOCK_STREAM): [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\socket.py", line 953, in getaddrinfo [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags): [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
socket.gaierror: [Errno 11002] getaddrinfo failed [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
During handling of the above exception, another exception occurred: [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
Traceback (most recent call last): [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 3731, in <module> [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    sys.exit(main(sys.argv)) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 3724, in main [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    ret = run(args) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 1080, in run [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\contextlib.py", line 79, in inner [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    return func(*args, **kwds) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 2412, in phase_compile_inputs [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    compile_source_file(i, input_file) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 2400, in compile_source_file [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    cmd = get_clang_command(input_file) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 2341, in get_clang_command [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    return get_compiler(use_cxx(src_file)) + get_cflags(options, state.orig_args) + compile_args + [src_file] [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\emcc.py", line 896, in get_cflags [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    system_libs.add_ports_cflags(cflags, settings) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\tools\system_libs.py", line 1905, in add_ports_cflags [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    port.get(Ports, settings, shared) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\tools\ports\zlib.py", line 18, in get [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    ports.fetch_project('zlib', 'https://github.com/madler/zlib/archive/v' + TAG + '.zip', 'zlib-' + TAG, sha512hash=HASH) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\tools\system_libs.py", line 1803, in fetch_project [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    retrieve() [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\helix\work\correlation\build\emsdk\upstream\emscripten\tools\system_libs.py", line 1759, in retrieve [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    f = urlopen(url) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 214, in urlopen [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    return opener.open(url, data, timeout) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 523, in open [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    response = meth(req, response) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 632, in http_response [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    response = self.parent.error( [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 555, in error [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    result = self._call_chain(*args) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 494, in _call_chain [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    result = func(*args) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 747, in http_error_302 [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    return self.parent.open(new, timeout=req.timeout) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 517, in open [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    response = self._open(req, data) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 534, in _open [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    result = self._call_chain(self.handle_open, protocol, protocol + [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 494, in _call_chain [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    result = func(*args) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 1389, in https_open [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    return self.do_open(http.client.HTTPSConnection, req, [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
  File "C:\Python\Lib\urllib\request.py", line 1349, in do_open [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
    raise URLError(err) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed> [took 11.81s] [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
```

We have hit this more than once now.

|Build|Kind|Start Time|
|---|---|---|
[1583876](https://dev.azure.com/dnceng/public/_build/results?buildId=1583876)|Rolling|2022-01-02|

**Comment by radical** [comment]
```
system_libs:INFO: retrieving port: zlib from https://github.com/madler/zlib/archive/v1.2.11.zip
...
ModuleNotFoundError: No module named 'requests'
...
socket.gaierror: [Errno 11002] getaddrinfo failed
...
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>
```

**Comment by radical** [comment]
Another instance on a rolling build: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ff20adda136e4c69b4/System.Xml.XPath.Tests/1/console.3d1621c9.log?sv=2019-07-07&se=2021-12-28T20%3A23%3A21Z&sr=c&sp=rl&sig=rjU4LyO5x0rmYPLs%2BPPZi12prhJ2Kh%2FS6YtPuPHrQJw%3D

@radekdoulik do these look like just intermittent issues, and can we do anything about them?

**Comment by radical** [comment]
Another on a rolling build: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8069f6100ee24c59a2/System.IO.UnmanagedMemoryStream.Tests/1/console.d471626b.log?sv=2019-07-07&se=2022-01-02T20%3A27%3A01Z&sr=c&sp=rl&sig=3AQKrWlBJxlpPZmXKGpnMyUZbMDZHvV2AWh2lXielw0%3D

**Comment by lewing** [comment]
we could try to get the build working using our packages rather than provisioning emsdk

**Comment by sbomer** [comment]
Another instance in today's rolling [build](https://runfo.azurewebsites.net/view/build/?number=1583876), looks like https://github.com/emscripten-core/emscripten/issues/16164.
