### ISSUE TITLE
[Android][x86] System.Security.Cryptography.CryptographicException : The X509 certificate store is read-only.

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#62713]
```
<test name="System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.RemoveReadOnlyNonExistingDoesNotThrow" type="System.Security.Cryptography.X509Certificates.Tests.X509StoreTests" method="RemoveReadOnlyNonExistingDoesNotThrow" time="0.0594677" result="Fail">
    <failure exception-type="System.Security.Cryptography.CryptographicException">
        <message><![CDATA[System.Security.Cryptography.CryptographicException : The X509 certificate store is read-only.]]></message>
        <stack-trace><![CDATA[   at Internal.Cryptography.Pal.StorePal.AndroidKeyStore.Remove(ICertificatePal cert)
    at System.Security.Cryptography.X509Certificates.X509Store.Remove(X509Certificate2 certificate)
    at System.Security.Cryptography.X509Certificates.Tests.X509StoreTests.RemoveReadOnlyNonExistingDoesNotThrow() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/X509StoreTests.cs:line 317
    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
    </failure>
</test>
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1509675&view=ms.vss-test-web.build-test-results-tab&runId=42989874&resultId=152135&paneView=debug

cc @steveisok @akoeplinger

**Comment by vcsjones** [comment]
Hm. I cannot reproduce this. I wonder if the certificate we are testing with is somehow getting added to the store.

The code clearly attempts to handle this condition.

https://github.com/dotnet/runtime/blob/ca5bb9318a13c3710aed44067e93785133ddd7df/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/StorePal.Android.AndroidKeyStore.cs#L84-L89

I wonder if we happened upon another test that added this to the store while we were running this test, `X509StoreMutableTests` or something.

**Comment by akoeplinger** [comment]
@vcsjones `X509StoreMutableTests` is marked as `OuterLoop` so it isn't running by default.

**Comment by akoeplinger** [comment]
We can certainly try reenabling the test and see if we see the failure again.

**Comment by vcsjones** [comment]
> X509StoreMutableTests is marked as OuterLoop so it isn't running by default.

Good point, just a bad example. Maybe another test does, maybe somewhere in networking tests...

> We can certainly try reenabling the test and see if we see the failure again.

I'll give that a try. If it passes, I'll change the test to use a unique certificate that any other test won't be using.
