### ISSUE TITLE
PeriodicTimer_ActiveOperations_TimerRooted  failure on Debian 10

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#62809]
PeriodicTimer_ActiveOperations_TimerRooted 
```
    System.Threading.Tests.PeriodicTimerTests.PeriodicTimer_ActiveOperations_TimerRooted [FAIL]
      Assert.Equal() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/System.Runtime/tests/System/Threading/PeriodicTimerTests.cs(202,0): at System.Threading.Tests.PeriodicTimerTests.WaitForTimerToBeCollected(WeakReference`1 timer, Boolean expected)
        /_/src/libraries/System.Runtime/tests/System/Threading/PeriodicTimerTests.cs(117,0): at System.Threading.Tests.PeriodicTimerTests.PeriodicTimer_ActiveOperations_TimerRooted()
        --- End of stack trace from previous location ---
  Finished:    System.Runtime.Tests
```
this spins for 0.5 sec, maybe it should have a little more time? (Assuming it's merely timing issue)
https://github.com/danmoseley/runtime/blob/2879e6ca886eb084335ccd0a579019fbe359628e/src/libraries/System.Runtime/tests/System/Threading/PeriodicTimerTests.cs#L206

**Comment by elinor-fung** [comment]
Dupe of https://github.com/dotnet/runtime/issues/59542?

**Comment by danmoseley** [comment]
yes dupe
