### ISSUE TITLE
Test failure System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtripUseOAEP

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62827]
Run: [runtime 20211214.76](https://dev.azure.com/dnceng/public/_build/results?buildId=1512867&view=ms.vss-test-web.build-test-results-tab&runId=43066030&resultId=169168&paneView=debug)
Failed test：
```
net7.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

- System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtripUseOAEP
```
**Error message:**
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Unknown error (0xc0000001)


Stack trace
   at System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(SafeNCryptKeyHandle key, ReadOnlySpan`1 input, AsymmetricPaddingMode paddingMode, Void* paddingInfo, Boolean encrypt) in /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.EncryptDecrypt.cs:line 260
   at System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(Byte[] data, RSAEncryptionPadding padding, Boolean encrypt) in /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.EncryptDecrypt.cs:line 118
   at System.Security.Cryptography.RSAImplementation.RSACng.Decrypt(Byte[] data, RSAEncryptionPadding padding) in /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.EncryptDecrypt.cs:line 29
   at System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter.DecryptKeyExchange(Byte[] rgbData) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSAOAEPKeyExchangeDeformatter.cs:line 30
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptKey(Byte[] keyData, RSA rsa, Boolean useOAEP) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs:line 946
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs:line 372
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs:line 657
   at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.Decrypt(XmlDocument doc, RSA rsaKey, String keyName) in /_/src/libraries/System.Security.Cryptography.Xml/tests/Samples/EncryptingDecryptingAsymmetric.cs:line 77
   at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtrip_Helper(Boolean useOAEP) in /_/src/libraries/System.Security.Cryptography.Xml/tests/Samples/EncryptingDecryptingAsymmetric.cs:line 105
   at System.Security.Cryptography.Xml.Tests.EncryptingAndDecryptingAsymmetric.AsymmetricEncryptionRoundtripUseOAEP() in /_/src/libraries/System.Security.Cryptography.Xml/tests/Samples/EncryptingDecryptingAsymmetric.cs:line 82
```

**Comment by vcsjones** [comment]
Duplicate of #29683
