### ISSUE TITLE
[wasm] debuger test failures on CI

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#62964]
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62292-merge-7343b975997548bbbb/DebuggerTests.ExceptionTests/1/console.b63ea3d2.log?sv=2019-07-07&se=2022-01-06T18%3A24%3A33Z&sr=c&sp=rl&sig=U0DvKF81B8WGLbJfPe%2Fxbj%2FgNUEgkyNgP0vTerw6NFM%3D)
```
[xUnit.net 00:00:19.12]     DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [FAIL]
[18:47:01] dbug: Microsoft.WebAssembly.Diagnostics.InspectorClient[0] connecting to ws://localhost:9400/launch-chrome-and-connect
[18:47:01] info: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] New test request
  Failed DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [1 s]
  Error Message:
   System.Net.WebSockets.WebSocketException : The remote party closed the WebSocket connection without completing the close handshake.
  Stack Trace:
     at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
--- End of stack trace from previous location ---
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.ReadOne(CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 84
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.RunLoop(Func`3 receive, CancellationTokenSource linkedCts) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 209
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.<>c__DisplayClass16_0.<<ConnectWithMainLoops>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 139
--- End of stack trace from previous location ---
   at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 490
   at DebuggerTests.DebuggerTestBase.EvaluateAndCheck(String expression, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 481
   at DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload() in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 214
--- End of stack trace from previous location ---
```

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62779-merge-21b8734785eb4f679e/DebuggerTests.HarnessTests/1/console.92c43f79.log?sv=2019-07-07&se=2022-01-06T16%3A05%3A10Z&sr=c&sp=rl&sig=WX5bbnVfLJZG7QzDvDafuI162IQsYk%2BCP6e12TfefjU%3D)
```
[xUnit.net 00:00:02.92]     DebuggerTests.HarnessTests.InspectorWaitForAfterMessageAlreadyReceived [FAIL]
[16:18:13] dbug: Microsoft.WebAssembly.Diagnostics.InspectorClient[0] connecting to ws://localhost:9400/launch-chrome-and-connect
  Failed DebuggerTests.HarnessTests.InspectorWaitForAfterMessageAlreadyReceived [1 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (The tasks argument included a null value. (Parameter 'tasks'))
---- System.ArgumentException : The tasks argument included a null value. (Parameter 'tasks')
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, Nullable`1 span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 240
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 137
----- Inner Stack Trace -----
   at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.RunLoop(Func`3 receive, CancellationTokenSource linkedCts) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 184
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.<>c__DisplayClass16_0.<<ConnectWithMainLoops>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 139
```

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62779-merge-24945395cf85457887/DebuggerTests.MonoJsTests/1/console.ebb2acf7.log?sv=2019-07-07&se=2022-01-06T18%3A00%3A15Z&sr=c&sp=rl&sig=cFW%2BFDbV%2BiZ0omPDHkgrwtF8dUWL0mbNOTSVy85ldfo%3D)
```
[xUnit.net 00:00:21.21]     DebuggerTests.MonoJsTests.DuplicateAssemblyLoadedEventNotLoadedFromBundle(load_pdb: True, expected_count: 1) [FAIL]
[18:16:14] info: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] New test request
  Failed DebuggerTests.MonoJsTests.DuplicateAssemblyLoadedEventNotLoadedFromBundle(load_pdb: True, expected_count: 1) [1 ms]
  Error Message:
   System.Net.WebSockets.WebSocketException : The server returned status code '200' when status code '101' was expected.
  Stack Trace:
     at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.ConnectWithMainLoops(Uri uri, Func`3 receive, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 125
   at Microsoft.WebAssembly.Diagnostics.InspectorClient.Connect(Uri uri, Func`4 onEvent, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 59
   at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, Nullable`1 span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 196
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 137
```

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62292-merge-17362eb3cae24549a9/DebuggerTests.BreakpointTests/1/console.523763da.log?sv=2019-07-07&se=2022-01-07T23%3A36%3A36Z&sr=c&sp=rl&sig=Zem2romyMxjEyjR0S0DbNLq%2BPccHYKrXxWnnmjb1zK8%3D)
```
[xUnit.net 00:01:01.89]     DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded [FAIL]
  Failed DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded [54 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 60.0209472)
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 497
   at DebuggerTests.DebuggerTestBase.EvaluateAndCheck(String expression, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 481
   at DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded() in /_/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:line 313
--- End of stack trace from previous location ---
```

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62292-merge-effc93d3be324c8493/DebuggerTests.SteppingTests/1/console.d8e23be5.log?sv=2019-07-07&se=2022-01-07T23%3A21%3A13Z&sr=c&sp=rl&sig=oWTT2Zkmnq7GR2BLgld8ooX0hGsbf05wCuZoWZRrgiw%3D)
```
[xUnit.net 00:01:31.18]     DebuggerTests.SteppingTests.CheckResetFrameNumberForEachStep [FAIL]
  Failed DebuggerTests.SteppingTests.CheckResetFrameNumberForEachStep [282 ms]
  Error Message:
   Assert.Equal() Failure
                                 ↓ (pos 46)
Expected: ···/debugger-test.cs#806#8
Actual:   ···/debugger-test.cs#802#8
                                 ↑ (pos 46)
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.CheckLocation(String script_loc, Int32 line, Int32 column, Dictionary`2 scripts, JToken location) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 250
   at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 505
   at DebuggerTests.DebuggerTestBase.StepAndCheck(StepKind kind, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, Int32 times) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 472
   at DebuggerTests.SteppingTests.CheckResetFrameNumberForEachStep() in /_/src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:line 963
--- End of stack trace from previous location ---
```

**Comment by steveisok** [comment]
It appears `HarnessTests.ExceptionThrown` is having the same problem

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1567435&view=ms.vss-test-web.build-test-results-tab)

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1dece6deca3540e3a6/DebuggerTests.HarnessTests/1/console.d5726c0b.log?sv=2019-07-07&se=2022-02-12T09%3A32%3A19Z&sr=c&sp=rl&sig=d56Ql2SiJd6aVeL24k1YKxSzJI7l7JyrRcyLv4vFstA%3D)

**Comment by thaystg** [comment]
I think this was fixed by @radical PR. We are not seeing these errors anymore.
If anyone disagrees please, reopen this issue.

**Comment by thaystg** [comment]
I reopened the issue to investigate @steveisok comment.
