### ISSUE TITLE
System.Data.Tests.AppDomainsAndFormatInfo.Bug55978 test failed

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#62965]
NodeJS on windows
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62779-merge-9dcf6f06b371400f98/System.Data.Common.Tests/1/console.63a00570.log?sv=2019-07-07&se=2022-01-06T18%3A25%3A38Z&sr=c&sp=rl&sig=vHDH2yfUEGXskQVSBw0kCXuVtLtnUVThqWE2%2FaqTPNI%3D)
```
[18:47:13] fail: [FAIL] System.Data.Tests.AppDomainsAndFormatInfo.Bug55978
[18:47:13] info: DataView.Rows.Count: Expected: 2, Actual: 3. Debug data: RowFilter: StartDate >= #12/19/2021 18:47:13# and StartDate <= #12/21/2021 18:47:13#, date: 12/17/2021 18:47:13
[18:47:13] info: row#0: '12/19/2021 18:47:13',
[18:47:13] info: row#1: '12/20/2021 18:47:13',
[18:47:13] info: row#2: '12/21/2021 18:47:13',
[18:47:13] info: 
[18:47:13] info: Expected: True
[18:47:13] info: Actual:   False
[18:47:13] info:    at System.Data.Tests.AppDomainsAndFormatInfo.Bug55978()
[18:47:13] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
[18:47:15] info: Finished:    System.Data.Common.Tests.dll
[18:47:15] info: 
[18:47:15] info: === TEST EXECUTION SUMMARY ===
[18:47:15] info: Total: 11692, Errors: 0, Failed: 1, Skipped: 10, Time: 30.5432452s
```

**Comment by pavelsavara** [comment]
Another occurence, this time on Android, not wasm
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62292-merge-3ff198bf8e7d4e47b3/System.Data.Common.Tests/1/test-ios-simulator-64-20211221_054002.log?sv=2019-07-07&se=2022-01-10T13%3A37%3A11Z&sr=c&sp=rl&sig=AqBWjtrcgYDdQdeJSYOa6KGiEYfmbRVk0pWnxnjARtw%3D)
```
 <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[DataView.Rows.Count: Expected: 2, Actual: 3. Debug data: RowFilter: StartDate >= #12/23/2021 05:40:27# and StartDate <= #12/25/2021 05:40:28#, date: 12/21/2021 05:40:27\nrow#0: '12/23/2021 05:40:27', \nrow#1: '12/24/2021 05:40:27', \nrow#2: '12/25/2021 05:40:27', \n\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at System.Data.Tests.AppDomainsAndFormatInfo.Bug55978()
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
        </failure>
```
