### ISSUE TITLE
Test failure Interop\\StringMarshalling\\VBByRefStr\\VBByRefStrTest\\VBByRefStrTest.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63003]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20211219.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1520317&view=ms.vss-test-web.build-test-results-tab&runId=43220080&paneView=debug&resultId=100703)

Failed test:
```
CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

- Interop\\StringMarshalling\\VBByRefStr\\VBByRefStrTest\\VBByRefStrTest.cmd

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open

- Interop\\StringMarshalling\\VBByRefStr\\VBByRefStrTest\\VBByRefStrTest.cmd

```
**Error message:**
```
Assert failure(PID 9812 [0x00002654], Thread: 9800 [0x2648]): !CREATE_CHECK_STRING(!GCHeapUtilities::GetGCHeap()->IsLargeObject(this))

CORECLR! Object::ValidateInner + 0x2BC (0x709acb6c)
CORECLR! Object::Validate + 0xAF (0x709ac86f)
CORECLR! WKS::GCHeap::Promote + 0x77 (0x70d2c577)
CORECLR! GcEnumObject + 0x57 (0x70ad2bb7)
CORECLR! EECodeManager::EnumGcRefs + 0xA04 (0x708e9974)
CORECLR! GcStackCrawlCallBack + 0x152 (0x70ad2e22)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x709e51e0)
CORECLR! Thread::StackWalkFramesEx + 0x186 (0x709e68d1)
CORECLR! Thread::StackWalkFrames + 0x159 (0x709e66cb)
CORECLR! ScanStackRoots + 0x196 (0x70ad20b6)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 550
Image: C:\h\w\A8E9093E\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A8E9093E\w\ABAD0933\uploads\Reports\Interop.StringMarshalling\VBByRefStr\VBByRefStrTest\VBByRefStrTest.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A8E9093E\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  VBByRefStrTest.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A8E9093E\p
C:\h\w\A8E9093E\w\ABAD0933\e\Interop\StringMarshalling\VBByRefStr\VBByRefStrTest\VBByRefStrTest.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_StringMarshalling._VBByRefStr_VBByRefStrTest_VBByRefStrTest_._VBByRefStr_VBByRefStrTest_VBByRefStrTest_cmd()
```

**Comment by AaronRobinsonMSFT** [comment]
@AndyAyersMS @janvorli - This is exclusively on Windows x86 and all of them seem to involve inlined P/Invokes. The test source is below. The issue is the instance of the compiler generated class for the closure on line 33 is being invalidated during the first P/Invoke call on line 24. Commenting out line 33 allows the test to pass as does removing all P/Invokes prior to line 33. I have attached a [JITDump](https://github.com/dotnet/runtime/files/7804302/main_jitdump.txt) of `Main` and that seems correct &ndash; the compiler generated instance is in `ESI` and that is properly marked.

Suggestion are most welcome.

https://github.com/dotnet/runtime/blob/a2b288d7da6a36164e5e556cd736ca50e0a9bc02/src/tests/Interop/StringMarshalling/VBByRefStr/VBByRefStrTest.cs#L15-L42

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr gcstress0x3-gcstress0xc 20220102.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1531890&view=ms.vss-test-web.build-test-results-tab&runId=43421240&paneView=debug&resultId=101019)

Failed test:
```

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

- Interop\\StringMarshalling\\VBByRefStr\\VBByRefStrTest\\VBByRefStrTest.cmd

CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open

- Interop\\StringMarshalling\\VBByRefStr\\VBByRefStrTest\\VBByRefStrTest.cmd

```
**Error message:**
```
Assert failure(PID 3220 [0x00000c94], Thread: 5240 [0x1478]): !CREATE_CHECK_STRING(!GCHeapUtilities::GetGCHeap()->IsLargeObject(this))

CORECLR! Object::ValidateInner + 0x2BC (0x7050cb6c)
CORECLR! Object::Validate + 0xAF (0x7050c86f)
CORECLR! WKS::GCHeap::Promote + 0x77 (0x7088c577)
CORECLR! GcEnumObject + 0x57 (0x70632b97)
CORECLR! EECodeManager::EnumGcRefs + 0xA04 (0x70449974)
CORECLR! GcStackCrawlCallBack + 0x152 (0x70632e02)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x705451e0)
CORECLR! Thread::StackWalkFramesEx + 0x186 (0x705468d1)
CORECLR! Thread::StackWalkFrames + 0x159 (0x705466cb)
CORECLR! ScanStackRoots + 0x196 (0x70632094)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 550
Image: C:\h\w\BED70A27\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\BED70A27\w\A9B309D0\uploads\Reports\Interop.StringMarshalling\VBByRefStr\VBByRefStrTest\VBByRefStrTest.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\BED70A27\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  VBByRefStrTest.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\BED70A27\p
C:\h\w\BED70A27\w\A9B309D0\e\Interop\StringMarshalling\VBByRefStr\VBByRefStrTest\VBByRefStrTest.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_StringMarshalling._VBByRefStr_VBByRefStrTest_VBByRefStrTest_._VBByRefStr_VBByRefStrTest_VBByRefStrTest_cmd()
```
