### ISSUE TITLE
Visual Studio 2022 : Extension code C# - JsonContent.CreateContent no longer works

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#63063]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-:-Extension-code-C--/1581333)._

---
[regression]
After upgrading to VisualStudio 2022, usage of following API result in error condition:
```
HttpContent content = JsonContent.Create(<object>,
                                                                 new MediaTypeHeaderValue("application/json"),
                                                                 new JsonSerializerOptions
                                                                 {
                                                                     PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                                                                     WriteIndented = true
                                                                 });
response = await client. PatchAsync(URL, content);
```
The HttpContent class gives following exception during PatchAsync call :
```
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Error while copying content to a stream.
  Source=mscorlib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   ....

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

When I changed the equivalent code to below:
```
string json = JsonConvert.SerializeObject(<object>, Formatting.Indented, new JsonSerializerSettings
                    {
                        Formatting = Formatting.Indented,
                        ContractResolver = new CamelCasePropertyNamesContractResolver()
                    });
  HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");
```

It worked.

But, with VS 2019 JsonContent worked perfectly.

---
#### Feedback Bot on 11/12/2021, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by krwq** [comment]
This doesn't seem like a problem with System.Text.Json but rather either improper setup of the project or something wrong with the packaging. Can you share your csproj?

**Comment by krwq** [comment]
I'm moving this to area-meta (assuming this is the right place for potential packaging issues)
