### ISSUE TITLE
Cannot create instance of type 'System.Text.Json.JsonDocument' because it is missing a public parameterless constructor.

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#63061]
### Description

```
Unhandled exception. System.InvalidOperationException: Cannot create instance of type 'System.Text.Json.JsonDocument' because it is missing a public parameterless constructor.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetPropertyValue(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration)
```

### Reproduction Steps

```
using Microsoft.Extensions.Configuration;
using System.Text.Json;

public class Program
{
    public static void Main(string[] args)
    {
        ConfigurationBuilder builder = new ConfigurationBuilder();
        builder.AddJsonFile("test.json");
        IConfigurationRoot? configuration = builder.Build();
        TestOptions? testOptions = configuration.Get<TestOptions>();
        if (testOptions.Type == 1)
        {
            ValueOptions? valueOptions = testOptions.Json.Deserialize<ValueOptions>();
            Console.WriteLine(valueOptions.Name);
        }
        else
        {
            //another deserialize
        }
    }
}

public class TestOptions
{
    public int Type { get; set; }

    public JsonDocument? Json { get; set; }
}

public class ValueOptions
{
    public int Id { get; set; }

    public string? Name { get; set; }
}
```

### Expected behavior

deserialize successful

### Actual behavior

failed to get options

**Comment by eerhardt** [comment]
ConfigurationBinder will bind strongly typed classes. See https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration#binding. Unfortunately `JsonDocument` doesn't meet the requirements for the kinds of Types that can be bound with ConfigurationBinder. These types are primitives, arrays, collections, and custom classes, with default ctors, made up of Types that can be bound.

You can rewrite your code above to instead be:

```C#
        if (testOptions.Type == 1)
        {
            ValueOptions? valueOptions = configuration.GetSection("json").Get<ValueOptions>();
            Console.WriteLine(valueOptions.Name);
        }
```

Which will allow it to work.

**Comment by Varorbc** [comment]
Thank you,`JsonSerializer.Deserialize<TestOptions>("");` work well, If it can be like that, so much the better

**Comment by eerhardt** [comment]
Closing as I believe this question has been answered.
