### ISSUE TITLE
[Android][x86][arm] System.Tests.GCExtendedTests.AllocateArrayTooLarge throws OverflowException instead of OutOfMemoryException

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#63079]
```
<test name="System.Tests.GCExtendedTests.AllocateArrayTooLarge" type="System.Tests.GCExtendedTests" method="AllocateArrayTooLarge" time="0.0181027" result="Fail">
<failure exception-type="Xunit.Sdk.ThrowsException">
    <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.OutOfMemoryException)\nActual:   typeof(System.OverflowException): Arithmetic operation resulted in an overflow.\n---- System.OverflowException : Arithmetic operation resulted in an overflow.]]></message>
    <stack-trace><![CDATA[   at System.GC.AllocateArray[Double](Int32 length, Boolean pinned)
at System.GC.AllocateUninitializedArray[Double](Int32 length, Boolean pinned)
at System.Tests.GCExtendedTests.<>c.<AllocateArrayTooLarge>b__29_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 1040
----- Inner Stack Trace -----
at System.GC.AllocateArray[Double](Int32 length, Boolean pinned)
at System.GC.AllocateUninitializedArray[Double](Int32 length, Boolean pinned)
at System.Tests.GCExtendedTests.<>c.<AllocateArrayTooLarge>b__29_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 1040]]></stack-trace>
</failure>
</test>
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1523011&view=ms.vss-test-web.build-test-results-tab&runId=43266500&resultId=166413&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

**This is a regression:** Reverting https://github.com/dotnet/runtime/commit/9ddd58a58d14a7bec5ed6eb777c6703c48aca15d makes the mentioned test pass.

cc @akoeplinger @steveisok @vargaz 

Upd. The tests are failing on Android x86/ arm legs:
- System.Tests.GCExtendedTests.AllocateArrayTooLarge
- System.Collections.Tests.SortedListTests.Capacity_Excessive
- System.Collections.Tests.CollectionBaseTests.Capacity_Excessive

**Comment by marek-safar** [comment]
@vargaz there are still few OOM exceptions expected (I didn't check if the tests are correct)
