### ISSUE TITLE
FileSystemWatch EnableRaisingEvents not supported on MonoVM

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#63185]
### Description

our code:
```c#
fileWatcher = new FileSystemWatcher(watchPath, "*" + watchFilter);
fileWatcher.NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.Size;
fileWatcher.Changed += FileWatcher_Changed;
fileWatcher.EnableRaisingEvents = true;
```

### Reproduction Steps

.net6.0 sdk
windows

### Expected behavior

work correctly

### Actual behavior

throw exception

System.PlatformNotSupportedException: This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
   at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at UnrealInit.RestartWatcher..ctor(Boolean bForceRestartWhenPlaying)
   at UnrealInit.PluginLoader.Start()
   at UnrealInit.PluginLoader.Init()

**Comment by lambdageek** [comment]
I don't think we hooked up the ThreadPoolBoundHandle stuff in Mono in 6.0.  @lateralusX @steveisok this is probably going to show up in a number of libraries tests on Windows in 7.0

**Comment by lateralusX** [comment]
Probably the same as https://github.com/dotnet/runtime/issues/34582, so it limitation in portable thread pool used by Mono.
