### ISSUE TITLE
Bad data can cause ILVerify to throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#63227]
### Description

While attempting to use ILVerify to diagnose a compiler output problem, it instead blew up in my face, dumping an `IndexOutOfRangeException` stack trace on me.

### Reproduction Steps

1) Install .NET 5.
2) Install ILVerify.
3) Download [this test case](https://github.com/dotnet/runtime/files/7794775/testcase.zip) and unzip it to a new folder.
4) Open PowerShell and CD to that folder.
5) `ilverify .\testcase.dll -r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.13\*.dll" -r "Boo.Lang.dll"`  (Adjust .NET 5 path as needed)
 

### Expected behavior

A correct program should not throw ["boneheaded exceptions."](https://ericlippert.com/2008/09/10/vexing-exceptions/)

A diagnostic tool should provide helpful diagnostic information about the nature of errors encountered.

### Actual behavior

<details>

```
Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Internal.IL.ILImporter.CreateBasicBlock(Int32 offset)
   at Internal.IL.ILImporter.FindBasicBlocks()
   at Internal.IL.ILImporter.Verify()
   at ILVerify.Verifier.VerifyMethod(EcmaModule module, MethodIL methodIL, MethodDefinitionHandle methodHandle)
   at ILVerify.Verifier.VerifyMethods(EcmaModule module, IEnumerable`1 methodHandles)+MoveNext()
   at ILVerify.Verifier.Verify(PEReader peReader, MethodDefinitionHandle methodHandle)+MoveNext()
   at ILVerify.Program.VerifyMethods(PEReader peReader, EcmaModule module, String path, Int32& numErrors, Int32& verifiedMethodCounter, Int32& methodCounter)
   at ILVerify.Program.VerifyAssembly(PEReader peReader, EcmaModule module, String path)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
```

</details>

### Configuration

.NET 5, Windows 10, x64

**Comment by jkotas** [comment]
```
Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Internal.IL.ILImporter.CreateBasicBlock(Int32 offset)
   at Internal.IL.ILImporter.FindBasicBlocks()
   at Internal.IL.ILImporter.Verify()
   at ILVerify.Verifier.VerifyMethod(EcmaModule module, MethodIL methodIL, MethodDefinitionHandle methodHandle)
   at ILVerify.Verifier.VerifyMethods(EcmaModule module, IEnumerable`1 methodHandles)+MoveNext()
   at ILVerify.Verifier.Verify(PEReader peReader, MethodDefinitionHandle methodHandle)+MoveNext()
   at ILVerify.Program.VerifyMethods(PEReader peReader, EcmaModule module, String path, Int32& numErrors, Int32& verifiedMethodCounter, Int32& methodCounter)
   at ILVerify.Program.VerifyAssembly(PEReader peReader, EcmaModule module, String path)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
```

**Comment by MichalStrehovsky** [comment]
peverify message:

```
[IL]: Error: [foo.exe : <Module>::main][offset 0x00000000] Code size is zero.
1 Error(s) Verifying empty.exe
```

The best fix is to add a check for length being zero in `FindBasicBlocks` and have that call `ReportZeroSizedMethod` (a new method; similar to the other `ReportXXX` method calls in ILImporter.cs). The `ReportZeroSizedMethod` method would be defined in ILImporter.Verify.cs file and report the error similar to how the other `Report` methods do it there.

It won't be possible to make a unit test for this because ILAsm will never generate a method with an empty body (it will put a ret there for you), so unit test can be skipped.

**Comment by masonwheeler** [comment]
There is actually a check for this already in `InitialPass`.  Unfortunately, its name notwithstanding, `InitialPass` is called *after* `FindBasicBlocks`.

**Comment by tmat** [comment]
Also hit for non-empty method bodies when `ret` is missing.


```
// [af599476-a23f-4c2e-b70d-a1de4f653a79]C.F()
.method instance void F() cil managed
{
  // Code size: 34
  .maxstack 1
  .locals init (bool V_0)

  IL_0000:  ldsflda     valuetype [System.Runtime]System.Threading.CancellationToken <PrivateImplementationDetails>::ModuleCancellationToken
  IL_0005:  call        instance void [System.Runtime]System.Threading.CancellationToken::ThrowIfCancellationRequested()
  IL_000A:  nop
  IL_000B:  nop
  IL_000C:  call        void [System.Console]System.Console::WriteLine()
  IL_0011:  nop
  IL_0012:  nop
  IL_0013:  ldsflda     valuetype [System.Runtime]System.Threading.CancellationToken <PrivateImplementationDetails>::ModuleCancellationToken
  IL_0018:  call        instance void [System.Runtime]System.Threading.CancellationToken::ThrowIfCancellationRequested()
  IL_001D:  ldc.i4.1
  IL_001E:  stloc.0
  IL_001F:  ldloc.0
  IL_0020:  brtrue.s    IL_000B
}

```

[repro.zip](https://github.com/dotnet/runtime/files/14106033/repro.zip)
