### ISSUE TITLE
ExecutionEngineException when using Marshal.Copy

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#63244]
### Description

However, according to the docs, this one is no longer being raised

### Reproduction Steps

```cs
using System.Reflection.PortableExecutable;
using System.Runtime.InteropServices;
using DeepEmulator;

const string peFile = @"someBigExeFile.exe";

using var fileStream = File.Open(peFile, FileMode.Open, FileAccess.Read);
using var peReader = new PEReader(fileStream);

var section = peReader.GetSectionData(".text");
var sectionBytes = section.GetContent().ToArray();

var funcAddr = Interop.VirtualAlloc(0, (uint)sectionBytes.Length, Interop.MEM_COMMIT, Interop.PAGE_READWRITE);
Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length); // Exception here

Interop.VirtualProtect((IntPtr)funcAddr, sectionBytes.Length, Interop.PAGE_EXECUTE, out var oldProtect);
uint threadId = 0;

var pInfo = IntPtr.Zero;

// Execute
var hThread = Interop.CreateThread(0, 0, funcAddr, pInfo, 0, ref threadId);
Interop.WaitForSingleObject(hThread, 0xFFFFFFFF);

### Expected behavior

Usage of Environment.FailFast

### Actual behavior

It throws an ExecutionEngineException

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.NET 7.0.100-alpha.1.21568.2
OS: Windows 10 Pro Version 21H1 (Build 19043.1415)
Architecture: AMD64

### Other information

_No response_

**Comment by danmoseley** [comment]
Could you please make the repro standalone? This depends on your pinvoke signatures, etc.

Is funcAddr valid? Why do you expect a fail fast?

**Comment by deeprobin** [comment]
> Could you please make the repro standalone? This depends on your pinvoke signatures, etc.
> 
> Is funcAddr valid? Why do you expect a fail fast?

I have scaled down the example accordingly.
FuncAddress is valid at the time. 

I can't tell you the exact procedure, but I assumed FailFast, because according to the documentation the ExecutionEngineException was replaced by it.

**Comment by deeprobin** [comment]
Have now noticed that the ExecutionEngineException occurs when the `destination` parameter is not IntPtr.Zero.
For ex.
```cs
var sectionBytes = new byte[2912012];
var funcAddr = 1u;
Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length);
```

Strangely enough, the ExecutionEngineException only occurs when the byte array reaches a certain size. If there is a maximum size for this I think we should use a more readable exception. On my system, the maximum size seems to be 2048 bytes.

```cs
var sectionBytes = new byte[2048];
var funcAddr = 1u;
Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length); // System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

```cs
var sectionBytes = new byte[2912012];
var funcAddr = 1u;
Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length);
```

Strangely enough, the ExecutionEngineException only occurs when the byte array reaches a certain size. If there is a maximum size for this I think we should use a more readable exception. On my system, the maximum size seems to be 2048 bytes.

```cs
var sectionBytes = new byte[2049];
var funcAddr = 1u;
Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length); // System.ExecutionEngineException

```

**Comment by deeprobin** [comment]
https://github.com/dotnet/runtime/blob/b42188a8143f3c7971a7ab1c735e31d8349e7991/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L260
https://github.com/dotnet/runtime/blob/b42188a8143f3c7971a7ab1c735e31d8349e7991/src/libraries/System.Private.CoreLib/src/System/Span.cs#L310-L324

Strangely enough, setting the breakpoint caused me to get an error message in the console.

```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Runtime.InteropServices.Marshal.CopyToNative[[System.Byte, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Byte[], Int32, IntPtr, Int32)
   at System.Runtime.InteropServices.Marshal.Copy(Byte[], Int32, IntPtr, Int32)
   at Program.<Main>$(System.String[])
```

After further analysis I came to the conclusion that the error takes place in Buffer.BulkMoveWithWriteBarrier.

https://github.com/dotnet/runtime/blob/b42188a8143f3c7971a7ab1c735e31d8349e7991/src/coreclr/System.Private.CoreLib/src/System/Buffer.CoreCLR.cs#L34-L40

Unfortunately the debugger didn't want to continue debugging, so I had to follow the rest of the process in my head.
BulkMoveWithWriteBarrierChunk is 0x4000 (dec: 16384). In the case of 2049 bytes we are still below this limit, so we get into _BulkMoveWithWriteBarrier where this error occurs

https://github.com/dotnet/runtime/blob/b42188a8143f3c7971a7ab1c735e31d8349e7991/src/coreclr/System.Private.CoreLib/src/System/Buffer.CoreCLR.cs#L44-L75

Since this error also occurs in release mode, I guess the error actually occurs in `__BulkMoveWithWriteBarrier` (internal call).
https://github.com/dotnet/runtime/blob/b42188a8143f3c7971a7ab1c735e31d8349e7991/src/coreclr/System.Private.CoreLib/src/System/Buffer.CoreCLR.cs#L77-L78

https://github.com/dotnet/runtime/blob/24e7a4a1a101d91b6666dc6f44137574246fdd9c/src/coreclr/vm/comutilnative.cpp#L648-L657

**Comment by deeprobin** [comment]
## Behavior in .NET Framework 4.8
```

**Comment by deeprobin** [comment]
My guess is that some _ASSERTE is causing this.
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/inc/debugmacros.h#L83-L89

**Comment by jkotas** [comment]
The arguments of `Marshal.Copy` are unmanaged pointers. Passing an invalid unmanaged pointer into methods like `Marshal.Copy` has unspecified behavior. It can silently corrupt data, it can crash inside the runtime or in some other place. There is no reliable way for runtime to validate the unmanaged pointers.

> Behavior in .NET Framework 4.8

It is by design that the behavior with invalid unmanaged pointers can vary between different runtime versions.

**Comment by danmoseley** [comment]
Should the [docs ](https://docs.microsoft.com/en-us/dotnet/api/system.executionengineexception?view=net-6.0)be saying this?
```
ExecutionEngineException previously indicated an unspecified fatal error in the runtime. The runtime no longer raises this exception so this type is obsolete.
```

**Comment by jkotas** [comment]
> Should the docs be saying this?

I think so. It is accurate description of the runtime behavior, for both .NET Framework and .NET Core.

`COR_E_EXECUTIONENGINE` `0x80131506` error code is used to signal fatal error. The internal uses of this error code by the runtime are not converted into raising of `ExecutionEngineException`.

**Comment by deeprobin** [comment]
As I understand it, this exception should not be thrown anymore. Practically it is still thrown.

What is the further procedure?

**Comment by jkotas** [comment]
> Practically it is still thrown.

Where do you see it thrown? 

`Fatal error. Internal CLR error. (0x80131506)` error message does not say anything about `ExecutionEngineException` being thrown.

**Comment by deeprobin** [comment]
@jkotas In Visual Studio 22

**Comment by jkotas** [comment]
@deeprobin I agree that it is confusing that the VS debugger reports `FailFast` as unhandled `ExecutionEngineException`. I have edited the top post to make it clear that this issue is about VS debugger behavior.

**Comment by deeprobin** [comment]
@jkotas Great! Thanks 👍🏼

**Comment by deeprobin** [comment]
Should we create an external issue at Visual Studio for this?

**Comment by EgorBo** [comment]
I must admit that it's indeed quite confusing when debugger points to `ExecutionEngineException` right at the comment that states that `The runtime no longer raises this exception so this type is obsolete.` 🙂

**Comment by mikelle-rogers** [comment]
I changed the title of this issue, because I found that it also reports the ExecutionEngineException outside of the debugger.

**Comment by mikelle-rogers** [comment]
> Have now noticed that the ExecutionEngineException occurs when the `destination` parameter is not IntPtr.Zero. For ex.
> 
> ```cs
> var sectionBytes = new byte[2912012];
> var funcAddr = 1u;
> Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length);
> ```
> 
> Strangely enough, the ExecutionEngineException only occurs when the byte array reaches a certain size. If there is a maximum size for this I think we should use a more readable exception. On my system, the maximum size seems to be 2048 bytes.
> 
> ```cs
> var sectionBytes = new byte[2048];
> var funcAddr = 1u;
> Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length); // System.NullReferenceException: 'Object reference not set to an instance of an object.'
> ```
> 
> ```cs
> var sectionBytes = new byte[2912012];
> var funcAddr = 1u;
> Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length);
> ```
> 
> Strangely enough, the ExecutionEngineException only occurs when the byte array reaches a certain size. If there is a maximum size for this I think we should use a more readable exception. On my system, the maximum size seems to be 2048 bytes.
> 
> ```cs
> var sectionBytes = new byte[2049];
> var funcAddr = 1u;
> Marshal.Copy(sectionBytes, 0, (IntPtr)funcAddr, sectionBytes.Length); // System.ExecutionEngineException
> ```

I found this to be the case as well.

**Comment by mikelle-rogers** [comment]
cc @janvorli

**Comment by janvorli** [comment]
I might have misunderstood the problem, but when I try the example with sectionBytes size >= 2049 on Windows 10, I get:
```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Runtime.InteropServices.Marshal.CopyToNative[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Byte[], Int32, IntPtr, Int32)
   at Program.<Main>$(System.String[])
```

I don't see any unhanled ExecutionEngineException.

**Comment by tommcdon** [comment]
Does Environment.FailFast repro the issue without the debugger?

**Comment by tommcdon** [comment]
It seems 0x80131506 is COR_E_EXECUTIONENGINE

**Comment by janvorli** [comment]
Right, but it is not an unhandled exception. It is not clear to me what is the expected behavior in this case. The problem most likely happens due to the fact that the failure address is out of the null reference area, so the AV cannot be translated to NullReferenceException.

**Comment by janvorli** [comment]
Hmm, actually, the issue is not due to the address not being in the null reference detection area. The failure with size=2049 happens at address 0x20, so it should have been reported as null reference. I'll investigate it further.

**Comment by janvorli** [comment]
It is clear now why the size changes the behavior. For sizes <= 2048, the copying is implemented fully in managed code. For sizes above that, the copying is delegated to the `memcpy` native function.
If it was using the `JIT_MemCpy`, it would be correctly translated to `NullReferenceException`. It is just a thin wrapper around `memmove`, accessing memory at src and dst so that the AV is triggered in this wrapper. `memcpy` is not recognized in any way, so it is considered to be general runtime code that is not allowed to cause null reference exception, thus the fail fast. We cannot reliably detect that an address is inside of `memcpy` as there are multiple variants that are executed based on the current architecture, block sizes etc. 
It is not clear to me why the managed code doesn't call `JIT_MemCpy` and calls `memcpy` directly instead.

**Comment by janvorli** [comment]
Correction - the managed code calls `__MemMove` QCALL (implemented by `Buffer_MemMove` in the native runtime)  which in turn calls `memmove` which in turn calls `memcpy`.

**Comment by janvorli** [comment]
It seems that to ensure we are getting `NullReferenceException` even for blocks larger than 2048, we would either need to call `JIT_MemCpy` from the `Buffer_MemMove` or modify the managed System.Buffer._MemMove to access the dst and src before invoking the QCALL.
cc: @jkotas for additional thoughts.

**Comment by jkotas** [comment]
`(void*)1` is invalid unmanaged pointer. Operations that end up reading or writing invalid unmanaged pointers have unspecified behavior as I have said in https://github.com/dotnet/runtime/issues/63244#issuecomment-1003649845 . They can throw arbitrary exception, crash with fail fast, silently corrupt process data, ... . 

The special handling of faults in the page at address zero is internal implementation detail of the runtime that allows JIT to elide explicit null checks in managed code. It is not meant to reliably sanitize accesses of invalid unmanaged pointers that happen to point into the page at address zero.

I believe that the only problem to solve here is how Visual Studio reports fail fasts. To reproduce the problem, create console app that does just `Environment.FailFast("Testing");` and press F5 in Visual Studio. You will see:

![image](https://user-images.githubusercontent.com/6668460/208793602-dfbe4b2b-d83f-4244-aba5-9dc72fbcd446.png)

"Exception of type 'ExecutionEngineException' was thrown" message is very confusing. There was no actual ExecutionEngineException thrown, and the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.executionengineexception) says that the runtime does not raise this exception anymore. 

The problem with the confusing error message does not reproduce outside debugger. Yes, the error code in the error message is `COR_E_EXECUTIONENGINE` but the error message does not say that there was an `ExecutionEngineException` exception thrown.

The VS debugger reports fail fasts in much better way for .NET Framework. For .NET Framework, the debugger displays:
![image](https://user-images.githubusercontent.com/6668460/208794557-7ddfe649-d384-43e3-b52c-a737d1c9abfa.png)
We have removed Managed Debugging Assistants in .NET Core, so the problem might have been introduced by that.

**Comment by mikelle-rogers** [comment]
This is a result of bad interaction between Visual Studio and the runtime- there is no exception, but the UI makes it look like there is. Prior reporting relied on MDAs (Managed Debugging Assistants), but we do not plan on bringing them back. We will reconsider fixing this issue in a future release.

**Comment by colejohnson66** [comment]
So the issue is a confused debugger?
