### ISSUE TITLE
JsonSerializerOptions.GetConverter Returns ObjectDefaultConverter, Insted of Expected Null

### ISSUE THREAD

**Issue by DerekJi** [dotnet/runtime#63444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Here's a sample project](https://github.com/DerekJi/JsonGetConverterDemo), which used to work very well.

In this project (see [CustomBase64Converter.cs](https://github.com/DerekJi/JsonGetConverterDemo/blob/master/JsonGetConverterDemo/CustomBase64Converter.cs)), I need to check if there's any available converter. 
```c#
    public T? Deserialize(ref Utf8JsonReader reader, JsonSerializerOptions options)
    {
        var converter = (JsonConverter<T>?)options.GetConverter(_valueType);

        if (converter != null)
        {
            return converter.Read(ref reader, _valueType, options);
        }
        else
        {
            return JsonSerializer.Deserialize<T>(ref reader, options);
        }
    }
```

It works perfectly before, with dotnet core 3.1. However, after upgraded to .net 6, it fails with exceptions like
![image](https://user-images.githubusercontent.com/33775203/148382751-b0ef1f24-b107-4b24-9f43-edd039df007a.png)

### Expected Behavior

The given string `encoded` can be deserialized correctly by `CustomBase64Converter` without exceptions.

```c#
    var encoded =
        "{\"StatusCode\":202,\"Description\":\"Testing\",\"AddressJson\":\"eyJTdHJlZXRObyI6IjVBIiwiU3RyZWV0IjoiU2FtcGxlIFN0cmVldCIsIlN1YnVyYiI6bnVsbCwiU3RhdGUiOiJTb3V0aCBBdXN0cmFsaWEiLCJDb3VudHJ5IjoiQXVzdHJhbGlhIn0=\"}";

    var options = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
    };

    var decoded = JsonSerializer.Deserialize<SampleResponse>(encoded, options);
```

## Reproduce the issue
1. Clone the sample project: https://github.com/DerekJi/JsonGetConverterDemo
2. Build and run in Visual Studio 2022. Or, run the commands in console
```bash
dotnet run
```
You'll get the exception

## Downgrade to dotnetcore3.1 and the issue is gone
1. update the project file to change `targetframework` as
```xml
<TargetFramework>netcoreapp3.1</TargetFramework>
```
2. rebuild and run the project, everything runs well.

### Exceptions (if any)

Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to JsonGetConverterDemo.Address. Path: $.AddressJson | LineNumber: 0 | BytePositionInLine: 198.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)   
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonResumableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at JsonGetConverterDemo.CustomBase64Converter`1.Deserialize(Utf8JsonReader& reader, JsonSerializerOptions options) in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\CustomBase64Converter.cs:line 16
   at JsonGetConverterDemo.CustomBase64Converter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\CustomBase64Converter.cs:line 41
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)   
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.<<Main>$>g__Demo|0_0() in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\Program.cs:line 35
   at Program.<Main>$(String[] args) in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\Program.cs:line 7

### .NET Version

6.0.100

### Anything else?

The document (https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.getconverter?view=net-6.0) says:
![image](https://user-images.githubusercontent.com/33775203/148385421-54be088d-dd47-403d-945c-44ba3c7d6a66.png)

Without any specified converters, I expect `options.GetConverter(_valueType)` returns null, just as described above. However, with .net 6, it returns `ObjectDefaultConverter` unexpectedly.

**Comment by eiriktsarpalis** [comment]
I ran your reproduction on the debugger, and it looks like the exception is being thrown because of this check failing in the default object converter:
https://github.com/dotnet/runtime/blob/fe8422cdff450941bc3ba4b120576e8822459df4/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectDefaultConverter.cs#L29-L32
This is because you are passing the converter an unused `Utf8JsonReader` instance so its `TokenType` property evaluates to `None`. Generally speaking converters are built under the assumption that the reader has already read the first token of the value being deserialized, so this type of failure is to expected in most cases.

In your case it would probably make sense to just call `JsonSerializer.Deserialize` like so
```C#
    public T? Deserialize(ref Utf8JsonReader reader, JsonSerializerOptions options)
    {
        return JsonSerializer.Deserialize<T>(ref reader, options);
    }
```
since the root deserialization logic will take all necessary steps to [prime your reader instance](https://github.com/dotnet/runtime/blob/fe8422cdff450941bc3ba4b120576e8822459df4/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L259-L262). Alternatively you could just call `reader.Read();` ahead of calling the converter `Read` method.

I ran the repro in both `net5.0` and `netcoreapp3.1` and can confirm that this failure doesn't occur in the latter. I'm assuming the original converter infrastructure would tolerate unread `Utf8JsonReader` instances and this property was lost during one of the more recent refactorings. @steveharter might have more context on history here. I don't believe this to be a regression though, converter methods are not meant to be consumed that way.

**Comment by DerekJi** [comment]
Thanks @eiriktsarpalis. Just as you said, the exception was just caused by the UNUSED `reader`. Tried to USE it first and then it works! 
```c#
            if (converter != null && reader.Read())
            {
                return converter.Read(ref reader, _valueType, options);    
            }
```

But it looks a bit ugly. 
* As using `converter.Read()`, I thought it would handle with such kinds of things inside. And the official doc doesn't mention that at all: 
  > [JsonConverter<T>.Read(Utf8JsonReader, Type, JsonSerializerOptions) Method](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.read?view=net-6.0)

* The exception message is quite confusing by simply saying "_The JSON value could not be converted to xxx_", which doesn't make sense here and just let me think "_Oh, that's a bad or wrong converter!_". It would be helpful to developers tell us something like "incorrect TokenType".

Cheers.

**Comment by eiriktsarpalis** [comment]
> The exception message is quite confusing by simply saying "The JSON value could not be converted to xxx", which doesn't make sense here and just let me think "Oh, that's a bad or wrong converter!". It would be helpful to developers tell us something like "incorrect TokenType".

That's because the original exception is being wrapped by the serializer -- would need to to double check but I believe the actual error message is in the inner exception.
