### ISSUE TITLE
ObjectDisposedException after slightly malformed POST/PUT request in HttpListener

### ISSUE THREAD

**Issue by frindler** [dotnet/runtime#63543]
### Description

When one post a slightly malformed (Content-Length missing and no body) HTTP POST/PUT request to a listening HttpListener, the Response object has been disposed and the code crashes with an ObjectDisposedException.

### Reproduction Steps

The following is essentially the simple example from https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener?view=net-6.0:
```c#
using System.Net;
HttpListener listener = new HttpListener();
listener.Prefixes.Add($@"http://*:42424/");
listener.Start();
Console.WriteLine("Listening...");
HttpListenerContext context = listener.GetContext();
HttpListenerRequest request = context.Request;
HttpListenerResponse response = context.Response;
string responseString = "<HTML><BODY> Hello world!</BODY></HTML>";
byte[] buffer = System.Text.Encoding.UTF8.GetBytes(responseString);
response.ContentLength64 = buffer.Length; // ***
Stream output = response.OutputStream;
output.Write(buffer,0,buffer.Length);
output.Close();
listener.Stop();
```
Now do (this is on macOS 12.1)
```
curl -X POST http://localhost:42424
```
or
```
curl -X PUT http://localhost:42424
```
and the code crashes with `ObjectDisposedException` at "***" since `response` has been disposed.

### Expected behavior

Either an exception or a graceful ignoring of the malformed request (it's just an empty body request). Then the result of the request should be
```
$ curl -X POST http://localhost:42424
<HTML><BODY> Hello world!</BODY></HTML>%   
```

### Actual behavior

Console output:
```
Listening...
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.set_ContentLength64(Int64 value)
   at Program.<Main>$(String[] args) in [...]/Program.cs:line 11
```

On the terminal running the request:
```
$ curl -X PUT http://localhost:42424
<h1>Length Required</h1>% 
```

### Known Workarounds

None since one cannot replace the HttpListenerResponse object (creation is forbidden).

A correct request like
```
$ curl -X POST http://localhost:42424 -d {}
```
(with explicit empty body) works fine and gives the expected result:
```
$ curl -X POST http://localhost:42424 -d {}
<HTML><BODY> Hello world!</BODY></HTML>%   
```

### Configuration

.NET 6.0.101
macOS 12.1 Monterey
x64 (Intel)

### Other information

Seems to be the same (?) as this bug in Mono: https://github.com/mono/mono/issues/10435

**Comment by karelz** [comment]
Triage: Looks like impact is only to have nicer exception. Given that HttpListener is not production high-performance solution, it may be ok to live with it.
If there is proposed change, we would consider taking it.

**Comment by rokonec** [comment]
I have looked at it and HttpListener on linux/mac works the way, that some errors, like unsupported HTML version or empty POST body, handle internally, sends back predefined response, and close and dispose response object.
Windows is different and for example for empty POST body, it is handled internally on http.sys (kernel), when http.sys send error response but keep listening for correct request so the `listener.GetContext()` will not end unless non malformed request is received.
For linux I would change to code to:
``` C#
            HttpListener listener = new HttpListener();
            listener.Prefixes.Add($@"http://+:42424/");
            listener.Start();
            Console.WriteLine("Listening...");
            HttpListenerContext context = listener.GetContext();
            HttpListenerRequest request = context.Request;
            HttpListenerResponse response = context.Response;
            Stream output = null;
            try
            {
                output = response.OutputStream;
            }
            catch (ObjectDisposedException) 
            {
                // GetContext handles some errors internally. In these cases, the response has 
                // already been sent, and the HttpListenerResponse object is disposed. 
                // Attempting to access the OutputStream will throw an ObjectDisposedException.
            }
            if (output != null)
            {
                string responseString = "<HTML><BODY> Hello world! </BODY></HTML>";
                byte[] buffer = System.Text.Encoding.UTF8.GetBytes(responseString);
                response.ContentLength64 = buffer.Length; // ***
                
                output.Write(buffer, 0, buffer.Length);
                output.Close();
            }
            listener.Stop();
```
Alternatively it can be tested by `response.ContentLength64 > 0` which indicates that response content has already been sent and therefore cannot be send again.

**Comment by rokonec** [comment]
Closed with above workaround ^
