### ISSUE TITLE
Test failure ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63603]
Run: [runtime 20220110.48](https://dev.azure.com/dnceng/public/_build/results?buildId=1545263&view=ms.vss-test-web.build-test-results-tab&runId=43675774&resultId=113535&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673

- ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...)

```
**Error message:**
```
System.NotSupportedException : Memory stream is not expandable.


Stack trace
   at System.IO.MemoryStream.set_Capacity(Int32 value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs:line 281
   at System.IO.MemoryStream.EnsureCapacity(Int32 value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs:line 165
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer) in /_/src/libraries/System.Private.CoreLib/src/System/IO/MemoryStream.cs:line 677
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 327
   at System.IO.StreamWriter.Dispose(Boolean disposing) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 220
   at System.IO.TextWriter.Dispose() in /_/src/libraries/System.Private.CoreLib/src/System/IO/TextWriter.cs:line 65
   at ConsoleEncoding.TestEncoding(String inputString) in /_/src/libraries/System.Console/tests/ConsoleEncoding.cs:line 55
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
```

**Comment by danmoseley** [comment]
Hm, this means that writing this string to a StreamWriter via Console.Write using Console.OutputEncoding produced more bytes than was expected. It was expected it would require as many bytes as the input:
https://github.com/dotnet/runtime/blob/4679edc6be3eb91263a7acfe542dfd30b53ed2bf/src/libraries/System.Console/tests/ConsoleEncoding.cs#L48

The message incidentally really ought to be improved eg "MemoryStream cannot be expanded because it wraps a user-provided buffer."

This failure appears to be a very rare sporadic failure rather than new:

```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-90d)
| where Result == "Fail"
| where  Method == "TestEncoding"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,Started,
  Duration,
  Method,
  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline|Pipeline_Configuration|OS|Arch|Test|Result|Finished|Started|Duration|Method|Build|Message|
|---|---|---|---|---|---|---|---|---|---|---|---|
|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|test/functional/cli/innerloop/|Fail|2021-11-17 18:44:53.9880000|2021-11-17 18:44:26.6060000|0.003|TestEncoding|20211117.22|System.NotSupportedException : Memory stream is not expandable.|
|runtime|Release|ubuntu.1804.amd64.open.rt|x64|test/functional/cli/innerloop/|Fail|2022-01-10 21:36:06.6530000|2022-01-10 21:35:37.7090000|0.004|TestEncoding|20220110.48|System.NotSupportedException : Memory stream is not expandable.|
