### ISSUE TITLE
GetClientCertificateAsync can fail with exception about corrupted frame 

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#63662]
Simple client like this agains Kestreal
```c#
await client.PostAsync("https://localhost:5006", new StringContent(new string('a', 100 * 1024)));
```
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMELEMDO0P0N", Request id "0HMELEMDO0P0N:00000002": An unhandled exception was thrown by the application.
      System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in C:\Users\test\github\wfurt-runtime\src\libraries\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 484
         at System.Net.Security.SslStream.RenegotiateAsync[TIOAdapter](TIOAdapter adapter) in C:\Users\test\github\wfurt-runtime\src\libraries\System.Net.Security\src\System\Net\Security\SslStream.Implementation.cs:line 305
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.TlsConnectionFeature.GetClientCertificateAsyncCore(CancellationToken cancellationToken)
         at Program.<>c__DisplayClass0_0.<<<Main>$>b__1>d.MoveNext() in C:\Users\test\source\repos\WebApplication104\WebApplication104\Program.cs:line 39
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

#56470 added check for pending data as 
https://github.com/dotnet/runtime/blob/cbfdf3f0d446b5e36aa2d6f495098c3599f958f8/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L273-L276

The problem is there there can still be partial frame in `_internalBuffer` and `_decryptedBytesCount` is zero. We can start renegotiation and then we will try to read response:
https://github.com/dotnet/runtime/blob/cbfdf3f0d446b5e36aa2d6f495098c3599f958f8/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L301-L304

The underlying code will attempt to read TLS frame but it can fail since what comes on the wire is not frame header but rest of previous unfinished frame. 

It seems like we should fail the call anyway but the current exception is incorrect and misleading.

cc: @Tratcher @avparuch

**Comment by karelz** [comment]
Triage: We will throw anyway, we should just throw better exception.

**Comment by wfurt** [comment]
related  #52037
