### ISSUE TITLE
`System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination` is occasionally failing on macOS

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#63760]
Example issue: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63633-merge-ec75d68785dd45e787/System.Runtime.InteropServices.Tests/1/console.0588a1a1.log?%3Fsv%3D2019-07-07%26se%3D2022-02-01T21%253A28%253A55Z%26sr%3Dc%26sp%3Drl%26sig%3DCBSx1OxpeyQ6%252BW5IKMid7t09mCxdd35u%252BTLWjqr%252Fzr0%253D

/cc @stephentoub 

<details>
  <summary>Text from link</summary>

```
Console log: 'System.Runtime.InteropServices.Tests' from job ec75d687-85dd-45e7-87fe-5c662f8f8222 workitem 858698f7-1ba5-4779-8f92-cf3f6dd7ff4e (osx.1014.amd64.open) executed on machine dci-mac-build-029.local
+ ./RunTests.sh --runtime-path /tmp/helix/working/B296096E/p
----- start Wed Jan 12 14:49:13 PST 2022 =============== To repro directly: =====================================================
pushd .
RUNTIME_PATH/dotnet exec --runtimeconfig System.Runtime.InteropServices.Tests.runtimeconfig.json --depsfile System.Runtime.InteropServices.Tests.deps.json xunit.console.dll System.Runtime.InteropServices.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing RSP_FILE
popd
===========================================================================================================
/private/tmp/helix/working/B296096E/w/A56F09A7/e /private/tmp/helix/working/B296096E/w/A56F09A7/e
  Discovering: System.Runtime.InteropServices.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.InteropServices.Tests (found 565 of 673 test cases)
  Starting:    System.Runtime.InteropServices.Tests (parallel test collections = on, max threads = 4)
    System.Runtime.InteropServices.Tests.NFloatTests.Ctor_Double_OutOfRange [SKIP]
      Condition(s) not met: "Is32BitProcess"
    System.Runtime.InteropServices.Tests.NFloatTests.ToStringTest32 [SKIP]
      Condition(s) not met: "Is32BitProcess"
    System.Runtime.InteropServices.Tests.CLongTests.Ctor_NInt_OutOfRange [SKIP]
      Condition(s) not met: "NativeIntConstructorCanOverflow"
    System.Runtime.InteropServices.Tests.CULongTests.Ctor_NUInt_OutOfRange [SKIP]
      Condition(s) not met: "NativeIntConstructorCanOverflow"
   System.Runtime.InteropServices.Tests: [Long Running Test] 'System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination', Elapsed: 00:02:11
   System.Runtime.InteropServices.Tests: [Long Running Test] 'System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination', Elapsed: 00:04:12
   System.Runtime.InteropServices.Tests: [Long Running Test] 'System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination', Elapsed: 00:06:13
   System.Runtime.InteropServices.Tests: [Long Running Test] 'System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination', Elapsed: 00:08:13
   System.Runtime.InteropServices.Tests: [Long Running Test] 'System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination', Elapsed: 00:10:14
    System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination(signal: SIGQUIT, cancel: False, expectedExitCode: 131) [FAIL]
      Half-way through waiting for remote process.
      Timed out at 1/12/2022 2:59:31 PM after 600000ms waiting for remote process.
      	Process ID: 2339
      	Handle: 1124
      	Name: dotnet
      	MainModule: /private/tmp/helix/working/B296096E/p/dotnet
      	StartTime: 1/12/2022 2:49:31 PM
      	TotalProcessorTime: 00:00:14.4258884
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/PosixSignalRegistrationTests.Unix.cs(177,0): at System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination(PosixSignal signal, Boolean cancel, Int32 expectedExitCode)
  Finished:    System.Runtime.InteropServices.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.InteropServices.Tests  Total: 1080, Errors: 0, Failed: 1, Skipped: 4, Time: 770.244s
/private/tmp/helix/working/B296096E/w/A56F09A7/e
----- end Wed Jan 12 15:02:14 PST 2022 ----- exit code 1 ----------------------------------------------------------
ulimit -c value: unlimited
+ export _commandExitCode=0
+ _commandExitCode=0
+ /usr/local/bin/python3 /tmp/helix/working/B296096E/p/reporter/run.py https://dev.azure.com/dnceng/ public 43749576 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvZG90bmV0L3J1bnRpbWUvNjg2OkJ1aWxkL0J1aWxkLzE1NDk0NjYiLCJhdWkiOiJiOWZkZDJkNS04OTAyLTQ5MWMtODE2YS00OWVhYWRjN2RkMDciLCJzaWQiOiI2YzI4ZDk5NS1kMTQ3LTQ3OTQtYmEyNC05NjhhMGRkNmUzNzIiLCJCdWlsZElkIjoiOWVlNmQ0NzgtZDI4OC00N2Y3LWFhY2MtZjZlNmQwODJhZTZkOzE1NDk0NjYiLCJwcGlkIjoidnN0ZnM6Ly8vQnVpbGQvQnVpbGQvMTU0OTQ2NiIsIm9yY2hpZCI6IjU2YTljYjhiLWQ5MjItNDgzYi05YjFjLTdiMWUzOGIxN2U2Ny5saWJyYXJpZXNfdGVzdF9ydW5fY2hlY2tlZF9jb3JlY2xyX29zeF94NjRfZGVidWcuX19kZWZhdWx0IiwiaXNzIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsImF1ZCI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb218dnNvOmI1NWRlNGVkLTRiNWEtNDIxNS1hOGU0LTBhMGE1ZjcxZTdkOCIsIm5iZiI6MTY0MjAyMTYxMywiZXhwIjoxNjQyMDMxODEzfQ.IUldRv5tCW0CryUm9dFOX9Z5LmE_jtkNGa89Wr3bbk2fJzMTaNXcNPm5X9YCaCbqzwrT9UUE6HXfZxQqjjdgFoyeQ9_kdDPH7VoFLzUGkiaVBeTCsfBmjCHwFyKMSXGWVIiHh66uhjRVKBfRBWw-o1ykemrZf4DZNnqG9T92VDIkENufkt4KDTwWiSYDKPhXh-keI-m-U5dKBAEOogDHhnMjOnX_w48TRUaughOatWbJece13CcJ1QLh6DudQ3N0Io--OatV6RFPgub9MCg6xUPhSSjSIX7YLgSn0xiK_L1DWvS2hvFul3YucrhZiOq88MHMSVdPRQK66WR4zfe8aw
['System.Runtime.InteropServices.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```
</details>

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at System.Tests.PosixSignalRegistrationTests.SignalCanCancelTermination",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[343925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343925)|dotnet/runtime|[System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343925&view=ms.vss-test-web.build-test-results-tab&runId=7187868&resultId=101433)|dotnet/runtime#84542|
|[343283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343283)|dotnet/runtime|[System.Runtime.InteropServices.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343283&view=ms.vss-test-web.build-test-results-tab&runId=7173168&resultId=173804)||
|[342944](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342944)|dotnet/runtime|[System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342944&view=ms.vss-test-web.build-test-results-tab&runId=7165756&resultId=101108)|dotnet/runtime#88510|
|[323174](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323174)|dotnet/runtime|[System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector](https://dev.azure.com/dnceng-public/public/_build/results?buildId=323174&view=ms.vss-test-web.build-test-results-tab&runId=6638196&resultId=113153)|dotnet/runtime#87579|
|[321247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321247)|dotnet/runtime|[System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector](https://dev.azure.com/dnceng-public/public/_build/results?buildId=321247&view=ms.vss-test-web.build-test-results-tab&runId=6590698&resultId=101343)|dotnet/runtime#86194|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|5|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 7/19/2023 11:52:51 PM UTC

**Comment by jkotas** [comment]
This failed again in #83866. 

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-83866-merge-5fc02df3627749f880/System.Runtime.InteropServices.Tests/1/console.b16259fb.log?helixlogtype=result

**Comment by jkoritzinsky** [comment]
Looks like the only failures currently seen are either false-positives due to the previous search string being too common or a timeout failure on a sanitizer run (which timed out other tests as well). I'm going to close this for now. If it pops again, we'll open another issue to track the failures.
