### ISSUE TITLE
NativeAOT: Crash with assertion during obj file emit.

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#63779]
```
Raw output file:      ~/runtime/artifacts/tests/coreclr/Linux.x64.Debug/nativeaot/SmokeTests/Reports/nativeaot.SmokeTests/FrameworkStrings/Baseline/Baseline.output.txt
Raw output:
BEGIN EXECUTION
Running Native AOT:  ~/runtime/dotnet.sh msbuild /p:IlcPath=~/runtime/artifacts/tests/coreclr/Linux.x64.Debug/Tests/Core_Root/nativeaot nativebuild.proj
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Generating native code
  Process terminated. Assertion failed.
     at ILCompiler.UserDefinedTypeDescriptor.GetStateMachineThisVariableTypeIndex(TypeDesc type)
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitDebugVar(INodeWithDebugInfo owningNode, DebugVarInfoMetadata& debugVar)
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitDebugVarInfo(ObjectNode node)
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitObject(String objectFilePath, IReadOnlyCollection`1 nodes, NodeFactory factory, ObjectWritingOptions options, IObjectDumper dumper, Logger logger)
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper)
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper)
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

**Comment by kant2002** [comment]
Assert is here 
https://github.com/dotnet/runtime/blob/b2dc37ba181a7fa4427e717eab819ba3543d0ae4/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs#L59

`type` equals `{[S.P.CoreLib]System.Runtime.CompilerServices.StaticClassConstructionContext*}`

Method for which emitting debug variable information is `{[S.P.CoreLib]System.Runtime.CompilerServices.ClassConstructorRunner+Cctor.GetCctor(StaticClassConstructionContext*)}`

On Windows error seems to be not present.

**Comment by kant2002** [comment]
Honestly this happens after rebase and gone after `git clean -xdf` so probably that's not an issue.

**Comment by MichalStrehovsky** [comment]
My guess is a stale symbol file. We should not crash if symbols are out sync because that's garbage input like any other - the compiler should tolerate as much garbage as possible because that's the real world.
