### ISSUE TITLE
Test failure System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.InvalidKeySize_DoesNotInvalidateKey

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63773]
Run: [runtime 20220113.81](https://dev.azure.com/dnceng/public/_build/results?buildId=1551629&view=ms.vss-test-web.build-test-results-tab&runId=43791174&paneView=debug&resultId=150803)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open

- System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.InvalidKeySize_DoesNotInvalidateKey

```
**Error message:**
```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal consistency check failed.


Stack trace
   at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKeyLite.cs:line 408
   at System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle() in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/DSACng.cs:line 48
   at System.Security.Cryptography.DSAImplementation.DSACng.ComputeQLength() in /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.SignVerify.cs:line 178
   at System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary(ReadOnlySpan`1 hash, Span`1 stackBuf) in /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.SignVerify.cs:line 156
   at System.Security.Cryptography.DSAImplementation.DSACng.CreateSignature(Byte[] rgbHash) in /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.SignVerify.cs:line 32
   at System.Security.Cryptography.DSA.SignData(Stream data, HashAlgorithmName hashAlgorithm) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/DSA.cs:line 251
   at System.Security.Cryptography.Dsa.Tests.DSASignVerify_Stream.SignData(DSA dsa, Byte[] data, HashAlgorithmName hashAlgorithm) in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs:line 61
   at System.Security.Cryptography.Dsa.Tests.DSASignVerify.InvalidKeySize_DoesNotInvalidateKey() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs:line 123
```

**Comment by vcsjones** [comment]
Duplicate of #25979
