### ISSUE TITLE
Test failure GC/Features/SustainedLowLatency/scenario/scenario.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63858]
Run: [runtime-coreclr jitstress2-jitstressregs 20220116.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1555856&view=ms.vss-test-web.build-test-results-tab&runId=43868408&paneView=debug&resultId=110427)

Failed test:
```
CoreCLR Linux arm64 Checked jitstress2_jitstressregs8 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- GC/Features/SustainedLowLatency/scenario/scenario.sh

```
**Error message:**
```
createdump: /__w/1/s/src/coreclr/pal/src/libunwind/src/dwarf/Gfind_proc_info-lsb.c:929: int _Uaarch64_dwarf_search_unwind_table(unw_addr_space_t, unw_word_t, unw_dyn_info_t *, unw_proc_info_t *, int, void *): Assertion `ip >= di->start_ip && ip < di->end_ip' failed.
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.sh: line 411:  4922 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Features/SustainedLowLatency/scenario/scenario.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false scenario.dll ''
Cleaning up-------gen0: 4021, gen1: 667; gen2: 194, heap size: 39,252,536 bytes
Cleaning up-------gen0: 8035, gen1: 1325; gen2: 386, heap size: 49,890,376 bytes
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.sh
Expected: True
Actual:   False


Stack trace
   at GC_Features._SustainedLowLatency_scenario_scenario_._SustainedLowLatency_scenario_scenario_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr r2r 20220314.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1663714&view=ms.vss-test-web.build-test-results-tab&runId=45766540&resultId=110008&paneView=debug)

Failed test:
```
R2R Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- GC/Features/SustainedLowLatency/scenario/scenario.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.sh: line 253: -r:/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.dll.rsp': No such file or directory
createdump: /__w/1/s/src/coreclr/pal/src/libunwind/src/dwarf/Gfind_proc_info-lsb.c:929: int _Uaarch64_dwarf_search_unwind_table(unw_addr_space_t, unw_word_t, unw_dyn_info_t *, unw_proc_info_t *, int, void *): Assertion `ip >= di->start_ip && ip < di->end_ip' failed.
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.sh: line 377:  5893 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Features/SustainedLowLatency/scenario/scenario.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/IL-CG2/scenario.dll
Response file: /root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.dll.rsp
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/IL-CG2/scenario.dll
-o:/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.dll
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false scenario.dll ''
Cleaning up-------gen0: 4018, gen1: 736; gen2: 203, heap size: 43,197,792 bytes
Cleaning up-------gen0: 8045, gen1: 1471; gen2: 403, heap size: 41,752,744 bytes
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/Features/SustainedLowLatency/scenario/scenario.sh
Expected: True
Actual:   False


Stack trace
   at GC_Features._SustainedLowLatency_scenario_scenario_._SustainedLowLatency_scenario_scenario_sh()
```

**Comment by mangod9** [comment]
closing since these were related to bunch of undiagnosed cg2 failures which havent reproed
