### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\Arm\\ArmBase\\ArmBase_ro\\ArmBase_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63856]
Run: [runtime-coreclr outerloop 20220116.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1555891&view=ms.vss-test-web.build-test-results-tab&runId=43868712&paneView=debug&resultId=100072)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\Arm\\ArmBase\\ArmBase_ro\\ArmBase_ro.cmd

```
**Error message:**
```
Could Not Find D:\h\w\9EFF08A1\w\B4C5097C\e\JIT\HardwareIntrinsics\Arm\ArmBase\ArmBase_ro\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\9EFF08A1\w\B4C5097C\e\JIT\HardwareIntrinsics\Arm\ArmBase\ArmBase_ro\ArmBase_ro.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef) at System.Threading.Tasks.TaskReplicator+Replica.Execute() at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object) at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean) at System.Threading.Tasks.Task.RunSynchronously(System.Threading.Tasks.TaskScheduler) at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean)
at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action1<Int32>, System.Action2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func1<System.__Canon>, System.Action1<System.__Canon>) at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IList1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon


Stack trace
   at JIT_HardwareIntrinsics._Arm_ArmBase_ArmBase_ro_ArmBase_ro_._Arm_ArmBase_ArmBase_ro_ArmBase_ro_cmd()
```

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib @echesakovMSFT.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr outerloop 20220210.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1606340&view=ms.vss-test-web.build-test-results-tab&runId=44796274&resultId=100236&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_r\\AdvSimd.Arm64_Part2_r.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_ro\\AdvSimd.Arm64_Part2_ro.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_ro\\AdvSimd.Arm64_Part2_ro.cmd
- JIT\\HardwareIntrinsics\\Arm\\AdvSimd.Arm64\\AdvSimd.Arm64_Part2_r\\AdvSimd.Arm64_Part2_r.cmd

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_ro/AdvSimd.Arm64_Part2_ro.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_ro/AdvSimd.Arm64_Part2_ro.sh
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part2_r/AdvSimd.Arm64_Part2_r.sh

```
**Error message:**
```
Could Not Find D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\AdvSimd.Arm64_Part2_r.dll.rsp
Could Not Find D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\TestLibrary.dll.rsp

Assert failure(PID 7368 [0x00001cc8], Thread: 7772 [0x1e5c]): Verify_TypeLayout 'TestStruct' failed to verify type layout

CORECLR! LoadDynamicInfoEntry + 0x10C0 (0x00007fffcc5c27d8) CORECLR! Module::FixupNativeEntry + 0x6C (0x00007fffcc54077c)
CORECLR! Module::FixupDelayListAux<Module ,int (__cdecl Module::)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x18C (0x00007fffcc683094) CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007fffcc684224)
CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007fffcc61e5e0) CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007fffcc61e3b8)
CORECLR! MethodDesc::PrepareILBasedCode + 0x2AC (0x00007fffcc620404) CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007fffcc62014c)
CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x2A8 (0x00007fffcc567100) CORECLR! MethodDesc::DoPrestub + 0x344 (0x00007fffcc61c054)
File: D:\a_work\1\s\src\coreclr\vm\jitinterface.cpp Line: 13513
Image: D:\h\w\A8AB08FF\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\A8AB08FF\w\A3A40948\uploads\Reports\JIT.HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\AdvSimd.Arm64_Part2_r.output.txt
Raw output:
BEGIN EXECUTION
AdvSimd.Arm64_Part2_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\AdvSimd.Arm64_Part2_r.dll.rsp
D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\IL-CG2\AdvSimd.Arm64_Part2_r.dll
-o:D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\AdvSimd.Arm64_Part2_r.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A8AB08FF\p\System..dll
-r:D:\h\w\A8AB08FF\p\Microsoft..dll
-r:D:\h\w\A8AB08FF\p\mscorlib.dll
-r:D:\h\w\A8AB08FF\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A8AB08FF\p\crossgen2\crossgen2.dll" @"D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\AdvSimd.Arm64_Part2_r.dll.rsp"   -r:D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\AdvSimd.Arm64_Part2_r.dll
Response file: D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\TestLibrary.dll.rsp
D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\IL-CG2\TestLibrary.dll
-o:D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\TestLibrary.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A8AB08FF\p\System..dll
-r:D:\h\w\A8AB08FF\p\Microsoft..dll
-r:D:\h\w\A8AB08FF\p\mscorlib.dll
-r:D:\h\w\A8AB08FF\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A8AB08FF\p\crossgen2\crossgen2.dll" @"D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\TestLibrary.dll.rsp"   -r:D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A8AB08FF\w\A3A40948\e\JIT\HardwareIntrinsics\Arm\AdvSimd.Arm64\AdvSimd.Arm64_Part2_r\TestLibrary.dll
"D:\h\w\A8AB08FF\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  AdvSimd.Arm64_Part2_r.dll
Supported ISAs:
AdvSimd:   True
Aes:       True
ArmBase:   True
Crc32:     True
Dp:


Stack trace
   at JIT_HardwareIntrinsics._Arm_AdvSimd_Arm64_AdvSimd_Arm64_Part2_r_AdvSimd_Arm64_Part2_r_._Arm_AdvSimd_Arm64_AdvSimd_Arm64_Part2_r_AdvSimd_Arm64_Part2_r_cmd()
```

**Comment by BruceForstall** [comment]
New failures look like CG2 issues. @dotnet/crossgen-contrib

**Comment by echesakovMSFT** [comment]
`ArmBase_ro` do not fail anymore on Arm32 (https://dev.azure.com/dnceng/public/_build/results?buildId=1610941&view=logs&j=cd261195-c7e2-54a1-60a3-459694f56242&t=c9e67d87-f9db-5f10-068f-358f9fd879f9) 

`AdvSimd.Arm64_Part2_r` and `AdvSimd.Arm64_Part2_ro` are tracked by #65281
