### ISSUE TITLE
PGO assert in Loop Hoisting

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#63982]
From https://dev.azure.com/dnceng/public/_build/results?buildId=1555828&view=ms.vss-test-web.build-test-results-tab

```
COMPlus_JitRandomEdgeCounts=1
COMPlus_JitRandomGuardedDevirtualization=1
COMPlus_ReadyToRun=0
COMPlus_TC_QuickJitForLoops=1
COMPlus_TieredCompilation=1
COMPlus_TieredPGO=1

corerun.exe  xunit.console.dll System.Runtime.Numerics.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing

  Discovering: System.Runtime.Numerics.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Numerics.Tests (found 223 of 228 test cases)
  Starting:    System.Runtime.Numerics.Tests (parallel test collections = on, max threads = 12)

Assert failure(PID 80276 [0x00013994], Thread: 80812 [0x13bac]): Assertion failed 'BitVecOps::IsMember(&bitVecTraits, succBlocks, uniqueSuccSet.nonDuplicates[i]->bbNum)' in 'Number:NumberToStringFormat(byref,byref,System.ReadOnlySpan`1[Char],System.Globalization.NumberFormatInfo)' during 'Hoist loop code' (IL size 1982)

    File: C:\repos\runtime2\src\coreclr\jit\fgdiagnostic.cpp Line: 3442
    Image: C:\repos\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe
```

Intermittent when run locally.

**Comment by AndyAyersMS** [comment]
Repros more reliably with the "trick" of duplicating `System.Runtime.Numerics.Tests.dll` 4x on the command line.

Issue seems to be that if one of a loop head's non-loop predecessors is a switch and we create a preheader for the loop, that switch's desc map is now out of date. Fix should be simple...

cc @BruceForstall 

```
BB39  [0498]  2       BB38,BB80             0.00       1 10 [???..???)                                      internal Loop0 IBC 

BB40  [0047] 22       BB39,BB47,BB48(2),BB51,BB52(2),BB54,BB55,BB56,BB57,BB58,BB60,BB61,BB62,BB63,BB65,BB66,BB67,BB69,BB71,BB73  75.58  147078 11 [1FE..209)-> BB89  ( cond )                     i Loop Loop0 bwd IBC align 
BB41  [0048]  1       BB40                 28.43   55332 11 [209..21C)-> BB89  ( cond )                     i bwd IBC 
BB42  [0049]  1       BB41                 28.39   55238 11 [21C..225)-> BB89  ( cond )                     i bwd IBC 
BB43  [0007]  1       BB42                 28.39   55238 11 [055..05B)-> BB48  ( cond )                     i bwd bwd-target IBC 
BB44  [0012]  1       BB43                 27.14   52809 11 [0A9..0B2)-> BB65  ( cond )                     i bwd IBC 
BB45  [0013]  1       BB44                 27.12   52783 11 [0B2..0BB)-> BB68  ( cond )                     i bwd IBC 
BB46  [0014]  1       BB45                 23.05   44856 11 [0BB..0C4)-> BB84  ( cond )                     i bwd IBC 
BB47  [0015]  1       BB46                 23.05   44856 11 [0C4..0C9)-> BB40  (always)                     i bwd IBC 

BB48  [0008]  1       BB43                  1.25    2429 10 [05B..07D)-> BB61,BB55,BB40,BB83,BB40,BB61,BB49[def] (switch)                     i bwd IBC 

optHoistThisLoop for loop L11 <BB40..BB47>:
  Loop body does not contain a call
  Loop has multiple exits

  USEDEF  (6)={V16 V221 V18 V72 V71 V22}
  INOUT   (18)={V220 V16 V15 V12 V221 V18 V05 V09 V06 V17 V07 V04 V10 V13 V22 V219 V222 V11}
  LOOPVARS(4)={V16 V221 V18 V22}
  only considering hoisting in entry block BB40

    optHoistLoopBlocks BB40 (weight= 75.58) of loop L11 <BB40..BB47>
      [000080] not hoistable: unset
      [000074] not hoistable: local, not rvalue / not in SSA / defined within current loop
*************** In fgCreateLoopPreHeader for L11
   existing head BB39 isn't unique non-loop predecessor of loop entry
New Basic Block BB352 [0501] created.

;; Asserts checking the desc map for BB48 (expects to find BB40 in the successor list, but now it's BB352)....
```
Note the fact that `BB40` is also a switch isn't important -- the `BB48->BB40` edge is the troublemaker.

**Comment by AndyAyersMS** [comment]
Fix is simple:
```diff
@@ -7574,6 +7574,8 @@ void Compiler::fgCreateLoopPreHeader(unsigned lnum)
                         fgAddRefPred(preHead, predBlock);
                     }
                 } while (++jumpTab, --jumpCnt);
+
+                UpdateSwitchTableTarget(predBlock, entry, preHead);
                 break;
```

With the above in place, I'm now seeing a second test failure:
```
    System.Numerics.Tests.cast_toTest.RunSingleExplicitCastToBigIntegerTests [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: -0
      Actual:   0
                ↑ (pos 0)
      Stack Trace:
        C:\repos\runtime2\src\libraries\System.Runtime.Numerics\tests\BigInteger\cast_to.cs(685,0): at System.Numerics.Tests.cast_toTest.VerifySingleExplicitCastToBigInteger(Single value)
        C:\repos\runtime2\src\libraries\System.Runtime.Numerics\tests\BigInteger\cast_to.cs(248,0): at System.Numerics.Tests.cast_toTest.RunSingleExplicitCastToBigIntegerTests()
```

**Comment by AndyAyersMS** [comment]
Suspect this could be from static state carrying over from one set of the replicated test assembly to the next:
https://github.com/dotnet/runtime/blob/fc3875f14f310cdce716df30a94feb43db79a28a/src/libraries/System.Runtime.Numerics/tests/BigInteger/cast_to.cs#L14

So, second time around we find a random value that doesn't convert as expected?
