### ISSUE TITLE
Generation of dynamic types with multiple threads using System.Reflection.Emit components causes runtime corruption

### ISSUE THREAD

**Issue by ryanovic** [dotnet/runtime#64094]
### Description

`TypeBuilder` could throw a random exception when multiple instances, that are defined in the same `ModuleBuilder`, are generated in different threads. It seems like a dynamic module itself got corrupted. It happens on a fresh instance only, meaning in the code sample below, increasing a number of iteration doesn't increase probability of an error, if the root module is not re-initialized at the beginning.

### Reproduction Steps

``` c#
using System;
using System.IO;
using System.Reflection;
using System.Reflection.Emit;
using System.Threading.Tasks;

public class TestBase
{
    public readonly TextReader reader;

    public TestBase(TextReader reader)
    {
        this.reader = reader;
    }
}

public interface ITest
{
    string Test(int num);
}

public class Program
{
    private static object syncroot = new object();
    private const int N = 10;

    public static void Main()
    {
        try
        {
            for (int step = 0; ; step++)
            {
                var assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("test" + step.ToString()), AssemblyBuilderAccess.Run);
                var module = assembly.DefineDynamicModule("test" + step++.ToString());
                var types = new Type[N];

                Console.Write(step.ToString() + '\r');

                Parallel.For(0, N, (i) =>
                {
                    TypeBuilder tb;

                    lock (syncroot) 
                    {
                        tb = module.DefineType("test_" + i.ToString(), TypeAttributes.Public, typeof(TestBase), new[] { typeof(ITest) });
                    }

                    MethodBuilder mb;

                    // The following lock sections commented are enough to workaroud the issue.
                    // Basically an error occurs when a new assembly reference is internally added in the assembly builder.
                    // Note, each thread is working with its own TypeBuilder, no shared  context, except the initial DefineType call.
                    
                    //lock (syncroot)
                    {
                        mb = tb.DefineMethod("Test", MethodAttributes.Public | MethodAttributes.Virtual, typeof(string), new[] { typeof(int) });
                    }

                    var il = mb.GetILGenerator();
                    var label = il.DefineLabel();

                    for (int j = 0; j < 50; j++)
                    {
                        il.Emit(OpCodes.Ldarg_0);
                        il.Emit(OpCodes.Ldc_I4, j);
                        il.Emit(OpCodes.Bne_Un, label);

                        il.Emit(OpCodes.Ldstr, j.ToString());
                        il.Emit(OpCodes.Ret);

                        il.MarkLabel(label);
                        label = il.DefineLabel();
                    }

                    il.MarkLabel(label);
                    il.Emit(OpCodes.Ldnull);
                    il.Emit(OpCodes.Ret);

                    ConstructorBuilder cb;

                    //lock (syncroot)
                    {
                        cb = tb.DefineConstructor(MethodAttributes.Public, CallingConventions.Standard, new[] { typeof(TextReader) });
                    }

                    il = cb.GetILGenerator();
                    il.Emit(OpCodes.Ldarg_0);
                    il.Emit(OpCodes.Ldarg_1);

                    //lock (syncroot)
                    {
                        il.Emit(OpCodes.Call, typeof(TestBase).GetConstructor(new[] { typeof(TextReader) }));
                    }

                    il.Emit(OpCodes.Ret);

                    types[i] = tb.CreateType();

                });
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }
    }
}

```

### Expected behavior

TypeBuilder instances manage their internal shared context in a thread-safe manner.

### Actual behavior

Examples of exception types could be thrown, though, seems, their just indicates a corrupted state : 

_System.BadImageFormatException_: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Reflection.Emit.ModuleBuilder.GetMemberRefOfMethodInfo(QCallModule module, Int32 tr, RuntimeMethodHandleInternal method)
   
_Fatal error. Internal CLR error._ (0x80131506)
   at System.Reflection.Emit.TypeBuilder.DefineType(System.Runtime.CompilerServices.QCallModule, System.String, Int32, System.Reflection.TypeAttributes, Int32, Int32[])
   
_System.TypeLoadException_: The signature is incorrect.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()

### Configuration

Reproduced with .Net Core 3.1, .Net 5, .Net 6
Windows 10, x64

**Comment by steveharter** [comment]
I wouldn't expect the Emit code to be thread-safe, and it is not documented to be. However, was not able to repro the threading issue on .NET Framework 4.7.2, so we do research to see why that is the case.

**Comment by ryanovic** [comment]
However, this is still confusing because the common module's metadata is used internally and no thread accesses shared data directly.

**Comment by steveharter** [comment]
It makes sense to assign this to 7.0 for further research or a fix.

**Comment by madelson** [comment]
> I wouldn't expect the Emit code to be thread-safe, and it is not documented to be

I think it would be helpful if it were thread-safe, because otherwise you can't lazily instantiate new types into your dynamic assembly as you need them.

**Comment by steveharter** [comment]
Moving to 9; seems important to investigate\fix.
