### ISSUE TITLE
JsonSerializerContext source generation fails with keyword identifiers

### ISSUE THREAD

**Issue by jzebedee** [dotnet/runtime#64159]
### Description

When a type containing a keyword identifier (e.g., `@base`) is used with `JsonSerializerContext`'s source generation, compilation fails with several errors:

```
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(55,78,55,82): error CS1001: Identifier expected
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(55,78,55,82): error CS1003: Syntax error, ',' expected
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(56,85,56,89): error CS1001: Identifier expected
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(56,85,56,89): error CS1003: Syntax error, ',' expected
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(119,53,119,57): error CS1001: Identifier expected
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(119,53,119,57): error CS1003: Syntax error, ',' expected
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(55,78,55,82): error CS1511: Keyword 'base' is not available in a static method
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(55,78,55,82): error CS0747: Invalid initializer member declarator
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(56,49,56,85): error CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(56,85,56,89): error CS1511: Keyword 'base' is not available in a static method
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(56,92,56,97): error CS0103: The name 'value' does not exist in the current context
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(56,85,56,98): error CS0747: Invalid initializer member declarator
1>System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\CK3JsonContext.Weight.g.cs(119,53,119,57): error CS1511: Keyword 'base' is not available in a static method
```

### Reproduction Steps

Define a type that includes a keyword identifier:

```csharp
public class Weight
{
    public int @base { get; set; }
    public int current { get; set; }
    public int target { get; set; }
}
```

and add it to a `JsonSerializerContext`:

```csharp
[JsonSerializable(typeof(Weight))]
internal partial class CK3JsonContext : JsonSerializerContext
{
}
```

### Expected behavior

Either source generation succeeds, or an error that keyword identifiers are not supported is emitted 

### Actual behavior

Generated source gets mangled and breaks compilation in an opaque way

**Comment by pinkfloydx33** [comment]
Think this is the same as  https://github.com/dotnet/runtime/issues/60968

**Comment by layomia** [comment]
Marking up-for-grabs; similar fix in https://github.com/dotnet/runtime/pull/64663.

**Comment by SteveDunn** [comment]
Hi - I'm happy to look at this one

**Comment by jeffhandley** [comment]
Thanks, @SteveDunn! I'll assign it to you. 🙂

**Comment by SteveDunn** [comment]
@layomia - I just read your blog to get me familiar with STJ sourcegen. I noticed an issue:

![image](https://user-images.githubusercontent.com/263416/155870900-c68bd266-c7dd-4719-baab-9f79b6590ac9.png)

I think that should be `JsonSourceGenerationOptions`

Great post though - thank you very much.

**Comment by SteveDunn** [comment]
I started looking at this, but I'm rather blocked at the moment as I simply cannot get the latest VS 2022 preview to debug any tests.

I see this in the output window in VS:

```
========== Starting test discovery ==========
Aborting test discovery because a test run was requested.
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Failed to negotiate protocol, waiting for response timed out after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TestRequestSender.CheckVersionWithTestHost()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
========== Test discovery aborted: 0 Tests found in 1.7 min ==========
Building Test Projects
Targeting test method: System.Text.Json.SourceGeneration.Tests.SerializationContextTests.EnsureFastPathGeneratedAsExpected
Starting test discovery for requested test run
Using automatically detected runsettings file(s). To learn more visit https://aka.ms/vs-runsettings.
Failed to configure settings for runsettings plugin 'BoostTestInternalSettings' as it threw following exception:
'Cannot deserialize type 'Microsoft.VisualStudio.TestPlatform.ObjectModel.TestRunSettings' because it contains property 'Name' which has no public setter.'
Please contact the plugin author.
========== Starting test discovery ==========
[xUnit.net 00:00:00.38] xUnit.net VSTest Adapter v2.4.2+2d84eb3141 (64-bit .NET 7.0.0-dev)
[xUnit.net 00:00:37.60]   Discovering: System.Text.Json.SourceGeneration.Roslyn4.0.Tests (method display = ClassAndMethod, method display options = None)
```

I have followed the instructions at: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/visualstudio.md#test-explorer

... but to no avail.
