### ISSUE TITLE
Test failure Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64172]
Run: [runtime-coreclr outerloop 20220123.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1567669&view=ms.vss-test-web.build-test-results-tab&runId=44076376&paneView=debug&resultId=100720)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd

R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_Disabled_NativeAssemblyDisabled.cmd
- Interop\\DisabledRuntimeMarshalling\\DisabledRuntimeMarshalling_NativeAssemblyDisabled\\DisabledRuntimeMarshalling_NativeAssemblyDisabled.cmd
```
**Error message:**
```
Could Not Find D:\h\w\A30908AB\w\A25508F4\e\Interop\DisabledRuntimeMarshalling\DisabledRuntimeMarshalling_NativeAssemblyDisabled\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\A30908AB\w\A25508F4\e\Interop\DisabledRuntimeMarshalling\DisabledRuntimeMarshalling_NativeAssemblyDisabled\DisabledRuntimeMarshallingNative.dll.rsp
Could Not Find D:\h\w\A30908AB\w\A25508F4\e\Interop\DisabledRuntimeMarshalling\DisabledRuntimeMarshalling_NativeAssemblyDisabled\DisabledRuntimeMarshallingNative_DisabledMarshalling.dll.rsp
Could Not Find D:\h\w\A30908AB\w\A25508F4\e\Interop\DisabledRuntimeMarshalling\DisabledRuntimeMarshalling_NativeAssemblyDisabled\DisabledRuntimeMarshalling_NativeAssemblyDisabled.dll.rsp
Unhandled exception. System.AggregateException: One or more errors occurred. (Code generation failed for method '[DisabledRuntimeMarshalling_NativeAssemblyDisabled]DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingDisabled.PInvokes+<>c.<Varargs_NotSupported>b__6_0()')
---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[DisabledRuntimeMarshalling_NativeAssemblyDisabled]DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingDisabled.PInvokes+<>c.<Varargs_NotSupported>b__6_0()'
---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl()
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType()
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignatureImpl(Boolean skipEmbeddedSignatureData)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignatureInternal(Boolean skipEmbeddedSignatureData)
at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseMethodSignature()
at Internal.TypeSystem.Ecma.EcmaModule.ResolveMemberReference(MemberReferenceHandle handle)
at Internal.TypeSystem.Ecma.EcmaModule.EcmaObjectLookupHashtable.CreateValueFromKey(EntityHandle handle)
at Internal.TypeSystem.LockFreeReaderHashtable2.CreateValueAndEnsureValueIsInTable(TKey key) at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle handle, NotFoundBehavior notFoundBehavior) at Internal.IL.EcmaMethodIL.GetObject(Int32 token, NotFoundBehavior notFoundBehavior) at Internal.JitInterface.CorInfoImpl.ResolveTokenInScope(MethodILScope methodIL, Object typeOrMethodContext, mdToken token) at Internal.JitInterface.CorInfoImpl.resolveToken(CORINFO_RESOLVED_TOKEN& pResolvedToken) at Internal.JitInterface.CorInfoImpl._resolveToken(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken) --- End of inner exception stack trace --- at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(DependencyNodeCore1 dependency)
at System.Threading.Tasks.Parallel.<>c__DisplayClass33_02.<ForEachWorker>b__0(Int32 i) at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) at System.Threading.Tasks.TaskReplicator.Replica.Execute() --- End of inner exception stack trace --- at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction1 action, ParallelOptions options, Boolean stopOnFirstFailure)
at System.Threading.Tasks.Parallel.ForWorker[TL


Stack trace
   at Interop_DisabledRuntimeMarshalling._DisabledRuntimeMarshalling_NativeAssemblyDisabled_DisabledRuntimeMarshalling_NativeAssemblyDisabled_._DisabledRuntimeMarshalling_NativeAssemblyDisabled_DisabledRuntimeMarshalling_NativeAssemblyDisabled_cmd()
```

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/interop-contrib This looks like something new.
