### ISSUE TITLE
[mono] Failing arm64 LLVM FullAOT tests

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#64179]
- [x] JIT/SIMD/VectorExp_ro/VectorExp_ro
- [ ] JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r

```
  Discovering: JIT.Intrinsics.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Intrinsics.XUnitWrapper (found 23 test cases)
  Starting:    JIT.Intrinsics.XUnitWrapper (parallel test collections = on, max threads = 4)
  Finished:    JIT.Intrinsics.XUnitWrapper
  Discovering: JIT.SIMD.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.SIMD.XUnitWrapper (found 99 test cases)
  Starting:    JIT.SIMD.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT/SIMD/VectorExp_ro/VectorExp_ro.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorExp_ro/VectorExp_ro.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorExp_ro.dll ''
      Failed Int64
        sum: [ 1, 25 ]
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_SIMD._VectorExp_ro_VectorExp_ro_._VectorExp_ro_VectorExp_ro_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorExp_ro/VectorExp_ro.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorExp_ro.dll ''
        Failed Int64
          sum: [ 1, 25 ]
        Expected: 100
        Actual: 255
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
  Finished:    JIT.SIMD.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Intrinsics.XUnitWrapper  Total:  23, Errors: 0, Failed: 0, Skipped: 0, Time: 1.091s
   JIT.SIMD.XUnitWrapper        Total:  99, Errors: 0, Failed: 1, Skipped: 0, Time: 3.866s
                                       ---          -          -           -        ------
                          GRAND TOTAL: 122          0          1           0        4.957s (5.302s)
```

```
  Discovering: JIT.HardwareIntrinsics.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.HardwareIntrinsics.XUnitWrapper (found 6 of 354 test cases)
  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_r.dll ''
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_HardwareIntrinsics._Arm_ArmBase_Yield_r_Yield_r_._Arm_ArmBase_Yield_r_Yield_r_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_r.dll ''
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh
    JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_ro.dll ''
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_HardwareIntrinsics._Arm_ArmBase_Yield_ro_Yield_ro_._Arm_ArmBase_Yield_ro_Yield_ro_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_ro.dll ''
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh
  Finished:    JIT.HardwareIntrinsics.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.HardwareIntrinsics.XUnitWrapper  Total: 6, Errors: 0, Failed: 2, Skipped: 0, Time: 0.749s
```

**Comment by SamMonoRT** [comment]
moving to 8.0.0

**Comment by fanyang-mono** [comment]
cc: @matouskozak
