### ISSUE TITLE
Validator.TryValidateObject on JObject throws System.ArgumentException

### ISSUE THREAD

**Issue by lhotamir** [dotnet/runtime#64207]
### Description

When a JObject class object is validated by System.ComponentModel.DataAnnotations.Validator ArgumentException is thrown.

### Reproduction Steps

```
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json.Linq;

namespace JObjectTest
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var data = JObject.Parse("{\"Enabled\":true}");

            var results = new List<ValidationResult>();

            var r = Validator.TryValidateObject(data, new (data), results, true);
        }
    }
}
```

### Expected behavior

TryValidate should return true and no validation error are produced.

### Actual behavior

Following exception is thrown:
```
Unhandled exception. System.ArgumentException: The type 'JObject' does not contain a public property named 'Enabled'. (Parameter 'propertyName')
   at System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.GetPropertyStoreItem(String propertyName)
   at System.ComponentModel.DataAnnotations.ValidationAttributeStore.GetPropertyValidationAttributes(ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.GetPropertyValues(Object instance, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.TryValidateObject(Object instance, ValidationContext validationContext, ICollection`1 validationResults, Boolean validateAllProperties)
   at JObjectTest.Program.Main(String[] args) in ...\Program.cs:line 15
```

### Regression?

Provided example is working with .NET 5.

### Configuration

.NET 6, x64, Windows 10

**Comment by enriqueraso** [comment]
Any updates on this issue? I upgraded a solution from .NET 5 to .NET 6, and same issue popped up.

**Comment by enriqueraso** [comment]
The exception is thrown GetPropertyValidationAttributes method inside GetPropertyValues. in Validator class.

This is the code of GetPropertyValues in .NET 5

```
private static ICollection<KeyValuePair<ValidationContext, object>> GetPropertyValues(object instance, ValidationContext validationContext)
{
   IEnumerable<PropertyInfo> enumerable = from p in instance.GetType().GetRuntimeProperties()
   									   where ValidationAttributeStore.IsPublic(p) && !p.GetIndexParameters().Any()
   									   select p;
   
   List<KeyValuePair<ValidationContext, object>> list = new List<KeyValuePair<ValidationContext, object>>(enumerable.Count());
   
   foreach (PropertyInfo item in enumerable)
   {
      ValidationContext validationContext2 = CreateValidationContext(instance, validationContext);
      validationContext2.MemberName = item.Name;
      if (_store.GetPropertyValidationAttributes(validationContext2).Any())
      {
         list.Add(new KeyValuePair<ValidationContext, object>(validationContext2, item.GetValue(instance, null)));
      }
   }
   return list;
}
```

And this is the new code in .NET 6

```
private static ICollection<KeyValuePair<ValidationContext, object>> GetPropertyValues(object instance, ValidationContext validationContext)
{
   var properties = TypeDescriptor.GetProperties(instance);
   List<KeyValuePair<ValidationContext, object>> list = new List<KeyValuePair<ValidationContext, object>>(properties.Count);

   foreach (PropertyDescriptor item in properties)
   {
      ValidationContext validationContext2 = CreateValidationContext(instance, validationContext);
      validationContext2.MemberName = item.Name;
      if (_store.GetPropertyValidationAttributes(validationContext2).Any())
      {
         list.Add(new KeyValuePair<ValidationContext, object>(validationContext2, item.GetValue(instance)));
      }
   }
   return list;
}
``` 

Maybe in .NET 6 is correct that properties contains the list of properties of the instance, instead of the list of runtime properties, but now GetPropertyValidationAttributes or CreateValidationContext are not correct.

You can reproduce the issue in .NET 5 using `var properties = TypeDescriptor.GetProperties(instance);`.

**Comment by enriqueraso** [comment]
@ajcvickers, in which .net version is this issue included? I tested with 6.0302 and it stills happen.

![image](https://user-images.githubusercontent.com/16336745/182403339-238f15d2-7fcd-465a-b71f-f5a29e32de4c.png)

**Comment by ajcvickers** [comment]
@enriqueraso As the milestone indicates, it will be included in .NET 7.

**Comment by barry-bvl** [comment]
@ajcvickers Will such regression not be solved in a LTS as .NET 6 as well?

**Comment by barry-bvl** [comment]
> @ajcvickers Will such regression not be solved in a LTS as .NET 6 as well?

Any update on this question @ajcvickers, @bricelam

**Comment by ajcvickers** [comment]
@barry-bvl We don't have any plans to patch this in 6.0. Calling Validate on this object will never do anything anyway, so the workaround, which is likely the more correct thing to do anyway, is not call Validate.
