### ISSUE TITLE
PlatformNotSupportedException FileInfo_ReadRights_WithSecurity FileInfo_WriteRights_WithSecurity

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#64221]
The following are failing with PNSE on Windows Release x64 Mono:
FileInfo_ReadRights_WithSecurity_Custom
FileInfo_ReadRights_WithSecurity_Default
FileInfo_ReadRights_WithSecurity_Null
FileInfo_WriteRights_WithSecurity_Custom
FileInfo_WriteRights_WithSecurity_Default
FileInfo_WriteRights_WithSecurity_Null

Example StackTrace:
```
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.PlatformNotSupported.cs(24,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
        /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs(184,0): at Microsoft.Win32.SafeHandles.SafeFileHandle.InitThreadPoolBinding()
        /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs(164,0): at Microsoft.Win32.SafeHandles.SafeFileHandle.<EnsureThreadPoolBindingInitialized>g__Init|27_0()
        /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs(155,0): at Microsoft.Win32.SafeHandles.SafeFileHandle.EnsureThreadPoolBindingInitialized()
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs(24,0): at System.IO.Strategies.OSFileStreamStrategy..ctor(SafeFileHandle handle, FileAccess access)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/AsyncWindowsFileStreamStrategy.cs(13,0): at System.IO.Strategies.AsyncWindowsFileStreamStrategy..ctor(SafeFileHandle handle, FileAccess access)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.Windows.cs(30,0): at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(SafeFileHandle handle, FileAccess access, Boolean isAsync)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.cs(16,0): at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, SafeFileHandle handle, FileAccess access, Int32 bufferSize, Boolean isAsync)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs(117,0): at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access, Int32 bufferSize, Boolean isAsync)
        /_/src/libraries/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.cs(230,0): at System.IO.FileSystemAclExtensions.Create(FileInfo fileInfo, FileMode mode, FileSystemRights rights, FileShare share, Int32 bufferSize, FileOptions options, FileSecurity fileSecurity)
        /_/src/libraries/System.IO.FileSystem.AccessControl/tests/FileSystemAclExtensionsTests.cs(645,0): at System.IO.FileSystemAclExtensionsTests.Verify_FileSecurity_CreateFile(FileMode mode, FileSystemRights rights, FileShare share, Int32 bufferSize, FileOptions options, FileSecurity expectedSecurity)
        /_/src/libraries/System.IO.FileSystem.AccessControl/tests/FileSystemAclExtensionsTests.cs(442,0): at System.IO.FileSystemAclExtensionsTests.FileInfo_ReadRights_WithSecurity_Null(FileMode mode, FileSystemRights rights, FileShare share, FileOptions options)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs(386,0): at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1568796&view=logs&j=585f1246-0618-5d47-ff3e-08c83309e2d2&t=5e10daf8-cc46-5bd4-2ab7-d28eafd857b5

Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64028-merge-4f3b2bd228964535b0/System.IO.FileSystem.AccessControl.Tests/1/console.63c013e7.log?sv=2019-07-07&se=2022-02-13T17%3A17%3A57Z&sr=c&sp=rl&sig=ugkagw0HlCZqJ3mWV82y076C%2FJ2xn7PJDeEjwCB3HEw%3D

**Comment by mdh1418** [comment]
Also hit on https://github.com/dotnet/runtime/pull/63949
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1568813&view=logs&j=585f1246-0618-5d47-ff3e-08c83309e2d2&t=5e10daf8-cc46-5bd4-2ab7-d28eafd857b5

**Comment by danmoseley** [comment]
@adamsitnik just curious, why does the implementation of FileSystemAclExtensions choose to pass FileOptions.Asynchronous? Presumably if it didn't, these would work on Mono.

**Comment by adamsitnik** [comment]
> just curious, why does the implementation of FileSystemAclExtensions choose to pass FileOptions.Asynchronous?

@danmoseley Afair when @carlossanlop was working on #61297 he has identified few product bugs and also some test gaps. To make sure that there are no more gaps Carlos added tests with all possible permutations of input arguments (`FileOptions`, `FileMode` etc).

So the tests don't focus on async IO itself, but just on testing all possible combinations of input (and some of them use `FileOptions.Asynchronous`).
