### ISSUE TITLE
With .NET 7 SDK, create razor project failed with error when running PerfView

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#64263]
Repro steps:
1. Install .NET 7 SDK:7.0.100-alpha.1.22062.5 from https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe
2. Download PerfView from https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md 
3. Start data collection by running.  It will ask for elevation (grant it) It should bring up a dialog box that shows that it is collecting data.   
PerfView /merge:false collect 	 
4. Create a new razor project 

Expected result:
The Razor project should be created successfully.

Actually Result:
The following error occured when creating razor project.
![image](https://user-images.githubusercontent.com/87680983/149292418-c8ea444f-051d-4c4b-afb4-7bcb69c52f67.png)
```
C:\Users\v-wenjj>dotnet new razor -o r1
Fatal error. Internal CLR error. (0x80131506)
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Linq.JsonLoadSettings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Linq.JsonLoadSettings)
   at Newtonsoft.Json.Linq.JObject.Load(Newtonsoft.Json.JsonReader, Newtonsoft.Json.Linq.JsonLoadSettings)
   at Microsoft.TemplateEngine.JExtensions.ReadObject(Microsoft.TemplateEngine.Abstractions.PhysicalFileSystem.IPhysicalFileSystem, System.String)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22, Microsoft.TemplateEngine.Edge, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<UpdateTemplateCacheAsync>d__22 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<UpdateTemplateCacheAsync>d__22, Microsoft.TemplateEngine.Edge, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<UpdateTemplateCacheAsync>d__22 ByRef)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager.UpdateTemplateCacheAsync(Boolean, System.Threading.CancellationToken)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatesAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatesAsync>d__16, Microsoft.TemplateEngine.Edge, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<GetTemplatesAsync>d__16 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager+<GetTemplatesAsync>d__16, Microsoft.TemplateEngine.Edge, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<GetTemplatesAsync>d__16 ByRef)
   at Microsoft.TemplateEngine.Edge.Settings.TemplatePackageManager.GetTemplatesAsync(System.Threading.CancellationToken)
   at Microsoft.TemplateEngine.Cli.TemplateResolution.BaseTemplateResolver+<GetTemplateGroupsAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Cli.TemplateResolution.BaseTemplateResolver+<GetTemplateGroupsAsync>d__10, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<GetTemplateGroupsAsync>d__10 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Cli.TemplateResolution.BaseTemplateResolver+<GetTemplateGroupsAsync>d__10, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<GetTemplateGroupsAsync>d__10 ByRef)
   at Microsoft.TemplateEngine.Cli.TemplateResolution.BaseTemplateResolver.GetTemplateGroupsAsync(System.Threading.CancellationToken)
   at Microsoft.TemplateEngine.Cli.TemplateResolution.InstantiateTemplateResolver+<ResolveTemplatesAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Cli.TemplateResolution.InstantiateTemplateResolver+<ResolveTemplatesAsync>d__8, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ResolveTemplatesAsync>d__8 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.TemplateEngine.Cli.TemplateResolution.InstantiateTemplateResolver+<ResolveTemplatesAsync>d__8, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ResolveTemplatesAsync>d__8 ByRef)
   at Microsoft.TemplateEngine.Cli.TemplateResolution.InstantiateTemplateResolver.ResolveTemplatesAsync(Microsoft.TemplateEngine.Cli.CommandParsing.INewCommandInput, System.String, System.Threading.CancellationToken)
   at Microsoft.TemplateEngine.Cli.TemplateInvocationCoordinator+<CoordinateInvocationAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Cli.TemplateInvocationCoordinator+<CoordinateInvocationAsync>d__10, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<CoordinateInvocationAsync>d__10 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.TemplateEngine.Cli.New3CommandStatus, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].Start[[Microsoft.TemplateEngine.Cli.TemplateInvocationCoordinator+<CoordinateInvocationAsync>d__10, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<CoordinateInvocationAsync>d__10 ByRef)
   at Microsoft.TemplateEngine.Cli.TemplateInvocationCoordinator.CoordinateInvocationAsync(Microsoft.TemplateEngine.Cli.CommandParsing.INewCommandInput, System.Threading.CancellationToken)
   at Microsoft.TemplateEngine.Cli.New3Command+<EnterTemplateManipulationFlowAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Cli.New3Command+<EnterTemplateManipulationFlowAsync>d__21, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<EnterTemplateManipulationFlowAsync>d__21 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.TemplateEngine.Cli.New3CommandStatus, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].Start[[Microsoft.TemplateEngine.Cli.New3Command+<EnterTemplateManipulationFlowAsync>d__21, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<EnterTemplateManipulationFlowAsync>d__21 ByRef)
   at Microsoft.TemplateEngine.Cli.New3Command.EnterTemplateManipulationFlowAsync(Microsoft.TemplateEngine.Cli.CommandParsing.INewCommandInput)
   at Microsoft.TemplateEngine.Cli.New3Command+<ExecuteAsync>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.TemplateEngine.Cli.New3Command+<ExecuteAsync>d__22, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__22 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.TemplateEngine.Cli.New3CommandStatus, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].Start[[Microsoft.TemplateEngine.Cli.New3Command+<ExecuteAsync>d__22, Microsoft.TemplateEngine.Cli, Version=7.0.100.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__22 ByRef)
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync(Microsoft.TemplateEngine.Cli.CommandParsing.INewCommandInput)
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

```

Dotnet --info:
C:\Users\v-wenjj>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   7.0.100-alpha.1.22062.5
 Commit:    62d1c5edb1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-alpha.1.22062.5\

Host (useful for support):
  Version: 7.0.0-alpha.1.22061.11
  Commit:  ef7ff07109

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.22055.15 [C:\Program Files\dotnet\sdk]
  7.0.100-alpha.1.22062.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-alpha.1.22062.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-alpha.1.22061.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-alpha.1.22061.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jeffschwMSFT** [comment]
Did this build contain the GC regions work that we reverted?  Does today's daily build have this same issue?

cc @mangod9

**Comment by mangod9** [comment]
Yeah based on this commit `ef7ff07` this build should have GC Regions enabled, which are now disabled in Preview1. 

FYI @cshung. We will investigate before enabling.

**Comment by trylek** [comment]
Based on @cshung's suggestion I have investigated why we're globally turning on the potentially expensive option <code>ShouldTrackSurvivorsForProfilerOrEtw</code> that is making the runtime tests vulnerable to the GC bug tracked in this issue. I have landed in this place:

https://github.com/dotnet/runtime/blob/1043f003c2b6e404014845e42d25513cebe2b9d9/src/tests/run.sh#L219

I'm not sure how to go on from here - @hoyosjs, do you have any suggestions? At a first glance I would speculate that we only need this logic for those tests that actually exercise event logging, for others it's mere busywork at the expense of more complicated GC. I'm also guessing that the specific nature of this particular setting is what ultimately makes r2r_extra pipelines pass on Windows but fail left and right on both Linux and OSX.

Thanks

Tomas

**Comment by hoyosjs** [comment]
I am relatively surprised `COMPlus_EnableEventLog` is needed at all (cc: @dotnet/dotnet-diag). I doubt any test uses LTTNG and event pipe should automatically. LTTNG is also relatively expensive... I'd say runtests should have this disabled by default and the flag should be a positive ( --enableEventLogging -> eventLogging = 1 -> `COMPlus_EnableEventLog=1`) to make it pay for play.

**Comment by WenJunJi01** [comment]
This issue still reproduces with .NET 7 Preview 4 from main branch of https://github.com/dotnet/installer.
![image](https://user-images.githubusercontent.com/87680983/163552714-1d25d2cb-38b0-47df-8401-2566526ed1de.png)
Dotnet info:
![image](https://user-images.githubusercontent.com/87680983/163552944-685953ba-bb03-4184-94d1-19c807ff91fd.png)

**Comment by cshung** [comment]
> This issue still reproduces with .NET 7 Preview 4 from main branch of https://github.com/dotnet/installer. 

My fix missed preview 4, that is why it is still reproducing there.

My fix was made on the 12th of April
```
commit 537a547f74287a625055b0a57dc29ff548edb176
Author: Andrew Au <andrewau@microsoft.com>
Date:   Tue Apr 12 17:54:16 2022 -0700

    Skip SIP in walk_relocation (#67889)
```

And preview 4 was using the commit from the 11th of April.
```
commit 5707668eac999163740e42c70f228772e6bc3680
Author: Jeremy Koritzinsky <jekoritz@microsoft.com>
Date:   Mon Apr 11 21:54:37 2022 -0700

    Code fix to add DisableRuntimeMarshalling when required (#67676)
```

**Comment by WenJunJi01** [comment]
Verified with .NET 7 Preview 4 SDK: 7.0.100-preview.4.22218.29(runtime-7.0.0-preview.4.22217.5) today, detailed test results:
EN and DE language -> Not repro
SC language-> Repro

We will continue to track this issue. One more question, do I need to open a new bug to track the problem with .NET 7 Preview 4?

**Comment by cshung** [comment]
@WenJunJi01, can you check the commit of the SC language build you used?
If it happened after the fix, we should reopen this issue and investigate.

**Comment by WenJunJi01** [comment]
@cshung Yesterday we installed the .NET 7 Preview 4 SDK from https://github.com/dotnet/installer on a machine with SC language(image: Windows-11-Enterprise-21H2-ZH-CN) and it can repro.
![image](https://user-images.githubusercontent.com/87680983/164202299-f1007fa3-72f0-4789-937a-34dbf52ce2ad.png)

But today I installed the latest version of perfview on a clean win11-SC machine to verify again, this issue can not repro. We also checked it on TK and JP environment and neither reproduced.
![image](https://user-images.githubusercontent.com/87680983/164205513-85b99890-3ced-48f0-9aa4-b4dc833275ed.png)

**Comment by cshung** [comment]
@WenJunJi01, can you share with me the output of `dotnet --info`?

**Comment by WenJunJi01** [comment]
@cshung 
**Dotnet info:**
C:\Users\v-wenjj>dotnet --info
.NET SDK (反映任何 global.json):
 Version:   7.0.100-preview.4.22219.19
 Commit:    2a412d3454

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.4.22219.19\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.4.22217.5
  Architecture: x64
  Commit:       74e1d4df57

.NET SDKs installed:
  7.0.100-preview.4.22219.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.4.22218.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.4.22217.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.4.22217.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by cshung** [comment]
@WenJunJi01
This build definitely contains the fix - it must be the case that something else is broken.
Can you try to capture a dump when the crash happens?

**Comment by WenJunJi01** [comment]
@cshung  Here is the dump file created on .NET Host. Since the file cannot be uploaded, the path is provided.

\\bvtsrv2\team\E2E\dump.zip

**Comment by cshung** [comment]
@WenJunJi01 
The dump is fairly normal, most threads are waiting, but thread 10 is still running some JSON stuff.
No exceptions, no deadlock, what is wrong with that?

**Comment by WenJunJi01** [comment]
Sorry I'm not very clear either. I'll keep watching to see if this problem reappears in future tests.
