### ISSUE TITLE
[wasm][debugger] Tests randomly fail with `The tasks argument included a null value. (Parameter 'tasks')`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64588]
Debugger tests randomly fail on the CI with this:

```
DevToolsProxy::Run: Exception System.ArgumentException: The tasks argument included a null value. (Parameter 'tasks')
    at System.Threading.Tasks.Task.WhenAny(Task[] tasks)
    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket) in /_/src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs:line 269
```

**Comment by radical** [comment]
Should be fixed by #65752 .
