### ISSUE TITLE
Connecting a Blazor Client app to an Azure Service Bus?

### ISSUE THREAD

**Issue by dkboon01** [dotnet/runtime#64620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to create a client to azure service bus message queue, I get this error crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.Security.Cryptography.Algorithms is not supported on this platform.
System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
   at System.Security.Cryptography.HMACSHA256..ctor(Byte[] key)
   at Azure.Messaging.ServiceBus.Authorization.SharedAccessSignature.BuildSignature(String audience, String sharedAccessKeyName, String sharedAccessKey, DateTimeOffset expirationTime)
   at Azure.Messaging.ServiceBus.Authorization.SharedAccessSignature..ctor(String serviceBusResource, String sharedAccessKeyName, String sharedAccessKey, Nullable`1 signatureValidityDuration)
   at Azure.Messaging.ServiceBus.ServiceBusConnection..ctor(String connectionString, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String connectionString, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String connectionString)
   at ABCBlazor.ServiceBusReceiver.SBReceiverConnect() in C:\Users\dboone\source\repos\ABCApps\ABCBlazor\ServiceBusReceiver.cs:line 16
   at ABCBlazor.Pages.Test.ReadServiceBus() in C:\Users\dboone\source\repos\ABCApps\ABCBlazor\Pages\Test.razor:line 11
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### Expected Behavior

Is there another security package besides System.Security.Cryptography.Algorithms that I can use to make this connection or a different work around to get messages from the Azure Service Bus?

### .NET Version

6.0.101

**Comment by vcsjones** [comment]
This is likely caused by https://github.com/dotnet/runtime/issues/40074 not being implemented.

The Message Bus SDK is using `System.Security.Cryptography.HMACSHA256` but that type is not available in WASM / Browsers.

> a different work around to get messages from the Azure Service Bus?

Since the SDK depends on `System.Security.Cryptography.HMACSHA256`, there is no way to replace it with another implementation.
