### ISSUE TITLE
[mono][arm6][linux]  System.Net.Tests.ServicePointManagerTest.FindServicePoint_Collectible failed.

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#64674]
```
Unhandled Exception:
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: True
Actual:   False
   at Xunit.Assert.Equal[Boolean](Boolean expected, Boolean actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 101
   at Xunit.Assert.Equal[Boolean](Boolean expected, Boolean actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63
   at System.Net.Tests.ServicePointManagerTest.<>c.<FindServicePoint_Collectible>b__15_0() in /_/src/libraries/System.Net.ServicePoint/tests/ServicePointManagerTest.cs:line 300
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
[ERROR] FATAL UNHANDLED EXCEPTION: Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: True
Actual:   False
   at Xunit.Assert.Equal[Boolean](Boolean expected, Boolean actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 101
   at Xunit.Assert.Equal[Boolean](Boolean expected, Boolean actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63
   at System.Net.Tests.ServicePointManagerTest.<>c.<FindServicePoint_Collectible>b__15_0() in /_/src/libraries/System.Net.ServicePoint/tests/ServicePointManagerTest.cs:line 300
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Net.Tests.ServicePointManagerTest.FindServicePoint_Collectible [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: True
        Actual:   False
        /_/src/libraries/System.Net.ServicePoint/tests/ServicePointManagerTest.cs(300,0): at System.Net.Tests.ServicePointManagerTest.<>c.<FindServicePoint_Collectible>b__15_0()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs(386,0): at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
        
        Child process:
          System.Net.ServicePoint.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Tests.ServicePointManagerTest+<>c Void <FindServicePoint_Collectible>b__15_0()
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ffb54b76a5e94879a8/System.Net.ServicePoint.Tests/3/console.15d816b9.log?sv=2019-07-07&se=2022-02-22T07%3A41%3A16Z&sr=c&sp=rl&sig=QSvkd91GeAqjkqrhO2rZ%2FhCS9MfDKzYibPnftrSQ8No%3D

cc @directhex @steveisok

**Comment by steveisok** [comment]
This is going to require RemoteExecutor support in order to work.  It's unknown if / when we'll get to that for mobile.

**Comment by wfurt** [comment]
ServicePointManager is obsolete. I would do anything expensive to make it pass. If this depends on `RemoteExecutor` I would open single tracking issue instead of tracing each single test failure.

**Comment by jkotas** [comment]
Fixed by #115129
