### ISSUE TITLE
Native crash in `System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64719]
`Libraries Test Run release mono Linux arm64 Debug`:
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1588536&view=logs&jobId=3f95ca23-483b-5dc9-4b05-6bd24fb925c2&j=3f95ca23-483b-5dc9-4b05-6bd24fb925c2&t=0c1dd9d1-4ef7-54d5-2d62-e4ab330605ca), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64695-merge-809da69847d3484492/System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests/1/console.13fb4ada.log?sv=2019-07-07&se=2022-02-23T01%3A25%3A34Z&sr=c&sp=rl&sig=UjqOa7PjShlvthxy11Aa1CxxY%2BIf1hcdXYoGxBZEMUA%3D).

```
  Discovering: System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests (found 180 test cases)
  Starting:    System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests (parallel test collections = on, max threads = 6)
  Finished:    System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests
=== TEST EXECUTION SUMMARY ===

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x7f83d4fcd8 - Unknown

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 100]
[New LWP 101]
[New LWP 102]
[New LWP 103]
[New LWP 107]
[New LWP 108]
[New LWP 109]
[New LWP 116]
[New LWP 117]
[New LWP 118]
[New LWP 119]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000007f842bda38 in __waitpid (pid=120, stat_loc=0x7fd6c4ba30, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame 
* 1    Thread 0x7f842f8000 (LWP 99) "dotnet" 0x0000007f842bda38 in __waitpid (pid=120, stat_loc=0x7fd6c4ba30, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
  2    Thread 0x7f833ff1e0 (LWP 100) "SGen worker" 0x0000007f842b930c in __pthread_cond_wait (cond=0x7f83e0b848 <work_cond>, mutex=0x7f83e0b818 <lock>) at pthread_cond_wait.c:186
  3    Thread 0x7f8165f1e0 (LWP 101) "dotnet" 0x0000007f83fb4140 in __GI___poll (fds=0x7f7c0014c0, nfds=1, timeout=<optimized out>) at ../sysdeps/unix/sysv/linux/generic/poll.c:38
  4    Thread 0x7f8145f1e0 (LWP 102) "Finalizer" 0x0000007f842bb830 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f83dfc840 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  5    Thread 0x7f803201e0 (LWP 103) "dotnet" 0x0000007f842bc9c8 in read () at ../sysdeps/unix/syscall-template.S:86
  6    Thread 0x7f7a7381e0 (LWP 107) ".NET ThreadPool" 0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f7a7373a0, mutex=0x7f70001160, abstime=0x7f7a737350) at pthread_cond_timedwait.c:198
  7    Thread 0x7f7a1f61e0 (LWP 108) ".NET ThreadPool" 0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f6c0060a0, mutex=0x7f6c006070, abstime=0x7f7a1f52b8) at pthread_cond_timedwait.c:198
  8    Thread 0x7f7a1a61e0 (LWP 109) ".NET ThreadPool" 0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f7a1a53a0, mutex=0x7f70001160, abstime=0x7f7a1a5350) at pthread_cond_timedwait.c:198
  9    Thread 0x7f7855b1e0 (LWP 116) ".NET Timers" 0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f4c00d820, mutex=0x7f4c00d7f0, abstime=0x7f7855a2c8) at pthread_cond_timedwait.c:198
  10   Thread 0x7f476ef1e0 (LWP 117) ".NET ThreadPool" 0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f476ee3a0, mutex=0x7f70001160, abstime=0x7f476ee350) at pthread_cond_timedwait.c:198
  11   Thread 0x7f46ee71e0 (LWP 118) ".NET Sockets" 0x0000007f83fbc584 in __GI_epoll_pwait (epfd=25, events=0x7f6001b3d0, maxevents=32, timeout=-1, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
  12   Thread 0x7f46ce71e0 (LWP 119) ".NET ThreadPool" 0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f46ce63a0, mutex=0x7f70001160, abstime=0x7f46ce6350) at pthread_cond_timedwait.c:198

Thread 12 (Thread 0x7f46ce71e0 (LWP 119)):
#0  0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f46ce63a0, mutex=0x7f70001160, abstime=0x7f46ce6350) at pthread_cond_timedwait.c:198
#1  0x0000007f83c0cb10 in mono_os_cond_timedwait (cond=0x7f46ce63a0, mutex=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/mono-os-mutex.c:75
#2  0x0000007f83c13a28 in mono_coop_cond_timedwait (cond=0x7f46ce63a0, mutex=<optimized out>, timeout_ms=20000) at /__w/1/s/src/mono/mono/mini/../../mono/utils/mono-coop-mutex.h:103
#3  mono_lifo_semaphore_timed_wait (semaphore=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/lifo-semaphore.c:48
#4  0x0000007f79f9c8f8 in ?? ()
#5  0x0000007f83b6c6b8 in ves_icall_System_Threading_Thread_YieldInternal () at /__w/1/s/src/mono/mono/metadata/icall.c:7152
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 11 (Thread 0x7f46ee71e0 (LWP 118)):
#0  0x0000007f83fbc584 in __GI_epoll_pwait (epfd=25, events=0x7f6001b3d0, maxevents=32, timeout=-1, set=0x0) at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x0000007f80fc0a08 in WaitForSocketEventsInner (port=25, buffer=0x7f6001b3d0, count=0x7f46ee6720) at /__w/1/s/src/native/libs/System.Native/pal_networking.c:2717
#2  0x0000007f80fc091c in SystemNative_WaitForSocketEvents (port=25, buffer=0x7f6001b3d0, count=0x7f46ee6720) at /__w/1/s/src/native/libs/System.Native/pal_networking.c:3017
#3  0x0000007f78d6d1d4 in ?? ()
#4  0x8020080280200802 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 0x7f476ef1e0 (LWP 117)):
#0  0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f476ee3a0, mutex=0x7f70001160, abstime=0x7f476ee350) at pthread_cond_timedwait.c:198
#1  0x0000007f83c0cb10 in mono_os_cond_timedwait (cond=0x7f476ee3a0, mutex=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/mono-os-mutex.c:75
#2  0x0000007f83c13a28 in mono_coop_cond_timedwait (cond=0x7f476ee3a0, mutex=<optimized out>, timeout_ms=20000) at /__w/1/s/src/mono/mono/mini/../../mono/utils/mono-coop-mutex.h:103
#3  mono_lifo_semaphore_timed_wait (semaphore=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/lifo-semaphore.c:48
#4  0x0000007f79f9c8f8 in ?? ()
#5  0x0000007f83b6c6b8 in ves_icall_System_Threading_Thread_YieldInternal () at /__w/1/s/src/mono/mono/metadata/icall.c:7152
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 9 (Thread 0x7f7855b1e0 (LWP 116)):
#0  0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f4c00d820, mutex=0x7f4c00d7f0, abstime=0x7f7855a2c8) at pthread_cond_timedwait.c:198
#1  0x0000007f80fc5e54 in SystemNative_LowLevelMonitor_TimedWait (monitor=0x7f4c00d7f0, timeoutMilliseconds=9900) at /__w/1/s/src/native/libs/System.Native/pal_threading.c:195
#2  0x0000007f7a1b1d74 in ?? ()
#3  0x0000007f80223250 in ?? ()
#4  0x0000007f83402408 in ?? ()
#5  0xf90047bda907f3bb in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 0x7f7a1a61e0 (LWP 109)):
#0  0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f7a1a53a0, mutex=0x7f70001160, abstime=0x7f7a1a5350) at pthread_cond_timedwait.c:198
#1  0x0000007f83c0cb10 in mono_os_cond_timedwait (cond=0x7f7a1a53a0, mutex=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/mono-os-mutex.c:75
#2  0x0000007f83c13a28 in mono_coop_cond_timedwait (cond=0x7f7a1a53a0, mutex=<optimized out>, timeout_ms=20000) at /__w/1/s/src/mono/mono/mini/../../mono/utils/mono-coop-mutex.h:103
#3  mono_lifo_semaphore_timed_wait (semaphore=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/lifo-semaphore.c:48
#4  0x0000007f79f9c8f8 in ?? ()
#5  0x0000007f83b6c6b8 in ves_icall_System_Threading_Thread_YieldInternal () at /__w/1/s/src/mono/mono/metadata/icall.c:7152
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 7 (Thread 0x7f7a1f61e0 (LWP 108)):
#0  0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f6c0060a0, mutex=0x7f6c006070, abstime=0x7f7a1f52b8) at pthread_cond_timedwait.c:198
#1  0x0000007f80fc5e54 in SystemNative_LowLevelMonitor_TimedWait (monitor=0x7f6c006070, timeoutMilliseconds=500) at /__w/1/s/src/native/libs/System.Native/pal_threading.c:195
#2  0x0000007f7a1b1d74 in ?? ()
#3  0x0000007f80223250 in ?? ()
#4  0x0000007f7a1f5920 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 6 (Thread 0x7f7a7381e0 (LWP 107)):
#0  0x0000007f842b96a8 in __pthread_cond_timedwait (cond=0x7f7a7373a0, mutex=0x7f70001160, abstime=0x7f7a737350) at pthread_cond_timedwait.c:198
#1  0x0000007f83c0cb10 in mono_os_cond_timedwait (cond=0x7f7a7373a0, mutex=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/mono-os-mutex.c:75
#2  0x0000007f83c13a28 in mono_coop_cond_timedwait (cond=0x7f7a7373a0, mutex=<optimized out>, timeout_ms=20000) at /__w/1/s/src/mono/mono/mini/../../mono/utils/mono-coop-mutex.h:103
#3  mono_lifo_semaphore_timed_wait (semaphore=0x7f70001160, timeout_ms=20000) at /__w/1/s/src/mono/mono/utils/lifo-semaphore.c:48
#4  0x0000007f79f9c8f8 in ?? ()
#5  0x0000007f83b6c6b8 in ves_icall_System_Threading_Thread_YieldInternal () at /__w/1/s/src/mono/mono/metadata/icall.c:7152
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 5 (Thread 0x7f803201e0 (LWP 103)):
#0  0x0000007f842bc9c8 in read () at ../sysdeps/unix/syscall-template.S:86
#1  0x0000007f80fc50c8 in SignalHandlerLoop (arg=0x55a47eb760) at /__w/1/s/src/native/libs/System.Native/pal_signal.c:321
#2  0x0000007f842b2fc4 in start_thread (arg=0x7f80fc501c <SignalHandlerLoop>) at pthread_create.c:335
#3  0x0000007f83fbc3f0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 4 (Thread 0x7f8145f1e0 (LWP 102)):
#0  0x0000007f842bb830 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f83dfc840 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=0x7f83dfc840 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:111
#2  0x0000007f842bb8e8 in __new_sem_wait_slow (sem=0x7f83dfc840 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:181
#3  0x0000007f83be0b10 in mono_os_sem_wait (sem=<optimized out>, flags=MONO_SEM_FLAGS_ALERTABLE) at /__w/1/s/src/mono/mono/mini/../utils/mono-os-semaphore.h:204
#4  mono_coop_sem_wait (sem=<optimized out>, flags=MONO_SEM_FLAGS_ALERTABLE) at /__w/1/s/src/mono/mono/mini/../../mono/utils/mono-coop-semaphore.h:41
#5  finalizer_thread (unused=<optimized out>) at /__w/1/s/src/mono/mono/metadata/gc.c:875
#6  0x0000007f83bbb2f8 in start_wrapper_internal (start_info=0x0, stack_ptr=<optimized out>) at /__w/1/s/src/mono/mono/metadata/threads.c:1203
#7  0x0000007f83bbb1a4 in start_wrapper (data=0x55a40b6e20) at /__w/1/s/src/mono/mono/metadata/threads.c:1265
#8  0x0000007f842b2fc4 in start_thread (arg=0x7f83bbb160 <start_wrapper>) at pthread_create.c:335
#9  0x0000007f83fbc3f0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 3 (Thread 0x7f8165f1e0 (LWP 101)):
#0  0x0000007f83fb4140 in __GI___poll (fds=0x7f7c0014c0, nfds=1, timeout=<optimized out>) at ../sysdeps/unix/sysv/linux/generic/poll.c:38
#1  0x0000007f83ddf518 in ipc_poll_fds (fds=<optimized out>, nfds=1, timeout=4294967295) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:470
#2  ds_ipc_poll (poll_handles_data=0x7f7c003010, poll_handles_data_len=1, timeout_ms=4294967295, callback=0x7f83dde97c <server_warning_callback>) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:1082
#3  0x0000007f83ddcc58 in ds_ipc_stream_factory_get_next_available_stream (callback=0x7f83dde97c <server_warning_callback>) at /__w/1/s/src/native/eventpipe/ds-ipc.c:395
#4  0x0000007f83ddb5fc in server_thread (data=<optimized out>) at /__w/1/s/src/native/eventpipe/ds-server.c:127
#5  0x0000007f83dde95c in ep_rt_thread_mono_start_func (data=0x55a40a1c10) at /__w/1/s/src/mono/mono/mini/../eventpipe/ep-rt-mono.h:1271
#6  0x0000007f842b2fc4 in start_thread (arg=0x7f83dde92c <ep_rt_thread_mono_start_func>) at pthread_create.c:335
#7  0x0000007f83fbc3f0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 2 (Thread 0x7f833ff1e0 (LWP 100)):
#0  0x0000007f842b930c in __pthread_cond_wait (cond=0x7f83e0b848 <work_cond>, mutex=0x7f83e0b818 <lock>) at pthread_cond_wait.c:186
#1  0x0000007f83c60544 in mono_os_cond_wait (cond=0x7f83e0b84c <work_cond+4>, mutex=<optimized out>) at /__w/1/s/src/mono/mono/mini/../../mono/utils/mono-os-mutex.h:219
#2  get_work (worker_index=<optimized out>, work_context=<optimized out>, do_idle=<optimized out>, job=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-thread-pool.c:167
#3  thread_func (data=0x0) at /__w/1/s/src/mono/mono/sgen/sgen-thread-pool.c:198
#4  0x0000007f842b2fc4 in start_thread (arg=0x7f83c60444 <thread_func>) at pthread_create.c:335
#5  0x0000007f83fbc3f0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89

Thread 1 (Thread 0x7f842f8000 (LWP 99)):
#0  0x0000007f842bda38 in __waitpid (pid=120, stat_loc=0x7fd6c4ba30, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x0000007f83d4fdd8 in dump_native_stacktrace (signal=<optimized out>, mctx=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:842
#2  mono_dump_native_crash_info (signal=<optimized out>, mctx=0x7fd6c4c490, info=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:869
#3  0x0000007f83d0c2c4 in mono_handle_native_crash (signal=0x7f83af8e49 "SIGSEGV", mctx=0x7fd6c4c490, info=0x7fd6c4c7f0) at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:2992
#4  0x0000007f83c783d0 in mono_sigsegv_signal_handler_debug (_dummy=11, _info=0x7fd6c4c7f0, context=0x7fd6c4c870, debug_fault_addr=0x54a4266bb8) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:3716
#5  <signal handler called>
#6  0x0000007f83caba28 in mini_get_method (cfg=0x55a483f320, m=<optimized out>, token=<optimized out>, klass=0x0, context=0x0) at /__w/1/s/src/mono/mono/mini/method-to-ir.c:4971
#7  0x0000007f83c8c3c0 in mono_method_to_ir (cfg=<optimized out>, method=<optimized out>, start_bblock=<optimized out>, end_bblock=0x55a483b5b0, return_var=<optimized out>, inline_args=<optimized out>, inline_offset=0, is_virtual_call=-1534856392) at /__w/1/s/src/mono/mono/mini/method-to-ir.c:7349
#8  0x0000007f83c7024c in mini_method_compile (method=<optimized out>, opts=374417919, flags=JIT_FLAG_RUN_CCTORS, parts=0, aot_method_index=-1) at /__w/1/s/src/mono/mono/mini/mini.c:3503
#9  0x0000007f83c72bd0 in mono_jit_compile_method_inner (method=0x55a412ed20, opt=0, error=0x7fd6c4e630) at /__w/1/s/src/mono/mono/mini/mini.c:4124
#10 0x0000007f83c774e8 in mono_jit_compile_method_with_opt (method=0x55a412ed20, opt=374417919, jit_only=0, error=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2652
#11 jit_compile_method_with_opt_cb (arg=0x7fd6c4e540) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2707
#12 jit_compile_method_with_opt (params=0x7fd6c4e540) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2723
#13 0x0000007f83c76948 in mono_jit_compile_method (method=<optimized out>, error=0x7fd6c4e630) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2742
#14 0x0000007f83d0e8f0 in common_call_trampoline (regs=<optimized out>, code=<optimized out>, m=0x55a412ed20, vt=0x0, vtable_slot=<optimized out>, error=0x7fd6c4e630) at /__w/1/s/src/mono/mono/mini/mini-trampolines.c:628
#15 0x0000007f83d0e3e0 in mono_magic_trampoline (regs=0x7fd6c4e6c0, code=0x7f78b25bf0 "\277\003", arg=0x55a412ed20, tramp=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-trampolines.c:769
#16 0x0000007f838dc2fc in ?? ()
#17 0x0000000000000030 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f83caba28):0x7f83caba18  13 02 00 b4 f4 01 00 b4 68 66 41 f9 28 02 b0 b7  ........hfA.(...
0x7f83caba28  88 06 40 f9 00 c1 02 91 84 d8 04 94 a0 01 00 34  ..@............4
0x7f83caba38  68 02 40 f9 60 7a 42 f9 c2 f1 ff f0 42 44 23 91  h.@.`zB.....BD#.
0x7f83caba48  08 05 40 f9 01 1d 40 f9 0f cd fa 97 f4 03 1f aa  ..@...@.........

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at <unknown> <0xffffffff>
	  at System.String:PadRight <0x00037>
	  at Xunit.DefaultRunnerReporterWithTypesMessageHandler:WriteDefaultSummary <0x0099b>
	  at Xunit.DefaultRunnerReporterWithTypesMessageHandler:HandleTestExecutionSummary <0x0003b>
	  at MessageSinkMessageExtensions:Dispatch <0x00093>
	  at Xunit.RunnerEventSink:OnMessageWithTypes <0x000cf>
	  at Xunit.AggregateMessageSink:OnMessageWithTypes <0x000f3>
	  at MessageSinkWithTypesExtensions:OnMessage <0x0005f>
	  at Xunit.ConsoleClient.ConsoleRunner:RunProject <0x00b23>
	  at Xunit.ConsoleClient.ConsoleRunner:EntryPoint <0x0060f>
	  at Xunit.ConsoleClient.Program:Main <0x000df>
	  at <Module>:runtime_invoke_int_object <0x00087>
=================================================================
/root/helix/work/workitem/e
./RunTests.sh: line 162:    99 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.runtimeconfig.json --depsfile System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.deps.json xunit.console.dll System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
----- end Thu Feb 3 01:33:55 UTC 2022 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
ulimit -c value: unlimited
```

**Comment by danmoseley** [comment]
Seems more likely runtime than XML - the managed callstack is in xunit, and the native callstack in JIT

**Comment by LeVladIonescu** [comment]
Not reproducible anymore.
XmlSchemaValidatorApi was also moved to System.Private.Xml/tests/XmlSchema/XmlSchemaValidatorApi.
