### ISSUE TITLE
[wasm][aot][windows] Crash in `Microsoft.Extensions.Logging.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64725]
Hit on https://github.com/dotnet/runtime/pull/62499
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1588560&view=logs&j=55f4943c-f76d-585b-7250-deab324f0a54&t=0cb31181-2886-5d2e-df8c-e96831674532), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62499-merge-dc77c069b450462da7/normal-Microsoft.Extensions.Logging.Tests/1/console.60d7085e.log?sv=2019-07-07&se=2022-02-23T02%3A09%3A16Z&sr=c&sp=rl&sig=XQrmsWgJpZzasSIzS5ip6UXx1RdSuAx%2BEUdTyO2mDCs%3D).

```
EXEC : warning : undefined symbol: htons (referenced by $inetPton6__deps: ['htons','$jstoi_q'], referenced by $writeSockaddr__deps: ['$Sockets','$inetPton4','$inetPton6','$zeroMemory'], referenced by __syscall_accept4__deps: ['$getSocketFromFD','$writeSockaddr','$DNS','$SYSCALLS'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: ntohs (referenced by $inetNtop6__deps: ['$inetNtop4','ntohs'], referenced by $readSockaddr__deps: ['$Sockets','$inetNtop4','$inetNtop6','ntohs'], referenced by $getSocketAddress__deps: ['$readSockaddr','$FS','$DNS'], referenced by __syscall_bind__deps: ['$getSocketFromFD','$getSocketAddress','$SYSCALLS'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: _get_daylight (referenced by tzset_impl__deps: ['_get_daylight','_get_timezone','_get_tzname'], referenced by tzset__deps: ['tzset_impl'], referenced by localtime_r__deps: ['tzset'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: _get_timezone (referenced by tzset_impl__deps: ['_get_daylight','_get_timezone','_get_tzname'], referenced by tzset__deps: ['tzset_impl'], referenced by localtime_r__deps: ['tzset'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: _get_tzname (referenced by tzset_impl__deps: ['_get_daylight','_get_timezone','_get_tzname'], referenced by tzset__deps: ['tzset_impl'], referenced by localtime_r__deps: ['tzset'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
```

Crash:
```
Application arguments: --run WasmTestRunner.dll Microsoft.Extensions.Logging.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
ABORT: undefined
Stacktrace:

Error
    at Object.onAbort (test-main.js:157:25)
    at abort (./dotnet.js:1317:24)
    at mmapAlloc (./dotnet.js:2193:7)
    at syscallMmap2 (./dotnet.js:5443:15)
    at ___syscall_mmap2 (./dotnet.js:5458:14)
    at __mmap (wasm://wasm/0a086f76:wasm-function[92064]:0x11f645d)
    at mono_valloc (wasm://wasm/0a086f76:wasm-function[80735]:0x10aa6f9)
    at mono_thread_small_id_alloc (wasm://wasm/0a086f76:wasm-function[80946]:0x10b1b17)
    at mono_thread_smr_init (wasm://wasm/0a086f76:wasm-function[80957]:0x10b1f27)
    at mono_thread_info_init (wasm://wasm/0a086f76:wasm-function[81030]:0x10b345a)
    at sgen_client_init (wasm://wasm/0a086f76:wasm-function[80684]:0x10a96bd)
    at sgen_gc_init (wasm://wasm/0a086f76:wasm-function[81410]:0x10ba8b0)
    at mono_gc_base_init (wasm://wasm/0a086f76:wasm-function[80691]:0x10a9990)
    at mono_init_internal (wasm://wasm/0a086f76:wasm-function[74792]:0x1012391)
    at mono_init_version (wasm://wasm/0a086f76:wasm-function[74798]:0x1012cb4)
    at mini_init (wasm://wasm/0a086f76:wasm-function[90537]:0x11c5d30)
    at mono_jit_init_version (wasm://wasm/0a086f76:wasm-function[90748]:0x11cc564)
    at mono_wasm_load_runtime (wasm://wasm/0a086f76:wasm-function[92526]:0x1206bc5)
    at Module._mono_wasm_load_runtime (./dotnet.js:7306:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8203:5)
    at run (./dotnet.js:8216:5)
    at runCaller (./dotnet.js:8170:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
Aborted(undefined)
ABORT: RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.
Stacktrace:

Error
    at Object.onAbort (test-main.js:157:25)
    at abort (./dotnet.js:1317:24)
    at ___syscall_mmap2 (./dotnet.js:5460:69)
    at __mmap (wasm://wasm/0a086f76:wasm-function[92064]:0x11f645d)
    at mono_valloc (wasm://wasm/0a086f76:wasm-function[80735]:0x10aa6f9)
    at mono_thread_small_id_alloc (wasm://wasm/0a086f76:wasm-function[80946]:0x10b1b17)
    at mono_thread_smr_init (wasm://wasm/0a086f76:wasm-function[80957]:0x10b1f27)
    at mono_thread_info_init (wasm://wasm/0a086f76:wasm-function[81030]:0x10b345a)
    at sgen_client_init (wasm://wasm/0a086f76:wasm-function[80684]:0x10a96bd)
    at sgen_gc_init (wasm://wasm/0a086f76:wasm-function[81410]:0x10ba8b0)
    at mono_gc_base_init (wasm://wasm/0a086f76:wasm-function[80691]:0x10a9990)
    at mono_init_internal (wasm://wasm/0a086f76:wasm-function[74792]:0x1012391)
    at mono_init_version (wasm://wasm/0a086f76:wasm-function[74798]:0x1012cb4)
    at mini_init (wasm://wasm/0a086f76:wasm-function[90537]:0x11c5d30)
    at mono_jit_init_version (wasm://wasm/0a086f76:wasm-function[90748]:0x11cc564)
    at mono_wasm_load_runtime (wasm://wasm/0a086f76:wasm-function[92526]:0x1206bc5)
    at Module._mono_wasm_load_runtime (./dotnet.js:7306:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8203:5)
    at run (./dotnet.js:8216:5)
    at runCaller (./dotnet.js:8170:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
{}
RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (./dotnet.js:1334:11)
    at mmapAlloc (./dotnet.js:2193:7)
    at syscallMmap2 (./dotnet.js:5443:15)
    at ___syscall_mmap2 (./dotnet.js:5458:14)
    at __mmap (wasm://wasm/0a086f76:wasm-function[92064]:0x11f645d)
    at mono_valloc (wasm://wasm/0a086f76:wasm-function[80735]:0x10aa6f9)
    at mono_thread_small_id_alloc (wasm://wasm/0a086f76:wasm-function[80946]:0x10b1b17)
    at mono_thread_smr_init (wasm://wasm/0a086f76:wasm-function[80957]:0x10b1f27)
    at mono_thread_info_init (wasm://wasm/0a086f76:wasm-function[81030]:0x10b345a)
    at sgen_client_init (wasm://wasm/0a086f76:wasm-function[80684]:0x10a96bd)
    at sgen_gc_init (wasm://wasm/0a086f76:wasm-function[81410]:0x10ba8b0)
    at mono_gc_base_init (wasm://wasm/0a086f76:wasm-function[80691]:0x10a9990)
    at mono_init_internal (wasm://wasm/0a086f76:wasm-function[74792]:0x1012391)
    at mono_init_version (wasm://wasm/0a086f76:wasm-function[74798]:0x1012cb4)
    at mini_init (wasm://wasm/0a086f76:wasm-function[90537]:0x11c5d30)
    at mono_jit_init_version (wasm://wasm/0a086f76:wasm-function[90748]:0x11cc564)
    at mono_wasm_load_runtime (wasm://wasm/0a086f76:wasm-function[92526]:0x1206bc5)
    at Module._mono_wasm_load_runtime (./dotnet.js:7306:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8203:5)
    at run (./dotnet.js:8216:5)
    at runCaller (./dotnet.js:8170:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
Aborted(RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.)
MONO_WASM: mono_wasm_load_runtime () failed: RuntimeError: Aborted(RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
MONO_WASM: Stacktrace: 

RuntimeError: Aborted(RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at abort (./dotnet.js:1334:11)
    at ___syscall_mmap2 (./dotnet.js:5460:69)
    at __mmap (wasm://wasm/0a086f76:wasm-function[92064]:0x11f645d)
    at mono_valloc (wasm://wasm/0a086f76:wasm-function[80735]:0x10aa6f9)
    at mono_thread_small_id_alloc (wasm://wasm/0a086f76:wasm-function[80946]:0x10b1b17)
    at mono_thread_smr_init (wasm://wasm/0a086f76:wasm-function[80957]:0x10b1f27)
    at mono_thread_info_init (wasm://wasm/0a086f76:wasm-function[81030]:0x10b345a)
    at sgen_client_init (wasm://wasm/0a086f76:wasm-function[80684]:0x10a96bd)
    at sgen_gc_init (wasm://wasm/0a086f76:wasm-function[81410]:0x10ba8b0)
    at mono_gc_base_init (wasm://wasm/0a086f76:wasm-function[80691]:0x10a9990)
    at mono_init_internal (wasm://wasm/0a086f76:wasm-function[74792]:0x1012391)
    at mono_init_version (wasm://wasm/0a086f76:wasm-function[74798]:0x1012cb4)
    at mini_init (wasm://wasm/0a086f76:wasm-function[90537]:0x11c5d30)
    at mono_jit_init_version (wasm://wasm/0a086f76:wasm-function[90748]:0x11cc564)
    at mono_wasm_load_runtime (wasm://wasm/0a086f76:wasm-function[92526]:0x1206bc5)
    at Module._mono_wasm_load_runtime (./dotnet.js:7306:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8203:5)
    at run (./dotnet.js:8216:5)
    at runCaller (./dotnet.js:8170:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
Process v8.cmd exited with 1
```

cc @radekdoulik @vargaz 

|Build|Kind|Start Time|
|---|---|---|
[1589203](https://dev.azure.com/dnceng/public/_build/results?buildId=1589203)|Rolling|2022-03-02|

**Comment by radekdoulik** [comment]
Looks like same issue in emscripten as mentioned in https://github.com/dotnet/runtime/issues/64724#issuecomment-1029432680

**Comment by radical** [comment]
This started with the 2.0.34 bump, which has been [rolled back](https://github.com/dotnet/runtime/pull/65517) now.
