### ISSUE TITLE
[wasm][aot][windows] Crash in `Microsoft.Extensions.HostFactoryResolver.Tests` with emsdk `2.0.34`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64724]
Hit on https://github.com/dotnet/runtime/pull/62499
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1588560&view=logs&j=55f4943c-f76d-585b-7250-deab324f0a54&t=0cb31181-2886-5d2e-df8c-e96831674532), and
[log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62499-merge-dc77c069b450462da7/normal-Microsoft.Extensions.HostFactoryResolver.Tests/1/console.6ce9da79.log?sv=2019-07-07&se=2022-02-23T02%3A09%3A16Z&sr=c&sp=rl&sig=XQrmsWgJpZzasSIzS5ip6UXx1RdSuAx%2BEUdTyO2mDCs%3D)

```
EXEC : warning : undefined symbol: htons (referenced by $inetPton6__deps: ['htons','$jstoi_q'], referenced by $writeSockaddr__deps: ['$Sockets','$inetPton4','$inetPton6','$zeroMemory'], referenced by __syscall_accept4__deps: ['$getSocketFromFD','$writeSockaddr','$DNS','$SYSCALLS'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: ntohs (referenced by $inetNtop6__deps: ['$inetNtop4','ntohs'], referenced by $readSockaddr__deps: ['$Sockets','$inetNtop4','$inetNtop6','ntohs'], referenced by $getSocketAddress__deps: ['$readSockaddr','$FS','$DNS'], referenced by __syscall_bind__deps: ['$getSocketFromFD','$getSocketAddress','$SYSCALLS'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: _get_daylight (referenced by tzset_impl__deps: ['_get_daylight','_get_timezone','_get_tzname'], referenced by tzset__deps: ['tzset_impl'], referenced by localtime_r__deps: ['tzset'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: _get_timezone (referenced by tzset_impl__deps: ['_get_daylight','_get_timezone','_get_tzname'], referenced by tzset__deps: ['tzset_impl'], referenced by localtime_r__deps: ['tzset'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
EXEC : warning : undefined symbol: _get_tzname (referenced by tzset_impl__deps: ['_get_daylight','_get_timezone','_get_tzname'], referenced by tzset__deps: ['tzset_impl'], referenced by localtime_r__deps: ['tzset'], referenced by top-level compiled C/C++ code) [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
```

Crash:
```
Application arguments: --run WasmTestRunner.dll Microsoft.Extensions.HostFactoryResolver.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
ABORT: undefined
Stacktrace:

ABORT: RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.
Error
    at Object.onAbort (test-main.js:157:25)
    at abort (./dotnet.js:1317:24)
    at mmapAlloc (./dotnet.js:2193:7)
    at syscallMmap2 (./dotnet.js:5453:15)
    at ___syscall_mmap2 (./dotnet.js:5468:14)
    at __mmap (wasm://wasm/08cd59f2:wasm-function[79835]:0xf2e810)
    at mono_valloc (wasm://wasm/08cd59f2:wasm-function[68503]:0xde2a82)
    at mono_thread_small_id_alloc (wasm://wasm/08cd59f2:wasm-function[68714]:0xde9ea0)
    at mono_thread_smr_init (wasm://wasm/08cd59f2:wasm-function[68725]:0xdea2b0)
    at mono_thread_info_init (wasm://wasm/08cd59f2:wasm-function[68798]:0xdeb7e3)
    at sgen_client_init (wasm://wasm/08cd59f2:wasm-function[68452]:0xde1a46)
    at sgen_gc_init (wasm://wasm/08cd59f2:wasm-function[69177]:0xdf2c25)
    at mono_gc_base_init (wasm://wasm/08cd59f2:wasm-function[68459]:0xde1d19)
    at mono_init_internal (wasm://wasm/08cd59f2:wasm-function[62601]:0xd4c9ef)
    at mono_init_version (wasm://wasm/08cd59f2:wasm-function[62607]:0xd4d312)
    at mini_init (wasm://wasm/08cd59f2:wasm-function[78304]:0xefe0a5)
    at mono_jit_init_version (wasm://wasm/08cd59f2:wasm-function[78515]:0xf048d9)
    at mono_wasm_load_runtime (wasm://wasm/08cd59f2:wasm-function[80298]:0xf3ef85)
    at Module._mono_wasm_load_runtime (./dotnet.js:7387:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8284:5)
    at run (./dotnet.js:8297:5)
    at runCaller (./dotnet.js:8251:19)
Stacktrace:
    at removeRunDependency (./dotnet.js:1305:7)

    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
Aborted(undefined)
Error
    at Object.onAbort (test-main.js:157:25)
    at abort (./dotnet.js:1317:24)
    at ___syscall_mmap2 (./dotnet.js:5470:69)
    at __mmap (wasm://wasm/08cd59f2:wasm-function[79835]:0xf2e810)
    at mono_valloc (wasm://wasm/08cd59f2:wasm-function[68503]:0xde2a82)
    at mono_thread_small_id_alloc (wasm://wasm/08cd59f2:wasm-function[68714]:0xde9ea0)
    at mono_thread_smr_init (wasm://wasm/08cd59f2:wasm-function[68725]:0xdea2b0)
    at mono_thread_info_init (wasm://wasm/08cd59f2:wasm-function[68798]:0xdeb7e3)
    at sgen_client_init (wasm://wasm/08cd59f2:wasm-function[68452]:0xde1a46)
    at sgen_gc_init (wasm://wasm/08cd59f2:wasm-function[69177]:0xdf2c25)
    at mono_gc_base_init (wasm://wasm/08cd59f2:wasm-function[68459]:0xde1d19)
    at mono_init_internal (wasm://wasm/08cd59f2:wasm-function[62601]:0xd4c9ef)
    at mono_init_version (wasm://wasm/08cd59f2:wasm-function[62607]:0xd4d312)
    at mini_init (wasm://wasm/08cd59f2:wasm-function[78304]:0xefe0a5)
    at mono_jit_init_version (wasm://wasm/08cd59f2:wasm-function[78515]:0xf048d9)
    at mono_wasm_load_runtime (wasm://wasm/08cd59f2:wasm-function[80298]:0xf3ef85)
    at Module._mono_wasm_load_runtime (./dotnet.js:7387:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8284:5)
    at run (./dotnet.js:8297:5)
    at runCaller (./dotnet.js:8251:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
{}
RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (./dotnet.js:1334:11)
    at mmapAlloc (./dotnet.js:2193:7)
    at syscallMmap2 (./dotnet.js:5453:15)
    at ___syscall_mmap2 (./dotnet.js:5468:14)
    at __mmap (wasm://wasm/08cd59f2:wasm-function[79835]:0xf2e810)
    at mono_valloc (wasm://wasm/08cd59f2:wasm-function[68503]:0xde2a82)
    at mono_thread_small_id_alloc (wasm://wasm/08cd59f2:wasm-function[68714]:0xde9ea0)
    at mono_thread_smr_init (wasm://wasm/08cd59f2:wasm-function[68725]:0xdea2b0)
    at mono_thread_info_init (wasm://wasm/08cd59f2:wasm-function[68798]:0xdeb7e3)
    at sgen_client_init (wasm://wasm/08cd59f2:wasm-function[68452]:0xde1a46)
    at sgen_gc_init (wasm://wasm/08cd59f2:wasm-function[69177]:0xdf2c25)
    at mono_gc_base_init (wasm://wasm/08cd59f2:wasm-function[68459]:0xde1d19)
    at mono_init_internal (wasm://wasm/08cd59f2:wasm-function[62601]:0xd4c9ef)
    at mono_init_version (wasm://wasm/08cd59f2:wasm-function[62607]:0xd4d312)
    at mini_init (wasm://wasm/08cd59f2:wasm-function[78304]:0xefe0a5)
    at mono_jit_init_version (wasm://wasm/08cd59f2:wasm-function[78515]:0xf048d9)
    at mono_wasm_load_runtime (wasm://wasm/08cd59f2:wasm-function[80298]:0xf3ef85)
    at Module._mono_wasm_load_runtime (./dotnet.js:7387:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8284:5)
    at run (./dotnet.js:8297:5)
    at runCaller (./dotnet.js:8251:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
Aborted(RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.)
MONO_WASM: mono_wasm_load_runtime () failed: RuntimeError: Aborted(RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
MONO_WASM: Stacktrace: 

RuntimeError: Aborted(RuntimeError: Aborted(undefined). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at abort (./dotnet.js:1334:11)
    at ___syscall_mmap2 (./dotnet.js:5470:69)
    at __mmap (wasm://wasm/08cd59f2:wasm-function[79835]:0xf2e810)
    at mono_valloc (wasm://wasm/08cd59f2:wasm-function[68503]:0xde2a82)
    at mono_thread_small_id_alloc (wasm://wasm/08cd59f2:wasm-function[68714]:0xde9ea0)
    at mono_thread_smr_init (wasm://wasm/08cd59f2:wasm-function[68725]:0xdea2b0)
    at mono_thread_info_init (wasm://wasm/08cd59f2:wasm-function[68798]:0xdeb7e3)
    at sgen_client_init (wasm://wasm/08cd59f2:wasm-function[68452]:0xde1a46)
    at sgen_gc_init (wasm://wasm/08cd59f2:wasm-function[69177]:0xdf2c25)
    at mono_gc_base_init (wasm://wasm/08cd59f2:wasm-function[68459]:0xde1d19)
    at mono_init_internal (wasm://wasm/08cd59f2:wasm-function[62601]:0xd4c9ef)
    at mono_init_version (wasm://wasm/08cd59f2:wasm-function[62607]:0xd4d312)
    at mini_init (wasm://wasm/08cd59f2:wasm-function[78304]:0xefe0a5)
    at mono_jit_init_version (wasm://wasm/08cd59f2:wasm-function[78515]:0xf048d9)
    at mono_wasm_load_runtime (wasm://wasm/08cd59f2:wasm-function[80298]:0xf3ef85)
    at Module._mono_wasm_load_runtime (./dotnet.js:7387:114)
    at ccall (./dotnet.js:696:18)
    at ./dotnet.js:719:12
    at Object.o.<computed> (./dotnet.js:3:4019)
    at finalize_startup (./dotnet.js:3:61490)
    at mono_wasm_after_runtime_initialized (./dotnet.js:3:59112)
    at callRuntimeCallbacks (./dotnet.js:1535:11)
    at postRun (./dotnet.js:1236:3)
    at doRun (./dotnet.js:8284:5)
    at run (./dotnet.js:8297:5)
    at runCaller (./dotnet.js:8251:19)
    at removeRunDependency (./dotnet.js:1305:7)
    at receiveInstance (./dotnet.js:1446:5)
    at receiveInstantiationResult (./dotnet.js:1457:5)
Process v8.cmd exited with 1
```

cc @radekdoulik @vargaz

|Build|Kind|Start Time|
|---|---|---|
[1589203](https://dev.azure.com/dnceng/public/_build/results?buildId=1589203)|Rolling|2022-03-02|

**Comment by radekdoulik** [comment]
emscripten issue: https://github.com/emscripten-core/emscripten/issues/15958
(partial?) fix: https://github.com/emscripten-core/emscripten/pull/16118

**Comment by radekdoulik** [comment]
I have tried to add the missing functions to `-s EXPORTED_FUNCTIONS=...` as a workaround, the clang started crashing after that.

@vargaz do you have some other idea to try?

**Comment by radekdoulik** [comment]
Exports work for me locally now. Either the changed list format helped or I had some problem with my local build?

**Comment by radekdoulik** [comment]
https://github.com/dotnet/runtime/pull/64807 fixes the linker warnings about undefined symbols. The crash is still present.

**Comment by radekdoulik** [comment]
@vargaz could you please take a look at the crash? I will be away next week.

I am able to reproduce it with `.\dotnet.cmd build -bl -c Release /t:Test -p:RunAOTCompilation=true -p:TargetOS=Browser .\src\libraries\Microsoft.Extensions.Logging\tests\Common\` on windows. Hopefully osx equivalent would reproduce it too.

**Comment by vargaz** [comment]
Can't reproduce this on osx.

**Comment by radical** [comment]
Re-opening this because https://github.com/dotnet/runtime/pull/64807 only fixed the warnings part of this issue.
