### ISSUE TITLE
[wasm] V8/Linux `RuntimeError: memory access out of bounds` for `System.Text.Json.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64775]
Hit on https://github.com/dotnet/runtime/pull/64759

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1590775&view=logs&jobId=06c2b9cd-9a25-5ea1-8363-c1b61a607e70&j=06c2b9cd-9a25-5ea1-8363-c1b61a607e70&t=8781fc1b-ea29-5eeb-5abc-12f9c52a8e0d), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64759-merge-efb62209054c4ea6b9/normal-System.Text.Json.Tests/1/console.a16f10ca.log?sv=2019-07-07&se=2022-02-23T22%3A13%3A23Z&sr=c&sp=rl&sig=ynoVKToRw9Iw%2Bj7V0f4ypGee%2FFZwYMsDSQUSIJ4Q7AE%3D).

```
[22:35:38] info: Starting:    System.Text.Json.Tests.dll
[22:50:34] info: wasm-function[8382]:0x1b66c4: RuntimeError: memory access out of bounds
[22:50:34] info: RuntimeError: memory access out of bounds
[22:50:34] info:     at <anonymous>:wasm-function[8382]:0x1b66c4
[22:50:34] info:     at <anonymous>:wasm-function[8383]:0x1b671f
[22:50:34] info:     at <anonymous>:wasm-function[1854]:0x823ff
[22:50:34] info:     at <anonymous>:wasm-function[8384]:0x1b678b
[22:50:34] info:     at <anonymous>:wasm-function[1853]:0x823a9
[22:50:34] info:     at <anonymous>:wasm-function[1852]:0x8236a
[22:50:34] info:     at <anonymous>:wasm-function[328]:0x1deed
[22:50:34] info:     at <anonymous>:wasm-function[380]:0x28982
[22:50:34] info:     at <anonymous>:wasm-function[171]:0x18efa
[22:50:34] info:     at <anonymous>:wasm-function[7734]:0x19769d
[22:50:34] info:     at <anonymous>:wasm-function[2003]:0x88d74
[22:50:34] info:     at <anonymous>:wasm-function[1204]:0x5eaec
[22:50:34] info:     at <anonymous>:wasm-function[8240]:0x1b1833
[22:50:34] info:     at <anonymous>:wasm-function[170]:0xd66f
[22:50:34] info:     at <anonymous>:wasm-function[169]:0xbd1e
[22:50:34] info:     at <anonymous>:wasm-function[7733]:0x196da6
[22:50:34] info:     at <anonymous>:wasm-function[1901]:0x84027
[22:50:34] info:     at <anonymous>:wasm-function[1899]:0x83f99
[22:50:34] info:     at <anonymous>:wasm-function[1262]:0x652d8
[22:50:34] info:     at <anonymous>:wasm-function[259]:0x1b728
[22:50:34] info:     at <anonymous>:wasm-function[230]:0x1ad6a
[22:50:34] info:     at <anonymous>:wasm-function[170]:0xce6a
[22:50:34] info:     at <anonymous>:wasm-function[169]:0xbd1e
[22:50:34] info:     at <anonymous>:wasm-function[7733]:0x196da6
[22:50:34] info:     at <anonymous>:wasm-function[1901]:0x84027
[22:50:34] info:     at <anonymous>:wasm-function[1905]:0x8468e
[22:50:34] info:     at <anonymous>:wasm-function[8151]:0x1b057c
[22:50:34] info:     at mono_background_exec (<anonymous>:wasm-function[2664]:0xa8574)
[22:50:34] info:     at Object.Module._mono_background_exec [as mono_background_exec] (./dotnet.js:12:136223)
[22:50:34] info:     at pump_message (./dotnet.js:3:69774)
[22:50:34] info: 
[22:50:34] info: Process v8 exited with 1
```

Might be random, because it didn't fail on another PR.

**Comment by radical** [comment]
This started with the 2.0.34 bump, which has been [rolled back](https://github.com/dotnet/runtime/pull/65517) now.
