### ISSUE TITLE
[wasm] Test failures on NodeJS/Linux because RemoteExecutor is not supported

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64776]
Hit on https://github.com/dotnet/runtime/pull/64766 which enables running library tests on NodeJS

.. due to `System.PlatformNotSupportedException : System.Diagnostics.Process is not supported on this platform.`

[Linux log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64766-merge-8c54abc52cee400e9c/WasmTestOnNodeJs-System.Text.RegularExpressions.Tests/1/console.8f37a21b.log?sv=2019-07-07&se=2022-02-23T22%3A37%3A37Z&sr=c&sp=rl&sig=S5UVK89KWpw7FanDf9oScdIbhgTc79u7jJDURrj1%2Bl4%3D):

```
[23:14:43] fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries
[23:14:43] info: System.TypeInitializationException : The type initializer for 'Microsoft.DotNet.RemoteExecutor.RemoteExecutor' threw an exception.
[23:14:43] info: ---- System.PlatformNotSupportedException : System.Diagnostics.Process is not supported on this platform.
[23:14:43] info:    at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries() in /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs:line 70
[23:14:43] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
[23:14:43] info: ----- Inner Stack Trace -----
[23:14:43] info:    at System.Diagnostics.Process.GetCurrentProcess() in /_/artifacts/obj/System.Diagnostics.Process/Release/net7.0/System.Diagnostics.Process.notsupported.cs:line 112
[23:14:43] info:    at Microsoft.DotNet.RemoteExecutor.RemoteExecutor..cctor() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 49
[23:14:43] fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Second_drops_first
[23:14:43] info: System.TypeInitializationException : The type initializer for 'Microsoft.DotNet.RemoteExecutor.RemoteExecutor' threw an exception.
[23:14:43] info: ---- System.PlatformNotSupportedException : System.Diagnostics.Process is not supported on this platform.
[23:14:43] info:    at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Second_drops_first() in /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs:line 42
[23:14:43] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
[23:14:43] info: ----- Inner Stack Trace -----
[23:14:43] info:    at System.Diagnostics.Process.GetCurrentProcess() in /_/artifacts/obj/System.Diagnostics.Process/Release/net7.0/System.Diagnostics.Process.notsupported.cs:line 112
[23:14:43] info:    at Microsoft.DotNet.RemoteExecutor.RemoteExecutor..cctor() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 49
[23:14:43] fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw
[23:14:43] info: System.TypeInitializationException : The type initializer for 'Microsoft.DotNet.RemoteExecutor.RemoteExecutor' threw an exception.
[23:14:43] info: ---- System.PlatformNotSupportedException : System.Diagnostics.Process is not supported on this platform.
[23:14:43] info:    at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_dictionary_linked_list_switch_does_not_throw() in /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs:line 105
[23:14:43] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
[23:14:43] info: ----- Inner Stack Trace -----
[23:14:43] info:    at System.Diagnostics.Process.GetCurrentProcess() in /_/artifacts/obj/System.Diagnostics.Process/Release/net7.0/System.Diagnostics.Process.notsupported.cs:line 112
[23:14:43] info:    at Microsoft.DotNet.RemoteExecutor.RemoteExecutor..cctor() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 49
[23:14:43] fail: [FAIL] System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_culture_and_options
[23:14:43] info: System.TypeInitializationException : The type initializer for 'Microsoft.DotNet.RemoteExecutor.RemoteExecutor' threw an exception.
[23:14:43] info: ---- System.PlatformNotSupportedException : System.Diagnostics.Process is not supported on this platform.
[23:14:43] info:    at System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Uses_culture_and_options() in /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Cache.Tests.cs:line 87
[23:14:43] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
[23:14:43] info: ----- Inner Stack Trace -----
[23:14:43] info:    at System.Diagnostics.Process.GetCurrentProcess() in /_/artifacts/obj/System.Diagnostics.Process/Release/net7.0/System.Diagnostics.Process.notsupported.cs:line 112
[23:14:43] info:    at Microsoft.DotNet.RemoteExecutor.RemoteExecutor..cctor() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs:line 49
```

But this does *not* fail on windows.

[Windows log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64766-merge-ccb944a48c6b47209f/WasmTestOnNodeJs-System.Text.RegularExpressions.Tests/1/console.e712b2d7.log?sv=2019-07-07&)

cc @pavelsavara

**Comment by radical** [comment]
cc @maraf

**Comment by pavelsavara** [comment]
`RemoteExecutor` is reason enough to disable the test for whole Browser target. But how come it doesn't always fail ?

**Comment by maraf** [comment]
When I run it locally on node, it skips the test with

```xml
<test name="System.Text.RegularExpressions.Tests.RegexCacheTests.Ctor_Cache_Promote_entries" type="System.Text.RegularExpressions.Tests.RegexCacheTests" method="Ctor_Cache_Promote_entries" time="0" result="Skip">
    <reason><![CDATA[Condition(s) not met: \"IsSupported (TargetInvocationException)\"]]></reason>
</test>
```
