### ISSUE TITLE
[android][arm64] System.Net.NetworkInformation.Tests.PingTest.SendPingWithIPAddressAndBigSize throws PNSE

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#64798]
```
<test name="System.Net.NetworkInformation.Tests.PingTest.SendPingWithIPAddressAndBigSize" type="System.Net.NetworkInformation.Tests.PingTest" method="SendPingWithIPAddressAndBigSize" time="0.0061604" result="Fail">
<failure exception-type="System.PlatformNotSupportedException">
    <message><![CDATA[System.PlatformNotSupportedException : Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).]]></message>
    <stack-trace><![CDATA[   at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
at System.Net.NetworkInformation.Ping.SendPingAsyncInternal(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
at System.Net.NetworkInformation.Tests.PingTest.SendPingWithIPAddressAndBigSize() in /_/src/libraries/System.Net.Ping/tests/FunctionalTests/PingTest.cs:line 466
--- End of stack trace from previous location ---]]></stack-trace>
</failure>
</test>
```
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-521451d46c924046b8/System.Net.Ping.Functional.Tests/3/testResults.xml?sv=2019-07-07&se=2022-02-23T22%3A09%3A12Z&sr=c&sp=rl&sig=%2B8wgChrHdrRRWwhqoRKjAV3zpuu44tCwoy89KcAfoGI%3D

Does this test need to be skipped on Android after the refactoring done in https://github.com/dotnet/runtime/pull/64625 ?

@steveisok @akoeplinger  

|Build|Kind|Start Time|
|---|---|---|
[1596337](https://dev.azure.com/dnceng/public/_build/results?buildId=1596337)|Rolling|2022-07-02|

**Comment by MaximLipnin** [comment]
Addressed in https://github.com/dotnet/runtime/pull/64897
