### ISSUE TITLE
System.Text.Json source generator does not support ReferenceHandler.Preserve option

### ISSUE THREAD

**Issue by morga4** [dotnet/runtime#64813]
### Description

JsonSerializer throws `Cannot parse a JSON object containing metadata properties like '$id' into an array or immutable collection type.` on deserialization once `JsonTypeInfo<T>` is used.

### Reproduction Steps

1. create net6.0 project
2. run the following code:

```
using System.Text.Json;
using System.Text.Json.Serialization;

var options = new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.Preserve };
var context = new ExampleJsonContext(options);

var json = JsonSerializer.Serialize(new Example(), context.Example);
// {"$id":"1"}

var ex = JsonSerializer.Deserialize(json, context.Example);
// System.Text.Json.JsonException: Cannot parse a JSON object containing metadata properties like '$id' into an array or immutable collection type. Type 'Example'. Path: $.$id | LineNumber: 0 | BytePositionInLine: 7.
//    at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
//    at System.Text.Json.ThrowHelper.ThrowJsonException_MetadataCannotParsePreservedObjectIntoImmutable(Type propertyType)
//    at System.Text.Json.JsonSerializer.ResolveMetadataForJsonObject[T](Utf8JsonReader& reader, ReadStack& state, JsonSerializerOptions options)
//    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
//    at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
//    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
//    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
//    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
//    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
//    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
//    at Program.<Main>$(String[] args)

class Example
{
}

[JsonSerializable(typeof(Example))]
partial class ExampleJsonContext : JsonSerializerContext
{
}
```

### Expected behavior

`JsonSerializer.Deserialize(json, context.Example)` returns an object of type `Example`

### Actual behavior

`JsonSerializer.Deserialize(json, context.Example)` throws `Cannot parse a JSON object containing metadata properties like '$id' into an array or immutable collection type.`

**Comment by morga4** [comment]
Can someone confirm the bug?

**Comment by layomia** [comment]
Yup I can repro this. Will put up a fix shortly.
