### ISSUE TITLE
NativeAOT Rd.xml file parsing should provide better reporting

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#64869]
### Description

Add following declaration
```diff
- <Type Name="System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String,System.Private.CoreLib],[System.Object,System.Private.CoreLib]],[System.String,System.Private.CoreLib],[System.Object,System.Private.CoreLib]]" Dynamic="Required All" />
+ <Type Name="System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String,System.Private.CoreLib],[System.Object,System.Private.CoreLib]],System.Private.CoreLib],[System.String,System.Private.CoreLib],[System.Object,System.Private.CoreLib]]" Dynamic="Required All" />
```

I do miss one closing `]` and explicit assembly name.

### Reproduction Steps

Explained in description

### Expected behavior

Something which indicate what's passed to that function. If parser is broken, I at least would like to know what approximate part it is broken at. In this case that's value for `assemblyName` which cannot be loaded.

### Actual behavior

Exception with obscure information
```
  System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)
     at System.Reflection.AssemblyName.nInit()
     at System.Reflection.AssemblyName..ctor(String assemblyName)
     at Internal.TypeSystem.CustomAttributeTypeNameParser.FindAssemblyIfNamePresent(String name)
     at Internal.TypeSystem.CustomAttributeTypeNameParser.GetTypeByCustomAttributeTypeName(ModuleDesc module, String name, Boolean throwIfNotFound, Func`4 resolver)
     at Internal.TypeSystem.CustomAttributeTypeNameParser.GetTypeByCustomAttributeTypeName(ModuleDesc module, String name, Boolean throwIfNotFound, Func`4 resolver)
     at ILCompiler.RdXmlRootProvider.ProcessTypeDirective(IRootingServiceProvider rootProvider, ModuleDesc containingModule, XElement typeElement)
     at ILCompiler.RdXmlRootProvider.ProcessAssemblyDirective(IRootingServiceProvider rootProvider, XElement assemblyElement)
     at ILCompiler.RdXmlRootProvider.AddCompilationRoots(IRootingServiceProvider rootProvider)
     at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 compilationRoots, ILProvider ilProvider, DebugInformationProvider debugInformationProvider, DevirtualizationManager devirtualizationManager, IInliningPolicy inliningPolicy, Logger logger)
     at ILCompiler.ILScannerBuilder.ToILScanner()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

**Comment by MichalStrehovsky** [comment]
We don't have plans to improve RD.XML support.
