### ISSUE TITLE
Test failure System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64888]
Run: [runtime-coreclr libraries-jitstress 20220205.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1595350&view=ms.vss-test-web.build-test-results-tab&runId=44606634&paneView=debug&resultId=128955)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

```
**Error message:**
```
System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.


Stack trace
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs:line 46
   at System.Diagnostics.Eventing.Reader.ProviderMetadata.GetProviderListProperty(EventLogHandle providerHandle, EvtPublisherMetadataPropertyId metadataProperty) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 304
   at System.Diagnostics.Eventing.Reader.ProviderMetadata.get_Keywords() in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 469
   at System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 106
```

**Comment by VincentBu** [comment]
Failed again in:[ runtime-coreclr libraries-jitstress 20220410.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1709535&view=ms.vss-test-web.build-test-results-tab&runId=46505806&paneView=debug&resultId=123722)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

```
**Error message:**
```
System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.


Stack trace
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs:line 46
   at System.Diagnostics.Eventing.Reader.ProviderMetadata.GetProviderListProperty(EventLogHandle providerHandle, EvtPublisherMetadataPropertyId metadataProperty) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 419
   at System.Diagnostics.Eventing.Reader.ProviderMetadata.get_Keywords() in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 469
   at System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 184
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220418.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1723402&view=ms.vss-test-web.build-test-results-tab&runId=46756928&paneView=debug&resultId=119923)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

net7.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open

- System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties
```
**Error message:**
```
System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.


Stack trace
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs:line 39
   at System.Diagnostics.Eventing.Reader.ProviderMetadata.GetProviderListProperty(EventLogHandle providerHandle, EvtPublisherMetadataPropertyId metadataProperty) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 304
   at System.Diagnostics.Eventing.Reader.ProviderMetadata.get_Keywords() in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 465
   at System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 108
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 379
```

**Comment by AndyAyersMS** [comment]
Stale issue, closing.
