### ISSUE TITLE
[wasm][debugger][tests] Retry when we fail to get the connection string from chrome

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64931]
Example failure on CI:

```
[20:04:06] dbug: Microsoft.WebAssembly.Diagnostics.InspectorClient[0] connecting to ws://localhost:9400/launch-chrome-and-connect
[20:04:06] info: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] New test request
[20:04:26] fail: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] Didnt get the con string after 20s.
[20:04:26] fail: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] got exception System.Exception: node.js timedout    at Microsoft.WebAssembly.Diagnostics.TestHarnessStartup.LaunchAndServe(ProcessStartInfo psi, HttpContext context, Func`2 extract_conn_url) in /_/src/mono/wasm/debugger/DebuggerTestSuite/TestHarnessStartup.cs:line 120
[20:04:26] dbug: DebuggerTests.Inspector[0] System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '200' when status code '101' was expected.    at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)    at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)    at Microsoft.WebAssembly.Diagnostics.DevToolsClient.ConnectWithMainLoops(Uri uri, Func`3 receive, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 125    at Microsoft.WebAssembly.Diagnostics.InspectorClient.Connect(Uri uri, Func`4 onEvent, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 59    at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, Nullable`1 span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 214
[20:04:26] dbug: Microsoft.WebAssembly.Diagnostics.InspectorClient[0] connecting to ws://localhost:9400/launch-chrome-and-connect
[xUnit.net 00:00:21.18]     DebuggerTests.CustomViewTests.UsingDebuggerDisplay [FAIL]
[20:04:26] info: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] New test request
  Failed DebuggerTests.CustomViewTests.UsingDebuggerDisplay [1 ms]
  Error Message:
   System.Net.WebSockets.WebSocketException : The server returned status code '200' when status code '101' was expected.
  Stack Trace:
     at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.WebAssembly.Diagnostics.DevToolsClient.ConnectWithMainLoops(Uri uri, Func`3 receive, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DevToolsClient.cs:line 125
   at Microsoft.WebAssembly.Diagnostics.InspectorClient.Connect(Uri uri, Func`4 onEvent, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 59
   at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, Nullable`1 span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 214
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 137
```

**Comment by radical** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/76528 .
