### ISSUE TITLE
profiler unit test releaseondetach SIGABRT'ing with updated C# compiler / `!!` usage

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#64986]
This needs investigation.  Disabling the test for now after discussion with @davmason.
```
  Discovering: profiler.unittest.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  profiler.unittest.XUnitWrapper (found 4 test cases)
  Starting:    profiler.unittest.XUnitWrapper (parallel test collections = on, max threads = 4)
    profiler/unittest/releaseondetach/releaseondetach.sh [FAIL]
      Fatal error while logging another fatal error.
      Unhandled exception. System.Exception: Profilee returned exit code 134 instead of expected exit code 100.
         at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
         at Profiler.Tests.ReleaseOnShutdown.Main(String[] args)
      /root/helix/work/workitem/e/profiler/unittest/releaseondetach/releaseondetach.sh: line 431:    79 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.unittest/releaseondetach/releaseondetach.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false releaseondetach.dll ''
      Profiler path: /root/helix/work/workitem/e/profiler/unittest/releaseondetach/libProfiler.so
      Attaching profiler /root/helix/work/workitem/e/profiler/unittest/releaseondetach/libProfiler.so to self.
      Profiler.dll!DllGetClassObject
      Profiler.dll!Profiler::Initialize
      Initialize for attach started
      RequestProfilerDetach successful
      Profiler detach succeeded
      PROFILER TEST PASSES
      Gathering state for process 128 corerun
      Crashing thread 000000aa signal 00000006
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.128.dmp
      Written 90910720 bytes (22195 pages) to core file
      Dump successfully written
      
      Test failed: Profilee returned exit code 134 instead of expected exit code 100.
      Gathering state for process 79 corerun
      Crashing thread 0000004f signal 00000006
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.79.dmp
      Written 101101568 bytes (24683 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/profiler/unittest/releaseondetach/releaseondetach.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at profiler_unittest._releaseondetach_releaseondetach_._releaseondetach_releaseondetach_sh()
      Output:
        Fatal error while logging another fatal error.
        Unhandled exception. System.Exception: Profilee returned exit code 134 instead of expected exit code 100.
           at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
           at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
           at Profiler.Tests.ReleaseOnShutdown.Main(String[] args)
        /root/helix/work/workitem/e/profiler/unittest/releaseondetach/releaseondetach.sh: line 431:    79 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.unittest/releaseondetach/releaseondetach.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false releaseondetach.dll ''
        Profiler path: /root/helix/work/workitem/e/profiler/unittest/releaseondetach/libProfiler.so
        Attaching profiler /root/helix/work/workitem/e/profiler/unittest/releaseondetach/libProfiler.so to self.
        Profiler.dll!DllGetClassObject
        Profiler.dll!Profiler::Initialize
        Initialize for attach started
        RequestProfilerDetach successful
        Profiler detach succeeded
        PROFILER TEST PASSES
        Gathering state for process 128 corerun
        Crashing thread 000000aa signal 00000006
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.128.dmp
        Written 90910720 bytes (22195 pages) to core file
        Dump successfully written
        
        Test failed: Profilee returned exit code 134 instead of expected exit code 100.
        Gathering state for process 79 corerun
        Crashing thread 0000004f signal 00000006
        Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.79.dmp
        Written 101101568 bytes (24683 pages) to core file
        Dump successfully written
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/profiler/unittest/releaseondetach/releaseondetach.sh
  Finished:    profiler.unittest.XUnitWrapper
```

**Comment by tommcdon** [comment]
@davmason "!!" was reverted so we should be able to re-enable the test
