### ISSUE TITLE
System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest Failures

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#65065]
After https://github.com/dotnet/runtime/pull/64625, the mentioned test fails during outerloop runs on Linux

```
----- start Wed Feb 9 09:42:55 UTC 2022 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Ping.Functional.Tests.runtimeconfig.json --depsfile System.Net.Ping.Functional.Tests.deps.json xunit.console.dll System.Net.Ping.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Ping.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Ping.Functional.Tests (found 5 of 50 test cases)
  Starting:    System.Net.Ping.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest [FAIL]
      System.PlatformNotSupportedException : Unable to send custom ping payload. Run program under privileged user account or grant cap_net_raw capability using setcap(8).
      Stack Trace:
        /_/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.PingUtility.cs(32,0): at System.Net.NetworkInformation.Ping.GetPingProcess(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
        /_/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.PingUtility.cs(76,0): at System.Net.NetworkInformation.Ping.SendWithPingUtilityAsync(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
        /_/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.Unix.cs(36,0): at System.Net.NetworkInformation.Ping.SendPingAsyncCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
        /_/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs(402,0): at System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
        /_/src/libraries/System.Net.Ping/tests/FunctionalTests/PingTest.cs(680,0): at System.Net.NetworkInformation.Tests.PingTest.SendPingToExternalHostWithLowTtlTest()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Ping.Functional.Tests
=== TEST EXECUTION SUMMARY ===
```

**Comment by karelz** [comment]
Fixed in main (7.0) in PR #65312 and in 6.0.14 in PR #80692.
