### ISSUE TITLE
[wasm][windows] Assertion in `mono_method_get_vtable_slot` for `System.Threading.Channels.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65244]
Found on my debugging PR https://github.com/dotnet/runtime/pull/65178:

`Trace: * Assertion at D:/a/_work/1/s/src/mono/mono/metadata/class.c:1990, condition `<disabled>' not met`

Running on windows, with node.

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1608892&view=logs&j=a07e672c-d717-5036-7657-9f851d8c04dc&t=00a7b5ce-df8e-5072-ea20-a3ed92ab7ac8), and 
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65178-merge-e952e6fb82c348f5ad/c-WasmTestOnNodeJs-System.Threading.Channels.Tests/1/console.c28035c8.log?sv=2019-07-07&se=2022-03-04T02%3A45%3A48Z&sr=c&sp=rl&sig=byC%2Fx5TUxs3ySbhksM0xgVy%2BSXD5D7orxtvRHPKuxOI%3D)

Symbolicated trace:

```
[03:02:00] info: Starting:    System.Threading.Channels.Tests.dll
[03:02:01] fail: Trace: * Assertion at D:/a/_work/1/s/src/mono/mono/metadata/class.c:1990, condition `<disabled>' not met
[03:02:01] fail: 
[03:02:01] fail:     at Object.mono_wasm_trace_logger (C:\helix\work\workitem\e\dotnet.js:3:15099)
[03:02:01] fail:     at _mono_wasm_trace_logger (C:\helix\work\workitem\e\dotnet.js:12:108815)
[03:02:01] fail:     at wasm_trace_logger (<anonymous>:wasm-function[111]:0x9754)
[03:02:01] fail:     at eglib_log_adapter (<anonymous>:wasm-function[2506]:0xa2d4e)
[03:02:01] fail:     at monoeg_g_logv_nofree (<anonymous>:wasm-function[8420]:0x1b7ae2)
[03:02:01] fail:     at monoeg_assertion_message (<anonymous>:wasm-function[8423]:0x1b7b71)
[03:02:01] fail:     at mono_assertion_message (<anonymous>:wasm-function[8425]:0x1b7bb4)
[03:02:01] fail:     at mono_assertion_message_disabled (<anonymous>:wasm-function[8424]:0x1b7b87)
[03:02:01] fail:     at mono_method_get_vtable_slot (<anonymous>:wasm-function[566]:0x37eab)
[03:02:01] fail:     at apply_override (<anonymous>:wasm-function[754]:0x43c31)
[03:02:01] fail:     at mono_class_setup_vtable_general (<anonymous>:wasm-function[751]:0x42cda)
[03:02:01] fail:     at mono_class_setup_vtable_full (<anonymous>:wasm-function[749]:0x424fa)
[03:02:01] fail:     at mono_class_check_vtable_constraints (<anonymous>:wasm-function[748]:0x420f6)
[03:02:01] fail:     at mono_class_check_vtable_constraints (<anonymous>:wasm-function[748]:0x42166)
[03:02:01] fail:     at mono_class_vtable_checked (<anonymous>:wasm-function[1907]:0x84962)
[03:02:01] fail:     at generate_code (<anonymous>:wasm-function[327]:0x21247)
[03:02:01] fail:     at mono_interp_transform_method (<anonymous>:wasm-function[379]:0x28932)
[03:02:01] fail:     at do_transform_method (<anonymous>:wasm-function[223]:0x1a856)
[03:02:01] fail:     at interp_exec_method (<anonymous>:wasm-function[169]:0x18b9e)
[03:02:01] fail:     at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbcce)
[03:02:01] fail:     at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0c)
[03:02:01] fail:     at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f78)
[03:02:01] fail:     at mono_runtime_invoke_checked (<anonymous>:wasm-function[1898]:0x83eea)
[03:02:01] fail:     at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1261]:0x65229)
[03:02:01] fail:     at do_icall (<anonymous>:wasm-function[258]:0x1b6d8)
[03:02:01] fail:     at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1a)
[03:02:01] fail:     at interp_exec_method (<anonymous>:wasm-function[169]:0xce1a)
[03:02:01] fail:     at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbcce)
[03:02:01] fail:     at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0c)
[03:02:01] fail:     at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f78)
[03:02:01] fail:     at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845df)
[03:02:01] fail:     at tp_cb (<anonymous>:wasm-function[8148]:0x1b04e9)
[03:02:01] fail:     at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c4))
[03:02:01] fail:     at Object.Module._mono_background_exec [as mono_background_exec] (C:\helix\work\workitem\e\dotnet.js:12:135597)
[03:02:01] fail:     at Timeout.pump_message [as _onTimeout] (C:\helix\work\workitem\e\dotnet.js:3:70141)
[03:02:01] fail:     at listOnTimeout (internal/timers.js:554:17)
[03:02:01] fail:     at processTimers (internal/timers.js:497:7)
[03:02:01] fail: * Assertion at D:/a/_work/1/s/src/mono/mono/metadata/class.c:1990, condition `<disabled>' not met
[03:02:01] fail: 
[03:02:01] info: Process node.exe exited with 1
```

cc @vargaz

**Comment by ilonatommy** [comment]
@radical, running like this:
`dotnet build /t:Test src/libraries/System.Threading.Channels/tests /p:Configuration=Release /p:TargetOS=Browser /p:BrowserHost=Windows` I'm getting no errors. 
```
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 1119, Errors: 0, Failed: 0, Skipped: 35, Time: 17.075954s
```
I can't find the issue to be disabling tests anywhere neither in libs root nor directly in the Threading tests. Is it likely we're fine with this one already?
