### ISSUE TITLE
[Tests] System.Text.RegularExpressions System.InvalidProgramException : Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#65278]
```
System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(engine: SourceGenerated, cultureName: null, pattern: "[ac]*b+?", input: "aaab", options: None, expectedGroups: ["aaab"], altMatch: null) [FAIL]
      System.InvalidProgramException : Common Language Runtime detected an invalid program.
      Stack Trace:
           at C.GeneratedRegex_Get0_E95584BB.RunnerFactory.Runner.Go()
        /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexRunner.cs(171,0): at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
        /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs(386,0): at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
        /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.Match.cs(84,0): at System.Text.RegularExpressions.Regex.Match(String input)
        /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs(978,0): at System.Text.RegularExpressions.Tests.RegexGroupTests.Groups(RegexEngine engine, String cultureName, String pattern, String input, RegexOptions options, String[] expectedGroups, String altMatch)
        --- End of stack trace from previous location ---
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1606293&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&s=96ac2280-8cb4-5df5-99de-dd2da759617d
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64952-merge-bb663c35c087459bb8/System.Text.RegularExpressions.Tests/1/console.e38aa8a8.log?sv=2019-07-07&se=2022-03-03T01%3A58%3A49Z&sr=c&sp=rl&sig=8twS3bwRjJKf0aJthzMSrl8XnyO1gthfCqRNFarRKm0%3D

**Comment by joperezr** [comment]
Wow this is really weird since the engine seems to be the SourceGenerated one for this specific test. @stephentoub correct me if I'm wrong, but the way these tests work when using the source generator is that we emit the source, compile it, and then pass an engine that uses Compiled and will load this binary right?

**Comment by stephentoub** [comment]
> the way these tests work when using the source generator is that we emit the source, compile it, and then pass an engine that uses Compiled and will load this binary right?

We emit the source, compile it, load the assembly, get the Type we emitted for the Regex-derived type, and instantiate it.  The IL here would be generated by Roslyn.
https://github.com/dotnet/runtime/blob/01b0737028f146f598affb2276cea45609c776c9/src/libraries/System.Text.RegularExpressions/tests/RegexGeneratorHelper.netcoreapp.cs#L129-L166

**Comment by stephentoub** [comment]
The issue was opened yesterday, but it looks like the failure is actually from Thursday?  Could this be another symptom of https://github.com/dotnet/runtime/issues/64904, @AndyAyersMS?

**Comment by AndyAyersMS** [comment]
I think it's unlikely that https://github.com/dotnet/runtime/issues/64904 would lead to an invalid program exception.

[Diffs for that change](https://dev.azure.com/dnceng/public/_build/results?buildId=1598996&view=ms.vss-build-web.run-extensions-tab) don't show any x86 regex methods (though I am not super-confident we're covering the source generated methods).

**Comment by stephentoub** [comment]
> though I am not super-confident we're covering the source generated methods

I'm fairly confident they're _not_... the source generation in these tests happens while executing the tests... it dynamically spins up Roslyn, emits the IL to an in-memory stream, compiles to an in-memory binary, loads the binary into an ALC, and then gets the Type via reflection from that assembly and instantiates it.

**Comment by AndyAyersMS** [comment]
I suppose a codegen bug could lead to silently generating invalid IL which could lead to a subsequent invalid program exception trying to jit that IL. Maybe.

We plan on capturing SPMI data via actual runs (rather than via reflection/PMI), but don't do that yet in most places.

Did this only fail that one time?

**Comment by stephentoub** [comment]
> Did this only fail that one time?

I don't think we've seen such failure another time.  Maybe this was on Win11 and it's another symptom of that AVX issue?

**Comment by mdh1418** [comment]
I'm not sure what the AVX issue is, but I believe I saw this failure when there were a ton of failures on CI. I think the Windows Amd64 lanes were all having trouble https://dev.azure.com/dnceng/public/_build/results?buildId=1606293&view=ms.vss-test-web.build-test-results-tab. Perhaps it was resolved or a flake?
