### ISSUE TITLE
Test failure System.Text.Json.SourceGeneration.Tests.ConstructorTests_Default.MultipleThreadsLooping

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65291]
Run: [runtime-libraries-coreclr outerloop 20220213.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1610237&view=ms.vss-test-web.build-test-results-tab&runId=44860608&paneView=debug&resultId=103642)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Text.Json.SourceGeneration.Tests.ConstructorTests_Default.MultipleThreadsLooping

```
**Error message:**
```
System.Text.Json.JsonException : '0x0A' is invalid within a JSON string. The string should be correctly escaped. Path: $.MyTuple.Item4.MySimpleTestStruct.MyDateTime | LineNumber: 241 | BytePositionInLine: 192.
---- System.Text.Json.JsonReaderException : '0x0A' is invalid within a JSON string. The string should be correctly escaped. LineNumber: 241 | BytePositionInLine: 192.


Stack trace
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 264
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 114
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 15
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 55
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 310
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerContext context) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 0
   at System.Text.Json.SourceGeneration.Tests.StringSerializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/Serialization/JsonSerializerWrapper.cs:line 104
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|12_0(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 34
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|12_3(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 52
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|12_5(Type type) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 81
   at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 86
   at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 20
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.cs:line 279
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1365
   at System.Text.Json.Utf8JsonReader.ConsumeString() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1271
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 1036
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 879
   at System.Text.Json.Utf8JsonReader.Read() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs:line 278
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack
```

**Comment by adamsitnik** [comment]
It has been most likely fixed by https://github.com/dotnet/runtime/pull/65490. I am going to close the issue, please reopen it if it fails again.
