### ISSUE TITLE
[wasm] Runtime crashes in `System.Text.Json`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65336]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1612165&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89), on https://github.com/dotnet/runtime/pull/65178 which runs each of the library tests 6 times.
These failures were on nodejs, which I'll add as comments.

**Comment by radical** [comment]
```
Trace: /__w/1/s/src/mono/mono/mini/../../mono/sgen/sgen-array-list.h:112 <disabled>
    at Object.mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/C1660A5B/e/dotnet.js:3:15099)
    at _mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/C1660A5B/e/dotnet.js:12:108815)
    at wasm_trace_logger (<anonymous>:wasm-function[111]:0x9755)
    at eglib_log_adapter (<anonymous>:wasm-function[2506]:0xa2d4f)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[8420]:0x1b7ae3)
    at monoeg_g_log (<anonymous>:wasm-function[8421]:0x1b7b14)
    at g_log_disabled (<anonymous>:wasm-function[8422]:0x1b7b47)
    at sgen_array_list_get_slot (<anonymous>:wasm-function[2744]:0xaa6d1)
    at sgen_get_complex_descriptor (<anonymous>:wasm-function[2743]:0xaa6ab)
    at drain_gray_stack (<anonymous>:wasm-function[2901]:0xb36be)
    at sgen_drain_gray_stack (<anonymous>:wasm-function[2768]:0xab2b4)
    at finish_gray_stack (<anonymous>:wasm-function[2802]:0xadbf2)
    at major_do_collection (<anonymous>:wasm-function[2779]:0xac0c8)
    at sgen_perform_collection_inner (<anonymous>:wasm-function[2776]:0xab67d)
    at sgen_perform_collection (<anonymous>:wasm-function[2774]:0xab4f9)
    at sgen_ensure_free_space (<anonymous>:wasm-function[2773]:0xab4a0)
    at sgen_los_alloc_large_inner (<anonymous>:wasm-function[2859]:0xb03bd)
    at sgen_alloc_obj_nolock (<anonymous>:wasm-function[2712]:0xa98e9)
    at mono_gc_alloc_string (<anonymous>:wasm-function[2451]:0x9d6a0)
    at mono_string_new_size_handle (<anonymous>:wasm-function[1915]:0x85703)
    at ves_icall_System_String_FastAllocateString_raw (<anonymous>:wasm-function[1367]:0x6c41e)
    at do_icall (<anonymous>:wasm-function[258]:0x1b640)
    at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1b)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xce1b)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (/datadisks/disk1/work/AD3B0951/w/C1660A5B/e/dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (/datadisks/disk1/work/AD3B0951/w/C1660A5B/e/dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
/__w/1/s/src/mono/mono/mini/../../mono/sgen/sgen-array-list.h:112 <disabled>
Process node exited with 1

```

**Comment by radical** [comment]
```
Trace: * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/class.c:2227

    at Object.mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/B55E094D/e/dotnet.js:3:15099)
    at _mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/B55E094D/e/dotnet.js:12:108815)
    at wasm_trace_logger (<anonymous>:wasm-function[111]:0x9755)
    at eglib_log_adapter (<anonymous>:wasm-function[2506]:0xa2d4f)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[8420]:0x1b7ae3)
    at monoeg_assertion_message (<anonymous>:wasm-function[8423]:0x1b7b72)
    at mono_assertion_message_unreachable (<anonymous>:wasm-function[8426]:0x1b7bdb)
    at mono_class_from_mono_type_internal (<anonymous>:wasm-function[511]:0x36428)
    at ves_icall_RuntimeTypeHandle_IsInstanceOfType_raw (<anonymous>:wasm-function[1363]:0x6befa)
    at wasm_invoke_iii (<anonymous>:wasm-function[8217]:0x1b1295)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xd620)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (/datadisks/disk1/work/AD3B0951/w/B55E094D/e/dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (/datadisks/disk1/work/AD3B0951/w/B55E094D/e/dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
* Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/class.c:2227
```

**Comment by radical** [comment]
```
Trace: * Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2171, condition `<disabled>' not met

    at Object.mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/AC1E08D3/e/dotnet.js:3:15099)
    at _mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/AC1E08D3/e/dotnet.js:12:108815)
    at wasm_trace_logger (<anonymous>:wasm-function[111]:0x9755)
    at eglib_log_adapter (<anonymous>:wasm-function[2506]:0xa2d4f)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[8420]:0x1b7ae3)
    at monoeg_assertion_message (<anonymous>:wasm-function[8423]:0x1b7b72)
    at mono_assertion_message (<anonymous>:wasm-function[8425]:0x1b7bb5)
    at mono_assertion_message_disabled (<anonymous>:wasm-function[8424]:0x1b7b88)
    at mono_class_from_mono_type_internal (<anonymous>:wasm-function[511]:0x36447)
    at ves_icall_RuntimeTypeHandle_HasInstantiation (<anonymous>:wasm-function[1144]:0x5cb15)
    at wasm_invoke_ii (<anonymous>:wasm-function[8197]:0x1b0df7)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xd620)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[1898]:0x83eeb)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1261]:0x6522a)
    at do_icall (<anonymous>:wasm-function[258]:0x1b6d9)
    at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1b)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xce1b)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (/datadisks/disk1/work/AD3B0951/w/AC1E08D3/e/dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (/datadisks/disk1/work/AD3B0951/w/AC1E08D3/e/dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
* Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2171, condition `<disabled>' not met
```

**Comment by radical** [comment]
```
Trace: * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-object.h:91

    at Object.mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/AC8708EE/e/dotnet.js:3:15099)
    at _mono_wasm_trace_logger (/datadisks/disk1/work/AD3B0951/w/AC8708EE/e/dotnet.js:12:108815)
    at wasm_trace_logger (<anonymous>:wasm-function[111]:0x9755)
    at eglib_log_adapter (<anonymous>:wasm-function[2506]:0xa2d4f)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[8420]:0x1b7ae3)
    at monoeg_assertion_message (<anonymous>:wasm-function[8423]:0x1b7b72)
    at mono_assertion_message_unreachable (<anonymous>:wasm-function[8426]:0x1b7bdb)
    at drain_gray_stack (<anonymous>:wasm-function[2901]:0xb3a56)
    at sgen_drain_gray_stack (<anonymous>:wasm-function[2768]:0xab2b4)
    at finish_gray_stack (<anonymous>:wasm-function[2802]:0xadbf2)
    at major_do_collection (<anonymous>:wasm-function[2779]:0xac0c8)
    at sgen_perform_collection_inner (<anonymous>:wasm-function[2776]:0xab67d)
    at sgen_perform_collection (<anonymous>:wasm-function[2774]:0xab4f9)
    at sgen_ensure_free_space (<anonymous>:wasm-function[2773]:0xab4a0)
    at sgen_los_alloc_large_inner (<anonymous>:wasm-function[2859]:0xb03bd)
    at sgen_alloc_obj_nolock (<anonymous>:wasm-function[2712]:0xa98e9)
    at mono_gc_alloc_string (<anonymous>:wasm-function[2451]:0x9d6a0)
    at mono_string_new_size_handle (<anonymous>:wasm-function[1915]:0x85703)
    at ves_icall_System_String_FastAllocateString_raw (<anonymous>:wasm-function[1367]:0x6c41e)
    at do_icall (<anonymous>:wasm-function[258]:0x1b640)
    at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1b)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xce1b)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[1898]:0x83eeb)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1261]:0x6522a)
    at do_icall (<anonymous>:wasm-function[258]:0x1b6d9)
    at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1b)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xce1b)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (/datadisks/disk1/work/AD3B0951/w/AC8708EE/e/dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (/datadisks/disk1/work/AD3B0951/w/AC8708EE/e/dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
* Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-object.h:91
```

**Comment by radical** [comment]
cc @radekdoulik

**Comment by radical** [comment]
This started with the 2.0.34 bump, which has been [rolled back](https://github.com/dotnet/runtime/pull/65517) now.
