### ISSUE TITLE
[wasm] runtime crashes in `System.Threading.Channels.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65337]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1612165&view=logs&j=a07e672c-d717-5036-7657-9f851d8c04dc&t=00a7b5ce-df8e-5072-ea20-a3ed92ab7ac8), on https://github.com/dotnet/runtime/pull/65178 which runs each of the library tests 6 times.
These failures were on *nodejs*, on *windows*, which I'll add as comments.

cc @radekdoulik

**Comment by radical** [comment]
```
RuntimeError: memory access out of bounds
    at alloc_obj (<anonymous>:wasm-function[2905]:0xb5c35)
    at major_alloc_object (<anonymous>:wasm-function[2896]:0xb20ef)
    at alloc_for_promotion (<anonymous>:wasm-function[2985]:0xb8826)
    at copy_object_no_checks.1 (<anonymous>:wasm-function[2991]:0xb9837)
    at simple_nursery_serial_scan_object (<anonymous>:wasm-function[2989]:0xb94e8)
    at simple_nursery_serial_drain_gray_stack (<anonymous>:wasm-function[2986]:0xb8891)
    at sgen_drain_gray_stack (<anonymous>:wasm-function[2768]:0xab2b4)
    at finish_gray_stack (<anonymous>:wasm-function[2802]:0xadbf2)
    at collect_nursery (<anonymous>:wasm-function[2778]:0xabd62)
    at sgen_perform_collection_inner (<anonymous>:wasm-function[2776]:0xab5a3)
    at sgen_perform_collection (<anonymous>:wasm-function[2774]:0xab4f9)
    at sgen_ensure_free_space (<anonymous>:wasm-function[2773]:0xab4a0)
    at sgen_alloc_obj_nolock (<anonymous>:wasm-function[2712]:0xa99da)
    at mono_gc_alloc_obj (<anonymous>:wasm-function[2440]:0x9d2cc)
    at interp_exec_method (<anonymous>:wasm-function[169]:0x122cb)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[1898]:0x83eeb)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1261]:0x6522a)
    at do_icall (<anonymous>:wasm-function[258]:0x1b6d9)
    at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1b)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xce1b)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (C:\helix\work\workitem\e\dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (C:\helix\work\workitem\e\dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Process node.exe exited with 7

```

**Comment by radical** [comment]
```
RuntimeError: memory access out of bounds
    at m_class_is_valuetype (<anonymous>:wasm-function[219]:0x1a7e3)
    at interp_exec_method (<anonymous>:wasm-function[169]:0x18ae5)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (C:\helix\work\workitem\e\dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (C:\helix\work\workitem\e\dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Process node.exe exited with 7
```

**Comment by radical** [comment]
```
RuntimeError: divide by zero
    at sgen_evacuation_freelist_blocks (<anonymous>:wasm-function[2914]:0xb6375)
    at major_start_major_collection (<anonymous>:wasm-function[2881]:0xb0e62)
    at major_start_collection (<anonymous>:wasm-function[2803]:0xae0cb)
    at major_do_collection (<anonymous>:wasm-function[2779]:0xac06d)
    at sgen_perform_collection_inner (<anonymous>:wasm-function[2776]:0xab67d)
    at sgen_perform_collection (<anonymous>:wasm-function[2774]:0xab4f9)
    at sgen_ensure_free_space (<anonymous>:wasm-function[2773]:0xab4a0)
    at sgen_los_alloc_large_inner (<anonymous>:wasm-function[2859]:0xb03bd)
    at sgen_alloc_obj_nolock (<anonymous>:wasm-function[2712]:0xa98e9)
    at mono_gc_alloc_vector (<anonymous>:wasm-function[2450]:0x9d628)
    at mono_array_new_specific_internal (<anonymous>:wasm-function[1982]:0x8855c)
    at mono_array_new_specific_checked (<anonymous>:wasm-function[1981]:0x884a3)
    at interp_exec_method (<anonymous>:wasm-function[169]:0x144d5)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[1898]:0x83eeb)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1261]:0x6522a)
    at do_icall (<anonymous>:wasm-function[258]:0x1b6d9)
    at do_icall_wrapper (<anonymous>:wasm-function[229]:0x1ad1b)
    at interp_exec_method (<anonymous>:wasm-function[169]:0xce1b)
    at interp_runtime_invoke (<anonymous>:wasm-function[168]:0xbccf)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7732]:0x196d0d)
    at do_runtime_invoke (<anonymous>:wasm-function[1900]:0x83f79)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[1904]:0x845e0)
    at tp_cb (<anonymous>:wasm-function[8148]:0x1b04ea)
    at mono_background_exec (<anonymous>:mono_background_exec (wasm-function[2663]:0xa84c5))
    at Object.Module._mono_background_exec [as mono_background_exec] (C:\helix\work\workitem\e\dotnet.js:12:135597)
    at Timeout.pump_message [as _onTimeout] (C:\helix\work\workitem\e\dotnet.js:3:70141)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Process node.exe exited with 7
```

**Comment by radical** [comment]
This started with the 2.0.34 bump, which has been [rolled back](https://github.com/dotnet/runtime/pull/65517) now.
