### ISSUE TITLE
[mono] gshared calls to non-generic static virtual interface method throw BadImageFormatException: Method has no body

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#65384]
Build and run this sample with mono (for example in src/mono/sample/HelloWorld/Program.cs):

```csharp
using System;
using System.IO;
using CancellationToken = System.Threading.CancellationToken;
using System.Threading.Tasks;

namespace NetStuff
{
    public interface IReadWriteAdapter {
	static abstract ValueTask<int> ReadAsync(Stream stream, Memory<byte> buffer, CancellationToken cancellationToken);
	static abstract void WriteAsync(Stream stream, byte[] buffer, int offset, int count);
    }

    public struct Message {
	public byte[] Payload {get; init;}
	public int Size => Payload.Length;
    }

    public class P {
	public void ForceAuthenticationAsync<TIOAdapter>(Stream innerStream, in Message message)
	    where TIOAdapter : IReadWriteAdapter
	{
	    TIOAdapter.WriteAsync (innerStream, message.Payload, 0, message.Size);
	}
    }

    public class AsyncReadWriteAdapter : IReadWriteAdapter {
	public static ValueTask<int> ReadAsync (Stream stream, Memory<byte> buffer, CancellationToken cancellationToken) => stream.ReadAsync(buffer, cancellationToken);

	// doesn't work
	public static void WriteAsync (Stream stream, byte[] buffer, int offset, int count) {
	    stream.WriteAsync(new ReadOnlyMemory<byte>(buffer, offset, count), default).AsTask().Wait();
	}

    }
}

namespace HelloWorld
{
    internal class Program
    {
        private static void Main(string[] args)
        {
	    var s = new MemoryStream(capacity: 1024);
	    var buf = new byte[] {0x01, 0x02, 0x03};
	    var message = new NetStuff.Message { Payload = buf };

	    var p  = new NetStuff.P ();
	    p.ForceAuthenticationAsync<NetStuff.AsyncReadWriteAdapter>(s, message);

	    s.Seek (0, SeekOrigin.Begin);
	    var res = new byte[buf.Length];
	    s.Read (new (res));
	    for (int i = 0; i < buf.Length; ++i)
		if (res[i] != buf[i])
		    throw new Exception ($"result differs at index {i}, expected {buf[i]}, got {res[i]}");
	    Console.WriteLine ("done");
        }
    }
}
```

Expected result:

```console
done
```

Actual result:

```console
Unhandled Exception:
System.BadImageFormatException: Method has no body
File name: 'HelloWorld'
   at NetStuff.P.ForceAuthenticationAsync[AsyncReadWriteAdapter](Stream innerStream, Message& message) in /Users/alklig/work/dotnet-runtime/runtime-bugs/src/mono/sample/HelloWorld/Program.cs:line 25
   at HelloWorld.Program.Main(String[] args) in /Users/alklig/work/dotnet-runtime/runtime-bugs/src/mono/sample/HelloWorld/Program.cs:line 51
[ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Method has no body
File name: 'HelloWorld'
   at NetStuff.P.ForceAuthenticationAsync[AsyncReadWriteAdapter](Stream innerStream, Message& message) in /Users/alklig/work/dotnet-runtime/runtime-bugs/src/mono/sample/HelloWorld/Program.cs:line 25
   at HelloWorld.Program.Main(String[] args) in /Users/alklig/work/dotnet-runtime/runtime-bugs/src/mono/sample/HelloWorld/Program.cs:line 51
```

Note:

changing the sample to `interface IReadWriteAdapter<T> where T: IReadWriteAdapter<T> { ... }` (and updating the use sites) makes the sample work.

Note 2:

`MONO_ENV_OPTIONS=--interp` or `MONO_ENV_OPTIONS=--optimize=-gshared` makes the repro work.

**Comment by stephentoub** [comment]
> I think we just completely bypass that stuff

That's...exciting :)

**Comment by lambdageek** [comment]
> [turning on vtable setup tracing](https://github.com/dotnet/runtime/blob/a14d27ac7ff3a58e39d889db72f7ce682c7492fd/src/mono/mono/metadata/class-setup-vtable.c#L372-L373) I don't even see `IReadWriteAdapter` or `AsyncReadWriteAdapter` in the output. I think we just completely bypass that stuff

no, this was wrong.  I think I had a stale build.

```
*** Vtable for class 'NetStuff.AsyncReadWriteAdapter' at "FINALLY" (size 8)
  [O][000][INDEX 000] object:GetHashCode () [0x7fd8c104cf48]
  [O][001][INDEX 001] object:Equals (object) [0x7fd8c104cf20]
  [O][002][INDEX 002] object:ToString () [0x7fd8c104cef8]
  [O][003][INDEX 003] object:Finalize () [0x7fd8c104ced0]
  [I][004][INDEX 004] NetStuff.AsyncReadWriteAdapter:ReadAsync (System.IO.Stream,System.Memory`1<byte>,System.Threading.CancellationToken) [0x7fd8e1035378]
  [I][005][INDEX 005] NetStuff.AsyncReadWriteAdapter:WriteAsync (System.IO.Stream,byte[],int,int,System.Threading.CancellationToken) [0x7fd8e10353c8]
  [I][006][INDEX 006] NetStuff.AsyncReadWriteAdapter:FlushAsync (System.IO.Stream,System.Threading.CancellationToken) [0x7fd8e1035418]
  [I][007][INDEX 007] NetStuff.AsyncReadWriteAdapter:WaitAsync (System.Threading.Tasks.TaskCompletionSource`1<bool>) [0x7fd8e1035468]
```

What is interesting, however is that runnign with `MONO_ENV_OPTIONS=--optimize=-gshared` (or with `MONO_ENV_OPTIONS=--interp`) makes the test case work.

So it's something in generic sharing in the JIT.

**Comment by stephentoub** [comment]
> So it's something in generic sharing in the JIT.

I pushed a change to switch the implementing types from classes to structs.  Your statement means there's a good chance then we'll see the issue go away for that specific PR, right? :popcorn:

**Comment by lambdageek** [comment]
> > So it's something in generic sharing in the JIT.
> 
> I pushed a change to switch the implementing types from classes to structs. Your statement means there's a good chance then we'll see the issue go away for that specific PR, right? 🍿

Yep 😞
