### ISSUE TITLE
Test failure System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65417]
Run: [runtime-libraries-coreclr outerloop 20220215.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1613576&view=ms.vss-test-web.build-test-results-tab&runId=44921124&paneView=debug&resultId=104290)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

```
**Error message:**
```
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Collections.Concurrent.ConcurrentDictionary`2.GrowTable(Tables tables) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1983
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, Nullable`1 nullableHashcode, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 993
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExp
```

**Comment by stephentoub** [comment]
cc: @olsaarik

**Comment by stephentoub** [comment]
This test is constructing ~18k regexes with nonbacktracking. And the failure is on 32-bit. Do we have a cache that might be preventing state from being collected?

**Comment by olsaarik** [comment]
There's a static instance of `UnicodeCategoryTheory` in `SymbolicRegexRunnerFactory`, which transitively holds an instance of `BDDAlgebra`. It's there due to the high startup cost of initializing the BDD for the case insensitivity relation. We're planning on removing that and having per-Regex BDD algebras once case insensitivity is handled in the parser.

**Comment by VincentBu** [comment]
Failed again in:[ runtime-libraries-coreclr outerloop 20220228.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1635742&view=ms.vss-test-web.build-test-results-tab&runId=45295412&resultId=104123&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

```
**Error message:**
```
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Collections.Concurrent.ConcurrentDictionary`2.GrowTable(Tables tables) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1983
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, Nullable`1 nullableHashcode, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 993
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.<>c.<ApplyBinaryOp>b__8_0(ValueTuple`3 key, BDDAlgebra algebra) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 176
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1177
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.ApplyBinaryOp(BoolOp op, BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 0
   at System.Text.RegularExpressions.Symbolic.BDDAlgebra.And(BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/BDDAlgebra.cs:line 69
   at System.Text.RegularExpressions.Symbolic.MintermGenerator`1.PartitionTree.Refine(IBooleanAlgebra`1 solver, TPredicate other) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/MintermGenerator.cs:line 100
   at System.Text.RegularExpressions.Symbolic.MintermGenerator`1.PartitionTree.Refine(IBooleanAlgebra`1 solver, TPredicate other) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/Algebras/MintermGenerator.cs:line 100
   at System.Text.RegularExpressions.Symbolic.MintermGenerator`1.PartitionTree.Refine(IBooleanAlgebra`1 solver, TPredicate other) in /_/src/libraries/
```

**Comment by VincentBu** [comment]
Failed again in:[ runtime-libraries-coreclr outerloop 20220315.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1664094&view=ms.vss-test-web.build-test-results-tab&runId=45773888&resultId=104148&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.2110.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.10-helix-arm64v8-20211116135000-0f8d97e
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20210913123654-4f64125
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Ubuntu.2110.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.04-helix-amd64-20210922170909-34a2d72
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Debian.11.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64-20210304164428-5a7c380
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(Centos.7.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20210714125435-dde38af
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-x64-CoreCLR_release-(openSUSE.15.2.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-15.2-helix-amd64-20211018152525-9cc02fe
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking


net7.0-Linux-Release-x64-CoreCLR_release-(Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-Linux-Release-arm-CoreCLR_release-(Debian.10.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-20210304164340-6616c63
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open
- System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking
```
**Error message:**
```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'options')


Stack trace
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument arg) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/ThrowHelper.cs:line 20
   at System.Text.RegularExpressions.Regex.ValidateOptions(RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 143
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 81
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 52
   at System.Text.RegularExpressions.Tests.RegexHelpers.GetRegexAsync(RegexEngine engine, String pattern, Nullable`1 options, Nullable`1 matchTimeout) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Tests.Common.cs:line 119
   at System.Text.RegularExpressions.Tests.RegexKnownPatternTests.PatternsDataSet_ConstructRegexForAll_NonBacktracking() in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.KnownPattern.Tests.cs:line 1436
--- End of stack trace from previous location ---
```

**Comment by stephentoub** [comment]
That last one is a different error.  I've fixed that in https://github.com/dotnet/runtime/pull/66693.
