### ISSUE TITLE
RevokeEndEntityWithInvalidRevocationName failed 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#65421]
Windows 11 x64

```
      <test name="System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocationName(pkiOptions: IssuerRevocationViaOcsp | EndEntityRevocationViaCrl | RootAuthorityHasDesignatedOcspResponder)" type="System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests" method="RevokeEndEntityWithInvalidRevocationName" time="36.6675043" result="Fail">
        <traits>
          <trait name="category" value="outerloop" />
        </traits>
        <failure exception-type="System.AggregateException">
          <message><![CDATA[System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)) (Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)) (Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)) (Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)) (Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1))
---- Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)
---- Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)
---- Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)
---- Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)
---- Assert.Equal() Failure
                    ↓ (pos 1)
Expected: [NoError, NoError, RevocationStatusUnknown | Offlin···
Actual:   [NoError, RevocationStatusUnknown | OfflineRevocati···
                    ↑ (pos 1)]]></message>
          <stack-trace><![CDATA[   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 48
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.SimpleTest(PkiOptions pkiOptions, RunSimpleTest callback, String callerName, Boolean pkiOptionsInTestName) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1530
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocationName(PkiOptions pkiOptions) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 909
----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1570
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RunWithInconclusiveEndEntityRevocation(ChainHolder holder, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1310
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocation(ChainHolder holder, CertificateAuthority intermediate, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1242
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c.<RevokeEndEntityWithInvalidRevocationName>b__29_0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 915
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_2.<SimpleTest>b__0() in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1540
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 40
----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1570
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RunWithInconclusiveEndEntityRevocation(ChainHolder holder, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1310
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocation(ChainHolder holder, CertificateAuthority intermediate, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1242
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c.<RevokeEndEntityWithInvalidRevocationName>b__29_0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 915
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_2.<SimpleTest>b__0() in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1540
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 40
----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1570
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RunWithInconclusiveEndEntityRevocation(ChainHolder holder, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1310
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocation(ChainHolder holder, CertificateAuthority intermediate, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1242
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c.<RevokeEndEntityWithInvalidRevocationName>b__29_0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 915
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_2.<SimpleTest>b__0() in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1540
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 40
----- Inner Stack Trace #4 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1570
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RunWithInconclusiveEndEntityRevocation(ChainHolder holder, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1310
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocation(ChainHolder holder, CertificateAuthority intermediate, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1242
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c.<RevokeEndEntityWithInvalidRevocationName>b__29_0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 915
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_2.<SimpleTest>b__0() in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1540
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 40
----- Inner Stack Trace #5 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1570
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RunWithInconclusiveEndEntityRevocation(ChainHolder holder, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1310
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntityWithInvalidRevocation(ChainHolder holder, CertificateAuthority intermediate, X509Certificate2 endEntity) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1242
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c.<RevokeEndEntityWithInvalidRevocationName>b__29_0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 915
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_2.<SimpleTest>b__0() in C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\tests\RevocationTests\DynamicRevocationTests.cs:line 1540
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in C:\git\runtime\src\libraries\Common\tests\TestUtilities\System\RetryHelper.cs:line 40]]></stack-trace>
        </failure>
```

**Comment by bartonjs** [comment]
In our current Kusto history it looks like one machine was in a bad state once and failed this test with WindowsCryptographicException; there's no indication of the failure as reported.

As this test requires networking (over loopback into HttpListener), it's subject to occasional flakiness, and that seems to be all that happened here.
