### ISSUE TITLE
Test failure System.IO.Compression.ZLibStreamUnitTests.ReadWrite_Success

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65476]
Run: [runtime-coreclr libraries-jitstress 20220215.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1615617&view=ms.vss-test-web.build-test-results-tab&runId=44957626&paneView=debug&resultId=133897)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-zapdisable-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.IO.Compression.ZLibStreamUnitTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 10240, startWithFlush: False)

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.IO.ConnectedStreams.BidirectionalStreamBufferStream.Dispose(Boolean disposing) in /_/src/libraries/Common/tests/System/IO/ConnectedStreams.cs:line 299
   at System.IO.Stream.Close()
   at System.IO.Compression.DeflateStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 655
   at System.IO.Stream.Close()
   at System.IO.Compression.ZLibStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:line 252
   at System.IO.Stream.Close()
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1729
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment]
I can't see any scenario where this field could be `null` as it's created only in one place, with non-nullable objects as arguments:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/tests/System/IO/ConnectedStreams.cs#L69-L77

Since it failed in jitstress CI leg and we have hit codegen arm64-specific issues very recently, I am going to move it to codegen area

**Comment by BruceForstall** [comment]
I see a consistent failure in `System.IO.Compression.ZLibStreamUnitTests.ReadTimeout_Expires_Throws` with GCStress=C and:
```
COMPlus_TieredCompilation=0
COMPlus_ReadyToRun=0
COMPlus_ZapDisable=1
```

```
  Starting:    System.IO.Compression.Tests (parallel test collections = on, max threads = 4)
    System.IO.Compression.ZLibStreamUnitTests.ReadTimeout_Expires_Throws [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /home/bruce/gh/runtime2/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs(57,0): at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
        /home/bruce/gh/runtime2/src/libraries/System.IO.Compression/tests/CompressionStreamUnitTests.ZLib.cs(13,0): at System.IO.Compression.ZLibStreamUnitTests.CreateStream(Stream stream, CompressionMode mode)
        /home/bruce/gh/runtime2/src/libraries/Common/tests/System/IO/Compression/CompressionStreamTestBase.cs(46,0): at System.IO.Compression.CompressionStreamTestBase.CreateConnectedStreamsAsync()
        /home/bruce/gh/runtime2/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2475,0): at System.IO.Tests.ConnectedStreamConformanceTests.ReadTimeout_Expires_Throws()
        --- End of stack trace from previous location ---
  Finished:    System.IO.Compression.Tests
```

Without GCStress I don't see a failure, so there is likely a GC hole somewhere.

**Comment by BruceForstall** [comment]
Smaller repro:

```
COMPlus_TieredCompilation=0
COMPlus_GCStress=4

pushd /home/brucefo/build/runtime/artifacts/bin/System.IO.Compression.Tests/Release/net7.0-unix
/home/brucefo/build/runtime/artifacts/bin/testhost/net7.0-Linux-Release-arm64/dotnet xunit.console.dll System.IO.Compression.Tests.dll -method System.IO.Compression.ZLibStreamUnitTests.ReadTimeout_Expires_Throws
```

**Comment by BruceForstall** [comment]
It also fails on win-arm64.

**Comment by BruceForstall** [comment]
It looks like there's a GC hole in `System.IO.Compression.CompressionStreamTestBase:CreateConnectedStreamsAsync():System.Threading.Tasks.Task`1[[System.IO.Tests.StreamPair, StreamConformanceTests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]]:this`:
```
G_M38498_IG02:        ; gcrefRegs=80000 {x19}, byrefRegs=0000 {}, byref
        52820000          mov     w0, #0x100
        52880001          mov     w1, #0x4000
        94000000          bl      System.IO.ConnectedStreams:CreateBidirectional(int,int):System.ValueTuple`2[[System.IO.Stream, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Stream, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
                             ; gcrRegs +[x0-x1]
        F9000FA0          str     x0, [fp,#24]
                             ; GC ptr vars +{V15}
        AA0103F4          mov     x20, x1
                             ; gcrRegs +[x20]
        AA1303E0          mov     x0, x19
        F9400FA1          ldr     x1, [fp,#24]  // [V15 tmp12]
        52800022          mov     w2, #1
        F9400263          ldr     x3, [x19]
        F9404C75          ldr     x21, [x3,#152]
        F94002A3          ldr     x3, [x21]
                             ; GC ptr vars -{V15}
        D63F0060          blr     x3
                             ; gcrRegs -[x1 x20]               // here we kill x20 after the call -- but it is still live
        AA0003F6          mov     x22, x0
                             ; gcrRegs +[x22]
        AA1303E0          mov     x0, x19
        AA1403E1          mov     x1, x20               // but here we copy it to x1, and mark it as a live gc reg
                             ; gcrRegs +[x1]
        2A1F03E2          mov     w2, wzr
        F94002A3          ldr     x3, [x21]
        D63F0060          blr     x3
                             ; gcrRegs -[x1 x19]
```

**Comment by BruceForstall** [comment]
In `CodeGen::genMultiRegStoreToLocal()` for a STORE_LCL_VAR of 2 promoted fields where one (or more) has an enregistered GC ref:
```
                                                             /--*  t2     struct
Generating: N015 ( 20, 11) [000006] MA-XG-------              *  STORE_LCL_VAR struct<System.ValueTuple`2[[System.IO.Stream, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.IO.Stream, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], 16>(P) V04 tmp1          NA
                                                  *    ref    V04.Item1 (offs=0x00) -> V15 tmp12
                                                  *    ref    V04.Item2 (offs=0x08) -> V16 tmp13         x20 REG NA,x20
                                                        GC regs: 80003 {x0 x1 x19} => 80000 {x19}
IN0004:                           str     x0, [fp,#24]
IN0005:                           mov     x20, x1
                                                        V16 in reg x20 is becoming live  [000006]
                                                        Live regs: 80000 {x19} => 180000 {x19 x20}
                                                        Live vars: {V00} => {V00 V15 V16}
                                                        GCvars: {} => {V15}
```
the code sets `hasRegs = true;` and then calls `genProduceReg`. However, `if (tree->gtHasReg())` fails on the STORE_LCL_VAR (STRUCT V4) node and so the the code (that is there) to update each member of the multi-reg liveness doesn't get invoked. So, it doesn't get added to the gcref tracking sets.

**Comment by BruceForstall** [comment]
This was exposed by https://github.com/dotnet/runtime/pull/64857, but that isn't the cause.

The issue is when a multi-reg return (here, STORE_LCL_VAR) does not enregister the first field: GenTree::gtHasReg() is used to determine if there is a register for a node, and even for multi-reg fields, it was only checking the first register. It needs to check for all of them.

**Comment by MaximLipnin** [comment]
It's still being hit on CI:
Configuration: `net7.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.314.Arm64.Open)`
Build: [runtime pipeline of the rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1635569&view=ms.vss-test-web.build-test-results-tab&runId=45291100&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=193289), [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-99e8ee203ca942198a/System.IO.Compression.Tests/1/console.7b899b97.log?sv=2019-07-07&se=2022-03-20T08%3A51%3A17Z&sr=c&sp=rl&sig=B7lABFJmvCIHQUmLsW0TaKDmZUlghnmVZ3VaHkjWMYI%3D)

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220227.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1635524&view=ms.vss-test-web.build-test-results-tab&runId=45291652&resultId=129860&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open

- System.IO.Compression.ZLibStreamUnitTests.ReadWrite_Success(mode: SyncByte, writeSize: 42, startWithFlush: False)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open

- System.IO.Compression.GzipStreamUnitTests.ReadWrite_Success(mode: AsyncMemory, writeSize: 42, startWithFlush: False)

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.IO.ConnectedStreams.BidirectionalStreamBufferStream.Dispose(Boolean disposing) in /_/src/libraries/Common/tests/System/IO/ConnectedStreams.cs:line 299
   at System.IO.Stream.Close()
   at System.IO.Compression.DeflateStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 645
   at System.IO.Stream.Close()
   at System.IO.Compression.ZLibStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/ZLibStream.cs:line 252
   at System.IO.Stream.Close()
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1729
--- End of stack trace from previous location ---
```
