### ISSUE TITLE
[wasm] running tests on NodeJs fails with `globalThis is not defined`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65485]
Hitting this on the [emscripten bump PR](https://github.com/dotnet/runtime/pull/63894). 
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1617351&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89&l=539):

```
[01:27:29] fail: /datadisks/disk1/work/A3DA08F7/w/B1B30976/e/test-main.js:97
[01:27:29] fail: if (typeof globalThis.crypto === 'undefined') {
[01:27:29] fail: ^
[01:27:29] fail: 
[01:27:29] fail: ReferenceError: globalThis is not defined
[01:27:29] fail:     at Object.<anonymous> (/datadisks/disk1/work/A3DA08F7/w/B1B30976/e/test-main.js:97:1)
[01:27:29] fail:     at Module._compile (internal/modules/cjs/loader.js:778:30)
[01:27:29] fail:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[01:27:29] fail:     at Module.load (internal/modules/cjs/loader.js:653:32)
[01:27:29] fail:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[01:27:29] fail:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[01:27:29] fail:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[01:27:29] fail:     at startup (internal/bootstrap/node.js:283:19)
[01:27:29] fail:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[01:27:29] info: Process node exited with 1
```

I'm disabling nodejs test runs for that PR.

cc @pavelsavara @maraf

**Comment by lewing** [comment]
I'm not sure what is happening here but it looks like a node specific case at this point, @maraf please work with @radekdoulik to look into it

**Comment by pavelsavara** [comment]
This looks like the new nodeJS version (which we get from emsdk) is not used. Why ?

**Comment by maraf** [comment]
The new emscripten has a newer version of node, which is in different folder (`14.15.5_64bit` -> `14.18.2_64bit`) and we have the path hardcoded in the `sendtohelix-wasm.targets`

**Comment by radekdoulik** [comment]
Could we avoid hardcoding the version number?

**Comment by pavelsavara** [comment]
Also please add something like this to `test-main.js`
```
if (node && process.versions.node.split(".")[0]<14) throw new Error("NodeJS at "+process.execPath+"has too low version" + process.versions.node);
```
So that we don't have think about why, next time.

**Comment by maraf** [comment]
> Could we avoid hardcoding the version number?

I'll try to read it from filesystem in https://github.com/dotnet/runtime/pull/65514.

> So that we don't have think about why, next time.

In PR https://github.com/dotnet/runtime/pull/65549.

**Comment by radical** [comment]
Just a heads up, that we are now running tests on nodejs only on PRs. Once this is fixed, we could enable that for rolling builds.

**Comment by maraf** [comment]
Both PRs I mentioned are merged. I think we can close this one.
