### ISSUE TITLE
LoadGdipImageFromStream failed

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#65510]
In the regular .NET WinForms app (.NET 7.0.100-preview.1.22114.7)

Then application will produce following exception
```
Exception Info: System.InvalidProgramException: Non-blittable parameter types are invalid for UnmanagedCallersOnly methods.
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromStream(IntPtr stream, IntPtr* image)
   at System.Drawing.Image.LoadGdipImageFromStream(GPStream stream, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromStream(Stream stream)
   at System.Drawing.ImageConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)

```

**Comment by ViktorHofer** [comment]
@kant2002 can you please provide more details and a repro example?

**Comment by danmoseley** [comment]
@AaronRobinsonMSFT can you help reason about this from an interop POV?

the call is to this
https://github.com/dotnet/runtime/blob/405337939cf8d793661f6c6c0007c3f519b26f0d/src/libraries/System.Drawing.Common/src/System/Drawing/GdiplusNative.Windows.cs#L215-L216

The UnmanagedCallersOnly methods are apparently being called from within the code geneated by the 'GeneratedDllImport' attribute.

They are likely these COMWrappers
https://github.com/dotnet/runtime/blob/405337939cf8d793661f6c6c0007c3f519b26f0d/src/libraries/System.Drawing.Common/src/System/Drawing/DrawingCom.COMWrappers.cs#L90

I think we need your expertise to understand this. Perhaps the bug is clear from inspection.

**Comment by AaronRobinsonMSFT** [comment]
@kant2002 Is this still occurring? The error message is odd given the signature in question. It is also from Preview 1 so I'd advocate for moving to the latest preview and seeing if this reproduces.

**Comment by kant2002** [comment]
I cannot find this issue in my recent logs, and I vaguely recall that this is probably was fixed in Preview 2 or Preview 3. Given that I cannot repro, I think that's closed.
