### ISSUE TITLE
Static class initialization throws TypeInitializationException

### ISSUE THREAD

**Issue by isolin** [dotnet/runtime#65575]
### Description

Not sure if this is a bug or just my mistake. In a very simple console app I have a static class with a Numerics.Vector3 member throwing `TypeInitializationException` when first accessed.

### Reproduction Steps

```cs
//World.cs
using System.Numerics;
namespace Data;

public static class World {
    public static readonly Vector3 Size = new(1,2,3);
    //... some other members
    static World() { /* initialize a lot of other members */ }
}
```

```cs
//Program.cs
using Data;

var size = World.Size; // <-- EXCEPTION

//... other stuff 
```

### Expected behavior

No exception, proper static field initialization.

### Actual behavior

An unhandled exception of type `System.TypeInitializationException` occurrs.
```
Innermost exception 	 System.ArgumentException : Object must be of type Single.
   at System.Single.CompareTo(Object value)
   at System.Collections.Comparer.Compare(Object a, Object b)
   at System.Array.BinarySearch(Array array, Int32 index, Int32 length, Object value, IComparer comparer)
```

### Configuration

Using .NET 6.0.102 at Ubuntu 20.04.3, x64. My .csproj

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
```

**Comment by isolin** [comment]
I just found that the reason was a different one! The exception was inside of the static class constructor.
`Array.BinarySearch(A, 0, a.Length, d)` where `A` is a `float[]` and `d` is a `double`. So the real exception is `System.InvalidOperationException` and indeed the double was expected to be a single. 

It would be great if

1. OmniSharp would be able to mark this and
2. there would be a file and line reference given in the exception report. They are missing in the `TypeInitializationException`.
