### ISSUE TITLE
Test failure WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65648]
Run: [runtime-libraries-coreclr outerloop 20220220.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1623376&view=ms.vss-test-web.build-test-results-tab&runId=45106820&resultId=102261&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT


net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h2.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.ClientPre.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open
- WindowsIdentityImpersonatedTests.RunImpersonated_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_NameResolution
- WindowsIdentityImpersonatedTests.RunImpersonatedAsync_TaskAndTaskOfT
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (Unable to find an entry point named 'LogonUser' in DLL 'advapi32.dll'.) (The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture)
---- System.EntryPointNotFoundException : Unable to find an entry point named 'LogonUser' in DLL 'advapi32.dll'.
---- The following constructor parameters did not have matching fixture data: WindowsIdentityFixture windowsIdentityFixture


Stack trace

----- Inner Stack Trace #1 (System.EntryPointNotFoundException) -----
   at System.WindowsTestAccount.<LogonUser>g____PInvoke__|10_0(UInt16* userName, UInt16* domain, UInt16* password, Int32 logonType, Int32 logonProvider, IntPtr* safeAccessTokenHandle)
   at System.WindowsTestAccount.LogonUser(String userName, String domain, String password, Int32 logonType, Int32 logonProvider, SafeAccessTokenHandle& safeAccessTokenHandle) in /_/src/libraries/Common/tests/TestUtilities/Microsoft.Interop.DllImportGenerator/Microsoft.Interop.DllImportGenerator/GeneratedDllImports.g.cs:line 275
   at System.WindowsTestAccount.CreateUser() in /_/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs:line 91
   at System.WindowsTestAccount..ctor(String userName) in /_/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs:line 44
   at System.WindowsIdentityFixture..ctor() in /_/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs:line 23
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by jkoritzinsky** [comment]
This might be from the work to remove support for ExactSpelling from source-generated interop.
