### ISSUE TITLE
Test failure System.IO.Compression.ZLibStreamUnitTests.Dispose_ClosesStream(disposeMode: 1)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65650]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20220219.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1622316&view=ms.vss-test-web.build-test-results-tab&runId=45090066&resultId=138925&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress2_jitstressregs0x10-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.IO.Compression.ZLibStreamUnitTests.Dispose_ClosesStream(disposeMode: 1)

```
**Error message:**
```
System.ArgumentException : Stream does not support reading. (Parameter 'stream')


Stack trace
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 58
   at System.IO.Compression.ZLibStreamUnitTests.CreateStream(Stream stream, CompressionMode mode) in /_/src/libraries/System.IO.Compression/tests/CompressionStreamUnitTests.ZLib.cs:line 13
   at System.IO.Compression.CompressionStreamTestBase.CreateConnectedStreamsAsync() in /_/src/libraries/Common/tests/System/IO/Compression/CompressionStreamTestBase.cs:line 46
   at System.IO.Tests.ConnectedStreamConformanceTests.Dispose_ClosesStream(Int32 disposeMode) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2645
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment]
It's most likely related to https://github.com/dotnet/runtime/issues/65476 or https://github.com/dotnet/runtime/issues/65538, I am moving it to codegen area

**Comment by JulieLeeMSFT** [comment]
> It's most likely related to #65476 or #65538, I am moving it to codegen area

@BruceForstall is looking into those two. Assigning this to Bruce as an related issue.

**Comment by BruceForstall** [comment]
I'm going to assume this was fixed by https://github.com/dotnet/runtime/pull/65916
