### ISSUE TITLE
[wasm] `System.Runtime.Loader.Tests` fail when run in randomized order

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65672]
Found on https://github.com/dotnet/runtime/pull/65628 .

[System.Runtime.Loader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65628-merge-d2d09977c2a3474e86/normal-System.Runtime.Loader.Tests/1/console.a566875d.log?sv=2019-07-07&) fail randomly, but deterministically with `XUNIT_RANDOM_ORDER_SEED=2106784294`.

```
[06:25:43] fail: [FAIL] System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(alc: "Empty", assemblyName: "System.Runtime.Loader.Tests", culture: "en")
[06:25:43] info: Assert.Same() Failure
[06:25:43] info: Expected: "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
[06:25:43] info: Actual:   "Empty" System.Runtime.Loader.AssemblyLoadContext #4
[06:25:43] info:    at System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(String alc, String assemblyName, String culture)
[06:25:43] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```

Maybe these tests have some unintended dependence on order?
To test it with that PR, make sure to <XUnitUseRandomizedTestOrderer>false</XUnitUseRandomizedTestOrderer> from the csproj.

**Comment by ilonatommy** [comment]
Still failing.

**Comment by lewing** [comment]
@vargaz can you make sure we understand the issue here?

**Comment by vargaz** [comment]
Can't reproduce this. I ran with:
```
XUNIT_RANDOM_ORDER_SEED=2106784294 EMSDK_PATH=$REPO/src/mono/wasm/emsdk/ ./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release src/libraries/System.Runtime.Loader/tests/
```

**Comment by radical** [comment]
Did you disable this?
https://github.com/dotnet/runtime/blob/ed2a5a1492edda956323086e6cb1a456d9418f44/src/libraries/System.Runtime.Loader/tests/System.Runtime.Loader.Tests.csproj#L14

**Comment by vargaz** [comment]
I can reproduce now.

**Comment by vargaz** [comment]
Fails without randomized order as well. Testcase:
```
using System;
using System.Reflection;
using System.Resources;
using System.Globalization;
using Xunit;

namespace System.Runtime.Loader.Tests
{
    public class SatelliteAssembliesTestsFixture
    {
            [Fact]
            public void FOO () {
                string assemblyName = "System.Runtime.Loader.Tests";

                AssemblyName satelliteAssemblyName = new AssemblyName(assemblyName + ".resources");
                satelliteAssemblyName.CultureInfo = new CultureInfo("en");

                var alc = new AssemblyLoadContext("Empty");

                Assembly satelliteAssembly = alc.LoadFromAssemblyName(satelliteAssemblyName);

                Assembly parentAssembly = alc.LoadFromAssemblyName(new AssemblyName(assemblyName));

                Console.WriteLine (parentAssembly == typeof (SatelliteAssembliesTestsFixture).Assembly);
                Assert.Equal (parentAssembly, typeof (SatelliteAssembliesTestsFixture).Assembly);
        }
    }
}
```

**Comment by vargaz** [comment]
Commenting out the:
```
                Assembly satelliteAssembly = alc.LoadFromAssemblyName(satelliteAssemblyName);
```
makes the test pass.
