### ISSUE TITLE
Assertion failed in System.Net.NetworkInformation.Functional.Tests

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#65841]
```
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.NetworkInformation.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.NetworkInformation.Functional.Tests (found 77 of 97 test cases)
  Starting:    System.Net.NetworkInformation.Functional.Tests (parallel test collections = on, max threads = 2)
Process terminated. Assertion failed.
Unexpected error: System.ComponentModel.Win32Exception (0x80004005): Success
   at System.Net.NetworkInformation.NetworkChange.ReadEventsAsync(Socket socket) in /_/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs:line 200
   at System.Net.NetworkInformation.NetworkChange.ReadEventsAsync(Socket socket) in /_/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs:line 200
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1328
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 996
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 206
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 981
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 383
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 110
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 500
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 973
   at System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation op) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1382
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 341
   at System.Net.Sockets.SocketAsyncContext.AsyncOperation.Process() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 292
   at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 2187
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs:line 242
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
Today, there were few builds affected already, all PRs:
- e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1628534&view=logs&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6&l=878
- https://dev.azure.com/dnceng/public/_build/results?buildId=1628598&view=logs&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6&l=878
- According to Kusto, others are in following PRs
- #65798
- #65738 
- #65753

Console logs:
- https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65134-merge-09e69924a6f84e9c9a/System.Net.NetworkInformation.Functional.Tests/1/console.a456ebb9.log?sv=2019-07-07&se=2022-03-15T19%3A13%3A28Z&sr=c&sp=rl&sig=3cAg09Qq3XOwxWMApVZkGPLzDQh2HHW273aq%2FqePADo%3D
- https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65753-merge-2961b6e514da474490/System.Net.NetworkInformation.Functional.Tests/1/console.27bad446.log?sv=2019-07-07&se=2022-03-15T02%3A12%3A44Z&sr=c&sp=rl&sig=kMtM%2BTQ6z3V9JWYGHnMLUsPQwAn3pKpCtpmpkfNNilw%3D
- https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65738-merge-04e6f449bf1e433596/System.Net.NetworkInformation.Functional.Tests/1/console.641330bd.log?sv=2019-07-07&se=2022-03-15T02%3A21%3A47Z&sr=c&sp=rl&sig=w8oax473wrjEWBd0LG1ABVxAHrxZgK%2BM2e%2BTh%2FSNSfw%3D
- https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65798-merge-f62105508a424604a2/System.Net.NetworkInformation.Functional.Tests/1/console.001757c0.log?sv=2019-07-07&se=2022-03-15T20%3A41%3A51Z&sr=c&sp=rl&sig=x%2F%2BO2y19MXezgE2bvJl7jeNAw%2FoLpGD47p13PEraMtg%3D

Possibly related to https://github.com/dotnet/runtime/pull/64614?

**Comment by ManickaP** [comment]
That's been changed recently in this PR https://github.com/dotnet/runtime/pull/64614
cc: @tmds
