### ISSUE TITLE
Test failure JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65942]
Run: [runtime-coreclr jitstress-isas-arm 20220226.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1634260&view=ms.vss-test-web.build-test-results-tab&runId=45274372&paneView=debug&resultId=106130)

Failed test:
```
CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR windows arm64 Checked jitstress_isas_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ OSX.1200.ARM64.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.ARM64.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nosimd @ OSX.1200.ARM64.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd
```
**Error message:**
```
Assert failure(PID 6424 [0x00001918], Thread: 12796 [0x31fc]): Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)' in 'TestHFAandHVA:TestReturnViaThrowing()' during 'Generate code' (IL size 37)

File: D:\a\_work\1\s\src\coreclr\jit\emitarm64.cpp Line: 6996
Image: D:\h\w\B0CA094F\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\B0CA094F\w\A50C090C\uploads\Reports\JIT.Directed\StructABI\structreturn\structreturn.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B0CA094F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  structreturn.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B0CA094F\p
D:\h\w\B0CA094F\w\A50C090C\e\JIT\Directed\StructABI\structreturn\structreturn.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._StructABI_structreturn_structreturn_._StructABI_structreturn_structreturn_cmd()
```
Failed test:
```
CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR windows arm64 Checked jitstress_isas_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic @ Windows.10.Arm64v8.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ OSX.1200.ARM64.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.ARM64.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nosimd @ OSX.1200.ARM64.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd
```
**Error message:**
```
Assert failure(PID 1264 [0x000004f0], Thread: 584 [0x0248]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'projs.GitHub_35821:Main(System.String[]):int' during 'Linear scan register alloc' (IL size 48)

File: D:\a\_work\1\s\src\coreclr\jit\lsrabuild.cpp Line: 596
Image: D:\h\w\B0CA094F\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\B0CA094F\w\A494090D\uploads\Reports\JIT.Regression\JitBlue\GitHub_35821\GitHub_35821\GitHub_35821.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B0CA094F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GitHub_35821.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B0CA094F\p
D:\h\w\B0CA094F\w\A494090D\e\JIT\Regression\JitBlue\GitHub_35821\GitHub_35821\GitHub_35821.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_GitHub_35821_GitHub_35821_GitHub_35821_._JitBlue_GitHub_35821_GitHub_35821_GitHub_35821_cmd()
```

**Comment by BruceForstall** [comment]
This continues to fail.

https://dev.azure.com/dnceng/public/_build/results?buildId=1634260&view=ms.vss-test-web.build-test-results-tab

**Comment by BruceForstall** [comment]
@echesakovMSFT @kunalspathak Can one of you take this?

cc @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
I will take a look.

**Comment by kunalspathak** [comment]
Introduced in #65468
