### ISSUE TITLE
[WASM] Wasm.Build.Tests run with `EMSDK` - `clang` failing to load `libLLVM-13git.so`

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65956]
Configuration: `net7.0-Browser-Release-wasm-Mono_Release_Linux-BuildWasmApps-Ubuntu.1804.Amd64.Open`
CI build: [runtime pipeline of the rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1635569&view=ms.vss-test-web.build-test-results-tab&runId=45291016&paneView=debug&resultId=100051)

An example of failed tests:
```
      <test name="Wasm.Build.NativeRebuild.Tests.NoopNativeRebuildTest.NoOpRebuildForNativeBuilds(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = False, ProjectFileContents = placeholder, ExtraBuildArgs =  }, nativeRelink: True, invariant: False, host: V8, id: \&quot;h420la1w.j0k\&quot;)" type="Wasm.Build.NativeRebuild.Tests.NoopNativeRebuildTest" method="NoOpRebuildForNativeBuilds" time="54.2599321" result="Fail">
        <output><![CDATA[-------- Building ---------
Binlog path: /datadisks/disk1/work/A0100914/w/B4AD0967/uploads/xharness-output/logs/h420la1w.j0k/rebuild_noop_Release.binlog
Running /datadisks/disk1/work/A0100914/p/sdk-no-workload/dotnet publish -p:WasmBuildOnlyAfterPublish=true  /p:WasmBuildSupportDir=/datadisks/disk1/work/A0100914/p/build /p:EMSDK_PATH=/datadisks/disk1/work/A0100914/p/build/emsdk  /p:Configuration=Release /bl:"/datadisks/disk1/work/A0100914/w/B4AD0967/uploads/xharness-output/logs/h420la1w.j0k/rebuild_noop_Release.binlog" /nologo /fl /flp:"v:diag,LogFile=/datadisks/disk1/work/A0100914/w/B4AD0967/uploads/xharness-output/logs/h420la1w.j0k/rebuild_noop_Release.binlog.log" /v:minimal  
WorkingDirectory: /datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k
Setting environment variables for execution:
	EMSDK_PATH = /datadisks/disk1/work/A0100914/p/build/emsdk
	DOTNET_INSTALL_DIR = /datadisks/disk1/work/A0100914/p/sdk-no-workload
	DOTNET_MULTILEVEL_LOOKUP = 0
	DOTNET_SKIP_FIRST_TIME_EXPERIENCE = 1
	MSBuildSDKsPath = 
	PATH = /datadisks/disk1/work/A0100914/p/sdk-no-workload:/datadisks/disk1/work/A0100914/p/sdk-no-workload:/datadisks/disk1/work/A0100914/p/xharness-cli:/datadisks/disk1/work/A0100914/p/dotnet-cli:/datadisks/disk1/work/A0100914/p/build/emsdk/node/14.15.5_64bit/bin:/datadisks/disk1/work/A0100914/p/chrome-linux:/datadisks/disk1/work/A0100914/p/chromedriver_linux64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
	WasmNativeStrip = false
[h420la1w.j0k] 
[h420la1w.j0k] Welcome to .NET 7.0!
[h420la1w.j0k] ---------------------
[h420la1w.j0k] SDK Version: 7.0.100-alpha.1.21528.1
[h420la1w.j0k] 
[h420la1w.j0k] ----------------
[h420la1w.j0k] Installed an ASP.NET Core HTTPS development certificate.
[h420la1w.j0k] To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
[h420la1w.j0k] Learn about HTTPS: https://aka.ms/dotnet-https
[h420la1w.j0k] ----------------
[h420la1w.j0k] Write your first app: https://aka.ms/dotnet-hello-world
[h420la1w.j0k] Find out what's new: https://aka.ms/dotnet-whats-new
[h420la1w.j0k] Explore documentation: https://aka.ms/dotnet-docs
[h420la1w.j0k] Report issues and find source on GitHub: https://github.com/dotnet/core
[h420la1w.j0k] Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
[h420la1w.j0k] --------------------------------------------------------------------------------------
[h420la1w.j0k] /datadisks/disk1/work/A0100914/p/sdk-no-workload/sdk/7.0.100-alpha.1.21528.1/MSBuild.dll /fl /nologo -maxcpucount -property:WasmBuildSupportDir=/datadisks/disk1/work/A0100914/p/build -property:EMSDK_PATH=/datadisks/disk1/work/A0100914/p/build/emsdk -property:Configuration=Release -p:WasmBuildOnlyAfterPublish=true -restore -target:Publish -verbosity:m /v:minimal /bl:/datadisks/disk1/work/A0100914/w/B4AD0967/uploads/xharness-output/logs/h420la1w.j0k/rebuild_noop_Release.binlog /flp:v:diag,LogFile=/datadisks/disk1/work/A0100914/w/B4AD0967/uploads/xharness-output/logs/h420la1w.j0k/rebuild_noop_Release.binlog.log ./rebuild_noop_Release.csproj
[h420la1w.j0k]   Determining projects to restore...
[h420la1w.j0k]   Restored /datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/rebuild_noop_Release.csproj (in 46.12 sec).
[h420la1w.j0k]   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
[h420la1w.j0k]   rebuild_noop_Release -> /datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/bin/Release/net6.0/browser-wasm/rebuild_noop_Release.dll
[h420la1w.j0k]   ** MicrosoftNetCoreAppRuntimePackDir : /datadisks/disk1/work/A0100914/p/build/microsoft.netcore.app.runtime.browser-wasm/
[h420la1w.j0k]   Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
[h420la1w.j0k]   rebuild_noop_Release -> /datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/bin/Release/net6.0/browser-wasm/publish/
[h420la1w.j0k]   rebuild_noop_Release -> /datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/bin/Release/net6.0/browser-wasm/rebuild_noop_Release.dll
[h420la1w.j0k]   ** MicrosoftNetCoreAppRuntimePackDir : /datadisks/disk1/work/A0100914/p/build/microsoft.netcore.app.runtime.browser-wasm/
[h420la1w.j0k]   Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
[h420la1w.j0k]   rebuild_noop_Release -> /datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/bin/Release/net6.0/browser-wasm/publish/
[h420la1w.j0k] embuilder : error : '/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/bin/clang --version' failed (returned 127) [/datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/rebuild_noop_Release.csproj]
[h420la1w.j0k] /datadisks/disk1/work/A0100914/p/build/wasm/WasmApp.Native.targets(317,5): error MSB3073: The command "embuilder.py build MINIMAL" exited with code 1. [/datadisks/disk1/work/A0100914/w/B4AD0967/e/h420la1w.j0k/rebuild_noop_Release.csproj]
]]></output>
        <failure exception-type="Xunit.Sdk.TrueException">
          <message><![CDATA[Build process exited with non-zero exit code: 1\nExpected: True\nActual:   False]]></message>
          <stack-trace><![CDATA[   at Wasm.Build.Tests.BuildTestBase.AssertBuild(String args, String label, Boolean expectSuccess, IDictionary`2 envVars, Nullable`1 timeoutMs) in /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs:line 588
   at Wasm.Build.Tests.BuildTestBase.BuildProject(BuildArgs buildArgs, String id, BuildProjectOptions options) in /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs:line 337
   at Wasm.Build.NativeRebuild.Tests.NativeRebuildTestsBase.FirstNativeBuild(String programText, Boolean nativeRelink, Boolean invariant, BuildArgs buildArgs, String id, String extraProperties) in /_/src/tests/BuildWasmApps/Wasm.Build.Tests/NativeRebuildTests/NativeRebuildTestsBase.cs:line 50
   at Wasm.Build.NativeRebuild.Tests.NoopNativeRebuildTest.NoOpRebuildForNativeBuilds(BuildArgs buildArgs, Boolean nativeRelink, Boolean invariant, RunHost host, String id) in /_/src/tests/BuildWasmApps/Wasm.Build.Tests/NativeRebuildTests/NoopNativeRebuildTest.cs:line 26]]></stack-trace>
        </failure>
```

**Comment by radical** [comment]
These tests are failing when running WBT with emsdk from the repo, instead of workloads.

Looking at the binlog:
```
                   Task "Exec" (TaskId:231)
                     Task Parameter:
                         EnvironmentVariables=
                             DOTNET_EMSCRIPTEN_LLVM_ROOT=/datadisks/disk1/work/A0100914/p/build/emsdk/bin
                             DOTNET_EMSCRIPTEN_BINARYEN_ROOT=/datadisks/disk1/work/A0100914/p/build/emsdk/
                             DOTNET_EMSCRIPTEN_NODE_JS=/datadisks/disk1/work/A0100914/p/build/emsdk/node/14.15.5_64bit/bin/node
                             PATH=/datadisks/disk1/work/A0100914/p/build/emsdk:/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/bin:/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/emscripten:/datadisks/disk1/work/A0100914/p/build/emsdk/node/14.15.5_64bit/bin:/datadisks/disk1/work/A01009
                             PYTHONUTF8=1 (TaskId:231)
                     Task Parameter:StandardErrorImportance=Low (TaskId:231)
                     Task Parameter:StandardOutputImportance=Low (TaskId:231)
                     Task Parameter:Command=embuilder.py build MINIMAL (TaskId:231)
                     Environment Variables passed to tool: (TaskId:231)
                       DOTNET_EMSCRIPTEN_LLVM_ROOT=/datadisks/disk1/work/A0100914/p/build/emsdk/bin (TaskId:231)
                       DOTNET_EMSCRIPTEN_BINARYEN_ROOT=/datadisks/disk1/work/A0100914/p/build/emsdk/ (TaskId:231)
                       DOTNET_EMSCRIPTEN_NODE_JS=/datadisks/disk1/work/A0100914/p/build/emsdk/node/14.15.5_64bit/bin/node (TaskId:231)
                       PATH=/datadisks/disk1/work/A0100914/p/build/emsdk:/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/bin:/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/emscripten:/datadisks/disk1/work/A0100914/p/build/emsdk/node/14.15.5_64bit/bin:/datadisks/disk1/work/A0100914/p/s
                       PYTHONUTF8=1 (TaskId:231)
                     embuilder.py build MINIMAL (TaskId:231)
                     /datadisks/disk1/work/A0100914/p/build/emsdk/upstream/bin/clang: error while loading shared libraries: libLLVM-13git.so: cannot open shared object file: No such file or directory (TaskId:231)
08:55:48.036   1:8>embuilder : error : '/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/bin/clang --version' failed (returned 127) [/datadisks/disk1/work/A0100914/w/AD9D09CE/e/f323ik3b.3wg/build_publish_Release.csproj]
08:55:48.036   1:8>/datadisks/disk1/work/A0100914/p/build/wasm/WasmApp.Native.targets(317,5): error MSB3073: The command "embuilder.py build MINIMAL" exited with code 1. [/datadisks/disk1/work/A0100914/w/AD9D09CE/e/f323ik3b.3wg/build_publish_Release.csproj]
```

Specifically:
`/datadisks/disk1/work/A0100914/p/build/emsdk/upstream/bin/clang: error while loading shared libraries: libLLVM-13git.so: cannot open shared object file: No such file or directory (TaskId:231)`

cc @radekdoulik

**Comment by radical** [comment]
Yes.
