### ISSUE TITLE
System.Threading.ThreadPools.Tests.ThreadPoolTests.CooperativeBlockingCanCreateThreadsFaster test failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65954]
Configuration: `net7.0-OSX-Release-x64-CoreCLR_checked-OSX.1200.Amd64.Open`
Build: [runtime pipeline of the rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1635569&view=ms.vss-test-web.build-test-results-tab&runId=45291126&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=178067)

```
Unhandled exception. Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.<>c.<CooperativeBlockingCanCreateThreadsFaster>b__38_0() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 953
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Threading.ThreadPools.Tests.ThreadPoolTests.CooperativeBlockingCanCreateThreadsFaster [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.TrueException: Assert.True() Failure
        Expected: True
        Actual:   False
        /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(953,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.<>c.<CooperativeBlockingCanCreateThreadsFaster>b__38_0()
        
        Child process:
          System.Threading.ThreadPool.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.ThreadPools.Tests.ThreadPoolTests+<>c Void <CooperativeBlockingCanCreateThreadsFaster>b__38_0()
        
        
  Finished:    System.Threading.ThreadPool.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.ThreadPool.Tests  Total: 65, Errors: 0, Failed: 1, Skipped: 0, Time: 40.712s
```

**Comment by hoyosjs** [comment]
Closing in favor of #66755 which has a linked PR.
