### ISSUE TITLE
Test failure System.IO.Compression.DeflateStreamUnitTests.ReadWrite_Success(mode: SyncSpan, writeSize: 1, startWithFlush: False)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65985]
Run:[runtime-coreclr libraries-jitstress 20220227.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1635524&view=ms.vss-test-web.build-test-results-tab&runId=45290762&paneView=debug&resultId=141727)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress2_tiered-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.IO.Compression.DeflateStreamUnitTests.ReadWrite_Success(mode: SyncSpan, writeSize: 1, startWithFlush: False)

```
**Error message:**
```
System.ArgumentException : Stream does not support reading. (Parameter 'stream')


Stack trace
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 71
   at System.IO.Compression.DeflateStreamUnitTests.CreateStream(Stream stream, CompressionMode mode) in /_/src/libraries/System.IO.Compression/tests/CompressionStreamUnitTests.Deflate.cs:line 14
   at System.IO.Compression.CompressionStreamTestBase.CreateConnectedStreamsAsync() in /_/src/libraries/Common/tests/System/IO/Compression/CompressionStreamTestBase.cs:line 46
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1727
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment]
Fixed by https://github.com/dotnet/runtime/pull/65916
