### ISSUE TITLE
Test failure System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65984]
Run: [runtime-libraries-coreclr outerloop 20220228.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1635742&view=ms.vss-test-web.build-test-results-tab&runId=45295418&resultId=100362&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash

```
**Error message:**
```
Exit code was -2146233082 but it should have been 42
Expected: True
Actual:   False


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 239
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.Stress_WriteConcurrently_DoesntCrash() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/DiagnosticSourceEventSourceBridgeTests.cs:line 1183
```

**Comment by danmoseley** [comment]
-2146233082 ==  COR_E_EXECUTIONENGINE

**Comment by davmason** [comment]
Only failed once in the last month and it was on #71516, which was causing lots of random crashes across the libraries tests. Closing, please reopen if the failure happens again.
