### ISSUE TITLE
dotnet-dump in AKS sidecar using alpine base images results in "ReadProcessMemory" FAILED

### ISSUE THREAD

**Issue by BWalti** [dotnet/runtime#66001]
### Description

I am trying to use a sidecar container, based on alpine, containing some "debug" tools: 
``` dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine as tools
RUN dotnet tool install --tool-path /tools dotnet-trace
RUN dotnet tool install --tool-path /tools dotnet-counters
RUN dotnet tool install --tool-path /tools dotnet-dump
# https://www.stefangeiger.ch/2020/04/21/dotnet-diagnostics-tools-gcdump-vs-dump.html
RUN dotnet tool install --tool-path /tools dotnet-gcdump

# /tmp is required for "sidecar diagnostics":
# https://docs.microsoft.com/en-us/dotnet/core/diagnostics/diagnostics-in-containers#using-net-core-global-cli-tools-in-a-sidecar-container
# but we do not need to define it as a volume:
# VOLUME [ "/tmp" ]

# another requirement is shared process namespace:
# https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

# according to following link we may use a runtime image:
# https://thecloudblog.net/post/tracing-and-profiling-a-net-core-application-on-azure-kubernetes-service-with-a-sidecar-container/
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine AS runtime
COPY --from=tools /tools /tools

ENV PATH="/tools:${PATH}"
WORKDIR /tools
```

to get a "dump" (to find out where we are "loosing" memory) of an ASP.NET core web application.

The deployment looks a bit like (cut out stuff for privacy reasons):
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - -c
        - while true; do echo echo $(date -u) 'Hi I am from Sidecar container' >>
          /var/log/index.html; sleep 300;done
        command:
        - /bin/sh
        image: .../dotnet-diagnostics:latest
        name: dotnet-diagnostics
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 10m
            memory: 120Mi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        volumeMounts:
        - mountPath: /tmp
          name: var-diagnostics
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: service-image:tag
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/live
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 10
        name: service
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/ready
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 200Mi
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /healthz/live
            port: 5000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /tmp
          name: var-diagnostics
      shareProcessNamespace: true
      volumes:
      - emptyDir:
          medium: Memory
        name: var-diagnostics
```

now, entering the sidecar using "VS Code Kubernetes extension" and invoking:

``` console
# dotnet-dump collect -p 937 --type Heap -o /tmp/heap202203011325 --diag

Writing dump with heap to /tmp/heap202203011325
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
...
```

and in the "app" on stdout:

``` console
EnumerateMemoryRegionsWithDAC: Memory enumeration FINISHED
Writing minidump with heap to file /tmp/heap202203011325
Writing memory region headers to core file
Writing process information to core file
Writing 20 auxv entries to core file
Writing 739 NT_FILE entries to core file
Writing 25 thread entries to core file
Writing 1753 memory regions to core file
ReadProcessMemory(000055e5e3f7c000, 00001000) FAILED
Writing dump FAILED
```

I may have stumbled upon a comment in another issue, which may be related to it:
> I've seen this on Alpine with the "loader" module.
Source: https://github.com/dotnet/runtime/issues/42980#issuecomment-702482109

As we are basing on alpine (sidecar, as well as "service") I imagine this could have something to do with this?
I have to admin, that I am out of ideas how to further analyze this on my end..

### Reproduction Steps

using the alpine sidecar container described in description, try to:

``` console
dotnet-dump collect -p {pid} --type Heap -o /tmp/heap --diag
```

### Expected behavior

I should be able to get the corresponding dump

### Actual behavior

Error Message in dotnet-dump:

``` console

Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt16()
   at Microsoft.Diagnostics.NETCore.Client.IpcHeader.Parse(BinaryReader reader) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcHeader.cs:line 57
   at Microsoft.Diagnostics.NETCore.Client.IpcMessage.Parse(Stream stream) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcMessage.cs:line 117
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.Read(Stream stream) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs:line 108
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessageGetContinuation(IpcEndpoint endpoint, IpcMessage message) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs:line 45
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessage(IpcEndpoint endpoint, IpcMessage message) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs:line 26
   at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.WriteDump(DumpType dumpType, String dumpPath, WriteDumpFlags flags) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs:line 139
   at Microsoft.Diagnostics.Tools.Dump.Dumper.Collect(IConsole console, Int32 processId, String output, Boolean diag, Boolean crashreport, DumpTypeOption type, String name) in /_/src/Tools/dotnet-dump/Dumper.cs:line 131
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)      
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext() 
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext() 
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

and Error message in "service" stdout:
``` console
...
DumpDataTarget::ReadVirtual 0x7fb6f2810000 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2812180 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d10000 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d13860 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d108f0 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d12bb0 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d159e0 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d327a8 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d334e0 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d32c60 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb6f2d35660 1 FAILED
DumpDataTarget::ReadVirtual 0x7fb76484bb88 8 FAILED
DumpDataTarget::ReadVirtual 0x7fb76484bb88 8 FAILED
DumpDataTarget::ReadVirtual 0x7fb76484bb88 8 FAILED
DumpDataTarget::ReadVirtual 0x7fb76484bb88 8 FAILED
DumpDataTarget::ReadVirtual 0x7fb76484bb88 8 FAILED
EnumerateMemoryRegionsWithDAC: Memory enumeration FINISHED
Writing minidump with heap to file /tmp/heap202203011325
Writing memory region headers to core file
Writing process information to core file
Writing 20 auxv entries to core file
Writing 739 NT_FILE entries to core file
Writing 25 thread entries to core file
Writing 1753 memory regions to core file
ReadProcessMemory(000055e5e3f7c000, 00001000) FAILED
Writing dump FAILED
```

### Configuration

.NET 6.0.2
Alpine based container image (mcr.microsoft.com/dotnet/sdk:6.0-alpine / mcr.microsoft.com/dotnet/runtime:6.0-alpine)
running in Azure Kubernetes Service (x64 Linux VMs)

**Comment by mikem8361** [comment]
Thanks for the detailed report.  Is there anyway you can attach the complete createdump logging output? This error is happening after createdump has successfully gathered all the state it needs and is in the middle of reading memory and writing it to the core dump.  All the memory regions should have been validated in the "gather" stage.

**Comment by BWalti** [comment]
@mikem8361 would I have to do this from the container, running the application? as in there, I am not root and therefore (maybe) getting:
``` console
 $ /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.2/createdump -u -d 527 > output.log
open(/proc/527/mem) FAILED 13 (Permission denied)
```

Has this to-do with the /tmp/ directory belonging to root and not the application user?

running from sidecar results in: https://gist.github.com/BWalti/9abeba9484ddb884f8ffbc855f00976b
interestingly, this seems to have worked -> there is a file /tmp/coredump.13 now with the size of about 289.4M

As I was surprised by that and was pretty sure, that I also tried this before, I re-run
``` console
dotnet-dump collect -p 13 -o /tmp/dump-collect20220303 --diag --type Full
```

and yet again got the "error":
``` console
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
```

and in app container:
``` console
CombineMemoryRegions: STARTED
CombineMemoryRegions: FINISHED
Writing full dump to file /tmp/dump-collect20220303
Writing memory region headers to core file
Writing process information to core file
Writing 20 auxv entries to core file
Writing 747 NT_FILE entries to core file
Writing 24 thread entries to core file
Writing 946 memory regions to core file
ReadProcessMemory(00007f0e0744c000, 00004000) FAILED
Writing dump FAILED
```

I'm not sure if I can get the whole log of the app container, as it died and re-started immediately. Therefore kubectl logs gets me the new rather empty log..

Does this help?

Thanks in advanced for your help!

**Comment by BWalti** [comment]
uuuh.. I just had an Idea which actually seems to be causing the problems: /tmp/ belongs to root, I tried running
``` console
dotnet-dump collect --type Full --diag -p 13 --crashreport -o /app/coredump
```

which seems to have worked!

well.. /tmp/ is 'rwxrwxrwt' so I'm not sure, why the app user is not allowed to write there.. but I guess I can work with that for now.

Maybe you have some pointers about that?

**Comment by mikem8361** [comment]
I'm not sure why /tmp/ isn't working.  Maybe @hoyosjs has some ideas.

**Comment by hoyosjs** [comment]
Not sure if the volume mount here is causing issues. The sticky bit could be an issue too if there was something like /tmp/dump-collect20220303 already there perhaps.

**Comment by BWalti** [comment]
In the meantime I believe I found out, why /tmp/ wasn't working: we used an "in Memory" EmptyDir volume mount for that and probably run into OOM on node.. so, I am now trying to use the before mentioned "/app/" directory, which worked previously, but fails again. this dotnet-dump utility seems to be extremely "finicky" about versions maybe?
In my understanding app container, as well as sidecar both use version 6.0.3, but nevertheless the dump collection fails with last messages on "collected app" console:
``` console
...
PHDR: loadbias 00007f1dd9f7c000
PHDR: 0x7f1dd9f7c040 type 1 (1) vaddr 0000000000000000 memsz 0000000000001578 paddr 0000000000000000 filesz 0000000000001578 offset 0000000000000000 align 0000000000001000
PHDR: 0x7f1dd9f7c078 type 1 (1) vaddr 0000000000002000 memsz 0000000000071d59 paddr 0000000000002000 filesz 0000000000071d59 offset 0000000000002000 align 0000000000001000
PHDR: 0x7f1dd9f7c0b0 type 1 (1) vaddr 0000000000074000 memsz 0000000000071e48 paddr 0000000000074000 filesz 0000000000071e48 offset 0000000000074000 align 0000000000001000
PHDR: 0x7f1dd9f7c0e8 type 1 (1) vaddr 00000000000e79e0 memsz 00000000000006d0 paddr 00000000000e79e0 filesz 000000000000067c offset 00000000000e69e0 align 0000000000001000
PHDR: 0x7f1dd9f7c120 type 2 (2) vaddr 00000000000e7d50 memsz 00000000000001c0 paddr 00000000000e7d50 filesz 00000000000001c0 offset 00000000000e6d50 align 0000000000000008
PHDR: 0x7f1dd9f7c158 type 4 (4) vaddr 0000000000000238 memsz 0000000000000024 paddr 0000000000000238 filesz 0000000000000024 offset 0000000000000238 align 0000000000000004
PHDR: 0x7f1dd9f7c190 type 1685382480 (6474e550) vaddr 00000000000e2870 memsz 000000000000058c paddr 00000000000e2870 filesz 000000000000058c offset 00000000000e2870 align 0000000000000004
PHDR: 0x7f1dd9f7c1c8 type 1685382481 (6474e551) vaddr 0000000000000000 memsz 0000000000000000 paddr 0000000000000000 filesz 0000000000000000 offset 0000000000000000 align 0000000000000010
PHDR: 0x7f1dd9f7c200 type 1685382482 (6474e552) vaddr 00000000000e79e0 memsz 0000000000000620 paddr 00000000000e79e0 filesz 0000000000000620 offset 00000000000e69e0 align 0000000000000001
DSO: link_map entry 0x7f1de2426650 l_ld 0x7f1dddd42cb0 l_addr (Ehdr) 7f1dddd2a000 /lib/libz.so.1
ELF: type 3 mach 0x3e ver 1 flags 0x0 phnum 8 phoff 0000000000000040 phentsize 0x38 shnum 25 shoff 0000000000018108 shentsize 0x40 shstrndx 24
PHDR: loadbias 00007f1dddd2a000
PHDR: 0x7f1dddd2a040 type 1 (1) vaddr 0000000000000000 memsz 0000000000002030 paddr 0000000000000000 filesz 0000000000002030 offset 0000000000000000 align 0000000000001000
PHDR: 0x7f1dddd2a078 type 1 (1) vaddr 0000000000003000 memsz 000000000000dae9 paddr 0000000000003000 filesz 000000000000dae9 offset 0000000000003000 align 0000000000001000
PHDR: 0x7f1dddd2a0b0 type 1 (1) vaddr 0000000000011000 memsz 0000000000006228 paddr 0000000000011000 filesz 0000000000006228 offset 0000000000011000 align 0000000000001000
PHDR: 0x7f1dddd2a0e8 type 1 (1) vaddr 0000000000018b40 memsz 0000000000000530 paddr 0000000000018b40 filesz 00000000000004c8 offset 0000000000017b40 align 0000000000001000
PHDR: 0x7f1dddd2a120 type 2 (2) vaddr 0000000000018cb0 memsz 00000000000001b0 paddr 0000000000018cb0 filesz 00000000000001b0 offset 0000000000017cb0 align 0000000000000008
PHDR: 0x7f1dddd2a158 type 1685382480 (6474e550) vaddr 0000000000015310 memsz 00000000000004a4 paddr 0000000000015310 filesz 00000000000004a4 offset 0000000000015310 align 0000000000000004
PHDR: 0x7f1dddd2a190 type 1685382481 (6474e551) vaddr 0000000000000000 memsz 0000000000000000 paddr 0000000000000000 filesz 0000000000000000 offset 0000000000000000 align 0000000000000010
PHDR: 0x7f1dddd2a1c8 type 1685382482 (6474e552) vaddr 0000000000018b40 memsz 00000000000004c0 paddr 0000000000018b40 filesz 00000000000004c0 offset 0000000000017b40 align 0000000000000001
DumpDataTarget::ReadVirtual 0x7f1ead349000 64 FAILED
CLRDataCreateInstance(ICLRDataEnumMemoryRegions) FAILED 80131c4f
```

and following output on sidecar:

``` console
Writing full to /app/core_20220404
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
...
```

how can I pinpoint the root cause of this issue?

**Comment by mikem8361** [comment]
Could the pod be terminated because OOM before createdump is finished? It would explain the `ReadProcessMemory(00007f0e0744c000, 00004000) FAILED` kind of errors.

**Comment by BWalti** [comment]
@mikem8361 that could very well be, especially as we are using an "InMemory" shared volume. So either the pod's RAM Limit or the Nodes RAM limit could actually be an issue.. I'll suggest to use "local storage" as a workaround to verify this.

Thanks for the hint!

Btw is there any way to guess how much RAM this operation would require? based on the Memory Address maybe? (or is this randomized for better security etc..)

**Comment by mikem8361** [comment]
Can I close this issue?  .NET can't really do anything about the low memory or auto-termination.

**Comment by BWalti** [comment]
@mikem8361 yeah I guess so. thanks for your efforts and sorry for any disturbance :)
we'll try things out on our end and as soon as we find out more (and have a problem with dotnet and not something RAM related anywhere else) we'd reopen a new ticket. (which I am pretty sure won't be the case ;) )
