### ISSUE TITLE
`System.Runtime.InteropServices.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected` failing on windows

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#66058]
Hit on https://github.com/dotnet/runtime/pull/66044 .

[build](https://dev.azure.com/dnceng/public/_build/results?buildId=1639318&view=logs&jobId=73b7db51-6fbc-594d-25c9-15b2737b0bf6&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66044-merge-91d0148f6aac4a3994/System.Runtime.InteropServices.Tests/1/console.f3eb421e.log?sv=2019-07-07&se=2022-03-22T02%3A11%3A51Z&sr=c&sp=rl&sig=yqvJ6vR%2BTvbnELUsmClgjCyOn4%2FsKf0Z9iihhb1OWRU%3D):

```
System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(type: typeof(System.Runtime.InteropServices.Tests.Common.IComImportObject), expected: 6) [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
           at System.Runtime.InteropServices.Marshal.GetEndComSlot(Type t)
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/Marshal/GetEndComSlotTests.Windows.cs(31,0): at System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(Type type, Int32 expected)
    System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(type: typeof(System.Runtime.InteropServices.Tests.Common.ManagedInterfaceSupportIUnknown), expected: 2) [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
           at System.Runtime.InteropServices.Marshal.GetEndComSlot(Type t)
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/Marshal/GetEndComSlotTests.Windows.cs(31,0): at System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(Type type, Int32 expected)
    System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(type: typeof(System.Runtime.InteropServices.Tests.Common.ManagedInterfaceSupportIDispatch), expected: 6) [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
           at System.Runtime.InteropServices.Marshal.GetEndComSlot(Type t)
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/Marshal/GetEndComSlotTests.Windows.cs(31,0): at System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(Type type, Int32 expected)
```

**Comment by elinor-fung** [comment]
@EgorBo already fixed this in https://github.com/dotnet/runtime/pull/66035
