### ISSUE TITLE
Some `System.Net.Http.Functional.Tests` tests are timing out

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#66059]
Hit on https://github.com/dotnet/runtime/pull/66044 .
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1639318&view=logs&jobId=73b7db51-6fbc-594d-25c9-15b2737b0bf6&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66044-merge-6a44147922f0491ba0/System.Net.Http.Functional.Tests/3/console.078800c8.log?sv=2019-07-07&se=2022-03-22T02%3A00%3A26Z&sr=c&sp=rl&sig=MYNuV%2BIScazMjDxj6HFdP2rpvF6SjzX7edQrvd%2B6NiM%3D).

```
    System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandlerTest.PostAsync_ManyDifferentRequestHeaders_SentCorrectly [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs(405,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_ManyDifferentRequestHeaders_SentCorrectly()
        --- End of stack trace from previous location ---
```

```
    System.Net.Http.Functional.Tests.Http1RawResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: AsyncArray, useSsl: True) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/ResponseStreamZeroByteReadTests.cs(125,0): at System.Net.Http.Functional.Tests.Http1ResponseStreamZeroByteReadTestBase.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(ReadWriteMode readMode, Boolean useSsl)
        --- End of stack trace from previous location ---
```

```
    System.Net.Http.Functional.Tests.Http1SingleChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: AsyncArray, useSsl: False) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/ResponseStreamZeroByteReadTests.cs(125,0): at System.Net.Http.Functional.Tests.Http1ResponseStreamZeroByteReadTestBase.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(ReadWriteMode readMode, Boolean useSsl)
        --- End of stack trace from previous location ---
```

**Comment by wfurt** [comment]
looks like this was also x86 leg - may be related to https://github.com/dotnet/runtime/issues/65292
