### ISSUE TITLE
ChangingMarshallingAttributes_SameStrategy_DoesNotRegenerate test is failing in CI on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#66143]
e.g. https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66142-merge-3d88824802df44db97/DllImportGenerator.Unit.Tests/1/console.b75deffd.log?sv=2019-07-07&se=2022-03-23T15%3A20%3A52Z&sr=c&sp=rl&sig=lCP6q0KCphE853h22%2B7gzi0cxzEqNaOZXFK8qsTuEl0%3D
```
    DllImportGenerator.UnitTests.IncrementalGenerationTests.ChangingMarshallingAttributes_SameStrategy_DoesNotRegenerate [FAIL]
      Assert.Collection() Failure
      Collection: [IncrementalGeneratorRunStep { ElapsedTime = 00:00:00.0023738, Inputs = [...], Name = "GenerateSingleStub", Outputs = [...] }]
      Error during comparison of item at index 0
      Inner exception: Assert.Collection() Failure
              Collection: [((unsafepartialclassTest
              {[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator","42.42.42.42")][System.Runtime.CompilerServices.SkipLocalsInitAttribute]publicstaticpartialboolMethod(boolp,inboolpIn,refboolpRef,outboolpOut){int__p_gen_native;int__pIn_gen_native;int__pRef_gen_native;pOut=default;int__pOut_gen_native;bool__retVal;int__retVal_gen_native;//// Marshal//__p_gen_native=(int)(p?1:0);__pIn_gen_native=(int)(pIn?1:0);__pRef_gen_native=(int)(pRef?1:0);__retVal_gen_native=__PInvoke__(__p_gen_native,&__pIn_gen_native,&__pRef_gen_native,&__pOut_gen_native);//// Unmarshal//__retVal=__retVal_gen_native!=0;pOut=__pOut_gen_native!=0;pRef=__pRef_gen_native!=0;return__retVal;//// Local P/Invoke//[System.Runtime.InteropServices.DllImportAttribute("DoesNotExist",EntryPoint="Method",ExactSpelling=true)]externstaticunsafeint__PInvoke__(intp,int*pIn,int*pRef,int*pOut);}}, System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.Diagnostic]), Modified)]
              Error during comparison of item at index 0
              Inner exception: Assert.Equal() Failure
                      Expected: Unchanged
                      Actual:   Modified
      Stack Trace:
        /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/IncrementalGenerationTests.cs(209,0): at DllImportGenerator.UnitTests.IncrementalGenerationTests.<>c.<ChangingMarshallingAttributes_SameStrategy_DoesNotRegenerate>b__7_3(ValueTuple`2 output)
        /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/IncrementalGenerationTests.cs(208,0): at DllImportGenerator.UnitTests.IncrementalGenerationTests.<>c.<ChangingMarshallingAttributes_SameStrategy_DoesNotRegenerate>b__7_1(IncrementalGeneratorRunStep step)
        /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/IncrementalGenerationTests.cs(205,0): at DllImportGenerator.UnitTests.IncrementalGenerationTests.ChangingMarshallingAttributes_SameStrategy_DoesNotRegenerate()
        --- End of stack trace from previous location ---
```
It appears to be very consistently failing.

**Comment by jkoritzinsky** [comment]
I guess there was a conflict between some of the PRs I merged in. I’ll take a look.

**Comment by agocke** [comment]
FYI @thaystg
