### ISSUE TITLE
Mono is crashing on the newly added tests for generic Attributes

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#66168]
Looks like Mono is crashing on the newly added tests even though they are disabled:
```
#13 0x0000007f8d2cfbdc in mono_assertion_message_unreachable (file=0x64 <error: Cannot access memory at address 0x64>, line=6) at /__w/1/s/src/mono/mono/eglib/goutput.c:234
#14 0x0000007f8d115120 in custom_attr_class_name_from_method_token (image=0x5589355e20, method_token=167772165, nspace=0x7fc25c2d58, class_name=0x7fc25c2d50, assembly_token=<optimized out>) at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2441
```

_Originally posted by @jkotas in https://github.com/dotnet/runtime/issues/65237#issuecomment-1041935039_

**Comment by SamMonoRT** [comment]
@naricc - this was another case of a disabled test still run in CI

**Comment by lambdageek** [comment]
This is going to affect https://github.com/dotnet/runtime/issues/70133 if the proposal lands with `[MarshalAs<JSType.Number>]`-style attributes

**Comment by SamMonoRT** [comment]
Moving to 9.0.0, we'll consider a backport based on the actual fix.
