### ISSUE TITLE
System.Text.Json.Serialization.Tests failing with `FileLoadException` on net48 runs

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#66232]
After https://github.com/dotnet/runtime/pull/65863, these two are failing on net48 runs:
- `System.Text.Json.Serialization.Tests.CacheTests.JsonSerializerOptions_ReuseConverterCaches`
- `System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException`

```
Child exception:
  System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Span`1..ctor(T[] array, Int32 start, Int32 length)
   at System.Text.Json.PooledByteBufferWriter.Dispose()
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.CustomConverterTests.<>c.<GetConverter_Poco_WriteThrowsNotSupportedException>b__321_0()
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1637814&view=ms.vss-test-web.build-test-results-tab&runId=45326006&paneView=debug&resultId=118036

cc @eiriktsarpalis @layomia

**Comment by eiriktsarpalis** [comment]
I've disabled the failing tests in netfx, reopening to track the issue.

**Comment by mrBen** [comment]
Is there a known workaround for this bug?

**Comment by arturfilar** [comment]
Is there any update on this?
Using System.Text.Json 7.0.0 and it screams for 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1. Which I don't think is even referenced by Json package. Weird

**Comment by Erithax** [comment]
I am also encountering this issue using `System.Text.Json.JsonSerializer.Deserialize<T>(text, opts);` 8.0.3 in NET48 and fixed proposed elsewhere using 
```xml
<!-- app.config --> 
<dependentAssembly>
  <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
</dependentAssembly>
```
do not help.

My exact error, with fusion log enables, is
```
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()

=== Pre-bind state information ===
LOG: DisplayName = System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/redacted/
LOG: Initial PrivatePath = NULL
Calling assembly : System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\redacted\red.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80131040.
```
