### ISSUE TITLE
Test failure JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66279]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220306.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1647673&view=ms.vss-test-web.build-test-results-tab&runId=45501334&resultId=109135&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh
```
**Error message:**
```
cmdLine:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/6/2022 3:58:23 PM, end: 3/6/2022 4:58:23 PM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ArrBoundBinaryOp.dll ''

cmdLine:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/6/2022 3:58:23 PM, end: 3/6/2022 4:58:23 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh
Expected: True
Actual:   False


Stack trace
   at JIT_opt._AssertionPropagation_ArrBoundBinaryOp_ArrBoundBinaryOp_._AssertionPropagation_ArrBoundBinaryOp_ArrBoundBinaryOp_sh()
```

**Comment by VincentBu** [comment]
Failed again in:  [runtime-coreclr r2r-extra 20220313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1661469&view=ms.vss-test-web.build-test-results-tab&runId=45727274&resultId=109755&paneView=debug)

Failed test:
```
R2R Linux arm Checked gcstress0xf @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh: line 246: -r:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.dll.rsp': No such file or directory

cmdLine:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 3/14/2022 6:56:09 AM, end: 3/14/2022 8:26:09 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/IL-CG2/ArrBoundBinaryOp.dll
Response file: /root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.dll.rsp
/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/IL-CG2/ArrBoundBinaryOp.dll
-o:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.dll
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ArrBoundBinaryOp.dll ''

cmdLine:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 3/14/2022 6:56:09 AM, end: 3/14/2022 8:26:09 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh
Expected: True
Actual:   False


Stack trace
   at JIT_opt._AssertionPropagation_ArrBoundBinaryOp_ArrBoundBinaryOp_._AssertionPropagation_ArrBoundBinaryOp_ArrBoundBinaryOp_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr gcstress0x3-gcstress0xc 20220327.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1684389&view=ms.vss-test-web.build-test-results-tab&runId=46096170&resultId=109781&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh

```
**Error message:**
```
cmdLine:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/27/2022 3:18:14 PM, end: 3/27/2022 4:18:14 PM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ArrBoundBinaryOp.dll ''

cmdLine:/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/27/2022 3:18:14 PM, end: 3/27/2022 4:18:14 PM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/opt/AssertionPropagation/ArrBoundBinaryOp/ArrBoundBinaryOp.sh
Expected: True
Actual:   False


Stack trace
   at JIT_opt._AssertionPropagation_ArrBoundBinaryOp_ArrBoundBinaryOp_._AssertionPropagation_ArrBoundBinaryOp_ArrBoundBinaryOp_sh()
```

**Comment by mangod9** [comment]
@BruceForstall since this is failing on arm32 only, is there a way to disable for that platform only? Seems like its just timing out on arm?

**Comment by BruceForstall** [comment]
> @BruceForstall since this is failing on arm32 only, is there a way to disable for that platform only? Seems like its just timing out on arm?

If there is a way to disable for GCStress only on arm32, I don't know how. If possible, it should be documented in https://github.com/dotnet/runtime/blob/main/docs/workflow/ci/disabling-tests.md.  fwiw, the test seems aggressively slow. On the other hand, maybe GCStress=3 is too slow, also.

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress0x3-gcstress0xc 20230305.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=193799&view=ms.vss-test-web.build-test-results-tab&runId=3679823&resultId=111310&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0x3 @ Windows.11.Arm64.Open

- tracing\\eventpipe\\enabledisable\\enabledisable\\enabledisable.cmd

coreclr linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh
```
**Error message:**
```
cmdLine:C:\h\w\B6C009D4\w\B1690976\e\tracing\eventpipe\enabledisable\enabledisable\enabledisable.cmd Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/5/2023 3:30:55 PM, end: 3/5/2023 4:30:55 PM)

Return code:      -100
Raw output file:      C:\h\w\B6C009D4\w\B1690976\uploads\Reports\tracing.eventpipe\enabledisable\enabledisable\enabledisable.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B6C009D4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  enabledisable.dll

cmdLine:C:\h\w\B6C009D4\w\B1690976\e\tracing\eventpipe\enabledisable\enabledisable\enabledisable.cmd Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/5/2023 3:30:55 PM, end: 3/5/2023 4:30:55 PM)
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=C:\h\w\B6C009D4\p
C:\h\w\B6C009D4\w\B1690976\e\tracing\eventpipe\enabledisable\enabledisable\enabledisable.cmd
Expected: True
Actual:   False


Stack trace
   at tracing_eventpipe._enabledisable_enabledisable_enabledisable_._enabledisable_enabledisable_enabledisable_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed in Run: [runtime-coreclr gcstress0x3-gcstress0xc 20230312.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=201836)
 
 **Failed tests:**
 ```
 coreclr linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
     - tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh
 ```
 
 **Error message:**
 ```
 
cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/12/2023 2:41:17 PM, end: 3/12/2023 3:41:17 PM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/enabledisable/enabledisable/enabledisable.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false enabledisable.dll ''

cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 3/12/2023 2:41:17 PM, end: 3/12/2023 3:41:17 PM)
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/crashdump_5912.dmp.crashreport.json'
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/e/tracing/eventpipe/enabledisable/enabledisable/enabledisable.sh
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at tracing_eventpipe._enabledisable_enabledisable_enabledisable_._enabledisable_enabledisable_enabledisable_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by mikelle-rogers** [comment]
Created new issue, https://github.com/dotnet/runtime/issues/83359, because test name is different.
