### ISSUE TITLE
Test failure tracing/eventpipe/complus_config/name_config_with_pid/name_config_with_pid.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66276]
Run: [runtime-coreclr jitstress-isas-x86 20220305.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1647092&view=ms.vss-test-web.build-test-results-tab&runId=45496552&resultId=110930&paneView=debug)

Failed test:
```
CoreCLR Linux x64 Checked jitstress_isas_2_x86_nosse2 @ Ubuntu.1804.Amd64.Open

- tracing/eventpipe/complus_config/name_config_with_pid/name_config_with_pid.sh

```
**Error message:**
```
Unhandled exception. System.IO.IOException: Broken pipe
---> System.Net.Sockets.SocketException (32): Broken pipe
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan1 buffer) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 292 --- End of inner exception stack trace --- at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan1 buffer) in //src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 296
at System.IO.Pipes.PipeStream.Write(ReadOnlySpan`1 buffer) in //src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 131
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.WriteLine(String value)
at NameConfigWithPid.Main(String[] args)
/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/tracing/eventpipe/complus_config/name_config_with_pid/name_config_with_pid.sh: line 393:  6976 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/BEB709DF/w/B1CC096E/uploads/Reports/tracing.eventpipe/complus_config/name_config_with_pid/name_config_with_pid.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/BEB709DF/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false name_config_with_pid.dll ''
No Args
Starting process '/datadisks/disk1/work/BEB709DF/p/corerun' '/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/tracing/eventpipe/complus_config/name_config_with_pid/name_config_with_pid.dll waitforinput'
Readline ''
Child process terminating
Gathering state for process 6983 corerun
Crashing thread 00001b47 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.6983.dmp
Written 58208256 bytes (14211 pages) to core file
Dump successfully written
Child process terminated
Gathering state for process 6976 corerun
Crashing thread 00001b40 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.6976.dmp
Written 84328448 bytes (20588 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/BEB709DF/p
/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/tracing/eventpipe/complus_config/name_config_with_pid/name_config_with_pid.sh
Expected: True
Actual:   False


Stack trace
   at tracing_eventpipe._complus_config_name_config_with_pid_name_config_with_pid_._complus_config_name_config_with_pid_name_config_with_pid_sh()
```

**Comment by adamsitnik** [comment]
Based on the following line from log:

> Readline ''

I suspect that the parent process tries to read the child process standard error before it actually writes anything (a race condition):

https://github.com/dotnet/runtime/blob/719d56525ea7b89d052420e7cea88786faf771df/src/tests/tracing/eventpipe/complus_config/name_config_with_pid.cs#L64-L66

`ReadLine` returns `null`:

https://github.com/dotnet/runtime/blob/c3cc9fd5d64df359c54b6d0518db75641e04bbc3/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs#L783-L786

there is a mismatch and it kills the process:

https://github.com/dotnet/runtime/blob/719d56525ea7b89d052420e7cea88786faf771df/src/tests/tracing/eventpipe/complus_config/name_config_with_pid.cs#L68-L72

the pipe gets closed and as the end result we observe "Broken pipe"

**Comment by adamsitnik** [comment]
Since it does not seem to be an IO/Console/Process issue but rather a test bug, I am moving it to the tracing area.

**Comment by tommcdon** [comment]
@BruceForstall 
The target process crashed due to an assert in the JIT: https://github.com/dotnet/runtime/blob/1934775fc47e7992ff4a502a40f6f4060a461b1f/src/coreclr/jit/gentree.cpp#L18174

This looks like a possible duplicate to https://github.com/dotnet/runtime/issues/66205

**Comment by BruceForstall** [comment]
@tommcdon This issue has been fixed. But a question: why didn't the assert show up in the console output? (Unfortunately, the data on AzDO is gone now, so I'm just assuming that it didn't, and the output we see in the GitHub issue text above was all that was seen). Is there something here where a second process is invoked and somehow its stdout/stderr/exceptions are suppressed? If the assert was visible, it would have been trivial to route this.

**Comment by tommcdon** [comment]
> @tommcdon This issue has been fixed. 

Excellent!!

> But a question: why didn't the assert show up in the console output?
> Is there something here where a second process is invoked and somehow its stdout/stderr/exceptions are suppressed? 

Good question.  @josalem might have insights.

**Comment by josalem** [comment]
I didn't write this test, but I can take a look at the code to give a more detailed answer.

For now, it looks like there are multiple processes involved (I see two different PIDs for dumps generated), so I'm betting the first process spawned the second with the correct environment variables. If the second process didn't have its StdOut redirected/piped to the first one's StdOut, then we might not see it.
