### ISSUE TITLE
Test failure tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66368]
Run:[ runtime-coreclr outerloop 20220308.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1651712&view=ms.vss-test-web.build-test-results-tab&runId=45562916&resultId=110088&paneView=debug)

Failed test:
```
R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open

- tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh

```
**Error message:**
```
rm: IL-CG2/composite-r2r.dll: No such file or directory
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh: line 272: -r:/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll.rsp: No such file or directory

cmdLine:/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 3/8/2022 12:26:24 PM, end: 3/8/2022 12:56:24 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/BCD809C1/w/AF25097D/uploads/Reports/tracing.eventpipe/pauseonstart/pauseonstart/pauseonstart.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
Response file: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll
-r:/tmp/helix/working/BCD809C1/p/System..dll
-r:/tmp/helix/working/BCD809C1/p/Microsoft..dll
-r:/tmp/helix/working/BCD809C1/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/BCD809C1/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/common.dll
Response file: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll.rsp
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/common.dll
-o:/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll
-r:/tmp/helix/working/BCD809C1/p/System..dll
-r:/tmp/helix/working/BCD809C1/p/Microsoft..dll
-r:/tmp/helix/working/BCD809C1/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/BCD809C1/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/pauseonstart.dll
Response file: /private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll.rsp
/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/pauseonstart.dll
-o:/private/tmp/helix/working/BCD809C1/w/AF25097D/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll
-r:/tmp/helix/working/BCD809C1/p/System..dll
-r:/tmp/helix/working/BCD809C1/p/Microsoft..dll
-r:/tmp/helix/working/BCD809C1/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running


Stack trace
   at tracing_eventpipe._pauseonstart_pauseonstart_pauseonstart_._pauseonstart_pauseonstart_pauseonstart_sh()
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr outerloop 20220317.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1668802&view=ms.vss-test-web.build-test-results-tab&runId=45855022&resultId=110093&paneView=debug)

Failed test:
```
R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open

- tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh

```
**Error message:**
```
rm: IL-CG2/composite-r2r.dll: No such file or directory
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh: line 272: -r:/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll.rsp: No such file or directory
task_for_pid(86807) FAILED 5 (os/kern) failure
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh: line 405: 86807 Segmentation fault: 11  (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/AF8A0959/w/B99609D7/uploads/Reports/tracing.eventpipe/pauseonstart/pauseonstart/pauseonstart.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
Response file: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll
-r:/tmp/helix/working/AF8A0959/p/System..dll
-r:/tmp/helix/working/AF8A0959/p/Microsoft..dll
-r:/tmp/helix/working/AF8A0959/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/AF8A0959/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/Microsoft.Diagnostics.NETCore.Client.dll
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/common.dll
Response file: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll.rsp
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/common.dll
-o:/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll
-r:/tmp/helix/working/AF8A0959/p/System..dll
-r:/tmp/helix/working/AF8A0959/p/Microsoft..dll
-r:/tmp/helix/working/AF8A0959/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/AF8A0959/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/common.dll
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/pauseonstart.dll
Response file: /private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll.rsp
/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/IL-CG2/pauseonstart.dll
-o:/private/tmp/helix/working/AF8A0959/w/B99609D7/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll
-r:/tmp/helix/working/AF8A0959/p/System..dll
-r:/tmp/helix/working/AF8A0959/p/Microsoft..dll
-r:/tmp/helix/working/AF8A0959/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:


Stack trace
   at tracing_eventpipe._pauseonstart_pauseonstart_pauseonstart_._pauseonstart_pauseonstart_pauseonstart_sh()
```

**Comment by trylek** [comment]
At the first glance this looks like an issue related to CoreCLR runtime diagnostics (event pipe) - do we know whether such a bug existed and has been fixed since or do we need to continue tracking this @tommcdon / @hoyosjs? Thanks!

**Comment by hoyosjs** [comment]
Closing this - the logs are gone and there's no real incident of this outside of PRs that were abandoned.
