### ISSUE TITLE
Test failure System.Text.Json.Serialization.Tests.WriteValueTests.CanWriteValueToJsonArray

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66425]
Run: [runtime-coreclr libraries-jitstress 20220308.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1653303&view=ms.vss-test-web.build-test-results-tab&runId=45585162&resultId=182910&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open

- System.Text.Json.Serialization.Tests.WriteValueTests.CanWriteValueToJsonArray

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Text.Json.JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 614
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1146
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 104
   at System.Text.Json.JsonSerializerOptions.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 34
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 26
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Utf8JsonWriter.cs:line 33
   at System.Text.Json.Serialization.Tests.WriteValueTests.CanWriteValueToJsonArray() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/WriteValueTests.cs:line 97
```

**Comment by elinor-fung** [comment]
I think this going to be the same root issue as https://github.com/dotnet/runtime/issues/66469.

**Comment by eiriktsarpalis** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/66469.
