### ISSUE TITLE
System.Text.Json.Tests crashing from `Debug.Assert` in `JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate`

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#66469]
From [test result](https://dev.azure.com/dnceng/public/_build/results?buildId=1656092&view=ms.vss-test-web.build-test-results-tab&runId=45638452&resultId=186126&paneView=debug) and [log](https://helix.dot.net/api/2019-06-17/jobs/0dd3f850-9e1a-4e47-899e-0a01d678d82f/workitems/System.Text.Json.Tests/console) from https://github.com/dotnet/runtime/pull/66332 - the example failure was on Linux arm64 on mono, but is being hit on other Unix, x64, and on coreclr as well:
```
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 6)
Process terminated due to "   at System.Diagnostics.DebugProvider.Fail(String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.cs:line 22
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 131
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 95
   at System.Diagnostics.Debug.Assert(Boolean condition) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 80
   at System.Text.Json.JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 613
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Text.Json.Serialization.Metadata.JsonTypeInfo, System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].GetOrAdd(Type key, Func`2 valueFactory) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1146
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 104
   at System.Text.Json.JsonSerializerOptions.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 34
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 26
   at System.Text.Json.JsonSerializer.DeserializeAsync[SimpleStruct](Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 49
   at System.Text.Json.Serialization.Tests.NullTests.<>c__DisplayClass10_0.<<ParseNullStringShouldThrowJsonExceptionAsync>b__0>d.MoveNext() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/Null.ReadTests.cs:line 193
```

https://github.com/dotnet/runtime/blob/406d8541926a608ec636b8e4865b4d168273aba3/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L613

**Comment by eiriktsarpalis** [comment]
Hmm, we might want to use a volatile write for `IsInitializedForReflectionSerializer` here:
https://github.com/dotnet/runtime/blob/406d8541926a608ec636b8e4865b4d168273aba3/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L591-L592

**Comment by elinor-fung** [comment]
I'm going to mark this as blocking-clean-ci. I've seen this on three different PRs I've been on today.

Query below shows a bunch of hits. Some of them might be a different crash (I don't know how to come up with a query to differentiate), but I opened five of the logs from today and they were all this assert.

```kusto
WorkItems
| where FriendlyName == "System.Text.Json.Tests"
| where  Queued > ago(3d)
| where ExitCode == 134
| join Jobs on JobId
| project
  Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  RuntimeFlavor = tostring(parse_json(Properties).runtimeFlavor),
  BuildId = tostring(parse_json(Properties).BuildId),
  QueueName, Source
```

**Comment by eiriktsarpalis** [comment]
I'm OOF but @layomia should be able to take a look at this tomorrow.

**Comment by danmoseley** [comment]
As an aside it seems that `Debug.Assert(condition)` ought to pass a default message.
