### ISSUE TITLE
System.Text.Json tests fail around DST time change

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#66555]
Failed in https://github.com/dotnet/runtime/pull/66534
```
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 2813 of 2871 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 6)
    System.Text.Json.Serialization.Tests.ConstructorTests_Span.ClassWithPrimitives_Parameterless [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:11.1679350-08:00
      Actual:   2023-03-12T03:43:11.1679350-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(401,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives_Parameterless()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_String.ClassWithPrimitives_Parameterless [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:11.2332270-08:00
      Actual:   2023-03-12T03:43:11.2332270-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(401,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives_Parameterless()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_AsyncStream.ClassWithPrimitives [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:54.8463990-08:00
      Actual:   2023-03-12T03:43:54.8463990-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(442,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_Span.ClassWithPrimitives [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:55.2968210-08:00
      Actual:   2023-03-12T03:43:55.2968210-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(442,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_SyncStream.ClassWithPrimitives [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:55.6895020-08:00
      Actual:   2023-03-12T03:43:55.6895020-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(442,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_SyncStream.ClassWithPrimitives_Parameterless [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:55.9520640-08:00
      Actual:   2023-03-12T03:43:55.9520640-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(401,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives_Parameterless()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_String.ClassWithPrimitives [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:56.6093880-08:00
      Actual:   2023-03-12T03:43:56.6093880-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(442,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives()
        --- End of stack trace from previous location ---
    System.Text.Json.Serialization.Tests.ConstructorTests_AsyncStream.ClassWithPrimitives_Parameterless [FAIL]
      Assert.Equal() Failure
      Expected: 2023-03-12T02:43:57.3079840-08:00
      Actual:   2023-03-12T03:43:57.3079840-07:00
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.ParameterMatching.cs(401,0): at System.Text.Json.Serialization.Tests.ConstructorTests.ClassWithPrimitives_Parameterless()
        --- End of stack trace from previous location ---
  Finished:    System.Text.Json.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.Json.Tests  Total: 17477, Errors: 0, Failed: 8, Skipped: 0, Time: 124.877s
```

**Comment by Clockwork-Muse** [comment]
I'm looking at this one.
