### ISSUE TITLE
NativeAOT InvalidCastException while compiling a generic mess

### ISSUE THREAD

**Issue by RossNordby** [dotnet/runtime#66573]
Attempting to compile this snippet:
```cs
static class Program
{
    struct SmallCat<T> { }

    interface ITechnique
    {
        void CatSlaps<T>();
    }

    struct ExtremelySmallCat : ITechnique
    {
        public void CatSlaps<T>() { }
    }

    static void Consider<TSomeCat, TAnotherFormOfCat>() where TSomeCat : struct, ITechnique
    {
        default(TSomeCat).CatSlaps<TAnotherFormOfCat>();
    }

    static void CatConcepts<T>()
    {
        Consider<ExtremelySmallCat, SmallCat<T>>();
    }

    static void Main()
    {
        CatConcepts<int>();
    }
}
```
with this csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
  </ItemGroup>

</Project>
```
with CLI:
`dotnet publish -c Release -r win10-x64`
with sdk version 7.0.100-preview.1.22110.4, ilcompiler version 7.0.0-alpha.1.22074.1 on Windows 11 22000.556 yields this output:

<details><summary>Build output</summary><blockquote>
Microsoft (R) Build Engine version 17.2.0-preview-22104-01+09bdfae16 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\norbe\source\repos\scratchpad\Abomination\AbominationInterop\ReproAttempt\ReproAttempt.csproj (in 5
  45 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
C:\Program Files\dotnet\sdk\7.0.100-preview.1.22110.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1113,5):
 warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used.
[C:\Users\norbe\source\repos\scratchpad\Abomination\AbominationInterop\ReproAttempt\ReproAttempt.csproj]
  ReproAttempt -> C:\Users\norbe\source\repos\scratchpad\Abomination\AbominationInterop\ReproAttempt\bin\Release\net7.0
  \win10-x64\ReproAttempt.dll
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
EXEC : error : One or more errors occurred. (Code generation failed for method '[ReproAttempt]Program.Consider<Extremel
ySmallCat,SmallCat`1<__Canon>>()') [C:\Users\norbe\source\repos\scratchpad\Abomination\AbominationInterop\ReproAttempt\
ReproAttempt.csproj]
  System.AggregateException: One or more errors occurred. (Code generation failed for method '[ReproAttempt]Program.Con
  sider<ExtremelySmallCat,SmallCat`1<__Canon>>()')
   ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[ReproAttempt]Program.Consider<Ext
  remelySmallCat,SmallCat`1<__Canon>>()'
   ---> System.InvalidCastException: Unable to cast object of type 'Internal.TypeSystem.Ecma.EcmaType' to type 'Interna
  l.TypeSystem.InstantiatedType'.
     at Internal.IL.ILImporter.ImportCall(ILOpcode opcode, Int32 token)
     at Internal.IL.ILImporter.ImportBasicBlock(BasicBlock basicBlock)
     at Internal.IL.ILImporter.ImportBasicBlocks()
     at Internal.IL.ILImporter.Import()
     at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode)
     --- End of inner exception stack trace ---
     at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeo
  ut, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeo
  ut, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boo
  lean stopOnFirstFailure)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions paral
  lelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, Cancel
  lationToken cancelToken, Exception otherException)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions paral
  lelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Ac
  tion`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEve
  rything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOpt
  ions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bod
  yWithEverything, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`
  1 body)
     at ILCompiler.ILScanner.CompileMultiThreaded(List`1 methodsToCompile)
     at ILCompiler.ILScanner.ComputeDependencyNodeDependencies(List`1 obj)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
C:\Users\norbe\.nuget\packages\microsoft.dotnet.ilcompiler\7.0.0-alpha.1.22074.1\build\Microsoft.NETCore.Native.targets
(306,5): error MSB3073: The command ""C:\Users\norbe\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.0-
alpha.1.22074.1\tools\\ilc" @"obj\Release\net7.0\win10-x64\native\ReproAttempt.ilc.rsp"" exited with code 1. [C:\Users\
norbe\source\repos\scratchpad\Abomination\AbominationInterop\ReproAttempt\ReproAttempt.csproj]
</blockquote></details>

**Comment by hez2010** [comment]
I cannot repro this issue. But instead, I found the NativeAOT-ed exe will exit immediately after launching due to an AV exception if I changed the source code to:

```csharp
static class Program
{
    struct SmallCat<T> { }

    interface ITechnique
    {
        void CatSlaps<T>() { Console.WriteLine("hello"); }
    }

    struct ExtremelySmallCat : ITechnique
    {
        
    }

    static void Consider<TSomeCat, TAnotherFormOfCat>() where TSomeCat : struct, ITechnique
    {
        default(TSomeCat).CatSlaps<TAnotherFormOfCat>();
    }

    static void CatConcepts<T>()
    {
        Consider<ExtremelySmallCat, SmallCat<T>>();
    }

    static void Main()
    {
        CatConcepts<int>();
    }
}
```

Exit code: 0xc0000005
