### ISSUE TITLE
Test failure System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66803]
Run: [runtime-libraries-coreclr outerloop 20220317.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1668177&view=ms.vss-test-web.build-test-results-tab&runId=45839696&resultId=104049&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759

- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-x64-CoreCLR_release-(openSUSE.15.2.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-15.2-helix-amd64-20211018152525-9cc02fe

- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-x64-CoreCLR_release-(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20210913123654-4f64125
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-x64-CoreCLR_release-(Ubuntu.2110.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.04-helix-amd64-20210922170909-34a2d72
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-x64-CoreCLR_release-(Debian.11.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64-20210304164428-5a7c380
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.2110.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.10-helix-arm64v8-20211116135000-0f8d97e
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)

net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeIntermediate_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: True, notTimeValid: True)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(policyErrors: False, notTimeValid: True)
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)) (Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)) (Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)) (Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)) (Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1))
---- Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)
---- Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)
---- Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)
---- Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)
---- Assert.Equal() Failure
↓ (pos 1)
Expected: [NotValidForUsage, NotValidForUsage, NotTimeValid | Revoked ···
Actual:   [NotValidForUsage, NotValidForUsage | RevocationStatusUnknow···
↑ (pos 1)


Stack trace
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 48
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.SimpleTest(PkiOptions pkiOptions, RunSimpleTest callback, String callerName, Boolean pkiOptionsInTestName) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1543
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_PolicyErrors_NotTimeValid(Boolean policyErrors, Boolean notTimeValid) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 645
----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass24_0.<RevokeEndEntity_PolicyErrors_NotTimeValid>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 683
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass24_0.<RevokeEndEntity_PolicyErrors_NotTimeValid>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 683
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass24_0.<RevokeEndEntity_PolicyErrors_NotTimeValid>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 683
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #4 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass24_0.<RevokeEndEntity_PolicyErrors_NotTimeValid>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 683
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #5 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass24_0.<RevokeEndEntity_PolicyErrors_NotTimeValid>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 683
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
```

**Comment by vcsjones** [comment]
This could be https://github.com/dotnet/runtime/pull/66520, so I'll take a look at it.

**Comment by vcsjones** [comment]
Even reverting #66520 I still see failures on Linux (and I fail to see how that PR could have caused Linux to start failing).

Steps I took

```shell
git show -R 4bcc7998f03f9e8c9d008d56e997d1c9d935e3a7 | git apply # Undo PR
./dotnet.sh test src/libraries/System.Security.Cryptography.X509Certificates/tests/ --filter RevokeEndEntity_PolicyErrors_NotTimeValid /p:OuterLoop=true
```

**Comment by bartonjs** [comment]
Two possibilities come to mind:

* I impacted this test when adding tracing.
* We got an OpenSSL update that's changing a reported status code here.

The first seems more likely.  I'm looking into that possibility now.

**Comment by bartonjs** [comment]
Yeah, introduced during a different bugfix detected by tracing.  Hmm... how to get the best of both worlds...
