### ISSUE TITLE
Possible Assert when disposing SslStream during transfer/handshake

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#66818]
On Debug libraries build, it is possible to hit an assert in `System.Net.ArrayBuffer.Discard` in `System.Net.Security.SslStream.SslBuffer.DiscardEncrypted` if the `SslStream` instance is disposed during handshake. This used to cause occasional test crash on CI builds (e.g. https://github.com/dotnet/runtime/issues/65455).

We should make sure that disposing `SslStream` instances in flight does not trigger the assert and/or cause subtle bugs on Release configuration such as two `SslStream` instances writing to the same pooled `byte[]` buffer.

**Comment by wfurt** [comment]
failed in https://helix.dot.net/api/2019-06-17/jobs/84a6a55e-cf80-4aca-b0a5-fc4afb645eea/workitems/System.Net.Security.Tests/console cc: @hoyosjs 

```
Process terminated. Assertion failed.
Expected 7 <= 0
   at System.Net.ArrayBuffer.Discard(Int32 byteCount) in /_/src/libraries/Common/src/System/Net/ArrayBuffer.cs:line 67
   at System.Net.Security.SslStream.SslBuffer.DiscardEncrypted(Int32 byteCount) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs:line 154
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 497
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 486
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
```

**Comment by rzikm** [comment]
According to timestamp, this was before #66682 was merged. Dump analysis shows that it was the same test as fixed in the PR

**Comment by karelz** [comment]
Triage:
- Similar in HTTP/3
- We should throw ObjectDisposedException instead of using disposed object -- if we can't due to multi-threading, we might need to remove the assert from `ArrayBuffer`, or @wfurt has another idea
- Asserts are bad as they crash the entire test suite
