### ISSUE TITLE
Should support Ber encoded timestamp

### ISSUE THREAD

**Issue by scott-xu** [dotnet/runtime#66834]
### Description

It only supported Der AsnEncodingRule when process response.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Rfc3161TimestampRequest.cs#L87

### Reproduction Steps

make a timestamp request to http://timestamp.entrust.net/TSS/RFC3161sha2TS and process the response

### Expected behavior

should successfully process the response

### Actual behavior

```
System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
 ---> System.Formats.Asn1.AsnContentException: The encoded value is not valid under the selected encoding, but it may be valid under the BER encoding.
   at System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Type flagsEnumType, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue[TFlagsEnum](ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnValueReader.ReadNamedBitListValue[TFlagsEnum](Nullable`1 expectedTag)
   at System.Security.Cryptography.Pkcs.Asn1.PkiStatusInfo.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PkiStatusInfo& decoded)
   at System.Security.Cryptography.Pkcs.Asn1.PkiStatusInfo.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PkiStatusInfo& decoded)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.Pkcs.Asn1.PkiStatusInfo.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PkiStatusInfo& decoded)
   at System.Security.Cryptography.Pkcs.Asn1.PkiStatusInfo.Decode(AsnValueReader& reader, ReadOnlyMemory`1 rebind, PkiStatusInfo& decoded)
   at System.Security.Cryptography.Pkcs.Asn1.Rfc3161TimeStampResp.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, Rfc3161TimeStampResp& decoded)
   at System.Security.Cryptography.Pkcs.Asn1.Rfc3161TimeStampResp.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, Rfc3161TimeStampResp& decoded)
   at System.Security.Cryptography.Pkcs.Asn1.Rfc3161TimeStampResp.Decode(AsnValueReader& reader, ReadOnlyMemory`1 rebind, Rfc3161TimeStampResp& decoded)
   at System.Security.Cryptography.Pkcs.Rfc3161TimestampRequest.ProcessResponse(ReadOnlyMemory`1 source, Rfc3161TimestampToken& token, Rfc3161RequestResponseStatus& status, Int32& bytesConsumed, Boolean shouldThrow)
   at System.Security.Cryptography.Pkcs.Rfc3161TimestampRequest.ProcessResponse(ReadOnlyMemory`1 responseBytes, Int32& bytesConsumed)
```

### Other information

Suggest adding `AsnEncodingRule` parameter to the `ProcessResponse` method

**Comment by filipnavara** [comment]
RFC 3161 is quite explicit about DER encoding being required.

**Comment by bartonjs** [comment]
All transport schemes described in [RFC3161, section 3](https://datatracker.ietf.org/doc/html/rfc3161#section-3) specify DER.

Entrust's TSA appears to not be spec-compliant.

**Comment by vcsjones** [comment]
I cannot reproduce this:

```C#
#nullable enable
using System;
using System.Net.Http;
using System.Security.Cryptography;
using System.Security.Cryptography.Pkcs;
using System.Security.Cryptography.X509Certificates;

Rfc3161TimestampRequest req = Rfc3161TimestampRequest.CreateFromData(
    new byte[] { 1 },
    HashAlgorithmName.SHA256,
    requestSignerCertificates: true);

byte[] encoded = req.Encode();
HttpClient client = new HttpClient();

ByteArrayContent requestData = new(encoded);
requestData.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/timestamp-query");
HttpResponseMessage response = await client.PostAsync(
    "http://timestamp.entrust.net/TSS/RFC3161sha2TS",
    requestData);

response.EnsureSuccessStatusCode();
byte[] timestampBytes = await response.Content.ReadAsByteArrayAsync();

Rfc3161TimestampToken token = req.ProcessResponse(timestampBytes, out _);

if (!token.VerifySignatureForData(new byte[] { 1 }, out X509Certificate2? cert))
{
    Console.WriteLine("Could not verify signature.");
    return;
}
Console.WriteLine(token.TokenInfo.Timestamp);
```

Gives me the output:

> 3/18/2022 5:01:52 PM +00:00

**Comment by bartonjs** [comment]
For what it's worth... we were going to fail anyways, even if we accepted BER.

The line that failed was decoding PkiStatusInfo.FailInfo, meaning the request had (almost certainly) failed.  So, we would have just thrown a different exception: https://github.com/dotnet/runtime/blob/0b12d37843e7165fb4c8b794186f19ef43af6c73/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Rfc3161TimestampRequest.cs#L119-L123

**Comment by bartonjs** [comment]
Since @vcsjones has shown that the referenced TSA successfully handles requests we produce, all RFC-suggested transports require DER-encoded responses (thanks for the quick suggestion on that, @filipnavara), and we're just talking about trading one exception for another... I don't think there's any work to be done here.

**Comment by scott-xu** [comment]
I just found the root cause. I'm using SHA1 as the timestamp digest algorithm in the timestamp request. The Entrust TSA sometimes successfully do the timestamp while sometimes not. (I guess there are several nodes in the backend with different configuration)
When it failed to do the timestamp it replies something like "UnsupportedAlgorithmTSError" in the content with http status code 200.
@bartonjs @vcsjones Thanks for your help.
