### ISSUE TITLE
Debug.Assert(false) on Mono produces  `Process terminated due to "  ` 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#66971]
On CoreCLR, `Debug.Assert(false)` produces `Process terminated. Assertion failed.`  which is reasonable. eg

```
Process terminated. Assertion failed.
   at C.Main() in /home/dan/proj/1/Program.cs:line 9
```

On Mono, it produces `Process terminated due to "  ` (such as seen below) which is untidy and also discarding potentially useful info.

```
Process terminated due to "   at System.Diagnostics.DebugProvider.Fail(String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.cs:line 22
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 131
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 95
   at System.Diagnostics.Debug.Assert(Boolean condition) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 80
   at System.Text.Json.JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 613
```

Seems this needs a couple things

1. an empty string check here https://github.com/dotnet/runtime/blob/baffb7107f4f2b11e7ff40859b2c3f4782ada791/src/mono/mono/metadata/icall.c#L6022
2. rather than ignoring the errorsource here, write it out as [coreclr does](https://github.com/dotnet/runtime/blob/baffb7107f4f2b11e7ff40859b2c3f4782ada791/src/coreclr/vm/eepolicy.cpp#L384) https://github.com/dotnet/runtime/blob/baffb7107f4f2b11e7ff40859b2c3f4782ada791/src/mono/mono/metadata/icall.c#L6020
3. add any missing new line before the callstack.

**Comment by danmoseley** [comment]
I'm going to assume this isn't controversial and mark up for grabs.

**Comment by pedrobsaila** [comment]
Hi @danmoseley , I would like to work on this issue. However I don't find any docs on debugging mono on linux (I found just for wasm and android). Do you have any idea on how to do it ?
