### ISSUE TITLE
Assertion failure in System.IO.Tests.FileSystemWatcherTest.VerifyExpectedPaths brings down tests

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#67071]
https://dev.azure.com/dnceng/public/_build/results?buildId=1678750&view=ms.vss-test-web.build-test-results-tab&runId=46008018&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=185660
on OSX. The filesystemwatcher tests are not 100% on Mac despite ongoing efforts. But it would be good to avoid asserting on a FSW event handler like this, as it brings down all the tests.
```
Unhandled exception. Xunit.Sdk.XunitException: Expected path(s):

Actual path: /var/folders/w0/b90psr5x21db419f956qf76c0000gq/T/SymbolicLink_Changed_Tests_us4a433c.dsa/FileSystemWatcher_SymbolicLink_IncludeSubdirectories_DoNotDereferenceChildLink_112_e28dd8e4/GetRandomDirName_85_ec123968_dir.link
   at System.IO.Tests.FileSystemWatcherTest.VerifyExpectedPaths(String[] expectedPaths, FileSystemEventArgs e) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 57
   at System.IO.Tests.FileSystemWatcherTest.<>c__DisplayClass10_0.<WatchCreated>b__0(Object o, FileSystemEventArgs e) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 80
   at System.IO.FileSystemWatcher.InvokeOn(FileSystemEventArgs e, FileSystemEventHandler handler) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 504
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 455
   at System.IO.FileSystemWatcher.RunningInstance.ProcessEvents(Int32 numEvents, Byte** eventPaths, Span`1 eventFlags, Span`1 eventIds, FileSystemWatcher watcher) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 475
   at System.IO.FileSystemWatcher.RunningInstance.<>c__DisplayClass14_0.<FileSystemEventCallback>b__0(Object o) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 417
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.IO.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr streamRef, IntPtr clientCallBackInfo, IntPtr numEvents, Byte** eventPaths, FSEventStreamEventFlags* eventFlags, UInt64* eventIds) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 415
./RunTests.sh: line 168: 13532 Abort trap: 6           "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.FileSystem.Watcher.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Watcher.Tests.deps.json xunit.console.dll System.IO.FileSystem.Watcher.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

**Comment by Jozkee** [comment]
This is happening because the test uses `ExpectNoEvent`, without `expectedPath` parameter, which makes a `new string[] { null }` on line 239. 
https://github.com/dotnet/runtime/blob/1a296c06fff8750b4658f6f7d901347e006744d0/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs#L237-L239
