### ISSUE TITLE
Test failure System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Ssl3)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67076]
Run: [runtime-coreclr libraries-jitstress 20220323.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1678069&view=ms.vss-test-web.build-test-results-tab&runId=45996014&resultId=190706&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Ssl3)

```
**Error message:**
```
System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.


Stack trace
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 427
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 350
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 421
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(SslProtocols protocol) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20220403.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1697345&view=ms.vss-test-web.build-test-results-tab&runId=46297952&paneView=debug&resultId=191910)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs4-Windows.10.Arm64v8.Open

- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Ssl3)

```
**Error message:**
```
System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.


Stack trace
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 427
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 350
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 421
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(SslProtocols protocol) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Triage: Looks like mainly/only JitStress - @rzikm to confirm.
Moving to Future. Similar to #53404.

**Comment by rzikm** [comment]
Pipelines: `runtime-coreclr libraries-jitstress` and `runtime-coreclr libraries-jitstressregs`, Five occurences in last 14 days

**Comment by wfurt** [comment]
How many total runs? (e.g. what is failure rate) 
Can you dig out console log @rzikm? Do you know if we run normal runtime tests on that queue? We may check registry setting if all failures are Ssl3.

**Comment by wfurt** [comment]
Could you put together draft PR to run our functional tests on that particular queue. I'm wondering if we will see some failures as well.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20220424.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1735202&view=ms.vss-test-web.build-test-results-tab&runId=46974946&paneView=debug&resultId=193725)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs1-Windows.10.Arm64v8.Open

- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(protocol: Ssl3)

```
**Error message:**
```
System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.


Stack trace
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 427
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 350
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncSslHelper(SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, Boolean expectedToFail) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 421
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_EachSupportedProtocol_Success(SslProtocols protocol) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by rzikm** [comment]
@wfurt I put up the draft PR, I ran the runtime pipeline twice and there were no failures on the Windows.10.Arm64v8.Open queue both times

**Comment by wfurt** [comment]
So it seems this is really jitstress related. And it is either timing on tests or real product bug exposed by the jitstress. e.g. something gets collected prematurely.

**Comment by rzikm** [comment]
There are no recent failures in the test db, so this is no longer actionable for us. Closing until it resurfaces
