### ISSUE TITLE
Test failure System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls12, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67075]
Run: [runtime-coreclr libraries-jitstress 20220323.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1678069&view=ms.vss-test-web.build-test-results-tab&runId=45996014&resultId=190843&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls12, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls11, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls12, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls11, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Tls, serverProtocol: Ssl3, expectedException: typeof(System.Security.Authentication.AuthenticationException))
```
**Error message:**
```
Assert.IsAssignableFrom() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.TimeoutException)


Stack trace
   at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols clientProtocol, SslProtocols serverProtocol, Type expectedException) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs:line 66
--- End of stack trace from previous location ---
```
Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Ssl3, serverProtocol: Tls12, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Ssl3, serverProtocol: Tls11, expectedException: typeof(System.Security.Authentication.AuthenticationException))
- System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(clientProtocol: Ssl3, serverProtocol: Tls, expectedException: typeof(System.Security.Authentication.AuthenticationException))
```
**Error message:**
```
Assert.IsAssignableFrom() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.IO.IOException)


Stack trace
   at System.Net.Security.Tests.ServerAsyncAuthenticateTest.ServerAsyncAuthenticate_MismatchProtocols_Fails(SslProtocols clientProtocol, SslProtocols serverProtocol, Type expectedException) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs:line 63
--- End of stack trace from previous location ---
```

**Comment by rzikm** [comment]
Looks like duplicate of https://github.com/dotnet/runtime/issues/65098
