### ISSUE TITLE
Test failure System.Diagnostics.Metrics.Tests.MetricsTests.PassingVariableTagsParametersTest

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67077]
Run: [runtime-coreclr libraries-jitstress 20220323.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1678069&view=ms.vss-test-web.build-test-results-tab&runId=45995996&resultId=166142&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress2_tiered-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.Diagnostics.Metrics.Tests.MetricsTests.PassingVariableTagsParametersTest

```
**Error message:**
```
Exit code was 139 but it should have been 42
Expected: True
Actual:   False


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 239
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 57
   at System.Diagnostics.Metrics.Tests.MetricsTests.PassingVariableTagsParametersTest() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricsTests.cs:line 615
```

**Comment by noahfalk** [comment]
@AndyAyersMS - hey Andy I was triaging and found this jit stress bug which is a few months old. If anyone on your team thinks it would be interesting I'm happy to reopen and reassign it.
