### ISSUE TITLE
NullReferenceException in System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper when using ILGenerator.EmitCall on an interface method with 'in' arguments.

### ISSUE THREAD

**Issue by ruediger-stevens** [dotnet/runtime#67084]
### Description

When I create a DynamicMethod and then use EmitCall to call an interface method that contains at least one 'in' argument a NullReferenceException occurs in System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper.

### Reproduction Steps

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Linq;
using System.Runtime.InteropServices;
using Xunit;

namespace System.Reflection.Emit.Tests
{
    [ActiveIssue("https://github.com/dotnet/runtime/issues/XXXX", TestPlatforms.Browser)]
    public sealed class ILGeneratorEmit5
    {
        public interface IHelper
        {
            int PassThrough(in int value);
        }
      
        public sealed class Helper : IHelper
        {
            public int PassThrough(in int value) => value;
        }
        
        [Fact]
        public void TestEmitCallFunctionWithInArgumentFromDynamicMethod()
        {
            var methodToCall = typeof(IHelper).GetMethod("PassThrough");

            var dynamicMethod = new DynamicMethod("CallingPassThrough",
                MethodAttributes.Public | MethodAttributes.Static,
                CallingConventions.Standard,
                typeof(int),
                new []
                {
                  typeof(IHelper),
                  typeof(int),
                },
                typeof(ILGeneratorEmit5),
                true);
                
            var il = dynamicMethod.GetILGenerator();
            
            var copy = il.DeclareLocal(typeof(int), false);
            
            il.Emit(OpCodes.Ldarg_1);
            il.Emit(OpCodes.Stloc, (ushort)copy.LocalIndex);
            
            il.Emit(OpCodes.Ldarg_0);
            il.Emit(OpCodes.Ldloca, (ushort)copy.LocalIndex);
            
            il.EmitCall(OpCodes.Call, methodToCall, null);
            
            il.Emit(OpCodes.Ret);
 
            var func = (Func<IHelper, int, int>)dynamicMethod.CreateDelegate(typeof(Func<IHelper, int, int>));
            
            var helperInstance = new Helper();
 
            var sum = func(helperInstance, 888);
            
            Assert.Equal(888, sum);
        }
    }
}

### Expected behavior

This code should run without exceptions

### Actual behavior

System.NullReferenceException : Object reference not set to an instance of an object.
  at System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(Type clsArgument, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\SignatureHelper.cs:line 322
   at System.Reflection.Emit.SignatureHelper.AddArgument(Type argument, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\SignatureHelper.cs:line 789
   at System.Reflection.Emit.SignatureHelper.AddArguments(Type[] arguments, Type[][] requiredCustomModifiers, Type[][] optionalCustomModifiers) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\SignatureHelper.cs:line 760
   at System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(Module scope, CallingConventions callingConvention, Int32 cGenericParam, Type returnType, Type[] requiredReturnTypeCustomModifiers, Type[] optionalReturnTypeCustomModifiers, Type[] parameterTypes, Type[][] requiredParameterTypeCustomModifiers, Type[][] optionalParameterTypeCustomModifiers) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\SignatureHelper.cs:line 75
   at System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(Module scope, CallingConventions callingConvention, Type returnType, Type[] requiredReturnTypeCustomModifiers, Type[] optionalReturnTypeCustomModifiers, Type[] parameterTypes, Type[][] requiredParameterTypeCustomModifiers, Type[][] optionalParameterTypeCustomModifiers) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\SignatureHelper.cs:line 43
   at System.Reflection.Emit.DynamicILGenerator.GetMemberRefSignature(CallingConventions call, Type returnType, Type[] parameterTypes, Type[][] requiredCustomModifiers, Type[][] optionalCustomModifiers, Type[] optionalParameterTypes) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\DynamicILGenerator.cs:line 476
   at System.Reflection.Emit.DynamicILGenerator.GetMemberRefToken(MethodBase methodInfo, Type[] optionalParameterTypes) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\DynamicILGenerator.cs:line 455
   at System.Reflection.Emit.DynamicILGenerator.EmitCall(OpCode opcode, MethodInfo methodInfo, Type[] optionalParameterTypes) in E:\Data\wc\github\dotnet_runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\Emit\DynamicILGenerator.cs:line 284
   at System.Reflection.Emit.Tests.ILGeneratorEmit5.TestEmitCallFunctionWithInArgumentFromDynamicMethod() in E:\Data\wc\github\dotnet_runtime\src\libraries\System.Reflection.Emit.ILGeneration\tests\ILGenerator\Emit5Tests.cs:line 50

### Regression?

This worked in .NET 4.7.2

### Known Workarounds

Currently: None!

### Configuration

I checked against release/net6 branch

**Comment by jkotas** [comment]
Regression likely introduced by https://github.com/dotnet/coreclr/pull/17881

**Comment by wzchua** [comment]
The signatureHelper uses `m_module` to get the tokens for the modifier and in many other places. This means DynamicMethod can't make use of it.

I noticed for ` Emit(OpCode opcode, MethodInfo meth!!)`, It just uses a count based on a list. I assume the correct fix is to use the same mechanism?

**Comment by jkotas** [comment]
I do not think it can be as simple as that. It still needs to store the optional argument types.

**Comment by steveharter** [comment]
@ruediger-stevens thanks for the nice repro. I verified this worked in .NET 5.0 (Core) but doesn't in 6.0\7.0.
