### ISSUE TITLE
"[XmlException] Data at the root level is invalid" at xml app.config read since .Net6

### ISSUE THREAD

**Issue by Maxyeah** [dotnet/runtime#67136]
### Describe the bug
Our internal configuration implementation with app.config isn´t working since update to .Net6.
If the application has no certificate at startup, it will create a new on and updates the app.config with properties from the certificate.
The Extension update fails with the following exception: [XmlException] Data at the root level is invalid. Line 1, position 1.
```
           // serialize value.
            var strm = new System.IO.MemoryStream();

            using (strm)
            {
                if (value != null)
                {
                    if (!UsesXmlSerialization(typeof(T)))
                    {
                        DataContractSerializer serializer = new DataContractSerializer(typeof(T));
                        serializer.WriteObject(strm, value);
                    }
                    else
                    {
                        XmlSerializer serializer = new XmlSerializer(typeof(T));
                        serializer.Serialize(strm, value);
                    }
                }
                // update dictionary.
                extensions[elementName] = strm.ToArray();
            }
```

The XML begins with:
```
 <?xml version="1.0" ?>
 <configuration>
   <configSections>
```

### Exceptions (if any)
Stack Trace:
[XmlException] Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at System.Xml.XmlDocument.set_InnerXml(String value)

### Further technical details
$ dotnet --info
.NET SDK (gem▒▒ "global.json"):
 Version:   6.0.101
 Commit:    ef49f6213a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.1.806 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

- Running on VS2022 (Version 17.0.5)

**Comment by StephenMolloy** [comment]
Fixed by #73731
