### ISSUE TITLE
Different Exit code when IHost stops from failing (async)IHostedService

### ISSUE THREAD

**Issue by Vandersteen** [dotnet/runtime#67146]
Given the following `Program.cs`

```c#
IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>(); 
        services.Configure<HostOptions>(hostOptions =>
        {
            hostOptions.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.StopHost;
        });
    })
    .Build();

await host.RunAsync();
```

And `Worker.cs`

```c#
public class Worker : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        //await Task.Delay(TimeSpan.FromSeconds(1), stoppingToken);
        throw new Exception();
    }
}
```

I get an 'error' exit code, which is usefull to detect errors in let's say kubernetes

> Process finished with exit code 134.

However when uncommenting the 'await Task...' 

There is no longer an 'error' exit code

```
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      System.Exception: Exception of type 'System.Exception' was thrown.
         at TestUpgrade.Worker.ExecuteAsync(CancellationToken stoppingToken) in Worker.cs:line 8
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

Process finished with exit code 0. <-------
```

Is there a way to detect this case using the hostbuilder ?

**Comment by eerhardt** [comment]
The difference in behavior here is that when you don't `await` in your hosted service, your code runs inline during the process startup. Thus when an exception is thrown before `await` happens, your startup is failing and the app crashes.

After the `await` has occurred, the host is started and the background service throws an exception, which the host catches, logs, and then exits the app. In that case the app exists "cleanly" today.

I think it would make sense to set the exit code to something non-zero in this case to indicate that the app has been stopped. Potentially, we may need an option to control the behavior if someone wants to opt-out of it.

Thoughts, @davidfowl @Tratcher @maryamariyan ?

**Comment by maryamariyan** [comment]
> I think it would make sense to set the exit code to something non-zero in this case to indicate that the app has been stopped.

+1. Keeping as-is. Might be good to look for more feedback here before deciding on how to approach this.

**Comment by deeprobin** [comment]
@maryamariyan In my private kubernetes development cluster I already had also the problem that error handling is hard to show without error code.

Kubernetes dashboard for ex. would otherwise display the status "finished" or something like that instead of "Failed".
![grafik](https://user-images.githubusercontent.com/10373452/170321483-0e18bbe0-b501-4739-aaa3-5feff616bea7.png)

But there are many usecases (for ex. Docker)

**Comment by davidfowl** [comment]
Why not change application code to return a non-zero exit code? This feels more like a template change than a change to these APIs tbh.

**Comment by eerhardt** [comment]
> Why not change application code to return a non-zero exit code?

How does the app know to return a non-zero exit code?

```C#
IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .Build();

await host.RunAsync();
```

`Run` and `RunAsync` return `void` and `Task`.

https://github.com/dotnet/runtime/blob/8aac5ee2e821498684b385f443d2474db215b2ae/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs#L48-L60

We would somehow need to bubble the exception up through `RunAsync`. Or some other way to know that the `Host` faulted.

**Comment by davidfowl** [comment]
Then I would change the title of this issue to make sure that RunAsync throws if we're shutting down the host. We can store the exception and make StopAsync throw observe the exception.

**Comment by eerhardt** [comment]
I think the title is fine - it describes the intended behavior, not the solution.

There are other possible solutions here. One would be to store the caught exceptions on the `IHost`, and expose them publicly in a property. Then the app code can do whatever they want after `RunAsync` is done by inspecting the background exceptions.

**Comment by davidfowl** [comment]
We shouldn't be setting the exit code. We used to do that a long time ago in the library because of other issues but the application owns the entrypoint.

> There are other possible solutions here. One would be to store the caught exceptions on the IHost, and expose them publicly in a property. Then the app code can do whatever they want after RunAsync is done by inspecting the background exceptions.

Maybe it's both? RunAsync is one observer of the Exception that was captured, which rethrows.

**Comment by tmds** [comment]
Exiting due to failure with a success exit code is bad.

> We can store the exception and make StopAsync throw observe the exception.

This seems like the proper thing to do. `StopAsync` already throws an `AggregateException` when `IHostedServices` throw during `StopAsync`.

We can't capture the exception for the generic `IHostedServices` because they don't have a `Task` that tracks the execution.
It is possible for `BackgroundService`, which has such a `Task` (`ExecuteTask` property).
(note: `ExecuteTask` isn't set if someone overrides StartAsync but forgets to call the base version.)

**Comment by deeprobin** [comment]
> We can't capture the exception for the generic IHostedServices because they don't have a Task that tracks the execution.

@tmds 
How about try-catch?

**Comment by Dean-NC** [comment]
I agree with the ability to have a different exit code. I'd like my Windows service's recovery to get done (restart), but with `BackgroundServiceExceptionBehavior.StopHost` I can't tell if the host is stopping due to an unhandled error. `IHostApplicationLifetime.ApplicationStopping` doesn't help...nothing to check in there.

**Comment by msschl** [comment]
I think an other BackgroundServiceExceptionBehavior value on the enum which sets an exit code on an unhandled error would be good. For Kubernetes when you use a dotnet worker as a cronjob the job is shown as completed with no failure although the background service might have failed.

**Comment by DamianEdwards** [comment]
Extension I put together just now for a template we're working on that ensures the app exits with a non-zero exit code if a `BackgroundService` faults:

```csharp
public static class HostExtensions
{
    public static async Task RunAndObserveBackgroundServices(this IHost host)
    {
        var backgroundServiceTasks = host.Services.GetServices<IHostedService>()
            .OfType<BackgroundService>().Select(s => s.ExecuteTask);

        await host.RunAsync();

        if (backgroundServiceTasks.Any(t => t?.IsFaulted == true))
        {
            // If a BackgroundService failed, set the exit code to -1.
            Environment.ExitCode = -1;
        }
    }
}
```

Simply call this method instead of `RunAsync()`/`Run()` from your `Program.Main`.

Given the impact of the current behavior in environments like Kubernetes, Azure Container Apps, Aspire, etc., I think we should prioritize improving this behavior in the runtime. As @msschl suggest, we should add a new value to `BackgroundServiceExceptionBehavior` (e.g. `StopHostAndSetExitNonZeroCode`, aka my best name suggestion ever) in .NET 10. We should also consider servicing .NET 8 and .NET 9 to enable this behavior via an app context switch (i.e. quirk it) so that folks can get the benefit of this change without having to wait for .NET 10.

**Comment by lvde0** [comment]
Yes, this should be higher priority. The [official example for applying EF Core migrations in Aspire](https://learn.microsoft.com/en-us/dotnet/aspire/database/ef-core-migrations) is currently not working correctly when migration fails. All dependent services are still started despite the migration failure.

**Comment by delreluca** [comment]
In addition I’ve noticed that this also breaks the exit code of Windows services when using `WindowsServiceLifetime` [(from the official package)](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices).

A Windows service has its own exit code which is controlled via `WindowsServiceLifetime.ExitCode`. However for it to be communicated back properly it has to be set before stop or shutdown. But the `StopHost` behaviour immediately shuts down, so something like

```cs
var lifetime = host.Services.GetService<IHostLifetime>();

await host.RunAsync();

if (backgroundServiceTasks.Any(t => t?.IsFaulted == true))
{
    // If a BackgroundService failed, set the exit code to -1.
    Environment.ExitCode = -1;

    if (lifetime is WindowsServiceLifetime svc) svc.ExitCode = Environment.ExitCode;
}
```

will be too late, it seems.

This affects [service recovery](https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service#configure-the-windows-service) (but note that these docs forget to tell you to set `sc failureflag serviceName 1` which will enable recovery when the service stops with an exit code, slight oversight).

Note that `WindowsServiceLifetime` doesn’t consider `Environment.ExitCode` at all, which would make for a good fallback and also work well with the proposed new `StopHostAndSetExitNonZeroCode` idea.

(The linked docs are not wrong per se, since they suggest to add a `try`/`catch` to each background service and call `Environment.Exit(1)`. An `Exit(1)` will of course terminate the process immediately which will leave the service in an unstopped state and thus still register as a failure even without the appropriate `failureflag` settings. However, immediately terminating is not always a good idea, for example my `host.Run()` is wrapped in a `try`/`finally` for log flushing.)

**Comment by Vandersteen** [comment]
In our case a background service was not a requirement, as we have a separate project that handles migrations / ...
This is how we solved it.
You can extend this how you want and have full control of the exit code

```csharp
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace UpgradeDb
{
    public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            try
            {
                using var host = CreateWebHostBuilder(args).Build();
                using var scope = host.Services.CreateScope();

                var upgradeDbService = scope.ServiceProvider.GetRequiredService<UpgradeDbService>();

                await upgradeDbService.ExecuteAsync();

                return 0;
            }
            catch (Exception e)
            {
                Console.WriteLine($"Host terminated unexpectedly!{Environment.NewLine}{e}");
                return 1;
            }
        }

        private static IHostBuilder CreateWebHostBuilder(string[] args)
        {
            var builder = Host.CreateDefaultBuilder(args)
                .ConfigureServices((context, services) =>
                {
                    services.AddDbContext<DbContext>((provider, builder) =>
                    {

                        builder.UseSqlServer(readonlyConnectionString, b =>
                        {
                            ...
                        });
                    });

                    services.AddSingleton<UpgradeDbService>();
                });

            return builder;
        }
    }

    public class UpgradeDbService
    {
        private readonly DbContext _dbContext;

        public UpgradeDbService(DbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task ExecuteAsync()
        {
            await _dbContext.MigrateAsync();
            //other migration logic if needed
        }
    }
}
```

**Comment by msschl** [comment]
@DamianEdwards 

```diff
namespace Microsoft.Extensions.Hosting;

public enum BackgroundServiceExceptionBehavior
{
+ StopHostWithNonZeroExitCode
}
```

**Comment by plachor** [comment]
It would be a good option to re-throw and let owning process to decide how to handle / translate that exception as in my case I would like to distinguish OOMs from rest of unhandled exceptions in order to be able to bump resources temporarily for a given service as I do in case of regular OMMKills. But now when it is framework that handles OOM within background service rather than kernel I end with exit code == 0. It will be soon 2026 🎆 are there any plans to improve this behavior @davidfowl ?
