### ISSUE TITLE
`System.Net.Http.Functional.Tests` failures on `coreclr windows x64 Debug`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#67164]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1682418&view=logs&jobId=55b384d0-d6b0-5894-fd8a-d754d713246e&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67017-merge-bc83fc42286c45ae86/System.Net.Http.Functional.Tests/1/console.a9f92371.log?sv=2019-07-07&se=2022-04-14T19%3A25%3A21Z&sr=c&sp=rl&sig=hMFplazVsiJ87mZ7RISQCXkAIKisaxOpgDmpAmNAW6Q%3D):

```
    System.Net.Http.Functional.Tests.Http1SingleChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: SyncSpan, useSsl: True) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/ResponseStreamZeroByteReadTests.cs(117,0): at System.Net.Http.Functional.Tests.Http1ResponseStreamZeroByteReadTestBase.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(ReadWriteMode readMode, Boolean useSsl)
        --- End of stack trace from previous location ---
```

```
    System.Net.Http.Functional.Tests.SocksProxyTest_Http1_Async.TestLoopbackAsync(scheme: "socks4", useSsl: True, useAuth: True, host: "localhost") [FAIL]
      System.AggregateException : One or more errors occurred. (Early EOF)
      ---- System.Exception : Early EOF
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/LoopbackSocksServer.cs(325,0): at System.Net.Http.Functional.Tests.LoopbackSocksServer.DisposeAsync()
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocksProxyTest.cs(58,0): at System.Net.Http.Functional.Tests.SocksProxyTest.<>c__DisplayClass3_0.<<TestLoopbackAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(38,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(101,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocksProxyTest.cs(37,0): at System.Net.Http.Functional.Tests.SocksProxyTest.TestLoopbackAsync(String scheme, Boolean useSsl, Boolean useAuth, String host)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/LoopbackSocksServer.cs(77,0): at System.Net.Http.Functional.Tests.LoopbackSocksServer.ProcessRequest(Socket clientSocket, NetworkStream ns)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/LoopbackSocksServer.cs(55,0): at System.Net.Http.Functional.Tests.LoopbackSocksServer.<>c__DisplayClass8_0.<<-ctor>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/LoopbackSocksServer.cs(315,0): at System.Net.Http.Functional.Tests.LoopbackSocksServer.DisposeAsync()
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: Close
  Date: Fri, 25 Mar 2022 19:54:58 GMT
  Content-Length: 0
}
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: Close
  Date: Fri, 25 Mar 2022 19:54:58 GMT
  Content-Length: 0
}
```

**Comment by karelz** [comment]
Triage: If it failed on rerun, we should keep it open. @rzikm can oyu please check?

**Comment by rzikm** [comment]
I can't find any information about retries in the job log or in the test reports. Strangely, it is reported as failure of the job itself, not individual tests (https://dev.azure.com/dnceng/public/_build/results?buildId=1682418&view=ms.vss-test-web.build-test-results-tab&runId=46071392&resultId=198765&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab), so it does not even show in the CI TestResults DB queries. I think that is because the entire job timed out.

I think this is just something environmental, so I will close this issue, we can reopen it if it happens more frequently.
