### ISSUE TITLE
Test failure XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67218]
Run: [runtime-coreclr libraries-jitstressregs 20220327.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1684241&view=ms.vss-test-web.build-test-results-tab&runId=46094000&resultId=181794&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs1-Windows.10.Arm64v8.Open

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs1-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs8-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray
```
**Error message:**
```
System.InvalidOperationException : There is an error in XML document (1, 176).
---- System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 487
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 419
   at XmlSerializerTests.RoundTripWithXmlMembersMapping(Object[] value, String baseline, Boolean skipStringCompare, XmlReflectionMember[] members, String ns, String wrapperName, Boolean rpc) in /_/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.cs:line 2043
   at XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier() in /_/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.RuntimeOnly.cs:line 2438
----- Inner Stack Trace -----
   at System.Array.GetLowerBound(Int32 dimension)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read2_wrapper()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 472
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20220403.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1697345&view=ms.vss-test-web.build-test-results-tab&runId=46297946&paneView=debug&resultId=182901)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs1-Windows.10.Arm64v8.Open

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs1-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs8-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray
```
**Error message:**
```
System.InvalidOperationException : There is an error in XML document (1, 176).
---- System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 487
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 419
   at XmlSerializerTests.RoundTripWithXmlMembersMapping(Object[] value, String baseline, Boolean skipStringCompare, XmlReflectionMember[] members, String ns, String wrapperName, Boolean rpc) in /_/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.cs:line 2043
   at XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier() in /_/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.RuntimeOnly.cs:line 2438
----- Inner Stack Trace -----
   at System.Array.GetLowerBound(Int32 dimension)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read2_wrapper()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 472
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20220417.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1722501&view=ms.vss-test-web.build-test-results-tab&runId=46744856&paneView=debug&resultId=190976)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs1-Windows.10.Arm64v8.Open

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs8-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstressregs1-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier
- XmlSerializerTests.XmlMembersMapping_IntArray

```
**Error message:**
```
System.InvalidOperationException : There is an error in XML document (1, 176).
---- System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 487
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 419
   at XmlSerializerTests.RoundTripWithXmlMembersMapping(Object[] value, String baseline, Boolean skipStringCompare, XmlReflectionMember[] members, String ns, String wrapperName, Boolean rpc) in /_/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.cs:line 2043
   at XmlSerializerTests.XmlMembersMapping_With_ChoiceIdentifier() in /_/src/libraries/System.Private.Xml/tests/XmlSerializer/XmlSerializerTests.RuntimeOnly.cs:line 2438
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 379
----- Inner Stack Trace -----
   at System.Array.GetLowerBound(Int32 dimension) in /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs:line 307
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length) in /_/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs:line 51
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read2_wrapper()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) in /_/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs:line 472
```

**Comment by StephenMolloy** [comment]
We haven't changed anything in this area (sgen) for quite a while, and this seems to only have popped up in recent months. This doesn't seem likely to be an SGen bug. Probably a JIT bug? I don't think we have the ability to create a corrupt array such that it would be able to get into Array.GetLowerBound() on our own.

**Comment by StephenMolloy** [comment]
Looks like this has been passing for a while now. Just a small blip - unrelated to any serializer changes. As posited above, this was probably a JIT issue. And probably fixed since it doesn't fail anymore.
