### ISSUE TITLE
The converter 'EnumConverter' is not compatible with the type 'System.Nullable`1[FooType]'.

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#67228]
### Description

Unhandled exception. System.InvalidOperationException: The converter 'EnumConverter' is not compatible with the type 'System.Nullable`1[FooType]'.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationConverterNotCompatible(Type converterType, Type type)
   at System.Text.Json.JsonSerializerOptions.GetConverterInternal(Type typeToConvert)
   at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Boolean isVirtual, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Boolean isVirtual, Nullable`1 typeNumberHandling, Boolean& propertyOrderSpecified, Dictionary`2& ignoredMembers)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type type, JsonConverter converter, Type runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type type)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)

### Reproduction Steps

```
using System.Text.Json;
using System.Text.Json.Serialization;

public static class Program
{
    public static void Main()
    {
        var jsonSerializerOptions = new JsonSerializerOptions();
        jsonSerializerOptions.Converters.Add(new EnumConverter());

        var foo = new Foo
        {
            TypeProperty = FooType.Off,
            NullableTypeProperty = FooType.On
        };
        var fooJson = JsonSerializer.Serialize(foo, jsonSerializerOptions);
        foo = JsonSerializer.Deserialize<Foo>(fooJson, jsonSerializerOptions);
    }
}

public enum FooType
{
    Off,

    On
}

public class Foo
{
    public FooType TypeProperty { get; set; }

    public FooType? NullableTypeProperty { get; set; }
}


public class EnumConverter : JsonConverter<Enum>
{
    public override bool CanConvert(Type typeToConvert)
        => typeToConvert.IsEnum || (typeToConvert.GenericTypeArguments.Length >= 1 && typeToConvert.GenericTypeArguments[0].IsEnum);

    public override Enum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var str = reader.GetString();

        return string.IsNullOrEmpty(str) || !Enum.TryParse(typeToConvert, str, out var result) ? null : (Enum)result!;
    }

    public override void Write(Utf8JsonWriter writer, Enum value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.ToString());
}

```

### Expected behavior

work fine

### Actual behavior

throw exception

### Configuration

.Net Version: net 6.0

**Comment by eiriktsarpalis** [comment]
This is by design -- You can't have a converter that is both of type `JsonConverter<FooType>` and `JsonConverter<FooType?>`. When writing custom converters for enum types you don't need to take nullable types into account, the default nullable converter will wrap around your custom converter. In other words changing your converter to the following:
```C#
public class EnumConverter : JsonConverter<FooType>
{
    public override bool CanConvert(Type typeToConvert) => typeof(FooType) == typeToConvert;

    public override FooType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var str = reader.GetString();

        return string.IsNullOrEmpty(str) || !FooType.TryParse(typeToConvert, str, out var result) ? default : (FooType)result!;
    }

    public override void Write(Utf8JsonWriter writer, FooType value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.ToString());
}
```
Should have the expected behaviour.
