### ISSUE TITLE
Wasm: FS is not defined on .NET 7 Preview 2

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [dotnet/runtime#67290]
### Description

Directed here by [Steve Sanderson](https://github.com/dotnet/aspnetcore/issues/39825#issuecomment-1076256239).

### Reproduction Steps

1. Create a .NET 6.0 Blazor Wasm project by running `dotnet new blazorwasm -f net6.0`
2. Create a .NET 7.0 Blazor Wasm project by running `dotnet new blazorwasm`
3. For both projects, add the following code to `Index.razor`:

```
@code
{
    [Inject]
    private IJSRuntime _js { get; set; }

    protected override async Task OnInitializedAsync()
    {
        var module = await _js.InvokeAsync<IJSObjectReference>("import", "./fs.js");
        await module.InvokeVoidAsync("fs");
    }
}
```

4. For both projects, create a new file `fs.js` in `wwwroot` and add the following code:

```
export function fs() {
    FS.analyzePath("dummy").exists;
}
```

### Expected behavior

No errors thrown for both projects

### Actual behavior

The project on .NET 7.0 throws the following error:

```
blazor.webassembly.js:1 
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: FS is not defined
      ReferenceError: FS is not defined
          at Module.fs (http://localhost:5236/fs.js:2:5)
          at http://localhost:5236/_framework/blazor.webassembly.js:1:3334
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (http://localhost:5236/_framework/blazor.webassembly.js:1:3308)
          at Object.kt [as invokeJSFromDotNet] (http://localhost:5236/_framework/blazor.webassembly.js:1:59840)
          at Object.mono_wasm_invoke_js_blazor (http://localhost:5236/_framework/dotnet.7.0.0-preview.2.22152.2.36b1887bg5.js:3:53168)
          at _mono_wasm_invoke_js_blazor (http://localhost:5236/_framework/dotnet.7.0.0-preview.2.22152.2.36b1887bg5.js:13:111972)
          at http://localhost:5236/_framework/dotnet.wasm:wasm-function[266]:0x1b79c
          at http://localhost:5236/_framework/dotnet.wasm:wasm-function[237]:0x1ad97
          at http://localhost:5236/_framework/dotnet.wasm:wasm-function[177]:0xce51
Microsoft.JSInterop.JSException: FS is not defined
ReferenceError: FS is not defined
    at Module.fs (http://localhost:5236/fs.js:2:5)
    at http://localhost:5236/_framework/blazor.webassembly.js:1:3334
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (http://localhost:5236/_framework/blazor.webassembly.js:1:3308)
    at Object.kt [as invokeJSFromDotNet] (http://localhost:5236/_framework/blazor.webassembly.js:1:59840)
    at Object.mono_wasm_invoke_js_blazor (http://localhost:5236/_framework/dotnet.7.0.0-preview.2.22152.2.36b1887bg5.js:3:53168)
    at _mono_wasm_invoke_js_blazor (http://localhost:5236/_framework/dotnet.7.0.0-preview.2.22152.2.36b1887bg5.js:13:111972)
    at http://localhost:5236/_framework/dotnet.wasm:wasm-function[266]:0x1b79c
    at http://localhost:5236/_framework/dotnet.wasm:wasm-function[237]:0x1ad97
    at http://localhost:5236/_framework/dotnet.wasm:wasm-function[177]:0xce51
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at FsRepo.Pages.Index.OnInitializedAsync() in C:\Users\zhiyu\Downloads\FsRepo\Pages\Index.razor:line 19
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Regression?

.NET 6

**Comment by lewing** [comment]
Your specific issue is probably fixed by https://github.com/dotnet/runtime/pull/66868 

cc @pavelsavara

**Comment by Zhiyuan-Amos** [comment]
Hello @lewing, just fyi, I am still able to reproduce this issue on .NET 7 Preview 3.

**Comment by pavelsavara** [comment]
The dotnet wasm runtime does not spill it's guts to global namespace in Net 7.0. 
But blazor still does publish it as `window.Module`.
Instead of `FS.analyzePath` try `window.Module.FS.analyzePath` see if that helps you.

**Comment by Zhiyuan-Amos** [comment]
@pavelsavara that works, thank you!
