### ISSUE TITLE
System.Drawing.Tests failing on Windows 10 Arm64 with OS apparently doubling DPI of bitmaps/icons

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67320]
Run: [runtime-coreclr libraries-jitstress 20220329.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1687534&view=ms.vss-test-web.build-test-results-tab&runId=46142258&resultId=127978&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Drawing.Tests.IconTests.ExtractAssociatedIcon_UNCFilePath_Success
- MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap48Features
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format64bppPArgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format64bppArgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format48bppRgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format32bppRgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format32bppPArgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format32bppArgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format24bppRgb)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format16bppRgb565)
- System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format16bppRgb555)
- System.Drawing.Tests.IconTests.Ctor_Icon_Width_Height(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_Stream_Size(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_Icon_Size(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_FilePath_Width_Height(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_FilePath_Size(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_Stream_Width_Height(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.GraphicsTests.GetHdc_FromHdc_Roundtrips
- System.ComponentModel.TypeConverterTests.ImageConverterTest.ImageConverterFromIconTest(name: \"pngwithheight_icon.ico\")
- System.ComponentModel.TypeConverterTests.ImageConverterTest.ImageConverterFromIconTest(name: \"256x256_seven_entries_multiple_bits.ico\")
- System.ComponentModel.TypeConverterTests.ImageConverterTest.ImageConverterFromIconTest(name: \"48x48_multiple_entries_4bit.ico\")
- MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap96Features
- MonoTests.System.Drawing.Imaging.IconCodecTest.Xp32bppIconFeatures
- System.Drawing.Tests.IconTests.Clone_ConstructedIcon_Success
- System.Drawing.Tests.IconTests.Ctor_FilePath(name: \"pngwithheight_icon.ico\")
- System.Drawing.Tests.IconTests.Ctor_FilePath(name: \"256x256_seven_entries_multiple_bits.ico\")
- System.Drawing.Tests.IconTests.Ctor_FilePath(name: \"48x48_multiple_entries_4bit.ico\")
- System.Drawing.Tests.IconTests.ExtractAssociatedIcon_FilePath_Success
- MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap16Features
- MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap32Features
- MonoTests.System.Drawing.Imaging.IconCodecTest.Bitmap64Features
- System.Drawing.Tests.IconTests.Ctor_Type_Resource
- System.Drawing.Tests.IconTests.Ctor_Stream
```
**One of error message:**
```
Assert.Equal() Failure
Expected: 32
Actual:   64


Stack trace
   at System.Drawing.Tests.IconTests.ExtractAssociatedIcon_FilePath_Success_Helper(String filePath) in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 416
   at System.Drawing.Tests.IconTests.ExtractAssociatedIcon_UNCFilePath_Success() in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 409
```
Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"bitmap_173x183_indexed_8bit.bmp\", width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"bitmap_173x183_indexed_8bit\", width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"48x48_multiple_entries_4bit.ico\", width: 16, height: 16)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"48x48_multiple_entries_4bit\", width: 16, height: 16)
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: TileFlipY, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: TileFlipXY, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: TileFlipX, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: Tile, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: Clamp, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Bitmap(bitmap: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.ToolboxBitmapAttributeTests.GetImage_Component_ReturnsExpected
- System.Drawing.Tests.ToolboxBitmapAttributeTests.GetImage_NoExtension(type: typeof(System.Drawing.Tests.Icon_toolboxBitmapAttributeTest), width: 256, height: 256)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type(type: typeof(System.Drawing.Tests.bitmap_173x183_indexed_8bit), width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_FileName(fileName: \"D:\\\\h\\\\w\\\\B6810A3D\\\\w\\\\AA5809DA\\\\e\\\\bitmaps\\\\48x48\"..., size: {Width=16, Height=16})
- System.Drawing.Tests.ToolboxBitmapAttributeTests.GetImage_TypeFileNameBool_ReturnsExpected(fileName: \"48x48_multiple_entries_4bit.ico\", width: 16, height: 16)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.GetImage_TypeFileNameBool_ReturnsExpected(fileName: \"bitmap_173x183_indexed_8bit.bmp\", width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.GetImage_Default_ReturnsExpected
```
**One of error message:**
```
Assert.Equal() Failure
Expected: {Width=173, Height=183}
Actual:   {Width=346, Height=366}


Stack trace
   at System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(Type type, String fileName, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/tests/ToolboxBitmapAttributeTests.cs:line 115
```
Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Point

```
**One of error message:**
```
Assert.Equal() Failure
↓ (pos 0)
Expected: [164, 185, 115, 185, 111, ...]
Actual:   [216, 50, 225, 134, 32, ...]
↑ (pos 0)


Stack trace
   at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash) in /_/src/libraries/System.Drawing.Common/tests/DrawingTest.cs:line 21
   at System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Point() in /_/src/libraries/System.Drawing.Common/tests/Graphics_DrawBezierTests.cs:line 19
```
Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault)
- System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 10, gdiVerticalFont: False, expectedNamePrefix: \"\", expectedWeight: 400)
- System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Regular, gdiCharSet: 0, gdiVerticalFont: False, expectedNamePrefix: \"\", expectedWeight: 400)
- System.Drawing.Tests.FontTests.ToLogFont_Invoke_ReturnsExpected(fontStyle: Bold | Italic | Strikeout, gdiCharSet: 255, gdiVerticalFont: True, expectedNamePrefix: \"@\", expectedWeight: 700)
```
**One of error message:**
```
Assert.Equal() Failure
Expected: -13
Actual:   -27


Stack trace
   at System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(TextRenderingHint textRenderingHint) in /_/src/libraries/System.Drawing.Common/tests/FontTests.cs:line 832
```

**Comment by danmoseley** [comment]
some more examples
```
    System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format32bppRgb) [FAIL]
      Assert.Equal() Failure
      Expected: 96
      Actual:   192
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/GraphicsTests.cs(3278,0): at System.Drawing.Tests.GraphicsTests.VerifyGraphics(Graphics graphics, RectangleF expectedVisibleClipBounds)
        /_/src/libraries/System.Drawing.Common/tests/GraphicsTests.cs(313,0): at System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(PixelFormat format)
    System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(format: Format48bppRgb) [FAIL]
      Assert.Equal() Failure
      Expected: 96
      Actual:   192
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/GraphicsTests.cs(3278,0): at System.Drawing.Tests.GraphicsTests.VerifyGraphics(Graphics graphics, RectangleF expectedVisibleClipBounds)
        /_/src/libraries/System.Drawing.Common/tests/GraphicsTests.cs(313,0): at System.Drawing.Tests.GraphicsTests.FromImage_Bitmap_Success(PixelFormat format)
```

It's only happened twice (the last two runs?) 

<HTML><HEAD></HEAD><BODY>

Pipeline | Pipeline_Configuration | OS | Arch | Result | Finished
-- | -- | -- | -- | -- | --
runtime-coreclr libraries-pgo | Release | windows.10.arm64v8.open | arm64 | Fail | 2022-03-26 19:09:39.2020000
runtime-coreclr libraries-jitstress | Release | windows.10.arm64v8.open | arm64 | Fail | 2022-03-29 09:26:03.9400000


</BODY></HTML>

@dotnet/dnceng windows.10.arm64v8.open queue image change recently?

**Comment by lpatalas** [comment]
> dotnet/dnceng windows.10.arm64v8.open queue image change recently?

I don't think there was any change but I will try to double check.

**Comment by VincentBu** [comment]
Failed again in:[ runtime-coreclr libraries-jitstress 20220613.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1820821&view=ms.vss-test-web.build-test-results-tab&runId=48304414&resultId=116845&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open

- System.Drawing.Tests.IconTests.ExtractAssociatedIcon_UNCFilePath_Success
- System.Drawing.Tests.GraphicsTests.GetHdc_FromHdc_Roundtrips
- System.Drawing.Tests.IconTests.Ctor_Icon_Size(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_Icon_Width_Height(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_Stream_Width_Height(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: ClearTypeGridFit)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixelGridFit)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SingleBitPerPixel)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAliasGridFit)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: AntiAlias)
- System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected(textRenderingHint: SystemDefault)
- System.Drawing.Tests.IconTests.Ctor_Stream_Size(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
- System.Drawing.Tests.IconTests.Ctor_FilePath_Size(fileName: \"256x256_seven_entries_multiple_bits.ico\", size: {Width=0, Height=0}, expectedSize: {Width=32, Height=32})
```
**Error message:**
```
Assert.Equal() Failure
Expected: 32
Actual:   64


Stack trace
   at System.Drawing.Tests.IconTests.ExtractAssociatedIcon_FilePath_Success_Helper(String filePath) in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 400
   at System.Drawing.Tests.IconTests.ExtractAssociatedIcon_UNCFilePath_Success() in /_/src/libraries/System.Drawing.Common/tests/IconTests.cs:line 393
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```
Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open

- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"bitmap_173x183_indexed_8bit.bmp\", width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"bitmap_173x183_indexed_8bit\", width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"48x48_multiple_entries_4bit.ico\", width: 16, height: 16)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(type: typeof(System.Drawing.Tests.ToolboxBitmapAttributeTests), fileName: \"48x48_multiple_entries_4bit\", width: 16, height: 16)
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: TileFlipY, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: TileFlipXY, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: TileFlipX, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: Tile, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.TextureBrushTests.Ctor_Image_WrapMode(image: Metafile { Flags = 327683, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 4127, HorizontalResolution = 606, Palette = (throws ExternalException), ... }, wrapMode: Clamp, expectedPixelFormat: Format32bppArgb, expectedSize: {Width=490, Height=654})
- System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type(type: typeof(System.Drawing.Tests.bitmap_173x183_indexed_8bit), width: 173, height: 183)
- System.Drawing.Tests.ToolboxBitmapAttributeTests.GetImage_NoExtension(type: typeof(System.Drawing.Tests.Icon_toolboxBitmapAttributeTest), width: 256, height: 256)

```
**Error message:**
```
Assert.Equal() Failure
Expected: {Width=173, Height=183}
Actual:   {Width=346, Height=366}


Stack trace
   at System.Drawing.Tests.ToolboxBitmapAttributeTests.Ctor_Type_String(Type type, String fileName, Int32 width, Int32 height) in /_/src/libraries/System.Drawing.Common/tests/ToolboxBitmapAttributeTests.cs:line 112
   at InvokeStub_ToolboxBitmapAttributeTests.Ctor_Type_String(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open

- System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Point

```
**Error message:**
```
Assert.Equal() Failure
↓ (pos 0)
Expected: [164, 185, 115, 185, 111, ...]
Actual:   [216, 50, 225, 134, 32, ...]
↑ (pos 0)


Stack trace
   at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash) in /_/src/libraries/System.Drawing.Common/tests/DrawingTest.cs:line 21
   at System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Point() in /_/src/libraries/System.Drawing.Common/tests/Graphics_DrawBezierTests.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by MattGal** [comment]
I can't check the March 30th machine; it'd have rebooted many times since then.  However, checking out the machine this ran on via KVM, I saw total video corruption with just a mouse and some redrawing artifacts, which rebooted after clicking around in the black for a bit:
![image](https://user-images.githubusercontent.com/7862010/173618133-eb4a99f7-dafb-46a5-81a8-7cbce904e60b.png)

Given this, and the fact the test passes quite regularly on the same queue with the same machines, I'd wager there's some kind of GPU driver bug with the integrated GPU on these devices (unlikely to be fixed).   Best we can probably do here is detect the problem and ask for reboots (either on the FR channel or via the reboot request API) when it happens.

**Comment by danmoseley** [comment]
@MattGal perhaps there's an updated driver (eg from GPU vendor) that we can ask them to update the images with?

**Comment by MattGal** [comment]
> @MattGal perhaps there's an updated driver (eg from GPU vendor) that we can ask them to update the images with?

Unfortunately not.  Qualcomm does not distribute the drivers rather  letting OEMs do so and even sketchy download sites only have the ones from May 2019 which are already on the machine.  We just need to get some Azure ARM64 capacity and start running these machines as VMs, there's not going to be a GPU update likely ever again for the Adreno 630 given there were none in the past 3 years.

**Comment by ViktorHofer** [comment]
Triage: Closing until we see this happening again. Presumably a machine problem. If this happens again, we should hold the machine.
