### ISSUE TITLE
CreateXHarnessAppleWorkItems task failed unexpectedly when building iOS arm64 AllSubsets_Mono

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#67349]
Rolling Build failed this morning on the `Build iOS arm64 Release AllSubsets_Mono` job at the Send to Helix step, with a problem when trying to use the tool `microsoft.dotnet.xharness.cli` to run the `CreateXHarnessAppleWorkItems` task. The issue seems to be just a failure in the SSL handshake communication. To view more details, you can get to the log of the failing build [here](https://dev.azure.com/dnceng/public/_build/results?buildId=1689969&view=logs&j=a5078f86-b345-5a4a-85ee-f64916152c6f&t=b1d0531b-2b6c-5e64-cc59-e2e1ffcc72bf).

For convenience, I'm pasting the stack trace of the failure below:
```
##[error].packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22171.2/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018: The "CreateXHarnessAppleWorkItems" task failed unexpectedly.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.<>c__DisplayClass14_0.<<DownloadProvisioningProfile>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 190
--- End of stack trace from previous location ---
   at Microsoft.Arcade.Common.Helpers.<>c__DisplayClass7_0.<DirectoryMutexExec>b__0() in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 71
   at Microsoft.Arcade.Common.Helpers.MutexExec[T](Func`1 function, String mutexName) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 45
   at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec[T](Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 64
   at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec(Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 71
   at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.DownloadProvisioningProfile(ApplePlatform platform) in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 179
   at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.AddProfileToPayload(String archivePath, String testTarget) in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 99
   at Microsoft.DotNet.Helix.Sdk.CreateXHarnessAppleWorkItems.PrepareWorkItem(IZipArchiveManager zipArchiveManager, IFileSystem fileSystem, IProvisioningProfileProvider provisioningProfileProvider, ITaskItem appBundleItem) in /_/src/Microsoft.DotNet.Helix/Sdk/CreateXHarnessAppleWorkItems.cs:line 189
   at Microsoft.DotNet.Helix.Sdk.CreateXHarnessAppleWorkItems.ExecuteTask(IProvisioningProfileProvider provisioningProfileProvider, IZipArchiveManager zipArchiveManager, IFileSystem fileSystem) in /_/src/Microsoft.DotNet.Helix/Sdk/CreateXHarnessAppleWorkItems.cs:line 81
```

@radical do you mind tagging the right people that should be looking into this?

**Comment by steveisok** [comment]
@premun looks like there might be a problem trying to grab the provisioning profile.

**Comment by premun** [comment]
I guess this is a fluke? Or possibly something to do with the TLS 1.2 changes happening all around, maybe the agent didn't have this enabled somehow?

I tried to run this again and seems to work but I will add retries: https://github.com/dotnet/arcade/issues/8703

**Comment by joperezr** [comment]
This doesn't seem fixed, it failed again in today's build: https://dev.azure.com/dnceng/public/_build/results?buildId=1694490&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d

It does seem flaky as we have had successful builds in between the two with the failure, but it does indeed happen some times so should be investigated as it is now twice this week where this is the only error keeping the rolling build from being green.

**Comment by premun** [comment]
I am prioritizing dotnet/arcade#8703 and will have a look. There was no code change in that area for many months so it might be actually related to TLS (for which retries won't help, I am afraid). But I will see what can be done.

**Comment by premun** [comment]
@wfurt @bartonjs do you think this is an intermittent issue that will be resolved by retries or will it fail because of some OS state?

**Comment by bartonjs** [comment]
RevocationStatusUnknown means one of

* The root certificate of the remote party could not be determined (should also say PartialChain)
* The root certificate of the remote party was not trusted (should also say UnknownRootAuthority)
* The client is running .NET 7 Preview 3 on Linux and some cert in the chain is expired (should also say NotTimeValid)
* The cached revocation data didn't exist or was expired and new data couldn't be obtained:
  * Firewall prevented the connection
  * The revocation data host was down
  * Timeout
  * No available client sockets
  * Any other kind of networking problem

Since no other status code was reported (or the exception only prints one) it sounds like just intermittency (unless it's a firewall configuration problem).  But for a revocation host problem it may take longer to recover than "try three times".

**Comment by carlossanlop** [comment]
Happened again in today's rolling build: https://dev.azure.com/dnceng/public/_build/results?buildId=1702530&view=results
Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1702530&view=logs&j=a5078f86-b345-5a4a-85ee-f64916152c6f&t=b1d0531b-2b6c-5e64-cc59-e2e1ffcc72bf&l=76
Callstack:
```
Tool 'microsoft.dotnet.xharness.cli' (version '1.0.0-prerelease.22180.1') was successfully installed.
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018: The "CreateXHarnessAppleWorkItems" task failed unexpectedly. [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    --- End of inner exception stack trace --- [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.<>c__DisplayClass14_0.<<DownloadProvisioningProfile>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 190 [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018: --- End of stack trace from previous location --- [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at Microsoft.Arcade.Common.Helpers.<>c__DisplayClass7_0.<DirectoryMutexExec>b__0() in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 71 [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at Microsoft.Arcade.Common.Helpers.MutexExec[T](Func`1 function, String mutexName) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 45 [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec[T](Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 64 [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec(Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 71 [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
/Users/runner/work/1/s/.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018:    at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.DownloadProvisioningProfile(ApplePlatform platform) in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 179 [/Users/runner/work/1/s/src/libraries/sendtohelixhelp.proj]
```

**Comment by premun** [comment]
Probably will keep happening before we merge the fix and flow Arcade to runtime

**Comment by premun** [comment]
@carlossanlop please note that the fix has already been merged into Arcade, however Arcade hasn't been promoted for well over a week because runtime has problem with ingestion of it. This is probably something to look into for the @dotnet/runtime-infrastructure team?

https://dnceng.visualstudio.com/internal/_build/results?buildId=1706764&view=results

**Comment by carlossanlop** [comment]
@hoyosjs please let me know when we update the arcade dependency in runtime so we consume this fix and close this issue.

**Comment by agocke** [comment]
@premun Is there any way to bring in a fix for this without updating the version of the SDK we use in runtime? That's a big task and might take us some time

**Comment by premun** [comment]
@agocke I'm not sure but this SSL error is a transient occasional error which is probably not blocking anything so I am not sure whether it makes sense to try to somehow build some .NET 6 Arcade with it.

Do you have some ETA for the Arcade bump?

**Comment by lewing** [comment]
> 
> Do you have some ETA for the Arcade bump?

The work is happening here https://github.com/dotnet/runtime/pull/67771

**Comment by carlossanlop** [comment]
Happened again on runtime rolling builds during the weekend:

- 04/09: https://dev.azure.com/dnceng/public/_build/results?buildId=1708699&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d&l=76
- 04/10:https://dev.azure.com/dnceng/public/_build/results?buildId=1709879&view=logs&j=a5078f86-b345-5a4a-85ee-f64916152c6f&t=b1d0531b-2b6c-5e64-cc59-e2e1ffcc72bf&l=76

**Comment by premun** [comment]
A fix was merged to main on April 21st and the issue hasn't happened since (on main):

I use this query to verify this:
```sql
TimelineIssues
| where Type == "error" and Message contains "CreateXHarnessAppleWorkItems"
| join kind=inner TimelineBuilds on BuildId
| where StartTime > now() - 7d
| order by StartTime desc
| project QueueTime, Project, Repository, Reason, BuildNumber, Definition, SourceBranch
```

We can give it a few more days and check again but it seems like the fix is helping.

**Comment by premun** [comment]
There were no occurrences in the last 6 days so feels like the fix helped. I think we can close this @joperezr
