### ISSUE TITLE
Test failure DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67410]
Run: [runtime-coreclr libraries-jitstress 20220331.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1692176&view=ms.vss-test-web.build-test-results-tab&runId=46218400&paneView=debug&resultId=137066)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_checked-jitstress2_tiered-Ubuntu.1804.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

net7.0-windows-Release-x64-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

net7.0-Linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.1804.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

net7.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at DataContractSerializerTests.DCS_MyPersonSurrogate_Stress() in /_/src/libraries/System.Runtime.Serialization.Xml/tests/DataContractSerializerStressTests.cs:line 56
```

**Comment by AndyAyersMS** [comment]
Seems plausible this is OSR related as the test method contains a few loops.

But I can't repro this at c288acdb794b1f2edba90868a823b161d88bd2b0 so perhaps it's fixed by one of the OSR fixes I pushed yesterday? Going to try some older builds to see.

**Comment by AndyAyersMS** [comment]
Can repro on windows x64 at ade99ed7cb678abe93461906928f33d544e0debe.

Via `COMPlus_JitEnablePatchpointRange` isolation, the issue seems to be in
```
Compiling 4253 System.Runtime.Serialization.ReflectionReader::ReadCollectionItems, IL size = 262, hash=0x7b7b033c Tier1-OSR @0x65 JitStress
Compiling 4255 System.Runtime.Serialization.ReflectionReader::ReadCollectionItems, IL size = 262, hash=0x7b7b033c Tier1-OSR @0x65 JitStress
```

**Comment by AndyAyersMS** [comment]
JitStress=2 here forces a no-way fallback so we rejit the OSR method with minopts.
```
*** forcing no-way fallback -- current jit request will be abandoned ***
```
so presumably there's some bad interaction of minopts and OSR to sort out.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220410.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1709535&view=ms.vss-test-web.build-test-results-tab&runId=46505788&paneView=debug&resultId=137300)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

net7.0-Linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.1804.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

net7.0-Linux-Release-x64-CoreCLR_checked-jitstress2_tiered-Ubuntu.1804.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

net7.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at DataContractSerializerTests.DCS_MyPersonSurrogate_Stress() in /_/src/libraries/System.Runtime.Serialization.Xml/tests/DataContractSerializerStressTests.cs:line 56
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
```
