### ISSUE TITLE
JsonSerializer.Deserialize can't be reliably used with Utf8JsonReaders that have been resumed

### ISSUE THREAD

**Issue by AdamMil** [dotnet/runtime#67454]
### Description

System.Text.Json.Utf8JsonReader is supposed to be resumable, so that you can read data in chunks, resuming the reader after each chunk. However, the JsonSerializer.Deserialize(ref Utf8JsonReader, ...) methods do not work reliably with a reader that has been resumed at the beginning of an object or array to deserialize. (I haven't tested strings, numbers, etc.)

I believe this is because internally, JsonSerializer.Read\<T\>(ref Utf8JsonReader, JsonTypeInfo) tries to copy the entire object or array into a separate buffer, _including the initial '{' or '[' character which has already been consumed by the reader_, and then create a new reader to deserialize from that buffer. In the case of a reader that has been resumed at the StartObject or StartArray token, the '{' or '[' character will not exist - because it has already been consumed from the input stream. Really, I don't think JsonSerializer should be trying to look backwards, at data that has already been consumed from the input source. The reader is supposed to be forward-only.

### Reproduction Steps

Here is one way to cause the exception:
````C#
public class Foo { public int a { get; set; } }
var bytes = System.Text.Encoding.ASCII.GetBytes("{\"a\":7}").AsSpan();
var jr = new Utf8JsonReader(bytes[..1], false, new JsonReaderState());
var read = jr.Read(); // move to StartObject. consume '{'
jr = new Utf8JsonReader(bytes[(int)jr.BytesConsumed..], true, jr.CurrentState); // BytesConsumed is 1
var foo = JsonSerializer.Deserialize<Foo>(ref jr); // this fails
````

There are many other, similar patterns that all fail.

### Expected behavior

JsonSerializer should respect the forward-only nature of the reader and not try to look backwards at already-consumed data, so that it can work with readers that have been resumed. The resumability of Utf8JsonReader is a core part of its design.

More specifically, the Deserialize methods that take a Utf8JsonReader should work if the reader is resumed at the start of the value to deserialize.

It would also be nice if it didn't try to copy the entire object or array - which can be quite large - into a separate buffer and then deserialize it using a separate reader. Can't it just use the reader I give it?

### Actual behavior

It fails with an exception like the following:

````
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to Test.Program+Foo. Path: $ | LineNumber: 0 | BytePositionInLine: 3.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 55
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectDefaultConverter.cs:line 25
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 249
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 61
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs:line 23
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs:line 421
   at System.Text.Json.JsonSerializer.Deserialize[TValue](Utf8JsonReader& reader, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs:line 60
   at Test.Program.Main() in Program.cs:line 25

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(System.Type) in ThrowHelper.Serialization.cs
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in ObjectDefaultConverter.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in JsonConverterOfT.cs
    System.Text.Json.Serialization.JsonConverter<T>.ReadCore(ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack) in JsonConverterOfT.ReadCore.cs
    System.Text.Json.JsonSerializer.ReadCore<TValue>(System.Text.Json.Serialization.JsonConverter, ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack) in JsonSerializer.Read.Helpers.cs
    System.Text.Json.JsonSerializer.Read<TValue>(ref System.Text.Json.Utf8JsonReader, System.Text.Json.Serialization.Metadata.JsonTypeInfo) in JsonSerializer.Read.Utf8JsonReader.cs
    System.Text.Json.JsonSerializer.Deserialize<TValue>(ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions) in JsonSerializer.Read.Utf8JsonReader.cs
    Test.Program.Main() in Program.cs
````

### Regression?

I doubt it.

### Known Workarounds

Inserting an extra '{' or '[' byte into the reader's input stream (so there are effectively two such bytes) when resuming, and then using reflection to set Utf8JsonReader._consumed = 1, will allow deserialization to succeed. I don't consider this an actual workaround that I could use in real code, because it depends on reflection and internal implementation details, but it will avoid the exception. (Also, a Utf8JsonReader can't be boxed, so normal reflection methods don't work.)

````C#
public class Foo { public int a { get; set; } }
var bytes = System.Text.Encoding.ASCII.GetBytes("{\"a\":7}").AsSpan();
var jr = new Utf8JsonReader(bytes[..1], false, new JsonReaderState());
var read = jr.Read(); // move to StartObject. consume '{'
// put an extra '{' or '[' byte into the stream by subtracting one from BytesConsumed
jr = new Utf8JsonReader(bytes[((int)jr.BytesConsumed-1)..], true, jr.CurrentState);
jr._consumed = 1; // set this via reflection (e.g. using a dynamic method) or the debugger
var foo = JsonSerializer.Deserialize<Foo>(ref jr); // this succeeds with the above hack
````

### Configuration

.NET 6.0 on Windows 10 Enterprise x64

**Comment by eiriktsarpalis** [comment]
This is by design -- `Utf8JsonReader` might make it possible to make JSON reading resumable, but it doesn't contain the necessary state to resume _deserialization_. Deserialization state (the `ReadState` struct) is currently not exposed, but we are considering allowing user defined async/resumable converters in the future (see #63795).

**Comment by AdamMil** [comment]
> Utf8JsonReader might make it possible to make JSON reading resumable, but it doesn't contain the necessary state to resume deserialization.

I'm not referring to resuming deserialization or to user-defined resumable converters. Deserialization hasn't even begun yet. I'm referring to having a Utf8JsonReader positioned on a StartObject token with all of the data for the object available, and then passing it to Deserialize. It shouldn't make a difference whether the reader was resumed there or navigated there via Read.

**Comment by eiriktsarpalis** [comment]
Your initial analysis on the root cause appears to be correct. It is not entirely clear to me what the [historical reasons for copying the contents of the buffer](https://github.com/dotnet/runtime/blob/16b2cf5baa8c14650261f957d7ea31d4ae723561/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L384-L397) might be here. It doesn't seem necessary for either checkpointing or reading ahead (which already happens separately in the converter layer). @bartonjs or @ahsonkhan might have more context. 

Looking at our test coverage for the `Utf8JsonReader` Deserialize methods, I don't believe they were meant to support re-entrant reader instances. They are also not accounting for that case, producing misleading error messages when passing the fixed-up reader to the underlying converters. As part of https://github.com/dotnet/runtime/issues/63795 we'd be looking at exposing `JsonSerializer` methods that support re-entrancy at the serialization layer.

Out of curiosity, what use case triggered this issue for you? Have you tried using any of the streaming deserialization APIs, in particular the `DeserializeAsyncEnumerable` method?

**Comment by AdamMil** [comment]
Thank you for taking another look.

I'm not sure what you mean by "re-entrant" readers. Does that just mean one that's been resumed?

I think this case only affects readers that are resumed exactly at the StartObject or StartArray token, in which case the deserializer tries to look backwards one byte into the reader's internal buffer to capture the initial '{' or '[' delimiter. This byte has already been consumed, so it fails after resuming because it's no longer in the internal buffer. One way to fix it without significant changes to the code would be to simply insert the corresponding '{' or '[' byte into the buffer and then copy the rest of the data from the reader, rather than trying to look backwards one byte.

(Of course, my preference would be to avoid the TrySkip call and the copy into a separate buffer, and just deserialize the value using the reader I provide, but that may be more work.)

I hit this issue when implementing a class to allow reading from a stream with the Utf8JsonReader interface. The Deserialize methods that take a stream want to deserialize the entire stream into some object or value, but what I want is to be able to pick out individual objects from a stream and deserialize them one by one. For a simple example, let's say you have a stream like this:
````
[{"a":1}, {"a":2}]
````
If the stream is positioned at the first '{' character, i.e. at the {"a":1} object, the JsonSerializer.Deserialize method will throw an exception upon seeing the ',' character after it.

Now imagine that the {"a":1} object is much bigger and you have hundreds of thousands of them coming over a network stream. I'd prefer not to deserialize the whole stream into a giant list. This takes time since you have to wait for the entire network transfer before you can begin processing any items, and it also takes memory since you have to hold all the data in memory at once. I'd prefer to use a reader loop like:

````C#
while(reader.Read() && reader.TokenType != JsonTokenType.EndArray)
{
    processItem(JsonSerializer.Deserialize<MyItem>(ref reader, ...));
}
````

In my case it looks like:

````C#
while(streamReader.Read(ref reader) && reader.TokenType != JsonTokenType.EndArray)
{
    streamReader.EnsureComplete(ref reader);
    processItem(JsonSerializer.Deserialize<MyItem>(ref reader, ...));
}
````

That way, it's truly _streaming_ the data and processing it as it comes in.

The EnsureComplete method makes sure all the data for the item the reader is currently positioned at is available to be read by the reader. This may require saving the reader state, reading more data, and resuming the reader based on the saved state. Since in my case the reader is always positioned on something like a StartObject token when I call EnsureComplete, it always gets resumed at the StartObject token and fails to deserialize.

**Comment by eiriktsarpalis** [comment]
> I'm not sure what you mean by "re-entrant" readers. Does that just mean one that's been resumed?

In this context it means passing on the `JsonReaderState` token across multiple buffer chunks.

> (Of course, my preference would be to avoid the TrySkip call and the copy into a separate buffer, and just deserialize the value using the reader I provide, but perhaps there's some reason you guys don't do that.)

Agreed. I'm guessing this logic was added for a reason, but that reason is unknown to me and may well be obsolete. It might be worth launching an investigation but at this point we are severely backlogged and can't prioritize it. Would you be interested in taking a look?

> The EnsureComplete method makes sure all the data for the item the reader is currently positioned at is available to be read by the reader. This may require saving the reader state, reading more data, and resuming the reader based on the saved state.

Ultimately this could be addressed by https://github.com/dotnet/runtime/issues/63795. It hasn't been prototyped yet, but we'd be looking at exposing `TrySerialize` and `TryDeserialize` methods roughly following this pattern:
```C#
while(streamReader.Read(ref reader) && reader.TokenType != JsonTokenType.EndArray)
{
     var state = new ReadState();
     while (!JsonSerializer.TryDeserialize<MyItem>(ref reader, out MyItem? result, ref state, ...))
     {
          streamReader.Read(ref reader);
     }

     processItem(result);
}
```
Ultimately this is how the streaming serialization methods are implemented under wraps, exposing such methods could allow more bespoke streaming applications.

**Comment by eiriktsarpalis** [comment]
> > Would you be interested in taking a look?
> 
> Perhaps, although I'd first have to figure out how to get started debugging the standard library. Any pointers?

Sure, [this guide](https://github.com/dotnet/runtime/tree/main/docs/workflow) should help getting your started.
