### ISSUE TITLE
Quic tests failing with Error Code: 0xEF850AE0 Stream aborted by peer

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#67476]
Many Quic tests failed in #67466 with:
```
 System.Net.Quic.Tests.MsQuicTests.WriteTests(writes: [[1000004], [15003], [502], [1000004], [1000004]], writeType: GatheredSequence) [FAIL]
      System.AggregateException : One or more errors occurred. (Could not complete receive call. Error Code: 0xEF850AE0) (Stream aborted by peer (4294967295).)
      ---- System.Net.Quic.QuicException : Could not complete receive call. Error Code: 0xEF850AE0
      ---- System.Net.Quic.QuicStreamAbortedException : Stream aborted by peer (4294967295).
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(88,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
```

**Comment by jkotas** [comment]
cc @ManickaP Potentially related to #67383
