### ISSUE TITLE
[wasm] ILLinker update broke wasm builds

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#67538]
This started breaking with https://github.com/dotnet/runtime/pull/67381 . [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1697346&view=logs&j=06c2b9cd-9a25-5ea1-8363-c1b61a607e70&t=07e56740-dd3a-5379-9df5-8d02f9b6c188):

```
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues [/__w/1/s/src/libraries/System.Net.Http/tests/FunctionalTests/System.Net.Http.Functional.Tests.csproj]
##[error]ILLink(0,0): error IL1012: (NETCORE_ENGINEERING_TELEMETRY=Build) IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: System.Void System.Net.Http.Functional.Tests.SocketsHttpHandler_Http2FlowControl_Test::<TestClientWindowScalingAsync>g__Wait|13_2(System.TimeSpan)
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
     at Mono.Linker.CompilerGeneratedState.PopulateCacheForType(TypeDefinition type)
     at Mono.Linker.CompilerGeneratedState.TryGetOwningMethodForCompilerGeneratedMember(IMemberDefinition sourceMember, MethodDefinition& owningMethod)
     at Mono.Linker.Steps.MarkStep.ShouldSuppressAnalysisWarningsForRequiresUnreferencedCode()
     at Mono.Linker.Steps.MarkStep.CheckAndReportRequiresUnreferencedCode(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessAnalysisAnnotationsForMethod(MethodDefinition method, DependencyKind dependencyKind)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkModule(ModuleDefinition module, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger, Boolean throwOnFatalLinkerException)
     at Mono.Linker.Driver.Main(String[] args)
```

cc @akoeplinger @sbomer @lewing

**Comment by radical** [comment]
This is fixed now, thanks.
