### ISSUE TITLE
Bad Process.StartTime in .NET 6 on Android

### ISSUE THREAD

**Issue by AigioL** [dotnet/runtime#67583]
### Description

```System.Diagnostics.Process.StartTime``` throws an exception on net6.0-android, but works fine on Xamarin.Android

### Reproduction Steps

```
void TestProcessStartTime()
{
    string startTimeString;
    try
    {
        var p = global::System.Diagnostics.Process.GetCurrentProcess();
        startTimeString = p.StartTime.ToString();
    }
    catch (Exception e)
    {
        startTimeString = e.ToString();
    }
    WriteLine($"StartTime: {startTimeString}");
}
```

### Expected behavior

Returns the correct DateTime

![Screenshot_1649162413](https://user-images.githubusercontent.com/24450093/161756337-92de2f1b-e093-49aa-8765-3486b0b677f7.png)

### Actual behavior

```
 android.runtime.JavaProxyThrowable: System.UnauthorizedAccessException: Access to the path '/proc/stat' is denied.
     ---> System.IO.IOException: Permission denied
       --- End of inner exception stack trace ---
        at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
        at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
        at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
        at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
        at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
        at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
        at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
        at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
        at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
        at System.IO.File.InternalReadAllText(String path, Encoding encoding)
        at System.IO.File.ReadAllText(String path)
        at System.Diagnostics.Process.get_BootTime()
        at System.Diagnostics.Process.BootTimeToDateTime(TimeSpan timespanAfterBoot)
        at System.Diagnostics.Process.get_StartTimeCore()
        at System.Diagnostics.Process.get_StartTime()
```
![Screenshot_1649162406](https://user-images.githubusercontent.com/24450093/161756302-ee34d050-5d1b-4ae6-9d70-34ebb8a456f9.png)

### Other information

This is the compiled apk files

[Xamarin.Android 12 APK](https://github.com/BeyondDimension/AspNetCore.Mobile/releases/download/test-process-starttime/com.github.beyonddimension.aspnetcore.mobile-Signed.apk)

[NET 6.0 APK](https://github.com/BeyondDimension/AspNetCore.Mobile/releases/download/test-process-starttime/com.github.beyonddimension.aspnetcore.mobile.net6-Signed.apk)

**Comment by steveisok** [comment]
@am11 Do you think you'll have time to fix this?

**Comment by am11** [comment]
@steveisok, thanks for the ping. #67589 needs device testing on Android. I tried to setup an emulator last month, but it was having some issues and I got distracted by other stuff. Is there any readymade docker or emulator setup available which I can pull and use without spending time on environment setup?

Otherwise, if someone has the dev device and spare cycles to help, we need to debug this (standalone) C code and compare with Linux desktop to find out which API behaves differently on Android, and what is the minimal change that could be applied to it to get the ball rolling:

```c
#include <assert.h>
#include <stdio.h>
#include <time.h>
#include <inttypes.h>

#define TARGET_LINUX

enum
{
    MicroSecondsToNanoSeconds = 1000,   // 10^3
    SecondsToNanoSeconds = 1000000000,  // 10^9
    SecondsToTicks = 10000000,          // 10^7
    TicksToNanoSeconds = 100,           // 10^2
};

int64_t SystemNative_GetBootTimeTicks()
{
#ifdef TARGET_LINUX
    struct timespec ts;

    int result = clock_gettime(CLOCK_BOOTTIME, &ts);
    assert(result == 0); // only possible errors are if the given clockId isn't supported or &ts is an invalid address
    (void)result; // suppress unused parameter warning in release builds

    int64_t sinceBootTicks = (ts.tv_sec * SecondsToTicks) + (ts.tv_nsec / TicksToNanoSeconds);

    result = clock_gettime(CLOCK_REALTIME_COARSE, &ts);
    assert(result == 0);

    int64_t sinceEpochTicks = (ts.tv_sec * SecondsToTicks) + (ts.tv_nsec / TicksToNanoSeconds);

    return sinceEpochTicks - sinceBootTicks;
#else
    return -1;
#endif
}


int main() {
    printf("%" PRId64 "\n", SystemNative_GetBootTimeTicks());
    return 0;
}
```

(`SystemNative_GetBootTimeTicks` is the current state of that function in PR)

**Comment by adamsitnik** [comment]
> thanks for the ping. https://github.com/dotnet/runtime/pull/67589 needs device testing on Android. I

@steveisok is there any chance you could help @am11 with the debugging?

**Comment by danmoseley** [comment]
@steveisok ?

**Comment by danmoseley** [comment]
@steveisok 🙂

**Comment by steveisok** [comment]
Sorry, yes, we can help with this one.

**Comment by steveisok** [comment]
@simonrozsival can you please help out with this one?

**Comment by simonrozsival** [comment]
@am11 I tested the code on my device with API 32 and on emulators with API 21 and 24 and it worked well on all of these levels. It seems to me that the only problem with the PR is that you're checking `TARGET_LINUX` and not `TARGET_ANDROID`.

**Comment by adamsitnik** [comment]
@simonrozsival thank you for your help!
