### ISSUE TITLE
[release/6.0] Test failure: profiler/multiple/multiple/multiple.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#67605]
In a release/6.0 jitstress run:

https://dev.azure.com/dnceng/public/_build/results?buildId=1697645&view=ms.vss-test-web.build-test-results-tab&runId=46302518&resultId=100017&paneView=debug

I see:

```
    profiler/multiple/multiple/multiple.sh [FAIL]
      Fatal error while logging another fatal error.
      Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
         at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
         at Profiler.Tests.MultiplyLoaded.Main(String[] args)
      /root/helix/work/workitem/e/profiler/multiple/multiple/multiple.sh: line 348:    73 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.multiple/multiple/multiple.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false multiple.dll ''
      Profiler path: /root/helix/work/workitem/e/profiler/multiple/multiple/libProfiler.so
      Profiler path: /root/helix/work/workitem/e/profiler/multiple/multiple/libProfiler.so
      Profiler.dll!DllGetClassObject
      Profiler.dll!Profiler::Initialize
      Setting exception mask
      Profiler.dll!DllGetClassObject
      Profiler.dll!Profiler::Initialize
      Profiler path: /root/helix/work/workitem/e/profiler/multiple/multiple/libProfiler.so
      [createdump] Gathering state for process 83 corerun
      [createdump] Crashing thread 00000063 signal 00000006
      [createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.83.dmp
      [createdump] Written 89767936 bytes (21916 pages) to core file
      [createdump] Dump successfully written
      
      Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
      [createdump] Gathering state for process 73 corerun
      [createdump] Crashing thread 00000049 signal 00000006
      [createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.73.dmp
      [createdump] Written 109113344 bytes (26639 pages) to core file
      [createdump] Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
```

Searching for this issue in GitHub, I see various hits and possibly a fix. If the fix isn't ported to release/6.0, could the test at least be disabled there?

@davmason @tommcdon

**Comment by mikelle-rogers** [comment]
Closing because the PR has been merged and we haven't heard any further reports.
