### ISSUE TITLE
[iOS] OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached Test Fails

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#67611]
Found in the rolling build and the test fails with:

https://github.com/dotnet/runtime/blob/670262af14840e3ae20738647199ab0a48fae7fe/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsMonitorTest.cs#L473-L485

```
Assert.Equal() Failure
Expected: 0
Actual:   24
```

**Comment by carlossanlop** [comment]
Found again in this `runtime-extra-platforms` rolling build from today:https://dev.azure.com/dnceng/public/_build/results?buildId=1700096&view=results

Artifacts: https://dev.azure.com/dnceng/public/_build/results?buildId=1700096&view=ms.vss-test-web.build-test-results-tab&runId=46336764&resultId=134879&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Log file: [net.dot.Microsoft.Extensions.Options.Tests.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-168242863f234be695/Microsoft.Extensions.Options.Tests/1/net.dot.Microsoft.Extensions.Options.Tests.log?sv=2019-07-07&se=2022-04-25T09%3A56%3A04Z&sr=c&sp=rl&sig=3FQPSt5FCNMkp1CpdRxlvAK5sGI5aLoE18bfTjbFmeM%3D)

Callstack:

```
[03:17:20.4929170] 2022-04-05 03:17:20.453 Microsoft.Extensions.Options.Tests[52859:67860912] Failed tests:
[03:17:20.4961440] 2022-04-05 03:17:20.456 Microsoft.Extensions.Options.Tests[52859:67860912] 1) 	[FAIL] Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached   Test name: Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached
[03:17:20.4961780] 2022-04-05 03:17:20.456 Microsoft.Extensions.Options.Tests[52859:67860912]    Assembly:  [Microsoft.Extensions.Options.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]
[03:17:20.4961970]    Exception messages: Assert.Equal() Failure
[03:17:20.4962010] Expected: 0
[03:17:20.4962080] 2022-04-05 03:17:20.456 Microsoft.Extensions.Options.Tests[52859:67860912] Actual:   24   Exception stack traces:    at Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached()
[03:17:20.4962130]    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
[03:17:20.4962170]    Execution time: 0.0105616
```

**Comment by carlossanlop** [comment]
Ah, sorry. Just noticed this is reporting the same rolling build failure, and you merged a fix. Removing the blocking label.

**Comment by carlossanlop** [comment]
I saw this again in runtime-extra-platforms but I suspect it's because the fix above was not included yet in this rolling build:

- Pipeline: `Build tvOS arm64 Release AllSubsets_Mono`
Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1701191&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d&l=65
Artifacts: https://dev.azure.com/dnceng/public/_build/results?buildId=1701191&view=ms.vss-test-web.build-test-results-tab&runId=46369408&resultId=131420&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
Test method: [FAIL] Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached
Issue: https://github.com/dotnet/runtime/issues/67611
Callstack:
```
Test name: Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached
[15:20:18.3110440] 2022-04-05 15:20:18.368 Microsoft.Extensions.Options.Tests[38963:48017886]    Assembly:  [Microsoft.Extensions.Options.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]
[15:20:18.3110500]    Exception messages: Assert.Equal() Failure
[15:20:18.3110540] Expected: 0
[15:20:18.3115400] 2022-04-05 15:20:18.369 Microsoft.Extensions.Options.Tests[38963:48017886] Actual:   24   Exception stack traces:    at Microsoft.Extensions.Options.Tests.OptionsMonitorTest.TestCurrentValueDoesNotAllocateOnceValueIsCached()
[15:20:18.3115630]    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
[15:20:18.3115690]    Execution time: 0.0114359
```

**Comment by lewing** [comment]
Has anyone looked into this, There was a browser failure on a recent pr

**Comment by steveisok** [comment]
No, not that I'm aware of. I believe this was somewhat flaky.

**Comment by SamMonoRT** [comment]
@BrzVlad - any insights into the GC.GetAllocatedBytesForCurrentThread() API?

**Comment by tarekgh** [comment]
I am going to disable this test on Mono as @jkotas suggested in the other issue.

**Comment by tarekgh** [comment]
I opened the PR https://github.com/dotnet/runtime/pull/84569

**Comment by tarekgh** [comment]
@lewing I'll close my PR as I am seeing you already opened another https://github.com/dotnet/runtime/pull/84571
