### ISSUE TITLE
Rolling build failure: Microsoft.Extensions.Hosting.UseWindowsServiceTests.DefaultsToOffOutsideOfService

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#67625]
Failure in rolling build: https://dev.azure.com/dnceng/public/_build/results?buildId=1699174&view=results is blocking a clean CI.

Pipeline: Build Browser wasm Linux Release LibraryTests
Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1699174&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89&l=294
Logs: 
  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7d96623c590c42948e/normal-Microsoft.Extensions.Hosting.WindowsServices.Tests/1/console.15d888fc.log?sv=2019-07-07&se=2022-04-24T20%3A53%3A20Z&sr=c&sp=rl&sig=dMJFI3lh6gm2lNr36F0Vy0mB8v3Nc1ugn8jxmqFX2c0%3D
  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c0b0aae46bfb435eab/WasmTestOnBrowser-Microsoft.Extensions.Hosting.WindowsServices.Tests/1/console.bc820607.log?sv=2019-07-07&se=2022-04-24T20%3A53%3A20Z&sr=c&sp=rl&
Test method: `[FAIL] Microsoft.Extensions.Hosting.UseWindowsServiceTests.DefaultsToOffOutsideOfService`
Issue: https://github.com/dotnet/runtime/issues/67601
Callstack:
```
[21:20:06] info: Assert.IsType() Failure
[21:20:06] info: Expected: Microsoft.Extensions.Hosting.Internal.ConsoleLifetime
[21:20:06] info: Actual:   Microsoft.Extensions.Hosting.Internal.NullLifetime
[21:20:06] info:    at Microsoft.Extensions.Hosting.UseWindowsServiceTests.DefaultsToOffOutsideOfService()
[21:20:06] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
[21:20:06] info: Finished:    Microsoft.Extensions.Hosting.WindowsServices.Tests.dll****
```

**Comment by radical** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/67550
