### ISSUE TITLE
Test failure：System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls11, url: \"https://www.ssllabs.com:10302/\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67685]
Run: [runtime-libraries-coreclr outerloop 20220406.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1702680&view=ms.vss-test-web.build-test-results-tab&runId=46401768&paneView=debug&resultId=104132)

Failed test：
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls11, url: \"https://www.ssllabs.com:10302/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls, url: \"https://www.ssllabs.com:10301/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls11, url: \"https://www.ssllabs.com:10302/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls, url: \"https://www.ssllabs.com:10301/\")

net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls11, url: \"https://www.ssllabs.com:10302/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls, url: \"https://www.ssllabs.com:10301/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls11, url: \"https://www.ssllabs.com:10302/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls, url: \"https://www.ssllabs.com:10301/\")

```
**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'.


Stack trace
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 558
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 34
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(SslProtocols sslProtocols, String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 199
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 1046
```

**Comment by rzikm** [comment]
Fixed by https://github.com/dotnet/runtime/pull/68083
