### ISSUE TITLE
Test failure: System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok(useAsync: False)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67683]
Run: [runtime-libraries-coreclr outerloop 20220406.7
](https://dev.azure.com/dnceng/public/_build/results?buildId=1702680&view=ms.vss-test-web.build-test-results-tab&runId=46401768&paneView=debug&resultId=104004)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: AsyncAPM, writeSize: 10485760, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: AsyncAPM, writeSize: 10485760, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: SyncAPM, writeSize: 10485760, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: SyncAPM, writeSize: 10485760, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: AsyncMemory, writeSize: 10485760, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: AsyncMemory, writeSize: 10485760, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: AsyncArray, writeSize: 10485760, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: AsyncArray, writeSize: 10485760, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: SyncArray, writeSize: 10485760, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: SyncArray, writeSize: 10485760, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: SyncSpan, writeSize: 10485760, startWithFlush: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ReadWrite_Success_Large(mode: SyncSpan, writeSize: 10485760, startWithFlush: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.CopyToAsync_AllDataCopied_Large(useAsync: True)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.CopyToAsync_AllDataCopied_Large(useAsync: False)
- System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.Parallel_ReadWriteMultipleStreamsConcurrently

net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: \"\")
- System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok(useAsync: False)
```
**Error message:**
```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.


Stack trace
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 160
   at System.Net.Security.SecureChannel.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 723
   at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 622
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 892
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs:line 797
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 417
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 128
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 92
   at System.Net.Security.Tests.SslStreamConformanceTests.CreateWrappedConnectedStreamsAsync(StreamPair wrapped, Boolean leaveOpen) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamConformanceTests.cs:line 49
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1775
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success_Large(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1719
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc) in /_/src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs:line 138
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 605
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 305
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs:line 147
```

**Comment by wfurt** [comment]
should be disabled by  #68083. https://github.com/dotnet/runtime/issues/67682 tracks disabled test.
