### ISSUE TITLE
Test failure: System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: \"api.nuget.org\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67686]
Run:[ runtime-libraries-coreclr outerloop 20220406.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1702680&view=ms.vss-test-web.build-test-results-tab&runId=46401590&paneView=debug&resultId=103501)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(host: \"api.nuget.org\")

```
**Error message:**
```
System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.


Stack trace
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1458
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1353
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 760
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 487
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 350
   at System.Net.Security.Tests.CertificateValidationRemoteServer.EndToEndHelper(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 106
   at System.Net.Security.Tests.CertificateValidationRemoteServer.DefaultConnect_EndToEnd_Ok(String host) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 85
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

**Comment by wfurt** [comment]
fixed by #67935.
