### ISSUE TITLE
Test failure: Attempt #1 - System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok(useAsync: True)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67687]
Run: [runtime-libraries-coreclr outerloop 20220406.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1702680&view=ms.vss-test-web.build-test-results-tab&runId=46401590&paneView=debug&resultId=103502)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- Attempt #1 - System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok(useAsync: True)

```
**Error message:**
```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- System.ComponentModel.Win32Exception : The function requested is not supported


Stack trace
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 387
   at System.Net.Security.Tests.CertificateValidationRemoteServer.CertificateValidationRemoteServer_EndToEnd_Ok(Boolean useAsync) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 44
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

**Comment by rzikm** [comment]
Seems to be newly failing, 6 hits so far

**Comment by rzikm** [comment]
Seems to be failing sufficiently often, so far on Win7 only, I will put up a PR to disable the test

**Comment by karelz** [comment]
Triage: Likely some test infra problem. We should address it.
