### ISSUE TITLE
Test failure System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_CollectionRemainsConsistent

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67828]
Run: [runtime-libraries-coreclr outerloop 20220410.7 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1709660&view=ms.vss-test-web.build-test-results-tab&runId=46507548&resultId=100052&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_release-(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620

- System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_CollectionRemainsConsistent

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.<>c__DisplayClass50_0.<ManyConcurrentAddsTakes_CollectionRemainsConsistent>b__0() in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 752
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.WaitAllOrAnyFailed(Task[] tasks) in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 1013
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakes_CollectionRemainsConsistent() in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 764
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
```

**Comment by danmoseley** [comment]
Only one failure on record, but a little worrying to have this fail. The test seems straightforward, so it might be some threading or memory model peculiarity? @stephentoub any theories off the top of your head?


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Method == "ManyConcurrentAddsTakes_CollectionRemainsConsistent"
//| where Type == "LibraryImportGenerator.UnitTests.AdditionalAttributesOnStub"
//| where WorkItemFriendlyName  == "LibraryImportGenerator.Unit.Tests"
//| where Finished >= now(-20d)
| where Result == "Fail"
//| where QueueName == "windows.11.amd64.clientpre.open"
//| where Message startswith "System.ArgumentNullException : Value cannot be null. (Parameter 'package"
| project Type, Method,
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Container = tostring(parse_json(Properties).operatingSystem), 
  Arch = tostring(parse_json(Properties).architecture),
 Finished,
 Build
  //Duration,
 // Method,
 // Build = tostring(parse_json(Properties).BuildNumber),
 //  Message//,//
 //,StackTrace
```

|Type|Method|Pipeline|Pipeline_Configuration|OS|Container|Arch|Finished|Build|
|---|---|---|---|---|---|---|---|---|
|System.Collections.Concurrent.Tests.ConcurrentQueueTests|ManyConcurrentAddsTakes_CollectionRemainsConsistent|runtime-libraries-coreclr outerloop|Release|ubuntu.1604.amd64.open.rt|(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620|x64|2022-04-10 12:33:14.6190000||

**Comment by karelz** [comment]
Super low frequency, removing blocking-outerloop label.
