### ISSUE TITLE
Rolling build failure: LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#67864]
@elinor-fung @jkoritzinsky please disable the test or merge a fix as soon as possible since it's affecting rolling builds.

- Pipeline: https://dev.azure.com/dnceng/public/_build/results?buildId=1709879&view=results

Two failures:

Queue: `Libraries Test Run release coreclr OSX x64 Release`
  - Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1709879&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b&t=caea1d4b-c90c-5be1-e57d-c4635079c333&l=57
  - Log file: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1539bf0ea63e4a9094/LibraryImportGenerator.Unit.Tests/1/console.f9e0b1c5.log?sv=2019-07-07&se=2022-04-30T20%3A44%3A32Z&sr=c&sp=rl&sig=x1tUZhcT%2BqgnL0zCMeCo7Ar0RTclnJLLbZaT%2B9jwXCo%3D
  - <details>
       <summary>Callstack</summary>

       ```
    LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic [FAIL]
      System.ArgumentNullException : Value cannot be null. (Parameter 'packageStream')
      Stack Trace:
           at NuGet.Packaging.PackageExtractor.ExtractPackageAsync(String source, Stream packageStream, PackagePathResolver packagePathResolver, PackageExtractionContext packageExtractionContext, CancellationToken token, Guid parentId)
        /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(358,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken)
        /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(197,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken)
        /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(174,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs(228,0): at LibraryImportGenerator.UnitTests.TestUtils.ResolveReferenceAssemblies(ReferenceAssemblies referenceAssemblies)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs(174,0): at LibraryImportGenerator.UnitTests.TestUtils.GetReferenceAssemblies(TestTargetFramework targetFramework)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs(132,0): at LibraryImportGenerator.UnitTests.TestUtils.CreateCompilation(SyntaxTree[] sources, TestTargetFramework targetFramework, OutputKind outputKind)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Diagnostics.cs(317,0): at LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic()
       ```
       </details>

 Queue: `Libraries Test Run release mono OSX x64 Release`
  - Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1709879&view=logs&j=d8aa34eb-4280-5100-d989-99a78ab22b6c&t=683b5689-715c-520d-1153-f2b6228fe807&l=57
  - Log file: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-718e21cd59ac41cca5/LibraryImportGenerator.Unit.Tests/1/console.bf6b6101.log?sv=2019-07-07&se=2022-04-30T20%3A44%3A37Z&sr=c&sp=rl&sig=3rqXgAzo4isqjuOQrmSTQBCTw%2BtAY2JKD%2BdwkcQ5knE%3D
  - <details>
       <summary>Callstack</summary>

       ```
    LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic [FAIL]
      System.ArgumentNullException : Value cannot be null. (Parameter 'packageStream')
      Stack Trace:
           at NuGet.Packaging.PackageExtractor.ExtractPackageAsync(String source, Stream packageStream, PackagePathResolver packagePathResolver, PackageExtractionContext packageExtractionContext, CancellationToken token, Guid parentId)
        /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(358,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken)
        /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(197,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken)
        /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs(174,0): at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs(228,0): at LibraryImportGenerator.UnitTests.TestUtils.ResolveReferenceAssemblies(ReferenceAssemblies referenceAssemblies)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs(174,0): at LibraryImportGenerator.UnitTests.TestUtils.GetReferenceAssemblies(TestTargetFramework targetFramework)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs(132,0): at LibraryImportGenerator.UnitTests.TestUtils.CreateCompilation(SyntaxTree[] sources, TestTargetFramework targetFramework, OutputKind outputKind)
        /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Diagnostics.cs(317,0): at LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic()
       ```
       </details>

**Comment by elinor-fung** [comment]
@jkoritzinsky this is https://github.com/dotnet/roslyn-sdk/issues/974, right? Do we just need to update to a version of the roslyn testing packages that has the fix from last week?

**Comment by jkoritzinsky** [comment]
Fixed by https://github.com/dotnet/runtime/pull/67676
