### ISSUE TITLE
System.Text.RegularExpressions.Tests.RegexMatchTests.Match_InstanceMethods_DefaultTimeout_Throws failing on CoreCLR checked runs 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#67886]
```
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 278 of 308 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)
    System.Text.RegularExpressions.Tests.RegexMatchTests.Match_InstanceMethods_DefaultTimeout_Throws(engine: SourceGenerated) [FAIL]
      Half-way through waiting for remote process.
      Timed out at 4/12/2022 3:37:54 AM after 60000ms waiting for remote process.
      	Process ID: 202
      	Handle: 1968
      	Name: dotnet
      	MainModule: /root/helix/work/correlation/dotnet
      	StartTime: 4/12/2022 3:36:53 AM
      	TotalProcessorTime: 00:01:24.7400000
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Match.Tests.cs(1061,0): at System.Text.RegularExpressions.Tests.RegexMatchTests.Match_InstanceMethods_DefaultTimeout_Throws(RegexEngine engine)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
  Finished:    System.Text.RegularExpressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.RegularExpressions.Tests  Total: 15161, Errors: 0, Failed: 1, Skipped: 0, Time: 352.840s
```

**Comment by jkotas** [comment]
Failed in #67885, #67884, #67882, ...

**Comment by jkotas** [comment]
Test introduced by #67775

cc @stephentoub

**Comment by danmoseley** [comment]
Let's just mark it release only.

**Comment by stephentoub** [comment]
I looked into this a bit, and the code doesn't even get to executing the regex: it's just taking a really long time in the source generator itself, e.g.
```
[PrestubMethodFrame] (System.Text.RegularExpressions.Generator.RegexGenerator+<>c__DisplayClass19_0.<EmitTryMatchAtCurrentPosition>g__EmitNode|17)
System.Text.RegularExpressions.Generator.RegexGenerator.EmitTryMatchAtCurrentPosition(System.CodeDom.Compiler.IndentedTextWriter, RegexMethod, System.Collections.Generic.Dictionary2<System.String,System.String[]>) 			System.Text.RegularExpressions.Generator.RegexGenerator.EmitRegexDerivedTypeRunnerFactory(System.CodeDom.Compiler.IndentedTextWriter, RegexMethod, System.Collections.Generic.Dictionary2<System.String,System.String[]>)
System.Text.RegularExpressions.Generator.RegexGenerator+<>c.<Initialize>b__4_1(System.Object, System.Threading.CancellationToken)
```

We use the source generator to process thousands of expressions as part of every CI run, including on checked runtimes.  What appears to be special about this one test is it's the only one that runs via RemoteExecutor.Invoke (there's one other, but it's already disabled for all runtime configurations other than release, bugged against https://github.com/dotnet/runtime/issues/10680).

Given that, I'm just going to disable this test against non-release runtimes as well.
