### ISSUE TITLE
WasmTestRunner failing with assertion for generic math tests

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#67999]
See https://github.com/dotnet/runtime/pull/67939 and https://dev.azure.com/dnceng/public/_build/results?buildId=1716676

```
[22:59:47] info: Incoming arguments: --run WasmTestRunner.dll System.Runtime.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[22:59:47] info: Application arguments: --run WasmTestRunner.dll System.Runtime.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[22:59:47] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[22:59:47] info: console.debug: Could not find symbols file dotnet.js.symbols. Ignoring.
[22:59:47] info: console.info: Initializing.....
[22:59:47] info: Discovering: System.Runtime.Tests.dll (method display = ClassAndMethod, method display options = None)
[22:59:52] info: Discovered:  System.Runtime.Tests.dll (found 7436 of 7726 test cases)
[22:59:52] info: Using random seed for test cases: 338959153
[22:59:52] info: Using random seed for collections: 338959153
[22:59:52] info: Starting:    System.Runtime.Tests.dll
[22:59:52] fail: Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:5976, condition `<disabled>' not met
[22:59:52] fail: 
[22:59:52] fail:     at mono_wasm_stringify_as_error_with_stack (./dotnet.js:3:19506)
[22:59:52] fail:     at Object.mono_wasm_trace_logger (./dotnet.js:3:19877)
[22:59:52] fail:     at _mono_wasm_trace_logger (./dotnet.js:6187:67)
[22:59:52] fail:     at wasm_trace_logger (<anonymous>:wasm-function[121934]:0x1cf6cb6)
[22:59:52] fail:     at eglib_log_adapter (<anonymous>:wasm-function[110146]:0x1b9d784)
[22:59:52] fail:     at monoeg_g_logstr (<anonymous>:wasm-function[121115]:0x1cdc468)
[22:59:52] fail:     at monoeg_g_logv_nofree (<anonymous>:wasm-function[121113]:0x1cdc417)
[22:59:52] fail:     at monoeg_assertion_message (<anonymous>:wasm-function[121118]:0x1cdc4e7)
[22:59:52] fail:     at mono_assertion_message (<anonymous>:wasm-function[121120]:0x1cdc52e)
[22:59:52] fail:     at mono_assertion_message_disabled (<anonymous>:wasm-function[121119]:0x1cdc4ff)
[22:59:52] fail:     at mono_aot_get_unbox_trampoline (<anonymous>:wasm-function[120273]:0x1cc567e)
[22:59:52] fail:     at mini_llvmonly_add_method_wrappers (<anonymous>:wasm-function[120704]:0x1cd2b3d)
[22:59:52] fail:     at mini_llvmonly_load_method (<anonymous>:wasm-function[120703]:0x1cd2a89)
[22:59:52] fail:     at resolve_vcall (<anonymous>:wasm-function[120720]:0x1cd3247)
[22:59:52] fail:     at mini_llvmonly_init_vtable_slot (<anonymous>:wasm-function[120714]:0x1cd2ffa)
[22:59:52] fail:     at mini_llvmonly_get_imt_trampoline (<anonymous>:wasm-function[120713]:0x1cd2e8d)
[22:59:52] fail:     at initialize_imt_slot (<anonymous>:wasm-function[108577]:0x1b75906)
[22:59:52] fail:     at build_imt_slots (<anonymous>:wasm-function[108569]:0x1b75667)
[22:59:52] fail:     at mono_vtable_build_imt_slot (<anonymous>:wasm-function[108568]:0x1b7544f)
[22:59:52] fail:     at mini_llvmonly_initial_imt_tramp (<anonymous>:wasm-function[120728]:0x1cd33d2)
[22:59:52] fail:     at corlib_System_Convert_ToString_object_System_IFormatProvider (<anonymous>:wasm-function[31147]:0x76d566)
[22:59:52] fail:     at invoke_iiii (./dotnet.js:8323:36)
[22:59:52] fail:     at xunit_execution_dotnet_Xunit_Sdk_ArgumentFormatter_Format_object_int_System_Nullable_1_int__System_Nullable_1_int_bool (<anonymous>:wasm-function[97259]:0x1993c82)
...
```

**Comment by tannergooding** [comment]
This still repro's even with all generic math tests disabled (and not even compiled in) for `Browser`

**Comment by jeffhandley** [comment]
@radical is this something you could help us with? This is blocking a PR we want to get in for Preview 4 and we're baffled from the libraries team side.

**Comment by radical** [comment]
cc @vargaz

**Comment by radical** [comment]
[console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67939-merge-0840a4b8ec1245ffa2/normal-System.Runtime.Tests/1/console.5fae6c10.log?sv=2019-07-07&se=2022-05-03T09%3A27%3A15Z&sr=c&sp=rl&sig=8tVJwTxLcSMPne%2BDaRlR%2FG6xaHH5thiQBhAehq9%2BmP4%3D)

**Comment by lewing** [comment]
cc @lambdageek

**Comment by vargaz** [comment]
Testcase for wasm:
```
        IBinaryInteger<int> i = 1;
        Console.WriteLine (i.GetShortestBitLength ());
```
