### ISSUE TITLE
Debug.Assert failure in System.Reflection.FieldInfo.SetValue in Debug Mono builds

### ISSUE THREAD

**Issue by directhex** [dotnet/runtime#68029]
### Description

Various tests are failing in Debug configuration with Mono in tests which use Moq (e.g. `System.Text.Tests.EncodingTests.GetEncoding_FromProvider_ByCodePage_WithDisallowedEncoding_Throws`, or `Microsoft.Extensions.Configuration.Test.ConfigurationRootTest.RootDisposesChangeTokenRegistrations`). The key stack trace elements look something like:

```
 at System.Diagnostics.Debug.Assert(Boolean condition) in /home/directhex/Projects/runtime/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 80
 at System.RuntimeType.CheckValue(Object& value, Boolean& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr) in /home/directhex/Projects/runtime/src/mono/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1689
 at System.Reflection.RuntimeFieldInfo.SetValue(Object obj, Object val, BindingFlags invokeAttr, Binder binder, CultureInfo culture) in /home/directhex/Projects/runtime/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeFieldInfo.cs:line 282
 at System.Reflection.FieldInfo.SetValue(Object obj, Object value) in /home/directhex/Projects/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/FieldInfo.cs:line 68
 at Castle.DynamicProxy.Internal.TypeUtil.SetStaticField(Type type, String fieldName, BindingFlags additionalFlags, Object value)
```

This issue does not appear in Release builds, as the assert itself is what's buggy.

### Reproduction Steps

Build/run System.Runtime.Tests with `--configuration Debug`

### Expected behavior

The tests run

### Actual behavior

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

No native Android stacktrace (see debuggerd output).

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7439c3ff25cf):0x7439c3ff25bf  8d 54 24 10 ba 06 00 00 00 b8 29 01 00 00 0f 05  .T$.......).....
0x7439c3ff25cf  0f 10 05 82 3c fc ff 0f 29 84 24 a0 00 00 00 0f  ....<...).$.....
0x7439c3ff25df  10 05 63 3c fc ff 0f 29 84 24 90 00 00 00 48 8d  ..c<...).$....H.
0x7439c3ff25ef  b4 24 90 00 00 00 bf 06 00 00 00 31 d2 e8 df 18  .$.........1....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Environment:FailFast <0x00095>
	  at System.Diagnostics.DebugProvider:FailCore <0x00103>
	  at System.Diagnostics.DebugProvider:Fail <0x000eb>
	  at System.Diagnostics.Debug:Fail <0x00045>
	  at System.Diagnostics.Debug:Assert <0x00053>
	  at System.Diagnostics.Debug:Assert <0x00043>
	  at System.RuntimeType:CheckValue <0x0008f>
	  at System.Reflection.RuntimeFieldInfo:SetValue <0x0019b>
	  at System.Reflection.FieldInfo:SetValue <0x00052>
	  at Castle.DynamicProxy.Internal.TypeUtil:SetStaticField <0x0008f>
	  at Castle.DynamicProxy.Generators.BaseProxyGenerator:InitializeStaticFields <0x0004b>
	  at Castle.DynamicProxy.Generators.InterfaceProxyWithoutTargetGenerator:GenerateType <0x00707>
	  at <>c__DisplayClass6_0:<GenerateCode>b__0 <0x0004d>
	  at <>c__DisplayClass33_0:<ObtainProxyType>b__0 <0x0017c>
	  at Castle.Core.Internal.SynchronizedDictionary`2:GetOrAdd <0x00189>
	  at Castle.DynamicProxy.Generators.BaseProxyGenerator:ObtainProxyType <0x00167>
	  at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator:GenerateCode <0x002c7>
	  at Castle.DynamicProxy.DefaultProxyBuilder:CreateInterfaceProxyTypeWithoutTarget <0x000df>
	  at Castle.DynamicProxy.ProxyGenerator:CreateInterfaceProxyTypeWithoutTarget <0x0005d>
	  at Castle.DynamicProxy.ProxyGenerator:CreateInterfaceProxyWithoutTarget <0x000b7>
	  at Moq.CastleProxyFactory:CreateProxy <0x00163>
	  at Moq.Mock`1:InitializeInstance <0x00144>
	  at Moq.Mock`1:OnGetObject <0x00037>
	  at Moq.Mock:get_Object <0x0002f>
	  at Moq.Mock`1:get_Object <0x0002b>
	  at Microsoft.Extensions.Configuration.Test.ConfigurationRootTest:RootDisposesChangeTokenRegistrations <0x00206>
	  at System.Object:runtime_invoke_void__this__ <0x00091>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000b9>
	  at System.Reflection.RuntimeMethodInfo:InvokeNonEmitUnsafe <0x0009f>
	  at System.Reflection.MethodInvoker:InvokeUnsafe <0x00067>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x001db>
	  at System.Reflection.MethodBase:Invoke <0x00049>
	  at Xunit.Sdk.TestInvoker`1:CallTestMethod <0x00043>
	  at <<InvokeTestMethodAsync>b__1>d:MoveNext <0x003d1>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000bf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x0002b>
	  at <>c__DisplayClass48_0:<InvokeTestMethodAsync>b__1 <0x000c7>
	  at <AggregateAsync>d__4:MoveNext <0x000e2>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000bf>
	  at Xunit.Sdk.ExecutionTimer:AggregateAsync <0x000bf>
	  at <>c__DisplayClass48_0:<InvokeTestMethodAsync>b__0 <0x00157>
	  at <RunAsync>d__9:MoveNext <0x00098>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000b7>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000bb>
	  at <InvokeTestMethodAsync>d__48:MoveNext <0x002af>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000c7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestInvoker`1:InvokeTestMethodAsync <0x000ef>
	  at Xunit.Sdk.XunitTestInvoker:InvokeTestMethodAsync <0x000f3>
	  at <<RunAsync>b__47_0>d:MoveNext <0x0060a>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000cf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestInvoker`1:<RunAsync>b__47_0 <0x000cf>
	  at <RunAsync>d__10`1:MoveNext <0x0009c>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000b7>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000bb>
	  at Xunit.Sdk.TestInvoker`1:RunAsync <0x000f3>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestMethodAsync <0x000db>
	  at <InvokeTestAsync>d__4:MoveNext <0x001ed>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000c7>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestAsync <0x000c7>
	  at <>c__DisplayClass43_0:<RunAsync>b__0 <0x00038>
	  at <RunAsync>d__10`1:MoveNext <0x000c6>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000bf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000f3>
	  at <RunAsync>d__43:MoveNext <0x004f3>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000cf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestRunner`1:RunAsync <0x000cf>
	  at Xunit.Sdk.XunitTestCaseRunner:RunTestAsync <0x000d7>
	  at <RunAsync>d__19:MoveNext <0x0033f>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000c7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestCaseRunner`1:RunAsync <0x000cb>
	  at Xunit.Sdk.XunitTestCase:RunAsync <0x000b3>
	  at Microsoft.DotNet.XUnitExtensions.SkippedFactTestCase:<>n__0 <0x0005b>
	  at <RunAsync>d__2:MoveNext <0x0011b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e7>
	  at Microsoft.DotNet.XUnitExtensions.SkippedFactTestCase:RunAsync <0x00167>
	  at Xunit.Sdk.XunitTestMethodRunner:RunTestCaseAsync <0x000a2>
	  at <RunTestCasesAsync>d__32:MoveNext <0x001be>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000cf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestMethodRunner`1:RunTestCasesAsync <0x000cf>
	  at <RunAsync>d__31:MoveNext <0x001f7>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000bf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestMethodRunner`1:RunAsync <0x000c7>
	  at Xunit.Sdk.XunitTestClassRunner:RunTestMethodAsync <0x000eb>
	  at <RunTestMethodsAsync>d__38:MoveNext <0x008ac>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000db>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestClassRunner`1:RunTestMethodsAsync <0x000d7>
	  at <RunAsync>d__37:MoveNext <0x00372>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000c7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestClassRunner`1:RunAsync <0x000cb>
	  at Xunit.Sdk.XunitTestCollectionRunner:RunTestClassAsync <0x000f7>
	  at <RunTestClassesAsync>d__28:MoveNext <0x003a6>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000cf>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestCollectionRunner`1:RunTestClassesAsync <0x000cf>
	  at <RunAsync>d__27:MoveNext <0x0036f>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000c7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestCollectionRunner`1:RunAsync <0x000cb>
	  at Xunit.Sdk.XunitTestAssemblyRunner:RunTestCollectionAsync <0x000c7>
	  at <RunTestCollectionsAsync>d__42:MoveNext <0x00233>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000ff>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestAssemblyRunner`1:RunTestCollectionsAsync <0x00117>
	  at Xunit.Sdk.XunitTestAssemblyRunner:<>n__0 <0x0003f>
	  at <RunTestCollectionsAsync>d__14:MoveNext <0x00283>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000c7>
	  at Xunit.Sdk.XunitTestAssemblyRunner:RunTestCollectionsAsync <0x000e3>
	  at <RunAsync>d__41:MoveNext <0x0050c>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e3>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002b>
	  at Xunit.Sdk.TestAssemblyRunner`1:RunAsync <0x000bf>
	  at <RunTestCases>d__8:MoveNext <0x0013f>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000db>
	  at Xunit.Sdk.XunitTestFrameworkExecutor:RunTestCases <0x00123>
	  at Xunit.Sdk.TestFrameworkExecutor`1:RunTests <0x000b5>
	  at Xunit.Xunit2:RunTests <0x00070>
	  at Xunit.XunitFrontController:RunTests <0x0005d>
	  at TestFrameworkExtensions:RunTests <0x00060>
	  at Xunit.ConsoleClient.ConsoleRunner:ExecuteAssembly <0x00edf>
	  at Xunit.ConsoleClient.ConsoleRunner:RunProject <0x007e7>
	  at Xunit.ConsoleClient.ConsoleRunner:EntryPoint <0x00677>
	  at Xunit.ConsoleClient.Program:Main <0x000df>
	  at <Module>:runtime_invoke_int_object <0x00091>
=================================================================
```

### Regression?

This is likely a regression, but we don't currently run any Mono Debug lanes on SRE platforms, so it's hard to be sure when it went wrong.

**Comment by directhex** [comment]
@lambdageek

**Comment by lambdageek** [comment]
/cc @steveharter 

I think this assert missed one caller: 
https://github.com/dotnet/runtime/blob/250fda5509a0810dafc27b07186a88cd4b050900/src/mono/System.Private.CoreLib/src/System/RuntimeType.Mono.cs#L1688-L1689

when called from `RuntimeFieldInfo.SetValue`, there's no "fast path" in the caller:

https://github.com/dotnet/runtime/blob/main/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeFieldInfo.cs#L282


(This should have failed a bunch of libraries tests, but apparently we don't run libraries tests against a Debug mono build)

As far as I can tell this is a performance, not correctness, issue when Asserts are disabled -`CheckValue` will call `TryConvertToType` which will call `IsInstanceOfType` which will return true and then `CheckValue` will succeed.
