### ISSUE TITLE
System.Text.RegularExpressions.Tests.RegexMatchTests.Match_InstanceMethods_DefaultTimeout_Throws times out

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#68034]
```
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 278 of 308 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)
    System.Text.RegularExpressions.Tests.RegexMatchTests.Match_InstanceMethods_DefaultTimeout_Throws(engine: SourceGenerated) [FAIL]
      Half-way through waiting for remote process.
      Timed out at 4/12/2022 8:59:15 AM after 60000ms waiting for remote process.
      	Process ID: 220
      	Handle: 6400
      	Name: dotnet
      	MainModule: /root/helix/work/correlation/dotnet
      	StartTime: 4/12/2022 8:58:15 AM
      	TotalProcessorTime: 00:01:12.2300000
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Match.Tests.cs(1061,0): at System.Text.RegularExpressions.Tests.RegexMatchTests.Match_InstanceMethods_DefaultTimeout_Throws(RegexEngine engine)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs(383,0): at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
  Finished:    System.Text.RegularExpressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.RegularExpressions.Tests  Total: 15089, Errors: 0, Failed: 1, Skipped: 0, Time: 271.235s
```

Rolling build: https://dnceng.visualstudio.com/public/_build/results?buildId=1712332&view=ms.vss-test-web.build-test-results-tab&runId=46549622&resultId=192267&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by joperezr** [comment]
@stephentoub FYI

**Comment by stephentoub** [comment]
This test is disabled.  When are these errors from?
https://github.com/dotnet/runtime/blob/c59e1c4dc6728cebf54c36e00191f7c3630058d8/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Match.Tests.cs#L1051

**Comment by joperezr** [comment]
Oh right, these failures are from a rolling build on Tuesday so that was before you disabled it. This is fine to close as a dupe then.
