### ISSUE TITLE
ILCompiler does not recognize "sha1" and "sha2" Instruction Sets

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#68132]
Repro:

```cs
using System;

namespace aotRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"base: {System.Runtime.Intrinsics.Arm.ArmBase.IsSupported}");
            Console.WriteLine($"neon: {System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported}");
            Console.WriteLine($"aes: {System.Runtime.Intrinsics.Arm.Aes.IsSupported}");
            Console.WriteLine($"crc: {System.Runtime.Intrinsics.Arm.Crc32.IsSupported}");
            Console.WriteLine($"dotprod: {System.Runtime.Intrinsics.Arm.Dp.IsSupported}");
            Console.WriteLine($"rdma: {System.Runtime.Intrinsics.Arm.Rdm.IsSupported}");
            Console.WriteLine($"sha1: {System.Runtime.Intrinsics.Arm.Sha1.IsSupported}");
            Console.WriteLine($"sha2: {System.Runtime.Intrinsics.Arm.Sha256.IsSupported}");			
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>win-arm64</RuntimeIdentifier>
     <PlatformTarget>ARM64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
    <IlcArg Include="--instructionset:sha1,sha2" />
  </ItemGroup>
</Project>
```

```cmd
dotnet run -c Release
```

```log
base: True
neon: True
aes: True
crc: True
dotprod: False
rdma: False
sha1: True
sha2: True
```

```cmd
dotnet publish -c Release
```

```log
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
EXEC : error : Specified method is not supported. [C:\Projects\repro\aotRepro\aotRepro.csproj]
  System.NotSupportedException: Specified method is not supported.
     at ILCompiler.HardwareIntrinsicHelpers.Arm64IntrinsicConstants.FromInstructionSetFlags(InstructionSetFlags instruc
  tionSets)
     at ILCompiler.ExpectedIsaFeaturesRootProvider.ILCompiler.ICompilationRootProvider.AddCompilationRoots(IRootingServ
  iceProvider rootProvider)
     at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 c
  ompilationRoots, ILProvider ilProvider, DebugInformationProvider debugInformationProvider, DevirtualizationManager de
  virtualizationManager, IInliningPolicy inliningPolicy, Logger logger)
     at ILCompiler.ILScannerBuilder.ToILScanner()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
```

FWIW I took the names from https://github.com/dotnet/runtime/blob/ce61c09a5f6fc71d8f717d3fc4562f42171869a0/src/coreclr/tools/Common/JitInterface/CorInfoInstructionSet.cs#L739-L740

cc @jkotas

**Comment by danmoseley** [comment]
Should "OptimizeCoreRT" be changed?

**Comment by jkotas** [comment]
> Should "OptimizeCoreRT" be changed?

https://github.com/dotnet/runtime/pull/68151
