### ISSUE TITLE
Test failure baseservices/TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#68197]
Run: [runtime-coreclr gcstress-extra 20220417.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1723079&view=ms.vss-test-web.build-test-results-tab&runId=46752164&paneView=debug&resultId=109518)

Failed test:
```
coreclr OSX arm64 Checked gcstress0xc_jitminopts_heapverify1 @ OSX.1200.ARM64.Open

- baseservices/TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.sh

```
**Error message:**
```
Unhandled exception. System.IO.FileLoadException: The given assembly name was invalid.
File name: 'CollectibleDerivedAssembly0'
at System.Reflection.AssemblyNameParser.Parse()
at System.Reflection.AssemblyName..ctor(String assemblyName)
at TieredVtableMethodTests.CreateCollectibleDerived()
at TieredVtableMethodTests.RunCollectibleIterations()
at TieredVtableMethodTests.Main()
[createdump] task_for_pid(33061) FAILED 5 (os/kern) failure
/private/tmp/helix/working/B3E809D8/w/B04409EA/e/baseservices/TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.sh: line 373: 33061 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/B3E809D8/w/B04409EA/uploads/Reports/baseservices.TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B3E809D8/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false TieredVtableMethodTests.dll ''
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/B3E809D8/p
/private/tmp/helix/working/B3E809D8/w/B04409EA/e/baseservices/TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_TieredCompilation._TieredVtableMethodTests_TieredVtableMethodTests_._TieredVtableMethodTests_TieredVtableMethodTests_sh()
```

**Comment by AaronRobinsonMSFT** [comment]
@trylek or @jkoritzinsky Could this be related to the consolidation of tests?

**Comment by trylek** [comment]
I don't think so, tests under baseservices still run using the legacy XUnit wrappers.

**Comment by mangod9** [comment]
Closing this as no repro for now. Please reopen if this is still failing.
