### ISSUE TITLE
COMPlus_EnableSSE3=0 does not set Ssse3.IsSupported to false

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#68245]
I set this variable, then ran a build to see what happens.
```
C:\git\runtime>set COMPlus_EnableSSE3=0

C:\git\runtime>build clr+libs+libs.tests -rc release -lc debug -test
```

```
   ---> System.NotSupportedException: Operation is not supported on this platform. The unsupported member type is located on type 'Microsoft.DotNet.ToolPackage.LocalToolsResolverCache+CacheRow[]'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
     at System.Runtime.Intrinsics.X86.Ssse3.Shuffle(Vector128`1 value, Vector128`1 mask)
     at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(Byte* pData, UIntPtr lengthInBytes)
     at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode(ReadOnlySpan`1 data)
     at System.Text.Encodings.Web.DefaultJavaScriptEncoder.FindFirstCharacterToEncodeUtf8(ReadOnlySpan`1 utf8Text)
     at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.DeterminePropertyName()
...
```
yet this path is protected behind
```
            if (Ssse3.IsSupported || (AdvSimd.Arm64.IsSupported && BitConverter.IsLittleEndian))
            {
```

**Comment by jkotas** [comment]
I assume that you are using .NET 6 SDK for the build and the crash happens during the build, not while running the tests.

It is a known issue in .NET 6: https://github.com/dotnet/runtime/issues/60035 . Fixed for .NET 7.

**Comment by tannergooding** [comment]
Should we consider backporting #60035 to .NET 6 since it's LTS?

**Comment by danmoseley** [comment]
Oh - nuts. I forgot (again) that we had not moved to the 7.0 SDK.

The only argument I can think of for back porting is that it makes it possible to due perf comparisons. But this seems relatively low importance and #62420 seems a large change.

**Comment by danmoseley** [comment]
And set COMPlus_EnableAVX=0 does work.
