### ISSUE TITLE
Extract_HardLinkEntry_TargetInsideDirectory test from System.Formats.Tar.Tests fails on Android/iOS/tvOS

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#68360]
Newly added test from https://github.com/dotnet/runtime/pull/67883 fails on runtime-extra-platfroms.
I haven't investigated whether it is expected, just filing this so I can disable the test with ActiveIssue.

Android fails with 
```
System.UnauthorizedAccessException : Access to the path '/data/user/0/net.dot.System.Formats.Tar.Tests/cache/qtsmyi3v.nmj/link' is denied.
---- System.IO.IOException : Permission denied


Stack trace
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Int32 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.Formats.Tar.TarEntry.ExtractAsHardLink(String targetFilePath, String hardLinkFilePath)
   at System.Formats.Tar.TarEntry.ExtractToFileInternal(String filePath, String linkTargetPath, Boolean overwrite)
   at System.Formats.Tar.TarEntry.ExtractRelativeToDirectory(String destinationDirectoryPath, Boolean overwrite)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternal(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen)
   at System.Formats.Tar.TarFile.ExtractToDirectory(Stream source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_LinkEntry_TargetInsideDirectory_Internal(TarEntryType entryType) in /_/src/libraries/System.Formats.Tar/tests/TarFile/TarFile.ExtractToDirectory.Stream.Tests.cs:line 123
   at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_HardLinkEntry_TargetInsideDirectory() in /_/src/libraries/System.Formats.Tar/tests/TarFile/TarFile.ExtractToDirectory.Stream.Tests.cs:line 101
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* byrefParameters, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
----- Inner Stack Trace -----
```

iOS/tvOS Simulators fail with

```
System.IO.IOException : Extracting the Tar entry '/Users/helix-runner/Library/Developer/CoreSimulator/Devices/11416593-2690-443B-964F-E9F6694BA19A/dat' would have resulted in a link target outside the specified destination directory: '/Users/helix-runner/Library/Developer/CoreSimulator/Devices/11416593-2690-443B-964F-E9F6694BA19A/data/Containers/Data/Application/1BD07C3B-0285-4EAB-943A-2BBFDD9E63A5/tmp/f2gsvib5.4m4/'


Stack trace
   at System.Formats.Tar.TarEntry.<ExtractRelativeToDirectory>g__GetSanitizedFullPath|34_0(String destinationDirectoryFullPath, String path, String exceptionMessage)
   at System.Formats.Tar.TarEntry.ExtractRelativeToDirectory(String destinationDirectoryPath, Boolean overwrite)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternal(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen)
   at System.Formats.Tar.TarFile.ExtractToDirectory(Stream source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_LinkEntry_TargetInsideDirectory_Internal(TarEntryType entryType)
   at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_HardLinkEntry_TargetInsideDirectory()
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* byrefParameters, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
```

FYI @carlossanlop

**Comment by stephentoub** [comment]
I expect this is the same root cause as what's being fixed in https://github.com/dotnet/runtime/pull/68361.

**Comment by akoeplinger** [comment]
I don't think it's the same issue.

**Comment by danmoseley** [comment]
@carlossanlop

**Comment by carlossanlop** [comment]
I think the user we use to execute tests in Android/iOS/tvOS does not have permission to create symbolic links in those operating systems. I will have to use elevation in those OS.

**Comment by carlossanlop** [comment]
Test failure has been fixed, and the test method has been reenabled.

**Comment by karelz** [comment]
The test is failing again -- @carlossanlop can you please disable it again and take a look?

Failures since 6/17 - [query in ranfo](https://runfo.azurewebsites.net/search/tests/?q=started%3A2022-06-17+definition%3Aruntime-extra-platforms+name%3A%22system.formats.tar.tests.tarfile_extracttodirectory_stream_tests.extract_hardlinkentry_targetinsidedirectory%22)
- 6/19: 43 failures

Rolling builds:
- [1832161](https://runfo.azurewebsites.net/view/build/?number=1832161) (6/18 AM) - 3 failures:
   - net7.0-iOSSimulator-Release-x64-Mono_Release-OSX.1015.Amd64.Open
   - net7.0-tvOSSimulator-Release-x64-Mono_Release-OSX.1015.Amd64.Open
   - net7.0-tvOS-Release-arm64-Mono_Release-OSX.1015.Amd64.AppleTV.Open

**Comment by karelz** [comment]
Also, test System.Formats.Tar.Tests.TarReader_ExtractToFile_Tests.**ExtractToFile_SpecialFile_Unelevated_Throws** fails as well with similar error to the 1st one report in the top post:

```
System.UnauthorizedAccessException : Access to the path '/private/var/mobile/Containers/Data/Application/607B5A9D-8D94-42C4-8CCD-54BCE7B1B2E9/tmp/j2osgcp1.kpt/output' is denied.
---- System.IO.IOException : Operation not permitted

  at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.Formats.Tar.TarEntry.ExtractAsFifo(String destinationFileName)
   at System.Formats.Tar.TarEntry.ExtractToFileInternal(String filePath, String linkTargetPath, Boolean overwrite)
   at System.Formats.Tar.TarEntry.ExtractToFile(String destinationFileName, Boolean overwrite)
   at System.Formats.Tar.Tests.TarReader_ExtractToFile_Tests.ExtractToFile_SpecialFile_Unelevated_Throws()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

**Comment by karelz** [comment]
@carlossanlop the main issue with test Extract_HardLinkEntry_TargetInsideDirectory was addressed. Thanks!

However, the second similar issue with test **ExtractToFile_SpecialFile_Unelevated_Throws** is still happening -- see above https://github.com/dotnet/runtime/issues/68360#issuecomment-1159654910

Reopening to keep tracking it. Feel free to split it into another issue if it is more convenient for you.

**Comment by karelz** [comment]
@carlossanlop given that it fails in each CI run, please disable the test ASAP unless you have high confidence fix. Thanks!

**Comment by adamsitnik** [comment]
I've opened #71258 to disable this test for tvOS

**Comment by ilonatommy** [comment]
I'm facing a very similar issue on unconnected PRs ([Run](https://dev.azure.com/dnceng/public/_build/results?buildId=1867809)) on:
- net7.0-Linux-Release-x64-Mono_Release_LinuxBionic-Ubuntu.1804.Amd64.Android.29.Open
- net7.0-Linux-Release-arm64-Mono_Release_LinuxBionic-Windows.10.Amd64.Android.Open
The error:
```
System.UnauthorizedAccessException : Access to the path '/data/local/tmp/htuovavi.iw1/output' is denied.
---- System.IO.IOException : Permission denied

 at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory) in /_/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 16
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory) in /_/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 42
   at Interop.CheckIo(Int32 result, String path, Boolean isDirectory) in /_/src/libraries/Common/src/Interop/Unix/Interop.IOErrors.cs:line 58
   at System.Formats.Tar.TarEntry.ExtractAsFifo(String destinationFileName) in /_/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.Unix.cs:line 31
   at System.Formats.Tar.TarEntry.CreateNonRegularFile(String filePath, String linkTargetPath) in /_/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.cs:line 461
   at System.Formats.Tar.TarEntry.ExtractToFileInternalAsync(String filePath, String linkTargetPath, Boolean overwrite, CancellationToken cancellationToken) in /_/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.cs:line 425
   at System.Formats.Tar.TarEntry.ExtractToFileAsync(String destinationFileName, Boolean overwrite, CancellationToken cancellationToken) in /_/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.cs:line 261
   at System.Formats.Tar.Tests.TarReader_TarEntry_ExtractToFileAsync_Tests.SpecialFile_Unelevated_Throws_Async() in /_/src/libraries/System.Formats.Tar/tests/TarReader/TarReader.TarEntry.ExtractToFileAsync.Tests.Unix.cs:line 37
   at System.Formats.Tar.Tests.TarReader_TarEntry_ExtractToFileAsync_Tests.SpecialFile_Unelevated_Throws_Async() in /_/src/libraries/System.Formats.Tar/tests/TarReader/TarReader.TarEntry.ExtractToFileAsync.Tests.Unix.cs:line 41
   at System.Formats.Tar.Tests.TarReader_TarEntry_ExtractToFileAsync_Tests.SpecialFile_Unelevated_Throws_Async() in /_/src/libraries/System.Formats.Tar/tests/TarReader/TarReader.TarEntry.ExtractToFileAsync.Tests.Unix.cs:line 41
```
It looks the same as above, just different platforms.

**Comment by karelz** [comment]
Test is disabled, not blocking CI anymore -> removing blocking-clean-ci label.
