### ISSUE TITLE
Enterprise authentication tests are failing with PlatformNotSupportedException

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#68366]
https://dnceng.visualstudio.com/public/_build/results?buildId=1730894&view=logs&j=47c231e8-52e2-5eb6-8574-66afcfcee82a&t=df5b78b1-c065-5bb1-4636-fc7a07ab8e6a

```
   Starting:    System.Net.Http.Enterprise.Tests (parallel test collections = on, max threads = 4)
      System.Net.Http.Enterprise.Tests.HttpClientAuthenticationTest.HttpClient_ValidAuthentication_Success(url: "http://apacheweb.linux.contoso.com/auth/kerberos/", useDomain: False, useAltPort: False) [STARTING]
  Unhandled exception. System.PlatformNotSupportedException: Requested protection level is not supported with the GSSAPI implementation currently installed.
     at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, Byte[] incomingBlob, ChannelBinding channelBinding, Byte[]& resultBlob, ContextFlagsPal& contextFlags) in /repo/src/libraries/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 384
     at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode) in /repo/src/libraries/Common/src/System/Net/NTAuthentication.Common.cs:line 215
     at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean thrownOnError) in /repo/src/libraries/Common/src/System/Net/NTAuthentication.Common.cs:line 201
     at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob) in /repo/src/libraries/Common/src/System/Net/NTAuthentication.Common.cs:line 182
     at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken) in /repo/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs:line 198
     at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /repo/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1033
     at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationTo
```

This seems to be regression from https://github.com/dotnet/runtime/pull/66879 @filipnavara. I look at the change again and nothing obvious pop up but I sync code just before the change and everything would pass. 

It seems to fail on chat that confidentiality is set but was not requested. I don't know why that would matter but I would not expect behavior differences in Kerberos from the managed NTLM. 

The test should runable again with #68311

**Comment by filipnavara** [comment]
I will have a look, probably on Monday. The weird thing is that the PR should not change anything at all for Linux builds.

**Comment by filipnavara** [comment]
Ah, actually there's the change to verify the last token after successful authentication (in AuthenticationHelper.NtAuth.cs). That could be related.

**Comment by filipnavara** [comment]
FWIW here's the [commit](https://github.com/dotnet/runtime/commit/7fc299549dc272a7e3abd7b89f78b39cc7d034b2) that added the check. It may have just never been run for the HTTP authentication because of the ignored last negotiation token. Furthermore, it is totally valid and normal for NTLM to upgrade to confidentiality.

**Comment by filipnavara** [comment]
I managed to reproduce this locally. Removing the extra check from 7fc299549dc272a7e3abd7b89f78b39cc7d034b2, as done in #68700, does make the problem go away. I'll do some additional tracing to see what is happening.

**Comment by wfurt** [comment]
I think it would be OK to have confidentiality on if we have reasonable confidence this is caused by the MIC calculation. 
And we will have to anyway since the support is only in 1.14 and above.

**Comment by wfurt** [comment]
I think we build on Centos7 but I'm not sure how this would work on RHEL7 since we use same binaries. 
cc: @tmds

**Comment by filipnavara** [comment]
> I think we build on Centos7 but I'm not sure how this would work on RHEL7 since we use same binaries.

That's what I am seeing, actually. The builds use the runtime `dlopen`/`dlsym` shim for all the APIs. The two optional symbols don't exist on RHEL7 which is already tested on the CI. I modified to code in #70447 to support runtime detection of the APIs, as long as the compilation of the GSS shim is done with KRB5>1.14.
