### ISSUE TITLE
Test failure Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#68453]
Run: [runtime-coreclr libraries-jitstress 20220423.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1734162&view=ms.vss-test-web.build-test-results-tab&runId=46957508&paneView=debug&resultId=103389)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open

- Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload

```
**Error message:**
```
System.IO.IOException : The requested operation cannot be performed on a file with a user-mapped section open. : 'D:\Users\runner\AppData\Roaming\Microsoft\UserSecrets\Microsoft.Extensions.Hosting.Unit.Tests\secrets.json'


Stack trace
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs:line 110
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs:line 44
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding) in /_/src/libraries/System.Private.CoreLib/src/System/IO/File.cs:line 796
   at Microsoft.Extensions.Hosting.Tests.HostTests.<CreateDefaultBuilder_SecretsDoesReload>g__SaveRandomSecret|11_0(String secretPath) in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs:line 281
   at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_SecretsDoesReload() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs:line 303
--- End of stack trace from previous location ---
```

**Comment by danmoseley** [comment]
Test writes to the secrets.json, registers it with the host, then writes it again. There is a race, after the first write the file change notification must occur and be handled, and the host also then waits another 250ms:

https://github.com/dotnet/runtime/blob/2309816c7b37c0f221dc60456c23787246ab3c65/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs#L38

One fix would be to wait 500ms or so before writing to it the second time. Better would be to wait for the reload -- it looks like ConfigurationReloadToken may be helpful.

**Comment by eerhardt** [comment]
Does this only fail in arm64 JIT stress runs? Is it because the runtime is so slow in this configuration that it doesn't fail anywhere else?

**Comment by danmoseley** [comment]
Jit Stress can apparently be slow, as it has tended to expose this kind of timing bug in tests.

**Comment by BruceForstall** [comment]
Note that jitminopts mode is particularly slow (it disables all JIT optimization).
