### ISSUE TITLE
WasmTestOnBrowser-System.CodeDom.Tests failing in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#68477]
This is failing on all jobs.
```
[01:14:21] info: Starting:    System.CodeDom.Tests.dll
[01:14:27] fail: [FAIL] System.CodeDom.Compiler.Tests.CompilerResultsTests.CompiledAssembly_GetWithPathToAssemblySet_ReturnsExpectedAssembly
[01:14:27] info: System.IO.FileNotFoundException : Could not load file or assembly '/System.CodeDom.Tests.dll'. The system cannot find the file specified.
[01:14:27] info:    at System.Reflection.Assembly.LoadFile(String path)
[01:14:27] info:    at System.CodeDom.Compiler.CompilerResults.get_CompiledAssembly()
[01:14:27] info:    at System.CodeDom.Compiler.Tests.CompilerResultsTests.CompiledAssembly_GetWithPathToAssemblySet_ReturnsExpectedAssembly()
[01:14:27] info:    at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* byrefParameters, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
```

**Comment by jkotas** [comment]
Introduced by https://github.com/dotnet/runtime/pull/68203
