### ISSUE TITLE
[wasm-mt] PInvokeTableGenerator doesn't like the wasm-mt-eventpipe sample

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#68498]
Build the runtime with `/p:WasmEnableThreads=true`, try to build the wasm-mt-eventpipe wasm sample with AOT compilation:

```
src/mono/wasm/build/WasmApp.Native.targets(276,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "PInvokeTableGenerator" task failed unexpectedly.
System.IO.FileLoadException: The assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already loaded been loaded into this MetadataLoadContext.
   at System.Reflection.MetadataLoadContext.LoadFromStreamCore(Stream peStream)
   at PInvokeTableGenerator.GenPInvokeTable(String[] pinvokeModules, String[] assemblies) in /_/src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:line 68
   at PInvokeTableGenerator.Execute() in /_/src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs:line 45
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

We're probably pulling in a ref assembly into the build.

**Comment by maraf** [comment]
> but maybe they don't need to be `PrivateAssets="all"`

The opposite is the true. It was missing in one csproj.
