### ISSUE TITLE
Test failure System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#68532]
Run: [runtime-coreclr libraries-jitstress 20220425.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1736001&view=ms.vss-test-web.build-test-results-tab&runId=46986298&paneView=debug&resultId=112865)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject

```
**Error message:**
```
Did not observe an error event within 500ms and 3 attempts.
Expected: True
Actual:   False


Stack trace
   at System.IO.Tests.FileSystemWatcherTest.ExpectError(FileSystemWatcher watcher, Action action, Action cleanup, Int32 attempts) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 369
   at System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.InternalBufferSize.cs:line 84
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 383
```

**Comment by Jozkee** [comment]
This test was added in https://github.com/dotnet/runtime/pull/53151, it appears that on `RecreateWatcher`, we don't set `Changed` on the new FSW, 
https://github.com/dotnet/runtime/blob/b490c47a7915a3e71f0a748c2e966ec90801c744/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs#L468-L478

which in this test is used to wait for the action to finish after the 10 times it changes the file, 
https://github.com/dotnet/runtime/blob/b490c47a7915a3e71f0a748c2e966ec90801c744/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.InternalBufferSize.cs#L106-L112
https://github.com/dotnet/runtime/blob/b490c47a7915a3e71f0a748c2e966ec90801c744/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.InternalBufferSize.cs#L93-L94

so that means that we only achieve it on the first attempt, but not for subsequent ones.

**Comment by Jozkee** [comment]
cc @thomsj @stephentoub

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20221031.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67706&view=ms.vss-test-web.build-test-results-tab&runId=1378080&resultId=115183&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject
```
**Error message:**
```
Did not observe an error event within 500ms and 3 attempts.
Expected: True
Actual:   False


Stack trace
   at System.IO.Tests.FileSystemWatcherTest.ExpectError(FileSystemWatcher watcher, Action action, Action cleanup, Int32 attempts) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 369
   at System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.InternalBufferSize.cs:line 82
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20230208.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=165305&view=ms.vss-test-web.build-test-results-tab&runId=3361464&resultId=114822&paneView=debug)

Failed test:
```
net8.0-windows-Release-x86-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open

- System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject
```
**Error message:**
```
Did not observe an error event within 500ms and 3 attempts.
Expected: True
Actual:   False


Stack trace
   at System.IO.Tests.FileSystemWatcherTest.ExpectError(FileSystemWatcher watcher, Action action, Action cleanup, Int32 attempts) in /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs:line 369
   at System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.InternalBufferSize.cs:line 82
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```
