### ISSUE TITLE
The "MonoAOTCompiler" task failed unexpectedly

### ISSUE THREAD

**Issue by ashotkhachatryan** [dotnet/runtime#68633]
### Description

AOT build fails for simple Blazor WebAssembly App when using .NET 7 Preview 3 SDK.

```
Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
AOT'ing 28 assemblies
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.3.22175.4\Sdk\WasmApp.Native.targets(567,5): Error MSB4018: The "MonoAOTCompiler" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reflection.Metadata, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MonoAOTCompiler.FilterAssemblies(IEnumerable`1 assemblies)
   at MonoAOTCompiler.ExecuteInternal()
   at MonoAOTCompiler.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Reproduction Steps

- Install .NET 7 Preview 3 SDK and wasm-tools workload
- Create a new 'Blazor WebAssembly App' with Visual Studio 2022 Preview
- Publish the app using AOT compilation

### Expected behavior

Publish succeeds.

### Actual behavior

Publish fails.

**Comment by lewing** [comment]
There was an issue in the preview3 packages.  You should be able to build/publish from the command or by using one of several work arounds.

@radical have we documented the workarounds?

**Comment by lewing** [comment]
This is fixed in preview 4 but we can keep this open until that is released.

**Comment by radical** [comment]
To workaround this, add the following to your csproj:

```xml
  <Target Name="Workaround" BeforeTargets="_WasmAotCompileApp" Condition="'$(_WasmShouldAOT)' == 'true'">
    <PropertyGroup>
      <_JsonContents>
      <![CDATA[
        {
          "runtimeOptions": {
            "tfm": "net7.0",
            "framework": {
              "name": "Microsoft.NETCore.App",
              "version": "7.0.0"
            },
            "configProperties": {
              "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
            }
          }
        }
        ]]>
      </_JsonContents>
    </PropertyGroup>
    <WriteLinesToFile Lines="$(_JsonContents)" File="$(OutDir)input.ignore.me.json" Overwrite="true" />
    <ItemGroup>
      <_ReservedProperty Include="RUNTIME_IDENTIFIER"/>
      <_ReservedProperty Include="APP_CONTEXT_BASE_DIRECTORY"/>
    </ItemGroup>

    <RuntimeConfigParserTask
        RuntimeConfigFile="$(OutDir)input.ignore.me.json"
        OutputFile="$(OutDir)output.ignore.me.json"
        RuntimeConfigReservedProperties="@(_ReservedProperty)">
    </RuntimeConfigParserTask>
  </Target>
```

**Comment by directhex** [comment]
Preview 4 was released on May 10th, so as per @lewing's comments I'm closing this.
