### ISSUE TITLE
CI Failure: Build Browser wasm Linux Release LibraryTests

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#68718]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1743690&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259

Only seen this once today, but didnt find an issue related to this. 
```
[09:10:22] crit: System.AggregateException: One or more errors occurred. (Built-in type converters have not been initialized. There is no converter available for type 'Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmLogMessage'. To root all built-in converters, use a 'JsonSerializerOptions'-based method of the 'JsonSerializer'.)
                  ---> System.NotSupportedException: Built-in type converters have not been initialized. There is no converter available for type 'Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmLogMessage'. To root all built-in converters, use a 'JsonSerializerOptions'-based method of the 'JsonSerializer'.
                    at System.Text.Json.ThrowHelper.ThrowNotSupportedException_BuiltInConvertersNotRooted(Type type)
                    at System.Text.Json.JsonSerializerOptions.GetConverterInternal(Type typeToConvert)
                    at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
                    at System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
                    at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type type, JsonSerializerOptions options)
                    at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type type)
                    at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
                    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType)
                    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.InvokeInternal(String message) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 70
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.Invoke(String message) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 52
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunSeleniumLogMessagePump(IWebDriver driver, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 225
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.<>c__DisplayClass6_0.<RunTestsWithWebDriver>b__0() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 69
                    at System.Threading.Tasks.Task.InnerInvoke()
                    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                    --- End of inner exception stack trace ---
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunTestsWithWebDriver(DriverService driverService, IWebDriver driver) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 128
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 77
                    at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 145
XHarness exit code: 71 (GENERAL_FAILURE)
```

|Build|Kind|Start Time|
|---|---|---|
[1743690](https://dev.azure.com/dnceng/public/_build/results?buildId=1743690)|Rolling|2022-29-04|

**Comment by radical** [comment]
@jakobbotsch Any idea if this has been hit after the issue was opened? I think it might have been fixed by one of the update PRs. I'm not able to query `runfo` for this.

**Comment by jakobbotsch** [comment]
@radical I haven't seen it in the rolling builds at least. Removing the blocking label. Let's close it and reopen it if we see another hit.
