### ISSUE TITLE
Helix tests failing during reporting with Permission Denied on run.py.log

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#68715]
Sample error:
```
Traceback (most recent call last):
  File "/root/helix/work/correlation/reporter/run.py", line 13, in <module>
    from test_results_reader import read_results
  File "/root/helix/work/correlation/reporter/test_results_reader/__init__.py", line 3, in <module>
    from helix.public import TestResult, TestResultAttachment
  File "/root/helix/scripts/helix/public/__init__.py", line 5, in <module>
    import helix.event
  File "/root/helix/scripts/helix/event.py", line 7, in <module>
    import helix.logs
  File "/root/helix/scripts/helix/logs.py", line 43, in <module>
    rotating_file_handler = RotatingFileHandler(log_file_path, maxBytes=20000000, backupCount=10)
  File "/usr/lib/python3.7/logging/handlers.py", line 147, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/root/helix/logs/run.py.log'
```

Most likely this is https://github.com/dotnet/arcade/issues/9208 cc @MattGal

**Comment by mangod9** [comment]
This is being tracked with: https://github.com/dotnet/arcade/issues/9208

**Comment by jakobbotsch** [comment]
I believe this has now been fixed, and I haven't seen these in the past two rolling builds.

**Comment by MattGal** [comment]
> I believe this has now been fixed, and I haven't seen these in the past two rolling builds.

Correct; the docker image that was causing this has been updated (though unsure if runtime is using it, yet) and we hotfixed this so it shouldn't be possible any more on 5/3.

**Comment by lewing** [comment]
thanks for tracking this down @MattGal
