### ISSUE TITLE
GetProcessesByName_NullEmpty_ReturnsAllProcesses fails on Android

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#68838]
https://dev.azure.com/dnceng/public/_build/results?buildId=1749724&view=ms.vss-test-web.build-test-results-tab&runId=47207876&paneView=debug&resultId=116967

net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open
and

net7.0-MacCatalyst-Release-x64-Mono_Release-OSX.1015.Amd64.Open
```

      <test name="System.Diagnostics.Tests.ProcessTests.GetProcessesByName_NullEmpty_ReturnsAllProcesses(name: null)" type="System.Diagnostics.Tests.ProcessTests" method="GetProcessesByName_NullEmpty_ReturnsAllProcesses" time="0.0090025" result="Fail">
        <failure exception-type="Xunit.Sdk.InRangeException">
          <message><![CDATA[Assert.InRange() Failure\r\nRange:  (2 - 2147483647)\r\nActual: 1]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_NullEmpty_ReturnsAllProcesses(String name) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1218
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* byrefParameters, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)]]></stack-trace>
        </failure>


              <test name="System.Diagnostics.Tests.ProcessTests.GetProcessesByName_NullEmpty_ReturnsAllProcesses(name: \&quot;\&quot;)" type="System.Diagnostics.Tests.ProcessTests" method="GetProcessesByName_NullEmpty_ReturnsAllProcesses" time="0.0021674" result="Fail">
        <failure exception-type="Xunit.Sdk.InRangeException">
          <message><![CDATA[Assert.InRange() Failure\r\nRange:  (2 - 2147483647)\r\nActual: 1]]></message>
          <stack-trace><![CDATA[   at System.Diagnostics.Tests.ProcessTests.GetProcessesByName_NullEmpty_ReturnsAllProcesses(String name) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1218
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* byrefParameters, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)]]></stack-trace>
        </failure>
```
cc @stephentoub related to https://github.com/dotnet/runtime/pull/68705?

cc @radical 

https://github.com/dotnet/runtime/pull/67771

**Comment by danmoseley** [comment]
Perhaps this should include Android and Catalyst
https://github.com/dotnet/runtime/pull/68705/files#diff-f756f37255fb9daf54bb56c6b6653e2dd6b5acb1103d60844ab08433e8053fe5R1211

**Comment by danmoseley** [comment]
Ah, I didn't catch up to date. Seems this was fixed https://github.com/dotnet/runtime/pull/68830
