### ISSUE TITLE
Test failure Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#68880]
Run: [runtime-coreclr jitstress-isas-x86 20220430.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149150&resultId=101045&paneView=debug)

Failed  test:
```
coreclr windows x64 Checked jitstress_isas_2_x86_nosse3 @ Windows.10.Amd64.Open

- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x64 Checked jitstress_isas_2_x86_nosse3_4 @ Windows.10.Amd64.Open

- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x86 Checked jitstress_isas_1_x86_nossse3 @ Windows.10.Amd64.Open
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x86 Checked jitstress_isas_1_x86_nosse3_4 @ Windows.10.Amd64.Open
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x86 Checked jitstress_isas_1_x86_nosse3 @ Windows.10.Amd64.Open
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x86 Checked jitstress_isas_x86_nosse3_4 @ Windows.10.Amd64.Open
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x86 Checked jitstress_isas_x86_nosse3 @ Windows.10.Amd64.Open
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

coreclr windows x64 Checked jitstress_isas_x86_nossse3 @ Windows.10.Amd64.Open
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd
- Interop\\COM\\NETClients\\Primitives\\NETClientPrimitivesInALC\\NETClientPrimitivesInALC.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\A7450908\w\BCE50A54\uploads\Reports\Interop.COM\NETClients\Primitives\NETClientPrimitivesInALC\NETClientPrimitivesInALC.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A7450908\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  NETClientPrimitivesInALC.dll
Numeric RNG seed: 37
Byte test invariant: 101 + 70 = 171
Int16 test invariant: 22885 + -29882 = -6997
UInt16 test invariant: 22885 + 35654 = 58539
Int32 test invariant: 120215909 + 1447004998 = 1567220907
UInt32 test invariant: 120215909 + 1447004998 = 1567220907
Int64 test invariant: 120215909 + 1447004998 = 1567220907
UInt64 test invariant: 120215909 + 1447004998 = 1567220907
Single test invariant: 1202159.1 + 14470051 = 15672210
Double test invariant: 1202159.09 + 14470049.98 = 15672209.07
Int32 11 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 = 66
Int32 12 test invariant: 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12 = 78
Byte[] marshalling
Int16[] marshalling
UInt16[] marshalling
Int32[] marshalling
UInt32[] marshalling
Int64[] marshalling
UInt64[] marshalling
Single[] marshalling
Double[] marshalling
Marshal strings as LPStr
Test object interop failure: System.PlatformNotSupportedException: Operation is not supported on this platform.
at System.Runtime.Intrinsics.X86.Ssse3.Shuffle(Vector1281 value, Vector1281 mask)
at System.SpanHelpers.Reverse(Char& buf, UIntPtr length)
at NetClient.StringTests.Reverse(String s)
at NetClient.StringTests.Marshal_LPString()
at NetClient.StringTests.Run()
at NetClient.Program.RunTests()
at NetClient.Program.Main(String[] doNotUse)
Unload succeeded - C:\h\w\A7450908\w\BCE50A54\e\Interop\COM\NETClients\Primitives\NETClientPrimitivesInALC\NETClientPrimitives.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A7450908\p
C:\h\w\A7450908\w\BCE50A54\e\Interop\COM\NETClients\Primitives\NETClientPrimitivesInALC\NETClientPrimitivesInALC.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._NETClients_Primitives_NETClientPrimitivesInALC_NETClientPrimitivesInALC_._NETClients_Primitives_NETClientPrimitivesInALC_NETClientPrimitivesInALC_cmd()
```
Queued | OS | Arch | Pipeline
-- | -- | -- | --
2022-05-01T06:01:27.297Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149394&resultId=101716&paneView=debug)
2022-05-01T05:36:41.64Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149352&resultId=101716&paneView=debug)
2022-05-01T05:33:41.431Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149346&resultId=101054&paneView=debug)
2022-05-01T05:25:02.888Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149304&resultId=101038&paneView=debug)
2022-05-01T04:49:41.976Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149178&resultId=101714&paneView=debug)
2022-05-01T04:43:42.237Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47149150&resultId=101045&paneView=debug)
2022-05-01T03:21:03.118Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47148828&resultId=101709&paneView=debug)
2022-05-01T03:06:09.659Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47148708&resultId=101498&paneView=debug)
2022-05-01T02:56:10.918Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47148666&resultId=101048&paneView=debug)
2022-05-01T02:34:44.433Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47148576&resultId=101055&paneView=debug)
2022-05-01T02:29:48.601Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47148556&resultId=102524&paneView=debug)
2022-05-01T02:26:51.37Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47148534&resultId=101273&paneView=debug)
2022-05-01T00:54:49.374Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47147562&resultId=101278&paneView=debug)
2022-05-01T00:49:52.446Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47147530&resultId=100807&paneView=debug)
2022-05-01T00:20:08.365Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47147094&resultId=101711&paneView=debug)
2022-05-01T00:18:41.65Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47147062&resultId=101700&paneView=debug)
2022-05-01T00:16:09.425Z | windows.10.amd64.open.rt | x86 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47146986&resultId=101700&paneView=debug)
2022-05-01T00:14:51.603Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=1745811&view=ms.vss-test-web.build-test-results-tab&runId=47146972&resultId=101707&paneView=debug)
2022-04-03T04:21:02.365Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr r2r-extra   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1697163&view=ms.vss-test-web.build-test-results-tab&runId=46295528&resultId=100661&paneView=debug)
2022-04-03T00:48:24.021Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1697031&view=ms.vss-test-web.build-test-results-tab&runId=46294584&resultId=100249&paneView=debug)
2022-04-02T23:35:43.867Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1697031&view=ms.vss-test-web.build-test-results-tab&runId=46294020&resultId=100784&paneView=debug)
2022-04-02T20:59:14.041Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x1000](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46293450&resultId=100238&paneView=debug)
2022-04-02T20:54:11.689Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x80](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46293412&resultId=100385&paneView=debug)
2022-04-02T20:47:32.844Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs0x10](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46293376&resultId=100240&paneView=debug)
2022-04-02T20:40:16.692Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs8](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46293354&resultId=100238&paneView=debug)
2022-04-02T19:17:45.894Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs3](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46292774&resultId=100384&paneView=debug)
2022-04-02T19:17:44.918Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs2](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46292778&resultId=100369&paneView=debug)
2022-04-02T19:17:43.989Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs4](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46292776&resultId=100368&paneView=debug)
2022-04-02T19:17:43.082Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress2-jitstressregs   Checked-jitstress2_jitstressregs1](https://dev.azure.com/dnceng/public/_build/results?buildId=1696887&view=ms.vss-test-web.build-test-results-tab&runId=46292772&resultId=100433&paneView=debug)
2022-04-02T05:58:23.522Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1696350&view=ms.vss-test-web.build-test-results-tab&runId=46284312&resultId=100240&paneView=debug)
2022-03-20T05:08:50.614Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1672206&view=ms.vss-test-web.build-test-results-tab&runId=45907220&resultId=100815&paneView=debug)
2022-03-20T02:53:49.325Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1672206&view=ms.vss-test-web.build-test-results-tab&runId=45906724&resultId=100538&paneView=debug)
2022-03-20T00:00:49.333Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1672206&view=ms.vss-test-web.build-test-results-tab&runId=45905696&resultId=100808&paneView=debug)
2022-03-13T05:38:43.65Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_2_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1660479&view=ms.vss-test-web.build-test-results-tab&runId=45717190&resultId=100804&paneView=debug)
2022-03-13T03:02:08.401Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1660479&view=ms.vss-test-web.build-test-results-tab&runId=45716574&resultId=100799&paneView=debug)
2022-03-13T00:47:35.705Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1660479&view=ms.vss-test-web.build-test-results-tab&runId=45715588&resultId=101035&paneView=debug)
2022-03-12T21:34:18.369Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_nosimd](https://dev.azure.com/dnceng/public/_build/results?buildId=1660479&view=ms.vss-test-web.build-test-results-tab&runId=45714274&resultId=100803&paneView=debug)

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib. This test is consistently failing in CI.  
@AndyAyersMS PTAL.

**Comment by AndyAyersMS** [comment]
We should disable the test for now.

**Comment by AndyAyersMS** [comment]
Likely introduced by https://github.com/dotnet/runtime/pull/64412.

**Comment by AndyAyersMS** [comment]
Seems like the logic is off here:

https://github.com/dotnet/runtime/blob/8626da3cc62d940513141b7c58c3495a87bb2bba/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs#L2377-L2400

and here

https://github.com/dotnet/runtime/blob/8626da3cc62d940513141b7c58c3495a87bb2bba/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Char.cs#L2064-L2087


We are checking if SSE2 is supported and then using SSSE3 instructions.
