### ISSUE TITLE
Mono JIT: Wrong stack size calculation of basic blocks

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#68905]
Originally, the issue was reported here: #34196 
where test case: [JIT/Regression/JitBlue/GitHub_23411/GitHub_23411.ilproj](https://github.com/dotnet/runtime/blob/2d4f2d0c8f60d5f49e39f3ddbe1824648ee2b306/src/tests/JIT/Regression/JitBlue/GitHub_23411/GitHub_23411.il) 
fails with `Invalid IL code` error message.

After further investigation - details reported here: https://github.com/dotnet/runtime/issues/34196#issuecomment-1100662244
it has been discovered that the root cause of failures is wrong stack size calculation of basic blocks in unstructured control flows with back edges.

Repro:
```
MONO_VERBOSE_METHOD=IsValidName artifacts/obj/mono/OSX.arm64.Debug/mono/mini/mono-sgen artifacts/tests/coreclr/OSX.arm64.Debug/JIT/Regression/JitBlue/GitHub_23411/GitHub_23411/GitHub_23411.dll
```

Output:
```
converting (in B33: stack: 0) IL_012f: pop       

Unhandled Exception:
System.InvalidProgramException: Invalid IL code in GitHub_23411:IsValidName (string): IL_012f: pop       


   at GitHub_23411.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in GitHub_23411:IsValidName (string): IL_012f: pop       


   at GitHub_23411.Main(String[] args)
```

**Comment by ivanpovazan** [comment]
Moving to 8.0.0

**Comment by ivanpovazan** [comment]
Moving to 9.0.0

**Comment by ivanpovazan** [comment]
The issue is present in a single unit test which includes unstructured control flows with back edges that is hand written.
An attempt to fix the issue with the interpreter showed that the runtime performance would be affected while we would gain very little value https://github.com/dotnet/runtime/pull/68855
Closing the issue as not planned.
