### ISSUE TITLE
X509Certificates failures in outer loop on CentOS 9

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#68911]
On CentOS 9 Stream, I am consistently seeing outer loop failures related to revocation.
For example:

<pre>Failed System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_IssuerUnrelatedOcsp(pkiOptions: IssuerRevocationViaCrl | OcspEverywhere) [2 s]
  Error Message:
   System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
                             ↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
                             ↑ (pos 2)) 
</pre>

This is even with `export OPENSSL_ENABLE_SHA1_SIGNATURES=1`, so I don't believe this is related to the SHA1 signature deprecation.

In the test above, we are expecting `X509ChainStatusFlags.RevocationStatusUnknown | X509ChainStatusFlags.OfflineRevocation` but are explicitly getting `X509ChainStatusFlags.Revoked`. This seems unlikely to be a transient issue.
/cc @tmds

**Comment by vcsjones** [comment]
For comparison, I don't see these failures on Ubuntu 22.04.

**Comment by vcsjones** [comment]
A further note: I cannot reproduce this against an OpenSSL that I have built myself.

Steps to reproduce:

Run `./dotnet.sh test src/libraries/System.Security.Cryptography.X509Certificates/tests /p:OuterLoop=true --filter DynamicRevocationTests`

Using the system-provided OpenSSL, I consistently see 5 tests with failures similar to above.

Next, checkout out `openssl/openssl`, build the 3.0.3 tag*, install it. Then, run the same tests with `export LD_LIBRARY_PATH=/usr/local/lib` so that .NET will pick up the custom OpenSSL build. These tests will now pass.

\* CentOS Stream 9 indicates that it has OpenSSL 3.0.1, but I don't know if that just means it's behind, or it's back porting fixes from .2 and .3 and freezing the version number.

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20220725.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1901188&view=ms.vss-test-web.build-test-results-tab&runId=49465530&paneView=debug&resultId=103903)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.2204.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-helix-arm64v8-20220504035342-1b9461f

- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_IssuerUnrelatedOcsp(pkiOptions: IssuerRevocationViaCrl | EndEntityRevocationViaOcsp)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_IssuerUnrelatedOcsp(pkiOptions: IssuerRevocationViaCrl | OcspEverywhere)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_IssuerUnrelatedOcsp(pkiOptions: OcspEverywhere)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_RootUnrelatedOcsp(pkiOptions: IssuerRevocationViaOcsp | AllEndEntityRevocation)
- System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_RootUnrelatedOcsp(pkiOptions: OcspEverywhere)
```

**Error message:**
```
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)) (Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)) (Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)) (Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)) (Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2))
---- Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)
---- Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)
---- Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)
---- Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)
---- Assert.Equal() Failure
↓ (pos 2)
Expected: [NoError, NoError, RevocationStatusUnknown | OfflineRevocati···
Actual:   [NoError, NoError, Revoked]
↑ (pos 2)


Stack trace
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 67
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.SimpleTest(PkiOptions pkiOptions, RunSimpleTest callback, String callerName, Boolean pkiOptionsInTestName) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1543
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.RevokeEndEntity_IssuerUnrelatedOcsp(PkiOptions pkiOptions) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 373
   at InvokeStub_DynamicRevocationTests.RevokeEndEntity_IssuerUnrelatedOcsp(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass19_0.<RevokeEndEntity_IssuerUnrelatedOcsp>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 429
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 67
----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass19_0.<RevokeEndEntity_IssuerUnrelatedOcsp>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 429
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 67
----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass19_0.<RevokeEndEntity_IssuerUnrelatedOcsp>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 429
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 67
----- Inner Stack Trace #4 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass19_0.<RevokeEndEntity_IssuerUnrelatedOcsp>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 429
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 67
----- Inner Stack Trace #5 (Xunit.Sdk.EqualException) -----
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.AssertChainStatus(X509Chain chain, X509ChainStatusFlags rootStatus, X509ChainStatusFlags issrStatus, X509ChainStatusFlags leafStatus) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1572
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass19_0.<RevokeEndEntity_IssuerUnrelatedOcsp>b__0(CertificateAuthority root, CertificateAuthority intermediate, X509Certificate2 endEntity, ChainHolder holder, RevocationResponder responder) in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 429
   at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.DynamicRevocationTests.<>c__DisplayClass46_0.<SimpleTest>b__0() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/DynamicRevocationTests.cs:line 1541
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 67
```

**Comment by vcsjones** [comment]
I believe this was fixed by https://github.com/dotnet/runtime/pull/70821, so closing this.
