### ISSUE TITLE
AggregateException.ToString() duplicates inner message exception

### ISSUE THREAD

**Issue by cmeeren** [dotnet/runtime#68930]
I propose that `AggregateException.ToString()` should not render the inner exception message multiple times. That is very verbose and also unnecessary since `AggregateException` also renders the inner exception(s) anyway.

To make the issue clear, consider this real-world example where I have thrown an exception when loading invalid data from DB. When that happens, I add the entire DTO to the exception message (ecause that provides me with all the information I need without having to go hunting in other logs). My exception is thrown from async code, and is at some point wrapped in an `AggregateException`.

Note, specifically, that the `AggregateException` renders like:

```
System.AggregateException: One or more errors occurred. (<inner exception message>):
 ---> <inner exception type and message>
```

```
System.AggregateException: One or more errors occurred. (Invalid data in Observation, full DTO:
{
  "ObservationId": 60584,
  "CreatedByUserId": 10036,
  "Description": "{\"type\":\"text\",\"data\":\"Test\"}",
  "ActionTaken": null,
  "Result": null,
  "Latitude": 500,
  "Longitude": 500,
  "Status": 1,
  "Priority": null,
  "Severity": null,
  "Archived": false,
  "ProjectId": 10002,
  "MainAttachment": null,
  "CategoryId": null,
  "LocationId": null,
  "CreatedAt": "2022-05-05T11:38:48.9887262+02:00",
  "UpdatedAt": "2022-05-05T11:38:58.4507177+02:00",
  "ResponsibleUser": null,
  "HappenedAtOffset": null,
  "ProjectObservationId": 180,
  "CauseId": null,
  "PublishedAt": "2022-05-05T11:38:58.4507177+02:00",
  "ClosedAt": null,
  "ResponsibleLeaderUserId": null,
  "DueStatus": 1,
  "DueWarning": null,
  "Due": "2022-05-12T11:38:58.4507177+02:00",
  "Visibility": 40,
  "HasBeenShared": false
})
 ---> System.Exception: Invalid data in Observation, full DTO:
{
  "ObservationId": 60584,
  "CreatedByUserId": 10036,
  "Description": "{\"type\":\"text\",\"data\":\"Test\"}",
  "ActionTaken": null,
  "Result": null,
  "Latitude": 500,
  "Longitude": 500,
  "Status": 1,
  "Priority": null,
  "Severity": null,
  "Archived": false,
  "ProjectId": 10002,
  "MainAttachment": null,
  "CategoryId": null,
  "LocationId": null,
  "CreatedAt": "2022-05-05T11:38:48.9887262+02:00",
  "UpdatedAt": "2022-05-05T11:38:58.4507177+02:00",
  "ResponsibleUser": null,
  "HappenedAtOffset": null,
  "ProjectObservationId": 180,
  "CauseId": null,
  "PublishedAt": "2022-05-05T11:38:58.4507177+02:00",
  "ClosedAt": null,
  "ResponsibleLeaderUserId": null,
  "DueStatus": 1,
  "DueWarning": null,
  "Due": "2022-05-12T11:38:58.4507177+02:00",
  "Visibility": 40,
  "HasBeenShared": false
}
 ---> System.Exception: Invalid Latitude value '500M': The value must be at most 90M
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Microsoft.FSharp.Core.PrintfModule.gprintf[a,TState,TResidue,TResult,TPrinter](FSharpFunc`2 envf, PrintfFormat`4 format) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1391
...
```

The problem is of course exacerbated if the exception tree contains multiple `AggregateException`.

Instead, this is what I propose:

```
System.AggregateException: One or more errors occurred.
 ---> System.Exception: Invalid data in Observation, full DTO:
{
  "ObservationId": 60584,
  "CreatedByUserId": 10036,
  "Description": "{\"type\":\"text\",\"data\":\"Test\"}",
  "ActionTaken": null,
  "Result": null,
  "Latitude": 500,
  "Longitude": 500,
  "Status": 1,
  "Priority": null,
  "Severity": null,
  "Archived": false,
  "ProjectId": 10002,
  "MainAttachment": null,
  "CategoryId": null,
  "LocationId": null,
  "CreatedAt": "2022-05-05T11:38:48.9887262+02:00",
  "UpdatedAt": "2022-05-05T11:38:58.4507177+02:00",
  "ResponsibleUser": null,
  "HappenedAtOffset": null,
  "ProjectObservationId": 180,
  "CauseId": null,
  "PublishedAt": "2022-05-05T11:38:58.4507177+02:00",
  "ClosedAt": null,
  "ResponsibleLeaderUserId": null,
  "DueStatus": 1,
  "DueWarning": null,
  "Due": "2022-05-12T11:38:58.4507177+02:00",
  "Visibility": 40,
  "HasBeenShared": false
}
 ---> System.Exception: Invalid Latitude value '500M': The value must be at most 90M
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1439
   at Microsoft.FSharp.Core.PrintfModule.gprintf[a,TState,TResidue,TResult,TPrinter](FSharpFunc`2 envf, PrintfFormat`4 format) in D:\a\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1391
...
```

Note that this is consistent with the `ToString()` of nested exceptions that are not `AggregateException`. For example, nesting two `Exception`s and calling `ToString` on the outer gives:

```
  "System.Exception: outer
 ---> System.Exception: inner"
```

If it's relevant, I'm on .NET 6.

**Comment by cmeeren** [comment]
My preferred resolution would be for someone knowledgeable about the relevant code/tests to implement this. Alternatively I am willing to help out, but will in that case need guidance on what code/tests to modify.

**Comment by cmeeren** [comment]
For the record: Since it's the inner exception's `Message` that is duplicated (and not `ToString`), a way to alleviate (not fix) the issue is to use a custom inner exception where `Message` is short, and `ToString` has all the details.
