### ISSUE TITLE
[wasm][nodejs] `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.SendAsync_ContentLengthAndTransferEncodingHeaders_IgnoreContentLength`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#69085]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1761079&view=results), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68921-merge-0538c45a14e046fc9b/WasmTestOnNodeJs-System.Net.Http.Functional.Tests/1/console.246e3a14.log?helixlogtype=result). Seen on https://github.com/dotnet/runtime/pull/68921 .

Breaking with `nodejs`:

```
[23:38:31] fail: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.SendAsync_ContentLengthAndTransferEncodingHeaders_IgnoreContentLength
[23:38:31] info: System.Net.Http.HttpRequestException : FetchError: request to http://127.0.0.1:40499/ failed, reason: Parse Error: Content-Length can't be present with Transfer-Encoding
[23:38:31] info: ---- System.Runtime.InteropServices.JavaScript.JSException : FetchError: request to http://127.0.0.1:40499/ failed, reason: Parse Error: Content-Length can't be present with Transfer-Encoding
[23:38:31] info:    at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|56_0(HttpRequestMessage request, CancellationToken cancellationToken)
[23:38:31] info:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[23:38:31] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.<>c__DisplayClass20_0.<<SendAsync_ContentLengthAndTransferEncodingHeaders_IgnoreContentLength>b__1>d.MoveNext()
[23:38:31] info: --- End of stack trace from previous location ---
[23:38:31] info:    at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
[23:38:31] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.<SendAsync_ContentLengthAndTransferEncodingHeaders_IgnoreContentLength>b__20_0(LoopbackServer server, Uri uri)
[23:38:31] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[23:38:31] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_ContentLengthAndTransferEncodingHeaders_IgnoreContentLength()
[23:38:31] info: --- End of stack trace from previous location ---
[23:38:31] info: ----- Inner Stack Trace -----
[23:38:31] info:    at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|56_0(HttpRequestMessage request, CancellationToken cancellationToken)
[23:38:31] fail: (node:713) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
```

This test was just introduced in https://github.com/dotnet/runtime/pull/69016 .

cc @pedrobsaila @ManickaP  @wfurt  @maraf @pavelsavara

**Comment by wfurt** [comment]
We should probably exclude the test from browsers. cc: @pedrobsaila.

**Comment by maraf** [comment]
The test works on browser, we can disable it just for NodeJS.
