### ISSUE TITLE
`System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Cancel_With_InfiniteTimeout` failing on `Libraries Test Run release coreclr windows x86 Release`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#69101]
[Build(https://dev.azure.com/dnceng/public/_build/results?buildId=1761080&view=logs&jobId=ab70ab4f-0cf4-5814-7190-28e4ead6a7bf&j=ab70ab4f-0cf4-5814-7190-28e4ead6a7bf&t=7397d5bd-c86f-542b-6ad4-5cdbdcdf155e), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68921-merge-54ca1596f7314196b4/System.IO.Pipes.Tests/1/console.6ea66272.log?helixlogtype=result).
```
    System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Cancel_With_InfiniteTimeout [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(0,0): at System.Threading.Tasks.TaskTimeoutExtensions.WaitAsync[TResult](Task`1 task, TimeSpan timeout, CancellationToken cancellationToken)
        /_/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.Specific.cs(699,0): at System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Cancel_With_InfiniteTimeout()
        --- End of stack trace from previous location ---
```

Test recently added in https://github.com/dotnet/runtime/pull/66877 .
cc @cranberry-knight

**Comment by stephentoub** [comment]
@dotnet/area-system-io, please take a look / disable this test... it's failing many PRs.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as this has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
