### ISSUE TITLE
NullReferenceException inside ConcurrentDictionary.GrowTable

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#69192]
Pipeline: https://dev.azure.com/dnceng/public/_build/results?buildId=1764865&view=results
Job: Installer Build and Test coreclr Linux_arm Release

```scala
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error : Error: Object reference not set to an instance of an object. [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at System.Collections.Concurrent.ConcurrentDictionary`2.GrowTable(Tables tables) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at System.Collections.Concurrent.ConcurrentDictionary`2.TryAddInternal(TKey key, Nullable`1 nullableHashcode, TValue value, Boolean updateIfExists, Boolean acquireLock, TValue& resultingValue) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.DependencyAnalysis.NodeCache`2.GetOrAdd(TKey key) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.DependencyAnalysis.NodeFactory.CompiledMethodNode(MethodDesc method) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.Compilation.RootingServiceProvider.AddCompilationRoot(MethodDesc method, Boolean rootMinimalDependencies, String reason) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.ReadyToRunRootProvider.RootMethods(TypeDesc type, String reason, IRootingServiceProvider rootProvider) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.ReadyToRunRootProvider.AddCompilationRoots(IRootingServiceProvider rootProvider) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.Compilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 compilationRoots, ILProvider ilProvider, DevirtualizationManager devirtualizationManager, IEnumerable`1 modulesBeingInstrumented, Logger logger, InstructionSetSupport instructionSetSupport) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.ReadyToRunCodegenCompilation..ctor(DependencyAnalyzerBase`1 dependencyGraph, NodeFactory nodeFactory, IEnumerable`1 roots, ILProvider ilProvider, Logger logger, DevirtualizationManager devirtualizationManager, IEnumerable`1 inputFiles, String compositeRootPath, InstructionSetSupport instructionSetSupport, Boolean resilient, Boolean generateMapFile, Boolean generateMapCsvFile, Boolean generatePdbFile, Func`2 printReproInstructions, String pdbPath, Boolean generatePerfMapFile, String perfMapPath, Int32 perfMapFormatVersion, Boolean generateProfileFile, Int32 parallelism, ProfileDataManager profileData, ReadyToRunMethodLayoutAlgorithm methodLayoutAlgorithm, ReadyToRunFileLayoutAlgorithm fileLayoutAlgorithm, Int32 customPESectionAlignment, Boolean verifyTypeAndFieldLayout) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.Program.Run(String[] args) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(463,5): error :    at ILCompiler.Program.Main(String[] args) [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
/root/runtime/artifacts/bin/Crossgen2Tasks/Debug/net7.0/Microsoft.NET.CrossGen.targets(351,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [/root/runtime/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.Composite.sfxproj]
```

@jkotas do you think this could also be a symptom of #68443?

**Comment by jkotas** [comment]
It can be a symptom of #68443. It is hard to tell with any level of confidence without a crash dump.

**Comment by jakobbotsch** [comment]
Another similar-looking-but-not-quite example in #69068:
```scala
    Generating native code
    Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
       at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValueInternal(TKey key, Int32 hashcode, TValue& value)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at ILCompiler.DependencyAnalysis.NodeFactory.NodeCache`2.GetOrAdd(TKey key) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 156
       at ILCompiler.DependencyAnalysis.NodeFactory.MethodMetadata(MethodDesc method) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 998
       at ILCompiler.UsageBasedMetadataManager.GeneratedTypesAndCodeMetadataPolicy.GeneratesMetadata(MethodDesc methodDef) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UsageBasedMetadataManager.cs:line 873
       at ILCompiler.Metadata.Transform`1.HandleQualifiedMethod(MethodDesc method) in /_/src/coreclr/tools/aot/ILCompiler.MetadataTransform/ILCompiler/Metadata/Transform.Method.cs:line 36
       at ILCompiler.MetadataManager.CreateStackTraceRecord(MetadataTransform transform, MethodDesc method) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/MetadataManager.cs:line 573
```

Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1769350&view=results
Job name: Build windows x64 debug NativeAOT

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr outerloop  20220526.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1791661&view=ms.vss-test-web.build-test-results-tab&runId=47895730&resultId=104628&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\opt\\virtualstubdispatch\\bigvtbl\\bigvtbl_cs_do\\bigvtbl_cs_do.cmd

```
**Error message:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Internal.NativeFormat.VertexArray.VertexTree.Save(NativeWriter writer) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 1806
at Internal.NativeFormat.NativeWriter.Save(Stream stream) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 334
at ILCompiler.DependencyAnalysis.ReadyToRun.DebugInfoTableNode.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/DebugInfoTableNode.cs:line 123
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 256
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 347
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 769
at ILCompiler.Program.Run(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 545
at ILCompiler.Program.Main(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 1046

Return code:      1
Raw output file:      C:\h\w\B9CC0A01\w\C1A90AAD\uploads\Reports\JIT.opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.output.txt
Raw output:
BEGIN EXECUTION
bigvtbl_cs_do.dll
1 file(s) copied.
20:36:39.30
Response file: C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.dll.rsp
C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\IL-CG2\bigvtbl_cs_do.dll
-o:C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B9CC0A01\p\System..dll
-r:C:\h\w\B9CC0A01\p\Microsoft..dll
-r:C:\h\w\B9CC0A01\p\mscorlib.dll
-r:C:\h\w\B9CC0A01\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B9CC0A01\p\crossgen2\crossgen2.dll" @"C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.dll.rsp"   -r:C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.dll
20:37:01.30
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B9CC0A01\p
C:\h\w\B9CC0A01\w\C1A90AAD\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_do\bigvtbl_cs_do.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_opt._virtualstubdispatch_bigvtbl_bigvtbl_cs_do_bigvtbl_cs_do_._virtualstubdispatch_bigvtbl_bigvtbl_cs_do_bigvtbl_cs_do_cmd()
```

**Comment by nerai** [comment]
I have a more or less reproducible crash attached. Is this related?

I'm on .NET 6.0, VS 2022.

```
Object reference not set to an instance of an object.

at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValueInternal(TKey key, Int32 hashcode, TValue& value)
in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 498
```

This is the line. The visible IP is in two lines below, probably because it is optimized.

```
                else
                {
498:                for (Node? n = Volatile.Read(ref tables.GetBucket(hashcode)); n != null; n = n._next)
                    {
                        if (hashcode == n._hashcode && _defaultComparer.Equals(n._key, key))
                        {
                            value = n._value;
                            return true;
                        }
                    }
                }
```

Seems to happen when physical RAM is exhausted (Count = 94644926, 63 GB).

I don't see which value exactly is null.

```
n
Unable to read memory

tables
Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.

_tables
{System.Collections.Concurrent.ConcurrentDictionary<X, Y>.Tables}
    _buckets: {System.Collections.Concurrent.ConcurrentDictionary<X, Y>.Node[587202557]}
    _countPerLock: {int[1536]}
    _fastModBucketsMultiplier: 31414618097
    _locks: {object[1536]}

_tables.GetBucket(hashcode)
{System.Collections.Concurrent.ConcurrentDictionary<X, Y>.Node}
    _hashcode: 50331649
    _key: {xxx}
    _next: {System.Collections.Concurrent.ConcurrentDictionary<X, Y>.Node}
    _value: {yyy}
```

A second thread seemed to be at the exact same IP when this happened.

**Comment by trylek** [comment]
I'm wondering whether this might be related to https://github.com/dotnet/runtime/issues/66079 - in this issue we're observing unbounded growth of certain dictionaries due to the generic explosion, at one point I observed 32-bit integer wraparound that might theoretically explain the nullref. I continue working on the fix for 66079 with the hope that this may go away once it's available.

**Comment by AntonLapounov** [comment]
> I have a more or less reproducible crash attached.

@nerai I do not see the repro attached.  Could you please share it?

**Comment by nerai** [comment]
> @nerai I do not see the repro attached. Could you please share it?

Sorry, I worded that poorly. The crash was reproducible, but it was part of a large in-prod project. It took hours/days to manifest during runtime, so it's not easy to create a separate project that I could share here.

**Comment by mangod9** [comment]
Hi @nerai, would you be able to share a few dumps of the failure so we could investigate further? Thanks

**Comment by AntonLapounov** [comment]
No repro since June 18th?

**Comment by mangod9** [comment]
Ok to close then and re-evaluate if it shows up again.
