### ISSUE TITLE
Microsoft.DotNet.ILCompiler build fail

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#69223]
### Description

Last console output is 

```
C:\Users\Administrator\.nuget\packages\htmlagilitypack\1.11.42\lib\netstandard2.0\HtmlAgilityPack.dll : warning IL3053:
 Assembly 'HtmlAgilityPack' produced AOT analysis warnings. [G:\gitsouce\Anf\Platforms\Anf.Web\Anf.Web.csproj]
EXEC : error : Object reference not set to an instance of an object. [G:\gitsouce\Anf\Platforms\Anf.Web\Anf.Web.csproj]
  System.NullReferenceException: Object reference not set to an instance of an object.
     at ILCompiler.DependencyAnalysis.ConstrainedMethodUseLookupResult.GetTarget(NodeFactory factory, GenericLookupResu
  ltContext dictionary)
     at ILCompiler.DependencyAnalysis.ReadyToRunGenericHelperNode.InstantiateDependencies(NodeFactory factory, Instanti
  ation typeInstantiation, Instantiation methodInstantiation)
     at ILCompiler.DependencyAnalysis.ShadowConcreteMethodNode.GetStaticDependencies(NodeFactory factory)
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node
  )
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan()
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
C:\Users\Administrator\.nuget\packages\microsoft.dotnet.ilcompiler\7.0.0-preview.3.22175.4\build\Microsoft.NETCore.Nati
ve.targets(269,5): error MSB3073: 命令“"C:\Users\Administrator\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompile
r\7.0.0-preview.3.22175.4\tools\\ilc" @"obj\Release\net7.0\win-x64\native\Anf.Web.ilc.rsp"”已退出，代码为 1。 [G:\gitsouce\Anf\
Platforms\Anf.Web\Anf.Web.csproj]
```

### Reproduction Steps

Use command

```cmd
dotnet publish -c Release -f net6.0 -r win-x64
```

### Expected behavior

Fail to compile to native

### Actual behavior

Succeed

### Regression?

.NET 6 or .NET 7

Microsoft.DotNet.ILCompiler 7.0.0-preview.3.22175.4

**Comment by am11** [comment]
@Cricle, NativeAOT will be introduced as part of .NET 7 release. It will not work with .NET 6.

**Comment by Cricle** [comment]
> 

Thanks, I will try after .NET 7 Release

**Comment by MichalStrehovsky** [comment]
This problem is not know, thanks for reporting. Reopening.

**Comment by jkotas** [comment]
@Cricle Could you please share a small project that reproduces the problem if possible?

**Comment by hez2010** [comment]
I think it's exactly https://github.com/dotnet/runtime/issues/68538

**Comment by Cricle** [comment]
@jkotas 
Can you try my project?  I try to write mini project, but always compile succeed in NET6.0.
https://github.com/Cricle/Anf/tree/dev/Platforms/Anf.Web
![image](https://user-images.githubusercontent.com/26201412/168007359-eb072a38-d01a-4b97-83d1-3a147784ad26.png)
Restore this line and try publish
