### ISSUE TITLE
System.Runtime.InteropServices.MarshalDirectiveException pops up when executing MetaFile automation case

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/runtime#69348]
### .NET version

**.Net 7.0 SDK:** 7.0.100-preview.5.22227.7

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it is a regression issue, cannot repro in .Net 6.0

### Issue description

System.Runtime.InteropServices.MarshalDirectiveException
  HResult=0x80131535
  Message=Cannot marshal 'parameter # 5': Cannot marshal managed types when the runtime marshalling system is disabled.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    [External Code]
    WinFormsApp12.Form1.Form1() in Form1.cs
    WinFormsApp12.Program.Main() in Program.cs

### Steps to reproduce

[WinFormsApp12.zip](https://github.com/dotnet/winforms/files/8582038/WinFormsApp12.zip)
1. Put tested application to the C:\Test folder on test machine
2. Open that test application, build and run

**Comment by kant2002** [comment]
Problem comes with marshaling 5th parameter of the delegate `EnumerateMetafileProc` which delegate itself.

https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs#L73-L78

@AaronRobinsonMSFT shouldn't this trigger error/warning from source generator?

**Comment by AaronRobinsonMSFT** [comment]
Yes it should. We recently discovered support for this in our analyzer. See https://github.com/dotnet/roslyn-analyzers/issues/5995

/cc @jkoritzinsky @elinor-fung

**Comment by Olina-Zhang** [comment]
In the latest .Net 7.0 build: 7.0.100-preview.6.22310.18, the exception is changed as following:

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ArgumentNullException.Throw(String paramName)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer[TDelegate](IntPtr ptr)
   at System.Drawing.Graphics.EnumerateMetafileProcMarshaller.<>c__DisplayClass3_0.<.ctor>b__0(EmfPlusRecordType recordType, Int32 flags, Int32 dataSize, IntPtr data, IntPtr callbackData)
   at System.Drawing.SafeNativeMethods.Gdip.<GdipEnumerateMetafileDestPointI>g____PInvoke|541_0(IntPtr graphics, IntPtr metafile, Point* destPoint, IntPtr callback, IntPtr callbackdata, IntPtr imageattributes)
   at System.Drawing.SafeNativeMethods.Gdip.GdipEnumerateMetafileDestPointI(HandleRef graphics, HandleRef metafile, Point& destPoint, EnumerateMetafileProc callback, IntPtr callbackdata, HandleRef imageattributes)
   at System.Drawing.Graphics.EnumerateMetafile(Metafile metafile, Point destPoint, EnumerateMetafileProc callback, IntPtr callbackData, ImageAttributes imageAttr)
   at System.Drawing.Graphics.EnumerateMetafile(Metafile metafile, Point destPoint, EnumerateMetafileProc callback)
   at WinFormsApp12.Form1..ctor() in C:\Test\WinFormsApp12\WinFormsApp12\Form1.cs:line 21
   at WinFormsApp12.Program.Main() in C:\Test\WinFormsApp12\WinFormsApp12\Program.cs:line 14

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 7.0 SDK build from main branch: 7.0.100-preview.7.22330.8, it is fixed: no exception pops up, case passed.
