### ISSUE TITLE
System.Text.Json fails to deserialize into a model with an ImmutableList property.

### ISSUE THREAD

**Issue by ericrini** [dotnet/runtime#69417]
### Description

The following StackOverflow issue describes a scenario trying to deserialize an object that has an immutable collection as a property using the System.Text.Json serializer. While the code appears to be a valid application of the general principles of System.Text.Json, it fails in practice. It is not clear if this is a bug, or some misunderstanding of the way that the JsonConstructorAttribute is intended to be used.

### Reproduction Steps

Given a readonly struct with an immutable collection property.

```
public readonly struct ImmutableModel
{
    [JsonConstructor]
    public ImmutableModel(IEnumerable<string> strings)
    {
        ImmutableList = strings.ToImmutableList();
    }
    
    public ImmutableList<string> ImmutableList { get; }
}
```

Serialize and deserialize it with the System.Text.Json serializer.

```
string json = JsonSerializer.Serialize(new ImmutableModel(new [] { "test" }));
JsonSerializer.Deserialize<ImmutableModel>(json);
```

### Expected behavior

The structure should be deserialized correctly.

### Actual behavior

The following exception is thrown during deserialization.

```
System.InvalidOperationException
Each parameter in the deserialization constructor on type '-----' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

### Regression?

Unknown.

### Known Workarounds

Most other IEnumerable implementations will work fine, the issue is with using an ImmutableList. There is something in the deserializer that doesn't like this, even though the constructor is correctly annotated and otherwise valid.

### Configuration

The issue is reproducible on .NET 6.0 using an Intel or Apple M1 processor.

```
> dotnet --version
6.0.105
```

### Other information

There is an issue on StackOverflow discussing this problem.
https://stackoverflow.com/questions/72268018/jsonconstructor-fails-on-ienumerable-property

**Comment by huoyaoyuan** [comment]
As the exception message said, the name of constructor parameter `strings` and the property `ImmutableList` does not match. They must match in both name and type.

The following code can run correctly:

```csharp
public readonly struct ImmutableModel
{
    [JsonConstructor]
    public ImmutableModel(ImmutableList<string> immutableList)
    {
        ImmutableList = immutableList.ToImmutableList();
    }

    public ImmutableList<string> ImmutableList { get; }
}

string json = JsonSerializer.Serialize(new ImmutableModel(new[] { "test" }.ToImmutableList()));
var model = JsonSerializer.Deserialize<ImmutableModel>(json);
```

**Comment by eiriktsarpalis** [comment]
Duplicate of #44428.
