### ISSUE TITLE
TimeZoneNotFoundException on Alpine-Linux when looking for Windows-Timezone

### ISSUE THREAD

**Issue by BrunoJuchli** [dotnet/runtime#69438]
### Description

When running on alpine linux with with icu library and tzdata installed, calling `System.TimeZoneInfo.FindSystemTimeZoneById(String id)` with a windows timezone identifier throws `System.TimeZoneNotFoundException`.

According to (my interpretation of) [this](https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/comment-page-2/#time-zone-conversion-apis) it should work.

### Reproduction Steps

Project:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <OutputType>Exe</OutputType>
      </PropertyGroup>
    </Project>

Code: 

    System.TimeZoneInfo.FindSystemTimeZoneById(
        "W. Europe Standard Time");
        
Dockerfile:

    FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine
    ENV \
         DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
         LC_ALL=en_US.UTF-8 \
         LANG=en_US.UTF-8

    RUN apk update && \
        apk add --no-cache icu tzdata

    #TODO: Copy app here
    #and set correct dll name on next line
    ENTRYPOINT ["dotnet", "Repro.dll"]

### Expected behavior

The call should return a `TimeZoneInfo` object.

### Actual behavior

Throws `System.TimeZoneNotFoundException` with message
> The time zone ID 'W. Europe Standard Time' was not found on the local computer. - Could not find file '/usr/share/zoneinfo/W. Europe Standard Time'.

Stacktrace:
> at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at ...
--- Inner exception stack trace ---
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)

### Known Workarounds

- Probably [App-Local ICU](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu).
  - downside of having to specify this in every executable and unit test project which depends on it.
  Which also means only (expensive?!) end-to-end tests will detect when the executable project is missing the configuration.
- using a library to `TimeZoneInfo` lookup, like https://github.com/mattjohnsonpint/TimeZoneConverter

### Configuration

.net runtime 6.0.5
on alpine linux 3.15
in amd 64.
  
(Docker image mcr.microsoft.com/dotnet/runtime:6.0-alpine
which currently resolves to 6.0.5-alpine3.15-amd64)
  

### Other information

It's possible this is an environment configuration/setup problem. Unfortunately the [docs](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) miss a section on what's necessary to run this on linux.

Also, if this is the case, it might be nice to include this information (or a link to it) in the exception message.

**Comment by BrunoJuchli** [comment]
It seems I have managed to resolve the issue by adding the following to the dockerfile:

    ENV \
     DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
     LC_ALL=en_US.UTF-8 \
     LANG=en_US.UTF-8

As documented here: https://github.com/dotnet/dotnet-docker/blob/main/samples/selecting-tags.md#alpine-globalization

**Comment by tarekgh** [comment]
@BrunoJuchli when using Alpine containers, the [Globalization Invariant Mode](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md) will be enabled. You can see the environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true`. When this mode is on, we don't load the ICU library. 
In your code, you are using Windows time zone Id `W. Europe Standard Time` while you are running on Linux based OS. We support that only when ICU library is enabled and loaded. 

What you need to do is either remove the environment variable from the container or change its value to false. Something like `export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false`. 

I am closing the issue but feel free to send any question we can help with.
