### ISSUE TITLE
Microsoft.Extensions.FileProviders.PhysicalFileProviderTests failing when running libraries tests

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#69470]
Found while running all tests in libraries, running manually from the individual project also fails.
```log
Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetDeleted(useWildcard: False) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_hyckoxqu.gxr\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetDeleted_133_5j0ok833\UsePollingFileWatcher_U
  seActivePolling_HasChanged_SymbolicLink_TargetDeleted_134_gdedfeee'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(136,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_Tar
  getDeleted(Boolean useWildcard)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetDeleted(useWildcard: True) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_g2apn3tr.vug\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetDeleted_133_vkn9eixf\UsePollingFileWatcher_U
  seActivePolling_HasChanged_SymbolicLink_TargetDeleted_134_2jqx7zfq'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(136,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_Tar
  getDeleted(Boolean useWildcard)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink(useWildcard: False) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_ain2p2jp.elp\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_25_7zefwhlk\UsePollingFileWatcher_UseActivePolling
  _HasChanged_SymbolicLink_26_s1iaz3dc'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(28,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink(Bool
  ean useWildcard)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink(useWildcard: True) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_yiqzoxek.uwk\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_25_ad27q58t\UsePollingFileWatcher_UseActivePolling
  _HasChanged_SymbolicLink_26_m9i0ytq8'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(28,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink(Bool
  ean useWildcard)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(useWildcard: False, linkWasBroken: False) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_kujw4mlr.41c\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged_93_uvobot9g\UsePollingFileWatcher_Us
  eActivePolling_HasChanged_SymbolicLink_TargetChanged_94_vn55hd1f'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(96,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_Targ
  etChanged(Boolean useWildcard, Boolean linkWasBroken)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(useWildcard: False, linkWasBroken: True) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_kqkpe5l1.3h3\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged_93_2tpbe1at\UsePollingFileWatcher_Us
  eActivePolling_HasChanged_SymbolicLink_TargetChanged_94_pu9i1tm1'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(96,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_Targ
  etChanged(Boolean useWildcard, Boolean linkWasBroken)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(useWildcard: True, linkWasBroken: False) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_3sc5wqrr.tst\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged_93_3tr8js5t\UsePollingFileWatcher_Us
  eActivePolling_HasChanged_SymbolicLink_TargetChanged_94_bsqfv443'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(96,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_Targ
  etChanged(Boolean useWildcard, Boolean linkWasBroken)
          --- End of stack trace from previous location ---
      Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(useWildcard: True, linkWasBroken: True) [FAIL]
        System.IO.IOException : A required privilege is not held by the client. : 'C:\Users\buyaa\AppData\Local\Temp\#PhysicalFileProviderTests_dxmtq0jy.yy5\UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged_93_3a6zi47a\UsePollingFileWatcher_Us
  eActivePolling_HasChanged_SymbolicLink_TargetChanged_94_r4fm6hio'
        Stack Trace:
          D:\dotnet\runtime\src\libraries\Common\src\Interop\Windows\Kernel32\Interop.CreateSymbolicLink.cs(59,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\FileSystem.Windows.cs(467,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
          D:\dotnet\runtime\src\libraries\System.Private.CoreLib\src\System\IO\File.cs(743,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
          D:\dotnet\runtime\src\libraries\Microsoft.Extensions.FileProviders.Physical\tests\PhysicalFileProviderTests.netcoreapp.cs(96,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_Targ
  etChanged(Boolean useWildcard, Boolean linkWasBroken)
          --- End of stack trace from previous location ---
    Finished:    Microsoft.Extensions.FileProviders.Physical.Tests
  === TEST EXECUTION SUMMARY ===
     Microsoft.Extensions.FileProviders.Physical.Tests  Total: 193, Errors: 0, Failed: 8, Skipped: 0, Time: 36.917s
```
Failing with clean build having no any changes

**Comment by Jozkee** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74462.
