### ISSUE TITLE
Call 'Type.GetType' after 'Assembly.LoadFrom' throw 'System.IO.FileLoadException'

### ISSUE THREAD

**Issue by yejinmo** [dotnet/runtime#69596]
### Description

When call 'Type.GetType' after 'Assembly.LoadFrom', throw 'System.IO.FileLoadException'

```
            Assembly assembly = Assembly.LoadFrom("Core.dll");
            var type = Type.GetType("Foundation.NSObject, Xamarin.iOS");
            Console.WriteLine("hello world");
```

Crash:
```
Unhandled exception. System.IO.FileLoadException:
File name: 'Xamarin.iOS, Culture=neutral, PublicKeyToken=null'
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Test.Program.Main(String[] args) in C:\Users\98518\Desktop\Test\Test\Program.cs:line 12
```

### Reproduction Steps

1. Create .Net Standard 2.0 dll project, write something or nothing, compile

```
using System;

namespace Core
{
    public class Class1
    {

    }
}
```

2. Create .Net 6 console project, code:

```
using System;
using System.IO;
using System.Reflection;

namespace Test
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Assembly assembly = Assembly.LoadFrom("Core.dll");
            var type = Type.GetType("Foundation.NSObject, Xamarin.iOS");
            Console.WriteLine("hello world");
        }
    }
}
```
3. Publish, using `.Net 6` `win-x64` `SingleFile` `SelfContained`
4. Copy `Core.dll` to `Test.exe` root directory
5. Run `Test.exe`

### Expected behavior

Output: 
```
hello world
```

### Actual behavior

Crash:
```
Unhandled exception. System.IO.FileLoadException:
File name: 'Xamarin.iOS, Culture=neutral, PublicKeyToken=null'
 ---> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Test.Program.Main(String[] args) in C:\Users\98518\Desktop\Test\Test\Program.cs:line 12
```

### Known Workarounds

This is not the solution!
If not used `Assembly.LoadFrom` everything ok.
```
            // Assembly assembly = Assembly.LoadFrom("Core.dll");
            var type = Type.GetType("Foundation.NSObject, Xamarin.iOS");
            Console.WriteLine("hello world");
```

### Configuration

- .Net 6
- Windows / Linux
- x64
- **Single File**

pubxml:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net6.0\publish\linux-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
</Project>
```

**Comment by vitek-karas** [comment]
Thanks for reporting this.

The problem has been fixed in .NET 7 with https://github.com/dotnet/runtime/pull/67890.
Targeting the test project to `net7.0` and rebuilding/publishing with .NET 7 Preview 4 makes the program work the same regardless if `LoadFrom` is called or not.

**Comment by yejinmo** [comment]
> Thanks for reporting this.
> 
> The problem has been fixed in .NET 7 with #67890. Targeting the test project to `net7.0` and rebuilding/publishing with .NET 7 Preview 4 makes the program work the same regardless if `LoadFrom` is called or not.

Is there a way to fix this problem in .Net 6?

**Comment by yejinmo** [comment]
@vitek-karas 

I upgraded to VS Preview and .Net 7 Preview and everything worked fine after testing. But I can't convince the team to upgrade the production environment from LTS to Preview. Is there a schedule for such maintenance updates for .Net 6?

**Comment by vitek-karas** [comment]
I'll see if it will be possible to backport the fix, but it's been this way since forever, so the priority to backport is relatively low.

As for the workaround: If you don't need the "auto resolve next to the file" functionality of `Assembly.LoadFrom` you could call `AssemblyLoadContext.Default.LoadFromAssemblyPath` instead (that's what `LoadFrom` does anyway).
