### ISSUE TITLE
Test failure JIT\\opt\\virtualstubdispatch\\bigvtbl\\bigvtbl_cs_d\\bigvtbl_cs_d.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#69661]
Run: [runtime-coreclr outerloop 20220522.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1783507&view=ms.vss-test-web.build-test-results-tab&runId=47774048&resultId=103866&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\opt\\virtualstubdispatch\\bigvtbl\\bigvtbl_cs_d\\bigvtbl_cs_d.cmd

```

**Error message:**
```
Process terminated. Assertion failed.
at Internal.NativeFormat.Section.Place(Vertex vertex) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 71
at Internal.NativeFormat.VertexArray.ExpandBlock(Int32 index, Int32 depth, Boolean place, Boolean& isLeaf) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 1849
at Internal.NativeFormat.VertexArray.ExpandBlock(Int32 index, Int32 depth, Boolean place, Boolean& isLeaf) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 1861
at Internal.NativeFormat.VertexArray.ExpandBlock(Int32 index, Int32 depth, Boolean place, Boolean& isLeaf) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 1861
at Internal.NativeFormat.VertexArray.ExpandBlock(Int32 index, Int32 depth, Boolean place, Boolean& isLeaf) in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 1861
at Internal.NativeFormat.VertexArray.ExpandLayout() in //src/coreclr/tools/Common/Internal/NativeFormat/NativeFormatWriter.cs:line 1925
at ILCompiler.DependencyAnalysis.ReadyToRun.MethodEntryPointTableNode.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/MethodEntryPointTableNode.cs:line 106
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 256
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 347
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 769
at ILCompiler.Program.Run(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 545
at ILCompiler.Program.Main(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 1046

Return code:      1
Raw output file:      C:\h\w\B32E098B\w\AFCC09A0\uploads\Reports\JIT.opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.output.txt
Raw output:
BEGIN EXECUTION
bigvtbl_cs_d.dll
1 file(s) copied.
11:32:09.50
Response file: C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.dll.rsp
C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\IL-CG2\bigvtbl_cs_d.dll
-o:C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B32E098B\p\System..dll
-r:C:\h\w\B32E098B\p\Microsoft..dll
-r:C:\h\w\B32E098B\p\mscorlib.dll
-r:C:\h\w\B32E098B\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B32E098B\p\crossgen2\crossgen2.dll" @"C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.dll.rsp"   -r:C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.dll
11:32:28.81
Crossgen2 failed with exitcode - -2146232797
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B32E098B\p
C:\h\w\B32E098B\w\AFCC09A0\e\JIT\opt\virtualstubdispatch\bigvtbl\bigvtbl_cs_d\bigvtbl_cs_d.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_opt._virtualstubdispatch_bigvtbl_bigvtbl_cs_d_bigvtbl_cs_d_._virtualstubdispatch_bigvtbl_bigvtbl_cs_d_bigvtbl_cs_d_cmd()
```
Queued | OS | Arch | Pipeline
-- | -- | -- | --
2022-05-22T11:16:15.941Z | windows.10.amd64.open.rt | x64 | [runtime-coreclr outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1783507&view=ms.vss-test-web.build-test-results-tab&runId=47774048&resultId=103866&paneView=debug)
2022-05-22T08:40:45.534Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1783471&view=ms.vss-test-web.build-test-results-tab&runId=47773510&resultId=101852&paneView=debug)
2022-05-20T22:20:18.504Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1782101&view=ms.vss-test-web.build-test-results-tab&runId=47755838&resultId=101425&paneView=debug)
2022-05-18T22:19:35.13Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1778170&view=ms.vss-test-web.build-test-results-tab&runId=47697696&resultId=102687&paneView=debug)
2022-05-17T08:47:30.986Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1774888&view=ms.vss-test-web.build-test-results-tab&runId=47642518&resultId=102055&paneView=debug)
2022-05-14T21:04:44.391Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593342&resultId=100809&paneView=debug)
2022-05-14T21:04:44.391Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593342&resultId=100798&paneView=debug)
2022-05-11T08:51:29.461Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1764222&view=ms.vss-test-web.build-test-results-tab&runId=47467998&resultId=102163&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2022-05-09T07:22:24.856Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1759346&view=ms.vss-test-web.build-test-results-tab&runId=47383710&resultId=101574&paneView=debug)
2022-05-09T07:22:24.856Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1759346&view=ms.vss-test-web.build-test-results-tab&runId=47383710&resultId=101828&paneView=debug)
2022-05-08T07:47:53.228Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1758576&view=ms.vss-test-web.build-test-results-tab&runId=47373210&resultId=102606&paneView=debug)
2022-05-07T21:24:55.153Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47369006&resultId=100940&paneView=debug)
2022-05-07T21:24:55.153Z | windows.10.arm64v8.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47369006&resultId=100955&paneView=debug)
2022-05-07T08:44:26.687Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1757603&view=ms.vss-test-web.build-test-results-tab&runId=47359006&resultId=102184&paneView=debug)
2022-04-30T07:20:38.583Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1745308&view=ms.vss-test-web.build-test-results-tab&runId=47138754&resultId=102606&paneView=debug)
2022-04-28T19:19:13.923Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1742580&view=ms.vss-test-web.build-test-results-tab&runId=47097444&resultId=102812&paneView=debug)
2022-04-28T10:21:53.648Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1742006&view=ms.vss-test-web.build-test-results-tab&runId=47088208&resultId=102763&paneView=debug)
2022-04-25T08:46:55.983Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1736002&view=ms.vss-test-web.build-test-results-tab&runId=46986854&resultId=101993&paneView=debug)
2022-04-23T10:38:02.895Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1734217&view=ms.vss-test-web.build-test-results-tab&runId=46958244&resultId=102878&paneView=debug)
2022-04-22T22:27:18.238Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1733488&view=ms.vss-test-web.build-test-results-tab&runId=46949886&resultId=101576&paneView=debug)
2022-04-22T08:59:37.932Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1732256&view=ms.vss-test-web.build-test-results-tab&runId=46929160&resultId=101795&paneView=debug)
2022-04-20T10:24:23.799Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1728055&view=ms.vss-test-web.build-test-results-tab&runId=46849378&resultId=102429&paneView=debug)
2022-04-16T23:01:03.971Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1722145&view=ms.vss-test-web.build-test-results-tab&runId=46740874&resultId=102736&paneView=debug)
2022-04-16T20:37:45.88Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1722041&view=ms.vss-test-web.build-test-results-tab&runId=46739572&resultId=101561&paneView=debug)
2022-04-12T09:03:21.51Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1712279&view=ms.vss-test-web.build-test-results-tab&runId=46548984&resultId=102251&paneView=debug)
2022-04-11T19:24:59.313Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1711210&view=ms.vss-test-web.build-test-results-tab&runId=46531680&resultId=102721&paneView=debug)
2022-04-11T08:49:27.055Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1710318&view=ms.vss-test-web.build-test-results-tab&runId=46518156&resultId=101567&paneView=debug)
2022-04-10T22:39:19.437Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1709911&view=ms.vss-test-web.build-test-results-tab&runId=46510710&resultId=102730&paneView=debug)
2022-04-08T22:51:43.369Z | ubuntu.1804.amd64.android.29.open.rt | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1708025&view=ms.vss-test-web.build-test-results-tab&runId=46486470&resultId=101720&paneView=debug)
2022-04-02T19:25:23.097Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1696936&view=ms.vss-test-web.build-test-results-tab&runId=46292866&resultId=101016&paneView=debug)
2022-03-30T20:41:58.472Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1690994&view=ms.vss-test-web.build-test-results-tab&runId=46199434&resultId=103373&paneView=debug)
2022-03-28T07:19:02.876Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1685079&view=ms.vss-test-web.build-test-results-tab&runId=46102742&resultId=100093&paneView=debug)
2022-03-25T19:40:07.455Z | ubuntu.1804.amd64.android.29.open.svc | x64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=1682369&view=ms.vss-test-web.build-test-results-tab&runId=46071606&resultId=102631&paneView=debug)
</details>

**Comment by mangod9** [comment]
This appears to have been a spike for that day and hasnt reproed since. Please reopen if this shows up again.
