### ISSUE TITLE
Unhandled SECURITY_STATUS (0x80090016) in SecurityStatusAdapterPal results in InternalException

### ISSUE THREAD

**Issue by jakraft** [dotnet/runtime#69828]
### Description

SecurityStatusAdapterPal does not seem to have an error code mapping for 0x80090016 (-2146893802). This can result in the following exception from HttpClient when .NET runtime cannot validate the CA certificate:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. -2146893802
at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)
at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& context, String targetName, ArraySegment`1 input, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
<>
at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
<>
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Bo--TRUNCATED--
```

### Reproduction Steps

I'm honestly not sure how to reproduce this. It happens once every few million requests for our service.

### Expected behavior

SecurityStatusAdapterPal should be able to translate this into a proper error code/exception that the consumer can catch.

### Actual behavior

SecurityStatusAdapterPal throws an System.Net.InternalException which cannot be caught since that class is internal to .NET runtime.

### Regression?

I am unsure if this is regression. From what I can tell looking at the SecurityStatusAdapterPal source code, it does not appear this code was ever supported.

### Configuration

- .NET Version: .NET Core SDK 3.1.417
- OS version: Unsure, this is running on an Azure VM. Likely Windows Server 2019 or 2022.
- Architecture: x64

### Other information

The exception indicates there's no mapping found in this dictionary: https://github.com/dotnet/runtime/blob/032a7dcbe1056493e8bab51e6b5b9503de727273/src/libraries/Common/src/System/Net/SecurityStatusAdapterPal.Windows.cs#L21-L66

**Comment by karelz** [comment]
Triage: It looks like the best (and only) thing we can do here is to make sure we do not throw `InternalException`.
It should be simple - just adding entry into the dictionary above. up-for-grabs

@jakraft is that in line with your expectations? Or do you expect more from Networking stack in this case?

**Comment by jakraft** [comment]
@karelz I think that should be sufficient assuming the stack will eventually convert it into a catchable exception (e.g. `System.Security.Authentication.AuthenticationException`). I'm not entirely sure under what circumstances this error code will happen. Do you know if there are any docs available to indicate which error codes are retriable/transient?

**Comment by jakraft** [comment]
I see that the milestone is set to 7.0.0. Does that mean the earliest the fix would go in is .NET 7? Is there any chance it can be backported to .NET Core 3.1, and if so, what does that process look like? Otherwise, we likely won't be able to take advantage of the fix for a few years.

**Comment by karelz** [comment]
@jakraft 3.1 does not have years of support left, only last few months -- see https://github.com/dotnet/core/blob/main/releases.md#supported-net-versions
Once we have fix, we can open discussion about backporting (to .NET 6.0). It will require business impact details - how much it hurts your app and why workarounds are not sufficient.
