### ISSUE TITLE
Test failure System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#69835]
Run: [runtime-coreclr libraries-jitstress 20220525.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1788418&view=ms.vss-test-web.build-test-results-tab&runId=47852274&paneView=debug&resultId=152391)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.10.Arm64v8.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-x64-CoreCLR_checked-no_tiered_compilation-Ubuntu.1804.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-x64-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-x64-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-windows-Release-x64-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-x64-CoreCLR_checked-tailcallstress-Ubuntu.1804.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-x64-CoreCLR_checked-zapdisable-Ubuntu.1804.Amd64.Open
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm64-CoreCLR_checked-no_tiered_compilation-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm64-CoreCLR_checked-tailcallstress-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm64-CoreCLR_checked-zapdisable-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm-CoreCLR_checked-zapdisable-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm-CoreCLR_checked-tailcallstress-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining

net7.0-Linux-Release-arm-CoreCLR_checked-no_tiered_compilation-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining
```
**Error message:**
```
Assert.Contains() Failure
Not found: TestAssembly
In value:  System.Reflection.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51


Stack trace
   at System.Reflection.Tests.MethodInfoTests.SecondCall(MethodInfo mi) in /_/src/libraries/System.Reflection/tests/MethodInfoTests.cs:line 796
   at System.Reflection.Tests.MethodInfoTests.CallStackFrame_AggressiveInlining() in /_/src/libraries/System.Reflection/tests/MethodInfoTests.cs:line 782
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```
No Kusto information.

**Comment by steveharter** [comment]
@jakobbotsch I was assuming NoInlining on the target method would prevent tailcall elimination. Is there a typical work-around that would prevent the tailcall elimination? i.e. a workaround that others use for direct C#-to-C# calls if depending on `Assembly.GetCallingAssembly`?

I could add another method with NoInlining which prevents the tailcall elimination but would also interfere with the normal testing path.
