### ISSUE TITLE
[wasm] Wasm.Build.Tests timing out on Windows

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#69860]
This is being hit on rolling builds, for example - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-93da5e9e54644bb5a2/Workloads-.BuildPublishTests/1/console.1923710a.log?helixlogtype=result .

```
    Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, host: V8, id: "lyqlwa0s.m2z") [STARTING]
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:02:00
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:04:01
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:06:01
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:08:02
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:10:03
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:12:03
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:14:04
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:16:05
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:18:05
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:20:06
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:22:07
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:24:08
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:26:08
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:28:08
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT', Elapsed: 00:30:09
    Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, host: V8, id: "lyqlwa0s.m2z") [FAIL]
      System.AggregateException : One or more errors occurred. (Process timed out. Last 20 lines of output:
      
      [lyqlwa0s.m2z]   build_publish_Release -> C:\helix\work\workitem\e\lyqlwa0s.m2z\bin\Release\net7.0\browser-wasm\build_publish_Release.dll
      
      [lyqlwa0s.m2z]   ** MicrosoftNetCoreAppRuntimePackDir : C:\helix\work\correlation\dotnet-workload\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.0-ci
      
      [lyqlwa0s.m2z]   build_publish_Release -> C:\helix\work\workitem\e\lyqlwa0s.m2z\bin\Release\net7.0\browser-wasm\publish\
      
      [lyqlwa0s.m2z]   AOT'ing 5 assemblies
      
      [lyqlwa0s.m2z]   [1/5] build_publish_Release.dll -> build_publish_Release.dll.bc
      
      [lyqlwa0s.m2z]   [2/5] System.Private.Runtime.InteropServices.JavaScript.dll -> System.Private.Runtime.InteropServices.JavaScript.dll.bc
      
      [lyqlwa0s.m2z]   [3/5] System.Private.Uri.dll -> System.Private.Uri.dll.bc
      
      [lyqlwa0s.m2z]   [4/5] System.Runtime.dll -> System.Runtime.dll.bc
      
      [lyqlwa0s.m2z]   [5/5] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
      
      )
      ---- Process timed out. Last 20 lines of output:
      
      [lyqlwa0s.m2z]   build_publish_Release -> C:\helix\work\workitem\e\lyqlwa0s.m2z\bin\Release\net7.0\browser-wasm\build_publish_Release.dll
      
      [lyqlwa0s.m2z]   ** MicrosoftNetCoreAppRuntimePackDir : C:\helix\work\correlation\dotnet-workload\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.0-ci
      
      [lyqlwa0s.m2z]   build_publish_Release -> C:\helix\work\workitem\e\lyqlwa0s.m2z\bin\Release\net7.0\browser-wasm\publish\
      
      [lyqlwa0s.m2z]   AOT'ing 5 assemblies
      
      [lyqlwa0s.m2z]   [1/5] build_publish_Release.dll -> build_publish_Release.dll.bc
      
      [lyqlwa0s.m2z]   [2/5] System.Private.Runtime.InteropServices.JavaScript.dll -> System.Private.Runtime.InteropServices.JavaScript.dll.bc
      
      [lyqlwa0s.m2z]   [3/5] System.Private.Uri.dll -> System.Private.Uri.dll.bc
      
      [lyqlwa0s.m2z]   [4/5] System.Runtime.dll -> System.Runtime.dll.bc
      
      [lyqlwa0s.m2z]   [5/5] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
      
      
      Stack Trace:
           at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.Wait()
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(683,0): at Wasm.Build.Tests.BuildTestBase.RunProcess(String path, ITestOutputHelper _testOutput, String args, IDictionary`2 envVars, String workingDir, String label, Boolean logToXUnit, Nullable`1 timeoutMs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(590,0): at Wasm.Build.Tests.BuildTestBase.AssertBuild(String args, String label, Boolean expectSuccess, IDictionary`2 envVars, Nullable`1 timeoutMs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(348,0): at Wasm.Build.Tests.BuildTestBase.BuildProject(BuildArgs buildArgs, String id, BuildProjectOptions options)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildPublishTests.cs(114,0): at Wasm.Build.Tests.BuildPublishTests.BuildThenPublishWithAOT(BuildArgs buildArgs, RunHost host, String id)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(758,0): at Wasm.Build.Tests.BuildTestBase.RunProcessAsync(String path, ITestOutputHelper _testOutput, String args, IDictionary`2 envVars, String workingDir, String label, Boolean logToXUnit, Nullable`1 timeoutMs)
```

**Comment by radical** [comment]
The commits between the last good one, and first bad one: https://github.com/dotnet/runtime/compare/4ff994e7...9859f70e

I think the emsdk update might be related. It has a rollback to 3.1.7 .

@radekdoulik are you able to run wasm.build.tests on windows? I'm having trouble running them at all. It complains of missing `xunit.console.dll`!?! I'll dig more tomorrow.

**Comment by radical** [comment]
@radekdoulik for example, are you able to run `XUnitClassName=Wasm.Build.Tests.InvariantGlobalizationTests` completely?
