### ISSUE TITLE
[release/7.0-preview5][wasm] Assertion failure in interpreter `src/mono/mono/mini/interp/interp.c:2114`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#69864]
This is on preview5 branch when running `System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests` on a browser.

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1790011&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89), [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview5f0eefb0759a44897ad/WasmTestOnBrowser-System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests/1/console.85a9f314.log?helixlogtype=result):

```
[00:33:48] info: Using random seed for test cases: 1987443318
[00:33:48] info: Using random seed for collections: 1987443318
[00:33:48] info: Starting:    System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll
[00:33:54] warn: 
[00:33:54] warn: Unhandled Exception:
[00:33:54] warn: StackOverflowException
[00:33:54] fail: Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2114, condition `<disabled>' not met
                 
                     at mono_wasm_stringify_as_error_with_stack (http://127.0.0.1:35065/dotnet.js:3:23680)
                     at Object.mono_wasm_trace_logger (http://127.0.0.1:35065/dotnet.js:3:24051)
                     at _mono_wasm_trace_logger (http://127.0.0.1:35065/dotnet.js:12:105856)
                     at wasm_trace_logger (http://127.0.0.1:35065/dotnet.wasm:wasm-function[113]:0x9a52)
                     at eglib_log_adapter (http://127.0.0.1:35065/dotnet.wasm:wasm-function[2590]:0xa3d31)
                     at monoeg_g_logv_nofree (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8502]:0x1be593)
                     at monoeg_assertion_message (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8505]:0x1be622)
                     at mono_assertion_message (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8507]:0x1be665)
                     at mono_assertion_message_disabled (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8506]:0x1be638)
                     at interp_runtime_invoke (http://127.0.0.1:35065/dotnet.wasm:wasm-function[226]:0xcf1a)
[00:33:54] fail: Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2114, condition `<disabled>' not met
                 
                     at mono_wasm_stringify_as_error_with_stack (http://127.0.0.1:35065/dotnet.js:3:23680)
                     at Object.mono_wasm_trace_logger (http://127.0.0.1:35065/dotnet.js:3:24051)
                     at _mono_wasm_trace_logger (http://127.0.0.1:35065/dotnet.js:12:105856)
                     at wasm_trace_logger (http://127.0.0.1:35065/dotnet.wasm:wasm-function[113]:0x9a52)
                     at eglib_log_adapter (http://127.0.0.1:35065/dotnet.wasm:wasm-function[2590]:0xa3d31)
                     at monoeg_g_logv_nofree (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8502]:0x1be593)
                     at monoeg_assertion_message (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8505]:0x1be622)
                     at mono_assertion_message (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8507]:0x1be665)
                     at mono_assertion_message_disabled (http://127.0.0.1:35065/dotnet.wasm:wasm-function[8506]:0x1be638)
                     at interp_runtime_invoke (http://127.0.0.1:35065/dotnet.wasm:wasm-function[226]:0xcf1a)
[00:33:54] fail: [out of order message from the browser]: http://127.0.0.1:35065/dotnet.js 11:1256 Uncaught ExitStatus: Program terminated with exit(1)
[00:48:42] fail: Application has finished with exit code TIMED_OUT but 0 was expected
```

cc @BrzVlad

**Comment by radical** [comment]
@BrzVlad could this be related to the tiering changes?
