### ISSUE TITLE
Tar tests that interact with file assets do not work on Browser

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#69953]
In this [PR resubmission](https://github.com/dotnet/runtime/pull/69469) I added the missing Browser target platform in the tests project, and the result was that the browser tests that need to read file assets do not work on WASM.

Those test classes that read file assets will be topped with the ActiveIssue attribute and will be linked to this issue for future investigation, to unblock merging that PR.

[Log1](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69469-merge-1c7f6feb86f44e48a2/normal-System.Formats.Tar.Tests/1/console.06e0cbb4.log?helixlogtype=result), [log2](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69469-merge-72cadc08da8d459e97/WasmTestOnBrowser-System.Formats.Tar.Tests/1/console.b789a313.log?helixlogtype=result)

Here's an output example of one of the browser CI legs:

```
[02:30:29] fail: [FAIL] System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.IncludeAllSegmentsOfPath(includeBaseDirectory: False)
[02:30:29] info: Assert.NotNull() Failure
[02:30:29] info:    at System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.IncludeAllSegmentsOfPath(Boolean includeBaseDirectory)
[02:30:29] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:29] fail: [FAIL] System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.IncludeAllSegmentsOfPath(includeBaseDirectory: True)
[02:30:29] info: Assert.NotNull() Failure
[02:30:29] info:    at System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.IncludeAllSegmentsOfPath(Boolean includeBaseDirectory)
[02:30:29] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:29] fail: [FAIL] System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.VerifyIncludeBaseDirectory(includeBaseDirectory: False)
[02:30:29] info: Assert.Equal() Failure
[02:30:29] info: Expected: 3
[02:30:29] info: Actual:   0
[02:30:29] info:    at System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.VerifyIncludeBaseDirectory(Boolean includeBaseDirectory)
[02:30:29] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:29] fail: [FAIL] System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.VerifyIncludeBaseDirectory(includeBaseDirectory: True)
[02:30:29] info: Assert.Equal() Failure
[02:30:29] info: Expected: 3
[02:30:29] info: Actual:   0
[02:30:29] info:    at System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.VerifyIncludeBaseDirectory(Boolean includeBaseDirectory)
[02:30:29] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_HardLinkEntry_TargetInsideDirectory
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: 2
[02:30:30] info: Actual:   1
[02:30:30] info:    at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_LinkEntry_TargetInsideDirectory_Internal(TarEntryType entryType)
[02:30:30] info:    at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_Stream_Tests.Extract_HardLinkEntry_TargetInsideDirectory()
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarFile_ExtractToDirectory_File_Tests.Extract_SpecialFiles_Unix_Unelevated_ThrowsUnauthorizedAccess
[02:30:30] info: Assert.Throws() Failure
[02:30:30] info: Expected: typeof(System.UnauthorizedAccessException)
[02:30:30] info: Actual:   (No exception was thrown)
[02:30:30] info:    at System.Formats.Tar.Tests.TarFile_ExtractToDirectory_File_Tests.Extract_SpecialFiles_Unix_Unelevated_ThrowsUnauthorizedAccess()
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.EntryName_NullOrEmpty
[02:30:30] info: Assert.NotNull() Failure
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.EntryName_NullOrEmpty()
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: V7, withContents: False)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: V7
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: V7, withContents: True)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: V7
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: Ustar, withContents: False)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: Ustar
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: Ustar, withContents: True)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: Ustar
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: Pax, withContents: False)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: Pax
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: Pax, withContents: True)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: Pax
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: Gnu, withContents: False)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: Gnu
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(format: Gnu, withContents: True)
[02:30:30] info: Assert.Equal() Failure
[02:30:30] info: Expected: Gnu
[02:30:30] info: Actual:   Unknown
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Directory(TarFormat format, Boolean withContents)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(format: V7)
[02:30:30] info: Assert.NotNull() Failure
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(TarFormat format)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(format: Ustar)
[02:30:30] info: Assert.NotNull() Failure
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(TarFormat format)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(format: Pax)
[02:30:30] info: Assert.NotNull() Failure
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(TarFormat format)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] fail: [FAIL] System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(format: Gnu)
[02:30:30] info: Assert.NotNull() Failure
[02:30:30] info:    at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(TarFormat format)
[02:30:30] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[02:30:30] info: Finished:    System.Formats.Tar.Tests.dll
```

**Comment by radical** [comment]
@carlossanlop you can surface files to the wasm app by using `<WasmFilesToIncludeInFileSystem Include="..." />`
