### ISSUE TITLE
LogValues[int] throws new IndexOutOfRangeException(message: nameof(index))

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/runtime#69981]
### Description

The indexer of Microsoft.Extensions.Logging.LoggerMessage.LogValues throws `new IndexOutOfRangeException(nameof(index))` if the index is out of range:

<https://github.com/dotnet/runtime/blob/70ae3df4a6f3c92fb6b315afc405edd10ff38579/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerMessage.cs#L485>

However, the [IndexOutOfRangeException(string) constructor](https://docs.microsoft.com/dotnet/api/system.indexoutofrangeexception.-ctor?view=net-6.0#system-indexoutofrangeexception-ctor(system-string)) uses the string as Exception.Message, not as a parameter name. `nameof(index)` is not really suitable for Exception.Message. Perhaps the indexer should instead use the IndexOutOfRangeException() or ArgumentOutOfRangeException(string) constructor. Changing the type of the exception would have a higher risk of breaking something.

The same bug is in the generic LogValues classes, and also in the source generator:

<https://github.com/dotnet/runtime/blob/70ae3df4a6f3c92fb6b315afc405edd10ff38579/src/libraries/Microsoft.Extensions.Logging.Abstractions/gen/LoggerMessageGenerator.Emitter.cs#L170>

### Reproduction Steps

LoggerMessageOutOfRange.csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.1" />
  </ItemGroup>

</Project>
```

Program.cs:

```C#
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;

class Program
{
    static void Main()
    {
        Action<ILogger, string, Exception?> message = LoggerMessage.Define<string>(
            LogLevel.Information,
            new EventId(1, "Event"),
            "{Param}");
        message(new BrokenLogger(), "dummy", null);
    }
}

class BrokenLogger : ILogger
{
    public IDisposable? BeginScope<TState>(TState state) => null;

    public bool IsEnabled(LogLevel logLevel) => true;

    public void Log<TState>(
        LogLevel logLevel,
        EventId eventId,
        TState state,
        Exception? exception,
        Func<TState, Exception?, string> formatter)
    {
        if (state is IReadOnlyList<KeyValuePair<string, object?>> structured)
        {
            // IReadOnlyList<T>.Item[Int32] documentation does not say
            // whether this should throw ArgumentOutOfRangeException
            // (like IList<T>.Item[Int32]) or IndexOutOfRangeException.
            _ = structured[structured.Count + 1];
        }
    }
}
```

`dotnet run`

### Expected behavior

Exception.Message should be a sentence.

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Extensions.Logging.LoggerMessage.LogValues`1.get_Item(Int32 index)
   at BrokenLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Projects\Kalle\LoggerMessageOutOfRange\Program.cs:line 35
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass10_0`1.<Define>g__Log|0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass10_0`1.<Define>b__1(ILogger logger, T1 arg1, Exception exception)
   at Program.Main() in C:\Projects\Kalle\LoggerMessageOutOfRange\Program.cs:line 13
```

### Actual behavior

Exception.Message is just the identifier `index`.

```
Unhandled exception. System.IndexOutOfRangeException: index
   at Microsoft.Extensions.Logging.LoggerMessage.LogValues`1.get_Item(Int32 index)
   at BrokenLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in C:\Projects\Kalle\LoggerMessageOutOfRange\Program.cs:line 35
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass10_0`1.<Define>g__Log|0(ILogger logger, T1 arg1, Exception exception)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass10_0`1.<Define>b__1(ILogger logger, T1 arg1, Exception exception)
   at Program.Main() in C:\Projects\Kalle\LoggerMessageOutOfRange\Program.cs:line 13
```

### Regression?

No, it worked this way already in <https://github.com/aspnet/Logging/pull/338>.

### Known Workarounds

Implement the logger correctly so that it won't use an out-of-range index.

Or catch the exception and throw a better one.

### Configuration

.NET SDK 6.0.300, runtime 6.0.5, on win10-x64.
Windows 10 Pro version 21H2 (OS Build 19044.1706).
Not specific to this configuration.

### Other information

I noticed this in the source code when looking for advice on how to support structured logging in a TState type. I was not using LoggerMessage because I wanted to specify the LogLevel in the logging call (mapping it from another logging system). The bug is unlikely to be hit in any production code, but it seems like something that should have been flagged by an analyzer and fixed.

**Comment by KalleOlaviNiemitalo** [comment]
I was implementing similar code and got this warning:

> warning CA1065: get_Item creates an exception of type IndexOutOfRangeException, an exception type that should not be raised in a property. If this exception instance might be raised, use a different exception type, convert this property into a method, or change this property's logic so that it no longer raises an exception.

Related:

* [CA1065: Do not raise exceptions in unexpected locations](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065)
* <https://github.com/dotnet/roslyn-analyzers/blob/e52a3f1c0b45684ddaa041f26a980fa451ea9001/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs#L170-L175>

So, I'll use ArgumentOutOfRangeException(string paramName) in my own code. I assume this would be too much of a breaking change for .NET Runtime, though.
