### ISSUE TITLE
Test failure System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#69993]
Run:[ runtime-coreclr libraries-jitstress 20220530.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1796137&view=ms.vss-test-web.build-test-results-tab&runId=47949336&paneView=debug&resultId=161492)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Net.Sockets.SocketException): No such host is known.
---- System.Net.Sockets.SocketException : No such host is known.


Stack trace
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 220
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 192
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 220
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 192
--- End of stack trace from previous location ---
```
No Kusto information.

CI leg: `runtime-coreclr libraries-jitstress`

| Date | branch | OS |
|-------|---------|---|
| 2022-05-30T07:55:59.41Z | main | Windows.10.Amd64.Open |
| 2022-05-31T08:14:01.729Z | main | Windows.10.Amd64.Open |

**Comment by wfurt** [comment]
... or skip for jitstress....

**Comment by jakobbotsch** [comment]
> ... or skip for jitstress....

We run a lot of jitstress legs so often flaky tests are exposed under jitstress simply by chance. Even if you skip it for jitstress it is likely this problem will show up in other future runs.
