### ISSUE TITLE
Test failure System.Threading.Channels.Tests.SyncMultiReaderUnboundedChannelTests.ManyProducerConsumer_ConcurrentReadWrite_Success(numReaders: 10, numWriters: 1)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70061]
Affected test:
- ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success - `System.Threading.Channels.Tests.BoundedChannelTests.ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success`

Failures:
- [1833880](https://runfo.azurewebsites.net/view/build/?number=1833880) (6/20 AM)
    - net7.0-Linux-Release-arm-CoreCLR_release-(Debian.10.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-20210304164340-6616c63
- [runtime-coreclr libraries-jitstress 20220531.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1797309&view=ms.vss-test-web.build-test-results-tab&runId=47966746&paneView=debug&resultId=143514) (5/31)

Failures frequency (in runtime-extra-platforms pipeline, does not include jitstress):
- 6/20 -- 1x failure in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.threading.channels.tests.boundedchanneltests.manyproducerconsumer_concurrentreadwrite_withbufferedcapacity_success%22)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_checked-no_tiered_compilation-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.Threading.Channels.Tests.SyncMultiReaderUnboundedChannelTests.ManyProducerConsumer_ConcurrentReadWrite_Success(numReaders: 10, numWriters: 1)

```
**Error message:**
````
System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
---- System.NullReferenceException : Object reference not set to an instance of an object.

Stack trace
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 4896
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 4625
   at System.Threading.Channels.Tests.ChannelTestBase.ManyProducerConsumer_ConcurrentReadWrite_Success(Int32 numReaders, Int32 numWriters) in /_/src/libraries/System.Threading.Channels/tests/ChannelTestBase.cs:line 263
   at InvokeStub_ChannelTestBase.ManyProducerConsumer_ConcurrentReadWrite_Success(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----- Inner Stack Trace -----
   at System.Threading.Channels.Tests.ChannelTestBase.<>c__DisplayClass26_0.<<ManyProducerConsumer_ConcurrentReadWrite_Success>b__0>d.MoveNext() in /_/src/libraries/System.Threading.Channels/tests/ChannelTestBase.cs:line 231
```
No Kusto information.

**Comment by stephentoub** [comment]
No additional reports in a year and a half. Closing.
