### ISSUE TITLE
Build: generate layout does not copy runtime libraries

### ISSUE THREAD

**Issue by Wraith2** [dotnet/runtime#70096]
### Description

When building tests the build script is supposed to setup the test CORE_ROOT directory to contain the runtime libraries and the core clr files. It no longer copied the runtime files which causes the tests to fail until the libraries are manually copied into the directory.

### Reproduction Steps

```
git clean-xdf
build -c Debug
src\tests\build.cmd x64 Debug /p:LibrariesConfiguration=Debug
src\tests\run.cmd x64 Debug /p:LibrariesConfiguration=Debug
```

### Expected behavior

Tests are able to execute.

### Actual behavior

Tests fail because they cannot locate runtime libraries. e.g.

```
E:\Programming\csharp7\runtime>src\tests\run.cmd x64 Debug /p:LibrariesConfiguration=Debug
RUNTEST: CORE_ROOT is initially set to: "/p:LibrariesConfiguration"
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" "E:\Programming\csharp7\runtime\src\tests\..\..\src\tests\run.py" -arch x64 -build_type Debug
host_os                  : windows
arch                     : x64
build_type               : Debug
runtime_repo_location    : E:\Programming\csharp7\runtime
core_root                : E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
test_location            : E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug
Found COMPlus variables in the current environment

Unset SUPERPMI_CACHE_DIRECTORY

TestEnv: C:\Users\Wraith\AppData\Local\Temp\tmpzthd411k.bat

Contents:

@REM Temporary test env for test run.
@echo on
set SUPERPMI_CACHE_DIRECTORY=E:\Programming\csharp7\runtime_support\spmi
@echo off


Setting __TestTimeout=1800000
Setting CORE_ROOT=E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
Setting __TestEnv=C:\Users\Wraith\AppData\Local\Temp\tmpzthd411k.bat
E:\Programming\csharp7\runtime\dotnet.cmd msbuild E:\Programming\csharp7\runtime\src\tests\build.proj /t:RunTests /clp:showcommandline /fileloggerparameters:"Verbosity=normal;LogFile=E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.log" /fileloggerparameters1:"WarningsOnly;LogFile=E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.wrn" /fileloggerparameters2:"ErrorsOnly;LogFile=E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.err" /consoleloggerparameters:Summary /p:TargetOS=windows /p:TargetArchitecture=x64 /p:Configuration=Debug /p:__LogsDir=E:\Programming\csharp7\runtime\artifacts\log /bl:E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.binlog
E:\Programming\csharp7\runtime\.dotnet
Microsoft (R) Build Engine version 17.2.0-preview-22175-02+058a0262c for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

E:\Programming\csharp7\runtime\.dotnet\sdk\7.0.100-preview.3.22179.4\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,E:\Programming\csharp7\runtime\.dotnet\sdk\7.0.100-preview.3.22179.4\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,E:\Programming\csharp7\runtime\.dotnet\sdk\7.0.100-preview.3.22179.4\dotnet.dll -maxcpucount -verbosity:m /bl:E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.binlog /clp:showcommandline /consoleloggerparameters:Summary /fileloggerparameters1:WarningsOnly;LogFile=E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.wrn /fileloggerparameters2:ErrorsOnly;LogFile=E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.err /fileloggerparameters:Verbosity=normal;LogFile=E:\Programming\csharp7\runtime\artifacts\log\TestRunResults_windows_x64_Debug.log /p:TargetOS=windows /p:TargetArchitecture=x64 /p:Configuration=Debug /p:__LogsDir=E:\Programming\csharp7\runtime\artifacts\log /t:RunTests E:\Programming\csharp7\runtime\src\tests\build.proj
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_d1\Methodical_d1.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodic
  al\Methodical_d1\Methodical_d1.log
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_others\Methodical_others.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\
  Methodical\Methodical_others\Methodical_others.log
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_r2\Methodical_r2.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodic
  al\Methodical_r2\Methodical_r2.log
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_d2\Methodical_d2.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodic
  al\Methodical_d2\Methodical_d2.log
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_r1\Methodical_r1.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodic
  al\Methodical_r1\Methodical_r1.log
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_do\Methodical_do.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodic
  al\Methodical_do\Methodical_do.log
  E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_ro\Methodical_ro.cmd >E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_ro\Methodical_ro.log
  Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'  Error running test group 'E:\Programming\csharp7\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Methodical\Methodical_d1\Methodical_d1.cmd' - exit code 1
  Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

### Regression?

Yes, This used to work.

### Known Workarounds

Find and copy the libraries into the test root manually.

### Configuration

Win10 x64. latest main, vs 17.3 preview1.

**Comment by Wraith2** [comment]
It's what the instructions tell you to use: https://github.com/dotnet/runtime/blob/f44b0ba183ec2680f3d35b8615d474d1d50bc94e/docs/workflow/testing/coreclr/windows-test-instructions.md

It did work before and others who contribute to the jit have confirmed they have seen the same issue.

**Comment by jtschuster** [comment]
Looks like this might have been causing an issue in a [rolling build](https://runfo.azurewebsites.net/view/build/?number=1880188) and a number of PRs. 
[Failures](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22methodical_ro%20work%20item%22)

Could be a separate issue though.

**Comment by hoyosjs** [comment]
Those failures are unrelated.

```
3D Array
Element manipulation of 5 by 6 by 5 matrices with different arithmatic operations
Process terminated. Assertion failed.
   at System.Number.FormatDouble(ValueStringBuilder& sb, Double value, ReadOnlySpan`1 format, NumberFormatInfo info)
   at System.Number.FormatDouble(Double value, String format, NumberFormatInfo info)
   at string1.Process3DArray(String[,,] a)
   at string1.TestEntryPoint()
   at Program.<Main>$(String[] args)
``` 

They do see libraries. There's one odd case there that doesn't have logs.
