### ISSUE TITLE
Test failure System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70273]
Run:[ runtime-libraries-coreclr outerloop 20220605.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1807657&view=ms.vss-test-web.build-test-results-tab&runId=48107550&resultId=104142&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.2110.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.10-helix-arm64v8-20211116135000-0f8d97e
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220427172132-97d8652
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-windows-Release-x64-CoreCLR_release-(Windows.10.Amd64.ServerRS5.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2019-helix-amd64-20220502135740-56c6673
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20220523142223-4f64125
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-windows-Release-x86-CoreCLR_release-Windows.11.Amd64.Client.Open
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-OSX-Release-arm64-CoreCLR_release-OSX.1200.ARM64.Open
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

net7.0-OSX-Release-x64-CoreCLR_release-OSX.1200.Amd64.Open
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-d]?[a-e]?[a-f]?[a-g]?[a-h]?\", anchor: \"$\", input: \"abcda\", pattern_repetition: 400, input_repetition: 4)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*?\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(engine: NonBacktracking, pattern: \"[a-e]*\", anchor: \"$\", input: \"abcde\", pattern_repetition: 2000, input_repetition: 20)
- System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: \"(\", inner: \"[aA]\", end: \")+\", options: None, input: \"aA\", pattern_repetition: 2000, input_repetition: 3000)
- System.Text.RegularExpressions.Tests.RegexMatchTests.Match_VaryingLengthStrings_Huge(engine: NonBacktracking)

```
**Error message:**
```
System.NotSupportedException : The specified pattern with RegexOptions.NonBacktracking could result in an automata as large as '10005' nodes, which is larger than the configured limit of '10000'.


Stack trace
   at System.Text.RegularExpressions.Symbolic.SymbolicRegexRunnerFactory..ctor(RegexTree regexTree, RegexOptions options, TimeSpan matchTimeout) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/SymbolicRegexRunnerFactory.cs:line 35
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 101
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 60
   at System.Text.RegularExpressions.Tests.RegexHelpers.GetRegexAsync(RegexEngine engine, String pattern, Nullable`1 options, Nullable`1 matchTimeout) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Tests.Common.cs:line 119
   at System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfConcat(RegexEngine engine, String pattern, String anchor, String input, Int32 pattern_repetition, Int32 input_repetition) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Match.Tests.cs:line 1930
--- End of stack trace from previous location ---
```

**Comment by danmoseley** [comment]
should be fixed by https://github.com/dotnet/runtime/pull/70246
