### ISSUE TITLE
Test failure JIT/Methodical/eh/interactions/gcincatch_ro/gcincatch_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70272]
Run: [runtime-coreclr gcstress-extra 20220604.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1807222&view=ms.vss-test-web.build-test-results-tab&runId=48103782&resultId=108159&paneView=debug)

Failed test:
```
coreclr Linux arm Checked gcstress0xc_jitminopts_heapverify1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/Methodical/eh/interactions/gcincatch_ro/gcincatch_ro.cmd

```
**Error message:**
```
Test Infrastructure Failure: System.AggregateException: One or more errors occurred. (Unknown socket error)
---> System.IO.IOException: Unknown socket error
---> System.Net.Sockets.SocketException (0xFFFDFFFE): Unknown socket error
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1460
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1047
at System.Net.Sockets.Socket.ReceiveAsync(Memory1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 327 at System.Net.Sockets.Socket.ReceiveAsync(Memory1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 310
at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory1 destination, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 307 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory1 destination, CancellationToken cancellationToken)
at System.IO.Pipes.PipeStream.ReadAsync(Memory1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 102 at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.ExecutionContextCallback(Object s) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.MoveNext(Thread threadPoolThread) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.MoveNext() at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) at System.Threading.Tasks.Task.FinishContinuations() at System.Threading.Tasks.Task1.TrySetResult(TResult result)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.SetExistingTaskResult(Task1 task, TResult result)
at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder1.SetResult(TResult result) at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory1 destination, CancellationToken cancellationToken) in //src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 313
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.ExecutionContextCallback(Object s)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.MoveNext(Thread threadPoolThread)
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.MoveNext()
at System.Threading.ThreadPool.<>c.<.cctor>b__78_0(Object state)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1321
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs ) in //src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 989


Stack trace
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 116
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String basePath, String assemblyPath)
   at Program.<Main>$(String[] args)
```
No Kusto information.

**Comment by AndyAyersMS** [comment]
Hard to believe this is still relevant, so closing.
