### ISSUE TITLE
Test failure baseservices\\exceptions\\stackoverflow\\stackoverflowtester\\stackoverflowtester.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70270]
Run: [runtime-coreclr jitstress-isas-x86 20220604.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1807172&view=ms.vss-test-web.build-test-results-tab&runId=48102224&paneView=debug&resultId=106199)

Failed test:
```
coreclr windows x64 Checked jitstress_isas_nohwintrinsic @ Windows.10.Amd64.Open

- baseservices\\exceptions\\stackoverflow\\stackoverflowtester\\stackoverflowtester.cmd

```
**Error message:**
```
Test Infrastructure Failure: System.InvalidOperationException: Process has exited, so the requested information is not available.
at System.Diagnostics.Process.get_ProcessName()
at CoreclrTestLib.CoreclrTestWrapperLib.FindChildProcessesByName(Process process, String childName)
at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir)
at baseservices_exceptions.stackoverflow_stackoverflowtester_stackoverflowtester._stackoverflow_stackoverflowtester_stackoverflowtester_cmd()
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._stackoverflow_stackoverflowtester_stackoverflowtester_._stackoverflow_stackoverflowtester_stackoverflowtester_cmd()
```
No Kusto information.

**Comment by janvorli** [comment]
This issue happens in the coreclr test running infrastructure, not in the test itself. It seems the code just needs to be hardened against child process exiting.
