### ISSUE TITLE
Test failure: Interop/PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#70296]
linux-x64, GCStress=0xC

https://dev.azure.com/dnceng/public/_build/results?buildId=1794742&view=ms.vss-test-web.build-test-results-tab&runId=47932734&resultId=101704&paneView=debug

```
+ cat /datadisks/disk1/work/B33E09CF/w/ABCE0985/u/SetStressModes_gcstress0xc.sh
#!/usr/bin/env bash
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_GCStress=0xC
...
  Starting:    Interop.PInvoke.XUnitWrapper (parallel test collections = on, max threads = 2)
    Interop/PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.sh [FAIL]
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/B33E09CF/w/ABCE0985/uploads/Reports/Interop.PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.output.txt
      Raw output:
      BEGIN EXECUTION
      /datadisks/disk1/work/B33E09CF/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false SetLastErrorTest.dll ''
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 1
      Actual:   42424
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at SetLastErrorTest.Main(String[] args)
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/B33E09CF/p
      > /datadisks/disk1/work/B33E09CF/w/ABCE0985/e/Interop/PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_PInvoke._SetLastError_SetLastErrorTest_SetLastErrorTest_._SetLastError_SetLastErrorTest_SetLastErrorTest_sh()
      Output:
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/B33E09CF/w/ABCE0985/uploads/Reports/Interop.PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.output.txt
        Raw output:
        BEGIN EXECUTION
        /datadisks/disk1/work/B33E09CF/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false SetLastErrorTest.dll ''
        Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 1
        Actual:   42424
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
           at SetLastErrorTest.Main(String[] args)
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/B33E09CF/p
        > /datadisks/disk1/work/B33E09CF/w/ABCE0985/e/Interop/PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.sh
```

**Comment by jkoritzinsky** [comment]
Looks like somewhere is trashing the last error now in GCStress.

**Comment by BruceForstall** [comment]
@AaronRobinsonMSFT I don't think it's appropriate to push this to "Future" milestone when it is causing outerloop job failures.

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Okay.
