### ISSUE TITLE
[wasm] DebuggerTests.EvaluateOnCallFrameTests.EvaluateExpressionsWithElementAccessByLocalVariable Failed

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#70310]
```
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [83] Starting /root/helix/work/correlation/firefox/firefox with -profile /root/helix/work/workitem/e/debugger-test/AppBundle/test-profile-83 -headless -new-instance -private -start-debugger-server 6583 http://localhost:9400/debugger-driver.html
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stderr *** You are running in headless mode.
**Browser died!**
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [test_id: 82] FirefoxProvider Dispose
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [test_id: 82] FirefoxProvider Dispose done
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 82] TestHarnessStartup done
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] TestHarnessStartup: closing for 82
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout [GFX1-]: glxtest: libpci missing
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout [GFX1-]: glxtest: libGL.so.1 missing
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout [GFX1-]: glxtest: libEGL missing
[19:06:47] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout [GFX1-]: No GPUs detected via PCI
[19:06:48] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
  Skipped DebuggerTests.EvaluateOnCallFrameTests.EvaluateOnPreviousFrames [1 ms]
  Skipped DebuggerTests.EvaluateOnCallFrameTests.EvaluateSimpleMethodCallsCheckChangedValue [1 ms]
[19:06:49] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout console.log: "determined url of main script to be http://localhost:9400/dotnet.js"
[19:06:50] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout console.debug: "Debugger.Debug: DEBUGGING ENABLED\n"
[19:06:50] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout console.debug: "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[19:06:50] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout console.debug: "Loaded 9149 symbols"
[19:06:50] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] browser-stdout console.log: "ready"
[19:06:50] dbug: Inspector-83[0] Connecting to the proxy at tcp://127.0.0.1:6002 ..
[19:06:50] dbug: Inspector-83[0] .. connected to the proxy!
[19:06:50] trce: Inspector-83[0] SendCommand: to: {   "type": "listTabs",   "to": "root" }
[19:06:50] info: Inspector-83[0] waiting for the runtime to be ready
[19:06:50] trce: Inspector-83[0] SendCommand: to: {   "type": "getWatcher",   "isServerTargetSwitchingEnabled": true,   "to": "server1.conn0.tabDescriptor1" }
[19:06:50] trce: Inspector-83[0] SendCommand: to: {   "type": "watchResources",   "resourceTypes": [     "console-message"   ],   "to": "server1.conn0.watcher3" }
[19:06:50] trce: Inspector-83[0] SendCommand: to: {   "type": "watchTargets",   "targetType": "frame",   "to": "server1.conn0.watcher3" }
[19:06:50] trce: Inspector-83[0] Updated threadActorId to server1.conn0.windowGlobal2147483650/thread1
[19:06:50] trce: Inspector-83[0] Updated consoleActorId to server1.conn0.windowGlobal2147483650/consoleActor3
[19:06:50] fail: FirefoxMonoProxy-83[0] Cannot respond to command: msg-:::0:::server1.conn0.windowGlobal2147483650/windowGlobalTarget2 with result: [Result: IsOk: True, IsErr: False, Value: {   "result": {     "value": {       "type": "frameUpdate",       "frames": [         {           "id": 9,           "isTopLevel": true,           "url": "http://localhost:9400/debugger-driver.html",           "title": ""         }       ],       "from": "server1.conn0.windowGlobal2147483650/windowGlobalTarget2"     }   } }, Error:  ] - command is not pending
[19:06:50] info: Inspector-83[0] console.log: determined url of main script to be http://localhost:9400/dotnet.js
[19:06:50] trce: Inspector-83[0] SendCommand: to: {   "type": "attach",   "options": {     "pauseOnExceptions": false,     "ignoreCaughtExceptions": true,     "shouldShowOverlay": true,     "shouldIncludeSavedFrames": true,     "shouldIncludeAsyncLiveFrames": false,     "skipBreakpoints": false,     "logEventBreakpoints": false,     "observeAsmJS": true,     "breakpoints": [],     "eventBreakpoints": []   },   "to": "server1.conn0.windowGlobal2147483650/thread1" }
[19:06:50] trce: Inspector-83[0] SendCommand: to: {   "type": "getBreakpointListActor",   "to": "server1.conn0.watcher3" }
[19:06:52] info: Inspector-83[0] runtime ready, TEST TIME
[19:06:52] trce: Inspector-83[0] SendCommand: to: {   "assemblyName": "debugger-test.dll",   "type": "DotnetDebugger.getMethodLocation",   "typeName": "DebuggerTests.EvaluateLocalsWithElementAccessTests",   "methodName": "EvaluateLocals",   "lineOffset": 5,   "to": "internal" }
[19:06:52] trce: Inspector-83[0] SendCommand: to: {   "type": "setBreakpoint",   "location": {     "line": 509,     "column": 0,     "sourceUrl": "dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs"   },   "to": "server1.conn0.breakpoint-list4" }
[19:06:52] fail: FirefoxMonoProxy-83[0] OnCommand for id: msg-:::0, {   "type": "setBreakpoint",   "location": {     "line": 509,     "column": 0,     "sourceUrl": "dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-evaluate-test.cs"   },   "to": "server1.conn0.breakpoint-list4" } failed: System.ArgumentNullException: Value cannot be null. (Parameter 's')    at System.Convert.FromBase64String(String s)    at Microsoft.WebAssembly.Diagnostics.MonoBinaryReader.From(Result result) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 439    at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.SendDebuggerAgentCommand[T](T command, MonoBinaryWriter arguments, CancellationToken token, Boolean throwOnError) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 910    at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.GetAssemblyId(String asm_name, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 1055    at Microsoft.WebAssembly.Diagnostics.MonoProxy.SetMonoBreakpoint(SessionId sessionId, String reqId, SourceLocation location, String condition, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1468    at Microsoft.WebAssembly.Diagnostics.MonoProxy.SetBreakpoint(SessionId sessionId, DebugStore store, BreakpointRequest req, Boolean sendResolvedEvent, Boolean fromEnC, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1652    at Microsoft.WebAssembly.Diagnostics.FirefoxMonoProxy.AcceptCommand(MessageId sessionId, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxMonoProxy.cs:line 432    at Microsoft.WebAssembly.Diagnostics.FirefoxMonoProxy.OnCommand(MessageId id, JObject parms, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxMonoProxy.cs:line 76
[19:06:52] info: Inspector-83[0] console.log: determined url of main script to be http://localhost:9400/dotnet.js
[19:06:52] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 83] TestHarnessStartup done
[19:06:52] dbug: DebuggerTests.TestHarnessProxy[0] TestHarnessStartup: closing for 83
[19:06:52] trce: Inspector-83[0] ** client socket closed, so stopping the client loop too
[19:06:52] dbug: Inspector-83[0] RunLoop stopped, reason: RunLoopExitState { reason = ConnectionClosed, exception = System.Exception: Connection id: client  ---> System.AggregateException: One or more errors occurred. ([ client connection ] Connection closed)  ---> System.Exception: [ client connection ] Connection closed    at Microsoft.WebAssembly.Diagnostics.FirefoxDebuggerConnection.<ReadOneAsync>g__CheckFail|10_0(<>c__DisplayClass10_0&) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Common/FirefoxDebuggerConnection.cs:line 77    at Microsoft.WebAssembly.Diagnostics.FirefoxDebuggerConnection.ReadOneAsync(CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Common/FirefoxDebuggerConnection.cs:line 42    --- End of inner exception stack trace ---    --- End of inner exception stack trace --- }
[19:06:52] dbug: Inspector-83[0] Failing 1 pending cmds
[19:06:52] dbug: Inspector-83[0] Shutdown was already requested once. Ignoring
[19:06:52] dbug: Inspector-84[0] Client connecting to ws://localhost:9400/launch-host-and-connect/?test_id=84&host=firefox&firefox-proxy-port=6002
[19:06:52] info: DebuggerTests.TestHarnessProxy[0] [testId: 84] New test request for test id 84
[19:06:52] dbug: DebuggerTests.TestHarnessProxy[0] [84] Starting /root/helix/work/correlation/firefox/firefox with -profile /root/helix/work/workitem/e/debugger-test/AppBundle/test-profile-84 -headless -new-instance -private -start-debugger-server 6584 http://localhost:9400/debugger-driver.html
[19:06:52] dbug: Inspector-83[0] RunLoop stopped, closing the websocket, state: Aborted
**Browser died!**
[xUnit.net 00:13:09.58]     DebuggerTests.EvaluateOnCallFrameTests.EvaluateExpressionsWithElementAccessByLocalVariable [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.EvaluateExpressionsWithElementAccessByLocalVariable [22 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 397
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 231
   at DebuggerTests.EvaluateOnCallFrameTests.EvaluateExpressionsWithElementAccessByLocalVariable() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 606
--- End of stack trace from previous location ---
```

Hit on unrelated PR https://github.com/dotnet/runtime/pull/70194

Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70194-merge-40682d4010bf475bab/firefox-DebuggerTests/1/console.0e127a17.log?helixlogtype=result
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1809200&view=logs&j=c7c013c2-b629-5fa5-abab-a8725284125b&t=6b7300c8-b6b8-57ee-0287-55d7d3c26e2c

**Comment by radical** [comment]
Firefox tests are known to be unstable currently, so we are not tracking them. Thank you for the report!
