### ISSUE TITLE
[wasm] Linker failure breaking rolling builds

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#70363]
Multiple browser builds are breaking with this, [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1810649&view=logs&j=06c2b9cd-9a25-5ea1-8363-c1b61a607e70&t=07e56740-dd3a-5379-9df5-8d02f9b6c188).

The changes since the last working build - https://github.com/dotnet/runtime/compare/f1cd5168...bab1a1f2 .

```
/_/src/libraries/System.Composition.Hosting/src/System/Composition/Hosting/Providers/ImportMany/ImportManyExportDescriptorProvider.cs(14,9): error IL1005: System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider..cctor(): Error processing method 'System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.GetImportManyDescriptor<TElement>(CompositionContract, CompositionContract, DependencyAccessor)' in assembly 'System.Composition.Hosting.dll'. [D:\a\_work\1\s\src\libraries\System.Composition.Hosting\tests\System.Composition.Hosting.Tests.csproj]
##[error]/_/src/libraries/System.Composition.Hosting/src/System/Composition/Hosting/Providers/ImportMany/ImportManyExportDescriptorProvider.cs(14,9): error IL1005: (NETCORE_ENGINEERING_TELEMETRY=Build) System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider..cctor(): Error processing method 'System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.GetImportManyDescriptor<TElement>(CompositionContract, CompositionContract, DependencyAccessor)' in assembly 'System.Composition.Hosting.dll'.
  Mono.Linker.LinkerFatalErrorException: /_/src/libraries/System.Composition.Hosting/src/System/Composition/Hosting/Providers/ImportMany/ImportManyExportDescriptorProvider.cs(14,9): error IL1005: System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider..cctor(): Error processing method 'System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider.GetImportManyDescriptor<TElement>(CompositionContract, CompositionContract, DependencyAccessor)' in assembly 'System.Composition.Hosting.dll'.
   ---> System.Collections.Generic.KeyNotFoundException: The given key 'System.Composition.Hosting.Providers.ImportMany.ImportManyExportDescriptorProvider/<>c__3`1' was not present in the dictionary.
     at Mono.Linker.CompilerGeneratedState.<PopulateCacheForType>g__MapGeneratedTypeTypeParameters|8_2(TypeDefinition generatedType, <>c__DisplayClass8_0&)
     at Mono.Linker.CompilerGeneratedState.<PopulateCacheForType>g__MapGeneratedTypeTypeParameters|8_2(TypeDefinition generatedType, <>c__DisplayClass8_0&)
     at Mono.Linker.CompilerGeneratedState.PopulateCacheForType(TypeDefinition type)
     at Mono.Linker.CompilerGeneratedState.GetGeneratedTypeAttributes(TypeDefinition generatedType)
     at ILLink.Shared.TrimAnalysis.FlowAnnotations.BuildTypeAnnotations(TypeDefinition type)
     at ILLink.Shared.TrimAnalysis.FlowAnnotations.GetAnnotations(TypeDefinition type)
     at ILLink.Shared.TrimAnalysis.FlowAnnotations.GetGenericParameterAnnotation(GenericParameter genericParameter)
     at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
     at Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger, Boolean throwOnFatalLinkerException)
D:\a\_work\1\s\.dotnet\sdk\7.0.100-preview.3.22179.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [D:\a\_work\1\s\src\libraries\System.Composition.Hosting\tests\System.Composition.Hosting.Tests.csproj]
```

cc @eerhardt @agocke @vitek-karas

**Comment by eerhardt** [comment]
#70082 seems pretty suspect. cc @jtschuster

**Comment by jtschuster** [comment]
@sbomer Looks like it's failing in handling compiler generated code.

**Comment by agocke** [comment]
Didn't realize we hadn't taken a linker build in a while -- this may be the result of my change. I'll investigate. How do I repro the problem?

**Comment by radical** [comment]
You can use this:

`./build.sh -ci -arch wasm -os Browser -s mono+libs+host+packs+libs.tests -c Release /p:ArchiveTests=true /p:BrowserHost=Linux /p:RunSmokeTestsOnly=False /p:EnableAggressiveTrimming=true /p:BuildAOTTestsOnHelix=true /p:RunAOTCompilation=false   /p:CrossBuild=false    `

**Comment by radical** [comment]
Can we revert that commit (https://github.com/dotnet/runtime/pull/70082) for now, because all the EAT/AOT builds for wasm are broken right now?

**Comment by maraf** [comment]
> Can we revert that commit (#70082) for now, because all the EAT/AOT builds for wasm are broken right now?

Reverting it didn't fix the problem.

**Comment by agocke** [comment]
I just checked in a linker change (https://github.com/dotnet/linker/pull/2827) that should fix the problem. It just has to flow to runtime.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/runtime/pull/69709
