### ISSUE TITLE
Crypto exception on startup with self-signed cert in Windows container

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#70386]
The .NET Docker repo has some [documentation](https://github.com/dotnet/dotnet-docker/blob/main/samples/host-aspnetcore-https.md) demonstrating how to use our sample container images. It describes how run the sample web app over HTTPS with a self-signed certificate. The scenario can lead to a startup failure when running the Windows version of the sample web app container.

Here's what I've been able to determine for the conditions in which this occurs:
* It's timing related. Sometimes the app will start successfully. Other times, it will fail. But it seems that once you can get things "warmed up", it will fail pretty consistently.
* It affects all versions of Windows containers. I've tried Windows Server 2019, 2022, and 20H2.
* It only occurs when running as ContainerUser (the default for Windows Nano Server). If you explicitly set the user to ContainerAdministrator, the issue goes away.

## Repro Steps

> Windows machine required

1. Install Docker Desktop
1. Install .NET 6 SDK
1. Set up the cert
    ```console
    dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p mypassword
    dotnet dev-certs https --trust
    ```
1. Run the container
    ```console
    docker run --rm -it -p 8000:80 -p 8001:443 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="mypassword" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v %USERPROFILE%\.aspnet\https:C:\https\ mcr.microsoft.com/dotnet/samples:aspnetapp-nanoserver-ltsc2022
    ```
    > The container image tag referenced above will give you the latest version. If you want the specific version I used at the time that I've created this issue and repro'd with, you can use `mcr.microsoft.com/dotnet/samples@sha256:b483d141a0516191d70fd7c14b453e36d7ed386d5185799f33a23270d46c0929`.

This command will either result in success or failure. In the success case, you'll see the following output:

```console
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory 'C:\Users\ContainerAdministrator\AppData\Local\ASP.NET\DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:443
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\app\
```

If it succeeds, press `Ctrl+C` to exit the container and try again. Keep rerunning the command until you hit the failure. For the failure case, you'll see the following:

```console
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory 'C:\Users\ContainerUser\AppData\Local\ASP.NET\DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Unhandled exception. Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: An internal error occurred.
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in C:\source\aspnetapp\Program.cs:line 30
```

This issue was originally investigated and captured in conversation at https://github.com/dotnet/dotnet-docker/pull/3366.

My theory is that this is caused by Windows itself asynchronously executing some startup logic while the .NET process is also starting up. And it's not yet initialized something that .NET requires to be initialized. That's just a wild guess at this point. Those of us on the .NET Docker team have seen behavior like that in Windows containers in previous investigations where there's additional initialization activity in the filesystem or registry even after the container's entrypoint process has been launched. But it requires more in-depth investigation before passing this off to the Windows container team to determine what's actually being accessed here and how it deviates from what would be expected.

**Comment by bartonjs** [comment]
We just opaquely call PFXImportCertStore; anything that it needs is a black box to us.

The one thing I know from years of people having trouble with IIS is that a loaded user profile is required.  So, if we're running concurrent with the user profile loader, that'd sound like the relevant race condition.
