### ISSUE TITLE
`ConsoleStream.ReadByte` throws when `Console.Encoding` is UTF-16

### ISSUE THREAD

**Issue by castholm** [dotnet/runtime#70448]
### Description

An `IOException` is thrown when invoking `Stream.ReadByte` on a stream obtained from `Console.OpenStandardInput` after having set `Console.Encoding` to `Encoding.Unicode`.

### Reproduction Steps

```csharp
using System;
using System.Text;

namespace ConsoleApp1;

class Program
{
    static void Main()
    {
        Console.InputEncoding = Encoding.Unicode;
        var stdin = Console.OpenStandardInput();
        _ = stdin.ReadByte();
    }
}
```

The same exception is also thrown if you invoke `Stream.Read` with a buffer of length 1:

```csharp
static void Main()
{
    Console.InputEncoding = Encoding.Unicode;
    var stdin = Console.OpenStandardInput();
    Span<byte> bytes = stackalloc byte[1];
    _ = stdin.Read(bytes);
}
```

### Expected behavior

`Stream.ReadByte` returns the least significant byte of the read code unit (and the most significant byte of the same code unit on the next `Stream.ReadByte` invocation).

-or-

A more descriptive exception (`NotSupportedException`?) with a more meaningful message is thrown if this is an explicitly unuspported scenario.

### Actual behavior

The following exception is thrown:

```
System.IO.IOException
  HResult=0x80070023
  Message=Unknown error (0x23)
  Source=System.Console
  StackTrace:
   at System.ConsolePal.WindowsConsoleStream.Read(Span`1 buffer)
   at System.IO.ConsoleStream.ReadByte()
   at ConsoleApp1.Program.Main() in C:\ConsoleApp1\Program.cs:line 12
```

### Known Workarounds

Invoking `Stream.Read` with a buffer of length 2 or more. You can also use `Encoding.CreateTranscodingStream` with both the inner and outer encodings set to UTF-16 to wrap the input stream.

### Configuration

.NET Core 6.0.300 / .NET Framework 4.8
Windows 10 x64

**Comment by danmoseley** [comment]
Apparently ReadFile failed with a last error of 35?  I can't find this code...

**Comment by danmoseley** [comment]
@jkotas do you know how to interpret this code? Presumably if we were to improve the error here, we would want to have some idea the error code is intended/used for.

**Comment by jkotas** [comment]
I am not able to find this error code either. 

> Would need a kernel debugger to know how it's coming up with that.

Yep

**Comment by adamsitnik** [comment]
It must be some secret error code, as it's missing on the [official list](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)

![image](https://user-images.githubusercontent.com/6011991/175324441-eb1f0997-b691-45e7-a952-ee98ef2e515a.png)

I am quite sure that it's by design (1 byte is not enough to represent a Unicode character), we should definitely throw more descriptive exception.

**Comment by eriawan** [comment]
@adamsitnik 

Just FYI, if we only look for 0x23 to search for Last Error Code, that error code of 35 is actually `ERROR_FCB_UNAVAILABLE`, by looking at inside of Windows 10 SDK's `Error.h` header file:

![image](https://user-images.githubusercontent.com/8773147/192624603-1b18529f-dcc8-4e1b-bd16-670c4557e2fb.png)

PS: AFAIK, this ERROR_FCB_UNAVAILABLE usually means that OS cannot allocate available FCB (file control blocks), therefore it may not be related to the exception at all.

Going further, using Microsoft Error Lookup (https://learn.microsoft.com/en-us/windows/win32/debug/system-error-code-lookup-tool) I have this:

![image](https://user-images.githubusercontent.com/8773147/192631622-98fd1060-270c-429d-94e2-45a63c12cf99.png)

and using that tool again to search for `0x80070023` then I got this:

![image](https://user-images.githubusercontent.com/8773147/192632519-4d3ab7a4-40ad-496a-8bc9-6a601e315388.png)
