### ISSUE TITLE
System.Uri regression in .NET 7

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#70443]
### Description

Context: https://github.com/dotnet/maui/pull/7859

After we got .NET MAUI in .NET 7, we started hitting a failure during builds that happens maybe %50 of the time:

```
XamlApp.xaml Invalid URI: The hostname could not be parsed. [D:\a\_work\1\s\src\Controls\samples\Controls.Sample\Maui.Controls.Sample.csproj]
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
at System.Uri..ctor(String uriString, UriKind uriKind)
at Microsoft.Maui.Controls.ResourceDictionary.RDSourceTypeConverter.GetResourcePath(Uri uri, String rootTargetPath)
at Microsoft.Maui.Controls.XamlC.RDSourceTypeConverter.ConvertFromString(String value, ILContext context, BaseNode node)+MoveNext()
at Microsoft.Maui.Controls.Build.Tasks.NodeILExtensions.PushConvertedValue(ValueNode node, ILContext context, TypeReference targetTypeRef, TypeReference typeConverter, IEnumerable`1 pushServiceProvider, Boolean boxValueTypes, Boolean unboxValueTypes)+MoveNext()
at Microsoft.Maui.Controls.Build.Tasks.SetPropertiesVisitor.Set(VariableDefinition parent, String localName, INode node, IXmlLineInfo iXmlLineInfo, ILContext context)+MoveNext()
at Microsoft.Maui.Controls.Build.Tasks.ILProcessorExtensions.Append(ILProcessor processor, IEnumerable`1 instructions)
at Microsoft.Maui.Controls.Build.Tasks.SetPropertiesVisitor.Visit(ValueNode node, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Build.Tasks.SetResourcesVisitor.Visit(ElementNode node, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Build.Tasks.XamlCTask.TryCoreCompile(MethodDefinition initComp, ILRootNode rootnode, String xamlFilePath, Exception& exception)
```

This is failing inside this method:

https://github.com/dotnet/maui/blob/8b8954b0530ec0d59a97d3b2cc75043b4951b30a/src/Controls/src/Core/ResourceDictionary.cs#L384-L393

I added some logging around the failure to get more information:
```
GetResourcePath failed:
uri=AppResources.xaml
OriginalString=AppResources.xaml
rootTargetPath=XamlApp.xaml
Message=Invalid URI: The hostname could not be parsed.
StackTrace=
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.Maui.Controls.ResourceDictionary.RDSourceTypeConverter.GetResourcePath(Uri uri, String rootTargetPath)
```

What is strange, is this unit test passes with the same input:

```csharp
[Test]
public void GetResourcePath()
{
    var result = ResourceDictionary.RDSourceTypeConverter.GetResourcePath(new Uri("AppResources.xaml", UriKind.Relative), "XamlApp.xaml");
    Assert.IsNotNull(result);
    Assert.IsNotEmpty(result);
}
```

### Reproduction Steps

I was able to reproduce this locally *once*, but it seems to happen on CI more frequently.

The repro steps would be:

1. clone dotnet/maui
2. `./build.ps1 --target=dotnet-build`

And even then, it doesn't seem to happen each time.

### Expected behavior

System.Uri doesn't throw an exception for the above input.

### Actual behavior

System.Uri throws an exception.

### Regression?

Yes, this works in .NET 6.

### Known Workarounds

Catch `UriFormatException`?

### Configuration

.NET SDK 7.0.100-preview.6.22276.1

It also seems to happen on Windows, I don't recall it happening on Mac.

**Comment by MihaZupan** [comment]
The only case where Uri parsing isn't 100% deterministic and repeatable is if you are registering a custom `UriParser`.

Consider the following code:
```c#
const string UriString = "pack:///XamlApp.xaml/../AppResources.xaml";

_ = new Uri(UriString, UriKind.Absolute); // OK

UriParser.Register(new GenericUriParser(GenericUriParserOptions.GenericAuthority), "pack", -1);

_ = new Uri(UriString, UriKind.Absolute); // The hostname could not be parsed.
```
which will succeed the first time, but throw after a custom parser is registered.

I suspect if you add `Debug.Assert(!UriParser.IsKnownScheme("pack"))` in `GetResourcePath`, you would see it blow up in all the cases you would hit the exception otherwise.

It's likely your move from 6.0 to 7.0 brought in more changes that included a component that now registers the parser. E.g. I can see a mention of such a thing in the [`PackUriHelper`](https://github.com/dotnet/runtime/blob/3cc587e1d037b054e785f1e758edec8490fa62ea/src/libraries/System.IO.Packaging/src/System/IO/Packaging/PackUriHelper.PackUriScheme.cs#L240) from `System.IO.Packaging` (just a guess - could be other code).

Looking at your `GetResourcePath` code, it seems like it could be using `Path` APIs instead.

**Comment by jonathanpeppers** [comment]
Yeah, this code came from Xamarin.Forms, no idea about it.

`UriParser.Register()` isn't used anywhere in dotnet/maui, is this something that could be configured by something like an env var?

**Comment by jonathanpeppers** [comment]
Oh... this is running inside MSBuild, maybe they do it.

**Comment by stephentoub** [comment]
I see this in a WPF build task:
https://github.com/dotnet/wpf/blob/144290982a74ce332d78e873cf52e3c4cb789d29/src/Microsoft.DotNet.Wpf/src/PresentationBuildTasks/MS/Internal/MarkupCompiler/MarkupCompiler.cs#L1811

**Comment by stephentoub** [comment]
And as Miha alludes to, any direct or indirect use of PackUriHelper will trigger a similar registration via its static ctor:
https://github.com/dotnet/runtime/blob/eef6c7f6cb7f73163313d349fbb796f37b4c3996/src/libraries/System.IO.Packaging/src/System/IO/Packaging/PackUriHelper.PackUriScheme.cs#L226-L229

**Comment by jonathanpeppers** [comment]
It looks like avoiding `pack://` solves the problem. I think we can close this.

The MSBuild node reuse is unfortunate, but I'm not sure if there is any action to take on that. Thanks!
