### ISSUE TITLE
Invalid path length for use with domain sockets on iOS/tvOS platform

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#70468]
Test `System.Net.Sockets.Tests.UnixDomainSocketTest.FilePathEquality` is failing on iOS/tvOS on runtime-extra-platforms

- [#20220608.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1813081&view=logs&j=e4e455c5-b032-5051-d2c5-a64982c9ac45&t=0263a457-10d3-5b56-3414-171b09292e09)
- [#20220608.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1814339&view=logs&j=e4e455c5-b032-5051-d2c5-a64982c9ac45)

```
System.ArgumentOutOfRangeException : The path '/Users/helix-runner/Library/Developer/CoreSimulator/Devices/5EC24E24-135D-45F8-A9C3-983B5638CD6F/data/Containers/Data/Application/217F4D6F-DDF0-4387-AE45-F5A6F237C8C9/tmp/xiqumhmj.pd3AAAAAAAAA' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')\nActual value was /Users/helix-runner/Library/Developer/CoreSimulator/Devices/5EC24E24-135D-45F8-A9C3-983B5638CD6F/data/Containers/Data/Application/217F4D6F-DDF0-4387-AE45-F5A6F237C8C9/tmp/xiqumhmj.pd3AAAAAAAAA.
   at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path, String boundFileName)
   at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path)
   at System.Net.Sockets.Tests.UnixDomainSocketTest.FilePathEquality()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

Test added in https://github.com/dotnet/runtime/pull/69722

|Build|Kind|Start Time|
|---|---|---|
[1813081](https://dev.azure.com/dnceng/public/_build/results?buildId=1813081)|Rolling|2022-08-06|
[1814339](https://dev.azure.com/dnceng/public/_build/results?buildId=1814339)|Rolling|2022-08-06|

**Comment by rzikm** [comment]
Looks like the `GetRandomNonExistingFilePath` produces too long paths, perhaps the same reason why other tests which use it are disabled on those platforms.
