### ISSUE TITLE
JSON source gen does not work correctly with nullable structs with custom converter

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#70475]
Repro:

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Repro
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // prints: {"Bar":"B"}
            Console.WriteLine(JsonSerializer.Serialize<FooStruct>(new FooStruct { Bar = Foo.B }));

            // error, see below for more details
            Console.WriteLine(JsonSerializer.Serialize<FooStruct>(new FooStruct { Bar = Foo.B }, EnumContext.Default.FooStruct));
        }
    }

    [JsonSerializable(typeof(FooStruct))]
    internal partial class EnumContext : JsonSerializerContext
    {

    }

    internal struct FooStruct
    {
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public Foo? Bar { get; set; }
    }

    internal enum Foo
    {
        A,
        B
    }
}
```

Exception message:

```
Unhandled exception. System.ArgumentException: GenericArguments[0], 'System.Nullable`1[Repro.Foo]', on 'System.Text.Json.Serialization.Converters.EnumConverter`1[T]' violates the constraint of type 'T'.
 ---> System.TypeLoadException: GenericArguments[0], 'System.Nullable`1[Repro.Foo]', on 'System.Text.Json.Serialization.Converters.EnumConverter`1[T]' violates the constraint of type parameter 'T'.
   at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(RuntimeType inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Text.Json.Serialization.Converters.EnumConverterFactory.Create(Type enumType, EnumConverterOptions converterOptions, JsonNamingPolicy namingPolicy, JsonSerializerOptions serializerOptions)
   at Repro.EnumContext.GetConverterFromFactory(Type type, JsonConverterFactory factory) in C:\Users\kwicher\source\repos\ConsoleApp89\ConsoleApp89\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\EnumContext.g.cs:line 69
   at Repro.EnumContext.GetConverterFromFactory[T](JsonConverterFactory factory) in C:\Users\kwicher\source\repos\ConsoleApp89\ConsoleApp89\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\EnumContext.g.cs:line 64
   at Repro.EnumContext.FooStructPropInit(JsonSerializerContext context) in C:\Users\kwicher\source\repos\ConsoleApp89\ConsoleApp89\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\EnumContext.FooStruct.g.cs:line 50
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache()
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteUsingGeneratedSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingGeneratedSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonTypeInfo`1 jsonTypeInfo)
   at Repro.Program.Main(String[] args) in C:\Users\kwicher\source\repos\ConsoleApp89\ConsoleApp89\Program.cs:line 10
```

**Comment by smokedlinq** [comment]
@krwq ran across this today. Any suggested workarounds while we wait for a fix?

**Comment by eiriktsarpalis** [comment]
Fixed in https://github.com/dotnet/runtime/pull/84208
