### ISSUE TITLE
Test `System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UnifiedHello_Ok` is failing on windows

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#70470]
Test `System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UnifiedHello_Ok` is failing on windows on runtime-extra-platforms

- [#20220608.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1814339&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d)

```
System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UnifiedHello_Ok(useOptionCallback: True) [FAIL]
    System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
    ---- System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
    Stack Trace:
    /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(359,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
    /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs(1071,0): at System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UnifiedHello_Ok(Boolean useOptionCallback)
    --- End of stack trace from previous location ---
    ----- Inner Stack Trace -----
    
System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UnifiedHello_Ok(useOptionCallback: False) [FAIL]
    System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
    ---- System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
    Stack Trace:
    /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(359,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
    /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs(1071,0): at System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UnifiedHello_Ok(Boolean useOptionCallback)
    --- End of stack trace from previous location ---
    ----- Inner Stack Trace -----
```

|Build|Kind|Start Time|
|---|---|---|
[1814339](https://dev.azure.com/dnceng/public/_build/results?buildId=1814339)|Rolling|2022-08-06|

**Comment by maraf** [comment]
cc @wfurt
