### ISSUE TITLE
[mono] Fix SuppressGCTransitionTest for Mono FullAOT mode

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#70490]
### Summary

The runtime test: `Interop/SuppressGCTransition/SuppressGCTransitionTest/SuppressGCTransitionTest.dll` fails in FullAOT mode on Mono with the following output:
 
```
Inline_NoGCTransition (1) ...
Inline_GCTransition (2) ...
NoInline_NoGCTransition (3) ...
NoInline_GCTransition (4) ...
Mixed (5) ...
Mixed_TightLoop (9) ...
Inline_NoGCTransition (266) ...
Inline_GCTransition (267) ...
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper managed-to-native) int SuppressGCTransitionTest:wrapper_native_indirect_0x6000012e8b40 (intptr&,int*)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

   at SuppressGCTransitionTest.Inline_GCTransition_FunctionPointer(Int32 expected) in /Users/ivan/repos/runtime-mono-AOT/src/tests/Interop/SuppressGCTransition/SuppressGCTransitionTest.cs:line 208
   at SuppressGCTransitionTest.Main(String[] args)
Expected: 100
Actual: 101
END EXECUTION - FAILED
```

### Repro
1) Enable building the test with Mono AOT
``` diff
diff --git a/src/tests/Interop/SuppressGCTransition/SuppressGCTransitionTest.csproj b/src/tests/Interop/SuppressGCTransition/SuppressGCTransitionTest.csproj
index c08644530f6..abb1fec49b7 100644
--- a/src/tests/Interop/SuppressGCTransition/SuppressGCTransitionTest.csproj
+++ b/src/tests/Interop/SuppressGCTransition/SuppressGCTransitionTest.csproj
@@ -2,7 +2,6 @@
   <PropertyGroup>
     <OutputType>Exe</OutputType>
     <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
-    <MonoAotIncompatible>true</MonoAotIncompatible>
   </PropertyGroup>
   <ItemGroup>
     <Compile Include="$(InteropCommonDir)CheckGCMode.cs" />
```
2) Build Mono
``` bash
./build.sh mono+libs+clr.hosts -c debug /p:MonoEnableLlvm=true /p:MonoLLVMUseCxx11Abi=true
```
3) Build the test
``` bash 
./src/tests/build.sh mono debug /p:LibrariesConfiguration=Debug -test:Interop/SuppressGCTransition/SuppressGCTransitionTest.csproj
```
4) AOT compile the test
``` bash
./src/tests/build.sh mono_fullaot debug /p:LibrariesConfiguration=Debug -test:Interop/SuppressGCTransition/SuppressGCTransitionTest.csproj
```
5) Run the test (note: adjust the paths)
``` bash
MONO_ENV_OPTIONS=--full-aot bash /Users/ivan/repos/runtime-mono-AOT/artifacts/tests/coreclr/OSX.arm64.Debug/Interop/SuppressGCTransition/SuppressGCTransitionTest/SuppressGCTransitionTest.sh -coreroot=/Users/ivan/repos/runtime-mono-AOT/artifacts/tests/coreclr/OSX.arm64.Debug/Tests/Core_Root
```

### Additional notes
Reason for the test exclusion should be updated here: 
https://github.com/dotnet/runtime/blob/3d74b00659fec817506e2888f87936518556e01c/src/tests/issues.targets#L2824-L2826

**Comment by ivanpovazan** [comment]
@lambdageek should we try to fix this for .NET7?

**Comment by ivanpovazan** [comment]
Moving to 9.0.0
