### ISSUE TITLE
Cannot extract shared runtime tar-ball with TarFile.ExtractToDirectory

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#70509]
### Description

Hit a `FormatException` when extracting a .tar.gz file.  I ran into this using the work item extraction I recently added to runfo: https://github.com/jaredpar/runfo/pull/152

### Reproduction Steps

Download https://dotnetcli.azureedge.net/dotnet/Runtime/6.0.5-servicing.22213.9/dotnet-runtime-6.0.5-osx-x64.tar.gz.
Pass this to `TarFile.ExtractToDirectory`, eg:
```c#
TarFile.ExtractToDirectory(@"c:\scratch\aspnetrepro\correlation-payload\dotnet-runtime-6.0.5-osx-x64.tar.gz", @".\", true);
```

### Expected behavior

Successfully extracts tar file

### Actual behavior

```
Unhandled exception. System.FormatException: Could not find any recognizable digits.
   at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToInt32(String value, Int32 fromBase)
   at System.Formats.Tar.TarHelpers.GetTenBaseNumberFromOctalAsciiChars(Span`1 buffer)
   at System.Formats.Tar.TarHeader.TryReadCommonAttributes(Span`1 buffer)
   at System.Formats.Tar.TarHeader.TryGetNextHeader(Stream archiveStream, Boolean copyData)
   at System.Formats.Tar.TarReader.TryGetNextEntryHeader(TarHeader& header, Boolean copyData)
   at System.Formats.Tar.TarReader.GetNextEntry(Boolean copyData)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternal(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen)
   at System.Formats.Tar.TarFile.ExtractToDirectory(String sourceFileName, String destinationDirectoryName, Boolean overwriteFiles)
```

### Regression?

No

### Configuration

.NET 7.0 preview 5, windows 11

**Comment by carlossanlop** [comment]
Thanks for reporting, Eric.

The first argument is passing the _compressed_ archive. The tar APIs only handle uncompressed archives. 

```cs
using FileStream compressedStream = File.OpenRead(@"c:\scratch\aspnetrepro\correlation-payload\dotnet-runtime-6.0.5-osx-x64.tar.gz");
using GZipStream decompressor = new(compressedStream, CompressionMode.Decompress);
TarFile.ExtractToDirectory(source: decompressor, destinationDirectoryName: ".\", overwriteFiles: true);
```

But I did find another bug: The archive contains entries whose paths begin with `./`, including an initial entry with the root folder literally named `./`. I will open another issue to get this addressed ASAP.

**Comment by ericstj** [comment]
Do you have an issue tracking the addition of APIs to support extracting a compressed `tar.gz`?

**Comment by carlossanlop** [comment]
> Do you have an issue tracking the addition of APIs to support extracting a compressed `tar.gz`?

I do not, I'll open one too. Thanks @ericstj.

**Comment by carlossanlop** [comment]
> Do you have an issue tracking the addition of APIs to support extracting a compressed `tar.gz`?

Opened https://github.com/dotnet/runtime/issues/70517

**Comment by danmoseley** [comment]
Presumbly it's going to be common to attempt to open a .tar.gz with this API. Can we provide a better message than "Unhandled exception. System.FormatException: Could not find any recognizable digits." ? Even @ericstj apparently didn't realize the problem.
