### ISSUE TITLE
Test `ClientOptions_TargetHostNull_OK` is failing on Android

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#70548]
Test `ClientOptions_TargetHostNull_OK` is failing on Android on runtime-extra-platforms

- [#20220609.10](https://dev.azure.com/dnceng/public/_build/results?buildId=1816458&view=logs&j=ce8bb18a-3299-5fcd-e022-e51015a098bb&t=ba57798b-4339-5c09-4389-8cb6ee18eeba)
- [testResults.xml](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d781613ab83c4484a7/System.Net.Security.Tests/1/testResults.xml?helixlogtype=result)

```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.\n---- Interop+AndroidCrypto+SslException : Exception of type 'Interop+AndroidCrypto+SslException' was thrown
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__144`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Security.Tests.SslClientAuthenticationOptionsTestBase.ClientOptions_TargetHostNull_OK() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslAuthenticationOptionsTest.cs:line 130
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.\n---- Interop+AndroidCrypto+SslException : Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__144`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Security.Tests.SslClientAuthenticationOptionsTestBase.ClientOptions_TargetHostNull_OK() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslAuthenticationOptionsTest.cs:line 130
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

Test added in https://github.com/dotnet/runtime/pull/69071

|Build|Kind|Start Time|
|---|---|---|
[1816458](https://dev.azure.com/dnceng/public/_build/results?buildId=1816458)|Rolling|2022-09-06|

**Comment by maraf** [comment]
cc @wfurt
