### ISSUE TITLE
`JIT\HardwareIntrinsics\General\Vector256` test crashes with an `SEHException` on a machine without AVX2

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#70663]
Reproduction: compile and run the `src\tests\JIT\HardwareIntrinsics\General\Vector256\Vector256_ro.csproj` test on a machine without AVX2.

Expected result: test passes.

Actual result: test crashes:
```
Ending test case at 13.06.2022 14:59:50
Beginning test case AndNot.Byte at 13.06.2022 14:59:50
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Runtime.Intrinsics.Vector256.AndNot[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.Intrinsics.Vector256`1<Byte>, System.Runtime.Intrinsics.Vector256`1<Byte>)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at JIT.HardwareIntrinsics.General.VectorBinaryOpTest__AndNotByte.RunReflectionScenario_UnsafeRead()
   at JIT.HardwareIntrinsics.General.Program.AndNotByte()
   at JIT.HardwareIntrinsics.General.Program.Main(System.String[])
```

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.
