### ISSUE TITLE
System.Reflection.Module.ResolveXXX doesn't work with runtime-generated methods

### ISSUE THREAD

**Issue by jl0pd** [dotnet/runtime#70722]
### Description

I've stumbled across problem with generated modules - it's impossible to get string for `ldstr` instruction when method is generated with `System.Reflection.Emit.AssemblyBuilder`. It makes unit testing for runtime code generation less complete, when I can't check operands. Problem goes beyond `ResolveString`, anything declared in other modules throws exception

### Reproduction Steps

Compile and run code

```csharp
using System.Buffers.Binary;
using System.Reflection;
using System.Reflection.Emit;

class Program
{
    public static void Main()
    {
        Compiled(); // success
        RefEmit(); // fail
    }

    private static void Compiled()
    {
        ShowFirstString(typeof(Program).GetMethod("SayHello")!);
    }

    private static void RefEmit()
    {
        var asm = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("asd"), AssemblyBuilderAccess.Run);
        var module = asm.DefineDynamicModule("module");
        var type = module.DefineType("type");

        var method = type.DefineMethod("foo", MethodAttributes.Public | MethodAttributes.Static);

        var il = method.GetILGenerator();
        il.Emit(OpCodes.Ldstr, "Hello, World");
        il.Emit(OpCodes.Call, typeof(Console).GetMethod("WriteLine", BindingFlags.Public | BindingFlags.Static, new[] { typeof(string) })!);
        il.Emit(OpCodes.Ret);

        var builtType = type.CreateType()!;
        ShowFirstString(builtType.GetMethod("foo")!);
    }

    public static void SayHello()
    {
        Console.WriteLine("Hello, World");
    }

    private static void ShowFirstString(MethodInfo method)
    {
        var body = method.GetMethodBody()!.GetILAsByteArray();
        int stringToken = BinaryPrimitives.ReadInt32LittleEndian(body.AsSpan(2, 4));
        Console.WriteLine(method.Module.ResolveString(stringToken));
    }
}
```

### Expected behavior

Both `Compiled` and `RefEmit` are executed without errors

### Actual behavior

`RefEmit` throws 

```
Unhandled exception. System.ArgumentException: Token 28700000 is not a valid string token in the scope of module ModuleResolveString.dll.
   at System.Reflection.RuntimeModule.ResolveString(Int32 metadataToken)
   at Program.ShowFirstString(MethodInfo method)
   at Program.Compiled()
   at Program.Main()
```

### Known Workarounds

https://stackoverflow.com/questions/4148297/resolving-the-tokens-found-in-the-il-from-a-dynamic-method, but it's for `DynamicMethod`, not for `System.Reflection.Emit.AssemblyBuilder`, which produces `RuntimeMethodInfo`

### Configuration

Sdk: net 6.0.300
Commit:  8473146e7d
Windows 10

<details>
  <summary>dotnet --info</summary>
  .NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.419 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.105 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

**Comment by jkotas** [comment]
>         int stringToken = BinaryPrimitives.ReadInt32LittleEndian(body.AsSpan(2, 4));

The string token is at offset 1 in the ref.emit case. Change this to `AsSpan(1, 4)` for the ref emit case and it will work just fine.

**Comment by jl0pd** [comment]
Oh, yes, sure. I've forgot about extra `nop` instruction in debug version. Release works fine with `AsSpan(1, 4)`.
