### ISSUE TITLE
Test failure tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70766]
Run:[ runtime-coreclr outerloop 20220614.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1825283&view=ms.vss-test-web.build-test-results-tab&runId=48380928&resultId=106628&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\9F0D08B4\w\BA1E09D6\uploads\Reports\tracing.eventpipe\diagnosticport\diagnosticport\diagnosticport.output.txt
Raw output:
BEGIN EXECUTION
common.dll
diagnosticport.dll
Microsoft.Diagnostics.NETCore.Client.dll
3 file(s) copied.
23:14:42.99
Response file: D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\common.dll.rsp
D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\IL-CG2\common.dll
-o:D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\common.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\9F0D08B4\p\System..dll
-r:D:\h\w\9F0D08B4\p\Microsoft..dll
-r:D:\h\w\9F0D08B4\p\mscorlib.dll
-r:D:\h\w\9F0D08B4\p\netstandard.dll
-O
" "dotnet" "D:\h\w\9F0D08B4\p\crossgen2\crossgen2.dll" @"D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\common.dll.rsp"   -r:D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\common.dll
23:14:47.33
23:14:47.35
Response file: D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticport.dll.rsp
D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\IL-CG2\diagnosticport.dll
-o:D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticport.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\9F0D08B4\p\System..dll
-r:D:\h\w\9F0D08B4\p\Microsoft..dll
-r:D:\h\w\9F0D08B4\p\mscorlib.dll
-r:D:\h\w\9F0D08B4\p\netstandard.dll
-O
" "dotnet" "D:\h\w\9F0D08B4\p\crossgen2\crossgen2.dll" @"D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticport.dll.rsp"   -r:D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticport.dll
23:14:51.42
23:14:51.46
Response file: D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\Microsoft.Diagnostics.NETCore.Client.dll.rsp
D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\IL-CG2\Microsoft.Diagnostics.NETCore.Client.dll
-o:D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\Microsoft.Diagnostics.NETCore.Client.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\9F0D08B4\p\System..dll
-r:D:\h\w\9F0D08B4\p\Microsoft..dll
-r:D:\h\w\9F0D08B4\p\mscorlib.dll
-r:D:\h\w\9F0D08B4\p\netstandard.dll
-O
" "dotnet" "D:\h\w\9F0D08B4\p\crossgen2\crossgen2.dll" @"D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\Microsoft.Diagnostics.NETCore.Client.dll.rsp"   -r:D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\Microsoft.Diagnostics.NETCore.Client.dll
23:14:56.22
"D:\h\w\9F0D08B4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  diagnosticport.dll
0.0s: ::== Running test: TEST_MultipleConnectPortsNoSuspend
0.3s: Server 0 address is 'DOTNET_TRACE_TESTS_n4i4fovh.qvo'
0.3s: Server 1 address is 'DOTNET_TRACE_TESTS_uuljjjp0.b20'
0.3s: Server 2 address is 'DOTNET_TRACE_TESTS_52aak0h3.2l0'
0.3s: Server 3 address is 'DOTNET_TRACE_TESTS_fh3c5ulm.hdj'
0.3s: export DOTNET_DiagnosticPorts=DOTNET_TRACE_TESTS_n4i4fovh.qvo,nosuspend;DOTNET_TRACE_TESTS_uuljjjp0.b20,nosuspend;DOTNET_TRACE_TESTS_52aak0h3.2l0,nosuspend;DOTNET_TRACE_TESTS_fh3c5ulm.hdj,nosuspend;
0.3s: running sub-process: D:\h\w\9F0D08B4\p\corerun.exe D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticpo


Stack trace
   at tracing_eventpipe._diagnosticport_diagnosticport_diagnosticport_._diagnosticport_diagnosticport_diagnosticport_cmd()
```
No Kusto information.

**Comment by janvorli** [comment]
The actual relevant part of the output is this:
```
  6.3s: ::== Running test: TEST_CanGetProcessInfo2WhileSuspended
  6.3s: running sub-process: D:\h\w\9F0D08B4\p\corerun.exe D:\h\w\9F0D08B4\w\BA1E09D6\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticport.dll 0
  6.4s: subprocess started: True
  6.4s: subprocess PID: 1336
  6.4s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
  6.5s: Wrote: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=4; Reserved=0 }; }
  6.5s: Received: [38 05 00 00 00 00 00 00 5B EE 1C 0F 5D 7C 87 43 8A 14 D0 6A 5C B4 F5 84 82 00 00 00 22 00 44 00 3A 00 5C 00 68 00 5C 00 77 00 5C 00 39 00 46 00 30 00 44 00 30 00 38 00 42 00 34 00 5C 00 70 00 5C 00 63 00 6F 00 72 00 65 00 72 00 75 00 6E 00 2E 00 65 00 78 00 65 00 22 00 20 00 44 00 3A 00 5C 00 68 00 5C 00 77 00 5C 00 39 00 46 00 30 00 44 00 30 00 38 00 42 00 34 00 5C 00 77 00 5C 00 42 00 41 00 31 00 45 00 30 00 39 00 44 00 36 00 5C 00 65 00 5C 00 74 00 72 00 61 00 63 00 69 00 6E 00 67 00 5C 00 65 00 76 00 65 00 6E 00 74 00 70 00 69 00 70 00 65 00 5C 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 5C 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 5C 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 2E 00 64 00 6C 00 6C 00 20 00 30 00 00 00 08 00 00 00 57 00 69 00 6E 00 64 00 6F 00 77 00 73 00 00 00 06 00 00 00 61 00 72 00 6D 00 33 00 32 00 00 00 01 00 00 00 00 00 09 00 00 00 37 00 2E 00 30 00 2E 00 30 00 2D 00 63 00 69 00 00 00 ]
 13.8s: ================= Subprocess Exited =================
 16.5s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=1; Reserved=0 }; }
 16.5s: - Exit code: -1073740286
 16.5s: Subprocess stdout: 
 16.5s: Subprocess stderr: 
	  5.3s: Assert failure(PID 1336 [0x00000538], Thread: 9824 [0x2660]): IsSet()
	  5.3s: <no module>! <no symbol> + 0x0 (0x00000000)
	  5.3s:     File: D:\a\_work\1\s\src\coreclr\inc\clrconfignocache.h Line: 34
	  5.3s:     Image: D:\h\w\9F0D08B4\p\corerun.exe
 16.9s: System.Exception: Process 1336 is not running.
   at Tracing.Tests.Common.ConnectionHelper.GetStandardTransport(Int32 processId)
   at Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation.<>c.<TEST_CanGetProcessInfo2WhileSuspended>b__6_0(Int32 pid)
   at Tracing.Tests.Common.Utils.RunSubprocess(Assembly currentAssembly, Dictionary`2 environment, Func`1 beforeExecution, Func`2 duringExecution, Func`1 afterExecution)
 16.9s: Calling process.Kill()
 16.9s: ----------------------------------------
 16.9s: Subprocess stdout: 
 16.9s: Subprocess stderr: 
	  5.3s: Assert failure(PID 1336 [0x00000538], Thread: 9824 [0x2660]): IsSet()
	  5.3s: <no module>! <no symbol> + 0x0 (0x00000000)
	  5.3s:     File: D:\a\_work\1\s\src\coreclr\inc\clrconfignocache.h Line: 34
	  5.3s:     Image: D:\h\w\9F0D08B4\p\corerun.exe
 16.9s: ----------------------------------------
 16.9s: Test passed: False
```
The assert that fires is here:
https://github.com/dotnet/runtime/blob/b9f899e8978fc9e6101823fc630cfc17ab45a7ae/src/coreclr/inc/clrconfignocache.h#L32-L36

I can only see two callers of that function that don't check for the IsSet before calling it:
https://github.com/dotnet/runtime/blob/b9f899e8978fc9e6101823fc630cfc17ab45a7ae/src/coreclr/utilcode/clrconfig.cpp#L209
https://github.com/dotnet/runtime/blob/b9f899e8978fc9e6101823fc630cfc17ab45a7ae/src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h#L348

Unfortunately there is no dump available and the call stack above doesn't show the caller. But my guess is that it is the latter.
