### ISSUE TITLE
JsonNode? control = JsonNode.Parse(json) => System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Paul-Grimes** [dotnet/runtime#70785]
### Description

Specified Argument was out of the range of valid values. (Parameter 'minimumLength')

### Reproduction Steps

Run into this issue with a JSON files that are greater then 800 MB.  Does not work on files that are 400 MB or less.

The json variable is:

`string json = File.ReadAllText(path);`

### Expected behavior

I was expecting it to be able to parse the string data.  The string should be able to hold up to 2 GB.

### Actual behavior

When the file was at 800MB I get a System.ArgumentOutOfRangeException.

**Comment by svick** [comment]
I can reproduce this using the following code:

```c#
StringBuilder sb = new("[");

while (sb.Length < 200_000_000)
{
    sb.Append("0,");
}
sb.Append("0]");

var node = JsonNode.Parse(sb.ToString());
```

The full exception is:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'minimumLength')
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at System.Text.Json.JsonDocument.MetadataDb.Enlarge()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
   at UserQuery.Main()
```

**Comment by eiriktsarpalis** [comment]
@Paul-Grimes could you confirm that @svick's reproduction matches your own stacktrace?

I suspect that the particular error occurs because of an arithmetic overflow in JsonDocument's Enlarge method:
https://github.com/dotnet/runtime/blob/3fc61ebb562afc327a8fc6de5c82d76e86bf6f5d/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.MetadataDb.cs#L234

The enlarge method could be improved to better handle boundary conditions, e.g. taking inspiration from List<T>'s internal `Grow` function:
https://github.com/dotnet/runtime/blob/3fc61ebb562afc327a8fc6de5c82d76e86bf6f5d/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L425-L429

Fundamentally though, this is hitting the limits of JsonDocument design, I don't believe the type is capable of handling arbitrarily large JSON data.

**Comment by eiriktsarpalis** [comment]
@Paul-Grimes In the meantime, I would recommend using one of streaming deserialization methods for large JSON data, e.g. `DeserializeAsync` or `DeserializeAsyncEnumerable` for long root-level arrays.

**Comment by MohammadAnsari98** [comment]
@eiriktsarpalis i really like to work on this issue , can you provide me a help about where i need to start , thanks

**Comment by berkansasmaz** [comment]
@eiriktsarpalis Hello! I can work on this. Can you assign it to me?
