### ISSUE TITLE
[Android] JIT/opt/OSR/pinnedlocal/pinnedlocal.sh

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#70820]
The test fails on regular basis - see [runfo results](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22jit%2Fopt%2Fosr%2Fpinnedlocal%2Fpinnedlocal.sh%22):
* 6/16 - 68 failures in last 7 days

Error:
```
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_opt._OSR_pinnedlocal_pinnedlocal_._OSR_pinnedlocal_pinnedlocal_sh()
```

Full console log:
<details>

```
    JIT/opt/OSR/pinnedlocal/pinnedlocal.sh [FAIL]
      
      cmdLine:/datadisks/disk1/work/CD450A54/w/AC8A0973/e/JIT/opt/OSR/pinnedlocal/pinnedlocal.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/13/2022 10:59:16 PM, end: 6/13/2022 11:59:16 PM)
      
      Return code:      -100
      Raw output file:      /datadisks/disk1/work/CD450A54/w/AC8A0973/uploads/Reports/JIT.opt/OSR/pinnedlocal/pinnedlocal.output.txt
      Raw output:
      BEGIN EXECUTION
      [1.0.0-prerelease.22310.1+43e9fe312ac5513edf763877ce9ebf5d57ca9f88] XHarness command issued: android run --instrumentation=net.dot.MonoRunner --package-name=net.dot.JIT_opt --output-directory=/datadisks/disk1/work/CD450A54/w/AC8A0973/uploads/Reports/JIT.opt/OSR/pinnedlocal --arg=entrypoint:libname=pinnedlocal.dll --expected-exit-code=100 -v
      
      cmdLine:/datadisks/disk1/work/CD450A54/w/AC8A0973/e/JIT/opt/OSR/pinnedlocal/pinnedlocal.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/13/2022 10:59:16 PM, end: 6/13/2022 11:59:16 PM)
      Test Harness Exitcode is : -100
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/CD450A54/p
      > /datadisks/disk1/work/CD450A54/w/AC8A0973/e/JIT/opt/OSR/pinnedlocal/pinnedlocal.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_opt._OSR_pinnedlocal_pinnedlocal_._OSR_pinnedlocal_pinnedlocal_sh()
      Output:
        
        cmdLine:/datadisks/disk1/work/CD450A54/w/AC8A0973/e/JIT/opt/OSR/pinnedlocal/pinnedlocal.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/13/2022 10:59:16 PM, end: 6/13/2022 11:59:16 PM)
        
        Return code:      -100
        Raw output file:      /datadisks/disk1/work/CD450A54/w/AC8A0973/uploads/Reports/JIT.opt/OSR/pinnedlocal/pinnedlocal.output.txt
        Raw output:
        BEGIN EXECUTION
        [1.0.0-prerelease.22310.1+43e9fe312ac5513edf763877ce9ebf5d57ca9f88] XHarness command issued: android run --instrumentation=net.dot.MonoRunner --package-name=net.dot.JIT_opt --output-directory=/datadisks/disk1/work/CD450A54/w/AC8A0973/uploads/Reports/JIT.opt/OSR/pinnedlocal --arg=entrypoint:libname=pinnedlocal.dll --expected-exit-code=100 -v
        
        cmdLine:/datadisks/disk1/work/CD450A54/w/AC8A0973/e/JIT/opt/OSR/pinnedlocal/pinnedlocal.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/13/2022 10:59:16 PM, end: 6/13/2022 11:59:16 PM)
        Test Harness Exitcode is : -100
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/CD450A54/p
        > /datadisks/disk1/work/CD450A54/w/AC8A0973/e/JIT/opt/OSR/pinnedlocal/pinnedlocal.sh
```

</details>

**Comment by karelz** [comment]
@SamMonoRT  @fanyang-mono this is failing in ALL rolling test runs this week (and likely earlier) -- can you (or someone on your team) please disable the test ASAP? Thanks!

**Comment by karelz** [comment]
There were similar failures also for non-Android tracked by #70641.

**Comment by SamMonoRT** [comment]
Do we still need to disable given the revert https://github.com/dotnet/runtime/pull/70627 PR was merged, as in are there failures since ?

**Comment by jkotas** [comment]
The reverted PR has nothing to do with the Mono failures. This test has been failing intermittently on Mono for very long time.

**Comment by SamMonoRT** [comment]
Interesting to hear about these failures only now. Will submit a PR to disable the test for now.

**Comment by fanyang-mono** [comment]
I took a look at the logs. This test usually takes around 1h to finish and often got killed due to over time. I will disable it for now.

**Comment by SamMonoRT** [comment]
Merged https://github.com/dotnet/runtime/pull/70843 to disable the test. Removing blocking-ci label and adding disabled-test one for further tracking

**Comment by karelz** [comment]
Thanks @fanyang-mono and @SamMonoRT for fast turnaround. It's appreciated!

**Comment by fanyang-mono** [comment]
Won't be able to get to it for .NET7. Moving to .NET8
