### ISSUE TITLE
Test failure JIT\\Directed\\RVAInit\\nested\\nested.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70876]
Run: [runtime-coreclr ilasm 20220616.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1829618&view=ms.vss-test-web.build-test-results-tab&runId=48444888&paneView=debug&resultId=105013)

Failed test:
```
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
- JIT\\Directed\\RVAInit\\nested\\nested.cmd
- JIT\\Directed\\RVAInit\\simple\\simple.cmd

coreclr Linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Directed/RVAInit/simple/simple.sh
- JIT/Directed/RVAInit/nested/nested.sh

coreclr Linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT/Directed/RVAInit/nested/nested.sh
- JIT/Directed/RVAInit/simple/simple.sh

coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open
- JIT\\Directed\\RVAInit\\simple\\simple.cmd
- JIT\\Directed\\RVAInit\\nested\\nested.cmd

coreclr windows arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open
- JIT\\Directed\\RVAInit\\simple\\simple.cmd
- JIT\\Directed\\RVAInit\\nested\\nested.cmd

coreclr Linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open
- JIT/Directed/RVAInit/simple/simple.sh
- JIT/Directed/RVAInit/nested/nested.sh

coreclr OSX x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open
- JIT/Directed/RVAInit/simple/simple.sh
- JIT/Directed/RVAInit/nested/nested.sh

coreclr OSX arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open
- JIT/Directed/RVAInit/nested/nested.sh
- JIT/Directed/RVAInit/simple/simple.sh
```
**Error message:**
```
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
at Test_nested.VerifyStruct(Test_nested& test)
at Test_nested.Main()

Return code:      1
Raw output file:      C:\h\w\B2CC09F8\w\BB1909F7\uploads\Reports\JIT.Directed\RVAInit\nested\nested.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\B2CC09F8\p\ildasm.exe /raweh /out=nested.dasm.il nested.dll
C:\h\w\B2CC09F8\p\ilasm.exe /output=nested.asm.dll  nested.dasm.il

Microsoft (R) .NET IL Assembler.  Version 7.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'nested.dasm.il'  to EXE --> 'nested.asm.dll'
Source file is UTF-8

Assembled method Test_nested::hex
Assembled method Test_nested::DumpStruct
Assembled method Test_nested::VerifyStruct
Assembled method Test_nested::Main
Creating PE file

Emitting classes:
Class 1:Internal
Class 2:Test_nested

Emitting fields and methods:
Global
Class 1Fields: 11;
Class 2Fields: 7;Methods: 4;
Resolving local member refs: 30 -> 30 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Class 2
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
"C:\h\w\B2CC09F8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  nested.asm.dll
.data D_1 = bytearray( DE 00 00 00 00 00 00 00 DE 6F 39 30 22 C8 00 00
66 45 13 02 66 45 13 02 66 45 13 02 00 00 00 00
66 45 13 02 00 00 00 00 83 00 8C 42 00 00 00 00
E3 A5 9B C4 20 00 54 40 00 00 00 00 00 00 00 00
)
END EXECUTION OF IL{D}ASM BINARY - FAILED -532462766 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B2CC09F8\p
C:\h\w\B2CC09F8\w\BB1909F7\e\JIT\Directed\RVAInit\nested\nested.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._RVAInit_nested_nested_._RVAInit_nested_nested_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
No Kusto information.

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/70875

**Comment by jakobbotsch** [comment]
ildasm seems to be cutting the last 8 bytes off a bytearray. Before:
```cil
.data D_1 = bytearray( DE 00 00 00 00 00 00 00 DE 6F 39 30 22 C8 00 00
66 45 13 02 66 45 13 02 66 45 13 02 00 00 00 00
66 45 13 02 00 00 00 00 83 00 8C 42 00 00 00 00
E3 A5 9B C4 20 00 54 40 6F 00 39 30 22 C8 00 00
 )
```
after
```cil
.data D_00004000 = bytearray (
                 DE 00 00 00 00 00 00 00 DE 6F 39 30 22 C8 00 00  // .........o90"...
                 66 45 13 02 66 45 13 02 66 45 13 02 00 00 00 00  // fE..fE..fE......
                 66 45 13 02 00 00 00 00 83 00 8C 42 00 00 00 00  // fE.........B....
                 E3 A5 9B C4 20 00 54 40)                         // .... .T@

```

**Comment by jakobbotsch** [comment]
ildasm has a `SizeOfField` function that tries to compute the size of a field by going through the fields of the type, used when printing fields using RVAs. This algorithm does not seem to take alignment into account which causes the problem.

**Comment by jakobbotsch** [comment]
It seems a little unreasonable to me to have to do type layout as part of ildasm.. I can probably fix this particular case, but I cannot imagine that the current algorithm handles anything but the simplest cases correctly.

**Comment by jakobbotsch** [comment]
This passes in .NET 6.0, but it seems to me the roundtripping test there is somehow not actually running the assembly produced by ilasm. For example, I see the following:
```scala
❯ C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Release\JIT\Directed\RVAInit\nested\nested.cmd
BEGIN EXECUTION
C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\\ildasm.exe /raweh /out=nested.dasm.il nested.dll
C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\\ilasm.exe /output=nested.asm.dll -QUIET -NOLOGO -DEBUG=OPT -OPTIMIZE nested.dasm.il
 "C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  nested.asm.dll


.data D_1 = bytearray( DE 00 00 00 00 00 00 00 DE 6F 39 30 22 C8 00 00
66 45 13 02 66 45 13 02 66 45 13 02 00 00 00 00
66 45 13 02 00 00 00 00 83 00 8C 42 00 00 00 00
E3 A5 9B C4 20 00 54 40 6F 00 39 30 22 C8 00 00
 )
 "C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  nested.dll
.data D_1 = bytearray( DE 00 00 00 00 00 00 00 DE 6F 39 30 22 C8 00 00
66 45 13 02 66 45 13 02 66 45 13 02 00 00 00 00
66 45 13 02 00 00 00 00 83 00 8C 42 00 00 00 00
E3 A5 9B C4 20 00 54 40 6F 00 39 30 22 C8 00 00
 )
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
```
This indicates that the roundtripped assembly was produced at nested.asm.dll and it ran successfully. However, if I delete the input dll, nested.dll, then it fails like in .NET 7:
```scala
❯ rm C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Release\JIT\Directed\RVAInit\nested\nested.dll
❯ C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\\corerun.exe C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Release\JIT\Directed\RVAInit\nested\nested.asm.dll
.data D_1 = bytearray( DE 00 00 00 00 00 00 00 DE 6F 39 30 22 C8 00 00
66 45 13 02 66 45 13 02 66 45 13 02 00 00 00 00
66 45 13 02 00 00 00 00 83 00 8C 42 00 00 00 00
E3 A5 9B C4 20 00 54 40 00 00 00 00 00 00 00 00
 )
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at Test.VerifyStruct(Test& test) in C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Release\JIT\Directed\RVAInit\nested\nested.dasm.il:line 242
   at Test.Main() in C:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Release\JIT\Directed\RVAInit\nested\nested.dasm.il:line 255
```

So it would seem that somehow executing nested.asm.dll with corerun.exe ends up actually running nested.dll, which is why it hasn't failed before.

**Comment by jakobbotsch** [comment]
The timeline here is:
eb9dd67^ -- passes (by executing the wrong assembly)
eb9dd67 -- fails with "Assembly with same name is already loaded"
5713bea^ -- fails with "Assembly with same name is already loaded"
5713bea -- fails with the reported error

@jkotas is this change in behavior expected? I am not totally sure I understand why executing `nested.asm.dll` was executing `nested.dll` before, and why it is fixed after eb9dd67 / 5713bea. Just to clarify, the new behavior seems much more reasonable to me and clearly the ilasm roundtrip testing was just downright broken before.

**Comment by jkotas** [comment]
> @jkotas is this change in behavior expected? 

This change in behavior should be only observable with corerun. You should not see it with the shipping dotnet host or standard build tooling. These won't ever create situation where assembly names do not match filenames, and where there are multiple assemblies with the same name in the app. I do not think we care about maintaining the exact behavior in this corner case.

**Comment by jakobbotsch** [comment]
Thanks @jkotas. Indeed I confirmed that the behavior is the same when using the dotnet host: it executes nested.dll instead of nested.asm.dll.

> Perhaps we should guard against this possibility by moving/renaming the original .dll before running the test (and restoring it afterwards)?

Yes, seems like we should do something similar to what the R2R testing does.
