### ISSUE TITLE
[wasm] Microsoft.VisualBasic.Core tests for CurrentDirectory fail for Browser on Windows

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#70887]
After enabling tests disabled in https://github.com/dotnet/runtime/issues/55429, testing `Microsoft.VisualBasic.Core` fails with 2 failures. 

Repro - run:
`dotnet build /t:Test src/libraries/Microsoft.VisualBasic.Core/tests /p:TargetOS=Browser /p:Configuration=Debug /p:BrowserHost=Windows /p:Scenario=WasmTestOnBrowser`

Behavior:
`CurrentDirectoryGet` and  `CurrentDirectorySet` failures. Call stack:

```
 info: Starting:    Microsoft.VisualBasic.Core.Tests.dll
  warn: [MONO] Process terminated. Assertion failed.
  warn: [MONO] These exceptions should be caught above
     at System.Diagnostics.DebugProvider.Fail(String message, String detailMessage)
     at System.Diagnostics.Debug.Fail(String message, String detailMessage)
     at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
     at System.Diagnostics.Debug.Assert(Boolean condition, String message)
     at Microsoft.VisualBasic.FileIO.FileSystem.GetLongPath(String FullPath)
     at Microsoft.VisualBasic.FileIO.FileSystem.NormalizePath(String Path)
     at Microsoft.VisualBasic.FileIO.FileSystem.get_CurrentDirectory()
     at Microsoft.VisualBasic.FileIO.Tests.FileSystemTests.CurrentDirectoryGet() in src\libraries\Microsoft.VisualBasic.Core\tests\Microsoft\VisualBasic\FileIO\FileSystemTests.cs:line 293
```
```
  ....same stack as above
     at Microsoft.VisualBasic.FileIO.FileSystem.get_CurrentDirectory()
     at Microsoft.VisualBasic.FileIO.Tests.FileSystemTests.CurrentDirectorySet() in \src\libraries\Microsoft.VisualBasic.Core\tests\Microsoft\VisualBasic\FileIO\FileSystemTests.cs:line 309
```

**Comment by radical** [comment]
@ilonatommy Can you print the exception before this line? https://github.com/dotnet/runtime/blob/a78211bef436e634f8bbdc25de78ecde97764d9e/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/FileIO/FileSystem.vb#L1517

**Comment by radical** [comment]
Also, this should have a different failure on CI, because that builds in Release config.

**Comment by ilonatommy** [comment]
> @ilonatommy Can you print the exception before this line?
> 
> https://github.com/dotnet/runtime/blob/a78211bef436e634f8bbdc25de78ecde97764d9e/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/FileIO/FileSystem.vb#L1517

```
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
     at System.ArgumentNullException.Throw(String paramName) in \src\libraries\System.Private.CoreLib\src\System\ArgumentNullException.cs:line 92
     at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName) in \src\libraries\System.Private.CoreLib\src\System\ArgumentNullException.cs:line 63
     at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName) in \src\libraries\System.Private.CoreLib\src\System\ArgumentException.cs:line 119
     at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName) in \src\libraries\System.Private.CoreLib\src\System\ArgumentException.cs:line 112
     at System.IO.Path.GetFullPath(String path) in \src\libraries\System.Private.CoreLib\src\System\IO\Path.Unix.cs:line 28
     at System.IO.DirectoryInfo..ctor(String path) in \src\libraries\System.Private.CoreLib\src\System\IO\DirectoryInfo.cs:line 18
     at Microsoft.VisualBasic.FileIO.FileSystem.GetLongPath(String FullPath) in \src\libraries\Microsoft.VisualBasic.Core\src\Microsoft\VisualBasic\FileIO\FileSystem.vb:line 1494
```
