### ISSUE TITLE
HTTP/3: Uninformative message when HTTP/3 connection fails

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#70949]
### Description

I'm trying to get HTTP/3 setup on a remote computer. It isn't working and the error message provided isn't useful to help me fix it.

Error message:

> Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.

Stack trace:
```
[04:27:35.530] 0 0: Error message: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /tmp/benchmarks-agent/benchmarks-server-1/bztvffi2.2p2/grpc-dotnet/src/Grpc.Net.Client/Balancer/Internal/BalancerHttpHandler.cs:line 136
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in /tmp/benchmarks-agent/benchmarks-server-1/bztvffi2.2p2/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 643")
   at GrpcClient.Program.UnaryCall(CancellationTokenSource cts, Int32 connectionId, Int32 streamId) in /tmp/benchmarks-agent/benchmarks-server-1/bztvffi2.2p2/grpc-dotnet/perf/benchmarkapps/GrpcClient/Program.cs:line 703
```

### Reproduction Steps

I haven't figured out why this breaks on the remote computer and works locally yet. I'm not sure why the error message is thrown. I'll try setting up an event source next...

### Expected behavior

The error message says **why** the HTTP/3 connection can't be established.

### Actual behavior

"Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection."

🤷‍♂️ 

### Configuration

.NET 7 daily build.

**Comment by JamesNK** [comment]
Complete logs below. The first request provides more information about the error. Additional error messages aren't helpful.

```
[07:14:08.682] gRPC Client
[07:14:08.770] Binding GrpcClient.ClientOptions
[07:14:08.772] -Url = http://10.0.0.102:5000/
[07:14:08.773] -UdsFileName = 
[07:14:08.773] -Connections = 1
[07:14:08.773] -Warmup = 0
[07:14:08.773] -Duration = 1
[07:14:08.773] -CallCount = 2
[07:14:08.773] -Scenario = unary
[07:14:08.773] -Latency = False
[07:14:08.774] -Protocol = h3
[07:14:08.774] -LogLevel = Debug
[07:14:08.774] -RequestSize = 0
[07:14:08.774] -ResponseSize = 0
[07:14:08.774] -GrpcClientType = GrpcNetClient
[07:14:08.774] -Streams = 1
[07:14:08.774] -EnableCertAuth = False
[07:14:08.775] -Deadline = 0
[07:14:08.777] NetCoreAppVersion: 7.0.0-preview.6.22318.3+e771b5dd9b51b679fd8e79ee3aaabfbebbddca68
[07:14:08.777] IsServerGC: True
[07:14:08.777] ProcessorCount: 28
[07:14:08.784] Setting up logging. Log level: Debug
[07:14:08.838] gRPC client type: GrpcNetClient
[07:14:08.838] Log level: Debug
[07:14:08.838] Protocol: 'h3'
[07:14:08.838] Creating channels to '10.0.0.102:5000'
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      Starting HttpEventSourceListener.
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : SocketsHttpHandler#24827179,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : Http3DelegatingHandler#22118023,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Associate : Http3DelegatingHandler#22118023,InnerHandler,Http3DelegatingHandler#22118023,SocketsHttpHandler#24827179 ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : BalancerHttpHandler#31201899,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Associate : BalancerHttpHandler#31201899,InnerHandler,BalancerHttpHandler#31201899,Http3DelegatingHandler#22118023 ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpMessageInvoker#12381635,.ctor,HttpMessageInvoker#12381635,BalancerHttpHandler#31201899 ->
[07:14:08.862] Call count: 2
[07:14:08.862] Starting unary
[07:14:08.883] 0 0: Starting unary
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : PushUnaryContent`2#15688314,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpRequestMessage#52307948,Content,HttpRequestMessage#52307948,PushUnaryContent`2#15688314 ->
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://10.0.0.102:5000/grpc.testing.BenchmarkService/UnaryCall'.
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event System.Net.Http - RequestStart : https,10.0.0.102,5000,/grpc.testing.BenchmarkService/UnaryCall,2,0,1 ->
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[1]
      Subchannel id '1' created with addresses: 10.0.0.102:5000
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Connecting. Detail: 'Connection requested.'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[3]
      Channel state updated to Connecting.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[8]
      Picked queued.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport[2]
      Subchannel id '1' connected to socket 10.0.0.102:5000.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Subchannel[11]
      Subchannel id '1' state changed to Ready. Detail: 'Successfully connected to socket.'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[3]
      Channel state updated to Ready.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[4]
      Channel picker updated.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[6]
      Successfully picked subchannel id '1' with address 10.0.0.102:5000.
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : HttpConnectionHandler#41149443,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : DiagnosticsHandler#39785641,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : SafeMsQuicRegistrationHandle#45523402,.ctor,MsQuicSafeHandle created ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 35287174,0,0,.ctor,HttpConnectionPool https://10.0.0.102:5000 ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 35287174,0,0,GetHttp3ConnectionAsync,Attempting new HTTP3 connection. ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : SafeMsQuicConfigurationHandle#44419000,.ctor,MsQuicSafeHandle created ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : SafeMsQuicConnectionHandle#52697953,.ctor,MsQuicSafeHandle created ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22597652,.ctor,[conn][0x7F8F04070F90] Outbound connection created ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : SafeMsQuicConfigurationHandle#44419000,ReleaseHandle,MsQuicSafeHandle released ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22597652,NativeCallback,[conn][0x7F8F04070F90] Connection received event SHUTDOWN_INITIATED_BY_TRANSPORT ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22597652,NativeCallback,[conn][0x7F8F04070F90] Connection received event SHUTDOWN_COMPLETE ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22597652,Dispose,[conn][0x7F8F04070F90] Connection disposing True ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#22597652,Dispose,[conn][0x7F8F04070F90] Connection releasing handle ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : SafeMsQuicConnectionHandle#52697953,ReleaseHandle,MsQuicSafeHandle released ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 35287174,0,0,GetHttp3ConnectionAsync,QUIC connection failed: System.Net.Http.HttpRequestException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE (10.0.0.102:5000)
       ---> Microsoft.Quic.MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE
         at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
         at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
      --- End of stack trace from previous location ---
         at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken) ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event System.Net.Http - RequestFailed :  ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event System.Net.Http - RequestStop :  ->
[41m[30mfail[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE (10.0.0.102:5000)
 ---> Microsoft.Quic.MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Balancer/Internal/BalancerHttpHandler.cs:line 114
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 481
[40m[32minfo[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call. HttpRequestException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE (10.0.0.102:5000) MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
[07:14:09.020] 0 0: Error message: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE (10.0.0.102:5000) MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE", DebugException="System.Net.Http.HttpRequestException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE (10.0.0.102:5000)
 ---> Microsoft.Quic.MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_ALPN_NEG_FAILURE
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Balancer/Internal/BalancerHttpHandler.cs:line 114
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 481")
   at GrpcClient.Program.UnaryCall(CancellationTokenSource cts, Int32 connectionId, Int32 streamId) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/perf/benchmarkapps/GrpcClient/Program.cs:line 694
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Info : PushUnaryContent`2#40644060,.ctor, ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpRequestMessage#17043416,Content,HttpRequestMessage#17043416,PushUnaryContent`2#40644060 ->
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[1]
      Starting gRPC call. Method type: 'Unary', URI: 'https://10.0.0.102:5000/grpc.testing.BenchmarkService/UnaryCall'.
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event System.Net.Http - RequestStart : https,10.0.0.102,5000,/grpc.testing.BenchmarkService/UnaryCall,2,0,1 ->
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Balancer.Internal.ConnectionManager[6]
      Successfully picked subchannel id '1' with address 10.0.0.102:5000.
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event System.Net.Http - RequestFailed :  ->
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      <- Event System.Net.Http - RequestStop :  ->
[41m[30mfail[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[6]
      Error starting gRPC call.
System.Net.Http.HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Balancer/Internal/BalancerHttpHandler.cs:line 114
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 481
[40m[32minfo[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[3]
      Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call. HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.'.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[4]
      Finished gRPC call.
[40m[37mdbug[39m[22m[49m: Grpc.Net.Client.Internal.GrpcCall[8]
      gRPC call canceled.
[07:14:09.024] 0 0: Error message: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Balancer/Internal/BalancerHttpHandler.cs:line 114
   at System.Net.Http.HttpMessageInvoker.<SendAsync>g__SendAsyncWithTelemetry|6_0(HttpMessageHandler handler, HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 481")
   at GrpcClient.Program.UnaryCall(CancellationTokenSource cts, Int32 connectionId, Int32 streamId) in /tmp/benchmarks-agent/benchmarks-server-1/f52va30i.cyd/grpc-dotnet/perf/benchmarkapps/GrpcClient/Program.cs:line 694
[07:14:09.025] Reached 2
[07:14:09.025] 0 0: Finished unary
[07:14:09.026] Stopping client.
[07:14:09.027] Least Requests per Connection: 2
[07:14:09.027] Most Requests per Connection: 2
[07:14:09.032] RPS: Infinity
[07:14:09.032] Total requests: 2
[07:14:09.032] Total errors: 2
[07:14:09.034] Mean latency: 68.256ms
[07:14:09.034] Max latency: 133.189ms
[40m[37mdbug[39m[22m[49m: HttpEventSourceListener[0]
      Stopping HttpEventSourceListener.
```

**Comment by ManickaP** [comment]
We should improve the message and include information from the underlying exception if we attempt but fail to establish an H/3 connection. We shouldn't be using all encompassing message which we use for unavailable H/3 support (missing msquic, disabled h/3, low version of windows, ...)
