### ISSUE TITLE
Test failure JIT/Methodical/Arrays/lcs/lcsvalbox_ro/lcsvalbox_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70967]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220619.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1833184&view=ms.vss-test-web.build-test-results-tab&runId=48491690&paneView=debug&resultId=110901)

Failed test:
```
coreclr OSX arm64 Checked gcstress0xc @ OSX.1200.ARM64.Open

- JIT/Methodical/Arrays/lcs/lcsvalbox_ro/lcsvalbox_ro.cmd

```
**Error message:**
```
cmdLine:/private/tmp/helix/working/B65409A4/w/A73F09B7/e/JIT/Methodical/Methodical_ro/../Arrays/lcs/lcsvalbox_ro/lcsvalbox_ro.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/19/2022 8:19:44 AM, end: 6/19/2022 9:19:45 AM)

Return code:      -100
Raw output file:      /tmp/helix/working/B65409A4/w/A73F09B7/uploads/Arrays/lcs/lcsvalbox_ro/output.txt
Raw output:
SKIPPING EXECUTION BECAUSE COMPlus_GCStress IS SET

cmdLine:/private/tmp/helix/working/B65409A4/w/A73F09B7/e/JIT/Methodical/Methodical_ro/../Arrays/lcs/lcsvalbox_ro/lcsvalbox_ro.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 6/19/2022 8:19:44 AM, end: 6/19/2022 9:19:45 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.

/private/tmp/helix/working/B65409A4/w/A73F09B7/e/JIT/Methodical/Methodical_ro/../Arrays/lcs/lcsvalbox_ro/lcsvalbox_ro.sh
Expected: True
Actual:   False


Stack trace
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String basePath, String assemblyPath)
   at Program.<Main>$(String[] args)
```

**Comment by jakobbotsch** [comment]
This has the same symptoms as #69092. Will close as a duplicate of that one.
