### ISSUE TITLE
Test failure tracing\\runtimeeventsource\\nativeruntimeeventsource\\nativeruntimeeventsource.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70966]
Run: [runtime-coreclr jitstress-isas-x86 20220618.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1832542&view=ms.vss-test-web.build-test-results-tab&runId=48487108&resultId=107041&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress_isas_1_x86_nosse2 @ Windows.10.Amd64.Open

- tracing\\runtimeeventsource\\nativeruntimeeventsource\\nativeruntimeeventsource.cmd

```
**Error message:**
```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A9D3098C\w\C6B10ADC\uploads\Reports\tracing.runtimeeventsource\nativeruntimeeventsource\nativeruntimeeventsource.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A9D3098C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  nativeruntimeeventsource.dll
DOOVERLAPPEDIO
[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:49 AM
Difference: 00:00:01.6342478
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "30.555555555555557"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9051356
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "22.916666666666668"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9054275
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "20.408163265306122"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9056008
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "22"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9057753
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "20"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9059585
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "21.568627450980394"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9061277
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "21.568627450980394"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9063118
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "21.568627450980394"
Name = "EstablishedNsPerYield" Value = "20"

[Simple] ThreadID = 8932 ID = 200 Name = IncreaseMemoryPressure
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9063122
Name = "BytesAllocated" Value = "2176"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 8932 ID = 70 Name = ThreadCreating
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9154906
Name = "ID" Value = "139857664"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 6740 ID = 85 Name = ThreadCreated
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9382517
Name = "ManagedThreadID" Value = "139857664"
Name = "AppDomainID" Value = "49677472"
Name = "Flags" Value = "0"
Name = "ManagedThreadIndex" Value = "4"
Name = "OSThreadID" Value = "6740"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 6740 ID = 71 Name = ThreadRunning
TimeStamp: 6/19/2022 3:15:48 AM
LocalTime: 6/19/2022 3:15:50 AM
Difference: 00:00:01.9392748
Name = "ID" Value = "139857664"
Name


Stack trace
   at tracing_runtimeeventsource._nativeruntimeeventsource_nativeruntimeeventsource_._nativeruntimeeventsource_nativeruntimeeventsource_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
No Kusto information.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr jitstress 20220704.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1860511&view=ms.vss-test-web.build-test-results-tab&runId=48883650&resultId=107063&paneView=debug)

Failed test:
```
coreclr windows x64 Checked zapdisable @ Windows.10.Amd64.Open

- tracing\\runtimeeventsource\\nativeruntimeeventsource\\nativeruntimeeventsource.cmd
```
**Error message:**
```
Unhandled exception. System.Exception: Condition 'Saw the ThreadPoolIOPack event' is not true
at Tracing.Tests.Common.Assert.True(String name, Boolean condition)
at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B9660A3A\w\B60F09FC\uploads\Reports\tracing.runtimeeventsource\nativeruntimeeventsource\nativeruntimeeventsource.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B9660A3A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  nativeruntimeeventsource.dll
[Simple] ThreadID = 1720 ID = 200 Name = IncreaseMemoryPressure
DOOVERLAPPEDIO
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.0638097
Name = "BytesAllocated" Value = "3800"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 1720 ID = 70 Name = ThreadCreating
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1184677
Name = "ID" Value = "2218165940576"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 7592 ID = 85 Name = ThreadCreated
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1199692
Name = "ManagedThreadID" Value = "2218165940576"
Name = "AppDomainID" Value = "1940755638464"
Name = "Flags" Value = "0"
Name = "ManagedThreadIndex" Value = "4"
Name = "OSThreadID" Value = "7592"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 7592 ID = 71 Name = ThreadRunning
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1308154
Name = "ID" Value = "2218165940576"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 1720 ID = 145 Name = MethodJittingStarted_V1
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1308838
Name = "MethodID" Value = "140735294199488"
Name = "ModuleID" Value = "140735287803904"
Name = "MethodToken" Value = "100677636"
Name = "MethodILSize" Value = "25"
Name = "MethodNamespace" Value = "System.Threading.Tasks.Task"
Name = "MethodName" Value = "Run"
Name = "MethodSignature" Value = "class System.Threading.Tasks.Task  (class System.Action)"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 7592 ID = 145 Name = MethodJittingStarted_V1
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1313076
Name = "MethodID" Value = "140735294465232"
Name = "ModuleID" Value = "140735287803904"
Name = "MethodToken" Value = "100691807"
Name = "MethodILSize" Value = "133"
Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipeEventDispatcher"
Name = "MethodName" Value = "TimeStampToDateTime"
Name = "MethodSignature" Value = "instance value class System.DateTime  (int64)"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 1720 ID = 146 Name = MethodJitMemoryAllocatedForCode
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1306428
Name = "MethodID" Value = "140735294199488"
Name = "ModuleID" Value = "140735287803904"
Name = "JitHotCodeRequestSize" Value = "116"
Name = "JitRODataRequestSize" Value = "0"
Name = "AllocatedSizeForJitCode" Value = "136"
Name = "JitAllocFlag" Value = "0"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 1720 ID = 143 Name = MethodLoadVerbose_V2
TimeStamp: 7/5/2022 7:08:22 AM
LocalTime: 7/5/2022 7:08:24 AM
Difference: 00:00:01.1307645
Name = "MethodID" Value = "140735294199488"
Name = "ModuleID" Value = "140735287803904"
Name = "MethodStartAddress" Value = "140735291030048"
Name = "MethodSize" Value = "116"
Name = "MethodToken" Value = "100677636"
Name = "MethodFlags" Value = "264"
Name = "MethodNamespace" Value = "System.Threading.Tasks.Task"
Name = "MethodName" Value = "Run"
Name = "MethodSignature" Value = "class System.Threading.Tasks.Task  (class System.Action)"
Name = "ClrInstanceID" Value = "0"
Name = "ReJITID" Value = ""

[Simple] ThreadID = 1720 ID = 1


Stack trace
   at tracing_runtimeeventsource._nativeruntimeeventsource_nativeruntimeeventsource_._nativeruntimeeventsource_nativeruntimeeventsource_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
