### ISSUE TITLE
Test failure System.PrivateUri.Tests.UriRelativeResolutionTest.Uri_Unicode_SurrogatePairs_Scheme

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70972]
Run: [runtime-coreclr libraries-jitstressregs 20220619.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1833056&view=ms.vss-test-web.build-test-results-tab&runId=48490146&resultId=140607&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.PrivateUri.Tests.UriRelativeResolutionTest.Uri_Unicode_SurrogatePairs_Scheme

```
**Error message:**
```
Assert.Equal() Failure
↓ (pos 8)
Expected: scheme:%\0\0%B9%B3%8F
Actual:   scheme:%25\0\0%B9%B3%8F
↑ (pos 8)


Stack trace
   at System.PrivateUri.Tests.UriRelativeResolutionTest.Uri_Unicode_SurrogatePairs_Scheme() in /_/src/libraries/System.Private.Uri/tests/FunctionalTests/UriRelativeResolutionTest.cs:line 241
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by JulieLeeMSFT** [comment]
@BruceForstall this fails in libraries code. Please take a look and route to a right owner.

**Comment by BruceForstall** [comment]
@danmoseley This didn't fail when the pipeline was rerun. Can you assign it to the appropriate team to investigate as a potential flaky test, or should we close it as "no repro"?

**Comment by dakersnar** [comment]
No repro since, assuming this was a one-off
