### ISSUE TITLE
Test failure net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70971]
Run: [runtime-libraries-coreclr outerloop 20220619.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1833104&view=ms.vss-test-web.build-test-results-tab&runId=48491140&resultId=104547&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success(uri: \"https://quic.aiortc.org:443/\")

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success(uri: \"https://quic.aiortc.org:443/\")

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success(uri: \"https://quic.aiortc.org:443/\")

net7.0-windows-Release-x86-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success(uri: \"https://quic.aiortc.org:443/\")

net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success(uri: \"https://quic.aiortc.org:443/\")

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_Upgrade_Success(uri: \"https://quic.aiortc.org:443/\")

```
**Error message:**
```
System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. (quic.aiortc.org:443)
---- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.


Stack trace
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1486
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1425
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 708
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs:line 23
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 823
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1102
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 85
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 558
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_Upgrade_Success(String uri) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 642
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1365
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 126
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1486
```

**Comment by ManickaP** [comment]
`quic.aiortc.org:443` is H/3 interop test. This shouldn't even attempt H/2, I'll look into it.

**Comment by wfurt** [comment]
downgrade?

**Comment by ManickaP** [comment]
I don't know, I have to look.

**Comment by ManickaP** [comment]
It was upgrade, PR is up.
