### ISSUE TITLE
Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents takes down process on an IO exception

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#71003]
Note, this is in a[ 6.0 run.](https://github.com/dotnet/runtime/pull/70763) But I see no issue that was already fixed.
```
Console log: 'Microsoft.Extensions.FileProviders.Physical.Tests' from job 6da37b81-3523-4f12-a96c-801644c3d58d workitem 9e894db9-c746-4e6b-8afb-11e12f053fb9 (windows.81.amd64.open.svc) executed on machine a0000OH
...

Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\h\w\A36408E4\t\dpomsqxx.ukm\bskgbwzu.5ha' is denied.
   at System.IO.FileSystem.GetFinalLinkTarget(String linkPath, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 585
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs:line 422
   at System.IO.FileSystemInfo.ResolveLinkTarget(Boolean returnFinalTarget) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystemInfo.cs:line 170
   at Microsoft.Extensions.FileProviders.Physical.FileSystemInfoHelper.GetFileLinkTargetLastWriteTimeUtc(FileInfo fileInfo) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/Internal/FileSystemInfoHelper.cs:line 56
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 57
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 101
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 476
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 673
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 326
```
I found https://github.com/dotnet/runtime/issues/57266, but this is not creating a symbolic link.

Looking at the dump briefly, I see no test running. Is it possible a test completed without unregistering for events -- so if this had not hit access denied, it would have gone nowhere?

**Comment by danmoseley** [comment]
Actually why an event fired is less interesting than why it knocked the process over. It is fragile for this code to read the disk, especially at an arbitrary path, on a threadpool thread, without catching typical IO exceptions. This problem existed before it was updated to follow file links, even File.GetLastWriteTimeUtc can throw UnauthorizedAccessException.

Probably this code here should catch IO exceptions and do something sensible, most likely, return "now" so that it looks like the file changed, to be sure.

https://github.com/dotnet/runtime/blob/ddb3c79f979b3890fbbba2b764d013c515eb4173/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingWildCardChangeToken.cs#L149

**Comment by danmoseley** [comment]
As it's terminal and flaky product I'd suggest a 7.0 fix.

**Comment by danmoseley** [comment]
sounds reasonable. do you plan to do that?

(although, one could argue perhaps it should do the same for all possible IO exceptions, or just Exception, since any will bring down the process)

**Comment by danmoseley** [comment]
I think it would be reasonable to catch all exceptions that might result from IO, as given the context almost any IO error might occur, and the user may have nothing they can do about them (they aren't on the stack).

In other contexts either they use is in the stack and can deal with it, or we package the exception up and send back to the original caller (e.g. in TaskResult). But it seems neither apply here
