### ISSUE TITLE
ManagedWebSocket throws annoying error when connection is aborted in ReceiveAsync.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#71012]
### Description

Currently I use Remora.Discord, which uses Polly and sockets to manage sockets to Discord, however when the socket goes into Aborted and then it tries to call ``ReceiveAsync`` it results in an annoying throw which then gets logged.

I think what could be done is to instead check for if the state is aborted then return instantly (instead of throwing).

However with this being breaking it would have to be done to .NET 7, as it might be high risk to change it for .NET 6.

### Reproduction Steps

I think a minimal reproducible example is to create a new console project, install Remora.Discord's latest package, it up as a discord bot (does not have to have commands, just connect) then wait until the exception gets logged to console (set up logging to console ofc).

### Expected behavior

For the function ReceiveAsync to instantly but silently return.

### Actual behavior

Here is the entry in the log where the exception gets logged to:

```
2022-06-20 07:11:35.435 -04:00 [WRN] Transient error in gateway client: The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseSent'
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseSent'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Remora.Discord.Gateway.Transport.WebSocketPayloadTransportService.ReceivePayloadAsync(CancellationToken ct)
   at Remora.Discord.Gateway.Transport.WebSocketPayloadTransportService.ReceivePayloadAsync(CancellationToken ct)
   at Remora.Discord.Gateway.DiscordGatewayClient.GatewayReceiverAsync(CancellationToken disconnectRequested)
```

### Regression?

I am not sure.

### Known Workarounds

None yet.

### Configuration

- .NET Version: .NET 6.0.6
- OS: Windows 11
- Architecture: x64
- specific to configuration?: Not sure.
- I do not use Blazor, however my specific discord bot does use the generic host from the AspNetCore framework to avoid the nuget package version of it.

### Other information

I think the problem lies in some or all of the ``ReceiveAsync`` overloads in ManagedWebSocket as Remora.Discord, and Polly cant be made to try to avoid the issue directly.

**Comment by karelz** [comment]
Triage: We do not believe that it is ok to succeed (aka immediately return), when the WebSocket is in Aborted state. The right thing to do is to signal to the upstack something is wrong -- via exception.
Success instead would lead to ignoring errors.

It is not clear to us why there are problems in Polly or Remora.Discord. Perhaps we need someone to look at their code and check if they are doing the right thing.

Given that we do not believe there is problem in .NET, closing. Let us know if you believe we missed some angle. Thanks!
