### ISSUE TITLE
JsonPatchDocument does not work properly with JsonNode objects

### ISSUE THREAD

**Issue by madmox** [dotnet/runtime#71074]
I am trying to apply a JSON patch to a JSON raw JSON string, so I thought I could use the JsonNode API as an intermediary to do the trick, as it is writable.

This is working as expected:
```csharp
string input = @"{ ""foo"": 1 }";
JsonNode obj = JsonSerializer.Deserialize<JsonNode>(input);
var patch = new JsonPatchDocument();
patch.Replace("/foo", 2);
patch.ApplyTo(obj);
string output = JsonSerializer.Serialize(obj);
Console.WriteLine(output); // { "foo": 2 }
```
But this does not work:
```csharp
string input = @"{ ""foo"": [ 1 ] }";
JsonNode obj = JsonSerializer.Deserialize<JsonNode>(input);
var patch = new JsonPatchDocument();
patch.Add("/foo/-", 2);
string output = JsonSerializer.Serialize(obj);
Console.WriteLine(output); // throws JsonPatchException
```
The exception thrown is:
> Microsoft.AspNetCore.JsonPatch.Exceptions.JsonPatchException: The target location specified by path segment '-' was not found.
   at Microsoft.AspNetCore.JsonPatch.Internal.ErrorReporter.<>c.<.cctor>b__1_0(JsonPatchError error)
   at Microsoft.AspNetCore.JsonPatch.Adapters.ObjectAdapter.Replace(Operation operation, Object objectToApplyTo)
   at Microsoft.AspNetCore.JsonPatch.Operations.Operation.Apply(Object objectToApplyTo, IObjectAdapter adapter)
   at Microsoft.AspNetCore.JsonPatch.JsonPatchDocument.ApplyTo(Object objectToApplyTo, IObjectAdapter adapter)
   at Microsoft.AspNetCore.JsonPatch.JsonPatchDocument.ApplyTo(Object objectToApplyTo)

I also tried using `ExpandoObject` and `dynamic` (just replace `JsonNode obj = JsonSerializer.Deserialize<JsonNode>(json);` with `dynamic obj = JsonSerializer.Deserialize<ExpandoObject>(json);`), but it fails with the exact same error.

**Comment by madmox** [comment]
This looks really neat, thanks. I could make my sample work with a very minor change (+ including your lib of course):
```csharp
string input = @"{ ""foo"": [ 1 ] }";
JsonNode obj = JsonSerializer.Deserialize<JsonNode>(input);
var patch = new JsonPatch(PatchOperation.Add(JsonPointer.Parse("/foo/-"), 2));
PatchResult patchResult = patch.Apply(obj);
string output = JsonSerializer.Serialize(patchResult.Result);
Console.WriteLine(output); // { "foo": [ 1, 2 ] }
```

I would like to see such functionality built into the framework.
