### ISSUE TITLE
[wasm] SocketsHttpHandler_HttpClientHandlerTest.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly fails with "Unexpected EOF trying to read request header"

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#71096]
```
[18:43:56] fail: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "\n ", dribble: True)
[18:43:56] info: System.AggregateException : One or more errors occurred. (TypeError: Failed to fetch) (Unexpected EOF trying to read request header)
[18:43:56] info: ---- System.Net.Http.HttpRequestException : TypeError: Failed to fetch
[18:43:56] info: -------- System.Runtime.InteropServices.JavaScript.JSException : TypeError: Failed to fetch
[18:43:56] info: ---- System.IO.IOException : Unexpected EOF trying to read request header
[18:43:56] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass15_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[18:43:56] info: --- End of stack trace from previous location ---
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[18:43:56] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(String newline, String fold, Boolean dribble)
[18:43:56] info: --- End of stack trace from previous location ---
[18:43:56] info: ----- Inner Stack Trace #1 (System.Net.Http.HttpRequestException) -----
[18:43:56] info:    at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|56_0(HttpRequestMessage request, CancellationToken cancellationToken)
[18:43:56] info:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[18:43:56] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass21_0.<<GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly>b__0>d.MoveNext()
[18:43:56] info: --- End of stack trace from previous location ---
[18:43:56] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[18:43:56] info: ----- Inner Stack Trace -----
[18:43:56] info:    at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|56_0(HttpRequestMessage request, CancellationToken cancellationToken)
[18:43:56] info: ----- Inner Stack Trace #2 (System.IO.IOException) -----
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync()
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendCustomResponseAsync(String response)
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass19_0.<<AcceptConnectionSendCustomResponseAndCloseAsync>b__0>d.MoveNext()
[18:43:56] info: --- End of stack trace from previous location ---
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
[18:43:56] info:    at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendCustomResponseAndCloseAsync(String response)
[18:43:56] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1836984&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70851-merge-cbfd4efc983a4e718f/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.efa7fecb.log?helixlogtype=result

**Comment by radical** [comment]
cc @pavelsavara @maraf

**Comment by karelz** [comment]
Failures 2022/3/27-7/21 (incl. PRs): **3457** failures, all in PRs

First failure on 6/17

```kusto
let failedTests = (methodName : string, includePR : bool, messageSubstr: string, includePassedOnRerun : bool) {
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName startswith "System.Net" 
    | where includePassedOnRerun or (Outcome == 'Failed')
    | extend startOfTestName = indexof_regex(TestName, @"[^.]+$")
    | extend Method = substring(TestName, startOfTestName)
    | extend Type = substring(TestName, 0, startOfTestName - 1)
    | project-away startOfTestName
    | where Method == methodName
    | where Message contains messageSubstr
    | distinct JobId, WorkItemId, Message, StackTrace, Method, Type, Arguments, Outcome
    | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
        | where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")))
        | where Type startswith "test/functional/cli/"
            and not(Properties contains "runtime-staging")
        | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
        | project-rename JobType = Type) on JobId
    | extend PropertiesJson = parse_json(Properties)
    | extend OS = replace_regex(tostring(PropertiesJson.operatingSystem), @'\((.*)\).*|([^\(].*)', @'\1\2')
    | extend Runtime = iif(PropertiesJson.runtimeFlavor == "mono", "Mono", iif(PropertiesJson.DefinitionName contains "coreclr", "CoreCLR", ""))
    | extend TargetBranch = extractjson("$.['System.PullRequest.TargetBranch']", Properties)
    | extend Architecture = PropertiesJson.architecture
    | extend Scenario = iif(isempty(PropertiesJson.scenario), "--", PropertiesJson.scenario)
    //| extend DefinitionName = PropertiesJson.DefinitionName
    | project-away PropertiesJson
};
failedTests('GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly', true, '', true);
```

**Comment by maraf** [comment]
All of the recent failures are from multithreaded runtime jobs which are marked as `shouldContinueOnError: true`

**Comment by karelz** [comment]
@maraf I am not sure what are implications of that. The failures are creating noise in official runs and on PRs. They create additional burden on devs and Test monitoring.
What is the plan to mitigate the impact?

**Comment by maraf** [comment]
Current issue is not blocking clean ci as it comes from `shouldContinueOnError: true` job.

**Comment by pavelsavara** [comment]
cc @steveisok

**Comment by steveisok** [comment]
If it's too difficult to differentiate, we can always turn it off, disable the suites that fail, or move to a separate pipeline.

@simonrozsival is actively trying to resolve the failures.

**Comment by maraf** [comment]
We discussed it offline and I think it's clear. I want to check if this error occured recently, but at least @radical said he didn't see it on rolling builds.

**Comment by lewing** [comment]
Is this resolved or are we still generating noise?

**Comment by maraf** [comment]
This one is not happening anymore.
