### ISSUE TITLE
Upgrade to .Net 6 from .Net 5 breaks authentication to oData-Webservice

### ISSUE THREAD

**Issue by Mapel** [dotnet/runtime#71138]
### Description

We are using and maintaining a web application written in asp.Net 5 running on IIS 10 (inprocess). The app is accessing a oData v4 webservice which is provided by our ERP system (Dynamics NAV 2017). We have a hybrid environment with synced AD/AAD, which is used for the user login. In the app we are using the OIDC-auth-provider and AAD. The windows client of Dynamics NAV 2017 is using Windows for the login.

Inside the app we are using Simple.OData.Client to access the service.

### Reproduction Steps

```
using Simple.OData.Client;
using System.Net;

// Version 1
NetworkCredential NAVCred = CredentialCache.DefaultNetworkCredentials;

// Version 2
NAVCred = new("username","password","domain");

// Version 3
NAVCred = new("username","password");

public ODataClient _client = new ODataClient(new ODataClientSettings(new Uri("Odata_URL"))
{
    Credentials = NAVCred,
});

var products = await _client
    .For("Products")
    .FindEntriesAsync();
```

### Expected behavior

All three version of NAVCred should work.

### Actual behavior

In .Net 5 all versions of NAVCred do work, but with .Net 6 only version 3 is working.

With version 1 and 2 the web service is returning an error "Der Zielprinzipalname ist falsch." (wrong target principal name).

Full error log

```
System.ComponentModel.Win32Exception (0x80090322): Der Zielprinzipalname ist falsch.
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Simple.OData.Client.RequestRunner.ExecuteRequestAsync(ODataRequest request, CancellationToken cancellationToken)
   at Simple.OData.Client.Session.SendMetadataRequestAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.ResolveMetadataAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.<>c__DisplayClass27_0.<<InitializeMetadataCache>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Simple.OData.Client.EdmMetadataCache.GetOrAddAsync(String key, Func`2 valueFactory)
   at Simple.OData.Client.Session.InitializeMetadataCache(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.Initialize(CancellationToken cancellationToken)
   at Simple.OData.Client.Session.ResolveAdapterAsync(CancellationToken cancellationToken)
   at Simple.OData.Client.BoundClient`1.FindEntriesAsync(ODataFeedAnnotations annotations, CancellationToken cancellationToken)
```

### Regression?

This issue look a little bit like my problem, but has another error message: [https://github.com/dotnet/runtime/issues/62136](url)

### Known Workarounds

We had to stay with .Net 5, because I found no workaround.

**Comment by wfurt** [comment]
Is the service running on n on-standard port? Could be https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/httpclient-port-lookup

**Comment by Mapel** [comment]
Yeah, that was it. Setting the environment variable worked.

Thanks.
