### ISSUE TITLE
Azure Virtual Machine serial console - Process terminated error

### ISSUE THREAD

**Issue by jaywithers** [dotnet/runtime#71224]
### Description

Hi,

I've been advised to open and issue in this repo, after first raising an issue in the PowerShell repo:
https://github.com/PowerShell/PowerShell/issues/17488.

### Reproduction Steps

When using an Azure Virtual Machine's Serial Console and pressing any key within a PS prompt, the error in the Error Details box below is given and I'm taken back to a Bash prompt.
I reported the issue to Azure support and they advised me to report it here instead.
The behaviour is the same on all of our VMs, but only when using the Serial Console.

### Expected behavior

Able to press a key when in a PS prompt without an error.

### Actual behavior

Error below given and taken back to a Bash prompt.

### Other information

Error details:

Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)Aborted (core dumped)

**Comment by Jozkee** [comment]
@jaywithers I wasn't able to repro. I followed these [instructions](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-overview) to access my serial console. My pwsh version is 7.2.5.

running `pwsh` on the serial console I ran `top` and `ls` and didn't get any error. Can you share more details of what are your repro steps or share your pwsh version?

**Comment by jaywithers** [comment]
Hi @Jozkee, we are running pwsh 7.2.4, but i have just upgraded to 7.2.5 and have the same issue.

The repro steps are as follows:

1. Click on Serial Console from the VM in the Azure Portal
2. Login to the VM
3. Type: pwsh
4. A pwsh prompt is presented
5. Then, after pressing any keyboard key, the following error is given and i am taken back to a bash prompt:

Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)Aborted (core dumped)

**Comment by Jozkee** [comment]
What distro are you using?

**Comment by jaywithers** [comment]
Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.9:GA:server
Kernel: Linux 3.10.0-1160.62.1.el7.x86_64
Architecture: x86-64

**Comment by jaywithers** [comment]
Hi, is there any update for this please?

**Comment by adamsitnik** [comment]
> What OS are you using? Forgot to mention I used Ubuntu.

> Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)

@tmds would you be interested in taking a look?

**Comment by tmds** [comment]
> @tmds would you be interested in taking a look?

Sure.

@jaywithers, can you:
- install `strace`
- run `strace -v -f -e read,write,ioctl pwsh`
- press a key to trigger the problem

That should trigger the issue and cause pwsh to terminate.

Can you share the resulting trace?

**Comment by adamsitnik** [comment]
@tmds have you ever considered blogging about the usage of `strace` for .NET devs?

**Comment by tmds** [comment]
> have you ever considered blogging about the usage of strace for .NET devs?

To do something with the `strace` output you need to have a rough idea of how .NET APIs relate to system calls/libc functions. I think that limits the target audience significantly.
