### ISSUE TITLE
Test failure JIT\\SIMD\\BitwiseOperations_ro\\BitwiseOperations_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71314]
Run: [runtime-coreclr r2r 20220625.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1845912&view=ms.vss-test-web.build-test-results-tab&runId=48684132&resultId=102047&paneView=debug)

Failed test:
```
R2R windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\SIMD\\BitwiseOperations_ro\\BitwiseOperations_ro.cmd

```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](https://dev.azure.com/dnceng/public/_build/results?buildId=1845912&view=ms.vss-test-web.build-test-results-tab&runId=48684132&resultId=102047&paneView=debug)
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__273_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      C:\h\w\9FE908DE\w\A01A08E9\uploads\Reports\JIT.SIMD\BitwiseOperations_ro\BitwiseOperations_ro.output.txt
Raw output:
BEGIN EXECUTION
BitwiseOperations_ro.dll
1 file(s) copied.
7:52:57.79
Response file: C:\h\w\9FE908DE\w\A01A08E9\e\JIT\SIMD\BitwiseOperations_ro\BitwiseOperations_ro.dll.rsp
C:\h\w\9FE908DE\w\A01A08E9\e\JIT\SIMD\BitwiseOperations_ro\IL-CG2\BitwiseOperations_ro.dll
-o:C:\h\w\9FE908DE\w\A01A08E9\e\JIT\SIMD\BitwiseOperations_ro\BitwiseOperations_ro.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\9FE908DE\p\System..dll
-r:C:\h\w\9FE908DE\p\Microsoft..dll
-r:C:\h\w\9FE908DE\p\mscorlib.dll
-r:C:\h\w\9FE908DE\p\netstandard.dll
-O
" "dotnet" "C:\h\w\9FE908DE\p\crossgen2\crossgen2.dll" @"C:\h\w\9FE908DE\w\A01A08E9\e\JIT\SIMD\BitwiseOperations_ro\BitwiseOperations_ro.dll.rsp"   -r:C:\h\w\9FE908DE\w\A01A08E9\e\JIT\SIMD\BitwiseOperations_ro\IL-CG2*.dll"
7:53:11.05
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\9FE908DE\p
C:\h\w\9FE908DE\w\A01A08E9\e\JIT\SIMD\BitwiseOperations_ro\BitwiseOperations_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._BitwiseOperations_ro_BitwiseOperations_ro_._BitwiseOperations_ro_BitwiseOperations_ro_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
No Kusto information.

**Comment by mangod9** [comment]
closing as this a single failure and we have resolved some non-deterministic problems in vm and gc areas recently. Please reopen if this repros again.
