### ISSUE TITLE
Test failure LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71315]
Run:[ runtime-libraries-coreclr outerloop 20220626.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1846055&view=ms.vss-test-web.build-test-results-tab&runId=48685432&paneView=debug&resultId=100249)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.2110.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.10-helix-arm64v8-20211116135000-0f8d97e

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220427172132-97d8652

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-arm64-CoreCLR_release-(Alpine.313.Arm64.Open)ubuntu.1804.armarch.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-helix-arm64v8-20210910135808-8a6f4f3

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-arm64-CoreCLR_release-(Alpine.314.Arm64.Open)ubuntu.1804.armarch.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Debian.11.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64-20210304164428-5a7c380

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20220523142223-4f64125

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Ubuntu.2110.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-21.04-helix-amd64-20210922170909-34a2d72

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(openSUSE.15.2.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:opensuse-15.2-helix-amd64-20211018152525-9cc02fe

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Centos.7.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20220601183719-dde38af

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-windows-Release-x64-CoreCLR_release-(Windows.10.Amd64.ServerRS5.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2019-helix-amd64-20220502135740-56c6673

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net48-windows-Release-x86-Windows.10.Amd64.Client21H1.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-Linux-Release-x64-CoreCLR_release-(Alpine.313.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-helix-amd64-20210910135845-8a6f4f3

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-OSX-Release-arm64-CoreCLR_release-OSX.1200.ARM64.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic

net7.0-OSX-Release-x64-CoreCLR_release-OSX.1200.Amd64.Open

- LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic
```
**Error message:**
```
Expected 2 diagnostics, but encountered 1. Actual diagnostics:
(6,32): error SYSLIB1053: 'LibraryImportAttribute.StringMarshalling=StringMarshalling.Utf8' has no equivalent in 'DllImportAtttribute' and will not be forwarded
Expected: True
Actual:   False


Stack trace
   at LibraryImportGenerator.UnitTests.Diagnostics.VerifyDiagnostics(DiagnosticResult[] expectedDiagnostics, Diagnostic[] actualDiagnostics) in /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Diagnostics.cs:line 535
   at LibraryImportGenerator.UnitTests.Diagnostics.StringMarshallingForwardingNotSupported_ReportsDiagnostic() in /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Diagnostics.cs:line 332
--- End of stack trace from previous location ---
```

**Comment by jkoritzinsky** [comment]
I'll take a look. This is likely due to the change I made to the char marshallers.
