### ISSUE TITLE
Test failure profiler\\rejit\\rejit\\rejit.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71316]
Run: [runtime-coreclr ilasm  20220625.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1845701&view=ms.vss-test-web.build-test-results-tab&runId=48681312&paneView=debug&resultId=100932)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open

- profiler\\rejit\\rejit\\rejit.cmd

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- profiler\\rejit\\rejit\\rejit.cmd

coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- profiler\\rejit\\rejit\\rejit.cmd

coreclr Linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- profiler/rejit/rejit/rejit.sh

coreclr Linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- profiler/rejit/rejit/rejit.sh

coreclr Linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open

- profiler/rejit/rejit/rejit.sh

coreclr OSX x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open

- profiler/rejit/rejit/rejit.sh

coreclr OSX arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open

- profiler/rejit/rejit/rejit.sh

```
**Error message:**
```
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
at Profiler.Tests.RejitWithInlining.Main(String[] args)

Return code:      1
Raw output file:      D:\h\w\B2CE09F9\w\C11D09ED\uploads\Reports\profiler.rejit\rejit\rejit.output.txt
Raw output:
BEGIN EXECUTION
D:\h\w\B2CE09F9\p\ildasm.exe /raweh /out=rejit.dasm.il rejit.dll
D:\h\w\B2CE09F9\p\ilasm.exe /output=rejit.asm.dll  rejit.dasm.il

Microsoft (R) .NET IL Assembler.  Version 7.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'rejit.dasm.il'  to EXE --> 'rejit.asm.dll'
Source file is UTF-8

Assembled method Profiler.Tests.RejitWithInlining::MaxInlining
Assembled method Profiler.Tests.RejitWithInlining::TriggerReJIT
Assembled method Profiler.Tests.RejitWithInlining::TriggerRevert
Assembled method Profiler.Tests.RejitWithInlining::TriggerInliningChain
Assembled method Profiler.Tests.RejitWithInlining::TriggerDirectInlining
Assembled method Profiler.Tests.RejitWithInlining::CallMethodWithoutInlining
Assembled method Profiler.Tests.RejitWithInlining::InlineeChain1
Assembled method Profiler.Tests.RejitWithInlining::InlineeTarget
Assembled method Profiler.Tests.RejitWithInlining::RunTest
Assembled method Profiler.Tests.RejitWithInlining::Main
Assembled method Profiler.Tests.RejitWithInlining::.ctor
Assembled method Profiler.Tests.RejitWithInlining::.cctor
Assembled method Profiler.Tests.SeparateClassNeverLoaded::TriggerInliningChain
Assembled method Profiler.Tests.SeparateClassNeverLoaded::TriggerDirectInlining
Assembled method Profiler.Tests.SeparateClassNeverLoaded::InlineeChain1
Assembled method Profiler.Tests.SeparateClassNeverLoaded::.ctor
Creating PE file

Emitting classes:
Class 1:Profiler.Tests.RejitWithInlining
Class 2:Profiler.Tests.RejitWithInlining�<>O
Class 3:Profiler.Tests.SeparateClassNeverLoaded

Emitting fields and methods:
Global
Class 1Fields: 1;Methods: 12;
Class 2Fields: 1;
Class 3Methods: 4;
Resolving local member refs: 24 -> 24 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Class 2
Class 3
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
"D:\h\w\B2CE09F9\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  rejit.asm.dll
Profiler path: D:\h\w\B2CE09F9\w\C11D09ED\e\profiler\rejit\rejit\Profiler.dll
Disabling tiered compilation, jitstress, and minopts.
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
INFO ReJITProfiler::Initialize - Initialize started
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=StelemRef Inlinee=GetMethodTable Inlinee module name=D:\h\w\B2CE09F9\p\System.Private.CoreLib.dll
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=StelemRef Inlinee=GetMethodTable Inlinee module name=D:\h\w\B2CE09F9\p\System.Private.CoreLib.dll
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=LdelemaRef Inlinee=GetMethodTable Inlinee module name=D:\h\w\B2CE09F9\p\System.Private.CoreLib.dll
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=LdelemaRef Inlinee=ThrowArrayMismatchException Inlinee module name=D:\h\w\B2CE09F9\p\System.Private.CoreLib.dll
INFO ReJITProfiler::AddInlining - Inlining occurred! Inliner=IndexOf Inlinee=Assert Inlinee module name=D:\h\w\B2CE09F9\p\System.Private.C


Stack trace
   at profiler_rejit._rejit_rejit_._rejit_rejit_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-06-26T00:23:12.197Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48682166&resultId=101187&paneView=debug)
2022-06-26T00:22:56.845Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48682164&resultId=101512&paneView=debug)
2022-06-25T23:30:22.861Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48681660&resultId=101701&paneView=debug)
2022-06-25T23:29:38.983Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nosse](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48681658&resultId=101814&paneView=debug)
2022-06-25T23:26:54.614Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48681648&resultId=101594&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-06-25T23:10:25.825Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_x86_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48681616&resultId=102068&paneView=debug)
2022-06-25T22:09:42.893Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48681462&resultId=102076&paneView=debug)
2022-06-25T21:48:11.453Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=1845714&view=ms.vss-test-web.build-test-results-tab&runId=48681408&resultId=102612&paneView=debug)
2022-06-25T21:31:10.003Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1845701&view=ms.vss-test-web.build-test-results-tab&runId=48681358&resultId=106268&paneView=debug)
2022-06-25T21:27:48.939Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1845701&view=ms.vss-test-web.build-test-results-tab&runId=48681330&resultId=102774&paneView=debug)
2022-06-25T21:10:12.874Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1845701&view=ms.vss-test-web.build-test-results-tab&runId=48681304&resultId=101571&paneView=debug)
2022-06-25T21:01:55.182Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1845701&view=ms.vss-test-web.build-test-results-tab&runId=48681270&resultId=100767&paneView=debug)
2022-06-25T20:58:22.076Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1845701&view=ms.vss-test-web.build-test-results-tab&runId=48681250&resultId=102081&paneView=debug)
2022-06-18T21:37:37.19Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1832517&view=ms.vss-test-web.build-test-results-tab&runId=48485338&resultId=102882&paneView=debug)
2022-06-18T21:37:36.281Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1832517&view=ms.vss-test-web.build-test-results-tab&runId=48485336&resultId=103787&paneView=debug)
2022-06-18T21:11:28.556Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1832517&view=ms.vss-test-web.build-test-results-tab&runId=48484978&resultId=102284&paneView=debug)
2022-06-18T21:11:13.916Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1832517&view=ms.vss-test-web.build-test-results-tab&runId=48484974&resultId=101204&paneView=debug)
2022-06-18T21:07:23.845Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1832517&view=ms.vss-test-web.build-test-results-tab&runId=48484886&resultId=101924&paneView=debug)
2022-06-11T21:38:31.749Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1819697&view=ms.vss-test-web.build-test-results-tab&runId=48290946&resultId=100037&paneView=debug)
2022-06-11T21:35:22.359Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1819697&view=ms.vss-test-web.build-test-results-tab&runId=48290898&resultId=100057&paneView=debug)
2022-06-11T21:22:47.254Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1819697&view=ms.vss-test-web.build-test-results-tab&runId=48290752&resultId=100012&paneView=debug)
2022-06-11T21:17:18.641Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1819697&view=ms.vss-test-web.build-test-results-tab&runId=48290706&resultId=100002&paneView=debug)
2022-06-11T21:15:20.906Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1819697&view=ms.vss-test-web.build-test-results-tab&runId=48290704&resultId=100003&paneView=debug)
2022-06-04T21:20:49.27Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1807135&view=ms.vss-test-web.build-test-results-tab&runId=48101958&resultId=100006&paneView=debug)
2022-06-04T21:18:20.547Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1807135&view=ms.vss-test-web.build-test-results-tab&runId=48101928&resultId=100003&paneView=debug)
2022-06-04T20:57:30.926Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1807135&view=ms.vss-test-web.build-test-results-tab&runId=48101832&resultId=100000&paneView=debug)
2022-06-04T20:55:28.016Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1807135&view=ms.vss-test-web.build-test-results-tab&runId=48101812&resultId=100005&paneView=debug)
2022-06-04T20:51:20.505Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1807135&view=ms.vss-test-web.build-test-results-tab&runId=48101780&resultId=100016&paneView=debug)
2022-05-28T21:24:46.716Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1794939&view=ms.vss-test-web.build-test-results-tab&runId=47935150&resultId=100001&paneView=debug)
2022-05-28T21:22:26.088Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1794939&view=ms.vss-test-web.build-test-results-tab&runId=47935136&resultId=100002&paneView=debug)
2022-05-28T20:58:35.038Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1794939&view=ms.vss-test-web.build-test-results-tab&runId=47934986&resultId=100003&paneView=debug)
2022-05-28T20:58:29.967Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1794939&view=ms.vss-test-web.build-test-results-tab&runId=47934984&resultId=100000&paneView=debug)
2022-05-28T20:56:57.54Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1794939&view=ms.vss-test-web.build-test-results-tab&runId=47934964&resultId=100001&paneView=debug)
2022-05-21T21:20:10.041Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1783199&view=ms.vss-test-web.build-test-results-tab&runId=47770146&resultId=100003&paneView=debug)
2022-05-21T21:17:13.79Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1783199&view=ms.vss-test-web.build-test-results-tab&runId=47770116&resultId=100011&paneView=debug)
2022-05-21T20:51:49.78Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1783199&view=ms.vss-test-web.build-test-results-tab&runId=47769892&resultId=100001&paneView=debug)
2022-05-21T20:51:08.229Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1783199&view=ms.vss-test-web.build-test-results-tab&runId=47769888&resultId=100005&paneView=debug)
2022-05-21T20:48:27.903Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1783199&view=ms.vss-test-web.build-test-results-tab&runId=47769876&resultId=100000&paneView=debug)
2022-05-14T21:29:24.808Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593486&resultId=100001&paneView=debug)
2022-05-14T21:27:04.558Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593432&resultId=100004&paneView=debug)
2022-05-14T21:01:50.223Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593326&resultId=100010&paneView=debug)
2022-05-14T21:01:33.965Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593324&resultId=100002&paneView=debug)
2022-05-14T20:56:11.162Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1771718&view=ms.vss-test-web.build-test-results-tab&runId=47593314&resultId=100006&paneView=debug)
2022-05-07T21:32:50.894Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47369268&resultId=100000&paneView=debug)
2022-05-07T21:29:25.479Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47369232&resultId=100001&paneView=debug)
2022-05-07T21:10:04.074Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47368540&resultId=100001&paneView=debug)
2022-05-07T21:05:29.568Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47368338&resultId=100031&paneView=debug)
2022-05-07T21:01:14.467Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1758220&view=ms.vss-test-web.build-test-results-tab&runId=47368240&resultId=100011&paneView=debug)
2022-04-30T21:29:52.107Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1745805&view=ms.vss-test-web.build-test-results-tab&runId=47145648&resultId=100005&paneView=debug)
2022-04-30T21:27:11.793Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1745805&view=ms.vss-test-web.build-test-results-tab&runId=47145634&resultId=100012&paneView=debug)
2022-04-30T21:07:59.015Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1745805&view=ms.vss-test-web.build-test-results-tab&runId=47145496&resultId=100005&paneView=debug)
2022-04-30T21:03:46.94Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1745805&view=ms.vss-test-web.build-test-results-tab&runId=47145452&resultId=100003&paneView=debug)
2022-04-30T20:57:59.447Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm   Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=1745805&view=ms.vss-test-web.build-test-results-tab&runId=47145384&resultId=100007&paneView=debug)

</details>

category:correctness
theme:asmdiffs
skill-level:beginner
cost:medium
impact:small

**Comment by JulieLeeMSFT** [comment]
Cc @dotnet/jit-contrib. @jakobbotsch PTAL.

**Comment by jakobbotsch** [comment]
Will reassign this to @TIHan since #71119 is assigned to him and this will be solved with that.

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr r2r 20230606.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=297874&view=ms.vss-test-web.build-test-results-tab&runId=6020770&resultId=100034&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - profiler\\rejit\\rejit\\rejit.cmd
```
**Error message:**
```
 Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.RejitWithInlining.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\C2530A3C\w\C0960A39\uploads\Reports\profiler.rejit\rejit\rejit.output.txt
Raw output:
BEGIN EXECUTION
common.dll
Microsoft.Diagnostics.NETCore.Client.dll
Profiler.dll
profiler_common.dll
rejit.dll
TestLibrary.dll
        6 file(s) copied.
 8:10:27.44
Response file: C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\common.dll.rsp
C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\IL-CG2\common.dll
-o:C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\common.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\C2530A3C\p\System.*.dll
-r:C:\h\w\C2530A3C\p\Microsoft.*.dll
-r:C:\h\w\C2530A3C\p\xunit.*.dll
-r:C:\h\w\C2530A3C\p\mscorlib.dll
-r:C:\h\w\C2530A3C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\C2530A3C\p\crossgen2\crossgen2.dll" @"C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\common.dll.rsp"   -r:C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\common.dll
" "dotnet" "C:\h\w\C2530A3C\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\common.dll --out C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\common.dll.r2rdump --val"
 8:10:29.66
 8:10:29.66
Response file: C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Microsoft.Diagnostics.NETCore.Client.dll.rsp
C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\IL-CG2\Microsoft.Diagnostics.NETCore.Client.dll
-o:C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Microsoft.Diagnostics.NETCore.Client.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\C2530A3C\p\System.*.dll
-r:C:\h\w\C2530A3C\p\Microsoft.*.dll
-r:C:\h\w\C2530A3C\p\xunit.*.dll
-r:C:\h\w\C2530A3C\p\mscorlib.dll
-r:C:\h\w\C2530A3C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\C2530A3C\p\crossgen2\crossgen2.dll" @"C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Microsoft.Diagnostics.NETCore.Client.dll.rsp"   -r:C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Microsoft.Diagnostics.NETCore.Client.dll
" "dotnet" "C:\h\w\C2530A3C\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Microsoft.Diagnostics.NETCore.Client.dll --out C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Microsoft.Diagnostics.NETCore.Client.dll.r2rdump --val"
 8:10:31.94
 8:10:31.96
Response file: C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Profiler.dll.rsp
C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\IL-CG2\Profiler.dll
-o:C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Profiler.dll
--targetarch:x64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\C2530A3C\p\System.*.dll
-r:C:\h\w\C2530A3C\p\Microsoft.*.dll
-r:C:\h\w\C2530A3C\p\xunit.*.dll
-r:C:\h\w\C2530A3C\p\mscorlib.dll
-r:C:\h\w\C2530A3C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\C2530A3C\p\crossgen2\crossgen2.dll" @"C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\Profiler.dll.rsp"   -r:C:\h\w\C2530A3C\w\C0960A39\e\profiler\rejit\rejit\IL-CG2\*.dll"
No input files are loadable
 8:10:32.22
 8:10:32.22
R
```

**Stack trace:**
```
    at profiler_rejit._rejit_rejit_._rejit_rejit_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
