### ISSUE TITLE
[runtime-coreclr pgo] nativeruntimeeventsource test fails arm32 and x86

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#71331]
```
Unhandled exception. System.Exception: Condition 'Saw the ThreadPoolIOPack event' is not true
at Tracing.Tests.Common.Assert.True(String name, Boolean condition)
at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args)
```
Fails in various PRs, e.g.:
https://dev.azure.com/dnceng/public/_build/results?buildId=1843344&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1832137&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1840992&view=ms.vss-test-web.build-test-results-tab

**Comment by AndyAyersMS** [comment]
I can't repro this locally yet either running the full pri-1 suite or running just this wrapper. May be some kind of timing issue with other concurrent tests so I will keep trying.

CI logs show the IOPack event is emitted.
```
        [Simple] ThreadID = 8584 ID = 65 Name = ThreadPoolIOPack
        TimeStamp: 6/29/2022 12:04:01 PM
        LocalTime: 6/29/2022 12:04:03 PM
        Difference: 00:00:02.3316022
        Name = "NativeOverlapped" Value = "150706496"
        Name = "Overlapped" Value = "89279024"
        Name = "ClrInstanceID" Value = "0"
```
not sure why it is not recognized.

**Comment by EgorBo** [comment]
I'll try to reproduce too locally, it seems it's a quite stable fail on CI - https://dev.azure.com/dnceng/public/_build?definitionId=1000

**Comment by AndyAyersMS** [comment]
I can repro if the machine is loaded (eg run the single test case while the machine running a build in a different clone of the runtime repo).
```
c:\repos\runtime1\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root\corerun.exe nativeruntimeeventsource.dll  1>D:\bugs\r71331\test1.log
Unhandled exception. System.Exception: Condition 'Saw the ThreadPoolIOPack event' is not true
   at Tracing.Tests.Common.Assert.True(String name, Boolean condition) in C:\repos\runtime1\src\tests\tracing\common\Assert.cs:line 14
   at Tracing.Tests.NativeRuntimeEventSourceTest.Main(String[] args) in C:\repos\runtime1\src\tests\tracing\runtimeeventsource\NativeRuntimeEventSourceTest.cs:line 48

c:\repos\runtime1\artifacts\tests\coreclr\windows.x86.Checked\tracing\runtimeeventsource\nativeruntimeeventsource>echo ERRORLEVEL=-532462766
```
Pretty sure it's just a timing issue with the test

https://github.com/dotnet/runtime/blob/6a02d5d3f35c84915bb71557569564ad07470238/src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs#L30-L49

In the "good" runs we have
```
[Simple] ThreadID = 18116 ID = 65 Name = ThreadPoolIOPack
TimeStamp: 6/29/2022 5:56:35 PM
LocalTime: 6/29/2022 5:56:37 PM
Difference: 00:00:01.4429606
	Name = "NativeOverlapped" Value = "148986208"
	Name = "Overlapped" Value = "87809744"
	Name = "ClrInstanceID" Value = "4"
```
and in the bad one
```
[Simple] ThreadID = 12144 ID = 65 Name = ThreadPoolIOPack
TimeStamp: 6/29/2022 5:54:01 PM
LocalTime: 6/29/2022 5:54:04 PM
Difference: 00:00:02.7299304
	Name = "NativeOverlapped" Value = "156569912"
	Name = "Overlapped" Value = "95742188"
	Name = "ClrInstanceID" Value = "4"
```
I think the event needs to arrive within 2 seconds and in the bad case it takes 2.7 seconds.

@tommcdon can you suggest somebody to verify/refute that this is a timing issue?

**Comment by AndyAyersMS** [comment]
Also (note to self) perfview will dump the raw counts, if you tell it to annotate the source for a method, and look in the log, you'll see something like:
```
GetSourceLine: Getting source line for code address index 0000215A
GetSourceLine: address for code address is 7ffd70e54ad4 module microbenchmarks
GetSourceLine: Found JITTed method System.Text.Json.Document.Tests.Perf_EnumerateArray.EnumerateArray(), index 0000086E token 6001add
GetSourceLine: Found an il-to-native mapping MethodIdx 0000086E Start 7ffd70e54a80 Len 33c
GetSourceLine: NativeOffset 54 ILOffset = c
FindSymbolFilePath: *{ Locating PDB c:\repos\performance\artifacts\obj\MicroBenchmarks\Release\net7.0\MicroBenchmarks.pdb GUID d7c3c786-f5ca-4fea-a8a2-646b668b2aba Age 1 Version 
FindSymbolFilePath: Pdb is for DLL c:\repos\performance\artifacts\bin\microbenchmarks\release\net7.0\e3f010d1-375f-440a-8d2c-94eda8290ad4\bin\release\net7.0\publish\microbenchmarks.dll
FindSymbolFilePath: } Hit Cache, returning c:\repos\performance\artifacts\obj\MicroBenchmarks\Release\net7.0\MicroBenchmarks.pdb
Opened Pdb file c:\repos\performance\artifacts\obj\MicroBenchmarks\Release\net7.0\MicroBenchmarks.pdb
Opened Portable Pdb Source File: c:\repos\performance\src\benchmarks\micro\libraries\System.Text.Json\Document\EnumerateArray.cs

Metric as a function of code address
      Address    :   Line     Metric
    7ffd70e54a94 :     57        1.0
    7ffd70e54aa8 :     57        1.0
    7ffd70e54ab4 :     57        3.0
    7ffd70e54ab8 :     57        1.0
    7ffd70e54ad4 :     57        3.0
    7ffd70e54ad8 :     57        3.0
    7ffd70e54ae4 :     57        1.0
    7ffd70e54aec :     57        1.0
    7ffd70e54b08 :     57        1.0
    7ffd70e54b10 :     57        2.0
    7ffd70e54b20 :     57        2.0
    7ffd70e54b60 :      0        1.0
    7ffd70e54b6c :      0        1.0
    7ffd70e54b88 :      0        1.0
    7ffd70e54bc4 :      0        4.0
    7ffd70e54bdc :      0        7.0
    7ffd70e54be8 :      0      206.0
    7ffd70e54bec :      0       25.0
    7ffd70e54bf0 :      0       29.0
```
This gives similar (though not exactly the same) data as my instructions retired tool with the new -show-samples option, which for the AFTER run above produces:
```
Samples for corerun: 5935 events for Benchmark Intervals
Jitting           : 00.52% 2.3E+05  samples 1729 methods
  JitInterface    : 00.23% 1E+05    samples
Jit-generated code: 99.28% 4.41E+07 samples
  Jitted code     : 99.28% 4.41E+07 samples
  MinOpts code    : 00.00% 0        samples
  FullOpts code   : 00.00% 0        samples
  Tier-0 code     : 00.00% 0        samples
  Tier-1 code     : 99.28% 4.41E+07 samples
  R2R code        : 00.00% 0        samples

93.09%   4.136E+07   Tier-1   [MicroBenchmarks]Perf_EnumerateArray.EnumerateArray()
05.96%   2.65E+06    Tier-1   [System.Text.Json]JsonDocument.CheckNotDisposed()
00.29%   1.3E+05     native   clrjit.dll
00.23%   1E+05       Tier-1   [e3f010d1-375f-440a-8d2c-94eda8290ad4]Runnable_0.WorkloadActionUnroll(int64)
00.14%   6E+04       native   coreclr.dll
00.14%   6E+04       native   ntoskrnl.exe
Raw samples for [MicroBenchmarks]Perf_EnumerateArray.EnumerateArray() at 0x00007FFD70E54A80 -- 0x00007FFD70E54DBC (length 0x033C)
0x0014 : 1
0x0028 : 1
0x0034 : 3
0x0038 : 1
0x0058 : 3
0x0064 : 1
0x006C : 1
0x0088 : 1
0x0090 : 2
0x00A0 : 2
0x00E0 : 1
0x00EC : 1
0x0108 : 1
0x0144 : 4
0x015C : 6
0x0168 : 186
```
The difference may be that my tool uses the exact BDN events to filter the samples, while the perfview report above is using an "include filter" on `WorkloadActionUnroll` and so may capture a bit more.

**Comment by AndyAyersMS** [comment]
Similar results on the M1
```
BenchmarkDotNet=v0.13.1.1786-nightly, OS=macOS Monterey 12.3 (21E230) [Darwin 21.4.0]
Apple M1 Max, 1 CPU, 10 logical and 10 physical cores
.NET SDK=7.0.100-preview.2.22153.17
  [Host]     : .NET 6.0.3 (6.0.322.12309), Arm64 RyuJIT
  Job-VMNNRZ : .NET 7.0.0 (42.42.42.42424), Arm64 RyuJIT
  Job-DELMRH : .NET 7.0.0 (42.42.42.42424), Arm64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  IterationTime=250.0000 ms  MaxIterationCount=20  
MinIterationCount=15  WarmupCount=1  
```
|         Method |        Job |                                                                   Toolchain |  TestCase |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio | Allocated | Alloc Ratio |
|--------------- |----------- |---------------------------------------------------------------------------- |---------- |---------:|----------:|----------:|---------:|---------:|---------:|------:|----------:|------------:|
| EnumerateArray | Job-VMNNRZ | AFTER | Json400KB | 2.314 us | 0.0020 us | 0.0018 us | 2.314 us | 2.313 us | 2.318 us |  1.22 |         - |          NA |
| EnumerateArray | Job-DELMRH | BEFORE | Json400KB | 1.901 us | 0.0030 us | 0.0027 us | 1.902 us | 1.895 us | 1.905 us |  1.00 |         - |          NA |

**Comment by AndyAyersMS** [comment]
> @tommcdon can you suggest somebody to verify/refute that this is a timing issue?

@tommcdon ping

**Comment by tommcdon** [comment]
> @tommcdon can you suggest somebody to verify/refute that this is a timing issue?
Sorry! I wasn't getting the notifications for this and didn't mean to miss this.  @davmason could you take a look?

**Comment by davmason** [comment]
I verified on my machine that I hit it almost 100% when the machine was at 100 CPU usage, and after the fix in #72010 it passes every time.

The only way this could not be a timing issue is if somehow the JIT recognizes that the code here doesn't actually do anything and removes it. From my understanding that is not currently something the JIT would do. https://github.com/dotnet/runtime/blob/246f2458fef4db3ed93d0a7f440e969f548b57c9/src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs#L72-L79
