### ISSUE TITLE
HttpListenerResponse: Unhandled exception. System.ObjectDisposedException

### ISSUE THREAD

**Issue by caoyudeng** [dotnet/runtime#71364]
### Description

Linux localhost.localdomain 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
HttpListener.GetContext() Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.

### Reproduction Steps

Send extremely long Get requests

### Expected behavior

==============================================================

### Actual behavior

Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.<>c.<Close>b__74_0(IAsyncResult iar)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemorySendOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<>c.<TryCancel>b__18_0(Object o)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

====================================================================

**Comment by davidfowl** [comment]
How long was the get request ?

**Comment by caoyudeng** [comment]
300+kb

**Comment by danmoseley** [comment]
Looks like this is .NET 5? That is out of support and not getting security fixes. Could you upgrade to .NET 6 and try again?

**Comment by caoyudeng** [comment]
linux .net 5: Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
linux .net 6:  Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
win .net 5: no exception.

**Comment by caoyudeng** [comment]
[update comment](https://github.com/dotnet/runtime/issues/71364#issue-1286713229)

**Comment by danmoseley** [comment]
Just curious as I'm not a networking person, what is a huge GET request -- a lot of headers? an enormously long URL? huge cookies?

**Comment by caoyudeng** [comment]
curl --location --request GET 'http://127.0.0.1:9527?content=<long url 300+kb>'

**Comment by danmoseley** [comment]
Yeah, that gives argument too long so I guess curl doesn't work for vast URL's.

**Comment by karelz** [comment]
Triage: HttpListener is not in active development. We would likely take a contribution for a fix though.
This looks like a corner case scenario.
