### ISSUE TITLE
QUIC: Hang when calling WriteAsync many times in a loop

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#71370]
### Description

I'm experimenting with replacing one call to `WriteAsync(ReadOnlySequence<byte> buffer, bool endStream)` with multiple calls to `WriteAsync(ReadOnlyMemory<byte> data, bool endStream)` in a loop.

When I make the change, and then attempt to write a large amount data, WriteAsync eventually hangs. Logs show it happened with the 49th write call.

Logs:

```
 Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(dataLength: 5242880)
   Source: QuicStreamContextTests.cs line 150
   Duration: 5.1 sec

  Message: 
System.TimeoutException : The operation has timed out.

  Stack Trace: 
TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) line 88
QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(Int32 dataLength) line 182
QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(Int32 dataLength) line 206
QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(Int32 dataLength) line 206
--- End of stack trace from previous location ---

  Standard Output: 
| [0.007s] TestLifetime Information: Starting test BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData-5242880 at 2022-06-28T07:59:25
| [0.084s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HMIORGF5PO27" accepted.
| [0.089s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests Information: Client starting stream.
| [0.109s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMIORGF5PO27:00000000" type Bidirectional accepted.
| [0.112s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests Information: Server accepted stream.
| [0.116s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests Information: Server sending data.
| [0.119s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 1 with 4096 bytes. 4096 bytes total. Is last: False
| [0.119s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 2 with 4096 bytes. 8192 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 3 with 4096 bytes. 12288 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 4 with 4096 bytes. 16384 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 5 with 4096 bytes. 20480 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 6 with 4096 bytes. 24576 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 7 with 4096 bytes. 28672 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 8 with 4096 bytes. 32768 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 9 with 4096 bytes. 36864 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 10 with 4096 bytes. 40960 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 11 with 4096 bytes. 45056 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 12 with 4096 bytes. 49152 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 13 with 4096 bytes. 53248 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 14 with 4096 bytes. 57344 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 15 with 4096 bytes. 61440 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 16 with 4096 bytes. 65536 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 17 with 4096 bytes. 69632 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 18 with 4096 bytes. 73728 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 19 with 4096 bytes. 77824 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 20 with 4096 bytes. 81920 bytes total. Is last: False
| [0.120s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 21 with 4096 bytes. 86016 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 22 with 4096 bytes. 90112 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 23 with 4096 bytes. 94208 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 24 with 4096 bytes. 98304 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 25 with 4096 bytes. 102400 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 26 with 4096 bytes. 106496 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 27 with 4096 bytes. 110592 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 28 with 4096 bytes. 114688 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 29 with 4096 bytes. 118784 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 30 with 4096 bytes. 122880 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 31 with 4096 bytes. 126976 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 32 with 4096 bytes. 131072 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 33 with 4096 bytes. 135168 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 34 with 4096 bytes. 139264 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 35 with 4096 bytes. 143360 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 36 with 4096 bytes. 147456 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 37 with 4096 bytes. 151552 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 38 with 4096 bytes. 155648 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 39 with 4096 bytes. 159744 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 40 with 4096 bytes. 163840 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 41 with 4096 bytes. 167936 bytes total. Is last: False
| [0.121s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 42 with 4096 bytes. 172032 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 43 with 4096 bytes. 176128 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 44 with 4096 bytes. 180224 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 45 with 4096 bytes. 184320 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 46 with 4096 bytes. 188416 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 47 with 4096 bytes. 192512 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 48 with 4096 bytes. 196608 bytes total. Is last: False
| [0.122s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Information: Writing segment 49 with 4096 bytes. 200704 bytes total. Is last: False
| [5.128s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HMIORGF5PO27:00000000" shutting down writes because: "Operation aborted.".
| [5.132s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests Error: Test threw an exception.
| System.TimeoutException: The operation has timed out.
|    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in C:\Development\Source\aspnetcore\src\Shared\TaskExtensions.cs:line 88
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(Int32 dataLength) in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\test\QuicStreamContextTests.cs:line 182
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(Int32 dataLength) in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\test\QuicStreamContextTests.cs:line 206
|    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicStreamContextTests.BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData(Int32 dataLength) in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\test\QuicStreamContextTests.cs:line 206
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
| [5.135s] TestLifetime Information: Finished test BidirectionalStream_ServerWritesDataAndDisposes_ClientReadsData-5242880 in 5.131289s
```

### Reproduction Steps

Code before:

```cs
var buffer = ...;
await _stream.WriteAsync(buffer, endStream: isCompleted);
```

Code after:

```cs
var buffer = ...;
var enumerator = buffer.GetEnumerator();
var isLastSegment = !enumerator.MoveNext();
var totalBytes = 0;
var segmentCount = 0;

while (!isLastSegment)
{
    var currentSegment = enumerator.Current;

    totalBytes += currentSegment.Length;
    segmentCount++;
    isLastSegment = !enumerator.MoveNext();

    _log.LogInformation($"Writing segment {segmentCount} with {currentSegment.Length} bytes. {totalBytes} bytes total. Is last: {isLastSegment}");
    await _stream.WriteAsync(currentSegment, endStream: isLastSegment && isCompleted);
}
```

### Expected behavior

Write all the data like `WriteAsync(ReadOnlySequence<byte>)` does.

### Actual behavior

Multiple calls to `WriteAsync(ReadOnlyMemory<byte>)` hangs.

**Comment by rzikm** [comment]
I am unable to reproduce this, do you perhaps have a self-contained repro you could share?

**Comment by rzikm** [comment]
The test is trying to write the entire data blob in its entirety before starting to read it

```cs
        Logger.LogInformation("Server sending data.");
        await serverStream.Transport.Output.WriteAsync(testData).DefaultTimeout();

        Logger.LogInformation("Server completing pipes.");
        await serverStream.Transport.Input.CompleteAsync().DefaultTimeout();
        await serverStream.Transport.Output.CompleteAsync().DefaultTimeout();

        Logger.LogInformation("Client reading until end of stream.");
        var data = await clientStream.ReadUntilEndAsync().DefaultTimeout();
```

You have no guarantee how much data will the stream accept before the calls to `WriteAsync` start blocking, and since you are not reading them, the test deadlocks.

The fact that this has not been the issue before is due to the buffering strategy MsQuic has, if I read the source correctly, it boils down something like:

```
if total_buffered_bytes < ideal_buffered_bytes
    buffer the entire write request and complete the ValueTask
else
    wait until total_buffered_bytes drops below ideal_buffered_bytes before buffering this request
```

So if you pass one giant blob of data, then it gets buffered entirely, but if you pass it in small chunks, it will block once the limit is reached. Note that the ideal_buffered_bytes value changes dynamically based on the congestion control and other factors.

There is nothing to fix on the library's side, you need to fix the test, e.g.:

```cs
        var readingTask = clientStream.ReadUntilEndAsync();
        Logger.LogInformation("Server sending data.");
        await serverStream.Transport.Output.WriteAsync(testData).DefaultTimeout();

        Logger.LogInformation("Server completing pipes.");
        await serverStream.Transport.Input.CompleteAsync().DefaultTimeout();
        await serverStream.Transport.Output.CompleteAsync().DefaultTimeout();

        Logger.LogInformation("Client reading until end of stream.");
        var data = await readingTask.DefaultTimeout();
```
