### ISSUE TITLE
QUIC: Port 50009 throws QUIC_STATUS_ADDRESS_IN_USE

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#71518]
### Description

In .NET 6 I have unit tests that start a Kestrel HTTP/3 endpoint on port 50019. It works fine.

I updated the unit test to .NET 7 and it now throws QUIC_STATUS_ADDRESS_IN_USE. Why is that? Is it a bug, or intentional behavior? If it's intentional then there should be documentation about what ports can be used.

### Reproduction Steps

Small modification to the empty ASP.NET Core template to add a H3 port:

```cs
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel(c =>
{
    c.ListenLocalhost(50009, listner =>
    {
        listner.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http3;
        listner.UseHttps();
    });
});
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

### Expected behavior

Works

### Actual behavior

```
System.IO.IOException
  HResult=0x80131620
  Message=Failed to bind to address https://localhost:50009.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.<BindAsync>d__2.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.<BindAsync>d__2.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<BindAsync>d__33.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__30`1.MoveNext()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\Users\james\source\repos\WebApplication6\WebApplication6\Program.cs:line 14

  This exception was originally thrown at this call stack:
    Microsoft.Quic.MsQuic.ThrowIfFailure(int, string)
    System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start(System.Net.Quic.QuicListenerOptions)
    System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener(System.Net.Quic.QuicListenerOptions)
    System.Net.Quic.QuicListener.ListenAsync(System.Net.Quic.QuicListenerOptions, System.Threading.CancellationToken)
    Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.CreateListenerAsync()
    Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(System.Net.EndPoint, Microsoft.AspNetCore.Http.Features.IFeatureCollection, System.Threading.CancellationToken)
    System.Threading.Tasks.ValueTask<TResult>.Result.get()
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(System.Net.EndPoint, Microsoft.AspNetCore.Connections.MultiplexedConnectionDelegate, Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, System.Threading.CancellationToken)
    Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync.__OnBind|0(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, System.Threading.CancellationToken)
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext, System.Threading.CancellationToken)
    ...
    [Call Stack Truncated]

Inner Exception 1:
AggregateException: One or more errors occurred.

Inner Exception 2:
MsQuicException: ListenerStart failed: QUIC_STATUS_ADDRESS_IN_USE
```

### Regression?

Yes

### Known Workarounds

Use a different port

**Comment by JamesNK** [comment]
The fix in my unit test project was to change the port to 55019. Why it works and 50019 doesn't.... 🤷‍♂️

**Comment by wfurt** [comment]
did you try to dump ports using `netstat`? AFAIK this error comes from Kernel. This could be sign of some old process sticking around.

**Comment by rzikm** [comment]
This does not look like .NET Runtime bug, the error comes from MsQuic.

I was able to reproduce this even outside MsQuic using the sample app from https://docs.microsoft.com/en-us/windows/win32/winsock/sio-acquire-port-reservation, the problematic range seems to be ports 50000-50059.

I filed issue with MsQuic to see if they can do something about it: https://github.com/microsoft/msquic/issues/2891

**Comment by rzikm** [comment]
There is something called _Port Exclusion Ranges_ apparently that affects this:

```
> netsh int ip show excludedportrange protocol=udp

Protocol udp Port Exclusion Ranges

Start Port    End Port
----------    --------
     50000       50059     *
     55642       55741
     63552       63651

* - Administered port exclusions.
```

**Comment by rzikm** [comment]
Tracking by (internal) OS issue: https://microsoft.visualstudio.com/OS/_workitems/edit/40464377

**Comment by karelz** [comment]
Triage: There is nothing we can do. It needs to be address in the OS. Moving to Future for tracking purposes.
If we see enough customers hitting it, we should document it properly.

**Comment by ManickaP** [comment]
Closing as by design: https://github.com/microsoft/msquic/issues/2891#issuecomment-3615011164
