### ISSUE TITLE
Test failure JIT\\opt\\OSR\\tailpgo\\tailpgo.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71519]
Run: [runtime-coreclr outerloop 20220630.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1855128&view=ms.vss-test-web.build-test-results-tab&runId=48816554&resultId=104095&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\OSR\\tailpgo\\tailpgo.cmd

```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](https://dev.azure.com/dnceng/public/_build/results?buildId=1855128&view=ms.vss-test-web.build-test-results-tab&runId=48816554&resultId=104095&paneView=debug)
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef) at System.Threading.Tasks.TaskReplicator+Replica.Execute() at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object) at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task+<>c.<.cctor>b__273_0(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean) at System.Threading.Tasks.Task.RunSynchronously(System.Threading.Tasks.TaskScheduler) at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean)
at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action1<Int32>, System.Action2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func1<System.__Canon>, System.Action1<System.__Canon>) at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IList1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action1<System.__Canon>, System.Action2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func4<System.__Canon,System.Threading.Tasks.ParallelLoopState


Stack trace
   at JIT_opt._OSR_tailpgo_tailpgo_._OSR_tailpgo_tailpgo_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS PTAL this blocking outerloop test failure.

**Comment by AndyAyersMS** [comment]
Seems like a failure in crossgen2, but I'll dig in and get more info.

**Comment by AndyAyersMS** [comment]
I can't repro this, and it's only failed once in the past 14 days (with over 500 successful runs in the meantime, though maybe not all on this particular config).

Since it's crossgen2 that is failing perhaps there is some bug in 7p5 (which is hosting crossgen2 here).
