### ISSUE TITLE
Test failure System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_TwoByte

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71604]
Run: [runtime-coreclr libraries-jitstress 20220703.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1859046&view=ms.vss-test-web.build-test-results-tab&runId=48865172&paneView=debug&resultId=162605)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_TwoByte

```
**Error message:**
```
Assert.Equal() Failure
Expected: 176
Actual:   235


Stack trace
   at System.SpanTests.ReadOnlySpanTests.TestMatchLastIndexOfAny_TwoByte() in /_/src/libraries/System.Memory/tests/ReadOnlySpan/LastIndexOfAny.T.cs:line 74
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by jakobbotsch** [comment]
I see no occurrences of this in the past month history we have for libraries-jitstress. I'll just close this.
