### ISSUE TITLE
Test failure System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71692]
Run: [runtime-coreclr libraries-jitstress 20220705.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1860579&view=ms.vss-test-web.build-test-results-tab&runId=48884374&paneView=debug&resultId=191850)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof() in /_/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs:line 62
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by Jozkee** [comment]
The assertion suggests that the child process (the `RemoteExecutor` one) using the client anonymous pipe fails to finish, but I don't see in which conditions it may hang for more than 30 secs. 
I tried attaching to both, client and server code and alternated between "client reads after/before server dispose" but no repro. 

@stephentoub @dotnet/area-system-io any ideas?

**Comment by stephentoub** [comment]
This is a jitstress run.  Was this failure a one-off?

**Comment by Jozkee** [comment]
It has a couple of failures on non-jitstress:
https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA22PwUoDQRBE7/sVRS7RU34gewoGVhBCFDzKOF26bTbdYXqyySEf7+KCePDUFPVeQb8w6p5xHmqgueHL1XBQk1bNWPDq5dBVHgNuv6GT/9BHf/+hptvJ1F96FmKrptFTsG5hfrm7b1arZIInRqRPIrvVpBZYcKRViMrEVXjO54IU4PXEXCmLZtZq7/LHemYZWTaDB2OnJ75tBp129szUkfHgH7M4/4i2xXKbdFh+Ax9XSqn4AAAA

**Comment by stephentoub** [comment]
One of those four is an assert failure on this line in the child:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs#L71
```
Expected: 1
Actual:   -842150655
   at System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.<ServerClosesPipe_ClientReceivesEof>g__ChildFunc|1_0(String clientHandle) in /_/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs:line 71
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```
It's possible the others that seemingly hang are different manifestations of whatever the same issue is.

One theory:
The test is creating the stream handles as inheritable:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Pipes/tests/AnonymousPipeTests/AnonymousPipeTest.CrossProcess.cs#L54
This makes sense given that it's launching a child process with which to communicate.  But if another test running concurrently were to also schedule a child process, and then that child process were to go away, that could impact these handles.

We might try moving the whole test into a remote invoke process (which would in turn create its own child).

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20230211.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=168368)
 
 **Failed tests:**
 ```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x1000-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs8-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x10-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs4-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs3-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue 
```
 
 **Error message:**
 ```
 Assert.True() Failure
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs:line 63
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
 ```

**Comment by BruceForstall** [comment]
The last report here is a different test, so I opened https://github.com/dotnet/runtime/issues/82055 to track that.

**Comment by v-wenyuxu** [comment]
Failed in Run: [runtime-coreclr libraries-jitstress 20230301.2](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=190643)
 
 **Failed tests:**
 ```
net8.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue

net8.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.11.Arm64.Open

- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue
```
 
 **Error message:**
 ```
 Assert.True() Failure
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedWindowsPlatforms_IsSupportedIsTrue() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
 ```

**Comment by BruceForstall** [comment]
The above failure was unrelated to this issue, and didn't happen subsequently, so probably can be ignored.

The other failures no longer appear, and isn't being investigated, so I'm closing this issue. It's certainly not blocking anymore.
