### ISSUE TITLE
Crossgen2 crashes intermittently on Windows ARM64

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71702]
Run: [runtime-coreclr outerloop 20220705.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1862466&view=ms.vss-test-web.build-test-results-tab&runId=48917226&paneView=debug&resultId=104343)
Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\CodeGenBringUpTests\\LocallocCnstB1_d\\LocallocCnstB1_d.cmd

```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Expand(System.__Canon[]) at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrGetExistingInner(System.__Canon, Boolean ByRef)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrGetExisting(System.__Canon) at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValueAndEnsureValueIsInTable(System.__Canon)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrCreateValue(System.__Canon) at ILCompiler.CompilerTypeSystemContext.EnsureLoadableType(Internal.TypeSystem.TypeDesc) at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(Internal.TypeSystem.TypeDesc) at ILCompiler.CompilerTypeSystemContext+ValidTypeHashTable.CreateValueFromKey(Internal.TypeSystem.TypeDesc) at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValueAndEnsureValueIsInTable(System.__Canon)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrCreateValue(System.__Canon) at ILCompiler.CompilerTypeSystemContext.EnsureLoadableType(Internal.TypeSystem.TypeDesc) at ILCompiler.CompilerTypeSystemContext.EnsureLoadableMethod(Internal.TypeSystem.MethodDesc) at Internal.JitInterface.CorInfoImpl.resolveToken(Internal.JitInterface.CORINFO_RESOLVED_TOKEN ByRef) at Internal.JitInterface.CorInfoImpl._resolveToken(IntPtr, IntPtr*, Internal.JitInterface.CORINFO_RESOLVED_TOKEN*) at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef) at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef) at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL) at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef,


Stack trace
   at JIT_CodeGenBringUpTests._LocallocCnstB1_d_LocallocCnstB1_d_._LocallocCnstB1_d_LocallocCnstB1_d_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by VincentBu** [comment]
Failed again in: [ runtime-coreclr outerloop 20220714.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1882214&view=ms.vss-test-web.build-test-results-tab&runId=49216106&resultId=106711&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- Loader\\CollectibleAssemblies\\ByRefLocals\\ByRefLocals\\ByRefLocals.cmd

```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Expand(System.__Canon[]) at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrGetExistingInner(System.__Canon, Boolean ByRef)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrGetExisting(System.__Canon) at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValueAndEnsureValueIsInTable(System.__Canon)
at Internal.TypeSystem.LockFreeReaderHashtable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrCreateValue(System.__Canon) at ILCompiler.CompilerTypeSystemContext.EnsureLoadableType(Internal.TypeSystem.TypeDesc) at ILCompiler.CompilerTypeSystemContext.EnsureLoadableMethod(Internal.TypeSystem.MethodDesc) at Internal.JitInterface.CorInfoImpl.resolveToken(Internal.JitInterface.CORINFO_RESOLVED_TOKEN ByRef) at Internal.JitInterface.CorInfoImpl._resolveToken(IntPtr, IntPtr*, Internal.JitInterface.CORINFO_RESOLVED_TOKEN*) at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef) at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef) at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL) at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

Return code:      1
Raw output file:      D:\h\w\B7EA0A1E\w\A1270949\uploads\Reports\Loader.CollectibleAssemblies\ByRefLocals\ByRefLocals\ByRefLocals.output.txt
Raw output:
BEGIN EXECUTION
ByRefLocals.dll
SpanAccessor.dll
Unloaded.dll
3 file(s) copied.
21:01:06.29
Response file: D:\h\w\B7EA0A1E\w\A1270949\e\Loader\CollectibleAssemblies\ByRefLocals\ByRefLocals\ByRefLocals.dll.rsp
D:\h\w\B7EA0


Stack trace
   at Loader_CollectibleAssemblies._ByRefLocals_ByRefLocals_ByRefLocals_._ByRefLocals_ByRefLocals_ByRefLocals_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr crossgen2 20220721.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1897099&view=ms.vss-test-web.build-test-results-tab&runId=49408756&resultId=102028&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- GC\\Regressions\\Github\\runtime_32848\\runtime_32848\\runtime_32848.cmd
```

**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at Internal.TypeSystem.LockFreeReaderHashtable2[[Internal.TypeSystem.TypeSystemContext+InstantiatedTypeKey, ILCompiler.TypeSystem, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Expand(System.__Canon[]) at Internal.TypeSystem.LockFreeReaderHashtable2[[Internal.TypeSystem.TypeSystemContext+InstantiatedTypeKey, ILCompiler.TypeSystem, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrGetExistingInner(System.__Canon, Boolean ByRef)
at Internal.TypeSystem.LockFreeReaderHashtable2[[Internal.TypeSystem.TypeSystemContext+InstantiatedTypeKey, ILCompiler.TypeSystem, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddOrGetExisting(System.__Canon) at Internal.TypeSystem.LockFreeReaderHashtable2[[Internal.TypeSystem.TypeSystemContext+InstantiatedTypeKey, ILCompiler.TypeSystem, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateValueAndEnsureValueIsInTable(InstantiatedTypeKey)
at Internal.TypeSystem.LockFreeReaderHashtable2[[Internal.TypeSystem.TypeSystemContext+InstantiatedTypeKey, ILCompiler.TypeSystem, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrCreateValue(InstantiatedTypeKey) at Internal.TypeSystem.TypeSystemContext.GetInstantiatedType(Internal.TypeSystem.MetadataType, Internal.TypeSystem.Instantiation) at Internal.TypeSystem.InstantiatedType.InstantiateSignature(Internal.TypeSystem.Instantiation, Internal.TypeSystem.Instantiation) at Internal.TypeSystem.FieldForInstantiatedType.get_FieldType() at Internal.TypeSystem.MetadataFieldLayoutAlgorithm.ComputeContainsGCPointers(Internal.TypeSystem.DefType) at Internal.TypeSystem.DefType.ComputeTypeContainsGCPointers() at Internal.TypeSystem.DefType.get_ContainsGCPointers() at Internal.JitInterface.CorInfoImpl.getClassAttribsInternal(Internal.TypeSystem.TypeDesc) at Internal.JitInterface.CorInfoImpl._getClassAttribs(IntPtr, IntPtr*, Internal.JitInterface.CORINFO_CLASS_STRUCT_*) at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef) at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef) at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL) at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at Syst


Stack trace
   at GC_Regressions._Github_runtime_32848_runtime_32848_runtime_32848_._Github_runtime_32848_runtime_32848_runtime_32848_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by shimingsg** [comment]
Failed again in: [runtime-coreclr r2r 20220802.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1919888&view=ms.vss-test-web.build-test-results-tab&runId=49733856&resultId=102860&paneView=debug)

Failed test:
```
R2R windows arm64 Checked @ Windows.10.Arm64v8.Open

- Loader\\classloader\\methodoverriding\\regressions\\593884\\vsw593884\\vsw593884.cmd
```

**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at System.Collections.Generic.Stack1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor() at Internal.JitInterface.CorInfoImpl..ctor() at Internal.JitInterface.CorInfoImpl..ctor(ILCompiler.ReadyToRunCodegenCompilation) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__38_6(System.Threading.Thread) at System.Runtime.CompilerServices.ConditionalWeakTable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetValueLocked(System.__Canon, CreateValueCallback<System.__Canon,System.__Canon>)
at System.Runtime.CompilerServices.ConditionalWeakTable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetValue(System.__Canon, CreateValueCallback<System.__Canon,System.__Canon>) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef) at System.Threading.Tasks.TaskReplicator+Replica.Execute() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean) at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean)
at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action1<Int32>, System.Action2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func1<System.__Canon>, System.Action1<System.__Canon>) at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action1<System.__Canon>, System.Action2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func1<System.__Canon>, System.Action`1<System.__Canon>)
at System.Threading.Tasks.Parallel.ForEach[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d


Stack trace
   at Loader_classloader._methodoverriding_regressions_593884_vsw593884_vsw593884_._methodoverriding_regressions_593884_vsw593884_vsw593884_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by AntonLapounov** [comment]
@MichalStrehovsky Have you seen this before?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Have you seen this before?

We have #72645 for Linux Arm64. That one is for NativeAOT-compiled crossgen2 though.

We don't AOT compile crossgen2 used in testing, so this sounds like a possible CoreCLR bug.

Hard to say if they're related. Could be.

**Comment by AntonLapounov** [comment]
We need to collect crash dumps.

**Comment by MichalStrehovsky** [comment]
We haven't seen it on Mac arm64? NativeAOT doesn't support that and we ship crossgen2 on top of CoreCLR there

**Comment by AntonLapounov** [comment]
This might be a dup of #75041.  Closing as non-actionable.
