### ISSUE TITLE
Test failure JIT/Methodical/refany/virtcall_do/virtcall_do.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71806]
Run:[ runtime-coreclr outerloop 20220707.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1866139&view=ms.vss-test-web.build-test-results-tab&runId=48965114&paneView=debug&resultId=104242)

Failed test:
```
R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- JIT/Methodical/refany/virtcall_do/virtcall_do.cmd

```
**Error message:**
```
/root/helix/work/workitem/e/JIT/Methodical/Methodical_do/../refany/virtcall_do/virtcall_do.sh: line 256: -r:/root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/IL-CG2/*.dll: No such file or directory

Assert failure(PID 5696 [0x00001640], Thread: 5696 [0x1640]): (*(CORCOMPILE_GCREFMAP_TOKENS )ppObj == NULL) || ((CORCOMPILE_GCREFMAP_TOKENS *)ppObj == newToken)
File: /__w/1/s/src/coreclr/vm/frames.cpp Line: 2000
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/e/JIT/Methodical/Methodical_do/../refany/virtcall_do/virtcall_do.sh: line 389:  5696 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/refany/virtcall_do/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/IL-CG2/virtcall_do.dll
20:29:51
Response file: /root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/virtcall_do.dll.rsp
/root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/IL-CG2/virtcall_do.dll
-o:/root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/virtcall_do.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/virtcall_do.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/Methodical/refany/virtcall_do/virtcall_do.dll
20:29:53
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false virtcall_do.dll ''
[createdump] Gathering state for process 5696 corerun
[createdump] Crashing thread 00001640 signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5696.dmp
[createdump] Written 96202752 bytes (23487 pages) to core file
[createdump] Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.

/root/helix/work/workitem/e/JIT/Methodical/Methodical_do/../refany/virtcall_do/virtcall_do.sh
Expected: True
Actual:   False


Stack trace
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String basePath, String assemblyPath)
   at Program.<Main>$(String[] args)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test
-- | -- | -- | -- | -- | --
2022-07-07T20:57:55.237Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T20:57:54.034Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T11:31:28.149Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T11:31:27.032Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T07:35:28.035Z | runtime-coreclr crossgen2 | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T07:35:26.8Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T07:32:42.759Z | runtime-coreclr crossgen2 outerloop | Checked | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T07:32:41.572Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T07:28:09.956Z | runtime-coreclr crossgen2 outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T07:28:08.459Z | runtime-coreclr crossgen2 outerloop | Checked | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T03:43:36.826Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do
2022-07-07T03:43:35.714Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.amd64.open | x64 | JIT/Methodical/refany/virtcall_do/virtcall_do

**Comment by BruceForstall** [comment]
@dotnet/crossgen-contrib

**Comment by ivdiazsa** [comment]
This failure apparently hasn't reproduced in the past couple of weeks and I can't get it to repro locally either. It passes well on both, my Linux and MacOS machines. Should we close the issue and reopen it if it repros again @mangod9?
