### ISSUE TITLE
Linker crashing with `System.NotImplementedException: switch`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#71848]
Failing on an unrelated https://github.com/dotnet/runtime/pull/71821 [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1868684&view=logs&j=fdcf4e60-0ea7-5f2b-0c09-3aee5fc1ad67&t=988ef9df-dca9-5ab3-3f87-0e162924ca92&l=3248).

```
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues [/__w/1/s/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/System.Text.RegularExpressions.Tests.csproj]
##[error]ILLink(0,0): error IL1012: (NETCORE_ENGINEERING_TELEMETRY=Build) IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues
  Fatal error in IL Linker
  Unhandled exception. System.NotImplementedException: switch
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.IsConstantBranch(OpCode opCode, Int32 operand)
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.RemoveConditions()
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.BodyReducer.RewriteBody()
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
/__w/1/s/.dotnet/sdk/7.0.100-preview.5.22307.18/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(110,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/System.Text.RegularExpressions.Tests.csproj]
##[error].dotnet/sdk/7.0.100-preview.5.22307.18/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(110,5): error NETSDK1144: (NETCORE_ENGINEERING_TELEMETRY=Build) Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
```

Interestingly, this is failing only for the wasm/highresource_aot jobs, and not the regular AOT ones.
- highresource_aot: runs *some* library tests, and run them on the build machine itself
- regular EAT/AOT: runs the tests on helix

Could it be using an older linker?

cc @vitek-karas @sbomer @marek-safar

**Comment by lewing** [comment]
System.Text.RegularExpressions.Tests is high resource so that makes sense

**Comment by radical** [comment]
`System.Text.RegularExpressions.Tests` isn't built in EAT, or AOT builds. Only in the highresource_aot .

**Comment by pavelsavara** [comment]
[Another log](https://dev.azure.com/dnceng/public/_build/results?buildId=1869917&view=logs&jobId=7768facb-0c9d-5dd5-0fa0-b8bf2c83581b&j=fdcf4e60-0ea7-5f2b-0c09-3aee5fc1ad67&t=988ef9df-dca9-5ab3-3f87-0e162924ca92)

**Comment by vitek-karas** [comment]
https://github.com/dotnet/linker/pull/2889 has a fix to make linker not crash.
