### ISSUE TITLE
[wasm] Tests randomly failing because the results xml was empty

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#71843]
Example [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71821-merge-35580f487c134821ad/WasmTestOnNodeJs-System.Net.WebHeaderCollection.Tests/1/console.59a5b563.log?helixlogtype=result):

```
2022-07-08T16:47:35.760Z	INFO   	run.py	__init__(48)	read_results	Found results file /datadisks/disk1/work/A0CE0977/w/B2EB091E/uploads/xharness-output/testResults.xml with format xunit
Traceback (most recent call last):
  File "/datadisks/disk1/work/A0CE0977/p/reporter/run.py", line 68, in <module>
    main()
  File "/datadisks/disk1/work/A0CE0977/p/reporter/run.py", line 65, in main
    reporter.report_results(all_results)
  File "/etc/helix/scripts/helix/test_reporting/packing_test_reporter.py", line 27, in report_results
    results = [x for x in results if x]
  File "/etc/helix/scripts/helix/test_reporting/packing_test_reporter.py", line 27, in <listcomp>
    results = [x for x in results if x]
  File "/datadisks/disk1/work/A0CE0977/p/reporter/test_results_reader/__init__.py", line 51, in read_results
    for result in file_results:
  File "/datadisks/disk1/work/A0CE0977/p/reporter/formats/xunit.py", line 47, in read_results
    for (_, element) in xml.etree.ElementTree.iterparse(path, events=['end']):
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1227, in iterator
    root = pullparser._close_and_return_root()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1274, in _close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

This will be fixed by https://github.com/dotnet/xharness/pull/919 .

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/xharness/pull/919, https://github.com/dotnet/runtime/pull/71866 .
