### ISSUE TITLE
[wasm] `System.Net.Http.Functional.Tests*EventSource_ExistsWithCorrectId` failing on Windows/Chrome

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#71877]
The bump to emsdk `3.1.12` - https://github.com/dotnet/runtime/pull/70693 also switches the windows library tests to run on `Chrome`, instead of `V8`. And this causes some more tests to be run.

`System.Net.Http.Functional.Tests*EventSource_ExistsWithCorrectId` are failing:
https://github.com/dotnet/runtime/blob/88d75e9676f767f94ab26acd876a2b1a46627143/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs#L34-L39

```
[FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest_Http2.EventSource_ExistsWithCorrectId
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Private.InternalDiagnostics.System.Net.Ht···
Actual:   NetEventSource
          ↑ (pos 0)
   at System.Net.Http.Functional.Tests.DiagnosticsTest.EventSource_ExistsWithCorrectId()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] System.Net.Http.Functional.Tests.SyncHttpHandler_DiagnosticsTest.EventSource_ExistsWithCorrectId
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Private.InternalDiagnostics.System.Net.Ht···
Actual:   NetEventSource
          ↑ (pos 0)
   at System.Net.Http.Functional.Tests.DiagnosticsTest.EventSource_ExistsWithCorrectId()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )

[FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest_Http11.EventSource_ExistsWithCorrectId
Assert.Equal() Failure
          ↓ (pos 0)
Expected: Private.InternalDiagnostics.System.Net.Ht···
Actual:   NetEventSource
          ↑ (pos 0)
   at System.Net.Http.Functional.Tests.DiagnosticsTest.EventSource_ExistsWithCorrectId()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
```

cc @lambdageek @pavelsavara

**Comment by lewing** [comment]
cc @lateralusX @lambdageek

**Comment by rzikm** [comment]
I see the same issues happening on NativeAOT runs
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ad2dbf4f19a44c52a7/System.Net.Security.Tests/3/console.49b9355a.log?helixlogtype=result

**Comment by ilonatommy** [comment]
Still a problem. This is not only `Windows - Chrome`, also `Linux - chrome/firefox`
```
[FAIL] System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ExistsWithCorrectId
[FAIL] System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ExistsWithCorrectId
   Assert.Equal() Failure: Strings differ
                    ↓ (pos 0)
   Expected: "System.Net.Http"
   Actual:   "HttpTelemetry"
```
