### ISSUE TITLE
Test failure readytorun\\tests\\fileversionpreservation\\fileversionpreservation\\fileversionpreservation.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71919]
Run: [runtime-coreclr ilasm 20220709.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1870330&view=ms.vss-test-web.build-test-results-tab&runId=49017232&paneView=debug&resultId=106731)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open

- readytorun\\tests\\fileversionpreservation\\fileversionpreservation\\fileversionpreservation.cmd
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- readytorun\\tests\\fileversionpreservation\\fileversionpreservation\\fileversionpreservation.cmd
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- readytorun\\tests\\fileversionpreservation\\fileversionpreservation\\fileversionpreservation.cmd
- JIT\\Directed\\debugging\\poisoning\\poison\\poison.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\A43808E8\w\BA8509E6\uploads\Reports\readytorun.tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.output.txt
Raw output:
BEGIN EXECUTION
D:\h\w\A43808E8\p\ildasm.exe /raweh /unicode /out=fileversionpreservation.dasm.il fileversionpreservation.dll
D:\h\w\A43808E8\p\ilasm.exe /output=fileversionpreservation.asm.dll  fileversionpreservation.dasm.il

Microsoft (R) .NET IL Assembler.  Version 7.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'fileversionpreservation.dasm.il'  to EXE --> 'fileversionpreservation.asm.dll'
Source file is UNICODE

Assembled method Program::Main
Assembled method Program::CheckVersionResourceUsingApi
Assembled method Program::RunTest
Assembled method Program::.ctor
Creating PE file

Emitting classes:
Class 1:Program

Emitting fields and methods:
Global
Class 1Methods: 4;
Resolving local member refs: 3 -> 3 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
"D:\h\w\A43808E8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  fileversionpreservation.asm.dll
D:\h\w\A43808E8\w\BA8509E6\e\readytorun\tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.asm.dll has version ""
D:\h\w\A43808E8\w\BA8509E6\e\readytorun\tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.asm.dll has version ""
END EXECUTION OF IL{D}ASM BINARY - FAILED -1 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A43808E8\p
D:\h\w\A43808E8\w\BA8509E6\e\readytorun\tests\fileversionpreservation\fileversionpreservation\fileversionpreservation.cmd
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._fileversionpreservation_fileversionpreservation_fileversionpreservation_._fileversionpreservation_fileversionpreservation_fileversionpreservation_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by TIHan** [comment]
It looks like ILASM does not respect the `AssemblyFileVersionAttribute` and does not output this information to the `File Version` of a file.

**Comment by TIHan** [comment]
A little related: https://github.com/dotnet/runtime/issues/23542

I'm wondering if we can extract the resource file from the C# compiled DLL with ILDASM and use it in ILASM.

**Comment by TIHan** [comment]
`ILASM` for .NET Core removed embedding resources in https://github.com/dotnet/coreclr/pull/20818 because it depended on `CvtRes.exe`.

An issue was filed to come up with a strategy to enable embedding resources again in ILASM: https://github.com/dotnet/runtime/issues/11412

**Comment by TIHan** [comment]
@JulieLeeMSFT To get this test to pass, we have to do: https://github.com/dotnet/runtime/issues/11412 - which might a fair amount of work. In the meantime, I recommend we disable this test.

**Comment by TIHan** [comment]
Closing.
