### ISSUE TITLE
HardwareIntrinsics RunReflectionScenario_Load failing due to "Assertion failed 'tgtIG'"

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#71950]
I didn't see an issue for this, but did see https://github.com/dotnet/runtime/issues/59447. My local build on Windows with debug runtime and release libraries have these failures:

```
Failed test: JIT_HardwareIntrinsics::_X86_Avx1_Avx_ro_Avx_ro_cmd (JIT\\HardwareIntrinsics\\X86\\Avx1\\Avx_ro\\Avx_ro.cmd)
Failed test: JIT_HardwareIntrinsics::_X86_Avx2_Avx2_ro_Avx2_ro_cmd (JIT\\HardwareIntrinsics\\X86\\Avx2\\Avx2_ro\\Avx2_ro.cmd)
Failed test: JIT_HardwareIntrinsics::_X86_Sse2_Sse2_r_Sse2_r_cmd (JIT\\HardwareIntrinsics\\X86\\Sse2\\Sse2_r\\Sse2_r.cmd)
```

Sample detail:
```
        Beginning scenario: RunReflectionScenario_Load
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=c:\git\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
        > c:\git\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\HardwareIntrinsics\X86\Sse2\Sse2_r\Sse2_r.cmd_windows_x64_Debug.cmd
        Expected: True
        Actual:   False
        Stack Trace:
          c:\git\runtime\artifacts\tests\coreclr\windows.x64.Debug\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(23810,0): at JIT_HardwareIntrinsics._X86_Sse2_Sse2_r_Sse2_r__windows_x64_Debug_._X
  86_Sse2_Sse2_r_Sse2_r_cmd_windows_x64_Debug_cmd()
             at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
             at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
        Output:

          Assert failure(PID 9420 [0x000024cc], Thread: 38064 [0x94b0]): Assertion failed 'tgtIG' in 'DynamicClass:InvokeStub_Sse2.StoreScalar(System.Object,System.Object,long):System.Object' during 'Generate code' (IL size
  37; hash 0xf44d3c9c; MinOpts)

              File: C:\git\runtime\src\coreclr\jit\emit.cpp Line: 4732
              Image: c:\git\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe
```

**Comment by JulieLeeMSFT** [comment]
@TIHan PTAL. cc @dotnet/jit-contrib.

**Comment by TIHan** [comment]
Been looking at this. It looks like one of the `jmp`s is a `BBJ_NONE` which means it's not an actual jump - somehow it is part of the jump list in `emitJumpDistBind`. This will take time, at least for me, as I'm unfamiliar with this area.

**Comment by TIHan** [comment]
Update: I'm still tracking this down, but there is a piece of code in `genCodeForTreeNode` that's interesting:
```cpp
        case GT_LABEL:
            genPendingCallLabel = genCreateTempLabel();
            emit->emitIns_R_L(INS_lea, EA_PTR_DSP_RELOC, genPendingCallLabel, treeNode->GetRegNum());
            break;
```
The `genPendingCallLabel` is not getting its `bbEmitCookie` assigned, which is why the assert hits.

**Comment by TIHan** [comment]
@steveharter Are these tests failing in some out-of-band CI runs? Current CI is not running these tests and can't quite figure out why.
