### ISSUE TITLE
[wasm] `STJ.Serialization.Tests.JsonIgnoreAttribute_UnsupportedCollection` failing on `main`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#71981]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1872987&view=logs&jobId=e36cdb78-1b23-5f53-5d15-e931194c7d32&j=b4344b0d-0f92-5d69-ccaf-e0b24fbf14a2&t=65a58faa-a542-5344-b5c8-897139f242cd), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71875-merge-624f8760879e44f287/System.Text.Json.Tests/1/console.f2a38d09.log?helixlogtype=result):

```
    System.Text.Json.Serialization.Tests.PropertyVisibilityTestsDynamic.JsonIgnoreAttribute_UnsupportedCollection [FAIL]
      System.UriFormatException : Invalid URI: The hostname could not be parsed.
      Stack Trace:
        /_/src/libraries/System.Private.Uri/src/System/UriExt.cs(42,0): at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
        /_/src/libraries/System.Private.Uri/src/System/Uri.cs(369,0): at System.Uri..ctor(String uriString)
        /_/src/libraries/System.Text.Json/tests/Common/PropertyVisibilityTests.cs(1193,0): at System.Text.Json.Serialization.Tests.PropertyVisibilityTests.JsonIgnoreAttribute_UnsupportedCollection()
        --- End of stack trace from previous location ---
  Finished:    System.Text.Json.Tests
```

**Comment by radical** [comment]
> FYI disabled tests are no longer blocking CI so removing label

Oops, sorry, missed this one!

**Comment by eiriktsarpalis** [comment]
@radical PTAL at this comment: https://github.com/dotnet/runtime/pull/71875/files#r919266335

Judging by the original code in this change, this appears to be a regression in System.Uri contructor validation.

**Comment by eiriktsarpalis** [comment]
I think simply reverting the accidental change would be good for now.
