### ISSUE TITLE
 System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest failures

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#71986]
### JSImportExportTest failures found in `Browser wasm Linux Release LibraryTests` leg

Found in: https://github.com/dotnet/runtime/pull/71851/checks?check_run_id=7292394030
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71851-merge-41355897a98b4bb08f/normal-System.Runtime.InteropServices.JavaScript.Tests/1/console.111b700c.log?helixlogtype=result
```
[23:07:43] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JSImportObject(value: Object { }, clazz: "ManagedObject")
[23:07:43] info: Assert.Equal() Failure
[23:07:43] info:           ↓ (pos 0)
[23:07:43] info: Expected: ManagedObject
[23:07:43] info: Actual:   Rr
[23:07:43] info:           ↑ (pos 0)
[23:07:43] info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTest[Object](Object value, Action`1 store1, Func`1 retrieve1, Func`2 echo1, Func`2 throw1, Func`2 identity1, String jsType, String jsClass)
[23:07:43] info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JSImportObject(Object value, String clazz)
[23:07:43] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[23:07:44] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JSImportException(value: System.Exception: Test, clazz: "ManagedError")
[23:07:44] info: Assert.Equal() Failure
[23:07:44] info:           ↓ (pos 0)
[23:07:44] info: Expected: ManagedError
[23:07:44] info: Actual:   jr
[23:07:44] info:           ↑ (pos 0)
[23:07:44] info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTest[Exception](Exception value, Action`1 store1, Func`1 retrieve1, Func`2 echo1, Func`2 throw1, Func`2 identity1, String jsType, String jsClass)
[23:07:44] info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JSImportException(Exception value, String clazz)
[23:07:44] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[23:07:45] info: Finished:    System.Runtime.InteropServices.JavaScript.Tests.dll
[23:07:45] info: 
[23:07:45] info: === TEST EXECUTION SUMMARY ===
[23:07:45] info: Total: 348, Errors: 0, Failed: 2, Skipped: 0, Time: 5.769732s
```

**Comment by vcsjones** [comment]
Looks like this will be fixed by https://github.com/dotnet/runtime/pull/71976.

**Comment by radical** [comment]
#71976 has been merged.
