### ISSUE TITLE
Test failure Loader\\classloader\\SequentialLayout\\ManagedSequential\\ManagedSequential\\ManagedSequential.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71987]
Run:; [runtime-coreclr gcstress-extra 20220710.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1871169&view=ms.vss-test-web.build-test-results-tab&runId=49029452&paneView=debug&resultId=104601)

Failed test:
```
coreclr windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open

- Loader\\classloader\\SequentialLayout\\ManagedSequential\\ManagedSequential\\ManagedSequential.cmd

coreclr windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- Loader\\classloader\\SequentialLayout\\ManagedSequential\\ManagedSequential\\ManagedSequential.cmd

coreclr Linux x64 Checked gcstress0xc_jitstress2 @ Ubuntu.1804.Amd64.Open

- Interop/PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.sh
- Loader/classloader/SequentialLayout/ManagedSequential/ManagedSequential/ManagedSequential.sh

coreclr Linux x64 Checked gcstress0xc_jitstress1 @ Ubuntu.1804.Amd64.Open

- Interop/PInvoke/SetLastError/SetLastErrorTest/SetLastErrorTest.sh

- Loader/classloader/SequentialLayout/ManagedSequential/ManagedSequential/ManagedSequential.sh

coreclr windows x64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- Loader\\classloader\\SequentialLayout\\ManagedSequential\\ManagedSequential\\ManagedSequential.cmd

coreclr OSX arm64 Checked gcstress0xc_tailcallstress @ OSX.1200.ARM64.Open

- JIT/Methodical/Boxing/boxunbox/KeepAliveBoxOpt/KeepAliveBoxOpt.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\AC4C0937\w\A8B60955\uploads\Reports\Loader.classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AC4C0937\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ManagedSequential.dll
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 8
Actual:   752
at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
at Program.<Main>$(String[] args)
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AC4C0937\p
C:\h\w\AC4C0937\w\A8B60955\e\Loader\classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_classloader._SequentialLayout_ManagedSequential_ManagedSequential_ManagedSequential_._SequentialLayout_ManagedSequential_ManagedSequential_ManagedSequential_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment]
This looks like a GC hole in JIT's codegen. The test is computing the offset of a field in the following way:
```csharp
    [StructLayout(LayoutKind.Sequential)]
    class LayoutClassObjectBase
    {
        public byte b1;
        public long l1;
    }

    [Fact]
    public static void LayoutClassObjectBaseIsManagedSequential()
    {
        var o = new LayoutClassObjectBase();
        // Validate that the long member is placed after the byte member, as is done with sequential layout in this case.
        Assert.Equal(8, (int)Unsafe.ByteOffset(ref o.b1, ref Unsafe.As<long, byte>(ref o.l1)));
    }
```

The JIT produces:
```asm
                            ; gcrRegs +[rax]
                            ; gcr arg pop 0
       488D4808             lea      rcx, bword ptr [rax+8]
                            ; byrRegs +[rcx]
       4883C010             add      rax, 16
                            ; gcrRegs -[rax]
                            ; byrRegs +[rax]
       8BF0                 mov      esi, eax
       2BF1                 sub      esi, ecx
```
the 32-bit subtraction is illegal, `esi` cannot contain the lower half of a byref this way.
