### ISSUE TITLE
System.IndexOutOfRangeException when using System.Text.Json 7.0 Preview 5 to do polymorphism serialize/deserialize

### ISSUE THREAD

**Issue by SilentCC** [dotnet/runtime#71994]
### Description

Recently I noticed that System.Text.Json support polymorphism deserialization in [.NET 7 Preivew 5](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-5/#polymorphism)
When I tried to using System.Text.Json to serialize **polymorphism class** that has a **nested structure**, it throwed an exception:

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.WriteStack.Push()
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at ConsoleTest.Serialization.IntergateWithNewtonsoft.PolymorphismTest() in D:\Source\Repos\ConsoleTest\ConsoleTest\System.Text.Json\IntergateWithNewtonsoft.cs:line 65
   at ConsoleTest.Program.Main(String[] args) in D:\Source\Repos\ConsoleTest\ConsoleTest\Program.cs:line 139
```

### Reproduction Steps

- System.Text.Json package version: 	
   `<PackageReference Include="System.Text.Json" Version="7.0.0-preview.5.22301.12" />`
- polymorphism class with nested structure:
```csharp
 [JsonDerivedType(typeof(Student), "ConsoleTest.Serialization.Student, ConsoleTest")]
    [JsonDerivedType(typeof(Teacher), "ConsoleTest.Serialization.Teacher, ConsoleTest")]
    public abstract class Person
    {
        public string Name { get; set; }
    }

    public class Student : Person
    {
        public string Class { get; set; }

        public IEnumerable<Person> Friends { get; set; }
    }

    public class Teacher : Person
    {
        public string Test { get; set; }
    }
```
- The serialized object
```csharp
 Person person = new Student
            {
                Name = "testName",
                Class = "1",
                Friends = new List<Person>
                {
                    new Teacher
                    {
                        Name = "testName2"
                    },

                    new Student
                    {
                        Name = "testName3",
                        Class = "2",
                        Friends = new List<Person>
                        {
                            new Student
                            {
                                Name = "testName4",
                                Class = "1"
                            }
                        }

                    }
                }
            };
```
- Serialize object
```csharp
   string json = System.Text.Json.JsonSerializer.Serialize(person);
```

### Expected behavior

It should return a json string.

### Actual behavior

It throws an System.IndexOutOfRangeException exception

### Other information

I compared with Newtonsoft.Json.
Here is the serialized code using Newtonsoft.Json
```csharp
  var binder = new KnownTypesBinder(new List<Type>
            {
                typeof(Student),
                typeof(Teacher)
            });

            var settings = new JsonSerializerSettings
            {
                TypeNameHandling = TypeNameHandling.Arrays | TypeNameHandling.Objects,
                SerializationBinder = binder,
            };

            string json = JsonConvert.SerializeObject(person, settings);
```

The result output from Newtonsoft:

```json
{
    "$type": "ConsoleTest.Serialization.Student, ConsoleTest",
    "Class": "1",
    "Friends": {
        "$type": "System.Collections.Generic.List`1[[ConsoleTest.Serialization.Person, ConsoleTest]], mscorlib",
        "$values": [
            {
                "$type": "ConsoleTest.Serialization.Teacher, ConsoleTest",
                "Test": null,
                "Name": "testName2"
            },
            {
                "$type": "ConsoleTest.Serialization.Student, ConsoleTest",
                "Class": "2",
                "Friends": {
                    "$type": "System.Collections.Generic.List`1[[ConsoleTest.Serialization.Person, ConsoleTest]], mscorlib",
                    "$values": [
                        {
                            "$type": "ConsoleTest.Serialization.Student, ConsoleTest",
                            "Class": "1",
                            "Friends": null,
                            "Name": "testName4"
                        }
                    ]
                },
                "Name": "testName3"
            }
        ]
    },
    "Name": "testName1"
}
```

**Comment by krwq** [comment]
Ok, seems the problem we're not increasing size of the stack correctly (off by 1). I'll send a patch soon, let me just try to find if there are any similar places which also need a fix
