### ISSUE TITLE
`System.Net.Quic.Functional.Tests` crash on coreclr/windows/x64

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#71995]
Hit on unrelated PR https://github.com/dotnet/runtime/pull/71875.
[build](https://dev.azure.com/dnceng/public/_build/results?buildId=1873866&view=logs&jobId=55b384d0-d6b0-5894-fd8a-d754d713246e&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71875-merge-82003482303e48ceb6/System.Net.Quic.Functional.Tests/1/console.0d396d7f.log?helixlogtype=result):

```
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 86 of 96 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
Process terminated. Assertion failed.
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ShutdownAsync(QUIC_CONNECTION_SHUTDOWN_FLAGS Flags, Int64 ErrorCode) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 598
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 762
   at System.Net.Quic.QuicConnection.CloseAsync(Int64 errorCode, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 79
   at System.Net.Quic.QuicListener.PendingConnection.StartHandshake(QuicConnection connection, SslClientHelloInfo clientHello, Func`4 connectionOptionsCallback) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.PendingConnection.cs:line 74
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 328
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
----- end Tue 07/12/2022  4:19:31.28 ----- exit code -2146232797 ----------------------------------------------------------
```

**Comment by ManickaP** [comment]
Interestingly, it didn't surface on #71579. This will be properly solved with #71783, but I'll put up a quick fix in the meantime.
