### ISSUE TITLE
System.Text.Json.Tests.Utf8JsonReaderTests.ReadJsonStringsWithComments rolling build failure on net7.0-Linux-Release-arm-CoreCLR_checked-(Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7-20210910135806-8a6f4f3

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#72100]
[Build](https://runfo.azurewebsites.net/view/build/?number=1874165)
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-455133167ff14f12a7/System.Text.Json.Tests/1/console.dfb6e8f2.log?%3Fhelixlogtype%3Dresult)

```
Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 4)
    System.Text.Json.Tests.Utf8JsonReaderTests.ReadJsonStringsWithComments(jsonString: "{\"Property1\": {\"Property1.1\": 42}, // comment\"...) [FAIL]
      System.InvalidOperationException : End position was not reached during enumeration.
      Stack Trace:
        /_/src/libraries/System.Memory/src/System/ThrowHelper.cs(43,0): at System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached()
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.MultiSegment.cs(325,0): at System.Text.Json.Utf8JsonReader.GetNextSpan()
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.MultiSegment.cs(1561,0): at System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(Byte marker)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.MultiSegment.cs(213,0): at System.Text.Json.Utf8JsonReader.ReadMultiSegment()
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs(285,0): at System.Text.Json.Utf8JsonReader.Read()
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Utf8JsonReaderTests.MultiSegment.cs(2096,0): at System.Text.Json.Tests.Utf8JsonReaderTests.ReadWithCommentsHelper(Utf8JsonReader& reader, Int32 expectedConsumed, Boolean validateThrows)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Utf8JsonReaderTests.MultiSegment.cs(1989,0): at System.Text.Json.Tests.Utf8JsonReaderTests.ReadJsonStringsWithComments(String jsonString)
           at InvokeStub_Utf8JsonReaderTests.ReadJsonStringsWithComments(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by karelz** [comment]
Only one hit in [last 60 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E60+definition%3Aruntime+name%3A%22system.text.json.tests.utf8jsonreadertests.readjsonstringswithcomments%22) (as of 7/22). Removing blocking-clean-ci label.
