### ISSUE TITLE
Test failure System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72238]
Run: [runtime-libraries-coreclr outerloop 20220714.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1880437&view=ms.vss-test-web.build-test-results-tab&runId=49187402&resultId=104088&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

```
**Error message:**
```
Assert.Equal() Failure
Expected: ConnectionAborted
Actual:   ConnectionIdle


Stack trace
   at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 53
   at System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 584
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Failures on both x86 and x64, Windows only

Failures only 7/14-7/18 (always in last retry, no PassedOnRerun). It seems to be gone (no failures 7/19-7/21) - removing 'blocking-outerloop'.
@ManickaP @CarnaViire @rzikm any idea what might have addressed it? Perhaps we should close it and wait for other occurrences?

**Comment by ManickaP** [comment]
It's still happening on main, I have a fix ready, PR will be up today.

**Comment by VincentBu** [comment]
Failed again in : [runtime-libraries-coreclr outerloop 20220724.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1900181&view=ms.vss-test-web.build-test-results-tab&runId=49452190&paneView=debug&resultId=103378)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x86-CoreCLR_release-Windows.11.Amd64.Client.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout

net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout
```

**Error message:**
```
Assert.Equal() Failure
Expected: ConnectionAborted
Actual:   ConnectionIdle


Stack trace
   at System.Net.Quic.Tests.QuicTestBase.AssertThrowsQuicExceptionAsync(QuicError expectedError, Func`1 testCode) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 60
   at System.Net.Quic.Tests.MsQuicTests.SetListenerTimeoutWorksWithSmallTimeout() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 628
--- End of stack trace from previous location ---
```
