### ISSUE TITLE
System.Collections.Immutable.Tests.ImmutableInterlockedTests.UpdateArray_HighConcurrency test failure on tvOs

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#72282]
[Build](https://runfo.azurewebsites.net/view/build/?number=1881678)
``NullReferenceException at System.Threading.Tasks.Task.AddToList[Task](Task item, List`1& list, Int32 initSize)``
First instance of the failure.

**Comment by danmoseley** [comment]
Best to include diagnostic info so it's convenient and searchable
```
      <test name="System.Collections.Immutable.Tests.ImmutableInterlockedTests.UpdateArray_HighConcurrency" type="System.Collections.Immutable.Tests.ImmutableInterlockedTests" method="UpdateArray_HighConcurrency" time="0.0200371" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object]]></message>
          <stack-trace><![CDATA[   at System.Threading.Tasks.Task.AddToList[Task](Task item, List`1& list, Int32 initSize)
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at System.Collections.Immutable.Tests.ImmutableInterlockedTests.<>c.<UpdateArray_HighConcurrency>b__12_0(UpdateArrayDelegate`1 func)
   at System.Collections.Immutable.Tests.ImmutableInterlockedTests.UpdateArrayHelper[Int32](Action`1 test)
   at System.Collections.Immutable.Tests.ImmutableInterlockedTests.UpdateArray_HighConcurrency()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)]]></stack-trace>
```

**Comment by agocke** [comment]
Roslyn uses ImmutableInterlocked a *ton* in extremely high stress scenarios and I don't think we've seen any failures. My suspicion is that this is likely a Mono runtime bug.

**Comment by karelz** [comment]
One occurrence only -> removing blocking-clean-ci label.
