### ISSUE TITLE
[libraries-pgo] NRE in System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#72363]
Failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1886357&view=ms.vss-test-web.build-test-results-tab&runId=49269680&resultId=111042&paneView=debug
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5b5f63f24f5746a780/System.Collections.Immutable.Tests/1/console.6b41d0ff.log?helixlogtype=result
```scala
    System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Enumerator.cs(202,0): at System.Collections.Immutable.ImmutableList`1.Enumerator.ResetStack()
        /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Enumerator.cs(107,0): at System.Collections.Immutable.ImmutableList`1.Enumerator..ctor(Node root, Builder builder, Int32 startIndex, Int32 count, Boolean reversed)
        /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Node.cs(766,0): at System.Collections.Immutable.ImmutableList`1.Node.IndexOf(T item, Int32 index, Int32 count, IEqualityComparer`1 equalityComparer)
        /_/src/libraries/System.Collections.Immutable/tests/IndexOfTests.cs(78,0): at System.Collections.Immutable.Tests.IndexOfTests.IndexOfTest[TCollection](Func`2 factory, Func`3 indexOfItem, Func`4 indexOfItemIndex, Func`5 indexOfItemIndexCount, Func`6 indexOfItemIndexCountEQ)
        /_/src/libraries/System.Collections.Immutable/tests/ImmutableArrayBuilderTest.cs(253,0): at System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    System.Collections.Immutable.Tests
```

**Comment by jakobbotsch** [comment]
Seems to have some other failure modes too, e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1886445&view=ms.vss-test-web.build-test-results-tab&runId=49278402&resultId=134107&paneView=debug

```scala
    System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf [FAIL]
      System.InvalidCastException : Unable to cast object of type 'Builder[System.Int32]' to type 'System.Collections.IList'.
      Stack Trace:
        /_/src/libraries/System.Collections.Immutable/tests/IndexOfTests.cs(78,0): at System.Collections.Immutable.Tests.IndexOfTests.IndexOfTest[TCollection](Func`2 factory, Func`3 indexOfItem, Func`4 indexOfItemIndex, Func`5 indexOfItemIndexCount, Func`6 indexOfItemIndexCountEQ)
        /_/src/libraries/System.Collections.Immutable/tests/ImmutableArrayBuilderTest.cs(253,0): at System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Unfortunately haven't had any luck reproing either of these yet after running the tests in a loop and with various amounts of concurrent CPU load.

**Comment by jakobbotsch** [comment]
Unrelated to the problem at hand, but I've noticed the following infinite recursion is possible with the debug-only textual PGO data that calls `TypeName::GetTypeManaged` from `getPgoInstrumentationResults` JIT-EE method:

1. We start jitting `System.Reflection.AssemblyNameParser.Parse`
2. We inline `NumberFormatInfo.get_CurrentInfo`
3. We request PGO information for that function, which can have a type handle histogram
4. With textual PGO input this calls `TypeName::GetTypeManaged` as mentioned above
5. `TypeName::GetTypeManaged` ends up calling into `AssemblyName.ParseAsAssemblySpec` that calls `AssemblyNameParser.Parse`, which starts jitting it again.

Stack trace with interesting frames:
```scala
00007FFC07C2CD90 00007F10710E5C3C System.Private.CoreLib.dll!System.Reflection.AssemblyNameParser.Parse() + 2460 [/home/jakob/dev/dotnet/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyNameParser.cs @ 126]
00007FFC07C2CE60 00007F10710E4DC6 System.Private.CoreLib.dll!System.Reflection.AssemblyName.ParseAsAssemblySpec(Char*, Void*) + 614
00007FFC07C2CF80 00007F10EF1B35DF libcoreclr.so!CallDescrWorkerInternal + 124 at /home/jakob/dev/dotnet/runtime/src/coreclr/pal/inc/unixasmmacrosamd64.inc:839
00007FFC07C2CFA0 00007F10EEF423DB libcoreclr.so!CallDescrWorkerWithHandler(CallDescrData*, int) + 331 at /home/jakob/dev/dotnet/runtime/src/coreclr/pal/inc/pal.h:4856
00007FFC07C2CFF0 00007F10EEF4270C libcoreclr.so!DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 204 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/callhelpers.cpp:218
00007FFC07C2D070 00007F10EEF7F05D libcoreclr.so!BaseAssemblySpec::Init(SString&) + 173 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/coreassemblyspec.cpp:0
00007FFC07C2D0E0 00007F10EF0B6AB0 libcoreclr.so!LoadDomainAssembly(SString*, Assembly*, AssemblyBinder*, int) + 192 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/typeparse.cpp:1411
00007FFC07C2D410 00007F10EF0B544F libcoreclr.so!TypeName::GetTypeWorker(int, int, Assembly*, int, int, Assembly*, AssemblyBinder*, OBJECTREF*) + 351 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/typeparse.cpp:1109
00007FFC07C2D980 00007F10EF0B6105 libcoreclr.so!TypeName::GetTypeManaged(char16_t const*, DomainAssembly*, int, int, int, Assembly*, OBJECTREF*, AssemblyBinder*) + 373 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/typeparse.cpp:939
00007FFC07C2DE90 00007F10EEEA6276 libcoreclr.so!PgoManager::getPgoInstrumentationResults(MethodDesc*, unsigned char**, ICorJitInfo::PgoInstrumentationSchema**, unsigned int*, unsigned char**, ICorJitInfo::PgoSource*) + 1542 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/pgo.cpp:0
00007FFC07C2E530 00007F10EEE52A6F libcoreclr.so!CEEJitInfo::getPgoInstrumentationResults(CORINFO_METHOD_STRUCT_*, ICorJitInfo::PgoInstrumentationSchema**, unsigned int*, unsigned char**, ICorJitInfo::PgoSource*) + 383 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/jitinterface.cpp:11920
00007FFC07C2E5E0 00007F106E026DF4 libclrjit.so!Compiler::compInitOptions(JitFlags*) + 1700 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:2727
00007FFC07C2E660 00007F106E02E186 libclrjit.so!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*) + 278 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.hpp:3838
00007FFC07C2E710 00007F106E02D1A7 libclrjit.so!Compiler::compCompile(CORINFO_MODULE_STRUCT_*, void**, unsigned int*, JitFlags*) + 2215 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:0
00007FFC07C2E710 00007F106E02D186 libclrjit.so!Compiler::compCompile(CORINFO_MODULE_STRUCT_*, void**, unsigned int*, JitFlags*) + 2182 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:5931
00007FFC07C2E7F0 00007F106E02FD81 libclrjit.so!jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 833 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:7431
00007FFC07C2E7F0 00007F106E02FBDB libclrjit.so!jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 411 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:7387
00007FFC07C2E7F0 00007F106E02FBD7 libclrjit.so!jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 407 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:7383
00007FFC07C2EE00 00007F106E07001F libclrjit.so!Compiler::fgInvokeInlineeCompiler(GenTreeCall*, InlineResult*, InlineContext**)::$_0::__invoke(Compiler::fgInvokeInlineeCompiler(GenTreeCall*, InlineResult*, InlineContext**)::Param*) + 447 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/fginline.cpp:1005
00007FFC07C2EE00 00007F106E06FE7B libclrjit.so!Compiler::fgInvokeInlineeCompiler(GenTreeCall*, InlineResult*, InlineContext**)::$_0::__invoke(Compiler::fgInvokeInlineeCompiler(GenTreeCall*, InlineResult*, InlineContext**)::Param*) + 27 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/fginline.cpp:948
00007FFC07C2EE50 00007F10EEE4EDB5 libcoreclr.so!CEEInfo::runWithErrorTrap(void (*)(void*), void*) + 325 at /home/jakob/dev/dotnet/runtime/src/coreclr/pal/inc/pal.h:4856
00007FFC07C2EEF0 00007F106E06DEA1 libclrjit.so!Compiler::fgInvokeInlineeCompiler(GenTreeCall*, InlineResult*, InlineContext**) + 529 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/fginline.cpp:1023
00007FFC07C2EEF0 00007F106E06DE8B libclrjit.so!Compiler::fgInvokeInlineeCompiler(GenTreeCall*, InlineResult*, InlineContext**) + 507 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.h:7736
00007FFC07C2F9B0 00007F106E1BC530 libclrjit.so!Compiler::fgMorphCallInlineHelper(GenTreeCall*, InlineResult*, InlineContext**) + 560 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/inline.h:357
00007FFC07C2F9F0 00007F106E1BC1DE libclrjit.so!Compiler::fgMorphCallInline(GenTreeCall*, InlineResult*) + 110 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/inline.h:392
00007FFC07C2FA30 00007F106E06D7A0 libclrjit.so!Compiler::fgInline() + 640 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/gentree.h:7304
00007FFC07C2FB80 00007F106E203816 libclrjit.so!Phase::Run() + 118 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/phase.cpp:61
00007FFC07C2FBD0 00007F106E029D61 libclrjit.so!Compiler::compCompile(void**, unsigned int*, JitFlags*) + 961 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:8799
00007FFC07C2FBD0 00007F106E029D20 libclrjit.so!Compiler::compCompile(void**, unsigned int*, JitFlags*) + 896 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/phase.h:37
00007FFC07C2FE90 00007F106E02EE21 libclrjit.so!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*) + 3505 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.hpp:3838
00007FFC07C2FF40 00007F106E02D1A7 libclrjit.so!Compiler::compCompile(CORINFO_MODULE_STRUCT_*, void**, unsigned int*, JitFlags*) + 2215 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:0
00007FFC07C2FF40 00007F106E02D186 libclrjit.so!Compiler::compCompile(CORINFO_MODULE_STRUCT_*, void**, unsigned int*, JitFlags*) + 2182 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:5931
00007FFC07C30020 00007F106E02FD81 libclrjit.so!jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 833 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:7431
00007FFC07C30020 00007F106E02FBDB libclrjit.so!jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 411 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:7387
00007FFC07C30020 00007F106E02FBD7 libclrjit.so!jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 407 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:7383
00007FFC07C30630 00007F106E03C536 libclrjit.so!CILJit::compileMethod(ICorJitInfo*, CORINFO_METHOD_INFO*, unsigned int, unsigned char**, unsigned int*) + 278 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/ee_il_dll.cpp:276
00007FFC07C306D0 00007F10EEE5429A libcoreclr.so!invokeCompileMethodHelper(EEJitManager*, CEEInfo*, CORINFO_METHOD_INFO*, CORJIT_FLAGS, unsigned char**, unsigned int*) + 234 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/jitinterface.cpp:12347
00007FFC07C30720 00007F10EEE5433A libcoreclr.so!invokeCompileMethod(EEJitManager*, CEEInfo*, CORINFO_METHOD_INFO*, CORJIT_FLAGS, unsigned char**, unsigned int*) + 90 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/jitinterface.cpp:0
00007FFC07C30790 00007F10EEE5544E libcoreclr.so!UnsafeJitFunction(PrepareCodeConfig*, COR_ILMETHOD_DECODER*, CORJIT_FLAGS, unsigned int*) + 2702 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/jitinterface.cpp:0
00007FFC07C313B0 00007F10EEEAE24A libcoreclr.so!MethodDesc::JitCompileCodeLocked(PrepareCodeConfig*, ListLockEntryBase<NativeCodeVersion>*, unsigned int*, CORJIT_FLAGS*) + 746 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/prestub.cpp:0
00007FFC07C314E0 00007F10EEEADD76 libcoreclr.so!MethodDesc::JitCompileCodeLockedEventWrapper(PrepareCodeConfig*, ListLockEntryBase<NativeCodeVersion>*) + 710 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/prestub.cpp:832
00007FFC07C315D0 00007F10EEEAD33D libcoreclr.so!MethodDesc::JitCompileCode(PrepareCodeConfig*) + 1005 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/prestub.cpp:0
00007FFC07C316A0 00007F10EEEAC71B libcoreclr.so!MethodDesc::PrepareILBasedCode(PrepareCodeConfig*) + 507 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/prestub.cpp:426
00007FFC07C31750 00007F10EEDCB336 libcoreclr.so!CodeVersionManager::PublishVersionableCodeIfNecessary(MethodDesc*, CallerGCMode, bool*, bool*) + 950 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/codeversion.cpp:1698
00007FFC07C318B0 00007F10EEEB13DA libcoreclr.so!MethodDesc::DoPrestub(MethodTable*, CallerGCMode) + 1242 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/prestub.cpp:2120
00007FFC07C319D0 00007F10EEEB0950 libcoreclr.so!PreStubWorker + 2176 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/prestub.cpp:0
00007FFC07C31A20                  [PrestubMethodFrame: 00007ffc07c31a20] System.Private.CoreLib.dll!System.Reflection.AssemblyNameParser.ParseVersion(System.String)
00007FFC07C31AE0 00007F10EF1B4274 libcoreclr.so!ThePreStub + 92 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/amd64/theprestubamd64.S:18
00007FFC07C31BD0 00007F10710E5C3C System.Private.CoreLib.dll!System.Reflection.AssemblyNameParser.Parse() + 2460 [/home/jakob/dev/dotnet/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyNameParser.cs @ 126]
00007FFC07C31CA0 00007F10710E4DC6 System.Private.CoreLib.dll!System.Reflection.AssemblyName.ParseAsAssemblySpec(Char*, Void*) + 614
00007FFC07C31DC0 00007F10EF1B35DF libcoreclr.so!CallDescrWorkerInternal + 124 at /home/jakob/dev/dotnet/runtime/src/coreclr/pal/inc/unixasmmacrosamd64.inc:839
00007FFC07C31DE0 00007F10EEF423DB libcoreclr.so!CallDescrWorkerWithHandler(CallDescrData*, int) + 331 at /home/jakob/dev/dotnet/runtime/src/coreclr/pal/inc/pal.h:4856
00007FFC07C31E30 00007F10EEF4270C libcoreclr.so!DispatchCallSimple(unsigned long*, unsigned int, unsigned long, unsigned int) + 204 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/callhelpers.cpp:218
00007FFC07C31EB0 00007F10EEF7F05D libcoreclr.so!BaseAssemblySpec::Init(SString&) + 173 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/coreassemblyspec.cpp:0
00007FFC07C31F20 00007F10EF0B6AB0 libcoreclr.so!LoadDomainAssembly(SString*, Assembly*, AssemblyBinder*, int) + 192 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/typeparse.cpp:1411
00007FFC07C32250 00007F10EF0B544F libcoreclr.so!TypeName::GetTypeWorker(int, int, Assembly*, int, int, Assembly*, AssemblyBinder*, OBJECTREF*) + 351 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/typeparse.cpp:1109
00007FFC07C327C0 00007F10EF0B6105 libcoreclr.so!TypeName::GetTypeManaged(char16_t const*, DomainAssembly*, int, int, int, Assembly*, OBJECTREF*, AssemblyBinder*) + 373 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/typeparse.cpp:939
00007FFC07C32CD0 00007F10EEEA6276 libcoreclr.so!PgoManager::getPgoInstrumentationResults(MethodDesc*, unsigned char**, ICorJitInfo::PgoInstrumentationSchema**, unsigned int*, unsigned char**, ICorJitInfo::PgoSource*) + 1542 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/pgo.cpp:0
00007FFC07C33370 00007F10EEE52A6F libcoreclr.so!CEEJitInfo::getPgoInstrumentationResults(CORINFO_METHOD_STRUCT_*, ICorJitInfo::PgoInstrumentationSchema**, unsigned int*, unsigned char**, ICorJitInfo::PgoSource*) + 383 at /home/jakob/dev/dotnet/runtime/src/coreclr/vm/jitinterface.cpp:11920
00007FFC07C33420 00007F106E026DF4 libclrjit.so!Compiler::compInitOptions(JitFlags*) + 1700 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.cpp:2727
00007FFC07C334A0 00007F106E02E186 libclrjit.so!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*) + 278 at /home/jakob/dev/dotnet/runtime/src/coreclr/jit/compiler.hpp:3838
```

Similar problem happens with ``System.Collections.Generic.ValueListBuilder`1[System.Int32].Dispose`` and `System.Globalization.CultureInfo.GetFormat`.

Easiest way seems to be to remove the type handle histogram data for those methods manually, though it would be nice with a cleaner solution for debugging purposes. Maybe we can find a different place to resolve the type handles in the textual PGO input after the process has started.

**Comment by jakobbotsch** [comment]
Finally managed to get a repro with the attached PGO data and
```
COMPlus_PGODataPath=pgo.txt
COMPlus_TieredPGO=0
COMPlus_TieredCompilation=0
COMPlus_ReadPGOData=1
COMPlus_ReadyToRun=0
COMPlus_JitRandomGuardedDevirtualization=10
COMPlus_TC_QuickJitForLoops=1
```

[pgo.zip](https://github.com/dotnet/runtime/files/9132035/pgo.zip)

and also the following patch that I will open a PR for:
```diff
diff --git a/src/coreclr/vm/pgo.cpp b/src/coreclr/vm/pgo.cpp
index bce02bd2a31..6d14ad8873d 100644
--- a/src/coreclr/vm/pgo.cpp
+++ b/src/coreclr/vm/pgo.cpp
@@ -878,7 +878,10 @@ HRESULT PgoManager::getPgoInstrumentationResults(MethodDesc* pMD, BYTE** pAlloca
                                                     if (!th.IsNull())
                                                     {
                                                         MethodDesc* pMD = MemberLoader::FindMethodByName(th.GetMethodTable(), methodString.GetUTF8());
-                                                        newPtr = (INT_PTR)pMD;
+                                                        if (pMD != nullptr && !pMD->IsGenericMethodDefinition())
+                                                        {
+                                                            newPtr = (INT_PTR)pMD;
+                                                        }
                                                     }
                                                 }
                                             }
```

**Comment by jakobbotsch** [comment]
It requires GDV for System.Collections.Immutable.Tests.IndexOfTests:IndexOfTest (hash 2f2443dc). Furthermore, it happens only when we do GDV at IL offsets 0x195 and 0x1a1. Problem repros with only those GDVs and does not repro without them.
