### ISSUE TITLE
System.Threading.Tasks.Dataflow.Tests failure on win-arm64 with ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#72364]
Failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1886357&view=ms.vss-test-web.build-test-results-tab&runId=49269698&resultId=198903&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ef7e255456564e3788/System.Threading.Tasks.Dataflow.Tests/1/console.70428948.log?helixlogtype=result

```scala
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'state')
   at System.Threading.ThreadPool.<>c.<.cctor>b__80_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1367
   at System.Threading.Tasks.Dataflow.Tests.AsyncEnumerable.Repeat(Int32 item, Int32 count)+MoveNext() in /_/src/libraries/System.Threading.Tasks.Dataflow/tests/Dataflow/DataflowTestHelper.IAsyncEnumerable.cs:line 22
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 294
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 294
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 341
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 984
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
```

**Comment by jakobbotsch** [comment]
Have had no luck reproing this and don't see any more occurrences with this same error. Also seems unlikely to be JIT related since it is nopgo (I did not notice that when I changed labels). I'll close it and we can see if it happens again.
