### ISSUE TITLE
JsonConverter<IPAddress> fails to work

### ISSUE THREAD

**Issue by cklogs** [dotnet/runtime#72393]
### Description

A custom JsonConverter<IPAddress> fails to (1) load and (2) serialize data.

### Reproduction Steps

1. Create IpAddressConverter
```c#
public class IpAddressConverter : JsonConverter<IPAddress> {
	public override bool CanConvert(Type typeToConvert) {
		return typeToConvert.IsAssignableFrom(typeof(IPAddress));
	}

	public override IPAddress Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) {
		var token = reader.GetString();

		if (reader.TokenType != JsonTokenType.String || string.IsNullOrEmpty(token)) {
			return null;
		}

		return IPAddress.Parse(token);
	}

	public override void Write(Utf8JsonWriter writer, IPAddress value, JsonSerializerOptions options) {
		var ipAddressString = string.Empty;

		if (value != null) {
			ipAddressString = value.ToString();
		}

		writer.WriteStringValue(ipAddressString);
	}
}
```
2. Add IpAddressConverter to base converters config in Startup.cs
```c#
services.AddMvc()
	.AddJsonOptions(options => {
		// other settings omitted
		options.JsonSerializerOptions.Converters.Add(new IpAddressConverter());
	});
```
3.  Return from asp.net controller a DTO with an IPAddress member:
```c#
public class MyDto {
	[JsonPropertyName("ipAddress")]
	public IPAddress IpAddress { get; set; }
}
```
4.  Try calling the endpoint from point 3, exception is thrown. Message has been anonymized slightly.
```
System.InvalidCastException: Unable to cast object of type 'MyNameSpace.IpAddressConverter' to type 'System.Text.Json.Serialization.JsonConverter`1[System.Object]'.
   at System.Text.Json.Serialization.JsonCollectionConverter`2.GetElementConverter(WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableConverter`1.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
```

### Expected behavior

JsonConverter for concrete type IPAddress should work.

### Actual behavior

Throws exception.

**Comment by jeffdahl** [comment]
I am also experiencing this with .NET 6.

**Comment by danmoseley** [comment]
Reopening due to comment above.
Same on .NET 7?

**Comment by eiriktsarpalis** [comment]
@jeffdahl could you please share a minimal reproduction?
