### ISSUE TITLE
Test failure System.SpanTests.ReadOnlySpanTests.TestMatchTwo_Char

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72427]
Run: [runtime-coreclr libraries-jitstress 20220718.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1886889&view=ms.vss-test-web.build-test-results-tab&runId=49276258&paneView=debug&resultId=165205)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.SpanTests.ReadOnlySpanTests.TestMatchTwo_Char

```
**Error message:**
```
Assert.Equal() Failure
Expected: 26
Actual:   4


Stack trace
   at System.SpanTests.ReadOnlySpanTests.TestMatchTwo_Char() in /_/src/libraries/System.Memory/tests/ReadOnlySpan/IndexOfAny.char.cs:line 120
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by danmoseley** [comment]
@BruceForstall I wonder whether this might be a case where a Jit bug has been exposed.

**Comment by BruceForstall** [comment]
> @BruceForstall I wonder whether this might be a case where a Jit bug has been exposed.

Looks like @jakobbotsch just assigned himself, so we'll find out.

**Comment by shimingsg** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220803.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1920081&view=ms.vss-test-web.build-test-results-tab&runId=49735324&resultId=133395&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open

- System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64Int64SumTest
```

**Error message:**
```
Assert.Equal() Failure
Expected: 1
Actual:   380606017560370616


Stack trace
   at System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64Int64SumTest() in /_/src/libraries/System.Runtime.Intrinsics/tests/Vectors/Vector64Tests.cs:line 3777
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by jakobbotsch** [comment]
I cannot repro this and we haven't seen it in libraries-jitstress since 7/18/2022, so I will just close it and see if we see it again.
