### ISSUE TITLE
Test failure profiler/elt/slowpatheltleave/slowpatheltleave.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72420]
Run: [runtime-coreclr r2r-extra 20220717.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1886658&view=ms.vss-test-web.build-test-results-tab&runId=49275082&paneView=debug&resultId=100026)

Failed test:
```
R2R Linux arm Checked gcstress0xc @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- profiler/elt/slowpatheltleave/slowpatheltleave.sh

```
**Error message:**
```
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/slowpatheltleave.sh: line 256: -r:/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/IL-CG2/*.dll: No such file or directory
Process terminated. Assertion failed.
at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable1.ConfiguredValueTaskAwaiter.System.Runtime.CompilerServices.IStateMachineBoxAwareAwaiter.AwaitUnsafeOnCompleted(IAsyncStateMachineBox box) at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AwaitUnsafeOnCompleted[TAwaiter](TAwaiter& awaiter, IAsyncStateMachineBox box)
at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory1 destination, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 307 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory1 destination, CancellationToken cancellationToken)
at System.IO.Pipes.PipeStream.ReadAsync(Memory1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 102 at System.Diagnostics.AsyncStreamReader.ReadBufferAsync() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 95 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at System.Diagnostics.AsyncStreamReader.ReadBufferAsync() at System.Threading.Tasks.Task1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/slowpatheltleave.sh: line 389:   339 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.elt/slowpatheltleave/slowpatheltleave.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/IL-CG2/common.dll
06:21:53
Response file: /root/helix/work/workitem/e/profiler/elt/slowpatheltleave/common.dll.rsp
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/IL-CG2/common.dll
-o:/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/common.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/common.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/profiler/elt/slowpatheltleave/common.dll
06:21:57
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
06:21:57
Response file: /root/helix/work/workitem/e/profiler/elt/slowpatheltleave/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/root/helix/work/workitem/e/profiler/elt/slowpatheltleave/Microsoft.Diagnostics.NETCore.Client.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running Cros


Stack trace
   at profiler_elt._slowpatheltleave_slowpatheltleave_._slowpatheltleave_slowpatheltleave_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment]
Dup of #69976
