### ISSUE TITLE
STJ source generator fails when two JsonSerializerContext derived types have same name in project

### ISSUE THREAD

**Issue by ithline** [dotnet/runtime#72671]
### Description

System.Text.Json source generator fails to generate output when two or more classes derived from `JsonSerializerContext` share the same name, even though their full name is different.

### Reproduction Steps

Declare two partial classes with nested `JsonSerializerContext` derived types with same name.

```C#
public partial class ModelA
{
    [JsonSerializable(typeof(ModelA))]
    private partial class SerializerContext : JsonSerializerContext
    {
    }
}

public partial class ModelB
{
    [JsonSerializable(typeof(ModelB))]
    private partial class SerializerContext : JsonSerializerContext
    {
    }
}

```

### Expected behavior

Generator creates code for both types.

### Actual behavior

Generator fails with the following message in visual studio

`Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'SerializerContext.g.cs' of the added source file must be unique within a generator.
Parameter name: hintName'
Generator threw the following exception:
'System.ArgumentException: The hintName 'SerializerContext.g.cs' of the added source file must be unique within a generator.
Parameter name: hintName
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at System.Text.Json.SourceGeneration.JsonSourceGenerator.Emitter.AddSource(String fileName, String source, Boolean isRootContextDef)
   at System.Text.Json.SourceGeneration.JsonSourceGenerator.Emitter.Emit()
   at System.Text.Json.SourceGeneration.JsonSourceGenerator.Execute(Compilation compilation, ImmutableArray``1 contextClasses, SourceProductionContext sourceProductionContext)
   at System.Text.Json.SourceGeneration.JsonSourceGenerator.<Initialize>b__2_3(SourceProductionContext spc, ValueTuple``2 source)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0``2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)'.`

### Known Workarounds

Rename serializer context types that both have different names.

**Comment by eiriktsarpalis** [comment]
I don't think we should be incorporating the type's full name in the generated source file by default, since that would deviate from established naming conventions when authoring partial classes. We might want to investigate if the `hintName` parameter in Roslyn's `SourceProductionContext` supports path names (i.e. `Path/To/Namespace/SerializerContext.g.cs`) but that should only kick in if duplicates are detected.

In the meantime, the suggested workaround would be to use unique context names or refactor into two separate projects.

**Comment by ithline** [comment]
Well name of the nested class is `ModelA+SerializerContext`, I don't see why that couldn't be used as name of the generated source file (replacing `+` with `.`)?

Logging generator does not have this problem as it generates all it's output into single file, maybe this could be another long-term solution.

**Comment by eiriktsarpalis** [comment]
> Well name of the nested class is ModelA+SerializerContext, I don't see why that couldn't be used as name of the generated source file (replacing + with .)?

Perhaps, but that would not address conflicts located in different namespaces.

> Logging generator does not have this problem as it generates all it's output into single file, maybe this could be another long-term solution.

That wouldn't be compatible with the `JsonSerializerContext` model, unfortunately.

**Comment by martincostello** [comment]
Just hit this myself in a test project where I was using nested private classes in different test classes to create a `JsonSerializerContext` to use with specific existing test code. Even though the classes being tested and serialized have different names, having the same context class name causes compilation to fail as they both try to generate the same source for `string`.

```csharp
public static partial class A
{
    private class TestClassA
    {
        public string Value { get; set; }
    }

    [JsonSerializable(typeof(TestClassA))]
    private sealed partial class TestJsonSerializerContext : JsonSerializerContext
    {
    }
}

public static partial class B
{
    private class TestClassB
    {
        public string Value { get; set; }
    }

    [JsonSerializable(typeof(TestClassB))]
    private sealed partial class TestJsonSerializerContext : JsonSerializerContext
    {
    }
}
```

```text
Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'TestJsonSerializerContext.String.g.cs' of the added source file must be unique within a generator.
Parameter name: hintName'.
System.ArgumentException: The hintName 'TestJsonSerializerContext.String.g.cs' of the added source file must be unique within a generator.
Parameter name: hintName
   at Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(String hintName, SourceText source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
```

**Comment by eiriktsarpalis** [comment]
We should try to improve the naming scheme for generated source files so that conflicts like this are less likely.

**Comment by ilonatommy** [comment]
Reported recently in VS as breaking hot reload: [VS community issue](https://developercommunity.visualstudio.com/t/Blazor-WASM-HotReload-Unexpected-error/10940326).
