### ISSUE TITLE
Test failure System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72825]
Run: [runtime-coreclr libraries-jitstressregs 20220725.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1902209&view=ms.vss-test-web.build-test-results-tab&runId=49481618&paneView=debug&resultId=186492)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs0x1000-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs0x10-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs8-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs3-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)

net7.0-Linux-Release-arm-CoreCLR_checked-jitstressregs4-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,A/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,9999999/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,59/0,J365/25\", dayNumber: 0, monthNumber: 0, shouldSucceed: False)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,58/0,J365/25\", dayNumber: 28, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,31/0,J365/25\", dayNumber: 1, monthNumber: 2, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,30/0,J365/25\", dayNumber: 31, monthNumber: 1, shouldSucceed: True)
- System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: \"<+00>0<+01>,0/0,J365/25\", dayNumber: 1, monthNumber: 1, shouldSucceed: True)
```

**Error message:**
```
Exit code was 134 but it should have been 42
Expected: True
Actual:   False


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 239
   at System.Tests.TimeZoneInfoTests.NJulianRuleTest(String posixRule, Int32 dayNumber, Int32 monthNumber, Boolean shouldSucceed) in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 2525
   at InvokeStub_TimeZoneInfoTests.NJulianRuleTest(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by danmoseley** [comment]
due to assertion failure:
```
dotnet: tzfile.c:489: __tzfile_read: Assertion `num_types == 1' failed.
```

**Comment by danmoseley** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
> guess: the tzfile on this configuration is slightly wrong, and this just happens to be using chk bits including a chk glibc?

For sure it is using the chk build of glibc. I am not sure if this is intended. Would be good if someone can confirm. 

In same time, I am seeing the assert is fired from https://sources.debian.org/src/glibc/2.28-10/time/tzfile.c/#L440. I'll try to look if I can modify the tz file we generate to avoid this assert.

**Comment by danmoseley** [comment]
@BruceForstall is it expected that you use the chk glibc in these runs -- I assume so, because you want asserts for memory misuse, etc.

**Comment by tarekgh** [comment]
@VincentBu you have the failure with the pipelines [runtime-coreclr libraries-jitstressregs 20220725.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1902209&view=ms.vss-test-web.build-test-results-tab&runId=49481618&paneView=debug&resultId=186492) but when looking at the PR https://github.com/dotnet/runtime/pull/72522 I am not seeing this pipeline in the CI run. any idea about that?

**Comment by VincentBu** [comment]
> @VincentBu  but when looking at the PR #72522 I am not seeing this pipeline in the CI run. Any idea about that?

I am not sure. I just check the pipeline [runtime-coreclr libraries-jitstressregs](https://dev.azure.com/dnceng/public/_build?definitionId=668&_a=summary). There are 2 failed runs this months, the one is [runtime-coreclr libraries-jitstressregs 20220725.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1902209&view=ms.vss-test-web.build-test-results-tab&runId=49481618&paneView=debug&resultId=186492) and the other is [runtime-coreclr libraries-jitstressregs 20220724.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1900130&view=results). According to the summary of [20220724.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1900130&view=results), it has nothing to do with #72522
