### ISSUE TITLE
Test failure JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72822]
Run: [runtime-coreclr outerloop 20220725.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481962&resultId=103627&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\TypeTestFolding\\TypeTestFolding.cmd

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 OSX x64 Checked @ OSX.1200.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open

- JIT/opt/ValueNumbering/TypeTestFolding/TypeTestFolding.sh
```

**Error message:**
```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
at ILCompiler.DependencyAnalysis.ReadyToRun.SignatureBuilder.EmitTypeSignature(TypeDesc typeDesc, SignatureContext context) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/SignatureBuilder.cs:line 329
at ILCompiler.DependencyAnalysis.ReadyToRun.NewArrayFixupSignature.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/NewArrayFixupSignature.cs:line 35
at ILCompiler.DependencyAnalysis.ReadyToRun.ImportSectionNode.MaterializeSignature(NodeFactory r2rFactory) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionNode.cs:line 61
at ILCompiler.DependencyAnalysis.ReadyToRun.ImportSectionsTableNode.MaterializeSignature() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ImportSectionsTableNode.cs:line 27
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.ComputeLastSetOfModuleIndices() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ManifestMetadataTableNode.cs:line 277
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestMetadataTableNode.GetManifestAssemblyMvidTableData() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ManifestMetadataTableNode.cs:line 324
at ILCompiler.DependencyAnalysis.ReadyToRun.ManifestAssemblyMvidHeaderNode.GetData(NodeFactory factory, Boolean relocsOnly) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/ManifestAssemblyMvidHeaderNode.cs:line 58
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable() in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/CodeGen/ReadyToRunObjectWriter.cs:line 256
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 354
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 882
at ILCompiler.Program.Run(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 583
at ILCompiler.Program.Main(String[] args) in //src/coreclr/tools/aot/crossgen2/Program.cs:line 1159

Return code:      1
Raw output file:      D:\h\w\A58708E6\w\B03A09BA\uploads\Reports\JIT.opt\ValueNumbering\TypeTestFolding\TypeTestFolding.output.txt
Raw output:
BEGIN EXECUTION
TypeTestFolding.dll
1 file(s) copied.
15:21:46.60
Response file: D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll.rsp
D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\IL-CG2\TypeTestFolding.dll
-o:D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A58708E6\p\System..dll
-r:D:\h\w\A58708E6\p\Microsoft..dll
-r:D:\h\w\A58708E6\p\mscorlib.dll
-r:D:\h\w\A58708E6\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A58708E6\p\crossgen2\crossgen2.dll" @"D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll.rsp"   -r:D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.dll
15:21:55.44
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A58708E6\p
D:\h\w\A58708E6\w\B03A09BA\e\JIT\opt\ValueNumbering\TypeTestFolding\TypeTestFolding.cmd
Expe


Stack trace
   at JIT_opt._ValueNumbering_TypeTestFolding_TypeTestFolding_._ValueNumbering_TypeTestFolding_TypeTestFolding_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by VincentBu** [comment]
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-07-25T20:52:15.265Z | osx.1200.amd64.open | x64 | [runtime-coreclr outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49482968&resultId=109460&paneView=debug)
2022-07-25T20:52:13.999Z | osx.1200.amd64.open | x64 | [runtime-coreclr outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49482946&resultId=109423&paneView=debug)
2022-07-25T20:52:13.999Z | osx.1200.amd64.open | x64 | [runtime-coreclr outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49482946&resultId=109423&paneView=debug)
2022-07-25T20:07:01.091Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481134&resultId=108691&paneView=debug)
2022-07-25T20:06:59.956Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481136&resultId=107994&paneView=debug)
2022-07-25T20:06:23.07Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481106&resultId=108845&paneView=debug)
2022-07-25T20:06:21.945Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481108&resultId=108076&paneView=debug)
2022-07-25T20:06:15.369Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481096&resultId=106045&paneView=debug)
2022-07-25T20:06:14.04Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481094&resultId=108106&paneView=debug)
2022-07-25T20:06:11.362Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr outerloop   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481082&resultId=105813&paneView=debug)
2022-07-25T20:06:10.249Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr outerloop   Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=1902031&view=ms.vss-test-web.build-test-results-tab&runId=49481080&resultId=106064&paneView=debug)

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/pull/72136 ? cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
The test uses an array of function pointers, perhaps that's a missing case in crossgen2?
