### ISSUE TITLE
Failure in HostActivation.Tests.MultiArchInstallLocation.EnvironmentVariable_DotnetRootPathDoesNotExist

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#72891]
```
❌ HostActivation.Tests.MultiArchInstallLocation.EnvironmentVariable_DotnetRootPathDoesNotExist [[Details]](https://dev.azure.com/dnceng//public/_build/results?buildId=1904713&view=ms.vss-test-web.build-test-results-tab&runId=49518260&resultId=100134&paneView=debug) [[0.22% failure rate]](https://dev.azure.com/dnceng//public/_build/results?buildId=1904713&view=ms.vss-test-web.build-test-results-tab&runId=49518260&resultId=100134&paneView=history)
Exception Message
System.IO.IOException : The process cannot access the file 'D:\a\_work\1\s\artifacts\tests\Debug\ha\nsnwdgz2.lez\PortableApp\bin\PortableApp.exe' because it is being used by another process.
CallStack
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Microsoft.DotNet.CoreSetup.Test.TestFileBackup.CopyOverDirectory(String source, String destination) in /_/src/installer/tests/TestUtils/TestFileBackup.cs:line 113
   at Microsoft.DotNet.CoreSetup.Test.TestFileBackup.Dispose() in /_/src/installer/tests/TestUtils/TestFileBackup.cs:line 73
   at HostActivation.Tests.MultiArchInstallLocation.EnvironmentVariable_DotnetRootPathDoesNotExist() in /_/src/installer/tests/HostActivation.Tests/MultiArchInstallLocation.cs:line 122
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Failing Configuration
Installer-coreclr-windows_x86-Debug
```
failed in https://github.com/dotnet/runtime/pull/72874

**Comment by agocke** [comment]
We haven't changed anything here and it's only failed once so far. I'll reprioritize if it happens again.
