### ISSUE TITLE
[wasm][debugger] HotReload test failures

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#72946]
```
Error: System.NullReferenceException: Object reference not set to an instance of an object.
    at TestHotReloadUsingSDB.RunMethod(String className, String methodName) in /_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs:line 990
    at mo (http://localhost:9400/dotnet.js:3:51791)
    at wo (http://localhost:9400/dotnet.js:3:52354)
    at _debugger_test__TestHotReloadUsingSDB_RunMethod (https://mono-wasm.invalid/_debugger_test__TestHotReloadUsingSDB_RunMethod:23:5)
    at invoke_static_method (http://localhost:9400/debugger-driver.html:27:11)
    at <anonymous>:1:32
```
seen on unrelated PR 

[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72939-merge-20226d49a4f9475ab0/chrome-DebuggerTests/1/console.11aa2119.log?helixlogtype=result)

```
[xUnit.net 00:34:34.87]     DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [FAIL]
Expected: DebuggerTests.ExceptionTestsClass.TestUncaughtException.run
Actual:   invoke_static_method
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.AssertEqual(Object expected, Object actual, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1136
   at DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload() in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 251
--- End of stack trace from previous location ---
[xUnit.net 00:42:02.91]     DebuggerTests.HotReloadTests.DebugHotReloadMethodChangedUserBreak [FAIL]
  Failed DebuggerTests.HotReloadTests.DebugHotReloadMethodChangedUserBreak [8 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False

``` 
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72996-merge-ee003a7ed8fe4ce881/chrome-DebuggerTests/1/console.37d2d3d0.log?helixlogtype=result)

```
[xUnit.net 00:40:47.22]     DebuggerTests.HotReloadTests.DebugHotReloadMethodChangedUserBreak [FAIL]
  Failed DebuggerTests.HotReloadTests.DebugHotReloadMethodChangedUserBreak [15 ms]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   False
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.LoadAssemblyAndTestHotReload(String asm_file, String pdb_file, String asm_file_hot_reload, String class_name, String method_name) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1387
   at DebuggerTests.HotReloadTests.DebugHotReloadMethodChangedUserBreak() in /_/src/mono/wasm/debugger/DebuggerTestSuite/HotReloadTests.cs:line 21
```
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72021-merge-f3a7ad6d17da404eb5/chrome-DebuggerTests/1/console.1fd38ae9.log?helixlogtype=result)

**Comment by ilonatommy** [comment]
Head on 0ef117e33e711950b0e6ac41c8fdb87503167e75, all of above are passing (tested in Codespaces).

**Comment by ilonatommy** [comment]
Might be random race as @pavelsavara says it was passing on CI re-run.

**Comment by lewing** [comment]
saw it again on https://github.com/dotnet/runtime/pull/73939 https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73939-merge-646ef37e77d843aaa0/chrome-DebuggerTests/1/console.3ea30947.log?helixlogtype=result

**Comment by lewing** [comment]
```
[xUnit.net 00:36:58.27]     DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [FAIL]
  Failed DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload [1 s]
  Error Message:
   [pause1]

Expected: DebuggerTests.ExceptionTestsClass.TestUncaughtException.run
Actual:   invoke_static_method
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.AssertEqual(Object expected, Object actual, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1184
   at DebuggerTests.ExceptionTests.ExceptionTestUncaughtWithReload() in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 251
--- End of stack trace from previous location ---
[Result: IsOk: True, IsErr: False, Value: {
  "breakpointId": "1:539:8:dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs",
  "locations": [
    {
      "scriptId": "dotnet://26565_1",
      "lineNumber": 542,
      "columnNumber": 8
    }
  ]
}, Error:  ]
[Result: IsOk: True, IsErr: False, Value: {
  "breakpointId": "1:1272:8:dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-test.cs",
  "locations": []
}, Error:  ]
Results File: C:\helix\work\workitem\uploads\xharness-output\logs\testResults.trx
```

**Comment by thaystg** [comment]
Created a new issue to fix this: https://github.com/dotnet/runtime/issues/73957
