### ISSUE TITLE
EmptyHandle.MDStreamVersion always throws ArgumentNullException

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#72943]
### Description

ModuleHandle.EmptyHandle property throws ArgumentNullException for MDStreamVersion member.

### Reproduction Steps

```c#
		Console.WriteLine(ModuleHandle.EmptyHandle.MDStreamVersion);
```

### Expected behavior

The property to better to return value (e.g. -1) for empty instance.

### Actual behavior

```
Unhandled exception. System.ArgumentNullException: Invalid handle.
   at System.ModuleHandle.GetMDStreamVersion(RuntimeModule module)
   at System.ModuleHandle.get_MDStreamVersion()
```

### Regression?

No

**Comment by buyaa-n** [comment]
Moved to future milestone for now, @marek-safar please let us know if it is needs to be fixed in 7.0

**Comment by steveharter** [comment]
Should fix; we shouldn't be throwing when calling this method.
