### ISSUE TITLE
[WINARM][Regression] Fail to run the command – dotnet test --framework net7.0 --arch x64/x86 --diag:log.txt

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#72988]
**Note:**
1.It’s regression issue. It doesn’t repro on dotnet-sdk-7.0.100-preview.7.22358.13.
2.Repro VM: 172.20.30.175.

**Builds info:**
dotnet-runtime-3.1.22-win-x64
dotnet-sdk-6.0.400-win-x64
dotnet-sdk-7.0.100-rc.1.22377.7-win-arm64
dotnet-sdk-7.0.100-rc.1.22377.7-win-x64
dotnet-sdk-7.0.100-rc.1.22377.7-win-x86

**Build Link:**
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-arm64.exe
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe
https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x86.exe
https://aka.ms/dotnet/6.0.4xx/daily/dotnet-sdk-win-x64.exe
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-3.1.22-windows-x64-installer

### Reproduction Steps

Execute the following commands by Powershell:
1.$env:DOTNET_MULTILEVEL_LOOKUP=0
2.ls env:
3.mkdir c:\test
4.cd c:\test
5.dotnet new mstest
6.Update file UnitTest1.cs with
```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections;
using System.Diagnostics;
using System.Text;
 
namespace CreateScenarioForVendors
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            StringBuilder builder = new StringBuilder();
 
            builder.AppendLine();
            builder.AppendLine();
            foreach (DictionaryEntry var in Environment.GetEnvironmentVariables())
            {
                if(var.Key.ToString().StartsWith("DOTNET_"))
                {
                    builder.AppendLine($"{var.Key.ToString()} {var.Value}");
                }
            }
            builder.AppendLine();
            builder.AppendLine();
            builder.AppendLine($"ProcessArchitecture {System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture.ToString()}");
            builder.AppendLine($"Location {typeof(object).Assembly.Location}");
            builder.AppendLine($"Process name {Process.GetCurrentProcess().Modules[0].FileName}");
 
            throw new Exception(builder.ToString());
        }
    }
}
```

Update the <PropertyGroup> </PropertyGroup> in project file in in this way
```
<PropertyGroup>
    <TargetFrameworks>net7.0;netcoreapp3.1</TargetFrameworks>
    <IsPackable>false</IsPackable>
  <LangVersion>latest</LangVersion>
  </PropertyGroup>
```

7.dotnet build
8.dotnet test --framework net7.0 --arch x64/x86 --diag:log.txt

### Expected behavior

The command should be run normally as following:
![image](https://user-images.githubusercontent.com/87680983/181441045-81e14f2b-683f-4e11-b6e5-5b88e8f67fbf.png)

### Actual behavior

Fail to run the command – dotnet test --framework net7.0 --arch x64/x86 --diag:log.txt
![image](https://user-images.githubusercontent.com/87680983/181441227-303c6bd8-5006-41c3-aa64-e953d20a4d24.png)

--Logs:
```
PS C:\test> dotnet test --framework net7.0  --arch x86 --diag:log.txt
  Determining projects to restore...
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
C:\test\test.csproj : error NU1301: The local source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' doesn't exi
st.
  Failed to restore C:\test\test.csproj (in 598 ms).
```

**Comment by hoyosjs** [comment]
This is not a runtime issue - it looks like the project saw a nuget config with bad info (a path that didn't exist):

```
Starting test execution, please wait...
Logging Vstest Diagnostics in file: E:\mocks\testNuget\mstest\log.txt
A total of 1 test files matched the specified pattern.
  Failed TestMethod1 [40 ms]
  Error Message:
   Test method CreateScenarioForVendors.UnitTest1.TestMethod1 threw exception:
System.Exception:

DOTNET_SKIP_FIRST_TIME_EXPERIENCE 0
DOTNET_MULTILEVEL_LOOKUP 0
DOTNET_HOST_PATH E:\mocks\testNuget\.dotnet\dotnet.exe
DOTNET_ROOT E:\mocks\testNuget\.dotnet\


ProcessArchitecture X64
Location E:\mocks\testNuget\.dotnet\shared\Microsoft.NETCore.App\7.0.0-rc.1.22367.4\System.Private.CoreLib.dll
Process name E:\mocks\testNuget\mstest\bin\Debug\net7.0\win-x64\x86\testhost.exe

  Stack Trace:
      at CreateScenarioForVendors.UnitTest1.TestMethod1() in E:\mocks\testNuget\mstest\UnitTest1.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)


Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 51 ms - mstest.dll (net7.0)
```
