### ISSUE TITLE
[LinuxBionic][CI] `System.Tests.TimeZoneInfoTests.NJulianRuleTest` failing

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#72995]
It is blocking clean staging.

Runs where it was observed:
- [20220728.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1908616&view=ms.vss-test-web.build-test-results-tab)
- [20220727.91](https://dev.azure.com/dnceng/public/_build/results?buildId=1907603&view=ms.vss-test-web.build-test-results-tab)

Failing tests:
```
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,0/0,J365/25", dayNumber: 1, monthNumber: 1, shouldSucceed: True) [FAIL]
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,30/0,J365/25", dayNumber: 31, monthNumber: 1, shouldSucceed: True) [FAIL]
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,31/0,J365/25", dayNumber: 1, monthNumber: 2, shouldSucceed: True) [FAIL]
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,58/0,J365/25", dayNumber: 28, monthNumber: 2, shouldSucceed: True) [FAIL]
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,59/0,J365/25", dayNumber: 0, monthNumber: 0, shouldSucceed: False) [FAIL]
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,9999999/0,J365/25", dayNumber: 0, monthNumber: 0, shouldSucceed: False) [FAIL]
System.Tests.TimeZoneInfoTests.NJulianRuleTest(posixRule: "<+00>0<+01>,A/0,J365/25", dayNumber: 0, monthNumber: 0, shouldSucceed: False) [FAIL]
```

Log:
```
[22:32:57] info: An error occurred running System.Runtime.Tests.sh
[22:32:57] dbug: Exit code: 1
                 Std out:
                   Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
                   Discovered:  System.Runtime.Tests (found 8579 of 8714 test cases)
                   Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 1)
                     System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest [SKIP]
                       Condition(s) not met: "DoesNotSupportIanaNamesConversion"
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.EqualException: Assert.Equal() Failure
                         Expected: 1
                         Actual:   0
                         /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs(2616,0): at System.Tests.TimeZoneInfoTests.<>c.<NJulianRuleTest>b__103_0(String day, String month, String succeed)
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.TimeZoneInfoTests+<>c Void <NJulianRuleTest>b__103_0(System.String, System.String, System.String)
                         
                         Child arguments:
                           1, 1, True
                         
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.EqualException: Assert.Equal() Failure
                         Expected: 1
                         Actual:   0
                         /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs(2616,0): at System.Tests.TimeZoneInfoTests.<>c.<NJulianRuleTest>b__103_0(String day, String month, String succeed)
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.TimeZoneInfoTests+<>c Void <NJulianRuleTest>b__103_0(System.String, System.String, System.String)
                         
                         Child arguments:
                           31, 1, True
                         
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.EqualException: Assert.Equal() Failure
                         Expected: 1
                         Actual:   0
                         /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs(2616,0): at System.Tests.TimeZoneInfoTests.<>c.<NJulianRuleTest>b__103_0(String day, String month, String succeed)
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.TimeZoneInfoTests+<>c Void <NJulianRuleTest>b__103_0(System.String, System.String, System.String)
                         
                         Child arguments:
                           1, 2, True
                         
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.EqualException: Assert.Equal() Failure
                         Expected: 1
                         Actual:   0
                         /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs(2616,0): at System.Tests.TimeZoneInfoTests.<>c.<NJulianRuleTest>b__103_0(String day, String month, String succeed)
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.TimeZoneInfoTests+<>c Void <NJulianRuleTest>b__103_0(System.String, System.String, System.String)
                         
                         Child arguments:
                           28, 2, True

```

**Comment by dakersnar** [comment]
@tarekgh any idea what might be causing this?

**Comment by tarekgh** [comment]
I am seeing `ubuntu.1804.amd64.android.29.open.rt`, is this run specific to Android? I am asking because this test passed CI before with enabling jit stress too. So I am wondering why this is failing there?

**Comment by tarekgh** [comment]
@ilonatommy do you see this failure in where else? I mean I can disable this test for Android platform.

**Comment by tarekgh** [comment]
I opened the PR https://github.com/dotnet/runtime/pull/73030 to disable this test on Android.

**Comment by ilonatommy** [comment]
@tarekgh, thank you, disabling till fix is found is fine. The failure can be seen in all runtime-staging jobs. They just don't mark the failure on red, it's kind of hidden - you need to open the job to see it.

**Comment by tarekgh** [comment]
>  disabling till fix is found is fine. The failure can be seen in all runtime-staging jobs. They just don't mark the failure on red, it's kind of hidden - you need to open the job to see it.

Yes, that is what I discovered yesterday :-( this is very confusing. @dotnet/dnceng any idea why doesn't fail the staging leg when any test fails there? As you see, this causes more work for us to track and fix new issues while this can be easily done in the original PR that is failed inside the staging leg and not reported as a failure.

**Comment by MattGal** [comment]
>  any idea why doesn't fail the staging leg when any test fails there?  

In almost any case other than "new very serious Azure DevOps bug is found" that'd be a YAML authoring error, but I'll take a quick stab and see if I can be helpful here.

**Comment by MattGal** [comment]
@tarekgh Looks like a property named 'shouldContinueOnError' gets passed to https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/helix.yml#L33 and makes it decide to do this behavior.  This is to make known-flaky tests that are expected to fail just make the build seem to have warnings.   Not sure why this helps since it's just turning the red circle yellow but it does seem to be intentional for this staging pipeline.

**Comment by tarekgh** [comment]
Thanks @MattGal this is helpful as always :-)

CC @dotnet/area-infrastructure-libraries to comment on that if they have more info.

**Comment by ViktorHofer** [comment]
> Yes, that is what I discovered yesterday :-( this is very confusing. https://github.com/orgs/dotnet/teams/dnceng any idea why doesn't fail the staging leg when any test fails there? As you see, this causes more work for us to track and fix new issues while this can be easily done in the original PR that is failed inside the staging leg and not reported as a failure.

@tarekgh please see https://github.com/dotnet/runtime/pull/45178 and the underlying issue for more details on the existing behavior.

**Comment by tarekgh** [comment]
I am seeing the comment `I just added continueOnError: true for test results, as we should protect build verticals of new platforms from PRs on breaking it and verticals are usually stable on new platforms, so a PR that adds a new platform, should add a vertical that is green from the beginning.` which I cannot comprehend.  but regardless of what is describing this behavior, it does not look right to me as we have evidence causing trouble as shown in this current case.

**Comment by ViktorHofer** [comment]
I'm not defending the existing behavior, I just wanted to point you to the change that has more details on it.

**Comment by tarekgh** [comment]
@ViktorHofer I was not blaming you :-) I appreciate the help you are providing. Should we file issue for this to revisit this decision?

**Comment by ViktorHofer** [comment]
Yes, I think that would make sense.

**Comment by tarekgh** [comment]
I logged https://github.com/dotnet/runtime/issues/73166
