### ISSUE TITLE
QUIC: Ephemeral port and connection already in use

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#73036]
### Description

A set of ASP.NET Core HTTP/3 tests failed. They are both configured to start on 127.0.0.1:0. Because the port is 0 (ephemeral) the listener should start on an unused port assigned by Windows.

Instead, this error is thrown: `System.Net.Quic.QuicException : The local address is already in use.`

### Reproduction Steps

This is one of the failing tests: https://github.com/dotnet/aspnetcore/blob/af7830f81669011ee5e6625d7fbe9f3384aa55a3/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs#L149-L211

The important part is Kestrel is listening on port 0:

```cs
o.Listen(IPAddress.Parse("127.0.0.1"), 0, listenOptions =>
{
    listenOptions.Protocols = Core.HttpProtocols.Http1AndHttp2AndHttp3;
    listenOptions.UseHttps(TestResources.GetTestCertificate());
});
```

Kestrel fails to start and errors because QUIC reports the port is already in use.

Note that these tests have been added to an xunit collection that prevents them from executing in parallel.

### Expected behavior

QUIC listener starts successfully and uses a port number assigned by the OS (Windows in this case)

### Actual behavior

```
System.Net.Quic.QuicException: The local address is already in use.
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.QuicListener.ListenAsync(QuicListenerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.CreateListenerAsync() in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 72
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(EndPoint endpoint, IFeatureCollection features, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/QuicTransportFactory.cs:line 69
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, MultiplexedConnectionDelegate multiplexedConnectionDelegate, ListenOptions listenOptions, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 63
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 225
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 89
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/ListenOptions.cs:line 189
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 206
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 31
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 311
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 231
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostService.cs:line 137
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 141
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.Listen_Http3AndSocketsCoexistOnSameEndpoint_AltSvcDisabled_NoUpgrade() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 245
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
```

### Configuration

Test image where the failures happened: Windows.Amd64.Server2022.Open

**Comment by JamesNK** [comment]
I investigated this some more, and I think the issue happens because Kestrel is listening on HTTP/1.1, HTTP/2 (TCP), and HTTP/3 (UDP).

The ephemeral port is used to bind a TCP socket first, which returns the assigned port. Then that port is reused with QUIC. But there is a chance that the free port for TCP is in use with UDP, causing this error.

This is a Kestrel problem. Will need to think about how to resolve it.
