### ISSUE TITLE
Reflection Invoke crashing on methods with ref void* arguments

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#73100]
## Repro
```csharp
using System.Reflection;

unsafe public class My
{
    static void Main()
    {
        var mi = typeof(My).GetMethod("MyMethod");

        object[] args = new object[1];
        mi.Invoke(null, args);
        Console.WriteLine(args[0] ?? "<null>");
    }

    public static void MyMethod(ref void* ptr)
    {
        ptr = (void*)0x12345678;
    }
}
```
## Actual behavior
```
Unhandled exception. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at My.Main() in C:\repro\Program.cs:line 11
```
This was broken in earlier .NET versions too. However, the exact failure mode is different in .NET 7.
## Expected behavior
"Copy back" wrapped pointer value to `args[0]`, similar to how it is done for other types of `ref` arguments

**Comment by MichalStrehovsky** [comment]
Dup of #10842?

**Comment by jkotas** [comment]
Yes, it looks like a dup, except that the failure mode is different now with changes in reflection internals.

**Comment by steveharter** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/10842
