### ISSUE TITLE
QUIC: Connection timeout has QuicError.InternalError

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#73141]
### Description

I see a timeout error being thrown as an internal error. Shouldn't a connection timeout exception have a QuicError of `QuicError.ConnectionIdle`?

### Reproduction Steps

1. Start Kestrel server with HTTP/3 endpoint
2. Make an HTTP/3 request from a console app and exit app without disposing of HttpClient
3. Kestrel eventually throws an error from `QuicConnection.AcceptInboundStreamAsync`.

### Expected behavior

QuicException.QuicError is ConnectionIdle

### Actual behavior

```
An internal error has occurred. Status code: QUIC_STATUS_CONNECTION_TIMEOUT.
   at System.Net.Quic.QuicConnection.<AcceptInboundStreamAsync>d__32.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.<AcceptAsync>d__18.MoveNext() in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionContext.cs:line 96
```

![image](https://user-images.githubusercontent.com/303201/182075101-dc16b765-36fa-413e-b40b-12f1b94f4803.png)

**Comment by JamesNK** [comment]
Complete logs:

```
[13:02:11.827] dbug: HttpEventSourceListener[0]
      Starting HttpEventSourceListener.
[13:02:11.833] dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
[13:02:12.044] warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'https://localhost:5001/, http://localhost:5000/'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
[13:02:12.085] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#14353717,.ctor,[list][0x222F0FA1230] MsQuicSafeHandle created ->
[13:02:12.089] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicListener#62074597,ListenAsync,[list][0x222F0FA1230] Listener listens on 0.0.0.0:5001 ->
[13:02:12.090] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#21800467,.ctor,[list][0x222F0FA0750] MsQuicSafeHandle created ->
[13:02:12.091] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicListener#61986480,ListenAsync,[list][0x222F0FA0750] Listener listens on [::]:5002 ->
[13:02:12.091] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#21007413,.ctor,[list][0x222F11B6870] MsQuicSafeHandle created ->
[13:02:12.092] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicListener#54848996,ListenAsync,[list][0x222F11B6870] Listener listens on [::]:5003 ->
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://0.0.0.0:5001
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5002
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5003
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5004
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5005
[13:02:12.097] info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5006
[13:02:12.097] dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Http3SampleApp
[13:02:12.097] dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Microsoft.AspNetCore.Watch.BrowserRefresh
[13:02:12.097] dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Microsoft.WebTools.BrowserLink.Net
[13:02:12.097] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[13:02:12.097] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
[13:02:12.097] info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Development\Source\aspnetcore\artifacts\bin\Http3SampleApp\Debug\net7.0\
[13:02:12.097] dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
[13:02:12.514] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
      Connection id "0HMJJFBVDGDM4" received FIN.
[13:02:12.519] dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMJJFBVDGDM4" accepted.
[13:02:12.520] dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMJJFBVDGDM4" started.
[13:02:12.533] dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context) in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Core\src\Middleware\HttpsConnectionMiddleware.cs:line 158
[13:02:12.599] dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HMJJFBVDGDM4" stopped.
[13:02:12.603] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HMJJFBVDGDM4" sending FIN because: "The Socket transport's send loop completed gracefully."
[13:02:27.340] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicListener#61986480,NativeCallback,[list][0x222F0FA0750] Received event NEW_CONNECTION ->
[13:02:27.342] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#46853828,.ctor,[conn][0x222F144C300] MsQuicSafeHandle created ->
[13:02:27.346] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicSafeHandle#53387259,.ctor,[cnfg][0x222F1461D60] MsQuicSafeHandle created ->
[13:02:27.350] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,NativeCallback,[conn][0x222F144C300] Received event IDEAL_PROCESSOR_CHANGED ->
[13:02:27.377] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,NativeCallback,[conn][0x222F144C300] Received event CONNECTED ->
[13:02:27.378] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,HandleEventConnected,[conn][0x222F144C300] Connection connected [::1%1]:5002 -> [::1]:53200 ->
[13:02:27.380] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[1]
      Connection id "0HMJJFC3R92PO" accepted.
[13:02:27.381] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,NativeCallback,[conn][0x222F144C300] Received event PEER_STREAM_STARTED ->
[13:02:27.381] dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMJJFC3R92PO" accepted.
[13:02:27.381] dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMJJFC3R92PO" started.
[13:02:27.381] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#31979881,.ctor,[strm][0x222F14949A0] MsQuicSafeHandle created ->
[13:02:27.381] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#31979881,.ctor,[strm][0x222F14949A0] [conn][0x222F144C300] ref count incremented ->
[13:02:27.382] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#53313535,NativeCallback,[strm][0x222F14949A0] Received event RECEIVE ->
[13:02:27.387] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,NativeCallback,[conn][0x222F144C300] Received event PEER_STREAM_STARTED ->
[13:02:27.387] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#54755275,.ctor,[strm][0x222F14A6410] MsQuicSafeHandle created ->
[13:02:27.387] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#54755275,.ctor,[strm][0x222F14A6410] [conn][0x222F144C300] ref count incremented ->
[13:02:27.387] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,NativeCallback,[strm][0x222F14A6410] Received event RECEIVE ->
[13:02:27.387] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,NativeCallback,[strm][0x222F14A6410] Received event PEER_SEND_SHUTDOWN ->
[13:02:27.396] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#41622463,.ctor,[strm][0x222F145ED40] MsQuicSafeHandle created ->
[13:02:27.396] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#41622463,.ctor,[strm][0x222F145ED40] [conn][0x222F144C300] ref count incremented ->
[13:02:27.396] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,NativeCallback,[strm][0x222F145ED40] Received event START_COMPLETE ->
[13:02:27.416] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[3]
      Stream id "0HMJJFC3R92PO:00000003" type Unidirectional connected.
[13:02:27.423] dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[1]
      00                                                 .
[13:02:27.424] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,WriteAsync,[strm][0x222F145ED40] Stream writing memory of '1' bytes while not completing writes. ->
[13:02:27.424] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,NativeCallback,[strm][0x222F145ED40] Received event SEND_COMPLETE ->
[13:02:27.426] dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[7]
      04 05 06 80 00 80 00                               .......
[13:02:27.426] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,WriteAsync,[strm][0x222F145ED40] Stream writing memory of '7' bytes while not completing writes. ->
[13:02:27.426] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,NativeCallback,[strm][0x222F145ED40] Received event SEND_COMPLETE ->
[13:02:27.428] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,NativeCallback,[strm][0x222F145ED40] Received event IDEAL_SEND_BUFFER_SIZE ->
[13:02:27.429] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#53313535,ReadAsync,[strm][0x222F14949A0] Stream reading into memory of '4096' bytes. ->
[13:02:27.430] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#53313535,ReadAsync,[strm][0x222F14949A0] Stream reading into memory of '4096' bytes. ->
[13:02:27.431] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[2]
      Stream id "0HMJJFC3R92PO:00000002" type Unidirectional accepted.
[13:02:27.432] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,ReadAsync,[strm][0x222F14A6410] Stream reading into memory of '4096' bytes. ->
[13:02:27.432] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[2]
      Stream id "0HMJJFC3R92PO:00000000" type Bidirectional accepted.
[13:02:27.435] dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      ReadAsync[8]
      00 04 05 06 80 01 00 00                            ........
[13:02:27.441] trce: Microsoft.AspNetCore.Server.Kestrel.Http3[46]
      Connection id "0HMJJFC3R92PO" received SETTINGS frame for stream ID 2 with length 5.
[13:02:27.445] dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      ReadAsync[48]
      01 2E 00 00 D1 D7 50 0E  6C 6F 63 61 6C 68 6F 73   ....ÑxP. localhos
      74 3A 35 30 30 32 C1 37  01 61 6C 74 2D 75 73 65   t:5002A7 .alt-use
      64 0E 6C 6F 63 61 6C 68  6F 73 74 3A 35 30 30 32   d.localh ost:5002
[13:02:27.445] trce: Microsoft.AspNetCore.Server.Kestrel.Http3[46]
      Connection id "0HMJJFC3R92PO" received HEADERS frame for stream ID 0 with length 46.
[13:02:27.495] dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      ReadAsync[0]
[13:02:27.528] info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/3 GET https://localhost:5002/ - -
[13:02:27.649] dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HMJJFC3R92PO", Request id "0HMJJFC3R92PO:00000000": started reading request body.
[13:02:27.650] dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HMJJFC3R92PO", Request id "0HMJJFC3R92PO:00000000": done reading request body.
[13:02:27.661] trce: Microsoft.AspNetCore.Server.Kestrel.Http3[47]
      Connection id "0HMJJFC3R92PO" sending HEADERS frame for stream ID 0 with length 53.
[13:02:27.663] trce: Microsoft.AspNetCore.Server.Kestrel.Http3[47]
      Connection id "0HMJJFC3R92PO" sending DATA frame for stream ID 0 with length 20.
[13:02:27.664] dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[77]
      01 35 00 00 D9 56 1D 4D  6F 6E 2C 20 30 31 20 41   .5..UV.M on, 01 A
      75 67 20 32 30 32 32 20  30 35 3A 30 32 3A 32 37   ug 2022  05:02:27
      20 47 4D 54 5F 4D 07 4B  65 73 74 72 65 6C 34 74    GMT_M.K estrel4t
      65 73 74 03 66 6F 6F 00  14 48 65 6C 6C 6F 20 57   est.foo. .Hello W
      6F 72 6C 64 21 20 48 54  54 50 2F 33 20            orld! HT TP/3
[13:02:27.664] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,WriteAsync,[strm][0x222F14A6410] Stream writing memory of '77' bytes while not completing writes. ->
[13:02:27.664] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,NativeCallback,[strm][0x222F14A6410] Received event SEND_COMPLETE ->
[13:02:27.667] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/3 GET https://localhost:5002/ - - - 200 - - 140.3278ms
[13:02:27.669] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[10]
      Stream id "0HMJJFC3R92PO:00000000" shutting down writes because: "The QUIC transport's send loop completed gracefully.".
[13:02:27.669] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,NativeCallback,[strm][0x222F14A6410] Received event SEND_SHUTDOWN_COMPLETE ->
[13:02:27.670] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#20017603,NativeCallback,[strm][0x222F14A6410] Received event SHUTDOWN_COMPLETE ->
[13:02:27.671] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#54755275,ReleaseHandle,[strm][0x222F14A6410] MsQuicSafeHandle released ->
[13:02:27.671] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#54755275,ReleaseHandle,[strm][0x222F14A6410] [conn][0x222F144C300] ref count decremented ->
[13:02:43.683] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,NativeCallback,[conn][0x222F144C300] Received event SHUTDOWN_INITIATED_BY_TRANSPORT ->
[13:02:43.684] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#53313535,NativeCallback,[strm][0x222F14949A0] Received event SHUTDOWN_COMPLETE ->
[13:02:43.685] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,NativeCallback,[strm][0x222F145ED40] Received event SEND_SHUTDOWN_COMPLETE ->
[13:02:43.685] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#39037392,NativeCallback,[strm][0x222F145ED40] Received event SHUTDOWN_COMPLETE ->
[13:02:43.685] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#43257534,NativeCallback,[conn][0x222F144C300] Received event SHUTDOWN_COMPLETE ->
[13:02:43.685] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[7]
      Stream id "0HMJJFC3R92PO:00000002" unexpected error.
      System.Net.Quic.QuicException: The connection timed out from inactivity.
         at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
         at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
         at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
         at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
      --- End of stack trace from previous location ---
         at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.DoReceiveAsync() in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 214
[13:02:43.685] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[7]
      Stream id "0HMJJFC3R92PO:00000003" unexpected error.
      System.Net.Quic.QuicException: The connection timed out from inactivity.
         at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
         at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
         at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
         at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.WaitForWritesClosedAsync() in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 188
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.DoSendAsync() in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 394
[13:02:43.689] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[10]
      Stream id "0HMJJFC3R92PO:00000003" shutting down writes because: "The connection timed out from inactivity.".
[13:02:43.689] dbug: Microsoft.AspNetCore.Server.Kestrel.Http3[45]
      Trace id "0HMJJFC3R92PO": HTTP/3 stream error "H3_INTERNAL_ERROR". An abort is being sent to the stream.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: HTTP_CLOSED_CRITICAL_STREAM
Process terminated. Assertion failed.
Unexpected exception in QuicConnectionContext.AcceptAsync: System.Net.Quic.QuicException: An internal error has occurred. Status code: QUIC_STATUS_CONNECTION_TIMEOUT
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionContext.cs:line 96
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in C:\Development\Source\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionContext.cs:line 96
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[13:02:43.691] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[13]
      Stream id "0HMJJFC3R92PO:00000002" aborted by application with error code 258 because: "HTTP_CLOSED_CRITICAL_STREAM".
```

It looks like the control streams are providing a friendly error message "System.Net.Quic.QuicException: The connection timed out from inactivity." but `AcceptInboundStreamAsync` isn't.

**Comment by rzikm** [comment]
Whoops I forgot to map CONNECTION_TIMEOUT status to QuicError. should be easy to fix.

Also, it looks like the decision we made at https://github.com/dotnet/runtime/pull/72599#discussion_r927462715 bit us sooner than expected, because the connection closes with CONNECTION_TIMEOUT when there is a pending ack for longer than DisconnectTimeoutUs (some 16s by default I think), which may happen when client process exits without closing the connection properly. cc: @ManickaP.
