### ISSUE TITLE
PublishTrimmed=true issue - TypeInitializationException in System.Runtime.Serialization.Formatters

### ISSUE THREAD

**Issue by replaysMike** [dotnet/runtime#733]
When using PublishTrimmed=true for publishing single file applications in .net core, I get a runtime error when performing binary serialization/deserialization in System.Runtime.Serialization.Formatters library.

```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunShowWarnings>true</PublishReadyToRunShowWarnings>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
```
The error during runtime received is:

```
System.TypeInitializationException: The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.Formatters.Binary.Converter..cctor()


   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.get_SystemAssemblyInfo()
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
```

I also tried adding the following to address this error:
```
<ItemGroup>
    <TrimmerRootAssembly Include="System.Runtime.Serialization.Formatters.Binary.Converter" />
</ItemGroup>
```
but that prevents it from publishing as it returns an error: `C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(87,5): error MSB6006: "dotnet.exe" exited with code -1073741819.`

I can disable PublishTrimmed=true for now, but I would think there's a way to address this.

The application is a .Net Core 3 app, which references two multi-target libraries which are `netstandard2.0;net462`

**Comment by danmosemsft** [comment]
@jeffschwMSFT it seems like the first issue here is that ILLink is suffering from an AV.

Is this the right repo for such an issue? I don't see an area label for the linker.

**Comment by replaysMike** [comment]
> What if you use
> ` <TrimmerRootAssembly Include="mscorlib" />`
> ?

This fixed it! For some reason I thought I had tried this originally, but it did solve the problem. Thanks!

**Comment by danmosemsft** [comment]
It should still not AV.

**Comment by jeffschwMSFT** [comment]
Move to mono/linker via https://github.com/mono/linker/issues/853
