### ISSUE TITLE
client.PostAsJsonAsync 方法出现了错误

### ISSUE THREAD

**Issue by ByboyCn** [dotnet/runtime#73360]
我在使用httpClient的client.PostAsJsonAsync方法时,在windows上没有出现任何问题,但是在docker中出现了报错System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. 
json内容如下
```
{"TbLonglinkDevice":{"Id":0,"OrId":"2d3342e725036ba0ba","DeviceJson":{"OriginalId":"2d3342e725036ba0ba","IsLogin":true,"Password":"adsf2sdfacv","DbIsLogin":false,"LastUpdateTime":"2022-08-04T13:26:42.5956824+08:00","Cookie":"eMMYDQAAAAAKmGTu/50A","SyncMsgKey":"CMsCABIECBoQ","SessionKey":"U0d","DeviceToken":"","RsaVersion":333,"DeviceTockenDate":"0001-01-01T00:00:00","Uin":234123,"Username":"12341234","NickName":"44444444","HeadImgUrl":"/0","AutoAuthKey":"CiQIIBIg1jkbFpRLqnUrZ3/Un7498DxKpV9AZ5cMUtq6FiPGS5wS0wIIzQISzQIImE4SwQJ3Kl2pkecsF8zpWPo9LuOhxN38gE=","PskKey":"AAABEQQCpUEob1LOJQPJ+FVFzYE0Y+VAdEVeinvVBaq0ztG5REvyt6kGw==","DeviceName":"IPAD",,"InstallTimeOffset":10001,"VersionBaseband":0,"Pid":"","SoftConfig":"","SoftData":"","ShareKey":"s4UU4bwpDD15QvQ==","ClientSession":"DarS81M539uXWcFYX+E89qg+Q","ServiceSession":"FYVUIQVA","DeviceId":"4927ff861b8347a9682af6d8797c5928","Imei":"4427ff861b8347a9682af6d8797c5928","Version":402659105,"FavSyncKey":""},"Ip":"10.206.219.145","OutIp":"101.206.219.145","Port":7100,"CreateTime":null,"UpdateTime":null,"Remark":null},"logsDetails":{"TriggerTheTime":"初始化","TriggerMethod":"重新链接","TriggerStatus":2,"TriggerReason":"","TriggerIncrement":1,"TriggerTime":"2022-08-04T15:43:57.2341073+08:00","InitStats":2,"LastServerIp":"14.215.158.119","DbLastServerIp":"14.215.158.119"}}
```

**Comment by quan0zhou** [comment]
I think it's a problem with your json itself, it seems to have an extra comma
![image](https://user-images.githubusercontent.com/27860834/182822345-24572c68-49d4-43d8-a553-6f7527823e58.png)

**Comment by eiriktsarpalis** [comment]
@ByboyCn does the above answer your question?

**Comment by danmoseley** [comment]
Should the exception message have contained a line number and offset? Or perhaps I'm just missing it.

**Comment by eiriktsarpalis** [comment]
`JsonException` generally do append line numbers and offsets. When I try to serialize the same payload on my machine.
```
Unhandled exception. System.Text.Json.JsonException: ',' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 651.
 ---> System.Text.Json.JsonReaderException: ',' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 651.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
```
Note the different exception message. The reported exception message is typically thrown in async deserialization when the reader runs out of data:

https://github.com/dotnet/runtime/blob/8daeec27929d15576f034a8743c2c9c524d24609/src/libraries/System.Text.Json/src/System/Text/Json/Reader/Utf8JsonReader.cs#L277-L289

I believe this is expected, but we would need a reproduction to be certain.

**Comment by ByboyCn** [comment]
多谢
