### ISSUE TITLE
Assert in SigPointer::GetTypeHandleThrowing

### ISSUE THREAD

**Issue by davmason** [dotnet/runtime#73503]
### Description

While trying to repro #72578 I ran in to an issue where if I patched a .net 7.0 preview 6 process with locally built binaries it would hit an assert in SigPointer::GetTypeHandleThrowing.

```
Assert failure(PID 25140 [0x00006234], Thread: 31672 [0x7bb8]): ((typ == ELEMENT_TYPE_CLASS) == (loadedType.GetSignatureCorElementType() == ELEMENT_TYPE_CLASS)) || pZapSigContext == NULL || pZapSigContext->externalTokens != ZapSig::NormalTokens

CORECLR! SigPointer::GetTypeHandleThrowing + 0x1911 (0x00007ff9`bde27331)
CORECLR! ZapSig::DecodeType + 0x12F (0x00007ff9`bdeb1bef)
CORECLR! LoadDynamicInfoEntry + 0xE28 (0x00007ff9`bdd2b0f8)
CORECLR! Module::FixupNativeEntry + 0x271 (0x00007ff9`bdc0caa1)
CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(READYTORUN_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x5CF (0x00007ff9`bdeb361f)
CORECLR! ReadyToRunInfo::GetEntryPoint + 0x618 (0x00007ff9`bdeb62c8)
CORECLR! MethodDesc::GetPrecompiledR2RCode + 0xE4 (0x00007ff9`bddfcc64)
CORECLR! MethodDesc::GetPrecompiledCode + 0xD1 (0x00007ff9`bddfc851)
CORECLR! MethodDesc::PrepareILBasedCode + 0x32A (0x00007ff9`bde0002a)
CORECLR! MethodDesc::PrepareCode + 0xE8 (0x00007ff9`bddffca8)
    File: C:\git\runtime\src\coreclr\vm\siginfo.cpp Line: 1517
    Image: C:\work\webapp\bin\Debug\net7.0\win10-x64\publish\webapp.exe

```

Debugging I see that the issue is that a [recent change](https://github.com/dotnet/runtime/pull/71849/files#diff-3bd61bc4ce55b78f710f4e7bdfd3a4e7efb92c53035c6b33a6a2feee1c0ac853) changed `AnsiStringMarshaller` from a struct to a class and the R2R image from Microsoft.AspNetCore.Cryptography.Internal.dll expects a struct and System.Private.CoreLib has it as a class.

### Reproduction Steps

- Install the .net 7.0 p6 sdk
- Create a webapp `dotnet new webapp`
- Publish it with `dotnet publish --self-contained -r win10-x64`
- Build coreclr from main and copy over `xcopy /y /e C:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\* .`
- Run `webapp.exe`

### Expected behavior

Web app runs normally

### Actual behavior

Assert is hit, and if running in release I see strange type system errors

```
C:\work\webapp\bin\Debug\net7.0\win10-x64\publish>webapp.exe
Unhandled exception. System.TypeLoadException: Could not load type 'System.Numerics.IComparisonOperators`2' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.AspNetCore.Http.ParameterBindingMethodCache.TryGetNumberStylesTryGetMethod(Type type, MethodInfo& method, Nullable`1& numberStyles)
   at Microsoft.AspNetCore.Http.ParameterBindingMethodCache.<FindTryParseMethod>g__Finder|15_0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelMetadata.InitializeTypeInformation()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadata..ctor(IModelMetadataProvider provider, ICompositeMetadataDetailsProvider detailsProvider, DefaultMetadataDetails details, DefaultModelBindingMessageProvider modelBindingMessageProvider)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreateModelMetadata(DefaultMetadataDetails entry)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.CreateCacheEntry(ModelMetadataIdentity key)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider.GetMetadataCacheEntryForObjectType()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.DefaultModelMetadataProvider..ctor(ICompositeMetadataDetailsProvider detailsProvider, DefaultModelBindingMessageProvider modelBindingMessageProvider)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.EnsureRazorPagesServices(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.MapRazorPages(IEndpointRouteBuilder endpoints)
   at Program.<Main>$(String[] args) in C:\work\webapp\Program.cs:line 23
```

### Regression?

I have not seen this issue previously when patching, but it may just never have happened to line up with this scenario

### Known Workarounds

Disable R2R

**Comment by jkotas** [comment]
> I see that the issue is that a [recent change](https://github.com/dotnet/runtime/pull/71849/files#diff-3bd61bc4ce55b78f710f4e7bdfd3a4e7efb92c53035c6b33a6a2feee1c0ac853) changed AnsiStringMarshaller from a struct to a class and the R2R image from Microsoft.AspNetCore.Cryptography.Internal.dll expects a struct and System.Private.CoreLib has it as a class.

This is by design. You can see crashes or asserts when you mix and match bits from different previews. 

Preview public surface is not stable and preview to preview changes are generally not compatible. We often change, add or remove API from preview to preview in incompatible ways. R2R nor IL is robust against that.
