### ISSUE TITLE
System.Text.Json.Nodes.Tests.JsonArrayTests.HeterogeneousArray - asserts

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#73538]
Occurrences 4/5-8/7 (incl. PRs) from Runfo in last 120 days:

Day | Run | OS
-- | -- | --
8/6 | Rolling run - [1927956](https://runfo.azurewebsites.net/view/build/?number=1927956) | net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open
8/6 | PR #73515 - [1927732](https://runfo.azurewebsites.net/view/build/?number=1927732) | net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open
8/3 | PR #73214 - [1922072](https://runfo.azurewebsites.net/view/build/?number=1922072) | net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open
7/15 | Rolling run - [1882819](https://runfo.azurewebsites.net/view/build/?number=1882819) | net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open
7/11 | PR #71943 - [1872339](https://runfo.azurewebsites.net/view/build/?number=1872339) | net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open

```
Assert.Equal() Failure
Expected: NaN
Actual:   2.2999999999999998

   at System.Text.Json.Nodes.Tests.JsonArrayTests.HeterogeneousArray() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonNode/JsonArrayTests.cs:line 435
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

**Comment by karelz** [comment]
@lewing looks like Android specific, can you please help route it?

**Comment by akoeplinger** [comment]
The `Expected: NaN` is extremely suspicious here since that is the `expected` value in this assert which should be `2.3`:
https://github.com/dotnet/runtime/blob/c302b7b9af154d17d154dde4ad37e47bc3792ecf/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonNode/JsonArrayTests.cs#L435

We recently did a major change to the x86 floating point handling in https://github.com/dotnet/runtime/pull/65723, there's a good chance this is fixed by that.

Let's keep an eye on it and see if it happens again.

**Comment by akoeplinger** [comment]
I don't see recent failures for this one so it is presumably fixed by https://github.com/dotnet/runtime/pull/65723.

Closing.
