### ISSUE TITLE
[wasm] Regression: Crash on running debugger tests on Codespaces

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73673]
Running debugger tests on codespaces now breaks with:

```
  Error Message:
   System.ArgumentException : {
  "timestamp": 1660098231978.708,
  "exceptionDetails": {
    "exceptionId": 1,
    "text": "Uncaught (in promise)",
    "lineNumber": 2,
    "columnNumber": 64026,
    "scriptId": "6",
    "url": "http://localhost:9400/dotnet.js",
    "exception": {
      "type": "object",
      "subtype": "error",
      "className": "TypeError",
      "description": "TypeError: Failed to fetch\n    at Object._s [as fetch_like] (http://localhost:9400/dotnet.js:3:64027)\n    at Do (http://localhost:9400/dotnet.js:3:51275)\n    at Po (http://localhost:9400/dotnet.js:3:51927)\n    at Uo (http://localhost:9400/dotnet.js:3:52273)\n    at Mo (http://localhost:9400/dotnet.js:3:50662)\n    at ko (http://localhost:9400/dotnet.js:3:50245)\n    at Ec (http://localhost:9400/dotnet.js:5:48267)\n    at http://localhost:9400/dotnet.js:5:46311",
      "objectId": "8367169025981544960.1.1",
      "preview": {
        "type": "object",
        "subtype": "error",
        "description": "TypeError: Failed to fetch\n    at Object._s [as fetch_like] (http://localhost:9400/dotnet.js:3:64027)\n    at Do (http://localhost:9400/dotnet.js:3:51275)\n    at Po (http://localhost:9400/dotnet.js:3:51927)\n    at Uo (http://localhost:9400/dotnet.js:3:52273)\n    at Mo (http://localhost:9400/dotnet.js:3:50662)\n    at ko (http://localhost:9400/dotnet.js:3:50245)\n    at Ec (http://localhost:9400/dotnet.js:5:48267)\n    at http://localhost:9400/dotnet.js:5:46311",
        "overflow": false,
        "properties": [
          {
            "name": "stack",
            "type": "string",
            "value": "TypeError: Failed to fetch\n    at Object._s [as fe…7)\n    at http://localhost:9400/dotnet.js:5:46311"
          },
          {
            "name": "message",
            "type": "string",
            "value": "Failed to fetch"
          }
        ]
      }
    },
    "executionContextId": 1,
    "exceptionMetaData": {
      "requestId": "3089.71"
    }
  },
  "__forMethod": "Runtime.exceptionThrown"
}
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, TimeSpan span) in /workspaces/runtime/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 343
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /workspaces/runtime/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 149
```

.. making codespaces completely unusable for debugger work.
Reverting de03d8a8c84062e04c5c7ad574bd7bb7e58db9a9 fixes it.

```
commit de03d8a8c84062e04c5c7ad574bd7bb7e58db9a9
Author: Pavel Savara <pavel.savara@gmail.com>
Date:   Tue Aug 9 18:54:49 2022 +0200

    [wasm] asset loading for workers (#73484)

    - move asset related logic to separate file`assets.ts`
    - split logging code into separate file `logging.ts`
    - add `dotnet.wasm` and `dotnet-crypto-worker.js` to mono-config.json
    - moved `readSymbolMapFile()` call to `startup.ts`
    - fixed bug in `setup_proxy_console()` which didn't really copy the original `log` and `error` functions of the console and caused recursion on error.
    - moved `init_crypto` after `mono_wasm_load_config` in `mono_wasm_pre_init_essential_async`
    - added new resource type `js-module-crypto` and `js-module-threads`
    - changed the detection of blazor startup sequence to not be disabled by presence of config, but only by config.assets having some assembly in it.

    Co-authored-by: Marek Fišera <mara@neptuo.com>
```

Users could probably run into this too.

**Comment by pavelsavara** [comment]
This is related to throttling and performance of codespaces.
![image](https://user-images.githubusercontent.com/271576/183971832-dfa9dc32-1a16-436c-9c5f-385268cf4d8b.png)
