### ISSUE TITLE
Test failure System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: Asynchronous)

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#73925]
Run: [runtime-coreclr libraries-jitstress 20220814.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1942500&view=ms.vss-test-web.build-test-results-tab&runId=50062636&resultId=137892&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: Asynchronous)
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: None)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: Asynchronous)
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: None)

net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: Asynchronous)
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: None)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: Asynchronous)
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: None)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: Asynchronous)
- System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(options: None)
```
**Error message:**
```
System.IO.IOException : The process cannot access the file '\?\PhysicalDrive0' because it is being used by another process.


Stack trace
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs:line 114
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs:line 47
   at System.IO.Tests.RandomAccess_GetLength.ReturnsActualLengthForDevices(FileOptions options) in /_/src/libraries/System.IO.FileSystem/tests/RandomAccess/GetLength.cs:line 48
   at InvokeStub_RandomAccess_GetLength.ReturnsActualLengthForDevices(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/commit/1ae7c5f816b9910beaea67c45bb3681e8630662d

Cc @virzak

**Comment by virzak** [comment]
Should we catch IOExceoption in the test case and rethrow unless the message contains a string: "because it is being used by another process"

I don't have better ideas and it seems that there are no other test cases for physical drive.

@adamsitnik

**Comment by virzak** [comment]
Ideally, should probably use [AttachVirtualDisk](https://docs.microsoft.com/en-us/windows/win32/api/virtdisk/nf-virtdisk-attachvirtualdisk) function and run all test cases against a virtual drive...
