### ISSUE TITLE
[wasm] Test failures due to trimming errors on `main`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#73932]
[Rolling builds](https://dev.azure.com/dnceng/public/_build/results?buildId=1942952&view=results) failing due to trimming errors like:

```
[22:39:56] fail: [FAIL] DataContractJsonSerializerTests.DCJS_VerifyDateTimeForFormatStringDCJsonSerSettings
[22:39:56] info: System.Runtime.Serialization.SerializationException : No set method for property 'System.DateTime UtcDateTime' in type 'System.Runtime.Serialization.DateTimeOffsetAdapter'.
[22:39:56] info:    at System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(ClassDataContract )
[22:39:56] info:    at System.Runtime.Serialization.Json.JsonClassDataContract.get_JsonFormatReaderDelegate()
[22:39:56] info:    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator , Boolean , DataContractResolver )
[22:39:56] info:    at DataContractJsonSerializerTests.SerializeAndDeserialize[DateTimeOffset](DateTimeOffset value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
[22:39:56] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
[22:39:56] fail: [FAIL] DataContractJsonSerializerTests.DCJS_ClassWithDatetimeOffsetTypeProperty
[22:39:56] info: System.Runtime.Serialization.SerializationException : No set method for property 'System.DateTime UtcDateTime' in type 'System.Runtime.Serialization.DateTimeOffsetAdapter'.
[22:39:56] info:    at System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(ClassDataContract )
[22:39:56] info:    at System.Runtime.Serialization.Json.JsonClassDataContract.get_JsonFormatReaderDelegate()
[22:39:56] info:    at System.Object.ReadTypeWithDateTimeOffsetTypePropertyFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
[22:39:56] info:    at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator , Boolean , DataContractResolver )
[22:39:56] info:    at DataContractJsonSerializerTests.SerializeAndDeserialize[TypeWithDateTimeOffsetTypeProperty](TypeWithDateTimeOffsetTypeProperty value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
[22:39:56] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , Span`1 , BindingFlags )
[22:39:56] info: Finished:    System.Runtime.Serialization.Json.Tests.dll
```

<div style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);"><br><br>

TestName | ConsoleUri
-- | --
~~normal-System.Runtime.Serialization.Json.ReflectionOnly.Tests~~ | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Runtime.Serialization.Json.ReflectionOnly.Tests/1/console.22326ac1.log?helixlogtype=result
~~normal-System.Runtime.Serialization.Json.Tests~~ | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Runtime.Serialization.Json.Tests/1/console.ae864d7d.log?helixlogtype=result
normal-System.Runtime.Serialization.Schema.Tests | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Runtime.Serialization.Schema.Tests/1/console.53a021b1.log?helixlogtype=result
~~normal-System.Runtime.Serialization.Xml.ReflectionOnly.Tests~~ | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Runtime.Serialization.Xml.ReflectionOnly.Tests/1/console.943b0a42.log?helixlogtype=result
~~normal-System.Runtime.Serialization.Xml.Tests~~ | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Runtime.Serialization.Xml.Tests/1/console.76324c76.log?helixlogtype=result
normal-System.Xml.XmlSerializer.ReflectionOnly.Tests | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Xml.XmlSerializer.ReflectionOnly.Tests/1/console.7177f9b5.log?helixlogtype=result
normal-System.Xml.XmlSerializer.Tests | https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1ee9e77bee6d490fac/normal-System.Xml.XmlSerializer.Tests/1/console.a2208202.log?helixlogtype=result

</div>

The trimming related build errors were fixed in https://github.com/dotnet/runtime/commit/7d986fa00cfc93e656e5bc548f244df82c401b59 . These are actual test failures now. I have pushed fixes for some of these to https://github.com/dotnet/runtime/pull/73894 .

cc @eerhardt @stephentoub

**Comment by radical** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/73961 which is referenced in disabled tests.
