### ISSUE TITLE
When I use the IP the remote server refuse connection

### ISSUE THREAD

**Issue by ComptonAlvaro** [dotnet/runtime#74093]
I am trying to connect from a client to the service.

By the moment I run the WPF client in the same computer than the gRPC service, that is hosted in ASP Core.

If in the client I use localhost as address, it works, but when I use the IP I get an error that tells the server refuse the connection.

The ASP is configure in this way:

```c#
builder.Services.AddGrpc();
var app = builder.Build();
app.MapGrpcService<GreeterService>();

app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run();
```

Then client use this code:
```c#
            paramDireccion = @"http://192.168.1.200";
            paramPuerto = 5130;
            var channel = GrpcChannel.ForAddress(paramDireccion + ":" + paramPuerto, new GrpcChannelOptions
            {
                HttpHandler = miHttpHandler
            });

            _client = new Greeter.GreeterClient(channel);
```

I am not using certificates in this case, just the code that is generated when I create a gRPC project, to try to connect first from the same computer and later from a remote computer.

I would like to connect using the IP, because it would be the way that I could connect to the remote server.

Thanks.

**Comment by danmoseley** [comment]
cc @JamesNK in case there is a gRPC specific thing.

**Comment by wfurt** [comment]
get capture with Wireshark. `loopback` will try both `127.0.0.1` and `::!`. It is possible you service is not listening on both address families.

**Comment by wfurt** [comment]
btw you should be able to see listening ports with `netstat`.

**Comment by davidfowl** [comment]
@ComptonAlvaro by default ASP.NET Core will listen on localhost unless otherwise specified.  You can:
- Use configuration to specify the urls. If this is in development, open up launchSettings.json and change localhost to 0.0.0.0 and it should work.
- You can do it in code and pass in the url:

```
app.Run("https://*:5001");
```

**Comment by ComptonAlvaro** [comment]
I tried to use grpcui to see if I could connect and when I try to connect, in the service, I have the following log:

Initial log before I try to call the service:

```
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for GestorOrdenadores.Service.Server.Host.AspCore.Services.GreeterService.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'SayHello' to service 'greet.Greeter'. Method type: Unary, HTTP method: POST, route pattern: '/greet.Greeter/SayHello'.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for Grpc.Reflection.ReflectionServiceImpl.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'ServerReflectionInfo' to service 'grpc.reflection.v1alpha.ServerReflection'. Method type: DuplexStreaming, HTTP method: POST, route pattern: '/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'.
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5001
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly GestorOrdenadores.Service.Server.Host.AspCore
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\desarrollo\proyectos\GestorOrdenadores\GestorOrdenadores.Service.Server.Host.AspCore\bin\Debug\net6.0\
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
```


The log after I try to call from client:


```
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for GestorOrdenadores.Service.Server.Host.AspCore.Services.GreeterService.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'SayHello' to service 'greet.Greeter'. Method type: Unary, HTTP method: POST, route pattern: '/greet.Greeter/SayHello'.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[2]
      Discovering gRPC methods for Grpc.Reflection.ReflectionServiceImpl.
trce: Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder[1]
      Added gRPC method 'ServerReflectionInfo' to service 'grpc.reflection.v1alpha.ServerReflection'. Method type: DuplexStreaming, HTTP method: POST, route pattern: '/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo'.
dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://[::]:5001
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly GestorOrdenadores.Service.Server.Host.AspCore
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\desarrollo\proyectos\GestorOrdenadores\GestorOrdenadores.Service.Server.Host.AspCore\bin\Debug\net6.0\
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMK113BRD4DE" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMK113BRD4DE" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.ComponentModel.Win32Exception (0x8009030E): No hay credenciales disponibles en el paquete de seguridad
         at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
         at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
         at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
         at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HMK113BRD4DE" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HMK113BRD4DE" sending FIN because: "The Socket transport's send loop completed gracefully."
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMK113BRD4DF" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMK113BRD4DF" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
       ---> System.ComponentModel.Win32Exception (0x8009030E): No hay credenciales disponibles en el paquete de seguridad
         at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         --- End of inner exception stack trace ---
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
         at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
         at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
         at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HMK113BRD4DF" stopped.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HMK113BRD4DF" sending FIN because: "The Socket transport's send loop completed gracefully."
```

Some of the messages that it tells is:

"No credentials are available in the security package".

**Comment by ComptonAlvaro** [comment]
I have found this issue: https://github.com/dotnet/runtime/issues/23749.

The tell that a possible solution it is create a first X509Certificate2 from the two files (certificata and key) and then createa another X509Certificate2 exporting the first X509Certificate2.

This works for me:

```
    string miStrCertificado = File.ReadAllText("certificados/server.crt");
    string miStrKey = File.ReadAllText("certificados/server.key");
    X509Certificate2 miCertficadoX509 = X509Certificate2.CreateFromPem(miStrCertificado, miStrKey);

    X509Certificate2 miCertificadoC509v2 = new X509Certificate2(miCertficadoX509.Export(X509ContentType.Pkcs12));
```

But I would like to know if there is some way to create only once the X509Certificate2 from the two files.

**Comment by davidfowl** [comment]
Are you on windows?

**Comment by ComptonAlvaro** [comment]
Yes, my server is windows 11.

**Comment by davidfowl** [comment]
Then yes, windows + SslStream doesn't support ephemeral keys.

**Comment by wfurt** [comment]
This is Windows limitation. It would be nice to perhaps throw better exception but it seems like the current one already led you to the answer.

**Comment by davidfowl** [comment]
@wfurt Can we throw or something to tell people this and can we document it?

cc @IEvangelist

**Comment by wfurt** [comment]
I guess @bartonjs  would probably know if there is way to  tell if the is Ephemeral. I don't know the `SEC_E_NO_CREDENTIALS` error code is only specific to ephemeral keys.

**Comment by davidfowl** [comment]
We answered this question like 3 times in the last week. It would be great if we could throw a better error 😄

**Comment by wfurt** [comment]
I was wondering if we could/should do the `X509Certificate2 miCertificadoC509v2 = new X509Certificate2(miCertficadoX509.Export(X509ContentType.Pkcs12));` automatically behind the scenes. (on Windows).
But making the key persistent has probably security implications....

**Comment by bartonjs** [comment]
That's... probably... OK?

The Windows version of the SslStreamCertificateContext could probably do it, though I can't think of an easy way that we can know to stop doing it if Windows ever adds support.  (Hopefully they'd tell us and then we can add a versioning check, or something)

**Comment by wfurt** [comment]
Isn't there a concern that the key now may be left on disk without user knowing it? Or is the export working 100% on top of memory store?

**Comment by bartonjs** [comment]
True, true.  Since SslStreamCertificateContext isn't IDisposable, and .NET (nee Core) doesn't finalize objects on exit, the manual copy is likely to leave the keyfile on disk forever.

Exception it is.

**Comment by ManickaP** [comment]
Triage: moved to security. This is about user-friendliness. Implementation should be simple.
