### ISSUE TITLE
Test failure System.Transactions.Tests.OleTxTests.GetExportCookie

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74120]
Run: [runtime-coreclr libraries-jitstress 20220817.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1948588&view=ms.vss-test-web.build-test-results-tab&runId=50166098&resultId=184802&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (The operation is not valid for the state of the transaction.) (The following constructor parameters did not have matching fixture data: OleTxFixture fixture)
---- System.Transactions.TransactionException : The operation is not valid for the state of the transaction.
-------- System.Transactions.TransactionManagerCommunicationException : Communication with the underlying transaction manager has failed.
------------ System.Runtime.InteropServices.COMException : The Transaction Manager is not available. (0x8004D01B)
---- The following constructor parameters did not have matching fixture data: OleTxFixture fixture
Stack trace

----- Inner Stack Trace #1 (System.Transactions.TransactionException) -----
   at System.Transactions.TransactionState.EnlistDurable(InternalTransaction tx, Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionState.cs:line 203
   at System.Transactions.Transaction.EnlistDurable(Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Transaction.cs:line 503
   at System.Transactions.Tests.OleTxTests.OleTxFixture..ctor() in /_/src/libraries/System.Transactions.Local/tests/OleTxTests.cs:line 483
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/ConstructorInvoker.cs:line 86
----- Inner Stack Trace -----
   at System.Transactions.Oletx.OletxTransactionManager.ProxyException(COMException comException) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/OletxTransactionManager.cs:line 613
   at System.Transactions.Oletx.DtcTransactionManager.Initialize() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs:line 63
   at System.Transactions.Oletx.DtcTransactionManager.get_ProxyShimFactory() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs:line 79
   at System.Transactions.Oletx.OletxTransactionManager.CreateTransaction(TransactionOptions properties) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/OletxTransactionManager.cs:line 448
   at System.Transactions.TransactionStatePromoted.EnterState(InternalTransaction tx) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionState.cs:line 2172
----- Inner Stack Trace -----
   at System.Transactions.DtcProxyShim.DtcInterfaces.ITransactionImportWhereabouts.GetWhereaboutsSize(UInt32& pcbSize)
   at System.Transactions.DtcProxyShim.OletxHelper.Retry(Action action) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/OletxHelper.cs:line 41
   at System.Transactions.DtcProxyShim.DtcProxyShimFactory.ConnectToProxy(String nodeName, Guid resourceManagerIdentifier, Object managedIdentifier, Boolean& nodeNameMatches, Byte[]& whereabouts, ResourceManagerShim& resourceManagerShim) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/DtcProxyShimFactory.cs:line 87
   at System.Transactions.Oletx.DtcTransactionManager.Initialize() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs:line 38
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220825.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1965939&view=ms.vss-test-web.build-test-results-tab&runId=50438000&resultId=184998&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)

net7.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)

net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open
- System.Transactions.Tests.OleTxTests.GetExportCookie
- System.Transactions.Tests.OleTxTests.Promotion
- System.Transactions.Tests.OleTxTests.TransmitterPropagationToken
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: ForceRollback, vote2: Prepared, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: ForceRollback, expectedOutcome1: Aborted, expectedOutcome2: Aborted, expectedTxStatus: Aborted)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_commit(vote1: Prepared, vote2: Prepared, expectedOutcome1: Committed, expectedOutcome2: Committed, expectedTxStatus: Committed)
- System.Transactions.Tests.OleTxTests.Two_durable_enlistments_rollback
- System.Transactions.Tests.OleTxTests.Recovery
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 2)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 1)
- System.Transactions.Tests.OleTxTests.Volatile_and_durable_enlistments(volatileCount: 0)
```

**Error message:**
```
System.AggregateException : One or more errors occurred. (The operation is not valid for the state of the transaction.) (The following constructor parameters did not have matching fixture data: OleTxFixture fixture)
---- System.Transactions.TransactionException : The operation is not valid for the state of the transaction.
-------- System.Transactions.TransactionManagerCommunicationException : Communication with the underlying transaction manager has failed.
------------ System.Runtime.InteropServices.COMException : The Transaction Manager is not available. (0x8004D01B)
---- The following constructor parameters did not have matching fixture data: OleTxFixture fixture


Stack trace

----- Inner Stack Trace #1 (System.Transactions.TransactionException) -----
   at System.Transactions.TransactionState.EnlistDurable(InternalTransaction tx, Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions, Transaction atomicTransaction) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionState.cs:line 203
   at System.Transactions.Transaction.EnlistDurable(Guid resourceManagerIdentifier, IEnlistmentNotification enlistmentNotification, EnlistmentOptions enlistmentOptions) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Transaction.cs:line 503
   at System.Transactions.Tests.OleTxTests.OleTxFixture..ctor() in /_/src/libraries/System.Transactions.Local/tests/OleTxTests.cs:line 505
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/ConstructorInvoker.cs:line 86
----- Inner Stack Trace -----
   at System.Transactions.Oletx.OletxTransactionManager.ProxyException(COMException comException) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/OletxTransactionManager.cs:line 613
   at System.Transactions.Oletx.DtcTransactionManager.Initialize() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs:line 63
   at System.Transactions.Oletx.DtcTransactionManager.get_ProxyShimFactory() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs:line 79
   at System.Transactions.Oletx.OletxTransactionManager.CreateTransaction(TransactionOptions properties) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/OletxTransactionManager.cs:line 448
   at System.Transactions.TransactionStatePromoted.EnterState(InternalTransaction tx) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionState.cs:line 2172
----- Inner Stack Trace -----
   at System.Transactions.DtcProxyShim.DtcInterfaces.ITransactionImportWhereabouts.GetWhereaboutsSize(UInt32& pcbSize)
   at System.Transactions.DtcProxyShim.OletxHelper.Retry(Action action) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/OletxHelper.cs:line 41
   at System.Transactions.DtcProxyShim.DtcProxyShimFactory.ConnectToProxy(String nodeName, Guid resourceManagerIdentifier, Object managedIdentifier, Boolean& nodeNameMatches, Byte[]& whereabouts, ResourceManagerShim& resourceManagerShim) in /_/src/libraries/System.Transactions.Local/src/System/Transactions/DtcProxyShim/DtcProxyShimFactory.cs:line 87
   at System.Transactions.Oletx.DtcTransactionManager.Initialize() in /_/src/libraries/System.Transactions.Local/src/System/Transactions/Oletx/DtcTransactionManager.cs:line 38
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by roji** [comment]
Submitted #74648 (7.0 backport PR #74649) to add test resiliency against communication failures with the MSDTC (CI flakiness).
