### ISSUE TITLE
Test failure: Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#74130]
osx-arm64 and osx-x64 random JitStress

arm64:
```
+ cat /tmp/helix/working/BC530A2F/w/B91F0A19/u/SetStressModes_jitstress_random_1.sh
#!/usr/bin/env bash
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_JitStress=1b
...
    Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh [FAIL]
      
      Return code:      1
      Raw output file:      /tmp/helix/working/BC530A2F/w/B91F0A19/uploads/Reports/Interop.ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/BC530A2F/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ObjectiveCMarshalAPI.dll ''
      Running Validate_ReferenceTrackingAPIs_InvalidArgs...
      Running Validate_ReferenceTracking_Scenario...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 3
      Actual:   4
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ObjectiveCMarshalAPI.Program.Validate_ReferenceTracking_Scenario()
         at ObjectiveCMarshalAPI.Program.Main(String[] doNotUse)
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
```

x64:
```
+ cat /tmp/helix/working/A7390905/w/BC1F0A12/u/SetStressModes_jitstress_random_1.sh
#!/usr/bin/env bash
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_JitStress=2af
...
    Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh [FAIL]
      
      Return code:      1
      Raw output file:      /tmp/helix/working/A7390905/w/BC1F0A12/uploads/Reports/Interop.ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/A7390905/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ObjectiveCMarshalAPI.dll ''
      Running Validate_ReferenceTrackingAPIs_InvalidArgs...
      Running Validate_ReferenceTracking_Scenario...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 3
      Actual:   4
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ObjectiveCMarshalAPI.Program.Validate_ReferenceTracking_Scenario()
         at ObjectiveCMarshalAPI.Program.Main(String[] doNotUse)
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1950662&view=ms.vss-test-web.build-test-results-tab&runId=50203142&resultId=111992&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

@AaronRobinsonMSFT @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
Reassigned this to @jakobbotsch.

**Comment by jakobbotsch** [comment]
Looks like a test bug, the test has `AllocAndTrackObject<T>` that allocates an object with a finalizer. It calls this several times and then asserts that the finalizers were called, but `AllocAndTrackObject<T>` is not marked as no-inlining, and in stress the JIT inlines one of them and extends the lifetime of the finalizable object.
