### ISSUE TITLE
NegotiateAuthenticationKerberosTest failing on Android

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#74224]
e.g. https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74167-merge-efc9957f72f44228a1/System.Net.Security.Tests.Attempt.2/3/console.60460f2d.log?helixlogtype=result

helix queue windows.10.amd64.android.open

```
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.TrueException: Client authentication failed with Unsupported
                         Expected: True
                         Actual:   False
                         /_/src/libraries/System.Net.Security/tests/FunctionalTests/NegotiateAuthenticationKerberosTest.cs(48,0): at System.Net.Security.Tests.NegotiateAuthenticationKerberosTest.<>c.<Loopback_Success>b__2_0()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Net.Security.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.NegotiateAuthenticationKerberosTest+<>c Void <Loopback_Success>b__2_0()
                         
                         
                       Output:
                         GSSAPI trace:
                         
                     System.Net.Security.Tests.ServerAllowNoEncryptionTest.ServerAllowNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [SKIP]
                       Condition(s) not met: "SupportsNullEncryption"
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.EqualException: Assert.Equal() Failure
                         Expected: ContinueNeeded
                         Actual:   GenericFailure
                         /_/src/libraries/System.Net.Security/tests/FunctionalTests/NegotiateAuthenticationKerberosTest.cs(75,0): at System.Net.Security.Tests.NegotiateAuthenticationKerberosTest.<>c.<Invalid_Token>b__3_0()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Net.Security.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.NegotiateAuthenticationKerberosTest+<>c Void <Invalid_Token>b__3_0()
                         
                         
                       Output:
                         GSSAPI trace:
                         
```

Failing reliably several times a day

**Comment by filipnavara** [comment]
Do you have a link to AzDO for any of the failed run? As stated in https://github.com/dotnet/runtime/pull/74225#issuecomment-1220448471 the conditions should already prevent it from running on Android so this looks like some weird mix-up.

**Comment by rzikm** [comment]
Sorry, should have included a link in the post, edited

**Comment by rzikm** [comment]
I see, I have accidentally commented a part of the query I use which excludes runs from "runtime-staging"... not sure what that is but the failures don't show on checklist on PRs either, so probably false alarm.

**Comment by karelz** [comment]
Likely related to #73343
