### ISSUE TITLE
[tvOS] XmlSerializerTests failing

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#74247]
Failing tests:
- XmlSerializerTests.Xml_ReadOnlyCollection
- XmlSerializerTests.Xml_ImmutableCollections

Likely introduced in #73729
Originaly reported in #74076
Sample test results: https://dev.azure.com/dnceng/public/_build/results?buildId=1948701&view=results

Sample failures:
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)
   at XmlSerializerTests.Xml_ReadOnlyCollection()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```
```
Assert.Contains() Failure
Not found: Parameterless constructor is required for collections and enumerators.
In value:  There is an error in XML document (4, 14). : Specified method is not supported.
   at XmlSerializerTests.Xml_ImmutableCollections(Type type, Object collection, Type createException, Type addException, String expectedXml, String exMsg)
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

**Comment by StephenMolloy** [comment]
I have re-enabled a bunch of serialization tests in PR #118507.
Per these two runs ([1118444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118444), [1118071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118071)), none of these testcases are failing anymore.
