### ISSUE TITLE
[iOS][MacCatalyst] iOS.Simulator.XmlSerializer_Deserialize.Test failing

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#74245]
Originally reported in #74076
Sample test results: https://dev.azure.com/dnceng/public/_build/results?buildId=1948701&view=results

Sample log:
```
[03:51:23] dbug: 2022-08-17 03:51:23.722536-0700 iOS.Simulator.XmlSerializer_Deserialize.Test[5742:876991] Unhandled managed exceptions:
[03:51:23] dbug: There is an error in XML document (0, 0). (System.InvalidOperationException)
[03:51:23] dbug: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
[03:51:23] dbug: at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle)
[03:51:23] dbug: at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
[03:51:23] dbug: at Program.Main(String[] )
[03:51:23] dbug: at Program.<Main>(String[] )
[03:51:23] dbug: 2022-08-17 03:51:23.725951-0700 iOS.Simulator.XmlSerializer_Deserialize.Test[5742:876991] DOTNET.APP_EXIT_CODE: 1
```

**Comment by StephenMolloy** [comment]
I believe these are the same tests called out in #74247

**Comment by StephenMolloy** [comment]
I have re-enabled a bunch of serialization tests in PR #118507.
Per these two runs ([1118444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118444), [1118071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118071)), none of these testcases are failing anymore.
