### ISSUE TITLE
reference binding to null pointer caught by ubsan

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#74284]
### Description

gcc -fsanitize=undefined finds a reference pointer to a NULL pointer.  This kind of thing has cropped up (and been fixed) recently in other places in the code.
```
/mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/gentree.h:4764:46: runtime error: reference binding to null pointer of type 'struct CallArg'
    #0 0x7fbecc9de3ae in CallArgs::CallArgIterator<&CallArg::GetNext>::operator*() const (/mnt/robhenry/dotnet/clang11.a/runtime/artifacts/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0-preview.7.22375.6/libclrjit.so+0x8ad3ae)
    #1 0x7fbeccef366e in Compiler::fgValueNumberHelperCallFunc(GenTreeCall*, VNFunc, ValueNumPair) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/valuenum.cpp:9824
    #2 0x7fbeccef5b1f in Compiler::fgValueNumberHelperCall(GenTreeCall*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/valuenum.cpp:10363
    #3 0x7fbeccef4aad in Compiler::fgValueNumberCall(GenTreeCall*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/valuenum.cpp:9924
    #4 0x7fbecceec5f9 in Compiler::fgValueNumberTree(GenTree*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/valuenum.cpp:8977
    #5 0x7fbeccee0f39 in Compiler::fgValueNumberBlock(BasicBlock*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/valuenum.cpp:7734
    #6 0x7fbeccedf4bd in Compiler::fgValueNumber() /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/valuenum.cpp:7509
    #7 0x7fbeccfd6321 in CompilerPhaseWithStatus::DoPhase() /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/phase.h:141
    #8 0x7fbeccdbd161 in Phase::Run() /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/phase.cpp:61
    #9 0x7fbeccfd640a in DoPhase(Compiler*, Phases, PhaseStatus (Compiler::*)()) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/phase.h:153
    #10 0x7fbeccfbb3ef in Compiler::compCompile(void**, unsigned int*, JitFlags*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:4900
    #11 0x7fbeccfc3bbe in Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:6738
    #12 0x7fbeccfbe704 in operator() /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:5884
    #13 0x7fbeccfc0d50 in Compiler::compCompile(CORINFO_MODULE_STRUCT_*, void**, unsigned int*, JitFlags*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:5903
    #14 0x7fbeccfc6513 in operator() /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:7384
    #15 0x7fbeccfc686c in operator() /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:7409
    #16 0x7fbeccfc6e05 in jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/compiler.cpp:7411
    #17 0x7fbeccfdc425 in CILJit::compileMethod(ICorJitInfo*, CORINFO_METHOD_INFO*, unsigned int, unsigned char**, unsigned int*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/jit/ee_il_dll.cpp:261
    #18 0x7ffff4f56ed4 in invokeCompileMethodHelper(EEJitManager*, CEEInfo*, CORINFO_METHOD_INFO*, CORJIT_FLAGS, unsigned char**, unsigned int*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/jitinterface.cpp:12331
    #19 0x7ffff4f573c7 in invokeCompileMethod(EEJitManager*, CEEInfo*, CORINFO_METHOD_INFO*, CORJIT_FLAGS, unsigned char**, unsigned int*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/jitinterface.cpp:12394
    #20 0x7ffff4f58d16 in UnsafeJitFunction(PrepareCodeConfig*, COR_ILMETHOD_DECODER*, CORJIT_FLAGS, unsigned int*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/jitinterface.cpp:12867
    #21 0x7ffff4a19d0a in MethodDesc::JitCompileCodeLocked(PrepareCodeConfig*, ListLockEntryBase<NativeCodeVersion>*, unsigned int*, CORJIT_FLAGS*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/prestub.cpp:952
    #22 0x7ffff4a194c9 in MethodDesc::JitCompileCodeLockedEventWrapper(PrepareCodeConfig*, ListLockEntryBase<NativeCodeVersion>*) /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/prestub.cpp:823
```

### Reproduction Steps

compile gcc -fsanitize=undefined and run crossgen2(?) and other pieces of code.

### Expected behavior

no runtime errors found by ubsanitized binaries

### Actual behavior

gt a runtime error

### Other information

/cc @aaronrobinson

**Comment by JulieLeeMSFT** [comment]
@AaronRobinsonMSFT, PTAL. Please push out to .NET 8 if needed.

**Comment by danmoseley** [comment]
@RobertHenry6bev I added fences (triple backtick) around your stack so it is easier to read (and does not link to issues in the repo..)
