### ISSUE TITLE
Failure in System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread on Debian 10

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#74388]
❌ System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread [[Console]](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74338-merge-8b265039da4a45779f/System.Runtime.Tests/1/console.5c513ad0.log?helixlogtype=result) [[Details]](https://dev.azure.com/dnceng//public/_build/results?buildId=1959322&view=ms.vss-test-web.build-test-results-tab&runId=50341050&resultId=185272&paneView=debug) [[Artifacts]](https://dev.azure.com/dnceng//public/_build/results?buildId=1959322&view=ms.vss-test-web.build-test-results-tab&runId=50341050&resultId=185272&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab) [[0.01% failure rate]](https://dev.azure.com/dnceng//public/_build/results?buildId=1959322&view=ms.vss-test-
❌ System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(size: 1000)

```
Allocated too much: start: 84649544 end: 84749920 size: 1000
Expected: True
Actual:   False
Stack Trace
   at System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(Int32 size) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 798
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64

```
Debian.10.Amd64.Open

**Comment by mangod9** [comment]
this seems to be a new failure, would be good to determine if some recent change might have affected this.

**Comment by danmoseley** [comment]
There is some slop already in the text, so apparently it's not expected to be totally deterministic?

            Assert.True((end - start) < 5 * size, $"Allocated too much: start: {start} end: {end} size: {size}");

So it would allocate 1K, allow up to 5K but it was 10K

**Comment by karelz** [comment]
Happens on all platforms. Roughly 1x per week.

**Comment by janvorli** [comment]
This doesn't seem to happen anymore and the issue is ancient. Closing
