### ISSUE TITLE
[wasm-mt] System.Runtime.InteropServices.JavaScript.Http.Tests.HttpRequestMessageTest.BlobUri_Marshal_CorrectValues_Browser test fails

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#74409]
A `WasmTestOnBrowser-System.Private.Runtime.InteropServices.JavaScript.Tests` test fails when multi-threading is enabled.

Console output:
```
[14:42:00] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Http.Tests.HttpRequestMessageTest.BlobUri_Marshal_CorrectValues_Browser
[14:42:00] info: System.Runtime.InteropServices.JavaScript.JSException : Error: Assert failed: Unknow converter for type 13 at 2 
[14:42:00] info:     at ho (http://127.0.0.1:33463/dotnet.js:5:35222)
[14:42:00] info:     at Object.ui (http://127.0.0.1:33463/dotnet.js:5:57096)
[14:42:00] info:     at _mono_wasm_bind_js_function (http://127.0.0.1:33463/dotnet.js:14:120525)
[14:42:00] info:     at do_icall (http://127.0.0.1:33463/dotnet.wasm:wasm-function[374]:0x27ee5)
[14:42:00] info:     at do_icall_wrapper (http://127.0.0.1:33463/dotnet.wasm:wasm-function[342]:0x2728f)
[14:42:00] info:     at interp_exec_method (http://127.0.0.1:33463/dotnet.wasm:wasm-function[282]:0x1893e)
[14:42:00] info:     at interp_runtime_invoke (http://127.0.0.1:33463/dotnet.wasm:wasm-function[281]:0x177ee)
[14:42:00] info:     at mono_jit_runtime_invoke (http://127.0.0.1:33463/dotnet.wasm:wasm-function[8284]:0x1affd0)
[14:42:00] info:     at do_runtime_invoke (http://127.0.0.1:33463/dotnet.wasm:wasm-function[2136]:0x91c4d)
[14:42:00] info:     at mono_runtime_invoke_checked (http://127.0.0.1:33463/dotnet.wasm:wasm-function[2134]:0x91bc3)
[14:42:00] info:    at System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindJSFunctionImpl(String functionName, String moduleName, ReadOnlySpan`1 signatures)
[14:42:00] info:    at System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindJSFunction(String functionName, String moduleName, ReadOnlySpan`1 signatures)
[14:42:00] info:    at System.Net.Http.BrowserHttpInterop.AbortResponse(JSObject fetchResponse)
[14:42:00] info:    at System.Net.Http.WasmFetchResponse.Dispose()
[14:42:00] info:    at System.Net.Http.BrowserHttpContent.Dispose(Boolean disposing)
[14:42:00] info:    at System.Net.Http.HttpContent.Dispose()
[14:42:00] info:    at System.Net.Http.HttpResponseMessage.Dispose(Boolean disposing)
[14:42:00] info:    at System.Net.Http.HttpResponseMessage.Dispose()
[14:42:00] info:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
[14:42:00] info:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[14:42:00] info:    at System.Runtime.InteropServices.JavaScript.Http.Tests.HttpRequestMessageTest.BlobUri_Marshal_CorrectValues_Browser()
```

**Comment by pavelsavara** [comment]
![image](https://github.com/dotnet/runtime/assets/271576/3e20116f-0bde-453b-b4b4-f8ce462f7159)

This is fixed now
