### ISSUE TITLE
Test failure GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74631]
Run: [runtime-coreclr outerloop 20220825.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1968348&view=ms.vss-test-web.build-test-results-tab&runId=50474432&resultId=106147&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\AB9B09A4\w\A299098F\uploads\Reports\GC.API\GC\GetTotalPauseDuration\GetTotalPauseDuration.output.txt
Raw output:
BEGIN EXECUTION
GetTotalPauseDuration.dll
1 file(s) copied.
20:25:49.20
Response file: D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll.rsp
D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\IL-CG2\GetTotalPauseDuration.dll
-o:D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\AB9B09A4\p\System..dll
-r:D:\h\w\AB9B09A4\p\Microsoft..dll
-r:D:\h\w\AB9B09A4\p\mscorlib.dll
-r:D:\h\w\AB9B09A4\p\netstandard.dll
-O
" "dotnet" "D:\h\w\AB9B09A4\p\crossgen2\crossgen2.dll" @"D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll.rsp"   -r:D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll
20:25:51.37
"D:\h\w\AB9B09A4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GetTotalPauseDuration.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AB9B09A4\p
D:\h\w\AB9B09A4\w\A299098F\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.cmd
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetTotalPauseDuration_GetTotalPauseDuration_._GC_GetTotalPauseDuration_GetTotalPauseDuration_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by AntonLapounov** [comment]
@cshung Please take a look.

**Comment by cshung** [comment]
I cannot reproduce the bug with a Windows arm64 virtual machine. For now, I added some more instrumentation to the test and see if we can obtain more information for debugging.

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr jitstress 20220831.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1980910&view=ms.vss-test-web.build-test-results-tab&runId=50638754&resultId=106163&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked jitstress1 @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked jitstress1_tiered @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked zapdisable @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked tailcallstress @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked jitstress2_tiered @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked jitminopts @ Windows.10.Arm64v8.Open
- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\B36D0987\w\AD9A094B\uploads\Reports\GC.API\GC\GetTotalPauseDuration\GetTotalPauseDuration.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B36D0987\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GetTotalPauseDuration.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B36D0987\p
D:\h\w\B36D0987\w\AD9A094B\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.cmd
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetTotalPauseDuration_GetTotalPauseDuration_._GC_GetTotalPauseDuration_GetTotalPauseDuration_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jeffschwMSFT** [comment]
@cshung can we disable this test for .NET 7? (it has been consistently failing for over a week)

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr outerloop 20220906.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=6005&view=ms.vss-test-web.build-test-results-tab&runId=113080&resultId=106153&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

coreclr windows arm64 Checked @ Windows.10.Arm64v8.Open

- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\B50A09A9\w\A0B408EB\uploads\Reports\GC.API\GC\GetTotalPauseDuration\GetTotalPauseDuration.output.txt
Raw output:
BEGIN EXECUTION
GetTotalPauseDuration.dll
1 file(s) copied.
14:11:02.91
Response file: D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll.rsp
D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\IL-CG2\GetTotalPauseDuration.dll
-o:D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B50A09A9\p\System..dll
-r:D:\h\w\B50A09A9\p\Microsoft..dll
-r:D:\h\w\B50A09A9\p\mscorlib.dll
-r:D:\h\w\B50A09A9\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B50A09A9\p\crossgen2\crossgen2.dll" @"D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll.rsp"   -r:D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.dll
14:11:04.95
"D:\h\w\B50A09A9\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GetTotalPauseDuration.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B50A09A9\p
D:\h\w\B50A09A9\w\A0B408EB\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.cmd
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetTotalPauseDuration_GetTotalPauseDuration_._GC_GetTotalPauseDuration_GetTotalPauseDuration_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Removing blocking-outerloop since the test has been disabled on arm64

**Comment by AndyAyersMS** [comment]
I don't think the exclusion is working.  I still see this test running and failing.

Eg https://dev.azure.com/dnceng-public/public/_build/results?buildId=11496&view=ms.vss-test-web.build-test-results-tab

**Comment by mangod9** [comment]
hmm. perhaps excluding it via `<ExcludeList Include="$(XunitTestBinBase)/GC/API/GC/GetTotalPauseDuration.csproj">` (notice `csproj`, rather than `*`. @trylek do you happen to know if individual tests can be disabled this way or only wildcards are supported?

**Comment by trylek** [comment]
There are two problems involved:

* The exclusions refer to the generated cmd / sh scripts, not the primary ilproj / csproj files.
* As the scripts are searched in test outputs, the project name emits another directory level.

As a result, I would expect that the right exclusion syntax in this particular case is as follows:

<code>&lt;ExcludeList Include="$(XUnitTestBinBase)/GC/API/GC/GetTotalPauseDuration/GetTotalPauseDuration$(ScriptExt)"&gt;</code>

**Comment by mangod9** [comment]
ah thanks, have updated it in this PR now: https://github.com/dotnet/runtime/pull/75475
