### ISSUE TITLE
firefox-DebuggerTests - TaskCanceledException in random tests

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#74640]
7/27-8/28 -- see [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~30+definition%3Aruntime-extra-platforms+name%3A%22firefox-debuggertests+work+item%22) - mostly TaskCanceledException:

Platform: net7.0-Browser-Release-wasm-Mono_firefox_Release-WasmDebuggerTests-(Ubuntu.1804.Amd64)Ubuntu.1804.Amd64.Open

Day | Run | Details
-- | -- | --
8/27 | **Rolling run** [1972127](https://runfo.azurewebsites.net/view/build/?number=1972127) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-eacd7938aba04b8ebd/firefox-DebuggerTests/1/console.ff74ce69.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.MiscTests.EmptyTypeWithNoLocalsOrParams - TaskCanceledException
8/25 | **Rolling run** [1967637](https://runfo.azurewebsites.net/view/build/?number=1967637) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-63a13bc861b649beb6/firefox-DebuggerTests/1/console.a08d76e3.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.PointerTests.InspectLocalPointersInClasses - TaskCanceledException
8/23 | PR [1962705](https://runfo.azurewebsites.net/view/build/?number=1962705) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74451-merge-2698084e78bc47d0b2/firefox-DebuggerTests/1/console.d6b8582f.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.BreakpointTests.ConditionalBreakpoint2 - TaskCanceledException
8/21 | PR [1957418](https://runfo.azurewebsites.net/view/build/?number=1957418) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74301-merge-d565b4e1e1f047e0b6/firefox-DebuggerTests/1/console.ee415a45.log?%3Fhelixlogtype%3Dresult) - 8x failures - 1x TaskCanceledException, 1x IOException (20x timeout), 6x System.Exception: No 'to' field found
8/17 | PR [1949152](https://runfo.azurewebsites.net/view/build/?number=1949152) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73456-merge-7f157199450d44d4b7/firefox-DebuggerTests/1/console.a2ca7228.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.DateTimeTests.CheckDateTimeLocale - TaskCanceledException
8/10 | PR [1934438](https://runfo.azurewebsites.net/view/build/?number=1934438) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73689-merge-73dc5254c72141d287/firefox-DebuggerTests/1/console.a415b7c8.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.BreakpointTests.ConditionalBreakpoint2 - TaskCanceledException
8/9 | PR [1931857](https://runfo.azurewebsites.net/view/build/?number=1931857) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73489-merge-43bcfbccc9804c929c/firefox-DebuggerTests/1/console.5f2556b1.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.MiscTests.EmptyTypeWithNoLocalsOrParams - TaskCanceledException 
8/8 | PR [1929674](https://runfo.azurewebsites.net/view/build/?number=1929674) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71203-merge-30e9441d49d940b4a9/firefox-DebuggerTests/1/console.8ed1e41e.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.BreakpointTests.ConditionalBreakpointHitTwice - TaskCanceledException 
8/7 | PR [1928901](https://runfo.azurewebsites.net/view/build/?number=1928901) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65723-merge-a9373bbb2ea4473094/firefox-DebuggerTests/1/console.2ff38139.log?%3Fhelixlogtype%3Dresult) - DebuggerTests.DateTimeTests.CheckDateTimeLocale - TaskCanceledException
7/27-8/6 |  | 4 PRs with 5 failures total - no Console logs available

Some failures:

8/25 - **Rolling run** [1967637](https://runfo.azurewebsites.net/view/build/?number=1967637) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-63a13bc861b649beb6/firefox-DebuggerTests/1/console.a08d76e3.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:20:07.20]     DebuggerTests.PointerTests.InspectLocalPointersInClasses(eval_fn: "invoke_static_method_async ('[debugger-test] Debug"..., type: "DebuggerTests.PointerTests", method: "LocalPointersAsync", line_offset: 32, bp_function_name: "DebuggerTests.PointerTests.LocalPointersAsync", use_cfo: False) [FAIL]
  Failed DebuggerTests.PointerTests.InspectLocalPointersInClasses(eval_fn: "invoke_static_method_async ('[debugger-test] Debug"..., type: "DebuggerTests.PointerTests", method: "LocalPointersAsync", line_offset: 32, bp_function_name: "DebuggerTests.PointerTests.LocalPointersAsync", use_cfo: False) [62 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 280
   at DebuggerTests.PointerTests.InspectLocalPointersInClasses(String eval_fn, String type, String method, Int32 line_offset, String bp_function_name, Boolean use_cfo) in /_/src/mono/wasm/debugger/DebuggerTestSuite/PointerTests.cs:line 360
--- End of stack trace from previous location ---
```

#### 8/23 - PR [1962705](https://runfo.azurewebsites.net/view/build/?number=1962705) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74451-merge-2698084e78bc47d0b2/firefox-DebuggerTests/1/console.d6b8582f.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:03:46.16]     DebuggerTests.BreakpointTests.ConditionalBreakpoint2(function_to_call: "invoke_add()", method_to_stop: "IntAdd", condition: "Math.NonExistentProperty", bp_stop_expected: False) [FAIL]
  Failed DebuggerTests.BreakpointTests.ConditionalBreakpoint2(function_to_call: "invoke_add()", method_to_stop: "IntAdd", condition: "Math.NonExistentProperty", bp_stop_expected: False) [20 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.BreakpointTests.ConditionalBreakpoint2(String function_to_call, String method_to_stop, String condition, Boolean bp_stop_expected) in /_/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:line 211
--- End of stack trace from previous location ---
```

#### 8/21 - PR [1957418](https://runfo.azurewebsites.net/view/build/?number=1957418) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74301-merge-d565b4e1e1f047e0b6/firefox-DebuggerTests/1/console.ee415a45.log?%3Fhelixlogtype%3Dresult)

8x failures

<details>

```
[xUnit.net 00:17:45.13]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: False) [3 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1052
--- End of stack trace from previous location ---
[xUnit.net 00:17:49.40]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1052
--- End of stack trace from previous location ---
[xUnit.net 00:17:54.77]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1052
--- End of stack trace from previous location ---
[xUnit.net 00:17:59.92]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: False) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1052
--- End of stack trace from previous location ---
[xUnit.net 00:18:04.44]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1052
--- End of stack trace from previous location ---
[xUnit.net 00:18:12.97]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: False) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1052
--- End of stack trace from previous location ---
[xUnit.net 00:18:22.43]     DebuggerTests.MiscTests.ExceptionThrownInJS [SKIP]
  Skipped DebuggerTests.MiscTests.ExceptionThrownInJS [1 ms]
[xUnit.net 00:18:31.08]     DebuggerTests.MiscTests.InspectNullableLocals [SKIP]
  Skipped DebuggerTests.MiscTests.InspectNullableLocals [1 ms]
OpenSession crashing. proxy state: RunLoopExitState { reason = Exception, exception = System.IO.IOException: [testId: 134] Timed out after 20s waiting for the browser to be ready: /root/helix/work/correlation/firefox/firefox
   at DebuggerTests.WasmHostProvider.LaunchHostAsync(ProcessStartInfo psi, HttpContext context, Func`2 checkBrowserReady, String messagePrefix, Int32 hostReadyTimeoutMs, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/WasmHostProvider.cs:line 91
   at DebuggerTests.FirefoxProvider.StartBrowserAndProxyAsync(HttpContext context, String targetUrl, Int32 remoteDebuggingPort, Int32 proxyPort, String messagePrefix, ILoggerFactory loggerFactory, CancellationTokenSource cts, Int32 browserReadyTimeoutMs) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxProvider.cs:line 50
   at DebuggerTests.TestHarnessStartup.<>c__DisplayClass13_0.<<Configure>b__1>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/TestHarnessStartup.cs:line 144 }
[xUnit.net 00:18:52.18]     DebuggerTests.MiscTests.SetBreakpointInProjectWithSpecialCharactersInPath(classWithNamespace: "DebuggerTests.CheckSpecialCharactersInPath", expectedFileLocation: "dotnet://debugger-test-special-char-in-path.dll/te"...) [FAIL]
  Failed DebuggerTests.MiscTests.SetBreakpointInProjectWithSpecialCharactersInPath(classWithNamespace: "DebuggerTests.CheckSpecialCharactersInPath", expectedFileLocation: "dotnet://debugger-test-special-char-in-path.dll/te"...) [1 ms]
  Error Message:
   System.IO.IOException : [testId: 134] Timed out after 20s waiting for the browser to be ready: /root/helix/work/correlation/firefox/firefox
  Stack Trace:
     at DebuggerTests.WasmHostProvider.LaunchHostAsync(ProcessStartInfo psi, HttpContext context, Func`2 checkBrowserReady, String messagePrefix, Int32 hostReadyTimeoutMs, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/WasmHostProvider.cs:line 91
   at DebuggerTests.FirefoxProvider.StartBrowserAndProxyAsync(HttpContext context, String targetUrl, Int32 remoteDebuggingPort, Int32 proxyPort, String messagePrefix, ILoggerFactory loggerFactory, CancellationTokenSource cts, Int32 browserReadyTimeoutMs) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxProvider.cs:line 50
   at DebuggerTests.TestHarnessStartup.<>c__DisplayClass13_0.<<Configure>b__1>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/TestHarnessStartup.cs:line 144
--- End of stack trace from previous location ---
   at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, TimeSpan span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 375
   at DebuggerTests.DebuggerTestFirefox.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 40```
```

```
[xUnit.net 00:22:40.88]     DebuggerTests.SteppingTests.BreakOnAwaitThenStepOverToNextAwaitCall [FAIL]
  Failed DebuggerTests.SteppingTests.BreakOnAwaitThenStepOverToNextAwaitCall [31 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.SteppingTests.BreakOnAwaitThenStepOverToNextAwaitCall() in /_/src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:line 753
--- End of stack trace from previous location ---
```

</details>

#### 8/17 - PR [1949152](https://runfo.azurewebsites.net/view/build/?number=1949152) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73456-merge-7f157199450d44d4b7/firefox-DebuggerTests/1/console.a2ca7228.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:05:52.53]     DebuggerTests.DateTimeTests.CheckDateTimeLocale(locale: "en-US", fdtp: "dddd, MMMM d, yyyy h:mm:ss tt", ldp: "dddd, MMMM d, yyyy", ltp: "h:mm:ss tt", sdp: "M/d/yyyy", stp: "h:mm tt") [FAIL]
  Failed DebuggerTests.DateTimeTests.CheckDateTimeLocale(locale: "en-US", fdtp: "dddd, MMMM d, yyyy h:mm:ss tt", ldp: "dddd, MMMM d, yyyy", ltp: "h:mm:ss tt", sdp: "M/d/yyyy", stp: "h:mm tt") [71 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.DateTimeTests.CheckDateTimeLocale(String locale, String fdtp, String ldp, String ltp, String sdp, String stp) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DateTimeTests.cs:line 26
--- End of stack trace from previous location ---
```

#### 8/10 - PR [1934438](https://runfo.azurewebsites.net/view/build/?number=1934438) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73689-merge-73dc5254c72141d287/firefox-DebuggerTests/1/console.a415b7c8.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:03:29.52]     DebuggerTests.BreakpointTests.ConditionalBreakpoint2(function_to_call: "invoke_add()", method_to_stop: "IntAdd", condition: "c == \"xyz\"", bp_stop_expected: False) [FAIL]
  Failed DebuggerTests.BreakpointTests.ConditionalBreakpoint2(function_to_call: "invoke_add()", method_to_stop: "IntAdd", condition: "c == \"xyz\"", bp_stop_expected: False) [926 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.BreakpointTests.ConditionalBreakpoint2(String function_to_call, String method_to_stop, String condition, Boolean bp_stop_expected) in /_/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:line 211
--- End of stack trace from previous location ---
```

#### 8/9 - PR [1931857](https://runfo.azurewebsites.net/view/build/?number=1931857) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73489-merge-43bcfbccc9804c929c/firefox-DebuggerTests/1/console.5f2556b1.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:19:03.60]     DebuggerTests.MiscTests.EmptyTypeWithNoLocalsOrParams(type_name: "EmptyClass", is_async: False) [FAIL]
  Failed DebuggerTests.MiscTests.EmptyTypeWithNoLocalsOrParams(type_name: "EmptyClass", is_async: False) [795 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 237
   at DebuggerTests.MiscTests.EmptyTypeWithNoLocalsOrParams(String type_name, Boolean is_async) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 668
--- End of stack trace from previous location ---
```

#### 8/8 - PR [1929674](https://runfo.azurewebsites.net/view/build/?number=1929674) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71203-merge-30e9441d49d940b4a9/firefox-DebuggerTests/1/console.8ed1e41e.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:05:13.08]     DebuggerTests.BreakpointTests.ConditionalBreakpointHitTwice(function_to_call: "invoke_add_with_parms(5, 10)", function_to_call2: "invoke_add_with_parms(10, 20)", method_to_stop: "IntAdd", condition: "c == 30", bp_stop_expected: False, bp_stop_expected2: True) [FAIL]
  Failed DebuggerTests.BreakpointTests.ConditionalBreakpointHitTwice(function_to_call: "invoke_add_with_parms(5, 10)", function_to_call2: "invoke_add_with_parms(10, 20)", method_to_stop: "IntAdd", condition: "c == 30", bp_stop_expected: False, bp_stop_expected2: True) [17 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 409
   at DebuggerTests.BreakpointTests.ConditionalBreakpointHitTwice(String function_to_call, String function_to_call2, String method_to_stop, String condition, Boolean bp_stop_expected, Boolean bp_stop_expected2) in /_/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:line 248
--- End of stack trace from previous location ---
```

#### 8/7 - PR [1928901](https://runfo.azurewebsites.net/view/build/?number=1928901) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65723-merge-a9373bbb2ea4473094/firefox-DebuggerTests/1/console.2ff38139.log?%3Fhelixlogtype%3Dresult)

```
[xUnit.net 00:05:20.82]     DebuggerTests.DateTimeTests.CheckDateTimeLocale(locale: "es-ES", fdtp: "dddd, d 'de' MMMM 'de' yyyy H:mm:ss", ldp: "dddd, d 'de' MMMM 'de' yyyy", ltp: "H:mm:ss", sdp: "d/M/yyyy", stp: "H:mm") [FAIL]
  Failed DebuggerTests.DateTimeTests.CheckDateTimeLocale(locale: "es-ES", fdtp: "dddd, d 'de' MMMM 'de' yyyy H:mm:ss", ldp: "dddd, d 'de' MMMM 'de' yyyy", ltp: "H:mm:ss", sdp: "d/M/yyyy", stp: "H:mm") [42 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 409
   at DebuggerTests.DateTimeTests.CheckDateTimeLocale(String locale, String fdtp, String ldp, String ltp, String sdp, String stp) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DateTimeTests.cs:line 26
--- End of stack trace from previous location ---
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by karelz** [comment]
Happens once per 2 days, marking as blocking-clean-ci.

**Comment by radical** [comment]
These tests are in runtime-extra-platforms now, so shouldn't be blocking clean ci, IIUC.

**Comment by karelz** [comment]
runtime-extra-platform is run in Rolling runs and sometimes kicked off by devs on PRs, so it does impact CI :(

**Comment by radical** [comment]
For PRs, the job will show up orange for test failures.

For rolling builds, we could skip running the job entirely.
@thaystg would that be fine? Or are the test failures not completely random, and it would be enough to disable a few explicitly?

**Comment by radical** [comment]
And for rolling builds, we can additionally *build* the Firefox tests in the `chrome debugger tests` job, so if anyone breaks it, it would get caught.

**Comment by thaystg** [comment]
> For PRs, the job will show up orange for test failures.
> 
> For rolling builds, we could skip running the job entirely. @thaystg would that be fine? Or are the test failures not completely random, and it would be enough to disable a few explicitly?

They are completely random. I'm planning to investigate it as soon as I finish the multithreaded debugger.
