### ISSUE TITLE
[wasm] V8 crash with`System.IO.MemoryMappedFiles.Tests` on linux

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#74723]
[Rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1972465&view=results), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2f5e1a8416ea418c83/normal-System.IO.MemoryMappedFiles.Tests/1/console.1cac1bf0.log?helixlogtype=result):

```
[09:19:33] info: Discovered:  System.IO.MemoryMappedFiles.Tests.dll (found 73 of 227 test cases)
[09:19:33] info: Using random seed for test cases: 208998403
[09:19:33] info: Using random seed for collections: 208998403
[09:19:33] info: Starting:    System.IO.MemoryMappedFiles.Tests.dll
[09:19:34] info: RuntimeError: memory access out of bounds
[09:19:34] info:     at free (dlfree (<anonymous>:wasm-function[9151]):0x1e0acc)
[09:19:34] info:     at __munmap (__munmap (<anonymous>:wasm-function[9053]):0x1d70c)6
[09:19:34] info:     at SystemNative_MUnmap (SystemNative_MUnmap (<anonymous>:wasm-function[8862]):0x1cb09)2
[09:19:34] info:     at wasm_invoke_iil (wasm_invoke_iil (<anonymous>:wasm-function[175]):0xc27)8
[09:19:34] info:     at interp_exec_method (interp_exec_method (<anonymous>:wasm-function[221]):0xe74)b
[09:19:34] info:     at interp_runtime_invoke (interp_runtime_invoke (<anonymous>:wasm-function[220]):0xce8)d
[09:19:34] info:     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (<anonymous>:wasm-function[8112]):0x1a1eb)1
[09:19:34] info:     at do_runtime_invoke (do_runtime_invoke (<anonymous>:wasm-function[2053]):0x8593)d
[09:19:34] info:     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (<anonymous>:wasm-function[2051]):0x858b)3
[09:19:34] info:     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1394]):0x6840)b
[09:19:34] info:     at do_icall (do_icall (<anonymous>:wasm-function[313]):0x1d45)a
[09:19:34] info:     at do_icall_wrapper (do_icall_wrapper (<anonymous>:wasm-function[283]):0x1c8c)f
[09:19:34] info:     at interp_exec_method (interp_exec_method (<anonymous>:wasm-function[221]):0xdfd)b
[09:19:34] info:     at interp_runtime_invoke (interp_runtime_invoke (<anonymous>:wasm-function[220]):0xce8)d
[09:19:34] info:     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (<anonymous>:wasm-function[8112]):0x1a1eb)1
[09:19:34] info:     at do_runtime_invoke (do_runtime_invoke (<anonymous>:wasm-function[2053]):0x8593)d
[09:19:34] info:     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (<anonymous>:wasm-function[2051]):0x858b)3
[09:19:34] info:     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1394]):0x6840)b
[09:19:34] info:     at do_icall (do_icall (<anonymous>:wasm-function[313]):0x1d45)a
[09:19:34] info:     at do_icall_wrapper (do_icall_wrapper (<anonymous>:wasm-function[283]):0x1c8c)f
[09:19:34] info:     at interp_exec_method (interp_exec_method (<anonymous>:wasm-function[221]):0xdfd)b
[09:19:34] info:     at interp_runtime_invoke (interp_runtime_invoke (<anonymous>:wasm-function[220]):0xce8)d
[09:19:34] info:     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (<anonymous>:wasm-function[8112]):0x1a1eb)1
[09:19:34] info:     at do_runtime_invoke (do_runtime_invoke (<anonymous>:wasm-function[2053]):0x8593)d
[09:19:34] info:     at mono_runtime_try_invoke (mono_runtime_try_invoke (<anonymous>:wasm-function[2058]):0x85fa)5
[09:19:34] info:     at mono_runtime_invoke (mono_runtime_invoke (<anonymous>:wasm-function[2085]):0x8806)4
[09:19:34] info:     at mono_wasm_invoke_method_bound (mono_wasm_invoke_method_bound (<anonymous>:wasm-function[115]):0x9c66)
[09:19:34] info:     at Object.Module._mono_wasm_invoke_method_bound [as mono_wasm_invoke_method_bound] (/datadisks/disk1/work/ACE309D3/w/A7750949/e/dotnet.js:14:124106)
[09:19:34] info:     at Ws (/datadisks/disk1/work/ACE309D3/w/A7750949/e/dotnet.js:5:55421)
[09:19:34] info:     at Object.b.javaScriptExports.call_entry_point (/datadisks/disk1/work/ACE309D3/w/A7750949/e/dotnet.js:5:58159)
[09:19:34] info:     at Object.Te [as runMain] (/datadisks/disk1/work/ACE309D3/w/A7750949/e/dotnet.js:5:2713)
[09:19:34] info:     at run (test-main.js:330:50)
[09:19:34] info: exiting due to exception: RuntimeError: memory access out of bounds
[09:19:34] info: WASM EXIT 1
[09:19:34] info: Process v8 exited with 1
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
cc @vargaz

**Comment by vargaz** [comment]
This appears to fix it:
https://github.com/emscripten-core/emscripten/pull/17868

**Comment by vargaz** [comment]
Should be fixed now.
