### ISSUE TITLE
Test failure GC\\LargeMemory\\API\\gc\\keepalive\\keepalive.cmd 

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74731]
Run: [runtime-coreclr r2r 20220827.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1972398&view=ms.vss-test-web.build-test-results-tab&runId=50530538&resultId=106243&paneView=debug)

Failed test:
```
R2R windows arm64 Checked @ Windows.10.Arm64v8.Open

- GC\\LargeMemory\\API\\gc\\keepalive\\keepalive.cmd
```
**Error message:**
```
Assert failure(PID 14020 [0x000036c4], Thread: 11044 [0x2b24]): !"Unable to commit a loaderheap code page"

CORECLR! UnlockedLoaderHeap::UnlockedReservePages + 0x3F0 (0x00007fff31c88808) CORECLR! UnlockedLoaderHeap::GetMoreCommittedPages + 0x300 (0x00007fff31c86de0)
CORECLR! UnlockedLoaderHeap::UnlockedAllocMem_NoThrow + 0xFC (0x00007fff31c87bc4) CORECLR! UnlockedLoaderHeap::UnlockedAllocMem + 0xC (0x00007fff31c8796c)
CORECLR! EEClass::operator new + 0x7C (0x00007fff318f82f4) CORECLR! MethodTableBuilder::CreateClass + 0x94 (0x00007fff31acf044)
CORECLR! ClassLoader::CreateTypeHandleForTypeDefThrowing + 0x560 (0x00007fff31ad0280) CORECLR! ClassLoader::CreateTypeHandleForTypeKey + 0xCC (0x00007fff3190801c)
CORECLR! ClassLoader::DoIncrementalLoad + 0x214 (0x00007fff319088f4) CORECLR! ClassLoader::LoadTypeHandleForTypeKey_Body + 0xAC8 (0x00007fff3190d060)
File: D:\a_work\1\s\src\coreclr\utilcode\loaderheap.cpp Line: 1173
Image: D:\h\w\A2A908F1\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\A2A908F1\w\BDF70A95\uploads\Reports\GC.LargeMemory\API\gc\keepalive\keepalive.output.txt
Raw output:
BEGIN EXECUTION
keepalive.dll
largeobject.dll
memcheck.dll
3 file(s) copied.
1:15:00.75
Response file: D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\keepalive.dll.rsp
D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\IL-CG2\keepalive.dll
-o:D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\keepalive.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A2A908F1\p\System..dll
-r:D:\h\w\A2A908F1\p\Microsoft..dll
-r:D:\h\w\A2A908F1\p\mscorlib.dll
-r:D:\h\w\A2A908F1\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A2A908F1\p\crossgen2\crossgen2.dll" @"D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\keepalive.dll.rsp"   -r:D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\keepalive.dll
1:15:02.74
1:15:02.75
Response file: D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\largeobject.dll.rsp
D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\IL-CG2\largeobject.dll
-o:D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\largeobject.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A2A908F1\p\System..dll
-r:D:\h\w\A2A908F1\p\Microsoft..dll
-r:D:\h\w\A2A908F1\p\mscorlib.dll
-r:D:\h\w\A2A908F1\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A2A908F1\p\crossgen2\crossgen2.dll" @"D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\largeobject.dll.rsp"   -r:D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\largeobject.dll
1:15:04.64
1:15:04.66
Response file: D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\memcheck.dll.rsp
D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\IL-CG2\memcheck.dll
-o:D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\memcheck.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A2A908F1\p\System..dll
-r:D:\h\w\A2A908F1\p\Microsoft..dll
-r:D:\h\w\A2A908F1\p\mscorlib.dll
-r:D:\h\w\A2A908F1\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A2A908F1\p\crossgen2\crossgen2.dll" @"D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\memcheck.dll.rsp"   -r:D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A2A908F1\w\BDF70A95\e\GC\LargeMemory\API\gc\keepalive\memcheck.dll
1:15:07.61
"D:\h\w\A2A908F1\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  keepalive.dll 2048
Large Memory Machine required
Test passed
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run t


Stack trace
   at GC_LargeMemory._API_gc_keepalive_keepalive_._API_gc_keepalive_keepalive_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by janvorli** [comment]
This assert should be removed. I have already removed a similar one at other place, but haven't realized there are two others. We are hitting OOM here, so the allocation can fail and upstream caller can handle it properly. Thus the assert doesn't make sense.
I'll fix it soon.
