### ISSUE TITLE
Regression in the XmlBaseWriter.cs

### ISSUE THREAD

**Issue by marcin-krystianc** [dotnet/runtime#74752]
### Description

In this optimization change ([XmlBaseWriter.cs](https://github.com/dotnet/runtime/commit/eeeeb7a75c338b0d994ccd7140d676a612990ebc#diff-623f899046e92b4f3466d81f642abd32a22cec9ba0fe81917b4121a6066ccc68)), there is a mistake which changes the logic in the `XmlBaseWriter.cs`. Previously, it checked for the existence of `-` at the end of a text, but now it is checked at the beginning of the text.

### Reproduction Steps

Use `.NET 7 preview 1` and run this command for any F# project:
`dotnet msbuild /t:build /pp /p:TargetFramework=net7.0 MyFsharpProject.fsharp`
It fails to write for example [this](https://github.com/dotnet/fsharp/blame/main/src/FSharp.Build/Microsoft.FSharp.NetSdk.props#L33) element (which exists there for about 5 years)

### Expected behavior

Shouldn't throw an exception

### Actual behavior

throws an exception:
```
System.ArgumentException: An XML comment cannot contain '--', and '-' cannot be the last character.
   at System.Xml.XmlTextWriter.WriteComment(String text)
   at System.Xml.XmlElement.WriteElementTo(XmlWriter writer, XmlElement el)
   at System.Xml.XmlDocument.Save(XmlWriter w)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.SaveLogicalProject(TextWriter writer)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Unhandled exception: System.ArgumentException: An XML comment cannot contain '--', and '-' cannot be the last character.
   at System.Xml.XmlTextWriter.WriteComment(String text)
   at System.Xml.XmlElement.WriteElementTo(XmlWriter writer, XmlElement el)
   at System.Xml.XmlDocument.Save(XmlWriter w)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.SaveLogicalProject(TextWriter writer)
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache, String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.ExecuteInProc(String[] arguments)
```

### Regression?

yes

### Known Workarounds

no

### Other information

FYI @GrabYourPitchforks

**Comment by krwq** [comment]
cc: @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Thanks for the report! I'll send a PR fixing this (and adding regression tests) within a few hours.

**Comment by GrabYourPitchforks** [comment]
Double-checked the original PR to look for additional errors. Buggy lines:

* https://github.com/dotnet/runtime/commit/eeeeb7a75c338b0d994ccd7140d676a612990ebc#diff-623f899046e92b4f3466d81f642abd32a22cec9ba0fe81917b4121a6066ccc68R445
* https://github.com/dotnet/runtime/commit/eeeeb7a75c338b0d994ccd7140d676a612990ebc#diff-5a4227ea7ed09c1330ccd8c1706b184096516ec666ec72f1cc98864f1d11a32fR766
