### ISSUE TITLE
Failures in SSL Stream tests:  There are no more endpoints available in the endpoint mapper.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#74838]
This happened in the `release/7.0` branch. Can you please confirm if this will require a backported fix?

PR: https://github.com/dotnet/runtime/pull/74808/
Queue: Libraries Test Run release coreclr windows x86 Release
Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1976097&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74808-merge-0a29e7160d114b13be/System.Net.Security.Tests/3/console.38a99609.log?helixlogtype=result

Failure message:
> CryptographicException : No hay más extremos disponibles desde el asignador de extremos.

Which translates to:

> CryptographicException : There are no more endpoints available in the endpoint mapper.

Tests with a similar failure:

[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_SecondNegotiateClientCertificateAsync_Throws](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_UntrustedCaWithCustomTrust_OK](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsync_IncompleteIncomingTlsFrame_Throws](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsync_ClientWriteData](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsyncNoRenego_Succeeds](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NestedAuth_Throws](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsyncConcurrentIO_Throws](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsync_PendingDecryptedData_Throws](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsyncTls13_Succeeds](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsync_Succeeds](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_TargetHostName_Succeeds](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_RandomSizeWrites_OK](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamMutualAuthenticationTest.SslStream_RequireClientCert_IsMutuallyAuthenticated_ReturnsTrue](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)
[System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok](https://helix.dot.net/api/2019-06-17/jobs/0a29e716-0d11-4b13-be0e-1d71d340c394/workitems/System.Net.Security.Tests/console)

Callstack example:

```
    System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_SecondNegotiateClientCertificateAsync_Throws(sendClientCertificate: True) [FAIL]
      System.AggregateException : One or more errors occurred. (No hay m�s extremos disponibles desde el asignador de extremos.) (The following constructor parameters did not have matching fixture data: CertificateSetup setup)
      ---- System.Security.Cryptography.CryptographicException : No hay m�s extremos disponibles desde el asignador de extremos.
      ---- The following constructor parameters did not have matching fixture data: CertificateSetup setup
      Stack Trace:
        
        ----- Inner Stack Trace #1 (System.Security.Cryptography.CryptographicException) -----
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngHelpers.cs(33,0): at System.Security.Cryptography.CngHelpers.OpenStorageProvider(CngProvider provider)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Create.cs(41,0): at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngAlgorithmCore.cs(73,0): at System.Security.Cryptography.CngAlgorithmCore.GetOrGenerateKey(Int32 keySize, CngAlgorithm algorithm)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSACng.Key.cs(24,0): at System.Security.Cryptography.RSACng.get_Key()
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSACng.ImportExport.cs(50,0): at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
        /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.ImportExport.cs(282,0): at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSA.cs(811,0): at System.Security.Cryptography.RSA.WritePkcs1PublicKey()
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSA.cs(675,0): at System.Security.Cryptography.RSA.ExportRSAPublicKey()
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSAWrapper.cs(141,0): at System.Security.Cryptography.RSAWrapper.ExportRSAPublicKey()
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/RSAPkcs1X509SignatureGenerator.cs(37,0): at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.BuildPublicKey(RSA rsa)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/RSAPkcs1X509SignatureGenerator.cs(27,0): at System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.BuildPublicKey()
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509SignatureGenerator.cs(10,0): at System.Security.Cryptography.X509Certificates.X509SignatureGenerator.get_PublicKey()
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs(141,0): at System.Security.Cryptography.X509Certificates.CertificateRequest..ctor(String subjectName, RSA key, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/CertificateAuthority.cs(820,0): at System.Security.Cryptography.X509Certificates.Tests.Common.CertificateAuthority.BuildPrivatePki(PkiOptions pkiOptions, RevocationResponder& responder, CertificateAuthority& rootAuthority, CertificateAuthority[]& intermediateAuthorities, X509Certificate2& endEntityCert, Int32 intermediateAuthorityCount, String testName, Boolean registerAuthorities, Boolean pkiOptionsInSubject, String subjectName, Int32 keySize, X509ExtensionCollection extensions)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/TestHelper.cs(168,0): at System.Net.Security.Tests.TestHelper.GenerateCertificates(String targetName, String testName, Boolean longChain, Boolean serverCertificate)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamNetworkStreamTest.cs(30,0): at System.Net.Security.Tests.CertificateSetup..ctor()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/ConstructorInvoker.cs(86,0): at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by wfurt** [comment]
looks like some environmental problem. cc @bartonjs in case he has some insight to the Cng....

**Comment by bartonjs** [comment]
We've seen it before on the es-ES test machine(s)... something about the RPC system is broken and that breaks CNG which breaks .NET Crypto and also SChannel.

It happened for a while, then stopped... and I guess is happening again.

https://github.com/dotnet/runtime/issues/70320#issuecomment-1176839910

**Comment by carlossanlop** [comment]
@dotnet/ncl This issue is a bit old. Should we close it in favor of a newer one? I think people will keep assigning their failures to this, but the root cause is probably going to be different.

**Comment by wfurt** [comment]
It seems like `SslStream` is victim of https://github.com/dotnet/runtime/issues/70320 as @bartonjs mentioned. 
This looks like broken environment to me. Maybe @MattGal would have some insight why the queue is any different. 

We may add some checks into test contractor and blow whole suite if crypto is not functional but that would probably not help with build stability.

**Comment by MattGal** [comment]
> why the queue is any different.

Happy to investigate, but could you share the queue and ideally the specific log you're asking about so I don't have to trawl through all of them?

**Comment by wfurt** [comment]
This seems to exclusively happen on `Windows.10.Amd64.Server2022.ES.Open` (and its predecessors) 
I have no clue why Spanish locale would break crypto.

**Comment by carlossanlop** [comment]
Seeing this happening again. Specifically, I found it in an unrelated `release/8.0-preview1` backport PR. It is affecting several DSA, EcDSA and RSA tests. cc @bartonjs @vcsjones 

- Affected unrelated PR: https://github.com/dotnet/runtime/pull/81492
- Queue: `Libraries Test Run release coreclr windows x64 Debug`
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=155894&view=logs&j=cb131f87-d5af-5ecc-6e5f-6dc86994859c&t=76503e0a-8c41-542c-43da-63a4758a95b0&l=104
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81492-merge-87d3855728224aee8c/System.Security.Cryptography.Cng.Tests/1/console.e58b6d67.log?helixlogtype=result
- Affected tests: `System.Security.Cryptography.Dsa*`, `System.Security.Cryptography.Rsa*`, System.Security.Cryptography.EcDsa*`
- Failure example:
```
System.Security.Cryptography.Dsa.Tests.DSASignVerify_Array.VerifyKnown_2048_SHA384 [FAIL]
      System.Security.Cryptography.CryptographicException : No hay mas extremos disponibles desde el asignador de extremos.
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngHelpers.cs(36,0): at System.Security.Cryptography.CngHelpers.OpenStorageProvider(CngProvider provider)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs(125,0): at System.Security.Cryptography.CngKey.Import(ReadOnlySpan`1 keyBlob, String curveName, CngKeyBlobFormat format, CngProvider provider)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs(113,0): at System.Security.Cryptography.CngKey.Import(Byte[] keyBlob, String curveName, CngKeyBlobFormat format, CngProvider provider)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs(41,0): at System.Security.Cryptography.CngKey.Import(Byte[] keyBlob, CngKeyBlobFormat format, CngProvider provider)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs(30,0): at System.Security.Cryptography.CngKey.Import(Byte[] keyBlob, CngKeyBlobFormat format)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/DSACng.ImportExport.cs(25,0): at System.Security.Cryptography.DSACng.ImportKeyBlob(Byte[] dsaBlob, Boolean includePrivate)
        /_/src/libraries/Common/src/System/Security/Cryptography/DSACng.ImportExport.cs(55,0): at System.Security.Cryptography.DSACng.ImportParameters(DSAParameters parameters)
        /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/DSA/DSASignVerify.cs(305,0): at System.Security.Cryptography.Dsa.Tests.DSASignVerify.VerifyKnown_2048_SHA384()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by bartonjs** [comment]
> It is affecting several DSA, EcDSA and RSA tests.

The OS is broken, not .NET.  There's nothing we can do about it... this is an infrastructure problem (something, somehow, has messed up the es-es machine(s)).

**Comment by MattGal** [comment]
@bartonjs how can we help investigate?  I remember this happening before, but the weird part this time seems to be that even in the same PR from above there are instances of the same test passing normally (e.g. https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81492-merge-514b2709db814335b9/System.Security.Cryptography.Cng.Tests/1/console.59ad373c.log?helixlogtype=result).  

Every helix machine in queues named windows.10.amd64.server2022.es.* runs the same image, and it seems to succeed more often than it fails. I can help you get a repro machine with the exact image used here, but are there other experiments or changes I could make to prevent this?  Do also note that we've regenerated this image last Thursday for unrelated reasons.

**Comment by bartonjs** [comment]
I have no idea how to investigate it.  Just that the error is that the Windows Remote Procedure Call (RPC) subsystem is what's failing, and we've only ever seen it on es-es.

Since SslStream and .NET Crypto both depend on Windows Crypto, and Windows Crypto depends on RPC, when RPC is broken the whole thing falls down.

**Comment by wfurt** [comment]
Is that transient error or would the machine get to a bad state? Perhaps we can instrument the test(s) to collect some more information...?

**Comment by carlossanlop** [comment]
7.0 PR affected: https://github.com/dotnet/runtime/pull/81139
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=156613&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e&l=73
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81139-merge-93c9e9f818bc41be8e/System.Net.Http.WinHttpHandler.Functional.Tests/3/console.0302382a.log?helixlogtype=result

**Comment by MattGal** [comment]
@carlossanlop I think the problem is something to do with the state of the machine, not the branch being run from.  You can try experiments in Kusto to see which test work items ran before, e.g.:

``` 
WorkItems
| where QueueName == "windows.10.amd64.server2022.es.open.svc"
| where MachineName == "a000M0Q"
| order by Finished desc
```

If we can identify something actually _wrong_ with the images, it's pretty straightforward to change them; however that hasn't happened yet.  I went ahead and asked the DDFUN team about regenerating the base image used in case that helps.

Given this is not 100% repro, I suspect Azure Security Pack might be involved here.  They have problems on non-EN-US systems for lots of stuff and might be running things in the background to cause it.  Fixes to (known) problems with non-EN systems are 'coming soon' for a while now.

**Comment by stephentoub** [comment]
This is causing lots of CI failures.  How can we stop the bleeding?  Can we take these particular machines / images out of rotation until the problem is understood and fixed?

**Comment by MattGal** [comment]
> This is causing lots of CI failures. How can we stop the bleeding? Can we take these particular machines / images out of rotation until the problem is understood and fixed?

I'd recommend removing it from rotation;  AFAIK there have been no runtime bugs even found specific to ES-ES OS other than test issues with the UI culture.

Since regenerating the image from its base did not seem to help, I've created [a ticket asking DDFUN to fully regenerate the base image](https://portal.microsofticm.com/imp/v3/incidents/details/365667668/home), after which the next regenerated version should help

**Comment by radical** [comment]
There are failures like the following too, seen on #81634 :
```
    System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : No es posible ponerse en contacto con la autoridad de seguridad local
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(326,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamCredentialCacheTest.cs(37,0): at System.Net.Security.Tests.SslStreamCredentialCacheTest.SslStream_SameCertUsedForClientAndServer_Ok()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
```

Do these fall under this issue too, or should I open a separate one for them?
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=164134&view=logs&jobId=cb131f87-d5af-5ecc-6e5f-6dc86994859c&j=f967148e-4c68-5d25-c313-1c7f2944d30b&t=4fea9fce-7920-5784-e204-1264ba7376de), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81634-merge-bfc747800a03460699/System.Net.Security.Tests/3/console.1c1d3816.log?helixlogtype=result).

**Comment by wfurt** [comment]
same issue @radical.

**Comment by stephentoub** [comment]
These are still causing lots of failures.  I thought there was a plan in place to fix the images... did that happen and this is still occurring?

**Comment by wfurt** [comment]
I ping the Windows schannel team but nothing useful came back. If we agree that we would like to have at least one non-english test run I feel our choices are IMHO limited to:
- creating different image - perhaps with different locale. (Czech since we have Infra group in Prgue?)
- instrumenting tests to collect more info on failures -> asserts to collect dumps, extra code to retry or run diagnostics, ...? 
- run some crypto operations using windows tools and make them part of Helix health check. I would think somebody should be able to come up with PowerShell that touches the parts we care about. 
- if the state is permanent, we should take some broken machine offline for investigation

we can also run more reports to see if there is pattern of particular machines or if the failures are uniform across the pool.

**Comment by MattGal** [comment]
> These are still causing lots of failures. I thought there was a plan in place to fix the images... did that happen and this is still occurring?

As of last week's (2/15) rollout, both the image we supply and the [base image it is generated from](https://portal.microsofticm.com/imp/v3/incidents/details/365667668/home) have been recreated entirely from scratch, so if the problem persists after then regenerating the images didn't help.  (Given we don't actually understand the problem this seems like a predictable outcome)

I have another theory here, which is that Azure Security Monitor does fun stuff to prep and scan the machine and it may be impacting the behavior of the machine. [They're certainly aware of the problem](https://msazure.visualstudio.com/One/_workitems/edit/15594051), but it has taken longer than expected to teach Azure Security Monitor to work correctly on non-EN-US oses.   This could be doing stuff in the background on the machine that causes your failures.   Just an idea, since the problem is so mysterious.

**Comment by stephentoub** [comment]
Thanks.  Until we can get to the bottom of it, then, we should switch this queue to using an en-US OS.

**Comment by MattGal** [comment]
Sure, `windows.amd64.server2022.open` / `windows.amd64.server2022` are the same OS in English locale.

**Comment by vcsjones** [comment]
@MattGal This error came up in an unrelated discussion for me, and "the RPC system is overwhelmed" was pointed out as a possible meaning to this error.

Do the machines that are running these non-English locales have similar specs and resources as the English ones? Are there less machines in the pool, so they might be running more jobs simultaneously?

**Comment by MattGal** [comment]
> Do the machines that are running these non-English locales have similar specs and resources as the English ones? 

They're running on the same size Azure VM as pretty much every Windows VM in Helix (Standard_D2a_v4).   I say "pretty much" just because your Windows.10.Amd* machines are running Intel 4-core setups, but literally everything else is this.  This is an irrelevant side note needed for compute-intensive and AVX-512-requiring workloads and only applies to a few queues.

While there is a tiny bit of generational and maintenance variance between server racks in Azure, these machines are close enough in spec for everything save performance testing.  Same disks, same memory, same AMD EPYC processors.

> Are there less machines in the pool, so they might be running more jobs simultaneously?

Helix machines only run one job's work item at a time.  I implemented, and there remains (totally vestigial) code in there today, the ability to have N helix clients running on a given machine but the work items people sent couldn't stop accessing the same part of the file system or eating up all the processor capability, so it's been one work item per agent for something like 6 years now.

The reason I suspected AzSecMon is that they run all sorts of executables (like the auditpol.exe example) while assuming they're EN-US versions of them and with lots of retries.  It might be interesting to catch this exception and list all the processes running on the machine as part of test output, to see if some common System32 executable is going nuts on the system.
