### ISSUE TITLE
TarWriter allows to write invalid link entries that are unable to extract

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#74887]
Consider the following:
```cs
using var ms = new MemoryStream();
using (var writer = new TarWriter(ms, leaveOpen: true))
{
    var linkEntry = new PaxTarEntry(TarEntryType.SymbolicLink, "invalid-link");
    writer.WriteEntry(linkEntry);
}

ms.Position = 0;
TarFile.ExtractToDirectory(ms, @"C:\Users\admin\Desktop\test", true); // throws FormatException
```

Above code throws a FormatException:
```
System.FormatException : The entry is a symbolic link or a hard link but the LinkName field is null or empty.
Stack Trace:
  C:\repos\runtime\src\libraries\System.Formats.Tar\src\System\Formats\Tar\TarEntry.cs(342,0): at System.Formats.Tar.TarEntry.GetDestinationAndLinkPaths(String destinationDirectoryPath)
  C:\repos\runtime\src\libraries\System.Formats.Tar\src\System\Formats\Tar\TarEntry.cs(286,0): at System.Formats.Tar.TarEntry.ExtractRelativeToDirectory(String destinationDirectoryPath, Boolean overwrite, SortedDictionary`2 pendingModes)
  C:\repos\runtime\src\libraries\System.Formats.Tar\src\System\Formats\Tar\TarFile.cs(405,0): at System.Formats.Tar.TarFile.ExtractToDirectoryInternal(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen)
  C:\repos\runtime\src\libraries\System.Formats.Tar\src\System\Formats\Tar\TarFile.cs(162,0): at System.Formats.Tar.TarFile.ExtractToDirectory(Stream source, String destinationDirectoryName, Boolean overwriteFiles)
  C:\repos\runtime\src\libraries\System.Formats.Tar\tests\TarFile\TarFile.CreateFromDirectory.File.Tests.cs(294,0): at System.Formats.Tar.Tests.TarFile_CreateFromDirectory_File_Tests.qt()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
  C:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\MethodInvoker.cs(64,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

I think that TarWriter should not allow you to create archives that we are unable to extract.

**Comment by Jozkee** [comment]
cc @carlossanlop
