### ISSUE TITLE
Test failure System.Tests.GCExtendedTests.GetGCMemoryInfo

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74902]
Frequency - [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.tests.gcextendedtests.getgcmemoryinfo%22) in Runfo
- 9/8 - **24x failures**, first on **8/30** in Rolling run [1977040](https://runfo.azurewebsites.net/view/build/?number=1977040) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-69ca0ae7edd744e3b9/System.Runtime.Tests/1/console.b71d7710.log?%3Fhelixlogtype%3Dresult)
    - net7.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open - all failures

### Original Report

Run: [runtime-coreclr libraries-jitstress 20220831.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1978327&view=ms.vss-test-web.build-test-results-tab&runId=50610272&resultId=182371&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo
```
**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: 0
   at System.Tests.GCExtendedTests.<>c.<GetGCMemoryInfo>b__24_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 818
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64

Child process:
  System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCExtendedTests+<>c Void <GetGCMemoryInfo>b__24_0()
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by mangod9** [comment]
we should disable till we can investigate this for 8.

**Comment by karelz** [comment]
@mangod9 can you please disable it ASAP?
It impacts CI -- including Rolling runs (see updated top post). Happens almost **3x per day**.

**Comment by jkotas** [comment]
Test disabled by https://github.com/dotnet/runtime/pull/75309

**Comment by karelz** [comment]
The test is still failing in CI -- was the disabling done correctly? @mangod9

Latest run: 9/12 AM Rolling run [12571](https://runfo.azurewebsites.net/view/build/?number=12571) - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c186ea673b2147c98d/System.Runtime.Tests/1/console.b7c39fd4.log?%3Fhelixlogtype%3Dresult)

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220912.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=12494&view=ms.vss-test-web.build-test-results-tab&runId=245546&resultId=175257&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open

- System.Tests.GCExtendedTests.GetGCMemoryInfo
```

**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: 0
   at System.Tests.GCExtendedTests.<>c.<GetGCMemoryInfo>b__24_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 818
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64

Child process:
  System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCExtendedTests+<>c Void <GetGCMemoryInfo>b__24_0()

```

**Comment by jakobbotsch** [comment]
Even after #75475 the test is still running it seems, e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=17418&view=ms.vss-test-web.build-test-results-tab&runId=345226&resultId=181918&paneView=debug.

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220915.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=17980&view=ms.vss-test-web.build-test-results-tab&runId=358228&resultId=183518&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1_tiered-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-tailcallstress-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo

net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open
- System.Tests.GCExtendedTests.GetGCMemoryInfo
```
**Error message:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: 0
   at System.Tests.GCExtendedTests.<>c.<GetGCMemoryInfo>b__24_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 818
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64

Child process:
  System.Runtime.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCExtendedTests+<>c Void <GetGCMemoryInfo>b__24_0()

```
