### ISSUE TITLE
superpmi: test failure collecting b425314.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#74969]
Doing a SuperPMI collection of b425314.cmd causes the test to fail with a System.IndexOutOfRangeException.

With https://github.com/dotnet/runtime/pull/74961,
```
set spmi_enable_collection=1
set spmi_collect_dir=c:\bugs\spmicollection3\test
mkdir %spmi_collect_dir%

call c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314\b425314.cmd -coreroot c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root

BEGIN EXECUTION
 "c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  b425314.dll
CastClass: Checks=10003, Flips=227149748, Elapsed=00:00:03.2172447
Unbox: Checks=10003, Flips=230166991, Elapsed=00:00:03.0070399
GenericMethod: Checks=5604758, Flips=172649670, Elapsed=00:00:03.0011782
2 exceptions were thrown
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CastClass.CheckVal(String str) in C:\gh\runtime\src\tests\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 463
   at CastClass.CheckObjects() in C:\gh\runtime\src\tests\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 530


System.Exception: Bad value 5
   at Unbox.CheckVal(Int32 val) in C:\gh\runtime\src\tests\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 606
   at Unbox.CheckObjects() in C:\gh\runtime\src\tests\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 671


System.Exception: Failure
   at Mutate.Main(String[] args) in C:\gh\runtime\src\tests\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 951
Test FAILED
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
```

Without https://github.com/dotnet/runtime/pull/74961, repro with:
```
set CORE_ROOT=c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
set spmi_collect_dir=c:\bugs\spmicollection3\test
mkdir %spmi_collect_dir%
set spmi_jitlib=%CORE_ROOT%\clrjit.dll
set SuperPMIShimLogPath=%spmi_collect_dir%
set SuperPMIShimPath=%spmi_jitlib%
set COMPlus_EnableExtraSuperPmiQueries=1
set COMPlus_JitName=superpmi-shim-collector.dll
set COMPlus_JitPath=%CORE_ROOT%\%COMPlus_JitName%

c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Checked\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314\b425314.dll
```

**Comment by AndyAyersMS** [comment]
I'll take a look.

**Comment by AndyAyersMS** [comment]
Looking at asm diffs with and without SPMI collection, I see a lot more jit temps marked as "is exact" across a lot of methods, and in this method it leads to actual codegen diffs and presumably bad code:
```
;; non -spmi

; Assembly listing for method CastClass:CheckObjects():this

;  V16 tmp11        [V16,T11] (  3, 16   )     ref  ->  rdx         "CASTCLASS eval op1"
;  V17 tmp12        [V17,T19] (  3,  8   )    long  ->  r10         "fgMakeTemp is creating a new local variable"
;  V18 tmp13        [V18,T03] (  4, 28   )     ref  ->  rax         class-hnd "spilling QMark2"
;* V19 tmp14        [V19    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impSpillSpecialSideEff"
;  V20 tmp15        [V20,T12] (  3, 16   )     ref  ->  rdx         "CASTCLASS eval op1"
;  V21 tmp16        [V21,T20] (  3,  8   )    long  ->   r9         "fgMakeTemp is creating a new local variable"
;  V22 tmp17        [V22,T04] (  4, 28   )     ref  ->  rax         class-hnd "spilling QMark2"
;* V23 tmp18        [V23    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impSpillSpecialSideEff"
;  V24 tmp19        [V24,T13] (  3, 16   )     ref  ->  rdx         "CASTCLASS eval op1"
;  V25 tmp20        [V25,T21] (  3,  8   )    long  ->   r8         "fgMakeTemp is creating a new local variable"
;  V26 tmp21        [V26,T05] (  4, 28   )     ref  ->  rax         class-hnd "spilling QMark2"
;* V27 tmp22        [V27    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impSpillSpecialSideEff"
;  V28 tmp23        [V28,T25] (  2,  0   )     ref  ->  rcx         class-hnd single-def "impSpillSpecialSideEff"
;  V29 tmp24        [V29,T14] (  3, 13   )     int  ->  rsi         "OSR entry state var"
;  V30 tmp25        [V30,T00] (  5, 40   )     ref  ->  rax         class-hnd "Inlining Arg"
;  V31 PSPSym       [V31,T23] (  1,  1   )    long  ->  [rbp-10H]   do-not-enreg[V] "PSPSym"
;  V32 cse0         [V32,T16] (  3, 12   )    long  ->  rdx         "CSE - moderate"

;; spmi

;* V16 tmp11        [V16    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impSpillSpecialSideEff"
;  V17 tmp12        [V17,T10] (  3, 16   )     ref  ->  rdx         "CASTCLASS eval op1"
;  V18 tmp13        [V18,T17] (  3,  8   )    long  ->   r9         "fgMakeTemp is creating a new local variable"
;  V19 tmp14        [V19,T03] (  4, 28   )     ref  ->  rax         class-hnd "spilling QMark2"
;* V20 tmp15        [V20    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impSpillSpecialSideEff"
;  V21 tmp16        [V21,T11] (  3, 16   )     ref  ->  rdx         "CASTCLASS eval op1"
;  V22 tmp17        [V22,T18] (  3,  8   )    long  ->   r8         "fgMakeTemp is creating a new local variable"
;  V23 tmp18        [V23,T04] (  4, 28   )     ref  ->  rax         class-hnd "spilling QMark2"
;* V24 tmp19        [V24    ] (  0,  0   )     ref  ->  zero-ref    class-hnd "impSpillSpecialSideEff"
;  V25 tmp20        [V25,T22] (  2,  0   )     ref  ->  rcx         class-hnd single-def "impSpillSpecialSideEff"
;  V26 tmp21        [V26,T12] (  3, 13   )     int  ->  rsi         "OSR entry state var"
;  V27 tmp22        [V27,T00] (  5, 40   )     ref  ->  rax         class-hnd exact "Inlining Arg"
;  V28 PSPSym       [V28,T20] (  1,  1   )    long  ->  [rbp-10H]   do-not-enreg[V] "PSPSym"
;  V29 cse0         [V29,T14] (  3, 12   )    long  ->  rdx         "CSE - moderate"
```
So SPMI is not faithfully passing results either to the VM or back from the VM.

**Comment by AndyAyersMS** [comment]
From the diff in jit dumps
```
;;; no spmi collect

Importing BB17 (PC=118) of 'CastClass:CheckObjects():this'
    [ 0] 118 (0x076) volatile.ldsfld 04000018
    [ 1] 125 (0x07d) castclass 01000015Querying runtime about current class of field CastClass.s_objVolatile (declared as System.Object)
Field's current class not available

Considering optimization of castclass from 00007FFE78729818 (System.Object) to 00007FFE789EACA8 (System.String)
Can't optimize since fromClass is inexact

;;; spmi collect

Importing BB17 (PC=118) of 'CastClass:CheckObjects():this'
    [ 0] 118 (0x076) volatile.ldsfld 04000018
    [ 1] 125 (0x07d) castclass 01000015Querying runtime about current class of field CastClass.s_objVolatile (declared as System.Object)
Runtime reports field is init-only and initialized and has class System.Object

Considering optimization of castclass from exact 00007FFE78729818 (System.Object) to 00007FFE789DCAE8 (System.String)
Not optimizing failing castclass (yet)
```
