### ISSUE TITLE
ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp failed on Ubuntu 22.04 WSL2 with not found: RevocationStatusUnknown\nIn value:  X509ChainStatusFlags[] [Revoked]]]

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#74972]
```
      <test name="System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp" type="System.Net.Security.Tests.CertificateValidationRemoteServer" method="ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp" time="1.6393596" result="Fail">
        <failure exception-type="Xunit.Sdk.ContainsException">
          <message><![CDATA[Assert.Contains() Failure\nNot found: RevocationStatusUnknown\nIn value:  X509ChainStatusFlags[] [Revoked]]]></message>
          <stack-trace><![CDATA[   at System.Net.Security.Tests.CertificateValidationRemoteServer.<ConnectWithRevocation_WithCallback_Core>g__CertificateValidationCallback|6_0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 344
   at System.Net.Security.SslStream.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus) in /home/dan/git/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Protocol.cs:line 1031
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus) in /home/dan/git/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 506
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions) in /home/dan/git/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 519
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /home/dan/git/runtime/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 332
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /home/dan/git/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /home/dan/git/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /home/dan/git/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext) in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 310
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext) in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 311
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext) in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 311
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext) in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 311
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext) in /home/dan/git/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 311
--- End of stack trace from previous location ---]]></stack-trace>
        </failure>
      </test>
```

**Comment by wfurt** [comment]
cc: @bartonjs

**Comment by karelz** [comment]
Duplicate of #70981
