### ISSUE TITLE
Mono Bionic CI failure in NegotiateAuthenticationKerberosTest `Invalid_Token` and `Loopback_Success` tests

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75008]
Found in a release/7.0 deps update PR: https://github.com/dotnet/runtime/pull/74926

Please determine if this needs a fix to get backported.

- Queue: `Build Linux_bionic arm64 Release AllSubsets_Mono`
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=logs&j=ab4fc4e5-ef33-5032-da89-7ee95c39b814&t=07cac0ba-4c44-502d-ba5a-d68e21dab793&l=58
- Console log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-0416eef15c6a45a1a6/System.Net.Security.Tests/3/console.7bff891b.log?helixlogtype=result

Callstacks:
```
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.TrueException: Client authentication failed with Unsupported
                         Expected: True
                         Actual:   False
                         /_/src/libraries/System.Net.Security/tests/FunctionalTests/NegotiateAuthenticationKerberosTest.cs(48,0): at System.Net.Security.Tests.NegotiateAuthenticationKerberosTest.<>c.<Loopback_Success>b__2_0()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Net.Security.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.NegotiateAuthenticationKerberosTest+<>c Void <Loopback_Success>b__2_0()
                         
                         
                       Output:
                         GSSAPI trace:
```

```
                       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
                       Stack Trace:
                         
                         Child exception:
                           Xunit.Sdk.EqualException: Assert.Equal() Failure
                         Expected: ContinueNeeded
                         Actual:   GenericFailure
                         /_/src/libraries/System.Net.Security/tests/FunctionalTests/NegotiateAuthenticationKerberosTest.cs(75,0): at System.Net.Security.Tests.NegotiateAuthenticationKerberosTest.<>c.<Invalid_Token>b__3_0()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                         
                         Child process:
                           System.Net.Security.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.NegotiateAuthenticationKerberosTest+<>c Void <Invalid_Token>b__3_0()
                         
                         
                       Output:
                         GSSAPI trace:
```
```                  
                   Finished:    System.Net.Security.Tests
                 === TEST EXECUTION SUMMARY ===
                    System.Net.Security.Tests  Total: 4420, Errors: 0, Failed: 2, Skipped: 10, Time: 11.246s
                 Std err:
                     System.Net.Security.Tests.NegotiateAuthenticationKerberosTest.Loopback_Success [FAIL]
                     System.Net.Security.Tests.NegotiateAuthenticationKerberosTest.Invalid_Token [FAIL]
```

**Comment by karelz** [comment]
Duplicate of #74708
