### ISSUE TITLE
WASM CI failure in `DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass`

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75013]
This was found in a release/7.0 deps update PR: https://github.com/dotnet/runtime/pull/74926

Please help determine if this issue needs a fix backported.

- Queue: `net7.0-Browser-Release-wasm-Mono_firefox_Release-WasmDebuggerTests-(Ubuntu.1804.Amd64)`
- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=18640&paneView=debug&resultId=100037
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-b804a8ffd359492593/firefox-DebuggerTests/1/console.9989d601.log?helixlogtype=result

- Callstacks:
>DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "this.")
```
[xUnit.net 00:12:38.21]     DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "this.") [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "this.") [53 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.EvaluateOnCallFrame(String id, String expression, Boolean expect_ok) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 430
   at DebuggerTests.DebuggerTestBase.EvaluateOnCallFrameAndCheck(String call_frame_id, ValueTuple`2[] args) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1166
   at DebuggerTests.EvaluateOnCallFrameTests.<>c__DisplayClass9_0.<<InheritedAndPrivateMembersInAClass>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 235
--- End of stack trace from previous location ---
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 299
   at DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(String prefix) in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 225
--- End of stack trace from previous location ---
```

>DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "")
```
[xUnit.net 00:13:38.22]     DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "") [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "") [53 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.EvaluateOnCallFrame(String id, String expression, Boolean expect_ok) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 430
   at DebuggerTests.DebuggerTestBase.EvaluateOnCallFrameAndCheck(String call_frame_id, ValueTuple`2[] args) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1166
   at DebuggerTests.EvaluateOnCallFrameTests.<>c__DisplayClass9_0.<<InheritedAndPrivateMembersInAClass>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 235
--- End of stack trace from previous location ---
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 299
   at DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(String prefix) in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 225
```

**Comment by radical** [comment]
These are failures with firefox, which is known to be unstable currently. Closing this.

**Comment by carlossanlop** [comment]
@radical @steveisok @lewing @akoeplinger we're still seeing this failure, but the issue was closed. Should we reopen it so we can keep tracking it? We could also add the KnownBuildError json to learn how often it happens.

Example of a recent hit (2023/07/12):

- PR: https://github.com/dotnet/runtime/pull/88758
- Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=337259&view=logs&j=c7c013c2-b629-5fa5-abab-a8725284125b&t=6b7300c8-b6b8-57ee-0287-55d7d3c26e2c
- Queue: `Build Browser wasm Linux Release Mono_DebuggerTests_firefox`
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-88758-merge-87a8a134564046b6bb/firefox-DebuggerTests/1/console.e3a0418b.log?helixlogtype=result

**Comment by carlossanlop** [comment]
Reopening. I'm still seeing this in 7.0.

- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=385075&view=logs&j=c7c013c2-b629-5fa5-abab-a8725284125b&t=6b7300c8-b6b8-57ee-0287-55d7d3c26e2c
- Queue: `Build Browser wasm Linux Release Mono_DebuggerTests_firefox`
- PR: https://github.com/dotnet/runtime/pull/91083
- Log: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-91083-merge-74edfa5b3d7147989c/firefox-DebuggerTests/1/console.435c20dc.log?helixlogtype=result
- Output:
```
[xUnit.net 00:14:05.65]     DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "this.") [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "this.") [53 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.EvaluateOnCallFrame(String id, String expression, Boolean expect_ok) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 430
   at DebuggerTests.DebuggerTestBase.EvaluateOnCallFrameAndCheck(String call_frame_id, ValueTuple`2[] args) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1165
   at DebuggerTests.EvaluateOnCallFrameTests.<>c__DisplayClass9_0.<<InheritedAndPrivateMembersInAClass>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 235
--- End of stack trace from previous location ---
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 299
   at DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(String prefix) in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 225
--- End of stack trace from previous location ---
[xUnit.net 00:15:05.66]     DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "") [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(prefix: "") [51 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.EvaluateOnCallFrame(String id, String expression, Boolean expect_ok) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 430
   at DebuggerTests.DebuggerTestBase.EvaluateOnCallFrameAndCheck(String call_frame_id, ValueTuple`2[] args) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1165
   at DebuggerTests.EvaluateOnCallFrameTests.<>c__DisplayClass9_0.<<InheritedAndPrivateMembersInAClass>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 235
--- End of stack trace from previous location ---
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 299
   at DebuggerTests.EvaluateOnCallFrameTests.InheritedAndPrivateMembersInAClass(String prefix) in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 225
--- End of stack trace from previous location ---
[xUnit.net 00:15:05.66]     DebuggerTests.EvaluateOnCallFrameTests.EvaluateBrowsableNone [SKIP]
[xUnit.net 00:15:05.66]     DebuggerTests.EvaluateOnCallFrameTests.EvaluateBrowsableNever [SKIP]
  Skipped DebuggerTests.EvaluateOnCallFrameTests.EvaluateBrowsableNone [1 ms]
  Skipped DebuggerTests.EvaluateOnCallFrameTests.EvaluateBrowsableNever [1 ms]
[xUnit.net 00:15:13.43]     DebuggerTests.EvaluateOnCallFrameTests.EvaluateStaticClassesNestedWithNoNamespace [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.EvaluateStaticClassesNestedWithNoNamespace [26 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpointInMethod(String assembly, String type, String method, Int32 lineOffset, Int32 col, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 415
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 280
   at DebuggerTests.EvaluateOnCallFrameTests.EvaluateStaticClassesNestedWithNoNamespace() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 870
--- End of stack trace from previous location ---
```
