### ISSUE TITLE
WASM CI failure in `DebuggerTests.ArrayTests` `InspectGenericTypeArrayLocals` and `InspectGenericValueTypeArrayLocals`

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75019]
Found in a release/7.0 PR: https://github.com/dotnet/runtime/pull/74926

Please help determine if this needs a fix to be backported to 7.0.

- Queue: `net7.0-Browser-Release-wasm-Mono_firefox_Release-WasmDebuggerTests-(Ubuntu.1804.Amd64)`
- Artifacts: 
  - InspectGenericTypeArrayLocals: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=18640&paneView=debug&resultId=100011
  - InspectGenericValueTypeArrayLocals: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=18640&paneView=debug&resultId=100053
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-b804a8ffd359492593/firefox-DebuggerTests/1/console.9989d601.log?helixlogtype=result
- Callstacks:

InspectGenericTypeArrayLocals:
```
[xUnit.net 00:03:03.52]     DebuggerTests.ArrayTests.InspectGenericTypeArrayLocals(line: 72, col: 8, method_name: "DebuggerTests.ArrayTestsClass.GenericTypeLocals", test_prev_frame: False, frame_idx: 0, use_cfo: False) [FAIL]
  Failed DebuggerTests.ArrayTests.InspectGenericTypeArrayLocals(line: 72, col: 8, method_name: "DebuggerTests.ArrayTestsClass.GenericTypeLocals", test_prev_frame: False, frame_idx: 0, use_cfo: False) [1 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpoint(String url_key, Int32 line, Int32 column, Boolean expect_ok, Boolean use_regex, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 106
   at DebuggerTests.ArrayTests.TestSimpleArrayLocals(Int32 line, Int32 col, String entry_method_name, String method_name, String etype_name, String local_var_name_prefix, Object[] array, Object[] array_elem_props, Boolean test_prev_frame, Int32 frame_idx, Boolean use_cfo) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ArrayTests.cs:line 236
   at DebuggerTests.ArrayTests.InspectGenericTypeArrayLocals(Int32 line, Int32 col, String method_name, Boolean test_prev_frame, Int32 frame_idx, Boolean use_cfo) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ArrayTests.cs:line 92
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Information: [testId: 21] New test request for test id 21
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [21] Starting /root/helix/work/correlation/firefox/firefox with -profile /root/helix/work/workitem/e/debugger-test/AppBundle/test-profile-21 -headless -new-instance -private -start-debugger-server 6521 http://localhost:9400/debugger-driver.html
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [test_id: 20] FirefoxProvider Dispose
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [test_id: 20] FirefoxProvider Dispose done
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [testId: 20] TestHarnessStartup done
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 20
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stderr *** You are running in headless mode.
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout [GFX1-]: glxtest: libpci missing
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout [GFX1-]: glxtest: libGL.so.1 missing
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout [GFX1-]: glxtest: libEGL missing
 | [2022-09-01T18:46:44] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout [GFX1-]: No GPUs detected via PCI
 | [2022-09-01T18:46:45] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
 | [2022-09-01T18:46:49] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout console.debug: "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
 | [2022-09-01T18:46:49] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout console.debug: "#debugger-app-ready#"
 | [2022-09-01T18:46:49] DebuggerTests.TestHarnessProxy Debug: [testId: 21] browser-stdout console.log: "ready"
 | [2022-09-01T18:46:49] Inspector-21 Information: waiting for the runtime to be ready
 | [2022-09-01T18:46:49] FirefoxMonoProxy-21 Error: Cannot respond to command: msg-:::0:::server1.conn0.windowGlobal4294967298/windowGlobalTarget2 with result: [Result: IsOk: True, IsErr: False, Value: {
 |                                                    "result": {
 |                                                      "value": {
 |                                                        "type": "frameUpdate",
 |                                                        "frames": [
 |                                                          {
 |                                                            "id": 17,
 |                                                            "isTopLevel": true,
 |                                                            "url": "http://localhost:9400/debugger-driver.html",
 |                                                            "title": ""
 |                                                          }
 |                                                        ],
 |                                                        "from": "server1.conn0.windowGlobal4294967298/windowGlobalTarget2"
 |                                                      }
 |                                                    }
 |                                                  }, Error:  ] - command is not pending
 | [2022-09-01T18:46:51] Inspector-21 Information: runtime ready, TEST TIME
 | [2022-09-01T18:46:51] FirefoxMonoProxy-21 Error: OnCommand for id: msg-:::0, {
 |                                                    "type": "setBreakpoint",
 |                                                    "location": {
 |                                                      "line": 73,
 |                                                      "column": 8,
 |                                                      "sourceUrl": "dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-array-test.cs"
 |                                                    },
 |                                                    "to": "server1.conn0.breakpoint-list4"
 |                                                  } failed: System.ArgumentNullException: Value cannot be null. (Parameter 's')
 |                                                     at System.Convert.FromBase64String(String s)
 |                                                     at Microsoft.WebAssembly.Diagnostics.MonoBinaryReader.From(Result result) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 462
 |                                                     at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.SendDebuggerAgentCommand[T](T command, MonoBinaryWriter arguments, CancellationToken token, Boolean throwOnError) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 997
 |                                                     at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.GetMethodIdByToken(Int32 assembly_id, Int32 method_token, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 1087
 |                                                     at Microsoft.WebAssembly.Diagnostics.MonoProxy.SetMonoBreakpoint(SessionId sessionId, String reqId, SourceLocation location, String condition, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1451
 |                                                     at Microsoft.WebAssembly.Diagnostics.MonoProxy.SetBreakpoint(SessionId sessionId, DebugStore store, BreakpointRequest req, Boolean sendResolvedEvent, Boolean fromEnC, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1646
 |                                                     at Microsoft.WebAssembly.Diagnostics.FirefoxMonoProxy.AcceptCommand(MessageId sessionId, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxMonoProxy.cs:line 432
 |                                                     at Microsoft.WebAssembly.Diagnostics.FirefoxMonoProxy.OnCommand(MessageId id, JObject parms, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxMonoProxy.cs:line 76
 | [2022-09-01T18:46:52] DebuggerTests.TestHarnessProxy Debug: [test_id: 21] FirefoxProvider Dispose
 | [2022-09-01T18:46:52] DebuggerTests.TestHarnessProxy Debug: [test_id: 21] FirefoxProvider Dispose done
 | [2022-09-01T18:46:52] DebuggerTests.TestHarnessProxy Debug: [testId: 21] TestHarnessStartup done
 | [2022-09-01T18:46:52] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 21
```

InspectGenericValueTypeArrayLocals:
```
[xUnit.net 00:00:35.13]     DebuggerTests.ArrayTests.InspectGenericValueTypeArrayLocals(line: 89, col: 8, method_name: "DebuggerTests.ArrayTestsClass.GenericValueTypeLoca"..., test_prev_frame: False, frame_idx: 0, use_cfo: False) [FAIL]
  Failed DebuggerTests.ArrayTests.InspectGenericValueTypeArrayLocals(line: 89, col: 8, method_name: "DebuggerTests.ArrayTestsClass.GenericValueTypeLoca"..., test_prev_frame: False, frame_idx: 0, use_cfo: False) [37 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestFirefox.SetBreakpoint(String url_key, Int32 line, Int32 column, Boolean expect_ok, Boolean use_regex, String condition) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestFirefox.cs:line 106
   at DebuggerTests.ArrayTests.TestSimpleArrayLocals(Int32 line, Int32 col, String entry_method_name, String method_name, String etype_name, String local_var_name_prefix, Object[] array, Object[] array_elem_props, Boolean test_prev_frame, Int32 frame_idx, Boolean use_cfo) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ArrayTests.cs:line 236
   at DebuggerTests.ArrayTests.InspectGenericValueTypeArrayLocals(Int32 line, Int32 col, String method_name, Boolean test_prev_frame, Int32 frame_idx, Boolean use_cfo) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ArrayTests.cs:line 129
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2022-09-01T18:44:16] DebuggerTests.TestHarnessProxy Information: [testId: 3] New test request for test id 3
 | [2022-09-01T18:44:16] DebuggerTests.TestHarnessProxy Debug: [3] Starting /root/helix/work/correlation/firefox/firefox with -profile /root/helix/work/workitem/e/debugger-test/AppBundle/test-profile-3 -headless -new-instance -private -start-debugger-server 6503 http://localhost:9400/debugger-driver.html
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stderr *** You are running in headless mode.
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [test_id: 2] FirefoxProvider Dispose
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [test_id: 2] FirefoxProvider Dispose done
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 2] TestHarnessStartup done
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 2
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout [GFX1-]: glxtest: libpci missing
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout [GFX1-]: glxtest: libGL.so.1 missing
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout [GFX1-]: glxtest: libEGL missing
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout [GFX1-]: No GPUs detected via PCI
 | [2022-09-01T18:44:17] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
 | [2022-09-01T18:44:21] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout console.debug: "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
 | [2022-09-01T18:44:21] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout console.debug: "#debugger-app-ready#"
 | [2022-09-01T18:44:21] DebuggerTests.TestHarnessProxy Debug: [testId: 3] browser-stdout console.log: "ready"
 | [2022-09-01T18:44:21] Inspector-3 Information: waiting for the runtime to be ready
 | [2022-09-01T18:44:21] FirefoxMonoProxy-3 Error: Cannot respond to command: msg-:::0:::server1.conn0.windowGlobal4294967298/windowGlobalTarget2 with result: [Result: IsOk: True, IsErr: False, Value: {
 |                                                   "result": {
 |                                                     "value": {
 |                                                       "type": "frameUpdate",
 |                                                       "frames": [
 |                                                         {
 |                                                           "id": 17,
 |                                                           "isTopLevel": true,
 |                                                           "url": "http://localhost:9400/debugger-driver.html",
 |                                                           "title": ""
 |                                                         }
 |                                                       ],
 |                                                       "from": "server1.conn0.windowGlobal4294967298/windowGlobalTarget2"
 |                                                     }
 |                                                   }
 |                                                 }, Error:  ] - command is not pending
 | [2022-09-01T18:44:23] Inspector-3 Information: runtime ready, TEST TIME
 | [2022-09-01T18:44:24] FirefoxMonoProxy-3 Error: OnCommand for id: msg-:::0, {
 |                                                   "type": "setBreakpoint",
 |                                                   "location": {
 |                                                     "line": 90,
 |                                                     "column": 8,
 |                                                     "sourceUrl": "dotnet://debugger-test.dll//_/src/mono/wasm/debugger/tests/debugger-test/debugger-array-test.cs"
 |                                                   },
 |                                                   "to": "server1.conn0.breakpoint-list4"
 |                                                 } failed: System.ArgumentNullException: Value cannot be null. (Parameter 's')
 |                                                    at System.Convert.FromBase64String(String s)
 |                                                    at Microsoft.WebAssembly.Diagnostics.MonoBinaryReader.From(Result result) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 462
 |                                                    at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.SendDebuggerAgentCommand[T](T command, MonoBinaryWriter arguments, CancellationToken token, Boolean throwOnError) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 997
 |                                                    at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.GetAssemblyId(String asm_name, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 1161
 |                                                    at Microsoft.WebAssembly.Diagnostics.MonoProxy.SetMonoBreakpoint(SessionId sessionId, String reqId, SourceLocation location, String condition, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1450
 |                                                    at Microsoft.WebAssembly.Diagnostics.MonoProxy.SetBreakpoint(SessionId sessionId, DebugStore store, BreakpointRequest req, Boolean sendResolvedEvent, Boolean fromEnC, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs:line 1646
 |                                                    at Microsoft.WebAssembly.Diagnostics.FirefoxMonoProxy.AcceptCommand(MessageId sessionId, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxMonoProxy.cs:line 432
 |                                                    at Microsoft.WebAssembly.Diagnostics.FirefoxMonoProxy.OnCommand(MessageId id, JObject parms, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Firefox/FirefoxMonoProxy.cs:line 76
 | [2022-09-01T18:44:24] DebuggerTests.TestHarnessProxy Debug: [testId: 3] TestHarnessStartup done
 | [2022-09-01T18:44:24] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 3
```

**Comment by radical** [comment]
Closing this as firefox tests are known to be unstable, because of which we the `runtime-staging` job ignores the test failures.
