### ISSUE TITLE
WASM CI failure in `DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode`

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75018]
Found in a release/7.0 PR: https://github.com/dotnet/runtime/pull/74926

Please help determine if this needs a fix backported to 7.0.

- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=18640&paneView=debug&resultId=100004
- Queue: `net7.0-Browser-Release-wasm-Mono_firefox_Release-WasmDebuggerTests-(Ubuntu.1804.Amd64)`
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-b804a8ffd359492593/firefox-DebuggerTests/1/console.9989d601.log?helixlogtype=result
- Callstacks:
```
[xUnit.net 00:25:18.07]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: False) [3 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```
```
[xUnit.net 00:25:23.90]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: True) [1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```
```
[xUnit.net 00:25:30.54]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```
```
[xUnit.net 00:25:36.28]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: False) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```
```
[xUnit.net 00:25:42.85]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```
```
[xUnit.net 00:25:48.83]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: False) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1467
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```

**Comment by radical** [comment]
Closing this as firefox tests are known to be unstable, because of which we the `runtime-staging` job ignores the test failures.

**Comment by carlossanlop** [comment]
Reopening because we are still hitting it, need to be able to easily find this issue when we hit it in a PR.

- Found in a `release/7.0` PR:  https://github.com/dotnet/runtime/pull/76113
- Queue: Build Browser wasm Linux Release Mono_DebuggerTests_firefox
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=31924&view=logs&j=c7c013c2-b629-5fa5-abab-a8725284125b&t=6b7300c8-b6b8-57ee-0287-55d7d3c26e2c
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76113-merge-15bb1c325df540758c/firefox-DebuggerTests/1/console.1a16e8a1.log?helixlogtype=result
<details>
<summary>Callstack</summary>
```
[xUnit.net 00:24:18.47]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: False) [4 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1471
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
[xUnit.net 00:24:24.40]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1471
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
[xUnit.net 00:24:31.11]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1471
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
[xUnit.net 00:24:37.81]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromClassWithoutDebugSymbols", line: 1287, jmc: False) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1471
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
[xUnit.net 00:24:44.27]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: True) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClass", line: 1335, jmc: True) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": true
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1471
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
[xUnit.net 00:24:50.57]     DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: False) [FAIL]
  Failed DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(class_name: "ClassInheritsFromNonUserCodeClassThatInheritsFromN"..., line: 1352, jmc: False) [< 1 ms]
  Error Message:
   System.Exception : No 'to' field found in '{
  "JustMyCodeStepping": false
}'
  Stack Trace:
     at DebuggerTests.FirefoxInspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/FirefoxInspectorClient.cs:line 194
   at DebuggerTests.InspectorClient.SendCommand(String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 78
   at DebuggerTests.DebuggerTestBase.SetJustMyCode(Boolean enabled) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1471
   at DebuggerTests.MiscTests.InspectThisThatInheritsFromClassNonUserCode(String class_name, Int32 line, Boolean jmc) in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 1054
--- End of stack trace from previous location ---
```
</details>

**Comment by radical** [comment]
These are known to be unstable firefox tests. @thaystg should we disable these for the 7.0 branch?

**Comment by radical** [comment]
@carlossanlop since these are expected, and known to be unstable, can we ignore these for 7.0 branch, or should I open a PR to disable it on 7.0 rolling builds?

**Comment by radical** [comment]
@ilonatommy @thaystg Are these still failing? Should this be moved to a future milestone?

**Comment by ilonatommy** [comment]
The tests are supposed to be blocked for firefox and the behavior from the description is expected.
