### ISSUE TITLE
Bionic Android Mono CI failure in System.IO.Pipes named pipes unix domain socket tests (server and client)

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75021]
Found in a release/7.0 PR: https://github.com/dotnet/runtime/pull/74926

Please help determine if a fix needs to be backported to 7.0.

- Queues:
  - `net7.0-Linux-Release-x64-Mono_Release_LinuxBionic-Ubuntu.1804.Amd64.Android.29.Open`
  - `net7.0-Linux-Release-arm64-Mono_Release_LinuxBionic-Windows.10.Amd64.Android.Open`
- Artifacts: 
  - x64: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=19036&paneView=debug
  - arm64: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1392&view=ms.vss-test-web.build-test-results-tab&runId=19052&paneView=debug
- Log files:
  - x64: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-c7a674cf67d64b9980/System.IO.Pipes.Tests/1/console.c3192c0d.log?helixlogtype=result
  - arm64: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74926-merge-0416eef15c6a45a1a6/System.IO.Pipes.Tests/1/console.6615c06b.log?helixlogtype=result
- Callstacks:

Server:
```
[11:52:30] dbug: Exit code: 1
                 Std out:
                   Discovering: System.IO.Pipes.Tests (method display = ClassAndMethod, method display options = None)
                   Discovered:  System.IO.Pipes.Tests (found 99 of 502 test cases)
                   Starting:    System.IO.Pipes.Tests (parallel test collections = on, max threads = 8)
                       System.Net.Sockets.SocketException : Permission denied
                       Stack Trace:
                         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3650,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
                         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(788,0): at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
                         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(766,0): at System.Net.Sockets.Socket.Bind(EndPoint localEP)
                         /_/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.UnixDomainSockets.cs(41,0): at System.IO.Pipes.Tests.NamedPipeTest_UnixDomainSockets.NamedPipeClient_Connects_With_UnixDomainSocketEndPointServer()
                         --- End of stack trace from previous location ---
```

Client:
```
                       System.Net.Sockets.SocketException : Permission denied
                       Stack Trace:
                         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3650,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
                         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(788,0): at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
                         /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(766,0): at System.Net.Sockets.Socket.Bind(EndPoint localEP)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs(331,0): at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs(279,0): at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs(44,0): at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs(84,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
                         /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.cs(40,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
                         /_/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.UnixDomainSockets.cs(20,0): at System.IO.Pipes.Tests.NamedPipeTest_UnixDomainSockets.NamedPipeServer_Connects_With_UnixDomainSocketEndPointClient()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```
Summary:
```
                   Finished:    System.IO.Pipes.Tests
                 === TEST EXECUTION SUMMARY ===
                    System.IO.Pipes.Tests  Total: 141, Errors: 0, Failed: 2, Skipped: 0, Time: 1.943s
                 
                 
                 Std err:
                     System.IO.Pipes.Tests.NamedPipeTest_UnixDomainSockets.NamedPipeClient_Connects_With_UnixDomainSocketEndPointServer [FAIL]
                     System.IO.Pipes.Tests.NamedPipeTest_UnixDomainSockets.NamedPipeServer_Connects_With_UnixDomainSocketEndPointClient [FAIL]
```

**Comment by steveisok** [comment]
These tests were disabled in main and need backported.

**Comment by carlossanlop** [comment]
@steveisok I noticed you disabled them directly in 7.0. Did they get disabled in main too? If yes, then this issue can be closed.
