### ISSUE TITLE
ubsan detects null this when calling a member function in the GC

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#75034]
### Description

Running on large core count ARM64, ubuntu 22.04 a "binary tree" memory consumer, the ubsan runtime detects a null-pointer used as a this pointer for a member call.

Running with the runtime compiled with gcc12 -O3 -fsanitize=undefined (eg the ubsan) Compiling near main/head on sha 7a45201181d37329b7ab0bee541ed7c42b5d94b6

Running the program kunal_gc (source attached).
Running with this invocation (where the single argument "26" means make a binary tree of depth 26, eg, huge)

```
UBSAN_OPTIONS=halt_on_error=0,print_stacktrace=1,use_sigaltstack=false,suppressions=/home/robhenry/git-work-e2/robhenry-perf/dotnet_build/ubsan.supp \
        ASAN_OPTIONS=halt_on_error=0,alloc_dealloc_mismatch=0 \
        TSAN_OPTIONS=halt_on_error=0,force_seq_cst_atomics=1,verbosity=0,suppressions=/home/robhenry/git-work-e2/robhenry-perf/dotnet_build/tsan.supp \
        LSAN_OPTIONS=verbosity=1:log_threads=1 \
        \
        DOTNET_gcServer="1" \
        DOTNET_GCNoAffinitize=0 \
        DOTNET_Thread_UseAllCpuGroups=1 \
        DOTNET_GCCpuGroup=1 \
        DOTNET_GCHeapCount=4 \
        \
        gdb --args \
          ../dotnet_load/kunal_gc/bin/Release/net7.0/linux-arm64/kunal_gc \
            26 \

```
where ubsan.supp is attached in a zip

the ubsan runtime runs a procedure that gdb has a breakpoint on it, and here's the backtrace.  pGenGCHeap is indeed null.

```
mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/gc/gc.cpp:46048:43: runtime error: member call on null pointer of type 'struct gc_heap'

Thread 1 "kunal_gc" hit Breakpoint 1, __ubsan::ScopedReport::~ScopedReport (this=this@entry=0xffffffffda30, __in_chrg=<optimized out>) at ../../../../src/libsanitizer/ubsan/ubsan_diag.cpp:388
388	../../../../src/libsanitizer/ubsan/ubsan_diag.cpp: No such file or directory.
(gdb) up
#1  0x0000fffff794a950 in handleTypeMismatchImpl (Data=Data@entry=0xfffff63d8b48, Pointer=Pointer@entry=0, Opts=...)
    at ../../../../src/libsanitizer/ubsan/ubsan_handlers.cpp:137
137	../../../../src/libsanitizer/ubsan/ubsan_handlers.cpp: No such file or directory.
(gdb) 
#2  0x0000fffff794b414 in __ubsan::__ubsan_handle_type_mismatch_v1 (Data=Data@entry=0xfffff63d8b48, Pointer=Pointer@entry=0)
    at ../../../../src/libsanitizer/ubsan/ubsan_handlers.cpp:142
142	in ../../../../src/libsanitizer/ubsan/ubsan_handlers.cpp
(gdb) 
#3  0x0000fffff51c5958 in SVR::GCHeap::GarbageCollect (this=0xaaaaaaba0a60, generation=<optimized out>, low_memory_p=<optimized out>, mode=2)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/gc/gc.cpp:46048
46048	            pGenGCHeap->background_gc_wait();
(gdb) print pGenGCHeap
$1 = (SVR::gc_heap *) 0x0
```
[robhenry_gc_files.zip](https://github.com/dotnet/runtime/files/9481352/robhenry_gc_files.zip)

### Reproduction Steps

see above

### Expected behavior

no ubsan runtime errors

### Actual behavior

observed ubsan runtime errors

### Other information

/cc @maoni

**Comment by RobertHenry6bev** [comment]
Same fault is detected when all of dotnet/runtime is built using other compilers:

- clang-14 -O3
- clang-14 -O0
- clang-11 -O0

**Comment by RobertHenry6bev** [comment]
Here's more state from gdb.

```
info threads
(gdb) info  threads
  Id   Target Id                                            Frame 
  1    Thread 0xfffff7ff3460 (LWP 347113) "kunal_gc"        __ubsan::ScopedReport::~ScopedReport (this=this@entry=0xffffffffcdc0, 
    __in_chrg=<optimized out>) at ../../../../src/libsanitizer/ubsan/ubsan_diag.cpp:388
  2    Thread 0xfffff425f0c0 (LWP 347116) "kunal_gc-ust"    syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
  3    Thread 0xfffff3a4f0c0 (LWP 347117) "kunal_gc-ust"    syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
  4    Thread 0xfffff323f0c0 (LWP 347118) "kunal_gc"        0x0000fffff751bc78 in __GI___poll (fds=0xfffff323e290, nfds=1, 
    timeout=<optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:41
  5    Thread 0xfffff2a2f0c0 (LWP 347119) "kunal_gc"        0x0000fffff751bc78 in __GI___poll (fds=0xffffe8000b70, nfds=1, 
    timeout=<optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:41
  6    Thread 0xfffff181f0c0 (LWP 347120) "kunal_gc"        0x0000fffff751790c in __libc_open64 (
    file=0xaaaaaac8684c "/tmp/clr-debug-pipe-347113-9441029-in", oflag=<optimized out>) at ../sysdeps/unix/sysv/linux/open64.c:41
  7    Thread 0xfffff100f0c0 (LWP 347121) "kunal_gc"        __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xaaaaaac91ee8) at ./nptl/futex-internal.c:57
  8    Thread 0xfffff02f20c0 (LWP 347122) ".NET Server GC"  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xaaaaaaca095c) at ./nptl/futex-internal.c:57
  9    Thread 0xfffff023d0c0 (LWP 347123) ".NET Server GC"  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xaaaaaaca842c) at ./nptl/futex-internal.c:57
  10   Thread 0xfffff01880c0 (LWP 347124) ".NET Server GC"  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xaaaaaacafef8) at ./nptl/futex-internal.c:57
  11   Thread 0xfffff00d30c0 (LWP 347125) ".NET Server GC"  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xaaaaaacb79c8) at ./nptl/futex-internal.c:57
  12   Thread 0xffffa2d300c0 (LWP 347126) ".NET Finalizer"  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0xffffa2d2e598, 
    op=137, expected=0, futex_word=0xaaaaaacbb108) at ./nptl/futex-internal.c:57
  14   Thread 0xff81050af0c0 (LWP 347128) "kunal_gc"        __GI___libc_read (nbytes=1, buf=0xff81050ae7c7, fd=<optimized out>)
    at ../sysdeps/unix/sysv/linux/read.c:26
  15   Thread 0xff81074f10c0 (LWP 347130) ".NET BGC"        0x0000fffff58ac9a8 in SVR::gc_heap::background_mark1 (this=0xaaaaaac9ae90, 
    o=0xff827e9b7f60 "\030.\003\245\377\377") at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/gc/gc.cpp:23510
* 16   Thread 0xff80e79be0c0 (LWP 347131) ".NET BGC"        __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xff81000039cc) at ./nptl/futex-internal.c:57
  17   Thread 0xff80e71ae0c0 (LWP 347132) ".NET BGC"        __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xff81000053dc) at ./nptl/futex-internal.c:57
  18   Thread 0xff80e699e0c0 (LWP 347133) ".NET BGC"        __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, 
    expected=0, futex_word=0xff8100006de8) at ./nptl/futex-internal.c:57
  19   Thread 0xff80e618e0c0 (LWP 347142) ".NET Tiered Com" __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0xff80e618cd18, 
    op=137, expected=0, futex_word=0xaaaaaacc5998) at ./nptl/futex-internal.c:57
```

Picking one of the BGC threads stuck in futex:

```
57	in ./nptl/futex-internal.c
(gdb) where
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0xaaaaaaca095c)
    at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0xaaaaaaca095c)
    at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0xaaaaaaca095c, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x0000fffff74bc8fc in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0xaaaaaaca0900, cond=0xaaaaaaca0930)
    at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0xaaaaaaca0930, mutex=0xaaaaaaca0900) at ./nptl/pthread_cond_wait.c:627
#5  0x0000fffff65668a8 in CorUnix::CPalSynchronizationManager::ThreadNativeWait (ptnwdNativeWaitData=0xaaaaaaca0900, 
    dwTimeout=4294967295, ptwrWakeupReason=0xfffff02f0cc4, pdwSignaledObject=0xfffff02f0cc0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/pal/src/synchmgr/synchmanager.cpp:478
#6  0x0000fffff65662d0 in CorUnix::CPalSynchronizationManager::BlockThread (this=0xaaaaaab6d860, pthrCurrent=0xaaaaaaca0750, 
    dwTimeout=4294967295, fAlertable=false, fIsSleep=false, ptwrWakeupReason=0xfffff02f0fe8, pdwSignaledObject=0xfffff02f0ff4)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/pal/src/synchmgr/synchmanager.cpp:301
#7  0x0000fffff6587234 in CorUnix::InternalWaitForMultipleObjectsEx (pThread=0xaaaaaaca0750, nCount=1, lpHandles=0xfffff02f1150, 
    bWaitAll=0, dwMilliseconds=4294967295, bAlertable=0, bPrioritize=0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/pal/src/synchmgr/wait.cpp:637
#8  0x0000fffff6587680 in WaitForSingleObjectEx (hHandle=0x74, dwMilliseconds=4294967295, bAlertable=0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/pal/src/synchmgr/wait.cpp:138
#9  0x0000fffff5f9cc5c in CLREventWaitHelper2 (handle=0x74, dwMilliseconds=4294967295, alertable=0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/synch.cpp:372
#10 0x0000fffff5f9c960 in CLREventWaitHelper(void*, unsigned int, int)::$_1::operator()(CLREventWaitHelper(void*, unsigned int, int)::Param*) const (this=0xfffff02f1287, pParam=0xfffff02f1290) at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/synch.cpp:397
#11 0x0000fffff5f9b0f0 in CLREventWaitHelper (handle=0x74, dwMilliseconds=4294967295, alertable=0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/synch.cpp:399
#12 0x0000fffff5f9afd0 in CLREventBase::WaitEx (this=0xaaaaaac973d0, dwMilliseconds=4294967295, mode=WaitMode_None, syncState=0x0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/synch.cpp:466
#13 0x0000fffff5f9aef0 in CLREventBase::Wait (this=0xaaaaaac973d0, dwMilliseconds=4294967295, alertable=0, syncState=0x0)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/synch.cpp:412
#14 0x0000fffff5c8b9e4 in GCEvent::Impl::Wait (this=0xaaaaaac973d0, timeout=4294967295, alertable=false)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/gcenv.os.cpp:1327
#15 0x0000fffff5c8ac74 in GCEvent::Wait (this=0xfffff6e551c8 <SVR::gc_heap::ee_suspend_event>, timeout=4294967295, alertable=false)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/gcenv.os.cpp:1405
#16 0x0000fffff5842be4 in SVR::gc_heap::gc_thread_function (this=0xaaaaaac9ae90)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/gc/gc.cpp:6758
#17 0x0000fffff5842b3c in SVR::gc_heap::gc_thread_stub (arg=0xaaaaaac9ae90)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/gc/gc.cpp:33870
#18 0x0000fffff5c89320 in (anonymous namespace)::CreateNonSuspendableThread(void (*)(void*), void*, char16_t const*)::$_1::operator()(void*) const (
    this=0xfffff5c89178 <(anonymous namespace)::CreateNonSuspendableThread(void (*)(void*), void*, char16_t const*)::$_1::__invoke(void*)>, argument=0xffffffffd238) at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/gcenv.ee.cpp:1476
#19 0x0000fffff5c89194 in (anonymous namespace)::CreateNonSuspendableThread(void (*)(void*), void*, char16_t const*)::$_1::__invoke(void*)
    (argument=0xffffffffd238) at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/vm/gcenv.ee.cpp:1461
#20 0x0000fffff65a5434 in CorUnix::CPalThread::ThreadEntry (pvParam=0xaaaaaaca0750)
    at /mnt/robhenry/dotnet/clang11.a/runtime/src/coreclr/pal/src/thread/thread.cpp:1829
#21 0x0000fffff74bd5c8 in start_thread (arg=0x0) at ./nptl/pthread_create.c:442
#22 0x0000fffff7525d1c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79

```

**Comment by cshung** [comment]
Thanks for filing the issue.

This is not a real reliability issue though. The tool is just detecting a case where `gc.cpp` is abusing the language.

We would like to write a single line of code that works for both server GC (aka `#define MULTIPLE_HEAPS`) (where there are multiple instances of the `gc_heap` object and the `background_gc_wait` function is a real member function) and for workstation GC (where there is no instance of `gc_heap` object and the `background_gc_wait` function is static.

The way we did that is in the server GC case, `pGenGCHeap` is the right `gc_heap` object instance and `background_gc_wait` is a member function, and in the workstation case `pGenGCHeap` is null and `background_gc_wait` is a static function. 

C++ seems to happily allow us to write `Class c = null; c->staticMethodOnClass()` to call a static method on the class, and so we used that to allow us to write a single line for both cases.

In fact, not just `background_gc_wait`, we call every `PER_HEAP` member the same way, the tool is likely to detect a lot of false positives.

Is it possible to silence this particular rule? If `null` is used to call a static method, let it go.

**Comment by AaronRobinsonMSFT** [comment]
>  the tool is likely to detect a lot of false positives.

This isn't a false positive. it is undefined behavior, this is alluded to in the following statement:

> The tool is just detecting a case where gc.cpp is abusing the language.

Right, it is abuse that triggers undefined behavior which can potentially cause a compiler to do unexpected things. I'd recommend not abusing the language here and instead making a single static function that accepts an instance and either calling the member on the instance or using the static as the impl if impl is `null` or in workstation GC. The code, as written, elicits undefined behavior and should be reconsidered.

**Comment by jkotas** [comment]
The GC has `pGenGCHeap` defined as:
```
#ifdef MULTIPLE_HEAPS
    gc_heap*    pGenGCHeap;
#else
    #define pGenGCHeap ((gc_heap*)0)
#endif //MULTIPLE_HEAPS
```
This problem affect all 100+ places where this define is used. Can we replace the `pGenGCHeap` macro with a different macro that avoids the null this pointer? Something like:
```
#ifdef MULTIPLE_HEAPS
    #define heap_ref(hp) hp->
#else
    #define heap_ref(hp) gc_heap::
#endif
```

Current code:
```
#ifdef MULTIPLE_HEAPS
    for (int hn = 0; hn < gc_heap::n_heaps; hn++)
    {
        gc_heap* hp = gc_heap::g_heaps[hn];
#else //MULTIPLE_HEAPS
    {
        gc_heap* hp = pGenGCHeap;
#endif //MULTIPLE_HEAPS
        total_estimated_reclaim += heap_ref(hp) estimated_reclaim (gen_number);
    }
```
New code:
```
#ifdef MULTIPLE_HEAPS
    for (int hn = 0; hn < gc_heap::n_heaps; hn++)
    {
        gc_heap* hp = gc_heap::g_heaps[hn];
#else //MULTIPLE_HEAPS
    {
#endif //MULTIPLE_HEAPS
        total_estimated_reclaim += heap_ref(hp) estimated_reclaim (gen_number);
    }
```

> instead making a single static function that accepts an instance and either calling the member on the instance 

This would likely introduce a measurable performance hit once done on all 100+ effected places.

**Comment by RobertHenry6bev** [comment]
Which ISA was the "measurable impact" on register allocation noted?

**Comment by jkotas** [comment]
x86/x64. It was years ago.

**Comment by AaronRobinsonMSFT** [comment]
> > instead making a single static function that accepts an instance and either calling the member on the instance

> It would likely introduce a measurable performance hit once done on all 100+ effected places. Passing the unnecessary this pointer around had measurable impact on register allocation and it is why this hack was introduced.

I'd prefer the other abstraction, but if there was measurable impact, especially in the GC, that approach would also work.

**Comment by RobertHenry6bev** [comment]
The bulk of the responses seem to imply that this situation is fortunately harmless, since we are running workstation gc.  But note that my environment has         DOTNET_gcServer="1"  and I'm asking for 4 heaps.

**Comment by AntonLapounov** [comment]
I agree with @RobertHenry6bev that the issue has nothing to do with the definition of `pGenGCHeap` as you can spot the `SVR::` prefix in the call stacks above.

> This isn't a false positive. it is undefined behavior,

It is not if I am reading [this](https://en.cppreference.com/w/cpp/language/static) correctly:
> To refer to a static member m of class T, two forms may be used: qualified name T::m or member access expression E.m or E->m, where E is an expression that evaluates to T or T* respectively.

**Comment by AaronRobinsonMSFT** [comment]
> > This isn't a false positive. it is undefined behavior,

> It is not if I am reading [this](https://en.cppreference.com/w/cpp/language/static) correctly:

> > To refer to a static member m of class T, two forms may be used: qualified name T::m or member access expression E.m or E->m, where E is an expression that evaluates to T or T* respectively.

I agree you are reading that correctly. I was not aware of this permission and given the warning assumed it was UB. Seems I was wrong here. Thanks for pointing this out @AntonLapounov.

> I agree with @RobertHenry6bev that the issue has nothing to do with the definition of pGenGCHeap as you can spot the SVR:: prefix in the call stacks above.

So are we missing the underlying issue that was triggered here? I've not run this scenario locally yet.

**Comment by AaronRobinsonMSFT** [comment]
Following the supplied link uncovered the primary source for what I had always considered UB - https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_closed.html#315. Calling a static method through the `.` was/is weird but I've always accepted as valid. However, calling via `p->` when `p` is `nullptr` was what I thought was UB, the link does confirm it is valid.

**Comment by janvorli** [comment]
The comments indicate that the issue is actually some intermittent issue rather than an undefined behavior code bug (as it was running with server GC where the `pGenGCHeap` cannot be NULL unless there is some race or memory corruption. May be a race exposed by the ubsan instrumentation or a bug in the ubsan instrumentation.

**Comment by RobertHenry6bev** [comment]
I wrote a tool that ran on linux and macosx that consumed the standard build output, and from that generated a huge makefile, where every .o was compiled with the same set of instrumentation flags.  This approach to compilation maybe needed before the issue I pointed out surfaces.  Or not. (See my note where all 2400 .o files in the dotnet runtime could be recompiled in < 1 minute.) While I haven't looked in 3 years, I suspect building for linux is still a hodge podge of makefiles, autotools, bash and python scripts.
