### ISSUE TITLE
[Mono] Behavior difference between optimized and non-optimized build

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#75125]
While working on https://github.com/dotnet/runtime/pull/75012 I have encountered something that seems to be a Mono Runtime bug (the code is working fine with CLR). It's reproducible only for **Release** builds.

You can find the repro in the details below:

<details>

```cs
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;
using Xunit;

namespace System.Buffers.Text.Tests
{
    public class IndexOfTests
    {
        [Fact]
        public void Repro()
        {
            Assert.Equal(0, IndexOfIgnoreCase(Encoding.ASCII.GetBytes("tESt"), Encoding.ASCII.GetBytes("TesT")));
            Assert.Equal(0, IndexOfIgnoreCase(Encoding.ASCII.GetBytes("tESt"), Encoding.ASCII.GetBytes("")));
        }

        public static int IndexOfIgnoreCase(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value)
            => IndexOfIgnoreCaseByte(text, value);

        private static int IndexOfIgnoreCaseByte(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value)
        {
            if (value.IsEmpty)
            {
                return 0;
            }
            else if (value.Length > text.Length)
            {
                return -1;
            }

            byte firstValue = value[0];
            if (firstValue > 127)
            {
                throw new ArgumentException("SR.Arg_ContainsNonAscii", nameof(value));
            }
            byte valueHead = Unsafe.As<byte, byte>(ref firstValue);
            char differentCase = GetDifferentCaseOrSame(Unsafe.As<byte, char>(ref firstValue));
            byte valueHeadDifferentCase = Unsafe.As<char, byte>(ref differentCase);

            int valueTailLength = value.Length - 1;
            if (valueTailLength == 0)
            {
                return MemoryExtensions.IndexOfAny(text, valueHead, valueHeadDifferentCase); // for single-byte values use plain IndexOf
            }

            int searchSpaceMinusValueTailLength = text.Length - valueTailLength;
            int offset = 0;
            int remainingSearchSpaceLength = searchSpaceMinusValueTailLength;

            while (remainingSearchSpaceLength > 0)
            {
                // Do a quick search for the first element of "value".
                int relativeIndex = MemoryExtensions.IndexOfAny(text.Slice(offset), valueHead, valueHeadDifferentCase);
                if (relativeIndex < 0)
                    break;

                remainingSearchSpaceLength -= relativeIndex;
                offset += relativeIndex;

                if (remainingSearchSpaceLength <= 0)
                    break;  // The unsearched portion is now shorter than the sequence we're looking for. So it can't be there.

                // Found the first element of "value". See if the tail matches.
                if (SequenceEqualIgnoreCaseByte(text.Slice(offset, value.Length), value)) // Map throws if non-ASCII char is found in value
                    return offset;  // The tail matched. Return a successful find.

                remainingSearchSpaceLength--;
                offset++;
            }

            return -1;
        }

        private static char GetDifferentCaseOrSame(char c)
            => char.IsAsciiLetterLower(c) ? (char)(c + 'A' - 'a') : char.IsAsciiLetterUpper(c) ? (char)(c - 'A' + 'a') : c;

        private static bool SequenceEqualIgnoreCaseByte(ReadOnlySpan<byte> text, ReadOnlySpan<byte> value)
        {
            Debug.Assert(text.Length == value.Length);

            for (int i = 0; i < text.Length; i++)
            {
                uint valueA = text[i];
                uint valueB = value[i];

                if (valueA == valueB)
                {
                    continue; // exact match
                }

                valueA |= 0x20u;
                if ((uint)(valueA - 'a') > (uint)('z' - 'a'))
                {
                    return false; // not exact match, and first input isn't in [A-Za-z]
                }

                if (valueA != (valueB | 0x20u))
                {
                    return false;
                }
            }

            return true;
        }
    }
}
```

You can add it to `src\libraries\System.Memory\tests\System.Memory.Tests.csproj` and run following command:

```cmd
.\build.cmd -c Release -subset mono+libs+libs.tests
.\dotnet.cmd build .\src\libraries\System.Memory\tests\System.Memory.Tests.csproj /t:Test /p:XunitMethodName=System.Buffers.Text.Tests.IndexOfTests.Repro /p:Configuration=Release
```

```log
D:\projects\runtime\.dotnet
MSBuild version 17.4.0-preview-22368-02+c8492483a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Microsoft.Interop.SourceGeneration -> D:\projects\runtime\artifacts\bin\Microsoft.Interop.SourceGeneration\Release\netstandard2.0\Microsoft.Interop.SourceGeneration.dll
  LibraryImportGenerator -> D:\projects\runtime\artifacts\bin\LibraryImportGenerator\Release\netstandard2.0\Microsoft.Interop.LibraryImportGenerator.dll
  TestUtilities -> D:\projects\runtime\artifacts\bin\TestUtilities\Release\net6.0\TestUtilities.dll
  System.Memory.Tests -> D:\projects\runtime\artifacts\bin\System.Memory.Tests\Release\net7.0\System.Memory.Tests.dll
  ----- start Tue 09/06/2022 15:19:26.61 ===============  To repro directly: =====================================================
  pushd D:\projects\runtime\artifacts\bin\System.Memory.Tests\Release\net7.0\
  "D:\projects\runtime\artifacts\bin\testhost\net7.0-windows-Release-x64\dotnet.exe" exec --runtimeconfig System.Memory.Tests.runtimeconfig.json --depsfile System.Memory.Tests.deps.json xunit.console.dll System.Memory.Tests.dll -xml te
  stResults.xml -nologo -method System.Buffers.Text.Tests.IndexOfTests.Repro -notrait category=OuterLoop -notrait category=failing
  popd
  ===========================================================================================================
    Discovering: System.Memory.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Memory.Tests (found 1 of 2460 test case)
    Starting:    System.Memory.Tests (parallel test collections = on, max threads = 24)
      System.Buffers.Text.Tests.IndexOfTests.Repro [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   -1
        Stack Trace:
          D:\projects\runtime\src\libraries\System.Memory\tests\Ascii\IndexOfTests.cs(16,0): at System.Buffers.Text.Tests.IndexOfTests.Repro()
          D:\projects\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
    Finished:    System.Memory.Tests
  === TEST EXECUTION SUMMARY ===
     System.Memory.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.121s
```

</details>

cc @lateralusX @lambdageek

**Comment by lateralusX** [comment]
@adamsitnik Is this on main? What platform did you run on?

**Comment by adamsitnik** [comment]
> Is this on main?

@lateralusX It's in my branch (https://github.com/adamsitnik/runtime/tree/asciiAPIs), I've synced it with main 6 days ago. I am going to sync it again and re-try.

> What platform did you run on?

For the CI it was failing for macOS and Linux x64, I was able to repro it on Windows x64.

**Comment by lateralusX** [comment]
OK, I can take a look tomorrow on Windows x64 to see if I can spot something.

**Comment by lateralusX** [comment]
Can I just run the test above on main or do I need more stuff from your branch?

**Comment by adamsitnik** [comment]
@lateralusX I've synced my fork with main and it still reproduces.

> Can I just run the test above on main or do I need more stuff from your branch?

You can either clone my fork and remove the following line:

https://github.com/dotnet/runtime/blob/8ab53c2fcca300c26dfde79d8b4af09fee9206d3/src/libraries/System.Memory/tests/Ascii/IndexOfTests.cs#L11

Or copy-paste the code I've provided in https://github.com/dotnet/runtime/issues/75125#issue-1363297554 and just run it (it's a full repro).

**Comment by SamMonoRT** [comment]
@lateralusX @adamsitnik  -- please can you verify if this happens on 7.0 release RC1 and determine if the fix needs to be backported ?

**Comment by lateralusX** [comment]
Looks like I at least was able to reproduce it on release/7.0 branch Windows x64.

**Comment by lateralusX** [comment]
I have isolated the area under debugger and currently debugging the codegen related to a specific construct, need to continue digging tomorrow.

**Comment by lateralusX** [comment]
So the issue seems to be located to this:

```
byte valueHead = Unsafe.As<byte, byte>(ref firstValue);
char differentCase = GetDifferentCaseOrSame(Unsafe.As<byte, char>(ref firstValue));
```

and it will translate to the following assembler:

```
0000026EBF80A34B 0F B6 85 E8 FE FF FF movzx       eax,byte ptr [rbp-118h]  
0000026EBF80A352 40 88 85 E0 FE FF FF mov         byte ptr [rbp-120h],al  
0000026EBF80A359 0F B7 8D E8 FE FF FF movzx       ecx,word ptr [rbp-118h]  
0000026EBF80A360 48 8D 64 24 00       lea         rsp,[rsp]  
0000026EBF80A365 90                   nop  
0000026EBF80A366 49 BB 90 BE 80 BF 6E 02 00 00 mov         r11,26EBF80BE90h  
0000026EBF80A370 41 FF D3             call        r11 
```

`Unsafe.As<byte, char>(ref firstValue)`

will incorrectly be generated as a word load into eax, but should just be a byte load that should be casted to a char. Need to look into how we lower that and where it makes incorrect assumptions.

**Comment by lateralusX** [comment]
So the same thing happens in a simple expression like this:

```
byte firstValue = 68;
char firstValueAsChar = Unsafe.As<byte, char>(ref firstValue);
```

so our intrinsic implementation in Mono will just return the input ref firstValue as the output of the function (internally handled as a System.IntPtr) and then the next instruction loads the value from that pointer, but since the load IL is loading a char, it will read two bytes from the pointer. Reading up on the documentation of Unsafe.As on the other hand, it says (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.as?view=net-6.0):

_This API is conceptually similar to C++'s reinterpret_cast<>. It is the caller's responsibility to ensure that the cast is legal. No runtime check will be performed._

So that would imply that runtime should work the way it does, since if it should resemble reinterpret_cast<> it will cast a byte * to a short * and then the code would read directly from that short * and that would give you the same behavior, reading two bytes from source interpreted as a short.

@adamsitnik so not sure runtime should really behave any different in this case, maybe you should cast to the right type without going through Unsafe? CoreCLR probably detect this case (since it works there), but not really sure if that is the required behavior. It works on Mono when using Debug build since the stack looks different, so the value is written to a section where you have 0x00, meaning the upper byte read is 0x00 giving you the right char value.

We could of course fix our Unsafe.As<TFrom,TTo> (ref TFrom source) to be more forgiving in case you cast to a bigger type and that will imply a temporary store, widening the value to the expected size, and then return the reference to that location.

@vargaz @lambdageek, thoughts?

**Comment by lambdageek** [comment]
> @vargaz @lambdageek, thoughts?

I bet it works on CoreCLR due to some accident of alignment or something.

I think this should probably just use a normal C# cast `(char)firstValue`

**Comment by adamsitnik** [comment]
> Is it possible to move away using Unsafe.As for byte -> char and use regular C# cast in this case?

@lateralusX I've moved away from using `Unsafe.As`: https://github.com/dotnet/runtime/pull/75012/commits/61066590fec7809c1168d88396839d69fd91a52c

Big thanks for your help and apologies for creating an issue that was not an actual bug.
