### ISSUE TITLE
Out of bounds array access in GC

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#75214]
When GCHeapHardLimit configuration is set, there's an out of bounds access in `gc_heap::virtual_commit` when `h_number == -1`.

When `heap_hard_limit > 0` and `bucket >= total_oh_count` and `h_number == -1`, the array access on https://github.com/dotnet/runtime/blob/426d9d2704b145eb9aab5ac4a19e89e4e72d4149/src/coreclr/gc/gc.cpp#L6913 can go out of bounds.

This was found while running the `JIT/Methodical/Methodical_others` test suite with a GC Heap Hard Limit of 0xc800000.

<details>
<summary>AddressSanitizer Report</summary>

```
=================================================================
==554148==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7ffd7713aca0 at pc 0x7ffd738ab9bd bp 0x00dcc237d1c0 sp 0x00dcc237d1c8
READ of size 8 at 0x7ffd7713aca0 thread T0
    #0 0x7ffd738ab9bc in WKS::gc_heap::virtual_commit(void *, unsigned __int64, int, int, bool *) E:\source\runtime\src\coreclr\gc\gc.cpp:6913
    #1 0x7ffd738643a9 in WKS::gc_heap::inplace_commit_card_table(unsigned char *, unsigned char *) E:\source\runtime\src\coreclr\gc\gc.cpp:8827
    #2 0x7ffd73869eb3 in WKS::gc_heap::make_card_table(unsigned char *, unsigned char *) E:\source\runtime\src\coreclr\gc\gc.cpp:8891
    #3 0x7ffd73863689 in WKS::gc_heap::initialize_gc(unsigned __int64, unsigned __int64, unsigned __int64) E:\source\runtime\src\coreclr\gc\gc.cpp:13521
    #4 0x7ffd7380c169 in WKS::GCHeap::Initialize(void) E:\source\runtime\src\coreclr\gc\gc.cpp:44926
    #5 0x7ffd74024b63 in EEStartupHelper(void) E:\source\runtime\src\coreclr\vm\ceemain.cpp:889
    #6 0x7ffd74029e91 in `EEStartup'::`9'::__Body::Run E:\source\runtime\src\coreclr\vm\ceemain.cpp:1070
    #7 0x7ffd74023930 in EEStartup(void) E:\source\runtime\src\coreclr\vm\ceemain.cpp:1072
    #8 0x7ffd740252de in EnsureEEStarted(void) E:\source\runtime\src\coreclr\vm\ceemain.cpp:308
    #9 0x7ffd72537ace in CorHost2::Start(void) E:\source\runtime\src\coreclr\vm\corhost.cpp:100
    #10 0x7ffd740403bb in coreclr_initialize E:\source\runtime\src\coreclr\dlls\mscoree\exports.cpp:251
    #11 0x7ff7e7b933cf in run E:\source\runtime\src\coreclr\hosts\corerun\corerun.cpp:348
    #12 0x7ff7e7b9debd in wmain E:\source\runtime\src\coreclr\hosts\corerun\corerun.cpp:563
    #13 0x7ff7e7c14c58 in invoke_main C:\repos\msvc\src\vctools\crt\vcstartup\src\startup\exe_common.inl:90
    #14 0x7ff7e7c14b7d in __scrt_common_main_seh C:\repos\msvc\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #15 0x7ff7e7c14a3d in __scrt_common_main C:\repos\msvc\src\vctools\crt\vcstartup\src\startup\exe_common.inl:330
    #16 0x7ff7e7c14ccd in wmainCRTStartup C:\repos\msvc\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp:16
    #17 0x7ffe374f54df  (C:\WINDOWS\System32\KERNEL32.DLL+0x1800154df)
    #18 0x7ffe38be485a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x18000485a)

0x7ffd7713aca0 is located 8 bytes to the right of global variable 'WKS::gc_heap::heap_hard_limit_oh' defined in 'gc.cpp:2331:21' (0x7ffd7713ac80) of size 24
SUMMARY: AddressSanitizer: global-buffer-overflow E:\source\runtime\src\coreclr\gc\gc.cpp:6913 in WKS::gc_heap::virtual_commit(void *, unsigned __int64, int, int, bool *)
Shadow bytes around the buggy address:
  0x1225661a7540: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a7550: 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a7560: 04 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a7570: 04 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a7580: 01 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
=>0x1225661a7590: 00 00 00 f9[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a75a0: 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a75b0: 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a75c0: 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a75d0: 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x1225661a75e0: 04 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
```

</details>

**Comment by mangod9** [comment]
+ @cshung since he was validating hard limit within containers.
