### ISSUE TITLE
Test failure System.Xml.Tests.SubtreeReaderTest.RunTests(testCase: 105376: ReadBase64 runs into an Overflow)

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75231]
Run: [runtime-coreclr libraries-jitstress 20220907.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=6899&view=ms.vss-test-web.build-test-results-tab&runId=133004&resultId=149938&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- System.Xml.Tests.SubtreeReaderTest.RunTests(testCase: 105376: ReadBase64 runs into an Overflow)
```
**Error message:**
```
System.Xml.XmlException : '', hexadecimal value 0x01, is an invalid character. Line 1, position 239502.


Stack trace
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs:line 5594
   at System.Xml.XmlTextReaderImpl.ReadContentAsBinary(Byte[] buffer, Int32 index, Int32 count) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs:line 9450
   at System.Xml.XmlTextReaderImpl.ReadContentAsBase64(Byte[] buffer, Int32 index, Int32 count) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs:line 1619
   at System.Xml.XmlSubtreeReader.ReadContentAsBase64(Byte[] buffer, Int32 index, Int32 count) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlSubtreeReader.cs:line 887
   at System.Xml.Tests.CDataReader.ReadContentAsBase64(Byte[] array, Int32 offset, Int32 len) in /_/src/libraries/System.Private.Xml/tests/XmlReaderLib/CDataReader.cs:line 798
   at System.Xml.Tests.TCReadContentAsBase64.ReadBase64BufferOverflowWorksProperly() in /_/src/libraries/System.Private.Xml/tests/XmlReaderLib/ReadBase64.cs:line 545
   at OLEDB.Test.ModuleCore.CVariation.Execute() in /_/src/libraries/Common/tests/System/Xml/ModuleCore/cvariation.cs:line 76
   at OLEDB.Test.ModuleCore.CTestCase.<>c__DisplayClass7_1.<TestCases>b__0() in /_/src/libraries/Common/tests/System/Xml/ModuleCore/ctestcase.cs:line 131
   at OLEDB.Test.ModuleCore.XunitTestCase.Run() in /_/src/libraries/Common/tests/System/Xml/ModuleCore/XunitTestCase.cs:line 33
   at System.Xml.Tests.SubtreeReaderTest.RunTests(XunitTestCase testCase) in /_/src/libraries/System.Private.Xml/tests/Readers/SubtreeReader/SubtreeReaderTests.cs:line 15
   at InvokeStub_SubtreeReaderTest.RunTests(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jeffhandley** [comment]
We should address this test failure in main and consider a backport into the release/7.0 branch.
