### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesOutboundControlStream_ClientClosesConnection - Status code: Unknown (0xdde6f334)

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75270]
Affected test:
- **ServerClosesOutboundControlStream_ClientClosesConnection** - `System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesOutboundControlStream_ClientClosesConnection`

Day | Run | OS | Details
-- | -- | -- | --
9/6 | Rolling run [6173](https://runfo.azurewebsites.net/view/build/?number=6173) | net7.0-Linux-Release-x64-CoreCLR_release-(Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c78318f2006041a9bc/System.Net.Http.Functional.Tests.Attempt.3/2/console.5af0922f.log?%3Fhelixlogtype%3Dresult)

I couldn't find more occurrences on 9/8 when looking at [last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22system.net.http.functional.tests%20work%20item%22) in Runfo (they have different symptoms).

Error - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c78318f2006041a9bc/System.Net.Http.Functional.Tests.Attempt.3/2/console.5af0922f.log?%3Fhelixlogtype%3Dresult):
```
    System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesOutboundControlStream_ClientClosesConnection(graceful: False) [FAIL]
      Assert.IsType() Failure
      Expected: System.Net.Http.HttpProtocolException
      Actual:   System.Net.Quic.QuicException
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(39,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.AssertProtocolErrorAsync(Int64 errorCode, Func`1 task)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1640,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerClosesOutboundControlStream_ClientClosesConnection>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(128,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(92,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1644,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesOutboundControlStream_ClientClosesConnection(Boolean graceful)
        --- End of stack trace from previous location ---
      Output:
        System.Net.Http.HttpRequestException: An error occurred while sending the request.
         ---> System.Net.Quic.QuicException: An internal error has occurred. Status code: Unknown (0xdde6f334)
           at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 157
           at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 616
           at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 653
           at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 677
        --- End of stack trace from previous location ---
           at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 273
           at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 309
           at System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 837
           at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 356
           at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 323
           --- End of inner exception stack trace ---
           at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 323
           at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 323
           at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs:line 252
           at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs:line 252
           at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1004
           at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1160
           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 85
           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 558
           at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in /_/src/xunit.assert/Asserts/Record.cs:line 111
```

**Comment by karelz** [comment]
Triage: After @antonfirsov's changes we should not propagate QuicExeption -- this is weird, we should take a look.

**Comment by rzikm** [comment]
0xdde6f334 does not seem to be any QUIC Status code used in Linux, so this is highly suspicious.

**Comment by wfurt** [comment]
are there cases when the status is not errno @nibanks? 
Of course if any of the pointers is bogus we would parse invalid memory.

**Comment by nibanks** [comment]
I don't recognize the status code. Is this coming from stream shutdown event? If so, that means it's an application layer error code, not a platform/QUIC one.

**Comment by rzikm** [comment]
> I don't recognize the status code. Is this coming from stream shutdown event? If so, that means it's an application layer error code, not a platform/QUIC one.

We don't use such values in our tests.

Based on the callstack, the value is definitely coming from SHUTDOWN_COMPLETE.ConnectionCloseStatus (for app closure we throw different exception and the app error code comes from SHUTDOWN_COMPLETE.ConnectionErrorCode field).

It could mean that we still have some memory corruption going on :/

**Comment by ManickaP** [comment]
Triage: check occurrence, close if not happening anymore.

**Comment by rzikm** [comment]
Happens occasionally, and passes on reruns. none of the recent failures had any weird weird MsQuic return code. I think we can close this safely.
