### ISSUE TITLE
TimeZoneInfo.FindSystemTimeZoneById() is case-sensitive on Linux

### ISSUE THREAD

**Issue by SergeyRazmyslov** [dotnet/runtime#75275]
### Description

According to [official documentation](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.findsystemtimezonebyid?view=net-6.0#remarks) the passed time zone identifier argument in method `TimeZoneInfo.FindSystemTimeZoneById()` is case-insensitive on Linux. There is no issue on Windows.

For example, `var timezoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Standard Time");` works correctly on Linux, but `var timezoneInfo = TimeZoneInfo.FindSystemTimeZoneById("CENTRAL STANDARD TIME");` throws exception.

### Reproduction Steps

Call the `FindSystemTimeZoneById()` with upper-case time zone ID:
````
var timezoneInfo = TimeZoneInfo.FindSystemTimeZoneById("CENTRAL STANDARD TIME");
````

### Expected behavior

Correct instance of `TimeZoneInfo` for requested time zone ID.

### Actual behavior

```
Unhandled exception. System.TimeZoneNotFoundException: The time zone ID 'CENTRAL STANDARD TIME' was not found on the local computer.
 ---> System.IO.FileNotFoundException: Could not find file '/usr/share/zoneinfo/CENTRAL STANDARD TIME'.
File name: '/usr/share/zoneinfo/CENTRAL STANDARD TIME'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at TimezoneTestApp.Program.Main() in /home/sergei/projects/timezones/Program.cs:line 13
```

### Configuration

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.400/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by danmoseley** [comment]
Are IDs in the TZ info specified to be case sensitive? If so perhaps we do not want to match insensitively.

**Comment by tarekgh** [comment]
> Are IDs in the TZ info specified to be case sensitive? If so perhaps we do not want to match insensitively.

This is a good question but needs a more detailed answer. 

In .NET Framework when we support Windows only, we allowed using case-insensitive Ids. The reason is zone Ids are stored in the registry and we can read it using case-insensitive operation. Also, we cache the mapping from Ids to the time zone object using a case-insensitive dictionary. 
In .NET Core, when we started supporting other platforms the case insensitivity was partially working. I mean if you try to call `TimeZoneInfo.FindSystemTimeZoneById` early before enumerating all time zone on the system using `TimeZoneInfo.GetSystemTimeZones()`  and using not well case formed Id, we'll throw exception. The reason is because the zone data is stored as files on Linux/MacOS and we try to search for such file to get the zone data. As such OSs have case-sensitive file system, we'll fail to find it. But if calling `TimeZoneInfo.GetSystemTimeZones()` first, we enumerate all zone files and cache the result in the case-insensitive dictionary. This will make `TimeZoneInfo.FindSystemTimeZoneById` work even with not well case formed Ids. 

Now as we have started to support creating zone objects using IANA ids when running on Windows and creating zone objects using Windows Ids when running on Linux/MacOS, we are depending on the ICU library for the Id conversion. ICU is case-sensitive and therefore we fail the case mentioned in this issue. 

There is no standardization for zone Ids case sensitivity, but most platforms are case-sensitive. for example, Java 8 started to be case sensitive while before that it was case-insensitive as mentioned in the [stackoverflow post](https://stackoverflow.com/questions/33741934/java-timezone-ids-are-case-sensitive-or-platform-dependent#:~:text=FYI%20%2D%20In%20the%20general%20case,be%20treated%20as%20case%20sensitive.).

My thinking, usually users pick Ids from some source which always be in well-formed casing shape. Using not well-formed casing Ids is not the norm case. We may suggest and update the docs to ask users to ensure using well-formed Ids. Otherwise, we'll need to support but it will come with some perf cost. Here is a simple workaround can be used by the users who want to work with case insensitive Ids:

```C#
        private static readonly IEnumerable<TimeZoneInfo> s_timeZonesList = TimeZoneInfo.GetSystemTimeZones();

        public static TimeZoneInfo? GetTimeZoneInfoUsingCaseInsensitiveId(string zoneId)
        {
            foreach (TimeZoneInfo tz in s_timeZonesList)
            {
                string? id;

                if (tz.Id.Equals(zoneId, StringComparison.OrdinalIgnoreCase) ||
                    ((tz.HasIanaId ? TimeZoneInfo.TryConvertIanaIdToWindowsId(tz.Id, out id) : TimeZoneInfo.TryConvertWindowsIdToIanaId(tz.Id, out id)) &&
                    id.Equals(zoneId, StringComparison.OrdinalIgnoreCase)))
                {
                    return tz;
                }
            }

            return null;
        }
```

**Comment by Clockwork-Muse** [comment]
> My thinking, usually users pick Ids from some source which always be in well-formed casing shape.

Usually, harvested from the available tz files.

> Here is a simple workaround...

... if the application loaded the zones on startup because of the enumeration, wouldn't that mean that `TimeZoneInfo.FindSystemTimeZoneById()` would have them cached in a case-insensitive format?

**Comment by tarekgh** [comment]
> ... if the application loaded the zones on startup because of the enumeration, wouldn't that mean that TimeZoneInfo.FindSystemTimeZoneById() would have them cached in a case-insensitive format?

Yes, first the enumeration is expensive, but we cache it. Second, when requesting `TimeZoneInfo.FindSystemTimeZoneById` passing IANA id on Windows or passing Windows Id on Linux, this will not work if using case-insensitive format because at that time we call ICU for that and ICU not support case-insensitive Ids.

**Comment by osexpert** [comment]
What is weird is that the Id you ask for the first time is the Id you get back in the cached TimeZoneInfo (Win10\Net7):
```
var tz = TimeZoneInfo.FindSystemTimeZoneById("central STANDARD time");
// tz.Id = "central STANDARD time"
tz = TimeZoneInfo.FindSystemTimeZoneById("central standard time");
// tz.Id = "central STANDARD time"
tz = TimeZoneInfo.FindSystemTimeZoneById("CENTRAL STANDARD TIME");
// tz.Id = "central STANDARD time"
```
I guess it make sense, but its kind of fishy and not deterministic. It could be possible to "poison" the cache if you are the first one to ask for time zones and you use funny casing:-D
