### ISSUE TITLE
Error hot reloading new method in Blazor WebAssembly app

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#75324]
### Description

I get an error in the browser dev console when hot reloading a new method in a Blazor WebAssembly app.

### Reproduction Steps

- Create a new standalone Blazor WebAssembly app
- F5 to debug
- Add the following to Index.razor:

```
@code {
    void Test()
    {
        Console.WriteLine("Test()");
    }
}
```

- Apply changes to the running app

### Expected behavior

Changes applied without error

### Actual behavior

Error shows up in the browser dev console:

```
Error: [MONO] /__w/1/s/src/mono/mono/eglib/ghashtable.c:238 <disabled>
    at xe (dotnet.7.0.0-rc.1.22426.10.t7u94tgxh6.js:5:509)
    at Object.$e (dotnet.7.0.0-rc.1.22426.10.t7u94tgxh6.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.0-rc.1.22426.10.t7u94tgxh6.js:14:104923)
    at 009921e2:0x9a42
    at 009921e2:0xa581a
    at 009921e2:0x1bfbaf
    at 009921e2:0x1bfbe0
    at 009921e2:0x1bfc13
    at 009921e2:0x1bec19
    at 009921e2:0x5a62a
```

### Known Workarounds

The app seems to continue to successfully execute, so I haven't determined what negative impact this error has.

### Configuration

7.0.100-rc.1.22429.3
Windows 11
VS 17.4 P1

**Comment by danroth27** [comment]
@lambdageek

**Comment by lambdageek** [comment]
i'll take a look on monday

**Comment by lewing** [comment]
@danroth27 versions of everything please

cc @thaystg

**Comment by thaystg** [comment]
@lambdageek @lewing I have a local fix for this issue, I will open a PR soon.
