### ISSUE TITLE
Test failure JIT\\Performance\\CodeQuality\\Benchstones\\BenchI\\Fib\\Fib\\Fib.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75325]
Run: [runtime-coreclr crossgen2 20220907.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=8394&view=ms.vss-test-web.build-test-results-tab&runId=166882&resultId=102661&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\Performance\\CodeQuality\\Benchstones\\BenchI\\Fib\\Fib\\Fib.cmd
```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](https://dev.azure.com/dnceng-public/public/_build/results?buildId=8394&view=ms.vss-test-web.build-test-results-tab&runId=166882&resultId=102661&paneView=debug)
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

Return code:      1
Raw output file:      D:\h\w\B4880A71\w\A8370997\uploads\Reports\JIT.Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\Fib.output.txt
Raw output:
BEGIN EXECUTION
Fib.dll
1 file(s) copied.
0:53:47.46
Response file: D:\h\w\B4880A71\w\A8370997\e\JIT\Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\Fib.dll.rsp
D:\h\w\B4880A71\w\A8370997\e\JIT\Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\IL-CG2\Fib.dll
-o:D:\h\w\B4880A71\w\A8370997\e\JIT\Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\Fib.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B4880A71\p\System..dll
-r:D:\h\w\B4880A71\p\Microsoft..dll
-r:D:\h\w\B4880A71\p\mscorlib.dll
-r:D:\h\w\B4880A71\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B4880A71\p\crossgen2\crossgen2.dll" @"D:\h\w\B4880A71\w\A8370997\e\JIT\Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\Fib.dll.rsp"   -r:D:\h\w\B4880A71\w\A8370997\e\JIT\Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\IL-CG2*.dll"
0:53:54.79
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B4880A71\p
D:\h\w\B4880A71\w\A8370997\e\JIT\Performance\CodeQuality\Benchstones\BenchI\Fib\Fib\Fib.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Performance._CodeQuality_Benchstones_BenchI_Fib_Fib_Fib_._CodeQuality_Benchstones_BenchI_Fib_Fib_Fib_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by stephentoub** [comment]
Another here:
https://github.com/dotnet/runtime/pull/75303/checks?check_run_id=8259916750
https://dev.azure.com/dnceng-public/public/_build/results?buildId=9329&view=logs&jobId=e93c566c-b6be-5acb-6fc2-de2972d01fec&j=e93c566c-b6be-5acb-6fc2-de2972d01fec&t=2dc174be-b57a-56b6-9566-e621f39fb1f6

**Comment by AntonLapounov** [comment]
This is a duplicate of #75041.  The issue is fixed in current builds; however, we are still testing Preview 7 bits.
```
0:018> kc7
 # Call Site
00 coreclr!DacEnumerableHashTable<InstMethodHashTable,InstMethodHashEntry,4>::BaseFindNextEntryByHash
01 coreclr!InstMethodHashTable::FindMethodDesc
02 coreclr!InstantiatedMethodDesc::FindLoadedInstantiatedMethodDesc
03 coreclr!MethodDesc::FindOrCreateAssociatedMethodDesc
04 coreclr!MemberLoader::GetMethodDescFromMethodSpec
05 coreclr!CEEInfo::resolveToken
06 clrjit!Compiler::impResolveToken

0:018> lmvm coreclr
Browse full module list
start             end                 module name
00007ffb`00330000 00007ffb`0087e000   coreclr  C (private pdb symbols)  C:\ProgramData\dbg\sym\coreclr.pdb\2777C70D51C74D4A9E274FD651567CCB1\coreclr.pdb
    Loaded symbol image file: coreclr.dll
    Image path: D:\h\w\B4880A71\p\dotnet-cli\shared\Microsoft.NETCore.App\7.0.0-preview.7.22375.6\coreclr.dll
 ```

**Comment by mangod9** [comment]
Closing as dupe till we get a newer SDK drop.
