### ISSUE TITLE
[WASM] Anonymous pipes issue

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#75394]
In https://github.com/dotnet/BenchmarkDotNet/pull/2092 I wanted to use Anonymous Pipes for communication between Host and Benchmark process.

The idea was very simple. The host process (always a .NET console app) creates two anonymous pipes:

```cs
using AnonymousPipeServerStream inputFromBenchmark = new AnonymousPipeServerStream(PipeDirection.In, HandleInheritability.Inheritable);
using AnonymousPipeServerStream acknowledgments = new AnonymousPipeServerStream(PipeDirection.Out, HandleInheritability.Inheritable);
```

Starts a new process and provides the handles as strings:

```cs
string args = benchmarkId.ToArguments(inputFromBenchmark.GetClientHandleAsString(), acknowledgments.GetClientHandleAsString());
```

Then the benchmark process parses the ids, creates a `SafeFileHandle` from it and provides it to `FileStream` that is later used for reading/writing:

```cs
private Stream OpenAnonymousPipe(string fileHandle, FileAccess access)
{
    var sfh = new SafeFileHandle(new IntPtr(int.Parse(fileHandle)), ownsHandle: true);
    return new FileStream(sfh, access);
}
```

It works fine for .NET, .NET Framework on all OSes but not with WASM.

On Linux, I am getting following error when trying to perform first read/write:

```log
Error: Access to the path is denied.
    at $o (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:37754)
    at Ws (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:55546)
    at Object.b.javaScriptExports.call_entry_point (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:58159)
    at Object.Te [as runMain] (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:2713)
    at run (test-main.js:331:50)
Error: Access to the path is denied.
    at $o (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:37754)
    at Ws (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:55546)
    at Object.b.javaScriptExports.call_entry_point (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:58159)
    at Object.Te [as runMain] (/home/adam/projects/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/6030f12e-9262-45b4-8132-240f1ecaa9ea/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:2713)
    at run (test-main.js:331:50)
WASM EXIT 1
```

BenchmarkDotNet is using v8 to run the benchmarks (`v8 --expose_wasm test-main.js`).

@radical  @lambdageek @naricc @vargaz Have you ever faced similar issue with WASM or have any idea what could be going wrong?

Can v8 be internally staring another process with no handle inheritance for some kind of sandboxing?
Can Emscripten not support anonymous pipes by design (security?)?

I would really like to get it working and avoid having dedicated code path for WASM.

**Comment by vargaz** [comment]
v8/emscripten in general doesn't support communicating with the host machine except console output. So emitting structured output to the console and parsing it is a possible way to make (one way) communication work.

**Comment by adamsitnik** [comment]
> v8/emscripten in general doesn't support communicating with the host machine except console output.

@vargaz thanks!

**Comment by lambdageek** [comment]
@radical has done this in the context of the wasm app host he may have some suggestions about a robust approach
