### ISSUE TITLE
[wasm] `System.IO.MemoryMappedFiles.Tests` failing with `memory access out of bounds`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#75430]
Linux, interpreter - [rolling build on main](https://dev.azure.com/dnceng-public/public/_build/results?buildId=12016&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89&s=96ac2280-8cb4-5df5-99de-dd2da759617d), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-30d232de713f4aa383/WasmTestOnBrowser-System.IO.MemoryMappedFiles.Tests/1/console.8998763f.log?helixlogtype=result):

```
[21:25:30] info: Using random seed for collections: 1801439021
[21:25:30] info: Starting:    System.IO.MemoryMappedFiles.Tests.dll
[21:25:30] fail: RuntimeError: memory access out of bounds
                     at dlfree (dlfree (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9152]:0x1e0b6c))
                     at __munmap (__munmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9054]:0x1d7166))
                     at SystemNative_MUnmap (SystemNative_MUnmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8863]:0x1cb132))
                     at wasm_invoke_iil (wasm_invoke_iil (http://127.0.0.1:37767/dotnet.wasm:wasm-function[176]:0xc2a3))
                     at interp_exec_method (interp_exec_method (http://127.0.0.1:37767/dotnet.wasm:wasm-function[222]:0xe776))
                     at interp_runtime_invoke (interp_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[221]:0xceb8))
                     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8113]:0x1a1f59))
                     at do_runtime_invoke (do_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2054]:0x85989))
                     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2052]:0x858ff))
                     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (http://127.0.0.1:37767/dotnet.wasm:wasm-function[1395]:0x68457))
[21:25:30] fail: RuntimeError: memory access out of bounds
                     at dlfree (dlfree (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9152]:0x1e0b6c))
                     at __munmap (__munmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9054]:0x1d7166))
                     at SystemNative_MUnmap (SystemNative_MUnmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8863]:0x1cb132))
                     at wasm_invoke_iil (wasm_invoke_iil (http://127.0.0.1:37767/dotnet.wasm:wasm-function[176]:0xc2a3))
                     at interp_exec_method (interp_exec_method (http://127.0.0.1:37767/dotnet.wasm:wasm-function[222]:0xe776))
                     at interp_runtime_invoke (interp_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[221]:0xceb8))
                     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8113]:0x1a1f59))
                     at do_runtime_invoke (do_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2054]:0x85989))
                     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2052]:0x858ff))
                     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (http://127.0.0.1:37767/dotnet.wasm:wasm-function[1395]:0x68457))
[21:25:30] fail: RuntimeError: memory access out of bounds
                     at dlfree (dlfree (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9152]:0x1e0b6c))
                     at __munmap (__munmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9054]:0x1d7166))
                     at SystemNative_MUnmap (SystemNative_MUnmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8863]:0x1cb132))
                     at wasm_invoke_iil (wasm_invoke_iil (http://127.0.0.1:37767/dotnet.wasm:wasm-function[176]:0xc2a3))
                     at interp_exec_method (interp_exec_method (http://127.0.0.1:37767/dotnet.wasm:wasm-function[222]:0xe776))
                     at interp_runtime_invoke (interp_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[221]:0xceb8))
                     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8113]:0x1a1f59))
                     at do_runtime_invoke (do_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2054]:0x85989))
                     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2052]:0x858ff))
                     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (http://127.0.0.1:37767/dotnet.wasm:wasm-function[1395]:0x68457))
```

cc @BrzVlad 

Also, @pavelsavara this is emitting multiple `WASM EXIT` messages which is causing the xharness failure:

```
[21:25:30] info: WASM EXIT 1
[21:25:30] info: Waiting to flush log messages with a timeout of 120 secs ..
[21:25:30] info: WASM EXIT 1
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMKK7GIDE5RF", Request id "0HMKK7GIDE5RF:00000001": An unhandled exception was thrown by the application.
      System.Threading.Channels.ChannelClosedException: The channel has been closed.
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunConsoleMessagesPump(WebSocket socket, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 196
         at Microsoft.DotNet.XHarness.CLI.Commands.WebServer.TestWebServerStartup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs:line 163
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[21:25:30] fail: Flushing log messages failed with: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
                    at System.Threading.Tasks.TaskCompletionSource.SetResult()
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.ProcessMessage(String message, Boolean isError) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 198
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.RunAsync(CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 82
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.RunAsync(CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 82
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.CompleteAndFlushAsync(Nullable`1 timeout) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 106. Ignoring.
[21:25:30] fail: [out of order message from the browser]: http://127.0.0.1:37767/dotnet.js 4:1872 "[main] websocket closed: [object CloseEvent]" CloseEvent
[21:25:30] info: Application has finished with exit code TESTS_FAILED. But the log processor failed with GENERAL_FAILURE.
[21:25:30] fail: Application has finished with exit code GENERAL_FAILURE but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/75465 .
