### ISSUE TITLE
[iOS] XslCompiledTransform tests failing on devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#75699]
https://github.com/dotnet/runtime/pull/75499 did some house cleaning and did not preserve skipping the entire Xsl suite.  XslCompiledTransform is not aot friendly and will result in messages like:

Rolling build [link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=17272&view=ms.vss-test-web.build-test-results-tab&runId=343228&resultId=107474&paneView=debug)

```
System.ExecutionEngineException : Attempting to JIT compile method '(wrapper dynamic-method) void object:Execute (System.Xml.Xsl.Runtime.XmlQueryRuntime)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.


Stack trace
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType)
   at System.Xml.Xsl.IlGen.XmlILModule.CreateDelegate(String name, Type typDelegate)
   at System.Xml.Xsl.XmlILGenerator.Generate(QilExpression query, TypeBuilder typeBldr)
   at System.Xml.Xsl.XslCompiledTransform.CompileQilToMsil(XsltSettings settings)
   at System.Xml.Xsl.XslCompiledTransform.LoadInternal(Object stylesheet, XsltSettings settings, XmlResolver stylesheetResolver, XmlResolver originalStylesheetResolver)
   at System.Xml.Xsl.XslCompiledTransform.Load(XmlReader stylesheet, XsltSettings settings, XmlResolver stylesheetResolver)
   at System.Xml.XslCompiledTransformApiTests.Errata4.TestXslTransform(Object param0, Object param1)
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

**Comment by stephentoub** [comment]
Where were these previously being suppressed?

**Comment by steveisok** [comment]
> https://docs.microsoft.com/xamarin/ios/internals/limitations

src/libraries/tests.proj is the place where whole suites can be skipped.  tbh, we are catching this in iOS one rolling build after the change went in.  That's expected.

https://github.com/dotnet/runtime/blob/6e4eacf77636a1858851b0ea18907c198e61a6e6/src/libraries/tests.proj#L262

**Comment by jkotas** [comment]
The problem exists for NativeAOT. All Xsl tests require reflection emit. 

All of them should be conditionalized on PlatformDetection.IsReflectionEmitSupported .

**Comment by jkotas** [comment]
Partial fix
