### ISSUE TITLE
Test failure: System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75702]
Day | Run | OS | Notes
-- | -- | -- | --
9/14 | Rolling run [16870](https://runfo.azurewebsites.net/view/build/?number=16870) (7.0) | net7.0-windows-Release-**arm64-CoreCLR**_release-Windows.10.Arm64.Open |
9/10 | Rolling run [11845](https://runfo.azurewebsites.net/view/build/?number=11845) (7.0) | net7.0-windows-Release-**arm64-NativeAOT**_Release-Windows.10.Arm64.Open | System.Net.Sockets.SocketException : A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
9/6 | Rolling run [6305](https://runfo.azurewebsites.net/view/build/?number=6305) | net7.0-windows-Release-**arm64-CoreCLR**_release-Windows.10.Arm64.Open |
8/23 | PR [1961463](https://runfo.azurewebsites.net/view/build/?number=1961463) | net7.0-windows-Release-**arm64-NativeAOT**_Release-Windows.10.Arm64.Open |

[Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-f60ae1b046df4220b8/System.Net.Sockets.Tests/3/console.05f699f2.log?%3Fhelixlogtype%3Dresult):
```
    System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets(reads: 0, writes: 90) [FAIL]
      System.Net.Sockets.SocketException : An operation was attempted on something that is not a socket.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2212,0): at System.Net.Sockets.Socket.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs(54,0): at System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady(Int32 reads, Int32 writes)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SelectTest.cs(33,0): at System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets(Int32 reads, Int32 writes)
           at InvokeStub_SelectTest.Select_ReadWrite_AllReady_ManySockets(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

[Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-314be14ecb2747e4b6/System.Net.Sockets.Tests/3/console.f036b5b2.log?%3Fhelixlogtype%3Dresult)
```
[FAIL] System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady_ManySockets(reads: 90, writes: 0)
System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Tests.SelectTest.Select_ReadWrite_AllReady(Int32 reads, Int32 writes) + 0x3b8
   at System.Net.Sockets.Tests!<BaseAddress>+0xa8f9cc
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x150
```

**Comment by carlossanlop** [comment]
Hit this in a `release/7.0` backport PR: https://github.com/dotnet/runtime/pull/75985

- Queue: Libraries Test Run release coreclr windows x86 Release
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=25296&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75985-merge-2275a3425edd4da8a3/System.Net.Sockets.Tests/1/console.a15aaa47.log?helixlogtype=result
- Callstack (seems that the process got killed):
```
System.Net.Sockets.Tests.Disconnect_CancellableTask.Disconnect_Success(reuseSocket: True) [FAIL]
      System.Net.Sockets.SocketException : An operation was attempted on something that is not a socket.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1460,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1216,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.DisconnectAsync(Socket socket, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(268,0): at System.Net.Sockets.Socket.DisconnectAsync(Boolean reuseSocket, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(291,0): at System.Net.Sockets.Tests.SocketHelperCancellableTask.DisconnectAsync(Socket s, Boolean reuseSocket)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(448,0): at System.Net.Sockets.Tests.SocketTestHelperBase`1.DisconnectAsync(Socket s, Boolean reuseSocket)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DisconnectTest.cs(30,0): at System.Net.Sockets.Tests.Disconnect`1.Disconnect_Success(Boolean reuseSocket)
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs(286,0): at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs(324,0): at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs(302,0): at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs(370,0): at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
           at lambda_method2(Closure, Object, Object)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2405,0): at System.Threading.Tasks.Task.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2387,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183,0): at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2345,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2283,0): at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs(35,0): at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
        /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs(105,0): at System.Threading.Thread.StartCallback()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DisconnectTest.cs(30,0): at System.Net.Sockets.Tests.Disconnect`1.Disconnect_Success(Boolean reuseSocket)
        --- End of stack trace from previous location ---
    System.Net.Sockets.Tests.SendFile_CancellableTask.SendFileGetsCanceledByDispose(owning: True) [FAIL]
      System.ObjectDisposedException : Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2997,0): at System.Net.Sockets.Socket.SendPacketsAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1151,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(Socket socket, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(681,0): at System.Net.Sockets.Socket.SendFileAsync(String fileName, ReadOnlyMemory`1 preBuffer, ReadOnlyMemory`1 postBuffer, TransmitFileOptions flags, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(655,0): at System.Net.Sockets.Socket.SendFileAsync(String fileName, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(287,0): at System.Net.Sockets.Tests.SocketHelperCancellableTask.SendFileAsync(Socket s, String fileName)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(445,0): at System.Net.Sockets.Tests.SocketTestHelperBase`1.SendFileAsync(Socket s, String fileName)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(270,0): at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_1.<<SendFileGetsCanceledByDispose>b__2>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(285,0): at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_0.<<SendFileGetsCanceledByDispose>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs(94,0): at System.RetryHelper.ExecuteAsync(Func`1 test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(254,0): at System.Net.Sockets.Tests.SendFile`1.SendFileGetsCanceledByDispose(Boolean owning)
        --- End of stack trace from previous location ---
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:02:32
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:04:32
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:06:32
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:08:32
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:10:32
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:12:32
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.SocketDuplicationTests+Synchronous.DuplicateAndClose_TcpServerHandler', Elapsed: 00:14:32
['System.Net.Sockets.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by danmoseley** [comment]
Hit on  net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open in https://github.com/dotnet/runtime/pull/76652/checks?check_run_id=8730006416
```
    System.Net.Sockets.Tests.SendFile_Apm.SendFileGetsCanceledByDispose(owning: True) [FAIL]
      System.ObjectDisposedException : Cannot access a disposed object.
      Object name: 'System.Net.Sockets.Socket'.
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(3760,0): at System.Net.Sockets.Socket.ThrowIfDisposed()
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2984,0): at System.Net.Sockets.Socket.SendPacketsAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(1141,0): at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(Socket socket, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs(730,0): at System.Net.Sockets.Socket.SendFileAsync(String fileName, ReadOnlyMemory`1 preBuffer, ReadOnlyMemory`1 postBuffer, TransmitFileOptions flags, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2356,0): at System.Net.Sockets.Socket.BeginSendFile(String fileName, Byte[] preBuffer, Byte[] postBuffer, TransmitFileOptions flags, AsyncCallback callback, Object state)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(2342,0): at System.Net.Sockets.Socket.BeginSendFile(String fileName, AsyncCallback callback, Object state)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(203,0): at System.Net.Sockets.Tests.SocketHelperApm.<>c__DisplayClass14_0.<SendFileAsync>b__0(AsyncCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(776,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskFactory.cs(880,0): at System.Threading.Tasks.TaskFactory.FromAsync(Func`3 beginMethod, Action`1 endMethod, Object state)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(202,0): at System.Net.Sockets.Tests.SocketHelperApm.SendFileAsync(Socket s, String fileName)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs(445,0): at System.Net.Sockets.Tests.SocketTestHelperBase`1.SendFileAsync(Socket s, String fileName)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(270,0): at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_1.<<SendFileGetsCanceledByDispose>b__2>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(285,0): at System.Net.Sockets.Tests.SendFile`1.<>c__DisplayClass10_0.<<SendFileGetsCanceledByDispose>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs(94,0): at System.RetryHelper.ExecuteAsync(Func`1 test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen, String testName)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendFile.cs(254,0): at System.Net.Sockets.Tests.SendFile`1.SendFileGetsCanceledByDispose(Boolean owning)
        --- End of stack trace from previous location ---
Unhandled exception. System.TimeoutException: Timeout waiting for client connection.
   at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
   at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
   at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
   at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
   at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
   at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
   at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
   at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
   at System.Net.Sockets.Tests.SocketTestServerAsync.StartAccept(SocketAsyncEventArgs acceptEventArg) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 141
   at System.Net.Sockets.Tests.SocketTestServerAsync.ProcessAccept(SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 178
   at System.Net.Sockets.Tests.SocketTestServerAsync.AcceptEventArg_Completed(Object sender, SocketAsyncEventArgs e) in /_/src/libraries/Common/tests/System/Net/Sockets/SocketTestServerAsync.cs:line 174
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 216
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 211
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 454
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 163
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 163
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__176_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs:line 1261
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandleOverlapped.cs:line 49
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1134
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
```

**Comment by karelz** [comment]
@rzikm can you please check how often it is failing?

**Comment by rzikm** [comment]
No recent hits. Closing until the issue resurfaces.
