### ISSUE TITLE
LibraryImport analyzer crashes when encountering certain attributes

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#75706]
### Repro
1. git clone https://github.com/terrafx/terrafx.interop.windows
2. Open the solution in VS 2022 (17.4.0 Preview 2.0)
3. Build (and wait a minute or so)

### Expected Behavior

The analyzer works and reports any bugs.

### Actual Behavior

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.Interop.Analyzers.CustomMarshallerAttributeAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains no elements'.	TerraFX.Interop.Windows (net6.0)	D:\Users\tagoo\source\repos\terrafx.interop.windows\sources\Interop\Windows\CSC	1	Active	Analyzer Failure
Error	AD0001	Analyzer 'Microsoft.Interop.Analyzers.NativeMarshallingAttributeAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains no elements'.	TerraFX.Interop.Windows (net6.0)	D:\Users\tagoo\source\repos\terrafx.interop.windows\sources\Interop\Windows\CSC	1	Active	Analyzer Failure
```

**Comment by tannergooding** [comment]
CC. @jkoritzinsky, @AaronRobinsonMSFT

**Comment by tannergooding** [comment]
Also seeing:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Access .Workspace off of a RemoteWorkspace Solution is not supported. - line 69'.
Exception occurred with following context:
Compilation: TerraFX.Samples.DirectX
ISymbol: GetSamples (Method)

System.InvalidOperationException: Access .Workspace off of a RemoteWorkspace Solution is not supported. - line 69
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
   at Microsoft.CodeAnalysis.Solution.get_Workspace()
   at Microsoft.CodeAnalysis.Diagnostics.WorkspaceAnalyzerOptions.GetHashCode()
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.AbstractDataFlowAnalysisContext`4.ComputeHashCodeParts(RoslynHashCode& hashCode)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CacheBasedEquatable`1.GetOrComputeHashCode()
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CacheBasedEquatable`1.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Analyzer.Utilities.SingleThreadedConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.TryGetOrComputeResultCore(TAnalysisContext analysisContext, Boolean cacheResult)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.TryGetOrComputeResultForAnalysisContext(PointsToAnalysisContext analysisContext)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, AnalyzerOptions analyzerOptions, WellKnownTypeProvider wellKnownTypeProvider, PointsToAnalysisKind pointsToAnalysisKind, DataFlowAnalysisResult`2& copyAnalysisResult, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, Boolean pessimisticAnalysis, Boolean performCopyAnalysis, Boolean exceptionPathsAnalysis)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, AnalyzerOptions analyzerOptions, WellKnownTypeProvider wellKnownTypeProvider, PointsToAnalysisKind pointsToAnalysisKind, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, Boolean pessimisticAnalysis, Boolean performCopyAnalysis, Boolean exceptionPathsAnalysis)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, Func`2 createOperationVisitor, WellKnownTypeProvider wellKnownTypeProvider, AnalyzerOptions analyzerOptions, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, PointsToAnalysisKind pointsToAnalysisKind, Boolean pessimisticAnalysis, Boolean performValueContentAnalysis, DataFlowAnalysisResult`2& valueContentAnalysisResult, ImmutableArray`1 additionalSupportedValueTypes, Func`2 getValueContentValueForAdditionalSupportedValueTypeOperation)
   at Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer.<>c__DisplayClass34_0.<AnalyzeOperationBlock>b__1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA1416, CA1422	TerraFX.Samples.DirectX (net6.0)		1	Active
```
and
```
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Access .Workspace off of a RemoteWorkspace Solution is not supported. - line 69'.
Exception occurred with following context:
Compilation: TerraFX.Samples.DirectX
ISymbol: GetSamples (Method)

System.InvalidOperationException: Access .Workspace off of a RemoteWorkspace Solution is not supported. - line 69
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
   at Microsoft.CodeAnalysis.Solution.get_Workspace()
   at Microsoft.CodeAnalysis.Diagnostics.WorkspaceAnalyzerOptions.GetHashCode()
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.AbstractDataFlowAnalysisContext`4.ComputeHashCodeParts(RoslynHashCode& hashCode)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CacheBasedEquatable`1.GetOrComputeHashCode()
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CacheBasedEquatable`1.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Analyzer.Utilities.SingleThreadedConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.TryGetOrComputeResultCore(TAnalysisContext analysisContext, Boolean cacheResult)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.TryGetOrComputeResultForAnalysisContext(PointsToAnalysisContext analysisContext)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, AnalyzerOptions analyzerOptions, WellKnownTypeProvider wellKnownTypeProvider, PointsToAnalysisKind pointsToAnalysisKind, DataFlowAnalysisResult`2& copyAnalysisResult, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, Boolean pessimisticAnalysis, Boolean performCopyAnalysis, Boolean exceptionPathsAnalysis)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.PointsToAnalysis.PointsToAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, AnalyzerOptions analyzerOptions, WellKnownTypeProvider wellKnownTypeProvider, PointsToAnalysisKind pointsToAnalysisKind, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, Boolean pessimisticAnalysis, Boolean performCopyAnalysis, Boolean exceptionPathsAnalysis)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.GlobalFlowStateAnalysis.GlobalFlowStateAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, ISymbol owningSymbol, Func`2 createOperationVisitor, WellKnownTypeProvider wellKnownTypeProvider, AnalyzerOptions analyzerOptions, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig, InterproceduralAnalysisPredicate interproceduralAnalysisPredicate, PointsToAnalysisKind pointsToAnalysisKind, Boolean pessimisticAnalysis, Boolean performValueContentAnalysis, DataFlowAnalysisResult`2& valueContentAnalysisResult, ImmutableArray`1 additionalSupportedValueTypes, Func`2 getValueContentValueForAdditionalSupportedValueTypeOperation)
   at Microsoft.NetCore.Analyzers.InteropServices.PlatformCompatibilityAnalyzer.<>c__DisplayClass34_0.<AnalyzeOperationBlock>b__1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA1416, CA1422	TerraFX.Samples.DirectX (net7.0)		1	Active
```

**Comment by jkoritzinsky** [comment]
The PlatformCompatibilityAnalyzer is in dotnet/roslyn-analyzers and is owned by the libraries team (I think Jeff Handley's team). Can you open a separate issue for that one?

**Comment by jkoritzinsky** [comment]
Also, for blittable bindings, we don't generate a method that calls a P/Invoke. We add the `DllImport` attribute to the `LibraryImport` method, making it the P/Invoke itself. So the extra metadata cost is just the `LibraryImport` attribute, which will be removed when trimming agressively (the mode that removes some attributes)
