### ISSUE TITLE
Test failure baseservices\\exceptions\\unittests\\RecursiveThrowNew\\RecursiveThrowNew.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75944]
Run: [runtime-coreclr jitstress 20220919.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468774&resultId=106563&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked jitstress2_tiered @ Windows.10.Arm64v8.Open
- baseservices\\exceptions\\unittests\\RecursiveThrowNew\\RecursiveThrowNew.cmd
...
coreclr OSX x64 Checked jitstress1 @ OSX.1200.Amd64.Open
- JIT/jit64/opt/cg/cgstress/CgStress1_do/CgStress1_do.sh
... 
coreclr OSX x64 Checked jitstress2 @ OSX.1200.Amd64.Open
- JIT/PGO/ProfileCastClassAndIsInst/ProfileCastClassAndIsInst/ProfileCastClassAndIsInst.sh
...
coreclr OSX x64 Checked jitstress1_tiered @ OSX.1200.Amd64.Open
- JIT/HardwareIntrinsics/X86/Sse2/AlignVector128_r/AlignVector128_r.sh
...
coreclr OSX arm64 Checked jitstress1_tiered @ OSX.1200.ARM64.Open
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part6_ro/AdvSimd.Arm64_Part6_ro.sh
...
coreclr OSX x64 Checked jitstress2_tiered @ OSX.1200.Amd64.Open
- JIT/HardwareIntrinsics/X86/Bmi2/Bmi2_r/Bmi2_r.sh
...
coreclr OSX arm64 Checked jitstress2_tiered @ OSX.1200.ARM64.Open
- baseservices/threading/generics/TimerCallback/thread14/thread14.sh
...
coreclr Linux x64 Checked zapdisable @ Ubuntu.1804.Amd64.Open
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh
...
coreclr Linux x64 Checked jitstress2_tiered @ Ubuntu.1804.Amd64.Open
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open
- JIT\\Regression\\VS-ia64-JIT\\V1.2-M02\\b28158\\b28158\\b28158.cmd
...
coreclr Linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open
- JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
...
coreclr Linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open
- JIT/jit64/opt/cse/HugeField1/HugeField1.sh
...
coreclr windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
...
coreclr Linux x64 Checked jitstress1 @ Ubuntu.1804.Amd64.Open
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
...
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
...
coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\Directed\\nullabletypes\\Desktop\\nullcomparaison_do\\nullcomparaison_do.cmd
...
coreclr windows x64 Checked jitstress2 @ Windows.10.Amd64.Open
- baseservices\\threading\\generics\\WaitCallback\\thread16\\thread16.cmd
...
coreclr OSX arm64 Checked jitstress1 @ OSX.1200.ARM64.Open
- JIT/CodeGenBringUpTests/Swap_do/Swap_do.sh
...
coreclr windows arm64 Checked jitstress1_tiered @ Windows.10.Arm64v8.Open
- JIT\\jit64\\hfa\\main\\testC\\hfa_nf2C_d\\hfa_nf2C_d.cmd
...
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Regression\\CLR-x86-JIT\\V1-M09.5-PDC\\b10894\\b10894\\b10894.cmd
...
coreclr Linux arm64 Checked zapdisable @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh
...
coreclr Linux arm Checked zapdisable @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh
...
coreclr windows x86 Checked zapdisable @ Windows.10.Amd64.Open
- JIT\\opt\\OSR\\largefuncletframe\\largefuncletframe.cmd
...
coreclr Linux arm64 Checked jitstress1_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr Linux arm64 Checked jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr windows arm64 Checked jitstress1 @ Windows.10.Arm64v8.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
...
coreclr Linux arm64 Checked jitstress2_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh
...
coreclr Linux arm Checked jitstress1_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr Linux arm64 Checked jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh
...
coreclr windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\Regression\\CLR-x86-JIT\\V1-M12-Beta2\\b84916\\b84916\\b84916.cmd
...
coreclr Linux arm Checked jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr OSX arm64 Checked jitstress2 @ OSX.1200.ARM64.Open
- Loader/classloader/generics/Instantiation/Recursion/Struct_ImplementMscorlibGenInterface/Struct_ImplementMscorlibGenInterface.sh
...
coreclr Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/jit64/opt/cse/HugeField2/HugeField2.sh
...
coreclr Linux arm Checked jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\Avx1\\Avx_r\\Avx_r.cmd
...
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\Sse3\\Sse3_ro\\Sse3_ro.cmd
...
```
**Error message:**
```
Assert failure(PID 16272 [0x00003f90], Thread: 7324 [0x1c9c]): Assertion failed 'false && "found use of a node that is not in the LIR sequence"' in 'System.AppContext:TryGetSwitch(System.String,byref):bool' during 'Rationalize IR' (IL size 97; hash 0x1d5a13fc; Tier1)

File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1622
Image: D:\h\w\AC3C097A\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\AC3C097A\w\A51409FF\uploads\Reports\baseservices.exceptions\unittests\RecursiveThrowNew\RecursiveThrowNew.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\AC3C097A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  RecursiveThrowNew.dll
RecursiveThrowNew
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AC3C097A\p
D:\h\w\AC3C097A\w\A51409FF\e\baseservices\exceptions\unittests\RecursiveThrowNew\RecursiveThrowNew.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._unittests_RecursiveThrowNew_RecursiveThrowNew_._unittests_RecursiveThrowNew_RecursiveThrowNew_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
One more assert in rationalize. Assigning to @BruceForstall. @jakobbotsch PTAL.
cc @dotnet/jit-contrib.

**Comment by jakobbotsch** [comment]
Looks related to #75842, apparently the threading added there was not enough (or perhaps incorrect). I'll look into a fix tomorrow.
cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Wonder if the failures we now see in #62689 are also related.

**Comment by AndyAyersMS** [comment]
Seems like it is from changes made in `optOptimizeBoolsGcStress` which is why it didn't come up in normal testing.

**Comment by AndyAyersMS** [comment]
This is not a 7.0 issue.
