### ISSUE TITLE
Test failure GC/Features/HeapExpansion/bestfit/bestfit.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75941]
Run: [runtime-coreclr jitstress 20220919.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468470&paneView=debug&resultId=107257)

Failed test:
```
coreclr OSX arm64 Checked jitstress1_tiered @ OSX.1200.ARM64.Open

- GC/Features/HeapExpansion/bestfit/bestfit.sh
```
**Error message:**
```
Assert failure(PID 84911 [0x00014baf], Thread: 11093087 [0xa9445f]): Assertion failed 'firstNode != nullptr' in 'System.Globalization.CultureData:IcuGetTimeFormatString(bool):System.String:this' during 'Rationalize IR' (IL size 103; hash 0x1b95165e; Tier1)

File: /Users/runner/work/1/s/src/coreclr/jit/lir.cpp Line: 1210
Image: /private/tmp/helix/working/A1860895/p/corerun
[createdump] Invalid process id: task_for_pid(84911) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/A1860895/w/A5F50944/e/GC/Features/HeapExpansion/bestfit/bestfit.sh: line 403: 84911 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A1860895/w/A5F50944/uploads/Reports/GC.Features/HeapExpansion/bestfit/bestfit.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A1860895/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false bestfit.dll '1' '1000' '50000'
Using random seed: -1200226766
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A1860895/p
/private/tmp/helix/working/A1860895/w/A5F50944/e/GC/Features/HeapExpansion/bestfit/bestfit.sh
Expected: True
Actual:   False


Stack trace
   at GC_Features._HeapExpansion_bestfit_bestfit_._HeapExpansion_bestfit_bestfit_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-09-20T08:53:57.595Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=23216&view=ms.vss-test-web.build-test-results-tab&runId=470736&resultId=101928&paneView=debug)
2022-09-20T06:25:34.076Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468470&resultId=107257&paneView=debug)
2022-09-18T22:47:11.767Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr gcstress-extra   Checked-heapverify1](https://dev.azure.com/dnceng/public/_build/results?buildId=21534&view=ms.vss-test-web.build-test-results-tab&runId=434260&resultId=108560&paneView=debug)
2022-09-17T22:47:24.173Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr gcstress-extra   Checked-heapverify1](https://dev.azure.com/dnceng/public/_build/results?buildId=21282&view=ms.vss-test-web.build-test-results-tab&runId=427632&resultId=108167&paneView=debug)
2022-09-05T22:02:12.451Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=5191&view=ms.vss-test-web.build-test-results-tab&runId=90202&resultId=100855&paneView=debug)
2022-09-05T10:07:05.729Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=4698&view=ms.vss-test-web.build-test-results-tab&runId=81638&resultId=100084&paneView=debug)

**Comment by JulieLeeMSFT** [comment]
Assigning to @BruceForstall. @jakobbotsch could you take a look while @BruceForstall is OOF?
cc @dotnet/jit-contrib.

**Comment by AndyAyersMS** [comment]
Not a 7.0 issue.

**Comment by AndyAyersMS** [comment]
Should be fixed by https://github.com/dotnet/runtime/pull/75992
