### ISSUE TITLE
Pthread assert failures on Arm64 Hisilicon D05

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#75968]
When using Arm64 `Hisilicon D05` (64x Cortex-A72 cores) with Ubuntu 18.04.

Running `./src/tests/run.sh Checked`

The following tests:
- Interop/UnmanagedCallersOnlyBasic/UnmanagedCallersOnlyBasicTest/UnmanagedCallersOnlyBasicTest.sh
- profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.sh
- profiler/unittest/releaseondetach/releaseondetach.sh

Fail with:
```
Assert failure(PID 5742 [0x0000166e], Thread: 5752 [0x1678]): pThread
                   File: /home/alahay01/dotnet/runtime/src/coreclr/vm/threads.inl Line: 43
                   Image: /home/alahay01/dotnet/runtime/artifacts/tests/coreclr/Linux.arm64.Checked/Tests/Core_Root/corerun
```

Curiously when running in gdb, all the tests fail with the same segfault:
```
Thread 11 "corerun" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xffbf0db9c1d0 (LWP 52198)]
0x0000fffff7e2f478 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x0000fffff7e2f478 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#1  0x0000fffff7f80088 in start_thread () from /lib/aarch64-linux-gnu/libpthread.so.0
#2  0x0000fffff7bf80cc in ?? () from /lib/aarch64-linux-gnu/libc.so.6
```

When running the exact same tests on an Altra with Ubuntu 18.04, these tests pass ok.

The Hisilicon D05 is a bit of an obscure box, so I'm not really expecting anyone else to be running dotnet on one. However, running on different types of boxes is a great way of exposing timing related bugs and other issues that will bite eventually.

**Comment by a74nh** [comment]
Interestingly, when run across all the box types in our CI, these tests passed. This included a Hisilicon D05.

The difference is that the issue reported here was not run inside a docker image. So this could be due to an issue with a slightly different version of glibc etc. I'll investigate further.
