### ISSUE TITLE
Blazor Wasm Crashes if another wasm instance is running in the service worker.

### ISSUE THREAD

**Issue by groogiam** [dotnet/runtime#76026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My application loads another .NET Wasm instance in a service worker to perform offline processing. This causes the debugger to crash with 

```
Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.    at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)    at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.ReadOne(WebSocket socket, CancellationToken token)    --- End of inner exception stack trace ---    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
```

This makes it impossible to debug my application with the service worker running.

The wasm instance loaded in the service worker uses https://github.com/unoplatform/Uno.Wasm.Bootstrap

### Expected Behavior

The debugger should not crash.

### Steps To Reproduce

https://github.com/groogiam/dotnetruntime-76026-repro

### .NET Version

6.0.401

**Comment by mkArtakMSFT** [comment]
@thaystg can you please look into this? Thanks!

**Comment by groogiam** [comment]
Updated error message.

```
(Invalid Session: "session-6EDF9A49784F785C8E2A78C17F076377" (Parameter 'sessionId'))  ---> System.ArgumentException: Invalid Session: "session-6EDF9A49784F785C8E2A78C17F076377" (Parameter 'sessionId')    at Microsoft.WebAssembly.Diagnostics.MonoProxy.GetContext(SessionId sessionId)    at Microsoft.WebAssembly.Diagnostics.MonoProxy.RuntimeReady(SessionId sessionId, CancellationToken token)    at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at System.Threading.Tasks.Task`1.get_Result()    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
```

**Comment by thaystg** [comment]
@groogiam can you share with me your C:\Users\[UserName]\AppData\Local\Temp\visualstudio-js-debugger.txt?

**Comment by groogiam** [comment]
[76026_visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/9629229/76026_visualstudio-js-debugger.txt)

**Comment by groogiam** [comment]
Just posted the repro in the original comment.

**Comment by thaystg** [comment]
@groogiam , thanks for the repro. The fix is in PR.

**Comment by groogiam** [comment]
@thaystg Awesome! Thanks for implementing the fix so quickly.

**Comment by groogiam** [comment]
@thaystg Any idea when this will be released? Thanks.

**Comment by thaystg** [comment]
@lewing it will be available in the version right after rc2, do you know when this will be released?

**Comment by lewing** [comment]
it should be in net7.0 GA (and 6.0.11)

**Comment by groogiam** [comment]
@lewing @thaystg Great! Thanks for the info.

**Comment by groogiam** [comment]
@thaystg After updating Visual Studio to 17.4.0 which I believe includes the 6.0.11 runtime I am still encountering this issue.

**Comment by thaystg** [comment]
Did you update the Microsoft.AspNetCore.Components.WebAssembly.DevServer package?

**Comment by groogiam** [comment]
Whoops, totally overlooked that step. That seems to have taken care of the issue. Thanks again!
