### ISSUE TITLE
Intermittent failure in CriticalFinalizer test

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#76041]
Affected tests:
- `baseservices/finalization/CriticalFinalizer/CriticalFinalizer.sh`
- `baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd`

Runfo failures in [last 30 days - .sh](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22baseservices%2Ffinalization%2Fcriticalfinalizer%2Fcriticalfinalizer.sh%22) and [last 30 days - .cmd](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22baseservices%5C%5Cfinalization%5C%5Ccriticalfinalizer%5C%5Ccriticalfinalizer.cmd%22):
- 9/23 - 188 failures
    - First failure in Rolling run https://runfo.azurewebsites.net/view/build/?number=24556 on 9/20 ... more than 50x failures per day

CoreCLR: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75573-merge-b0042e942c0145f38e/baseservices.finalization/1/console.e135272f.log?helixlogtype=result
```
BEGIN EXECUTION
"C:\h\w\A68508F4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CriticalFinalizer.dll 
Finalized 0 Normal and 0 Critical objects.
The first Critical object was finalized after 0 Normal objects.
Expected: 100
Actual: 101
END EXECUTION - FAILED
```

Mono: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74586-merge-662a1339f83d41b786/baseservices.finalization/1/console.0af36b40.log?helixlogtype=result
```
BEGIN EXECUTION
/tmp/helix/working/A1850911/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false CriticalFinalizer.dll ''
Finalized 100 Normal and 99 Critical objects.
The first Critical object was finalized after 100 Normal objects.
Expected: 100
Actual: 101
END EXECUTION - FAILED
```
```
{ "ErrorMessage":"CriticalFinalizer" } 
```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[28655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28655)|dotnet/runtime|LLVM AOT compile CoreCLR tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/28655/logs/1777)

|Build|Definition|Test|
|---|---|---|
|[29097](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29097)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29097&view=ms.vss-test-web.build-test-results-tab&runId=586054&resultId=103265)|
|[28963](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28963)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28963&view=ms.vss-test-web.build-test-results-tab&runId=585362&resultId=100006)|
|[28964](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28964)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28964&view=ms.vss-test-web.build-test-results-tab&runId=585370&resultId=110809)|
|[29051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29051)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29051&view=ms.vss-test-web.build-test-results-tab&runId=585598&resultId=103004)|
|[29016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29016)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29016&view=ms.vss-test-web.build-test-results-tab&runId=585520&resultId=103041)|
|[29012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29012)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29012&view=ms.vss-test-web.build-test-results-tab&runId=585474&resultId=103041)|
|[29010](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29010)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=29010&view=ms.vss-test-web.build-test-results-tab&runId=585434&resultId=100069)|
|[28977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28977)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28977&view=ms.vss-test-web.build-test-results-tab&runId=585086&resultId=103262)|
|[28942](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28942)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28942&view=ms.vss-test-web.build-test-results-tab&runId=584954&resultId=100005)|
|[28861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28861)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28861&view=ms.vss-test-web.build-test-results-tab&runId=584842&resultId=100142)|
|[28621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28621)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28621&view=ms.vss-test-web.build-test-results-tab&runId=583814&resultId=110809)|
|[28899](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28899)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28899&view=ms.vss-test-web.build-test-results-tab&runId=583614&resultId=101098)|
|[28892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28892)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28892&view=ms.vss-test-web.build-test-results-tab&runId=583586&resultId=101314)|
|[28655](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28655)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28655&view=ms.vss-test-web.build-test-results-tab&runId=582966&resultId=100089)|
|[28841](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28841)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28841&view=ms.vss-test-web.build-test-results-tab&runId=582902&resultId=100188)|
|[28819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28819)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28819&view=ms.vss-test-web.build-test-results-tab&runId=582510&resultId=103262)|
|[28749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28749)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28749&view=ms.vss-test-web.build-test-results-tab&runId=581790&resultId=110005)|
|[28766](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28766)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28766&view=ms.vss-test-web.build-test-results-tab&runId=581716&resultId=100122)|
|[28692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28692)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28692&view=ms.vss-test-web.build-test-results-tab&runId=581136&resultId=100204)|
|[28682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28682)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28682&view=ms.vss-test-web.build-test-results-tab&runId=581120&resultId=100224)|
|[28649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28649)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28649&view=ms.vss-test-web.build-test-results-tab&runId=578836&resultId=103262)|
|[28606](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28606)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28606&view=ms.vss-test-web.build-test-results-tab&runId=577392&resultId=110809)|
|[28615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28615)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28615&view=ms.vss-test-web.build-test-results-tab&runId=577274&resultId=100989)|
|[28597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28597)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28597&view=ms.vss-test-web.build-test-results-tab&runId=576808&resultId=100304)|
|[28592](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28592)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28592&view=ms.vss-test-web.build-test-results-tab&runId=576724&resultId=100269)|
|[28591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28591)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28591&view=ms.vss-test-web.build-test-results-tab&runId=576700&resultId=100192)|
|[27258](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27258)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27258&view=ms.vss-test-web.build-test-results-tab&runId=575262&resultId=100071)|
|[28513](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28513)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28513&view=ms.vss-test-web.build-test-results-tab&runId=574886&resultId=110809)|
|[28494](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28494)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28494&view=ms.vss-test-web.build-test-results-tab&runId=574254&resultId=103262)|
|[28476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28476)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28476&view=ms.vss-test-web.build-test-results-tab&runId=573856&resultId=103262)|
|[28414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28414)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28414&view=ms.vss-test-web.build-test-results-tab&runId=573554&resultId=110809)|
|[27149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27149)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27149&view=ms.vss-test-web.build-test-results-tab&runId=572978&resultId=103260)|
|[28383](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28383)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28383&view=ms.vss-test-web.build-test-results-tab&runId=572118&resultId=100254)|
|[28313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28313)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28313&view=ms.vss-test-web.build-test-results-tab&runId=571294&resultId=103262)|
|[28293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28293)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28293&view=ms.vss-test-web.build-test-results-tab&runId=570840&resultId=103262)|
|[28278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28278)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28278&view=ms.vss-test-web.build-test-results-tab&runId=571006&resultId=101258)|
|[28251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28251)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28251&view=ms.vss-test-web.build-test-results-tab&runId=570948&resultId=101314)|
|[28306](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28306)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28306&view=ms.vss-test-web.build-test-results-tab&runId=570932&resultId=101059)|
|[28149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28149)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28149&view=ms.vss-test-web.build-test-results-tab&runId=568764&resultId=100166)|
|[27779](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27779)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27779&view=ms.vss-test-web.build-test-results-tab&runId=567762&resultId=103261)|
|[27987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27987)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27987&view=ms.vss-test-web.build-test-results-tab&runId=565762&resultId=102210)|
|[27102](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27102)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27102&view=ms.vss-test-web.build-test-results-tab&runId=566954&resultId=100022)|
|[28056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28056)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28056&view=ms.vss-test-web.build-test-results-tab&runId=566628&resultId=100144)|
|[28047](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28047)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28047&view=ms.vss-test-web.build-test-results-tab&runId=565850&resultId=103003)|
|[28023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28023)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28023&view=ms.vss-test-web.build-test-results-tab&runId=566096&resultId=101314)|
|[27880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27880)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27880&view=ms.vss-test-web.build-test-results-tab&runId=565226&resultId=100076)|
|[27960](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27960)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27960&view=ms.vss-test-web.build-test-results-tab&runId=564516&resultId=103261)|
|[27940](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27940)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27940&view=ms.vss-test-web.build-test-results-tab&runId=564364&resultId=100391)|
|[27866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27866)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27866&view=ms.vss-test-web.build-test-results-tab&runId=562906&resultId=100005)|
|[26219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=26219)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=26219&view=ms.vss-test-web.build-test-results-tab&runId=562654&resultId=100085)|
|[27820](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27820)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27820&view=ms.vss-test-web.build-test-results-tab&runId=561308&resultId=103261)|
|[27804](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27804)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27804&view=ms.vss-test-web.build-test-results-tab&runId=561162&resultId=103261)|
|[27855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27855)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27855&view=ms.vss-test-web.build-test-results-tab&runId=562074&resultId=101059)|
|[27831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27831)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27831&view=ms.vss-test-web.build-test-results-tab&runId=561664&resultId=100259)|
|[27789](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27789)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27789&view=ms.vss-test-web.build-test-results-tab&runId=561164&resultId=100804)|
|[27742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27742)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27742&view=ms.vss-test-web.build-test-results-tab&runId=560558&resultId=103260)|
|[27754](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27754)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27754&view=ms.vss-test-web.build-test-results-tab&runId=560328&resultId=103002)|
|[27703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27703)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27703&view=ms.vss-test-web.build-test-results-tab&runId=559784&resultId=100032)|
|[26661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=26661)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=26661&view=ms.vss-test-web.build-test-results-tab&runId=558390&resultId=103259)|
|[27657](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27657)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27657&view=ms.vss-test-web.build-test-results-tab&runId=558654&resultId=100278)|
|[27643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27643)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27643&view=ms.vss-test-web.build-test-results-tab&runId=558066&resultId=100130)|
|[27588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27588)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27588&view=ms.vss-test-web.build-test-results-tab&runId=557792&resultId=100158)|
|[27630](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27630)|dotnet/runtime|[baseservices.finalization.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27630&view=ms.vss-test-web.build-test-results-tab&runId=557690&resultId=103002)|
|[27557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27557)|dotnet/runtime|[baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=27557&view=ms.vss-test-web.build-test-results-tab&runId=556856&resultId=100002)|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|33|65|65|

**Comment by HJLeee** [comment]
@AntonLapounov Please take a look. https://github.com/dotnet/runtime/pull/76046

**Comment by karelz** [comment]
@AntonLapounov it seems it may have been a regression caused by #75952.
This is blocking significantly CI -- can you please roll back the change, or disable the affected test ASAP? (definitely before the weekend) Thanks!

**Comment by buyaa-n** [comment]
Failed in https://github.com/dotnet/runtime/pull/75965
Log: https://helix.dot.net/api/2019-06-17/jobs/ab2fe355-3fb8-48fd-bf26-f1ab51bd2648/workitems/baseservices.finalization/console
```log
baseservices\finalization\CriticalFinalizer\CriticalFinalizer.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\BD950A05\w\B05A0982\uploads\Reports\baseservices.finalization\CriticalFinalizer\CriticalFinalizer.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\BD950A05\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CriticalFinalizer.dll 
      Finalized 0 Normal and 0 Critical objects.
      The first Critical object was finalized after 0 Normal objects.
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\BD950A05\p
      > C:\h\w\BD950A05\w\B05A0982\e\baseservices\finalization\CriticalFinalizer\CriticalFinalizer.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at baseservices_finalization._CriticalFinalizer_CriticalFinalizer_._CriticalFinalizer_CriticalFinalizer_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      C:\h\w\BD950A05\w\B05A0982\uploads\Reports\baseservices.finalization\CriticalFinalizer\CriticalFinalizer.output.txt
        Raw output:
        BEGIN EXECUTION
         "C:\h\w\BD950A05\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CriticalFinalizer.dll 
        Finalized 0 Normal and 0 Critical objects.
        The first Critical object was finalized after 0 Normal objects.
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\h\w\BD950A05\p
        > C:\h\w\BD950A05\w\B05A0982\e\baseservices\finalization\CriticalFinalizer\CriticalFinalizer.cmd
  Finished:    baseservices.finalization.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   baseservices.finalization.XUnitWrapper  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 1.235s
```

**Comment by jkotas** [comment]
Disabling the test in https://github.com/dotnet/runtime/pull/76131. Please re-enable once fixed.

**Comment by AustinWise** [comment]
If my system is doing something CPU intensive, like compiling CoreCLR, the test failure reproduces more reliably. It fails rough 1 in 100 runs.

Calling `GC.Collect` and `GC.WaitForPendingFinalizers` several times in a loop seems to fix the problem. I'm not sure though that is really a reliable way to fix the test.

**Comment by AntonLapounov** [comment]
There are two issues:
* The lambda used in `Parallel.For` creates a closure object (`DisplayClass`) and places the `arr` reference there. That closure object may be kept alive by one of thread pool threads.
* In some Mono runs the test reports only 99 `Critical` objects collected out of 100.  I suspect that `GC.WaitForPendingFinalizers()` might not synchronize the current thread with the finalizer thread regarding visibility of memory stores performed by finalizers.

**Comment by AntonLapounov** [comment]
Looking at the Mono code, there may be a race condition in `sgen_have_pending_finalizers` for checking the `pending_unqueued_finalizer` flag: https://github.com/dotnet/runtime/blob/c986a12cdae428a3d603ced4e24690d2629c9cb3/src/mono/mono/sgen/sgen-gc.c#L2906-L2912

**Comment by mangod9** [comment]
I am closing this based on https://github.com/dotnet/runtime/pull/76046. We can reopen if this continues to be an issue.

**Comment by AustinWise** [comment]
@mangod9 This test is still disabled, referencing this issue:

https://github.com/dotnet/runtime/blob/main/src/tests/issues.targets#L14-L16

So I'm don't think the test was ever fixed to be reliable.

**Comment by jkotas** [comment]
We should either delete the test or fix it to be reliable.
