### ISSUE TITLE
Test failure: JIT/opt/OSR/largefuncletframe/largefuncletframe.sh

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#76085]
Affected tests:
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh

Failure: `Assertion failed 'false && "found use of a node that is not in the LIR sequence"`

- 9/23:
    - 35x failures in Kusto on main runs on 9/22 -- looks like a fresh regression
    - Note: Runfo [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22largefuncletframe%22) shows first occurrence on 9/20 in Rolling run [23975](https://runfo.azurewebsites.net/view/build/?number=23975)

```kusto
let failedTests = (testNameSubstring : string, methodName : string, messageSubstr: string, includePR : bool, includePassedOnRerun : bool) {
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName contains testNameSubstring
    | where includePassedOnRerun or (Outcome == 'Failed')
    | extend startOfTestName = indexof_regex(TestName, @"[^.]+$")
    | extend Method = substring(TestName, startOfTestName)
    | extend Type = substring(TestName, 0, startOfTestName - 1)
    | project-away startOfTestName
    | where (methodName == '') or (Method == methodName)
    | where Message contains messageSubstr
    | distinct JobId, WorkItemId, Message, StackTrace, Method, Type, Arguments, Outcome
    | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
        | where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")))
        | where Type startswith "test/functional/cli/"
            and not(Properties contains "runtime-staging")
            and not(Properties contains "jitstress")
        | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
        | project-rename JobType = Type) on JobId
    | extend PropertiesJson = parse_json(Properties)
    | extend OS = replace_regex(tostring(PropertiesJson.operatingSystem), @'\((.*)\).*|([^\(].*)', @'\1\2')
    | extend Runtime = iif(PropertiesJson.runtimeFlavor == "mono", "Mono", iif(PropertiesJson.DefinitionName contains "coreclr", "CoreCLR", ""))
    | extend TargetBranch = extractjson("$.['System.PullRequest.TargetBranch']", Properties)
    | extend Architecture = PropertiesJson.architecture
    | extend Scenario = iif(isempty(PropertiesJson.scenario), "--", PropertiesJson.scenario)
    //| extend DefinitionName = PropertiesJson.DefinitionName
    | project-away PropertiesJson
};
failedTests(
    '', //testNameSubstring
    '', //methodName
    'found use of a node that is not in the LIR sequence', //messageSubstr
    true,  //includePR
    true); //includePassedOnRerun
```

Example error:
```

Assert failure(PID 13588 [0x00003514], Thread: 7980 [0x1f2c]): Assertion failed 'false && "found use of a node that is not in the LIR sequence"' in 'System.Diagnostics.Tracing.EventSource:Initialize(System.Guid,System.String,System.String[]):this' during 'Rationalize IR' (IL size 414; hash 0x578c91f2; Tier0-FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1622
    Image: D:\h\w\A89A0902\p\corerun.exe


Return code:      1
Raw output file:      D:\h\w\A89A0902\w\A01808E0\uploads\Reports\JIT.opt\OSR\largefuncletframe\largefuncletframe.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\A89A0902\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  largefuncletframe.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\A89A0902\p
> D:\h\w\A89A0902\w\A01808E0\e\JIT\opt\OSR\largefuncletframe\largefuncletframe.cmd
Expected: True
Actual:   False

   at JIT_opt._OSR_largefuncletframe_largefuncletframe_._OSR_largefuncletframe_largefuncletframe_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Another example: [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74580-merge-4df4f5aeddbe4f2b86/JIT.1/1/console.46926d6c.log?%3Fhelixlogtype%3Dresult)

**Comment by karelz** [comment]
Not sure if it is related, but if you remove the test name, there are **24K+** failures in Kusto with the same assert across various tests -- almost all in jitstress, except 30.
Kusto will stop showing failures, but at least the top 24,461 it shows are all from 9/22:

```kusto
let failedTests = (testNameSubstring : string, methodName : string, messageSubstr: string, includePR : bool, includePassedOnRerun : bool) {
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName contains testNameSubstring
    | where includePassedOnRerun or (Outcome == 'Failed')
    | extend startOfTestName = indexof_regex(TestName, @"[^.]+$")
    | extend Method = substring(TestName, startOfTestName)
    | extend Type = substring(TestName, 0, startOfTestName - 1)
    | project-away startOfTestName
    | where (methodName == '') or (Method == methodName)
    | where Message contains messageSubstr
    | distinct JobId, WorkItemId, Message, StackTrace, Method, Type, Arguments, Outcome
    | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
        | where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")))
        | where Type startswith "test/functional/cli/"
            and not(Properties contains "runtime-staging")
            //and not(Properties contains "stress")
        | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
        | project-rename JobType = Type) on JobId
    | extend PropertiesJson = parse_json(Properties)
    | extend OS = replace_regex(tostring(PropertiesJson.operatingSystem), @'\((.*)\).*|([^\(].*)', @'\1\2')
    | extend Runtime = iif(PropertiesJson.runtimeFlavor == "mono", "Mono", iif(PropertiesJson.DefinitionName contains "coreclr", "CoreCLR", ""))
    | extend TargetBranch = extractjson("$.['System.PullRequest.TargetBranch']", Properties)
    | extend Architecture = PropertiesJson.architecture
    | extend Scenario = iif(isempty(PropertiesJson.scenario), "--", PropertiesJson.scenario)
    //| extend DefinitionName = PropertiesJson.DefinitionName
    | project-away PropertiesJson
};
failedTests(
    '', //testNameSubstring
    '', //methodName
    'found use of a node that is not in the LIR sequence', //messageSubstr
    true,  //includePR
    true); //includePassedOnRerun
```

**Comment by jakobbotsch** [comment]
This is likely a duplicate of #75944, the fix was just merged one hour ago (#75992).

**Comment by AndyAyersMS** [comment]
Right, should be fixed by https://github.com/dotnet/runtime/pull/75992.

**Comment by karelz** [comment]
Duplicate of #75944
