### ISSUE TITLE
CI failure: System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestLoadTests.VerifySignature_RSA_PSS(hashAlgorithm: "SHA512")

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76099]
Found in this `release/7.0` PR: https://github.com/dotnet/runtime/pull/75913

Please help determine if this is a failure that needs a fix backported to 7.0.

- Queue: Libraries Test Run release coreclr windows x64 Release
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=26747&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d&l=105
- Log file: https://helix.dot.net/api/2019-06-17/jobs/4e8a3335-6a35-4b6e-9c11-70a1dccc9eab/workitems/System.Security.Cryptography.X509Certificates.Tests/console
- Callstack:
```
----- start Thu 09/22/2022 21:08:19.93 ===============  To repro directly: ===================================================== 
pushd C:\helix\work\workitem\e\
"C:\helix\work\correlation\dotnet.exe" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\helix\work\workitem\e>"C:\helix\work\correlation\dotnet.exe" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.X509Certificates.Tests (found 805 of 859 test cases)
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 2)
    System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestLoadTests.VerifySignature_RSA_PSS(hashAlgorithm: "SHA512") [FAIL]
      System.Security.Cryptography.CryptographicException : Unknown error (0xc0000001)
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngCommon.SignVerify.cs(42,0): at System.Security.Cryptography.CngCommon.SignHash(SafeNCryptKeyHandle keyHandle, ReadOnlySpan`1 hash, AsymmetricPaddingMode paddingMode, Void* pPaddingInfo, Int32 estimatedSize)
        /_/src/libraries/Common/src/System/Security/Cryptography/RSACng.SignVerify.cs(71,0): at System.Security.Cryptography.RSACng.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSA.cs(363,0): at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSAWrapper.cs(107,0): at System.Security.Cryptography.RSAWrapper.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSA.cs(344,0): at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/RSAPssX509SignatureGenerator.cs(106,0): at System.Security.Cryptography.X509Certificates.RSAPssX509SignatureGenerator.SignData(Byte[] data, HashAlgorithmName hashAlgorithm)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/Pkcs10CertificationRequestInfo.cs(77,0): at System.Security.Cryptography.X509Certificates.Pkcs10CertificationRequestInfo.ToPkcs10Request(X509SignatureGenerator signatureGenerator, HashAlgorithmName hashAlgorithm)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs(377,0): at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSigningRequest(X509SignatureGenerator signatureGenerator)
        /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateRequest.cs(283,0): at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSigningRequest()
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/CertificateCreation/CertificateRequestLoadTests.cs(392,0): at System.Security.Cryptography.X509Certificates.Tests.CertificateCreation.CertificateRequestLoadTests.VerifySignature_RSA_PSS(String hashAlgorithm)
           at InvokeStub_CertificateRequestLoadTests.VerifySignature_RSA_PSS(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    System.Security.Cryptography.X509Certificates.Tests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.X509Certificates.Tests  Total: 1344, Errors: 0, Failed: 1, Skipped: 0, Time: 18.739s
----- end Thu 09/22/2022 21:08:41.04 ----- exit code 1 ----------------------------------------------------------
```

**Comment by vcsjones** [comment]
Duplicate of #29683
