### ISSUE TITLE
WasmTestOnBrowser-System.Private.Xml.Tests - GENERAL_FAILURE

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#76134]
Runfo failures in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22wasmtestonbrowser-system.private.xml.tests+work+item%22)
- Platform: `net7.0-Browser-Release-wasm-Mono_Release-WasmTestOnBrowser-(Windows.Amd64.Server2022.Open)windows.amd64.server2022.open`

Day | Run | Details
-- | -- | --
9/23 | Rolling run [28100](https://runfo.azurewebsites.net/view/build/?number=28100) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f997c730347841ecb9/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.c190c73c.log?%3Fhelixlogtype%3Dresult) - InvalidOperationException
9/21 | Rolling run [24630](https://runfo.azurewebsites.net/view/build/?number=24630) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d5a7337f04754c51a3/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.c6028933.log?%3Fhelixlogtype%3Dresult) - InvalidOperationException
9/20 | 2x Rolling run [24096](https://runfo.azurewebsites.net/view/build/?number=24096) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0b0b911e9a9a42e588/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.71eca106.log?%3Fhelixlogtype%3Dresult) & [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-996d1a815413482980/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.5746fad1.log?%3Fhelixlogtype%3Dresult) - InvalidOperationException
9/20 | Rolling run [23279](https://runfo.azurewebsites.net/view/build/?number=23279) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-bbd0b54a8645473faf/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.d5648536.log?%3Fhelixlogtype%3Dresult) - InvalidOperationException
9/19 | Rolling run [22721](https://runfo.azurewebsites.net/view/build/?number=22721) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8367caff4cb749499f/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.0508f1f3.log?%3Fhelixlogtype%3Dresult) - InvalidOperationException
9/18 | Rolling run [21535](https://runfo.azurewebsites.net/view/build/?number=21535) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-61a326dc2b8f4d0eb4/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.efae9b84.log?%3Fhelixlogtype%3Dresult) - ChannelClosedException
9/17 | Rolling run [21283](https://runfo.azurewebsites.net/view/build/?number=21283) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5d9d19187fdd4eb49d/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.8036c146.log?%3Fhelixlogtype%3Dresult) - ChannelClosedException
9/16 | Rolling run [20550](https://runfo.azurewebsites.net/view/build/?number=20550) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b434c4e3b79440d7b0/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.417f526f.log?%3Fhelixlogtype%3Dresult) - ChannelClosedException
9/16 | Rolling run [19690](https://runfo.azurewebsites.net/view/build/?number=19690) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2265aaea8262447890/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.85b207f2.log?%3Fhelixlogtype%3Dresult) - ChannelClosedException
9/15 | Rolling run [18995](https://runfo.azurewebsites.net/view/build/?number=18995) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4522af83cf7041c084/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.98def8ac.log?%3Fhelixlogtype%3Dresult) - ChannelClosedException

Failure examples:

**InvalidOperationException** - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f997c730347841ecb9/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.c190c73c.log?%3Fhelixlogtype%3Dresult) on 9/23:
```
[23:37:33] info: Starting:    System.Private.Xml.Tests.dll
[23:38:40] fail: 224964280
[23:38:40] fail: 224964280
[23:38:40] fail: 224964280
[23:38:40] fail: 225333728
[23:38:40] info: WASM EXIT 1
[23:38:40] info: Waiting to flush log messages with a timeout of 120 secs ..
[23:38:40] info: WASM EXIT 1
[23:38:40] fail: Application has finished with exit code TESTS_FAILED but 0 was expected
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMKTNI0N1333", Request id "0HMKTNI0N1333:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Message processor is not running. Make sure to call RunAsync first
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.InvokeAsync(String message, Boolean isError) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 94
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunConsoleMessagesPump(WebSocket socket, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 196
         at Microsoft.DotNet.XHarness.CLI.Commands.WebServer.TestWebServerStartup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs:line 163
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
XHarness exit code: 71 (GENERAL_FAILURE)

C:\helix\work\workitem\e\wasm_build\AppBundle>set EXIT_CODE=71 
----- end Fri 09/23/2022 23:38:44.97 ----- exit code 71 ----------------------------------------------------------
```

**ChannelClosedException** - [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-61a326dc2b8f4d0eb4/WasmTestOnBrowser-System.Private.Xml.Tests/1/console.efae9b84.log?%3Fhelixlogtype%3Dresult) on 
```
[23:13:04] info: Starting:    System.Private.Xml.Tests.dll
[23:14:16] fail: 245597000
[23:14:16] fail: 245597000
[23:14:16] fail: 245597000
[23:14:16] fail: 245597120
[23:14:16] info: WASM EXIT 1
[23:14:16] info: Waiting to flush log messages with a timeout of 120 secs ..
[23:14:16] info: WASM EXIT 1
[23:14:16] fail: Flushing log messages failed with: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.ProcessMessage(String message, Boolean isError) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 200
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.RunAsync(CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 82
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.RunAsync(CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 82
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.CompleteAndFlushAsync(Nullable`1 timeout) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 106. Ignoring.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMKPPD0JB2H6", Request id "0HMKPPD0JB2H6:00000001": An unhandled exception was thrown by the application.
      System.Threading.Channels.ChannelClosedException: The channel has been closed.
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunConsoleMessagesPump(WebSocket socket, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 196
         at Microsoft.DotNet.XHarness.CLI.Commands.WebServer.TestWebServerStartup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs:line 163
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[23:14:16] fail: [out of order message from the browser]: http://127.0.0.1:49195/dotnet.js 4:1872 "[main] websocket closed: [object CloseEvent]" CloseEvent
[23:14:16] info: Could not process message: {"method":"console.log","payload":"WASM EXIT 1","arguments":["WASM EXIT 1"]}
[23:14:16] info: Application has finished with exit code TESTS_FAILED. But the log processor failed with GENERAL_FAILURE.
[23:14:16] fail: Application has finished with exit code GENERAL_FAILURE but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)

C:\helix\work\workitem\e\wasm_build\AppBundle>set EXIT_CODE=71 
----- end Sun 09/18/2022 23:14:20.41 ----- exit code 71 ----------------------------------------------------------
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
The xharness exception can be ignored. The real issue is https://github.com/dotnet/runtime/issues/74302 .

**Comment by lewing** [comment]
looks like a manifestation of https://github.com/dotnet/runtime/pull/76033

**Comment by carlossanlop** [comment]
It's affecting various System.Xml tests. They all show this error message:

```
[21:36:12] warn: Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
[21:51:05] fail: Tests timed out. Killing driver service pid 4661
[21:51:06] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

- Pipeline: `runtime-extra-platforms`
- Queues:
  - `Build Browser wasm Linux Release LibraryTests_Threading`
  - `Build Browser wasm Linux Release LibraryTests_Threading_PerfTracing`
- Job results:
  - Threading: https://dev.azure.com/dnceng-public/public/_build/results?buildId=38971&view=logs&j=5e0663a6-779c-5be5-6d4c-61295b043a58&t=a6da8bfe-2e5e-5d0c-f321-5907e9da992a
  - Threading_PerfTracing: https://dev.azure.com/dnceng-public/public/_build/results?buildId=38971&view=logs&j=92c81310-cb26-5923-f96e-b7c73963fa3d&t=0aa9a844-8701-5b62-3bc4-3a39f7c23650

- Log files:
  - System.Xml.RW.XmlSystemPathResolver
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76565-merge-ca460d6a395347bab6/WasmTestOnBrowser-System.Xml.RW.XmlSystemPathResolver.Tests/1/console.37cb0c0c.log?helixlogtype=result

  - System.Xml.XmlSchema.XmlSchemaValidatorApi https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76565-merge-ca460d6a395347bab6/WasmTestOnBrowser-System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests/1/console.17381658.log?helixlogtype=result

  - System.Xml.XmlSchemaSet https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76565-merge-ca460d6a395347bab6/WasmTestOnBrowser-System.Xml.XmlSchemaSet.Tests/1/console.e1c804c4.log?helixlogtype=result

**Comment by radical** [comment]
Ignore all the failures in these two:

- Build Browser wasm Linux Release LibraryTests_Threading
- Build Browser wasm Linux Release LibraryTests_Threading_PerfTracing

The job is *orange* because we want to ignore the test failures. It will be *red* for build failures though, and those we are interested in.

**Comment by lewing** [comment]
we think this is fixed in mail now so please make noise if you see it in a test
