### ISSUE TITLE
System.Collections.Concurrent.Tests.ConcurrentStackTests.ManyConcurrentAddsTakes_ForceContentionWithToArray - NullReferenceException 

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#76141]
Test affected:
- **ManyConcurrentAddsTakes_ForceContentionWithToArray** - `System.Collections.Concurrent.Tests.ConcurrentStackTests.ManyConcurrentAddsTakes_ForceContentionWithToArray`

Runfo failures in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.collections.concurrent.tests.concurrentstacktests.manyconcurrentaddstakes_forcecontentionwithtoarray%22)

As of 9/24:
Day | Run | OS | Notes
-- | -- | -- | --
9/22 | Rolling run [27269](https://runfo.azurewebsites.net/view/build/?number=27269) (release/7.0) | net7.0-tvOS-Release-arm64-Mono_Release-OSX.1100.Amd64.AppleTV.Open | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-52ffd6eab66542c3af/System.Collections.Concurrent.Tests/1/console.76da0915.log?%3Fhelixlogtype%3Dresult)
9/12 | Rolling run [13766](https://runfo.azurewebsites.net/view/build/?number=13766) (main) | net7.0-tvOS-Release-arm64-Mono_Release-OSX.1100.Amd64.AppleTV.Open | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-52ffd6eab66542c3af/System.Collections.Concurrent.Tests/1/console.76da0915.log?%3Fhelixlogtype%3Dresult)

Error:
```
System.Collections.Concurrent.Tests.ConcurrentStackTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)

System.NullReferenceException : Object reference not set to an instance of an object
   at System.Runtime.Intrinsics.Vector128`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Count()
   at System.SpanHelpers.IndexOfValueType[Int32,DontNegate`1](Int32& searchSpace, Int32 value, Int32 length)
   at System.Array.IndexOf[Int32](Int32[] array, Int32 value, Int32 startIndex, Int32 count)
   at System.Array.InternalArray__ICollection_Contains[Int32](Int32 item)
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(Double seconds)
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

**Comment by krwq** [comment]
cc: @tannergooding as FYI since it might be related to Vector128

**Comment by krwq** [comment]
marking it as 8.0 since it looks like some recent regression

**Comment by tannergooding** [comment]
> System.NullReferenceException : Object reference not set to an instance of an object
   at System.Runtime.Intrinsics.Vector128`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Count()
   at System.SpanHelpers.IndexOfValueType[Int32,DontNegate`1](Int32& searchSpace, Int32 value, Int32 length)
   at System.Array.IndexOf[Int32](Int32[] array, Int32 value, Int32 startIndex, Int32 count)
   at System.Array.InternalArray__ICollection_Contains[Int32](Int32 item)
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(Double seconds)
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)

Is there a reliable repro? I expect there is something else "wrong" here since:
1. `Vector128<T>` is a value type
2. `get_Count` is an intrinsic, but even if it wasn't the software fallback is a trivial type check + "integer division" (really its a constant)
