### ISSUE TITLE
[wasm] perf builds breaking with a linker NRE

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#76167]
[Log](https://helixri107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-af06872332e64e7bad/wasm.x64.micro.net7.0.Partition14/1/console.a13d9c8b.log?sv=2021-08-06&se=2022-12-25T01%3A28%3A58Z&sr=c&sp=rl&sig=jLIhft6393msXytcyU%2BfO432001i9AR2R%2B%2B4UIS3j%2FU%3D):

```
  BenchmarkDotNet.Autogenerated -> /home/helixbot/work/AEA909DD/w/A60B0989/e/performance/artifacts/bin/for-running/MicroBenchmarks/a1b9703b-4c4e-43a4-9666-c96d19422335/bin/net7.0/browser-wasm/a1b9703b-4c4e-43a4-9666-c96d19422335.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://github.com/dotnet/linker/issues [/home/helixbot/work/AEA909DD/w/A60B0989/e/performance/artifacts/bin/for-running/MicroBenchmarks/a1b9703b-4c4e-43a4-9666-c96d19422335/BenchmarkDotNet.Autogenerated.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.Steps.MarkStep.IsInterfaceImplementationMethodNeededByTypeDueToInterface(OverrideInformation overrideInformation)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedTypesWithInterfaces()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

Another instance - [log](https://helixri107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-57868ea8baa7473ab1/wasmaot.x64.micro.net7.0.Partition20.Attempt.2/1/console.69d95d5e.log?sv=2021-08-06&se=2022-12-20T16%3A26%3A43Z&sr=c&sp=rl&sig=qx%2FPpHxjvpjjL%2BEADx2As%2FTO8qk7G5GchRJGpIyLge4%3D).
(these ran on `PERFTIGER198`)

**Comment by vitek-karas** [comment]
@jtschuster Could you please take a look? It's in the interface marking magic :wink:

**Comment by radical** [comment]
This was hit again on the perf pipeline. [Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2020709&view=logs&j=10348dd7-5cd6-5c42-fc55-e890e0795f10&t=3fe50c48-466c-5f5d-0411-aa33700b2a9d):
```
[2022/10/14 01:22:41][INFO]   Fatal error in IL Linker
[2022/10/14 01:22:41][INFO]   Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Steps.MarkStep.IsInterfaceImplementationMethodNeededByTypeDueToInterface(OverrideInformation overrideInformation)
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Steps.MarkStep.ProcessMarkedTypesWithInterfaces()
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Steps.MarkStep.Process()
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Pipeline.Process(LinkContext context)
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Driver.Run(ILogger customLogger)
[2022/10/14 01:22:41][INFO]      at Mono.Linker.Driver.Main(String[] args)
```

**Comment by radical** [comment]
An `IndexOutOfRangeException`, [build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2020876&view=logs&j=10348dd7-5cd6-5c42-fc55-e890e0795f10&t=3fe50c48-466c-5f5d-0411-aa33700b2a9d):

```
[2022/10/14 05:18:36][INFO]   Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
[2022/10/14 05:18:36][INFO]      at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Steps.MarkStep.ProcessOverride(OverrideInformation overrideInformation)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Steps.MarkStep.ProcessVirtualMethod(MethodDefinition method)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Steps.MarkStep.ProcessVirtualMethods()
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Steps.MarkStep.Process()
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Pipeline.Process(LinkContext context)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Driver.Run(ILogger customLogger)
[2022/10/14 05:18:36][INFO]      at Mono.Linker.Driver.Main(String[] args)
```

And another NRE, but with a different trace, [build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2020709):

```
[2022/10/14 01:14:58][INFO]   Fatal error in IL Linker
[2022/10/14 01:14:58][INFO]   Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
[2022/10/14 01:14:58][INFO]      at Mono.Cecil.MethodReference.get_ReturnType()
[2022/10/14 01:14:58][INFO]      at Mono.Cecil.MetadataResolver.GetMethod(Collection`1 methods, MethodReference reference)
[2022/10/14 01:14:58][INFO]      at Mono.Cecil.MetadataResolver.GetMethod(TypeDefinition type, MethodReference reference)
[2022/10/14 01:14:58][INFO]      at Mono.Cecil.MetadataResolver.Resolve(MethodReference method)
[2022/10/14 01:14:58][INFO]      at Mono.Cecil.ModuleDefinition.Resolve(MethodReference method)
[2022/10/14 01:14:58][INFO]      at Mono.Cecil.MethodReference.Resolve()
[2022/10/14 01:14:58][INFO]      at Mono.Linker.LinkContext.TryResolve(MethodReference methodReference)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Dataflow.CompilerGeneratedState.<GetCompilerGeneratedStateForType>g__ProcessMethod|11_0(MethodDefinition method, <>c__DisplayClass11_0&)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Dataflow.CompilerGeneratedState.GetCompilerGeneratedStateForType(TypeDefinition type)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Dataflow.CompilerGeneratedState.TryGetCompilerGeneratedCalleesForUserMethod(MethodDefinition method, List`1& callees)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.ProcessQueue()
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.Process()
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Pipeline.Process(LinkContext context)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Driver.Run(ILogger customLogger)
[2022/10/14 01:14:58][INFO]      at Mono.Linker.Driver.Main(String[] args)
```
