### ISSUE TITLE
Test failure baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#76161]
Run: [runtime-coreclr ilasm 20220924.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28964&view=ms.vss-test-web.build-test-results-tab&runId=585370&resultId=100027&paneView=debug)

Failed test:
```
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- baseservices\\finalization\\CriticalFinalizer\\CriticalFinalizer.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\AD88097F\w\A75B093B\uploads\Reports\baseservices.finalization\CriticalFinalizer\CriticalFinalizer.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\AD88097F\p\ildasm.exe /raweh /unicode /out=CriticalFinalizer.dasm.il CriticalFinalizer.dll
C:\h\w\AD88097F\p\ilasm.exe /output=CriticalFinalizer.asm.dll  CriticalFinalizer.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'CriticalFinalizer.dasm.il'  to EXE --> 'CriticalFinalizer.asm.dll'
Source file is UNICODE

Assembled method Normal::Finalize
Assembled method Normal::.ctor
Assembled method Critical::Finalize
Assembled method Critical::.ctor
Assembled method CriticalFinalizerTest?<>c__DisplayClass0_0::.ctor
Assembled method CriticalFinalizerTest?<>c__DisplayClass0_0::<AllocateObjects>b__0
Assembled method CriticalFinalizerTest::AllocateObjects
Assembled method CriticalFinalizerTest::Main
Creating PE file

Emitting classes:
Class 1:Normal
Class 2:Critical
Class 3:CriticalFinalizerTest
Class 4:CriticalFinalizerTest�<>c__DisplayClass0_0

Emitting fields and methods:
Global
Class 1Fields: 1;Methods: 2;
Class 2Fields: 2;Methods: 2;
Class 3Methods: 2;
Class 4Fields: 1;Methods: 2;
Resolving local member refs: 18 -> 18 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Class 2
Class 3
Class 4
Method Implementations (total): 2
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
"C:\h\w\AD88097F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  CriticalFinalizer.asm.dll
Finalized 0 Normal and 0 Critical objects.
The first Critical object was finalized after 0 Normal objects.
END EXECUTION OF IL{D}ASM BINARY - FAILED 101 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AD88097F\p
C:\h\w\AD88097F\w\A75B093B\e\baseservices\finalization\CriticalFinalizer\CriticalFinalizer.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_finalization._CriticalFinalizer_CriticalFinalizer_._CriticalFinalizer_CriticalFinalizer_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by MichalStrehovsky** [comment]
The test was disabled in #76131. Tracked in #76041.
