### ISSUE TITLE
X509Certificate2.CreateFromPemFile throws error when reading AWS pem file

### ISSUE THREAD

**Issue by edcastanohunter** [dotnet/runtime#76242]
### Description

I am trying to use the following cert file from AWS [https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem](https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem).

But when I try to  load it using _X509Certificate2.CreateFromPemFile_ I got the following exception:

```
Type: System.Security.Cryptography.CryptographicException
Message: The key contents do not contain a PEM, the content is malformed, or the key does not match the certificate.
Stack trace:   
 at System.Security.Cryptography.X509Certificates.X509Certificate2.ExtractKeyFromPem[TAlg](ReadOnlySpan`1 keyPem, String[] labels, Func`1 factory, Func`2 import)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPem(ReadOnlySpan`1 certPem, ReadOnlySpan`1 keyPem)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile(String certPemFilePath, String keyPemFilePath)
   at Program.<Main>$(String[] args) in C:\_WS\MM\PlayingAndValidating\Program.cs:line 15
```

### Reproduction Steps

1. Downloa d the certificate from AWS: [https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem](https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem)
2. Create a simple console app using net6.0
3. copy the downloaded file into the project and make the project copy always that file 
4. run the following code 
```cs

using System.Security.Cryptography.X509Certificates;
var certP = "rds-ca-2019-root.pem";
var cert = X509Certificate2.CreateFromPemFile(certP, null);

```

### Expected behavior

It should be able to read that pem file.

### Actual behavior

It is throwing an exception.

**Comment by edcastanohunter** [comment]
Thank you Kevin. It would be good if we have a more accurate message for it. Don't you think?
