### ISSUE TITLE
CI Failure: No templates or subcommands found matching: 'wasmbrowser'

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76269]
Found in this `release/7.0` backport PR: https://github.com/dotnet/runtime/pull/76113

- Affected queues:
  - Build Browser wasm windows Release WasmBuildTests
  - Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=31924&view=logs&j=f386e426-bcac-5c89-397e-589b8da0ec42&t=e6a4592a-90b9-5f43-2cfd-2dff490c67e2&l=92
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76113-merge-4e66aa5eef7845f99b/Workloads-.WasmTemplateTests/1/console.091adacb.log?helixlogtype=result
<details>
<summary>Callstack</summary>

```
Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(extraNewArgs: "") [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(450,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(String extraNewArgs)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Debug_niuw5u2p.nc2
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(extraNewArgs: "") [FINISHED] Time: 0.4310924s
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(extraNewArgs: "-f net7.0") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(extraNewArgs: "-f net7.0") [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser -f net7.0
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(450,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(String extraNewArgs)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser -f net7.0 -  in pwd C:\helix\work\workitem\e\browser_Debug_vuhnbond.bev
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildAndRun(extraNewArgs: "-f net7.0") [FINISHED] Time: 0.435404s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "") [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(259,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(252,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_hyicqmdc.u5m
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "") [FINISHED] Time: 0.40324s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(259,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(252,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_rbloyrtr.tdp
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 0.4205703s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(259,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(252,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_bckygxm2.mll
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: True, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 0.3907695s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: True, extraProperties: "") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: True, extraProperties: "") [FINISHED] Time: 10.0202522s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: True, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: True, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 16.4909201s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: True, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: True, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 15.1624844s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "") [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(259,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(252,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_g1ewi4fa.e2h
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "") [FINISHED] Time: 0.4302892s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(259,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(252,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_udaebfmm.1rj
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 0.4351256s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(259,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserRunTwiceWithAndThenWithoutBuildAsync(String config, String extraProperties, Boolean runOutsideProjectDirectory)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(252,0): at Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(Boolean forConsole, Boolean runOutsideProjectDirectory, String extraProperties)
        --- End of stack trace from previous location ---
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_wzgi2svi.u34
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: False, runOutsideProjectDirectory: False, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 0.4133537s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: False, extraProperties: "") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: False, extraProperties: "") [FINISHED] Time: 9.2818516s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: False, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: False, extraProperties: "<OutputPath>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 16.7358627s
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: False, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.RunWithDifferentAppBundleLocations(forConsole: True, runOutsideProjectDirectory: False, extraProperties: "<WasmAppDir>C:\\Users\\ContainerAdministrator\\App"...) [FINISHED] Time: 16.7346603s
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(config: "Debug") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(config: "Debug") [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(34,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(83,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(String config)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Debug_vsj03yti.uca
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(config: "Debug") [FINISHED] Time: 0.4530369s
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(config: "Release") [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(config: "Release") [FAIL]
       Expected 0 exit code but got 103: C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser 
      Standard Output:
      [] No templates or subcommands found matching: 'wasmbrowser'.
      [] 
      [] To list installed templates similar to 'wasmbrowser', run:
      []    dotnet new list wasmbrowser
      [] To search for the templates on NuGet.org, run:
      []    dotnet new search wasmbrowser
      [] 
      [] 
      [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
      
      Stack Trace:
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(34,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/BuildTestBase.cs(460,0): at Wasm.Build.Tests.BuildTestBase.CreateWasmTemplateProject(String id, String template, String extraArgs)
        /_/src/tests/BuildWasmApps/Wasm.Build.Tests/WasmTemplateTests.cs(83,0): at Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(String config)
           at InvokeStub_WasmTemplateTests.BrowserBuildThenPublish(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        [] Executing (Captured Output) - C:\helix\work\workitem\e\\dotnet-net7\dotnet.exe new wasmbrowser  -  in pwd C:\helix\work\workitem\e\browser_Release_bngatvm5.21p
        [] No templates or subcommands found matching: 'wasmbrowser'.
        [] 
        [] To list installed templates similar to 'wasmbrowser', run:
        []    dotnet new list wasmbrowser
        [] To search for the templates on NuGet.org, run:
        []    dotnet new search wasmbrowser
        [] 
        [] 
        [] For details on the exit code, refer to https://aka.ms/templating-exit-codes#103
    Wasm.Build.Tests.WasmTemplateTests.BrowserBuildThenPublish(config: "Release") [FINISHED] Time: 0.4098817s
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: False, relinking: False) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: False, relinking: False) [FINISHED] Time: 12.9759399s
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: False, relinking: False) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: False, relinking: False) [FINISHED] Time: 12.2737466s
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: False, relinking: True) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Debug", aot: False, relinking: True) [FINISHED] Time: 23.2329858s
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Release", aot: False, relinking: False) [STARTING]
    Wasm.Build.Tests.WasmTemplateTests.ConsolePublishAndRun(config: "Release", aot: False, relinking: False) [FINISHED] Time: 39.4286425s
============== DELETING THE BUILDS =============
  Finished:    Wasm.Build.Tests
=== TEST EXECUTION SUMMARY ===
   Wasm.Build.Tests  Total: 28, Errors: 0, Failed: 10, Skipped: 0, Time: 1613.811s
```
</details>

**Comment by radical** [comment]
https://github.com/dotnet/runtime/pull/76113 has a fix for this now.

**Comment by carlossanlop** [comment]
Thanks @radical. Do we need the same fix in main?

**Comment by radical** [comment]
It's included in https://github.com/dotnet/runtime/pull/76124 .

**Comment by radical** [comment]
Closing this since the fix has been pushed to https://github.com/dotnet/runtime/pull/76113, and it's passing.
