### ISSUE TITLE
WASM CI failure: Wasm.Browser.Threads.Sample - SharedArrayBuffer is not defined, exit code 71, GENERAL_FAILURE

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76331]
Saw this for the first time in a `release/7.0` backport PR: https://github.com/dotnet/runtime/pull/76052

Please help determine if a backport is needed to get this fixed.

- Pipeline: runtime-extra-platforms
- Queue: Build Browser wasm Linux Release LibraryTests_Threading
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=29620&view=logs&j=5e0663a6-779c-5be5-6d4c-61295b043a58&t=a6da8bfe-2e5e-5d0c-f321-5907e9da992a
- Log file: https://helix.dot.net/api/2019-06-17/jobs/32e62e8c-0a02-43ea-ae20-151bccd041af/workitems/Wasm.Browser.Threads.Sample/console
- Test: Wasm.Browser.Threads.Sample
<details>
<summary>Callstack</summary>

```
===========================================================================================================
/datadisks/disk1/work/AD1809AE/w/AFA409DD/e /datadisks/disk1/work/AD1809AE/w/AFA409DD/e /datadisks/disk1/work/AD1809AE/w/AFA409DD/e
[1.0.0-prerelease.22411.1+5ebf69650b9f7b4ecab485be840b3022420f7812] XHarness command issued: wasm test-browser --app=. --browser=Chrome --html-file=index.html --output-directory=/datadisks/disk1/work/AD1809AE/w/AFA409DD/uploads/xharness-output -- Wasm.Browser.Threads.Sample.dll
[03:41:37] info: Starting chromedriver with args: --headless --incognito --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --enable-features=NetworkService,NetworkServiceInProcess --allow-insecure-localhost --disable-breakpad --disable-component-extensions-with-background-pages --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-ipc-flooding-protection --force-color-profile=srgb --metrics-recording-only
Starting ChromeDriver 100.0.4896.0 (ecbece54737a3df72a99f07de4850663ea5a48d3-refs/heads/main@{#972765}) on port 40921
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[03:41:40] info: user code in createDotnetRuntime callback
[03:41:40] fail: [out of order message from the browser]: http://127.0.0.1:41677/main.js 10:24 ReferenceError: SharedArrayBuffer is not defined
                     at http://127.0.0.1:41677/dotnet.js:14:13769
                     at http://127.0.0.1:41677/main.js:64:87
[03:41:40] info: WASM EXIT 2
[03:41:40] info: Waiting to flush log messages with a timeout of 120 secs ..
[03:41:40] fail: Application has finished with exit code HELP_SHOWN but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
/datadisks/disk1/work/AD1809AE/w/AFA409DD/e /datadisks/disk1/work/AD1809AE/w/AFA409DD/e
----- end Mon Sep 26 03:41:40 UTC 2022 ----- exit code 71 ----------------------------------------------------------
```
</details>

**Comment by carlossanlop** [comment]
Among the same [job results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76052-merge-32e62e8c0a0243eaae/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.bc61724a.log?helixlogtype=result) there are a few somewhat similar failures, but I'm not sure if they are related:

-----

- Test: System.Net.Http.Functional.Tests
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76052-merge-32e62e8c0a0243eaae/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.bc61724a.log?helixlogtype=result

<details>
<summary>Callstack</summary>

```
[03:41:55] fail: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.SendAsync_RequestVersion20_HttpNotHttps_NoUpgradeRequest
[03:41:55] info: System.Net.WebSockets.WebSocketException : An internal WebSocket error occurred. Please see the innerException, if present, for more details. 
[03:41:55] info: ---- System.Runtime.InteropServices.JavaScript.JSException : TypeError: Failed to execute 'send' on 'WebSocket': The provided ArrayBufferView value must not be shared.
[03:41:55] info:    at System.Net.WebSockets.BrowserWebSocket.SendAsyncCore(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
[03:41:55] info:    at System.Net.Test.Common.LoopbackServer.ListenAsync()
[03:41:55] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[03:41:55] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.SendAsync_RequestVersion20_HttpNotHttps_NoUpgradeRequest()
[03:41:55] info: --- End of stack trace from previous location ---
[03:41:55] info: ----- Inner Stack Trace -----
[03:41:55] info:    at System.Net.WebSockets.BrowserInterop.WebSocketSend(JSObject webSocket, IntPtr bufferPtr, Int32 bufferLength, Int32 messageType, Boolean endOfMessage)
[03:41:55] info:    at System.Net.WebSockets.BrowserInterop.UnsafeSendSync(JSObject jsWs, ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage)
[03:41:55] info:    at System.Net.WebSockets.BrowserWebSocket.SendAsyncCore(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
[03:41:55] info:     at xc (http://127.0.0.1:43015/dotnet.js:5:95619)
[03:41:55] info:     at Object.Oc [as ws_wasm_send] (http://127.0.0.1:43015/dotnet.js:5:94269)
[03:41:55] info:     at _bound_js_INTERNAL_ws_wasm_send (https://dotnet.generated.invalid/_bound_js_INTERNAL_ws_wasm_send:11:21)
[03:41:55] info:     at Object.li (http://127.0.0.1:43015/dotnet.js:5:58352)
[03:41:55] info:     at _mono_wasm_invoke_bound_function (http://127.0.0.1:43015/dotnet.js:14:121580)
[03:41:55] info:     at do_icall (http://127.0.0.1:43015/dotnet.wasm:wasm-function[339]:0x226a1)
[03:41:55] info:     at do_icall_wrapper (http://127.0.0.1:43015/dotnet.wasm:wasm-function[307]:0x21b3f)
[03:41:55] info:     at interp_exec_method (http://127.0.0.1:43015/dotnet.wasm:wasm-function[243]:0x131c2)
[03:41:55] info:     at interp_entry (http://127.0.0.1:43015/dotnet.wasm:wasm-function[291]:0x2151f)
[03:41:55] info:     at interp_entry_static_0 (http://127.0.0.1:43015/dotnet.wasm:wasm-function[366]:0x2320e)
```
</details>

-----

- Test: System.Net.WebSockets.Client
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76052-merge-32e62e8c0a0243eaae/WasmTestOnBrowser-System.Net.WebSockets.Client.Tests/1/console.cd1a18c9.log?helixlogtype=result

<details>
<summary>Callstack</summary>

```
[03:42:22] fail: [FAIL] System.Net.WebSockets.Client.Tests.InvokerArraySegmentSendReceiveTest.SendReceive_Concurrent_Success(server: ws://127.0.0.1:44415/WebSocket/EchoWebSocket.ashx)
[03:42:22] info: System.Net.WebSockets.WebSocketException : An internal WebSocket error occurred. Please see the innerException, if present, for more details. 
[03:42:22] info: ---- System.Runtime.InteropServices.JavaScript.JSException : TypeError: Failed to execute 'send' on 'WebSocket': The provided ArrayBufferView value must not be shared.
[03:42:22] info:    at System.Net.WebSockets.BrowserWebSocket.SendAsyncCore(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
[03:42:22] info:    at System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_Concurrent_Success(Uri server)
[03:42:22] info: --- End of stack trace from previous location ---
[03:42:22] info: ----- Inner Stack Trace -----
[03:42:22] info:    at System.Net.WebSockets.BrowserInterop.WebSocketSend(JSObject webSocket, IntPtr bufferPtr, Int32 bufferLength, Int32 messageType, Boolean endOfMessage)
[03:42:22] info:    at System.Net.WebSockets.BrowserInterop.UnsafeSendSync(JSObject jsWs, ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage)
[03:42:22] info:    at System.Net.WebSockets.BrowserWebSocket.SendAsyncCore(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
[03:42:22] info:     at xc (http://127.0.0.1:44415/dotnet.js:5:95619)
[03:42:22] info:     at Object.Oc [as ws_wasm_send] (http://127.0.0.1:44415/dotnet.js:5:94269)
[03:42:22] info:     at _bound_js_INTERNAL_ws_wasm_send (https://dotnet.generated.invalid/_bound_js_INTERNAL_ws_wasm_send:11:21)
[03:42:22] info:     at Object.li (http://127.0.0.1:44415/dotnet.js:5:58352)
[03:42:22] info:     at _mono_wasm_invoke_bound_function (http://127.0.0.1:44415/dotnet.js:14:121580)
[03:42:22] info:     at do_icall (http://127.0.0.1:44415/dotnet.wasm:wasm-function[339]:0x226a1)
[03:42:22] info:     at do_icall_wrapper (http://127.0.0.1:44415/dotnet.wasm:wasm-function[307]:0x21b3f)
[03:42:22] info:     at interp_exec_method (http://127.0.0.1:44415/dotnet.wasm:wasm-function[243]:0x131c2)
[03:42:22] info:     at interp_entry (http://127.0.0.1:44415/dotnet.wasm:wasm-function[291]:0x2151f)
[03:42:22] info:     at interp_entry_static_0 (http://127.0.0.1:44415/dotnet.wasm:wasm-function[366]:0x2320e)
[03:42:22] fail: [out of order message from the browser]: http://127.0.0.1:44415/dotnet.js 4:1403 "proxyConsole failed: TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Worker'\n    |     property 'pthread' -> object with constructor 'Object'\n    --- property 'worker' closes the circle"
[03:42:22] fail: [out of order message from the browser]: http://127.0.0.1:44415/dotnet.js 4:1403 "proxyConsole failed: TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Worker'\n    |     property 'pthread' -> object with constructor 'Object'\n    --- property 'worker' closes the circle"
```
</details>

-----

- Test: System.Xml.XmlSchema.XmlSchemaValidatorApi
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76052-merge-32e62e8c0a0243eaae/WasmTestOnBrowser-System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests/1/console.aa11c46a.log?helixlogtype=result

<details>
<summary>Callstack</summary>

```
===========================================================================================================
/datadisks/disk1/work/AD1809AE/w/B26009B7/e /datadisks/disk1/work/AD1809AE/w/B26009B7/e /datadisks/disk1/work/AD1809AE/w/B26009B7/e
[1.0.0-prerelease.22411.1+5ebf69650b9f7b4ecab485be840b3022420f7812] XHarness command issued: wasm test-browser --app=. --output-directory=/datadisks/disk1/work/AD1809AE/w/B26009B7/uploads/xharness-output --web-server-use-cop -s dotnet.js.symbols --symbol-patterns wasm-symbol-patterns.txt --symbolicator WasmSymbolicator.dll,Microsoft.WebAssembly.Internal.SymbolicatorWrapperForXHarness -- --run WasmTestRunner.dll System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[03:42:28] info: Starting chromedriver with args: --headless --incognito --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --enable-features=NetworkService,NetworkServiceInProcess --allow-insecure-localhost --disable-breakpad --disable-component-extensions-with-background-pages --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-ipc-flooding-protection --force-color-profile=srgb --metrics-recording-only
Starting ChromeDriver 100.0.4896.0 (ecbece54737a3df72a99f07de4850663ea5a48d3-refs/heads/main@{#972765}) on port 36917
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[03:42:30] info: Incoming arguments: --run WasmTestRunner.dll System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[03:42:30] info: Application arguments: --run WasmTestRunner.dll System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[03:42:30] info: browser: [main] Console websocket connected.
[03:42:30] info: http://127.0.0.1:38513/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[03:42:30] info: http://127.0.0.1:38513/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[03:42:30] info: http://127.0.0.1:38513/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[03:42:30] info: http://127.0.0.1:38513/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[03:42:35] info: Initializing.....
[03:42:36] info: Discovering: System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll (method display = ClassAndMethod, method display options = None)
[03:42:36] info: Discovered:  System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll (found 186 of 186 test cases)
[03:42:36] info: Using random seed for test cases: 814076898
[03:42:36] info: Using random seed for collections: 814076898
[03:42:36] info: Starting:    System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests.dll
[03:42:42] warn: Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread
[03:57:29] fail: Tests timed out. Killing driver service pid 3766
[03:57:29] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
/datadisks/disk1/work/AD1809AE/w/B26009B7/e /datadisks/disk1/work/AD1809AE/w/B26009B7/e
----- end Mon Sep 26 03:57:29 UTC 2022 ----- exit code 71 ----------------------------------------------------------
```

</details>


Etc.

**Comment by carlossanlop** [comment]
Some tests in the [Build Browser wasm Linux Release LibraryTests_Threading_PerfTracing](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76052-merge-32e62e8c0a0243eaae/WasmTestOnBrowser-System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests/1/console.aa11c46a.log?helixlogtype=result) queue is also being affected by this (return error code 71).

**Comment by radical** [comment]
The PerfTracing, and Threading jobs have known failures, and are unstable currently. That's why we have the test failures ignored on CI, for now. Unless somebody is actively tracking them, I don't think issues on it will be useful.
cc @lambdageek

**Comment by lewing** [comment]
that particular error suggests the page wasn't served properly which is puzzling to me
