### ISSUE TITLE
AES cryptographic library working ok in .NET 4.7.2 gives the following error in .NET 6  when decrypting existing data: System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed. 

### ISSUE THREAD

**Issue by motohead400** [dotnet/runtime#76389]
### Description

I'm trying to use a method from a .NET 4.7.2 library of mine in a .NET 6 project to read existing encrypted data from the database.  When running the method in .NET 6 I get the following error: System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.  The same method reads the same data with no issues when running in .NET 4.7.2

This appears to be similar to this issue: https://github.com/dotnet/runtime/issues/46672

I tried setting FeedbackSize to 128 but that didn't help. 

Below is the code for the method:

```C#
        public static string Decrypt_AES_BytesToString(byte[] cipherText, byte[] key)
        {
            // Check arguments.
            if (cipherText == null || cipherText.Length <= 0)
                throw new ArgumentNullException("cipherText");
            if (key == null || key.Length <= 0)
                throw new ArgumentNullException("key");            

            // Check arguments.
            if (cipherText == null || cipherText.Length <= 0)
                throw new ArgumentNullException("cipherText");
            if (key == null || key.Length <= 0)
                throw new ArgumentNullException("Key");

            // Declare the string used to hold
            // the decrypted text.
            string plaintext = null;

            // Create an AesCryptoServiceProvider object
            // with the specified key and IV.
            using (AesCryptoServiceProvider aesAlg = new AesCryptoServiceProvider())
            {
                aesAlg.Key = key;                
                aesAlg.Padding = PaddingMode.PKCS7;
               
                // Create the streams used for decryption.
                using (MemoryStream msDecrypt = new MemoryStream(cipherText))
                {
                    var iv = new byte[16];
                    msDecrypt.Read(iv, 0, 16);  // Pull the IV from the first 16 bytes of the encrypted value
                    using (CryptoStream csDecrypt = new CryptoStream(msDecrypt, aesAlg.CreateDecryptor(aesAlg.Key, iv), CryptoStreamMode.Read))
                    {
                        using (StreamReader srDecrypt = new StreamReader(csDecrypt))
                        {
                            // Read the decrypted bytes from the decrypting stream
                            // and place them in a string.
                            plaintext = srDecrypt.ReadToEnd();
                        }
                    }
                }
            }

            return plaintext;
        }
```

### Reproduction Steps

Use the following methods to encrypt data in .NET 4.7.2.  Then try to decrypt that data using the decryption method pasted in the description above in .NET 6

```C#
        public static byte[] Encrypt_AES_StringToBytes(string plainText, byte[] key)
        {
            // Check arguments.
            if (plainText == null || plainText.Length <= 0)
                throw new ArgumentNullException("plainText");
            if (key == null || key.Length <= 0)
                throw new ArgumentNullException("key");                       

            // Create an AesCryptoServiceProvider object with the specified key.
            using (AesCryptoServiceProvider aesAlg = new AesCryptoServiceProvider())
            {
                aesAlg.Key = key;
                aesAlg.Padding = PaddingMode.PKCS7;
                return Encrypt_AES_StringToBytes(plainText, aesAlg);
            }

            // Return the encrypted bytes from the memory stream.
            
        }

        public static byte[] Encrypt_AES_StringToBytes(string plainText, AesCryptoServiceProvider aesCryptoServiceProvider)
        {
            byte[] encrypted;
            // Create an encryptor to perform the stream transform.
            ICryptoTransform encryptor = aesCryptoServiceProvider.CreateEncryptor(aesCryptoServiceProvider.Key, aesCryptoServiceProvider.IV);

            // Create the streams used for encryption.
            using (MemoryStream msEncrypt = new MemoryStream())
            {
                msEncrypt.Write(aesCryptoServiceProvider.IV, 0, aesCryptoServiceProvider.IV.Length);  // Add the IV to the first 16 bytes of the encrypted value
                using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                {
                    using (StreamWriter swEncrypt = new StreamWriter(csEncrypt))
                    {
                        //Write all data to the stream.
                        swEncrypt.Write(plainText);
                    }
                    encrypted = msEncrypt.ToArray();
                }
            }

            return encrypted;
        }
```

### Expected behavior

I expect the data to be decrypted like it would be normally

### Actual behavior

I get the following exception:

```
Exception: 
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken, Boolean useAsync)
   at System.Security.Cryptography.CryptoStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
```

### Configuration

I'm running the code in .NET 6 using Visual Studio 2022 on Windows 10 in 64 bit mode.

**Comment by vcsjones** [comment]
You could try changing it to something like this:


```csharp
var iv = new byte[16];
var totalRead = 0;
while (totalRead < iv.Length)
{
    totalRead += msDecrypt.Read(iv, totalRead, iv.Length - totalRead);
}
```

**Comment by bartonjs** [comment]
I'm not seeing any failure with running that encrypt as-shown on net472, saving the results to a file, reading the file in net6.0 and decrypting it with decrypt-as-shown.

If you think you're getting data truncation you can try decrypting in PaddingMode.None; but I suspect that your problem may be that you're not actually producing/using the same key in both applications.

**Comment by motohead400** [comment]
> I'm not seeing any failure with running that encrypt as-shown on net472, saving the results to a file, reading the file in net6.0 and decrypting it with decrypt-as-shown.
> 
> If you think you're getting data truncation you can try decrypting in PaddingMode.None; but I suspect that your problem may be that you're not actually producing/using the same key in both applications.

Oh my gosh, you're correct bartonjs.  I'm so sorry for wasting your time on this issue.  The encryption key had an ampersand in the web.config file, which had to be written as "&amp;"  When I moved this to the appsettings.json file I brain farted and replaced the &amp; with a "@" symbol instead of "&"
