### ISSUE TITLE
[release/3.1] CI failure: System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76651]
I've been seeing this failure in some corefx `release/3.1` PRs. Latest example: https://github.com/dotnet/corefx/pull/43161

- Affected queues: `Linux Build musl_arm64_Release` and `MacOS Build x64_Release`
- Job results:
  - Linux https://dev.azure.com/dnceng-public/public/_build/results?buildId=40240&view=logs&j=b56707d3-1a71-5591-8c27-c40f122945bd&t=ebb0ea3d-ee94-5738-aa0e-ff0231a3b283&l=35
  - MacOS https://dev.azure.com/dnceng-public/public/_build/results?buildId=40240&view=logs&j=c0301585-8551-5e4f-e903-7e15f25b7319&t=ac085211-69c5-5ada-e2f3-cc83ef45c356&l=37
- Log files:
  - Linux https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-43161-merge-6b4afb3b59424e299a/System.Globalization.Extensions.Tests/1/console.b097cbc9.log?helixlogtype=result
  - MacOS https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-corefx-refs-pull-43161-merge-efcbdf50df0b43b794/System.Globalization.Extensions.Tests/1/console.bbaaed0d.log?helixlogtype=result
- Callstacks
<details>
<summary>Linux</summary>

```
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Globalization.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Globalization.Extensions.Tests (found 27 test cases)
  Starting:    System.Globalization.Extensions.Tests (parallel test collections = on, max threads = 2)
    System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid [FAIL]
      Assert.All() Failure: 1 out of 200 items in the collection did not pass.
      [174]: Item: System.Globalization.Tests.Unicode_6_0_IdnaTest
             System.Exception: Expected IdnMapping.GetUnicode("\uD803\uDE78\u3002\uD803\uDEA9\u094D") to throw an ArgumentException.
                at System.Globalization.Tests.IdnMappingIdnaConformanceTests.<>c.<GetUnicode_Invalid>b__3_1(IConformanceIdnaTest entry) in /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs:line 122
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
      Stack Trace:
        /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs(125,0): at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid()
    System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid [FAIL]
      Assert.All() Failure: 1 out of 194 items in the collection did not pass.
      [168]: Item: System.Globalization.Tests.Unicode_6_0_IdnaTest
             System.Exception: Expected IdnMapping.GetAscii("\uD803\uDE78\u3002\uD803\uDEA9\u094D") to throw an ArgumentException.
                at System.Globalization.Tests.IdnMappingIdnaConformanceTests.<>c.<GetAscii_Invalid>b__2_1(IConformanceIdnaTest entry) in /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs:line 96
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
      Stack Trace:
        /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs(99,0): at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid()
  Finished:    System.Globalization.Extensions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Globalization.Extensions.Tests  Total: 294, Errors: 0, Failed: 2, Skipped: 0, Time: 0.787s
/root/helix/work/workitem/e
----- end Tue Oct 4 18:36:01 UTC 2022 ----- exit code 1 ----------------------------------------------------------
```
</details>

<details>
<summary>MacOS</summary>

```
===========================================================================================================
/private/tmp/helix/working/C5B30A64/w/AD220950/e /private/tmp/helix/working/C5B30A64/w/AD220950/e
  Discovering: System.Globalization.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Globalization.Extensions.Tests (found 27 test cases)
  Starting:    System.Globalization.Extensions.Tests (parallel test collections = on, max threads = 6)
    System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid [FAIL]
      Assert.All() Failure: 1 out of 200 items in the collection did not pass.
      [174]: Item: System.Globalization.Tests.Unicode_6_0_IdnaTest
             System.Exception: Expected IdnMapping.GetUnicode("\uD803\uDE78\u3002\uD803\uDEA9\u094D") to throw an ArgumentException.
                at System.Globalization.Tests.IdnMappingIdnaConformanceTests.<>c.<GetUnicode_Invalid>b__3_1(IConformanceIdnaTest entry) in /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs:line 122
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
      Stack Trace:
        /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs(125,0): at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetUnicode_Invalid()
    System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid [FAIL]
      Assert.All() Failure: 1 out of 194 items in the collection did not pass.
      [168]: Item: System.Globalization.Tests.Unicode_6_0_IdnaTest
             System.Exception: Expected IdnMapping.GetAscii("\uD803\uDE78\u3002\uD803\uDEA9\u094D") to throw an ArgumentException.
                at System.Globalization.Tests.IdnMappingIdnaConformanceTests.<>c.<GetAscii_Invalid>b__2_1(IConformanceIdnaTest entry) in /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs:line 96
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 36
      Stack Trace:
        /_/src/System.Globalization.Extensions/tests/IdnMapping/IdnMappingIdnaConformanceTests.cs(99,0): at System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid()
  Finished:    System.Globalization.Extensions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Globalization.Extensions.Tests  Total: 295, Errors: 0, Failed: 2, Skipped: 0, Time: 0.607s
/private/tmp/helix/working/C5B30A64/w/AD220950/e
----- end Tue Oct 4 11:17:04 PDT 2022 ----- exit code 1 ----------------------------------------------------------
```
<details>

**Comment by carlossanlop** [comment]
`Get_Ascii_Invalid` is also failing. It's a test a few lines above. I'll disable it in the same PR: https://github.com/dotnet/corefx/pull/43162

**Comment by tarekgh** [comment]
Closing it per the PR https://github.com/dotnet/corefx/pull/43162
