### ISSUE TITLE
[wasm] Cannot handle variables of type dynamic

### ISSUE THREAD

**Issue by yamachu** [dotnet/runtime#76663]
### Description

Project code created with templates such as wasmconsole crashes when dealing with variables of dynamic type.
It is reproduced even if `PublishTrimmed` is set to `false`.

### Reproduction Steps

1. `$ dotnet new wasmconsole`
2. Write code that uses dynamic types to Program.cs .  (`dynamic a = 1; Console.WriteLine(a);`)
3. `dotnet publish -c Release`
4. `node bin/Release/net7.0/browser-wasm/AppBundle/main.mjs`

### Expected behavior

Can handle variables of type dynamic on wasm runtime.

### Actual behavior

Throw Exception

```
ManagedError: The type initializer for 'AnonHostModuleHolder' threw an exception.
    at $o (file:///Users/yk-yamada/dev/repro/bin/Release/net7.0/browser-wasm/AppBundle/dotnet.js:5:37754)
    at Ws (file:///Users/yk-yamada/dev/repro/bin/Release/net7.0/browser-wasm/AppBundle/dotnet.js:5:55546)
    at Object._bound_cs__MyClass_Greeting (https://dotnet.generated.invalid/_bound_cs__MyClass_Greeting:9:3)
    at file:///Users/yk-yamada/dev/repro/bin/Release/net7.0/browser-wasm/AppBundle/main.mjs:23:30 {
  [Symbol(wasm js_owned_gc_handle)]: 38
```

### Other information

I noticed this when using Dapper.
I know that I can work around it by using methods via System.Object or specific classes.
like this
https://github.com/yamachu/pokedex-net-webassembly-without-blazor/blob/20390e7fdab4cb908a599dd730ed936368683045/dotnet/src/Shared/src/PokedexUsecase.cs#L60-L88

If there is no support for dynamic types, it would be nice to see some restrictions added to Learn document.

**Comment by marek-safar** [comment]
I don't think we want to support dynamic in WASM AOT but should explore how to enable better error messages for such cases.

@lewing thoughts?

**Comment by lewing** [comment]
cc @vargaz

**Comment by vargaz** [comment]
I'm not sure we want to support this on wasm.
