### ISSUE TITLE
CI Linux failure: SyncHttpHandler_HttpProtocolTests_Dribble.GetAsync_ResponseHasNormalLineEndings_Success

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76678]
Seen today in a `release/7.0` PR.

- Affected PR: https://github.com/dotnet/runtime/pull/76565
- Queue: `Libraries Test Run release coreclr Linux x64 Release`
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=38971&view=logs&j=b9b7de4d-2126-5581-6453-1576f9aaac5f&t=db048d48-40e8-5399-9b14-d587763f33ff
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76565-merge-20ba7d17175d4e7ea0/System.Net.Http.Functional.Tests.Attempt.3/2/console.31709ece.log?helixlogtype=result

Callstack:
```
System.Net.Http.Functional.Tests.SyncHttpHandler_HttpProtocolTests_Dribble.GetAsync_ResponseHasNormalLineEndings_Success(lineEnding: "\r\n") [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/Common/tests/System/Net/Http/HttpProtocolTests.cs(377,0): at System.Net.Http.Functional.Tests.HttpProtocolTests.<>c__DisplayClass19_0.<<GetAsync_ResponseHasNormalLineEndings_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(103,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpProtocolTests.cs(369,0): at System.Net.Http.Functional.Tests.HttpProtocolTests.GetAsync_ResponseHasNormalLineEndings_Success(String lineEnding)
        --- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Last hit in kusto from 19.8. on RC1, closing.

**Comment by antonfirsov** [comment]
This started to fail regularly on `ubuntu.1804.amd64.open.rt`, reopening.

**Comment by MihaZupan** [comment]
Not seeing any more `PassedOnRerun` entries for this test after #93139 was merged.
