### ISSUE TITLE
WASM CI failure: System.Runtime.InteropServices.JavaScript.Http.Tests.HttpRequestMessageTest.BlobUri_Marshal_CorrectValues_Browser

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#76676]
Found in this unrelated release/7.0 PR: https://github.com/dotnet/runtime/pull/76565

Please help determine if this needs a fix to get backported to the 7.0 branch.

- Pipeline: `runtime-extra-platforms`
- Queue: `Build Browser wasm Linux Release LibraryTests_Threading`
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=38971&view=logs&j=5e0663a6-779c-5be5-6d4c-61295b043a58&t=a6da8bfe-2e5e-5d0c-f321-5907e9da992a&l=115
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76565-merge-ba131cfd615f47bf82/WasmTestOnBrowser-System.Private.Runtime.InteropServices.JavaScript.Tests/1/console.0feee59b.log?helixlogtype=result

<details>
<summary>Callstack example</summary>

```
[21:33:36] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Http.Tests.HttpRequestMessageTest.BlobUri_Marshal_CorrectValues_Browser
[21:33:36] info: System.Runtime.InteropServices.JavaScript.JSException : Error: Assert failed: Unknow converter for type 13 at 2 
[21:33:36] info:     at ho (http://127.0.0.1:42311/dotnet.js:5:35495)
[21:33:36] info:     at Object.ui (http://127.0.0.1:42311/dotnet.js:5:57369)
[21:33:36] info:     at _mono_wasm_bind_js_function (http://127.0.0.1:42311/dotnet.js:14:120525)
[21:33:36] info:     at do_icall (http://127.0.0.1:42311/dotnet.wasm:wasm-function[339]:0x22795)
[21:33:36] info:     at do_icall_wrapper (http://127.0.0.1:42311/dotnet.wasm:wasm-function[307]:0x21b3f)
[21:33:36] info:     at interp_exec_method (http://127.0.0.1:42311/dotnet.wasm:wasm-function[243]:0x131c2)
[21:33:36] info:     at interp_runtime_invoke (http://127.0.0.1:42311/dotnet.wasm:wasm-function[242]:0x12072)
[21:33:36] info:     at mono_jit_runtime_invoke (http://127.0.0.1:42311/dotnet.wasm:wasm-function[8263]:0x1aaac2)
[21:33:36] info:     at do_runtime_invoke (http://127.0.0.1:42311/dotnet.wasm:wasm-function[2115]:0x8c6f0)
[21:33:36] info:     at mono_runtime_invoke_checked (http://127.0.0.1:42311/dotnet.wasm:wasm-function[2113]:0x8c666)
[21:33:36] info:    at System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindJSFunctionImpl(String functionName, String moduleName, ReadOnlySpan`1 signatures)
[21:33:36] info:    at System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindJSFunction(String functionName, String moduleName, ReadOnlySpan`1 signatures)
[21:33:36] info:    at System.Net.Http.BrowserHttpInterop.AbortResponse(JSObject fetchResponse)
[21:33:36] info:    at System.Net.Http.WasmFetchResponse.Dispose()
[21:33:36] info:    at System.Net.Http.BrowserHttpContent.Dispose(Boolean disposing)
[21:33:36] info:    at System.Net.Http.HttpContent.Dispose()
[21:33:36] info:    at System.Net.Http.HttpResponseMessage.Dispose(Boolean disposing)
[21:33:36] info:    at System.Net.Http.HttpResponseMessage.Dispose()
[21:33:36] info:    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
[21:33:36] info:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[21:33:36] info:    at System.Runtime.InteropServices.JavaScript.Http.Tests.HttpRequestMessageTest.BlobUri_Marshal_CorrectValues_Browser()
[21:33:36] info: --- End of stack trace from previous location ---
```
</details>

**Comment by maraf** [comment]
It comes from a "threading" job which is marked as orange, failures are expected.
No need to fix at the moment.
