### ISSUE TITLE
Microsoft.DotNet.CoreSetup.Test.HostActivation.StartupHooks.Muxer_activation* tests failed

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#76681]
Installer-coreclr-Linux_musl_x64-Release
https://dev.azure.com/dnceng-public/public/_build/results?buildId=41475&view=ms.vss-test-web.build-test-results-tab&runId=836728&resultId=100173&paneView=debug

```
2022-10-05T17:47:33.3169099Z   Tests succeeded: /__w/1/s/artifacts/bin/AppHost.Bundle.Tests/Release/net7.0/AppHost.Bundle.Tests.dll [net7.0|x64]
2022-10-05T17:50:09.9899791Z VSTest : error : Tests failed: /__w/1/s/artifacts/TestResults/Release/HostActivation.Tests_net7.0_x64.html [net7.0|x64] [/__w/1/s/src/installer/tests/HostActivation.Tests/HostActivation.Tests.csproj]
2022-10-05T17:50:10.0037776Z ##[error]VSTest(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Tests failed: /__w/1/s/artifacts/TestResults/Release/HostActivation.Tests_net7.0_x64.html [net7.0|x64]
2022-10-05T17:50:10.2194526Z   Running tests: /__w/1/s/artifacts/bin/Microsoft.NET.HostModel.AppHost.Tests/Release/net7.0/Microsoft.NET.HostModel.AppHost.Tests.dll [net7.0|x64]
2022-10-05T17:50:10.2239540Z   Running tests: /__w/1/s/artifacts/bin/Microsoft.NET.HostModel.Bundle.Tests/Release/net7.0/Microsoft.NET.HostModel.Bundle.Tests.dll [net7.0|x64]
2022-10-05T17:53:59.6472126Z   Tests succeeded: /__w/1/s/artifacts/bin/Microsoft.NET.HostModel.AppHost.Tests/Release/net7.0/Microsoft.NET.HostModel.AppHost.Tests.dll [net7.0|x64]
2022-10-05T17:56:15.1856178Z   Tests succeeded: /__w/1/s/artifacts/bin/Microsoft.NET.HostModel.Bundle.Tests/Release/net7.0/Microsoft.NET.HostModel.Bundle.Tests.dll [net7.0|x64]
2022-10-05T17:56:15.2320955Z 
2022-10-05T17:56:15.2322011Z Build FAILED.
2022-10-05T17:56:15.2338432Z 
2022-10-05T17:56:15.2340089Z VSTest : error : Tests failed: /__w/1/s/artifacts/TestResults/Release/HostActivation.Tests_net7.0_x64.html [net7.0|x64] [/__w/1/s/src/installer/tests/HostActivation.Tests/HostActivation.Tests.csproj]
2022-10-05T17:56:15.2341413Z     0 Warning(s)
2022-10-05T17:56:15.2341942Z     1 Error(s)
2022-10-05T17:56:15.2342166Z 
2022-10-05T17:56:15.2342681Z Time Elapsed 00:32:07.31
```
```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/bin /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=8.0.0-ci
Standard Output:
MSBuild version 17.4.0-preview-22428-01+14c24b2d3 for .NET
/__w/1/s/.dotnet/sdk/7.0.100-rc.1.22431.12/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=linux-musl-x64 --property:MNAVersion=8.0.0-ci -property:PublishDir=/__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./StartupHookWithParameter.csproj
/__w/1/s/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/StartupHookWithParameter.csproj]
StartupHookWithParameter -> /__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/bin/Debug/net7.0/StartupHookWithParameter.dll

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/bin /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=8.0.0-ci
Standard Output:
MSBuild version 17.4.0-preview-22428-01+14c24b2d3 for .NET
/__w/1/s/.dotnet/sdk/7.0.100-rc.1.22431.12/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=linux-musl-x64 --property:MNAVersion=8.0.0-ci -property:PublishDir=/__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./StartupHookWithParameter.csproj
/__w/1/s/.dotnet/sdk/7.0.100-rc.1.22431.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/StartupHookWithParameter.csproj]
StartupHookWithParameter -> /__w/1/s/artifacts/tests/Release/ha/rwohkpum.0rj/StartupHookWithParameter/bin/Debug/net7.0/StartupHookWithParameter.dll

---- The following constructor parameters did not have matching fixture data: SharedTestState fixture


Stack trace

----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 333
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.StartupHooks.SharedTestState..ctor() in /_/src/installer/tests/HostActivation.Tests/StartupHooks.cs:line 800
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

This doesn't seem to be a dupe of https://github.com/dotnet/runtime/issues/74328 even though a similar query is linked there. the build failed with code 1.

**Comment by elinor-fung** [comment]
@danmoseley I must be missing it - can you point out what looks different from https://github.com/dotnet/runtime/issues/74328? They both seem successful `dotnet build/publish` with exit code 1 to me.

**Comment by danmoseley** [comment]
I thought "exit code 1 even when the build passes" sounded like an infra bug (Eg in MSBuild?), whereas this is just a test failure (??)

**Comment by elinor-fung** [comment]
In this case (and in a lot of the tests under installer/), the test actually runs `dotnet build/publish` and checks the exit code as part of the test setup, so it comes through as a test failure when that command exits with 1 even when it successfully builds/publishes.

**Comment by danmoseley** [comment]
Ah - the title of #74328 is super misleading then. It might as well say "Some installer test(s) failed". Now I am not sure what it is encompassing.

**Comment by elinor-fung** [comment]
The root problem is around `dotnet build/publish` per the title, but it manifests itself in our repo in multiple ways - commonly in the installer tests and also in wasm tests - basically anything that runs the command and fails if the error code is not 0.

I added a line at the top of the description to hopefully make it clearer that we are seeing installer test failures as a result. I'm going to close this against https://github.com/dotnet/runtime/issues/74328.
