### ISSUE TITLE
`ActivityListener` callbacks `ActivityStarted` and `ActivityStopped` intermittently triggered twice for same `Activity`

### ISSUE THREAD

**Issue by TimothyMothra** [dotnet/runtime#76757]
### Description

Hello,
I'm investigating an issue where `ActivityStopped` is invoked twice, resulting in duplicate Traces in OpenTelemetry.

- Additional test logs here: https://github.com/Azure/azure-sdk-for-net/pull/31567
- Full test class here: https://github.com/Azure/azure-sdk-for-net/blob/074dd56aaa4f951c97b896435254594173385279/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/E2ETelemetryItemValidation/TracesTests.cs

### Reproduction Steps

I've only been able to reproduce this on Azure SDK's AzDO build servers.
I've seen this issue occur on all combinations of Ubuntu, Windows, MacOs and NET461, NETCore3.1, NET60 (Azure SDKs test matrix).
This most often reproduces while using a `LoggerFactory` and creating a Log within an `Activity`, but I've seen other combinations without Logs.

I have not been able to reproduce this on my dev box or on OpenTelemetry-dotnet's GH build servers.

<details>
  <summary>Example 1: When using only `ActivityListener` I've seen `ActivityStarted` invoked twice for the same `Activity`. This is that test:</summary>

```csharp
        [Theory]
        [InlineData(LogLevel.Information)]
        [InlineData(LogLevel.Warning)]
        [InlineData(LogLevel.Error)]
        [InlineData(LogLevel.Critical)]
        [InlineData(LogLevel.Debug)]
        [InlineData(LogLevel.Trace)]
        public void LogWithinActivity_ActivityListener(LogLevel logLevel)
        {
            // SETUP
            var uniqueTestId = Guid.NewGuid();

            var activitySourceName = $"activitySourceName{uniqueTestId}";
            using var activitySource = new ActivitySource(activitySourceName);
            //Assert.False(activitySource.HasListeners());

            var logCategoryName = $"logCategoryName{uniqueTestId}";

            var activityLogs = new List<string>();

            var listener = new ActivityListener
            {
                ActivityStarted = activity => activityLogs.Add($"ActivityStarted: {activity.OperationName}, {activity.Id}"),
                ActivityStopped = activity => activityLogs.Add($"ActivityStopped: {activity.OperationName}, {activity.Id}"),
                ShouldListenTo = activitySource => activitySource.Name.Equals(activitySourceName),
                // SampleUsingParentId = (ref ActivityCreationOptions<string> activityOptions) => ActivitySamplingResult.AllDataAndRecorded,
                Sample = (ref ActivityCreationOptions<ActivityContext> activityOptions) => ActivitySamplingResult.AllDataAndRecorded,
            };

            ActivitySource.AddActivityListener(listener);
            //Assert.True(activitySource.HasListeners());

            var loggerFactory = LoggerFactory.Create(builder =>
            {
            });

            // ACT
            string spanId, traceId;
            string activityName = $"TestActivity {nameof(this.LogWithinActivity_ActivityListener)} {logLevel}";

            using (var activity = activitySource.StartActivity(name: activityName))
            {
                spanId = activity.SpanId.ToHexString();
                traceId = activity.TraceId.ToHexString();

                var logger = loggerFactory.CreateLogger(logCategoryName);

                logger.Log(
                    logLevel: logLevel,
                    eventId: 0,
                    exception: null,
                    message: "Hello {name}.",
                    args: new object[] { "World" });
            }

            // CLEANUP
            listener.Dispose();
            loggerFactory.Dispose();

            // ASSERT
            try
            {
                Assert.True(activityLogs.Count == 2, "Unexpected count of activity logs.");
            }
            catch (Exception)
            {
                this._outputHelper.WriteLine($"Activities Logs:{activityLogs.Count}\n");
                this._outputHelper.WriteLine($"Expected TraceId:{traceId}  Expected SpanId:{spanId}\n");

                foreach (var aLog in activityLogs)
                {
                    this._outputHelper.WriteLine(aLog);
                }

                throw;
            }
        }
```

[LINK TO BUILD LOG](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1902232&view=logs&j=e55623aa-2fbf-55e5-4c09-cf8db4d32009&t=4275b670-3b16-5f74-df27-48dcab0a8d51&l=262)
```
  Failed Azure.Monitor.OpenTelemetry.Exporter.Tests.E2ETelemetryItemValidation.TracesTests.LogWithinActivity_ActivityListener(logLevel: Error) [190 ms]
  Error Message:
   Unexpected count of activity logs.
Expected: True
Actual:   False
  Stack Trace:
     at Azure.Monitor.OpenTelemetry.Exporter.Tests.E2ETelemetryItemValidation.TracesTests.LogWithinActivity_ActivityListener(LogLevel logLevel) in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/E2ETelemetryItemValidation/TracesTests.cs:line 419
  Standard Output Messages:
 Activities Logs:3
 
 Expected TraceId:92a7b68c9db1ac45c964b638b6014929  Expected SpanId:4009e925dcc179b0
 
 ActivityStarted: TestActivity LogWithinActivity_ActivityListener Error, 00-92a7b68c9db1ac45c964b638b6014929-4009e925dcc179b0-01
 ActivityStarted: TestActivity LogWithinActivity_ActivityListener Error, 00-92a7b68c9db1ac45c964b638b6014929-4009e925dcc179b0-01
 ActivityStopped: TestActivity LogWithinActivity_ActivityListener Error, 00-92a7b68c9db1ac45c964b638b6014929-4009e925dcc179b0-01

```

</details>

<details>
  <summary>Example 2: When using OpenTelemetry's `InMemoryExporter` I've seen `ActivityStopped` invoked twice for the same `Activity`. This is that test:</summary>

This test subscribes to OpenTelemetry's EventSource logs which show that ActivityStopped was invoked twice.
OpenTelemetry's `ActivityListener` is here: https://github.com/open-telemetry/opentelemetry-dotnet/blob/622583c6ffaea2e3d83d4fcb8935c6a8dbc6f81f/src/OpenTelemetry/Trace/TracerProviderSdk.cs#L89

```csharp
        [Theory]
        [InlineData(LogLevel.Information)]
        [InlineData(LogLevel.Warning)]
        [InlineData(LogLevel.Error)]
        [InlineData(LogLevel.Critical)]
        [InlineData(LogLevel.Debug)]
        [InlineData(LogLevel.Trace)]
        public void LogWithinActivity_InMemoryExporterOnly(LogLevel logLevel)
        {
            // SETUP
            var uniqueTestId = Guid.NewGuid();

            using var listener = new TestListener();

            var activitySourceName = $"activitySourceName{uniqueTestId}";
            using var activitySource = new ActivitySource(activitySourceName);

            var logCategoryName = $"logCategoryName{uniqueTestId}";

            List<Activity> exportedActivities = new List<Activity>();
            List<LogRecord> exportedLogs = new List<LogRecord>();

            var tracerProvider = Sdk.CreateTracerProviderBuilder()
                .AddSource(activitySourceName)
                .AddInMemoryExporter(exportedActivities)
                .Build();

            var loggerFactory = LoggerFactory.Create(builder =>
            {
                builder
                    .AddFilter<OpenTelemetryLoggerProvider>(logCategoryName, logLevel)
                    .AddOpenTelemetry(options =>
                    {
                        options.AddInMemoryExporter(exportedLogs);
                    });
            });

            // ACT
            string spanId, traceId;
            string activityName = $"TestActivity {nameof(this.LogWithinActivity_InMemoryExporterOnly)} {logLevel}";

            using (var activity = activitySource.StartActivity(name: activityName))
            {
                spanId = activity.SpanId.ToHexString();
                traceId = activity.TraceId.ToHexString();

                var logger = loggerFactory.CreateLogger(logCategoryName);

                logger.Log(
                    logLevel: logLevel,
                    eventId: 0,
                    exception: null,
                    message: "Hello {name}.",
                    args: new object[] { "World" });
            }

            // CLEANUP
            tracerProvider.Dispose();
            loggerFactory.Dispose();

            // ASSERT
            try
            {
                Assert.True(exportedActivities.Count == 1, "Unexpected count of exported Activities.");
                Assert.True(exportedLogs.Count == 1, "Unexpected count of exported Logs.");
            }
            catch (Exception)
            {
                this._outputHelper.WriteLine($"Activities Count:{exportedActivities.Count}  Logs Count:{exportedLogs.Count}\n");
                this._outputHelper.WriteLine($"Expected TraceId:{traceId}  Expected SpanId:{spanId}\n");

                foreach (var activity in exportedActivities)
                {
                    this._outputHelper.WriteLine("Exported Activity:");
                    this._outputHelper.WriteLine($"\tDisplayName: {activity.DisplayName}");
                    this._outputHelper.WriteLine($"\tId: {activity.Id}");
                    this._outputHelper.WriteLine($"\tTraceId: {activity.TraceId.ToHexString()}");
                    this._outputHelper.WriteLine($"\tSpanId: {activity.SpanId.ToHexString()}");
                }

                _outputHelper.WriteLine($"EVENT SOURCE LOGS:");
                foreach (var e in listener.Events)
                {
                    _outputHelper.WriteLine(EventSourceEventFormatting.Format(e));
                }

                throw;
            }
        }
```

[LINK TO BUILD LOG](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1902494&view=logs&j=df47e0b9-f7f0-5a6d-001b-395452402a29&t=4e7be197-90e0-54b4-32b4-fc5516b8477e&l=312)
```
  Failed Azure.Monitor.OpenTelemetry.Exporter.Tests.E2ETelemetryItemValidation.TracesTests.LogWithinActivity_InMemoryExporterOnly(logLevel: Debug) [56 ms]
  Error Message:
   Unexpected count of exported Activities.
Expected: True
Actual:   False
  Stack Trace:
     at Azure.Monitor.OpenTelemetry.Exporter.Tests.E2ETelemetryItemValidation.TracesTests.LogWithinActivity_InMemoryExporterOnly(LogLevel logLevel) in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Azure.Monitor.OpenTelemetry.Exporter.Tests/E2ETelemetryItemValidation/TracesTests.cs:line 320
  Standard Output Messages:
 Activities Count:2  Logs Count:1
 
 Expected TraceId:d5d68140817d14920cd72c74d92061c7  Expected SpanId:131694d936087c63
 
 Exported Activity:
 	DisplayName: TestActivity LogWithinActivity_InMemoryExporterOnly Debug
 	Id: 00-d5d68140817d14920cd72c74d92061c7-131694d936087c63-01
 	TraceId: d5d68140817d14920cd72c74d92061c7
 	SpanId: 131694d936087c63
 Exported Activity:
 	DisplayName: TestActivity LogWithinActivity_InMemoryExporterOnly Debug
 	Id: 00-d5d68140817d14920cd72c74d92061c7-131694d936087c63-01
 	TraceId: d5d68140817d14920cd72c74d92061c7
 	SpanId: 131694d936087c63
 EVENT SOURCE LOGS:
 Activity started. OperationName = 'TestActivity LogWithinActivity_InMemoryExporterOnly Debug', Id = '00-d5d68140817d14920cd72c74d92061c7-131694d936087c63-01'.
 Activity stopped. OperationName = 'TestActivity LogWithinActivity_InMemoryExporterOnly Debug', Id = '00-d5d68140817d14920cd72c74d92061c7-131694d936087c63-01'.
 Activity stopped. OperationName = 'TestActivity LogWithinActivity_InMemoryExporterOnly Debug', Id = '00-d5d68140817d14920cd72c74d92061c7-131694d936087c63-01'.
 'TracerProvider' Disposed.
 'OpenTelemetryLoggerProvider' Disposed.
```

</details>

### Expected behavior

For a given `Activity`, I expect `ActivityListener` callbacks `ActivityStarted` and `ActivityStopped` to be invoked exactly once.

### Actual behavior

When using OpenTelemetry's `InMemoryExporter` I've seen `ActivityStopped` invoked twice for the same `Activity`.

When using only `ActivityListener` I've seen `ActivityStarted` invoked twice for the same `Activity`.

### Configuration

OS: Ubuntu, Windows, MacOs 
Framework: NET461, NETCore3.1, NET60

**Comment by tarekgh** [comment]
@TimothyMothra this is possible to happen when adding or removing `ActivitySource` listeners objects during the notification callbacks. In your example, could you try adding some delay before your objects disposer and watch if you still see the failures? The other idea could be instead of adding a delay before the disposer, you may declare the `listener` as the following:

```C#
using var listener = new ActivityListener
```

just add `using` word in front of the line. This apply to `traceProvider` too.

**Comment by TimothyMothra** [comment]
I tested with the `using` and the issue still occurs. Is this functionally different than manually disposing?
I did test with a timer and this issue occurred less often, but it did still occur.

I can work around this for unit tests, but I'm concerned how an OTel customer would mitigate the issue.

**Comment by tarekgh** [comment]
We never get any issue from OTel. Also, even if this happened, I don't think it would be harmful in any way. It is very very unlikely and if it does happen, getting the event twice is unlikely to cause any problem. missing event would be more concerning. by that I am closing this issue but feel free to respond back if you have any question.
