### ISSUE TITLE
.NET 6 Alpine container rarely fails in FileSystemEnumerator on HostBuilder.Build()

### ISSUE THREAD

**Issue by WilliamNadeau** [dotnet/runtime#76763]
### Description

I'm exploring deploying .NET 6 containers on top of the alpine base image hosted in AWS Fargate. My test application is a simple console application that wakes up, writes to stdout, and then quits. Most of the time, it works without issue, but rarely it fails. It's failing out of the startup. See the stack trace below.

I read that this may be issues with musl compatibility and that musl 1.2.2 may rectify the issue, but I verified that the image is using musl 1.2.2 and the issue persists.

I swapped out the base image for debian and ubuntu base images and the problems disappear.

| Base Image | Success |
| --- | --- |
| dotnet/runtime:6.0.9-alpine3.16 | Failure |
| dotnet/runtime:6.0.9-jammy | Success |
| dotnet/runtime:6.0.9-bullseye-slim | Success |

This is hard to reproduce as it only occurs about 0.06% of the time. I've seen a few other issues floating around having issues with FileSystemEnumerator failing on alpine, but no resolutions. The other tickets I've seen just end up using a different base image (https://github.com/dotnet/runtime/issues/43144#issuecomment-892754678 for example)

```
Unhandled exception. System.IO.IOException: The process cannot access the file '/app/runtimes/win/lib/net6.0' because it is being used by another process.
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken) |
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in /jenkins/workspace/ntry.ExampleDockerConsole_master/Sentry.ExampleDockerBatch/Program.cs:line 3
   at Program.<Main>(String[] args)
```

### Reproduction Steps

1. Create a .NET 6 console application with Docker support
2. Switch the dockerfile to base from dotnet/runtime:6.0.9-alpine3.16
3. Run on Fargate until it fails

### Expected behavior

The application should not be rarely running into IO exceptions that crash the app.

### Actual behavior

The application raises an exception crashing the application.

### Known Workarounds

Use one of the other .NET base images that doesn't use Alpine Linux.

### Configuration

.NET 6
dotnet/runtime:6.0.9-alpine3.16 on top of a AWS Linux Fargate container

### Other information

There's other tickets that seem to point to a possible issue with FileSystemEnumerable on Alpine:

- https://github.com/dotnet/extensions/issues/1902
- https://github.com/dotnet/runtime/issues/43144

**Comment by adamsitnik** [comment]
Hi @WilliamNadeau 

Thank you for a detailed bug report.

> Create a .NET 6 console application with Docker support

Are you sure it's plain console app, not something more complex like ASP.NET that actually uses `FileSystemWatcher`?

Could you please try updating `musl` to `1.2.2` as described https://github.com/dotnet/runtime/issues/43144#issuecomment-1154247195 and let us know if it helps?

**Comment by WilliamNadeau** [comment]
> Are you sure it's plain console app, not something more complex like ASP.NET that actually uses FileSystemWatcher?

@adamsitnik My apologies, the app functions as a console app but it is built using the WorkerService .NET 6 template. It is using the HostBuilder to build and run the application.

The container is using musl 1.2.2 and still exhibits the issue.

**Comment by robertoramacciati** [comment]
Hi, I can confirm the  musl 1.2.2 also still exhibits the issue.

Sometime using HttpClient to call an https external service or  connecting sqlserver over a ssl channel.
The observed exception is 
`System.IO.IOException: The process cannot access the file '/etc/ssl/certs' because it is being used by another process.`

It's rarely thrown but of course it's annoying

**Comment by jplonghi** [comment]
Hello, also noticed the issue using C# MongoDB Driver, it throws a connection exception but inner details expose a problem trying to access /etc/ssl/certs. It happens sporadically and I can't reproduce it. It is also present in non-prod environments but even more rarely. 

It is a simple .net app using mcr.microsoft.com/dotnet/aspnet:6.0-alpine

At this point, I'm changing the dockerfile to use the Debian version *mcr.microsoft.com/dotnet/aspnet:6.0*  to see if the problem disappears after a few days. Some threads also point out Alpine of having DNS issues.

The table comparison in this post is good, https://crunchtools.com/comparison-linux-container-images/ 
Interesting Alpine is the only one using muslc

```
MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.
 ---> System.IO.IOException: The process cannot access the file '/etc/ssl/certs' because it is being used by another process.
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry(Byte* entryBufferPtr, Int32 bufferLength)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at Internal.Cryptography.Pal.CachedSystemStoreProvider.<LoadMachineStores>g__ProcessDir|25_0(DirectoryInfo dir, <>c__DisplayClass25_0& )
   at Internal.Cryptography.Pal.CachedSystemStoreProvider.LoadMachineStores(DirectoryInfo rootStorePath, FileInfo rootStoreFile)
   at Internal.Cryptography.Pal.CachedSystemStoreProvider.GetCollections()
   at Internal.Cryptography.Pal.CachedSystemStoreProvider.GetNativeCollections(SafeX509StackHandle& root, SafeX509StackHandle& intermediate)
   at Internal.Cryptography.Pal.OpenSslX509ChainProcessor.InitiateChain(SafeX509Handle leafHandle, X509Certificate2Collection customTrustStore, X509ChainTrustMode trustMode, DateTime verificationTime, TimeSpan remainingDownloadTime)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, X509Certificate2Collection customTrustStore, X509ChainTrustMode trustMode, DateTime verificationTime, TimeSpan timeout, Boolean disableAia)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Net.Security.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, Boolean isServer, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at MongoDB.Driver.Core.Connections.SslStreamFactory.CreateStreamAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.PooledConnection.OpenAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.ConnectionCreator.CreateOpenedInternalAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.ConnectionCreator.CreateOpenedOrReuseAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionHelper.EnteredPoolAsync(Boolean enteredPool, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannelAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.InitializeAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableWriteContext.CreateAsync(IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteAsync(IWriteBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperationAsync[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperationAsync[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.BulkWriteAsync(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionBase`1.InsertOneAsync(TDocument document, InsertOneOptions options, Func`3 bulkWriteAsync)
```

**Comment by taskinozdemir** [comment]
@adamsitnik The container is using musl 1.2.4 for our applications and still exhibits the issue.

**Comment by bodyabos** [comment]
+ We have the same issue with Alpine
