### ISSUE TITLE
crossgen/llc --help is malformed

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#76770]
`crossgen2.exe --help` prints an exception:
```
armel: Unhandled exception. System.CommandLine.CommandLineException: Target architecture 'armel' is not supported
   at System.CommandLine.Helpers.GetTargetArchitecture(String token) in C:\prj\runtime-main\src\coreclr\tools\Common\CommandLineHelpers.cs:line 109
   at ILCompiler.Crossgen2RootCommand.<>c.<GetExtendedHelp>b__182_0(HelpContext _) in C:\prj\runtime-main\src\coreclr\tools\aot\crossgen2\Crossgen2RootCommand.cs:line 337
   at System.CommandLine.Help.HelpBuilder.Write(HelpContext context)
   at System.CommandLine.Help.HelpResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.Invoke(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
   at ILCompiler.Program.Main(String[] args) in C:\prj\runtime-main\src\coreclr\tools\aot\crossgen2\Program.cs:line 874
```

`llc.exe --help` produces a long malformed list of ISAs, I think it should be either removed or hidden under `--instruction-set help`
```
The allowable values for the --instruction-set option are described in the table below. Each architecture has a different set of valid instruction sets, and multiple instruction sets may be specified by separating the instructions sets by a ','. For example 'avx2,bmi,lzcnt'
arm: arm64: base
, neon
, aes
, crc
, dotprod
, rdma
, sha1
, sha2
, lse



, rcpc
x86: base
, sse
, sse2
, sse3
, ssse3
, sse4.1
, sse4.2
, avx
, avx2
, aes
, bmi
, bmi2
, fma
, lzcnt
, pclmul
, popcnt


, avxvnni
, movbe
, serialize
, avx512f
, avx512f_vl
, avx512bw
, avx512bw_vl
, avx512cd
, avx512cd_vl
, avx512dq
, avx512dq_vl
x64: base
, sse
, sse2
, sse3
, ssse3
, sse4.1
, sse4.2
, avx
, avx2
, aes
, bmi
, bmi2
, fma
, lzcnt
, pclmul
, popcnt


, avxvnni
, movbe
, serialize
, avx512f
, avx512f_vl
, avx512bw
, avx512bw_vl
, avx512cd
, avx512cd_vl
, avx512dq
, avx512dq_vl
```

**Comment by EgorBo** [comment]
cc @am11 can it be related to your recent changes there?

**Comment by am11** [comment]
Yes, I'll take a look. Thanks for the report.
