### ISSUE TITLE
[mono] System.Net.Sockets.SocketException (98): Address in use

### ISSUE THREAD

**Issue by ayakael** [dotnet/runtime#76806]
### Description

.net 7.0.100-rc1 is unstable on mono-flavored runtime on `linux-musl`, as it tends to randomly fail due to `System.Net.Sockets.SocketException` errors. Due to the randomness of the fatal errors, it's been hard to debug.
```
UNHANDLED EXCEPTIONS FROM PROCESS 1347774:
=====================
10/09/2022 23:01:10
System.Net.Sockets.SocketException (98): Address in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount)
   at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.InternalConstruct(String pipeName)
   at Microsoft.Build.BackEnd.ServerNodeEndpointOutOfProc..ctor(String pipeName, Handshake handshake)
   at Microsoft.Build.Experimental.OutOfProcServerNode.RunInternal(Exception& shutdownException, ServerNodeHandshake handshake)
   at Microsoft.Build.Experimental.OutOfProcServerNode.Run(Exception& shutdownException)
   at Microsoft.Build.CommandLine.MSBuildApp.StartLocalNode(CommandLineSwitches commandLineSwitches, Boolean lowpriority)
   at Microsoft.Build.CommandLine.MSBuildApp.ProcessCommandLineSwitches(CommandLineSwitches switchesFromAutoResponseFile, CommandLineSwitches switchesNotFromAutoResponseFile, String& projectFile, String[]& targets, String& toolsVersion, Dictionary`2& globalProperties, ILogger[]& loggers, LoggerVerbosity& verbosity, List`1& distributedLoggerRecords, Int32& cpuCount, Boolean& enableNodeReuse, TextWriter& preprocessWriter, TextWriter& targetsWriter, Boolean& detailedSummary, ISet`1& warningsAsErrors, ISet`1& warningsNotAsErrors, ISet`1& warningsAsMessages, Boolean& enableRestore, Boolean& interactive, ProfilerLogger& profilerLogger, Boolean& enableProfiler, Dictionary`2& restoreProperties, Boolean& isolateProjects, GraphBuildOptions& graphBuild, String[]& inputResultsCaches, String& outputResultsCache, Boolean& lowPriority, Boolean recursing, String commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
===================
```
Sometimes fails with:
```
UNHANDLED EXCEPTIONS FROM PROCESS 1361566:
=====================
10/09/2022 23:11:19
System.AggregateException: One or more errors occurred. (Connection reset by peer)
 ---> System.IO.IOException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.Receive(Span`1 buffer, SocketFlags socketFlags)
   at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.BufferedReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__38_0(Object <p0>)
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Build.Internal.CommunicationsUtilities.ReadAsync(Stream stream, Byte[] buffer, Int32 bytesToRead)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Result()
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

### Reproduction Steps

Try to build something using mono on `linux-musl` environment, and let fate decide if it fails or not.

### Expected behavior

Build should occur

### Actual behavior

Build fails

### Regression?

Indeed, this is a regression: version 6.0.9 of runtime in the same enviornment does not fail

### Known Workarounds

Try to rebuild till build completes

### Configuration

> dotnet --info
```
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    cb14812a5c

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.17_alpha20220809
 OS Platform: Linux
 RID:         linux-musl-s390x
 Base Path:   /home/build/dotnet7/testing/dotnet7-stage0/src/bootstrap/sdk/7.0.100-rc.1.22431.12/

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: s390x
  Commit:       N/A

.NET SDKs installed:
  7.0.100-rc.1.22431.12 [/home/build/dotnet7/testing/dotnet7-stage0/src/bootstrap/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [/home/build/dotnet7/testing/dotnet7-stage0/src/bootstrap/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [/home/build/dotnet7/testing/dotnet7-stage0/src/bootstrap/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by ayakael** [comment]
This seems to be fixed in sdk version 7.0.100-rc2. Closing.
