### ISSUE TITLE
Directory.GetFiles throws DirectoryNotFoundException if path contains ''$'\240''a' on Linux

### ISSUE THREAD

**Issue by voltagex** [dotnet/runtime#76877]
### Description

If the path contains what I *think* is a blank character of some sort from classic Mac (I found it in an Apple archive), Directory.GetFiles will throw a DirectoryNotFoundException (I was also getting access denied on another machine but I can't reproduce that)

### Reproduction Steps

It's difficult to put this into a Dockerfile or Bash script due to character escaping but the following should illustrate the issue
```
mkdir -p /tmp/test/''$'\240'hiddencharacter
dotnet new console
echo 'foreach (var dir in Directory.GetDirectories("/tmp/test")) Directory.GetFiles(dir);' > Program.cs
dotnet run

```

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/test/�hiddencharacter'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at Program.<Main>$(String[] args) in /src/Program.cs:line 1
```

### Expected behavior

Files in directory are enumerated

### Actual behavior

Exception

### Regression?

Unknown, it fails with mono, too.

### Known Workarounds

Unknown, I found this when using FileSystemEnumerable, my workaround is to test with Directory.GetFiles and then proceed with FileSystemEnumerable if there's no exception.

### Configuration

Tested with:
NET 6.0 docker image
NET 7.0.100-rc.1.22431.12 on Debian bookworm

### Other information

Setting LANG did not help

**Comment by vcsjones** [comment]
> /tmp/test/�hiddencharacter

The `�` appears to be the REPLACEMENT CHARACTER.

This sounds like another manifestation of https://github.com/dotnet/runtime/issues/513. For better or for worse, .NET expects paths on Linux to be valid UTF-8 (even though there is technically no such restriction in Linux).

When you try round-tripping `\240` through the UTF-8 encoding, it doesn't get preserved:

```csharp
var str = System.Text.Encoding.UTF8.GetString(new byte[] { 240 });
Console.WriteLine(str); //Outputs �
Console.WriteLine((int)str[0]); //Outputs 65533
```

So what .NET ends up doing is looking for a directory named `�hiddencharacter`, not `\240hiddencharacter`, and that's where the not exists comes from.

As identified in the linked issue, there is no trivial work around for this that I am aware of.

**Comment by jeffhandley** [comment]
Thanks, @vcsjones. I'm closing this as a duplicate of #513 and I'll edit that issue's description to cite the new repro steps reported here. Thanks for the time creating the repro and filing this issue, @voltagex.
