### ISSUE TITLE
Runtime_76346 fails in jitstress on arm64

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#76910]
The test added for #76346 seems to fail under jitstress=2. Works fine without jitstress.

```scala
D:\h\w\AD9809AF\w\B39E099D\e>type D:\h\w\AD9809AF\w\B39E099D\u\SetStressModes_jitstress2.cmd 
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=2

...

D:\h\w\AD9809AF\w\B39E099D\e>dotnet D:\h\w\AD9809AF\p\xunit\xunit.console.dll JIT\Regression\JIT.Regression.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.Regression 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-rc.1.22426.10)
  Discovering: JIT.Regression.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Regression.XUnitWrapper (found 685 of 1673 test cases)
  Starting:    JIT.Regression.XUnitWrapper (parallel test collections = on, max threads = 8)
    JIT\Regression\JitBlue\Runtime_76346\Runtime_76346\Runtime_76346.cmd [FAIL]
      
      Return code:      1
      Raw output file:      D:\h\w\AD9809AF\w\B39E099D\uploads\Reports\JIT.Regression\JitBlue\Runtime_76346\Runtime_76346\Runtime_76346.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\AD9809AF\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Runtime_76346.dll 
      Running... 0
      In finally1
      try2... 0
      finally2... 0
      Expected: 100
      Actual: -2147483645
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\AD9809AF\p
      > D:\h\w\AD9809AF\w\B39E099D\e\JIT\Regression\JitBlue\Runtime_76346\Runtime_76346\Runtime_76346.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Regression._JitBlue_Runtime_76346_Runtime_76346_Runtime_76346_._JitBlue_Runtime_76346_Runtime_76346_Runtime_76346_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=48223&view=ms.vss-test-web.build-test-results-tab&runId=976374&resultId=109511&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

cc @BruceForstall

**Comment by BruceForstall** [comment]
Repros with just

```
set COMPlus_JitStressModeNames=STRESS_EMITTER
```

**Comment by BruceForstall** [comment]
This is a bug in the `STRESS_EMITTER` implementation of alignment instructions on arm64. In particular, if alignment is inserted after a `BBJ_ALWAYS` block, we insert breakpoint instead of NOP instructions. In this case, we have a `BBJ_CALLFINALLY/BBJ_ALWAYS` pair, and the code thinks the BBJ_ALWAYS is a "normal" branch, which it is not.

Additionally, the code adds alignment in the `BBJ_CALLFINALLY/BBJ_ALWAYS` block, which means the alignment gets included in the "cloned finally" region reported to the VM. This is probably undesirable.
