### ISSUE TITLE
Exception thrown when making a Nullable<> generic type from a System.Enum constrained generic type parameter

### ISSUE THREAD

**Issue by p66ush** [dotnet/runtime#77000]
### Description

System.ArgumentException is thrown when trying to make Nullable<> generic type from a System.Enum constrained generic type parameter.

The exception has the following message:

_'T', on 'System.Nullable`1[T]' violates the constraint of type parameter 'T'._

### Reproduction Steps

This example code can be used to reproduce the problem.

```csharp
namespace Example;

public class Example<T> where T : Enum
{
}

internal class Program
{
    static void Main()
    {
        Type type = typeof(Nullable<>).MakeGenericType(typeof(Example<>).GetGenericArguments()[0]);
    }
}
```

### Expected behavior

Since the IsValueType property of the generic type parameter is True, I would expect that this operation would be allowed.

### Actual behavior

System.ArgumentException
  HResult=0x80070057
  Message=GenericArguments[0], 'T', on 'System.Nullable`1[T]' violates the constraint of type 'T'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Example.Program.Main() in C:\Example\Program.cs:line 11

  This exception was originally thrown at this call stack:
    System.RuntimeTypeHandle.Instantiate(System.RuntimeType)
    System.RuntimeType.MakeGenericType(System.Type[])

Inner Exception 1:
TypeLoadException: GenericArguments[0], 'T', on 'System.Nullable`1[T]' violates the constraint of type parameter 'T'.

### Configuration

- .NET 6 SDK 6.0.401
- Windows 10 Enterprise (10.0.19044.2006)
- x64
- Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.3.4

### Other information

Just for info - I recently raised another issue related to a System.Enum constrainted generic type parameter (#76300).

Apologies, if again, I've raised a duplicate issue here.

**Comment by Joe4evr** [comment]
> ```cs
> Type type = typeof(Nullable<>).MakeGenericType(typeof(Example<>).GetGenericArguments()[0]);
> ```

This code is creating `typeof(Nullable<Example<>>)` and your `Example<T>` is a class therefor cannot be used as a type argument for `Nullable<T>`. The actual behavior is correct.

**Comment by p66ush** [comment]
Wow - how is that for interaction! I was just typing a response to the first point, and it changed before my eyes :)

Here is some code that breaks it down a bit better:

```csharp
using System.Diagnostics;

namespace Example;

public class Example<T> where T : Enum
{
}

internal class Program
{
    static void Main()
    {
        Type genericTypeParameter = typeof(Example<>).GetGenericArguments()[0];
        Debug.Assert(genericTypeParameter.IsValueType);
        Type type = typeof(Nullable<>).MakeGenericType(genericTypeParameter);
    }
}
```

Note that the assert does not fail, so the generic type parameter does indeed have an IsValueType of True.

That is a very fair point about the System.Enum constraint being used itself as the type parameter. I must confess I did notice that the struct and System.Enum constraints could be combined, but didn't think the relevance through enough. 

The fact that IsValueType is True threw me. It does seem a bit confusing when System.Enum is a reference type.

**Comment by Joe4evr** [comment]
> Note that the assert does not fail, so the generic type parameter does indeed have an IsValueType of True.

That is strange and might be an actual bug. Do note that `MakeGenericType()` [does work when `struct` is added to the constraint](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRLKsBLCAbAE2QBoYQE4A7AHwAEAmARgFgAoNgNygQAIYeAvHwCeABwgB7MAAoAwgB4AfAEoA3J248A5oL4A6AOIQYRyhATYAxgEEEWuAFsIlGMmnKA2gAYAuuta0jACc0lp6AJLIAGpQeHAQACpiEGpsbPxCMMlScvIAopSOKv46mYbGpuZWtvZOLm6evv6BIWGRMXGJyansrBki4jmy9Eo9pfpGJs5VNnaOzq7u3n5sLaER0bHxSeI9GrwuulmDMgBycHh4UMB4EKN6ALJQANYQlRaWOxChPWsueqcoE49gEAMw8Bg8BQJRQ8ADuAAtzBAeAkeCAeAVHDwAN48AC+aV6tHBkOG8hh8KRSFR6J4yBgFEsMGImMKDlxBKAA==) (which is basically what you want 99.9999999...% of the time).

**Comment by stephentoub** [comment]
> That is strange and might be an actual bug

This prints "False" and "True" (on both .NET Framework 4.8 and .NET 7), which certainly seems inconsistent. @dotnet/area-system-reflection?

```C#
using System;

internal class Program
{
    static void Main() => TakesEnum<Enum>();

    public static void TakesEnum<T>() where T : Enum
    {
        Console.WriteLine(typeof(T).IsValueType);
        Console.WriteLine(typeof(Program).GetMethod("TakesEnum").GetGenericArguments()[0].IsValueType);
    }
}
```

**Comment by p66ush** [comment]
> That is strange and might be an actual bug. Do note that `MakeGenericType()` [does work when `struct` is added to the constraint](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRLKsBLCAbAE2QBoYQE4A7AHwAEAmARgFgAoNgNygQAIYeAvHwCeABwgB7MAAoAwgB4AfAEoA3J248A5oL4A6AOIQYRyhATYAxgEEEWuAFsIlGMmnKA2gAYAuuta0jACc0lp6AJLIAGpQeHAQACpiEGpsbPxCMMlScvIAopSOKv46mYbGpuZWtvZOLm6evv6BIWGRMXGJyansrBki4jmy9Eo9pfpGJs5VNnaOzq7u3n5sLaER0bHxSeI9GrwuulmDMgBycHh4UMB4EKN6ALJQANYQlRaWOxChPWsueqcoE49gEAMw8Bg8BQJRQ8ADuAAtzBAeAkeCAeAVHDwAN48AC+aV6tHBkOG8hh8KRSFR6J4yBgFEsMGImMKDlxBKAA==) (which is basically what you want 99.9999999...% of the time).

Absolutely - thanks.

I only came across this problem while running a bulk of unit tests trying various permutations, but thought it was worthy of mention in case it was a bug.
