### ISSUE TITLE
IWA authentication on Android fails with TypeInitializationException in NetSecurityNative

### ISSUE THREAD

**Issue by mstefarov** [dotnet/runtime#77015]
### Description

I am trying to connect to an IWA-secured web service, using an HttpClient backed by SocketsHttpHandler that's pre-configured with username/password on a NetworkCredential. My app targets net6.0-android31. My network requests fail with an exception:

```
System.ComponentModel.Win32Exception: The type initializer for 'NetSecurityNative' threw an exception.
at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
at System.Net.NTAuthentication..ctor(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at Esri.ArcGISRuntime.Http.Caching.CacheManager.SendUsingCachingAsync(Func`3 sendAsyncDelegate, HttpRequestMessage request, CancellationToken cancellationToken)
at Esri.ArcGISRuntime.Http.HttpDispatcher.SendAsync(HttpRequestMessage request, HandlerOptions options, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Esri.ArcGISRuntime.Portal.Utils.WebRequestJson`1.d__1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
...
```

A similar exception is thrown if I do not specify a NetworkCredential up-front:
```
System.TypeInitializationException: The type initializer for 'NetSecurityNative' threw an exception. ---> System.TypeInitializationException: The type initializer for 'GssInitializer' threw an exception. ---> System.DllNotFoundException: libSystem.Net.Security.Native
at Interop.NetSecurityNative.GssInitializer..cctor()
--- End of inner exception stack trace ---
at Interop.NetSecurityNative..cctor()
--- End of inner exception stack trace ---
at Microsoft.Win32.SafeHandles.SafeGssNameHandle.CreateTarget(String name)
at System.Net.Security.SafeDeleteNegoContext..ctor(SafeFreeNegoCredentials credential, String targetName)
at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, ChannelBinding channelBinding, String targetName, ContextFlagsPal inFlags, Byte[] incomingBlob, Byte[]& resultBuffer, ContextFlagsPal& outFlags)
at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, Byte[] incomingBlob, ChannelBinding channelBinding, Byte[]& resultBlob, ContextFlagsPal& contextFlags)
at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at Esri.ArcGISRuntime.Http.Caching.CacheManager.SendUsingCachingAsync(Func`3 sendAsyncDelegate, HttpRequestMessage request, CancellationToken cancellationToken)
at Esri.ArcGISRuntime.Http.HttpDispatcher.SendAsync(HttpRequestMessage request, HandlerOptions options, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Esri.ArcGISRuntime.Portal.Utils.WebRequestJson`1.d__1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
...
```

### Reproduction Steps

- Find a service secured by IWA (i.e. WWW-Authenticate: Negotiate and/or NTLM)
- In an Android app, create an HttpClient powered by SocketsHttpHandler
- Make a GET request to the service

### Expected behavior

Either I can connect to IWA-secured services (ideally) or my requests fail with a more helpful error message (e.g. I get a HTTP/401 HttpResponseMessage).  I'm guessing NTLM will start working in net7.0 with https://github.com/dotnet/runtime/issues/62264 but it would be helpful to at least start getting a 401 response back.

### Actual behavior

Network stack throws TypeInitializationExceptions

### Regression?

AndroidClientHandler used to give me an HTTP/401 response for this service, which is still better than current behavior.

### Configuration

- dotnet 6.0.9 and also 6.0.10
- Targeting net6.0-android31 on armv8
- Various Android devices, e.g. OnePlus 3T (Android 9) and Google Pixel 5 (Android 12)

### Other information

Could this be related to https://github.com/dotnet/runtime/pull/55037? @VSadov

**Comment by steveisok** [comment]
@simonrozsival should this be a 401 or a PNSE?

**Comment by simonrozsival** [comment]
@steveisok I think the better option would be to ignore the `WWW-Authenticate: NTLM` response header should be ignored and we should return the HTTP response as is instead of trying to authenticate the connection which cannot succeed on `net6.0-android`.

**Comment by wfurt** [comment]
This _should_ work with 7.0, right @simonrozsival ? e.g. the fix is probably upgrade @mstefarov. 
I agree that ignoring unsupported mechanisms is probably best - this is what we would do on other platforms.

**Comment by akoeplinger** [comment]
@mstefarov would you mind trying with net7 and see if this works there? thanks
