### ISSUE TITLE
osr stress arm64 - coreclr_initialize failed

### ISSUE THREAD

**Issue by markples** [dotnet/runtime#77066]
Numerous failures

https://dev.azure.com/dnceng-public/public/_build/results?buildId=50997&view=logs&j=63f2a02a-7891-5505-e9da-45b13105e16b
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2cca9f46ad19498ea2/PayloadGroup0/1/console.33597c72.log?helixlogtype=result

```
D:\h\w\B4F7098C\w\A4F208EA\e>type D:\h\w\B4F7098C\w\A4F208EA\u\SetStressModes_jitosr_stress.cmd 
set COMPlus_TieredCompilation=1
set COMPlus_TC_OnStackReplacement=1
set COMPlus_TC_QuickJitForLoops=1
set COMPlus_TC_OnStackReplacement_InitialCounter=1
set COMPlus_OSR_HitLimit=1
...
    Regressions\coreclr\15650\interfacecctor\interfacecctor.cmd [FAIL]
...
    Regressions\coreclr\15650\interfacecctor\interfacecctor.cmd [FAIL]
      BEGIN: coreclr_initialize failed - Error: 0x80004005
      END: coreclr_initialize failed - Error: 0x80004005
      
      Return code:      1
      Raw output file:      D:\h\w\B4F7098C\w\A4F208EA\uploads\Reports\Regressions.coreclr\15650\interfacecctor\interfacecctor.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\B4F7098C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  interfacecctor.dll 
      Exe path: D:\h\w\B4F7098C\p\corerun.exe
      Properties:
          TRUSTED_PLATFORM_ASSEMBLIES = <snip>
          APP_PATHS = D:\h\w\B4F7098C\w\A4F208EA\e\Regressions\coreclr\15650\interfacecctor\
          NATIVE_DLL_SEARCH_DIRECTORIES = D:\h\w\B4F7098C\w\A4F208EA\e\Regressions\coreclr\15650\interfacecctor\;D:\h\w\B4F7098C\p\;
          System.Reflection.Metadata.MetadataUpdater.IsSupported = false
      Managed assembly: D:\h\w\B4F7098C\w\A4F208EA\e\Regressions\coreclr\15650\interfacecctor\interfacecctor.dll
      Arguments (0): 
      Expected: 100
      Actual: -1
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\B4F7098C\p
      > D:\h\w\B4F7098C\w\A4F208EA\e\Regressions\coreclr\15650\interfacecctor\interfacecctor.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at Regressions_coreclr._15650_interfacecctor_interfacecctor_._15650_interfacecctor_interfacecctor_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        BEGIN: coreclr_initialize failed - Error: 0x80004005
        END: coreclr_initialize failed - Error: 0x80004005
```

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-3e5e06bd1dfe4a9fb6/PayloadGroup0/1/console.b759b716.log?helixlogtype=result

has several of these.  Some have a different error:
```
    Regressions\coreclr\GitHub_24524\test24524\test24524.cmd [FAIL]
      BEGIN: coreclr_initialize failed - Error: 0x8007000e
      END: coreclr_initialize failed - Error: 0x8007000e
```

After those, the symptoms vary a lot.  I wonder if the run is corrupted at that point.

```
    Regressions\coreclr\22728\createdelegate\createdelegate.cmd [FAIL]
      Test Infrastructure Failure: System.ComponentModel.Win32Exception (1455): An error occurred trying to start process 'D:\h\w\B770094A\w\A38A0894\e\Regressions\coreclr\22728\createdelegate\createdelegate.cmd' with working directory 'D:\h\w\B770094A\w\A38A0894\e'. The paging file is too small for this operation to complete.
         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
         at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir)
         at Regressions_coreclr._22728_createdelegate_createdelegate_._22728_createdelegate_createdelegate_cmd()
```

```
    Regressions\coreclr\GitHub_45082\test45082\test45082.cmd [FAIL]
      Not enough memory resources are available to process this command.
      The syntax of the command is incorrect.
```

```
    Regressions\coreclr\1514\InterlockExchange\InterlockExchange.cmd [FAIL]
      The system cannot execute the specified program.
      Not enough memory resources are available to process this command.
      The syntax of the command is incorrect.
```

```
    Regressions\coreclr\22728\debug15\debug15.cmd [FAIL]
      
      Assert failure(PID 7740 [0x00001e3c], Thread: 3372 [0x0d2c]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! <no symbol> + 0x0 (0x00007ffe`740a28c0)
      CORECLR! <no symbol> + 0x0 (0x00007ffe`740a2890)
      -----
      .AV on tid=0xd2c (3372), cxr=0000008BE5175F50, exr=0000008BE51762E0
      FAILED: false
          File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7117
          Image: D:\h\w\B770094A\p\corerun.exe
```

**Comment by markples** [comment]
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Seems to have been some one-off CI issue? Things returned to "normal" after that (though there was another spate of odd failures a few days ago). Am going to close this.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/10121823/198669190-01c61b27-94ac-4bd6-9553-71712c714257.png">
