### ISSUE TITLE
Test failure JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#77145]
Run: [runtime-coreclr r2r-extra 20221016.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54329&view=ms.vss-test-web.build-test-results-tab&runId=1112046&resultId=100761&paneView=debug)

Failed test:
```
R2R-CG2 OSX arm64 Checked forcerelocs @ OSX.1200.ARM64.Open

- JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh
```
**Error message:**
```
/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh: line 292: -r:/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/IL-CG2/*.dll: No such file or directory

Assert failure(PID 47032 [0x0000b7b8], Thread: 8793531 [0x862dbb]): g_pConfig->ShouldInjectFault(INJECTFAULT_DYNAMICCODEHEAP)
File: /Users/runner/work/1/s/src/coreclr/vm/dynamicmethod.cpp Line: 446
Image: /private/tmp/helix/working/8DFA0801/p/corerun

[createdump] Invalid process id: task_for_pid(47032) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh: line 416: 47032 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/8DFA0801/w/A3790895/uploads/Reports/JIT.Stress/ABI/pinvokes_d/pinvokes_d.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/IL-CG2/pinvokes_d.dll
23:39:02
Response file: /private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.dll.rsp
/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/IL-CG2/pinvokes_d.dll
-o:/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.dll
-r:/tmp/helix/working/8DFA0801/p/System..dll
-r:/tmp/helix/working/8DFA0801/p/Microsoft..dll
-r:/tmp/helix/working/8DFA0801/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /tmp/helix/working/8DFA0801/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.dll
23:39:03
in ReleaseLock
in takeLock
/tmp/helix/working/8DFA0801/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false pinvokes_d.dll '--pinvokes' '--num-calls' '1000' '--no-ctrlc-summary'
Stressing pinvokes
OSVersion: Unix 12.4.0
OSArchitecture: Arm64
ProcessArchitecture: Arm64
Selecting arm64 ABI.
50 callers done
100 callers done
150 callers done
200 callers done
250 callers done
300 callers done
350 callers done
400 callers done
[createdump] Target process is alive
in ReleaseLock
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/8DFA0801/p
/private/tmp/helix/working/8DFA0801/w/A3790895/e/JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Stress._ABI_pinvokes_d_pinvokes_d_._ABI_pinvokes_d_pinvokes_d_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-17T06:35:08.445Z | osx.1200.arm64.open | arm64 | [runtime-coreclr r2r-extra   Checked-forcerelocs](https://dev.azure.com/dnceng/public/_build/results?buildId=54329&view=ms.vss-test-web.build-test-results-tab&runId=1112046&resultId=100761&paneView=debug)

**Comment by v-wenyuxu** [comment]
Run: [runtime-coreclr r2r-extra 20230114.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=138050&view=ms.vss-test-web.build-test-results-tab&runId=3002028&resultId=100027&paneView=debug)

Failed test:
```
R2R-CG2 osx arm64 Checked forcerelocs @ OSX.1200.ARM64.Open

- JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh
```
**Error message:**
```
/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh: line 307: -r:/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/IL-CG2/*.dll: No such file or directory

Assert failure(PID 88642 [0x00015a42], Thread: 7565288 [0x736fe8]): g_pConfig->ShouldInjectFault(INJECTFAULT_DYNAMICCODEHEAP)
File: /Users/runner/work/1/s/src/coreclr/vm/dynamicmethod.cpp Line: 446
Image: /private/tmp/helix/working/BB340A39/p/corerun

[createdump] Invalid process id: task_for_pid(88642) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh: line 437: 88642 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/BB340A39/w/A24608EE/uploads/Reports/JIT.Stress/ABI/pinvokes_do/pinvokes_do.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/IL-CG2/pinvokes_do.dll
20:34:47
Response file: /private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.dll.rsp
/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/IL-CG2/pinvokes_do.dll
-o:/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.dll
-r:/tmp/helix/working/BB340A39/p/System..dll
-r:/tmp/helix/working/BB340A39/p/Microsoft..dll
-r:/tmp/helix/working/BB340A39/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
-O
Running CrossGen2:  dotnet /tmp/helix/working/BB340A39/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.dll
Running R2RDump:  dotnet /tmp/helix/working/BB340A39/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.dll --out /private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.dll.r2rdump --val
20:34:48
in ReleaseLock
in takeLock
/tmp/helix/working/BB340A39/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false pinvokes_do.dll '--pinvokes' '--num-calls' '1000' '--no-ctrlc-summary'
Stressing pinvokes
OSVersion: Unix 12.4.0
OSArchitecture: Arm64
ProcessArchitecture: Arm64
Selecting arm64 ABI.
50 callers done
100 callers done
150 callers done
200 callers done
250 callers done
300 callers done
350 callers done
400 callers done
450 callers done
500 callers done
550 callers done
600 callers done
650 callers done
[createdump] Target process is alive
in ReleaseLock
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/BB340A39/p
/private/tmp/helix/working/BB340A39/w/A24608EE/e/JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Stress._ABI_pinvokes_do_pinvokes_do_._ABI_pinvokes_do_pinvokes_do_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Closing since this no longer repros.
