### ISSUE TITLE
[jitstress] ParserTests failing on correct (displayed) values

### ISSUE THREAD

**Issue by markples** [dotnet/runtime#77154]
runtime-coreclr libraries-jitstress-random
Libraries Test Run checked coreclr windows x86 Release

https://dev.azure.com/dnceng-public/public/_build/results?buildId=53798&view=logs&j=33a55bae-e260-534b-8b9d-b9890ba134c2&t=49ce589b-b628-52a0-14f5-f855761894bb
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fab8d4489c5c42b19a/System.Memory.Tests/1/console.652d1f9b.log?helixlogtype=result

```
    System.Buffers.Text.Tests.ParserTests.TestParserDouble(testData: [ParseDouble '-0',G to -0)]) [FAIL]
      TestException : This parse attempt [ParseDouble '-0',G to -0)] succeeded as expected but parsed to the wrong value:
  Expected: -0
  Actual:   -0

      Stack Trace:
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ValidateParser.cs(41,0): at System.Buffers.Text.Tests.ParserTests.ValidateParserHelper[T](ParserTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ValidateParser.cs(12,0): at System.Buffers.Text.Tests.ParserTests.ValidateParser[T](ParserTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ParserTests.cs(84,0): at System.Buffers.Text.Tests.ParserTests.TestParserDouble(ParserTestData`1 testData)
           at InvokeStub_ParserTests.TestParserDouble(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    System.Buffers.Text.Tests.ParserTests.TestParserDouble(testData: [ParseDouble '-0.0',G to -0)]) [FAIL]
      TestException : This parse attempt [ParseDouble '-0.0',G to -0)] succeeded as expected but parsed to the wrong value:
  Expected: -0
  Actual:   -0

      Stack Trace:
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ValidateParser.cs(41,0): at System.Buffers.Text.Tests.ParserTests.ValidateParserHelper[T](ParserTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ValidateParser.cs(12,0): at System.Buffers.Text.Tests.ParserTests.ValidateParser[T](ParserTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ParserTests.cs(84,0): at System.Buffers.Text.Tests.ParserTests.TestParserDouble(ParserTestData`1 testData)
           at InvokeStub_ParserTests.TestParserDouble(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    System.Buffers.Text.Tests.ParserTests.TestParserDouble(testData: [ParseDouble '123.45',G to 123.45)]) [FAIL]
      TestException : This parse attempt [ParseDouble '123.45',G to 123.45)] succeeded as expected but parsed to the wrong value:
  Expected: 123.45
  Actual:   123.45

      Stack Trace:
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ValidateParser.cs(41,0): at System.Buffers.Text.Tests.ParserTests.ValidateParserHelper[T](ParserTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ValidateParser.cs(12,0): at System.Buffers.Text.Tests.ParserTests.ValidateParser[T](ParserTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Parser/ParserTests.cs(84,0): at System.Buffers.Text.Tests.ParserTests.TestParserDouble(ParserTestData`1 testData)
           at InvokeStub_ParserTests.TestParserDouble(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
...
```
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
I can't repro this, so closing.
