### ISSUE TITLE
Test failure GC/API/GC/GetAllocatedBytesForCurrentThread/GetAllocatedBytesForCurrentThread.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#77240]
Run: [runtime-coreclr jitstress 20221018.4](https://dev.azure.com/dnceng-public/public/_build/results?buildId=56760&view=ms.vss-test-web.build-test-results-tab&runId=1163304&resultId=110634&paneView=debug)

Failed test:
```
coreclr Linux arm64 Checked jitminopts @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f

- GC/API/GC/GetAllocatedBytesForCurrentThread/GetAllocatedBytesForCurrentThread.sh
```
**Error message:**
```
cmdLine:/root/helix/work/workitem/e/GC/API/GC/GetAllocatedBytesForCurrentThread/GetAllocatedBytesForCurrentThread.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 10/19/2022 6:57:03 AM, end: 10/19/2022 7:27:03 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.API/GC/GetAllocatedBytesForCurrentThread/GetAllocatedBytesForCurrentThread.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false GetAllocatedBytesForCurrentThread.dll ''
allocating 100591792 bytes
iter 0 allocated 100592320 bytes
allocating 69871537 bytes
iter 1 allocated 69871660 bytes
allocating 117132247 bytes
iter 2 allocated 117132478 bytes
allocating 114120841 bytes
iter 3 allocated 114121175 bytes
allocating 44458941 bytes
iter 4 allocated 44459050 bytes
allocating 88643056 bytes
iter 5 allocated 88643559 bytes
allocating 99280887 bytes
iter 6 allocated 99281200 bytes
allocating 119782422 bytes
iter 7 allocated 119782947 bytes
allocating 95140843 bytes
iter 8 allocated 95141195 bytes
allocating 44154525 bytes
iter 9 allocated 44154760 bytes
allocating 65902318 bytes
iter 10 allocated 65902401 bytes
allocating 117408172 bytes
iter 11 allocated 117408205 bytes
allocating 101956820 bytes
iter 12 allocated 101956830 bytes
allocating 56336951 bytes
iter 13 allocated 56337356 bytes
allocating 84051497 bytes
iter 14 allocated 84051641 bytes
allocating 90384401 bytes
iter 15 allocated 90384539 bytes
allocating 66760129 bytes
iter 16 allocated 66760236 bytes
allocating 117911847 bytes
iter 17 allocated 117911890 bytes
allocating 91238249 bytes
iter 18 allocated 91238287 bytes
allocating 51506041 bytes
iter 19 allocated 51506277 bytes
allocating 68612323 bytes
iter 20 allocated 68612403 bytes
allocating 115696941 bytes
iter 21 allocated 115697309 bytes
allocating 64336231 bytes
iter 22 allocated 64336484 bytes
allocating 112540591 bytes
iter 23 allocated 112541352 bytes
allocating 93884709 bytes
iter 24 allocated 93885126 bytes
allocating 86000848 bytes
iter 25 allocated 86001239 bytes
allocating 124196208 bytes
iter 26 allocated 124196273 bytes
allocating 68546900 bytes
iter 27 allocated 68547327 bytes
allocating 64710294 bytes
iter 28 allocated 64710505 bytes
allocating 47838836 bytes
iter 29 allocated 47839017 bytes
allocating 123098620 bytes
iter 30 allocated 123098939 bytes
allocating 70434190 bytes
iter 31 allocated 70434878 bytes
allocating 85127666 bytes
iter 32 allocated 85127837 bytes
allocating 97721410 bytes
iter 33 allocated 97721724 bytes
allocating 49692608 bytes
iter 34 allocated 49692918 bytes
allocating 60525018 bytes
iter 35 allocated 60525464 bytes
allocating 55838310 bytes
iter 36 allocated 55839134 bytes
allocating 96516946 bytes
iter 37 allocated 96517209 bytes
allocating 70579922 bytes
iter 38 allocated 70580264 bytes
allocating 77091091 bytes
iter 39 allocated 77091104 bytes
allocating 82079580 bytes
iter 40 allocated 82080050 bytes
allocating 75410024 bytes
iter 41 allocated 75410332 bytes
allocating 99661792 bytes
iter 42 allocated 99661986 bytes
allocating 85726152 bytes
iter 43 allocated 85727055 bytes
allocating 78166979 bytes

cmdLine:/root/helix/work/workitem/e/GC/API/GC/GetAllocatedBytesForCurrentThread/GetAllocatedBytesForCurrentThread.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 10/19/2022 6:57:03 AM, end: 10/19/2022 7:27:03 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/API/GC/GetAllocatedBytesForCurrentThread/GetAllocatedBytesForCurrentThread.sh
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetAllocatedBytesForCurrentThread_GetAllocatedBytesForCurrentThread_._GC_GetAllocatedBytesForCurrentThread_GetAllocatedBytesForCurrentThread_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-19T05:54:12.866Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitminopts](https://dev.azure.com/dnceng/public/_build/results?buildId=56760&view=ms.vss-test-web.build-test-results-tab&runId=1163304&resultId=110634&paneView=debug)
2022-10-01T08:55:23.7Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=37391&view=ms.vss-test-web.build-test-results-tab&runId=745170&resultId=102022&paneView=debug)
2022-09-25T19:00:06.12Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=29433&view=ms.vss-test-web.build-test-results-tab&runId=591624&resultId=100214&paneView=debug)
2022-09-23T06:56:27.552Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545718&resultId=107612&paneView=debug)
2022-09-22T06:52:24.578Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520634&resultId=107811&paneView=debug)
2022-09-22T06:37:18.032Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520452&resultId=107612&paneView=debug)
2022-09-21T06:32:36.124Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493604&resultId=107610&paneView=debug)
2022-09-21T06:12:11.216Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493434&resultId=107706&paneView=debug)
2022-09-20T08:53:57.595Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=23216&view=ms.vss-test-web.build-test-results-tab&runId=470736&resultId=101969&paneView=debug)
2022-09-20T06:25:34.076Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468470&resultId=107811&paneView=debug)
2022-09-05T22:02:12.451Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=5191&view=ms.vss-test-web.build-test-results-tab&runId=90202&resultId=100866&paneView=debug)
2022-09-05T10:07:05.729Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=4698&view=ms.vss-test-web.build-test-results-tab&runId=81638&resultId=100129&paneView=debug)

**Comment by mangod9** [comment]
This hasnt reproed in a while.
