### ISSUE TITLE
0.5% customers will fail to Start my App when run as Windows Service

### ISSUE THREAD

**Issue by mingtong** [dotnet/runtime#77327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

OS: 10.0.19044.0, 10.0.19043.0, 10.0.22000.0
.net: 6.0.4 (self container)
For short, my App have around 3m live users per day, now about 15k users per day report error log with the folloing.

System.InvalidOperationException: Stopped without starting
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

My starting code is like
```
            IHost host = CreateHostBuilder(argsWithoutConsole, hostIP, hostPort).Build();
            await host.StartAsync().ConfigureAwait(false);
```

```
        private static IHostBuilder CreateHostBuilder(string[] args, string hostIP, int hostPort)
        {
            var ipAddress = hostIP;
            int availablePort = hostPort;

            var builder = Host.CreateDefaultBuilder(args);

            if (!ServiceUtil.IsRunningAsAdministrator())
            {
                logger.Debug("Is Running As service");
                builder.UseWindowsService();
            }
            builder.ConfigureHostOptions(config =>
                       {
                           //config.ShutdownTimeout = TimeSpan.FromSeconds(5);
                       })
                       .UseServiceProviderFactory<ContainerBuilder>(new AutofacServiceProviderFactory())
                       .ConfigureWebHost(webBuilder =>
                       {
                           webBuilder
                               .UseStartup<ServiceConfig>()
                               .UseKestrel((hostingContext, options) =>
                               {
                                   options.Listen(IPAddress.Parse(ipAddress), availablePort);
                               });
                       });

            return builder;
        }
```

what will be the probable reason for this?
Since the exception is just kind of easy, so I cant find useful information of the "Stopped without starting".

### Steps To Reproduce

It happened to customers only, so there is no clear steps to reproduce, that is also why I am posting here.

### Exceptions (if any)

System.InvalidOperationException: Stopped without starting
at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

### .NET Version

6.0.4

**Comment by teo-tsirpanis** [comment]
(FYI issues get only one area)

**Comment by hez2010** [comment]
Is it possible that the service is blocked by an Antivirus software?

**Comment by mingtong** [comment]
> Is it possible that the service is blocked by an Antivirus software?

Only Microsoft can answer this.

**Comment by Clockwork-Muse** [comment]
> > Is it possible that the service is blocked by an Antivirus software?
> 
> Only Microsoft can answer this.

... there are multiple other AV vendors.  You'd have to engage with your failing customers to find out their AV vendor, and have them check their logs to see if the application is being blocked.
Although I would expect it wouldn't even be allowed to try to start/be quarantined in such a case, so wouldn't be getting this far.

It's maybe more likely that the Windows firewall is blocking it - I would imagine Kestrel crashes if it can't get the port.  If that's the case, the firewall should have logs for it.  You should be able to get a log message in such a case, though...

**Comment by mingtong** [comment]
> 

I guess it's not about the port, cause I use 0, means random port.
The promblem is we have no effective way to contact end users, you know there is a long process though Developer-->USER.

**Comment by Clockwork-Muse** [comment]
> I guess it's not about the port, cause I use 0, means random port.

Random or specific port isn't relevant - if the firewall/AV decides you shouldn't get a port, your process is just not going to get _any_ port.

**Comment by mingtong** [comment]
> > I guess it's not about the port, cause I use 0, means random port.
> 
> Random or specific port isn't relevant - if the firewall/AV decides you shouldn't get a port, your process is just not going to get _any_ port.

So you mean firewall is blocking my App, then in what case my requested port will be blocked? 
1, App has signtuare.
2, Both service and client are on same PC, means IP = 127.0.0.1

**Comment by Clockwork-Muse** [comment]
> So you mean firewall is blocking my App, then in what case my requested port will be blocked?

**IF** the firewall/AV is blocking your app, it just blocks it regardless.  But I don't know if this is true, since it depends on customer config even you don't have.
> 1, App has signtuare.

There are several different things that can be signatures, but AVs especially sometimes work by checking for behavior, so just might stop your app because it thinks it's suspicious.

> 2, Both service and client are on same PC, means IP = 127.0.0.1

Firewalls can and do block connections to local addresses, and AVs are especially prone to do so.  This is more likely in some corporate scenarios, where firewalls are usually configured by policy.
Keep in mind that it's pretty common for there to be a firewall-related popup in Windows.

**Comment by hez2010** [comment]
I think you can log more information in the service so that you can get the failure details.

**Comment by carlossanlop** [comment]
We would need a minimal repro or a crash dump to help diagnose this issue. Can you please provide one of those, @mingtong?

**Comment by mingtong** [comment]
> We would need a minimal repro or a crash dump to help diagnose this issue. Can you please provide one of those, @mingtong?

If I can repro then I won't be here, like i said, 0.5% of my customers, not a high percentage, but in absolute data, it's 15000, not few.

and i have no way to collect a crash dump unless i can reach the end user, but for privacy, i can't know who are facing this.

what i can do is just upload logs in "unhandled exceptions", however, which is the "more logs" should i collect? it's just starting service.

**Comment by ViktorHofer** [comment]
Is there anything logged in the Windows Event Viewer that could help?

**Comment by mingtong** [comment]
> Is there anything logged in the Windows Event Viewer that could help?
Currently, no.
I collect logs by the time when "Unhandled_exception" was happening and then upload to my server, didnt collect event logs in current version, cause not sure the execution duration for the API GetEventLog(), next version can add it into code.

**Comment by riverar** [comment]
@mingtong Are you by any chance using Entity Framework or SQLite in your startup path? Am hitting this 100% of the time on my machine and am currently trying to get to the bottom of it.

**Comment by mingtong** [comment]
> 

I use SQLite, but don't use EF Core.

**Comment by mingtong** [comment]
> @mingtong Are you by any chance using Entity Framework or SQLite in your startup path? Am hitting this 100% of the time on my machine and am currently trying to get to the bottom of it.

I use SQLite, but don't use EF Core.

**Comment by carlossanlop** [comment]
Would it be possible for one of you to share a minimum repro console app using SQLite? @riverar @mingtong

**Comment by riverar** [comment]
I root caused my particular issue and will file a separate dotnet bug with repro. Sneak preview: Was not related to SQLite, but rather a result of the `BackgroundService` extension not keeping the Windows SCM happy (e.g., cough, me not using the right _WindowsServiceLifetimeOptions.ServiceName_ for its signals). I think similar errors in the SCM area will surface as `Stopped without starting`, which is a really poor/confusing developer experience.

For background: I was also investigating SQLite's bundler, which attempts to activate WinRT types and do _appmodel things_, all without explicitly checking for package identity. There's a try/catch to cover the no-identity scenario, but it seems wrong to keep throwing exceptions that confuse developers during debug. I'll file that bug too.

@mingtong My suggestion for your issue is to try getting Event logs from the affected customers (Application channel). Or at least a screenshot of the user attempting to start the service via Services. Either method should reveal the actual SCM error, which could aid in debugging further. (Mine was `The executable program that this service is configured to run in does not implement the service.`)

**Comment by mingtong** [comment]
> I root caused my particular issue and will file a separate dotnet bug with repro. Sneak preview: Was not related to SQLite, but rather a result of the `BackgroundService` extension not keeping the Windows SCM happy (e.g., cough, me not using the right _WindowsServiceLifetimeOptions.ServiceName_ for its signals). I think similar errors in the SCM area will surface as `Stopped without starting`, which is a really poor/confusing developer experience.
> 
> For background: I was also investigating SQLite's bundler, which attempts to activate WinRT types and do _appmodel things_, all without explicitly checking for package identity. There's a try/catch to cover the no-identity scenario, but it seems wrong to keep throwing exceptions that confuse developers during debug. I'll file that bug too.
> 
> @mingtong My suggestion for your issue is to try getting Event logs from the affected customers (Application channel). Or at least a screenshot of the user attempting to start the service via Services. Either method should reveal the actual SCM error, which could aid in debugging further. (Mine was `The executable program that this service is configured to run in does not implement the service.`)

Many thanks for your information, I will collect more logs in next release, and will update you here.
