### ISSUE TITLE
JsonConverter.Read/WriteAsPropertyName methods throw NotSupportedException when invoked in built-in converters

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#77326]
The code
```C#
var options = new JsonSerializerOptions();
var writer = new Utf8JsonWriter(new MemoryStream());

writer.WriteStartObject();
JsonConverter<int> converter = JsonMetadataServices.Int32Converter;
converter.WriteAsPropertyName(writer, 42, options);
```
throws the following exception
```
Unhandled exception. System.NotSupportedException: The type 'System.Int32' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.Int32Converter'.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at Program.<Main>$(String[] args)
```
Even though the converter does support serializing to dictionary keys. 

The issue does not manifest when the serializer calls into the built-in converters because it follows uses the `Read/WriteAsPropertyNameCore` methods instead. For consistency, we should make sure that the public methods behave as expected when invoked by user code.

**Comment by eiriktsarpalis** [comment]
Another issue is that a number of built-in simple converters such as `VersionConverter` do not implement dictionary key serialization. We should audit what we have an make sure that they implement key serialization:

https://github.com/dotnet/runtime/blob/c34ccb11f4ccd4de0112c34f9ccd86a1a28d9905/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Converters.cs#L47-L74
