### ISSUE TITLE
ConfigurationErrorsException: Section or group name 'system.diagnostics' is already defined.

### ISSUE THREAD

**Issue by MagicAndre1981** [dotnet/runtime#77369]
### Description

I try to migrate a WinForms application from .net6 to .net 7 and noticed that I get an System.Configuration.ConfigurationErrorsException saying that Section or group name 'system.diagnostics' is already defined:

```
Inner Exception 1:
ConfigurationErrorsException: Section or group name 'system.diagnostics' is already defined. Updates to this may only occur at the configuration level where it is defined.
```

### Reproduction Steps

- create a new WinForms app with .net 7 RC2
- add app.config and add usersetting

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
 <configSections>
   <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
   <section name="system.diagnostics"
            type="System.Diagnostics.SystemDiagnosticsSection,
            System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
   <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
     <section name="WinFormsAppAppConfigDemo.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
   </sectionGroup>
 </configSections>
 <entityFramework>
   <defaultConnectionFactory type="EntityFramework.Firebird.FbConnectionFactory, EntityFramework.Firebird" />
   <providers>
     <provider invariantName="FirebirdSql.Data.FirebirdClient" type="EntityFramework.Firebird.FbProviderServices, EntityFramework.Firebird" />
   </providers>
 </entityFramework>
 <system.diagnostics>
   <sources>
     <source name="FirebirdSql.Data.FirebirdClient">
       <listeners>
         <clear />
       </listeners>
     </source>
   </sources>
 </system.diagnostics>
 <userSettings>
  <WinFormsAppAppConfigDemo.Properties.Settings>
   <setting name="myBoolSetting" serializeAs="String">
    <value>False</value>
   </setting>
  </WinFormsAppAppConfigDemo.Properties.Settings>
 </userSettings>
</configuration>
```

- add [system.diagnostics under configSections](https://learn.microsoft.com/en-us/dotnet/architecture/modernize-desktop/migrate-modern-applications#migrating-configuration-files)
- add system.diagnostics and clear a source
- try access the usersetting (`if (Settings.Default.myBoolSetting)`) and exception occrurs 

### Expected behavior

app runs fine

### Actual behavior

exception

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationSystem.cs:line 164
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationSystem.cs:line 201
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigurationSystem.cs:line 60
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientSettingsStore.cs:line 96
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/LocalFileSettingsProvider.cs:line 68
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs:line 166
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs:line 64
   at System.Configuration.SettingsBase.get_Item(String propertyName) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/SettingsBase.cs:line 29
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs:line 694
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName) in /_/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ApplicationSettingsBase.cs:line 395
   at WinFormsAppAppConfigDemo.Properties.Settings.get_myBoolSetting() in C:\Users\Andre\source\repos\WinFormsAppAppConfigDemo\WinFormsAppAppConfigDemo\Properties\Settings.Designer.cs:line 31
   at WinFormsAppAppConfigDemo.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\Andre\source\repos\WinFormsAppAppConfigDemo\WinFormsAppAppConfigDemo\Form1.cs:line 14
   at System.Windows.Forms.Form.OnLoad(EventArgs e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 4111
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 5156
   at System.Windows.Forms.Control.CreateControl() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 5085
   at System.Windows.Forms.Control.WmShowWindow(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13027
   at System.Windows.Forms.Control.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13471
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 369

  This exception was originally thrown at this call stack:
    System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool) in ConfigurationSchemaErrors.cs
    System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors) in BaseConfigurationRecord.cs
    System.Configuration.ClientConfigurationSystem.EnsureInit(string) in ClientConfigurationSystem.cs

Inner Exception 1:
ConfigurationErrorsException: Section or group name 'system.diagnostics' is already defined. Updates to this may only occur at the configuration level where it is defined. (C:\Users\Andre\source\repos\WinFormsAppAppConfigDemo\WinFormsAppAppConfigDemo\bin\Debug\net7.0-windows\WinFormsAppAppConfigDemo.dll.config line 5)
```

### Regression?

yes, worked in .net 6

### Known Workarounds

nothing found

### Configuration

.net 7.0 RC2, Windows 11 22621

**Comment by MagicAndre1981** [comment]
ok, it looks like the Firebird provider no longer used the config so I can remove it to workaround the issue. I'll leave it open for further investigations.

**Comment by buyaa-n** [comment]
>  I'll leave it open for further investigations.

@MagicAndre1981 could you provide a sample app for repro? Tried to follow the `Reproduction Steps` provided, but it did not work, I guess the steps are not complete and as I am not that familiar with WinForms and related settings could not fill in the missing part

**Comment by MagicAndre1981** [comment]
> > I'll leave it open for further investigations.
> 
> @MagicAndre1981 could you provide a sample app for repro? 

here it is:

https://github.com/MagicAndre1981/WinFormsDemoAppRuntimeIssue77369

I added net6 and .net7 as `TargetFrameworks` and the 6.0 version runs fine, while the 7.0 fails

**Comment by buyaa-n** [comment]
Thanks @MagicAndre1981 for the repro, it looks [we added](https://github.com/dotnet/runtime/pull/73087) the `system.diagnostics` in the implicit machine config list:
https://github.com/dotnet/runtime/blob/40df8f6a4c1a1b0b1b731f2a8023b5bb10357790/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L84

so you should not add it in App.config manually, the fix is obviously removing that `<section name="system.diagnostics ..."` section from the `<configSections>`.

> I checked the [breaking changes](https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0), but haven't found anything related to System.Configuration so it looks like a bug to me or if this an intended change, document it please.

Right, it does look like breaking change and needs documented CC @steveharter

**Comment by MagicAndre1981** [comment]
>  it looks [we added](https://github.com/dotnet/runtime/pull/73087) the `system.diagnostics` in the implicit machine config list:
> 
> https://github.com/dotnet/runtime/blob/40df8f6a4c1a1b0b1b731f2a8023b5bb10357790/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L84
> 
> so you should not add it in App.config manually, the fix is obviously removing that `<section name="system.diagnostics ..."` section from the `<configSections>`.

> Right, it does look like breaking change and needs documented CC @steveharter

ok, thanks, please document this when 7.0 gets GA to avoid further confusions

**Comment by steveharter** [comment]
The 7.0 PR https://github.com/dotnet/runtime/pull/73087 added support to automatically read the config file for the System.Diagnostics section -- previously the config section wasn't read and basically was ignored. So those moving from .NET Framework that had an existing app.config file with the diagnostic section would have found that the section was ignored and the various tracesource, switches etc were not hooked up (until the 7.0 PR above).

> it looks https://github.com/dotnet/runtime/pull/73087 the system.diagnostics in the implicit machine config list:

Yes thanks that is the issue -- the entry in the app.config is no longer necessary and causes the exception.

> Right, it does look like breaking change and needs documented CC @steveharter

Per offline discussion, it seems like this is more of a porting issue that should be documented in https://learn.microsoft.com/en-us/dotnet/architecture/modernize-desktop/migrate-modern-applications#migrating-configuration-files . In general, all of the implicit sections (8 or so) no longer can be in the app.config. Whether we also want to add the breaking change is still open, but it is not necessary IMO.

**Comment by steveharter** [comment]
I did create the breaking change issue: https://github.com/dotnet/docs/issues/32147

**Comment by steveharter** [comment]
We should create a docs issue to update https://learn.microsoft.com/en-us/dotnet/architecture/modernize-desktop/migrate-modern-applications#migrating-configuration-files.

**Comment by steveharter** [comment]
Doc issue created: https://github.com/dotnet/docs/issues/32169
