### ISSUE TITLE
Test failure JIT\\Directed\\StructABI\\StructABI\\StructABI.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#77362]
Run: [runtime-coreclr jitstress 20221022.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=60278&view=ms.vss-test-web.build-test-results-tab&runId=1236266&resultId=109448&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\Directed\\StructABI\\StructABI\\StructABI.cmd

coreclr Linux arm Checked jitstress1_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Directed/StructABI/StructABI/StructABI.sh

coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Directed\\StructABI\\StructABI\\StructABI.cmd

coreclr Linux arm Checked jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Directed/StructABI/StructABI/StructABI.sh

coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\Directed\\StructABI\\StructABI\\StructABI.cmd

coreclr Linux arm Checked jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Directed/StructABI/StructABI/StructABI.sh

coreclr Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Directed/StructABI/StructABI/StructABI.sh

coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\Directed\\StructABI\\StructABI\\StructABI.cmd
```
**Error message:**
```
Assert failure(PID 5372 [0x000014fc], Thread: 8388 [0x20c4]): Assertion failed '((lclNode->gtFlags & GTF_VAR_DEF) != 0) && (((lclNode->gtFlags & GTF_VAR_USEASG) != 0) == !isFullDef)' in 'InlineArray1:Get():InlineArray1' during 'SSA: insert phis' (IL size 42; hash 0x77245012; Tier0-FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\ssabuilder.cpp Line: 753
Image: C:\h\w\B2970998\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\B2970998\w\C84E0AD9\uploads\Reports\JIT.Directed\StructABI\StructABI\StructABI.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B2970998\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  StructABI.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B2970998\p
C:\h\w\B2970998\w\C84E0AD9\e\JIT\Directed\StructABI\StructABI\StructABI.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._StructABI_StructABI_StructABI_._StructABI_StructABI_StructABI_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment]
cc @SingleAccretion, related to some of the recent SSA work?

**Comment by SingleAccretion** [comment]
Indeed, the assert was updated to check `USEASG` is set correctly as well; suspect that has revealed some pre-existing issues. Will take a look.

**Comment by SingleAccretion** [comment]
The issue here is that we do not update the def flags when we unroll a loop (because we don't remorph the cloned statements). I can see a couple solutions:

1) Relax the assert to only apply to non-address-exposed variables.
2) Remorph statements after cloning them.
3) Handle this inside `gtCloneExpr`.

I am inclined to go with `3` as the least impactful change. In due time, all this flag setting and resetting will go away anyway.
