### ISSUE TITLE
Ubuntu: dotnet-dump/gcdump can not dump process memory if application was compiled on windows machine

### ISSUE THREAD

**Issue by Greendq** [dotnet/runtime#77392]
### Description

When project is cross-compiled under Windows for Linux, dotnet-dump and dotnet-gcdump can not create dumps for the running process. Tested on Ubuntu 20.04 and Ubuntu 22.04. Tested on Amazon VMs, but looks like virtualization does not matter here.

When the same application is compiled under Linux on testing machine - tools works as expected, dumps are created.

To reproduce:
[console.zip](https://github.com/dotnet/diagnostics/files/9260109/console.zip)

1) Create the simplest snippet:

```
namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
	    Console.ReadLine();
        }
    }
}

```
2) Compile it under Windows platform for Linux:

```
dotnet publish -r linux-x64 --self-contained -c Debug /p:PublishSingleFile=false /p:PublishTrimmed=false

Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\tmp\console\windows.csproj (in 87 ms).
  windows -> D:\tmp\console\bin\Debug\net6.0\linux-x64\windows.dll
  windows -> D:\tmp\console\bin\Debug\net6.0\linux-x64\publish\

D:\tmp\console>dotnet --version
6.0.302

```
3) Run it on Linux from one terminal and try to created a memory dump from another terminal.
```

ubuntu@ip-172-30-4-132:~/console/publish$ ps ax|grep windows
   5548 pts/1    Sl+    0:00 ./windows
   5558 pts/2    S+     0:00 grep --color=auto windows
ubuntu@ip-172-30-4-132:~/console/publish$ dotnet-dump collect -p 5548

Writing full to /home/ubuntu/console/publish/core_20220804_103250
Write dump failed - HRESULT: 0x00000000.
ubuntu@ip-172-30-4-132:~/console/publish$ dotnet-gcdump collect -p 5548
Writing gcdump to '/home/ubuntu/console/publish/20220804_103344_5548.gcdump'...
        Failed to collect gcdump. Try running with '-v' for more information.
ubuntu@ip-172-30-4-132:~/console/publish$ dotnet-gcdump collect -v -p 5548
Writing gcdump to '/home/ubuntu/console/publish/20220804_103355_5548.gcdump'...
  0.0s: Creating type table flushing task
  0.0s: [Error] Exception during gcdump: Microsoft.Diagnostics.NETCore.Client.ServerNotAvailableException: Process 5548 not running compatible .NET runtime.
   at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.GetDefaultAddress() in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs:line 282
   at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.Connect(TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs:line 243
   at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessageGetContinuation(IpcEndpoint endpoint, IpcMessage message) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs:line 40
   at Microsoft.Diagnostics.NETCore.Client.EventPipeSession.Start(IpcEndpoint endpoint, IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs:line 33
   at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.StartEventPipeSession(IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB) in /_/src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs:line 69
   at Microsoft.Diagnostics.Tools.GCDump.EventPipeSessionController..ctor(Int32 pid, List`1 providers, Boolean requestRundown) in /_/src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs:line 235
   at Microsoft.Diagnostics.Tools.GCDump.EventPipeDotNetHeapDumper.DumpFromEventPipe(CancellationToken ct, Int32 processID, MemoryGraph memoryGraph, TextWriter log, Int32 timeout, DotNetHeapInfo dotNetInfo) in /_/src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs:line 52
[  0.0s: Done Dumping .NET heap success=False]
        Failed to collect gcdump. Try running with '-v' for more information.
ubuntu@ip-172-30-4-132:~/console/publish$ dotnet --version
6.0.302

```

In some rare cases dotnet-gcdump produces dump successfully for more complex project, but it fails for the simple snippet. 

### Configuration

Build machine: Windows 10 Pro, Net SDK 6.0.302, x86-64 (Intel), Visual Studio 2022 community edition, version 17.2.6

Tested on AWS Ubuntu 20.04 and 22.04, both VMs are x86-64, on both VMs was installed latest full SDK version 6.0

No matter if tools are running as unprivileged user (the same as user launched application) or root user - results are the same, both tools fail to crate dumps.

**Comment by Greendq** [comment]
Just for clarification: it was NOT a single-file application, it was bunch of files, just all needed *dll`s into one directory.

**Comment by mikem8361** [comment]
Sorry, I looked at the "/p:PublishSingleFile=false" part of the command incorrectly and thought it was setting it to true.

**Comment by raffaeler** [comment]
I did not use single file option as well.
I published with --self-contained instead

**Comment by mikem8361** [comment]
I'm curious if you copied all the of the "publish" directory (bin\Debug\net6.0\linux-x64\publish) files?  I just tried to repro this with Windows 10/WSL Ubuntu 22.04 and dump generation/createdump works. 

One thing (not sure if I have already suggested this) is to add --diag to your dotnet-dump collect command. The option sends logging to the app's console.

**Comment by raffaeler** [comment]
Yes, I did copy the entire content of the publish folder created right after the `dotnet publish` command using the `--self-contained=true` argument.

More recently I abandoned dotnet-dump and I am dumping using the clrmd dump facility which fails as well. Do they share the same dumping code?

**Comment by mikem8361** [comment]
Depending on how you copied the files to the Linux machine, the execute flag on the createdump binary may not be set.  Can you check that with `ls -l ./createdump`?

I'll have to look at clrmd, but if you are creating the dump on linux, it is using the same code.

**Comment by Greendq** [comment]
> Depending on how you copied the files to the Linux machine, the execute flag on the createdump binary may not be set. Can you check that with `ls -l ./createdump`?
> 
> I'll have to look at clrmd, but if you are creating the dump on linux, it is using the same code.

Looks like this was the issue - when I changed the permissions for createdump to 755 - it worked.

So, actually, this is not a bug, but a feature.

Anyway, error messages says nothing about wrong executable flag permissions for the createdump.

Thank you!

**Comment by mikem8361** [comment]
You should get better error messages in 7.0 something like `Problem launching createdump (may not have execute permissions): execve() FAILED`.  So are we good?  Can we close this issue?

**Comment by Greendq** [comment]
Yes, better error message will solve a lot of issues of this kind.

You are brilliant, thank you.

And yes, you can close the issue :)
