### ISSUE TITLE
Assert running System.Net.Sockets tests on macOS 13

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#77416]
When running the System.Net.Sockets tests on the newly-released macOS 13 (Ventura):

```
./dotnet.sh build /t:test /p:Outerloop=true src/libraries/System.Net.Sockets/tests/FunctionalTests
```

Fails with the following assert here:

https://github.com/dotnet/runtime/blob/f791f78f605e5d4941f91c888db59ac656940bd1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Unix.cs#L288

```
Process terminated. Assertion failed.
  LingerState. Expected: System.Net.Sockets.LingerOption, Actual: System.Net.Sockets.LingerOption
```

The full stack:

```
Process terminated. Assertion failed.
  LingerState. Expected: System.Net.Sockets.LingerOption, Actual: System.Net.Sockets.LingerOption
     at System.Net.Sockets.Socket.CopyStateFromSource(Socket source) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Unix.cs:line 288
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(SocketAddress remoteSocketAddress) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 350
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(Int32 bytesTransferred, SocketFlags flags) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 883
     at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 983
     at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 376
     at System.Net.Sockets.SocketAsyncEventArgs.AcceptCompletionCallback(IntPtr acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressSize, SocketError socketError) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 30
     at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback(Boolean allowPooling) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 616
     at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 973
     at System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation op) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1382
     at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute() in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 341
     at System.Net.Sockets.SocketAsyncContext.AsyncOperation.Process() in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 292
     at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events) in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 2187
     at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute() in /Users/vcsjones/Projects/runtime/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs:line 242
     at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/vcsjones/Projects/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
     at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /Users/vcsjones/Projects/runtime/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
     at System.Threading.Thread.StartCallback() in /Users/vcsjones/Projects/runtime/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
```

**Comment by wfurt** [comment]
I can reproduce. This is strange as it is failing to compare `LingerOptions` after accept. As far as I can tell they are the same and it even does not call any kernel code on the socket. 

This is debug asset and it does not feel like critical for Ventura support.

**Comment by filipnavara** [comment]
The strange thing is the difference in the case of `System.Net` and `System.NET`.

**Comment by vcsjones** [comment]
> The strange thing is the difference in the case of `System.Net` and `System.NET`.

That was Apple's aggressive autocorrect when I pasted. It learned ".NET" from me.

**Comment by am11** [comment]
Is it x64 specific? I couldn't reproduce it on M1 running macOS 13 (`sw_vers -buildVersion`: 22A380).

**Comment by vcsjones** [comment]
@am11 
> Is it x64 specific? I couldn't reproduce it on M1 running macOS 13 (`sw_vers -buildVersion`: 22A380).

No, I reproduced it on an M1 running the same OS build.

Whatever is triggering it is an outerloop test. It doesn't reproduce if I leave out `/p:Outerloop=true`.

**Comment by am11** [comment]
I ran those tests 10 times, it is passing; could be some other difference then.

```zsh
% pkill -KILL dotnet

% for ((n=0;n<10;n++)); do
  ./dotnet.sh build /t:test /p:Outerloop=true src/libraries/System.Net.Sockets/tests/FunctionalTests
done
```

**Comment by wfurt** [comment]
good to know. I get same assert as Kevin - needs debug build as it is under `#if DEBUG`

**Comment by am11** [comment]
Yup, I used debug (default); tried clean build with a6cb7705bd5317ab5e9f718b55a82444156fc0c8, no failures.

**Comment by wfurt** [comment]
Do you still see it failing @vcsjones? I don't have ARM handy at the moment and it does not fail for me on 13.6 on Intel Mac.

**Comment by vcsjones** [comment]
No. The assert is gone for me on the same machine that was asserting before. Since there doesn't seem to be anything actionable here, closing.

**Comment by wfurt** [comment]
thanks for confirming @vcsjones
