### ISSUE TITLE
[tests][Android] LargeHeaders_TrickledOverTime_ProcessedEfficiently Insufficient Memory

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#77474]
Out Of Memory Exception on Android x86 and arm

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=63540&view=logs&j=bf46dbf5-7e63-514c-8f02-f313a0e24f72&t=2f14e9fa-1a65-5c95-6243-fe027309024d

```
trailingHeaders: False, async: True, lineFolds: False
trailingHeaders: False, async: False, lineFolds: Truee
trailingHeaders: False, async: False, lineFolds: False
```
```
System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
at System.Net.Http.HttpConnection.FillAsync(Boolean async) at System.Net.Http.HttpConnection.<FillForHeadersAsync>g__ReadUntilEndOfHeaderAsync|100_0(Boolean async)
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken) at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.Send(HttpRequestMessage request)
at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_MaxResponseHeadersLength_Http11.LargeHeaders_TrickledOverTime_ProcessedEfficiently(Boolean trailingHeaders, Boolean async, Boolean lineFolds) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 1384 --- End of stack trace from previous location ---

**Comment by MihaZupan** [comment]
I think this test may reach ~200 MB of memory at max, is that too much for android test?

**Comment by mdh1418** [comment]
> is that too much for android tests?

I'm hearing that the emulators have 3GB, so the memory stress is probably not solely from the test if the tests are truly 200MB max

**Comment by steveisok** [comment]
I'm not aware of this happening too often anymore.  Feel free to reopen if you find otherwise.

**Comment by MihaZupan** [comment]
The test is still disabled against this issue
https://github.com/dotnet/runtime/blob/35e23f7216bb7d0c3adfa2217bce35fbc447941e/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L1601-L1602

**Comment by vitek-karas** [comment]
@simonrozsival as a lower pri - could you please look what it would take to reenable the test?
