### ISSUE TITLE
[NativeAOT] Failed to load SQLitePCLRaw.core

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#77476]
When building NativeAOT for Linux, OSX, and Windows, the build fails to load `SQLitePCLRaw.core`

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=63540&view=logs&j=1a903bec-56c1-5f69-7b57-f0ab9c1e238e
```

     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ResolveHandle(EntityHandle handle) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 61
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode typeCode) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 143
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode typeCode) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 98
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 309
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseFieldSignature() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaSignatureParser.cs:line 449
     at Internal.TypeSystem.Ecma.EcmaField.InitializeFieldType() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaField.cs:line 102
     at Internal.TypeSystem.MetadataFieldLayoutAlgorithm.ComputeInstanceLayout(DefType defType, InstanceLayoutKind layoutKind) in /_/src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs:line 38
     at Internal.TypeSystem.DefType.ComputeInstanceLayout(InstanceLayoutKind layoutKind) in /_/src/coreclr/tools/Common/TypeSystem/Common/DefType.FieldLayout.cs:line 436
     at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc type) in /_/src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs:line 137
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 558
     at ILCompiler.DependencyAnalysis.EETypeNode..ctor(NodeFactory factory, TypeDesc type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/EETypeNode.cs:line 83
     at ILCompiler.DependencyAnalysis.NodeFactory.CreateNecessaryTypeNode(TypeDesc type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 514
     at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
     at ILCompiler.DependencyAnalysis.GenericCompositionNode.GetData(NodeFactory factory, Boolean relocsOnly) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/GenericCompositionNode.cs:line 90
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory factory) in /_/src/coreclr/tools/Common/Compiler/DependencyAnalysis/ObjectNode.cs:line 59
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 182
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 222
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 257
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 308
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 140
     at ILCompiler.Program.<Run>g__RunScanner|3_0(<>c__DisplayClass3_0&) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 405
     at ILCompiler.Program.Run() in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 385
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass197_0.<.ctor>b__0(InvocationContext context) in /_/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 266
```

**Comment by am11** [comment]
Failing since https://github.com/dotnet/runtime/commit/c6c8bb8b73ff4f7a686ca5a350fbb0093b3b708b.

```
  Internal.TypeSystem.TypeSystemException+FileNotFoundException: Failed to load assembly 'SQLitePCLRaw.core'
     at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID id, String fileName) in /_/src/coreclr/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 35
```

cc @roji

**Comment by teo-tsirpanis** [comment]
The commit you linked only changed test code.

**Comment by am11** [comment]
@teo-tsirpanis, that's the first commit off of `main` branch which failed with FileNotFoundException according to AzDO.

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/3840695/198171210-e5827c89-4dca-4983-a950-849f354de191.png">

**Comment by MichalStrehovsky** [comment]
The CI runs are batched - it was likely introduced in https://github.com/dotnet/runtime/commit/e139ffb68a34584eabaaf68bfdf733b1d8f53d81 when the test was added. I'm disabling it in https://github.com/dotnet/runtime/pull/77522.
