### ISSUE TITLE
Test failure JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#77527]
Run: [runtime-coreclr jitstress 20221025.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=63546&view=ms.vss-test-web.build-test-results-tab&runId=1293342&resultId=106526&paneView=debug)

Failed test:
```
coreclr Linux arm Checked jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
- JIT/superpmi/superpmicollect/superpmicollect.sh
- JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh
... ...
coreclr Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/superpmi/superpmicollect/superpmicollect.sh
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
- JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
- profiler/unittest/getappdomainstaticaddress/getappdomainstaticaddress.sh
- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
... ...
coreclr Linux arm Checked jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/superpmi/superpmicollect/superpmicollect.sh
- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
- JIT/superpmi/superpmicollect/CscBench/CscBench.sh
- profiler/elt/slowpatheltenter/slowpatheltenter.sh
... ...
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- GC\\Features\\SustainedLowLatency\\scenario\\scenario.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_ro\\Vector128_ro.cmd
- Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd
... ...
coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- Loader\\classloader\\explicitlayout\\objrefandnonobjrefoverlap\\case14\\case14.cmd
... ...
coreclr Linux arm Checked jitstress1_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- GC/Features/SustainedLowLatency/scenario/scenario.sh
- JIT/superpmi/superpmicollect/superpmicollect.sh
- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
- Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
- JIT/superpmi/superpmicollect/CscBench/CscBench.sh
... ...
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- Loader\\classloader\\MethodImpl\\CovariantReturns\\Interfaces\\UnitTest\\UnitTest.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\Sse2_ro\\Sse2_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx1\\Avx_ro\\Avx_ro.cmd
- baseservices\\exceptions\\unittests\\TryCatchInFinally\\TryCatchInFinally.cmd
... ...
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
... ...
```
**Error message:**
```
Assert failure(PID 588 [0x0000024c], Thread: 588 [0x024c]): Assertion failed 'isCandidateVar(fieldVarDsc) == isMultiReg' in 'AssignJagged:DoAssignIteration(int[][][],int):long' during 'Linear scan register alloc' (IL size 40; hash 0x0297ed52; Tier0-MinOpts)

File: /__w/1/s/src/coreclr/jit/lsrabuild.cpp Line: 1269
Image: /root/helix/work/correlation/corerun
[createdump] waitpid() returned successfully (wstatus 00000000)
/root/helix/work/workitem/e/JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh: line 422:   588 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Performance/CodeQuality/Bytemark/Bytemark/Bytemark.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Bytemark.dll ''
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 509.42890  Index: 13.06462
NUMERIC SORT(rectangle):  Iterations/sec: 386.36585  Index: 9.90860
STRING SORT:  Iterations/sec: 1275.61272  Index: 569.97887
BITFIELD:  Iterations/sec: 62309016.73850  Index: 10.68820
FP EMULATION(struct):  Iterations/sec: 62.74860  Index: 30.10969
FP EMULATION(class):  Iterations/sec: 60.01666  Index: 28.79878
FOURIER:  Iterations/sec: 15345.67639  Index: 17.45259
ASSIGNMENT(jagged):[createdump] Gathering state for process 588 corerun
[createdump] Crashing thread 0000024c signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.588.dmp
[createdump] Written 73203712 bytes (17872 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 2393ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Performance._CodeQuality_Bytemark_Bytemark_Bytemark_._CodeQuality_Bytemark_Bytemark_Bytemark_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-26T06:46:07.151Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=63546&view=ms.vss-test-web.build-test-results-tab&runId=1293650&resultId=106214&paneView=debug)
2022-10-26T06:01:02.055Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=63546&view=ms.vss-test-web.build-test-results-tab&runId=1293342&resultId=106526&paneView=debug)
2022-10-12T08:58:25.529Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=49282&view=ms.vss-test-web.build-test-results-tab&runId=992930&resultId=101987&paneView=debug)
2022-09-24T08:51:23.447Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=28573&view=ms.vss-test-web.build-test-results-tab&runId=576324&resultId=101947&paneView=debug)
2022-09-23T06:56:27.552Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545718&resultId=103953&paneView=debug)
2022-09-23T06:33:57.904Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545292&resultId=102865&paneView=debug)
2022-09-23T06:21:02.909Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545106&resultId=106162&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-09-23T06:21:02.018Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545108&resultId=105510&paneView=debug)
2022-09-23T06:19:28.895Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545100&resultId=103781&paneView=debug)
2022-09-23T06:06:50.788Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545010&resultId=102881&paneView=debug)
2022-09-23T06:01:51.583Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=544924&resultId=106402&paneView=debug)
2022-09-22T07:26:26.975Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=521058&resultId=104254&paneView=debug)
2022-09-22T07:09:06.366Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520844&resultId=103731&paneView=debug)
2022-09-22T06:52:24.578Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520634&resultId=105431&paneView=debug)
2022-09-22T06:41:01.815Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520484&resultId=105665&paneView=debug)
2022-09-22T06:37:18.032Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520452&resultId=103580&paneView=debug)
2022-09-22T06:23:36.542Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520288&resultId=102201&paneView=debug)
2022-09-22T06:23:34.727Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520290&resultId=102911&paneView=debug)
2022-09-22T06:19:30.608Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520254&resultId=103561&paneView=debug)
2022-09-22T06:19:26.433Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520256&resultId=105975&paneView=debug)
2022-09-22T06:11:07.948Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520160&resultId=102584&paneView=debug)
2022-09-21T06:32:36.124Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493604&resultId=104546&paneView=debug)
2022-09-21T06:15:40.238Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493444&resultId=103554&paneView=debug)
2022-09-21T06:15:08.091Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493442&resultId=101894&paneView=debug)
2022-09-21T06:12:11.216Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493434&resultId=103999&paneView=debug)
2022-09-21T06:09:58.841Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493406&resultId=105521&paneView=debug)
2022-09-21T06:01:51.189Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493336&resultId=102617&paneView=debug)
2022-09-21T06:01:48.876Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493334&resultId=102073&paneView=debug)
2022-09-21T05:51:52.907Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493264&resultId=102408&paneView=debug)
2022-09-21T05:51:25.838Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493246&resultId=102240&paneView=debug)
2022-09-21T05:51:23.576Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493250&resultId=103963&paneView=debug)
2022-09-20T07:03:31.507Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=469174&resultId=103576&paneView=debug)
2022-09-20T06:29:15.318Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468562&resultId=102287&paneView=debug)
2022-09-20T06:25:34.076Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468470&resultId=103778&paneView=debug)
2022-09-20T06:22:33.291Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468446&resultId=104488&paneView=debug)
2022-09-20T06:22:30.991Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468444&resultId=104044&paneView=debug)
2022-09-20T06:09:55.262Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468184&resultId=101117&paneView=debug)
2022-09-20T06:07:40.552Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468126&resultId=106436&paneView=debug)
2022-09-20T05:58:14.425Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=467920&resultId=101979&paneView=debug)
2022-09-20T05:58:12.172Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress   Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=467916&resultId=102347&paneView=debug)
</details>

**Comment by jakobbotsch** [comment]
@SingleAccretion I assume this is fixed by #77502?

**Comment by SingleAccretion** [comment]
Yep. I've checked the latest stress run and it green as expected.

**Comment by kunalspathak** [comment]
> Yep. I've checked the latest stress run and it is green as expected.

This was recently hit in Antigen: https://dev.azure.com/dnceng-public/public/_build/results?buildId=89026&view=ms.vss-build-web.run-extensions-tab

(Non-reduced) repro: https://gist.github.com/kunalspathak/6822cfa8315747ad87b4a46a54eae3ef
