### ISSUE TITLE
[tests] SyndicationFeed_Load_Write_RSS_Feed failing on Wasm with tmp/ file already exists

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#77526]
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=63936&view=logs&j=d4e38924-13a0-58bd-9074-6a4810543e7c&t=7a581d54-fbdb-5b9d-4377-cc346f489112
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77487-merge-c4fe11b1c351438183/WasmTestOnBrowser-System.ServiceModel.Syndication.Tests/1/console.a322771a.log?helixlogtype=result
```
[16:44:34] fail: [FAIL] System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom
[16:44:34] info: System.IO.IOException : The file '/tmp/' already exists.
[16:44:34] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
[16:44:34] info:    at Interop.CheckIo(Int64 result, String path, Boolean isDirError)
[16:44:34] info:    at Interop.CheckIo(IntPtr result, String path, Boolean isDirError)
[16:44:34] info:    at System.IO.Path.GetTempFileName()
[16:44:34] info:    at System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom()
[16:44:34] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
[16:44:35] info: Finished:    System.ServiceModel.Syndication.Tests.dll
```

**Comment by akoeplinger** [comment]
Hit this outside of wasm too, tracking via: https://github.com/dotnet/runtime/issues/78454
