### ISSUE TITLE
[wasm] Test failing on nodejs - `SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.ResponseHeaders_ExtraWhitespace_Trimmed`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#77631]
[log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77448-merge-bed3bf982b5047e8b4/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.1e2cf2e6.log?helixlogtype=result):

```
[09:31:18] info: Starting:    System.Net.Http.Functional.Tests.dll
[09:31:19] info: (node:13868) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[09:31:19] info: (Use `node --trace-warnings ...` to show where the warning was created)
[09:31:19] fail: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.ResponseHeaders_ExtraWhitespace_Trimmed
[09:31:19] info: Assert.True() Failure
[09:31:19] info: Expected: True
[09:31:19] info: Actual:   False
[09:31:19] info:    at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.<ResponseHeaders_ExtraWhitespace_Trimmed>b__1_0(Uri uri)
[09:31:19] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[09:31:19] info: --- End of stack trace from previous location ---
[09:31:19] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[09:31:19] info:    at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass15_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[09:31:19] info: --- End of stack trace from previous location ---
[09:31:19] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[09:31:19] info:    at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.ResponseHeaders_ExtraWhitespace_Trimmed()
[09:31:19] info: --- End of stack trace from previous location ---
```

This started in the same time range as https://github.com/dotnet/runtime/issues/77630 .

cc @pavelsavara @maraf 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
These are failing to find the test headers in the http response. And also the app might be crashing at the end. And trivially reproducible.

**Comment by radical** [comment]
@maraf this is still failing, keeping `runtime-wasm` red. Can we disable the tests?
