### ISSUE TITLE
Test failure R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open JIT\\jit64\\mcc\\interop\\mcc_i17\\mcc_i17.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#77662]
Run: [runtime-coreclr crossgen2 20221029.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67252&view=ms.vss-test-web.build-test-results-tab&runId=1369656&resultId=100835&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open
- JIT\\jit64\\mcc\\interop\\mcc_i17\\mcc_i17.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i16\\mcc_i16.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i86\\mcc_i86.cmd
- JIT\\Directed\\callconv\\StdCallMemberFunction\\StdCallMemberFunctionTest\\StdCallMemberFunctionTest.cmd
- JIT\\Directed\\callconv\\CdeclMemberFunction\\CdeclMemberFunctionTest\\CdeclMemberFunctionTest.cmd
... ...
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\jit64\\mcc\\interop\\mcc_i07\\mcc_i07.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i86\\mcc_i86.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i36\\mcc_i36.cmd
- JIT\\Directed\\callconv\\StdCallMemberFunction\\StdCallMemberFunctionTest\\StdCallMemberFunctionTest.cmd
- JIT\\Directed\\callconv\\ThisCall\\EmptyThisCallTest\\EmptyThisCallTest.cmd
... ...
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\jit64\\mcc\\interop\\mcc_i17\\mcc_i17.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i16\\mcc_i16.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i86\\mcc_i86.cmd
- JIT\\jit64\\hfa\\main\\testC\\hfa_nd1C_r\\hfa_nd1C_r.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i66\\mcc_i66.cmd
... ...
R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
- JIT\\jit64\\mcc\\interop\\mcc_i57\\mcc_i57.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i86\\mcc_i86.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i66\\mcc_i66.cmd
- JIT\\Directed\\callconv\\PlatformDefaultMemberFunction\\PlatformDefaultMemberFunctionTest\\PlatformDefaultMemberFunctionTest.cmd
- JIT\\jit64\\hfa\\main\\testC\\hfa_nd1C_r\\hfa_nd1C_r.cmd
... ...
```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\BE1409E8\w\B305096E\uploads\Reports\JIT.jit64\mcc\interop\mcc_i17\mcc_i17.output.txt
Raw output:
BEGIN EXECUTION
mcc_i17.dll
native_i0c.dll
native_i0s.dll
native_i1c.dll
native_i1s.dll
native_i3c.dll
native_i3s.dll
native_i5c.dll
native_i5s.dll
native_i6c.dll
native_i6s.dll
native_i7c.dll
native_i7s.dll
native_i8c.dll
native_i8s.dll
15 file(s) copied.
1:27:24.90
Response file: D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\mcc_i17.dll.rsp
D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\IL-CG2\mcc_i17.dll
-o:D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\mcc_i17.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\BE1409E8\p\System..dll
-r:D:\h\w\BE1409E8\p\Microsoft..dll
-r:D:\h\w\BE1409E8\p\mscorlib.dll
-r:D:\h\w\BE1409E8\p\netstandard.dll
-O
" "dotnet" "D:\h\w\BE1409E8\p\crossgen2\crossgen2.dll" @"D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\mcc_i17.dll.rsp"   -r:D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\mcc_i17.dll
" "dotnet" "D:\h\w\BE1409E8\p\r2rdump\r2rdump.dll" --disasm --header --sc --in D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\mcc_i17.dll --out D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\mcc_i17.dll.r2rdump"
1:27:30.88
1:27:30.90
Response file: D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0c.dll.rsp
D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\IL-CG2\native_i0c.dll
-o:D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0c.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\BE1409E8\p\System..dll
-r:D:\h\w\BE1409E8\p\Microsoft..dll
-r:D:\h\w\BE1409E8\p\mscorlib.dll
-r:D:\h\w\BE1409E8\p\netstandard.dll
-O
" "dotnet" "D:\h\w\BE1409E8\p\crossgen2\crossgen2.dll" @"D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0c.dll.rsp"   -r:D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\IL-CG2*.dll"
No input files are loadable
" "dotnet" "D:\h\w\BE1409E8\p\r2rdump\r2rdump.dll" --disasm --header --sc --in D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0c.dll --out D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0c.dll.r2rdump"
Error: System.BadImageFormatException: ECMA metadata / RTR_HEADER not found in file 'D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0c.dll'
at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in //src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 484
at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader..ctor(IAssemblyResolver assemblyResolver, String filename) in //src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 404
at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 447
1:27:31.91
1:27:31.93
Response file: D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0s.dll.rsp
D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\IL-CG2\native_i0s.dll
-o:D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0s.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\BE1409E8\p\System..dll
-r:D:\h\w\BE1409E8\p\Microsoft..dll
-r:D:\h\w\BE1409E8\p\mscorlib.dll
-r:D:\h\w\BE1409E8\p\netstandard.dll
-O
" "dotnet" "D:\h\w\BE1409E8\p\crossgen2\crossgen2.dll" @"D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0s.dll.rsp"   -r:D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\IL-CG2*.dll"
No input files are loadable
" "dotnet" "D:\h\w\BE1409E8\p\r2rdump\r2rdump.dll" --disasm --header --sc --in D:\h\w\BE1409E8\w\B305096E\e\JIT\jit64\mcc\interop\mcc_i17\native_i0s.dll --out D:\h\


Stack trace
   at JIT_jit64._mcc_interop_mcc_i17_mcc_i17_._mcc_interop_mcc_i17_mcc_i17_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment]
The R2RDump invocation is newly added by #74963, cc @cshung. It is also causing failures for [pgostress](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66922&view=results) and [pgo](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67270&view=results).

**Comment by cshung** [comment]
Thanks, @jakobbotsch. I knew something would blow up.

Is there any way I can reproduce these failures locally? I would like to diagnose what's going on.

Judging from the output, it appears that either crossgen2 is not compiling, generated a corrupted binary, or we have some decoding bug in R2RDump. In either case, it would be good to take a look at what happened there.

**Comment by jakobbotsch** [comment]
For a lot of the win-arm32 issues it seems like we just don't have coredistools.dll available there. cc @BruceForstall to confirm.

For this particular issue it seems we are invoking `r2rdump` on a native DLL and it fails to find the R2R_HEADER, which also seems expected. You can see crossgen2 gives "No input files are loadable" instead, which apparently does not fail.

To reproduce this on an win-arm64 machine you just need to build that particular test and run the test wrapper while setting `RunCrossGen2=1`.

**Comment by BruceForstall** [comment]
> For a lot of the win-arm32 issues it seems like we just don't have coredistools.dll available there. cc @BruceForstall to confirm.

Yes, it got removed with https://github.com/dotnet/jitutils/pull/348 since win-arm is not officially supported. It shouldn't affect gcstress, but obviously does support win-arm native hosted disasm.
