### ISSUE TITLE
[wasm] `dotnet-runtime-perf` pipeline completely broken

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#77883]
The wasm perf runs are broken after https://github.com/dotnet/runtime/pull/77852 . I haven't investigated why that would be breaking the runs, but all of the wasm ones broke. I don't know if some of the non-wasm ones are breaking too.

1. previous passing pipeline [run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2036755&view=results) which is building exactly the previous commit
2. and the failing [run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2037006&view=logs&j=10348dd7-5cd6-5c42-fc55-e890e0795f10&t=3fe50c48-466c-5f5d-0411-aa33700b2a9d&l=58)

The wasm runs are failing with:
```
[2022/11/03 22:06:50][INFO] $ dotnet exec MicroBenchmarks.dll --anyCategories Libraries Runtime "" --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmEngine /home/helixbot/.jsvu/v8 --cli /home/helixbot/work/B85009EF/p/dotnet/dotnet --wasmDataDir /home/helixbot/work/B85009EF/p/wasm-data --logBuildOutput --generateBinLog "" --partition-count 30 --partition-index 10 --artifacts /home/helixbot/work/B85009EF/w/9F070920/e/artifacts/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/B85009EF/w/9F070920/e/performance/artifacts/packages --runtimes wasmnet70 --buildTimeout 1200
[2022/11/03 22:06:50][INFO] Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
[2022/11/03 22:06:50][INFO] 
[2022/11/03 22:06:50][INFO] File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[2022/11/03 22:06:50][INFO] $ popd
[2022/11/03 22:06:50][ERROR] Process exited with status -6
[2022/11/03 22:06:50][INFO] Run failure registered
Traceback (most recent call last):
  File "/home/helixbot/work/B85009EF/w/9F070920/e/performance/scripts/benchmarks_ci.py", line 326, in <module>
    __main(sys.argv[1:])
  File "/home/helixbot/work/B85009EF/w/9F070920/e/performance/scripts/benchmarks_ci.py", line 295, in __main
    args
  File "/home/helixbot/work/B85009EF/w/9F070920/e/performance/scripts/micro_benchmarks.py", line 357, in run
    status = dotnet.exec(asm_path, success_exit_codes, verbose, *run_args)
  File "/home/helixbot/work/B85009EF/w/9F070920/e/performance/scripts/dotnet.py", line 54, in exec
    return RunCommand(cmdline, success_exit_codes, verbose=verbose).run(working_dir)
  File "/home/helixbot/work/B85009EF/w/9F070920/e/performance/scripts/performance/common.py", line 251, in run
    returncode, quoted_cmdline)
subprocess.CalledProcessError: Command '$ dotnet exec MicroBenchmarks.dll --anyCategories Libraries Runtime "" --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmEngine /home/helixbot/.jsvu/v8 --cli /home/helixbot/work/B85009EF/p/dotnet/dotnet --wasmDataDir /home/helixbot/work/B85009EF/p/wasm-data --logBuildOutput --generateBinLog "" --partition-count 30 --partition-index 10 --artifacts /home/helixbot/work/B85009EF/w/9F070920/e/artifacts/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/B85009EF/w/9F070920/e/performance/artifacts/packages --runtimes wasmnet70 --buildTimeout 1200' died with <Signals.SIGABRT: 6>.
```

cc @lewing @AaronRobinsonMSFT 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
- I tested with Aaron's commit (https://github.com/dotnet/runtime/commit/803688595257517f4b47e873d11152b0560c204a) intact
- Between the two CI runs:
  - `dotnet/performance` repo had some new commits, and removing https://github.com/dotnet/performance/commit/860803b569cb8cad6a9da437eddfd7da747ccead seems to fix the issue
  - Even with the commit, building for `net7.0` works fine
  - The 8.0 sdk installed in `dotnet/runtime`, and the `Wasm-tools` workload isn't quite on net8.0 yet. And now we also have https://github.com/dotnet/runtime/pull/77899 . I think this performance commit should be reverted till the sdk+runtime becomes usable for net8.0 .

cc @LoopedBard3 @ericstj

@AaronRobinsonMSFT this looks completely unrelated to your PR 👍

**Comment by AaronRobinsonMSFT** [comment]
> @AaronRobinsonMSFT this looks completely unrelated to your PR 👍

:heart: Thanks @radical. Your diligence here is most appreciated.

**Comment by radical** [comment]
Closing this as the pipeline has been green after the reverts, and changes.
