### ISSUE TITLE
[gcstress0x3-gcsttress0xc] Interop/COM/ComWrappers/WeakReference/WeakReferenceTest/WeakReferenceTest fails

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#77976]
This seems to fail in most configurations.
Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=74629&view=ms.vss-test-web.build-test-results-tab&runId=1537250&resultId=100704&paneView=debug
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-14125259177c4ad1a0/Interop/1/console.3beead92.log?helixlogtype=result

```scala
  Starting:    Interop.COM.XUnitWrapper (parallel test collections = on, max threads = 4)
    Interop\COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\9EB00911\w\A7D3099F\uploads\Reports\Interop.COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\9EB00911\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  WeakReferenceTest.dll 
      Running ValidateNonComWrappers...
      Running ValidateGlobalInstanceMarshalling...
        -- Validate weak reference creation
          -- Validate RCW recreation
          -- Validate release
        -- Validate target reset
          -- Validate RCW recreation
          -- Validate release
      Running ValidateGlobalInstanceTrackerSupport...
        -- Validate weak reference creation
          -- Validate RCW recreation
          -- Validate release
        -- Validate target reset
          -- Validate RCW recreation
          -- Validate release
      Validate weak reference with aggregation.
      Running ValidateLocalInstance...
        -- Validate weak reference creation
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: True
      Actual:   False
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ComWrappersTests.Program.GetWeakReference(TestComWrappers cw)
         at ComWrappersTests.Program.ValidateNativeWeakReference(TestComWrappers cw)
         at ComWrappersTests.Program.Main(String[] doNotUse)
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\9EB00911\p
      > C:\h\w\9EB00911\w\A7D3099F\e\Interop\COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_COM._ComWrappers_WeakReference_WeakReferenceTest_WeakReferenceTest_._ComWrappers_WeakReference_WeakReferenceTest_WeakReferenceTest_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by VSadov** [comment]
It is possible. I will take a look.

**Comment by JulieLeeMSFT** [comment]
Thanks @VSadov. Assigning it to you now.

**Comment by JulieLeeMSFT** [comment]
@VSadov, this failed again on 11/13. Could you take a look?

[Link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81893&view=logs&j=34b2f53b-add1-5e74-7a39-5a11483297fc&t=d7e2c250-79b4-55e9-85ca-245fa916faea)

**Comment by VSadov** [comment]
I am sorry, I did not realize this is in a regular run and not just a one-off failure.

**Comment by VSadov** [comment]
I am able to reproduce this.

**Comment by VSadov** [comment]
It is a testcase issue. There is a race in the test. I will make a PR with a fix shortly.
