### ISSUE TITLE
TLS Handshake error: `Win32Exception: The message received was unexpected or badly formatted`

### ISSUE THREAD

**Issue by brunobritodev** [dotnet/runtime#77989]
### Description

While trying to make a Client integration with a server through Mutual TLS we got this error: 

```
System.Net.Http.HttpRequestException
  HResult=0x80131501
  Message=The SSL connection could not be established, see inner exception.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.ConnectHelper.<EstablishSslConnectionAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__96.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<CreateHttp11ConnectionAsync>d__98.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<AddHttp11ConnectionAsync>d__73.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<GetHttp11ConnectionAsync>d__75.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__83.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsyncCore>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<<Main>$>d__0.MoveNext() in D:\workspace\PixSantander\PixSantander\Program.cs:line 43

Inner Exception 1:
AuthenticationException: Authentication failed, see inner exception.

Inner Exception 2:
Win32Exception: The message received was unexpected or badly formatted.
```

Our code:

```csharp
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls13;
var certificatePath = @"<your-certificate>.pfx";
var certificatePassword = "<your-password>";

var handler = new HttpClientHandler();

handler.ClientCertificateOptions = ClientCertificateOption.Manual;
handler.ClientCertificates.Add(new X509Certificate2(certificatePath, certificatePassword));

var client = new HttpClient(handler);
client.BaseAddress = new Uri("https://trust-pix-h.santander.com.br/");

var content = new FormUrlEncodedContent(new[]
{
    new KeyValuePair<string, string>("client_id", "<your-client_id>"),
    new KeyValuePair<string, string>("client_secret", "<your-client-secret>"),
});
var result = await client.PostAsync("oauth/token?grant_type=client_credentials", content);
Console.WriteLine(await result.Content.ReadAsStringAsync());
```

If we change from Windows to run through WSL2, then works. If we do the same integration, with same parameters, but in another languages like nodejs, java or even in Postman, everything goes fine. 

One of our devs spent a week and didn't got any solution out there. The error message dont give any clue. After hours trying to figure out what's happening. Then we found that changing a Windows registry information:

```registry
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Messaging]
"MessageLimitClient"=dword:00418000
```

Then .NET start to work at Windows.

My whole point is: Maybe a better error message? A way to change tls handshake size? 

### Reproduction Steps

I can't give all information to reproduce the error, since it's needs to share sensitive information (pfx file and password). But I can share some details:
Server: https://trust-pix-h.santander.com.br/
Cipher: ECDHE-RSA-AES256-GCMA-SHA384
TLS 1.2
![image](https://user-images.githubusercontent.com/7241156/200406416-f0374c4c-9ddf-4077-be56-c83c36b87d77.png)

### Expected behavior

A better error message saying the handshake was failed because the TLS size. The actual message lead the developer to unknown places where he never finds what's really going on.

### Actual behavior

Message=The SSL connection could not be established, see inner exception.

Inner Exception 1:
AuthenticationException: Authentication failed, see inner exception.

Inner Exception 2:
Win32Exception: The message received was unexpected or badly formatted.

### Regression?

Works in Linux.

### Known Workarounds

Change windows registry:

```registry
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Messaging]
"MessageLimitClient"=dword:00418000
```

Or deploy in Linux environments.

### Configuration

* Which version of .NET is the code running on?
   .NET 2.2, 3.1, 5 and 6. Also occur in .NET Framework

* What OS and version, and what distro if applicable?
  Windows 10 Pro version 21h2

* What is the architecture (x64, x86, ARM, ARM64)?
  x64

**Comment by wfurt** [comment]
While I agree better exception would be nice the error code is coming from OS and .NET is really not involved in parsing and TLS Handshake. I'm not sure if there is much we can do.

BTW as far as repro, you can always generate new pair of keys for testing while

**Comment by karayakar** [comment]
This issue still happens in dot net 6.

Buffer="System.Exception: One or more errors occurred. (One or more errors occurred. (The SSL connection could not be established, see inner exception.)) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (The SSL connection could not be established, see inner exception.)) ---> System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.    --- End of inner exception stack trace ---    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)    --- End of inner exception stack trace ---    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at lifeboxwebapi.Services.LifeBoxApi.GetUploadStreamUrlService(LocalFile file) in XXXXXXXXXXX.cs:line 329    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at lifeboxwebapi.LifeboxController.GetStreamUrl() in XXXXX.cs:line 68    --- End of inner exception stack trace ---    at XXXXXX.GetStreamUrl() in

**Comment by wfurt** [comment]
The error come from schannel .NET use to do the TLS e.g. were are not in charge of the the error we surface what OS give use. 0x80090326 `SEC_E_ILLEGAL_MESSAGE` - it may be worth to do packet capture to see what TLS message this if failing on.

**Comment by pablokawan** [comment]
After only eight hours of banging my head trying to figure out why Banco do Brasil wasn’t accepting the digital certificate, I finally discovered it’s an issue that’s been open since 2022—and could be fixed simply by using the registry editor. Incredible, right?
