### ISSUE TITLE
Test failure: ObjectDisposedException in System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#78017]
logs https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77936-merge-f10cb260f4f742869e/normal-System.Runtime.InteropServices.JavaScript.Tests/1/console.637ff1dc.log?helixlogtype=result

```
[07:11:11] info: Starting:    System.Runtime.InteropServices.JavaScript.Tests.dll
[07:11:16] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes
[07:11:16] info: System.ObjectDisposedException : Cannot access a disposed object.
[07:11:16] info: Object name: 'value'.
[07:11:16] info:    at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTestHelper.echopromise_JSObject(JSObject value)
[07:11:16] info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes()
[07:11:16] info: --- End of stack trace from previous location ---
[07:11:18] info: Finished:    System.Runtime.InteropServices.JavaScript.Tests.dll
[07:11:18] info: 
[07:11:18] info: === TEST EXECUTION SUMMARY ===
[07:11:18] info: Total: 360, Errors: 0, Failed: 1, Skipped: 1, Time: 6.578831s
```

**Comment by pavelsavara** [comment]
duplicate https://github.com/dotnet/runtime/issues/77334
