### ISSUE TITLE
s390x: XxHash3Tests.Hash_OneShot_Expected and Hash_Streaming_Expected tests fail

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#78043]
e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=76403&view=ms.vss-test-web.build-test-results-tab&runId=1580894&resultId=130159&paneView=debug

```
Assert.Equal() Failure
Expected: 3402425285238347205
Actual:   18319083679080722056


Stack trace
   at System.IO.Hashing.Tests.XxHash3Tests.Hash_OneShot_Expected() in /_/src/libraries/System.IO.Hashing/tests/XxHash3Tests.cs:line 39
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs:line 33
```

/cc @nealef @uweigand

**Comment by uweigand** [comment]
It seems the failures start occurring once the string length gets larger than 240 bytes.  This is when the `DeriveSecretFromSeed` routine gets first involved, and on initial glance this doesn't appear to be endian safe:
```
for (int i = 0; i < SecretLengthBytes; i += sizeof(ulong) * 2)
{
    Unsafe.WriteUnaligned(destinationSecret + i, Unsafe.ReadUnaligned<ulong>(defaultSecret + i) + seed);
    Unsafe.WriteUnaligned(destinationSecret + i + 8, Unsafe.ReadUnaligned<ulong>(defaultSecret + i + 8) - seed);
}
```
The original C implementation has here:
```
        for (i=0; i < nbRounds; i++) {
            xxh_u64 lo = XXH_readLE64(kSecretPtr + 16*i)     + seed64;
            xxh_u64 hi = XXH_readLE64(kSecretPtr + 16*i + 8) - seed64;
            XXH_writeLE64((xxh_u8*)customSecret + 16*i,     lo);
            XXH_writeLE64((xxh_u8*)customSecret + 16*i + 8, hi);
       }
```
Looks like this needs byte-swaps at the loads and stores on a big-endian system.

**Comment by uweigand** [comment]
CC @stephentoub
