### ISSUE TITLE
How to identify HttpClient connect timeout errors?

### ISSUE THREAD

**Issue by fstugren** [dotnet/runtime#78070]
### Description

A while ago I opened this issue with the runtime team:

[Occasional timeouts in HttpConnectionPool.ConnectAsync](https://github.com/dotnet/runtime/issues/63706)

The idea was to find a way to identify connect timeouts (failures of the http client to establish a connection with a service) vs. "request too slow" timeouts (where the service processes the request but takes too long to respond). The reason for this approach was that we noticed (in asp.net core 3.1 and later .net 5) that sometimes there would be seemingly random connection failures with services, that would always succeed on retry. I wanted to specify a short connect timeout, different from the HttpClient request timeout (default 100 seconds) and retry on those connection errors aggressively. Unfortunately, the exceptions caught were not helpful to tell the cases apart. Eventually I came up with a hack that looks for well-known patterns in the exception callstack to differentiate between the two kinds of timeouts.

The earlier github issue mentioned that a solution would be available in .net 6.0, but initial attempts at testing revealed that the exceptions were still confusing. 

I am now in the process of migrating the services to .net 6.0, (SDK version 6.0.403) and took on this issue again to see if the connection errors are easier to detect now. However, it seems that the current exception caught in the case of a connect timeout is still awkward to detect.

- exception: TaskCanceledException ("The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.") - not true, only the shorter connection timeout had elapsed
- exception.InnerException: TimeoutException ("The operation was canceled.")
- exception.InnerException.InnerException: TaskCanceledException ("The operation was canceled.")
- exception.InnerException.InnerException.InnerException: TimeoutException ("A connection could not be established within the configured ConnectTimeout.")

This looks a bit convoluted, and I have to dig 4 levels of inner exceptions deep, but the message "**A connection could not be established within the configured ConnectTimeout.**" is pretty evocative of the connection problem; it seems better than having to dig through the callstack.

Is this the best I can do, or are there any plans to make this easier on us?

### Reproduction Steps

This can be repro'ed with any asp.net Kestrel service that uses the ServerCertificateSelector callback of the HttpsConnectionAdapterOptions and any application that uses the .net HttpClient to call an API of the service. Put a breakpoint in the server certificate selector callback and run the client, wait until the connect timeout elapses. The breakpoint would prevent the Https connection from completing. When the client times out, catch and inspect the exception.

### Expected behavior

The timeout exception should include a specialized inner exception that would indicate either by its type or by an error code property that the timeout was caused by an inability to establish a connection with the server.

### Actual behavior

See the Exception.ToString() value on the client below. Compare that with the stack trace I provided in the related github issue.

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(OperationCanceledException oce)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException(Exception exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.CancellationCleanupLogic()
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPool.<>c.<.cctor>b__87_0(Object state)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal()
   at System.Net.Sockets.SocketAsyncEventArgs.HandleCompletionPortCallbackError(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__179_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

**Comment by fstugren** [comment]
Tagging a few of the people who helped me with the original issue: @stephentoub, @ManickaP, @karelz, @wfurt, @MihaZupan 
Thanks

**Comment by ManickaP** [comment]
The extra depth and wrong message of timeout exception for connect timeout was solved in https://github.com/dotnet/runtime/pull/72274/. That's .NET 7.0 though and it's unlikely it would get ported into .NET 6.0.

**Comment by wfurt** [comment]
I think this is tricky as we can fail with `TaskCanceledException` even if we don't attempt to connect because of system load or ThreadPool contention. In that case it would surface without HTTP code even involved. 
One way to know for sure IMHO is to use the `ConnectCallback`. With that you can have complete control over transport and TLS negotiation. 
I personally feel it has other benefits as you can for example log the address, duration or whatever useful evidence you may have. It would also allow you to build retry for the transport instead of retrying whole HTTP request.

**Comment by fstugren** [comment]
Hi @wfurt - In the original issue (https://github.com/dotnet/runtime/issues/63706) you also mentioned the ConnectCallback. Looking back at my comments on that issue, I remembered I tried using the callback, but it was not addressing my problem, because the callback was not capturing the connect timeout exceptions. You opened a related github issue to cover it (https://github.com/dotnet/runtime/pull/63851). What was its outcome? (I can't quite infer the outcome from that discussion thread alone).

**Comment by ManickaP** [comment]
What might be of interest to you is https://github.com/dotnet/runtime/issues/76644 - i.e. an enum for different internal errors coming from `HttpClient`

We're still not decided whether to implement and certainly not decided on particular details. But we know that we'll do the decision this release (8.0 time frame). You can chime in on that issue to express your interest if that would help you.

**Comment by fstugren** [comment]
For now, I have cleaned up my hack (described in https://github.com/dotnet/runtime/issues/63706) that looked through the call stack string for certain function names that indicate a connect timeout, and I replaced it with a search through the hierarchy of inner exceptions for one with the message "A connection could not be established within the configured ConnectTimeout." It's a bit more maintainable in the long run, albeit identifying a kind of error by looking for some words in its exception message is not something I would recommend, except as a last resort, as it ignores possible localization issues (if the word search is based on English words) and the all-too-real possibility that a runtime library developer chooses to slightly alter the error message spelling in a future release.

Is there any example on how to use the connect callback to inspect connection errors?

**Comment by ManickaP** [comment]
We don't have such an exact example, you can check the docs for how to set the callback: https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback?view=net-6.0
The `cancellationToken` sent to the callback will be cancelled when the `ConnectTimeout` expires.

You can also look into our code and what we do by default (if no callback is defined):
https://github.com/dotnet/runtime/blob/9129083c2fc6ef32479168f0555875b54aee4dfb/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1585-L1607

Then it's fully up to you what you do about connection timeout and other errors. For example, you can supplant them with your own exception type. However, note that even your exception type will get wrapped, but it would be easier to recognize on the outside by the type of innerExcception instead of string matching.

Does this help you?

**Comment by ManickaP** [comment]
Triage: if we decide to provide a better way to identify connect timeout exception, it'll be as part of https://github.com/dotnet/runtime/issues/76644. For now, we don't have anything better than `ConnectCallback` or the hack you use.
I'll close this for now, feel free to re-open if I missed something.

**Comment by antonfirsov** [comment]
We cannot solve this as part of #76644. There is no way to include error codes in `TaskCancelledException`. One solution could be to embed an `HttpRequestException` as an `InnerException` with a specific error code, but that feels like weird hack to me since that error code wouldn't be used in normal `HttpRequestException` scenarios. I believe this is better handled as a separate ask.

IIRC this request also came up in our discussions with @mortengc in our discussions on #63159, and this basically what #30896 is about (see https://github.com/dotnet/runtime/issues/30896#issuecomment-1423118908), so I'm reopening this for a retriage.

**Comment by antonfirsov** [comment]
Triage:

We are open to solve this through our API, but it is not critical for 8.0. Note that there is a workaround available by utilizing Http telemetry and `AsyncLocal`:
https://gist.github.com/antonfirsov/3c5fe022d7a1fe36c6cac0a704b9f410

Moving to Future.
