### ISSUE TITLE
[.Net7] Json deserialization regression: The value of the '$id' metadata property '93' conflicts with an existing identifier. Path: $... | LineNumber: ... | BytePositionInLine: ....

### ISSUE THREAD

**Issue by MarianSWA** [dotnet/runtime#78132]
### Description

Just upgraded to .Net 7 and in some cases when the app deserialises previously serialised objects in .Net 6, it throws this error. It seems that indeed, back in .net 6, there was a bug causing some id's to be duplicated (usually in the same area) which maybe was fixed in 7, but there are already lots of already serialized objects which don't work any more. Is there a workaround for this? Besides manually parsing the old objects and replacing those ids? 
Thanks!

Here's the entire error:

The value of the '$id' metadata property '93' conflicts with an existing identifier. Path: $... | LineNumber: ... | BytePositionInLine: ....
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.ThrowHelper.ThrowJsonException_MetadataDuplicateIdFound(String id)
   at System.Text.Json.Serialization.PreserveReferenceResolver.AddReference(String referenceId, Object value)
   at System.Text.Json.JsonSerializer.TryHandleReferenceFromJsonElement(Utf8JsonReader& reader, ReadStack& state, JsonElement element, Object& referenceValue)
   at System.Text.Json.Serialization.Converters.ObjectConverter.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)

### Reproduction Steps

1. Serialise big object trees in .net 6
2. Upgrade to .net 7 and deserialise the same objects using the same code as before

### Expected behavior

The objects should be deserialised as before

### Actual behavior

The error shown before is thrown. Currently couldn't find any workaround for this

### Regression?

Yes, as mentioned, this worked in .net 6, although, the bug that caused duplicated ids in .net6 seems to be fixed. However, the validation behaves as that bug never happened so the existing jsons crash when deserialised.

### Known Workarounds

not so far

**Comment by eiriktsarpalis** [comment]
It would help if you could share a reproduction that produces the duplicate id's in .NET 6 and the .NET 7 code that subsequently fails to parse them. Thanks!

**Comment by MarianSWA** [comment]
Hi @eiriktsarpalis, I noticed that the bug that produces duplicates also happens in .net7, the only new thing is that now there is a new validation rule when parsing that throws the exception when duplicates ids are found. 
My app has a pretty big json object structure, and the error reproduces on aprox 20% of already saved jsons. I'll try to pinpoint the exact structure of objects that causes it and get back with more details

**Comment by eiriktsarpalis** [comment]
That would be helpful, thanks.

**Comment by MarianSWA** [comment]
So I've spent the last 2 days trying to figure out what the exact scenario is, and couldn't pinpoint it as we have a relatively complicates structure of objects, and it seems it's a very deceiving bug. 
The only detail that I can give at this point is that the bug happens when a json is saved, then re-loaded and saved again, for some reason on the second save, after a certain point in the json, misses one element in the count, gives the second next id the same one, and from that point on, the ids are having +2 offset.

@eiriktsarpalis do you know if there is a way to prevent that check (at least until the proper solution is found)
Or maybe, is there a way to downgrade only the System.Text.Json? We've spent a lot of time upgrading our solution and it would be a shame to downgrade back to .net 6 just for this (which is a big regression for us). Thanks!

**Comment by eiriktsarpalis** [comment]
> The only detail that I can give at this point is that the bug happens when a json is saved, then re-loaded and saved again, for some reason on the second save, after a certain point in the json, it misses one element in the count, gives the second next id the same one, and from that point on, the ids are having +2 offset.

I think we need something more concrete to work with. I'm not aware of any past issues where the same `$id` would emitted twice for different instances.

> do you know if there is a way to prevent that check

You could try turning off `ReferenceHandler.Preserve`. Alternatively, you could try implementing your own [`ReferenceHandler` class](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.referencehandler?view=net-7.0) that simply ignored duplicate id's.

**Comment by MarianSWA** [comment]
@eiriktsarpalis Thanks for the suggestions, ReferenceHandler to ReferenceHandler.IgnoreCycles actually works, with the condition that we go immediately after the deserialisation and manually set back the required references. Only thing that remains is to migrate the previous data to the new ReferenceHandler.IgnoreCycles. 

Do you know of an easy way to remove from the json stuff like `"$id":"1", "$values":[]`  so that they will be correctly parsed with the Preserve disabled?

Regarding the original bug, I imagine it is a case so rare, that if we can find a faster workaround, it's not worth the time fixing it. And if other people encounter it they can just follow our working workaround:
1.  Set `ReferenceHandler = ReferenceHandler.IgnoreCycles`
2. If necessary (and most likely it is, since you had ReferenceHandler.Preserve enabled) manually set the required references back - hopefully you are able to recompute them with the information you have saved in the json.
3. Migrate existing saved json files to make them parsable with ReferenceHandler.IgnoreCycles. [will update the reply when finding an easy solution for this]

Thanks again, @eiriktsarpalis, for all the help!

**Comment by eiriktsarpalis** [comment]
> Do you know of an easy way to remove from the json stuff like "$id":"1", "$values":[] so that they will be correctly parsed with the Preserve disabled?

I would probably just deserialize and reserialize the data using the new configuration.

> Regarding the original bug, I imagine it is a case so rare, that if we can find a faster workaround, it's not worth the time fixing it.

We're definitely interested, so if you're able to isolate it we'd want to take a closer look.

With that said, I'm going to close this issue. Feel free to reopen or create a new one once you have more information!
