### ISSUE TITLE
[release/6.0] CI failure in JIT.Math tests run in Browser: NugetSdkResolver failed while attempting to resolve Microsoft.Build.NoTargets/1.0.53

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#78183]
```json
{
  "ErrorMessage": "The SDK resolver \"NuGetSdkResolver\" failed while attempting to resolve the SDK "Microsoft.Build.NoTargets/1.0.53",
  "BuildRetry": false
}
```

I'm seeing this failure affecting JIT.Math tests specifically that are executed in the Browser queue in the release/6.0 branch.

Example:
- PR: https://github.com/dotnet/runtime/pull/77506/
- Queue: `Build Browser wasm Release AllSubsets_Mono_RuntimeTests`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=73538&view=logs&j=2296eecc-f5ab-523f-c15d-f45eef1bfdea&t=d328b091-66a6-5d96-5a21-3cf77f57f009&l=66

Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77506-merge-cece912146774116a5/JIT.Math/1/console.c5d1280a.log?helixlogtype=result
Callstack:
```
  Discovering: JIT.Math.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Math.XUnitWrapper (found 2 test cases)
  Starting:    JIT.Math.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/Math/Functions/Functions_r/Functions_r.sh [FAIL]
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A77108C1/w/ACD409B9/uploads/Reports/JIT.Math/Functions/Functions_r/Functions_r.output.txt
      Raw output:
      BEGIN EXECUTION
      Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242: SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Microsoft.Build.NoTargets/1.0.53". Exception: "System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at NuGet.Common.Migrations.MigrationRunner.Run()
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/A77108C1/p
      > /datadisks/disk1/work/A77108C1/w/ACD409B9/e/JIT/Math/Functions/Functions_r/Functions_r.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Math._Functions_Functions_r_Functions_r_._Functions_Functions_r_Functions_r_sh()
      Output:
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A77108C1/w/ACD409B9/uploads/Reports/JIT.Math/Functions/Functions_r/Functions_r.output.txt
        Raw output:
        BEGIN EXECUTION
        Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242: SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Microsoft.Build.NoTargets/1.0.53". Exception: "System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at NuGet.Common.Migrations.MigrationRunner.Run()
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/A77108C1/p
        > /datadisks/disk1/work/A77108C1/w/ACD409B9/e/JIT/Math/Functions/Functions_r/Functions_r.sh
  Finished:    JIT.Math.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Math.XUnitWrapper  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 7.206s
```

Another log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77506-merge-cece912146774116a5/JIT.Methodical.eE/1/console.a76c7e97.log?helixlogtype=result
Callstack:
```
  Discovering: JIT.Methodical.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Methodical.XUnitWrapper (found 113 of 695 test cases)
  Starting:    JIT.Methodical.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/Methodical/ELEMENT_TYPE_IU/_il_relu_array_merge_Target_32BIT/_il_relu_array_merge_Target_32BIT.sh [FAIL]
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A77108C1/w/B6AF091C/uploads/Reports/JIT.Methodical/ELEMENT_TYPE_IU/_il_relu_array_merge_Target_32BIT/_il_relu_array_merge_Target_32BIT.output.txt
      Raw output:
      BEGIN EXECUTION
      
      Welcome to .NET 6.0!
      ---------------------
      SDK Version: 6.0.110
      
      ----------------
      Installed an ASP.NET Core HTTPS development certificate.
      To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
      Learn about HTTPS: https://aka.ms/dotnet-https
      ----------------
      Write your first app: https://aka.ms/dotnet-hello-world
      Find out what's new: https://aka.ms/dotnet-whats-new
      Explore documentation: https://aka.ms/dotnet-docs
      Report issues and find source on GitHub: https://github.com/dotnet/core
      Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
      --------------------------------------------------------------------------------------
      Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242: SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Microsoft.Build.NoTargets/1.0.53". Exception: "System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at NuGet.Common.Migrations.MigrationRunner.Run()
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
      /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/A77108C1/p
      > /datadisks/disk1/work/A77108C1/w/B6AF091C/e/JIT/Methodical/ELEMENT_TYPE_IU/_il_relu_array_merge_Target_32BIT/_il_relu_array_merge_Target_32BIT.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Methodical._ELEMENT_TYPE_IU__il_relu_array_merge_Target_32BIT__il_relu_array_merge_Target_32BIT_._ELEMENT_TYPE_IU__il_relu_array_merge_Target_32BIT__il_relu_array_merge_Target_32BIT_sh()
      Output:
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A77108C1/w/B6AF091C/uploads/Reports/JIT.Methodical/ELEMENT_TYPE_IU/_il_relu_array_merge_Target_32BIT/_il_relu_array_merge_Target_32BIT.output.txt
        Raw output:
        BEGIN EXECUTION
        
        Welcome to .NET 6.0!
        ---------------------
        SDK Version: 6.0.110
        
        ----------------
        Installed an ASP.NET Core HTTPS development certificate.
        To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
        Learn about HTTPS: https://aka.ms/dotnet-https
        ----------------
        Write your first app: https://aka.ms/dotnet-hello-world
        Find out what's new: https://aka.ms/dotnet-whats-new
        Explore documentation: https://aka.ms/dotnet-docs
        Report issues and find source on GitHub: https://github.com/dotnet/core
        Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
        --------------------------------------------------------------------------------------
        Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242: SDK Resolver Failure: "The SDK resolver "NuGetSdkResolver" failed while attempting to resolve the SDK "Microsoft.Build.NoTargets/1.0.53". Exception: "System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at NuGet.Common.Migrations.MigrationRunner.Run()
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
        /datadisks/disk1/work/A77108C1/p/wasm-test-runner/WasmTestRunner.proj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/A77108C1/p
        > /datadisks/disk1/work/A77108C1/w/B6AF091C/e/JIT/Methodical/ELEMENT_TYPE_IU/_il_relu_array_merge_Target_32BIT/_il_relu_array_merge_Target_32BIT.sh
  Finished:    JIT.Methodical.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Methodical.XUnitWrapper  Total: 113, Errors: 0, Failed: 1, Skipped: 0, Time: 121.666s
```

**Comment by carlossanlop** [comment]
@directhex found that this was the first job where this failure showed up (thanks for investigating):
https://dev.azure.com/dnceng-public/public/_build/results?buildId=56472&view=results

**Comment by akoeplinger** [comment]
This is really another instance of the NuGet-Migrations issue: https://github.com/dotnet/runtime/issues/78183
