### ISSUE TITLE
[release/7.0] CI failure: MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters "Category does not exist"

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#78194]
Found in a release/7.0 backport PR: https://github.com/dotnet/runtime/pull/77924

- Queue: `Libraries Build windows net48 x86 Release`
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=73673&view=logs&j=bcd0b573-6223-5b97-9574-b5bb8414cd58&t=77990c5a-bddc-5d6f-6f2e-eea0cb8098e6&l=51
- Log example: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77924-merge-b08e9483be7e46f4be/System.Runtime.Caching.Tests/1/console.3631ece1.log?helixlogtype=result
- Callstack:
```
===========================================================================================================

C:\h\w\B33A09DB\w\AA200974\e>xunit.console.exe System.Runtime.Caching.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Runtime.Caching.Tests (app domain = on [no shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Caching.Tests (found 31 of 37 test cases)
  Starting:    System.Runtime.Caching.Tests (parallel test collections = on, max threads = 2)
    MonoTests.System.Runtime.Caching.MemoryCacheTest.PhysicalMemoryLimitNotSupported [SKIP]
      Condition(s) not met: "DoesNotSupportPhysicalMemoryMonitor"
    MonoTests.System.Runtime.Caching.CountersTest.Basic_Counters [FAIL]
      System.InvalidOperationException : Category does not exist.
      Stack Trace:
           at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
           at System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(String categoryName, String machineName)
        /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs(109,0): at MonoTests.System.Runtime.Caching.CountersTest.<PollCounters>d__1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/CountersTest.cs(49,0): at MonoTests.System.Runtime.Caching.CountersTest.<Basic_Counters>d__0.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  Finished:    System.Runtime.Caching.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Caching.Tests  Total: 43, Errors: 0, Failed: 1, Skipped: 1, Time: 4.626s
----- end Thu 11/10/2022 21:34:12.31 ----- exit code 1 ----------------------------------------------------------
```

```json
{
  "ErrorMessage": "Category does not exist.",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.

**Comment by radical** [comment]
Hit this on a PR for `main` - https://github.com/dotnet/runtime/pull/79007/checks?check_run_id=9808184971

**Comment by akoeplinger** [comment]
Looks like this is no longer happening, closing.
