### ISSUE TITLE
Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService() throws exception

### ISSUE THREAD

**Issue by mejas** [dotnet/runtime#78301]
I'm currently encountering an issue where calling `WindowsServiceHelpers.IsWindowsService()` throws the following exception:
```
Unhandled exception. System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder, Action`1 configure)
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder)
   at WinServiceTest.Program.CreateEnvironment(String[] args) in WinServiceTest\WinServiceTest\Program.cs:line 17
   at WinServiceTest.Program.Main(String[] args) WinServiceTest\WinServiceTest\Program.cs:line 10
   at WinServiceTest.Program.<Main>(String[] args)
```
This happens regardless if running under .NET 6 or .NET 7.

I'm including the steps to reproduce the problem below:
1. Get [WinServiceTest.zip](https://github.com/dotnet/runtime/files/9998871/WinServiceTest.zip) and extract
2. Run `dotnet tool restore`
3. Run `dotnet cake --target=run`

The application is run by an invocation using `System.Diagnostics.Process` (hence the use of the cake script) and doing this reliably reproduces the issue. Oddly, running via Visual Studio and `dotnet` does not have the issue and the application runs successfully.

Notes:
[This mono issue](https://github.com/mono/mono/issues/20732) may or may _not_ be related. The stack trace is familar, so it might be worth mentioning.

**Comment by eerhardt** [comment]
@mejas - in your repro project, it is targeting `net6.0`, but using the `7.0.0` Hosting NuGet package. Does the issue still repro if you target `net7.0` with the `7.0.0` Hosting NuGet package?

**Comment by mejas** [comment]
@eerhardt I just tried with `net7.0` and it does seem to work.
