### ISSUE TITLE
Crash in HttpListener during application teardown due to bad safehandle handling

### ISSUE THREAD

**Issue by alanmcgovern** [dotnet/runtime#78326]
### Description
I don't have a great repro for this at the moment as it only seems to occur during CI, and even there it's kinda random. It *looks* like the issue is triggered by:
1) Create a `HttpListener`
2) Call `GetContextAsync`
3) Shut down the application... some time after.

Result:
https://gist.github.com/alanmcgovern/3b5bd826400493d9d83751bcdf25107f#file-gistfile1-txt-L156-L174

This causes the application to exit with a non-zero exit code. I assume there's some mix between shutting down the appdomain/executing finalizers, and the native callback being invoked. By the time it ends up calling `Abort`, the safehandle its interacting with has already been finalized and so is invalid.

### Configuration
It's hard to tell from these logs, though it looks like this occurs under [.NET Core 3.1](https://gist.github.com/alanmcgovern/3b5bd826400493d9d83751bcdf25107f#file-gistfile1-txt-L156-L174) and *maybe* under [.NET 6.0](https://gist.github.com/alanmcgovern/3b5bd826400493d9d83751bcdf25107f#file-failure-2-L146-L183)

The log output looks like there's interleaving from several processes, so it's not super clear which framework the issue is originating in, and I haven't been able to repro it yet.

**Comment by ManickaP** [comment]
Could you share a repro case? Are you awaiting `GetContextAsync` before shutdown?

Note that `HttpListener` is in maintenance only mode, we always recommend users to migrate to Kestrel.

**Comment by ManickaP** [comment]
My hunch is that this is a user code problem. You say that adding Dispose helped, I guess you have some resources that are not properly cleaned up when they should be.

BTW, what's the error stack trace? The log you linked contains a lot of information.

> I was hopeful the stacktrace and existence of the crash would be enough to allow someone to create a better testcase.

Sorry, the burden of creating isolated repro-case is on you. As I said, this class is in maintenance mode only and we won't be putting any resources into this unless we're sure there's a bug in our code. Moreover, we strongly recommend to migrate to Kestrel serve from `HttpListener`, mainly because you get much better support with it.

Please let me know if you wish to pursue creating the isolated repro. Otherwise, I'll close this.

**Comment by ManickaP** [comment]
I'll close this now, since we don't have a repro and we suspect its a user code problem from the description. If you discover this really is `HttpListener` bug, feel free to reopen, thanks.

**Comment by alanmcgovern** [comment]
> Sorry, the burden of creating isolated repro-case is on you.

To be honest, the burden isn't on me. Like most users of opensource, I'm reporting errors and leaving it to the maintainers to decide if they wish to fix it, or invest time in identifying the problematic code which would allow a repro to more easily be made.

> BTW, what's the error stack trace? The log you linked contains a lot of information.

```
2022-11-12T15:57:38.1939225Z The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
2022-11-12T15:57:38.1940332Z Object name: 'SafeHandle'.
2022-11-12T15:57:38.1940992Z    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
2022-11-12T15:57:38.1941745Z    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
2022-11-12T15:57:38.1943414Z    at Interop.HttpApi.HttpCancelHttpRequest(SafeHandle requestQueueHandle, UInt64 requestId, IntPtr pOverlapped)
2022-11-12T15:57:38.1944405Z    at System.Net.HttpListenerContext.ForceCancelRequest(SafeHandle requestQueueHandle, UInt64 requestId)
2022-11-12T15:57:38.1945113Z    at System.Net.HttpListenerContext.Abort()
2022-11-12T15:57:38.2133655Z    at System.Net.HttpResponseStream.EndWriteCore(IAsyncResult asyncResult)
2022-11-12T15:57:38.2183806Z    at System.Net.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
2022-11-12T15:57:38.2226259Z    at System.Net.HttpListenerResponse.NonBlockingCloseCallback(IAsyncResult asyncResult)
2022-11-12T15:57:38.2227583Z    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
2022-11-12T15:57:38.2228532Z    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
2022-11-12T15:57:38.2481497Z    at System.Net.HttpResponseStreamAsyncResult.IOCompleted(HttpResponseStreamAsyncResult asyncResult, UInt32 errorCode, UInt32 numBytes)
2022-11-12T15:57:38.2676479Z    at System.Net.HttpResponseStreamAsyncResult.Callback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2022-11-12T15:57:38.2808965Z    at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2022-11-12T15:57:38.2878129Z    at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
2022-11-12T15:57:38.2897845Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-11-12T15:57:38.2929329Z --- End of stack trace from previous location ---
2022-11-12T15:57:38.2939554Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-11-12T15:57:38.2941758Z    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

\This looks like a pretty clear framework crash due to mishandling of async `Abort`s after the underlying `SafeHandle` has been finalized. There's no usercode in this stacktrace.

If you can find me the specific revision of the framework which this stacktrace corresponds to I could review the code and potentially come up with a better repro.

**Comment by alanmcgovern** [comment]
ah no, in my attempt to put together a repro that one is not actually representative.

**Comment by alanmcgovern** [comment]
For what it's worth, this is the problematic stacktrace which is *not* the same as what is created from the testcase above:

```
2022-11-12T15:57:38.1939225Z The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
2022-11-12T15:57:38.1940332Z Object name: 'SafeHandle'.
2022-11-12T15:57:38.1940992Z    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
2022-11-12T15:57:38.1941745Z    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
2022-11-12T15:57:38.1943414Z    at Interop.HttpApi.HttpCancelHttpRequest(SafeHandle requestQueueHandle, UInt64 requestId, IntPtr pOverlapped)
2022-11-12T15:57:38.1944405Z    at System.Net.HttpListenerContext.ForceCancelRequest(SafeHandle requestQueueHandle, UInt64 requestId)
2022-11-12T15:57:38.1945113Z    at System.Net.HttpListenerContext.Abort()
2022-11-12T15:57:38.2133655Z    at System.Net.HttpResponseStream.EndWriteCore(IAsyncResult asyncResult)
2022-11-12T15:57:38.2183806Z    at System.Net.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
2022-11-12T15:57:38.2226259Z    at System.Net.HttpListenerResponse.NonBlockingCloseCallback(IAsyncResult asyncResult)
2022-11-12T15:57:38.2227583Z    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
2022-11-12T15:57:38.2228532Z    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
2022-11-12T15:57:38.2481497Z    at System.Net.HttpResponseStreamAsyncResult.IOCompleted(HttpResponseStreamAsyncResult asyncResult, UInt32 errorCode, UInt32 numBytes)
2022-11-12T15:57:38.2676479Z    at System.Net.HttpResponseStreamAsyncResult.Callback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2022-11-12T15:57:38.2808965Z    at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
2022-11-12T15:57:38.2878129Z    at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
2022-11-12T15:57:38.2897845Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-11-12T15:57:38.2929329Z --- End of stack trace from previous location ---
2022-11-12T15:57:38.2939554Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2022-11-12T15:57:38.2941758Z    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

**Comment by ManickaP** [comment]
You kick off `GetContext(h);` without awaiting it, letting it run. Then you `Abort` the Listener in parallel, regard in what state your request processing is. You should first stop the loop inside the `GetContext`, await the Task and then abort the listener.
