### ISSUE TITLE
Exception Thrown when combining Polymorphic Records /w JsonNamingPolicy.SnakeCaseLower

### ISSUE THREAD

**Issue by troysteinbauer** [dotnet/runtime#78366]
### Description

While experimenting with the preview of `System.Text.Json 8.0.0`, I was unable to use `JsonPolymorphic` feature when deserializing json text formatted in the `JsonNamingPolicy.SnakeCaseLower` style. An exception is thrown.

Note, there is no exception thrown when deserializing the polymorphic records when the json text is in `CamelCase`. 

### Reproduction Steps

```C#
public class PolymorphicJsonExample
{
    [JsonPolymorphic(TypeDiscriminatorPropertyName = "Type")]
    [JsonDerivedType(typeof(TypeA), "a")]
    [JsonDerivedType(typeof(TypeB), "b")]
    private abstract record Base(string Type);
    private sealed record TypeA(string Type, int ValueA) : Base(Type);
    private sealed record TypeB(string Type, bool ValueB) : Base(Type);

    [Test]
    public void FromJsonA()
    {
        const string jsonA = """{"type":"a","value_a":1}""";
        var valueA = JsonSerializer.Deserialize<Base>(jsonA, new JsonSerializerOptions(JsonSerializerOptions.Default)
        {
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        });
        Assert.That(valueA, Is.TypeOf<TypeA>());
    }

    [Test]
    public void FromJsonB()
    {
        const string jsonB = """{"Type":"b","ValueB":true}""";
        var valueB = JsonSerializer.Deserialize<Base>(jsonB);
        Assert.That(valueB, Is.TypeOf<TypeB>());
    }
}
```

### Expected behavior

No exceptions thrown during test `PolymorphicJsonExample.FromJsonA()` and it successfully passes.

### Actual behavior

Exception thrown:
```
  Failed FromJsonA [2 ms]
  Error Message:
   System.NotSupportedException : Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Tape.Net.Tests.PolymorphicJsonExample+Base'. Path: $ | LineNumber: 0 | BytePositionInLine: 8.
  ----> System.NotSupportedException : Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Tape.Net.Tests.PolymorphicJsonExample+Base'.
  Stack Trace:
     at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type type, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Tape.Net.Tests.PolymorphicJsonExample.FromJsonA() in PolymorphicJsonExample.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--NotSupportedException
```

### Configuration

- dotnet 7.0.100
- System.Text.Json 8.0.0-alpha.1.22559.2

**Comment by eiriktsarpalis** [comment]
This is by design -- Naming policy only applies to .NET member names but does not convert string literals passed to serialization attributes. This is similar to how `JsonPropertyNameAttribute` works. The reason you're seeing this error message is because the deserializer couldn't bind to a type discriminator, so it attempted to deserialize the abstract base class instead.
