### ISSUE TITLE
Can't validate CMS signature in .NET 6/7, works in .NET 4.8

### ISSUE THREAD

**Issue by petarpetrovt** [dotnet/runtime#78453]
### Description

Validating a CMS content and signature pair throws `CryptographicException` on `.NET 6/7`, but works fine on `.NET 4.8`.
```
System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
 ---> System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Universal' class value '5', but it should have been 'Universal' class value '4'.
   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
   at System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber universalTagNumber, Nullable`1& contentLength, Int32& headerLength, ReadOnlySpan`1& contents, Int32& bytesConsumed)
   at System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetString(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, ReadOnlySpan`1& value, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnReader.TryReadPrimitiveOctetString(ReadOnlyMemory`1& contents, Nullable`1 expectedTag)
   at System.Security.Cryptography.Pkcs.SignedCms.GetContent(ReadOnlyMemory`1 wrappedContent, String contentType)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.Pkcs.SignedCms.GetContent(ReadOnlyMemory`1 wrappedContent, String contentType)
   at System.Security.Cryptography.Pkcs.SignerInfo.PrepareDigest(Boolean compatMode)
   at System.Security.Cryptography.Pkcs.SignerInfo.VerifySignature(CmsSignature signatureProcessor, X509Certificate2 certificate, Boolean compatMode)
   at System.Security.Cryptography.Pkcs.SignerInfo.Verify(X509Certificate2Collection extraStore, X509Certificate2 certificate, Boolean verifySignatureOnly)
   at System.Security.Cryptography.Pkcs.SignerInfo.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignatures(SignerInfoCollection signers, X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
   at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(Boolean verifySignatureOnly)
```

### Reproduction Steps

```csharp
using System;
using System.Security.Cryptography.Pkcs;

byte[] signatureBytes = Convert.FromBase64String("MIAGCSqGSIb3DQEHAqCAMIACAQExDTALBglghkgBZQMEAgEwgAYJKoZIhvcNAQcBoIAFAAAAAACgggSxMIIErTCCApWgAwIBAgIIYTAf3JMNLTwwDQYJKoZIhvcNAQELBQAwDzENMAsGA1UEAxMEdGVzdDAeFw0yMjExMTUxMDQ5MTdaFw0zMjExMTMxMDQ5MTdaMA8xDTALBgNVBAMTBHRlc3QwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC7dYppdQ58cgMgYvaJx/zoxb+GsSABklBotscZOJLix0RjOGuVWh725LX3Dk9+5Qfmck+bj3ONPm9Xlxr6sgePySBRVRHsRMoygT4ellCtSm+bnyExOYKumBvQfYwNjavG/f8hiJL0eDg4rq0AaLMYO64eES0ip0ginaJDPipSYisbYlRTU3ch8uquiphmT68GfyyJG3hZU3ZOM4N4ENEnP9jterhkXuAmalsWeotOxtNvBp58mCFbFCDfewX2kMtIOxuDWd8zdWcot787m2G29OMsVFcNMqE1jFqMLS/DW8bM017Mqqzc0ECZjV5LllwBNkLDVhYCj2kgXLo297NTLPFm5n45cH0x3cttKDIhIB21gxyHxgPKeTspeiyB8uMnYCzItooyrP0m+4umXvZWhxyVwfMTPwZYwi/zPQYfV84dVz3ry0eX8aUMdX8ibu0N5rIj4cnh5I/TNaDHVnkjoB46/H3xtLhul91Jgu0mYp9JoohIgRQvkWwa0ISyn1rwbDhSFFaI2LiWKNCIgb/QWfiwKMlvMJASR177VpC53/OMn1YFRm0xcm6Zhxsc8gtpSnz90HvzxuH4yR1rromVQ+v6AGN67UIhodR5W3kRlbDj3SBD733jR8FTz+/IPfeiL9PoAZrK8HqB5/qRRrXcfTlI/2DKri6qjfILdfYX9QIDAQABow0wCzAJBgNVHREEAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQBbn6WO8VFLwZo40/5VxJbw4cRCLbtU/CfWL6M5W65NAhJN9pdnITeyjUkthMWOzg5456YSO7EG2mFvzZ4Bg5x4vUU7JpdXK1cglmfUFYdlqTuewZa6F3+UsVj9weFD2tejdffQ7ou2f+T+NDxLxg5O3wy1gf5EAq474PBp8DWAAEdtMxIlhnmlDdAh1YumirLk2ZhbxTP4h8WswjNtOVlnqv4yKc8it/WOAhJonBNqJYe09J7fImjP2SjYMJasKAz1CgK/sVvCWy41PKRlxRDbqmC/ziB7GNSHzv/dfvWSypV63e/tZsT+bPu7kYXUwbT5pmX3Jxogjb0Dylg27AtCYDQo6jbYNU8kFB2j1tOyKfBPzfhu0k9j/pJK65EKjyfPPjFaIyOqPbv2qQK9vrcHuJBY/CXlMQWSp3W1ga2RiN4/3kdGqDQ3ixmN5HjhpXaNhSAya/ATfOBtUdIXKXDHc4SIdPXr/GtTBkeQM+0JV7rId8yDmQcfviNcfDdVO3RMtE6dMNBmS3LShg5nwbYx+eJf/seii7YG1/c30Q7iNAbkaszXXXSz5SaaCD3GIH+CS4WhxaKKCPmEQ4oBNMSJ/3CJpAx3uY8yU54LdUMgWITv/hPFKprnxQyNmFXCkxP9y01WcPI+WXth2QlePAiuIctkKDMQQHKD2e7EcAf2BzGCAkIwggI+AgEBMBswDzENMAsGA1UEAxMEdGVzdAIIYTAf3JMNLTwwCwYJYIZIAWUDBAIBMAsGCSqGSIb3DQEBAQSCAgAPyCgDZwhofoYw61fIMbzcjL3Mgy0f1+xvtyROnpGZyu5QUkK0JvjoWIq/DxSuotDlYUhixMc97j+L5JdGGi7yhkN1nwvHi0PDY1FjjRjYTGRqJY0HZLxHURUr/sknm0KpILu9PIZDjDpmbTe0mVu5LfZoJQYajsirwIq+zDTiYko/55Z3BoGeD9rx3peWtBhPtSEzY410KRnpidewWopMGcCilpHWBFVG78g8S0lPUGblj/hQB8BJVTeuPAqdu/SPhJC1PaVtOw3X8ZgPG9mgdmqYa8niI1CNlJtlaF9iGKK1ji4dQ4g9pmJjt+0r6x7sXq1YYo02wPRuvyGSWDx7dyF2LBuUe2c+2jCqit6ps2wrsvsskk6T5lR8S+aoSodVdYZnjx4mqVTYc1DCb0gt7+euvFfQkEwWY5dCpaqT1giTeNLejqnfNva0uzaspTihB+3Wk5O3QR0BKewgtzoe0OE8WkOjJgt05ZZCnTrJXXZxlQeq2OpXFuJXxqtaqY3gFB3ya76GklfWk2m53kgYI2RbbxmVvmsMcxPRDP8wDpFeMguxgRNXw1Ouag8S4AJL4MeE78/8uDqyJF3owJT6ufwPhNpmlomzCru216ytkRP/M286kkzMYyUefLhwnNV5hq53Dcbputs9+X+0Bkf6hNo6fCxv07BHpv3ZcqcQZwAAAAAAAA==");
byte[] contentBytes = Convert.FromBase64String("VGVzdCBkYXRhLg==");

var signedCms = new SignedCms(new ContentInfo(contentBytes), detached: true);
signedCms.Decode(signatureBytes);
signedCms.CheckSignature(verifySignatureOnly: true);
```

### Expected behavior

Don't throw on .NET 6/7 target framework.

### Actual behavior

Throws `System.Security.Cryptography.CryptographicException: ASN1 corrupted data.` exception.

**Comment by petarpetrovt** [comment]
It seems that .NET 4.8 supports `DerNull (UniversalTagNumber.Null = 5)` for OctetString but .NET 6/7 does not.

**Comment by bartonjs** [comment]
OK, with an older PKCS#7 hat on:

```
   35:d=3  hl=2 l=inf  cons:    SEQUENCE
   37:d=4  hl=2 l=   9 prim:     OBJECT            :pkcs7-data
   48:d=4  hl=2 l=inf  cons:     cont [ 0 ]
   50:d=5  hl=2 l=   0 prim:      NULL
   52:d=5  hl=2 l=   0 prim:      EOC
   54:d=4  hl=2 l=   0 prim:     EOC
```

pkcs7-data is the `Data` type from PKCS#7.  And that says


> Data content type
> 
>    The data content type is just an octet string. It shall have ASN.1
>    type Data:
> 
>    Data ::= OCTET STRING
> 
>    The data content type is intended to refer to arbitrary octet
>    strings, such as ASCII text files; the interpretation is left to the
>    application. Such strings need not have any internal structure
>    (although they may; they could even be DER encodings).


So applying the `Data` structured parser, it's still invalid making the payload invalid either under the CMS rules (`OCTET STRING` is enforced) or the PKCS#7 rules (uses the encoding of the identified content type, which in this case is still `OCTET STRING`).

It further looks like the calling code expects that detached/external content is in use, which is inconsistent with the signedData.contentInfo.content value being specified:

>         3.   The optional omission of the content field makes
>              it possible to construct "external signatures," for
>              example, without modification to or replication of the
>              content to which the signatures apply. In the case of
>              external signatures, the content being signed would be
>              omitted from the "inner" encapsulated ContentInfo value
>              included in the signed-data content type.

Note that it says `omitted`, not `NULL`.

**Comment by petarpetrovt** [comment]
> A BER-NULL in that position is invalid, as NULL is not an OCTET STRING.
> 
> ```
>       EncapsulatedContentInfo ::= SEQUENCE {
>         eContentType ContentType,
>         eContent [0] EXPLICIT OCTET STRING OPTIONAL }
> 
>       ContentType ::= OBJECT IDENTIFIER
> ```
> 
> OPTIONAL values, when not present, must be omitted... not have a BER-NULL written in their location.
> 
> What tool/library produced this file?

@bartonjs - old bouncy castle code that i am migrating

```csharp
new ContentInfo(ASN1.Cms.CmsObjectIdentifiers.Data, content: DerNull.Instance);
```
Changing this to `content: null` fixes the problem but it's weird it works in .NET Framework 4.8.

**Comment by bartonjs** [comment]
While this is a behavioral change, it only applies to documents that violate the underlying standard.  Since the only known affected documents were produced by a custom tool there's not a broad concern with existing payloads that cannot be processed.  As such, there's no real action here.
