### ISSUE TITLE
Local test run fails to analyze HardwareIntrinsics test results

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#78462]
After a local crossgen2 tests run, using `.\src\tests\run.cmd checked runcrossgen2tests`, I hit

```
Analyzing C:\dev\dotnet\runtime2\artifacts\log\JIT.HardwareIntrinsics.HardwareIntrinsics_r.testRun.xml
Analyzing C:\dev\dotnet\runtime2\artifacts\log\JIT.HardwareIntrinsics.HardwareIntrinsics_ro.testRun.xml
Traceback (most recent call last):
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1411, in <module>
    sys.exit(main(args))
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1399, in main
    parse_test_results(args, tests, assemblies)
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1196, in parse_test_results
    parse_test_results_xml_file(args, item, item_name, tests, assemblies)
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1255, in parse_test_results_xml_file
    assert tests[test_name] == None
AssertionError
```

There is a test named `JIT.HardwareIntrinsics.Arm::Abs_Vector128_Double (global::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.Abs_Vector128_Double())` in both `JIT.HardwareIntrinsics.HardwareIntrinsics_r.testRun.xml` and `JIT.HardwareIntrinsics.HardwareIntrinsics_ro.testRun.xml` which causes the assert.

Does the analysis need to disambiguate by the assembly somehow too?

cc @davidwrighton, presumably related to your recent changes here

**Comment by jakobbotsch** [comment]
Compared to the other cases (e.g. `JIT\Methodical\fp\exgen\10w5d.cs`) which also has multiple variants, the difference is the following:

JIT.Methodical.Methodical_ro.testRun.xml:
```
<test name="JIT\Methodical\fp\exgen\10w5d_cs_ro\10w5d_cs_ro.dll" type="Test_10w5d.testout1" method="TestEntryPoint" time="0.110234"  result="Pass">
```

JIT.Methodical.Methodical_do.testRun.xml:
```
<test name="JIT\Methodical\fp\exgen\10w5d_cs_do\10w5d_cs_do.dll" type="Test_10w5d.testout1" method="TestEntryPoint" time="0.126991"  result="Pass">
```

While for HW intrinsics there is no difference in the `name` attribute:
JIT.HardwareIntrinsics.HardwareIntrinsics_ro.testRun.xml:
```
<test name="global::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.Abs_Vector128_Double()" type="JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program" method="Abs_Vector128_Double" time="0.124129"  result="Pass">
```

JIT.HardwareIntrinsics.HardwareIntrinsics_r.testRun.xml:
```
<test name="global::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.Abs_Vector128_Double()" type="JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program" method="Abs_Vector128_Double" time="0.119133"  result="Pass">
```
(exact same line)
