### ISSUE TITLE
ConsoleManualTests.ReadKey_KeyChords failures

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#78467]
When I run these tests, I get an error for:
`Ctrl+Alt+B`:
```
  Error Message:
   Assert.Equal() Failure
Expected: 0x0002
Actual:   '\0'
  Stack Trace:
     at System.ConsoleManualTests.ReadKey_KeyChords(String requestedKeyChord, ConsoleKeyInfo expected) in /home/tmds/repos/runtime/src/libraries/System.Console/tests/ManualTests/ManualTests.cs:line 169
   at InvokeStub_ConsoleManualTests.ReadKey_KeyChords(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
and `Ctrl+J`:
```
  Error Message:
   Assert.Equal() Failure
Expected: 0
Actual:   Control
  Stack Trace:
     at System.ConsoleManualTests.ReadKey_KeyChords(String requestedKeyChord, ConsoleKeyInfo expected) in /home/tmds/repos/runtime/src/libraries/System.Console/tests/ManualTests/ManualTests.cs:line 168
   at InvokeStub_ConsoleManualTests.ReadKey_KeyChords(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

cc @adamsitnik

**Comment by tmds** [comment]
@adamsitnik are these failures due to the Console improvements you've made? Should the tests be updated to validate the new behavior?
