### ISSUE TITLE
`HttpRequestException`: Destination is too short. (Parameter 'destination')

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/runtime#78516]

**Comment by ManickaP** [comment]
Triage: Looks like `QPackDecoder` error where we attempt to copy to smaller buffer than necessary. We should fix this for 8.0. 

It would be nice to get an isolated repro though. I assume this could be reproduced without reverse proxy, blazor app etc.

**Comment by BrunoBlanes** [comment]
I tried reproducing it without the blazor app, by serving just the static `blazor.webassembly.js` file, to no success.
I don't quite understand if it needs to have the entire flow of requests made for it to break.
Also I couldn't find a way to force Edge to use HTTP3, so I still had to use a Proxy.

**Comment by ManickaP** [comment]
> Also I couldn't find a way to force Edge to use HTTP3, so I still had to use a Proxy.

Might be because browsers don't like self-signed certs in QUIC (TLS is part of QUIC itself and the browser cannot let you manually accept the seemingly insecure cert as that's done one layer bellow).

What could work, is having `HttpClient` directly requesting all those files from the server. In other words, instead of browser -> proxy -> server, having `HttpClient` -> server. The less moving parts in the repro, the easier to root cause and fix.

**Comment by wfurt** [comment]
It very likely depends on actual value and sequence. If the flow or headers are different you may not trigger it. 
You may also try to stop through in Debugger and check  the `DecodeInternal`. At least in VS it should fetch correct sources for you automatically.

**Comment by BrunoBlanes** [comment]
I was able to reproduce the error without the need of a proxy, with the help of the default Blazor Hosted Template and the following code:

```c#
using var httpClient = new HttpClient();
await GetFileAsync("/index.html");
await Task.WhenAll(new List<Task>
{
    GetFileAsync("/css/bootstrap/bootstrap.min.css"),
    GetFileAsync("/css/app.css"),
    GetFileAsync("/BlazorApp4.Client.styles.css"),
    GetFileAsync("/_framework/blazor.webassembly.js")
});

async Task GetFileAsync(string relativeUri)
{
    Console.WriteLine("Requesting file...");
    var request = new HttpRequestMessage
    {
	Method = HttpMethod.Get,
	RequestUri = new Uri(new Uri("https://localhost:5001"), relativeUri),
	Version = new Version(3, 0),
	VersionPolicy = HttpVersionPolicy.RequestVersionExact,
    };

    request.Headers.Add("accept", new[]
    {
	"text/html",
	"application/xhtml+xml",
	"application/xml;q=0.9",
	"image/webp",
	"image/apng",
	"*/*;q=0.8",
	"application/signed-exchange;v=b3;q=0.9"
    });
    request.Headers.Add("accept-encoding", new[] { "gzip", "defalte", "br" });
    request.Headers.Add("accept-language", new[] { "en-US", "en;q=0.9", "pt;q=0.8", "es;q=0.7" });
    request.Headers.Add("cache-control", "no-cache");
    request.Headers.Add("pragma", "no-cache");
    request.Headers.Add("sec-ch-ua", new[]
    {
	@"""Not_A Brand"";v=""99""",
	@"""Microsoft Edge"";v=""109""",
	@"""Chromium"";v=""109"""
    });
    request.Headers.Add("sec-ch-ua-mobile", "?0");
    request.Headers.Add("sec-ch-ua-platform", @"""Windows""");
    request.Headers.Add("sec-fetch-dest", "document");
    request.Headers.Add("sec-fetch-mode", "navigate");
    request.Headers.Add("sec-fetch-site", "none");
    request.Headers.Add("sec-fetch-user", "?1");
    request.Headers.Add("upgrade-insecure-requests", "1");
    request.Headers.Add("user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.0.0");

    HttpResponseMessage response = (await httpClient.SendAsync(
	request,
	new CancellationTokenSource().Token))
	.EnsureSuccessStatusCode();
    Console.WriteLine($"File {relativeUri.Split("/")[^1]} received with length {(await response.Content.ReadAsStringAsync()).Length}.");
}
```

It always breaks on the `js` file. Also, the headers are what did it for me, without them I couldn't reproduce the errors (I just basically copied them from my browser).

**Comment by BrunoBlanes** [comment]
> You may also try to stop through in Debugger and check the `DecodeInternal`. At least in VS it should fetch correct sources for you automatically.

I did, and from what I could gather it happens with the `"accept-encoding"` header and only with the `"gzip"` value, so essentially this is the only line of code needed for it to crash:
```c#
    request.Headers.Add("accept-encoding", new[] { "gzip" });
```

The exception is thrown at `System.ReadOnlySpan<T>.CopyTo(Span<T> destination)` method once it gets called by `QPackDecoder`:

```c#
// If a header range was set, but the value was not in the data, then copy the range
// to the name buffer. Must copy because the data will be replaced and the range
// will no longer be valid.
if (_headerNameRange != null)
{
    EnsureStringCapacity(ref _headerNameOctets, _stringLength, existingLength: 0);
    _headerName = _headerNameOctets;

    ReadOnlySpan<byte> headerBytes = data.Slice(_headerNameRange.GetValueOrDefault().start, _headerNameRange.GetValueOrDefault().length);
    headerBytes.CopyTo(_headerName);            
    _headerNameLength = headerBytes.Length;            
    _headerNameRange = null;
}
```

However I am getting a lot of errors on VS telling me that it could not obtain the value of the local variable, so I wasn't able to learn much about the spans themselves.

**Comment by BrunoBlanes** [comment]
After messing around with my breakpoints, and if I am not mistaken, `_headerNameOctets` is of length `16`, while `headerBytes` gets created with length `18` which would explain the exception being thrown.

**Comment by BrunoBlanes** [comment]
I got VS to decompile the source code and here's what I could find:

`DecodeInternal` is crashing on these last 25 bytes of header data from a sized 64 buffer:

```b
55 11 98 108 97 122 111 114 45 101 110 118 105 114 111 110 109 101 110 116 11 68 101 118 101
```
```ascii
7blazor-environmentDeve
```
Comprised above is one header name and the first four bytes of its value, which would eventually become
`"blazor-environment":"Development"`

Under the `QPackeDecoder.ParseCompressedHeaders` method this is falling into the `Literal Header Field Without Name Reference` case, where `BeginTryDecode` does not succeed and so `ParseHeaderNameLength` is called:
```c#
case 2:
    _Huffman = (b & LiteralHeaderFieldWithoutNameReferenceHuffmanMask) != 0;
    prefixInt = b & LiteralHeaderFieldWithoutNameReferencePrefixMask;

    if (_integerDecoder.BeginTryDecode((byte)prefixInt, LiteralHeaderFieldWithoutNameReferencePrefix, out intResult))
    {
	if (intResult == 0)
	{
		throw new QPackDecodingException(SR.Format(SR.net_http_invalid_header_name, ""));
	}
	OnStringLength(intResult, State.HeaderName);
	ParseHeaderName(data, ref currentIndex, handler);
    }
    else
    {
	_state = State.HeaderNameLength;
	ParseHeaderNameLength(data, ref currentIndex, handler);
    }
    break;
```

Here, at `ParseHeaderNameLength`, we learn that the header name length is `18` bytes long and define `_headerNameRange` accordingly.

Then, at `ParseHeaderValueLength` we learn that the header value length is to be `11` bytes long.

Once at `ParseHeaderValue` we get the confirmation that only `4` bytes of the value string are currently available. `_stringOctets` is currently `32` bytes long, so no change is made to accommodate the remaining data that is to come.

Now that we've gone through the entire buffer, we fall into the following condition:
```c#
if (_headerNameRange.HasValue)
{
    EnsureStringCapacity(ref _headerNameOctets, _stringLength, 0);
    _headerName = _headerNameOctets;
    ReadOnlySpan<byte> headerBytes = data.Slice(_headerNameRange.GetValueOrDefault().start, _headerNameRange.GetValueOrDefault().length);
    headerBytes.CopyTo(_headerName);
    _headerNameLength = headerBytes.Length;
    _headerNameRange = null;
}
```
We've last filled `_stringLength` with the header value length value of `11`, hence now `_headerNameOctets` will be initialized to a `16` bytes long array.

`_headerNameRange` was initialized to be the start of the header name and its length of `18` bytes and therefore we are now trying to copy `18` bytes of data into a `16` bytes array.

I haven't had the time to dive deep into HTTP3 header encoding, so I am not able to pin-point the issue here. However, I find odd that we don't create the header name given that we already know its value, instead we created a "range buffer". Had this range not be initialized (or be set back to `null` at some point), this bug would not be present.

**Comment by BrunoBlanes** [comment]
> I did, and from what I could gather it happens with the `"accept-encoding"` header and only with the `"gzip"` value, so essentially this is the only line of code needed for it to crash:
> 
> ```cs
>     request.Headers.Add("accept-encoding", new[] { "gzip" });
> ```

Now that I've dug a little deeper, I assume that adding this header to the request message is just a coincidence that makes the server add its matching `"content-encoding":"gzip"` header to the response for the `64` bytes buffer to be chopped in the perfect way for an unpredicted event.

**Comment by BrunoBlanes** [comment]
Sorry for the lengthy explanation, it is much more for my understanding and sake of mind than anything else.

**Comment by ManickaP** [comment]
@BrunoBlanes please don't apologize, this is great investigation. You gave us stable repro and even dived into investigating this, that will help us a lot! Thank you!

**Comment by BrunoBlanes** [comment]
Little update, I decided I am in too deep and began trying to fix it myself, as a learning experience since I haven't messed with the .NET source code before. As such, I came up with the following test for this scenario:
```c#
using System.Linq;
using System.Net.Http.QPack;
using System.Net.Http.Unit.Tests.HPack;
using System.Text;
using Xunit;

namespace System.Net.Http.Unit.Tests.QPack
{
    public class QPackDecoderTest
    {
        private const int MaxHeaderFieldSize = 8190;

        // 4.5.6 - Literal Field Without Name Reference - (literal-header-field)
        private static readonly byte[] _literalFieldWithoutNameReference = new byte[] { 0x37, 0x0d, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x2d, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2d, 0x66, 0x69, 0x65, 0x6c, 0x64 };

        private const string _headerNameString = "literal-header-field";
        private const string _headerValueString = "should-not-break";

        private static readonly byte[] _headerValueBytes = Encoding.ASCII.GetBytes(_headerValueString);

        private static readonly byte[] _headerValue = new byte[] { (byte)_headerValueBytes.Length }
            .Concat(_headerValueBytes)
            .ToArray();

        private readonly QPackDecoder _decoder;
        private readonly TestHttpHeadersHandler _handler = new TestHttpHeadersHandler();

        public QPackDecoderTest()
        {
            _decoder = new QPackDecoder(MaxHeaderFieldSize);
        }

        [Fact]
        public void DecodesLiteralField_WithoutNameReferece()
        {
            // The key take away here is that the header name length should be bigger than 16 bytes
            // and the header value length less than or equal to 16 bytes and they cannot all be
            // read at once, they must be broken into separate buffers
            byte[] encoded = _literalFieldWithoutNameReference
                .Concat(_headerValue)
                .ToArray();

            _decoder.Decode(new byte[] { 0, 0 }, endHeaders: false, handler: _handler);
            _decoder.Decode(encoded[..^7], endHeaders: false, handler: _handler);
            _decoder.Decode(encoded[^8..], endHeaders: true, handler: _handler);

            Assert.Equal(1, _handler.DecodedHeaders.Count);
            Assert.Equal(_headerNameString, _handler.DecodedHeaders.Keys.First());
            Assert.Equal(_headerValueString, _handler.DecodedHeaders.Values.First());
        }
    }
}
```

**Comment by kapryeong** [comment]
The same error occurs even when PUT is executed several times in the console program.

```
  HttpClient client = new()
  {
      DefaultRequestVersion = HttpVersion.Version30,
      DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact
  };
//....//
 foreach (AasAndSubmodels item in list)
 {
      await _httpClient.PutAsJsonAsync($"shells/{item.AAS.IdShort}", item.AAS);
 }
```

```
Unhandled exception: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.ArgumentException: Destination is too short. (Parameter 'destination')
   at System.Net.Http.QPack.QPackDecoder.DecodeInternal(ReadOnlySpan`1 data, IHttpStreamHeadersHandler handler)
   at System.Net.Http.Http3RequestStream.ReadHeadersAsync(Int64 headersLength, CancellationToken cancellationToken)
   at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
```

**Comment by karelz** [comment]
Fixed in 7.0.7 in PR #85977 and PR https://github.com/dotnet/aspnetcore/pull/47949 and in 6.0.18 in PR #85976 and PR https://github.com/dotnet/aspnetcore/pull/47950.
