### ISSUE TITLE
 runtime-coreclr superpmi-collect failed with System.Net.Sockets.SocketException (55): No buffer space available

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#78541]
## Build Information
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2044300
Build error leg or test failing: coreclr Pri1 Runtime Tests Run OSX arm64 checked
Pull request: https://github.com/dotnet/runtime/pull/78297

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "System.Net.Sockets.SocketException (55): No buffer space available",
  "BuildRetry": false
}
```
cc @dotnet/jit-contrib. 

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[2227823](https://dev.azure.com/dnceng/internal/_build/results?buildId=2227823)|dotnet-runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2227823/logs/2250)||
|[2226350](https://dev.azure.com/dnceng/internal/_build/results?buildId=2226350)|dotnet-runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2226350/logs/2330)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|2|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.

**Comment by JulieLeeMSFT** [comment]
[Link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2044300&view=logs&j=765fd5e9-e47f-5cb0-4cbf-499eaaaee93e&t=95cab8ea-58dc-5bcb-a161-6de341c6b8ff)

```
2022-11-14T06:22:14.5104150Z MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
2022-11-14T06:22:14.5109060Z MSBUILD : error MSB4166: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/MSBuild_pid-62011_23413a2766fc484ab1bee3f5452c9618.failure.txt:
2022-11-14T06:22:14.5111490Z MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 62011:
2022-11-14T06:22:14.5114230Z MSBUILD : error MSB4166: =====================
2022-11-14T06:22:14.5117660Z MSBUILD : error MSB4166: 11/14/2022 6:22:14 AM
2022-11-14T06:22:14.5118430Z MSBUILD : error MSB4166: System.IO.IOException: No buffer space available
2022-11-14T06:22:14.5119820Z MSBUILD : error MSB4166:  ---> System.Net.Sockets.SocketException (55): No buffer space available
2022-11-14T06:22:14.5121250Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
2022-11-14T06:22:14.5122960Z MSBUILD : error MSB4166:    --- End of inner exception stack trace ---
2022-11-14T06:22:14.5123760Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
2022-11-14T06:22:14.5125500Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
2022-11-14T06:22:14.5126660Z MSBUILD : error MSB4166: ===================
2022-11-14T06:22:14.5127100Z MSBUILD : error MSB4166: 
2022-11-14T06:22:14.5127600Z MSBUILD : error MSB4166: 
2022-11-14T06:22:14.5133800Z ##[error]Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
```

**Comment by wfurt** [comment]
as far as I can tell this comes from msbuild, not from tests, right?

**Comment by wfurt** [comment]
There is no repro and in general this is not actionable. There are many articles on internet about his and it seems environmental e.g. disperse after reboot. It seems to be related to state of the machine e.g. large number of connection or lack of kernel resources. So this specific failures looks like infrastructure to me. We can investigate if there is way how to reproduce it.
