### ISSUE TITLE
Multi-threading bugs in System.IO.Packaging

### ISSUE THREAD

**Issue by lklein53** [dotnet/runtime#78547]
### Description

Hi together,

I think the bug reported in https://github.com/dotnet/runtime/issues/43012 is not fully fixed.
I can't reproduce the exact same issue, but instead a 

> System.Xml.XmlException Unrecognized root element in Core Properties part. Line 1, position 57.

is sometimes thrown using the reproducer from the original ticket.

Thanks for having a look

### Reproduction Steps

The reproducer from the original bug report triggers the exception for me
```
class Program
{
	static void Main(string[] args)
	{
		Parallel.For(1, Environment.ProcessorCount, (i) => ReadPackage());
	}

	private static void ReadPackage()
	{
		using var ms = File.OpenRead(@"package.xlsx"); // Any valid Package, e.g. Excel .xlsx

		using var package = Package.Open(ms, FileMode.Open, FileAccess.Read);

		// Trigger parsing some XML inside the package.
		// Note: this is just 1 of the places in Package where XML parsing is done.
		_ = package.PackageProperties;
	}
}
```

### Expected behavior

No exception to be thrown.

### Actual behavior

```
System.Xml.XmlException
Unrecognized root element in Core Properties part. Line 1, position 57.
   at System.IO.Packaging.PartBasedPackageProperties.ParseCorePropertyPart(PackagePart part)
   at System.IO.Packaging.PartBasedPackageProperties.ReadPropertyValuesFromPackage()
   at System.IO.Packaging.PartBasedPackageProperties..ctor(Package package)
   at System.IO.Packaging.Package.get_PackageProperties()
```
is thrown

### Configuration

Which version of .NET is the code running on? Have repeated the issue in .net6.0 (Microsoft.AspNetCore.App 6.0.11)
What OS and version, and what distro if applicable? Linux, Ubuntu 22.04
What is the architecture (x64, x86, ARM, ARM64)? x64
Do you know whether it is specific to that configuration? I don't believe it to be specific to the configuration.

**Comment by lklein53** [comment]
Sorry I missed that the wrong version of the packaging lib was referenced
