### ISSUE TITLE
AccessViolationException in System.Security.Cryptography.X509Certificates tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#78560]
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Interop+Crypt32.<CertGetCertificateContextProperty>g____PInvoke|33_0(IntPtr, CertContextPropId, Byte*, Int32*)
--------------------------------
   at Interop+Crypt32.CertGetCertificateContextProperty(Microsoft.Win32.SafeHandles.SafeCertContextHandle, CertContextPropId, Byte[], Int32 ByRef)
   at Microsoft.Win32.SafeHandles.SafeCertContextHandle.get_HasPersistedPrivateKey()
   at System.Security.Cryptography.X509Certificates.CertificatePal.TryAcquireCngPrivateKey(Microsoft.Win32.SafeHandles.SafeCertContextHandle, System.Security.Cryptography.CngKeyHandleOpenOptions ByRef)
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetPrivateKey[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`2<System.Security.Cryptography.CspParameters,System.__Canon>, System.Func`2<System.Security.Cryptography.CngKey,System.__Canon>)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=87409
Build error leg or test failing: System.Net.Security.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/78534

## Error Message

```json
{
  "ErrorMessage": "System.Security.Cryptography.X509Certificates.CertificatePal",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[87409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=87409)|dotnet/runtime|[System.Net.Security.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=87409&view=ms.vss-test-web.build-test-results-tab&runId=1832528&resultId=199680)|dotnet/runtime#78534|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by vcsjones** [comment]
I can reproduce it racing `GetRSAPrivateKey` and `Dispose`. It's a little tricky to hit but this did it in a few minutes:

```C#
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

using RSA rsa = RSA.Create();
CertificateRequest req = new CertificateRequest("CN=potato", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
using X509Certificate2 cert = req.CreateSelfSigned(DateTimeOffset.Now, DateTimeOffset.Now);

while (true)
{
    X509Certificate2 w = new X509Certificate2(cert.RawDataMemory.Span);
    X509Certificate2 y = w.CopyWithPrivateKey(rsa);
    w.Dispose();
    Thread t1 = new Thread(cert => {
        Thread.Sleep(Random.Shared.Next(0, 20));
        X509Certificate2 c = (X509Certificate2)cert!;
        c.Dispose();
        GC.Collect();
    });
    Thread t2 = new Thread(cert => {
        Thread.Sleep(Random.Shared.Next(0, 20));
        X509Certificate2 c = (X509Certificate2)cert!;

        try
        {
            c.GetRSAPrivateKey()!.ExportParameters(false);
        }
        catch
        {
            // don't care about managed exceptions.
        }
    });
    t1.Start(y);
    t2.Start(y);
    t1.Join();
    t2.Join();
}
```

Gave me:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Interop+Crypt32.<CertGetCertificateContextProperty>g____PInvoke|33_0(IntPtr, CertContextPropId, Byte*, Int32*)
   at Interop+Crypt32.CertGetCertificateContextProperty(Microsoft.Win32.SafeHandles.SafeCertContextHandle, CertContextPropId, Byte[], Int32 ByRef)
   at System.Security.Cryptography.X509Certificates.CertificatePal.TryAcquireCngPrivateKey(Microsoft.Win32.SafeHandles.SafeCertContextHandle, System.Security.Cryptography.CngKeyHandleOpenOptions ByRef)
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetPrivateKey[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`2<System.Security.Cryptography.CspParameters,System.__Canon>, System.Func`2<System.Security.Cryptography.CngKey,System.__Canon>)
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Security.Cryptography.X509Certificates.X509Certificate2, System.Predicate`1<System.Security.Cryptography.X509Certificates.X509Certificate2>)
   at Program+<>c.<<Main>$>b__0_1(System.Object)
```

**Comment by vcsjones** [comment]
This one is somewhat perplexing since, I would have though, the `SafeHandle` would have helped us here.

**Comment by bartonjs** [comment]
Probably means something in the GetPrivateKey path is doing DangerousGetHandle() and has faith it'll work, when it needed to DangerousAddRef/DangerousRelease around the operation.

**Comment by vcsjones** [comment]
I'll try to track it down it over over the weekend as soon as I finish the RNG API additions.

**Comment by vcsjones** [comment]
So, it looks like `CertificatePal.Windows.cs` just has a wrong approach to working with safe handles when multithreading `Dispose` comes in to play. The issue, for this particular example the problem is here:

https://github.com/dotnet/runtime/blob/6519ec2b64bab3dd2d4a07dbfab2a5ac6542f366/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificatePal.Windows.cs#L478-L483

The `GC.KeepAlive(_certContext)` is good to keep the GC from cleaning up the safe handle, but not someone just explicitly disposing it. When I wrap that method in a `DangerousAddRef` and `DangerousRelease`, then I can't reproduce the problem anymore.

However, this class makes considerable use of `GC.KeepAlive`, but don't account for another thread disposing of the underlying CERT_CONTEXT. `KeyAlgorithm` presumably suffers from the same problem:

https://github.com/dotnet/runtime/blob/6519ec2b64bab3dd2d4a07dbfab2a5ac6542f366/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificatePal.Windows.cs#L83-L85

What if another thread calls `Dispose` between lines 83 and 84?

The `CertContext` property in general just looks super risky to use, since it's basically just doing `DangerousGetHandle` but hiding it.

I'll open a PR to fix this eventually, but I think it makes sense to look at this bit more holistically than fix just this one instance of it.

**Comment by vcsjones** [comment]
Note for myself: adding and removing from the store has the same problem.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Interop+Crypt32.<CertFreeCertificateContext>g____PInvoke|41_0(IntPtr)
--------------------------------
   at Interop+Crypt32.CertFreeCertificateContext(IntPtr)
   at Microsoft.Win32.SafeHandles.SafeCertContextHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean)
   at System.Runtime.InteropServices.SafeHandle.Dispose()
   at System.Security.Cryptography.X509Certificates.StorePal.Add(System.Security.Cryptography.X509Certificates.ICertificatePal)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(System.Security.Cryptography.X509Certificates.X509Certificate2)
   at MemoryCertificateStore.Add(System.Security.Cryptography.X509Certificates.X509Certificate2)
   at Program+<>c__DisplayClass0_0.<<Main>$>b__0(System.Object)
```
