### ISSUE TITLE
Test failure JIT.HardwareIntrinsics.General._Vector256.VectorUnaryOpTest__ConvertToDoubleUInt64.ValidateResult(UInt64[], Double[], System.String)

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#78576]
Run: [runtime-coreclr superpmi-collect 20221113.3](https://dev.azure.com/dnceng/internal/_build/results?buildId=2044300) 

Failed test: coreclr Pri1 Runtime Tests Run windows x64 checked

Error message:
```
06:16:08.575 Running test: global::JIT.HardwareIntrinsics.General._Vector256.Program.ConvertToDoubleUInt64()
Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Process terminated. Temporary instrumentation to diagnose https://github.com/dotnet/runtime/issues/76280
   at System.Environment.FailFast(System.String)
   at JIT.HardwareIntrinsics.General._Vector256.VectorUnaryOpTest__ConvertToDoubleUInt64.ValidateResult(UInt64[], Double[], System.String)
   at JIT.HardwareIntrinsics.General._Vector256.VectorUnaryOpTest__ConvertToDoubleUInt64.ValidateResult(System.Runtime.Intrinsics.Vector256`1<UInt64>, Void*, System.String)
   at JIT.HardwareIntrinsics.General._Vector256.VectorUnaryOpTest__ConvertToDoubleUInt64.RunClassLclFldScenario()
   at JIT.HardwareIntrinsics.General._Vector256.Program.ConvertToDoubleUInt64()
   at Program.<<Main>$>g__TestExecutor64|0_63(<>c__DisplayClass0_0 ByRef)
   at Program.<Main>$(System.String[])
Expected: 100
Actual: -2146232797
END EXECUTION - FAILED
FAILED
```

```json
{ 
    "ErrorMessage":"JIT.HardwareIntrinsics\\General\\Vector256\\Vector256_",
    "BuildRetry": false
} 
```

**Comment by JulieLeeMSFT** [comment]
cc @BruceForstall @dotnet/jit-contrib.

**Comment by BruceForstall** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/76280; closing

**Comment by jkotas** [comment]
The superpmi collection pipelines should be switched to the new machine pools to fix this. We should keep this open to track that.
