### ISSUE TITLE
Test failure System.Diagnostics.Tests.EventLogReaderTests.CastToEventLogRecord_NotNull

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78618]
Run:

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open

- System.Diagnostics.Tests.EventLogReaderTests.CastToEventLogRecord_NotNull
- System.Diagnostics.Tests.EventLogSessionTests.ExportLogAndMessages_NullPath_Throws(usingDefaultCtor: False)
- System.Diagnostics.Tests.EventLogSessionTests.ExportLogAndMessages_NullPath_Throws(usingDefaultCtor: True)
- System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: False)
- System.Diagnostics.Tests.ProviderMetadataTests.ProviderNameTests(noProviderName: True)
- System.Diagnostics.Tests.EventLogReaderTests.LogStatus
- System.Diagnostics.Tests.EventLogReaderTests.ReadEventPsh(logName: \"Microsoft-Windows-PowerShell/Operational\", useQuery: True)
- System.Diagnostics.Tests.EventLogReaderTests.ReadEventPsh(logName: \"Microsoft-Windows-PowerShell/Operational\", useQuery: False)
- System.Diagnostics.Tests.EventLogReaderTests.BatchSize_OtherCtor
- System.Diagnostics.Tests.EventLogReaderTests.Seek
- System.Diagnostics.Tests.EventLogReaderTests.CancelReading
- System.Diagnostics.Tests.EventLogReaderTests.ReadEvent(logName: \"Application\", useQuery: True)
- System.Diagnostics.Tests.EventLogReaderTests.ReadEvent(logName: \"Application\", useQuery: False)
```
**Error message:**
```
System.Diagnostics.Eventing.Reader.EventLogException : The RPC server is unavailable.


Stack trace
   at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogException.cs:line 47
   at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtQuery(EventLogHandle session, String path, String query, Int32 flags) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/NativeWrapper.cs:line 63
   at System.Diagnostics.Eventing.Reader.EventLogReader..ctor(EventLogQuery eventQuery, EventBookmark bookmark) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/EventLogReader.cs:line 98
   at System.Diagnostics.Tests.Helpers.GetBookmark(String log, PathType pathType) in /_/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs:line 74
   at System.Diagnostics.Tests.EventLogReaderTests.CastToEventLogRecord_NotNull() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/EventLogReaderTests.cs:line 87
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by ericstj** [comment]
> System.Diagnostics.Eventing.Reader.EventLogException : The RPC server is unavailable.

This indicates that the windows `EventLog` service was not running on the test machine.  If this is hit again, the machine should be checked using the following.
```
C:\>sc query EventLog

SERVICE_NAME: EventLog
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
It's possible that the service was stopped or misconfigured on the test machine.

If we happen to hit this regularly we might need to look at fixing the implementation of https://github.com/dotnet/runtime/blob/da30389d2c0c3e5cad98f82e9bee0c9e8cfd78eb/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs#L18.

cc @dotnet/area-system-diagnostics-eventlog
