### ISSUE TITLE
Test failure System.Diagnostics.Tests.ProviderMetadataTests.SourceDoesNotExist_Throws

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78617]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20221119.1](url)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open

- System.Diagnostics.Tests.ProviderMetadataTests.SourceDoesNotExist_Throws
- System.Diagnostics.Tests.EventLogSessionTests.ClearLog_LogNameNullEmptyOrNotExist_Throws
- System.Diagnostics.Tests.EventLogSessionTests.ExportLog_InvalidInputCombinations_Throws(usingDefaultCtor: False)
- System.Diagnostics.Tests.EventLogSessionTests.ExportLog_InvalidInputCombinations_Throws(usingDefaultCtor: True)
- System.Diagnostics.Tests.EventLogSessionTests.EventLogExceptionShouldHaveHResultSet
```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.Diagnostics.Eventing.Reader.EventLogNotFoundException)
Actual:   typeof(System.Diagnostics.Eventing.Reader.EventLogException): The RPC server is unavailable.
---- System.Diagnostics.Eventing.Reader.EventLogException : The RPC server is unavailable.


Stack trace
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName, EventLogSession session, CultureInfo targetCultureInfo, String logFilePath) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 66
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 47
   at System.Diagnostics.Tests.ProviderMetadataTests.<>c.<SourceDoesNotExist_Throws>b__0_0() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 19
----- Inner Stack Trace -----
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName, EventLogSession session, CultureInfo targetCultureInfo, String logFilePath) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 66
   at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName) in /_/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/Reader/ProviderMetadata.cs:line 47
   at System.Diagnostics.Tests.ProviderMetadataTests.<>c.<SourceDoesNotExist_Throws>b__0_0() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 19
```

**Comment by v-wenyuxu** [comment]
Fail again in: [runtime-coreclr libraries-jitstress 20221211.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=109061&view=ms.vss-test-web.build-test-results-tab&runId=2326302&resultId=142605&paneView=debug)

Failed test:
```
net8.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

- System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws

net8.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open

- System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws
```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Net.Sockets.SocketException): No such host is known.
---- System.Net.Sockets.SocketException : No such host is known.


Stack trace
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 220
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 192
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 220
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped) in /_/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs:line 192
--- End of stack trace from previous location ---
```

**Comment by danmoseley** [comment]
@v-wenyuxu Those latest failures seem different.

**Comment by ericstj** [comment]
> System.Diagnostics.Eventing.Reader.EventLogException : The RPC server is unavailable.

This indicates that the windows `EventLog` service was not running on the test machine.  If this is hit again, the machine should be checked using the following.
```
C:\>sc query EventLog

SERVICE_NAME: EventLog
        TYPE               : 30  WIN32
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
It's possible that the service was stopped or misconfigured on the test machine.

If we happen to hit this regularly we might need to look at fixing the implementation of https://github.com/dotnet/runtime/blob/da30389d2c0c3e5cad98f82e9bee0c9e8cfd78eb/src/libraries/System.Diagnostics.EventLog/tests/Helpers.cs#L18.

cc @dotnet/area-system-diagnostics-eventlog

**Comment by danmoseley** [comment]
Or just copy what I did for the EFS service --

https://github.com/dotnet/runtime/blob/3747edb1812106f0b88a42b724c3e44b69dc79c4/src/libraries/System.IO.FileSystem/tests/File/EncryptDecrypt.Windows.cs#L17-L33
