### ISSUE TITLE
Test failure JIT/Directed/nullabletypes/isinst_do/isinst_do.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78623]
Run: [runtime-coreclr ilasm 20221119.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867338&resultId=102092&paneView=debug)

Failed test:
```
coreclr Linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open

- JIT/Directed/nullabletypes/isinst_do/isinst_do.sh
- JIT/Directed/nullabletypes/isinst2_do/isinst2_do.sh
- JIT/jit64/regress/vsw/524070/test2/test2.sh
- JIT/Directed/nullabletypes/Desktop/nullcomparaison_do/nullcomparaison_do.sh
- JIT/jit64/valuetypes/nullable/box-unbox/value/box-unbox-value033/box-unbox-value033.sh
... ...
```
**Error message:**
```
isinst2_do.dasm.il(104179) : error : Undeclared identifier val
isinst2_do.dasm.il(104280) : error : Undeclared identifier val
isinst2_do.dasm.il(104394) : error : Undeclared identifier val
isinst2_do.dasm.il(104407) : error : Undeclared identifier val
isinst2_do.dasm.il(104442) : error : Undeclared identifier val
isinst2_do.dasm.il(104455) : error : Undeclared identifier val
isinst2_do.dasm.il(104468) : error : Undeclared identifier val
isinst2_do.dasm.il(104481) : error : Undeclared identifier val
isinst2_do.dasm.il(104494) : error : Undeclared identifier val
isinst2_do.dasm.il(104507) : error : Undeclared identifier val
isinst2_do.dasm.il(104658) : error : Undeclared identifier val
isinst2_do.dasm.il(104722) : error : Undeclared identifier val
isinst2_do.dasm.il(104726) : error : Undeclared identifier val
isinst2_do.dasm.il(104742) : error : Undeclared identifier val
isinst2_do.dasm.il(104746) : error : Undeclared identifier val
isinst2_do.dasm.il(104762) : error : Undeclared identifier val
isinst2_do.dasm.il(104766) : error : Undeclared identifier val
isinst2_do.dasm.il(104782) : error : Undeclared identifier val
isinst2_do.dasm.il(104786) : error : Undeclared identifier val
isinst2_do.dasm.il(104802) : error : Undeclared identifier val
isinst2_do.dasm.il(104806) : error : Undeclared identifier val
isinst2_do.dasm.il(104822) : error : Undeclared identifier val
isinst2_do.dasm.il(104826) : error : Undeclared identifier val
isinst2_do.dasm.il(104842) : error : Undeclared identifier val
isinst2_do.dasm.il(104846) : error : Undeclared identifier val
isinst2_do.dasm.il(104862) : error : Undeclared identifier val
isinst2_do.dasm.il(104866) : error : Undeclared identifier val
isinst2_do.dasm.il(104882) : error : Undeclared identifier val
isinst2_do.dasm.il(104886) : error : Undeclared identifier val
isinst2_do.dasm.il(104902) : error : Undeclared identifier val
isinst2_do.dasm.il(104906) : error : Undeclared identifier val
isinst2_do.dasm.il(104922) : error : Undeclared identifier val
isinst2_do.dasm.il(104926) : error : Undeclared identifier val
isinst2_do.dasm.il(104942) : error : Undeclared identifier val
isinst2_do.dasm.il(104946) : error : Undeclared identifier val
isinst2_do.dasm.il(104962) : error : Undeclared identifier val
isinst2_do.dasm.il(104966) : error : Undeclared identifier val
isinst2_do.dasm.il(104982) : error : Undeclared identifier val
isinst2_do.dasm.il(104986) : error : Undeclared identifier val
isinst2_do.dasm.il(105002) : error : Undeclared identifier val
isinst2_do.dasm.il(105006) : error : Undeclared identifier val
isinst2_do.dasm.il(105022) : error : Undeclared identifier val
isinst2_do.dasm.il(105026) : error : Undeclared identifier val
isinst2_do.dasm.il(105042) : error : Undeclared identifier val
isinst2_do.dasm.il(105046) : error : Undeclared identifier val
isinst2_do.dasm.il(105062) : error : Undeclared identifier val
isinst2_do.dasm.il(105066) : error : Undeclared identifier val
isinst2_do.dasm.il(105082) : error : Undeclared identifier val
isinst2_do.dasm.il(105086) : error : Undeclared identifier val
isinst2_do.dasm.il(105102) : error : Undeclared identifier val
isinst2_do.dasm.il(105106) : error : Undeclared identifier val
isinst2_do.dasm.il(105122) : error : Undeclared identifier val
isinst2_do.dasm.il(105126) : error : Undeclared identifier val
isinst2_do.dasm.il(105142) : error : Undeclared identifier val
isinst2_do.dasm.il(105146) : error : Undeclared identifier val
isinst2_do.dasm.il(105162) : error : Undeclared identifier val
isinst2_do.dasm.il(105166) : error : Undeclared identifier val
isinst2_do.dasm.il(105182) : error : Undeclared identifier val
isinst2_do.dasm.il(105186) : error : Undeclared identifier val
isinst2_do.dasm.il(105202) : error : Undeclared identifier val
isinst2_do.dasm.il(105206) : error : Undeclared identifier val
isinst2_do.dasm.il(105222) : error : Undeclared identifier val
isinst2_do.dasm.il(105226) : error : Undeclared identifier val
isinst2_do.dasm.il(105242) : er


Stack trace
   at JIT_Directed._nullabletypes_isinst2_do_isinst2_do_._nullabletypes_isinst2_do_isinst2_do_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-09-27T21:28:00.087Z | osx.1015.amd64.open | x64 | [runtime-staging Release](https://dev.azure.com/dnceng/public/_build/results?buildId=32186&view=ms.vss-test-web.build-test-results-tab&runId=650398&resultId=100372&paneView=debug)
2022-09-23T06:19:28.895Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545100&resultId=105210&paneView=debug)
2022-09-21T21:30:34.502Z | osx.1015.amd64.open | x64 | [runtime-staging Release](https://dev.azure.com/dnceng/public/_build/results?buildId=25335&view=ms.vss-test-web.build-test-results-tab&runId=513594&resultId=100356&paneView=debug)
2022-11-19T21:17:27.562Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867570&resultId=102918&paneView=debug)
2022-11-19T21:16:39.834Z | osx.1200.arm64.open | arm64 | [runtime-coreclr ilasm Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867566&resultId=102181&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-11-19T20:51:51.061Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr ilasm Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867338&resultId=102092&paneView=debug)
2022-11-19T20:51:17.451Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr ilasm Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867336&resultId=101861&paneView=debug)
2022-11-19T20:48:25.822Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr ilasm Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867310&resultId=101978&paneView=debug)
2022-09-23T06:53:56.591Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545628&resultId=101741&paneView=debug)
2022-09-23T06:43:45.893Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545466&resultId=101995&paneView=debug)
2022-09-23T06:32:48.56Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545260&resultId=102174&paneView=debug)
2022-09-23T06:10:25.719Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545046&resultId=101607&paneView=debug)
2022-09-23T06:06:53.056Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545008&resultId=101765&paneView=debug)
2022-09-23T06:06:50.788Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545010&resultId=102640&paneView=debug)
2022-09-23T06:01:53.178Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=544926&resultId=103363&paneView=debug)
2022-09-22T07:09:06.366Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520844&resultId=103064&paneView=debug)
2022-09-22T06:23:34.727Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520290&resultId=103092&paneView=debug)
2022-09-22T06:23:33.602Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520286&resultId=102797&paneView=debug)
2022-09-22T06:19:30.608Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520254&resultId=102447&paneView=debug)
2022-09-22T06:11:06.088Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520164&resultId=102315&paneView=debug)
2022-11-19T21:17:27.562Z | osx.1200.amd64.open | x64 | [runtime-coreclr ilasm Checked-ilasmroundtrip](https://dev.azure.com/dnceng/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867570&resultId=105151&paneView=debug)
2022-09-22T06:38:30.9Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520510&resultId=101870&paneView=debug)
</details>

**Comment by jakobbotsch** [comment]
cc @markples

**Comment by markples** [comment]
I don't believe that this is a `Main(args)` issue.  Recent change to ilasm/ildasm (#78434) could be it.  I'll repro locally.

**Comment by markples** [comment]
@AaronRobinsonMSFT We just started seeing garbage in ildasm output, and #78434 is the only recent change in that directory.  The problem doesn't occur on Windows.  I tried debugging it (WSL, Ubuntu 20.04, but I don't think it matters).  At src/coreclr/ildasm/dasm.cpp:3746, you changed `"@%Id0"` to `"@%zd0"`.  However, when I stepped into it, I ended up in `src/coreclr/pal/src/safecrt/output.inl`:

```
#define FIND_CHAR_CLASS(lookuptbl, c)      \
        ((c) < _T(' ') || (c) > _T('x') ? \
            CH_OTHER            \
            :               \
        (enum CHARTYPE)(lookuptbl[(c)-_T(' ')] & 0xF))
```

which converted the `z` to `CH_OTHER` and then

```
#define FIND_NEXT_STATE(lookuptbl, class, state)   \
        (enum STATE)(lookuptbl[(class) * NUMSTATES + (state)] >> 4)
```

ended up with `ST_INVALID`.  There are a lot of other `%z` in that PR, so I'm not sure what is going on.  Can you please advise?

**Comment by AaronRobinsonMSFT** [comment]
Let me take a look.
