### ISSUE TITLE
Test failure baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78620]
Run: [runtime-coreclr gcstress-extra 20221119.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=88757&view=ms.vss-test-web.build-test-results-tab&runId=1868240&resultId=100014&paneView=debug)

Failed test:
```
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
```
**Error message:**
```
Assert failure(PID 688 [0x000002b0], Thread: 5040 [0x13b0]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x7070264c)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x705d499e)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x705d4459)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x705d47bd)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x705d40dd)
CORECLR! StackFrameIterator::Next + 0x50 (0x705d36b7)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x705d4d15)
CORECLR! Thread::StackWalkFrames + 0x159 (0x705d4afd)
CORECLR! ScanStackRoots + 0x196 (0x706ab594)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x706a990f)
File: D:\a_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
Image: C:\h\w\AF8D0979\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\AF8D0979\w\A73208C3\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AF8D0979\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll
Running BlittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt unrecognized
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
-- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt(unrecognized)
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AF8D0979\p
C:\h\w\AF8D0979\w\A73208C3\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by AaronRobinsonMSFT** [comment]
This looks like a codegen issue.

**Comment by AaronRobinsonMSFT** [comment]
Perhaps not. There is something slightly confusing in these tests. I think the cdecl and stdcall args are flipped in the following secitons.

https://github.com/dotnet/runtime/blob/4f53c2f7e62df44f07cf410df8a0d439f42a0a71/src/tests/baseservices/callconvs/TestCallingConventions.cs#L101-L111

https://github.com/dotnet/runtime/blob/4f53c2f7e62df44f07cf410df8a0d439f42a0a71/src/tests/baseservices/callconvs/TestCallingConventions.cs#L178-L188

**Comment by AaronRobinsonMSFT** [comment]
Reading the above tests and code more closely the tests are correct and validating the metadata callconv value is preferred over the `modopt` for other calling conventions. I stepped through some of this code and it appears that in the `calli` scenario the JIT's call into the VM isn't using the [`CallConvBuilder`](https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/callconvbuilder.cpp), which I _think_ it should. I don't recall all the code paths here, but I can say the VM side hasn't changed much since it was written, but the JIT side appears to have changed substantially. Perhaps something was missed in that transition?

/cc @jakobbotsch since I see your alias the most on recent changes in this area. Please let me know if I can help in any way.

**Comment by AaronRobinsonMSFT** [comment]
This reproduces locally for me on every run using the below environment variables. I've tried a few things like disabling inlining of the IL method that performs the `calli`, but the failure continues. I've also been able to reproduce this by removing all calls except the two calls under `NonblittableFunctionPointers()`, calling `BlittableFunctionPointers()` can be removed.

```csharp
    static void NonblittableFunctionPointers()
    {
        Console.WriteLine($"Running {nameof(NonblittableFunctionPointers)}...");

        IntPtr mod = NativeLibrary.Load(NativeFunctions.GetFullPath());
        var cbDefault = NativeLibrary.GetExport(mod, "ToUpper").ToPointer();
        var cbCdecl = NativeLibrary.GetExport(mod, "ToUpperCdecl").ToPointer();
        var cbStdcall = NativeLibrary.GetExport(mod, "ToUpperStdcall").ToPointer();

        const char a = 'i';
        const char expected = 'I';

        {
            Console.WriteLine($" -- unmanaged modopt(stdcall) modopt(unrecognized)");
            var b = CallFunctionPointers.CallUnmanagedCharChar_ModOptStdcall_ModOptUnknown(cbStdcall, a);
            Assert.Equal(expected, b);
        }

        {
            Console.WriteLine($" -- unmanaged cdecl modopt(stdcall)");
            var b = CallFunctionPointers.CallUnmanagedCdeclCharChar_ModOptStdcall(cbCdecl, a);
            Assert.Equal(expected, b);
        }
    }
```

Environment variables:
```
DOTNET_TieredCompilation=0
DOTNET_GCStress=C
DOTNET_ReadyToRun=0
DOTNET_ZapDisable=1
DOTNET_JITStress=2
```

**Comment by jakobbotsch** [comment]
From a bisection it looks like it was exposed by #78386.

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20221127.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=94512)
 
 **Failed tests:**
 ```
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
 ```
 
 **Error message:**
 ```
 
Assert failure(PID 3988 [0x00000f94], Thread: 4680 [0x1248]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x70fc228c)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x70e946be)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x70e94179)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x70e944dd)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x70e93dfd)
CORECLR! StackFrameIterator::Next + 0x50 (0x70e933d7)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x70e94a35)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70e9481d)
CORECLR! ScanStackRoots + 0x196 (0x70f6b1e4)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x70f6955f)
    File: D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
    Image: C:\h\w\A41A091E\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A41A091E\w\A5CD090A\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A41A091E\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll 
Running BlittableFunctionPointers...
 -- unmanaged
 -- unmanaged cdecl
 -- unmanaged stdcall
 -- unmanaged modopt(cdecl)
 -- unmanaged modopt(stdcall)
 -- unmanaged modopt unrecognized
 -- unmanaged modopt(stdcall) modopt(cdecl)
 -- unmanaged modopt(stdcall) modopt(unrecognized)
 -- unmanaged cdecl modopt(stdcall)
 -- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
 -- unmanaged
 -- unmanaged cdecl
 -- unmanaged stdcall
 -- unmanaged modopt(cdecl)
 -- unmanaged modopt(stdcall)
 -- unmanaged modopt(unrecognized)
 -- unmanaged modopt(stdcall) modopt(cdecl)
 -- unmanaged modopt(stdcall) modopt(unrecognized)
 -- unmanaged cdecl modopt(stdcall)
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A41A091E\p
> C:\h\w\A41A091E\w\A5CD090A\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
    at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20221204.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=101480&view=ms.vss-test-web.build-test-results-tab&runId=2173368&resultId=100004&paneView=debug)

Failed test:
```
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
```
**Error message:**
```
Assert failure(PID 4928 [0x00001340], Thread: 5584 [0x15d0]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x704903fc)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x703630ff)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x70362bba)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x70362f1e)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x7036283e)
CORECLR! StackFrameIterator::Next + 0x50 (0x70361e18)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x70363476)
CORECLR! Thread::StackWalkFrames + 0x159 (0x7036325e)
CORECLR! ScanStackRoots + 0x196 (0x70439784)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x70437aff)
File: D:\a_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
Image: C:\h\w\B0E3097B\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\B0E3097B\w\B41309C5\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B0E3097B\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll
Running BlittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt unrecognized
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
-- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt(unrecognized)
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B0E3097B\p
C:\h\w\B0E3097B\w\B41309C5\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20221217.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=115496&view=ms.vss-test-web.build-test-results-tab&runId=2443094&resultId=100023&paneView=debug)

Failed test:
```
coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd

coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
```

**Error message:**
```
Assert failure(PID 944 [0x000003b0], Thread: 5824 [0x16c0]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x704f262c)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x703c5111)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x703c4bc9)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x703c4f2d)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x703c484d)
CORECLR! StackFrameIterator::Next + 0x50 (0x703c3e27)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x703c5488)
CORECLR! Thread::StackWalkFrames + 0x159 (0x703c5270)
CORECLR! ScanStackRoots + 0x196 (0x7049b7b4)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x70499b0f)
File: D:\a_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
Image: C:\h\w\AC20091F\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\AC20091F\w\A6E509A8\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AC20091F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll
Running BlittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt unrecognized
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
-- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
-- unmanaged
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AC20091F\p
C:\h\w\AC20091F\w\A6E509A8\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20221225.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=119750&view=ms.vss-test-web.build-test-results-tab&runId=2554032&resultId=100006&paneView=debug)

Failed test:
```
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd

coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
```

**Error message:**
```
Assert failure(PID 6300 [0x0000189c], Thread: 7164 [0x1bfc]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x704d183c)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x703a431e)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x703a3dd9)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x703a413d)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x703a3a5d)
CORECLR! StackFrameIterator::Next + 0x50 (0x703a3037)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x703a4695)
CORECLR! Thread::StackWalkFrames + 0x159 (0x703a447d)
CORECLR! ScanStackRoots + 0x196 (0x7047a9f4)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x70478d4f)
File: D:\a_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
Image: C:\h\w\A58708DC\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A58708DC\w\A7E80985\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A58708DC\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll
Running BlittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt unrecognized
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
-- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
-- unmanaged
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A58708DC\p
C:\h\w\A58708DC\w\A7E80985\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20230107.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=129577&view=ms.vss-test-web.build-test-results-tab&runId=2800624&resultId=100014&paneView=debug)

Failed test:
```
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd

coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
```
**Error message:**
```
Assert failure(PID 472 [0x000001d8], Thread: 6916 [0x1b04]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x70090cbc)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x6ff6399e)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x6ff63459)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x6ff637bd)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x6ff630dd)
CORECLR! StackFrameIterator::Next + 0x50 (0x6ff626b7)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x6ff63d15)
CORECLR! Thread::StackWalkFrames + 0x159 (0x6ff63afd)
CORECLR! ScanStackRoots + 0x196 (0x70039e24)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x7003817f)
File: D:\a_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
Image: C:\h\w\AEE2098C\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\AEE2098C\w\9A6108B9\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AEE2098C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll
Running BlittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt unrecognized
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
-- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
-- unmanaged
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AEE2098C\p
C:\h\w\AEE2098C\w\9A6108B9\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20230122.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=144745&view=ms.vss-test-web.build-test-results-tab&runId=3116961&resultId=100011&paneView=debug)

Failed test:
```
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd

coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd
```
**Error message:**
```
Assert failure(PID 5484 [0x0000156c], Thread: 3748 [0x0ea4]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x70d20b1c)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x70bf390e)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x70bf33c9)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x70bf372d)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x70bf304d)
CORECLR! StackFrameIterator::Next + 0x50 (0x70bf2627)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x70bf3c85)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70bf3a6d)
CORECLR! ScanStackRoots + 0x196 (0x70cc9bc4)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x70cc7f1f)
File: D:\a_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
Image: C:\h\w\B37A09EE\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\B37A09EE\w\AFD6099A\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B37A09EE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll
Running BlittableFunctionPointers...
-- unmanaged
-- unmanaged cdecl
-- unmanaged stdcall
-- unmanaged modopt(cdecl)
-- unmanaged modopt(stdcall)
-- unmanaged modopt unrecognized
-- unmanaged modopt(stdcall) modopt(cdecl)
-- unmanaged modopt(stdcall) modopt(unrecognized)
-- unmanaged cdecl modopt(stdcall)
-- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
-- unmanaged
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B37A09EE\p
C:\h\w\B37A09EE\w\AFD6099A\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed in Run: [runtime-coreclr gcstress-extra 20230212.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=169006)
 
 **Failed tests:**
 ```
 coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open
     - baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd

coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open
     - baseservices\\callconvs\\TestCallingConventions\\TestCallingConventions.cmd 
```
 
 **Error message:**
 ```
 
Assert failure(PID 2440 [0x00000988], Thread: 5768 [0x1688]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"

CORECLR! DoJITFailFast + 0xBA (0x70780fec)
CORECLR! CrawlFrame::SetCurGSCookie + 0x2F (0x7065394f)
CORECLR! StackFrameIterator::PreProcessingForManagedFrames + 0x51 (0x7065340a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x21C (0x7065376e)
CORECLR! StackFrameIterator::NextRaw + 0x9E0 (0x7065308e)
CORECLR! StackFrameIterator::Next + 0x50 (0x70652668)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x70653cc6)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70653aae)
CORECLR! ScanStackRoots + 0x196 (0x70729f14)
CORECLR! GCToEEInterface::GcScanRoots + 0xF1 (0x7072826f)
    File: D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp Line: 4351
    Image: C:\h\w\B5340A00\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B5340A00\w\96F907F5\uploads\Reports\baseservices.callconvs\TestCallingConventions\TestCallingConventions.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B5340A00\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestCallingConventions.dll 
Running BlittableFunctionPointers...
 -- unmanaged
 -- unmanaged cdecl
 -- unmanaged stdcall
 -- unmanaged modopt(cdecl)
 -- unmanaged modopt(stdcall)
 -- unmanaged modopt unrecognized
 -- unmanaged modopt(stdcall) modopt(cdecl)
 -- unmanaged modopt(stdcall) modopt(unrecognized)
 -- unmanaged cdecl modopt(stdcall)
 -- unmanaged stdcall modopt(cdecl)
Running NonblittableFunctionPointers...
 -- unmanaged
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B5340A00\p
> C:\h\w\B5340A00\w\96F907F5\e\baseservices\callconvs\TestCallingConventions\TestCallingConventions.cmd
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by BruceForstall** [comment]
@EgorBo This test continues to fail regularly. PTAL.

**Comment by BruceForstall** [comment]
The test is now disabled (for GCStress), so remove blocking label, add disabled-test label

**Comment by BruceForstall** [comment]
I can't reproduce this locally. Submitted PR to re-enable for GCStress and triggered GCStress pipelines: https://github.com/dotnet/runtime/pull/92445

**Comment by BruceForstall** [comment]
I re-enabled the test. If it fails again, we'll get a new issue.
