### ISSUE TITLE
AOT - Cannot use System.Reflection on type named `AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage`

### ISSUE THREAD

**Issue by sencagri** [dotnet/runtime#78638]
### Description

I have published a .NET Maui app it is working on emulators but not working on real devices.  By the way, I have tested 5 different real device.

### **When trimming and AOT is disabled it works but incredibly slow and sluggish.** 

There is a apk file I have uploaded for testing, you can download it to your devices and emulators also.
https://aktifbarkod.com/d just go and download apk file. ( There is a only one apk file )

The only log output I can find is below from a real device:
```
android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage while decoding custom attribute: (null)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(Assembly , Type )
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[XamlResourceIdAttribute](Assembly )
   at Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute.GetTypeForPath(Assembly assembly, String path)
   at Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(Uri value, String resourcePath, Assembly assembly, IXmlLineInfo lineInfo)
   at AktifBarkod.AktifPOS.Mobil.App.InitializeComponent()
   at AktifBarkod.AktifPOS.Mobil.App..ctor()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
   at System.Collections.Concurrent.ConcurrentDictionary2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
   at Microsoft.Maui.MauiApplication.OnCreate()
   at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
 at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
 at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6975)
 at android.app.ActivityThread.access$1500(ActivityThread.java:257)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8037)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Real device

https://user-images.githubusercontent.com/7950917/201405363-05593aff-26bb-4aee-bfc3-e8017199dbad.mp4

Emulator

https://user-images.githubusercontent.com/7950917/201408674-68cda6da-3e98-42d6-91d5-ae0782785c0f.mp4

PS:

### Steps to Reproduce

-

### Link to public reproduction project repository

This is a private repo.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All android versions

### Did you find any workaround?

no

**Comment by SamMonoRT** [comment]
cc @ivanpovazan @jandupej : please investigate.

**Comment by ivanpovazan** [comment]
@sencagri could you please provide versions of dotnet and MAUI you were using?

>Same issue here. I have updated to .net 7 to see if it solves the problem but apk still crashes

@VictorCanovasA does it crash with the same exception?

**Comment by sencagri** [comment]
![image](https://user-images.githubusercontent.com/7950917/206239265-7de3e819-7a1d-4778-96d1-5e2209528a31.png)

All possible combinations tested.

**Comment by alrit-solutions** [comment]
I managed to get this working in the end by removing Android SDKs and re-downloading/installing them. Had to recreate the device images again for the emulator. Also went back to .net 6. 
![image](https://user-images.githubusercontent.com/55795906/206432440-ac629f79-8c36-49e2-819b-16a89f106334.png)

**Comment by sencagri** [comment]
We are not working together.

**Comment by espenrl** [comment]
It seems to be an issue specific to XAML. I have types in my MAUI project with Norwegian letter å, but only those used in XAML causes this problem for me. Other ones work fine. I had to rename a viewmodel and some pocos which where being databound in XAML.

**Comment by jonathanpeppers** [comment]
@espenrl can you try disabling XAML compilation?

https://learn.microsoft.com/en-us/dotnet/maui/xaml/xamlc?view=net-maui-7.0#disable-compilation

If that solves your problem, we should move this back to dotnet/maui.

**Comment by espenrl** [comment]
These results are from release builds deployed by cable through latest VS Preview to a Samsung S22.

With XAML compilation set to skip at assembly level the app crashes at startup. And I don't get an error message because of the release build.

With XAML compilation set to skip at the page level I get a different error message. Please see the exceptions below.

```
namespace Mdir.Views;

public sealed partial class VerneområdePage : ContentPage
{
    public VerneområdePage(VerneområdeViewModel viewModel)
    {
        InitializeComponent();
        BindingContext = viewModel;
    }
}
```

Before applying XAML compilation skip.
```
System.TypeLoadException: Could not resolve type with token 0100033b from typeref (expected class 'Mdir.Views.VerneområdeViewModel' in assembly '')
   at Mdir.Views.VerneområdePage..ctor(VerneområdeViewModel viewModel)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.Controls.Routing.TypeRouteFactory.GetOrCreate(IServiceProvider services)
   at Microsoft.Maui.Controls.Routing.GetOrCreateContent(String route, IServiceProvider services)
   at Microsoft.Maui.Controls.ShellSection.GetOrCreateFromRoute(String route, ShellRouteParameters queryData, IServiceProvider services, Boolean isLast, Boolean isPopping)
   at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping)
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
```

With [XamlCompilation (XamlCompilationOptions.Skip)] at page level.
```
System.TypeLoadException: Could not load type Mdir.Views.VerneområdePage while decoding custom attribute: (null)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
   at System.Attribute.GetCustomAttributes(Assembly , Type )
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(Assembly , Type )
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[XamlResourceIdAttribute](Assembly )
   at Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute.GetResourceIdForType(Type type)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.GetXamlForType(Type type, Object instance, Boolean& useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[VerneområdePage](VerneområdePage view, Type callingType)
   at Mdir.Views.VerneområdePage.InitializeComponent()
   at Mdir.Views.VerneområdePage..ctor(VerneområdeViewModel viewModel)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.Controls.Routing.TypeRouteFactory.GetOrCreate(IServiceProvider services)
   at Microsoft.Maui.Controls.Routing.GetOrCreateContent(String route, IServiceProvider services)
   at Microsoft.Maui.Controls.ShellSection.GetOrCreateFromRoute(String route, ShellRouteParameters queryData, IServiceProvider services, Boolean isLast, Boolean isPopping)
   at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping)
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
```

**Comment by jonathanpeppers** [comment]
@espenrl it looks like you can disable XamlC completely with:
```xml
<PropertyGroup>
  <MauiXamlCValidateOnly>true</MauiXamlCValidateOnly>
</PropertyGroup>
```

That should prevent it from writing assemblies with Mono.Cecil at all. Does that change anything?

**Comment by espenrl** [comment]
I tried it and the app still crashes upon startup.

**Comment by ivanpovazan** [comment]
Thank you all for the provided input.
After investigating it does not seem to be related to XamlC, but instead to the AOT image. 
I have created a smaller example which reproduces the issue.

The repro steps are as follows..

Dotnet and MAUI versions:
- `dotnet 7.0.100`
- `maui 7.0.52/7.0.100 SDK 7.0.100`

Create, build and run the following application:
1. Create a MAUI application:
`dotnet new maui -n ReproIssue78638`
2. Add the following types to the `MauiProgram.cs`:
``` csharp
[AttributeUsage(AttributeTargets.Class)]
public class TestingAttribute : Attribute
{
	public Type Type {get; private set;}
	public TestingAttribute(Type type)
	{
		Type = type;
	}
}

[Testing(typeof(EkranDiğer))]
public class ATestingClass
{
	public ATestingClass(){}
}

public class EkranDiğer{}
```
3. Adjust the `CreateMauiApp` method in `MauiProgram.cs` by adding:
``` csharp
public static MauiApp CreateMauiApp()
{
	var attr = (TestingAttribute) Attribute.GetCustomAttribute(typeof(ATestingClass), typeof (TestingAttribute));
	Console.WriteLine($"CreateMauiApp started {attr.Type}");

	var builder = MauiApp.CreateBuilder();
	...
```
4. Build the application and run on a device:
`dotnet publish -c Release -t:Run -f net7.0-android -bl`
5. Inspect the log with
`adb logcat > log.txt`

```
... log.txt:
01-13 14:41:26.202 24860 24860 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type ReproIssue78638.EkranDiğer while decoding custom attribute: (null)
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at System.Attribute.GetAttr(ICustomAttributeProvider , Type , Boolean )
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at System.Attribute.GetCustomAttribute(MemberInfo , Type )
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at ReproIssue78638.MauiProgram.CreateMauiApp()
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at ReproIssue78638.MainApplication.CreateMauiApp()
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at Microsoft.Maui.MauiApplication.OnCreate()
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
01-13 14:41:26.202 24860 24860 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6986)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:274)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2093)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
01-13 14:41:26.202 24860 24860 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```
---
I also confirmed that the problem is not present on iOS platforms.
- Built and executed with: `dotnet publish -c Release -t:Run -f net7.0-ios -r ios-arm64 -bl`
- The app successfully starts up and prints: `CreateMauiApp started ReproIssue78638.EkranDiğer`

I will continue investigating.
