### ISSUE TITLE
Blazor.platform.readStringField not working anymore after dotnet 7.0 upgrade

### ISSUE THREAD

**Issue by devedse** [dotnet/runtime#78731]
### Description

Hello, I'm currently a user of nKast's WASM implementation of MonoGame:
https://github.com/nkast/Wasm
https://github.com/kniEngine/kni

However after a dotnet 7 upgrade this logic doesn't work anymore.

I've been trying to dive into the issue here but it seems the code that was previously used to pass parameters to the frontend isn't working anymore:
![image](https://user-images.githubusercontent.com/2350015/203421446-6c1861fe-5bce-4512-8949-cbcf393d0788.png)

Previously the `var id` should have the value `theCanvas`.

The way this functionality is being called can be found here:
https://github.com/nkast/Wasm/blob/main/Wasm.Dom/Document.cs#L40

### Reproduction Steps

I created a branch of my 3d Maze Generator making use of MonoGame / Wasm to run in the browser here:
https://github.com/devedse/DeveMazeGeneratorCore/tree/dotnet7

Simply open the DeveMazeGeneratorCoreMonoGame.sln, set the Blazor project as startup and click F5.

This error should popup in the console window:

```
Unhandled Exception:
blazor.webassembly.js:1 System.NullReferenceException: Object reference not set to an instance of an object.
dotnet.7.0.0.3dkjxfc2jf.js:5 Uncaught Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at :5259/MonoGame.Framework.BlazorGameWindow.get_ClientBounds() in C:\XGit\kni\MonoGame.Framework\Platform\Blazor\BlazorGameWindow.cs:line 62
   at Microsoft.Xna.Platform.ConcreteGraphicsDeviceManager..ctor(:5259/Game game) in C:\XGit\kni\MonoGame.Framework\ConcreteGraphicsDeviceManager.Blazor.cs:line 16
   at Microsoft.Xna.Framework.GraphicsDeviceManager..ctor(:5259/Game game) in C:\XGit\kni\MonoGame.Framework\GraphicsDeviceManager.cs:line 39
   at DeveMazeGeneratorMonoGame.TheGame..ctor(:5259/IContentManagerExtension contentManagerExtension, Nullable`1 desiredScreenSize, Platform platform) in C:\XGitPrivate\DeveMazeGeneratorCore\DeveMazeGeneratorCore.MonoGame.Core\TheGame.cs:line 152
   at :5259/DeveMazeGeneratorCore.MonoGame.Blazor.Pages.Index.TickDotNet() in C:\XGitPrivate\DeveMazeGeneratorCore\DeveMazeGeneratorCore.MonoGame.Blazor\Pages\Index.razor.cs:line 37
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(:5259/JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(:5259/JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(:5259/String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at qi (dotnet.7.0.0.3dkjxfc2jf.js:5:80156)
    at Ji (dotnet.7.0.0.3dkjxfc2jf.js:5:80040)
    at _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:30:5)
    at Object.invokeDotNetFromJS (blazor.webassembly.js:1:45192)
    at g (blazor.webassembly.js:1:1621)
    at A.invokeMethod (blazor.webassembly.js:1:3812)
    at tickJS ((index):61:32)
```

### Expected behavior

I know that this behaviour is now deprecated (as of: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/import-export-interop?view=aspnetcore-7.0#call-javascript-from-net)

However I would expect the funcionality to remain working.

### Actual behavior

The `Blazor.platform.readStringField` is returning:
![image](https://user-images.githubusercontent.com/2350015/203422455-763634b4-17ec-4ec5-b48f-976e43f8ffc4.png)

but should return `theCanvas`

### Known Workarounds

Probably rewrite everything to [JSImport] [JSExport], but that's quite some work I'd rather not do now.

### Configuration

dotnet 7.0
X64
Google Chrome

**Comment by pavelsavara** [comment]
@devedse could you please create simpler repro ? 
As far as I could tell, we didn't remove any functionality in Net7 and marking it obsolete should not break it. 

If I read the code correctly it uses `readStringField` and I don't know if that's public API. But it's fragile for sure. Maybe some memory offset changed ?

cc @danroth27 this seems most likely blazor interop.

**Comment by devedse** [comment]
@pavelsavara, it's a bit hard for me to produce something smaller. The way I reproduced it is by manually including the sources of the NuGet packages I was using.

**Comment by pavelsavara** [comment]
I'm not sure, but it seems to me that if you add `string` which is ref type into ValueTuple it would become non-blittable. 
And perhaps native offset of fields changed between net6 and net7 (as that's internal implementation detail).

**Comment by nkast** [comment]
I found another example that is very similar.
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-5.0#unmarshalled-javascript-interop-2
It uses a struct ('InteropStruct') to pass values to JS and the readStringField/readInt32Field methods.
In my test I am passing two integer values before and after the string which I can read successfully with readInt32Field from offsets 0 and 8.

**Comment by pavelsavara** [comment]
Observation: 
- the `ValueTuple` is `[StructLayout(LayoutKind.Auto)]`
- the `RenderTreeEdit` where Blazor uses it internally is `[StructLayout(LayoutKind.Explicit)]` with 
`[FieldOffset(16)]`


https://github.com/dotnet/runtime/blob/89cfbfd84146e89ab18771c42928d23ff09232c1/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L626-L629


https://github.com/dotnet/aspnetcore/blob/ea529f4756841fdf8d7cee5b3c188210520c1323/src/Components/Components/src/RenderTree/RenderTreeEdit.cs#L14-L15

**Comment by pavelsavara** [comment]
I tried to reproduce by building your branch. And it works for me.

![image](https://user-images.githubusercontent.com/271576/203839250-5ba4135a-9fb6-4ee8-8800-5cbfc930f177.png)

I also noticed that your screenshot has `Document.6.0.2.js` in it.

**Comment by pavelsavara** [comment]
Perhaps try to re-install your `wasm-tools` workload if you installed any of the previews.

**Comment by nkast** [comment]
@pavelsavara I got the net7 from a VS update. I installed the wasm-tools just in case but I had no difference.

I've added some more tests for ValueTuples and structs with varying number of arguments.
The problem seems to be with single fields in structs/ValueTuples, which was the case originally 
with the 'GetElementById(..)'.

The value 'd' I am getting in TestValueTupleString1 and TestStructString1 
can be converted directly to string with 'BINDING.conv_string(d)'.
Normally 'readStringField(..)' resolves this value from HEAP32.

The TestStructInt1 receives directly the value of the struct field. [1](https://github.com/nkast/Wasm/blob/16d73db82a9f8f2d1187a31133dbe92e9d71debd/Wasm.Dom/wwwroot/js/Document.7.0.0.js#L63)
Bellow are the results I am getting from those tests.

```
*net6
TestValueTupleString1: theCanvas1
TestValueTupleString2: theCanvas2
TestValueTupleString3: theCanvas3
TestValueTupleString1: theCanvas1struct
TestValueTupleString2: theCanvas2struct
TestStructInt1: 42
TestString: theCanvas

*net7
TestValueTupleString1: ????
TestValueTupleString2: theCanvas2
TestValueTupleString3: theCanvas3
TestValueTupleString1: ????
TestValueTupleString2: theCanvas2struct
TestStructInt1: 0
TestString: theCanvas
 ```
