### ISSUE TITLE
CI failure: System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Cancel_With_InfiniteTimeout - The operation has timed out.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#78777]
Hit this in a PR in `main`: https://github.com/dotnet/runtime/pull/78744/

Curious that the test name is "inifite timeout". It failed here: https://github.com/dotnet/runtime/blob/9687016b1652735b143845bc4b6b35ec0b72a680/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.Specific.cs#L721

- Queue: `Libraries Test Run release coreclr windows x64 Debug`
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=91705&view=logs&j=cb131f87-d5af-5ecc-6e5f-6dc86994859c&t=76503e0a-8c41-542c-43da-63a4758a95b0&l=105
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78744-merge-28ab70a3bafc4828a7/System.IO.Pipes.Tests/1/console.ee868f43.log?helixlogtype=result
- Callstack:
```
===========================================================================================================

C:\h\w\B3F10974\w\B5340A08\e>"C:\h\w\B3F10974\p\dotnet.exe" exec --runtimeconfig System.IO.Pipes.Tests.runtimeconfig.json --depsfile System.IO.Pipes.Tests.deps.json xunit.console.dll System.IO.Pipes.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.IO.Pipes.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.Pipes.Tests (found 445 of 536 test cases)
  Starting:    System.IO.Pipes.Tests (parallel test collections = on, max threads = 2)
    System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Cancel_With_InfiniteTimeout [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
           at System.Threading.Tasks.TaskTimeoutExtensions.WaitAsync[TResult](Task`1 task, TimeSpan timeout, CancellationToken cancellationToken)
        /_/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.Specific.cs(721,0): at System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Cancel_With_InfiniteTimeout()
        --- End of stack trace from previous location ---
  Finished:    System.IO.Pipes.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.Pipes.Tests  Total: 1223, Errors: 0, Failed: 1, Skipped: 0, Time: 14.792s
----- end Wed 11/23/2022  4:48:38.02 ----- exit code 1 ----------------------------------------------------------
2022-11-23T04:48:38.779Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-11-23T04:48:38.779Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B3F10974\w\B5340A08\e' for test results files
2022-11-23T04:48:38.779Z	INFO   	run.py	__init__(48)	read_results	Found results file C:\h\w\B3F10974\w\B5340A08\e\testResults.xml with format xunit
2022-11-23T04:48:38.794Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\B3F10974\w\B5340A08\uploads' for test results files
2022-11-23T04:48:38.794Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 1223 test reports to 'C:\h\w\B3F10974\w\B5340A08\e\__test_report.json'
2022-11-23T04:48:38.810Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 363262 bytes
ERROR: The process "corerun.exe" not found.
Did not find dumps, skipping dump docs generation.
['System.IO.Pipes.Tests' END OF WORK ITEM LOG: Command exited with 0]
```

**Comment by stephentoub** [comment]
ClientConnectAsync_Cancel_With_InfiniteTimeout continues to fail on many PRs.

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/69101
