### ISSUE TITLE
ArgumentOutOfRangeException thrown for System.Text.Json with default buffer size

### ISSUE THREAD

**Issue by Nuklon** [dotnet/runtime#78856]
### Description

With default 16KB buffer size, some JSONs (I cannot add as it contains private data) throw the following exception:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
```

### Reproduction Steps

Deserialize a JSON file. It seems to happen with certain file sizes. I can reproduce it with a file of size: 153.936.953 bytes (saved as UTF8). If I add a space in front of the file (+1 byte, so 153.936.954 bytes) it works correctly. (I cannot attach this JSON due to it being private data).

### Expected behavior

Shouldn't throw and read it correctly

### Actual behavior

Throws.

### Regression?

I don't know.

### Known Workarounds

Change default buffer size to 4K or 32K. Alternatively: read entire file into memory, then deserialize it.

### Configuration

.NET 7.0 RTM.
Windows 10 21H2.
x64.
Probably not.

**Comment by Nuklon** [comment]
Just saw #78692, this seems like a duplicate. Didn't find it before, so let me close this.
