### ISSUE TITLE
ILCompiler --make-repro-path option is not working in .net8

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#78921]
### Description

`--make-repro-path` command line options seems to be broken in NativeAOT compiler (most likely in Crossgen2 as well) on the main branch.

### Reproduction Steps

This is a minimal repro scenario which causes the failure:

1. Create a dummy response file test.rsp in the root folder with:
```
--reference:./artifacts/bin/coreclr/OSX.arm64.Debug/System.Private.CoreLib.dll
./artifacts/bin/coreclr/OSX.arm64.Debug/System.Private.CoreLib.dll
-o:a.o
--make-repro-path:/Users/ivan/tmp
```
2. Build NativeAOT with:
`./build.sh clr+clr.aot`
3. Invoke the NativeAOT compiler with:
` ./dotnet.sh exec ./artifacts/bin/coreclr/OSX.arm64.Debug/ilc/ilc.dll @test.rsp`

NOTE: This response file does not make much sense and will throw somewhere else in the ILCompiler, but is good enough to reproduce the issue and generate the zip when fixed.

### Expected behavior

The repro package is created.

### Actual behavior

The ilc compiler throws with:
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.String]' to type 'System.String'.
   at System.CommandLine.Helpers.MakeReproPackage(String makeReproPath, String outputFilePath, String[] args, ParseResult res, IEnumerable`1 inputOptions) in /Users/ivan/repos/runtime-coreCLR/src/coreclr/tools/Common/CommandLineHelpers.cs:line 226
   at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass200_0.<.ctor>b__0(InvocationContext context) in /Users/ivan/repos/runtime-coreCLR/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 265
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at ILCompiler.Program.Main(String[] args) in /Users/ivan/repos/runtime-coreCLR/src/coreclr/tools/aot/ILCompiler/Program.cs:line 658
```

### Configuration

- .NET 8 version: current main branch - hash f35444a98a0dfc8767ef960a5c9cfca7109ce519
- Platform: osx-arm64
- OS: Ventura 13.0.1

**Comment by jkotas** [comment]
cc @am11 This looks like a regression from System.CommandLine conversion.
