### ISSUE TITLE
Build mono+libs for browser on windows failed with UnicodeDecodeError.

### ISSUE THREAD

**Issue by ifeuille** [dotnet/runtime#78947]
### Description

1.I have test HelloWorld/mbr/... samples with backend mono on my windows pc.
2.It's ok to build mono+libs for windows system.
But it's failed when I tried(by console. Cygwin test too):
build.cmd mono+libs -os Browser -c Debug

### Reproduction Steps

build browser mono with cmd:
build.cmd mono+libs -os Browser -c Debug

### Expected behavior

1.checkout branch release/v6.0
2.prepare all environment and resources.
3.build browser mono with cmd:
build.cmd mono+libs -os Browser -c Debug

### Actual behavior

it's failed when I tried(by console. Cygwin test too):
build.cmd mono+libs -os Browser -c Debug
And the output error:
````
  Microsoft.Extensions.Configuration.Xml -> D:\work\net\NetRuntime\artifacts\bin\Microsoft.Extensions.Configuratistandard2.0-Debug\System.Security.Cryptography.Pkcs.dll
on.Xml\netstandard2.0-Debug\Microsoft.Extensions.Configuration.Xml.dll
  Microsoft.Extensions.Hosting.Systemd -> D:\work\net\NetRuntime\artifacts\bin\Microsoft.Extensions.Hosting.Syste1-Debug\Microsoft.Extensions.Hosting.dll
md\netstandard2.1-Debug\Microsoft.Extensions.Hosting.Systemd.dll
  Microsoft.Extensions.Hosting.WindowsServices -> D:\work\net\NetRuntime\artifacts\bin\Microsoft.Extensions.Hostimd\netstandard2.1-Debug\Microsoft.Extensions.Hosting.Systemd.dll
ng.WindowsServices\netstandard2.1-Debug\Microsoft.Extensions.Hosting.WindowsServices.dll
  mscorlib -> D:\work\net\NetRuntime\artifacts\bin\manual.mscorlib\net6.0-Debug\mscorlib.dll
  System -> D:\work\net\NetRuntime\artifacts\bin\manual.System\net6.0-Debug\System.dll
  System.Data -> D:\work\net\NetRuntime\artifacts\bin\manual.System.Data\net6.0-Debug\System.Data.dll
  System.Xml -> D:\work\net\NetRuntime\artifacts\bin\manual.System.Xml\net6.0-Debug\System.Xml.dll
  ApiCompat ->
  Trimming browser-wasm runtime pack assemblies with ILLinker...
  Trimming browser-wasm OOB assemblies with ILLinker...
  wasm ->
  Traceback (most recent call last):
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emcc.py", line 3731, in <module>
      sys.exit(main(sys.argv))
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emcc.py", line 3724, in main
      ret = run(args)
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emcc.py", line 1125, in run
      phase_post_link(options, state, wasm_target, wasm_target, target)
    File "contextlib.py", line 79, in inner
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emcc.py", line 2491, in phase_post_link
      phase_emscript(options, in_wasm, wasm_target, memfile)
    File "contextlib.py", line 79, in inner
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emcc.py", line 2519, in phase_emscript
      emscripten.run(in_wasm, wasm_target, final_js, memfile)
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emscripten.py", line 834, in run
      emscript(in_wasm, out_wasm, outfile_js, memfile, shared.DEBUG)
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emscripten.py", line 308, in emscript
      glue, forwarded_data = compile_settings()
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\emscripten.py", line 176, in compile_set
tings
      out = shared.run_js_tool(path_from_root('src', 'compiler.js'),
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\tools\shared.py", line 232, in run_js_to
ol
      return check_call(command, *args, **kw).stdout
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\tools\shared.py", line 218, in check_cal
l
      return run_process(cmd, *args, **kw)
    File "D:\work\net\NetRuntime\src\mono\wasm\emsdk\upstream\emscripten\tools\shared.py", line 103, in run_proce
ss
      ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
    File "subprocess.py", line 507, in run
    File "subprocess.py", line 1121, in communicate
  UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 314148: illegal multibyte sequence
  
  
  
D:\work\net\NetRuntime\src\mono\wasm\wasm.proj(224,5): error MSB3073: The command "@cmd /c "call "D:/work/net/Net
Runtime/src/mono/wasm/emsdk/emsdk_env.bat" > nul 2>&1 && emcc @D:\work\net\NetRuntime\artifacts\bin\native\net6.0
-Browser-Debug-wasm\src\emcc-default.rsp -g -Os -s -DENABLE_NETCORE=1 -DDEBUG=1 --js-library runtime/library_mono
.js --js-library runtime/binding_support.js --js-library runtime/dotnet_support.js --js-library "D:\work\net\NetR
untime\src\libraries\Native\Unix\System.Native\pal_random.js" "D:\work\net\NetRuntime\artifacts\obj\mono\Browser.
wasm.Debug\driver.o" "D:\work\net\NetRuntime\artifacts\obj\mono\Browser.wasm.Debug\pinvoke.o" "D:\work\net\NetRun
time\artifacts\obj\mono\Browser.wasm.Debug\corebindings.o" "D:\work\net\NetRuntime\artifacts\bin\mono\Browser.was
m.Debug\libmono-ee-interp.a" "D:\work\net\NetRuntime\artifacts\bin\mono\Browser.wasm.Debug\libmonosgen-2.0.a" "D:
\work\net\NetRuntime\artifacts\bin\mono\Browser.wasm.Debug\libmono-ilgen.a" "D:\work\net\NetRuntime\artifacts\bin
\mono\Browser.wasm.Debug\libmono-icall-table.a" "D:\work\net\NetRuntime\artifacts\bin\native\net6.0-Browser-Debug
-wasm\libSystem.Native.a" "D:\work\net\NetRuntime\artifacts\bin\native\net6.0-Browser-Debug-wasm\libSystem.IO.Com
pression.Native.a" "C:\Users\**\.nuget\packages\microsoft.netcore.runtime.icu.transport\6.0.0-rtm.22108.1\runt
imes\browser-wasm\native\lib\libicuuc.a" "C:\Users\**\.nuget\packages\microsoft.netcore.runtime.icu.transport\
6.0.0-rtm.22108.1\runtimes\browser-wasm\native\lib\libicui18n.a" "D:\work\net\NetRuntime\artifacts\bin\mono\Brows
er.wasm.Debug\libmono-component-hot_reload-static.a" "D:\work\net\NetRuntime\artifacts\bin\mono\Browser.wasm.Debu
g\libmono-component-debugger-static.a" "D:\work\net\NetRuntime\artifacts\bin\mono\Browser.wasm.Debug\libmono-comp
onent-diagnostics_tracing-stub-static.a" -o "D:\work\net\NetRuntime\artifacts\bin\native\net6.0-Browser-Debug-was
m\dotnet.js" && "D:/work/net/NetRuntime/src/mono/wasm/emsdk//upstream/bin/wasm-opt" --strip-dwarf "D:\work\net\Ne
tRuntime\artifacts\bin\native\net6.0-Browser-Debug-wasm\dotnet.wasm" -o "D:\work\net\NetRuntime\artifacts\bin\nat
ive\net6.0-Browser-Debug-wasm\dotnet.wasm""" exited with code 1.

````

### Configuration

branch: release/6.0
windows10+x64

### Other information

owners:@akoeplinger

**Comment by ifeuille** [comment]
It's fixed by :
[53367](https://github.com/dotnet/runtime/issues/53367)
[emsdk-35](https://github.com/dotnet/emsdk/pull/35)
