### ISSUE TITLE
IL instruction: ldtoken(method) compiles incorrectly at PublishAOT.

### ISSUE THREAD

**Issue by Dogwei** [dotnet/runtime#78955]
#### I'm adapting AOT for my project.

Github: https://github.com/Dogwei/Swifter.Json
Nuget: https://www.nuget.org/packages/Swifter.Json/

#### But I have come across a tricky problem as below, which makes me have to ask for help.

```
3>Specified cast is not valid.
3>System.InvalidCastException: Specified cast is not valid.
3>   at ILCompiler.DependencyAnalysis.ConstructedEETypeNode.CreationAllowed(TypeDesc) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ConstructedEETypeNode.cs:line 145
3>   at ILCompiler.DependencyAnalysis.NativeLayoutMethodLdTokenVertexNode.GetGenericVirtualMethodDependencies(NodeFactory) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NativeLayoutVertexNode.cs:line 269
3>   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 181
3>   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 221
3>   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 256
3>   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 307
3>   at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 140
3>   at ILCompiler.Program.<Run>g__RunScanner|73_4(<>c__DisplayClass73_0&) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 884
3>   at ILCompiler.Program.Run(String[]) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 866
3>   at ILCompiler.Program.Main(String[]) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 1150
3>命令“"C:\Users\X\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.0\tools\\ilc" @"obj\Release\net7\win-x64\native\Swifter.Json.Test.ilc.rsp"”已退出，代码为 1。
```

#### As shown in the frame selection part below.

```
ldtoken(MethodInfo);
```

![image](https://user-images.githubusercontent.com/14845492/204471125-61138a63-ab6d-40e2-aa34-1e212bfc8639.png)

#### csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7</TargetFramework>
	<LangVersion>11</LangVersion>
    <Nullable>enable</Nullable>
	<PublishTrimmed>true</PublishTrimmed>
	<PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swifter.Json" Version="1.6.0.5" />
  </ItemGroup>

</Project>

```
#### Main function:

```
            var model = new { Id = 123, Name = "Dogwei" };

            Console.WriteLine(JsonFormatter.SerializeObject(model));
```

**Comment by Suchiman** [comment]
My guess would be, that the issue goes away if the `ldtoken` were immediately followed up by
```
call class [System.Runtime]System.Reflection.MethodBase [System.Runtime]System.Reflection.MethodBase::GetMethodFromHandle(valuetype [System.Runtime]System.RuntimeMethodHandle)
castclass [System.Runtime]System.Reflection.MethodInfo
```
which is the standard sequence emitted by, for example, `Expression<Func<T>>`

**Comment by MichalStrehovsky** [comment]
I'm pretty sure this is because the ldtoken is to an uninstantiated generic method. Those need to be filtered out and ignored for generic virtual method processing. We do it elsewhere but I apparently forgot here.

But given the ldtoken is immediately followed by Make generic method, this is not going to work at runtime with AOT anyway. MakeGenericMethod is runtime code generation and needs a jit.

We should still fix the ldtoken though.
