### ISSUE TITLE
[wasm] `dotnet-runtime-perf` - OOM on `Perf_File.ReadAllBytes` with `size=100M`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#79047]
[Run with the interpreter](https://dev.azure.com/dnceng/internal/_build/results?buildId=2056448&view=results):

```
[2022/11/30 04:47:28][INFO] WorkloadActual  14: 15 op, 237789001.00 ns, 15.8526 ms/op
[2022/11/30 04:47:28][INFO] WorkloadActual  15: 15 op, 237506001.00 ns, 15.8337 ms/op
[2022/11/30 04:47:28][INFO] OutOfMemoryException!
[2022/11/30 04:47:28][INFO] BenchmarkDotNet continues to run additional iterations until desired accuracy level is achieved. It's possible only if the benchmark method doesn't have any side-effects.
[2022/11/30 04:47:28][INFO] If your benchmark allocates memory and keeps it alive, you are creating a memory leak.
[2022/11/30 04:47:28][INFO] You should redesign your benchmark and remove the side-effects. You can use `OperationsPerInvoke`, `IterationSetup` and `IterationCleanup` to do that.
[2022/11/30 04:47:28][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/11/30 04:47:28][INFO]  ---> System.OutOfMemoryException: Out of memory
[2022/11/30 04:47:28][INFO]    at System.IO.File.ReadAllBytes(String )
[2022/11/30 04:47:28][INFO]    at System.IO.Tests.Perf_File.ReadAllBytes(Int32 size)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_49.WorkloadActionNoUnroll(Int64 invokeCount)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Engines.EngineStage.RunIteration(IterationMode mode, IterationStage stage, Int32 index, Int64 invokeCount, Int32 unrollFactor)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Engines.EngineActualStage.RunAuto(Int64 invokeCount, IterationMode iterationMode, Int32 unrollFactor)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Engines.EngineActualStage.Run(Int64 invokeCount, IterationMode iterationMode, Boolean runAuto, Int32 unrollFactor, Boolean forceSpecific)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Engines.EngineActualStage.RunWorkload(Int64 invokeCount, Int32 unrollFactor, Boolean forceSpecific)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Engines.Engine.Run()
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_49.Run(IHost host, String benchmarkName)
[2022/11/30 04:47:28][INFO]    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
[2022/11/30 04:47:28][INFO]    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
[2022/11/30 04:47:28][INFO]    --- End of inner exception stack trace ---
[2022/11/30 04:47:28][INFO]    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
[2022/11/30 04:47:28][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
[2022/11/30 04:47:28][INFO]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
[2022/11/30 04:47:28][INFO]    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
[2022/11/30 04:47:28][INFO] // AfterAll
[2022/11/30 04:47:28][INFO] {"name":"ExitStatus","message":"Program terminated with exit(-1)","status":-1}
[2022/11/30 04:47:28][INFO] WASM EXIT -1
```

- The [changes](https://github.com/dotnet/runtime/compare/8ccdb1cd29754ed64a451300cd1fc59d35b88d40...f1a42cf6) since the [last working build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2056196&view=results).
- The last change in `dotnet/performance` repo was 2 days ago, so before either of these builds.
- The good build (`20221129.11`) used `v8 11.0.127`, and the bad one (`20221129.14`) used `v8 v11.0.131` .

cc @radekdoulik

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
Looks like `20221129.11` also had the same failure, but it didn't get show up in kusto :/

**Comment by radical** [comment]
Update:

1. the [last working build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2055730&view=results) is `20221129.6`
2. Diff - [20221129.6 .. 2022129.14](https://github.com/dotnet/runtime/compare/d4d12c5563621db5ed31abaeb0143bf30c2d53d3...f1a42cf6)

Also, in a subsequent run - [20221130.1](https://dev.azure.com/dnceng/internal/_build/results?buildId=2056710&view=results) the benchmark did not fail.

cc @adamsitnik @LoopedBard3

**Comment by adamsitnik** [comment]
@radical were you able to reproduce it locally? I just looked at the benchmark and the maximum amount of memory it can be holding at the same time is 200 MB (100 for the previous result and 100 for the currently executed benchmark). Does WASM/v8 have any specific memory limitations?

**Comment by radical** [comment]
> @radical were you able to reproduce it locally? I just looked at the benchmark and the maximum amount of memory it can be holding at the same time is 200 MB (100 for the previous result and 100 for the currently executed benchmark). Does WASM/v8 have any specific memory limitations?
> 
> From the commits range you have provided nothing looks suspicious to me.

I will try to reproduce this locally today.

**Comment by radical** [comment]
This hasn't been hit in the last two months, so closing it.
