### ISSUE TITLE
SslStream does not have Read override with Span

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#79072]
I bump to it when investigating #78586
The exception looks like:
```
Unhandled exception. System.NotSupportedException:  This method may not be called when another read operation is pending.
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.Read(Span`1 destination)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
```

Because the overload is missing, we hit the base class that would rent buffer, read to it and then copy data over to the span.

https://github.com/dotnet/runtime/blob/067e43a1363f6d1748acc679f1804cd48299ba89/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L790-L808

**Comment by MihaZupan** [comment]
Is the alternative to cache `PointerMemoryManager`s instead? It may be cheaper than an extra memory copy.

**Comment by wfurt** [comment]
I think we should add the overload to `SslStream` (and `NegotiateStream`). I'm not sure if this is omission from when we added `Span` or if there is reason behind it. Perhaps @stephentoub would remember.

**Comment by stephentoub** [comment]
This gets to Miha's question.  The logic in SslStream is shared between sync and async and implemented in terms of a ReadOnlyMemory.  Our options then are either:
(1) Resplit all the logic to have separate sync and async code paths
(2) Pool MemoryManager instances to be able to a pinned ReadOnlySpan via the ROM code path
(3) Use pooled buffers via ArrayPool

We're currently doing (3).  Since only one read at a time is supported, anyway, seems reasonable to switch to (2), as we should only ever need a single instance per stream.

**Comment by rzikm** [comment]
Triage: possible perf improvement, not critical for 8.0 so putting in Future for now.
