### ISSUE TITLE
[wasm][debugger] `DebuggerTests.CallFunctionOnTests.InvalidPropertyGetters` timed out on rolling builds

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#79100]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=98062&view=results):

```
[xUnit.net 00:04:37.13]     DebuggerTests.CallFunctionOnTests.InvalidPropertyGetters(eval_fn: "negative_cfo_test ();", bp_loc: "/other.js", line: 64, col: 1, use_cfo: False) [FAIL]
  Failed DebuggerTests.CallFunctionOnTests.InvalidPropertyGetters(eval_fn: "negative_cfo_test ();", bp_loc: "/other.js", line: 64, col: 1, use_cfo: False) [55 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 60.0018026)
  Stack Trace:
     at DebuggerTests.CallFunctionOnTests.InvalidPropertyGetters(String eval_fn, String bp_loc, Int32 line, Int32 col, Boolean use_cfo) in /_/src/mono/wasm/debugger/DebuggerTestSuite/CallFunctionOnTests.cs:line 835
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Information: [testId: 42] New test request for test id 42
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: [42] Starting /datadisks/disk1/work/A7B20943/p/chrome-linux/chrome with --headless --disable-gpu --lang=en-US --incognito --remote-debugging-port=0 http://localhost:9400/debugger-driver.html
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: [testId: 41] TestHarnessStartup done
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 41
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: [testId: 42] browser-stderr 
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: [testId: 42] browser-stderr DevTools listening on ws://127.0.0.1:34379/devtools/browser/f4617881-394a-45e0-886f-5ed32116b3cc
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: [testId: 42] browser-stderr [1130/204304.927718:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
 | [2022-11-30T20:43:04] DebuggerTests.TestHarnessProxy Debug: [testId: 42] browser-stderr [1130/204304.958964:WARNING:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
 | [2022-11-30T20:43:05] DebuggerTests.TestHarnessProxy Information: [testId: 42] launching proxy for ws://127.0.0.1:34379/devtools/page/76481407C59B95A05909F92E9318C709
 | [2022-11-30T20:43:05] Inspector-42 Information: waiting for the runtime to be ready
 | [2022-11-30T20:43:09] Inspector-42 Information: runtime ready, TEST TIME
 | [2022-11-30T20:43:09] Inspector-42 Information: console.log: ready
```

- [proxy log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-0d8d224d073b46b7b1/chrome-DebuggerTests.CallFunctionOnTests/1/xharness-output/logs/proxy-20221130.log?helixlogtype=result)
- Looking at the proxy log, it does pause:
`2022-11-30T20:43:09.1052307+00:00 [VRB] DevToolsProxy-42: to-ide:`
```json
{
  "method": "Debugger.paused",
  "params": {
    "callFrames": [
      {
        "callFrameId": "2527198315647271032.1.0",
        "functionName": "negative_cfo_test",
        "functionLocation": {
          "scriptId": "4",
          "lineNumber": 54,
          "columnNumber": 27
        },
        "location": {
          "scriptId": "4",
          "lineNumber": 64,
          "columnNumber": 1
        },
        "url": "",
        "scopeChain": [
          {
            "type": "block",
            "object": {
              "type": "object",
              "className": "Object",
              "description": "Object",
              "objectId": "2527198315647271032.1.9"
            },
            "name": "negative_cfo_test",
            "startLocation": {
              "scriptId": "4",
              "lineNumber": 54,
              "columnNumber": 46
            },
            "endLocation": {
              "scriptId": "4",
              "lineNumber": 66,
              "columnNumber": 1
            }
          },
          {
            "type": "local",
            "object": {
              "type": "object",
              "className": "Object",
              "description": "Object",
              "objectId": "2527198315647271032.1.10"
            },
            "name": "negative_cfo_test",
            "startLocation": {
              "scriptId": "4",
              "lineNumber": 54,
              "columnNumber": 27
            },
            "endLocation": {
              "scriptId": "4",
              "lineNumber": 66,
              "columnNumber": 1
            }
          },
          {
            "type": "global",
            "object": {
              "type": "object",
              "className": "Window",
              "description": "Window",
              "objectId": "2527198315647271032.1.11"
            }
          }
        ],
        "this": {
          "type": "undefined"
        },
        "canBeRestarted": true
      },
      {
        "callFrameId": "2527198315647271032.1.1",
        "functionName": "",
        "functionLocation": {
          "scriptId": "69",
          "lineNumber": 0,
          "columnNumber": 26
        },
        "location": {
          "scriptId": "69",
          "lineNumber": 0,
          "columnNumber": 31
        },
        "url": "",
        "scopeChain": [
          {
            "type": "local",
            "object": {
              "type": "object",
              "className": "Object",
              "description": "Object",
              "objectId": "2527198315647271032.1.12"
            },
            "startLocation": {
              "scriptId": "69",
              "lineNumber": 0,
              "columnNumber": 26
            },
            "endLocation": {
              "scriptId": "69",
              "lineNumber": 0,
              "columnNumber": 54
            }
          },
          {
            "type": "global",
            "object": {
              "type": "object",
              "className": "Window",
              "description": "Window",
              "objectId": "2527198315647271032.1.13"
            }
          }
        ],
        "this": {
          "type": "object",
          "className": "Window",
          "description": "Window",
          "objectId": "2527198315647271032.1.14"
        },
        "canBeRestarted": true
      }
    ],
    "reason": "other",
    "hitBreakpoints": [
      "1:64:1:http://localhost:9400/other.js"
    ]
  }
}
```

- but then the test times out anyway after ~50s:
```
2022-11-30T20:44:04.8290139+00:00 [DBG] DevToolsProxy-42: RunLoop stopped, reason: RunLoopExitState { reason = ConnectionClosed, exception = System.Exception: Connection id: ide
 ---> System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.WebAssembly.Diagnostics.DevToolsDebuggerConnection.ReadOneAsync(CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Common/DevToolsDebuggerConnection.cs:line 43
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace --- }
2
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
note: the subsequent rolling build didn't have this failure, so it is intermittent.

**Comment by steveisok** [comment]
@radical is the blocking-clean-ci label still needed?

**Comment by radical** [comment]
No, I have removed it.
