### ISSUE TITLE
Test failure JIT\\Performance\\CodeQuality\\Serialization\\Serialize\\Serialize.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#79132]
Run: [runtime-coreclr jitstress 20221130.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=98546&view=ms.vss-test-web.build-test-results-tab&runId=2103462&resultId=119743&paneView=debug)

Failed test:
```
coreclr windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Serialization\\Serialize\\Serialize.cmd

coreclr Linux x64 Checked jitstress2_tiered @ Ubuntu.1804.Amd64.Open
- JIT/superpmi/superpmicollect/superpmicollect.sh
- readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh
- Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh
- JIT/superpmi/superpmicollect/CscBench/CscBench.sh
- baseservices/RuntimeConfiguration/TestConfig/TestConfig.sh
- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh

coreclr windows x64 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
... ...

coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- JIT\\Performance\\CodeQuality\\Serialization\\Serialize\\Serialize.cmd
- JIT\\Regression\\JitBlue\\Runtime_63354\\Runtime_63354\\Runtime_63354.cmd

coreclr Linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open
- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- readytorun/tests/mainv2/mainv2.sh
- readytorun/tests/mainv1/mainv1.sh
- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
- baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh
... ...

coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd
- Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
... ...

coreclr Linux x64 Checked jitstress1 @ Ubuntu.1804.Amd64.Open
- JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh

coreclr windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd

coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_63354\\Runtime_63354\\Runtime_63354.cmd

coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
... ...

coreclr OSX x64 Checked jitstress1 @ OSX.1200.Amd64.Open
- JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh

coreclr OSX x64 Checked jitstress2 @ OSX.1200.Amd64.Open
- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- profiler/gc/gc/gc.sh
- profiler/gc/gcallocate/gcallocate.sh
- profiler/gc/gcbasic/gcbasic.sh
- JIT/superpmi/superpmicollect/superpmicollect.sh
... ...
```
**Error message:**
```
Assert failure(PID 5436 [0x0000153c], Thread: 5084 [0x13dc]): Assertion failed '((id->idGCref() == GCT_BYREF) && (ins == INS_add || ins == INS_sub || ins == INS_sub_hide || insIsCMOV(ins))) || ((id->idGCref() == GCT_GCREF) && insIsCMOV(ins))' in 'Newtonsoft.Json.JsonTextWriter:UpdateCharEscapeFlags():this' during 'Emit code' (IL size 24; hash 0x946d0be0; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 12179
Image: C:\h\w\9ABC08B8\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\9ABC08B8\w\A4A20943\uploads\Reports\JIT.Performance\CodeQuality\Serialization\Serialize\Serialize.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\9ABC08B8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Serialize.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\9ABC08B8\p
C:\h\w\9ABC08B8\w\A4A20943\e\JIT\Performance\CodeQuality\Serialization\Serialize\Serialize.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Performance._CodeQuality_Serialization_Serialize_Serialize_._CodeQuality_Serialization_Serialize_Serialize_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
@kunalspathak @dotnet/jit-contrib jitstress is very broken

**Comment by kunalspathak** [comment]
The assert seems to be introduced in #78879. Will take a look.
