### ISSUE TITLE
System.Text.Json.Serialization.Tests.NumberHandlingTests.Number_AsCollectionElement_RoundTrip failing in jitstress

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#79290]
Tests: https://dev.azure.com/dnceng-public/public/_build/results?buildId=102920&view=ms.vss-test-web.build-test-results-tab
Console: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fe79a38bc4a94a9a8b/System.Text.Json.Tests/1/console.e9ac5927.log?helixlogtype=result

```scala
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 5511 of 5577 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 4)
    System.Text.Json.Serialization.Tests.NumberHandlingTests.Number_AsCollectionElement_RoundTrip [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/NumberHandlingTests.cs(537,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.RunAllCollectionsRoundTripTest[T](String json)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/NumberHandlingTests.cs(445,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.RunAsCollectionElementTest[T](List`1 numbers)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/NumberHandlingTests.cs(382,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.Number_AsCollectionElement_RoundTrip()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    System.Text.Json.Tests
```

It is failing on both x64/x86. Looks related to if conversion/GT_SELECT. Likely the other failures have the same root cause, but I haven't checked.

**Comment by jakobbotsch** [comment]
Bisected it to 712aed5d which is ``System.Collections.Generic.HashSet`1[System.Nullable`1[short]]:FindItemIndex(System.Nullable`1[short]):int:this``, so very likely the other failures are the same root cause given the mention of nullable.

Snip of diff:
```diff
@@ -26,8 +26,8 @@
 ;  V13 tmp1         [V13,T31] (  3,  1.50)     int  ->  r14        
 ;* V14 tmp2         [V14    ] (  0,  0   )    bool  ->  zero-ref    "Inlining Arg"
 ;* V15 tmp3         [V15    ] (  0,  0   )    bool  ->  zero-ref    "Inlining Arg"
-;  V16 tmp4         [V16,T32] (  3,  1.50)     int  ->  r15         "Inline return value spill temp"
-;  V17 tmp5         [V17,T35] (  2,  1   )   byref  ->  rcx         single-def "Inline return value spill temp"
+;  V16 tmp4         [V16,T36] (  2,  1   )     int  ->  r15         "Inline return value spill temp"
+;  V17 tmp5         [V17,T34] (  2,  1   )   byref  ->  rcx         single-def "Inline return value spill temp"
 ;  V18 tmp6         [V18,T29] (  3,  1.50)     ref  ->  rbp         class-hnd "Inline stloc first use temp"
 ;  V19 tmp7         [V19,T18] (  4,  4   )     int  ->  r13         "Inlining Arg"
 ;  V20 tmp8         [V20,T27] (  2,  2   )    long  ->  rsi         "Inlining Arg"
@@ -43,7 +43,7 @@
 ;  V30 tmp18        [V30,T13] (  2,  8   )   short  ->  rcx         "Inlining Arg"
 ;* V31 tmp19        [V31    ] (  0,  0   )    bool  ->  zero-ref    "Inlining Arg"
 ;* V32 tmp20        [V32    ] (  0,  0   )    bool  ->  zero-ref    "Inlining Arg"
-;  V33 tmp21        [V33,T36] (  2,  1   )   byref  ->  rdx         single-def "Inline return value spill temp"
+;  V33 tmp21        [V33,T35] (  2,  1   )   byref  ->  rdx         single-def "Inline return value spill temp"
 ;  V34 tmp22        [V34,T30] (  3,  1.50)     ref  ->  r15         class-hnd "Inline stloc first use temp"
 ;  V35 tmp23        [V35,T19] (  4,  4   )     int  ->  r13         "Inlining Arg"
 ;  V36 tmp24        [V36,T28] (  2,  2   )    long  ->  rsi         "Inlining Arg"
@@ -56,11 +56,11 @@
 ;  V43 tmp31        [V43,T02] (  3, 20   )    bool  ->   r9         V27.hasValue(offs=0x00) P-INDEP "field V27.hasValue (fldOffset=0x0)"
 ;  V44 tmp32        [V44,T23] (  2,  4   )   short  ->  r10         V27.value(offs=0x02) P-INDEP "field V27.value (fldOffset=0x2)"
 ;  V45 tmp33        [V45,T09] (  3, 12   )   byref  ->  rcx         "BlockOp address local"
-;  V46 cse0         [V46,T33] (  3,  1.50)     int  ->  r12         "CSE - moderate"
-;  V47 cse1         [V47,T34] (  3,  1.50)     int  ->  r12         "CSE - moderate"
+;  V46 cse0         [V46,T32] (  3,  1.50)     int  ->  r12         "CSE - stress mode"
+;  V47 cse1         [V47,T33] (  3,  1.50)     int  ->  r12         "CSE - moderate"
 ;  V48 cse2         [V48,T17] (  5,  4   )     int  ->  r14         "CSE - moderate"
 ;  V49 cse3         [V49,T01] (  6, 20.50)     int  ->  registers   "CSE - aggressive"
-;  V50 cse4         [V50,T14] ( 14,  7   )     ref  ->  rdx         "CSE - aggressive"
+;  V50 cse4         [V50,T14] ( 14,  7   )     ref  ->  rdx         "CSE - stress mode"
 ;
 ; Lcl frame size = 40
 
@@ -79,7 +79,7 @@ G_M4770_IG01:
 						;; size=24 bbWeight=1    PerfScore 9.50
 G_M4770_IG02:
        cmp      gword ptr [rsi+08H], 0
-       je       G_M4770_IG25
+       je       G_M4770_IG23
 						;; size=11 bbWeight=1    PerfScore 4.00
 G_M4770_IG03:
        mov      rdi, gword ptr [rsi+10H]
@@ -95,30 +95,26 @@ G_M4770_IG04:
        xor      ebx, ebx
        mov      rbp, gword ptr [rsi+18H]
        test     rbp, rbp
-       jne      G_M4770_IG17
+       jne      G_M4770_IG15
        movzx    r14, byte  ptr [rsp+78H]
+       xor      ecx, ecx
        test     r14d, r14d
-       jne      SHORT G_M4770_IG05
+       setne    cl
        xor      r15d, r15d
-       jmp      SHORT G_M4770_IG06
-       align    [0 bytes for IG09]
-						;; size=31 bbWeight=0.50 PerfScore 4.00
-G_M4770_IG05:
-       movsx    r15, word  ptr [rsp+7AH]
-						;; size=6 bbWeight=0.50 PerfScore 1.50
-G_M4770_IG06:
+       test     ecx, ecx
+       cmovne   r15d, dword ptr [rsp+7AH]
        mov      rbp, gword ptr [rsi+08H]
        mov      r12d, dword ptr [rbp+08H]
        mov      r13d, r12d
        mov      rsi, qword ptr [rsi+20H]
        test     r13d, r13d
```

Looks like there is some incorrect handling (maybe related to containment?) of the operands.
