### ISSUE TITLE
Mutex ctor will often throw IOException immediately after macOS reboot

### ISSUE THREAD

**Issue by darthwalsh** [dotnet/runtime#79375]
### Description

The call `new  System.Threading.Mutex(false, "some_text")` running in multiple processes will throw `System.IO.IOException The system cannot open the device or file specified. : 'some_text'` maybe 30% of the time after I've rebooted my macbook.

This seems to be the root cause of PowerShell/PSReadLine#2658, as `pwsh` PSReadLine process attempts to use a Mutex during setup.

### Reproduction Steps

Create a new `net6.0` console app that 
* calls Mutex ctor
* prints an exception if it happened
* stays open to show output

Program.cs: 
```csharp
try {
  using (var m = new Mutex(false, "darthwalsh_PSReadLine_issues_2658")) {
    Console.Write("created but didn't take Mutex darthwalsh_PSReadLine_issues_2658   ...");
    var line = Console.ReadLine();
    Console.WriteLine("QUITTING: " + line);
  }
} catch (Exception e) {
  Console.WriteLine(e.ToString());

  var line = Console.ReadLine();
  Console.WriteLine("QUITTING: " + line);
}
```

Build with `dotnet publish -c Release --self-contained -a x64`

Created a new iTerm2 profile that only runs the compiled output, i.e. `/Users/walshca/code/temp/MutexThrow/bin/Release/net6.0/osx-x64/publish/MutexThrow` and open this profile in **10** tabs, each split into **12** instances. (Having 120 processes in parallel is likely overkill, but it seems to guarantee a repro.) (see Actual image)

Ensure iTerm2 is set up to relaunch with the same tabs.

Reboot macOS. Log in. Find iTerm. Look through all tabs at output messages.

### Expected behavior

120x messages of `created but didn't take Mutex darthwalsh_PSReadLine_issues_2658   ...` with no exceptions

### Actual behavior

Out of 120 processes, index 0, 2, 5, and 12 failed with message:

```
System.IO.IOException: The system cannot open the device or file specified. : 'darthwalsh_PSReadLine_issues_2658'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Program.<Main>$(String[] args) in /Users/walshca/code/temp/MutexThrow/Program.cs:line 2
```

![image](https://user-images.githubusercontent.com/2829438/206332123-2fa32518-c391-4e06-90af-f176cf806456.png)

(the screenshot shows the failures, then a couple attempts to reproduce the problem by ownly logging out without rebooting, which did not trigger it.)

### Known Workarounds

The conversation in PowerShell/PSReadLine#2658 discussed whether catching and retrying the exception should be tried, but it's unclear what is causing Mutex ctor to throw.

### Configuration

- Build with dotnet `6.0.822.36306`
- macOS Monterey 12.6.1 21G217 
- x64 2.3 GHz 8-Core Intel Core i9
- It seems likely OS-specific, unknown about arch or build flags

### Other information

A related problem dotnet/runtime#36823 can happen if the `/tmp` permissions are incorrect, but that's not the case here.

The [Mutex.ctor() API docs](https://learn.microsoft.com/en-us/dotnet/api/system.threading.mutex.-ctor?view=net-7.0) isn't clear if this exception is expected and transient, and we should try to catch it and retry Mutex creation?

**Comment by mangod9** [comment]
@kouvel. Does this repro consistently for you @darthwalsh ?

**Comment by darthwalsh** [comment]
@mangod9 I've kept my repo running through a few more reboots. The first two reboots each had 3 thrown exceptions. The last reboot had 0 exceptions. So during OS startup with dozens of dotnet processes, I'd expect to see a crash about 90% of the time.

Is there any more investigation I can do to help move this issue forward?

Also, do we have a rough idea of what the fix will be? i.e. maybe Mutex ctor() is changed to somehow not throw (i.e. retry on file access error)? Or, would the docs on MSDN be updated to say some exceptions are expected in this situation?

**Comment by darthwalsh** [comment]
Continuing to update this, my macbook updated to 13.2 Ventura. I am monitoring with 16 processes starting in iTerm. I haven't had the issue on the two reboots since OS upgrade, but I'm not confident about the cause: Did 13.2 fix something? Did the OS change something about how soon applications are started after booting? Did the race condition get lucky twice in a row?

It will still be helpful to get an update to the docs about the exception policy, whether or not this specific issue will not reproduce again.

**Comment by darthwalsh** [comment]
Continuing to update this, I've since upgraded to macOS 14.1.2 and still regularly see this, as recently as November. I'm not sure if there's a better way to look at the data, but global-find-substring shows I have seen this error a total of 136 times in my iTerm history in the last 10 months.

I'll be upgrading to an Apple Silicon macbook, and probably won't keep trying to reproduce the issue. As long as dotnet core supports macOS on Intel chips this feels worth fixing :)

**Comment by darthwalsh** [comment]
On Apple Silicon I got a very similar error (different message, but same exception type). This happened right after rebooting, and my terminal opened a dozen instances of `pwsh` at the same time

```
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2886463743'. One or more system calls failed: stat("/tmp/.dotnet/shm", ...) == -1; errno == ENOENT;
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

system info:
```
$ sw_vers
ProductName:		macOS
ProductVersion:		15.5
BuildVersion:		24F74

$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.1
PSEdition                      Core
GitCommitId                    7.5.1
OS                             Darwin 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:29 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6030
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
