### ISSUE TITLE
Test failure ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#79431]
Run: [runtime-coreclr gcstress-extra 20221208.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106070&view=ms.vss-test-web.build-test-results-tab&runId=2271196&resultId=122031&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_zapdisable @ Windows.10.Arm64v8.Open

- ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd

coreclr windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- JIT\\Regression\\JitBlue\\Runtime_45557\\Runtime_45557\\Runtime_45557.cmd
```

**Error message:**
```
Assert failure(PID 11016 [0x00002b08], Thread: 13944 [0x3678]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner'::1'::catch$12 + 0x138 (0x00007fff23436698) CORECLR! CallSettingFrame + 0x68 (0x00007fff22e82e60)
CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x134 (0x00007fff23393544) NTDLL! RtlRestoreContext + 0xEC (0x00007fff69fe369c)
CORECLR! Object::ValidateInner + 0x144 (0x00007fff22f7763c) CORECLR! Object::Validate + 0xA4 (0x00007fff22f7743c)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007fff2318c898) CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x1274 (0x00007fff2318b6ac)
CORECLR! EECodeManager::EnumGcRefs + 0x2D0 (0x00007fff22eea470) CORECLR! GcStackCrawlCallBack + 0x434 (0x00007fff230499b4)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: D:\h\w\B3B209DA\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\B3B209DA\w\A5E508F1\uploads\Reports\ilasm.PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B3B209DA\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  IlasmPortablePdbTests.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B3B209DA\p
D:\h\w\B3B209DA\w\A5E508F1\e\ilasm\PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.cmd
Expected: True
Actual:   False


Stack trace
   at ilasm_PortablePdb._IlasmPortablePdbTests_IlasmPortablePdbTests_._IlasmPortablePdbTests_IlasmPortablePdbTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
@TIHan PTAL.

**Comment by TIHan** [comment]
Having a hard time reproducing this one. Here is how I'm trying to reproduce it:

```cmd
@REM Temporary test env for test run.
@echo on
set DOTNETCLI=c:\work\runtime\src\tests\..\..\dotnet.cmd
set DOTNETPATH=C:\Program Files\dotnet
set DOTNET_GCSTRESS=0xc
set DOTNET_MULTILEVEL_LOOKUP=0
set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
set DOTNET_ZAPDISABLE=1
set __DOTNET_ADD_32BIT=1
set __DOTNET_PREFERRED_BITNESS=32
@echo off


Running GCStress, extending test timeout to cater for slower runtime.
Setting __TestTimeout=14400000
Setting CORE_ROOT=c:\work\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
Setting __TestEnv=C:\Users\will\AppData\Local\Temp\tmpr743tpr9.bat
c:\work\runtime\dotnet.cmd msbuild c:\work\runtime\src\tests\build.proj /t:RunTests /clp:showcommandline /fileloggerparameters:"Verbosity=normal;LogFile=c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.log" /fileloggerparameters1:"WarningsOnly;LogFile=c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.wrn" /fileloggerparameters2:"ErrorsOnly;LogFile=c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.err" /consoleloggerparameters:Summary /p:TargetOS=windows /p:TargetArchitecture=x64 /p:Configuration=Checked /p:__LogsDir=c:\work\runtime\artifacts\log /bl:c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.binlog
C:\Program Files\dotnet
MSBuild version 17.4.0+18d5aef85 for .NET
C:\Program Files\dotnet\sdk\7.0.100\MSBuild.dll -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.100\dotnet.dll -maxcpucount -verbosity:m /bl:c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.binlog /clp:showcommandline /consoleloggerparameters:Summary /fileloggerparameters1:WarningsOnly;LogFile=c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.wrn /fileloggerparameters2:ErrorsOnly;LogFile=c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.err /fileloggerparameters:Verbosity=normal;LogFile=c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked.log /p:TargetOS=windows /p:TargetArchitecture=x64 /p:Configuration=Checked /p:__LogsDir=c:\work\runtime\artifacts\log /t:RunTests c:\work\runtime\src\tests\build.proj
  "c:\work\runtime\\dotnet.cmd" --roll-forward latestmajor c:\work\runtime\artifacts\tests\coreclr\windows.x64.Checked\
  Tests\Core_Root\xunit\xunit.console.dll .\ilasm\PortablePdb\ilasm.PortablePdb.XUnitWrapper.dll -parallel collections
  -html c:\work\runtime\artifacts\log\TestRun.html -xml c:\work\runtime\artifacts\log\TestRun.xml  -notrait category=ou
  terloop -notrait category=failing -nocolor
  C:\Program Files\dotnet
  Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0)
    Discovering: ilasm.PortablePdb.XUnitWrapper (method display = ClassAndMethod, method display options = None)
    Discovered:  ilasm.PortablePdb.XUnitWrapper (found 1 test case)
    Starting:    ilasm.PortablePdb.XUnitWrapper (parallel test collections = on, max threads = 32)
    Finished:    ilasm.PortablePdb.XUnitWrapper
  === TEST EXECUTION SUMMARY ===
     ilasm.PortablePdb.XUnitWrapper  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 3.487s

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.25
Test run finished.
Parsing test results from (c:\work\runtime\artifacts\log\TestRunResults_windows_x64_Checked)
Analyzing c:\work\runtime\artifacts\log\TestRun.xml
Time [secs] | Total | Passed | Failed | Skipped | Assembly Execution Summary
============================================================================
      3.487 |     1 |      1 |      0 |       0 | ilasm.PortablePdb.XUnitWrapper.dll
----------------------------------------------------------------------------
      3.487 |     1 |      1 |      0 |       0 | (total)
```

**Comment by v-wenyuxu** [comment]
Failed again: [runtime-coreclr gcstress-extra 20221217.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=115496&view=ms.vss-test-web.build-test-results-tab&runId=2443490&resultId=217326&paneView=debug)

Failed test:
```
coreclr windows x64 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open

- JIT\\Regression\\JitBlue\\Runtime_45557\\Runtime_45557\\Runtime_45557.cmd

coreclr windows arm64 Checked gcstress0xc_jitstress1 @ Windows.10.Arm64v8.Open

- Interop\\COM\\ComWrappers\\WeakReference\\WeakReferenceTest\\WeakReferenceTest.cmd
```
**Error message:**
```
Assert failure(PID 3792 [0x00000ed0], Thread: 5976 [0x1758]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner'::1'::catch$12 + 0x142 (0x00007ffcb382ab02) CORECLR! CallSettingFrame_LookupContinuationIndex + 0x20 (0x00007ffcb377fbf0)
CORECLR! _FrameHandler4::CxxCallCatchBlock + 0x1DE (0x00007ffcb377db6e) NTDLL! RtlCaptureContext + 0x3C3 (0x00007ffce3179d73)
CORECLR! Object::ValidateInner + 0x104 (0x00007ffcb3028ee4) CORECLR! Object::Validate + 0xA1 (0x00007ffcb3028da1)
CORECLR! GcInfoDecoder::ReportStackSlotToGC + 0x139 (0x00007ffcb34d1519) CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x131F (0x00007ffcb34d01cf)
CORECLR! EECodeManager::EnumGcRefs + 0x395 (0x00007ffcb2f02fb5) CORECLR! GcStackCrawlCallBack + 0x3C9 (0x00007ffcb31c74c9)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: C:\h\w\AD5909C4\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\AD5909C4\w\9FDC08FB\uploads\Reports\JIT.Regression\JitBlue\Runtime_45557\Runtime_45557\Runtime_45557.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AD5909C4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Runtime_45557.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AD5909C4\p
C:\h\w\AD5909C4\w\9FDC08FB\e\JIT\Regression\JitBlue\Runtime_45557\Runtime_45557\Runtime_45557.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_45557_Runtime_45557_Runtime_45557_._JitBlue_Runtime_45557_Runtime_45557_Runtime_45557_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr gcstress-extra 20230101.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=122270&view=ms.vss-test-web.build-test-results-tab&runId=2624696&resultId=102088&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_jitstress1 @ Windows.11.Arm64.Open

- Interop\\COM\\ComWrappers\\WeakReference\\WeakReferenceTest\\WeakReferenceTest.cmd

coreclr windows arm64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.11.Arm64.Open

- JIT\\Performance\\CodeQuality\\BenchmarksGame\\fasta\\fasta-1\\fasta-1.cmd
```
**Error message:**
```
Assert failure(PID 8212 [0x00002014], Thread: 8528 [0x2150]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner'::1'::catch$12 + 0x138 (0x00007ff846954f7c) CORECLR! CallSettingFrame + 0x68 (0x00007ff8463a2e60)
CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x134 (0x00007ff8468b1e14) NTDLL! RtlCaptureContext + 0x1B8 (0x00007ff8ae6c2248)
CORECLR! Object::ValidateInner + 0x144 (0x00007ff846496b7c) CORECLR! OBJECTREF::OBJECTREF + 0x118 (0x00007ff846492560)
CORECLR! MarshalNative::GCHandleInternalGet + 0x40 (0x00007ff8465a0580) <no module>! <no symbol> + 0x0 (0x00007ff7e6e94260)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: C:\h\w\B5A70902\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\B5A70902\w\BB090A34\uploads\Reports\Interop.COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B5A70902\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  WeakReferenceTest.dll
Running ValidateNonComWrappers...
Running ValidateGlobalInstanceMarshalling...
-- Validate weak reference creation
-- Validate RCW recreation
-- Validate release
-- Validate target reset
-- Validate RCW recreation
-- Validate release
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B5A70902\p
C:\h\w\B5A70902\w\BB090A34\e\Interop\COM\ComWrappers\WeakReference\WeakReferenceTest\WeakReferenceTest.cmd
Expected: True
Actual:   False


Stack trace
   at Interop_COM._ComWrappers_WeakReference_WeakReferenceTest_WeakReferenceTest_._ComWrappers_WeakReference_WeakReferenceTest_WeakReferenceTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
Note that the tests which original failed didn't fail in the latest report. It might be worthwhile to change the issue title to represent the current test(s).

**Comment by v-wenyuxu** [comment]
Run: [runtime-coreclr outerloop 20230116.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=139053&view=ms.vss-test-web.build-test-results-tab&runId=3020124&resultId=122019&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open

- tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd

R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open

- tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd

coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open

- tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd

coreclr windows arm Checked @ Windows.11.Arm64.Open

- tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd
```
**Error message:**
```
Assert failure(PID 4796 [0x000012bc], Thread: 7988 [0x1f34]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

<no module>! <no symbol> + 0x0 (0x00000000)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: C:\h\w\A66E091C\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A66E091C\w\B77D099F\uploads\Reports\tracing.eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.output.txt
Raw output:
BEGIN EXECUTION
common.dll
eventsourceerror.dll
Microsoft.Diagnostics.NETCore.Client.dll
3 file(s) copied.
20:46:21.50
Response file: C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll.rsp
C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2\common.dll
-o:C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A66E091C\p\System..dll
-r:C:\h\w\A66E091C\p\Microsoft..dll
-r:C:\h\w\A66E091C\p\mscorlib.dll
-r:C:\h\w\A66E091C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A66E091C\p\crossgen2\crossgen2.dll" @"C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll.rsp"   -r:C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll
" "dotnet" "C:\h\w\A66E091C\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll --out C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll.r2rdump --val"
20:46:24.49
20:46:24.49
Response file: C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll.rsp
C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2\eventsourceerror.dll
-o:C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A66E091C\p\System..dll
-r:C:\h\w\A66E091C\p\Microsoft..dll
-r:C:\h\w\A66E091C\p\mscorlib.dll
-r:C:\h\w\A66E091C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A66E091C\p\crossgen2\crossgen2.dll" @"C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll.rsp"   -r:C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll
" "dotnet" "C:\h\w\A66E091C\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll --out C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll.r2rdump --val"
20:46:27.47
20:46:27.47
Response file: C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\Microsoft.Diagnostics.NETCore.Client.dll.rsp
C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2\Microsoft.Diagnostics.NETCore.Client.dll
-o:C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\Microsoft.Diagnostics.NETCore.Client.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A66E091C\p\System..dll
-r:C:\h\w\A66E091C\p\Microsoft..dll
-r:C:\h\w\A66E091C\p\mscorlib.dll
-r:C:\h\w\A66E091C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A66E091C\p\crossgen2\crossgen2.dll" @"C:\h\w\A66E091C\w\B77D099F\e\tracing\eventpipe\eventsourceerror\eventsourceerror\Microsoft.Diagnostics.NETCore.Client.dll.rsp"   -r:C:\h\w\A66E091C\w\B77D099F\e\tracing


Stack trace
   at tracing_eventpipe._eventsourceerror_eventsourceerror_eventsourceerror_._eventsourceerror_eventsourceerror_eventsourceerror_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment]
> Seems like this should result in codegen of swpal x20, x0, [x1], the current codegen instead swaps [x1] with garbage and overwrites x0.

Nope, turns out that these instructions actually write the middle operand register and swap the first and last registers. So the codegen seems right, but the GC update is wrong:
```
                             ; gcrRegs +[x0]
```
This should be adding `x20` as a new GC register then.
