### ISSUE TITLE
[wasm] Wasm.Build.Tests - blazor run tests failing

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#79514]
Update: Revisit this to enable the tests once https://github.com/dotnet/aspnetcore/issues/45492 is merged.

[Wasm.Build.Tests.Blazor.BuildPublishTests](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-312d817ac7e84f22b7/Workloads-Wasm.Build.Tests.Blazor.BuildPublishTests/1/console.c5bb1e38.log?helixlogtype=result):

```
   Wasm.Build.Tests.Blazor.BuildPublishTests.WithDllImportInMainAssembly(config: "Debug") [FAIL]
      System.TimeoutException : Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for selector "text=Counter"
      ============================================================
      Stack Trace:
        /_/src/Playwright/Transport/Connection.cs(164,0): at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args)
        /_/src/Playwright/Transport/Connection.cs(475,0): at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(840,0): at Wasm.Build.Tests.BuildTestBase.BlazorRun(String config, Func`2 test, String extraArgs)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(849,0): at Wasm.Build.Tests.BuildTestBase.BlazorRun(String config, Func`2 test, String extraArgs)
        /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BuildPublishTests.cs(127,0): at Wasm.Build.Tests.Blazor.BuildPublishTests.WithDllImportInMainAssembly(String config)
        --- End of stack trace from previous location ---
      Output:
...

        [] Executing - /datadisks/disk1/work/AA71094D/w/A652094D/e/dotnet-net7+latest/dotnet run -c Debug --no-build  in pwd /datadisks/disk1/work/AA71094D/w/A652094D/e/wbt/blz_dllimp_Debug
        	[DOTNET_INSTALL_DIR] = /datadisks/disk1/work/AA71094D/w/A652094D/e/dotnet-net7+latest
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /datadisks/disk1/work/AA71094D/w/A652094D/e/dotnet-net7+latest:./dotnet-net7+latest:/__w/1/s/artifacts/bin/chromedriver/chromedriver_linux64:/datadisks/disk1/work/AA71094D/p/dotnet-net7+latest:/datadisks/disk1/work/AA71094D/p/xharness-cli:/datadisks/disk1/work/AA71094D/p/dotnet-cli:/datadisks/disk1/work/AA71094D/p/build/emsdk-node/14.18.2_64bit/bin:/datadisks/disk1/work/AA71094D/p/chrome-linux:/datadisks/disk1/work/AA71094D/p/chromedriver_linux64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        	[WasmNativeStrip] = false
        	[DOTNET_ROOT] = /datadisks/disk1/work/AA71094D/w/A652094D/e/dotnet-net7+latest/dotnet
        [] info: Microsoft.Hosting.Lifetime[14]
        []       Now listening on: http://localhost:5144
        [] info: Microsoft.Hosting.Lifetime[0]
        []       Application started. Press Ctrl+C to shut down.
        [] info: Microsoft.Hosting.Lifetime[0]
        []       Hosting environment: Development
        [] info: Microsoft.Hosting.Lifetime[0]
        []       Content root path: /datadisks/disk1/work/AA71094D/w/A652094D/e/wbt/blz_dllimp_Debug
        Launching chrome ('/datadisks/disk1/work/AA71094D/p/chrome-linux/chrome') via playwright with args = --explicitly-allowed-ports=5144
```

Same failure for `Wasm.Build.Tests.Blazor.BuildPublishTests.WithDllImportInMainAssembly(config: "Release")`, and `Wasm.Build.Tests.WasmTemplateTests.BlazorRunTest`.

```json
{
  "ErrorMessage": ".*System.TimeoutException : Timeout.*waiting for selector.*text=Counter.*",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
chrome console log:
```
          [error] crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
                Unhandled exception rendering component: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.Template
Parser:_invalidParameterNameCharacters' (0) due to: Could not resolve type with token 0100008d from typeref (expected class 'System.Buf
fers.IndexOfAnyValues`1' in assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:Syst
em.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Buffers.IndexOfAnyValues`1 member:(null)
          System.TypeLoadException: Could not load type of field 'Microsoft.AspNetCore.Components.Routing.TemplateParser:_invalidParame
terNameCharacters' (0) due to: Could not resolve type with token 0100008d from typeref (expected class 'System.Buffers.IndexOfAnyValues
`1' in assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=7
.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Buffers.IndexOfAnyValues`1 member:(null)
             at Microsoft.AspNetCore.Components.RouteTableFactory.Create(Dictionary`2 templatesByHandler)
             at Microsoft.AspNetCore.Components.RouteTableFactory.Create(List`1 componentTypes)
             at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey)
             at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
             at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
             at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters)
```

**Comment by radical** [comment]
The problem here is that blazor projects still need to target 7.0, and the references are getting mixed up.

- [ ] update the runtime pack to the built one, for net7.0 (for blazor tests)
- [ ] but the above then conflicts with the the AOT compiler being used from 7.0, because we use that to generate `runtime-icall-table.h`

**Comment by radical** [comment]
This issue is caused because of `aspnetcore` still being on `net7.0`, and `runtime` being on `net8.0`. This is temporary, and will change in https://github.com/dotnet/aspnetcore/issues/45492 . Once that is merged, running the blazor projects should work fine. Until then we can have the tests enabled except the running part.
