### ISSUE TITLE
Test failure - many failures in win-x86 GCStress=3

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#79516]
Failed in Run: [runtime-coreclr gcstress0x3-gcstress0xc 20221211.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=108672)
 
 **Failed tests:**
 ```
coreclr windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

- JIT\\IL_Conformance\\Convert\\TestConvertFromIntegral\\TestConvertFromIntegral.cmd
- JIT\\opt\\Vectorization\\UnrollEqualsStartsWIth\\UnrollEqualsStartsWIth.cmd
 ```
 
 **Error message:**
 ```
 
Assert failure(PID 4224 [0x00001080], Thread: 5492 [0x1574]): Consistency check failed: Crst Level violation: Can't take level 9 lock CrstCodeVersioning because you already holding level 3 lock CrstDynamicMT
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x702bba90)
CORECLR! CrstBase::IsSafeToTake + 0x2C3 (0x6fe37dbe)
CORECLR! CrstBase::Enter + 0x134 (0x6fe37883)
CORECLR! CrstBase::AcquireLock + 0xD (0x6fd8cc31)
CORECLR! CodeVersionManager::LockHolder::LockHolder + 0x25 (0x6fdcfb28)
CORECLR! EECodeInfo::GetNativeCodeVersion + 0xD3 (0x6feac92f)
CORECLR! EECodeInfo::GetSavedMethodCode + 0x8C (0x6feacd5a)
CORECLR! UnwindStackFrame + 0xD0 (0x6fe5ad10)
CORECLR! StackFrameIterator::NextRaw + 0x5B6 (0x6ff64423)
CORECLR! StackFrameIterator::Next + 0x50 (0x6ff63e27)
    File: D:\a\_work\1\s\src\coreclr\vm\crst.cpp Line: 765
    Image: C:\h\w\B1A0095C\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B1A0095C\w\AA230971\uploads\Reports\JIT.IL_Conformance\Convert\TestConvertFromIntegral\TestConvertFromIntegral.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B1A0095C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TestConvertFromIntegral.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B1A0095C\p
> C:\h\w\B1A0095C\w\AA230971\e\JIT\IL_Conformance\Convert\TestConvertFromIntegral\TestConvertFromIntegral.cmd
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
    at JIT_IL_Conformance._Convert_TestConvertFromIntegral_TestConvertFromIntegral_._Convert_TestConvertFromIntegral_TestConvertFromIntegral_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by v-wenyuxu** [comment]
Failed in Run: [runtime-coreclr gcstress0x3-gcstress0xc 20230212.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=168907)
 
 **Failed tests:**
 ```
 coreclr windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
     - JIT\\SIMD\\Vector3Interop_ro\\Vector3Interop_ro.cmd
     - JIT\\SIMD\\Vector3Interop_r\\Vector3Interop_r.cmd
     - Interop\\ArrayMarshalling\\SafeArray\\SafeArrayTest\\SafeArrayTest.cmd
     - Interop\\COM\\ComWrappers\\API\\ComWrappersTests\\ComWrappersTests.cmd
     - Interop\\COM\\ComWrappers\\GlobalInstance\\GlobalInstanceMarshallingTests\\GlobalInstanceMarshallingTests.cmd
     ... ...
 ```
 
 **Error message:**
 ```
 
Assert failure(PID 6000 [0x00001770], Thread: 1504 [0x05e0]): Consistency check failed: Crst Level violation: Can't take level 9 lock CrstCodeVersioning because you already holding level 5 lock CrstInteropData
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x70c21752)
CORECLR! CrstBase::IsSafeToTake + 0x2C3 (0x707a7d6e)
CORECLR! CrstBase::Enter + 0x134 (0x707a7833)
CORECLR! CrstBase::AcquireLock + 0xD (0x706fcc31)
CORECLR! CodeVersionManager::LockHolder::LockHolder + 0x25 (0x7073f7df)
CORECLR! EECodeInfo::GetNativeCodeVersion + 0xD3 (0x7081ca8f)
CORECLR! EECodeInfo::GetSavedMethodCode + 0x8C (0x7081ceba)
CORECLR! UnwindStackFrame + 0xD0 (0x707cacb0)
CORECLR! StackFrameIterator::NextRaw + 0x5B6 (0x708d2c64)
CORECLR! StackFrameIterator::Next + 0x50 (0x708d2668)
    File: D:\a\_work\1\s\src\coreclr\vm\crst.cpp Line: 765
    Image: C:\h\w\A7FF08A7\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A7FF08A7\w\B6EE09F8\uploads\Reports\JIT.SIMD\Vector3Interop_ro\Vector3Interop_ro.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A7FF08A7\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Vector3Interop_ro.dll 
nativeCall_PInvoke_CheckVector3Size: sizeof(Vector3) == 12
nativeCall_PInvoke_Vector3Arg:
    iVal 123
    sumOfEles(1.000000, 2.000000, 3.000000) = 6.000000
    str  abcdefg
    sumOfEles(10.000000, 11.000000, 12.000000) = 33.000000
nativeCall_PInvoke_Vector3Arg_Unix:
    v3f32_xmm0: 1.000000 2.000000 3.000000
    f32_xmm2 - f32_xmm7: 100.000000 101.000000 102.000000 103.000000 104.000000 105.000000
    f32_mem0: 106.000000
    v3f32_mem1: 10.000000 20.000000 30.000000
    f32_mem2-3: 107.000000 108.000000
    sum = 1002.000000
nativeCall_PInvoke_Vector3Arg_Unix2:
    v3f32_xmm0: 1.000000 2.000000 3.000000
    f32_xmm2 - f32_xmm7: 100.000000 101.000000 102.000000 103.000000 104.000000 105.000000
    f32_mem0: 106.000000
    v3f32_mem1: 4.000000 5.000000 6.000000
    f32_mem2-3: 107.000000 108.000000
    v3f32_mem4: 7.000000 8.000000 9.000000
    f32_mem5: 109.000000
    sum = 1090.000000
nativeCall_PInvoke_Vector3Ret:
    Return value: (1.000000, 2.000000, 3.000000)
    Sum of return scalar values = 6.000000
nativeCall_PInvoke_Vector3Array
    arrEle[0]: 1.000000 2.000000 3.000000
    arrEle[1]: 5.000000 6.000000 7.000000
    Sum = 24.000000
nativeCall_PInvoke_Vector3InStruct
    First struct member: (1.000000 2.000000 3.000000) -> (2.000000 3.000000 4.000000)
    Second struct member: (5.000000 6.000000 7.000000) -> (6.000000 7.000000 8.000000)
    Sum of all return scalar values = 30.000000
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A7FF08A7\p
> C:\h\w\A7FF08A7\w\B6EE09F8\e\JIT\SIMD\Vector3Interop_ro\Vector3Interop_ro.cmd
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at JIT_SIMD._Vector3Interop_ro_Vector3Interop_ro_._Vector3Interop_ro_Vector3Interop_ro_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by BruceForstall** [comment]
@janvorli @trylek @jkotas @mangod9 @davidwrighton This is a recent regression hitting many tests in win-x86 GCStress=3. Can someone route this to someone to investigate?

**Comment by trylek** [comment]
@AaronRobinsonMSFT was apparently the last one changing the <code>crst.cpp/h</code> files in

https://github.com/dotnet/runtime/pull/76553

including <code>CrstCodeVersioning</code> which is one of the locks involved in the assertion failure so I guess he's the initial suspect.

**Comment by AaronRobinsonMSFT** [comment]
Not that I am trying to avoid anything, but @jkotas just changed something here yesterday - https://github.com/dotnet/runtime/pull/82044.

**Comment by AaronRobinsonMSFT** [comment]
Unless this test hasn't run since October of last year, which would be unfortunate.

**Comment by trylek** [comment]
Oh, sorry about that, I didn't realize the change may have only involved the header file, I looked at history of the cpp file, thanks for educating me. In such case @jkotas is now the hot suspect :-).

**Comment by BruceForstall** [comment]
Note that the failures first appeared on Saturday:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=168435&view=ms.vss-test-web.build-test-results-tab

(but it only runs on Sat/Sun, so it had been a week since the previous run)

**Comment by BruceForstall** [comment]
Oh, looks like Jan's change should have fixed this, and this is a dup of https://github.com/dotnet/runtime/issues/82037.

I'll trigger another gcstress run
