### ISSUE TITLE
dotnet 7 on win7 x86 Could not load file or assembly, A dynamic link library (DLL) initialization routine failed. (0x8007045A)

### ISSUE THREAD

**Issue by harvito** [dotnet/runtime#79616]
### Description

A component that was working on Windows 7 (Embedded Standard) with dotnet 6 run time is no longer loading with dotnet 7 runtime. 

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\Admin\Desktop\WmmiTest\net7.0\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll'. A dynamic link library (DLL) initialization routine failed. (0x8007045A)
File name: 'C:\Users\Admin\Desktop\WmmiTest\net7.0\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll'
   at Microsoft.Management.Infrastructure.Options.DComSessionOptions..ctor()
   at <StartupCode$WmmiApp>.$Program.main@() in C:\Users\harvito\source\repos\WmmiApp\WmmiApp\Program.fs:line 1
```

### Reproduction Steps

1. Create a console app and target dotnet7. Add reference to "Microsoft.Management.Infrastructure" Version="2.0.0" and target compile to x86

WmmiApp.fsproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="2.0.0" />
  </ItemGroup>

</Project>
```

Program.fs
```
let cimOptions = new Microsoft.Management.Infrastructure.Options.DComSessionOptions()

printfn "cimOptions: %O" cimOptions
System.Console.ReadKey() |> ignore
```

2. Build, then copy bin\x86\Release\net7.0 to a Windows 7 x86 with Microsoft.AspNetCore.App 7.0.0 and Microsoft.NETCore.App 7.0.0 runtimes. 

3. Run the app, I used `WmmiApp.exe > output.txt 2>&1` to capture err and output to output.txt:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\Admin\Desktop\WmmiTest\net7.0\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll'. A dynamic link library (DLL) initialization routine failed. (0x8007045A)
File name: 'C:\Users\Admin\Desktop\WmmiTest\net7.0\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll'
   at Microsoft.Management.Infrastructure.Options.DComSessionOptions..ctor()
   at <StartupCode$WmmiApp>.$Program.main@() in C:\Users\harvito\source\repos\WmmiApp\WmmiApp\Program.fs:line 1
```

Doing the same exercise but targeting net6 does not produce exception.

### Expected behavior

Dotnet 7 runtime should be able to load the same assemblies as 6.

### Actual behavior

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\Users\Admin\Desktop\WmmiTest\net7.0\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll'. A dynamic link library (DLL) initialization routine failed. (0x8007045A)
File name: 'C:\Users\Admin\Desktop\WmmiTest\net7.0\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll'
   at Microsoft.Management.Infrastructure.Options.DComSessionOptions..ctor()
   at <StartupCode$WmmiApp>.$Program.main@() in C:\Users\harvito\source\repos\WmmiApp\WmmiApp\Program.fs:line 1
```

### Regression?

It seems this is a regression. It works when targeting dotnet 6.0. It also works on Windows 10.

### Configuration

sdk: net7.0
runtimes installed:
```
Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
OS: Windows Embedded Standard 7 Version 6.1 (Build7601: Service Pack 1)
architecture: intel x86 32-bit
issue appears specific to this configuration

**Comment by vcsjones** [comment]
Just as a point of information, .NET 7 no longer supports Windows 7 or Windows 8.1 Client SKUs. https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#support-changes-from-net-60

**Comment by smasher164** [comment]
Closing since .NET 7 doesn't support Windows 7.

**Comment by dongzhaosheng73** [comment]
Now Microsoft recommendation System. The Management or Microsoft. Management Infrastructure are is the result of my search to Microsoft pushing MMI results this project hasn't been updated, Microsoft.Management in Windows 10 if the.NET framework version is earlier than 4.7

"The native library 'c:\windows\microsoft.net \ framework \ v4.0.30319 \ wminet_utils DLL'"
