### ISSUE TITLE
Test failure: Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#79664]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=108777&view=ms.vss-test-web.build-test-results-tab&runId=2318470&resultId=100490&paneView=debug

coreclr OSX arm64 Checked jitstress2_jitstressregs3

```
export DOTNET_TieredCompilation=0
export DOTNET_JitStress=2
export DOTNET_JitStressRegs=3
```

```
    Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh [FAIL]
      
      Return code:      1
      Raw output file:      /tmp/helix/working/AFF509D6/w/C0620A3E/uploads/Reports/Interop.ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/AFF509D6/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ObjectiveCMarshalAPI.dll ''
      Running Validate_ReferenceTrackingAPIs_InvalidArgs...
      Running Validate_ReferenceTracking_Scenario...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 3
      Actual:   4
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ObjectiveCMarshalAPI.Program.Validate_ReferenceTracking_Scenario()
         at ObjectiveCMarshalAPI.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/tmp/helix/working/AFF509D6/p
      > /private/tmp/helix/working/AFF509D6/w/C0620A3E/e/Interop/ObjectiveC/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI/ObjectiveCMarshalAPI.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_ObjectiveC._ObjectiveCMaralAPI_ObjectiveCMaralAPI_ObjectiveCMaralAPI_._ObjectiveCMarshalAPI_ObjectiveCMarshalAPI_ObjectiveCMarshalAPI_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
```

Looks like the same issue as https://github.com/dotnet/runtime/issues/74130, which was "fixed" with https://github.com/dotnet/runtime/pull/75189

@AaronRobinsonMSFT PTAL
cc @jakobbotsch

**Comment by BrianBohe** [comment]
This is now failing also in runtime-coreclr jitstress-random, on osx x64 https://helix.dot.net/api/2019-06-17/jobs/22d64e09-edca-43ca-952f-8188616155c7/workitems/Interop/console
