### ISSUE TITLE
The certificate data cannot be read with the provided password, the password may be incorrect - When a docker container is set to automatically restart or manually restarted

### ISSUE THREAD

**Issue by Edstub207** [dotnet/runtime#79707]
### Description

When running a docker container with the password set as an envar at runtime the website works as expected, however, if the site crashes or container stops, it doesn't work upon restart. The args in use are:

ASPNETCORE_Kestrel__Certificates__Default__Password="BLAH"
 ASPNETCORE_Kestrel__Certificates__Default__Path=/app/horde.pfx
restart always

### Reproduction Steps

Start a container with a cert, protected by a password. Stop the container or have it crash and automatically restart 

### Expected behavior

The cert password is registered correctly

### Actual behavior

The application crashes

`[11:42:24 ftl] Fatal error.
System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
   at Internal.Cryptography.Pal.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts)
   at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean single, Boolean ephemeralSpecified, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password)
   at Horde.Build.Commands.ServerCommand.ReadGrpcCertificate(ServerSettings hordeSettings) in /app/Source/Programs/Horde/Horde.Build/Commands/ServerCommand.cs:line 116
   at Horde.Build.Commands.ServerCommand.ExecuteAsync(ILogger logger) in /app/Source/Programs/Horde/Horde.Build/Commands/ServerCommand.cs:line 40
   at EpicGames.Core.CommandHost.RunAsync(CommandLineArguments args, IServiceProvider serviceProvider, Type defaultCommandType) in /app/Source/Programs/Shared/EpicGames.Core/CommandHost.cs:line 266`

### Configuration

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
Linux Docker container running on Ubuntu 20.04

**Comment by vcsjones** [comment]
I'm not able to reproduce this. Do you have a sample Dockerfile and docker compose that can reproduce this?

Is it possible the environment variables or certificate changed between the container restart?

**Comment by Edstub207** [comment]
> I'm not able to reproduce this. Do you have a sample Dockerfile and docker compose that can reproduce this?
> 
> Is it possible the environment variables or certificate changed between the container restart?

- The dockerfile is as below:

`FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app
COPY Source/Programs/Horde/nuget.config ./Source/Programs/Horde/nuget.config
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update && apt-get -qq install curl

# Restore all the C# projects
COPY Source/Programs/Shared/EpicGames.Core/*.csproj ./Source/Programs/Shared/EpicGames.Core/
COPY Source/Programs/Shared/EpicGames.Horde/*.csproj ./Source/Programs/Shared/EpicGames.Horde/
COPY Source/Programs/Shared/EpicGames.IoHash/*.csproj ./Source/Programs/Shared/EpicGames.IoHash/
COPY Source/Programs/Shared/EpicGames.Perforce/*.csproj ./Source/Programs/Shared/EpicGames.Perforce/
COPY Source/Programs/Shared/EpicGames.Perforce.Managed/*.csproj ./Source/Programs/Shared/EpicGames.Perforce.Managed/
COPY Source/Programs/Shared/EpicGames.Redis/*.csproj ./Source/Programs/Shared/EpicGames.Redis/
COPY Source/Programs/Shared/EpicGames.Serialization/*.csproj ./Source/Programs/Shared/EpicGames.Serialization/
COPY Source/Programs/Shared/EpicGames.Serialization.Tests/*.csproj ./Source/Programs/Shared/EpicGames.Serialization.Tests/
COPY Source/Programs/Horde/Horde.Agent/*.csproj ./Source/Programs/Horde/Horde.Agent/
COPY Source/Programs/Horde/Horde.Build/*.csproj ./Source/Programs/Horde/Horde.Build/
COPY Source/Programs/Horde/Horde.Build.Tests/*.csproj ./Source/Programs/Horde/Horde.Build.Tests/
RUN dotnet restore Source/Programs/Horde/Horde.Build/Horde.Build.csproj -p:WithHordeStorage=false

# Add certs and dashboard into image.....
RUN mkdir -p /app/out/DashboardApp/
RUN mkdir -p /app/out/Data/Config/
COPY Source/Programs/Horde/HordeDashboard/published/ /app/out/DashboardApp/
COPY Source/Programs/Horde/Horde.Build/horde.pfx /app/out/horde.pfx
COPY Source/Programs/Horde/Horde.Build/Defaults/ /app/out/Data/Config/

# Build the server
COPY Binaries/DotNET/EpicGames.Perforce.Native/ Binaries/DotNET/EpicGames.Perforce.Native/
COPY Source/Programs/Shared/ Source/Programs/Shared/
COPY Source/Programs/Horde/Horde.Build/ Source/Programs/Horde/Horde.Build/
COPY Source/Programs/AutomationTool/AutomationUtils/Matchers/ Source/Programs/AutomationTool/AutomationUtils/Matchers/
COPY Source/Programs/UnrealBuildTool/Matchers/ Source/Programs/UnrealBuildTool/Matchers/
ARG msbuild_args
RUN dotnet publish Source/Programs/Horde/Horde.Build/Horde.Build.csproj -c Release -o out -p:WithHordeStorage=false $msbuild_args -p:RunAnalyzersDuringBuild=True

# Create the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "Horde.Build.dll" ]
`

No the cert hasn't changed, if I prune Docker containers and start it without re-downloading the image (using the same params) it's all fine.

**Comment by Edstub207** [comment]
@vcsjones Hey! Just bumping this.

**Comment by Edstub207** [comment]
I found the problem with this - Not sure why, but the application goes down a different code path and therefore is looking at a different cert the second time. Sorry about raising the invalid issue!
