### ISSUE TITLE
HTTP/3 checker website claims it supports HTTP/3, but HttpClient throws VER_NEG_ERROR

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/runtime#79729]
### Description

Hello,

I don't know if this is a bug, but I am leaving it here :-)

The website https://http3check.net/ is used for testing HTTP/3, and when itself is checked, it claims that it supports HTTP/3.

However, different tools returned different evaluations:

1) https://http3test.seowebchecker.com/ claims that https://http3check.net/ does not support HTTP/3,

2) https://geekflare.com/tools/http3-test says that https://http3check.net/ supports HTTP/3,

3) .NET 6 HttpClient throws the following Exception (`VER_NEG_ERROR`) when trying to connect to https://http3check.net/, with HTTP/3 RequestVersionExact:

```
System.Net.Http.HttpRequestException: Connection has been shutdown by transport. Error Code: VER_NEG_ERROR (http3check.net:443)
 ---> System.Net.Quic.QuicException: Connection has been shutdown by transport. Error Code: VER_NEG_ERROR
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Pororoca.Infrastructure.Features.Requester.PororocaRequester.RequestAsync(IPororocaVariableResolver variableResolver, PororocaHttpRequest req, Boolean disableSslVerification, CancellationToken cancellationToken) in C:\PROJETOS\Pororoca\src\Pororoca.Infrastructure\Features\Requester\PororocaRequester.cs:line 37
```

### Reproduction Steps

Try to connect with HttpClient, HTTP/3 version exact, to the URL https://http3check.net/

### Expected behavior

I am not sure if this is a bug or simply the website is mal-configured

### Actual behavior

-

### Configuration

.NET 6, Windows 11, debugging

### Other information

Other URLs that support HTTP/3 connect fine:

https://cloudflare-quic.com

https://quic.aiortc.org

**Comment by wfurt** [comment]
cc: @nibanks. There were multiple early versions of the spec so I'm wondering if that could be related....

**Comment by nibanks** [comment]
Probably something like that. I'd take those websites with a grain of salt...

**Comment by mattzink** [comment]
HTTP3 client support was in preview status for .NET 6, which was released before the HTTP3 standard was complete. Have you tried on .NET 7?

**Comment by nibanks** [comment]
FYI, if you're interested, [microsoft/quicreach](https://github.com/microsoft/quicreach) daily tests the top 5000+ hostnames to see if they advertise and can support the handshake for HTTP/3. If you're looking for more servers to try your client against, you can use the list there (see [Reach](https://github.com/microsoft/quicreach/actions/workflows/reach.yml) action for details).

**Comment by rzikm** [comment]
I took a trace of quicreach probing http3check.net and it shows that the following Version Negotiation packet was received from the server:

[4]3778.4F18::2023/01/02-14:19:06.380453900 [Microsoft-Quic][conn][0x2BBAFF83D40] Received Version Negotation:
[4]3778.4F18::2023/01/02-14:19:06.380454400 [Microsoft-Quic][conn][0x2BBAFF83D40]   Ver[0]: 0x51303433
[4]3778.4F18::2023/01/02-14:19:06.380454900 [Microsoft-Quic][conn][0x2BBAFF83D40]   Ver[1]: 0x51303436
[4]3778.4F18::2023/01/02-14:19:06.380455200 [Microsoft-Quic][conn][0x2BBAFF83D40]   Ver[2]: 0x51303530
[4]3778.4F18::2023/01/02-14:19:06.380455600 [Microsoft-Quic][conn][0x2BBAFF83D40]   Ver[3]: 0xff000019
[4]3778.4F18::2023/01/02-14:19:06.380455900 [Microsoft-Quic][conn][0x2BBAFF83D40]   Ver[4]: 0xff00001b

The first three versions are the Google QUIC Q043, Q046 and Q050. (used by chromium browsers). The last two correspond to the draft versions 25 and 33, respectively.

MsQuic (which backs the .NET System.Net.Quic implementation) supports the following versions:

```c
//
// The QUIC version numbers, in host byte order.
//
#define QUIC_VERSION_VER_NEG_H  0x00000000U     // Version for 'Version Negotiation'
#define QUIC_VERSION_2_H        0x709a50c4U     // Second official version
#define QUIC_VERSION_1_H        0x00000001U     // First official version
#define QUIC_VERSION_1_MS_H     0xabcd0000U     // First Microsoft version (-1412628480 in decimal)
#define QUIC_VERSION_DRAFT_29_H 0xff00001dU     // IETF draft 29
```

As there is no overlap between the two peers, the connection cannot be established.

I don't think there is anything for us to do. Since QUIC has been standardized by IETF, servers advertising QUIC support should support the first or second official version of the protocol.
