### ISSUE TITLE
System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments failing in CI (Outerloop)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#79749]
Configuration: `net48-windows-Release-x86-Windows.10.Amd64.Client21H1.Open`

```
Unexpected Error event: System.MethodAccessException: Attempt by security transparent method 'System.Diagnostics.Metrics.MetricsEventSource+MetricSpec.Parse(System.String)' to access security critical method 'System.MemoryExtensions.AsSpan(System.String, Int32, Int32)' failed.

Assembly 'System.Diagnostics.DiagnosticSource, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.
at System.Diagnostics.Metrics.MetricsEventSource.MetricSpec.Parse(String text) in //src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:line 474
at System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.ParseSpecs(String metricsSpecs) in //src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:line 393
at System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand(EventCommandEventArgs command) in /_/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs:line 363
Expected: True
Actual:   False
  at System.Diagnostics.Metrics.Tests.MetricsEventListener.AssertOnError() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 1144
   at System.Diagnostics.Metrics.Tests.MetricsEventListener.GetCountEvents(String eventName) in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 1153
   at System.Diagnostics.Metrics.Tests.MetricsEventListener.WaitForEvent(TimeSpan timeout, Int32 numEvents, String eventName) in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 1117
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 272
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=114328&view=ms.vss-test-web.build-test-results-tab&runId=2422252&paneView=debug

**Comment by ViktorHofer** [comment]
cc @tommcdon @noahfalk

**Comment by tommcdon** [comment]
@tarekgh
