### ISSUE TITLE
DirectoryNotFoundException on iOS due to case mismatch

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/runtime#79889]
### Description

When calling `Directory.CreateDirectory` on a filesystem that is not case sensitive, the base of the provided path should not need to match its case.  This indeed works on both Windows, Linux, and macOS already:

```csharp
Directory.CreateDirectory("TEST");
Directory.CreateDirectory("test/test");
```

However on iOS, the second line fails, throwing a `DirectoryNotFoundException` with the message  _"Could not find a part of the path."_

### Reproduction Steps

1. Create a new ios app
  ```
  dotnet new ios -n MyIosApp
  ```
2. Add the following lines in `AppDelegate.cs` at the end of `FinishedLaunching` before the return.
  ```csharp
  Directory.CreateDirectory("TEST");
  Directory.CreateDirectory("test/test");
  ```
3. Debug/Run the app in a simulator.

### Expected behavior

Because the file system is case insensitive, the app should create the directories as follows:

```
TEST
TEST/test
```

Since it's an iOS app, the directories would have be created under:

`/Users/[username]/Library/Developer/CoreSimulator/Devices/[deviceid]/data/Containers/Bundle/Application/[appid]/MyIosApp.app/`

### Actual behavior

Only the first call succeeds, creating the `TEST` directory.  The second call fails with:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/matt/Library/Developer/CoreSimulator/Devices/C9C5256E-18BE-416E-A04F-4B741608E149/data/Containers/Bundle/Application/04BF3752-7A12-41A4-AEC2-77AE830B98F4/MyIosApp.app/test/test'.
   at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at MyIosApp.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/matt/temp/iOS/MyIosApp/AppDelegate.cs:line 29
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Program.<Main>$(String[] args) in /Users/matt/temp/iOS/MyIosApp/Main.cs:line 6
```

### Configuration

.NET 7.0.101
Xamarin.iOS 16.0.0.72

Running on a M1 (arm64) Macbook Pro.

Full version info from "About Visual Studio" in VS for Mac follows:

<details>
<summary>Version information</summary>

```
Visual Studio Enterprise 2022 for Mac Preview
Version 17.5 Preview (17.5 build 437)
Installation UUID: 7fccecb1-31c0-40dd-afc6-4ad5fcaafe9b

Runtime
.NET 7.0.0 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.101/Sdks
SDK Versions:
	7.0.101
	7.0.100
	6.0.404
	6.0.403
	6.0.402
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.404
	6.0.403
	3.1.426
	3.1.425

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.1
	7.0.0
	6.0.12
	6.0.11
	6.0.10

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.12
	6.0.11
	3.1.32
	3.1.31
	3.1.30

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.2 (21534)
Build 14C18

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Enterprise)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Enterprise)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.5.1.13
Hash: 14bdde937f
Branch: remotes/origin/d17-5
Build date: 2022-11-02 21:36:49 UTC

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Enterprise)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/matt/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0 rc4

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.8
Hash: 6f27afd
Branch: remotes/origin/HEAD
Build date: 2022-11-02 21:36:54 UTC

Android Device Manager
Version: 0.0.0.1217
Hash: 6175224
Branch: main
Build date: 2022-11-02 21:36:54 UTC

Build Information
Release ID: 1705000437
Git revision: a5d0fb913c1ff781c80fe725a3e0511c34e26a08
Build date: 2022-11-02 21:34:22+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 12.6.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Thu Sep 29 20:13:56 PDT 2022
    root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64

```

</details>

**Comment by mattjohnsonpint** [comment]
Small correction.  I believe that the file system on iOS on actual devices is case-sensitive.  However the default file system on macOS is case-insensitive.  Thus I think the simulator must be doing something to emulate a case-sensitive file system over the actual case-insensitive one.

Either way, it should not throw the exception.

**Comment by mattjohnsonpint** [comment]
... or rather maybe it *should*?  If the file system was actually case sensitive then I suppose the failure would be appropriate.

It's confusing because `Directory.Exists("test")` (lower-case) will be true even if it was created as upper-case `"TEST"`, but then `Directory.CreateDirectory` will still say part of the path *doesn't* exist.  Not sure if the behavior of `CreateDirectory` or `Exists` is correct here, but I think they should be consistent.

**Comment by vcsjones** [comment]
Yeah. This was a long standing issue with macOS and iOS development. iOS's file system is case sensitive, whereas macOS is not (by default). The simulator has a special trick to run case sensitive, a hidden entitlement called `com.apple.private.iopol.case_sensitivity`. Originally, the simulator _used_ to be case insensitive, but that lead to too many developers wondering why their app worked fine in the simulator, but not on a real device. So that special work around was made... 10ish years ago?

That doesn't necessarily explain the odd behavior you are seeing, but it makes sense to me that it does throw saying that it does not exist.

**Comment by bartonjs** [comment]
The description only had

```C#
Directory.CreateDirectory("TEST");
Directory.CreateDirectory("test/test");
```

but there's an implied claim that `Directory.Exists("test")` would return true after the first CreateDirectory.  Is that actually true?

**Comment by vcsjones** [comment]
> Is that actually true?

That doesn't seem to be the case for me. Using this AppDelegate:

```C#
public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
{
    Window = new UIWindow (UIScreen.MainScreen.Bounds);

    Directory.CreateDirectory("TEST");
    bool existsDifferentCase = Directory.Exists("test");
    bool existsSameCase = Directory.Exists("TEST");

    var vc = new UIViewController();
    vc.View!.AddSubview(new UILabel (Window!.Frame) {
        BackgroundColor = UIColor.SystemBackground,
        TextAlignment = UITextAlignment.Center,
        Text = $"Exists different case: {existsDifferentCase}; Exists same case: {existsSameCase}.",
        AutoresizingMask = UIViewAutoresizing.All,
    });
    Window.RootViewController = vc;

    Window.MakeKeyAndVisible();
    return true;
}
```

This is what the simulator displays:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/361677/210653403-be8dec20-8f5c-45e3-8250-3e28f461e3c0.png">
