### ISSUE TITLE
`IOptions<RecordType>` with `services.Configure<RecordType>` throws

### ISSUE THREAD

**Issue by aradalvand** [dotnet/runtime#79958]
### Description

Apparently this was implemented in #43662 but to my surprise the following actually throws:

```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

var builder = WebApplication.CreateBuilder(args);

builder.Services.Configure<Settings>(builder.Configuration);

var app = builder.Build();

app.MapGet("/test", ([FromServices] IOptions<Settings> settings) =>
{
    return $"{settings.Value.Color}";
});

app.Run();

public record Settings(string Color, int Length);
```
The exception:
```
An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No service for type 'Settings' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at lambda_method1(Closure, Object, HttpContext)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
Yet this is precisely the use case outlined in #43662, am I missing something?!

### Reproduction Steps

Described above.

### Expected behavior

Shouldn't throw.

### Actual behavior

Throws.

**Comment by tarekgh** [comment]
This is most likely be the same issue tracked here https://github.com/dotnet/runtime/issues/78771. Could you please try to define the record as: 

```C# 
public record Settings(string Color, int Length);
{
 public string Color { get; init; }
 public int Length { get; init; }
}
```

and look if this can help workaround the issue?

**Comment by aradalvand** [comment]
@tarekgh It isn't. That issue is about the in-memory configuration provider, mine has nothing to do with that. In that issue it seems the in-memory configuration provider is failing to work with the `Get<RecordType>()` method, in my case `Get<RecordType>()` does work, it's the `IOptions` pattern that doesn't.

**Comment by tarekgh** [comment]
@aradalvand thank for the info. We'll try to look at it later.

**Comment by jzebedee** [comment]
This bug still exists a fresh year and fresh .NET release later. However, the following does correctly bind to a record type:

`builder.Configuration.Get<Settings>()`

So clearly the binding is able to happen, but there's still a bug in the registration/binding of option types through `.Configure`.

**Comment by tarekgh** [comment]
The record is actually a class. When using record this way, the compiler will generate a class `public class Settings` with only one constructor `public Settings(string Color, int Length)`. The options binding will fail to create instance of this class because there is no parameter-less constructor to use. There is easy workaround for this problem by using something like the following instead:

```C#
public class Settings
{
    public string Color { get; set; } = null!;
    public int Length { get; set; }
}
```

We're maintaining the open issue to address it with a fix in the future, although it's not currently a priority compared to our ongoing tasks and considering the easy workaround.

**Comment by jzebedee** [comment]
> There is easy workaround for this problem by using something like the following instead:
> 
> ```cs
> public class Settings
> {
>     public string Color { get; set; } = null!;
>     public int Length { get; set; }
> }
> ```

That's not a workaround for the issue. That's just a regular class. If we were going down that route, why use a record in the first place?

It's also explicitly mentioned in #43662 that binding of immutable record types is supported just as shown in the original repro. That issue is closed, so I'm not sure if it was never correctly implemented or if this is a regression.

**Comment by tarekgh** [comment]
@jzebedee I am not saying we are not going to fix the issue. I am just mentioning the workaround for anyone blocked by that for now. That is all. 

For https://github.com/dotnet/runtime/issues/43662 it is addressed by https://github.com/dotnet/runtime/pull/67258. You mentioned in the other comment `So clearly the binding is able to happen, but there's still a bug in the registration/binding of option types through .Configure.`. This means the implementation missed the case of IOption binding. This is not a regression.

**Comment by tarekgh** [comment]
I have looked more on this; the best can be done for now is instead of doing:

```C#
var settings = app.Services.GetRequiredService<IOptions<Settings>>().Value;
```

do

```C#
            IConfiguration configuration = app.Services.GetRequiredService<IConfiguration>();
            Settings? settings = configuration.GetSection("Settings").Get<Settings>();
```

Here are more details:

When calling `app.Services.GetRequiredService<IOptions<Settings>>().Value`, this eventually need to create instance of the `Settings` record. As the record is defined with a primary constructor, the record will not have any parameter-less constructors. Eventually the options try to create the instance of the record https://github.com/dotnet/runtime/blob/1d2e841eff21c3a1e4591ef6cf522afd5c40ff51/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs#L100 then fail to do so because cannot call the record constructor which is taking parameters. And cannot even extract the parameter values from the configuration because on this level the options cannot access the configuration. 
The suggested way to make this work is instead of using options to get the instance, try to use the configuration to do it. First get the configuration `IConfiguration configuration = app.Services.GetRequiredService<IConfiguration>();` then get the record instance `Settings? settings = configuration.GetSection("Settings").Get<Settings>();`. This will work because the configuration can read the settings values and pass such values to the record constructor to create the record instance.
