### ISSUE TITLE
[mono] TestUserCredentialsPropertiesOnWindows fails with "Token cannot be zero."

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#80019]
This **outerloop** test fails on Windows on Mono:

```
    System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
      System.ArgumentException : Token cannot be zero.
      Stack Trace:
        /_/src/libraries/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs(293,0): at System.Security.Principal.WindowsIdentity.DuplicateAccessToken(IntPtr accessToken)
        /_/src/libraries/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs(320,0): at System.Security.Principal.WindowsIdentity.CreateFromToken(IntPtr userToken)
        /_/src/libraries/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs(107,0): at System.Security.Principal.WindowsIdentity..ctor(IntPtr userToken, String authType, Int32 isAuthenticated)
        /_/src/libraries/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs(63,0): at System.Security.Principal.WindowsIdentity..ctor(IntPtr userToken)
        /_/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs(108,0): at System.WindowsTestAccount.CreateUser()
        /_/src/libraries/Common/tests/TestUtilities/System/WindowsIdentityFixture.cs(47,0): at System.WindowsTestAccount..ctor(String userName)
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(472,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(30,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Filing this issue to track disabling the test.

**Comment by danmoseley** [comment]
Any idea how this could be Mono only? Some interop bug?

**Comment by akoeplinger** [comment]
No idea, I haven't looked at it. It's possible that this boils down to some interop thing that Mono doesn't support, if it's by design we can disable the tests completely on Mono. /cc @lateralusX

**Comment by lateralusX** [comment]
Was this on test runs using debug only library builds? Looks like this change:

https://github.com/dotnet/runtime/pull/71991

added an new field to the SafeHandle class on debug builds,  that is not accounted for in Mono's SafeHandle native representation, https://github.com/dotnet/runtime/blob/dcda1e08cb8f421877388be2d685c009a31b1845/src/mono/mono/metadata/class-internals.h#L677, so Mono still assumes first field is the handle, while on debug build, its now a string to a callstack as the first field, so either we would need to do similar change in Mono like done on CoreCLR, add a MonoString * to the struct for debug builds of runtime and S.P.C, eliminate the field on Mono runtime or not make it the first field in the class layout (Mono uses sequential layout for SafeHandle and only cares about first field being the handle).

**Comment by akoeplinger** [comment]
@lateralusX I don't remember whether it was only but your explanation makes sense, do you have time to make a PR? I don't have a working Windows environment at the moment.

**Comment by lateralusX** [comment]
@akoeplinger, I can look at it, do you have the PR that disabled the failing tests?

@stephentoub, any reason why m_ctorStackTrace added in https://github.com/dotnet/runtime/pull/71991 was added as first field in SafeHandle class? Could it be moved to the be the last field making sure Mono's native representation of SafeHandle can stay the same on both debug/release builds since we only care about the offset to handle field in the allocated object when marshalling.

**Comment by akoeplinger** [comment]
@lateralusX I'm working on that in https://github.com/dotnet/runtime/pull/79885 so it's still enabled in main (didn't have time to finish the PR before the holiday break)
