### ISSUE TITLE
Test failure GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80109]
Run: [runtime-coreclr gcstress-extra 20230101.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=122270&view=ms.vss-test-web.build-test-results-tab&runId=2624664&resultId=120743&paneView=debug)

Failed test:
```
coreclr OSX arm64 Checked gcstress0xc_zapdisable_heapverify1 @ OSX.1200.ARM64.Open

- GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh
```
**Error message:**
```
Unhandled exception. System.ArgumentNullException: Value cannot be null.
at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
at System.Runtime.CompilerServices.ConditionalWeakTable2.Enumerator.Dispose() at System.Buffers.TlsOverPerCoreLockedStacksArrayPool1.Trim()
at System.Gen2GcCallback.Finalize()
[createdump] Invalid process id: task_for_pid(26444) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/92730862/w/A44C08F2/e/GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh: line 417: 26444 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/92730862/w/A44C08F2/uploads/Reports/GC.API/GC/GetGeneration_fail/GetGeneration_fail.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/92730862/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false GetGeneration_fail.dll ''
This test should throw an exception!
Generation: 0
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/92730862/p
/private/tmp/helix/working/92730862/w/A44C08F2/e/GC/API/GC/GetGeneration_fail/GetGeneration_fail.sh
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetGeneration_fail_GetGeneration_fail_._GC_GetGeneration_fail_GetGeneration_fail_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Single failure in early days of DATAS bring up. Closing for now.
