### ISSUE TITLE
Attribute argument of a type containing function pointer fails with `TypeLoadException` during reflection

### ISSUE THREAD

**Issue by jjonescz** [dotnet/runtime#80138]
**Version Used**: https://github.com/dotnet/roslyn/commit/34180c3974c46fe354740d7f5fddd17244474612 (2022-12-20)

Discovered while working on dotnet/roslyn#66073.

**Steps to Reproduce**:

```cs
[Theory, CombinatorialData, WorkItem(65594, "https://github.com/dotnet/roslyn/issues/65594")]
public void Attribute_TypedDefault_Enum([CombinatorialValues("class", "struct")] string kind)
{
    var source = $$"""
        using System;
        using System.Linq;
        
        var attr = typeof(C).CustomAttributes.Single(d => d.AttributeType == typeof(A));
        var arg = attr.ConstructorArguments.Single();
        Console.WriteLine((int)arg.Value == 0);
        
        class A : Attribute
        {
            public A(B<delegate*<void>[]>.E e) { }
        }

        {{kind}} B<T>
        {
            public enum E { }
        }

        [A(default)]
        class C { }
        """;

    var verifier = CompileAndVerify(source, expectedOutput: "True", symbolValidator: static module =>
    {
        var c = module.GlobalNamespace.GetTypeMember("C");
        var attr = c.GetAttributes().Single(d => d.AttributeClass?.Name == "A");
        Assert.Empty(attr.ConstructorArguments);
    });
    verifier.VerifyDiagnostics();
}
```

**Expected Behavior**: The test succeeds.

**Actual Behavior**: At runtime, it fails with:

```
System.TypeLoadException: Could not load type '(fnptr)' from assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(String name, RuntimeModule scope)
   at System.Reflection.CustomAttributeTypedArgument.ResolveType(RuntimeModule scope, String typeName)
   at System.Reflection.CustomAttributeTypedArgument..ctor(RuntimeModule scope, CustomAttributeEncodedArgument encodedArg)
   at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
   at Program.<Main>$(String[] args)
```

Changing `A`'s constructor to take parameter of a different type, e.g., `B<int>.E` instead of `B<delegate*<void>[]>.E`, makes the test pass. (Although I wouldn't expect the symbol validator to discover empty attribute constructor arguments, but that's a different issue - dotnet/roslyn#66370.)

> **Note** This issue is mentioned in tests (dotnet/roslyn#66073).

**Comment by steveharter** [comment]
Function pointers are not currently supported as a reflectable type othan than `IntPtr`; see https://github.com/dotnet/runtime/issues/11354.

We are working on adding support in 8.0, although resolving a function pointer from a string may not be supported in 8.0 either as shown in the provided call stack
`System.Reflection.CustomAttributeTypedArgument.ResolveType(RuntimeModule scope, String typeName)`.

Keeping in 8.0 for re-assessment once the core function pointer work is in.

**Comment by steveharter** [comment]
This issue still occurs in v8 RC1:
```cs

namespace ConsoleApp172
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var attr = typeof(C).CustomAttributes.Single(d => d.AttributeType == typeof(A));

            // throws:
            var arg = attr.ConstructorArguments.Single();

            Console.WriteLine((int)arg.Value == 0);
        }
    }

    class A : Attribute
    {
        public A(B<delegate*<void>[]>.E e) { }
        
        // This works:
        // public A(B<void*[]>.E e) { }
    }

    class B<T>
    {
        public enum E { }
    }

    [A(default)]
    class C { }
}
```

Moving to v9 based on priority.
