### ISSUE TITLE
[6.0] CI failure: UnauthorizedAccessException in System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#80475]
I'm seeing this test failure intermittently affecting `release/6.0` backport PRs.

- Example PR: https://github.com/dotnet/runtime/pull/80452
- Queue: `Libraries Build windows net48 x86 Release`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=132447&view=logs&j=79ebbb2e-07f2-5457-c5e5-132dd7ee4ba8&t=160ce0e3-a8e8-5ac5-8623-55bee3c49b38&l=54
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-80452-merge-e981f4b74b094252ba/System.Diagnostics.EventLog.Tests/1/console.a3676540.log?helixlogtype=result
- Callstack:
```
    System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties [FAIL]
      System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.
      Stack Trace:
           at System.Diagnostics.Eventing.Reader.EventLogException.Throw(Int32 errorCode)
           at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtOpenProviderMetadata(EventLogHandle session, String ProviderId, String logFilePath, Int32 locale, Int32 flags)
           at System.Diagnostics.Eventing.Reader.ProviderMetadata..ctor(String providerName, EventLogSession session, CultureInfo targetCultureInfo, String logFilePath)
        /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs(104,0): at System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties()
```

The test failure is happening in this constructor: https://github.com/dotnet/runtime/blob/fb3101268627d83e3b8200d31c8f9c0fd78540a9/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs#L104

**Comment by ViktorHofer** [comment]
@carlossanlop the test is already disabled in main. You want to backport https://github.com/dotnet/runtime/pull/68417 into release/6.0. cc @danmoseley

**Comment by akoeplinger** [comment]
Closing old 6.0 known issue.
