### ISSUE TITLE
Issue with Razor (Crashed After errors!)

### ISSUE THREAD

**Issue by abdollahkahne** [dotnet/runtime#80496]
### Description

I am started to use Ubuntu 22.04 and encounter this issue. So I can not work razor page intellisense. I see same issue on issues but one of them is closed and the other is not active. I do the suggestion there and I can not fix the issue. So I reported it for new solutions if anyone have solved this issue. 
Thank you 
```
Razor.VSCode version 6.0.0-preview.5.21358.6
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

Cannot get required symbol EVP_MD_size from libssl
[Info  - 11:43:08] Connection to server got closed. Server will restart.
[Error - 11:43:08] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1174265)
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1230914)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1231089)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1250254)
	at t (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1229288)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at V (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1166325)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at l.fireClose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177200)
	at Socket.<anonymous> (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177962)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 11:43:08] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1174265)
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1230914)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1231089)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1250254)
	at t (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1229288)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at V (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1166325)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at l.fireClose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177200)
	at Socket.<anonymous> (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177962)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Info  - 11:43:17] Connection to server got closed. Server will restart.
[Error - 11:43:17] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1174265)
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1230914)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1231089)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1250254)
	at t (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1229288)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at V (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1166325)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at l.fireClose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177200)
	at Socket.<anonymous> (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177962)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Info  - 11:43:24] Connection to server got closed. Server will restart.
[Error - 11:43:24] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1174265)
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1230914)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1231089)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1250254)
	at t (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1229288)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at V (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1166325)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at l.fireClose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177200)
	at Socket.<anonymous> (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177962)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Info  - 11:43:30] Connection to server got closed. Server will restart.
[Error - 11:43:30] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1174265)
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1230914)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1231089)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1250254)
	at t (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1229288)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at V (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1166325)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at l.fireClose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177200)
	at Socket.<anonymous> (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177962)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)
Cannot get required symbol EVP_MD_size from libssl
[Error - 11:43:36] Connection to server got closed. Server will not be restarted.
[Error - 11:43:36] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1174265)
	at Object.dispose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1230914)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1231089)
	at E.handleConnectionClosed (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1250254)
	at t (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1229288)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at V (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1166325)
	at n.invoke (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159116)
	at r.fire (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1159846)
	at l.fireClose (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177200)
	at Socket.<anonymous> (/home/student/.vscode/extensions/ms-dotnettools.csharp-1.25.2-linux-x64/dist/extension.js:2:1177962)
	at Socket.emit (node:events:538:35)
	at Pipe.<anonymous> (node:net:687:12)

```

### Reproduction Steps

create a razor page and try to work with it!

### Expected behavior

Intellisense work as previously

### Actual behavior

Intellisense do not work

**Comment by abdollahkahne** [comment]
Sorry this issue is not related here, I wanted to report it to Omnisharp extension.
