### ISSUE TITLE
Test failure JIT\\opt\\ValueNumbering\\ExposedLocalsNumbering\\ExposedLocalsNumbering.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80533]
Run: [runtime-coreclr outerloop 20230111.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=134019&view=ms.vss-test-web.build-test-results-tab&runId=2909300&resultId=106456&paneView=debug)

Failed test:
```
coreclr linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- JIT/opt/ValueNumbering/ExposedLocalsNumbering/ExposedLocalsNumbering.sh

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\opt\\ValueNumbering\\ExposedLocalsNumbering\\ExposedLocalsNumbering.cmd
```
**Error message:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at ExposedLocalsNumbering.Main()

Return code:      1
Raw output file:      C:\h\w\9A5D089B\w\AFD7098B\uploads\Reports\JIT.opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.output.txt
Raw output:
BEGIN EXECUTION
ExposedLocalsNumbering.dll
1 file(s) copied.
20:08:36.03
Response file: C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.dll.rsp
C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\IL-CG2\ExposedLocalsNumbering.dll
-o:C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\9A5D089B\p\System..dll
-r:C:\h\w\9A5D089B\p\Microsoft..dll
-r:C:\h\w\9A5D089B\p\mscorlib.dll
-r:C:\h\w\9A5D089B\p\netstandard.dll
-O
" "dotnet" "C:\h\w\9A5D089B\p\crossgen2\crossgen2.dll" @"C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.dll.rsp"   -r:C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.dll
" "dotnet" "C:\h\w\9A5D089B\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.dll --out C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.dll.r2rdump --val"
20:08:38.76
"C:\h\w\9A5D089B\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ExposedLocalsNumbering.dll
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\9A5D089B\p
C:\h\w\9A5D089B\w\AFD7098B\e\JIT\opt\ValueNumbering\ExposedLocalsNumbering\ExposedLocalsNumbering.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_opt._ValueNumbering_ExposedLocalsNumbering_ExposedLocalsNumbering_._ValueNumbering_ExposedLocalsNumbering_ExposedLocalsNumbering_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by SingleAccretion** [comment]
Disabled in #80522.
