### ISSUE TITLE
[6.0] WASM CI failure: WorkloadManifestCompositionException: Workload manifest dependency 'Emscripten' version '6.0.4' is lower than version '6.0.13' required by manifest 'mono.toolchain'

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#80574]
Found in 6.0 PR: https://github.com/dotnet/runtime/pull/80554

Queue: `Build Browser wasm Release AllSubsets_Mono_WasmBuildTests`
Step: Build product
Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=135390&view=logs&j=3a9f831a-39fc-5a98-005d-1222ec2c60ca&t=43ac2bf6-9cb4-5da7-8a9d-b264068ff198&l=3667
Full error message:

<details>

  ```
--------------------------------------------------------------------------------------
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.13' required by manifest 'microsoft.net.workload.mono.toolchain' [/__w/1/s/artifacts/bin/dotnet-workload/sdk-manifests/6.0.400/microsoft.net.workload.mono.toolchain/WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
2023-01-12T16:27:51.8117584Z 
2023-01-12T16:27:51.8220766Z Build FAILED.
2023-01-12T16:27:51.8221031Z 
2023-01-12T16:27:51.8278797Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.13' required by manifest 'microsoft.net.workload.mono.toolchain' [/__w/1/s/artifacts/bin/dotnet-workload/sdk-manifests/6.0.400/microsoft.net.workload.mono.toolchain/WorkloadManifest.json] [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8288510Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.13' required by manifest 'microsoft.net.workload.mono.toolchain' [/__w/1/s/artifacts/bin/dotnet-workload/sdk-manifests/6.0.400/microsoft.net.workload.mono.toolchain/WorkloadManifest.json] [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8296007Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8318708Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8387573Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8392074Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8397533Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8403715Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8410155Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8417144Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8421459Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8424808Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8428481Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8432169Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8436042Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8440329Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8443592Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8446145Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8448989Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8452114Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8454980Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8457998Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8461739Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8465455Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8468274Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8471009Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8474165Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8477665Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8480770Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8483486Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8486652Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8490458Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8493651Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : workload install failed: Welcome to .NET 6.0! [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8496072Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --------------------- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8498328Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : SDK Version: 6.0.400 [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8500528Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : ---------------- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8502951Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Installed an ASP.NET Core HTTPS development certificate. [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8506124Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8508968Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Learn about HTTPS: https://aka.ms/dotnet-https [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8511878Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : ---------------- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8515256Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Write your first app: https://aka.ms/dotnet-hello-world [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8518053Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Find out what's new: https://aka.ms/dotnet-whats-new [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8520774Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Explore documentation: https://aka.ms/dotnet-docs [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8523410Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Report issues and find source on GitHub: https://github.com/dotnet/core [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8526398Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8528880Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : -------------------------------------------------------------------------------------- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8533183Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten' version '6.0.4' is lower than version '6.0.13' required by manifest 'microsoft.net.workload.mono.toolchain' [/__w/1/s/artifacts/bin/dotnet-workload/sdk-manifests/6.0.400/microsoft.net.workload.mono.toolchain/WorkloadManifest.json] [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8537166Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8540349Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8544939Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8550256Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8554087Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8556717Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8559765Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8562290Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8564886Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8567391Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8570019Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8572643Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8575421Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8578086Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error : --- End of stack trace from previous location --- [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8580795Z /__w/1/s/src/libraries/workloads-testing.targets(127,5): error :    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext() [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
2023-01-12T16:27:51.8582144Z     0 Warning(s)
2023-01-12T16:27:51.8582633Z     33 Error(s)
  ```
</details>

**Comment by carlossanlop** [comment]
Not sure if also related, but in the log I see this additional build failure that is not showing up as the main error:

```

                 ^~~~~~
  /__w/1/s/src/mono/mono/mini/mini-llvm.c: In function ‘emit_entry_bb’:
  /__w/1/s/src/mono/mono/mini/mini-llvm.c:3759:15: warning: variable ‘vtype’ set but not used [-Wunused-but-set-variable]
     LLVMTypeRef vtype;
                 ^~~~~
  /__w/1/s/src/mono/mono/mini/mini-llvm.c:3953:30: warning: variable ‘store’ set but not used [-Wunused-but-set-variable]
      LLVMValueRef rgctx_alloc, store;
                                ^~~~~
  /__w/1/s/src/mono/mono/mini/mini-llvm.c: In function ‘default_cpp_lpad_exc_signature’:
  /__w/1/s/src/mono/mono/mini/mini-llvm.c:4725:18: warning: variable ‘inited’ set but not used [-Wunused-but-set-variable]
    static gboolean inited = FALSE;
                    ^~~~~~
  /__w/1/s/src/mono/mono/mini/mini-llvm.c: In function ‘process_bb’:
  /__w/1/s/src/mono/mono/mini/mini-llvm.c:5353:26: warning: variable ‘starting_builder’ set but not used [-Wunused-but-set-variable]
    LLVMBuilderRef builder, starting_builder;
                            ^~~~~~~~~~~~~~~~
  /__w/1/s/src/mono/mono/mini/mini-llvm.c: In function ‘mono_llvm_emit_call’:
  /__w/1/s/src/mono/mono/mini/mini-llvm.c:12084:12: warning: variable ‘stack_size’ set but not used [-Wunused-but-set-variable]
    int i, n, stack_size;
              ^~~~~~~~~~
  [ 97%] Building CXX object mono/mini/CMakeFiles/monosgen-objects.dir/mini-llvm-cpp.cpp.o

```

**Comment by lewing** [comment]
looks likr the 6.0.400 sdk branch has very stale baseline manifests (well behind the 6.0.1xx branch) but I'm not sure that is the cause 

cc @dsplaisted @marcpopMSFT

**Comment by lewing** [comment]
this could be the flow issue, a new emsdk build and version should be incoming soon, lets see if that gets the correct stable darc branch in the flow

**Comment by marcpopMSFT** [comment]
> this could be the flow issue, a new emsdk build and version should be incoming soon, lets see if that gets the correct stable darc branch in the flow
We don't autoflow the baseline manifest updates in servicing as we generally don't want them to be updating.  If you think they should get updated, it'll have to be a manual update in installer. Why would an older baseline manifest cause this?

**Comment by lewing** [comment]
> > this could be the flow issue, a new emsdk build and version should be incoming soon, lets see if that gets the correct stable darc branch in the flow
> > We don't autoflow the baseline manifest updates in servicing as we generally don't want them to be updating.  If you think they should get updated, it'll have to be a manual update in installer. Why would an older baseline manifest cause this?

I mainly noticed that the emscripten version in release/6.0-1xx (6.0.13) was newer than release/6.0-4xx (6.0.4) which does seem wrong?

**Comment by marcpopMSFT** [comment]
That's because there's a CoherentParentDependency in 6.0.1xx so it gets updated whenever runtime updates. It probably shouldn't.
https://github.com/dotnet/installer/blob/release/6.0.1xx/eng/Version.Details.xml#L169

Let's talk in the sync in two weeks.

**Comment by lewing** [comment]
why is https://www.nuget.org/packages/Microsoft.NET.Workload.Emscripten.Manifest-6.0.400 on nuget.org but not in the dotnet6 feed?

**Comment by marcpopMSFT** [comment]
probably a publishing issue. CC @mmitche @wtgodbe

**Comment by lewing** [comment]
@carlossanlop https://github.com/dotnet/runtime/pull/80591 will bump the version for 6.0.x and hopefully end up in the feed
