### ISSUE TITLE
Test failure tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80594]
Run: [runtime-coreclr outerloop 20230112.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=135595&view=ms.vss-test-web.build-test-results-tab&runId=2945282&resultId=122241&paneView=debug)

Failed test: 
```
coreclr linux arm Checked no_tiered_compilation @ (Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7

- tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.sh
```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/pauseonstart/pauseonstart/pauseonstart.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false pauseonstart.dll ''
0.0s: ::== Running test: TEST_RuntimeResumesExecutionWithCommand
0.1s: Server name is '/tmp/DOTNET_TRACE_TESTS_knx5obsv.u2z'
1.1s: running sub-process: /root/helix/work/correlation/corerun /root/helix/work/workitem/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll 0
1.5s: subprocess started: True
1.5s: subprocess PID: 6567
2.0s: { Magic=System.Byte[]; ClrInstanceId=0ef740a8-22c1-4ef2-9c5c-c8f76a445b42; ProcessId=6567; Unused=0; }
2.1s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=1; Reserved=0 }; }
2.2s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=0; Reserved=0 }; Payload=[ 0x00 0x00 0x00 0x00  ]}
2.2s: Sending 'exit' to subprocess stdin
3.4s: ================= Subprocess Exited =================
3.4s: SubProcess exited - Exit code: 0
3.4s: ----------------------------------------
3.4s: Subprocess stdout:
2.2s: Subprocess started!  Waiting for input...
2.2s: Received 'exit'.  Exiting...
3.4s: Subprocess stderr:
3.4s: ----------------------------------------
3.5s: Test passed: True
3.5s:
3.5s: ::== Running test: TEST_TracesHaveRelevantEvents
3.6s: Server name is '/tmp/DOTNET_TRACE_TESTS_4dymwyfx.ylt'
3.6s: running sub-process: /root/helix/work/correlation/corerun /root/helix/work/workitem/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll 0
3.6s: subprocess started: True
3.6s: subprocess PID: 6594
3.6s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
3.8s: { Magic=System.Byte[]; ClrInstanceId=b2086826-afe3-49a8-815b-224d23d878f8; ProcessId=6594; Unused=0; }
3.8s: Starting EventPipeSession over standard connection
4.0s: Started EventPipeSession over standard connection with session id: 0xe72c29b0
4.0s: Send ResumeRuntime Diagnostics IPC Command
4.0s: Sent: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=1; Reserved=0 }; }
4.0s: received: { Header={ Magic=System.Byte[]; Size=24; CommandSet=255; CommandId=0; Reserved=0 }; Payload=[ 0x00 0x00 0x00 0x00  ]}
6.0s: Stopping EventPipeSession over standard connection
6.5s: Stopped EventPipeSession over standard connection
6.5s: Sending 'exit' to subprocess stdin
6.5s: ================= Subprocess Exited =================
6.5s: SubProcess exited - Exit code: 0
6.5s: ----------------------------------------
6.5s: Subprocess stdout:
1.3s: Subprocess started!  Waiting for input...
2.9s: Received 'exit'.  Exiting...
6.5s: Subprocess stderr:
6.5s: ----------------------------------------
7.3s: isStartupEventPresent: True
7.3s: Test passed: True
7.3s:
7.3s: ::== Running test: TEST_MultipleSessionsCanBeStartedWhilepaused
7.4s: Server name is '/tmp/DOTNET_TRACE_TESTS_oh4tuea5.4vj'
7.4s: running sub-process: /root/helix/work/correlation/corerun /root/helix/work/workitem/e/tracing/eventpipe/pauseonstart/pauseonstart/pauseonstart.dll 0
7.4s: subprocess started: True
7.4s: subprocess PID: 6608
7.4s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
7.6s: { Magic=System.Byte[]; ClrInstanceId=92451341-b197-4047-b5a3-eb86f3de9d7e; ProcessId=6608; Unused=0; }
7.6s: Starting EventPipeSession over standard connection
7.6s: Started EventPipeSession over standard connection with session id: 0xeb3e79b0
7.6s: Starting EventPipeSession over standard connection
7.6s: Started EventPipeSession over standard connection with session id: 0xeb245410
7.6s: Starting EventPipeSession over standard connection
7.6s: Started EventPipeSession over standard connection with session id: 0xeb245470
7.6s: Send ResumeRuntime Diagnostics IPC Command
7.6s:


Stack trace
   at tracing_eventpipe._pauseonstart_pauseonstart_pauseonstart_._pauseonstart_pauseonstart_pauseonstart_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
@dotnet/dotnet-diag

**Comment by tommcdon** [comment]
@davmason would you mind taking a look?
