### ISSUE TITLE
Test failure JIT/opt/ValueNumbering/ExposedLocalsNumbering/ExposedLocalsNumbering.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80595]
Run: [runtime-coreclr jitstress 20230111.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=134839&view=ms.vss-test-web.build-test-results-tab&runId=2929352&paneView=debug&resultId=120077)

Failed test:
```
coreclr osx x64 Checked tailcallstress @ OSX.1200.Amd64.Open

- JIT/opt/ValueNumbering/ExposedLocalsNumbering/ExposedLocalsNumbering.sh
```
**Error message:**
```
Assert failure(PID 53516 [0x0000d10c], Thread: 6763099 [0x67325b]): !config->ShouldCountCalls() || pMethodDesc->IsEligibleForTieredCompilation()
File: /Users/runner/work/1/s/src/coreclr/vm/codeversion.cpp Line: 1721
Image: /private/tmp/helix/working/AF8609C0/p/corerun

[createdump] Invalid process id: task_for_pid(53516) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/AF8609C0/w/9A8A08C7/e/JIT/opt/ValueNumbering/ExposedLocalsNumbering/ExposedLocalsNumbering.sh: line 427: 53516 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/AF8609C0/w/9A8A08C7/uploads/Reports/JIT.opt/ValueNumbering/ExposedLocalsNumbering/ExposedLocalsNumbering.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/AF8609C0/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ExposedLocalsNumbering.dll ''
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/AF8609C0/p
/private/tmp/helix/working/AF8609C0/w/9A8A08C7/e/JIT/opt/ValueNumbering/ExposedLocalsNumbering/ExposedLocalsNumbering.sh
Expected: True
Actual:   False


Stack trace
   at JIT_opt._ValueNumbering_ExposedLocalsNumbering_ExposedLocalsNumbering_._ValueNumbering_ExposedLocalsNumbering_ExposedLocalsNumbering_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by SingleAccretion** [comment]
This run was on the commit immediately preceding d87f7b2b81647917528286d91ed91db2a34b0985 (da2c147a9c129b00ef09b88a7309754cb09e193d).
