### ISSUE TITLE
System.TypeInitializationException: PosixSignalRegistration at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

### ISSUE THREAD

**Issue by jinek** [dotnet/runtime#80686]
### Description

Application packed into a container based on `mcr.microsoft.com/dotnet/aspnet:7.0`  randomly failed to start with following exception:
```
2023-01-15T15:42:37.534862799Z AppDomainException: System.TypeInitializationException: The type initializer for 'System.Runtime.InteropServices.PosixSignalRegistration' threw an exception.
2023-01-15T15:42:37.534946627Z  ---> System.IO.IOException: The process cannot access the file because it is being used by another process.
2023-01-15T15:42:37.534951827Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2023-01-15T15:42:37.534954662Z    at System.Runtime.InteropServices.PosixSignalRegistration.Initialize()
2023-01-15T15:42:37.534957287Z    at System.Runtime.InteropServices.PosixSignalRegistration..cctor()
2023-01-15T15:42:37.534965352Z    --- End of inner exception stack trace ---
2023-01-15T15:42:37.534968067Z    at System.Runtime.InteropServices.PosixSignalRegistration.Register(PosixSignal signal, Action`1 handler)
2023-01-15T15:42:37.534970742Z    at Microsoft.Extensions.Hosting.Internal.ConsoleLifetime.RegisterShutdownHandlers()
2023-01-15T15:42:37.534973337Z    at Microsoft.Extensions.Hosting.Internal.ConsoleLifetime.WaitForStartAsync(CancellationToken cancellationToken)
2023-01-15T15:42:37.534975962Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-01-15T15:42:37.534978517Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-01-15T15:42:37.534981132Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-01-15T15:42:37.534983737Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-01-15T15:42:37.534986302Z    at Program.<Main>$(String[] args) in /src/**********/Program.cs:line 126
2023-01-15T15:42:37.541518249Z Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Runtime.InteropServices.PosixSignalRegistration' threw an exception.
2023-01-15T15:42:37.541533347Z  ---> System.IO.IOException: The process cannot access the file because it is being used by another process.
2023-01-15T15:42:37.541538617Z    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2023-01-15T15:42:37.541542164Z    at System.Runtime.InteropServices.PosixSignalRegistration.Initialize()
2023-01-15T15:42:37.541545109Z    at System.Runtime.InteropServices.PosixSignalRegistration..cctor()
2023-01-15T15:42:37.541548586Z    --- End of inner exception stack trace ---
2023-01-15T15:42:37.541551982Z    at System.Runtime.InteropServices.PosixSignalRegistration.Register(PosixSignal signal, Action`1 handler)
2023-01-15T15:42:37.541555038Z    at Microsoft.Extensions.Hosting.Internal.ConsoleLifetime.RegisterShutdownHandlers()
2023-01-15T15:42:37.541559657Z    at Microsoft.Extensions.Hosting.Internal.ConsoleLifetime.WaitForStartAsync(CancellationToken cancellationToken)
2023-01-15T15:42:37.541562703Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-01-15T15:42:37.541565548Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-01-15T15:42:37.541591397Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-01-15T15:42:37.541595404Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-01-15T15:42:37.541598029Z    at Program.<Main>$(String[] args) in /src/**********/Program.cs:line 126
```
I understand this is probably related to the state of the overall system, but just want to check because the container itself is pure aspdotnet:7
Also we have `System.TypeInitializationException` which means we can not run another host in current process.

### Reproduction Steps

Do not know how to reproduce.

### Expected behavior

`Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)` should start with no exceptions.

### Actual behavior

Exception of type TypeInitializationException thrown.

### Regression?

I could not find any mentions of this issue.

### Configuration

Ran with approximately this Dockerfile:
```
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "*********.dll"]
```

**Comment by buyaa-n** [comment]
@jinek it would be very helpful if you provide some repro

**Comment by jinek** [comment]
> @jinek it would be very helpful if you provide some repro

Sorry, I don't know how to reproduce. Is it possible that the exception is thrown by runtime when loading assembly of `https://github.com/dotnet/runtime/blob/9fd407ae7a1b6a846a60fc0269b60d984b0e3c0b/src/libraries/Common/src/Interop/Unix/System.Native/Interop.InitializeTerminalAndSignalHandling.cs#L12` (because assembly module file is busy by some another process) ?

**Comment by buyaa-n** [comment]
It might be Interop issue CC @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
I don't think this is an interop issue based on the current details.

@jinek I would suggest trying to collect a DMP of the crash to narrow down the failure. https://learn.microsoft.com/dotnet/core/diagnostics/dumps
