### ISSUE TITLE
Test failure tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd 

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80680]
Run: [runtime-coreclr ilasm 20230114.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=137887&view=ms.vss-test-web.build-test-results-tab&runId=2999018&resultId=122104&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

coreclr linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

coreclr linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr osx x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr osx arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\B94E09EE\w\C3920A54\uploads\Reports\tracing.eventpipe\diagnosticport\diagnosticport\diagnosticport.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\B94E09EE\p\ildasm.exe /raweh /unicode /out=diagnosticport.dasm.il diagnosticport.dll
C:\h\w\B94E09EE\p\ilasm.exe /output=diagnosticport.asm.dll  diagnosticport.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'diagnosticport.dasm.il'  to EXE --> 'diagnosticport.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::.cctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::<TEST_CanGetProcessInfo2WhileSuspended>b__6_0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::<TEST_CanGetProcessInfo2WhileSuspended>b__6_1
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::<Main>b__7_0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0?<<TEST_MultipleConnectPortsNoSuspend>b__0>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0?<<TEST_MultipleConnectPortsNoSuspend>b__0>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0::<TEST_MultipleConnectPortsNoSuspend>b__0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1?<<TEST_MultipleConnectPortsNoSuspend>b__1>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1?<<TEST_MultipleConnectPortsNoSuspend>b__1>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1::<TEST_MultipleConnectPortsNoSuspend>b__1
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0?<<TEST_MultipleConnectPortsSuspend>b__0>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0?<<TEST_MultipleConnectPortsSuspend>b__0>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0::<TEST_MultipleConnectPortsSuspend>b__0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1?<<TEST_MultipleConnectPortsSuspend>b__1>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1?<<TEST_MultipleConnectPortsSuspend>b__1>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1::<TEST_MultipleConnectPortsSuspend>b__1
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1::<TEST_MultipleConnectPortsSuspend>b__2
Assembled method Tracing.Tests.DiagnosticPortValidation.Dia


Stack trace
   at tracing_eventpipe._diagnosticport_diagnosticport_diagnosticport_._diagnosticport_diagnosticport_diagnosticport_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by tommcdon** [comment]
@BruceForstall - it seems this test is not compatible with ilasm/ildasm tests, and so we should exclude this test.  Would you mind following up?

Relevant output:

```
        5.2s: ::== Running test: TEST_CanGetProcessInfo2WhileSuspended
        5.2s: running sub-process: C:\h\w\B94E09EE\p\corerun.exe C:\h\w\B94E09EE\w\C3920A54\e\tracing\eventpipe\diagnosticport\diagnosticport\diagnosticport.asm.dll 0
        5.2s: subprocess started: True
        5.2s: subprocess PID: 9128
        5.2s: Standard Diagnostics Server connection not created yet -> try again in 100 ms
        5.3s: Wrote: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=4; Reserved=0 }; }
        5.3s: Received: [A8 23 00 00 00 00 00 00 95 B6 60 F2 1A 9E 1F 41 AB 1D DF 13 6C 9B 8B 28 86 00 00 00 22 00 43 00 3A 00 5C 00 68 00 5C 00 77 00 5C 00 42 00 39 00 34 00 45 00 30 00 39 00 45 00 45 00 5C 00 70 00 5C 00 63 00 6F 00 72 00 65 00 72 00 75 00 6E 00 2E 00 65 00 78 00 65 00 22 00 20 00 43 00 3A 00 5C 00 68 00 5C 00 77 00 5C 00 42 00 39 00 34 00 45 00 30 00 39 00 45 00 45 00 5C 00 77 00 5C 00 43 00 33 00 39 00 32 00 30 00 41 00 35 00 34 00 5C 00 65 00 5C 00 74 00 72 00 61 00 63 00 69 00 6E 00 67 00 5C 00 65 00 76 00 65 00 6E 00 74 00 70 00 69 00 70 00 65 00 5C 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 5C 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 5C 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 2E 00 61 00 73 00 6D 00 2E 00 64 00 6C 00 6C 00 20 00 30 00 00 00 08 00 00 00 57 00 69 00 6E 00 64 00 6F 00 77 00 73 00 00 00 06 00 00 00 61 00 72 00 6D 00 36 00 34 00 00 00 13 00 00 00 64 00 69 00 61 00 67 00 6E 00 6F 00 73 00 74 00 69 00 63 00 70 00 6F 00 72 00 74 00 2E 00 61 00 73 00 6D 00 00 00 09 00 00 00 38 00 2E 00 30 00 2E 00 30 00 2D 00 63 00 69 00 00 00 ]
        5.5s: System.Exception: ManagedEntrypointAssemblyName must match. Expected: diagnosticport, Received: diagnosticport.asm
         at Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation.<>c.<TEST_CanGetProcessInfo2WhileSuspended>b__6_0(Int32 pid)
         at Tracing.Tests.Common.Utils.RunSubprocess(Assembly currentAssembly, Dictionary`2 environment, Func`1 beforeExecution, Func`2 duringExecution, Func`1 afterExecution)
```

**Comment by BruceForstall** [comment]
@elinor-fung Looks like you changed this test in a way that is not compatible with ilasm/ildasm round-trip testing:

```
System.Exception: ManagedEntrypointAssemblyName must match. Expected: diagnosticport, Received: diagnosticport.asm
```

If you can't make it work, you can add:
```
<IlasmRoundTripIncompatible>true</IlasmRoundTripIncompatible>
```

to the test proj file.

**Comment by elinor-fung** [comment]
Thanks, @BruceForstall. https://github.com/dotnet/runtime/pull/80766 should address this.
