### ISSUE TITLE
Test failure tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80767]
Run: [runtime-coreclr jitstress 20230116.4](https://dev.azure.com/dnceng-public/public/_build/results?buildId=139245&view=ms.vss-test-web.build-test-results-tab&runId=3023292&resultId=121571&paneView=debug)

Failed test:
```
coreclr osx x64 Checked jitstress2 @ OSX.1200.Amd64.Open

- tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh
```
**Error message:**
```
Unhandled exception. System.Exception: Condition 'noEventsListener.EventCount == 0' is not true
at Tracing.Tests.NativeRuntimeEventSourceTest.Main()
[createdump] Invalid process id: task_for_pid(4517) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/C00A09FF/w/A33F091C/e/tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh: line 439:  4517 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/C00A09FF/w/A33F091C/uploads/Reports/tracing.runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/C00A09FF/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false nativeruntimeeventsource.dll ''
[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2635705
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "44.857142857142854"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2731720
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "46.608695652173914"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2732357
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "45.04347826086956"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2733144
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "44.47826086956522"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2733732
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "44.73913043478261"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2734600
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "44.391304347826086"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2735088
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "44.391304347826086"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 58 Name = YieldProcessorMeasurement
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2735505
Name = "ClrInstanceID" Value = "0"
Name = "NsPerYield" Value = "44.391304347826086"
Name = "EstablishedNsPerYield" Value = "44.391304347826086"

[Simple] ThreadID = 3676695 ID = 200 Name = IncreaseMemoryPressure
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2734441
Name = "BytesAllocated" Value = "3672"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 3676695 ID = 70 Name = ThreadCreating
TimeStamp: 1/17/2023 1:12:53 AM
LocalTime: 1/17/2023 1:12:54 AM
Difference: 00:00:00.2734930
Name = "ID" Value = "140635877237776"
Name = "ClrInstanceID" Value = "0"

[Simple] ThreadID = 3676717 ID = 85 Name = ThreadCreated


Stack trace
   at tracing_runtimeeventsource._nativeruntimeeventsource_nativeruntimeeventsource_._nativeruntimeeventsource_nativeruntimeeventsource_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
@tommcdon
