### ISSUE TITLE
The token supplied to the function is invalid at System.Net.NTAuthentication.GetOutgoingBlob

### ISSUE THREAD

**Issue by hajekj** [dotnet/runtime#80781]
### Description

When using HttpClient in parallel, Windows Authentication (NTLM) seems to fail some requests with following error: `The token supplied to the function is invalid`
**Stack trace:**
```
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.<SendWithNtAuthAsync>d__53.MoveNext()
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__83.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.AuthenticationHelper.<SendWithAuthAsync>d__17.MoveNext()
   at System.Net.Http.DiagnosticsHandler.<SendAsyncCore>d__8.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at PCT20018NtlmTest.Program.<>c__DisplayClass1_0.<<DoSomething>b__0>d.MoveNext() in C:\Users\hajek\Scratch\PCT20018NtlmTest\PCT20018NtlmTest\Program.cs:line 45
```

This happens when sending requests both over HTTP and HTTPS.

### Reproduction Steps

1. I have a machine running in Azure with Windows Server 2019 Datacenter (build 10.0.17763). The server has IIS installed and Windows Authentication enabled on default site.
1. When I run following code (dependent on `AsyncEnumerator` package):
```csharp
using Dasync.Collections;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace PCT20018NtlmTest
{
	internal class Program
	{
		static void Main(string[] args)
		{
			DoSomething().Wait();
		}

		static async Task DoSomething()
		{
			var baseUrl = "http://13.94.243.22/";
			var messageHandler = new HttpClientHandler
			{
				Credentials = new NetworkCredential("AzureUser", "mysuperstrongpwd.1", ".")
			};
			var httpClient = new HttpClient(messageHandler)
			{
				BaseAddress = new Uri(baseUrl),
			};

			var collection = new List<string>();
			for (var a = 0; a < 1000; a++)
			{
				collection.Add(a.ToString());
			}

			await collection.ParallelForEachAsync(async x =>
			{
				try
				{
					var result = await httpClient.GetAsync("/");
					result.EnsureSuccessStatusCode();
				}
				catch (Exception e)
				{

				}
			}, maxDegreeOfParallelism: 20);
		}
	}
}
```
1. Some of the requests pass through, however some start throwing the exception `The token supplied to the function is invalid`

### Expected behavior

I expect all requests to complete successfully.

### Actual behavior

Some requests fail (in my case 8 out of 1,000).

### Configuration

Running on Windows 22H2 (25276.1000) with .NET 6.0 `6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]` x64

**Comment by filipnavara** [comment]
Are you able to catch the error in debugger on first-chance exception? If yes, would you be willing to share a memory dump saved from the debugger?

**Comment by wfurt** [comment]
I could not reproduce it on my Win11 VM with 6.0.8. I agree with @filipnavara that using current release(s) is worth of shot. 
And thanks for the repro & site. It is very useful.

**Comment by honzakostejn** [comment]
I've successfully ran the code 8 times without any exception.

Running on Windows 10 21H2 (19044.2486) with .NET 6.0 LTS.

**Comment by hajekj** [comment]
@filipnavara Yes, I am able to catch the error. This doesn't seem to be happening to me on .NET 7.0 (`7.0.100 [C:\Program Files\dotnet\sdk]`).

Memory dump from debugger: https://thenetworg-my.sharepoint.com/:u:/g/personal/jan_hajek_thenetw_org/EUe3SIXiKkpOhOCfcmk3k2IBuioilexkzV9bOqehlRTeJg?e=JSEZfV

**Comment by filipnavara** [comment]
Unfortunately the dump is taken only after the exception was caught. I'd need it when the exception is thrown, ie. with this setting:

![image](https://user-images.githubusercontent.com/1764393/213413939-fc9e7ef8-fc90-430c-8a48-ba02b5c8ce5c.png)

I tried to reproduce it with .NET 7.0.2 and 6.0.13 (SDK 6.0.405). It didn't throw the exception with either of them on my machine (Windows 11 22H2).

**Comment by hajekj** [comment]
Apologies, here should be correct dump: https://thenetworg-my.sharepoint.com/:u:/g/personal/jan_hajek_thenetw_org/Edot_B0GkAVLhXUVIef_h30BmNRLz8E5alysSzlkOpEy5A?e=cdVUUm

**Comment by hajekj** [comment]
I also did Fiddler trace on .NET 7.0 build, but wasn't able to figure anything specific from it. Also if you want, we can do some remote session via Teams, or whatever you prefer, if you want to dig deeper. I also tried with Wireshark, but also wasn't able to figure anything specific out.

It doesn't seem to happen when I set `maxDegreeOfParallelism` to `5`, but happens when I set it to `6` and higher.

[fiddlertracenet7.zip](https://github.com/dotnet/runtime/files/10455885/fiddlertracenet7.zip)

**Comment by filipnavara** [comment]
The Fiddler trace doesn't seem to be very useful in this particular case. It's a session-based authentication, so it's normal to see 401 errors during the first steps. There's 6 session that go through the authentication process, 5 of them reach the full exchange (ie. all three NTLM messages back and forth). One of them does not and the last request is not present in the Fiddler trace. That likely means just that .NET 7 reports the "invalid token" error as "401 Unauthorized" (last reply from server). That's expected change of behavior that was intentionally done to match documented exceptions. Internally it likely fails with the same API error on the Win32 API call.

I'll look at the dump next.

**Comment by MaceWindu1** [comment]
I've run the code on my Windows 11 22H2 Build 22621.1105 and got the same exception (.NET 6.0).

**Comment by filipnavara** [comment]
There's actually one interesting thing in the Fiddler trace. The very last successful request reused an existing session and skipped the authentication. I previously didn't consider that connection pooling may have some effect.
 
Unfortunately, the dump seems a bit difficult to analyze due to the async exceptions / stack traces. Not sure I will find anything useful in it.

> I've run the code on my Windows 11 22H2 Build 22621.1105 and got the same exception (.NET 6.0).

That's the same build I have FWIW. I tried to change the parameters (number of iterations, degree of parallelism) and it didn't reproduce on my machine so far.

**Comment by hajekj** [comment]
I ran through the code with symbols loaded for .NET, and I managed to get to method `NegotiateStreamPal.InitializeSecurityContext` which seems to return `statusCode.ErrorCode = InvalidToken` which probably comes from here: https://github.com/dotnet/runtime/blob/f429780c9ccce3546e9c9e25c05ed083318428bd/src/libraries/Common/src/System/Net/Security/NegotiateStreamPal.Windows.cs#L21 (but VS doesn't let me go into this method).

**Comment by filipnavara** [comment]
> The difference in behavior compared to 7.0 is also curious.

The difference between .NET 6 and .NET 7 is easy to explain. It was deliberate change not to propagate `Win32Exception` from a the authentication code. The are two reasons for that. First, the exception now doesn't happen in the first place since the status code is propagated as enum from `NegotiateAuthentication` and not as exception. Second, `HttpClient.Send[Async]` was never documented to throw `Win32Exception`. It now either ends up returning the last 401 Unauthorized response with the "invalid token", or in other cases throws `HttpRequestException`.

**Comment by hajekj** [comment]
@filipnavara - since I can see you are Prague based as well, we could arrange to share the affected computer with you if it would provide any help.

**Comment by filipnavara** [comment]
> @filipnavara - since I can see you are Prague based as well, we could arrange to share the affected computer with you if it would provide any help.

I don't want to set your expectations too high. I am just a community triager and contributor that happened to dig into the NTLM/Negotiate code a lot over the past year.

That said, drop me a note at filip.navara (at) gmail.com, and let's see if I can come up with more ideas on what to try and what diagnostic information would be worth collecting.

**Comment by karelz** [comment]
We are thinking about holistic error code propagation from HttpClient (see #76644) - I wonder if this is related and we should keep that in mind - cc @antonfirsov

**Comment by hajekj** [comment]
We met with @filipnavara in person, and I am posting some debug information. Code snippet:

```csharp
var blob = auth.GetOutgoingBlob((string?)null, out var statusCode);
Debug.Assert(blob != null);
Debug.Assert(statusCode == NegotiateAuthenticationStatusCode.ContinueNeeded);
var blob2 = auth.GetOutgoingBlob("TlRMTVNTUAACAAAAHgAeADgAAAAVgoriyDx605ofbuYAAAAAAAAAAJgAmABWAAAACgBjRQAAAA9wAGMAdAAyADIAMAAwADQALQBwAG8AaABvAGQAYQACAB4AcABjAHQAMgAyADAAMAA0AC0AcABvAGgAbwBkAGEAAQAeAHAAYwB0ADIAMgAwADAANAAtAHAAbwBoAG8AZABhAAQAHgBwAGMAdAAyADIAMAAwADQALQBwAG8AaABvAGQAYQADAB4AcABjAHQAMgAyADAAMAA0AC0AcABvAGgAbwBkAGEABwAIAApGrtiHMdkBAAAAAA==", out statusCode);
Debug.Assert(blob != null);
Debug.Assert(statusCode == NegotiateAuthenticationStatusCode.Completed);
```

Debug output: [output.txt](https://github.com/dotnet/runtime/files/10509871/output.txt)

Thanks again Filip, for your time and help!

**Comment by filipnavara** [comment]
To offer some context for the trace output above. The test case fails on the affected machine. The third column in the log file is the thread id (`[22]` iirc). Walking back from the failure we can see it happens when processing the Challenge NTLM token. I tried to manually take the token from trace and inject it into `NegotiateAuthentication` to artificially reproduce the failure. It accepts the token just fine though...

This leaves basically three possible causes of the issue:
1) Buffer mishandling
2) The NTAuthentication/NegotiateAuthentication context being unintentionally reset between the initial HTTP request with `Authorization:` header and the reply with the token that is processed
3) Intermittent failure in the Windows SSPI itself

**Comment by ManickaP** [comment]
Triage: we were able to reproduce it, we should figure out what is happening in 8.0 and fix it.

**Comment by hajekj** [comment]
Once there is a version of 8.0 to test against, please let me know. Will try it as well.

**Comment by filipnavara** [comment]
> Once there is a version of 8.0 to test against, please let me know. Will try it as well.

.NET 8 Preview 1 branched out this week. However, there are no changes relevant to this issue AFAICT.

**Comment by SteveSyfuhs** [comment]
Is channel binding configured on the client or server?

**Comment by filipnavara** [comment]
> Is channel binding configured on the client or server?

It was observed when connecting to `http` endpoint so no TLS channel binding was present AFAICT.

**Comment by wfurt** [comment]
Reading through the thread, this does not seems like recent regression, right? e.g. failing with 6.0 and 7.0.
I assume this is still problem @hajekj? 
I should be able to dedicate some time in next few weeks but the test site seems to be down. 
If you want to still pursue this can you please shoot email to my GH address?

**Comment by hajekj** [comment]
I have reinstalled my computer since and haven't encountered the issue.

**Comment by wfurt** [comment]
Thanks for the update @hajekj . Since this seems environmental and specific to particular single instance I'm inclined to just close it. 
Long run Im wondering @filipnavara if it would be useful to add one switch to force managed implementation even on platforms with GSSAPI. Or make it default for "NTLM" and leave GSSAPI to handle "Negotiate". But I feel that would be separate from this particular issue.

**Comment by filipnavara** [comment]
> Long run Im wondering @filipnavara if it would be useful to add one switch to force managed implementation even on platforms with GSSAPI. Or make it default for "NTLM" and leave GSSAPI to handle "Negotiate". But I feel that would be separate from this particular issue.

I would definitely be inclined to add this switch. Ideally we would allow switching both NTLM and SPNEGO to managed implementation. I started some work on refactoring the code to make it possible but it was too late to land it for .NET 7 and I didn't revisit it since then...

**Comment by karelz** [comment]
Triage: Not able to reproduce anymore, closing.
We can move discussion about further improvements in the space offline.
