### ISSUE TITLE
ResourceManager not threadsafe when case insensitive keys are used

### ISSUE THREAD

**Issue by tl-laurence** [dotnet/runtime#80790]
### Description

Using resource manager in a high load environment we see errors occurring and strings being read incorrectly. This only happens when the `IgnoreCase` property is `true`.

Error message: `Corrupt .resources file. Invalid offset '503403335' into data section.`

Stack:
`
  at System.Resources.ResourceReader.AllocateStringForNameIndex(Int32 index, Int32& dataOffset)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetString(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
`

### Reproduction Steps

This test fails intermittently but more frequently after a clean rebuild

```cs
[TestFixture]
public class ResourceManagerTest
{
    [Test]
    public void GivenCaseInvariantResources_ThenNoErrors()
    {
        Parallel.For(0, 1000, (i) =>
         {
             var resourceMan = new System.Resources.ResourceManager("MyBaseName", typeof(MyAssembly).Assembly);
             resourceMan.IgnoreCase = true;

             Parallel.For(0, 1000, (i) =>
             {
                 var key = "key_that_exists_but_not_in_same_case_as_resources";
                 resourceMan.GetString(key);
             });
         });
    }
}
```

### Expected behavior

The resource should be read without an error as the class is marked as thread safe.

### Actual behavior

Error message: `Corrupt .resources file. Invalid offset '503403335' into data section.`

Stack:
`
  at System.Resources.ResourceReader.AllocateStringForNameIndex(Int32 index, Int32& dataOffset)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetString(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
`

After the error occurs once **resource strings are read incorrectly without and further errors** until the application is restarted

### Known Workarounds

Don't use the IgnoreCase flag

### Configuration

.NET 6.0
Errors occurs on:
 - Windows 10 Pro x64
 - Ubuntu 18.4 x64

**Comment by steveharter** [comment]
Appears to be a bug. That method is doc'd as being "thread safe"

Thread Safety
The [GetString(String)](https://learn.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager.getstring?view=net-7.0#system-resources-resourcemanager-getstring(system-string)) method is thread safe.

**Comment by steveharter** [comment]
@tl-laurence is the resource file special in any way (lots of items?) or is it changed at runtime? 

Basically wondering how to best repro this.

**Comment by tarekgh** [comment]
Is this different than https://github.com/dotnet/runtime/issues/74052?

**Comment by tl-laurence** [comment]
Yes it looks like it could be the same issue as #74053. I will have a go at testing with the suggested version. 

@steveharter there is nothing special about the resource files. We have multiple languages configured but can reproduce with a single culture.

It is the IgnoreCase flag and the use of a key that is not in the correct case that causes it from what I have found.

We removed the ignorecase and looked up the keys in a concurrent dictionary instead as a workaround which has stopped the errors.

**Comment by danmoseley** [comment]
@tl-laurence did you verify it's fixed?

**Comment by tl-laurence** [comment]
Yes this is fixed in .Net 8
