### ISSUE TITLE
[wasm] *all* `perf` microbenchmarks crashing with AOT+v8

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#80834]
Seeing these on `dotnet-runtime-perf` pipeline. I was able to reproduce it with a test https://github.com/dotnet/runtime/pull/80796 .
Example crash in [20230118.9](https://dev.azure.com/dnceng/internal/_build/results?buildId=2091641&view=results):

```
MONO_WASM: mono_wasm_load_runtime () failed: {}
MONO_WASM: Stacktrace:

RuntimeError: memory access out of bounds
    at decode_uint_with_len (wasm://wasm/105aef92:wasm-function[175039]:0x368a9d1)
    at find_aot_method_in_amodule (wasm://wasm/105aef92:wasm-function[175005]:0x3687c0f)
    at find_aot_method (wasm://wasm/105aef92:wasm-function[175004]:0x3687a13)
    at mono_aot_get_method (wasm://wasm/105aef92:wasm-function[175010]:0x368836c)
    at jit_compile_method_with_opt_cb (wasm://wasm/105aef92:wasm-function[174856]:0x367c577)
    at invoke_vi (/home/helixbot/work/A08F08B6/w/B50E09FC/e/performance/artifacts/bin/for-running/MicroBenchmarks/37d0da3d-9db0-43bb-834e-9def1f0eec4a/bin/net8.0/browser-wasm/AppBundle/dotnet.js:14:232529)
    at mono_llvm_cpp_catch_exception (wasm://wasm/105aef92:wasm-function[166598]:0x34db1ed)
    at jit_compile_method_with_opt (wasm://wasm/105aef92:wasm-function[174855]:0x367c384)
    at mono_jit_compile_method_jit_only (wasm://wasm/105aef92:wasm-function[174857]:0x367ccfa)
    at do_jit_call (wasm://wasm/105aef92:wasm-function[166293]:0x34c05a3)
MONO_WASM: Error in mono_wasm_before_user_runtime_initialized: {}
MONO_WASM: Stacktrace:

RuntimeError: memory access out of bounds
    at decode_uint_with_len (wasm://wasm/105aef92:wasm-function[175039]:0x368a9d1)
    at find_aot_method_in_amodule (wasm://wasm/105aef92:wasm-function[175005]:0x3687c0f)
    at find_aot_method (wasm://wasm/105aef92:wasm-function[175004]:0x3687a13)
    at mono_aot_get_method (wasm://wasm/105aef92:wasm-function[175010]:0x368836c)
    at mono_interp_jit_call_supported (wasm://wasm/105aef92:wasm-function[166424]:0x34c41fc)
    at interp_transform_call (wasm://wasm/105aef92:wasm-function[166462]:0x34ce802)
    at generate_code (wasm://wasm/105aef92:wasm-function[166445]:0x34c773c)
    at mono_interp_transform_method (wasm://wasm/105aef92:wasm-function[166505]:0x34d0fc9)
    at do_transform_method (wasm://wasm/105aef92:wasm-function[166283]:0x34bffde)
    at mono_interp_exec_method (wasm://wasm/105aef92:wasm-function[166282]:0x34bfd82)
MONO_WASM: onRuntimeInitializedAsync() failed: {}
MONO_WASM: Stacktrace:

RuntimeError: memory access out of bounds
    at decode_uint_with_len (wasm://wasm/105aef92:wasm-function[175039]:0x368a9d1)
    at find_aot_method_in_amodule (wasm://wasm/105aef92:wasm-function[175005]:0x3687c0f)
    at find_aot_method (wasm://wasm/105aef92:wasm-function[175004]:0x3687a13)
    at mono_aot_get_method (wasm://wasm/105aef92:wasm-function[175010]:0x368836c)
    at mono_interp_jit_call_supported (wasm://wasm/105aef92:wasm-function[166424]:0x34c41fc)
    at interp_transform_call (wasm://wasm/105aef92:wasm-function[166462]:0x34ce802)
    at generate_code (wasm://wasm/105aef92:wasm-function[166445]:0x34c773c)
    at mono_interp_transform_method (wasm://wasm/105aef92:wasm-function[166505]:0x34d0fc9)
    at do_transform_method (wasm://wasm/105aef92:wasm-function[166283]:0x34bffde)
    at mono_interp_exec_method (wasm://wasm/105aef92:wasm-function[166282]:0x34bfd82)
RuntimeError: memory access out of bounds
    at decode_uint_with_len (wasm://wasm/105aef92:wasm-function[175039]:0x368a9d1)
    at find_aot_method_in_amodule (wasm://wasm/105aef92:wasm-function[175005]:0x3687c0f)
    at find_aot_method (wasm://wasm/105aef92:wasm-function[175004]:0x3687a13)
    at mono_aot_get_method (wasm://wasm/105aef92:wasm-function[175010]:0x368836c)
    at mono_interp_jit_call_supported (wasm://wasm/105aef92:wasm-function[166424]:0x34c41fc)
    at interp_transform_call (wasm://wasm/105aef92:wasm-function[166462]:0x34ce802)
    at generate_code (wasm://wasm/105aef92:wasm-function[166445]:0x34c773c)
    at mono_interp_transform_method (wasm://wasm/105aef92:wasm-function[166505]:0x34d0fc9)
    at do_transform_method (wasm://wasm/105aef92:wasm-function[166283]:0x34bffde)
    at mono_interp_exec_method (wasm://wasm/105aef92:wasm-function[166282]:0x34bfd82)
WASM EXIT 1
exiting due to exception: RuntimeError: memory access out of bounds
```

Another for `Benchmark: Burgers.Burgers_1`:
```
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2784, condition `<disabled>' not met

    at se (/home/helixbot/work/A08F08B6/w/B87409E5/e/performance/artifacts/bin/for-running/MicroBenchmarks/062c331c-cdbd-400f-a2f2-c1e9faf023c6/bin/net8.0/browser-wasm/AppBundle/dotnet.js:5:521)
    at ie (/home/helixbot/work/A08F08B6/w/B87409E5/e/performance/artifacts/bin/for-running/MicroBenchmarks/062c331c-cdbd-400f-a2f2-c1e9faf023c6/bin/net8.0/browser-wasm/AppBundle/dotnet.js:5:811)
    at wasm_trace_logger (wasm://wasm/104a36f6:wasm-function[175577]:0x36862d1)
    at eglib_log_adapter (wasm://wasm/104a36f6:wasm-function[169158]:0x353edb9)
    at monoeg_g_logv_nofree (wasm://wasm/104a36f6:wasm-function[175054]:0x3664f17)
    at monoeg_assertion_message (wasm://wasm/104a36f6:wasm-function[175057]:0x3664fab)
    at mono_assertion_message (wasm://wasm/104a36f6:wasm-function[175059]:0x3664ff2)
    at mono_assertion_message_disabled (wasm://wasm/104a36f6:wasm-function[175058]:0x3664fc3)
    at do_jit_call (wasm://wasm/104a36f6:wasm-function[165986]:0x3489394)
    at mono_interp_exec_method (wasm://wasm/104a36f6:wasm-function[165975]:0x347d0a4)
No Workload Results were obtained from the run.
// Benchmark Process 11939 has exited with code 1.
```

This started showing up with https://dev.azure.com/dnceng/internal/_build/results?buildId=2091264&view=results which built 6e773f2b73db1f1b04e5292725a99cf48be84428:
```
commit 6e773f2b73db1f1b04e5292725a99cf48be84428
Author: Zoltan Varga <vargaz@gmail.com>
Date:   Wed Jan 18 06:30:09 2023 -0500

    [mono][aot] Optimize the layout of the extra_method_table. (#80682)
```

The runs for the PR used `V8 version: 11.0.162`.

cc @vargaz @BrzVlad 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
Fixed by #80839 .
