### ISSUE TITLE
[Mono] System.Reflection.Metadata.Tests.MetadataReaderTests.GetAssemblyName is failing

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#80863]
The changes in #80581 cause the [rolling build of runtime-extra-platforms](https://dev.azure.com/dnceng-public/public/_build/results?buildId=142070&view=ms.vss-test-web.build-test-results-tab&runId=3085811&resultId=143807&paneView=debug) to fail.

Ref #77697

On `android-arm64`, `android-arm`, `tvos-arm64`:
```
Assert.Equal() Failure
Expected: MSIL
Actual:   None

Stack trace
   at System.Reflection.Metadata.Tests.MetadataReaderTests.GetAssemblyName() in /_/src/libraries/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs:line 3098
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

On `android-x64`, `tvossimulator-x64`:
```
Assert.Equal() Failure
Expected: MSIL
Actual:   Amd64
```

On `android-x86`:
```
Assert.Equal() Failure
Expected: MSIL
Actual:   X86
```

**Comment by jkotas** [comment]
cc @VSadov

**Comment by VSadov** [comment]
This could be a result of intentional simplification of the ProcessorArchitecture computation. I will take a look.

**Comment by VSadov** [comment]
Actually it looks like new test scenarios. Possibly a test issue.
