### ISSUE TITLE
Regression with JsonConverter attribute with Syste.Text.Json 7

### ISSUE THREAD

**Issue by MortenBoysen** [dotnet/runtime#80914]
### Description

When upgrading `System.Text.Json` from version 6.0.7 to 7.0.1 in an application targeting .NET 6 we experienced a `NotSupportedException` in code that worked fine before the upgrade. This particular code uses a custom `JsonConverter` to serialize a `Double[,]`array.

### Reproduction Steps

The following small project fails with a `NotSupportedException` when trying to serialize the DTO.

*.csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="7.0.1" />
  </ItemGroup>
</Project>
```

Program.cs:
```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using systemtextjson7regression;

var dto = new Dto() { Data = new double[,] { { 1, 243 }, { 1, 2 } } };
JsonSerializer.SerializeToUtf8Bytes(dto);

namespace systemtextjson7regression
{
    public class DoubleMatrixJsonConverter : JsonConverter<double[,]>
    {
        /// <inheritdoc />
        public override double[,] Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => throw new NotImplementedException();

        /// <inheritdoc />
        public override void Write(Utf8JsonWriter writer, double[,] value, JsonSerializerOptions options) { }
    }

    class Dto
    {
        [JsonConverter(typeof(DoubleMatrixJsonConverter))]
        public double[,] Data { get; set; }
    }
}
```

### Expected behavior

The programme terminates without throwing an exception:

```
Unhandled exception. System.NotSupportedException: The type 'System.Double[,]' is not supported.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type propertyType)
   at System.Text.Json.Serialization.Converters.IEnumerableConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetConverterForType(Type typeToConvert, JsonSerializerOptions options, Boolean resolveJsonConverterAttribute)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateJsonTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropertyCache()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes[TValue](TValue value, JsonSerializerOptions options)
   at Program.<Main>$(String[] args) in C:\Users\Morten Boysen\source\repos\systemtextjson7regression\systemtextjson7regression\Program.cs:line 6
```

### Actual behavior

A `NotSupportedException` is thrown.

### Regression?

Yes, this worked on .NET 6 with `System.Net.Json` version 6.0.7. An interesting observation is that this fails with both version 6.0.7 and 7.0.1 of `System.Text.Json` iff the target framework is .NET 7. That means the error matrix looks like this:

Target framwork .NET 6 and `System.Net.Json` version 6.0.7: Works
Target framwork .NET 7 and `System.Net.Json` version 7.0.1: Fails
Target framwork .NET 7 and `System.Net.Json` version 6.0.7: Fails
Target framwork .NET 7 and `System.Net.Json` version 7.0.1: Fails

### Known Workarounds

Explicitly adding the converter to the converter collection makes the code work on all target platform/`System.Text.Json` combinations:

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
using systemtextjson7regression;

var dto = new Dto() { Data = new double[,] { { 1, 243 }, { 1, 2 } } };
var options = new JsonSerializerOptions();
options.Converters.Add(new DoubleMatrixJsonConverter());
JsonSerializer.SerializeToUtf8Bytes(dto, options);

namespace systemtextjson7regression
{
    public class DoubleMatrixJsonConverter : JsonConverter<double[,]>
    {
        /// <inheritdoc />
        public override double[,] Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => throw new NotImplementedException();

        /// <inheritdoc />
        public override void Write(Utf8JsonWriter writer, double[,] value, JsonSerializerOptions options) { }
    }

    class Dto
    {
        //[JsonConverter(typeof(DoubleMatrixJsonConverter))]
        public double[,] Data { get; set; }
    }
}
```

However, this does not work in our scenario, as the assembly defining the DTO and custom converter is not referenced by the assembly creating the serializer and doing the serialization, so we cannot register the converter (the two assemblies are both being referenced by a third assembly, creating the application).

### Configuration

This fails on Windows 10 and 11.

**Comment by eiriktsarpalis** [comment]
I can reproduce. The issue is caused by the fact that we're now eagerly resolving the default converter for the type:

https://github.com/dotnet/runtime/blob/a734aa467f1bbf4d5bf30fe217e1a36eb966ce08/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.cs#L84-L107

which in the case of multi-dimensional arrays is throwing an exception:

https://github.com/dotnet/runtime/blob/a734aa467f1bbf4d5bf30fe217e1a36eb966ce08/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactory.cs#L43-L53

We should change the built-in converter factory so that instead of throwing it returns an instance of `UnsupportedTypeConverter` like we already do with other unsupported types:

https://github.com/dotnet/runtime/blob/a734aa467f1bbf4d5bf30fe217e1a36eb966ce08/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/UnsupportedTypeConverter.cs#L6-L13

We should audit the remaining built-in converter factories for cases where we currently throw at construction time.

**Comment by MortenBoysen** [comment]
Just out of my curiosity, why does this fail on .NET 7, when the package reference for `System.Text.Json` is explicitly set to 6.0.7? Is the runtime somehow choosing a version 7 package of System.Text.Json anyway on .NET 7?

**Comment by eiriktsarpalis** [comment]
IIRC it is not possible to reference versions of STJ earlier than the one available in the shared framework.
