### ISSUE TITLE
Getting errors while running dotnet/performance (https://github.com/dotnet/performance) benchmark with mono

### ISSUE THREAD

**Issue by shivanirmishra** [dotnet/runtime#80922]
I have built the mono runtime of dotnet using: https://github.com/dotnet/runtime/blob/main/docs/workflow/building/mono/README.md
And then tried running the dotnet/performance benchmark using:
https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

The steps I followed to run the benchmarks are as below:
1) /path/to/dotnet/runtime$ ./build.sh mono+libs -os browser -c Release
2) /path/to/dotnet/runtime$ ./dotnet.sh build -p:TargetOS=Browser -p:TargetArchitecture=wasm -c Release src/mono/wasm/Wasm.Build.Tests /t:InstallWorkloadUsingArtifacts
3) /path/to/dotnet/performance$ python3 ./scripts/benchmarks_ci.py -f net8.0 --dotnet-path </path/to/dotnet/runtime/>artifacts/bin/dotnet-net8+latest --wasm --bdn-artifacts artifacts/BenchmarkDotNet.Artifacts
    --bdn-arguments="--anyCategories Libraries Runtime --category-exclusion-filter NoInterpreter NoWASM NoMono --logBuildOutput --wasmDataDir </path/to/dotnet/runtime>/src/mono/wasm --filter <filter>"

Steps 1 and 2 are succeeded and in the 3rd step I am getting errors as below:
```
[2023/01/20 13:39:31][INFO] // *** Execute ***
[2023/01/20 13:39:31][INFO] // Launch: 1 / 1
[2023/01/20 13:39:31][INFO] // Execute: v8 --expose_wasm test-main.js -- --run d0d63672-0bfd-4c53-9d21-eb56809797ec.dll --benchmarkName BenchmarksGame.BinaryTrees_2.RunBench --job "PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Toolchain=Wasm, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1" --benchmarkId 0  in /home/shivani/NET/performance/artifacts/bin/MicroBenchmarks/Release/net8.0/d0d63672-0bfd-4c53-9d21-eb56809797ec/bin/net8.0/browser-wasm/AppBundle
[2023/01/20 13:39:31][INFO] Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'v8' with working directory '/home/shivani/NET/performance/artifacts/bin/MicroBenchmarks/Release/net8.0/d0d63672-0bfd-4c53-9d21-eb56809797ec/bin/net8.0/browser-wasm/AppBundle'. No such file or directory
[2023/01/20 13:39:31][INFO]    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
[2023/01/20 13:39:31][INFO]    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Toolchains.MonoWasm.WasmExecutor.Execute(Process process, BenchmarkCase benchmarkCase, AsyncProcessOutputReader processOutputReader, ILogger logger, ConsoleExitHandler consoleExitHandler, Int32 launchIndex)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Toolchains.MonoWasm.WasmExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, IResolver resolver, Int32 launchIndex)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Toolchains.MonoWasm.WasmExecutor.Execute(ExecuteParameters executeParameters)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Int32 launchIndex)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, Int32 totalBenchmarkCount, StartedClock& runsChronometer, Int32& benchmarksToRunCount, TaskbarProgress taskbarProgress)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
[2023/01/20 13:39:31][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[2023/01/20 13:39:31][INFO]    at MicroBenchmarks.Program.Main(String[] args) in /home/shivani/NET/performance/src/benchmarks/micro/Program.cs:line 43
[2023/01/20 13:39:31][INFO] $ popd
[2023/01/20 13:39:31][ERROR] Process exited with status 134
[2023/01/20 13:39:31][INFO] Run failure registered
Traceback (most recent call last):
  File "./scripts/benchmarks_ci.py", line 330, in <module>
    __main(sys.argv[1:])
  File "./scripts/benchmarks_ci.py", line 293, in __main
    is_success = micro_benchmarks.run(
  File "/home/shivani/NET/performance/scripts/micro_benchmarks.py", line 363, in run
    status = BENCHMARKS_CSPROJ.run(
  File "/home/shivani/NET/performance/scripts/dotnet.py", line 500, in run
    return RunCommand(cmdline, success_exit_codes, verbose=verbose).run(
  File "/home/shivani/NET/performance/scripts/performance/common.py", line 252, in run
    raise CalledProcessError(
subprocess.CalledProcessError: Command '$ dotnet run --project /home/shivani/NET/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --anyCategories Libraries Runtime --category-exclusion-filter NoInterpreter NoWASM NoMono --logBuildOutput --wasmDataDir /home/shivani/NET/runtime/src/mono/wasm --filter *BinaryTrees_2* --artifacts artifacts/BenchmarkDotNet.Artifacts --packages /home/shivani/NET/performance/artifacts/packages --runtimes wasmnet80 --buildTimeout 1200' returned non-zero exit status 134.
```

**Comment by radical** [comment]
You need `v8` installed too.

**Comment by radical** [comment]
You can use https://github.com/GoogleChromeLabs/jsvu to install it.
