### ISSUE TITLE
ArgumentNullException does not report parameter name in message

### ISSUE THREAD

**Issue by marcominerva** [dotnet/runtime#81004]
### Description

I'm using `ArgumentNullException` to validate parameters. For example, I have this code:

    PrintMessage(null);

    static void PrintMessage(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        Console.WriteLine(text);
    }

However, running this code, I obtain the following exception:

    System.ArgumentNullException: 'Value cannot be null. Arg_ParamName_Name'

So, parameter name isn't inserted in the message. I have tried also with the following alternatives:

    ArgumentNullException.ThrowIfNull(text, nameof(text));
    
    ArgumentNullException.ThrowIfNullOrEmpty(text);
    ArgumentNullException.ThrowIfNullOrEmpty(text, nameof(text));
    
    if (text is null)
    {
        throw new ArgumentNullException(nameof(text));
    }

But they don't work either.

### Reproduction Steps

    PrintMessage(null);
    
    static void PrintMessage(string text)
    {
        // ArgumentNullException does not report parameter name in message
        ArgumentNullException.ThrowIfNull(text);
    
        // These don't work either.
    
        //ArgumentNullException.ThrowIfNull(text, nameof(text));
    
        //ArgumentNullException.ThrowIfNullOrEmpty(text);
        //ArgumentNullException.ThrowIfNullOrEmpty(text, nameof(text));
    
        //if (text is null)
        //{
        //    throw new ArgumentNullException(nameof(text));
        //}
    
        Console.WriteLine(text);
    }

### Expected behavior

The parameter name should be written in the exception message.

### Actual behavior

The parameter name is not written in the exception message. Instead, the placeholder `Arg_ParamName_Name` is always used.

### Regression?

This doesn't work neither in .NET 6.0.13 nor .NET 7.0.2

### Configuration

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by stephentoub** [comment]
Can you share a standalone repro project?

**Comment by marcominerva** [comment]
Sure, here it is: https://github.com/marcominerva/ArgumentNullExceptionIssue.

**Comment by stephentoub** [comment]
I can't repro what you're seeing:
```
D:\repos> git clone https://github.com/marcominerva/ArgumentNullExceptionIssue
Cloning into 'ArgumentNullExceptionIssue'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 2), reused 11 (delta 1), pack-reused 0
Receiving objects: 100% (15/15), 6.23 KiB | 6.23 MiB/s, done.
Resolving deltas: 100% (2/2), done.
D:\repos> cd .\ArgumentNullExceptionIssue\ArgumentNullExceptionIssue\
D:\repos\ArgumentNullExceptionIssue\ArgumentNullExceptionIssue [master ≡]> dotnet run -c Release
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'text')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Program.<<Main>$>g__PrintMessage|0_0(String text) in D:\repos\ArgumentNullExceptionIssue\ArgumentNullExceptionIssue\Program.cs:line 6
   at Program.<Main>$(String[] args) in D:\repos\ArgumentNullExceptionIssue\ArgumentNullExceptionIssue\Program.cs:line 1
D:\repos\ArgumentNullExceptionIssue\ArgumentNullExceptionIssue [master ≡]>
```

**Comment by marcominerva** [comment]
Yes, I see that running the application from the command line works correctly. The issue appears if I run the application in Visual Studio 2022 v17.4.4, in Debug or Release:

![image](https://user-images.githubusercontent.com/3522534/213939420-523c1e3d-9eef-41c5-8798-a78afc4dc231.png)

**Comment by stephentoub** [comment]
Thanks, though I'm unable to repro that either:
![image](https://user-images.githubusercontent.com/2642209/213939981-2c1b4427-8c45-40c4-a052-193e62d965f8.png)
I do have a newer VS (`Version 17.6.0 Preview 1.0 [33316.92.main]`), but I wouldn't expect that to matter.

Maybe it's some kind of culture issue, such that resources can't be found and the key name ends up being used?

**Comment by marcominerva** [comment]
I'm using Visual Studio in English on an Italian Windows 11 laptop. I have tried to step into .NET source code and I see these steps, perhaps they could help:

![image](https://user-images.githubusercontent.com/3522534/213940697-ff4b8abe-9ee0-4b42-8938-0a286d7b81e2.png)

![image](https://user-images.githubusercontent.com/3522534/213940671-d056ef4b-c2b5-47c3-9371-8d8a2112a67d.png)

![image](https://user-images.githubusercontent.com/3522534/213940730-02f32f4c-859b-48b9-8a1f-753d45930806.png)

**Comment by stephentoub** [comment]
So you're getting some resources but not others? When you step through the exception's Message property, where does it go awry?

**Comment by marcominerva** [comment]
I'm seeing something weird. Using some breakpoints, it seems that the exception is raised before setting the error message. I have recorded a video to show you the workflow. In particular, note that, after I get the exception, I press F11 to step into and continue exception.

https://user-images.githubusercontent.com/3522534/213997509-43c02c05-b6cc-4433-908d-5d430499053a.mp4

**Comment by stephentoub** [comment]
I'd guess it's just an artifact of the corelib code being optimized.

Can you instead step through:
```C#
var e = new ArgumentNullException("text");
string m = e.Message;
```
rather than relying on the debugger's invocation of Message?

**Comment by marcominerva** [comment]
Using this code, the `Message` property is correctly set:

![image](https://user-images.githubusercontent.com/3522534/214081023-7571f9ef-d2f7-4133-9a1d-ba4383e16c08.png)

When the `Message `property is called, this is the method that is invoked: https://github.com/dotnet/runtime/blob/a39435f8e709dfc8f876943092ac905f028f513f/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs#L77

That is the same that is called when using `ArgumentNullException.ThrowIfNull(text);`, but it this latter case, what it seems, giving my video, is that it is called "too late", when the Exception has already been thrown.

**Comment by stephentoub** [comment]
> it is called "too late", when the Exception has already been thrown.

Presumably it's the debugger accessing Message in your video, which is why it would invoked after the exception was already thrown.

That doesn't explain why evaluation in the debugger would yield an inability to find some of the relevant resources.

@noahfalk, @tarekgh, anything here ring a bell?

**Comment by tarekgh** [comment]
just a guess, in the debugger when trying to get the resources, the value of `s_usingResourceKeys` being `true` and that is why it returned the resource key name instead of the value. The comment on the code explains when this value be `true`.  Native code generator for VS debugger may set this `true` value. 

https://github.com/dotnet/runtime/blob/d92e70f05b8de72758f3a990844e53c76b44d713/src/libraries/Common/src/System/SR.cs#L12

**Comment by noahfalk** [comment]
I can explain some of the behavior you see, but other portions are just speculative.

> is that it is called "too late", when the Exception has already been thrown

Most likely the code for the Message getter is run twice (or more) in the original video repro despite the breakpoint only hitting once. When the debugger wants to evaluate expressions to show their value in the UI windows such as the Exception helper dialog or the Locals/Autos/Watch window it will ignore breakpoints while running the expressions. I assume the debugger did run Exception.Message at the time the exception helper window shows the text.
The one time you do see the breakpoint hit after exception has been thrown, that is the runtime evaluating the Message property so it can format text that goes on the console when an app crashes with unhandled exception. 

> So you're getting some resources but not others?

The different resources are evaluating at different times, and likely under different circumstances. The SR.ArgumentNull_Generic resource is evaluated during the exception constructor via normal runtime code execution. The value was stored in the _message field so that it won't ever need to be resolved again. The SR.Arg_ParamName_Name is evaluated every time the Message property is run and it is probably being executed in response to a debugger function-evaluation request pre-emptively pushed onto the stack. There are some fallback paths in the resource resolution code that return the original key if there is unexpected re-entrancy which might happen if there is an unexpected re-entrant exception. Another speculative option is that the debugger had to fallback to using IL interpretation for some reason and the IL interpreter needed to replace resource lookup with a simplified implementation.

**Comment by marlon-tucker** [comment]
IF it makes any difference, I've also encountered this issue using NET6 and Visual Studio 2022 version 17.5.3.

It's not the end of the world as you can find the parameter name by expanding the exception details dialog, however, it does add a layer of friction to the developer experience.

**Comment by Metritutus** [comment]
I have also seen this behaviour.  I believe it may be a Visual Studio issue, and specific to unhandled exceptions.

If the exception is thrown with a normal `throw` and is unhandled, it only seems to show incorrectly when viewing the unhandled exception in Visual Studio's "Exception Unhandled" window.  In other areas it appears correctly:
![image](https://github.com/dotnet/runtime/assets/324345/381a4a07-4107-48ab-a9bb-139e647d7ca3)

If the exception is re-thrown using `ExceptionDispatchInfo` however, then it shows incorrectly in multiple areas, but again, only if unhandled:
![image](https://github.com/dotnet/runtime/assets/324345/16f19bf6-84d2-4fa5-a156-d004b5ee4106)

This behaviour appears to affect both `ArgumentNullException` and `ArgumentException`, but might affect others?

Another clue that this appears to be something specific to Visual Studio, is that if you run the application without debugging, the correct exception message will show in the console window when the app crashes:

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'args')
```

I hope this information is of use.

**Comment by nohopestage** [comment]
There's also a problem with `ArgumentNulllException.ThrowIfNull`. The `ParamName` property is null if the `paramName` argument is not specified, although, as stated in the in the docs, it's supposed to be omitted.

**Comment by stephentoub** [comment]
> There's also a problem with `ArgumentNulllException.ThrowIfNull`. The `ParamName` property is null if the `paramName` argument is not specified, although, as stated in the docs, it's supposed to be omitted. I'm using .NET 6.0.110.

That should not be the case. Are you calling it with the parameter name not specified or are you passing null? There's a difference. Can you share a repro?

**Comment by nohopestage** [comment]
> > There's also a problem with `ArgumentNulllException.ThrowIfNull`. The `ParamName` property is null if the `paramName` argument is not specified, although, as stated in the docs, it's supposed to be omitted. I'm using .NET 6.0.110.
> 
> That should not be the case. Are you calling it with the parameter name not specified or are you passing null? There's a difference. Can you share a repro?

I'm calling it with the parameter name not specified. The repro posted by the OP can be used to reproduce the behavior.

**Comment by stephentoub** [comment]
For me that outputs
```
text
```
as expected.

**Comment by nohopestage** [comment]
> How are you building / running this?
Building and running from VS.

**Comment by SchreinerK** [comment]
any progress??
this issue occurs also on other exceptions, where parameter name ist specified.
Windows 11 german, Visual Studio 2022 (Version 17.11.0) (english language pack),  TargetFramework: net8.0-windows

```csharp
throw new ArgumentException("Test", "argument");
```

![image](https://github.com/user-attachments/assets/a97af925-2a5c-4b17-a995-7da2190788e0)

same App but with TargetFramework: net481
![image](https://github.com/user-attachments/assets/89d98d3b-4cf1-4795-b457-1f130cf96e5f)

**Comment by PranavSenthilnathan** [comment]
Here is a repro (add the following in a new console app):
```cs
Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("es");

throw new ArgumentNullException("foo");
```

Running in VS gives:
![Image](https://github.com/user-attachments/assets/236f2dcc-3c51-4fd4-82ea-5f2f9a4dd56a)

This might not be the exact issue reported in this thread but it's close enough that the root cause is most likely the same. I've found the location in the VS debugger that's causing it, so I've updated [this ticket](https://developercommunity.visualstudio.com/t/Caught-exception-popup-does-use-weird-pl/10369930) with this repro and some internal details. You can use that ticket to monitor this issue going forward.
