### ISSUE TITLE
TaskCancelledException in HttpConnectionPool

### ISSUE THREAD

**Issue by sksk571** [dotnet/runtime#81023]
### Description

We have a small web application that started sporadically throwing TaskCancelledException's after migration from .NET5 to .NET6 and later .NET7. The application consists of just one controller method that retrieves image from Amazon S3, resizes it and saves a resized copy back to S3. The application works fine under .NET5, but under .NET6 and .NET7 it sporadically throws thousands of TaskCancelledException errors from method HttpConnectionPool+HttpConnectionWaiter`1+<WaitForConnectionAsync>

### Configuration

- Version: .NET6+
- OS version: Alpine Linux 3.16
- Architecture: x64

### Regression?

This is a regression in .NET6+ compared to .NET5.

### Data

Dump files captured during one of the incidents contain thousands of async calls looking like
```
.00007f0f9ec03878 (0) System.Net.Http.HttpConnectionPool+HttpConnectionWaiter`1+<WaitForConnectionAsync>d__5[[System.__Canon, System.Private.CoreLib]]
..00007f0f9ec03918 (4) System.Net.Http.HttpConnectionPool+<SendWithVersionDetectionAndRetryAsync>d__84
...00007f0f9ec03a38 (0) System.Net.Http.DiagnosticsHandler+<SendAsyncCore>d__10
....00007f0f9ec03b00 (0) System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d
.....00007f0f9ec03bc0 (0) Amazon.Runtime.HttpWebRequestMessage+<GetResponseAsync>d__20
```
and
```
.00007f0f9ec1c840 (1) System.Net.Http.HttpConnectionPool+<ConnectToTcpHostAsync>d__99
..00007f0f9ec1c910 (0) System.Net.Http.HttpConnectionPool+<ConnectAsync>d__98
...00007f0f9ec1c9d8 (0) System.Net.Http.HttpConnectionPool+<CreateHttp11ConnectionAsync>d__100
....00007f0f9ec1ca98 (0) System.Net.Http.HttpConnectionPool+<AddHttp11ConnectionAsync>d__74
```

The events from a trace captured using System.Net.Http provider:
[dotnet_20230119_154543_2847c867.9.excel.xlsx](https://github.com/dotnet/runtime/files/10480348/dotnet_20230119_154543_2847c867.9.excel.xlsx)

### Analysis

Tracing some of the failed requests to connections using ActivityID shows that the corresponding connection was established and closed, but not used for some reason. 
This [issue](https://github.com/dotnet/runtime/issues/66297) may be related.

**Comment by MihaZupan** [comment]
> after migration from .NET5 to .NET6 and later .NET7

We're aware of this issue on .NET 6, and it can be mitigated by setting the `ConnectTimeout` (it's infinite by default).
```c#
new SocketsHttpHandler
{
    ConnectTimeout = TimeSpan.FromSeconds(5)
}
```

> and later .NET7

Are you seeing similar behavior on .NET 7?
7.0 has a mitigation in place that should prevent this issue from affecting many requests - #71785.

> The events from a trace captured using System.Net.Http provider

If this situation happens again, could you also collect the following events?
```
System.Net.Sockets
System.Net.Security
Private.InternalDiagnostics.System.Net.Http
```
That would give us more information about what the connection pool was doing at the time.

**Comment by antonfirsov** [comment]
Seeing this happening on .NET 7.0 is very weird, I wouldn't be surprised if this is a different issue, especially if it's true that:

> Tracing some of the failed requests to connections using ActivityID shows that the corresponding connection was established and closed, but not used for some reason. 

@sksk571 do you see the same scale of `TaskCancelledException`-s and closed connections on .NET 7.0 as on .NET 6.0?

I would really like to see the additional traces collected on .NET 7.0, if setting `ConnectTimeout` (on .NET 6.0!) doesn't help.

**Comment by MihaZupan** [comment]
Can you send it to `Miha.Zupan` and `Anton.Firszov` @microsoft.com?

**Comment by antonfirsov** [comment]
After exchanging information with @sksk571 it looks like there are sporadic stalled `getaddrinfo` calls on their server. As a result of #49171, a single stalled call will hang any follow-up DNS resolution request which go to the same host. This leads to a massive accumulation pending connection attempts in `HttpConnectionPool`. These will only complete when the first stalled DNS resolution attempt completes. By this time the originating requests are timed out and end up throwing.

We can consider mitigating this by:
- Implementing a semaphore logic instead of the strict serialization of all DNS requests.
- Removing cancelled resolution attempts from [`Dns.s_tasks`](https://github.com/dotnet/runtime/blob/95723eb36afac72806727ff38961fadad71ed057/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs#L648). In the log I received there is an enormous amount of cancellations due to `PendingConnectionTimeoutOnRequestCompletion` (#71785), which currently don't affect the Dns queuing mechanism at all.

Whether we are open to implement such mitigations depends whether such DNS misbehavior is common. It would be good to understand what's causing this on your infra @sksk571.

**Comment by MihaZupan** [comment]
Looks like a +1 on #19443

**Comment by antonfirsov** [comment]
Triage: only one customer report so far, the root cause is environmental. Putting to "Future" for now, if we get more customers hitting this we can bump the priority.

**Comment by matt-augustine** [comment]
We are experiencing similar behavior in a high-traffic ASP.NET Core application on .NET 7.0.101. The application runs on Kubernetes, and the issue typically occurs when new pods are created and begin processing a high volume of requests. The application makes numerous outbound HTTP requests to various cloud services while processing each inbound request. 

The symptoms include:
- `http11-requests-queue-duration` event counter values reaching 40 seconds or more.
- `current-dns-lookups` values of up to 2,000.
- `dns-lookups-duration` values of 40 seconds or more.
- `current-outgoing-connect-attempts` values of 100 or more.
- `threadpool-queue-length` values of 100 or more.
- Many logged exceptions similar to the one in the original report:
```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.TimeoutException: A connection could not be established within the configured ConnectTimeout.
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(OperationCanceledException oce)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetException(Exception exception)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.TrySetCanceled(CancellationToken tokenToRecord, Object cancellationException)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.SocketAsyncEventArgs.<DnsConnectAsync>g__Core|112_0(MultiConnectSocketAsyncEventArgs internalArgs, Task`1 addressesTask, Int32 port, SocketType socketType, ProtocolType protocolType, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

**Comment by antonfirsov** [comment]
@matt-augustine I'm experimenting with a fix now. Would be great if you could validate it for your case, will reach out on Teams.

**Comment by karelz** [comment]
Moving to 9.0 as it hit 3 customers. They found workarounds, but it would be nice to avoid the problem for others in future.

**Comment by DejanPelzel** [comment]
I believe we were severely affected by this issue, which resulted in massive stability issues. We were able to work around by using a custom DNS resolver and SocketsHttpHandler with ConnectCallback, but it seems this is wider spread than 3 customers and can cause massive damage for things like edge services that communicate via HTTP.

**Comment by neon-sunset** [comment]
@MihaZupan apologies for the ping. I wanted to inquire if moving this to the Future milestone (also, sometimes, unfortunately, known as Never) could be reconsidered. It is not ideal if the customers are finding out about this issue the hard way. Thanks for your help!

**Comment by MihaZupan** [comment]
In this case it was more of a "definitely not in 9.0" (in June) than "never".

We have been actively looking into the possibility of having a managed DNS implementation (https://github.com/dotnet/aspire/pull/6104), though AFAIK it's debatable if/when that would become the default for components like HttpClient. At the very least it would make working around this issue easier. cc: @rzikm

**Comment by ogxd** [comment]
We also are quite impacted by this issue as we use DNS resolution for service discovery for a large backend infrastructure (handling hundreds of billions of requests per day). We forcibly had to switch to using https://github.com/MichaCo/DnsClient.NET as a workaround as SLAs were compromised. In case the rootcause is unclear, we took a memory dump if that can help investigating, let me know if you need thread stack information.

**Comment by MihaZupan** [comment]
For context, there's more info about how we got here in #48566. In short:
- The glibc APIs we use on Linux aren't async.
- They don't fully support cancellation.

Having a reliable repro where DNS queries get "stuck" forever may be useful for future testing. But I'm not sure we can do much here other than swapping out the underlying impl, e.g. #19443.

**Comment by ogxd** [comment]
At work we're being severy impacted by this. 

Here is the count of thread pool thread per pod (it's a backend service, load is constant, so it's supposed to be stable, usually between 20 and 30 threads):
![Image](https://github.com/user-attachments/assets/f4e96915-dba0-4d4a-b2c9-156e6dc572f1)

We can see that the thread pool may suddenly create many more threads, which is a sign that some threads are in a blocked state. So we did a pstack using [dr-dotnet](https://github.com/dr-dotnet/dr-dotnet) :

![Image](https://github.com/user-attachments/assets/55ec63f0-fd74-4955-b7ae-0a35600324a4)

You can see that theses threads are blocks on the Dns resolution syscall.

We tried using an alternate client for DNS resolution, however it cannot replace every usage (eg the Microsoft.SqlClient uses System.Net.Dns). At this point, we're even considering using [Harmony](https://github.com/pardeike/Harmony) to patch the Dns method and dynamically replace it's implementation at runtime 🙄

**Comment by karelz** [comment]
@ogxd it would be useful for our prioritization to have a call - learn more about your service, find out the limitations and see what kind of experiments and solutions would be sufficient for you.
For example, custom DNS (#19443) is something we are seriously looking for .NET - although it may be more .NET 11 timeframe.

**Comment by ogxd** [comment]
@karelz  Sure we can do that 👍. If you have some time between 2pm and 6pm CET (we're in Paris) on any week day please let me know (feel free to reach out or directly send an invite at [oginiaux@gmail.com](oginiaux@gmail.com)). I'll compile some more relevant bits of information and context.

**Comment by hacst** [comment]
The title here is somewhat understating the issue. Just having a sufficiently high number of new connections to a single host (e.g. an api during a load spike) and a non-zero DNS resolution time will lead to a pile up of DNS requests as all queries for a specific host get [serialized](https://github.com/dotnet/runtime/blob/ef853a71052646a42abf17e888ec6d9a69614ad9/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs#L645). If you have a query latency of 5ms and no OS cache, which is pretty normal for Linux in Kubernetes due to the way it handles DNS, you cannot open more than 200 connections per second to a host before you start falling behind. Even if you stay below that rate on average, trying to open 20 connections at the same time means one is going to wait 100ms for DNS resolution instead of 5ms. This is bound to wreck some .NET services p99 without them realizing thats whats going on.

The [current implementations stated assumption](https://github.com/dotnet/runtime/blob/ef853a71052646a42abf17e888ec6d9a69614ad9/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs#L645) of having a local DNS cache available that will respond instantly after the first query does not hold in the diverse environments dotnet now deploys to. Imo this shifts the tradeoff to where it makes sense to revisit the implementation so it can make better use of the available resources in the system. Thread pool exhaustion is of course still a serious concern, but it should be possible to mititgate this by having overall limits on in-progress resolutions as suggested in the implementations comment. Right now there would be no such limit if different domains are resolved so it would even improve robustness slightly.

Of course ideally this would all become non-blocking to begin with. But as stated before in this thread libc does not offer this on many systems (e.g musl used in alpine does not even have the getaddrinfo_a variant) and introducing a dotnet native resolver to replace the corresponding libc one completely seems like a heavy lift even for the .NET 11 timeframe. I assume this is also why this issue has been pending for so long. 

It would be great to have some progress on this even with a less than optimal solution as I can definitely corroborate that this issue takes quite a while to track down from its symptoms and was very unexpected. In our case it caused failure of an api gateway instance based on [yarp](https://github.com/dotnet/yarp).
