### ISSUE TITLE
Test failure Interop\\PInvoke\\SetLastError\\SetLastErrorTest\\SetLastErrorTest.cmd

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#81121]
Failed in run: [runtime-coreclr outerloop 20230119.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=142535&view=ms.vss-test-web.build-test-results-tab&runId=3091200&resultId=115593&paneView=debug)

Failed tests:
```
R2R-CG2 windows arm64 Checked @ Windows.11.Arm64.Open
  - Interop\\PInvoke\\SetLastError\\SetLastErrorTest\\SetLastErrorTest.cmd
```

Error message:
```
Unhandled exception. System.ArgumentNullException: Invalid handle.
at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
at System.RuntimeType.GetMethodBase(RuntimeType reflectedType, RuntimeMethodHandleInternal methodHandle)
at System.RuntimeType.GetMethodBase(RuntimeType reflectedType, IRuntimeMethodInfo methodHandle)
at System.Diagnostics.StackFrameHelper.GetMethodBase(Int32 i)
at System.Diagnostics.StackFrame..ctor(StackFrameHelper stackFrameHelper, Int32 skipFrames, Boolean needFileInfo)
at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 skipFrames, Boolean fNeedFileInfo, Exception e)
at System.Exception.get_StackTrace()
at System.Exception.ToString()
at Internal.JitInterface.CorInfoImpl.AllocException(Exception ex) in //src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 164
at Internal.JitInterface.CorInfoImpl.resolveToken(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken) in //src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 449
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr& exception, IntPtr jit, IntPtr thisHandle, IntPtr callbacks, CORINFO_METHOD_INFO& info, UInt32 flags, IntPtr& nativeEntry, UInt32& codeSize)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in //src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 355
at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 659
at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 841
at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 775
at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in //src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 753

Return code:      1
Raw output file:      C:\h\w\A5B60925\w\BBC409CF\uploads\Reports\Interop.PInvoke\SetLastError\SetLastErrorTest\SetLastErrorTest.output.txt
Raw output:
BEGIN EXECUTION
SetLastErrorNative.dll
SetLastErrorTest.dll
TestLibrary.dll
3 file(s) copied.
20:33:43.82
Response file: C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\SetLastErrorNative.dll.rsp
C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\IL-CG2\SetLastErrorNative.dll
-o:C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\SetLastErrorNative.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A5B60925\p\System..dll
-r:C:\h\w\A5B60925\p\Microsoft..dll
-r:C:\h\w\A5B60925\p\mscorlib.dll
-r:C:\h\w\A5B60925\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A5B60925\p\crossgen2\crossgen2.dll" @"C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\SetLastErrorNative.dll.rsp"   -r:C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\IL-CG2*.dll"
No input files are loadable
20:33:44.09
20:33:44.10
Response file: C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\SetLastErrorTest.dll.rsp
C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastErrorTest\IL-CG2\SetLastErrorTest.dll
-o:C:\h\w\A5B60925\w\BBC409CF\e\Interop\PInvoke\SetLastError\SetLastE
```

Stack trace:
```
   at Interop_PInvoke._SetLastError_SetLastErrorTest_SetLastErrorTest_._SetLastError_SetLastErrorTest_SetLastErrorTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
Seems duplicate with https://github.com/dotnet/runtime/issues/81120. Closing.
