### ISSUE TITLE
[wasm] `DebuggerTests.ExceptionTests` timing out on CI/linux

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#81170]
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1929e528323c4cc6ab/chrome-DebuggerTests.ExceptionTests/1/console.57e82c03.log?helixlogtype=result

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Killed
['chrome-DebuggerTests.ExceptionTests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81166-merge-94b9d3b08db54e2694/chrome-DebuggerTests.ExceptionTests/1/console.1f001ef8.log?helixlogtype=result):

```
[18:17:46] dbug: DevToolsProxy-0[0] DevToolsProxy: Starting for browser at ws://127.0.0.1:44541/devtools/page/C034D7D3123FB2706F7026F07BF800EF
[18:17:46] dbug: DevToolsProxy-0[0] DevToolsProxy: Proxy waiting for connection to the browser at ws://127.0.0.1:44541/devtools/page/C034D7D3123FB2706F7026F07BF800EF
[18:17:46] info: Inspector-0[0] waiting for the runtime to be ready
[18:17:46] dbug: DevToolsProxy-0[0] Default context created, clearing state and sending events
[18:18:07] dbug: Inspector-0[0] console.debug: #debugger-app-ready#
[18:18:07] info: Inspector-0[0] runtime ready, TEST TIME
[18:18:07] info: Inspector-0[0] console: <message missing>
[18:18:07] info: Inspector-0[0] console.log: uncaught test
[18:18:07] dbug: Inspector-0[0] Failing all waiters because: Runtime.exceptionThrown: {   "timestamp": 1674670687902.601,   "exceptionDetails": {     "exceptionId": 1,     "text": "Uncaught",     "lineNumber": 46,     "columnNumber": 7,     "scriptId": "5",     "url": "http://localhost:9400/other.js",     "stackTrace": {       "callFrames": [         {           "functionName": "exception_uncaught_test",           "scriptId": "5",           "url": "http://localhost:9400/other.js",           "lineNumber": 46,           "columnNumber": 7         },         {           "functionName": "exceptions_test",           "scriptId": "5",           "url": "http://localhost:9400/other.js",           "lineNumber": 51,           "columnNumber": 1         },         {           "functionName": "",           "scriptId": "86",           "url": "",           "lineNumber": 0,           "columnNumber": 32         }       ]     },     "exception": {       "type": "object",       "subtype": "error",       "className": "RangeError",       "description": "RangeError: exception uncaught\n    at exception_uncaught_test (http://localhost:9400/other.js:47:8)\n    at exceptions_test (http://localhost:9400/other.js:52:2)\n    at <anonymous>:1:33",       "objectId": "-3584951409223131675.1.12",       "preview": {         "type": "object",         "subtype": "error",         "description": "RangeError: exception uncaught\n    at exception_uncaught_test (http://localhost:9400/other.js:47:8)\n    at exceptions_test (http://localhost:9400/other.js:52:2)\n    at <anonymous>:1:33",         "overflow": false,         "properties": [           {             "name": "stack",             "type": "string",             "value": "RangeError: exception uncaught\n    at exception_un…lhost:9400/other.js:52:2)\n    at <anonymous>:1:33"           },           {             "name": "message",             "type": "string",             "value": "exception uncaught"           }         ]       }     },     "executionContextId": 1   } }
[18:18:44] dbug: Inspector-0[0] RunLoop stopped, reason: RunLoopExitState { reason = Cancelled, exception =  }
[18:18:44] dbug: Inspector-0[0] Failing 0 pending cmds
[18:18:44] dbug: DevToolsProxy-0[0] RunLoop stopped, reason: RunLoopExitState { reason = ConnectionClosed, exception = System.Exception: Connection id: ide  ---> System.AggregateException: One or more errors occurred. (The remote party closed the WebSocket connection without completing the close handshake.)  ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.    at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)    at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) --- End of stack trace from previous location ---    at Microsoft.WebAssembly.Diagnostics.DevToolsDebuggerConnection.ReadOneAsync(CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Common/DevToolsDebuggerConnection.cs:line 43    --- End of inner exception stack trace ---    --- End of inner exception stack trace --- }
[18:18:44] dbug: DebuggerTests.TestHarnessProxy[0] [testId: 0] TestHarnessStartup done
[18:18:44] dbug: DebuggerTests.TestHarnessProxy[0] TestHarnessStartup: closing for 0
['chrome-DebuggerTests.ExceptionTests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by lewing** [comment]
@radical have we seen this recently?

**Comment by radical** [comment]
> @radical have we seen this recently?

It's disabled currently. We should re-enable and see if it is still failing.
