### ISSUE TITLE
Test failure tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#81241]
Failed again: [runtime-coreclr outerloop 20230124.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=146350&view=results) and many ohter outerloop runs

Failed tests:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
coreclr windows arm Checked @ Windows.11.Arm64.Open
R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open
  -  tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd
```
Error message:
```
Assert failure(PID 9480 [0x00002508], Thread: 9544 [0x2548]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

<no module>! <no symbol> + 0x0 (0x00000000)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: C:\h\w\995208D3\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\995208D3\w\9DC108DD\uploads\Reports\tracing.eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.output.txt
Raw output:
BEGIN EXECUTION
common.dll
eventsourceerror.dll
Microsoft.Diagnostics.NETCore.Client.dll
3 file(s) copied.
11:37:02.23
Response file: C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll.rsp
C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2\common.dll
-o:C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\995208D3\p\System..dll
-r:C:\h\w\995208D3\p\Microsoft..dll
-r:C:\h\w\995208D3\p\mscorlib.dll
-r:C:\h\w\995208D3\p\netstandard.dll
-O
" "dotnet" "C:\h\w\995208D3\p\crossgen2\crossgen2.dll" @"C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll.rsp"   -r:C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll
" "dotnet" "C:\h\w\995208D3\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll --out C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\common.dll.r2rdump --val"
11:37:04.69
11:37:04.69
Response file: C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll.rsp
C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2\eventsourceerror.dll
-o:C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\995208D3\p\System..dll
-r:C:\h\w\995208D3\p\Microsoft..dll
-r:C:\h\w\995208D3\p\mscorlib.dll
-r:C:\h\w\995208D3\p\netstandard.dll
-O
" "dotnet" "C:\h\w\995208D3\p\crossgen2\crossgen2.dll" @"C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll.rsp"   -r:C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll
" "dotnet" "C:\h\w\995208D3\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll --out C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\eventsourceerror.dll.r2rdump --val"
11:37:06.80
11:37:06.80
Response file: C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\Microsoft.Diagnostics.NETCore.Client.dll.rsp
C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\IL-CG2\Microsoft.Diagnostics.NETCore.Client.dll
-o:C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\Microsoft.Diagnostics.NETCore.Client.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\995208D3\p\System..dll
-r:C:\h\w\995208D3\p\Microsoft..dll
-r:C:\h\w\995208D3\p\mscorlib.dll
-r:C:\h\w\995208D3\p\netstandard.dll
-O
" "dotnet" "C:\h\w\995208D3\p\crossgen2\crossgen2.dll" @"C:\h\w\995208D3\w\9DC108DD\e\tracing\eventpipe\eventsourceerror\eventsourceerror\Microsoft.Diagnostics.NETCore.Client.dll.rsp"   -r:C:\h\w\995208D3\w\9DC108DD\e\tracing
```
Stack trace:
```
   at tracing_eventpipe._eventsourceerror_eventsourceerror_eventsourceerror_._eventsourceerror_eventsourceerror_eventsourceerror_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
It is failing in all the outerloop runs. From 2 other runs, it seems that it is happening on arm tests. 

```
tracing\\eventpipe\\eventsourceerror\\eventsourceerror\\eventsourceerror.cmd
    Assert failure(PID 9480 [0x00002508], Thread: 9544 [0x2548]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")
```

[Run 20230123.3 ](https://dev.azure.com/dnceng-public/public/_build/results?buildId=146066):
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open
coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
coreclr windows arm Checked @ Windows.11.Arm64.Open
coreclr linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open) 
coreclr linux arm Checked @ (Alpine.314.Arm32.Open) 
```

[Run 20230123.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=145481) 
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open
coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
coreclr windows arm Checked @ Windows.11.Arm64.Open
coreclr linux arm Checked @ (Ubuntu.1804.Arm32.Open) 
```

**Comment by trylek** [comment]
As the offending test has been disabled, I believe this is no longer blocking outerloop.

**Comment by hoyosjs** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/80666
