### ISSUE TITLE
DebuggerTests.MiscTests.CannotDebugLazyLoadedAssemblyWithoutPdb test timed out on CI

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#81294]
DebuggerTests.MiscTests.CannotDebugLazyLoadedAssemblyWithoutPdb test timed out on CI leg: [Mono_DebuggerTests_chrome](https://github.com/dotnet/runtime/pull/78544/checks?check_run_id=10921697814)
From [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78544-merge-66ea35de39b64d6b9b/chrome-DebuggerTests.MiscTests/1/console.f89c5e43.log?helixlogtype=result):
```log
[xUnit.net 00:10:38.57]     DebuggerTests.MiscTests.CannotDebugLazyLoadedAssemblyWithoutPdb [FAIL]
  Failed DebuggerTests.MiscTests.CannotDebugLazyLoadedAssemblyWithoutPdb [1 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 60.0033297)
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, TimeSpan span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 346
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 160
  Standard Output Messages:
 | [2023-01-27T05:53:06] DebuggerTests.TestHarnessProxy Information: [testId: 61] New test request for test id 61
 | [2023-01-27T05:53:06] DebuggerTests.TestHarnessProxy Debug: [61] Starting C:\helix\work\correlation\chrome-win\chrome.exe with --headless --disable-gpu --lang=en-US --incognito --remote-debugging-port=0 http://localhost:9400/debugger-driver.html
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.169:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: The pipe has been ended. (0x6D)
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.227:ERROR:network_change_notifier_win.cc(224)] WSALookupServiceBegin failed with: 0
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr 
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr DevTools listening on ws://127.0.0.1:50592/devtools/browser/192f6027-c8b4-47ec-ab2b-af7e02d99360
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.327:ERROR:dxva_video_decode_accelerator_win.cc(1451)] DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found. (0x7E)
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.333:ERROR:dxva_video_decode_accelerator_win.cc(1451)] DXVAVDA fatal error: could not LoadLibrary: mfplat.dll: The specified module could not be found. (0x7E)
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.335:ERROR:dxva_video_decode_accelerator_win.cc(1451)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: The specified module could not be found. (0x7E)
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.338:ERROR:dxva_video_decode_accelerator_win.cc(1455)] DXVAVDA fatal error: could not LoadLibrary: dxva2.dll: The specified module could not be found. (0x7E)
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 61] browser-stderr [0127/055308.340:ERROR:dxva_video_decode_accelerator_win.cc(1459)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: The specified module could not be found. (0x7E)
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Information: [testId: 61] launching proxy for ws://127.0.0.1:50592/devtools/page/AA2EDAE00C76D6C0A6C0D194DCC6E2DE
 | [2023-01-27T05:53:08] Inspector-61 Information: waiting for the runtime to be ready
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: [testId: 60] TestHarnessStartup done
 | [2023-01-27T05:53:08] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 60


[xUnit.net 00:11:13.71]     DebuggerTests.MiscTests.SetBreakpointInProjectWithColonInSourceName [SKIP]
  Skipped DebuggerTests.MiscTests.SetBreakpointInProjectWithColonInSourceName [1 ms]
Results File: C:\helix\work\workitem\uploads\xharness-output\logs\testResults.trx

Failed!  - Failed:     1, Passed:    65, Skipped:     1, Total:    67, Duration: 11 m 1 s - DebuggerTestSuite.dll (net8.0)
```

**Comment by thaystg** [comment]
Not happening recently.
