### ISSUE TITLE
Test failure tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#81323]
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20230128.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=151649)
 
 **Failed tests:**
 ```
 coreclr linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh
 ```
 
 **Error message:**
 ```
 Test Infrastructure Failure: System.UnauthorizedAccessException: Access to the path '/home/helixbot/dotnetbuild/dumps/crashdump_6843.dmp.crashreport.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, StreamWriter outputWriter)
   at CoreclrTestLib.CoreclrTestWrapperLib.CollectCrashDump(Process process, String crashDumpPath, StreamWriter outputWriter)
   at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir)
   at tracing_eventpipe._rundownvalidation_rundownvalidation_rundownvalidation_._rundownvalidation_rundownvalidation_rundownvalidation_sh()
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at tracing_eventpipe._rundownvalidation_rundownvalidation_rundownvalidation_._rundownvalidation_rundownvalidation_rundownvalidation_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by hoyosjs** [comment]
@kunalspathak this is related to the stack symbolication logic.

**Comment by kunalspathak** [comment]
From the console logs, it seems just before `ReadAllText()` we checked and see that we have permissions to read the file.

```
createdump stdout:
[createdump] Gathering state for process 6843 corerun
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/crashdump_6843.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/crashdump_6843.dmp
[createdump] Written 174620672 bytes (42632 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 2246ms

createdump stderr:

Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/crashdump_6843.dmp.crashreport.json
stdout: -rw------- 1 root root 87964 Jan 28 16:53 /home/helixbot/dotnetbuild/dumps/crashdump_6843.dmp.crashreport.json
``` 

The fix is easy, but I am wondering what could be wrong and why we would get this error? This will help to make it more robust. @hoyosjs - do you know?

**Comment by tommcdon** [comment]
@davmason would you mind taking a look at the product failure?

**Comment by tommcdon** [comment]
There is a known gc hold in eventsource.  Note sure if this test is using managed event sources, though sharing in case it is related- #81241

**Comment by BruceForstall** [comment]
Another case:

tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh

coreclr linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

https://dev.azure.com/dnceng-public/public/_build/results?buildId=168907&view=ms.vss-test-web.build-test-results-tab&runId=3404395&resultId=111325&paneView=debug


```
  Starting:    tracing.eventpipe.XUnitWrapper (parallel test collections = on, max threads = 2)
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:02:03
[Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:02:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:04:03
[Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:04:24
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:07:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:09:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:11:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:13:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:15:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:17:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:19:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:21:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:23:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:25:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:27:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:29:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:31:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:33:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:35:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:37:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:39:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:41:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:43:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:45:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:47:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:49:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:51:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:53:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:55:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:57:03
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh', Elapsed: 00:59:03
Attempting to collect crash dump: /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp
Invoking: sudo /root/helix/work/correlation/createdump --crashreport --name "/home/helixbot/dotnetbuild/dumps/crashdump_496.dmp" 496 --withheap
createdump stdout:
[createdump] Gathering state for process 496 corerun
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp
[createdump] Written 193712128 bytes (47293 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 300ms

createdump stderr:

Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json
stdout: -rw------- 1 root root 83181 Feb 12 16:39 /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json

=========================================
Error reading /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json: System.UnauthorizedAccessException: Access to the path '/home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, StreamWriter outputWriter)
Collected crash dump: /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp
    tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh [FAIL]
      
      cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/12/2023 3:39:43 PM, end: 2/12/2023 4:39:43 PM)
      
      Return code:      -100
      Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false rundownvalidation.dll ''
        0.0s: ==TEST STARTING==
       17.0s: Started sending sentinel events...
       17.0s: Connecting to EventPipe...
       36.4s: Creating EventPipeEventSource...
       36.7s: EventPipeEventSource created
       37.4s: Dynamic.All callback registered
       37.4s: Running optional trace validator
       37.6s: Finished running optional trace validator
       37.6s: Starting stream processing...
       41.9s: Saw new provider 'Microsoft-DotNETCore-SampleProfiler'
       65.9s: Saw sentinel event
       65.9s: Stopped sending sentinel events
       66.3s: Starting event generating action...
       66.3s: Stopping event generating action
       66.4s: Sending StopTracing command...
      688.8s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
      707.7s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
      928.8s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
      
      cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/12/2023 3:39:43 PM, end: 2/12/2023 4:39:43 PM)
      Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json'
      Test Harness Exitcode is : -100
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at tracing_eventpipe._rundownvalidation_rundownvalidation_rundownvalidation_._rundownvalidation_rundownvalidation_rundownvalidation_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/12/2023 3:39:43 PM, end: 2/12/2023 4:39:43 PM)
        
        Return code:      -100
        Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false rundownvalidation.dll ''
          0.0s: ==TEST STARTING==
         17.0s: Started sending sentinel events...
         17.0s: Connecting to EventPipe...
         36.4s: Creating EventPipeEventSource...
         36.7s: EventPipeEventSource created
         37.4s: Dynamic.All callback registered
         37.4s: Running optional trace validator
         37.6s: Finished running optional trace validator
         37.6s: Starting stream processing...
         41.9s: Saw new provider 'Microsoft-DotNETCore-SampleProfiler'
         65.9s: Saw sentinel event
         65.9s: Stopped sending sentinel events
         66.3s: Starting event generating action...
         66.3s: Stopping event generating action
         66.4s: Sending StopTracing command...
        688.8s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
        707.7s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
        928.8s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
        
        cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/12/2023 3:39:43 PM, end: 2/12/2023 4:39:43 PM)
        Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json'
        Test Harness Exitcode is : -100
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh
```

**Comment by kunalspathak** [comment]
```
Error reading /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json: System.UnauthorizedAccessException: Access to the path '/home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, StreamWriter outputWriter)
```

Just to clarify for this specific error that we handled it in https://github.com/dotnet/runtime/pull/81467 and above logs are just printing that we saw problem access the crash report, but after that, things move on. Once again @hoyosjs  on what that would be problem in first place.

**Comment by BruceForstall** [comment]
Test is now disabled for GCStress for arm.

**Comment by hoyosjs** [comment]
IT might be that USER is not set: https://github.com/dotnet/runtime/blob/e0f7c43484f39d49c7c8d22d56dcc386215064bd/src/tests/Common/Coreclr.TestWrapper/CoreclrTestWrapperLib.cs#L368

**Comment by kunalspathak** [comment]
That's right and that can be confirmed from the logs, but how do we get it?

```
Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json
stdout: -rw------- 1 root root 83181 Feb 12 16:39 /home/helixbot/dotnetbuild/dumps/crashdump_496.dmp.crashreport.json
```

**Comment by davmason** [comment]
GCStress is not an interesting scenario for this test, closing this issue.
