### ISSUE TITLE
[6.0] CI test failure in OSX System.Net.Sockets.Tests.DualModeAccept.AcceptV4BoundToAnyV6_Success [FAIL]

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#81437]
Found in a release/6.0 backport PR. https://github.com/dotnet/runtime/pull/81281/checks?check_run_id=10937030682

Log: https://helix.dot.net/api/2019-06-17/jobs/1dacef47-5173-49ec-ac68-fc7446cf11ed/workitems/System.Net.Sockets.Tests/console
```log
System.Net.Sockets.Tests.DualModeAccept.AcceptV4BoundToAnyV6_Success [FAIL]
      System.ArgumentException : The supplied System.Net.Internals.SocketAddress is an invalid size for the System.Net.IPEndPoint end point. (Parameter 'socketAddress')
      Stack Trace:
        /_/src/libraries/Common/src/System/Net/Internals/IPEndPointExtensions.cs(36,0): at System.Net.Sockets.IPEndPointExtensions.Create(EndPoint thisObj, SocketAddress socketAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(1092,0): at System.Net.Sockets.Socket.Accept()
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(766,0): at System.Net.Sockets.Tests.DualModeAccept.Accept_Helper(IPAddress listenOn, IPAddress connectTo)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(756,0): at System.Net.Sockets.Tests.DualModeAccept.AcceptV4BoundToAnyV6_Success()
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
  Finished:    System.Net.Sockets.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 1888, Errors: 0, Failed: 1, Skipped: 1, Time: 5.332s
```

**Comment by antonfirsov** [comment]
Triage: we should keep monitoring if it happens again. We would only fix it if it fails massively.
