### ISSUE TITLE
Wrong line numbers in exception stack trace on macOS/arm64

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/runtime#81526]
### Description

This simple program throws an exception on the wrong line number, when run on an arm64 Mac in Release configuration:

```csharp
namespace ConsoleApp1;
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!" + args[0]);
    }
}
```

Run without args so an `IndexOutOfRangeException` occurs.  The exception *should* occur on line 6.
- In Release configuration with the arm64 macOS SDK, the stack trace incorrectly shows line 7.
- In Debug configuration with the arm64 macOS SDK, the stack trace shows correctly on line 6.
- In *either* configuration with the x64 macOS SDK, the stack trace shows correctly on line 6.

Same results for .NET 6 or .NET 7.  (6.0.405 or 7.0.102)

### Reproduction Steps

On an arm64 Mac, with the current arm64 SDK for .NET 6 or .NET 7 installed:

- `dotnet new console --use-program-main`
- Edit `Program.cs` and append ` + args[0]` to the string in the sample (or just copy from code above).
- `dotnet run -c Release`

### Expected behavior

Exception should show as:

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ConsoleApp1.Program.Main(String[] args) in /Users/matt/temp/ConsoleApp1/Program.cs:line 6
```

### Actual behavior

Exception actually shows as:

```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ConsoleApp1.Program.Main(String[] args) in /Users/matt/temp/ConsoleApp1/Program.cs:line 7
```

### Regression?

Unknown

### Known Workarounds

Run in Debug configuration, or run with the x64 SDK in either configuration.

### Configuration

`dotnet --info`

```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: arm64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.405 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found
```

### Other information

Might be related to #44986 - however that one is about x64 which appears to work for this code.  This one fails on arm64.

Also that one is using `System.Diagnostics.StackTrace` - where here I am just letting the runtime throw an exception without anything special.

**Comment by mattjohnsonpint** [comment]
Also note, if I change the code to this it gives the correct line number:

```csharp
namespace ConsoleApp1;
class Program
{
    static void Main(string[] args)
    {
        throw new Exception("test");
    }
}
```

**Comment by mattjohnsonpint** [comment]
It also gives the correct line number if I use the minimal console template and just have only:

```csharp
Console.WriteLine("Hello, World!" + args[0]);
```

**Comment by jakobbotsch** [comment]
The debug mappings generated by the JIT for x64/arm64 are pretty much equivalent in spirit:
```asm
; Assembly listing for method ConsoleApp1.Program:Main(System.String[]) (Tier0)
; Emitting BLENDED_CODE for X64 with AVX - Windows
; Tier0 code
; rbp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00    ] (  1,  1   )     ref  ->  [rbp+10H]   do-not-enreg[] class-hnd
;  V01 OutArgs      [V01    ] (  1,  1   )  struct (32) [rsp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;
; Lcl frame size = 32

G_M27759_IG01:  ;; offset=0000H
       push     rbp
       sub      rsp, 32
       lea      rbp, [rsp+20H]
       mov      gword ptr [rbp+10H], rcx
                                                ;; size=14 bbWeight=1 PerfScore 2.75
G_M27759_IG02:  ;; offset=000EH
                            ; INLRT @ 0x000[E-]
       mov      rdx, gword ptr [rbp+10H]
       xor      ecx, ecx
       cmp      ecx, dword ptr [rdx+08H]
       jae      SHORT G_M27759_IG04
       mov      eax, ecx
       lea      rdx, bword ptr [rdx+8*rax+10H]
       mov      rdx, gword ptr [rdx]
       mov      rcx, 0x19F74701720      ; 'Hello, World!'

       call     [System.String:Concat(System.String,System.String):System.String]
       mov      rcx, rax
       call     [System.Console:WriteLine(System.String)]
                            ; INLRT @ 0x012[E-]
       nop
                                                ;; size=47 bbWeight=1 PerfScore 15.25
G_M27759_IG03:  ;; offset=003DH
       add      rsp, 32
       pop      rbp
       ret
                                                ;; size=6 bbWeight=1 PerfScore 1.75
G_M27759_IG04:  ;; offset=0043H
       call     CORINFO_HELP_RNGCHKFAIL
       int3
                                                ;; size=6 bbWeight=0 PerfScore 0.00

; Total bytes of code 73, prolog size 10, PerfScore 27.05, instruction count 21, allocated bytes for code 73 (MethodHash=8b5b9390) for method ConsoleApp1.Program:Main(System.String[]) (Tier0)
; ============================================================

IP mapping count : 5
IL offs PROLOG : 0x00000000 ( STACK_EMPTY )
IL offs 0x0000 : 0x0000000E ( STACK_EMPTY )
IL offs 0x0012 : 0x0000003C ( STACK_EMPTY )
IL offs EPILOG : 0x0000003C ( STACK_EMPTY )
IL offs NO_MAP : 0x00000043 ( STACK_EMPTY )

; Variable debug info: 2 live ranges, 1 vars for method ConsoleApp1.Program:Main(System.String[])
(V00 arg0) : From 00000000h to 0000000Eh, in rcx
(V00 arg0) : From 0000000Eh to 00000048h, in rbp[16] (1 slot)
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ConsoleApp1.Program.Main(String[] args) in /media/windev/dotnet/playground/Program.cs:line 8
```

```asm
; Assembly listing for method ConsoleApp1.Program:Main(System.String[])
; Emitting BLENDED_CODE for generic ARM64 - Unix
; Tier-0 compilation
; MinOpts code
; fp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 arg0         [V00    ] (  1,  1   )     ref  ->  [fp+18H]   do-not-enreg[] class-hnd
;# V01 OutArgs      [V01    ] (  1,  1   )  struct ( 0) [sp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;
; Lcl frame size = 16

G_M27759_IG01:  ;; offset=0000H
            stp     fp, lr, [sp, #-0x20]!
            mov     fp, sp
            str     x0, [fp, #0x18]     // [V00 arg0]
                                                ;; size=12 bbWeight=1 PerfScore 2.50
G_M27759_IG02:  ;; offset=000CH
                             ; INLRT @ 0x000[E-]
            ldr     x1, [fp, #0x18]     // [V00 arg0]
            mov     w0, wzr
            ldr     w2, [x1, #0x08]
            cmp     w0, w2
            bhs     G_M27759_IG04
            add     x1, x1, x0,  LSL #3
            add     x1, x1, #16
            ldr     x1, [x1]
            movz    x0, #0xA820
            movk    x0, #0x7411 LSL #16
            movk    x0, #0xFFFF LSL #32
            movz    x2, #0x4CA8      // code for System.String:Concat(System.String,System.String):System.String
            movk    x2, #0x7975 LSL #16
            movk    x2, #0xFFFF LSL #32
            ldr     x2, [x2]
            blr     x2
            movz    x1, #0x47C8      // code for System.Console:WriteLine(System.String)
            movk    x1, #0x79B5 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
                                                ;; size=84 bbWeight=1 PerfScore 24.00
G_M27759_IG03:  ;; offset=0060H
                             ; INLRT @ 0x012[E-]
            ldp     fp, lr, [sp], #0x20
            ret     lr
                                                ;; size=8 bbWeight=1 PerfScore 2.00
G_M27759_IG04:  ;; offset=0068H
            bl      CORINFO_HELP_RNGCHKFAIL
            brk_unix #0
                                                ;; size=8 bbWeight=0 PerfScore 0.00

; Total bytes of code 112, prolog size 8, PerfScore 39.70, instruction count 28, allocated bytes for code 112 (MethodHash=8b5b9390) for method ConsoleApp1.Program:Main(System.String[])
; ============================================================

IP mapping count : 5
IL offs PROLOG : 0x00000000 ( STACK_EMPTY )
IL offs 0x0000 : 0x0000000C ( STACK_EMPTY )
IL offs 0x0012 : 0x00000060 ( STACK_EMPTY )
IL offs EPILOG : 0x00000060 ( STACK_EMPTY )
IL offs NO_MAP : 0x00000068 ( STACK_EMPTY )

; Variable debug info: 2 live ranges, 1 vars for method ConsoleApp1.Program:Main(System.String[])
(V00 arg0) : From 00000000h to 0000000Ch, in x0
(V00 arg0) : From 0000000Ch to 0000006Ch, in fp[24] (1 slot)
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ConsoleApp1.Program.Main(String[] args) in /media/windev/dotnet/playground/Program.cs:line 9
Aborted
```

Note that unlike actual debug-enabled codegen tier0 will use shared throw helpers which is related here. I'm not sure how x64 is doing the mapping back since there is actually no way to know how which indexing resulted in the throw helper being called (and indeed, if I add another array indexing expression x64 gets it wrong too). Let me see if I can figure out how the diagnostic layer ends up with 8 vs 9 -- it would be good to unify that, but overall the behavior here is by design and a tradeoff between debug and non-debug codegen.

**Comment by jakobbotsch** [comment]
The difference between x64 and arm64 is the following in `DebuggerJitInfo::MapNativeOffsetToIL`:
x64:
```
TID 9118: DJI::MNOTI: nativeOffset = 0x48
TID 9118: DJI::MNOTI: m->natStart:0x0 m->natEnd:0xe il:PROLOG
TID 9118: DJI::MNOTI: m->natStart:0xe m->natEnd:0x3c il:0x0 src:0x2
TID 9118: DJI::MNOTI: m->natStart:0x3c m->natEnd:0x3c il:0x12 src:0x2
TID 9118: DJI::MNOTI: m->natStart:0x3c m->natEnd:0x43 il:EPILOG
TID 9118: DJI::MNOTI: m->natStart:0x43 m->natEnd:0x0 il:NO MAP
TID 9118: DJI::MNOTI:MAPPING_UNMAPPED_ADDRESS
```

arm64:
```scala
TID 6babd: DJI::MNOTI: nativeOffset = 0x67
TID 6babd: DJI::MNOTI: m->natStart:0x0 m->natEnd:0xc il:PROLOG
TID 6babd: DJI::MNOTI: m->natStart:0xc m->natEnd:0x60 il:0x0 src:0x2
TID 6babd: DJI::MNOTI: m->natStart:0x60 m->natEnd:0x60 il:0x12 src:0x2
TID 6babd: DJI::MNOTI: m->natStart:0x60 m->natEnd:0x68 il:EPILOG
TID 6babd: DJI::MNOTI:MAPPING_EPILOG
```

So the VM/debug layer seems to end up with different `natEnd` for the EPILOG mapping. That causes the x64 version to return IL offset = 0, while the arm64 version sees the throw helper as being in the epilog and returns the last offset. I'll try to figure out the source of this difference.

There is a question of whether we should attach at least one of the throwing helper calls as debug info in the throw helper, though I'm not totally sure how the debug layer would react to these new mappings coming out of order.

**Comment by jakobbotsch** [comment]
The `nativeOffset = 0x67` that the ARM64 debug layer sees seems to be the culprit, since that's part of the epilog. The correct offset would be 0x68.

**Comment by jakobbotsch** [comment]
The code that subtracts 1 from the offset is here:

https://github.com/dotnet/runtime/blob/be09d8658987cdf2a9d221bb20f852ad9a503717/src/coreclr/vm/debugdebugger.cpp#L1224-L1250

Assumption 2 only seems to be true on x64; on x64 the offset passed to this function is 0x48, i.e. the return address of the call to `CORINFO_HELP_RNGCHKFAIL`. On arm64, the offset passed to the function is `0x68`, which is the address of the `bl` instruction, not the return address.

So this is probably EH related. @janvorli can you take a look?
