### ISSUE TITLE
[wasm] `SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain` fails intermittently on CI

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#81569]
[Rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=152219&view=logs&j=1567862a-6a9e-5016-9353-cc84f1411dc4&t=95224710-367f-55b7-6b5e-1fa98616b1e8), [console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1e68e43d939b4feeb5/chrome-DebuggerTests.SteppingTests/1/console.23cf62d7.log?helixlogtype=result), and
[proxy log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1e68e43d939b4feeb5/chrome-DebuggerTests.SteppingTests/1/xharness-output/logs/proxy-20230130.log?helixlogtype=result).

```
[xUnit.net 00:02:39.15]     DebuggerTests.SteppingTests.SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain(secondServers: ["https://symbols.nuget.org/download/symbols", ""]) [FAIL]
  Failed DebuggerTests.SteppingTests.SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain(secondServers: ["https://symbols.nuget.org/download/symbols", ""]) [1 s]
  Error Message:
   [[this] Value for json property named description didn't match.]

Expected: []
Actual:   Newtonsoft.Json.Linq.JArray
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.AssertEqual(Object expected, Object actual, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 1231
   at DebuggerTests.DebuggerTestBase.CheckValue(JToken actual_val, JToken exp_val, String label) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 900
   at DebuggerTests.DebuggerTestBase.CheckObject(JToken locals, String name, String class_name, String subtype, Boolean is_null, String description) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 391
   at DebuggerTests.SteppingTests.<SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain>b__40_1(JToken locals) in /_/src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:line 1214
   at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 636
   at DebuggerTests.DebuggerTestBase.StepAndCheck(StepKind kind, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, Int32 times) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 570
   at DebuggerTests.SteppingTests.SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain(String[] secondServers) in /_/src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:line 1211
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Information: [testId: 15] New test request for test id 15
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: [15] Starting C:\helix\work\correlation\chrome-win\chrome.exe with --headless --disable-gpu --lang=en-US --incognito --remote-debugging-port=0 http://localhost:9400/debugger-driver.html
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090419.564:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: The pipe has been ended. (0x6D)
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090419.625:ERROR:network_change_notifier_win.cc(224)] WSALookupServiceBegin failed with: 0
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr 
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr DevTools listening on ws://127.0.0.1:49386/devtools/browser/42f19f5a-9dd5-4214-9e73-2f2bd193757b
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: [testId: 14] TestHarnessStartup done
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 14
 | [2023-01-30T09:04:19] DebuggerTests.TestHarnessProxy Information: [testId: 15] launching proxy for ws://127.0.0.1:49386/devtools/page/9330C3815013CDA5D66A350FFC762E92
 | [2023-01-30T09:04:19] Inspector-15 Information: waiting for the runtime to be ready
 | [2023-01-30T09:04:21] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090421.062:ERROR:dxva_video_decode_accelerator_win.cc(1451)] DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found. (0x7E)
 | [2023-01-30T09:04:21] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090421.080:ERROR:dxva_video_decode_accelerator_win.cc(1451)] DXVAVDA fatal error: could not LoadLibrary: mfplat.dll: The specified module could not be found. (0x7E)
 | [2023-01-30T09:04:21] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090421.083:ERROR:dxva_video_decode_accelerator_win.cc(1451)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: The specified module could not be found. (0x7E)
 | [2023-01-30T09:04:21] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090421.085:ERROR:dxva_video_decode_accelerator_win.cc(1455)] DXVAVDA fatal error: could not LoadLibrary: dxva2.dll: The specified module could not be found. (0x7E)
 | [2023-01-30T09:04:21] DebuggerTests.TestHarnessProxy Debug: [testId: 15] browser-stderr [0130/090421.087:ERROR:dxva_video_decode_accelerator_win.cc(1459)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: The specified module could not be found. (0x7E)
 | [2023-01-30T09:04:28] Inspector-15 Information: runtime ready, TEST TIME
 Using cachePath: C:\Users\ContainerAdministrator\AppData\Local\Temp\dbg-tests-tmp\87352ff6-40d9-4ee6-9433-042cf639e32b\symbols-cache
 | [2023-01-30T09:04:28] Inspector-15 Information: console.warning: Loading symbols from symbol servers.
 | [2023-01-30T09:04:28] Inspector-15 Information: console.warning: Symbols from symbol servers completely loaded.
 | [2023-01-30T09:04:29] Inspector-15 Information: console.warning: Loading symbols from symbol servers.
 | [2023-01-30T09:04:29] Inspector-15 Information: console.warning: Symbols from symbol servers completely loaded.
 [[this] Value for json property named description didn't match.]

 Expected: []
 Actual:   Newtonsoft.Json.Linq.JArray 
Expected: {
   "type": "object",
   "className": "Newtonsoft.Json.Linq.JArray",
   "description": "[]"
 } 
Actual: {
   "type": "object",
   "value": null,
   "description": "Newtonsoft.Json.Linq.JArray",
   "className": "Newtonsoft.Json.Linq.JArray",
   "objectId": "dotnet:object:8"
 }

```

the proxy has:
```
2023-01-30T09:04:29.4426821+00:00 [DBG] DevToolsProxy-15: Error while evaluating ToString method: Microsoft.WebAssembly.Diagnostics.DebuggerAgentException: SendDebuggerAgentCommand failed for InvokeMethod: [Result: IsOk: False, IsErr: True, Value: , Error: {
  "result": {
    "type": "object",
    "subtype": "error",
    "className": "RuntimeError",
    "description": "RuntimeError: memory access out of bounds\n    at http://localhost:9400/dotnet.wasm:wasm-function[1022]:0x4dd96\n    at http://localhost:9400/dotnet.wasm:wasm-function[1021]:0x4dc14\n    at http://localhost:9400/dotnet.wasm:wasm-function[953]:0x49b2a\n    at http://localhost:9400/dotnet.wasm:wasm-function[926]:0x48c84\n    at http://localhost:9400/dotnet.wasm:wasm-function[247]:0x1a826\n    at http://localhost:9400/dotnet.wasm:wasm-function[244]:0x181a5\n    at http://localhost:9400/dotnet.wasm:wasm-function[286]:0x1bb78\n    at http://localhost:9400/dotnet.wasm:wasm-function[8325]:0x1b279e\n    at http://localhost:9400/dotnet.wasm:wasm-function[2154]:0x8ebfc\n    at http://localhost:9400/dotnet.wasm:wasm-function[2159]:0x8f29e",
    "objectId": "1101866362431735367.2.439"
  },
  "exceptionDetails": {
    "exceptionId": 3,
    "text": "Uncaught",
    "lineNumber": 0,
    "columnNumber": 318870,
    "scriptId": "10",
    "stackTrace": {
      "callFrames": [
        {
          "functionName": "$func1022",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 318870
        },
        {
          "functionName": "$func1021",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 318484
        },
        {
          "functionName": "$func953",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 301866
        },
        {
          "functionName": "$func926",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 298116
        },
        {
          "functionName": "$func247",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 108582
        },
        {
          "functionName": "$func244",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 98725
        },
        {
          "functionName": "$func286",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 113528
        },
        {
          "functionName": "$func8325",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 1779614
        },
        {
          "functionName": "$func2154",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 584700
        },
        {
          "functionName": "$func2159",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 586398
        },
        {
          "functionName": "$func1036",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 325125
        },
        {
          "functionName": "$mono_wasm_send_dbg_command",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 297752
        },
        {
          "functionName": "Module._mono_wasm_send_dbg_command",
          "scriptId": "9",
          "url": "http://localhost:9400/dotnet.js",
          "lineNumber": 13,
          "columnNumber": 133672
        },
        {
          "functionName": "O",
          "scriptId": "9",
          "url": "http://localhost:9400/dotnet.js",
          "lineNumber": 2,
          "columnNumber": 8083
        },
        {
          "functionName": "",
          "scriptId": "208",
          "url": "",
          "lineNumber": 0,
          "columnNumber": 29
        },
        {
          "functionName": "mono_wasm_fire_debugger_agent_message",
          "scriptId": "9",
          "url": "http://localhost:9400/dotnet.js",
          "lineNumber": 2,
          "columnNumber": 7461
        },
        {
          "functionName": "$func930",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 298573
        },
        {
          "functionName": "$func1103",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 363471
        },
        {
          "functionName": "$func1027",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 322249
        },
        {
          "functionName": "$func1026",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 320785
        },
        {
          "functionName": "$func953",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 301887
        },
        {
          "functionName": "$func926",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 298116
        },
        {
          "functionName": "$func247",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 108582
        },
        {
          "functionName": "$func244",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 98725
        },
        {
          "functionName": "$func286",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 113528
        },
        {
          "functionName": "$func8325",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 1779614
        },
        {
          "functionName": "$func2154",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 584700
        },
        {
          "functionName": "$func2159",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 586398
        },
        {
          "functionName": "$func2186",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 595349
        },
        {
          "functionName": "$mono_wasm_invoke_method_ref",
          "scriptId": "10",
          "url": "http://localhost:9400/dotnet.wasm",
          "lineNumber": 0,
          "columnNumber": 41851
        },
        {
          "functionName": "Module._mono_wasm_invoke_method_ref",
          "scriptId": "9",
          "url": "http://localhost:9400/dotnet.js",
          "lineNumber": 13,
          "columnNumber": 124056
        },
        {
          "functionName": "_debugger_test__TestLoadSymbols_Run",
          "scriptId": "92",
          "url": "https://dotnet.generated.invalid/_debugger_test__TestLoadSymbols_Run",
          "lineNumber": 24,
          "columnNumber": 4
        },
        {
          "functionName": "invoke_static_method",
          "scriptId": "4",
          "url": "http://localhost:9400/debugger-driver.html",
          "lineNumber": 27,
          "columnNumber": 10
        },
        {
          "functionName": "",
          "scriptId": "86",
          "url": "",
          "lineNumber": 0,
          "columnNumber": 93
        }
      ]
    },
    "exception": {
      "type": "object",
      "subtype": "error",
      "className": "RuntimeError",
      "description": "RuntimeError: memory access out of bounds\n    at http://localhost:9400/dotnet.wasm:wasm-function[1022]:0x4dd96\n    at http://localhost:9400/dotnet.wasm:wasm-function[1021]:0x4dc14\n    at http://localhost:9400/dotnet.wasm:wasm-function[953]:0x49b2a\n    at http://localhost:9400/dotnet.wasm:wasm-function[926]:0x48c84\n    at http://localhost:9400/dotnet.wasm:wasm-function[247]:0x1a826\n    at http://localhost:9400/dotnet.wasm:wasm-function[244]:0x181a5\n    at http://localhost:9400/dotnet.wasm:wasm-function[286]:0x1bb78\n    at http://localhost:9400/dotnet.wasm:wasm-function[8325]:0x1b279e\n    at http://localhost:9400/dotnet.wasm:wasm-function[2154]:0x8ebfc\n    at http://localhost:9400/dotnet.wasm:wasm-function[2159]:0x8f29e",
      "objectId": "1101866362431735367.2.440"
    }
  }
} ]
   at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.SendDebuggerAgentCommand[T](T command, MonoBinaryWriter arguments, CancellationToken token, Boolean throwOnError) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 1014
   at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.InvokeMethod(ArraySegment`1 argsBuffer, Int32 methodId, CancellationToken token, String name, Boolean isMethodStatic) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 1843
   at Microsoft.WebAssembly.Diagnostics.MonoSDBHelper.InvokeToStringAsync(IEnumerable`1 typeIds, Boolean isValueType, Boolean isEnum, Int32 objectId, BindingFlags extraFlags, CancellationToken token) in /_/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs:line 1905
2023-01-30T09:04:29.4428548+00:00 [VRB] DevToolsProxy-15: to-ide:  {
  "id": 16,
  "sessionId": null,
  "result": {
    "result": [
      {
        "value": {
          "type": "object",
          "value": null,
          "description": "Manual text",
          "className": "Newtonsoft.Json.Linq.JValue",
          "objectId": "dotnet:object:7"
        },
        "writable": false,
        "name": "item"
      },
      {
        "value": {
          "type": "object",
          "value": null,
          "description": "Newtonsoft.Json.Linq.JArray",
          "className": "Newtonsoft.Json.Linq.JArray",
          "objectId": "dotnet:object:8"
        },
        "writable": false,
        "name": "this",
        "fieldOffset": -1
      }
    ],
    "privateProperties": []
  }
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment]
has this been fixed?

**Comment by thaystg** [comment]
I think so.
