### ISSUE TITLE
Test failure System.Text.RegularExpressions.Tests.UpgradeToGeneratedRegexAnalyzerTests.NoDiagnosticsForNet60(invocationType: StaticMethods)

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#81586]
Run: [runtime-coreclr libraries-jitstress 20230201.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=156964&view=ms.vss-test-web.build-test-results-tab&runId=3257855&resultId=196341&paneView=debug)

Failed test:
```
net8.0-linux-Release-x64-CoreCLR_checked-zapdisable-Ubuntu.1804.Amd64.Open

- System.Text.RegularExpressions.Tests.UpgradeToGeneratedRegexAnalyzerTests.NoDiagnosticsForNet60(invocationType: StaticMethods)
```
**Error message:**
```
NuGet.Protocol.Core.Types.FatalProtocolException : An error occurred while retrieving package metadata for 'Microsoft.NETCore.App.Ref.6.0.0' from source 'nuget.org'.
---- System.Net.Http.HttpRequestException : Response status code does not indicate success: 400 (Bad Request).


Stack trace
   at NuGet.Protocol.DependencyInfoResourceV3.ResolvePackage(PackageIdentity package, NuGetFramework projectFramework, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.GetPackageDependenciesAsync(PackageIdentity packageIdentity, NuGetFramework targetFramework, ImmutableArray`1 repositories, SourceCacheContext cacheContext, ILogger logger, Builder dependencies, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 570
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 227
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 197
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 174
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.CreateSolutionAsync(ProjectId projectId, EvaluatedProjectState projectState, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1235
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.CreateProjectImplAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1050
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.CreateProjectAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1029
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.GetSolutionAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 1007
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.GetSortedDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, ImmutableArray`1 analyzers, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 890
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 273
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunImplAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 304
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 181
   at System.Text.RegularExpressions.Tests.CSharpCodeFixVerifier`2.VerifyCodeFixAsync(String source, String fixedSource, ReferenceAssemblies references) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/CSharpCodeFixVerifier`2.cs:line 36
   at System.Text.RegularExpressions.Tests.CSharpCodeFixVerifier`2.VerifyAnalyzerAsync(String source, ReferenceAssemblies references) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/CSharpCodeFixVerifier`2.cs:line 25
   at System.Text.RegularExpressions.Tests.UpgradeToGeneratedRegexAnalyzerTests.NoDiagnosticsForNet60(InvocationType invocationType) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/UpgradeToGeneratedRegexAnalyzerTests.cs:line 159
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 165
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.RegistrationUtility.LoadRanges(HttpSource httpSource, Uri registrationUri, String packageId, VersionRange range, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.ResolverMetadataClient.GetDependencies(HttpSource httpClient, Uri registrationUri, String packageId, VersionRange range, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.ResolverMetadataClient.GetRegistrationInfo(HttpSource httpClient, Uri registrationUri, String packageId, VersionRange range, SourceCacheContext cacheContext, NuGetFramework projectTargetFramework, ILogger log, CancellationToken token)
   at NuGet.Protocol.DependencyInfoResourceV3.ResolvePackage(PackageIdentity package, NuGetFramework projectFramework, SourceCacheContext cacheContext, ILogger log, CancellationToken token)
```

**Comment by stephentoub** [comment]
This looks like a temporary networking issue while resolving nuget packages.  I'm going to close it for now; we can reopen if it occurs again.

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20230219.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=177303&view=ms.vss-test-web.build-test-results-tab&runId=3497939&resultId=166300&paneView=debug)

Failed test:
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstressregs3-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- LibraryImportGenerator.UnitTests.Compiles.ValidateNoGeneratedOuptutForNoImport(id: \"Compiles.cs:652\", source: \"\\nusing System.Runtime.InteropServices;\\npublic cl\"..., framework: Standard)

net8.0-linux-Release-arm-CoreCLR_checked-jitstressregs0x1000-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- LibraryImportGenerator.UnitTests.Compiles.ValidateNoGeneratedOuptutForNoImport(id: \"Compiles.cs:653\", source: \"\\nusing System.Runtime.InteropServices;\\npublic cl\"..., framework: Framework)
- LibraryImportGenerator.UnitTests.Compiles.ValidateNoGeneratedOuptutForNoImport(id: \"Compiles.cs:652\", source: \"\\nusing System.Runtime.InteropServices;\\npublic cl\"..., framework: Standard)
```
**Error message:**
```
NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json.
---- System.Net.Http.HttpRequestException : Response status code does not indicate success: 503 (Service Unavailable).


Stack trace
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.DependencyInfoResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.GetPackageDependenciesAsync(PackageIdentity packageIdentity, NuGetFramework targetFramework, ImmutableArray`1 repositories, SourceCacheContext cacheContext, ILogger logger, Builder dependencies, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 569
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveCoreAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 227
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 197
   at Microsoft.CodeAnalysis.Testing.ReferenceAssemblies.ResolveAsync(String language, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/ReferenceAssemblies.cs:line 174
   at Microsoft.Interop.UnitTests.TestUtils.ResolveReferenceAssemblies(ReferenceAssemblies referenceAssemblies) in /_/src/libraries/System.Runtime.InteropServices/tests/Common/TestUtils.cs:line 274
   at Microsoft.Interop.UnitTests.TestUtils.GetReferenceAssemblies(TestTargetFramework targetFramework) in /_/src/libraries/System.Runtime.InteropServices/tests/Common/TestUtils.cs:line 220
   at Microsoft.Interop.UnitTests.TestUtils.CreateCompilation(SyntaxTree[] sources, TestTargetFramework targetFramework, OutputKind outputKind, IEnumerable`1 refs, Boolean allowUnsafe) in /_/src/libraries/System.Runtime.InteropServices/tests/Common/TestUtils.cs:line 174
   at LibraryImportGenerator.UnitTests.Compiles.ValidateNoGeneratedOuptutForNoImport(String id, String source, TestTargetFramework framework) in /_/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Compiles.cs:line 662
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 165
   at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
```

**Comment by stephentoub** [comment]
@ViktorHofer, is there anything to be done about this?

**Comment by ViktorHofer** [comment]
Not really. NuGet already retries and the two status codes indicate a server error. We should probably close the issue.

**Comment by BruceForstall** [comment]
Closing

**Comment by stephentoub** [comment]
Related:
https://github.com/dotnet/runtime/pull/82431#issuecomment-1438984253
