### ISSUE TITLE
Inconsistent behavior in `SslStream.AuthenticateAsClient` across win/linux

### ISSUE THREAD

**Issue by CharlieEriksen** [dotnet/runtime#81590]
### Description

On .NET 7.0, `SslStream.AuthenticateAsClient` behaves differently on Windows and Linux. When `TargetHost` is set for the `SslClientAuthenticationOptions` parameter, in some cases on Linux it will lead to the connection not establishing successfully, while it does on Windows.

While this appears to be host specific and is dependent on the parameters to `AuthenticateAsClient`, the fact that the very same code does not function the same across OS is problematic, leading to a lot of wasted time. 

On Linux, you will simply get a connection reset:
```
Unhandled exception. System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SyncReadWriteAdapter.ReadAsync(Stream stream, Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at Program.Main() in /mnt/c/Users/Charlie/RiderProjects/SslStreamTest/SslStreamTest/Program.cs:line 17
```

### Reproduction Steps

Run this code across both Windows and Linux:
```csharp
using System.Net.Security;
using System.Net.Sockets;
					
public class Program
{
    public static void Main()
    {
        TcpClient client = new TcpClient("143.166.83.22", 443);
        SslStream sslStream = new SslStream(client.GetStream(), false);

        sslStream.AuthenticateAsClient(new SslClientAuthenticationOptions(){TargetHost = "143.166.83.22",RemoteCertificateValidationCallback = (sender, x509Certificate, chain, errors) => true});
    }
}
```

### Expected behavior

As seen on Windows: A connection is established. 

### Actual behavior

As seen on Linux: Connection is reset:
```
Unhandled exception. System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SyncReadWriteAdapter.ReadAsync(Stream stream, Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at Program.Main() in /mnt/c/Users/Charlie/RiderProjects/SslStreamTest/SslStreamTest/Program.cs:line 17
```

### Known Workarounds

Not setting `TargetHost` can help in some cases. 

### Configuration

Windows:
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
```

Linux, wsl:
```
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.102/

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [/usr/share/dotnet/sdk]
```

**Comment by rzikm** [comment]
This is kinda interesting. I can replicate this using openssl cli

```
openssl s_client -connect 143.166.83.22:443 -servername "143.166.83.22"
```

If I omit the -servername parameter (equivalent to not specifying `TargetHost` in .NET), then everything works.

The difference in behavior is caused by difference between SChannel and OpenSSL. SChannel will not send the SNI extension when you specify the `TargetHost` as IP address, while OpenSSL will send whatever you tell it to.

From [RFC 6066](https://www.rfc-editor.org/rfc/rfc6066#section-3)

> Literal IPv4 and IPv6 addresses are not permitted in "HostName".

The specific server in question (pc-premierce80.us.dell.com) is kinda picky about SNI and will close the connection when SNI can be interpreted as IP address. Not all servers behave like this btw.

We can probably check if the `TaretHost` parses as IP address and avoid sending it to be consistent across platforms. An obvious workaround for the user is not setting `TargetHost` to an IP literal.

Not critical for 8.0, moving to future. This should also be relatively simple, so it is a good candidate for external contribution.

**Comment by wfurt** [comment]
https://www.rfc-editor.org/rfc/rfc6066#page-7
```
   "HostName" contains the fully qualified DNS hostname of the server,
   as understood by the client.  The hostname is represented as a byte
   string using ASCII encoding without a trailing dot.  This allows the
   support of internationalized domain names through the use of A-labels
   defined in [[RFC5890](https://www.rfc-editor.org/rfc/rfc5890)].  DNS hostnames are case-insensitive.  The
   algorithm to compare hostnames is described in [[RFC5890](https://www.rfc-editor.org/rfc/rfc5890)], [Section](https://www.rfc-editor.org/rfc/rfc6066#section-2.3.2.4)
   [2.3.2.4](https://www.rfc-editor.org/rfc/rfc6066#section-2.3.2.4).

   Literal IPv4 and IPv6 addresses are not permitted in "HostName".
```

I think we should fix it @rzikm even if the server behavior is finicky. 
(and also make sure HttpClient does not try to set it)

**Comment by rzikm** [comment]
I did not realize the issue cannot be avoided with HttpClient. So fixing the issue in 8.0 makes more sense.

I think fixing it on SslStream level (not passing TargetHost to underlying platform crypto) should be enough, no need to do the same on HttpClient level.

**Comment by CharlieEriksen** [comment]
Thanks for the quick triage and for figuring out what was wrong @rzikm and @wfurt. I hadn't actually caught the fact that it also was an issue with HttpClient, but I had been wondering why my HTTP responses against IP addresses were rather flaky. So that explains that!
