### ISSUE TITLE
Fail to run Q# program because an dotnet runtime error

### ISSUE THREAD

**Issue by weucode** [dotnet/runtime#81679]
### Description

When running the program in [this issue](https://github.com/microsoft/qsharp-runtime/issues/1106), it went wrong with a runtime exception`System.DivideByZeroException: Attempted to divide by zero`. 

We tried to import `ModPowL` as a user-defined API and call it, but it did not get the same exception, meaning that the content in `ModPowL` was right. Moreover, we found that the error message point to something error in [this page](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigIntegerCalculator.PowMod.cs). 

Here are the error message:
```
Unhandled exception. System.DivideByZeroException: Attempted to divide by zero.
 ---> NISLNameSpace.main on /home/htm/qsharpProject/quantumDemo3/Program.qs:line 10

Unhandled exception: System.DivideByZeroException: Attempted to divide by zero.
   at System.Numerics.BigIntegerCalculator.PowCore(UInt32 power, UInt32 modulus, UInt64 value, UInt64 result)
   at System.Numerics.BigInteger.ModPow(BigInteger value, BigInteger exponent, BigInteger modulus)
   at Microsoft.Quantum.Math.ModPowL.Native.<>c.<get___Body__>b__2_0(ValueTuple`3 args)
   at Microsoft.Quantum.Simulation.Core.Function`2.Apply(I a)
   at Microsoft.Quantum.Simulation.Core.Function`2.Microsoft.Quantum.Simulation.Core.ICallable<I,O>.Apply(I args)
   at NISLNameSpace.main.<get___Body__>b__16_0(QVoid __in__) in /home/htm/qsharpProject/quantumDemo3/Program.qs:line 10
   at Microsoft.Quantum.Simulation.Core.Operation`2.Apply(I a)
   at Microsoft.Quantum.Simulation.Core.Operation`2.Apply[GenO](Object args)
   at Microsoft.Quantum.Simulation.Common.SimulatorBase.Execute[T,I,O](I args)
   at Microsoft.Quantum.Simulation.Common.SimulatorBase.<>c__DisplayClass68_0`3.<Run>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Quantum.EntryPointDriver.Simulation`3.RunSimulator(TIn input, Func`1 createSimulator)
   at Microsoft.Quantum.EntryPointDriver.Simulation`3.Simulate(IEntryPoint entryPoint, TIn input, DriverSettings settings, String simulator)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Can you give me some suggestion about why this program run failure?

### Reproduction Steps

Run the program.

```namespace NameSpace {
	open Microsoft.Quantum.Math;
	open Microsoft.Quantum.Intrinsic;

	@EntryPoint()
	operation main() : Unit {
		let value = 1L;
		let exponent = 0L;
		let modulus = 0L;
		let result = ModPowL(value,exponent,modulus);
		Message($"{value}");
		Message($"{exponent}");
		Message($"{modulus}");
		Message($"{result}");
	}
}
```

### Expected behavior

1
0
0
1

### Actual behavior

Unhandled exception. System.DivideByZeroException: Attempted to divide by zero.
 ---> NISLNameSpace.main on /home/htm/qsharpProject/quantumDemo3/Program.qs:line 10

### Configuration

**dotnet version**:6.0.400

**os version**:Windows10 & Ubuntu18.04

**QDK version**:0.27.253010

**Comment by Clockwork-Muse** [comment]
> let modulus = 0L;

This is a definition problem [of the modulus operator](https://en.wikipedia.org/wiki/Modulo#:~:text=In%20computing%2C%20the%20modulo%20operation%20returns%20the%20remainder,is%20the%20dividend%20and%20n%20is%20the%20divisor.):
> In [computing](https://en.wikipedia.org/wiki/Computing), the modulo operation returns the [remainder](https://en.wikipedia.org/wiki/Remainder) or signed remainder of a [division](https://en.wikipedia.org/wiki/Division_(mathematics)), after one number is divided by another (called the [modulus](https://en.wikipedia.org/wiki/Modular_arithmetic) of the operation).  
> Given two positive numbers a and n, a modulo n (often abbreviated as a mod n) is the remainder of the [Euclidean division](https://en.wikipedia.org/wiki/Euclidean_division) of a by n, where a is the [dividend](https://en.wikipedia.org/wiki/Division_(mathematics)) and n is the [divisor](https://en.wikipedia.org/wiki/Divisor).

In other words, you're asking the code to perform `someValue % 0`, so a `DivideByZeroException` is **expected** (in some cases this can even be spotted [at compile time](https://dotnetfiddle.net/fi8NOD)). 

> We tried to import `ModPowL` as a user-defined API and call it, but it did not get the same exception, meaning that the content in `ModPowL` was right.

Not sure what you were doing here, but this sounds like a more serious problem, because the exception should have been thrown.

</hr>
As designed, not a bug in the core libraries.
