### ISSUE TITLE
[wasm][debugger] Multiple tests failing on rolling builds on Windows

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#81792]
Multiple tests are failing on [rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=163015&view=results). One of them([log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-11494c94a15e44e0bc/chrome-DebuggerTests.ArrayTests/1/console.ea4a5947.log?helixlogtype=result)):

```
DebuggerTests.ArrayTests.InspectValueTypeArrayLocalsInAsyncInstanceStructMethod(use_cfo: False) [FAIL]
  Failed DebuggerTests.ArrayTests.InspectValueTypeArrayLocalsInAsyncInstanceStructMethod(use_cfo: False) [1 ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Command Profiler.enable timed out during init for the test.Remaining commands: [Debugger.enable: Canceled], [Runtime.runIfWaitingForDebugger: Canceled], [Debugger.setAsyncCallStackDepth: Canceled], [Target.setAutoAttach: Canceled], [app-ready: Canceled].Total time: 60.0025634
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, TimeSpan span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 380
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 167
  Standard Output Messages:
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Information: [testId: 12] New test request for test id 12
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [12] Starting C:\helix\work\correlation\chrome-win\chrome.exe with --headless --disable-gpu --lang=en-US --incognito --remote-debugging-port=0 http://localhost:9400/debugger-driver.html
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.805:ERROR:registration_protocol_win.cc(135)] TransactNamedPipe: The pipe has been ended. (0x6D)
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.856:ERROR:network_change_notifier_win.cc(222)] WSALookupServiceBegin failed with: 0
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr 
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr DevTools listening on ws://127.0.0.1:49281/devtools/browser/11cc8e69-f3f3-4632-8b76-52610f837d6d
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.947:ERROR:dxva_video_decode_accelerator_win.cc(1453)] DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found. (0x7E)
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.954:ERROR:dxva_video_decode_accelerator_win.cc(1453)] DXVAVDA fatal error: could not LoadLibrary: mfplat.dll: The specified module could not be found. (0x7E)
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.956:ERROR:dxva_video_decode_accelerator_win.cc(1453)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: The specified module could not be found. (0x7E)
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.959:ERROR:dxva_video_decode_accelerator_win.cc(1457)] DXVAVDA fatal error: could not LoadLibrary: dxva2.dll: The specified module could not be found. (0x7E)
 | [2023-02-07T20:59:24] DebuggerTests.TestHarnessProxy Debug: [testId: 12] browser-stderr [0207/205924.961:ERROR:dxva_video_decode_accelerator_win.cc(1461)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: The specified module could not be found. (0x7E)
 | [2023-02-07T20:59:25] DebuggerTests.TestHarnessProxy Information: [testId: 12] launching proxy for ws://127.0.0.1:49281/devtools/page/993BC43AA975F885A273B5A0EF15F96A
 | [2023-02-07T20:59:25] Inspector-12 Information: waiting for the runtime to be ready
 | [2023-02-07T20:59:25] DebuggerTests.TestHarnessProxy Debug: [testId: 11] TestHarnessStartup done
 | [2023-02-07T20:59:25] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 11
```

**Comment by radical** [comment]
This seems to be related to chrome version. It was working fine with `109.0.5414.119`, but fails with the latest stable `110.0.5481.77`.

It is reproducible on codespaces, for example when running tests for AssignmentTests .

**Comment by radical** [comment]
@thaystg Should this be closed? On CI it seems to pass with the latest stable (111.x). Is it true on codespaces too?

**Comment by thaystg** [comment]
Yeah, I've just tested on codespaces and it's working, let me close.
