### ISSUE TITLE
Code coverage failing for corelib

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#81835]
Trying to do code coverage on corelib (e.g. do code coverage for System.Collections.Concurrent's tests) results in failure:
```
Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
     at System.Runtime.CompilerServices.RuntimeHelpers.GetSpanDataFrom(RuntimeFieldHandle fldHandle, RuntimeTypeHandle targetTypeHandle, Int32& count)
     at System.Runtime.CompilerServices.RuntimeHelpers.CreateSpan[T](RuntimeFieldHandle fldHandle) in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\CompilerServices\RuntimeHelpers.cs:line 100
     at System.DateTime.get_DaysToMonth365() in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\DateTime.cs:line 124
     at System.DateTime.CreateDateTimeFromSystemTime(SYSTEMTIME& time, UInt64 hundredNanoSecond) in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\DateTime.Windows.cs:line 112
     at System.DateTime.UpdateLeapSecondCacheAndReturnUtcNow() in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\DateTime.Windows.cs:line 247
     at System.DateTime.get_UtcNow() in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\DateTime.Windows.cs:line 34
     at System.DateTimeOffset.get_UtcNow() in D:\repos\runtime\src\libraries\System.Private.CoreLib\src\System\DateTimeOffset.cs:line 340
     at Xunit.XunitFilters.ChangeTrackingHashSet`1..ctor(IEqualityComparer`1 comparer) in /_/src/xunit.runner.utility/Project/XunitFilters.cs:line 280
     at Xunit.XunitFilters..ctor() in /_/src/xunit.runner.utility/Project/XunitFilters.cs:line 33
     at Xunit.XunitProject..ctor() in /_/src/xunit.runner.utility/Project/XunitProject.cs:line 17
     at Xunit.ConsoleClient.CommandLine.GetProjectFile(List`1 assemblies) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/CommandLine.cs:line 85
     at Xunit.ConsoleClient.CommandLine.Parse(Predicate`1 fileExists) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/CommandLine.cs:line 234
     at Xunit.ConsoleClient.CommandLine..ctor(String[] args, Predicate`1 fileExists) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/CommandLine.cs:line 21
     at Xunit.ConsoleClient.CommandLine.Parse(String[] args) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/CommandLine.cs:line 110
     at Xunit.ConsoleClient.ConsoleRunner.EntryPoint(String[] args) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/ConsoleRunner.cs:line 31
     at Xunit.ConsoleClient.Program.Main(String[] args) in /_/src/Microsoft.DotNet.XUnitConsoleRunner/src/Program.cs:line 16
```

Failure from RuntimeHelpers.CreateSpan like this typically means the field being referenced isn't properly aligned.  Does the coverlet collector do anything that might impact such alignment?

cc: @ViktorHofer, @MarcoRossignoli

**Comment by MarcoRossignoli** [comment]
Last release was done https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Changelog.md#release-date-2022-10-29 last October, has something changed? 
Coverlet is inserting a tracker and inserting a call to an helper method 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/7894084/217618635-0e23e31d-4224-466f-80d8-f9a72aa31957.png">
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/7894084/217618721-31accc52-b89c-429a-b957-70ff5ad2de8d.png">

**Comment by ViktorHofer** [comment]
We actually use the 3.1.2 version: https://github.com/dotnet/runtime/blob/bd540938a4830ee91dec5ee2d39545b2f69a19d5/.config/dotnet-tools.json#L6

**Comment by stephentoub** [comment]
> Coverlet is inserting a tracker and a call to an helper method

Is the rewritten corelib persisted to disk somewhere?

**Comment by stephentoub** [comment]
My guess is coverlet is using a cecil and a version of it that lacks https://github.com/jbevain/cecil/pull/817 and/or https://github.com/jbevain/cecil/pull/888.
cc: @sbomer

**Comment by MarcoRossignoli** [comment]
> What library (and what version of that library) is it using to rewrite the assembly?
```
<PackageReference Update="Mono.Cecil" Version="0.11.1" />
```

> Is the rewritten corelib persisted to disk somewhere?

Unfortunately not...if you can "block a test" adding some sleep it's possible copy/paste the instrumented lib somewhere for inspection. The instrumented lib is restored at the end of the tests and we don't have an option to preserve it.

**Comment by stephentoub** [comment]
@sbomer, it looks like Mono.Cecil hasn't published an update in a year and a half.  How do we go about spurring that along?  Anyone using any of the released versions with newer releases of Roslyn could end up having problems.

**Comment by stephentoub** [comment]
> FYI a new cecil release was just published!

Thanks, @sbomer. @MarcoRossignoli, could coverlet be updated to use the new build?

**Comment by MarcoRossignoli** [comment]
Thanks @stephentoub I'll do soon as possible.
