### ISSUE TITLE
[wasi] `System.Globalization.CultureNotFoundException : Only the invariant culture is supported in globalization-invariant mode. `

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#81908]
[build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=164683&view=logs&j=1e6805f2-db3e-5a24-0ebf-884eed04edf0&t=045c6ff3-c0bb-5f29-6ed4-ed58f4e24c0c), and [Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81649-merge-ce422f9d0b1548a4bf/System.Memory.Tests/1/console.0d7ab3c8.log?helixlogtype=result):

```
[22:28:39] fail: [FAIL] System.SpanTests.TryWriteTests.AppendFormatted_ValueTypes_CreateProviderFlowed
[22:28:39] info: System.Globalization.CultureNotFoundException : Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
[22:28:39] info: en-US is an invalid culture identifier.
[22:28:39] info:    at System.Globalization.CultureInfo..ctor(String , Boolean )
[22:28:39] info:    at System.Globalization.CultureInfo..ctor(String )
[22:28:39] info:    at System.SpanTests.TryWriteTests.<AppendFormatted_ValueTypes_CreateProviderFlowed>g__Test|10_0[FormattableInt32Wrapper](FormattableInt32Wrapper t)
[22:28:39] info:    at System.SpanTests.TryWriteTests.AppendFormatted_ValueTypes_CreateProviderFlowed()
[22:28:39] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
[22:28:39] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

cc @pavelsavara @mkhamoyan

**Comment by pavelsavara** [comment]
Because

https://github.com/dotnet/runtime/blob/db00f4e7146708fcb4877a3e4dd726d6a7eb83af/src/mono/wasi/runtime/driver.c#L12

**Comment by radical** [comment]
There are other changes needed too. I can't work on this right now, so unassigned myself.

**Comment by mkhamoyan** [comment]
I can work on this next week.
