### ISSUE TITLE
System.Security.Cryptography.CryptographicException : No hay más extremos disponibles desde el asignador de extremos.

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#82027]
Multiple failing tests, see https://github.com/dotnet/runtime/pull/82022/checks?check_run_id=11291261767.

```
System.Security.Cryptography.CryptographicException : No hay más extremos disponibles desde el asignador de extremos.

 at System.Security.Cryptography.CngHelpers.OpenStorageProvider(CngProvider provider) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngHelpers.cs:line 36
   at System.Security.Cryptography.CngKey.Import(ReadOnlySpan`1 keyBlob, String curveName, CngKeyBlobFormat format, CngProvider provider) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs:line 125
   at System.Security.Cryptography.CngKey.Import(Byte[] keyBlob, String curveName, CngKeyBlobFormat format, CngProvider provider) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs:line 113
   at System.Security.Cryptography.CngKey.Import(Byte[] keyBlob, String curveName, CngKeyBlobFormat format) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CngKey.Import.cs:line 35
   at System.Security.Cryptography.ECCng.ImportKeyBlob(Byte[] ecBlob, String curveName, Boolean includePrivateParameters) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECCng.ImportExport.cs:line 13
   at System.Security.Cryptography.ECDsaCng.ImportKeyBlob(Byte[] ecfullKeyBlob, String curveName, Boolean includePrivateParameters) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECDsaCng.cs:line 117
   at System.Security.Cryptography.ECDsaCng.ImportParameters(ECParameters parameters) in /_/src/libraries/Common/src/System/Security/Cryptography/ECDsaCng.ImportExport.cs:line 69
   at System.Security.Cryptography.ECDsa.Create(ECParameters parameters) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/ECDsa.Create.Windows.cs:line 36
   at System.Security.Cryptography.Cose.Tests.CoseTestHelpers.CreateECDsa(ECParameters parameters, Boolean includePrivateKey) in /_/src/libraries/System.Security.Cryptography.Cose/tests/CoseTestHelpers.cs:line 394
   at System.Security.Cryptography.Cose.Tests.CoseTestHelpers.get_ES256() in /_/src/libraries/System.Security.Cryptography.Cose/tests/CoseTestHelpers.cs:line 346
   at System.Security.Cryptography.Cose.Tests.CoseTestHelpers.get_DefaultKey() in /_/src/libraries/System.Security.Cryptography.Cose/tests/CoseTestHelpers.cs:line 361
   at System.Security.Cryptography.Cose.Tests.CoseHeaderMapTests.DecodedProtectedMapShouldBeReadOnly() in /_/src/libraries/System.Security.Cryptography.Cose/tests/CoseHeaderMapTests.cs:line 180
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=169255
Build error leg or test failing: System.Security.Cryptography.Cose.Tests.CoseHeaderMapTests.DecodedProtectedMapShouldBeReadOnly
Pull request: https://github.com/dotnet/runtime/pull/82022

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "CoseHeaderMapTests",
  "ExcludeConsoleLog": false
}
```

Cc @Jozkee 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by vcsjones** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/74838
