### ISSUE TITLE
Test failure System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82055]
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20230211.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=168368)
 
 **Failed tests:**
 ```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x80-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x1000-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs8-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x10-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs4-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue

net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs3-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue 
```
 
 **Error message:**
 ```
 Assert.True() Failure
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs:line 63
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
 ```

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

**Comment by ManickaP** [comment]
Once #82092 is merged, this should become "disabled-test" issue.

**Comment by ManickaP** [comment]
Disabled in https://github.com/dotnet/runtime/pull/82092

**Comment by wfurt** [comment]
It seems like ubuntu-18.04 does not have ARM32 binaries published ... but 20.04 does: https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/libm/libmsquic/
While this is probably fixable in msquic, I'm wondering if we could simply update the test image.
Ubuntu 18.04 is EOS in ~ month https://ubuntu.com/blog/ubuntu-18-04-eol-for-devices

I would think the jitstress really does not care much, does its @BruceForstall ?
We can make fix this and get us on support OS version.

**Comment by BruceForstall** [comment]
> I would think the jitstress really does not care much, does its @BruceForstall ?

jitstress shouldn't care about the specific OS. It uses whatever the specific OS is defined by our YML files defining the test matrix machines.

**Comment by wfurt** [comment]
good to know @BruceForstall. I decided to add the missing MsQuic as it was super easy. Moving to newer Ubuntu will probably needed soon but that probably requires more effort and testing.
