### ISSUE TITLE
SupportedLinuxPlatforms_IsSupportedIsTrue fails on distros without quic

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#82077]
https://github.com/dotnet/runtime/pull/81481 added a test which hard-codes the availability of quic for the runtime CI configuration:

https://github.com/dotnet/runtime/blob/327a244ae9418e994264bb7175377e09b6aebaad/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs#L55-L65

This test fails on our internal CI builds both on Fedora and RHEL as there is no quic there.

The other test that was added in this PR (`SupportedLinuxPlatformsWithMsquic_IsSupportedIsTrue`) looks like it is doing the right thing: check the `IsSupported` based on the availability of the native `libmsquic` library.

Can we remove `SupportedLinuxPlatforms_IsSupportedIsTrue`?

Additionally, `SupportedLinuxPlatformsWithMsquic_IsSupportedIsTrue` can probably be improved by using `NativeLibrary` to try and load `libmsquic`, and also verify that when the native library is not present, `IsSupported` returns `false`.

@ManickaP @CarnaViire @wfurt @karelz wdyt?

cc @omajid 

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

**Comment by ManickaP** [comment]
This is on purpose, we had a big test hole exactly due to optionality of Quic support. 
And for the `find` vs `NativeLibrary.Load`, once again this is on purpose trying to get the library by other means than loading. As we also want to catch cases where libmsquic is present, but some of its dependencies aren't (we had this exact issue), which would not be caught with regular Load.

But we can figure something out that would suppress that particular test in your environment but not in ours. Do you have any suggestion for this?

**Comment by tmds** [comment]
> This is on purpose, we had a big test hole exactly due to optionality of Quic support.

If this test is meant to verify the the runtime CI configurations include quic, it can be skipped when not running on the runtime CI configurations.

Probably there is already a way to check this. It may be:

https://github.com/dotnet/runtime/blob/327a244ae9418e994264bb7175377e09b6aebaad/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L27

@ViktorHofer is this the right property to detect Microsoft CI?

> And for the find vs NativeLibrary.Load, once again this is on purpose trying to get the library by other means than loading. As we also want to catch cases where libmsquic is present, but some of its dependencies aren't (we had this exact issue), which would not be caught with regular Load.

`SupportedLinuxPlatforms_IsSupportedIsTrue` does this check already. You could make it explicit by asserting a `NativeLibrary` load works.

`SupportedLinuxPlatforms_IsSupportedIsTrue` verifies `msquic` is available and working on Microsoft CI.

`SupportedLinuxPlatformsWithMsquic_IsSupportedIsTrue` could just use `NativeLibrary`.

**Comment by wfurt** [comment]
There is also  `[Trait(XunitConstants.Category, XunitConstants.IgnoreForCI)]` - and we can perhaps flip it. 

Preferably, your internal CI probably _should_ include Quic & Https as well @tmds as it is part of the product. 
But I understand if that takes some time.

**Comment by wfurt** [comment]
Arch Linux seems to https://aur.archlinux.org/packages/msquic
I'm talking with MSQuic team about Alpine as they do not have any story for that. 
For RHEL/Fedora/Centos we consume packages they publish and sign on packages.microsoft.com

**Comment by wfurt** [comment]
BTW it would be great IMHO if msquic could become one or OS packages....

**Comment by tmds** [comment]
As .NET maintainers, we're not looking to maintain msquic.
I have no idea where things are heading for quic support in Linux.

**Comment by tmds** [comment]
> IgnoreForCI

I think this is meant for skipping tests that are inappropriate for CI, like tests that require some interaction.

We're looking for a condition that explicitly detects the Microsoft CI that is triggered on this repo.

**Comment by ManickaP** [comment]
I used the "InHelix" as you suggested @tmds. It's already in PR.

**Comment by jakobbotsch** [comment]
This is still failing CI.

**Comment by tmds** [comment]
This issue is about this test failing when it is not running in Microsoft CI.
@ManickaP is tracking the failures that happen in Microsoft CI here: https://github.com/dotnet/runtime/issues/81901.

**Comment by jakobbotsch** [comment]
Ok. I edited that issue with the known error details instead.

**Comment by ilonatommy** [comment]
Failed on https://github.com/dotnet/runtime/pull/105794, [log](https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-105794-merge-cddd5c1f38124965a1/System.Net.Quic.Functional.Tests/3/console.2b15ace8.log?helixlogtype=result)
```
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs(50,0): at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue()
        --- End of stack trace from previous location ---
      Output:
        /usr/lib64/libmsquic.so.2
        /usr/lib64/libmsquic.so.2.4.0
        
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue [FAIL]
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs(68,0): at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        Running on Distro=centos VersionId=9.0
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 3, Errors: 0, Failed: 2, Skipped: 0, Time: 0.466s
```

**Comment by ManickaP** [comment]
This is another symptom of https://github.com/dotnet/runtime/issues/105788. I'll temporarily fix up the docker images.

**Comment by liveans** [comment]
This is fixed by dotnet/dotnet-buildtools-prereqs-docker#1156

Success run: [link](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-106018-merge-e1e97f19d75843f7b6/System.Net.Quic.Functional.Tests/1/console.86634918.log?helixlogtype=result)

```
Console log: 'System.Net.Quic.Functional.Tests' from job e1e97f19-d758-43f7-b647-befe81c13deb (ubuntu.2004.armarch.open) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8 on a00B66U
running $HELIX_CORRELATION_PAYLOAD/scripts/115ae0f16f41495095cc1db7e53ffe46/execute.sh in /datadisks/disk1/work/B0D209EC/w/B9140984/e max 2700 seconds

Output:
[BEGIN EXECUTION]
+ sudo python -m pip install --disable-pip-version-check -r /root/helix/scripts/runtime_python_requirements.txt
Ignoring cffi: markers 'python_version < "3.8"' don't match your environment
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 1)) (2024.7.4)
Requirement already satisfied: ndg-httpsclient==0.5.1 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: psutil==5.9.3 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 3)) (5.9.3)
Requirement already satisfied: pyasn1==0.4.5 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 4)) (0.4.5)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: cryptography>=39.0.1 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 7)) (43.0.0)
Requirement already satisfied: pyopenssl>=23.0.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 8)) (24.2.1)
Requirement already satisfied: asn1crypto==0.24.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 10)) (0.24.0)
Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 11)) (2.8)
Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 13)) (1.16.0)
Requirement already satisfied: pycparser==2.19 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 14)) (2.19)
Requirement already satisfied: docker==3.7.2 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 16)) (3.7.2)
Requirement already satisfied: docker-pycreds==0.4.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 17)) (0.4.0)
Requirement already satisfied: websocket-client==0.56.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 18)) (0.56.0)
Requirement already satisfied: requests<=2.28.1,>=2.21.0 in /usr/lib/python3/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 20)) (2.22.0)
Requirement already satisfied: urllib3<1.27,>=1.24.3 in /usr/lib/python3/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 21)) (1.25.8)
Requirement already satisfied: azure-storage-blob==12.5.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 23)) (12.5.0)
Requirement already satisfied: azure-core==1.7.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 24)) (1.7.0)
Requirement already satisfied: azure-devops==5.0.0b9 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 25)) (5.0.0b9)
Requirement already satisfied: msrest==0.6.10 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 26)) (0.6.10)
Requirement already satisfied: isodate==0.6.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 27)) (0.6.0)
Requirement already satisfied: requests-oauthlib==1.2.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 28)) (1.2.0)
Requirement already satisfied: oauthlib==3.1.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 29)) (3.1.0)
+ export PYTHONPATH=/root/helix/scripts:
+ cd /root/helix/work/workitem/e
+ mkdir -p /home/helixbot/dotnetbuild/dumps/
+ /root/helix/work/correlation/scripts/115ae0f16f41495095cc1db7e53ffe46/execute.sh
+ export __TestArchitecture=arm64
+ ./RunTests.sh --runtime-path /root/helix/work/correlation
========================= Begin custom configuration settings ==============================
export __IsXUnitLogCheckerSupported=1
export XUNIT_HIDE_PASSING_OUTPUT_DIAGNOSTICS=1
========================== End custom configuration settings ===============================
----- start Tue 06 Aug 2024 03:24:09 PM UTC =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 141 of 152 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on [2 threads], stop on fail = off)
MsQuic supported and using 'libmsquic.so 2.4.1.514926 (1cb9a4c4fe7e09425f3214ab49e61a74767a1014)'.
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
MsQuic Counters:
    CONN_CREATED 1612
    CONN_HANDSHAKE_FAIL 27
    CONN_APP_REJECT 8
    CONN_LOAD_REJECT 0

Unobserved exceptions of 0 different types: 

  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 431, Errors: 0, Failed: 0, Skipped: 1, Time: 131.193s
/root/helix/work/workitem/e
----- end Tue 06 Aug 2024 03:26:24 PM UTC ----- exit code 0 ----------------------------------------------------------
exit code 0 means Exited Successfully
dmesg: read kernel buffer failed: Operation not permitted
----- start =============== XUnitLogChecker Output =====================================================
No dumps found in /home/helixbot/dotnetbuild/dumps.
----- end =============== XUnitLogChecker Output - exit code 0 ===========================
+ export _commandExitCode=0
+ python /root/helix/work/correlation/reporter/run.py https://dev.azure.com/dnceng-public/ public 19563498 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJjNzczZjJjMi01MTIwLTQyMDctYWZlMi1hZmFmMzVhOGJjMGEiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiJiMzY0MWVkMC01MjViLTQyZTktOWE4NS05MDc5ZTE1ZjA4ODgiLCJzaWQiOiI5OWE1NGNmYy0yYjdjLTQ2OGMtYTVlYi04M2E1Y2U5NWExMDEiLCJCdWlsZElkIjoiY2JiMTgyNjEtYzQ4Zi00YWJiLTg2NTEtOGNkY2I1NDc0NjQ5Ozc2NzMxNiIsIkRlZklkIjoiMTI5Iiwiam9icmVmIjoiZjhmOWU1ZGItOWYyOC00Mjk3LWIwMzktZjAzN2RkMTc4NDU1OjBkMjg4MTFmLTc1ZWMtNWViYS0xM2ZkLWRlM2NhYmZmOGQzNiIsInBwaWQiOiJ2c3RmczovLy9CdWlsZC9CdWlsZC83NjczMTYiLCJvcmNoaWQiOiJmOGY5ZTVkYi05ZjI4LTQyOTctYjAzOS1mMDM3ZGQxNzg0NTUuYnVpbGQubGlicmFyaWVzX3Rlc3RfcnVuX2NoZWNrZWRfY29yZWNscl9saW51eF9hcm02NF9kZWJ1Zy5fX2RlZmF1bHQiLCJyZXBvSWRzIjoiIiwiaXNzIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbSIsImF1ZCI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb218dnNvOjZmY2M5MmU1LTczYTctNGY4OC04ZDEzLWQ5MDQ1YjQ1ZmIyNyIsIm5iZiI6MTcyMjk1NTkzNywiZXhwIjoxNzIyOTY2MTM2fQ.lboQm7rNeMl4pziA9QSb3J9YuccitKjfVmb_ZfOwr7P8zeMKB3x0iqGrZgu3W5n5nA3wTTAd23USSQscMpH2nShPr69bR98pS0pF6D2Tc-q4fTwOR_QrtiPXNCxDdgC7coUHK400Nqtrdi31NIrvM1GLe6IE1-y5Jh9HWhbr2eq5c1lnVJFZSzQCHdUvco79P59u4hQr7etvUQ5Ql2Ho6uooET7z8uj1lJW4-PHmcKORqqUCtBK-A9Xnzz5oztkL_ONnaDsfFvD6uZ5adraI7UM--HwfmQmJNPUVCCljaHCKrBKfsexjeco-pEJiFii2q2IqDRZScnuI6EooBnTKaA
2024-08-06T15:26:25.290Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2024-08-06T15:26:25.291Z	INFO   	run.py	__init__(42)	read_results	Searching '/root/helix/work/workitem/e' for test results files
2024-08-06T15:26:25.291Z	INFO   	run.py	__init__(48)	read_results	Found results file /root/helix/work/workitem/e/testResults.xml with format xunit
2024-08-06T15:26:25.296Z	INFO   	run.py	__init__(42)	read_results	Searching '/root/helix/work/workitem/uploads' for test results files
2024-08-06T15:26:25.296Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 431 test reports to '/root/helix/work/workitem/e/__test_report.json'
2024-08-06T15:26:25.297Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 107658 bytes
+ python /root/helix/work/correlation/gen-debug-dump-docs.py -buildid 767316 -workitem System.Net.Quic.Functional.Tests -jobid e1e97f19-d758-43f7-b647-befe81c13deb -outdir /root/helix/work/workitem/uploads -templatedir /root/helix/work/correlation -dumpdir /home/helixbot/dotnetbuild/dumps -productver 9.0.0
gen-debug-dump-docs.py: Did not find dumps, skipping dump docs generation.
+ exit 0
+ export _commandExitCode=0
+ chmod -R 777 /home/helixbot/dotnetbuild/dumps
+ exit 0

[END EXECUTION]
Exit Code:0
```
