### ISSUE TITLE
Test failure: crossgen2 crash building HardwareIntrinsics tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82114]
Two occurrences in `runtime-coreclr r2r-extra` pipeline:

R2R-CG2 osx arm64 Checked jitstressregs3 @ OSX.1200.ARM64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=170990&view=ms.vss-test-web.build-test-results-tab&runId=3424690&paneView=debug&resultId=116622

```
Running CrossGen2:  dotnet /tmp/helix/working/AEB70978/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/AEB70978/w/B10F0979/e/JIT/HardwareIntrinsics/HardwareIntrinsics_r/X86_Sse41.X64_r.dll.rsp  
[createdump] Gathering state for process 4403 
[createdump] Crashing thread 009bc075 signal 0000000b
[createdump] Writing crash report to file /cores/coredump.4403.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.4403.dmp
[createdump] Written 489718136 bytes (29890 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 3423ms
JIT/HardwareIntrinsics/HardwareIntrinsics_r/HardwareIntrinsics_r.sh: line 235:  4403 Segmentation fault: 11  (core dumped) $__Command
Running R2RDump:  dotnet /tmp/helix/working/AEB70978/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/AEB70978/w/B10F0979/e/JIT/HardwareIntrinsics/HardwareIntrinsics_r/X86_Sse41.X64_r.dll --out /private/tmp/helix/working/AEB70978/w/B10F0979/e/JIT/HardwareIntrinsics/HardwareIntrinsics_r/X86_Sse41.X64_r.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 470
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 444
```

R2R-CG2 osx arm64 Checked forcerelocs @ OSX.1200.ARM64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=170990&view=ms.vss-test-web.build-test-results-tab&runId=3424695&paneView=debug&resultId=116641

```
Running CrossGen2:  dotnet /tmp/helix/working/BB3C0A3A/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/BB3C0A3A/w/A1B90919/e/JIT/HardwareIntrinsics/HardwareIntrinsics_ro/X86_Aes_ro.dll.rsp  
[createdump] Gathering state for process 28092 
[createdump] Crashing thread 0071cd52 signal 0000000b
[createdump] Writing crash report to file /cores/coredump.28092.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.28092.dmp
[createdump] Written 496402808 bytes (30298 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 3660ms
JIT/HardwareIntrinsics/HardwareIntrinsics_ro/HardwareIntrinsics_ro.sh: line 235: 28092 Segmentation fault: 11  (core dumped) $__Command
Running R2RDump:  dotnet /tmp/helix/working/BB3C0A3A/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/BB3C0A3A/w/A1B90919/e/JIT/HardwareIntrinsics/HardwareIntrinsics_ro/X86_Aes_ro.dll --out /private/tmp/helix/working/BB3C0A3A/w/A1B90919/e/JIT/HardwareIntrinsics/HardwareIntrinsics_ro/X86_Aes_ro.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 470
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 444
02:31:13
Crossgen2 failed with exitcode: 139
```

@dotnet/crossgen-contrib

**Comment by davidwrighton** [comment]
I've looked at the json crash reports, and it looks to me that something may be going wrong in tail-call. Both of these failures are occurring at the same point in code attempting to access objects passed as parameters, and it appears that one of them moved. I think what is happening is `System.Reflection.CustomAttribute.FilterCustomAttributeRecord` is calling `System.Reflection.CustomAttribute.MatchesTypeFilter` which is tail-calling `System.Type.IsAssignableFrom` (and landing in `System.RuntimeType.IsAssignableFrom`, which is then tail-calling `System.RuntimeTypeHandle.CanCastTo`. Somewhere in this chain is appears that there is a GC hole.

However, I don't have access to the right hardware to look into this issue. @jakobbotsch could you please take a look and examine the GC reporting around tail-calls to make sure there isn't a bug there?

**Comment by trylek** [comment]
Closing as no repro, critical ARM fixes have been merged since.
