### ISSUE TITLE
Test failure Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82127]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=169012&view=ms.vss-test-web.build-test-results-tab&runId=3405426&paneView=debug

Looks like it fails in all `jitobjectstackallocation` scenarios.

coreclr linux arm64 Checked jitobjectstackallocation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_JitObjectStackAllocation=1
```

```
    Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/Loader.classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false reabstraction.dll ''
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 2/13/2023 12:01:11 AM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Loader_classloader._DefaultInterfaceMethods_reabstraction_reabstraction_reabstraction_._DefaultInterfaceMethods_reabstraction_reabstraction_reabstraction_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/Loader.classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false reabstraction.dll ''
        Expected: 100
        Actual: 255
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 2/13/2023 12:01:11 AM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh
  Finished:    Loader.classloader.XUnitWrapper
```

@AndyAyersMS

**Comment by AndyAyersMS** [comment]
I'll take this one.

**Comment by AndyAyersMS** [comment]
`CORINFO_HELP_VIRTUAL_FUNC_PTR` can now throw exceptions other than null pointer deref, so this bit of morph is now wrong:

https://github.com/dotnet/runtime/blob/24107379cd4fbfe236f0a1cf92dbd6c4ad944fec/src/coreclr/jit/morph.cpp#L7805-L7822

Not sure when this behavior changed.
