### ISSUE TITLE
Crash on startup on Android in Release when referencing a class with non ascii characters from a class library

### ISSUE THREAD

**Issue by CodeAuChocolat** [dotnet/runtime#82187]
### Description

I have a class _Tür_ in a .NET 7 class library and I reference this class in a MAUI-App.  When compiled in Release with AOT enabled, on an Android device, the app crashes immediatly.
Works on Windows.
Works on Android Emulator

I am using Visual Studio 17.4.5.

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui                       7.0.59/7.0.100        SDK 7.0.200

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Create a .NET 7 class library
3. Add a Reference to the class libarary to the MAUI app
4. Add a class Tür to the class library
5. Add a field to App.xaml.cs using the class Tür
6. Run the app on an android device in Release

### Link to public reproduction project repository

https://github.com/CodeAuChocolat/MauiUmlautCrash

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7, Android 12

### Did you find any workaround?

Rename class or disable AOT

### Relevant log output

```shell
Time	Device Name	Type	PID	Tag	Message
02-15 10:04:07.288	CipherLab RS31	Error	18286	AndroidRuntime	android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type of field 'MauiUmlautCrash.App:_tor' (0) due to: Could not resolve type with token 01000058 from typeref (expected class 'UmlautLib.Tür' in assembly 'UmlautLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:UmlautLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:UmlautLib.Tür member:(null)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
   at Microsoft.Maui.MauiApplication.OnCreate()
   at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
 from settings cache , name = dropbox:data_app_crash , value = null
 from settings cache , name = send_action_app_error , value = 1
 from settings cache , name = logcat_for_data_app_crash , value = null
  Force finishing activity com.companyname.mauiumlautcrash/crc642a249426a1f98bd8.MainActivity
 from settings cache , name = dropbox:data_app_crash , value = null
 from settings cache , name = dropbox_age_seconds , value = null
 from settings cache , name = dropbox_max_files , value = null
 from settings cache , name = dropbox_quota_percent , value = null
 from settings cache , name = dropbox_reserve_percent , value = null
 from settings cache , name = dropbox_quota_kb , value = null
```

**Comment by steveharter** [comment]
Based on above this looks like an AOT issue with non-ascii characters used in a type name.

**Comment by lambdageek** [comment]
Is the trimmer running when we build for Android in Release mode for devices? Maybe it removed `Tür` but not the field reference?

**Comment by lambdageek** [comment]
I can repro with a Release build running on an arm64 emulator on an arm64 mac.

**Comment by lambdageek** [comment]
I don't think it's a trimmer issue.  afaict the trimmer didn't change the assembly.

Usually these class setup errors come from the class loader, but I really don't get why the class loader would care about the architecture.

We do cache some class info in the AOT data, which could affect startup on AOT.  But I didn't think the backend for that was arch-specific...

**Comment by lambdageek** [comment]
Possible dupe of #78638

**Comment by lambdageek** [comment]
One place where the AOT compiler and class names interact is in `mono_aot_get_class_from_name` which is installed with `mono_install_get_class_from_name` and then used in `mono_class_from_name_checked_aux`.  When an AOT image is present, it stores a hash table mapping every namespace.name to its type def table token.  It's possible that the input to the hash function is different when the table is constructed (in `emit_class_name_table`) vs when it's used at runtime.  

But:

1. I don't see any such difference that would manifest for names with utf-8 multi-byte characters.  (Although a class named `,` or `+` or something will expose a bug: aot-compiler calls `mono_type_get_name_full` which calls `mono_identifier_escape_type_name_chars`, but aot-runtime doesn't do the same escaping)
2. Why would it only show up on arm64 android and not on x64 or in any ios testing??

**Comment by lambdageek** [comment]
Oh god... is it some signed vs unsigned `char` nonsense.
This is what the AOT compiler sees:
```
'MauiUmlautCrash.MeineTüre'=00000038
```
This is what the android device is trying to look up
```
03-10 12:33:13.637  6694  6694 W mauiumlautcrash: aleksey - AOT cache 'MauiUmlautCrash.MeineTüre'=0000002b not found
```
guint
mono_metadata_str_hash (gconstpointer v1)
{
	/* Same as g_str_hash () in glib */
	char *p = (char *) v1;
	guint hash = *p;

	while (*p++) {
		if (*p)
			hash = (hash << 5) - hash + *p;
	}

	return hash;
}
```

UTF-8 continuation bytes have the top bit set, so if `char` is signed on one device and unsigned on another, the hash computation will be different - [godbolt link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMJ0hwBk8DTAA5dwAjTGIQAFYAZlIAB1QFQlsGZzcPL3jE5IE/AOCWMIiYi0wrGwEhAiZiAjT3TylS8pSqmoI8oNDwqNiFatr6jKb%2B9s6Cot6ASgtUV2Jkdg4AUgAmaP9kNywAamXox37if2AAOgR97GWNAEFru/XN7cw9g/78VHPL%2B7WNhi3XLt9ocCOhaHgQl9oldbr8noCXsD3v4CFCYXdbq4UdFVsYCPcksAAuhjAgmAoEDsIGgGP0dgA3VB4dA7ABU9K4Ux%2BAHYAEI/DQATkJxJ2yDJxDZcVeABEqSLMCzxTU2VMGVx9vzYUKsYIcXidmSKbKpZqBRjBQB3BB0F4QVlxNb81a8tXLPkCwXXQV4KhUh1c7VeoXeo2U/ZyiBh16OYE7SJqgC0hvJ4ZdpuiWot7pl5u9xEwBHmDBTFLN2ru3NzFd1BH1%2BMxtLwRMVpNTVJpdMZzLZHMDlaz3tcTZbSolUpNEGHCrHKtZao55YttfrpfD0TlDqXnuttv9jpdTrdHqD3t9%2B/73qvQujEapt4OcYTO2Tt/TW8znpzeaFBaLxBLMNt1hKsfxubt0HuNAWDiGpMDbClMAUDsBDpZVJVZBRLxPG4djwnYV1xAhDS4E0ZwQhAICwpd8II7EiMNVYTWnZtiQoqiuU/CtaLiY5BCoCA1lWMAVlWSIFBEk1lkiXkNFUNZIg0AAOVRSB2OSFOU%2BTIlzSJHAYIS1IUNSEC4EzVk4rMeL4ggBKEsMkJ2OC9jEhRpP0wySNlO8ECY/YADEXNWBRWEwISdhAIKZQASX8/zsAAJWwQIABUhMsnlqwxG4UXuFgmH8CAIOwqz8Og2CCwoxzBNWVYAFkmCxOQWAMVw6mIVNTjqzB/EwFL5jC2qMtuWjyrgqrkJq%2BrGrwZrWvazrut6tLHGiZZeUcAt0po/C/2LdTtyrDgZloThIl4TwOC0UhUE4RwdgUOYFkRdYeFIAhNGOmYAGsQGiaJTn%2BoHgZB/ROEkC7PpuzheAUEANHez6ZjgWAkHK20yAoalUBgjGUGALhatILB6TwRYADU8EwS0AHk4kYTg3poWgCHCOGIBCKGQn8GoAE9Gd4bnmGIXmaZCbRMGsAXSGgthBBphhaH5q7eCwfKjHEFXibwAtrDwekkKhzBVEltqljelEyih8EQg6kXnCwKGCGOFgBZmKgDGABRKepumGe4Xh%2BEEEQxHYJog/kJQ1Ch3QzIMIwQFMYxzBtuHIBmVA4gqWkYeaSXs/sBgnBcBo9F8XqJh6MyEiSbOhkaLJa5ScZugiMzLHz1oBjqEvhjzvXKm7lvCirixu/rvRRlqYfJk5WZ5kWCQTrOyGtdujgdlUJSADZE23yQdmAZBkB2QnTiYiBcEIEgXOiTleA%2BlWph%2Bv6AZB9%2BgbBjgIdIS7rvX2G8NEZP1ICjRAIBjamyIJjSgNQvbKEMGUIQCBUCWkum9dGBhs4IICLQZBqC/68EwT0ZABMibEOIIEUKucKE0zavgtBRsTbIBuMQL2udIHICqPgS6gdZAh3EOHWQigVDqC1rHfQhgTBmH0BCNOEAM5ZxSHDDgsMnqL3bqCfwOCkEoMYQHd6BZ2AI0tB1OIbsv7nV/lDde2BmFtRvlvXe%2B9D7H1Pqsc%2BVJHBqSvtA2%2B99gFaGfqQX6/1AYf3fl/H%2BhDoaqIsEAx%2BQTl4cFWKvf%2BudElfVIAbYgSQ7CSCAA%3D)
