### ISSUE TITLE
AppHost.Bundle.Tests Test host process crashed on Linux x64 Release CoreCLR Installer Build and Test

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#82202]
Seems like a flakey problem

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=173148&view=logs&j=c5f2201a-1517-53df-cad8-ae304147cc38&t=a15e3034-cc18-5a91-b9dd-0aaebf757d0c
```
VSTest : error : Tests failed: /__w/1/s/artifacts/TestResults/Release/AppHost.Bundle.Tests_net8.0_x64.html [net8.0|x64] [/__w/1/s/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/AppHost.Bundle.Tests.csproj]
##[error]VSTest(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Tests failed: /__w/1/s/artifacts/TestResults/Release/AppHost.Bundle.Tests_net8.0_x64.html [net8.0|x64]
```

```
=== COMMAND LINE ===
/__w/1/s/.dotnet/dotnet test /__w/1/s/artifacts/bin/AppHost.Bundle.Tests/Release/net8.0/AppHost.Bundle.Tests.dll --logger:console;verbosity=normal --logger:trx;LogFileName=AppHost.Bundle.Tests_net8.0_x64.trx --logger:html;LogFileName=AppHost.Bundle.Tests_net8.0_x64.html --ResultsDirectory:/__w/1/s/artifacts/TestResults/Release --Framework:.NETCoreApp,Version=v8.0 --filter category!=failing -v detailed --blame-crash-dump-type full --blame-hang-timeout 5m --blame-hang-dump-type full
Microsoft (R) Test Execution Command Line Tool Version 17.6.0-preview-20230107-01 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
/__w/1/s/artifacts/bin/AppHost.Bundle.Tests/Release/net8.0/AppHost.Bundle.Tests.dll
Blame: Attaching crash dump utility to process dotnet (8196).
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 8.0.0-alpha.1.23058.2)
[xUnit.net 00:00:00.98]   Discovering: AppHost.Bundle.Tests
[xUnit.net 00:00:01.16]   Discovered:  AppHost.Bundle.Tests
[xUnit.net 00:00:01.17]   Starting:    AppHost.Bundle.Tests
[EXEC       >] [....] [00:00:00.000] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/d41lnq3d.jnq/StandaloneApp/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci
[EXEC       -] [....] [00:00:00.004] Waiting for process 8268 to exit...
[EXEC       >] [....] [00:00:01.023] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/romg1hvv.rtp/SingleFileApiTests/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci /p:AddFile=/__w/1/s/artifacts/bin/linux-x64.Release/corehost_test/libmockcoreclr.so
[EXEC       >] [....] [00:00:01.024] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/35kzlikc.n1l/SingleFileApiTests/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci /p:AddFile=/__w/1/s/artifacts/bin/linux-x64.Release/corehost_test/libmockcoreclr.so
[EXEC       -] [....] [00:00:01.040] Waiting for process 8278 to exit...
[EXEC       -] [....] [00:00:01.043] Waiting for process 8279 to exit...
[EXEC       >] [....] [00:00:02.093] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 --self-contained false -o /__w/1/s/artifacts/tests/Release/ahb/p5isdjmu.5bq/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci
[EXEC       -] [....] [00:00:02.102] Waiting for process 8333 to exit...
[EXEC       <] [ OK ] [00:00:43.216] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 --self-contained false -o /__w/1/s/artifacts/tests/Release/ahb/p5isdjmu.5bq/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci exited with 0
[EXEC       >] [....] [00:00:47.327] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/pkz3m0pl.r12/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci
[EXEC       -] [....] [00:00:47.351] Waiting for process 8924 to exit...
[EXEC       <] [ OK ] [00:02:17.902] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/d41lnq3d.jnq/StandaloneApp/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci exited with 0
[EXEC       <] [ OK ] [00:02:52.019] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/35kzlikc.n1l/SingleFileApiTests/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci /p:AddFile=/__w/1/s/artifacts/bin/linux-x64.Release/corehost_test/libmockcoreclr.so exited with 0
[EXEC       <] [ OK ] [00:02:52.031] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/romg1hvv.rtp/SingleFileApiTests/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci /p:AddFile=/__w/1/s/artifacts/bin/linux-x64.Release/corehost_test/libmockcoreclr.so exited with 0
[EXEC       >] [....] [00:02:57.129] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 --self-contained true -o /__w/1/s/artifacts/tests/Release/ahb/0fbbs2yo.pc0/SingleFileApiTests/publish /p:PublishSingleFile=true /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci /p:AddFile=/__w/1/s/artifacts/bin/linux-x64.Release/corehost_test/libmockcoreclr.so /p:SingleFileHostSourcePath=/__w/1/s/artifacts/bin/linux-x64.Release/corehost/singlefilehost
[EXEC       >] [....] [00:02:57.131] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 --self-contained true -o /__w/1/s/artifacts/tests/Release/ahb/avdbxxig.pi1/SingleFileApiTests/publish /p:PublishSingleFile=true /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci /p:AddFile=/__w/1/s/artifacts/bin/linux-x64.Release/corehost_test/libmockcoreclr.so /p:SingleFileHostSourcePath=/__w/1/s/artifacts/bin/linux-x64.Release/corehost/singlefilehost
[EXEC       -] [....] [00:02:57.134] Waiting for process 9265 to exit...
[EXEC       -] [....] [00:02:57.134] Waiting for process 9266 to exit...
[EXEC       <] [ OK ] [00:03:08.740] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/pkz3m0pl.r12/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci exited with 0
[EXEC       >] [....] [00:03:13.220] /__w/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --runtime linux-x64 --framework net8.0 /p:NetCoreAppCurrent=net8.0 -o /__w/1/s/artifacts/tests/Release/ahb/tlammkyh.2zj/AppWithSubDirs/publish /p:TestTargetRid=linux-x64 /p:MNAVersion=8.0.0-ci
[EXEC       -] [....] [00:03:13.231] Waiting for process 9333 to exit...
[createdump] Gathering state for process 8196 dotnet
[createdump] Writing full dump to file /__w/_temp/d601bafd-dd57-4ead-a563-1e7fcec7e6b4/dotnet_8196_20230215T185154_hangdump.dmp
[createdump] Written 148709376 bytes (36306 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 4763ms
The active test run was aborted. Reason: Test host process crashed
Data collector 'Blame' message: The specified inactivity time of 5 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
Results File: /__w/1/s/artifacts/TestResults/Release/AppHost.Bundle.Tests_net8.0_x64.trx
Html test results file : /__w/1/s/artifacts/TestResults/Release/AppHost.Bundle.Tests_net8.0_x64.html

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.


Attachments:
  /__w/1/s/artifacts/TestResults/Release/01f120a2-4cab-4530-8451-7be45e6d2efb/dotnet_8196_20230215T185154_hangdump.dmp
  /__w/1/s/artifacts/TestResults/Release/01f120a2-4cab-4530-8451-7be45e6d2efb/dotnet_9266_20230215T185153_hangdump.dmp

```

**Comment by elinor-fung** [comment]
This actually hit our test timeout, so the test run was stopped (which seems to get reported as a crash). From the logs, the test setup was actually just taking a really long time. For whatever reason, the publish prep that we do for single-file tests was taking about 3 minutes for each project (looking at passing runs, it was about 20s). We could increase the timeout, but I don't think this is a common occurrence. Unless we see this much more, I'm inclined to just stick with our broader effort of making the testing here better:
- https://github.com/dotnet/runtime/pull/81187
- https://github.com/dotnet/runtime/issues/80369

**Comment by agocke** [comment]
Agreed, closing as dup of https://github.com/dotnet/runtime/issues/80369
