### ISSUE TITLE
Test failure tracing/eventpipe/bigevent/bigevent/bigevent.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82251]
Linux arm32 GCStress=3

https://dev.azure.com/dnceng-public/public/_build/results?buildId=174088&view=ms.vss-test-web.build-test-results-tab&runId=3460314&resultId=111326&paneView=debug

It timed out after an hour:

```
  Starting:    tracing.eventpipe.XUnitWrapper (parallel test collections = on, max threads = 2)
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:02:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:04:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:06:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:08:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:10:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:12:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:14:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:16:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:18:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:20:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:22:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:24:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:26:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:28:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:30:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:32:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:34:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:36:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:38:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:40:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:42:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:44:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:46:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:48:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:50:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:52:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:54:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:56:23
   tracing.eventpipe.XUnitWrapper: [Long Running Test] 'tracing/eventpipe/bigevent/bigevent/bigevent.sh', Elapsed: 00:58:23
Attempting to collect crash dump: /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp
Invoking: sudo /root/helix/work/correlation/createdump --crashreport --name "/home/helixbot/dotnetbuild/dumps/crashdump_323.dmp" 323 --withheap
createdump stdout:
[createdump] Gathering state for process 323 corerun
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp
[createdump] Written 207892480 bytes (50755 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 365ms

createdump stderr:

Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json
stdout: -rw------- 1 root root 80672 Feb 16 09:31 /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json

=========================================
Error reading /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json: System.UnauthorizedAccessException: Access to the path '/home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, StreamWriter outputWriter)
Collected crash dump: /home/helixbot/dotnetbuild/dumps/crashdump_323.dmp
    tracing/eventpipe/bigevent/bigevent/bigevent.sh [FAIL]
      
      cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/16/2023 8:31:59 AM, end: 2/16/2023 9:31:59 AM)
      
      Return code:      -100
      Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/bigevent/bigevent/bigevent.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false bigevent.dll ''
        0.0s: ==TEST STARTING==
       16.0s: Started sending sentinel events...
       16.1s: Connecting to EventPipe...
       29.3s: Creating EventPipeEventSource...
       29.7s: EventPipeEventSource created
       30.3s: Dynamic.All callback registered
       30.3s: Running optional trace validator
       30.4s: Finished running optional trace validator
       30.4s: Starting stream processing...
       35.8s: Saw sentinel event
       35.8s: Stopped sending sentinel events
       36.1s: Starting event generating action...
       37.1s: Stopping event generating action
       37.2s: Sending StopTracing command...
       41.7s: Saw new provider 'BigEventSource'
       41.8s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
       77.3s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
      407.0s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
      
      cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/16/2023 8:31:59 AM, end: 2/16/2023 9:31:59 AM)
      Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json'
      Test Harness Exitcode is : -100
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at tracing_eventpipe._bigevent_bigevent_bigevent_._bigevent_bigevent_bigevent_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/16/2023 8:31:59 AM, end: 2/16/2023 9:31:59 AM)
        
        Return code:      -100
        Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/bigevent/bigevent/bigevent.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false bigevent.dll ''
          0.0s: ==TEST STARTING==
         16.0s: Started sending sentinel events...
         16.1s: Connecting to EventPipe...
         29.3s: Creating EventPipeEventSource...
         29.7s: EventPipeEventSource created
         30.3s: Dynamic.All callback registered
         30.3s: Running optional trace validator
         30.4s: Finished running optional trace validator
         30.4s: Starting stream processing...
         35.8s: Saw sentinel event
         35.8s: Stopped sending sentinel events
         36.1s: Starting event generating action...
         37.1s: Stopping event generating action
         37.2s: Sending StopTracing command...
         41.7s: Saw new provider 'BigEventSource'
         41.8s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
         77.3s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
        407.0s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
        
        cmdLine:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh Timed Out (timeout in milliseconds: 3600000 from variable __TestTimeout, start: 2/16/2023 8:31:59 AM, end: 2/16/2023 9:31:59 AM)
        Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/crashdump_323.dmp.crashreport.json'
        Test Harness Exitcode is : -100
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh
```

@davmason

**Comment by BruceForstall** [comment]
Failed again: https://dev.azure.com/dnceng-public/public/_build/results?buildId=176742&view=ms.vss-test-web.build-test-results-tab&runId=3494096&resultId=111621&paneView=debug
