### ISSUE TITLE
Test failure in System.Net.Http.Json.Functional.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82266]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=174125&view=ms.vss-test-web.build-test-results-tab&runId=3460501&resultId=223424&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

This appeared in pipeline `runtime-coreclr libraries-jitstress`, configuration `net8.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open`, though I don't think it's related to JitStress as I wasn't able to reproduce the problem locally with or without stress.

```
  Starting:    System.Net.Http.Json.Functional.Tests (parallel test collections = on, max threads = 4)
Process terminated. Assertion failed.
   at System.Threading.ThreadPoolBoundHandle.BindHandleCore(SafeHandle handle) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.Windows.cs:line 14
   at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.cs:line 81
   at System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(Boolean trySkipCompletionPortOnSuccess) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.Windows.cs:line 57
   at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandleSlow() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs:line 437
   at System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept(Socket socket, SafeSocketHandle handle, SafeSocketHandle acceptHandle, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs:line 261
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2625
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(Socket socket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1005
   at System.Net.Sockets.Socket.AcceptAsync(Socket acceptSocket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 70
   at System.Net.Sockets.Socket.AcceptAsync() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 32
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 136
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 159
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
   at System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.<>c__DisplayClass13_2.<<GetFromJsonAsync_EnforcesTimeout>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http.Json/tests/FunctionalTests/HttpClientJsonExtensionsTests.cs:line 430
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.<>c__DisplayClass13_2.<GetFromJsonAsync_EnforcesTimeout>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 503
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2391
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2353
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2287
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2278
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
-
```

**Comment by wfurt** [comment]
the relevant code does not seems to change for very long time. It seems like the thread pool would assert if the handle is closed before `BindHandleCore` is executed.

**Comment by stephentoub** [comment]
It's hitting this assert:
https://github.com/dotnet/runtime/blob/e625cf8ee5abea97faab188bf2f92ee390aad1f2/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.Windows.cs#L14

**Comment by MihaZupan** [comment]
The test that hit this is rather new: [`GetFromJsonAsync_EnforcesTimeout`](https://github.com/dotnet/runtime/blob/28f958de34be053bdebfca0b804cb6ac9232f4cc/src/libraries/System.Net.Http.Json/tests/FunctionalTests/HttpClientJsonExtensionsTests.cs#L405)
It's a bit different from other tests in that the socket may be getting disposed while a different thread is calling `Socket.AcceptAsync` at the same time.

**Comment by mangod9** [comment]
Closing since this has only failed a few times (that too on x86). Will reopen if this repros.
