### ISSUE TITLE
llvm-symbolizer invocation failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#82544]
Seen in https://github.com/dotnet/runtime/issues/82414

And here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=181701&view=ms.vss-test-web.build-test-results-tab&runId=3542266&resultId=107033&paneView=debug

```
      Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 2/23/2023 8:33:19 AM
      Processing /home/helixbot/dotnetbuild/dumps/coredump.12662.dmp.crashreport.json
      Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.12662.dmp.crashreport.json'
      Invoking llvm-symbolizer --pretty-print
      Errors while running llvm-symbolizer --pretty-print
      System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/root/helix/work/workitem/e'. No such file or directory
         at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, StreamWriter outputWriter)
      Test Harness Exitcode is : 1
```

Related: https://github.com/dotnet/runtime/issues/77918

**Comment by kunalspathak** [comment]
@BruceForstall - I haven't see this happening lately. I will close this. Feel free to reopen if you see any instances of it.
