### ISSUE TITLE
Bogus `OperationCanceledException` raised by `StreamPipeReader` read methods

### ISSUE THREAD

**Issue by bentoi** [dotnet/runtime#82594]
### Description

The `StreamPipeReader.ReadAsync` and `ReadAtLeastAsync` method can raise an `OperationCanceledException` with a token which is not the given cancellation token.

Here:
- https://github.com/dotnet/runtime/blob/afacfaf19176b7496624caf5416a5baa96c39d59/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeReader.cs#L276
- https://github.com/dotnet/runtime/blob/afacfaf19176b7496624caf5416a5baa96c39d59/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeReader.cs#L276

These two throw clauses should be replaced with `cancellationToken.ThrowIfCancellationRequested();`

### Reproduction Steps

I don't have reproduction steps but the bug is obvious.

### Expected behavior

The operation canceled exception should use the provided cancellation token.

### Actual behavior

It's not.

### Configuration

DotNet 8.0.100-preview.1.23115.2

**Comment by bentoi** [comment]
I don't know about the second expression but I would think that if `tokenSource.IsCancellationRequested && !cancellationToken.IsCancellationRequested` is false, the else block should raise `OperationCanceledException` with the provided token.

Unfortunately, I haven't been able to reproduce it with a test case :(. I'm using the stream pipe reader to wrap a `QuicStream`.

To figure out the issue (it took me a while ;)) and after ruling out a `QuicStream` issue, I ended up importing the `StreamPipeReader` source into my project because I wouldn't see a complete stack trace otherwise. So in the stack trace  bellow, `Foo.StreamPipeReader` is really the `System.IO.Pipelines.StreamPipeReader` source code from the 8.0 preview. 

Here, the `CancellationToken` property of the `OperationCanceledException` raised `streamPipeReader.ReadAsync()` is not the cancellation token provided to the `ReadAsync` call.

```
System.OperationCanceledException: The operation was canceled.
   at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
   at System.Net.Quic.ResettableValueTaskSource.<>c.<TryGetValueTask>b__12_0(Object obj, CancellationToken cancellationToken)
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Foo.StreamPipeReader.Cancel() in /home/vagrant/workspace/Foo-csharp/src/Foo.Quic/Transports/Internal/StreamPipeReader.cs:line 833
   at Foo.StreamPipeReader.<>c.<ReadAsync>b__38_1(Object state) in /home/vagrant/workspace/Foo-csharp/src/Foo.Quic/Transports/Internal/StreamPipeReader.cs:line 431
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Foo.Internal.FooProtocolConnection.<DisposeAsync>g__PerformDisposeAsync|36_0() in /home/vagrant/workspace/Foo-csharp/src/Foo/Internal/FooProtocolConnection.cs:line 251
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---
   at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Foo.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken) in /home/vagrant/workspace/Foo-csharp/src/Foo.Quic/Transports/Internal/StreamPipeReader.cs:line 450
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Foo.QuicPipeReader.ReadAsync(CancellationToken cancellationToken) in /home/vagrant/workspace/Foo-csharp/src/Foo.Quic/Transports/Internal/QuicPipeReader.cs:line 48
```

Hopefully it helps figuring out the issue.

**Comment by stephentoub** [comment]
I see. I misunderstood the concern you were raising. You're concerned about the token stored in the exception, not that cancelation exceptions are occurring when not requested.

I think that block should actually be more like:
```C#
if (cancellationToken.IsCancellationRequested)
{
    if (e.Token == cancellationToken) throw;
    throw new OperationCanceledException(token, e);
}
else if (tokenSource.IsCancellationRequested)
{
    IsCanceled = true;
}
else
{
    throw;
}
```
cc: @halter73

**Comment by bentoi** [comment]
The same fix is needed for the `ReadAtLeastCore` implementation 😉. Should I open another issue?

**Comment by manandre** [comment]
> The same fix is needed for the `ReadAtLeastCore` implementation 😉. Should I open another issue?

Fix applied to the  `ReadAtLeastAsync` implementation in #83926
