### ISSUE TITLE
Test failure profiler\\multiple\\multiple\\multiple.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#82690]
Run: [runtime-coreclr r2r-extra 20230225.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=185253)
 
 **Failed tests:**
 ```
 R2R-CG2 windows arm64 Checked jitminopts @ Windows.11.Arm64.Open
     - profiler\\multiple\\multiple\\multiple.cmd
 ```
 
 **Error message:**
 ```
 Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.MultiplyLoaded.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\BA0809DB\w\A49E090C\uploads\Reports\profiler.multiple\multiple\multiple.output.txt
Raw output:
BEGIN EXECUTION
common.dll
Microsoft.Diagnostics.NETCore.Client.dll
multiple.dll
Profiler.dll
profiler_common.dll
TestLibrary.dll
        6 file(s) copied.
 4:49:45.77
Response file: C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\common.dll.rsp
C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\IL-CG2\common.dll
-o:C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\common.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\BA0809DB\p\System.*.dll
-r:C:\h\w\BA0809DB\p\Microsoft.*.dll
-r:C:\h\w\BA0809DB\p\mscorlib.dll
-r:C:\h\w\BA0809DB\p\netstandard.dll
-O
" "dotnet" "C:\h\w\BA0809DB\p\crossgen2\crossgen2.dll" @"C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\common.dll.rsp"   -r:C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\common.dll
" "dotnet" "C:\h\w\BA0809DB\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\common.dll --out C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\common.dll.r2rdump --val"
 4:49:47.71
 4:49:47.71
Response file: C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\Microsoft.Diagnostics.NETCore.Client.dll.rsp
C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\IL-CG2\Microsoft.Diagnostics.NETCore.Client.dll
-o:C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\Microsoft.Diagnostics.NETCore.Client.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\BA0809DB\p\System.*.dll
-r:C:\h\w\BA0809DB\p\Microsoft.*.dll
-r:C:\h\w\BA0809DB\p\mscorlib.dll
-r:C:\h\w\BA0809DB\p\netstandard.dll
-O
" "dotnet" "C:\h\w\BA0809DB\p\crossgen2\crossgen2.dll" @"C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\Microsoft.Diagnostics.NETCore.Client.dll.rsp"   -r:C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\Microsoft.Diagnostics.NETCore.Client.dll
" "dotnet" "C:\h\w\BA0809DB\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\Microsoft.Diagnostics.NETCore.Client.dll --out C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\Microsoft.Diagnostics.NETCore.Client.dll.r2rdump --val"
 4:49:50.58
 4:49:50.58
Response file: C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\multiple.dll.rsp
C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\IL-CG2\multiple.dll
-o:C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\multiple.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\BA0809DB\p\System.*.dll
-r:C:\h\w\BA0809DB\p\Microsoft.*.dll
-r:C:\h\w\BA0809DB\p\mscorlib.dll
-r:C:\h\w\BA0809DB\p\netstandard.dll
-O
" "dotnet" "C:\h\w\BA0809DB\p\crossgen2\crossgen2.dll" @"C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\multiple.dll.rsp"   -r:C:\h\w\BA0809DB\w\A49E090C\e\profiler\multiple\multiple\IL-CG2\*.dll"
Emitting R2R PE f
 ```
 
 **Stack trace:**
 ```
   at profiler_multiple._multiple_multiple_._multiple_multiple_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by hoyosjs** [comment]
@davmason this one seems to on shutdown, but no profiler succeed message
