### ISSUE TITLE
Test failure System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#82692]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20230225.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184893&view=ms.vss-test-web.build-test-results-tab&runId=3576245&resultId=178118&paneView=debug)

Failed test:
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open

- System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback(checkRevocation: True)
- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.TimestampTooOld(includeOption: None)
- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.TimestampTooOld(includeOption: WholeChain)
- System.Formats.Asn1.Tests.Writer.WriteGeneralizedTime.VerifyWriteGeneralizedTime_IgnoresConstructed(ruleSet: DER)
- System.Formats.Asn1.Tests.Writer.WriteGeneralizedTime.VerifyWriteGeneralizedTime_IgnoresConstructed(ruleSet: CER)
- System.Formats.Asn1.Tests.Writer.WriteGeneralizedTime.VerifyWriteGeneralizedTime_IgnoresConstructed(ruleSet: BER)
... ...

net8.0-linux-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Ubuntu.1804.Amd64.Open

- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.CertMatchV1AndV2(includeOption: None, v1Option: ValidHashWithName, v2Option: ValidHashWithName, hashAlgName: \"SHA384\")
- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.CertMatchV1AndV2(includeOption: None, v1Option: ValidHashWithName, v2Option: ValidHashWithName, hashAlgName: null)
- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.CertMatchV1AndV2(includeOption: WholeChain, v1Option: ValidHashWithName, v2Option: ValidHashWithName, hashAlgName: \"SHA384\")
- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.CertMatchV1AndV2(includeOption: WholeChain, v1Option: ValidHashWithName, v2Option: ValidHashWithName, hashAlgName: null)
- System.Security.Cryptography.Pkcs.Tests.TimestampTokenTests.CertMatchV1AndV2(includeOption: None, v1Option: ValidHashWithName, v2Option: ValidHashNoName, hashAlgName: \"SHA512\")
... ...
```
**Error message:**
```
Assert.Equal() Failure
Expected: RemoteCertificateChainErrors
Actual:   None


Stack trace
   at System.Net.Security.Tests.CertificateValidationRemoteServer.<ConnectWithRevocation_WithCallback_Core>g__CertificateValidationCallback|7_0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 364
   at System.Net.Security.SslStream.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Protocol.cs:line 1071
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 537
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 550
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs:line 335
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 316
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 317
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 317
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 317
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates) in /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs:line 317
--- End of stack trace from previous location ---
```

**Comment by CarnaViire** [comment]
Triage: we should check how much does this fail -- we don't see it happening in runtime CI pipeline. Closing for now, but we'll reopen if it resurfaces.
