### ISSUE TITLE
System.Text.Json source generator does not support custom property names through JsonPropertyNameAttribute

### ISSUE THREAD

**Issue by mazhou-msft** [dotnet/runtime#82730]
### Description

When using Json Source Generator, it does not support custom property names by applying `JsonPropertyName` attribute. As the below code demonstrates, it will throw an exception in this case. 

### Reproduction Steps

Use the code below.

```csharp
using System.Collections.Immutable;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Collections.Frozen;

var json = /*lang=json,strict*/ """
 {
    "name": "John",
    "phoneNumbers": [
        "425-000-1212",
        "425-000-1213"
    ],
    "additionalData": {
        "key1": "value1",
        "key2": "value2"
    },
    "sv": "1.0.9999"
 }
 """;

var context = JsonContext.Default;
var person = JsonSerializer.Deserialize(json, context.Person);

Console.WriteLine(person!.SchemaVersion);

[JsonSerializable(typeof(Person))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
public sealed partial class JsonContext : JsonSerializerContext
{ 
}

public class Person
{
    public required string Name { get; set; }

    public required ImmutableList<string> PhoneNumbers { get; init; }

    [JsonPropertyName("sv")]
    public required Version SchemaVersion { get; init; }

    [JsonExtensionData]
    [JsonInclude]
    public IDictionary<string, JsonElement> AdditionalData { get; private set; } = new Dictionary<string, JsonElement>();
}

```

### Expected behavior

The code should run and output following
`1.0.9999`

### Actual behavior

Code throws exception:

```
Unhandled exception. System.InvalidOperationException: Each parameter in the deserialization constructor on type 'Person' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at Program.<Main>$(String[] args) in C:\Users\mazhou\source\repos\Demo\Demo\Program.cs:line 22
```

### Regression?

Not sure

### Known Workarounds

Remove the `JsonPropertyName` attribute from the affected property, or use 
```csharp
[JsonPropertyName("schemaVersion")]
```

### Configuration

.NET 8 Preview (1 & 2)
Windows 11 22H2 x64
VS 17.6 Preview 1

### Other information

If it is not supported by plans, we should at least adjust the error message to be more clear to the customer.

**Comment by eiriktsarpalis** [comment]
I can reproduce: 
```C#
JsonTypeInfo<Person> typeInfo = JsonContext.Default.Person;

string json = JsonSerializer.Serialize(new Person { Property = 42 }, typeInfo);
var person = JsonSerializer.Deserialize(json, typeInfo);

[JsonSerializable(typeof(Person))]
public sealed partial class JsonContext : JsonSerializerContext 
{
}

public class Person 
{
    [JsonPropertyName("Prop")]
    public int Property { get; init; }
}
```
This is a .NET 8 only issue, the fix for `required` and `init` properties in #79828 appears to not account for custom property names when doing constructor parameter info binding. We should fix this.

**Comment by mazhou-msft** [comment]
Thanks for the quick fix!

**Comment by eiriktsarpalis** [comment]
Thanks for reporting the issue so early! The fix should become available once Preview 3 gets released.
