### ISSUE TITLE
Cast exception in ImmutableCollections.DoNotCallToImmutableCollectionOnAnImmutableCollectionValueAnalyzer on Preview 1 SDK

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#82741]
**Version Used**:  Microsoft (R) Visual C# Compiler version 4.6.0-1.23109.10 (73338d92)

During Arcade PR to diagnostics which includes an SDK update to preview 1: 

```
Csc
    Assembly = D:\a\_work\1\s\.dotnet\sdk\8.0.100-preview.1.23115.2\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll
    ...
D:\a\_work\1\s\artifacts\obj\DbgShim.UnitTests\Release\net6.0\DbgShim.UnitTests.AssemblyInfo.cs /warnaserror+:NU1605
    CompilerServer: tool - using command line tool by design 'D:\a\_work\1\s\.dotnet\dotnet.exe' - ef89cd70-e1f2-4e39-9be8-f6682bbd9912
    Microsoft (R) Visual C# Compiler version 4.6.0-1.23109.10 (73338d92)
    Copyright (C) Microsoft Corporation. All rights reserved.
    Errors
        CSC error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.ImmutableCollections.DoNotCallToImmutableCollectionOnAnImmutableCollectionValueAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.ArrayTypeSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'. [D:\a\_work\1\s\src\tests\DbgShim.UnitTests\DbgShim.UnitTests.csproj]
        CSC error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.ImmutableCollections.DoNotCallToImmutableCollectionOnAnImmutableCollectionValueAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.ArrayTypeSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.'. [D:\a\_work\1\s\src\tests\DbgShim.UnitTests\DbgShim.UnitTests.csproj]
    Exception occurred with following context:
    Compilation: DbgShim.UnitTests
    IOperation: Invocation
    SyntaxTree: D:\a\_work\1\s\src\tests\DbgShim.UnitTests\LibraryProviderWrapper.cs
    SyntaxNode: elfFile.BuildID.ToImmutableArray ... [InvocationExpressionSyntax]@[17022..17056) (403,31)-(403,65)
    System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.ArrayTypeSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.
       at Microsoft.NetCore.Analyzers.ImmutableCollections.DoNotCallToImmutableCollectionOnAnImmutableCollectionValueAnalyzer.<>c__DisplayClass10_0.<Initialize>b__1(OperationAnalysisContext operationContext)
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
    -----
    Suppress the following diagnostics to disable this analyzer: CA2009
    Exception occurred with following context:
    Compilation: DbgShim.UnitTests
    IOperation: Invocation
    SyntaxTree: D:\a\_work\1\s\src\tests\DbgShim.UnitTests\LibraryProviderWrapper.cs
    SyntaxNode: machOFile.Uuid.ToImmutableArray ... [InvocationExpressionSyntax]@[17477..17510) (412,31)-(412,64)
    System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.ArrayTypeSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.
       at Microsoft.NetCore.Analyzers.ImmutableCollections.DoNotCallToImmutableCollectionOnAnImmutableCollectionValueAnalyzer.<>c__DisplayClass10_0.<Initialize>b__1(OperationAnalysisContext operationContext)
       at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
    -----
    Suppress the following diagnostics to disable this analyzer: CA2009

```

Link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=186280&view=logs&j=381005e4-1702-5f11-e3ba-1c83c6f16daf&t=cf0c8f6c-b092-553d-d3b5-a9c73b3fa7b5&l=241

**Comment by CyrusNajmabadi** [comment]
This is not a roslyn analyzer.  Transferring.

**Comment by hoyosjs** [comment]
Moving to roslyn-analyzers.
