### ISSUE TITLE
[browser] FetchError: request failed, reason: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#82880]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-82865-merge-eed132fb706b4bff95/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.4e89e456.log?helixlogtype=result) [Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=190149&view=results)

This is NodeJS on linux

```
[FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(newline: "\n", fold: "", dribble: False)
[00:19:13] info: System.Net.Http.HttpRequestException : FetchError: request to http://127.0.0.1:39305/ failed, reason: Parse Error: Invalid header value char
[00:19:13] info: ---- System.Runtime.InteropServices.JavaScript.JSException : FetchError: request to http://127.0.0.1:39305/ failed, reason: Parse Error: Invalid header value char
[00:19:13] info:    at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[00:19:13] info:    at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
[00:19:13] info:    at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|55_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
[00:19:13] info:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[00:19:13] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass21_0.<<GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly>b__0>d.MoveNext()
[00:19:13] info: --- End of stack trace from previous location ---
[00:19:13] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[00:19:13] info: --- End of stack trace from previous location ---
[00:19:13] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[00:19:13] info:    at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass15_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[00:19:13] info: --- End of stack trace from previous location ---
[00:19:13] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[00:19:13] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.GetAsync_ManyDifferentResponseHeaders_ParsedCorrectly(String newline, String fold, Boolean dribble)
[00:19:13] info: --- End of stack trace from previous location ---
[00:19:13] info: ----- Inner Stack Trace -----
[00:19:13] info:    at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
[00:19:13] info:     at ClientRequest.<anonymous> (/root/helix/work/workitem/e/node_modules/node-fetch/lib/index.js:1491:11)
[00:19:13] info:     at ClientRequest.emit (node:events:513:28)
[00:19:13] info:     at Socket.socketOnData (node:_http_client:543:9)
[00:19:13] info:     at Socket.emit (node:events:513:28)
[00:19:13] info:     at addChunk (node:internal/streams/readable:315:12)
[00:19:13] info:     at readableAddChunk (node:internal/streams/readable:289:9)
[00:19:13] info:     at Socket.Readable.push (node:internal/streams/readable:228:10)
[00:19:13] info:     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by pavelsavara** [comment]
cc @maraf

**Comment by maraf** [comment]
It's Linux specific, probably related to node update to v17.

**Comment by maraf** [comment]
Node v16 is almost EOL https://endoflife.date/nodejs. The error doesn't reproduce in v17

**Comment by maraf** [comment]
We still have node 16.19, I would like to enable the test when we upgrade

**Comment by ilonatommy** [comment]
Currently we have `v18.17.1` [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-103804-merge-4c825bd6447d4207b2/Workloads-NoWebcil-ST-Wasm.Build.Tests.NativeBuildTests/1/console.d8e67a05.log?helixlogtype=result), I can't repro locally, unblocking

**Comment by ilonatommy** [comment]
Reproduced on CI: [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-103959-merge-284c3841ddbb472590/WasmTestOnNodeJS-ST-System.Net.Http.Functional.Tests/1/console.d3363a16.log?helixlogtype=result)

```
[15:43:38] info: Using js engine NodeJS from path /usr/bin/node
[15:43:38] info: v18.17.1
```
