### ISSUE TITLE
Several XML tests are sporadically failing in CI due to OOMs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#82894]
e.g.
```
  Discovering: System.Private.Xml.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Private.Xml.Tests (found 4736 of 4787 test cases)
  Starting:    System.Private.Xml.Tests (parallel test collections = on, max threads = 2)
    System.Xml.CharCheckingReaderTests.CharCheckingReaderTest.RunTests(testCase: ReadBinHex runs into an Overflow) [FAIL]
      System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/String.cs(291,0): at System.String.Ctor(ReadOnlySpan`1 value)
        /_/src/libraries/System.Private.CoreLib/src/System/Span.cs(384,0): at System.Span`1.ToString()
        /_/src/libraries/Common/src/System/Text/ValueStringBuilder.cs(90,0): at System.Text.ValueStringBuilder.ToString()
        /_/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs(551,0): at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
        /_/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs(512,0): at System.String.Format(String format, Object[] args)
        /_/src/libraries/System.Private.Xml/src/System/Xml/XmlException.cs(197,0): at System.Xml.XmlException.CreateMessage(String res, String[] args, Int32 lineNumber, Int32 linePosition)
        /_/src/libraries/System.Private.Xml/src/System/Xml/XmlException.cs(117,0): at System.Xml.XmlException..ctor(String res, String arg)
        /_/src/libraries/System.Private.Xml/src/System/Xml/BinHexDecoder.cs(165,0): at System.Xml.BinHexDecoder.Decode(ReadOnlySpan`1 chars, Span`1 bytes, Boolean& hasHalfByteCached, Byte& cachedHalfByte, Int32& charsDecoded, Int32& bytesDecoded)
        /_/src/libraries/System.Private.Xml/src/System/Xml/BinHexDecoder.cs(74,0): at System.Xml.BinHexDecoder.Decode(String str, Int32 startPos, Int32 len)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/ReadContentAsBinaryHelper.cs(367,0): at System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/ReadContentAsBinaryHelper.cs(394,0): at System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/ReadContentAsBinaryHelper.cs(232,0): at System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlCharCheckingReader.cs(567,0): at System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHex(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/tests/XmlReaderLib/CDataReader.cs(822,0): at System.Xml.Tests.CDataReader.ReadElementContentAsBinHex(Byte[] array, Int32 offset, Int32 len)
        /_/src/libraries/System.Private.Xml/tests/XmlReaderLib/ReadBinHex.cs(970,0): at System.Xml.Tests.TCReadElementContentAsBinHex.TestReadBinHex_105376()
        /_/src/libraries/Common/tests/System/Xml/ModuleCore/cvariation.cs(77,0): at OLEDB.Test.ModuleCore.CVariation.Execute()
        /_/src/libraries/Common/tests/System/Xml/ModuleCore/ctestcase.cs(131,0): at OLEDB.Test.ModuleCore.CTestCase.<>c__DisplayClass7_1.<TestCases>b__0()
        /_/src/libraries/Common/tests/System/Xml/ModuleCore/XunitTestCase.cs(33,0): at OLEDB.Test.ModuleCore.XunitTestCase.Run()
        /_/src/libraries/System.Private.Xml/tests/Readers/CharCheckingReader/CharReaderTests.cs(16,0): at System.Xml.CharCheckingReaderTests.CharCheckingReaderTest.RunTests(XunitTestCase testCase)
           at InvokeStub_CharCheckingReaderTest.RunTests(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    System.Xml.CharCheckingReaderTests.CharCheckingReaderTest.RunTests(testCase: ReadBinHex runs into an Overflow) [FAIL]
      System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
      Stack Trace:
           at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)
        /_/src/libraries/System.Private.CoreLib/src/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs(113,0): at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
        /_/src/libraries/Common/src/System/Text/ValueStringBuilder.cs(302,0): at System.Text.ValueStringBuilder.Grow(Int32 additionalCapacityBeyondPos)
        /_/src/libraries/System.Private.CoreLib/src/System/Text/ValueStringBuilder.AppendFormat.cs(250,0): at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
        /_/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs(550,0): at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
        /_/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs(512,0): at System.String.Format(String format, Object[] args)
        /_/src/libraries/System.Private.Xml/src/System/Xml/XmlException.cs(197,0): at System.Xml.XmlException.CreateMessage(String res, String[] args, Int32 lineNumber, Int32 linePosition)
        /_/src/libraries/System.Private.Xml/src/System/Xml/XmlException.cs(117,0): at System.Xml.XmlException..ctor(String res, String arg)
        /_/src/libraries/System.Private.Xml/src/System/Xml/BinHexDecoder.cs(165,0): at System.Xml.BinHexDecoder.Decode(ReadOnlySpan`1 chars, Span`1 bytes, Boolean& hasHalfByteCached, Byte& cachedHalfByte, Int32& charsDecoded, Int32& bytesDecoded)
        /_/src/libraries/System.Private.Xml/src/System/Xml/BinHexDecoder.cs(74,0): at System.Xml.BinHexDecoder.Decode(String str, Int32 startPos, Int32 len)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/ReadContentAsBinaryHelper.cs(367,0): at System.Xml.ReadContentAsBinaryHelper.ReadContentAsBinary(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/ReadContentAsBinaryHelper.cs(394,0): at System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinary(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/ReadContentAsBinaryHelper.cs(232,0): at System.Xml.ReadContentAsBinaryHelper.ReadElementContentAsBinHex(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlCharCheckingReader.cs(567,0): at System.Xml.XmlCharCheckingReader.ReadElementContentAsBinHex(Byte[] buffer, Int32 index, Int32 count)
        /_/src/libraries/System.Private.Xml/tests/XmlReaderLib/CDataReader.cs(822,0): at System.Xml.Tests.CDataReader.ReadElementContentAsBinHex(Byte[] array, Int32 offset, Int32 len)
        /_/src/libraries/System.Private.Xml/tests/XmlReaderLib/ReadBinHex.cs(970,0): at System.Xml.Tests.TCReadElementContentAsBinHex.TestReadBinHex_105376()
        /_/src/libraries/Common/tests/System/Xml/ModuleCore/cvariation.cs(77,0): at OLEDB.Test.ModuleCore.CVariation.Execute()
        /_/src/libraries/Common/tests/System/Xml/ModuleCore/ctestcase.cs(131,0): at OLEDB.Test.ModuleCore.CTestCase.<>c__DisplayClass7_1.<TestCases>b__0()
        /_/src/libraries/Common/tests/System/Xml/ModuleCore/XunitTestCase.cs(33,0): at OLEDB.Test.ModuleCore.XunitTestCase.Run()
        /_/src/libraries/System.Private.Xml/tests/Readers/CharCheckingReader/CharReaderTests.cs(16,0): at System.Xml.CharCheckingReaderTests.CharCheckingReaderTest.RunTests(XunitTestCase testCase)
           at InvokeStub_CharCheckingReaderTest.RunTests(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "ReadBinHex runs into an Overflow",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[493122](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493122)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=493122&view=ms.vss-test-web.build-test-results-tab&runId=11431808&resultId=175649)|dotnet/runtime#95324|
|[488999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=488999)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=488999&view=ms.vss-test-web.build-test-results-tab&runId=11303730&resultId=181394)|dotnet/runtime#95324|
|[487764](https://dev.azure.com/dnceng-public/public/_build/results?buildId=487764)|dotnet/runtime|[WasmTestOnBrowser-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=487764&view=ms.vss-test-web.build-test-results-tab&runId=11261856&resultId=181393)|dotnet/runtime#95324|
|[486016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=486016)|dotnet/runtime|[WasmTestOnNodeJS-System.Private.Xml.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=486016&view=ms.vss-test-web.build-test-results-tab&runId=11201418&resultId=167433)|dotnet/runtime#95324|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|4|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.

**Comment by danmoseley** [comment]
> ErrorMessage": "",

Won't this match every failure everywhere?

**Comment by stephentoub** [comment]
> Won't this match every failure everywhere?

The bot added that.  I haven't yet edited it.
