### ISSUE TITLE
System.Net.Http.Json.Functional.Tests failed in CI on mono_interpreter linux x64 Debug leg

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#82918]
### Description

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-82749-merge-fdbe8f8962684007ba/System.Net.Http.Json.Functional.Tests/1/console.40f776d9.log?helixlogtype=result
https://dev.azure.com/dnceng-public/public/_build/results?buildId=189717&view=logs&j=23a86602-2d9d-5895-e5e2-aa59708a0666&t=1a6bdf4d-f5b5-57dc-7f13-e811be7fe65f&l=55

```
  Discovering: System.Net.Http.Json.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.Json.Functional.Tests (found 44 test cases)
  Starting:    System.Net.Http.Json.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.GetFromJsonAsync_EnforcesTimeout(useDeleteAsync: True, slowHeaders: False) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Threading.Tasks.TaskCanceledException)
      Actual:   typeof(System.Net.Http.HttpRequestException): Connection refused (127.0.0.1:33023)
      ---- System.Net.Http.HttpRequestException : Connection refused (127.0.0.1:33023)
      -------- System.Net.Sockets.SocketException : Connection refused
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1630,0): at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1533,0): at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1638,0): at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(487,0): at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
        /_/src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs(21,0): at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1[[System.Net.Http.HttpConnection, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(2596,0): at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.<WaitForConnectionAsync>d__5[[System.Net.Http.HttpConnection, System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1101,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(550,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.cs(84,0): at System.Net.Http.Json.HttpClientJsonExtensions.<<FromJsonAsyncCore>g__Core|4_0>d`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Text.Json.JsonSerializerOptions, System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
        ----- Inner Stack Trace -----

```

### Reproduction Steps

It is CI test run

### Expected behavior

Test should pass

### Actual behavior

test is failing

**Comment by eiriktsarpalis** [comment]
@CarnaViire given the error message this looks like an `area-System.Net.Http` or test infra issue?

**Comment by eiriktsarpalis** [comment]
@dotnet/ncl ☝️

**Comment by CarnaViire** [comment]
I've found that the test was introduced by @MihaZupan in https://github.com/dotnet/runtime/pull/79386
It doesn't seem like an infra issue, as the connection is to localhost. Could it be test issue @MihaZupan -- any thoughts?
Interestingly, I don't see such failures in Kusto...

**Comment by MihaZupan** [comment]
Seems like an infra/environment issue to me, I don't think there's anything special with the test up to the point where the loopback connection is made. If we haven't seen more failures for it I'd ignore it.

**Comment by eiriktsarpalis** [comment]
Seems that we could close this for now.
