### ISSUE TITLE
TarWriter on Windows Server treats File Deduplication reparse point flag as symbolic links

### ISSUE THREAD

**Issue by billfreist** [dotnet/runtime#82949]
https://github.com/dotnet/runtime/blob/9fd3ece652fed473c9f2398363da6d7bca41a5d9/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Windows.cs#L25

As seen in the snippet above, the Tar Entry gets mistaken for a symlink if the reparse point flag is set, but it doesn't verify if the file/directory is actually a symlink/junction. Windows Server with file deduplication enabled, or even OneDrive synced files, can set the Reparse point flag, but utilizes entirely different reparse tags.

IO_REPARSE_TAG_DEDUP is used for deduplication, whereas IO_REPARSE_TAG_MOUNT_POINT & IO_REPARSE_TAG_SYMLINK are used for junctions and symlinks.

**Comment by billfreist** [comment]
I should note, this results in the following exception:

```
System.ArgumentException: The value cannot be an empty string. (Parameter 'value')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.Formats.Tar.TarEntry.set_LinkName(String value)
   at System.Formats.Tar.TarWriter.ConstructEntryForWriting(String fullPath, String entryName, FileOptions fileOptions)
   at System.Formats.Tar.TarWriter.ReadFileFromDiskAndWriteToArchiveStreamAsEntryAsync(String fullPath, String entryName, CancellationToken cancellationToken)

**Comment by billfreist** [comment]
Looking further, it appears this line is masking the issue (which ultimately leads to the exception due to the fallback to passing `string.Empty`.
https://github.com/dotnet/runtime/blob/9fd3ece652fed473c9f2398363da6d7bca41a5d9/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Windows.cs#L61

`FileSystemInfo.LinkTarget` checks for those proper Reparse Tags mentioned above and returns `null` when it doesn't have those tags. It would _seem_ that the code could just check for the existence of that valid LinkTarget once it determines it has the reparse point file flag. Something like:

`if ((attributes & FileAttributes.ReparsePoint) != 0 && info.LinkTarget is not null)`

**Comment by carlossanlop** [comment]
@Jozkee @adamsitnik is this something that the System.IO APIs do correctly, or do we have to address this problem in both the Tar APIs and the IO APIs? (maybe Zip too?)

**Comment by Jozkee** [comment]
`LinkTarget` works properly.

> FileSystemInfo.LinkTarget checks for those proper Reparse Tags mentioned above and returns null

**Comment by billfreist** [comment]
> `LinkTarget` works properly.
> 
> > FileSystemInfo.LinkTarget checks for those proper Reparse Tags mentioned above and returns null

Sorry, the wording wasn't clear. I meant that it returns `null` when its supposed to. So in the case I'm hitting with the dedup tag, its `null`, when it has the symbolic link or junction tags then it returns a valid link target.

**Comment by carlossanlop** [comment]
@billfreist - 

I see what you mean. We should explicitly confirm that the file is a reparse point of type junction, and nothing else, and if the answer is "junction", we should store it in the archive as a symbolic link (because it's the closest entry type to junction, and because the Tar spec does not officially support junctions).

I am unsure how the other reparse points should be treated. I suspect we could try treating them as regular files. I'd have to investigate.

If it's helpful for you, @billfreist , the workaround would be to manually extract that reparse point junction entry manually, using TarArchive to open the archive, then iterating the entries until the one that failed is found, and manually creating a symbolic link for it: https://learn.microsoft.com/en-us/dotnet/api/system.io.file.createsymboliclink?view=net-7.0

**Comment by carlossanlop** [comment]
Ok I have a fix that would specifically check, just like we do in FileSystem.Windows.cs, that if we have a reparse point, we only treat it as a tar symlink if windows categorized it as a junction or as a symlink.

**Comment by karelz** [comment]
Triage: Next step - pick up previous PR #89102 and finish it (adding tests).
