### ISSUE TITLE
[wasi] Failing test - `System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest_Negative`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#82967]
```
  info: Starting:    managed/System.Runtime.Serialization.Xml.Tests.dll
  fail: [FAIL] System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest_Negative(badType: typeof(System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests+TypeWithReadWriteCollectionAndNoCtorOnCollection), exType: typeof(System.Runtime.Serialization.InvalidDataContractException), exMsg: "System.Runtime.Serialization.Xml.XsdDataContractEx"...)
  info: Assert.Throws() Failure
  info: Expected: typeof(System.Runtime.Serialization.InvalidDataContractException)
  info: Actual:   (No exception was thrown)
  info:    at System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest_Negative(Type badType, Type exType, String exMsg)
  info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
  info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by StephenMolloy** [comment]
I have re-enabled a bunch of serialization tests in PR #118507.
Per these two runs ([1118444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118444), [1118071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1118071)), many of these testcases are failing anymore.

`System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterTypesTests.TypesTest_Negative` still fails.
