### ISSUE TITLE
Testing Mono runtime and Testing Libraries failed on Windows X64

### ISSUE THREAD

**Issue by LyricChuan** [dotnet/runtime#83074]
Branch release/7.0
Testing Mono runtime
follow the steps in PowerShell
1）./build.cmd mono+libs                       #success
2）./build.cmd clr.hosts -c debug           #success
3）cd src/tests
     ./build.cmd mono debug                   #success
4）./run.cmd Debug                               #fail

Summary
Tests run: 2191 — Failures: 3

Failed tests
 ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd
\r\nReturn code:      1\r\nRaw output file:      D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Reports\\ilasm.PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n \"D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\\corerun.exe\"   IlasmPortablePdbTests.dll \r\n\r\nAssembling 'D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\TestFiles\\TestPdbDebugDirectory1.il'  to DLL --> 'D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\TestFiles\\TestPdbDebugDirectory1.dll'\r\nSource file is UTF-8\r\n\r\nAssembled method TestPdbDebugDirectoryType::Foo\r\nCreating PE file\r\n\r\nEmitting classes:\r\nClass 1:TestPdbDebugDirectoryType\r\n\r\nEmitting fields and methods:\r\nGlobal \r\nClass 1Methods: 1;\r\n\r\nEmitting events and properties:\r\nGlobal \r\nClass 1\r\nWriting PE file\r\nFailed to write output file, error code=0x80070020\r\nWriting PDB file: D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\TestFiles\\TestPdbDebugDirectory1.pdb\r\n\r\n***** FAILURE ***** \r\nXunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1\r\n   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 101\r\n   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63\r\n   at IlasmPortablePdbTests.IlasmPortablePdbTesterCommon.Assemble(String ilasmFullPath, String ilSrc, String testDir, String& dll, String& pdb) in D:\\Work_DotNet\\runtime\\src\\tests\\ilasm\\PortablePdb\\IlasmPortablePdbTesterCommon.cs:line 48\r\n   at IlasmPortablePdbTests.IlasmPortablePdbTester.TestPortablePdbDebugDirectory(String ilSource) in D:\\Work_DotNet\\runtime\\src\\tests\\ilasm\\PortablePdb\\IlasmPortablePdbTester.cs:line 38\r\n   at Program.<Main>$(String[] args) in D:\\Work_DotNet\\runtime\\src\\tests\\ilasm\\PortablePdb\\XUnitWrapperGenerator\\XUnitWrapperGenerator.XUnitWrapperGenerator\\SimpleRunner.g.cs:line 3\r\nExpected: 100\r\nActual: 101\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\r\n> D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd\r\nExpected: True\r\nActual:   False
   at ilasm_PortablePdb._IlasmPortablePdbTests_IlasmPortablePdbTests_._IlasmPortablePdbTests_IlasmPortablePdbTests_cmd() in D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\TestWrappers\ilasm.PortablePdb\ilasm.PortablePdb.XUnitWrapper.cs:line 149
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Output:
Return code:      1
Raw output file:      D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Reports\ilasm.PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.output.txt
Raw output:
BEGIN EXECUTION
 "D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe"   IlasmPortablePdbTests.dll 

Assembling 'D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\TestFiles\TestPdbDebugDirectory1.il'  to DLL --> 'D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\TestFiles\TestPdbDebugDirectory1.dll'
Source file is UTF-8

Assembled method TestPdbDebugDirectoryType::Foo
Creating PE file

Emitting classes:
Class 1:TestPdbDebugDirectoryType

Emitting fields and methods:
Global 
Class 1Methods: 1;

Emitting events and properties:
Global 
Class 1
Writing PE file
Failed to write output file, error code=0x80070020
Writing PDB file: D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\TestFiles\TestPdbDebugDirectory1.pdb

***** FAILURE ***** 
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   1
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 101
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63
   at IlasmPortablePdbTests.IlasmPortablePdbTesterCommon.Assemble(String ilasmFullPath, String ilSrc, String testDir, String& dll, String& pdb) in D:\Work_DotNet\runtime\src\tests\ilasm\PortablePdb\IlasmPortablePdbTesterCommon.cs:line 48
   at IlasmPortablePdbTests.IlasmPortablePdbTester.TestPortablePdbDebugDirectory(String ilSource) in D:\Work_DotNet\runtime\src\tests\ilasm\PortablePdb\IlasmPortablePdbTester.cs:line 38
   at Program.<Main>$(String[] args) in D:\Work_DotNet\runtime\src\tests\ilasm\PortablePdb\XUnitWrapperGenerator\XUnitWrapperGenerator.XUnitWrapperGenerator\SimpleRunner.g.cs:line 3
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
> D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.cmd
Traits:
TestGroup	ilasm.PortablePdb

======================================================================================

ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd_windows_x64_Debug.cmd
\r\nReturn code:      1\r\nRaw output file:      D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Reports\\ilasm.PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd_windows_x64_Debug.output.txt\r\nRaw output:\r\nCore_Root is set to: \"D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\"\r\ncall D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\\\PortablePdb\\\\IlasmPortablePdbTests\\\\IlasmPortablePdbTests.cmd\r\nBEGIN EXECUTION\r\n \"D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\\corerun.exe\"   IlasmPortablePdbTests.dll \r\n\r\nAssembling 'D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\TestFiles\\TestPdbDebugDirectory1.il'  to DLL --> 'D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\TestFiles\\TestPdbDebugDirectory1.dll'\r\nSource file is UTF-8\r\n\r\nAssembled method TestPdbDebugDirectoryType::Foo\r\nCreating PE file\r\n\r\nEmitting classes:\r\nClass 1:TestPdbDebugDirectoryType\r\n\r\nEmitting fields and methods:\r\nGlobal \r\nClass 1Methods: 1;\r\n\r\nEmitting events and properties:\r\nGlobal \r\nClass 1\r\nWriting PE file\r\nWriting PDB file: D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\TestFiles\\TestPdbDebugDirectory1.pdb\r\nFailed to write PDB file, error code=0x80070020\r\n\r\n***** FAILURE ***** \r\nXunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1\r\n   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 101\r\n   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63\r\n   at IlasmPortablePdbTests.IlasmPortablePdbTesterCommon.Assemble(String ilasmFullPath, String ilSrc, String testDir, String& dll, String& pdb) in D:\\Work_DotNet\\runtime\\src\\tests\\ilasm\\PortablePdb\\IlasmPortablePdbTesterCommon.cs:line 48\r\n   at IlasmPortablePdbTests.IlasmPortablePdbTester.TestPortablePdbDebugDirectory(String ilSource) in D:\\Work_DotNet\\runtime\\src\\tests\\ilasm\\PortablePdb\\IlasmPortablePdbTester.cs:line 38\r\n   at Program.<Main>$(String[] args) in D:\\Work_DotNet\\runtime\\src\\tests\\ilasm\\PortablePdb\\XUnitWrapperGenerator\\XUnitWrapperGenerator.XUnitWrapperGenerator\\SimpleRunner.g.cs:line 3\r\nExpected: 100\r\nActual: 101\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\r\n> D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd_windows_x64_Debug.cmd\r\nExpected: True\r\nActual:   False
   at ilasm_PortablePdb._IlasmPortablePdbTests_IlasmPortablePdbTests__windows_x64_Debug_._IlasmPortablePdbTests_IlasmPortablePdbTests_cmd_windows_x64_Debug_cmd() in D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\TestWrappers\ilasm.PortablePdb\ilasm.PortablePdb.XUnitWrapper.cs:line 248
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Output:
Return code:      1
Raw output file:      D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Reports\ilasm.PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.cmd_windows_x64_Debug.output.txt
Raw output:
Core_Root is set to: "D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root"
call D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd
BEGIN EXECUTION
 "D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe"   IlasmPortablePdbTests.dll 

Assembling 'D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\TestFiles\TestPdbDebugDirectory1.il'  to DLL --> 'D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\TestFiles\TestPdbDebugDirectory1.dll'
Source file is UTF-8

Assembled method TestPdbDebugDirectoryType::Foo
Creating PE file

Emitting classes:
Class 1:TestPdbDebugDirectoryType

Emitting fields and methods:
Global 
Class 1Methods: 1;

Emitting events and properties:
Global 
Class 1
Writing PE file
Writing PDB file: D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\TestFiles\TestPdbDebugDirectory1.pdb
Failed to write PDB file, error code=0x80070020

***** FAILURE ***** 
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 0
Actual:   1
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 101
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 63
   at IlasmPortablePdbTests.IlasmPortablePdbTesterCommon.Assemble(String ilasmFullPath, String ilSrc, String testDir, String& dll, String& pdb) in D:\Work_DotNet\runtime\src\tests\ilasm\PortablePdb\IlasmPortablePdbTesterCommon.cs:line 48
   at IlasmPortablePdbTests.IlasmPortablePdbTester.TestPortablePdbDebugDirectory(String ilSource) in D:\Work_DotNet\runtime\src\tests\ilasm\PortablePdb\IlasmPortablePdbTester.cs:line 38
   at Program.<Main>$(String[] args) in D:\Work_DotNet\runtime\src\tests\ilasm\PortablePdb\XUnitWrapperGenerator\XUnitWrapperGenerator.XUnitWrapperGenerator\SimpleRunner.g.cs:line 3
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
> D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\PortablePdb\IlasmPortablePdbTests\IlasmPortablePdbTests.cmd_windows_x64_Debug.cmd
Traits:
TestGroup	ilasm.PortablePdb

======================================================================================

ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd_windows_x64_Debug.cmd
\r\nReturn code:      1\r\nRaw output file:      D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Reports\\ilasm.System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd_windows_x64_Debug.output.txt\r\nRaw output:\r\nCore_Root is set to: \"D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\"\r\ncall D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\\\System\\\\Runtime\\\\CompilerServices\\\\MethodImplOptionsTests\\\\MethodImplOptionsTests.cmd\r\nBEGIN EXECUTION\r\n \"D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\\corerun.exe\"   MethodImplOptionsTests.dll \r\nAggressiveOptimizationTest\r\n\r\nAssembling 'MiAggressiveOptimization.il'  to DLL --> 'MiAggressiveOptimization.dll'\r\nSource file is UTF-8\r\n\r\nSource file is UTF-8\r\n\r\nSource file is UTF-8\r\n\r\nAssembled method Program::Main\r\nCreating PE file\r\n\r\nEmitting classes:\r\nClass 1:Program\r\n\r\nEmitting fields and methods:\r\nGlobal \r\nClass 1Methods: 1;\r\n\r\nEmitting events and properties:\r\nGlobal \r\nClass 1\r\nWriting PE file\r\nFailed to write output file, error code=0x80070020\r\n\r\n***** FAILURE ***** \r\nilasm failed with exit code: 1\r\nExpected: 100\r\nActual: 101\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\Tests\\Core_Root\r\n> D:\\Work_DotNet\\runtime\\artifacts\\tests\\coreclr\\windows.x64.Debug\\ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd_windows_x64_Debug.cmd\r\nExpected: True\r\nActual:   False
   at ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests__windows_x64_Debug_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_cmd_windows_x64_Debug_cmd() in D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\TestWrappers\ilasm.System\ilasm.System.XUnitWrapper.cs:line 248
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Output:
Return code:      1
Raw output file:      D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Reports\ilasm.System\Runtime\CompilerServices\MethodImplOptionsTests\MethodImplOptionsTests.cmd_windows_x64_Debug.output.txt
Raw output:
Core_Root is set to: "D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root"
call D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd
BEGIN EXECUTION
 "D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe"   MethodImplOptionsTests.dll 
AggressiveOptimizationTest

Assembling 'MiAggressiveOptimization.il'  to DLL --> 'MiAggressiveOptimization.dll'
Source file is UTF-8

Source file is UTF-8

Source file is UTF-8

Assembled method Program::Main
Creating PE file

Emitting classes:
Class 1:Program

Emitting fields and methods:
Global 
Class 1Methods: 1;

Emitting events and properties:
Global 
Class 1
Writing PE file
Failed to write output file, error code=0x80070020

***** FAILURE ***** 
ilasm failed with exit code: 1
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root
> D:\Work_DotNet\runtime\artifacts\tests\coreclr\windows.x64.Debug\ilasm\System\Runtime\CompilerServices\MethodImplOptionsTests\MethodImplOptionsTests.cmd_windows_x64_Debug.cmd
Traits:
TestGroup	ilasm.System

**Comment by LyricChuan** [comment]
Testing Libraries
follow the steps in PowerShell                                                
1）./build.cmd -subset clr+libs -rc Release                                #success
2）./build.cmd -subset mono+libs -rc Release                          #success
3）./build.cmd -subset libs.tests                                                #success
4）./build.cmd -subset libs.tests -test -testnobuild                   #fail


D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Sys
tem.DirectoryServices.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\System.DirectoryServices.Tests\Debug\ne
t7.0-windows\testResults.xml for details! [D:\Work_DotNet\runtime\src\libraries\System.DirectoryServices\tests\System.D
irectoryServices.Tests.csproj::TargetFramework=net7.0-windows]
D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Sys
tem.Drawing.Common.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\System.Drawing.Common.Tests\Debug\net7.0-w
indows\testResults.xml for details! [D:\Work_DotNet\runtime\src\libraries\System.Drawing.Common\tests\System.Drawing.Co
mmon.Tests.csproj::TargetFramework=net7.0-windows]
D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Sys
tem.Diagnostics.Process.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\System.Diagnostics.Process.Tests\Debu
g\net7.0-windows\testResults.xml for details! [D:\Work_DotNet\runtime\src\libraries\System.Diagnostics.Process\tests\Sy
stem.Diagnostics.Process.Tests.csproj::TargetFramework=net7.0-windows]
D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Sys
tem.Net.Quic.Functional.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\System.Net.Quic.Functional.Tests\Debu
g\net7.0-windows\testResults.xml for details! [D:\Work_DotNet\runtime\src\libraries\System.Net.Quic\tests\FunctionalTes
ts\System.Net.Quic.Functional.Tests.csproj::TargetFramework=net7.0-windows]
D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Mic
rosoft.Extensions.FileProviders.Physical.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\Microsoft.Extensions
.FileProviders.Physical.Tests\Debug\net7.0\testResults.xml for details! [D:\Work_DotNet\runtime\src\libraries\Microsoft
.Extensions.FileProviders.Physical\tests\Microsoft.Extensions.FileProviders.Physical.Tests.csproj::TargetFramework=net7
.0]
D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Lib
raryImportGenerator.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\LibraryImportGenerator.Tests\Debug\net7.0
\testResults.xml for details! [D:\Work_DotNet\runtime\src\libraries\System.Runtime.InteropServices\tests\LibraryImportG
enerator.Tests\LibraryImportGenerator.Tests.csproj]
D:\Work_DotNet\runtime\eng\testing\tests.targets(181,5): error : One or more tests failed while running tests from 'Icu
AppLocal.Tests'. Please check D:\Work_DotNet\runtime\artifacts\bin\IcuAppLocal.Tests\Debug\net7.0\testResults.xml for d
etails! [D:\Work_DotNet\runtime\src\libraries\System.Globalization\tests\IcuAppLocal\IcuAppLocal.Tests.csproj]
    0 warning
    7 error

Build failed with exit code 1. Check errors above.
Some builds failed:
        Configuration: Debug, Architecture: x64
