### ISSUE TITLE
[Test Failure] System.Net.Quic.Tests.QuicStreamConformanceTests.Parallel_ReadWriteMultipleStreamsConcurrently on Alpine 3.17

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#83101]
e.g. https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-120fd66ce615431389/System.Net.Quic.Functional.Tests/3/console.ed55dc16.log?helixlogtype=result

Outerloop test, 24 occurences in the last 7 days (as of 03-07)

```
----- start Wed Feb 22 12:59:27 UTC 2023 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 8 of 122 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.QuicStreamConformanceTests.Parallel_ReadWriteMultipleStreamsConcurrently [FAIL]
      System.Net.Quic.QuicException : The server refused the connection.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(470,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(569,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(598,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(312,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(68,0): at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(73,0): at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs(91,0): at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass12_0.<<CreateConnectedStreamsAsync>b__2>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(568,0): at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs(80,0): at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync()
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs(137,0): at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync()
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2471,0): at System.IO.Tests.ConnectedStreamConformanceTests.CopyToAsync_AllDataCopied(Int32 byteCount, Boolean useAsync)
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2503,0): at System.IO.Tests.ConnectedStreamConformanceTests.<Parallel_ReadWriteMultipleStreamsConcurrently>b__47_1()
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2501,0): at System.IO.Tests.ConnectedStreamConformanceTests.Parallel_ReadWriteMultipleStreamsConcurrently()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 28, Errors: 0, Failed: 1, Skipped: 0, Time: 178.986s
/root/helix/work/workitem/e
----- end Wed Feb 22 13:02:27 UTC 2023 ----- exit code 1 ----------------------------------------------------------
```

**Comment by wfurt** [comment]
probably same root cause as #82769

**Comment by ManickaP** [comment]
All occurrences are  on net8.0-linux-Release-x64-CoreCLR_Release-(Alpine.317.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-amd64, so another "baby" machine which cannot handle the load. And the test exercises parallelism, mortal combination for these type of failures.

**Comment by ManickaP** [comment]
Root cause issue is https://github.com/dotnet/runtime/issues/55979

**Comment by rzikm** [comment]
Connections being refused were fixed by https://github.com/dotnet/runtime/pull/98361.
