### ISSUE TITLE
Blazor WebAssembly dotnet 8 Preview 1 with AOT Crashes on Safari on iOS

### ISSUE THREAD

**Issue by e012345678** [dotnet/runtime#83161]
### Description

```
[Error] MONO_WASM: instantiate_wasm_module() failed: {}
	u (blazor.webassembly.js:1:38685)
	Ec (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153414)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175425)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] se@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:530
yn@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64318
wn@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64170
vc@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153380
@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175476
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
	u (blazor.webassembly.js:1:38685)
	yn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64316)
	wn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64171)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153381)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Error: Failed to start platform. Reason: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89 — blazor.webassembly.js:1:62395
	u (blazor.webassembly.js:1:38685)
	(anonymous function) (blazor.webassembly.js:1:63821)
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153198)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153285)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153314)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153343)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153372)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 124: invalid opcode 253, in function at index 89
	quit_ (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:14:1387)
	yn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64935)
	wn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64171)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153381)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] MONO_WASM: instantiate_wasm_module() failed: {}
	u (blazor.webassembly.js:1:38685)
	Ec (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153414)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175425)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] se@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:530
yn@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64318
wn@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64170
vc@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153380
@https://myapplicationhere.com/app/_framework/dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175476
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
	u (blazor.webassembly.js:1:38685)
	yn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64316)
	wn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64171)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153381)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Error: Failed to start platform. Reason: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169 — blazor.webassembly.js:1:62395
	u (blazor.webassembly.js:1:38685)
	(anonymous function) (blazor.webassembly.js:1:63821)
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153198)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153285)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153314)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153343)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169
	(anonymous function)
	rejectPromise
	reject (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:66213)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153372)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 16: invalid opcode 253, in function at index 169
	quit_ (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:14:1387)
	yn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64935)
	wn (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:64171)
	vc (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:153381)
	(anonymous function) (dotnet.8.0.0-preview.1.23110.8.rqi6qmc4oy.js:5:175477)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

### Reproduction Steps

 ```
 <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
	<WasmEnableSIMD Condition="'$(Configuration)'=='Release'">true</WasmEnableSIMD>
	<RunAOTCompilation Condition="'$(Configuration)'=='Release'">true</RunAOTCompilation>
	<WasmDedup>false</WasmDedup>
	<EmccTotalMemory Condition="'$(Configuration)'=='Release'">134217728</EmccTotalMemory>
  </PropertyGroup>
```

### Expected behavior

Should work to load the page

### Actual behavior

See above, crashes

### Configuration

Running on iOS
Safari v16

Same application works on Windows (Chrome/Edge)

**Comment by e012345678** [comment]
WasmEnableSIMD not supported in Apple Safari.
