### ISSUE TITLE
[wasm] emscripten 3.1.30 related filesystem related issue

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#83197]
These tests currently fail with emscripten 3.1.30. I don't want to block 3.1.30 bump PR, we can fix it after the bump is merged.

System.IO.FileSystem.Tests

```
[21:01:58] fail: [FAIL] System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.SetLastWriteTimeTicks
[21:01:58] info: First File Ticks	638137333180008020
[21:01:58] info: Second File Ticks	638137333180008010
[21:01:58] info: Expected: True
[21:01:58] info: Actual:   False
[21:01:58] info:    at System.IO.Tests.File_GetSetTimes.SetLastWriteTimeTicks()
[21:01:58] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
[21:01:58] info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

System.IO.MemoryMappedFiles.Tests
```
[21:01:53] fail: [FAIL] System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.LeaveOpenRespected_OutstandingViews(leaveOpen: False)
[21:01:53] info: System.UnauthorizedAccessException : Access to the path is denied.
[21:01:53] info: ---- System.IO.IOException : Bad file descriptor
[21:01:53] info:    at System.IO.MemoryMappedFiles.MemoryMappedView.Flush(UIntPtr capacity)
[21:01:53] info:    at System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Flush()
[21:01:53] info:    at System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Dispose(Boolean disposing)
[21:01:53] info:    at System.IO.UnmanagedMemoryAccessor.Dispose()
[21:01:53] info:    at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile.LeaveOpenRespected_OutstandingViews(Boolean leaveOpen)
[21:01:53] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
[21:01:53] info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[21:01:53] info: ----- Inner Stack Trace -----
[21:01:53] info: 
[21:01:54] fail: [FAIL] System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.UseAfterMMFDisposal
[21:01:54] info: System.UnauthorizedAccessException : Access to the path is denied.
[21:01:54] info: ---- System.IO.IOException : Bad file descriptor
[21:01:54] info:    at System.IO.MemoryMappedFiles.MemoryMappedView.Flush(UIntPtr capacity)
[21:01:54] info:    at System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Flush()
[21:01:54] info:    at System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Dispose(Boolean disposing)
[21:01:54] info:    at System.IO.UnmanagedMemoryAccessor.Dispose()
[21:01:54] info:    at System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.UseAfterMMFDisposal()
[21:01:54] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
[21:01:55] info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[21:01:55] info: ----- Inner Stack Trace -----
```

**Comment by pavelsavara** [comment]
I believe this is improved or fixes by recent emscripten bump

**Comment by akoeplinger** [comment]
The File tick tests were reenabled in https://github.com/dotnet/runtime/pull/129299 and are passing.
Only the MemoryMappedFiles ones are remaining, I _think_ I tried enabling them too in #129299 but I'm not sure. Let's take a look in 12.0
