### ISSUE TITLE
[Blazor WASM] System.InvalidProgramException: Unable to run method 'void Microsoft.AspNetCore.Razor.Language.Legacy.ParserHelpers:.cctor ()': locals size too big.

### ISSUE THREAD

**Issue by KristianMariyanov** [dotnet/runtime#83260]
### Description

I started the migration to net8 preview 1 in the Blazor REPL project (https://blazorrepl.telerik.com), but I get an exception while trying to compile any blazor code using `Microsoft.AspNetCore.Mvc.Razor.Extensions` package.

The error is related to the runtime because I start getting the error after updating to net8.

The same code is running successfully on net7. 

I added a sample project with steps to reproduce: https://github.com/KristianMariyanov/net8-wasm-runtime-bug

Could be related to: https://github.com/dotnet/runtime/issues/76808

### Reproduction Steps

1. Clone: https://github.com/KristianMariyanov/net8-wasm-runtime-bug
2. Ensure net 8 preview 1 is installed
3. Run the project
4. Click the button on the Index page

### Expected behavior

Run successfully

### Actual behavior

Throw exception:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'Microsoft.AspNetCore.Razor.Language.Legacy.ParserHelpers' threw an exception.
System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Razor.Language.Legacy.ParserHelpers' threw an exception.
 ---> System.InvalidProgramException: Unable to run method 'void Microsoft.AspNetCore.Razor.Language.Legacy.ParserHelpers:.cctor ()': locals size too big.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlTokenizer.Data()
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlTokenizer.Dispatch()
   at Microsoft.AspNetCore.Razor.Language.Legacy.Tokenizer.Turn()
   at Microsoft.AspNetCore.Razor.Language.Legacy.Tokenizer.NextToken()
   at Microsoft.AspNetCore.Razor.Language.Legacy.TokenizerView`1[[Microsoft.AspNetCore.Razor.Language.Legacy.HtmlTokenizer, Microsoft.AspNetCore.Razor.Language, Version=6.0.14.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].Next()
   at Microsoft.AspNetCore.Razor.Language.Legacy.TokenizerBackedParser`1[[Microsoft.AspNetCore.Razor.Language.Legacy.HtmlTokenizer, Microsoft.AspNetCore.Razor.Language, Version=6.0.14.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].NextToken()
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseDocument()
   at Microsoft.AspNetCore.Razor.Language.Legacy.RazorParser.Parse(RazorSourceDocument source)
   at Microsoft.AspNetCore.Razor.Language.RazorSyntaxTree.Parse(RazorSourceDocument source, RazorParserOptions options)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorParsingPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessDeclarationOnly(RazorProjectItem projectItem)
   at BlazorApp1.Client.Pages.Index.CompileDocument() in C:\Development\net8-wasm-runtime-bug\BlazorApp1\Client\Pages\Index.razor:line 38
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

### Regression?

The same code is running successfully on net7 sdk. You can change the version of the packages in the referenced project and see.

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/issues/46622

**Comment by KristianMariyanov** [comment]
@BrzVlad @lewing Thank you for the quick fix. Will the fix be part of the next preview version of the runtime?

**Comment by BrzVlad** [comment]
Yes, it will be in preview 3.
