### ISSUE TITLE
Test failure System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#83317]
Failed in Run: [runtime-coreclr libraries-jitstress 20230311.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=201752)
 
 **Failed tests:**
 ```
 net8.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.11.Arm64.Open
     - System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static
 ```
 
 **Error message:**
 ```
Assert.True() Failure
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 274
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
 ```

**Comment by carlossanlop** [comment]
The test is checking if `PerformanceCounterCategory.GetInstanceNames()` returns a number greater than zero. If not, the assert fails.

The test has been failing in this assert since at least 04/25 (unsure if Kusto is deleting results older than that):

<details><summary>Results (expand)</summary>

```
AzureDevOpsTests
| where TestName == "System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static"
and Outcome == "Failed"
| project RunCompleted, TestName, Message, StackTrace, QueueName, BuildReason
```

RunCompleted | TestName | QueueName | BuildReason
-- | -- | -- | --
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:11:52.7100000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-04-25 20:17:31.2130000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.11.arm64.open | PullRequest
2023-05-22 13:55:29.7500000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.10.amd64.open.rt | PullRequest
2023-07-05 12:45:40.5230000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.81.amd64.open.rt | PullRequest
2023-07-05 12:45:40.5230000 | System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static | windows.81.amd64.open.rt | PullRequest

</details>

In 04/25 the message was:

```
System.AggregateException : One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length'))
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
---- System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'length')
```

And then it started showing up like this:

```
Assert.True() Failure
Expected: True
Actual:   False
```

The history of `src/libraries/System.Diagnostics.PerformanceCounter` [does not show any changes in April](https://github.com/dotnet/runtime/commits/main/src/libraries/System.Diagnostics.PerformanceCounter). So I suspect it's the same error (the array length was not larger than zero, it was zero, so it's technically out of the range of valid values... it was an unhelpful message).

While I investigate the potential root cause, I'm going to change it to `AssertExtensions.GreaterThan` and will add a meaningful message argument.

**Comment by carlossanlop** [comment]
The code tries to get the "Processor" performance counter category from the registry and then tries to get the list of all the elements under this category. The test seems to be failing very rarely to get such list. May be some configuration problem in the computer. The test even has several retries.

I'll modify the test so we get a more meaningful error message that we can attach to KnownBuildError properly.

**Comment by carlossanlop** [comment]
Also wanted to mention that I've seen a few cases in related areas that need the process to be elevated in arm64 for the feature to work. Something we could consider.
