### ISSUE TITLE
Microsoft.Extensions.Configuration.ConfigurationBinder.Bind Method ignored all the exceptions.

### ISSUE THREAD

**Issue by codelovercc** [dotnet/runtime#83385]
### Description

Microsoft.Extensions.Configuration.ConfigurationBinder.Bind Method ignored all the exceptions. If there is any Exceptions thrown, it will be ignored, that makes harder to find where is going wrong.

### Reproduction Steps

appsettings.json

```json
{
     "WebSitesOptions":{
         "WebSites": {
               "0": {
                "Name": "Shop mall",
                "Url": "https://shop***.com"
              }
          }
     }
}
```

WebSite.cs
```C#
public class WebSite
{
    public string Name { get; set; }

    public Uri? Url {get; set;}
}
```

WebSitesOptions.cs
```C#
public class WebSitesOptions
{
    public WebSite[] WebSites { get; set; }
}
```

Add Options to IServiceCollection
```C#
public static IServiceCollection AddWebSitesOptions(IServiceCollection services, IConfiguration config)
{
    services.AddOptions<WebSitesOptions>().Bind(config).ValidateDataAnnotations();
    return services;
}
```

Now let's run it, take a look in to appsettings.json `"Url": "https://shop***.com"` . `https://shop***.com` is an invalid Url. It means that `https://shop***.com` can not convert to a Url instance and an InvalidOperationException was created and thrown when binding the config to WebSite instance. But Microsoft.Extensions.Configuration.ConfigurationBinder.Bind Method ignored all the exceptions, finally I get a `WebSitesOptions` with an empty array of `WebSite`, and no one tells me there is an exception when binding.

Here is a code segment of Microsoft.Extensions.Configuration.ConfigurationBinder.Bind Method

```C#
            foreach (IConfigurationSection section in config.GetChildren())
            {
                var itemBindingPoint = new BindingPoint();
                try
                {
                    BindInstance(
                        type: elementType,
                        bindingPoint: itemBindingPoint,
                        config: section,
                        options: options);
                    if (itemBindingPoint.HasNewValue)
                    {
                        arguments[0] = itemBindingPoint.Value;

                        addMethod.Invoke(instance, arguments);
                    }
                }
                catch
                {
                     //Here! all exceptions are ignored!
                }
            }
```

If we change class WebSite like below

```C#
public class WebSite
{
    public string Name { get; set; }

    [Url] // to validate the value is correct.
    public string? Url {get; set;}
}
```

Rerun the code. `https://shop***.com` passed the `UrlAttribute` validation, But `https://shop***.com` is not a valid Url. Because the string starts with 'http', 'https' or 'ftp', it will pass the verification of `UrlAttribute`.

### Expected behavior

If option binding fails, an exception should be thrown to notify the caller.

### Actual behavior

Nothing happened,like it works fine, actually the value of the option is incorrect.

### Configuration

.Net 7.0.0
MacOS BigSur 11.7
Intel Core i7

**Comment by tarekgh** [comment]
@codelovercc we have fixed this in `.NET 8`. You can try the following:

Reference .NET 8 libraries, like:

```Xml
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0-preview.2.23128.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.2.23128.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0-preview.2.23128.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0-preview.2.23128.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0-preview.2.23128.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-preview.2.23128.3" /> 
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0-preview.2.23128.3" /> 
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations " Version="8.0.0-preview.2.23128.3" />
```

and change the following line in your code:

```diff
- services.AddOptions<WebSitesOptions>().Bind(config).ValidateDataAnnotations();
+ services.AddOptions<WebSitesOptions>().Bind(config, o => o.ErrorOnUnknownConfiguration = true).ValidateDataAnnotations();
```

You should get the exception like:

```
System.InvalidOperationException
  HResult=0x80131509
  Message='ErrorOnUnknownConfiguration' was set and binding has failed. The likely cause is an invalid configuration value.
  Source=Microsoft.Extensions.Configuration.Binder
  StackTrace:
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindArray(Type type, IEnumerable source, IConfiguration config, BinderOptions options) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 756
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 310
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 268
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 237
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 408
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs:line 142
   at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options) in /_/src/libraries/Microsoft.Extensions.Options.ConfigurationExtensions/src/NamedConfigureFromConfigurationOptions.cs:line 38
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options) in /_/src/libraries/Microsoft.Extensions.Options/src/ConfigureNamedOptions.cs:line 49
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name) in /_/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs:line 62
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value() in /_/src/libraries/Microsoft.Extensions.Options/src/UnnamedOptionsManager.cs:line 30
   at NetCoreApp.Program.Main(String[] args) in C:\Temp\NetCoreApp\Program.cs:line 69

  This exception was originally thrown at this call stack:
    System.Uri.CreateThis(string, bool, System.UriKind, System.UriCreationOptions) in UriExt.cs
    System.Uri.Uri(string, System.UriKind) in Uri.cs
    System.UriTypeConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, object) in UriTypeConverter.cs
    Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(System.Type, string, string, out object, out System.Exception) in ConfigurationBinder.cs

Inner Exception 1:
InvalidOperationException: Failed to convert configuration value at 'WebSitesOptions:WebSites:0:Url' to type 'System.Uri'.

Inner Exception 2:
UriFormatException: Invalid URI: The hostname could not be parsed.
```

**Comment by codelovercc** [comment]
Thank you! All of you are doing a great job.
