### ISSUE TITLE
Test failure: Fatal error. Internal CLR error at System.GC.AllocateNewArray

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#83407]
Run: [runtime-coreclr outerloop 20230312.3](https://dnceng-public.visualstudio.com/public/_build/results?buildId=201955)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open
-Interop\\PInvoke\\CriticalHandles\\StructTest\\StructTest\\StructTest.cmd
```

Error Message:
```
Fatal error. Internal CLR error. (0x80131506)
at System.GC.AllocateNewArray(IntPtr, Int32, GC_ALLOC_FLAGS)
at System.Text.StringBuilder.ExpandByABlock(Int32)
at System.Text.StringBuilder.Append(Char, Int32)
at System.Text.StringBuilder.Append(Char)
at System.Diagnostics.StackTrace.ToString(TraceFormat, System.Text.StringBuilder)
at System.Diagnostics.StackTrace.ToString(TraceFormat)
at System.Exception.get_StackTrace()
at System.Exception.ToString()
at Internal.JitInterface.CorInfoImpl.AllocException(System.Exception)
at Internal.JitInterface.CorInfoImpl._resolveToken(IntPtr, IntPtr*, Internal.JitInterface.CORINFO_RESOLVED_TOKEN*)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation+<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore`1<ILCompiler.DependencyAnalysis.NodeFactory>, Int32)
at ILCompiler.ReadyToRunCodegenCompilation+<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32)
at ILCompiler.ReadyToRunCodegenCompilation+<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(System.Object)
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      C:\h\w\A8B5093A\w\B0BC097D\uploads\Reports\Interop.PInvoke\CriticalHandles\StructTest\StructTest\StructTest.output.txt
Raw output:
BEGIN EXECUTION
CriticalHandlesNative.dll
StructTest.dll
TestLibrary.dll
3 file(s) copied.
2:43:41.13
Response file: C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\CriticalHandlesNative.dll.rsp
C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\IL-CG2\CriticalHandlesNative.dll
-o:C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\CriticalHandlesNative.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A8B5093A\p\System..dll
-r:C:\h\w\A8B5093A\p\Microsoft..dll
-r:C:\h\w\A8B5093A\p\mscorlib.dll
-r:C:\h\w\A8B5093A\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A8B5093A\p\crossgen2\crossgen2.dll" @"C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\CriticalHandlesNative.dll.rsp"   -r:C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\IL-CG2*.dll"
No input files are loadable
2:43:41.55
2:43:41.55
Response file: C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\StructTest.dll.rsp
C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\IL-CG2\StructTest.dll
-o:C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\StructTest.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A8B5093A\p\System..dll
-r:C:\h\w\A8B5093A\p\Microsoft..dll
-r:C:\h\w\A8B5093A\p\mscorlib.dll
-r:C:\h\w\A8B5093A\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A8B5093A\p\crossgen2\crossgen2.dll" @"C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\StructTest.dll.rsp"   -r:C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTest\StructTest\StructTest.dll
" "dotnet" "C:\h\w\A8B5093A\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A8B5093A\w\B0BC097D\e\Interop\PInvoke\CriticalHandles\StructTe
```

Stack trace:
```
   at Interop_PInvoke._CriticalHandles_StructTest_StructTest_StructTest_._CriticalHandles_StructTest_StructTest_StructTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
cc @jakobbotsch if it is related to our struct work.

**Comment by JulieLeeMSFT** [comment]
Also failed in run [20230311.4](https://dnceng-public.visualstudio.com/public/_build/results?buildId=201699).

**Comment by EgorBo** [comment]
Duplicates https://github.com/dotnet/runtime/issues/81109 ?
