### ISSUE TITLE
[wasm] System.Runtime.Tests failing in debug builds on main

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#83415]
Truncated test output:
```
  info: console.debug: MONO_WASM: all assets are loaded in wasm memory
  info: console.debug: MONO_WASM: mono_wasm_load_runtime
  info: MONO_WASM: mono_wasm_load_runtime () failed: {}
  info: MONO_WASM: Stacktrace:
  info: 
  info: RuntimeError: memory access out of bounds
  info:     at strlen (strlen (wasm://wasm/02f69622:wasm-function[15041]:0x2ffc88))
  info:     at monoeg_strdup.10 (monoeg_strdup.10 (wasm://wasm/02f69622:wasm-function[2089]:0x91072))
  info:     at mono_runtime_register_appctx_properties (mono_runtime_register_appctx_properties (wasm://wasm/02f69622:wasm-function[2088]:0x91011))
  info:     at monovm_initialize (monovm_initialize (wasm://wasm/02f69622:wasm-function[14348]:0x2db4bc))
  info:     at mono_wasm_load_runtime (mono_wasm_load_runtime (wasm://wasm/02f69622:wasm-function[116]:0x8236))
  info:     at Module._mono_wasm_load_runtime (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:23983:114)
  info:     at ccall (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:23487:22)
  info:     at Object.mono_wasm_load_runtime (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:23514:16)
  info:     at mono_wasm_load_runtime (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16438:33)
  info:     at mono_wasm_before_memory_snapshot (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16417:9)
  info:     at onRuntimeInitializedAsync (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16133:19)
  info: 
  info: ==== JS stack trace =========================================
  info: 
  info:     0: builtin exit frame: trace(this=0x33bf00186e65 <console map = 0x33bf00186c81>#0#,0x33bf00186e65 <console map = 0x33bf00186c81>#0#,0x33bf0072ee19 <String[24]: #MONO_WASM: abort_startup>)
  info: 
  info:     1: abort_startup(aka abort_startup) [0x33bf003f9b3d] [/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16203] [bytecode=0x33bf0072eeb1 offset=23](this=0x33bf00000251 <undefined>,0x33bf0046c929 <RuntimeError map = 0x33bf003c6205>#1#,0x33bf00000de1 <false>)
  info:     2: mono_wasm_load_runtime(aka mono_wasm_load_runtime) [0x33bf00703e61] [/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16443] [bytecode=0x33bf003c4e69 offset=157](this=0x33bf00000251 <undefined>,0x33bf003c44a1 <String[6]: #unused>,-1)
  info:     3: mono_wasm_before_memory_snapshot(aka mono_wasm_before_memory_snapshot) [0x33bf003f9c31] [/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16417] [bytecode=0x33bf003c45bd offset=470](this=0x33bf00000251 <undefined>)
  info:     4: onRuntimeInitializedAsync(aka onRuntimeInitializedAsync) [0x33bf003f9b05] [/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16133] [bytecode=0x33bf007547f9 offset=221](this=0x33bf00000251 <undefined>,0x33bf007096c5 <JSFunction userOnRuntimeInitialized (sfi = 0x33bf0039472d)>#2#)
  info:     5: /* anonymous */ [0x33bf00434369](this=0x33bf00183b6d <JSGlobalProxy>#3#,0x33bf00000251 <undefined>)
  info:     6: StubFrame [pc: 0x55a91ff37870]
  info:     7: StubFrame [pc: 0x55a91fe74ae4]
  info:     8: EntryFrame [pc: 0x55a91fe4a187]
  info: =====================
  info: 
  info: * Assertion: should not be reached at /home/kate/Projects/dotnet-runtime-wasm/src/mono/mono/utils/../../mono/utils/mono-threads-coop.h:48
  info: 
  info: Aborted()
  info: MONO_WASM: onRuntimeInitializedAsync() failed: {}
  info: MONO_WASM: Stacktrace:
  info: 
  info: RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
  info:     at abort (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:17913:11)
  info:     at _abort (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:22359:7)
  info:     at monoeg_assert_abort (monoeg_assert_abort (wasm://wasm/02f69622:wasm-function[573]:0x45a18))
  info:     at monoeg_log_default_handler (monoeg_log_default_handler (wasm://wasm/02f69622:wasm-function[588]:0x45f61))
  info:     at monoeg_g_logstr (monoeg_g_logstr (wasm://wasm/02f69622:wasm-function[583]:0x45d7f))
  info:     at monoeg_g_logv_nofree (monoeg_g_logv_nofree (wasm://wasm/02f69622:wasm-function[581]:0x45ccc))
  info:     at monoeg_assertion_message (monoeg_assertion_message (wasm://wasm/02f69622:wasm-function[585]:0x45dff))
  info:     at mono_assertion_message_unreachable (mono_assertion_message_unreachable (wasm://wasm/02f69622:wasm-function[587]:0x45e9d))
  info:     at mono_threads_suspend_policy_is_blocking_transition_enabled.1 (mono_threads_suspend_policy_is_blocking_transition_enabled.1 (wasm://wasm/02f69622:wasm-function[1135]:0x5a37a))
  info:     at mono_threads_is_blocking_transition_enabled.1 (mono_threads_is_blocking_transition_enabled.1 (wasm://wasm/02f69622:wasm-function[1138]:0x5a4d3))
  info:     at mono_threads_enter_gc_unsafe_region_unbalanced_with_info (mono_threads_enter_gc_unsafe_region_unbalanced_with_info (wasm://wasm/02f69622:wasm-function[1149]:0x5a9c1))
  info:     at mono_threads_enter_gc_unsafe_region_unbalanced_internal (mono_threads_enter_gc_unsafe_region_unbalanced_internal (wasm://wasm/02f69622:wasm-function[1150]:0x5ab10))
  info:     at mono_jit_cleanup (mono_jit_cleanup (wasm://wasm/02f69622:wasm-function[13741]:0x2afc80))
  info:     at mono_wasm_exit (mono_wasm_exit (wasm://wasm/02f69622:wasm-function[148]:0x8d33))
  info:     at Module._mono_wasm_exit (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:24108:90)
  info:     at mono_wasm_load_runtime (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16446:17)
  info:     at mono_wasm_before_memory_snapshot (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16417:9)
  info:     at onRuntimeInitializedAsync (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16133:19)
  info: 
  info: ==== JS stack trace =========================================
  info: 
  info:     0: builtin exit frame: trace(this=0x33bf00186e65 <console map = 0x33bf00186c81>#0#,0x33bf00186e65 <console map = 0x33bf00186c81>#0#,0x33bf0072ee19 <String[24]: #MONO_WASM: abort_startup>)
  info: 
  info:     1: abort_startup(aka abort_startup) [0x33bf003f9b3d] [/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16203] [bytecode=0x33bf0072eeb1 offset=23](this=0x33bf00000251 <undefined>,0x33bf0046eee1 <RuntimeError map = 0x33bf003c61dd>#1#,0x33bf00000dc5 <true>)
  info:     2: onRuntimeInitializedAsync(aka onRuntimeInitializedAsync) [0x33bf003f9b05] [/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16172] [bytecode=0x33bf007547f9 offset=639](this=0x33bf00000251 <undefined>,0x33bf007096c5 <JSFunction userOnRuntimeInitialized (sfi = 0x33bf0039472d)>#2#)
  info:     3: /* anonymous */ [0x33bf0046f335](this=0x33bf00183b6d <JSGlobalProxy>#3#,0x33bf0046eee1 <RuntimeError map = 0x33bf003c61dd>#1#)
  info:     4: StubFrame [pc: 0x55a91ff379f7]
  info:     5: StubFrame [pc: 0x55a91fe74c2a]
  info:     6: EntryFrame [pc: 0x55a91fe4a187]
  info: =====================
  info: 
  info: RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
  info:     at abort (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:17913:11)
  info:     at _abort (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:22359:7)
  info:     at monoeg_assert_abort (monoeg_assert_abort (wasm://wasm/02f69622:wasm-function[573]:0x45a18))
  info:     at monoeg_log_default_handler (monoeg_log_default_handler (wasm://wasm/02f69622:wasm-function[588]:0x45f61))
  info:     at monoeg_g_logstr (monoeg_g_logstr (wasm://wasm/02f69622:wasm-function[583]:0x45d7f))
  info:     at monoeg_g_logv_nofree (monoeg_g_logv_nofree (wasm://wasm/02f69622:wasm-function[581]:0x45ccc))
  info:     at monoeg_assertion_message (monoeg_assertion_message (wasm://wasm/02f69622:wasm-function[585]:0x45dff))
  info:     at mono_assertion_message_unreachable (mono_assertion_message_unreachable (wasm://wasm/02f69622:wasm-function[587]:0x45e9d))
  info:     at mono_threads_suspend_policy_is_blocking_transition_enabled.1 (mono_threads_suspend_policy_is_blocking_transition_enabled.1 (wasm://wasm/02f69622:wasm-function[1135]:0x5a37a))
  info:     at mono_threads_is_blocking_transition_enabled.1 (mono_threads_is_blocking_transition_enabled.1 (wasm://wasm/02f69622:wasm-function[1138]:0x5a4d3))
  info:     at mono_threads_enter_gc_unsafe_region_unbalanced_with_info (mono_threads_enter_gc_unsafe_region_unbalanced_with_info (wasm://wasm/02f69622:wasm-function[1149]:0x5a9c1))
  info:     at mono_threads_enter_gc_unsafe_region_unbalanced_internal (mono_threads_enter_gc_unsafe_region_unbalanced_internal (wasm://wasm/02f69622:wasm-function[1150]:0x5ab10))
  info:     at mono_jit_cleanup (mono_jit_cleanup (wasm://wasm/02f69622:wasm-function[13741]:0x2afc80))
  info:     at mono_wasm_exit (mono_wasm_exit (wasm://wasm/02f69622:wasm-function[148]:0x8d33))
  info:     at Module._mono_wasm_exit (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:24108:90)
  info:     at mono_wasm_load_runtime (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16446:17)
  info:     at mono_wasm_before_memory_snapshot (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16417:9)
  info: WASM EXIT 1
  info:     at onRuntimeInitializedAsync (/home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/dotnet.js:16133:19)
  info: // jitted 0 bytes; 0 traces (0 candidates, NaN%); 0 jit_calls (NaN% direct); 0 interp_entries
  info: // time: 0ms generating, 0ms compiling wasm. 0 null checks eliminated. 0 back-branches emitted (0 failed, NaN%)
  info: exiting due to exception: RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
  info: Process v8 exited with 1
        
  info: Waiting to flush log messages with a timeout of 120 secs ..
  fail: Application has finished with exit code 1 but 0 was expected
  XHarness exit code: 71 (GENERAL_FAILURE)
  ~/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle ~/Projects/dotnet-runtime-wasm/src/libraries/System.Runtime/tests
  ----- end Tue 14 Mar 2023 01:33:44 PM PDT ----- exit code 71 ----------------------------------------------------------
  XHarness artifacts: /home/kate/Projects/dotnet-runtime-wasm/artifacts/bin/System.Runtime.Tests/Debug/net8.0-browser/browser-wasm/AppBundle/xharness-output
```

Fails consistently in strlen. This started happening once I bumped to latest main, things were OK a day or two ago.

**Comment by lewing** [comment]
@pavelsavara please take a look and triage as appropriate

**Comment by pavelsavara** [comment]
Work on my machine™️, but debug build is quite slow to run the tests.
Windows, V8 version: 11.5.3

```
build.cmd -bl -os browser -subset mono+libs -c Debug
dotnet.cmd build /p:TargetOS=browser /p:TargetArchitecture=wasm /p:Configuration=Debug src\libraries\System.Runtime\tests\ /t:Test
```

```
  info: Finished:    System.Runtime.Tests.dll
  info:
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 63457, Errors: 0, Failed: 0, Skipped: 98, Time: 1561.5430919s
```

Feel free to re-open
