### ISSUE TITLE
System.Net.Http.WinHttpHandler.StartRequestAsync assertion failed

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#83486]
Found in this unrelated main PR: https://github.com/dotnet/runtime/pull/83356

- Queue: `Libraries Test Run release coreclr windows x64 Debug`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=206231&view=logs&j=cb131f87-d5af-5ecc-6e5f-6dc86994859c&t=76503e0a-8c41-542c-43da-63a4758a95b0
- Log file: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83356-merge-e4bc4ff8fcbb43f780/System.Net.Http.WinHttpHandler.Functional.Tests/1/console.83bcb5b4.log?helixlogtype=result

Callstack:
```
Process terminated. Assertion failed.
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 885
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<>c.<SendAsync>b__118_0(Object s) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 614
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 267
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2353
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
```

Here is the assert that fails:
https://github.com/dotnet/runtime/blob/13733cdd969842de9c36235d730a604ce55ee729/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L885

**Comment by stephentoub** [comment]
At quick glance it looks like this could happen if the WinHttpHandler is Dispose'd concurrently with a request being initiated, as Dispose nulls out the session handle.  That seems bogus; it should probably not null out the handle.  Even if the assert were removed, subsequent code tries to use the session handle and would null ref, which we don't want either.  If we instead just dispose of the handle but don't null it out, use of the handle will result in an ObjectDisposedException, which is much more diagnosable.

**Comment by ManickaP** [comment]
Triage: seems like fairly straightforward fix, we should do it in 8.0.
