### ISSUE TITLE
PLINQ query crashes a .NET Core 6 application due to unhandled InvalidCastException thrown from System.Threading.Tasks.Task.RunContinuations.

### ISSUE THREAD

**Issue by mhinkka** [dotnet/runtime#83520]
### Description

I have a Web API application hosted in IIS that sorts rows of an array (actually a two-dimensional array/table of objects: object[][]) using expressions similar to this:

`rows.AsParallel().AsOrdered().WithCancellation(cts.Token).OrderBy(...).ThenBy(...).ToList()` 

The application has built-in support for canceling any running sorting operation at any point. This cancellation performs cancellation for the thread that is sorting the array using a call to Thread.Interrupt-function as well as calling CancellationTokenSource.Cancel for the CancellationTokenSource (cts). I want to use both methods as I can't pass the cancellation token into all the places these cancellable operations could call (Including, e.g., third-party components).

We have been getting intermittent unhandled System.InvalidCastException exceptions from System.Threading.Tasks.Task.RunContinuations crashing the whole application in situations that have the following issues in common:

1. PLINQ sorting operation is being run.
2. The sorting operation has been interrupted with the ThreadInterruptException.
3. An unhandled exception was thrown from System.Threading.Tasks.Task.RunContinuations.
This exception has the following details:

```
System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.ProcessChildCompletion(Task childTask)
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() 
```

In some cases, if the worker thread is using the thread that initiated the PLINQ operation, this stack trace looks different and in that case, this exception could be caught, but this situation seems quite rare as usually parallel tasks are being processed by other threads than the PLINQ caller. Thus, there is no way to catch the exception that occurred in System.Threading.Tasks.Task.RunContinuations, the application terminates.

To me, this seems like a problem in the .NET 6 runtime as I don't see how I can directly affect the continuationObjects being passed to System.Threading.Tasks.Task.RunContinuations.

Can you confirm whether this is an issue in .NET 6 runtime and/or is there some way for me to adjust my application so that this does not occur anymore?

Note also that in the reproducion step-function shown below, the stack trace is slightly different, but the situation is still as fatal as in this production environment case:
```
Application: testhost.exe
CoreCLR Version: 6.0.1523.11507
.NET Version: 6.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.ProcessChildCompletion(Task childTask)
   at System.Threading.Tasks.Task.NotifyParentIfPotentiallyAttachedTask()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Reproduction Steps

I'm not sure if this is minimal, nor whether it replicates in all the environments, but at least in my test environment using .NET 6.0.15 (CoreCLR 6.0.1523.11507) I can replicate this issue reliably by running the code in the following C# function:
```
		public void CrashTest()
		{
			var rnd = new Random();
			var rows = Enumerable.Range(1, 1000000)
				.Select(x => new object[] { $"T{rnd.Next()}" })
				.ToArray();
			var cts = new CancellationTokenSource();

			for (var i = 0; i < 10000; ++i)
			{
				var thread1 = new Thread(() =>
				{
					try
					{
						while (true)
						{
							var _ = rows
								.AsParallel()
								.AsOrdered()
								.WithCancellation(cts.Token)
								.OrderBy(row => row[0])
								.ToList();
						}
					}
					catch (ThreadInterruptedException)
					{
					}
				});

				thread1.Start();
				Thread.Sleep(rnd.Next(100));
				thread1.Interrupt();
				cts.Cancel();
				thread1.Join();
			}
		}

```

### Expected behavior

Application does not crash. 
PLINQ operation is cancelled without threads being killed.

### Actual behavior

An unhandled InvlidCastException is thrown from System.Threading.Tasks.Task.RunContinuations crashing the whole application.

```
Exception generated into windows event log:
Log Name:      Application
Source:        .NET Runtime
Date:          16/03/2023 17.27.19
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Description:
Application: testhost.exe
CoreCLR Version: 6.0.1523.11507
.NET Version: 6.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.ProcessChildCompletion(Task childTask)
   at System.Threading.Tasks.Task.NotifyParentIfPotentiallyAttachedTask()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-16T15:27:19.4485051Z" />
    <EventRecordID>160159</EventRecordID>
    <Correlation />
    <Execution ProcessID="12224" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>NB474</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: testhost.exe
CoreCLR Version: 6.0.1523.11507
.NET Version: 6.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.ProcessChildCompletion(Task childTask)
   at System.Threading.Tasks.Task.NotifyParentIfPotentiallyAttachedTask()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&amp; currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
</Data>
  </EventData>
</Event>
```

### Regression?

We didn't have this issue with the same application in .NET Framework 4.7.1.

### Configuration

```
.NET version:       replicates with 6.0.5, 6.0.14, and 6.0.15
Operating system:   "Microsoft Windows NT 10.0.17763.0" and "Microsoft Windows NT 10.0.22621.0"
Process:            64 bit
Operating System:   64 bit
CPU:                "Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz" and "12th Gen Intel(R) Core(TM) i7-12800H Cores: 20"
Cores:              32 and 20 
Memory:             256 GB and 64 GB
```

### Other information

For me it seems that this is most probably thrown from this line in System.Threading.Tasks.Task.RunContinuations:

`List<object?>` continuations = (List<object?>)continuationObject;

**Comment by stephentoub** [comment]
Note that the _vast_ majority of code, including in the core libraries, is not hardened against use of thread interrupts.  These can cause exceptions to emerge from practically any place the thread is in a wait/sleep/join state, which means almost any blocking operation, time acquiring a lock, etc, and most code is not written to accomodate such asynchronous exceptions.

**Comment by mhinkka** [comment]
We originally used Thread.Abort in .NET Framework 4.7.1 but as this was documented to not be a good practice, and as it is no longer supported by .NET 5, we switched to use the often recommended replacement of Thread.Interrupt. Also, we didn't find any clear indication in the .NET documentation that you should avoid using thread interrupts too.

Perhaps some kind of a warning about this issue should then be added to the documentation, e.g., [here](https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread.interrupt) or [here](https://learn.microsoft.com/en-us/dotnet/standard/threading/pausing-and-resuming-threads)?

Also, some kind of workaround proposals in situations where you can't pass cancellation tokens to the code that is blocking in wait/sleep/join state (e.g., code in a third-party component) would be very useful.

**Comment by Clockwork-Muse** [comment]
>Also, some kind of workaround proposals in situations where you can't pass cancellation tokens to the code that is blocking in wait/sleep/join state (e.g., code in a third-party component) would be very useful.

Start it as a separate process, kill the process.  Or yell at those third parties to properly support cancellation.

That said....

> I have a Web API application

Web frameworks usually want to be in control of all the threads that are started (for a variety of reasons), so this feels like a code smell.  Additionally, assuming your web api has any reasonable amount of concurrent requests, the only thing PLINQ is doing is adding overhead to everybody's requests, and making things slower than if you'd done it with regular LINQ.

**Comment by theodorzoulias** [comment]
> Also, some kind of workaround proposals in situations where you can't pass cancellation tokens to the code that is blocking in wait/sleep/join state (e.g., code in a third-party component) would be very useful.

.NET 7 introduced the [`ControlledExecution.Run`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.controlledexecution.run) API, that can be used to abort an `Action` using a `CancellationToken`. This method uses [internally](https://github.com/dotnet/runtime/blob/3286b32e11dcd5b55994a193c6d0716c581724e3/src/coreclr/System.Private.CoreLib/src/System/Runtime/ControlledExecution.CoreCLR.cs#L43) the `Thread.Abort` mechanism to stop the action, and then resets the abort so that the thread doesn't actually die. It's a dangerous API, and Microsoft does not recommend using it in production code. You can find [here](https://stackoverflow.com/questions/75087774/thread-or-task-stopping-a-hung-single-line-of-code/75090418#75090418 "Thread or Task (stopping a hung single line of code)") a variant of this API that uses the `Thread.Interrupt` instead of the `Thread.Abort` (the `RunInterruptible` method).

**Comment by Clockwork-Muse** [comment]
@theodorzoulias - as mentioned earlier, a version that uses `Thread.Interrupt()` is going to run into many of the same problems as the one that uses `Thread.Abort()`, so both of those are still dangerous.

**Comment by sleushunou** [comment]
I faced with similar issue on prod
https://github.com/dotnet/runtime/issues/114262

**Comment by jjacksoncapula** [comment]
We experienced a similar issue. Running on dotnet 9.0.1 on Windows. Stack trace as follows:

```
2025-05-15 14:44:07,672 [347] FATAL ServiceHost<Position> - Fatal unhandled exception! Service will be terminated
System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

I previously commented on [https://github.com/dotnet/runtime/issues/114262](url) but was informed by @lateralusX that this is more at home here.

Our theory is that because our code is -in essence- doing:
while (true)
{
await DoSomething();
await DoStuffAsync();
}
async Task DoStuffAsync()
{
if (false)
await DoMoreStuffAsync();
}

The "await DoStuffAsync();" is in effect awaiting on a NOP which is very very fast and maybe even removed completely by the compiler and/or the JIT. We speculate that this is fast enough to trigger a race condition so the continuation is finished and we do hit the issue as described.

So - in our own code - we have replaced "await NOP" with "await Task.Completed" which we hope will help, but we don't have a way to prove it.

**Comment by stephentoub** [comment]
Are you using Thread.Interrupt?

**Comment by jjacksoncapula** [comment]
No - we do not use that anywhere

**Comment by stephentoub** [comment]
Can you share a repro?

**Comment by jjacksoncapula** [comment]
We can't reproduce - we just saw the error on our production server (after the app died due to unhandled exception). Unfortunately all we have to go off is the logs posted above.

**Comment by jjacksoncapula** [comment]
We experienced the same issue again today. This time I can see it was during a 4s garbage collection. Mentioning in case the provides any further useful context. 

```
2025-07-15 13:06:05,648 [41] FATAL ServiceHost<Position> - Fatal unhandled exception! Service will be terminated
System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2025-07-15 13:06:09,709 [GC Notifications] INFO  Alvitas.Common.Util.GcManagement - FullGCComplete: Succeeded
2025-07-15 13:06:09,710 [GC Notifications] INFO  Alvitas.Common.Util.GcManagement - Index: 5193, Pauses: 00:00:04.0602930,00:00:00, Compacted: True, Generation: 2, Total memory available: 96635740160
```

**Comment by tannergooding** [comment]
I think this is the same as https://github.com/dotnet/runtime/issues/114262 which was repro'ing on iOS.

A small fix was applied via https://github.com/dotnet/runtime/pull/115659 and recently backported

CC. @stephentoub

**Comment by stephentoub** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/114262. We can re-open if it continues even after the applied fix.
