### ISSUE TITLE
CI failures on System.Runtime.Serialization.Xml.Tests

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#83551]
Non-blocking failures in System.Runtime.Serialization.Xml.Tests.dll. May be related to https://github.com/dotnet/runtime/issues/82561

Encountered on https://github.com/dotnet/runtime/pull/82453, https://github.com/dotnet/runtime/pull/83519 and other PRs

```
System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export(testname: "Exp2", export: Action`1 { Method = Void <Export_MemberData>b__7_2(System.Runtime.Serialization.XsdDataContractExporter), Target = <>c { } }, schemaCheck: Action`2 { Method = Void <Export_MemberData>b__3(System.String, System.Xml.Schema.XmlSchemaSet), Target = <>c__DisplayClass7_0 { autoImportKVP = False } })

DataContractSerializerTests.DCS_MemoryStream_Serialize_UsesBuiltInAdapter

DataContractSerializerTests.DCS_FileStreamSurrogate
```

Logs
```
[1.0.0-prerelease.23157.1+1845890ce4b9ebb3c0807508e4ad65bed24aa8fd] XHarness command issued: wasi test --app=. --output-directory=/root/helix/work/workitem/uploads/xharness-output --engine-arg=--dir=. --timeout=00:30:00 -- dotnet.wasm WasmTestRunner managed/System.Runtime.Serialization.Xml.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[20:24:07] info: Using wasm engine WasmTime from path /root/helix/work/correlation/wasmtime/wasmtime
[20:24:07] info: wasmtime-cli 5.0.0
[20:24:07] info: 
[20:24:07] info: Running /root/helix/work/correlation/wasmtime/wasmtime --dir=. dotnet.wasm WasmTestRunner managed/System.Runtime.Serialization.Xml.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[20:24:10] info: Discovering: managed/System.Runtime.Serialization.Xml.Tests.dll (method display = ClassAndMethod, method display options = None)
[20:24:11] info: Discovered:  managed/System.Runtime.Serialization.Xml.Tests.dll (found 276 of 279 test cases)
[20:24:11] info: Using random seed for test cases: 169084759
[20:24:11] info: Using random seed for collections: 169084759
[20:24:11] info: Starting:    managed/System.Runtime.Serialization.Xml.Tests.dll
[20:24:11] fail: [FAIL] DataContractSerializerTests.DCS_FileStreamSurrogate
[20:24:11] info: System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/2mqjcaob.j3o_DCS_FileStreamSurrogate_4046'.
[20:24:11] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo , String , Boolean )
[20:24:11] info:    at Interop.CheckIo(Error , String , Boolean )
[20:24:11] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , OpenFlags , Int32 , Func`4 )
[20:24:11] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , UnixFileMode , Int64& , UnixFileMode& , Func`4 )
[20:24:11] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 , Func`4 )
[20:24:11] info:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 )
[20:24:11] info:    at System.IO.Strategies.UnixFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 )
[20:24:11] info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 )
[20:24:11] info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 , Nullable`1 )
[20:24:11] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
[20:24:11] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
[20:24:11] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
[20:24:11] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare )
[20:24:11] info:    at MyFileStream..ctor(String fileName)
[20:24:11] info:    at DataContractSerializerTests.DCS_FileStreamSurrogate()
[20:24:11] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
[20:24:11] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
[20:24:15] fail: [FAIL] DataContractSerializerTests.DCS_MemoryStream_Serialize_UsesBuiltInAdapter
[20:24:15] info: XML comparison is also failing
[20:24:15] info: Test failed for input: System.IO.MemoryStream
[20:24:15] info: Expected: <MemoryStream xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/System.IO"><__identity i:nil="true" xmlns="http://schemas.datacontract.org/2004/07/System" /><_buffer></_buffer><_capacity>0</_capacity><_expandable>false</_expandable><_exposable>true</_exposable><_isOpen>true</_isOpen><_length>0</_length><_origin>0</_origin><_position>0</_position><_writable>true</_writable></MemoryStream>
[20:24:15] info: Actual: <MemoryStream xmlns="http://schemas.datacontract.org/2004/07/System.IO" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><_buffer/><_capacity>0</_capacity><_expandable>false</_expandable><_exposable>true</_exposable><_isOpen>true</_isOpen><_length>0</_length><_origin>0</_origin><_position>0</_position><_writable>true</_writable></MemoryStream>
[20:24:15] info: Expected: True
[20:24:15] info: Actual:   False
[20:24:15] info:    at System.Runtime.Serialization.Tests.DataContractSerializerHelper.SerializeAndDeserialize[MemoryStream](MemoryStream value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare, Boolean verifyBinaryRoundTrip)
[20:24:15] info:    at DataContractSerializerTests.<DCS_MemoryStream_Serialize_UsesBuiltInAdapter>g__ValidateObject|238_0(MemoryStream original, String expectedXml, Byte[] expectedData, Int32 expectedPosition, Boolean expectedExposable)
[20:24:15] info:    at DataContractSerializerTests.DCS_MemoryStream_Serialize_UsesBuiltInAdapter()
[20:24:15] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
[20:24:15] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
[20:24:18] fail: [FAIL] System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export(testname: "Exp2", export: Action`1 { Method = Void <Export_MemberData>b__7_2(System.Runtime.Serialization.XsdDataContractExporter), Target = <>c { } }, schemaCheck: Action`2 { Method = Void <Export_MemberData>b__3(System.String, System.Xml.Schema.XmlSchemaSet), Target = <>c__DisplayClass7_0 { autoImportKVP = False } })
[20:24:18] info: Assert.Equal() Failure
[20:24:18] info: Expected: 20
[20:24:18] info: Actual:   4
[20:24:18] info:    at System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.<>c__DisplayClass7_0.<Export_MemberData>b__3(String s, XmlSchemaSet ss)
[20:24:18] info:    at System.Runtime.Serialization.Xml.XsdDataContractExporterTests.ExporterApiTests.Export(String testname, Action`1 export, Action`2 schemaCheck)
[20:24:18] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
[20:24:18] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
[20:24:19] info: Finished:    managed/System.Runtime.Serialization.Xml.Tests.dll
[20:24:19] info: 
[20:24:19] info: === TEST EXECUTION SUMMARY ===
[20:24:19] info: Total: 332, Errors: 0, Failed: 3, Skipped: 3, Time: 7.8821065s
[20:24:19] info: 
[20:24:19] info: Received expected 142625 of /root/helix/work/workitem/uploads/xharness-output/testResults.xml
[20:24:19] info: Finished writing 142625 bytes of RESULTXML
[20:24:19] info: Xml file was written to the provided writer.
[20:24:19] info: Tests run: 332 Passed: 326 Inconclusive: 0 Failed: 3 Ignored: 0 Skipped: 3
[20:24:19] info: Process wasmtime exited with 1
[20:24:19] info: Waiting to flush log messages with a timeout of 120 secs ..
[20:24:19] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "[FAIL] DataContractSerializerTests.DCS_FileStreamSurrogate",
  "BuildRetry": false
}
```

**Comment by StephenMolloy** [comment]
DCS_FileStreamSurrogate is fixed.

The other two tests are still disabled in trimmed scenarios - being tracked by #73961. I'm using that bug for now.
