### ISSUE TITLE
Test failure JIT\\Directed\\debugging\\debuginfo\\tester\\tester.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#83575]
Run: [runtime-coreclr outerloop 20230316.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=208004&view=ms.vss-test-web.build-test-results-tab&runId=3857155&resultId=120073&paneView=debug)

Failed test:
```
coreclr windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\Directed\\debugging\\debuginfo\\tester\\tester.cmd
```
**Error message:**
```
Assert failure(PID 356 [0x00000164], Thread: 2688 [0x0a80]): ep_rt_volatile_load_uint32_t (&buffer->state) == (uint32_t)EP_BUFFER_STATE_READ_ONLY

CORECLR! ep_buffer_free + 0x24 (0x7049e63f)
CORECLR! buffer_manager_deallocate_buffer + 0x3A (0x7049cc36)
CORECLR! ep_buffer_manager_deallocate_buffers + 0xE0 (0x7049ec4c)
CORECLR! ep_buffer_manager_free + 0x12 (0x7049edef)
CORECLR! ep_session_free + 0x42 (0x704a4c02)
CORECLR! disable_holding_lock + 0x169 (0x7049db66)
CORECLR! disable_helper + 0x9D (0x7049d978)
CORECLR! ep_disable + 0x78 (0x704a02b2)
CORECLR! eventpipe_protocol_helper_stop_tracing + 0x3B (0x704abe33)
CORECLR! ds_eventpipe_protocol_helper_handle_ipc_message + 0x40 (0x704a8665)
File: D:\a_work\1\s\src\native\eventpipe\ep-buffer.c Line: 60
Image: C:\h\w\ABA409E3\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\ABA409E3\w\B7DF0A10\uploads\Reports\JIT.Directed\debugging\debuginfo\tester\tester.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\ABA409E3\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  tester.dll
0.1s: ==TEST STARTING==
1.7s: Started sending sentinel events...
1.8s: Connecting to EventPipe...
2.9s: Creating EventPipeEventSource...
3.0s: EventPipeEventSource created
3.2s: Dynamic.All callback registered
3.2s: Running optional trace validator
4.0s: Finished running optional trace validator
4.0s: Starting stream processing...
5.4s: Saw new provider 'Microsoft-Windows-DotNETRuntime'
7.4s: Saw sentinel event
7.4s: Stopped sending sentinel events
7.4s: Starting event generating action...
7.4s: Stopping event generating action
7.5s: Sending StopTracing command...
7.9s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
8.4s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 3/17/2023 2:41:31 AM
Processing C:\cores\corerun.exe.356.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\ABA409E3\t\tmpjxu351.tmp" -z "C:\cores\corerun.exe.356.dmp"
stdout:
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\cores\corerun.exe.356.dmp]
User Mini Dump File with Full Memory: Only application data is available

************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\ABA409E3\p\PDB
Symbol search path is: C:\h\w\ABA409E3\p\PDB
Executable search path is:
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Fri Mar 17 02:41:51.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:06:39.735
Process Uptime: 0 days 0:00:18.000
................................................................
...

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(164.a80): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=055ce338 ebx=00000000 ecx=00000000 edx=00000000 esi=055ce2e8 edi=055ce338
eip=703bd37e esp=055ce61c ebp=055cf6b4 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=005


Stack trace
   at JIT_Directed._debugging_debuginfo_tester_tester_._debugging_debuginfo_tester_tester_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by davmason** [comment]
I looked in to this a bit, the assert is failing because as we're tearing down the buffer manager we find a buffer that has a single event in it and is still writeable, when it should have been converted to readonly as part of `ep_buffer_manager_write_all_buffers_to_file_v4`. I don't have anything further at the moment

CC @lateralusX

**Comment by lateralusX** [comment]
@davmason Sounds like this is a candidate getting fixed by https://github.com/dotnet/runtime/pull/86180 as well?
