### ISSUE TITLE
MetadataLoadContext: IsValueType: NotSupportedException: Modified types do not support this member

### ISSUE THREAD

**Issue by ericsink** [dotnet/runtime#83679]
### Description

I just updated some things to net8.0 preview 2 with System.Reflection.MetadataLoadContext preview 2.  I'm using S.R.MDLC to load all the reference assemblies and process them.

There are several places now where I am now seeing the following exception:

```
Unhandled exception: System.NotSupportedException: Modified types do not support this member. Use the UnderlyingSystemType property to call this member.
   at System.Reflection.RoModifiedType.Equals(Type other)
   at System.Reflection.TypeLoading.RoType.ComputeBaseTypeClassification()
   at System.Reflection.TypeLoading.RoType.IsValueTypeImpl()
   at System.Reflection.NullabilityInfoContext.GetNullabilityInfo(MemberInfo memberInfo, Type type, NullableAttributeStateParser parser, Int32& index)
   at System.Reflection.NullabilityInfoContext.Create(ParameterInfo parameterInfo)
```

The exception is thrown when I try to retrieve nullability info for a parameter, but it can also be triggered by simply using IsValueType.

One place it happens is on the `value` parameter of `System.Runtime.InteropServices.SequenceMarshal.TryRead`.  There are several others.  The repro project will dump out a list of them.

I'm just coming up to speed on the new "modified types" stuff, and I see that they don't support equality, and that's what the exception is saying.  What I cannot figure out is why a modified type is in play here.  Or how I might detect that situation and use the APIs differently to avoid the problem.

### Reproduction Steps

[repro.zip](https://github.com/dotnet/runtime/files/11021185/repro.zip)

Run this console app with the path of the targeting pack as its first argument.  For example:

```
dotnet run /usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/8.0.0-preview.2.23128.3/ref/net8.0
```

### Expected behavior

IsValueType on the parameter type should not throw.

### Actual behavior

System.NotSupportedException: Modified types do not support this member. 

### Regression?

Yes, I think this is a regression of sorts.

The crash does NOT occur with System.Reflection.MetadataLoadContext 8.0.0-preview.1.23110.8

The crash DOES occur with System.Reflection.MetadataLoadContext 8.0.0-preview.2.23128.3

### Configuration

.NET 8 Preview 2

macOS arm64

I haven't tried this on Windows or Linux yet.

**Comment by steveharter** [comment]
@ericsink thanks for the wonderful repro.
