### ISSUE TITLE
[Mono] linux-arm64 System.Numerics.Vector.Tests assertion: wrong maximal instruction length of instruction storex_membase (expected 12, got 16)

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#83780]
## Build Information
[System.Numerics.Vectors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=213517&view=ms.vss-test-web.build-test-results-tab&runId=3967018&resultId=200482)

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=213517&view=ms.vss-test-web.build-test-results-tab&runId=3967018&resultId=200482&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
Leg Name: net8.0-linux-Release-arm64-Mono_release

Console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-74a8be5a5c5f471383/System.Numerics.Vectors.Tests/1/console.acff6844.log?helixlogtype=result

<pre>
wrong maximal instruction length of instruction storex_membase (expected 12, got 16)
* Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini-arm64.c:5150
</pre>

<details>
<pre>
Thread 10 (Thread 0xff19ea62d1b0 (LWP 32) ".NET Long Runni"):
#0  0x0000ff19f539477c in __GI___wait4 (pid=<optimized out>, stat_loc=0xff19ea6262b0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x0000ff19f5017ce4 in dump_native_stacktrace (signal=<optimized out>, mctx=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:843
#2  mono_dump_native_crash_info (signal=<optimized out>, mctx=0xff19ea626ce0, info=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:870
#3  0x0000ff19f4fcdf68 in mono_handle_native_crash (signal=0xff19f4ed9cee "SIGABRT", mctx=0xff19ea626ce0, info=0xff19ea627020) at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:2979
#4  0x0000ff19f50173f0 in sigabrt_signal_handler (_dummy=6, _info=0xff19ea627020, context=0xff19ea6270a0) at /__w/1/s/src/mono/mono/mini/mini-posix.c:225
#5  <signal handler called>
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x0000ff19f5310aa0 in __GI_abort () at abort.c:79
#8  0x0000ff19f50aec80 in monoeg_assert_abort () at /__w/1/s/src/mono/mono/eglib/goutput.c:57
#9  0x0000ff19f50bef2c in mono_log_write_logfile (log_domain=<optimized out>, level=G_LOG_LEVEL_ERROR, hdr=<optimized out>, message=0xff19c80ffe60 "* Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini-arm64.c:5150\n") at /__w/1/s/src/mono/mono/utils/mono-log-common.c:146
#10 0x0000ff19f50af030 in monoeg_g_logstr (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, msg=0x0) at /__w/1/s/src/mono/mono/eglib/goutput.c:151
#11 monoeg_g_logv_nofree (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=...) at /__w/1/s/src/mono/mono/eglib/goutput.c:166
#12 0x0000ff19f50af148 in monoeg_assertion_message (format=0x0) at /__w/1/s/src/mono/mono/eglib/goutput.c:207
#13 0x0000ff19f50af1a8 in mono_assertion_message_unreachable (file=0xff19ea628298 "", line=0) at /__w/1/s/src/mono/mono/eglib/goutput.c:234
#14 0x0000ff19f500d638 in mono_arch_output_basic_block (cfg=<optimized out>, bb=0xff19c80ec340) at /__w/1/s/src/mono/mono/mini/mini-arm64.c:5150
#15 0x0000ff19f4f2c09c in mono_codegen (cfg=0xff19c80e5c30) at /__w/1/s/src/mono/mono/mini/mini.c:2076
#16 0x0000ff19f4f2eb24 in mini_method_compile (method=<optimized out>, opts=374417919, flags=JIT_FLAG_RUN_CCTORS, parts=0, aot_method_index=-1) at /__w/1/s/src/mono/mono/mini/mini.c:3932
#17 0x0000ff19f4f2fe5c in mono_jit_compile_method_inner (method=0xff19d812e3e0, opt=-362642792, error=0xff19ea629430) at /__w/1/s/src/mono/mono/mini/mini.c:4126
#18 0x0000ff19f4f34b80 in mono_jit_compile_method_with_opt (method=0xff19d812e3e0, opt=374417919, jit_only=1, error=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2718
#19 jit_compile_method_with_opt_cb (arg=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2773
#20 jit_compile_method_with_opt (params=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2789
#21 0x0000ff19f4f38900 in mono_jit_compile_method_jit_only (method=<optimized out>, error=0xff19ea629430) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:2827
#22 mono_jit_runtime_invoke (method=0xff19d812e3e0, obj=<optimized out>, params=0x0, exc=0x0, error=0xff19ea629430) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:3388
#23 0x0000ff19f513d8e8 in do_runtime_invoke (method=0xff19d812e3e0, obj=0xff19f46d95d0, params=0x0, exc=0x0, error=0xff19ea629430) at /__w/1/s/src/mono/mono/metadata/object.c:2545
#24 mono_runtime_invoke_checked (method=0xff19d812e3e0, obj=0xff19f46d95d0, params=0x0, error=0xff19ea629430) at /__w/1/s/src/mono/mono/metadata/object.c:2761
#25 0x0000ff19f5146b5c in mono_runtime_try_invoke_byrefs (method=0xff19d812e3e0, obj=0xff19ea628298, params_byref=0x0, exc=0x0, error=0xff19ea629430) at /__w/1/s/src/mono/mono/metadata/object.c:5145
#26 0x0000ff19f50fee60 in ves_icall_InternalInvoke (method_handle=..., this_arg_handle=..., params_byref=0x0, exception_out=..., error=0xff19ea629430) at /__w/1/s/src/mono/mono/metadata/icall.c:3561
#27 0x0000ff19f51092d4 in ves_icall_InternalInvoke_raw (a0=0xff19ea6294e0, a1=0xff19ea6294e8, a2=0x0, a3=0xff19ea629568) at /__w/1/s/src/mono/mono/metadata/../metadata/icall-def.h:368
#28 0x0000ff19eb8cc7c8 in ?? ()
#29 0x0000ff19f46d95d0 in ?? ()
#30 0x0000ff19ea9521b0 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
</pre>

<pre>
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00007>
	  at System.Reflection.MethodInvoker:InterpretedInvoke <0x00073>
	  at System.Reflection.MethodInvoker:Invoke <0x00103>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x001a7>
	  at System.Reflection.MethodBase:Invoke <0x00053>
	  at Xunit.Sdk.TestInvoker`1:CallTestMethod <0x00047>
	  at <<InvokeTestMethodAsync>b__1>d:MoveNext <0x00377>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0009f>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x0002f>
	  at <>c__DisplayClass48_0:<InvokeTestMethodAsync>b__1 <0x000cb>
	  at <AggregateAsync>d__4:MoveNext <0x000c3>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0009b>
	  at Xunit.Sdk.ExecutionTimer:AggregateAsync <0x000eb>
	  at <>c__DisplayClass48_0:<InvokeTestMethodAsync>b__0 <0x0017b>
	  at <RunAsync>d__9:MoveNext <0x00067>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00093>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000e7>
	  at <InvokeTestMethodAsync>d__48:MoveNext <0x00287>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000a7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestInvoker`1:InvokeTestMethodAsync <0x00113>
	  at Xunit.Sdk.XunitTestInvoker:InvokeTestMethodAsync <0x0011b>
	  at <<RunAsync>b__47_0>d:MoveNext <0x00673>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000af>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestInvoker`1:<RunAsync>b__47_0 <0x000d3>
	  at <RunAsync>d__10`1:MoveNext <0x00073>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00093>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000e7>
	  at Xunit.Sdk.TestInvoker`1:RunAsync <0x0010b>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestMethodAsync <0x000cb>
</pre>
</details>

## Error Message

```json 
{ 
    "ErrorMessage": "wrong maximal instruction length of instruction storex_membase (expected 12, got 16)",
    "BuildRetry": false,
    "ExcludeConsoleLog": false
} 
```

**Comment by lambdageek** [comment]
Duplicate of https://github.com/dotnet/runtime/pull/83769
