### ISSUE TITLE
Loading assemblies with invalid metadata keeps their file open.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#83796]
Consider [the attached assembly](https://github.com/dotnet/runtime/files/11045510/FieldEdgeCase.zip). Loading it with `Assembly.LoadFromFile` will fail with the following message:

```
File name: 'FieldEdgeCase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: File is corrupt. (0x8013110E)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFile(String path)
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\Users\teo\code\RoslynTest\stdin:line 1
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Failing to load it is expected, but the runtime keeps holding on the file, preventing me from deleting or modifying it. By contrast, a more obviously invalid assembly like a plaintext file is not held.

I'm on .NET 7.0.4.

**Comment by jkotas** [comment]
You would need to load the assembly as collectible in order to be able to unload it. Once we start loading the unloadable assembly, there is no easy way to revert the process.

**Comment by agocke** [comment]
Closing as resolved, by design.
