### ISSUE TITLE
Wrong cancellation token raised by `StreamPipeReader.ReadAsync` and `ReadAtLeastCore`

### ISSUE THREAD

**Issue by bentoi** [dotnet/runtime#83885]
### Description

This is a follow up of https://github.com/dotnet/runtime/issues/82594

I tried with 8.0.0 RC2 and it doesn't look like the issue is fixed. However, it's easy to reproduce this time. I've attached a small test case. 

I believe that both `ReadAsync` and `ReadAtLeastCore` are affected by this issue.

### Reproduction Steps

Run attached test case

[streampipereader.zip](https://github.com/dotnet/runtime/files/11063012/streampipereader.zip)

### Expected behavior

The program should succeed. 

### Actual behavior

It fails with a `TaskCanceledException` with an unexpected token. Shouldn't this also be `OperationCanceledException`?

```csharp
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Program.TestStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /home/vagrant/workspace/streampipereader/Program.cs:line 43
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Program.Main(String[] args) in /home/vagrant/workspace/streampipereader/Program.cs:line 12
   at Program.<Main>(String[] args)
```

### Configuration

.NET 8.0.0 RC2

**Comment by manandre** [comment]
The initial fix is not part of 8.0 preview 2, but it will be part of 8.0 preview 3.
I have just created a new PR #83926 to apply the same fix to `ReadAtLeastAsync`.
