### ISSUE TITLE
[jitosr_stress_random] Failures in System.Text related tests

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#83959]
There seem to be widespread failures in System.Text related tests in the jitosr_stress_random runs: https://dev.azure.com/dnceng-public/public/_build/results?buildId=217773&view=results

Example failure on windows-release-x64: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-0dce5b8399ce429a95/System.Text.Encodings.Web.Tests/1/console.1cdfd228.log?helixlogtype=result

```scala
  Starting:    System.Text.Encodings.Web.Tests (parallel test collections = on, max threads = 4)
    System.Text.Encodings.Web.Tests.JavaScriptEncoderTests.JavaScriptEncode_Relaxed_StillEncodesForbiddenChars_Simple_Escaping [FAIL]
      Assert.Equal() Failure
                  ? (pos 2)
      Expected: \b
      Actual:   \by
                  ? (pos 2)
      Stack Trace:
        /_/src/libraries/System.Text.Encodings.Web/tests/JavaScriptEncoderTests.Relaxed.cs(75,0): at System.Text.Encodings.Web.Tests.JavaScriptEncoderTests.JavaScriptEncode_Relaxed_StillEncodesForbiddenChars_Simple(String input, String expected)
        /_/src/libraries/System.Text.Encodings.Web/tests/JavaScriptEncoderTests.Relaxed.cs(56,0): at System.Text.Encodings.Web.Tests.JavaScriptEncoderTests.JavaScriptEncode_Relaxed_StillEncodesForbiddenChars_Simple_Escaping()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Probably from #83910
