### ISSUE TITLE
Test failure Tests.System.TimeProviderTests.TestProviderTimer

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84236]
Run: [runtime-coreclr libraries-jitstress 20230402.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225552&view=ms.vss-test-web.build-test-results-tab&runId=4237928&resultId=178641&paneView=debug)

Failed test:
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- Tests.System.TimeProviderTests.TestProviderTimer(provider: SystemTimeProvider { LocalNow = 2023-04-02T07:37:44.3564986+00:00, LocalTimeZone = (UTC) Coordinated Universal Time, TimestampFrequency = 1000000000, UtcNow = 2023-04-02T07:37:44.3564582+00:00 }, MaxMilliseconds: 6000)
```
**Error message:**
```
Assert.Equal() Failure
Expected: 400
Actual:   300


Stack trace
   at Tests.System.TimeProviderTests.TestProviderTimer(TimeProvider provider, Int32 MaxMilliseconds) in /_/src/libraries/Common/tests/Tests/System/TimeProviderTests.cs:line 118
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by tarekgh** [comment]
I increased the timeout in the PR https://github.com/dotnet/runtime/pull/84235 which should help with this issue. I am closing it and watch if we'll see it again.
