### ISSUE TITLE
Alt-Svc and Authentication header value parsers throw from TryParse

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#84269]
```c#
var headers = new HttpResponseMessage().Headers;
headers.TryAddWithoutValidation("Alt-Svc", "a=");
_ = headers.Count();
```

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.HttpRuleParser.GetExpressionLength(String input, Int32 startIndex, Char openChar, Char closeChar, Boolean supportsNesting, Int32 nestedCount, Int32& length)
   at System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedAltAuthority(String value, Int32 startIndex, String& host, Int32& port, Int32& readLength)
   at System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength(String value, Int32 startIndex, Object storeValue, Object& parsedValue)
   at System.Net.Http.Headers.BaseHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(HeaderStoreItemInfo info, HeaderDescriptor descriptor, String rawValue)
```

---

```c#
// The same applies to "Proxy-Authenticate", "Proxy-Authorization", "WWW-Authenticate" as they share the parser
var headers = new HttpRequestMessage().Headers;
headers.TryAddWithoutValidation("Authorization", "a \n");
_ = headers.Count();
```

```
System.FormatException: New-line characters are not allowed in header values.
   at System.Net.Http.Headers.HttpHeaders.CheckContainsNewLine(String value)
   at System.Net.Http.Headers.AuthenticationHeaderValue..ctor(String scheme, String parameter)
   at System.Net.Http.Headers.AuthenticationHeaderValue.GetAuthenticationLength(String input, Int32 startIndex, Object& parsedValue)
   at System.Net.Http.Headers.BaseHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(HeaderStoreItemInfo info, HeaderDescriptor descriptor, String rawValue)
```

**Comment by MihaZupan** [comment]
Similar issues with `ETag`, `If-Match`, `If-None-Match`, `If-Range` that share the `EntityTagHeaderValue` parser.

```c#
var headers = new HttpRequestMessage().Headers;
headers.TryAddWithoutValidation("If-Match", "w/\t\t");
_ = headers.Count();
```

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.HttpRuleParser.GetExpressionLength(String input, Int32 startIndex, Char openChar, Char closeChar, Boolean supportsNesting, Int32 nestedCount, Int32& length)
   at System.Net.Http.Headers.EntityTagHeaderValue.GetEntityTagLength(String input, Int32 startIndex, EntityTagHeaderValue& parsedValue)
   at System.Net.Http.Headers.GenericHeaderParser.ParseMultipleEntityTags(String value, Int32 startIndex, Object& parsedValue)
   at System.Net.Http.Headers.BaseHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(HeaderStoreItemInfo info, HeaderDescriptor descriptor, String rawValue)
```

**Comment by IDisposable** [comment]
When adding the values with embedded `'\n'` characters, what is the expectation that this should satisfy. Streaming out a header with an embedded newline would simply terminate the value of the injected value see [token specification](https://httpwg.org/specs/rfc9110.html#rule.token.separators) so in essence these are invalid token values and thus expecting them to parse back out seems unfair.

**Comment by MihaZupan** [comment]
The main issue is that enumerating the header collection **should never throw**, even if some of the values are invalid. The examples I showed above are a few edge cases that violate that expectation.

Regarding `'\n'`, you are right that it shouldn't be used in header values, but it does happen in the wild.
And while you can't receive a value containing a `'\n'` when using SocketsHttpHandler over HTTP/1.1, you can with HTTP/2. The same parsing issue can also be observed with `"a \ra"`, which you can receive over H1.

The expectation isn't that the validation should accept such values as valid, but that it should be able to reject them without throwing.

**Comment by mla-alm** [comment]
I'd like to look into a fix for this.

**Comment by MihaZupan** [comment]
Thanks!
