### ISSUE TITLE
Seeing HTTP Client timeout issue after upgrading to dotnet core 6.0

### ISSUE THREAD

**Issue by jikuma** [dotnet/runtime#84388]
### Description

Our application is deployed on a Kubernetes cluster running on a Linux node. Recently, we upgraded our dotnet core runtime from 5.0 to 6.0. However, after the upgrade, we started encountering an error that says, 'The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.' 

```exception
Exception: Exception: System.Threading.Tasks.TaskCanceledException, The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.,    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Azure.Management.TrafficManager.ProfilesOperations.ListBySubscriptionWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.TrafficManager.ProfilesOperationsExtensions.ListBySubscriptionAsync(IProfilesOperations operations, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.TrafficManager.ProfilesOperationsExtensions.ListBySubscription(IProfilesOperations operations)
  <Redacted>
  InnerException: System.TimeoutException, Exception: System.TimeoutException, The operation was canceled.,  InnerException: System.Threading.Tasks.TaskCanceledException, Exception: System.Threading.Tasks.TaskCanceledException, The operation was canceled.,    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) InnerException: System.IO.IOException, Exception: System.IO.IOException, Unable to read data from the transport connection: Operation canceled.,    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) InnerException: System.Net.Sockets.SocketException, Exception: System.Net.Sockets.SocketException, Operation canceled, 
```

In above example our code is trying to reach traffic manager using Azure SDK. 

### Configuration

Dotnet core runtime 6.0.15

Any idea how to debug the issue or what might have changed in dotnet 6.0, which can cause the issue.

**Comment by MihaZupan** [comment]
This may be related to a connection pool problem introduced in .NET 6 (fixed in 7.0).

Can you try setting the `ConnectTimeout` to something like `TimeSpan.FromSeconds(15)` (default to infinite) and see if the problem persists? If setting the `ConnectTimeout` resolves the issues, this is likely similar to #81989.

If it does not, we will need more information to investigate further (network trace/memory dump/[diagnostic events](https://learn.microsoft.com/en-gb/dotnet/fundamentals/networking/networking-telemetry#internal-diagnostics)).

**Comment by jikuma** [comment]
Thanks for your help @MihaZupan. We are using the Azure SDK to call the Traffic Manager, DNS, and Container Registry resource providers. Previously, we did not pass an HttpClient to these requests, and instead, a new HttpClient would be created for each request.

At a few places, I updated the code to include an HttpClient with a 15-second ConnectTimeout. This resulted in a decrease in timeout errors. However, I still encounter timeout errors occasionally in the areas where I updated the SDK calls to use a specified HttpClient.

I will update the code to pass an HttpClient for all SDK calls and observe if the timeout issue is resolved. If the issue persists, I will try to collect the trace and share it with you.

**Comment by flindby** [comment]
We are seeing this now when running integration tests with `WebApplicationFactory ` when moving from .NET6 to .NET7

**Comment by davidfowl** [comment]
WebApplicationFactory doesn’t use the same implementation so maybe you’re seeing something different? Or maybe you have a repro?

**Comment by flindby** [comment]
Note: I increased the HttpClient.Timeout to 10min, all tests now pass, but the test run went from 35m to 1h 42m. I have looked at all breaking changes for .NET 7 but cannot really locate the issue.
Any ideas what can cause the increased test execution time?

**Comment by wfurt** [comment]
It seems like something is not finishing e.g. not getting responses. Increased time would just make this longer. I think you will need to find specific instances and possibly do packet captures to fully understand what is happening @flindby.

**Comment by flindby** [comment]
@wfurt  But all tests pass when we increase the timeout - so the problem must be that something happened when we switched to .NET7. I cannot see why tests starts running slower after the upgrade.

**Comment by karelz** [comment]
Triage: 7.0 should solve this. 6.0 has a workaround (using ConnectTimout and doing retries).
Closing.
