### ISSUE TITLE
Casting via generic math doesn't always inline in R2R

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#84421]
Related: #78648.

```csharp
uint M0() => uint.CreateTruncating(42u);
uint M1() => uint.CreateTruncating((byte)42);
uint M2() => uint.CreateTruncating(42UL);
uint M3() => uint.CreateTruncating(42);
uint M4() => uint.CreateTruncating((sbyte)42);
int M5() => int.CreateTruncating(42);
int M6() => int.CreateTruncating((sbyte)42);
int M7() => int.CreateTruncating(42L);
int M8() => int.CreateTruncating(42u);
int M9() => int.CreateTruncating((byte)42);
```

```asm
// crossgen2 8.0.0-preview.4.23206.99+18e2c5fd9e2239a8b06fe49dbb6492d40f5e5e19

C:M0():uint:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       mov      eax, 42
						;; size=5 bbWeight=1 PerfScore 0.25
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00

C:M1():uint:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.UInt32:CreateTruncating[ubyte](ubyte):uint
						;; size=3 bbWeight=1 PerfScore 2.00

C:M2():uint:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.UInt32:CreateTruncating[ulong](ulong):uint
						;; size=3 bbWeight=1 PerfScore 2.00

C:M3():uint:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.UInt32:CreateTruncating[int](int):uint
						;; size=3 bbWeight=1 PerfScore 2.00

C:M4():uint:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.UInt32:CreateTruncating[byte](byte):uint
						;; size=3 bbWeight=1 PerfScore 2.00

C:M5():int:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       mov      eax, 42
						;; size=5 bbWeight=1 PerfScore 0.25
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00

C:M6():int:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.Int32:CreateTruncating[byte](byte):int
						;; size=3 bbWeight=1 PerfScore 2.00

C:M7():int:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.Int32:CreateTruncating[long](long):int
						;; size=3 bbWeight=1 PerfScore 2.00

C:M8():int:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.Int32:CreateTruncating[uint](uint):int
						;; size=3 bbWeight=1 PerfScore 2.00

C:M9():int:this:
; Emitting BLENDED_CODE for X64 CPU with SSE2 - Unix
						;; size=0 bbWeight=1 PerfScore 0.00
       lea      rax, [(reloc)]
       mov      edi, 42
						;; size=12 bbWeight=1 PerfScore 0.75
       tail.jmp [rax]System.Int32:CreateTruncating[ubyte](ubyte):int
						;; size=3 bbWeight=1 PerfScore 2.00
```

https://csharp.godbolt.org/z/K6xM8hP6P

**Comment by JulieLeeMSFT** [comment]
We will push this to Future becuase we will not have time to work on this in .NET 8.

**Comment by EgorBo** [comment]
@xtqqczze it emits expected codegen for JIT and NativeAOT, seems to be R2R specific, from what I see R2R runtime throws 
```
Internal.JitInterface.RequiresRuntimeJitException: SVM
   at Internal.JitInterface.CorInfoImpl.getCallInfo(CORINFO_RESOLVED_TOKEN& pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult) in C:\prj\runtime\src\coreclr\tools\aot\ILCompiler.ReadyToRun\JitInterface\CorInfoImpl.ReadyToRun.cs:line 2109
   at Internal.JitInterface.CorInfoImpl._getCallInfo(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult) in C:\prj\runtime\src\coreclr\tools\Common\JitInterface\CorInfoImpl_generated.cs:line 2178
```
for `getCallInfo` during inlining so JIT gives up on inlining due to error

**Comment by stephentoub** [comment]
>> We will push this to Future becuase we will not have time to work on this in .NET 8.

> seems to be R2R specific

In case it impacts prioritization, we're on a path to make fairly heavy use of this throughout core formatting/parsing logic, as in https://github.com/dotnet/runtime/pull/84469.

**Comment by EgorBo** [comment]
@dotnet/crossgen-contrib any idea why we hit this during compilation of
```csharp
uint M1() => uint.CreateTruncating((byte)42);
```

![image](https://user-images.githubusercontent.com/523221/231473755-43aa8692-dbfb-4faa-a536-8e7c62d52359.png)

**Comment by trylek** [comment]
Well, Crossgen2 doesn't yet support static virtual method resolution, that was planned for .NET 7 but it got cut as it turned out to be quite challenging and we didn't get to it early enough in the release cycle. If it becomes more of a perf problem now we can discuss its prioritization among .NET 8 Crossgen2 work. If method is not a static virtual then that's just a bug in the check that should be easy to fix.

**Comment by EgorBo** [comment]
Yes it's `static virtual TSelf CreateTruncating`.

> If it becomes more of a perf problem

I assume it could be e.g. for customers who disable tiering since we now use more and more of these

**Comment by trylek** [comment]
OK, thanks for pointing it out, I'll discuss it at today Crossgen2 weekly sync. Maybe we could start supporting at least some cases, IIRC the main problem is precompilation of canonical methods where the resolution depends on the actual type passed at runtime i.o.w. there's no way to resolve the call at compile time.

**Comment by mangod9** [comment]
@EgorBo @trylek assume this will be closed once SVM support in crossgen2 is enabled?

**Comment by EgorBo** [comment]
> @EgorBo @trylek assume this will be closed once SVM support in crossgen2 is enabled?

Correct

**Comment by trylek** [comment]
I believe this should be fixed with https://github.com/dotnet/runtime/pull/87438, closing. There are still certain cases that cannot be resolved at compile time, some of them can be fixed in the future by improving the JIT interface. In particular, embedGenericHandle doesn't support passing the constrained type that would be needed if SVM lookup fails at compile time (the SVM lookup itself would still need runtime work but the method calling the SVM could be precompiled); similarly, CanInline doesn't support type constraint information so that, if there's an implementation of the SVM on the interface that defines it, we incorrectly decide we can inline it despite the fact that the constrained lookup could find a different implementation on derived interfaces or types.

**Comment by xtqqczze** [comment]
Unfortunately, with #87438, the codegen still has many missed inlining opportunities, especially for signed integers.

```asm
// crossgen2 8.0.0-rc.1.23409.99+40b39ff7df1dc2388a5865c9ad151dce88fa007d

C:M0():uint:this (FullOpts):
 
       mov      eax, 42
 
       ret      
 
C:M1():uint:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       mov      dword ptr [rbp-0x08], 42
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 

C:M2():uint:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       mov      dword ptr [rbp-0x08], 42
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
C:M3():uint:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       xor      esi, esi
       mov      dword ptr [rbp-0x08], esi
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Int32:System.Numerics.INumberBase<System.Int32>.TryConvertToTruncating[uint](int,byref):bool]
       test     eax, eax
       je       SHORT G_M000_IG04
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
G_M000_IG04:
       call     [System.ThrowHelper:ThrowNotSupportedException()]
       int3     
 
C:M4():uint:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       xor      esi, esi
       mov      dword ptr [rbp-0x08], esi
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.SByte:System.Numerics.INumberBase<System.SByte>.TryConvertToTruncating[uint](byte,byref):bool]
       test     eax, eax
       je       SHORT G_M000_IG04
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
G_M000_IG04:
       call     [System.ThrowHelper:ThrowNotSupportedException()]
       int3     
 
C:M5():int:this (FullOpts):
 
       mov      eax, 42
 
       ret      
 
C:M6():int:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Int32:TryConvertFromTruncating[byte](byte,byref):bool]
       test     eax, eax
       jne      SHORT G_M000_IG04
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.SByte:System.Numerics.INumberBase<System.SByte>.TryConvertToTruncating[int](byte,byref):bool]
       test     eax, eax
       je       SHORT G_M000_IG06
 
G_M000_IG04:
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
G_M000_IG06:
       call     [System.ThrowHelper:ThrowNotSupportedException()]
       int3     
 
C:M7():int:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Int32:TryConvertFromTruncating[long](long,byref):bool]
       test     eax, eax
       jne      SHORT G_M000_IG04
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Int64:System.Numerics.INumberBase<System.Int64>.TryConvertToTruncating[int](long,byref):bool]
       test     eax, eax
       je       SHORT G_M000_IG06
 
G_M000_IG04:
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
G_M000_IG06:
       call     [System.ThrowHelper:ThrowNotSupportedException()]
       int3     
 
C:M8():int:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Int32:TryConvertFromTruncating[uint](uint,byref):bool]
       test     eax, eax
       jne      SHORT G_M000_IG04
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.UInt32:System.Numerics.INumberBase<System.UInt32>.TryConvertToTruncating[int](uint,byref):bool]
       test     eax, eax
       je       SHORT G_M000_IG06
 
G_M000_IG04:
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
G_M000_IG06:
       call     [System.ThrowHelper:ThrowNotSupportedException()]
       int3     
 
C:M9():int:this (FullOpts):
       push     rbp
       sub      rsp, 16
       lea      rbp, [rsp+0x10]
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Int32:TryConvertFromTruncating[ubyte](ubyte,byref):bool]
       test     eax, eax
       jne      SHORT G_M000_IG04
 
       lea      rsi, [rbp-0x08]
       mov      edi, 42
       call     [System.Byte:System.Numerics.INumberBase<System.Byte>.TryConvertToTruncating[int](ubyte,byref):bool]
       test     eax, eax
       je       SHORT G_M000_IG06
 
G_M000_IG04:
       mov      eax, dword ptr [rbp-0x08]
 
       add      rsp, 16
       pop      rbp
       ret      
 
G_M000_IG06:
       call     [System.ThrowHelper:ThrowNotSupportedException()]
       int3     
 ```
