### ISSUE TITLE
Test failure GC\\API\\Frozen\\Frozen\\Frozen

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84462]
Run: [runtime-coreclr outerloop 20230406.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230331&view=ms.vss-test-web.build-test-results-tab&runId=4362366&resultId=120745&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open

- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open

- GC\\API\\Frozen\\Frozen\\Frozen.cmd
```
**Error message:**
```
Assert failure(PID 8184 [0x00001ff8], Thread: 7388 [0x1cdc]): Consistency check failed: AV in clr at this callstack:
<no module>! <no symbol> + 0x0 (0x00000000)
.AV on tid=0x1cdc (7388), cxr=0517E020, exr=0517E1C0
FAILED: false

<no module>! <no symbol> + 0x0 (0x00000000)
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 7116
Image: C:\h\w\BCE20A35\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\BCE20A35\w\A7CE0936\uploads\Reports\GC.API\Frozen\Frozen\Frozen.output.txt
Raw output:
BEGIN EXECUTION
Frozen.dll
1 file(s) copied.
20:09:42.19
Response file: C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.dll.rsp
C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\IL-CG2\Frozen.dll
-o:C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\BCE20A35\p\System..dll
-r:C:\h\w\BCE20A35\p\Microsoft..dll
-r:C:\h\w\BCE20A35\p\xunit.*.dll
-r:C:\h\w\BCE20A35\p\mscorlib.dll
-r:C:\h\w\BCE20A35\p\netstandard.dll
-O
" "dotnet" "C:\h\w\BCE20A35\p\crossgen2\crossgen2.dll" @"C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.dll.rsp"   -r:C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.dll
" "dotnet" "C:\h\w\BCE20A35\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.dll --out C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.dll.r2rdump --val"
20:09:44.80
"C:\h\w\BCE20A35\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Frozen.dll
False
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 4/6/2023 8:09:42 PM
Processing C:\cores\corerun.exe.8184.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm\cdb.exe
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\BCE20A35\p
> C:\h\w\BCE20A35\w\A7CE0936\e\GC\API\Frozen\Frozen\Frozen.cmd
Expected: True
Actual:   False


Stack trace
   at GC_API._Frozen_Frozen_Frozen_._Frozen_Frozen_Frozen_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment]
Failed in [jitstress](https://dev.azure.com/dnceng-public/public/_build/results?buildId=231142&view=ms.vss-test-web.build-test-results-tab&runId=4383110&resultId=117168&paneView=debug).

**Comment by EgorBo** [comment]
Looks more like a gc issue to me cc @dotnet/gc 
```
Assert failure(PID 6996 [0x00001b54], Thread: 10992 [0x2af0]): Consistency check failed: AV in clr at this callstack:
CORECLR! WKS::gc_heap::clear_mark_array + 0x9E (0x70d7c9a9)
CORECLR! WKS::gc_heap::remove_ro_segment + 0x43 (0x70d8f71b)
CORECLR! GCInterface_UnregisterFrozenSegment + 0x100 (0x70aee960)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fa74fed)
CORECLR! CallDescrWorkerInternal + 0x34 (0x70d978b1)
CORECLR! CallDescrWorker + 0xAA (0x70ac596c)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70ac5aaa)
CORECLR! RuntimeMethodHandle::InvokeMethod + 0x6E0 (0x70c2c6c0)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fbe82b6)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fbf4ddd)
<no module>! <no symbol> + 0x0 (0x04bd2c41)
<no module>! <no symbol> + 0x0 (0x04bd1ba9)
CORECLR! CallDescrWorkerInternal + 0x34 (0x70d978b1)
CORECLR! CallDescrWorker + 0xAA (0x70ac596c)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70ac5aaa)
CORECLR! MethodDescCallSite::CallTargetWorker + 0x648 (0x70ac6124)
CORECLR! RunMainInternal + 0x1AB (0x708bff9d)
CORECLR! ``RunMain'::29&#39;::__Body::Run&#39;::5'::__Body::Run + 0x40 (0x708bfb8c)
CORECLR! RunMain&#39;::29'::__Body::Run + 0x6C (0x708bfc49)
```

**Comment by mangod9** [comment]
@cshung who had added this test I believe.

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr jitstress 20230412.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237553&view=ms.vss-test-web.build-test-results-tab&runId=4543110&resultId=121708&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitminopts @ Windows.10.Amd64.Open

- GC\\API\\Frozen\\Frozen\\Frozen.cmd
```
**Error message:**
```
Assert failure(PID 6044 [0x0000179c], Thread: 5620 [0x15f4]): Consistency check failed: AV in clr at this callstack:
CORECLR! WKS::gc_heap::clear_mark_array + 0x9E (0x6ff7db2c)
CORECLR! WKS::gc_heap::remove_ro_segment + 0x43 (0x6ff9089b)
CORECLR! GCInterface_UnregisterFrozenSegment + 0x100 (0x6fcef3d0)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6ec8482d)
CORECLR! CallDescrWorkerInternal + 0x34 (0x6ff98a31)
CORECLR! CallDescrWorker + 0xAA (0x6fcc63dc)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x6fcc651a)
CORECLR! RuntimeMethodHandle::InvokeMethod + 0x6E0 (0x6fe2d850)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6edf1506)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6edfe01d)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6edf0c14)
<no module>! <no symbol> + 0x0 (0x010b45ea)
<no module>! <no symbol> + 0x0 (0x010b4562)
<no module>! <no symbol> + 0x0 (0x010b2cf6)
CORECLR! CallDescrWorkerInternal + 0x34 (0x6ff98a31)
CORECLR! CallDescrWorker + 0xAA (0x6fcc63dc)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x6fcc651a)
CORECLR! MethodDescCallSite::CallTargetWorker + 0x648 (0x6fcc6b94)
CORECLR! RunMainInternal + 0x1AB (0x6fac03bd)
.AV on tid=0x15f4 (5620), cxr=00B7D5B8, exr=00B7D568
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x6ffadd50)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6fb64589)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6fb6427e)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x6fb64224)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x6fb6479a)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1C21A (0x76fbf95a)
NTDLL! RtlUnwind + 0x1BA (0x76f8011a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x76f90dbf)
CORECLR! WKS::gc_heap::remove_ro_segment + 0x43 (0x6ff9089b)
CORECLR! GCInterface_UnregisterFrozenSegment + 0x100 (0x6fcef3d0)
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 7116
Image: C:\h\w\A204087F\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A204087F\w\A754094E\uploads\Reports\GC.API\Frozen\Frozen\Frozen.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A204087F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Frozen.dll
False
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 4/13/2023 5:39:46 AM
Processing C:\cores\corerun.exe.6044.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\A204087F\t\tmpuudc5h.tmp" -z "C:\cores\corerun.exe.6044.dmp"
stdout:
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\cores\corerun.exe.6044.dmp]
User Mini Dump File with Full Memory: Only application data is available

************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\A204087F\p\PDB
Symbol search path is: C:\h\w\A204087F\p\PDB
Executable search path is:
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Thu Apr 13 05:40:04.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:29:35.264
Process Uptime: 0 days 0:00:17.000
.................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception informati


Stack trace
   at GC_API._Frozen_Frozen_Frozen_._Frozen_Frozen_Frozen_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
