### ISSUE TITLE
SslStream throws when using OpenSSL cert

### ISSUE THREAD

**Issue by amcasey** [dotnet/runtime#84575]
### Description

[Simplified from https://github.com/dotnet/runtime/issues/84505]

We're seeing an `AuthenticationException` from `SslStream` when using a certificate from OpenSSL in a server running on Windows.

### Reproduction Steps

Generate a couple of certs with openssl (they seem to have slightly different failure modes)
```
openssl req -new -newkey rsa:4096 -x509 -nodes -days 365 -keyout server.key -out server.crt -subj "/C=SG/ST=Singapore/L=Singapore /O=My Company Pte. Ltd./OU=My Organization/CN=localhost/emailAddress=a@b.c"
openssl pkcs12 -export -out twocerts.pfx -inkey server.key -in server.crt -certfile server.crt -passout pass:mypass
openssl pkcs12 -export -out onecert.pfx -inkey server.key -in server.crt -passout pass:mypass
```

Create a `dotnet new console` app with the following code (fix cert path for your box)
```csharp
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Cryptography.X509Certificates;

TcpListener listener = new TcpListener(IPAddress.Any, 5000);
listener.Start();

TcpClient client = listener.AcceptTcpClient();

SslStream sslStream = new SslStream(client.GetStream(), false);
var serverCertificate = new X509Certificate2(@"c:\tmp\opensslCerts\twocerts.pfx", "mypass");
sslStream.AuthenticateAsServer(serverCertificate, clientCertificateRequired: false, checkCertificateRevocation: false);
```

Navigate to https://localhost:5000

### Expected behavior

No exception (the server code is mangled to be minimal and wouldn't do anything sensible if it made it past the exception).

### Actual behavior

I'm seeing several different callstacks, some of which I suspect are expected.

For twocerts.pfx and `curl https://localhost:5000 --insecure` (or navigating to https://localhost:5000 in Edge)
```
Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslAuthenticationOptions authOptions)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested)
   at System.Net.Security.SslStream.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions, Boolean newCredentialsRequested)
   at System.Net.Security.SslStream.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, Boolean checkCertificateRevocation)
   at Program.<Main>$(String[] args) in c:\tmp\opensslCerts\repro\Program.cs:line 13
```

For onecert.pfx and navigating to https://localhost:5000 in Edge (but not `curl https://localhost:5000 --insecure`).  (This might just be because the cert is self-signed or because the server code is incomplete?)
```
Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, Boolean checkCertificateRevocation)
   at Program.<Main>$(String[] args) in c:\tmp\opensslCerts\repro\Program.cs:line 13
```

Probably expected: for either cert and either client, but address http://localhost:5000 (note: http, not https)
```
Unhandled exception. System.Security.Authentication.AuthenticationException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, Boolean checkCertificateRevocation)
   at Program.<Main>$(String[] args) in c:\tmp\opensslCerts\repro\Program.cs:line 13
```

### Regression?

The behavior appears to be the same in dotnet 7.0.200.

### Configuration

OS: Microsoft Windows 11 Enterprise (10.0.22621 Build 22621)
OpenSSL: 1.1.1s  1 Nov 2022 (from git version 2.39.2.windows.1)
dotnet: 8.0.100-preview.4.23210.1

In the course of experimenting, I've seen similar behavior on win10 and with certs from openssl 3, but I haven't rigorously built a matrix.

### Other information

[onecert.pfx.txt](https://github.com/dotnet/runtime/files/11192446/onecert.pfx.txt)
[twocerts.pfx.txt](https://github.com/dotnet/runtime/files/11192448/twocerts.pfx.txt)

There are the files I tested with.  Obviously, you'll need to remove the `.txt` I added to placate GH.

**Comment by amcasey** [comment]
FYI @khteh @wfurt, I've filed a simplified issue here.

**Comment by amcasey** [comment]
I tried the repros on `Ubuntu 22.04.2 LTS` with `OpenSSL 3.0.2 15 Mar 2022` and `dotnet 8.0.100-preview.4.23210.3`.

twocerts.pfx and `curl https://localhost:5000 --insecure` succeeds on Ubuntu.  The other stacks look the same.

If the only actual issue is that passing the same cert as `-in` and `-certfile` doesn't work with schannel, this is probably pretty low priority (at least, until we find a customer who depends on this scenario).

**Comment by amcasey** [comment]
@vcsjones Thanks for the explanation!

Do you have a sense of why I'm seeing `An unknown error occurred while processing the certificate.` when accessing the server (which is using the unambiguous `onecert.pfx`) from Edge, but not from curl?  I tried importing `onecert.pfx` as a Trusted Root CA, but that didn't seem to make a difference.  I also fleshed out the server code (from https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstream?view=net-7.0) and saw that the exception seems to be recoverable - a subsequent request from curl (i.e. after accessing with Edge and seeing the  stack) succeeds.

**Comment by vcsjones** [comment]
> o you have a sense of why I'm seeing An unknown error occurred while processing the certificate. when accessing the server (which is using the unambiguous onecert.pfx) from Edge, but not from curl? 

Chrome / Edge don't care about the common name on the certificate. They only care about the subjectAltName on the certificate, and the example certificates provided don't include a SAN. If you add a SAN:

```shell
openssl req -new -newkey rsa:4096 -x509 -nodes \
    -days 365 -keyout server.key -out server.crt \
    -subj "/C=SG/ST=Singapore/L=Singapore /O=My Company Pte. Ltd./OU=My Organization/CN=localhost/emailAddress=a@b.c" \
    -addext "subjectAltName = DNS:localhost"
openssl pkcs12 -export -out onecert.pfx -inkey server.key -in server.crt -passout pass:mypass
```

With the SAN, _and_ add it Trusted Root Certification Authorities, then it will work.

`curl` on the other hand is willing to use the commonName from the subject in the certificate. Chromium has documented their strictness here:

https://developer.chrome.com/blog/chrome-58-deprecations/#remove-support-for-commonname-matching-in-certificates

**Comment by vcsjones** [comment]
> and saw that the exception seems to be recoverable - a subsequent request from curl (i.e. after accessing with Edge and seeing the stack) succeeds.

Although re-reading your message, I may not be seeing the same issue you are - do you have a screenshot of the Edge error page? (With details expanded?)

**Comment by amcasey** [comment]
![image](https://user-images.githubusercontent.com/10508071/230982644-5bcb42f7-82a4-43af-bfba-a645c6595478.png)

**Comment by amcasey** [comment]
Your explanation makes sense (and matches the edge error page).  The only part I'm a little confused about is why the server reports the exception if it's the client that's unhappy with the cert.

**Comment by wfurt** [comment]
client may just hang up during TLS handshake or sent TLS alert. Either one will be reported as exception on server since the negotiation did not finish successfully. 
We would probably see that if you do packet capture.

**Comment by amcasey** [comment]
> With the SAN, and add it Trusted Root Certification Authorities, then it will work.

It did.

**Comment by amcasey** [comment]
> We would probably see that if you do packet capture.

I'm new to this, but I gave that a shot and saw that (what I'm pretty sure are) the TLS messages appear to be misclassified as a "Radio Signalling Link".

**Comment by wfurt** [comment]
you can always right-click and do "Decode as" and select TLS. It would probably just work if you run the service on port 443. (and should not impact the observed behavior)

**Comment by amcasey** [comment]
Okay, after using `Decode as` and setting `SSLKEYLOGFILE`, I can now see 
```
22	0.354747	127.0.0.1	127.0.0.1	TLSv1.3	74	Change Cipher Spec, Alert (Level: Fatal, Description: Certificate Unknown)
```

Given that there's a description, it would be nice to get an error more informative than `An unknown error occurred while processing the certificate.`, but I appreciate that the bandwidth of HRESULTs is limited.

Thanks @vcsjones and @wfurt for the explanations!

**Comment by amcasey** [comment]
I've hidden comments from the tangential thread helping me understand why some of the exceptions are expected.  Thanks!

**Comment by vcsjones** [comment]
For the two-certificate-one-key case, this behavior is known and tested, so I would say for this case, this is "working as intended":

https://github.com/dotnet/runtime/blob/f516d02550e5f47d12b7d551b8b3dfcf33d8743a/src/libraries/System.Security.Cryptography/tests/X509Certificates/PfxFormatTests.cs#L929-L935

@amcasey Given that we know the two-cert case is working as intended, albeit the Win32 error is not exactly clear, and we understand the single-cert case is due to a TLS alert the browser is sending back, I don't think there is any work left to do for this issue.

**Comment by amcasey** [comment]
@vcsjones Fine by me, but it would be good to hear from @khteh, on whose behalf I filed this.

**Comment by khteh** [comment]
I added SAN but **without** adding it to the Trusted Root Certification Authorities it works. Is this expected? What difference does it make whether or not we add this self-signed cert to the Trusted Root Certification Authorities?

**Comment by khteh** [comment]
I think I put ` -addext "subjectAltName = DNS:localhost"` in the wrong `openssl pkcs12` command yesterday instead of `openssl req`. I just regenerated the cert, add Trusted Root Authorities as shown, but still see `"An unknown error occurred while processing the certificate."`

![image](https://user-images.githubusercontent.com/3871483/231318781-ec84564a-f3db-465e-9932-743f2249f5eb.png)

**Comment by emayevski** [comment]
This is an old thread, but the issue is apparently still there. 

I have a valid CA certificate and a valid end-entity certificate signed with this CA cert. Both are packed into a PFX file. If I now try to load the certificate *collection* from this PFX file, two certificates are loaded, the CA comes first and the end-entity one comes second, the second has HasPrivateKey property as true, *however* if I use this end-entity certificate for Kestrel server-side authentication, the SSL connection randomly does not work with the internal error being SEC_E_UNKNOWN_CREDENTIALS . Note that in _some_ cases after restarting the application multiple times, a connection will succeed (the key is loaded) and once the key is loaded, it is cached and consequent operations work fine. 

Now, if I put the CA certificate into a separate DER or PEM-encoded file and have just the end-entity certificate in the PFX and load the PFX using CertificateLoader.LoadCertificateFromFile(), then I can use the end-entity certificate with Kestrel successfully all the time. And if I load the CA cert from another file, I can use it in a CA certificates collection for the use by Kestrel). 

I spent some time trying different tricks, but the approach of having just one end-entity cert in the PFX is the only one that works reliably. 

The certificates were generated with OpenSSL on Windows and the above occurs also on Windows.
