### ISSUE TITLE
JSON Serialize as object doesn't work with source generation by default

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#84704]
### Description

In order to solve polymorphic JSON serialization scenarios in ASP.NET, specifically in ASP.NET's `EndpointFilterDelegate` which uses `object` as the "declared type", we need to serialize the value "as object". However, this doesn't work with source generation by default unless the user explicitly adds `typeof(object)` to the source generated context.

### Reproduction Steps

Run:

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

var value = new Derived() { BaseString = "Base", DerivedString = "Derived" };

var options = new JsonSerializerOptions();
options.TypeInfoResolver = new TestJsonContext();

Console.WriteLine(JsonSerializer.Serialize<object>(value, options));

internal class Base
{
    public string? BaseString { get; set; }
}

internal class Derived : Base
{
    public string? DerivedString { get; set; }
}

[JsonSerializable(typeof(Base))]
[JsonSerializable(typeof(Derived))]
internal partial class TestJsonContext : JsonSerializerContext { }
```

### Expected behavior

Should output

```
{"DerivedString":"Derived","BaseString":"Base"}
```

### Actual behavior

```
System.NotSupportedException
  Message=JsonTypeInfo metadata for type 'System.Object' was not provided by TypeInfoResolver of type 'TestJsonContext'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type type, IJsonTypeInfoResolver resolver) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 726
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 90
   at System.Text.Json.JsonSerializerOptions.get_ObjectTypeInfo() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 144
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 54
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs:line 32
   at Program.<Main>$(String[] args) in C:\DotNetTest\Net8Console\Program.cs:line 9
```

### Known Workarounds

A workaround is to add

```C#
[JsonSerializable(typeof(object))]
```

To the `TestJsonContext`.

### Other information

One concern is that we shouldn't regress the Native AOT size by too much by fixing this problem. Our current goal is to have a ~10 MB native executable for the `dotnet new api -aot` template. Fixing this issue can't take up too much of that 10 MB goal. We should measure and ensure we aren't adding too much size to fix this (for example by rooting a bunch of converters that are not necessary).

**Comment by eiriktsarpalis** [comment]
We could baking in the converter for `object` in every generated context, however the object converter roots both `JsonDocument` and `JsonNode` types since it needs the for deserialization:

https://github.com/dotnet/runtime/blob/0b081118dedcbc01d445f3f56222fde9d86f3f44/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectConverter.cs#L22-L28

We should try to quantify the size regression and possibly come up with a scheme that avoids rooting these types unless they're needed for deserialization.

**Comment by eerhardt** [comment]
With the app:

```C#
using System.Text.Json;
using System.Text.Json.Serialization;
using JsonOptions = Microsoft.AspNetCore.Http.Json.JsonOptions;
using Microsoft.AspNetCore.Mvc;
using Net8Api;
using Microsoft.Extensions.Options;

var builder = WebApplication.CreateSlimBuilder(args);
builder.Logging.AddConsole();

builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default);
});

var app = builder.Build();

var sampleTodos = TodoGenerator.GenerateTodos().ToArray();

var todosApi = app.MapGroup("/todos");
todosApi.MapGet("/", () => sampleTodos);
todosApi.MapGet("/{id}", (int id) =>
    sampleTodos.FirstOrDefault(a => a.Id == id) is { } todo
        ? Results.Ok(todo)
        : Results.NotFound());
todosApi.MapGet("/derived", ([FromServices] IOptions<JsonOptions> o) => JsonSerializer.Serialize<object>(new Derived() { BaseString = "Base", DerivedString = "Derived" }, o.Value.SerializerOptions));

//todosApi.MapPost("/", Todo (Todo todo, CancellationToken ct) =>
//{
//    return new Todo();
//});

app.Run();

internal class Base
{
    public string? BaseString { get; set; }
}

internal class Derived : Base
{
    public string? DerivedString { get; set; }
}

// uncomment for "object" support:
// [JsonSerializable(typeof(object))]
[JsonSerializable(typeof(Todo[]))]
[JsonSerializable(typeof(Base))]
[JsonSerializable(typeof(Derived))]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}
```

Note the 2 commented out pieces of code.

1. Adds a Deserializing call to JSON
2. Adds `[JsonSerializable(typeof(object))]` to the JsonSerializerContext

I see the following app size change:

Just Serializing:
**without `JsonSerializable(typeof(object)`:** 9.15 MB (9,603,072 bytes)
**with `JsonSerializable(typeof(object)`:** 9.15 MB (9,604,096 bytes)

Serializing and Deserializing:
**without `JsonSerializable(typeof(object)`:** 9.51 MB (9,980,928 bytes)
**with `JsonSerializable(typeof(object)`:** 9.51 MB (9,981,440 bytes)

As you can see, adding `[JsonSerializable(typeof(object))]` adds almost no size to the app. This is because ASP.NET itself is pulling in the `ObjectConverter` already:

https://github.com/dotnet/aspnetcore/blob/7d0c27344d193cb6ad263732d1fef6d3e0fd1f71/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs#L365-L386

I'm not exactly sure why the ObjectConverter is generated for this usage of the source generator. I think it has something to do with `RouteValueDictionary`, which has `public ICollection<object?> Values`, but looking at the generated code for `RouteValueDictionary`, I don't see it using that property:

```C#
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Microsoft.AspNetCore.Diagnostics
{
    internal sealed partial class ExtensionsExceptionJsonContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary>? _RouteValueDictionary;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary> RouteValueDictionary
        {
            get => _RouteValueDictionary ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary>)Options.GetTypeInfo(typeof(global::Microsoft.AspNetCore.Routing.RouteValueDictionary));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary> Create_RouteValueDictionary(global::System.Text.Json.JsonSerializerOptions options)
        {
            global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary>? jsonTypeInfo = null;
            global::System.Text.Json.Serialization.JsonConverter? customConverter;
            if (options.Converters.Count > 0 && (customConverter = GetRuntimeProvidedCustomConverter(options, typeof(global::Microsoft.AspNetCore.Routing.RouteValueDictionary))) != null)
            {
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary>(options, customConverter);
            }
            else
            {
                global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::Microsoft.AspNetCore.Routing.RouteValueDictionary> info = new global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::Microsoft.AspNetCore.Routing.RouteValueDictionary>()
                {
                    ObjectCreator = () => new global::Microsoft.AspNetCore.Routing.RouteValueDictionary(),
                    NumberHandling = default,
                    SerializeHandler = null
                };
        
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateIDictionaryInfo<global::Microsoft.AspNetCore.Routing.RouteValueDictionary, global::System.String, global::System.Object>(options, info);
        
            }
        
            
            jsonTypeInfo.OriginatingResolver = this;
        
            return jsonTypeInfo;
        }
        
    }
}
```

**Comment by eiriktsarpalis** [comment]
Sounds like we could just bake in `object` support for now, and consider strategies for reducing the probability of rooting `JsonNode`/`JsonDocument` later.
