### ISSUE TITLE
Test failure profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84750]
Run: [runtime-coreclr outerloop 20230412.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=236667&view=ms.vss-test-web.build-test-results-tab&runId=4524690&resultId=100029&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open

- profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd
- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd

R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open

- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd
- profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd

coreclr windows arm Checked no_tiered_compilation @ Windows.11.Arm64.Open

- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd
- profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd

coreclr windows arm Checked @ Windows.11.Arm64.Open

- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd
- profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd
```
**Error message:**
```
Unhandled exception.
Cannot print exception string because Exception.ToString() failed.
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
at SlowPathELTTests.SlowPathELTLeave.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A6E7095C\w\9D5F091D\uploads\Reports\profiler.elt\slowpatheltleave\slowpatheltleave.output.txt
Raw output:
BEGIN EXECUTION
common.dll
Microsoft.Diagnostics.NETCore.Client.dll
Profiler.dll
profiler_common.dll
slowpathcommon.dll
slowpatheltleave.dll
TestLibrary.dll
7 file(s) copied.
19:58:10.06
Response file: C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\common.dll.rsp
C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\IL-CG2\common.dll
-o:C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\common.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A6E7095C\p\System..dll
-r:C:\h\w\A6E7095C\p\Microsoft..dll
-r:C:\h\w\A6E7095C\p\xunit..dll
-r:C:\h\w\A6E7095C\p\mscorlib.dll
-r:C:\h\w\A6E7095C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A6E7095C\p\crossgen2\crossgen2.dll" @"C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\common.dll.rsp"   -r:C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\common.dll
" "dotnet" "C:\h\w\A6E7095C\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\common.dll --out C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\common.dll.r2rdump --val"
19:58:13.03
19:58:13.04
Response file: C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Microsoft.Diagnostics.NETCore.Client.dll.rsp
C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\IL-CG2\Microsoft.Diagnostics.NETCore.Client.dll
-o:C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Microsoft.Diagnostics.NETCore.Client.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A6E7095C\p\System..dll
-r:C:\h\w\A6E7095C\p\Microsoft..dll
-r:C:\h\w\A6E7095C\p\xunit..dll
-r:C:\h\w\A6E7095C\p\mscorlib.dll
-r:C:\h\w\A6E7095C\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A6E7095C\p\crossgen2\crossgen2.dll" @"C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Microsoft.Diagnostics.NETCore.Client.dll.rsp"   -r:C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Microsoft.Diagnostics.NETCore.Client.dll
" "dotnet" "C:\h\w\A6E7095C\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Microsoft.Diagnostics.NETCore.Client.dll --out C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Microsoft.Diagnostics.NETCore.Client.dll.r2rdump --val"
19:58:16.70
19:58:16.71
Response file: C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Profiler.dll.rsp
C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\IL-CG2\Profiler.dll
-o:C:\h\w\A6E7095C\w\9D5F091D\e\profiler\elt\slowpatheltleave\Profiler.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A6E7095C\p\System..dll
-r:C:\h\w\A6E7095C\p\Microsoft..dll
-r:C:\h\w\A6E7095C\p\xunit.*.dll
-r:C:\h\w\A


Stack trace
   at profiler_elt._slowpatheltleave_slowpatheltleave_._slowpatheltleave_slowpatheltleave_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Closing since this is a single failure.
