### ISSUE TITLE
SslStress build fails on Windows

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#84800]
Failures are happening since the 4th of April.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=237968&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=5eb51885-c505-5c55-9d72-61f5b1b42e84

```
panic: assignment to entry in nil map
System.Management.Automation.RemoteException
goroutine 36 [running]:
github.com/compose-spec/compose-go/types.MappingWithEquals.OverrideBy(...)
	github.com/compose-spec/compose-go@v1.13.2/types/types.go:427
github.com/docker/compose/v2/pkg/compose.(*composeService).build.func1({0x2b04d80, 0xc00055e1e0}, {0xc00032d548, 0x6})
	github.com/docker/compose/v2/pkg/compose/build.go:78 +0x7f4
github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
	github.com/docker/compose/v2/pkg/compose/dependencies.go:127 +0x63
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
docker-compose exited with error code 2
At D:\a\_work\1\s\src\libraries\System.Net.Security\tests\StressTests\SslStress\run-docker-compose.ps1:62 char:3
```

This is likely caused by update of go to 1.20.x in the runner image in combination with some weird side effect of #83211.
https://github.com/actions/runner-images/blob/win22/20230402.1/images/win/Windows2022-Readme.md
https://github.com/actions/runner-images/issues/7276

**Comment by antonfirsov** [comment]
Looks like we are hitting https://github.com/docker/compose/issues/10412, I recommend to wait for the upstream fix to propagate.

**Comment by antonfirsov** [comment]
This has been fixed by an upstream update around 04/28.
