### ISSUE TITLE
Test failure System.Net.Quic.Tests.QuicStreamTests.ReadWrite_Random_Success

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84816]
Run: [runtime-coreclr libraries-jitstress 20230413.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237678&view=ms.vss-test-web.build-test-results-tab&runId=4545162&resultId=168514&paneView=debug)

Failed test:
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_tiered-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- System.Net.Quic.Tests.QuicStreamTests.ReadWrite_Random_Success(readSize: 8192, writeSize: 8192)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWrite_Success(mode: AsyncAPM, writeSize: 10240, startWithFlush: True)
- System.Net.Quic.Tests.QuicStreamConformanceTests.Read_Eof_Returns0(mode: AsyncAPM, dataAvailableFirst: True)
- System.Net.Quic.Tests.QuicStreamConformanceTests.CopyToAsync_AllDataCopied(byteCount: 4096, useAsync: False)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired(flowExecutionContext: False, continueOnCapturedContext: True)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired(flowExecutionContext: False, continueOnCapturedContext: True)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success(mode: AsyncAPM)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(mode: AsyncAPM)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ZeroByteRead_BlocksUntilDataAvailableOrNops(mode: AsyncAPM)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException(cancellationDelay: 100)
- System.Net.Quic.Tests.QuicStreamConformanceTests.Read_DataStoredAtDesiredOffset(mode: AsyncAPM)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWrite_CustomMemoryManager_Success(useAsync: True)
- System.Net.Quic.Tests.QuicStreamConformanceTests.Dispose_ClosesStream(disposeMode: 1)
- System.Net.Quic.Tests.QuicStreamConformanceTests.Write_DataReadFromDesiredOffset(mode: AsyncAPM)
- System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_CancelPendingValueTask_ThrowsCancellationException(cancellationDelay: 100)
- System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientCompleteWrites_Success(extraCall: False)
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (The connection timed out from inactivity.) (The connection timed out from inactivity.)
---- System.Net.Quic.QuicException : The connection timed out from inactivity.
---- System.Net.Quic.QuicException : The connection timed out from inactivity.


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 288
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 318
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 318
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 282
   at System.Net.Quic.Tests.QuicStreamTests.ReadWrite_Random_Success(Int32 readSize, Int32 writeSize) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 364
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.Net.Quic.QuicException) -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 470
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 569
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 598
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 402
   at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass16_0.<<ReadWrite_Random_Success>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 381
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__0>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 292
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
----- Inner Stack Trace #2 (System.Net.Quic.QuicException) -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 470
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 569
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 598
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.OpenOutboundStreamAsync(QuicStreamType type, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 374
   at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass16_0.<<ReadWrite_Random_Success>b__0>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 367
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 298
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
```

**Comment by ManickaP** [comment]
Looks like a one-off fluke, for this run https://dev.azure.com/dnceng-public/public/_build/results?buildId=235855&view=ms.vss-test-web.build-test-results-tab the tests passed, and they were passing before.
Closing for now. We can re-open if this starts happening more often.
