### ISSUE TITLE
Test failure baseservices\\exceptions\\unittests\\EHPatternTests\\EHPatternTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84815]
Run: [runtime-coreclr r2r 20230412.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=237582&view=ms.vss-test-web.build-test-results-tab&runId=4544044&resultId=120445&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.11.Arm64.Open

- baseservices\\exceptions\\unittests\\EHPatternTests\\EHPatternTests.cmd
```
**Error message:**
```
Unhandled exception.
Cannot print exception string because Exception.ToString() failed.

Return code:      1
Raw output file:      C:\h\w\ACF60912\w\B00A09B6\uploads\Reports\baseservices.exceptions\unittests\EHPatternTests\EHPatternTests.output.txt
Raw output:
BEGIN EXECUTION
EHPatternTests.dll
1 file(s) copied.
6:51:06.64
Response file: C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\EHPatternTests.dll.rsp
C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\IL-CG2\EHPatternTests.dll
-o:C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\EHPatternTests.dll
--targetarch:arm
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\ACF60912\p\System..dll
-r:C:\h\w\ACF60912\p\Microsoft..dll
-r:C:\h\w\ACF60912\p\xunit.*.dll
-r:C:\h\w\ACF60912\p\mscorlib.dll
-r:C:\h\w\ACF60912\p\netstandard.dll
-O
" "dotnet" "C:\h\w\ACF60912\p\crossgen2\crossgen2.dll" @"C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\EHPatternTests.dll.rsp"   -r:C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\EHPatternTests.dll
" "dotnet" "C:\h\w\ACF60912\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\EHPatternTests.dll --out C:\h\w\ACF60912\w\B00A09B6\e\baseservices\exceptions\unittests\EHPatternTests\EHPatternTests.dll.r2rdump --val"
6:51:08.81
"C:\h\w\ACF60912\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  EHPatternTests.dll
BaseClassTest
System.IO.FileNotFoundException: 1
at BaseClassTest.f2()
at BaseClassTest.f1()
System.IO.FileNotFoundException: 1
at BaseClassTest.f1()
at BaseClassTest.Run()
0121: PASS
TryCatchInFinallyTest
System.InvalidProgramException: Common Language Runtime detected an invalid program.
at TryCatchInFinallyTest.Run()
0123456: PASS
RecurseTest
System.Exception: 7
at RecurseTest.DoTest(Int32 level)
System.Exception: 5
at RecurseTest.DoTest(Int32 level)
System.Exception: 3
at RecurseTest.DoTest(Int32 level)
System.Exception: 1
at RecurseTest.DoTest(Int32 level)
876543210: PASS
ThrowInFinallyNestedInTryTest
System.ArgumentException: Value does not fall within the expected range.
at ThrowInFinallyNestedInTryTest.MiddleMethod()
at ThrowInFinallyNestedInTryTest.Run()
0123456789a: PASS
GoryManagedPresentTest
System.DivideByZeroException: Attempted to divide by zero.
at GoryManagedPresentTest.foo(Int32 dummy)
at GoryManagedPresentTest.Run()
0123456: PASS
InnerFinallyAndCatchTest
abcdefghijklm13: PASS
InnerFinallyTest
try 1
try 1.1
finally 1.1
try 1.1.1
Throwing an exception here!
finally 1.1.1
catch 1
finally 1
: PASS
ThrowInFinallyTest
System.Exception: C
at ThrowInFinallyTest.Dumb()
at ThrowInFinallyTest.Run()
0123456789Ca: PASS
RecursiveRethrow
System.Exception: RecursionIsFun
at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
at RecursiveRethrow.LoveToRecurse(Int32 i)
at RecursiveRethrow.LoveToRecurse(Int32 i)
System.Exception: RecursionIsFun
at Re


Stack trace
   at baseservices_exceptions._unittests_EHPatternTests_EHPatternTests_._unittests_EHPatternTests_EHPatternTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by janvorli** [comment]
The `corerun.exe.9132.dmp` shows that an access violation happened in the `mark_bit_bit_of` function in GC with this interesting part of stack trace:
```
 # Child-SP RetAddr      Call Site
00 0537c770 73041ece     KERNELBASE!RaiseFailFastException+0x60
01 0537c998 73042820     coreclr!FailFastOnAssert+0x2b [D:\a\_work\1\s\src\coreclr\utilcode\debug.cpp @ 60] 
02 0537c9a0 7304236e     coreclr!_DbgBreakCheck+0x245 [D:\a\_work\1\s\src\coreclr\utilcode\debug.cpp @ 290] 
03 0537da58 73042496     coreclr!_DbgBreakCheckNoThrow+0x47 [D:\a\_work\1\s\src\coreclr\utilcode\debug.cpp @ 307] 
04 0537dab8 73033ab2     coreclr!DbgAssertDialog+0xfb [D:\a\_work\1\s\src\coreclr\utilcode\debug.cpp @ 459] 
05 0537db20 72dc927c     coreclr!CHECK::Trigger+0x17f [D:\a\_work\1\s\src\coreclr\utilcode\check.cpp @ 142] 
06 0537dba8 72dc8ee2     coreclr!CLRVectoredExceptionHandlerPhase3+0x1ed [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 7115] 
07 0537dc10 72dc8e7a     coreclr!CLRVectoredExceptionHandlerPhase2+0x53 [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 6869] 
08 0537dc68 72dc9484     coreclr!CLRVectoredExceptionHandler+0x137 [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 6836] 
09 0537dca8 77e79118     coreclr!CLRVectoredExceptionHandlerShim+0x165 [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 7509] 
0a 0537dcf0 77eb7770     ntdll!RtlRemoveVectoredExceptionHandler+0x249
0b 0537dd40 77e25cd8     ntdll!RtlLogStackBackTrace+0x7a1
0c 0537e070 73006b88     ntdll!KiUserExceptionDispatcher+0x9
0d (Inline) --------     coreclr!WKS::mark_bit_bit_of+0x5 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 8519] 
0e (Inline) --------     coreclr!WKS::gc_heap::mark_array_clear_marked+0x9 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 8549] 
0f 0537e270 7301d322     coreclr!WKS::gc_heap::clear_mark_array+0x85 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 8593] 
10 (Inline) --------     coreclr!WKS::gc_heap::seg_clear_mark_array_bits_soh+0x4f [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 11124] 
11 0537e290 72ea0b32     coreclr!WKS::gc_heap::remove_ro_segment+0x67 [D:\a\_work\1\s\src\coreclr\gc\gc.cpp @ 9640] 
12 0537e2c0 71e600a2     coreclr!GCInterface_UnregisterFrozenSegment+0x83 [D:\a\_work\1\s\src\coreclr\vm\comutilnative.cpp @ 1090] 
```

**Comment by cshung** [comment]
This function should only be called in the `Frozen` test case, are we sure this is reading the right dump?

> 11 0537e290 72ea0b32     coreclr!WKS::gc_heap::remove_ro_segment+0x67

The issue associated with `remove_ro_segment` is fixed [here](https://github.com/dotnet/runtime/pull/84734).

**Comment by janvorli** [comment]
Unfortunately, there is no dump for the EHPatternsTest. There is only one for the Frozen test and one for the coreroot_determinism test. I'll try to repro it  locally.

**Comment by mangod9** [comment]
Closing since this is not actionable currently due to no dump. Please reopen if it occurs again.
