### ISSUE TITLE
PipeReader.AdvanceTo throws InvalidCastException

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#849]
I'm puzzled by the fact that `PipeReader.AdvanceTo` accepts a `default(SequencePosition)` but throws `InvalidCastException` when provided a position from an empty sequence. Is that by design?

```cs
var pipe = new Pipe();
pipe.Reader.AdvanceTo(default); // this works
pipe.Reader.AdvanceTo(ReadOnlySequence<byte>.Empty.Start); // this throws InvalidCastException
```

Should it throw `ArgumentException` instead given the `SequencePosition` came from an unrelated `ReadOnlySequence<byte>`?

I'm a bit puzzled that `PipeReader.AdvanceTo` can be called before reading anyway.

**Comment by AArnott** [comment]
`AdvanceTo(default)` throws something reasonable now:

```
Unhandled exception. System.InvalidOperationException: NoReadingOperationToComplete
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadToComplete()
   at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed)
   at Program.Main()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

But `AdvanceTo(ReadOnlySequence<byte>.Empty.Start)` still throws badly (in fact, the exception message looks like it is a token that was meant to be replaced):

```
Unhandled exception. System.InvalidCastException: Arg_InvalidCastException
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed, SequencePosition& examined)
   at System.IO.Pipelines.Pipe.AdvanceReader(SequencePosition& consumed)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed)
   at Program.Main()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by TheActualTwinkle** [comment]
I looked into this on current main. The `InvalidCastException` comes from the direct casts of `SequencePosition.GetObject()` to `BufferSegment` in `Pipe.AdvanceReader`. I also found the same pattern in `StreamPipeReader.AdvanceTo`.

For a position from an unrelated sequence, should this throw `ArgumentException`, as originally suggested, or `InvalidOperationException` through the existing invalid-cursor path? Should the fix cover both implementations? I'd like to work on this once the intended exception and scope are confirmed.
