### ISSUE TITLE
Test failure Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84914]
Run: [runtime-coreclr ilasm 20230415.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=240791&view=ms.vss-test-web.build-test-results-tab&runId=4623314&resultId=101167&paneView=debug)

Failed test:
```
coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\B28409BA\w\AC66093D\uploads\Reports\Interop.NativeLibrary\API\NativeLibraryTests\NativeLibraryTests.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\B28409BA\p\ildasm.exe /raweh /unicode /out=NativeLibraryTests.dasm.il NativeLibraryTests.dll
C:\h\w\B28409BA\p\ilasm.exe /output=NativeLibraryTests.asm.dll  NativeLibraryTests.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'NativeLibraryTests.dasm.il'  to EXE --> 'NativeLibraryTests.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
Assembled method GetLibraryExportTests?<>c__DisplayClass8_0::.ctor
Assembled method GetLibraryExportTests?<>c__DisplayClass8_0::<GetLibraryExport>b__0
Assembled method GetLibraryExportTests?<>c__DisplayClass9_0::.ctor
Assembled method GetLibraryExportTests?<>c__DisplayClass9_0::<TryGetLibraryExport>b__0
Assembled method GetLibraryExportTests::.ctor
Assembled method GetLibraryExportTests::GetValidExport_ManualMangling
Assembled method GetLibraryExportTests::GetValidExport
Assembled method GetLibraryExportTests::NullHandle
Assembled method GetLibraryExportTests::NullExport
Assembled method GetLibraryExportTests::ExportDoesNotExist
Assembled method GetLibraryExportTests::Dispose
Assembled method GetLibraryExportTests::GetLibraryExport
Assembled method GetLibraryExportTests::TryGetLibraryExport
Assembled method GetLibraryExportTests::RunExportedFunction
Assembled method GetMainProgramHandleTests?<>c__DisplayClass9_0::.ctor
Assembled method GetMainProgramHandleTests?<>c__DisplayClass9_0::<GetSymbolFromMainProgramHandle>b__0
Assembled method GetMainProgramHandleTests::CanAccessCoreRunExportFromMainProgramHandle
Assembled method GetMainProgramHandleTests::NativeLibraryLoadDoesNotLoadSymbolsGlobally
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle
Assembled method GetMainProgramHandleTests::InvalidSymbolName_Fails
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle_Mangling
Assembled method GetMainProgramHandleTests::FreeMainProgramHandle
Assembled method GetMainProgramHandleTests::get_IsHostedByCoreRun
Assembled method GetMainProgramHandleTests::GetSymbolFromMainProgramHandle
Assembled method GetMainProgramHandleTests::LoadLibraryGlobally
Assembled method GetMainProgramHandleTests::.ctor
Assembled method GetMainProgramHandleTests::.cctor
Assembled method NativeLibraryTests?<>c__DisplayClass24_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass24_0::<LoadLibrary_NameOnly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass25_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass25_0::<TryLoadLibrary_NameOnly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass26_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass26_0::<LoadLibrary_WithAssembly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass27_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass27_0::<TryLoadLibrary_WithAssembly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass28_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass28_0::<FreeLibrary>b__0
Assembled method NativeLibraryTests::.ctor
Assembled method NativeLibraryTests::LoadLibraryFullPath_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnNonExistentFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnInvalidFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryRelativePaths_NameOnly
Assembled method NativeLibraryTe


Stack trace
   at Interop_NativeLibrary._API_NativeLibraryTests_NativeLibraryTests_._API_NativeLibraryTests_NativeLibraryTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
Full message:

```
    Interop\NativeLibrary\API\NativeLibraryTests\NativeLibraryTests.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\B28409BA\w\AC66093D\uploads\Reports\Interop.NativeLibrary\API\NativeLibraryTests\NativeLibraryTests.output.txt
      Raw output:
      BEGIN EXECUTION
      C:\h\w\B28409BA\p\ildasm.exe /raweh /unicode /out=NativeLibraryTests.dasm.il NativeLibraryTests.dll
      C:\h\w\B28409BA\p\ilasm.exe /output=NativeLibraryTests.asm.dll  NativeLibraryTests.dasm.il
      
      .NET IL Assembler.  Version 8.0.0-ci
      Copyright (c) Microsoft Corporation.  All rights reserved.
      Assembling 'NativeLibraryTests.dasm.il'  to EXE --> 'NativeLibraryTests.asm.dll'
      Source file is UNICODE
      
      Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
      Assembled method GetLibraryExportTests?<>c__DisplayClass8_0::.ctor
      Assembled method GetLibraryExportTests?<>c__DisplayClass8_0::<GetLibraryExport>b__0
      Assembled method GetLibraryExportTests?<>c__DisplayClass9_0::.ctor
      Assembled method GetLibraryExportTests?<>c__DisplayClass9_0::<TryGetLibraryExport>b__0
      Assembled method GetLibraryExportTests::.ctor
      Assembled method GetLibraryExportTests::GetValidExport_ManualMangling
      Assembled method GetLibraryExportTests::GetValidExport
      Assembled method GetLibraryExportTests::NullHandle
      Assembled method GetLibraryExportTests::NullExport
      Assembled method GetLibraryExportTests::ExportDoesNotExist
      Assembled method GetLibraryExportTests::Dispose
      Assembled method GetLibraryExportTests::GetLibraryExport
      Assembled method GetLibraryExportTests::TryGetLibraryExport
      Assembled method GetLibraryExportTests::RunExportedFunction
      Assembled method GetMainProgramHandleTests?<>c__DisplayClass9_0::.ctor
      Assembled method GetMainProgramHandleTests?<>c__DisplayClass9_0::<GetSymbolFromMainProgramHandle>b__0
      Assembled method GetMainProgramHandleTests::CanAccessCoreRunExportFromMainProgramHandle
      Assembled method GetMainProgramHandleTests::NativeLibraryLoadDoesNotLoadSymbolsGlobally
      Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle
      Assembled method GetMainProgramHandleTests::InvalidSymbolName_Fails
      Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle_Mangling
      Assembled method GetMainProgramHandleTests::FreeMainProgramHandle
      Assembled method GetMainProgramHandleTests::get_IsHostedByCoreRun
      Assembled method GetMainProgramHandleTests::GetSymbolFromMainProgramHandle
      Assembled method GetMainProgramHandleTests::LoadLibraryGlobally
      Assembled method GetMainProgramHandleTests::.ctor
      Assembled method GetMainProgramHandleTests::.cctor
      Assembled method NativeLibraryTests?<>c__DisplayClass24_0::.ctor
      Assembled method NativeLibraryTests?<>c__DisplayClass24_0::<LoadLibrary_NameOnly>b__0
      Assembled method NativeLibraryTests?<>c__DisplayClass25_0::.ctor
      Assembled method NativeLibraryTests?<>c__DisplayClass25_0::<TryLoadLibrary_NameOnly>b__0
      Assembled method NativeLibraryTests?<>c__DisplayClass26_0::.ctor
      Assembled method NativeLibraryTests?<>c__DisplayClass26_0::<LoadLibrary_WithAssembly>b__0
      Assembled method NativeLibraryTests?<>c__DisplayClass27_0::.ctor
      Assembled method NativeLibraryTests?<>c__DisplayClass27_0::<TryLoadLibrary_WithAssembly>b__0
      Assembled method NativeLibraryTests?<>c__DisplayClass28_0::.ctor
      Assembled method NativeLibraryTests?<>c__DisplayClass28_0::<FreeLibrary>b__0
      Assembled method NativeLibraryTests::.ctor
      Assembled method NativeLibraryTests::LoadLibraryFullPath_NameOnly
      Assembled method NativeLibraryTests::LoadLibraryOnNonExistentFile_NameOnly
      Assembled method NativeLibraryTests::LoadLibraryOnInvalidFile_NameOnly
      Assembled method NativeLibraryTests::LoadLibraryRelativePaths_NameOnly
      Assembled method NativeLibraryTests::LoadLibraryFullPath_WithAssembly
      Assembled method NativeLibraryTests::LoadLibraryOnNonExistentFile_WithAssembly
      Assembled method NativeLibraryTests::LoadLibraryOnInvalidFile_WithAssembly
      Assembled method NativeLibraryTests::LoadLibraryNameOnly_WithAssembly
      Assembled method NativeLibraryTests::LoadLibraryFileName_WithAssembly
      Assembled method NativeLibraryTests::LoadLibraryFullPathWithoutNativePrefixOrSuffix_WithAssembly_Success
      Assembled method NativeLibraryTests::LoadLibraryFullPathWithoutNativePrefixOrSuffix_WithAssembly_Failure
      Assembled method NativeLibraryTests::get_HasKnownLibraryInSystemDirectory
      Assembled method NativeLibraryTests::LoadSystemLibrary_WithSearchPath
      Assembled method NativeLibraryTests::LoadLibrary_NullLibName
      Assembled method NativeLibraryTests::LoadLibrary_NullAssembly
      Assembled method NativeLibraryTests::LoadLibrary_UsesFullPath_EvenWhen_AssemblyDirectory_Specified
      Assembled method NativeLibraryTests::LoadLibrary_AssemblyDirectory
      Assembled method NativeLibraryTests::Free
      Assembled method NativeLibraryTests::Dispose
      Assembled method NativeLibraryTests::LoadLibrary_NameOnly
      Assembled method NativeLibraryTests::TryLoadLibrary_NameOnly
      Assembled method NativeLibraryTests::LoadLibrary_WithAssembly
      Assembled method NativeLibraryTests::TryLoadLibrary_WithAssembly
      Assembled method NativeLibraryTests::FreeLibrary
      Assembled method TestHelpers::EXPECT
      Assembled method TestHelpers::Run
      Assembled method NativeLibraryToLoad::GetFileName
      Assembled method NativeLibraryToLoad::GetLibraryFileName
      Assembled method NativeLibraryToLoad::GetFullPath
      Assembled method NativeLibraryToLoad::GetDirectory
      Assembled method NativeLibraryToLoad::.ctor
      Assembled method __GeneratedMainWrapper::Main
      Assembled method __GeneratedMainWrapper::.ctor
      Creating PE file
      
      Emitting classes:
      Class 1:System.Runtime.CompilerServices.NullablePublicOnlyAttribute
      Class 2:Microsoft.CodeAnalysis.EmbeddedAttribute
      Class 3:System.Runtime.CompilerServices.NullableAttribute
      Class 4:System.Runtime.CompilerServices.NullableContextAttribute
      Class 5:GetLibraryExportTests
      Class 6:GetLibraryExportTests?NativeFunctionWrapper
      Class 7:GetLibraryExportTests?<>c__DisplayClass8_0
      Class 8:TestResult
      Class 9:GetLibraryExportTests?<>c__DisplayClass9_0
      Class 10:NativeLibraryToLoad
      Class 11:TestHelpers
      Class 12:GetMainProgramHandleTests
      Class 13:GetMainProgramHandleTests?<>c__DisplayClass9_0
      Class 14:NativeLibraryTests
      Class 15:NativeLibraryTests?<>c__DisplayClass24_0
      Class 16:NativeLibraryTests?<>c__DisplayClass25_0
      Class 17:NativeLibraryTests?<>c__DisplayClass26_0
      Class 18:NativeLibraryTests?<>c__DisplayClass27_0
      Class 19:NativeLibraryTests?<>c__DisplayClass28_0
      Class 20:__GeneratedMainWrapper
      
      Emitting fields and methods:
      Global 
      Class 1Fields: 1;Methods: 1;
      Class 2Methods: 1;
      Class 3Fields: 1;Methods: 2;
      Class 4Fields: 1;Methods: 1;
      Class 5Fields: 1;Methods: 10;
      Class 6Methods: 4;
      Class 7Fields: 2;Methods: 2;
      Class 8Fields: 12;
      Class 9Fields: 2;Methods: 2;
      Class 10Fields: 2;Methods: 5;
      Class 11Methods: 2;
      Class 12Fields: 1;Methods: 12;
      Class 13Fields: 1;Methods: 2;
      Class 14Fields: 3;Methods: 25;
      Class 15Fields: 2;Methods: 2;
      Class 16Fields: 2;Methods: 2;
      Class 17Fields: 4;Methods: 2;
      Class 18Fields: 4;Methods: 2;
      Class 19Fields: 1;Methods: 2;
      Class 20Methods: 2;
      Resolving local member refs: 335 -> 335 defs, 0 refs, 0 unresolved
      
      Emitting events and properties:
      Global 
      Class 1
      Class 2
      Class 3
      Class 4
      Class 5
      Class 6
      Class 7
      Class 8
      Class 9
      Class 10
      Class 11
      Class 12Props: 1;
      Class 13
      Class 14Props: 1;
      Class 15
      Class 16
      Class 17
      Class 18
      Class 19
      Class 20
      Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
      Writing PE file
      Operation completed successfully
       "C:\h\w\B28409BA\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  NativeLibraryTests.asm.dll 
      System.IO.FileNotFoundException: Could not load file or assembly 'C:\h\w\B28409BA\w\AC66093D\e\Interop\NativeLibrary\API\NativeLibraryTests\subdirectory\NativeLibraryTests.asm-in-subdirectory.dll'. The system cannot find the file specified.
      File name: 'C:\h\w\B28409BA\w\AC66093D\e\Interop\NativeLibrary\API\NativeLibraryTests\subdirectory\NativeLibraryTests.asm-in-subdirectory.dll'
         at System.Reflection.Assembly.LoadFile(String path)
         at NativeLibraryTests.LoadLibrary_AssemblyDirectory()
         at __GeneratedMainWrapper.Main()
      END EXECUTION OF IL{D}ASM BINARY - FAILED 101 vs 100
```

**Comment by BruceForstall** [comment]
@elinor-fung Looks like you changed this test recently in a way that might break ilasm round-trip testing.

Maybe mark it `<IlasmRoundTripIncompatible>true</IlasmRoundTripIncompatible>` if there's no easy way to fix that?

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr ilasm 20230429.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257167&view=ms.vss-test-web.build-test-results-tab&runId=5019084&resultId=100243&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
coreclr linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
    - Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
coreclr osx x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr osx arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
```

**Error message:**
```
 
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/ildasm -raweh -unicode -out=NativeLibraryTests.dasm.il NativeLibraryTests.dll
/root/helix/work/correlation/ilasm -output=NativeLibraryTests.asm.dll NativeLibraryTests.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling &#39;NativeLibraryTests.dasm.il&#39;  to EXE --&gt; &#39;NativeLibraryTests.asm.dll&#39;
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass8_0::.ctor
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass8_0::&lt;GetLibraryExport&gt;b__0
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass9_0::.ctor
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass9_0::&lt;TryGetLibraryExport&gt;b__0
Assembled method GetLibraryExportTests::.ctor
Assembled method GetLibraryExportTests::GetValidExport_ManualMangling
Assembled method GetLibraryExportTests::GetValidExport
Assembled method GetLibraryExportTests::NullHandle
Assembled method GetLibraryExportTests::NullExport
Assembled method GetLibraryExportTests::ExportDoesNotExist
Assembled method GetLibraryExportTests::Dispose
Assembled method GetLibraryExportTests::GetLibraryExport
Assembled method GetLibraryExportTests::TryGetLibraryExport
Assembled method GetLibraryExportTests::RunExportedFunction
Assembled method GetMainProgramHandleTests�&lt;&gt;c__DisplayClass9_0::.ctor
Assembled method GetMainProgramHandleTests�&lt;&gt;c__DisplayClass9_0::&lt;GetSymbolFromMainProgramHandle&gt;b__0
Assembled method GetMainProgramHandleTests::CanAccessCoreRunExportFromMainProgramHandle
Assembled method GetMainProgramHandleTests::NativeLibraryLoadDoesNotLoadSymbolsGlobally
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle
Assembled method GetMainProgramHandleTests::InvalidSymbolName_Fails
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle_Mangling
Assembled method GetMainProgramHandleTests::FreeMainProgramHandle
Assembled method GetMainProgramHandleTests::get_IsHostedByCoreRun
Assembled method GetMainProgramHandleTests::GetSymbolFromMainProgramHandle
Assembled method GetMainProgramHandleTests::LoadLibraryGlobally
Assembled method GetMainProgramHandleTests::.ctor
Assembled method GetMainProgramHandleTests::.cctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass24_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass24_0::&lt;LoadLibrary_NameOnly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass25_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass25_0::&lt;TryLoadLibrary_NameOnly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass26_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass26_0::&lt;LoadLibrary_WithAssembly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass27_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass27_0::&lt;TryLoadLibrary_WithAssembly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass28_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass28_0::&lt;FreeLibrary&gt;b__0
Assembled method NativeLibraryTests::.ctor
Assembled method NativeLibraryTests::LoadLibraryFullPath_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnNonExistentFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnInvalidFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryRelativePaths_NameOnly
Assembled method NativeLibraryTests::LoadLibraryFullPath_WithAssembly
Assembled 
```

**Stack trace:**
```
    at Interop_NativeLibrary._API_NativeLibraryTests_NativeLibraryTests_._API_NativeLibraryTests_NativeLibraryTests_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-29T20:59:11.978Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Reason":"Schedule","operatingSystem":"OSX.1200.Amd64.Open","DefinitionId":"140","System.JobAttempt":"1","BuildId":"257167","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"5019544","Project":"public","System.PhaseAttempt":"1","System.StageName":"Build","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildNumber":"20230429.1","System.JobName":"__default","architecture":"x64","configuration":"Checked-ilasmroundtrip"} | Schedule
