### ISSUE TITLE
Linux musl x64 build break apparently due to some libc version mismatch (high priority as it is blocking clean CI)

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#84949]
Platform: **Linux musl x64**
Example run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=241777&view=logs&j=92e17f34-a5d5-5d2c-e1e5-826eb9786835&t=8b99f496-81fe-5fa6-0e3e-125347621b1c

Diagnostics:

<pre>
  249 / 264 (94%, 249 failed): failed in 667 msecs, exit code 134, expected 0: dotnet /__w/1/s/artifacts/bin/coreclr/linux.x64.Checked/crossgen2/crossgen2.dll @/__w/1/s/artifacts/tests/coreclr/obj/linux.x64.Checked/crossgen.out/System.Runtime.Loader.dll.rsp
  !! Unhandled exception. System.DllNotFoundException: Unable to load shared library 'jitinterface_x64' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
  !! /__w/1/s/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.3.23174.8/jitinterface_x64.so: cannot open shared object file: No such file or directory
  !! /__w/1/s/artifacts/bin/coreclr/linux.x64.Checked/crossgen2/jitinterface_x64.so: cannot open shared object file: No such file or directory
  !! /__w/1/s/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.3.23174.8/libjitinterface_x64.so: cannot open shared object file: No such file or directory
  !! libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
  !! /__w/1/s/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.3.23174.8/jitinterface_x64: cannot open shared object file: No such file or directory
  !! /__w/1/s/artifacts/bin/coreclr/linux.x64.Checked/crossgen2/jitinterface_x64: cannot open shared object file: No such file or directory
  !! /__w/1/s/.dotnet/shared/Microsoft.NETCore.App/8.0.0-preview.3.23174.8/libjitinterface_x64: cannot open shared object file: No such file or directory
  !! /__w/1/s/artifacts/bin/coreclr/linux.x64.Checked/crossgen2/libjitinterface_x64: cannot open shared object file: No such file or directory
  !!    at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
  !!    at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
  !!    at Internal.JitInterface.JitConfigProvider.<>c__DisplayClass5_0.<Initialize>b__0(String libName, Assembly assembly, Nullable`1 searchPath) in /_/src/coreclr/tools/Common/JitInterface/JitConfigProvider.cs:line 59
  !!    at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
  !!    at Internal.JitInterface.CorInfoImpl.GetJitHost(IntPtr configProvider)
  !!    at Internal.JitInterface.CorInfoImpl.Startup(CORINFO_OS os) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 179
  !!    at Internal.JitInterface.JitConfigProvider.Initialize(TargetDetails target, IEnumerable`1 jitFlags, IEnumerable`1 parameters, String jitPath) in /_/src/coreclr/tools/Common/JitInterface/JitConfigProvider.cs:line 64
  !!    at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilationBuilder.cs:line 296
  !!    at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, ReadyToRunCompilerContext typeSystemContext) in /_/src/coreclr/tools/aot/crossgen2/Program.cs:line 613
  !!    at ILCompiler.Program.Run() in /_/src/coreclr/tools/aot/crossgen2/Program.cs:line 289
  !!    at ILCompiler.Crossgen2RootCommand.<>c__DisplayClass187_0.<.ctor>b__0(InvocationContext context) in /_/src/coreclr/tools/aot/crossgen2/Crossgen2RootCommand.cs:line 293
  !!    at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
  !!    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  !! --- End of stack trace from previous location ---
  !!    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseErrorReporting>b__0>d.MoveNext()
  !! --- End of stack trace from previous location ---
  !!    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
  !! --- End of stack trace from previous location ---
  !!    at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
  !! --- End of stack trace from previous location ---
  !!    at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
  !!    at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
  !!    at System.CommandLine.Parsing.ParseResultExtensions.Invoke(ParseResult parseResult, IConsole console)
  !!    at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
  !!    at ILCompiler.Program.Main(String[] args) in /_/src/coreclr/tools/aot/crossgen2/Program.cs:line 890
</pre>

/cc @janvorli @sbomer @dotnet/runtime-infrastructure @dotnet/crossgen-contrib

**Comment by janvorli** [comment]
The error sounds as if we attempted to load MUSL version of the libjitinterface_x64.so on a glibc distro.

**Comment by janvorli** [comment]
But the log seems correct - I can see 
__DistroRid: linux-musl-x64

**Comment by janvorli** [comment]
@sbomer It looks like the cross build is attempting to use crossgen2 with MUSL version of JIT native libraries while it should use the glibc ones.

**Comment by trylek** [comment]
@janvorli - I see, so am I right to understand that in this particular case <code>HostArchitecture=Linux</code> whereas <code>TargetArchitecture=Linux_musl</code> and some code publishing the JIT native libraries uses the <code>TargetArchitecture</code> version instead of the <code>HostArchitecture</code> which should be used instead as that's the OS on which the build is running?

**Comment by trylek** [comment]
I have asked @davidwrighton offline for help as I believe he wrote most of these scripts, I'll continue working on this tomorrow if we don't nail it down before EOD today. One thing I'm still missing is why has this blown up right now considering we've been running Linux-musl tests for years as far as I recall?

**Comment by janvorli** [comment]
> why has this blown up right now

Because we've never cross built x64 musl on x64 glibc before

**Comment by trylek** [comment]
I see, thanks for explaining.

**Comment by trylek** [comment]
By the way, do we know why the PR run on https://github.com/dotnet/runtime/pull/84148 didn't catch this while obviously subsequent PR / CI runs have been hitting this? Three years ago, Santi wrote this filtering logic so that we decide what tests to run based on the extent of a PR, is there a mapping we're missing in the vein of, if we're touching this bit of code, we need to rerun these tests?

**Comment by trylek** [comment]
I see, thanks for explaining. At some point I was convinced I was seeing these failures in the CI runs but you're right it doesn't make sense, we're only running the R2R legs in outerloop. It would be nice to add at least minimum coverage to PR but the dnceng team used to be strongly opposed to that as PR costs are already too high, perhaps if we manage to save some time elsewhere we might be able to do that.
