### ISSUE TITLE
BigInteger has a buggy assert

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#84991]
```C#
[Fact]
public static void Repro()
{
    BigInteger.TryParse("FFFFFFFF0", NumberStyles.HexNumber, null, out _);
}
```
That crashes in debug with:
```
     at System.Numerics.BigInteger.AssertValid() in D:\repos\runtime\src\libraries\System.Runtime.Numerics\src\System\Numerics\BigInteger.cs:line 3154
     at System.Numerics.BigInteger..ctor(Int32 n, UInt32[] rgu) in D:\repos\runtime\src\libraries\System.Runtime.Numerics\src\System\Numerics\BigInteger.cs:line 485
     at System.Numerics.BigNumber.HexNumberToBigInteger(BigNumberBuffer& number, BigInteger& result) in D:\repos\runtime\src\libraries\System.Runtime.Numerics\src\System\Numerics\BigNumber.cs:line 502
     at System.Numerics.BigNumber.TryParseBigInteger(ReadOnlySpan`1 value, NumberStyles style, NumberFormatInfo info, BigInteger& result) in D:\repos\runtime\src\libraries\System.Runtime.Numerics\src\System\Numerics\BigNumber.cs:line 372
     at System.Numerics.BigNumber.TryParseBigInteger(String value, NumberStyles style, NumberFormatInfo info, BigInteger& result) in D:\repos\runtime\src\libraries\System.Runtime.Numerics\src\System\Numerics\BigNumber.cs:line 353
     at System.Numerics.BigInteger.TryParse(String value, NumberStyles style, IFormatProvider provider, BigInteger& result) in D:\repos\runtime\src\libraries\System.Runtime.Numerics\src\System\Numerics\BigInteger.cs:line 688
```
due to this assert:
https://github.com/dotnet/runtime/blob/634cc1e04e91b2b264a57798a2c733ae261758f9/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L3153-L3154

**Comment by stephentoub** [comment]
The assert has been commented out for now with a todo against this issue:
https://github.com/dotnet/runtime/blob/7b662a7e264552ea19a51a0135f2441bd5f141aa/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L3153-L3154
