### ISSUE TITLE
ContentDisposition.ToString() will generate \r\n when FileName use long chinese  string

### ISSUE THREAD

**Issue by jnzhsh** [dotnet/runtime#85091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Initialization  ContentDisposition  like this
``` c#
System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
. {
.     FileName = "第九届第九届第九届-第九届第九届第九届第九届.pdf",
.     Inline = true 
. };
cd.ToString()
```
the string output like `"inline; filename=\"=?utf-8?B?56ys5Lmd5bGK56ys5Lmd5bGK56ys5Lmd5bGKLeesrOS5neWxiuesrOS5?=\r\n =?utf-8?B?neWxiuesrOS5neWxiuesrOS5neWxii5wZGY=?=\""`
when l use this string to Initialization  response header
`Response.Headers.Add("Content-Disposition", cd.ToString());`
it will throw Exception like this 
```
system.InvalidOperationException: Invalid non-ASCII or control character in header: 0x000D
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(String headerName, StringValues headerValues, Func`2 encodingSelector)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
```

### Expected Behavior

No Error

### .NET Version

6.0.401

### Anything else?

asp.net  core version 
![image](https://user-images.githubusercontent.com/32035323/233294735-0b4abe85-e499-4c63-8274-8187b3947d1e.png)

**Comment by mitchdenny** [comment]
This looks like a runtime issue to me rather than ASP.NET Core specifically.

**Comment by jnzhsh** [comment]
> This looks like a runtime issue to me rather than ASP.NET Core specifically.

This is my dotnet  info
```
dotnet --info
.NET SDK:
 Version:   6.0.401
 Commit:    0906eae6f8

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jnzhsh** [comment]
I use the class `System.Net.Http.Headers.ContentDispositionHeaderValue` instead. 
It solved my problem
