### ISSUE TITLE
Test failure System.Threading.ThreadPools.Tests.ThreadPoolTests.FileStreamFlushAsyncThreadPoolDeadlockTest

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85211]
**Failed in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230422.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=248636&view=ms.vss-test-web.build-test-results-tab&runId=4800170&resultId=178164&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Threading.ThreadPools.Tests.ThreadPoolTests.FileStreamFlushAsyncThreadPoolDeadlockTest
```

**Error message:**
```
 Half-way through waiting for remote process.
Timed out at 4/22/2023 9:42:05 AM after 60000ms waiting for remote process.
	Process ID: 298
	Handle: 1440
	Name: dotnet
	MainModule: /root/helix/work/correlation/dotnet
	StartTime: 4/22/2023 9:41:05 AM
	TotalProcessorTime: 00:00:04.7300000

```

**Stack trace:**
```
    at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.FileStreamFlushAsyncThreadPoolDeadlockTest() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 1032
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```



**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL.

**Comment by kunalspathak** [comment]
The failure happened on 4/22, but 3 recent runs, [this](https://dev.azure.com/dnceng-public/public/_build/results?buildId=250917&view=ms.vss-test-web.build-test-results-tab), [this](https://dev.azure.com/dnceng-public/public/_build/results?buildId=256997&view=ms.vss-test-web.build-test-results-tab) and [this](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257540&view=ms.vss-test-web.build-test-results-tab), they don't show up. I will close the issue.
