### ISSUE TITLE
SEHException (0x80004005): External component has thrown an exception

### ISSUE THREAD

**Issue by akirayamamoto** [dotnet/runtime#85231]
### Description

We are intermittently getting an `SEHException` when opening an `X509Store`.

### Reproduction Steps

```
var store = new X509Store("Something", StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite);
```

### Expected behavior

We would not expect any exceptions here.

### Actual behavior

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Interop.crypt32.CertControlStore(SafeCertStoreHandle hCertStore, CertControlStoreFlags dwFlags, CertControlStoreType dwControlType, IntPtr pvCtrlPara)
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Octopus.Shared.Security.Certificates.CertificateEncoder.FromBase64String(String thumbprint, String certificateString, String password, ILog log, Boolean storeInKeyStore) in ./source/Octopus.Shared/Security/Certificates/CertificateEncoder.cs:line 95
   at Octopus.Shared.Security.Certificates.CertificateEncoder.FromBase64String(String thumbprint, String certificateString, String password, ILog log) in ./source/Octopus.Shared/Security/Certificates/CertificateEncoder.cs:line 75
   at Octopus.Shared.Security.Certificates.CertificateEncoder.FromBase64String(String certificateString, ILog log) in ./source/Octopus.Shared/Security/Certificates/CertificateEncoder.cs:line 71
   at Octopus.Core.Initialization.BuiltIn.OctopusCertificateInitializer.Initialize(IRawRelationalStore store) in ./source/Octopus.Core/Initialization/BuiltIn/OctopusCertificateInitializer.cs:line 49
   at Octopus.Core.Initialization.StoreInitializer.Initialize() in ./source/Octopus.Core/Initialization/StoreInitializer.cs:line 19
   at Octopus.Server.OctopusServerEngine.Start() in ./source/Octopus.Server/OctopusServerEngine.cs:line 70
   at Octopus.Server.Commands.RunCommand.Start() in ./source/Octopus.Server/Commands/RunCommand.cs:line 89
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in ./source/Octopus.Shared/Startup/AbstractCommand.cs:line 101
   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime) in ./source/Octopus.Shared/Startup/OctopusProgram.cs:line 504
   at Octopus.Shared.Startup.WindowsServiceHost.<>c__DisplayClass2_0.<Run>b__0() in ./source/Octopus.Shared/Startup/WindowsServiceHost.cs:line 26
   at Octopus.Shared.Startup.WindowsServiceAdapter.RunService() in ./source/Octopus.Shared/Startup/WindowsServiceAdapter.cs:line 48
   at System.Threading.Thread.StartCallback()
```

### Known Workarounds

None at the moment.

### Configuration

Which version of .NET is the code running on?
`Microsoft.NETCore.App 6.0.16`
`dotnet sdk 6.0.408`

What OS and version, and what distro if applicable?
Windows Server 2016 and 2019.

What is the architecture (x64, x86, ARM, ARM64)?
x86.

Do you know whether it is specific to that configuration?
This issue does not happen on Linux.

### Other information

We are getting the same issue in this [piece of code here](https://github.com/OctopusDeploy/Halibut/blob/eb51216b8796db2a0b1f6828acd41ec9683c65cc/source/Halibut/Transport/DiscoveryClient.cs#L32):

```
Halibut.HalibutClientException: External component has thrown an exception.
 ---> System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Interop.crypt32.CertGetCertificateChain(IntPtr hChainEngine, SafeCertContextHandle pCertContext, FILETIME* pTime, SafeCertStoreHandle hStore, CERT_CHAIN_PARA& pChainPara, CertChainFlags dwFlags, IntPtr pvReserved, SafeX509ChainHandle& ppChainContext)
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, X509Certificate2Collection customTrustStore, X509ChainTrustMode trustMode, DateTime verificationTime, TimeSpan timeout, Boolean disableAia)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException)
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate)
   at System.Net.CertificateValidation.BuildChainAndVerifyProperties(X509Chain chain, X509Certificate2 remoteCertificate, Boolean checkCertName, Boolean isServer, String hostName)
   at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Halibut.Transport.DiscoveryClient.Discover(ServiceEndPoint serviceEndpoint, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Halibut.Transport.DiscoveryClient.Discover(ServiceEndPoint serviceEndpoint, CancellationToken cancellationToken)
   at Halibut.HalibutRuntime.Discover(ServiceEndPoint endpoint, CancellationToken cancellationToken)
   at Halibut.HalibutRuntime.Discover(ServiceEndPoint endpoint)
   at Octopus.Server.Orchestration.MachineDiscovery.TentacleDiscovery.Discover(String host, Int32 port, ProxyDetails proxy) in ./source/Octopus.Server/Orchestration/MachineDiscovery/TentacleDiscovery.cs:line 27
   at Octopus.Server.Web.Handlers.DiscoverDeploymentTargetRequestHandler.Discover(DiscoveryEndpointDetails endpointDetails, Proxy proxy) in ./source/Octopus.Server/Web/Handlers/DiscoverDeploymentTargetRequestHandler.cs:line 92
   at Octopus.Server.Web.Handlers.DiscoverDeploymentTargetRequestHandler.Handle(DiscoverDeploymentTargetRequest request, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Handlers/DiscoverDeploymentTargetRequestHandler.cs:line 63
   at Octopus.Core.Infrastructure.Mediator.AutofacMediator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/AutofacMediator.cs:line 37
   at Octopus.Core.Infrastructure.Mediator.Decorators.SystemComponentModelValidationDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/SystemComponentModelValidationDecorator.cs:line 60
   at Octopus.Core.Infrastructure.Mediator.Decorators.FluentValidationsDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/FluentValidationsDecorator.cs:line 78
   at Octopus.Core.Infrastructure.Mediator.Decorators.MessageBusSiphoningDecorator.Request[TRequest,TResponse](IRequest`2 request, CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/Mediator/Decorators/MessageBusSiphoningDecorator.cs:line 37
   at Octopus.Server.Web.Controllers.DeploymentTargets.DiscoverDeploymentTargetController.DiscoverDeploymentTarget(DiscoverDeploymentTargetRequest request, CancellationToken cancellationToken) in ./source/Octopus.Server/Web/Controllers/DeploymentTargets/DiscoverDeploymentTargetController.cs:line 21
   at lambda_method23135(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Octopus.Server.Web.Middleware.BoundaryTrailerRewriteMiddleware.Invoke(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/BoundaryTrailerRewriteMiddleware.cs:line 44
   at Octopus.Server.Web.Infrastructure.Authentication.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in ./source/Octopus.Server/Web/Infrastructure/Authentication/AuthorizationMiddlewareResultHandler.cs:line 50
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 46
   at Octopus.Server.Web.UnitOfWorkMiddleware.InvokeAsync(HttpContext httpContext, IUnitOfWork unitOfWork) in ./source/Octopus.Server/Web/UnitOfWorkMiddleware.cs:line 46
   at Octopus.Server.Web.Middleware.OctopusClientOldVersionWarningMiddleware.InvokeAsync(HttpContext context, IAutomationContext automationContext) in ./source/Octopus.Server/Web/Middleware/OctopusClientOldVersionWarningMiddleware.cs:line 52
   at Octopus.Server.Web.Middleware.DynamicContentHeadersMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/DynamicContentHeadersMiddleware.cs:line 48
   at Octopus.Server.Web.Middleware.MaintenanceModeMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/MaintenanceModeMiddleware.cs:line 59
   at Octopus.Server.Web.Middleware.OctopusAuthenticationMiddleware.InvokeAsync(HttpContext context, IUserAuthenticator userAuthenticator, IAuthCookieService authCookieService, IWebAuthCache authCache, ILogger logger) in ./source/Octopus.Server/Web/Middleware/OctopusAuthenticationMiddleware.cs:line 58
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Octopus.Server.Web.Middleware.LegacyRequestLoggerMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/LegacyRequestLoggerMiddleware.cs:line 41
   at Octopus.Server.Web.Middleware.TelemetryMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/TelemetryMiddleware.cs:line 65
   at Octopus.Server.Web.Middleware.ErrorHandlingMiddleware.InvokeAsync(HttpContext context) in ./source/Octopus.Server/Web/Middleware/ErrorHandlingMiddleware.cs:line 49
```

We are also experiencing some other Windows API issues that we believe is somehow connected to this one:

```
System.IO.IOException: The handle is invalid.
   at System.Threading.EventWaitHandle.Set()
   at Octopus.Server.OctopusServerEngine.Start() in ./source/Octopus.Server/OctopusServerEngine.cs:line 100
   at Octopus.Server.Commands.RunCommand.Start() in ./source/Octopus.Server/Commands/RunCommand.cs:line 89
   at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions) in ./source/Octopus.Shared/Startup/AbstractCommand.cs:line 101
   at Octopus.Shared.Startup.OctopusProgram.Start(ICommandRuntime commandRuntime) in ./source/Octopus.Shared/Startup/OctopusProgram.cs:line 504
   at Octopus.Shared.Startup.WindowsServiceHost.<>c__DisplayClass2_0.<Run>b__0() in ./source/Octopus.Shared/Startup/WindowsServiceHost.cs:line 26
   at Octopus.Shared.Startup.WindowsServiceAdapter.RunService() in ./source/Octopus.Shared/Startup/WindowsServiceAdapter.cs:line 48
   at System.Threading.Thread.StartCallback()
```

```
System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.
   at System.Threading.Semaphore.ReleaseCore(Int32 releaseCount)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutNewObject(DbConnectionInternal obj)
   at Microsoft.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutObject(DbConnectionInternal obj, Object owningObject)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.CloseConnection(DbConnection owningObject, DbConnectionFactory connectionFactory)
   at Microsoft.Data.SqlClient.SqlConnection.Close()
   at Microsoft.Data.SqlClient.SqlConnection.Dispose(Boolean disposing)
   at Nevermore.Advanced.ReadTransaction.Dispose()
   at Octopus.Server.Spaces.SpacesCache.GetSpaces() in ./source/Octopus.Server/Spaces/SpacesCache.cs:line 84
   at Octopus.Server.Spaces.SpacesCache.get_AllSpaces() in ./source/Octopus.Server/Spaces/SpacesCache.cs:line 29
   at Octopus.Server.Web.Infrastructure.Spaces.LazyAllSpacePartitions.CreateSpacePartitions() in ./source/Octopus.Server/Web/Infrastructure/Spaces/LazyAllSpacePartitions.cs:line 53
   at Octopus.Server.Web.Infrastructure.Spaces.LazyAllSpacePartitions.CreatePartitions() in ./source/Octopus.Server/Web/Infrastructure/Spaces/LazyAllSpacePartitions.cs:line 33
   at Octopus.Server.Web.Infrastructure.Spaces.LazyAllSpacePartitions.All() in ./source/Octopus.Server/Web/Infrastructure/Spaces/LazyAllSpacePartitions.cs:line 25
   at Octopus.Core.Spaces.AllSpacePartitionsExtensionMethods.AllFor(IAllSpacePartitions allSpacePartitions, Type type) in ./source/Octopus.Core/Spaces/AllSpacePartitionsExtensionMethods.cs:line 10
   at Octopus.Server.Web.Infrastructure.Security.AccessChecker`1.CanViewDocumentType() in ./source/Octopus.Server/Web/Infrastructure/Security/AccessChecker.cs:line 96
   at Octopus.Server.Web.Infrastructure.OctopusQueryExecutor.GetPartitionsWithViewAccess[TDocument,TKey]() in ./source/Octopus.Server/Web/Infrastructure/OctopusQueryExecutor.cs:line 440
   at Octopus.Server.Web.Infrastructure.OctopusQueryExecutor.Queryable[TDocument,TKey]() in ./source/Octopus.Server/Web/Infrastructure/OctopusQueryExecutor.cs:line 185
   at Octopus.Core.Persistence.EntityTracking.EntityTrackingDocumentStoreDecorator`2.Query() in ./source/Octopus.Core/Persistence/EntityTracking/EntityTrackingDocumentStoreDecorator.cs:line 146
   at Octopus.Core.Infrastructure.BusinessProcesses.BusinessProcessAnimator`2.DoWork(CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/BusinessProcesses/BusinessProcessAnimator.cs:line 117
   at Octopus.Core.Infrastructure.BackgroundServices.Metronome`1.<>c__DisplayClass10_0.<<WorkerTask>b__1>d.MoveNext() in ./source/Octopus.Core/Infrastructure/BackgroundServices/Metronome.cs:line 133
--- End of stack trace from previous location ---
   at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.<>c__DisplayClass5_0`2.<<Execute>b__0>d.MoveNext() in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 74
--- End of stack trace from previous location ---
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
```

```
System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.
   at System.Threading.Semaphore.ReleaseCore(Int32 releaseCount)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutNewObject(DbConnectionInternal obj)
   at Microsoft.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutObject(DbConnectionInternal obj, Object owningObject)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.CloseConnection(DbConnection owningObject, DbConnectionFactory connectionFactory)
   at Microsoft.Data.SqlClient.SqlConnection.Close()
   at Microsoft.Data.SqlClient.SqlConnection.Dispose(Boolean disposing)
   at Nevermore.Advanced.ReadTransaction.Dispose()
   at Octopus.Core.Persistence.Database.QueryExecutorProvider.Dispose() in ./source/Octopus.Core/Persistence/Database/QueryExecutorProvider.cs:line 118
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWork.DisposeOurDatabaseTransactionSafely() in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWork.cs:line 204
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWork.CommitToDatabase(CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWork.cs:line 189
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWork.Complete(CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWork.cs:line 120
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
   at Octopus.Core.Infrastructure.UnitsOfWork.UnitOfWorkExtensionMethods.Do(IUnitOfWork unitOfWork, Func`1 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Core/Infrastructure/UnitsOfWork/UnitOfWorkExtensionMethods.cs:line 92
   at Octopus.Server.Infrastructure.Orchestration.UnitsOfWork.UnitOfWorkExecutor.Execute[T1,T2](Func`4 action, CancellationToken cancellationToken, String name) in ./source/Octopus.Server/Infrastructure/Orchestration/UnitsOfWork/UnitOfWorkExecutor.cs:line 77
   at Octopus.Core.Infrastructure.BackgroundServices.Metronome`1.WorkerTask(CancellationToken cancellationToken) in ./source/Octopus.Core/Infrastructure/BackgroundServices/Metronome.cs:line 80
```

```
System.Threading.SemaphoreFullException: Adding the specified count to the semaphore would cause it to exceed its maximum count.
   at System.Threading.Semaphore.ReleaseCore(Int32 releaseCount)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutNewObject(DbConnectionInternal obj)
   at Microsoft.Data.ProviderBase.DbConnectionPool.DeactivateObject(DbConnectionInternal obj)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PutObject(DbConnectionInternal obj, Object owningObject)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.CloseConnection(DbConnection owningObject, DbConnectionFactory connectionFactory)
   at Microsoft.Data.SqlClient.SqlConnection.Close()
   at Microsoft.Data.SqlClient.SqlConnection.Dispose(Boolean disposing)
   at Nevermore.Advanced.ReadTransaction.Dispose()
   at Octopus.Core.Model.Clustering.OctopusClusterService.GetCurrentNode() in ./source/Octopus.Core/Model/Clustering/OctopusClusterService.cs:line 131
   at Octopus.Server.Orchestration.TaskQueue.TaskQueueLimiter.GetTasksThisNodeCanFairlyExecute() in ./source/Octopus.Server/Orchestration/TaskQueue/TaskQueueLimiter.cs:line 192
   at Octopus.Server.Orchestration.TaskQueue.TaskQueue.TryToDoWork(OctopusServerNode thisNode, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/TaskQueue/TaskQueue.cs:line 187
   at Octopus.Server.Orchestration.TaskQueue.TaskQueue.PollForWork(OctopusServerNode thisNode, CancellationToken cancellationToken) in ./source/Octopus.Server/Orchestration/TaskQueue/TaskQueue.cs:line 138
```

**Comment by borland** [comment]
Additional information:

We have captured some process dumps with PageHeap enabled. We found that the dotnet crashdump capabilities (setting `COMPlus_DbgEnableMiniDump`) didn't work as our application is running as a windows service, so we fell back to the Windows Error Reporting dump creation using the registry `HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`

Most dumps simply contain the WER callstack, like this:

```
 	KERNELBASE.dll!RaiseFailFastException()	Unknown
 	userenv.dll!wil::details::WilDynamicLoadRaiseFailFastException(struct _EXCEPTION_RECORD *,struct _CONTEXT *,unsigned long)	Unknown
 	userenv.dll!wil::details::WilRaiseFailFastException(struct _EXCEPTION_RECORD *,struct _CONTEXT *,unsigned long)	Unknown
 	userenv.dll!wil::details::WilFailFast(struct wil::FailureInfo const &)	Unknown
 	userenv.dll!wil::details::ReportFailure(void *,unsigned int,char const *,char const *,char const *,void *,enum wil::FailureType,long,unsigned short const *,enum wil::details::ReportFailureOptions)	Unknown
 	userenv.dll!wil::details::ReportFailure_Hr(void *,unsigned int,char const *,char const *,char const *,void *,enum wil::FailureType,long)	Unknown
 	userenv.dll!wil::details::in1diag3::FailFast_Unexpected(void *,unsigned int,char const *)	Unknown
 	userenv.dll!wil::mutex_t<class wil::details::unique_storage<struct wil::details::resource_policy<void *,void ,&wil::details::CloseHandle(void *),struct wistd::integral_constant<unsigned __int64,0>,void *,0,std::nullptr_t> >,struct wil::err_returncode_policy>::acquire(unsigned long *,unsigned long,int)	Unknown
 	userenv.dll!wil::details_abi::ProcessLocalStorageData<struct wil::details_abi::ProcessLocalData>::Release(void)	Unknown
 	userenv.dll!wil::details_abi::ProcessLocalStorage<struct wil::details_abi::ProcessLocalData>::~ProcessLocalStorage<struct wil::details_abi::ProcessLocalData>(void)	Unknown
 	ucrtbase.dll!<lambda>(void)()	Unknown
 	ucrtbase.dll!__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda>(void) & __ptr64,<lambda_3883c3dff614d5e0c5f61bb1ac94921c>>()	Unknown
 	ucrtbase.dll!_execute_onexit_table()	Unknown
 	ucrtbase.dll!__crt_state_management::wrapped_invoke<int ,int *,int>(int ,int *)	Unknown
 	userenv.dll!dllmain_crt_process_detach()	Unknown
 	userenv.dll!dllmain_dispatch()	Unknown
 	ntdll.dll!LdrpCallInitRoutine()	Unknown
 	ntdll.dll!LdrShutdownProcess()	Unknown
 	ntdll.dll!RtlExitUserProcess()	Unknown
 	kernel32.dll!ExitProcessImplementation()	Unknown
 	ucrtbase.dll!exit_or_terminate_process()	Unknown
 	ucrtbase.dll!common_exit()	Unknown
>	Octopus.Server.exe!__scrt_common_main_seh() Line 295	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

Both Visual Studio and WinDBG indicate that this is the only running native thread, however `!clrthreads` in WinDBG says there are approx 100 threads, so something isn't quite right here, perhaps related to WER capturing the dump rather than dotnet?
I believe these are correlated with the AppDomain UnhandledExceptions.

We did capture one dump which caught the SEHException itself. This has a native callstack indicating the exception source is `TppSetupNextWait`

```
// stuff higher than this elided, just normal CLR exception handling
2e 2e 0000001f`c9f7ce60 00007ffd`070d511f     coreclr!ProcessCLRException+0x3390000001f`c9f7ce60 00007ffd`070d511f     coreclr!ProcessCLRException+0x339 [D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp @ 1135]  [D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp @ 1135] 
2f 2f 0000001f`c9f7d090 00007ffd`0703610c     ntdll!RtlpExecuteHandlerForUnwind+0xf
30 30 0000001f`c9f7d0c0 00007ffd`0703370a     ntdll!RtlUnwindEx+0x51c
31 31 0000001f`c9f7d7d0 00007ffc`e96abb6f     ntdll!RtlUnwind+0xca
32 32 0000001f`c9f7dd40 00007ffc`e965a0d9     coreclr!ClrUnwindEx+0x1b0000001f`c9f7dd40 00007ffc`e965a0d9     coreclr!ClrUnwindEx+0x1b [D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp @ 5341]  [D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp @ 5341] 
33 33 0000001f`c9f7dd70 00007ffd`070d509f     coreclr!ProcessCLRException+0x3a90000001f`c9f7dd70 00007ffd`070d509f     coreclr!ProcessCLRException+0x3a9 [D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp @ 1090]  [D:\a\_work\1\s\src\coreclr\vm\exceptionhandling.cpp @ 1090] 
34 34 0000001f`c9f7dfa0 00007ffd`07034cef     ntdll!RtlpExecuteHandlerForException+0xf
35 35 0000001f`c9f7dfd0 00007ffd`07038ae6     ntdll!RtlDispatchException+0x40f
36 36 0000001f`c9f7e700 00007ffd`07140c19     ntdll!RtlRaiseException+0x316
37 37 0000001f`c9f7ef00 00007ffd`070e40e7     ntdll!TppRaiseHandleStatus+0x91
38 38 0000001f`c9f7efe0 00007ffd`0705c156     ntdll!TppSetupNextWait+0x87dc7
39 39 0000001f`c9f7f030 00007ffd`0705bc16     ntdll!TpSetWaitEx+0xa6
3a 3a 0000001f`c9f7f070 00007ffd`03cceb17     ntdll!RtlRegisterWait+0x1d6
3b 3b 0000001f`c9f7f130 00007ffd`04099c5c     KERNELBASE!RegisterWaitForSingleObjectEx+0x47
3c 3c 0000001f`c9f7f170 00007ffd`04099ba9     crypt32!I_RegisterWaitForSingleObjectEx+0x80
3d 3d 0000001f`c9f7f1b0 00007ffd`0408442c     crypt32!InitRegistryStoreChange+0xb5
3e 3e 0000001f`c9f7f1f0 00007ffd`0408428b     crypt32!ResyncFromRegistry+0x68
3f 3f 0000001f`c9f7f270 00007ffd`040a2540     crypt32!RegStoreProvControl+0x8b
40 40 0000001f`c9f7f2c0 00007ffd`040a25b2     crypt32!CertControlStore+0x60
41 41 0000001f`c9f7f330 00007ffd`040a23b6     crypt32!CertControlStore+0xd2
42 42 0000001f`c9f7f3a0 00007ffd`040a2624     crypt32!EnableAutoResync+0x7a
43 43 0000001f`c9f7f3d0 00007ffc`8f9d5990     crypt32!CertControlStore+0x144
44 44 0000001f`c9f7f440 00000000`00000004     0x00007ffc`8f9d5990
45 45 0000001f`c9f7f448 00000000`00000000     0x4
```

We also traced the error causing the SemaphoreFullException in SqlClient, and this is also caused by an Invalid Handle value.

All three different errors seem to trace back to the same root cause of Handle corruption in the threadpool RegisterWait methods.

This old blog post from Raymond Chen seems relevant:
https://devblogs.microsoft.com/oldnewthing/20160115-00/?p=92861

It suggests that the source of the error could be closing a handle while the threadpool has an outstanding wait on this.

We are currently searching our code for places where this could be happening, but have been unable to find any such instances.

Is it possible for anyone to provide more information here? Is the Raymond Chen article relevant?

Kind regards

Orion
