### ISSUE TITLE
jitstress-random ComWrappersTestsBuiltInComDisabled is failing

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#85262]
Failing on [jitstress-random](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249289&view=ms.vss-test-web.build-test-results-tab&runId=4820970&resultId=111632&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab)

```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=30d
```

```
      BEGIN EXECUTION
       "C:\h\w\B9AB0A63\p\corerun.exe" -p "System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ComWrappersTestsBuiltInComDisabled.dll 
      Running ValidateComInterfaceCreation...
      Running ValidateComInterfaceCreationRoundTrip...
      Running ValidateComObjectExtendsManagedLifetime...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 0
      Actual:   1
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ComWrappersTests.Program.ValidateComObjectExtendsManagedLifetime()
         at ComWrappersTests.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test failed. Trying to see if dump file was created in C:\cores since 4/23/2023 7:51:40 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\B9AB0A63\p
      > C:\h\w\B9AB0A63\w\B3B80A0B\e\Interop\COM\ComWrappers\API\ComWrappersTestsBuiltInComDisabled\ComWrappersTestsBuiltInComDisabled.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_COM._ComWrappers_API_ComWrappersTestsBuiltInComDisabled_ComWrappersTestsBuiltInComDisabled_._ComWrappers_API_ComWrappersTestsBuiltInComDisabled_ComWrappersTestsBuiltInComDisabled_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jkoritzinsky** [comment]
This might be related to #85235

**Comment by AaronRobinsonMSFT** [comment]
This repos on x64 too.

> This might be related to #85235

I don't see how. That test isn't run yet, but it isn't written the best way. I will fix that while I am investigating.

**Comment by jkoritzinsky** [comment]
I was thinking that the failure was due to #85087 (as that test added the failing test case), but that #85235 would fix the failure with its fix.
