### ISSUE TITLE
error BLAZORSDK1001 in wasm tests

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#85354]
`error BLAZORSDK1001: Unable to find 'RazorClassLibrary.dll' to be lazy loaded later. Confirm that project or package references are included and the reference is used in the project.`

This error was encountered in a number of the wasm test legs in https://dev.azure.com/dnceng-public/public/_build/results?buildId=250766&view=logs&jobId=4de1b480-db2d-5e2d-1b07-cb01593ab740.

```
Expected 0 exit code but got 1: /root/helix/work/workitem/e/dotnet-latest/dotnet build -bl:/root/helix/work/workitem/uploads/xharness-output/logs/blz_razor_lib_top_youwyvwp.vdm/blz_razor_lib_top_youwyvwp.vdm-build.binlog -p:Configuration=Release -p:WasmEnableWebcil=true -p:BlazorEnableCompression=false -nr:false  /warnaserror
Standard Output:
[] MSBuild version 17.7.0-preview-23221-02+ac3f5ad89 for .NET
[]   Determining projects to restore...
[]   Restored /root/helix/work/workitem/e/wbt/blz_razor_lib_top_youwyvwp.vdm/wasm/wasm.csproj (in 341 ms).
[]   1 of 2 projects are up-to-date for restore.
[] /root/helix/work/workitem/e/dotnet-latest/sdk/8.0.100-preview.4.23224.16/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/helix/work/workitem/e/wbt/blz_razor_lib_top_youwyvwp.vdm/wasm/wasm.csproj]
[]   RazorClassLibrary -> /root/helix/work/workitem/e/wbt/blz_razor_lib_top_youwyvwp.vdm/RazorClassLibrary/bin/Release/net8.0/RazorClassLibrary.dll
[] /root/helix/work/workitem/e/wbt/nuget/blz_razor_lib_top_youwyvwp.vdm/microsoft.net.sdk.webassembly.pack/8.0.0-preview.4.23224.2/build/Microsoft.NET.Sdk.WebAssembly.Browser.targets(314,5): error BLAZORSDK1001: Unable to find 'RazorClassLibrary.dll' to be lazy loaded later. Confirm that project or package references are included and the reference is used in the project. [/root/helix/work/workitem/e/wbt/blz_razor_lib_top_youwyvwp.vdm/wasm/wasm.csproj]
[]
[] Build FAILED.
[]
[] /root/helix/work/workitem/e/wbt/nuget/blz_razor_lib_top_youwyvwp.vdm/microsoft.net.sdk.webassembly.pack/8.0.0-preview.4.23224.2/build/Microsoft.NET.Sdk.WebAssembly.Browser.targets(314,5): error BLAZORSDK1001: Unable to find 'RazorClassLibrary.dll' to be lazy loaded later. Confirm that project or package references are included and the reference is used in the project. [/root/helix/work/workitem/e/wbt/blz_razor_lib_top_youwyvwp.vdm/wasm/wasm.csproj]
[]     0 Warning(s)
[]     1 Error(s)
[]
[] Time Elapsed 00:00:15.07
[]
[] Workload updates are available. Run dotnet workload list for more information.
   at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput) in /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs:line 44
   at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput) in /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs:line 28
   at Wasm.Build.Tests.BuildTestBase.BlazorBuildInternal(String id, String config, Boolean publish, Boolean setWasmDevel, String[] extraArgs) in /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs:line 601
   at Wasm.Build.Tests.BuildTestBase.BlazorBuild(BlazorBuildOptions options, String[] extraArgs) in /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs:line 543
   at Wasm.Build.Tests.Blazor.BuildPublishTests.BugRegression_60479_WithRazorClassLib() in /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BuildPublishTests.cs:line 208
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unable to find 'RazorClassLibrary.dll' to be lazy loaded later.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

**Comment by radical** [comment]
@maraf this seems like a regression. Do we know what is causing this?

**Comment by radical** [comment]
Opened https://github.com/dotnet/runtime/pull/85685 to re-enable the test.
