### ISSUE TITLE
iOS-net7 simple_nursery_serial_scan_object invalid GC type desc

### ISSUE THREAD

**Issue by marekdovjak** [dotnet/runtime#85379]
### Description

Our iOS-net7 app started to report following crash reports to appcenter. We have many such crashes, they differ under the line `sgen_ensure_free_space`. We are unable to reproduce them, but we have report that application did crash immediately after resuming from background. 
It also seems that this crash started to happen after upgrading our project from Xamarin.iOS to the iOS-net7 framework.
We checked the app's memory usage and memory leaks, but found no issues. Any idea what this could be related to?

```Thread 19 Crashed:
0   libsystem_kernel.dylib               0x00000001dfdcf674 __pthread_kill + 8
1   libsystem_c.dylib                    0x00000001a9930c8c abort + 176
2   TapHome Next                         0x0000000106491124 log_callback(char const*, char const*, char const*, int, void*) (runtime.m:1168)
3   TapHome Next                         0x00000001067991f0 monoeg_g_logv_nofree (goutput.c:151)
4   TapHome Next                         0x00000001067992a8 monoeg_assertion_message (goutput.c:207)
5   TapHome Next                         0x0000000106799308 mono_assertion_message_unreachable (goutput.c:234)
6   TapHome Next                         0x000000010670f4d8 simple_nursery_serial_scan_object (sgen-scan-object.h:93)
7   TapHome Next                         0x000000010670fcb0 simple_nursery_serial_drain_gray_stack (sgen-minor-scan-object.h:142)
8   TapHome Next                         0x00000001066ea554 finish_gray_stack (sgen-gc.c:578)
9   TapHome Next                         0x00000001066e96f4 collect_nursery (sgen-gc.c:1932)
10  TapHome Next                         0x00000001066e5d5c sgen_perform_collection (sgen-gc.c:2656)
11  TapHome Next                         0x00000001066e5b1c sgen_ensure_free_space (sgen-gc.c:2622)
12  TapHome Next                         0x00000001066da8e0 sgen_alloc_obj_nolock (sgen-alloc.c:279)
13  TapHome Next                         0x00000001066dad58 sgen_alloc_obj (sgen-alloc.c:454)
14  TapHome Next                         0x00000001066b0a88 mono_gc_alloc_obj (sgen-mono.c:911)
15  TapHome Next                         0x0000000102e891b0 wrapper_managed_to_native_object___icall_wrapper_mono_gc_alloc_obj_intptr_intptr + 124
16  TapHome Next                         0x0000000106263f2c corlib_wrapper_alloc_object_AllocSmall_intptr_intptr + 140
17  TapHome Next                         0x00000001024bbd64 TapHome_SQLite_SQLiteCommand__ExecuteDeferredQueryd__12_1_T_REF_MoveNext (SQLite.cs:3771)
18  TapHome Next                         0x0000000106161e64 corlib_System_Collections_Generic_List_1_T_REF__ctor_System_Collections_Generic_IEnumerable_1_T_REF + 424
19  TapHome Next                         0x00000001052e5624 System_Linq_System_Linq_Enumerable_ToList_TSource_REF_System_Collections_Generic_IEnumerable_1_TSource_REF + 164
20  TapHome Next                         0x000000010301a1a0 TapHome_Next_TapHome_Client_Storage_Db_CommonDb_GetGenericKeyValueStringValueAsInt_System_Guid_System_Guid_string_int (CommonDb.GenericKeyValue.cs:60)
21  TapHome Next                         0x000000010353e92c TapHome_Next_Com_TapHome_Communication_ClientCommunicationManager_ProcessMessage_TapHome_Core_Lib_Communication_Messages_MessageBase_Com_TapHome_Communication_CommunicationSocketState (ClientCommunicationManager.cs:1176)
22  TapHome Next                         0x00000001024b655c Com_TapHome_Communication_ClientCommunicationManager_ProcessSerializedMessage_byte___Com_TapHome_Communication_CommunicationSocketState (ClientCommunicationManager.cs:997)
23  TapHome Next                         0x000000010354364c TapHome_Next_Com_TapHome_Communication_ClientCommunicationManager_Com_TapHome_Communication_IClientCommunicationReceiver_MessageReceived_Com_TapHome_Communication_CommunicationSocketState_byte__ (ClientCommunicationManager.cs:1505)
24  TapHome Next                         0x00000001060ae8a0 corlib_System_Threading_Tasks_AwaitTaskContinuation_Run_System_Threading_Tasks_Task_bool + 160
25  TapHome Next                         0x00000001060a5754 corlib_System_Threading_Tasks_Task_FinishContinuations + 120
26  TapHome Next                         0x0000000102e19d54 System_Threading_Tasks_ValueTask_1_ValueTaskSourceAsTask__c_TResult_GSHAREDVT___cctorb__4_0_object + 448
27  TapHome Next                         0x0000000106244510 corlib_System_Threading_Tasks_Sources_ManualResetValueTaskSourceCore_1_TResult_INT_SignalCompletion + 328
28  TapHome Next                         0x00000001054cf2b4 System_Net_Security_System_Runtime_CompilerServices_PoolingAsyncValueTaskMethodBuilder_1_StateMachineBox_1_int_System_Net_Security_SslStream__ReadAsyncInternald__159_1_System_Net_Security_AsyncReadWriteAdapter_ExecutionContextCallback_object + 60
29  TapHome Next                         0x0000000106074830 corlib_System_Threading_Thread_StartCallback + 252
30  TapHome Next                         0x00000001067270bc mono_jit_runtime_invoke (mini-runtime.c:3524)
31  TapHome Next                         0x0000000106665bdc mono_runtime_invoke_checked (object.c:2415)
32  TapHome Next                         0x000000010667f730 start_wrapper_internal (threads.c:1213)
33  TapHome Next                         0x000000010667f4c0 start_wrapper (threads.c:1264)
34  libsystem_pthread.dylib              0x00000001f052d6cc _pthread_start + 144
35  libsystem_pthread.dylib              0x00000001f052cba4 thread_start + 4
```

### Reproduction Steps

We are unable to reporduce the crash, but it happens to our users

### Expected behavior

Application does not crash

### Actual behavior

App crashes randomly

### Regression?

This probably started to happen after upgrading our app project from the Xamarin.iOS to the iOS-net7 

### Known Workarounds

No

### Configuration

```Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
ios                        16.2.2054/7.0.100      SDK 7.0.200        
maccatalyst                16.2.2054/7.0.100      SDK 7.0.200
```

**Comment by michaldobrodenka** [comment]
Maybe similar to this https://github.com/dotnet/runtime/issues/79910

Try turning off llvm, if it helps (as a workaround)

**Comment by marekdovjak** [comment]
After turning off the "Use the LLVM optimizing compiler", such crashes are no longer reported.
What's interesting, the following crash also disappeared

```Xamarin Exception Stack:
System.InvalidCastException: Arg_InvalidCastException
  at System.Threading.Tasks.Task.DelayPromise.TimerCallback(Object )
  at System.Threading.TimerQueueTimer.CallCallback(Boolean )
  at System.Threading.TimerQueueTimer.Fire(Boolean )
  at System.Threading.TimerQueue.FireNextTimers()
  at System.Threading.TimerQueue.System.Threading.IThreadPoolWorkItem.Execute()
  at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(Object , Thread )
  at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
  at System.Threading.Thread.StartCallback()

**Comment by BrzVlad** [comment]
Unfortunately, this is not really actionable without a repro sample.
