### ISSUE TITLE
Test failure JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85440]
Run: [runtime-coreclr jitstress 20230425.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=252731&view=ms.vss-test-web.build-test-results-tab&runId=4906788&resultId=116816&paneView=debug)

Failed test:
```
coreclr osx x64 Checked jitstress2_tiered @ OSX.1200.Amd64.Open

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr osx x64 Checked jitstress1_tiered @ OSX.1200.Amd64.Open

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open

- JIT\\Performance\\CodeQuality\\SIMD\\RayTracer\\RayTracer\\RayTracer.cmd

coreclr windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open

- JIT\\Performance\\CodeQuality\\SIMD\\RayTracer\\RayTracer\\RayTracer.cmd

coreclr linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr windows arm64 Checked jitstress1_tiered @ Windows.11.Arm64.Open

- JIT\\Performance\\CodeQuality\\SIMD\\RayTracer\\RayTracer\\RayTracer.cmd

coreclr linux arm64 Checked jitstress1_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr linux arm64 Checked jitstress2_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr windows arm64 Checked jitstress2_tiered @ Windows.11.Arm64.Open

- JIT\\Performance\\CodeQuality\\SIMD\\RayTracer\\RayTracer\\RayTracer.cmd

coreclr linux x64 Checked jitstress2_tiered @ Ubuntu.1804.Amd64.Open

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr osx arm64 Checked jitstress1_tiered @ OSX.1200.ARM64.Open

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh

coreclr osx arm64 Checked jitstress2_tiered @ OSX.1200.ARM64.Open

- JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh
```
**Error message:**
```
Assert failure(PID 62354 [0x0000f392], Thread: 7117586 [0x6c9b12]): Assertion failed 'lclNum < lvaCount' in 'RayTracer:RenderSequential(Scene,int[]):this' during 'Physical promotion' (IL size 95; hash 0xfa1a8d9f; Tier1-OSR)

File: /Users/runner/work/1/s/src/coreclr/jit/compiler.h Line: 3423
Image: /private/tmp/helix/working/A4840974/p/corerun
[createdump] Invalid process id: task_for_pid(62354) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 3ms
[createdump] waitpid() returned successfully (wstatus 0000ff00)
/private/tmp/helix/working/A4840974/w/AAAD090B/e/JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh: line 448: 62354 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A4840974/w/AAAD090B/uploads/Reports/JIT.Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A4840974/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true RayTracer.dll ''
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 4/26/2023 12:42:34 AM
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/A4840974/p
> /private/tmp/helix/working/A4840974/w/AAAD090B/e/JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Performance._CodeQuality_SIMD_RayTracer_RayTracer_RayTracer_._CodeQuality_SIMD_RayTracer_RayTracer_RayTracer_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T06:10:22.769Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | osx.1200.amd64.open | x64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"operatingSystem":"OSX.1200.Amd64.Open","System.PhaseAttempt":"1","System.JobAttempt":"1","System.StageName":"Build","architecture":"x64","BuildId":"252731","AzurePipelinesTestRunId":"4906788","System.JobName":"__default","BuildNumber":"20230425.5","Project":"public","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Reason":"Schedule","DefinitionId":"109","configuration":"Checked-jitstress2_tiered","DefinitionName":"runtime-coreclr jitstress","System.PhaseName":"run_test_p1__osx_x64_checked"} | Schedule
2023-04-26T06:10:21.396Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"BuildNumber":"20230425.5","operatingSystem":"OSX.1200.Amd64.Open","Reason":"Schedule","System.StageName":"Build","System.JobName":"__default","architecture":"x64","BuildId":"252731","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Project":"public","System.PhaseAttempt":"1","System.StageAttempt":"1","DefinitionId":"109","configuration":"Checked-jitstress1_tiered","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"4906794","System.PhaseName":"run_test_p1__osx_x64_checked","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-04-26T06:10:08.609Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.arm64.open | arm64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"System.JobAttempt":"1","System.JobName":"__default","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"4906776","DefinitionId":"109","operatingSystem":"OSX.1200.ARM64.Open","DefinitionName":"runtime-coreclr jitstress","System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","Reason":"Schedule","BuildNumber":"20230425.5","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","architecture":"arm64","System.StageName":"Build","BuildId":"252731","configuration":"Checked-jitstress1_tiered","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-26T06:10:07.624Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | osx.1200.arm64.open | arm64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","Reason":"Schedule","architecture":"arm64","DefinitionName":"runtime-coreclr jitstress","System.StageName":"Build","System.JobName":"__default","operatingSystem":"OSX.1200.ARM64.Open","configuration":"Checked-jitstress2_tiered","System.StageAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Project":"public","BuildId":"252731","System.PhaseName":"run_test_p1__osx_arm64_checked","DefinitionId":"109","AzurePipelinesTestRunId":"4906778","BuildNumber":"20230425.5","System.PhaseAttempt":"1","System.JobAttempt":"1"} | Schedule
2023-04-26T05:27:26.183Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | ubuntu.1804.armarch.open | arm64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"configuration":"Checked-jitstress1_tiered","System.JobAttempt":"1","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","DefinitionName":"runtime-coreclr jitstress","System.JobName":"__default","System.StageAttempt":"1","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__linux_arm64_checked","System.StageName":"Build","System.PhaseAttempt":"1","BuildId":"252731","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","BuildNumber":"20230425.5","AzurePipelinesTestRunId":"4906420","Reason":"Schedule","DefinitionId":"109","architecture":"arm64"} | Schedule
2023-04-26T05:27:24.032Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | ubuntu.1804.armarch.open | arm64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"System.PhaseAttempt":"1","Project":"public","DefinitionId":"109","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr jitstress","System.StageAttempt":"1","AzurePipelinesTestRunId":"4906422","System.JobAttempt":"1","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","BuildNumber":"20230425.5","System.StageName":"Build","configuration":"Checked-jitstress2_tiered","System.JobName":"__default","architecture":"arm64","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","BuildId":"252731","System.PhaseName":"run_test_p1__linux_arm64_checked"} | Schedule
2023-04-26T05:25:13.814Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | ubuntu.1804.amd64.open.rt | x64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"DefinitionName":"runtime-coreclr jitstress","System.JobName":"__default","BuildNumber":"20230425.5","Reason":"Schedule","DefinitionId":"109","System.StageAttempt":"1","System.StageName":"Build","System.PhaseAttempt":"1","Project":"public","System.PhaseName":"run_test_p1__linux_x64_checked","architecture":"x64","System.JobAttempt":"1","configuration":"Checked-jitstress1_tiered","operatingSystem":"Ubuntu.1804.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildId":"252731","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","AzurePipelinesTestRunId":"4906404"} | Schedule
2023-04-26T05:25:09.281Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | ubuntu.1804.amd64.open.rt | x64 | JIT/Performance/CodeQuality/SIMD/RayTracer/RayTracer/RayTracer.sh | Failed | {"architecture":"x64","DefinitionName":"runtime-coreclr jitstress","System.JobAttempt":"1","operatingSystem":"Ubuntu.1804.Amd64.Open","Reason":"Schedule","Project":"public","System.PhaseAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","BuildNumber":"20230425.5","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","System.JobName":"__default","BuildId":"252731","configuration":"Checked-jitstress2_tiered","AzurePipelinesTestRunId":"4906402","DefinitionId":"109","System.PhaseName":"run_test_p1__linux_x64_checked"} | Schedule

**Comment by jakobbotsch** [comment]
Fixed by #85343
