### ISSUE TITLE
[wasi] Tests fail to create a temp file in `System.Runtime.Serialization.Xml.ReflectionOnly.Tests`, and `System.Runtime.Serialization.Xml.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#85690]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85681-merge-1a634b5df2d94cb68e/System.Runtime.Serialization.Xml.ReflectionOnly.Tests/1/console.af5f9bef.log?helixlogtype=result).
`System.Runtime.Serialization.Xml.ReflectionOnly.Tests`, and `System.Runtime.Serialization.Xml.Tests`:

```
[22:09:22] fail: [FAIL] DataContractSerializerTests.DCS_FileStreamSurrogate
[22:09:22] info: System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/q5vucmkj.caj_DCS_FileStreamSurrogate_4046'.
[22:09:22] info:    at Interop.ThrowExceptionForIoErrno(ErrorInfo , String , Boolean )
[22:09:22] info:    at Interop.CheckIo(Error , String , Boolean )
[22:09:22] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , OpenFlags , Int32 , Func`4 )
[22:09:22] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , UnixFileMode , Int64& , UnixFileMode& , Func`4 )
[22:09:22] info:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 , Func`4 )
[22:09:22] info:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 )
[22:09:22] info:    at System.IO.Strategies.UnixFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 )
[22:09:22] info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String , FileMode , FileAccess , FileShare , FileOptions , Int64 , Nullable`1 )
[22:09:22] info:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream , String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 , Nullable`1 )
[22:09:22] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions , Int64 )
[22:09:22] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , FileOptions )
[22:09:22] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare , Int32 , Boolean )
[22:09:22] info:    at System.IO.FileStream..ctor(String , FileMode , FileAccess , FileShare )
[22:09:22] info:    at MyFileStream..ctor(String fileName)
[22:09:22] info:    at DataContractSerializerTests.DCS_FileStreamSurrogate()
[22:09:22] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
[22:09:22] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

Fails consistently.

**Comment by radical** [comment]
`mkstemp`, and `mkdtemp` not supported

**Comment by ilonatommy** [comment]
Still failing, tracking issue for the missing support: https://github.com/WebAssembly/wasi-libc/issues/229
