### ISSUE TITLE
Regression: Internal error in ILCompiler

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#85760]
I started receiving this compilation error:
```
  System.AggregateException: One or more errors occurred. (Code generation failed for method '[Microsoft.macOS]SceneKit.SCNMatrix4.CreateFromAxisAngle(Vector3,float32,SCNMatrix4&)')
   ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[Microsoft.macOS]SceneKit.SCNMatrix4.CreateFromAxisAngle(Vector3,float32,SCNMatrix4&)'
   ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
     at Internal.JitInterface.CorInfoImpl.HandleToObject(Void*) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 731
     at Internal.JitInterface.CorInfoImpl.recordRelocation(Void*, Void*, Void*, UInt16, UInt16, Int32) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 3807
     at Internal.JitInterface.CorInfoImpl._recordRelocation(IntPtr, IntPtr*, Void*, Void*, Void*, UInt16, UInt16, Int32) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 2692
     --- End of inner exception stack trace ---
     at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode, MethodIL) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 383
     at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodCodeNode, MethodIL ) in /_/src/coreclr/tools/aot/ILCompiler.RyuJit/JitInterface/CorInfoImpl.RyuJit.cs:line 62
     at ILCompiler.RyuJitCompilation.CompileSingleMethod(CorInfoImpl, MethodCodeNode) in /_/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 190
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker&, Int32, Boolean& )
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker&, Int32, Boolean& )
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1, ParallelOptions, Boolean)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32, Int32, ParallelOptions, Action`1, Action`2, Func`4, Func`1, Action`1)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection, CancellationToken, Exception)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32, Int32, ParallelOptions, Action`1, Action`2, Func`4, Func`1, Action`1)
     at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1, ParallelOptions, Action`1, Action`2, Action`3, Func`4, Func`5, Func`1, Action`1)
     at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1, ParallelOptions, Action`1)
     at ILCompiler.RyuJitCompilation.CompileMultiThreaded(List`1) in /_/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 150
     at ILCompiler.RyuJitCompilation.ComputeDependencyNodeDependencies(List`1) in /_/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 140
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 316
     at ILCompiler.RyuJitCompilation.CompileInternal(String, ObjectDumper) in /_/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 88
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String, ObjectDumper) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 523
     at ILCompiler.Program.Run() in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 532
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass206_0.<.ctor>b__0(InvocationContext) in /_/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 275
```

Unfortunately I don't have a self-contained repro since it involves multiple xamarin-macios branches cobbled together with a small test program. The error started happening between dotnet-sdk-8.0.100-preview.5.23226.2 and dotnet-sdk-8.0.100-preview.5.23253.1 and it was most likely triggered by a change between these SDKs.

**Comment by filipnavara** [comment]
Bin log in case it helps: [msbuild.binlog.zip](https://github.com/dotnet/runtime/files/11396113/msbuild.binlog.zip)

**Comment by filipnavara** [comment]
Generated repro with `--make-repro-path` (+ manually fixing the `--root` parameter): [repro.zip](https://github.com/dotnet/runtime/files/11396306/repro.zip)

**Comment by JulieLeeMSFT** [comment]
Cc @TIHan

**Comment by MichalStrehovsky** [comment]
Doesn't repro with latest main. I had to adjust the rsp file in the repro package because `--appcontextswitch` parameter was deleted, but it compiles fine after deleting those lines.
