### ISSUE TITLE
Test failure GC\\API\\Frozen\\Frozen\\Frozen.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85863]
Run: [runtime-coreclr jitstress-isas-avx512 20230408.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232506&view=ms.vss-test-web.build-test-results-tab&runId=4417162&resultId=117160&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstressregs0x2000 @ Windows.10.Amd64.Open

- GC\\API\\Frozen\\Frozen\\Frozen.cmd

coreclr windows x86 Checked jitstress_isas_x86_evex @ Windows.10.Amd64.Open

- GC\\API\\Frozen\\Frozen\\Frozen.cmd
```
**Error message:**
```
Assert failure(PID 3000 [0x00000bb8], Thread: 1760 [0x06e0]): Consistency check failed: AV in clr at this callstack:

CORECLR! WKS::gc_heap::clear_mark_array + 0x9E (0x70fbcce9)
CORECLR! WKS::gc_heap::remove_ro_segment + 0x43 (0x70fcfa5b)
CORECLR! GCInterface_UnregisterFrozenSegment + 0x100 (0x70d2ebb0)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fcb506d)
CORECLR! CallDescrWorkerInternal + 0x34 (0x70fd7bf1)
CORECLR! CallDescrWorker + 0xAA (0x70d05bdc)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70d05d1a)
CORECLR! RuntimeMethodHandle::InvokeMethod + 0x6E0 (0x70e6c9b0)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fe282e6)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fe34dfd)
<no module>! <no symbol> + 0x0 (0x04652d39)
<no module>! <no symbol> + 0x0 (0x04651c49)
CORECLR! CallDescrWorkerInternal + 0x34 (0x70fd7bf1)
CORECLR! CallDescrWorker + 0xAA (0x70d05bdc)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70d05d1a)
CORECLR! MethodDescCallSite::CallTargetWorker + 0x648 (0x70d06394)
CORECLR! RunMainInternal + 0x1AB (0x70afff9d)
CORECLR! ``RunMain'::29&#39;::__Body::Run&#39;::5'::__Body::Run + 0x40 (0x70affb8c)
CORECLR! RunMain&#39;::29'::__Body::Run + 0x6C (0x70affc49)

.AV on tid=0x6e0 (1760), cxr=0077D0C8, exr=0077D078
FAILED: false


CORECLR! CHECK::Trigger + 0x256 (0x70fecf10)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x70ba4149)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x70ba3e3e)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x70ba3de4)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x70ba435a)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1C21A (0x77d4f95a)
NTDLL! RtlUnwind + 0x1BA (0x77d1011a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x77d20dbf)
CORECLR! WKS::gc_heap::remove_ro_segment + 0x43 (0x70fcfa5b)
CORECLR! GCInterface_UnregisterFrozenSegment + 0x100 (0x70d2ebb0)
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 7116
Image: C:\h\w\B70C09C8\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B70C09C8\w\B29C0943\uploads\Reports\GC.API\Frozen\Frozen\Frozen.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B70C09C8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Frozen.dll
False
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 4/8/2023 9:08:14 PM
Processing C:\cores\corerun.exe.3000.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B70C09C8\t\tmpgabxrl.tmp" -z "C:\cores\corerun.exe.3000.dmp"
stdout:
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.3000.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B70C09C8\p\PDB
Symbol search path is: C:\h\w\B70C09C8\p\PDB
Executable search path is:
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sat Apr  8 21:08:37.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:09:47.477
Process Uptime: 0 days 0:00:23.000
.................................


************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified


You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in



Stack trace
   at GC_API._Frozen_Frozen_Frozen_._Frozen_Frozen_Frozen_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by EgorBo** [comment]
@cshung can you take a look please?

**Comment by mangod9** [comment]
closing since this was a one time failure and no dumps exist currently. Please reopen if it occurs again.
