### ISSUE TITLE
Dotnet failed to run after publishing on debian with the error below

### ISSUE THREAD

**Issue by 1988gadocansey** [dotnet/runtime#85878]
Debian 10
Dotnet 7

System.UnauthorizedAccessException: Access to the path '/root/.dotnet' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.DirectoryWrapper.CreateDirectory(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by adamsitnik** [comment]
Hi @1988gadocansey 

Thank you for sharing the log output!

These two lines look interesting to me:

> `Access to the path '/root/.dotnet' is denied.`
> ConfigureDotNetForFirstTimeUse

It seems that the SDK is trying to create a folder in `'/root/.dotnet'` to configure something when it's used for the same time.

I am going to move it to the SDK folder, in the meantime you can run `dotnet publish` as root once and it should workaround the problem.
