### ISSUE TITLE
Polymorphic deserialization of a composite collection throws NullReferenceException

### ISSUE THREAD

**Issue by Nectivio** [dotnet/runtime#85934]
### Description

If a `JsonDerivedType` of a `JsonPolymorphic` base class implements `ICollection<T>` where T is the base class it will serialize as a JSON object with a `$type`property for the type discriminator and a `$values` property with an array of the items in the collection. This is all good.

When deserializing however, a `NullReferenceException` it thrown.

### Reproduction Steps

```
using System.Collections;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PolymorphicCollectionSerialization;

[JsonPolymorphic]
[JsonDerivedType(typeof(Composite), nameof(Composite))]
public abstract class Base
{
}

public class Composite : Base, ICollection<Base>
{
    private readonly ICollection<Base> _items = new List<Base>();
 
    // Implementation ICollection<Base> as delegation to _items
    public IEnumerator<Base> GetEnumerator() => _items.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() => ((IEnumerable) _items).GetEnumerator();
    public void Add(Base item) => _items.Add(item);
    public void Clear() => _items.Clear();
    public bool Contains(Base item) => _items.Contains(item);
    public void CopyTo(Base[] array, int arrayIndex) => _items.CopyTo(array, arrayIndex);
    public bool Remove(Base item) => _items.Remove(item);
    public int Count => _items.Count;
    public bool IsReadOnly => _items.IsReadOnly;
}

public class Program
{
    public static void Main(string[] args)
    {
        Base test = new Composite {new Composite(), new Composite()};

        var json = JsonSerializer.Serialize(test);

        Console.WriteLine(json); // {"$type":"Composite","$values":[{"$type":"Composite","$values":[]},{"$type":"Composite","$values":[]}]}

        var deserialized = JsonSerializer.Deserialize<Base>(json) as Composite; // throws System.NullReferenceException 

        Console.WriteLine($"{deserialized?.Count}"); // Expected: 2
    }
}

```

### Expected behavior

Serialization of the class works correctly, I would expect it to deserialize back to an equivalent object.

### Actual behavior

The following exception is thrown

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.JsonSerializer.LookupProperty(Object obj, ReadOnlySpan`1 unescapedPropertyName, ReadStack& state, JsonSerializerOptions options, Boolean& useExtensionProperty, Boolean createExtensionProperty)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.OnTryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at PolymorphicCollectionSerialization.Program.Main(String[] args) in /Users/dangraham/Library/Mobile Documents/com~apple~CloudDocs/Source/PolymorphicCollectionSerialization/PolymorphicCollectionSerialization/Class1.cs:line 43
```

### Regression?

I don't think so, I believe this kind of Polymorphic Deserialization in System.Text.Json is new in .NET 7

### Known Workarounds

1. Remove the ICollection implementation, replace with a property:

```
public class Composite : Base
{
    public ICollection<Base> Items { get; } = new List<Base>();
}
```

2. Implement a custom JsonConverter

### Configuration

dotnet 7.0.100
macOS 13.3.1 (a)
intel x64

**Comment by eiriktsarpalis** [comment]
Appears to be a bug in how the `ReadStack` resolves the `JsonTypeInfo` for the nested polymorphic element. Instead of using `Base` it somehow defaults to `Composite` so it won't attempt to read any polymorphic metadata resulting in the exception. Issue reproduces in both .NET 7 and .NET 8.
