### ISSUE TITLE
EntryPointNotFoundException throwns in action

### ISSUE THREAD

**Issue by CheloXL** [dotnet/runtime#85990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following exception is being thrown in an asp.mvc action
```
System.EntryPointNotFoundException: Entry point was not found.
   at System.Threading.Tasks.Sources.IValueTaskSource`1.GetStatus(Int16 token)
   at Blinkay.Control.Controllers.ApiController.RunCommand[TCommand](TCommand command) in D:\2DS\Blinkay\aaa\Api\Controllers\ApiController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
....
```

### Expected Behavior

It should not throw.

### Steps To Reproduce

I'm attaching a reduced test case that fails 100% of the time. This is the first time I encounter this kind of error, and I'm reporting here as the same code running on a console application or xunit test works without issues. Just simply do a request to https://localhost:55123/api/installations/1
[test.zip](https://github.com/dotnet/aspnetcore/files/11398317/test.zip)

### Exceptions (if any)

```
System.EntryPointNotFoundException: Entry point was not found.
         at System.Threading.Tasks.Sources.IValueTaskSource`1.GetStatus(Int16 token)
         at Blinkay.Control.Controllers.ApiController.RunCommand[TCommand](TCommand command) in D:\2DS\Blinkay\aaa\Api\Controllers\ApiController.cs:line 31
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

7.0.203

### Anything else?

```
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.200 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by halter73** [comment]
I think the issue here is that `Unsafe.As<ValueTask<DerivedClass>, ValueTask<BaseClass>>(ref task)` is really unsafe and you shouldn't do it.

It happens to work if `ValueTask<T>._obj` is the already-completed result, but when the `_obj` is an `Task<T>` you run into problems.

https://github.com/dotnet/runtime/blob/05a3d360d6079db3cb64636fcdf99f832a58c1d2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs#L714-L719

The issue is not really on line 719. `_obj` is not an `IValueTaskSource<DerivedClass>` nor an `IValueTaskSource<BaseClass>`. The issue happens when it tries to cast to `Task<BaseClass>` and fails on line 714. `_obj` is an `AsyncStateMachineBox<T>` which derives from `Task<DerivedClass>` which cannot be casted to `Task<BaseClass>` because classes unlike interfaces cannot be covariant.

I'm not sure why this results in an `EntryPointNotFoundException`, but I don't think you can expect the best errors when you do unsafe things incorrectly.

**Comment by halter73** [comment]
I see. Then the Mediator source generator code here looks suspicious:

https://github.com/martinothamar/Mediator/blob/7955fc8ca5247fdf98f2265337885c70e72b13a0/src/Mediator.SourceGenerator.Implementation/resources/Mediator.sbn-cs#L399

I think we should probably close this issue and keep https://github.com/martinothamar/Mediator/issues/90 open.
