### ISSUE TITLE
[Test Failure] System.Net.Security.Tests.SslStreamSniTest.UnencodedHostName_ValidatesCertificate on Android

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#86003]
New test introduced by https://github.com/dotnet/runtime/pull/84976

```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- Interop+AndroidCrypto+SslException : Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__149`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Security.Tests.SslStreamSniTest.UnencodedHostName_ValidatesCertificate() in /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamSniTest.cs:line 266
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

**Comment by wfurt** [comment]
Android SNI is more picky AFIK. We should perhaps disable that test. 
 cc: @simonrozsival 

BTW it would be nice if the exception gives at least some clues. (assuming this is whole stack @rzkim)

**Comment by rzikm** [comment]
Test disabled by https://github.com/dotnet/runtime/pull/86241
