### ISSUE TITLE
`System.Text.Json` ignores `JsonConverter` attribute

### ISSUE THREAD

**Issue by ngarside** [dotnet/runtime#86222]
### Description

The `System.Text.Json` source generator will attempt to use the default converter for properties which are adorned with `JsonConverterAttribute`, rather than the specified converter.

### Reproduction Steps

Create a project with these files:

```csharp
// Project.csproj

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
</Project>

// Program.cs

using System.Text.Json;
using System.Text.Json.Serialization;

var entity = new Entity { Content = new byte[] { 1, 2, 3 } };
var json = JsonSerializer.Serialize(entity);
Console.WriteLine(json);

record Entity
{
    [JsonConverter(typeof(MemoryConverter))]
    public ReadOnlyMemory<byte> Content { get; init; }
}

class MemoryConverter : JsonConverter<ReadOnlyMemory<byte>>
{
    public override ReadOnlyMemory<byte> Read(
        ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return reader.GetBytesFromBase64();
    }

    public override void Write(
        Utf8JsonWriter writer, ReadOnlyMemory<byte> value, JsonSerializerOptions options)
    {
        writer.WriteBase64StringValue(value.Span);
    }
}
```

Run the project with `dotnet run`.

### Expected behavior

Program should output `{"Content":"AQID"}`.

### Actual behavior

Program throws `InvalidOperationException`:

```
Unhandled exception. System.InvalidOperationException: The type 'System.ReadOnlySpan`1[System.Byte]' of property 'Span' on type 'System.ReadOnlyMemory`1[System.Byte]' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_CannotSerializeInvalidType(Type typeToConvert, Type declaringType, MemberInfo memberInfo)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreatePropertyInfo(JsonTypeInfo typeInfo, Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options, Boolean shouldCheckForRequiredKeyword)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.AddMembersDeclaredBySuperType(JsonTypeInfo typeInfo, Type currentType, Boolean shouldCheckMembersForRequiredMemberAttribute, PropertyHierarchyResolutionState& state)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateProperties(JsonTypeInfo typeInfo)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type type, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.CachingContext.CacheEntry.GetResult()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|161_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
```

### Regression?

Yes (works with .NET 7).

### Known Workarounds

Use a different type for the property (in this case `byte[]`), although this may not be an option for other types

### Configuration

.NET 7.0.203
.NET 8.0.100-preview.3.23178.7
Windows 11 x64

**Comment by eiriktsarpalis** [comment]
Seems to be caused by #81576, namely the serializer will now attempt to resolve a `JsonTypeInfo<ReadOnlyMemory<byte>>`, but because the converter is only specified on the property it will still attempt to generate the default converter for the type which will fail with an exception.

As a quick workaround, I would recommend registering your `MemoryConverter` with the `JsonSerializerOptions.Converter` list.
