### ISSUE TITLE
Test failure baseservices\\typeequivalence\\simple\\Simple\\Simple.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#86232]
**Failed in:** [runtime-coreclr ilasm 20230513.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272937&view=ms.vss-test-web.build-test-results-tab)

**Failed tests:**
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
    - baseservices\\typeequivalence\\simple\\Simple\\Simple.cmd
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - baseservices\\typeequivalence\\simple\\Simple\\Simple.cmd
coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - baseservices\\typeequivalence\\simple\\Simple\\Simple.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:\h\w\AACF095F\w\B58F09BC\uploads\Reports\baseservices.typeequivalence\simple\Simple\Simple.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\AACF095F\p\ildasm.exe /raweh /unicode /out=Simple.dasm.il Simple.dll
C:\h\w\AACF095F\p\ilasm.exe /output=Simple.asm.dll  Simple.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'Simple.dasm.il'  to EXE --> 'Simple.asm.dll'
Source file is UNICODE

Assembled method Simple?EmptyType2::Create
Assembled method Simple?EmptyType2::.ctor
Assembled method Simple?MethodTestDerived::Create
Assembled method Simple?MethodTestDerived::.ctor
Assembled method Simple?MethodTestDerived::ScaleInt
Assembled method Simple?MethodTestDerived::ScaleString
Assembled method Simple?Generic`1::Method
Assembled method Simple?Generic`1::.ctor
Assembled method Simple?<>c::.cctor
Assembled method Simple?<>c::.ctor
Assembled method Simple?<>c::<TestLoadingValueTypesWithMethod>b__13_0
Assembled method Simple::InterfaceTypesFromDifferentAssembliesAreEquivalent
Assembled method Simple::ValidateTypeInstanceEquality
Assembled method Simple::InterfaceTypesMethodOperations
Assembled method Simple::CallSparseInterface
Assembled method Simple::TestArrayEquivalence
Assembled method Simple::TestByRefEquivalence
Assembled method Simple::TestGenericClassNonEquivalence
Assembled method Simple::TestGenericInterfaceEquivalence
Assembled method Simple::TestTypeEquivalenceWithTypePunning
Assembled method Simple::TestLoadingValueTypesWithMethod
Assembled method Simple::LoadInvalidType
Assembled method Simple::Main
Assembled method Simple::.ctor
Assembled method Simple::<InterfaceTypesFromDifferentAssembliesAreEquivalent>g__AreNotSameObject|1_0
Creating PE file

Emitting classes:
Class 1:Simple
Class 2:Simple�EmptyType2
Class 3:TypeEquivalenceTypes.IEmptyType
Class 4:Simple�MethodTestDerived
Class 5:TypeEquivalenceTypes.IMethodTestType
Class 6:Simple�IGeneric`1
Class 7:Simple�Generic`1
Class 8:Simple�<>c
Class 9:TypeEquivalenceTypes.ISparseType
Class 10:TypeEquivalenceTypes.OnlyLoadOnce_1
Class 11:TypeEquivalenceTypes.OnlyLoadOnce_2
Class 12:TypeEquivalenceTypes.OnlyLoadOnce_3

Emitting fields and methods:
Global 
Class 1Methods: 14;
Class 2Methods: 2;
Class 3
Class 4Fields: 2;Methods: 4;
Class 5Methods: 2;
Class 6Methods: 1;
Class 7Methods: 2;
Class 8Fields: 2;Methods: 3;
Class 9Methods: 4;
Class 10Fields: 1;
Class 11Fields: 1;
Class 12Fields: 1;
Resolving local member refs: 41 -> 41 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global 
Class 1
Class 2
Class 3
Class 4
Class 5
Class 6
Class 7
Class 8
Class 9
Class 10
Class 11
Class 12
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
 "C:\h\w\AACF095F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Simple.asm.dll 
InterfaceTypesFromDifferentAssembliesAreEquivalent
ValidateTypeInstanceEquality
InterfaceTypesMethodOperations
Test Failure: System.TypeLoadException: Bad use of Runtime Impl attribute.
   at Simple.CallSparseInterface()
   at Simple.Main()
END EXECUTION OF IL{D}ASM BINARY - FAILED 101 vs 100
Test failed. Trying to see if dump file was created in C:\cores since 5/13/2023 8:41:33 PM
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AACF095F\p
> C:\h\w\AACF095F\w\B58F09BC\e\baseservices\typeequivalence\simple\Simple\Simple.cmd
Expected: True
Actual:   False
```

**Stack trace:**
```
    at baseservices_typeequivalence._simple_Simple_Simple_._simple_Simple_Simple_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
Key failure text?

```
Test Failure: System.TypeLoadException: Bad use of Runtime Impl attribute.
```

@mangod9 @davidwrighton @jkotas Maybe a type system issue? Any idea what might have changed in this area, or who can investigate?

**Comment by mangod9** [comment]
Assume this is a consistent failure?

**Comment by BruceForstall** [comment]
> Assume this is a consistent failure?

It's a new regression. It consistently failed on three different architecture runs.

**Comment by BruceForstall** [comment]
> @BruceForstall I tried to reproduce this and was unable to. Are you able to reproduce the failure?

Repros for me with:
```
set DOTNET_TieredCompilation=0
set RunningIlasmRoundTrip=1
call Simple.cmd -coreroot c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
```

**Comment by davidwrighton** [comment]
Ah, user error on my part.

Well, there is a round-tripping issue. In particular, the _VtblGap methods on TypeEquivalenceTypes.ISparseType are not keeping their rtspecialname flag. Turns out this a regression from #86055
