### ISSUE TITLE
[6.0] [tvOS] Failed to boot Apple TV: Unable to boot the Simulator

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#86274]
### Error Blob

- Found in 6.0 PR: https://github.com/dotnet/runtime/pull/85976
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=267323&view=ms.vss-test-web.build-test-results-tab&runId=5268702&resultId=170693&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
- Artifacts: https://dev.azure.com/dnceng-public/public/_build/results?buildId=267323&view=ms.vss-test-web.build-test-results-tab&runId=5268702&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=170693
- Job: https://dev.azure.com/dnceng-public/public/public%20Team/_build/results?buildId=267323&view=logs&j=e4e455c5-b032-5051-d2c5-a64982c9ac45&t=5de5e156-699a-557b-38b4-10fd41c307dc&l=59
- Queue: `Build tvOSSimulator x64 Release AllSubsets_Mono`
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-85976-merge-2e46abf052f94c5981/System.IO.Pipelines.Tests/1/console.8253a092.log?helixlogtype=result

```json
{
  "ErrorMessage": "Cleaning up the failed installation from 'Apple TV'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

Callstack:

```
[12:17:15] dbug: Installing '/tmp/helix/working/AC920919/w/999E08B9/e/System.IO.Pipelines.Tests.app' to 'Apple TV' (46.04 MB)
[12:17:15] dbug: Running /private/tmp/helix/working/AC920919/p/microsoft.dotnet.xharness.cli/6.0.0-prerelease.23253.6/tools/net6.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_13.1.app --device=:v2:udid=7A684FBE-97F2-4D8E-848D-F959E5BD38A6 --installsim /tmp/helix/working/AC920919/w/999E08B9/e/System.IO.Pipelines.Tests.app -v -v
[12:17:17] dbug: Using Xcode 13.1 found in /Applications/Xcode_13.1.app
[12:17:17] dbug: Xamarin.Hosting: Xamarin.Hosting
[12:17:17] dbug: Xamarin.Hosting:     Version: 729eaa8fe3 (refs/heads/main)
[12:17:17] dbug: Xamarin.Hosting:     Xcode: /Applications/Xcode_13.1.app
[12:17:17] dbug: Xamarin.Hosting:     Xcode Version: 13.1
[12:17:17] dbug: Xamarin.Hosting:     Verbosity: 2
[12:17:19] dbug: Xamarin.Hosting: Booting Apple TV...
[12:17:36] dbug: Xamarin.Hosting: Failed to boot Apple TV: Unable to boot the Simulator..
[12:17:36] dbug: Xamarin.Hosting: Will try to continue anyway.
[12:17:36] dbug: Xamarin.Hosting: Installing on tvOS 15.0 (19J344) - Apple TV by executing 'xcrun simctl install 7A684FBE-97F2-4D8E-848D-F959E5BD38A6 /tmp/helix/working/AC920919/w/999E08B9/e/System.IO.Pipelines.Tests.app'
[12:22:52] dbug: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
[12:22:52] dbug: Unable to lookup in current state: Shutdown
[12:22:53] dbug: error HE0046: Failed to install the app 'net.dot.System.IO.Pipelines.Tests' on the device 'tvOS 15.0 (19J344) - Apple TV': simctl returned exit code 149
[12:22:53] dbug: Process mlaunch exited with 1
[12:22:53] fail: Failed to install the application
[12:22:53] info: Cleaning up the failed installation from 'Apple TV'
[12:22:53] info: Uninstalling the application 'net.dot.System.IO.Pipelines.Tests' from 'Apple TV'
[12:22:53] dbug: Running /Applications/Xcode_13.1.app/Contents/Developer/usr/bin/simctl uninstall 7A684FBE-97F2-4D8E-848D-F959E5BD38A6 net.dot.System.IO.Pipelines.Tests
[12:22:53] dbug: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
[12:22:53] dbug: Unable to lookup in current state: Shutdown
[12:22:53] dbug: Process simctl exited with 149
[12:22:53] fail: Failed to uninstall the app bundle! Check logs for more details!
```

Unsure if related, but the macos.system.log file in the artifacts shows these two errors:
```
2023-05-09 12:14:35.848995-0400  localhost runningboardd[197]: (RunningBoard) Created Activity ID: 0x73aed, Parent ID: 0x8000000000073fbd, Description: acquireAssertionWithDescriptor
2023-05-09 12:14:35.849226-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:general] Launchd didn't have information for pid 47743, reason: Error Domain=NSPOSIXErrorDomain Code=113 "Unknown error: 113"
2023-05-09 12:14:35.849247-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:process] _resolveProcessWithIdentifier pid 47743 euid 504 auid 504
2023-05-09 12:14:35.849248-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:process] Unable to obtain process properties from launchd for pid=47743
2023-05-09 12:14:35.849330-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:process] Resolved pid 47743 to [anon<dataaccessd>(504):47743]
2023-05-09 12:14:35.849411-0400  localhost runningboardd[197]: (RunningBoardServices) [com.apple.runningboard:general] Full encoding handle <private>, with data 5b87cda40000ba7f, and pid 47743
2023-05-09 12:14:35.849520-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:process] [anon<dataaccessd>(504):47743] This process will not be managed.
2023-05-09 12:14:35.849523-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:process] Now tracking process: [anon<dataaccessd>(504):47743]
2023-05-09 12:14:35.849800-0400  localhost runningboardd[197]: (AppServerSupport) [com.apple.libxpc.OSLaunchdJob:all] copyJobWithPid:47743 failed with error 113: Could not find specified service
2023-05-09 12:14:35.849892-0400  localhost runningboardd[197]: (RunningBoard) [com.apple.runningboard:assertion] Acquiring assertion targeting [anon<dataaccessd>(504):47743] from originator [daemon<com.apple.powerd>:99] with description <RBSAssertionDescriptor| "App is holding power assertion" ID:197-99-2078 target:47743 attributes:[
	<RBSDomainAttribute| domain:"com.apple.appnap" name:"PowerAssertion" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
```

And the listing-tvos-simulator.log file had these lines:

```
[12:16:38.8264700] mlaunch failed when listing simulators but trying to parse the results anyway
[12:16:38.8398490] Failed to find/create simulator (attempt 1/3):
System.Exception: Failed to list simulators - no XML with devices found. mlaunch timed out with 137)
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData, Boolean _) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 81
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Boolean createIfNeeded, Boolean minVersion) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 351
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Int32 retryCount, Boolean createIfNeeded, Boolean minVersion) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 478
[12:16:38.8407590] Running /private/tmp/helix/working/AC920919/p/microsoft.dotnet.xharness.cli/6.0.0-prerelease.23253.6/tools/net6.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_13.1.app --listsim=/tmp/helix/working/AC920919/t/tmp6VVPkF.tmp --output-format=XML -v -v -v -v -v

[12:16:41.1725140] Using Xcode 13.1 found in /Applications/Xcode_13.1.app
[12:16:41.1840320] Xamarin.Hosting: Xamarin.Hosting
[12:16:41.1841280] Xamarin.Hosting:     Version: 729eaa8fe3 (refs/heads/main)
[12:16:41.1841750] Xamarin.Hosting:     Xcode: /Applications/Xcode_13.1.app
[12:16:41.1876350] Xamarin.Hosting:     Xcode Version: 13.1
[12:16:41.1876900] Xamarin.Hosting:     Verbosity: 5
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by akoeplinger** [comment]
Closing old known issue since it hasn't happened anymore.
