### ISSUE TITLE
Test failure: System.Buffers.Text.Tests.FormatterTests.TestFormatterSingle

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#86275]
runtime-coreclr libraries-jitstress2-jitstressregs

arm64 (windows and linux), JitStress=2, JitStressRegs=3

https://dev.azure.com/dnceng-public/public/_build/results?buildId=272702&view=ms.vss-test-web.build-test-results-tab

Example:
```
    System.Buffers.Text.Tests.FormatterTests.TestFormatterSingle(testData: [FormatSingle 0,E to '0.000000E+000')]) [FAIL]
      Assert.Equal() Failure
                  (pos 1)
      Expected: 0.000000E+000
      Actual:   0
                  (pos 1)
      Stack Trace:
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Formatter/ValidateFormatter.cs(79,0): at System.Buffers.Text.Tests.FormatterTests.ValidateFormatterHelper[T](FormatterTestData`1 testData)
        /_/src/libraries/System.Memory/tests/ParsersAndFormatters/Formatter/ValidateFormatter.cs(18,0): at System.Buffers.Text.Tests.FormatterTests.ValidateFormatter[T](FormatterTestData`1 testData)
           at InvokeStub_FormatterTests.TestFormatterSingle(Object, Object, IntPtr*)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
    System.Buffers.Text.Tests.FormatterTests.TestFormatterSingle(testData: [FormatSingle 0,E0 to '0E+000')]) [FAIL]
```

**Comment by kunalspathak** [comment]
I don't see this is failing from past 1 month and can't access the build log listed in the issue. I will close it as "no repro".
