### ISSUE TITLE
.NET 6 Android, The certificate data cannot be read with the provided password, the password may be incorrect

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#86349]
moved from https://github.com/mono/mono/issues/21300 cc @amarthere

I created sample application in VS 2022 with .NET 6.0 for both Android and iOS.
In that application I am creating X509Certificate object using pfx file and password.
The application is running fine on iOS but on Android i am getting below error:
Can you please look into it?

I am attaching sample application which reproduces the issue:
[MauiApp1.zip](https://github.com/mono/mono/files/7509160/MauiApp1.zip)

Exception: The certificate data cannot be read with the provided password, the password may be incorrect.
[DOTNET] Exception: at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
[DOTNET] at Internal.Cryptography.Pal.AndroidCertificatePal.ReadPkcs12(ReadOnlySpan1 rawData, SafePasswordHandle password, Boolean ephemeralSpecified) [DOTNET]    at Internal.Cryptography.Pal.AndroidCertificatePal.FromBlob(ReadOnlySpan1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[DOTNET] at Internal.Cryptography.Pal.AndroidCertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[DOTNET] at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
[DOTNET] at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
[DOTNET] at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
[DOTNET] at MauiApp1.App.ECDSACertificateTest() in C:\Users\jadhaa01\source\repos\MauiApp1\MauiApp1\App.xaml.cs:line 154

**Comment by lewing** [comment]
looks similar to https://github.com/dotnet/runtime/issues/85019

**Comment by vcsjones** [comment]
> looks similar to #85019

Yeah. The certificate in the example is encrypted with pbeWithSHAAnd40BitRC2-CBC.

**Comment by akoeplinger** [comment]
@amarthere if you have the openssl tool installed somewhere you can use this commandline:

```
openssl pkcs12 -info -in ECDSA_cert_internal.pfx
```

It will print some info including this which shows that RC2 was used:
```
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 1024
```

**Comment by amarthere** [comment]
Hi @akoeplinger,

I ran the same command and noticed that we don't use RC2. We use "pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 1024"
It seems Android does support this algorithm. https://developer.android.com/reference/javax/crypto/Cipher

We get below error when using the certificate:
**"The certificate data cannot be read with the provided password, the password may be incorrect."**
Please see my original ticket for more details:
https://github.com/mono/mono/issues/21300


<img width="569" alt="Screenshot 2023-05-25 at 2 29 34 PM" src="https://github.com/dotnet/runtime/assets/45111478/4f477824-fc85-40e3-a578-eeb67c741313">

Regards,
Amar

**Comment by bartonjs** [comment]
That's only one of the two pieces of encrypted data (the private key), to see the other (the certificate(s)) you'll need to do something more like

```sh
$ openssl asn1parse -inform der -in self.pfx -i
    0:d=0  hl=4 l=1649 cons: SEQUENCE
    4:d=1  hl=2 l=   1 prim:  INTEGER           :03
    7:d=1  hl=4 l=1591 cons:  SEQUENCE
   11:d=2  hl=2 l=   9 prim:   OBJECT            :pkcs7-data
   22:d=2  hl=4 l=1576 cons:   cont [ 0 ]
   26:d=3  hl=4 l=1572 prim:    OCTET STRING      [HEX DUMP]:308206203082031F06092A864886F70D010706A08203103082030C0201003082030506092A864886F70D010701301C060A2A864886F70D010C0106300E0408E0CBC266D7284F6302020800808202D8F5EEA15B6B1800B10182A45C73BBC3A1772A96A01A40AB3EB5BBC1D418DF2CB8F5A7BD52E773E779E4C71A3487B05BC9EF2DE234399A33047D8A00058CC36DAF0FE982ABEF7E39A180467700DFC4D943960EFD3B03775A2BC4A4CE19D1A8B2A2EBC1178438F6A02C259BEE5D26D0E438D78BBA6CC7A19BE9BC3B5E08E6023D387EB471A501739C7C4F005AD140D58EBD1DEFEDAD90195DF4F3C71B8B081D4C84C8A64058BC4EF593B9AAD6AEA2E3D40CAA6517EFC807AEB40500C871C554109821D7B13866E10E94D88FC0CA1A89F4BC0895C84081479C16F2718CF75FD1BE7B845FB2172D9513B588D98AA1B5178809742741E71C7FDA72FE1A5750E7F4623FB8C8A4BA8E4912A814B047C969EAA855A9B9A1232565F744234E1B4BF74711286B785E689CE24D8B45F4863C9D9CEE292284E3BF64BA76E359E6F7009CE04769CCFDC38A7D5D6D3B213CD4D26F45FB25C3C2E2FFC7EF0AA68DECA74AE42782E2F1389D779E63F1DF839E28D6AAC40CAF35913C445521DF96267BC8DB1FF85A6D5006F878BBB88AF7CC866890CACD5E1DF89D49B496A114A5C2024FA2FDE19B7AE2013C9281C77313BFD152219762B75C94FD7A1A68A05E51F7D0FE17EBF0524703592624AB24009BD139DD5678A97043596D445BA2822F0EE1F311926CE040DB781BF3C67AE2FC1F4A8688C2EF13A51172BDDB77A167B8DFFF9B982B50A8E64D6BAC815B6A3579867B87A1D7727C03E0DF14D051D240B30C218E5370E11BCA826F3313867EA53CC0B24302D6C4E16FBEC19E448BD2ECC044E6F68CF6A08FAC703E901091814270E8EAD2FCA4F9D3C8815A0D17C0245331BD3D8EA45E75872CC0200AB48D4BD78821D3F3620CC757F1FB45B12F2D180908F477BC94EF23C157FB6EB863479A54D00C2EFC20D893DE4276A88A79C6A0C0DEB08A06E8C7C33D6389D64CDBAEF7E6E128CE7E1F07702FED764141F9DC6AB071D75FB5D962E4C3ACCA50E47D893D015B8E67DCDDB6B76BC2D533823B4659D87DCD308202F906092A864886F70D010701A08202EA048202E6308202E2308202DE060B2A864886F70D010C0A0102A08202A6308202A2301C060A2A864886F70D010C0103300E0408661C16B9FD4EF6630202080004820280C746D217E81FD31E6172B190F3B2C3886D226D0BBC465FFBE4206A3526452BC2EF74B590A0D7FC5350EB2FB9267D0094962AA9573FF5BA0133F149595C847B1479A5B6B9A68F8B372416EF56BD3671F39E2F3E8458128B23E3CB1AA904002474400325ADB25ABB59A8EEC7C9CCD833462E5C29BBB6071029426AA411148D56F47430745960EC1957FB7EB320D78322355F7F6EDDF33A95E08AF71FC81857371751315C8BE253AEED6EAF2869568528A10DF84BBC23BA37318EEA2B894161FC10AEE577EC7A71F062C57D71281894828BEAB367D70671639F7F22F966056FE441790DB1F3EBEA3E55C7B8C6DBB393462ACAF25B1D1A2D6C8C7B817D1CD02DCE6A35C5C32C6AFE8B42458982F46C9F77AB605AFAF481078E9824614A08173C163F30093ADF1F1AFBA117D8A78688F393C0DDBCBC348F5347ECD07AD5A3733B9C854FAF879FAE815705585D79C16FB3AC720198D73DB26FC1159E1CEA7F19A8284ACB0E8BB6DD61A382434A5F502F1532F5E6F9004C0DA15C869DF9D601FA62460CFE7CEF9713916A2ADC7D26A09650B1200DE458E0308A18E0A62636AE452ACD32EFD450FD032C04E6DFBF3420CE5FB51D95819325AF904D58E3FFC138F772E7E4B8A6F696C530B4FD0B89634FC4E065BD922F6009B03FC676EC7745BF4A9BCDF0AA2934D88AD024E66BA663064E1A7B73E412C12A01FBDC07ED6CE379A53FFBF6B1A3E205E7FEBFF4F2079BAFE24D5676F5A02CA7308DDE0CB393BA6AF43372182C2870825BDDF9A137C376AFA17D164B6AC8C9E2C5D73C07C2D39868C7E27C88DB7F6146396F79304020E868D80E80C441686A151885DB482C24A88FD1EFC411B23B1A8C0AC462F45F3680E3D666F4C7E863B3F362B62DF9EE1B512167F2B7F03125302306092A864886F70D01091531160414245386AD2DE5689DD67CFF9CC3E2340D2CF9FEFD
 1602:d=1  hl=2 l=  49 cons:  SEQUENCE
 1604:d=2  hl=2 l=  33 cons:   SEQUENCE
 1606:d=3  hl=2 l=   9 cons:    SEQUENCE
 1608:d=4  hl=2 l=   5 prim:     OBJECT            :sha1
 1615:d=4  hl=2 l=   0 prim:     NULL
 1617:d=3  hl=2 l=  20 prim:    OCTET STRING      [HEX DUMP]:06D6F1D3F993F388658714199F20557662A276CB
 1639:d=2  hl=2 l=   8 prim:   OCTET STRING      [HEX DUMP]:0C70A7F240119B61
 1649:d=2  hl=2 l=   2 prim:   INTEGER           :0800
```

Two lines below pkcs7-data we have an `OCTET STRING`.  Take the start offset (26) and add the header length (hl) (4), and get 30, so now call it again with `-offset 30`:

```
$ openssl asn1parse -inform der -in self.pfx -i -offset 30
    0:d=0  hl=4 l=1568 cons: SEQUENCE
    4:d=1  hl=4 l= 799 cons:  SEQUENCE
    8:d=2  hl=2 l=   9 prim:   OBJECT            :pkcs7-encryptedData
   19:d=2  hl=4 l= 784 cons:   cont [ 0 ]
   23:d=3  hl=4 l= 780 cons:    SEQUENCE
   27:d=4  hl=2 l=   1 prim:     INTEGER           :00
   30:d=4  hl=4 l= 773 cons:     SEQUENCE
   34:d=5  hl=2 l=   9 prim:      OBJECT            :pkcs7-data
   45:d=5  hl=2 l=  28 cons:      SEQUENCE
   47:d=6  hl=2 l=  10 prim:       OBJECT            :pbeWithSHA1And40BitRC2-CBC
   59:d=6  hl=2 l=  14 cons:       SEQUENCE
   61:d=7  hl=2 l=   8 prim:        OCTET STRING      [HEX DUMP]:E0CBC266D7284F63
   71:d=7  hl=2 l=   2 prim:        INTEGER           :0800
   75:d=5  hl=4 l= 728 prim:      cont [ 0 ]
  807:d=1  hl=4 l= 761 cons:  SEQUENCE
  811:d=2  hl=2 l=   9 prim:   OBJECT            :pkcs7-data
  822:d=2  hl=4 l= 746 cons:   cont [ 0 ]
  826:d=3  hl=4 l= 742 prim:    OCTET STRING      [HEX DUMP]:308202E2308202DE060B2A864886F70D010C0A0102A08202A6308202A2301C060A2A864886F70D010C0103300E0408661C16B9FD4EF6630202080004820280C746D217E81FD31E6172B190F3B2C3886D226D0BBC465FFBE4206A3526452BC2EF74B590A0D7FC5350EB2FB9267D0094962AA9573FF5BA0133F149595C847B1479A5B6B9A68F8B372416EF56BD3671F39E2F3E8458128B23E3CB1AA904002474400325ADB25ABB59A8EEC7C9CCD833462E5C29BBB6071029426AA411148D56F47430745960EC1957FB7EB320D78322355F7F6EDDF33A95E08AF71FC81857371751315C8BE253AEED6EAF2869568528A10DF84BBC23BA37318EEA2B894161FC10AEE577EC7A71F062C57D71281894828BEAB367D70671639F7F22F966056FE441790DB1F3EBEA3E55C7B8C6DBB393462ACAF25B1D1A2D6C8C7B817D1CD02DCE6A35C5C32C6AFE8B42458982F46C9F77AB605AFAF481078E9824614A08173C163F30093ADF1F1AFBA117D8A78688F393C0DDBCBC348F5347ECD07AD5A3733B9C854FAF879FAE815705585D79C16FB3AC720198D73DB26FC1159E1CEA7F19A8284ACB0E8BB6DD61A382434A5F502F1532F5E6F9004C0DA15C869DF9D601FA62460CFE7CEF9713916A2ADC7D26A09650B1200DE458E0308A18E0A62636AE452ACD32EFD450FD032C04E6DFBF3420CE5FB51D95819325AF904D58E3FFC138F772E7E4B8A6F696C530B4FD0B89634FC4E065BD922F6009B03FC676EC7745BF4A9BCDF0AA2934D88AD024E66BA663064E1A7B73E412C12A01FBDC07ED6CE379A53FFBF6B1A3E205E7FEBFF4F2079BAFE24D5676F5A02CA7308DDE0CB393BA6AF43372182C2870825BDDF9A137C376AFA17D164B6AC8C9E2C5D73C07C2D39868C7E27C88DB7F6146396F79304020E868D80E80C441686A151885DB482C24A88FD1EFC411B23B1A8C0AC462F45F3680E3D666F4C7E863B3F362B62DF9EE1B512167F2B7F03125302306092A864886F70D01091531160414245386AD2DE5689DD67CFF9CC3E2340D2CF9FEFD
 1572:d=0  hl=2 l=  49 cons: SEQUENCE
 1574:d=1  hl=2 l=  33 cons:  SEQUENCE
 1576:d=2  hl=2 l=   9 cons:   SEQUENCE
 1578:d=3  hl=2 l=   5 prim:    OBJECT            :sha1
 1585:d=3  hl=2 l=   0 prim:    NULL
 1587:d=2  hl=2 l=  20 prim:   OCTET STRING      [HEX DUMP]:06D6F1D3F993F388658714199F20557662A276CB
 1609:d=1  hl=2 l=   8 prim:  OCTET STRING      [HEX DUMP]:0C70A7F240119B61
 1619:d=1  hl=2 l=   2 prim:  INTEGER           :0800
```

That shows a segment of `pkcs7-encryptedData` using `pbeWithSHA1And40BitRC2-CBC`, which is the part of the file containing the certificates.  (If we repeated the recursion at offset (30 + 826 + 4) we'd see an encrypted segment using `pbeWithSHA1And3-KeyTripleDES-CBC`, which is the private key).  This certificate section is what .NET on Android can't read.

You can rebuild the PFX with OpenSSL, and supply the `-descert` option, e.g. `openssl pkcs12 -export -in some.cer -inkey some.key -out some.pfx -descert`, and then .NET on Android should be able to read it.   (That changes the cert encryption from RC2-40 to 3DES)
