### ISSUE TITLE
The context has expired and can no longer be used

### ISSUE THREAD

**Issue by okarpov** [dotnet/runtime#86385]
### Description

```
One or more errors occurred. (The SSL connection could not be established, see inner exception.) :
    System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> System.ComponentModel.Win32Exception (590615): The context has expired and can no longer be used.
--- End of inner exception stack trace ---
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
```

### Reproduction Steps

```c#
ViewModels.BrokerFMCSAStatus CheckBrokerFMCSA(string mcNum)
        {
            ViewModels.BrokerFMCSAStatus res = new ViewModels.BrokerFMCSAStatus();
            try
            {
                string resp = string.Empty;
                var socketsHandler = new System.Net.Http.HttpClientHandler()
                {
                    AutomaticDecompression = System.Net.DecompressionMethods.All,
                    SslProtocols = System.Security.Authentication.SslProtocols.Tls13 | System.Security.Authentication.SslProtocols.Tls12,
                    ServerCertificateCustomValidationCallback = CertValidCallback,
                    ClientCertificateOptions = ClientCertificateOption.Automatic,
                    CheckCertificateRevocationList = false,

                };
                var sockHandler = (System.Net.Http.SocketsHttpHandler)GetUnderlyingSocketsHttpHandler(socketsHandler);
                sockHandler.SslOptions = new SslClientAuthenticationOptions()
                {
                    AllowRenegotiation = true,
                    CertificateRevocationCheckMode = X509RevocationMode.NoCheck,
                    EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls13 | System.Security.Authentication.SslProtocols.Tls12,
                    RemoteCertificateValidationCallback = new RemoteCertificateValidationCallback((sender, certificate, chain, policyErrors) => { return true; })
                };



                using (System.Net.Http.HttpClient wc = new System.Net.Http.HttpClient(socketsHandler, true))
                {
                    
                    wc.DefaultRequestVersion = System.Net.HttpVersion.Version20;
                    wc.DefaultVersionPolicy = System.Net.Http.HttpVersionPolicy.RequestVersionOrLower;

                    wc.DefaultRequestHeaders.Accept.TryParseAdd("text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");
                    wc.DefaultRequestHeaders.AcceptEncoding.TryParseAdd("gzip, deflate, br");
                    wc.DefaultRequestHeaders.AcceptLanguage.TryParseAdd("en-US,en;q=0.9");
                    wc.DefaultRequestHeaders.TryAddWithoutValidation("sec-ch-ua", "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"");
                    wc.DefaultRequestHeaders.TryAddWithoutValidation("ContentType", "application/x-www-form-urlencoded");
                    wc.DefaultRequestHeaders.TryAddWithoutValidation("origin", "https://safer.fmcsa.dot.gov");
                    wc.DefaultRequestHeaders.Referrer = new Uri("https://safer.fmcsa.dot.gov/");
                    wc.DefaultRequestHeaders.UserAgent.TryParseAdd("Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36");
                    resp = wc.PostAsync("https://safer.fmcsa.dot.gov/query.asp", new StringContent( 
                        "searchtype=ANY&query_type=queryCarrierSnapshot&query_param=MC_MX&query_string=" + mcNum
                    )).Result.Content.ReadAsStringAsync().Result;

                }
                res.RawHTML = resp;
            }
            catch (System.Net.WebException wex)
            {
                try
                {
                    using (var wexstream = new System.IO.StreamReader(wex.Response.GetResponseStream()))
                    {
                        wex=wex;
                    }
                }
                catch(Exception wwex)
                {
                    wwex=wwex;
                }
            }
            catch (Exception ex)
            {
                ex=ex;
            }

            return res;
        }

        protected static bool CertValidCallback(HttpRequestMessage s, X509Certificate2 e, X509Chain a, SslPolicyErrors b)
        {
            return true;
        }
        public static bool RemoteCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors policyErrors) { return true; }

        protected static object GetUnderlyingSocketsHttpHandler(System.Net.Http.HttpClientHandler handler)
        {
            return typeof(System.Net.Http.HttpClientHandler).GetField("_underlyingHandler", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)?.GetValue(handler);
        }
```

### Expected behavior

should return HTML content

### Actual behavior

```
One or more errors occurred. (The SSL connection could not be established, see inner exception.) :
    System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> System.ComponentModel.Win32Exception (590615): The context has expired and can no longer be used.
--- End of inner exception stack trace ---
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
```

### Configuration
IIS Server
.Net 3.1 - .Net 7.0

### Other information

Windows Server 2012 R2 Standard

**Comment by wfurt** [comment]
Do you know if this fails with Tls12 only @okarpov? I would expect so as Server 2012 does not support TLS 13. 
I also think this is not actionable as written. Could you please some up with minimal runable repro and possible server that can be used for testing?

**Comment by okarpov** [comment]
this should be completely standalone working method you can run udner Console.
Unfortunately i have no other server like that and can not share my client's server credentials, sorry.
do not know about Tls12 only or not

'''
void CheckBrokerFMCSA(string mcNum="235546")
        {
            try
            {
                string resp = string.Empty;
                var socketsHandler = new System.Net.Http.HttpClientHandler()
                {
                    AutomaticDecompression = System.Net.DecompressionMethods.All,
                    SslProtocols = System.Security.Authentication.SslProtocols.Tls13 | System.Security.Authentication.SslProtocols.Tls12,
                    ServerCertificateCustomValidationCallback = CertValidCallback,
                    ClientCertificateOptions = ClientCertificateOption.Automatic,
                    CheckCertificateRevocationList = false,

                };
                var sockHandler = (System.Net.Http.SocketsHttpHandler)GetUnderlyingSocketsHttpHandler(socketsHandler);
                sockHandler.SslOptions = new SslClientAuthenticationOptions()
                {
                    AllowRenegotiation = true,
                    CertificateRevocationCheckMode = X509RevocationMode.NoCheck,
                    EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls13 | System.Security.Authentication.SslProtocols.Tls12,
                    RemoteCertificateValidationCallback = new RemoteCertificateValidationCallback((sender, certificate, chain, policyErrors) => { return true; })
                };



                using (System.Net.Http.HttpClient wc = new System.Net.Http.HttpClient(socketsHandler, true))
                {
                    
                    wc.DefaultRequestVersion = System.Net.HttpVersion.Version20;
                    wc.DefaultVersionPolicy = System.Net.Http.HttpVersionPolicy.RequestVersionOrLower;

                    wc.DefaultRequestHeaders.Accept.TryParseAdd("text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9");
                    wc.DefaultRequestHeaders.AcceptEncoding.TryParseAdd("gzip, deflate, br");
                    wc.DefaultRequestHeaders.AcceptLanguage.TryParseAdd("en-US,en;q=0.9");
                    wc.DefaultRequestHeaders.TryAddWithoutValidation("sec-ch-ua", "\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"104\"");
                    wc.DefaultRequestHeaders.TryAddWithoutValidation("ContentType", "application/x-www-form-urlencoded");
                    wc.DefaultRequestHeaders.TryAddWithoutValidation("origin", "https://safer.fmcsa.dot.gov");
                    wc.DefaultRequestHeaders.Referrer = new Uri("https://safer.fmcsa.dot.gov/");
                    wc.DefaultRequestHeaders.UserAgent.TryParseAdd("Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36");
                    resp = wc.PostAsync("https://safer.fmcsa.dot.gov/query.asp", new StringContent( 
                        "searchtype=ANY&query_type=queryCarrierSnapshot&query_param=MC_MX&query_string=" + mcNum
                    )).Result.Content.ReadAsStringAsync().Result;

                }
                resp = resp;
            }
            catch (System.Net.WebException wex)
            {
                try
                {
                    using (var wexstream = new System.IO.StreamReader(wex.Response.GetResponseStream()))
                    {
                        wex=wex;
                    }
                }
                catch(Exception wwex)
                {
                    wwex=wwex;
                }
            }
            catch (Exception ex)
            {
                ex=ex;
            }

            return res;
        }

        protected static bool CertValidCallback(HttpRequestMessage s, X509Certificate2 e, X509Chain a, SslPolicyErrors b)
        {
            return true;
        }
        public static bool RemoteCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors policyErrors) { return true; }

        protected static object GetUnderlyingSocketsHttpHandler(System.Net.Http.HttpClientHandler handler)
        {
            return typeof(System.Net.Http.HttpClientHandler).GetField("_underlyingHandler", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)?.GetValue(handler);
        }
'''

**Comment by rzikm** [comment]
@okarpov I am unable to reproduce the issue with the console code you provided on Win 11. Does removing `Tls13` from the `SslProtocols` fix the problem on your machine?

I'm afraid that without more info the this issue is not actionable for us.
