### ISSUE TITLE
Test failure System.Text.Json.Serialization.Tests.EnumConverterTests.NegativeEnumValue_CultureInvariance

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#86417]
**Failed in:** runtime-coreclr libraries-jitstress-random 20230517.1

**Failed tests:**
```
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress_random_1-Windows.11.Arm64.Open
    - System.Text.Json.Serialization.Tests.EnumConverterTests.NegativeEnumValue_CultureInvariance
    - System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException
    - System.Text.Json.Serialization.Tests.CacheTests.JsonSerializerOptions_ReuseConverterCaches
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Exception of type 'Microsoft.DotNet.RemoteExecutor.RemoteExecutionException' was thrown.
```

**Stack trace:**
```
 
Child exception:
  System.FormatException: Format specifier was invalid.
   at System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(Int64 value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.SignedNumber.cs:line 57
   at System.Text.Json.Utf8JsonWriter.WriteNumberValue(Int64 value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.SignedNumber.cs:line 48
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs:line 241
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 393
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.WriteCore.cs:line 16
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoOfT.WriteHelpers.cs:line 53
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs:line 163
   at System.Text.Json.Serialization.Tests.EnumConverterTests.<>c.<NegativeEnumValue_CultureInvariance>b__19_0() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/EnumConverterTests.cs:line 379
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59

Child process:
  System.Text.Json.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Text.Json.Serialization.Tests.EnumConverterTests+<>c Void <NegativeEnumValue_CultureInvariance>b__19_0()


```

**Comment by BruceForstall** [comment]
The failure was
```
DOTNET_JitStress=285
DOTNET_TieredCompilation=0
```

but is it only JitStress?

https://dev.azure.com/dnceng-public/public/_build/results?buildId=277067&view=ms.vss-test-web.build-test-results-tab&runId=5494920&resultId=192561&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by eiriktsarpalis** [comment]
Appears to have been a one-off test failure back in May. Closing for now.
