### ISSUE TITLE
HttpClient returns "System.IO.IOException: The response ended prematurely" when run in a container

### ISSUE THREAD

**Issue by albertich** [dotnet/runtime#86434]
### Description

Hello!
I've encountered different behavior of ignoring the server certificate when using a proxy in an httpclient on the local machine and in a container.

### Reproduction Steps

Code

```
using System.Net;
using Microsoft.Extensions.DependencyInjection;

var serviceCollection = new ServiceCollection();
serviceCollection.AddHttpClient("test")
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        var httpClientHandler = new HttpClientHandler();
        httpClientHandler.Proxy = new WebProxy("some_proxy_url");
        httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;
        return httpClientHandler;
    });

var serviceProvider = serviceCollection.BuildServiceProvider();

await serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient("test").GetAsync("https://google.com");

Console.WriteLine("Application completed");
```

Dockerfile

```
FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "ConsoleApp1.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]
```

### Expected behavior

Application completes successfully

### Actual behavior

When run on local machine works as expected, when run in a container the following error occurs

```
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args) in /src/Program.cs:line 16
   at Program.<Main>(String[] args)
```

### Configuration

.NET 7.0.5
Ubuntu 22.04.2 LTS
x64

**Comment by wfurt** [comment]
You should get packet captures with Wireshark @albertich. This is likely coming from external sources. Perhaps something about the container setup.

**Comment by albertich** [comment]
@wfurt I have attached the dockerfile that I tested with. There are no custom settings.

**Comment by MihaZupan** [comment]
Were you able to collect a network capture/create a standalone project that reproduces the issue @albertich?
Without knowing how the proxy behaves, it will be hard for us to track the issue down.
