### ISSUE TITLE
Test failure GC\\Scenarios\\NDPin\\ndpinfinal\\ndpinfinal.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#86562]
Run: [runtime-coreclr jitstress-random 20230521.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281278&view=ms.vss-test-web.build-test-results-tab&runId=5581518&resultId=119907&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress_random_2 @ Windows.10.Amd64.Open

- GC\\Scenarios\\NDPin\\ndpinfinal\\ndpinfinal.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\BCD409F6\w\ACED08CB\uploads\Reports\GC.Scenarios\NDPin\ndpinfinal\ndpinfinal.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\BCD409F6\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ndpinfinal.dll
Test should return with ExitCode 100 ...
1 objects have been finalized!
Test Failed!
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/21/2023 7:58:09 PM
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:



set CORE_ROOT=C:\h\w\BCD409F6\p
C:\h\w\BCD409F6\w\ACED08CB\e\GC\Scenarios\NDPin\ndpinfinal\ndpinfinal.cmd
Expected: True
Actual:   False




Stack trace
   at GC_Scenarios._NDPin_ndpinfinal_ndpinfinal_._NDPin_ndpinfinal_ndpinfinal_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by Maoni0** [comment]
env vars set for this test from https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-abb2f6cad574400b9b/PayloadGroup0/1/console.86e05407.log?helixlogtype=result

set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2b2

**Comment by v-wenyuxu** [comment]
Failed again in: [runtime-coreclr jitstress-random 20230604.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=295095&view=ms.vss-test-web.build-test-results-tab&runId=5941276&resultId=119633&paneView=debug)

Failed test:
```
coreclr windows x64 Checked jitstress_random_2 @ Windows.10.Amd64.Open

- GC\\Scenarios\\NDPin\\ndpinfinal\\ndpinfinal.cmd

coreclr osx x64 Checked jitstress_random_1 @ OSX.1200.Amd64.Open

- GC/Scenarios/NDPin/ndpinfinal/ndpinfinal.sh
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\B83E0999\w\B7DB09C4\uploads\Reports\GC.Scenarios\NDPin\ndpinfinal\ndpinfinal.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B83E0999\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ndpinfinal.dll
Test should return with ExitCode 100 ...
1 objects have been finalized!
Test Failed!
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 6/4/2023 8:09:22 PM
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:



set CORE_ROOT=C:\h\w\B83E0999\p
C:\h\w\B83E0999\w\B7DB09C4\e\GC\Scenarios\NDPin\ndpinfinal\ndpinfinal.cmd
Expected: True
Actual:   False




Stack trace
   at GC_Scenarios._NDPin_ndpinfinal_ndpinfinal_._NDPin_ndpinfinal_ndpinfinal_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Closing since this hasnt reproed in a few months.
