### ISSUE TITLE
[browser][MT] Memory growth on worker could cause failure

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#86642]
When we compile the runtime with `/p:MonoWasmBuildVariant=multithread` and the web worker would cause memory growth, the linear memory buffer is disconnected from the original buffer on the main thread.

Example of allocation and resize on worker
![image](https://github.com/dotnet/runtime/assets/271576/b8237084-52b1-4c2b-937c-5f1983b7b069)

Example of subsequent failure on main thread: the buffer is no longer `instanceof SharedArrayBuffer` but I think it's just disconnected.
![image](https://github.com/dotnet/runtime/assets/271576/40cf8826-f09c-4caa-a7f3-fd980d00a929)

Leads to 
```
MONO_WASM: TypeError: Failed to execute 'decode' on 'TextDecoder': The provided ArrayBufferView value must not be shared.
    at UTF8ArrayToString (http://localhost:8000/dotnet.native.js:379:22)
    at Object.UTF8ToString (http://localhost:8000/dotnet.native.js:412:15)
    at mono_wasm_trace_logger (http://localhost:8000/dotnet.runtime.js:211:32)
    at wasm_trace_logger (http://localhost:8000/dotnet.native.wasm:wasm-function[142]:0x11902)
    at callback_adapter (http://localhost:8000/dotnet.native.wasm:wasm-function[872]:0x58eec)
    at mono_tracev_inner (http://localhost:8000/dotnet.native.wasm:wasm-function[867]:0x58cfb)
    at mono_trace.13 (http://localhost:8000/dotnet.native.wasm:wasm-function[5213]:0x15b333)
    at mono_runtime_class_init_full (http://localhost:8000/dotnet.native.wasm:wasm-function[5206]:0x15ab4e)
    at do_init_vtable (http://localhost:8000/dotnet.native.wasm:wasm-function[294]:0x2793e)
    at mono_interp_exec_method (http://localhost:8000/dotnet.native.wasm:wasm-function[277]:0x1ec85)
```
on the main thread.

**Comment by pavelsavara** [comment]
Something should probably proxy the resize call to all threads https://github.com/emscripten-core/emscripten/pull/8365

**Comment by lambdageek** [comment]
Resizing on worker threads should be fine, provided the main thread is using `Module.GROWABLE_HEAP_U8` (and other views).

I don't see how proxying to the main thread will help - in that case won't the workers have the same problem?

**Comment by pavelsavara** [comment]
Our TS code doesn't use `Module.GROWABLE_HEAP_U8` yet.

**Comment by pavelsavara** [comment]
We could disable usage of TextDecoder in emscripten by `-s TEXTDECODER=0` and in our code by other means.

This seems to be related discussions
https://github.com/emscripten-core/emscripten/issues/18034
https://github.com/emscripten-core/emscripten/issues/15217

In the reported case it's not an `iframe`.
