### ISSUE TITLE
System.InvalidCastException: Arg_InvalidCastException after upgrading blazor webassembly from .net 6 to .net 7

### ISSUE THREAD

**Issue by quirynen** [dotnet/runtime#86748]
### Description

This exception only shows in production randomly. Blazor Webassembly app throws this exception randomly when an API request is made. The api calls work 7 times out of 10. Only in production release, everything works normally in development mode. Same issue as closed issue https://github.com/dotnet/runtime/issues/78864.

### Reproduction Steps

I have not been able to reproduce this problem in development environment. Stacktrace should provide some clue.

### Expected behavior

Code should work without InvalidCastException

### Actual behavior

Unhandled exception rendering component: Arg_InvalidCastException <s:Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer>
System.InvalidCastException: Arg_InvalidCastException
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Example.test.Web.Client.Helpers.WebHelper.<GetJsonAsStringAsync>d__0`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Example.test.Web.Client.Services.Settings.HardwareSettingsService.GetHardwareSettings()
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Example.test.Web.Client.ViewModels.Settings.Hardware.HardwareSettingsViewModel.InitializeHardwareSettings()
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Example.test.Web.Client.Components.Shared.Authorization.PermissionsAuthorizeView.AssignAuthorizedContent()
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Example.test.Web.Client.Components.Shared.Authorization.PermissionsAuthorizeView.OnInitializedAsync()
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at System.Object.IdSetter(Object , String )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Example.Calculation.ML.StripTest.PositionStripTest, Example.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , Dictionary`2& )
   at System.Text.Json.Serialization.JsonConverter`1[[Example.test.Web.Model.Services.ServiceResponse`1[[Example.test.Web.Model.Settings.Hardware.HardwareSettings, Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], Example.test.Web.Model, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[ServiceResponse`1](ReadOnlySpan`1 , JsonTypeInfo )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

### Regression?

I had to go back to .net6 where the same code works 100% of the time. In .net 7, api calls fails randomly

### Known Workarounds

Going back to .net 6

### Configuration

.Net Version : .net 7,
Browser : Chrome, Edge, Firefox

### Other information

/

**Comment by eiriktsarpalis** [comment]
As with https://github.com/dotnet/runtime/issues/78864, we would need some kind of reproduction to be able to take a look at this.

**Comment by quirynen** [comment]
As with https://github.com/dotnet/runtime/issues/78864 , it's almost impossible to provide a kind of reproduction as unfortunately it appears randomly, and not on a small repo project

**Comment by eiriktsarpalis** [comment]
The issue is not actionable on our side without a reproduction, unfortunately. Generally speaking it should be possible to obtain a minimal repro by slowly trimming away components from your project.
