### ISSUE TITLE
RuntimeError: Failed to create a .NET runtime (coreclr) using the  parameters {}.

### ISSUE THREAD

**Issue by jagadeswar-devarasetti-dsw** [dotnet/runtime#86750]
Hi Guys .

I am working C# and python.

I had created c# .net functions and those functions i am calling in python using pythonnet library.

using below statements : 
 
from pythonnet import load
load("coreclr")
import clr
import sys
clr.AddReference("/home/path/c#.dll")
from Test2 import Program

obj2 = Program()

Encryptionkey = "key to encrypt and decrypt"
EncryptedText = "cipher text"
data = obj2.DecryptData(EncryptedText,Encryptionkey)
print(data)

this entire build i done in windows and i got dll file . and also able to call the functions successfully in my local windows server.

now same process using same dll file I have to deploy in RHEL9.1 server

while i am running python script i getting this bellow error : 

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pythonnet/__init__.py", line 77, in _create_runtime_from_spec
    return clr_loader.get_coreclr(**params)
  File "/home/user/.local/lib/python3.9/site-packages/clr_loader/__init__.py", line 121, in get_coreclr
    dotnet_root = find_dotnet_root()
  File "/home/user/.local/lib/python3.9/site-packages/clr_loader/util/find.py", line 57, in find_dotnet_root
    raise RuntimeError("Can not determine dotnet root")
RuntimeError: Can not determine dotnet root

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jrspy/test.py", line 2, in <module>
    load("coreclr")
  File "/home/user/.local/lib/python3.9/site-packages/pythonnet/__init__.py", line 133, in load
    set_runtime(runtime, **params)
  File "/home/user/.local/lib/python3.9/site-packages/pythonnet/__init__.py", line 29, in set_runtime
    runtime = _create_runtime_from_spec(runtime, params)
  File "/home/user/.local/lib/python3.9/site-packages/pythonnet/__init__.py", line 90, in _create_runtime_from_spec
    raise RuntimeError(
RuntimeError: Failed to create a .NET runtime (coreclr) using the
                parameters {}.

yours valuable suggestions are helpful.

NOTE :
does dll and associated packages  requires to install .net ?
i have not installed .net on rhel server. 

@vitek-karas @jkotas

**Comment by jkotas** [comment]
According to the code at https://github.com/pythonnet/clr-loader/blob/79d6c6792ebc09e43d514a3ce554b32a89a2eb19/clr_loader/util/find.py#L19-L59, pythonnet either expects `dotnet` to be on the `PATH` or `DOTNET_ROOT` variable pointing to. So yes, you need to have dotnet runtime on the rhel server in order to use pythonnet.

You should be asking question like this in pythonnet repo so that they can improve their docs.

**Comment by jagadeswar-devarasetti-dsw** [comment]
Thanks @jkotas ,
