### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506) in .NET 6

### ISSUE THREAD

**Issue by Feralnex** [dotnet/runtime#86775]
### Description

Running [this project](https://github.com/Feralnex/MemoryManagementTest) in .net 6.0.16 causes Fatal error. Internal CLR error. (0x80131506) (using UnregisterFrozenSegment causes this error).

Seems that it wasn't fixed in https://github.com/dotnet/runtime/pull/83623

### Reproduction Steps

Run applicatiojn few times until error pops up.

### Expected behavior

frozen segments works as expected

### Actual behavior

Fatal Error often pops up when using FrozenSegments:

Fatal error. Internal CLR error. (0x80131506)
   at System.GC._UnregisterFrozenSegment(IntPtr)
   at Unmanaged.ObjectHandler.UnregisterFrozenSegment(IntPtr)
   at Unmanaged.Collections.Array`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Destroy(System.__Canon)
   at Unmanaged.Collections.Array`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Destroy(Boolean)
   at Unmanaged.Extensions.UnmanagedExtensions.Destroy[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, Boolean)
   at Unmanaged.Program.Main(System.String[])

**Comment by Maoni0** [comment]
it doesn't look like [#83623](https://github.com/dotnet/runtime/pull/83623) was backported to .NET 6 though (@cshung, was this supposed to be backported?). or did you mean you think this is a different issue?

**Comment by jkotas** [comment]
> UnregisterFrozenSegment 

`UnregisterFrozenSegment` has known reliability bugs. We have stopped testing it in https://github.com/dotnet/runtime/pull/86279 because of that.

`UnregisterFrozenSegment` is internal experimental API. It is not tested and supported for general use.

**Comment by martincostello** [comment]
Have recently seen this error happening seemingly randomly on Windows 11 ARM GitHub Actions runners as part of the actions/setup-dotnet action ([example](https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/30558437577/job/90925018034?pr=7573#step:3:18)):

```text
Current runner version: '2.336.0'
Runner Image Provisioner
  Hosted Compute Agent
  Version: 20260707.563
  Commit: 02667638d2b423fbc733a8e32a88b44996a3ba6e
  Build Date: 2026-07-07T19:33:50Z
  Worker ID: {b6f9993e-1226-410e-abd5-7b6c5c143708}
  Azure Region: westus2
Operating System
  Microsoft Windows 11
  10.0.26200
  Enterprise
Runner Image
  Image: windows-11-arm64
  Version: 20260719.114.1
  Included Software: https://github.com/actions/runner-images/blob/win11-arm64/20260719.114/images/windows/Windows11-Arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win11-arm64%2F20260719.114

Run actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & 'C:\a\_actions\actions\setup-dotnet\a98b56852c35b8e3190ac28c8c2271da59106c68\externals\install-dotnet.ps1' -SkipNonVersionedFiles -Runtime dotnet -Channel LTS
dotnet-install: .NET Core Runtime with version '10.0.10' is already installed.
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command & 'C:\a\_actions\actions\setup-dotnet\a98b56852c35b8e3190ac28c8c2271da59106c68\externals\install-dotnet.ps1' -SkipNonVersionedFiles -Channel 8.0
Fatal error.
Internal CLR error. (0x80131506)
Error: Failed to install dotnet, exit code: 3221225477. Fatal error.
Internal CLR error. (0x80131506)
```

**Comment by martincostello** [comment]
A more detailed occurrence ([example](https://github.com/open-telemetry/opentelemetry-dotnet/actions/runs/30616245237/job/91110047206#step:3:24)):

```text
Fatal error.
Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny_NoCacheLookup(Void*, System.Object)
   at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void*, System.Object)
   at Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)
   at Microsoft.PowerShell.TaskbarJumpList+<>c.<CreateRunAsAdministratorJumpList>b__0_0()
   at System.Threading.Thread+StartHelper.Callback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
Error: Failed to install dotnet, exit code: 3221225477. Fatal error.
Internal CLR error. (0x80131506)
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny_NoCacheLookup(Void*, System.Object)
   at System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(Void*, System.Object)
   at Microsoft.PowerShell.TaskbarJumpList.CreateElevatedEntry(System.String)
   at Microsoft.PowerShell.TaskbarJumpList+<>c.<CreateRunAsAdministratorJumpList>b__0_0()
   at System.Threading.Thread+StartHelper.Callback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

**Comment by jkotas** [comment]
@martincostello "Internal CLR error. (0x80131506)" can have many different causes. This issue is about UnregisterFrozenSegment causing this error. I have updated the title to make it clear. The callstack you have shared shows that there is no UnregisterFrozenSegment involved. Could you please open a new issue?

**Comment by martincostello** [comment]
> Could you please open a new issue?

https://github.com/dotnet/runtime/issues/131636

**Comment by MichalPetryka** [comment]
> `UnregisterFrozenSegment` is internal experimental API. It is not tested and supported for general use.

Should this issue be just closed then?
