### ISSUE TITLE
AccessViolationException in ILLink in .NET 7

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#86807]
We have a integration test that builds 100 class libraries for use in an Android app. This works most of the time, but sometimes on Windows we hit:

```
    Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at Mono.Cecil.MetadataReader.RangesSize(Mono.Cecil.Range[])
       at Mono.Cecil.MetadataReader.ReadCustomAttributes(Mono.Cecil.ICustomAttributeProvider)
       at Mono.Cecil.Mixin+<>c.<GetCustomAttributes>b__13_0(Mono.Cecil.ICustomAttributeProvider, Mono.Cecil.MetadataReader)
       at Mono.Cecil.ModuleDefinition.Read[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.__Canon, System.Func`3<System.__Canon,Mono.Cecil.MetadataReader,System.__Canon>)
       at Mono.Cecil.Mixin.GetCustomAttributes(Mono.Cecil.ICustomAttributeProvider, Mono.Collections.Generic.Collection`1<Mono.Cecil.CustomAttribute> ByRef, Mono.Cecil.ModuleDefinition)
       at Mono.Cecil.MethodDefinition.get_CustomAttributes()
       at Microsoft.Android.Sdk.ILLink.ApplyPreserveAttribute.GetPreserveAttributes(Mono.Cecil.ICustomAttributeProvider)
       at Microsoft.Android.Sdk.ILLink.ApplyPreserveAttribute.MarkMethodIfPreserved(Mono.Cecil.MethodDefinition)
       at Microsoft.Android.Sdk.ILLink.ApplyPreserveAttribute.ProcessMethod(Mono.Cecil.MethodDefinition)
       at Mono.Linker.Steps.MarkSubStepsDispatcher.DispatchMethod(Mono.Cecil.MethodDefinition)
       at Mono.Linker.Steps.MarkSubStepsDispatcher.BrowseTypes(Mono.Collections.Generic.Collection`1<Mono.Cecil.TypeDefinition>)
       at Mono.Linker.Steps.MarkSubStepsDispatcher.BrowseTypes(Mono.Collections.Generic.Collection`1<Mono.Cecil.TypeDefinition>)
       at Mono.Linker.Steps.MarkSubStepsDispatcher.BrowseAssembly(Mono.Cecil.AssemblyDefinition)
       at Mono.Linker.Steps.MarkSubStepsDispatcher.<Initialize>b__5_0(Mono.Cecil.AssemblyDefinition)
       at Mono.Linker.Steps.MarkStep.MarkAssembly(Mono.Cecil.AssemblyDefinition, Mono.Linker.DependencyInfo)
       at Mono.Linker.Steps.MarkStep.MarkModule(Mono.Cecil.ModuleDefinition, Mono.Linker.DependencyInfo)
       at Mono.Linker.Steps.MarkStep.MarkType(Mono.Cecil.TypeReference, Mono.Linker.DependencyInfo, System.Nullable`1<Mono.Linker.MessageOrigin>)
       at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
       at Mono.Linker.Steps.MarkStep.Initialize()
       at Mono.Linker.Steps.MarkStep.Process(Mono.Linker.LinkContext)
       at Mono.Linker.Pipeline.ProcessStep(Mono.Linker.LinkContext, Mono.Linker.Steps.IStep)
       at Mono.Linker.Pipeline.Process(Mono.Linker.LinkContext)
       at Mono.Linker.Driver.Run(Mono.Linker.ILogger)
       at Mono.Linker.Driver.Main(System.String[])
    Errors
        C:\a\_work\1\s\bin\Release\dotnet\sdk\7.0.100-rc.1.22425.9\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(133,5): error MSB6006: "dotnet.exe" exited with code 57005. [C:\a\_work\1\a\TestRelease\08-31_14.34.17\temp\BuildAMassiveApp\App1\App1.csproj]
    OutputProperties
        _ILLinkExitCode = 57005
```

I believe this started happening here:
* https://github.com/xamarin/xamarin-android/pull/7255
* https://github.com/dotnet/linker/compare/f09bacf...6252a21

This Maestro bump, I believe, was the first time we ever saw something like this.

Logs: [accessviolation.zip](https://github.com/dotnet/linker/files/9463038/accessviolation.zip)

Let me know if you need the entire project, I believe the solution with 100+ class libraries is too large to attach here.

/fyi @sbomer

**Comment by marek-safar** [comment]
@vitek-karas should we remove server forcing GC on desktop? If I recall the gain was not very significant and it seems to make illink unstable.

**Comment by MichalStrehovsky** [comment]
> @vitek-karas should we remove server forcing GC on desktop? If I recall the gain was not very significant and it seems to make illink unstable.

It was 20%: https://github.com/dotnet/linker/pull/1493

We should move this to the VM area. Server GC is a supported configuration option and our flagship appmodels (ASP.NET) use it by default.

Is this seen only on 7.0? Or is the workaround also used in 8.0 and we don't have data?

**Comment by jonathanpeppers** [comment]
It passed for us three times in a row using .NET 8 (main/preview 5 builds). I took out the workaround, and we'll see if this happens again.

**Comment by mangod9** [comment]
@jonathanpeppers hoping this is ok to close now?
