### ISSUE TITLE
SQL Impersonation run failed with System.IO.FileLoadExceptions at .NET  single file app

### ISSUE THREAD

**Issue by WD1993** [dotnet/runtime#87132]
### Description

SQL Impersonation run failed with System.IO.FileLoadExceptions at .NET self-contained app.

System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
---> System.IO.FileLoadException:
File name: 'System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
--- End of inner exception stack trace ---
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection) at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions) at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource1 retry, SqlConnectionOverrides overrides)
at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
at Microsoft.Data.SqlClient.SqlConnection.Open()
at Microsoft.SqlServer.Management.PermissionControl.PermissionControlManager.<>c__DisplayClass21_0.b__0()
at System.Security.Principal.WindowsIdentity.<>c__DisplayClass73_0.b__0(Object )
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
at Microsoft.SqlServer.Management.IaaSUtility.ImpersonationUtility.Run(Int32 processId, Action callback)

Checked with , the dlls are packed inside single file app. 
![image](https://github.com/dotnet/runtime/assets/45744691/c6f8e729-5919-459a-87cc-98be053160c8)

### Reproduction Steps

 ImpersonationUtility.Run(sqlServiceProcessId,
                        () =>
                        {
                            using (SqlConnection sqlConnection = new SqlConnection(connection.ToString()))
                            {
                                sqlConnection.Open();

                                // get the login from the SQL server to avoid case sensitivity issue
                                string currentLoginName = null;

                                using (SqlCommand command = new SqlCommand(CheckIfLoginExists, sqlConnection))
                                {
                                    command.Parameters.AddWithValue("@accountName", accountName);
                                    using (SqlDataReader reader = command.ExecuteReader())
                                    {
                                        if (reader.HasRows && reader.Read())
                                        {
                                            // there will be only one login at server-level
                                            currentLoginName = (string)reader[0];
                                        }
                                    }
                                }

                                if (!string.IsNullOrEmpty(currentLoginName))
                                {
                                    // login exists and need to be removed
                                    using (SqlCommand dropcommand = new SqlCommand(DropSqlLogin, sqlConnection))
                                    {
                                        dropcommand.Parameters.AddWithValue("@accountName", currentLoginName);
                                        dropcommand.ExecuteNonQuery();
                                    }
                                    Logger.LogInfo($"Successfully removed {currentLoginName} from {sqlServiceName}");
                                }
                                else
                                {
                                    Logger.LogInfo($"Skipping removal of {accountName} from {sqlServiceName} as login doesn't exist.");
                                }
                            }
                        });

### Expected behavior

connection should be setup

### Actual behavior

fileloadexception raiesd

### Known Workarounds

Cancel the single file publish makes issue gone, however it might not be a scalable solution for us.

### Configuration

Microsoft.Data.SqlClient version: (5.0.1)
.NET target: (.NET7)
SQL Server version: (SQL Server 2017,SQL Server 2019)
Operating system: (WS2016 WS2019)

**Comment by Wraith2** [comment]
Reading the error message it looks like `System.Configuration.ConfigurationManager` has been trimmed away. See if there's a way to force it to be kept.
Also consider moving to https://github.com/dotnet/SqlClient which will be updated with trimming support where the System version won't because it is in maintenance mode.

**Comment by WD1993** [comment]
Hi @Wraith2  
1. we are in MDS 5.0.1 
2. we checked exe file, System.Configuration.ConfigurationManager is there
