### ISSUE TITLE
[jitstress] JIT/opt/Devirtualization/Comparer_get_Default failing with AV

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#87258]
Pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=299370&view=results
Fails in multiple configurations. Example log from win-x64: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-9716df531a2a4296a9/JIT.opt/1/console.2c10fd9e.log?helixlogtype=result

```scala
06:04:08.292 Running test: JIT/opt/Devirtualization/Comparer_get_Default/Comparer_get_Default.dll
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Program.GetHashCodeTests()
   at Program.TestEntryPoint()
   at Program.<<Main>$>g__TestExecutor32|0_33(System.IO.StreamWriter, System.IO.StreamWriter, <>c__DisplayClass0_0 ByRef)
   at Program.<Main>$(System.String[])
App Exit Code: -1073741819
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
```

Last run before CI issues that was green is c81e83ab01fb3aed44de34e5aff659d28e6c91f4. So the JIT commits are
```scala
commit 8685cacd46a484e2e861b44916e4fde09c781204
Author: Tanner Gooding <tagoo@outlook.com>

    Improve codegen for AVX-512 comparisons and general handling of `TYP_MASK` (#87089)

commit eb09ba9d222463daf604e7a4b7cdf18732afdbfd
Author: Tanner Gooding <tagoo@outlook.com>

    Fix handling of CreateScalarUnsafe for embedded broadcast (#87134)

commit 10222f94e5d89b19959117dd9e5b8576ef63f878
Author: Jakob Botsch Nielsen <Jakob.botsch.nielsen@gmail.com>

    JIT: Clean up BB successor iteration (#86839)

commit f026bb09aa572d51945ba9204d681923ae89a60a
Author: Dong-Heon Jung <clamp03@gmail.com>

    [RISC-V][JIT] Fix arithmetics (#86996)

commit af1262cb6115a0b374dee7fb96cb9185bd09ac53
Author: Tanner Gooding <tagoo@outlook.com>

    Allow the user to control the MaxVectorTBitWidth (#85551)

commit 404aede4505eb7197125fa645bcf6f2fb70da139
Author: Egor Bogatov <egorbo@gmail.com>

    Fold obj.GetType to a constant (#87101)

commit 9f8f6531b72c44da09d5ffcadf638f11cf51d227
Author: Mark Plesko <markples@microsoft.com>

    Save 260k in InitValueNumStoreStatics (#85945)

commit 3bd33dd53f0490e1e188d13f4c8a553aae7b384a
Author: Aaron Robinson <arobins@microsoft.com>

    Remove legacy stacksampler logic (#87076)

commit 1e029d0768967255b3f866102aba10671fd562e5
Author: Ruihan-Yin <107431934+Ruihan-Yin@users.noreply.github.com>

    Enable EVEX feature: embedded broadcast for Vector128/256/512.Add() in limited cases (#84821)

commit 6cb44ff34d19289e0eb7373d8ae6872f2f0e65a0
Author: Dong-Heon Jung <clamp03@gmail.com>

    [RISC-V][JIT] Implement genCodeForIncSaturate (#86891)
```

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
Looks like 404aede4505eb7197125fa645bcf6f2fb70da139 is the culprit, cc @EgorBo
