### ISSUE TITLE
outerloop crossgen2 access violation in jit.opt workitem 

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#87305]
I noticed it in [my PR](https://github.com/dotnet/runtime/pull/87261) and issue [#87268](https://github.com/dotnet/runtime/issues/87268) was linked to it. but that issue seems to only be on linux. so I just want to make sure the issue on windows (both arm64 and x64) is recorded. this is the callstack

```
" "dotnet" "C:\h\w\AAA608BA\p\crossgen2\crossgen2.dll" @"C:\h\w\AAA608BA\w\AA1B09B4\e\JIT\opt\JIT.opt\Comparer_get_Default.dll.rsp"   -r:C:\h\w\AAA608BA\w\AA1B09B4\e\JIT\opt\JIT.opt\IL-CG2\*.dll"
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
--------------------------------
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
   at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
   at ILCompiler.ReadyToRunCodegenCompilation+<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore`1<ILCompiler.DependencyAnalysis.NodeFactory>, Int32)
   at ILCompiler.ReadyToRunCodegenCompilation+<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32)
   at ILCompiler.ReadyToRunCodegenCompilation+<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileMethodList|2(System.Collections.Generic.IEnumerable`1<ILCompiler.DependencyAnalysisFramework.DependencyNodeCore`1<ILCompiler.DependencyAnalysis.NodeFactory>>)
   at ILCompiler.ReadyToRunCodegenCompilation.ComputeDependencyNodeDependencies(System.Collections.Generic.List`1<ILCompiler.DependencyAnalysisFramework.DependencyNodeCore`1<ILCompiler.DependencyAnalysis.NodeFactory>>)
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2[[ILCompiler.DependencyAnalysisFramework.NoLogStrategy`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILCompiler.DependencyAnalysisFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ComputeMarkedNodes()
   at ILCompiler.ReadyToRunCodegenCompilation.Compile(System.String)
   at ILCompiler.Program.RunSingleCompilation(System.Collections.Generic.Dictionary`2<System.String,System.String>, ILCompiler.InstructionSetSupport, System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.HashSet`1<Internal.TypeSystem.ModuleDesc>, ILCompiler.ReadyToRunCompilerContext)
   at ILCompiler.Program.Run()
   at ILCompiler.Crossgen2RootCommand+<>c__DisplayClass190_0.<.ctor>b__0(System.CommandLine.Invocation.InvocationContext)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(System.CommandLine.Invocation.InvocationContext)
   at System.CommandLine.Invocation.InvocationPipeline+<>c__DisplayClass4_0+<<BuildInvocationChain>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.CommandLine.Invocation.InvocationPipeline+<>c__DisplayClass4_0+<<BuildInvocationChain>b__0>d, System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<BuildInvocationChain>b__0>d ByRef)
   at System.CommandLine.Invocation.InvocationPipeline+<>c__DisplayClass4_0.<BuildInvocationChain>b__0(System.CommandLine.Invocation.InvocationContext, System.Func`2<System.CommandLine.Invocation.InvocationContext,System.Threading.Tasks.Task>)
   at System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass16_0+<<UseParseErrorReporting>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass16_0+<<UseParseErrorReporting>b__0>d, System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<UseParseErrorReporting>b__0>d ByRef)
   at System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass16_0.<UseParseErrorReporting>b__0(System.CommandLine.Invocation.InvocationContext, System.Func`2<System.CommandLine.Invocation.InvocationContext,System.Threading.Tasks.Task>)
   at System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass11_0+<<UseHelp>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass11_0+<<UseHelp>b__0>d, System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<UseHelp>b__0>d ByRef)
   at System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass11_0.<UseHelp>b__0(System.CommandLine.Invocation.InvocationContext, System.Func`2<System.CommandLine.Invocation.InvocationContext,System.Threading.Tasks.Task>)
   at System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass22_0+<<UseVersionOption>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass22_0+<<UseVersionOption>b__0>d, System.CommandLine, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<UseVersionOption>b__0>d ByRef)
   at System.CommandLine.CommandLineBuilderExtensions+<>c__DisplayClass22_0.<UseVersionOption>b__0(System.CommandLine.Invocation.InvocationContext, System.Func`2<System.CommandLine.Invocation.InvocationContext,System.Threading.Tasks.Task>)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(System.CommandLine.Invocation.InvocationContext)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(System.CommandLine.IConsole)
   at ILCompiler.Program.Main(System.String[])
```

hit this in my PR here: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-87261-merge-d6dfd312c566416db8/JIT.opt/1/console.75b77cb9.log?helixlogtype=result

and https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-a4edf2bb864c4721ae/JIT.opt/1/console.ddbf9d49.log?helixlogtype=result is on windows x64 (unfortunately I didn't record which PR this was from and now I don't know how to find out)

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-9c5874ba70d4462f83/JIT.opt/1/console.a232e75e.log?helixlogtype=result
from this PR: #20230607.4 • Fix reading runtime settings early in startup (#87205)

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-949b937e91954c6186/JIT.opt/1/console.24625fb6.log?helixlogtype=result
from this PR: #20230608.2 • Setup for runs with physical promotion. (#87227)

**Comment by jakobbotsch** [comment]
Dup of #87258?

**Comment by Maoni0** [comment]
maybe? it's hard to tell when the issue I observed started to happened - it's basically useless to see this workitem's history because it includes any issue it hit (which could be anything). I had to look at each one individually to see what error it actually hit.
