### ISSUE TITLE
[browser][debugger][MT] PropertiesSortedByProtectionLevel

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#87314]
```
[xUnit.net 00:09:37.01]     DebuggerTests.GetPropertiesTests.PropertiesSortedByProtectionLevel(expectedPublicInternalAndProtected: [["BaseBase_PropertyForHidingWithField"] = [[[...]], [[...]], [[...]]], ["Base_PropertyForOverridingWithProperty"] = [[[...]], [[...]], [[...]]], ["BaseBase_PropertyForVHO"] = [[[...]], [[...]], [[...]]], ["BaseBase_PropertyForVOH"] = [[[...]], [[...]], [[...]]], ["BaseBase_AutoPropertyForVHO"] = [[[...]], [[...]]], ...], expectedPriv: [["BaseBase_FieldForHidingWithAutoProperty"] = [[[...]], [[...]]], ["S_BaseBase_FieldForHidingWithAutoProperty"] = [[[...]], [[...]], [[...]]], ["BaseBase_FieldForHidingWithField"] = [[[...]], [[...]], [[...]]], ["BaseBase_AutoPropertyForHidingWithProperty (BaseCl"...] = [[[...]], [[...]], [[...]]], ["BaseBase_PropertyForHidingWithAutoProperty"] = [[[...]], [[...]]], ...], entryMethod: "DerivedClass2") [FAIL]
Detected a container, disabling sandboxing for debugger tests.
  Failed DebuggerTests.GetPropertiesTests.PropertiesSortedByProtectionLevel(expectedPublicInternalAndProtected: [["BaseBase_PropertyForHidingWithField"] = [[[...]], [[...]], [[...]]], ["Base_PropertyForOverridingWithProperty"] = [[[...]], [[...]], [[...]]], ["BaseBase_PropertyForVHO"] = [[[...]], [[...]], [[...]]], ["BaseBase_PropertyForVOH"] = [[[...]], [[...]], [[...]]], ["BaseBase_AutoPropertyForVHO"] = [[[...]], [[...]]], ...], expectedPriv: [["BaseBase_FieldForHidingWithAutoProperty"] = [[[...]], [[...]]], ["S_BaseBase_FieldForHidingWithAutoProperty"] = [[[...]], [[...]], [[...]]], ["BaseBase_FieldForHidingWithField"] = [[[...]], [[...]], [[...]]], ["BaseBase_AutoPropertyForHidingWithProperty (BaseCl"...] = [[[...]], [[...]], [[...]]], ["BaseBase_PropertyForHidingWithAutoProperty"] = [[[...]], [[...]]], ...], entryMethod: "DerivedClass2") [1 ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, String urlToInspect, TimeSpan span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 377
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 173
  Standard Output Messages:
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Information: [testId: 71] New test request for test id 71
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: [71] Starting /root/helix/work/correlation/chrome-linux/chrome with --no-sandbox --headless --disable-gpu --lang=en-US --incognito --remote-debugging-port=0 about:blank
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: [testId: 70] TestHarnessStartup done
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 70
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: [testId: 71] browser-stderr [0608/200427.680681:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: [testId: 71] browser-stderr 
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: [testId: 71] browser-stderr DevTools listening on ws://127.0.0.1:36729/devtools/browser/0d44c5e7-cdda-4db2-bf03-f5c7d81c1e35
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Debug: [testId: 71] browser-stderr [0608/200427.700076:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
 | [2023-06-08T20:04:27] DebuggerTests.TestHarnessProxy Information: [testId: 71] launching proxy for ws://127.0.0.1:36729/devtools/page/8273F15E037C1875724AABBC42B74AA3
 | [2023-06-08T20:04:27] Inspector-71 Information: waiting for the runtime to be ready
 | [2023-06-08T20:04:28] Inspector-71 Error: Unable to find command msg-AC4CE5FE9ACDC970A595B9B58E567B76:::12
 | [2023-06-08T20:04:28] Inspector-71 Error: _isFailingWithException. System.NullReferenceException: Object reference not set to an instance of an object.
 |                                              at DebuggerTests.InspectorClient.HandleMessage(String msg, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 45
 |                                              at Microsoft.WebAssembly.Diagnostics.RunLoop.RunActualAsync(CancellationTokenSource x) in /_/src/mono/wasm/debugger/BrowserDebugProxy/Common/RunLoop.cs:line 142
 |                                              at Microsoft.WebAssembly.Diagnostics.RunLoop.<>c__DisplayClass20_0.<<RunAsync>b__0>d.MoveNext() in /_/src/mono/wasm/debugger/BrowserDebugProxy/Common/RunLoop.cs:line 54
 |                                           --- End of stack trace from previous location ---
 |                                              at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
 |                                              at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
 |                                           --- End of stack trace from previous location ---
 |                                              at DebuggerTests.Inspector.<OpenSessionAsync>b__40_1() in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 362.
```
[build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=300315&view=logs&jobId=2112d60c-a661-5638-18dd-f51355a8b038)
[Log ](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-86759-merge-33368a48c0f84a42ac/chrome-DebuggerTests.GetPropertiesTests/1/console.2ae17aa5.log?helixlogtype=result)

**Comment by ilonatommy** [comment]
Most probably fixed between ccd2c5e27bc74166380d0ffa94cac19b491ced30 and fb7f47a3040e98c1b514dfae3b425f2011334005, cannot reproduce on the PR's branch. Main does not fail either.
