### ISSUE TITLE
[browser][debugger][MT] CallFunctionOnTests.RunOnInvalidCfoId

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#87315]
```
[xUnit.net 00:08:09.53]     DebuggerTests.CallFunctionOnTests.RunOnInvalidCfoId(eval_fn: "negative_cfo_test ();", bp_loc: "/other.js", line: 64, col: 1, use_cfo: False) [FAIL]
Detected a container, disabling sandboxing for debugger tests.
  Failed DebuggerTests.CallFunctionOnTests.RunOnInvalidCfoId(eval_fn: "negative_cfo_test ();", bp_loc: "/other.js", line: 64, col: 1, use_cfo: False) [1 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (Index was outside the bounds of the array.)
---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
  Stack Trace:
     at DebuggerTests.Inspector.OpenSessionAsync(Func`3 getInitCmds, String urlToInspect, TimeSpan span) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 377
   at DebuggerTests.DebuggerTestBase.InitializeAsync() in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 173
----- Inner Stack Trace -----
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at DebuggerTests.InspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 98
   at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 219
  Standard Output Messages:

...

[2023-06-08T20:02:59] Inspector-67 Error: _isFailingWithException. System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 |                                            ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
 |                                              at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
 |                                              at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
 |                                              at DebuggerTests.InspectorClient.SendCommand(SessionId sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs:line 98
 |                                              at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 219
 |                                              --- End of inner exception stack trace ---
 |                                              at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 220
 |                                              at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 219
 |                                              at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 220
 |                                              at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 223
 |                                              at DebuggerTests.Inspector.OnMessage(String sessionId, String method, JObject args, CancellationToken token) in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 221
 |                                              at DebuggerTests.Inspector.<OpenSessionAsync>b__40_1() in /_/src/mono/wasm/debugger/DebuggerTestSuite/Inspector.cs:line 362.
```

[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=300315&view=logs&jobId=2112d60c-a661-5638-18dd-f51355a8b038)
[log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-86759-merge-33368a48c0f84a42ac/chrome-DebuggerTests.CallFunctionOnTests/1/console.8a5f1d20.log?helixlogtype=result)

**Comment by mdh1418** [comment]
Seeing the same with `DebuggerTests.MonoJsTests.RaiseDebugEventTraceTest` on  #84191 for [build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=300962&view=logs&j=33b44b3f-656e-594a-4626-7b6774eb48dc&t=c78b85cf-7ee5-529a-7a89-9f3ff870ebc2)
[log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-84191-merge-5de6a2c2b6df46aeb7/chrome-DebuggerTests.MonoJsTests/1/console.267044cd.log?helixlogtype=result)

**Comment by ilonatommy** [comment]
Reason: "[A Dictionary<TKey,TValue>.ValueCollection can support multiple readers concurrently, as long as the collection is not modified.](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.valuecollection?view=net-7.0#thread-safety)".
`pending_cmds` is getting modified from different threads which sometimes causes the issue:
https://github.com/dotnet/runtime/blob/7b25983451968a7edfeba78a3a16c050dba12a4f/src/mono/wasm/debugger/DebuggerTestSuite/InspectorClient.cs#L98
