### ISSUE TITLE
System.Net.Mail.Functional.Tests work item crash with Mono on Linux x64

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#87327]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=300749
Build error leg or test failing: System.Net.Mail.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/86668

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "mono_threads_platform_exit () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Provided build not found. Provide a valid build in the "**Build: :mag_right:**" line.
**Validation performed at:** 7/25/2023 2:39:32 PM UTC

**Comment by danmoseley** [comment]
```
Thread 7 (Thread 0x7f7051388700 (LWP 30)):
#0  0x00007f705b7b40ca in __waitpid (pid=31, stat_loc=0x7f7051385e80, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f705afa5012 in mono_dump_native_crash_info () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#2  0x00007f705af4e62e in mono_handle_native_crash () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#3  0x00007f705aeb5e96 in mono_sigsegv_signal_handler_debug () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#4  <signal handler called>
#5  0x00007f705b7d6d3d in elf_machine_rela (skip_ifunc=0, reloc_addr_arg=0x7f7050c2a440, version=0x30, sym=0x7f7050969d70, reloc=0x7f70509c45a8, map=0x7f704018d280) at ../sysdeps/x86_64/dl-machine.h:308
#6  elf_dynamic_do_Rela (skip_ifunc=0, lazy=<optimized out>, nrelative=<optimized out>, relsize=<optimized out>, reladdr=<optimized out>, map=0x7f704018d280) at do-rel.h:137
#7  _dl_relocate_object (scope=<optimized out>, reloc_mode=reloc_mode@entry=0, consider_profiling=<optimized out>, consider_profiling@entry=0) at dl-reloc.c:258
#8  0x00007f705b7de1ae in dl_open_worker (a=a@entry=0x7f7051387b50) at dl-open.c:377
#9  0x00007f705b3f08cf in __GI__dl_catch_exception (exception=exception@entry=0x7f7051387b30, operate=operate@entry=0x7f705b7ddf70 <dl_open_worker>, args=args@entry=0x7f7051387b50) at dl-error-skeleton.c:196
#10 0x00007f705b7ddbca in _dl_open (file=0x7f705b7b7a0f "libgcc_s.so.1", mode=-2147483646, caller_dlopen=0x7f705b7b4c7b <pthread_cancel_init+43>, nsid=<optimized out>, argc=18, argv=0x7ffdf8b63838, env=0x7ffdf8b638d0) at dl-open.c:599
#11 0x00007f705b3efe0d in do_dlopen (ptr=ptr@entry=0x7f7051387d90) at dl-libc.c:96
#12 0x00007f705b3f08cf in __GI__dl_catch_exception (exception=exception@entry=0x7f7051387d10, operate=operate@entry=0x7f705b3efdd0 <do_dlopen>, args=args@entry=0x7f7051387d90) at dl-error-skeleton.c:196
#13 0x00007f705b3f095f in __GI__dl_catch_error (objname=objname@entry=0x7f7051387d68, errstring=errstring@entry=0x7f7051387d70, mallocedp=mallocedp@entry=0x7f7051387d67, operate=operate@entry=0x7f705b3efdd0 <do_dlopen>, args=args@entry=0x7f7051387d90) at dl-error-skeleton.c:215
#14 0x00007f705b3efee7 in dlerror_run (operate=operate@entry=0x7f705b3efdd0 <do_dlopen>, args=args@entry=0x7f7051387d90) at dl-libc.c:46
#15 0x00007f705b3eff76 in __GI___libc_dlopen_mode (name=name@entry=0x7f705b7b7a0f "libgcc_s.so.1", mode=mode@entry=-2147483646) at dl-libc.c:195
#16 0x00007f705b7b4c7b in pthread_cancel_init () at ../sysdeps/nptl/unwind-forcedunwind.c:53
#17 0x00007f705b7b4e94 in _Unwind_ForcedUnwind (exc=0x7f7051388d70, stop=0x7f705b7b2f30 <unwind_stop>, stop_argument=0x7f7051387f10) at ../sysdeps/nptl/unwind-forcedunwind.c:127
#18 0x00007f705b7b30a0 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:121
#19 0x00007f705b7ab1f5 in __do_cancel () at pthreadP.h:305
#20 __pthread_exit (value=<optimized out>) at pthread_exit.c:28
#21 0x00007f705b05b356 in mono_threads_platform_exit () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#22 0x00007f705b0e4ba7 in start_wrapper () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#23 0x00007f705b7a9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#24 0x00007f705b3b506f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f705168a700 (LWP 29)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007f705b7ac7d1 in __GI___pthread_mutex_lock (mutex=0x7f705b7f3968 <_rtld_global+2312>) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007f705b7ddb66 in _dl_open (file=0x7f705b7b7a0f "libgcc_s.so.1", mode=-2147483646, caller_dlopen=0x7f705b7b4c7b <pthread_cancel_init+43>, nsid=-2, argc=18, argv=0x7ffdf8b63838, env=0x7ffdf8b638d0) at dl-open.c:548
#3  0x00007f705b3efe0d in do_dlopen (ptr=ptr@entry=0x7f7051689d90) at dl-libc.c:96
#4  0x00007f705b3f08cf in __GI__dl_catch_exception (exception=exception@entry=0x7f7051689d10, operate=operate@entry=0x7f705b3efdd0 <do_dlopen>, args=args@entry=0x7f7051689d90) at dl-error-skeleton.c:196
#5  0x00007f705b3f095f in __GI__dl_catch_error (objname=objname@entry=0x7f7051689d68, errstring=errstring@entry=0x7f7051689d70, mallocedp=mallocedp@entry=0x7f7051689d67, operate=operate@entry=0x7f705b3efdd0 <do_dlopen>, args=args@entry=0x7f7051689d90) at dl-error-skeleton.c:215
#6  0x00007f705b3efee7 in dlerror_run (operate=operate@entry=0x7f705b3efdd0 <do_dlopen>, args=args@entry=0x7f7051689d90) at dl-libc.c:46
#7  0x00007f705b3eff76 in __GI___libc_dlopen_mode (name=name@entry=0x7f705b7b7a0f "libgcc_s.so.1", mode=mode@entry=-2147483646) at dl-libc.c:195
#8  0x00007f705b7b4c7b in pthread_cancel_init () at ../sysdeps/nptl/unwind-forcedunwind.c:53
#9  0x00007f705b7b4e94 in _Unwind_ForcedUnwind (exc=0x7f705168ad70, stop=0x7f705b7b2f30 <unwind_stop>, stop_argument=0x7f7051689f10) at ../sysdeps/nptl/unwind-forcedunwind.c:127
#10 0x00007f705b7b30a0 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:121
#11 0x00007f705b7ab1f5 in __do_cancel () at pthreadP.h:305
#12 __pthread_exit (value=<optimized out>) at pthread_exit.c:28
#13 0x00007f705b05b356 in mono_threads_platform_exit () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#14 0x00007f705b0e4ba7 in start_wrapper () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#15 0x00007f705b7a9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#16 0x00007f705b3b506f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f7051724700 (LWP 28)):
#0  __libc_read (nbytes=1, buf=0x7f7051723ee7, fd=7) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=7, buf=0x7f7051723ee7, nbytes=1) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007f70582e5146 in SignalHandlerLoop () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0//libSystem.Native.so
#3  0x00007f705b7a9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#4  0x00007f705b3b506f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f70584ec700 (LWP 27)):
#0  0x00007f705b7ab495 in __GI___pthread_timedjoin_ex (threadid=140120375723776, thread_return=0x7f70584ebd60, abstime=0x0, block=<optimized out>) at pthread_join_common.c:89
#1  0x00007f705b05b539 in mono_native_thread_join () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#2  0x00007f705b0e40c0 in mono_threads_join_threads () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#3  0x00007f705b10b58b in finalizer_thread () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#4  0x00007f705b0e4aa9 in start_wrapper () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#5  0x00007f705b7a9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f705b3b506f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f70587ee700 (LWP 26)):
#0  0x00007f705b3aa6f9 in __GI___poll (fds=0x7f7054002710, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f705b0313be in ds_ipc_poll () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#2  0x00007f705b02e7e8 in ds_ipc_stream_factory_get_next_available_stream () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#3  0x00007f705b02cdcf in server_thread () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#4  0x00007f705b030811 in ep_rt_thread_mono_start_func () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#5  0x00007f705b7a9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f705b3b506f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f705a3ff700 (LWP 25)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7f705b19d698 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f705b19d648 <lock>, cond=0x7f705b19d670 <work_cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f705b19d670 <work_cond>, mutex=0x7f705b19d648 <lock>) at pthread_cond_wait.c:655
#3  0x00007f705b172723 in thread_func () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#4  0x00007f705b7a9fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#5  0x00007f705b3b506f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f705b2b7740 (LWP 24)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:103
#1  0x00007f705b7ac7d1 in __GI___pthread_mutex_lock (mutex=0x7f705b7f3968 <_rtld_global+2312>) at ../nptl/pthread_mutex_lock.c:115
#2  0x00007f705b7ddb66 in _dl_open (file=0x5620db346310 "/root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/System.Diagnostics.Debug.dll.so", mode=-2147483647, caller_dlopen=0x7f705b04cc0a <mono_dl_open_full+122>, nsid=-2, argc=18, argv=0x7ffdf8b63838, env=0x7ffdf8b638d0) at dl-open.c:548
#3  0x00007f705b79e256 in dlopen_doit (a=a@entry=0x7ffdf8b608a0) at dlopen.c:66
#4  0x00007f705b3f08cf in __GI__dl_catch_exception (exception=exception@entry=0x7ffdf8b60840, operate=operate@entry=0x7f705b79e200 <dlopen_doit>, args=args@entry=0x7ffdf8b608a0) at dl-error-skeleton.c:196
#5  0x00007f705b3f095f in __GI__dl_catch_error (objname=objname@entry=0x5620da1b70f0, errstring=errstring@entry=0x5620da1b70f8, mallocedp=mallocedp@entry=0x5620da1b70e8, operate=operate@entry=0x7f705b79e200 <dlopen_doit>, args=args@entry=0x7ffdf8b608a0) at dl-error-skeleton.c:215
#6  0x00007f705b79e995 in _dlerror_run (operate=operate@entry=0x7f705b79e200 <dlopen_doit>, args=args@entry=0x7ffdf8b608a0) at dlerror.c:170
#7  0x00007f705b79e2e6 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#8  0x00007f705b04cc0a in mono_dl_open_full () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#9  0x00007f705af349d9 in load_aot_module () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#10 0x00007f705b065408 in mono_assembly_request_load_from () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#11 0x00007f705b064eca in mono_assembly_request_open () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#12 0x00007f705af841ae in mono_core_preload_hook () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#13 0x00007f705b067423 in invoke_assembly_preload_hook () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#14 0x00007f705b064185 in mono_assembly_request_byname () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#15 0x00007f705b063aa2 in mono_assembly_load_reference () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#16 0x00007f705b0689a8 in mono_class_from_typeref_checked () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#17 0x00007f705b0a9476 in method_from_memberref () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#18 0x00007f705b0a787e in mono_get_method_checked () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#19 0x00007f705b0ffab4 in mono_custom_attrs_from_index_checked () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#20 0x00007f705afe1027 in interp_inline_method () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#21 0x00007f705afdb740 in interp_inline_newobj () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#22 0x00007f705afcbeea in generate_code () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#23 0x00007f705afe10c9 in interp_inline_method () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#24 0x00007f705afd8c81 in interp_transform_call () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#25 0x00007f705afc83ff in generate_code () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#26 0x00007f705afcf722 in generate () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#27 0x00007f705afcf1fd in mono_interp_transform_method () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#28 0x00007f705afe37c3 in tier_up_method () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#29 0x00007f705afe38cd in mono_interp_tier_up_frame_patchpoint () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#30 0x00007f705afb4c05 in mono_interp_exec_method () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#31 0x00007f705afa6886 in interp_runtime_invoke () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#32 0x00007f705b0cc8d7 in mono_runtime_invoke_checked () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#33 0x00007f705b0d3548 in mono_runtime_exec_main_checked () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#34 0x00007f705af0f2af in mono_jit_exec () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#35 0x00007f705af11ae2 in mono_main () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#36 0x00007f705af83e67 in monovm_execute_assembly () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libcoreclr.so
#37 0x00007f705b1d6838 in ?? () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.so
#38 0x00007f705b204dda in ?? () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.so
#39 0x00007f705b2050cf in ?? () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.so
#40 0x00007f705b205ff2 in corehost_main () from /root/helix/work/correlation/shared/Microsoft.NETCore.App/8.0.0/libhostpolicy.so
#41 0x00007f705b27f5dc in ?? () from /root/helix/work/correlation/host/fxr/8.0.0/libhostfxr.so
#42 0x00007f705b27a753 in ?? () from /root/helix/work/correlation/host/fxr/8.0.0/libhostfxr.so
#43 0x00007f705b276bcc in ?? () from /root/helix/work/correlation/host/fxr/8.0.0/libhostfxr.so
#44 0x00007f705b275cab in ?? () from /root/helix/work/correlation/host/fxr/8.0.0/libhostfxr.so
#45 0x00007f705b26eb65 in hostfxr_main_startupinfo () from /root/helix/work/correlation/host/fxr/8.0.0/libhostfxr.so
#46 0x00005620d8235942 in ?? ()
#47 0x00005620d8235e25 in ?? ()
#48 0x00007f705b2e009b in __libc_start_main (main=0x5620d8235d80, argc=18, argv=0x7ffdf8b63838, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdf8b63828) at ../csu/libc-start.c:308
#49 0x00005620d8229359 in ?? ()
[Inferior 1 (process 24) detached]
```

**Comment by SamMonoRT** [comment]
cc @kotlarmilos @ivanpovazan
This seems like the new test @kotlarmilos added recently.

**Comment by kotlarmilos** [comment]
This is a library test that failed with the interpreter. Added the Known Build Error label to identify any regressions.

According to the latest runs, it seems to be fixed.

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89428-merge-79e83417e2cd45198b/System.Net.Mail.Functional.Tests/1/console.3284299b.log?helixlogtype=result
