### ISSUE TITLE
Test failure JIT/Directed/arglist/vararg_TargetWindows/vararg_TargetWindows

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#87389]
**Failed in:** runtime-coreclr jitstress-isas-x86 20230610.1

**Failed tests:**
```
coreclr windows x86 Checked jitstress_isas_1_x86_nohwintrinsic @ Windows.10.Amd64.Open
    - JIT/Directed/arglist/vararg_TargetWindows/vararg_TargetWindows.cmd
coreclr windows x86 Checked jitstress_isas_2_x86_nohwintrinsic @ Windows.10.Amd64.Open
    - JIT/Directed/arglist/vararg_TargetWindows/vararg_TargetWindows.cmd
coreclr windows x86 Checked jitstress_isas_2_x86_nosse @ Windows.10.Amd64.Open
    - JIT/Directed/arglist/vararg_TargetWindows/vararg_TargetWindows.cmd
coreclr windows x86 Checked jitstress_isas_1_x86_nosse @ Windows.10.Amd64.Open
    - JIT/Directed/arglist/vararg_TargetWindows/vararg_TargetWindows.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwAD6D093CwA44D093Auploadsrglistararg_TargetWindowsoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwAD6D093Cpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  vararg_TargetWindows.dll 
Passed: TestPassingIntsManaged(new int[] { 100, 299, -100, 50 })
Passed: check_passing_four_sixteen_byte_structs(5, __arglist(expectedValue, s, s2, s3, s4)) == 0
Passed: TestPassingTenEightBytes
Passed: TestPassingTenSixteenBytes
Passed: TestPassingIntsNoVarargsManaged
Passed: TestPassingLongsNoVarargsManaged
Passed: TestPassingFloatsNoVarargsManaged
Passed: TestPassingDoublesNoVarargsManaged
Passed: TestPassingIntAndFloatsNoVarargsManaged
Passed: TestPassingFloatsAndIntNoVarargsManaged
Passed: TestPassingIntAndDoublesNoVarargsManaged
Passed: TestPassingDoublesAndIntNoVarargsManaged
Passed: TestPassingLongAndFloatsNoVarargsManaged()
Passed: TestPassingFloatsAndlongNoVarargsManaged()
Passed: TestPassinglongAndDoublesNoVarargsManaged()
Passed: TestPassingDoublesAndlongNoVarargsManaged()
Passed: TestPassingTwoIntStructsNoVarargsManaged()
Passed: TestPassingFourIntStructsNoVaragsManaged()
Passed: TestPassingTwoLongStructsNoVarargsManaged()
Passed: TestPassingTwoLongStructsWithIntAndLongNoVarargsManaged()
Passed: TestPassingTwoLongStructsAndIntNoVarargsManaged()
Passed: TestPassingFourLongStructsNoVarargsManaged()
Passed: TestPassingTwoFloatStructsNoVarargsManaged()
Passed: TestPassingFourFloatStructsNoVarargsManaged()
Passed: TestPassingTwoDoubleStructsNoVarargsManaged() 
Passed: TestPassingTwoLongStructsAndFloatNoVarargsManaged()
Passed: TestPassingFourDoubleStructsNoVarargsManaged()
Passed: TestPassingIntsManaged(new int[] { 100, 299, -100, 50 })
Passed: TestPassingLongsManaged(new long[] { 100L, 299L, -100L, 50L })
Passed: TestPassingFloatsManaged(new float[] { 100.0f, 299.0f, -100.0f, 50.0f })
Passed: TestPassingDoublesManaged(new double[] { 100.0d, 299.0d, -100.0d, 50.0d })
Passed: TestPassingManyIntsManaged
Passed: TestPassingManyLongsManaged
Passed: TestPassingManyFloatsManaged
Passed: TestPassingManyDoublesManaged
Passed: TestPassingIntsAndLongsManaged(new int[] { 100, 200 }, new long[] { 102312131L, 91239191L })
Passed: TestPassingFloatsAndDoublesManaged(new float[] { 100.0F, 200.0F }, new double[] { 12.1231321, 441.2332132335342321 })
Passed: TestPassingIntsAndFloatsManaged()
Passed: TestPassingLongsAndDoublesManaged()
Passed: TestPassingEmptyIntsManaged(new int[] { })
Passed: TestPassingEmptyLongsManaged(new long[] { })
Passed: TestPassingEmptyFloatsManaged(new float[] { })
Passed: TestPassingEmptyDoubleManaged(new double[] { })
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(0, 0, 0, 8, 1, firstExpectedValue, first)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(1, 0, 0, 8, 1, secondExpectedValue, second)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(0, 1, 0, 8, 1, thirdExpectedValue, third)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(1, 1, 0, 8, 1, fourthExpectedValue, fourth)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(0, 0, 0, 8, 1, firstExpectedValue, first)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(1, 0, 0, 8, 1, secondExpectedValue, second)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(0, 1, 0, 8, 1, thirdExpectedValue, third)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(1, 1, 0, 8, 1, fourthExpectedValue, fourth)) == 0
Passed: TestPassingEightByteStructsManaged()
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(0, 0, 0, 16, 1, firstExpectedValue, first)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(1, 0, 0, 16, 1, secondExpectedValue, second)) == 0
Passed: ManagedNativeVarargTests.CheckPassingStruct(6, __arglist(0, 1, 0, 16, 1, thirdExpectedVal
```

**Stack trace:**
```
    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor204|0_205(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```



**Comment by BruceForstall** [comment]
Example:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=302664&view=ms.vss-test-web.build-test-results-tab&runId=6137758&resultId=111359&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
set DOTNET_TieredCompilation=0
set DOTNET_EnableBMI1=0
set DOTNET_EnableBMI2=0
set DOTNET_EnableLZCNT=0
set DOTNET_EnableSSE=0
set DOTNET_JitStress=1
```

```
Expected: 100
Actual:   129
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
   at __GeneratedMainWrapper.Main()
_passing_struct(6, __arglist(1, 1, 0, 16, 1, fourthExpectedValue, fourth)) == 0
...
Failure: TestEchoThreeDoubleStructManagedNoVararg()
```

JitStress "nohwintrinsic" ABI regression

@dotnet/jit-contrib @tannergooding

**Comment by tannergooding** [comment]
May be related to the `Vector<T>` sizing feature, like with the Arm64 case. Looking

**Comment by tannergooding** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/87502 worked around by https://github.com/dotnet/runtime/pull/87420
