### ISSUE TITLE
Tests.System.TimeProviderTests.TestProviderTimer test failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#87477]
```
    Tests.System.TimeProviderTests.TestProviderTimer(provider: SystemTimeProvider { LocalTimeZone = (UTC-08:00) Pacific Time (Los Angeles), TimestampFrequency = 1000000000 }, MaxMilliseconds: 6000) [FAIL]
      Assert.Equal() Failure
      Expected: 400
      Actual:   300
      Stack Trace:
        /_/src/libraries/Common/tests/System/TimeProviderTests.cs(147,0): at Tests.System.TimeProviderTests.TestProviderTimer(TimeProvider provider, Int32 MaxMilliseconds)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=310209&view=results
Build error leg or test failing: Tests.System.TimeProviderTests.TestProviderTimer
Pull request: https://github.com/dotnet/runtime/pull/87465

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "Tests.System.TimeProviderTests.TestProviderTimer",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[369508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369508)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369508&view=ms.vss-test-web.build-test-results-tab&runId=7837500&resultId=177426)|dotnet/runtime#90301|
|[368460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368460)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368460&view=ms.vss-test-web.build-test-results-tab&runId=7814192&resultId=183739)|dotnet/runtime#88303|
|[368186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368186)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=368186&view=ms.vss-test-web.build-test-results-tab&runId=7800002&resultId=187116)|dotnet/runtime#89712|
|[367527](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367527)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367527&view=ms.vss-test-web.build-test-results-tab&runId=7781448&resultId=187114)|dotnet/runtime#89712|
|[366693](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366693)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366693&view=ms.vss-test-web.build-test-results-tab&runId=7759064&resultId=187117)|dotnet/runtime#89712|
|[365758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365758)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365758&view=ms.vss-test-web.build-test-results-tab&runId=7738876&resultId=175508)|dotnet/runtime#90109|
|[365568](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365568)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365568&view=ms.vss-test-web.build-test-results-tab&runId=7735174&resultId=169955)|dotnet/runtime#89876|
|[365460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365460)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365460&view=ms.vss-test-web.build-test-results-tab&runId=7731126&resultId=186150)|dotnet/runtime#89712|
|[365050](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365050)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365050&view=ms.vss-test-web.build-test-results-tab&runId=7719158&resultId=168970)|dotnet/runtime#89977|
|[362331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362331)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362331&view=ms.vss-test-web.build-test-results-tab&runId=7655120&resultId=186110)|dotnet/runtime#89712|
|[361438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361438)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361438&view=ms.vss-test-web.build-test-results-tab&runId=7631940&resultId=168300)|dotnet/runtime#89892|
|[361359](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361359)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361359&view=ms.vss-test-web.build-test-results-tab&runId=7628740&resultId=184506)|dotnet/runtime#89887|
|[360986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360986)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360986&view=ms.vss-test-web.build-test-results-tab&runId=7620470&resultId=177916)|dotnet/runtime#89864|
|[360643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360643)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360643&view=ms.vss-test-web.build-test-results-tab&runId=7611820&resultId=171330)|dotnet/runtime#89852|
|[359917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359917)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359917&view=ms.vss-test-web.build-test-results-tab&runId=7594788&resultId=170905)|dotnet/runtime#89827|
|[356491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356491)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356491&view=ms.vss-test-web.build-test-results-tab&runId=7500466&resultId=171098)|dotnet/runtime#89654|
|[356016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356016)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356016&view=ms.vss-test-web.build-test-results-tab&runId=7488496&resultId=173505)|dotnet/runtime#89534|
|[355839](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355839)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355839&view=ms.vss-test-web.build-test-results-tab&runId=7485488&resultId=177855)|dotnet/runtime#89652|
|[355823](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355823)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355823&view=ms.vss-test-web.build-test-results-tab&runId=7484760&resultId=168091)|dotnet/runtime#89654|
|[354795](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354795)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354795&view=ms.vss-test-web.build-test-results-tab&runId=7458960&resultId=178843)|dotnet/runtime#89612|
|[353099](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353099)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353099&view=ms.vss-test-web.build-test-results-tab&runId=7419808&resultId=175456)|dotnet/runtime#88034|
|[352568](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352568)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352568&view=ms.vss-test-web.build-test-results-tab&runId=7407246&resultId=173420)|dotnet/runtime#89490|
|[352449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352449)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352449&view=ms.vss-test-web.build-test-results-tab&runId=7402650&resultId=100244)|dotnet/runtime#89452|
|[351217](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351217)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351217&view=ms.vss-test-web.build-test-results-tab&runId=7374056&resultId=187836)|dotnet/runtime#89422|
|[350530](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350530)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350530&view=ms.vss-test-web.build-test-results-tab&runId=7358050&resultId=184687)|dotnet/runtime#89405|
|[350399](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350399)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350399&view=ms.vss-test-web.build-test-results-tab&runId=7355118&resultId=180922)||
|[349665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349665)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349665&view=ms.vss-test-web.build-test-results-tab&runId=7342512&resultId=176645)|dotnet/runtime#89296|
|[349455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349455)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349455&view=ms.vss-test-web.build-test-results-tab&runId=7331220&resultId=177693)||
|[347837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347837)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347837&view=ms.vss-test-web.build-test-results-tab&runId=7290248&resultId=172494)|dotnet/runtime#89308|
|[347587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347587)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347587&view=ms.vss-test-web.build-test-results-tab&runId=7284154&resultId=185926)|dotnet/runtime#89293|
|[347563](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347563)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347563&view=ms.vss-test-web.build-test-results-tab&runId=7283532&resultId=186868)|dotnet/runtime#89255|
|[344569](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344569)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344569&view=ms.vss-test-web.build-test-results-tab&runId=7202650&resultId=199780)|dotnet/runtime#89160|
|[343712](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343712)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343712&view=ms.vss-test-web.build-test-results-tab&runId=7181184&resultId=185861)|dotnet/runtime#89108|
|[343283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343283)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343283&view=ms.vss-test-web.build-test-results-tab&runId=7171962&resultId=182502)||
|[343063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343063)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343063&view=ms.vss-test-web.build-test-results-tab&runId=7166966&resultId=168006)|dotnet/runtime#88962|
|[342183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342183)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342183&view=ms.vss-test-web.build-test-results-tab&runId=7146490&resultId=174754)|dotnet/runtime#88926|
|[342063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342063)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342063&view=ms.vss-test-web.build-test-results-tab&runId=7143732&resultId=169839)|dotnet/runtime#88981|
|[341320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341320)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341320&view=ms.vss-test-web.build-test-results-tab&runId=7124150&resultId=170794)|dotnet/runtime#86089|
|[341260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341260)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341260&view=ms.vss-test-web.build-test-results-tab&runId=7121934&resultId=185752)|dotnet/runtime#88869|
|[341089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341089)|dotnet/runtime|[System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341089&view=ms.vss-test-web.build-test-results-tab&runId=7116648&resultId=190837)||
|[340892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340892)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340892&view=ms.vss-test-web.build-test-results-tab&runId=7108784&resultId=189877)||
|[340835](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340835)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340835&view=ms.vss-test-web.build-test-results-tab&runId=7108058&resultId=176877)|dotnet/runtime#88920|
|[339933](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339933)|dotnet/runtime|[Tests.System.TimeProviderTests.TestProviderTimer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339933&view=ms.vss-test-web.build-test-results-tab&runId=7087528&resultId=178976)|dotnet/runtime#88920|
|[339874](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339874)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339874&view=ms.vss-test-web.build-test-results-tab&runId=7086312&resultId=185818)|dotnet/runtime#88869|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|9|44|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=310209
**Result validation: :white_check_mark:** Known issue matched with the provided build.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/issues/84236 tracked the same failure.
