### ISSUE TITLE
Test failures: Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#87508]
Linux/arm64 JitStress

https://dev.azure.com/dnceng-public/public/_build/results?buildId=304266&view=ms.vss-test-web.build-test-results-tab&runId=6175518&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=126035

```
DOTNET_TieredCompilation=0
DOTNET_JitStress=101
```

```
  Starting:    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests (parallel test collections = on, max threads = 2)
...
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_T_BinderOptions [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(294,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_T_BinderOptions()
        --- End of stack trace from previous location ---
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_TypeOf [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(340,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_TypeOf()
        --- End of stack trace from previous location ---
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.TestCollectionsGen [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(694,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.TestCollectionsGen()
        --- End of stack trace from previous location ---
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_TypeOf_BinderOptions [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(386,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_TypeOf_BinderOptions()
        --- End of stack trace from previous location ---
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(202,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get()
        --- End of stack trace from previous location ---
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_T [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(248,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Get_T()
        --- End of stack trace from previous location ---
    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Configure [FAIL]
      The collection was expected to contain a single element, but it was empty.
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(724,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, LanguageVersion languageVersion, Action`1 assessDiagnostics)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigurationBindingGeneratorTests.Baselines.cs(546,0): at Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.ConfigurationBindingGeneratorTests.Configure()
        --- End of stack trace from previous location ---
  Finished:    Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests
```

@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Possibly related: https://github.com/dotnet/runtime/issues/87506

**Comment by AndyAyersMS** [comment]
I can repro -- via binary search on `DOTNET_JitStressRange` the issue is in this method:
```
# 8508: JIT compiled Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator+Emitter:EmitHelperMethods():this [FullOpts, IL size=227, code size=964, hash=0x1359ac8f JitStress]
```

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL

**Comment by jakobbotsch** [comment]
Oddly the above does not repro the issue for me... I am bisecting it anew now.
