### ISSUE TITLE
[wasm] Microbenchmarks failing with assertion `Assertion at /__w/1/s/src/mono/mono/component/marshal-ilgen-stub.c:28, condition `!m_type_is_byref(t)' not met`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#87623]
[Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2200729&view=results), [commit](1d9b36d3b6d23e37e9959ad85360b4041eeb90a9):

## Interpreter:

EDIT: symbolicated trace:
```
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/component/marshal-ilgen-stub.c:28, condition `!m_type_is_byref(t)' not met

    at ft (/home/helixbot/work/96640802/w/B9C40A15/e/performance/artifacts/bin/for-running/MicroBenchmarks/fa21f9df-08d0-43a4-b28d-0078821ea492/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/96640802/w/B9C40A15/e/performance/artifacts/bin/for-running/MicroBenchmarks/fa21f9df-08d0-43a4-b28d-0078821ea492/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm_trace_logger (wasm://wasm/00a5f7d6:wasm-function[7879]:0x1e41d0)
    at eglib_log_adapter (wasm://wasm/00a5f7d6:wasm-function[581]:0x37fbb)
    at monoeg_g_logv_nofree (wasm://wasm/00a5f7d6:wasm-function[504]:0x35f57)
    at monoeg_assertion_message (wasm://wasm/00a5f7d6:wasm-function[508]:0x36078)
    at mono_assertion_message (wasm://wasm/00a5f7d6:wasm-function[510]:0x360bb)
    at stub_emit_marshal_ilgen (wasm://wasm/00a5f7d6:wasm-function[1300]:0x66db1)
    at mono_emit_marshal (wasm://wasm/00a5f7d6:wasm-function[1820]:0x8990b)
    at emit_native_wrapper_ilgen (wasm://wasm/00a5f7d6:wasm-function[2651]:0xb86de)
```

## AOT:

This has the same assertion, but it keeps going, and hits more assertions after that.

```
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/component/marshal-ilgen-stub.c:28, condition `!m_type_is_byref(t)' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[174037]:0x3224ab8
    at wasm://wasm/1011ac9a:wasm-function[174556]:0x3248d31
    at wasm://wasm/1011ac9a:wasm-function[175391]:0x3279dc7
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2753, condition `<disabled>' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[173265]:0x31f1e64
    at wasm://wasm/1011ac9a:wasm-function[172870]:0x31cfd1d
    at wasm://wasm/1011ac9a:wasm-function[172862]:0x31c2f60
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2753, condition `<disabled>' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[173265]:0x31f1e64
    at wasm://wasm/1011ac9a:wasm-function[172870]:0x31cfd1d
    at wasm://wasm/1011ac9a:wasm-function[172862]:0x31c2f60
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2753, condition `<disabled>' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[173265]:0x31f1e64
    at wasm://wasm/1011ac9a:wasm-function[172870]:0x31cfd1d
    at wasm://wasm/1011ac9a:wasm-function[172862]:0x31c2f60
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2753, condition `<disabled>' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[173265]:0x31f1e64
    at wasm://wasm/1011ac9a:wasm-function[172870]:0x31cfd1d
    at wasm://wasm/1011ac9a:wasm-function[172862]:0x31c2f60
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2753, condition `<disabled>' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[173265]:0x31f1e64
    at wasm://wasm/1011ac9a:wasm-function[172870]:0x31cfd1d
    at wasm://wasm/1011ac9a:wasm-function[172862]:0x31c2f60
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2753, condition `<disabled>' not met

    at ft (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/A7DB0967/w/9B5708F6/e/performance/artifacts/bin/for-running/MicroBenchmarks/e0c1a5aa-e644-4a06-bf72-dc8cbcb1a68e/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm://wasm/1011ac9a:wasm-function[180617]:0x33af5ea
    at wasm://wasm/1011ac9a:wasm-function[173335]:0x31f3ec5
    at wasm://wasm/1011ac9a:wasm-function[173260]:0x31f1d1c
    at wasm://wasm/1011ac9a:wasm-function[173264]:0x31f1e4c
    at wasm://wasm/1011ac9a:wasm-function[173266]:0x31f1e93
    at wasm://wasm/1011ac9a:wasm-function[173265]:0x31f1e64
    at wasm://wasm/1011ac9a:wasm-function[172870]:0x31cfd1d
    at wasm://wasm/1011ac9a:wasm-function[172862]:0x31c2f60
```

EDIT: changes since last working commit: 6a6339fb6ed7f828242b9557c36e2df669a26587...1d9b36d3b6d23e37e9959ad85360b4041eeb90a9

cc @jandupej

**Comment by lewing** [comment]
@jandupej @kg could this be related to the ilgen changes?

**Comment by jandupej** [comment]
> @jandupej @kg could this be related to the ilgen changes?

It might be. At that point in ilgen stub, there should be no byref types. It is possible that the analyzer has missed a case where marhsal ilgen is needed. I'll investigate tmr.

**Comment by radical** [comment]
changes since last working commit: https://github.com/dotnet/runtime/compare/6a6339fb6ed7f828242b9557c36e2df669a26587...1d9b36d3b6d23e37e9959ad85360b4041eeb90a9 which includes https://github.com/dotnet/runtime/pull/86035

**Comment by radical** [comment]
@jandupej @kg @lewing symbolicated trace:
```
Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/component/marshal-ilgen-stub.c:28, condition `!m_type_is_byref(t)' not met

    at ft (/home/helixbot/work/96640802/w/B9C40A15/e/performance/artifacts/bin/for-running/MicroBenchmarks/fa21f9df-08d0-43a4-b28d-0078821ea492/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12422)
    at mt (/home/helixbot/work/96640802/w/B9C40A15/e/performance/artifacts/bin/for-running/MicroBenchmarks/fa21f9df-08d0-43a4-b28d-0078821ea492/bin/net8.0/browser-wasm/AppBundle/dotnet.runtime.js:3:12676)
    at wasm_trace_logger (wasm://wasm/00a5f7d6:wasm-function[7879]:0x1e41d0)
    at eglib_log_adapter (wasm://wasm/00a5f7d6:wasm-function[581]:0x37fbb)
    at monoeg_g_logv_nofree (wasm://wasm/00a5f7d6:wasm-function[504]:0x35f57)
    at monoeg_assertion_message (wasm://wasm/00a5f7d6:wasm-function[508]:0x36078)
    at mono_assertion_message (wasm://wasm/00a5f7d6:wasm-function[510]:0x360bb)
    at stub_emit_marshal_ilgen (wasm://wasm/00a5f7d6:wasm-function[1300]:0x66db1)
    at mono_emit_marshal (wasm://wasm/00a5f7d6:wasm-function[1820]:0x8990b)
    at emit_native_wrapper_ilgen (wasm://wasm/00a5f7d6:wasm-function[2651]:0xb86de)
```

**Comment by radical** [comment]
Looks like a build issue. I'm fixing it now.

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/87629 .
