### ISSUE TITLE
Test failure DataContractJsonSerializerTests.DCJS_BoolAsRoot

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#87755]
**Failed in:** [runtime-coreclr libraries-jitstress-random 20230617.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=311189&view=ms.vss-test-web.build-test-results-tab&runId=6348472&resultId=196374&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress_random_2-Windows.11.Arm64.Open
    - DataContractJsonSerializerTests.DCJS_BoolAsRoot
net8.0-linux-Release-x64-CoreCLR_checked-jitstress_random_1-Ubuntu.1804.Amd64.Open
    - System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation
    - System.Xml.XmlSchemaTests.TC_SchemaSet_Misc.Dev10_40509
    - System.Xml.XmlSchemaTests.TC_SchemaSet_Misc.v106
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress_random_2-Windows.11.Arm64.Open
    - DataContractJsonSerializerTests.DCJS_DictionaryGenericMembers
    - DataContractJsonSerializerTests.DCJS_ArrayOfBoolean
    - DataContractJsonSerializerTests.DCJS_CustomType
    - DataContractJsonSerializerTests.DCJS_DataMemberAttribute
    - DataContractJsonSerializerTests.DCJS_TypeWithAllPrimitiveProperties
    - DataContractJsonSerializerTests.DCJS_GenericDictionaryOfInt32Boolean
    - DataContractJsonSerializerTests.DCJS_DictionaryWithVariousKeyValueTypes
    - DataContractJsonSerializerTests.DCJS_GenericICollectionOfBoolean
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress_random_2-Windows.11.Arm64.Open
    - DataContractJsonSerializerTests.DCJS_TypeWithAllPrimitiveProperties
    - DataContractJsonSerializerTests.DCJS_DataMemberAttribute
    - DataContractJsonSerializerTests.DCJS_GenericDictionaryOfInt32Boolean
    - DataContractJsonSerializerTests.DCJS_ObjectAsRoot
    - DataContractJsonSerializerTests.DCJS_DictionaryGenericMembers
    - DataContractJsonSerializerTests.DCJS_DictionaryWithVariousKeyValueTypes
    - DataContractJsonSerializerTests.DCJS_GenericICollectionOfBoolean
    - DataContractJsonSerializerTests.DCJS_DictionaryMembers
    - DataContractJsonSerializerTests.DCJS_ArrayOfBoolean
    - DataContractJsonSerializerTests.DCJS_CollectionMembers
    - DataContractJsonSerializerTests.DCJS_EnumerableMembers
    - DataContractJsonSerializerTests.DCJS_NonGenericDictionaryOfInt32Boolean
    - DataContractJsonSerializerTests.DCJS_CustomType
    - DataContractJsonSerializerTests.DCJS_NonGenericDictionaryOfInt32Boolean
    - DataContractJsonSerializerTests.DCJS_CollectionMembers
    - DataContractJsonSerializerTests.DCJS_DictionaryMembers
    - DataContractJsonSerializerTests.DCJS_EnumerableMembers
    - DataContractJsonSerializerTests.DCJS_ObjectAsRoot
```

**Error message:**
```
 System.NullReferenceException : Object reference not set to an instance of an object.
```

**Stack trace:**
```
    at System.Xml.XmlConvert.TryToBoolean(String s, Boolean& result) in /_/src/libraries/System.Private.Xml/src/System/Xml/XmlConvert.cs:line 762
   at System.Xml.Schema.Datatype_boolean.TryParseValue(String s, XmlNameTable nameTable, IXmlNamespaceResolver nsmgr, Object& typedValue) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/DataTypeImplementation.cs:line 1538
   at System.Xml.Schema.XmlSchemaValidator.CheckElementValue(String stringValue) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/XmlSchemaValidator.cs:line 1963
   at System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(String stringValue, XmlSchemaSimpleType& memberType) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/XmlSchemaValidator.cs:line 1436
   at System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(XmlSchemaInfo schemaInfo, Object typedValue) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/XmlSchemaValidator.cs:line 1188
   at System.Xml.XsdValidatingReader.ProcessEndElementEvent() in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XsdValidatingReader.cs:line 2132
   at System.Xml.XsdValidatingReader.Read() in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XsdValidatingReader.cs:line 1414
   at System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation() in /_/src/libraries/System.Private.Xml/tests/XmlSchema/XmlSchemaValidatorApi/ValidateMisc.cs:line 995
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Xml.XmlSchemaValidatorApiTests.TCXmlSchemaValidatorMisc.NullPointerExceptionInXSDValidation | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
</details>

**Comment by BruceForstall** [comment]
Maybe another case of https://github.com/dotnet/runtime/issues/87506?

**Comment by AndyAyersMS** [comment]
Same method `System.Xml.XmlConvert:TryToBoolean` as in #87506 so almost certainly the same issue.

cc @jakobbotsch
