### ISSUE TITLE
ILStrip failure for FsToolkit.ErrorHandling(Must be of type CilStrip.Mono.Cecil.TypeReference)

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#87867]
_From @NickDarvey on Wed, 21 Jun 2023 11:28:51 GMT_

### Steps to Reproduce

1. Download `FsToolkitiOSApp.zip` (attached)
2. Run
    ```
    dotnet build -c Release -t:Run -f net7.0-ios -p:RuntimeIdentifier=ios-arm64 -p:_DeviceName=1234 -bl
    ``` 

### Expected Behavior

Release build completes.

### Actual Behavior

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7067/targets/Xamarin.Shared.Sdk.targets(765,3): ILStrip failed for obj/Release/net7.0-ios/ios-arm64/linked/FsToolkit.ErrorHandling.dll: Must be of type CilStrip.Mono.Cecil.TypeReference [/FsToolkitiOSApp.fsproj]


System.ArgumentException: Must be of type CilStrip.Mono.Cecil.TypeReference
   at CilStrip.Mono.Cecil.GenericArgumentCollection.OnValidate(Object o)
   at System.Collections.CollectionBase.System.Collections.IList.Add(Object value)
   at CilStrip.Mono.Cecil.GenericArgumentCollection.Add(TypeReference value)
   at CilStrip.Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.GetGenericArg(GenericArg arg, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.CompleteParameter(ParameterDefinition parameter, Param signature, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.BuildParameterDefinition(String name, Int32 sequence, ParameterAttributes attrs, Param psig, GenericContext context)
   at CilStrip.Mono.Cecil.ReflectionReader.CompleteMethods()
   at CilStrip.Mono.Cecil.ReflectionReader.VisitTypeDefinitionCollection(TypeDefinitionCollection types)
   at CilStrip.Mono.Cecil.AggressiveReflectionReader.VisitTypeDefinitionCollection(TypeDefinitionCollection types)
   at CilStrip.Mono.Cecil.ReflectionReader.VisitModuleDefinition(ModuleDefinition mod)
   at CilStrip.Mono.Cecil.StructureReader.TerminateAssemblyDefinition(AssemblyDefinition asm)
   at CilStrip.Mono.Cecil.AssemblyDefinition.Accept(IReflectionStructureVisitor visitor)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(ImageReader irv, Boolean manifestOnly)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(ImageReader reader)
   at CilStrip.Mono.Cecil.AssemblyFactory.GetAssembly(String file)
   at ILStrip.StripAssembly(ITaskItem assemblyItem)
   
```

### Environment

<details>
<summary>Version information</summary>

```
dotnet  7.0.304
dotnet workload maui-ios 7.0.86/7.0.100
```

</details>

### Build Logs and Example Project

[FsToolkitiOSApp.zip](https://github.com/xamarin/xamarin-macios/files/11816963/FsToolkitiOSApp.zip)

### Workaround

Disabling IL stripping, as described in https://github.com/xamarin/xamarin-macios/issues/14841#issue-1218995218, works.

Is there a way to _only_ disable it for this asssembly?

_Copied from original issue xamarin/xamarin-macios#18485_

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Wed, 21 Jun 2023 12:18:17 GMT_

Smaller repro: [testproj.zip](https://github.com/xamarin/xamarin-macios/files/11817339/testproj.zip)

Download & execute:

```
$ dotnet build /t:RunILStrip
testproj.csproj(10,5): error : ILStrip failed for FsToolkit.ErrorHandling.dll: Must be of type CilStrip.Mono.Cecil.TypeReference
```

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Wed, 21 Jun 2023 12:18:34 GMT_

> Is there a way to _only_ disable it for this asssembly?

It's rather ugly, but you can add something like this to your project file:

```xml
  <Target Name="_RemoveILStripTrigger" BeforeTargets="_StripAssemblyIL">
    <ItemGroup>
      <_RemovedResolvedFileToPublish Include="@(ResolvedFileToPublish)" Condition="'%(Filename)%(Extension)' == 'FsToolkit.ErrorHandling.dll'" />
      <ResolvedFileToPublish Remove="@(_RemovedResolvedFileToPublish)" />
    </ItemGroup>
  </Target>

  <Target Name="_RestoreILStripTrigger" AfterTargets="_StripAssemblyIL">
    <ItemGroup>
      <ResolvedFileToPublish Include="@(_RemovedResolvedFileToPublish)" />
    </ItemGroup>
  </Target>
```

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Wed, 21 Jun 2023 12:18:58 GMT_

Moving to dotnet/runtime, since the ILStrip implementation lives there.

**Comment by SamMonoRT** [comment]
cc @fanyang-mono

**Comment by jandupej** [comment]
I can replicate the issue both with the current ILStrip and one from net6.0.

**Comment by jandupej** [comment]
Moving to net9.0, since there is a workaround.

**Comment by jandupej** [comment]
When opening the assembly to be trimmed, Cecil chokes on the following method:
```cil
.method public static 
	valuetype [FSharp.Core]Microsoft.FSharp.Core.FSharpValueOption`1<!!'value'> tryParse$W<'value'> (
		class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!!'value'&, bool>> tryParse,
		string valueToParse
	) cil managed
{...}
```
Note the `'value'&` in the inner `FSharpFunc'2`, this results in `ReflectionReader.GetTypeRefFromSig` to return `null`, because it has no case for `ElementType.ByRef`. Certain validations fail and build crashes.

**Comment by xperiandri** [comment]
This is our repro https://github.com/Ecierge/FsToolkit.ErrorHandling_AOT_repro

**Comment by vitek-karas** [comment]
This makes me sad...

The ILStrip task uses a private copy of Mono.Cecil because it seems to need to set metadata token values (which mainline Cecil doesn't support). This private copy is maintained in dotnet/runtime-assets and was added with https://github.com/dotnet/runtime-assets/pull/160. But it's really just a copy from mono/mono which was added with https://github.com/mono/mono/commit/29e9001a01adbe2d787595845d0a6f7a5abe7e1a. That is a 14 years old commit - there's no way to tell how old the source was when the copy was made, but at least 14 years.

The problem:
- We've been making changes to IL since, some of which needed Mono.Cecil updates so that it can correctly parse the input and write it back out. So, there are likely cases where ILStrip corrupts the content to some degree.
- Any fixes made to Cecil in the last 14 years are not there. It's very possible that the above issue doesn't exist in current Cecil.

The thing which breaks the 14 year old Cecil is a ref type in a generic parameter - not surprising as ref types didn't exist 14 years ago really - specifically this: https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/fd9460f0bfa9b670d7ef95ba48ec274a5146871c/src/FsToolkit.ErrorHandling/ValueOption.fs#L44

Quick look at the usage of Cecil says that this is not going to be easy to fix as Cecil changed a LOT since then (the public APIs used 
to just load assembly doesn't exist anymore), so it's not just the ability to manipulate tokens which is different.

The "fix" for this whole situation is probably tracked by https://github.com/dotnet/runtime/issues/60273.

Honestly, it's surprising this is not a more common problem.

/cc @steveisok

**Comment by vitek-karas** [comment]
Also cc @agocke, @sbomer as sort of owners of Cecil's usage in runtime. See the comment above for context.

**Comment by xperiandri** [comment]
Any updates?

**Comment by MichalStrehovsky** [comment]
`class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc2<!!'value'&, bool>>` is invalid IL. Byrefs cannot be generic type arguments.

This code does not work at runtime. ILStrip is free to crash on assemblies that don't conform to the file format.

I don't know nearly enough F# to reach this at runtime but a small C# test app that references the FsToolkit.ErrorHandling nuget (with no trimming or ILStrip whatsoever):

```csharp
var t = Type.GetType("FsToolkit.ErrorHandling.ValueOption, FsToolkit.ErrorHandling");
Console.WriteLine(t.GetMethod("tryParse$W"));
```

Will crash with:

```
Unhandled exception. System.TypeLoadException: The generic type 'Microsoft.FSharp.Core.FSharpFunc`2' was used with an invalid instantiation in assembly 'FSharp.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.<get_Signature>g__LazyCreateSignature|25_0()
   at System.Reflection.RuntimeMethodInfo.ToString()
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at System.Console.WriteLine(Object value)
   at Program.<Main>$(String[] args) in C:\Users\Michal\source\repos\Repro\Repro\Program.cs:line 2
```

**Comment by MichalStrehovsky** [comment]
Hmm, looks like I don't have sufficient rights to move this to the dotnet/fsharp repo. @T-Gro do you have sufficient rights to move this? This is an F# compiler bug (and maybe language bug if this is allowed?). The details at https://github.com/dotnet/runtime/issues/87867#issuecomment-2987986857, problematic code at https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/fd9460f0bfa9b670d7ef95ba48ec274a5146871c/src/FsToolkit.ErrorHandling/ValueOption.fs#L44

**Comment by T-Gro** [comment]
This is a "witness" method for an F# inline function with statically (compile time) resolved type parameters ("SRTP"s). It is only ever run after type application and inlining.

Is there an extension point by which one can exclude methods from Cecil validation? That could be done as an idea.
