### ISSUE TITLE
[HTTP/3] [HttpStress] Client failing to connect

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#87938]
Recently we started to see the following error in HTTP 3.0 stress runs on Linux. Unlike the timeouts in https://github.com/dotnet/runtime/issues/77126, this kills of the test run at startup.

<details>

```
Starting 4 client workers.
client_1  | Trying connect to the server [https://server:5001/.](https://server:5001/)
server_1  | Server started at https://+:5001/
client_1  | Stress client could not connect to host https://server:5001/, 10 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 9 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 8 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 7 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 6 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 5 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 4 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 3 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 2 attempts remaining
client_1  | Stress client could not connect to host https://server:5001/, 1 attempts remaining
client_1  | Unhandled exception. System.AggregateException: One or more errors occurred. (Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.)
client_1  |  ---> System.Net.Http.HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
client_1  |  ---> System.Net.Http.HttpRequestException: The server is currently unreachable. (server:5001)
client_1  |  ---> System.Net.Quic.QuicException: The server is currently unreachable.
client_1  |    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 484
client_1  |    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 545
client_1  |    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 579
client_1  | --- End of stack trace from previous location ---
client_1  |    at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 176
client_1  |    at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 328
client_1  |    at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 72
client_1  |    at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 77
client_1  |    at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 120
client_1  |    --- End of inner exception stack trace ---
client_1  |    at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 133
client_1  |    at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 919
client_1  |    at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 993
client_1  |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1049
client_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
client_1  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 530
client_1  |    at HttpStress.StressClient.<InitializeClient>g__SendTestRequestToServer|16_0(Int32 maxRetries) in /app/StressClient.cs:line 150
client_1  |    --- End of inner exception stack trace ---
client_1  |    at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 442
client_1  |    at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 980
client_1  |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1049
client_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
client_1  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 530
client_1  |    at HttpStress.StressClient.<InitializeClient>g__SendTestRequestToServer|16_0(Int32 maxRetries) in /app/StressClient.cs:line 150
client_1  |    at HttpStress.StressClient.InitializeClient() in /app/StressClient.cs:line 137
client_1  |    --- End of inner exception stack trace ---
client_1  |    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2785
client_1  |    at System.Threading.Tasks.Task.Wait() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2629
client_1  |    at HttpStress.StressClient.Start() in /app/StressClient.cs:line 90
client_1  |    at HttpStress.Program.Run(Configuration config) in /app/Program.cs:line 223
client_1  |    at HttpStress.Program.Main(String[] args) in /app/Program.cs:line 40
client_1  |    at HttpStress.Program.<Main>(String[] args)
```

</details>

https://dev.azure.com/dnceng-public/public/_build/results?buildId=310086&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0

**Comment by ManickaP** [comment]
I believe this should be fixed by this particular change: https://github.com/dotnet/runtime/pull/87971/files#diff-a4f53800a0e6b2a16cda442c903251d398bef9226539ed6312f71bdbf3998ce4R145-R146
I'll close it for now, Anton feel free to re-open if this resurfaces.
