### ISSUE TITLE
_marshal_task_to_cs calls complete_task on already completed task

### ISSUE THREAD

**Issue by dlemstra** [dotnet/runtime#87963]
### Description

We have a project that uses `<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>` and copies the content of `AppBundle` to a JavaScript project. This dotnet project contains a lot of libraries and we have an issue were we could not found the root cause for. We are unable to reproduce it in a small project . I am adding the error message here because this might be related:

```
dotnet.js:14  System.TypeLoadException: Could not find method '.ctor' due to a type load error: Parent class
 failed to load, due to: Failed to load generic parameter 1 assembly:CompanyName.dll type:CompanyClass`2 
member:(null) assembly:CompanyName.dll type:OtherCompanyClass`2 member:(null)
```

To try to work around this problem we tried an AOT build (`RunAOTCompilationAfterBuild`). But we then got the following error reported in the console:

> An attempt was made to transition a task to a final state when it had already completed.

This seems to be happening because of this call: 

https://github.com/dotnet/runtime/blob/5331448bc790aa27b8bfa08ee0f56761d10347b4/src/mono/wasm/runtime/marshal-to-cs.ts#L323

That is happening after this call: https://github.com/dotnet/runtime/blob/5331448bc790aa27b8bfa08ee0f56761d10347b4/src/mono/wasm/runtime/marshal-to-cs.ts#L318 that fails with the following error message:

```
RuntimeError: null function or function signature mismatch
    at dotnet.wasm:wasm-function[268195]:0x792fb17
    at dotnet.wasm:wasm-function[278722]:0x7d6dd5c
    at invoke_viiiii (dotnet/dotnet.js:14:237182)
    at dotnet.wasm:wasm-function[278817]:0x7d7bda0
    at dotnet.wasm:wasm-function[293]:0x1850ff
    at dotnet.wasm:wasm-function[306692]:0x9bbb73a
    at invoke_vi (dotnet/dotnet.js:14:235216)
    at dotnet.wasm:wasm-function[306970]:0x9bd7ebc
    at dotnet.wasm:wasm-function[306662]:0x9bbad05
    at dotnet.wasm:wasm-function[306599]:0x9bac4f5
```

### Reproduction Steps

We are unable to create a small sample project that can be used to reproduce this issue.

### Expected behavior

That the `RuntimeError: null function or function signature mismatch` error is reported.

### Actual behavior

We are getting this error message instead `An attempt was made to transition a task to a final state when it had already completed.`.

### Configuration

.NET 7.0.304
Windows
```
<OutputType>Exe</OutputType>
<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
```

**Comment by radical** [comment]
cc @kg @pavelsavara

**Comment by pavelsavara** [comment]
`Failed to load generic parameter 1` could be trimming problem, reflection problem or some non-wasm native dependency in the DLL preventing the class from loading. To troubleshoot it, I think you could try to create simpler app, where you try to instantiate that type yourself.

`already completed task` is more interesting from our perspective, if you could give us small sample app to reproduce it. Possibly you are doing something nasty with JS promises ?

**Comment by dlemstra** [comment]
Thanks for your quick response. I will try to create a smaller app where this can be reproduced but that won't be an easy task due to the complexity of the library and all it's dependencies. But I just managed to find a workaround for this issue by accident:

```C#
// Inside a constructor
Console.WriteLine(typeof(OtherCompanyClass<SomeClass<TValue>, TItem>));
A= (_A = new OtherCompanyClass<SomeClass<TValue>, TItem>(this, this)).ExtensionMethod(this);
```

Adding the `Console.WriteLine` seems to prevent something from happening that breaks the application and I hope you can tell me what that could be. And it also looks like that small sample could be used to diagnose both issues. Adding both `<WasmEmitSymbolMap>true</WasmEmitSymbolMap>` and `<WasmNativeStrip>false</WasmNativeStrip>`  is telling me that the issue is occuring at the same spot. And I also just did a quick search for `_marshal_task_to_cs` inside the issues (should have done that earlier) and I found #77122 that mentions something similar. Maybe our code also causes the dotnet.wasm to break and then this issue will occur?

**Comment by kg** [comment]
> `already completed task` is more interesting from our perspective, if you could give us small sample app to reproduce it. Possibly you are doing something nasty with JS promises ?
Perhaps the process of completing the task (running completion handlers?) is failing, so when we attempt to handle the exception, we go in and try to complete it with the new exception and that fails?

**Comment by kg** [comment]
> > `already completed task` is more interesting from our perspective, if you could give us small sample app to reproduce it. Possibly you are doing something nasty with JS promises ?
> 
> Perhaps the process of completing the task (running completion handlers?) is failing, so when we attempt to handle the exception, we go in and try to complete it with the new exception and that fails?

Yes, looking at https://github.com/dotnet/runtime/blob/cfe30c057debbdd9ad21b36ae61062dbe72a1f83/src/mono/wasm/runtime/marshal-to-cs.ts#L315-L324 I think that's what happened here. The way it's written, if we fail during complete_task or the call after it, we will attempt to complete the task again. We should either swallow the exception caused by a second task completion, or put in some logic to detect that it's already completed.
