### ISSUE TITLE
ILC fails to initialize native object writer with path containing '../'

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#87961]
## Description

The ILC compiler encounters a failure when attempting to initialize the Native Object Writer with a path that contains `../`. When the path does not include a parent directory reference, the compiler initializes the writer correctly.

```
error : Unable to create file for /tmp/helix/working/ABCA092E/w/C3E60A32/e/apple_build/../publish/native/Program.o: No such file or directory [/private/tmp/helix/working/ABCA092E/w/C3E60A32/e/publish/ProxyProjectForAOTOnHelix.proj]
error : Fail to initialize Native Object Writer [/private/tmp/helix/working/ABCA092E/w/C3E60A32/e/publish/ProxyProjectForAOTOnHelix.proj]
  System.IO.IOException: Fail to initialize Native Object Writer
     at ILCompiler.DependencyAnalysis.ObjectWriter..ctor(String objectFilePath, NodeFactory factory, ObjectWritingOptions options) in /Users/miloskotlar/dotnet/runtime-ios/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs:line 856
     at ILCompiler.DependencyAnalysis.ObjectWriter.EmitObject(String objectFilePath, IReadOnlyCollection`1 nodes, NodeFactory factory, ObjectWritingOptions options, IObjectDumper dumper, Logger logger) in /Users/miloskotlar/dotnet/runtime-ios/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/ObjectWriter.cs:line 947
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in /Users/miloskotlar/dotnet/runtime-ios/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 523
     at ILCompiler.Program.Run() in /Users/miloskotlar/dotnet/runtime-ios/src/coreclr/tools/aot/ILCompiler/Program.cs:line 545
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass215_0.<.ctor>b__0(InvocationContext context) in /Users/miloskotlar/dotnet/runtime-ios/src/coreclr/tools/aot/ILCompiler/ILCo
```

**Comment by kotlarmilos** [comment]
https://github.com/dotnet/runtime/pull/87962#discussion_r1259429080
