### ISSUE TITLE
learn: how to implement a client of the event based asynchronous pattern throws a platform not supported exception

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#87974]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/learn:-how-to-implement-a-client-of-the-/10324907)._

---
[severity:It's more difficult to complete my work]
Using the code from:
[learn: how to implement a client of the event based asynchronous pattern](https://learn.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/how-to-implement-a-client-of-the-event-based-asynchronous-pattern),
I am getting a [platformnotsupportedexception](https://learn.microsoft.com/en-us/dotnet/api/system.platformnotsupportedexception?view=net-7.0) 

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Operation is not supported on this platform.
  Source=WinFormsApp1
  StackTrace:
   at AsyncPattern.PrimeNumberCalculator.WorkerEventHandler.BeginInvoke(Int32 numberToCheck, AsyncOperation asyncOp, AsyncCallback callback, Object object)
   at AsyncPattern.PrimeNumberCalculator.CalculatePrimeAsync(Int32 numberToTest, Object taskId) in C:\my\learn\cs\learn\components\prime.number.calculator\WinFormsApp1\PrimeNumberCalculatorMain.cs:line 641
   at AsyncPattern.PrimeNumberCalculatorMain.startAsyncButton_Click(Object sender, EventArgs e) in C:\my\learn\cs\learn\components\prime.number.calculator\WinFormsApp1\PrimeNumberCalculatorMain.cs:line 99
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

at
```
// Start the asynchronous operation.
WorkerEventHandler workerDelegate = new WorkerEventHandler( CalculateWorker );
workerDelegate.BeginInvoke(
    numberToTest,
    asyncOp,
    null,
    null );
```

when called from:
```
PrimeNumberCalculatorMain.startAsyncButton_Click( object, EventArgs)
```

The project file looks like this:
```
  
    WinExe
    net6.0-windows
    enable
    true
    enable
  
```

And the main function is:
```
[STAThread]
static void Main()
{
    ApplicationConfiguration.Initialize();
    Application.Run( new PrimeNumberCalculatorMain() );
}
```

Microsoft Visual Studio Community 2022 (64-bit) - Version 17.5.3

---
#### Feedback Bot on 3/29/2023, 07:03 AM: 

(private comment, text removed)
#### John Qiao [MSFT] on 3/30/2023, 03:30 AM: 

(private comment, text removed)
#### David Hary on 3/30/2023, 06:32 AM: 

(private comment, text removed)
#### Feedback Bot on 3/30/2023, 09:30 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CarnaViire** [comment]
Comment from the user:

> Meanwhile, I implemented this using the Task-Based pattern.
Still, it might help others if the learn topic could be either fixed, removed or the cause of the platform exception be elucidated.
Would it make sense to add a note to the learning topic regarding this issue once confirmed.
