### ISSUE TITLE
System.TypeInitializationException thrown in Blazor WASM with a certain type layout

### ISSUE THREAD

**Issue by akurone** [dotnet/runtime#88066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Type layout below causes `System.TypeInitializationException` to be thrown in WASM (same code can run in a server-type project):
```csharp
public sealed class TwistedType {
  public static IEnumerable<TwistedType> TheTroubleMaker = NestedStatic.ArrayOfTwistedType.Prepend(new());

  public static class NestedStatic {
    public static TwistedType[] ArrayOfTwistedType = { new() };
  }

  public string World { get; } = "World";
}
```
The relevant member of `NestedStatic` type is referenced like:
```razor
<h1>Hello, @TwistedType.NestedStatic.ArrayOfTwistedType[0].World!</h1>
```

### Expected Behavior

Type initialization should be successful in WASM as in server.

### Steps To Reproduce

Clone [this](https://github.com/akurone/BlzWasmTypeInitRepro) repo and run.
Versions:
- Chrome: 116.0.5829.0
- .net: 7.0.304

### Exceptions (if any)

```console
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'NestedStatic' threw an exception.
System.TypeInitializationException: The type initializer for 'NestedStatic' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'BlzWasmTypeInitRepro.TwistedType' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Prepend[TwistedType](IEnumerable`1 source, TwistedType element)
   at BlzWasmTypeInitRepro.TwistedType..cctor() in BlzWasmTypeInitRepro\Types.cs:line 5
   --- End of inner exception stack trace ---
   at BlzWasmTypeInitRepro.TwistedType.NestedStatic..cctor() in BlzWasmTypeInitRepro\Types.cs:line 9
   --- End of inner exception stack trace ---
   at BlzWasmTypeInitRepro.Pages.Index.BuildRenderTree(RenderTreeBuilder __builder) in BlzWasmTypeInitRepro\Pages\Index.razor:line 3
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### .NET Version

7.0.304

**Comment by lambdageek** [comment]
CoreCLR is also quite fragile here.  change `#if true` to `#if false` below to see a difference - the first one runs, the second one throws

```csharp
using System;
using System.Collections.Generic;

Console.WriteLine ($"Hello {SecondOne.ArrayOfFirstOne[0].World}");


public static class Helper
{
    public static FirstOne[] Prepend(FirstOne[] coll, FirstOne oneMore)
    {
        var copy = new FirstOne[coll.Length + 1];
        copy[0] = oneMore;
        for (int i = 0; i < coll.Length; ++i)
            copy[i+1] = coll[i];
        return copy;
    }
}

public sealed class FirstOne {
#if true
    // this works
    
    public static IEnumerable<FirstOne> TheTroubleMaker = Helper.Prepend (SecondOne.ArrayOfFirstOne, new());

#else
    // this throws
    
    public static IEnumerable<FirstOne> TheTroubleMaker;

    static FirstOne() {
        //Console.WriteLine ("FirstOne .cctor");
        TheTroubleMaker = Helper.Prepend (SecondOne.ArrayOfFirstOne, new());
    }
#endif

    public string World { get; } = "World";
}


public static class SecondOne {
    public static FirstOne[] ArrayOfFirstOne = { new () };

    //static SecondOne() {
    //    Console.WriteLine ("SecondOne .cctor");
    //    ArrayOfFirstOne = new FirstOne[] { new() };
    //}
}
```

**Comment by lambdageek** [comment]
Ok, this isn't one of the cases where ECMA allows us some leeway because of circular dependencies.  Rather, this is a case where the cctor must run "at or before static field access" and mono is leaning on the "or before" (specifically I think we run it when the instance constructor for `FirstOne` is called)

It looks like mono is calling a `beforefieldinit` static constructor even if we never touch the static fields of that class

```csharp
using System;
using System.Runtime.CompilerServices;
using System.Collections.Generic;

object o  = SecondOne.ArrayOfFirstOne[0];
Console.WriteLine ($"Hello {o!=null}");

public static class Helper
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static FirstOne[] PrependOne(FirstOne[] coll)
    {
        throw new Exception ("Called");
    }
}

public sealed class FirstOne {
    public static IEnumerable<FirstOne> TheTroubleMaker = Helper.PrependOne (SecondOne.ArrayOfFirstOne);

    public FirstOne() {}

    public string World() => "World";
}

public static class SecondOne {
    public static FirstOne[] ArrayOfFirstOne = { new () };
}
```

It looks like we're running the cctor for `FirstOne` when `SecondOne` tries to instantiate it.  But constructor invocation for a `beforefieldinit` class is not sufficient.  _Only_ static field access (or explicit cctor invocation) should trigger it, I think.

There is s

**Comment by lambdageek** [comment]
@vargaz @BrzVlad I see some calls to `mono_class_is_before_field_init` in method-to-ir, so we're aware that sometimes `beforefieldinit` means we shouldn't run the cctor.  But it looks like we do it anyway.  In the interpreter I don't see anything that looks at `beforefieldinit`, so it's probably too eager, also.

**Comment by vargaz** [comment]
Probably a dup of:
https://github.com/dotnet/runtime/issues/77513

**Comment by lambdageek** [comment]
I think #77513 is not quite the same. In that one, the bad static field is used in the body of a called method - it's just not on an executed path. In this one, the bad static field is not used at all in any JITted method.
Fixing 77513 seems harder

**Comment by LeVladIonescu** [comment]
Moving this to `Postponed to .Net9` with high priority.
