### ISSUE TITLE
Cryptographic error "Padding is invalid and cannot be removed"

### ISSUE THREAD

**Issue by hunterb46** [dotnet/runtime#88070]
### Describe the bug
An exception is thrown when decrypting from an inflate stream
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.

It appears to only happen on certain lengths, so in the example below, it tests out different sizes, where it is starting on a size that causes an issue on my local machine.

### To Reproduce
```c#
  var aes = Aes.Create();
  aes.KeySize = 256;
  
  for (var i = 3911; i < 100000; i++)
  {
      var data = new byte[i];
      var rand = new Random();
      rand.NextBytes(data);

      using (var aesEncryptor = aes.CreateEncryptor())
      using (var source = new MemoryStream(data))
      using (var encrypted = new MemoryStream())
      using (var csOut = new CryptoStream(encrypted, aesEncryptor, CryptoStreamMode.Write))
      using (var gzipOut = new ZipOutputStream(csOut))
      {
          gzipOut.SetLevel(5);
          gzipOut.PutNextEntry(new ZipEntry("Zip Entry") { DateTime = DateTime.Now });
          source.CopyTo(gzipOut);
          gzipOut.Finish();
          csOut.FlushFinalBlock();
  
          var newSource = new MemoryStream(encrypted.ToArray());
          using (var decrypted = new MemoryStream())
          using (var aesDecryptor = aes.CreateDecryptor())
          using (var csIn = new CryptoStream(newSource, aesDecryptor, CryptoStreamMode.Read))
          using (var gzipIn = new ZipInputStream(csIn))
          {
              var entry = gzipIn.GetNextEntry();
              gzipIn.CopyTo(decrypted);
              var entry2 = gzipIn.GetNextEntry();
              Assert.That(source.ToArray(), Is.EqualTo(decrypted.ToArray()));
          }
      }
  }
```

### Exceptions (if any)
```
System.Security.Cryptography.CryptographicException
  HResult=0x80131430
  Message=Padding is invalid and cannot be removed.
  Source=System.Core
  StackTrace:
   at System.Security.Cryptography.CapiSymmetricAlgorithm.DepadBlock(Byte[] block, Int32 offset, Int32 count)
   at System.Security.Cryptography.CapiSymmetricAlgorithm.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at ICSharpCode.SharpZipLib.Zip.ZipInputStream.GetNextEntry()
```

### Further technical details
It appears there is a flag(_finalBlockTransformed) in Dispose method that doesn't get set in some cases and will cause this issue.

**Comment by vcsjones** [comment]
> CapiSymmetricAlgorithm

Based on this in your error stack, you are using .NET Framework.

I can't reproduce this in .NET 7. Are you able to reproduce this in .NET 6 or .NET 7?

I can reproduce this for .NET Framework. If you are reporting this issue for .NET Framework, then the issue should be reported at https://developercommunity.visualstudio.com/home.
