### ISSUE TITLE
[browser][MT] The WebSocket is not connected.

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#88084]
### Error Blob
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=395678&view=results

```json
{
  "ErrorMessage": "MONO_WASM: WebSocket error",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=395678
**Error message validated:** `MONO_WASM: WebSocket error`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/5/2023 5:51:29 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment]
Reproduced it locally on my system on MT build

```
[2023-07-27T10:02:04.641Z] [FAIL] System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.RequestDuration_CustomTags_Recorded
System.IO.IOException : Unable to write data to the transport connection
---- System.InvalidOperationException : The WebSocket is not connected.
   at System.Net.WebSockets.WebSocketStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\WebSockets\WebSocketStream.cs:line 233
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(Byte[] response) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 756
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseBodyAsync(Byte[] content, Boolean isFinal) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1000
   at System.Net.Test.Common.GenericLoopbackConnection.SendResponseBodyAsync(String content, Boolean isFinal) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\GenericLoopbackServer.cs:line 162
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(HttpStatusCode statusCode, IList`1 headers, String content, Boolean isFinal) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 960
   at System.Net.Test.Common.LoopbackServer.Connection.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1070
   at System.Net.Test.Common.LoopbackServer.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1103
   at System.Net.Test.Common.LoopbackServer.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1103
   at System.Net.Http.Functional.Tests.HttpMetricsTest.<>c.<<RequestDuration_CustomTags_Recorded>b__11_1>d.MoveNext() in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\MetricsTest.cs:line 301
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in C:\Dev\runtime\src\libraries\Common\tests\System\Threading\Tasks\TaskTimeoutExtensions.cs:line 90
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\GenericLoopbackServer.cs:line 39
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 107
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.WebSockets.BrowserWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.WebSockets.Client\src\System\Net\WebSockets\BrowserWebSockets\BrowserWebSocket.cs:line 153
   at System.Net.WebSockets.WebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.WebSockets\src\System\Net\WebSockets\WebSocket.cs:line 57
   at System.Net.WebSockets.ClientWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs:line 149
   at System.Net.WebSockets.WebSocketStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\WebSockets\WebSocketStream.cs:line 229

...


```

**Comment by pavelsavara** [comment]
Another

```
[2023-07-27T10:11:33.507Z] [FAIL] System.Net.Http.Functional.Tests.HttpClientHandlerTest_Url.TrimmingTrailingWhiteSpace(requestPath: "/test%20", expectedServerPath: "/test%20")
System.IO.IOException : Unable to write data to the transport connection
---- System.InvalidOperationException : The WebSocket is not connected.
   at System.Net.WebSockets.WebSocketStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\WebSockets\WebSocketStream.cs:line 233
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(Byte[] response) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 756
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseBodyAsync(Byte[] content, Boolean isFinal) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1000
   at System.Net.Test.Common.GenericLoopbackConnection.SendResponseBodyAsync(String content, Boolean isFinal) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\GenericLoopbackServer.cs:line 162
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(HttpStatusCode statusCode, IList`1 headers, String content, Boolean isFinal) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 960
   at System.Net.Test.Common.LoopbackServer.Connection.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1070
   at System.Net.Test.Common.LoopbackServer.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1103
   at System.Net.Test.Common.LoopbackServer.HandleRequestAsync(HttpStatusCode statusCode, IList`1 headers, String content) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 1103
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Url.<>c__DisplayClass1_0.<<TrimmingTrailingWhiteSpace>b__0>d.MoveNext() in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Url.cs:line 37
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\Http\LoopbackServer.cs:line 107
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Url.TrimmingTrailingWhiteSpace(String requestPath, String expectedServerPath) in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Url.cs:line 29
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.WebSockets.BrowserWebSocket.SendAsync(ArraySegment`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.WebSockets.Client\src\System\Net\WebSockets\BrowserWebSockets\BrowserWebSocket.cs:line 153
   at System.Net.WebSockets.WebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.WebSockets\src\System\Net\WebSockets\WebSocket.cs:line 57
   at System.Net.WebSockets.ClientWebSocket.SendAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs:line 149
   at System.Net.WebSockets.WebSocketStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\Dev\runtime\src\libraries\Common\tests\System\Net\WebSockets\WebSocketStream.cs:line 229
```

**Comment by pavelsavara** [comment]
This is slightly different, this is non-MT, [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89588-merge-ec6a3004971e477198/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.5e6bec72.log?helixlogtype=result)

```
[06:46:49] info: Process node exited with 1
                 
[06:46:49] info: Waiting to flush log messages with a timeout of 120 secs ..
[06:46:48] fail: RemoteLoopHandler.ProcessWebSocketRequest failed
                 System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
                  ---> Microsoft.AspNetCore.Connections.ConnectionResetException: Connection reset by peer
                  ---> System.Net.Sockets.SocketException (104): Connection reset by peer
                    --- End of inner exception stack trace ---
                    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
                    at System.IO.Pipelines.Pipe.GetReadAsyncResult()
                    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1UpgradeMessageBody.ReadAsyncInternalAwaited(ValueTask`1 readTask, CancellationToken cancellationToken)
                    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
                    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                    at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
                    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                    at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
                    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
                    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
                    at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
                    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
                    at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
                 --- End of stack trace from previous location ---
                    at RemoteLoopServer.RemoteLoopHandler.ProcessWebSocketRequest(HttpContext context, WebSocket control, ILogger logger) in /_/src/libraries/Common/tests/System/Net/Prerequisites/RemoteLoopServer/Handlers/RemoteLoopHandler.cs:line 53
[06:46:49] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by pavelsavara** [comment]
no hits
