### ISSUE TITLE
Native crash on System.Text.Json.SourceGeneration.Roslyn4.4.Tests net8.0-linux-Debug-arm64-Mono_release

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#88102]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=322652
Build error leg or test failing: System.Text.Json.SourceGeneration.Roslyn4.4.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/85378
Console log: https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-85378-merge-9106d2de4c074ca4a0/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/1/console.e281cc02.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-85378-merge-9106d2de4c074ca4a0/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/1/console.e281cc02.log?helixlogtype=result)

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Segmentation fault      (core dumped) \"$RUNTIME_PATH/dotnet\" exec --runtimeconfig System.Text.Json.SourceGeneration.Roslyn4.4.Tests.runtimeconfig.json --depsfile System.Text.Json.SourceGeneration.Roslyn4.4.Tests.deps.json xunit.console.dll System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[457353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457353)|dotnet/runtime|[System.Text.Json.SourceGeneration.Roslyn4.4.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457353&view=ms.vss-test-web.build-test-results-tab&runId=10300956&resultId=202226)|dotnet/runtime#94214|
|[448707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448707)|dotnet/runtime|[System.Text.Json.SourceGeneration.Roslyn4.4.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=448707&view=ms.vss-test-web.build-test-results-tab&runId=10051498&resultId=202091)|dotnet/runtime#93519|
|[444796](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444796)|dotnet/runtime|[System.Text.Json.SourceGeneration.Roslyn4.4.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444796&view=ms.vss-test-web.build-test-results-tab&runId=9946162&resultId=202063)|dotnet/runtime#90436|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|3|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=322652
**Error message validated:** `Segmentation fault      (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.SourceGeneration.Roslyn4.4.Tests.runtimeconfig.json --depsfile System.Text.Json.SourceGeneration.Roslyn4.4.Tests.deps.json xunit.console.dll System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 8:19:27 PM UTC

**Comment by buyaa-n** [comment]
Same failure happened in https://github.com/dotnet/runtime/pull/88851/checks?check_run_id=15108017335'From log:
```log
Starting:    System.Text.Json.SourceGeneration.Roslyn4.4.Tests (parallel test collections = on, max threads = 2)
Process terminated. Assertion failed.
Configure called directly, use EnsureConfigured which synchronizes access to this method
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 667
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 652
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 627
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 114
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 151
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 46
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 130
   at System.Text.Json.SourceGeneration.Tests.StringSerializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/Serialization/JsonSerializerWrapper.SourceGen.cs:line 42
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|14_0(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 33
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|14_0(String json, Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|14_3(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 53
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|14_3(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<>c__DisplayClass14_0.<MultipleThreads>b__8() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 76
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 501
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 264
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2349
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 58
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
/root/helix/work/workitem/e
./RunTests.sh: line 168:    25 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.SourceGeneration.Roslyn4.4.Tests.runtimeconfig.json --depsfile System.Text.Json.SourceGeneration.Roslyn4.4.Tests.deps.json xunit.console.dll System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
----- end Mon Jul 17 17:57:45 UTC 2023 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
ulimit -c value: unlimited
[ 4409.546122] docker0: port 1(vethdf6d6e3) entered disabled state
[ 4409.551554] device vethdf6d6e3 left promiscuous mode
```

**Comment by eiriktsarpalis** [comment]
Seems to have only had one occurrence in the past month. Moving to 9.0.0 since it doesn't appear to be blocking release.

**Comment by buyaa-n** [comment]
Again failed on https://github.com/dotnet/runtime/pull/93244/checks?check_run_id=18052534433
[Log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-93244-merge-8b427caa74254c80ad/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/1/console.0da57efd.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-93244-merge-8b427caa74254c80ad/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/1/console.0da57efd.log?helixlogtype=result)):
```
Process terminated. Assertion failed.
Configure called directly, use EnsureConfigured which synchronizes access to this method
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 667
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 652
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 627
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 152
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 42
   at System.Text.Json.JsonSerializer.DeserializeAsync(Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 133
   at System.Text.Json.SourceGeneration.Tests.AsyncStreamSerializerWrapper.DeserializeWrapper(Stream utf8Json, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/Serialization/JsonSerializerWrapper.SourceGen.cs:line 88
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.SourceGeneration.Tests.AsyncStreamSerializerWrapper.DeserializeWrapper(Stream utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.StreamingJsonSerializerWrapper.DeserializeWrapper(String json, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/StreamingJsonSerializerWrapper.cs:line 76
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.StreamingJsonSerializerWrapper.DeserializeWrapper(String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|15_0(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 33
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|15_0(String json, Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|15_3(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 53
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|15_3(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<>c__DisplayClass15_0.<MultipleThreads>b__8() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 76
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 264
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2349
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 102
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 104
./RunTests.sh: line 204:    25 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.SourceGeneration.Roslyn4.4.Tests.runtimeconfig.json --depsfile System.Text.Json.SourceGeneration.Roslyn4.4.Tests.deps.json xunit.console.dll System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

**Comment by kg** [comment]
Failed again on https://github.com/dotnet/runtime/pull/94446/checks?check_run_id=18427196268
Log: https://helix.dot.net/api/2019-06-17/jobs/e45850f6-4322-490d-885a-54dcb4ee5066/workitems/System.Text.Json.SourceGeneration.Roslyn4.4.Tests/console

```
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Text.Json.SourceGeneration.Roslyn4.4.Tests.runtimeconfig.json --depsfile System.Text.Json.SourceGeneration.Roslyn4.4.Tests.deps.json xunit.console.dll System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Text.Json.SourceGeneration.Roslyn4.4.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.SourceGeneration.Roslyn4.4.Tests (found 3718 of 3802 test cases)
  Starting:    System.Text.Json.SourceGeneration.Roslyn4.4.Tests (parallel test collections = on, max threads = 2)
Process terminated. Assertion failed.
Configure called directly, use EnsureConfigured which synchronizes access to this method
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 672
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 657
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 632
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 152
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 42
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 130
   at System.Text.Json.SourceGeneration.Tests.StringSerializerWrapper.DeserializeWrapper(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/Serialization/JsonSerializerWrapper.SourceGen.cs:line 42
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|15_0(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 33
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|15_0(String json, Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|15_3(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 53
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|15_3(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.ConstructorTests.<>c__DisplayClass15_0.<MultipleThreads>b__8() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 76
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 264
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2349
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 102
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 104
./RunTests.sh: line 204:    21 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.SourceGeneration.Roslyn4.4.Tests.runtimeconfig.json --depsfile System.Text.Json.SourceGeneration.Roslyn4.4.Tests.deps.json xunit.console.dll System.Text.Json.SourceGeneration.Roslyn4.4.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```
