### ISSUE TITLE
 System.ArgumentException: Stream does not support reading. (Parameter 'stream') when reading from HttpMessageResponse.Content.ReadAsStringAsync()

### ISSUE THREAD

**Issue by pschubert777** [dotnet/runtime#88198]
### Description

When logging the HttpRequest and Response, in intermittent circumstances the ReadAsStringAsync() method fails and produces the following exception

System.ArgumentException: Stream does not support reading. (Parameter 'stream')

The response that is retrieved is from a HTTP POST request that is sends and receives a XML request and response respectively. The response is compressed using gzip. The logging is done in the MessageFormatter which is a delegating handler see lines 87 and 100

The issue happens intermittently. The Http Request is being made in the Intacct.SDK (located below)

MessageFormatter - https://github.com/intacct/intacct-sdk-net/blob/master/Intacct.SDK/Logging/MessageFormatter.cs
RequestHandler - https://github.com/intacct/intacct-sdk-net/blob/master/Intacct.SDK/Xml/RequestHandler.cs
LoggingHandler https://github.com/intacct/intacct-sdk-net/blob/master/Intacct.SDK/Xml/LoggingHandler.cs

### Reproduction Steps

It happens intermittently

### Expected behavior

Not throw an error when calling HttpResponseMessage.Content.ReadAsStringAsync()

### Actual behavior

An error is thrown with the following Stack trace

```
 System.ArgumentException: Stream does not support reading. (Parameter 'stream')
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode)
   at System.Net.Http.DecompressionHandler.GZipDecompressedContent.GetDecompressedStream(Stream originalStream)
   at System.Net.Http.DecompressionHandler.DecompressedContent.TryCreateContentReadStream()
   at System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
```

**Full Stack Trace**

```
System.AggregateException:
at System.Threading.Tasks.Task.ThrowIfExceptional (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Threading.Tasks.Task1.GetResultCore (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Threading.Tasks.Task1.get_Result (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at Intacct.SDK.Logging.MessageFormatter+<>c__DisplayClass6_0.b__0 (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
at System.Text.RegularExpressions.Regex+<>c.b__84_0 (System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
at System.Text.RegularExpressions.RegexRunner.Scan (System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
at System.Text.RegularExpressions.Regex.Run (System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
at System.Text.RegularExpressions.Regex.Replace (System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
at System.Text.RegularExpressions.Regex.Replace (System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
at System.Text.RegularExpressions.Regex.Replace (System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
at Intacct.SDK.Logging.MessageFormatter.Format (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
at Intacct.SDK.Xml.LoggingHandler+d__4.MoveNext (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Net.Http.HttpClient+<<SendAsync>g__Core|83_0>d.MoveNext (System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at Intacct.SDK.Xml.RequestHandler+d__9.MoveNext (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at Intacct.SDK.Xml.RequestHandler+<ExecuteOnline>d__5.MoveNext (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at Intacct.SDK.AbstractClient+d__3.MoveNext (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at Intacct.SDK.OnlineClient+<ExecuteBatch>d__2.MoveNext (Intacct.SDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)  Inner exception System.ArgumentException handled at System.Threading.Tasks.Task.ThrowIfExceptional: at System.IO.Compression.DeflateStream..ctor (System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) at System.IO.Compression.GZipStream..ctor (System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) at System.IO.Compression.GZipStream..ctor (System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089) at System.Net.Http.DecompressionHandler+GZipDecompressedContent.GetDecompressedStream (System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) at System.Net.Http.DecompressionHandler+DecompressedContent.TryCreateContentReadStream (System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) at System.Net.Http.DecompressionHandler+DecompressedContent+<SerializeToStreamAsync>d__6.MoveNext (System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Net.Http.HttpContent+<LoadIntoBufferAsyncCore>d__63.MoveNext (System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult (System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e) at System.Net.Http.HttpContent+<WaitAndReturnAsync>d__822.MoveNext (System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
```

### Regression?

Not sure

### Known Workarounds

N/A

### Configuration

It has seemed to only have started to happen
Version: .NET 6
OS: Windows (Azure App Service)
The Azure App Service is a Function app that is running a Azure Durable Function in .NET 6.

### Other information

The thrown exception is coming from the DeflateStream when decompressing the response stream. See screenshot below

![image](https://github.com/dotnet/runtime/assets/44069136/bfc45585-f218-45b2-b69f-3b59f030a4a0)

**Comment by karelz** [comment]
@pschubert777 does it happen for the same response again? Or is it intermittent even for identical request+response combo?

**Comment by pschubert777** [comment]
> @pschubert777 does it happen for the same response again? Or is it intermittent even for identical request+response combo?

@karelz It is intermittent, it is happening either with the  Request or Response ReadAsStringAsync().  the ReadAsStringAsync() is called for both the  Request and Response in the LoggingHandler, Then in the RequestHandler, ReadAsStreamAsync() is called on the Response

**Comment by karelz** [comment]
@pschubert777 will it reproduce again when you add retries for this specific case?

**Comment by pschubert777** [comment]
> @pschubert777 will it reproduce again when you add retries for this specific case?

@karelz  yes it does reproduce when adding retries but intermittently. It also does it when a single request is sent successfully. I have attached a couple screenshots from Azure Application Insights that displays the failures. 

In the first screenshot, a total of three retries are made, the first two retries fail with a 502 error. On the last  one it is successful, but the System.ArgumentException arises from the MemoryStream not being readable when decompressing the gzip response


![image](https://github.com/dotnet/runtime/assets/44069136/0c5b55a0-d807-44ec-8bf1-9dde26cd615f)



In this one below, a successfuly request and response was returned but ended up with the same result. The System.ArgumentException was thrown due to the memoryStream not being readable when making the http call from the SDK

![image](https://github.com/dotnet/runtime/assets/44069136/a0acf3e2-904c-43e5-be11-fd1097621fdb)

**Comment by karelz** [comment]
Triage: Not a regression (reported against 6.0). Only 1 report so far, it may be specific to the app / environment.
Moving it to Future.

**Comment by karelz** [comment]
@pschubert777 sadly, it is not actionable with the info above. Can you try to create a repro (even if it takes time to hit it) for us to look at?
Alternatively, you can try to look at dumps if something pops up there ...
