### ISSUE TITLE
OOM on  System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawLargeJsonToStreamWithoutFlushing

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#88272]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=326554
Build error leg or test failing: System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawLargeJsonToStreamWithoutFlushing
Pull request: https://github.com/dotnet/runtime/pull/87335

    System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawLargeJsonToStreamWithoutFlushing [FAIL]
      System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Array.cs(63,0): at System.Array.Resize[T](T[]& array, Int32 newSize)
        /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs(200,0): at System.Buffers.ArrayBufferWriter`1.CheckAndResizeBuffer(Int32 sizeHint)
        /_/src/libraries/Common/src/System/Buffers/ArrayBufferWriter.cs(134,0): at System.Buffers.ArrayBufferWriter`1.GetMemory(Int32 sizeHint)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.cs(1069,0): at System.Text.Json.Utf8JsonWriter.Grow(Int32 requiredSize)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Raw.cs(266,0): at System.Text.Json.Utf8JsonWriter.WriteRawValueCore(ReadOnlySpan`1 utf8Json, Boolean skipInputValidation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Raw.cs(113,0): at System.Text.Json.Utf8JsonWriter.WriteRawValue(ReadOnlySpan`1 utf8Json, Boolean skipInputValidation)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Utf8JsonWriterTests.WriteRaw.cs(373,0): at System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawLargeJsonToStreamWithoutFlushing()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawMaxUtf16InputLength', Elapsed: 00:02:03

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawLargeJsonToStreamWithoutFlushing.*System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by eiriktsarpalis** [comment]
I'm also seeing `System.Text.Json.Tests.Utf8JsonWriterTests.WriteRawMaxUtf16InputLength` fail a couple of times with OOM in the same build. It all impacts Debug builds on Windows.

**Comment by eiriktsarpalis** [comment]
The test was disabled on Linux for similar reasons. I've posted https://github.com/dotnet/runtime/pull/89442 which disables it altogether.
