### ISSUE TITLE
`IOException: The system call level is not correct.` exception with `GetFiles` on a network share

### ISSUE THREAD

**Issue by michaelosthege** [dotnet/runtime#88334]
### Description

I have a program that monitors an SMB1 share (yes, I know, but it's a Windows Embedded device not under my control) for changes.

After upgrading from .NET Framework 4.6.1 to .NET 7, the line that does `Directory.GetFiles(@"\\192.168.162.132\Result", "*.csv", SearchOption.TopDirectoryOnly);` now raises `IOException: The system call level is not correct.`.`

The share can be accessed via the File Explorer just fine.

Also the following PowerShell command works:

```powershell
$result = [System.IO.Directory]::GetFiles("\\192.168.162.132\Result", "*.csv")
echo $result
```

### Configuration

* ClickOnce self-contained .NET 7.0 app
* OS Versions
  * Windows 10 Pro (en-US) Version 1909 Build 18363
  * Windows 10 Enterprise (en-US) Version 1607 (LTSB) Build 14393
  * One newer Windows 10 which doesn't have SMB1 installed (will follow-up with the exact version)
* All x64

### Regression?

Yes, it worked under .NET Framework 4.6.1.

### Other information

I tested two variants using `DirectoryInfo().GetFileSystemEntries()` which I had initially, and using `Directory.GetFiles()`:

```csharp
string[] variantOne = RemoteDirectory.EnumerateFileSystemInfos("*.csv", SearchOption.TopDirectoryOnly);
IEnumerable<FileSystemInfo> variantTwo = Directory.GetFiles(RemoteDirectory.FullName, "*.csv", SearchOption.TopDirectoryOnly);
```

The traceback is slightly different, but the underlying exception is identical:

```
System.IO.IOException: The system call level is not correct. : '\\\\192.168.162.132\\Result'
  at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()`
  at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()`
```

The German version is `Die Ebene des Systemaufrufs ist falsch.`.

On another machine with a newer Windows 10 installation, I got a different message:

```
IOException: You can't connect to the file share because it's not secure.
This share requires the obsolete SMB1 protocol, which is unsafe and could expose your system to attack.
Your system requires SMB2 or higher.
For more info on resolving this issue, see: https://go.microsoft.com/fwlink/?linkid=852747 : '\\\\192.168.162.132\\Result'
```

This makes me wonder:
__Was there a change between .NET Framework 4.6.1 → .NET 7 that might explain why accessing this SMB1 share no longer works?__

At this point I'm pretty much out of ideas, and any information on this would be very helpful, because my only escape route is to go back to out-of-support framework versions.

**Comment by adamsitnik** [comment]
Hi @michaelosthege 

I suspect that we have changed the sys-call that is being used to fetch files for given directory. Based on the analysis of your call-stack and our source code I believe that `NtQueryDirectoryFile` is the falling sys-call:

https://github.com/dotnet/runtime/blob/0a47ab064b53fa6dcd5a749be6563c3de1a04d7c/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Windows.cs#L86

[This](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/8549bd8e-3959-43fb-bae9-5b5d24a33232) doc describes `ERROR_INVALID_LEVEL` as:

> The value that is specified for the level parameter is invalid.

But [NtQueryDirectoryFile](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntquerydirectoryfile) does not mention a parameter called "level". It does mention that the callers must be running with specific IRQL level:

> Callers of NtQueryDirectoryFile must be running at IRQL = PASSIVE_LEVEL and [with special kernel APCs enabled](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/disabling-apcs).

The error you got on a different machine points to [this](https://learn.microsoft.com/en-US/windows-server/storage/file-server/troubleshoot/smbv1-not-installed-by-default-in-windows) doc which mentions which events are being logged in case of issues with SMB1. Could you please repro the issue and check what gets logged in the Event Log?

Moreover it mentions that SMB1 is deprecated, which means that we most likely won't fix it.

> SMB1 is deprecated and should not be installed nor enabled. 

FWIW I can see that some other OSS tools have special handling of this error, they seem to re-create the directory handle?

https://github.com/FarGroup/FarManager/blob/b8e8df24eac2ca28242540f216f04fef1500d7be/far/platform.fs.cpp#L417-L420

https://github.com/FarGroup/FarManager/blob/b8e8df24eac2ca28242540f216f04fef1500d7be/far/platform.fs.cpp#L424-L434

But I doubt it's the case here, as it would fail sometimes, not always.

cc @JeremyKuhne and @carlossanlop who might know more about changes in the implementaiton

**Comment by michaelosthege** [comment]
Thanks @adamsitnik for taking a look!

I reproduced it with a minimal console app published as self-contained:

<details><summary>Program.cs</summary>

```csharp
Console.WriteLine("Attempting to enumerate SMB2 share...");
try
{
    var files = Directory.GetFiles(@"\\192.168.162.129\Share\Software");
    Console.WriteLine("Success:" + string.Join('\n', files));
}
catch (Exception ex)
{
    Console.WriteLine($"Failed to enumerate: {ex}");
    await Task.Delay(5000);
    throw;
}

await Task.Delay(1000);

Console.WriteLine("Attempting to enumerate SMB1 share...");
try
{
    var files = Directory.GetFiles(@"\\192.168.162.132\Result");
    Console.WriteLine("Success:" + string.Join('\n', files));
}
catch (Exception ex)
{
    Console.WriteLine($"Failed to enumerate: {ex}");
    await Task.Delay(5000);
    throw;
}

await Task.Delay(5000);

```

</details>

It produced this EventLog entry:

<details><summary>EventLog entry</summary>

```
Log Name:      Application
Source:        Application Error
Date:          03/07/2023 16:47:59
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      IBT1003
Description:
Faulting application name: dotnetRuntimeIssue88334.exe, version: 1.0.0.0, time stamp: 0x638f960f
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0x67005c2a
Exception code: 0xe0434352
Fault offset: 0x00114402
Faulting process id: 0x1c30
Faulting application start time: 0x01d9adce157a8718
Faulting application path: \\ibt710\Share\Software\dotnetRuntimeIssue88334\dotnetRuntimeIssue88334.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 370256df-17e4-4827-bf36-bc52d2bb0b29
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-07-03T16:47:59.514213400Z" />
    <EventRecordID>471606</EventRecordID>
    <Channel>Application</Channel>
    <Computer>IBT1003</Computer>
    <Security />
  </System>
  <EventData>
    <Data>dotnetRuntimeIssue88334.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>638f960f</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.18362.815</Data>
    <Data>67005c2a</Data>
    <Data>e0434352</Data>
    <Data>00114402</Data>
    <Data>1c30</Data>
    <Data>01d9adce157a8718</Data>
    <Data>\\ibt710\Share\Software\dotnetRuntimeIssue88334\dotnetRuntimeIssue88334.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>370256df-17e4-4827-bf36-bc52d2bb0b29</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          03/07/2023 16:47:59
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      IBT1003
Description:
Application: dotnetRuntimeIssue88334.exe
CoreCLR Version: 7.0.222.60605
.NET Version: 7.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The system call level is not correct. : '\\192.168.162.132\Result'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at Program.<Main>$(String[] args) in C:\Users\osthege\Repos\dotnetRuntimeIssue88334\dotnetRuntimeIssue88334\Program.cs:line 25
   at Program.<Main>$(String[] args) in C:\Users\osthege\Repos\dotnetRuntimeIssue88334\dotnetRuntimeIssue88334\Program.cs:line 32
   at Program.<Main>(String[] args)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-07-03T16:47:59.398363100Z" />
    <EventRecordID>471605</EventRecordID>
    <Channel>Application</Channel>
    <Computer>IBT1003</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: dotnetRuntimeIssue88334.exe
CoreCLR Version: 7.0.222.60605
.NET Version: 7.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The system call level is not correct. : '\\192.168.162.132\Result'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at Program.&lt;Main&gt;$(String[] args) in C:\Users\osthege\Repos\dotnetRuntimeIssue88334\dotnetRuntimeIssue88334\Program.cs:line 25
   at Program.&lt;Main&gt;$(String[] args) in C:\Users\osthege\Repos\dotnetRuntimeIssue88334\dotnetRuntimeIssue88334\Program.cs:line 32
   at Program.&lt;Main&gt;(String[] args)
</Data>
  </EventData>
</Event>
```

</details>
