### ISSUE TITLE
Test failure: JIT/Methodical/NaN/intrinsic_cs_ro/intrinsic_cs_ro.dll

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#88451]
runtime-coreclr jitstress-random

win-arm64:
```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=312
```

linux-x64:
```
export DOTNET_TieredCompilation=0
export DOTNET_JitStress=ab
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=329904&view=ms.vss-test-web.build-test-results-tab

```
20:59:12.414 Running test: JIT/Methodical/NaN/intrinsic_cs_ro/intrinsic_cs_ro.dll
...
Tanh(NaN) == NaN  OK
System.Exception: Tanh(NaN) failed: expected -∞, got -1
   at Test_intrinsic.JitTest.Test.Fail(String func, Double arg, Double exp, Double res)
   at Test_intrinsic.JitTest.Test.TestEntryPoint()
=== FAILED ===
20:59:12.938 Failed test: JIT/Methodical/NaN/intrinsic_cs_ro/intrinsic_cs_ro.dll
```

@dotnet/jit-contrib

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress-random 20230723.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349291&view=ms.vss-test-web.build-test-results-tab&runId=7326632&resultId=108564&paneView=debug)

**Failed tests:**
```
coreclr osx x64 Checked jitstress_random_2 @ OSX.1200.Amd64.Open
    - JIT/Methodical/NaN/intrinsic_cs_ro/intrinsic_cs_ro.dll
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - JIT/Methodical/NaN/intrinsic_cs_do/intrinsic_cs_do.dll
```
**Error message:**
```
Assert.Equal() Failure
Expected: 100
Actual:   101
```

**Stack trace:**
```
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
   at Program.<<Main>$>g__TestExecutor85|0_86(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr jitstress-random 20230806.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364925&view=ms.vss-test-web.build-test-results-tab&runId=7716980&resultId=110705&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress_random_2 @ OSX.1200.ARM64.Open
    - JIT/Methodical/NaN/intrinsic_cs_do/intrinsic_cs_do.dll
```

**Error message:**
```
Assert.Equal() Failure
Expected: 100
Actual:   101
```

**Stack trace:**
```
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
   at Program.<<Main>$>g__TestExecutor84|0_85(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jakobbotsch** [comment]
This looks like a bug in constant folding:
```csharp
public static void Main()
{
    Console.WriteLine(Math.Tanh(double.NegativeInfinity));
    Console.WriteLine(Math.Tanh(NegativeInfinity()));
}

[MethodImpl(MethodImplOptions.NoInlining)]
private static double NegativeInfinity() => double.NegativeInfinity;
```
Result:
```scala
NaN
-1
```

JitStress causes us to inline the second `TestTanh` call which exposes the issue. Also, many of the `Fail` calls in this file are passing the wrong arguments to the wrong parameters, which gives very confusing output.
