### ISSUE TITLE
ConfigurationManager.GetSection("system.diagnostics") throws ConfigurationErrorsException on net6.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#88456]
### Description

Calling `ConfigurationManager.GetSection("system.diagnostics")` using the latest ConfigurationManager package throws on net6.0.  See below for details

### Reproduction Steps

Run attached project, targeting net6.0, referencing 7.0.0 ConfigurationManager.
```c#
using System.Configuration; 

var section = ConfigurationManager.GetSection("system.diagnostics");
Console.WriteLine(section?.GetType()?.AssemblyQualifiedName ?? "null");
```
[configDiagnosticsTest.zip](https://github.com/dotnet/runtime/files/11963200/configDiagnosticsTest.zip)

### Expected behavior

Succeeds and returns `null` or a valid section.

### Actual behavior

Throws:
```
Unhandled exception. System.Configuration.ConfigurationErrorsException: An error occurred creating the configuration section handler for system.diagnostics: Could not load type 'System.Diagnostics.SystemDiagnosticsSection' from assembly 'System.Configuration.ConfigurationManager'. (C:\scratch\configDiagnosticsTest\bin\Debug\net6.0\Config\machine.config line 10)
 ---> System.TypeLoadException: Could not load type 'System.Diagnostics.SystemDiagnosticsSection' from assembly 'System.Configuration.ConfigurationManager'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.GetConfigType(String typeName, Boolean throwOnError)
   at System.Configuration.Internal.DelegatingConfigHost.GetConfigType(String typeName, Boolean throwOnError)
   at System.Configuration.Internal.DelegatingConfigHost.GetConfigType(String typeName, Boolean throwOnError)
   at System.Configuration.TypeUtil.GetType(IInternalConfigHost host, String typeString, Boolean throwOnError)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.Init(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory..ctor(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
   at System.Configuration.RuntimeConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at Program.<Main>$(String[] args) in C:\scratch\configDiagnosticsTest\Program.cs:line 3
```

### Regression?

Yes, from 6.0.0 package.  Previously this would return null since the section was not registered.

Now System.Configuration.ConfigurationManger registers the section type as present in it's own assembly:
https://github.com/dotnet/runtime/blob/68b410f5b293a4cfa81f3db3a173c3459d5dd9de/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ImplicitMachineConfigHost.cs#L84

But it only defines that type in its `net7.0` and later build:
https://github.com/dotnet/runtime/blob/68b410f5b293a4cfa81f3db3a173c3459d5dd9de/src/libraries/System.Configuration.ConfigurationManager/src/System.Configuration.ConfigurationManager.csproj#L263-L269

### Known Workarounds

Don't call this method / catch the exception.  In the case of the report I looked it the call was coming from an older version of `System.Diagnostics.PerformanceCounter` and updating that package to 7.0.0 worked around the issue.
```xml
<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="7.0.0" />
```

### Configuration

.NET 6.0, windows x64.  Specific to .NET 6.0 and older - .NET 7.0 and later works and returns an instance of `SystemDiagnosticsSection`.

**Comment by ericstj** [comment]
I can imagine one of two fixes here - either `ifdef` out that registration of the `system.diagnostics` section so that it doesn't exist for net6.0 and earlier (to be consistent with the types defined only for 7.0+) or include the types in 6.0 as well.  I can't recall why we excluded those types from older frameworks -- did we depend on changes that weren't in a package? -- understanding that would probably need to go into the decision here.
