### ISSUE TITLE
IDictionary - ConcurrentDictionary TryAdd throws Exception

### ISSUE THREAD

**Issue by Flatscha** [dotnet/runtime#88461]
### Description

If 2 processes call TryAdd on the same dictionary TryAdd will throw the Exception on the second one
```
Exception Info: System.ArgumentException: The key already existed in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)
   at System.Collections.Generic.CollectionExtensions.TryAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, TValue value)
```

### Reproduction Steps

Create a dictionary 
        `IDictionary<string, object> Dict = new ConcurrentDictionary<string, object>();`
Start two tasks that call TryAdd onto that dictionary at the same time

### Expected behavior

TryAdd should not throw any Exceptions besides `ArgumentNullException`

### Actual behavior

TryAdd throws `System.ArgumentException: The key already existed in the dictionary.`

### Configuration

- Which version of .NET is the code running on? 
   **.NET 7.0**
- What OS and version, and what distro if applicable?
   **Windows 10 Enterprise / Windows 10 IoT / Windows Server 2016 Standard**
- What is the architecture (x64, x86, ARM, ARM64)?
   **x64**
- Do you know whether it is specific to that configuration?
  **I don't think so**
- If you're using Blazor, which web browser(s) do you see this issue in?
   **newest release of chrome**

### Other information

There should be a catch which returns false in the TryAdd method

**Comment by Tornhoof** [comment]
That's because ``TryAdd`` will be resolved as the extension method on IDictionary and that one basically calls ``ContainsKey`` and then ``Add``.
To use the ConcurrentDictionary one, don't cast your dictionary to IDictionary.
