### ISSUE TITLE
[wasm] Perf pipeline completely broken

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#88534]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2216141&view=results

```
$ pushd "/home/helixbot/work/B79109DE/w/AF9E097B/e/performance/artifacts/bin/for-running/MicroBenchmarks"
$ dotnet exec MicroBenchmarks.dll --anyCategories Libraries Runtime "" --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmEngine /home/helixbot/.jsvu/v8 "--wasmArgs=--expose_wasm --module " --cli /home/helixbot/work/B79109DE/p/dotnet/dotnet --wasmDataDir /home/helixbot/work/B79109DE/p/wasm-data --logBuildOutput --generateBinLog "" --partition-count 30 --partition-index 16 --artifacts /home/helixbot/work/B79109DE/w/AF9E097B/e/artifacts/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/B79109DE/w/AF9E097B/e/performance/artifacts/packages --runtimes wasmnet80 --buildTimeout 1200
Unhandled exception. System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.NullableContextAttribute' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at BenchmarkDotNet.Extensions.ReflectionExtensions.<>c.<GetBenchmarks>b__14_0(MethodInfo method)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at BenchmarkDotNet.Extensions.ReflectionExtensions.GetBenchmarks(TypeInfo typeInfo)
   at BenchmarkDotNet.Extensions.ReflectionExtensions.ContainsRunnableBenchmarks(Type type)
   at BenchmarkDotNet.Extensions.ReflectionExtensions.<>c.<GetRunnableBenchmarks>b__12_0(Type type)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at BenchmarkDotNet.Extensions.ReflectionExtensions.GetRunnableBenchmarks(Assembly assembly)
   at BenchmarkDotNet.Running.TypeFilter.GetTypesWithRunnableBenchmarks(IEnumerable`1 types, IEnumerable`1 assemblies, ILogger logger)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /home/helixbot/work/B79109DE/w/AF9E097B/e/performance/src/benchmarks/micro/Program.cs:line 43
```

Likely related to #87857 .

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
This will be fixed once we have an installer with https://github.com/dotnet/sdk/pull/33841 . But I will investigate to how it is failing for the wasm case, because we use a sdk with updated assemblies for running the benchmarks.

**Comment by radical** [comment]
This is no longer failing.
