### ISSUE TITLE
behavior of [:XX:] inside a regex range has changed

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#88587]
```c#
using System.Text.RegularExpressions;
using System;
namespace ConsoleApp13
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Regex.IsMatch("a", "[[:abc:]aaa]"));
            Console.WriteLine(Regex.IsMatch("a", "[[:abc:]"));
            Console.WriteLine(Regex.IsMatch("a", "[[::]"));
        }
    }
}
```
C:\Users\danmose\source\repos\ConsoleApp13>dotnet run -f net7.0
False
True
Unhandled exception. System.Text.RegularExpressions.RegexParseException: Invalid pattern '[[::]' at offset 5. Unterminated [] set.
   at System.Text.RegularExpressions.RegexParser.ScanCharClass(Boolean caseInsensitive, Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.CountCaptures(RegexOptions& optionsFoundInPattern)
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at ConsoleApp13.Program.Main(String[] args) in C:\Users\danmose\source\repos\ConsoleApp13\Program.cs:line 11

C:\Users\danmose\source\repos\ConsoleApp13>dotnet run -f net48
True

Unhandled Exception: System.ArgumentException: parsing "[[:abc:]" - Unterminated [] set.
   at System.Text.RegularExpressions.RegexParser.ScanCharClass(Boolean caseInsensitive, Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.CountCaptures()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at ConsoleApp13.Program.Main(String[] args) in C:\Users\danmose\source\repos\ConsoleApp13\Program.cs:line 10

```

This is because this line was accidentally deleted in .NET Core 3.1:

https://github.com/dotnet/corefx/pull/30632/files#diff-7ff2e84732300c51d80db48e484683bceed5a053305731fa906ab61d2e94950fL629

It would previously allow `[:XXX:]` where `XXX` is zero or more word chars and the whole is _inside a range_, and simply ignore it. So eg a pattern `[[:digit:]]` which is equivalent to `\d` in PCRE would be evaluated as `[]` an empty range. With the line removed, now it only ignores literally `[::]` in a range.

If this was an attempt to allow the possibility to add support later, it would have been made to reject patterns with these in, so that adding later wouldn't be a breaking change. The oldest copy I can find is from 2002/08/20 and it has "lookup name (nyi)" there too -- my guess is the nyi was intended to be fixed before .NET Framework 1.0.

My suggestion is to now remove this code entirely as it's useless. This would be a breaking change for anyone who has a pattern containing `[::]` inside a range -- which has to be almost literally zero.

**Comment by danmoseley** [comment]
Among engines that don't support this kind of range, Python and Javascript just treat a `[` inside a range as a literal. Java pushes a new bracket on the stack, which we don't support with or without colons.

We should just do the Python behavior. That would cause patterns to break where currently a literal `[::]` exists in a range (very improbable).
