### ISSUE TITLE
MissingMethodException in use of System.Text.Json since 8.0.0-preview.6.23329.7

### ISSUE THREAD

**Issue by NielsHoogeveen** [dotnet/runtime#88681]
### Since upgrading System.Text.Json to 8.0.0-preview.6.23329.7, I run into the following MissingMethodException.

 System.MissingMethodException: Method not found: 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable System.Threading.Tasks.Task.ConfigureAwait(System.Threading.Tasks.ConfigureAwaitOptions)'.
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
         at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsyncSlow[TValue](Stream body, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Builder.CircuitJavaScriptInitializationMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

This exception can be reproduced by creating a severside blazor app dotnet8 preview, and then install the latest prerelease version of System.Text.Json via the Nuget package manager .

**Comment by eiriktsarpalis** [comment]
Are you running the nuget package against a .NET 8 Preview version that's older than 6? That would explain the exception message you're seeing since newer STJ versions rely on this new API being present https://github.com/dotnet/runtime/pull/87067

**Comment by NielsHoogeveen** [comment]
> Are you running the nuget package against a .NET 8 Preview version that's older than 6? That would explain the exception message you're seeing since newer STJ versions rely on this new API being present #87067

I ran it earlier today, when the Nuget packages were available, but the .NET 8 Preview version was still at 5. I am downloading the latest version of Visual Studio preview now, as well as the .NET 8 Preview version 6, as we speak. Once those have been installed, I will check if the problem has been resolved and let you know.

**Comment by NielsHoogeveen** [comment]
Installing .NET 8 Preview 6 solves the problem. I should have been a bit less eager to upgrade my Nuget Packages.
