### ISSUE TITLE
`DynamicallyAccessedMembersAnalyzer` throws for `InlineArrayAccessOperation`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#88684]
As per the title, the `DynamicallyAccessedMembersAnalyzer` currently throws when encountering an `InlineArrayAccessOperation`:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer' threw an exception of type 'System.NotImplementedException' with message 'Microsoft.CodeAnalysis.Operations.InlineArrayAccessOperation: D:\Users\tagoo\source\repos\terrafx.interop.windows\samples\DirectX\D3D12\HelloConstBuffer12.cs: (177,8)-(177,29)'.
Exception occurred with following context:
Compilation: TerraFX.Samples.DirectX
ISymbol: CreatePipelineState (Method)

System.NotImplementedException: Microsoft.CodeAnalysis.Operations.InlineArrayAccessOperation: D:\Users\tagoo\source\repos\terrafx.interop.windows\samples\DirectX\D3D12\HelloConstBuffer12.cs: (177,8)-(177,29)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitSimpleAssignment(ISimpleAssignmentOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.VisitExpressionStatement(IExpressionStatementOperation operation, LocalDataFlowState`2 state)
   at ILLink.RoslynAnalyzer.DataFlow.OperationWalker`2.Visit(IOperation operation, TArgument argument)
   at ILLink.RoslynAnalyzer.TrimAnalysis.TrimAnalysisVisitor.Visit(IOperation operation, LocalDataFlowState`2 argument)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.Transfer(BlockProxy block, LocalDataFlowState`2 state)
   at ILLink.Shared.DataFlow.ForwardDataFlowAnalysis`7.Fixpoint(TControlFlowGraph cfg, TLattice lattice, TTransfer transfer)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowAnalysis`3.AnalyzeMethod(MethodBodyValue method, InterproceduralState`2& interproceduralState)
   at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowAnalysis`3.InterproceduralAnalyze()
   at ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer.<>c.<Initialize>b__8_1(OperationBlockAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__54`1.<ExecuteBlockActions>b__54_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: IL2026, IL2032, IL2041, IL2043, IL2055, IL2057, IL2058, IL2059, IL2060, IL2062, IL2063, IL2064, IL2065, IL2066, IL2067, IL2068, IL2069, IL2070, IL2071, IL2072, IL2073, IL2074, IL2075, IL2076, IL2077, IL2078, IL2079, IL2080, IL2081, IL2082, IL2083, IL2084, IL2085, IL2086, IL2087, IL2088, IL2089, IL2090, IL2091, IL2092, IL2093, IL2094, IL2095, IL2096, IL2097, IL2098, IL2099, IL2103, IL2106, IL2110, IL2111	TerraFX.Samples.DirectX (net8.0)	D:\Users\tagoo\source\repos\terrafx.interop.windows\samples\DirectX\TerraFX.Samples.DirectX.csproj	1	Active
```

**Comment by vitek-karas** [comment]
@tannergooding do you have the piece of code which triggers this? `D:\Users\tagoo\source\repos\terrafx.interop.windows\samples\DirectX\D3D12\HelloConstBuffer12.cs: (177,8)-(177,29)`

**Comment by tannergooding** [comment]
@vitek-karas: Sorry, thought I included the simplified repro steps...

It triggers for any code similar to:
```csharp
using System.Runtime.CompilerServices;

var myStruct = new MyStruct();
myStruct.Buffer[0] = 5; // AD0001

public struct MyStruct
{
    public FixedBuffer Buffer;

    [InlineArray(8)]
    public partial struct FixedBuffer
    {
        public int e0;
    }
}
```

Just make sure the project includes:
```xml
<TargetFramework>net8.0</TargetFramework>
<LangVersion>preview</LangVersion>
<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
```

**Comment by vitek-karas** [comment]
Thanks for reporting this @tannergooding .

Unfortunately it's going to be tricky to implement right now, as there's no good way to write tests. Runtime repo is still on Preview 5 which doesn't have the compiler changes to support this feature. In theory we could upgrade the compiler version for this, but that seems unnecessary. We will have to wait for the repo to upgrade to Preview 6 which seems to have the necessary compiler support.

While looking into this I came up with some tests which would be interesting to add:
```C#
		class InlineArrayTest
		{
			[InlineArray (5)]
			struct PrimitiveTypeArray
			{
				public BindingFlags value;
			}

			static void AccessPrimitiveTypeArray ()
			{
				PrimitiveTypeArray a = new PrimitiveTypeArray ();
				ref var item = ref a[1];
				item = BindingFlags.Public;

				typeof (InlineArrayTest).GetProperty (nameof (TestProperty), a[1]);
			}

			[InlineArray (5)]
			struct UnannotatedTypeArray
			{
				public Type value;
			}

			static void AccessUnannotatedTypeArray ()
			{
				UnannotatedTypeArray a = new UnannotatedTypeArray ();
				ref var item = ref a[2];
				item = typeof (InlineArrayTest);

				a[2].GetProperty (nameof (TestProperty));
			}

			[InlineArray (5)]
			struct AnnotatedTypeArray
			{
				[DynamicallyAccessedMembers (DynamicallyAccessedMemberTypes.PublicProperties)]
				public Type value;
			}

			static void AccessAnnotatedTypeArray ()
			{
				AnnotatedTypeArray a = new AnnotatedTypeArray ();
				ref var item = ref a[3];
				item = typeof (InlineArrayTest);

				a[3].GetProperty (nameof (TestProperty));
			}

			public static void Test ()
			{
				AccessPrimitiveTypeArray ();
				AccessUnannotatedTypeArray ();
				AccessAnnotatedTypeArray ();
			}

			public int TestProperty { get; set; }
		}
```

These will have to be modified as I would expect warnings to be generated for the TypeArray cases.

**Comment by vitek-karas** [comment]
This brings an interesting topic of interactions between inline arrays and data flow annotations. Technically:
```C#
[InlineArray(5)]
struct MyTypes
{
    [DynamicallyAccessedMembers(PublicProperties)]
    public Type type;
}

void Test(MyType myTypes)
{
    myTypes[2].GetProperty("Name"); // This should not warn, since the value is annotated.

    myType[2] = typeof(TestType); // This should apply the annotations to TestType

    // And so on
}
```

This would require implementing intrinsic knowledge of inline arrays into data flow analysis of all trimming tools.
I'd argue we should not implement that right now, I simply don't see anybody doing something like this, and if they do, that's going to be very rare. I think it's OK to leave this as an analysis hole (most of the type it will actually produce warnings where it should not) ... for now.

That's not to say we should not fix the analyzer to not crash on this - we must do that.

**Comment by tannergooding** [comment]
> Unfortunately it's going to be tricky to implement right now, as there's no good way to write tests

Is there anything short term we can do to help ensure the analyzer doesn't throw and completely fail for unrecognized operation kinds? Can we, for example, mark such cases as a warning and gracefully continue on the next type/method?

**Comment by vitek-karas** [comment]
https://github.com/dotnet/runtime/pull/88836 has fixes to make the analyzer ignore unrecognized nodes (we discussed this and there's no good way to do this other than make the analyzer resistant to unknown inputs).

I'll keep this issue opened to track adding tests and to figure out the annotation interaction question I posted above.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/runtime/pull/88836 is now merged - as noted above I'll keep the issue active to track adding tests.
