### ISSUE TITLE
[7.0] Linux_bionic arm64 failure in Convert.cs causing FormatException in System.Diagnostics.Process tests

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#88756]
### Error Blob

```json
{
  "ErrorMessage": "FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Here's where the exception is being thrown in 7.0: https://github.com/dotnet/runtime/blob/d80211655317d5c243b882edfcdc2b16035bb40c/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L2906

- PR: https://github.com/dotnet/runtime/pull/88652
- Queue: `Build Linux_bionic arm64 Release AllSubsets_Mono`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356&view=logs&j=ab4fc4e5-ef33-5032-da89-7ee95c39b814&t=07cac0ba-4c44-502d-ba5a-d68e21dab793&l=62
- Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-77a8ac66f4cb447ca0/System.Diagnostics.Process.Tests/1/console.0511117b.log?helixlogtype=result
- Callstack (the [FAIL] output seemed to be printed out of order, at the end):
```
[21:02:20] dbug: Exit code: 1
                 Std out:
                   Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
                   Discovered:  System.Diagnostics.Process.Tests (found 257 of 317 test cases)
                   Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 8)
                       System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
                       Stack Trace:
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2906,0): at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2836,0): at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2643,0): at System.Convert.FromBase64String(String s)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.<>c.<ExecuteProcessAndReturnParsedOutput>b__9_0(String s)
                         /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs(83,0): at System.Linq.Enumerable.SelectArrayIterator`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
                         /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(17,0): at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ExecuteProcessAndReturnParsedOutput(Dictionary`2 envVars, Func`1 processWork)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(289,0): at System.Diagnostics.Tests.ProcessStartInfoTests.EnvironmentGetEnvironmentVariablesIsCaseSensitive()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                       System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
                       Stack Trace:
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2906,0): at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2836,0): at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2643,0): at System.Convert.FromBase64String(String s)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.<>c.<ExecuteProcessAndReturnParsedOutput>b__9_0(String s)
                         /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs(83,0): at System.Linq.Enumerable.SelectArrayIterator`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
                         /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(17,0): at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ExecuteProcessAndReturnParsedOutput(Dictionary`2 envVars, Func`1 processWork)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(336,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentVariablesDoesNotThrowForCaseSensitiveDuplicates()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                       System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
                       Stack Trace:
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2906,0): at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2836,0): at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2643,0): at System.Convert.FromBase64String(String s)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.<>c.<ExecuteProcessAndReturnParsedOutput>b__9_0(String s)
                         /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs(83,0): at System.Linq.Enumerable.SelectArrayIterator`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
                         /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(17,0): at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ExecuteProcessAndReturnParsedOutput(Dictionary`2 envVars, Func`1 processWork)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(312,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentDoesNotThrowForCaseSensitiveDuplicates()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
                     System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
                       Condition(s) not met: "IsWindowsNanoServer"

                   Finished:    System.Diagnostics.Process.Tests
                 === TEST EXECUTION SUMMARY ===
                    System.Diagnostics.Process.Tests  Total: 319, Errors: 0, Failed: 3, Skipped: 6, Time: 50.317s
                 
                 
                 Std err:
                     System.Diagnostics.Tests.ProcessStartInfoTests.EnvironmentGetEnvironmentVariablesIsCaseSensitive [FAIL]
                     System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentVariablesDoesNotThrowForCaseSensitiveDuplicates [FAIL]
                     System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentDoesNotThrowForCaseSensitiveDuplicates [FAIL]

```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[661457](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661457)|dotnet/runtime|[System.Diagnostics.Process.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=661457&view=ms.vss-test-web.build-test-results-tab&runId=16393732&resultId=206567)|dotnet/runtime#101732|
|[659984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659984)|dotnet/runtime|[System.Diagnostics.Process.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=659984&view=ms.vss-test-web.build-test-results-tab&runId=16352134&resultId=166966)||
|[647537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=647537)|dotnet/runtime|[System.Diagnostics.Process.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=647537&view=ms.vss-test-web.build-test-results-tab&runId=15995314&resultId=171628)||
|[644871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644871)|dotnet/runtime|[System.Diagnostics.Process.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=644871&view=ms.vss-test-web.build-test-results-tab&runId=15909018&resultId=171213)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|4|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=336356
**Error message validated:** `FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/12/2023 6:05:51 PM UTC

**Comment by vitek-karas** [comment]
This looks basically like the same problem in main here: https://github.com/dotnet/runtime/issues/76333 - since we're closing 7.0, I'm going to close this in favor of the main bug.
