### ISSUE TITLE
Virtual Static Method Default Interface Method Reabstraction does not work on Mono

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#88775]
### Description

New test added as part of PR #88711 

### Reproduction Steps

Run the src/tests/Loader/classloader/StaticVirtualMethods/Reabstraction/Reabstraction/Reabstraction.ilproj test on a Mono platform.

### Expected behavior

Test passes

### Actual behavior

Test fails

```
Unhandled Exception:
Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.EntryPointNotFoundException)
Actual:   typeof(System.BadImageFormatException): Bad IL format.
at VirtualStaticMethodReabstraction.Call[BarStruct](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336233&view=ms.vss-test-web.build-test-results-tab&runId=6984112&resultId=111993&paneView=debug)
at VirtualStaticMethodReabstraction.<>c.<Main>b__0_0()
at Xunit.Assert.RecordException(Action testCode) in //src/xunit.assert/Asserts/Record.cs:line 33
[ERROR] FATAL UNHANDLED EXCEPTION: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.EntryPointNotFoundException)
Actual:   typeof(System.BadImageFormatException): Bad IL format.
at VirtualStaticMethodReabstraction.Call[BarStruct](https://dev.azure.com/dnceng-public/public/_build/results?buildId=336233&view=ms.vss-test-web.build-test-results-tab&runId=6984112&resultId=111993&paneView=debug)
at VirtualStaticMethodReabstraction.<>c.<Main>b__0_0()
at Xunit.Assert.RecordException(Action testCode) in //src/xunit.assert/Asserts/Record.cs:line 33


Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Loader.classloader/StaticVirtualMethods/Reabstraction/Reabstraction/Reabstraction.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true Reabstraction.dll ''
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 7/12/2023 2:14:35 AM
Test Harness Exitcode is : 1
To run the test:



set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/Loader/classloader/StaticVirtualMethods/Reabstraction/Reabstraction/Reabstraction.sh
Expected: True
Actual:   False

```

### Regression?

No

**Comment by SamMonoRT** [comment]
cc @lambdageek

**Comment by lewing** [comment]
cc @steveisok

**Comment by lewing** [comment]
@lambdageek @vargaz
