### ISSUE TITLE
Test failure System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88889]
**Failed in:**  [runtime-coreclr libraries-jitstress 20230713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338141&view=ms.vss-test-web.build-test-results-tab&runId=7036114&resultId=165800&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
```

**Error message:**
```
System.Net.Mail.SmtpException : Failure sending mail.
---- System.IO.IOException : Unable to read data from the transport connection: The connection was closed.
```

**Stack trace:**
```
   at System.Net.Mail.SmtpClient.Send(MailMessage message) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 531
   at System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 572
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
----- Inner Stack Trace -----
   at System.Net.Mail.SmtpReplyReaderFactory.ProcessRead(Byte[] buffer, Int32 offset, Int32 read, Boolean readLine) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpReplyReaderFactory.cs:line 114
   at System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpReplyReaderFactory.cs:line 323
   at System.Net.Mail.SmtpConnection.GetConnection(String host, Int32 port) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 280
   at System.Net.Mail.SmtpTransport.GetConnection(String host, Int32 port) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs:line 114
   at System.Net.Mail.SmtpClient.Send(MailMessage message) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 491
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-05-03T07:34:51.35Z | runtime-coreclr libraries-jitstress | Release | ubuntu.1804.amd64.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication | Failed | {"AzurePipelinesTestRunId":"5100440","DefinitionId":"138","System.JobName":"__default","BuildNumber":"20230503.1","System.JobAttempt":"1","DefinitionName":"runtime-coreclr libraries-jitstress","System.PhaseAttempt":"1","System.StageAttempt":"1","configuration":"Release","scenario":"jitstress1","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"260461","System.PhaseName":"libraries_test_run_checked_coreclr_linux_x64_Release","architecture":"x64","Reason":"Schedule","Project":"public","runtimeFlavor":"coreclr","System.StageName":"Build","System.JobId":"fe27627b-bd13-56b8-97c3-9bb28451d0b9","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule

**Comment by jakobbotsch** [comment]
Likely the same situation as https://github.com/dotnet/runtime/issues/88890#issuecomment-1636331713 -- the test passed in the next run, so going to close.
