### ISSUE TITLE
Test failure System.Runtime.InteropServices.Tests.SafeBufferTests.ReadWrite_RoundTrip

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88887]
**Failed in:**  [runtime-coreclr libraries-jitstress 20230713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338141&view=ms.vss-test-web.build-test-results-tab&runId=7036114&resultId=126935&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open
    - System.Runtime.InteropServices.Tests.SafeBufferTests.ReadWrite_RoundTrip
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.11.Arm64.Open
    - System.Runtime.InteropServices.Tests.SafeBufferTests.ReadWrite_RoundTrip
    - System.Buffers.Binary.Tests.BinaryReaderUnitTests.ReadingStructFieldByFieldOrReadAndReverseEndianness
net8.0-linux-Release-arm64-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.Runtime.InteropServices.Tests.SafeBufferTests.ReadWrite_RoundTrip
    - System.Buffers.Binary.Tests.BinaryReaderUnitTests.ReadingStructFieldByFieldOrReadAndReverseEndianness
```

**Error message:**
```
Assert.Equal() Failure
Expected: System.Runtime.InteropServices.Tests.SafeBufferTests+TestStruct
Actual:   System.Runtime.InteropServices.Tests.SafeBufferTests+TestStruct
```

**Stack trace:**
```
   at System.Runtime.InteropServices.Tests.SafeBufferTests.ReadWrite_RoundTrip() in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/SafeBufferTests.cs:line 166
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by jakobbotsch** [comment]
Likely same situation as https://github.com/dotnet/runtime/issues/88890#issuecomment-1636331713 -- the test passed in the next run, so going to close.
