### ISSUE TITLE
Test failure Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParamsVariousFormsDynamicallyDeducedTypes

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88891]
**Failed in:** [runtime-coreclr libraries-jitstress 20230713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338141&view=ms.vss-test-web.build-test-results-tab&runId=7036228&resultId=103256&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.11.Arm64.Open
    - Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParamsVariousFormsDynamicallyDeducedTypes
```

**Error message:**
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: 1 2. 2 3. 3 4,5. 4 . 
Actual:         Assert.Equal() Failure\r\n      Expec···
          ↑ (pos 0)
```

**Stack trace:**
```
   at Microsoft.CSharp.RuntimeBinder.Tests.Helpers.OverrideConsoleAndRun(Action`1 command) in /_/src/libraries/Microsoft.CSharp/tests/Helpers.cs:line 19
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by jakobbotsch** [comment]
Likely the same situation as https://github.com/dotnet/runtime/issues/88890#issuecomment-1636331713 -- the test passed in the next run, so going to close.
