### ISSUE TITLE
Test failure System.Diagnostics.Metrics.Tests.AggregationStoreTests.GetThreeLabel

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88890]
**Failed in:** [runtime-coreclr libraries-jitstress 20230713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338141&view=ms.vss-test-web.build-test-results-tab&runId=7036114&paneView=debug&resultId=172993)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open
    - System.Diagnostics.Metrics.Tests.AggregationStoreTests.GetThreeLabel
    - System.Diagnostics.Metrics.Tests.AggregationStoreTests.GetNoLabels
```

**Error message:**
```
Assert.NotNull() Failure
```

**Stack trace:**
```
   at System.Diagnostics.Metrics.Tests.AggregationStoreTests.GetThreeLabel() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/AggregationManagerTests.cs:line 183
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by jakobbotsch** [comment]
Double checked and this one was broken by #88665 and fixed by #88669.
