### ISSUE TITLE
Test failure Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SafelyDisposeNestedProviderReferences

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88895]
**Failed in:** [runtime-coreclr libraries-jitstress 20230713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338141&view=ms.vss-test-web.build-test-results-tab&runId=7036114&resultId=101775&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2-Windows.10.Amd64.Open
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SafelyDisposeNestedProviderReferences
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.LastServiceReplacesPreviousServices
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ScopedServiceCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.InterfaceConstrainedOpenGenericServicesCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.NestedScopedServiceCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SingletonServicesComeFromRootProvider
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.OpenGenericServicesCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ClosedServicesPreferredOverOpenGenericServices
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.MultipleServiceCanBeIEnumerableResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.FactoryServicesCanBeCreatedByGetService
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.FactoryServicesAreCreatedAsPartOfCreatingObjectGraph
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.NestedScopedServiceCanBeResolvedWithNoFallbackProvider
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SingleServiceCanBeIEnumerableResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.AbstractClassConstrainedOpenGenericServicesCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.OuterServiceCanHaveOtherServicesInjected
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ResolvingEnumerableContainingOpenGenericServiceUsesCorrectSlot
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ServicesRegisteredWithImplementationType_ReturnDifferentInstancesPerResolution_ForTransientServices
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.TransientServiceCanBeResolvedFromScope
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.GetServiceOrCreateInstanceRegisteredServiceTransient
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ServicesRegisteredWithImplementationType_ReturnSameInstancesPerResolution_ForSingletons
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.TransientServiceCanBeResolvedFromProvider
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ServicesRegisteredWithImplementationTypeCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.RegistrationOrderIsPreservedWhenServicesAreIEnumerableResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.GetServiceOrCreateInstanceRegisteredServiceSingleton
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ConstrainedOpenGenericServicesCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ConstrainedOpenGenericServicesReturnsEmptyWithNoMatches
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ScopedServices_FromCachedScopeFactory_CanBeResolvedAndDisposed
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.GetServiceOrCreateInstanceUnregisteredService
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SingletonServiceCanBeResolvedFromScope
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SingletonServiceCanBeResolved
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.DisposingScopeDisposesService
    - Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.ScopesAreFlatNotHierarchical
    - System.Text.RegularExpressions.Tests.RegexMatchTests.Match
    - System.Text.RegularExpressions.Tests.AttRegexTests.Test
    - System.Text.RegularExpressions.Tests.RegexPcre2Tests.IsMatchTests
    - System.Text.RegularExpressions.Tests.RegexRustTests.MatchStartAndEndPositions
    - System.Text.RegularExpressions.Tests.RegexGroupTests.Groups
    - System.Text.RegularExpressions.Tests.MonoTests.ValidateRegex
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_RepeatedSequenceOfNumbers
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_56bytes_HitsEdgeCaseForPaddingLength
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_127bytes_HitsEdgeCase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_AlphabetInUpperLowerCasesAndNumbers
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_Phrase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_64bytes_HitsEdgeCase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_55bytes_HitsEdgeCaseForPaddingLength
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_AlphabetInLowercase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_128bytes_HitsEdgeCase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_ThreeLetters
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_Empty
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_65bytes_HitsEdgeCase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_63bytes_HitsEdgeCase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_129bytes_HitsEdgeCase
    - System.Net.Security.Tests.MD4Tests.TryEncrypt_SingleLetter
    - System.Net.Security.Tests.NegotiateAuthenticationTests.RemoteIdentity_ThrowsOnDisposed
    - System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmCorrectExchangeTest
    - System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmSignatureTest
    - System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmIncorrectExchangeTest
    - System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmProtocolExampleTest
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Text.RegularExpressions.Tests.AttRegexTests.Test
    - System.Text.RegularExpressions.Tests.RegexGroupTests.Groups
```

**Error message:**
```
System.AggregateException : One or more errors occurred. (Failed to compare two elements in the array.)
---- System.InvalidOperationException : Failed to compare two elements in the array.
-------- System.NullReferenceException : Object reference not set to an instance of an object.
```

**Stack trace:**
```
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1895
   at Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.CreateServiceProviderImpl(IServiceCollection serviceCollection) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.External.Tests/Lamar.cs:line 22
   at Microsoft.Extensions.DependencyInjection.Specification.SkippableDependencyInjectionSpecificationTests.CreateServiceProvider(IServiceCollection serviceCollection) in /_/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.External.Tests/SkippableDependencyInjectionSpecificationTests.cs:line 26
   at Microsoft.Extensions.DependencyInjection.Specification.DependencyInjectionSpecificationTests.SafelyDisposeNestedProviderReferences() in /_/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs:line 586
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
----- Inner Stack Trace -----
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/ArraySortHelper.cs:line 67
   at System.Text.RegularExpressions.RegexFindOptimizations.FindFixedDistanceString(List`1 fixedDistanceSets) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexFindOptimizations.cs:line 272
   at System.Text.RegularExpressions.RegexFindOptimizations..ctor(RegexNode root, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexFindOptimizations.cs:line 147
   at System.Text.RegularExpressions.RegexTree..ctor(RegexNode root, Int32 captureCount, String[] captureNames, Hashtable captureNameToNumberMapping, Hashtable captureNumberSparseMapping, RegexOptions options, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexTree.cs:line 80
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs:line 131
   at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 76
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.Cache.cs:line 125
   at LamarCodeGeneration.Util.StringExtensions.SplitCamelCase(String str)
   at LamarCodeGeneration.Model.Variable.DefaultArgName(Type argType)
   at Lamar.IoC.Instances.ConstructorInstance..ctor(Type serviceType, Type implementationType, ServiceLifetime lifetime)
   at Lamar.IoC.Instances.Instance.For(ServiceDescriptor service)
   at System.Linq.Enumerable.SelectIListIterator`2.Fill(IList`1 source, Span`1 results, Func`2 func) in /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 426
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray() in /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 408
   at Lamar.ServiceGraph.buildFamilyForInstanceGroup(IServiceCollection services, IGrouping`2 group)
   at Lamar.ServiceGraph.<>c__DisplayClass36_0.<organizeIntoFamilies>b__2(IGrouping`2 group)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 135
   at LamarCodeGeneration.Util.EnumerableExtensions.Each[T](IEnumerable`1 v
```

**Comment by jakobbotsch** [comment]
Likely the same situation as https://github.com/dotnet/runtime/issues/88890#issuecomment-1636331713 -- the test passed in the next run, so going to close.
