### ISSUE TITLE
[browser][nodejs] RequestDuration_CustomTags_Recorded - ENOENT: no such file or directory, open 'http://127.0.0.1:45051/'

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#88900]
remote Loopback issue on NodeJS

```
[19:38:28] fail: [FAIL] System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.RequestDuration_CustomTags_Recorded
[19:38:28] info: System.Net.Http.HttpRequestException : Error: ENOENT: no such file or directory, open 'http://127.0.0.1:45051/'
[19:38:28] info: ---- System.Runtime.InteropServices.JavaScript.JSException : Error: ENOENT: no such file or directory, open 'http://127.0.0.1:45051/'
[19:38:28] info:    at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
[19:38:28] info:    at System.Net.Http.BrowserHttpContent.GetResponseData(CancellationToken cancellationToken)
[19:38:28] info:    at System.Net.Http.BrowserHttpContent.<SerializeToStreamAsync>g__Impl|7_0(BrowserHttpContent self, Stream stream, CancellationToken cancellationToken)
[19:38:28] info:    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
[19:38:28] info:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[19:38:28] info:    at System.Net.Http.Functional.Tests.HttpMetricsTest.<RequestDuration_CustomTags_Recorded>b__11_0(Uri uri)
[19:38:28] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[19:38:28] info: --- End of stack trace from previous location ---
[19:38:28] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[19:38:28] info:    at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[19:38:28] info: --- End of stack trace from previous location ---
[19:38:28] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[19:38:28] info: --- End of stack trace from previous location ---
[19:38:28] info: ----- Inner Stack Trace -----
[19:38:28] info:    at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
```

```
[19:38:37] fail: [FAIL] System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.RequestDuration_EnrichmentHandler_ContentLengthError_Recorded
[19:38:37] info: Assert.Equal() Failure
[19:38:37] info: Expected: 200
[19:38:37] info: Actual:   500
[19:38:37] info:    at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyOptionalTag[Nullable`1](KeyValuePair`2[] tags, String name, Nullable`1 value)
[19:38:37] info:    at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(Measurement`1 measurement, Uri uri, String protocol, Nullable`1 statusCode, String method)
[19:38:37] info:    at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.<RequestDuration_EnrichmentHandler_ContentLengthError_Recorded>b__3_0(Uri uri)
[19:38:37] info:    at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
[19:38:37] info: --- End of stack trace from previous location ---
[19:38:37] info:    at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
[19:38:37] info:    at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
[19:38:37] info: --- End of stack trace from previous location ---
[19:38:37] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[19:38:37] info:    at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.RequestDuration_EnrichmentHandler_ContentLengthError_Recorded()
[19:38:37] info: --- End of stack trace from previous location ---
```

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-88387-merge-ce8294c2991d4c4fab/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.b4125c53.log?helixlogtype=result)

Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=338789&view=results

## Error Message

```json
{
    "ErrorMessage": "System.Net.Http.HttpRequestException : Error: ENOENT: no such file or directory, open",
    "BuildRetry": false,
    "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[350621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350621)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350621&view=ms.vss-test-web.build-test-results-tab&runId=7359894&resultId=105291)|dotnet/runtime#89387|
|[350096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350096)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350096&view=ms.vss-test-web.build-test-results-tab&runId=7350258&resultId=105320)|dotnet/runtime#88052|
|[350086](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350086)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350086&view=ms.vss-test-web.build-test-results-tab&runId=7349920&resultId=105291)|dotnet/runtime#89387|
|[348658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348658)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348658&view=ms.vss-test-web.build-test-results-tab&runId=7309058&resultId=105493)|dotnet/runtime#88052|
|[347032](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347032)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=347032&view=ms.vss-test-web.build-test-results-tab&runId=7266558&resultId=105427)|dotnet/runtime#88929|
|[340459](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340459)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340459&view=ms.vss-test-web.build-test-results-tab&runId=7099388&resultId=185379)|dotnet/runtime#88929|
|[340384](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340384)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340384&view=ms.vss-test-web.build-test-results-tab&runId=7097060&resultId=105416)|dotnet/runtime#88387|
|[339571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339571)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339571&view=ms.vss-test-web.build-test-results-tab&runId=7084306&resultId=185364)|dotnet/runtime#88052|
|[339570](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339570)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339570&view=ms.vss-test-web.build-test-results-tab&runId=7077784&resultId=185364)|dotnet/runtime#88387|
|[339390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339390)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339390&view=ms.vss-test-web.build-test-results-tab&runId=7072068&resultId=185364)|dotnet/runtime#88883|
|[339072](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339072)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=339072&view=ms.vss-test-web.build-test-results-tab&runId=7062168&resultId=185354)|dotnet/runtime#88505|
|[338789](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338789)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338789&view=ms.vss-test-web.build-test-results-tab&runId=7053122&resultId=185354)|dotnet/runtime#88846|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|5|12|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=338789
**Error message validated:** `System.Net.Http.HttpRequestException : Error: ENOENT: no such file or directory, open`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/14/2023 9:38:12 AM UTC

**Comment by pavelsavara** [comment]
Another [log](https://helix.dot.net/api/2019-06-17/jobs/6db66e21-2435-4d6c-9e5e-23fe06a87552/workitems/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/console)

**Comment by pavelsavara** [comment]
Probably caused by https://github.com/dotnet/runtime/pull/87319 because the NodeJS CI pipeline didn't run.

cc @antonfirsov
