### ISSUE TITLE
Test failure GC\\Features\\HeapExpansion\\plug\\plug.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88977]
**Failed in:** [runtime-coreclr ilasm 20230715.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340916&view=ms.vss-test-web.build-test-results-tab&runId=7109956&resultId=119835&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 
Assert failure(PID 5420 [0x0000152c], Thread: 4804 [0x12c4]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x704e69e3)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x704e7109)
CORECLR! PinObject + 0x91 (0x704b0ee1)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x704b01a4)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x704afcd9)
CORECLR! ProcessScanQNode + 0x32 (0x704b0072)
CORECLR! ProcessScanQueue + 0x2E (0x704b00b1)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x704b06e4)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x704b0555)
CORECLR! TableScanHandles + 0xB0 (0x704b0410)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x704b0607)
CORECLR! HndScanHandlesForGC + 0x139 (0x704ae2bd)
CORECLR! Ref_TracePinningRoots + 0xC6 (0x704b2493)
CORECLR! GCScan::GcScanHandles + 0x64 (0x704b4e30)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E7 (0x704e5ca3)
CORECLR! WKS::gc_heap::gc1 + 0x13B (0x704eff2f)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x704e82c9)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x704e8477)
CORECLR! <lambda_675ed0882a6bd702e62f472ad598a04e>::operator() + 0x84 (0x702a9163)
-----
.AV on tid=0x12c4 (4804), cxr=0943E9E8, exr=0943E998
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x7051a640)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x700d529b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x700d4f90)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x700d4f34)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x700d54aa)
NTDLL! WinSqmEventWrite + 0x1C21A (0x7787f95a)
NTDLL! RtlUnwind + 0x1BA (0x7784011a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x77850dbf)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x704e7109)
CORECLR! PinObject + 0x91 (0x704b0ee1)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7115
    Image: C:\h\w\B5AE09CC\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B5AE09CC\w\B4810948\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\B5AE09CC\p\ildasm.exe /raweh /unicode /out=plug.dasm.il plug.dll
C:\h\w\B5AE09CC\p\ilasm.exe /output=plug.asm.dll  plug.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'plug.dasm.il'  to EXE --> 'plug.asm.dll'
Source file is UNICODE

Assembled method Test::Usage
Assembled method Test::Main
Assembled method Test::.ctor
Creating PE file

Emitting classes:
Class 1:Test

Emitting fields and methods:
Global 
Class 1Methods: 3;
Resolving local member refs: 2 -> 2 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global 
Class 1
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
 "C:\h\w\B5AE09CC\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.asm.dll 
Running 100 iterations
 "C:\h\w\B5AE09CC\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 7/15/2023 9:16:18 PM
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B5AE09CC\p
> C:\h\w\B5AE09CC\w\B4810948\e\GC\Features\HeapExpansion\plug\plug.cmd
Expected: True
Actual:   False
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Looks to be a one time failure but no dumps.

**Comment by mangod9** [comment]
Closing as transient.
