### ISSUE TITLE
Test failure System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_CalledByNonLocalProcess_ThrowsInvalidOperationException

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88976]
**Failed in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230715.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=340684&view=ms.vss-test-web.build-test-results-tab&runId=7104062&resultId=171534&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open
    - System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_CalledByNonLocalProcess_ThrowsInvalidOperationException
    - System.Diagnostics.Tests.ProcessTests.TestProcessOnRemoteMachineWindows
```

**Error message:**
```
System.ArgumentException : Process with an Id of 4700 is not running.
```

**Stack trace:**
```
   at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1039
   at System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_CalledByNonLocalProcess_ThrowsInvalidOperationException() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 2445
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by adamsitnik** [comment]
It seems to be a one time failure, closing.
