### ISSUE TITLE
[6.0] [mono] [linux] Conole test failure SetOut.SetOutReadToEnd

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#89084]
### Error Blob

```json
{
  "ErrorMessage": "SetOut.SetOutReadToEnd [FAIL]",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- PR https://github.com/dotnet/runtime/pull/89063
- Job `Libraries Test Run release mono_interpreter Linux x64 Debug`
- Build https://dev.azure.com/dnceng-public/public/_build/results?buildId=342882&view=logs&jobId=ba66422d-a35c-5bc8-b6c6-3a55f049cbee&j=ba66422d-a35c-5bc8-b6c6-3a55f049cbee&t=6e0f453a-5535-5664-111a-8f164e521e88
- Log https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-89063-merge-0dc77f96320b4b609a/System.Console.Tests/1/console.8fc5e077.log?helixlogtype=result
- Output:

```
=====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Console.Tests.runtimeconfig.json --depsfile System.Console.Tests.deps.json xunit.console.dll System.Console.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Console.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Console.Tests (found 102 of 138 test cases)
  Starting:    System.Console.Tests (parallel test collections = on, max threads = 2)
    Color.RedirectedOutput_EnvVarSet_EmitsAnsiCodes [SKIP]
    SetOut.SetOutReadToEnd [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: Test
      Actual:         Condition(s) not met: "TermIsSet"\nT···
                ↑ (pos 0)
      Stack Trace:
        /_/src/libraries/System.Console/tests/Helpers.cs(30,0): at Helpers.SetAndReadHelper(Action`1 setHelper, Func`1 getHelper, Func`2 readHelper)
        /_/src/libraries/System.Console/tests/SetOut.cs(34,0): at SetOut.SetOutReadToEnd()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(370,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
0
0
  Finished:    System.Console.Tests
=== TEST EXECUTION SUMMARY ===
   System.Console.Tests  Total: 143, Errors: 0, Failed: 1, Skipped: 1, Time: 2.289s
/root/helix/work/workitem/e
----- end Tue 18 Jul 2023 01:11:30 AM UTC ----- exit code 1 ----------------------------------------------------------
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=342882
**Error message validated:** `SetOut.SetOutReadToEnd [FAIL]`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 7/18/2023 2:55:45 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by akoeplinger** [comment]
Closing old 6.0 known issue, no recent hits.
