### ISSUE TITLE
HttpClient.SendAsync throws System.ObjectDisposedException on Android

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#89086]
### Description

I'm experiencing this on a MAUI project but as its on a .NET runtime function I am posting it here.

HttpClient.SendAsync throws `System.ObjectDisposedException: Cannot access a closed Stream.` on android when request message method is set to GET.

### Reproduction Steps

```C#
internal async Task<bool> BlaFunction()
{
    try
    {
        using (var content = new ByteArrayContent(JsonSerializer.SerializeToUtf8Bytes(...)))
        {
            using (var request = new HttpRequestMessage())
            {
                request.RequestUri = new Uri("https://bla.com/");
                request.Method = HttpMethod.Get;

                request.Headers.Add("somekey", "somevalue");
                request.Content = content;

                using (var bla = await httpClient.SendAsync(request))
                {
                    ///
                }
            }
        }
    }
    catch (Exception e)
    {
        throw;
    }
}
```

### Expected behavior

No exception

### Actual behavior

```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Xamarin.Android.Net.AndroidMessageHandler.WriteRequestContentToOutput(HttpRequestMessage request, HttpURLConnection httpConnection, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 500
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 575
   at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 417
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

### Known Workarounds

Doesn't throw if I change method to POST, i.e. `request.Method = HttpMethod.Post`

### Configuration

```
Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.120 [C:\Program Files\dotnet\sdk]
  7.0.200-preview.22628.1 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
```

MAUI app targets `net7.0-android` and it was tested in: `Android Emulator - pixel 5 API 31`

**Comment by steveisok** [comment]
@simonrozsival can you please triage?

**Comment by Symbai** [comment]
I'm sorry.

```
Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.120 [C:\Program Files\dotnet\sdk]
  7.0.200-preview.22628.1 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23330.10 [C:\Program Files\dotnet\sdk]
```

MAUI app targets `net7.0-android` and it was tested in: `Android Emulator - pixel 5 API 31`

**Comment by simonrozsival** [comment]
I'm not able to reproduce the bug locally with this code snippet:
```csharp
var data = "bla";
var url = "https://httpbin.org/anything";

try
{
    using (var content = new ByteArrayContent(JsonSerializer.SerializeToUtf8Bytes(data)))
    {
        using (var request = new HttpRequestMessage())
        {
            request.RequestUri = new Uri(url);
            request.Method = HttpMethod.Get;

            request.Headers.Add("somekey", "somevalue");
            request.Content = content;

            var httpClient = new HttpClient();
            using (var bla = await httpClient.SendAsync(request))
            {
                var body = await bla.Content.ReadAsStringAsync();
                Console.WriteLine(body);
                return bla.IsSuccessStatusCode;
            }
        }
    }
}
catch (Exception e)
{
    throw;
}
```

The request completes successfully and I get a 200 response.

> Doesn't throw if I change method to POST, i.e. request.Method = HttpMethod.Post

I thought that it's a little strange that you send a GET request to your server with a body and I can see that some servers would reject such requests, but since it fails for POST it fails as well that's not the issue.

@Symbai could you please share some more information about the data you serialize and send to the server or about the server you are using? Or can you modify your code so that you can share it with us and we can have a complete code snippet to replicate the issue on our end and identify what's going on? It would be very helpful! I'm afraid that with just the information that's currently available to me I can't do much more.

**Comment by Symbai** [comment]
@simonrozsival Just to verify, have you been trying to reproduce this on Android? Because the stacktrace from my exception clearly shows android-only-related code. I haven't been able to reproduce this on Windows for example as well. Otherwise I will try and gather more information.

**Comment by simonrozsival** [comment]
@Symbai yes, I tried it on Android using the AndroidMessageHandler

**Comment by Symbai** [comment]
Im not able to reproduce this myself either on a new project

**Comment by simonrozsival** [comment]
@Symbai thanks for closing the issue. Let us know if you run into the problem again.
