### ISSUE TITLE
Half.TryParse assertion failure on System.Globalization.Ordinal.EqualsIgnoreCaseUtf8_Scalar

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#89094]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=344043
Build error leg or test failing: System.Text.Json.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/89036

### Error Blob

```json
{
  "ErrorMessage": "System.Globalization.Ordinal.EqualsIgnoreCaseUtf8_Scalar",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

While adding support for Half to System.Text.Json (https://github.com/dotnet/runtime/pull/88962), I noticed one test triggers the assertion failure consistently on macOS-12.4.
Note: This didn't repro for me locally on macOS 13.4.1 arm64.

The test attempts to deserialize floting-point literals (NaN, infinity, -Infinity) in multiple casings/variants that are invalid for S.T.Json. Error happens on line 883.
https://github.com/dotnet/runtime/blob/43fe8a8fc7642a1268e80b0433aebb92b049ee09/src/libraries/System.Text.Json/tests/Common/NumberHandlingTests.cs#L848-L883

Helix log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-88962-merge-9757e201f6374e20b5/System.Text.Json.Tests/1/console.78feb75a.log?helixlogtype=result

Call stack:
```
/private/tmp/helix/working/9EC208C7/w/A9F108F7/e /private/tmp/helix/working/9EC208C7/w/A9F108F7/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 7160 of 7231 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 6)
Process terminated. Assertion failed.
   at System.Globalization.Ordinal.EqualsIgnoreCaseUtf8_Scalar(Byte& charA, Int32 lengthA, Byte& charB, Int32 lengthB) in /_/src/libraries/System.Private.CoreLib/src/System/Globalization/Ordinal.Utf8.cs:line 308
   at System.Number.TryParseFloat[TChar,TFloat](ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info, TFloat& result) in /_/src/libraries/System.Private.CoreLib/src/System/Number.Parsing.cs:line 1229
   at System.Half.TryParse(ReadOnlySpan`1 utf8Text, NumberStyles style, IFormatProvider provider, Half& result) in /_/src/libraries/System.Private.CoreLib/src/System/Half.cs:line 2238
   at System.Text.Json.Serialization.Converters.HalfConverter.TryParse(ReadOnlySpan`1 buffer, Half& result) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/HalfConverter.cs:line 197
   at System.Text.Json.Serialization.Converters.HalfConverter.ReadCore(Utf8JsonReader& reader) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/HalfConverter.cs:line 50
   at System.Text.Json.Serialization.Converters.HalfConverter.ReadNumberWithCustomHandling(Utf8JsonReader& reader, JsonNumberHandling handling, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/HalfConverter.cs:line 115
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 193
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfoOfT.cs:line 308
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectDefaultConverter.cs:line 49
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 258
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs:line 51
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfoOfT.ReadHelper.cs:line 22
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Span.cs:line 160
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 443
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 55
   at System.Text.Json.Serialization.Tests.JsonSerializerWrapper.StringSerializerWrapper.DeserializeWrapper[T](String json, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/JsonSerializerWrapper.Reflection.cs:line 129
   at System.Text.Json.Serialization.Tests.NumberHandlingTests.<>c__DisplayClass39_0.<<FloatingPointConstants_Fail>b__1>d.MoveNext() in /_/src/libraries/System.Text.Json/tests/Common/NumberHandlingTests.cs:line 883
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Text.Json.Serialization.Tests.NumberHandlingTests.<>c__DisplayClass39_0.<FloatingPointConstants_Fail>b__1()
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=344043
**Error message validated:** `System.Globalization.Ordinal.EqualsIgnoreCaseUtf8_Scalar`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/18/2023 11:30:55 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[344444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344444)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344444&view=ms.vss-test-web.build-test-results-tab&runId=7199754&resultId=191955)|dotnet/runtime#89153|
|[344421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344421)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344421&view=ms.vss-test-web.build-test-results-tab&runId=7199328&resultId=191955)|dotnet/runtime#89154|
|[344427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344427)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344427&view=ms.vss-test-web.build-test-results-tab&runId=7199326&resultId=191955)|dotnet/runtime#89155|
|[344398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344398)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344398&view=ms.vss-test-web.build-test-results-tab&runId=7199020&resultId=191955)|dotnet/runtime#89151|
|[344340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344340)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344340&view=ms.vss-test-web.build-test-results-tab&runId=7197162&resultId=191950)|dotnet/runtime#87438|
|[344330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344330)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344330&view=ms.vss-test-web.build-test-results-tab&runId=7196836&resultId=191950)|dotnet/runtime#89061|
|[344321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344321)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344321&view=ms.vss-test-web.build-test-results-tab&runId=7196454&resultId=191950)|dotnet/runtime#89147|
|[344317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344317)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344317&view=ms.vss-test-web.build-test-results-tab&runId=7196442&resultId=191945)|dotnet/runtime#89123|
|[344290](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344290)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344290&view=ms.vss-test-web.build-test-results-tab&runId=7195808&resultId=191945)|dotnet/runtime#87847|
|[344296](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344296)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344296&view=ms.vss-test-web.build-test-results-tab&runId=7195748&resultId=191954)|dotnet/runtime#89102|
|[344284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344284)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344284&view=ms.vss-test-web.build-test-results-tab&runId=7195206&resultId=191950)|dotnet/runtime#89144|
|[344268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344268)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344268&view=ms.vss-test-web.build-test-results-tab&runId=7195142&resultId=191936)|dotnet/runtime#89130|
|[344261](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344261)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344261&view=ms.vss-test-web.build-test-results-tab&runId=7194786&resultId=191936)|dotnet/runtime#85328|
|[344239](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344239)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344239&view=ms.vss-test-web.build-test-results-tab&runId=7194322&resultId=191936)|dotnet/runtime#86089|
|[344207](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344207)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344207&view=ms.vss-test-web.build-test-results-tab&runId=7193170&resultId=191941)|dotnet/runtime#89129|
|[344182](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344182)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344182&view=ms.vss-test-web.build-test-results-tab&runId=7193228&resultId=191936)|dotnet/runtime#89135|
|[344136](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344136)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344136&view=ms.vss-test-web.build-test-results-tab&runId=7191764&resultId=191941)|dotnet/runtime#87656|
|[344099](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344099)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344099&view=ms.vss-test-web.build-test-results-tab&runId=7190988&resultId=191936)|dotnet/runtime#89064|
|[344092](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344092)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344092&view=ms.vss-test-web.build-test-results-tab&runId=7190894&resultId=191936)|dotnet/runtime#89116|
|[344056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344056)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344056&view=ms.vss-test-web.build-test-results-tab&runId=7189838&resultId=191923)|dotnet/runtime#89123|
|[344043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344043)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344043&view=ms.vss-test-web.build-test-results-tab&runId=7189660&resultId=191923)|dotnet/runtime#89036|
|[344049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344049)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344049&view=ms.vss-test-web.build-test-results-tab&runId=7187996&resultId=188823)||
|[343994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343994)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343994&view=ms.vss-test-web.build-test-results-tab&runId=7188360&resultId=191923)|dotnet/runtime#87438|
|[343982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343982)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343982&view=ms.vss-test-web.build-test-results-tab&runId=7188200&resultId=191923)|dotnet/runtime#85328|
|[343063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343063)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343063&view=ms.vss-test-web.build-test-results-tab&runId=7166966&resultId=188762)|dotnet/runtime#88962|
|[342911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342911)|dotnet/runtime|[System.Text.Json.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342911&view=ms.vss-test-web.build-test-results-tab&runId=7164930&resultId=188756)|dotnet/runtime#88962|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|25|26|26|

**Comment by Jozkee** [comment]
cc @tannergooding

**Comment by elinor-fung** [comment]
Recent PRs are consistently hitting this on Linux and Windows as well: [linux](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344043&view=logs&j=fe27627b-bd13-56b8-97c3-9bb28451d0b9&t=210da701-2853-589e-f0dc-02686f4c4da6), [windows](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344043&view=logs&j=51e4640a-c078-5be6-cc1b-f971e75d762f&t=a795459e-9f5a-52e6-9047-d38ac6fe5fb4)

**Comment by EgorBo** [comment]
Sounds like it's from https://github.com/dotnet/runtime/pull/86875

**Comment by markples** [comment]
adding some keywords to help github issue search (?)

EqualsIgnoreCaseUtf8_Scalar
Json.Tests
System.Text.Json.SourceGeneration.Roslyn4.4.Tests
Roslyn4.4.Tests
Roslyn4

**Comment by EgorBo** [comment]
Looks like https://github.com/dotnet/runtime/pull/88962 is the PR that broke CI by uncovering an existing bug, it seems that the assert was noticed and ignored on macOS
