### ISSUE TITLE
[NativeAOT] Assertions while building libraries tests

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#89191]
A few tests fail to compile in Checked build of libraries tests.
(examp[le log: https://[dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344603/logs/705](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/344603/logs/705))

```
 2023-07-19T05:57:52.0500275Z   Process terminated. Assertion failed.
2023-07-19T05:57:52.0501327Z      at ILCompiler.Dataflow.MethodBodyScanner.InterproceduralScan(MethodIL startingMethodBody) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/MethodBodyScanner.cs:line 330
2023-07-19T05:57:52.0502397Z      at ILCompiler.Dataflow.ReflectionMethodBodyScanner.InterproceduralScan(MethodIL methodBody) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 103
2023-07-19T05:57:52.0503563Z      at ILCompiler.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(NodeFactory factory, FlowAnnotations annotations, Logger logger, MethodIL methodBody) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 128
2023-07-19T05:57:52.0553815Z      at ILCompiler.DependencyAnalysis.DataflowAnalyzedMethodNode.GetStaticDependencies(NodeFactory factory) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/DataflowAnalyzedMethodNode.cs:line 32
2023-07-19T05:57:52.0557054Z      at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 182
2023-07-19T05:57:52.0557674Z      at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 222
2023-07-19T05:57:52.0558201Z      at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 257
2023-07-19T05:57:52.0558679Z      at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 308
2023-07-19T05:57:52.0559130Z      at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 140
2023-07-19T05:57:52.0559526Z      at ILCompiler.Program.<Run>g__RunScanner|4_0(<>c__DisplayClass4_0&) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 467
2023-07-19T05:57:52.0559854Z      at ILCompiler.Program.Run() in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 447
2023-07-19T05:57:52.0560231Z      at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass221_0.<.ctor>b__0(ParseResult result) in /_/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 277
2023-07-19T05:57:52.0560609Z      at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
2023-07-19T05:57:52.0560914Z      at ILCompiler.Program.Main(String[] args) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 727
2023-07-19T05:57:52.1918929Z /__w/1/s/artifacts/bin/coreclr/linux.x64.Checked/build/Microsoft.NETCore.Native.targets(300,5): error MSB3073: The command ""/__w/1/s/artifacts/bin/coreclr/linux.x64.Checked/x64/ilc/ilc" @"/__w/1/s/artifacts/obj/Microsoft.Extensions.Logging.Tests/Release/net8.0/native/Microsoft.Extensions.Logging.Tests.ilc.rsp"" exited with code 134. [/__w/1/s/src/libraries/Microsoft.Extensions.Logging/tests/Common/Microsoft.Extensions.Logging.Tests.csproj::TargetFramework=net8.0]

```

**Comment by am11** [comment]
Related to https://github.com/dotnet/linker/issues/2845.
https://github.com/dotnet/runtime/blob/cf1482c277b0fd93d037f10e5c8660d4168fd870/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/MethodBodyScanner.cs#L316-L332

**Comment by VSadov** [comment]
CC: @MichalStrehovsky @vitek-karas

**Comment by MichalStrehovsky** [comment]
Cc @dotnet/illink @dotnet/illink-contrib for thoughts since this assert is in code we mirror with illinker. Can we comment it out? Some assert is already commented out around here.

**Comment by MichalStrehovsky** [comment]
@sbomer @vitek-karas yup, this is a problem in the shared logic with illinker. We just don't have any legs with illinker that would cover this.

The problem is that source generated code is triggering "this is compiler generated class" logic. We're hitting the assert because the MethodBodies collection has all of these methods:

```
"MethodBodyValue { MethodBody = [Microsoft.Extensions.Logging.Console]Microsoft.Extensions.Configuration.Binder.SourceGeneration.<GeneratedConfigurationBinder_g>F86B5F805A26B32373DA5BA80136649730AD5F76CC2979BFEE086BEB55048B927__CoreBindingHelper..cctor() }"
"MethodBodyValue { MethodBody = [Microsoft.Extensions.Logging.Console]Microsoft.Extensions.Configuration.Binder.SourceGeneration.<GeneratedConfigurationBinder_g>F86B5F805A26B32373DA5BA80136649730AD5F76CC2979BFEE086BEB55048B927__CoreBindingHelper+<>c.<.cctor>b__18_0() }"
"MethodBodyValue { MethodBody = [Microsoft.Extensions.Logging.Console]Microsoft.Extensions.Configuration.Binder.SourceGeneration.<GeneratedConfigurationBinder_g>F86B5F805A26B32373DA5BA80136649730AD5F76CC2979BFEE086BEB55048B927__CoreBindingHelper+<>c.<.cctor>b__18_1() }"
"MethodBodyValue { MethodBody = [Microsoft.Extensions.Logging.Console]Microsoft.Extensions.Configuration.Binder.SourceGeneration.<GeneratedConfigurationBinder_g>F86B5F805A26B32373DA5BA80136649730AD5F76CC2979BFEE086BEB55048B927__CoreBindingHelper+<>c.<.cctor>b__18_2() }"
"MethodBodyValue { MethodBody = [Microsoft.Extensions.Logging.Console]Microsoft.Extensions.Configuration.Binder.SourceGeneration.<GeneratedConfigurationBinder_g>F86B5F805A26B32373DA5BA80136649730AD5F76CC2979BFEE086BEB55048B927__CoreBindingHelper+<>c.<.cctor>b__18_3() }"
"MethodBodyValue { MethodBody = [Microsoft.Extensions.Logging.Console]Microsoft.Extensions.Configuration.Binder.SourceGeneration.<GeneratedConfigurationBinder_g>F86B5F805A26B32373DA5BA80136649730AD5F76CC2979BFEE086BEB55048B927__CoreBindingHelper+<>c.<.cctor>b__18_4() }"
```

We consider the `<GeneratedConfigurationBinder_g>` compiler generated state. I have a workaround in #89287 but I don't know how a real fix looks like. This assert is currently putting runtime-extra-platforms CI legs on the floor so we need something to unblock (either disable all failing tests in the CI, I don't know how many there are, or take my PR).
