### ISSUE TITLE
A really obscure System.IO.Pipes issue that appeared on .NET 6

### ISSUE THREAD

**Issue by chriskarlsson** [dotnet/runtime#89427]
### Discussed in https://github.com/dotnet/runtime/discussions/85530

<div type='discussions-op-text'>

<sup>Originally posted by **natan-abolafya** April 28, 2023</sup>
This is really a head scratcher. We have an application where we create a `NamedPipeServerStream` on C# and a nodejs application connects to this pipe for communication.

After upgrading to .NET 6 from .NET 5, very few users started reporting that they started having issues caused by this communication dying out of nowhere. This happens only on specific devices but it happens to them frequently. Everybody else is using it quite fine.
There were of course other changes between these two application versions, but we are quite confident that it's the .NET change caused this as downgrading .NET and keeping everything else the same seems to solve the issue. ~~We have also tested upgrading to .NET 7 which also seems to address the issue.~~ **UPDATE: We still see it with .NET 7.**

Unfortunately, we did not manage to collect very detailed information about the issue due to various layers above the pipe code nor isolate it as we don't have access to these devices.

I think the Pipe code thinks that the other side closed the connection as that part of the code is triggered, while nodejs reports `read EPIPE` on this code piece
```
      this.connection.on('error', error => {
          Log.error('Service connection error: ' + error.message);
      });
```

~~So, the solution should be upgrading to .NET 7 of course but it's not so simple. We just made a test build by cutting a lot of corners. Not really easy for production.~~
I was hoping to find the issue that appeared ~~and disappeared and hope to convince the maintainers to backport it to .NET 6 since it's LTS~~. But I couldn't find anything related. I can't really report it either as the information I have doesn't feel enough to report a bug.

So I guess my question is: does this ring any bell to anyone? Is there an issue I failed to find?

**UPDATE**: It still happens on .NET 7.
</div>

**Comment by chriskarlsson** [comment]
Some further investigation points to this [change](https://github.com/dotnet/runtime/pull/52695) as a possible reason for the dying connection:
```
[2023-07-18T06:18:02.153Z] Warn : UI JSON-RPC connection has failed: 'Reading JSON RPC from the stream failed with OperationCanceledException: The operation was canceled.' ('StreamError')
[2023-07-18T06:18:02.154Z] Warn :    at System.IO.Pipes.PipeStream.PipeValueTaskSource.GetResult(Int16 )
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object )
--- End of stack trace from previous location ---
   at Stratus.WindowsClient.WindowsUtils.Pipe.PipeServerCommunication.ReadAsync(Byte[] buffer, Int32 offset, Int32 length) in C:\BuildAgent\work\cabf95aa4bca1f9d\src\client\Windows\Client\WindowsUtils\Pipe\PipeServerCommunication.cs:line 75
   at Stratus.WindowsClient.WindowsUtils.Pipe.PipeCommunication.ReadAsync() in C:\BuildAgent\work\cabf95aa4bca1f9d\src\client\Windows\Client\WindowsUtils\Pipe\PipeCommunication.cs:line 92
   at Shared.Base.Stream.TextLineStreamToMessageCommunication.ReadMessageAsync() in C:\BuildAgent\work\cabf95aa4bca1f9d\src\client\Shared\Base\Stream\TextLineStreamToMessageCommunication.cs:line 55
   at Shared.Base.Stream.CommunicationTextLineStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\BuildAgent\work\cabf95aa4bca1f9d\src\client\Shared\Base\Stream\CommunicationTextLineStream.cs:line 86
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader , CancellationTokenSource , CancellationToken )
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 )
   at StreamJsonRpc.NewLineDelimitedMessageHandler.ReadCoreAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.ReadAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync()
```

**Comment by chriskarlsson** [comment]
> What patch versions are you using? I suspect this is #82245, which was also backported to 7.0 and 6.0.

6.0.14. Seems like it was backported to 6.0.16. I'll try upgrading to the latest and see if that helps.

**Comment by chriskarlsson** [comment]
Bumping to 6.0.20 solved the issue. Thank you very much!

**Comment by stephentoub** [comment]
Thanks for confirming.
