### ISSUE TITLE
[browser] mono runtime already exited with 0

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#89425]
### Error Blob

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=350621&view=results
Log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89387-merge-7052a2aebdb04a27be/WasmTestOnNodeJS-System.Net.WebSockets.Client.Tests/1/console.ec43186b.log?helixlogtype=result

```json
{
  "ErrorMessage": "mono runtime already exited with",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

wasm `System.Net.WebSockets.Client.Tests` nodeJS

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=350621
**Error message validated:** `mono runtime already exited with`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/25/2023 9:31:59 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[457734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457734)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457734&view=ms.vss-test-web.build-test-results-tab&runId=10309828&resultId=187499)|dotnet/runtime#94204|
|[457289](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457289)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=457289&view=ms.vss-test-web.build-test-results-tab&runId=10297578&resultId=187499)|dotnet/runtime#94204|
|[456278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456278)|dotnet/runtime|[WasmTestOnNodeJS-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=456278&view=ms.vss-test-web.build-test-results-tab&runId=10269268&resultId=187506)|dotnet/runtime#94204|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|3|

**Comment by pavelsavara** [comment]
Finally we have also stack trace, [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89699-merge-90d5a45ab7084400a6/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.9c28844c.log?helixlogtype=result)

```
[17:01:34] info: === TEST EXECUTION SUMMARY ===
[17:01:34] info: Total: 511, Errors: 0, Failed: 0, Skipped: 89, Time: 4.5920939s
[17:01:34] info: 
[17:01:34] info: MONO_WASM: Proxy of C# function with GCHandle 70 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# function with GCHandle 278 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# function with GCHandle 422 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# function with GCHandle 342 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# object with GCHandle 358 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# function with GCHandle 374 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# object with GCHandle 390 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# function with GCHandle 198 was still alive. disposing.
[17:01:34] info: MONO_WASM: Proxy of C# object with GCHandle 246 was still alive. disposing.
[17:01:34] info: file:///root/helix/work/workitem/e/test-main.js:31
[17:01:34] info:             throw ex;
[17:01:34] info:             ^
[17:01:34] info: 
[17:01:34] info: Error: Assert failed: mono runtime already exited with 0
[17:01:34] info:     at fe (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:17543)
[17:01:34] info:     at Object.ge [as assert_runtime_running] (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:17750)
[17:01:34] info:     at Object.p.javaScriptExports.call_delegate (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:200872)
[17:01:34] info:     at i (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:31721)
[17:01:34] info:     at WebSocket.o.addEventListener.once (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:60619)
[17:01:34] info:     at WebSocket.onClose (/root/helix/work/workitem/e/node_modules/ws/lib/event-target.js:210:18)
[17:01:34] info:     at Object.onceWrapper (node:events:628:26)
[17:01:34] info:     at WebSocket.emit (node:events:513:28)
[17:01:34] info:     at WebSocket.emitClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:257:10)
[17:01:34] info:     at Socket.socketOnClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:1178:15)
[17:01:34] info:     at Socket.emit (node:events:513:28)
[17:01:34] info:     at TCP.<anonymous> (node:net:301:12)
```

**Comment by pavelsavara** [comment]
We have another [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89857-merge-37082936f5ef4ba08e/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.398af621.log?helixlogtype=result)

```
[19:06:02] info: MONO_WASM: Proxy of C# function with GCHandle 422 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# object with GCHandle 438 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# function with GCHandle 454 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# object with GCHandle 470 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# function with GCHandle 230 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# function with GCHandle 374 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# function with GCHandle 390 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# function with GCHandle 486 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of C# object with GCHandle 86 was still alive. disposing.
[19:06:02] info: MONO_WASM: Proxy of JS object with JSHandle 5 was still alive. disposing.
[19:06:02] info: file:///root/helix/work/workitem/e/test-main.js:31
[19:06:02] info:             throw ex;
[19:06:02] info:             ^
[19:06:02] info: 
[19:06:02] info: Error: Assert failed: mono runtime already exited with 0
[19:06:02] info:     at De (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:20455)
[19:06:02] info:     at Object.Oe [as assert_runtime_running] (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:20662)
[19:06:02] info:     at Object.p.javaScriptExports.call_delegate (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:200981)
[19:06:02] info:     at i (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:31836)
[19:06:02] info:     at WebSocket.u (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:60647)
[19:06:02] info:     at WebSocket.onClose (/root/helix/work/workitem/e/node_modules/ws/lib/event-target.js:210:18)
[19:06:02] info:     at Object.onceWrapper (node:events:628:26)
[19:06:02] info:     at WebSocket.emit (node:events:513:28)
[19:06:02] info:     at WebSocket.emitClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:257:10)
[19:06:02] info:     at Socket.socketOnClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:1178:15)
[19:06:02] info:     at Socket.emit (node:events:513:28)
[19:06:02] info:     at TCP.<anonymous> (node:net:301:12)
```

**Comment by pavelsavara** [comment]
Another [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89926-merge-21703de48f5b46c9b4/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.1f4eccb6.log?helixlogtype=result)

```
[15:01:31] info: MONO_WASM: mono_exit failed Error: WebSocket was closed before the connection was established
[15:01:31] info:     at WebSocket.close (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:284:14)
[15:01:31] info:     at js (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:63397)
[15:01:31] info:     at WebSocket.o.dispose (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:61251)
[15:01:31] info:     at Object.ro [as forceDisposeProxies] (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:45730)
[15:01:31] info:     at xe (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:22063)
[15:01:31] info:     at run (file:///root/helix/work/workitem/e/test-main.js:392:17)
[15:01:31] info:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[15:01:31] info:     at async file:///root/helix/work/workitem/e/test-main.js:406:1
[15:01:31] info: file:///root/helix/work/workitem/e/test-main.js:31
[15:01:31] info:             throw ex;
[15:01:31] info:             ^
[15:01:31] info: 
[15:01:31] info: Error: Assert failed: mono runtime already exited with 0
[15:01:31] info:     at Ee (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:20026)
[15:01:31] info:     at Object.Ae [as assert_runtime_running] (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:20233)
[15:01:31] info:     at Object.p.javaScriptExports.call_delegate (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:201163)
[15:01:31] info:     at i (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:31836)
[15:01:31] info:     at WebSocket.u (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:60647)
[15:01:31] info:     at WebSocket.onClose (/root/helix/work/workitem/e/node_modules/ws/lib/event-target.js:210:18)
[15:01:31] info:     at Object.onceWrapper (node:events:628:26)
[15:01:31] info:     at WebSocket.emit (node:events:513:28)
[15:01:31] info:     at WebSocket.emitClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:257:10)
[15:01:31] info:     at Socket.socketOnClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:1178:15)
[15:01:31] info:     at Socket.emit (node:events:513:28)
[15:01:31] info:     at TCP.<anonymous> (node:net:301:12)
```

**Comment by pavelsavara** [comment]
Another [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-91317-merge-ecdfb0d8784a4c4da3/WasmTestOnNodeJS-System.Net.Http.Functional.Tests/1/console.09bfb92f.log?helixlogtype=result)
```
info: Error: Assert failed: mono runtime already exited with 0
info:     at De (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:18481)
info:     at Object.Oe [as assert_runtime_running] (file:///root/helix/work/workitem/e/_framework/dotnet.js:3:18688)
info:     at l.javaScriptExports.call_delegate (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:211136)
info:     at i (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:31204)
info:     at WebSocket.u (file:///root/helix/work/workitem/e/_framework/dotnet.runtime.js:3:82130)
info:     at WebSocket.onClose (/root/helix/work/workitem/e/node_modules/ws/lib/event-target.js:210:18)
info:     at Object.onceWrapper (node:events:629:26)
info:     at WebSocket.emit (node:events:514:28)
info:     at WebSocket.emitClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:257:10)
info:     at Socket.socketOnClose (/root/helix/work/workitem/e/node_modules/ws/lib/websocket.js:1178:15)
info:     at Socket.emit (node:events:514:28)
info:     at TCP.<anonymous> (node:net:323:12)
```

**Comment by lewing** [comment]
can we close this?

**Comment by pavelsavara** [comment]
Hopefully this was fixed by https://github.com/dotnet/runtime/pull/93472
