### ISSUE TITLE
Problem with GLIBC_2.34 on Ubuntu.22.04-x64

### ISSUE THREAD

**Issue by dockeratso** [dotnet/runtime#89471]
Hi!

The dotnet 7 SDK (version:   7.0.306) causes a runtime error when running external libraries compiled with libc.so.6 and with version GLIBC_2.35. It is no problem when I test with dotnet 8 SDK preview (version:  8.0.100-preview.6.23330.14).

## How to reproduce error:

Setup a Ubuntu.22.04 WSL  (Windows subsystem for Linux)

Install dotnet 7 SDK with

sudo snap install dotnet-sdk --classic
 
Check out LearnOpenTK using 

git clone https://github.com/opentk/LearnOpenTK.git

cd LearnOpenTK/Chapter1/2-HelloTriangle

Change target framework to net7.0 in the csproj-file.

Run: dotnet run

## Log  output:

dotnet run
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'glfw' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/runtimes/linux-x64/native/glfw.so: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/glfw.so: cannot open shared object file: No such file or directory
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/glfw.so: cannot open shared object file: No such file or directory
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/runtimes/linux-x64/native/libglfw.so: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/libglfw.so: cannot open shared object file: No such file or directory
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/libglfw.so: cannot open shared object file: No such file or directory
/snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/lib/libglfw.so)
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/runtimes/linux-x64/native/glfw: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/glfw: cannot open shared object file: No such file or directory
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/glfw: cannot open shared object file: No such file or directory
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/runtimes/linux-x64/native/libglfw: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/libglfw: cannot open shared object file: No such file or directory
/home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/bin/Debug/net7.0/libglfw: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..ctor()
   at LearnOpenTK.Program.Main() in /home/scienta/testar/LearnOpenTK/Chapter1/2-HelloTriangle/Program.cs:line 11

```

**Comment by janvorli** [comment]
This is clearly a problem of dotnet installed as a snap package. Non-snap installation would not have this issue. The relevant part of the error says:
`/snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/lib/libglfw.so)`

The snap packed older libc than the 2.35 in the dotnet package. When snap runs stuff, it overrides the libraries that it has copies of and that are requested to be loaded as dependencies of the runtime and all the shared libraries that dotnet process ends up loading.

**Comment by dockeratso** [comment]
Ok. I tried to install dotnet in the usual way (using apt install) and then everything worked as usual (with GLIBC_2.35). Thanks for the quick response.

**Comment by MichaelSimons** [comment]
[Triage] Canonical has taken over the ownership and production of .NET Snaps.  This is described in the [runtime](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap-runtime) and [sdk](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap-sdk) snap documentation.  If you experience issues with the snaps or have suggestions on how to improve them, please open an issue at https://github.com/canonical/dotnet-snap. Closing issue.
