### ISSUE TITLE
[mono] Apple mobile tests could not find test artifacts

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#89491]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=349967&view=results
Build error leg or test failing: tvos-arm64 Release AllSubsets_Mono
Pull request: https://github.com/dotnet/runtime/pull/88167

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.IO.DirectoryNotFoundException : Could not find a part of the path",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
[FAIL] System.IO.Compression.ZLibStreamUnitTests.Dispose_WithUnfinishedReadAsync   Test name: System.IO.Compression.ZLibStreamUnitTests.Dispose_WithUnfinishedReadAsync
[20:08:56.1418830] 2023-07-25 17:08:56.241 System.IO.Compression.Tests[43690:25521723]    Assembly:  [System.IO.Compression.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[20:08:56.1418930] 2023-07-25 17:08:56.241 System.IO.Compression.Tests[43690:25521723]    Exception messages: System.IO.FileNotFoundException : Could not find file '/private/var/containers/Bundle/Application/5CFA5A88-4C15-401E-A916-556A00578E7B/System.IO.Compression.Tests.app/UncompressedTestFiles/TestDocument.pdf'.   Exception stack traces:    at System.IO.FileInfo.get_Length()
[20:08:56.1419040]    at System.IO.Compression.CompressionStreamUnitTestBase.Dispose_WithUnfinishedReadAsync()
[20:08:56.1419100] --- End of stack trace from previous location ---
[20:08:56.1419190]    Execution time: 0.0040698
[20:08:56.1419670] 2023-07-25 17:08:56.241 System.IO.Compression.Tests[43690:25521723] 2) 	[FAIL] System.IO.Compression.ZLibStreamUnitTests.Read_EndOfStreamPosition   Test name: System.IO.Compression.ZLibStreamUnitTests.Read_EndOfStreamPosition
[20:08:56.1419890] 2023-07-25 17:08:56.241 System.IO.Compression.Tests[43690:25521723]    Assembly:  [System.IO.Compression.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[20:08:56.1425240] 2023-07-25 17:08:56.242 System.IO.Compression.Tests[43690:25521723]    Exception messages: System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/containers/Bundle/Application/5CFA5A88-4C15-401E-A916-556A00578E7B/System.IO.Compression.Tests.app/ZLibTestData/TestDocument.pdf.z'.   Exception stack traces:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1433750] 2023-07-25 17:08:56.244 System.IO.Compression.Tests[43690:25521723]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1433920]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
[20:08:56.1448530] 2023-07-25 17:08:56.244 System.IO.Compression.Tests[43690:25521723]    at System.IO.File.ReadAllBytes(String path)
[20:08:56.1448670]    at StreamHelpers.CreateTempCopyStream(String path)
[20:08:56.1448730]    at LocalMemoryStream.readAppFileAsync(String testFile)
[20:08:56.1448780]    at System.IO.Compression.CompressionStreamUnitTestBase.Read_EndOfStreamPosition()
[20:08:56.1449250] 2023-07-25 17:08:56.245 System.IO.Compression.Tests[43690:25521723] --- End of stack trace from previous location ---
[20:08:56.1449330]    Execution time: 0.0046917
[20:08:56.1450030] 2023-07-25 17:08:56.245 System.IO.Compression.Tests[43690:25521723] 3) 	[FAIL] System.IO.Compression.ZLibStreamUnitTests.BaseStream_ValidAfterDisposeWithTrueLeaveOpen   Test name: System.IO.Compression.ZLibStreamUnitTests.BaseStream_ValidAfterDisposeWithTrueLeaveOpen(mode: Compress)   Test case: System.IO.Compression.ZLibStreamUnitTests.BaseStream_ValidAfterDisposeWithTrueLeaveOpen
[20:08:56.1450210]    Assembly:  [System.IO.Compression.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[20:08:56.1450800] 2023-07-25 17:08:56.245 System.IO.Compression.Tests[43690:25521723]    Exception messages: System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/containers/Bundle/Application/5CFA5A88-4C15-401E-A916-556A00578E7B/System.IO.Compression.Tests.app/ZLibTestData/TestDocument.pdf.z'.   Exception stack traces:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1451490] 2023-07-25 17:08:56.245 System.IO.Compression.Tests[43690:25521723]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1452160] 2023-07-25 17:08:56.245 System.IO.Compression.Tests[43690:25521723]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
[20:08:56.1452240]    at System.IO.File.ReadAllBytes(String path)
[20:08:56.1452290]    at StreamHelpers.CreateTempCopyStream(String path)
[20:08:56.1458420] 2023-07-25 17:08:56.246 System.IO.Compression.Tests[43690:25521723]    at LocalMemoryStream.readAppFileAsync(String testFile)
[20:08:56.1458600]    at System.IO.Compression.CompressionStreamUnitTestBase.BaseStream_ValidAfterDisposeWithTrueLeaveOpen(CompressionMode mode)
[20:08:56.1458660] --- End of stack trace from previous location ---
[20:08:56.1458720]    Execution time: 0.0029031
[20:08:56.1472050] 2023-07-25 17:08:56.247 System.IO.Compression.Tests[43690:25521723] 4) 	[FAIL] System.IO.Compression.ZLibStreamUnitTests.BaseStream_ValidAfterDisposeWithTrueLeaveOpen   Test name: System.IO.Compression.ZLibStreamUnitTests.BaseStream_ValidAfterDisposeWithTrueLeaveOpen(mode: Decompress)   Test case: System.IO.Compression.ZLibStreamUnitTests.BaseStream_ValidAfterDisposeWithTrueLeaveOpen
[20:08:56.1472200]    Assembly:  [System.IO.Compression.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[20:08:56.1484290] 2023-07-25 17:08:56.248 System.IO.Compression.Tests[43690:25521723]    Exception messages: System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/containers/Bundle/Application/5CFA5A88-4C15-401E-A916-556A00578E7B/System.IO.Compression.Tests.app/ZLibTestData/TestDocument.pdf.z'.   Exception stack traces:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1484470] 2023-07-25 17:08:56.249 System.IO.Compression.Tests[43690:25521723]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1491640] 2023-07-25 17:08:56.249 System.IO.Compression.Tests[43690:25521723]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
[20:08:56.1491750]    at System.IO.File.ReadAllBytes(String path)
[20:08:56.1491810]    at StreamHelpers.CreateTempCopyStream(String path)
[20:08:56.1492290] 2023-07-25 17:08:56.249 System.IO.Compression.Tests[43690:25521723]    at LocalMemoryStream.readAppFileAsync(String testFile)
[20:08:56.1492360]    at System.IO.Compression.CompressionStreamUnitTestBase.BaseStream_ValidAfterDisposeWithTrueLeaveOpen(CompressionMode mode)
[20:08:56.1492410] --- End of stack trace from previous location ---
[20:08:56.1492450]    Execution time: 0.004419
[20:08:56.1496950] 2023-07-25 17:08:56.250 System.IO.Compression.Tests[43690:25521723] 5) 	[FAIL] System.IO.Compression.ZLibStreamUnitTests.FlushAsync_DuringFlushAsync   Test name: System.IO.Compression.ZLibStreamUnitTests.FlushAsync_DuringFlushAsync
[20:08:56.1497730] 2023-07-25 17:08:56.250 System.IO.Compression.Tests[43690:25521723]    Assembly:  [System.IO.Compression.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
[20:08:56.1506120] 2023-07-25 17:08:56.251 System.IO.Compression.Tests[43690:25521723]    Exception messages: System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/containers/Bundle/Application/5CFA5A88-4C15-401E-A916-556A00578E7B/System.IO.Compression.Tests.app/ZLibTestData/TestDocument.pdf.z'.   Exception stack traces:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1507180] 2023-07-25 17:08:56.251 System.IO.Compression.Tests[43690:25521723]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
[20:08:56.1507320]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
[20:08:56.1518130] 2023-07-25 17:08:56.252 System.IO.Compression.Tests[43690:25521723]    at System.IO.File.ReadAllBytes(String path)
[20:08:56.1518430]    at StreamHelpers.CreateTempCopyStream(String path)
[20:08:56.1518480]    at LocalMemoryStream.readAppFileAsync(String testFile)
[20:08:56.1518530]    at System.IO.Compression.CompressionStreamUnitTestBase.FlushAsync_DuringFlushAsync()
[20:08:56.1541760] 2023-07-25 17:08:56.253 System.IO.Compression.Tests[43690:25521723] --- End of stack trace from previous location ---
[20:08:56.1542050]    Execution time: 0.0029317

```

The `System.Formats.Tar.Tests` and `System.IO.Compression.Tests` are failing with System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/containers/Bundle/Application/5CFA5A88-4C15-401E-A916-556A00578E7B/<PATH>'.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=349967
**Error message validated:** `System.IO.DirectoryNotFoundException : Could not find a part of the path`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/26/2023 8:39:19 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[353600](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353600)|dotnet/runtime|[normal-System.IO.FileSystem.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353600&view=ms.vss-test-web.build-test-results-tab&runId=7431648&resultId=172236)||
|[353281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353281)|dotnet/runtime|[System.Formats.Tar.Tests.TarReader_File_Tests.Throw_FifoContainsNonZeroDataSection](https://dev.azure.com/dnceng-public/public/_build/results?buildId=353281&view=ms.vss-test-web.build-test-results-tab&runId=7424294&resultId=104203)|dotnet/runtime#89223|
|[352690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690)|dotnet/runtime|[System.IO.Compression.Tests.zip_UpdateTests.AddFileToArchive](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352690&view=ms.vss-test-web.build-test-results-tab&runId=7417440&resultId=134426)|dotnet/runtime#89431|
|[352583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352583)|dotnet/runtime|[System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectoryNormal](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352583&view=ms.vss-test-web.build-test-results-tab&runId=7407784&resultId=135326)|dotnet/runtime#89301|
|[352553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553)|dotnet/runtime|[System.IO.Compression.Tests.ZipFile_Create.CreateSetsExternalAttributesCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352553&view=ms.vss-test-web.build-test-results-tab&runId=7406784&resultId=143370)|dotnet/runtime#89498|
|[352503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352503)|dotnet/runtime|[System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectory_IncludeBaseDirectoryAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352503&view=ms.vss-test-web.build-test-results-tab&runId=7405516&resultId=133832)|dotnet/runtime#89428|
|[352326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326)|dotnet/runtime|[System.IO.Compression.Tests.ZipFile_Create.CreateSetsExternalAttributesCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352326&view=ms.vss-test-web.build-test-results-tab&runId=7400444&resultId=142710)||
|[351866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866)|dotnet/runtime|[System.IO.Compression.Tests.ZipFile_Create.CreateSetsExternalAttributesCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351866&view=ms.vss-test-web.build-test-results-tab&runId=7388668&resultId=145105)||
|[351758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758)|dotnet/runtime|[System.IO.Compression.Tests.ZipFile_Create.CreateSetsExternalAttributesCorrectly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351758&view=ms.vss-test-web.build-test-results-tab&runId=7386788&resultId=140061)|dotnet/runtime#89223|
|[350013](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350013)|dotnet/runtime|[System.Data.Tests.SqlTypes.SqlXmlTest.CreateReader_TestAgainstBaseline](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350013&view=ms.vss-test-web.build-test-results-tab&runId=7371070&resultId=122640)|dotnet/runtime#89392|
|[351065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065)|dotnet/runtime|[System.Formats.Tar.Tests.TarReader_Tests.TarReader_LeaveOpen_False_Async](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351065&view=ms.vss-test-web.build-test-results-tab&runId=7370030&resultId=104050)||
|[350917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350917)|dotnet/runtime|[System.IO.Compression.Tests.zip_UpdateTests.AddFileToArchive_AfterReading](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350917&view=ms.vss-test-web.build-test-results-tab&runId=7367000&resultId=136900)|dotnet/runtime#89308|
|[349967](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349967)|dotnet/runtime|[System.IO.Compression.Tests.zip_UpdateTests.UpdateReadTwice](https://dev.azure.com/dnceng-public/public/_build/results?buildId=349967&view=ms.vss-test-web.build-test-results-tab&runId=7347448&resultId=134066)|dotnet/runtime#88167|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|13|13|

**Comment by akoeplinger** [comment]
Interestingly I don't see this locally. Maybe related to building the projects on Helix? @steveisok any ideas?

**Comment by steveisok** [comment]
I'm assuming the test data comes from `System.IO.Compression.TestData`.  @akoeplinger I don't see where this is being packaged with the app and/or written to disk in the tests.

**Comment by akoeplinger** [comment]
Yeah it comes from `System.IO.Compression.TestData` and is supposed to just end up in the app. Not sure if this never worked or regressed recently?

**Comment by akoeplinger** [comment]
OK, I know what's going on. Locally the test files are in the correct subfolders inside the .app:
<img width="761" alt="image" src="https://github.com/dotnet/runtime/assets/1376924/1ae034fd-5567-43fc-92fc-365e427673ae">


But on the Helix-built one they end up in the root:

<img width="1137" alt="image" src="https://github.com/dotnet/runtime/assets/1376924/267d5d85-9f00-458e-a53f-cbb51b285ec0">

**Comment by kotlarmilos** [comment]
That must have regressed in https://github.com/dotnet/runtime/blob/f9377970b336b5d84ebdd58ff0e3ecc442f39a45/eng/testing/tests.ioslike.targets#L64-L80


The recursive dir didn't work for the runtime tests
```msbuild
<BundleFiles Condition="'%(AppleAssembliesToBundle._IsNative)' != 'true'"
                   Include="@(AppleAssembliesToBundle)"         TargetDir="publish\%(AppleAssembliesToBundle.RecursiveDir)" />
      <BundleFiles Include="@(AppleNativeFilesToBundle)"        TargetDir="publish\%(AppleNativeFilesToBundle.RecursiveDir)" />
      <BundleFiles Include="$(RuntimeConfigFilePath)"           TargetDir="publish" />
```

**Comment by akoeplinger** [comment]
> The RecursivDir didn't work for the runtime tests

Hmm we should figure out that problem then since the `RecursiveDir` is the correct thing in all of these.

**Comment by kotlarmilos** [comment]
Runtime tests intermediate path doesn't have full path resolved causing `RecursiveDir` not being populated.

```
/Users/miloskotlar/dotnet/runtime/artifacts/tests/coreclr/obj/ios.arm64.Release/Managed/./build/
```

Resolving the full path should fix the issue.
```
<IntermediateOutputPath>$([System.IO.Path]::GetFullPath('$(IntermediateOutputPath)'))</IntermediateOutputPath>
```
