### ISSUE TITLE
Unhandled exception while loading Microsoft.Extensions.Hosting.WindowsServices

### ISSUE THREAD

**Issue by vishnudas707** [dotnet/runtime#89553]
### Description

I have created a worker service in .NET 6, initially the project was using Microsoft.Extensions.Hosting.WindowsServices (7.0.0) version, later I have upgraded to 7.0.1, then i have re-published the project and deployed as windows service. When i try to start the service manually, I captured the exception from event viewer application

Application: QueueConsumer.exe
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: 
File name: 'Microsoft.Extensions.Hosting.WindowsServices, Version=7.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Program.<Main>$(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)

### Reproduction Steps

Upgrade Microsoft.Extensions.Hosting.WindowsServices from 7.0.0 to 7.0.1, publish and deployed the project as windows service and try to start the service, Observe the event viewer for error details

### Expected behavior

Windows service should start without any error/ correct exception should be available at event viewer.

### Actual behavior

It is throwing an unhandled exception occurred while loading the file

**Comment by vishnudas707** [comment]
Issue was related to difference in assembly manifest, obj folder pointing out to the old DLL, when publishing it as single file, unable to find the exception. Published as non-single file option and able to produce the exception
