### ISSUE TITLE
[wasm][debugger] NRE seen in proxy when loading symbols from symbol server

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#89700]
I saw this in https://dev.azure.com/dnceng-public/public/_build/results?buildId=355827&view=logs&j=1567862a-6a9e-5016-9353-cc84f1411dc4&t=95224710-367f-55b7-6b5e-1fa98616b1e8 which is on an unrelated https://github.com/dotnet/runtime/pull/88929 .

From the proxy log:
```
[ERR] DevToolsProxy-15: Failed to load symbols from symbol server. (Object reference not set to an instance of an object.)
[VRB] DevToolsProxy-15: SymbolChecksum: SHA256:35ddd68863cd8cde7a42eb5a29c56074321f4b909d6738bc80d64f7aeb466c72
[ERR] DevToolsProxy-15: Failed to load symbols from symbol server. (A task was canceled.)
```

The tests also timed out. The proxy shows tests running for a roughly  ~2mins in total.

cc @thaystg

**Comment by lewing** [comment]
This is likely a network error, what is the frequency?

**Comment by radical** [comment]
> This is likely a network error, what is the frequency?

No idea really. This is from the proxy log, so this was found only when grep'ing the proxy log.

note to self: log the trace as a debug message.

**Comment by radical** [comment]
This was hit [again](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-9bf149990937410c9c/chrome-DebuggerTests.SteppingTests/1/console.6ca2953a.log?helixlogtype=result):
```
[xUnit.net 00:02:04.49]     DebuggerTests.SteppingTests.SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain(secondServers: []) [FAIL]
  Failed DebuggerTests.SteppingTests.SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain(secondServers: []) [57 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 674
   at DebuggerTests.DebuggerTestBase.StepAndCheck(StepKind kind, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, Int32 times) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 629
   at DebuggerTests.SteppingTests.SteppingIntoLibrarySymbolsLoadedFromSymbolServerRemoveSymbolServerAndStepAgain(String[] secondServers) in /_/src/mono/wasm/debugger/DebuggerTestSuite/SteppingTests.cs:line 1196
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2023-08-20T21:04:18] DevToolsProxy-13 Error: Failed to load symbols from symbol server. (The operation was canceled.)
 | [2023-08-20T21:04:18] DevToolsProxy-13 Error: Failed to load symbols from symbol server. (Object reference not set to an instance of an object.)
 | [2023-08-20T21:04:18] DevToolsProxy-13 Error: Failed to load symbols from symbol server. (Object reference not set to an instance of an object.)
 | [2023-08-20T21:04:18] DevToolsProxy-13 Error: Failed to load symbols from symbol server. (Object reference not set to an instance of an object.)
```
