### ISSUE TITLE
ASP.NET CI Broken on Linux ARM and Linux musl-x64

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#89734]
Current ASP.NET CI is failing on Linux ARM and linux-musl-x64, with this stack trace:

Appeared when upgrading from `8.0.100-preview.7.23360.1` to `8.0.100-rc.1.23377.2`

```
  Unhandled exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at System.Object.GetType()
     at System.Xml.Serialization.CodeGenerator.GetVariableType(Object var)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(String source, Type elementType, Type stackType)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(String source, String arrayName, String choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, String checkSpecified, Boolean checkForNull, Boolean readOnly, Int32 fixupIndex, Int32 elementIndex)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteArray(String source, String arrayName, ArrayMapping arrayMapping, Boolean readOnly, Boolean isNullable, Int32 elementIndex)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(String source, String arrayName, String choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, String checkSpecified, Boolean checkForNull, Boolean readOnly, Int32 fixupIndex, Int32 elementIndex)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(StructMapping structMapping)
     at System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods()
     at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd()
     at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types)
     at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
     at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
     at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
     at Microsoft.DotNet.ToolPackage.ToolConfigurationDeserializer.Deserialize(String pathToXml)
     at Microsoft.DotNet.ToolPackage.ToolPackageInstance.DeserializeToolConfiguration(LockFileTargetLibrary library)
     at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetToolConfiguration()
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetCommands()
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
     at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
     at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
     at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
     at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
     at System.Linq.Parallel.SpoolingTaskBase.Work()
     at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location ---
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
     --- End of inner exception stack trace ---
     at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
     at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
     at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
     at System.Linq.Parallel.MergeExecutor`1.Execute()
     at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
     at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
     at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
     at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
     at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
     at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
     at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   ---> (Inner Exception dotnet/sdk#1) System.NullReferenceException: Object reference not set to an instance of an object.
     at System.Object.GetType()
     at System.Xml.Serialization.CodeGenerator.GetVariableType(Object var)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(String source, Type elementType, Type stackType)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(String source, String arrayName, String choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, String checkSpecified, Boolean checkForNull, Boolean readOnly, Int32 fixupIndex, Int32 elementIndex)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteArray(String source, String arrayName, ArrayMapping arrayMapping, Boolean readOnly, Boolean isNullable, Int32 elementIndex)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(String source, String arrayName, String choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, String checkSpecified, Boolean checkForNull, Boolean readOnly, Int32 fixupIndex, Int32 elementIndex)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(Member[] members, Member anyElement, String elementElseString)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(Member[] members, String elementElseString, String elseString, Member anyElement, Member anyText)
     at System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(StructMapping structMapping)
     at System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods()
     at System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd()
     at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types)
     at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
     at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
     at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
     at Microsoft.DotNet.ToolPackage.ToolConfigurationDeserializer.Deserialize(String pathToXml)
     at Microsoft.DotNet.ToolPackage.ToolPackageInstance.DeserializeToolConfiguration(LockFileTargetLibrary library)
     at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetToolConfiguration()
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at Microsoft.DotNet.ToolPackage.ToolPackageInstance.GetCommands()
     at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
     at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
     at System.Lazy`1.CreateValue()
     at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
     at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
     at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
     at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
     at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
     at System.Linq.Parallel.SpoolingTaskBase.Work()
     at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
     at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location ---
     at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
<---
  
/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Tools.proj(55,5): error MSB3073: The command ""/home/vsts/work/1/s/.dotnet/dotnet" tool restore" exited with code 1.
##[error].packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Tools.proj(55,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Restore) The command ""/home/vsts/work/1/s/.dotnet/dotnet" tool restore" exited with code 1.

Build FAILED.

/home/vsts/work/1/s/.packages/microsoft.dotnet.arcade.sdk/8.0.0-beta.23371.1/tools/Tools.proj(55,5): error MSB3073: The command ""/home/vsts/work/1/s/.dotnet/dotnet" tool restore" exited with code 1.
```

From: 
https://dev.azure.com/dnceng-public/public/_build/results?buildId=355133&view=logs&j=4a1f0fe1-d87a-57fd-c29d-71ea15e38f30&t=e34518a7-7ef2-58fc-776d-024f679b17d8

**Comment by jeffschwMSFT** [comment]
@mangod9 could you take a look?

**Comment by mangod9** [comment]
hi @sebastienros, is there a repro and/or dump available to investigate this further?

**Comment by eerhardt** [comment]
@mangod9 - https://github.com/dotnet/aspnetcore/pull/49763 should be repro'ing the failure.

**Comment by mangod9** [comment]
Ok will take a look. Does it need to build on Linux ARM machine, or is it a cross build from x64?

**Comment by eerhardt** [comment]
It looks like it is just a regular Linux Ubuntu.20.04 x64 machine.

**Comment by ericstj** [comment]
I was hypothesizing with @eerhardt that you might be able to repro by just rerunning `dotnet tool restore` in a loop, potentially deleting whatever it creates to ensure it has work to do.

**Comment by eerhardt** [comment]
FYI - we just merged https://github.com/dotnet/aspnetcore/pull/49761 which updates the SDK used by ASP.NET to `8.0.100-rc.1.23381.2`. This version is newer than the version we were seeing this failure in. So if it was a bug that was fixed, we will know if it no longer repros with the latest SDK.

**Comment by mangod9** [comment]
ok sounds good. I will try to repro it on linux x64 in the meantime.

**Comment by mangod9** [comment]
I am able to repro the sdk failure locally (for that sdk version), lldb unfortunately isnt cooperating to show the right stack.

**Comment by eerhardt** [comment]
@mangod9 - we've merged https://github.com/dotnet/aspnetcore/pull/49761 which updates to a newer SDK than what we were using when we saw this issue. I haven't seen the problem repro overnight, but will continue to monitor the CI for it.

**Comment by mangod9** [comment]
ok let me know if the issue repros on the latest sdk

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib anything here seem familiar? I looked at plausible commit ranges for the jit and nothing jumped out, either for intoducing a bug between Jul-10 and Jul-27, or resolving it since.

**Comment by eerhardt** [comment]
I'm going to close this as we aren't seeing this error on the latest builds (currently on SDK `8.0.100-rc.1.23381.2`). If it pops back up, we will re-open.

**Comment by mangod9** [comment]
Ok thanks. I was able to determine that it was AVing on `GetType` for `Microsoft.DotNet.ToolPackage.ToolConfigurationDeserialization.DotNetCliToolCommand`.
