### ISSUE TITLE
System.Data.Odbc PlatformNotSupportedException

### ISSUE THREAD

**Issue by esso23** [dotnet/runtime#898]
System.Data.Odbc v4.7.0
**Platform:** Windows Server 2019 version 1809 (build 17763.805)
**Runtime:** .NET Core 3.1 (Library with odbc dependency is .NET Standard 2.1)
**Exception:**
```
System.PlatformNotSupportedException: System.Data.ODBC is not supported on this platform.
   at System.Data.Odbc.OdbcConnection..ctor(String connectionString)
   at Connector.SysCfg.Odbc.OdbcSysCfgRepository..ctor(String dsnName) in D:\Sync\Repositories-Ipecon\paragon-platform\src\Connector.SysCfg\Odbc\OdbcSysCfgRepository.cs:line 28
...
```
**Code:**
```cs
mConnection = new OdbcConnection($"DSN={mDsnName};");
```

**Additional info:**
Just migrated from .NET Framework 4.6.1 to .NET Core 3.1 on the same machine. OdbcConnection worked fine on .NET Framework 4.6.1.
Application is x86.

**Comment by esso23** [comment]
Ok, I figured out it was because of the .NET Standard, which is not supported. I still see some problems with this though:
It's not the **platform** that is not supported. I was targeting win-x86 **platform** which **is** supported.
I had to go to dotnet/corefx repo, check the System.Data.Odbc.csproj to find out what's going on. On this line:
```
<GeneratePlatformNotSupportedAssemblyMessage Condition="'$(TargetGroup)' == 'netstandard'">SR.Odbc_PlatformNotSupported</GeneratePlatformNotSupportedAssemblyMessage>
```

I think the exception is misleading and should be changed to something else.

**Comment by ajcvickers** [comment]
@esso23 Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ligf** [comment]
I also encountered a similar problem
The class library refers to odbc, and the console refers to the dll file, and it will prompt "System.Data.ODBC is not supported on this platform."

**Comment by roji** [comment]
This looks like it should no longer be relevant, as there won't be further versions of .NET Standard and libraries are expected to simply target .NET.

**Comment by ActionNamou** [comment]
Same issue here. I am new to c# and I was trying to make a connection to an sql table to fill a dataset like this
public static DataSet GetDataSetFromAdapter(DataSet dataSet, string connectionString, string queryString)
        {
            using (OdbcConnection connection =
                       new OdbcConnection(connectionString))
            {
                OdbcDataAdapter adapter =
                    new OdbcDataAdapter(queryString, connection);

                // Open the connection and fill the DataSet.
                try
                {
                    connection.Open();
                    adapter.Fill(dataSet);
                    MessageBox.Show("here u did it");

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
                // The connection is automatically closed when the
                // code exits the using block.
            }
            return dataSet;
        }
Please let me know how we can fix this error.

**Comment by MicahKimel** [comment]
I am also having this issue in .net5.0, my code is similar to @ActionNamou

**Comment by BryanCrotaz** [comment]
I'm seeing this targetting .Net 6.0 and running as a service on a Windows 10 VM

**Comment by roji** [comment]
Can you please share a minimal, runnable code sample - including your csproj?

**Comment by MicahKimel** [comment]
@roji Sure, I'm probably doing something dumb, but here is a ASP.NET Core Web API template with TargetFramework `netcoreapp3.1` with @ActionNamou code in the default controller. I didn't include my odbc connection string in the controller, but it is valid and works fine in the `Server Explorer`. Thanks!

https://github.com/MicahKimel/SystemDataOdbcError

**Comment by MaceWindu** [comment]
@MicahKimel you should downgrade System.Data.Odbc to v6.0.1 https://github.com/dotnet/runtime/discussions/78550

**Comment by BryanCrotaz** [comment]
6.0.1 gives the same error when the project is entirely built in .Net 6.0.
```
System.PlatformNotSupportedException: System.Data.ODBC is not supported on this platform.
   at System.Data.Odbc.OdbcCommand..ctor(String cmdText)
   at Signergy.Queries.Installations.GetUpdatedCrewQuery.Run(Int32 since, CancellationToken cancellationToken)
   at Signergy.Repositories.CrewRepository.GetCrewModifiedSince(Int32 modifiedSince, CancellationToken cancellationToken)
   at ServiceProcess.SignergyAgentProcess.QueryCrew(CancellationToken cancellationToken)
   at ServiceProcess.SignergyAgentProcess.LoopingQuery(CancellationToken token)
```

**Comment by roji** [comment]
@BryanCrotaz and others, it will probably take me a few more days to look into this, thanks for your patience.

**Comment by BryanCrotaz** [comment]
@roji Emailed you source code in case that helps you diagnose.

**Comment by MaceWindu** [comment]
@BryanCrotaz I don't know what exactly wrong with your code, but workers build produce runtimes sub-folder with runtime-specific builds. For some reason when you run your program it cannot locate proper runtime for windows and default files from build root used. And they contain `netstandard2.0` version of odbc assembly, which always will throw such exception. You shold check you don't remove/have `windows` runtime subfolder

**Comment by chkrishna2001** [comment]
Is there a fix for this ?, I am getting this error when I use .net 5.0, but works when using .net 6.0

**Comment by ajcvickers** [comment]
@chkrishna2001 .NET 5 is out-of-support.

**Comment by ajcvickers** [comment]
I'm not aware of any workarounds.

**Comment by gordon-matt** [comment]
Just noticed this issue. Linking to one I recently opened myself: #88281

**Comment by ActionNamou** [comment]
Fixed this issue long ago but here is a little help for anyone new: Fix the issue by matching the System.Data.Odbc package version relative to the dotnet version you are on. Example, if you are on .net 5, go to System.Data.Odbc package and make sure you are also on one of the versions starting with 5.

**Comment by donnyv** [comment]
@ActionNamou That saved me. Thanks!

**Comment by rikvandenberg** [comment]
We are running into a similar issue recently on .NET 10 in combination with a Delphi Application. Our Delphi application loads .NET core plugins. And some plugins use OleDb or ODBC to make database connections.

Adding a `RuntimeIdentifier` to our plugin project has helped us to solve this issue. 

```
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
```

I guess this makes sense as it helps the NuGet package to make the correct decision which DLL it should use.
