### ISSUE TITLE
Assert in System.Net.Sockets.SocketAsyncEventArgs.CompleteAcceptOperation

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#89806]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=359274
Build error leg or test failing: System.Net.Http.Json.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/89537

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Sockets.SocketAsyncEventArgs.CompleteAcceptOperation",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Sample failure log:

```
Process terminated. Assertion failed.
   at System.Net.Sockets.SocketAsyncEventArgs.CompleteAcceptOperation(IntPtr acceptedFileDescriptor, Memory`1 socketAddress) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 36
   at System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept(Socket _, SafeSocketHandle handle, SafeSocketHandle acceptHandle, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 56
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2695
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(Socket socket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 965
   at System.Net.Sockets.Socket.AcceptAsync(Socket acceptSocket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 70
   at System.Net.Sockets.Socket.AcceptAsync() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 32
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 142
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 165
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
   at System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.<>c__DisplayClass14_2.<<GetFromJsonAsync_EnforcesTimeout>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http.Json/tests/FunctionalTests/HttpClientJsonExtensionsTests.cs:line 495
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.<>c__DisplayClass14_2.<GetFromJsonAsync_EnforcesTimeout>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 501
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2387
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 264
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2349
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2283
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2274
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 58
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
```

Seems to be introduced in https://github.com/dotnet/runtime/commit/e2c6fcfa8a621cbdbc89e1e686a3e4cc39088080#diff-31c708307a9d9c09e7e488a873803e62bfcc91a8d3fa6d9398d3c8bb13cff1afR36 cc @wfurt 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=359274
**Error message validated:** `System.Net.Sockets.SocketAsyncEventArgs.CompleteAcceptOperation`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/1/2023 8:29:07 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[361800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361800)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361800&view=ms.vss-test-web.build-test-results-tab&runId=7641448&resultId=209030)|dotnet/runtime#89912|
|[361711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361711)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361711&view=ms.vss-test-web.build-test-results-tab&runId=7639456&resultId=209066)|dotnet/runtime#89630|
|[361700](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361700)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361700&view=ms.vss-test-web.build-test-results-tab&runId=7638942&resultId=209066)|dotnet/runtime#88926|
|[361673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361673)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361673&view=ms.vss-test-web.build-test-results-tab&runId=7638584&resultId=208916)|dotnet/runtime#86888|
|[361597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361597)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361597&view=ms.vss-test-web.build-test-results-tab&runId=7636882&resultId=200059)|dotnet/runtime#89841|
|[361610](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361610)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361610&view=ms.vss-test-web.build-test-results-tab&runId=7636786&resultId=200207)|dotnet/runtime#89902|
|[361577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361577)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361577&view=ms.vss-test-web.build-test-results-tab&runId=7635454&resultId=209030)|dotnet/runtime#89900|
|[361506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361506)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361506&view=ms.vss-test-web.build-test-results-tab&runId=7634486&resultId=208910)|dotnet/runtime#89869|
|[361496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361496)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361496&view=ms.vss-test-web.build-test-results-tab&runId=7632000&resultId=208900)|dotnet/runtime#89894|
|[361438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361438)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361438&view=ms.vss-test-web.build-test-results-tab&runId=7630862&resultId=200386)|dotnet/runtime#89892|
|[361299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361299)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361299&view=ms.vss-test-web.build-test-results-tab&runId=7627726&resultId=208901)|dotnet/runtime#89882|
|[361145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361145)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361145&view=ms.vss-test-web.build-test-results-tab&runId=7623524&resultId=200204)|dotnet/runtime#89870|
|[361051](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361051)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361051&view=ms.vss-test-web.build-test-results-tab&runId=7622264&resultId=200201)|dotnet/runtime#87773|
|[360929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360929)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360929&view=ms.vss-test-web.build-test-results-tab&runId=7618340&resultId=200205)|dotnet/runtime#89863|
|[360734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360734)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360734&view=ms.vss-test-web.build-test-results-tab&runId=7612920&resultId=209025)|dotnet/runtime#89736|
|[360640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360640)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360640&view=ms.vss-test-web.build-test-results-tab&runId=7611794&resultId=208959)|dotnet/runtime#89813|
|[360105](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360105)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=360105&view=ms.vss-test-web.build-test-results-tab&runId=7597942&resultId=200199)|dotnet/runtime#89636|
|[359917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359917)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359917&view=ms.vss-test-web.build-test-results-tab&runId=7594830&resultId=208908)|dotnet/runtime#89827|
|[359852](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359852)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359852&view=ms.vss-test-web.build-test-results-tab&runId=7593990&resultId=200199)|dotnet/runtime#89822|
|[359833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359833)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359833&view=ms.vss-test-web.build-test-results-tab&runId=7593692&resultId=200197)|dotnet/runtime#89689|
|[359830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359830)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359830&view=ms.vss-test-web.build-test-results-tab&runId=7593536&resultId=200195)|dotnet/runtime#89531|
|[359812](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359812)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359812&view=ms.vss-test-web.build-test-results-tab&runId=7593254&resultId=208913)|dotnet/runtime#89809|
|[359866](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359866)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359866&view=ms.vss-test-web.build-test-results-tab&runId=7591136&resultId=200202)|dotnet/runtime#89799|
|[359677](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359677)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359677&view=ms.vss-test-web.build-test-results-tab&runId=7583548&resultId=209012)|dotnet/runtime#89583|
|[359495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359495)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359495&view=ms.vss-test-web.build-test-results-tab&runId=7579692&resultId=209045)|dotnet/runtime#89781|
|[359395](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359395)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359395&view=ms.vss-test-web.build-test-results-tab&runId=7579296&resultId=208891)|dotnet/runtime#89630|
|[359274](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359274)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359274&view=ms.vss-test-web.build-test-results-tab&runId=7574852&resultId=200193)|dotnet/runtime#89537|
|[359286](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359286)|dotnet/runtime|[System.Net.HttpListener.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=359286&view=ms.vss-test-web.build-test-results-tab&runId=7572130&resultId=209009)|dotnet/runtime#87773|
|[358747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358747)|dotnet/runtime|[System.Net.Http.Json.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358747&view=ms.vss-test-web.build-test-results-tab&runId=7558372&resultId=200335)|dotnet/runtime#89301|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|16|29|29|

**Comment by wfurt** [comment]
I was not able to reproduce it locally so far. It is not clear if that is macOS specific and if there was possibility that Accept did not get peer's address before -> this is what new Asser guards. 
cc: @rzikm for visibility

**Comment by ericstj** [comment]
Doesn't seem to be _specific_ to MacOS - looks like some hits are on linux too:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=359495&view=ms.vss-test-web.build-test-results-tab&runId=7579692&resultId=209045
https://dev.azure.com/dnceng-public/public/_build/results?buildId=359677&view=ms.vss-test-web.build-test-results-tab&runId=7583548&resultId=209012
