### ISSUE TITLE
Test failure: System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#89830]
**Failed in:** runtime-coreclr libraries-jitstress 20230801.1

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull
net8.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Http.Json.Functional.Tests.JsonContentTests_Sync.TestJsonContentContentTypeIsNotTheSameOnMultipleInstances
```

**Error message:**
```
 System.InvalidOperationException : This JsonSerializerOptions instance is read-only or has already been used in serialization or deserialization.
```

**Stack trace:**
```
    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerOptionsReadOnly(JsonSerializerContext context) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 214
   at System.Text.Json.JsonSerializerOptions.set_TypeInfoResolver(IJsonTypeInfoResolver value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 207
   at System.Net.Http.Json.Functional.Tests.JsonContentTestsBase.JsonContentMediaTypeDefaultIfNull() in /_/src/libraries/System.Net.Http.Json/tests/FunctionalTests/JsonContentTests.cs:line 161
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/v-bibu/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/v-bibu/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Http.Json.Functional.Tests.JsonContentTests_Async.JsonContentMediaTypeDefaultIfNull | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule

</body>

</html>

**Comment by eiriktsarpalis** [comment]
Looks like a race introduced by https://github.com/dotnet/runtime/pull/89729. I'll follow up with a fix shortly.
