### ISSUE TITLE
[wasm] Badly formatted stack trace with latest stable chrome (`115.*`)

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#89906]
Stack traces broke with the latest stable chrome, and are being fixed in [`89f6429` (#89890)](https://github.com/dotnet/runtime/pull/89890/commits/89f6429fcf8a065971dd1a0646c4a8b98d0d2116) .

But after the fix the traces look like the following, with the managed part appearing above the error message, follow by the native trace.

```
   at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTestHelper.ThrowFromJSExport(String message)
   at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTestHelper.__Wrapper_ThrowFromJSExport_817705034(JSMarshalerArgument* __arguments_buffer)
Error: -t-e-s-t-
    at sr (http://127.0.0.1:60345/_framework/dotnet.runtime.js:3:33284)
    at Br (http://127.0.0.1:60345/_framework/dotnet.runtime.js:3:42679)
    at http://127.0.0.1:60345/_framework/dotnet.runtime.js:3:40825
    at Module.catch1stack (http://127.0.0.1:60345/JavaScriptTestHelper.mjs:132:9)
    at http://127.0.0.1:60345/_framework/dotnet.runtime.js:3:36627
    at mr (http://127.0.0.1:60345/_framework/dotnet.runtime.js:3:37821)
    at do_icall (http://127.0.0.1:60345/_framework/dotnet.native.wasm:wasm-function[221]:0x19711)
    at do_icall_wrapper (http://127.0.0.1:60345/_framework/dotnet.native.wasm:wasm-function[108]:0x157bc)
    at mono_interp_exec_method (http://127.0.0.1:60345/_framework/dotnet.native.wasm:wasm-function[101]:0x9c92)
    at interp_runtime_invoke (http://127.0.0.1:60345/_framework/dotnet.native.wasm:wasm-function[141]:0x16cd7)
```
----

**Comment by radical** [comment]
cc @pavelsavara @kg

**Comment by kg** [comment]
Ideally the stack would start with the managed exception type + message, then we'd stitch in the managed stack, then the JS stack. This is tricky to get right since Error.stack's formatting isn't standardized.

**Comment by pavelsavara** [comment]
I'm not sure it's worth the risk/complexity/performance
