### ISSUE TITLE
HttpListener on linux vulnerability

### ISSUE THREAD

**Issue by CREAsTIVE** [dotnet/runtime#89983]
Every URI ending in % throws an uncatchable `IndexOutOfRange` exception. Attached is a code section of the decompiled version of the System.Net.HttpClient.dll library
![image](https://github.com/dotnet/core/assets/62616308/81d8c2e8-3853-4493-a407-28bb8728a60f)

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/e2b5936b758c10fe4f4f287393cb14a288febbd7/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerRequestUriBuilder.cs#L180-L186

There is an assert to prove that won't happen.

**Comment by karelz** [comment]
@CREAsTIVE the code you linked is used only on Windows. Can you post callstack from Linux on your Raspberry Pi?

**Comment by CREAsTIVE** [comment]
> @CREAsTIVE the code you linked is used only on Windows. Can you post callstack from Linux on your Raspberry Pi?

`Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.HttpListenerRequestUriBuilder.ParseRawPath(Encoding encoding)
   at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(Encoding encoding)
   at System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath()
   at System.Net.HttpListenerRequestUriBuilder.Build()
   at System.Net.HttpListenerRequest.FinishInitialization()
   at System.Net.HttpConnection.OnReadInternal(IAsyncResult ares)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aborted`

I took the compiled version of the dll from `.dotnet/shared/Microsoft.NETCore.App/7.0.9/System.Net.HttpListener.dll` (and therefore its removal caused an error)

Installed from guide: https://learn.microsoft.com/en-us/dotnet/iot/deployment
```
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS
echo 'export DOTNET_ROOT=$HOME/.dotnet' >> ~/.bashrc
echo 'export PATH=$PATH:$HOME/.dotnet' >> ~/.bashrc
source ~/.bashrc
```

**Comment by GerardSmit** [comment]
> @CREAsTIVE the code you linked is used only on Windows.

It seems this is not the case.

The Windows (http.sys) implementation is found in:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.HttpListener/src/System/Net/Windows

The comment and Debug.Assert (which is removed in release mode) were added in .NET Framework:
https://referencesource.microsoft.com/#System/net/System/Net/HttpListenerRequestUriBuilder.cs,237

This is when .NET wasn't cross-platform, but now there is a managed implementation as well: https://github.com/dotnet/runtime/tree/main/src/libraries/System.Net.HttpListener/src/System/Net/Managed

I think the managed implementation doesn't check the URL like http.sys does.
