### ISSUE TITLE
Test failure System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#90085]
**Failed in:** [runtime-coreclr libraries-pgo 20230806.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=364913&view=ms.vss-test-web.build-test-results-tab&runId=7716358&resultId=179801&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x86-CoreCLR_checked-fullpgo_random_gdv_methodprofiling_only-Windows.10.Amd64.Open
    - System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get
```

**Error message:**
```
Assert.Equal() Failure
Expected: 00:02:00
Actual:   00:01:00
```

**Stack trace:**
```
   at System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get() in /_/src/libraries/System.Transactions.Local/tests/TransactionManagerTest.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by AaronRobinsonMSFT** [comment]
Work was recently done in these Invoker paths.

/cc @steveharter

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr libraries-jitstress 20240103.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=514467&view=ms.vss-test-web.build-test-results-tab&runId=12061580&resultId=170787&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get
```

**Error message:**
```
Assert.Equal() Failure: Values differ
Expected: 00:02:00
Actual:   00:01:00
```

**Stack trace:**
```
   at System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get() in /_/src/libraries/System.Transactions.Local/tests/TransactionManagerTest.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by VincentBu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20240211.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=561955&view=ms.vss-test-web.build-test-results-tab&runId=13416210&resultId=174359&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-CoreCLR_checked-fullpgo_random_gdv_methodprofiling_only-Ubuntu.2204.Amd64.Open
    - System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 00:02:00
Actual:   00:01:00
```

**Stack trace:**
```
    at System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get() in /_/src/libraries/System.Transactions.Local/tests/TransactionManagerTest.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by BruceForstall** [comment]
@AndyAyersMS Looks like it mostly fails in PGO stress?

**Comment by AndyAyersMS** [comment]
The test is
```C#
        [Fact]
        public void DefaultTimeout_MaxTimeout_Set_Get()
        {
            TimeSpan tsDefault = TimeSpan.Parse("00:02:00");
            TransactionManager.DefaultTimeout = tsDefault;
            Assert.Equal(tsDefault, TransactionManager.DefaultTimeout);
```
where the initial value of the default timeout is `01:00`.

The property getter/setter is nontrivial

https://github.com/dotnet/runtime/blob/eece6a62d2694da768c5c9f246a96feb528f6bae/src/libraries/System.Transactions.Local/src/System/Transactions/TransactionManager.cs#L292-L344

The original PR #71703 noted there was a potential problem with tearing reads on a 32 bit platform, I wonder if it is still there but just harder to observe, and these tests manage to delay execution just the right way (on occasion).

FYI @mconnew in case this is a latent test issue.

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-pgo 20240310.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596869&view=ms.vss-test-web.build-test-results-tab&runId=14453666&resultId=163123&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-CoreCLR_checked-jitosr_stress_random-Windows.10.Amd64.Open
    - System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 00:02:00
Actual:   00:01:00
```

**Stack trace:**
```
   at System.Transactions.Tests.TransactionManagerTest.DefaultTimeout_MaxTimeout_Set_Get() in /_/src/libraries/System.Transactions.Local/tests/TransactionManagerTest.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by AndyAyersMS** [comment]
Seems to no longer be a problem.
