### ISSUE TITLE
[wasm] Blazor, or console template with AOT/relinking fails with: `mono_wasm_load_runtime () failed Error: unreachable`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#90111]
[log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89754-merge-b12d1eaba86b4304bc/Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests3/1/console.f423f3b4.log?helixlogtype=result):
These were hit on https://github.com/dotnet/runtime/pull/89754:

`Wasm.Build.Tests.Blazor.MiscTests3.WithDllImportInMainAssembly(config: "Debug", build: False, publish: True) ` ([log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89754-merge-b12d1eaba86b4304bc/Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests3/1/console.f423f3b4.log?helixlogtype=result)):
```
        Launching chrome ('/root/helix/work/correlation/chrome-linux/chrome') via playwright with args = --explicitly-allowed-ports=46619
        Waiting for page to load
        [error] MONO_WASM: mono_wasm_load_runtime () failed Error: unreachable
            at _mono_wasm_debugger_log (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:93622)
            at http://127.0.0.1:46619/_framework/dotnet.native.wasm:wasm-function[133]:0x5f9e
            at http://127.0.0.1:46619/_framework/dotnet.native.wasm:wasm-function[5794]:0x18405c
            at http://127.0.0.1:46619/_framework/dotnet.native.wasm:wasm-function[5768]:0x180cdb
            at Module._mono_wasm_load_runtime (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:110277)
            at ccall (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:101958)
            at Object.mono_wasm_load_runtime (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:102338)
            at Uu (http://127.0.0.1:46619/_framework/dotnet.runtime.8.0.0-ci.zvz55o64uz.js:3:207818)
            at http://127.0.0.1:46619/_framework/dotnet.runtime.8.0.0-ci.zvz55o64uz.js:3:197259
            at http://127.0.0.1:46619/_framework/dotnet.runtime.8.0.0-ci.zvz55o64uz.js:3:197939
        [error] MONO_WASM: Error: unreachable
            at _mono_wasm_debugger_log (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:93622)
            at http://127.0.0.1:46619/_framework/dotnet.native.wasm:wasm-function[133]:0x5f9e
            at http://127.0.0.1:46619/_framework/dotnet.native.wasm:wasm-function[5794]:0x18405c
            at http://127.0.0.1:46619/_framework/dotnet.native.wasm:wasm-function[5768]:0x180cdb
            at Module._mono_wasm_load_runtime (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:110277)
            at ccall (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:101958)
            at Object.mono_wasm_load_runtime (http://127.0.0.1:46619/_framework/dotnet.native.8.0.0-ci.lglyt991p3.js:8:102338)
            at Uu (http://127.0.0.1:46619/_framework/dotnet.runtime.8.0.0-ci.zvz55o64uz.js:3:207818)
            at http://127.0.0.1:46619/_framework/dotnet.runtime.8.0.0-ci.zvz55o64uz.js:3:197259
            at http://127.0.0.1:46619/_framework/dotnet.runtime.8.0.0-ci.zvz55o64uz.js:3:197939
        [error] Error: Failed to start platform. Reason: Error: unreachable
            at Yt (http://127.0.0.1:46619/_framework/blazor.webassembly.js:1:55058)
            at async on (http://127.0.0.1:46619/_framework/blazor.webassembly.js:1:56628)
```

Similar failures in
[WasmTemplateTests](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89754-merge-b12d1eaba86b4304bc/Workloads-NoWebcil-Wasm.Build.Tests.WasmTemplateTests/1/console.74608858.log?helixlogtype=result), and [Blazor.SimpleRunTests]https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-89754-merge-b12d1eaba86b4304bc/Workloads-NoWebcil-Wasm.Build.Tests.Blazor.SimpleRunTests/1/console.c3ec463d.log?helixlogtype=result).

cc @kg @pavelsavara

**Comment by pavelsavara** [comment]
This is not calling the imports too early (I suspected on the chat), because there is `_mono_wasm_load_runtime` on the stack.\

Probably emcc `applyImportAndExportNameChanges` during re-link 
Then `replace_linker_placeholders` setting early enough, but with un-minified names, which the WASM side doesn't bind to.

I wonder if we could do it by index rather than by name.
