### ISSUE TITLE
ArgumentException: maccatalyst does not have a valid platform name

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#90313]
Error like:
```
src/mono/msbuild/common/LibraryBuilder.targets(28,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "LibraryBuilderTask" task failed unexpectedly.
System.ArgumentException: maccatalyst does not have a valid platform name
   at Microsoft.Apple.Build.AppleSdk.GetPlatformName(String targetOS) in /_/src/tasks/MobileBuildTasks/Apple/AppleSdk.cs:line 138
   at Microsoft.Apple.Build.AppleSdk..ctor(String targetOS, TaskLoggingHelper logger) in /_/src/tasks/MobileBuildTasks/Apple/AppleSdk.cs:line 25
   at Microsoft.Apple.Build.AppleProject..ctor(String projectName, String runtimeIdentifier, TaskLoggingHelper logger) in /_/src/tasks/MobileBuildTasks/Apple/AppleProject.cs:line 31
   at LibraryBuilderTask.BuildAppleLibrary(List`1 sources, List`1 libs, List`1 linkerArgs) in /_/src/tasks/LibraryBuilder/LibraryBuilder.cs:line 401
   at LibraryBuilderTask.Execute() in /_/src/tasks/LibraryBuilder/LibraryBuilder.cs:line 156
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=368974
Build error leg or test failing: 
Pull request: https://github.com/dotnet/runtime/pull/90119

## Error Message
```json
{
  "ErrorMessage": "maccatalyst does not have a valid platform name",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=368974
**Error message validated:** `maccatalyst does not have a valid platform name`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/10/2023 2:07:01 PM UTC

**Comment by ivanpovazan** [comment]
Closing as fixed via: https://github.com/dotnet/runtime/pull/90237
