### ISSUE TITLE
[wasm][debugger] Firefox test failure `EvaluateOnCallFrameTests.EvaluateObjectIndexingByNonIntConst`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#90354]
[Rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496), and [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-d7fabad884f043ff8e/firefox-DebuggerTests.EvaluateOnCallFrameTests/1/console.d72765af.log?helixlogtype=result):

```
[xUnit.net 00:09:18.13]     DebuggerTests.EvaluateOnCallFrameTests.EvaluateObjectIndexingByNonIntConst [FAIL]
  Failed DebuggerTests.EvaluateOnCallFrameTests.EvaluateObjectIndexingByNonIntConst [11 s]
  Error Message:
   Assert.True() Failure
Expected: True
Actual:   (null)
  Stack Trace:
     at DebuggerTests.EvaluateOnCallFrameTests.<EvaluateObjectIndexingByNonIntConst>b__26_0(JObject pause_location) in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 646
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 372
   at DebuggerTests.EvaluateOnCallFrameTests.EvaluateObjectIndexingByNonIntConst() in /_/src/mono/wasm/debugger/DebuggerTestSuite/EvaluateOnCallFrameTests.cs:line 625
--- End of stack trace from previous location ---
  Standard Output Messages:
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Information: [testId: 31] New test request for test id 31
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [31] Starting /root/helix/work/correlation/firefox/firefox with -profile /root/helix/work/workitem/e/debugger-test/AppBundle/test-profile-31 -headless -new-instance -private -start-debugger-server 6531 -UILocale en-US http://localhost:9400/debugger-driver.html
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [testId: 30] TestHarnessStartup done
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: TestHarnessStartup: closing for 30
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [test_id: 30] FirefoxProvider Dispose
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stderr *** You are running in headless mode.
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout [GFX1-]: glxtest: libpci missing
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout [GFX1-]: glxtest: libGL.so.1 missing
 | [2023-08-10T09:35:09] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout [GFX1-]: No GPUs detected via PCI
 | [2023-08-10T09:35:10] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout Started devtools server on 6531
 | [2023-08-10T09:35:10] Inspector-31 Information: waiting for the runtime to be ready
 | [2023-08-10T09:35:10] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout [GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
 | [2023-08-10T09:35:11] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout console.warn: TopSitesFeed: Contile provided more links than permitted. (3 received, limit is 2)
 | [2023-08-10T09:35:12] FirefoxMonoProxy-31 Error: Cannot respond to command: msg-:::0:::server1.conn0.windowGlobal10737418242/windowGlobalTarget2 with result: [Result: IsOk: True, IsErr: False, Value: {
 |                                                    "result": {
 |                                                      "value": {
 |                                                        "type": "frameUpdate",
 |                                                        "frames": [
 |                                                          {
 |                                                            "id": 26,
 |                                                            "isTopLevel": true,
 |                                                            "url": "http://localhost:9400/debugger-driver.html",
 |                                                            "title": ""
 |                                                          }
 |                                                        ],
 |                                                        "from": "server1.conn0.windowGlobal10737418242/windowGlobalTarget2"
 |                                                      }
 |                                                    }
 |                                                  }, Error:  ] - command is not pending
 | [2023-08-10T09:35:12] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout Handler function DebuggerTransport instance's this.hooks.onPacket threw an exception: TypeError: to is undefined
 | [2023-08-10T09:35:12] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout Stack: onPacket@resource://devtools/server/devtools-server-connection.js:355:23
 | [2023-08-10T09:35:12] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout _onJSONObjectReady/<@resource://devtools/shared/transport/transport.js:463:22
 | [2023-08-10T09:35:12] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22
 | [2023-08-10T09:35:12] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout exports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22
 | [2023-08-10T09:35:12] DebuggerTests.TestHarnessProxy Debug: [testId: 31] browser-stdout Line: 355, column: 23
...
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
Disabled by https://github.com/dotnet/runtime/pull/90347 as unsupported.
