### ISSUE TITLE
New "an operation is not legal in the current state" failures from Type.GetType

### ISSUE THREAD

**Issue by bricelam** [dotnet/runtime#90415]
### Description

After some recent dependency updates, we're seeing occasional failures on the efcore CI. They seem so stem from [this code](https://github.com/dotnet/efcore/blob/d64788ec31bdb0bad17348a788df094613c15b7b/src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs#L55-L88) inside a static construstor:

```cs
var appDataType = Type.GetType("Windows.Storage.ApplicationData, Microsoft.Windows.SDK.NET");
```

/cc @ajcvickers

### Reproduction Steps

None. The failures are infrequent. The most recent one was from the OSX.1100.Amd64.Open pool on Helix.

### Expected behavior

We only recently started seeing these failures.

### Actual behavior

```
Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Sqlite [FAIL]
  System.TypeInitializationException : The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
  ---- System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Windows.SDK.NET, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
  -------- System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Stack Trace:
    D:\a\_work\1\s\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs(95,0): at Microsoft.Data.Sqlite.SqliteConnection..ctor()
```

### Regression?

Yes. This code has worked consistently for several releases.

### Known Workarounds

We could safely swallow the exception. This code is not critical and is only here to make the out-of-box experience on net8.0-windows (and uap10.0) better. The user can always call `sqlite3_win32_set_directory` themselves.

### Configuration

```
.NET SDK:
 Version:   8.0.100-rc.1.23407.2
 Commit:    c7045b1a4a

Host:
  Version:      8.0.0-rc.1.23402.2
  Commit:       0d6d6c3435

.NET SDKs installed:
  8.0.100-rc.1.23407.2

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-rc.1.23401.1
  Microsoft.NETCore.App 8.0.0-rc.1.23381.3
  Microsoft.NETCore.App 8.0.0-rc.1.23402.2
```

**Comment by jkotas** [comment]
Do you have any `AppDomain.AssemblyResolve` events registered or use AssemblyLoadContext to customize assembly loading behavior?

The most likely explanation of this exception stacktrace is that you have `AppDomain.AssemblyResolve` event handler registered, the event handler has a race condition - it accesses a global collection singleton while some other thread is modifying it and this throws InvalidOperationException intermittently, this InvalidOperationException exception gets wrapped in FileLoadException.

I do not think you should swallow this exception. It points to a race condition in your test infrastructure that can cause other similar problems.

**Comment by bricelam** [comment]
We don't in our product or test code. I wonder if something in xUnit.net or some other testing infrastructure code does...

**Comment by jkotas** [comment]
Yes, xunit had a bug that manifested as this exception.

Make sure that you have xunit with this fix: https://github.com/xunit/xunit/issues/1842

**Comment by jkotas** [comment]
xunit PR with the fix: https://github.com/xunit/xunit/pull/2382

**Comment by bricelam** [comment]
Our version of xUnit.net (2.4.2 brought in by Arcade) contains that fix.

**Comment by jkotas** [comment]
I think that the xunit fix is incomplete, or there is some other assembly resolver registered with similar bug. Can you find out the list of all assembly resolvers that are registered during the test that hits this crash?

**Comment by bricelam** [comment]
AFAICT nothing has been added to the AssemblyResolve event...

**Comment by jkotas** [comment]
We need more details about when this is happening. Could you please share the test log next time that it happens?

**Comment by bricelam** [comment]
```
    Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Sqlite [FAIL]
      System.TypeInitializationException : The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
      ---- System.IO.FileLoadException : Could not load file or assembly 'Windows, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. An operation is not legal in the current state. (0x80131509)
      -------- System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
      Stack Trace:
        D:\a\_work\1\s\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs(95,0): at Microsoft.Data.Sqlite.SqliteConnection..ctor()
        D:\a\_work\1\s\src\EFCore.Sqlite.Core\Update\Internal\SqliteUpdateSqlGenerator.cs(31,0): at Microsoft.EntityFrameworkCore.Sqlite.Update.Internal.SqliteUpdateSqlGenerator..ctor(UpdateSqlGeneratorDependencies dependencies)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
           at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
        D:\a\_work\1\s\src\EFCore\Internal\DbContextServices.cs(70,0): at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
        D:\a\_work\1\s\src\EFCore\Internal\DbContextServices.cs(116,0): at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
        D:\a\_work\1\s\src\EFCore\Infrastructure\EntityFrameworkServicesBuilder.cs(284,0): at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
        D:\a\_work\1\s\src\EFCore\DbContext.cs(468,0): at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
        D:\a\_work\1\s\src\EFCore\DbContext.cs(450,0): at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
        D:\a\_work\1\s\src\EFCore\DbContext.cs(404,0): at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
        D:\a\_work\1\s\src\EFCore\DbContext.cs(2215,0): at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
        D:\a\_work\1\s\src\EFCore\Infrastructure\Internal\InfrastructureExtensions.cs(34,0): at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService(IInfrastructure`1 accessor, Type serviceType)
        D:\a\_work\1\s\src\EFCore\Infrastructure\Internal\InfrastructureExtensions.cs(24,0): at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
        D:\a\_work\1\s\src\EFCore\Infrastructure\AccessorExtensions.cs(42,0): at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
        D:\a\_work\1\s\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpRuntimeModelCodeGeneratorTest.cs(12312,0): at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Test(DbContext context, CompiledModelCodeGenerationOptions options, Action`1 assertScaffold, Action`1 assertModel, Type additionalDesignTimeServices, Action`1 useContext, String expectedExceptionMessage)
        D:\a\_work\1\s\test\EFCore.Design.Tests\Scaffolding\Internal\CSharpRuntimeModelCodeGeneratorTest.cs(11600,0): at Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Sqlite()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
           at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
           at System.Reflection.TypeNameParser.ResolveAssembly(String assemblyName)
           at System.Reflection.TypeNameParser.GetType(String typeName, ReadOnlySpan`1 nestedTypeNames, String assemblyNameIfAny)
           at System.Reflection.TypeNameParser.Parse()
           at System.Reflection.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Assembly requestingAssembly, Boolean throwOnError, Boolean ignoreCase, Boolean extensibleParser)
           at System.Type.GetType(String typeName)
        D:\a\_work\1\s\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs(55,0): at Microsoft.Data.Sqlite.SqliteConnection..cctor()
        ----- Inner Stack Trace -----
           at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
           at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
           at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
```

**Comment by bricelam** [comment]
Hmm. Looks like SqlClient is hooking AssemblyLoadContext.Resolving:

* Microsoft.Data.SqlClient.SqlConfigurableRetryLogicLoader.Default_Resolving()

I'll move the issue to them.

**Comment by bricelam** [comment]
Can't transfer. Filed https://github.com/dotnet/SqlClient/issues/2134

**Comment by bricelam** [comment]
Although I'm not 100% sure it's their implementation that's the problem. This part of the stack trace looks sus:

```
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
```

**Comment by jkotas** [comment]
> This part of the stack trace looks sus:

Right, this means that there is a resolver that calls Dictionary, without proper synchronization. The SqlClient resolver does not use Dictionary, so it is probably some other one. Unfortunately, the resolver method frame was optimized out so we cannot tell the name of the resolver that caused this problem.

You can try reproducing the problem with `DOTNET_JITMinOpts=1`. It will disable the JIT optimizations and we should see the name of the resolver in the stacktrace.

Also, could you please share a link to the full CI log when it hit the problem? It would be useful to see all details - the exact commit and build flavor that the failure happened on, the name of the test that hit the problem and when the problem occurred during the run, etc.

**Comment by bricelam** [comment]
Here's the latest:

https://dnceng-public.visualstudio.com/public/_build/results?buildId=380896&view=results

It happens pretty regularly. (About once every two days.)

**Comment by bricelam** [comment]
This was one of the first times we saw it fail on `main` (if failed on a few PRs before that):

https://dnceng-public.visualstudio.com/public/_build/results?buildId=370139&view=results

Shortly before, we updated our SDK from 8.0.100-rc.1.23381.2 to 8.0.100-rc.1.23407.2 and our runtime packages from 8470b87bcb366cc06486c6f7aa23ae6de3259eba to 0d6d6c343556d8aaae49347c82b09281f8968196.

**Comment by jkotas** [comment]
I have stepped through the resolvers registered when the test is running under debugger. There are two resolvers registered: the xunit one and the SqlClient one that you have linked to above.

I think the race condition is in the xunit resolver:

xunit registers the resolver here: https://github.com/xunit/xunit/blob/v2/src/common/AssemblyResolution/AssemblyHelper_NetCoreApp.cs#L56

The resolver calls `DependencyContextAssemblyCache.LoadManagedDll` here: https://github.com/xunit/xunit/blob/v2/src/common/AssemblyResolution/AssemblyHelper_NetCoreApp.cs#L84-L85

The first thing that `DependencyContextAssemblyCache.LoadManagedDll` does is accessing Dictionary without any locks taken: https://github.com/xunit/xunit/blob/v2/src/common/AssemblyResolution/DependencyContextAssemblyCache.cs#L156-L158

**Comment by jkotas** [comment]
If you are seeing this problem on macOS only, you can workaround it by loading the Windows-specific assemblies in `SqliteConnection` only on Windows. It is general goodness - it will avoid a bunch of unnecessary work and swallowed exceptions on non-Windows platforms.

Otherwise, this should be tracked in dotnet/arcade and/or xunit/xunit. @dotnet/area-infrastructure-libraries should be able to comment on what it would take to service this issue in xunit.

**Comment by bricelam** [comment]
We've seen it on Windows too. Also, I don't think there was a good netstandard2.0 API for detecting the runtime, so we just always did it. We multi-target now though, so it could certainly be optimized on net6.0+.

**Comment by jkotas** [comment]
>I don't think there was a good netstandard2.0 API 

`RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` is netstandard2.0.

**Comment by agocke** [comment]
Closing as not a runtime issue.
