### ISSUE TITLE
Official build is failing on OneLocBuild step

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#90466]
in [runtime-official-build](https://dev.azure.com/dnceng/internal/_build?definitionId=679&_a=summary) OneLocBuild started failing in this range [dotnet/runtime@786b987...64a6771](https://github.com/dotnet/runtime/compare/786b9872ad306d5b0febdc2e6c820b69e0e232dc...64a6771016359c48133bac44f3a1d4cd9b611c42)

https://github.com/dotnet/sdk/pull/34522#issuecomment-1676044841

**Comment by lewing** [comment]
cc @dotnet/arcade-contrib

**Comment by lewing** [comment]
@NikolaMilosavljevic could this be related to your xliff-tasks change?

**Comment by lewing** [comment]
```

OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.ResponseManager.ExecuteAll(IDictionary`2 lsBuildPaths, CancellationToken cancelToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\ResponseManager.cs:line 139
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.RunBuild(Project project, Int64 index, CancellationToken cancellationToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 191
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.<>c__DisplayClass14_0.<Execute>b__0(Project project, ParallelLoopState state, Int64 index) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 103
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
OneLocBuildClient.exe Information: 0 :    --- End of inner exception stack trace ---
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`3 body)
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.Execute(LocArtifact artifact, Settings settings, CancellationToken cancellationToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 111
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Program.Execute(IEnumerable`1 artifactPaths, Boolean isLocalBuild) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Program.cs:line 160
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Program.Main(String[] args) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Program.cs:line 114
OneLocBuildClient.exe Information: 0 : ---> (Inner Exception #0) System.Exception: Running LSBuild failed with exit codes '8'.
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.ResponseManager.ExecuteAll(IDictionary`2 lsBuildPaths, CancellationToken cancelToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\ResponseManager.cs:line 139
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.RunBuild(Project project, Int64 index, CancellationToken cancellationToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 191
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.<>c__DisplayClass14_0.<Execute>b__0(Project project, ParallelLoopState state, Int64 index) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 103
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
OneLocBuildClient.exe Information: 0 : 
```
https://dev.azure.com/dnceng/internal/_build/results?buildId=2242185&view=logs&j=6aa31087-d1b8-5ee1-af29-f0fe63353381&t=f5f0ecb8-e09a-5b29-99cb-311e048f2c1c&l=394

**Comment by lewing** [comment]
blocking https://github.com/dotnet/sdk/pull/34522 and  https://github.com/dotnet/installer/pull/17118

**Comment by akoeplinger** [comment]
I opened a PR to disable OneLocBuild for now: https://github.com/dotnet/runtime/pull/90480

**Comment by ericstj** [comment]
Here's more of the failure text:
```
OneLocBuildClient.exe Information: 0 : [20:06:25 ERR] LSBuild :   > Starting 'parse /w 0 /s "D:\a\_work\1\s\OneLocBuild\packages\LSBuild.XLoc.7.2.20223\tools\netfx\default.lss" /s "D:\a\_work\1\s\eng\common\loc\P22DotNetHtmlLocalization.lss" /o "D:\a\_work\1\a\loc\en\src\installer\pkg\sfx\bundle\osx_resources\conclusion.html.lcg" "D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\conclusion.html" '
OneLocBuildClient.exe Information: 0 : LSBuild :     > Parsing File 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\conclusion.html'
OneLocBuildClient.exe Information: 0 : LSBuild :       > Parsing File 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\conclusion.html'
OneLocBuildClient.exe Information: 0 : LSBuild :         > Parsing File 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\conclusion.html'
OneLocBuildClient.exe Information: 0 : LSBuild :           Error PARSE106 - All Parse retry attempts failed.
OneLocBuildClient.exe Information: 0 : LSBuild :           Error BL1006 - There are no parsers that can parse file 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\conclusion.html' successfully
OneLocBuildClient.exe Information: 0 : LSBuild :         < Done.
OneLocBuildClient.exe Information: 0 : LSBuild :       < Done.
OneLocBuildClient.exe Information: 0 : LSBuild :     < Done.
OneLocBuildClient.exe Information: 0 : LSBuild :   < The command completed successfully.
OneLocBuildClient.exe Information: 0 : LSBuild :   Info BT1048 - {"Elapsed Time (ms)":"4675.9447"}
OneLocBuildClient.exe Information: 0 : LSBuild :   > Starting 'parse /w 0 /s "D:\a\_work\1\s\OneLocBuild\packages\LSBuild.XLoc.7.2.20223\tools\netfx\default.lss" /s "D:\a\_work\1\s\eng\common\loc\P22DotNetHtmlLocalization.lss" /o "D:\a\_work\1\a\loc\en\src\installer\pkg\sfx\bundle\osx_resources\welcome.html.lcg" "D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\welcome.html" '
OneLocBuildClient.exe Information: 0 : LSBuild :     > Parsing File 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\welcome.html'
OneLocBuildClient.exe Information: 0 : LSBuild :       > Parsing File 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\welcome.html'
OneLocBuildClient.exe Information: 0 : LSBuild :         > Parsing File 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\welcome.html'
OneLocBuildClient.exe Information: 0 : LSBuild :           Error PARSE106 - All Parse retry attempts failed.
OneLocBuildClient.exe Information: 0 : LSBuild :           Error BL1006 - There are no parsers that can parse file 'D:\a\_work\1\s\src\installer\pkg\sfx\bundle\osx_resources\welcome.html' successfully
OneLocBuildClient.exe Information: 0 : LSBuild :         < Done.
OneLocBuildClient.exe Information: 0 : LSBuild :       < Done.
OneLocBuildClient.exe Information: 0 : LSBuild :     < Done.
OneLocBuildClient.exe Information: 0 : LSBuild :   < The command completed successfully.
OneLocBuildClient.exe Information: 0 : LSBuild :   Info BT1048 - {"Elapsed Time (ms)":"3015.0379"}
OneLocBuildClient.exe Information: 0 : 
OneLocBuildClient.exe Information: 0 : [20:06:28 INF] Localization done for project 'D:\a\_work\1\s\eng\Localize\LocProject.json', Elapsed time '13.1277248' seconds.
OneLocBuildClient.exe Information: 0 : [20:06:28 ERR] Localization build failed.
OneLocBuildClient.exe Information: 0 : System.AggregateException: One or more errors occurred. ---> System.Exception: Running LSBuild failed with exit codes '8'.
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.ResponseManager.ExecuteAll(IDictionary`2 lsBuildPaths, CancellationToken cancelToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\ResponseManager.cs:line 139
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.RunBuild(Project project, Int64 index, CancellationToken cancellationToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 191
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.<>c__DisplayClass14_0.<Execute>b__0(Project project, ParallelLoopState state, Int64 index) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 103
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
OneLocBuildClient.exe Information: 0 :    --- End of inner exception stack trace ---
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`3 body)
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.Execute(LocArtifact artifact, Settings settings, CancellationToken cancellationToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 111
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Program.Execute(IEnumerable`1 artifactPaths, Boolean isLocalBuild) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Program.cs:line 160
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Program.Main(String[] args) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Program.cs:line 114
OneLocBuildClient.exe Information: 0 : ---> (Inner Exception #0) System.Exception: Running LSBuild failed with exit codes '8'.
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.ResponseManager.ExecuteAll(IDictionary`2 lsBuildPaths, CancellationToken cancelToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\ResponseManager.cs:line 139
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.RunBuild(Project project, Int64 index, CancellationToken cancellationToken) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 191
OneLocBuildClient.exe Information: 0 :    at Microsoft.Localization.XLoc.Build.Local.LSBuild.<>c__DisplayClass14_0.<Execute>b__0(Project project, ParallelLoopState state, Int64 index) in D:\Repos\ceapex\CEINTL\SWSys-Build-XLoc\src\XLoc\Build\Local\LSBuild.cs:line 103
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
OneLocBuildClient.exe Information: 0 :    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
```

I found another successful build and it had the same LSBuild.Xloc package version, so that doesn't seem to have changed.  We'll need to figure this out and fix it for RC2.  @NikolaMilosavljevic cc @cristianosuzuki77

**Comment by carlossanlop** [comment]
FYI per the instructions here: https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md#if-youre-releasing-from-a-branch-other-than-main-including-servicing-branches

I temporarily changed the oneloc yml mirror branch in main to release/8.0: https://github.com/dotnet/runtime/pull/90812

And  backported it to release/8.0: https://github.com/dotnet/runtime/pull/90813

The main change will be reverted once we ship.

**Comment by carlossanlop** [comment]
@akoeplinger ah, I need to re-enable OneLocBuild, since you disabled it here: https://github.com/dotnet/runtime/pull/90480

I'll include it in my PR.

**Comment by agocke** [comment]
@carlossanlop This has been updated now
