### ISSUE TITLE
[NativeAOT] Tests failing `nativeaot/SmokeTests/StackTraceMetadata/StackTraceMetadata/StackTraceMetadata.sh` on tvos-arm64

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#90460]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=371640

Affected pipelines:
- runtime-extra-platforms

Build error legs:
- `tvos-arm64 Release AllSubsets_NativeAOT_RuntimeTests`

Tests failing: 
- `nativeaot/SmokeTests/StackTraceMetadata/StackTraceMetadata/StackTraceMetadata.sh`

Crash log:

```
Test failed. Trying to see if dump file was created in /cores since 8/11/2023 8:00:09 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/tmp/helix/working/BB1E0A01/p
      > /private/tmp/helix/working/BB1E0A01/w/C1E70A94/e/nativeaot/SmokeTests/StackTraceMetadata/StackTraceMetadata/StackTraceMetadata.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at nativeaot_SmokeTests_StackTraceMetadata._StackTraceMetadata_StackTraceMetadata_._StackTraceMetadata_StackTraceMetadata_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Pull request: https://github.com/dotnet/runtime/pull/90430

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "nativeaot/SmokeTests/StackTraceMetadata/StackTraceMetadata/StackTraceMetadata.sh [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by ivanpovazan** [comment]
The regression was introduced in the following range: https://github.com/dotnet/runtime/compare/2d9acc6f789b7ed098c251151c609eb68f21f68c..bb9ba7abb3bed64ecebcd6c9d3c00be0d6c3b88d
Will continue bisecting to find the root cause.
