### ISSUE TITLE
Access violation when passing parameter to native -> managed callback on 32-bit

### ISSUE THREAD

**Issue by Pixelstormer** [dotnet/runtime#90462]
### Description

I'm following the .NET documentation for [invoking managed code from unmanaged code](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke#invoking-managed-code-from-unmanaged-code) in order to call C# code from Rust. This is working perfectly fine in most cases, but under specific conditions is producing an access violation.

### Reproduction Steps

The access violation occurs specificially when the unmanaged code passes an argument to the managed callback, and only when the code is compiled against a 32-bit target. It does not occur when compiled against a 64-bit target, nor when the managed callback does not have any arguments.
<details><summary>Crashing example</summary>

```csharp
// Compiled against a 32-bit target, e.g. win-x86
using System.Runtime.InteropServices;

namespace crash_repro
{
    public static partial class Program
    {
        public delegate void ManagedCallbackDelegate(int value);

        // The issue occurs regardless of whether you use LibraryImport, DllImport, or anything else, such as MonoMod's DynDllImport
        [LibraryImport("crash_repro_native")]
        public static partial void do_callback(ManagedCallbackDelegate callbackDelegate);

        public static void Main()
        {
            do_callback((int value) => Console.WriteLine($"Native to Managed callback gave value: {value}"));
        }
    }
}

```
```rust
// Compiled against a 32-bit target, e.g. i686-pc-windows-msvc
#[no_mangle]
pub extern "C" fn do_callback(managed_callback: extern "C" fn(i32)) {
    managed_callback(8);
}
```
</details>

### Expected behavior

I would expect the code to run just fine, without crashing:
```
Native to Managed callback gave value: 8
```

### Actual behavior

The above code gives the following output when ran:
<details><summary>Very long console output</summary>

```
Native to Managed callback gave value: 8
Native to Managed callback gave value: 28375412
Fatal error. 0xC0000005
   at crash_repro.Program.<do_callback>g____PInvoke|1_0(IntPtr)
   at crash_repro.Program.do_callback(ManagedCallbackDelegate)
   at crash_repro.Program.Main()
wine: Call from 7BC2F970 to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at crash_repro.Program.<do_callback>g____PInvoke|1_0(IntPtr callbackDelegate)
   at crash_repro.Program.do_callback(ManagedCallbackDelegate callbackDelegate) in /home/ts/dev/rust/bevyengine/crash-repro/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs:line 14
   at crash_repro.Program.Main() in /home/ts/dev/rust/bevyengine/crash-repro/Program.cs:line 17
wine: Unimplemented function KERNEL32.dll.RaiseFailFastException called at address 7BC2F970 (thread 010c), starting debugger...
Unhandled exception: unimplemented function KERNEL32.dll.RaiseFailFastException called in 32-bit code (0x7bc2f970).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7bc2f970 ESP:0069db14 EBP:0069db78 EFLAGS:00000202(   - --  I   - - - )
 EAX:01b6feb2 EBX:0069db20 ECX:01996d8c EDX:01b70a62
 ESI:00a70030 EDI:00000000
Stack dump:
0x0069db14:  00000001 0069db7c 0069db38 80000100
0x0069db24:  00000001 00000000 7bc2f970 00000002
0x0069db34:  01b70a62 01b6feb2 7b072c6b 0000009c
0x0069db44:  0069db60 0069db90 01839afd 0069db68
0x0069db54:  00000001 0069db90 01839afd 007d6d90
0x0069db64:  00000000 01a7d55a 13f4f5e8 0069db8c
Backtrace:
=>0 0x7bc2f970 A_SHAFinal+0xff60() in ntdll (0x0069db78)
  1 0x01bd000f (0x0069dbe4)
  2 0x019d20e6 EntryPoint+0x119186() in coreclr (0x0069e7e0)
  3 0x019d1581 EntryPoint+0x118621() in coreclr (0x0069eb48)
  4 0x0195f7f0 EntryPoint+0xa6890() in coreclr (0x0069ecd8)
  5 0x7bc584e9 A_SHAFinal+0x38ad9() in ntdll (0x0069ed08)
  6 0x7bc584bb A_SHAFinal+0x38aab() in ntdll (0x0069ed28)
  7 0x7bc58f03 A_SHAFinal+0x394f3() in ntdll (0x0069eda8)
  8 0x7bc5834d A_SHAFinal+0x3893d() in ntdll (0x06e20c6b)
  9 0x0069f0a8 (0x06e20c6b)
0x7bc2f970 ntdll+0x2f970: subl	$4,%esp
Modules:
Module	Address			Debug info	Name (58 modules)
PE	00140000-0019b000	Deferred        combase
PE	001a0000-001a8000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	00400000-00420000	Deferred        crash_repro_managed
PE	01340000-01392000	Deferred        hostpolicy
PE	017a0000-01bc8000	Export          coreclr
PE	01be0000-01be8000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	06340000-06db9000	Deferred        system.private.corelib
PE	06e80000-06fc4000	Deferred        clrjit
PE	076c0000-076c8000	Deferred        crash_repro_managed
PE	07d80000-07d8e000	Deferred        system.runtime
PE	07ec0000-07ecc000	Deferred        system.runtime.interopservices
PE	07ed0000-08373000	Deferred        crash_repro_native
PE	08380000-0838d000	Deferred        userenv
PE	083b0000-083d6000	Deferred        system.console
PE	083e0000-083f2000	Deferred        system.threading
PE	08400000-08408000	Deferred        system.text.encoding.extensions
PE	08450000-08459000	Deferred        system.diagnostics.stacktrace
PE	084d0000-085d7000	Deferred        system.reflection.metadata
PE	085f0000-08684000	Deferred        system.collections.immutable
PE	10000000-1004e000	Deferred        hostfxr
PE	61740000-61783000	Deferred        advapi32
PE	61f00000-61f09000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	61f80000-61f8b000	Deferred        api-ms-win-crt-math-l1-1-0
PE	62d40000-62d47000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	62fc0000-6304d000	Deferred        rpcrt4
PE	63480000-6348c000	Deferred        version
PE	63740000-63749000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	63bc0000-63bda000	Deferred        shcore
PE	64a40000-64a94000	Deferred        shlwapi
PE	64ec0000-64fee000	Deferred        oleaut32
PE	65d40000-65d48000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	66240000-66257000	Deferred        bcrypt
PE	66600000-66607000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	66b00000-66b3e000	Deferred        win32u
PE	67c40000-67c7e000	Deferred        mscoree
PE	67ec0000-6881f000	Deferred        shell32
PE	68e00000-68e11000	Deferred        aclui
PE	6a280000-6a32c000	Deferred        msvcrt
PE	6a400000-6a534000	Deferred        ole32
PE	6ac80000-6ac87000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6b780000-6b788000	Deferred        api-ms-win-core-winrt-l1-1-0
PE	6b7c0000-6b7c9000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	6bc00000-6bc2c000	Deferred        sechost
PE	6bcc0000-6bd41000	Deferred        setupapi
PE	6c9c0000-6ca46000	Deferred        gdi32
PE	6cc40000-6cd9c000	Deferred        comctl32
PE	6cf40000-6cf47000	Deferred        api-ms-win-crt-time-l1-1-0
PE	6d780000-6d7a8000	Deferred        ws2_32
PE	6de80000-6de88000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6ed00000-6ef40000	Deferred        user32
PE	6fa80000-6fafa000	Deferred        dbghelp
PE	6ff00000-6ff09000	Deferred        api-ms-win-crt-string-l1-1-0
PE	70b40000-70c18000	Deferred        ucrtbase
PE	71200000-7121c000	Deferred        imm32
PE	7b000000-7b0ec000	Deferred        kernelbase
PE	7b600000-7b81e000	Deferred        kernel32
PE	7bc00000-7bcab000	Dwarf           ntdll
PE	7e4d0000-7e4d4000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000020 start.exe
	["C:\windows\syswow64\start.exe" /exec /home/ts/dev/rust/bevyengine/crash-repro/bin/Debug/net7.0/win-x86/crash_repro_managed.exe]
	00000024    0
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	00000050    0
	0000005c    0
	00000070    0
	0000007c    0
	000000a8    0
	000000ac    0
	000000c4    0
	000000e4    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	00000060    0
	00000064    0
	000000d0    0
00000068 winedevice.exe
	0000006c    0
	00000074    0
	00000078    0
	00000088    0
	0000008c    0
	00000090    0
00000080 explorer.exe
	00000084    0
	0000009c    0
	000000a0    0
00000094 plugplay.exe
	00000098    0
	000000b0    0
	000000b4    0
	000000b8    0
000000bc svchost.exe
	000000c0    0
	000000c8    0
	000000cc    0
000000d4 tabtip.exe
	000000d8    0
	00000100    0
	00000104    0
000000dc rpcss.exe
	000000e0    0
	000000e8    0
	000000ec    0
	000000f0    0
	000000f4    0
	000000f8    0
	000000fc    0
00000108 (D) Z:\home\ts\dev\rust\bevyengine\crash-repro\bin\Debug\net7.0\win-x86\crash_repro_managed.exe
	["Z:\home\ts\dev\rust\bevyengine\crash-repro\bin\Debug\net7.0\win-x86\crash_repro_managed.exe" ]
	0000010c    0 <==
	00000110    0
	00000114    0
	00000118    2
	0000011c    0
	0000012c    0
System information:
    Wine build: wine-7.2-1-g1f8837bdccd (Staging)
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 6.2.6-76060206-generic
Monitored process exited.
Initial process has exited (return code: 256)
Exit with return code 256
```
</details>

Yes, I am running it through Wine, but I have confimed that the issue also occurs on a real Windows installation, so it is not a Wine issue. I cannot test it natively on Linux, as .NET itself [does not yet support 32-bit linux](https://github.com/dotnet/runtime/issues/7335), and the issue does not occur at all when compiling against 64-bit targets.

### Regression?

I've tried compiling the C# side of the code against `net7.0`, `netstandard2.0`, `netcoreapp2.0`, `netcoreapp3.1` and `net48`, and the issue occurred in the same way on all of them.

### Known Workarounds

You would work around the issue by compiling against a 64-bit target, or by only using managed callbacks that don't have any arguments.

### Configuration

<details><summary>Output of `dotnet --info`</summary>

```
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     pop
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>
<details><summary>Output of `rustc --version --verbose`</summary>

```
rustc 1.71.1 (eb26296b5 2023-08-03)
binary: rustc
commit-hash: eb26296b556cef10fb713a38f3d16b9886080f26
commit-date: 2023-08-03
host: x86_64-unknown-linux-gnu
release: 1.71.1
LLVM version: 16.0.5
```
</details>

**Comment by jkotas** [comment]
The default calling convention for Rust on Windows x86 32-bit is cdecl: https://doc.rust-lang.org/reference/items/external-blocks.html#abi
The default calling convention for .NET on Windows x86 32-bit is stdcall: https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.callingconvention

The calling convention mismatches often lead to crashes like the one you have encountered on Windows x86. You should be fix the mismatch and the crash by explicitly specifying cdecl calling convention in C# like this: 

```
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace crash_repro
{
    public static partial class Program
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void ManagedCallbackDelegate(int value);

        [LibraryImport("crash_repro_native")]
        [UnmanagedCallConv(CallConvs = new Type[] { typeof(CallConvCdecl) })]
        public static partial void do_callback(ManagedCallbackDelegate callbackDelegate);

        public static void Main()
        {
            do_callback((int value) => Console.WriteLine($"Native to Managed callback gave value: {value}"));
        }
    }
}
```

**Comment by Pixelstormer** [comment]
After reading the documentation on the `Unmanaged` attributes, I now understand the situation with calling conventions, and explicitly specifying `cdecl` as suggested works perfectly to fix the crash. It's just unfortunate that the documentation I was originally referencing makes absolutely no mention of calling conventions or these attributes, when they're clearly important for addressing issues like these.

**Comment by danmoseley** [comment]
@Pixelstormer The docs accept PRs if you have a clarification you wish to offer. Just click the edit button on the doc.

**Comment by jkotas** [comment]
Submitted doc updates in https://github.com/dotnet/docs/pull/36768 . Please take a look.
