### ISSUE TITLE
[mono] Tests failing `System.Globalization.Calendars.IOS.Tests` on ios-like platforms

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#90497]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=371961

Affected pipelines:
- runtime-extra-platforms

Build error legs:
- net8.0-maccatalyst-Release-arm64-Mono_Release-OSX.1200.Arm64.Open
- net8.0-maccatalyst-Release-x64-Mono_Release-OSX.1200.Amd64.Open
- net8.0-tvos-Release-arm64-Mono_Release-OSX.13.Amd64.AppleTV.Open
- net8.0-iossimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open
- net8.0-tvossimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open

Work items failing: 
- System.Globalization.Calendars.IOS.Tests

Crash log example:
```
[FAIL] System.Globalization.Tests.JapaneseCalendarTests.GetEra_Invalid_ThrowsArgumentOutOfRangeException   Test name: System.Globalization.Tests.JapaneseCalendarTests.GetEra_Invalid_ThrowsArgumentOutOfRangeException
2023-08-11 15:51:13.586 Df System.Globalization.Calendars.IOS.Tests[89155:3cbb9a]    Assembly:  [System.Globalization.Calendars.IOS.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
   Exception messages: Assert.All() Failure: 1 out of 1 items in the collection did not pass.
[0]: Item: 9/7/68 12:00:00 AM
2023-08-11 15:51:13.586 Df System.Globalization.Calendars.IOS.Tests[89155:3cbb9a]      Xunit.Sdk.ThrowsException: Assert.Throws() Failure
     Expected: typeof(System.ArgumentOutOfRangeException)
     Actual:   (No exception was thrown)
        at Xunit.Assert.Throws(Type exceptionType, Exception exception) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 226
2023-08-11 15:51:13.586 Df System.Globalization.Calendars.IOS.Tests[89155:3cbb9a]         at Xunit.Assert.Throws[ArgumentOutOfRangeException](Func`1 testCode) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 48
2023-08-11 15:51:13.586 Df System.Globalization.Calendars.IOS.Tests[89155:3cbb9a]         at System.Globalization.Tests.CalendarTestBase.<>c__DisplayClass48_0.<GetEra_Invalid_ThrowsArgumentOutOfRangeException>b__0(DateTime dt)
2023-08-11 15:51:13.586 Df System.Globalization.Calendars.IOS.Tests[89155:3cbb9a]         at Xunit.Assert.<>c__DisplayClass11_0`1[[System.DateTime, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<All>b__0(DateTime item, Int32 index) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 34
2023-08-11 15:51:13.586 Df System.Globalization.Calendars.IOS.Tests[89155:3cbb9a]         at Xunit.Assert.All[DateTime](IEnumerable`1 collection, Action`2 action) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 61   Exception stack traces:    at System.Globalization.Tests.CalendarTestBase.GetEra_Invalid_ThrowsArgumentOutOfRangeException()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Pull request: https://github.com/dotnet/runtime/pull/90023

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "[FAIL] System.Globalization.Tests.JapaneseCalendarTests.GetEra_Invalid_ThrowsArgumentOutOfRangeException",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961
**Error message validated:** `[FAIL] System.Globalization.Tests.JapaneseCalendarTests.GetEra_Invalid_ThrowsArgumentOutOfRangeException`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/13/2023 7:37:32 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[372849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849&view=ms.vss-test-web.build-test-results-tab&runId=7921678&resultId=195420)|dotnet/runtime#90519|
|[372550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550&view=ms.vss-test-web.build-test-results-tab&runId=7913880&resultId=195420)||
|[372445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445&view=ms.vss-test-web.build-test-results-tab&runId=7909874&resultId=195432)|dotnet/runtime#90270|
|[372307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307&view=ms.vss-test-web.build-test-results-tab&runId=7904390&resultId=195420)||
|[372186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186&view=ms.vss-test-web.build-test-results-tab&runId=7900394&resultId=195420)||
|[372071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372071)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372071&view=ms.vss-test-web.build-test-results-tab&runId=7896762&resultId=195420)||
|[371961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961)|dotnet/runtime|[System.Globalization.Calendars.IOS.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961&view=ms.vss-test-web.build-test-results-tab&runId=7893450&resultId=195420)|dotnet/runtime#90023|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|7|7|

**Comment by mdh1418** [comment]
I believe this should be fixed by https://github.com/dotnet/runtime/pull/90515
Looking at the tvos lane https://[helix.dot.net/api/jobs/3c99382b-fad6-45d8-994b-f42abe817a4a/workitems/System.Globalization.Calendars.Tests?api-version=2019-06-17](https://helix.dot.net/api/jobs/3c99382b-fad6-45d8-994b-f42abe817a4a/workitems/System.Globalization.Calendars.Tests?api-version=2019-06-17) the `GetEra_Invalid_ThrowsArgumentOutOfRangeException` is passing
