### ISSUE TITLE
Unhandled IOException failing superpmi-collect runtime tests on OS X arm64 Checked

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#90530]
[Full log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2242382/logs/2229)

Exception trace:
```
=====================
8/13/2023 7:14:06 PM
System.IO.IOException: No buffer space available
 ---> System.Net.Sockets.SocketException (55): No buffer space available
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

This failure is from [yesterday's weekly run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2242382&view=results) of runtime-coreclr superpmi-replay.

**Comment by amanasifkhalid** [comment]
@jakobbotsch could you PTAL? Thank you!

**Comment by amanasifkhalid** [comment]
This hasn't repro'd recently in [runtime-coreclr superpmi-collect](https://dev.azure.com/dnceng/internal/_build?definitionId=977&_a=summary).
