### ISSUE TITLE
Test failure JIT/superpmi/superpmicollect/superpmicollect.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#90723]
**Failed in:** [runtime-coreclr outerloop 20230816.9](https://dev.azure.com/dnceng-public/public/_build/results?buildId=376942&view=ms.vss-test-web.build-test-results-tab&runId=8020774&resultId=108465&paneView=debug)

**Failed tests:**
```
coreclr linux x64 Checked @ (Alpine.315.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-amd64
    - JIT/superpmi/superpmicollect/superpmicollect.sh
coreclr windows x86 Checked @ Windows.10.Amd64.Open
    - JIT\\superpmi\\superpmicollect\\superpmicollect.cmd
```

**Error message:**
```
ERROR: Test /root/helix/work/workitem/e/JIT/superpmi/superpmicollect/CscBench/CscBench.sh failed

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.superpmi/superpmicollect/superpmicollect.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true superpmicollect.dll ''
SuperPMI collection and playback - BEGIN
Setting environment variables:
    SuperPMIShimLogPath=/tmp/kg5zk5ry.er3SPMI
    SuperPMIShimPath=/root/helix/work/correlation/libclrjit.so
    DOTNET_JitName=libsuperpmi-shim-collector.so
Running: /bin/chmod +x "/root/helix/work/workitem/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh"
Running: /usr/bin/env bash /root/helix/work/workitem/e/JIT/superpmi/superpmicollect/Bytemark/Bytemark.sh
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true Bytemark.dll ''
BBBBBB   YYY   Y  TTTTTTT  EEEEEEE
BBB   B  YYY   Y    TTT    EEE
BBB   B  YYY   Y    TTT    EEE
BBBBBB    YYY Y     TTT    EEEEEEE
BBB   B    YYY      TTT    EEE
BBB   B    YYY      TTT    EEE
BBBBBB     YYY      TTT    EEEEEEE

BYTEmark (tm) C# Mode Benchmark ver. 2 (06/99)
NUMERIC SORT(jagged):  Iterations/sec: 1022.95788  Index: 26.23440
NUMERIC SORT(rectangle):  Iterations/sec: 558.79395  Index: 14.33062
STRING SORT:  Iterations/sec: 447.80811  Index: 200.09299
BITFIELD:  Iterations/sec: 320248479.94821  Index: 54.93392
FP EMULATION(struct):  Iterations/sec: 134.92740  Index: 64.74444
FP EMULATION(class):  Iterations/sec: 120.87510  Index: 58.00149
FOURIER:  Iterations/sec: 76728.85423  Index: 87.26348
ASSIGNMENT(jagged):  Iterations/sec: 19.93684  Index: 75.86315
ASSIGNMENT(rectangle):  Iterations/sec: 16.44562  Index: 62.57846
IDEA:  Iterations/sec: 4958.30584  Index: 75.83595
HUFFMAN:  Iterations/sec: 2062.23103  Index: 57.18571
NEURAL NET(jagged):  Iterations/sec: 23.00149  Index: 36.95018
NEURAL NET(rectangle):  Iterations/sec: 9.64381  Index: 15.49207
LU DECOMPOSITION:  Iterations/sec: 2055.70593  Index: 106.49616
===========OVERALL============
INTEGER INDEX: 56.29202
FLOATING-POINT INDEX: 48.02563
 (90 MHz Dell Pentium = 1.00)
==============================
Expected: 100
Actual: 100
END EXECUTION - PASSED
Running: /bin/chmod +x "/root/helix/work/workitem/e/JIT/superpmi/superpmicollect/CscBench/CscBench.sh"
Running: /usr/bin/env bash /root/helix/work/workitem/e/JIT/superpmi/superpmicollect/CscBench/CscBench.sh
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true CscBench.dll ''
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Microsoft.CodeAnalysis.Emit.EmitOptions.ValidateOptions(DiagnosticBag diagnostics, CommonMessageProvider messageProvider, Boolean isDeterministic)
   at Microsoft.CodeAnalysis.Compilation.CheckOptionsAndCreateModuleBuilder(DiagnosticBag diagnostics, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, RebuildData rebuildData, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, Em
```

**Stack trace:**
```
   at JIT_superpmi._superpmicollect_superpmicollect_._superpmicollect_superpmicollect_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
<html>
<body>
<div><br/><br/>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-08-16T11:01:49.338Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"System.PhaseName":"run_test_p1__osx_x64_checked","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Project":"public","System.JobName":"__default","BuildNumber":"20230816.1","Reason":"Schedule","DefinitionName":"runtime-coreclr outerloop","configuration":"Checked","AzurePipelinesTestRunId":"7993004","System.PhaseAttempt":"1","architecture":"x64","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","BuildId":"375642","operatingSystem":"OSX.1200.Amd64.Open","System.JobAttempt":"1","System.StageAttempt":"1"} | Schedule
2023-08-16T11:01:49.338Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"System.PhaseName":"run_test_p1__osx_x64_checked","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Project":"public","System.JobName":"__default","BuildNumber":"20230816.1","Reason":"Schedule","DefinitionName":"runtime-coreclr outerloop","configuration":"Checked","AzurePipelinesTestRunId":"7993004","System.PhaseAttempt":"1","architecture":"x64","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","BuildId":"375642","operatingSystem":"OSX.1200.Amd64.Open","System.JobAttempt":"1","System.StageAttempt":"1"} | Schedule
2023-08-16T11:01:49.338Z | runtime-coreclr outerloop | Checked | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"System.PhaseName":"run_test_p1__osx_x64_checked","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Project":"public","System.JobName":"__default","BuildNumber":"20230816.1","Reason":"Schedule","DefinitionName":"runtime-coreclr outerloop","configuration":"Checked","AzurePipelinesTestRunId":"7993004","System.PhaseAttempt":"1","architecture":"x64","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","BuildId":"375642","operatingSystem":"OSX.1200.Amd64.Open","System.JobAttempt":"1","System.StageAttempt":"1"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-08-05T06:00:45.852Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildNumber":"20230804.1","System.JobAttempt":"1","AzurePipelinesTestRunId":"7703738","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","Project":"public","BuildId":"364376","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseAttempt":"1","System.StageName":"Build","configuration":"Checked-jitstress1_tiered","operatingSystem":"OSX.1200.Amd64.Open","DefinitionName":"runtime-coreclr jitstress"} | Schedule
2023-04-26T06:10:17.798Z | runtime-coreclr jitstress | Checked-jitstress2 | osx.1200.amd64.open | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"BuildId":"252731","Reason":"Schedule","System.PhaseName":"run_test_p1__osx_x64_checked","System.PhaseAttempt":"1","DefinitionName":"runtime-coreclr jitstress","AzurePipelinesTestRunId":"4906790","Project":"public","operatingSystem":"OSX.1200.Amd64.Open","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-jitstress2","DefinitionId":"109","System.StageName":"Build","BuildNumber":"20230425.5","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","architecture":"x64","System.JobName":"__default","System.JobAttempt":"1"} | Schedule
2023-04-26T05:27:22.852Z | runtime-coreclr jitstress | Checked-jitstress2 | ubuntu.1804.armarch.open | arm64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"System.StageName":"Build","System.JobName":"__default","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","configuration":"Checked-jitstress2","System.StageAttempt":"1","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","Project":"public","BuildId":"252731","DefinitionName":"runtime-coreclr jitstress","architecture":"arm64","DefinitionId":"109","Reason":"Schedule","AzurePipelinesTestRunId":"4906414","System.PhaseName":"run_test_p1__linux_arm64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","BuildNumber":"20230425.5","System.PhaseAttempt":"1"} | Schedule
2023-04-26T05:25:23.22Z | runtime-coreclr jitstress | Checked-jitstress2 | ubuntu.1804.armarch.open | arm | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1__linux_arm_checked","operatingSystem":"(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7","System.StageName":"Build","System.JobId":"860c965f-b28e-50d5-65d2-e40bd59f3a69","BuildNumber":"20230425.5","System.JobName":"__default","Reason":"Schedule","System.PhaseAttempt":"1","architecture":"arm","configuration":"Checked-jitstress2","Project":"public","DefinitionName":"runtime-coreclr jitstress","BuildId":"252731","DefinitionId":"109","AzurePipelinesTestRunId":"4906372","System.JobAttempt":"1","System.StageAttempt":"1"} | Schedule
2023-04-26T05:25:21.005Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | ubuntu.1804.armarch.open | arm | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","configuration":"Checked-jitstress2_tiered","DefinitionId":"109","BuildNumber":"20230425.5","System.PhaseAttempt":"1","BuildId":"252731","operatingSystem":"(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7","Project":"public","AzurePipelinesTestRunId":"4906374","DefinitionName":"runtime-coreclr jitstress","System.JobAttempt":"1","System.JobName":"__default","System.PhaseName":"run_test_p1__linux_arm_checked","System.JobId":"860c965f-b28e-50d5-65d2-e40bd59f3a69","architecture":"arm","Reason":"Schedule","System.StageName":"Build"} | Schedule
2023-04-26T05:25:12.735Z | runtime-coreclr jitstress | Checked-jitstress2 | ubuntu.1804.amd64.open.rt | x64 | JIT/superpmi/superpmicollect/superpmicollect.sh | Failed | {"System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"252731","System.JobAttempt":"1","Project":"public","DefinitionId":"109","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","configuration":"Checked-jitstress2","System.JobName":"__default","Reason":"Schedule","DefinitionName":"runtime-coreclr jitstress","System.StageName":"Build","BuildNumber":"20230425.5","architecture":"x64","AzurePipelinesTestRunId":"4906396","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__linux_x64_checked"} | Schedule
</details>

**Comment by BruceForstall** [comment]
Possible dup of https://github.com/dotnet/runtime/issues/90711
