### ISSUE TITLE
[wasi] Can't import native functions with 64bit parameters when using mono_add_internal_call

### ISSUE THREAD

**Issue by mhmd-azeez** [dotnet/runtime#90786]
### Description

When trying to import C functions, it seems like there is a certain threshold that causes problems when it's hit. The size depends both on parameter types and return type. For example, this works:

```
IMPORT("env", "do_something") extern int64_t do_something(int32_t);
```

Output:
```
Mo in D:\dylibso\Int64Repro\host on main ● ~4 λ dotnet run
Input: 5
```

But this doesn't work (notice the parameter is also 64 bit now):
```
IMPORT("env", "do_something") extern int64_t do_something(int64_t);
```

Output:
```
Mo in D:\dylibso\Int64Repro\host on main ● ~3 λ dotnet run
../plugin/bin/Debug/net7.0/Int64Repro.wasm
Unhandled exception. Extism.Sdk.Native.ExtismException: error while executing at wasm backtrace:
    0: 0x405605 - <unknown>!<wasm function 7673>
    1: 0x403143 - <unknown>!<wasm function 7586>
    2: 0x405ad0 - <unknown>!<wasm function 7682>
    3: 0xe1c36 - <unknown>!<wasm function 699>
    4: 0x2d0b5a - <unknown>!<wasm function 4847>
    5: 0x3f5839 - <unknown>!<wasm function 7289>
    6: 0x3f56e5 - <unknown>!<wasm function 7287>
    7: 0x3f55ae - <unknown>!<wasm function 7286>
    8: 0x3f58b8 - <unknown>!<wasm function 7290>
    9: 0x3a26ad - <unknown>!<wasm function 6652>
   10: 0xbc1fa - <unknown>!<wasm function 397>
   11: 0x660dd - <unknown>!<wasm function 323>
   12: 0x61af2 - <unknown>!<wasm function 322>
   13: 0x365523 - <unknown>!<wasm function 6277>
   14: 0x20f187 - <unknown>!<wasm function 3058>
   15: 0x210e70 - <unknown>!<wasm function 3074>
   16: 0x21a4d8 - <unknown>!<wasm function 3160>
   17: 0xe1e05 - <unknown>!<wasm function 701>
   18: 0xe202a - <unknown>!<wasm function 702>
   19: 0x3408 - <unknown>!<wasm function 39>
   20: 0x32e7 - <unknown>!<wasm function 36>
   21: 0x417269 - <unknown>!<wasm function 7885>

Caused by:
    Exited with i32 exit status 1
   at Extism.Sdk.Native.Plugin.CallFunction(String functionName, ReadOnlySpan`1 data)
   at Program.<Main>$(String[] args) in D:\dylibso\Int64Repro\host\Program.cs:line 35
```

This doesn't work, but it's even more starnge:
```
IMPORT("env", "do_something") extern int32_t do_something(int32_t, int32_t, int32_t, int32_t, int32_t);
```

Output:
```
Mo in D:\dylibso\Int64Repro\host on main ● ~3 λ dotnet run
../plugin/bin/Debug/net7.0/Int64Repro.wasm
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Extism.Sdk.Native.LibExtism.extism_function_new(System.String, Extism.Sdk.Native.ExtismValType*, Int64, Extism.Sdk.Native.ExtismValType*, Int64, InternalExtismFunction, IntPtr, IntPtr)
--------------------------------
   at Extism.Sdk.HostFunction..ctor(System.String, System.String, System.Span`1<Extism.Sdk.Native.ExtismValType>, System.Span`1<Extism.Sdk.Native.ExtismValType>, IntPtr, Extism.Sdk.ExtismFunction)
   at Program.<Main>$(System.String[])
```

### Reproduction Steps

https://github.com/mhmd-azeez/Int64Repro

### Expected behavior

You should be able to have function imports with any number of 64 bit parameters

### Actual behavior

You can't have function imports that have one or more 64 bit parameters

### Known Workarounds

None

### Configuration

wasm/wasi

**Comment by mhmd-azeez** [comment]
To clarify, the problem doesn't actually happen at the native function. The native function _can_ have 64 bit params, but the corresponding C# function blows up

**Comment by radical** [comment]
cc @maraf

**Comment by lewing** [comment]
cc @vargaz

**Comment by vargaz** [comment]
Can't reproduce this with the testcase, when running dotnet run in ```plugin```, i get:

Error: failed to run main module `bin/Debug/net7.0/Int64Repro.wasm`

Caused by:
    0: failed to instantiate "bin/Debug/net7.0/Int64Repro.wasm"
    1: unknown import: `env::do_something` has not been defined

I think the problem is caused by the interpreter not knowing about this particular icall signature. We have a build task called InterpToNativeGenerator which generates a function used by the interpreter to call icalls, but that task only works on the icall table inside the runtime, it doesn't know about extra icalls registered from native code. To solve this, we would need to scan assemblies for extra internal calls.

**Comment by mhmd-azeez** [comment]
@vargaz what are you using to run the plugin? Are you using one of the hosts provided? Because the host has to provide the appropriate `env::do_something` function on its side. However, to be clear, this is not an import problem. This happens even if the function is a normal native function (without import).

I have pushed a change to use a normal function:
```
// this doens't work
int64_t do_something(int64_t v) {
    return v * 2;
}

void repro_attach_internal_calls()
{
    mono_add_internal_call("Program::do_something", do_something);
}
```

When using the .NET host, it should give you this output:
```
Mo in D:\dylibso\Int64Repro\host on main λ dotnet run
Unhandled exception. Extism.Sdk.Native.ExtismException: error while executing at wasm backtrace:
    0: 0x405629 - <unknown>!<wasm function 7673>
    1: 0x403167 - <unknown>!<wasm function 7586>
    2: 0x405af4 - <unknown>!<wasm function 7682>
    3: 0xe1c5a - <unknown>!<wasm function 699>
    4: 0x2d0b7e - <unknown>!<wasm function 4847>
    5: 0x3f585d - <unknown>!<wasm function 7289>
    6: 0x3f5709 - <unknown>!<wasm function 7287>
    7: 0x3f55d2 - <unknown>!<wasm function 7286>
    8: 0x3f58dc - <unknown>!<wasm function 7290>
    9: 0x3a26d1 - <unknown>!<wasm function 6652>
   10: 0xbc21e - <unknown>!<wasm function 397>
   11: 0x66101 - <unknown>!<wasm function 323>
   12: 0x61b16 - <unknown>!<wasm function 322>
   13: 0x365547 - <unknown>!<wasm function 6277>
   14: 0x20f1ab - <unknown>!<wasm function 3058>
   15: 0x210e94 - <unknown>!<wasm function 3074>
   16: 0x21a4fc - <unknown>!<wasm function 3160>
   17: 0xe1e29 - <unknown>!<wasm function 701>
   18: 0xe204e - <unknown>!<wasm function 702>
   19: 0x342c - <unknown>!<wasm function 39>
   20: 0x32d5 - <unknown>!<wasm function 35>
   21: 0x41728d - <unknown>!<wasm function 7885>

Caused by:
    Exited with i32 exit status 1
   at Extism.Sdk.Native.Plugin.CallFunction(String functionName, ReadOnlySpan`1 data)
   at Program.<Main>$(String[] args) in D:\dylibso\Int64Repro\host\Program.cs:line 34
```

**Comment by vargaz** [comment]
I'd suggest using pinvokes (DllImport) as a workaround, its much better supported than adding internal calls.

**Comment by mhmd-azeez** [comment]
@vargaz I haven't been able to make pinvoke work in wasm either. Are there any samples?

The only thing I was able to achieve was to call a parameterless function:
https://github.com/mhmd-azeez/Int64Repro/commit/e75b0ab21a971c0f3703529016a426afb11fb14e

**Comment by vargaz** [comment]
pinvokes should work out of the box in browser wasm, wasi is _very_ experimental, so things might not work.

Unfortunately, I can't get extism to work so i can't reproduce the problem. I was trying:
```DYLD_LIBRARY_PATH=/Users/vargaz/extism/target/release/deps dotnet run```

and got:
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'extism_context_new' in shared library 'extism'.
   at Extism.Sdk.Native.LibExtism.extism_context_new()
   at Extism.Sdk.Native.Context..ctor()
```

**Comment by mhmd-azeez** [comment]
@vargaz can you try the Go host? it doesn't depend on the shared libraries

**Comment by vargaz** [comment]
I can reproduce with that, will look into it.

**Comment by vargaz** [comment]
So it looks like the icall case fails because the interpreter can't call icalls with those signatures:
```
wasmtime bin/Debug/net7.0/Int64Repro.wasm 
[wasm_trace_logger] CANNOT HANDLE INTERP ICALL SIG LL
```

The pinvoke case seems to fail because wasi doesn't have any pinvoke support right now.
A workaround that _might_ work is to pass these 64 bit values as 2 32 bit values. Or marshal them into a byte array and
pass the address of the byte array as a pointer argument.

**Comment by mhmd-azeez** [comment]
Hmmm, that's not ideal because the host gives the same import functions to all of the plugins (that might be implemented in different languages).

What about creating our own `InterpToNativeGenerator`? Would that allow us to generate the right functions for the interpreter? I want to hide away these limitations from the PDK users

**Comment by vargaz** [comment]
These restrictions will eventually be fixed, but right now the only way to implement this seem to have wasm specific versions, they can be internal, they don't have to be exposed to the user.

**Comment by mhmd-azeez** [comment]
Ah, that'd be great! Can you provide an example of breaking the 64bit int into two 32bit ints without exposing it to the user. Since the user has to create the C# method. I don't want the code, just some high level steps

**Comment by vargaz** [comment]
In a normal api, the icalls are hidden anyway, so they are not public methods. So you would have a public method
like
```
public foo (long arg) {
   foo_icall (arg >> 32, arg & 0xffffffff);
}

[InternalCall]
private void foo_icall (int arg_high, int arg_low);
```
and in C:
```
void foo_icall(int arg_high, int arg_low)
{
   int64_t arg = ((int64_t)arg_high << 32) | arg_low;
...
}
```

**Comment by mhmd-azeez** [comment]
I see, is this possible with MSBuild or is this only for Source Generators. Ideally, I want this to work for both C# and F#

**Comment by vargaz** [comment]
So the main problem was that the test project was using the old wasi-sdk stuff, .net8 has experimental official support described here:
https://twitter.com/stevensanderson/status/1658845798212202496

With net8, pinvokes work for me, with the following csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>wasi-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
	<WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
	<NativeFileReference Include="$(MSBuildThisFileDirectory)native.c" />
        <!-- workaround -->
	<_WasmNativeFileForLinking Include="@(NativeFileReference)" />
  </ItemGroup>

</Project>
```

and c# declaration:
```
	[DllImport("mylib")]
    public static unsafe extern long do_something(long n);
```

**Comment by mhmd-azeez** [comment]
Ah, that makes everything so much simpler! Thank you very much :)

**Comment by mhmd-azeez** [comment]
@vargaz can you please post the whole project? what does `native.c` contain? Because it doesn't seem to import the function for me:

```
using System;
using System.Runtime.InteropServices;

var x = 5;
var z = Native.do_something(x);

Console.WriteLine($"Hello, Wasi Console: {z}");

public class Native
{

    [DllImport("native")]
    public static unsafe extern long do_something(long n);
}

```

```
Mo in D:\dylibso\x\waconsole λ wasm-objdump --details --section=import .\bin\Release\net8.0\wasi-wasm\AppBundle\waconsole.wasm

waconsole.wasm: file format wasm 0x1

Section Details:

Import[37]:
 - func[0] sig=7 <wasi_snapshot_preview1.sock_accept> <- wasi_snapshot_preview1.sock_accept
 - func[1] sig=5 <wasi_snapshot_preview1.args_get> <- wasi_snapshot_preview1.args_get
 - func[2] sig=5 <wasi_snapshot_preview1.args_sizes_get> <- wasi_snapshot_preview1.args_sizes_get
 - func[3] sig=5 <wasi_snapshot_preview1.environ_get> <- wasi_snapshot_preview1.environ_get
 - func[4] sig=5 <wasi_snapshot_preview1.environ_sizes_get> <- wasi_snapshot_preview1.environ_sizes_get
 - func[5] sig=5 <wasi_snapshot_preview1.clock_res_get> <- wasi_snapshot_preview1.clock_res_get
 - func[6] sig=26 <wasi_snapshot_preview1.clock_time_get> <- wasi_snapshot_preview1.clock_time_get
 - func[7] sig=43 <wasi_snapshot_preview1.fd_advise> <- wasi_snapshot_preview1.fd_advise
 - func[8] sig=4 <wasi_snapshot_preview1.fd_close> <- wasi_snapshot_preview1.fd_close
 - func[9] sig=5 <wasi_snapshot_preview1.fd_fdstat_get> <- wasi_snapshot_preview1.fd_fdstat_get
 - func[10] sig=5 <wasi_snapshot_preview1.fd_fdstat_set_flags> <- wasi_snapshot_preview1.fd_fdstat_set_flags
 - func[11] sig=5 <wasi_snapshot_preview1.fd_filestat_get> <- wasi_snapshot_preview1.fd_filestat_get
 - func[12] sig=24 <wasi_snapshot_preview1.fd_filestat_set_size> <- wasi_snapshot_preview1.fd_filestat_set_size       
 - func[13] sig=43 <wasi_snapshot_preview1.fd_filestat_set_times> <- wasi_snapshot_preview1.fd_filestat_set_times     
 - func[14] sig=71 <wasi_snapshot_preview1.fd_pread> <- wasi_snapshot_preview1.fd_pread
 - func[15] sig=5 <wasi_snapshot_preview1.fd_prestat_get> <- wasi_snapshot_preview1.fd_prestat_get
 - func[16] sig=7 <wasi_snapshot_preview1.fd_prestat_dir_name> <- wasi_snapshot_preview1.fd_prestat_dir_name
 - func[17] sig=71 <wasi_snapshot_preview1.fd_pwrite> <- wasi_snapshot_preview1.fd_pwrite
 - func[18] sig=12 <wasi_snapshot_preview1.fd_read> <- wasi_snapshot_preview1.fd_read
 - func[19] sig=71 <wasi_snapshot_preview1.fd_readdir> <- wasi_snapshot_preview1.fd_readdir
 - func[20] sig=61 <wasi_snapshot_preview1.fd_seek> <- wasi_snapshot_preview1.fd_seek
 - func[21] sig=4 <wasi_snapshot_preview1.fd_sync> <- wasi_snapshot_preview1.fd_sync
 - func[22] sig=5 <wasi_snapshot_preview1.fd_tell> <- wasi_snapshot_preview1.fd_tell
 - func[23] sig=12 <wasi_snapshot_preview1.fd_write> <- wasi_snapshot_preview1.fd_write
 - func[24] sig=7 <wasi_snapshot_preview1.path_create_directory> <- wasi_snapshot_preview1.path_create_directory      
 - func[25] sig=11 <wasi_snapshot_preview1.path_filestat_get> <- wasi_snapshot_preview1.path_filestat_get
 - func[26] sig=72 <wasi_snapshot_preview1.path_filestat_set_times> <- wasi_snapshot_preview1.path_filestat_set_times 
 - func[27] sig=14 <wasi_snapshot_preview1.path_link> <- wasi_snapshot_preview1.path_link
 - func[28] sig=73 <wasi_snapshot_preview1.path_open> <- wasi_snapshot_preview1.path_open
 - func[29] sig=10 <wasi_snapshot_preview1.path_readlink> <- wasi_snapshot_preview1.path_readlink
 - func[30] sig=7 <wasi_snapshot_preview1.path_remove_directory> <- wasi_snapshot_preview1.path_remove_directory      
 - func[31] sig=10 <wasi_snapshot_preview1.path_rename> <- wasi_snapshot_preview1.path_rename
 - func[32] sig=11 <wasi_snapshot_preview1.path_symlink> <- wasi_snapshot_preview1.path_symlink
 - func[33] sig=7 <wasi_snapshot_preview1.path_unlink_file> <- wasi_snapshot_preview1.path_unlink_file
 - func[34] sig=12 <wasi_snapshot_preview1.poll_oneoff> <- wasi_snapshot_preview1.poll_oneoff
 - func[35] sig=1 <wasi_snapshot_preview1.proc_exit> <- wasi_snapshot_preview1.proc_exit
 - func[36] sig=5 <wasi_snapshot_preview1.random_get> <- wasi_snapshot_preview1.random_get
```

**Comment by vargaz** [comment]
Its something like:
```
int64_t do_something(int64_t v) {
    return v * 2;
}
```

Make sure the DllImport () name ('native') matches the filename (?) of the NativeFileReference ('native.c'), its somehow used to establish the mapping.  If things work, then ```do_something``` should show up in ```obj/Debug/net8.0/wasi-wasm/wasm/for-build/pinvoke-table.h```.

**Comment by mhmd-azeez** [comment]
@vargaz thank you very much! I was able to make the plugin work and run it with wasmtime directly, for any future people, it's here: https://github.com/mhmd-azeez/Int64Repro/tree/a2c6d66a910d44e872413ef94e404096294aa14e/plugin

The only thing is can't import mono headers anymore. Fortunately I don't need them anymore

**Comment by mhmd-azeez** [comment]
I was able to get the Go host to run the plugin by making sure that args[0] is not null ([this is expectd by mono](https://github.com/mono/mono/blob/a44926a5be1c648deec836e9cdda3c93e25f9a51/mono/metadata/object.c#L4605)). Thank you very much for your help @vargaz 

The only thing left is that I can't use the mono headers anymore from native.c, [I need this to export my own `_initialize` function](https://github.com/extism/csharp-pdk/blob/3f47afb67a44a0d8d70cd83cd3891877fdea9239/src/Extism.Pdk/native/extism_ffi.c#L179):

```
#include <mono-wasi/driver.h>
```

```
Mo in D:\dylibso\Int64Repro\plugin on main ● ~1 λ dotnet build
MSBuild version 17.8.0-preview-23367-03+0ff2a83e9 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSD
K1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\dylibso\Int64Repro\plugin\Int64Repro.csproj]
  Int64Repro -> D:\dylibso\Int64Repro\plugin\bin\Debug\net8.0\wasi-wasm\Int64Repro.dll
  MicrosoftNetCoreAppRuntimePackRidNativeDir: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.wasi-wasm\8.0.0-preview.7.23375.6\runtimes\w
  asi-wasm\native\
  Performing WASI SDK build: "D:\tools\wasi-sdk\bin\clang.exe" "@D:\dylibso\Int64Repro\plugin\obj\Debug\net8.0\wasi-wasm\wasm\for-build\clang-compile.rsp"
D:/dylibso/Int64Repro/plugin/native.c(1,9): warning GDEFCC9BD: #pragma once in main file [-Wpragma-once-outside-header] [D:\dylibso\Int64Repro\plugin\Int64
Repro.csproj]
  #pragma once
          ^
  D:/dylibso/Int64Repro/plugin/native.c:6:10: fatal error: 'mono-wasi/driver.h' file not found
  #include <mono-wasi/driver.h>
           ^~~~~~~~~~~~~~~~~~~~
  1 warning and 1 error generated.
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Wasi.Sdk\8.0.0-preview.7.23375.6\Sdk\WasiApp.Native.targets(470,5): error MSB3073: The comm
and ""D:\tools\wasi-sdk\bin\clang.exe" "@D:\dylibso\Int64Repro\plugin\obj\Debug\net8.0\wasi-wasm\wasm\for-build\clang-compile.rsp"" exited with code 1. [D:
\dylibso\Int64Repro\plugin\Int64Repro.csproj]

Build FAILED.

D:/dylibso/Int64Repro/plugin/native.c(1,9): warning GDEFCC9BD: #pragma once in main file [-Wpragma-once-outside-header] [D:\dylibso\Int64Repro\plugin\Int64
Repro.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Wasi.Sdk\8.0.0-preview.7.23375.6\Sdk\WasiApp.Native.targets(470,5): error MSB3073: The comm
and ""D:\tools\wasi-sdk\bin\clang.exe" "@D:\dylibso\Int64Repro\plugin\obj\Debug\net8.0\wasi-wasm\wasm\for-build\clang-compile.rsp"" exited with code 1. [D:
\dylibso\Int64Repro\plugin\Int64Repro.csproj]
    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:16.64
```

This used to work with the old Wasi SDK

**Comment by vargaz** [comment]
Could you open another issue for that problem ?

**Comment by mhmd-azeez** [comment]
Sure thing
