### ISSUE TITLE
ObjectDisposedException intermittently crashes test process from DefaultHttpClientFactory.ExpiryTimer_Tick

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#90919]
### Description

The fix for #90386 does not appear to have resolved the issue but just changed the failure mode: https://github.com/dotnet/runtime/issues/90386#issuecomment-1686180896

/cc @CarnaViire

### Reproduction Steps

Clone https://github.com/martincostello/dependabot-helper/commit/c8cbfc6be40fbf62b5c30a20c150e9f84870d981 and run build.ps1 in the root of the repository.

### Expected behavior

The tests pass.

### Actual behavior

The test process crashes with an exception such as:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<.ctor>b__14_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.ExpiryTimer_Tick(Object state)
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<.ctor>b__14_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.ExpiryTimer_Tick(Object state)
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<.ctor>b__14_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.ExpiryTimer_Tick(Object state)
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<.ctor>b__14_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.ExpiryTimer_Tick(Object state)
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Regression?

Yes.

### Known Workarounds

None.

### Configuration

.NET SDK `8.0.100-rc.2.23420.6` which contains .NET Runtime `8.0.0-rc.1.23414.4` @ e89794659669cb7bb967db73a7ea6889c3891727.

**Comment by CarnaViire** [comment]
> .NET SDK 8.0.100-rc.2.23420.6 which contains .NET Runtime 8.0.0-rc.1.23414.4 @ https://github.com/dotnet/runtime/commit/e89794659669cb7bb967db73a7ea6889c3891727.

This build doesn't include my change yet 😅 you can check it here: https://github.com/dotnet/runtime/commits/2470610ea493b650177a5303684f87ee9fcec966

My commit was merged 11:44 PM GMT+1, and the one you are pointed at is from 5:34 PM GMT+1 😅

Can you please update to the latest daily build and try again?

**Comment by martincostello** [comment]
My bad, sorry about that 😅

I looked at the tree for e89794659669cb7bb967db73a7ea6889c3891727 and saw your name on the latest commit to [HttpClientFactory](https://github.com/dotnet/runtime/tree/e89794659669cb7bb967db73a7ea6889c3891727/src/libraries/Microsoft.Extensions.Http/src), but I didn't pay enough attention to the commit message to see that it was the initial change that introduced the issue, rather than being the fix:

![image](https://github.com/dotnet/runtime/assets/1439341/1ed7eb14-2497-4b14-8574-dc94b634eed5)

The fact the stack trace seemed to have changed made me think the fix had gone in too.

I've updated a bunch of repos to `8.0.100-rc.2.23422.31` just now and the problem does indeed appear to be resolved 🙇

https://github.com/martincostello/dependabot-helper/pull/820

**Comment by karelz** [comment]
Fixed in 8.0 (main) in PR #90503.
