### ISSUE TITLE
System.Runtime.InteropServices.SEHException blocking runtime-coreclr superpmi-collect pipeline

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#90947]
Multiple CoreCLR tests from the last run of the superpmi-collect pipeline are failing with `System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.` Here are the [pipeline results](https://dev.azure.com/dnceng/internal/_build/results?buildId=2249475&view=ms.vss-test-web.build-test-results-tab), and an example stack trace:
```
    baseservices\typeequivalence\istypeequivalent\istypeequivalent\istypeequivalent.cmd [FAIL]
      Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
         at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
         at Xunit.Sdk.AssertEqualityComparer`1.IsSet(TypeInfo typeInfo) in /_/src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs:line 333
         at Xunit.Sdk.AssertEqualityComparer`1.CheckIfSetsAreEqual(T x, T y, TypeInfo typeInfo) in /_/src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs:line 295
         at Xunit.Sdk.AssertEqualityComparer`1.Equals(T x, T y, Nullable`1& mismatchIndex) in /_/src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs:line 111
         at Xunit.Sdk.AssertEqualityComparer`1.Equals(T x, T y) in /_/src/xunit.assert/Asserts/Sdk/AssertEqualityComparer.cs:line 49
         at Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 301
         at istypeequivalent.Test.TestTypesWhichShouldMatch()
         at istypeequivalent.Test.Main()
```

Here's the [offending line](https://github.com/xunit/assert.xunit/blob/2.4.2/Sdk/AssertEqualityComparer.cs#L334) in AssertEqualityComparer.cs; looks like an issue with `GetTypeInfo()`.

**Comment by BruceForstall** [comment]
I've run many superpmi collections recently as part of #91101 and haven't seen this, so I'm going to chalk this up as a "random" failure and close it.

If it still occurs (in a superpmi collection), feel free to re-open.
