### ISSUE TITLE
AddJwtBearer doesn't consider system proxy settings

### ISSUE THREAD

**Issue by behrouz-rad-snkeos** [dotnet/runtime#90985]
### Description

When we have an Authority to validate the access token and environment variables for proxy settings have been defined (HTTP_PROXY, HTTPS_PROXY, NO_PROXY), the HttpClient which is responsible to make a request to the Authority url seems doesn't consider system proxy settings.

### Reproduction Steps

```c#
    builder.Services
      .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
      .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
        {
          options.Authority = JWT_AUTHORITY;
          options.SaveToken = true;
          options.TokenValidationParameters = new TokenValidationParameters
          {
            ValidateIssuer = false,
            ValidateAudience = false,
            RequireAudience = false,
          };
        }
      );
```

### Expected behavior

The request should be successful.

### Actual behavior

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://proxy.site.net:8080/' failed with status code '503'."
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Company.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in
```

### Known Workarounds

We had to set the proxy settings directly and it worked
```c#
    builder.Services
      .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
      .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
        {
          options.Authority = JWT_AUTHORITY;
          options.BackchannelHttpHandler = new HttpClientHandler
          {
            UseProxy = true,
            Proxy = new WebProxy
            {
              Address = new Uri("http://proxy.site.net:8080"),
              BypassProxyOnLocal = true,
              BypassList = new string[] { "localhost" },
            }
          };
          options.SaveToken = true;
          options.TokenValidationParameters = new TokenValidationParameters
          {
            ValidateIssuer = false,
            ValidateAudience = false,
            RequireAudience = false,
          };
        }
      );
```

### Configuration

- .NET 6.0
- Windows 10 Enterprise
- x64

**Comment by karelz** [comment]
From the exception, it seems proxy is being taken into account, it just return [503 HTTP status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503). That looks like proxy issue, not client issue.

**Comment by antonfirsov** [comment]
The top level API-s in question, `JwtBearerExtensions` and `AuthenticationServiceCollectionExtensions` are owned by aspnet, I think this issue should be transferred.

**Comment by karelz** [comment]
> The top level API-s in question, `JwtBearerExtensions` and `AuthenticationServiceCollectionExtensions` are owned by aspnet, I think this issue should be transferred.

It would be great to see if vanilla HttpClient works. That will tell us if this is the right place to file an issue.
Can you folks give it a try?

Also, I did NOT understand clearly what is the original report about -- from reply https://github.com/dotnet/runtime/issues/90985#issuecomment-1690088993 it seems that the KEY problem is that NO_PROXY is being ignored for localhost, while HTTPS_PROXY works correctly. Is that good summary?

**Comment by behrouz-rad-snkeos** [comment]
Ok we did further tests. Here are things we did.

On a developer system without proxy settings:
1) A simple Web API project with authentication/authorization enabled was created. The authentication service was created as following:
```
builder.Services
  .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
  .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
  {
    options.Authority = "https://localhost:4444";
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
      ValidateIssuer = false,
      ValidateAudience = false,
      RequireAudience = false,
    };
  }
);
var app = builder.Build();
app.UseAuthentication();
app.UseAuthorization();
```
2) The endpoint was protected with `[Authorize]` attribute.
3) A simple Console App was created to test the endpoint.
3-1) By using the `HttpClient` and without the access token the endpoint returned 401. With the access token the data was returned successfully, which is the expected behavior.

We brought both projects to a machine on which the proxy is set via HTTP_PROXY (http://proxy.site.net:8080), HTTPS_PROXY (http://proxy.site.net:8080), and NO_PROXY (localhost).
When we ran the console app, the operation was unsuccessful and the following stack trace was returned:
```
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://proxy.site.net:8080/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.SendAsyncAndRetryOnNetworkError(HttpClient httpClient, Uri uri)
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
       ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'http://proxy.site.net:8080/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.SendAsyncAndRetryOnNetworkError(HttpClient httpClient, Uri uri)
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Then we modified the Web API project as following:
```
builder.Services
  .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
  .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
  {
    options.BackchannelHttpHandler = new HttpClientHandler
    {
      UseProxy = true,
      Proxy = new WebProxy
      {
        Address = new Uri("http://proxy.site.net:8080/"),
        BypassProxyOnLocal = true,
        BypassList = new[] { "localhost" },
      }
    };
    options.Authority = "https://localhost:4444";
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
      ValidateIssuer = false,
      ValidateAudience = false,
      RequireAudience = false,
    };
  }
);
```
With these changes the request was successful and we got the data from the protected endpoint.

**Comment by karelz** [comment]
@behrouz-rad-snkeos were you able to test out also vanilla Console app with HttpClient? No `JwtBearer`, no ASP.NET -- just a request to see if it gets proxied correctly or not.

**Comment by behrouz-rad-snkeos** [comment]
> @behrouz-rad-snkeos were you able to test out also vanilla Console app with HttpClient? No `JwtBearer`, no ASP.NET -- just a request to see if it gets proxied correctly or not.

Yes, I can confirm that `HttpClient` correctly detects proxy settings and I was able to get the data from a public endpoint.

**Comment by karelz** [comment]
OK, so just to be super-clear:
- WHEN you set the environment variables above (NO_PROXY without http prefix to localhost)
- AND WHEN you use `HttpClient` (without setting its Proxy explicitly),
- THEN things work CORRECTLY from Console HelloWorld app,
- BUT they FAIL from Web API app using `JwtBearer`.

Is that correct understanding?

And you get these results on multiple machines.
Do you have a machine where you can delete the environment variables and THEN both app works and once you SET the evn. vars, then it stops working?

**Comment by karelz** [comment]
Another question: Do you use http/https prefix in the NO_PROXY URLs?

**Comment by behrouz-rad-snkeos** [comment]
> OK, so just to be super-clear:
> 
> * WHEN you set the environment variables above (especially NO_PROXY)
> * AND WHEN you use `HttpClient` (without setting its Proxy explicitly),
> * THEN things work CORRECTLY from Console HelloWorld app,
> * BUT they FAIL from Web API app using `JwtBearer`.
> 
> Is that correct understanding?
> 
Yes, that is correct.

> Do you have a machine where you can delete the environment variables and THEN both app works and once you SET the evn. vars, then it stops working?

On the same machine I removed the the envs and restarted the machine. The Console App successfully retrieved the data from the public localhost endpoint and also managed to receive the data from the protected endpoint (without setting proxy anywhere). I set again the envs and that problem happened again.
> Another question: Do you use http/https prefix in the NO_PROXY URLs of localhost?

No

**Comment by karelz** [comment]
Thanks for confirmation. Feels like we are getting closer to which area to focus on.

Can you give it a try with NO_PROXY with http and https prefixes? Would that help?

**Comment by behrouz-rad-snkeos** [comment]
> Thanks for confirmation. Feels like we are getting closer to which area to focus on.
> 
> Can you give it a try with NO_PROXY with http and https prefixes? Would that help?

I tested with both `http://localhost` and `https://localhost` and something more strange happened.

Previously that error was on the Web API project side, but now the same error happens on the Console App side for both public and protected localhost endpoint.

Here is the code for the Console App if you are interested in:
```
using IdentityModel.Client;

var handler = new HttpClientHandler
{
    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
};

var httpClient = new HttpClient(handler)
{
    BaseAddress = new Uri("https://localhost:7013")
};

var tokenResponse = await httpClient.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
{
  Address = "https://localhost:4444/oauth2/token",
  ClientId = "client_id",
  ClientSecret = "client_secret",
  Scope = "openid profile user/*.read user/*.write"
});
httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {tokenResponse.AccessToken}");

var response = await httpClient.GetAsync("weatherforecast");
var data = await response.Content.ReadAsStringAsync();

Console.WriteLine(data);
```

**Comment by wfurt** [comment]
Did you try to enable tracing and look at HTTP logs @behrouz-rad-snkeos?. This is long but it seems like you do not expect proxy to but used for `localhost` but the failing method is `EstablishProxyTunnelAsync` e.g. `HttpClient` trying to connect to proxy. And strangely, it gets 503 error back. It may be worth of trying to do packet capture.  As @antonfirsov mentioned the builder & Jwt are not runtime components so it is difficult to know what exactly  is happening there.

Also if you step through in debugger, you should see is that is `HttpEnvironmentProxy` or system proxy. 
And for the environmental proxy you can check if `_bypass` is set to what you expect it.
