### ISSUE TITLE
Test crashes on System.Net.Security Test Suite

### ISSUE THREAD

**Issue by liveans** [dotnet/runtime#91014]
### Error Blob

```json
{
  "ErrorMessage": "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

**Comment by wfurt** [comment]
It happen to reproduce for me locally while working on something else.
```
(lldb) clrstack
OS Thread Id: 0x3c17ed (1)
        Child SP               IP Call Site
00007F967A7FADC0 00007fd7d608603b [HelperMethodFrame_3OBJ: 00007f967a7fadc0] System.Environment.FailFast(System.String, System.Exception, System.String)
00007F967A7FAF00 00007FD75905CACE System.Diagnostics.DebugProvider.FailCore(System.String, System.String, System.String, System.String) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.Unix.cs @ 28]
00007F967A7FAF50 00007FD75905C710 System.Diagnostics.DebugProvider.Fail(System.String, System.String) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.cs @ 29]
00007F967A7FAFA0 00007FD75905C663 System.Diagnostics.Debug.Fail(System.String, System.String) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs @ 133]
00007F967A7FAFD0 00007FD75881285D System.Net.HttpConnection.get_LocalEndPoint() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpConnection.cs @ 169]
00007F967A7FB020 00007FD758812766 System.Net.HttpListenerRequest.get_LocalEndPoint() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListenerRequest.Managed.cs @ 338]
00007F967A7FB050 00007FD758810894 System.Net.HttpListenerRequest.FinishInitialization() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListenerRequest.Managed.cs @ 168]
00007F967A7FB2B0 00007FD75880C55E System.Net.HttpConnection.OnReadInternal(System.IAsyncResult) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpConnection.cs @ 295]
00007F967A7FB3B0 00007FD75880BE34 System.Net.HttpConnection.OnRead(System.IAsyncResult) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpConnection.cs @ 254]
00007F967A7FB3E0 00007FD7590589A2 System.Threading.Tasks.TaskToAsyncResult+TaskAsyncResult.<.ctor>b__2_0() [/home/furt/github/wfurt-runtime2/src/libraries/Common/src/System/Threading/Tasks/TaskToAsyncResult.cs @ 154]
00007F967A7FB410 00007FD758F543F4 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs @ 179]
00007F967A7FB460 00007FD758F5823F System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback, System.Object, System.Threading.Tasks.Task ByRef) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs @ 702]
00007F967A7FB490 00007FD759058844 System.Threading.Tasks.AwaitTaskContinuation.Run(System.Threading.Tasks.Task, Boolean) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs @ 572]
00007F967A7FB500 00007FD758F56C23 System.Threading.Tasks.Task.RunContinuations(System.Object) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs @ 3468]
00007F967A7FB5A0 00007FD758F7074F System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib]].TrySetResult(Int32) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs @ 398]
00007F967A7FB5E0 00007FD75880B245 System.Threading.Tasks.ValueTask`1+ValueTaskSourceAsTask+<>c[[System.Int32, System.Private.CoreLib]].<.cctor>b__4_0(System.Object) [/home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs @ 665]
00007F967A7FB650 00007FD7585B89FD System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs @ 1031]
00007F967A7FB670 00007FD7585B89A0 System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 210]
00007F967A7FB690 00007FD7585B8829 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32, System.Net.Sockets.SocketFlags) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs @ 981]
00007F967A7FB6D0 00007FD7585B875A System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs @ 382]
00007F967A7FB700 00007FD7585B86EF System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32, System.Memory`1<Byte>, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs @ 102]
00007F967A7FB760 00007FD7585B8558 System.Net.Sockets.SocketAsyncContext+BufferMemoryReceiveOperation.InvokeCallback(Boolean) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 501]
00007F967A7FB7C0 00007FD7585B6A47 System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].ProcessAsyncOperation(System.__Canon) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 1004]
00007F967A7FB810 00007FD7585B6893 System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 1413]
00007F967A7FB830 00007FD7585B6830 System.Net.Sockets.SocketAsyncContext+ReadOperation.System.Threading.IThreadPoolWorkItem.Execute() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 340]
00007F967A7FB850 00007FD7585B674D System.Net.Sockets.SocketAsyncContext+AsyncOperation.Process() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 291]
00007F967A7FB870 00007FD758582E7B System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents) [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 2197]
00007F967A7FB8C0 00007FD7585827D7 System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute() [/home/furt/github/wfurt-runtime2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs @ 242]
```
when I look at at object, the `_socket` is null.


```
(lldb) dumpobj 0x00007f97454e03e0
Name:        System.Net.HttpConnection
MethodTable: 00007fd7589e9a70
EEClass:     00007fd7589fbde8
Size:        200(0xc8) bytes
File:        /home/furt/github/wfurt-runtime2/artifacts/bin/testhost/net8.0-linux-Debug-x64/shared/Microsoft.NETCore.App/9.0.0/System.Net.HttpListener.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007fd7577878e8  40000dd        8 ...et.Sockets.Socket  0 instance 0000000000000000 _socket
00007fd7570cb498  40000e2       20     System.IO.Stream  0 instance 00007f97454e04a8 _stream
00007fd758a20490  40000e3       28 ...pEndPointListener  0 instance 00007f9745435290 _epl
00007fd7581ee7d0  40000e4       30 ...m.IO.MemoryStream  0 instance 00007f97454e05b0 _memoryStream
00007fd75707eef8  40000e5       38        System.Byte[]  0 instance 00007f97454e5420 _buffer
00007fd757b3de50  40000e6       40 ...tpListenerContext  0 instance 00007f97454e05f0 _context
00007fd757127120  40000e7       48 ...ext.StringBuilder  0 instance 0000000000000000 _currentLine
00007fd758a218e0  40000e8       50 ...et.ListenerPrefix  0 instance 0000000000000000 _prefix
00007fd758ace328  40000e9       58 ...HttpRequestStream  0 instance 0000000000000000 _requestStream
00007fd758ace7f0  40000ea       60 ...ttpResponseStream  0 instance 0000000000000000 _responseStream
00007fd756d7cc08  40000eb       b9       System.Boolean  1 instance                0 _chunked
00007fd756dd0980  40000ec       a4         System.Int32  1 instance                0 _reuses
00007fd756d7cc08  40000ed       ba       System.Boolean  1 instance                0 _contextBound
00007fd756d7cc08  40000ee       bb       System.Boolean  1 instance                0 _secure
00007fd757fc8530  40000ef       68 ...s.X509Certificate  0 instance 0000000000000000 _cert
00007fd756dd0980  40000f0       a8         System.Int32  1 instance            90000 _timeout
00007fd75898b3c0  40000f1       70 ...m.Threading.Timer  0 instance 00007f97454e0520 _timer
00007fd757badbf8  40000f2       78 ...em.Net.IPEndPoint  0 instance 0000000000000000 _localEndPoint
00007fd7589e7df8  40000f3       80 ....Net.HttpListener  0 instance 0000000000000000 _lastListener
00007fd756e48690  40000f4       88       System.Int32[]  0 instance 0000000000000000 _clientCertErrors
00007fd757fc8e70  40000f5       90 ....X509Certificate2  0 instance 0000000000000000 _clientCert
00007fd757b85940  40000f6       98 ...ecurity.SslStream  0 instance 0000000000000000 _sslStream
00007fd7589e9928  40000f7       ac         System.Int32  1 instance                1 _inputState
00007fd7589e99c8  40000f8       b0         System.Int32  1 instance                0 _lineState
00007fd756dd0980  40000f9       b4         System.Int32  1 instance              249 _position
00007fd756d7cc08  40000fa       bc       System.Boolean  1 instance                0 _closed
00007fd757fa6a80  40000dc       e8 System.AsyncCallback  0   static 00007f97422c4a30 s_onreadCallback
```

From what I can tell, the listener was closed and disposed via 
```
   at System.Net.HttpConnection.Close(Boolean force) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpConnection.cs:line 552
   at System.Net.HttpListenerResponse.Close(Boolean force) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListenerResponse.Managed.cs:line 109
   at System.Net.HttpListenerResponse.Close() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListenerResponse.Managed.cs:line 95
   at System.Net.HttpResponseStream.DisposeCore() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpResponseStream.Managed.cs:line 89
   at System.Net.HttpResponseStream.Dispose(Boolean disposing) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/HttpResponseStream.cs:line 87
   at System.IO.Stream.Close() in /home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs:line 165
   at System.Net.HttpConnection.Close(Boolean force) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpConnection.cs:line 513
   at System.Net.HttpEndPointListener.Close() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointListener.cs:line 315
   at System.Net.HttpEndPointManager.RemoveEndPoint(HttpEndPointListener epl, IPEndPoint ep) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs:line 180
   at System.Net.HttpEndPointListener.CheckIfRemove() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointListener.cs:line 303
   at System.Net.HttpEndPointListener.RemovePrefix(ListenerPrefix prefix) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointListener.cs:line 402
   at System.Net.HttpEndPointManager.RemovePrefixInternal(String prefix, HttpListener listener) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs:line 213
   at System.Net.HttpEndPointManager.RemoveListener(HttpListener listener) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpEndPointManager.cs:line 190
   at System.Net.HttpListener.Close(Boolean force) in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs:line 154
   at System.Net.HttpListener.Dispose() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs:line 137
   at System.Net.HttpListener.System.IDisposable.Dispose() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/HttpListener.cs:line 324
   at System.Net.HttpListener.Close() in /home/furt/github/wfurt-runtime2/src/libraries/System.Net.HttpListener/src/System/Net/HttpListener.cs:line 303
   at System.Security.Cryptography.X509Certificates.Tests.Common.RevocationResponder.Dispose() in /home/furt/github/wfurt-runtime2/src/libraries/Common/tests/System/Security/Cryptography/X509Certificates/RevocationResponder.cs:line 49
   at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext, Boolean noIntermediates)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 179
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /home/furt/github/wfurt-runtime2/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 349
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _) in /_/src/xunit.execution/Sdk/AsyncTestSyncContext.cs:line 75
   at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state) in /_/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 106

```

So this looks like bug in HttpListener. We can probably reproduced while rapidly creating and destroying the listener. 
As minimum, we can perhaps guard agains null in the LocalEndPoint method.

However it is unpleasant as the exception happens on thread pool it kills the whole process. It may be worth of guarding some section with try/catch and swallow the exception(s) quetly. 
 

I'm wondering if we should take minimal fix to 8.0 @karelz to stabilize CI runs and decrease noise.

**Comment by karelz** [comment]
Yeah, we might need it in 8.0 to decrease noise in test results. @liveans can you please take a look?
Once we have 9.0 fix, we can decide what to do and if to port it to 8.0. Thanks!

**Comment by liveans** [comment]
I can't repro this locally, but we have talked with @wfurt, based on the logs and dumps @wfurt already has a proposed fix.
