### ISSUE TITLE
Error in DefaultHttpClientFactory timer method

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#91053]
### Description

`DefaultHttpClientFactory` was updated to lazily acquire `ILoggerFactory`:

https://github.com/dotnet/runtime/blob/c4f8c3b27a8fb2e452a57a6516050c8c2ee677f4/src/libraries/Microsoft.Extensions.Http/src/DefaultHttpClientFactory.cs#L98-L100

However there is now the chance for code in the background method to throw an error if `ILoggerFactory` has been disposed:

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
   at Microsoft.Extensions.Logging.LoggerFactoryExtensions.CreateLogger[T](ILoggerFactory factory)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.ExpiryTimer_Tick(Object state)
   at Microsoft.Extensions.Http.ActiveHandlerTrackingEntry.Timer_Tick()
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Because the error happens inside a `Timer` method, the process crashes. Needs to be fixed for .NET 8.

### Reproduction Steps

I don't have an exact repo because this error came from a test, and I'm not sure exactly which one. However, I imagine it can be simulated by starting the factory and then disposing of the service collection.

### Expected behavior

The process doesn't crash.

What I think should happen is the code inside the lazy checks for this error and returns `NullLogger.Instance` if the factory has been disposed.

```cs
_logger = new Lazy<ILogger>(
() =>
{
    // The ILoggerFactory could have been disposed after the HttpClientFactory was created but before the clean-up timer.
    // Return a null logger instance to allow clean-up code to continue to run until HttpClientFactory is stopped.
    try { return _services.GetRequiredService<ILoggerFactory>().CreateLogger<DefaultHttpClientFactory>(); }
    catch (ObjectDisposedException) { return NullLogger.Instance; }
}
LazyThreadSafetyMode.ExecutionAndPublication);
```

### Actual behavior

Process crashes.

### Regression?

Yes

**Comment by karelz** [comment]
Triage: Agreed, crash in a new feature - we should address it.

**Comment by karelz** [comment]
@liveans can you please take a look at it while @CarnaViire is on vacation?

**Comment by vcsjones** [comment]
Possible duplicate of https://github.com/dotnet/runtime/issues/90919 and may already be fixed?

**Comment by karelz** [comment]
Duplicate of #90919

**Comment by JamesNK** [comment]
Yes, this is a duplicate.

I think my suggested fix is cleaner than the committed one, but it doesn't matter enough to change.

**Comment by karelz** [comment]
We can beautify it in 9.0 if @CarnaViire agrees ;)
