### ISSUE TITLE
EncryptedXml fails to decrypt element encrypted by a X509 certificate referenced by a negative issuer serial

### ISSUE THREAD

**Issue by vgriph** [dotnet/runtime#91064]
### Description

When trying to decrypt an xml document that has been encrypted with a certificate with a negative serial number, the `EncryptedXml` fails to find that certificate for decryption. 

### Reproduction Steps

1. Create a self signed certificate with a negative serial number for test purpose
```
New-SelfSignedCertificate -SerialNumber 'c0000000000000000000000000000001'  -Subject 'CN=test' -CertStoreLocation Cert:\CurrentUser\My
``` 
Note the output thumbprint in the output.
```
   PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\My

Thumbprint                                Subject
----------                                -------
153CDC6432F5EF5804850349C0FDA8AFC619CB5D  CN=test
```

2. Create a new console app project
3.Add a NuGet reference to System.Security.Cryptography.Xml v 7.0.1
4. Enter the following code
```
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography.Xml;
using System.Xml;

var store = new X509Store(StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);
var cert = store.Certificates.Find(
    X509FindType.FindByThumbprint, 
    "153CDC6432F5EF5804850349C0FDA8AFC619CB5D", // Use the value returned when creating the certificate
    false).Single();
store.Close();

var xml = new XmlDocument();
xml.LoadXml("<Test/>");
var encryptor = new EncryptedXml();
var encrypted = encryptor.Encrypt(xml.DocumentElement, cert);

// The encryption embeds the certificate in the document. Replace it with a issuer serial reference.
var keyInfo = encrypted.KeyInfo.Cast<KeyInfoEncryptedKey>().Single()
    .EncryptedKey.KeyInfo.Cast<KeyInfoX509Data>().Single();
keyInfo.Certificates.Clear();
keyInfo.AddIssuerSerial(cert.IssuerName.Name, cert.GetSerialNumberString());
EncryptedXml.ReplaceElement(xml.DocumentElement, encrypted, false);

var decryptor = new EncryptedXml(xml);
decryptor.DecryptDocument();
```

### Expected behavior

It should be possible to decrypt the XML

### Actual behavior

```
System.Security.Cryptography.CryptographicException
  HResult=0x80131501
  Message=Unable to retrieve the decryption key.
  Source=System.Security.Cryptography.Xml
  StackTrace:
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri) in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs:line 375
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument() in /_/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/EncryptedXml.cs:line 671
   at Program.<Main>$(String[] args) in ConsoleApp1\Program.cs:line 24
```

### Known Workarounds

Override the `public byte[]? DecryptEncryptedKey(EncryptedKey encryptedKey)` and provide an alternative implementation

```
using System.Numerics;
using System.Security.Cryptography.X509Certificates;
using System.Security.Cryptography.Xml;
using System.Xml;

namespace ConsoleApp1
{
    internal class WorkAround : EncryptedXml
    {
        public WorkAround(XmlDocument document) : base(document) { }

        public override byte[]? DecryptEncryptedKey(EncryptedKey encryptedKey)
        {
            var key = base.DecryptEncryptedKey(encryptedKey);
            if (key == null)
            {
                var store = new X509Store(StoreLocation.CurrentUser);
                store.Open(OpenFlags.ReadOnly);
                var allCerts = store.Certificates;
                store.Close();
                foreach (var keyInfo in encryptedKey.KeyInfo.OfType<KeyInfoX509Data>()
                             .Where(x => x.IssuerSerials is { Count: > 0 }))
                {
                    foreach (var issuerSerial in keyInfo.IssuerSerials.Cast<X509IssuerSerial>())
                    {
                        var issuerCerts = allCerts.Find(X509FindType.FindByIssuerDistinguishedName,
                            issuerSerial.IssuerName, false);
                        var parsedSerialNumber = BigInteger.Parse(issuerSerial.SerialNumber);
                        var matching = issuerCerts.Find(X509FindType.FindBySerialNumber,
                            parsedSerialNumber.ToString("x2"), false);

                        if (matching.Count > 0)
                        {
                            keyInfo.AddCertificate(matching[0]);
                            keyInfo.IssuerSerials.Clear();
                            return base.DecryptEncryptedKey(encryptedKey);
                        }
                    }
                }
            }

            return key;
        }
    }
}
```

### Configuration

.NET 7 on Windows 10 21H2 (64-bit)

**Comment by vcsjones** [comment]
This is a regression from .NET Framework 4.8, so for consistency purposes I think we should address this in .NET 9.

Given that negative serial numbers are non-conformant, (RFC 5280, 4.1.2.2) I don't think we need to fix this for .NET 8, and also there is a work around posted in the original issue.

**Comment by vcsjones** [comment]
Okay, so I finally got around to looking at this, and this appears to have been broken a long time ago in https://github.com/dotnet/corefx/pull/14662.

The problem is not with decrypting - the problem is with encrypting. Rather, when you encrypt, it write down the serial number as `<X509SerialNumber>-85070591730234615865843651857942052863</X509SerialNumber>`, whereas .NET Framework writes it down as `<X509SerialNumber>255211775190703847597530955573826158593</X509SerialNumber>`.

We should change the encoding in `KeyInfoX509Data` to work the same as .NET Framework.
