### ISSUE TITLE
DataContractJsonSerializer throws exception - Value cannot be null. (Parameter 'key')

### ISSUE THREAD

**Issue by davidliang2008** [dotnet/runtime#91104]
### Description

I have a JSON string I want to deserialize to `Microsoft.Xrm.Sdk.Entity` object:
```
{
    "Id": "28bdb958-71fd-e711-8129-5065f38be461",
    "Name": "name",
    "Attributes": [
        { "Key": "key1", "Value": "value1" },
        { "Key": "key2", "Value": "value2" }
    ]
}
```
and I have the following code to parse JSON string (let's name it jsonString) to the Entity object:
```c#
using System.IO;
using System.Runtime.Serialization.Json;
using System.Text;
using Microsoft.Xrm.Sdk;

var serializer = new DataContractJsonSerializer(typeof(Entity));
using var stream = new MemoryStream(Encoding.ASCII.GetBytes(jsonString));
var entity = serializer.ReadObject(stream) as Entity;
```

### Reproduction Steps

https://dotnetfiddle.net/lm2gj7

### Expected behavior

The JSON string would be parsed correctly to `Microsoft.Xrm.Sdk.Entity` without errors

### Actual behavior

it throws an unhandled exception:
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(KeyValuePair`2 keyValuePair)
   at ReadAttributeCollectionFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   at System.Runtime.Serialization.Json.JsonCollectionDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at ReadEntityFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
```

### Known Workarounds

If the `Key` and `Value` are passed as lower key, it worked!
```json
{
    "Id": "28bdb958-71fd-e711-8129-5065f38be461",
    "Name": "name",
    "Attributes": [
        { "key": "key1", "value": "value1" },
        { "key": "key2", "value": "value2" }
    ]
}
```

Here is the working demo: https://dotnetfiddle.net/sbEJyl

### Other information

- I filed [a bug](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/issues/395) under Microsoft.Powerplatform.Dataverse.Client too.
- I am using Microsoft.PowerPlatform.Dataverse.Client, version 1.0.1.

**Comment by gregsdennis** [comment]
Have you tried using the `System.Text.Json` serializer instead of the `DataContractSerializer`?

**Comment by davidliang2008** [comment]
> Have you tried using the `System.Text.Json` serializer instead of the `DataContractSerializer`?

Yes, it throwed even more exceptions.

**Comment by StephenMolloy** [comment]
`DataContractJsonSerializer` (DCJS) is designed as an opinionated serializer that follows specific conventions for round-trip serialization. When DCJS serializes collections of key/value pairs (like the `AttributeCollection` in `Microsoft.Xrm.Sdk.Entity`), it uses lowercase property names ("key" and "value") by convention. This is consistent with how both DCJS and its XML counterpart `DataContractSerializer` handle dictionary-like collections.

The JSON you're trying to deserialize appears to be from another source that uses different casing conventions ("Key" and "Value" with capital letters). Since DCJS expects its own serialization format for proper deserialization, this mismatch causes the error you're seeing.

For your use case, where you need to deserialize JSON from external sources with different formatting conventions, I'd recommend using a more flexible, general-purpose JSON serializer such as:

- **System.Text.Json** (built into modern .NET)
- **Newtonsoft.Json** (JSON.NET)

These serializers offer more control over property name mapping and can handle various casing conventions through configuration.

Since this behavior is by design for `DataContractJsonSerializer`, I'll be closing this issue.
