### ISSUE TITLE
Test failure Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#91188]
**Failed in:** [runtime-coreclr libraries-pgo 20230827.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=387379&view=ms.vss-test-web.build-test-results-tab&runId=8294572&resultId=102428&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-arm64-CoreCLR_checked-defaultpgo-Windows.11.Arm64.Open
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty
```

**Error message:**
```
Assert.Equal() Failure
Expected: stuff
Actual:   (null)
```

**Stack trace:**
```
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty() in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/Common/ConfigurationBinderTests.cs:line 751
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by tarekgh** [comment]
This is duplicate of https://github.com/dotnet/runtime/issues/86532

**Comment by tarekgh** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/91308
