### ISSUE TITLE
Error on `TimeZoneInfo.FromSerializedString` 

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#91312]
### Description

`TimeZoneInfo.FromSerializedString` throws on some timezone.

### Reproduction Steps

```csharp
foreach (TimeZoneInfo t in TimeZoneInfo.GetSystemTimeZones())
{
    string s = t.ToSerializedString();
    try
    {
        TimeZoneInfo.FromSerializedString(s);
    }
    catch (Exception ex)
    {
        Console.WriteLine(s);
        Console.WriteLine(ex);
        return;
    }
}
```

### Expected behavior

Empty output.

### Actual behavior

```
Pacific/Niue;-660;(UTC-11:00) Niue Time;Niue Time;GMT-11:00;[01:01:0001;12:31:0001;0;[1;00:00:00;1;1;];[1;23:59:59.999;12;31;];-19;][01:01:0002;12:31:1951;0;[1;00:00:00;1;1;];[1;23:59:59.999;12;31;];-19;][01:01:1952;10:16:1952;0;[1;00:00:00;1;1;];[1;00:19:39.999;10;16;];-19;][10:16:1952;12:31:1952;0;[1;00:19:40;10;16;];[1;23:59:59.999;12;31;];-20;][01:01:1953;12:31:1963;0;[1;00:00:00;1;1;];[1;23:59:59.999;12;31;];-20;][01:01:1964;07:01:1964;0;[1;00:00:00;1;1;];[1;00:19:59.999;7;1;];-20;];
System.Runtime.Serialization.SerializationException: An error occurred while deserializing the object.  The serialized data is corrupt.
 ---> System.InvalidTimeZoneException: The elements of the AdjustmentRule array must be in chronological order and must not overlap.
   at System.TimeZoneInfo.ValidateTimeZoneInfo(String id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, Boolean& adjustmentRulesSupportDst)
   at System.TimeZoneInfo..ctor(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime, Boolean hasIanaId)
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   at Program.<Main>$(String[] args)
```

### Configuration

Ubuntu 22
.NET 6 & .NET 7

**Comment by skyoxZ** [comment]
Oh it has been reported. Duplicate #19794
