### ISSUE TITLE
[mono] Runtime crash in full AOT mode when using `LiteDB` 

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#91332]
### Description

When an iOS application uses `LiteDB` library, Mono runtime tends to crash with:
```
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971] System.TypeInitializationException: TypeInitialization_Type, LiteDB.BsonExpression
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]  ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) LiteDB.BsonValue object:Thunk1ret_BsonValue_IEnumerable`1_BsonDocument_BsonValue_Collation_BsonDocument (System.Func`2<object[], object>,System.Collections.Generic.IEnumerable`1<LiteDB.BsonDocument>,LiteDB.BsonDocument,LiteDB.BsonValue,LiteDB.Collation,LiteDB.BsonDocument)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

Below I have provided the minimal repro causing the failure. 

### Reproduction Steps

1. Install .NET8 preview 7
2. Install ios workload
    ```bash
    dotnet workload install ios
    ```
3. Create ios template app
    ```bash
    dotnet new ios -n TestLiteDB ; cd TestLiteDB
    ```
4. Add `LiteDB` reference
    ```bash
    dotnet add package LiteDB --version 5.0.17
    ```
5. Change the `AppDelegate.cs` code by adding the following lines in `FinishedLaunching` method:
    ```cs
    string msg = "Hello, iOS!";
    try 
    {
        LiteDB.BsonExpression.Create("$.Price");
    }
    catch (Exception ez)
    {
        msg = ez.ToString();
    }
    Console.WriteLine(msg);
    ```
6. Build and run the app on a device:
    ```bash
    dotnet publish -r ios-arm64 -c Release -t:Run -bl
    ```
    
PS It is also possible to extract the referenced library in a HelloWorld app built in full AOT mode (iOS is used in this example due to its default AOT configuration)

### Expected behavior

The app does not crash.

### Actual behavior

The app crashes with:
```
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971] System.TypeInitializationException: TypeInitialization_Type, LiteDB.BsonExpression
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]  ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) LiteDB.BsonValue object:Thunk1ret_BsonValue_IEnumerable`1_BsonDocument_BsonValue_Collation_BsonDocument (System.Func`2<object[], object>,System.Collections.Generic.IEnumerable`1<LiteDB.BsonDocument>,LiteDB.BsonDocument,LiteDB.BsonValue,LiteDB.Collation,LiteDB.BsonDocument)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type , Object )
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type , Func`2 )
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type , Func`2 )
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate(Type )
   at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate(IStrongBox[] )
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at System.Linq.Expressions.Expression`1[[LiteDB.BsonExpressionScalarDelegate, LiteDB, Version=5.0.17.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27]].Compile()
   at LiteDB.BsonExpression.<>c__DisplayClass70_0.<Compile>b__0(String s)
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at System.Collections.Concurrent.ConcurrentDictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[LiteDB.BsonExpressionScalarDelegate, LiteDB, Version=5.0.17.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27]].GetOrAdd(String , Func`2 )
   at LiteDB.BsonExpression.Compile(BsonExpression expr, ExpressionContext context)
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at LiteDB.BsonExpression.ParseAndCompile(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters, DocumentScope scope)
   at LiteDB.BsonExpression.Create(Tokenizer tokenizer, BsonExpressionParserMode mode, BsonDocument parameters)
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at LiteDB.BsonExpression.Create(String expression, BsonDocument parameters)
   at LiteDB.BsonExpression.Create(String expression)
   at LiteDB.BsonExpression..cctor()
   Exception_EndOfInnerExceptionStack
2023-08-30 14:40:53.182 TestLiteDB[33696:14992971]    at TestLiteDB.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
```

### Regression?

The failure is present when targeting .NET7 as well, tested by changing the target framework in the project file to:
```xml
<TargetFramework>net7.0-ios</TargetFramework>
```

### Known Workarounds

Enabling Mono interpreter via: `-p:UseInterpreter=true` works around the issue.

### Other information

Possibly related to: https://github.com/dotnet/runtime/issues/90092

**Comment by GiaNTizmO** [comment]
LiteDB use some code generation (Linq Expression Emitting if I remember correctly)
I have previously contacted one of the authors of the LiteDB library.
We are waiting for a new version of LiteDB with AOT support. (https://github.com/mbdavid/LiteDB-vNext)
https://github.com/mbdavid/LiteDB/issues/2338

**Comment by ivanpovazan** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/94063
