### ISSUE TITLE
Test failure System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#91368]
**Failed in:** [runtime-coreclr libraries-jitstress 20230830.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=390295&view=ms.vss-test-web.build-test-results-tab&runId=8371998&resultId=119917&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)
net8.0-linux-Release-arm-CoreCLR_checked-jitstress1_tiered-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)
```

**Error message:**
```
System.Exception : Inconsistent LargeStruct: 1 1 1 1 1 1 1 0
```

**Stack trace:**
```
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.LargeStruct.get_Value() in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 1030
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.<>c__DisplayClass52_0.<ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking>b__1() in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 871
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2399
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2385
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 179
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 203
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2345
--- End of stack trace from previous location ---
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.WaitAllOrAnyFailed(Task[] tasks) in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 1013
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(Double seconds) in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 876
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 178
```

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr libraries-jitstress 20230906.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=396564&view=ms.vss-test-web.build-test-results-tab&runId=8556720&resultId=138394&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-CoreCLR_checked-jitstress1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(seconds: 1)
```

**Error message:**
```
System.Exception : Inconsistent LargeStruct: 1 1 0 0 0 0 0 0
```

**Stack trace:**
```
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.LargeStruct.get_Value() in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 1030
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.<>c__DisplayClass52_0.<ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking>b__1() in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 871
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2399
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2385
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 179
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 203
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2345
--- End of stack trace from previous location ---
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.WaitAllOrAnyFailed(Task[] tasks) in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 1013
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakesPeeks_ForceContentionWithOtherThreadsPeeking(Double seconds) in /_/src/libraries/System.Collections.Concurrent/tests/ProducerConsumerCollectionTests.cs:line 876
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 178
```

**Comment by eiriktsarpalis** [comment]
This issue isn't following the standard test failure template, so I'm going to assume that it has been resolved by now.
