### ISSUE TITLE
[linux-arm64] Random runtime crashes on AWS Gravitron3 with 7.0.400 SDK

### ISSUE THREAD

**Issue by tommaybe** [dotnet/runtime#91386]
### Describe the bug
We have been running on Gravitron2 instances for years without any runtime errors. Since upgrading to Gravitron3, quite frequently (at least several times per day) our application runtime crashes with:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'state')
   at System.Threading.ThreadPool.<>c.<.cctor>b__78_0(Object state)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

This seems similar to issues previously raised here, affecting also ARM:
https://github.com/dotnet/runtime/issues/70486
https://github.com/dotnet/runtime/issues/84407

However it is stated as fixed, which does not seem to be the case.

### To Reproduce
We were unable to produce sample code reproducing the error, but are facing the error in a mission-critical service every day.

### Exceptions (if any)
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'state')
   at System.Threading.ThreadPool.<>c.<.cctor>b__78_0(Object state)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Further technical details
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-arm64
 Base Path:   /usr/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: arm64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Hosting: Docker via Hashicorp Nomad on EC2, specifically c7g.2xlarge
IDE: Rider 2023.1.4

**Comment by tommaybe** [comment]
I can confirm that switching to .NET 8 Preview 7 seems to have solved the issue for us, if that helps in analysis.

**Comment by karelz** [comment]
@tommaybe sadly, that does not help. It might be just different timing, or something.

Few options here now:
1. Take dumps and look at them (quite involved and costly).
2. @MihaZupan has a suspicion that there was one change in 8.0 that might address it (PR #82147). That change is however pretty big and won't likely make it into servicing. However, one could try a private build of 7.0.x with that patch to see if it helps.
3. Use 8.0. RC1 will be out in couple of weeks and it will be go-live license -- i.e. supported. Would that be an option for you?

If the impact on you is severe, please contact official Microsoft support channels. We will do our best here, but there are no SLAs on GitHub.

**Comment by tommaybe** [comment]
@karelz Understood. It ran well for a few hours, now we're seeing crashes again, slightly reduced frequency but could be pure luck.

The exception has changed, should I raise it separately? This is now on .NET 8 Preview 7. 

```
System.ArgumentOutOfRangeException: An unexpected state object was encountered. This is usually a sign of a bug in async method custom infrastructure, such as a custom awaiter or IValueTaskSource implementation. (Parameter 'state')
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by jkotas** [comment]
> The exception has changed, should I raise it separately? This is now on .NET 8 Preview 7.

It is likely a different manifestation of the same problem. Are you able to collect core dumps for the crash?

**Comment by tommaybe** [comment]
I have taken a mini dump (Full) on crash - what can I share to help further analyse?

**Comment by jkotas** [comment]
> What can I share to help further analyse?

Could you please run `VerifyHeap` on the dump? It will help eliminate GC heap corruption as the cause.

> send the dump 

Unless you prefer a different way, you can share the dump with Microsoft by opening a feedback issue at https://developercommunity.visualstudio.com/, attaching the dump to it (the attachments are not publicly visible), and sharing the feedback issue ID here.

**Comment by tommaybe** [comment]
@antonfirsov There is no special middleware, we make use of Akka.NET further downstream, e.g. received GRPC messages are forwarded into the actor system.

I have reviewed our use of ValueTasks and cannot find an issue there either.

We have collected and compared about 4 crash dumps , each time the stack is the same, and we could get down to the socket instance indicating our GRPC port and the remote IP of our most busy remote service (which is calling this GRPC api).  

As this is a critical app for a financial trading service, I would have some reservations in sharing the dump fully, as there are probably dozens of keys, account ids, PII etc.... Any other way to get to the bottom of this? I would be happy to jump on a screenshare and debug it together, and I can accommodate any timezones... 😄

**Comment by tommaybe** [comment]
> > What can I share to help further analyse?
> 
> Could you please run `VerifyHeap` on the dump? It will help eliminate GC heap corruption as the cause.
> 
> > send the dump
> 
> Unless you prefer a different way, you can share the dump with Microsoft by opening a feedback issue at https://developercommunity.visualstudio.com/, attaching the dump to it (the attachments are not publicly visible), and sharing the feedback issue ID here.


@jkotas 
> Could you please run `VerifyHeap` on the dump? It will help eliminate GC heap corruption as the cause.

I have done this, no corruption detected.

**Comment by tommaybe** [comment]
Please treat the following as mildly educated guesswork, as we are not familiar with the sockets codebase.

The thread stack suggests that the origin of the exception is Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketReceiver, which derives from SocketAwaitableEventArgs, which is, according to the comments, a "slimmed down version" of the code that was touched in the PR #84432.

The exception seems to be thrown because _userToken in SocketAwaitableEventArgs is null (we verified that it is).

```
0:069> !dso
OS Thread Id: 0x1ea (69)
          SP/REG           Object Name
    fff74f7ed9d0     fff80fefe5e8 Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketReceiver
    [...]

0:069> !dumpobj /d fff80fefe5e8
Name:        Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketReceiver
MethodTable: 0000ffff5f66ba88
EEClass:     0000ffff5f682d50
Tracked Type: false
Size:        248(0xf8) bytes
File:        /usr/share/dotnet/shared/Microsoft.AspNetCore.App/8.0.0-preview.7.23375.9/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
0000ffff56a476f8  4000374      1b0     System.EventArgs  0   static 0000000000000000 Empty
0000ffff560113d8  4000156        8 ...et.Sockets.Socket  0 instance 0000000000000000 _acceptSocket
0000ffff560113d8  4000157       10 ...et.Sockets.Socket  0 instance 0000000000000000 _connectSocket
0000ffff556a52e8  4000158       c0 ...Private.CoreLib]]  1 instance 0000fff80fefe6a8 _buffer
0000ffff54770980  4000159       88         System.Int32  1 instance                0 _offset
0000ffff54770980  400015a       8c         System.Int32  1 instance                0 _count
0000ffff5474cab0  400015b       b8       System.Boolean  1 instance                0 _bufferIsExplicitArray
0000ffff5cd977b0  400015c       18 ...Private.CoreLib]]  0 instance 0000000000000000 _bufferList
0000ffff5cd99610  400015d       20 ...Private.CoreLib]]  0 instance 0000000000000000 _bufferListInternal
0000ffff54770980  400015e       90         System.Int32  1 instance                0 _bytesTransferred
0000ffff5474cab0  400015f       b9       System.Boolean  1 instance                0 _disconnectReuseSocket
0000ffff576721c8  4000160       94         System.Int32  1 instance                4 _completedOperation
0000ffff576723a0  4000161       d0 ...PacketInformation  1 instance 0000fff80fefe6b8 _receiveMessageFromPacketInfo
0000ffff576537c8  4000162       28  System.Net.EndPoint  0 instance 0000000000000000 _remoteEndPoint
0000ffff54770980  4000163       98         System.Int32  1 instance                0 _sendPacketsSendSize
0000000000000000  4000164       30              SZARRAY  0 instance 0000000000000000 _sendPacketsElements
0000ffff57672440  4000165       9c         System.Int32  1 instance                0 _sendPacketsFlags
0000ffff5765a460  4000166       a0         System.Int32  1 instance                0 _socketError
0000ffff547ff130  4000167       38     System.Exception  0 instance 0000000000000000 _connectByNameError
0000ffff576724e0  4000168       a4         System.Int32  1 instance                0 _socketFlags
0000ffff54745a80  4000169       40        System.Object  0 instance 0000000000000000 _userToken
0000ffff553064a8  400016a       48        System.Byte[]  0 instance 0000000000000000 _acceptBuffer
0000ffff54770980  400016b       a8         System.Int32  1 instance                0 _acceptAddressBufferCount
0000ffff57677f48  400016c       50 ...als.SocketAddress  0 instance 0000000000000000 _socketAddress
0000ffff5474cab0  400016d       ba       System.Boolean  1 instance                0 _flowExecutionContext
0000ffff54c89028  400016e       58 ....ExecutionContext  0 instance 0000000000000000 _context
0000ffff560113d8  4000170       60 ...et.Sockets.Socket  0 instance 0000fff80fefe298 _currentSocket
0000ffff5474cab0  4000171       bb       System.Boolean  1 instance                0 _userSocket
0000ffff5474cab0  4000172       bc       System.Boolean  1 instance                0 _disposeCalled
0000ffff54770980  4000173       ac         System.Int32  1 instance                0 _operating
0000ffff55a21d80  4000174       68 ...lationTokenSource  0 instance 0000000000000000 _multipleConnectCancellation
0000000000000000  4000175       70                       0 instance 0000000000000000 Completed
0000ffff547f5948  4000176       80        System.IntPtr  1 instance 0000000000000000 _acceptedFileDescriptor
0000ffff54770980  4000177       b0         System.Int32  1 instance                0 _socketAddressSize
0000ffff576724e0  4000178       b4         System.Int32  1 instance                0 _receivedFlags
0000ffff57743da8  4000179       78 ....Net.Primitives]]  0 instance 0000fff80fefeb60 _transferCompletionCallback
0000ffff553049e8  400016f       58 ...g.ContextCallback  0   static 0000fff80cc12300 s_executionCallback
0000ffff5d1529b8  4000061       e0 ...nes.PipeScheduler  0 instance 0000fff80c0745c8 _ioScheduler
0000ffff55a23cb0  4000062       e8 ...Private.CoreLib]]  0 instance 0000fff80a95dc48 _continuation
0000ffff55a23cb0  4000060       20 ...Private.CoreLib]]  0   static 0000fff80a95dc48 _continuationCompleted
```

**Comment by karelz** [comment]
@tommaybe 
> Any other way to get to the bottom of this? I would be happy to jump on a screenshare and debug it together, and I can accommodate any timezones

Jumping on a call is rather inconvenient and expensive for us on these kinds of difficult investigations. Is there a chance for you to try to create an isolated repro? Perhaps start with hammering your code under stress, then if you can repro it with some frequency, start removing code to minimize it?

**Comment by antonfirsov** [comment]
>The thread stack suggests that the origin of the exception is Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketReceiver, which derives from SocketAwaitableEventArgs, which is, according to the comments, a "slimmed down version" of the code that was touched in the PR https://github.com/dotnet/runtime/pull/84432.

@halter73 @davidfowl this is likely a Kestrel bug. I think this should be made `volatile` or adapt https://github.com/dotnet/runtime/pull/82147:

https://github.com/dotnet/aspnetcore/blob/203730e1fdc17ae8b0f704e897b523b45df949fb/src/Servers/Kestrel/Transport.Sockets/src/Internal/SocketAwaitableEventArgs.cs#L21

**Comment by tommaybe** [comment]
@karelz @antonfirsov 

I was able to pare down our grpc service to bare essentials, without Akka etc., deployed it to an ARM node and bombarded it with requests all day. The service crashed with the same exception after a few hours. I have uploaded the dump file on the dev community page.

The feedback issue is here:
https://developercommunity.visualstudio.com/t/Runtime-crashes-on-ARM-in-Kestrel-socket/10459700

**Comment by antonfirsov** [comment]
@tommaybe would it be possible for you to test a private build of `Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll`, preferably in a .NET 8.0 preview 7 setup?

**Comment by tommaybe** [comment]
> @tommaybe would it be possible for you to test a custom build of `Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll`, preferably in a .NET 8.0 preview 7 setup?

Sure, can do.

**Comment by karelz** [comment]
I don't see the dump there :|
I wonder if it will be faster to just try the private build @antonfirsov was suggesting ... if it fixes the problem, then no dumps are necessary :)

**Comment by tommaybe** [comment]
I am very much in favor of that. 👍 Let me know how to proceed.

**Comment by antonfirsov** [comment]
I also can't see the dump, and going down that rabbit hole is a scenario I really hope to avoid :)

I made a patched build of `Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll`: [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.zip](https://github.com/dotnet/runtime/files/12553731/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.zip)

@tommaybe please replace the file under `<DOTNETDIR>/shared/Microsoft.AspNetCore.App/8.0.0-preview.7.23375.9/`, run your app with .NET 8.0 preview 7 and let us know whether it eliminates the crash.

**Comment by tommaybe** [comment]
@antonfirsov Thanks for the quick turnaround on this, really appreciated!

I have deployed the real service as well as my repro with your patch, will let you know if I see further crashes or not.

**Comment by tommaybe** [comment]
Both Stresstest and Production were running the patched version friday, no crashes anymore. 👍
