### ISSUE TITLE
Got Win32Exception when I send an HTTPS request

### ISSUE THREAD

**Issue by 1dNDN** [dotnet/runtime#91464]
### Description

I get Win32Exception error (0x80090326) when I send HTTPS requests. 

### Reproduction Steps

Two lines of code are enough to reproduce

```c#
var client = new HttpClient();
var response = await client.GetAsync("https://google.com/");
```

### Expected behavior

It is expected that I will receive the contents of the page google.com in response

### Actual behavior

Actually I get the error below
```
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](Byte[] buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args)
```

### Regression?

This applies equally to httpclient, WebClient, HttpWebRequest. This applies equally to all versions .NET Core, from 2.1 to 8.0. This also applies to .NET Framework 4.8.1.
This is reproduced in both Windows 22h2 and Debian 12 located on my local network.
This is not fixed with a VPN.

This is not reproducible in the browser (using JS) and is not reproducible using Python

### Configuration

I use .NET 8.0, but its applies to all other .NETs.
I use Windows 10 22h2, but its also applies to Debian 12.
I use x64 architecture

**Comment by NCLnclNCL** [comment]
Use try catch

**Comment by 1dNDN** [comment]
> Use try catch

But I need to send to eliminate the cause of the exception, not ignore it. 
If I put the code in try catch, it won't start working properly after that

> CODE-OF-CONDUCT.md

???

**Comment by rzikm** [comment]
I am not able to reproduce the issue. Can you collect packet captures? And perhaps see if it reproduces also on non-http url?

**Comment by 1dNDN** [comment]
Using http, everything works correctly and the code is executed successfully

**Comment by 1dNDN** [comment]
I will attach packet captures a little later today, there is no time to deal with capturing https traffic right now

**Comment by karelz** [comment]
Does it happen on more than 1 machine? (perhaps something invasive messing up with your outgoing traffic)
Is it specific to your network environment?

The fact it does not work across .NET Framework and .NET Core means that it is unlikely bug in .NET as the 2 code bases are entirely different.
Also, it is rather basic behavior which was not reported by anyone so far ...

**Comment by 1dNDN** [comment]
Yes, this happens on different machines in my local network: on a debian server and on a windows desktop. 
The behavior does not change if you connect the wire from the provider directly to the machine.

All other ways to make an https request on both machines work without errors, including curl, python, chrome, postman and anything else. The error occurs only in all versions of .net.

The application built on my desktop does not work on the desktop and on the server in my local network, but the same standalone binary file is successfully launched on a server rented from the hoster.

Unfortunately, I haven't solved my Wireshark problems yet, so I'll bring the packet capture a little later.

**Comment by wfurt** [comment]
This is likely environmental, likely caused by some upstream firewall. The `0x80090326` may be confusing as you may see it when peers sends TLS alert early during handshake. If you have repro on Linux you can use `tcpdump -w` as well as it will produce same format as Wireshark. it would be helpful to get captures for working case as well. 

As experiments, you may try to lock the TLS version to TLS 1.2 and possibly try to use IP address instead of name.

**Comment by 1dNDN** [comment]
I thought it was necessary to decrypt the https content using MITM interception.
An unencrypted dump is easier to make, here it is.

Sequentially:
1. HTTPS TLS 1.3 request by domain
2. HTTPS TLS 1.2 request by domain
3. HTTP request by domain
4. HTTPS TLS 1.3 request by IP address

https://1dndn.ru/files/google.zip - here's the dump

**Comment by 1dNDN** [comment]
This is definitely not a problem of my firewall, because it was observed on two independent devices plugged directly into the network.
I might think it's my ISP blocking some data, but similar requests using other tools work fine. In addition, using a VPN does not solve the problem.

**Comment by rzikm** [comment]
> I changed the TLS version using ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
All HTTPS requests failing, HTTP request working properly

Just FYI, `ServicePointManager` settings have no effect on HttpClient in .NET Core, and there is a pending task to mark it obsolete so that such code gives compiler warnings. Can you try again by configuring the `HttpClient` directly? Something like this

```
using System.Net.Http;
using System.Security.Authentication;

var handler = new SocketsHttpHandler
{
    SslOptions = {
        EnabledSslProtocols = SslProtocols.Tls12
    }
};

using HttpClient client = new(handler);

using var response = await client.GetAsync("https://google.com");

System.Console.WriteLine(response);
```

**Comment by 1dNDN** [comment]
My mistake. Here is the correct HTTPS TLS 1.3 capture

https://1dndn.ru/files/google2.zip

**Comment by rzikm** [comment]
That's interesting, and those are Windows captures? Can you also collect the same packet captures on the other affected OS (Debian)?

**Comment by rzikm** [comment]
or rather, what is the exception message reported when running on Debian?

**Comment by wfurt** [comment]
I'm not able to access the files @1dNDN. You should be able to attache them the the issue. 
You can also check if the other working systems use 1.2 or 1.3. Linux will default to TLS 1.3 for long time, on Win Dows that started with Windows 11 & Server 2022.

**Comment by 1dNDN** [comment]
[google.zip](https://github.com/dotnet/runtime/files/12593623/google.zip)
[google2.zip](https://github.com/dotnet/runtime/files/12593625/google2.zip)
I'm sorry, I forgot about this github function

**Comment by wfurt** [comment]
sorry for the delay @1dNDN. I look at the traces and they seem perfectly normal and perhaps not even corresponding to the capture. Frame 13 is likely the GET and there is response afterwards e.g. this should pass the handshake stage. 
It feels that some security software is interfering with the flow - we have seen that in past that the packet captures did not reflect what the application is actually getting. It is going to be difficult to investigate since there is no repro and it is likely environmental. Aside from .NET sestina you can disable TLS 1.3 in registry and always fall-back to TLS 1.2.

I also included captures from my local tests - they look pretty much the same but the client is happy.
[google-tls13.pcapng.zip](https://github.com/dotnet/runtime/files/12718209/google-tls13.pcapng.zip)

**Comment by rzikm** [comment]
There has been no activity for some time. And comments above say that the workaround (Enforcing TLS 1.2) works. Otherwise there is nothing actionable for our team at the moment. I am going to close the issue now, feel free to open new issue if more actionable information becomes available.

**Comment by 1dNDN** [comment]
I tested this code on a clean Windows 10 on another PC on the same LAN, it works there.
On a problematic PC, the firewall is completely turned off. 
Workaround does not work for 3 party code.
Edge in IE mode seems to be unable to load the page either.

P.S. I checked on a pc with live linux, there is no error there

**Comment by 1dNDN** [comment]
I fixed it!
https://stackoverflow.com/questions/56072561/how-to-enable-tls-1-3-in-windows-10/59210166#59210166

But on the contrary, it was necessary to turn off
`"Enabled"=dword:00000000`

Thank you!

**Comment by wfurt** [comment]
right. This is equivalent of setting it explicitly in the code ... but it should work globally for everything using schannel. It will have no impact in code that use their own crypto & TLS.
