### ISSUE TITLE
[MT][browser] `System.Transactions.Tests.AsyncTransactionScopeTests` error: Thread failed to start

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91538]
Failing after enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536).
```
  [ERROR] FATAL UNHANDLED EXCEPTION: System.Threading.ThreadStartException: Thread failed to start.
    ---> System.ExecutionEngineException: mono_thread_platform_create_thread() failed
    --- End of inner exception stack trace ---
    at System.Threading.Thread.ThrowThreadStartException(Exception ex)
    at System.Threading.Thread.StartCore()
    at System.Threading.Thread.Start(Boolean captureContext, Boolean internalThread)
    at System.Threading.Thread.UnsafeStart()
    at System.Threading.WebWorkerEventLoop.StartExitable(Thread thread, Boolean captureContext)
    at System.Threading.PortableThreadPool.WorkerThread.CreateWorkerThread()
    at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker(PortableThreadPool threadPoolInstance)
    at System.Threading.PortableThreadPool.AdjustMaxWorkersActive()
    at System.Threading.PortableThreadPool.NotifyWorkItemProgress(Object threadLocalCompletionCountObject, Int32 currentTimeMs)
    at System.Threading.PortableThreadPool.NotifyWorkItemComplete(Object threadLocalCompletionCountObject, Int32 currentTimeMs)
    at System.Threading.ThreadPoolWorkQueue.Dispatch()
    at System.Threading.PortableThreadPool.WorkerThread.WorkLoopSemaphoreSuccess(LowLevelLifoAsyncWaitSemaphore semaphore, Object stateObject)
    at System.Threading.LowLevelLifoAsyncWaitSemaphore.InternalAsyncWaitSuccess(LowLevelLifoAsyncWaitSemaphore self, WaitEntry internalWaitEntry)
    at System.Threading.LowLevelLifoAsyncWaitSemaphore.SuccessCallback(IntPtr lifoSemaphore, IntPtr userData)
```
Test got blocked.

**Comment by pavelsavara** [comment]
Possibly we are leaking threads with external event loop (like thread pool threads)
We should make sure `emscripten_thread_cleanup` is called.

Also for `JSWebWorker` we need to make sure that the thread is not re-used.
See `PThread.returnWorkerToPool`

**Comment by ilonatommy** [comment]
`DoTxNewThread`, `RunBarrierTest8_PostPhaseException`, `InterlockedAddAndRead_Multithreaded_Int64`, `Microsoft.Extensions.DependencyInjection.Tests` are not blocked anymore.
`Shared_ParallelUsage` - trying to reproduce failure locally, so far with no success
