### ISSUE TITLE
[MT][browser] `System.Threading.Tasks.Tests.TaskContinueWhenAllTests` fails

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91548]
After enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536)
```
Assert.Null() Failure
info: Expected: (null)
info: Actual:   System.AggregateException: One or more errors occurred. (An exception was thrown by a TaskScheduler.)
info:            ---> System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
info:            ---> System.Threading.ThreadStartException: Thread failed to start.
info:            ---> System.ExecutionEngineException: mono_thread_platform_create_thread() failed
info:              --- End of inner exception stack trace ---
info:              at System.Threading.Thread.ThrowThreadStartException(Exception ex)
info:              at System.Threading.Thread.StartCore()
info:              at System.Threading.Thread.Start(Object parameter, Boolean captureContext, Boolean internalThread)
info:              at System.Threading.Thread.UnsafeStart(Object parameter)
info:              at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
info:              at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
info:              at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
info:              --- End of inner exception stack trace ---
info:              at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
info:              at System.Threading.Tasks.ContinueWithTaskContinuation.Run(Task completedTask, Boolean canInlineContinuationTask)
info:              --- End of inner exception stack trace ---
info:              at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
info:              at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
info:              at System.Threading.Tasks.Task.Wait()
info:              at System.Threading.Tasks.Tests.TaskContinueWhenAllTests.TestContinueWhenAll_TaskContinuationOptions()
```

**Comment by pavelsavara** [comment]
maybe this was "resolved" by https://github.com/dotnet/runtime/pull/94204

**Comment by ilonatommy** [comment]
Same as https://github.com/dotnet/runtime/issues/91549, no tests blocked by this issue. The whole lib is blocked by https://github.com/dotnet/runtime/issues/91538 and it hangs with no exception thrown.
