### ISSUE TITLE
[MT][browser] `System.Threading.Timer` timeout

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91545]
After enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536) they hover and do not finish execution. Either no error is displayed or a following one:
```
Assert.True() Failure
Expected: True
   at System.Threading.Tests.TimerFiringTests.Timer_Fires_After_DueTime_Ellapses()
    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
Tests got blocked.

**Comment by pavelsavara** [comment]
maybe this was resolved by https://github.com/dotnet/runtime/pull/94180, please try again

**Comment by ilonatommy** [comment]
Yes, it was, and is not blocked by active issue anymore, can be closed.
