### ISSUE TITLE
[MT][browser] `System.Threading.Tasks.Tests.TaskPropertiesTests.TaskOptionsTestAsync` fails

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91549]
After enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536)
```
 System.Threading.Tasks.TaskSchedulerException : An exception was thrown by a TaskScheduler.
info: ---- System.Threading.ThreadStartException : Thread failed to start.
info: -------- System.ExecutionEngineException : mono_thread_platform_create_thread() failed
info:    at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
info:    at System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
info:    at System.Threading.Tasks.Task.Start()
info:    at System.Threading.Tasks.Tests.TaskPropertiesTests.TaskOptionTest(Boolean runSync)
info:    at System.Threading.Tasks.Tests.TaskPropertiesTests.TaskOptionsTestAsync()
info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
info:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
info: ----- Inner Stack Trace -----
info:    at System.Threading.Thread.ThrowThreadStartException(Exception ex)
info:    at System.Threading.Thread.StartCore()
info:    at System.Threading.Thread.Start(Object parameter, Boolean captureContext, Boolean internalThread)
info:    at System.Threading.Thread.UnsafeStart(Object parameter)
info:    at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
info:    at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
info:    at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
info: ----- Inner Stack Trace -----
```

**Comment by pavelsavara** [comment]
maybe this was "resolved" by https://github.com/dotnet/runtime/pull/94204, please try again
