### ISSUE TITLE
[MT][browser] `System.Transactions`, `System.Threading` timeouts

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91541]
After enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536) they hover and do not finish execution. No error displayed.

Tests got blocked.

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97270-merge-5bdfde9a9c95496c8f/WasmTestOnBrowser-System.Transactions.Local.Tests/1/console.dd7ed842.log?helixlogtype=result)
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534976&view=logs&jobId=58dc7ccb-0414-5dd3-62a5-bf2e63258b7c&j=63c2d0c8-fec2-5788-81c8-f3ac95e8841f&t=744baa8c-2e26-50b3-27ca-51a0d84eca60)
```
[18:06:57] info: [2024-01-21T18:06:57.237Z] [FAIL] System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync
[18:06:57] info: Assert.Null() Failure: Value is not null
[18:06:57] info: Expected: null
[18:06:57] info: Actual:   CommittableTransaction { IsolationLevel = Serializable, PromoterType = 00000000-0000-0000-0000-000000000000, TransactionInformation = TransactionInformation { CreationTime = 2024-01-21T18:06:56.2100000, DistributedIdentifier = 00000000-0000-0000-0000-000000000000, LocalIdentifier = "6740f5f6-68bb-4440-a264-7d2e8a182b5e:270", Status = Committed } }
[18:06:57] info:    at System.Transactions.Tests.AsyncTransactionScopeTests.AssertTransactionNull()
[18:06:57] info:    at System.Transactions.Tests.AsyncTransactionScopeTests.<>c__DisplayClass18_0.<VerifyBYOTSyncTSNestedAsync>b__0()
[18:06:57] info:    at System.Threading.Tasks.Task.InnerInvoke()
[18:06:57] info:    at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
[18:06:57] info:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[18:06:57] info: --- End of stack trace from previous location ---
[18:06:57] info:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[18:06:57] info:    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[18:06:57] info: --- End of stack trace from previous location ---
[18:06:57] info:    at System.Transactions.Tests.AsyncTransactionScopeTests.VerifyBYOTSyncTSNestedAsync()
[18:06:57] info: --- End of stack trace from previous location ---
```
