### ISSUE TITLE
Test failure profiler/gc/gcbasic/gcbasic.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#91568]
**Failed in:** [runtime-coreclr crossgen2 20230903.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=394564&view=ms.vss-test-web.build-test-results-tab&runId=8501448&resultId=100201&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx x64 Checked @ OSX.1200.Amd64.Open
    - profiler/gc/gcbasic/gcbasic.sh
```

**Error message:**
```
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/gcbasic.sh: line 321: -r:/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/*.dll: No such file or directory
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/gcbasic.sh: line 260: 58020 Trace/BPT trap: 5       (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/B25E094C/w/B89A09ED/uploads/Reports/profiler.gc/gcbasic/gcbasic.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
03:26:05
Response file: /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/Microsoft.Diagnostics.NETCore.Client.dll
-r:/tmp/helix/working/B25E094C/p/System.*.dll
-r:/tmp/helix/working/B25E094C/p/Microsoft.*.dll
-r:/tmp/helix/working/B25E094C/p/xunit.*.dll
-r:/tmp/helix/working/B25E094C/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--hot-cold-splitting
--targetarch:x64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B25E094C/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/Microsoft.Diagnostics.NETCore.Client.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/Microsoft.Diagnostics.NETCore.Client.dll
Running R2RDump:  dotnet /tmp/helix/working/B25E094C/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/Microsoft.Diagnostics.NETCore.Client.dll --out /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/Microsoft.Diagnostics.NETCore.Client.dll.r2rdump --val
03:26:08
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/TestLibrary.dll
03:26:08
Response file: /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/TestLibrary.dll.rsp
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/TestLibrary.dll
-o:/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/TestLibrary.dll
-r:/tmp/helix/working/B25E094C/p/System.*.dll
-r:/tmp/helix/working/B25E094C/p/Microsoft.*.dll
-r:/tmp/helix/working/B25E094C/p/xunit.*.dll
-r:/tmp/helix/working/B25E094C/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--hot-cold-splitting
--targetarch:x64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B25E094C/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/TestLibrary.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/TestLibrary.dll
Running R2RDump:  dotnet /tmp/helix/working/B25E094C/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/TestLibrary.dll --out /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/TestLibrary.dll.r2rdump --val
03:26:10
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/common.dll
03:26:10
Response file: /private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/common.dll.rsp
/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/IL-CG2/common.dll
-o:/private/tmp/helix/working/B25E094C/w/B89A09ED/e/profiler/gc/gcbasic/common.dll
-r:/tmp/helix/working/B25E094C/p/System.*.dll
-r:/tmp/helix/working/B25E094C/p/Microsoft.*.dll
-r:/tmp/helix/working/B25E094C/p/xunit.*.dll
-r:/tmp/helix/working/B25E094C/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--hot-cold-splitting
--targetarch:x64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B25E094C/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B25E0
```

**Stack trace:**
```
   at profiler_gc._gcbasic_gcbasic_._gcbasic_gcbasic_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
2023-09-04T07:25:50.12Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | profiler/gc/gcbasic/gcbasic.sh | Failed | {"BuildId":"394564","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","Project":"public","architecture":"x64","System.StageName":"Build","System.PhaseAttempt":"1","Reason":"Schedule","BuildNumber":"20230903.1","System.StageAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","DefinitionName":"runtime-coreclr crossgen2","AzurePipelinesTestRunId":"8501448","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"124","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked"} | Schedule
</details>

**Comment by mangod9** [comment]
@cshung are we running crossgen2 tests with hot-cold splitting enabled? Failure only occurs on macOS x64.

**Comment by amanasifkhalid** [comment]
@mangod9 yes, this test has hot/cold splitting enabled (by the `--hot-cold-splitting` flag passed to Crossgen from the .rsp file). I added a hot/cold splitting job to `runtime-coreclr crossgen2` in #91217.

**Comment by ivdiazsa** [comment]
Closing since no appearances have been recorded recently.
