### ISSUE TITLE
[MT][browser] `customAttributeCount` fails

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91597]
Failing after enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536).
```
 [FAIL] System.Tests.GetCustomAttribute.customAttributeCount
 Assert.Equal() Failure
 Expected: 5
 Actual:   3
   at System.Tests.GetCustomAttribute.customAttributeCount()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by ilonatommy** [comment]
It's not blocked, passing, closing.
