### ISSUE TITLE
[MT][browser] ` Wasm.Browser.Config.Sample`, `Wasm.Browser.Config.Sample` fail

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91676]
Failing after enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536).

Wasm.Browser.Config.Sample:
```
Single asset for js-module-threads not found Error: Assert failed: Single asset for js-module-threads not found
    at Je (globals.ts:141:19)
    at assets.ts:126:5
WASM EXIT 1
```

Minimal config needs 2 versions: for MT and for ST, MT adding:
```
    {
        name: "dotnet.native.worker.js",
        behavior: "js-module-threads"
    },
```

Then, we're getting `setRuntimeGlobals is not a function`, probably because config is not loaded properly - "demo imports / promises" are embedded in the minimal config and are not getting resolved. We would need a callback to main.js on the worker to fulfill them.

**Comment by ilonatommy** [comment]
It got fixed with the pinned PR, closing.
