### ISSUE TITLE
[MT][browser] `Http.Tests` fails with `Operation is not supported on this platform`

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#91673]
Failing after enabling all MT library tests (https://github.com/dotnet/runtime/pull/91536).
```
[FAIL] Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensionsTest.AddHttpClient_ConfigurePrimaryHttpMessageHandler_ApplyChangesPrimaryHandler
info: System.PlatformNotSupportedException : Operation is not supported on this platform.
info:    at System.Net.Http.BrowserHttpHandler.set_Credentials(ICredentials value)
info:    at System.Net.Http.HttpClientHandler.set_Credentials(ICredentials value)
info:    at Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensionsTest.<>c__DisplayClass49_0.<AddHttpClient_ConfigurePrimaryHttpMessageHandler_ApplyChangesPrimaryHandler>b__0(HttpMessageHandler primaryHandler, IServiceProvider _)
info:    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass8_0.<ConfigurePrimaryHttpMessageHandler>b__1(HttpMessageHandlerBuilder b)
info:    at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
info:    at Microsoft.Extensions.Http.MetricsFactoryHttpMessageHandlerFilter.<>c__DisplayClass2_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
info:    at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass6_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
info:    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
info:    at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__2()
info:    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ViaFactory(LazyThreadSafetyMode mode)
info:    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
info:    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].CreateValue()
info:    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].get_Value()
info:    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
info:    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
info:    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TestTypedClient](IServiceProvider s, IHttpClientBuilder builder)
info:    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass13_0`1[[Microsoft.Extensions.Http.TestTypedClient, Microsoft.Extensions.Http.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].<AddTypedClientCore>b__0(IServiceProvider s)
info:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
info:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
info:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
info:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
info:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
info:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
info:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
info:    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
info:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
info:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[TestTypedClient](IServiceProvider provider)
info:    at Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensionsTest.AddHttpClient_ConfigurePrimaryHttpMessageHandler_ApplyChangesPrimaryHandler()
info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
info:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by pavelsavara** [comment]
`BrowserHttpHandler.set_Credentials` is really not supported on a browser. This is not related to MT, probably only uncovered there.

Please add
`[SkipOnPlatform(TestPlatforms.Browser, "Credentials is not supported on Browser")]` and all tests which have this on stack trace instead of this ActiveIssue.

There are also other APIs which browser doesn't support. You can find them by searching for other 
`[SkipOnPlatform(TestPlatforms.Browser, `

**Comment by ilonatommy** [comment]
> Please add `[SkipOnPlatform(TestPlatforms.Browser, "Credentials is not supported on Browser")]` and all tests which have this on stack trace instead of this ActiveIssue.

This was done in https://github.com/dotnet/runtime/pull/94204, no more active issues for this issue is left. All the other tests from `Microsoft.Extensions.Http.Tests` pass when run on repeat with MT.

Closing.
