### ISSUE TITLE
[wasm][debugger] Timeout waiting for CheckInspectLocalsAtBreakpointSite 

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#91773]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=398924
Build error leg or test failing: chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/91759

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "CheckInspectLocalsAtBreakpointSite",
  "ErrorPattern": "DebuggerTests.GetPropertiesTests.InspectTypeInheritedMembers.*System.Threading.Tasks.TaskCanceledException",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation: :warning:** Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build: :mag_right:**" line.
**Validation performed at:** 9/20/2023 4:46:55 PM UTC

```
"type_name": "Base_PropertyForOverridingWithProperty",\n  "value": {\n    "__custom_type": "datetime",\n    "binary": 637296086430000000\n  }\n}, True), ["BaseBase_PropertyForVHO"] = ({\n  "__custom_type": "getter",\n  "type_name": "BaseBase_PropertyForVHO",\n  "value": {\n    "type": "string",\n    "value": "Derived#BaseBase_PropertyForVHO"\n  }\n}, True), ["BaseBase_PropertyForVOH"] = ({\n  "__custom_type": "getter",\n  "type_name": "BaseBase_PropertyForVOH",\n  "value": {\n    "type": "string",\n    "value": "Derived#BaseBase_PropertyForVOH"\n  }\n}, True), ["BaseBase_AutoPropertyForVHO"] = ({\n  "type": "string",\n  "value": "Derived#BaseBase_AutoPropertyForVHO"\n}, True), ...], is_async: False) [FAIL]
  Failed DebuggerTests.GetPropertiesTests.InspectTypeInheritedMembers(type_name: "DerivedClass2", own_properties: False, accessors_only: False, expected_names: ["BaseBase_PropertyForHidingWithField", "Base_PropertyForOverridingWithProperty", "BaseBase_PropertyForVHO", "BaseBase_PropertyForVOH", "BaseBase_AutoPropertyForVHO", ...], all_props: [["BaseBase_PropertyForHidingWithField"] = ({
  "type": "number",
  "value": "210",
  "description": "210"
}, True), ["Base_PropertyForOverridingWithProperty"] = ({
  "__custom_type": "getter",
  "type_name": "Base_PropertyForOverridingWithProperty",
  "value": {
    "__custom_type": "datetime",
    "binary": 637296086430000000
  }
}, True), ["BaseBase_PropertyForVHO"] = ({
  "__custom_type": "getter",
  "type_name": "BaseBase_PropertyForVHO",
  "value": {
    "type": "string",
    "value": "Derived#BaseBase_PropertyForVHO"
  }
}, True), ["BaseBase_PropertyForVOH"] = ({
  "__custom_type": "getter",
  "type_name": "BaseBase_PropertyForVOH",
  "value": {
    "type": "string",
    "value": "Derived#BaseBase_PropertyForVOH"
  }
}, True), ["BaseBase_AutoPropertyForVHO"] = ({
  "type": "string",
  "value": "Derived#BaseBase_AutoPropertyForVHO"
}, True), ...], is_async: False) [49 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 60.6492803)
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.WaitFor(String what) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 277
   at DebuggerTests.DebuggerTestBase.CheckInspectLocalsAtBreakpointSite(String type, String method, Int32 line_offset, String bp_function_name, String eval_expression, Func`2 locals_fn, Func`2 wait_for_event_fn, Boolean use_cfo, String assembly, Int32 col) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 365
   at DebuggerTests.GetPropertiesTests.InspectTypeInheritedMembersInternal(String type_name, Nullable`1 own_properties, Nullable`1 accessors_only, String[] expected_names, Dictionary`2 all_props, Boolean is_async, AutoEvaluate auto_evaluate_status) in /_/src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs:line 647
   at DebuggerTests.GetPropertiesTests.InspectTypeInheritedMembers(String type_name, Nullable`1 own_properties, Nullable`1 accessors_only, String[] expected_names, Dictionary`2 all_props, Boolean is_async) in /_/src/mono/wasm/debugger/DebuggerTestSuite/GetPropertiesTests.cs:line 265
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment]
Removed `known build error` because the error string to match was too generic, and ended up matching unrelated tests.
