### ISSUE TITLE
claim loop when adding a claim to an identity

### ISSUE THREAD

**Issue by dhduvall** [dotnet/runtime#91814]
### Description

I'm seeing a self-referential loop in a `ClaimsIdentity` via the `Subject` of the `Claim` objects in `Claims` when adding a `Claim` to the identity via `AddClaim()`.

Serilog just gives up after a few levels, Newtonsoft's JSON serializer crashes, and the validation code I'm using doesn't seem to have an issue.

Perhaps this is a misuse of the interfaces (please correct me if that's the case!), but even so, this probably shouldn't happen.

I have a small repo to demonstrate the issue.

### Reproduction Steps

git clone https://github.com/dhduvall/dotnet-copyclaims
cd dotnet-copyclaims
dotnet run

### Expected behavior

There should be no loop—Serilog output shouldn't be large, and Newtonsoft's JSON serialization shouldn't crash.

### Actual behavior

```
{"Timestamp":"2023-09-08T12:30:33.9829680-07:00","Level":"Information","MessageTemplate":"Added claim \"iat\"","Properties":{"Claim":{"Issuer":"LOCAL AUTHORITY","OriginalIssuer":"LOCAL AUTHORITY","Properties":{},"Subject":null,"Type":"iat","Value":"1516239022","ValueType":"http://www.w3.org/2001/XMLSchema#integer","_typeTag":"Claim"}}}
{"Timestamp":"2023-09-08T12:30:34.0057350-07:00","Level":"Information","MessageTemplate":"Populated identity with claims","Properties":{"Identity":{"AuthenticationType":null,"IsAuthenticated":false,"Actor":null,"BootstrapContext":null,"Claims":[{"Issuer":"LOCAL AUTHORITY","OriginalIssuer":"LOCAL AUTHORITY","Properties":{},"Subject":{"AuthenticationType":null,"IsAuthenticated":false,"Actor":null,"BootstrapContext":null,"Claims":[{"Issuer":"LOCAL AUTHORITY","OriginalIssuer":"LOCAL AUTHORITY","Properties":{},"Subject":{"AuthenticationType":null,"IsAuthenticated":false,"Actor":null,"BootstrapContext":null,"Claims":[{"Issuer":"LOCAL AUTHORITY","OriginalIssuer":"LOCAL AUTHORITY","Properties":{},"Subject":{"AuthenticationType":null,"IsAuthenticated":null,"Actor":null,"BootstrapContext":null,"Claims":null,"Label":null,"Name":null,"NameClaimType":null,"RoleClaimType":null,"_typeTag":"ClaimsIdentity"},"Type":"iat","Value":"1516239022","ValueType":"http://www.w3.org/2001/XMLSchema#integer","_typeTag":"Claim"}],"Label":null,"Name":null,"NameClaimType":"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name","RoleClaimType":"http://schemas.microsoft.com/ws/2008/06/identity/claims/role","_typeTag":"ClaimsIdentity"},"Type":"iat","Value":"1516239022","ValueType":"http://www.w3.org/2001/XMLSchema#integer","_typeTag":"Claim"}],"Label":null,"Name":null,"NameClaimType":"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name","RoleClaimType":"http://schemas.microsoft.com/ws/2008/06/identity/claims/role","_typeTag":"ClaimsIdentity"},"Type":"iat","Value":"1516239022","ValueType":"http://www.w3.org/2001/XMLSchema#integer","_typeTag":"Claim"}],"Label":null,"Name":null,"NameClaimType":"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name","RoleClaimType":"http://schemas.microsoft.com/ws/2008/06/identity/claims/role","_typeTag":"ClaimsIdentity"}}}
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Subject' with type 'System.Security.Claims.ClaimsIdentity'. Path 'Claims[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Program.<Main>$(String[] args) in /Users/duvall/coros/copyclaims/Program.cs:line 41
```

**Comment by gregsdennis** [comment]
I think this is mis-tagged.

**Comment by dhduvall** [comment]
> From a JSON perspective you could use `PreserveReferencesHandling.All` to avoid the loop, but please observe that this completely transforms the payload as it adds new semantics to the payload, similar to what we describe on S.T.Json [ReferenceHandler.Preserve](https://learn.microsoft.com/dotnet/api/system.text.json.serialization.referencehandler.preserve).
> 
> You may want to take a look at `ReferenceLoopHandling = ReferenceLoopHandling.Ignore` too but using it will cause your payload to suffer data-loss.

Thanks for the pointers. I really was only serializing this as part of my debugging, and when I found the loop, I thought perhaps it was the result of something I'd done wrong and was causing my overall project to fail. It wasn't, though, and I don't really need this anymore, but it'll be good to have these in my back pocket for next time.

> From a security perspective I don't know if there may be something you can do to keep the essence of your ClaimsIdentity while avoiding the reference loop. cc @bartonjs @vcsjones.
> 
> @dhduvall why do you think there should be no loop?

I don't think a lot of code is really ready to deal with loops. Newtonsoft crashes by default, and while you can configure it to be safer, it's entirely different than how you configure `System.Text.Json`. Serilog didn't crash, but its "recurse a couple levels and then give up" behavior isn't especially useful except for preventing a crash. Who knows how much other code out there isn't expecting a loop at all (unlike a serializer).

It also looks like the `AddClaim()` code is trying to avoid a loop. I'm not sure why it's not successful, or perhaps I'm wrong about what it's trying to do. See, for instance, https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Claims/src/System/Security/Claims/ClaimsIdentity.cs#L413-L425
