### ISSUE TITLE
IOException inside HostBuilder

### ISSUE THREAD

**Issue by chrfin** [dotnet/runtime#91879]
### Description

We use `Host.CreateDefaultBuilder(args).RunConsoleAsync()` to create a host and are hosting some custom services with that host.

### Reproduction Steps

Sadly we cannot reproduce the problem deliberately, but it happens a few times per week...

### Expected behavior

We would like the program to start successfully.

### Actual behavior

From time to time this program crashes directly at startup with the following exception:
```
Unhandled exception. System.IO.IOException: Invalid argument : '/proc/1889/task/1889/net'
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, CancellationToken cancellationToken)
```

### Known Workarounds

We have the feeling that it is somehow related to the ethernet configuration of our device as it seems to be not happening if we disconnect the ethernet cable.

### Configuration

The program is running with .NET 6.0 on an embedded ARM64 based system running a custom Linux build based on kernel 5.4.

**Comment by Jozkee** [comment]
I'm also curious about the path of your config.json (part of the repro). I don't understand why the FSW should be iterating over `/proc`.

**Comment by chrfin** [comment]
We do not have any config.json file at all. And args contians only "-w" (we use that some other place).

**Comment by inigoOCF** [comment]
Same behaviour. We have been working for a week with our application installed on about 8 computers and today 3 of them have launched the exception and start up:

```
sep 14 09:02:17   Unhandled exception. System.IO.IOException: Invalid argument : '/proc/1881/task/1881/net'
sep 14 09:02:17      at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName)
sep 14 09:02:17      at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken)
sep 14 09:02:17      at System.IO.FileSystemWatcher.StartRaisingEvents()
sep 14 09:02:17      at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
sep 14 09:02:17      at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
sep 14 09:02:17      at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
sep 14 09:02:17      at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
sep 14 09:02:17      at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
sep 14 09:02:17      at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
sep 14 09:02:17      at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
sep 14 09:02:17      at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
sep 14 09:02:17      at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
sep 14 09:02:17      at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
sep 14 09:02:17      at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder()
```
- Restarting the service or rebooting the pc still fails.
- Running the app directly via console works correctly.
- Reinstalling the app works correctly again.

startup-logic:
```
                IConfiguration configuration = new ConfigurationManager();
                configuration["AllowedHosts"] = "*";
                configuration["Kestrel:EndpointDefaults:Protocols"] = "Http2";
                configuration["Logging:LogLevel:Default"] = "Information";
                configuration["Logging:LogLevel:Microsoft.AspNetCore"] = "Warning";

                var serverUrl = $"http://localhost:{port}";

                var builder = WebApplication.CreateBuilder();
                builder.Configuration.AddConfiguration(configuration);
                builder.Services.AddGrpc();
                builder.Services.AddSingleton<IServiceGrpcServer>(this);
                _webApplication = builder.Build();
                _webApplication.MapGrpcService<ServiceGrpcServer>();
                _webApplication.RunAsync(serverUrl);
```

**Comment by chrfin** [comment]
@Jozkee Any chance for a feasible work-around or to get a fix into .NET 8.0 (as 8 is LTS and 9 will not)?

**Comment by Jozkee** [comment]
As a workaround, can you try setting env. var. `DOTNET_USE_POLLING_FILE_WATCHER=1`? Since this is an issue with how the FileSystemWatcher traverses the directory, is possible that the polling doesn't incur in enumerating /proc subdirectories.

Could you please share in which directory your app is on disk? I'm wondering if it's on `/` and that's why `/proc` is being enumerated for watching.

**Comment by chrfin** [comment]
@Jozkee Our app is at `/usr/USER/APP/app`. It is started with a specific user, maybe that changes the working dir?

**Comment by sancheolz** [comment]
/proc is filesystem for process states. in /proc/{id} the id is process id. For me state of process with id mentioned in /proc was zombie. So to reproduce issue you need to put some process to zombie state, and than start your service with hostbuilder.

**Comment by svick** [comment]
This should be mitigated by https://github.com/dotnet/runtime/pull/128072: we shouldn't be trying to watch `/proc` in an application launched from `/` . If you intentionally try to watch `/proc`, I assume you will still encounter this exception, so I'm going to keep this issue open in case we want to better support that edge case and transfer this issue to `System.IO`.

If you think watching `/proc` is not worth supporting, feel free to close this issue.

**Comment by adamsitnik** [comment]
> This should be mitigated by [#128072](https://github.com/dotnet/runtime/pull/128072)

Closing as fixed.
