### ISSUE TITLE
Test falilure GC/Features/SustainedLowLatency/scenario/scenario.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#92036]
**Failed in:** [runtime-coreclr jitstress-isas-x86 20230913.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=404847&view=ms.vss-test-web.build-test-results-tab&runId=8780904&resultId=117789&paneView=debug)

**Failed tests:**
```
coreclr osx x64 Checked jitstress_isas_2_x86_noavx @ OSX.1200.Amd64.Open
    - GC/Features/SustainedLowLatency/scenario/scenario.sh
```

**Error message:**
```
[createdump] Invalid process id: task_for_pid(87528) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0
/private/tmp/helix/working/B756094C/w/A7A6091B/e/GC/Features/SustainedLowLatency/scenario/scenario.sh: line 499: 87528 Segmentation fault: 11  (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/B756094C/w/A7A6091B/uploads/Reports/GC.Features/SustainedLowLatency/scenario/scenario.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B756094C/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true scenario.dll ''
[createdump] Target process is alive
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 9/13/2023 12:38:13 PM
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/tmp/helix/working/B756094C/p
> /private/tmp/helix/working/B756094C/w/A7A6091B/e/GC/Features/SustainedLowLatency/scenario/scenario.sh
Expected: True
Actual:   False
```

**Stack trace:**
```
   at GC_Features._SustainedLowLatency_scenario_scenario_._SustainedLowLatency_scenario_scenario_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
a single failure so closing for now
