### ISSUE TITLE
8.0.100-rc.1.23455.8 run dotnet run will crash

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#92050]
### Description

![image](https://github.com/dotnet/runtime/assets/26201412/85594cbe-5fd2-4655-9e74-a3f55725a677)

### Reproduction Steps

Use `dotnet run`

### Expected behavior

Compiled and run

### Actual behavior

Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.Serialization.SerializationGuard.<ThrowIfDeserializationInProgress>g__ThrowIfDeserializationInProgress|0_0(System.Runtime.Serialization.SerializationInfo, System.String, Int32 ByRef)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.ProcessStartInfoExtensions.ExecuteAndCaptureOutput(System.Diagnostics.ProcessStartInfo, System.String ByRef, System.String ByRef)
   at Microsoft.DotNet.Cli.Telemetry.MacAddressGetter.GetShellOutMacAddressOutput()
   at Microsoft.DotNet.Cli.Telemetry.MacAddressGetter.GetMacAddress()
   at Microsoft.DotNet.Cli.Telemetry.TelemetryCommonProperties.GetMachineId()
   at Microsoft.DotNet.Configurer.UserLevelCacheWriter.RunWithCacheInFilePath(System.String, System.Func`1<System.String>)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryCommonProperties.GetTelemetryCommonProperties()
   at Microsoft.DotNet.Cli.Telemetry.Telemetry.InitializeTelemetry()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

### Configuration

`dotnet --info`

```txt
.NET SDK:
 Version:   8.0.100-rc.1.23455.8
 Commit:    e14caf947f

 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23455.8\

.NET workloads installed:

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64

.NET SDKs installed:
  7.0.202 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by huoyaoyuan** [comment]
I see `Process.Start` in the call stack. Is this #92046 ?

**Comment by Coloryr** [comment]
I think yes, when test in shell, is same error code.

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/issues/92007

**Comment by jkotas** [comment]
Thank you for reporting this issue. This was fixed by https://github.com/dotnet/runtime/pull/90826. The fix is included in .NET 8 RC2.

**Comment by jonnyruffles** [comment]
> Thank you for reporting this issue. This was fixed by #90826. The fix is included in .NET 8 RC2.

Hey, I'm just wondering if this could be backported to RC1?

**Comment by huoyaoyuan** [comment]
> Hey, I'm just wondering if this could be backported to RC1?

After shipped, a version will be frozen snapshot. Any change will only appear in next preview or patch.

**Comment by jkotas** [comment]
In you need the fix before RC2 is officially released, you can install the daily runtime build from https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#daily-builds-table
