### ISSUE TITLE
[mono][ios] Tests failing 'JIT_SIMD' on ios/tvos devices

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#92129]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=407596

Affected pipelines:
- `runtime-extra-platforms`
- `runtime-ioslike`

Build error leg or test failing: 
- `JIT_SIMD.WorkItemExecution`

Pull request: https://github.com/dotnet/runtime/pull/92114

Crash log: 
```
[13:45:58.0912870] Launched application 'net.dot.JIT_SIMD' on 'DNCENGTVOS-110' with pid 97714
[13:45:58.2608060] 2023-09-14 10:45:58.346 JIT_SIMD[97714:37277054] System.DllNotFoundException: Vector3TestNative
[13:45:58.2608500]    at PInvokeTest.test()
[13:45:58.2608570]    at Test_Vector3Interop.TestEntryPoint()
[13:45:58.2608630]    at __GeneratedMainWrapper.Main()
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "net\\.dot\\.JIT_SIMD.*Test failed",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by jkotas** [comment]
Tests are still disabled with ActiveIssue.

Fix or delete the test, or disable the test as by-design without ActiveIssue.
