### ISSUE TITLE
Test failure Interop\\COM\\ComWrappers\\API\\ComWrappersTests\\ComWrappersTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#92200]
**Failed in:** [runtime-coreclr gcstress0x3-gcstress0xc 20230916.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=408768&view=ms.vss-test-web.build-test-results-tab&runId=8880562&resultId=101895&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open
    - Interop\\COM\\ComWrappers\\API\\ComWrappersTests\\ComWrappersTests.cmd
```

**Error message:**
```
 Assert failure(PID 5372 [0x000014fc], Thread: 3088 [0x0c10]): CONTRACT VIOLATION by ThreadBaseExceptionFilter_Worker at "D:\a\_work\1\s\src\coreclr\vm\excep.cpp" @ 5540

THROWS called in a NOTHROW region.

                        CONTRACT in ThreadBaseExceptionFilter_Worker at "D:\a\_work\1\s\src\coreclr\vm\excep.cpp" @ 5540
VIOLATED-->  CONTRACT in ComWrappersNative::OnFullGCStarted at "D:\a\_work\1\s\src\coreclr\vm\interoplibinterface_comwrappers.cpp" @ 2020
                        CONTRACT in Interop::OnGCStarted at "D:\a\_work\1\s\src\coreclr\vm\interoplibinterface_shared.cpp" @ 80
                        CONTRACT in GCToEEInterface::GcStartWork at "D:\a\_work\1\s\src\coreclr\vm\gcenv.ee.cpp" @ 313
                        GCX_COOP in Thread::PerformPreemptiveGC at "D:\a\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 2339
                        CONTRACT in Thread::PerformPreemptiveGC at "D:\a\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 2303
                        CONTRACT in Thread::RareEnablePreemptiveGC at "D:\a\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 2364
                        CONTRACT in ManagedThreadBase_DispatchInner at "D:\a\_work\1\s\src\coreclr\vm\threads.cpp" @ 7219
                        CONTRACT in ManagedThreadBase_NoADTransition at "D:\a\_work\1\s\src\coreclr\vm\threads.cpp" @ 7484



CORECLR! CONTRACT_ASSERT + 0x2E4 (0x6fc02896)
CORECLR! ClrDebugState::CheckOkayToThrow + 0x23 (0x6fc03e84)
CORECLR! BaseContract::DoChecks + 0x122 (0x6fc080d4)
CORECLR! EEContract::DoChecks + 0x4B (0x6fe8c4b1)
CORECLR! ThreadBaseExceptionFilter_Worker + 0x7C (0x6fce9e43)
CORECLR! ThreadBaseExceptionAppDomainFilter + 0x10 (0x6fce9db7)
CORECLR! ThreadBaseRedirectingFilter + 0x14 (0x6fdf4ee9)
CORECLR! `ManagedThreadBase_DispatchOuter'::`8'::__Body::Run + 0x75 (0x6fdf234b)
CORECLR! EH4_CallFilterFunc + 0x12 (0x70250402)
CORECLR! except_handler4 + 0xD4 (0x7024c364)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 5540
    Image: C:\h\w\A1E808C9\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A1E808C9\w\A53108F6\uploads\Reports\Interop.COM\ComWrappers\API\ComWrappersTests\ComWrappersTests.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A1E808C9\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ComWrappersTests.dll 
Running ValidateComInterfaceCreation...
Running ValidateComInterfaceCreationRoundTrip...
Running ValidateComInterfaceUnwrapWrapperSpecific...
Running ValidateComObjectExtendsManagedLifetime...
Running ValidateCreatingAComInterfaceForObjectAfterTheFirstIsFree...
Running ValidateResurrection...
Running ValidateFallbackQueryInterface...
Running ValidateCreateObjectCachingScenario...
Running ValidateCreateObjectWeakHandleCacheCleanUp...
Running ValidateMappingAPIs...
Running ValidateWrappersInstanceIsolation...
Running ValidatePrecreatedExternalWrapper...
Running ValidateExternalWrapperCacheCleanUp...
Running ValidateSuppliedInnerNotAggregation...
Running ValidateIUnknownImpls...
Running ValidateBadComWrapperImpl...
Running ValidateRuntimeTrackerScenario...
Running ValidateQueryInterfaceAfterManagedObjectCollected...
Running ValidateAggregationWithComObject...
Running ValidateAggregationWithReferenceTrackerObject...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 9/16/2023 2:57:34 PM
Processing C:\cores\corerun.exe.5372.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\A1E808C9\t\tmpr0muyx.tmp" -z "C:\cores\corerun.exe.5372.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.5372.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Pa
```

**Stack trace:**
```
   at Interop_COM._ComWrappers_API_ComWrappersTests_ComWrappersTests_._ComWrappers_API_ComWrappersTests_ComWrappersTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by AaronRobinsonMSFT** [comment]
Unable to reproduce this issue now. Ran several iterations using the following environments.

```
DOTNET_GCStress=0x3
DOTNET_TieredCompilation=0
```

and

```
DOTNET_GCStress=0xC
DOTNET_TieredCompilation=0
```
