### ISSUE TITLE
Test failure Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#92202]
**Failed in:** [runtime-coreclr jitstress-random 20230917.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409203&view=ms.vss-test-web.build-test-results-tab&runId=8894348&resultId=116613&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked jitstress_random_2 @ Windows.10.Amd64.Open
    - Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd
```

**Error message:**
```

Return code:      1
Raw output file:      C:\h\w\AF9F091C\w\AE880999\uploads\Reports\Interop.COM\Dynamic\Dynamic\Dynamic.output.txt
Raw output:
BEGIN EXECUTION
Copying 'C:\h\w\AF9F091C\p\CoreShim.dll'...
        1 file(s) copied.
 "C:\h\w\AF9F091C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Dynamic.dll 
Running BasicTest
Test Failure: System.NotSupportedException: Specified method is not supported.
   at System.Runtime.InteropServices.Variant.GetAccessor(VarEnum varType) in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/Variant.Extended.cs:line 244
   at Microsoft.CSharp.RuntimeBinder.ComInterop.VariantBuilder.InitializeArgumentVariant(MemberExpression variant, Expression parameter) in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/VariantBuilder.cs:line 80
   at Microsoft.CSharp.RuntimeBinder.ComInterop.ComInvokeBinder.GenerateTryBlock() in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/ComInvokeBinder.cs:line 245
   at Microsoft.CSharp.RuntimeBinder.ComInterop.ComInvokeBinder.MakeIDispatchInvokeTarget() in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/ComInvokeBinder.cs:line 508
   at Microsoft.CSharp.RuntimeBinder.ComInterop.ComInvokeBinder.Invoke() in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/ComInvokeBinder.cs:line 157
   at Microsoft.CSharp.RuntimeBinder.ComInterop.IDispatchMetaObject.TryPropertyPut(SetMemberBinder binder, DynamicMetaObject value) in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/IDispatchMetaObject.cs:line 219
   at Microsoft.CSharp.RuntimeBinder.ComInterop.IDispatchMetaObject.BindSetMember(SetMemberBinder binder, DynamicMetaObject value) in /_/src/libraries/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/ComInterop/IDispatchMetaObject.cs:line 194
   at System.Dynamic.SetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args) in /_/src/libraries/System.Linq.Expressions/src/System/Dynamic/SetMemberBinder.cs:line 56
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel) in /_/src/libraries/System.Linq.Expressions/src/System/Dynamic/DynamicMetaObjectBinder.cs:line 81
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args) in /_/src/libraries/System.Linq.Expressions/src/System/Runtime/CompilerServices/CallSiteBinder.cs:line 120
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1) in /_/src/libraries/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs:line 260
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1) in /_/src/libraries/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs:line 268
   at Dynamic.BasicTest.Null()
   at Dynamic.BasicTest.Run()
   at Dynamic.Program.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 9/17/2023 7:55:46 PM
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AF9F091C\p
> C:\h\w\AF9F091C\w\AE880999\e\Interop\COM\Dynamic\Dynamic\Dynamic.cmd
Expected: True
Actual:   False
```

**Stack trace:**
```
   at Interop_COM._Dynamic_Dynamic_Dynamic_._Dynamic_Dynamic_Dynamic_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=410857
Build error leg or test failing: Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd
Pull request: https://github.com/dotnet/runtime/pull/92252

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.NotSupportedException: Specified method is not supported",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by BruceForstall** [comment]
I see this fail in a lot of win-x64 stress mode runs:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=409220&view=ms.vss-test-web.build-test-results-tab&runId=8894564&resultId=116513&paneView=debug

and:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=409326&view=ms.vss-test-web.build-test-results-tab&runId=8899440&resultId=116513&paneView=debug

@dotnet/interop-contrib

**Comment by BruceForstall** [comment]
As well as non-jitstress:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=409347&view=ms.vss-test-web.build-test-results-tab

https://dev.azure.com/dnceng-public/public/_build/results?buildId=409239&view=ms.vss-test-web.build-test-results-tab&runId=8895398&resultId=115384&paneView=debug

**Comment by BruceForstall** [comment]
And plain outerloop: https://dev.azure.com/dnceng-public/public/_build/results?buildId=409427&view=ms.vss-test-web.build-test-results-tab

**Comment by AaronRobinsonMSFT** [comment]
I applied @EgorBo's fix in https://github.com/dotnet/runtime/issues/92202 and this issue is no longer reproducible. I needed to set the following and it crashed reliably.

```
SET DOTNET_TieredCompilation=0
SET DOTNET_ReadyToRun=0
SET DOTNET_ZapDisable=1
```
