### ISSUE TITLE
NRE in ConfigurationBinder.BindInstance

### ISSUE THREAD

**Issue by RussKie** [dotnet/runtime#92213]
### Description

This looks like a regression which happened between 8.0.0-rc.2.23431.9 (3c48925a6c1ab31865b4438a6cb88242d1a8fe4d) and 8.0.0-rc.2.23466.4 (287c10d2539d47268a1083c4d533cf84124900cf).

Updating the 1P internal codebase to the latest .NET Extensions, [several tests failed](https://domoreexp.visualstudio.com/R9/_build/results?buildId=23855283&view=ms.vss-test-web.build-test-results-tab&runId=186097722&paneView=debug&resultId=167506) with the following stack trace:
```
at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
```

### Reproduction Steps

I'm not familiar with this area of the runtime, nor I'm sufficiently familiar with the 1P codebase I'm updating to craft a standalone repro, so we may need to debug it interactively since this is an internal codebase.

### Expected behavior

No NRE, everything continues work as before :)

### Actual behavior

Tests fail

### Regression?

Yes

### Other information

/cc: @geeknoid @joperezr

**Comment by tarekgh** [comment]
@RussKie if you can get us a standalone repro will be helpful to act on this issue. 

Side question, do you know if the configuration binder source generator is enabled in your case?

**Comment by tarekgh** [comment]
@layomia FYI. no need to act on it till we gather more information. Thanks!

**Comment by ericstj** [comment]
I see the error that @RussKie provided points to https://domoreexp.visualstudio.com/R9/_git/3a5add3e-806c-495f-968c-4a688096398e?path=/test/Service/Middleware.UnexpectedRouteReporting.Tests/UnexpectedRouteExtensionsTest.cs&version=GBgeeknoid/net8&_a=contents

I was able to pull out the repro to a standalone app using their packages and I confirm the repro.  I'll try to reduce it to not use their packages and share it.

**Comment by ericstj** [comment]
Yeah, this is due to Mock<IConfigurationSection>.GetSection returning null rather than a section without a value.  We'll always return a value: https://github.com/dotnet/runtime/blob/5883b728c8b29a7026cf3a807a22928cee844bc5/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationRoot.cs#L77-L78

We should fix this and add a test case that uses Moq in a similar manner.

**Comment by ericstj** [comment]
Here's the isolated repro: 
[extNullRef.zip](https://github.com/dotnet/runtime/files/12676802/extNullRef.zip)

**Comment by RussKie** [comment]
Thank you @ericstj
