### ISSUE TITLE
Test failure: System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#92246]
Also,

System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_AddQuotes
System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes

Many failures on x64 in various JitStress runs. Does not fail for MinOpts.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=410217&view=ms.vss-test-web.build-test-results-tab&runId=8923252&resultId=134731&paneView=debug

https://dev.azure.com/dnceng-public/public/_build/results?buildId=410219&view=ms.vss-test-web.build-test-results-tab

e.g.,

net9.0-windows-Release-x64-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode

```
    System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode(decoded: ")", encoded: "\\u0029") [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: \u0029
      Actual:   )
                 (pos 0)
      Stack Trace:
        /_/src/libraries/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs(357,0): at System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode(String decoded, String encoded)
           at InvokeStub_HttpUtilityTest.JavaScriptStringEncode(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode(decoded: "E", encoded: "E") [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: E
      Actual:   \u0045
                 (pos 0)
      Stack Trace:
        /_/src/libraries/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs(357,0): at System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode(String decoded, String encoded)
           at InvokeStub_HttpUtilityTest.JavaScriptStringEncode(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes(decoded: ")", encoded: "\\u0029") [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: \u0029
      Actual:   )
                 (pos 0)
      Stack Trace:
        /_/src/libraries/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs(372,0): at System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes(String decoded, String encoded)
           at InvokeStub_HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes(decoded: "E", encoded: "E") [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: E
      Actual:   \u0045
                 (pos 0)
      Stack Trace:
        /_/src/libraries/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs(372,0): at System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes(String decoded, String encoded)
           at InvokeStub_HttpUtilityTest.JavaScriptStringEncode_ExplicitDontAddQuotes(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_AddQuotes(decoded: ")", encoded: "\\u0029") [FAIL]
      Assert.Equal() Failure
                  (pos 1)
      Expected: "\u0029"
      Actual:   ")"
                  (pos 1)
      Stack Trace:
        /_/src/libraries/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs(364,0): at System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_AddQuotes(String decoded, String encoded)
           at InvokeStub_HttpUtilityTest.JavaScriptStringEncode_AddQuotes(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_AddQuotes(decoded: "E", encoded: "E") [FAIL]
      Assert.Equal() Failure
                  (pos 1)
      Expected: "E"
      Actual:   "\u0045"
                  (pos 1)
      Stack Trace:
        /_/src/libraries/System.Web.HttpUtility/tests/HttpUtility/HttpUtilityTest.cs(364,0): at System.Web.Tests.HttpUtilityTest.JavaScriptStringEncode_AddQuotes(String decoded, String encoded)
           at InvokeStub_HttpUtilityTest.JavaScriptStringEncode_AddQuotes(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Web.HttpUtility.Tests
=== TEST EXECUTION SUMMARY ===
   System.Web.HttpUtility.Tests  Total: 2361, Errors: 0, Failed: 6, Skipped: 0, Time: 3.744s
```

**Comment by BruceForstall** [comment]
@EgorBo This is a regression from https://github.com/dotnet/runtime/pull/87656
