### ISSUE TITLE
MSBuild crashing in the build

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#92290]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=410579
Build error leg or test failing: Build / Mono  Product Build windows x64 release / Build product
Pull request: https://github.com/dotnet/runtime/pull/91768

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Child Node \"[0-9]+\" exited prematurely.",
  "BuildRetry": true,
  "ExcludeConsoleLog": false
}
```

**Comment by ViktorHofer** [comment]
cc @rainersigwald @rokonec

**Comment by lewing** [comment]
reup for 97 hits per month

**Comment by MichalStrehovsky** [comment]
We now have more useful information in the logs for these. Two of the available logs have this in it:

```
2024-02-19T21:13:25.8115210Z MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/MSBuildTemprunner/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
2024-02-19T21:13:25.8126770Z MSBUILD : error MSB4166: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/MSBuildTemprunner/MSBuild_pid-50918_4ee39488d5ca4c7d9fb049f19f43c144.failure.txt:
2024-02-19T21:13:25.8128200Z MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 50918:
2024-02-19T21:13:25.8129250Z MSBUILD : error MSB4166: =====================
2024-02-19T21:13:25.8140670Z MSBUILD : error MSB4166: 2/19/2024 9:13:25 PM
2024-02-19T21:13:25.8241810Z MSBUILD : error MSB4166: System.IO.IOException: No buffer space available
2024-02-19T21:13:25.8260730Z MSBUILD : error MSB4166:  ---> System.Net.Sockets.SocketException (55): No buffer space available
2024-02-19T21:13:25.8363710Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
2024-02-19T21:13:25.8364490Z MSBUILD : error MSB4166:    --- End of inner exception stack trace ---
2024-02-19T21:13:25.8465500Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
2024-02-19T21:13:25.8569320Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
2024-02-19T21:13:25.8670730Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
2024-02-19T21:13:25.8773480Z MSBUILD : error MSB4166: ===================
```

@rainersigwald does this ring any bell?

**Comment by rainersigwald** [comment]
All of the recent hits seem to be dotnet/msbuild#10342, which should be fixed in the preview7 GA build. Is there a timeline for updating to that? Anything my team can help with?

**Comment by rainersigwald** [comment]
> ```
> 2024-02-19T21:13:25.8115210Z MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/MSBuildTemprunner/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
> 2024-02-19T21:13:25.8126770Z MSBUILD : error MSB4166: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/MSBuildTemprunner/MSBuild_pid-50918_4ee39488d5ca4c7d9fb049f19f43c144.failure.txt:
> 2024-02-19T21:13:25.8128200Z MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 50918:
> 2024-02-19T21:13:25.8129250Z MSBUILD : error MSB4166: =====================
> 2024-02-19T21:13:25.8140670Z MSBUILD : error MSB4166: 2/19/2024 9:13:25 PM
> 2024-02-19T21:13:25.8241810Z MSBUILD : error MSB4166: System.IO.IOException: No buffer space available
> 2024-02-19T21:13:25.8260730Z MSBUILD : error MSB4166:  ---> System.Net.Sockets.SocketException (55): No buffer space available
> 2024-02-19T21:13:25.8363710Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
> 2024-02-19T21:13:25.8364490Z MSBUILD : error MSB4166:    --- End of inner exception stack trace ---
> 2024-02-19T21:13:25.8465500Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
> 2024-02-19T21:13:25.8569320Z MSBUILD : error MSB4166:    at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
> 2024-02-19T21:13:25.8670730Z MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
> 2024-02-19T21:13:25.8773480Z MSBUILD : error MSB4166: ===================
> ```

this one I don't recognize, but I haven't seen it in the current links.

**Comment by rainersigwald** [comment]
Is it possible to have multiple issues with known problems that match a signature with prioritization? I'd like to create one like `at Microsoft.Build.BackEnd.Logging.LoggingContext.LogBuildEvent` to bucket the https://github.com/dotnet/msbuild/issues/10342 hits so we can use this one for "everything else that causes an MSBuild worker node crash".

**Comment by jkoritzinsky** [comment]
You can have multiple known issues I think, but I don't think there's a prioritization mechanism.

I'd recommend having a separate issue to bucket the dotnet/msbuild#10342 hits and leave this one as a catch-all to trigger build retries when a node dies (and we can triage specific failure classes into different known issues if they happen with enough frequency).

**Comment by danmoseley** [comment]
We should now get MSBuild dumps (the text file with a stack anyway) once https://github.com/dotnet/arcade/pull/16715 floats around repos.

This should not be closed.

**Comment by lewing** [comment]
A fresh occurrence on [dotnet/runtime#129454 build 1472222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1472222) (linux WBT, `SatelliteLoadingTests.LoadSatelliteAssembly`) surfaced the full inner exception that the dump-capture logging from dotnet/arcade#16715 now provides:

```
Microsoft.Build.Exceptions.InternalLoggerException:
 ---> System.ObjectDisposedException:
      Object name: 'System.Collections.Immutable.SortedInt32KeyNode`1+Enumerator[[...]]'
   at System.Collections.Immutable.SortedInt32KeyNode`1.Enumerator.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.Enumerator.MoveNext()
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.EnumerateMetadata(...)+MoveNext()
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(ITaskItem item, Boolean writeMetadata)
   at Microsoft.Build.Logging.BuildEventArgsWriter.WriteTaskItemList(...)
   at Microsoft.Build.Logging.BuildEventArgsWriter.Write(TargetFinishedEventArgs e)
   at Microsoft.Build.Logging.BinaryLogger.Write(BuildEventArgs e)
```

This is a distinct root cause from the previously-fixed dotnet/msbuild#10342 (`AssemblyLoadsTracker`). The crash is an `ImmutableDictionary<,>.Enumerator` struct copy being accessed after its shared `SecurePooledObject<Stack<...>>` slot was returned to the pool by another copy's `Dispose()`. The `yield return` iterator inside `ProjectItemInstance.TaskItem.EnumerateMetadata` parks one such copy across yield boundaries, making it vulnerable when multiple loggers or threads enumerate the same item's metadata concurrently.

PR up at **dotnet/msbuild#14115** — materializes the snapshot eagerly so the enumeration happens in a single stack frame on one thread and the returned array carries no reference to a pooled enumerator.

Repo-wide audit found no other `yield return` iterators over `Immutable*` collections in `src/Build`, `src/Framework`, or `src/Tasks`, so the fix is targeted at the one known offender. Worth keeping this issue open until #14115 ships and we observe whether occurrences drop to zero.

> [!NOTE]
> This comment was AI/Copilot-generated.

**Comment by lewing** [comment]
Another occurrence in the **VMR internal official build** (dotnet/dotnet unified-build pipeline):

**Build:** https://dev.azure.com/dnceng/internal/_build/results?buildId=3008360
**Leg:** `OSX_x64` (SDK repo build phase)
**Date:** 2026-06-25
**Exit code:** 139 (SIGSEGV, signal 11)

```
/Users/runner/work/1/s/src/sdk/eng/common/tools.sh: line 516: 85878 Segmentation fault: 11  "$_InitializeBuildTool" "$@"
```

The crash occurred immediately after a successful NuGet tool restore (`microsoft.dotnet.helix.jobmonitor`), at the start of the `dotnet msbuild` invocation for the SDK build/pack/publish phase. No inner exception or dump was captured (the arcade dump-capture from #16715 is not wired in this leg).

**Bisection confirms non-deterministic:**
- Build [3008113](https://dev.azure.com/dnceng/internal/_build/results?buildId=3008113) (commit `b97dd2f4`, queued 15:28 UTC) \u2014 OSX_x64 **passed**
- Build [3008360](https://dev.azure.com/dnceng/internal/_build/results?buildId=3008360) (commit `58d582b6`, queued 20:37 UTC) \u2014 OSX_x64 **SIGSEGV**
- Only source delta between them is [dotnet/dotnet#5328](https://github.com/dotnet/dotnet/pull/5328) (signing validation config change \u2014 cannot cause a segfault)

This is notable because the VMR official pipeline does **not** appear to have the `BuildRetry` pattern wired for the "Child Node exited prematurely" match, so the crash is not automatically retried. Worth considering whether the VMR build orchestration should catch exit code 139 and retry.

> [!NOTE]
> This comment was AI/Copilot-generated.

**Comment by jkotas** [comment]
> https://dev.azure.com/dnceng/internal/_build/results?buildId=3008360

This build run on SDK from early May. Look for "Attempting to install 'sdk v11.0.100-preview.5.26302.115 from public_location." in the log. 26302 is May 2.

https://github.com/dotnet/runtime/pull/129531 fixed OSX-x64 specific bug that can explain intermittent SIGSEGV like the one we are seeing here. I think the best course of action to fix this crash is to accelerate update of the toolset SDK to current, and see whether it stops reproing.

This won't fix all crashes listed here. This issue is grab-bag of crashes with multiple different symptoms that are likely to have multiple different root causes.

**Comment by missymessa** [comment]
### Ownership triage: build-agent crash, not Helix test infra

Looked at this from the .NET Engineering Services / Helix side to determine whether the crashes are in infrastructure we own.

**Finding: these are build-time MSBuild worker-node crashes on Azure DevOps build agents, not Helix test-execution machines.**
- All failing legs are product-build legs (e.g. *"Mono Product Build windows x64 release / Build product"*, *"OSX_x64 (SDK repo build phase)"*).
- Crash paths are AzDO agent working dirs (`/Users/runner/work/1/s/...`, `/var/folders/.../MSBuildTemprunner/`), not Helix work-item directories.
- The identified root causes are all software bugs, none Helix-infra defects: dotnet/msbuild#10342 (fixed), dotnet/msbuild#14115 (still open), dotnet/runtime#129531 (macOS x64 SIGSEGV, merged 2026-06-18).

**Current status of the in-flight fixes:**
- dotnet/msbuild#14115 (`ImmutableDictionary` enumerator race) — **still OPEN**, needs a merge nudge from the MSBuild team.
- dotnet/runtime#129531 (macOS x64 SIGSEGV) — merged 2026-06-18; per @jkotas the toolset SDK still needs to advance past `11.0.100-preview.5.26302.115` for repos to pick it up.
- dotnet/arcade#16715 (`MSBUILDDEBUGPATH` dump capture) — merged, but **not wired into every leg** (the VMR OSX_x64 SDK build phase captured no dump).

**Two engineering-services-owned gaps** we're tracking internally (dnceng AzDO work item **#11558** — `https://dev.azure.com/dnceng/internal/_workitems/edit/11558`, internal-only):
1. The VMR official pipeline (dotnet/dotnet unified-build) does **not** wire the `BuildRetry` known-issue pattern for "Child Node exited prematurely" / exit 139, so these crashes aren't auto-retried there (unlike dotnet/runtime CI). Example: dnceng build 3008360 (OSX_x64, exit 139).
2. Ensure the arcade#16715 dump-capture is applied to the OSX_x64 VMR leg (and audit other legs missing it) so future crashes preserve a stack trace.

The remaining root-cause fixes (msbuild#14115, toolset SDK bump for runtime#129531) are owned upstream by the MSBuild and runtime teams.

> [!NOTE]
> This comment was AI/Copilot-generated.
