### ISSUE TITLE
System.IO.Directory.CreateTempSubdirectory(String prefix) fails with Success exception in wasi-wasm build

### ISSUE THREAD

**Issue by dbaeumer** [dotnet/runtime#92336]
### Description

Calling `System.IO.Directory.CreateTempSubdirectory(String prefix)` fails with an exception in a wasi-wasm build

### Reproduction Steps

- .Net version 8.0.100-rc.1.23455.8
- tempDir.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifier>wasi-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <PublishTrimmed>true</PublishTrimmed>
    <WasmSingleFileBundle>true</WasmSingleFileBundle>
  </PropertyGroup>
</Project>
```
- Program.cs
```
using System;
using System.IO;
using System.Text;

Console.WriteLine("Hello, Wasi Console!");

using (var writer = File.Create("/tmp/test.txt")) {
	writer.Write(Encoding.UTF8.GetBytes("Hello World!"));
}

var dir = Directory.CreateTempSubdirectory();
Console.WriteLine("Created temp dir: " + dir.FullName);
```

- dotnet build
- create a tmp directory in the workspace directory
- wasmtime 12.0.2
- run `wasmtime run --mapdir /::. --env TMPDIR=/tmp obj/Debug/net8.0/wasi-wasm/wasm/for-build/tempDir.wasm`

### Expected behavior

Creating the temp directory works

### Actual behavior

```
System.IO.IOException: Success
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Interop.ThrowIOExceptionForLastError()
   at System.IO.Directory.CreateTempSubdirectoryCore(String prefix)
   at System.IO.Directory.CreateTempSubdirectory(String prefix)
   at Program.<Main>$(String[] args)
```

The write to the file happened successful.

**Comment by dbaeumer** [comment]
I can create a directory as well using the following code

```cs
var dirOne = Directory.CreateDirectory("/tmp/dirOne");
Console.WriteLine("Created dir: " + dirOne.FullName);
```

**Comment by pavelsavara** [comment]
Could be related https://github.com/dotnet/runtime/issues/81210 and https://github.com/WebAssembly/wasi-libc/issues/414

**Comment by dbaeumer** [comment]
@pavelsavara I executed the WASM file on the VS Code WASI host implementation which offers nice tracing of host calls. The `Directory.CreateTempSubdirectory()` call doesn't result in any host calls, so I guess this fails inside some C# code and is falsely reported as a exception with an `errno`. There aren't any `fd_readdir` calls either before. 

What I did notice as well is that the wasm code does tons of `clock_time_get(id: monotonic, precision: 1)` calls.

**Comment by pavelsavara** [comment]
See 

https://github.com/dotnet/runtime/blob/32c3355c502c4d8fd8f6dd50d23e9676faf03e3c/src/native/libs/System.Native/pal_io.c#L850-L852

https://github.com/WebAssembly/wasi-libc/blob/ce2f157d46e04f323edf93f02c8f60069d88df96/libc-top-half/musl/include/stdlib.h#L118-L122

**Comment by dbaeumer** [comment]
Any reason why we couldn't implement that in C# for WASI. I can understand why we can't use libc since they hardcode `/tmp` but Python on wasm-wasi has support for this since they come with their own `mkdtemp` implementation.

**Comment by pavelsavara** [comment]
That's what https://github.com/dotnet/runtime/issues/81210 wants I think.

It would be also good to do that for emscripten build. 

Because the idea of generating randomness out of timer + checking if there is file system conflict is very ugly. 
We had issues with that already because of the granularity of browser timer used.

https://github.com/emscripten-core/emscripten/blob/813a727fa77b3596c75a6d62b2fdb87365f9d75a/system/lib/libc/musl/src/temp/mkdtemp.c#L16-L19



https://github.com/emscripten-core/emscripten/blob/813a727fa77b3596c75a6d62b2fdb87365f9d75a/system/lib/libc/musl/src/temp/__randname.c#L13-L14



PR welcome.

**Comment by adamsitnik** [comment]
It reminds me of

![image](https://github.com/dotnet/runtime/assets/6011991/ea58bede-60e5-4370-b5fc-68ede53daa9a)

**Comment by pavelsavara** [comment]
`SetLastError` FTW ? 😎

**Comment by ilonatommy** [comment]
blocked by https://github.com/WebAssembly/wasi-libc/issues/229
