### ISSUE TITLE
`ReadsWritesClosedFinish_StreamDisposed` test failures

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#92350]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=412998
Build error leg or test failing: System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed
Pull request: https://github.com/dotnet/runtime/pull/92135

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=412998
**Error message validated:** `System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/20/2023 3:45:38 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[414741](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414741)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/414741/logs/99)|dotnet/runtime#92241|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[417649](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417649)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417649&view=ms.vss-test-web.build-test-results-tab&runId=9151254&resultId=200821)||
|[417614](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417614)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417614&view=ms.vss-test-web.build-test-results-tab&runId=9150204&resultId=200854)||
|[417331](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417331)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417331&view=ms.vss-test-web.build-test-results-tab&runId=9140600&resultId=194899)||
|[417175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417175)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=417175&view=ms.vss-test-web.build-test-results-tab&runId=9136314&resultId=200686)||
|[416890](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416890)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416890&view=ms.vss-test-web.build-test-results-tab&runId=9126888&resultId=194899)|dotnet/runtime#92527|
|[416726](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416726)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416726&view=ms.vss-test-web.build-test-results-tab&runId=9121092&resultId=194899)||
|[416701](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416701)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416701&view=ms.vss-test-web.build-test-results-tab&runId=9120316&resultId=194899)|dotnet/runtime#92512|
|[416451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416451)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416451&view=ms.vss-test-web.build-test-results-tab&runId=9113340&resultId=190760)|dotnet/runtime#92452|
|[416245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416245)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416245&view=ms.vss-test-web.build-test-results-tab&runId=9106154&resultId=194899)|dotnet/runtime#92501|
|[416203](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416203)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416203&view=ms.vss-test-web.build-test-results-tab&runId=9103968&resultId=194899)||
|[415507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415507)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415507&view=ms.vss-test-web.build-test-results-tab&runId=9080832&resultId=194899)|dotnet/runtime#92307|
|[415491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415491)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415491&view=ms.vss-test-web.build-test-results-tab&runId=9080084&resultId=200720)||
|[415451](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415451)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415451&view=ms.vss-test-web.build-test-results-tab&runId=9079130&resultId=200719)||
|[415077](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415077)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415077&view=ms.vss-test-web.build-test-results-tab&runId=9067864&resultId=156004)|dotnet/runtime#92435|
|[414896](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414896)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414896&view=ms.vss-test-web.build-test-results-tab&runId=9065040&resultId=155037)|dotnet/runtime#92384|
|[414919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414919)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414919&view=ms.vss-test-web.build-test-results-tab&runId=9064654&resultId=194883)|dotnet/runtime#92405|
|[414925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414925)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414925&view=ms.vss-test-web.build-test-results-tab&runId=9062774&resultId=194882)||
|[414813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414813)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414813&view=ms.vss-test-web.build-test-results-tab&runId=9060630&resultId=194882)|dotnet/runtime#92385|
|[414795](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414795)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414795&view=ms.vss-test-web.build-test-results-tab&runId=9060502&resultId=194763)|dotnet/runtime#92274|
|[414423](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414423)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414423&view=ms.vss-test-web.build-test-results-tab&runId=9047882&resultId=200669)||
|[413702](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413702)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413702&view=ms.vss-test-web.build-test-results-tab&runId=9030390&resultId=205320)|dotnet/runtime#92385|
|[413148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413148)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413148&view=ms.vss-test-web.build-test-results-tab&runId=9013390&resultId=194882)||
|[413086](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413086)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413086&view=ms.vss-test-web.build-test-results-tab&runId=9012178&resultId=194882)|dotnet/runtime#90436|
|[412998](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412998)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412998&view=ms.vss-test-web.build-test-results-tab&runId=9009356&resultId=194882)|dotnet/runtime#92135|
|[412861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412861)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412861&view=ms.vss-test-web.build-test-results-tab&runId=9007318&resultId=194882)|dotnet/runtime#92174|
|[412212](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412212)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412212&view=ms.vss-test-web.build-test-results-tab&runId=8980790&resultId=194880)|dotnet/runtime#92307|
|[412132](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412132)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=412132&view=ms.vss-test-web.build-test-results-tab&runId=8977132&resultId=208049)|dotnet/runtime#92037|
|[411887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411887)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411887&view=ms.vss-test-web.build-test-results-tab&runId=8970222&resultId=209540)|dotnet/runtime#92298|
|[411860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411860)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411860&view=ms.vss-test-web.build-test-results-tab&runId=8969404&resultId=194899)|dotnet/runtime#91904|
|[411640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411640)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411640&view=ms.vss-test-web.build-test-results-tab&runId=8963820&resultId=194880)|dotnet/runtime#92211|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|3|31|31|

**Comment by MihaZupan** [comment]
cc: @ManickaP [Kusto](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA61TTWvbQBC9+1cMoiAJFKnQW4sLadOAC4ld25BDKWEtTeSNpV11djZ2kva/d1b+iE166KEnS+M38968eWqQ4U7pBqs5Op5642AIiWNFfKEY4T1U8sO6xRSeB2XjHSMlMZra0UNHtspXUrL5WpvKrl1ukOM0lx61UA57oDaIpE0divLf+ZMnvMCHcecCpRv8gvUSCSG8XasWoWd3a81LiGaPQtjm18gRHJDJ2HNpBTkcQnzZq4/BEhyXJ8o5rMZmiuRNnB56jeXkwISm2vHcWFqNhOnLBkvP2pootFTasTYlw1e7GFUZ7FHh+QqdUzVmADNW5WpOqpSX/ehsLyaDc6p9i6bf9N5qAyvxaqiNQYLkfzgq4o5cfOxOHWRRVNx52UK2Uk1RNrqIQJkq6CbGCj7Cy71DPVg0IdshsUYHpTWstAQjEidDEs4ELhrq3iLn21aRfpJWqm9btUkutdFuiWLRy5Cs15XBJ1KmXGYws56CXTsJGXzz6DEYl8LicWu3DBc77rHkM0ITziXlfr1hPy0Fa3bI3x8GzUmQX6XYcTAMQohP4/6CCtvghiUTMHKjcJ7G2k4GHWglVn9zU++xRZxJqxz+n1vtHlvEx+xX4vfWqrDH/klmEN65YomqckUrmPhE82Qq6K2zJwnoaHdwQUpK+d5Zk0Rv8u/x7uua+KaZ4k8vAvO5nBF5Sxn/iI6PmPYSet7g+JHbiapt8u5tlaavv+alkuRMg+Qb0uLB58bKh7kNye2MCVV7oV0XitEffvLht44EAAA=) has 247 records for this one starting with September 13th when the test was added, mostly passing on reruns.

[Example logs](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92135-merge-510bc108cb954c68bd/System.Net.Quic.Functional.Tests/3/console.ea90070a.log?helixlogtype=result):
```
System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed(payloadSize: 1, disposeServer: False, completeWrites: True) [FAIL]
  Assert.True() Failure
  Expected: True
  Actual:   False
  Stack Trace:
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1512,0): at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass47_0.<<ReadsWritesClosedFinish_StreamDisposed>g__WaitingSide|3>d.MoveNext()
    --- End of stack trace from previous location ---
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1427,0): at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass47_0.<<ReadsWritesClosedFinish_StreamDisposed>b__1>d.MoveNext()
    --- End of stack trace from previous location ---
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1427,0): at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass47_0.<<ReadsWritesClosedFinish_StreamDisposed>b__1>d.MoveNext()
    --- End of stack trace from previous location ---
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(299,0): at System.Net.Quic.Tests.QuicTestBase.<>c__DisplayClass39_1.<<RunClientServer>b__0>d.MoveNext()
    --- End of stack trace from previous location ---
    /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
    --- End of stack trace from previous location ---
    /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
    /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(295,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(325,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(325,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(289,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
    /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(1412,0): at System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed(Int32 payloadSize, Boolean disposeServer, Boolean completeWrites)
    --- End of stack trace from previous location ---
  Output:
    System.Net.Quic.QuicException: Reading has been aborted on the stream.
       at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 180
       at System.Net.Quic.QuicStream.<DisposeAsync>g__StreamShutdown|44_0(QUIC_STREAM_SHUTDOWN_FLAGS flags, Int64 errorCode) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 740
       at System.Net.Quic.QuicStream.DisposeAsync() in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 702
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
       at System.Net.Quic.QuicStream.DisposeAsync()
       at System.Net.Quic.Tests.QuicStreamTests.<>c__DisplayClass47_0.<<ReadsWritesClosedFinish_StreamDisposed>g__DisposeSide|2>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 1466
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 288
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 179
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 368
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 346
       at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 795
       at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3456
       at System.Threading.Tasks.Task.TrySetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3330
       at System.Threading.Tasks.Task.CancellationPromise`1.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2926
       at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
       at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 58
    --- End of stack trace from previous location ---
       at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in /_/src/Microsoft.DotNet.XUnitAssert/src/Record.cs:line 113
```
