### ISSUE TITLE
[8.0] coreclr test failure: readytorun_GenericCycleDetection._Depth3Test_Depth3Test_._Depth3Test_Depth3Test_sh()

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#92420]
### Error Blob

```json
{
  "ErrorMessage": "at readytorun_GenericCycleDetection._Depth3Test_Depth3Test_._Depth3Test_Depth3Test_sh()",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Affected 8.0 PR: https://github.com/dotnet/runtime/pull/92374
- Queue: `coreclr Pri0 Runtime Tests Run linux arm64 checked`
- Output: https://dev.azure.com/dnceng-public/public/_build/results?buildId=413445&view=logs&j=15d7b3ca-f7a5-5373-9266-3c1554d785ae&t=419130a4-49ed-506c-d64d-960f64a7e2f4
- Log file: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-80-rc1-36beb22420eb4e10b2/PayloadGroup0/1/console.a3f6e0ab.log?helixlogtype=result

<details><summary>Output (expand)</summary>

```
  Starting:    readytorun.GenericCycleDetection.XUnitWrapper (parallel test collections = on, max threads = 2)
   readytorun.GenericCycleDetection.XUnitWrapper: [Long Running Test] 'readytorun/GenericCycleDetection/Depth3Test/Depth3Test.sh', Elapsed: 00:02:48
      cp: target '/root/helix/work/correlation/lib*.dylib' is not a directory
      /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/Depth3Test.sh: line 253:  1921 Killed                  $__Command
    readytorun/GenericCycleDetection/Depth3Test/Depth3Test.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/readytorun.GenericCycleDetection/Depth3Test/Depth3Test.output.txt
      Raw output:
      BEGIN EXECUTION
      in takeLock
      22:27:38
      Response file: /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll.rsp
      /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/IL-CG2/Depth3Test.dll
      -o:/root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll
      -r:/root/helix/work/correlation/System.*.dll
      -r:/root/helix/work/correlation/Microsoft.*.dll
      -r:/root/helix/work/correlation/xunit.*.dll
      -r:/root/helix/work/correlation/mscorlib.dll
      --verify-type-and-field-layout
      --method-layout:random
      --targetarch:arm64
      --targetos:linux
      Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll.rsp  --enable-generic-cycle-detection --maxgenericcycle:3 --maxgenericcyclebreadth:-1 --composite
      Emitting R2R PE file: /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll
      Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll --out /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll.r2rdump --val
      Warning: No files matching /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll
      Error: System.ArgumentException: Input filename must be specified (--in <file>)
         at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 433
      
      22:32:25
      Crossgen2 failed with exitcode: 137
      in ReleaseLock
      Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 9/20/2023 10:27:38 PM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/Depth3Test.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at readytorun_GenericCycleDetection._Depth3Test_Depth3Test_._Depth3Test_Depth3Test_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        cp: target '/root/helix/work/correlation/lib*.dylib' is not a directory
        /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/Depth3Test.sh: line 253:  1921 Killed                  $__Command
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/readytorun.GenericCycleDetection/Depth3Test/Depth3Test.output.txt
        Raw output:
        BEGIN EXECUTION
        in takeLock
        22:27:38
        Response file: /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll.rsp
        /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/IL-CG2/Depth3Test.dll
        -o:/root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll
        -r:/root/helix/work/correlation/System.*.dll
        -r:/root/helix/work/correlation/Microsoft.*.dll
        -r:/root/helix/work/correlation/xunit.*.dll
        -r:/root/helix/work/correlation/mscorlib.dll
        --verify-type-and-field-layout
        --method-layout:random
        --targetarch:arm64
        --targetos:linux
        Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll.rsp  --enable-generic-cycle-detection --maxgenericcycle:3 --maxgenericcyclebreadth:-1 --composite
        Emitting R2R PE file: /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll
        Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll --out /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll.r2rdump --val
        Warning: No files matching /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/composite-r2r.dll
        Error: System.ArgumentException: Input filename must be specified (--in <file>)
           at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 433
        
        22:32:25
        Crossgen2 failed with exitcode: 137
        in ReleaseLock
        Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 9/20/2023 10:27:38 PM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/readytorun/GenericCycleDetection/Depth3Test/Depth3Test.sh
```
</details>

**Comment by mangod9** [comment]
@trylek is this one of the new tests which was added as part of your cycle detection change?

**Comment by trylek** [comment]
@mangod9 / @carlossanlop - This is a test issue, Crossgen2 timeout when compiling an artificially huge generic graph to exercise a cutoff parameter I added earlier this year to prevent Crossgen2 from OOMing upon such constructs. I merged in a PR slightly simplifying the test to avoid the timeouts in

https://github.com/dotnet/runtime/pull/90777

but apparently it missed the 8.0 fork on 8/14. I don't think the test is fundamental for .NET 8 validation, after all it's just one of three tests I created for this purpose and the feature itself is rather obscure as the bug has been hit just by a few customers so far.

Carlos, can you please advise what is the most appropriate course of action here? I guess we can either send out shiproom request for backporting my PR or for excluding this test in ```issues.targets``` in the 8.0 branch. In both cases I would assume that the change is "non-product" (infra / test only) so it should hopefully fall under tell mode but I may be mistaken. For this issue, that can be marked as a test issue but that won't make the occasional timeouts in the 8.0 branch go away so it will cause a bit of long-term pain when monitoring the runs.

Thanks

Tomas

**Comment by trylek** [comment]
In fact it's a little weird - my PR includes removal of the issues.targets exclusion of the test that was merged before by someone, maybe Bruce but I'm not sure, when the bug started manifesting, so it should have been disabled prior to my merge of this PR. I guess in such case we should first figure out why the issues.targets exclusion is missing in the 8.0 branch - could it be a bad conflict merge?

**Comment by trylek** [comment]
OK, I've found it, Bruce merged in the addition to ```issues.targets``` in

https://github.com/dotnet/runtime/pull/90802

on 8/18 so it also missed the fork. In such case I guess a third option is to port just Bruce's PR.

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
