### ISSUE TITLE
System.Management.Tests fail with System.Management.ManagementException

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#92518]
```
    System.Management.Tests.ManagementObjectTests.Set_Property_Win32_ComputerSystem [FAIL]
      System.Management.ManagementException : Invalid class 
      Stack Trace:
        /_/src/libraries/System.Management/src/System/Management/ManagementException.cs(614,0): at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
        /_/src/libraries/System.Management/src/System/Management/ManagementObject.cs(794,0): at System.Management.ManagementObject.Get()
        /_/src/libraries/System.Management/tests/System/Management/ManagementObjectTests.cs(61,0): at System.Management.Tests.ManagementObjectTests.Set_Property_Win32_ComputerSystem()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
```

```
    System.Management.Tests.ManagementClassTests.Get_SourceFile_For_Win32_Processor(lang: CSharp) [FAIL]
      System.Management.ManagementException : Not found 
      Stack Trace:
        /_/src/libraries/System.Management/src/System/Management/ManagementException.cs(614,0): at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
        /_/src/libraries/System.Management/src/System/Management/ManagementObject.cs(794,0): at System.Management.ManagementObject.Get()
        /_/src/libraries/System.Management/src/System/Management/ManagementClass.cs(1438,0): at System.Management.ManagementClass.GetStronglyTypedClassCode(CodeLanguage lang, String filePath, String classNamespace)
        /_/src/libraries/System.Management/tests/System/Management/ManagementClassTests.cs(39,0): at System.Management.Tests.ManagementClassTests.Get_SourceFile_For_Win32_Processor(CodeLanguage lang)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=416627
Build error leg or test failing: System.Management.Tests.ManagementClassTests.ClassMembers_For_Win32_LogicalDisk
Pull request: https://github.com/dotnet/runtime/pull/92492

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Management.ManagementException",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=416627
**Error message validated:** `System.Management.ManagementException`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/23/2023 6:55:24 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0
