### ISSUE TITLE
Test failure JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#92573]
**Failed in:** [runtime-coreclr jitstress-isas-arm 20230923.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=416992&view=ms.vss-test-web.build-test-results-tab&runId=9130748&resultId=116239&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked jitstress_isas_nohwintrinsic @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd
coreclr osx arm64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.ARM64.Open
    - JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd
coreclr windows arm64 Checked jitstress_isas_nohwintrinsic @ Windows.11.Arm64.Open
    - JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd
```

**Error message:**
```
 Assert failure(PID 562 [0x00000232], Thread: 562 [0x0232]): Assertion failed 'compiler->compIsaSupportedDebugOnly(HWIntrinsicInfo::lookupIsa(intrin.id))' in 'MultiplyLongOpsTest:smnegl_single_cast(int,int,long)' during 'Generate code' (IL size 15; hash 0xe1d89229; FullOpts)

    File: /__w/1/s/src/coreclr/jit/hwintrinsiccodegenarm64.cpp Line: 210
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0xfffb6d6f5a78)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xfffb6d6f5a78)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/root/helix/work/workitem/e/JIT/opt/JIT.opt/../Multiply/MultiplyLongOps/MultiplyLongOps.sh: line 514:   562 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
__tmp0_MultiplyLongOps.cs:19:11: error: ARM64: expected string not found in input
 //ARM64: {{^ *}} smaddl {{x[0-9]+}}, {{w[0-9]+}}, {{w[0-9]+}}, {{x[0-9]+}}{{$}}
          ^
__jit_disasm.out:24:73: note: scanning from here
; BEGIN METHOD MultiplyLongOpsTest:smaddl_single_cast(int,int,long,long)
                                                                        ^
__jit_disasm.out:28:2: note: possible intended match here
 stp x19, x20, [sp, #0x10]
 ^

Input file: __jit_disasm.out
Check file: __tmp0_MultiplyLongOps.cs

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            1: ; Assembly listing for method MultiplyLongOpsTest:smaddl_single_cast(int,int,long,long) (FullOpts) 
            2: ; Emitting BLENDED_CODE for generic ARM64 - Unix 
            3: ; FullOpts code 
            4: ; optimized code 
            5: ; fp based frame 
            6: ; partially interruptible 
            7: ; No PGO data 
            8: ; 0 inlinees with PGO data; 6 single block inlinees; 1 inlinees without PGO data 
            9: ; Final local variable assignments 
           10: ; 
           11: ; V00 arg0 [V00,T02] ( 3, 3 ) int -> x0 single-def 
           12: ; V01 arg1 [V01,T03] ( 3, 3 ) int -> x1 single-def 
           13: ; V02 arg2 [V02,T04] ( 3, 3 ) long -> x2 single-def 
           14: ; V03 arg3 [V03,T05] ( 3, 3 ) long -> x19 single-def 
           15: ; V04 loc0 [V04,T08] ( 2, 2 ) long -> x20 single-def 
           16: ;# V05 OutArgs [V05 ] ( 1, 1 ) struct ( 0) [sp+0x00] do-not-enreg[XS] addr-exposed "OutgoingArgSpace" 
           17: ; V06 tmp1 [V06,T01] ( 3, 6 ) ref -> x22 class-hnd exact single-def "NewObj constructor temp" <Xunit.Sdk.AssertEqualityComparer`1[long]> 
           18: ;* V07 tmp2 [V07 ] ( 0, 0 ) ref -> zero-ref class-hnd exact "NewObj constructor temp" <Xunit.Sdk.AssertEqualityComparer`1+<>c__DisplayClass3_0[long]> 
           19: ; V08 tmp3 [V08,T06] ( 3, 3 ) ref -> x21 class-hnd exact single-def "Inline stloc first use temp" <Xunit.Sdk.AssertEqualityComparer`1+<>c__DisplayClass3_0[long]> 
           20: ; V09 tmp4 [V09,T00] ( 4, 8 ) ref -> x0 class-hnd exact single-def "NewObj constructor temp" <System.Func`1[System.Collections.IEqualityComparer]> 
           21: ; V10 cse0 [V10,T07] ( 3, 3 ) long -> x21 "CSE - aggressive" 
           22: ; 
           23: ; Lcl frame size = 0 
           24: ; BEGIN METHOD MultiplyLongOpsTest:smaddl_single_cast(int,int,long,long) 
check:19'0                                                                             X error: no match found
           25:  
check:19'0     ~
           26: G_M39709_IG01: 
check:19'0     ~~~~~~~~~~~~~~~
           27:  stp fp, lr, [sp, #-0x30]! 
check:19'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
           28:  stp x19, x20, [sp, #0x10] 
check:19'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:19'1      ?                          possible intended match
           29:  stp x21, x22, [sp, #0x20] 
check:19'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
           30:  mov fp, sp 
check:19'0     ~~~~~~~~~~~~
           31:  mov x19, x3 
check:19'0     ~~~~~~~~~~~~~
           32:  ;; size=20 bbWeight=1 PerfScore 4.00 
check:19'0     ~~~~~~~~~~~
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor294|0_295(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-09-23T20:51:04.825Z | runtime-coreclr jitstress-isas-arm | Checked-jitstress_isas_nohwintrinsic | osx.1200.arm64.open | arm64 | JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd | Failed | {"architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"416992","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"9130926","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20230923.1","configuration":"Checked-jitstress_isas_nohwintrinsic","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"116","DefinitionName":"runtime-coreclr jitstress-isas-arm","Reason":"Schedule","System.StageAttempt":"1","System.StageName":"Build"} | Schedule
2023-09-23T20:51:04.825Z | runtime-coreclr jitstress-isas-arm | Checked-jitstress_isas_nohwintrinsic | osx.1200.arm64.open | arm64 | JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd | Failed | {"architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"416992","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"9130926","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20230923.1","configuration":"Checked-jitstress_isas_nohwintrinsic","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"116","DefinitionName":"runtime-coreclr jitstress-isas-arm","Reason":"Schedule","System.StageAttempt":"1","System.StageName":"Build"} | Schedule
2023-09-23T20:51:04.825Z | runtime-coreclr jitstress-isas-arm | Checked-jitstress_isas_nohwintrinsic | osx.1200.arm64.open | arm64 | JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd | Failed | {"architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"416992","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"9130926","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20230923.1","configuration":"Checked-jitstress_isas_nohwintrinsic","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"116","DefinitionName":"runtime-coreclr jitstress-isas-arm","Reason":"Schedule","System.StageAttempt":"1","System.StageName":"Build"} | Schedule
2023-09-23T20:51:04.825Z | runtime-coreclr jitstress-isas-arm | Checked-jitstress_isas_nohwintrinsic | osx.1200.arm64.open | arm64 | JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd | Failed | {"architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"416992","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"9130926","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20230923.1","configuration":"Checked-jitstress_isas_nohwintrinsic","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"116","DefinitionName":"runtime-coreclr jitstress-isas-arm","Reason":"Schedule","System.StageAttempt":"1","System.StageName":"Build"} | Schedule
2023-09-23T20:51:04.825Z | runtime-coreclr jitstress-isas-arm | Checked-jitstress_isas_nohwintrinsic | osx.1200.arm64.open | arm64 | JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd | Failed | {"architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"416992","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"9130926","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20230923.1","configuration":"Checked-jitstress_isas_nohwintrinsic","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"116","DefinitionName":"runtime-coreclr jitstress-isas-arm","Reason":"Schedule","System.StageAttempt":"1","System.StageName":"Build"} | Schedule
2023-09-23T20:51:04.825Z | runtime-coreclr jitstress-isas-arm | Checked-jitstress_isas_nohwintrinsic | osx.1200.arm64.open | arm64 | JIT/opt/Multiply/MultiplyLongOps/MultiplyLongOps.cmd | Failed | {"architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","BuildId":"416992","System.PhaseAttempt":"1","AzurePipelinesTestRunId":"9130926","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildNumber":"20230923.1","configuration":"Checked-jitstress_isas_nohwintrinsic","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"116","DefinitionName":"runtime-coreclr jitstress-isas-arm","Reason":"Schedule","System.StageAttempt":"1","System.StageName":"Build"} | Schedule

**Comment by JulieLeeMSFT** [comment]
@kunalspathak, PTAL.

**Comment by kunalspathak** [comment]
@c272 @a74nh

**Comment by kunalspathak** [comment]
Fixed by https://github.com/dotnet/runtime/pull/92607
