### ISSUE TITLE
CreateCertificate_MicrosoftPlatformCryptoProvider_EcdsaKey fails with The requested operation is not supported

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#92623]
Ran outer loop tests on my Windows 11 22H2 machine with HEAD of 867f5d483e340af033f2ba83d29b21bab0e3bcb3
```xml
      <test name="System.Security.Cryptography.X509Certificates.Tests.CertTests.CreateCertificate_MicrosoftPlatformCryptoProvider_EcdsaKey" type="System.Security.Cryptography.X509Certificates.Tests.CertTests" method="CreateCertificate_MicrosoftPlatformCryptoProvider_EcdsaKey" time="0.0165974" result="Fail">
        <traits>
          <trait name="category" value="outerloop" />
        </traits>
        <failure exception-type="System.Security.Cryptography.CryptographicException">
          <message><![CDATA[System.Security.Cryptography.CryptographicException : The requested operation is not supported.]]></message>
          <stack-trace><![CDATA[   at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters) in C:\git\runtime\src\libraries\System.Security.Cryptography\src\System\Security\Cryptography\CngKey.Create.cs:line 49
   at Test.Cryptography.CngPlatformProviderKey..ctor(CngAlgorithm algorithm, String keySuffix, String testName, CngProperty[] additionalParameters) in C:\git\runtime\src\libraries\Common\tests\System\Security\Cryptography\CngPlatformProviderKey.cs:line 29
   at System.Security.Cryptography.X509Certificates.Tests.CertTests.CreateCertificate_MicrosoftPlatformCryptoProvider_EcdsaKey() in C:\git\runtime\src\libraries\System.Security.Cryptography\tests\X509Certificates\CertTests.cs:line 608
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\MethodBaseInvoker.cs:line 57]]></stack-trace>
        </failure>
      </test>
```
the failure is 
```c#
            using (CngPlatformProviderKey platformKey = new CngPlatformProviderKey(CngAlgorithm.ECDsaP384))
```

Is there some check that can be made that the OS supports this algorithm?

BTW, this message (system message for 0x80090029) is not super helpful, I wonder whether we should add some possible causes to the message.

**Comment by danmoseley** [comment]
this one apparently needs the same guard.
```
      <test name="System.Security.Cryptography.Cng.Tests.PropertyTests.CreatePersisted_PlatformEccKeyHasKeySize(algorithm: \&quot;ECDH_P384\&quot;, expectedKeySize: 384)" type="System.Security.Cryptography.Cng.Tests.PropertyTests" method="CreatePersisted_PlatformEccKeyHasKeySize" time="0.2592442" result="Fail">
        <traits>
          <trait name="category" value="outerloop" />
        </traits>
        <failure exception-type="System.Security.Cryptography.CryptographicException">
          <message><![CDATA[System.Security.Cryptography.CryptographicException : The requested operation is not supported.]]></message>
          <stack-trace><![CDATA[   at System.Security.Cryptography.CngKey.Create(CngAlgorithm algorithm, String keyName, CngKeyCreationParameters creationParameters) in C:\git\runtime\src\libraries\System.Security.Cryptography\src\System\Security\Cryptography\CngKey.Create.cs:line 49
   at Test.Cryptography.CngPlatformProviderKey..ctor(CngAlgorithm algorithm, String keySuffix, String testName, CngProperty[] additionalParameters) in C:\git\runtime\src\libraries\Common\tests\System\Security\Cryptography\CngPlatformProviderKey.cs:line 29
   at System.Security.Cryptography.Cng.Tests.PropertyTests.CreatePersisted_PlatformEccKeyHasKeySize(String algorithm, Int32 expectedKeySize) in C:\git\runtime\src\libraries\System.Security.Cryptography.Cng\tests\PropertyTests.cs:line 22
   at InvokeStub_PropertyTests.CreatePersisted_PlatformEccKeyHasKeySize(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
```
