### ISSUE TITLE
Updating published Blazor WebAssembly application from .NET 7 to .NET8 preview crashes with: Cannot read properties of undefined (reading 'dotnet.wasm')

### ISSUE THREAD

**Issue by pekspro** [dotnet/runtime#92697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have published an .NET 7 Blazor WebAssembly application, and run in a browser. And then updates to .NET 8 preview the application will crash in the browser:

```
blazor.webassembly.js:1  Error: Failed to start platform. Reason: TypeError: Cannot read properties of undefined (reading 'dotnet.wasm')
    at Vt (blazor.webassembly.js:1:62226)
(anonymous) @ blazor.webassembly.js:1

Promise.catch (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
blazor.webassembly.js:1  Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at blazor.webassembly.js:1:37659
    at blazor.webassembly.js:1:38464
    at Object.start (blazor.webassembly.js:1:46018)
    at Vt (blazor.webassembly.js:1:62202) 
```

![image](https://github.com/dotnet/aspnetcore/assets/3163293/1b25c337-7e1c-4f56-b28d-0c8f9dd78922)

Clearing caches fixes the problem.

### Expected Behavior

The application should not crash, and automatically update the caches.

### Steps To Reproduce

* Create a new .NET 7 Blazor WebAssembly application
* Publish the application to Azure App Service.
* Start the application in a lot of browsers. It feels like this is easier to get in a mobile, but not sure.
* Update the application to .NET 8 preview.

```XML
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-rc.1.23421.29" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-rc.1.23421.29" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

* Publish the application again.
* Update the application in the browser.
* The application will now not load.

### .NET Version

8.0.100-rc.1.23455.8

### Anything else?

Clearing the storage cache and a hard reload (Ctrl+F5) fixes the issue:

https://user-images.githubusercontent.com/3163293/269350678-66df8ae0-8bc2-427f-97ca-2c5e0c5d26f8.png

This can also be solved with JavaScript. Update the index.html with this:

```HTML
<div id="app">
    <svg class="loading-progress">
        <circle r="40%" cx="50%" cy="50%" />
        <circle r="40%" cx="50%" cy="50%" />
    </svg>
    <div class="loading-progress-text"></div>
    <div class="loading-reload-text">
        <a href="#" id="reload-link">Reload</a>
    </div>

    <script>
        document.getElementById('reload-link').addEventListener('click', function (event) {
            event.preventDefault();

            caches.keys().then(function (cacheNames) {
                return Promise.all(
                    cacheNames.map(function (cacheName) {
                        return caches.delete(cacheName);
                    })
                );
            }).then(function () {
                window.location.reload(true);
            });
        });
    </script>
</div>
```

And add this CSS.

```CSS
.loading-reload-text {
    text-align: center;
    opacity: 0;
    animation: loading-reload-fade-in 1s ease-in-out 4s forwards;
}

@keyframes loading-reload-fade-in {
    from {
        opacity: 0;
    }

    to {
        opacity: 1;
    }
}

.loading-reload-text a {
    font-weight: 300;
    font-size: 90%;
}
```

**Comment by radical** [comment]
cc @maraf @pavelsavara

**Comment by pavelsavara** [comment]
> A hard reload (Ctrl+F5) solves that issue.

I agree with Javier, this is caching issue. 
We have brief advisory about caching here https://github.com/dotnet/runtime/blob/main/src/mono/wasm/features.md#caching-and-integrity

**Comment by pavelsavara** [comment]
@maraf @javiercn I remeber we droped version sufix from `dotnet.js` because you are not loading the boot config anymore.
What made the `blazor.boot.json` to not get stale in similar situations in Net7 ?

**Comment by jamescarter-le** [comment]
Same issue here, when trying to `start` the application the issue is that `e.bootConfig.resources.runtime` is null:

`const t = Object.keys(e.bootConfig.resources.runtime).filter((e=>e.startsWith("dotnet.") && e.endsWith(".js")))[0]`

**Comment by Grizzlly** [comment]
I am getting this error when I am trying to load Blazor WASM as a Chrome Extension. The culprit is what @jamescarter-le pointed out.

**Comment by maraf** [comment]
```
blazor.webassembly.js:1  Error: Failed to start platform. Reason: TypeError: Cannot read properties of undefined (reading 'dotnet.wasm')
```

I have checked the scenario locally, the error message comes from stale version of `blazor.webassembly.js`. Correct version of `blazor.boot.json` is downloaded, but `blazor.webassembly.js` is served from the cache. Tested locally with `dotnet serve`.

**Comment by maraf** [comment]
> Same issue here, when trying to `start` the application the issue is that `e.bootConfig.resources.runtime` is null:
> 
> `const t = Object.keys(e.bootConfig.resources.runtime).filter((e=>e.startsWith("dotnet.") && e.endsWith(".js")))[0]`

That's a different error for the same symptom

**Comment by pekspro** [comment]
@maraf, I host the app in Azure App Service. On Windows, with the free tier.

**Comment by maraf** [comment]
> @maraf, I host the app in Azure App Service. On Windows, with the free tier.

So the blazor wasm app is hosted from ASP.NET Core server app?

**Comment by pekspro** [comment]
@maraf, no, it's a Blazor WebAssembly application (I mentioned the details in the original post).

**Comment by pavelsavara** [comment]
@pekspro we want to understand what's the the HTTP server and it's configuration. Because that matters for the caching in the browser.

**Comment by pekspro** [comment]
@pavelsavara, @maraf  I created a new one. This is the URL:

https://blazorupdatetest20231004.azurewebsites.net/

I created it with the publish wizard in Visual Studio. I'm using the default settings for everything.

![image](https://github.com/dotnet/runtime/assets/3163293/e1115ac9-f583-4486-8e59-d9a93c3efdfc)

![image](https://github.com/dotnet/runtime/assets/3163293/50a9099e-662f-4593-a36a-0301d0c2086a)

![image](https://github.com/dotnet/runtime/assets/3163293/f7ee407b-cea5-4113-bc32-126a16c3c355)

![image](https://github.com/dotnet/runtime/assets/3163293/846a7e50-328a-4ed5-92b8-9ef45e6004b0)


This is the publishing settings:

![image](https://github.com/dotnet/runtime/assets/3163293/aeb47b7a-d793-4c2b-99a3-29c108a8e3d8)

![image](https://github.com/dotnet/runtime/assets/3163293/babb9dc5-c3a4-4e5d-9383-ebc2de1a4335)

Here it has failed in four different browsers:

![image](https://github.com/dotnet/runtime/assets/3163293/fa983eec-bd27-42c2-bc1a-324f76a4212e)


And here is an ARM-template for the service:

```text
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "sites_BlazorUpdateTest20231004_name": {
            "defaultValue": "BlazorUpdateTest20231004",
            "type": "String"
        },
        "serverfarms_BlazorUpdateTest20231004_externalid": {
            "defaultValue": "/subscriptions/54a74381-8a65-4500-91b0-85a187c27cab/resourceGroups/HelixDevPek/providers/Microsoft.Web/serverfarms/BlazorUpdateTest20231004",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Web/sites",
            "apiVersion": "2022-09-01",
            "name": "[parameters('sites_BlazorUpdateTest20231004_name')]",
            "location": "North Europe",
            "tags": {
                "hidden-related:/subscriptions/54a74381-8a65-4500-91b0-85a187c27cab/resourceGroups/HelixDevPek/providers/Microsoft.Web/serverFarms/BlazorUpdateTest20231004": "empty"
            },
            "kind": "app",
            "identity": {
                "type": "SystemAssigned"
            },
            "properties": {
                "enabled": true,
                "hostNameSslStates": [
                    {
                        "name": "blazorupdatetest20231004.azurewebsites.net",
                        "sslState": "Disabled",
                        "hostType": "Standard"
                    },
                    {
                        "name": "blazorupdatetest20231004.scm.azurewebsites.net",
                        "sslState": "Disabled",
                        "hostType": "Repository"
                    }
                ],
                "serverFarmId": "[parameters('serverfarms_BlazorUpdateTest20231004_externalid')]",
                "reserved": false,
                "isXenon": false,
                "hyperV": false,
                "vnetRouteAllEnabled": false,
                "vnetImagePullEnabled": false,
                "vnetContentShareEnabled": false,
                "siteConfig": {
                    "numberOfWorkers": 1,
                    "acrUseManagedIdentityCreds": false,
                    "alwaysOn": false,
                    "http20Enabled": false,
                    "functionAppScaleLimit": 0,
                    "minimumElasticInstanceCount": 0
                },
                "scmSiteAlsoStopped": false,
                "clientAffinityEnabled": true,
                "clientCertEnabled": false,
                "clientCertMode": "Required",
                "hostNamesDisabled": false,
                "customDomainVerificationId": "886FDFA6A573582ACE4AE24CF190ACE9F124793618E02C42F260D1B5FEA957D4",
                "containerSize": 0,
                "dailyMemoryTimeQuota": 0,
                "httpsOnly": true,
                "redundancyMode": "None",
                "storageAccountRequired": false,
                "keyVaultReferenceIdentity": "SystemAssigned"
            }
        },
        {
            "type": "Microsoft.Web/sites/basicPublishingCredentialsPolicies",
            "apiVersion": "2022-09-01",
            "name": "[concat(parameters('sites_BlazorUpdateTest20231004_name'), '/ftp')]",
            "location": "North Europe",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('sites_BlazorUpdateTest20231004_name'))]"
            ],
            "tags": {
                "hidden-related:/subscriptions/54a74381-8a65-4500-91b0-85a187c27cab/resourceGroups/HelixDevPek/providers/Microsoft.Web/serverFarms/BlazorUpdateTest20231004": "empty"
            },
            "properties": {
                "allow": true
            }
        },
        {
            "type": "Microsoft.Web/sites/basicPublishingCredentialsPolicies",
            "apiVersion": "2022-09-01",
            "name": "[concat(parameters('sites_BlazorUpdateTest20231004_name'), '/scm')]",
            "location": "North Europe",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('sites_BlazorUpdateTest20231004_name'))]"
            ],
            "tags": {
                "hidden-related:/subscriptions/54a74381-8a65-4500-91b0-85a187c27cab/resourceGroups/HelixDevPek/providers/Microsoft.Web/serverFarms/BlazorUpdateTest20231004": "empty"
            },
            "properties": {
                "allow": true
            }
        },
        {
            "type": "Microsoft.Web/sites/config",
            "apiVersion": "2022-09-01",
            "name": "[concat(parameters('sites_BlazorUpdateTest20231004_name'), '/web')]",
            "location": "North Europe",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('sites_BlazorUpdateTest20231004_name'))]"
            ],
            "tags": {
                "hidden-related:/subscriptions/54a74381-8a65-4500-91b0-85a187c27cab/resourceGroups/HelixDevPek/providers/Microsoft.Web/serverFarms/BlazorUpdateTest20231004": "empty"
            },
            "properties": {
                "numberOfWorkers": 1,
                "defaultDocuments": [
                    "Default.htm",
                    "Default.html",
                    "Default.asp",
                    "index.htm",
                    "index.html",
                    "iisstart.htm",
                    "default.aspx",
                    "index.php",
                    "hostingstart.html"
                ],
                "netFrameworkVersion": "v7.0",
                "phpVersion": "5.6",
                "requestTracingEnabled": false,
                "remoteDebuggingEnabled": false,
                "httpLoggingEnabled": false,
                "acrUseManagedIdentityCreds": false,
                "logsDirectorySizeLimit": 35,
                "detailedErrorLoggingEnabled": false,
                "publishingUsername": "$BlazorUpdateTest20231004",
                "scmType": "None",
                "use32BitWorkerProcess": true,
                "webSocketsEnabled": false,
                "alwaysOn": false,
                "managedPipelineMode": "Integrated",
                "virtualApplications": [
                    {
                        "virtualPath": "/",
                        "physicalPath": "site\\wwwroot",
                        "preloadEnabled": false
                    }
                ],
                "loadBalancing": "LeastRequests",
                "experiments": {
                    "rampUpRules": []
                },
                "autoHealEnabled": false,
                "vnetRouteAllEnabled": false,
                "vnetPrivatePortsCount": 0,
                "localMySqlEnabled": false,
                "managedServiceIdentityId": 12794,
                "ipSecurityRestrictions": [
                    {
                        "ipAddress": "Any",
                        "action": "Allow",
                        "priority": 2147483647,
                        "name": "Allow all",
                        "description": "Allow all access"
                    }
                ],
                "scmIpSecurityRestrictions": [
                    {
                        "ipAddress": "Any",
                        "action": "Allow",
                        "priority": 2147483647,
                        "name": "Allow all",
                        "description": "Allow all access"
                    }
                ],
                "scmIpSecurityRestrictionsUseMain": false,
                "http20Enabled": false,
                "minTlsVersion": "1.2",
                "scmMinTlsVersion": "1.2",
                "ftpsState": "FtpsOnly",
                "preWarmedInstanceCount": 0,
                "elasticWebAppScaleLimit": 0,
                "functionsRuntimeScaleMonitoringEnabled": false,
                "minimumElasticInstanceCount": 0,
                "azureStorageAccounts": {}
            }
        },
        {
            "type": "Microsoft.Web/sites/hostNameBindings",
            "apiVersion": "2022-09-01",
            "name": "[concat(parameters('sites_BlazorUpdateTest20231004_name'), '/', parameters('sites_BlazorUpdateTest20231004_name'), '.azurewebsites.net')]",
            "location": "North Europe",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('sites_BlazorUpdateTest20231004_name'))]"
            ],
            "properties": {
                "siteName": "BlazorUpdateTest20231004",
                "hostNameType": "Verified"
            }
        },
        {
            "type": "Microsoft.Web/sites/siteextensions",
            "apiVersion": "2022-09-01",
            "name": "[concat(parameters('sites_BlazorUpdateTest20231004_name'), '/Microsoft.AspNetCore.AzureAppServices.SiteExtension')]",
            "location": "North Europe",
            "dependsOn": [
                "[resourceId('Microsoft.Web/sites', parameters('sites_BlazorUpdateTest20231004_name'))]"
            ]
        }
    ]
}
```

I can you more if you need to. But you should able to replicate in a couple of minutes.

**Comment by pekspro** [comment]
I noticed something interesting. I did a soft refesh in Edge and the page failed loading again. Then I did a hard refresh, and the application was loaded.

I few minutes later I did a soft refresh in the other browser. Then the application worked in Chrome and Firefix, but it was still failing in Brave. The is the request for blazor.webassembly.js:

![image](https://github.com/dotnet/runtime/assets/3163293/fdf5e07a-ec5c-4d6c-a171-b64a05202691)

And this is in Chrome:

![image](https://github.com/dotnet/runtime/assets/3163293/9def2ad9-dbbb-454b-9548-49048ea1cc63)

**Comment by pavelsavara** [comment]
So it's `Microsoft-IIS/10.0` + `ASP.NET`

There is `ETag` but I don't see any `Cache-Control` and therefore subsequent load is from browser cache.

![image](https://github.com/dotnet/runtime/assets/271576/83782485-1959-44ce-80ef-bab6f6dbff71)

![image](https://github.com/dotnet/runtime/assets/271576/5b052ec2-44a0-4de6-b824-4255525761ae)

**Comment by pavelsavara** [comment]
@javiercn this is not runtime issue, could you guys please take over ?

I think better documentation on how to host Blazor on Azure could help. Or even specific ARM template.
