### ISSUE TITLE
[mono][tests] The type initializer for 'NetSecurityNative' threw an exception

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#93104]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=429167&view=logs&j=ab306dbd-9f73-5131-57d7-1eb5f5188356&t=15d6e221-840c-5f04-2f14-457f5a7ff25b
Build error leg or test failing: linux_bionic-x64 Release AllSubsets_Mono

```
System.TypeInitializationException : The type initializer for 'NetSecurityNative' threw an exception.
            ---- System.TypeInitializationException : The type initializer for 'GssInitializer' threw an exception.
            -------- System.DllNotFoundException : libSystem.Net.Security.Native
            Stack Trace:
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(79,0): at Interop.NetSecurityNative.GssApiException.GetGssApiDisplayStatus(Status status, Boolean isMinor)
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(47,0): at Interop.NetSecurityNative.GssApiException.GetGssApiDisplayStatus(Status majorStatus, Status minorStatus, String helpText)
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(39,0): at Interop.NetSecurityNative.GssApiException..ctor(Status majorStatus, Status minorStatus, String helpText)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(201,0): at System.Net.NegotiateAuthenticationPal.UnixNegotiateAuthenticationPal..ctor(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(43,0): at System.Net.NegotiateAuthenticationPal.Create(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/src/System/Net/Security/NegotiateAuthentication.cs(42,0): at System.Net.Security.NegotiateAuthentication..ctor(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/tests/UnitTests/NegotiateAuthenticationTests.cs(103,0): at System.Net.Security.Tests.NegotiateAuthenticationTests.DefaultNetworkCredentials_NTLM_DoesNotThrow()
              /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
              /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
              ----- Inner Stack Trace -----
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs(20,0): at Interop.NetSecurityNative..cctor()
              ----- Inner Stack Trace -----
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs(27,0): at Interop.NetSecurityNative.GssInitializer..cctor()
          System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmCorrectExchangeTest [SKIP]
            Condition(s) not met: "IsNtlmAvailable (TargetInvocationException)"
          System.Net.Security.Tests.NegotiateAuthenticationTests.Package_Unsupported_NTLM [SKIP]
            Condition(s) not met: "IsNtlmUnavailable (TargetInvocationException)"
          System.Net.Security.Tests.NegotiateAuthenticationTests.Package_Supported_NTLM [SKIP]
            Condition(s) not met: "IsNtlmAvailable (TargetInvocationException)"
          System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmSignatureTest [SKIP]
            Condition(s) not met: "IsNtlmAvailable (TargetInvocationException)"
            System.TypeInitializationException : The type initializer for 'NetSecurityNative' threw an exception.
            ---- System.TypeInitializationException : The type initializer for 'GssInitializer' threw an exception.
            -------- System.DllNotFoundException : libSystem.Net.Security.Native
            Stack Trace:
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(79,0): at Interop.NetSecurityNative.GssApiException.GetGssApiDisplayStatus(Status status, Boolean isMinor)
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(47,0): at Interop.NetSecurityNative.GssApiException.GetGssApiDisplayStatus(Status majorStatus, Status minorStatus, String helpText)
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(32,0): at Interop.NetSecurityNative.GssApiException..ctor(Status majorStatus, Status minorStatus)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(507,0): at System.Net.NegotiateAuthenticationPal.UnixNegotiateAuthenticationPal.AcquireCredentialsHandle(NetworkCredential credential)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(213,0): at System.Net.NegotiateAuthenticationPal.UnixNegotiateAuthenticationPal..ctor(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(43,0): at System.Net.NegotiateAuthenticationPal.Create(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/src/System/Net/Security/NegotiateAuthentication.cs(42,0): at System.Net.Security.NegotiateAuthentication..ctor(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/tests/UnitTests/NegotiateAuthenticationTests.cs(38,0): at System.Net.Security.Tests.NegotiateAuthenticationTests.RemoteIdentity_ThrowsOnUnauthenticated()
              /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
              /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
              ----- Inner Stack Trace -----
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs(20,0): at Interop.NetSecurityNative..cctor()
              ----- Inner Stack Trace -----
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs(27,0): at Interop.NetSecurityNative.GssInitializer..cctor()
          System.Net.Security.Tests.NegotiateAuthenticationTests.NtlmIncorrectExchangeTest [SKIP]
            Condition(s) not met: "IsNtlmAvailable (TargetInvocationException)"
            System.TypeInitializationException : The type initializer for 'NetSecurityNative' threw an exception.
            ---- System.TypeInitializationException : The type initializer for 'GssInitializer' threw an exception.
            -------- System.DllNotFoundException : libSystem.Net.Security.Native
            Stack Trace:
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(79,0): at Interop.NetSecurityNative.GssApiException.GetGssApiDisplayStatus(Status status, Boolean isMinor)
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(47,0): at Interop.NetSecurityNative.GssApiException.GetGssApiDisplayStatus(Status majorStatus, Status minorStatus, String helpText)
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.GssApiException.cs(32,0): at Interop.NetSecurityNative.GssApiException..ctor(Status majorStatus, Status minorStatus)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(472,0): at System.Net.NegotiateAuthenticationPal.UnixNegotiateAuthenticationPal.GetPackageType(String package)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(187,0): at System.Net.NegotiateAuthenticationPal.UnixNegotiateAuthenticationPal..ctor(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs(43,0): at System.Net.NegotiateAuthenticationPal.Create(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/src/System/Net/Security/NegotiateAuthentication.cs(42,0): at System.Net.Security.NegotiateAuthentication..ctor(NegotiateAuthenticationClientOptions clientOptions)
              /_/src/libraries/System.Net.Security/tests/UnitTests/NegotiateAuthenticationTests.cs(71,0): at System.Net.Security.Tests.NegotiateAuthenticationTests.Package_Unsupported()
              /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
              /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
              ----- Inner Stack Trace -----
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs(20,0): at Interop.NetSecurityNative..cctor()
              ----- Inner Stack Trace -----
              /_/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.IsNtlmInstalled.cs(27,0): at Interop.NetSecurityNative.GssInitializer..cctor()
        Finished:    System.Net.Security.Unit.Tests
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "The type initializer for 'NetSecurityNative' threw an exception",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by rzikm** [comment]
Triage: Test failure, Should investigate in 9.0 timeframe

**Comment by wfurt** [comment]
Is this what #92830 was trying to fix @steveisok?  It seems like the suggestions from there should still be applicable, right? e.g. using managed implementation instead of GSS. Is there some way how to tag Bionic specific issues?
