### ISSUE TITLE
Hot reload - EnC: we do not support patching of existing PARAM table cols. token=0x08000d0e

### ISSUE THREAD

**Issue by solbster** [dotnet/runtime#93149]
### Description

I have a large Blazor wasm hosted app and hot reload stopped working for some time ago.

```
Error: System.TypeLoadException: EnC: we do not support patching of existing PARAM table cols. token=0x08000d0e
   at System.Reflection.Metadata.MetadataUpdater.ApplyUpdate(:5001/Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.Extensions.HotReload.HotReloadAgent.ApplyDeltas(:5001/IReadOnlyList`1 deltas)
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.ApplyHotReloadDelta(:5001/String moduleIdString, Byte[] metadataDelta, Byte[] ilDelta, Byte[] pdbBytes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(:5001/JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(:5001/JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(:5001/String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at qi (dotnet.7.0.11.sf8asx8yhf.js:5:80665)
    at Ji (dotnet.7.0.11.sf8asx8yhf.js:5:80549)
    at _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:30:5)
    at Object.invokeDotNetFromJS (blazor.webassembly.js:1:45224)
    at g (blazor.webassembly.js:1:1621)
    at e.invokeMethod (blazor.webassembly.js:1:2670)
    at Vt.Ke._internal.applyHotReload (blazor.webassembly.js:1:58767)
    at aspnetcore-browser-refresh.js:140:35
    at Array.forEach (<anonymous>)
    at applyBlazorDeltas (aspnetcore-browser-refresh.js:138:14)
```

### Reproduction Steps

Not possible, my app to large.

### Expected behavior

Hot reload should complete and refresh the browser.

### Actual behavior

Need to stop and start the project again.

### Configuration

Windows 11
Visual Studio v17.7.4
MS project assemblys v7.0.11
MudBlazor v6.11.0

### Other information
Hot-reload is executed from Visual Studio and debug-mode
_No response_

**Comment by solbster** [comment]
21:34 38.92 MyApp.Server (Web assembly): Sending updates to running application
21:34 38.97 MyApp.Server (Web assembly): [Error] Applying updates failed: 
21:34 38.97 MyApp.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application. 
21:34 38.97 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application. 
21:34 38.97 Stack trace for WebToolsException:
   at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.<ApplyUpdatesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.<LogOnExceptionAsync>d__3.MoveNext()
21:34 38.99 An unexpected error has occurred, any pending updates have been discarded.

**Comment by marek-safar** [comment]
@lambdageek PTAL

**Comment by SamMonoRT** [comment]
@solbster - it would be helpful if you noted down dotnet versions when you encountered this, and possibly if you can gather information when this was working for you.

**Comment by lambdageek** [comment]
the weird thing is we don't advertise that we support renaming parameters in net7. so unclear why roslyn sends us such a change anyway

**Comment by lambdageek** [comment]
Hmm. Tried `dotnet watch` with the .NET 7 SDK. adding/modifying/removing custom attributes doesn't do it. renaming params with net7 is a rude edit as expected.

@solbster are you doing hot reload with `dotnet watch` or with Visual Studio on Windows?  What version of Visual Studio are you using?

**Comment by solbster** [comment]
> Hmm. Tried `dotnet watch` with the .NET 7 SDK. adding/modifying/removing custom attributes doesn't do it. renaming params with net7 is a rude edit as expected.
> 
> @solbster are you doing hot reload with `dotnet watch` or with Visual Studio on Windows? What version of Visual Studio are you using?

@lambdageek 

I'm using the latest version of Visual Studio (Version 17.7.4), and my operating system is Windows 11 with the latest updates. I'm utilizing hot-reload from Visual Studio while in debug mode.

I've even reinstalled my PC with Windows 11 and performed a fresh installation of Windows 11 with all the latest updates. All the packages in my project are up to the latest available versions.

**Comment by lambdageek** [comment]
@solbster Thanks for the quick reply.  Can you give me an example of the kind of change you're making that results in this error?  

Here are some things I tried.

I created 

```csharp
[AttributeUsage(AttributeTargets.All, AllowMultiple =true, Inherited = false)]
    class MyFavoriteAttribute : Attribute {
        public MyFavoriteAttribute (string xyz) { this.Xyz = xyz; }
        public string Xyz { get; }
    }
```

* Created a method in the `@code` section of a razor page `void UpdateCounter([MyFavorite("abc")] ref int counter) { counter ++; }` and called it from some other code in the razor page.
* Started `dotnet watch` and tried the following kinds of edits:
   * Changed `[MyFavorite("abc")]` to `[MyFavorite("def")]`
   * Removed `[MyFavorite("def")]`
   * Added `[MyFavorite("123")]`
   * Renamed `ref int counter` to `ref int counter2` (rude edit - app restarted).

Questions:
1. Are you editing a .cs file or a .razor file.  If it's a razor file, are you chaning `@code` (or other C# code) or razor markup.
2. If you're changing C# code, what kind of change are you making? are oyu editing a lambda or a static/instance method? is it an async method?
3. If editing razor markup, is the markup at the toplevel or in the child content of another component?
4. If editing razor markup, what exactly are you doing? adding/modifying html  or adding/modifying a component.  Are you editing the attributes or child content? Are you editing `@bind` `@onclick` or some other special razor attribute?


> I'm using the latest version of Visual Studio (Version 17.7.4), and my operating system is Windows 11 with the latest updates. I'm utilizing hot-reload from Visual Studio while in debug mode.
> 
> I've even reinstalled my PC with Windows 11 and with all the latest updates. Performed a fresh installation of Visual Studio . All the packages in my project are up to the latest available versions.
> 
> When running from dotnet watch, in the console it says success, but it throws the same exception in the browser. (System.TypeLoadException: EnC: we do not support patching of existing PARAM table cols. token=0x080008b7)

**Comment by solbster** [comment]
@lambdageek 

I'm only modifying the HTML code using MudBlazor components. This can involve changing the text within a <MudText></MudText> component or adjusting the size of a <MudImage> component. I'm not making any changes within the @code{} block.

Example

<MudText>1</MudText> @*Hot-reload OK*@
<MudText>2</MudText> @*Hot-reload OK*@
<MudText>3</MudText> @*Hot-reload throws :
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to set property 'ChildContent' on object of type 'MudBlazor.MudText'. The error was: Specified cast is not valid.
System.InvalidOperationException: Unable to set property 'ChildContent' on object of type 'MudBlazor.MudText'. The error was: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[MudText,RenderFragment](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)

*@


@code
{}

**Comment by lambdageek** [comment]
Tried changing/adding/removing size, alignment and content of a MudText component.  Changes applied cleanly.

Can you share some of your layout?

**Comment by solbster** [comment]
> lambdageek

@lambdageek 

I've uploaded some files for you to review on my private GitHub repository. You should now have access to the repository and the files I've added.

**Comment by lambdageek** [comment]
Thank you! I'll take a look tomorrow

**Comment by lambdageek** [comment]
@solbster No luck.  I tried the files from the private repo (had to make some placeholders for the app model, but it wasn't too bad). and when I am changing the `MudText` components in `Index.razor` in a hot reload session, everything works, I can change the text content or the `Typo` and `Style` attributes.

can you try opening the developer tools in the browser and go to the Application tab and in the Storage section click "Clear site data" and then ensure on the "Network" tab that "Disable cache" is checked and then hit reload.

**Comment by solbster** [comment]
@lambdageek Tried with your suggestion, but without any luck. Getting this error:
`dotnet.7.0.12.cd75lmyo37.js:5  [MONO] /__w/1/s/src/mono/mono/metadata/custom-attrs.c:1936 <disabled>

Module._mono_wasm_invoke_method_ref @ dotnet.7.0.12.cd75lmyo37.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:29
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
invokeMethodAsync @ blazor.webassembly.js:1
resizeHandler @ MudBlazor.min.js:7
setTimeout (async)
throttleResizeHandler @ MudBlazor.min.js:7
blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly '0, Version=6.11.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly '0, Version=6.11.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: '0, Version=6.11.0.0, Culture=neutral, PublicKeyToken=null'
   at MyApp.Client.Pages.Index.<BuildRenderTree>b__0_5(RenderTreeBuilder )
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at MudBlazor.MudHidden.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)`

**Comment by lambdageek** [comment]
Why is it loading Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer 6.11 ?? that's kind of strange

**Comment by solbster** [comment]
Yeah i know, its very strange. 

I removed Localization, SignalR, AnimatedCheckMark, OnLocaltionChanged, WebAssemblyHostExtensions and CustomHttpClientHandler, but i'm still get the same errors.

**Comment by solbster** [comment]
When starting the application through debug i can see this error.

```
browserLink:21 
        
GET http://localhost:54928/1c8e9c7cb6954a1c80ebdb446122bdb6/browserLinkSignalR/negotiate?requestUrl=https%3A%2F%2Flocalhost%3A5001%2F&browserName=&userAgent=Mozilla%2F5.0+(Linux%3B+Android+10%3B+SM-G981B)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F80.0.3987.162+Mobile+Safari%2F537.36+Edg%2F117.0.0.0&browserIdKey=window.browserLink.initializationData.browserId&browserId=56df-9eae&clientProtocol=1.3&_=1697136087929 net::ERR_CONNECTION_REFUSED
```

After changing a class from Class="mt-5" to mt-3 for a MudButton i get this:

```
dotnet.7.0.12.cd75lmyo37.js:5  Error: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/interp-internals.h:351

    at xe (dotnet.7.0.12.cd75lmyo37.js:5:509)
    at Object.je (dotnet.7.0.12.cd75lmyo37.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.12.cd75lmyo37.js:14:104923)
    at 00993936:0x9bf9
    at 00993936:0xa5a31
    at 00993936:0x1c01c0
    at 00993936:0x1c024f
    at 00993936:0x1c02b8
    at 00993936:0x1db49
    at 00993936:0x2a50f

```

**Comment by solbster** [comment]
@lambdageek, hot-reload has started working again. I don't have an explanation for this, but the only thing I can think of is that new Windows updates were installed.

**Comment by lambdageek** [comment]
@solbster strange.  I'm going to close the issue for now; please ping me or open a new issue if the problem shows up again.  Thanks for helping me to investigate it!
