### ISSUE TITLE
Test failure GC\\Features\\HeapExpansion\\plug\\plug.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93162]
**Failed in:** [runtime-coreclr pgo 20230930.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423526&view=ms.vss-test-web.build-test-results-tab&runId=9309998&resultId=120138&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked defaultpgo @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 
Assert failure(PID 944 [0x000003b0], Thread: 4900 [0x1324]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x7012963d)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x70129d59)
CORECLR! PinObject + 0xF3 (0x700f3813)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x700f2684)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x700f21b9)
CORECLR! ProcessScanQNode + 0x32 (0x700f2552)
CORECLR! ProcessScanQueue + 0x2E (0x700f2591)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x700f2bc4)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x700f2a35)
CORECLR! TableScanHandles + 0xB0 (0x700f28f0)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x700f2ae7)
CORECLR! HndScanHandlesForGC + 0x139 (0x700f07a3)
CORECLR! Ref_TracePinningRoots + 0xC8 (0x700f4f0a)
CORECLR! GCScan::GcScanHandles + 0x64 (0x700f7877)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E7 (0x701288fa)
CORECLR! WKS::gc_heap::gc1 + 0x13B (0x70132b3f)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x7012af19)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x7012b0c7)
CORECLR! <lambda_50537d1654603c60e9d825b89783fd7d>::operator() + 0x84 (0x6feeb70f)
-----
.AV on tid=0x1324 (4900), cxr=0950ECB8, exr=0950EC68
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x7015d3e0)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6fd15e89)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6fd15b7e)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x6fd15b24)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x6fd160aa)
NTDLL! WinSqmEventWrite + 0x1C21A (0x7716f95a)
NTDLL! RtlUnwind + 0x1BA (0x7713011a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x77140dbf)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x70129d59)
CORECLR! PinObject + 0xF3 (0x700f3813)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7177
    Image: C:\h\w\B56E09D3\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B56E09D3\w\AD9809B7\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B56E09D3\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 9/30/2023 9:54:11 AM
Processing C:\cores\corerun.exe.944.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B56E09D3\t\tmpow01t5.tmp" -z "C:\cores\corerun.exe.944.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.944.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B56E09D3\p\PDB
Symbol search path is: C:\h\w\B56E09D3\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sat Sep 30 09:54:23.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:08:09.413
Process Uptime: 0 days 0:00:12.000
.................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored 
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by jkotas** [comment]
This has been failing intermittently for a while. Previous issue tracking this failure https://github.com/dotnet/runtime/issues/88977

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr jitstressregs-x86 20231224.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508345&view=ms.vss-test-web.build-test-results-tab&runId=11870994&resultId=120660&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstressregs0x10_x86_noavx @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 Assert failure(PID 6580 [0x000019b4], Thread: 6692 [0x1a24]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x6ffee484)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x6ffeeb99)
CORECLR! PinObject + 0xF3 (0x6ffb8603)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x6ffb7464)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x6ffb6f99)
CORECLR! ProcessScanQNode + 0x32 (0x6ffb7332)
CORECLR! ProcessScanQueue + 0x2E (0x6ffb7371)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x6ffb79b4)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x6ffb7825)
CORECLR! TableScanHandles + 0xB0 (0x6ffb76e0)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x6ffb78d7)
CORECLR! HndScanHandlesForGC + 0x139 (0x6ffb557e)
CORECLR! Ref_TracePinningRoots + 0xC8 (0x6ffb9cf6)
CORECLR! GCScan::GcScanHandles + 0x64 (0x6ffbc6f7)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E7 (0x6ffed749)
CORECLR! WKS::gc_heap::gc1 + 0x13B (0x6fff7967)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x6ffefd29)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x6ffefed7)
CORECLR! <lambda_1b38767654925028206050c0a535fa8e>::operator() + 0x84 (0x6fdb10b3)
-----
.AV on tid=0x1a24 (6692), cxr=08FBE7C4, exr=08FBE774
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x7004ca62)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6fbd6d30)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6fbd6a25)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x6fbd69cb)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x6fbd6f3a)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1C0D3 (0x7769f953)
NTDLL! RtlUnwind + 0x1BA (0x7766025a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x77670eff)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x6ffeeb99)
CORECLR! PinObject + 0xF3 (0x6ffb8603)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7165
    Image: C:\h\w\C1F20A41\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\C1F20A41\w\C4E80A9C\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\C1F20A41\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 12/24/2023 8:58:01 PM
Processing C:\cores\corerun.exe.6580.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\C1F20A41\t\tmpbyevft.tmp" -z "C:\cores\corerun.exe.6580.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.6580.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\C1F20A41\p\PDB
Symbol search path is: C:\h\w\C1F20A41\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sun Dec 24 20:58:19.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:14:12.143
Process Uptime: 0 days 0:00:18.000
.................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest 
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr jitstress 20240129.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=545388&view=ms.vss-test-web.build-test-results-tab&runId=12951490&resultId=120723&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitminopts @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 Assert failure(PID 7384 [0x00001cd8], Thread: 7476 [0x1d34]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x7014a4c6)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x7014abd9)
CORECLR! PinObject + 0xF3 (0x70114623)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x70113504)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x70112fc9)
CORECLR! ProcessScanQNode + 0x32 (0x701133d2)
CORECLR! ProcessScanQueue + 0x2E (0x70113411)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x701139d4)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x70113845)
CORECLR! TableScanHandles + 0xB0 (0x70113780)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x701138f7)
CORECLR! HndScanHandlesForGC + 0x139 (0x701115f1)
CORECLR! Ref_TracePinningRoots + 0xC8 (0x70115d16)
CORECLR! GCScan::GcScanHandles + 0x64 (0x70118717)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E7 (0x70149789)
CORECLR! WKS::gc_heap::gc1 + 0x13B (0x701539a7)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x7014bd69)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x7014bf17)
CORECLR! <lambda_7f2395fa1000bef1473ae437439df325>::operator() + 0x84 (0x6ff0cb7f)
-----
.AV on tid=0x1d34 (7476), cxr=091DED1C, exr=091DECCC
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x701a8a62)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6fd34770)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6fd34465)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x6fd3440b)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x6fd3497a)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1C0D3 (0x778cf953)
NTDLL! RtlUnwind + 0x1BA (0x7789025a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x778a0eff)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x7014abd9)
CORECLR! PinObject + 0xF3 (0x70114623)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp:7165
    Image: C:\h\w\AEBD094C\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\AEBD094C\w\AA7C0947\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AEBD094C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 1/30/2024 5:46:21 AM
Processing C:\cores\corerun.exe.7384.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\AEBD094C\t\tmp2vswyd.tmp" -z "C:\cores\corerun.exe.7384.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.7384.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\AEBD094C\p\PDB
Symbol search path is: C:\h\w\AEBD094C\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Tue Jan 30 05:46:37.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:10:48.943
Process Uptime: 0 days 0:00:16.000
..................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress 20240304.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=588901&view=ms.vss-test-web.build-test-results-tab&runId=14211304&resultId=121131&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitminopts @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 
Assert failure(PID 4484 [0x00001184], Thread: 9640 [0x25a8]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x6f6d9594)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x6f6d9ca9)
CORECLR! PinObject + 0xF3 (0x6f6a3783)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x6f6a2664)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x6f6a2129)
CORECLR! ProcessScanQNode + 0x32 (0x6f6a2532)
CORECLR! ProcessScanQueue + 0x2E (0x6f6a2571)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x6f6a2b34)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x6f6a29a5)
CORECLR! TableScanHandles + 0xB0 (0x6f6a28e0)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x6f6a2a57)
CORECLR! HndScanHandlesForGC + 0x139 (0x6f6a074e)
CORECLR! Ref_TracePinningRoots + 0xC8 (0x6f6a4e76)
CORECLR! GCScan::GcScanHandles + 0x64 (0x6f6a7877)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E7 (0x6f6d8859)
CORECLR! WKS::gc_heap::gc1 + 0x13B (0x6f6e2a37)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x6f6dae3a)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x6f6dafe7)
CORECLR! <lambda_98eabe3fe0c78dfed31e0caf458acd24>::operator() + 0x84 (0x6f49bc23)
-----
.AV on tid=0x25a8 (9640), cxr=094CEA68, exr=094CEA18
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x6f737a82)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6f2c5190)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6f2c4e85)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x6f2c4e2b)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x6f2c539a)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1C0D3 (0x76f5f953)
NTDLL! RtlUnwind + 0x1BA (0x76f2025a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x76f30eff)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x6f6d9ca9)
CORECLR! PinObject + 0xF3 (0x6f6a3783)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp:7160
    Image: C:\h\w\B9690A0E\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B9690A0E\w\BD5A0A3B\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B9690A0E\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 3/5/2024 5:34:49 AM
Processing C:\cores\corerun.exe.4484.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B9690A0E\t\tmpzs40xe.tmp" -z "C:\cores\corerun.exe.4484.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.4484.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B9690A0E\p\PDB
Symbol search path is: C:\h\w\B9690A0E\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Tue Mar  5 05:34:57.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:35:14.019
Process Uptime: 0 days 0:00:08.000
..................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored 
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20240325.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=618022&view=ms.vss-test-web.build-test-results-tab&runId=15120010&resultId=114522&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 
Assert failure(PID 9704 [0x000025e8], Thread: 9744 [0x2610]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x6fabc850)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x6fabcf69)
CORECLR! PinObject + 0xF3 (0x6fa868b3)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x6fa85794)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x6fa85259)
CORECLR! ProcessScanQNode + 0x32 (0x6fa85662)
CORECLR! ProcessScanQueue + 0x2E (0x6fa856a1)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x6fa85c64)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x6fa85ad5)
CORECLR! TableScanHandles + 0xB0 (0x6fa85a10)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x6fa85b87)
CORECLR! HndScanHandlesForGC + 0x139 (0x6fa83890)
CORECLR! Ref_TracePinningRoots + 0xC8 (0x6fa87fa5)
CORECLR! GCScan::GcScanHandles + 0x64 (0x6fa8a9a7)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E7 (0x6fabbb0b)
CORECLR! WKS::gc_heap::gc1 + 0x13B (0x6fac5d98)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x6fabe0f9)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x6fabe2a7)
CORECLR! <lambda_17900e4cd36d7e7fc31fdaa89a77f1d0>::operator() + 0x84 (0x6f87cc3f)
-----
.AV on tid=0x2610 (9744), cxr=0904E8A0, exr=0904E850
FAILED: false

CORECLR! CHECK::Trigger + 0x256 (0x6fb1ad8f)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6f6a4c6b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6f6a4960)
CORECLR! CLRVectoredExceptionHandler + 0x13C (0x6f6a4906)
CORECLR! CLRVectoredExceptionHandlerShim + 0x17A (0x6f6a4e7a)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1C0D3 (0x76f9f953)
NTDLL! RtlUnwind + 0x1BA (0x76f6025a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x76f70eff)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x6fabcf69)
CORECLR! PinObject + 0xF3 (0x6fa868b3)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp:7160
    Image: C:\h\w\B00B092F\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B00B092F\w\A869091B\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B00B092F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 3/26/2024 3:17:00 AM
Processing C:\cores\corerun.exe.9704.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B00B092F\t\tmp4lxv3r.tmp" -z "C:\cores\corerun.exe.9704.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.9704.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B00B092F\p\PDB
Symbol search path is: C:\h\w\B00B092F\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Tue Mar 26 03:17:13.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:04:35.651
Process Uptime: 0 days 0:00:12.000
..................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Closing since this hasn't reproed for a few weeks.
