### ISSUE TITLE
Test failure System.Data.Tests.DataSetTypedDataSetTest.TypedDataSet

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93271]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20230930.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423555&view=ms.vss-test-web.build-test-results-tab&runId=9310200&resultId=119766&paneView=debug)
Failed Test:
```
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs0x2000-Windows.10.Amd64.Open

- System.Data.Tests.DataSetTypedDataSetTest.TypedDataSet
```

**Error message:**
```
System.Runtime.Serialization.SerializationException : Invalid BinaryFormatter stream.
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.NullReferenceException : Object reference not set to an instance of an object.



Stack trace
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream) in /_/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryFormatter.Core.cs:line 52
   at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterHelpers.Clone[T](T obj, ISerializationSurrogate surrogate, FormatterAssemblyStyle assemblyFormat, TypeFilterLevel filterLevel, FormatterTypeStyle typeFormat) in /_/src/libraries/Common/tests/System/Runtime/Serialization/Formatters/BinaryFormatterHelpers.cs:line 41
   at System.Data.Tests.DataSetTypedDataSetTest.TypedDataSet() in /_/src/libraries/System.Data.Common/tests/System/Data/DataSetTypedDataSetTest.cs:line 748
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
----- Inner Stack Trace -----
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Constructor.cs:line 57
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context) in /_/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/ObjectManager.cs:line 793
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder) in /_/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/ObjectManager.cs:line 198
   at System.Runtime.Serialization.ObjectManager.DoFixups() in /_/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/ObjectManager.cs:line 843
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser) in /_/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryObjectReader.cs:line 104
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream) in /_/src/libraries/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/BinaryFormatter.Core.cs:line 44
----- Inner Stack Trace -----
   at System.Uri.get_IriParsing() in /_/src/libraries/System.Private.Uri/src/System/Uri.cs:line 270
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e) in /_/src/libraries/System.Private.Uri/src/System/UriExt.cs:line 90
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) in /_/src/libraries/System.Private.Uri/src/System/UriExt.cs:line 38
   at System.Xml.Schema.Parser.StartParsing(XmlReader reader, String targetNamespace) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/Parser.cs:line 84
   at System.Xml.Schema.Parser.Parse(XmlReader reader, String targetNamespace) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/Parser.cs:line 51
   at System.Xml.Schema.XmlSchema.Read(XmlReader reader, ValidationEventHandler validationEventHandler) in /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/XmlSchema.cs:line 78
   at System.Data.DataSet.ReadXSDSchema(XmlReader reader) in /_/src/libraries/System.Data.Common/src/System/Data/DataSet.cs:line 1816
   at System.Data.DataSet.ReadXmlSchema(XmlReader reader, Boolean denyResolving) in /_/src/libraries/System.Data.Common/src/System/Data/DataSet.cs:line 1689
   at System.Data.Tests.DataSet1..ctor(SerializationInfo info, StreamingContext context) in /_/src/libraries/System.Data.Common/tests/System/Data/DataSet1.Designer.cs:line 58
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void*
```

**Comment by danmoseley** [comment]
@GrabYourPitchforks  presumably this test and the path it's testing will be deleted this release, per https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#net-9-nov-2024 ?

**Comment by danmoseley** [comment]
no reason to believe that binary formatter is related to the failure though. the common factor for these tests is a NRE here
```
    System.Data.Tests.DataSetReadXmlSchemaTest.TestSampleFileNoTables [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Private.Uri/src/System/Uri.cs(270,0): at System.Uri.get_IriParsing()
        /_/src/libraries/System.Private.Uri/src/System/UriExt.cs(90,0): at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
        /_/src/libraries/System.Private.Uri/src/System/UriExt.cs(38,0): at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/Parser.cs(84,0): at System.Xml.Schema.Parser.StartParsing(XmlReader reader, String targetNamespace)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/Parser.cs(51,0): at System.Xml.Schema.Parser.Parse(XmlReader reader, String targetNamespace)
        /_/src/libraries/System.Private.Xml/src/System/Xml/Schema/XmlSchema.cs(78,0): at System.Xml.Schema.XmlSchema.Read(XmlReader reader, ValidationEventHandler validationEventHandler)
        /_/src/libraries/System.Data.Common/src/System/Data/DataSet.cs(1816,0): at System.Data.DataSet.ReadXSDSchema(XmlReader reader)
        /_/src/libraries/System.Data.Common/src/System/Data/DataSet.cs(1689,0): at System.Data.DataSet.ReadXmlSchema(XmlReader reader, Boolean denyResolving)
        /_/src/libraries/System.Data.Common/tests/System/Data/DataSetReadXmlSchemaTest.cs(485,0): at System.Data.Tests.DataSetReadXmlSchemaTest.TestSampleFileNoTables()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

@BruceForstall this may actually be a JIT stress failure. The code below is throwing NRE -- I cannot see how, as there's a null check.

```C#
        private bool IriParsing => IriParsingStatic(_syntax);

        internal static bool IriParsingStatic(UriParser? syntax)
        {
            return syntax is null || syntax.InFact(UriSyntaxFlags.AllowIriParsing);
        }
```

**Comment by BruceForstall** [comment]
@danmoseley Does the test reliably fail with:
```
DOTNET_JitStress=2
DOTNET_JitStressRegs=0x2000
DOTNET_TieredCompilation=0
```
and succeed with:
```
DOTNET_TieredCompilation=0
```
?

**Comment by danmoseley** [comment]
@BruceForstall I looped it a few times (both alone and together) and got no failures with those set and with those not set. So either there's something else or I'm just not looping it enough.

Oh, I'm using release runtime. Let me build checked

**Comment by danmoseley** [comment]
@BruceForstall I looped the test for an hour with those env vars, on a checked runtime. No failures. That's maybe 1000-2000 times on x64. I also tested for a while without them, no failure.

This isn't my area, so I don't know that I can contribute further.

**Comment by BruceForstall** [comment]
The more recent build of this pipeline succeeded with [no failures](https://dev.azure.com/dnceng-public/public/_build/results?buildId=430636&view=results). So, I suggest closing as "no repro" unless the area owner wants to investigate more.
