### ISSUE TITLE
System.IO.File.OpenRead - incorrect and misleading exception

### ISSUE THREAD

**Issue by rwv37** [dotnet/runtime#93324]
### Description

When `File.OpenRead` is called with a directory name instead of a file name, [the documentation says](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.openread?view=net-7.0) that it will throw an `UnauthorizedAccessException`. It does in fact do this in some cases (e.g. if you try to call it for @"C:\\"). However, at least in one case, it instead throws a `DirectoryNotFoundException` instead. Not only is this contrary to the documentation, but it's also extra misleading in a way: It will throw `DirectoryNotFoundException` even if the specified directory does, in fact, exist.

### Reproduction Steps

```
namespace ConsoleApp1
{
    internal class Program
    {
        static void Main()
        {
            File.OpenRead(Path.GetTempPath());
        }
    }
}

```

### Expected behavior

Running the program should, according to the documentation, result in an `UnauthorizedAccessException`.

### Actual behavior

It instead results in a `DirectoryNotFoundException` (even if the directory does exist):

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bob\AppData\Local\Temp\'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at ConsoleApp1.Program.Main() in C:\Users\bob\BobStuff\Trunk\ConsoleApp1\ConsoleApp1\Program.cs:line 7
```

Note that it works as per the documents for at least one different directory:

```
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at ConsoleApp1.Program.Main() in C:\Users\bob\BobStuff\Trunk\ConsoleApp1\ConsoleApp1\Program.cs:line 7
```

I have not tried it on any directory other than these two.

### Regression?

I don't know.

### Configuration

- .Net 7
- Windows 11 Pro 64-bit
- x64
- No idea if it's specific to that configuration
- Not using Blazor (or at the very least I have no idea what Blazor is and if I'm using it, I'm doing so unbeknownst to me)

**Comment by Jozkee** [comment]
This behavior comes from the windows API CreateFile, it appears that the rule is throw `DirectoryNotFoundException` if the path ends in a separator. otherwise throw `UnauthorizedAccessException` if it didn't end in separator and it happened to be a directory. 

For `C:\` we throw `UnauthorizedAccessException` because it has been special-cased since .NET framework times, see https://github.com/dotnet/runtime/issues/70275 where is proposed to remove the special-casing.

[Documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.openread?view=net-7.0) already states that `DirectoryNotFoundException` means "The specified path is invalid", that IMO encompasses paths ending in a separator.

**Comment by rwv37** [comment]
"[Documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.openread?view=net-7.0) already states that DirectoryNotFoundException means "The specified path is invalid", that IMO encompasses paths ending in a separator."

A few things:

(1) The documentation also already states -- very explicitly, no "IMO" about it -- that "path specified a directory" results in `UnauthorizedAccessException`.

(2) I respectfully disagree with your opinion. First, you've omitted the end of the `DirectoryNotFoundException` section of the documentation, which gives an example: "The specified path is invalid, (for example, it is on an unmapped drive)."

I think it's clear in context that this "path is invalid" here does not mean "... in any possible sense of the phrase 'path is invalid' that you can possibly imagine". It means the directory was not found. Hence, `DirectoryNotFoundException`.

The definitions given in the `OpenRead()` documentation for (at least) `ArgumentException`, `ArgumentNullException`, `PathTooLongException`, `FileNotFoundException`, and `NotSupportedException` are all _also_ consistent with interpretations of "path is invalid". These interpretations are totally reasonable _if you ignore the context_, as you're doing with `DirectoryNotFoundException`. So is it reasonable for `DirectoryNotFound` exception to be thrown for, say, a filename that's too long? For a file that doesn't exist? For all the others too? Because they're all consistent with some context-free interpretation of "path is invalid"? And despite the fact that the documentation specifically describes these situations as resulting in exceptions that are _not_ `DirectoryNotFound`?

(3) Even ignoring all of the above, I'm honestly having a very tough time believing that `DirectoryNotFoundException` is a reasonable choice of exception for situations where the specified directory can be found. Such as the situation I originally described in this post - the directory provided as the `path` parameter to `OpenRead()` _could_ be found. The problem is not that a directory couldn't be found. It's something else entirely. The `DirectoryNotFoundException` is thus highly misleading _even if we accept the context-free "any possible interpretation of 'path is invalid'" definition_.

If this is not going to change so that reality reflects the documentation, fine, I guess; I don't really care that much. But then at the very least, the documentation should be changed to reflect reality.

**Comment by Jozkee** [comment]
> It means the directory was not found.

I think that's the confusing bit. By the name of the exception, yet it should mean that, but by that same logic UnauthorizedAccessException should mean that the path is a file to which you cannot access, and that's not true.

The problem _I think_ is that Windows tends to repurpose error codes. In this case you should not see DirectoryNotFoundException as what the name implies, the directory not existing. For example, take an existing directory and append it with a separator e.g: `File.OpenRead(@"C:\Users\bob\")` it will throw DNFE even when it does exist.

Yes, it is unfortunate that DNFE is used to convey "path is invalid" in this API, and many other ones that call CreateFile, but as I said, that decision was made by the OS, and we forward it to the user, it is not wise for dotnet to catch it and then replace it with something else as then inconsistencies between managed and unmanaged happen, as it is already the case for `C:\` or any other root drive path.

That's why I closed the issue, I don’t have a good solution to the problem of "`C:\directory` raises UnauthorizedAccessException but `C:\directory\` raises DirectoryNotFoundException we should align them".

What do you think that the documentation should state instead?
