### ISSUE TITLE
[wasm] JSImportExportTest.JsImportTaskTypes - System.ObjectDisposedException

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#93347]
### Error Blob

```json
{
  "ErrorMessage": "JSImportExportTest.JsImportTaskTypes",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=434577&view=results

```
fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes
info: System.ObjectDisposedException : Cannot access a disposed object.
info: Object name: 'System.Runtime.InteropServices.JavaScript.JSObject'.
info:    at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTestHelper.echopromise_JSObject(JSObject value)
info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes()
```
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-93010-merge-8801997f7db744b89d/WasmTestOnNodeJS-System.Runtime.InteropServices.JavaScript.Tests/1/console.6b94f736.log?helixlogtype=result)

Previously tracked as https://github.com/dotnet/runtime/issues/77334

**Comment by pavelsavara** [comment]
Last few were bad rule matching on a passing test
