### ISSUE TITLE
[wasm] MT browser-bench crash

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#93398]
I was trying to measure wasm/MT perf recently. The browser-bench is crashing for me, during the app start measurements, in this place:

```
AppStart, Reach managed count: 29, per call: 170.79310344827587ms, total: 4.953s
AppStart, Reach managed count: 31, per call: 178.83870967741936ms, total: 5.544s
dotnet.native.js:4738 Uncaught TypeError: Failed to execute 'getRandomValues' on 'Crypto': The provided ArrayBufferView value must not be shared.
    at Object.getBatchedRandomValues (dotnet.native.js:4738:11)
    at _dotnet_browser_entropy (dotnet.native.js:4749:17)
    at dotnet.native.wasm:0x2110c7
    at dotnet.native.wasm:0x210f5d
    at dotnet.native.wasm:0x21f50
    at dotnet.native.wasm:0x1ecb4
    at dotnet.native.wasm:0x12fdd
    at dotnet.native.wasm:0x200e3
    at dotnet.native.wasm:0xfa6b2
    at dotnet.native.wasm:0xc82b7
```

**Comment by lewing** [comment]
interesting
