### ISSUE TITLE
Improve error message for dictionary key converters not implementing `ReadAsPropertyName`/`WriteAsPropertyName`.

### ISSUE THREAD

**Issue by bitbonk** [dotnet/runtime#93406]
### Description

When I serialize an object that contains a property of type `Dictionary<TKey, TValue>` and `TKey` is a custom class, I get a `NotSupportedException`, _even if there is a JSON converter for this_.

```csharp
JsonSerializer.Serialize(
    new Custom
    {
        Dict = new Dictionary<CustomKey, string>
        {
            [new CustomKey {Value1 = "one", Value2 = "two"}] = "three",
            [new CustomKey {Value1 = "four", Value2 = "five"}] = "six"
        }});
```

```csharp
class Custom
{
    public Dictionary<CustomKey, string> Dict { get; set; }
}

[JsonConverter(typeof(CustomKeyJsonConverter))]
class CustomKey
{
    public string Value1 { get; set; }
    public string Value2 { get; set; }

    public static CustomKey Parse(string text)
    {
        var values = text.Split("-");
        return new CustomKey {Value1 = values[0], Value2 = values[1]};
    }

    public override string ToString()
    {
        return $"{this.Value1}-{this.Value2}";
    }
}

class CustomKeyJsonConverter : JsonConverter<CustomKey>
{
    public override CustomKey? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return CustomKey.Parse(reader.GetString());
    }

    public override void Write(Utf8JsonWriter writer, CustomKey value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString());
    }
}
```

### Reproduction Steps

see above

### Expected behavior

The serialization (and deserialization) should succeed if there is a JSON converter for the key.

### Actual behavior

The following `NotSupportedException` exception is thrown

```text
System.NotSupportedException
The type 'JsonTest.CustomKey' is not a supported dictionary key using converter of type 'JsonTtest.CustomKeyJsonConverter'. The unsupported member type is located on type 'System.String'. Path: $.Dict.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
```

### Regression?

The same behavior is in .NET 6, 7 and 8, so it probably not a regression.

### Known Workarounds

Write a custom JSON for the whole `Dictionary<CustomKey, string>` type.

### Configuration

Windows 11, ,NET SDK 8.0.100-rc.2.23502.2

**Comment by eiriktsarpalis** [comment]
Using converters for dictionary key serialization requires overriding the `ReadAsPropertyName`/`WriteAsPropertyName` methods:

```C#
class CustomKeyJsonConverter : JsonConverter<CustomKey>
{
    public override CustomKey? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => CustomKey.Parse(reader.GetString());

    public override void Write(Utf8JsonWriter writer, CustomKey value, JsonSerializerOptions options)
        => writer.WriteStringValue(value.ToString());

    public override CustomKey ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => CustomKey.Parse(reader.GetString());

    public override void WriteAsPropertyName(Utf8JsonWriter writer, CustomKey value, JsonSerializerOptions options)
        => writer.WritePropertyName(value.ToString());
}
```

Keeping the issue open since we could improve the error message to include this information.

**Comment by naeemaei** [comment]
I am interested in helping to contribute in this issue

**Comment by eiriktsarpalis** [comment]
Thanks @naeemaei, I've assigned it to you.

**Comment by naeemaei** [comment]
Considering that this error occurs when the methods are not implemented in the converter, is it better to create a  method with `NotImplementedException` in `ThrowHelper.cs` or append `dictionary key converter not implemented ReadAsPropertyName/WriteAsPropertyName methods` message to the existing message of the `DictionaryKeyTypeNotSupported` key?

```cs
[DoesNotReturn]
public static void ThrowNotImplementedException_DictionaryKeyTypeConvertorNotImplemented(Type keyType, JsonConverter converter)
{
    throw new NotImplementedException(SR.Format(SR.DictionaryKeyTypeConvertorNotImplemented, keyType, converter.GetType()));
}
```

@eiriktsarpalis

**Comment by eiriktsarpalis** [comment]
Changing the exception type can break users that depend on catching the current exception. I think it would be preferable to just update the error message.

**Comment by bitbonk** [comment]
Just for completeness and future readers: Changing the converter as @eiriktsarpalis suggested in https://github.com/dotnet/runtime/issues/93406#issuecomment-1761268819 does fix the problem, the exceptions goes away and the type is correctly (de)serialized (testet with .NET 6).
