### ISSUE TITLE
System.Numerics.Tensors.Tests.TensorPrimitivesTests.SoftMax not implemented

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#93425]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=436660
Build error leg or test failing: System.Numerics.Tensors.Tests.TensorPrimitivesTests.SoftMax
Pull request: https://github.com/dotnet/runtime/pull/93409

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Numerics.Tensors.Tests.TensorPrimitivesTests.SoftMax(tensorLength: 8) [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
System.Numerics.Tensors.Tests.TensorPrimitivesTests.SoftMax(tensorLength: 8) [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
        /_/src/libraries/System.Numerics.Tensors/src/System/Numerics/Tensors/TensorPrimitives.netstandard.cs(2570,0): at System.Numerics.Tensors.TensorPrimitives.ExpOperator.Invoke(Vector`1 x)
        /_/src/libraries/System.Numerics.Tensors/src/System/Numerics/Tensors/TensorPrimitives.netstandard.cs(991,0): at System.Numerics.Tensors.TensorPrimitives.<InvokeSpanScalarIntoSpan>g__Vectorized|56_1[TTransformOperator,TBinaryOperator](Single& xRef, Single y, Single& dRef, UIntPtr remainder, TTransformOperator xTransformOp, TBinaryOperator binaryOp)
        /_/src/libraries/System.Numerics.Tensors/src/System/Numerics/Tensors/TensorPrimitives.netstandard.cs(971,0): at System.Numerics.Tensors.TensorPrimitives.InvokeSpanScalarIntoSpan[TTransformOperator,TBinaryOperator](ReadOnlySpan`1 x, Single y, Span`1 destination, TTransformOperator xTransformOp, TBinaryOperator binaryOp)
```

**Comment by lewing** [comment]
wrong issue
