### ISSUE TITLE
Everything works well untill joining server

### ISSUE THREAD

**Issue by Godofdoggoss** [dotnet/runtime#93433]
### Description

Log:java.lang.ArrayIndexOutOfBoundsException: Index 19699 out of bounds for length 19699
	at packets.DataTypeProvider.readNext(DataTypeProvider.java:76)
	at packets.DataTypeProvider$1.read(DataTypeProvider.java:198)
	at java.base/java.io.InputStream.read(InputStream.java:293)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:570)
	at se.llbit.nbt.StringTag.read(StringTag.java:46)
	at se.llbit.nbt.NamedTag.read(NamedTag.java:58)
	at packets.DataTypeProvider.readNbtTag(DataTypeProvider.java:195)
	at packets.handler.version.ClientBoundGamePacketHandler_1_18.lambda$new$1(ClientBoundGamePacketHandler_1_18.java:32)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.RuntimeException: Invalid VarInt found! Packet structure may have changed.
	at packets.DataReader.readVarInt(DataReader.java:70)
	at packets.DataTypeProvider.readVarInt(DataTypeProvider.java:111)
	at game.data.entity.EntityRegistry.destroyEntities(EntityRegistry.java:187)
	at packets.handler.ClientBoundGamePacketHandler.lambda$new$5(ClientBoundGamePacketHandler.java:60)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$7(ProxyServer.java:106)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$9(ProxyServer.java:103)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.run(ProxyServer.java:62)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 17 out of bounds for byte[10]
	at java.base/java.lang.System.arraycopy(Native Method)
	at packets.DataTypeProvider.readByteArray(DataTypeProvider.java:90)
	at packets.DataTypeProvider.readDouble(DataTypeProvider.java:216)
	at packets.handler.ServerBoundGamePacketHandler.lambda$new$0(ServerBoundGamePacketHandler.java:20)
	at packets.handler.PacketHandler.handle(PacketHandler.java:57)
	at packets.DataReader.readPackets(DataReader.java:163)
	at packets.DataReader.pushData(DataReader.java:118)
	at proxy.ProxyServer.lambda$run$4(ProxyServer.java:86)
	at util.ExceptionHandling.attempt(ExceptionHandling.java:12)
	at proxy.ProxyServer.lambda$run$6(ProxyServer.java:83)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Reproduction Steps

launch minecraft launch world downloader, insert adress into world downloader, join local host, join server yet downloader says error

### Expected behavior

i join the game, takes a second and downloads the world

### Actual behavior

i join the game, downloader goes kablooe

### Regression?

no clue 

### Known Workarounds

 i dont have any

### Configuration

 i have no clue what i put here

### Other information

![image](https://github.com/dotnet/runtime/assets/147778415/9cfd6bcc-ffd5-43cc-a67b-8b64af5699cf)

Version:1.20.1
Latest launcher
World:1.20.1

**Comment by jkotas** [comment]
This repo for .NET runtime. The traces that you share do not appear to have anything to do with .NET runtime.
