### ISSUE TITLE
NativeFileReference regression in .NET 8.0

### ISSUE THREAD

**Issue by b-straub** [dotnet/runtime#93538]
### Description

A object detection sample project using the ONNX runtime as WASM static library is running well using NET7.0 but fails on NET8.0rc with the following error chain:

``

await createEmscripten(module);
..
mono_download_assets();
...
}).catch(err => {
    loaderHelpers.err("Error in mono_download_assets: " + err);
    mono_exit(1, err);
    throw err;
});

``

The error comes obviously from the inclusion of the ONNX rumtime.

### Reproduction Steps

Clone the repository [WASMObjectDetector](https://github.com/b-straub/WASMObjectDetector)
Run the WASMObjectDetector7 sample
Run the WASMObjectDetector8 sample

### Expected behavior

WASMObjectDetector8 sample working as well.

### Actual behavior

WASMObjectDetector8 sample -> failing with "Error in mono_download_assets"

### Regression?

working on NET7.0

### Known Workarounds

none

### Configuration

VS Version 17.8.0 Preview 3.0
NET7.0 SDK 7.0.402
NET8.0rc2 SDK 8.0.100-rc.2.23502.2

**Comment by maraf** [comment]
Running the .NET 8 sample I'm getting a different error

```
Error
    at Object.ke [as mono_exit] (http://localhost:5028/_framework/dotnet.js:3:19020)
    at Ll.e.onAbort.e.onAbort (http://localhost:5028/_framework/dotnet.runtime.8.0.0-rc.2.23479.6.cfr91rytrt.js:3:214072)
    at abort (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:856:22)
    at ___cxx_global_var_init (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:1400:51)
    at __wasm_call_ctors (http://localhost:5028/_framework/dotnet.native.wasm:wasm-function[109]:0x1813d)
    at callRuntimeCallbacks (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:1238:26)
    at initRuntime (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:725:3)
    at doRun (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:7793:5)
    at run (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:7813:5)
    at runCaller (http://localhost:5028/_framework/dotnet.native.8.0.0-rc.2.23479.6.gzw26f0zwy.js:7756:19)
```

**Comment by b-straub** [comment]
after 'dotnet run' or running from VS I get in Edge only a warning:

![image](https://github.com/dotnet/runtime/assets/7459002/edc742d8-d346-4e88-a062-4ddff255c580)

same for Firefox:

![image](https://github.com/dotnet/runtime/assets/7459002/42baf3d9-b551-41c0-8eab-3d8c2f196836)

**Comment by maraf** [comment]
The .NET 7 app starts, but than the ObjectDetector page fails with

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: onnxruntime
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Compunet.YoloV8.YoloV8..ctor(Byte[] model, YoloV8Metadata metadata, SessionOptions options)
   at Compunet.YoloV8.YoloV8..ctor(ModelSelector selector)
   at WASMObjectDetectorShared.Services.ObjectDetectorService.InitializeAsync() in C:\Development\bugrepro\onnx-nativefileref\WASMObjectDetector\WASMObjectDetectorShared\Services\ObjectDetectorService.cs:line 24
   at WASMObjectDetectorShared.Component.ObjectDetectorComponent.OnInitializedAsync() in C:\Development\bugrepro\onnx-nativefileref\WASMObjectDetector\WASMObjectDetectorShared\Component\ObjectDetectorComponent.razor:line 21
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by b-straub** [comment]
you need to install the wasm-tools workload in order to run emcc.
For NET7 you should see for "dotnet run -v n"

 _CheckEmccIsExpectedVersion:
         emcc --version
       _WasmCompileNativeFiles:
         embuilder.bat build MINIMAL
         Compiling native assets with emcc with -O0. This may take a while ...
       _WasmLinkDotNet:
         Linking for initial memory $(EmccInitialHeapSize)=16777216 bytes. Set this msbuild property to change the valu
         e.
         Linking with emcc with -O0. This may take a while ...
         emcc "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.12\runtimes\browser-w
         asm\native\src\emcc-default.rsp" "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wa
         sm\7.0.12\runtimes\browser-wasm\native\src\emcc-link.rsp" ....

NET 8.0 will compile with Emscripten.3.1.34.Sdk
and indeed a new warning will appear here: warning : undefined symbol: __cxx_global_var_init

**Comment by maraf** [comment]
Could this be related https://github.com/microsoft/onnxruntime/issues/4539 ?

**Comment by b-straub** [comment]
> Could this be related [microsoft/onnxruntime#4539](https://github.com/microsoft/onnxruntime/issues/4539) ?

I don't think so. The onnxruntime.a is build outside the dotnet build process. For the dotnet build only the Emscripten linker will be called. The NET7 runtime is build from 1.15.1 release branch with 3.1.12 SDK, and the NET8 from 1.16.1 with the standard SDK for this branch. You can also use the "onnxruntime.a" from WASMObjectDetection7 project and the problem will persists.

I couldn't however test the NET7 project with the NET8 Emscripten SDK. No idea where to change the SDK for MSBUILD.

**Comment by b-straub** [comment]
I can't be a general NET8 native asset problem as well since other libs e.g. OpenCVSharp Wasm runtime will work.
[OpenCVSharp4 Demo](https://github.com/LostBeard/SpawnDev.BlazorJS.OpenCVSharp4)

**Comment by b-straub** [comment]
The runtime is build with the settings below. Using emsdk 3.1.12 with the 1.15.1 branch requires a small cMakeLists.txt tweak.
Just comment

````
 #list(APPEND ORT_WARNING_FLAGS -Wno-deprecated-builtins)
````

[Build ONNX Runtime for Web](https://onnxruntime.ai/docs/build/web.html)
````
git checkout rel1.15.1
./build.sh --config Release --build_wasm_static_lib --skip_tests --disable_wasm_exception_catching --disable_rtti  --enable_wasm_simd  --emsdk_version 3.1.12

or 
git checkout rel1.16.1
./build.sh --config Release --build_wasm_static_lib --skip_tests --disable_wasm_exception_catching --disable_rtti  --enable_wasm_simd

````

**Comment by SingleAccretion** [comment]
This could be an LLVM bug.

(E. g. there is https://github.com/llvm/llvm-project/issues/62243 and linked issues).

**Comment by b-straub** [comment]
> This could be an LLVM bug.
> 
> (E. g. there is [llvm/llvm-project#62243](https://github.com/llvm/llvm-project/issues/62243) and linked issues).

The linker doesn’t crash in the dotnet build, only a warning is emitted. Might be because WasmAllowUndefinedSymbols is set to true.
WasmAllowUndefinedSymbols=true will link with ‘-s ERROR_ON_UNDEFINED_SYMBOLS=0’

**Comment by maraf** [comment]
I have found so other issues with same function name pointing to llvm, but I'm not sure why it's marked as wasm import and why emscripten doesn't provide implementation, or what the implementation should be.

**Comment by SingleAccretion** [comment]
> Maybe it's the way how emscripten deals with undefined symbols.

Indeed; to be more precise, that is what `-s ERROR_ON_UNDEFINED_SYMBOLS=0` causes the linker to do. There are a couple other settings as well (e. g. error on any undefined symbols, resolve them to unreachable stubs in wasm).

AFAIK `__cxx_global_var_init` is supposed to be the synthesized global constructor function (for one particular variable). See this [godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:8,endLineNumber:10,positionColumn:8,positionLineNumber:10,selectionStartColumn:8,selectionStartLineNumber:10,startColumn:8,startLineNumber:10),source:'%23include+%3Cstdint.h%3E%0A%0Astruct+A%0A%7B%0A++++volatile+int+m%3B%0A++++A()+%7B+m+%3D+1%3B+%7D%0A%7D%3B%0A%0AA+g_A1%3B%0AA+g_A2%3B'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.223231357552585,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:wasm32clang,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'1',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-emit-llvm',overrides:!(),selection:(endColumn:26,endLineNumber:33,positionColumn:26,positionLineNumber:33,selectionStartColumn:26,selectionStartLineNumber:33,startColumn:26,startLineNumber:33),source:1),l:'5',n:'0',o:'+WebAssembly+clang+(trunk)+(Editor+%231)',t:'0')),k:50.776768642447415,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) for example.

**Comment by b-straub** [comment]
I’m not a compiler guy and can’t comment on the WASM compiler/linker inners. Since it’s running well on NET7 I’m even not sure how things are connected.
I suggest two things: 
- Compile the NET7 project with Emscripten SDK from 8.
- Bisect the 8.0 runtime to find where problem might come from.

When copying the onnxruntime.a from 7 to 8 even some possible onnx build differences will be ruled out.

**Comment by b-straub** [comment]
> that is what `-s ERROR_ON_UNDEFINED_SYMBOLS=0` causes the linker to do

Needed, since I can’t change Onnx managed code, there there are obviously other compliation conditions used than inside the wasm static library build.

**Comment by b-straub** [comment]
@pavelsavara Any idea?

**Comment by pavelsavara** [comment]
I didn't try to replicate, but high level I guess the same as SingleAccretion about `ERROR_ON_UNDEFINED_SYMBOLS`. 
Try `<WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>` in your project file.

**Comment by b-straub** [comment]
> I didn't try to replicate, but high level I guess the same as SingleAccretion about `ERROR_ON_UNDEFINED_SYMBOLS`. Try `<WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>` in your project file.

That was defined all the time, see the sample repository. I'm just not convinced that it's not a problem inside the asset loader. I have no clue how to debug into the runtime further.

**Comment by aheejin** [comment]
https://github.com/llvm/llvm-project/pull/73095 might have fixed the `__cxx_global_var_init` undefined symbol issue.

**Comment by pavelsavara** [comment]
Now it needs to flow via emscripten to dotnet/rutntime. I guess we would not be doing emscripten upgrade on .Net 8 servicing release. 

@lewing thoughts ?

**Comment by aheejin** [comment]
FYI, emsdk's latest release has the fix too: https://github.com/emscripten-core/emsdk/releases/tag/3.1.50

**Comment by nor0x** [comment]
found this issue via a search for my issue. I'm working on a Blazor WebAssembly app with a reference to a native file and since the .NET8 upgrade I get the following error during launch

```
"Error
    at Object.ke [as mono_exit] (http://localhost:31557/_framework/dotnet.js:3:19020)
    at Ll.e.onAbort.e.onAbort (http://localhost:31557/_framework/dotnet.runtime.8.0.1.rswtxkdyko.js:3:214204)
    at abort (http://localhost:31557/_framework/dotnet.native.8.0.1.gqt17pj1ci.js:859:22)
    at assert (http://localhost:31557/_framework/dotnet.native.8.0.1.gqt17pj1ci.js:390:5)
    at ___syscall_utimensat (http://localhost:31557/_framework/dotnet.native.8.0.1.gqt17pj1ci.js:5319:7)
    at utimensat (wasm://wasm/059a7ade:wasm-function[28003]:0x8a864f)
    at SystemNative_UTimensat (wasm://wasm/059a7ade:wasm-function[27555]:0x89747f)
    at do_icall (wasm://wasm/059a7ade:wasm-function[16162]:0x63dc0b)
    at do_icall_wrapper (wasm://wasm/059a7ade:wasm-function[16047]:0x638b28)
    at mono_interp_exec_method (wasm://wasm/059a7ade:wasm-function[16040]:0x62aa56)"
```


I'm not sure if this is the same one that is discussed here in the comments but so far I was not able to fix it. I have already tried adding `<WasmAllowUndefinedSymbols>true</WasmAllowUndefinedSymbols>`.

One thing that I noticed is that for me launching the app only fails in Debug mode - a Release build works fine.

Anybody some more ideas which could be helpful in my case?
