### ISSUE TITLE
Suppress Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd for JITStress

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93533]
**Failed in:** [runtime-coreclr gcstress-extra 20231014.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438833&view=ms.vss-test-web.build-test-results-tab&runId=9764922&resultId=111207&paneView=debug)

**Failed tests:**
```
coreclr linux x64 Checked gcstress0xc_zapdisable_jitstress2 @ Ubuntu.2204.Amd64.Open
    - Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd
coreclr linux x64 Checked gcstress0xc_zapdisable_heapverify1 @ Ubuntu.2204.Amd64.Open
    - Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd
coreclr linux arm64 Checked gcstress0xc_zapdisable_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd
coreclr linux x64 Checked gcstress0xc_zapdisable @ Ubuntu.2204.Amd64.Open
    - Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd
```

**Error message:**
```
Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
/datadisks/disk1/work/B03B09AD/w/A50708D7/e/Interop/Interop/../SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.sh: line 494:  7136 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/B03B09AD/w/A50708D7/uploads/SuppressGCTransition/SuppressGCTransitionNegativeTest/output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/B03B09AD/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true SuppressGCTransitionNegativeTest.dll ''
Explicit GC mode check is enabled
ILStubCache_GCTransition_NoGCTransition (1) ...
[createdump] Gathering state for process 7136 corerun
[createdump] Crashing thread 1be0 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.7136.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7136.dmp
[createdump] Written 78536704 bytes (19174 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 324ms
Expected: 134
Actual: 139
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 10/14/2023 10:55:07 PM
Processing /home/helixbot/dotnetbuild/dumps/coredump.7136.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.7136.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/datadisks/disk1/work/B03B09AD/w/A50708D7/e/Interop/Interop'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 499
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /datadisks/disk1/work/B03B09AD/w/A50708D7/e/Interop/Interop/../SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.sh
Expected: True
Actual:   False
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor136|0_137(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-10-12T10:17:44.589Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","BuildId":"435689","System.StageAttempt":"1","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr outerloop","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","Reason":"Schedule","System.JobName":"__default","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","System.JobAttempt":"1","architecture":"arm64","System.PhaseAttempt":"1","BuildNumber":"20231012.1","AzurePipelinesTestRunId":"9682156"} | Schedule
2023-10-12T10:17:44.589Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","BuildId":"435689","System.StageAttempt":"1","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr outerloop","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","Reason":"Schedule","System.JobName":"__default","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","System.JobAttempt":"1","architecture":"arm64","System.PhaseAttempt":"1","BuildNumber":"20231012.1","AzurePipelinesTestRunId":"9682156"} | Schedule

**Comment by BruceForstall** [comment]
@trylek another fallout from https://github.com/dotnet/runtime/pull/91901
@dotnet/interop-contrib

**Comment by jkoritzinsky** [comment]
I have a feeling that this and #93534 are expected (and should be disabled in GCStress). I'll inspect a little more locally and see.

These tests were manual tests before #91901, so I wouldn't be amazed if they always failed in GCStress.

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr jitstress 20231107.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=462922&view=ms.vss-test-web.build-test-results-tab&runId=10483744&resultId=121097&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress1 @ OSX.1200.ARM64.Open
    - Interop/SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.cmd
    - Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd
```

**Error message:**
```
Fatal error. Invalid Program: attempted to call a UnmanagedCallersOnly method from managed code.

cmdLine:/private/tmp/helix/working/AFFB09B3/w/A91208E4/e/Interop/Interop/../SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 11/7/2023 9:29:36 PM, end: 11/7/2023 9:59:36 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/AFFB09B3/w/A91208E4/uploads/SuppressGCTransition/SuppressGCTransitionNegativeTest/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/AFFB09B3/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true SuppressGCTransitionNegativeTest.dll ''
Explicit GC mode check is enabled
ILStubCache_GCTransition_NoGCTransition (1) ...

cmdLine:/private/tmp/helix/working/AFFB09B3/w/A91208E4/e/Interop/Interop/../SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 11/7/2023 9:29:36 PM, end: 11/7/2023 9:59:36 PM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/AFFB09B3/w/A91208E4/e/Interop/Interop/../SuppressGCTransition/SuppressGCTransitionNegativeTest/SuppressGCTransitionNegativeTest.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor136|0_137(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by agocke** [comment]
This should be fixed.
