### ISSUE TITLE
Test failure Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93534]
**Failed in:** [runtime-coreclr gcstress-extra 20231014.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438833&view=ms.vss-test-web.build-test-results-tab&runId=9764964&resultId=135903&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open
    - Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd
coreclr windows x86 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open
    - Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd
coreclr windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open
    - Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd
```

**Error message:**
```
 Assert failure(PID 4480 [0x00001180], Thread: 11564 [0x2d2c]): InlinedCallFrame::FrameHasActiveCall(m_crawl.pFrame)

CORECLR! StackFrameIterator::PostProcessingForManagedFrames + 0x12A (0x71b2aeec)
CORECLR! StackFrameIterator::NextRaw + 0x77A (0x71b2ab2a)
CORECLR! StackFrameIterator::Next + 0x50 (0x71b2a36a)
CORECLR! Thread::StackWalkFramesEx + 0x198 (0x71b2b9be)
CORECLR! Thread::StackWalkFrames + 0x152 (0x71b2b7a2)
CORECLR! ScanStackRoots + 0x1B7 (0x71c04dc5)
CORECLR! GCToEEInterface::GcScanRoots + 0xF5 (0x71c02f29)
CORECLR! WKS::gc_heap::mark_phase + 0x20D (0x71e50f7b)
CORECLR! WKS::gc_heap::gc1 + 0x148 (0x71e4ab14)
CORECLR! WKS::gc_heap::garbage_collect + 0x3E0 (0x71e4a945)
    File: D:_work1ssrccoreclrmstackwalk.cpp Line: 3291
    Image: C:hwB49A09E1pcorerun.exe


Return code:      1
Raw output file:      C:hwB49A09E1wAF9E0914uploadsUnmanagedCallersOnlyUnmanagedCallersOnlyNegativeTestoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB49A09E1pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  UnmanagedCallersOnlyNegativeTest.dll 
NegativeTest_ViaCalli function via calli instruction. The CLR _will_ crash.
Expected: -2146233082
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 10/14/2023 10:41:19 PM
Processing C:corescorerun.exe.4480.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggerscdb.exe -c "$<C:hwB49A09E1		mps4qnqo.tmp" -z "C:corescorerun.exe.4480.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.4480.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB49A09E1pPDB
Symbol search path is: C:hwB49A09E1pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sat Oct 14 22:41:21.000 2023 (UTC + 0:00)
System Uptime: 0 days 3:00:45.502
Process Uptime: 0 days 0:00:02.000
...................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1180.2d2c): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=0057b7c8 ebx=00000000 ecx=00000000 edx=00000000 esi=0057b778 edi=0057b7c8
eip=71eba702 esp=0057baac ebp=0057cb44 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!FailFastOnAssert+0x21:
71eba702 5e              pop     esi
0:000> cdb: Reading initial command '$<C:hwB49A09E1		mps4qnqo.tmp'
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: 1180.2d2c Suspend: 0 Teb: 003da000 Unfrozen
ChildEBP RetAddr  
0057bab8 71ebb3f1 coreclr!FailFastOnAssert+0x21
0057cb44 71ebab03 coreclr!_DbgBreakCheck+0x331
0057cbb4 71ebae2d coreclr!_DbgBreakCheckNoThrow+0x51
0057cc50 71b2aeec coreclr!DbgAssertDialog+0x20c
0057ce50 71b2ab2a coreclr!StackFrameIterator::PostProcessingForManagedFrames+0x12a
0057cec8 71b2a36a coreclr!StackFrameIterator::NextRaw+0x77a
0057ced8 71b2b9be coreclr!StackFrameIterator::Next+0x50
0057d1ac 71b2b7a2 c
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor139|0_140(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-10-12T10:17:44.589Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","BuildId":"435689","System.StageAttempt":"1","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr outerloop","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","Reason":"Schedule","System.JobName":"__default","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","System.JobAttempt":"1","architecture":"arm64","System.PhaseAttempt":"1","BuildNumber":"20231012.1","AzurePipelinesTestRunId":"9682156"} | Schedule
2023-10-12T10:17:44.589Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyNegativeTest/UnmanagedCallersOnlyNegativeTest.cmd | Failed | {"configuration":"Checked-no_tiered_compilation","BuildId":"435689","System.StageAttempt":"1","DefinitionId":"108","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr outerloop","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.PhaseName":"run_test_p1__osx_arm64_checked","System.StageName":"Build","Reason":"Schedule","System.JobName":"__default","Project":"public","operatingSystem":"OSX.1200.ARM64.Open","System.JobAttempt":"1","architecture":"arm64","System.PhaseAttempt":"1","BuildNumber":"20231012.1","AzurePipelinesTestRunId":"9682156"} | Schedule

**Comment by BruceForstall** [comment]
@trylek Looks like you added this with https://github.com/dotnet/runtime/pull/91901

@dotnet/interop-contrib
