### ISSUE TITLE
There is no safe round-trip for System.Enum values

### ISSUE THREAD

**Issue by bradwilson** [dotnet/runtime#93663]
### Description

I am trying to round-trip enum values to string and back in a way that is safe and guaranteed to always succeed, for any legal (or semi-legal) value.

As you know, since an enum value can store any integral value (with limitations based on the enum's definition), the safest and most compact way to round-trip those values would be via their integral value. This also allows users to round trip enum values which are not explicitly defined, which is of course legal in .NET.

The problem comes when the framework attempts to round-trip negative values. It appears to do so using the current culture and not the invariant culture. Some cultures (like `fo-FO`) use character U+2212 ("Minus Sign") when printing negative numbers, rather than U+002D ("Hyphen-Minus"). The Enum parsing functions, when presented with such a string, fail to parse.

Here is an example of tests that illustrate the problem (using .NET 6):

```csharp
using System;
using System.Globalization;
using Xunit;

enum MyEnum
{
    NegativeOne = -1
}

public class UnitTest
{
    [Fact]
    public void Passing()
    {
        var expected = MyEnum.NegativeOne;

        var actual = Enum.Parse(typeof(MyEnum), expected.ToString("d"));

        Assert.Equal(expected, actual);
    }

    [Fact]
    public void Failing()
    {
        var culture = CultureInfo.CreateSpecificCulture("fo-FO");
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;

        var expected = MyEnum.NegativeOne;

        var actual = Enum.Parse(typeof(MyEnum), expected.ToString("d"));

        Assert.Equal(expected, actual);
    }
}
```

The failing test results in the following stack trace:

```
at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at System.Enum.Parse(Type enumType, String value)
```

It appears that it misidentifies the string as being a named enum value because of the U+2212 minus sign.

### Configuration

I am able to reproduce this with .NET 6.0.23 on both Windows and Linux (Ubuntu 22.04 in WSL2). The machine is x64.

### Regression?

I am unable to reproduce this with .NET Framework 4.8.1 on Windows. It appears that the `fo-FO` culture does not use U+2212 for printing minus signs on .NET Framework. This means the parse bug probably exists there as well but isn't as likely to be trigger-able. (There may be a culture on .NET Framework that uses U+2212 for minus signs, but `fo-FO` does not appear to. It may also be the case that support for Unicode minus signs in integral `ToString()` is new to .NET Core/.NET.)

### Other information

This was reported against xUnit.net in https://github.com/xunit/xunit/issues/2796.

**Comment by danmoseley** [comment]
Parameterless ToString() conventionally uses current culture, I think?

Perhaps the question is why the Enum.ToString overloads that take an IFormatProvider are ignoring it. (And are documented to ignore it).

**Comment by bradwilson** [comment]
@danmoseley Correct, parameterless uses CurrentCulture, and as near as I can tell there's no override that will work here.

Example code ([SharpLab link](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AcQBsB7AIwEMqBLALweGZqgG488AbgzBEAxhCrAIYAKYB9AGY0iAXiIBhCVNkBJKErLrZHGQGUADjNHMFzUZsnSZACgBESgLQAxAPKuAlHy4gsJEQlQQMqpEACoyAM7AAKJQEAC2ZAByMgDmHMwCMj5QMkF4pACcbnpCYMwMUMBiWk4gAUEO2jJ6Bppgso2dTtFDuvo0ZDXC9YMtsh1z3eOG0gPAAKo6o1Fq2z0TU3UNwNtBlc7hkWQxNKbAdVA5bnABgeWYVZcy17f3zI/PAKqNSuDyYdr8fAfZxvYJQqruGjeHzNRyyNqwvbLPprbbRcRo+RKBaE/YrfoyRqbPFqAldRQ0M7Qr4/O4PJ6uF7+WHnFk3Nn/Dlc4FEUHg2HvKoS+FuGJgACegqIwGUNEK/WYcCiAHdmMAABaxX7smEYkldMk4yknRb4xYM81OS2ra3U220+3EyUXJhXfl/AGc1wwDSLMmHGY2wncpmfX3ff0moMhrEGCPHbb+EViiFw87S86uOWKx7K1Xqupaoi6g0kTAEMheGhgNIcU251MTK2zQl2wkOvCd8lrN29j39r0y0gNpstttD9M9roh1wAbwIIDgAF9g2F4zHvdPG83W8BnAuoLVI9sV+vNzuQ18syoQWDc96C9CiwqlSqiGqZA1Ksa0Nf5gEA8waCoEw4DrDcOzDbEXSXYZx3pSch27DYtndVF0MZQ960MYxwPPRC00vaYM0WEMABI1y+e9XljZwjyMGQTDI0llkXKNlyIejV0Y7cgRfUU32lSl0liBJklSNI8FXPAiBUohsjyThCmKHYiDBGA8C3PAgA==)):

```csharp
using System;
using System.Globalization;

var culture_fo = CultureInfo.CreateSpecificCulture("fo-FO");

var value = TestEnum.NegativeOne;

Console.WriteLine("Invariant culture:");
CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
Console.WriteLine(value.ToString("d"));
Console.WriteLine(value.ToString("d") == "-1");

Console.WriteLine();

Console.WriteLine("fo-FO culture:");
CultureInfo.CurrentCulture = culture_fo;
CultureInfo.CurrentUICulture = culture_fo;
Console.WriteLine(value.ToString("d"));
Console.WriteLine(value.ToString("d") == "-1");

Console.WriteLine();

Console.WriteLine("Trying to override with ToString():");
CultureInfo.CurrentCulture = culture_fo;
CultureInfo.CurrentUICulture = culture_fo;
Console.WriteLine(value.ToString("d", CultureInfo.InvariantCulture));
Console.WriteLine(value.ToString("d", CultureInfo.InvariantCulture) == "-1");

Console.WriteLine();

Console.WriteLine("Trying to override with string.Format():");
CultureInfo.CurrentCulture = culture_fo;
CultureInfo.CurrentUICulture = culture_fo;
Console.WriteLine(string.Format(CultureInfo.InvariantCulture, "{0:d}", value));
Console.WriteLine(string.Format(CultureInfo.InvariantCulture, "{0:d}", value) == "-1");

Console.WriteLine();

Console.WriteLine("Trying to override with interpolated string:");
CultureInfo.CurrentCulture = culture_fo;
CultureInfo.CurrentUICulture = culture_fo;
Console.WriteLine(string.Create(CultureInfo.InvariantCulture, $"{value:d}"));
Console.WriteLine(string.Create(CultureInfo.InvariantCulture, $"{value:d}") == "-1");

enum TestEnum
{
    NegativeOne = -1,
}
```

Results:

```
Invariant culture:
-1
True

fo-FO culture:
−1
False

Trying to override with ToString():
−1
False

Trying to override with string.Format():
−1
False

Trying to override with interpolated string:
−1
False
```

**Comment by bradwilson** [comment]
> Perhaps the question is why the Enum.ToString overloads that take an IFormatProvider are ignoring it.

My guess is that decision predates printing negative integers with a symbol other than U+002D (and/or `Enum.Parse` and friends need to be updated to accommodate other negative and positive symbols).

https://en.wikipedia.org/wiki/Plus_and_minus_signs#Character_codes

**Comment by bradwilson** [comment]
It's worth noting that `int.Parse` doesn't have a problem with U+2212:

```csharp
using System;
using System.Globalization;

var culture = CultureInfo.CreateSpecificCulture("fo-FO");
CultureInfo.CurrentCulture = culture;
CultureInfo.CurrentUICulture = culture;

var value = (-1).ToString();
Console.WriteLine(int.Parse(value) == -1);
Console.WriteLine(value == "-1");
```

Results:

```
True
False
```

**Comment by bradwilson** [comment]
I do want to circle back to the original ask: `Enum.ToString()` should have way to produce a "safe to roundtrip" format that does not depend on culture (especially because the format provider overloads are marked `[Obsolete]` and don't use the format provider, so I cannot specify the invariant culture myself).

In my mind, there a couple fixes possible here:

1. Add a new format string for culture-invariant round-trippable value
2. Update `"d"` to become culture invariant
3. Update all integral values from `ToString()` to become culture invariant

Additionally, if you don't choose option 3 above, then you _also_ need to fix the bug where enum values can be printed with `ToString()` that are not `Parse()`able.

**Comment by danmoseley** [comment]
4 seems to me to be the most appealing. And fixing parse to honor culture.

**Comment by bradwilson** [comment]
If you do option 4, it's worth verifying that CA1305 will properly trigger again when given the newly un-obsoleted overloads. It's not explicitly listed as skipped in [the documentation](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305#cause) so it may be that just the observation of `[Obsolete]` is what causes CA1305 to not trigger today (in which case it won't require updating), but it's worth double checking anyway. 😄
