### ISSUE TITLE
System.Runtime.Tests have 6 tests failing on my machine - daylight time

### ISSUE THREAD

**Issue by Evangelink** [dotnet/runtime#93736]
### Description

Following recommendation from @ViktorHofer I am opening an issue about 6 tests that are failing locally on my machine.

Content of the testResults.xml file:

```xml
<test name="System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC-08:00) Pacific Time (US &amp; Canada), displayName: \&quot;(UTC-08:00) Pacific Time (US &amp; Canada)\&quot;, alternativeDisplayName: null, standardName: \&quot;Pacific Standard Time\&quot;, daylightName: \&quot;Pacific Daylight Time\&quot;)" type="System.Tests.TimeZoneInfoTests" method="Platform_TimeZoneNames" time="0.0152797" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure: Strings differ\r\n                   ↓ (pos 8)\r\nExpected: \"Pacific Daylight Time\"\r\nActual:   \"Pacific Summer Time\"\r\n                   ↑ (pos 8)]]></message>
          <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(TimeZoneInfo tzi, String displayName, String alternativeDisplayName, String standardName, String daylightName) in C:\src\dotnet-runtime\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 154
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in C:\src\dotnet-runtime\src\coreclr\System.Private.CoreLib\src\System\Reflection\MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in C:\src\dotnet-runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\MethodBaseInvoker.cs:line 268]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC+10:00) Canberra, Melbourne, Sydney, displayName: \&quot;(UTC+10:00) Canberra, Melbourne, Sydney\&quot;, alternativeDisplayName: null, standardName: \&quot;AUS Eastern Standard Time\&quot;, daylightName: \&quot;AUS Eastern Daylight Time\&quot;)" type="System.Tests.TimeZoneInfoTests" method="Platform_TimeZoneNames" time="0.0008159" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure: Strings differ\r\n                       ↓ (pos 12)\r\nExpected: \"AUS Eastern Daylight Time\"\r\nActual:   \"AUS Eastern Summer Time\"\r\n                       ↑ (pos 12)]]></message>
          <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(TimeZoneInfo tzi, String displayName, String alternativeDisplayName, String standardName, String daylightName) in C:\src\dotnet-runtime\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 154
   at InvokeStub_TimeZoneInfoTests.Platform_TimeZoneNames(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC+08:00) Perth, displayName: \&quot;(UTC+08:00) Perth\&quot;, alternativeDisplayName: null, standardName: \&quot;W. Australia Standard Time\&quot;, daylightName: \&quot;W. Australia Daylight Time\&quot;)" type="System.Tests.TimeZoneInfoTests" method="Platform_TimeZoneNames" time="0.0002613" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure: Strings differ\r\n                        ↓ (pos 13)\r\nExpected: \"W. Australia Daylight Time\"\r\nActual:   \"W. Australia Summer Time\"\r\n                        ↑ (pos 13)]]></message>
          <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(TimeZoneInfo tzi, String displayName, String alternativeDisplayName, String standardName, String daylightName) in C:\src\dotnet-runtime\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 154
   at InvokeStub_TimeZoneInfoTests.Platform_TimeZoneNames(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC+03:30) Tehran, displayName: \&quot;(UTC+03:30) Tehran\&quot;, alternativeDisplayName: null, standardName: \&quot;Iran Standard Time\&quot;, daylightName: \&quot;Iran Daylight Time\&quot;)" type="System.Tests.TimeZoneInfoTests" method="Platform_TimeZoneNames" time="0.0002572" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure: Strings differ\r\n                ↓ (pos 5)\r\nExpected: \"Iran Daylight Time\"\r\nActual:   \"Iran Summer Time\"\r\n                ↑ (pos 5)]]></message>
          <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(TimeZoneInfo tzi, String displayName, String alternativeDisplayName, String standardName, String daylightName) in C:\src\dotnet-runtime\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 154
   at InvokeStub_TimeZoneInfoTests.Platform_TimeZoneNames(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC-03:30) Newfoundland, displayName: \&quot;(UTC-03:30) Newfoundland\&quot;, alternativeDisplayName: null, standardName: \&quot;Newfoundland Standard Time\&quot;, daylightName: \&quot;Newfoundland Daylight Time\&quot;)" type="System.Tests.TimeZoneInfoTests" method="Platform_TimeZoneNames" time="0.0002553" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure: Strings differ\r\n                        ↓ (pos 13)\r\nExpected: \"Newfoundland Daylight Time\"\r\nActual:   \"Newfoundland Summer Time\"\r\n                        ↑ (pos 13)]]></message>
          <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(TimeZoneInfo tzi, String displayName, String alternativeDisplayName, String standardName, String daylightName) in C:\src\dotnet-runtime\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 154
   at InvokeStub_TimeZoneInfoTests.Platform_TimeZoneNames(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(tzi: (UTC-03:00) City of Buenos Aires, displayName: \&quot;(UTC-03:00) City of Buenos Aires\&quot;, alternativeDisplayName: null, standardName: \&quot;Argentina Standard Time\&quot;, daylightName: \&quot;Argentina Daylight Time\&quot;)" type="System.Tests.TimeZoneInfoTests" method="Platform_TimeZoneNames" time="0.00026" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure: Strings differ\r\n                     ↓ (pos 10)\r\nExpected: \"Argentina Daylight Time\"\r\nActual:   \"Argentina Summer Time\"\r\n                     ↑ (pos 10)]]></message>
          <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.Platform_TimeZoneNames(TimeZoneInfo tzi, String displayName, String alternativeDisplayName, String standardName, String daylightName) in C:\src\dotnet-runtime\src\libraries\System.Runtime\tests\System\TimeZoneInfoTests.cs:line 154
   at InvokeStub_TimeZoneInfoTests.Platform_TimeZoneNames(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
```

### Reproduction Steps

I have cloned the repository and followed the steps to build and run tests locally. I see that 6 tests are failing.

### Expected behavior

All tests are green/passed

### Actual behavior

6 tests are consistently failing

### Other information

My machine is set for Czech Republic in case it impacts the tests.

**Comment by tarekgh** [comment]
@Evangelink could you please send more information regarding what OS and OS version you have? What is the default time zone on that machine? Are there any customized user's settings related to time zone on that machine?
