### ISSUE TITLE
[wasm] MeterDisposeTest is failing

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#93754]
Starting in #93337 MeterDisposeTest started failing on wasm

```
[13:39:53] info: [2023-10-19T13:39:53.690Z] [FAIL] Microsoft.Extensions.Diagnostics.Metrics.Tests.DefaultMetricsFactoryTests.MeterDisposeTest
[13:39:53] info: Assert.Equal() Failure: Values differ
[13:39:53] info: Expected: 10
[13:39:53] info: Actual:   0
[13:39:53] info:    at Microsoft.Extensions.Diagnostics.Metrics.Tests.DefaultMetricsFactoryTests.MeterDisposeTest()
[13:39:53] info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[13:39:53] info:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by SamMonoRT** [comment]
@lewing @radical  - I'm not sure who the right owner is, but I assigned @radical for tracking. Reach out to Vlad if indeed an interpreter issue (I don't think it is though). I also added disabled-test label, and removed the untriaged label, setting it to 9.0.0

**Comment by lewing** [comment]
@mkhamoyan please check if the test is still failing and update the status here

**Comment by mkhamoyan** [comment]
@lewing I have checked, and the test is still failing.
