### ISSUE TITLE
Test failure profiler\\assembly\\ALCTest\\ALCTest.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93768]
**Failed in:** [runtime-coreclr outerloop 20231019.7](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444989&view=ms.vss-test-web.build-test-results-tab&runId=9952650&resultId=100038&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows arm64 Checked @ Windows.11.Arm64.Open
    - profiler\\assembly\\ALCTest\\ALCTest.cmd
```

**Error message:**
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\..\TestFile\TestFile.dll'. The process cannot access the file because it is being used by another process. (0x80070020)
File name: 'C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\..\TestFile\TestFile.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at TestLibrary.Utilities.ExecuteAndUnloadInternal(String assemblyPath, String[] args, Action`1 unloadingCallback, WeakReference& alcWeakRef)
   at TestLibrary.Utilities.ExecuteAndUnload(String assemblyPath, String[] args, Action`1 unloadingCallback)
   at Profiler.Tests.ALCTest.RunTest(String[] args)
   at Profiler.Tests.ALCTest.Main(String[] args)
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.ALCTest.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AE7009D0\w\AF500966\uploads\Reports\profiler.assembly\ALCTest\ALCTest.output.txt
Raw output:
BEGIN EXECUTION
ALCTest.dll
eventpipe_common.dll
Microsoft.Diagnostics.NETCore.Client.dll
Profiler.dll
profiler_common.dll
TestLibrary.dll
        6 file(s) copied.
 6:18:53.97
Response file: C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\ALCTest.dll.rsp
C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\IL-CG2\ALCTest.dll
-o:C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\ALCTest.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AE7009D0\p\System.*.dll
-r:C:\h\w\AE7009D0\p\Microsoft.*.dll
-r:C:\h\w\AE7009D0\p\xunit.*.dll
-r:C:\h\w\AE7009D0\p\mscorlib.dll
-r:C:\h\w\AE7009D0\p\netstandard.dll
" "dotnet" "C:\h\w\AE7009D0\p\crossgen2\crossgen2.dll" @"C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\ALCTest.dll.rsp"   -r:C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\ALCTest.dll
" "dotnet" "C:\h\w\AE7009D0\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\ALCTest.dll --out C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\ALCTest.dll.r2rdump --val"
 6:18:56.96
 6:18:56.97
Response file: C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\eventpipe_common.dll.rsp
C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\IL-CG2\eventpipe_common.dll
-o:C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\eventpipe_common.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AE7009D0\p\System.*.dll
-r:C:\h\w\AE7009D0\p\Microsoft.*.dll
-r:C:\h\w\AE7009D0\p\xunit.*.dll
-r:C:\h\w\AE7009D0\p\mscorlib.dll
-r:C:\h\w\AE7009D0\p\netstandard.dll
" "dotnet" "C:\h\w\AE7009D0\p\crossgen2\crossgen2.dll" @"C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\eventpipe_common.dll.rsp"   -r:C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\eventpipe_common.dll
" "dotnet" "C:\h\w\AE7009D0\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\eventpipe_common.dll --out C:\h\w\AE7009D0\w\AF500966\e\profiler\assembly\ALCTest\eventpipe_common.dll.r2rdump --val"
 6:19:00.05
 6:19:00.
```

**Stack trace:**
```
   at profiler_assembly._ALCTest_ALCTest_._ALCTest_ALCTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed again in:** [runtime-coreclr r2r-extra 20240114.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=526984&view=ms.vss-test-web.build-test-results-tab&runId=12409952&resultId=100057&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows arm64 Checked jitstress1_tiered @ Windows.11.Arm64.Open
    - profiler\\assembly\\ALCTest\\ALCTest.cmd
```

**Error message:**
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\..\TestFile\TestFile.dll'. The process cannot access the file because it is being used by another process. (0x80070020)
File name: 'C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\..\TestFile\TestFile.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at TestLibrary.Utilities.ExecuteAndUnloadInternal(String assemblyPath, String[] args, Action`1 unloadingCallback, WeakReference& alcWeakRef)
   at TestLibrary.Utilities.ExecuteAndUnload(String assemblyPath, String[] args, Action`1 unloadingCallback)
   at Profiler.Tests.ALCTest.RunTest(String[] args)
   at Profiler.Tests.ALCTest.Main(String[] args)
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.ALCTest.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A06208FB\w\A1A40975\uploads\Reports\profiler.assembly\ALCTest\ALCTest.output.txt
Raw output:
BEGIN EXECUTION
ALCTest.dll
eventpipe_common.dll
Microsoft.Diagnostics.NETCore.Client.dll
Profiler.dll
profiler_common.dll
TestLibrary.dll
        6 file(s) copied.
 3:57:57.50
Response file: C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\ALCTest.dll.rsp
C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\IL-CG2\ALCTest.dll
-o:C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\ALCTest.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A06208FB\p\System.*.dll
-r:C:\h\w\A06208FB\p\Microsoft.*.dll
-r:C:\h\w\A06208FB\p\xunit.*.dll
-r:C:\h\w\A06208FB\p\mscorlib.dll
-r:C:\h\w\A06208FB\p\netstandard.dll
" "dotnet" "C:\h\w\A06208FB\p\crossgen2\crossgen2.dll" @"C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\ALCTest.dll.rsp"   -r:C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\ALCTest.dll
" "dotnet" "C:\h\w\A06208FB\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\ALCTest.dll --out C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\ALCTest.dll.r2rdump --val"
 3:57:59.78
 3:57:59.81
Response file: C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\eventpipe_common.dll.rsp
C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\IL-CG2\eventpipe_common.dll
-o:C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\eventpipe_common.dll
--targetarch:arm64
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A06208FB\p\System.*.dll
-r:C:\h\w\A06208FB\p\Microsoft.*.dll
-r:C:\h\w\A06208FB\p\xunit.*.dll
-r:C:\h\w\A06208FB\p\mscorlib.dll
-r:C:\h\w\A06208FB\p\netstandard.dll
" "dotnet" "C:\h\w\A06208FB\p\crossgen2\crossgen2.dll" @"C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\eventpipe_common.dll.rsp"   -r:C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\IL-CG2\*.dll"
Emitting R2R PE file: C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\eventpipe_common.dll
" "dotnet" "C:\h\w\A06208FB\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\eventpipe_common.dll --out C:\h\w\A06208FB\w\A1A40975\e\profiler\assembly\ALCTest\eventpipe_common.dll.r2rdump --val"
 3:58:02.11
 3:58:02.
```

**Stack trace:**
```
   at profiler_assembly._ALCTest_ALCTest_._ALCTest_ALCTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr jitstress-random 20240505.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666195&view=ms.vss-test-web.build-test-results-tab&runId=16524308&resultId=100003&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - profiler\\assembly\\ALCTest\\ALCTest.cmd
```

**Error message:**
```
 
Assert failure(PID 2976 [0x00000ba0], Thread: 5164 [0x142c]): Assertion failed 'firstILBlock->hasProfileWeight()' in 'System.Diagnostics.Process:RaiseOnExited():this' during 'Compute block weights' (IL size 54; hash 0x98ba2134; Tier0-MinOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fgprofile.cpp:4544
    Image: C:\h\w\A3C608B7\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A3C608B7\w\AB2209AF\uploads\Reports\profiler.assembly\ALCTest\ALCTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A3C608B7\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ALCTest.dll 
Profiler path: C:\h\w\A3C608B7\w\AB2209AF\e\profiler\assembly\ALCTest\Profiler.dll
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Unload succeeded - C:\h\w\A3C608B7\w\AB2209AF\e\profiler\assembly\ALCTest\..\TestFile\TestFile.dll
Profiler.dll!Profiler::Shutdown
PROFILER TEST PASSES

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/5/2024 7:48:55 PM
Processing C:\cores\corerun.exe.2976.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A3C608B7\p
> C:\h\w\A3C608B7\w\AB2209AF\e\profiler\assembly\ALCTest\ALCTest.cmd
```

**Stack trace:**
```
   at profiler_assembly._ALCTest_ALCTest_._ALCTest_ALCTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
No mention in months; removing blocking-outerloop
