### ISSUE TITLE
ILLink : InvalidCastException in AssemblyReferencesCorrector

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#93796]
Repro:

`dotnet new console`

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="Walter.Web.FireWall.EventLog" />

        <PackageReference Include="Walter.Web.FireWall.EventLog" Version="2021.8.9.1105" />
    </ItemGroup>
</Project>
```

`dotnet publish`

Interesting output:
```
  Fatal error in IL Linker
  Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.ModuleDefinition' to type
   'Mono.Cecil.AssemblyNameReference'.
     at Mono.Linker.Steps.SweepStep.AssemblyReferencesCorrector.ProcessTypeReference(TypeReference type)
     at Mono.Linker.TypeReferenceWalker.WalkScopeOfTypeReference(TypeReference type)
     at Mono.Linker.TypeReferenceWalker.WalkMethodReference(MethodReference mr)
     at Mono.Linker.TypeReferenceWalker.WalkTypeScope(MethodBody body)
     at Mono.Linker.TypeReferenceWalker.WalkScopes(TypeDefinition typeDefinition)
     at Mono.Linker.TypeReferenceWalker.Process()
     at Mono.Linker.Steps.SweepStep.SweepAssemblyReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.SweepAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.ProcessAssemblyAction(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.Process()
     ....
```

/cc @LakshanF

**Comment by vitek-karas** [comment]
Went through the cases which were causing this, all of them are obfuscated assemblies which cause several problems in the trimmer. Ignoring the exception, the analysis will not work properly because of compiler generated code. The obfuscators rename types, including the compiler generated types. Our logic is currently based on detecting patterns in the type names to detect compiler generated types, but that breaks down with obfuscation. Running these through a debug trimmer causes multiple asserts in different places.

It's unlikely we will take fixes to support these - unless we make a larger push to support obfuscated code in general.
