### ISSUE TITLE
ILLink: argument exception in Cecil when writing assembly

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#93797]
Repro:

`dotnet new console`

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="Syncfusion.Maui.Gauges" />

        <PackageReference Include="Syncfusion.Maui.Gauges" Version="20.4.40" />
    </ItemGroup>
</Project>
```

`dotnet publish`

Stack trace from the output:
```
   ---> System.ArgumentException: Member 'Syncfusion.Maui.Graphics.Internals.IDrawableView' is declared in another modu
  le and needs to be imported
     at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
     at Mono.Cecil.SignatureWriter.MakeTypeDefOrRefCodedRID(TypeReference type)
     at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
     at Mono.Cecil.SignatureWriter.WriteGenericInstanceSignature(IGenericInstance instance)
     at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
     at Mono.Cecil.MetadataBuilder.GetTypeSpecSignature(TypeReference type)
     at Mono.Cecil.MetadataBuilder.GetTypeSpecToken(TypeReference type)
     at Mono.Cecil.MetadataBuilder.GetTypeToken(TypeReference type)
     at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
     at Mono.Cecil.MetadataBuilder.AddTypes()
     at Mono.Cecil.MetadataBuilder.BuildTypes()
     at Mono.Cecil.MetadataBuilder.BuildModule()
     at Mono.Cecil.MetadataBuilder.BuildMetadata()
     at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
     at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
     at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
     at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writ
  erParameters)
```

/cc @LakshanF

**Comment by vitek-karas** [comment]
Similar failure on a different package - worth validating on the same fix:

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>

        <TargetPackageName>NewPlatform.Flexberry.ORM.ODataService</TargetPackageName>
        <TargetPackageVersion>7.0.0</TargetPackageVersion>
        <TargetAssemblyName></TargetAssemblyName>

        <TargetAssemblyName Condition="'$(TargetAssemblyName)' == ''">$(TargetPackageName)</TargetAssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="$(TargetAssemblyName)" />

        <PackageReference Include="$(TargetPackageName)" Version="$(TargetPackageVersion)" />
    </ItemGroup>

    <Target Name="ConfigureTrimming"
            BeforeTargets="PrepareForILLink">
        <ItemGroup>
          <ManagedAssemblyToLink Condition="'%(Filename)' == '$(TargetAssemblyName)'">
              <TrimmerSingleWarn>false</TrimmerSingleWarn>
          </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
</Project>
```

Stack trace:
```
  Fatal error in IL Linker
  Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net8.0
  \win-x64\linked\Microsoft.AspNetCore.OData.dll'.
   ---> System.ArgumentException: Member 'Microsoft.AspNet.OData.Batch.ODataBatchMiddleware' is declared in another mod
  ule and needs to be imported
     at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
     at Mono.Cecil.SignatureWriter.MakeTypeDefOrRefCodedRID(TypeReference type)
     at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
     at Mono.Cecil.SignatureWriter.WriteGenericInstanceSignature(IGenericInstance instance)
     at Mono.Cecil.MetadataBuilder.GetMethodSpecSignature(MethodSpecification method_spec)
     at Mono.Cecil.MetadataBuilder.CreateMethodSpecRow(MethodSpecification method_spec)
   ...
     at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writ
  erParameters)
```

**Comment by danmoseley** [comment]
is the bug here that it should not be dumping stack? or that it should not be failing? I was going to open a bug for the former, perhaps this covers it. dumping stack when it's not a bug on us is ugly.
```
ILLink : error IL1011: Failed to write 'obj\Debug\net8.0\linked\System.Private.CoreLib.dll'. [D:\a\aspire-samples\aspire-samples\samples\Metrics\MetricsApp.Client\MetricsApp.Client.csproj]
  Fatal error in IL Linker
  Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Debug\net8.0\linked\System.Private.CoreLib.dll'.
   ---> System.IO.IOException: The process cannot access the file 'D:\a\aspire-samples\aspire-samples\samples\Metrics\MetricsApp.Client\obj\Debug\net8.0\linked\System.Private.CoreLib.dll' because it is being used by another process.
     at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
     at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
     at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
     at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
     at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

**Comment by jkotas** [comment]
> Fail earlier and more predictably, like how Native AOT does it. 

NativeAOT tries to be resilient against missing assemblies where possible. It is not 100% resilient, but it covers a lot of the common situations. We have actually done work to make native AOT more resilient based on customer reports. There are a lot of assemblies and packages with dangling references in the wild. 

cc @MichalStrehovsky

**Comment by jkotas** [comment]
I think so. (It would not be must-fix bug - we would be ok with won't fixing it if the fix is too complicated or invasive.)
