### ISSUE TITLE
ILLink: ArgumentOutOfRangeException in ILProcessor

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#93802]
Repro:

`dotnet new console`

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="Kodeo.Doctum.Test" />

        <PackageReference Include="Kodeo.Doctum.Test" Version="6.0.0-beta008" />
    </ItemGroup>
</Project>
```

`dotnet publish`

Stack trace:
```
  Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Pa
  rameter 'target')
     at Mono.Cecil.Cil.ILProcessor.InsertAfter(Instruction target, Instruction instruction)
     at Mono.Linker.LinkerILProcessor.InsertAfter(Instruction target, Instruction instruction)
     at Mono.Linker.Steps.MarkStep.ProcessPendingTypeChecks()
     at Mono.Linker.Steps.MarkStep.Process()
```

/cc @LakshanF

**Comment by vitek-karas** [comment]
That looks like obfuscated code - if that's the case we should probably close it. None of our compiler generated code logic will work when it's renamed/obfuscated.

**Comment by sbomer** [comment]
Not a high priority since we don't support obfuscated code - but I think we should at least avoid crashing on this kind of input.
