### ISSUE TITLE
ILLink: argument out of range when formatting MSBuild message for a warning

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#93804]
Repro:

`dotnet new console`

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>
        <TrimmerSingleWarn>false</TrimmerSingleWarn>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="callback.CBFSStorage" />

        <PackageReference Include="callback.CBFSStorage" Version="22.0.8517" />
    </ItemGroup>
</Project>
```

`dotnet publish`

Stack trace:
```
  Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Pa
  rameter 'start')
     at Mono.Linker.MethodReferenceExtensions.GetDisplayName(MethodReference method)
     at Mono.Linker.MessageContainer.ToMSBuildString()
     at Mono.Linker.MessageContainer.ToString()
     at Mono.Linker.ConsoleLogger.LogMessage(MessageContainer message)
     at Mono.Linker.LinkContext.LogMessage(MessageContainer message)
     at Mono.Linker.LinkContext.FlushCachedWarnings()
     at Mono.Linker.Steps.ProcessWarningsStep.Process()
```

/cc @LakshanF

**Comment by vitek-karas** [comment]
Likely the same root cause as for a failure with somewhat different callstack.

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>

        <TargetPackageName>Volo.Abp.EntityFrameworkCore.Oracle.Devart</TargetPackageName>
        <TargetPackageVersion>7.2.3</TargetPackageVersion>
        <TargetAssemblyName></TargetAssemblyName>

        <TargetAssemblyName Condition="'$(TargetAssemblyName)' == ''">$(TargetPackageName)</TargetAssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="$(TargetAssemblyName)" />

        <PackageReference Include="$(TargetPackageName)" Version="$(TargetPackageVersion)" />
    </ItemGroup>

    <Target Name="ConfigureTrimming"
            BeforeTargets="PrepareForILLink">
        <ItemGroup>
          <ManagedAssemblyToLink Condition="'%(Filename)' == '$(TargetAssemblyName)'">
              <TrimmerSingleWarn>false</TrimmerSingleWarn>
          </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
</Project>
```

The new callstack looks like:
```
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Pa
  rameter 'start')
     at Mono.Linker.MethodReferenceExtensions.GetDisplayName(MethodReference method)
     at Mono.Linker.Steps.UnreachableBlocksOptimizer.ProcessMethod(MethodDefinition method)
     at Mono.Linker.LinkContext.GetMethodIL(MethodDefinition method)
     at Mono.Linker.LinkContext.GetMethodIL(MethodBody methodBody)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin
  )
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

**Comment by vitek-karas** [comment]
In both cases the failure occurs on an obfuscated assembly. It has a method is a property getter, but doesn't have the `.get` suffix in the name.

No plan to address any of these.
