### ISSUE TITLE
Test failure baseservices\\exceptions\\unittests\\Baadbaad\\Baadbaad.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93847]
Run: [runtime-coreclr r2r-extra 20231021.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=446782&view=ms.vss-test-web.build-test-results-tab&runId=9998198&resultId=105483&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_jitstress1 @ Windows.11.Arm64.Open
- baseservices\\exceptions\\unittests\\RethrowAndFinally\\RethrowAndFinally.cmd
- ilasm\\PortablePdb\\IlasmPortablePdbTests\\IlasmPortablePdbTests.cmd
- baseservices\\exceptions\\unittests\\RecursiveThrowNew\\RecursiveThrowNew.cmd
- baseservices\\exceptions\\sharedexceptions\\emptystacktrace\\OOMException01\\OOMException01.cmd
- baseservices\\exceptions\\unittests\\Baadbaad\\Baadbaad.cmd
... ...
```
**Error message:**
```
Assert failure(PID 2892 [0x00000b4c], Thread: 1248 [0x04e0]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")


CORECLR! Object::ValidateInner'::1'::catch$12 + 0x134 (0x00007ff9d6a53a7c) CORECLR! CallSettingFrame + 0x68 (0x00007ff9d6243000)
CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x1C0 (0x00007ff9d6909200) NTDLL! RtlCaptureContext + 0x1B8 (0x00007ffa42692248)
CORECLR! Object::ValidateInner + 0x144 (0x00007ff9d638b8c4) CORECLR! Object::Validate + 0xA4 (0x00007ff9d638b664)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ff9d6634be0) CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x127C (0x00007ff9d663339c)
CORECLR! EECodeManager::EnumGcRefs + 0x2CC (0x00007ff9d62d105c) CORECLR! GcStackCrawlCallBack + 0x43C (0x00007ff9d649e61c)
File: D:\a_work\1\s\src\coreclr\vm\object.cpp Line: 600
Image: C:\h\w\C1EE0A40\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\C1EE0A40\w\A62D08CA\uploads\Reports\baseservices.exceptions\unittests\RethrowAndFinally\RethrowAndFinally.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\C1EE0A40\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  RethrowAndFinally.dll

RethrowAndFinallysTest

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 10/21/2023 11:31:57 PM
Processing C:\cores\corerun.exe.2892.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:



set CORE_ROOT=C:\h\w\C1EE0A40\p
C:\h\w\C1EE0A40\w\A62D08CA\e\baseservices\exceptions\unittests\RethrowAndFinally\RethrowAndFinally.cmd




Stack trace
   at baseservices_exceptions._unittests_RethrowAndFinally_RethrowAndFinally_._unittests_RethrowAndFinally_RethrowAndFinally_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment]
Closing since this is an old issue.
