### ISSUE TITLE
[NativeAOT] DWARF debug info is generated for trimmed static fields

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#93868]
This can be trivially reproduced with the `Reflection_FromUsage` smoke test in the repository and dumping the debugging information with `dwarfdump`/`llvm-dwarfdump`. It contains debugging information for the `Bool` type (`System.Boolean` with shorten name) and the `TrueString` and `FalseString` static fields. The actual static fields don't exist in the executable.

I tried to fix it with https://github.com/dotnet/runtime/pull/92705/commits/4ce59b178619fdc842c86ecd47f48040e60f7f88 but unfortunately it doesn't pass the CI (compiling crossgen2 with ILC on osx-x64/osx-arm64):
```
  Process terminated. Assertion failed.
     at ILCompiler.PreinitializationManager.PreinitializationInfoHashtable.CreateValueFromKey(MetadataType key) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/PreinitializationManager.cs:line 161
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 562
     at ILCompiler.PreinitializationManager.GetPreinitializationInfo(MetadataType type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/PreinitializationManager.cs:line 131
     at ILCompiler.PreinitializationManager.IsPreinitialized(MetadataType type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/PreinitializationManager.cs:line 94
     at ILCompiler.DependencyAnalysis.GCStaticsNode..ctor(MetadataType type, PreinitializationManager preinitManager) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/GCStaticsNode.cs:line 25
     at ILCompiler.DependencyAnalysis.NodeFactory.<CreateNodeCaches>b__38_2(MetadataType type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 189
     at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
     at ILCompiler.DependencyAnalysis.NodeFactory.NodeCache`2.GetOrAdd(TKey key) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 152
     at ILCompiler.DependencyAnalysis.NodeFactory.TypeGCStaticsSymbol(MetadataType type) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/NodeFactory.cs:line 660
     at ILCompiler.UserDefinedTypeDescriptor.GetClassTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 667
     at ILCompiler.UserDefinedTypeDescriptor.GetNewTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 335
     at ILCompiler.UserDefinedTypeDescriptor.GetTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 323
     at ILCompiler.UserDefinedTypeDescriptor.GetVariableTypeIndex(TypeDesc type, Boolean needsCompleteIndex) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 273
     at ILCompiler.UserDefinedTypeDescriptor.GetClassTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 630
     at ILCompiler.UserDefinedTypeDescriptor.GetNewTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 335
     at ILCompiler.UserDefinedTypeDescriptor.GetTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 323
     at ILCompiler.UserDefinedTypeDescriptor.GetVariableTypeIndex(TypeDesc type, Boolean needsCompleteIndex) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 273
     at ILCompiler.UserDefinedTypeDescriptor.GetClassTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 630
     at ILCompiler.UserDefinedTypeDescriptor.GetNewTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 335
     at ILCompiler.UserDefinedTypeDescriptor.GetTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 323
     at ILCompiler.UserDefinedTypeDescriptor.GetVariableTypeIndex(TypeDesc type, Boolean needsCompleteIndex) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 301
     at ILCompiler.UserDefinedTypeDescriptor.GetClassTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 630
     at ILCompiler.UserDefinedTypeDescriptor.GetNewTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 335
     at ILCompiler.UserDefinedTypeDescriptor.GetTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 323
     at ILCompiler.UserDefinedTypeDescriptor.GetVariableTypeIndex(TypeDesc type, Boolean needsCompleteIndex) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 301
     at ILCompiler.UserDefinedTypeDescriptor.GetClassTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 630
     at ILCompiler.UserDefinedTypeDescriptor.GetNewTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 335
     at ILCompiler.UserDefinedTypeDescriptor.GetTypeIndex(TypeDesc type, Boolean needsCompleteType) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UserDefinedTypeDescriptor.cs:line 323
     at ILCompiler.ObjectWriter.ObjectWriter.EmitObject(String objectFilePath, IReadOnlyCollection`1 nodes, IObjectDumper dumper, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ObjectWriter/ObjectWriter.cs:line 403
     at ILCompiler.ObjectWriter.MachObjectWriter.EmitObject(String objectFilePath, IReadOnlyCollection`1 nodes, NodeFactory factory, ObjectWritingOptions options, IObjectDumper dumper, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ObjectWriter/MachObjectWriter.cs:line 680
     at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper) in /_/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 106
     at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 521
     at ILCompiler.Program.Run() in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 573
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass221_0.<.ctor>b__0(ParseResult result) in /_/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 277
     at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
     at ILCompiler.Program.Main(String[] args) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 737
```

**Comment by MichalStrehovsky** [comment]
@filipnavara I'm fixing this in #95570. When it merges, it will probably need porting a two-liner change from the object writer to the managed one.
