### ISSUE TITLE
Test failure GC\\API\\GC\\CollectionCountTest\\CollectionCountTest.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93905]
Run: [runtime-coreclr gcstress-extra 20231022.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447181&view=ms.vss-test-web.build-test-results-tab&runId=10009558&resultId=103649&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_jitstress1 @ Windows.11.Arm64.Open

- GC\\API\\GC\\CollectionCountTest\\CollectionCountTest.cmd
```
**Error message:**
```
Assert failure(PID 2812 [0x00000afc], Thread: 7924 [0x1ef4]): Consistency check failed: AV in clr at this callstack:

CORECLR! WKS::gc_heap::relocate_address + 0x150 (0x00007ffcdd5350a0) CORECLR! WKS::GCHeap::Relocate + 0xBC (0x00007ffcdd4fdfcc)
CORECLR! GcEnumObject + 0x90 (0x00007ffcdd2de050) CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x30C (0x00007ffcdd474d8c)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x127C (0x00007ffcdd47339c) CORECLR! EECodeManager::EnumGcRefs + 0x2CC (0x00007ffcdd11105c)
CORECLR! GcStackCrawlCallBack + 0x43C (0x00007ffcdd2de61c) CORECLR! Thread::StackWalkFramesEx + 0x248 (0x00007ffcdd208e08)
CORECLR! Thread::StackWalkFrames + 0x154 (0x00007ffcdd208aa4) CORECLR! ScanStackRoots + 0x28C (0x00007ffcdd2dcff4)
CORECLR! GCToEEInterface::GcScanRoots + 0x1B0 (0x00007ffcdd2db760) CORECLR! WKS::gc_heap::plan_phase + 0x4054 (0x00007ffcdd5313ec)
CORECLR! WKS::gc_heap::gc1 + 0x250 (0x00007ffcdd51c158) CORECLR! WKS::gc_heap::garbage_collect + 0x680 (0x00007ffcdd51bc60)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x53C (0x00007ffcdd4fae6c) CORECLR! WKS::GCHeap::GarbageCollect + 0x1C8 (0x00007ffcdd4fa8a8)
CORECLR! WKS::GCHeap::StressHeap + 0x798 (0x00007ffcdd4ff5a8) CORECLR! DoGcStress + 0x408 (0x00007ffcdd2d7a40)
CORECLR! Thread::RedirectedHandledJITCase + 0x1A0 (0x00007ffc`dd3e2198)

.AV on tid=0x1ef4 (7924), cxr=000000CD4897BBE0, exr=000000CD4897BF70
FAILED: false


CORECLR! CHECK::Trigger + 0x1BC (0x00007ffcdd5cee0c) CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x218 (0x00007ffcdd11b180)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007ffcdd11acfc) CORECLR! CLRVectoredExceptionHandler + 0x1E4 (0x00007ffcdd11ac3c)
CORECLR! CLRVectoredExceptionHandlerShim + 0x24C (0x00007ffcdd11b54c) NTDLL! RtlTimeToSecondsSince1970 + 0x1A8 (0x00007ffd35236fc8)
NTDLL! RtlRaiseException + 0x198 (0x00007ffd3521f938) NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ffd351b2764)
CORECLR! WKS::gc_heap::relocate_address + 0x150 (0x00007ffcdd5350a0) CORECLR! WKS::GCHeap::Relocate + 0xBC (0x00007ffcdd4fdfcc)
File: D:\a_work\1\s\src\coreclr\vm\excep.cpp Line: 7177
Image: C:\h\w\ADB609EE\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\ADB609EE\w\A060093D\uploads\Reports\GC.API\GC\CollectionCountTest\CollectionCountTest.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\ADB609EE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  CollectionCountTest.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 10/23/2023 1:34:10 AM
Processing C:\cores\corerun.exe.2812.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:



set CORE_ROOT=C:\h\w\ADB609EE\p
C:\h\w\ADB609EE\w\A060093D\e\GC\API\GC\CollectionCountTest\CollectionCountTest.cmd

Stack trace
   at GC_API._GC_CollectionCountTest_CollectionCountTest_._GC_CollectionCountTest_CollectionCountTest_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr gcstress-extra 20240224.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=578457&view=ms.vss-test-web.build-test-results-tab&runId=13881206&resultId=111730&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked gcstress0xc_disabler2r_jitstress2 @ Windows.10.Amd64.Open
    - JIT/Directed/pinvoke/pinvoke-examples/pinvoke-examples.cmd
```

**Error message:**
```
 
Assert failure(PID 12216 [0x00002fb8], Thread: 9160 [0x23c8]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::plan_phase + 0x3734 (0x00007ff9`7e0729b4)
CORECLR! WKS::gc_heap::gc1 + 0x23C (0x00007ff9`7e06119c)
CORECLR! WKS::gc_heap::garbage_collect + 0x73A (0x00007ff9`7e060efa)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x4E3 (0x00007ff9`7e046d63)
CORECLR! WKS::GCHeap::GarbageCollect + 0x1F6 (0x00007ff9`7e046806)
CORECLR! WKS::GCHeap::StressHeap + 0x718 (0x00007ff9`7e04a4d8)
CORECLR! DoGcStress + 0x433 (0x00007ff9`7dce7463)
CORECLR! Thread::RedirectedHandledJITCase + 0x1C9 (0x00007ff9`7deac029)
CORECLR! Thread::RedirectedHandledJITCaseForGCStress + 0x2F (0x00007ff9`7deac30f)
CORECLR! RedirectedHandledJITCaseForGCStress_Stub + 0x26 (0x00007ff9`7e0a3b56)
<no module>! <no symbol> + 0x0 (0x00007ff9`1e89e452)
<no module>! <no symbol> + 0x0 (0x00000032`c497c5c0)
<no module>! <no symbol> + 0x0 (0x00000032`c497c9a0)
-----
.AV on tid=0x23c8 (9160), cxr=00000032C497A7C0, exr=00000032C497ACB0
FAILED: false

CORECLR! CHECK::Trigger + 0x1E6 (0x00007ff9`7e0fbfe6)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x4BB (0x00007ff9`7da3426b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x91 (0x00007ff9`7da33b41)
CORECLR! CLRVectoredExceptionHandler + 0xDFD (0x00007ff9`7da33a9d)
CORECLR! CLRVectoredExceptionHandlerShim + 0x1C0 (0x00007ff9`7da34500)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ff9`adf36b40)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ff9`adf046cb)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ff9`adf79a2a)
CORECLR! WKS::gc_heap::plan_phase + 0x3734 (0x00007ff9`7e0729b4)
CORECLR! WKS::gc_heap::gc1 + 0x23C (0x00007ff9`7e06119c)
    File: D:_work1ssrccoreclrmexcep.cpp:7166
    Image: C:hwB72A09E4pcorerun.exe


Return code:      1
Raw output file:      C:hwB72A09E4wAEF909A8uploadspinvokepinvoke-examplesoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB72A09E4pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  pinvoke-examples.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 2/24/2024 10:57:23 PM
Processing C:corescorerun.exe.12216.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwB72A09E4		mprixaln.tmp" -z "C:corescorerun.exe.12216.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.12216.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB72A09E4pPDB
Symbol search path is: C:hwB72A09E4pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Feb 24 22:57:27.000 2024 (UTC + 0:00)
System Uptime: 0 days 3:16:28.318
Process Uptime: 0 days 0:00:04.000
................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(2fb8.23c8): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
KERNELBASE!RaiseFailFastException+0xae:
00007ff9`
```
**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor229|0_230(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by mangod9** [comment]
closing since this hasn't reproed recently.
