### ISSUE TITLE
Test failure ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93955]
Run: [runtime-coreclr gcstress-extra 20231022.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=447181&view=ms.vss-test-web.build-test-results-tab&runId=10009558&resultId=104203&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_jitstress1 @ Windows.11.Arm64.Open

- ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd
```
**Error message:**
```
Assert failure(PID 9852 [0x0000267c], Thread: 4064 [0x0fe0]): HasPerInstInfo()


CORECLR! MethodTable::SanityCheck + 0xD0 (0x00007ffcdd1bfcf0) CORECLR! MethodTable::Validate + 0x1C (0x00007ffcdd1c23e4)
CORECLR! Object::ValidateInner + 0x15C (0x00007ffcdd1cb8dc) CORECLR! Object::Validate + 0xA4 (0x00007ffcdd1cb664)
CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ffcdd474be0) CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x127C (0x00007ffcdd47339c)
CORECLR! EECodeManager::EnumGcRefs + 0x2CC (0x00007ffcdd11105c) CORECLR! GcStackCrawlCallBack + 0x43C (0x00007ffcdd2de61c)
CORECLR! Thread::StackWalkFramesEx + 0x248 (0x00007ffcdd208e08) CORECLR! Thread::StackWalkFrames + 0x154 (0x00007ffcdd208aa4)
File: D:\a_work\1\s\src\coreclr\vm\methodtable.h Line: 2637
Image: C:\h\w\ADB609EE\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\ADB609EE\w\A060093D\uploads\Reports\ilasm.System\Runtime\CompilerServices\MethodImplOptionsTests\MethodImplOptionsTests.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\ADB609EE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  MethodImplOptionsTests.dll
AggressiveOptimizationTest


Assembling 'MiAggressiveOptimization.il'  to DLL --> 'MiAggressiveOptimization.dll'
Source file is UTF-8


Source file is UTF-8


Source file is UTF-8


Assembled method Program::Main
Creating PE file


Emitting classes:
Class 1:Program


Emitting fields and methods:
Global
Class 1Methods: 1;


Emitting events and properties:
Global
Class 1
Writing PE file
Operation completed successfully
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 10/23/2023 1:34:38 AM
Processing C:\cores\corerun.exe.9852.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:



set CORE_ROOT=C:\h\w\ADB609EE\p
C:\h\w\ADB609EE\w\A060093D\e\ilasm\System\Runtime\CompilerServices\MethodImplOptionsTests\MethodImplOptionsTests.cmd




Stack trace
   at ilasm_System._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_._Runtime_CompilerServices_MethodImplOptionsTests_MethodImplOptionsTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment]
This test run had 40 test failures, all GCStress-related asserts, e.g.:
```
    baseservices\compilerservices\dynamicobjectproperties\TestAPIs\TestAPIs.cmd [FAIL]
      
      Assert failure(PID 2544 [0x000009f0], Thread: 8984 [0x2318]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")
      
      CORECLR! `Object::ValidateInner'::`1'::catch$12 + 0x134 (0x00007ffc`dd893a7c)
      CORECLR! CallSettingFrame + 0x68 (0x00007ffc`dd083000)
      CORECLR! _FrameHandler3::CxxCallCatchBlock + 0x1C0 (0x00007ffc`dd749200)
      NTDLL! RtlCaptureContext + 0x1B8 (0x00007ffd`351b2248)
      CORECLR! Object::ValidateInner + 0x144 (0x00007ffc`dd1cb8c4)
      CORECLR! Object::Validate + 0xA4 (0x00007ffc`dd1cb664)
      CORECLR! GcInfoDecoder::ReportRegisterToGC + 0x160 (0x00007ffc`dd474be0)
      CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0x127C (0x00007ffc`dd47339c)
      CORECLR! EECodeManager::EnumGcRefs + 0x2CC (0x00007ffc`dd11105c)
      CORECLR! GcStackCrawlCallBack + 0x43C (0x00007ffc`dd2de61c)
          File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 600
          Image: C:\h\w\ADB609EE\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      C:\h\w\ADB609EE\w\A060093D\uploads\Reports\baseservices.compilerservices\dynamicobjectproperties\TestAPIs\TestAPIs.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\ADB609EE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  TestAPIs.dll 
      Expected: 100
      Actual: -1073740286
```

**Comment by jakobbotsch** [comment]
This seems to have resolved itself. The remaining failures in the gcstress pipelines seem to be #94393
