### ISSUE TITLE
[ILink][browser][debug] Microsoft.CodeAnalysis.Operations.DynamicMemberReferenceOperation

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#94016]
### Error Blob

```json
{
  "ErrorMessage": "Microsoft.CodeAnalysis.Operations.DynamicMemberReferenceOperation",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=451726&view=logs&j=25ff4a1f-a33e-587c-1adf-e8bafe0c741d&t=652ede7b-14bb-5de9-c266-e48d99622f63

wasm/browser target with Debug configuration
`.\build.cmd -bl -os browser -subset mono+libs -c Debug`

```
Process terminated. Assertion failed. [C:\Dev\runtime\src\mono\wasm\host\WasmAppHost.csproj]
Microsoft.CodeAnalysis.Operations.DynamicMemberReferenceOperation: C:\Dev\runtime\src\mono\wasm\host\DevServer\WebAssemblyNetDebugProxyAppBuilderExtensions.cs: (200,12)-(200,32) [C:\Dev\runtime\src\mono\wasm\host\WasmAppHost.csproj]
  at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.ProcessSingleTargetAssignment(IOperation targetOperation, IAssignmentOperation operation, LocalDataFlowState`2 state, Boolean merge) in C:\Dev\runtime\src\tools\illink\src\ILLink.RoslynAnalyzer\DataFlow\LocalDataFlowVisitor.cs:line 302
  at ILLink.RoslynAnalyzer.DataFlow.LocalDataFlowVisitor`2.ProcessAssignment(IAssignmentOperation operation, LocalDataFlowState`2 state) in C:\Dev\runtime\src\tools\illink\src\ILLink.RoslynAnalyzer\DataFlow\LocalDataFlowVisitor.cs:line 326
```

**Comment by JakeYallop** [comment]
I'm running into this when trying to build the repo locally. Is there a temporary workaround for this I can use?
```
./build.cmd -os browser -subset mono+libs
```

Its a fresh clone (the only extra step I did was to sync main from dotnet/runtime).

**Comment by JakeYallop** [comment]
That did not work unfortunately, same error as before.
