### ISSUE TITLE
Test failure in DecryptEnvelopedOctetStringWithExtraData (linux x64)

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#94067]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=452229
Build error leg or test failing: System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsRsaPaddingMode.DecryptEnvelopedOctetStringWithExtraData
Pull request: https://github.com/dotnet/runtime/pull/94060

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "error:03000072:digital envelope routines::decode error",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
Interop+Crypto+OpenSslCryptographicException : error:03000072:digital envelope routines::decode error

   at Interop.Crypto.DecodeSubjectPublicKeyInfo(ReadOnlySpan`1 source, EvpAlgorithmId algorithmId) in /_/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.EvpPkey.cs:line 76
   at System.Security.Cryptography.RSAOpenSsl.ImportSubjectPublicKeyInfo(ReadOnlySpan`1 source, Boolean checkAlgorithm, Int32& bytesRead) in /_/src/libraries/Common/src/System/Security/Cryptography/RSAOpenSsl.cs:line 544
   at System.Security.Cryptography.RSAOpenSsl.ImportRSAPublicKey(ReadOnlySpan`1 source, Int32& bytesRead) in /_/src/libraries/Common/src/System/Security/Cryptography/RSAOpenSsl.cs:line 509
   at System.Security.Cryptography.X509Certificates.OpenSslX509Encoder.BuildRsaPublicKey(Byte[] encodedData) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslX509Encoder.cs:line 269
   at System.Security.Cryptography.X509Certificates.OpenSslX509Encoder.DecodePublicKey(Oid oid, Byte[] encodedKeyValue, Byte[] encodedParameters, ICertificatePal certificatePal) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslX509Encoder.cs:line 36
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPublicKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/CertificateExtensionsCommon.cs:line 31
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPublicKey(X509Certificate2 certificate) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/RSACertificateExtensions.cs:line 19
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.MakeKtri(Byte[] cek, CmsRecipient recipient, Boolean& v0Recipient) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.KeyTrans.cs:line 171
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes, Byte[] encryptedContent, Byte[] cek, Byte[] parameterBytes) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs:line 112
   at Internal.Cryptography.Pal.AnyOS.ManagedPkcsPal.Encrypt(CmsRecipientCollection recipients, ContentInfo contentInfo, AlgorithmIdentifier contentEncryptionAlgorithm, X509Certificate2Collection originatorCerts, CryptographicAttributeObjectCollection unprotectedAttributes) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs:line 36
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipientCollection recipients) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 117
   at System.Security.Cryptography.Pkcs.EnvelopedCms.Encrypt(CmsRecipient recipient) in /_/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/EnvelopedCms.cs:line 98
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.TestSimpleDecrypt_RoundTrip(CertLoader certLoader, ContentInfo contentInfo, String algorithmOidValue, SubjectIdentifierType type, ContentInfo expectedContentInfo) in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/DecryptTests.cs:line 818
   at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.DecryptEnvelopedOctetStringWithExtraData() in /_/src/libraries/System.Security.Cryptography.Pkcs/tests/EnvelopedCms/DecryptTests.cs:line 765
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/c
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=452229
**Error message validated:** `error:03000072:digital envelope routines::decode error`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/26/2023 8:33:34 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by Jozkee** [comment]
Same as https://github.com/dotnet/runtime/issues/64816, seems to be intermittent and coming from [d2i_PUBKEY](https://github.com/dotnet/runtime/blob/771a1ab338c453f23d6277dea4534f9c115a6e01/src/native/libs/System.Security.Cryptography.Native/pal_evp_pkey.c#L150C21-L150C31).

**Comment by jeffhandley** [comment]
Added this to the 9.0.0 milestone because of the frequency

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not been hit in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by vcsjones** [comment]
I am going to close this out. I cannot reproduce it, and it does not look like this has failed in CI a few months.
