### ISSUE TITLE
Microsoft ODBC Driver for SQL Server fails with out any error message in the exception

### ISSUE THREAD

**Issue by SokolovAlexeyCode** [dotnet/runtime#94087]
**Configuration:** 
- Azure SQL DB
- Test database contains only one view. View is made from two simple tables with one join by one column. Every column is nvarchar type.  There are only 10 rows in each table. Every value in each cell is a short string. The data in  the database is very simple.
- Driver: "msodbcsql18.dll"
- Console Application with target framework NET6
- Windows Server 2019 x64

After the SQL-request has completed, I read the data. Several rows are processed successfully. And in some momemt of time the code fails. There is no error message in log file, there are no details about the cause of its occurrence.

```
await using var connection = new OdbcConnection(settings.OdbcConnectionString);
await connection.OpenAsync();
await using var command = connection.CreateCommand();

command.CommandText = "SELECT  [Col1] ,[Col2], [Col3] ,[Col4] ,[Col5], [Col6] ,[Col7] ,[Col8], [Col9] ,[Col11] ,[Col12]  FROM  [My_View] where Col2 in ('1','2', '3', '4','5','6', '7', '8', '9','10') ;";
await using var dataReader = await command.ExecuteReaderAsync();

while (await dataReader.ReadAsync())
{
    for (var i = 0; i < dataReader.FieldCount; ++i)
    {
        // Error on the random line and column
        var value = dataReader.GetValue(i);
	Console.WriteLine(value as string);
    }
}
```
**The error is** 
System.Data.Odbc.OdbcException (0x80131937)
   at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, RetCode retcode)
   at System.Data.Odbc.OdbcDataReader.GetData(Int32 i, SQL_C sqlctype, Int32 cb, Int32& cbLengthOrIndicator)
   at System.Data.Odbc.OdbcDataReader.internalGetString(Int32 i)
   at System.Data.Odbc.OdbcDataReader.GetValue(Int32 i, TypeMap typemap)
   at System.Data.Odbc.OdbcDataReader.GetValue(Int32 i)

**Comment by roji** [comment]
@SokolovAlexeyCode this is unlikely to be a problem in System.Data.Odbc per se, as opposed to the actual ODBC driver being used (the SQL Server one).

But in order to properly investigate this, we need to be able to reproduce the error - even if it's unreliable. Can you please include the schema of the test database being queried above, along with the seeding data to trigger the exception?

**Comment by SokolovAlexeyCode** [comment]
@roji thanks for the answer. Yes, I will attach the SQL with the schema but it's such a simple and primitive schema that I don't think it could be useful

**there is the important nuance:** I tried to reproduce that on the several machines and could not reproduce. **There is only one customer virtual machine where this exception occurs** after reading several rows using DataReader.  Unfortunately, I don't know the configuration ot their VM. But I know that this VM is under hard using. I started thinking that the lack of memory while DataReader is reading the data  could be the root cause, but I don not how to analyze this hypothesis. There is no a message in the exception and I cannot reproduce this situation on my configuration. 

Through the SQL Server Profiler I can see that the query to the database from the driver only goes out once. After this, the reader does its job and reads row by row several times without any problems. But at some point it fails. Row and cell don't matter - they are different every time. I don’t understand that all the information that is received from the database is stored during this time. On the ODBC driver side (and each line is requested from it in a loop) or already in the application memory. For me this System.Data.Odbc.OdbcException (0x80131937) could have a lot of reasons on the both side because I did not investigate how System.Data.Odbc is designed.  And the worst thing it is hard to reproduce.

I have tried two versions of the Microsoft ODBC driver - version 13, version 18 - the behavior the same. Thanks in advance.

```
USE [DBTests]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table1](
	[Col1] [nvarchar](50) NOT NULL,
	[Col2] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Col1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table2](
	[Col1] [nvarchar](50) NOT NULL,
	[Col3] [nvarchar](255) NULL,
	[Col4] [nvarchar](255) NULL,
	[Col5] [nvarchar](255) NULL,
	[Col6] [nvarchar](255) NULL,
	[Col7] [nvarchar](255) NULL,
	[Col8] [nvarchar](255) NULL,
	[Col9] [nvarchar](255) NULL,
	[Col10] [nvarchar](255) NULL,
	[Col11] [nvarchar](255) NULL,
	[Col12] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Col1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[My_View] AS
SELECT T1.Col1,    T1.Col2 ,    T2.Col3,    T2.Col4,    T2.Col5 ,    T2.Col6,    T2.Col7,    T2.Col8,    T2.Col9,    T2.Col10,	  T2.Col11, T2.Col12
FROM Table1 T1
INNER JOIN Table2 T2 ON T1.Col1 = T2.Col1;
GO
ALTER TABLE [dbo].[Table2]  WITH CHECK ADD FOREIGN KEY([Col1])
REFERENCES [dbo].[Table1] ([Col1])
GO
```

**Comment by roji** [comment]
@SokolovAlexeyCode I'm not sure how we can investigate this issue if it occurs only on a single VM in your platform, and cannot be reproduced... In such cases, I recommend trying to set up a console program that continuously runs the problematic in a loop - and from several threads in parallel. If an error exists, then in many cases this can trigger it after a while - that's enough of a repro.

**Comment by SokolovAlexeyCode** [comment]
@roji Thanks for the answer. I'll try the method you suggested. Yes, I understand that the situation is not the most convenient and quite bad for research. My hope was that perhaps you knew from your own experience a limited range of reasons why such an exception could occur without the exception message. Thanks for the advice.
