### ISSUE TITLE
[ODBC] SSL_read error coming when calling a table valued function

### ISSUE THREAD

**Issue by alpha-gamma** [dotnet/runtime#94170]
### Description

When trying to call a table valued function created in Databricks from C# code using System.Data.Odbc, i am getting the following error - 

```
System.AggregateException: One or more errors occurred. (ERROR [08S01] [Simba][Hardy] (115) Connection failed with error: SSL_read: Interrupted system call)
 ---> System.Data.Odbc.OdbcException (0x80131937): ERROR [08S01] [Simba][Hardy] (115) Connection failed with error: SSL_read: Interrupted system call
   at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, SQLRETURN retcode)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Odbc.OdbcCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
```

The code works fine when I query data from a normal table.

The application is running on AKS. 

The table valued function calls works in the below scenarios - 
1. when I login into the pod and manually run the sql in cli using ISQL.
2. It works with a python app using pyodbc.

### Reproduction Steps

1. Create a console application
2. Add System.Data.Odbc nuget package.
3. Write the below code

```
using (OdbcConnection connection = new("Driver=DatabricksSQL;Host=<host>;Port=443;HTTPPath=/sql/1.0/warehouses/<warehouse>;SparkServerType=3;ThriftTransport=2;SSL=1;AuthMech=3;UID=token;PWD=<token>;UseUnicode=1;"))
    {
        connection.Open();
        
        string commandText = "SELECT * FROM func_name('param1');";
        using (OdbcCommand command = new OdbcCommand(commandText, connection))
        {
            command.CommandTimeout = 600;
            try
            {
                using (OdbcDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Console.WriteLine($"reading information inside");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred while ExecuteReaderAsync with error: {ex.Message}, Inner message: {ex.InnerException?.Message}");
            }
        }
    }
```

### Expected behavior

The SQL statement should run successfully and data should be received.

### Actual behavior

ExecuteReader() method gives the below exception -

```
System.AggregateException: One or more errors occurred. (ERROR [08S01] [Simba][Hardy] (115) Connection failed with error: SSL_read: Interrupted system call)
 ---> System.Data.Odbc.OdbcException (0x80131937): ERROR [08S01] [Simba][Hardy] (115) Connection failed with error: SSL_read: Interrupted system call
   at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, SQLRETURN retcode)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Odbc.OdbcCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
```

```
Simba::SparkODBC::SOTCLIServiceUtils::ThrowOnNotSuccess: Backend returned non-SUCCESS status for operation ExecuteStatement: 
    TStatus.statusCode=ERROR_STATUS
    TStatus.infoMessages=
    TStatus.sqlState=

    TStatus.errorCode=0
    TStatus.errorMessage="org.apache.hive.service.cli.HiveSQLException: Error running query: [UNRESOLVABLE_TABLE_VALUED_FUNCTION] org.apache.spark.sql.AnalysisException: [UNRESOLVABLE_TABLE_VALUED_FUNCTION] Could not resolve func_name to a table-valu"
    TStatus.__isset.errorCode: false
    TStatus.__isset.errorMessage: false
    TStatus.__isset.infoMessages: false
    TStatus.__isset.sqlState: false
```

### Configuration

**.NET Version: 7.0**
```
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             4
On-line CPU(s) list:                0-3
Thread(s) per core:                 2
Core(s) per socket:                 2
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
```

**Comment by roji** [comment]
Apologies that this went unanswered for such a long time.

The fact that the same query works when querying a regular table - instead of a table-valued function - indicates an issue with the specific ODBC driver, as opposed to with .NET System.Data.Odbc; System.Data.Odbc is only a layer over the native ODBC driver, which is the one actually doing the work.

Please report this to Databricks for fixing on their side. If there's some specific reason to believe that System.Data.Odbc is at fault here somehow, please post back and we'll revisit.
