### ISSUE TITLE
Timezone Tests Fail with TestReadyToRun on Linux in CI

### ISSUE THREAD

**Issue by ivdiazsa** [dotnet/runtime#94190]
PR #91229 adds a new pipeline to run libraries tests with ReadyToRun, by means of the MSBuild flag `-p:TestReadyToRun=true`. However, some timezone tests don't work with _TestReadyToRun_ on Linux in the CI. It seems something is missing to setup there. This issue is to track the necessary work to fix them.

Here's an extract of the log with the failing tests:

```text
2023-10-30T21:34:56.9791963Z   [FAIL] System.Tests.TimeZoneInfoTests.ConvertTime_SameTimeZones
2023-10-30T21:34:56.9793183Z   System.TypeInitializationException : The type initializer for 'System.Tests.TimeZoneInfoTests' threw an exception.
2023-10-30T21:34:56.9794622Z   ---- System.TimeZoneNotFoundException : The time zone ID 'Europe/London' was not found on the local computer.
2023-10-30T21:34:56.9795970Z   -------- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/zoneinfo/Europe/London'.
2023-10-30T21:34:56.9797551Z      at System.Tests.TimeZoneInfoTests.ConvertTime_SameTimeZones() in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 443
2023-10-30T21:34:56.9799087Z      at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
2023-10-30T21:34:56.9800453Z      at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
2023-10-30T21:34:56.9801265Z   ----- Inner Stack Trace -----
2023-10-30T21:34:56.9801694Z      at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
2023-10-30T21:34:56.9802736Z      at System.Tests.TimeZoneInfoTests..cctor() in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 46
2023-10-30T21:34:56.9803709Z   ----- Inner Stack Trace -----
2023-10-30T21:34:56.9804388Z      at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2023-10-30T21:34:56.9805984Z      at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2023-10-30T21:34:56.9809567Z      at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2023-10-30T21:34:56.9812811Z      at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
2023-10-30T21:34:56.9814688Z      at System.TimeZoneInfo.ReadAllBytesFromSeekableNonZeroSizeFile(String path, Int32 maxFileSize)
2023-10-30T21:34:56.9815828Z      at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)
...
2023-10-30T21:34:58.9094503Z   [FAIL] Tests.System.TimeProviderTests.TestSystemProviderWithTimeZone
2023-10-30T21:34:58.9096087Z   System.TimeZoneNotFoundException : The time zone ID 'America/Los_Angeles' was not found on the local computer.
2023-10-30T21:34:58.9097677Z   ---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/usr/share/zoneinfo/America/Los_Angeles'.
2023-10-30T21:34:58.9105136Z      at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
2023-10-30T21:34:58.9106398Z      at Tests.System.TimeProviderTests.TestSystemProviderWithTimeZone() in /_/src/libraries/Common/tests/System/TimeProviderTests.cs:line 56
2023-10-30T21:34:58.9107973Z      at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
2023-10-30T21:34:58.9109288Z      at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
2023-10-30T21:34:58.9110292Z   ----- Inner Stack Trace -----
2023-10-30T21:34:58.9110973Z      at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
2023-10-30T21:34:58.9112497Z      at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2023-10-30T21:34:58.9115847Z      at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
2023-10-30T21:34:58.9119148Z      at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
2023-10-30T21:34:58.9121103Z      at System.TimeZoneInfo.ReadAllBytesFromSeekableNonZeroSizeFile(String path, Int32 maxFileSize)
2023-10-30T21:34:58.9122323Z      at System.TimeZoneInfo.TryGetTimeZoneFromLocalMachineCore(String id, TimeZoneInfo& value, Exception& e)
```

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/pull/91229/files#r1377556495

**Comment by ivdiazsa** [comment]
> https://github.com/dotnet/runtime/pull/91229/files#r1377556495

Closing as the tests were being run in the wrong place, explained in the comment linked above. In Helix, they pass as expected.
