### ISSUE TITLE
[SslStress] SocketException (111): Connection refused

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#94222]
This exception started to pop up quite often on CI in runs against `main` since 2023-10-14. To list a few runs:
- 3x in [report 10/14-19](https://github.com/dotnet/runtime/issues/42211#issuecomment-1770972051)
    - 2x in run [20231014.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=438734&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=f4d03b33-e265-5206-5dc1-b33aeb754840&l=13398)
    - 1x in run [20231018.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442616&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=f4d03b33-e265-5206-5dc1-b33aeb754840&l=11383)
- 5x in [report 10/20-31](https://github.com/dotnet/runtime/issues/42211#issuecomment-1787544999)
    - https://dev.azure.com/dnceng-public/public/_build/results?buildId=445570&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=f4d03b33-e265-5206-5dc1-b33aeb754840
    - https://dev.azure.com/dnceng-public/public/_build/results?buildId=447860&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=f4d03b33-e265-5206-5dc1-b33aeb754840
    - https://dev.azure.com/dnceng-public/public/_build/results?buildId=451951&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=f4d03b33-e265-5206-5dc1-b33aeb754840

Considering the frequency, I think we should take a look within the 9.0 timeframe.

```
System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1378
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1294
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 258
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 193
   at SslStress.SslClientBase.<StartCore>g__RunSingleWorker|15_1(Int32 workerId, Random random) in /app/System.Net.Security/tests/StressTests/SslStress/SslClientBase.cs:line 116
```

**Comment by wfurt** [comment]
clearly this is problem with either sockets or more likely infrastructure. I'm not sure if we want to track is as `System.Net.Security` issue....

**Comment by antonfirsov** [comment]
I agree that this is most likely not caused by `System.Net.Security` code, however we always tracked `SslStress` issues under `System.Net.Security`, because the SslStress project is part of the System.Net.Security test suite and we usually label test failures with the area labels where they pop up.

**Comment by rzikm** [comment]
I checked recent runs and the failures always happen in bursts at the start of the stress test. Is it possible that we are perhaps starting too early?

**Comment by antonfirsov** [comment]
That makes sense, there is no synchronization between client and server startup. We can add a CLI controllable delay in `Program.cs` to delay the client start or figure out [how to control startup order with docker compose](https://docs.docker.com/compose/startup-order/).

**Comment by rzikm** [comment]
Yeah, I tinkered with the healthcheack+depends on functionality of docker compose, I got it working, but then I realized the command I used for healthcheck will not work on Windows.... so I will just do the same thing we do for http stress
