### ISSUE TITLE
A specific HttpRequestException cannot be catched and terminates the whole Console App

### ISSUE THREAD

**Issue by HazyFish** [dotnet/runtime#94277]
### Description

A HttpRequestException with inner exception `System.Security.Authentication.AuthenticationException: Cannot determine the frame size or a corrupted frame was received.` cannot be catched and will terminate the whole Console App.

### Reproduction Steps

- Create a .NET 7 Console App.
- Create the following `RetryHandler`.

```c#
internal class RetryHandler : DelegatingHandler
{
    public RetryHandler(HttpMessageHandler innerHandler) : base(innerHandler)
    { }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        Exception? exception = null;

        for (int i = 0; i < 5; i++)
        {
            try
            {
                Console.WriteLine($"{request.Method.Method} {request.RequestUri?.AbsoluteUri}");
                var response = await base.SendAsync(request, cancellationToken);
                response.EnsureSuccessStatusCode();
                return response;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"FAILED {request.Method.Method} {request.RequestUri?.AbsoluteUri}");
                Console.WriteLine(ex);
                exception = ex;
                await Task.Delay(TimeSpan.FromSeconds(5 + 5 * i), cancellationToken);
                Console.WriteLine($"Retrying {request.Method.Method} {request.RequestUri?.AbsoluteUri} ({i + 1})");
            }
        }

        Console.WriteLine($"FAILED {request.Method.Method} {request.RequestUri?.AbsoluteUri}");
        throw exception ?? throw new ApplicationException("Failed to send request.");
    }
}
```
- Create a HttpClient with HTTP Proxy

```c#
var httpClient = new HttpClient(new RetryHandler(new HttpClientHandler
{
    Proxy = new WebProxy(...)),
}))
{
    Timeout = TimeSpan.FromSeconds(30)
};
```

- Make 1,000+ HTTP requests using the HTTP Client.

- The error will occur undeterministically (I don't understand if it's client or server's fault for triggering the Exception, but in either case, the `catch` block should be able to catch the Exception but it does not)

### Expected behavior

Since it's an `HttpRequestException`, it should be caught in `catch` block, not crashing the whole app immediately.

### Actual behavior

This specific type of `HttpRequestException` that caused by `System.Security.Authentication.AuthenticationException: Cannot determine the frame size or a corrupted frame was received.` is not caught and terminates the whole Console App with the following printed:

```
Unhandled exception: System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
   at System.Net.Security.SslStream.HaveFullTlsFrame(Int32& frameSize)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

### Configuration

- Windows 11 (x64)
- .NET 7

**Comment by wfurt** [comment]
Could you get packet captures. It seems to be coming from https://github.com/dotnet/runtime/blob/35db500cedca4e7061fe1e91390ad1df62bc0f3c/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs#L979C17-L979C17 
That of course does not explain why you would see whole whole process exit. 

This is going to be difficult to investigate as I doubt we would be able to reproduce. The fragment does not show any use of the client. Do you fetch just the header and you handle the response stream? Ofr you have have put buffer everything? And what is the role of delegating handler? Can you reproduce it without it? 

The symptoms you describing look like something throwing on thread pool. You may try to hook up https://learn.microsoft.com/en-us/dotnet/api/system.appdomain.firstchanceexception?view=net-7.0 to see if you can get more insight about pending tasks.

**Comment by HazyFish** [comment]
Hi @wfurt! Thank you so much for your prompt response. 

> Do you fetch just the header and you handle the response stream? Ofr you have have put buffer everything? And what is the role of delegating handler? Can you reproduce it without it?

I read the whole response by Stream. The delegating handler is just my attempt to catch the exception at a lower level. I can reproduce without it.

> The symptoms you describing look like something throwing on thread pool.

I have turned all my code where I used `await Task.WhenAll` to make concurrent HTTP requests into sequential await in a `foreach` loop and now the original Exception no longer throws and I'm catching Timeout exceptions like the following which I think is normal:

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 15 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)       
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.<EnsureReadAheadTaskHasStarted>g__ReadAheadWithZeroByteReadAsync|40_0()
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

Based on this, could you please give me some hints on why making concurrent HTTP Requests using Task.WhenAll could cause the non-catchable exception so I can continue my investigation?

**Comment by wfurt** [comment]
Hard to tell without having some code sample to work with. For one, if you serialize request, they will all (probably) re-use same connection. When you run requests in parallel there will be multiple connections (unless you use H/2) and some request _may_ reuse previous one. Depending on the duration, you may or may not reuse previous connections and that may have impact on the streams. 

There are to mysteries to solve: 1) why the SslStream fails to read TLS frame. That alsmot looks like the server _can_ send some extra garbage occasionally...? 2) why the exception does not propagate straight up to the caller. There still _may_ be bug somewhere but the way how the stream is consumed matters. 

As another experimenting,  could you force TLS 1.2 on either client or server and check if that makes any difference?

**Comment by HazyFish** [comment]
> Hard to tell without having some code sample to work with.

I completely understand. It's a complex piece of code and I have been trying to simplify the code step by step to reduce the scope of the problem. At this point, I cannot give a minimal sample with a reasonable amount of code.

I will try your suggestions of forcing TLS 1.2 and I think I can also try reading all responses as strings to simplify things.

I really appreciate your insights and help!!!
