### ISSUE TITLE
Error: Using UserPrincipal.GetGroups() get an exception (A local error has occurred)

### ISSUE THREAD

**Issue by scalex000** [dotnet/runtime#94282]
### Description

I get an exception when calling UserPrincipal.GetGroups method to get all user groups in the AD.  One AD DC is out of service.

Code:

 using (HostingEnvironment.Impersonate())

                {
                   // establish domain context
                    PrincipalContext _domain = new PrincipalContext(ContextType.Domain, DOMAIN_NAME);
                    // find your user
                    UserPrincipal _user = UserPrincipal.FindByIdentity(_domain, userName);
                    // if found - grab its groups

                    if (_user != null)

                    {

                       // _usuario.Mail = GetValue(_user.EmailAddress);
                       // _usuario.Nombre = GetValue(_user.GivenName);
                      //  _usuario.Apellido = GetValue(_user.Surname);
                      //  _usuario.Tarjeta = GetValue(_user.EmployeeId);
                      //  _usuario.NombreUsuario = GetValue(_user.Name);*/

                       // _usuario.Grupos = new List<Grupo>();

                        //_usuario.ListCustomerSubscriber = new List<CustomerSubscribersView>();

                         **PrincipalSearchResult<Principal> groups = _user.GetGroups();**
}
}

### Reproduction Steps

1. Create a group of domain controllers (5 DC)
2. Disable one DC.
3. Impersonate the user
4. Create the principalContext (ContextType.Domain, DOMAIN_NAME)
5. Find the identity in the principalContext of the user are log in.
6. Using the principaluser try to get the groups (GetGrupos without context).

### Expected behavior

When calling UserPrincipal.GetGroups(), needs to get the available Domain Controller from Active Directory.

### Actual behavior

When calling UserPrincipal.GetGroups() I get an exception System.DirectoryServices.AccountManagement.PrincipalOperationException: "A local error has occurred".

 at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOf(Principal p)   at System.DirectoryServices.AccountManagement.Principal.GetGroupsHelper()   at System.DirectoryServices.AccountManagement.Principal.GetGroups()   at Claro.Ajustes.Inmediatos.Service.AuthenticationService.GetUsuarioInfo(String name) in C:\Backup_D\Source Code\pcc\Service\AuthenticationService.cs:line 77

   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)   at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.ExpandWellKnownDN(WellKnownDN dn)   at System.DirectoryServices.ActiveDirectory.DomainController.get_Domain()   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOf(Principal p)

  at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)   at System.DirectoryServices.DirectoryEntry.Bind()   at System.DirectoryServices.DirectoryEntry.get_AdsObject()   at System.DirectoryServices.PropertyValueCollection.PopulateList()   at System.DirectoryServices.PropertyValueCollection..ctor(DirectoryEntry entry, String propertyName)   at System.DirectoryServices.PropertyCollection.get_Item(String propertyName)   at System.DirectoryServices.ActiveDirectory.PropertyManager.GetPropertyValue(DirectoryContext context, DirectoryEntry directoryEntry, String propertyName)

### Regression?

I will try to make the same code on .net 6

### Known Workarounds

I use the overload method UserPrincipal.GetGroups(PrincipalContext).

### Configuration

Version: .net 4.8
OS: Windows 11
Architecture: x64
Language: C#
ASP.net

### Other information

I believe the problem is on GetGroupMemberOf(Principal): Resultset at System.DirectoryServices.AccountManagementADStoreCtx.GetGroupsMemberOf(principal).

**Comment by scalex000** [comment]
@jay98014 I'm sorry after I created the bug I didn't know this repo it was only for dotnet core.  Do you know where is the .net framework repo?

**Comment by danmoseley** [comment]
@scalex000 Can you report on .NET Core? (6, 7 or 8) if do this is the right place.
If not, try https://developercommunity.visualstudio.com/dotnet

**Comment by scalex000** [comment]
I already test on .netcore it's the same

**Comment by scalex000** [comment]
> @scalex000 Can you report on .NET Core? (6, 7 or 8) if do this is the right place. If not, try https://developercommunity.visualstudio.com/dotnet

I test this using .net 6.

**Comment by scalex000** [comment]
this bug not belong to this repo.
