### ISSUE TITLE
Test failure Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#94392]
**Failed in:** [runtime-coreclr jitstress 20231104.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460190&view=ms.vss-test-web.build-test-results-tab&runId=10392310&resultId=119439&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress2_tiered @ Windows.11.Arm64.Open
    - Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.cmd
```

**Error message:**
```
 Return code:      1
Raw output file:      C:hwBC2D0A09wB4D4092FuploadsPInvokeCriticalHandlesReverseTestReverseTestoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwBC2D0A09pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ReverseTest.dll 
Expected: 100
Actual: 3
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 11/5/2023 5:42:16 AM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwBC2D0A09wB4D4092FeInteropInterop../PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor85|0_86(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-27T06:27:52.691Z | runtime-coreclr r2r | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionName":"runtime-coreclr r2r","System.PhaseName":"run_test_p1_R2R_linux_x64_checked","DefinitionId":"120","AzurePipelinesTestRunId":"8289534","operatingSystem":"Ubuntu.2204.Amd64.Open","BuildId":"387187","BuildNumber":"20230826.1","System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"x64","System.StageName":"Build","configuration":"Checked-no_tiered_compilation","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobName":"__default","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","System.JobAttempt":"1","Project":"public"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
2023-08-26T19:27:05.191Z | runtime-coreclr outerloop | Checked-no_tiered_compilation | ubuntu.2204.amd64.open.rt | x64 | Interop/PInvoke/CriticalHandles/ReverseTest/ReverseTest/ReverseTest.sh | Failed | {"DefinitionId":"108","Reason":"Schedule","BuildNumber":"20230826.3","AzurePipelinesTestRunId":"8285172","DefinitionName":"runtime-coreclr outerloop","System.StageName":"Build","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"387081","operatingSystem":"Ubuntu.2204.Amd64.Open","configuration":"Checked-no_tiered_compilation","System.PhaseName":"run_test_p1_R2R_CG2_linux_x64_checked","System.JobId":"fa2c7683-52dc-5163-1de4-3cf5b1b4c990","System.StageAttempt":"1"} | Schedule
</details>

**Comment by agocke** [comment]
Failures have fallen off. Closing.
