### ISSUE TITLE
ILLink: ArgumentException in Cecil metadata reader during marking

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#94457]
Repro:

```console
dotnet new console
```

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>

        <TargetPackageName>Aspose.PDF</TargetPackageName>
        <TargetPackageVersion>23.6.0</TargetPackageVersion>
        <TargetAssemblyName></TargetAssemblyName>

        <TargetAssemblyName Condition="'$(TargetAssemblyName)' == ''">$(TargetPackageName)</TargetAssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="$(TargetAssemblyName)" />

        <PackageReference Include="$(TargetPackageName)" Version="$(TargetPackageVersion)" />
    </ItemGroup>

    <Target Name="ConfigureTrimming"
            BeforeTargets="PrepareForILLink">
        <ItemGroup>
            <ManagedAssemblyToLink Condition="'%(Filename)' == '$(TargetAssemblyName)'">
                <TrimmerSingleWarn>false</TrimmerSingleWarn>
            </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
</Project>
```

```console
dotnet publish
```

Stack trace from the output:
```
  Fatal error in IL Linker
  Unhandled exception. System.ArgumentException: Value does not fall within the expected range.
     at Mono.Cecil.MetadataReader.GetMember[TMember](Collection`1 members, MetadataToken token)
     at Mono.Cecil.MetadataReader.GetProperty(TypeDefinition type, MetadataToken token)
     at Mono.Cecil.MetadataReader.ReadMethodSemantics(MethodDefinition method)
     at Mono.Cecil.MetadataReader.ReadAllSemantics(TypeDefinition type)
     at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read)
     at Mono.Cecil.MethodDefinition.ReadSemantics()
     at Mono.Linker.MethodDefinitionExtensions.TryGetProperty(MethodDefinition md, PropertyDefinition& property)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason, MessageOrigin& origin
  )
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

/cc @LakshanF

**Comment by vitek-karas** [comment]
Aspose.PFD is obfuscaed and causes various asserts in the trimmer - eventually leading to a crash in Cecil. No plans to address any of the problems here.
