### ISSUE TITLE
ILLink: Null ref in type reference walker during marking

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#94458]
Repro:

```console
dotnet new console
```

`app.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>true</PublishTrimmed>
        <WarningsAsErrors>false</WarningsAsErrors>
        <NoWarn>NU1605;NU1603;NU1701</NoWarn>

        <TargetPackageName>UmbraCare.Core</TargetPackageName>
        <TargetPackageVersion>11.1.0</TargetPackageVersion>
        <TargetAssemblyName></TargetAssemblyName>

        <TargetAssemblyName Condition="'$(TargetAssemblyName)' == ''">$(TargetPackageName)</TargetAssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="$(TargetAssemblyName)" />

        <PackageReference Include="$(TargetPackageName)" Version="$(TargetPackageVersion)" />
    </ItemGroup>

    <Target Name="ConfigureTrimming"
            BeforeTargets="PrepareForILLink">
        <ItemGroup>
            <ManagedAssemblyToLink Condition="'%(Filename)' == '$(TargetAssemblyName)'">
                <TrimmerSingleWarn>false</TrimmerSingleWarn>
            </ManagedAssemblyToLink>
        </ItemGroup>
    </Target>
</Project>
```

```console
dotnet publish
```

Stack trace from the output:
```
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.TypeReferenceWalker.WalkMethodReference(MethodReference mr)
     at Mono.Linker.TypeReferenceWalker.WalkTypeScope(MethodBody body)
     at Mono.Linker.TypeReferenceWalker.WalkScopes(TypeDefinition typeDefinition)
     at Mono.Linker.TypeReferenceWalker.Process()
     at Mono.Linker.Steps.MarkStep.TypeReferenceMarker.MarkTypeReferences(AssemblyDefinition assembly, MarkingHelpers m
  arkingHelpers)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkFullyPreservedAssemblies()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

/cc @LakshanF

**Comment by vitek-karas** [comment]
This fails on `UmbraCare.Core.dll` which is an obfuscated assembly and it contains things like call instructions to non-existing tokens. There's no point trying to support trimming this assembly.
