### ISSUE TITLE
Test failure System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Invalid

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#94498]
**Failed in:** [runtime-coreclr libraries-jitstress 20231106.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461683&view=ms.vss-test-web.build-test-results-tab&runId=10438344&resultId=129054&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.11.Arm64.Open
    - System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Invalid
```

**Error message:**
```
Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InvalidOperationException)
```

**Stack trace:**
```
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Invalid() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 145
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20240525.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687420&view=ms.vss-test-web.build-test-results-tab&runId=17066804&resultId=174845&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-jitstress2_jitstressregs0x80-Ubuntu.2204.Amd64.Open
    - System.Numerics.Tensors.Tests.Int16GenericTensorPrimitives.SumOfMagnitudes_MinValue_Throws
    - System.Numerics.Tensors.Tests.Int16GenericTensorPrimitives.SumOfMagnitudes_MinValue_Throws
net9.0-windows-Release-x64-jitstress2_jitstressregs0x80-Windows.10.Amd64.Open
    - System.Numerics.Tensors.Tests.Int16GenericTensorPrimitives.SumOfMagnitudes_MinValue_Throws
    - System.Numerics.Tensors.Tests.Int16GenericTensorPrimitives.SumOfMagnitudes_MinValue_Throws
```

**Error message:**
```
 Assert.All() Failure: 1 out of 256 items in the collection did not pass.
[7]: Item:  8
     Error: Assert.Throws() Failure: No exception was thrown
            Expected: typeof(System.OverflowException)
```

**Stack trace:**
```
   at System.Numerics.Tensors.Tests.GenericSignedIntegerTensorPrimitivesTests`1.SumOfMagnitudes_MinValue_Throws() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitives.Generic.cs:line 1623
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by danmoseley** [comment]
- Hit counts: 0 in the last 24 hours, 7 days, and 1 month
 - Last comment: Nov 8, 2023 (just the area-subscription bot)
 - Last human activity: Aug 6, 2024 — ericstj re-milestoned it to "Future" and added needs-further-triage
 - State: Still OPEN, but no reproduction in over 2 years

The test (PerformanceCounterCategory_Create_Invalid) failed once on ARM64 JitStress in Nov 2023 and was never seen again. It's a stale "Known Build Error" that nobody closed. Looks like a safe candidate to close.
