### ISSUE TITLE
[7.0] Assertion failed in System.Net.Http.Json.Functional.Tests in ThreadPoolBoundHandle.BindHandleCore in ThreadPoolBoundHandle.Windows.cs:line 14

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#94491]
@dotnet/ncl there's a failed assertion in the branding PR for 7.0.15: https://github.com/dotnet/runtime/pull/94483

The failure message is too generic to create a Known Build Issue (feel free to make one though if you can find a proper string).

- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=462339&view=results
- Queue: `Libraries Test Run checked coreclr windows x86 Debug`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=462339&view=logs&j=215a953c-1e4b-5cc0-95e2-5484aabbe659&t=312e0115-80c6-5d8d-a731-029b3098bcf6&l=58
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-94483-merge-680efdc5274741ed9c/System.Net.Http.Json.Functional.Tests/1/console.b0ca3e21.log?helixlogtype=result
- Output:
```
C:\h\w\AF7F0982\w\A0FD0900\e>"C:\h\w\AF7F0982\p\dotnet.exe" exec --runtimeconfig System.Net.Http.Json.Functional.Tests.runtimeconfig.json --depsfile System.Net.Http.Json.Functional.Tests.deps.json xunit.console.dll System.Net.Http.Json.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Net.Http.Json.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.Json.Functional.Tests (found 43 test cases)
  Starting:    System.Net.Http.Json.Functional.Tests (parallel test collections = on, max threads = 4)
Process terminated. Assertion failed.
   at System.Threading.ThreadPoolBoundHandle.BindHandleCore(SafeHandle handle) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.Windows.cs:line 14
   at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.cs:line 81
   at System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(Boolean trySkipCompletionPortOnSuccess) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.Windows.cs:line 57
   at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandleSlow() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs:line 437
   at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandle() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs:line 428
   at System.Net.Sockets.SocketAsyncEventArgs.AllocateNativeOverlapped() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs:line 104
   at System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept(Socket socket, SafeSocketHandle handle, SafeSocketHandle acceptHandle, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Windows.cs:line 261
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 2639
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(Socket socket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1012
   at System.Net.Sockets.Socket.AcceptAsync(Socket acceptSocket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 70
   at System.Net.Sockets.Socket.AcceptAsync() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 32
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 136
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Test.Common.LoopbackServer.EstablishConnectionAsync()
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 159
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync)
   at System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.<>c__DisplayClass13_2.<<GetFromJsonAsync_EnforcesTimeout>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http.Json/tests/FunctionalTests/HttpClientJsonExtensionsTests.cs:line 430
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.<>c__DisplayClass13_2.<GetFromJsonAsync_EnforcesTimeout>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 503
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2387
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2349
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2283
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2274
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 919
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 121
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
----- end Tue 11/07/2023 20:03:14.33 ----- exit code -2146232797 ----------------------------------------------------------
```

**Comment by wfurt** [comment]
This does not look like networking issue to me as it fail in CoreLib. By quick look it seems like there is check that handle is not Closed and then we go to BindHandleCore where the same assert fails. W may do something in `Socket` but I don't know if that is right approach. 
Any thoughts on this @stephentoub 

and HTTP is probably wrong area .... even if the failure was in JSON test suite.

**Comment by karelz** [comment]
Happened only once, does not impact customers. Closing.
If it happens more often, we should reopen.
