### ISSUE TITLE
[8.0] System.Net.Quic.QuicException : The connection timed out from inactivity.

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#94539]
### Error Blob

```json
{
  "ErrorMessage": "System.Net.Quic.QuicException : The connection timed out from inactivity.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

@dotnet/ncl Opening an issue for the Quic failure. I'm seeing it in multiple PRs, so I want to have it tagged with "Known Build Error" to know the exact impact.

- Example of affected PR: https://github.com/dotnet/runtime/pull/93919
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=455782&view=results
- Queue: `Libraries Test Run checked coreclr linux_musl arm Release`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=455782&view=logs&j=fd49b2ea-3ee3-5298-d793-bdb9fd631e7e&t=26d44400-a1b8-5ed1-d719-0cc35b38251b&l=55
- Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-93919-merge-2a4b74e375ac4cbf89/System.Net.Quic.Functional.Tests/1/console.ffffbf3a.log?helixlogtype=result
<details><summary>Output example (expand)</summary>

```
----- start Mon Oct 30 21:58:42 UTC 2023 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
MsQuic supported and using 'libmsquic.so 2.3.0.0 (7ea0e2e640008ad5c86d8d31e0cd186399b6b404)'.
  Discovered:  System.Net.Quic.Functional.Tests (found 124 of 134 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
    System.Net.Quic.Tests.MsQuicCipherSuitesPolicyTests.SupportedCipher_Success [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicCipherSuitesPolicyTests.cs(35,0): at System.Net.Quic.Tests.MsQuicCipherSuitesPolicyTests.TestConnection(CipherSuitesPolicy serverPolicy, CipherSuitesPolicy clientPolicy)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicCipherSuitesPolicyTests.cs(37,0): at System.Net.Quic.Tests.MsQuicCipherSuitesPolicyTests.TestConnection(CipherSuitesPolicy serverPolicy, CipherSuitesPolicy clientPolicy)
        --- End of stack trace from previous location ---
    System.Net.Quic.Tests.MsQuicTests.Read_ReadsCompleted_ReportedBeforeReturning0 [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(214,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(245,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(291,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(289,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(334,0): at System.Net.Quic.Tests.QuicTestBase.RunStreamClientServer(Func`2 clientFunction, Func`2 serverFunction, Boolean bidi, Int32 iterations, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(1298,0): at System.Net.Quic.Tests.MsQuicTests.Read_ReadsCompleted_ReportedBeforeReturning0()
        --- End of stack trace from previous location ---
    System.Net.Quic.Tests.MsQuicTests.BasicTest_WithReadsCompletedCheck [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(214,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(245,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(291,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(289,0): at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(1262,0): at System.Net.Quic.Tests.MsQuicTests.BasicTest_WithReadsCompletedCheck()
        --- End of stack trace from previous location ---
    System.Net.Quic.Tests.MsQuicTests.CloseAsync_ByServer_AcceptThrows [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(214,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(245,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(945,0): at System.Net.Quic.Tests.MsQuicTests.CloseAsync_ByServer_AcceptThrows()
        --- End of stack trace from previous location ---
    System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(ipString: "127.0.0.1", expectsError: True) [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(214,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(245,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(183,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(183,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(592,0): at System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(String ipString, Boolean expectsError)
        --- End of stack trace from previous location ---
    System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(ipString: "::1", expectsError: True) [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(214,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(245,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(183,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(183,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(592,0): at System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(String ipString, Boolean expectsError)
        --- End of stack trace from previous location ---
    System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(ipString: "127.0.0.1", expectsError: False) [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(538,0): at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(572,0): at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs(176,0): at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(322,0): at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(79,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(84,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(214,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(245,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListener listener)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(183,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(183,0): at System.Net.Quic.Tests.QuicTestBase.CreateConnectedQuicConnection(QuicClientConnectionOptions clientOptions, QuicListenerOptions listenerOptions)
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs(592,0): at System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForLoopbackIP_IndicatesExpectedError(String ipString, Boolean expectsError)
        --- End of stack trace from previous location ---
...
...
...
```
</details>

**Comment by carlossanlop** [comment]
@dotnet/ncl I just noticed you already have two different issues tracking two variants of this failure. They _might_ be the exact same problem, but a different string was used for the KnownBuildError. Can you please confirm you only need one and close the other as duplicate?

- https://github.com/dotnet/runtime/issues/86019
- https://github.com/dotnet/runtime/issues/91757

I'll close this one as duplicate too.

**Comment by carlossanlop** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/91757
