### ISSUE TITLE
Wasm.Build.Tests.WasmNativeDefaultsTests.DefaultsWithPublish failing

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#94926]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=473142
Build error leg or test failing: Wasm.Build.Tests.WasmNativeDefaultsTests.DefaultsWithPublish
Pull request: https://github.com/dotnet/runtime/pull/94875

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "    Wasm\.Build\.Tests\.WasmNativeDefaultsTests\.DefaultsWithPublish\(config: ""Debug"", extraProperties: ""<WasmEnableExceptionHandling>True<\/WasmEnableExcep""···, aot: False, expectWasmBuildNativeForBuild: False, expectWasmBuildNativeForPublish: False\) \[FAIL\]
      Assert\.Contains\(\) Failure: Sub-string not found
      String:    ""\[\] MSBuild version 17\.9\.0-preview-23557-0""···
      Not found: ""Stopping the build""",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Console:
```
    Wasm.Build.Tests.WasmNativeDefaultsTests.DefaultsWithPublish(config: "Debug", extraProperties: "<WasmEnableExceptionHandling>True</WasmEnableExcep"···, aot: False, expectWasmBuildNativeForBuild: False, expectWasmBuildNativeForPublish: False) [FAIL]
      Assert.Contains() Failure: Sub-string not found
      String:    "[] MSBuild version 17.9.0-preview-23557-0"···
      Not found: "Stopping the build"
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/WasmNativeDefaultsTests.cs(125,0): at Wasm.Build.Tests.WasmNativeDefaultsTests.DefaultsWithPublish(String config, String extraProperties, Boolean aot, Boolean expectWasmBuildNativeForBuild, Boolean expectWasmBuildNativeForPublish)
           at InvokeStub_WasmNativeDefaultsTests.DefaultsWithPublish(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Output:
        
        ** -------- publish -------- **
        
        Binlog path: /root/helix/work/workitem/uploads/xharness-output/logs/cn45biap_dor/cn45biap_dor-publish.binlog
        [] Executing (Captured Output) - /root/helix/work/workitem/e/dotnet-latest/dotnet publish -bl:/root/helix/work/workitem/uploads/xharness-output/logs/cn45biap_dor/cn45biap_dor-publish.binlog -p:Configuration=Debug -nr:false   -  in pwd /root/helix/work/workitem/e/wbt/cn45biap_dor
        	[DOTNET_ROOT] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_INSTALL_DIR] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /root/helix/work/workitem/e/dotnet-latest:./dotnet-latest:/__w/1/s/artifacts/bin/chromedriver/chromedriver_linux64:/root/helix/work/correlation/dotnet-latest:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        	[WasmEnableWebCil] = false
        	[NUGET_PACKAGES] = /root/helix/work/workitem/e/wbt/nuget/cn45biap_dor
        	[ForceNet8Current] = false
        [] MSBuild version 17.9.0-preview-23557-02+5d1509792 for .NET
        []   Determining projects to restore...
        []   Restored /root/helix/work/workitem/e/wbt/cn45biap_dor/native_defaults_publish.csproj (in 635 ms).
        [] /root/helix/work/workitem/e/dotnet-latest/sdk/9.0.100-alpha.1.23564.26/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/helix/work/workitem/e/wbt/cn45biap_dor/native_defaults_publish.csproj]
        []   native_defaults_publish -> /root/helix/work/workitem/e/wbt/cn45biap_dor/bin/Debug/net9.0/browser-wasm/native_defaults_publish.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/9.0.0-ci'
        []   Optimizing assemblies for size. This process might take a while.
        []   native_defaults_publish -> /root/helix/work/workitem/e/wbt/cn45biap_dor/bin/Debug/net9.0/browser-wasm/publish/
        []   native_defaults_publish -> /root/helix/work/workitem/e/wbt/cn45biap_dor/bin/Debug/net9.0/browser-wasm/native_defaults_publish.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/9.0.0-ci'
        []   native_defaults_publish -> /root/helix/work/workitem/e/wbt/cn45biap_dor/bin/Debug/net9.0/browser-wasm/publish/
        []   ** WasmBuildNative: 'false', WasmNativeStrip: 'true', WasmBuildingForNestedPublish: 'true'
        [] /root/helix/work/workitem/e/wbt/cn45biap_dor/native_defaults_publish.csproj(15,17): error : Stopping the build
        [] 
        [] Workload updates are available. Run `dotnet workload list` for more information.
```

**Comment by radical** [comment]
@jtschuster jfyi, `ErrorPattern` does not support regex spanning multiple lines.

**Comment by radical** [comment]
The output does have:
```
        [] /root/helix/work/workitem/e/wbt/cn45biap_dor/native_defaults_publish.csproj(15,17): error : Stopping the build
        [] 
        [] Workload updates are available. Run `dotnet workload list` for more information.
```

.. so the output string might be missing the last few lines.
TODO: Change the assertion so we print the last few lines for this failure, which should help confirm this.

**Comment by pavelsavara** [comment]
This issue seems to be stale, closing. Please re-open if you see it again
