### ISSUE TITLE
[WASM] Jiterpreter crash using `System.Text.JSON` and `WasmNativeStrip` usage.

### ISSUE THREAD

**Issue by nickwinder** [dotnet/runtime#94939]
### Description

Crash in the Jiterpreter using `System.Text.JSON` serialization or deserialization when native WASM is stripped or a high Emscripten optimization level is chosen. 

Setting `WasmNativeStrip` to `false` rectifies the issue, so it seems the strip command is too aggressive, or is disobeying the `EMSCRIPTEN_KEEP_ALIVE` annotation on the `mono_wasm_copy_managed_pointer` symbol. 

### Reproduction Steps

Minimal repo highlighting the issue can be found at https://github.com/nickwinder/dotnet-8-webassembly-bug

Basically, use `System.Text.JSON` using `WasmNativeStrip` and Emscripten optimization of `O3`. 

I've found other mixtures of settings cause the same issue, but this was the simplest and easiest to reproduce. 

### Expected behavior

Calling `System.Text.JSON` serialization/deserialization should not crash, even when native binary is stripped, or highly optimized. 

### Actual behavior

Crashes with the following error log. 

```
raw cwrap mono_wasm_copy_managed_pointer not found

      at Ja (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/jiterpreter-support.ts:1862:15)
      at Ja (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/jiterpreter.ts:264:31)
      at $i (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/jiterpreter.ts:703:26)
      at ../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/jiterpreter.ts:736:9
      at Ul (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/jiterpreter.ts:1049:19)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:322624)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1589606)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1548333)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:791465)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:122212)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:85466)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:66234)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:301784)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1589606)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1548333)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:791465)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:122212)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:85466)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:241702)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:791302)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:324116)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1589606)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1548333)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:791465)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:122212)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:622449)
      at null.<anonymous> (wasm:/wasm/00a3bc76:1:1525334)
      at Object.apply [as mono_wasm_invoke_method_bound] (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/dotnet.native.js:8:96257)
      at mono_wasm_invoke_method_bound (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/invoke-cs.ts:273:29)
      at Object.kr (../WasmStripBug/WasmStripBug/bin/Release/net8.0/browser-wasm/AppBundle/https:/raw.githubusercontent.com/dotnet/runtime/5535e31a712343a63f5d7d796cd874e563e5ac14/src/mono/wasm/runtime/invoke-cs.ts:184:13)
      at Object.DoSomething (tests/init-test.js:5:40)
  ```

### Regression?

.NET7 still allows this combination of optimization and features. 

### Configuration

.NET8
Env : Chrome browser (likely others) and Node.js environments. 
Arch : WASM

**Comment by radical** [comment]
cc @kg

**Comment by kg** [comment]
Hi,
Thanks for the report! The good news is that this isn't formally a crash, and is instead a compatibility issue with emscripten's optimizer where the function we're looking for is getting renamed. So while we work on a long-term fix, it should be safe and reliable to use a workaround like the one you've come up with (disabling NativeStrip) or a different suitable workaround. An optimization level of 1 would also prevent this renaming from happening (O2 and O3 enable it), I believe. You could also try passing `-s ASSERTIONS=1` to the linker, but I haven't tested it myself - just a guess from reading emscripten's source code.

**Comment by nickwinder** [comment]
Thanks @kg. The issue with all the workaround is that they all produce huge binaries, so it's not usable in production. 
If there are any lower level workarounds which don't involved manipulating the stripping/optimization I'd love to explore them. But as of now, I wasn't able to find one. 
Thanks

**Comment by kg** [comment]
Try adding `-lexports.js` to your `EmccLinkOptimizationFlag` and see what happens

**Comment by nickwinder** [comment]
Awesome that does the trick! Thanks so much.
