### ISSUE TITLE
System.Net.Security is not supported on this platform

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#94980]
I was trying to use `HttpClient` with an `https` endpoint.

We should resolve this or provide guidance in the message on the alternative. HTTPS is pretty common.

```bash
Unhandled Exception:
System.PlatformNotSupportedException: System.Net.Security is not supported on this platform.
   at System.Net.Security.SslClientAuthenticationOptions..ctor()
   at System.Net.Http.SocketsHttpHandler.get_SslOptions()
   at System.Net.Http.HttpClientHandler.ThrowForModifiedManagedSslOptionsIfStarted()
   at System.Net.Http.HttpClientHandler.set_ClientCertificateOptions(ClientCertificateOption value)
   at System.Net.Http.HttpClientHandler..ctor()
   at System.Net.Http.HttpClient..ctor()
```

**Comment by lewing** [comment]
The long term plan here would be to implement a platform abstraction for System.Net.Security that wrapped  https://github.com/WebAssembly/wasi-crypto in its final form. There are also other options available for technology demonstrations/non-shipping code.
