### ISSUE TITLE
[wasm] MonoProxy throws System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by dlemstra** [dotnet/runtime#95019]
### Description

While debugging with the `Microsoft.AspNetCore.Components.WebAssembly.DevServer` library  I sometimes get the following exception inside the method `OnSourceFileAdded` of the `MonoProxy` class:

```
fail: DevToolsProxy[0]
      failed: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
         at Microsoft.WebAssembly.Diagnostics.MonoProxy.OnSourceFileAdded(SessionId sessionId, SourceFile source, ExecutionContext context, CancellationToken token, Boolean resolveBreakpoints)
         at Microsoft.WebAssembly.Diagnostics.MonoProxy.LoadStore(SessionId sessionId, Boolean tryUseDebuggerProtocol, CancellationToken token)
         at Microsoft.WebAssembly.Diagnostics.MonoProxy.LoadStore(SessionId sessionId, Boolean tryUseDebuggerProtocol, CancellationToken token)
```

### Reproduction Steps

It looks like the exception is happening on this line: https://github.com/dotnet/runtime/blob/57e08256987dc48e2c2575c6c38bd96c75f5dc6d/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L1594 But I was unable to figure out what is causing this. 

But I did find a similar issue inside the `ResetBreakpoint` method: https://github.com/dotnet/runtime/blob/57e08256987dc48e2c2575c6c38bd96c75f5dc6d/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L1726 There is a call to `RemoveBreakpoint` on line 1740: https://github.com/dotnet/runtime/blob/57e08256987dc48e2c2575c6c38bd96c75f5dc6d/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L1740 That can change the values of the dictionary: https://github.com/dotnet/runtime/blob/57e08256987dc48e2c2575c6c38bd96c75f5dc6d/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L1770

Maybe the values should first be copied to a list?

### Expected behavior

`System.InvalidOperationException` is not thrown.

### Actual behavior

`System.InvalidOperationException` is thrown.

### Known Workarounds

Removing the `--user-data-dir` clears all the breakpoints and that seems to fix the issue.

### Configuration

```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.8d38d0cc
```

Version `8.0.0` of `Microsoft.AspNetCore.Components.WebAssembly.DevServer`.

**Comment by mistachkin** [comment]
I'm seeing what appears to be a very similar problem within the generic Dictionary class as well.  However, in my case, the exception does not happen every single time the code is executed.  I'm starting to suspect it is related to memory pressure on the host system.  Here is the my stack trace:

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Eagle._Containers.Public.VariableDictionary.MaybeCopyFrom(Interpreter interpreter, IDictionary`2 dictionary, CloneFlags flags, Result& error) in Eagle\Library\Containers\Public\VariableDictionary.cs:line 132
   at Eagle._Containers.Public.VariableDictionary.Create(Interpreter interpreter, IDictionary`2 oldDictionary, CloneFlags flags, Result& error) in Eagle\Library\Containers\Public\VariableDictionary.cs:line 75
   at Eagle._Components.Private.CallFrameOps.CloneToNewScope(Interpreter interpreter, String name, Boolean global, Boolean byRef, VariableDictionary& newVariables, ICallFrame& newFrame, Boolean& created, Result& error) in Eagle\Library\Components\Private\CallFrameOps.cs:line 662
   at Eagle._Commands.Scope.Execute(Interpreter interpreter, IClientData clientData, ArgumentList arguments, Result& result) in Eagle\Library\Commands\Scope.cs:line 409
   at Eagle._Wrappers.Command.Execute(Interpreter interpreter, IClientData clientData, ArgumentList arguments, Result& result) in Eagle\Library\Wrappers\Command.cs:line 184
   at Eagle._Components.Public.Engine.PrivateExecuteCommand(ICommand command, Interpreter interpreter, IClientData clientData, ArgumentList arguments, EngineFlags engineFlags, SubstitutionFlags substitutionFlags, EventFlags eventFlags, ExpressionFlags expressionFlags, Int32 executeResultLimit, Boolean& usable, Boolean& exception, Result& result) in Eagle\Library\Components\Public\Engine.cs:line 8605
```

**Comment by thaystg** [comment]
This is fixed.
