### ISSUE TITLE
Linux: Segfault in strlen running helloworld.cs

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#95070]
### Description

With recent HEAD, running a simple C# program in dotnet causes a segfault.

### Reproduction Steps

```
$ git reset --hard 7f425d9c4bb
$ ./build.sh -rc checked -lc release -s clr+libs
$ ./src/tests/build.sh generatelayoutonly Checked
$ export CORE_ROOT=/home/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root
$ corerun ./bin/Release/net7.0/linux-arm64/helloworld.dll
[1]    3799154 segmentation fault (core dumped)  $CORE_ROOT/corerun ./bin/Release/net7.0/linux-arm64/helloworld.dll
```

### Expected behavior

Simple C# program should run

### Actual behavior

Segfault

Arm64:
```
$ gdb --args $CORE_ROOT/corerun ./bin/Release/net7.0/linux-arm64/helloworld.dll
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun...
(gdb) r
Starting program: /home/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun ./bin/Release/net7.0/linux-arm64/helloworld.dll
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xfffff6faf100 (LWP 3798790)]
[New Thread 0xfffff679f100 (LWP 3798791)]
[New Thread 0xfffff5f8f100 (LWP 3798792)]
[New Thread 0xfffff577f100 (LWP 3798793)]
[New Thread 0xfffff4f5f100 (LWP 3798794)]
[New Thread 0xffff9ffff100 (LWP 3798795)]
[New Thread 0xffff9f7ef100 (LWP 3798796)]
[New Thread 0xffff9db24100 (LWP 3798797)]
[New Thread 0xffff9c88f100 (LWP 3798803)]

Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
__strlen_mte () at ../sysdeps/aarch64/multiarch/../strlen.S:60
60	../sysdeps/aarch64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_mte () at ../sysdeps/aarch64/multiarch/../strlen.S:60
#1  0x0000fffff7b90514 in __GI___strdup (s=0x1 <error: Cannot access memory at address 0x1>) at ./string/strdup.c:41
#2  0x0000fffff41b9038 in SystemNative_SetKeypadXmit ()
   from /home/alahay01/dotnet/examples/helloworld/bin/Release/net7.0/linux-arm64/libSystem.Native.so
#3  0x0000ffffa986e0bc in ?? ()
#4  0x0000ffffa98661bc in ?? ()
#5  0x0000ffffa9866060 in ?? ()
#6  0x0000ffffffffd1c0 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

X86:
```
$ gdb --args $CORE_ROOT/corerun ./bin/Release/net7.0/linux-x64/conditional.dll
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /data_sdb/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun...
(gdb) r
Starting program: /data_sdb/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/linux.x64.Checked/Tests/Core_Root/corerun ./bin/Release/net7.0/linux-x64/conditional.dll
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6dff640 (LWP 434237)]
[New Thread 0x7ffff65fe640 (LWP 434238)]
[New Thread 0x7ffff5dfd640 (LWP 434239)]
[New Thread 0x7ffff55fc640 (LWP 434240)]
[New Thread 0x7ffff4ddf640 (LWP 434241)]
[New Thread 0x7fffe7fff640 (LWP 434242)]
[New Thread 0x7fffe77fe640 (LWP 434243)]
[New Thread 0x7fff769ff640 (LWP 434244)]
[New Thread 0x7fff757ff640 (LWP 434245)]

Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
__strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
77	../sysdeps/x86_64/multiarch/strlen-evex.S: No such file or directory.
Breakpoint 1 at 0x7ffff79b22bc: file ../sysdeps/x86_64/multiarch/strlen-evex.S, line 77.
(gdb) bt
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#1  0x00007ffff78a8583 in __GI___strdup (s=0x1 <error: Cannot access memory at address 0x1>) at ./string/strdup.c:41
#2  0x00007ffff4096343 in SystemNative_SetKeypadXmit ()
   from /data_sdb/alahay01/dotnet/examples/conditional/bin/Release/net7.0/linux-x64/libSystem.Native.so
#3  0x00007fff794abc26 in ?? ()
#4  0x003d1b68313f5b1b in ?? ()
#5  0x00007fbf6a815ca0 in ?? ()
#6  0x0000000000000000 in ?? ()
(gdb)
``

### Regression?

Yes

### Known Workarounds

None

### Configuration

Arm64
Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-72-generic aarch64)
Ampere Altra

X86
Ubuntu 22.04.3 LTS


### Other information

_No response_

**Comment by a74nh** [comment]
Currently figuring out when this broke for me

**Comment by a74nh** [comment]
Looks like this is because I was targeting .NET7
```
<TargetFramework>net7.0</TargetFramework>
```

Should I still be able to run .NET7 using .NET8 ?

**Comment by EgorBo** [comment]
@a74nh I assume you built a net7.0 app and copied your local .NET 8.0 runtime bits there?
If so, that is a fragile scenario, not guaranteed to work even for the same TFM sometimes.

**Comment by a74nh** [comment]
> @a74nh I assume you built a net7.0 app and copied your local .NET 8.0 runtime bits there? If so, that is a fragile scenario, not guaranteed to work even for the same TFM sometimes.

Yes. Ok, will close this then.
