### ISSUE TITLE
Authentication - An extended error has occurred.

### ISSUE THREAD

**Issue by PLibardi** [dotnet/runtime#95214]
### Description

Trying to authenticate to Local Account I got this error "An extended error has occurred."
This happens only on 1 VM while all others systems work fine!

following is the call stack (bottom to top):

System.DirectoryServices.AccountManagement.PrincipalOperationException: An extended error has occurred.
 ---> System.Runtime.InteropServices.COMException: An extended error has occurred.
   at System.DirectoryServices.AccountManagement.UnsafeNativeMethods.IADs.Get(String bstrName)
   at System.DirectoryServices.AccountManagement.CredentialValidator.BindSam(String target, String userName, String password)

### Reproduction Steps

Execute a call by the following code:

```
using (PrincipalContext ctx = new PrincipalContext(ContextType.Machine))
                {
                    UserPrincipal up = UserPrincipal.FindByIdentity(ctx, IdentityType.SamAccountName, username);
                    if (up != null) // user exists
                    {
                        if (ctx.ValidateCredentials(username, password))
                        {
                            result.User = username;
                        }
                        else
                        {
                            result.User = null;
                        }
                    }
                }
```

### Expected behavior

Authentication to succeed/fail based on username/password as it happens on all other VMs that I am using

### Actual behavior

the authentication always fail even if username/password are correct because the application catches an exception while validating the data

### Known Workarounds

Unfortunately neither the reboot of the VM resolves the issue.

**Comment by PLibardi** [comment]
I found that users flags were set to both “User must change password at next logon” and “User cannot change password”.
These 2 flags are in conflict. I still have to find how it has been possible to set both of them
Just removing “User must change password at next logon” made our system to properly authenticate the users,
