### ISSUE TITLE
Mono Windows x86: possible CompareExchange issue causes failures in System.Diagnostics.DiagnosticSource.Tests

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#95210]
Repro steps:

```
.\build.cmd mono+libs -c Release -arch x86
.\dotnet.cmd build /t:Test /p:RuntimeFlavor=mono /p:TargetArchitecture=x86 /p:TestScope=outerloop -c Release .\src\libraries\System.Diagnostics.DiagnosticSource\tests\ -f net9.0
```

This will result in a bunch of test failures like this one:

```
System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceWorksWithSequentialListeners [FAIL]
  Assert.Equal() Failure: Strings differ
               (pos 0)
  Expected: "10"
  Actual:   "0"
               (pos 0)
  Stack Trace:
          C:\dev\runtime\src\libraries\System.Diagnostics.DiagnosticSource\tests\MetricEventSourceTests.cs(1621,0): at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.AssertGenericCounterEventsPresent(String eventName, EventWrittenEventArgs[] events, String meterName, String instrumentName, String tags, String expectedUnit, ValueTuple`2[] expected)
          C:\dev\runtime\src\libraries\System.Diagnostics.DiagnosticSource\tests\MetricEventSourceTests.cs(1592,0): at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.AssertCounterEventsPresent(EventWrittenEventArgs[] events, String meterName, String instrumentName, String tags, String expectedUnit, ValueTuple`2[] expected)
          C:\dev\runtime\src\libraries\System.Diagnostics.DiagnosticSource\tests\MetricEventSourceTests.cs(1366,0): at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceWorksWithSequentialListeners()
          C:\dev\runtime\src\mono\System.Private.CoreLib\src\System\Reflection\MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
          C:\dev\runtime\src\libraries\System.Private.CoreLib\src\System\Reflection\MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by akoeplinger** [comment]
Looks like I don't see this when reverting https://github.com/dotnet/runtime/pull/91566 so might be related to interlocked exchange on doubles and maybe it just exposes an underlying issue.

**Comment by MichalPetryka** [comment]
> Looks like I don't see this when reverting #91566 so might be related to interlocked exchange on doubles and maybe it just exposes an underlying issue.

Maybe something with CompareExchange comparing doubles bitwise and not with normal FP equality?

**Comment by ericstj** [comment]
@stephentoub can you have a look at this?  @akoeplinger was calling out your change https://github.com/dotnet/runtime/pull/91566 as introducing this regression.

**Comment by stephentoub** [comment]
> and maybe it just exposes an underlying issue.

That would be my guess... there are only two src uses of Interlocked.CompareExchange on doubles in the whole repo, and this one gets much more stressed than the other. My guess is a mono bug in CompareExchange.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/blob/bfffd58eeb204d368989038a19786bff86000b19/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventCounter.cs#L154
