### ISSUE TITLE
AndroidMessageHandler or HttpClientHandler throw System.ObjectDisposedException: Cannot access a closed Stream

### ISSUE THREAD

**Issue by PontiacGTX** [dotnet/runtime#95658]
### Description

I am trying to do a local http post request from a http client but whenever I tried overriding to check the signed certificate by giving a HttpClientHandler or AndroidMessageHandler  ot the http client, it ends up throwing an exception when I call to PostAsync method

### Steps to Reproduce

Create a Maui Project
On Program Add a HttpClient to the DI container

```c#
#if DEBUG
	     var httpHelper = new HttpClientHandlerHelper();

	     var insecureHandler =new CustomAndroidMessageHandler();//httpHelper.GetInsecureHandler()
        builder.Services.AddSingleton<HttpClient>(x=> new HttpClient(httpHelper.GetInsecureHandler(), false));

#else
		builder.Services.AddSingleton<HttpClient>();
#endif

declare a class to get the http client handler

HttpClientHandlerHelper



  public class HttpClientHandlerHelper:IDisposable
    {
        private bool disposedValue;

        public HttpClientHandler GetInsecureHandler()
        {
            HttpClientHandler handler = new HttpClientHandler();
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
            {
               
                return true;
            };
            return handler;
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    // TODO: eliminar el estado administrado (objetos administrados)
                }

                // TODO: liberar los recursos no administrados (objetos no administrados) y reemplazar el finalizador
                // TODO: establecer los campos grandes como NULL
                disposedValue = true;
            }
        }

      
        public void Dispose()
        {
            // No cambie este código. Coloque el código de limpieza en el método "Dispose(bool disposing)".
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
    }
```

make some service using this HttpClient by DI and then call a method using PostAsync, but in the url the base url should contain
the local ip in my case is like, while calling a webapi running 

http://192.168.250.3:5000/api/Account/Create

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30 Android 11, WIndows 10 1709

### Did you find any workaround?

Not yet

### Relevant log output

```shell
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.get_Length()
   at System.Net.Http.HttpContent.GetComputedOrBufferLength()
   at System.Net.Http.Headers.HttpContentHeaders.get_ContentLength()
   at Xamarin.Android.Net.AndroidMessageHandler.SetupRequestBody(HttpURLConnection httpConnection, HttpRequestMessage request) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 1132
   at Xamarin.Android.Net.AndroidMessageHandler.SetupRequestInternal(HttpRequestMessage request, URLConnection conn) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 984
   at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 374
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MauiChat.Common.Services.ChatServicesService.CreateUser(String phoneNumber) in C:\Users\PontiacGTX\Source\Repos\MauiChat\Common\Services\ChatServicesService.cs:line 38}
```

**Comment by wfurt** [comment]
AFAIK `HttpClientHandler` will use platform handler if you target Maui. You would need to use `SocketsHttphandler` explicitly if you want to use the managed implementation.

cc: @simonrozsival  for more comments.

**Comment by simonrozsival** [comment]
@wfurt Yes, the native handler is used by default (in case of Android that is `AndroidMessageHandler`). It's possible to either create `SocketsHttpHandler` manually and pass it to `HttpClient` or the developer can add `<UseNativeHttpHandler>false</UseNativeHttpHandler>` to change the default behavior.

The original issue used `ServerCertificateCustomValidationCallback` in .NET 6. At that time this functionality wasn't properly implemented in either the native nor the managed HTTP handlers. The native handler supports the validation callback since .NET 7 and the managed one since .NET 8.

@arahmancsd I'm surprised there is a difference between .NET 7 and .NET 8 RC1. Have you tried again with the final release of .NET 8? Can you still reproduce the issue?
